### ISSUE TITLE
Unable to install apk through Appium

### ISSUE THREAD

**Issue by Srutherford2407** [appium/appium#10033]
I am attempting to use Appium to automate some mobile test. I went through some how to video's and got everything working on my machine. However, when I added the information for the app I need to automate it fails.

Appium v1.7.2
Mac
Android virtual device: Pixel 2
Mobile Version: 8.0

## Details
Screencast of error in Appium: https://screencast.com/t/I3F0OEzIp1LF

## Link to Appium logs
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/stevenrutherford/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","am","force-stop","com.foodlogiq.connect"]
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Removing forwarded port socket connection: 8200 
[debug] [ADB] Running '/Users/stevenrutherford/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","forward","--remove","tcp:8200"]
[error] [MJSONWP] Encountered internal error running command: Error: Error executing adbExec. Original error: 'Command '/Users/stevenrutherford/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell pm install -r /data/local/tmp/c7fb40980d2df250663e798d838abb50.apk' exited with code 1'; Stderr: 'Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]'; Code: '1'
    at ADB.execFunc$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-adb/lib/tools/system-calls.js:321:13)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
[info] [HTTP] <-- POST /wd/hub/session 500 23961 ms - 479

**Comment by mykola-mokhnach** [comment]
https://stackoverflow.com/questions/24572052/install-failed-no-matching-abis-when-install-apk

Closed as non Appium-related.
