### ISSUE TITLE
Appium session fails to start

### ISSUE THREAD

**Issue by Dipanjan1** [appium/appium#10049]
Appium session failing to start. Says JAVA_HOME is not set, though it is set. Appreciate if anyone could help me out with the problem.

I am using macOS Sierra version 10.12.6

Screenshot of the error attached and .bash_profile as below:

export PATH="/Users/u2015188/Library/Android/sdk/paltform-tools":"/usr/local/bin/adb":"/Library/Java/Home/bin":"/Users/u205188/Library/Android/sdk":"$JAVA_8_HOME":$PATH
eval "$(jenv init -)"
export JAVA_HOME="$JAVA_8_HOME"
export ANDROID_SDK_ROOT="/usr/local/share/android-sdk"
export ANDROID_NDK_HOME="/usr/local/share/android-ndk"
export JAVA_HOME="/Library/Java/Home"
export ANDROID_HOME="/Users/u205188/Library/Android/sdk"

<img width="919" alt="screen shot 2018-01-21 at 9 12 54 am" src="https://user-images.githubusercontent.com/30587787/35188927-d752aab2-fe8b-11e7-997f-215bff03b97f.png">

**Comment by mykola-mokhnach** [comment]
Please attach the necessary info along with server logs. You can check which environment variables are set for the particular process by executing `ps -wwE -p <PID>` command. See http://chwalisz.org/2013/01/25/osx-show-environment-vars-of-a-running-process/ for more details.

**Comment by Dipanjan1** [comment]
@mykola-mokhnach 

This what I get on ps -wwE -p <PID>

PID 	TTY        TIME	CMD
1113 	??         1:37.73 	/Applications/Appium.app/Contents/MacOS/Appium TMPDIR=/var/folders/zx/wlsrrmw554d7pmfr_bc6nf4xzqkg73/T/ __CF_USER_TEXT_ENCODING=0x7F793CE3:0x0:0x0 SHELL=/bin/ksh HOME=/Users/u205188 Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.dMpysgNh0R/Render SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.R0PcxdLjQu/Listeners PATH=/usr/bin:/bin:/usr/sbin:/sbin LOGNAME=u205188 XPC_SERVICE_NAME=io.appium.desktop.4756 USER=u205188 XPC_FLAGS=0x1


And the complete server log is as below:
```

[Appium] Welcome to Appium v1.6.4-beta
[Appium] Non-default server args:
[Appium] address: '127.0.0.1'
[Appium] Appium REST http interface listener started on 127.0.0.1:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/u205188/Downloads/Marketplace-1.0.131_bab988db_-qa-signed-aligned.apk","appActivity":"com.android.chrome.com.android.chrome/com.google.android.apps.chrome.Main","appPackage":"com.android.chrome","automationName":"UIAutomator2","deviceName":"ce12160cf55490330c","fullReset":true,"platformName":"Android","platformVersion":"7.0","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/u205188/Downloads/Marketplace-1.0.131_bab988db_-qa-signed-aligned.apk","appActivity":"com.android.chrome.com.android.chrome/com.google.android.apps.chrome.Main","appPackage":"com.android.chrome","automationName":"UIAutomator2","deviceName":"ce12160cf55490330c","fullReset":true,"platformName":"Android","platformVersion":"7.0","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null,null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1516580000249 (10:13:20 GMT+1000 (AEST))
[Appium] Creating new AndroidUiautomator2Driver (v0.2.13) session
[Appium] Capabilities:
[Appium] app: '/Users/u205188/Downloads/Marketplace-1.0.131_bab988db_-qa-signed-aligned.apk'
[Appium] appActivity: 'com.android.chrome.com.android.chrome/com.google.android.apps.chrome.Main'
[Appium] appPackage: 'com.android.chrome'
[Appium] automationName: 'UIAutomator2'
[Appium] deviceName: 'ce12160cf55490330c'
[Appium] fullReset: true
[Appium] platformName: 'Android'
[Appium] platformVersion: '7.0'
[Appium] newCommandTimeout: 0
[Appium] connectHardwareKeyboard: true
[BaseDriver] The following capabilities were provided, but are not recognized by appium: connectHardwareKeyboard.
[BaseDriver] Session created with session id: a8024d1e-e309-4b30-bbca-43f0b137b8d1
[BaseDriver] Using local app '/Users/u205188/Downloads/Marketplace-1.0.131_bab988db_-qa-signed-aligned.apk'
[UiAutomator2] Checking whether app is actually present
[UiAutomator2] UIAutomator2 Driver version:0.2.13
[AndroidDriver] Getting Java version
[AndroidDriver] Java version is: 9.0.1
[ADB] Checking whether adb is present
[ADB] The ANDROID_HOME environment variable is not set to the Android SDK root directory path. ANDROID_HOME is required for compatibility with SDK 23+. Checking along PATH for adb.
[ADB] Using adb from /usr/local/bin/adb 
[AndroidDriver] Retrieving device list
[ADB] Trying to find a connected android device
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[AndroidDriver] Looking for a device with Android '7.0'
[ADB] Setting device id to ce12160cf55490330c
[ADB] Getting device platform version
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/usr/local/bin/adb' with args: ["-P",5037,"-s","ce12160cf55490330c","shell","getprop","ro.build.version.release"]
[AndroidDriver] Using device: ce12160cf55490330c
[ADB] Checking whether adb is present
[ADB] The ANDROID_HOME environment variable is not set to the Android SDK root directory path. ANDROID_HOME is required for compatibility with SDK 23+. Checking along PATH for adb.
[ADB] Using adb from /usr/local/bin/adb 
[ADB] Setting device id to ce12160cf55490330c
[ADB] Getting device platform version
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/usr/local/bin/adb' with args: ["-P",5037,"-s","ce12160cf55490330c","shell","getprop","ro.build.version.release"]
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/usr/local/bin/adb' with args: ["-P",5037,"-s","ce12160cf55490330c","shell","wm","size"]
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/usr/local/bin/adb' with args: ["-P",5037,"-s","ce12160cf55490330c","shell","getprop","ro.product.model"]
[ADB] Current device property 'ro.product.model': SM-G930F
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/usr/local/bin/adb' with args: ["-P",5037,"-s","ce12160cf55490330c","shell","getprop","ro.product.manufacturer"]
[ADB] Current device property 'ro.product.manufacturer': samsung
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/usr/local/bin/adb' with args: ["-P",5037,"-s","ce12160cf55490330c","shell","am","force-stop","io.appium.uiautomator2.server"]
[ADB] Running '/usr/local/bin/adb' with args: ["-P",5037,"-s","ce12160cf55490330c","wait-for-device"]
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/usr/local/bin/adb' with args: ["-P",5037,"-s","ce12160cf55490330c","shell","echo","ping"]
[Logcat] Starting logcat capture
[AndroidDriver] Pushing settings apk to device...
[ADB] Running '/usr/local/bin/adb' with args: ["-P",5037,"-s","ce12160cf55490330c","install","/Applications/Appium.app/Contents/Resources/app/node_modules/io.appium.settings/bin/settings_apk-debug.apk"]
[ADB] Running '/usr/local/bin/adb' with args: ["-P",5037,"-s","ce12160cf55490330c","install","/Applications/Appium.app/Contents/Resources/app/node_modules/io.appium.settings/bin/settings_apk-debug.apk"]
[ADB] Application '/Applications/Appium.app/Contents/Resources/app/node_modules/io.appium.settings/bin/settings_apk-debug.apk' already installed. Continuing.
[AndroidDriver] Pushing unlock helper app to device...
[ADB] Running '/usr/local/bin/adb' with args: ["-P",5037,"-s","ce12160cf55490330c","install","/Applications/Appium.app/Contents/Resources/app/node_modules/appium-unlock/bin/unlock_apk-debug.apk"]
[ADB] Running '/usr/local/bin/adb' with args: ["-P",5037,"-s","ce12160cf55490330c","install","/Applications/Appium.app/Contents/Resources/app/node_modules/appium-unlock/bin/unlock_apk-debug.apk"]
[ADB] Application '/Applications/Appium.app/Contents/Resources/app/node_modules/appium-unlock/bin/unlock_apk-debug.apk' already installed. Continuing.
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/usr/local/bin/adb' with args: ["-P",5037,"-s","ce12160cf55490330c","shell","getprop","ro.build.version.sdk"]
[ADB] Device API level: 24
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/usr/local/bin/adb' with args: ["-P",5037,"-s","ce12160cf55490330c","shell","appops","set","io.appium.settings","android:mock_location","allow"]
[UiAutomator2] Forwarding UiAutomator2 Server port 6790 to 8200
[ADB] Forwarding system: 8200 to device: 6790
[ADB] Running '/usr/local/bin/adb' with args: ["-P",5037,"-s","ce12160cf55490330c","forward","tcp:8200","tcp:6790"]
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/usr/local/bin/adb' with args: ["-P",5037,"-s","ce12160cf55490330c","shell","dumpsys","window"]
[AndroidDriver] Screen already unlocked, doing nothing
[AndroidDriver] Extracting strings from apk /Users/u205188/Downloads/Marketplace-1.0.131_bab988db_-qa-signed-aligned.apk undefined /var/folders/zx/wlsrrmw554d7pmfr_bc6nf4xzqkg73/T/com.android.chrome
[ADB] Extracting strings for language: default
[ADB] Device API level: 24
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/usr/local/bin/adb' with args: ["-P",5037,"-s","ce12160cf55490330c","shell","getprop","persist.sys.locale"]
[ADB] Current device property 'persist.sys.locale': en-AU
[ADB] No strings.xml for language 'en', getting default strings.xml
[ADB] Reading strings from converted strings.json
[ADB] Running '/usr/local/bin/adb' with args: ["-P",5037,"-s","ce12160cf55490330c","push","/var/folders/zx/wlsrrmw554d7pmfr_bc6nf4xzqkg73/T/com.android.chrome/strings.json","/data/local/tmp"]
[ADB] Uninstalling com.android.chrome
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/usr/local/bin/adb' with args: ["-P",5037,"-s","ce12160cf55490330c","shell","am","force-stop","com.android.chrome"]
[ADB] Running '/usr/local/bin/adb' with args: ["-P",5037,"-s","ce12160cf55490330c","uninstall","com.android.chrome"]
[ADB] App was not uninstalled, maybe it wasn't on device?
[UiAutomator2] Deleting UiAutomator2 session
[UiAutomator2] Deleting UiAutomator2 server session
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: Error: Trying to proxy a session command without session id
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/usr/local/bin/adb' with args: ["-P",5037,"-s","ce12160cf55490330c","shell","am","force-stop","com.android.chrome"]
[UiAutomator2] FULL_RESET set to 'true', Uninstalling 'com.android.chrome'
[ADB] Uninstalling com.android.chrome
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/usr/local/bin/adb' with args: ["-P",5037,"-s","ce12160cf55490330c","shell","am","force-stop","com.android.chrome"]
[ADB] Running '/usr/local/bin/adb' with args: ["-P",5037,"-s","ce12160cf55490330c","uninstall","com.android.chrome"]
[ADB] App was not uninstalled, maybe it wasn't on device?
[Logcat] Stopping logcat capture
[ADB] Removing forwarded port socket connection: 8200 
[ADB] Running '/usr/local/bin/adb' with args: ["-P",5037,"-s","ce12160cf55490330c","forward","--remove","tcp:8200"]
[MJSONWP] Encountered internal error running command: Error: JAVA_HOME is not set currently. Please set JAVA_HOME. at getJavaHome (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-adb/lib/helpers.js:106:9) at getJavaForOs (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-adb/lib/helpers.js:95:17) at ADB.callee$0$0$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-adb/lib/tools/apk-signing.js:76:16) at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-adb/node_modules/babel-runtime/regenerator/runtime.js:67:40) at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-adb/node_modules/babel-runtime/regenerator/runtime.js:315:22) at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-adb/node_modules/babel-runtime/regenerator/runtime.js:100:21) at invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-adb/node_modules/babel-runtime/regenerator/runtime.js:136:37) at enqueueResult (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-adb/node_modules/babel-runtime/regenerator/runtime.js:185:17) at Promise.F (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-adb/node_modules/core-js/library/modules/$.export.js:30:36) at AsyncIterator.enqueue (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-adb/node_modules/babel-runtime/regenerator/runtime.js:184:12) at AsyncIterator.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-adb/node_modules/babel-runtime/regenerator/runtime.js:100:21) at Object.runtime.async (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-adb/node_modules/babel-runtime/regenerator/runtime.js:209:12) at ADB.callee$0$0 [as checkApkCert] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-adb/build/lib/tools/apk-signing.js:219:30) at AndroidUiautomator2Driver.initAUT$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-uiautomator2-driver/lib/driver.js:309:35) at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-uiautomator2-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40) at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-uiautomator2-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22) at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-uiautomator2-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21) at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-uiautomator2-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 8981 ms - 190 

```

**Comment by mykola-mokhnach** [comment]
> TMPDIR=/var/folders/zx/wlsrrmw554d7pmfr_bc6nf4xzqkg73/T/ __CF_USER_TEXT_ENCODING=0x7F793CE3:0x0:0x0 SHELL=/bin/ksh HOME=/Users/u205188 Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.dMpysgNh0R/Render SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.R0PcxdLjQu/Listeners PATH=/usr/bin:/bin:/usr/sbin:/sbin LOGNAME=u205188 XPC_SERVICE_NAME=io.appium.desktop.4756 USER=u205188 XPC_FLAGS=0x1


As you can see here Appium process does not have JAVA_HOME var in its env. Closed as not an issue,
