### ISSUE TITLE
Appium 1.7.2 - beta5 - driver.getPageSource() throws JsonException: Unable to convert: Method is not implemented

### ISSUE THREAD

**Issue by vikas-thange-twc** [appium/appium#10048]
## The problem

I am trying to launch already installed app with package name and activity name. I can see the app is getting launched when I initialize AndroidDriver<AndroidElement> driver object. but when i call driver.getPageSource() it throws `**org.openqa.selenium.json.JsonException: Unable to convert: Method is not implemented**`

## Environment

* Appium version : Appium 1.7.2-beta5 (installed beta using npm)
* Last Appium version that did not exhibit the issue (if applicable): v1.6.5 (with Appium-Desktop)
* Desktop OS/version used to run Appium: Mac 10.12.6
* Node.js version (unless using Appium.app|exe): v7.3.0
* Mobile platform/version under test: Android O
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI 1.7.2-beta-5 has issue but appium desktop with 1.6.5 works.
* Java Client: 6.0.0-BETA2
## Details

Not sure if this method not implemented due to appium beta or java client-beta version. I am assuming it is appium server issue 

## Link to Appium logs

```
[HTTP] --> GET /wd/hub/session/9447332a-5694-4bc2-b0b6-77958df25820/context {}
[debug] [MJSONWP] Calling AppiumDriver.getCurrentContext() with args: ["9447332a-5694-4bc2-b0b6-77958df25820"]
[debug] [MJSONWP] Responding to client with driver.getCurrentContext() result: "NATIVE_APP"
[HTTP] <-- GET /wd/hub/session/9447332a-5694-4bc2-b0b6-77958df25820/context 200 3 ms - 22 
[HTTP] --> POST /wd/hub/session/9447332a-5694-4bc2-b0b6-77958df25820/execute/sync {"script":"var source = document.documentElement.outerHTML; \nif (!source) { source = new XMLSerializer().serializeToString(document); }\nreturn source;","args":[]}
[debug] [MJSONWP] Calling AppiumDriver.execute() with args: ["var source = document.documentElement.outerHTML; \nif (!source) { source = new XMLSerializer().serializeToString(document); }\nreturn source;",[],"9447332a-5694-4bc2-b0b6-77958df25820"]
[HTTP] <-- POST /wd/hub/session/9447332a-5694-4bc2-b0b6-77958df25820/execute/sync 400 7 ms - 25 
```

Full Appium Log Gist : https://gist.github.com/vikas-thange-twc/65196086074925b3b979a04c939c7209

## Code To Reproduce Issue [ Good To Have ]
```
DesiredCapabilities caps;
AndroidDriver<AndroidElement> driver;
caps = new DesiredCapabilities();
caps.setCapability(MobileCapabilityType.PLATFORM_NAME, "android");
caps.setCapability(MobileCapabilityType.DEVICE_NAME, "S5");
caps.setCapability(MobileCapabilityType.NO_RESET, "true");
caps.setCapability(MobileCapabilityType.FULL_RESET, "false");
caps.setCapability(AndroidMobileCapabilityType.APP_PACKAGE, "com.whatsapp");
caps.setCapability(AndroidMobileCapabilityType.APP_ACTIVITY, ".HomeActivity");
driver = new AndroidDriver<AndroidElement>(new URL("http://0.0.0.0:4723/wd/hub"), caps);
driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
System.out.println(driver.getContextHandles());
System.out.println(driver.getContext());
System.out.println(driver.getPageSource()); // Throws org.openqa.selenium.json.JsonException: Unable to convert: Method is not implemented
```
## Console Log after running program
```
org.openqa.selenium.json.JsonException: Unable to convert: Method is not implemented
Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:01:39.354Z'
System info: host: 'XIPL9137.local', ip: 'fe80:0:0:0:145c:6b7d:673:f2d1%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_102'
Driver info: driver.version: RemoteWebDriver
	at com.google.gson.JsonParser.parse(JsonParser.java:65)
	at com.google.gson.JsonParser.parse(JsonParser.java:45)
	at org.openqa.selenium.json.JsonToBeanConverter.convert(JsonToBeanConverter.java:203)
	at org.openqa.selenium.json.JsonToBeanConverter.convert(JsonToBeanConverter.java:57)
	at org.openqa.selenium.json.Json.toType(Json.java:78)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:87)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:89)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:600)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:46)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.getPageSource(RemoteWebDriver.java:482)
	at SwipeExampleAndBuiltInApp.postMessage(SwipeExampleAndBuiltInApp.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 9 path $
	... 39 more
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 9 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1409)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
	at com.google.gson.JsonParser.parse(JsonParser.java:60)
	... 38 more
```

**Comment by mykola-mokhnach** [comment]
This issue is known and the fix for it is going to be merged into beta soon. Please revert to latest stable release as a workaround.
