### ISSUE TITLE
 UnhandledPromiseRejectionWarning: Error: [elementById("searchEditText")] Error response status: 13, , UnknownError - An unknown server-side error

### ISSUE THREAD

**Issue by potapovDim** [appium/appium#10074]
## Environment

* Appium v1.7.2
* Mac OS High Sierra v.10.13.3
* Node.js v9.3.0
* Mobile platform android 7.1.2
* Real device Google Pixel

### Appium server stack
```
 Encountered internal error running command:  {"w3cStatus":400,"jsonwp":{"sessionId":"d1c13877-0520-4e00-9bb8-7505ad3dc408","status":10,"value":"android.support.test.uiautomator.StaleObjectException\n\tat android.support.test.uiautomator.UiObject2.getAccessibilityNodeInfo(UiObject2.java:629)\n\tat android.support.test.uiautomator.UiObject2.hashCode(UiObject2.java:105)\n\tat java.lang.Object.toString(Object.java:260)\n\tat java.util.Formatter$FormatSpecifier.printString(Formatter.java:2922)\n\tat java.util.Formatter$FormatSpecifier.print(Formatter.java:2802)\n\tat java.util.Formatter.format(Formatter.java:2491)\n\tat java.util.Formatter.format(Formatter.java:2426)\n\tat java.lang.String.format(String.java:2626)\n\tat io.appium.uiautomator2.utils.ReflectionUtils.invoke(ReflectionUtils.java:91)\n\tat io.appium.uiautomator2.model.UiObject2Element.getBoolAttribute(UiObject2Element.java:121)\n\tat io.appium.uiautomator2.handler.GetElementAttribute.safeHandle(GetElementAttribute.java:40)\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:56)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:208)...
```

```
[HTTP] <-- GET /wd/hub/session/48c218ce-bd0b-43fe-86a3-e2bbc16d11ab/element/7b386dfa-e341-4463-ad06-b57d6e9dd434/displayed 500
```

```
[MJSONWP] Encountered internal error running command: TypeError: Cannot read property 'jwproxy' of null
```

### Terminal stack
```
(node:9515) UnhandledPromiseRejectionWarning: Error: [elementById("searchEditText")] Error response status: 13, , UnknownError - An unknown server-side error occurred while processingthe command. Selenium error: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'jwproxy' of null
    at exports.newError (/Users/dpot/Documents/safeToNetIos/node_modules/wd/lib/utils.js:148:13)
    at /Users/dpot/Documents/safeToNetIos/node_modules/wd/lib/callbacks.js:75:19
    at /Users/dpot/Documents/safeToNetIos/node_modules/wd/lib/webdriver.js:179:5
    at Request._callback (/Users/dpot/Documents/safeToNetIos/node_modules/wd/lib/http-utils.js:88:7)
    at Request.self.callback (/Users/dpot/Documents/safeToNetIos/node_modules/wd/node_modules/request/request.js:186:22)
    at Request.emit (events.js:159:13)
    at Request.<anonymous> (/Users/dpot/Documents/safeToNetIos/node_modules/wd/node_modules/request/request.js:1081:10)
    at Request.emit (events.js:159:13)
    at IncomingMessage.<anonymous> (/Users/dpot/Documents/safeToNetIos/node_modules/wd/node_modules/request/request.js:1001:12)
    at Object.onceWrapper (events.js:254:19)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1062:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
(node:9515) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9515) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with anon-zero exit code.
(node:9515) UnhandledPromiseRejectionWarning: Error: [elementById("searchEditText")] Error response status: 13, , UnknownError - An unknown server-side error occurred while processingthe command. Selenium error: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'jwproxy' of null
    at exports.newError (/Users/dpot/Documents/safeToNetIos/node_modules/wd/lib/utils.js:148:13)
    at /Users/dpot/Documents/safeToNetIos/node_modules/wd/lib/callbacks.js:75:19
    at /Users/dpot/Documents/safeToNetIos/node_modules/wd/lib/webdriver.js:179:5
    at Request._callback (/Users/dpot/Documents/safeToNetIos/node_modules/wd/lib/http-utils.js:88:7)
    at Request.self.callback (/Users/dpot/Documents/safeToNetIos/node_modules/wd/node_modules/request/request.js:186:22)
    at Request.emit (events.js:159:13)
    at Request.<anonymous> (/Users/dpot/Documents/safeToNetIos/node_modules/wd/node_modules/request/request.js:1081:10)
    at Request.emit (events.js:159:13)
    at IncomingMessage.<anonymous> (/Users/dpot/Documents/safeToNetIos/node_modules/wd/node_modules/request/request.js:1001:12)
    at Object.onceWrapper (events.js:254:19)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1062:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
(node:9515) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:9515) UnhandledPromiseRejectionWarning: Error: [elementByAccessibilityId("Navigate up")] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'jwproxy' of null
    at exports.newError (/Users/dpot/Documents/safeToNetIos/node_modules/wd/lib/utils.js:148:13)
    at /Users/dpot/Documents/safeToNetIos/node_modules/wd/lib/callbacks.js:75:19
    at /Users/dpot/Documents/safeToNetIos/node_modules/wd/lib/webdriver.js:179:5
    at Request._callback (/Users/dpot/Documents/safeToNetIos/node_modules/wd/lib/http-utils.js:88:7)
    at Request.self.callback (/Users/dpot/Documents/safeToNetIos/node_modules/wd/node_modules/request/request.js:186:22)
    at Request.emit (events.js:159:13)
    at Request.<anonymous> (/Users/dpot/Documents/safeToNetIos/node_modules/wd/node_modules/request/request.js:1081:10)
    at Request.emit (events.js:159:13)
    at IncomingMessage.<anonymous> (/Users/dpot/Documents/safeToNetIos/node_modules/wd/node_modules/request/request.js:1001:12)
    at Object.onceWrapper (events.js:254:19)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1062:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
(node:9515) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```
## Code To Reproduce Issue
* wdjs
driver.elementById('searchEditText')

**Comment by mykola-mokhnach** [comment]
StaleObjectException means you shouldn't have to cache element instance but rather try to find it each time you try to access its properties. I cannot say more, because full server log is missing.

**Comment by potapovDim** [comment]
@mykola-mokhnach ill give you my stack tomorrow

**Comment by mykola-mokhnach** [comment]
Sorry @potapovDim, but I don't provide personal support.
