### ISSUE TITLE
Adding ChromeOptions cause Error

### ISSUE THREAD

**Issue by pavkr** [appium/appium#10080]
## The problem

**[ADB] The ANDROID_HOME environment variable is not set to the Android SDK root directory path. ANDROID_HOME is required for compatibility with SDK 23+. Checking along PATH for aapt.**

## Environment
from terminal: 
`$ echo $ANDROID_HOME
/Users/auto-it/Library/Android/sdk`

`$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/auto-it/library/android/sdk/platform-tools/:/Users/auto-it/Library/Android/sdk/build-tools:/Users/auto-it/Library/Android/sdk/platform-tools:/Users/auto-it/Library/Android/sdk/tools`

`$ adb --version
Android Debug Bridge version 1.0.39
Version 27.0.0-4455170
Installed as /Users/auto-it/library/android/sdk/platform-tools/adb`

* Appium version 
`$ appium -v
1.7.2`
* Last Appium version that did not exhibit the issue (if applicable): 1.7.1
* Desktop OS/version used to run Appium: macOS High Sierra 10.13.2 
* Node.js version (unless using Appium.app|exe): 
`$ node -v
v9.3.0`
* Mobile platform/version under test: Android 7.1.1, iOS 11.
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe: CLI

## Details

Basically Without ChromeOptions everything works fine.

## Link to Appium logs

```
debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.7.2","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 12 ms - 83 
[debug] [ADB] App is installed
[debug] [ADB] Getting package info for io.appium.unlock
[debug] [ADB] Getting connected devices...
[debug] [ADB] 2 device(s) connected
[debug] [ADB] Running '/Users/auto-it/library/android/sdk/platform-tools//adb' with args: ["-P",5037,"-s","31b31d241ae173e6","shell","dumpsys","package","io.appium.unlock"]
[ADB] Checking whether aapt is present
[ADB] The ANDROID_HOME environment variable is not set to the Android SDK root directory path. ANDROID_HOME is required for compatibility with SDK 23+. Checking along PATH for aapt.
[ADB] Error: Could not find aapt Please set the ANDROID_HOME environment variable with the Android SDK root directory path.
    at Object.wrappedLogger.errorAndThrow (/usr/local/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:69:13)
    at ADB.callee$0$0$ (/usr/local/lib/node_modules/appium/node_modules/appium-adb/lib/tools/system-calls.js:127:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
 Error: Could not find aapt Please set the ANDROID_HOME environment variable with the Android SDK root directory path.
    at Object.wrappedLogger.errorAndThrow (/usr/local/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:69:13)
    at ADB.callee$0$0$ (/usr/local/lib/node_modules/appium/node_modules/appium-adb/lib/tools/system-calls.js:127:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
[AndroidDriver] Ignored error while installing Appium Unlock helper: 'Could not find aapt Please set the ANDROID_HOME environment variable with the Android SDK root directory path.'. Manually uninstalling the application with package id 'io.appium.unlock' may help. Expect some Appium features may not work as expected unless this problem is fixed.
```

## Code To Reproduce Issue [ Good To Have ]
```
DesiredCapabilities capabilities = new DesiredCapabilities();
                capabilities.SetCapability("newCommandTimeout", 380);
                capabilities.SetCapability("udid", (string)(doc.capabilities[0].deviceName));
                capabilities.SetCapability("deviceName", (string)(doc.capabilities[0].deviceName));
                capabilities.SetCapability("noReset", "true");
                capabilities.SetCapability("fullReset", "false");
                capabilities.SetCapability("javascriptEnabled", "true");
                capabilities.SetCapability(CapabilityType.BrowserName, (string)doc.capabilities[0].browserName);
                capabilities.SetCapability(CapabilityType.Platform, (string)doc.capabilities[0].devicePlatform);

                // Follow up for issue https://github.com/appium/appium/issues/9838
                if (doc.capabilities[0].browserName == "Chrome")
                {
                    ChromeOptions options = new ChromeOptions();
                    options.AddArgument("--enable-precise-memory-info");
                    //options.AddArguments("--enable-precise-memory-info");
                    capabilities.SetCapability(ChromeOptions.Capability, options);
                }
                //Start new driver instance
                //driver = new RemoteWebDriver(new URL(host), capabilities);
                driver = new AndroidDriver<RemoteWebElement>(url, capabilities, new TimeSpan(0, 30, 0));
```

**Comment by mykola-mokhnach** [comment]
I have no idea how setting of capabilities might affect environment variables detection. Make sure the environment variable is visible to the Appium [process](http://chwalisz.org/2013/01/25/osx-show-environment-vars-of-a-running-process/) itself.

**Comment by pavkr** [comment]
Yeah, me neither. But I went despaired when the only way to debug why my test is failing was to comment chunks of code. However I can assure you, the bottom of the issue is hiding somewhere behind ChromeOptions since rest of the code works perfect. 

Probably the logs I've attached did not contain actual reason as they are not full. I'll run it again in the morning and add full log, maybe it will help.
