### ISSUE TITLE
【iOS】Encountered internal error running command: InvalidArgumentError: The capabilities argument was not valid for the following reason(s): "capabilities" must be a JSON object

### ISSUE THREAD

**Issue by yefankongge** [appium/appium#10090]
The problem
The appium version I used before was 1.6.5，appium-base-driver@2.20.1，appium-android-driver@1.37.3，Android runs normally, but iOS runs failed

Environment
Appium version (or git revision) that exhibits the issue:1.6.5
Last Appium version that did not exhibit the issue (if applicable):1.6.5
Desktop OS/version used to run Appium:mac 10.12.6；xcode 9.2
Node.js version (unless using Appium.app|exe):7.2.1
Mobile platform/version under test:iOS 10.3
Real device or emulator/simulator:Real device
Appium CLI or Appium.app|exe: Appium CLI
Details

org.openqa.selenium.WebDriverException: Unable to parse remote response: The capabilities argument was not valid for the following reason(s): "capabilities" must be a JSON object.
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T15:28:36.4Z'
System info: host: 'yefandeMacBook-Pro.local', ip: 'fe80:0:0:0:888:36b9:b686:a92e%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_101'
Driver info: driver.version: IOSDriver
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:347)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:136)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:89)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:586)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:217)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:140)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:83)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:93)
	at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:78)
	at com.xxx.qa.BaseTest.beforeClass(BaseTest.java:69)
null

Link to Appium logs

Last login: Mon Jan 29 17:58:56 on ttys001
yefandeMacBook-Pro:~ yefan$ appium

[Appium] Welcome to Appium v1.6.5
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/yefan/Documents/code/test/UIAutomation_iOS/APK/xxxx4iPhone.zip","noReset":true,"newCommandTimeout":120,"platformVersion":"10.3","bundleId":"com.juangua.xxxxdev","automationName":"XCUITest","autoDismissAlerts":true,"unicodeKeyboard":"True","platformName":"iOS","udid":"d7e966361d39299cbc243a11cfa8acdbb364a1bf","deviceName":"iphone 6s plus"},"requiredCapabilities":{},"capabilities":{"desiredCapabilities":{"app":"/Users/yefan/Documents/code/test/UIAutomation_iOS/APK/xxxx4iPhone.zip","noReset":true,"newCommandTimeout":120,"platformVersion":"10.3","bundleId":"com.juangua.xxxxdev","automationName":"XCUITest","autoDismissAlerts":true,"unicodeKeyboard":"True","platformName":"iOS","udid":"d7e966361d39299cbc243a11cfa8acdbb364a1bf","deviceName":"iphone 6s plus"},"requiredCapabilities":{},"alwaysMatch":{"platformName":"iOS"},"firstMatch":[]}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/yefan/Documents/code/test/UIAutomation_iOS/APK/xxxx4iPhone.zip","noReset":true,"newCommandTimeout":120,"platformVersion":"10.3","bundleId":"com.juangua.xxxxdev","automationName":"XCUITest","autoDismissAlerts":true,"unicodeKeyboard":"True","platformName":"iOS","udid":"d7e966361d39299cbc243a11cfa8acdbb364a1bf","deviceName":"iphone 6s plus"},{},{"desiredCapabilities":{"app":"/Users/yefan/Documents/code/test/UIAutomation_iOS/APK/xxxx4iPhone.zip","noReset":true,"newCommandTimeout":120,"platformVersion":"10.3","bundleId":"com.juangua.xxxxdev","automationName":"XCUITest","autoDismissAlerts":true,"unicodeKeyboard":"True","platformName":"iOS","udid":"d7e966361d39299cbc243a11cfa8acdbb364a1bf","deviceName":"iphone 6s plus"},"requiredCapabilities":{},"alwaysMatch":{"platformName":"iOS"},"firstMatch":[]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1517222331771 (18:38:51 GMT+0800 (CST))
[Appium] Creating new XCUITestDriver (v2.66.0) session
[Appium] Capabilities:
[Appium]   app: '/Users/yefan/Documents/code/test/UIAutomation_iOS/APK/xxxx4iPhone.zip'
[Appium]   noReset: true
[Appium]   newCommandTimeout: 120
[Appium]   platformVersion: '10.3'
[Appium]   bundleId: 'com.juangua.xxxxdev'
[Appium]   automationName: 'XCUITest'
[Appium]   autoDismissAlerts: true
[Appium]   unicodeKeyboard: 'True'
[Appium]   platformName: 'iOS'
[Appium]   udid: 'd7e966361d39299cbc243a11cfa8acdbb364a1bf'
[Appium]   deviceName: 'iphone 6s plus'
[XCUITest] InvalidArgumentError: The capabilities argument was not valid for the following reason(s): "capabilities" must be a JSON object.
    at parseCaps (/usr/local/lib/node_modules/appium/node_modules/._appium-base-driver@2.20.0@appium-base-driver/lib/basedriver/capabilities.js:115:11)
    at processCapabilities (/usr/local/lib/node_modules/appium/node_modules/._appium-base-driver@2.20.0@appium-base-driver/lib/basedriver/capabilities.js:185:43)
    at XCUITestDriver.callee$0$0$ (/usr/local/lib/node_modules/appium/node_modules/._appium-base-driver@2.20.0@appium-base-driver/lib/basedriver/commands/session.js:17:5)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:185:17)
    at F (/usr/local/lib/node_modules/appium/node_modules/._core-js@1.2.7@core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:209:12)
    at XCUITestDriver.callee$0$0 [as createSession] (/usr/local/lib/node_modules/appium/node_modules/._appium-base-driver@2.20.0@appium-base-driver/build/lib/basedriver/commands/session.js:35:30)
    at XCUITestDriver.createSession$ (/usr/local/lib/node_modules/appium/node_modules/._appium-xcuitest-driver@2.66.0@appium-xcuitest-driver/lib/driver.js:93:21)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:185:17)
    at F (/usr/local/lib/node_modules/appium/node_modules/._core-js@1.2.7@core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:209:12)
    at XCUITestDriver.createSession (/usr/local/lib/node_modules/appium/node_modules/._appium-xcuitest-driver@2.66.0@appium-xcuitest-driver/build/lib/driver.js:194:34)
    at AppiumDriver.createSession$ (/usr/local/lib/node_modules/appium/lib/appium.js:183:43)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:185:17)
    at F (/usr/local/lib/node_modules/appium/node_modules/._core-js@1.2.7@core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:209:12)
    at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/build/lib/appium.js:307:34)
    at /usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:267:26
    at tryCatcher (/usr/local/lib/node_modules/appium/node_modules/._bluebird@2.11.0@bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/appium/node_modules/._bluebird@2.11.0@bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/appium/node_modules/._bluebird@2.11.0@bluebird/js/main/promise.js:584:18)
    at Promise._settlePromiseAtPostResolution (/usr/local/lib/node_modules/appium/node_modules/._bluebird@2.11.0@bluebird/js/main/promise.js:248:10)
    at Async._drainQueue (/usr/local/lib/node_modules/appium/node_modules/._bluebird@2.11.0@bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/usr/local/lib/node_modules/appium/node_modules/._bluebird@2.11.0@bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/appium/node_modules/._bluebird@2.11.0@bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
 { InvalidArgumentError: The capabilities argument was not valid for the following reason(s): "capabilities" must be a JSON object.
    at parseCaps (/usr/local/lib/node_modules/appium/node_modules/._appium-base-driver@2.20.0@appium-base-driver/lib/basedriver/capabilities.js:115:11)
    at processCapabilities (/usr/local/lib/node_modules/appium/node_modules/._appium-base-driver@2.20.0@appium-base-driver/lib/basedriver/capabilities.js:185:43)
    at XCUITestDriver.callee$0$0$ (/usr/local/lib/node_modules/appium/node_modules/._appium-base-driver@2.20.0@appium-base-driver/lib/basedriver/commands/session.js:17:5)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:185:17)
    at F (/usr/local/lib/node_modules/appium/node_modules/._core-js@1.2.7@core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:209:12)
    at XCUITestDriver.callee$0$0 [as createSession] (/usr/local/lib/node_modules/appium/node_modules/._appium-base-driver@2.20.0@appium-base-driver/build/lib/basedriver/commands/session.js:35:30)
    at XCUITestDriver.createSession$ (/usr/local/lib/node_modules/appium/node_modules/._appium-xcuitest-driver@2.66.0@appium-xcuitest-driver/lib/driver.js:93:21)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:185:17)
    at F (/usr/local/lib/node_modules/appium/node_modules/._core-js@1.2.7@core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:209:12)
    at XCUITestDriver.createSession (/usr/local/lib/node_modules/appium/node_modules/._appium-xcuitest-driver@2.66.0@appium-xcuitest-driver/build/lib/driver.js:194:34)
    at AppiumDriver.createSession$ (/usr/local/lib/node_modules/appium/lib/appium.js:183:43)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:185:17)
    at F (/usr/local/lib/node_modules/appium/node_modules/._core-js@1.2.7@core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:209:12)
    at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/build/lib/appium.js:307:34)
    at /usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:267:26
    at tryCatcher (/usr/local/lib/node_modules/appium/node_modules/._bluebird@2.11.0@bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/appium/node_modules/._bluebird@2.11.0@bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/appium/node_modules/._bluebird@2.11.0@bluebird/js/main/promise.js:584:18)
    at Promise._settlePromiseAtPostResolution (/usr/local/lib/node_modules/appium/node_modules/._bluebird@2.11.0@bluebird/js/main/promise.js:248:10)
    at Async._drainQueue (/usr/local/lib/node_modules/appium/node_modules/._bluebird@2.11.0@bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/usr/local/lib/node_modules/appium/node_modules/._bluebird@2.11.0@bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/appium/node_modules/._bluebird@2.11.0@bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5) jsonwpCode: undefined, w3cStatus: 400 }
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[HTTP] <-- POST /wd/hub/session 400 64 ms - 106 

Code To Reproduce Issue [ Good To Have ]
 @BeforeClass
    public void beforeClass() throws Exception {
        DesiredCapabilities capabilities = new DesiredCapabilities();
        File classpathRoot = new File(System.getProperty("user.dir"));
        File appDir = new File(classpathRoot, "APK");
        File app = new File(appDir, "xxxx4iPhone.zip");
        capabilities.setCapability("platformName", "iOS");
        capabilities.setCapability("deviceName", ConfigUtils.getString("device"));
        capabilities.setCapability("udid", ConfigUtils.getString("udid"));
        capabilities.setCapability("bundleId", ConfigUtils.getString("app_name"));
        //capabilities.setCapability("deviceName", "iPhone 6s");
        capabilities.setCapability("platformVersion", "10.3");
        capabilities.setCapability("newCommandTimeout", 120);
        capabilities.setCapability("automationName", "XCUITest");
        capabilities.setCapability("app", app);
        capabilities.setCapability("autoDismissAlerts", true);
        capabilities.setCapability("noReset", true);
        capabilities.setCapability("unicodeKeyboard", "True"); //支持中文输入
        driver = new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
        //driver = new IOSDriver(new URL("http://172.17.61.98:4723/wd/hub"), capabilities);
        System.out.println("driver init over");
    }

**Comment by mykola-mokhnach** [comment]
It looks like you have updated some submodules ignoring the shrinkwrap. You could either delete the current stuff and reinstall version 1.6.5 or update to 1.7.2 (selenium java API should also be at least at 3.7 for Appium 1.7+ )

Closed as not an issue.
