### ISSUE TITLE
Appium's Settings randomly failed to launch

### ISSUE THREAD

**Issue by sleepylee** [appium/appium#10115]
## The problem

My test suites got randomly failed due to the Settings app from Appium couldn't be launched. I think the log says quite clear the issue but I'm not sure why it happens on this Mac mini but not on the other old MacBook we already had setup and run on the same environment.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1 (also on 1.7.2)
* NPM version: 5.6.0
* Mobile platform/version under test: Android
* Real device or emulator/simulator: emulator API 23 -> 25
* Mac OS HiSiera

## Logs
```
[AndroidDriver] Failed to launch settings app: Error occured while starting App. Original error: Error executing adbExec. Original error: 'Command '/Android/sdk/platform-tools/adb -P 5045 -s emulator-5558 shell am start -W -n io.appium.settings/.Settings -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' timed out after 20000ms'; Stderr: ''; Code: 'null'
[ADB] Error: Error occured while starting App. Original error: Error executing adbExec. Original error: 'Command '/Android/sdk/platform-tools/adb -P 5045 -s emulator-5558 shell am start -W -n com.redpla.staging/com.tune.ui.activity.SplashActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' timed out after 20000ms'; Stderr: ''; Code: 'null'
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at ADB.callee$0$0$ (../../../lib/tools/apk-utils.js:101:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
```

**Comment by mykola-mokhnach** [comment]
Can you also provide the logcat output for the case it times out?

**Comment by sleepylee** [comment]
hi @mykola-mokhnach , I have updated it on the issue description

**Comment by mykola-mokhnach** [comment]
Sorry, I don't see any logcat listings attached there.

btw, 1.7.2 should not throw this error, but rather just write it into the log..

**Comment by sleepylee** [comment]
hey @mykola-mokhnach, sorry for the late reply. 
I have initiated the whole setup on our mac again (mostly I was doing downgrade) and the issue doesn't occur anymore so I couldn't attach any more information for you regarding this issue. 
We are currently still using appium 1.7.1, but with a downgrade from node & npm: from ~node 9.4.0 and npm 5.6.0~ to node 8.9.1 and npm 5.5.1 (matching with our well running machine). Guess we may close this issue then?

**Comment by mykola-mokhnach** [comment]
yes, reopen it if you get more detailed info.

**Comment by SlavikVostretsov** [comment]
Hi @mykola-mokhnach ! Could you please help me to resolve this issue? I also faced this issue on my Mac and Windows machines. I've already tried different versions of appium (1.7.2, 1.8.0, 1.8.1) and provided above node version 8.9.1 with 5.5.1 npm version. 
I'm sure that it worked correctly about a month ago but I cannot figure out what is happened now 
Do you have any thoughts or should I provide any additional info?

Note: I'm able to install the app by drag and dropping directly to an emulator 

Here are my logs
[debug] [ADB] Device API level: 22
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\user\AppData\Local\Android\Sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","am","start","-W","-n","com.myApp.xamarin.droid.myApp/md59f575434f825bd763d7136ca1a771623.MainActivity","-S","-a","android.intent.action.MAIN","-c","android.intent.category.LAUNCHER","-f","0x10200000"]
[debug] [ADB] Running 'C:\Users\user\AppData\Local\Android\Sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","am","start","-W","-n","com.myApp.xamarin.droid.myApp/md59f575242342343d7136ca1a771623.MainActivity","-S","-a","android.intent.action.MAIN","-c","android.intent.category.LAUNCHER","-f","0x10200000"]
[ADB] Error: Error occured while starting App. Original error: Error executing adbExec. Original error: 'Command 'C\:\\Users\\user\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 shell am start -W -n com.myApp.xamarin.droid.myApp/md59f575434f825bd763d7136ca1a771623.MainActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' timed out after 20000ms'; Stderr: ''; Code: 'null'
    at Object.wrappedLogger.errorAndThrow (C:\Users\user\mobile\node_modules\appium\node_modules\appium-support\lib\logging.js:69:13)
    at ADB.callee$0$0$ (C:\Users\user\mobile\node_modules\appium\node_modules\appium-adb\lib\tools\apk-utils.js:101:9)
    at tryCatch (C:\Users\user\mobile\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\user\mobile\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\user\mobile\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\user\mobile\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at <anonymous>
 Error: Error occured while starting App. Original error: Error executing adbExec. Original error: 'Command 'C\:\\Users\\user\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 shell am start -W -n com.myApp.xamarin.droid.myApp/md59f575434f825bd763d7136ca1a771623.MainActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' timed out after 20000ms'; Stderr: ''; Code: 'null'
    at Object.wrappedLogger.errorAndThrow (C:\Users\user\mobile\node_modules\appium\node_modules\appium-support\lib\logging.js:69:13)
    at ADB.callee$0$0$ (C:\Users\user\mobile\node_modules\appium\node_modules\appium-adb\lib\tools\apk-utils.js:101:9)
    at tryCatch (C:\Users\user\mobile\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\user\mobile\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\user\mobile\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\user\mobile\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at <anonymous>
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [UiAutomator2] Deleting UiAutomator2 server session
[debug] [JSONWP Proxy] Proxying [DELETE /] to [DELETE http://localhost:8200/wd/hub/session/b2147d3d-cf64-4c25-a56c-79e2dade5e17] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"b2147d3d-cf64-4c25-a56c-79e2dade5e17\",\"status\":0,\"value\":\"Session deleted\"}"
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\user\AppData\Local\Android\Sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","am","force-stop","com.myApp.xamarin.droid.myApp"]
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Removing forwarded port socket connection: 8200 
[debug] [ADB] Running 'C:\Users\user\AppData\Local\Android\Sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","forward","--remove","tcp:8200"]
[MJSONWP] Encountered internal error running command: Error: Error occured while starting App. Original error: Error executing adbExec. Original error: 'Command 'C\:\\Users\\user\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 shell am start -W -n com.myApp.xamarin.droid.myApp/md59f575434f825bd763d7136ca1a771623.MainActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' timed out after 20000ms'; Stderr: ''; Code: 'null'
    at Object.wrappedLogger.errorAndThrow (C:\Users\user\mobile\node_modules\appium\node_modules\appium-support\lib\logging.js:69:13)
    at ADB.callee$0$0$ (C:\Users\user\mobile\node_modules\appium\node_modules\appium-adb\lib\tools\apk-utils.js:101:9)
    at tryCatch (C:\Users\user\mobile\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\user\mobile\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\user\mobile\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\user\mobile\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at <anonymous>
[HTTP] <-- POST /wd/hub/session 500 96551 ms - 602

**Comment by mykola-mokhnach** [comment]
@SlavikVostretsov Try to create a new thread on Appium forum with the necessary details.
