### ISSUE TITLE
I got a error about"[MJSONWP] Encountered internal error running command: Error: An error occurred"

### ISSUE THREAD

**Issue by KuKiSiNi77** [appium/appium#10125]
## The problem

I have ten test case that have same behavior.The first few case normally ran,but the last couldn't and got posted a error log like that:

```java

[debug] [JSONWP Proxy] Got response with status 200: {"value":"The application under test with bundle id 'com.appiumTest.rlterm3push.v6' is not running, possibly crashed","sessionId":"BE165778-ACD7-44F3-8FF1-AFFEE922B201","status":889}
[MJSONWP] Encountered internal error running command: Error: An error occurred
    at JWProxy.command$ (../../../lib/jsonwp-proxy/proxy.js:176:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/_babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/_babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/_babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/_babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session/71e55a19-054d-4822-bf68-4da006788cb7/touch/perform 500 232 ms - 188

```

I had a try to use try-catch get a log:

```java

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: An error occurred (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 237 milliseconds
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'binlis-Mac-mini.local', ip: '192.168.1.153', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_77'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{app=/Applications/rlasp2_autotest/6.4/autoTest/apps/rlterm3.app, networkConnectionEnabled=false, noReset=true, databaseEnabled=false, deviceName=autotest, launchTimeout=500000, platform=MAC, wdaLocalPort=8002, platformVersion=10.3.0, webStorageEnabled=false, locationContextEnabled=false, automationName=XCuiTest, useNewWDA=true, browserName=, takesScreenshot=true, javascriptEnabled=true, udid=9da82887884423f91840e4a4601862d2821de94a, platformName=iOS}]
Session ID: 71e55a19-054d-4822-bf68-4da006788cb7
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
  at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
  at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
  at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:40)
  at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
  at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
  at io.appium.java_client.AppiumDriver.performTouchAction(AppiumDriver.java:336)
  at io.appium.java_client.TouchAction.perform(TouchAction.java:323)

```

From the device's log, the device didn't crashed.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Desktop OS/version used to run Appium: 10.12.6
* Node.js version (unless using Appium.app|exe): v6.6.0
* Real device or emulator/simulator: iPad Air 2 10.3.2

## Capabilities

```java 

DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "");
capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "10.3.0");
capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "autotest");
capabilities.setCapability(MobileCapabilityType.UDID, udid);
capabilities.setCapability(IOSMobileCapabilityType.LAUNCH_TIMEOUT, 500000);
capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME,AutomationName.IOS_XCUI_TEST);
capabilities.setCapability(MobileCapabilityType.APP, app.getAbsolutePath());
capabilities.setCapability(MobileCapabilityType.NO_RESET, true);
capabilities.setCapability("wdaLocalPort",wdaLocalPort);
capabilities.setCapability("useNewWDA", true);
iosDriver = new IOSDriver<>(service.getUrl(), capabilities);
iosDriver.manage().timeouts().implicitlyWait(6, TimeUnit.SECONDS);

```

**Comment by mykola-mokhnach** [comment]
Does the application crash if you run the test locally?

**Comment by KuKiSiNi77** [comment]
@mykola-mokhnach there's no doubt that it happened.

**Comment by vjmaiky** [comment]
doesn't influence that he has both app and browser caps in the same time?

**Comment by mykola-mokhnach** [comment]
Please attach the full server log
