### ISSUE TITLE
Get manifiest fail

### ISSUE THREAD

**Issue by donsmart86** [appium/appium#10120]
## The problem

I am posting this issue here because I fear no-one is maintaining appium-adb where I also posted an issue.

I was attempting to automate some tests on a modern third-party application (e.g. Instagram) downloaded from Google Play.  Early in the process appium server tries to pull the manifest from the APK, which fails because the third-party library used by the appium-adb module does not recognize all of the data types currently supported by AXML.  Starting in version 26.1.1 of the Android SDK, Google started providing a tool named **_apkanalyzer_** that can extract manifests from an APK and presumably will keep abreast of AXML format changes.  With apkanalyzer, a little Bash scripting, a patch to appium-adb module's android-manifest.js file, and a little assist from XMLStarlet to filter the XML, I was able to work-around the problem using apkanalyzer.

I'm not sure how important it is for the Appium community to maintain backward compatibility with older Android SDK versions, but this is definitely a better way to maintain forward compatibility.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable):?
* Desktop OS/version used to run Appium: macOS Sierra and Ubuntu 16.04
* Node.js version (unless using Appium.app|exe): 9.4.0
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe: Appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Do you have the part of server log where the manifest extraction fails?

**Comment by mykola-mokhnach** [comment]
BTW, you're welcome to create a PR yourself

**Comment by donsmart86** [comment]
I don't have the server log any more, but below is the crux of the
problem.  When android-manifest.js can't produce the manifest, the appium
server fails the test case.

$ java -jar
/usr/local/lib/node_modules/appium/node_modules/appium-adb/jars/appium_apk_tools.jar
printLaunchActivity
Downloads/instagram/com.instagram.android_84116177_3a95e6360b34d76f.apk
Downloads/instagram/AndroidManifest.xml
Feb 05, 2018 8:26:34 AM brut.androlib.res.decoder.AXmlResourceParser
getAttributeValue
WARNING: Could not decode attr value, using undecoded value instead:
ns=android, name=versionCode, value=0x050382d1
brut.androlib.AndrolibException: Invalid value type: 0
at
brut.androlib.res.data.value.ResValueFactory.factory(ResValueFactory.java:62)
at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:211)
at
brut.androlib.res.decoder.ARSCDecoder.readComplexEntry(ARSCDecoder.java:199)
at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:169)
at brut.androlib.res.decoder.ARSCDecoder.readConfig(ARSCDecoder.java:157)
at brut.androlib.res.decoder.ARSCDecoder.readType(ARSCDecoder.java:125)
at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:100)
at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:78)
at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
at
brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:605)
at
brut.androlib.res.AndrolibResources.loadFrameworkPkg(AndrolibResources.java:126)
at brut.androlib.res.data.ResTable.getPackage(ResTable.java:75)
at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:58)
at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:54)
at brut.androlib.res.decoder.ResAttrDecoder.decode(ResAttrDecoder.java:36)
at
brut.androlib.res.decoder.AXmlResourceParser.getAttributeValue(AXmlResourceParser.java:369)
at
org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeValue(XmlPullParserDelegate.java:69)
at
brut.androlib.res.decoder.XmlPullStreamDecoder$1.parseManifest(XmlPullStreamDecoder.java:97)
at
brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:65)
at
brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:141)
at
brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPullStreamDecoder.java:153)
at
brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecoder.java:131)
at
brut.androlib.res.AndrolibResources.decodeManifest(AndrolibResources.java:164)
at
io.appium.apktools.AndroidManifestActivityHelper.decodeManifestXML(AndroidManifestActivityHelper.java:27)
at io.appium.apktools.Main.main(Main.java:33)

Feb 05, 2018 8:26:35 AM brut.androlib.res.decoder.AXmlResourceParser
getAttributeValue
WARNING: Could not decode attr value, using undecoded value instead:
ns=android, name=versionName, value=0x0000012d
brut.androlib.AndrolibException: Invalid value type: 0
at
brut.androlib.res.data.value.ResValueFactory.factory(ResValueFactory.java:62)
at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:211)
at
brut.androlib.res.decoder.ARSCDecoder.readComplexEntry(ARSCDecoder.java:199)
at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:169)
at brut.androlib.res.decoder.ARSCDecoder.readConfig(ARSCDecoder.java:157)
at brut.androlib.res.decoder.ARSCDecoder.readType(ARSCDecoder.java:125)
at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:100)
at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:78)
at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
at
brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:605)
at
brut.androlib.res.AndrolibResources.loadFrameworkPkg(AndrolibResources.java:126)
at brut.androlib.res.data.ResTable.getPackage(ResTable.java:75)
at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:58)
at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:54)
at brut.androlib.res.decoder.ResAttrDecoder.decode(ResAttrDecoder.java:36)
at
brut.androlib.res.decoder.AXmlResourceParser.getAttributeValue(AXmlResourceParser.java:369)
at
org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeValue(XmlPullParserDelegate.java:69)
at
brut.androlib.res.decoder.XmlPullStreamDecoder$1.parseManifest(XmlPullStreamDecoder.java:99)
at
brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:65)
at
brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:141)
at
brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPullStreamDecoder.java:153)
at
brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecoder.java:131)
at
brut.androlib.res.AndrolibResources.decodeManifest(AndrolibResources.java:164)
at
io.appium.apktools.AndroidManifestActivityHelper.decodeManifestXML(AndroidManifestActivityHelper.java:27)
at io.appium.apktools.Main.main(Main.java:33)

Feb 05, 2018 8:26:35 AM brut.androlib.res.decoder.AXmlResourceParser
getAttributeValue
WARNING: Could not decode attr value, using undecoded value instead:
ns=android, name=versionCode, value=0x050382d1
brut.androlib.AndrolibException: Invalid value type: 0
at
brut.androlib.res.data.value.ResValueFactory.factory(ResValueFactory.java:62)
at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:211)
at
brut.androlib.res.decoder.ARSCDecoder.readComplexEntry(ARSCDecoder.java:199)
at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:169)
at brut.androlib.res.decoder.ARSCDecoder.readConfig(ARSCDecoder.java:157)
at brut.androlib.res.decoder.ARSCDecoder.readType(ARSCDecoder.java:125)
at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:100)
at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:78)
at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
at
brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:605)
at
brut.androlib.res.AndrolibResources.loadFrameworkPkg(AndrolibResources.java:126)
at brut.androlib.res.data.ResTable.getPackage(ResTable.java:75)
at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:58)
at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:54)
at brut.androlib.res.decoder.ResAttrDecoder.decode(ResAttrDecoder.java:36)
at
brut.androlib.res.decoder.AXmlResourceParser.getAttributeValue(AXmlResourceParser.java:369)
at
org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeValue(XmlPullParserDelegate.java:69)
at
org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:267)
at
org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)
at
brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:83)
at
brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:141)
at
brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPullStreamDecoder.java:153)
at
brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecoder.java:131)
at
brut.androlib.res.AndrolibResources.decodeManifest(AndrolibResources.java:164)
at
io.appium.apktools.AndroidManifestActivityHelper.decodeManifestXML(AndroidManifestActivityHelper.java:27)
at io.appium.apktools.Main.main(Main.java:33)

Feb 05, 2018 8:26:35 AM brut.androlib.res.decoder.AXmlResourceParser
getAttributeValue
WARNING: Could not decode attr value, using undecoded value instead:
ns=android, name=versionName, value=0x0000012d
brut.androlib.AndrolibException: Invalid value type: 0
at
brut.androlib.res.data.value.ResValueFactory.factory(ResValueFactory.java:62)
at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:211)
at
brut.androlib.res.decoder.ARSCDecoder.readComplexEntry(ARSCDecoder.java:199)
at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:169)
at brut.androlib.res.decoder.ARSCDecoder.readConfig(ARSCDecoder.java:157)
at brut.androlib.res.decoder.ARSCDecoder.readType(ARSCDecoder.java:125)
at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:100)
at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:78)
at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
at
brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:605)
at
brut.androlib.res.AndrolibResources.loadFrameworkPkg(AndrolibResources.java:126)
at brut.androlib.res.data.ResTable.getPackage(ResTable.java:75)
at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:58)
at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:54)
at brut.androlib.res.decoder.ResAttrDecoder.decode(ResAttrDecoder.java:36)
at
brut.androlib.res.decoder.AXmlResourceParser.getAttributeValue(AXmlResourceParser.java:369)
at
org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeValue(XmlPullParserDelegate.java:69)
at
org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:267)
at
org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)
at
brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:83)
at
brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:141)
at
brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPullStreamDecoder.java:153)
at
brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecoder.java:131)
at
brut.androlib.res.AndrolibResources.decodeManifest(AndrolibResources.java:164)
at
io.appium.apktools.AndroidManifestActivityHelper.decodeManifestXML(AndroidManifestActivityHelper.java:27)
at io.appium.apktools.Main.main(Main.java:33)

Exception in thread "main" java.lang.NullPointerException
at java.io.Writer.write(Writer.java:157)
at
brut.androlib.res.util.ExtMXSerializer.writeAttributeValue(ExtMXSerializer.java:38)
at org.xmlpull.mxp1_serializer.MXSerializer.attribute(MXSerializer.java:673)
at
org.xmlpull.v1.wrapper.classic.XmlSerializerDelegate.attribute(XmlSerializerDelegate.java:106)
at
org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:267)
at
org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)
at
brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:83)
at
brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:141)
at
brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPullStreamDecoder.java:153)
at
brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecoder.java:131)
at
brut.androlib.res.AndrolibResources.decodeManifest(AndrolibResources.java:164)
at
io.appium.apktools.AndroidManifestActivityHelper.decodeManifestXML(AndroidManifestActivityHelper.java:27)
at io.appium.apktools.Main.main(Main.java:33)

**Comment by mykola-mokhnach** [comment]
Please try the if recent appium beta works for you

**Comment by donsmart86** [comment]
*Fails to locate apkanalyzer for this reason:*

2018-02-08 18:11:38:535 - info: [Appium] Welcome to Appium v1.8.0-beta3
...
2018-02-08 18:11:51:747 - info: [debug] [AndroidDriver] Parsing package and
activity from app manifest
2018-02-08 18:11:51:749 - info: [ADB] Using the alternative activity name
detection method because of: Cannot read property 'getBinaryFromSdkRoot' of
null

*My environment is:*

MacBook-Pro:~ don.smart$ printenv ANDROID_HOME
/Users/don.smart/Library/Android/sdk
MacBook-Pro:~ don.smart$ which apkanalyzer
/Users/don.smart/Library/Android/sdk/tools/bin/apkanalyzer

*Appium server log is attached.*

**Comment by mykola-mokhnach** [comment]
Can you please update and try again?

**Comment by donsmart86** [comment]
Never mind, I found your changes.  That works. Thanks.

**Comment by mykola-mokhnach** [comment]
Cool. Thanks for checking. 

Please let us know if there are any there compatibility issues or create a PR yourself ;)
