### ISSUE TITLE
An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65"

### ISSUE THREAD

**Issue by UtopiaHXM** [appium/appium#10131]
## The problem

hello, when I start appium-desktop and run my case with python , the situation appeared as follow,there is no error, but something weird , the server port is 0:
2018-02-05 20:23:28.409959+0800 WebDriverAgentRunner-Runner[235:5782] Running tests...
2018-02-05 20:23:29.747533+0800 WebDriverAgentRunner-Runner[235:5782] Continuing to run tests in the background with task ID 1
Test Suite 'All tests' started at 2018-02-05 20:23:31.012
Test Suite 'WebDriverAgentRunner.xctest' started at 2018-02-05 20:23:31.014
Test Suite 'UITestingUITests' started at 2018-02-05 20:23:31.015
Test Case '-[UITestingUITests testRunner]' started.
    t =     0.01s Start Test at 2018-02-05 20:23:31.027
    t =     0.01s Set Up
2018-02-05 20:23:31.041109+0800 WebDriverAgentRunner-Runner[235:5782] Built at Feb  5 2018 20:23:38
2018-02-05 20:23:31.077423+0800 WebDriverAgentRunner-Runner[235:5782] ServerURLHere->http://30.28.181.181:0<-ServerURLHere

I dont know why the port 0 is used, and i couldn't access the above url,either.
 
## Environment

Appium v1.7.2
info AppiumDoctor Appium Doctor v.1.4.3
info AppiumDoctor ### Diagnostic starting ###
info AppiumDoctor  ✔ The Node.js binary was found at: /usr/local/bin/node
info AppiumDoctor  ✔ Node version is 6.12.0
info AppiumDoctor  ✔ Xcode is installed at: /Applications/Xcode.app/Contents/Developer
info AppiumDoctor  ✔ Xcode Command Line Tools are installed.
info AppiumDoctor  ✔ DevToolsSecurity is enabled.
info AppiumDoctor  ✔ The Authorization DB is set up properly.
info AppiumDoctor  ✔ Carthage was found at: /usr/local/bin/carthage
info AppiumDoctor  ✔ HOME is set to: /Users/rolanda
info AppiumDoctor ### Diagnostic completed, no fix needed. ###
info AppiumDoctor 
info AppiumDoctor Everything looks good, bye!
info AppiumDoctor 

## Details
the follow pic shows my sign information of webdriveragent in appium: 
![image](https://user-images.githubusercontent.com/9431757/35804679-b71570f2-0ab3-11e8-9233-49ca53a77c2a.png)
## Link to Appium logs

The server is running

[Appium] Welcome to Appium v1.7.2
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"requiredCapabilities":{},"desiredCapabilities":{"deviceName":"iPhone","udid":"49b3de4c9fbb7d03809b55be47ef09fbbeb3fdd0","app":"/Users/rolanda/Desktop/appiumSimpleDemo/build/Release-iphoneos/appiumSimpleDemo.app","platformVersion":"10.3.3","platformName":"iOS","bundleId":"com.autonavi.amap"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"deviceName":"iPhone","udid":"49b3de4c9fbb7d03809b55be47ef09fbbeb3fdd0","app":"/Users/rolanda/Desktop/appiumSimpleDemo/build/Release-iphoneos/appiumSimpleDemo.app","platformVersion":"10.3.3","platformName":"iOS","bundleId":"com.autonavi.amap"},{},null]
[BaseDriver] Event 'newSessionRequested' logged at 1517832808711 (20:13:28 GMT+0800 (CST))
[Appium] Requested iOS support with version >= 10, using XCUITest driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
[Appium] Creating new XCUITestDriver (v2.64.0) session
[Appium] Capabilities:
[Appium]   deviceName: iPhone
[Appium]   udid: 49b3de4c9fbb7d03809b55be47ef09fbbeb3fdd0
[Appium]   app: /Users/rolanda/Desktop/appiumSimpleDemo/build/Release-iphoneos/appiumSimpleDemo.app
[Appium]   platformVersion: 10.3.3
[Appium]   platformName: iOS
[Appium]   bundleId: com.autonavi.amap
[BaseDriver] Session created with session id: 459c4def-4279-4208-908f-10a94e8bc70b
[XCUITest] Current user: 'rolanda'
[XCUITest] Current version of libimobiledevice: stable 1.2.0 (bottled), HEAD
[XCUITest] Xcode version set to '9.1' (tools v9.2.0.0.1.1510905681)
[XCUITest] iOS SDK Version set to '11.1'
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1517832809534 (20:13:29 GMT+0800 (CST))
[XCUITest] Available devices: 
[XCUITest] Error: Unknown device or simulator UDID: '49b3de4c9fbb7d03809b55be47ef09fbbeb3fdd0'
    at XCUITestDriver.determineDevice$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:622:17)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at 
 Error: Unknown device or simulator UDID: '49b3de4c9fbb7d03809b55be47ef09fbbeb3fdd0'
    at XCUITestDriver.determineDevice$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:622:17)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at 
[XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[MJSONWP] Encountered internal error running command: Error: Unknown device or simulator UDID: '49b3de4c9fbb7d03809b55be47ef09fbbeb3fdd0'
    at XCUITestDriver.determineDevice$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:622:17)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at 
[HTTP] <-- POST /wd/hub/session 500 961 ms - 213 
[HTTP] --> POST /wd/hub/session {"requiredCapabilities":{},"desiredCapabilities":{"deviceName":"iPhone","udid":"49b3de4c9fbb7d03809b55be47ef09fbbeb3fdd0","app":"/Users/rolanda/Desktop/appiumSimpleDemo/build/Release-iphoneos/appiumSimpleDemo.app","platformVersion":"10.3.3","platformName":"iOS","bundleId":"com.autonavi.amap"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"deviceName":"iPhone","udid":"49b3de4c9fbb7d03809b55be47ef09fbbeb3fdd0","app":"/Users/rolanda/Desktop/appiumSimpleDemo/build/Release-iphoneos/appiumSimpleDemo.app","platformVersion":"10.3.3","platformName":"iOS","bundleId":"com.autonavi.amap"},{},null]
[BaseDriver] Event 'newSessionRequested' logged at 1517832863099 (20:14:23 GMT+0800 (CST))
[Appium] Requested iOS support with version >= 10, using XCUITest driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
[Appium] Creating new XCUITestDriver (v2.64.0) session
[Appium] Capabilities:
[Appium]   deviceName: iPhone
[Appium]   udid: 49b3de4c9fbb7d03809b55be47ef09fbbeb3fdd0
[Appium]   app: /Users/rolanda/Desktop/appiumSimpleDemo/build/Release-iphoneos/appiumSimpleDemo.app
[Appium]   platformVersion: 10.3.3
[Appium]   platformName: iOS
[Appium]   bundleId: com.autonavi.amap
[BaseDriver] Session created with session id: 7d5c80b2-1a77-408a-902e-5bd4ead7d8dd
[XCUITest] Current user: 'rolanda'
[XCUITest] Current version of libimobiledevice: stable 1.2.0 (bottled), HEAD
[XCUITest] Xcode version set to '9.1' (tools v9.2.0.0.1.1510905681)
[XCUITest] iOS SDK Version set to '11.1'
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1517832863909 (20:14:23 GMT+0800 (CST))
[XCUITest] Available devices: 49b3de4c9fbb7d03809b55be47ef09fbbeb3fdd0
[XCUITest] Creating iDevice object with udid '49b3de4c9fbb7d03809b55be47ef09fbbeb3fdd0'
[XCUITest] Determining device to run tests on: udid: '49b3de4c9fbb7d03809b55be47ef09fbbeb3fdd0', real device: true
[BaseDriver] Using local app '/Users/rolanda/Desktop/appiumSimpleDemo/build/Release-iphoneos/appiumSimpleDemo.app'
[BaseDriver] Event 'appConfigured' logged at 1517832864048 (20:14:24 GMT+0800 (CST))
[XCUITest] Checking whether app '/Users/rolanda/Desktop/appiumSimpleDemo/build/Release-iphoneos/appiumSimpleDemo.app' is actually present on file system
[XCUITest] App is present
[BaseDriver] Event 'resetStarted' logged at 1517832864048 (20:14:24 GMT+0800 (CST))
[XCUITest] Reset: running ios real device reset flow
[BaseDriver] Event 'resetComplete' logged at 1517832864048 (20:14:24 GMT+0800 (CST))
[iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[iOSLog] Starting iOS device log capture with: 'idevicesyslog'
[XCUITest] Cannot get the name of the crashes folder for the device with udid '49b3de4c9fbb7d03809b55be47ef09fbbeb3fdd0'. Original error: Command 'idevicename -u 49b3de4c9fbb7d03809b55be47ef09fbbeb3fdd0' exited with code 255
[BaseDriver] Event 'logCaptureStarted' logged at 1517832864436 (20:14:24 GMT+0800 (CST))
[XCUITest] Setting up real device
[XCUITest] Reset requested. Removing app with id 'com.autonavi.amap' from the device
[XCUITest] Installing '/Users/rolanda/Desktop/appiumSimpleDemo/build/Release-iphoneos/appiumSimpleDemo.app' on device with UUID '49b3de4c9fbb7d03809b55be47ef09fbbeb3fdd0'...
[XCUITest] The app has been installed successfully.
[BaseDriver] Event 'appInstalled' logged at 1517832875171 (20:14:35 GMT+0800 (CST))
[XCUITest] Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] WDA is not listening at 'http://localhost:8100/'
[BaseDriver] Event 'wdaStartAttempted' logged at 1517832875241 (20:14:35 GMT+0800 (CST))
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Killing running processes 'xcodebuild.*49b3de4c9fbb7d03809b55be47ef09fbbeb3fdd0, iproxy 8100' for the device 49b3de4c9fbb7d03809b55be47ef09fbbeb3fdd0...
[XCUITest] 'pgrep -nif xcodebuild.*49b3de4c9fbb7d03809b55be47ef09fbbeb3fdd0' didn't detect any matching processes. Return code: 1
[XCUITest] 'pgrep -nif iproxy 8100' didn't detect any matching processes. Return code: 1
[XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[XCUITest] Using Xcode 9.1, so fixing WDA codebase
[XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=49b3de4c9fbb7d03809b55be47ef09fbbeb3fdd0 IPHONEOS_DEPLOYMENT_TARGET=10.3' in directory '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Output from xcodebuild will not be logged. To see xcode logging, use 'showXcodeLog' desired capability
[XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Log file for xcodebuild test: /var/folders/wr/xff34fn10915ktltrrdrkbcm0000gn/T/com.apple.dt.XCTest/IDETestRunSession-E2D5D550-76FD-4C75-8BA6-99D9CD846C16/WebDriverAgentRunner-BC762EF7-639A-4FFC-B403-104C1CADC41E/Session-WebDriverAgentRunner-2018-02-05_201442-6vSNl9.log
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[Xcode] 2018-02-05 20:14:46.776 xcodebuild[33308:42459540] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[Xcode] 2018-02-05 20:14:16.550523+0800 WebDriverAgentRunner-Runner[215:4032] Running tests...
[Xcode] 2018-02-05 20:14:16.614154+0800 WebDriverAgentRunner-Runner[215:4032] 未能载入软件包“WebDriverAgentRunner”，因为它已损坏或丢失必要的资源。 请尝试重新安装软件包。
[Xcode] 2018-02-05 20:14:16.614243+0800 WebDriverAgentRunner-Runner[215:4032] (dlopen_preflight(/var/containers/Bundle/Application/CEFBBCEE-FB88-41D7-B93D-0E6619BA8B04/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner): Library not loaded: @rpath/RoutingHTTPServer.framework/RoutingHTTPServer
[Xcode]   Referenced from: /private/var/containers/Bundle/Application/CEFBBCEE-FB88-41D7-B93D-0E6619BA8B04/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib
[Xcode]   Reason: no suitable image found.  Did find:
[Xcode] 	/private/var/containers/Bundle/Application/CEFBBCEE-FB88-41D7-B93D-0E6619BA8B04/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer: required code signature missing for '/private/var/containers/Bundle/Application/CEFBBCEE-FB88-41D7-B93D-0E6619BA8B04/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer'
[Xcode] )
[Xcode] 
[XCUITest] xcodebuild exited with code '65' and signal 'null'
[BaseDriver] Event 'wdaStartFailed' logged at 1517832887002 (20:14:47 GMT+0800 (CST))
[XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
[XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down iproxy process (pid 33307)
[XCUITest] iproxy exited with code 'null'
[XCUITest] Removing WDA application from device
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
    at XCUITestDriver.quitAndUninstall$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:375:13)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at 
 **Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
    at XCUITestDriver.quitAndUninstall$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:375:13)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at** 
[XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
    at XCUITestDriver.quitAndUninstall$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:375:13)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at 
[HTTP] <-- POST /wd/hub/session 500 24274 ms - 470

**Comment by UtopiaHXM** [comment]
looking forward to your reply

**Comment by trix0** [comment]
here #10106  like 5 issues bellow :) try to use search next time It ll save you some time

**Comment by mykola-mokhnach** [comment]
> [XCUITest] Error: Unknown device or simulator UDID: '49b3de4c9fbb7d03809b55be47ef09fbbeb3fdd0'

This means the device with given id is not connected to the machine or is not visible. Use `idevice_id -l` command to see the list of connected device ids.

closed as not an issue

**Comment by UtopiaHXM** [comment]
the error of unknow device perhaps is privious，not an issue, the real matter is code 65

**Comment by mykola-mokhnach** [comment]
Error 65 means that WDA source is not signed properly and thus cannot be deployed on the device.
