### ISSUE TITLE
Emulator start failed with wrong args when use isHeadless option

### ISSUE THREAD

**Issue by rainmanwy** [appium/appium#10177]
## The problem
```
[debug] [ADB] Running '/opt/android-sdk/emulator/emulator' with args: ["-avd","my26","null","-no-window"]
[debug] [ADB] Trying to find my26 emulator
[debug] [ADB] Getting connected emulators
[debug] [ADB] Getting connected devices...
[ADB] [AVD OUTPUT] invalid command-line parameter: null.
[ADB] [AVD OUTPUT] Hint: use '@foo' to launch a virtual device named 'foo'.
[ADB] [AVD OUTPUT] please use -help for more information
[ADB] Error: Emulator avd my26 exit with code 1, signal null
```

## Environment

* Appium 1.7.2
* Desktop OS/version used to run Appium:  Deepin linux 15.5
* Node.js version (unless using Appium.app|exe): v6.3.1
* Real device or emulator/simulator: emulator
* python client version:  Appium-Python-Client==0.26

## Details

step 1: start appium with command "appium"
step 2: use python client to start emulator. 
```
>>> dc = {
...     'avd': 'my26',
...     'appPackage': 'com.github.rainmanwy.firstapp',
...     'platformVersion': '5.1',
...     'isHeadless': 'true',
...     'automationName': 'Appium',
...     'app': '/home/rainman/workspace/app-debug.apk',
...     'appActivity': 'MainActivity',
...     'deviceName': 'my22:5554',
...     'platformName': 'Android'
... }

>>> 
>>> 
>>> d = webdriver.Remote('http://127.0.0.1:4723/wd/hub', dc)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/appium/webdriver/webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 310, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/remote_connection.py", line 466, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/remote_connection.py", line 528, in _request
    resp = opener.open(request, timeout=self._timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.5/urllib/request.py", line 1257, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
```

appium log:
```
[Appium] Welcome to Appium v1.7.2
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"capabilities":{"firstMatch":[{}],"alwaysMatch":{"platformName":"Android"}},"desiredCapabilities":{"appPackage":"com.github.rainmanwy.firstapp","avd":"my26","isHeadless":"true","platformVersion":"5.1","automationName":"Appium","app":"/home/rainman/workspace/app-debug.apk","appActivity":"MainActivity","deviceName":"my22:5554","platformName":"Android"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"appPackage":"com.github.rainmanwy.firstapp","avd":"my26","isHeadless":"true","platformVersion":"5.1","automationName":"Appium","app":"/home/rainman/workspace/app-debug.apk","appActivity":"MainActivity","deviceName":"my22:5554","platformName":"Android"},null,{"firstMatch":[{}],"alwaysMatch":{"platformName":"Android"}}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1518407650611 (11:54:10 GMT+0800 (CST))
[Appium] Merged W3C capabilities {"firstMatch":[{}],"alwaysMatch":{"platformName... into desiredCapabilities object {"appPackage":"com.github.rainmanwy.firstapp","...
[Appium] Creating new AndroidDriver (v1.37.0) session
[Appium] Capabilities:
[Appium]   appPackage: com.github.rainmanwy.firstapp
[Appium]   avd: my26
[Appium]   isHeadless: true
[Appium]   platformVersion: 5.1
[Appium]   automationName: Appium
[Appium]   app: /home/rainman/workspace/app-debug.apk
[Appium]   appActivity: MainActivity
[Appium]   deviceName: my22:5554
[Appium]   platformName: Android
[BaseDriver] Capability 'isHeadless' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] Session created with session id: b1aadac7-905a-442f-8e39-fb90f677583e
[debug] [AndroidDriver] Getting Java version
[AndroidDriver] Java version is: 1.8.0_141
[ADB] Checking whether adb is present
[ADB] Using adb from /opt/android-sdk/platform-tools/adb
[debug] [ADB] Trying to find my26 emulator
[debug] [ADB] Getting connected emulators
[debug] [ADB] Getting connected devices...
[debug] [ADB] 0 device(s) connected
[debug] [ADB] 0 emulator(s) connected
[debug] [ADB] Emulator my26 not running
[debug] [ADB] Launching Emulator with AVD my26, launchTimeout60000 ms and readyTimeout 60000 ms
[ADB] Checking whether emulator is present
[ADB] Using emulator from /opt/android-sdk/emulator/emulator
[ADB] Checking whether emulator is present
[debug] [ADB] Running '/opt/android-sdk/emulator/emulator' with args: ["-avd","my26","null","-no-window"]
[debug] [ADB] Trying to find my26 emulator
[debug] [ADB] Getting connected emulators
[debug] [ADB] Getting connected devices...
[ADB] [AVD OUTPUT] invalid command-line parameter: null.
[ADB] [AVD OUTPUT] Hint: use '@foo' to launch a virtual device named 'foo'.
[ADB] [AVD OUTPUT] please use -help for more information
[debug] [ADB] 0 device(s) connected
[debug] [ADB] 0 emulator(s) connected
[debug] [ADB] Emulator my26 not running
[ADB] Error: Emulator avd my26 exit with code 1, signal null
    at Object.wrappedLogger.errorAndThrow (/usr/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:69:13)
    at SubProcess.<anonymous> (/usr/lib/node_modules/appium/node_modules/appium-adb/lib/tools/system-calls.js:619:11)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (/usr/lib/node_modules/appium/node_modules/teen_process/lib/teen_process.js:234:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
 Error: Emulator avd my26 exit with code 1, signal null
    at Object.wrappedLogger.errorAndThrow (/usr/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:69:13)
    at SubProcess.<anonymous> (/usr/lib/node_modules/appium/node_modules/appium-adb/lib/tools/system-calls.js:619:11)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (/usr/lib/node_modules/appium/node_modules/teen_process/lib/teen_process.js:234:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
uncaughtException: Emulator avd my26 exit with code 1, signal null
	{"date":"Mon Feb 12 2018 11:54:10 GMT+0800 (CST)","process":{"pid":20824,"uid":1000,"gid":1000,"cwd":"/home/rainman","execPath":"/usr/bin/nodejs","version":"v6.3.1","argv":["/usr/bin/nodejs","/usr/bin/appium"],"memoryUsage":{"rss":164335616,"heapTotal":141213696,"heapUsed":90332600}},"os":{"loadavg":[1.9326171875,1.82080078125,1.78955078125],"uptime":98178},"trace":[{"column":13,"file":"/usr/lib/node_modules/appium/node_modules/appium-support/lib/logging.js","function":"Object.wrappedLogger.errorAndThrow","line":69,"method":"errorAndThrow","native":false},{"column":11,"file":"/usr/lib/node_modules/appium/node_modules/appium-adb/lib/tools/system-calls.js","function":null,"line":619,"method":null,"native":false},{"column":13,"file":"events.js","function":"emitTwo","line":106,"method":null,"native":false},{"column":7,"file":"events.js","function":"SubProcess.emit","line":191,"method":"emit","native":false},{"column":14,"file":"/usr/lib/node_modules/appium/node_modules/teen_process/lib/teen_process.js","function":null,"line":234,"method":null,"native":false},{"column":13,"file":"events.js","function":"emitTwo","line":106,"method":null,"native":false},{"column":7,"file":"events.js","function":"ChildProcess.emit","line":191,"method":"emit","native":false},{"column":12,"file":"internal/child_process.js","function":"Process.ChildProcess._handle.onexit","line":204,"method":"onexit","native":false}],"stack":["Error: Emulator avd my26 exit with code 1, signal null","    at Object.wrappedLogger.errorAndThrow (/usr/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:69:13)","    at SubProcess.<anonymous> (/usr/lib/node_modules/appium/node_modules/appium-adb/lib/tools/system-calls.js:619:11)","    at emitTwo (events.js:106:13)","    at SubProcess.emit (events.js:191:7)","    at ChildProcess.<anonymous> (/usr/lib/node_modules/appium/node_modules/teen_process/lib/teen_process.js:234:14)","    at emitTwo (events.js:106:13)","    at ChildProcess.emit (events.js:191:7)","    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)"]}
```

**Comment by rainmanwy** [comment]
it works. Thank you very much!

**Comment by imurchie** [comment]
`appium-android-driver@2.0.1` ought to fix this. Re-install Appium@beta and try again!
