### ISSUE TITLE
iOS native app execution over wifi fails

### ISSUE THREAD

**Issue by lahiruw** [appium/appium#10182]
Hi Frieds ,
Need a help from you'll . i'm trying to execute a native app over wireless debugging .what happens here is app loads login page and exits soon  . Let me know if theres any suggestion to over come this issue .Android apps executes fine with wireless debugging .Even same app works fine when connected through cable .

Device details
---------------
iPhone 6 -11.2
xcode - 9.2
appium - 1.6.4
Web inspector enabled .

Error Log
----------
`Appium has been started
Running test - testInvAssociateUserCanSeeInventoryOptions
[iOS] Error: Timed out waiting for ios_webkit_debug_proxy to open
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at IWDP.start$ (../../lib/iwdp.js:61:14)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
 Error: Timed out waiting for ios_webkit_debug_proxy to open
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at IWDP.start$ (../../lib/iwdp.js:61:14)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
[XCUITest] Error: Could not start ios_webkit_debug_proxy server: Timed out waiting for ios_webkit_debug_proxy to open
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at XCUITestDriver.start$ (../../lib/driver.js:336:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
 Error: Could not start ios_webkit_debug_proxy server: Timed out waiting for ios_webkit_debug_proxy to open
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at XCUITestDriver.start$ (../../lib/driver.js:336:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
[XCUITest] Error: Could not start ios_webkit_debug_proxy server: Timed out waiting for ios_webkit_debug_proxy to open
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at XCUITestDriver.start$ (../../lib/driver.js:336:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
 Error: Could not start ios_webkit_debug_proxy server: Timed out waiting for ios_webkit_debug_proxy to open
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at XCUITestDriver.start$ (../../lib/driver.js:336:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
[MJSONWP] Encountered internal error running command: Error: Could not start ios_webkit_debug_proxy server: Timed out waiting for ios_webkit_debug_proxy to open
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at XCUITestDriver.start$ (../../lib/driver.js:336:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
Result: SKIPPED
`

**Comment by lahiruw** [comment]
@imurchie Hope you are an expert in this type of issues .Sorry if i troubling you , but this is a burning issue in my project .....

**Comment by mykola-mokhnach** [comment]
We don't test testing automation over Wi-Fi and don't support it officially, so issues there are quite possible.

**Comment by lahiruw** [comment]
@mykola-mokhnach Thanks a lot , but at least any idea about the error occurred ?

**Comment by lahiruw** [comment]
Any ideas from others pls ? Any one tried doing this ?

**Comment by andreiaionitoaiesv** [comment]
I've managed to run some tests on iOS native app over WiFi, but it is very flaky. After a while it doesn't work anymore, either doesn't find the phone, or doesn't start a session. Anyone else with some more updates?
