### ISSUE TITLE
Error in waiting for device. Original error: 'Error executing adbExec. 

### ISSUE THREAD

**Issue by KUbhaya** [appium/appium#10213]
## The problem

I am trying to execute the basic Appium program and got the following error while executing.
Error: Error in waiting for device. Original error: 'Error executing adbExec. Original error: 'Command 'C\:\\Users\\kanchana.u\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 wait-for-device' timed out after 10000ms'; Stderr: ''; Code: 'null''. Retrying by restarting ADB

## Environment

Windows 10 Pro 64x
Appium version 1.7.2
java-client-6.0.0-BETA2 
selenium-java-3.8.1
jdk-8u161-windows-x64
android-studio-ide-171.4443003-windows
Virtual Device: 1080 × 1920: 420dpi | 25 | Android 7.1.1 (Google Play) | x86 | 2 GB |
Eclipse: luna

## Link to Appium logs

Error: Error in waiting for device. Original error: 'Error executing adbExec. Original error: 'Command 'C\:\\Users\\kanchana.u\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 wait-for-device' timed out after 10000ms'; Stderr: ''; Code: 'null''. Retrying by restarting ADB
    at Object.wrappedLogger.errorAndThrow (C:\Users\kanchana.u\AppData\Roaming\npm\node_modules\appium\node_modules\appium-support\lib\logging.js:69:13)
    at ADB.callee$1$0$ (C:\Users\kanchana.u\AppData\Roaming\npm\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:737:11)
    at tryCatch (C:\Users\kanchana.u\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\kanchana.u\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\kanchana.u\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\kanchana.u\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at <anonymous>

## Code To Reproduce Issue [ Good To Have ]
package mobile;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.android.AndroidElement;
import io.appium.java_client.remote.MobileCapabilityType;

import org.openqa.selenium.remote.DesiredCapabilities;

public class base {

	public static void main(String[] args) throws MalformedURLException {
		// TODO Auto-generated method stub

		// Appium code
		
		File f=new File("src");
		File fs=new File(f,"ApiDemos-debug.apk");
		
		DesiredCapabilities cap=new DesiredCapabilities();
		cap.setCapability(MobileCapabilityType.DEVICE_NAME, "Demo");
		cap.setCapability("avd","Demo");
		cap.setCapability(MobileCapabilityType.APP, fs.getAbsolutePath());
		AndroidDriver<AndroidElement> driver=new AndroidDriver<>(new URL("http://127.0.0.1:4723/wd/hub"),cap);
	}

}

I am new to the appium coding. please help me.

**Comment by mykola-mokhnach** [comment]
This looks more like a problem with the emulator or a slow machine. Are you able to start it manually?

**Comment by KUbhaya** [comment]
yes I started manually. Emulator is opened. When code is running still displays error.

**Comment by mykola-mokhnach** [comment]
What is the output of `emulator -list-avds` command?

**Comment by abhilashshettigartrt** [comment]
hey @mykola-mokhnach i am getting same issue,will you help me out it with 
and the result giving my Test device name

**Comment by vidyasagarpogiri** [comment]
Hi Im facing the below error , please find my logs .


[ADB] Error: Error in waiting for device. Original error: 'Error executing adbExec. Original error: 'Command 'C\:\\Users\\vidhyasagarp\\android-sdk_r24.4.1-windows\\android-sdk-windows\\platform-tools\\adb.exe -P 5037 -s emulator-5554 wait-for-device' timed out after 10000ms'; Stderr: ''; Code: 'null''. Retrying by restarting ADB
    at Object.wrappedLogger.errorAndThrow (C:\Users\vidhyasagarp\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:69:13)
    at ADB.callee$1$0$ (C:\Users\vidhyasagarp\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:737:11)
    at tryCatch (C:\Users\vidhyasagarp\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\vidhyasagarp\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\vidhyasagarp\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\vidhyasagarp\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at 
 Error: Error in waiting for device. Original error: 'Error executing adbExec. Original error: 'Command 'C\:\\Users\\vidhyasagarp\\android-sdk_r24.4.1-windows\\android-sdk-windows\\platform-tools\\adb.exe -P 5037 -s emulator-5554 wait-for-device' timed out after 10000ms'; Stderr: ''; Code: 'null''. Retrying by restarting ADB
    at Object.wrappedLogger.errorAndThrow (C:\Users\vidhyasagarp\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:69:13)
    at ADB.callee$1$0$ (C:\Users\vidhyasagarp\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:737:11)
    at tryCatch (C:\Users\vidhyasagarp\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\vidhyasagarp\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\vidhyasagarp\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\vidhyasagarp\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at 
[AndroidDriver] Shutting down Android driver
[AndroidDriver] Called deleteSession but bootstrap wasn't active
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\vidhyasagarp\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","am","force-stop","io.appium.unlock"]
[ADB] Running 'C:\Users\vidhyasagarp\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","am","force-stop","io.appium.unlock"]
[MJSONWP] Encountered internal error running command: Error: Error in waiting for device. Original error: 'Error executing adbExec. Original error: 'Command 'C\:\\Users\\vidhyasagarp\\android-sdk_r24.4.1-windows\\android-sdk-windows\\platform-tools\\adb.exe -P 5037 -s emulator-5554 wait-for-device' timed out after 10000ms'; Stderr: ''; Code: 'null''. Retrying by restarting ADB
    at Object.wrappedLogger.errorAndThrow (C:\Users\vidhyasagarp\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:69:13)
    at ADB.callee$1$0$ (C:\Users\vidhyasagarp\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:737:11)
    at tryCatch (C:\Users\vidhyasagarp\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\vidhyasagarp\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\vidhyasagarp\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\vidhyasagarp\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at 
[HTTP] <-- POST /wd/hub/session 500 72614 ms - 468

**Comment by SuryakiranP** [comment]
Error getting device platform version. Original error: Error executing adbExec. Original error: 'Command 'C\:\\Users\\suryakiranp\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s 02157df29af5152e shell getprop ro.build.version.release' exited with code 3221226356'; Stderr: ''; Code: '3221226356'
[MJSONWP]     at ADB.callee$0$0$ (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\adb-commands.js:93:11)
[MJSONWP]     at tryCatch (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[MJSONWP]     at run (C:\Program Files (x86)\Appium\resources\app\webpack:\~\babel-polyfill\~\core-js\modules\es6.promise.js:75:1)
[MJSONWP]     at C:\Program Files (x86)\Appium\resources\app\webpack:\~\babel-polyfill\~\core-js\modules\es6.promise.js:92:1
[MJSONWP]     at flush (C:\Program Files (x86)\Appium\resources\app\webpack:\~\babel-polyfill\~\core-js\modules\_microtask.js:18:1)
[MJSONWP]     at process._tickCallback (internal/process/next_tick.js:61:11)
[HTTP] <-- POST /wd/hub/session 500 5389 ms - 467
[HTTP] 
[HTTP] --> DELETE /wd/hub/session
[HTTP] {}
[HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- DELETE /wd/hub/session 404 3 ms - 57
[HTTP]

**Comment by SuryakiranP** [comment]
Can anyone give me the solution .

**Comment by mykola-mokhnach** [comment]
@SuryakiranP the only solution is to downgrade adb, as this is a bug in the recent Android SDK

**Comment by J4-D06-0041** [comment]
This is to confirm that the solution suggested by @mykola-mokhnach  is correct.
there appears to be a serious bug in the latest ADB version.

look for your android installation directory SDK and change the "tools" and "platform-tools" folders.

**Comment by SuryakiranP** [comment]
@mykola-mokhnach  I have resolved it by downgrading adb

**Comment by ABoterberg** [comment]
> This is to confirm that the solution suggested by @mykola-mokhnach is correct.
> there appears to be a serious bug in the latest ADB version.
> 
> look for your android installation directory SDK and change the "tools" and "platform-tools" folders.

Hi J4, what do you mean when u say change the folders? Could you please specify thank you in advance!

**Comment by J4-D06-0041** [comment]
> > This is to confirm that the solution suggested by @mykola-mokhnach is correct.
> > there appears to be a serious bug in the latest ADB version.
> > look for your android installation directory SDK and change the "tools" and "platform-tools" folders.
> 
> Hi J4, what do you mean when u say change the folders? Could you please specify thank you in advance!

Hello @ABoterberg,
sorry for the late reply, I was out on vacation earlier.
Anyway what I mean by that is you need to downgrade your API Level on the platform tools.

I think you are using the latest API (Level 28) Android 9.0 (Pie)... the thing is, that would cause an error when used together with appium,
I'm not quite sure yet as to what causes this but I had raised this issue to appium and android forums already.

I fixed this issue by doing the following:
Open Android Studio -> Tools -> SDK Manager -> install a lower API level.
Create a new Android Virtual device with the lower API level and that should fix the issue you are facing.

I hope this helps.
Good luck!

**Comment by ABoterberg** [comment]
> > > This is to confirm that the solution suggested by @mykola-mokhnach is correct.
> > > there appears to be a serious bug in the latest ADB version.
> > > look for your android installation directory SDK and change the "tools" and "platform-tools" folders.
> > 
> > 
> > Hi J4, what do you mean when u say change the folders? Could you please specify thank you in advance!
> 
> Hello @ABoterberg,
> sorry for the late reply, I was out on vacation earlier.
> Anyway what I mean by that is you need to downgrade your API Level on the platform tools.
> 
> I think you are using the latest API (Level 28) Android 9.0 (Pie)... the thing is, that would cause an error when used together with appium,
> I'm not quite sure yet as to what causes this but I had raised this issue to appium and android forums already.
> 
> I fixed this issue by doing the following:
> Open Android Studio -> Tools -> SDK Manager -> install a lower API level.
> Create a new Android Virtual device with the lower API level and that should fix the issue you are facing.
> 
> I hope this helps.
> Good luck!

I made a new emulator with an older Android version, it appears it was Android Q that was giving me the issue.. 
I'm not sure if this is the same (Issue?)/solution, but it seems connected.
