### ISSUE TITLE
I'm getting an error while finding ios native app element

### ISSUE THREAD

**Issue by JeevaTamil** [appium/appium#10229]
## The problem
I am testing iOS application. in the initial page, I need to tap on a button. I am getting below error:
**[MJSONWP] Encountered internal error running command: Error: An error occurred
    at JWProxy.command$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:176:15)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at 
[HTTP] <-- GET /wd/hub/session/78a0a9c6-0b25-46f2-a2a9-8468e2692db7 500 50 ms - 188 
[XCUITest] Connection to WDA timed out
[iProxy] recv failed: Operation not permitted**

##Code used 
simple find element command-> 
WebElement btn = driver.findElement(By.xpath("//*[@label= 'Allow & Sign in']"));

## Environment
* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacBook Pro/ 10.12.6 (16G29)
* Node.js version (unless using Appium.app|exe): v8.9.4
* Mobile platform/version under test: iPhone 6S Plus / iOS 11.0.3
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium.app

## Details
I can able to launch the application. In the application, I need to perform 3 swipes to reach the sign in button page and I can able to perform that swipe as well. My only problem is finding the element.

NOTE: I can able to find the element in The inspector.

## Link to Appium logs
<script src="https://gist.github.com/JeevaTamil/ff2427f9cffcf35352758c9ae75cf6a1.js"></script>

## Eclipse Error message
<script src="https://gist.github.com/JeevaTamil/8ffdc820a3e9456bd24dbd834f45a226.js"></script>

## Code To Reproduce Issue [ Good To Have ]
<script src="https://gist.github.com/JeevaTamil/67646eabc09bcb950f87b194e6c6c3ac.js"></script>

**Comment by mykola-mokhnach** [comment]
> [iProxy] recv failed: Operation not permitted

This means that webdriveragent stopped responding. Please report the issue to https://github.com/facebook/WebDriverAgent/issues. There is nothing that can be done there on Appium side

**Comment by JeevaTamil** [comment]
At least give me a suggestion Please..

**Comment by mykola-mokhnach** [comment]
Try not to use xpath locators
