### ISSUE TITLE
Appium for 1.8.0-based npm package can't be run

### ISSUE THREAD

**Issue by alexttransisland** [appium/appium#10223]
## The problem

`appium` from terminal can't be run

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0-*
* Last Appium version that did not exhibit the issue (if applicable): 1.7.2, 1.8.0-* as of 19.02.2018
* Desktop OS/version used to run Appium: MacOS (High Sierra)
* Node.js version (unless using Appium.app|exe): 9.5.0
* Mobile platform/version under test: N/A
* Real device or emulator/simulator: Does not matter
* Appium CLI or Appium.app|exe: npm-runner

## Details

After doing `npm install -g appium@1.8.0-beta`, `npm install -g appium@1.8.0-beta` -> `appium` as of 20.02.2018 the following issue occurs
```
Error: Cannot find module 'babel-runtime/helpers/asyncToGenerator'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/build/index.js:12:26)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/appium/build/lib/appium.js:49:29)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/appium/build/lib/main.js:43:15)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:190:16)
    at bootstrap_node.js:662:3
```
Though as of 19.02.2018 same commands worked well. For `npm install -g appium@1.7.2` everything works.

## Link to Appium logs

No logs avaiable since can't run `appium`

**Comment by mykola-mokhnach** [comment]
`npm i -g babel-runtime` helps

**Comment by alexttransisland** [comment]
Thanks @mykola-mokhnach

**Comment by mykola-mokhnach** [comment]
This should be fixed now
