### ISSUE TITLE
Appium CLI doesn't pass capabilities args

### ISSUE THREAD

**Issue by BuKT** [appium/appium#10220]
Appium v.1.7.2 installed via npm over Win10 and running with node.js 8.9.1, connected to Xiaomi Mi5 with MIUI 9.2.1 (Android 7)

When running from batch script with help of appium-java-client (5.0.0-BETA8) somehow on third `AppiumDriver.createSession`-call it mixes up the order of parameters. First two calls (for Unlock.app and Appium Settings) passes capabilities correctly. But my application itself fails with some `you forgot to define platformName capability` error. I found out, that [caps](https://github.com/appium/appium/blob/master/lib/appium.js#L63) argument is null this call, but unfortunatelly i'm not node-developer and can't find, why createSession callee mixes up the parameters

Short log for these three calls:

```
Calling AppiumDriver.createSession() with args:
[
	{
		"appPackage":"app.domain",
		"app":"Path\To\file.apk",
		"appActivity":"Activity.Domain.And.Name",
		"newCommandTimeout":120,
		"automationName":"UiAutomator2",
		"udid":"unique",
		"platformName":"Android",
		"deviceName":"Mi5"
	},
	{},
	[
		{
			"desiredCapabilities":{
				"appPackage":"app.domain",
				"app":"Path\To\file.apk",
				"appActivity":"Activity.Domain.And.Name",
				"newCommandTimeout":120,
				"automationName":"UiAutomator2",
				"udid":"unique",
				"platformName":"Android",
				"deviceName":"Mi5"
			}
		},
		{
			"requiredCapabilities":{}
		}
	]
]
//<...>
Calling AppiumDriver.createSession() with args:
[
	{
		"appPackage":"app.domain",
		"app":"Path\To\file.apk",
		"appActivity":"Activity.Domain.And.Name",
		"newCommandTimeout":120,
		"automationName":"UiAutomator2",
		"udid":"unique",
		"platformName":"Android",
		"deviceName":"Mi5"
	},
	{},
	null
]
//<...>
Calling AppiumDriver.createSession() with args:
[
	null,
	null,
	[
		{
			"desiredCapabilities":{
				"appPackage":"app.domain",
				"app":"Path\To\file.apk",
				"appActivity":"Activity.Domain.And.Name",
				"newCommandTimeout":120,
				"automationName":"UiAutomator2",
				"udid":"unique",
				"platformName":"Android",
				"deviceName":"Mi5"
			}
		},
		{
			"requiredCapabilities":{}
		}
	]
]
```

Full log for last call with stacktrace:

```
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [null,null,[{"desiredCapabilities":{"appPackage":"app.domain","app":"Path\To\file.apk","appActivity":"Activity.Domain.And.Name","newCommandTimeout":120,"automationName":"UiAutomator2","udid":"unique","platformName":"Android","deviceName":"MyDevice"}},{"requiredCapabilities":{}}]]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1519045424668 (16:03:44 GMT+0300 (RTZ 2 (зима)))
[MJSONWP] Encountered internal error running command: Error: You must include a platformName capability
    at AppiumDriver.getDriverForCaps (../../lib/appium.js:64:13)
    at AppiumDriver.createSession$ (../../lib/appium.js:180:28)
    at tryCatch (Path\To\Appium\appium\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (Path\To\Appium\appium\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (Path\To\Appium\appium\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at invoke (Path\To\Appium\appium\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at enqueueResult (Path\To\Appium\appium\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:185:17)
    at new Promise (<anonymous>)
    at new F (Path\To\Appium\appium\node_modules\appium\node_modules\core-js\library\modules\$.export.js:30:36)
    at AsyncIterator.enqueue (Path\To\Appium\appium\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (Path\To\Appium\appium\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at Object.runtime.async (Path\To\Appium\appium\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:209:12)
    at AppiumDriver.createSession (../../lib/appium.js:205:30)
    at AppiumDriver.executeCommand$ (../../../lib/basedriver/driver.js:246:27)
    at tryCatch (Path\To\Appium\appium\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (Path\To\Appium\appium\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (Path\To\Appium\appium\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at invoke (Path\To\Appium\appium\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at enqueueResult (Path\To\Appium\appium\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:185:17)
    at new Promise (<anonymous>)
    at new F (Path\To\Appium\appium\node_modules\appium\node_modules\core-js\library\modules\$.export.js:30:36)
    at AsyncIterator.enqueue (Path\To\Appium\appium\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (Path\To\Appium\appium\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at Object.runtime.async (Path\To\Appium\appium\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:209:12)
    at AppiumDriver.executeCommand (../../../lib/basedriver/driver.js:261:16)
    at AppiumDriver.executeCommand$ (../../lib/appium.js:24:19)
    at tryCatch (Path\To\Appium\appium\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (Path\To\Appium\appium\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (Path\To\Appium\appium\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at invoke (Path\To\Appium\appium\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at enqueueResult (Path\To\Appium\appium\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:185:17)
    at new Promise (<anonymous>)
    at new F (Path\To\Appium\appium\node_modules\appium\node_modules\core-js\library\modules\$.export.js:30:36)
    at AsyncIterator.enqueue (Path\To\Appium\appium\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (Path\To\Appium\appium\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at Object.runtime.async (Path\To\Appium\appium\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:209:12)
    at AppiumDriver.executeCommand (../../lib/appium.js:306:21)
    at asyncHandler$ (../../../lib/mjsonwp/mjsonwp.js:269:48)
    at tryCatch (Path\To\Appium\appium\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (Path\To\Appium\appium\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (Path\To\Appium\appium\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at invoke (Path\To\Appium\appium\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at enqueueResult (Path\To\Appium\appium\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:185:17)
    at new Promise (<anonymous>)
    at new F (Path\To\Appium\appium\node_modules\appium\node_modules\core-js\library\modules\$.export.js:30:36)
    at AsyncIterator.enqueue (Path\To\Appium\appium\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (Path\To\Appium\appium\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at Object.runtime.async (Path\To\Appium\appium\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:209:12)
    at asyncHandler (../../../lib/mjsonwp/mjsonwp.js:303:20)
    at ../../../lib/mjsonwp/mjsonwp.js:332:15
    at Layer.handle [as handle_request] (Path\To\Appium\appium\node_modules\appium\node_modules\express\lib\router\layer.js:95:5)
    at next (Path\To\Appium\appium\node_modules\appium\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (Path\To\Appium\appium\node_modules\appium\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (Path\To\Appium\appium\node_modules\appium\node_modules\express\lib\router\layer.js:95:5)
    at Path\To\Appium\appium\node_modules\appium\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (Path\To\Appium\appium\node_modules\appium\node_modules\express\lib\router\index.js:335:12)
    at next (Path\To\Appium\appium\node_modules\appium\node_modules\express\lib\router\index.js:275:10)
    at logger (Path\To\Appium\appium\node_modules\appium\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (Path\To\Appium\appium\node_modules\appium\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (Path\To\Appium\appium\node_modules\appium\node_modules\express\lib\router\index.js:317:13)
    at Path\To\Appium\appium\node_modules\appium\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (Path\To\Appium\appium\node_modules\appium\node_modules\express\lib\router\index.js:335:12)
    at next (Path\To\Appium\appium\node_modules\appium\node_modules\express\lib\router\index.js:275:10)
    at Path\To\Appium\appium\node_modules\appium\node_modules\body-parser\lib\read.js:125:5
    at invokeCallback (Path\To\Appium\appium\node_modules\appium\node_modules\raw-body\index.js:224:16)
    at done (Path\To\Appium\appium\node_modules\appium\node_modules\raw-body\index.js:213:7)
    at IncomingMessage.onEnd (Path\To\Appium\appium\node_modules\appium\node_modules\raw-body\index.js:273:7)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[HTTP] <-- POST /wd/hub/session 500 199 ms - 179

```

Any help is appreciated. Thank you for your attention

**Comment by vjmaiky** [comment]
seems something like: 
https://github.com/appium/appium/issues/10055

**Comment by mykola-mokhnach** [comment]
Are you sure you send correct capabilities data in the client script?

**Comment by BuKT** [comment]
Of course, i'm sure. You could check it yourself - there are logs with it. It just depersonalized before publicized

**Comment by mykola-mokhnach** [comment]
try to update the client lib to 6.0.0-BETA2

**Comment by mykola-mokhnach** [comment]
Also try to update Appium to the recent beta version - session creation algorithm has been slightly changed there

**Comment by BuKT** [comment]
Appium 1.7.2 is the most recent [release](https://libraries.io/npm/appium/versions).
Which version do you mean?

**Comment by mykola-mokhnach** [comment]
I mean appium@beta

**Comment by BuKT** [comment]
Still doesn't work. Same error, different stacktrace:

`[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [null,null,[{"desiredCapabilities":{"appPackage":"com.plarium.whetstone.dev","app":"C:\\Users\\flashader\\Desktop\\Whetstone_Testing_0-3-10-5.apk","appActivity":"com.plarium.unityactivitywrapper.UnityPlayerActivityWrapper","newCommandTimeout":120,"automationName":"UiAutomator2","udid":"2915f4d0","platformName":"Android","deviceName":"Mi5"}},{"requiredCapabilities":{}}]]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1519126399576 (14:33:19 GMT+0300 (RTZ 2 (зима)))
[MJSONWP] Encountered internal error running command: Error: You must include a platformName capability
    at AppiumDriver.getDriverForCaps (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\appium\lib\appium.js:64:13)
    at AppiumDriver.createSession$ (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\appium\lib\appium.js:202:28)
    at tryCatch (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at invoke (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at enqueueResult (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\babel-runtime\regenerator\runtime.js:185:17)
    at new Promise (<anonymous>)
    at new F (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\core-js\library\modules\$.export.js:30:36)
    at AsyncIterator.enqueue (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\babel-runtime\regenerator\runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at Object.runtime.async (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\babel-runtime\regenerator\runtime.js:209:12)
    at AppiumDriver.createSession (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\appium\build\lib\appium.js:293:34)
    at AppiumDriver.executeCommand$ (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\appium-base-driver\lib\basedriver\driver.js:277:27)
    at tryCatch (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at invoke (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at enqueueResult (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\babel-runtime\regenerator\runtime.js:185:17)
    at new Promise (<anonymous>)
    at new F (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\core-js\library\modules\$.export.js:30:36)
    at AsyncIterator.enqueue (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\babel-runtime\regenerator\runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at Object.runtime.async (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\babel-runtime\regenerator\runtime.js:209:12)
    at AppiumDriver.executeCommand (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\appium-base-driver\build\lib\basedriver\driver.js:261:34)
    at AppiumDriver.executeCommand$ (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\appium\lib\appium.js:24:19)
    at tryCatch (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at invoke (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at enqueueResult (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\babel-runtime\regenerator\runtime.js:185:17)
    at new Promise (<anonymous>)
    at new F (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\core-js\library\modules\$.export.js:30:36)
    at AsyncIterator.enqueue (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\babel-runtime\regenerator\runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at Object.runtime.async (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\babel-runtime\regenerator\runtime.js:209:12)
    at AppiumDriver.executeCommand (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\appium\build\lib\appium.js:621:34)
    at asyncHandler$ (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:257:48)
    at tryCatch (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at invoke (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at enqueueResult (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\babel-runtime\regenerator\runtime.js:185:17)
    at new Promise (<anonymous>)
    at new F (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\core-js\library\modules\$.export.js:30:36)
    at AsyncIterator.enqueue (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\babel-runtime\regenerator\runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at Object.runtime.async (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\babel-runtime\regenerator\runtime.js:209:12)
    at asyncHandler (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\appium-base-driver\build\lib\protocol\protocol.js:325:32)
    at C:\Program Files (x86)\AutoTestingPack\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:356:15
    at Layer.handle [as handle_request] (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\express\lib\router\layer.js:95:5)
    at C:\Program Files (x86)\AutoTestingPack\appium\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\express\lib\router\index.js:275:10)
    at logger (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\express\lib\router\index.js:317:13)
    at C:\Program Files (x86)\AutoTestingPack\appium\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\express\lib\router\index.js:275:10)
    at C:\Program Files (x86)\AutoTestingPack\appium\node_modules\body-parser\lib\read.js:130:5
    at invokeCallback (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\raw-body\index.js:224:16)
    at done (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\raw-body\index.js:213:7)
    at IncomingMessage.onEnd (C:\Program Files (x86)\AutoTestingPack\appium\node_modules\raw-body\index.js:273:7)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)`

**Comment by mykola-mokhnach** [comment]
@dpgraham can you please take a look?

**Comment by mykola-mokhnach** [comment]
To me it looks like you are trying to pass JSONWP capabilities in the argument, which should only contains W3C caps. Not sure why this happens though. Which client do you use? Can you provide the client code, which performs driver initialisation?

**Comment by BuKT** [comment]
[This one](https://github.com/bitbar/testdroid-samples/blob/master/image-recognition/src/main/java/AbstractAppiumTest.java#L89).

It's inside the js, not outer client, because other two calls (as described in the first post) are passing w/o errors.

**Comment by mykola-mokhnach** [comment]
What if you try to create new AndroidDriver instance instead of calling `resetApp`? Most likely the bug lies somewhere in this call

**Comment by BuKT** [comment]
`seretApp`-method never calling. Client-side fails at [this line](https://github.com/bitbar/testdroid-samples/blob/master/image-recognition/src/main/java/AbstractAppiumTest.java#L100) with `SessionNotCreated` exception

**Comment by mykola-mokhnach** [comment]
hm, can you show the output of `mvn dependency:tree`?

**Comment by BuKT** [comment]
> It's inside the js, not external client, because other two calls (as described in the first post) are passing w/o errors.

```
PS Path\To\Project> mvn dependency:tree
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Testing 0.9.3
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ Testing ---
[INFO] app.domain:Testing:jar:0.9.3
[INFO] +- ch.qos.logback:logback-classic:jar:1.1.7:compile
[INFO] |  \- ch.qos.logback:logback-core:jar:1.1.7:compile
[INFO] +- io.appium:java-client:jar:6.0.0-BETA2:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-java:jar:3.7.1:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-chrome-driver:jar:3.7.1:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-edge-driver:jar:3.7.1:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-firefox-driver:jar:3.7.1:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-ie-driver:jar:3.7.1:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-opera-driver:jar:3.7.1:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-remote-driver:jar:3.7.1:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-safari-driver:jar:3.7.1:compile
[INFO] |  |  +- net.bytebuddy:byte-buddy:jar:1.7.5:compile
[INFO] |  |  +- org.apache.commons:commons-exec:jar:1.3:compile
[INFO] |  |  +- commons-codec:commons-codec:jar:1.10:compile
[INFO] |  |  +- commons-logging:commons-logging:jar:1.2:compile
[INFO] |  |  +- com.google.guava:guava:jar:23.0:compile
[INFO] |  |  |  +- com.google.errorprone:error_prone_annotations:jar:2.0.18:compile
[INFO] |  |  |  +- com.google.j2objc:j2objc-annotations:jar:1.1:compile
[INFO] |  |  |  \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.14:compile
[INFO] |  |  \- org.apache.httpcomponents:httpcore:jar:4.4.6:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-support:jar:3.7.1:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-api:jar:3.7.1:compile
[INFO] |  +- com.google.code.gson:gson:jar:2.8.2:compile
[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.5.3:compile
[INFO] |  +- cglib:cglib:jar:3.2.5:compile
[INFO] |  |  +- org.ow2.asm:asm:jar:5.2:compile
[INFO] |  |  \- org.apache.ant:ant:jar:1.9.6:compile
[INFO] |  |     \- org.apache.ant:ant-launcher:jar:1.9.6:compile
[INFO] |  +- commons-validator:commons-validator:jar:1.6:compile
[INFO] |  |  +- commons-beanutils:commons-beanutils:jar:1.9.2:compile
[INFO] |  |  +- commons-digester:commons-digester:jar:1.8.1:compile
[INFO] |  |  \- commons-collections:commons-collections:jar:3.2.2:compile
[INFO] |  +- org.apache.commons:commons-lang3:jar:3.7:compile
[INFO] |  +- commons-io:commons-io:jar:2.6:compile
[INFO] |  +- org.springframework:spring-context:jar:5.0.2.RELEASE:compile
[INFO] |  |  +- org.springframework:spring-aop:jar:5.0.2.RELEASE:compile
[INFO] |  |  +- org.springframework:spring-beans:jar:5.0.2.RELEASE:compile
[INFO] |  |  +- org.springframework:spring-core:jar:5.0.2.RELEASE:compile
[INFO] |  |  |  \- org.springframework:spring-jcl:jar:5.0.2.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-expression:jar:5.0.2.RELEASE:compile
[INFO] |  +- org.aspectj:aspectjweaver:jar:1.8.13:compile
[INFO] |  \- org.openpnp:opencv:jar:3.2.0-1:compile
[INFO] +- com.testdroid:testdroid-api:jar:2.38:compile
[INFO] |  +- net.sf.json-lib:json-lib:jar:jdk15:2.4:compile
[INFO] |  |  +- commons-lang:commons-lang:jar:2.5:compile
[INFO] |  |  \- net.sf.ezmorph:ezmorph:jar:1.0.6:compile
[INFO] |  +- com.google.oauth-client:google-oauth-client:jar:1.15.0-rc:compile
[INFO] |  |  +- com.google.http-client:google-http-client:jar:1.15.0-rc:compile
[INFO] |  |  |  \- xpp3:xpp3:jar:1.1.4c:compile
[INFO] |  |  \- com.google.code.findbugs:jsr305:jar:1.3.9:compile
[INFO] |  +- com.google.api-client:google-api-client:jar:1.18.0-rc:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.6.0:compile
[INFO] |  \- com.fasterxml.jackson.core:jackson-databind:jar:2.6.0:compile
[INFO] |     \- com.fasterxml.jackson.core:jackson-core:jar:2.6.0:compile
[INFO] +- org.slf4j:slf4j-api:jar:1.7.4:compile
[INFO] +- org.json:json:jar:20151123:compile
[INFO] +- junit:junit:jar:4.12:compile
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:compile
[INFO] \- org.apache.maven:maven-artifact:jar:3.0.3:compile
[INFO]    \- org.codehaus.plexus:plexus-utils:jar:2.0.6:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.617 s
[INFO] Finished at: 2018-02-20T15:15:52+03:00
[INFO] Final Memory: 16M/309M
[INFO] ------------------------------------------------------------------------
```

**Comment by vjmaiky** [comment]
Just replace those methods with the ones which are marked as replacement for deprecated ones.
I would get all dependencies updated and try after that.

**Comment by BuKT** [comment]
Do you need additional logs?

**Comment by mykola-mokhnach** [comment]
I've never seen any similar reports, so I'd assume it's a client-side issue.
