### ISSUE TITLE
Error: Unable to launch WebDriverAgent because of xcodebuild failure:

### ISSUE THREAD

**Issue by gitsachin** [appium/appium#10241]
## The problem

Unable to launch WebDriverAgent because of xcodebuild failure: when I try to launch .app on iphone.

## Environment

* Appium version 1.7.2:
* xcode 9.3
* iOS 11.2
* Node v8.9.4
* Real device

## Link to Appium logs

[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
    at XCUITestDriver.quitAndUninstall$ (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:375:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>

**Comment by mykola-mokhnach** [comment]
Error 65 usually means that WDA sources are not signed properly. Closed duplicate
