### ISSUE TITLE
Encountered internal error running command: TypeError: Cannot read property 'async' of undefined

### ISSUE THREAD

**Issue by chunyang8866** [appium/appium#10254]
## The problem
Encountered internal error running command: TypeError: Cannot read property 'async' of undefined
    at XCUITestDriver.createSession (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/build/lib/driver.js:194:33)
    at AppiumDriver.createSession$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/lib/appium.js:224:41)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at 
    at process._tickCallback (internal/process/next_tick.js:109:7)

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):1.3.2
* Desktop OS/version used to run Appium:macOS10.13.3
* Node.js version (unless using Appium.app|exe):8.9.1
* Mobile platform/version under test:11.1
* Real device or emulator/simulator:iphone7plus
* Appium CLI or Appium.app|exe:camera360

**Comment by mykola-mokhnach** [comment]
Please provide the full log
