### ISSUE TITLE
[ADB] Incorrect package and activity when one activity start other activity

### ISSUE THREAD

**Issue by Valentine11** [appium/appium#10277]
## The problem

I have a fake activity for tests (call it FakeActivity) that opens another activity (call it NeededActivity) with parameters passed to it as a string. Here an ADB command example for this, which works fine:
`adb shell am start -n "com.app.package/com.FakeActivity" --es "activity" "com.NeededActivity" --es "params" "\[\{name='date',type='date',value='2018-05-12'\},\{name='can_return',type='boolean',value=false\}\]"`

I use in tests wd startActivity() method, like this:
```
let activity = {
            appPackage: 'com.app.package',
            appActivity: 'com.FakeActivity',
            optionalIntentArguments: ` --es "activity" "com.NeededActivity" --es "params" "\[\{name='date',type='date',value='2018-05-22'\},\{name='can_return',type='boolean',value=false\}\]"`
        };
return driver.startActivity(activity);
```

When I run the test, I see on device screen that the NeededActivity is open to me. But at this time, I see in appium logs that adb, apparently, is trying to verify that the first, FakeActivity has been opened:
```
[ADB] Getting focused package and activity
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\Valentine\path-to\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","dumpsys","window","windows"]
[ADB] Found package: 'com.app.package' and fully qualified activity name : 'com.NeededActivity'
[ADB] Incorrect package and activity. Retrying.
```

 And since the open activity and the initial does not match, it falls off with an error in timeout:
```
[ADB] Error: Error occured while starting App. Original error: 'com.FakeActivity' never started
    at Object.wrappedLogger.errorAndThrow (C:\Users\Valentine\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:69:13)
    at ADB.callee$0$0$ (C:\Users\Valentine\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\apk-utils.js:101:9)
    at tryCatch (C:\Users\Valentine\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\Valentine\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\Valentine\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\Valentine\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
etc
```
Is there are a workaround this problem? If no, what about implement it? TY.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2 desktop gui
* Last Appium version that did not exhibit the issue (if applicable): -
* Desktop OS/version used to run Appium: windows 10
* Mobile platform/version under test: andriod 7.1
* Real device or emulator/simulator: emulator locally

**Comment by mykola-mokhnach** [comment]
have you tried to play `waitActivity` option?

**Comment by Valentine11** [comment]
OMG of course! Its works! Thank you so much!!
