### ISSUE TITLE
Appium not executing test cases on the real device

### ISSUE THREAD

**Issue by santhoshsr** [appium/appium#10278]
## The problem

The appium can not start on device!
Trying Protractor test cases using appium and test cases are not executing on real android device.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Desktop OS/version used to run Appium: windows 7
* Node.js version (unless using Appium.app|exe): appium app latest version 1.3.2
* Mobile platform/version under test: Samsung Tab 2/ android 7.0
* Real device or emulator/simulator: Real device 
* Appium CLI or Appium.app|exe: Appium.exe

## Details

It seems appium can not install and run protractor test cases  to the real device and run it. I tried to run potractor test cases to test a webapp.
webapp is created using android webview activity.
I am facing below issue

[17:03:34] I/launcher - Running 1 instances of WebDriver
[17:03:34] I/hosted - Using the selenium server at http://localhost:4723/wd/hub
[17:04:19] E/launcher - An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: 502 - "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n<html>\n\n\n<head>\n  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=7\" />\n  <meta content=\"text/html; charset=UTF-8\" http-equiv=\"Content-Type\">\n  <title>McAfee Web Gateway - Notification</title>\n  <script src=\"/mwg-internal/de5fs23hu73ds/files/javascript/sw.js\" type=\"text/javascript\" ></script>\n  <link rel=\"stylesheet\" href=\"/mwg-internal/de5fs23hu73ds/files/default/stylesheet.css\" />\n</head>\n\n\n<body onload=\"swOnLoad();\">\n  <table class='bodyTable'>\n    <tr>\n      <td class='bodyData' background='/mwg-internal/de5fs23hu73ds/files/default/img/bg_body.gif'>\n\n<table class='logoTable'>\n  <tr>\n    <td class='logoData'>\n      <a href='http://www.com'>\n        <img src='/mwg-internal/de5fs23hu73ds/files/default/img/rc_mwg.gif'></a>\n    </td>\n  </tr>\n</table>\n\n\n\n\n<table class='titleTable' background='/mwg-internal/de5fs23hu73ds/files/default/img/bg_navbar.jpg'>\n  <tr>\n    <td class='titleData'>\n      Cannot Connect.\n    </td>\n  </tr>\n</table>\n\n\n\n<table class=\"contentTable\">\n  <tr>\n    <td class=\"contentData\">\n      The Proxy received an invalid response.\n    </td>\n  </tr>\n</table>\n\n\n\n<table class=\"infoTable\">\n  <tr>\n    <td class=\"infoData\">\n      <b>URL: </b>http://localhost:8200/wd/hub/status<br />\n<b>Client IP Address: 131.199.38.224 <br/>\n<b>Client URL: http://localhost:8200/wd/hub/status <br/>\n<b>Proxy: la3wgus01 <br/>\n    </td>\n  </tr>\n</table>\n\n\n\n\n<table class='policyTable'>\n  <tr>\n    <td class='policyHeading'>\n      <hr>\n      <a href=\"http://rweb.com/ent/rcdocs/rcollins/rpoleb002.pdf\">Use and Monitoring of Computing Resources</a>\n    </td>\n  </tr>\n  <tr>\n    <td class='policyData'>\n    </td>\n  </tr>\n</table>\n\n\n<table class='footTable'>\n  <tr>\n    <td class='helpDeskData'
background='/mwg-internal/de5fs23hu73ds/files/default/img/bg_navbar.jpg'>\n      If you feel you have reached this site in error, please contact the IT Service Desk at (319) 295-2000.\n    </td>\n  </tr>\n  <tr>\n    <td class='footData'>\n      generated <span id=\"time\">2018-02-28 19:04:17</span> by McAfee Web Gateway\n      <br />\n      appium\n    </td>\n  </tr>\n</table>\n\n      </td>\n    </tr>\n  </table>\n</body>\n\n</html>\n"
    at Object.checkLegacyResponse (C:\Projects\VenueUI\stageApp\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:546:15)
    at parseHttpResponse (C:\Projects\VenueUI\stageApp\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:509:13)
    at doSend.then.response (C:\Projects\VenueUI\stageApp\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:441:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
From: Task: WebDriver.createSession()
    at Function.createSession (C:\Projects\VenueUI\stageApp\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:769:24)
    at createDriver (C:\Projects\VenueUI\stageApp\node_modules\protractor\node_modules\selenium-webdriver\index.js:170:33)
    at Builder.build (C:\Projects\VenueUI\stageApp\node_modules\protractor\node_modules\selenium-webdriver\index.js:635:14)
    at Hosted.getNewDriver (C:\Projects\VenueUI\stageApp\node_modules\protractor\built\driverProviders\driverProvider.js:53:33)
    at Runner.createBrowser (C:\Projects\VenueUI\stageApp\node_modules\protractor\built\runner.js:195:43)
    at q.then.then (C:\Projects\VenueUI\stageApp\node_modules\protractor\built\runner.js:339:29)
    at _fulfilled (C:\Projects\VenueUI\stageApp\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Projects\VenueUI\stageApp\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Projects\VenueUI\stageApp\node_modules\q\q.js:796:13)
    at C:\Projects\VenueUI\stageApp\node_modules\q\q.js:556:49
    at runSingle (C:\Projects\VenueUI\stageApp\node_modules\q\q.js:137:13)
    at flush (C:\Projects\VenueUI\stageApp\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

## Link to Appium logs

Appium Logs: https://gist.github.com/santhoshsr/9a9723a1c4dccc6ec6c387187eb75a8e#file-appium-log
ADB Logs: https://gist.github.com/santhoshsr/9a9723a1c4dccc6ec6c387187eb75a8e#file-logcat-log
Protractor Log: https://gist.github.com/santhoshsr/9a9723a1c4dccc6ec6c387187eb75a8e#file-protractor-log

## Code To Reproduce Issue [ Good To Have ]

var HtmlScreenshotReporter = require('protractor-jasmine2-screenshot-reporter');
var appLocation = 'app-debug.apk';

var reporter = new HtmlScreenshotReporter({
  dest: './screenshots',
  filename: 'my-report.html',
  captureOnlyFailedSpecs: true
});

exports.config = {
  allScriptsTimeout: 11000,
  seleniumAddress: 'http://localhost:4723/wd/hub',
  specs: [
    '../e2e/**/*.e2e-spec.ts'
  ],
  capabilities: {
    platformName: 'Android',
    platformVersion: '7.0',
    deviceName:   '28e5dd470169b530', 
    automationName: 'UiAutomator2',
    browserName: "",
    autoWebview: true,
    app: appLocation,
    fullReset: true,
  },
  //directConnect: true,
  baseUrl: 'http://localhost:4723/',
  //baseUrl: 'http://127.0.0.1:8000',
  framework: 'jasmine',
  jasmineNodeOpts: {
    showColors: true,
    defaultTimeoutInterval: 30000,
    print: function() {}
  },
  useAllAngular2AppRoots: true,
   // Setup the report before any tests start
  beforeLaunch: function() {
    require('ts-node').register({
      project: 'e2e/tsconfig.e2e.json'
    });

    //require('connect')().use(require('serve-static')('www')).listen(4200);
    return new Promise(function(resolve){
      reporter.beforeLaunch(resolve);
    });
  },
  // Assign the test reporter to each running instance
  onPrepare: function() {
    var jasmineReporters = require('jasmine-reporters');
    jasmine.getEnv().addReporter(new jasmineReporters.TerminalReporter({
      verbosity: 3,
      color: true,
      showStack: true
    }));
    jasmine.getEnv().addReporter(new jasmineReporters.JUnitXmlReporter({
      savePath: process.env.JUNIT_REPORT_PATH,
      outputFile: process.env.JUNIT_REPORT_NAME,
      consolidateAll: true
    }));
    jasmine.getEnv().addReporter(reporter);

    // configuring wd in onPrepare
    // wdBridge helps to bridge wd driver with other selenium clients
    // See https://github.com/sebv/wd-bridge/blob/master/README.md
      var wd = require('wd'),
          protractor = require('protractor'),
          wdBridge = require('wd-bridge')(protractor, wd);
      wdBridge.initFromProtractor(exports.config);

  },
  // Close the report after all tests finish
  afterLaunch: function(exitCode) {
    return new Promise(function(resolve){
      reporter.afterLaunch(resolve.bind(this, exitCode));
    });
  }  

};

**Comment by mykola-mokhnach** [comment]
It is a problem with your corporate network configuration. Appium acts as a proxy between the webdriver agent and your client code, but the current network settings prevent the requests to be proxied properly. Nothing we can do there.

**Comment by santhoshsr** [comment]
verified with network team, they do not have any firewall blocking localhost and they confirmed it is not network issue and it may be issue with application of configuration.
