### ISSUE TITLE
Cannot parse launchActivity from manifest

### ISSUE THREAD

**Issue by codestealer** [appium/appium#10270]
Hi, I have this error while I try to install specific apk on a device.

```
[AndroidDriver] Not cleaning generated files. Add `clearSystemFiles` capability if wanted.
[MJSONWP] Encountered internal error running command: Error: packageAndLaunchActivityFromManifest failed. Original error: Cannot parse launchActivity from manifest: Feb 27, 2018 10:06:15 AM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
WARNING: Config flags size > 38. Exceeding bytes: 0x746E00000000000000000000000000000000.
Feb 27, 2018 10:06:15 AM brut.androlib.res.decoder.ARSCDecoder readConfig
WARNING: Invalid config flags detected. Dropping resources: string-sr-ERR0

    at Object.wrappedLogger.errorAndThrow (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\appium\node_modules\appium-support\lib\logging.js:69:13)
    at ADB.callee$0$0$ (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\appium\node_modules\appium-adb\lib\tools\android-manifest.js:188:7)
    at tryCatch (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at <anonymous>
```

Environment:
Windows 10
Appium version: beta
Android: 7.1.1 (real device and simulator)

**Comment by mykola-mokhnach** [comment]
This has been addressed in the recent beta version. Try to uninstall and install it again

**Comment by codestealer** [comment]
I did. My app is not in launcher after installation. It is like a service app and is started with some other app

**Comment by mykola-mokhnach** [comment]
what is the output of `apkanalyzer -h manifest print <apkPath>` cpommand?

**Comment by mykola-mokhnach** [comment]
To me it still looks like this is not the latest beta or you don't have the recent Android SDK installed on the machine (should be 26 or higher to include the `apkanalyzer` utility)

**Comment by codestealer** [comment]
I use SDK 27

**Comment by mykola-mokhnach** [comment]
Can you attach the full log?

**Comment by codestealer** [comment]
No, sorry. It is a company app. Do you need anything else that I can send you that can help?

**Comment by mykola-mokhnach** [comment]
Then you'll, most likely, have to debug it yourself.

**Comment by codestealer** [comment]
Thanks
