### ISSUE TITLE
Execution waits for long at remote.ProtocolHandshake create session stage.

### ISSUE THREAD

**Issue by HPramesh** [appium/appium#10292]
## The problem

Am running my scripts on Windows 7 machine on multiple Android devices sequentially, during my test runs after some test cases execution, execution halts almost for 9-10 minutes and the error below gets repeated quite a number of times before running again. Test scripts do not fail but stop as if waiting for some command. Thereby slowing down the execution.  

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1/7.1.2
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: Windows 7 with Service Pack 1
* Node.js version (unless using Appium.app|exe): v6.9.4
* Mobile platform/version under test: Moto G/Android 5.1v, Nexus5x/Android 7.1v
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: NA

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

 at GeneratorFunctionPrototype.invoke (C:\Users\Administrator\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
2018-03-02 07:57:10:188 - [debug] [AndroidDriver] Screen is locked, trying to unlock
2018-03-02 07:57:11:696 - [AndroidDriver] Using app unlock, this is going to be deprecated!
2018-03-02 07:57:12:935 - [AndroidDriver] Unlocking screen
2018-03-02 07:57:12:936 - [debug] [ADB] Getting connected devices...
2018-03-02 07:57:12:985 - [debug] [ADB] 6 device(s) connected
2018-03-02 07:57:12:986 - [debug] [ADB] Running 'C:\Users\Administrator\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","014b200364f6a4c5","shell","am","force-stop","io.appium.unlock"]
2018-03-02 07:57:13:837 - [debug] [ADB] Device API level: 25
2018-03-02 07:57:13:839 - [debug] [ADB] Getting connected devices...
2018-03-02 07:57:13:885 - [debug] [ADB] 6 device(s) connected
2018-03-02 07:57:13:887 - [debug] [ADB] Running 'C:\Users\Administrator\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","014b200364f6a4c5","shell","am","start","-W","-n","io.appium.unlock/.Unlock","-a","android.intent.action.MAIN","-c","android.intent.category.LAUNCHER",
"-f","0x10200000"]
2018-03-02 07:57:33:894 - [debug] [ADB] Running 'C:\Users\Administrator\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","014b200364f6a4c5","shell","am","start","-W","-n","io.appium.unlock/.Unlock","-a","android.intent.action.MAIN","-c","android.intent.category.LAUNCHER",
"-f","0x10200000"]
2018-03-02 07:57:53:908 - [ADB] Error: Error occured while starting App. Original error: Error executing adbExec. Original error: 'Command 'C\:\\Users\\Administrator\\AppData\\Local\\Android\\sdk\\platform-tools\\adb.exe -P 5037 -s 014b200364f6a4c5 shell am start -W -n io.appium.unlock/.Unlock -a an
droid.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' timed out after 20000ms'; Stderr: ''; Code: 'null'
    at Object.wrappedLogger.errorAndThrow (C:\Users\Administrator\AppData\Roaming\npm\node_modules\appium\node_modules\appium-support\lib\logging.js:69:13)
    at ADB.callee$0$0$ (C:\Users\Administrator\AppData\Roaming\npm\node_modules\appium\node_modules\appium-adb\lib\tools\apk-utils.js:101:9)
    at tryCatch (C:\Users\Administrator\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\Administrator\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\Administrator\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\Administrator\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
 Error: Error occured while starting App. Original error: Error executing adbExec. Original error: 'Command 'C\:\\Users\\Administrator\\AppData\\Local\\Android\\sdk\\platform-tools\\adb.exe -P 5037 -s 014b200364f6a4c5 shell am start -W -n io.appium.unlock/.Unlock -a android.intent.action.MAIN -c and
roid.intent.category.LAUNCHER -f 0x10200000' timed out after 20000ms'; Stderr: ''; Code: 'null'
    at Object.wrappedLogger.errorAndThrow (C:\Users\Administrator\AppData\Roaming\npm\node_modules\appium\node_modules\appium-support\lib\logging.js:69:13)
    at ADB.callee$0$0$ (C:\Users\Administrator\AppData\Roaming\npm\node_modules\appium\node_modules\appium-adb\lib\tools\apk-utils.js:101:9)
    at tryCatch (C:\Users\Administrator\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\Administrator\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\Administrator\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\Administrator\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
2018-03-02 07:57:54:914 - [debug] [AndroidDriver] Screen is locked, trying to unlock
2018-03-02 07:57:54:917 - [AndroidDriver] Using app unlock, this is going to be deprecated!
2018-03-02 07:57:54:918 - [AndroidDriver] Unlocking screen
2018-03-02 07:57:54:919 - [debug] [ADB] Getting connected devices...
2018-03-02 07:57:54:965 - [debug] [ADB] 6 device(s) connected
2018-03-02 07:57:54:966 - [debug] [ADB] Running 'C:\Users\Administrator\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","014b200364f6a4c5","shell","am","force-stop","io.appium.unlock"]
2018-03-02 07:57:55:667 - [debug] [ADB] Device API level: 25

**Comment by mykola-mokhnach** [comment]
Set `skipUnlock` to true. Also, use UIAutomator2 automation name for Android6+
