### ISSUE TITLE
Command 'Scripts/bootstrap.sh -d when starting ios session

### ISSUE THREAD

**Issue by orevron** [appium/appium#10301]
## The problem
** start session with ios simulator on react native app.
** during the session creation after app is installed on the device (i can see it) the appium server is stuck.
** nothing is happens until i interrupt the request and then the following error arrive:

> [MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: "Command 'Scripts/bootstrap.sh -d' exited with code 1".
    at XCUITestDriver.quitAndUninstall$ (/private/var/folders/d1/q5pjtdys5hj68yx8h9h0_m8h0000gn/T/AppTranslocation/BFD0B7CD-42DA-446E-8279-AAFDC1125603/d/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/lib/driver.js:387:13)
    at tryCatch (/private/var/folders/d1/q5pjtdys5hj68yx8h9h0_m8h0000gn/T/AppTranslocation/BFD0B7CD-42DA-446E-8279-AAFDC1125603/d/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/private/var/folders/d1/q5pjtdys5hj68yx8h9h0_m8h0000gn/T/AppTranslocation/BFD0B7CD-42DA-446E-8279-AAFDC1125603/d/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/private/var/folders/d1/q5pjtdys5hj68yx8h9h0_m8h0000gn/T/AppTranslocation/BFD0B7CD-42DA-446E-8279-AAFDC1125603/d/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/private/var/folders/d1/q5pjtdys5hj68yx8h9h0_m8h0000gn/T/AppTranslocation/BFD0B7CD-42DA-446E-8279-AAFDC1125603/d/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)

## Environment

* Appium version 1.7.2
* MacBook Pro High Sierra OSX 10.13.3
* Using appium Desktop
* IPhone 8 iOS 11.2
* simulator:
* Appium.app

## Details
the ipa was generated for simulator and is working perfect without the appium.

## Link to Appium logs
https://gist.github.com/orevron/dde81741ffc6ac424773f2f4478d845f

## Code To Reproduce Issue [ Good To Have ]
just create the sessions... these are my capabilities:
{
  "deviceName": "iPhone 8",
  "platformName": "iOS",
  "platformVersion": "11.2",
  "newCommandTimeout": 60000,
  "app": "/data/capriza-ng/app/ios/approvalsapp.app",
  "automationName": "XCUITest",
}

**Comment by mykola-mokhnach** [comment]
Closed as duplicate

**Comment by orevron** [comment]
can you provide the number of the issue ????
@mykola-mokhnach

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium/search?q=%22Scripts%2Fbootstrap.sh+-d%22&type=Issues&utf8=✓
