### ISSUE TITLE
Appium 1.7.2 - Chromedriver 

### ISSUE THREAD

**Issue by pascencio** [appium/appium#10309]
## The problem
Hi!
I'm triying to run a simple test on a hybrid app on android. When inspect the app with google chrome everything works! But when I try to execute my test get this error from Chromedriver (Using the debug capability for chromedriver):

DevTools request: http://localhost:<someport>/json/version

I have another test with an hybrid app working perfectly.

Thanks in advance!

## Environment

* Appium version: 1.7.2
* Desktop OS/version used to run Appium: Manjaro Linux 17.1.6 / Deepin 15.5
* Node.js version: v9.6.1
* Mobile platform/version under test: Galaxy TAB A and Galaxy J5 2006 - Android 6.0.1
* Real device 
* Appium CLI

## Details

- I test using chromedriver: 2.30, 2.31, 2.32, 2.33, 2.34 and 2.35.
- My device have Google Chrome 64.
- Remote debug works perfectly
- The app have debug mode only 

## Link to Appium logs

https://gist.github.com/pascencio/703faec167eba4cce5bcc0b668b017a5

## Code To Reproduce Issue

```java
@Test
public void test() throws MalformedURLException, InterruptedException {
    DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
    desiredCapabilities.setCapability("platformName", "Android");
    desiredCapabilities.setCapability("platformVersion", "6.0.1");
    desiredCapabilities.setCapability("deviceName", "Test");
    desiredCapabilities.setCapability("appPackage", "some.package");
    desiredCapabilities.setCapability("appActivity", ".MainActivity");
    desiredCapabilities.setCapability("autoWebview", true);
    AppiumDriver<WebElement> driver = new AndroidDriver<WebElement>(new URL("http://localhost:4723/wd/hub"), desiredCapabilities);

    driver.findElements(By.xpath("//*[@id=\"log_pers_rut\"]")).get(0).sendKeys("1-9");
    driver.findElements(By.xpath("//*[@id=\"log_pers_password\"]")).get(0).sendKeys("12345");
    driver.findElements(By.xpath("//*[@id=\"ingresar_pers\"]")).get(0).click();
}
```

**Comment by mykola-mokhnach** [comment]
Can you try appium@beta?

**Comment by pascencio** [comment]
Hi @mykola-mokhnach !

Same issue using appium beta with chromdriver 2.35.

**Comment by pascencio** [comment]
Hi,
Here is the chromedriver log as additional information:
https://gist.githubusercontent.com/pascencio/703faec167eba4cce5bcc0b668b017a5/raw/adbfa42e0e3e240ae192f39b912a1447dc9917ad/chromedriver.log

**Comment by larearruda** [comment]
I'm getting the same error.
Appium version 1.7.2 (tried to change to versions 1.8.0 1.7.1 and the error persisted)
Device Chrome version 66
Chromedriver version: '2.33.506120'
Android real devices used to test:
- Motorola Moto G 5 Plus - Android 7.0
- Samsung J5 - Android 6.0
- ASUS Zenfone - 5 Android  5.0
Node version v8.9.4 
Desktop OS used to run Appium: Windows 10
I updated the WebView on device and still no clue.


Error log bellow

[debug] [Chromedriver] Chromedriver version: '2.33.506120'
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8001/wd/hub/status] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"\",\"status\":0,\"value\":{\"build\":{\"version\":\"alpha\"},\"os\":{\"arch\":\"x86_64\",\"name\":\"Windows NT\",\"version\":\"10.0.15063\"}}}"
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8001/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.myproject.app","androidUseRunningApp":true,"androidDeviceSerial":"0024804552"}}}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"389103f4f33c7d403592e8edd6249576","status":100,"value":{"message":"chrome not reachable\n  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 10.0.15063 x86_64)"}}
[Chromedriver] Error: Failed to start Chromedriver session: An error occurred (Original error: chrome not reachable
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 10.0.15063 x86_64))
    at Object.wrappedLogger.errorAndThrow (C:\Users\larissa.arruda\AppData\Roaming\npm\node_modules\appium\node_modules\appium-support\lib\logging.js:69:13)
    at Chromedriver.callee$2$0$ (C:\Users\larissa.arruda\AppData\Roaming\npm\node_modules\appium\node_modules\appium-chromedriver\lib\chromedriver.js:217:13)
    at tryCatch (C:\Users\larissa.arruda\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\larissa.arruda\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\larissa.arruda\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\larissa.arruda\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at <anonymous>
 Error: Failed to start Chromedriver session: An error occurred (Original error: chrome not reachable
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 10.0.15063 x86_64))
    at Object.wrappedLogger.errorAndThrow (C:\Users\larissa.arruda\AppData\Roaming\npm\node_modules\appium\node_modules\appium-support\lib\logging.js:69:13)
    at Chromedriver.callee$2$0$ (C:\Users\larissa.arruda\AppData\Roaming\npm\node_modules\appium\node_modules\appium-chromedriver\lib\chromedriver.js:217:13)
    at tryCatch (C:\Users\larissa.arruda\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\larissa.arruda\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\larissa.arruda\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\larissa.arruda\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at <anonymous>
