### ISSUE TITLE
Appium-Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device

### ISSUE THREAD

**Issue by neerusqa** [appium/appium#10308]
## The problem

I am unable to launch real time Ios device in MAC through appium and selenium configuration.
I am getting below error.

[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
    at XCUITestDriver.quitAndUninstall$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:375:13)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at 
[HTTP] <-- POST /wd/hub/session 500 63900 ms - 470 

## Environment

[Appium]   app: /Users/Kirang/Documents/PR_Automation/xxxx.app
[Appium]   bundleId: com.xxxx
[Appium]   deviceName: iPhone 6s
[Appium]   platformName: ios
[Appium]   platformVersion: 11.2
[Appium]   udid: xxxxxx
[BaseDriver] Session created with session id: f7c9465c-810d-4abc-8a0c-393830accc8d
[XCUITest] Current user: 'kirang'
[XCUITest] Current version of libimobiledevice: stable 1.2.0 (bottled), HEAD
[XCUITest] Xcode version set to '9.2' (tools v9.0.0.0.1.1504363082)
[XCUITest] iOS SDK Version set to '11.2'

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Closed as duplicate
