### ISSUE TITLE
Appium v1.7.2 Original error: Invalid Version: android-4.4W?

### ISSUE THREAD

**Issue by ppppip** [appium/appium#10313]
## The problem
An unknown server-side error occurred while processing the command. Original error: Invalid Version: android-4.4W

## Environment

* Appium version (or git revision) that exhibits the issue:v1.7.2
* Last Appium version that did not exhibit the issue (if applicable):v.1.4.x
* Desktop OS/version used to run Appium:windows 10
* Node.js version (unless using Appium.app|exe):v8.9.3
* Mobile platform/version under test:5.1.1 & 7.0 
* Real device or emulator/simulator:Real
* Appium CLI or Appium.app|exe:Appium CLI

## Details
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Invalid Version: android-4.4W

The laat Appium version is ok,thank you very much~

## Link to Appium logs
[Appium] Welcome to Appium v1.7.2
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"capabilities":{"firstMatch":[{}],"alwaysMatch":{"platformName":"Android"}},"desiredCapabilities":{"platformName":"Android","platformVersion":"5.1.1","deviceName":"1b8d6589","appPackage":"com.hunantv.imgo.activity","appActivity":"com.hunantv.imgo.activity.MainActivity","newCommandTimeout":600,"resetKeyboard":true,"unicodeKeyboard":true,"noReset":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"Android","platformVersion":"5.1.1","deviceName":"1b8d6589","appPackage":"com.hunantv.imgo.activity","appActivity":"com.hunantv.imgo.activity.MainActivity","newCommandTimeout":600,"resetKeyboard":true,"unicodeKeyboard":true,"noReset":true},null,{"firstMatch":[{}],"alwaysMatch":{"platformName":"Android"}}]
[BaseDriver] Event 'newSessionRequested' logged at 1520410220065 (16:10:20 GMT+0800 (中国标准时间))
[Appium] Merged W3C capabilities {"firstMatch":[{}],"alwaysMatch":{"platformName... into desiredCapabilities object {"platformName":"Android","platformVersion":"5....
[Appium] Creating new AndroidDriver (v1.37.0) session
[Appium] Capabilities:
[Appium]   platformName: Android
[Appium]   platformVersion: 5.1.1
[Appium]   deviceName: 1b8d6589
[Appium]   appPackage: 
[Appium]   appActivity: 
[Appium]   newCommandTimeout: 600
[Appium]   resetKeyboard: true
[Appium]   unicodeKeyboard: true
[Appium]   noReset: true
[BaseDriver] Session created with session id: e928c9ee-3020-46c1-95bc-2ec45a811dff
[AndroidDriver] Getting Java version
[AndroidDriver] Java version is: 1.8.0_131
[ADB] Checking whether adb is present
[AndroidDriver] Shutting down Android driver
[AndroidDriver] Called deleteSession but bootstrap wasn't active
[MJSONWP] Encountered internal error running command: TypeError: Invalid Version: android-4.4W
    at new SemVer (C:\Users\ThinkPad\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\semver\semver.js:293:11)
    at compare (C:\Users\ThinkPad\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\semver\semver.js:566:10)
    at rcompare (C:\Users\ThinkPad\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\semver\semver.js:576:10)
    at Array.sort (native)
    at Array.sort (C:\Users\ThinkPad\AppData\Local\Programs\appium-desktop\resources\app\webpack:\~\core-js\modules\es6.array.sort.js:21:1)
    at ADB.callee$0$0$ (C:\Users\ThinkPad\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:89:17)
    at tryCatch (C:\Users\ThinkPad\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\ThinkPad\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\ThinkPad\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\ThinkPad\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at 
[HTTP] <-- POST /wd/hub/session 500 281 ms - 165

**Comment by mykola-mokhnach** [comment]
Closed as duplicate

https://github.com/appium/appium/issues/9926
