### ISSUE TITLE
RunAppInBackground is  not working in 1.7.2

### ISSUE THREAD

**Issue by harsh2906** [appium/appium#10326]
## The problem

When I try to run my app in background and then in foreground it's giving error as  "[pool-3-thread-1] 09 Mar 2018 15:09:54,158 ERROR: org.openqa.selenium.WebDriverException:An unknown server-side error occurred while processing the command. Original error: Error occured while starting App. Original error: Permission to start activity denied. (WARNING: The server did not provide any stacktrace information)
"

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): 1.7.1
* Desktop OS/version used to run Appium: Windows 10 enterprise
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android 6.0.1
* Real device or emulator/simulator: Samsung Galaxy s6 , nexus 5
* Appium CLI or Appium.app|exe: 

## Details

The same code is working fine on 1.7.1 until I updated appium to 1.7.2
## Link to Appium logs

[debug] [ADB] Running 'C:\Users\e071941\AppData\Local\Android\Sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","072344a50b3604e0","shell","am","start","-W","-n","com.abc.xyz.abc/com.abc.xyz.ui.abc"][error] [ADB] Error: Permission to start activity denied.
    at Object.wrappedLogger.errorAndThrow (C:\Users\e071941\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:69:13)
    at ADB.callee$0$0$ (C:\Users\e071941\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\apk-utils.js:94:11)
    at tryCatch (C:\Users\e071941\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\e071941\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\e071941\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\e071941\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at <anonymous>
 Error: Permission to start activity denied.
    at Object.wrappedLogger.errorAndThrow (C:\Users\e071941\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:69:13)
    at ADB.callee$0$0$ (C:\Users\e071941\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\apk-utils.js:94:11)
    at tryCatch (C:\Users\e071941\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\e071941\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\e071941\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\e071941\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at <anonymous>

## Code To Reproduce Issue [ Good To Have ]

driver.runAppInBackground(Duration.ofSeconds(2));

**Comment by mykola-mokhnach** [comment]
Do you see what is changed in the log in comparison to the previous version? What is the output if you try to execute the logged command manually?

**Comment by InfantAnto** [comment]
I too having the same issue with runAppInBackground in appium 1.7.2. Then I switch back to the Appium 1.7.1. Any solutions would be appreciated.

**Comment by mekxtari** [comment]
I also had to switch back to 1.7.1 because background app keyword in robot framework did not work in 1.7.2. Hopefully this will be fixed as soon as possible

**Comment by mykola-mokhnach** [comment]
@InfantAnto @mekxtari, sorry, but your comments are totally useless and won't help to solve the issue even a bit. We need the information I asked above to start the investigation. Also, there is always appium@beta with the most recent fixes. Perhaps, your problem has been already addresses there.

**Comment by mykola-mokhnach** [comment]
Closed as inactive
