### ISSUE TITLE
CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory Could not proxy command to remote server. Original error: Error: read ECONNRESET

### ISSUE THREAD

**Issue by Kitty2014** [appium/appium#10356]
The problem
I am trying to run a test on a remote server, after running the Test Case 
After running for some time 
--- Last few GCs --->

4614636 ms: Mark-sweep 1366.1 (1434.9) -> 1365.8 (1434.9) MB, 1558.2 / 0.0 ms [allocation failure] [GC in old space requested].
4616193 ms: Mark-sweep 1365.8 (1434.9) -> 1365.6 (1434.9) MB, 1556.6 / 0.0 ms [allocation failure] [GC in old space requested].
4617770 ms: Mark-sweep 1365.6 (1434.9) -> 1367.2 (1405.9) MB, 1577.0 / 0.0 ms [last resort gc].
4619336 ms: Mark-sweep 1367.2 (1405.9) -> 1369.5 (1405.9) MB, 1565.0 / 0.0 ms [last resort gc].

--- JS stacktrace --->

=== JS stack trace =========================================

ecurity context: 000001669C5CFB49 <JS Object>
   1: onread [net.js:529] [pc=000002539A11121C] (this=000003026F7F2391 <a Pipe with map 0000013F04872361>,nread=176,buffer=000002E4FF79DD99 <an Uint8Array with map 00000178A741DB11>)
   2: arguments adaptor frame: 3->2

=== Details ================================================

1]: onread [net.js:529] [pc=000002539A11121C] (this=000003026F7F2391 <a Pipe with map 0000013F04872361>,nread...

ATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
[qa1.txt](https://github.com/appium/appium/files/1815257/qa1.txt)

Environment
Appium version :1.7.2-beta
Desktop OS/version used to run Appium: Ubuntu
Node.js version : v6.10.3
Mobile platform/version under test: Android
Real device or emulator/simulator:Android 7
Details
error occur in server:
2018-03-15 09:18:53:681 - [MJSONWP] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: Error: read ECONNRESET
    at JWProxy.proxy$ (D:\Develop\nodejs\node_global\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:152:13)
    at tryCatch (D:\Develop\nodejs\node_global\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (D:\Develop\nodejs\node_global\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (D:\Develop\nodejs\node_global\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (D:\Develop\nodejs\node_global\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
2018-03-15 09:18:53:688 - [HTTP] <-- POST /wd/hub/session/2800e069-2aae-4b8d-a60f-80d41d1b3401/elements 500 27 ms - 251

<--- Last few GCs --->

 4614636 ms: Mark-sweep 1366.1 (1434.9) -> 1365.8 (1434.9) MB, 1558.2 / 0.0 ms [allocation failure] [GC in old space requested].
 4616193 ms: Mark-sweep 1365.8 (1434.9) -> 1365.6 (1434.9) MB, 1556.6 / 0.0 ms [allocation failure] [GC in old space requested].
 4617770 ms: Mark-sweep 1365.6 (1434.9) -> 1367.2 (1405.9) MB, 1577.0 / 0.0 ms [last resort gc].
 4619336 ms: Mark-sweep 1367.2 (1405.9) -> 1369.5 (1405.9) MB, 1565.0 / 0.0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 000001669C5CFB49 <JS Object>
    1: onread [net.js:529] [pc=000002539A11121C] (this=000003026F7F2391 <a Pipe with map 0000013F04872361>,nread=176,buffer=000002E4FF79DD99 <an Uint8Array with map 00000178A741DB11>)
    2: arguments adaptor frame: 3->2

==== Details ================================================

[1]: onread [net.js:529] [pc=000002539A11121C] (this=000003026F7F2391 <a Pipe with map 0000013F04872361>,nread...

Any solution would be appreciated.
Thanks

**Comment by mykola-mokhnach** [comment]
Does it also happen in the recent 1.8.0-beta?
