### ISSUE TITLE
Unable to create IOSDriver

### ISSUE THREAD

**Issue by zhaoxusun** [appium/appium#10458]
## Appium
When I try to create IOSDriver , 
![image](https://user-images.githubusercontent.com/30275668/38202500-7f5ee5de-36ce-11e8-9a56-8971d2dd1fa7.png)

the appium server throws a exception:
![image](https://user-images.githubusercontent.com/30275668/38202031-eed7b078-36cc-11e8-96ab-e4fef635fc96.png)

## The problem
The code throws a exception:
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: An error occurred (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 263 milliseconds
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'localhost', ip: 'fe80:0:0:0:8f4:ee6d:d061:29bf%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_121'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{networkConnectionEnabled=false, noReset=false, bundleId=com.meituan.imeituan-beta, databaseEnabled=false, deviceName=iPhone 8, platform=MAC, platformVersion=11.1.2, webStorageEnabled=false, locationContextEnabled=false, automationName=XCUITest, browserName=, takesScreenshot=true, javascriptEnabled=true, udid=1e1776ef5f5c00aefa15e1b79568f7ea7be8ba1a, platformName=iOS, autoAcceptAlerts=true}]
Session ID: 9dc93016-295e-4413-9cd2-cf8f8fa38310
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:167)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:671)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:46)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at io.appium.java_client.HasSessionDetails.getSessionDetails(HasSessionDetails.java:36)
	at io.appium.java_client.HasSessionDetails.getSessionDetail(HasSessionDetails.java:42)
	at io.appium.java_client.HasSessionDetails.getPlatformName(HasSessionDetails.java:46)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:100)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:112)
	at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:78)
## Environment
appium 1.8.0-beta3
appium java-client 6.0.0-BETA4
real device iphone 8 v11.1.2
xcode 9.2

**Comment by mykola-mokhnach** [comment]
Uninstall WebDriverAgent binary from the device. The issue happens, because you've update Appium code, but the old WDA binary is still cached on the device.

**Comment by zhaoxusun** [comment]
@mykola-mokhnach I update WDA, but failed again.
![image](https://user-images.githubusercontent.com/30275668/38304473-2fec2dbc-383c-11e8-96a5-0c79dd75e4cd.png)

Can you give some suggestions

**Comment by zhaoxusun** [comment]
@mykola-mokhnach 
`git clone https://github.com/facebook/WebDriverAgent`
`git pull` 

It is right or how to download the latest version

**Comment by mykola-mokhnach** [comment]
No. Ttemporarily set `useNewWDA` capability to `true`

**Comment by zhaoxusun** [comment]
Thanks, I will try again later
