### ISSUE TITLE
Appium does not run code on simulator

### ISSUE THREAD

**Issue by rmsangani** [appium/appium#10461]
## The problem

I am trying to run one small Java command to click a button. My code is able to locate the element by id but appium is not acting upon it. (the click() command is not working)

## Environment

* Real device or emulator/simulator: iPhone SE, iOS 11.2
* Appium CLI or Appium.app|exe: Latest

## Details

I am trying to run one small Java command to click a button. My code is able to locate the element by id but appium is not acting upon it. (the click() command is not working)
[appium-server-logs.txt](https://github.com/appium/appium/files/1868825/appium-server-logs.txt)

Error in eclipse: java.lang.NullPointerException

## Link to Appium logs

attached logs in .txt file

logs after the app is launched:
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"11.2\",\n      \"sdkVersion\" : \"11.2\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"11.2\",\n      \"ip\" : \"10.181.8.58\"\n    },\n    \"build\" : {\n      \"time\" : \"Apr  2 2018 12:28:39\"\n    }\n  },\n  \"sessionId\" : \"F77698D7-D5E9-4A35-8D4F-9E775955EBD9\",\n  \"status\" : 0\n}"
[XCUITest] Will reuse previously cached WDA instance at 'http://localhost:8100/'. Set the wdaLocalPort capability to a value different from 8100 if this is an undesired behavior.
[BaseDriver] Event 'wdaStartAttempted' logged at 1522691276395 (13:47:56 GMT-0400 (EDT))
[XCUITest] Using provided WebdriverAgent at 'http://localhost:8100/'
[BaseDriver] Event 'wdaSessionAttempted' logged at 1522691276396 (13:47:56 GMT-0400 (EDT))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"11.2\",\n      \"sdkVersion\" : \"11.2\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"11.2\",\n      \"ip\" : \"10.181.8.58\"\n    },\n    \"build\" : {\n      \"time\" : \"Apr  2 2018 12:28:39\"\n    }\n  },\n  \"sessionId\" : \"F77698D7-D5E9-4A35-8D4F-9E775955EBD9\",\n  \"status\" : 0\n}"
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.crowdcompass.tumbleweed","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[JSONWP Proxy] Got response with status 200: {"value":{"sessionId":"0629E093-45D6-4949-A2AB-5146A557AE33","capabilities":{"device":"iphone","browserName":"AttendeeHub","sdkVersion":"11.2","CFBundleIdentifier":"com.crowdcompass.tumbleweed"}},"sessionId":"0629E093-45D6-4949-A2AB-5146A557AE33","status":0}
[BaseDriver] Event 'wdaSessionStarted' logged at 1522691280510 (13:48:00 GMT-0400 (EDT))
[BaseDriver] Event 'wdaStarted' logged at 1522691280510 (13:48:00 GMT-0400 (EDT))
[XCUITest] Skipping setting of the initial display orientation. Set the "orientation" capability to either "LANDSCAPE" or "PORTRAIT", if this is an undesired behavior.
[BaseDriver] Event 'orientationSet' logged at 1522691280511 (13:48:00 GMT-0400 (EDT))
[Appium] New XCUITestDriver session created successfully, session 7310ad29-cc43-4a62-96d6-7ffab265cd08 added to master session list
[BaseDriver] Event 'newSessionStarted' logged at 1522691280512 (13:48:00 GMT-0400 (EDT))
[MJSONWP] Responding to client with driver.createSession() result: {"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"app":"/Users/rsangani/Desktop/ipafile/attendee.app","automationName":"XCUITest","deviceName":"iPhone SE","newCommandTimeout":60000,"platformName":"ios","platformVersion":"11.2","uuid":"94293957-ADC1-49AA-B6CA-A123A542B7","udid":"94293957-ADC1-49AA-B6CA-A123A542B7E2"}
[HTTP] <-- POST /wd/hub/session 200 16184 ms - 537 
[HTTP] --> POST /wd/hub/session/7310ad29-cc43-4a62-96d6-7ffab265cd08/element {"using":"id","value":"directory_eventOpen"}
[MJSONWP] Calling AppiumDriver.findElement() with args: ["id","directory_eventOpen","7310ad29-cc43-4a62-96d6-7ffab265cd08"]
[XCUITest] Executing command 'findElement'
[BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[BaseDriver] Waiting up to 0 ms for condition
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/0629E093-45D6-4949-A2AB-5146A557AE33/element] with body: {"using":"id","value":"directory_eventOpen"}
[JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"AED46680-555B-4227-9108-AF5325CC89FB"},"sessionId":"0629E093-45D6-4949-A2AB-5146A557AE33","status":0}
[MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"AED46680-555B-4227-9108-AF5325CC89FB"}
[HTTP] <-- POST /wd/hub/session/7310ad29-cc43-4a62-96d6-7ffab265cd08/element 200 92 ms - 122 
[HTTP] --> POST /wd/hub/session/7310ad29-cc43-4a62-96d6-7ffab265cd08/element {"using":"id","value":"directory_eventOpen"}
[MJSONWP] Calling AppiumDriver.findElement() with args: ["id","directory_eventOpen","7310ad29-cc43-4a62-96d6-7ffab265cd08"]
[XCUITest] Executing command 'findElement'
[BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[BaseDriver] Waiting up to 0 ms for condition
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/0629E093-45D6-4949-A2AB-5146A557AE33/element] with body: {"using":"id","value":"directory_eventOpen"}
[JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"8604E625-44BD-4067-A113-9ABD0E2F18C2"},"sessionId":"0629E093-45D6-4949-A2AB-5146A557AE33","status":0}
[MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"8604E625-44BD-4067-A113-9ABD0E2F18C2"}
[HTTP] <-- POST /wd/hub/session/7310ad29-cc43-4a62-96d6-7ffab265cd08/element 200 64 ms - 122 
[HTTP] --> POST /wd/hub/session/7310ad29-cc43-4a62-96d6-7ffab265cd08/element {"using":"id","value":"directory_eventOpen"}
[MJSONWP] Calling AppiumDriver.findElement() with args: ["id","directory_eventOpen","7310ad29-cc43-4a62-96d6-7ffab265cd08"]
[XCUITest] Executing command 'findElement'
[BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[BaseDriver] Waiting up to 0 ms for condition
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/0629E093-45D6-4949-A2AB-5146A557AE33/element] with body: {"using":"id","value":"directory_eventOpen"}
[JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"C0B39044-1669-4418-95E7-A9124C472129"},"sessionId":"0629E093-45D6-4949-A2AB-5146A557AE33","status":0}
[MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"C0B39044-1669-4418-95E7-A9124C472129"}
[HTTP] <-- POST /wd/hub/session/7310ad29-cc43-4a62-96d6-7ffab265cd08/element 200 69 ms - 122 

## Code To Reproduce Issue [ Good To Have ]

package test_appium;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.remote.CapabilityType;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import java.io.File;
import java.net.URL;
import io.appium.*;
import io.appium.java_client.ios.IOSDriver;

//import com.gargoylesoftware.htmlunit.javascript.host.file.File;

//import org.testng.annotations.Test;
//import org.junit.Test;

public class MyFirstTest {
	public WebDriver driver = null;
	public IOSDriver driver_1 = null; 
	@Before
	public void setUp() throws Exception {
	// set up appium
		System.out.println("entered before test");
	File appDir = new File("/Users/rsangani/Desktop/ipafile");

	File app = new File(appDir, "attendee.app");
	DesiredCapabilities capabilities = new DesiredCapabilities();
	capabilities.setCapability("platformName", "iOS");
	capabilities.setCapability("deviceName", "iPhone SE");
	capabilities.setCapability("platformVersion", "11.2");
	capabilities.setCapability("automationName","XCUITest");
	capabilities.setCapability("app", app.getAbsolutePath());
	capabilities.setCapability("uuid","94293957-ADC1-49AA-B6CA-A123A542B7");
	capabilities.setCapability("newCommandTimeout", "60000");
	System.out.println("worked till app path");
	driver_1 = new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"),capabilities);
	//driver=new RemoteWebDriver(new URL("http://127.0.0.1:4723/wd/hub"),capabilities);
	System.out.println("App launched");
	}
	
	@After
	public void tearDown() throws Exception {
		driver_1.findElement(By.id("directory_eventOpen")).click();
		System.out.println("entered finish");
	//driver_1.quit();
	}
	
	@Test
	public void testCases() throws InterruptedException {
		
		System.out.println("successsssss");
		Thread.sleep(5000);
		System.out.println("exited sleep");
		System.out.println(driver_1);
		System.out.println(driver_1.findElement(By.id("directory_eventOpen")));
		driver_1.findElement(By.id("directory_eventOpen")).click();
		//driver_1.findElement(By.xpath("//XCUIElementTypeButton[@name=\"directory_eventOpen\"]")).click();
		System.out.println("It pressed");
		Thread.sleep(5000);
		//driver_1.switchTo().alert().accept();
		}
}

**Comment by mykola-mokhnach** [comment]
I don't see any issues in the attached server log. Most likely the problem lies in your client code. Did you try to debug it?

**Comment by rmsangani** [comment]
I had packaged the project file and sent across to one other person. The code ran perfectly fine with that person. The only thing he had changed in the code was that they changed the uuid of their simulator. Can you tell me what more information should I provide from my end?

**Comment by mykola-mokhnach** [comment]
What is the exception stacktrace?

**Comment by rmsangani** [comment]
java.lang.NullPointerException
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:279)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:83)
	at test_appium.MyFirstTest.testCases(MyFirstTest.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)

java.lang.NullPointerException
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:279)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:83)
	at test_appium.MyFirstTest.tearDown(MyFirstTest.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:36)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)

**Comment by rmsangani** [comment]
this is the output: based on my code
entered before test
worked till app path
Apr 02, 2018 1:48:00 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
App launched
successsssss
exited sleep
IOSDriver:  on MAC (7310ad29-cc43-4a62-96d6-7ffab265cd08)
[[IOSDriver:  on MAC (7310ad29-cc43-4a62-96d6-7ffab265cd08)] -> id: directory_eventOpen]

**Comment by rmsangani** [comment]
The output if I comment out driver_1.findElement(By.id("directory_eventOpen")).click(); from the @After block

entered before test
worked till app path
Apr 02, 2018 2:14:18 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
App launched
successsssss
exited sleep
IOSDriver:  on MAC (fad4197e-7702-475b-a414-eb109caeccf5)
[[IOSDriver:  on MAC (fad4197e-7702-475b-a414-eb109caeccf5)] -> id: directory_eventOpen]
entered finish

**Comment by mykola-mokhnach** [comment]
This is java client error, which has nothing to do to the server itself.  
I assume it throws an error, because you try to use either wrong or deleted driver instance to find an element, but this is just a guess. If you still think this is a bug then you can report it to  https://github.com/appium/java-client

closed as not an issue.
