### ISSUE TITLE
Slowness identifying objects in NATIVE context

### ISSUE THREAD

**Issue by abhishekmangudkarQK** [appium/appium#10483]
## Objects getting identified slowly
While switching from Web to Native context, appium responds to elements very slowly.
Once it switched back to Web context, appium identifies elements better. 

## Environment

* Appium version : 1.7.2
* Desktop OS/version : Windows 7
* Node.js version : 6.10.1
* Mobile platform/version under test: Android Oreo 8
* Real device or emulator/simulator: Real Device [Google Pixel] 

## Link to Appium logs

018-04-04 10:07:23:149 - info: [HTTP] <-- POST /wd/hub/session/fb071397-7d34-457d-8ae5-96b0052e2256/appium/device/hide_keyboard 500 130 ms - 218 
2018-04-04 10:07:23:180 - info: [HTTP] --> GET /wd/hub/session/fb071397-7d34-457d-8ae5-96b0052e2256/window/current/size {}
2018-04-04 10:07:23:180 - info: [MJSONWP] Driver proxy active, passing request on via HTTP proxy
2018-04-04 10:07:23:180 - info: [debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/fb071397-7d34-457d-8ae5-96b0052e2256/window/current/size] to [GET http://localhost:8206/wd/hub/session/49683146-b490-4352-9a39-538a49790bff/window/current/size] with body: {}
2018-04-04 10:07:23:196 - info: [debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"49683146-b490-4352-9a39-538a49790bff\",\"status\":0,\"value\":{\"height\":1794,\"width\":1080}}"
2018-04-04 10:07:23:212 - info: [JSONWP Proxy] Replacing sessionId 49683146-b490-4352-9a39-538a49790bff with fb071397-7d34-457d-8ae5-96b0052e2256
2018-04-04 10:07:23:212 - info: [HTTP] <-- GET /wd/hub/session/fb071397-7d34-457d-8ae5-96b0052e2256/window/current/size 200 31 ms - 100 
2018-04-04 10:07:23:228 - info: [HTTP] --> POST /wd/hub/session/fb071397-7d34-457d-8ae5-96b0052e2256/elements {"using":"xpath","value":"//*[@*[contains(.,'SAVE')]]"}
2018-04-04 10:07:23:228 - info: [debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["xpath","//*[@*[contains(.,'SAVE')]]","fb071397-7d34-457d-8ae5-96b0052e2256"]
2018-04-04 10:07:23:228 - info: [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
2018-04-04 10:07:23:228 - info: [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
2018-04-04 10:07:23:228 - info: [debug] [BaseDriver] Waiting up to 0 ms for condition
2018-04-04 10:07:23:243 - info: [debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8206/wd/hub/session/49683146-b490-4352-9a39-538a49790bff/elements] with body: {"strategy":"xpath","selector":"//*[@*[contains(.,'SAVE')]]","context":"","multiple":true}
2018-04-04 10:07:44:101 - info: [debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"49683146-b490-4352-9a39-538a49790bff","status":0,"value":[{"ELEMENT":"e214295f-1944-45cb-97d0-337fa19e34ab"}]}
2018-04-04 10:07:44:101 - info: [debug] [MJSONWP] Responding to client with driver.findElements() result: [{"ELEMENT":"e214295f-1944-45cb-97d0-337fa19e34ab"}]
2018-04-04 10:07:44:116 - info: [HTTP] <-- POST /wd/hub/session/fb071397-7d34-457d-8ae5-96b0052e2256/elements 200 20882 ms - 124 
2018-04-04 10:07:44:147 - info: [HTTP] --> GET /wd/hub/session/fb071397-7d34-457d-8ae5-96b0052e2256/element/e214295f-1944-45cb-97d0-337fa19e34ab/location {}
2018-04-04 10:07:44:147 - info: [MJSONWP] Driver proxy active, passing request on via HTTP proxy
2018-04-04 10:07:44:147 - info: [debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/fb071397-7d34-457d-8ae5-96b0052e2256/element/e214295f-1944-45cb-97d0-337fa19e34ab/location] to [GET http://localhost:8206/wd/hub/session/49683146-b490-4352-9a39-538a49790bff/element/e214295f-1944-45cb-97d0-337fa19e34ab/location] with body: {}
2018-04-04 10:07:54:241 - info: [debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"49683146-b490-4352-9a39-538a49790bff\",\"status\":0,\"value\":{\"x\":158,\"y\":908}}"
2018-04-04 10:07:54:241 - info: [JSONWP Proxy] Replacing sessionId 49683146-b490-4352-9a39-538a49790bff with fb071397-7d34-457d-8ae5-96b0052e2256
2018-04-04 10:07:54:241 - info: [HTTP] <-- GET /wd/hub/session/fb071397-7d34-457d-8ae5-96b0052e2256/element/e214295f-1944-45cb-97d0-337fa19e34ab/location 200 10096 ms - 89 
2018-04-04 10:07:54:272 - info: [HTTP] --> GET /wd/hub/session/fb071397-7d34-457d-8ae5-96b0052e2256/element/e214295f-1944-45cb-97d0-337fa19e34ab/location {}
2018-04-04 10:07:54:272 - info: [MJSONWP] Driver proxy active, passing request on via HTTP proxy
2018-04-04 10:07:54:272 - info: [debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/fb071397-7d34-457d-8ae5-96b0052e2256/element/e214295f-1944-45cb-97d0-337fa19e34ab/location] to [GET http://localhost:8206/wd/hub/session/49683146-b490-4352-9a39-538a49790bff/element/e214295f-1944-45cb-97d0-337fa19e34ab/location] with body: {}
2018-04-04 10:08:04:413 - info: [debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"49683146-b490-4352-9a39-538a49790bff\",\"status\":0,\"value\":{\"x\":158,\"y\":908}}"
2018-04-04 10:08:04:413 - info: [JSONWP Proxy] Replacing sessionId 49683146-b490-4352-9a39-538a49790bff with fb071397-7d34-457d-8ae5-96b0052e2256
2018-04-04 10:08:04:413 - info: [HTTP] <-- GET /wd/hub/session/fb071397-7d34-457d-8ae5-96b0052e2256/element/e214295f-1944-45cb-97d0-337fa19e34ab/location 200 10141 ms - 89 
2018-04-04 10:08:04:428 - info: [HTTP] --> GET /wd/hub/session/fb071397-7d34-457d-8ae5-96b0052e2256/element/e214295f-1944-45cb-97d0-337fa19e34ab/location {}
2018-04-04 10:08:04:428 - info: [MJSONWP] Driver proxy active, passing request on via HTTP proxy
2018-04-04 10:08:04:428 - info: [debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/fb071397-7d34-457d-8ae5-96b0052e2256/element/e214295f-1944-45cb-97d0-337fa19e34ab/location] to [GET http://localhost:8206/wd/hub/session/49683146-b490-4352-9a39-538a49790bff/element/e214295f-1944-45cb-97d0-337fa19e34ab/location] with body: {}
2018-04-04 10:08:14:538 - info: [debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"49683146-b490-4352-9a39-538a49790bff\",\"status\":0,\"value\":{\"x\":158,\"y\":908}}"
2018-04-04 10:08:14:538 - info: [JSONWP Proxy] Replacing sessionId 49683146-b490-4352-9a39-538a49790bff with fb071397-7d34-457d-8ae5-96b0052e2256
2018-04-04 10:08:14:538 - info: [HTTP] <-- GET /wd/hub/session/fb071397-7d34-457d-8ae5-96b0052e2256/element/e214295f-1944-45cb-97d0-337fa19e34ab/location 200 10117 ms - 89 
2018-04-04 10:08:29:470 - info: [HTTP] --> POST /wd/hub/session/fb071397-7d34-457d-8ae5-96b0052e2256/element {"using":"xpath","value":"//*[@*[contains(.,'SAVE')]]"}
2018-04-04 10:08:29:470 - info: [debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["xpath","//*[@*[contains(.,'SAVE')]]","fb071397-7d34-457d-8ae5-96b0052e2256"]
2018-04-04 10:08:29:470 - info: [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
2018-04-04 10:08:29:517 - info: [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
2018-04-04 10:08:29:517 - info: [debug] [BaseDriver] Waiting up to 0 ms for condition
2018-04-04 10:08:29:517 - info: [debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8206/wd/hub/session/49683146-b490-4352-9a39-538a49790bff/element] with body: {"strategy":"xpath","selector":"//*[@*[contains(.,'SAVE')]]","context":"","multiple":false}
2018-04-04 10:08:59:906 - info: [debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"49683146-b490-4352-9a39-538a49790bff","status":0,"value":{"ELEMENT":"73095b2d-277e-4ec0-a249-cc5c422228e7"}}
2018-04-04 10:08:59:906 - info: [debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"73095b2d-277e-4ec0-a249-cc5c422228e7"}
2018-04-04 10:08:59:906 - info: [HTTP] <-- POST /wd/hub/session/fb071397-7d34-457d-8ae5-96b0052e2256/element 200 30441 ms - 122 
2018-04-04 10:08:59:937 - info: [HTTP] --> GET /wd/hub/session/fb071397-7d34-457d-8ae5-96b0052e2256/screenshot {}
2018-04-04 10:08:59:937 - info: [debug] [MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["fb071397-7d34-457d-8ae5-96b0052e2256"]
2018-04-04 10:08:59:937 - info: [debug] [ADB] Device API level: 26
2018-04-04 10:09:00:749 - info: [debug] [MJSONWP] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAABDgAAAeACAYAAAArYecKAACAAElEQVR4AezBCZzfdWHn/9fn+/3+7jl+c2SuXDO5Q0IyARJTAiQZqraCSYMC7kKBpFiLpfqndTdo3cGwhdKtQi2suFpwg65WVOoggoLJJCiHnBMgIQGS3+Q+5jfHb47fzO/8ruH/mO746+QgyVzJ+/k01lXfcBERERERERERGcMsRERERERERETGOAsRERERERERkTHOQkRERERERERkjLMQERERERERERnjLERERERERERExjgLEREREREREZExzkJEREREREREZIyzEBEREREREREZ4yxERERERERERMY4CxERERERERGRMc5hDDIG/B4HYyCTdUmkMoiIiIiIiIjIucthlDMGAl6HPL+HoM/BY1v4PDZzJhUT9Dq0did4e28brguJdIbuvhTxRJpEKoOIiIiIyJlUW1NKYdBLLJ6kKRJlLAmHfMyvLiEWT9IUiSJyuuZMLKYw6OVkxOJJtu5tQ2QoOYxSljGEQ17Kw0EWTS/nI7UTWDKrkomleQwmlcmyY38HT766m+d3HOKN5lbauvvo6k0hIiIiInIqamtKuWHZTFYuqqG6LJ9czUe6aHgpwiObdtAUiTKaza8uYeOdKzlqzQONrG/czliydE4V86tLqa0pobqsgKOWzqliMJu3HuCo5iOdNEVa2dIcZfPWA5zNZlaF2XGgg+FUGPRSnO9HZLRwGGUsYygIepk8Lo/VdbO5bukMivN8nIjHtpg7qZi5k4rJZF0iRzr51tPb+NFz79HalaAnkUJERERE5GTU1pRy7+olLJ1TxfFUl+Xz+Svn8fkr57F56wH++jvP0RSJMto9fOtyjlrfuJ3RqrosnxULa7hx+Uxqa0r5IJbOqeKopXOquHE5/64pEmV94w4efzlC85EuzhYzq8JMrwqz40AHIucyY131DZdRwrEtppQXcMOymXzmo3MozvNxOjJZl52HYtz3sy3824sRWjp7ERERERE5...
2018-04-04 10:09:00:765 - info: [HTTP] <-- GET /wd/hub/session/fb071397-7d34-457d-8ae5-96b0052e2256/screenshot 200 823 ms - 186574 
2018-04-04 10:09:00:796 - info: [HTTP] --> POST /wd/hub/session/fb071397-7d34-457d-8ae5-96b0052e2256/elements {"using":"xpath","value":"//*[@*[contains(.,'SAVE')]]"}
2018-04-04 10:09:00:796 - info: [debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["xpath","//*[@*[contains(.,'SAVE')]]","fb071397-7d34-457d-8ae5-96b0052e2256"]
2018-04-04 10:09:00:796 - info: [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
2018-04-04 10:09:00:796 - info: [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
2018-04-04 10:09:00:796 - info: [debug] [BaseDriver] Waiting up to 0 ms for condition
2018-04-04 10:09:00:796 - info: [debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8206/wd/hub/session/49683146-b490-4352-9a39-538a49790bff/elements] with body: {"strategy":"xpath","selector":"//*[@*[contains(.,'SAVE')]]","context":"","multiple":true}
2018-04-04 10:09:21:279 - info: [debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"49683146-b490-4352-9a39-538a49790bff","status":0,"value":[{"ELEMENT":"9008f3d6-3636-4c2e-ac6b-efbddb47a5a4"}]}
2018-04-04 10:09:21:295 - info: [debug] [MJSONWP] Responding to client with driver.findElements() result: [{"ELEMENT":"9008f3d6-3636-4c2e-ac6b-efbddb47a5a4"}]
2018-04-04 10:09:21:295 - info: [HTTP] <-- POST /wd/hub/session/fb071397-7d34-457d-8ae5-96b0052e2256/elements 200 20497 ms - 124 
2018-04-04 10:09:24:353 - info: [HTTP] --> POST /wd/hub/session/fb071397-7d34-457d-8ae5-96b0052e2256/element/9008f3d6-3636-4c2e-ac6b-efbddb47a5a4/click {"id":"9008f3d6-3636-4c2e-ac6b-efbddb47a5a4"}
2018-04-04 10:09:24:353 - info: [debug] [MJSONWP] Calling AppiumDriver.click() with args: ["9008f3d6-3636-4c2e-ac6b-efbddb47a5a4","fb071397-7d34-457d-8ae5-96b0052e2256"]
2018-04-04 10:09:24:369 - info: [debug] [JSONWP Proxy] Proxying [POST /element/9008f3d6-3636-4c2e-ac6b-efbddb47a5a4/click] to [POST http://localhost:8206/wd/hub/session/49683146-b490-4352-9a39-538a49790bff/element/9008f3d6-3636-4c2e-ac6b-efbddb47a5a4/click] with body: {"element":"9008f3d6-3636-4c2e-ac6b-efbddb47a5a4"}
2018-04-04 10:09:44:633 - info: [debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"49683146-b490-4352-9a39-538a49790bff","status":0,"value":true}
2018-04-04 10:09:44:633 - info: [debug] [MJSONWP] Responding to client with driver.click() result: true
2018-04-04 10:09:44:649 - info: [HTTP] <-- POST /wd/hub/session/fb071397-7d34-457d-8ae5-96b0052e2256/element/9008f3d6-3636-4c2e-ac6b-efbddb47a5a4/click 200 20285 ms - 76 
2018-04-04 10:09:44:665 - info: [HTTP] --> POST /wd/hub/session/fb071397-7d34-457d-8ae5-96b0052e2256/appium/device/hide_keyboard {}
2018-04-04 10:09:44:665 - info: [debug] [MJSONWP] Calling AppiumDriver.hideKeyboard() with args: [null,null,null,null,"fb071397-7d34-457d-8ae5-96b0052e2256"]
2018-04-04 10:09:44:665 - info: [debug] [ADB] Getting connected devices...
2018-04-04 10:09:44:711 - info: [debug] [ADB] 1 device(s) connected
2018-04-04 10:09:44:711 - info: [debug] [ADB] Running 'D:\Android SDK\platform-tools\adb.exe' with args: ["-P",5037,"-s","FA6A40311558","shell","dumpsys","input_method"]
2018-04-04 10:09:44:836 - error: [MJSONWP] Encountered internal error running command: Error: Soft keyboard not present, cannot hide keyboard
    at AndroidUiautomator2Driver.callee$0$0$ (C:\Users\Q4062\AppData\Roaming\npm\node_modules\appium\node_modules\appium-android-driver\lib\commands\general.js:59:11)
    at tryCatch (C:\Users\Q4062\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\Q4062\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\Q4062\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\Q4062\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
2018-04-04 10:09:44:836 - info: [HTTP] <-- POST /wd/hub/session/fb071397-7d34-457d-8ae5-96b0052e2256/appium/device/hide_keyboard 500 179 ms - 218 
2018-04-04 10:09:44:867 - info: [HTTP] --> GET /wd/hub/session/fb071397-7d34-457d-8ae5-96b0052e2256/window/current/size {}
2018-04-04 10:09:44:867 - info: [MJSONWP] Driver proxy active, passing request on via HTTP proxy
2018-04-04 10:09:44:867 - info: [debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/fb071397-7d34-457d-8ae5-96b0052e2256/window/current/size] to [GET http://localhost:8206/wd/hub/session/49683146-b490-4352-9a39-538a49790bff/window/current/size] with body: {}
2018-04-04 10:09:44:900 - info: [debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"49683146-b490-4352-9a39-538a49790bff\",\"status\":0,\"value\":{\"height\":1794,\"width\":1080}}"
2018-04-04 10:09:44:900 - info: [JSONWP Proxy] Replacing sessionId 49683146-b490-4352-9a39-538a49790bff with fb071397-7d34-457d-8ae5-96b0052e2256
2018-04-04 10:09:44:900 - info: [HTTP] <-- GET /wd/hub/session/fb071397-7d34-457d-8ae5-96b0052e2256/window/current/size 200 40 ms - 100 
2018-04-04 10:09:44:915 - info: [HTTP] --> POST /wd/hub/session/fb071397-7d34-457d-8ae5-96b0052e2256/elements {"using":"xpath","value":"//android.widget.TextView[@text='Deposits']"}
2018-04-04 10:09:44:915 - info: [debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["xpath","//android.widget.TextView[@text='Deposits']","fb071397-7d34-457d-8ae5-96b0052e2256"]
2018-04-04 10:09:44:915 - info: [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
2018-04-04 10:09:44:915 - info: [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
2018-04-04 10:09:44:915 - info: [debug] [BaseDriver] Waiting up to 0 ms for condition
2018-04-04 10:09:44:915 - info: [debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8206/wd/hub/session/49683146-b490-4352-9a39-538a49790bff/elements] with body: {"strategy":"xpath","selector":"//android.widget.TextView[@text='Deposits']","context":"","multiple":true}
2018-04-04 10:10:05:226 - info: [debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"49683146-b490-4352-9a39-538a49790bff","status":0,"value":[{"ELEMENT":"57d2af79-c412-496e-baec-7357381b1b2f"}]}
2018-04-04 10:10:05:226 - info: [debug] [MJSONWP] Responding to client with driver.findElements() result: [{"ELEMENT":"57d2af79-c412-496e-baec-7357381b1b2f"}]
2018-04-04 10:10:05:242 - info: [HTTP] <-- POST /wd/hub/session/fb071397-7d34-457d-8ae5-96b0052e2256/elements 200 20320 ms - 124 
2018-04-04 10:10:05:258 - info: [HTTP] --> GET /wd/hub/session/fb071397-7d34-457d-8ae5-96b0052e2256/element/57d2af79-c412-496e-baec-7357381b1b2f/location {}
2018-04-04 10:10:05:258 - info: [MJSONWP] Driver proxy active, passing request on via HTTP proxy
2018-04-04 10:10:05:258 - info: [debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/fb071397-7d34-457d-8ae5-96b0052e2256/element/57d2af79-c412-496e-baec-7357381b1b2f/location] to [GET http://localhost:8206/wd/hub/session/49683146-b490-4352-9a39-538a49790bff/element/57d2af79-c412-496e-baec-7357381b1b2f/location] with body: {}
2018-04-04 10:10:15:430 - info: [debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"49683146-b490-4352-9a39-538a49790bff\",\"status\":0,\"value\":{\"x\":66,\"y\":1428}}"
2018-04-04 10:10:15:430 - info: [JSONWP Proxy] Replacing sessionId 49683146-b490-4352-9a39-538a49790bff with fb071397-7d34-457d-8ae5-96b0052e2256
2018-04-04 10:10:15:430 - info: [HTTP] <-- GET /wd/hub/session/fb071397-7d34-457d-8ae5-96b0052e2256/element/57d2af79-c412-496e-baec-7357381b1b2f/location 200 10172 ms - 89 
2018-04-04 10:10:15:445 - info: [HTTP] --> GET /wd/hub/session/fb071397-7d34-457d-8ae5-96b0052e2256/element/57d2af79-c412-496e-baec-7357381b1b2f/location {}
2018-04-04 10:10:15:445 - info: [MJSONWP] Driver proxy active, passing request on via HTTP proxy
2018-04-04 10:10:15:445 - info: [debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/fb071397-7d34-457d-8ae5-96b0052e2256/element/57d2af79-c412-496e-baec-7357381b1b2f/location] to [GET http://localhost:8206/wd/hub/session/49683146-b490-4352-9a39-538a49790bff/element/57d2af79-c412-496e-baec-7357381b1b2f/location] with body: {}
2018-04-04 10:10:25:618 - info: [debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"49683146-b490-4352-9a39-538a49790bff\",\"status\":0,\"value\":{\"x\":66,\"y\":1428}}"
2018-04-04 10:10:25:618 - info: [JSONWP Proxy] Replacing sessionId 49683146-b490-4352-9a39-538a49790bff with fb071397-7d34-457d-8ae5-96b0052e2256
2018-04-04 10:10:25:618 - info: [HTTP] <-- GET /wd/hub/session/fb071397-7d34-457d-8ae5-96b0052e2256/element/57d2af79-c412-496e-baec-7357381b1b2f/location 200 10169 ms - 89 
2018-04-04 10:10:25:649 - info: [HTTP] --> GET /wd/hub/session/fb071397-7d34-457d-8ae5-96b0052e2256/element/57d2af79-c412-496e-baec-7357381b1b2f/location {}
2018-04-04 10:10:25:649 - info: [MJSONWP] Driver proxy active, passing request on via HTTP proxy
2018-04-04 10:10:25:649 - info: [debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/fb071397-7d34-457d-8ae5-96b0052e2256/element/57d2af79-c412-496e-baec-7357381b1b2f/location] to [GET http://localhost:8206/wd/hub/session/49683146-b490-4352-9a39-538a49790bff/element/57d2af79-c412-496e-baec-7357381b1b2f/location] with body: {}
2018-04-04 10:10:35:759 - info: [debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"49683146-b490-4352-9a39-538a49790bff\",\"status\":0,\"value\":{\"x\":66,\"y\":1428}}"
2018-04-04 10:10:35:759 - info: [JSONWP Proxy] Replacing sessionId 49683146-b490-4352-9a39-538a49790bff with fb071397-7d34-457d-8ae5-96b0052e2256
2018-04-04 10:10:35:759 - info: [HTTP] <-- GET /wd/hub/session/fb071397-7d34-457d-8ae5-96b0052e2256/element/57d2af79-c412-496e-baec-7357381b1b2f/location 200 10110 ms - 89 
2018-04-04 10:10:35:790 - info: [HTTP] --> POST /wd/hub/session/fb071397-7d34-457d-8ae5-96b0052e2256/element {"using":"xpath","value":"//android.widget.TextView[@text='Deposits']"}
2018-04-04 10:10:35:790 - info: [debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["xpath","//android.widget.TextView[@text='Deposits']","fb071397-7d34-457d-8ae5-96b0052e2256"]
2018-04-04 10:10:35:805 - info: [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
2018-04-04 10:10:35:806 - info: [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
2018-04-04 10:10:35:806 - info: [debug] [BaseDriver] Waiting up to 0 ms for condition
2018-04-04 10:10:35:806 - info: [debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8206/wd/hub/session/49683146-b490-4352-9a39-538a49790bff/element] with body: {"strategy":"xpath","selector":"//android.widget.TextView[@text='Deposits']","context":"","multiple":false}
2018-04-04 10:11:06:226 - info: [debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"49683146-b490-4352-9a39-538a49790bff","status":0,"value":{"ELEMENT":"d5934d0c-9f7a-41c0-817b-dcf550bc8a19"}}
2018-04-04 10:11:06:226 - info: [debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"d5934d0c-9f7a-41c0-817b-dcf550bc8a19"}
2018-04-04 10:11:06:226 - info: [HTTP] <-- POST /wd/hub/session/fb071397-7d34-457d-8ae5-96b0052e2256/element 200 30439 ms - 122 
2018-04-04 10:11:06:277 - info: [HTTP] --> GET /wd/hub/session/fb071397-7d34-457d-8ae5-96b0052e2256/screenshot {}
2018-04-04 10:11:06:277 - info: [debug] [MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["fb071397-7d34-457d-8ae5-96b0052e2256"]
2018-04-04 10:11:06:277 - info: [debug] [ADB] Device API level: 26
2018-04-04 10:11:07:213 - info: [debug] [MJSONWP] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAABDgAAAeACAYAAAArYecKAACAAElEQVR4AezBCZyddWHv/8/veZ6zn5k5s08m20z2kBAmQEJKWJKBFouYGETFC0VR1D+Wamn7b6y9N5q0UOr1gtuVqiUWeysV12FRRJKAGNCwTYjZCMmZJJNkMnNmnzlnzvr8jf9XesfjZIFktuT7fhvrxq+5iIiIiIiIiIiMYxYiIiIiIiIiIuOchYiIiIiIiIjIOGchIiIiIiIiIjLOWYiIiIiIiIiIjHMWIiIiIiIiIiLjnIWIiIiIiIiIyDhnISIiIiIiIiIyzlmIiIiIiIiIiIxzFiIiIiIiIiIi45yFiIiIiIiIiMg45zAOGQN+j4MxkM25JNNZREREREREROT85TDGGQMBr0PY7yHoc/DYFj6PzbwpJQS9Du19SXYe7MB1IZnJ0jeQJp7MkExnERERERE5m+pqyygKeumOp2iMxhhPIiEfF9WU0h1P0RiNIXKm5k0uoSjo5XR0x1NsP9iByHByGKMsY4iEvFRGgiyeWcmf1E1i6ZwJTC4LM5R0NsfuQ1385JX9vLC7hdeb2unoG6A3kUZERERE5O2oqy3jtmWzWbm4lpqKAvI1tfbSsCXKt5/dTWM0xlh2UU0pG9et5JgPf3UTD2/axXhSWuCnMOClKOQl4LU5prQgwFDaexMck0hl6e5P0ZNI0d47wLlsdnWE3Ye7GElFQS8lBX5ExgqHMcYyhsKgl6nlYW6vn8stV8+iJOzjVDy2xfwpJcyfUkI25xJt7eEbT+/ge5vfpL03SX8yjYiIiIjI6airLeP+25dy9bxqTqamooBP3bCAT92wgOe2H+avvrWZxmiMsW79Xcs55uFNuxirAl6HqkiQyWVhCoNe3orSggDHTSrlv/TEUxyM9dHSFSeRynCumF0dYWZ1hN2HuxA5nxnrxq+5jBGObTGtspDbls3m49fNoyTs40xkcy57W7p54PGt/OhXUdp6EoiIiIiInMwn37mABz68lLfr...
2018-04-04 10:11:07:229 - info: [HTTP] <-- GET /wd/hub/session/fb071397-7d34-457d-8ae5-96b0052e2256/screenshot 200 953 ms - 175650 
2018-04-04 10:11:07:244 - info: [HTTP] --> POST /wd/hub/session/fb071397-7d34-457d-8ae5-96b0052e2256/elements {"using":"xpath","value":"//android.widget.TextView[@text='Deposits']"}
2018-04-04 10:11:07:244 - info: [debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["xpath","//android.widget.TextView[@text='Deposits']","fb071397-7d34-457d-8ae5-96b0052e2256"]
2018-04-04 10:11:07:244 - info: [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
2018-04-04 10:11:07:244 - info: [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
2018-04-04 10:11:07:244 - info: [debug] [BaseDriver] Waiting up to 0 ms for condition
2018-04-04 10:11:07:244 - info: [debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8206/wd/hub/session/49683146-b490-4352-9a39-538a49790bff/elements] with body: {"strategy":"xpath","selector":"//android.widget.TextView[@text='Deposits']","context":"","multiple":true}
2018-04-04 10:11:27:587 - info: [debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"49683146-b490-4352-9a39-538a49790bff","status":0,"value":[{"ELEMENT":"9de986df-39b5-4957-b788-3480235ce648"}]}
2018-04-04 10:11:27:587 - info: [debug] [MJSONWP] Responding to client with driver.findElements() result: [{"ELEMENT":"9de986df-39b5-4957-b788-3480235ce648"}]
2018-04-04 10:11:27:602 - info: [HTTP] <-- POST /wd/hub/session/fb071397-7d34-457d-8ae5-96b0052e2256/elements 200 20354 ms - 124 
2018-04-04 10:11:30:646 - info: [HTTP] --> POST /wd/hub/session/fb071397-7d34-457d-8ae5-96b0052e2256/element/9de986df-39b5-4957-b788-3480235ce648/click {"id":"9de986df-39b5-4957-b788-3480235ce648"}
2018-04-04 10:11:30:661 - info: [debug] [MJSONWP] Calling AppiumDriver.click() with args: ["9de986df-39b5-4957-b788-3480235ce648","fb071397-7d34-457d-8ae5-96b0052e2256"]
2018-04-04 10:11:30:661 - info: [debug] [JSONWP Proxy] Proxying [POST /element/9de986df-39b5-4957-b788-3480235ce648/click] to [POST http://localhost:8206/wd/hub/session/49683146-b490-4352-9a39-538a49790bff/element/9de986df-39b5-4957-b788-3480235ce648/click] with body: {"element":"9de986df-39b5-4957-b788-3480235ce648"}
2018-04-04 10:11:41:971 - info: [debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"49683146-b490-4352-9a39-538a49790bff","status":0,"value":true}
2018-04-04 10:11:41:971 - info: [debug] [MJSONWP] Responding to client with driver.click() result: true
2018-04-04 10:11:41:987 - info: [HTTP] <-- POST /wd/hub/session/fb071397-7d34-457d-8ae5-96b0052e2256/element/9de986df-39b5-4957-b788-3480235ce648/click 200 11335 ms - 76

**Comment by mykola-mokhnach** [comment]
uiatomator only adds a delay if the application is not in idle state when a lookup is being executed. Make sure you don't have background animations in your app or disable them before test.

there is nothing else that can be done there from our side.

**Comment by abhishekmangudkarQK** [comment]
I tried with both options of uiAutomator & background animation. Didn't work..

I'm trying with different device with same OS..let's see..
