### ISSUE TITLE
iOS 11.4 -- /alert/text is returning null

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#10497]
## The problem

* The call to WebDriverAgent `GET: /alert/text` is returning `null`

## Environment

* iOS 11.4 (XCode 9.4 beta)

## Details

* Running `alert-e2e-specs.js` in XCUITest Driver is failing

```
XCUITestDriver - alerts - should detect Simple:
     TypeError: Cannot read property 'should' of null
      at Context.callee$1$0$ (test/functional/basic/alert-e2e-specs.js:44:32)
      at tryCatch (node_modules/babel-runtime/regenerator/runtime.js:67:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (node_modules/babel-runtime/regenerator/runtime.js:315:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (node_modules/babel-runtime/regenerator/runtime.js:100:21)
      at GeneratorFunctionPrototype.invoke (node_modules/babel-runtime/regenerator/runtime.js:136:37)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:160:7)
```

* In XCUITestDriver alert.js this line is returning null: ```this.proxyCommand('/alert/text', 'GET')```

## Code To Reproduce Issue [ Good To Have ]

* From XCUITestDriver: ```gulp transpile && mocha --timeout 7000000 build/test/functional/basic/alert-e2e-specs.js ```

**Comment by dpgraham** [comment]
False alarm. Was using an outdated WebDriverAgent.
