### ISSUE TITLE
AppiumCommandExecutor: VTable failed, and 'Dispose' method lacks implementation

### ISSUE THREAD

**Issue by gamesguru** [appium/appium#10514]
## The problem

After updating appium, node, and packages in visual studio I can no longer get the phone to connect.

## Environment

Appium 1.7.2
java 1.8.0_162
node 5.8.0
samsung J3 (6.0.1)
macOS and win10

## Details
Occurs at the constructor for the device driver (line 230 of testLogic.cs)

Source code: [appiumAndroidUnitTests.zip](https://github.com/appium/appium/files/1895236/appiumAndroidUnitTests.zip)

```
macOS
 ===============
  --Exception--
 ===============
4/10/2018 11:18:23 AM
appium-dotnet-driver, -2146233054
System.Collections.ListDictionaryInternal
VTable setup of type OpenQA.Selenium.Appium.Service.AppiumCommandExecutor failed


Void .ctor(Uri, ICapabilities)
  at OpenQA.Selenium.Appium.AppiumDriver`1[W]..ctor (System.Uri remoteAddress, OpenQA.Selenium.ICapabilities desiredCapabilities) [0x00000] in <9b3ceeffa60d410090f33f3b9ea8ebde>:0 
  at OpenQA.Selenium.Appium.Android.AndroidDriver`1[W]..ctor (System.Uri remoteAddress, OpenQA.Selenium.Remote.DesiredCapabilities desiredCapabilities) [0x0000d] in <9b3ceeffa60d410090f33f3b9ea8ebde>:0 
  at appiumUnitTests.testLogic.runTests (appiumUnitTests.Program+device de) [0x00846] in /Users/sjaroch/Desktop/repos/appiumandroidunittestscsharp/appiumUnitTests/testLogic.cs:230 
 ===================
  --End exception--
 ===================

 
 
 Windows
 ===============
  --Exception--
 ===============
4/10/2018 11:20:26 AM
appium-dotnet-driver, -2146233054
System.Collections.ListDictionaryInternal
Method 'Dispose' in type 'OpenQA.Selenium.Appium.Service.AppiumCommandExecutor' from assembly 'appium-dotnet-driver, Version=3.0.0.2, Culture=neutral, PublicKeyToken=null' does not have an implementation.


Void .ctor(System.Uri, OpenQA.Selenium.ICapabilities, System.TimeSpan)
   at OpenQA.Selenium.Appium.AppiumDriver`1..ctor(Uri remoteAddress, ICapabilities desiredCapabilities, TimeSpan commandTimeout)
   at OpenQA.Selenium.Appium.AppiumDriver`1..ctor(Uri remoteAddress, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Appium.Android.AndroidDriver`1..ctor(Uri remoteAddress, DesiredCapabilities desiredCapabilities)
   at appiumUnitTests.testLogic.runTests(device de) in C:\Users\sjaroch\Desktop\android-test-lib\appiumAndroidUnitTests\appiumUnitTests\testLogic.cs:line 230
 ===================
  --End exception--
 ===================
```

**Comment by mykola-mokhnach** [comment]
I assume this should be reported to https://github.com/appium/appium-dotnet-driver

**Comment by gamesguru** [comment]
posted another copy @ https://github.com/appium/appium-dotnet-driver/issues/217
feel free to archive this one here
