### ISSUE TITLE
Does appium support automation of QT/QML based apps ?

### ISSUE THREAD

**Issue by shantanuchandalia** [appium/appium#10535]
## The problem

Do we have any support for QT/QLM based mobile apps ?
I am testing this app using Appium and i am getting frequent crashes. I am able to detect objects and the script runs fine but crash happens many times. 

Log : 

? W/libO2ITeach.so: (null):0 ((null)): QQuickButton QVariant(Invalid) QRect(0,0 0x0)
? E/AndroidRuntime: FATAL EXCEPTION: main
                    Process: com.ifm.Syntron.O2ITeach, PID: 11728
                    java.lang.ArrayIndexOutOfBoundsException: int[] offset=5 length=1 dst.length=5
                        at org.qtproject.qt5.android.accessibility.QtNativeAccessibility.childIdListForAccessibleObject(Native Method)
                        at org.qtproject.qt5.android.accessibility.QtAccessibilityDelegate.getNodeForVirtualViewId(QtAccessibilityDelegate.java:339)
                        at org.qtproject.qt5.android.accessibility.QtAccessibilityDelegate.access$800(QtAccessibilityDelegate.java:64)
                        at org.qtproject.qt5.android.accessibility.QtAccessibilityDelegate$1.createAccessibilityNodeInfo(QtAccessibilityDelegate.java:353)
                        at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfVirtualNode(AccessibilityInteractionController.java:1154)
                        at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1057)
                        at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1053)
                        at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1053)
                        at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1053)
                        at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchAccessibilityNodeInfos(AccessibilityInteractionController.java:852)
                        at android.view.AccessibilityInteractionController.findAccessibilityNodeInfoByAccessibilityIdUiThread(AccessibilityInteractionController.java:156)
                        at android.view.AccessibilityInteractionController.-wrap1(AccessibilityInteractionController.java)
                        at android.view.AccessibilityInteractionController$PrivateHandler.handleMessage(AccessibilityInteractionController.java:1208)
                        at android.os.Handler.dispatchMessage(Handler.java:102)
                        at android.os.Looper.loop(Looper.java:163)
                        at android.app.ActivityThread.main(ActivityThread.java:6237)
                        at java.lang.reflect.Method.invoke(Native Method)
                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:877)
                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
? W/ActivityManager:   Force finishing activity com.ifm.Syntron.O2ITeach/org.qtproject.qt5.android.bindings.QtActivity
? W/KloServer: Aborted broadcast does not supprt for: com.ifm.Syntron.O2ITeach
? W/ActivityManager: Activity pause timeout for ActivityRecord{c34c6f0 u0 com.ifm.Syntron.O2ITeach/org.qtproject.qt5.android.bindings.QtActivity t168 f}
? W/ActivityManager: Activity destroy timeout for ActivityRecord{c34c6f0 u0 com.ifm.Syntron.O2ITeach/org.qtproject.qt5.android.bindings.QtActivity t168 f}

## Environment

* Appium version (or git revision) that exhibits the issue: Appium v1.7.1
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): Node.js 8.9.3 (x64) and npm
* Mobile platform/version under test: 7.0 android
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: Appium.app|exe

**Comment by mykola-mokhnach** [comment]
How this is related to Appium? The crash happens in the application under test

**Comment by mykola-mokhnach** [comment]
closed as not an issue
