### ISSUE TITLE
KEYS.RETURN in sendkeys not working on iOS real device

### ISSUE THREAD

**Issue by shridharkalagi** [appium/appium#10566]
## The problem

KEYS.RETURN in sendkeys not working on iOS real device

## Environment

* Appium version (or git revision) that exhibits the issue:1.8.0Beta-5
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:10.12.6 
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:iOS
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe:CLI
* XCODE version - 9.2

## Link to Appium logs
Server logs [here](https://gist.github.com/shridharkalagi/ed667b7e49abbc35dee89e0ca9b646b5)

Client logs -
`org.openqa.selenium.UnsupportedCommandException: sendKeysToActiveElement
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
System info: host: 'INshridhk.local', ip: 'fe80:0:0:0:10bd:6cec:8ffc:ee78%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_65'
Driver info: driver.version: AppiumDriver
	at org.openqa.selenium.remote.http.AbstractHttpCommandCodec.encode(AbstractHttpCommandCodec.java:218)
	at org.openqa.selenium.remote.http.AbstractHttpCommandCodec.encode(AbstractHttpCommandCodec.java:117)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:152)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:129)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at org.openqa.selenium.remote.RemoteExecuteMethod.execute(RemoteExecuteMethod.java:35)
	at org.openqa.selenium.remote.RemoteKeyboard.sendKeys(RemoteKeyboard.java:38)
	at com.buynow.flows.iOSFlow.keyBoardback(iOSFlow.java:282)`

## Code To Reproduce Issue [ Good To Have ]
((AppiumDriver<MobileElement>) driver).getKeyboard().sendKeys(Keys.RETURN)

**Comment by shridharkalagi** [comment]
@mykola-mokhnach can you please look into this?

**Comment by mykola-mokhnach** [comment]
This won't work with xcuitest. You could show the keyboard, locate and tap the necessary key there instead.
