### ISSUE TITLE
Implicit timeOut does not work

### ISSUE THREAD

**Issue by WolfmosRioja** [appium/appium#10583]
I can't use the implicit time out.
If I set 5 or 500 seconds the result is the same.

driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);

I paste the log info

org.openqa.selenium.WebDriverException: org.openqa.selenium.WebDriverException: Returned value cannot be converted to WebElement: {stacktrace=NoSuchElementError: An element could not be located on the page using the given search parameters.
    at AndroidUiautomator2Driver.callee$0$0$ (C:\Users\SergioOlmos\AppData\Roaming\npm\node_modules\appium\node_modules\appium-android-driver\lib\commands\find.js:69:13)
    at tryCatch (C:\Users\SergioOlmos\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\SergioOlmos\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\SergioOlmos\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\SergioOlmos\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at <anonymous>, error=no such element, message=An element could not be located on the page using the given search parameters.}
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
System info: host: 'DESKTOP-DCGVD8Q', ip: '172.19.48.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_144'
Driver info: driver.version: AndroidDriver

**Comment by mykola-mokhnach** [comment]
The error happens on java client side, so please report it where it should be reported: https://github.com/appium/java-client

**Comment by WolfmosRioja** [comment]
Thanks for the support @mykola-mokhnach ! --> https://github.com/appium/java-client/issues/872
