### ISSUE TITLE
Capturing performance data for native app

### ISSUE THREAD

**Issue by klementynka** [appium/appium#10595]
Hello, 
I am trying to capturing performance data for native app, but I have an error when .trace file is written. Can you please take a look at this and tell me what I am doing wrong. Thank you :)

My environment:
Appium 1.8.0
Mac High Sierra 10.13.3
Eclipse Neon.3 Release (4.6.3)
Simulator iPad Air 2 iOS 11.2
Node v8.9.4

My set up:
  DesiredCapabilities caps = new DesiredCapabilities();
    caps.setCapability("platformName", "iOS");
    caps.setCapability("platformVersion", "11.2");
    caps.setCapability("deviceName", "iPad Air 2");
    caps.setCapability("appiumVersion", "1.8.0");
    caps.setCapability("automationName", "XCUITest");
    caps.setCapability("orientation", "LANDSCAPE");
    caps.setCapability("app", "...core.app");
 URL remoteUrl = new URL("http://localhost:4723/wd/hub");
		    driver = new IOSDriver<MobileElement>(remoteUrl, caps);

My code:
sw = new swPage(driver);
File traceZip = new File("/.../LoginLeaks.trace.zip");

try {
		HashMap<String, Object> args = new HashMap<>();
		args.put("pid", "current");
		args.put("profileName", "Time Profiler");
		args.put("timeout", 60000);
		driver.executeScript("mobile: startPerfRecord", args);

		Login(driver);

		args = new HashMap<>();
		args.put("profileName", "Time Profiler");
		String b64Zip = (String) driver.executeScript("mobile: stopPerfRecord", args);
		byte[] bytesZip = Base64.getMimeDecoder().decode(b64Zip);
		FileOutputStream stream = new FileOutputStream(traceZip);
		stream.write(bytesZip);
		stream.close();
	} finally {
		driver.quit();
	}
}

	public void Login(IOSDriver<MobileElement> driver) throws Exception {

		sw.clikIgnoreOnTheUpdateAvailable();
		sw.typeUsername();
		sw.clickLoginButton();
		sw.typePassword();
		sw.clickLoginButton();
	}

I have following error when running my tests. Mentioned line 44 of PerformanceTest.java is
String b64Zip = (String) driver.executeScript("mobile: stopPerfRecord", args);

FAILED: testAppActivity
java.lang.ClassCastException: com.google.common.collect.Maps$TransformedEntriesMap cannot be cast to java.lang.String
	at makerspace.PerformanceTest.testAppActivity(PerformanceTest.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

And I have following error in the Appium log:

[W3C] Encountered internal error running command: Error: Cannot read '/var/folders/z3/5pm3bdj96jg89sw4_tx9t69jwcpthd/T/2018324-1680-1181eiz.qy84/appium_perf_Time_Profiler_1524617236037.trace.zip' to the memory, because the file is too large (13.22 MB >= 3.63 MB). Try to provide a link to a remote writable location instead.
[W3C]     at encodeBase64OrUpload$ (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/utils.js:420:13)
[W3C]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[W3C]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[W3C]     at <anonymous>

[Appium log](https://gist.github.com/klementynka/bb74c0fc44ff2b3c1961b5af1aa169f5.js)

**Comment by mykola-mokhnach** [comment]
There is a bug there with memory calculation. I'll fix it soon

**Comment by mykola-mokhnach** [comment]
Linking https://github.com/appium/appium-xcuitest-driver/pull/656

**Comment by mykola-mokhnach** [comment]
The fix has been published to appium@beta

**Comment by klementynka** [comment]
It is working now. Thanks for help. :)
