### ISSUE TITLE
Not able to launch appium after upgrade node 10.0.0

### ISSUE THREAD

**Issue by priyankshah217** [appium/appium#10609]
## The problem

Appium is not being launched after node upgrade to 10.0.0

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: High sierra 10.13.4 (17E199)
* Node.js version (unless using Appium.app|exe): 10.0.0
* Mobile platform/version under test: Not required
* Real device or emulator/simulator: Not required
* Appium CLI or Appium.app|exe: Not Required

## Details

Appium 1.8.0 was working fine with older version of node, but after upgrade node to recent one (10.0.0), unable to launch appium.

## Link to Appium logs

Please fine below appium logs.

```
internal/util.js:360
    const filename = frame.getFileName();
                           ^

TypeError: frame.getFileName is not a function
    at isInsideNodeModules (internal/util.js:360:28)
    at showFlaggedDeprecation (buffer.js:149:8)
    at new Buffer (buffer.js:174:3)
    at retrieveSourceMap (/usr/local/lib/node_modules/appium/node_modules/asyncbox/node_modules/source-map-support/source-map-support.js:118:21)
    at mapSourcePosition (/usr/local/lib/node_modules/appium/node_modules/asyncbox/node_modules/source-map-support/source-map-support.js:140:21)
    at wrapCallSite (/usr/local/lib/node_modules/appium/node_modules/asyncbox/node_modules/source-map-support/source-map-support.js:303:20)
    at /usr/local/lib/node_modules/appium/node_modules/asyncbox/node_modules/source-map-support/source-map-support.js:338:26
    at Array.map (<anonymous>)
    at Function.prepareStackTrace (/usr/local/lib/node_modules/appium/node_modules/asyncbox/node_modules/source-map-support/source-map-support.js:337:24)
    at process.emit (/usr/local/lib/node_modules/appium/node_modules/asyncbox/node_modules/source-map-support/source-map-support.js:387:52)
    at process._fatalException (internal/bootstrap/node.js:435:27)

```

## Code To Reproduce Issue [ Good To Have ]

- Upgrade node to latest one (10.0.0)

- Launch appium

It working fine after downgrading node version.

**Comment by pavanbachu0604** [comment]
even I am facing the same issue . @priyankshah217  : Did you find any resolution ?

**Comment by FA-tvonmoll** [comment]
Same here. As he mentioned initially: reverting back (in my case, I went to 9.10.1) works as a temporary workaround.

**Comment by pavanbachu0604** [comment]
@FA-tvonmoll how to downgrade npm to  9.10.1 ?

**Comment by FA-tvonmoll** [comment]
Depends how you installed it in the first place (and your OS). I use hombrew on macOS, so it's `$ brew switch node 9.10.1`.

Looks like you can do it via npm as well: https://exhesham.com/2017/12/01/how-to-downgrade-nodejs-and-npm-on-windows/

**Comment by imurchie** [comment]
I would highly recommend using a node version manager, like `nvm` (https://github.com/creationix/nvm).

In the meantime, I am looking into why this is happening.

**Comment by pavanbachu0604** [comment]
@imurchie when installing using nvm the node is getting saved in location /Users/xxxxx/.nvm/versions/node/v9.11.1/bin/node and appium is saved in /Users/xxxx/.nvm/versions/node/v9.11.1/bin/appium , the problem is while running the test cases it is trying to download the dependencies and I have firewall issue at work.

**Comment by PaulysGitHub** [comment]
Yup, happening to me too! Rolling back npm version.

**Comment by priyankshah217** [comment]
@PaulysGitHub , Do this in order to restore old node version.
Even I faced the same issue, downgrade node version by 

- Uninstall node `brew uninstall node`

- Install node lower version of node `brew install node@8`

- Do force link to node 8 `brew link --overwrite node@8 --force`

It will work.

Other than you can nvm to restore old version, and ensure that you need to reinstall appium.

**Comment by barotashish** [comment]
ashish@ashish-barot:~$ appium
internal/util.js:360
    const filename = frame.getFileName();
                           ^

TypeError: frame.getFileName is not a function
    at isInsideNodeModules (internal/util.js:360:28)
    at showFlaggedDeprecation (buffer.js:149:8)
    at new Buffer (buffer.js:174:3)
    at retrieveSourceMap (/home/linuxbrew/.linuxbrew/lib/node_modules/appium/node_modules/asyncbox/node_modules/source-map-support/source-map-support.js:118:21)
    at mapSourcePosition (/home/linuxbrew/.linuxbrew/lib/node_modules/appium/node_modules/asyncbox/node_modules/source-map-support/source-map-support.js:140:21)
    at wrapCallSite (/home/linuxbrew/.linuxbrew/lib/node_modules/appium/node_modules/asyncbox/node_modules/source-map-support/source-map-support.js:303:20)
    at /home/linuxbrew/.linuxbrew/lib/node_modules/appium/node_modules/asyncbox/node_modules/source-map-support/source-map-support.js:338:26
    at Array.map (<anonymous>)
    at Function.prepareStackTrace (/home/linuxbrew/.linuxbrew/lib/node_modules/appium/node_modules/asyncbox/node_modules/source-map-support/source-map-support.js:337:24)
    at process.emit (/home/linuxbrew/.linuxbrew/lib/node_modules/appium/node_modules/asyncbox/node_modules/source-map-support/source-map-support.js:387:52)
    at process._fatalException (internal/bootstrap/node.js:435:27)

Getting same error on Ubuntu 17.10

**Comment by barotashish** [comment]
https://discuss.appium.io/t/how-to-install-appium-on-ubuntu-linux-17-10/21882

**Comment by lolotoms** [comment]
I have the same on mac OS platform. I installed the last nove version (brew install node) and tried to upgrade (node 10.0.0 already installed). Now i am trying to install appium (npm install -g appium) and had the result : 
/usr/local/bin/appium -> /usr/local/lib/node_modules/appium/build/lib/main.js

> appium-chromedriver@3.5.2 install /usr/local/lib/node_modules/appium/node_modules/appium-chromedriver
> node install-npm.js

Error trying to install Chromedriver binary. Waiting and trying again. frame.getFileName is not a function
...
Unable to import install script. Re-run `install appium-chromedriver` manually.

> appium-selendroid-driver@1.7.0 install /usr/local/lib/node_modules/appium/node_modules/appium-selendroid-driver
> node ./bin/install.js

internal/util.js:360
    const filename = frame.getFileName();
                           ^

TypeError: frame.getFileName is not a function
    at isInsideNodeModules (internal/util.js:360:28)
    at showFlaggedDeprecation (buffer.js:149:8)
    at new Buffer (buffer.js:174:3)
    at Array.<anonymous> (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/source-map-support/source-map-support.js:149:21)
    at /usr/local/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/source-map-support/source-map-support.js:53:24
    at mapSourcePosition (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/source-map-support/source-map-support.js:171:21)
    at wrapCallSite (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/source-map-support/source-map-support.js:343:20)
    at /usr/local/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/source-map-support/source-map-support.js:378:26
    at Array.map (<anonymous>)
    at Function.prepareStackTrace (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/source-map-support/source-map-support.js:377:24)
    at process.emit (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/source-map-support/source-map-support.js:431:52)
    at process._fatalException (internal/bootstrap/node.js:435:27)
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! appium-selendroid-driver@1.7.0 install: `node ./bin/install.js`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the appium-selendroid-driver@1.7.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2018-04-30T09_15_45_743Z-debug.log

**Comment by imurchie** [comment]
Yes. As it stands, this WILL NOT WORK. The latest Appium was released _before_ Node 10 was released. We are working on getting it working.

**Comment by whyboris** [comment]
For reference, I have a similar `frame.getFileName` error when running _Protractor_ e2e tests (on an Angular app) on Node 10. No such problem occurs on previous (v8 & v9) versions of Node.

**Comment by aKaltenb** [comment]
Node has been updated to 10.1.0.
appium is launching again

**Comment by imurchie** [comment]
Appium 1.8.1-beta (`npm install -g appium@beta` ought to work.

**Comment by barotashish** [comment]
Let me try npm install -g appium@beta 

as I am also getting error with npm install -g appium ( with Node version 10.0.0) 

ashish@ashish-barot:~/Documents/Testing Tool$ npm install -g appium
/home/ashish/.nvm/versions/node/v10.0.0/bin/appium -> /home/ashish/.nvm/versions/node/v10.0.0/lib/node_modules/appium/build/lib/main.js

> appium-chromedriver@3.5.2 install /home/ashish/.nvm/versions/node/v10.0.0/lib/node_modules/appium/node_modules/appium-chromedriver
> node install-npm.js

Error trying to install Chromedriver binary. Waiting and trying again. frame.getFileName is not a function
Error trying to install Chromedriver binary. Waiting and trying again. frame.getFileName is not a function
Error trying to install Chromedriver binary. Waiting and trying again. frame.getFileName is not a function

**Comment by aKaltenb** [comment]
updating to Node 10.1.0 solves this error

**Comment by barotashish** [comment]
Yes Now my installation is successful 

npm install -g appium@beta  - this is working fine. 

Thank you everyone for your help and input !

**Comment by justintoth** [comment]
This allows the installation of appium to work, but running appium gives the same error...

> C:\Users\justin>appium -v
> 1.8.1-beta1
> 
> C:\Users\justin>appium
> internal/util.js:360
>     const filename = frame.getFileName();
>                            ^
> 
> TypeError: frame.getFileName is not a function
>     at isInsideNodeModules (internal/util.js:360:28)
>     at showFlaggedDeprecation (buffer.js:149:8)
>     at new Buffer (buffer.js:174:3)
>     at Array.<anonymous> (C:\Users\justin\AppData\Roaming\npm\node_modules\appium\node_modules\appium-espresso-driver\node_modules\source-map-support\source-map-support.js:149:21)
>     at C:\Users\justin\AppData\Roaming\npm\node_modules\appium\node_modules\appium-espresso-driver\node_modules\source-map-support\source-map-support.js:53:24
>     at mapSourcePosition (C:\Users\justin\AppData\Roaming\npm\node_modules\appium\node_modules\appium-espresso-driver\node_modules\source-map-support\source-map-support.js:171:21)
>     at wrapCallSite (C:\Users\justin\AppData\Roaming\npm\node_modules\appium\node_modules\appium-espresso-driver\node_modules\source-map-support\source-map-support.js:343:20)
>     at C:\Users\justin\AppData\Roaming\npm\node_modules\appium\node_modules\appium-espresso-driver\node_modules\source-map-support\source-map-support.js:378:26
>     at Array.map (<anonymous>)
>     at Function.prepareStackTrace (C:\Users\justin\AppData\Roaming\npm\node_modules\appium\node_modules\appium-espresso-driver\node_modules\source-map-support\source-map-support.js:377:24)
>     at process.emit (C:\Users\justin\AppData\Roaming\npm\node_modules\appium\node_modules\appium-espresso-driver\node_modules\source-map-support\source-map-support.js:431:52)
>     at process._fatalException (internal/bootstrap/node.js:435:27)
