### ISSUE TITLE
 Encountered internal error running command: Error: An error occurred     at JWProxy.command$

### ISSUE THREAD

**Issue by fangnavinfo** [appium/appium#10620]
## The problem
All the testcase return false,  when testcases run  for a long time(3 hours). 

appium record log:
error] [MJSONWP] Encountered internal error running command: Error: An error occurred
    at JWProxy.command$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:176:15)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: IOS Sierra 10.12.6
* Node.js version (unless using Appium.app|exe):v9.4.0
* Mobile platform/version under test:IPAD 10.3.3
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
The log is too big,  gist return error when i push it, so i push it on github
https://github.com/fangnavinfo/antest/blob/master/appium-server-logs.txt.zip

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
This is some third party issue, which causes the device to stop responding Appium commands. There is nothing we can do on Appium side. I'd try to reboot the device from time to time.
