### ISSUE TITLE
unable to click on the element after clicking on the frame layout element 

### ISSUE THREAD

**Issue by sai-pop** [appium/appium#10636]
Hi I am unable to click on any element after clicking on the frame layout element.

ie.. after clicking on the drop-down option i am unable to click on any element.

**My code:**

login.Createnewaccountlink(driver).click();												
		createaccount.fName(driver).sendKeys(ear.getCellData(System.getProperty("user.dir")+"\\src\\main\\java\\com\\veriotapp\\Datasheets\\loginvalidations.xlsx","cavalidations","Firstname",3));
		createaccount.lName(driver).sendKeys(ear.getCellData(System.getProperty("user.dir")+"\\src\\main\\java\\com\\veriotapp\\Datasheets\\loginvalidations.xlsx","cavalidations","Lastname",3));
		createaccount.email(driver).sendKeys(ear.getCellData(System.getProperty("user.dir")+"\\src\\main\\java\\com\\veriotapp\\Datasheets\\loginvalidations.xlsx","cavalidations","Email",3));
		createaccount.password(driver).sendKeys(ear.getCellData(System.getProperty("user.dir")+"\\src\\main\\java\\com\\veriotapp\\Datasheets\\loginvalidations.xlsx","cavalidations","Password",3));
		createaccount.cpassword(driver).sendKeys(ear.getCellData(System.getProperty("user.dir")+"\\src\\main\\java\\com\\veriotapp\\Datasheets\\loginvalidations.xlsx","cavalidations","Confirm Password",3));
		//	createaccount.secur(ear.getCellData(System.getProperty("user.dir")+"\\src\\main\\java\\com\\veriotapp\\Datasheets\\loginvalidations.xlsx","cavalidations","Security question",3));
		createaccount.answer(driver).sendKeys(ear.getCellData(System.getProperty("user.dir")+"\\src\\main\\java\\com\\veriotapp\\Datasheets\\loginvalidations.xlsx","cavalidations","Answer",3));
		createaccount.privacypolicy_checkbox(driver).click();	
		createaccount.ageconfirm_checkbox(driver).click();
		createaccount.security_dropdownicon(driver).click();
		/*List<WebElement> qstns = createaccount.security_dropdownlist(driver).findElements(By.id("com.veriot.veriotventure.qa:id/question_list"));
		System.out.println(qstns.size());*/
		driver.findElement(By.xpath("//*[@class='android.widget.RelativeLayout'][@index='2']")).click();	
		driver.findElement(By.id("com.veriot.veriotventure.qa:id/register_question3")).click();
		WebElement 	element=createaccount.privacypolicy_checkbox(driver);
		JavascriptExecutor executor = (JavascriptExecutor)driver;
		executor.executeScript("arguments[0].click();", element);
		createaccount.privacypolicy_checkbox(driver).click();	
		WebDriverWait wait=new WebDriverWait(driver, 90);
		wait.until(ExpectedConditions.visibilityOfElementLocated((By.id("com.veriot.veriotventure.qa:id/register_sign_up"))));
		createaccount.CreateAccount_but(driver).isDisplayed();
		createaccount.CreateAccount_but(driver).click();

**Error logs**:::
org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T15:28:36.4Z'
System info: host: 'HYD-VPULIPAKA', ip: '172.19.0.155', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_45'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{app=D:\My workspace\veriot-android\Veriot_qa.apk, appPackage=com.veriot.veriotventure.qa, deviceScreenSize=1080x1920, networkConnectionEnabled=true, warnings={}, appWaitPackage=com.veriot.veriotventure.qa, appWaitActivity=com.veriot.veriotventure.qa.activity.SplashActivity, databaseEnabled=false, version=7.1.1, deviceName=emulator-5554, platform=LINUX, deviceUDID=emulator-5554, appActivity=com.veriot.veriotventure.qa.activity.SplashActivity, desired={app=D:\My workspace\veriot-android\Veriot_qa.apk, unicodeKeyboard=true, platformName=Android, version=7.1.1, deviceName=Nexus_5X, resetKeyboard=true}, platformVersion=7.1.1, webStorageEnabled=false, locationContextEnabled=false, takesScreenshot=true, javascriptEnabled=true, deviceModel=Android SDK built for x86, unicodeKeyboard=true, deviceManufacturer=Google, platformName=LINUX, resetKeyboard=true}]
Session ID: 0cae6f0e-232d-40d3-ac82-db721b31c12f
*** Element info: {Using=id, value=com.veriot.veriotventure.qa:id/register_question3}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:82)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:45)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:89)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:586)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:356)
	at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:62)
	at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.findElement(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementById(RemoteWebDriver.java:402)
	at io.appium.java_client.DefaultGenericMobileDriver.findElementById(DefaultGenericMobileDriver.java:70)
	at io.appium.java_client.AppiumDriver.findElementById(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.findElementById(AndroidDriver.java:1)
	at org.openqa.selenium.By$ById.findElement(By.java:218)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:348)
	at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:58)
	at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.findElement(AndroidDriver.java:1)
	at com.veriotandroid.MainTests.CreateAccountvalidations.fnamemorethan64char(CreateAccountvalidations.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
![create account](https://user-images.githubusercontent.com/20333910/39513451-04cbb666-4e12-11e8-8e08-1a7220645a0a.png)

**Comment by mykola-mokhnach** [comment]
You must switch to webview context in order to properly interact with elements there

**Comment by sai-pop** [comment]
after switching to web view too i am unable to click on the elements

**Comment by sai-pop** [comment]
still unable to click on other elements after clicking on the frame-layout elements

**Comment by prasanna532** [comment]
Iam also facing the same issue 

Even is have tried with switchTo().frame() but no luck. :(

**Comment by prasanna532** [comment]
@sai-pop 
I have found the some solution for that which is working fine for me try this once.

MobileElement el1 = (MobileElement) driver.findEelementById("test").click();

Use MobileElement instead of the WebEelement.

**Comment by mykola-mokhnach** [comment]
Closed as inactive
