### ISSUE TITLE
Getting java.lang.NoSuchMethodError: com.google.common.base.Throwables.throwIfUnchecked(Ljava/lang/Throwable;)V when creating AndroidDriver class

### ISSUE THREAD

**Issue by satgh12** [appium/appium#10658]
## The problem

Getting java.lang.NoSuchMethodError: com.google.common.base.Throwables.throwIfUnchecked(Ljava/lang/Throwable;)V when creating AndroidDriver class

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1 server, 5.0.4 - client
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac 10.13.4
* Node.js version (unless using Appium.app|exe): 6.11.4
* Mobile platform/version under test: Android 4.4
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: CLI

## Details

Getting the below error when invoking AppiumDriver<MobileElement> driver = new AndroidDriver<MobileElement>(new URL("http://localhost:4910/wd/hub"), capabilities);

java.lang.NoSuchMethodError: com.google.common.base.Throwables.throwIfUnchecked(Ljava/lang/Throwable;)V
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:103)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:586)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:217)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:140)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:83)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:93)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:72)
	at com.smarttech.testcases.TestBase.getKappIQDriver(TestBase.java:415)
	at com.smarttech.testcases.KappIQSetupTest.setupKappIQ(KappIQSetupTest.java:154)

## Link to Appium logs

No appium logs formed yet when this error occurred.

## Code To Reproduce Issue [ Good To Have ]

DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability("autoLaunch", false);
            capabilities.setCapability(AndroidMobileCapabilityType.APP_PACKAGE, "packgae_name");
            capabilities.setCapability(AndroidMobileCapabilityType.APP_ACTIVITY, ".CalibrationUIActivity");
            capabilities.setCapability(AndroidMobileCapabilityType.APP_WAIT_ACTIVITY, ".CalibrationUIActivity");
            capabilities.setCapability(AndroidMobileCapabilityType.INTENT_ACTION, "intent action");
AppiumDriver<MobileElement> driver = new AndroidDriver<MobileElement>(new URL("http://localhost:4910/wd/hub"), capabilities);
        driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);

pom.xml
=======

<build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.18.1</version>
                <configuration>
                    <properties>
                        <property>
                            <name>usedefaultlisteners</name>
                            <value>false</value>
                        </property>
                        <property>
                            <name>listener</name>
                            <value>org.uncommons.reportng.HTMLReporter, org.uncommons.reportng.JUnitXMLReporter</value>
                        </property>
                    </properties>
                    <systemProperties>
                        <property>
                            <name>org.uncommons.reportng.title</name>
                            <value>foo</value>
                        </property>
                    </systemProperties>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.3</version>
                <configuration>
                    <source>1.7</source>
                    <target>1.7</target>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>org.simpleframework</groupId>
            <artifactId>simple-xml</artifactId>
            <version>2.7.1</version>
        </dependency>
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>6.9.10</version>
        </dependency>
        <dependency>
            <groupId>io.appium</groupId>
            <artifactId>java-client</artifactId>
            <version>5.0.4</version>
        </dependency>
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20141113</version>
        </dependency>
        <dependency>
            <groupId>org.uncommons</groupId>
            <artifactId>reportng</artifactId>
            <version>1.1.4</version>
            <exclusions>
                <exclusion>
                    <groupId>org.testng</groupId>
                    <artifactId>testng</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.google.inject</groupId>
            <artifactId>guice</artifactId>
            <version>4.0</version>
            <scope>test</scope>
        </dependency>
        
        <dependency>
            <groupId>jcifs</groupId>
            <artifactId>jcifs</artifactId>
            <version>1.3.17</version>
        </dependency>
    </dependencies>

**Comment by satgh12** [comment]
Resolved this issue by adding the new guava dependency

<dependency>
            <groupId>io.appium</groupId>
            <artifactId>java-client</artifactId>
            <version>5.0.4</version>
            <exclusions>
                <exclusion>
                    <groupId>com.google.guava</groupId>
                    <artifactId>guava</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>21.0</version>
        </dependency>
