### ISSUE TITLE
Process didn't end after 180000ms  when Capturing performance data for native app

### ISSUE THREAD

**Issue by Kitty2014** [appium/appium#10652]
Hello,
I am trying to capturing performance data for native app, Can you please take a look at this and tell me what I am doing wrong. Thank you :)

My environment:
Appium 1.8.0
Mac :10.13.5 Beta (17F59b)
Eclipse:Version: Oxygen.1a Release (4.7.1a)
iOS :11.3.1
Node :v9.4.0

[{"preventWDAAttachments":true,"simpleIsVisibleCheck":true,"noReset":true,"clearSystemFiles":true,"xcodeOrgId":"9H4SUA4596","bundleId":"com.autounion.usedcar","deviceName":"iPhone","launchTimeout":60000,"xcodeSigningId":"iPhone Developer","wdaLocalPort":3301,"logTimestamp":true,"newCommandTimeout":0,"automationName":"XCUITest","useNewWDA":true,"platformName":"iOS","udid":"6b5dc9ce1d3846893ff756459eb2b7133938bbcb"},{},[{"desiredCapabilities":{"preventWDAAttachments":true,"simpleIsVisibleCheck":true,"noReset":true,"clearSystemFiles":true,"xcodeOrgId":"9H4SUA4596","bundleId":"com.autounion.usedcar","deviceName":"iPhone","launchTimeout":60000,"xcodeSigningId":"iPhone Developer","wdaLocalPort":3301,"logTimestamp":true,"newCommandTimeout":0,"automationName":"XCUITest","useNewWDA":true,"platformName":"iOS","udid":"6b5dc9ce1d3846893ff756459eb2b7133938bbcb"}},{"requiredCapabilities":{}}]]

My Code:
 @Test
    public void Profiler() throws Exception {
        //Appium服务端必须以 --relaxed-security启动
    	    String time = new SimpleDateFormat("yyyy年MM月dd日 hh时mm分ss秒SSS毫秒").format(new Date());
         String perfLocation = System.getProperty("user.dir") + "/logs/";
         if (!(new File(perfLocation).isDirectory())) { // 判断是否存在该目录
				System.out.println("当前目录全文路径   "+perfLocation);
				new File(perfLocation).mkdir();
			}
         String filename = perfLocation +"当前性能收集数据__"+ time + ".zip";
        traceZip = new File(filename);
      
            HashMap<String, Object> args = new HashMap<>();
            args.put("timeout", 60000);
            args.put("pid", "current");
            args.put("profileName", "Time Profiler");
            driver.executeScript("mobile: startPerfRecord", args);
            test_1101_XZJG();
            args = new HashMap<>();
            args.put("profileName", "Time Profiler");
            String b64Zip = (String)driver.executeScript("mobile: stopPerfRecord", args);
            byte[] bytesZip = Base64.getMimeDecoder().decode(b64Zip);
            FileOutputStream stream = new FileOutputStream(traceZip);
            stream.write(bytesZip);
        
    }

Error note:

2018-05-07 10:32:33:300 - [HTTP] {"script":"mobile: stopPerfRecord","args":[{"profileName":"Time Profiler"}]}
2018-05-07 10:32:33:300 - [debug] [MJSONWP] Calling AppiumDriver.execute() with args: ["mobile: stopPerfRecord",[{"profileName":"Time Profiler"}],"c180f991-19d9-4f60-89e4-efae800cab60"]
2018-05-07 10:32:33:301 - [debug] [XCUITest] Executing command 'execute'
2018-05-07 10:32:33:301 - [debug] [XCUITest] Sending SIGINT to the running instruments process
2018-05-07 10:33:02:292 - [debug] [XCUITest] Connection to WDA timed out
2018-05-07 10:33:02:293 - [debug] [iProxy] recv failed: Operation not permitted
2018-05-07 10:34:33:300 - [HTTP] <-- POST /wd/hub/session/c180f991-19d9-4f60-89e4-efae800cab60/execute - - ms - -
2018-05-07 10:34:33:300 - [HTTP] 
2018-05-07 10:34:35:304 - [HTTP] --> POST /wd/hub/session/c180f991-19d9-4f60-89e4-efae800cab60/execute
2018-05-07 10:34:35:304 - [HTTP] {"script":"mobile: stopPerfRecord","args":[{"profileName":"Time Profiler"}]}
2018-05-07 10:34:35:304 - [debug] [MJSONWP] Calling AppiumDriver.execute() with args: ["mobile: stopPerfRecord",[{"profileName":"Time Profiler"}],"c180f991-19d9-4f60-89e4-efae800cab60"]
2018-05-07 10:34:35:305 - [debug] [XCUITest] Executing command 'execute'
2018-05-07 10:35:33:299 - [debug] [XCUITest] Sending SIGINT to the running instruments process
2018-05-07 10:35:33:300 - [MJSONWP] Encountered internal error running command: Error: Process didn't end after 180000ms
2018-05-07 10:35:33:300 - [MJSONWP]     at Timeout._onTimeout (/usr/local/lib/node_modules/appium/node_modules/teen_process/lib/teen_process.js:299:16)
2018-05-07 10:35:33:301 - [MJSONWP]     at ontimeout (timers.js:458:11)
2018-05-07 10:35:33:301 - [MJSONWP]     at tryOnTimeout (timers.js:296:5)
2018-05-07 10:35:33:301 - [MJSONWP]     at Timer.listOnTimeout (timers.js:259:5)
2018-05-07 10:38:33:294 - [MJSONWP] Encountered internal error running command: Error: Process didn't end after 180000ms
2018-05-07 10:38:33:294 - [MJSONWP]     at Timeout._onTimeout (/usr/local/lib/node_modules/appium/node_modules/teen_process/lib/teen_process.js:299:16)
2018-05-07 10:38:33:294 - [MJSONWP]     at ontimeout (timers.js:458:11)
2018-05-07 10:38:33:294 - [MJSONWP]     at tryOnTimeout (timers.js:296:5)
2018-05-07 10:38:33:294 - [MJSONWP]     at Timer.listOnTimeout (timers.js:259:5)
2018-05-07 10:38:33:295 - [HTTP] <-- POST /wd/hub/session/c180f991-19d9-4f60-89e4-efae800cab60/execute 500 238001 ms - 204
2018-05-07 10:38:33:295 - [HTTP] 
2018-05-07 10:38:33:306 - [HTTP] --> POST /wd/hub/session/c180f991-19d9-4f60-89e4-efae800cab60/appium/app/close
2018-05-07 10:38:33:306 - [HTTP] {}

**Comment by Kitty2014** [comment]
sometimes pops in appium server ：

2018-05-07 10:50:26:491 - [HTTP] {"script":"mobile: stopPerfRecord","args":[{"profileName":"Time Profiler"}]}
2018-05-07 10:50:26:491 - [debug] [MJSONWP] Calling AppiumDriver.execute() with args: ["mobile: stopPerfRecord",[{"profileName":"Time Profiler"}],"59c89ec7-2e9b-4973-9c36-21f56969adb1"]
2018-05-07 10:50:26:492 - [debug] [XCUITest] Executing command 'execute'
2018-05-07 10:50:26:492 - [debug] [XCUITest] Sending SIGINT to the running instruments process
2018-05-07 10:50:55:453 - [debug] [XCUITest] Connection to WDA timed out
2018-05-07 10:50:55:453 - [debug] [iProxy] recv failed: Operation not permitted

**Comment by mykola-mokhnach** [comment]
> 2018-05-07 10:50:55:453 - [debug] [XCUITest] Connection to WDA timed out

The WDA server just stops responding while the test is running. Try to figure out why.

**Comment by Kitty2014** [comment]
@mykola-mokhnach  WDA work 👌  but sometimes this error occur  during stop record
2018-05-07 10:34:35:304 - [HTTP] {"script":"mobile: stopPerfRecord","args":[{"profileName":"Time Profiler"}]}

**Comment by Kitty2014** [comment]
I  will add the  Xcode service information this afternoon  for
 you tracking

**Comment by Kitty2014** [comment]
@mykola-mokhnach  after update My Mac to 10.13.5 Beta (17F66a)  cannot reproduce
