### ISSUE TITLE
It isn't possible to specify a path in the client's filesystem in chromedriverExecutable Android capability

### ISSUE THREAD

**Issue by ovenal** [appium/appium#10651]
## The problem

There is a remote Appium server that I can't manage. I would like to run the tests for Android (on different phones with different Android versions) and there is a problem with chromedriver and Chrome compatibility. In order to avoid it there are "chromedriverExecutable" and "chromedriverExecutableDir" Android capabilities.
Unfortunately it looks like Appium expects that provided path to chromedriver should be in the local filesystem of a machine where Appium server is running. So the client can't manage what chromedriver version should be used without reconfiguration of Appium server.

I don't know if current behavior is the expected one or it's a bug. 
Anyway it would be nice to have a possibility to specify chromedriver path in the filesystem on the client side, so Appium server can take and use it for the tests execution (like it works for apk-file which is located in the client filesystem).

## Environment

* Appium version: 1.7.2
* OS/version: Win10:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android (all)
* Real device or emulator/simulator: both
* Appium CLI or Appium.app|exe: AppiumDesktop

## Details

When the client connects to the Appium server with "chromedriverExecutable" capability that contains a path to chromedriver.exe in the local filesystem, Appium can't start a session and fails with the message:
```
 Error: Trying to use a chromedriver binary at the path C:\Program Files (x86)\chromedriver_2_24.exe, but it doesn't exist!
    at Chromedriver.initChromedriverPath$ (C:\Users\oleksiy.gruba\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-chromedriver\lib\chromedriver.js:39:13)
    at tryCatch (C:\Users\oleksiy.gruba\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\oleksiy.gruba\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\oleksiy.gruba\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\oleksiy.gruba\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at 
```

## Link to Appium logs

https://gist.github.com/ovenal/273d4ae5dba013f69397bc6189b9449a

**Comment by mykola-mokhnach** [comment]
This should be supported on both client and server sides.

**Comment by mykola-mokhnach** [comment]
This might be a potential security hole, since the binary is executed by appium after being pushed to the server and there is no good way to verify the binary is "true". For now, the other feature for automatic chromedrivers download has been been implemented though
