### ISSUE TITLE
Unable to switch from native app context to WEBVIEW context

### ISSUE THREAD

**Issue by mdelgadoAxa** [appium/appium#10663]
## The problem

Unable to switch from native app context to WEBVIEW context.

## Environment

* Appium version: 1.8.0-beta5
* Desktop OS/version used to run Appium:  MAC OS Sieraa 10.13.3
* Node.js version: 5.6.0
* Mobile platform/version under test: Android 8.0 Api 26
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: 6.0.0-BETA5

## Link to Appium logs

Create a [GIST](https://gist.github.com/mdelgadoAxa/89795d1b6a784a142e4f7a87e61d77f5).

**Comment by mykola-mokhnach** [comment]
Are able to see the webview in the chrome remote debugger? Have you tried different versions of chrome driver?

**Comment by mdelgadoAxa** [comment]
Hello @mykola-mokhnach indeed im able to see the webview 
![Chrome remote debugger](https://user-images.githubusercontent.com/37302551/39747907-e9a13d74-52ae-11e8-9b02-e0107a9ad1e2.png). Also i tried with different chromedriver versions from 2.30 to 2.37.

**Comment by mykola-mokhnach** [comment]
I assume it is some internal problem in the chrome driver itself. Attach the logcat output. Perhaps it contains some useful more useful info.

**Comment by mykola-mokhnach** [comment]
Also try to change the debugging port. Maybe, there is conflict.

**Comment by mdelgadoAxa** [comment]
@mykola-mokhnach here is the [logcat](https://gist.github.com/mdelgadoAxa/3e357ab4e638d5e584255a7f613d7d98). I'll try changing debugging port

**Comment by mdelgadoAxa** [comment]
Maybe not i run the command line `adb logcat > logcat.txt` and i get that.

**Comment by mykola-mokhnach** [comment]
the output should be collected while the script is trying to connect to the web view

**Comment by mdelgadoAxa** [comment]
@mykola-mokhnach as you can see in line 14 the WebView is initialize [logcat](https://gist.github.com/mdelgadoAxa/8a06f9793689aa6411e3f6745510a1fb).

**Comment by mykola-mokhnach** [comment]
> /system/bin/webview_zygote32: failed to make and chown /acct/uid_99021: Permission denied
I don't like this line, but there is not much one can do on Appium side. I'd try to describe the issue on chromedriver bugs tracker.

**Comment by liviudanu-ellation** [comment]
@mykola-mokhnach, I guess this is a bug introduced to 1.8.0 with `Automatically choose compatible Chromedriver for Chrome version` feature.  Currently I am facing a similar issue on Galaxy S7 device.
The Chrome version there is 68.X.X, but appium detects it as 58 (I see the same message in the logs provided by @mdelgadoAxa ) and appium cant switch contexts.

@mykola-mokhnach , can you take a look into this? Ping me if you may need my logs, Thank you.

**Comment by mykola-mokhnach** [comment]
@imurchie knows more about it.

You could also try appium@beta to check if there are some fixes there.

**Comment by vjmaiky** [comment]
Using appium 1.8.1 and java library 6.0.0 i'm getting an exception when running get context command:
Same piece of code worked perfectly on 1.8.0-beta 3 and java library 6 beta 5.

```
org.openqa.selenium.WebDriverException: java.io.IOException: unexpected end of stream on Connection{0.0.0.0:1024, proxy=DIRECT hostAddress=/0.0.0.0:1024 cipherSuite=none protocol=http/1.1}
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'EN610847.local', ip: '172.16.118.35', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.4', java.version: '1.8.0_144'
Driver info: driver.version: AppiumDriver
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:233)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:46)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at io.appium.java_client.AppiumDriver.getContextHandles(AppiumDriver.java:206)
	at core.helpers.ContextHandler.getContextHandles(ContextHandler.java:15)
	at core.helpers.ContextHandler.switchToWebview(ContextHandler.java:49)
	at api.apps.inflightiOS.paymentView.PaymentView.purchaseWithCreditCard(PaymentView.java:217)
	at tests.loggedUser.MobileTestSet_10_ConnectView.Test001(MobileTestSet_10_ConnectView.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at core.watchers.Retry$1.evaluate(Retry.java:28)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.io.IOException: unexpected end of stream on Connection{0.0.0.0:1024, proxy=DIRECT hostAddress=/0.0.0.0:1024 cipherSuite=none protocol=http/1.1}
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:208)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:105)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:155)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:218)
	... 37 more
Caused by: java.io.EOFException: \n not found: limit=0 content=…
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:237)
	at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:215)
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
	... 55 more

```

**Comment by mykola-mokhnach** [comment]
@vjmaiky Such error is thrown by okhttp lib if the connection to the server is unexpectedly interrupted: https://github.com/square/okhttp/issues/2738

**Comment by vjmaiky** [comment]
is there any way to workaround it?

**Comment by sumio** [comment]
@mykola-mokhnach @liviudanu-ellation 
I'm also facing with the issue on my Nexus6 device.

As far as I investigated, `com.google.android.webview` is _disabled_ on Nexus 6 device and `com.android.chrome` is used as `WebView` instead.
In Android OS, disabled package has a `versionName` _at a time of factory shipment_ which is usually too old.

[Current implementation of appium-chromedriver](https://github.com/appium/appium-chromedriver/blob/master/lib/chromedriver.js#L156-L167) detects the installed version of `WebView` as the following manner:

1. if `com.google.android.webview` or `com.android.webview` is installed, adopt its version.
2. if `com.android.chrome` is installed, adopt its version.

The above detection logic doesn't care if the package is disabled or not.
So, Appium detects wrong version number of webview package which is disabled.

I suggest that the detection logic become to exclude disabled packages.
`adb shell pm list packages -d` which shows disabled packages may help.

**Comment by sumio** [comment]
@mykola-mokhnach @liviudanu-ellation 
I found a quick workaround.
Put the following settings into the desired capabilities:

```
        chromeBundleId: 'com.android.chrome',
```

**Comment by mykola-mokhnach** [comment]
@sumio Thanks for the investigation
@imurchie ping
