### ISSUE TITLE
Not able to scroll to particular element in appium 1.7.1 server

### ISSUE THREAD

**Issue by sjdptn** [appium/appium#10677]
Not able to scroll to particular element:

Used the following code:
			WebElement Object1= driver.findElement(By.xpath("//*[@label=\"No\"]"));
			  JavascriptExecutor js = (JavascriptExecutor) driver;
			    HashMap scrollObject = new HashMap();
			    scrollObject.put("direction", "down");
			    scrollObject.put("name", "Object1");
			    js.executeScript("mobile: scroll", scrollObject);

Also the further specifictions mentioned below:

Appium server : 1.7.1 (appium desktop)
Eclipse Oxygen 2 IDE 
code : Java
OS : Mac OS

Error in console:
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: An unknown server-side error occurred while processing the command. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T15:28:36.4Z'
System info: host: 'ef3582c8c520', ip: '172.18.0.4', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-47-generic', java.version: '1.8.0_131'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{reportPdfUrl=https://ibmgbs.reporting.perfectomobile.com/export/api/v1/test-executions/pdf?externalId[0]=sajpatan@in.ibm.com_RemoteWebDriver_18-05-10_09_21_19_6248&_timestamp[0]=1525944079281, simpleIsVisibleCheck=true, deviceName=625BC022B6B1EF70FFB14354E2698561500B4748, platform=ANY, password=, deviceSessionId=sajpatan@in.ibm.com_RemoteWebDriver_18-05-10_09_21_19_6248, webStorageEnabled=false, automationName=XCUITest, host=ibmgbs.perfectomobile.com, singleTestReportUrl=https://ibmgbs.reporting.perfectomobile.com?externalId[0]=sajpatan@in.ibm.com_RemoteWebDriver_18-05-10_09_21_19_6248&_timestamp[0]=1525944079281, browserName=, takesScreenshot=true, javascriptEnabled=true, platformName=ANY, networkConnectionEnabled=false, testGridReportUrl=https://ibmgbs.reporting.perfectomobile.com?externalId[0]=sajpatan@in.ibm.com_RemoteWebDriver_18-05-10_09_21_19_6248&_timestamp[0]=1525944079281, entityType=appium_driver, xcuitestFindOptimizations=true, bundleId=com.stopandshop.mobile.beta, databaseEnabled=false, version=, serverConnector=, serverHost=1.1.80.34:11603, securityToken=, executionId=sajpatan@in.ibm.com_RemoteWebDriver_18-05-10_09_21_19_6248, autoLaunch=true, locationContextEnabled=false, scriptName=RemoteWebDriver, reportKey=sajpatan@in.ibm.com_RemoteWebDriver_18-05-10_09_21_19_6248, windTunnelReportUrl=https://ibmgbs.reporting.perfectomobile.com?externalId[0]=sajpatan@in.ibm.com_RemoteWebDriver_18-05-10_09_21_19_6248&_timestamp[0]=1525944079281, user=}]
Session ID: c64e21d2-e066-4209-a35f-e26bbc1dac8e
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'macbook-air.in.ibm.com', ip: 'fe80:0:0:0:ce5:58b7:2ceb:4ae3%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.3', java.version: '1.8.0_151'
Driver info: driver.version: RemoteWebDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:82)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:45)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:89)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:586)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:522)
	at com.perfectomobile.selenium.server.appium.AppiumDriverWrapper$17.call(AppiumDriverWrapper.java:515)
	at com.nexperience.function.execute.ExecuteCallableCommand.process(ExecuteCallableCommand.java:30)
	at com.nexperience.engine.script.command.AbstractScriptCommand.doExecute(AbstractScriptCommand.java:173)
	at com.nexperience.engine.script.command.ScriptCommandBase.execute(ScriptCommandBase.java:107)
	at com.nexperience.engine.script.tcl.event.CommandTclEvent.processEvent(CommandTclEvent.java:43)
	at com.nexperience.engine.script.tcl.event.MaseTclEvent.processEvent(MaseTclEvent.java:56)
	at tcl.lang.Notifier.serviceEvent(Notifier.java:457)
	at tcl.lang.Notifier.doOneEvent(Notifier.java:610)
	at tcl.lang.Notifier.processTclEvents(Notifier.java:786)
	at com.nexperience.engine.script.tcl.event.TclEventProcessor.start(TclEventProcessor.java:78)
	at com.nexperience.engine.script.tcl.TclInterpreter.startEventProcessing(TclInterpreter.java:550)
	at com.nexperience.engine.script.execution.step.StepExecutionEventProcessor.callImpl(StepExecutionEventProcessor.java:85)
	at com.nexperience.engine.script.execution.step.StepExecutionEventProcessor.callImpl(StepExecutionEventProcessor.java:21)
	at com.nexperience.util.thread.WrappedCallable.call(WrappedCallable.java:31)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

===============================================
    Default test
    Tests run: 1, Failures: 1, Skips: 0
===============================================

===============================================
Default suite
Total tests run: 1, Failures: 1, Skips: 0
===============================================

**Comment by mykola-mokhnach** [comment]
```
```

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios/ios-xctest-mobile-gestures.md
