### ISSUE TITLE
Unable to locate elements with special characters($) in their locator values

### ISSUE THREAD

**Issue by Gocoollnath** [appium/appium#10681]
## The problem

Unable to locate elements with special characters($) in their locator values

## Environment

Appium version 1.8.0
Desktop OS/version used to run Appium: Windows 10 Pro
Node.js version (unless using Appium.app|exe): 8.10.0
Mobile platform/version under test: Android API 25 ,v7.1.1
Real device or emulator/simulator: Real Device Samsung Tab
Appium CLI or Appium.app|exe: both

## Ecxeption stacktraces

May 10, 2018 6:27:58 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
md52da4fc008d6b8a11b2105cb85a17be71.LoginView
Select Vehicle screen is displayed
ABC 123
Exception in thread "main" org.openqa.selenium.WebDriverException: Returned value cannot be converted to WebElement: {stacktrace=InvalidSelectorError: Argument was an invalid selector (e.g. XPath/CSS).
    at errorFromMJSONWPStatusCode (C:\Users\gokulnath.kumar\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:769:12)
    at Socket.<anonymous> (C:\Users\gokulnath.kumar\AppData\Roaming\npm\node_modules\appium\node_modules\appium-android-bootstrap\lib\bootstrap.js:129:18)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:246:13)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:607:20), error=invalid selector, message=Argument was an invalid selector (e.g. XPath/CSS).}
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:33:08.638Z'
System info: host: 'IN-GOKUL-D', ip: '172.22.237.81', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '10'
Driver info: driver.version: AndroidDriver
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:326)
	at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:62)
	at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.findElement(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:421)
	at io.appium.java_client.DefaultGenericMobileDriver.findElementByXPath(DefaultGenericMobileDriver.java:140)
	at io.appium.java_client.AppiumDriver.findElementByXPath(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.findElementByXPath(AndroidDriver.java:1)
	at sign_in.signing.main(signing.java:75)
Caused by: java.lang.ClassCastException: com.google.common.collect.Maps$TransformedEntriesMap cannot be cast to org.openqa.selenium.WebElement
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:324)
	... 8 more

## Link to Appium logs

https://gist.github.com/Gocoollnath/18375636f56469faedea7593f454c43f

## Code To Reproduce Issue [ Good To Have ]

driver.findElementByXPath("(//android.app.ActionBar$Tab)[2]").click();

**Comment by mykola-mokhnach** [comment]
1. You're trying to use an outdated client with newer Appium release. 
2. The xpath expression containing `$` sign has incorrect syntax and cannot be parsed. Did you check the actual page source output before constructing the locator?
3. It is recommended to use UiAutomator2 backend for Android 6+

**Comment by Gocoollnath** [comment]
The special character is in Class name for the element and i need second one in the screen to be clicked. Even with driver.FindElementByClassName("android.app.ActionBar$Tab").Click() doesn't work, when i need to click the first one. Can you please share  the latest version of the client?

![special character](https://user-images.githubusercontent.com/39054531/39874099-76f72da0-548a-11e8-9122-335392786163.png)

**Comment by mykola-mokhnach** [comment]
I won't be able to help unless you use UIA1. It's outdated and is not supported by Goodle itself.

**Comment by Gocoollnath** [comment]
Using UIAutomator2 getting same error. Please find the stack trace in the link below
https://gist.github.com/Gocoollnath/9971090318385e0a2804172ded07a53d

**Comment by liviudanu-ellation** [comment]
@Gocoollnath, if xpath does not work, use UiSelector instead.

**Comment by mykola-mokhnach** [comment]
Use the value of `className` property rather than the node name itself to locate the element .

**Comment by Gocoollnath** [comment]
tried with driver.findElement(MobileBy.AndroidUIAutomator("new UiSelector().className(\"android.app.ActionBar$Tab\").instance(1)")).click();. Same error

**Comment by dpgraham** [comment]
Also, @Gocoollnath are you using the latest beta of the Java client?

**Comment by dpgraham** [comment]
https://github.com/appium/appium-base-driver/pull/211

**Comment by Gocoollnath** [comment]
Actual class name was android.app.ActionBar.Tab. The dot before tab gets changed to $. Don't know why it's happening. App is developed on xamarain framework. 

@dpgraham I use Java client 5.2

**Comment by dpgraham** [comment]
Try I don't know why either @Gocoollnath but it's not something we can change. The class name is something that is reported to us by UIAutomator2 and if that's reporting a class name with an illegal Xpath character, that element can't be referenced by Xpath (see https://stackoverflow.com/questions/27060726/escape-a-dollar-sign-in-selenium-xpath-locator)

What I recommend is coming up with a new selector to spot the element. You can probably reconfigure the Xpath selector somehow.
