### ISSUE TITLE
Appium server error "Original error: Invalid Version: lib64"

### ISSUE THREAD

**Issue by Elmue** [appium/appium#10697]
I have installed Appium server on Windows 7 (64 bit) as described in this video:
https://www.youtube.com/watch?v=-GJTzPOIoqs

I have installed:
- Appium-Desktop 1.72
- Java jdk1.8.0_171 (64 bit)
- Android SDK tools version 25 (latest version)
- Android SDK Platform tools version 27 (latest version)
- Android SDK Build tools version 27 (latest version)
- Android 5.1.1 (which is the same version as on my smartphone)

I have set the environment variables JAVA_HOME and ANDROID_HOME as described in the video.
I have appended to the PATH variable: 
%JAVA_HOME%\bin;%ANDROID_HOME%\tools;%ANDROID_HOME%\platform-tools; 
as described in the video.

When I start the Appium server there is no error.
But when my Appium client application connects to the Appium server (in RemoteWebDriver.StartSession) I get this error:

**"An unknown server-side error occurred while processing the command. Original error: Invalid Version: lib64"**

What the heck does this mean?
Why is Appium not able to give understandable and intelligent error messages?

This is the log:

[info] [Appium] Creating new AndroidDriver (v1.37.0) session
[info] [Appium] Capabilities:
[info] [Appium]   newCommandTimeout: 20
[info] [Appium]   appPackage: com.android.settings
[info] [Appium]   deviceName: SM_J111M
[info] [Appium]   platformName: Android
[info] [BaseDriver] Session created with session id: e4039c74-c521-4258-b982-336d2c83ccfc
[debug] [AndroidDriver] Getting Java version[info] [AndroidDriver] Java version is: 1.8.0_111
[info] [ADB] Checking whether adb is present
[debug] [AndroidDriver] Shutting down Android driver
[debug] [AndroidDriver] Called deleteSession but bootstrap wasn't active
[error] [MJSONWP] Encountered internal error running command: TypeError: Invalid Version: lib64
    at new SemVer (E:\Temp\appium-desktop\app-1.5.0\resources\app\node_modules\appium\node_modules\semver\semver.js:293:11)
    at compare (E:\Temp\appium-desktop\app-1.5.0\resources\app\node_modules\appium\node_modules\semver\semver.js:566:10)
    at rcompare (E:\Temp\appium-desktop\app-1.5.0\resources\app\node_modules\appium\node_modules\semver\semver.js:576:10)
    at Array.sort (native)
    at Array.sort (E:\Temp\appium-desktop\app-1.5.0\resources\app\webpack:\~\core-js\modules\es6.array.sort.js:21:1)
    at ADB.callee$0$0$ (E:\Temp\appium-desktop\app-1.5.0\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:89:17)
    at tryCatch (E:\Temp\appium-desktop\app-1.5.0\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (E:\Temp\appium-desktop\app-1.5.0\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (E:\Temp\appium-desktop\app-1.5.0\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (E:\Temp\appium-desktop\app-1.5.0\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at <anonymous>
[info] [HTTP] <-- POST /wd/hub/session 500 206 ms - 159

**Comment by Elmue** [comment]
I found the reason. Although I had set the environment variable ANDROID_HOME correctly after the next reboot it had the old value again. Very strange. I fixed that and now it works.
