### ISSUE TITLE
Appium Desktop 1.6.1 & Appium server 1.8.0 - org.openqa.selenium.WebDriverException: org.openqa.selenium.WebDriverException: Returned value cannot be converted to WebElement for MobileElement on @FindBy

### ISSUE THREAD

**Issue by tlytvyn** [appium/appium#10715]
## The problem
When I am executing Android tests I am getting this issue on @AndroidFindBy MobileElement search:

@AndroidFindBy(xpath = "//*[contains(@resource-id, 'permission_allow_button')]")
private MobileElement allowLocationButton;

```
org.openqa.selenium.WebDriverException: org.openqa.selenium.WebDriverException: Returned value cannot be converted to WebElement: {error=no such element, message=An element could not be located on the page using the given search parameters., stacktrace=NoSuchElementError: An element could not be located on the page using the given search parameters.
    at AndroidDriver.callee$0$0$ (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/lib/commands/find.js:69:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)}
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'administrator’s-MacBook-Pro', ip: 'fe80:0:0:0:1015:5ce1:dee:b047%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.3', java.version: '1.8.0_102'
Driver info: driver.version: AndroidDriver
	at io.appium.java_client.pagefactory.AppiumElementLocator$WaitingFunction.apply(AppiumElementLocator.java:214)
	at io.appium.java_client.pagefactory.AppiumElementLocator$WaitingFunction.apply(AppiumElementLocator.java:1)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:248)
	at io.appium.java_client.pagefactory.AppiumElementLocator.waitFor(AppiumElementLocator.java:121)
	at io.appium.java_client.pagefactory.AppiumElementLocator.findElement(AppiumElementLocator.java:141)
```

## Environment
- I am running Appium Desktop version _1.6.1_.
- I am on (pick one):
    - [ ] Mac

**Comment by imurchie** [comment]
The element is not being found. What client is this? It ought to be interpreting this as an error rather than a returned element.

**Comment by mykola-mokhnach** [comment]
the problem with incorrect exception has been fixed in appium@beta (https://github.com/appium/appium-base-driver/pull/211).

**Comment by tlytvyn** [comment]
@mykola-mokhnach @imurchie the problem is that "Returned value cannot be converted to WebElement" - when I am switching to 1.7 server everything works fine and MobileElement is instantiated

**Comment by tlytvyn** [comment]
@mykola-mokhnach @imurchie I have checked - simple findElement(By. ... ) is not working with 1.8 server version, Java client 6.0.0-BETA5 - Caused by: java.lang.ClassCastException: com.google.common.collect.Maps$TransformedEntriesMap cannot be cast to org.openqa.selenium.WebElement

**Comment by narendra-chandratre** [comment]
Did you push the fix for same issue?? I have observed "java.lang.ClassCastException"
