### ISSUE TITLE
Error: No open port found

### ISSUE THREAD

**Issue by risgo** [appium/appium#10716]
## The problem

I'm running some tests, parallelly with 5 devices at a time. After a few hours, Appium randomly starts throwing "No open port found" errors continuosly which are not resolved until adb & appium are killed or wire to cable is reconnected. The devices are still responsive on machines while this error happens.  

## Environment

* 1.8.0 
* Windows(7) & Mac(10.13.2)
* Node.js version : v8.11.1
* 7.0 & 7.1
* Real device : Moto G5 Plus & Moto G4 Plus
* Appium CLI, Appium.app & Appium.exe 

## Link to Appium logs

 `org.openqa.selenium.WebDriverException: An unknown server-side error occurred wh
ile processing the command. Original error: No open port found
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'Admin-PC', ip: '169.254.121.42', os.name: 'Windows 7', os.a
rch: 'amd64', os.version: '6.1', java.version: '10'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while pro
cessing the command. Original error: No open port found
    at getResponseForW3CError (C:\Users\Admin\AppData\Roaming\npm\node_modules\
appium\node_modules\appium-base-driver\lib\protocol\errors.js:800:13)
    at asyncHandler$ (C:\Users\Admin\AppData\Roaming\npm\node_modules\appium\no
de_modules\appium-base-driver\lib\protocol\protocol.js:352:37)
    at tryCatch (C:\Users\Admin\AppData\Roaming\npm\node_modules\appium\node_mo
dules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\Admin\AppData\R
oaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js
:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\U
sers\Admin\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\r
egenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\Admin\AppData\Roaming\npm\no
de_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at <anonymous>
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInsta
nce0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInsta
nce(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newI
nstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:
488)
        at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHands
hakeResponse.java:57)
        at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFun
ction$2(W3CHandshakeResponse.java:104)
        at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(P
rotocolHandshake.java:123)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipe
line.java:195)
        at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Splitera
tors.java:958)
        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(Refere
ncePipeline.java:127)
        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(Abstra
ctPipeline.java:502)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline
.java:488)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractP
ipeline.java:474)
        at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.
java:150)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline
.java:234)
        at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipel
ine.java:543)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHa
ndshake.java:126)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHa
ndshake.java:73)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExe
cutor.java:136)
        at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumComm
andExecutor.java:129)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.ja
va:545)
        at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGener
icMobileDriver.java:42)
        at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
        at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.jav
a:1)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriv
er.java:209)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.jav
a:132)
        at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGeneri
cMobileDriver.java:38)
        at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:84)
        at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:94)
        at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java
:80)
        at pospackage.MobileConnection.setUp(MobileConnection.java:159)`

## Code To Reproduce Issue [ Good To Have ]

This happens randomly in hours, thus can't be reproduced quick.

**Comment by mykola-mokhnach** [comment]
I don't think there is something that can be done on appium side. most likely it is a problem with adb itself.
