### ISSUE TITLE
Unable to launch Jabong application 

### ISSUE THREAD

**Issue by SapizonTechnologiesLLP** [appium/appium#10724]
## The problem

Am trying to launch jabong android mobile application no MI note 4 but am unable to launch that application 
## Environment

* Appium version (or git revision) that exhibits the issue: Using Appium desktop application 1.6.1
* Desktop OS/version used to run Appium: Windows 10 pro 
* Node.js version (unless using Appium.app|exe): v8.9.4
* Mobile platform/version under test: redmi note 4 android 7.0 NRD90M
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium exe

## Details
```java
	static String node ="C:\\Program Files\\nodejs\\node.exe";
	static String appiumMain="C:\\Users\\DELL\\AppData\\Local\\Programs\\appium-desktop\\resources\\app\\node_modules\\appium\\build\\lib\\main.js";
	static AppiumDriverLocalService services;
	static SimpleDateFormat df= new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS");
	static String LogFile="C:\\Users\\DELL\\eclipse-workspace\\appium\\Appium.log";
	@BeforeTest
	public void startService()
	{
		services=AppiumDriverLocalService.buildService(new AppiumServiceBuilder()
				.usingDriverExecutable(new File(node))
				.withAppiumJS(new File(appiumMain)).withIPAddress("127.0.0.1")
				.usingPort(4723)
				.withLogFile(new File(LogFile)));
		services.start();
	}
	@Test
	public void test() throws MalformedURLException, InterruptedException {
		
			DesiredCapabilities  cap = new DesiredCapabilities();
			cap.setCapability(MobileCapabilityType.DEVICE_NAME, "android");
			cap.setCapability("appPackage", " com.jabong.android");
			cap.setCapability("appActivity", "com.jabong.android.view.activity.JabongMainActivity");
			driver = new AndroidDriver<AndroidElement>(new URL("http://127.0.0.1:4723/wd/hub"),cap);
			driver.manage().timeouts().implicitlyWait(10l, TimeUnit.SECONDS);
			driver.findElement(By.id("com.divum.MoneyControl")).click();
			driver.findElement(By.id("com.moneycontrol.handheld.HomeActivity")).click();
			
		
	}


	
	@AfterTest
	public void stopService() throws MalformedURLException {
		services.stop();
	}
```

## Link to Appium logs
```
[RemoteTestNG] detected TestNG version 6.13.1
[35m[Appium][39m Welcome to Appium v1.8.0
[35m[Appium][39m Non-default server args:
[35m[Appium][39m   address: 127.0.0.1
[35m[Appium][39m   log: C:\Users\DELL\eclipse-workspace\appium\Appium.log
[35m[Appium][39m Appium REST http interface listener started on 127.0.0.1:4723
[35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/status[39m
[35m[HTTP][39m [90m{}[39m
[debug] [35m[MJSONWP][39m Calling AppiumDriver.getStatus() with args: []
[debug] [35m[MJSONWP][39m Responding to client with driver.getStatus() result: {"build":{"version":"1.8.0","revision":null}}
[35m[HTTP][39m [37m<-- GET /wd/hub/status [39m[32m200[39m [90m11 ms - 83[39m
[35m[HTTP][39m [90m[39m
[35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m
[35m[HTTP][39m [90m{"desiredCapabilities":{"appPackage":" com.jabong.android","appActivity":"com.jabong.android.view.activity.JabongMainActivity","platformName":"Android","deviceName":"android"},"requiredCapabilities":{},"capabilities":{"desiredCapabilities":{"appPackage":" com.jabong.android","appActivity":"com.jabong.android.view.activity.JabongMainActivity","platformName":"Android","deviceName":"android"},"requiredCapabilities":{},"alwaysMatch":{"platformName":"Android"},"firstMatch":[]}}[39m
[debug] [35m[MJSONWP][39m Calling AppiumDriver.createSession() with args: [{"appPackage":" com.jabong.android","appActivity":"com.jabong.android.view.activity.JabongMainActivity","platformName":"Android","deviceName":"android"},{},{"desiredCapabilities":{"appPackage":" com.jabong.android","appActivity":"com.jabong.android.view.activity.JabongMainActivity","platformName":"Android","deviceName":"android"},"requiredCapabilities":{},"alwaysMatch":{"platformName":"Android"},"firstMatch":[]}]
[debug] [35m[BaseDriver][39m Event 'newSessionRequested' logged at 1526895810615 (15:13:30 GMT+0530 (India Standard Time))
[35m[Appium][39m Could not parse W3C capabilities: 'deviceName' can't be blank. Falling back to JSONWP protocol.
[35m[Appium][39m The following capabilities were provided in the JSONWP desired capabilities that are missing in W3C capabilities: ["appPackage","appActivity","platformName","deviceName"]. Falling back to JSONWP protocol.
[35m[Appium][39m Creating new AndroidDriver (v2.6.0) session
[35m[Appium][39m Capabilities:
[35m[Appium][39m   appPackage:  com.jabong.android
[35m[Appium][39m   appActivity: com.jabong.android.view.activity.JabongMainActivity
[35m[Appium][39m   platformName: Android
[35m[Appium][39m   deviceName: android
[debug] [35m[BaseDriver][39m Creating session with MJSONWP desired capabilities: {"appPackage":" com.jabong....
[35m[BaseDriver][39m Session created with session id: dfff6d32-afda-446d-8e74-70c05c8b55e5
[debug] [35m[AndroidDriver][39m Getting Java version
[35m[AndroidDriver][39m Java version is: 1.8.0_161

[35m[ADB][39m Checking whether adb is present
[35m[ADB][39m Found 2 'build-tools' folders under 'C:\Users\DELL\AppData\Local\Android\Sdk' (newest first):
[35m[ADB][39m     C:/Users/DELL/AppData/Local/Android/Sdk/build-tools/27.0.3
[35m[ADB][39m     C:/Users/DELL/AppData/Local/Android/Sdk/build-tools/26.0.2
[35m[ADB][39m Using adb.exe from C:\Users\DELL\AppData\Local\Android\Sdk\platform-tools\adb.exe
[35m[AndroidDriver][39m Retrieving device list
[debug] [35m[ADB][39m Trying to find a connected android device
[debug] [35m[ADB][39m Getting connected devices...
[debug] [35m[ADB][39m 1 device(s) connected
[35m[AndroidDriver][39m Using device: 31caa5790503
[35m[ADB][39m Checking whether adb is present
[35m[ADB][39m Using adb.exe from C:\Users\DELL\AppData\Local\Android\Sdk\platform-tools\adb.exe
[debug] [35m[ADB][39m Setting device id to 31caa5790503
[35m[AndroidDriver][39m Starting Android session
[debug] [35m[ADB][39m Running 'C:\Users\DELL\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 31caa5790503 wait-for-device'
[debug] [35m[ADB][39m Getting connected devices...
[debug] [35m[ADB][39m 1 device(s) connected
[debug] [35m[ADB][39m Running 'C:\Users\DELL\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 31caa5790503 shell echo ping'
[debug] [35m[AndroidDriver][39m Pushing settings apk to device...
[debug] [35m[ADB][39m Getting install status for io.appium.settings
[debug] [35m[ADB][39m Getting connected devices...
[debug] [35m[ADB][39m 1 device(s) connected
[debug] [35m[ADB][39m Running 'C:\Users\DELL\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 31caa5790503 shell pm list packages io.appium.settings'
[debug] [35m[ADB][39m App is installed
[debug] [35m[ADB][39m Getting package info for 'io.appium.settings'
[debug] [35m[ADB][39m Getting connected devices...
[debug] [35m[ADB][39m 1 device(s) connected
[debug] [35m[ADB][39m Running 'C:\Users\DELL\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 31caa5790503 shell dumpsys package io.appium.settings'
[35m[ADB][39m Checking whether aapt is present
[35m[ADB][39m Using aapt.exe from C:\Users\DELL\AppData\Local\Android\Sdk\build-tools\27.0.3\aapt.exe
[debug] [35m[ADB][39m The installed 'io.appium.settings' package does not require upgrade ('2.3.0' >= '2.3.0')
[debug] [35m[ADB][39m Getting connected devices...
[debug] [35m[ADB][39m 1 device(s) connected
[debug] [35m[ADB][39m Running 'C:\Users\DELL\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 31caa5790503 shell ps'
[debug] [35m[AndroidDriver][39m io.appium.settings is already running. There is no need to reset its permissions.
[debug] [35m[ADB][39m Getting connected devices...
[debug] [35m[ADB][39m 1 device(s) connected
[debug] [35m[ADB][39m Running 'C:\Users\DELL\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 31caa5790503 shell getprop ro.build.version.sdk'
[debug] [35m[ADB][39m Current device property 'ro.build.version.sdk': 24
[debug] [35m[ADB][39m Device API level: 24
[debug] [35m[ADB][39m Getting connected devices...
[debug] [35m[ADB][39m 1 device(s) connected
[debug] [35m[ADB][39m Running 'C:\Users\DELL\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 31caa5790503 shell appops set io.appium.settings android\:mock_location allow'
[35m[AndroidDriver][39m setDeviceLanguageCountry requires language or country.
[35m[AndroidDriver][39m Got language: 'null' and country: 'null'
[debug] [35m[Logcat][39m Starting logcat capture
[debug] [35m[AndroidDriver][39m Pushing unlock helper app to device...
[debug] [35m[ADB][39m Getting install status for io.appium.unlock
[debug] [35m[ADB][39m Getting connected devices...
[debug] [35m[ADB][39m 1 device(s) connected
[debug] [35m[ADB][39m Running 'C:\Users\DELL\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 31caa5790503 shell pm list packages io.appium.unlock'
[debug] [35m[ADB][39m App is installed
[debug] [35m[ADB][39m Getting package info for 'io.appium.unlock'
[debug] [35m[ADB][39m Getting connected devices...
[debug] [35m[ADB][39m 1 device(s) connected
[debug] [35m[ADB][39m Running 'C:\Users\DELL\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 31caa5790503 shell dumpsys package io.appium.unlock'
[35m[ADB][39m Checking whether aapt is present
[35m[ADB][39m Using aapt.exe from C:\Users\DELL\AppData\Local\Android\Sdk\build-tools\27.0.3\aapt.exe
[debug] [35m[ADB][39m The installed 'io.appium.unlock' package does not require upgrade ('2.0.0' >= '2.0.0')
[35m[ADB][39m Getting device platform version
[debug] [35m[ADB][39m Getting connected devices...
[debug] [35m[ADB][39m 1 device(s) connected
[debug] [35m[ADB][39m Running 'C:\Users\DELL\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 31caa5790503 shell getprop ro.build.version.release'
[debug] [35m[ADB][39m Current device property 'ro.build.version.release': 7.0
[debug] [35m[ADB][39m Getting connected devices...
[debug] [35m[ADB][39m 1 device(s) connected
[debug] [35m[ADB][39m Running 'C:\Users\DELL\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 31caa5790503 shell wm size'
[debug] [35m[ADB][39m Getting connected devices...
[debug] [35m[ADB][39m 1 device(s) connected
[debug] [35m[ADB][39m Running 'C:\Users\DELL\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 31caa5790503 shell getprop ro.product.model'
[debug] [35m[ADB][39m Current device property 'ro.product.model': Redmi Note 4
[debug] [35m[ADB][39m Getting connected devices...
[debug] [35m[ADB][39m 1 device(s) connected
[debug] [35m[ADB][39m Running 'C:\Users\DELL\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 31caa5790503 shell getprop ro.product.manufacturer'
[debug] [35m[ADB][39m Current device property 'ro.product.manufacturer': Xiaomi
[35m[AndroidDriver][39m No app sent in, not parsing package/activity
[debug] [35m[AndroidDriver][39m No app capability. Assuming it is already on the device
[debug] [35m[ADB][39m Getting install status for  com.jabong.android
[debug] [35m[ADB][39m Getting connected devices...
[debug] [35m[ADB][39m 1 device(s) connected
[debug] [35m[ADB][39m Running 'C:\Users\DELL\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 31caa5790503 shell pm list packages ' com.jabong.android''
[debug] [35m[ADB][39m App is not installed
[debug] [35m[AndroidDriver][39m Shutting down Android driver
[debug] [35m[AndroidDriver][39m Called deleteSession but bootstrap wasn't active
[debug] [35m[Logcat][39m Stopping logcat capture
[debug] [35m[ADB][39m Getting connected devices...
[debug] [35m[ADB][39m 1 device(s) connected
[debug] [35m[ADB][39m Running 'C:\Users\DELL\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 31caa5790503 shell am force-stop io.appium.unlock'
[debug] [35m[AndroidDriver][39m Not cleaning generated files. Add `clearSystemFiles` capability if wanted.
[debug] [35m[BaseDriver][39m Event 'newSessionStarted' logged at 1526895815470 (15:13:35 GMT+0530 (India Standard Time))
[35m[W3C][39m Encountered internal error running command: Error: 'app' option is required for reinstall
[35m[W3C][39m     at Object.callee$0$0$ (C:\Users\DELL\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium-android-driver\lib\android-helpers.js:266:11)
[35m[W3C][39m     at tryCatch (C:\Users\DELL\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium-android-driver\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[35m[W3C][39m     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\DELL\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium-android-driver\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[35m[W3C][39m     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\DELL\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium-android-driver\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[35m[W3C][39m     at GeneratorFunctionPrototype.invoke (C:\Users\DELL\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium-android-driver\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[35m[W3C][39m     at <anonymous>
[35m[HTTP][39m [37m<-- POST /wd/hub/session [39m[31m500[39m [90m4869 ms - 1556[39m
[35m[HTTP][39m [90m[39m
FAILED: test
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: 'app' option is required for reinstall
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T15:28:36.4Z'
System info: host: 'DESKTOP-EVAHJRN', ip: '10.0.75.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_161'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: 'app' option is required for reinstall
    at getResponseForW3CError (C:\Users\DELL\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium-base-driver\lib\protocol\errors.js:800:13)
    at asyncHandler$ (C:\Users\DELL\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium-base-driver\lib\protocol\protocol.js:352:37)
    at tryCatch (C:\Users\DELL\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium-base-driver\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\DELL\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium-base-driver\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\DELL\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium-base-driver\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\DELL\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium-base-driver\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at <anonymous>
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$24(ProtocolHandshake.java:359)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:362)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:136)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:89)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:586)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:217)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:140)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:83)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:93)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:72)
	at com.sapizon.testcase.Hybrid.test(Hybrid.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.runSuites(TestNG.java:1028)
	at org.testng.TestNG.run(TestNG.java:996)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
```

## Code To Reproduce Issue [ Good To Have ]

It should launch the jabong application but it fails to open 

Play store :- Jabong application

**Comment by imurchie** [comment]
Your app is not installed. But you have not provided an app to install.

**Comment by imurchie** [comment]
Try removing the space from the beginning of your `appPackage`
```java
cap.setCapability("appPackage", " com.jabong.android");
```

**Comment by mykola-mokhnach** [comment]
if app is already installed then it is mandatory to set `noReset` to true
