### ISSUE TITLE
Appium is not starting on Android N (Nougat)

### ISSUE THREAD

**Issue by poonam26sg** [appium/appium#10745]
It seems android N is not supported bu appium.

I am trying to execute a code which works smoothly on Android 6.0.1 is failing on android 7.0 .
App installation itself is failing.

**Environment**
 Appium version :  1.7.0:
Desktop OS/version used to run Appium: Windows 10
Mobile platform/version : Android 7.0
Real device : Samsung Galaxy S8

**Appium logs**
ADB] 1 device(s) connected
[ADB] Running 'D:\Android SDK\platform-tools\adb.exe' with args: ["-P",5037,"-s","*****************","shell","am","force-stop","io.appium.unlock"]
[AndroidDriver] Not cleaning generated files. Add `clearSystemFiles` capability if wanted.
[MJSONWP] Encountered internal error running command: Error: Error executing adbExec. Original error: 'Command ''D:\\Android SDK\\platform-tools\\adb.exe' -P 5037 -s ********************** install C\:\\******************\Local\\Programs\\appium-desktop\\resources\\app\\node_modules\\appium\\node_modules\\appium-unlock\\bin\\unlock_apk-debug.apk' exited with code 1'; Stderr: 'adb: failed to install C:\******************\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-unlock\bin\unlock_apk-debug.apk: Failure [INSTALL_FAILED_VERSION_DOWNGRADE]'; Code: '1'
    at ADB.execFunc$ (C:\******************\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:317:13)
    at tryCatch (C:\******************\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\******************\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\******************\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\******************\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[HTTP] <-- POST /wd/hub/session 500 9433 ms - 726

**Comment by mykola-mokhnach** [comment]
Upgrade Appium server or remove unlock helper app from the device manually
