### ISSUE TITLE
Getting a handle on Safari opened by my app.

### ISSUE THREAD

**Issue by kebernet** [appium/appium#10744]
## The problem

We are using the React Native OAuth lib. This kicks open a Safari instance to handle the login page, but I don't seem to be able to automate this at all.

I have tried creating a new Safari driver instance, but it wants to open the 0.0.0.0 default page, but I want to connect to the previously launched thing.

## Environment

* Appium version (or git revision) that exhibits the issue:
1.8.0
* Last Appium version that did not exhibit the issue (if applicable):
N/A
* Desktop OS/version used to run Appium:
Mac OS 10.13.4
* Node.js version (unless using Appium.app|exe):
9.8.0
* Mobile platform/version under test:
ios
* Real device or emulator/simulator:
Simulator 10.0
* Appium CLI or Appium.app|exe:

## Details

Getting contexts from the mobile driver returns nothing. Safari re-opens with the 0.0.0.0 URI

## Link to Appium logs

Legit no value to be had here:

Command duration or timeout: 431 milliseconds
Build info: version: '2.48.2', revision: '41bccdd10cf2c0560f637404c2d96164b67d9d67', time: '2015-10-09 13:08:06'
System info: host: 'robert-cooper.local', ip: '192.168.1.206', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.4', java.version: '1.8.0_77'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{app=/Users/rcooper/Documents/manheim/ManheimExpress/ios/build/DerivedData/Build/Products/Debug-iphonesimulator/ManheimExpress.app, networkConnectionEnabled=false, databaseEnabled=false, deviceName=iPhone Simulator, platform=MAC, platformVersion=10.0, webStorageEnabled=false, locationContextEnabled=false, browserName=, takesScreenshot=true, javascriptEnabled=true, platformName=iOS, udid=8F391D69-168B-4BD3-A9D2-0A627C8D7121}]
Session ID: df2eec4f-71cc-4bdb-a6ad-f2acb67c91a5
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:647)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:206)
	at io.appium.java_client.AppiumDriver.getContextHandles(AppiumDriver.java:552)
	at com.manheim.manheimexpress.cucumber.steps.BaseSteps.clickByElementId(BaseSteps.java:48)

## Code To Reproduce Issue [ Good To Have ]

This is a lot of setup, but for real we are just using the react-native oauth code that kicks out to a browser. It is just that the kick out to a browser doesn't seem to allow automation. I really just want to connect to the Safair/Chrome instance that is already running without resetting the state.

**Comment by mykola-mokhnach** [comment]
Does https://appium.io/docs/en/writing-running-appium/web/hybrid/ work for you?

**Comment by mykola-mokhnach** [comment]
It is not possible to say more without the server log
