### ISSUE TITLE
[MJSONWP] Encountered internal error running command: Error: An error occurred

### ISSUE THREAD

**Issue by yangyang50** [appium/appium#10775]
## The problem

Installed the latest 1.8.2-beta2 and not able to start iOS tests。Could you do me a favor,How to achieve this function。My email address is softwareyang@126.com, can you give me a contact information? My English is not very good,If you can give me a contact will be better. thank you very much

## Environment

appium:1.8.2-beta3
wda: latest version
mac 10.13.4
iphone 11.3.1

## Details

the following is the code:

@Before
    public void setUp() throws MalformedURLException {
        DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
        desiredCapabilities.setCapability("deviceName", "iphone 6 Plus");
        desiredCapabilities.setCapability("platformVersion", "10.1.1");
        desiredCapabilities.setCapability("platformName", "iOS");
        desiredCapabilities.setCapability("app", "/Users/yangyang50/Desktop/work/JDMEIphone_4.6.0.ipa");
        desiredCapabilities.setCapability("udid", "ae881a9d1a264c582ee9286c043480160fe1f892");
        desiredCapabilities.setCapability("autoLaunch", false);

        URL remoteUrl = new URL("http://localhost:4723/wd/hub");

        driver = new IOSDriver(remoteUrl, desiredCapabilities);
    }

the following is the error:

[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"11.3.1\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"11.3.1\",\n      \"ip\" : \"10.0.220.208\"\n    },\n    \"build\" : {\n      \"time\" : \"May 29 2018 16:37:58\"\n    }\n  },\n  \"sessionId\" : \"FABE11B4-B8B0-4B4D-9774-9476D5A4E558\",\n  \"status\" : 0\n}"
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.testjdme","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"sessionId":"0DB7B540-BBA8-4FB8-87DB-995F9BF96DD5","capabilities":{"device":"iphone","browserName":" ","sdkVersion":"11.3.1","CFBundleIdentifier":"com.apple.springboard"}},"sessionId":"0DB7B540-BBA8-4FB8-87DB-995F9BF96DD5","status":0}
[debug] [BaseDriver] Event 'wdaSessionStarted' logged at 1527583659740 (16:47:39 GMT+0800 (CST))
[debug] [BaseDriver] Event 'wdaStarted' logged at 1527583659740 (16:47:39 GMT+0800 (CST))
[XCUITest] Skipping setting of the initial display orientation. Set the "orientation" capability to either "LANDSCAPE" or "PORTRAIT", if this is an undesired behavior.
[debug] [BaseDriver] Event 'orientationSet' logged at 1527583659741 (16:47:39 GMT+0800 (CST))
[Appium] New XCUITestDriver session created successfully, session 38611174-e3e4-4779-b8ff-ba5e4b8d5c78 added to master session list
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1527583659742 (16:47:39 GMT+0800 (CST))
[debug] [MJSONWP] Responding to client with driver.createSession() result: {"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"app":"/Users/yangyang50/Desktop/work/JDMEIphone_4.6.0.ipa","autoLaunch":false,"platformVersion":"10.1.1","platformName":"iOS","udid":"ae881a9d1a264c582ee9286c043480160fe1f892","deviceName":"iphone 6 Plus"}
[HTTP] <-- POST /wd/hub/session 200 13830 ms - 475
[HTTP] 
[HTTP] --> GET /wd/hub/session/38611174-e3e4-4779-b8ff-ba5e4b8d5c78
[HTTP] {}
[debug] [MJSONWP] Calling AppiumDriver.getSession() with args: ["38611174-e3e4-4779-b8ff-ba5e4b8d5c78"]
[debug] [XCUITest] Executing command 'getSession'
[debug] [JSONWP Proxy] Proxying [GET /] to [GET http://localhost:8100/session/0DB7B540-BBA8-4FB8-87DB-995F9BF96DD5] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"sessionId\" : \"0DB7B540-BBA8-4FB8-87DB-995F9BF96DD5\",\n    \"capabilities\" : {\n      \"device\" : \"iphone\",\n      \"browserName\" : \" \",\n      \"sdkVersion\" : \"11.3.1\",\n      \"CFBundleIdentifier\" : \"com.apple.springboard\"\n    }\n  },\n  \"sessionId\" : \"0DB7B540-BBA8-4FB8-87DB-995F9BF96DD5\",\n  \"status\" : 0\n}"
[XCUITest] Merging WDA caps over Appium caps for session detail response
[debug] [JSONWP Proxy] Proxying [GET /wda/screen] to [GET http://localhost:8100/session/0DB7B540-BBA8-4FB8-87DB-995F9BF96DD5/wda/screen] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"Unhandled endpoint: \\/session\\/0DB7B540-BBA8-4FB8-87DB-995F9BF96DD5\\/wda\\/screen -- http:\\/\\/localhost:8100\\/ with parameters {\\n    wildcards =     (\\n        \\\"session\\/0DB7B540-BBA8-4FB8-87DB-995F9BF96DD5\\/wda\\/screen\\\"\\n    );\\n}\",\n  \"sessionId\" : \"0DB7B540-BBA8-4FB8-87DB-995F9BF96DD5\",\n  \"status\" : 1\n}"
[MJSONWP] Encountered internal error running command: Error: An error occurred
[MJSONWP]     at JWProxy.command$ (/Users/yangyang50/Downloads/appium-1.8.2-beta/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:176:15)
[MJSONWP]     at tryCatch (/Users/yangyang50/Downloads/appium-1.8.2-beta/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/yangyang50/Downloads/appium-1.8.2-beta/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/yangyang50/Downloads/appium-1.8.2-beta/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke (/Users/yangyang50/Downloads/appium-1.8.2-beta/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- GET /wd/hub/session/38611174-e3e4-4779-b8ff-ba5e4b8d5c78 500 171 ms - 188
[HTTP]

**Comment by mykola-mokhnach** [comment]
This error pops up, because WDA binary is cached on the device. Try to set `useNewWDA` to `true` and see if it helps. In case the error still happens then perform XCode caches cleanup and full Appium reinstall.

**Comment by yangyang50** [comment]
@mykola-mokhnach I tried the method you said and it is not good to make it. If you increase "desiredCapabilities.setCapability("useNewWDA", true); " the following error will be reported. If you clear the xode caches and full Appium reinstall, it will not work. What better way do you have?

the following is the error:

[debug] [XCUITest] App is present
[debug] [iOS] Getting bundle ID from app '/var/folders/1x/3qyrv3511fqdcnpl6gj_p1187mfzv3/T/2018429-31949-1atydcn.8a1cg/Payload/MEAppModule_Example.app': 'com.testjdme'
[debug] [BaseDriver] Event 'resetStarted' logged at 1527589568415 (18:26:08 GMT+0800 (CST))
[debug] [XCUITest] Reset: running ios real device reset flow
[debug] [BaseDriver] Event 'resetComplete' logged at 1527589568415 (18:26:08 GMT+0800 (CST))
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Starting iOS device log capture with: 'idevicesyslog'
[debug] [XCUITest] Crash reports root '/Users/yangyang50/Library/Logs/CrashReporter/MobileDevice/杨洋的 iPhone' does not exist. Got nothing to gather.
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1527589568654 (18:26:08 GMT+0800 (CST))
[XCUITest] Setting up real device
[debug] [BaseDriver] Event 'appInstalled' logged at 1527589568654 (18:26:08 GMT+0800 (CST))
[XCUITest] Using WDA path: '/Users/yangyang50/Downloads/appium-1.8.2-beta/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Users/yangyang50/Downloads/appium-1.8.2-beta/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[debug] [XCUITest] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[debug] [XCUITest] Capability 'useNewWDA' set to true, so uninstalling WDA before proceeding
[XCUITest] Shutting down sub-processes
[debug] [XCUITest] Removing WDA application from device
[debug] [BaseDriver] Event 'wdaUninstalled' logged at 1527589569280 (18:26:09 GMT+0800 (CST))
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1527589569281 (18:26:09 GMT+0800 (CST))
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Killing running processes 'xcodebuild.*ae881a9d1a264c582ee9286c043480160fe1f892, iproxy 8100' for the device ae881a9d1a264c582ee9286c043480160fe1f892...
[debug] [XCUITest] 'pgrep -nif xcodebuild.*ae881a9d1a264c582ee9286c043480160fe1f892' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] 'pgrep -nif iproxy 8100' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[debug] [XCUITest] Using Xcode 9.3.1, so fixing WDA codebase
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Users/yangyang50/Downloads/appium-1.8.2-beta/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=ae881a9d1a264c582ee9286c043480160fe1f892 IPHONEOS_DEPLOYMENT_TARGET=10.1' in directory '/Users/yangyang50/Downloads/appium-1.8.2-beta/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will not be logged. To change this, use 'showXcodeLog' desired capability
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] Log file for xcodebuild test: /var/folders/1x/3qyrv3511fqdcnpl6gj_p1187mfzv3/T/com.apple.dt.XCTest/IDETestRunSession-964972E8-E813-4942-9679-BEC6455ED5CC/WebDriverAgentRunner-4E853A37-5050-4CE0-B92E-A94F9BA0222B/Session-WebDriverAgentRunner-2018-05-29_182615-R2IVZH.log
[Xcode] 2018-05-29 18:26:15.768 xcodebuild[32095:541275] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/yangyang50/Library/Developer/Xcode/DerivedData/WebDriverAgent-hguaulkznifkrxcinzrpfughbdqr/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7fafde1f85b0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[Xcode] 
[Xcode] 2018-05-29 18:26:15.768 xcodebuild[32095:541275] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted, NSUnderlyingError=0x7fafde417a70 {Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/yangyang50/Library/Developer/Xcode/DerivedData/WebDriverAgent-hguaulkznifkrxcinzrpfughbdqr/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7fafde1f85b0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}}}
[Xcode] 
[Xcode] 
[Xcode] Testing failed:
[Xcode] 
[Xcode] 	Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the project editor.
[Xcode] 	Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 11.3'
[Xcode] 	Early unexpected exit, operation never finished bootstrapping - no restart will be attempted
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[XCUITest] xcodebuild exited with code '65' and signal 'null'
[debug] [BaseDriver] Event 'wdaStartFailed' logged at 1527589575807 (18:26:15 GMT+0800 (CST))

**Comment by mykola-mokhnach** [comment]
> [Xcode] Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the project editor.
> [Xcode] Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 11.3'

This means you have to properly configure codesigning for WDA sources: https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md

**Comment by yangyang50** [comment]
I added the following content in the code, also cleared the xcode cache, the problem has been resolved。thank you very much

desiredCapabilities.setCapability("useNewWDA", true);
desiredCapabilities.setCapability("xcodeOrgId","????");
desiredCapabilities.setCapability("xcodeSigningId","iPhone Developer");
