### ISSUE TITLE
 Could not navigate to webview; there are none!

### ISSUE THREAD

**Issue by reach2jeyan** [appium/appium#10774]
## The problem

I am trying to launch a link in the safari browser in the iOS simulator with version `11.0` with appium version `1.8.1` . I however get this following error. Is there any additional webview options that needs to be passed in the desired capabilities?

Desired capabilities:

```
def start_safari(udid,bootstrap,port_number,url)
      caps_config = { deviceName: "iPhone Simulator",
                      platformName: "iOS",
                      udid: udid,
                      chromedriverExecutable: '/usr/local/lib/node_modules/appium/node_modules/chromedriver/lib/chromedriver/chromedriver',
                      bootstrapPort: bootstrap,
                      browserName: "Safari",
                      safariInitialUrl: url,
                      newCommandTimeout: "3600",
                      automationName: "XCUITest",
                      # startIWDP: "true",
                      bundleId: "com.apple.mobilesafari",
                      appium_lib: { wait: 20,
                                    debug: false

                      } }
      appium_lib_config = {port: port_number}
      $opts={ caps: caps_config, appium_lib: appium_lib_config}
```
## Error
```

Encountered internal error running command: Error: Could not navigate to webview; there are none!
[MJSONWP]     at XCUITestDriver.spinHandles$ (/usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/lib/commands/context.js:522:13)
[MJSONWP]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[MJSONWP]     at <anonymous>
[HTTP] <-- POST /wd/hub/session 500 278686 ms - 183

Selecting by url: true (expected url: 'http://www.linkedin.com')
[debug] [RemoteDebugger] useNewSafari --> false
[debug] [RemoteDebugger] Connecting to remote debugger through TCP: ::1:27753
[debug] [RemoteDebugger] Debugger socket connected
[debug] [RemoteDebugger] Sending connection key request
[debug] [RemoteDebugger] Sending '_rpc_reportIdentifier:' message to remote debugger
[RemoteDebugger] Socket error: read ECONNRESET

```

I see that the url is launched, but the tap which is provided on the next step, does not initiate any action but throws this above error

**Comment by mykola-mokhnach** [comment]
It is enough to set `browserName` to `Safari`: https://appium.io/docs/en/writing-running-appium/web/hybrid/

Regarding webviews accessiblity: make sure you can see them in Safari remote debugger first
