### ISSUE TITLE
uiautomator when it is shutting down, tries to stop the uiautomator process, even if it has already stopped

### ISSUE THREAD

**Issue by JonathanWylie** [appium/appium#10785]
## The problem

uiautomator when it is shutting down, tries to stop the uiautomator process, even if it has already stopped. If it has stopped already then it throws an ugly exception.

## Environment

* Appium version (or git revision) that exhibits the issue:  appium-uiautomator@1.2.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Ubuntu 16.04.4 LTS
* Node.js version (unless using Appium.app|exe): v6.10.2
* Mobile platform/version under test:
* Real device or emulator/simulator: Android Emulator
* Appium CLI or Appium.app|exe:

## Details

appium uiautomator manages the uiautomator process which runs on the emulator.
When it is stopping it closes it's connection to uiautomator, and the uiautomator logs some output about what it did.
```
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Closed client connection
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: numtests=1
...
[debug] [AndroidBootstrap] [UIAUTO STDOUT] OK (1 test)
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS_CODE: -1
```
It then stops the uiautomator process and double checks it is really stopped by killing any uiautomator processes on the emulator.
```
[debug] [UiAutomator] Shutting down UiAutomator
[debug] [UiAutomator] Moving to state 'stopping'
[debug] [UiAutomator] UiAutomator shut down normally
[debug] [UiAutomator] Moving to state 'stopped'
[debug] [ADB] Attempting to kill all uiautomator processes
```
But sporadically I get these errors, where the uiautomator unexepctedly terminates with exit code 0.
This happens during the shutdown process. We see:
- Connection is closed
- uiautomator logs it's output at the end of testing
- uiautomator exits unexpectedly with code 0
- uiautomator shutsdown, but fails when it tries to stop the process which has already stopped

```
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Closed client connection
...[debug] [AndroidBootstrap] [UIAUTO STDOUT] OK (1 test)
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS_CODE: -1
[debug] [AndroidBootstrap] Received command result from bootstrap
[UiAutomator] UiAutomator exited unexpectedly with code 0, signal null
[debug] [UiAutomator] Moving to state 'stopped'
[debug] [UiAutomator] Shutting down UiAutomator
[debug] [UiAutomator] Moving to state 'stopping'
[Appium] Had trouble ending session 6f4a4cdd-e924-4b18-abd6-29cc814505ee: Can't stop process; it's not currently running (cmd: '/sv/android/sdk_v3/platform-tools/adb')
[MJSONWP] Encountered internal error running command: Error: Can't stop process; it's not currently running (cmd: '/sv/android/sdk_v3/platform-tools/adb')
[MJSONWP]     at SubProcess.stop$ (/sv/venv/svMonitorInjectorV2_data/svMonitorInjectorV2_2018-05-23_08-39-12-902178/lib/python2.7/site-packages/svAppium/node_modules/teen_process/lib/subprocess.js:179:13)
...
[MJSONWP]     at GeneratorFunctionPrototype.invoke (/sv/venv/svMonitorInjectorV2_data/svMonitorInjectorV2_2018-05-23_08-39-12-902178/lib/python2.7/site-packages/svAppium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- DELETE /wd/hub/session/6f4a4cdd-e924-4b18-abd6-29cc814505ee 500 756 ms - 264
[HTTP]
```

I think that the uiautomator process is terminating naturally at the end of testing.
If I hack appium-uiautomator to not stop the process and not kill remaining uiautomator processes, then I can see afterwards that the uiautomator has termianted anyway.

logging showing appium-uiautomator not trying to stop the process
```
2018-05-31 06:48:19,084/+  55225|DEBUG   | processes.py:478  |  9949 |   Thread-4 | Appium | [debug] [UiAutomator] Shutting down UiAutomator
2018-05-31 06:48:19,084/+  55225|DEBUG   | processes.py:478  |  9949 |   Thread-4 | Appium | [debug] [UiAutomator] Moving to state 'stopping'
2018-05-31 06:48:19,084/+  55225|DEBUG   | processes.py:478  |  9949 |   Thread-4 | Appium | [debug] [UiAutomator] Moving to state 'stopped'
2018-05-31 06:48:19,085/+  55226|DEBUG   | processes.py:478  |  9949 |   Thread-4 | Appium | [debug] [Logcat] Stopping logcat capture
2018-05-31 06:48:19,086/+  55227|DEBUG   | processes.py:478  |  9949 |   Thread-4 | Appium | [debug] [UiAutomator] Moving to state 'stopped'
```

But during the test we see the process, but it is no longer running afterwards, despite appium-uiautomator not trying to stop it.
```
platform-tools/adb -P 5037 -s emulator-5568 shell ps | grep "uiautomator"
root      5111  1166  840220 27544 ffffffff b768c8c3 S uiautomator
platform-tools/adb -P 5037 -s emulator-5568 shell ps | grep "uiautomator"
```

I think the fix is straightforward. Don't try to stop the process if it has already stopped.

**Comment by JonathanWylie** [comment]
Here is a pull request: https://github.com/appium/appium-uiautomator/pull/12

**Comment by JonathanWylie** [comment]
My pull request was accepted, so closing this.
