### ISSUE TITLE
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: o.?

### ISSUE THREAD

**Issue by umashankaryadagiri1** [appium/appium#10804]
Code :

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.time.Duration;
import java.util.List;
import java.util.concurrent.TimeUnit;

import org.apache.poi.EncryptedDocumentException;
import org.apache.poi.openxml4j.exceptions.InvalidFormatException;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.usermodel.WorkbookFactory;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.Keys;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.testng.annotations.Test;

import io.appium.java_client.TouchAction;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.android.AndroidElement;
import io.appium.java_client.remote.MobileCapabilityType;

public class Demo {
	AndroidDriver<AndroidElement> driver;
	Duration mills = Duration.ofMillis(3000);
	public static Workbook wb,wb1;
	public static Sheet sheet;
	public static Row row;
	public static Cell cell;
	static int i=0;
	int j=3;
	int k=0;
	
	/**
	 * @author Umashankar
	 * @purpose Testing shopping links
	 * @date 01-June-2018
	 * @throws MalformedURLException
	 * @throws InterruptedException
	 */

	@Test
	public void ent() throws MalformedURLException, InterruptedException {
				
				DesiredCapabilities cap = new DesiredCapabilities();
				cap.setCapability(MobileCapabilityType.DEVICE_NAME, "Android Device");
				cap.setCapability("platformName", "Android");
				cap.setCapability("appPackage", "com.tmw.mobilewallet");
				cap.setCapability("appActivity", "com.tmw.mobilewallet.activities.SplashActivity");
				driver = new AndroidDriver<AndroidElement>(new URL("http://127.0.0.1:4723/wd/hub"), cap);
				cap.setCapability("autoAcceptAlerts", true);
				driver.manage().timeouts().implicitlyWait(50,TimeUnit.SECONDS);
				Thread.sleep(6000);
				driver.findElementByXPath("//android.widget.RelativeLayout[@index='0']/android.widget.EditText[@index='1']").sendKeys("8692805930");
				//driver.findElementByXPath("//android.widget.RelativeLayout[@index='0']/android.widget.EditText[@index='1']").sendKeys("8879757323");
				Thread.sleep(5000);
				driver.findElementByXPath("//android.widget.LinearLayout[@index='0']/android.widget.TextView[@text='Send OTP']").click();
				Thread.sleep(30000);
				driver.findElementByXPath("//android.widget.LinearLayout[@index='2']/android.widget.LinearLayout[@index='0']").click();//4
				Thread.sleep(1000);
				driver.findElementByXPath("//android.widget.LinearLayout[@index='3']/android.widget.LinearLayout[@index='0']").click();//7
				Thread.sleep(1000);
				driver.findElementByXPath("//android.widget.LinearLayout[@index='3']/android.widget.LinearLayout[@index='1']").click();//8
				Thread.sleep(1000);
				driver.findElementByXPath("//android.widget.LinearLayout[@index='1']/android.widget.LinearLayout[@index='1']").click();//1
				Thread.sleep(2000);
				driver.findElementByXPath("//android.widget.LinearLayout[@index='4']/android.widget.LinearLayout[@index='2']").click();//right tick
								
				
			    
			    System.out.println(driver.getContext());
			    Thread.sleep(2000);
				
				
				try {
					
					Thread.sleep(10000);
					driver.findElement(By.xpath("//android.widget.TextView[@text='Gold']")).click();
				
					
			}
				catch(Exception e){
					e.printStackTrace();}
				
					
				}
	}

Error :[RemoteTestNG] detected TestNG version 6.11.0
Jun 05, 2018 7:26:58 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
NATIVE_APP
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: o.? (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.9.1', revision: '63f7b50', time: '2018-02-07T22:25:02.294Z'
System info: host: 'Q69DWS69', ip: '172.16.50.7', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_102'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {appActivity: com.tmw.mobilewallet.activi..., appPackage: com.tmw.mobilewallet, databaseEnabled: false, desired: {appActivity: com.tmw.mobilewallet.activi..., appPackage: com.tmw.mobilewallet, deviceName: Android Device, platformName: Android}, deviceManufacturer: Xiaomi, deviceModel: Redmi 4A, deviceName: 667d74c1f4c4, deviceScreenSize: 720x1280, deviceUDID: 667d74c1f4c4, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, platform: LINUX, platformName: LINUX, platformVersion: 6.0.1, takesScreenshot: true, warnings: {}, webStorageEnabled: false}
Session ID: cc44a1db-82d9-44b1-bef9-87dc90fb70db
*** Element info: {Using=xpath, value=//android.widget.TextView[@text='Gold']}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:160)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:89)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:371)
	at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:62)
	at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.findElement(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:473)
	at io.appium.java_client.DefaultGenericMobileDriver.findElementByXPath(DefaultGenericMobileDriver.java:140)
	at io.appium.java_client.AppiumDriver.findElementByXPath(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.findElementByXPath(AndroidDriver.java:1)
	at org.openqa.selenium.By$ByXPath.findElement(By.java:361)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:363)
	at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:58)
	at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.findElement(AndroidDriver.java:1)
	at Demo.ent(Demo.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
PASSED: ent

===============================================
    Default test
    Tests run: 1, Failures: 0, Skips: 0
===============================================

===============================================
Default suite
Total tests run: 1, Failures: 0, Skips: 0
===============================================

Appium logs :abled":false,"warnings":{},"desired":{"appActivity":"com.tmw.mobilewallet.activi
ties.SplashActivity","appPackage":"com.tmw.mobilewallet","deviceName":"Android D
evice","platformName":"Android"},"appActivity":"com.tmw.mobilewallet.activities.
SplashActivity","appPackage":"com.tmw.mobilewallet","deviceName":"667d74c1f4c4",
"platformName":"Android","deviceUDID":"667d74c1f4c4","platformVersion":"6.0.1","
deviceScreenSize":"720x1280","deviceModel":"Redmi 4A","deviceManufacturer":"Xiao
mi"}
[HTTP] <-- GET /wd/hub/session/cc44a1db-82d9-44b1-bef9-87dc90fb70db 200 5 ms - 7
24
[HTTP]
[HTTP] --> POST /wd/hub/session/cc44a1db-82d9-44b1-bef9-87dc90fb70db/element/5/c
lick
[HTTP] {"id":"5"}
[debug] [W3C] Calling AppiumDriver.click() with args: ["5","cc44a1db-82d9-44b1-b
ef9-87dc90fb70db"]
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":
"element:click","params":{"elementId":"5"}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":
"action","action":"element:click","params":{"elementId":"5"}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: click
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0
,"value":true}
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [MJSONWP] Responding to client with driver.click() result: true
[HTTP] <-- POST /wd/hub/session/cc44a1db-82d9-44b1-bef9-87dc90fb70db/element/5/c
lick 200 3162 ms - 76
[HTTP]
[HTTP] --> POST /wd/hub/session/cc44a1db-82d9-44b1-bef9-87dc90fb70db/element
[HTTP] {"using":"xpath","value":"//android.widget.LinearLayout[@index='1']/andro
id.widget.LinearLayout[@index='1']"}
[debug] [W3C] Calling AppiumDriver.findElement() with args: ["xpath","//android.
widget.LinearLayout[@index='1']/android.widget.LinearLayout[@index='1']","cc44a1
db-82d9-44b1-bef9-87dc90fb70db"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class
 name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":
"find","params":{"strategy":"xpath","selector":"//android.widget.LinearLayout[@i
ndex='1']/android.widget.LinearLayout[@index='1']","context":"","multiple":false
}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":
"action","action":"find","params":{"strategy":"xpath","selector":"//android.widg
et.LinearLayout[@index='1']/android.widget.LinearLayout[@index='1']","context":"
","multiple":false}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding '//android.widget.Lin
earLayout[@index='1']/android.widget.LinearLayout[@index='1']' using 'XPATH' wit
h the contextId: '' multiple: false
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[CLASS=andro
id.widget.LinearLayout, INSTANCE=6]
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0
,"value":{"ELEMENT":"6"}}
[debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEME
NT":"6"}
[HTTP] <-- POST /wd/hub/session/cc44a1db-82d9-44b1-bef9-87dc90fb70db/element 200
 267 ms - 87
[HTTP]
[HTTP] --> GET /wd/hub/session/cc44a1db-82d9-44b1-bef9-87dc90fb70db
[HTTP] {}
[debug] [W3C] Calling AppiumDriver.getSession() with args: ["cc44a1db-82d9-44b1-
bef9-87dc90fb70db"]
[debug] [MJSONWP] Responding to client with driver.getSession() result: {"platfo
rm":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled"
:true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEn
abled":false,"warnings":{},"desired":{"appActivity":"com.tmw.mobilewallet.activi
ties.SplashActivity","appPackage":"com.tmw.mobilewallet","deviceName":"Android D
evice","platformName":"Android"},"appActivity":"com.tmw.mobilewallet.activities.
SplashActivity","appPackage":"com.tmw.mobilewallet","deviceName":"667d74c1f4c4",
"platformName":"Android","deviceUDID":"667d74c1f4c4","platformVersion":"6.0.1","
deviceScreenSize":"720x1280","deviceModel":"Redmi 4A","deviceManufacturer":"Xiao
mi"}
[HTTP] <-- GET /wd/hub/session/cc44a1db-82d9-44b1-bef9-87dc90fb70db 200 12 ms -
724
[HTTP]
[HTTP] --> GET /wd/hub/session/cc44a1db-82d9-44b1-bef9-87dc90fb70db
[HTTP] {}
[debug] [W3C] Calling AppiumDriver.getSession() with args: ["cc44a1db-82d9-44b1-
bef9-87dc90fb70db"]
[debug] [MJSONWP] Responding to client with driver.getSession() result: {"platfo
rm":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled"
:true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEn
abled":false,"warnings":{},"desired":{"appActivity":"com.tmw.mobilewallet.activi
ties.SplashActivity","appPackage":"com.tmw.mobilewallet","deviceName":"Android D
evice","platformName":"Android"},"appActivity":"com.tmw.mobilewallet.activities.
SplashActivity","appPackage":"com.tmw.mobilewallet","deviceName":"667d74c1f4c4",
"platformName":"Android","deviceUDID":"667d74c1f4c4","platformVersion":"6.0.1","
deviceScreenSize":"720x1280","deviceModel":"Redmi 4A","deviceManufacturer":"Xiao
mi"}
[HTTP] <-- GET /wd/hub/session/cc44a1db-82d9-44b1-bef9-87dc90fb70db 200 8 ms - 7
24
[HTTP]
[HTTP] --> GET /wd/hub/session/cc44a1db-82d9-44b1-bef9-87dc90fb70db
[HTTP] {}
[debug] [W3C] Calling AppiumDriver.getSession() with args: ["cc44a1db-82d9-44b1-
bef9-87dc90fb70db"]
[debug] [MJSONWP] Responding to client with driver.getSession() result: {"platfo
rm":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled"
:true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEn
abled":false,"warnings":{},"desired":{"appActivity":"com.tmw.mobilewallet.activi
ties.SplashActivity","appPackage":"com.tmw.mobilewallet","deviceName":"Android D
evice","platformName":"Android"},"appActivity":"com.tmw.mobilewallet.activities.
SplashActivity","appPackage":"com.tmw.mobilewallet","deviceName":"667d74c1f4c4",
"platformName":"Android","deviceUDID":"667d74c1f4c4","platformVersion":"6.0.1","
deviceScreenSize":"720x1280","deviceModel":"Redmi 4A","deviceManufacturer":"Xiao
mi"}
[HTTP] <-- GET /wd/hub/session/cc44a1db-82d9-44b1-bef9-87dc90fb70db 200 6 ms - 7
24
[HTTP]
[HTTP] --> GET /wd/hub/session/cc44a1db-82d9-44b1-bef9-87dc90fb70db
[HTTP] {}
[debug] [W3C] Calling AppiumDriver.getSession() with args: ["cc44a1db-82d9-44b1-
bef9-87dc90fb70db"]
[debug] [MJSONWP] Responding to client with driver.getSession() result: {"platfo
rm":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled"
:true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEn
abled":false,"warnings":{},"desired":{"appActivity":"com.tmw.mobilewallet.activi
ties.SplashActivity","appPackage":"com.tmw.mobilewallet","deviceName":"Android D
evice","platformName":"Android"},"appActivity":"com.tmw.mobilewallet.activities.
SplashActivity","appPackage":"com.tmw.mobilewallet","deviceName":"667d74c1f4c4",
"platformName":"Android","deviceUDID":"667d74c1f4c4","platformVersion":"6.0.1","
deviceScreenSize":"720x1280","deviceModel":"Redmi 4A","deviceManufacturer":"Xiao
mi"}
[HTTP] <-- GET /wd/hub/session/cc44a1db-82d9-44b1-bef9-87dc90fb70db 200 4 ms - 7
24
[HTTP]
[HTTP] --> POST /wd/hub/session/cc44a1db-82d9-44b1-bef9-87dc90fb70db/element/6/c
lick
[HTTP] {"id":"6"}
[debug] [W3C] Calling AppiumDriver.click() with args: ["6","cc44a1db-82d9-44b1-b
ef9-87dc90fb70db"]
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":
"element:click","params":{"elementId":"6"}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":
"action","action":"element:click","params":{"elementId":"6"}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: click
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0
,"value":true}
[debug] [MJSONWP] Responding to client with driver.click() result: true
[HTTP] <-- POST /wd/hub/session/cc44a1db-82d9-44b1-bef9-87dc90fb70db/element/6/c
lick 200 437 ms - 76
[HTTP]
[HTTP] --> POST /wd/hub/session/cc44a1db-82d9-44b1-bef9-87dc90fb70db/element
[HTTP] {"using":"xpath","value":"//android.widget.LinearLayout[@index='4']/andro
id.widget.LinearLayout[@index='2']"}
[debug] [W3C] Calling AppiumDriver.findElement() with args: ["xpath","//android.
widget.LinearLayout[@index='4']/android.widget.LinearLayout[@index='2']","cc44a1
db-82d9-44b1-bef9-87dc90fb70db"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class
 name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":
"find","params":{"strategy":"xpath","selector":"//android.widget.LinearLayout[@i
ndex='4']/android.widget.LinearLayout[@index='2']","context":"","multiple":false
}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":
"action","action":"find","params":{"strategy":"xpath","selector":"//android.widg
et.LinearLayout[@index='4']/android.widget.LinearLayout[@index='2']","context":"
","multiple":false}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding '//android.widget.Lin
earLayout[@index='4']/android.widget.LinearLayout[@index='2']' using 'XPATH' wit
h the contextId: '' multiple: false
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[CLASS=andro
id.widget.LinearLayout, INSTANCE=19]
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0
,"value":{"ELEMENT":"7"}}
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEME
NT":"7"}
[HTTP] <-- POST /wd/hub/session/cc44a1db-82d9-44b1-bef9-87dc90fb70db/element 200
 244 ms - 87
[HTTP]
[HTTP] --> GET /wd/hub/session/cc44a1db-82d9-44b1-bef9-87dc90fb70db
[HTTP] {}
[debug] [W3C] Calling AppiumDriver.getSession() with args: ["cc44a1db-82d9-44b1-
bef9-87dc90fb70db"]
[debug] [MJSONWP] Responding to client with driver.getSession() result: {"platfo
rm":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled"
:true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEn
abled":false,"warnings":{},"desired":{"appActivity":"com.tmw.mobilewallet.activi
ties.SplashActivity","appPackage":"com.tmw.mobilewallet","deviceName":"Android D
evice","platformName":"Android"},"appActivity":"com.tmw.mobilewallet.activities.
SplashActivity","appPackage":"com.tmw.mobilewallet","deviceName":"667d74c1f4c4",
"platformName":"Android","deviceUDID":"667d74c1f4c4","platformVersion":"6.0.1","
deviceScreenSize":"720x1280","deviceModel":"Redmi 4A","deviceManufacturer":"Xiao
mi"}
[HTTP] <-- GET /wd/hub/session/cc44a1db-82d9-44b1-bef9-87dc90fb70db 200 12 ms -
724
[HTTP]
[HTTP] --> GET /wd/hub/session/cc44a1db-82d9-44b1-bef9-87dc90fb70db
[HTTP] {}
[debug] [W3C] Calling AppiumDriver.getSession() with args: ["cc44a1db-82d9-44b1-
bef9-87dc90fb70db"]
[debug] [MJSONWP] Responding to client with driver.getSession() result: {"platfo
rm":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled"
:true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEn
abled":false,"warnings":{},"desired":{"appActivity":"com.tmw.mobilewallet.activi
ties.SplashActivity","appPackage":"com.tmw.mobilewallet","deviceName":"Android D
evice","platformName":"Android"},"appActivity":"com.tmw.mobilewallet.activities.
SplashActivity","appPackage":"com.tmw.mobilewallet","deviceName":"667d74c1f4c4",
"platformName":"Android","deviceUDID":"667d74c1f4c4","platformVersion":"6.0.1","
deviceScreenSize":"720x1280","deviceModel":"Redmi 4A","deviceManufacturer":"Xiao
mi"}
[HTTP] <-- GET /wd/hub/session/cc44a1db-82d9-44b1-bef9-87dc90fb70db 200 9 ms - 7
24
[HTTP]
[HTTP] --> GET /wd/hub/session/cc44a1db-82d9-44b1-bef9-87dc90fb70db
[HTTP] {}
[debug] [W3C] Calling AppiumDriver.getSession() with args: ["cc44a1db-82d9-44b1-
bef9-87dc90fb70db"]
[debug] [MJSONWP] Responding to client with driver.getSession() result: {"platfo
rm":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled"
:true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEn
abled":false,"warnings":{},"desired":{"appActivity":"com.tmw.mobilewallet.activi
ties.SplashActivity","appPackage":"com.tmw.mobilewallet","deviceName":"Android D
evice","platformName":"Android"},"appActivity":"com.tmw.mobilewallet.activities.
SplashActivity","appPackage":"com.tmw.mobilewallet","deviceName":"667d74c1f4c4",
"platformName":"Android","deviceUDID":"667d74c1f4c4","platformVersion":"6.0.1","
deviceScreenSize":"720x1280","deviceModel":"Redmi 4A","deviceManufacturer":"Xiao
mi"}
[HTTP] <-- GET /wd/hub/session/cc44a1db-82d9-44b1-bef9-87dc90fb70db 200 3 ms - 7
24
[HTTP]
[HTTP] --> GET /wd/hub/session/cc44a1db-82d9-44b1-bef9-87dc90fb70db
[HTTP] {}
[debug] [W3C] Calling AppiumDriver.getSession() with args: ["cc44a1db-82d9-44b1-
bef9-87dc90fb70db"]
[debug] [MJSONWP] Responding to client with driver.getSession() result: {"platfo
rm":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled"
:true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEn
abled":false,"warnings":{},"desired":{"appActivity":"com.tmw.mobilewallet.activi
ties.SplashActivity","appPackage":"com.tmw.mobilewallet","deviceName":"Android D
evice","platformName":"Android"},"appActivity":"com.tmw.mobilewallet.activities.
SplashActivity","appPackage":"com.tmw.mobilewallet","deviceName":"667d74c1f4c4",
"platformName":"Android","deviceUDID":"667d74c1f4c4","platformVersion":"6.0.1","
deviceScreenSize":"720x1280","deviceModel":"Redmi 4A","deviceManufacturer":"Xiao
mi"}
[HTTP] <-- GET /wd/hub/session/cc44a1db-82d9-44b1-bef9-87dc90fb70db 200 4 ms - 7
24
[HTTP]
[HTTP] --> POST /wd/hub/session/cc44a1db-82d9-44b1-bef9-87dc90fb70db/element/7/c
lick
[HTTP] {"id":"7"}
[debug] [W3C] Calling AppiumDriver.click() with args: ["7","cc44a1db-82d9-44b1-b
ef9-87dc90fb70db"]
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":
"element:click","params":{"elementId":"7"}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":
"action","action":"element:click","params":{"elementId":"7"}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: click
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0
,"value":true}
[debug] [MJSONWP] Responding to client with driver.click() result: true
[HTTP] <-- POST /wd/hub/session/cc44a1db-82d9-44b1-bef9-87dc90fb70db/element/7/c
lick 200 427 ms - 76
[HTTP]
[HTTP] --> GET /wd/hub/session/cc44a1db-82d9-44b1-bef9-87dc90fb70db/context
[HTTP] {}
[debug] [W3C] Calling AppiumDriver.getCurrentContext() with args: ["cc44a1db-82d
9-44b1-bef9-87dc90fb70db"]
[debug] [MJSONWP] Responding to client with driver.getCurrentContext() result: "
NATIVE_APP"
[HTTP] <-- GET /wd/hub/session/cc44a1db-82d9-44b1-bef9-87dc90fb70db/context 200
11 ms - 84
[HTTP]
[HTTP] --> POST /wd/hub/session/cc44a1db-82d9-44b1-bef9-87dc90fb70db/element
[HTTP] {"using":"xpath","value":"//android.widget.TextView[@text='Gold']"}
[debug] [W3C] Calling AppiumDriver.findElement() with args: ["xpath","//android.
widget.TextView[@text='Gold']","cc44a1db-82d9-44b1-bef9-87dc90fb70db"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class
 name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":
"find","params":{"strategy":"xpath","selector":"//android.widget.TextView[@text=
'Gold']","context":"","multiple":false}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":
"action","action":"find","params":{"strategy":"xpath","selector":"//android.widg
et.TextView[@text='Gold']","context":"","multiple":false}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding '//android.widget.Tex
tView[@text='Gold']' using 'XPATH' with the contextId: '' multiple: false
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [MJSONWP] Matched JSONWP error code 13 to UnknownError
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Command returned error:org.w3
c.dom.DOMException: o.?
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":1
3,"value":"o.?"}
[HTTP] <-- POST /wd/hub/session/cc44a1db-82d9-44b1-bef9-87dc90fb70db/element 500
 126 ms - 176
[HTTP]

While i try to click on simple xpath : driver.findElement(By.xpath("//android.widget.TextView[@text='Gold']")).click(); is not working

**Comment by mykola-mokhnach** [comment]
Switch to UIAutomator2 backend

**Comment by umashankaryadagiri1** [comment]
Switch to UIAutomator2 backend - I am new to appium let me know how to switch to UIAutomator2 backend

**Comment by KazuCocoa** [comment]
Let's read http://appium.io/docs/en/writing-running-appium/caps/index.html 's `automationName` @umashankaryadagiri1

**Comment by mykola-mokhnach** [comment]
Is sir banned from Google search?
http://appium.io/docs/en/drivers/android-uiautomator2/index.html
