### ISSUE TITLE
Android: Unable to connect to Chrome webview

### ISSUE THREAD

**Issue by mayureshshirodkar** [appium/appium#10837]
## The problem

Since upgrading to Appium 1.8.2 Beta, i am unable to connect to Chrome webview.
Appium tries to look for com.google.android.webview package but the chromedriver is at version 2.39 resulting in compatibility error.

My Chrome browser version on device is 67.0. - As required.
Android Webview version-55.0.2883 - Less than required.

I tried to update the Android Webview app, but it showed as disabled and there was no option to update it on Google Playstore.

I googled this up and looks like Chrome will become webview in Android 7-
Here's the reference- https://www.androidpolice.com/2016/07/20/google-explains-chrome-will-become-webview-android-7-0/

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.2 Beta
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 10.13.4
* Node.js version (unless using Appium.app|exe): 
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator: Moto G4

## Details
Adding snippet of the error here.Detailed log below.
```
[HTTP] --> POST /wd/hub/session/a321fca7-a52a-4a66-b7ac-4caa96334a4b/context
[HTTP] {"name":"WEBVIEW_com.eab.se"}
[debug] [W3C] Calling AppiumDriver.setContext() with args: ["WEBVIEW_com.eab.se","a321fca7-a52a-4a66-b7ac-4caa96334a4b"]
[debug] [AndroidDriver] Getting a list of available webviews
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Applications/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -P 5037 -s ZY223DDFLZ shell cat /proc/net/unix'
[debug] [AndroidDriver] WEBVIEW_25224 mapped to pid 25224
[debug] [AndroidDriver] Getting process name for webview
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Applications/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -P 5037 -s ZY223DDFLZ shell ps'
[debug] [AndroidDriver] Parsed pid: '25224' pkg: 'com.eab.se' from
[debug] [AndroidDriver]     USER      PID   PPID  VSIZE  RSS   WCHAN            PC  NAME
[debug] [AndroidDriver]     u0_a812   25224 585   1207384 103516 SyS_epoll_ 00000000 S com.eab.se
[debug] [AndroidDriver] Returning process name: 'com.eab.se'
[debug] [AndroidDriver] Found webviews: ["WEBVIEW_chrome","WEBVIEW_com.eab.se"]
[debug] [AndroidDriver] Available contexts: ["NATIVE_APP","WEBVIEW_chrome","WEBVIEW_com.eab.se"]
[debug] [AndroidDriver] Connecting to chrome-backed webview context 'WEBVIEW_com.eab.se'
[debug] [AndroidDriver] A port was not given, using random port: 8000
[debug] [Chromedriver] Changed state to 'starting'
[debug] [Chromedriver] The following Chromedriver executables were found:
[debug] [Chromedriver]     /usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/chromedriver (minimum Chrome version '66.0.3359')
[debug] [ADB] Getting package info for 'com.google.android.webview'
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
**[debug] [ADB] Running '/Applications/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -P 5037 -s ZY223DDFLZ shell dumpsys package com.google.android.webview'
[debug] [Chromedriver] Found Chrome bundle 'com.google.android.webview' version '55.0.2883'
[Chromedriver] Error: No Chromedriver found that can automate Chrome '55.0.2883'. See https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md for more details.**
[Chromedriver]     at Object.wrappedLogger.errorAndThrow (/usr/local/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[Chromedriver]     at Chromedriver.getCompatibleChromedriver$ (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/lib/chromedriver.js:228:11)
[Chromedriver]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[Chromedriver]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[Chromedriver]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[Chromedriver]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[Chromedriver]     at <anonymous>
[Chromedriver] Error: No Chromedriver found that can automate Chrome '55.0.2883'. See https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md for more details.
[Chromedriver]     at Object.wrappedLogger.errorAndThrow (/usr/local/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[Chromedriver]     at Chromedriver.getCompatibleChromedriver$ (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/lib/chromedriver.js:228:11)
[Chromedriver]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[Chromedriver]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[Chromedriver]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[Chromedriver]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[Chromedriver]     at <anonymous>
[W3C] Encountered internal error running command: Error: No Chromedriver found that can automate Chrome '55.0.2883'. See https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md for more details.
[W3C]     at Object.wrappedLogger.errorAndThrow (/usr/local/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[W3C]     at Chromedriver.getCompatibleChromedriver$ (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/lib/chromedriver.js:228:11)
[W3C]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[W3C]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[W3C]     at <anonymous>
[HTTP] <-- POST /wd/hub/session/a321fca7-a52a-4a66-b7ac-4caa96334a4b/context 500 404 ms - 1438

```
## Link to Appium logs

Detailed Log- https://gist.github.com/mayureshshirodkar/269a5aeed8aaa23de07735bd3b513b98

**Comment by lamquangthanh** [comment]
Hello, i have the same issues with you (Nexus 6). Nexus use the default version of chrome (v55) and cannot uninstall or update to the latest. But when i check on samsung, it works.

**Comment by mykola-mokhnach** [comment]
> [W3C] Encountered internal error running command: Error: No Chromedriver found that can automate Chrome '55.0.2883'. See https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md for more details.

Have you eventually read this doc?

**Comment by mayureshshirodkar** [comment]
@mykola-mokhnach Yes i have gone through the documents. 
I tried this combination:
1. Downgrade the chromedriver version on appium to 2.28,
Downgrade Chrome browser is updated to 55.0, this worked fine.
This combination worked fine.

2. Upgrade chromedriver to version 2.39
Upgrade chrome browser to 67.0.
Package com.google.android.webview doesn't update and stays at 55 version

**Comment by mykola-mokhnach** [comment]
> Downgrade the chromedriver version on appium to 2.28,
> Downgrade Chrome browser is updated to 55.0, this worked fine.
> This combination worked fine.

Then I assume the problem is fixed. Regarding webview update: it is compl;etely different topic, which have nothing to do with Appium itself. Please create a question on Appium forum or in google groups.
