### ISSUE TITLE
Method has not yet been implemented-dialogue box

### ISSUE THREAD

**Issue by netravm** [appium/appium#10831]
## The problem
   Not able to find the element from dialogue box using appium. but I could do same thing through selenium for web apps.

## Environment
* Appium version:  v1.6.5
* Desktop OS : windows 10
* Mobile platform/version under test: Android
* Real device
* Appium.app|exe: 
  It's Hybrid App

## Details
   driver.switchTo().activeElement();
  Thread.sleep(5000);
  try{
      Boolean isModal = 
      driver.findElement(By.xpath("/html/body/div[2]/div[2]/div/div/div/div/div/div/div"))
							.isDisplayed();
  }
 catch (Exception e) {
     System.out.println("No such element found: Catch");
      e.printStackTrace();
}

Below console error:

No such element found: Catch
org.openqa.selenium.WebDriverException: Method has not yet been implemented (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 33 milliseconds
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'LAPTOP-SNSNE9IB', ip: '192.168.0.140', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_102'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{appPackage=com.sadhana.smart_station2, deviceScreenSize=800x1280, networkConnectionEnabled=true, warnings={}, --session-override=true, databaseEnabled=false, deviceName=a4195b1c, version=7.7.1, platform=LINUX, deviceUDID=a4195b1c, appActivity=.MainActivity, desired={appPackage=com.sadhana.smart_station2, appActivity=.MainActivity, browserName=Android, --session-override=true, udid=a4195b1c, platformName=Android, deviceName=Galaxy Tab A(2017), version=7.7.1}, platformVersion=7.1.1, webStorageEnabled=false, locationContextEnabled=false, takesScreenshot=true, browserName=Android, javascriptEnabled=true, deviceModel=SM-T385, udid=a4195b1c, platformName=Android, deviceManufacturer=samsung}]
Session ID: 539c3186-aeb1-4638-a1e4-795b0fac3b8f
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:167)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:671)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteTargetLocator.window(RemoteWebDriver.java:991)
	at com.linkeztech.code.smartStation2.SmartStation2AppTest$1.run(SmartStation2AppTest.java:159)
	at java.lang.Thread.run(Thread.java:745)
isModal - false

## Appium logs
[appium.log](https://github.com/appium/appium/files/2084671/appium.log)

**Comment by mykola-mokhnach** [comment]
This is by design, since the idea of active element is not very clear on mobile because one cannot make elements focused there.

**Comment by netravm** [comment]
@mykola-mokhnach 
    So  how can I access element from modal/dialogue box in Tab?

set capability looks like below:
		capabilities.setCapability("deviceName", "Galaxy Tab A(2017)");
		capabilities.setCapability(CapabilityType.BROWSER_NAME, "Android");
		capabilities.setCapability(CapabilityType.VERSION, "7.7.1");
		capabilities.setCapability("udid", "a4195b1c");
		capabilities.setCapability("platformName", "Android");
		capabilities.setCapability("appPackage", "com.netra.myapp");
		capabilities.setCapability("appActivity", ".MainActivity");
		capabilities.setCapability("--session-override", true);

Please help me If you have any solution

**Comment by mykola-mokhnach** [comment]
In the same way you access other elements - locate it on the page.

**Comment by netravm** [comment]
Thank you for your quick reply...
I Got the element. but not able click on button in the modal.
There is no error.
I am using click function.

**Comment by mykola-mokhnach** [comment]
Try to switch to uiautomator2. If this does not help then click by coordinates.

**Comment by netravm** [comment]
uiautomator2 did not work..
If I click by coordinates by coordinates also not working.
I used below code:
`TouchAction action = new TouchAction(driver);
action.tap(90, 32).perform();`

**Comment by mykola-mokhnach** [comment]
Create an issue report to Google then.
