### ISSUE TITLE
appium-uiautomator2-server-v1.12.0.apk install fali after  upgrade appium to v1.8.1

### ISSUE THREAD

**Issue by WenRui13** [appium/appium#10852]
## The problem
New session can not be created after upgrade appium from v1.8.0-beta4 to 1.8.1, and get install appium-uiautomator2-server-v1.12.0.apk failure error.

## Environment

* Appium version (or git revision) that exhibits the issue:1.8.1
* Last Appium version that did not exhibit the issue (if applicable):1.8.0 beta4
* Desktop OS/version used to run Appium: Linux centOS
* Node.js version (unless using Appium.app|exe):v10.4.0
* Mobile platform/version under test:android 7.1.1
* Real device or emulator/simulator:real devices
* Appium CLI or Appium.app|exe:

## Link to Appium logs

[log](https://gist.github.com/WenRui13/305fca745cf8ad5e84d9c7708f5b325e)

**Comment by robin-xl** [comment]
you can try this step:
uninstall uia2
1、adb uninstall io.appium.uiautomator2.server
2、adb uninstall io.appium.uiautomator2.server.test
then make sure that you can install uia2 in termial

**Comment by WenRui13** [comment]
@robin-xl ,I do as you sey, the two package are not on the device,the result is bellow:
[root@localhost ~]# adb -H 10.1.64.43 -P 5037 -s 497590bb  uninstall io.appium.uiautomator2.server.test

Exception occurred while dumping:
java.lang.IllegalArgumentException: Unknown package: io.appium.uiautomator2.server.test
        at com.android.server.pm.Settings.isOrphaned(Settings.java:4282)
        at com.android.server.pm.PackageManagerService.isOrphaned(PackageManagerService.java:20752)
        at com.android.server.pm.PackageManagerService.deletePackage(PackageManagerService.java:17906)
        at com.android.server.pm.PackageInstallerService.uninstall(PackageInstallerService.java:888)
        at com.android.server.pm.PackageManagerShellCommand.runUninstall(PackageManagerShellCommand.java:797)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:123)
        at android.os.ShellCommand.exec(ShellCommand.java:94)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:21316)
        at android.os.Binder.shellCommand(Binder.java:468)
        at android.os.Binder.onTransact(Binder.java:367)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2607)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:3925)
        at android.os.Binder.transact(Binder.java:499)
        at oppo.x.filterExecTransact(Unknown Source)
        at com.oppo.color.safe.jni.JniManager.execTransact(Unknown Source)

[root@localhost ~]# adb -H 10.1.64.43 -P 5037 -s 497590bb  uninstall io.appium.uiautomator2.server.test

Exception occurred while dumping:
java.lang.IllegalArgumentException: Unknown package: io.appium.uiautomator2.server.test
        at com.android.server.pm.Settings.isOrphaned(Settings.java:4282)
        at com.android.server.pm.PackageManagerService.isOrphaned(PackageManagerService.java:20752)
        at com.android.server.pm.PackageManagerService.deletePackage(PackageManagerService.java:17906)
        at com.android.server.pm.PackageInstallerService.uninstall(PackageInstallerService.java:888)
        at com.android.server.pm.PackageManagerShellCommand.runUninstall(PackageManagerShellCommand.java:797)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:123)
        at android.os.ShellCommand.exec(ShellCommand.java:94)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:21316)
        at android.os.Binder.shellCommand(Binder.java:468)
        at android.os.Binder.onTransact(Binder.java:367)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2607)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:3925)
        at android.os.Binder.transact(Binder.java:499)
        at oppo.x.filterExecTransact(Unknown Source)
        at com.oppo.color.safe.jni.JniManager.execTransact(Unknown Source)


tks all the same.

**Comment by WenRui13** [comment]
oh, sorrry, it need to input password when install no-officify app on remote device, wait long to input password untill timeout , so the two packages about  uia2 install fail.

**Comment by JohnE4528** [comment]
wenrui13@, se me presento el mismo error y trato de realizar lo que mencionan atrás y no funciona. lo pudo solucionar. si lo realizo me puede indicar como lo realizo. gracias
