### ISSUE TITLE
'Cannot perform this action on a sealed instance' exception is thrown randomly when i call sendKeys()

### ISSUE THREAD

**Issue by JohnHuahuaZhan** [appium/appium#10861]
## environment
- appium (1.8.1)
- uiautomator2
- java client(6.0.0)
- windows 10

## log
```log
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: java.lang.IllegalStateException: Cannot perform this action on a sealed instance.
	at android.view.accessibility.AccessibilityNodeInfo.enforceNotSealed(AccessibilityNodeInfo.java:2956)
	at android.view.accessibility.AccessibilityNodeInfo.setConnectionId(AccessibilityNodeInfo.java:2839)
	at android.view.accessibility.AccessibilityInteractionClient.finalizeAndCacheAccessibilityNodeInfo(AccessibilityInteractionClient.java:703)
	at android.view.accessibility.AccessibilityInteractionClient.finalizeAndCacheAccessibilityNodeInfos(AccessibilityInteractionClient.java:721)
	at android.view.accessibility.AccessibilityInteractionClient.findAccessibilityNodeInfoByAccessibilityId(AccessibilityInteractionClient.java:293)
	at android.view.accessibility.AccessibilityInteractionClient.getRootInActiveWindow(AccessibilityInteractionClient.java:160)
	at android.app.UiAutomation.getRootInActiveWindow(UiAutomation.java:479)
	at android.support.test.uiautomator.UiAutomatorBridge.getRootInActiveWindow(UiAutomatorBridge.java:82)
	at android.support.test.uiautomator.QueryController.getRootNode(QueryController.java:170)
	at android.support.test.uiautomator.QueryController.findAccessibilityNodeInfo(QueryController.java:149)
	at android.support.test.uiautomator.QueryController.findAccessibilityNodeInfo(QueryController.java:138)
	at android.support.test.uiautomator.UiObject.findAccessibilityNodeInfo(UiObject.java:188)
	at android.support.test.uiautomator.UiObject.getText(UiObject.java:558)
	at io.appium.uiautomator2.model.UiObjectElement.getText(UiObjectElement.java:53)
	at io.appium.uiautomator2.handler.SendKeysToElement.isTextFieldClear(SendKeysToElement.java:47)
	at io.appium.uiautomator2.handler.SendKeysToElement.safeHandle(SendKeysToElement.java:88)
	at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:65)
	at io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:247)
	at io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:238)
	at io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:44)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:466)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:784)

Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
System info: host: 'DESKTOP-FLCQUDM', ip: '10.0.4.81', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_73'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {app: d:\DongFangHongReleaseOld.apk, appActivity: com.huored.android.lt.Welco..., appPackage: com.android.CzDongFangHong, appWaitActivity: com.huored.android.lt.Login..., appWaitPackage: com.android.CzDongFangHong, autoGrantPermissions: true, automationName: UIAutomator2, chromeDriverPort: 9515, databaseEnabled: false, desired: {app: d:\DongFangHongReleaseOld.apk, appActivity: com.huored.android.lt.Welco..., appPackage: com.android.CzDongFangHong, appWaitActivity: com.huored.android.lt.Login..., appWaitPackage: com.android.CzDongFangHong, autoGrantPermissions: true, automationName: UIAutomator2, chromeDriverPort: 9515, deviceName: huaweiHonor9-8.0, fullReset: false, newCommandTimeout: 300, noReset: false, platformName: android, resetKeyboard: true, systemPort: 8200, udid: 8BN0217826002935, unicodeKeyboard: true}, deviceApiLevel: 26, deviceManufacturer: HUAWEI, deviceModel: STF-AL00, deviceName: 8BN0217826002935, deviceScreenDensity: 480, deviceScreenSize: 1080x1920, deviceUDID: 8BN0217826002935, fullReset: false, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, newCommandTimeout: 300, noReset: false, pixelRatio: 3, platform: LINUX, platformName: LINUX, platformVersion: 8.0.0, resetKeyboard: true, statBarHeight: 72, systemPort: 8200, takesScreenshot: true, udid: 8BN0217826002935, unicodeKeyboard: true, viewportRect: {height: 1848, left: 0, top: 72, width: 1080}, warnings: {}, webStorageEnabled: false}
Session ID: e33eeb85-0d7c-43c7-93bf-bf4bf8035b07
```
## code
```java
CompatibleBy compatibleBy = new CompatibleBy(byType, by);
        MobileElement element = getTestContext().getAndroidElementHelper().find(getTestContext().getAndroidElementHelper().inputable(compatibleBy), false);
        getTestContext().getAndroidElementHelper().clear(element, false);
        element = getTestContext().getAndroidElementHelper().find(getTestContext().getAndroidElementHelper().inputable(compatibleBy), false);
        getTestContext().getAndroidElementHelper().input(element, content, false);
```
```java
 public MobileElement find(CompatibleBy by, boolean noWait){
        if(!noWait)
            return AndroidWaiter.waitElementVisible(driver, by.getBy(), pollingEvery, timeout);
        return driver.findElement(by.getBy());
    }
```
as you can see ,even i wait for the element preset and visible before i send keys to it, 'Cannot perform this action on a sealed instance' exception  is also thrown randomly

**Comment by mykola-mokhnach** [comment]
The exception is thrown by UIA2 framework itself, so there is not much that can be done from Appium side. Make sure the element you are trying to locate is the correct one. Try to add some timers there.

**Comment by JohnHuahuaZhan** [comment]
@mykola-mokhnach 
Thanks for your prompt reply! my locate is correct and the exception happens not very often。i will try to add timers .Thx

**Comment by bahunov** [comment]
You need to add extra implicit wait to get around this issue:
```
public void waitForElement(String elementId) {
        /*
        Appium driver bug causes IllegalStateException - hence this implementation
        https://github.com/appium/appium/issues/10861
         */
        try{
           maxWait.until(ExpectedConditions.visibilityOfElementLocated(By.id(elementId)));
        } catch (IllegalStateException ignored) {
            try {
                Thread.sleep(500);
            } catch (InterruptedException secondIgnored) {}
        }
    }
```

the you just go e.g:

```
waitForElement("elementId");
WebElement element =driver.findElement(By.id("elementId"));
element.click()
```

**Comment by bahunov** [comment]
Any update on this? I'm getting this randomly on real devices sometimes...
