### ISSUE TITLE
W3C Protocol expects any of script, pageload, or implicit to be set appium 1.8.1

### ISSUE THREAD

**Issue by rwilliamshgem** [appium/appium#10884]
## The problem

Just updated appium through npm to the latest version (1.8.1) from 1.7.1 and my automation is failing trying to set the implicit timeout wait.
 
## Environment

* Appium version (or git revision) that exhibits the issue: 3.0.0.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 1.8.1
* Node.js version (unless using Appium.app|exe): 8.11.0
* Mobile platform/version under test: Android 6/ios 11.4
* Real device or emulator/simulator: real-device
* Appium CLI or Appium.app|exe: appium cli

## Details

The exception given out is below:

OpenQA.Selenium.WebDriverException
  HResult=0x80131500
  Message=Parameters were incorrect. We wanted "W3C protocol expects any of script, pageLoad or implicit to be set" and you sent {"type":"implicit","ms":30000}
  Source=WebDriver
  StackTrace:
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteTimeouts.ExecuteSetTimeout(String timeoutType, TimeSpan timeToWait)
   at OpenQA.Selenium.Remote.RemoteTimeouts.set_ImplicitWait(TimeSpan value)
   at GemApp.ManagerApp.Tests.UI.SpecflowIoC.BeforeScenario() in C:\Projects\GemApp.ManagerApp-NetStandard\GemApp.ManagerApp.Tests.UI\SpecflowIoC.cs:line 46

## Link to Appium logs

[W3CProtocol.txt](https://github.com/appium/appium/files/2105871/W3CProtocol.txt)

## Code To Reproduce Issue [ Good To Have ]
*Create a AndroidDriver<AppiumWebElement>*
followed by line below
driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(30);

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/appium/appium-dotnet-driver
