### ISSUE TITLE
Can appium test a debugger version app or a app with lots of debug builds ?

### ISSUE THREAD

**Issue by lwb2001258** [appium/appium#10902]
## The problem

sometimes the appium scripts was stucked and without any error in the appium logs. The appium logs just stop and the scripts stop go on.  My question is whether the debug builds cause the problem? Can appium test a debugger version app or a app with lots of debug builds ? Would the debug builds effect the scripts.

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.5
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:win10
* Node.js version (unless using Appium.app|exe):8.4
* Mobile platform/version under test:android 7,api 24
* Real device or emulator/simulator:real device
* Appium CLI or Appium.app|exe:the appium was installed through npm

**Comment by mykola-mokhnach** [comment]
Do you use the most recent server version?
Do you have server/logcat logs?
Do you use uiautomator2 with Android 6+?

**Comment by lwb2001258** [comment]
Thank you for your reply. The appium version was 1.6.5/1.7.1, node version was 8.4.0,the uiautomator2 was used, the Android version was 7.0. And appium scripts run and stuck at the middle. Do you have any idea about that?
        the io.appium maven version was 5.0.4, and selenium maven version was 2.53.0, the attachment was the appium logs, it stucks at the last line of the logs.
[appium0620115115.txt](https://github.com/appium/appium/files/2117880/appium0620115115.txt)
@mykola-mokhnach

**Comment by lwb2001258** [comment]
The appium scripts was stuck sometimes at somewhere, It have bother me for a week and I can not solve it.

**Comment by lwb2001258** [comment]
sometimes the appium was stucked without error, sometimes the appium server would crash randomly with the error:
org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'DESKTOP-F6GLHCI', ip: '192.168.8.34', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_171'
Driver info: driver.version: AndroidDriver
Capabilities [{app=F:\appiumforone\A03APK\A03V2T.apk, appPackage=com.iteach.zed.a03, appActivity=com.iteach.zed.a03.activity.LoginActivity, noReset=true, noSign=true, newCommandTimeout=10000, automationName=UiAutomator2, unicodeKeyboard=true, platformName=Android, deviceName=huawei, resetKeyboard=true, platform=ANY}]
Session ID: 8d302ddc-85bd-4897-9515-a329ff80911f
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:665)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:43)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteTimeouts.implicitlyWait(RemoteWebDriver.java:865)
	at com.iteach.zed.a03.main.A03DataManager.dataCrashJiao(A03DataManager.java:270)
	at com.iteach.zed.a03.main.DataManagerTest.t_004_数据管理模块_数据碰撞交集测试(DataManagerTest.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.openqa.selenium.WebDriverException: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:4723 [/127.0.0.1] failed: Connection refused: connect
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'DESKTOP-F6GLHCI', ip: '192.168.8.34', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_171'
Driver info: driver.version: AndroidDriver
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:76)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:644)
	... 18 more
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:4723 [/127.0.0.1] failed: Connection refused: connect
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:144)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:90)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:64)
	... 19 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	... 32 more

**Comment by lwb2001258** [comment]
also several times the click() was done by the appium logs but it didn't done by the phone.

**Comment by lwb2001258** [comment]
my app have many debug builds so I think may be some problems in the app.

**Comment by mykola-mokhnach** [comment]
Can you also attach the logcat output for the moment when the freeze happens?

**Comment by lwb2001258** [comment]
the appium logs was 
[appium0621140424.txt](https://github.com/appium/appium/files/2122359/appium0621140424.txt)
the testng error was :
org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'DESKTOP-F6GLHCI', ip: '192.168.8.34', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_171'
Driver info: driver.version: AndroidDriver
Capabilities [{app=F:\appiumforone\A03APK\A03V2T.apk, appPackage=com.iteach.zed.a03, appActivity=com.iteach.zed.a03.activity.LoginActivity, noReset=true, noSign=true, newCommandTimeout=10000, automationName=UiAutomator2, unicodeKeyboard=true, platformName=Android, deviceName=huawei, resetKeyboard=true, platform=ANY}]
Session ID: 8d302ddc-85bd-4897-9515-a329ff80911f
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:665)
at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:43)
at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteTimeouts.implicitlyWait(RemoteWebDriver.java:865)
at com.iteach.zed.a03.main.A03DataManager.dataCrashJiao(A03DataManager.java:270)
at com.iteach.zed.a03.main.DataManagerTest.t_004_数据管理模块_数据碰撞交集测试(DataManagerTest.java:99)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: org.openqa.selenium.WebDriverException: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:4723 [/127.0.0.1] failed: Connection refused: connect
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'DESKTOP-F6GLHCI', ip: '192.168.8.34', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_171'
Driver info: driver.version: AndroidDriver
at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:76)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:644)
... 18 more
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:4723 [/127.0.0.1] failed: Connection refused: connect
at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158)
at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:144)
at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:90)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:64)
... 19 more
Caused by: java.net.ConnectException: Connection refused: connect
at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
at java.net.PlainSocketImpl.connect(Unknown Source)
at java.net.SocksSocketImpl.connect(Unknown Source)
at java.net.Socket.connect(Unknown Source)
at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
... 32 more

**Comment by mykola-mokhnach** [comment]
It is not what is needed. Logcat is the log of the device itself and can be collected by gathering the output of `adb logcat` command.

**Comment by lwb2001258** [comment]
[adblog.txt](https://github.com/appium/appium/files/2122514/adblog.txt)
Thank you for you reply. I adb logcat the logs and pls see the attachment. Before the computer unreach the phone we can see a lot of "system out" and other unknown character and the system output quit.
[adberrorlog.txt](https://github.com/appium/appium/files/2122520/adberrorlog.txt)
Before the remote device was died, the appium scripts tried to get the toast. If the scripts not tried to get the toast, the appium server would not crash. So I want to know whether my app causes the problem. Thank you!

**Comment by lwb2001258** [comment]
The following is the code. and it would not run error in the testng method but the next testng method would run error with "UnreachableBrowserException: Error communicating with the remote browser. It may have died" 	
public static void dataTransSeveralData(AndroidDriver<AndroidElement> driver) throws Exception {
		driver.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);
		dataTransWithoutData(driver);
		driver.findElement(By.xpath("//android.widget.ListView/android.widget.LinearLayout[1]/android.widget.CheckBox"))
				.click();
		WriteToTxt.logWriteToTxt(df.format(new Date()) + "   " + "选择第一个数据文件");
		driver.findElement(By.xpath("//android.widget.ListView/android.widget.LinearLayout[2]/android.widget.CheckBox"))
				.click();
		WriteToTxt.logWriteToTxt(df.format(new Date()) + "   " + "选择第二个数据文件");
		driver.findElement(By.id("com.iteach.zed.a03:id/btn_send")).click();
		WriteToTxt.logWriteToTxt(df.format(new Date()) + "   " + "点击发送按钮");
		driver.findElement(By.id("com.iteach.zed.a03:id/email_contact")).clear();
		driver.findElement(By.id("com.iteach.zed.a03:id/email_contact")).sendKeys("1wb444@163.com");
		WriteToTxt.logWriteToTxt(df.format(new Date()) + "   " + "输入邮箱地址");
		driver.findElement(By.id("com.iteach.zed.a03:id/btn_ok")).click();
		WriteToTxt.logWriteToTxt(df.format(new Date()) + "   " + "点击发送");
		boolean flag = false;
		String key = "正在发送";
		try {
			WebDriverWait wait = new WebDriverWait(driver, 15);
			WebElement target = wait
					.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//*[contains(@text,'" + key + "')]")));
			WriteToTxt.logWriteToTxt(df.format(new Date()) + "   " + "出现正在发送的提示");
			flag = true;
			System.out.println("Toast:" + target.getText());
		} catch (Exception e) {
			e.printStackTrace();
		}

		Assert.assertTrue(flag == true);
		Thread.sleep(30000);
	}

**Comment by mykola-mokhnach** [comment]
I think you just don't use it properly. There is a separate API for checking toasts. Look though previous messages of discuss.appium.io
