### ISSUE TITLE
iOS : Webview elements are not found by Appium

### ISSUE THREAD

**Issue by varunpandurangi** [appium/appium#10904]
## The problem

Ours is a hybrid app , Native part works well and when it switches to Webview , Appium struggles to identify the elements [ I am using id's ,not xpath] . Some times it does identify the webview elements but executes the commands dead slow with long pauses between each action. Not sure what's the reason ?

## Environment

* Appium version : 1.8.1 [Even tried with 1.8.2-beta ,same issues exists]
* Desktop OS/version used to run Appium: MAC 10.13.5
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iPhone 6 [11.4]
* Real device or emulator/simulator: Real device
*ios-webkit-debug-proxy  - 1.8
*libimobiledevice-1.2.0_2

## Link to Appium logs
https://gist.github.com/varunpandurangi/361ecd16a2fb23ec51f69bb56ef54b55

**Comment by mykola-mokhnach** [comment]
Make sure IWDP component is up to date. Also verify implicit waits. It is recommended to set them to zero.

**Comment by mykola-mokhnach** [comment]
Make sure the version of `appium-remote-debugger` lib is 3.12.0 or greater. Reinstall your beta if it is lower than that

**Comment by varunpandurangi** [comment]
OK, But when I did that . I get a different error now - it fails to  process the capabilities with below error : 

java.lang.NoSuchMethodError: org.openqa.selenium.json.JsonOutput.write(Ljava/lang/Object;)Lorg/openqa/selenium/json/JsonOutput;
	at io.appium.java_client.remote.NewAppiumSessionPayload.writeTo(NewAppiumSessionPayload.java:265)
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:162)
	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:196)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:218)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:209)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:132)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:84)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:94)
	at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:90)
	at Factory.DriverFactory.generateDriver(DriverFactory.java:67)
	at base.BaseTest.setUp(BaseTest.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:169)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
	Suppressed: java.io.IOException: Incomplete document
		at com.google.gson.stream.JsonWriter.close(JsonWriter.java:559)
		at org.openqa.selenium.json.JsonOutput.close(JsonOutput.java:39)
		at io.appium.java_client.remote.NewAppiumSessionPayload.writeTo(NewAppiumSessionPayload.java:288)
		... 40 more

**Comment by mykola-mokhnach** [comment]
It is a problem with your client (probably some dependencies are missing) and has nothing to do with the server.

**Comment by varunpandurangi** [comment]
OK. Thanks @mykola-mokhnach  , Will Log an issue with  Appium/JavaClient . Looks like a compatibility issue with the latest java client [3.12.0] .

**Comment by mykola-mokhnach** [comment]
I assume we can close this one then.
