### ISSUE TITLE
Original error: pageElementJSON.filter is not a function

### ISSUE THREAD

**Issue by JohnHuahuaZhan** [appium/appium#10926]
## The problem

appium server was on the mac device.java client was running at linux platform. ". Original error: pageElementJSON.filter is not a function" exception was thrown when i tried to call driver.getContextHandles().

## Environment

* Appium version (or git revision) that exhibits the issue:1.8.1
* Desktop OS/version used to run Appium:mac os 10.13.5
* Node.js version (unless using Appium.app|exe):8.11.2
* Mobile platform/version under test:ios10.3.3
* Real device or emulator/simulator:real device
* IWDP version:1.8

## Link to Appium logs

```
[debug] [RemoteDebugger] Page element JSON: {"value":"Unhandled endpoint: /json -- http://localhost:27753/ with parameters {\n    wildcards =     (\n        json\n    );\n}","sessionId":"08F5379D-37AF-4882-A26A-D2619959B6EC","status":1}
[W3C] Encountered internal error running command: TypeError: pageElementJSON.filter is not a function
[W3C]     at WebKitRemoteDebugger.pageArrayFromJson$ (/usr/local/lib/node_modules/appium/node_modules/appium-remote-debugger/lib/webkit-remote-debugger.js:61:40)
[W3C]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[W3C]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[W3C]     at <anonymous>
[HTTP] <-- GET /wd/hub/session/f017a4f7-18c2-4fe4-97c4-650d456e5395/contexts 500 14 ms - 1164
[HTTP] 
[HTTP] --> DELETE /wd/hub/session/f017a4f7-18c2-4fe4-97c4-650d456e5395
[HTTP] {}
```

## Code To Reproduce Issue [ Good To Have ]
```java
capabilities.setCapability(IOSMobileCapabilityType.START_IWDP, true);
  capabilities.setCapability("webkitDebugProxyPort", 27753);
            driver = new IOSDriver<>(new URL("http://192.168.31.191:4723/wd/hub"), capabilities);
           System.out.println(driver.getContextHandles());
```

## stack trace
```
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: pageElementJSON.filter is not a function
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'caihua-PC', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-21deepin-generic', java.version: '1.8.0_172'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities {app: /Users/caihua/Desktop/xjq3...., automationName: XCuiTest, browserName: , commandTimeouts: {default: 16000, findElement: 8000, findElements: 15000, setValue: 8000}, databaseEnabled: false, deviceName: ipad, fullReset: false, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: false, newCommandTimeout: 600, noReset: true, platform: MAC, platformName: iOS, platformVersion: 11.3.1, showXcodeLog: false, startIWDP: true, takesScreenshot: true, udid: 0c518faa3c350226439b1a7f929..., updatedWDABundleId: com.minglin.appium.ios, wdaConnectionTimeout: 60000, wdaLaunchTimeout: 60000, wdaLocalPort: 27753, wdaStartupRetries: 3, wdaStartupRetryInterval: 6000, webStorageEnabled: false, xcodeOrgId: S4LAW85QU6, xcodeSigningId: iPhone Developer}
Session ID: f017a4f7-18c2-4fe4-97c4-650d456e5395
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:231)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:46)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at io.appium.java_client.AppiumDriver.getContextHandles(AppiumDriver.java:206)
	at ios_appium.App.main(App.java:66)
```

**Comment by mykola-mokhnach** [comment]
@imurchie FYI

**Comment by mykola-mokhnach** [comment]
@JohnHuahuaZhan What if you put a breakpoint there and try to open `http://localhost:27753/` and `http://localhost:27753/json` in browser? What output do you see there?

**Comment by mykola-mokhnach** [comment]
Are you sure that IWDP is started properly on that port and works? Otherwise the response does not look good. Perhaps, you have some unexpected port forwarding or proxying enabled on that machine?

**Comment by JohnHuahuaZhan** [comment]
@mykola-mokhnach 
thank you so much.i used another port and it worked
