### ISSUE TITLE
UiAutomator2 capability is not working: org.openqa.selenium.InvalidArgumentException: 'systemPort' must be of type number

### ISSUE THREAD

**Issue by aksenov007** [appium/appium#10930]
## The problem

Impossible to use Android capability `systemPort` because of: org.openqa.selenium.InvalidArgumentException: 'systemPort' must be of type number

## Environment

* Appium version: 1.8.2-beta (using 1.8.1 is not possible to set implicit timeout so I used
* Appium base driver version: 2.32.2
* Last Appium version that did not exhibit the issue (if applicable): 1.7.2
* Desktop OS/version used to run Appium: Windows 10
* Mobile platform/version under test: Android
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: just ran the command `appium` without any additional arguments

## Details

Caused by: org.openqa.selenium.InvalidArgumentException: 'systemPort' must be of type number
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'SAZONOVPC', ip: '10.110.5.146', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_172'
Driver info: driver.version: AndroidDriver
remote stacktrace: InvalidArgumentError: 'systemPort' must be of type number
    at validateCaps (C:\Users\Jenkins\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\capabilities.js:52:11)
    at parseCaps (C:\Users\Jenkins\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\capabilities.js:154:20)
    at processCapabilities (C:\Users\Jenkins\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\capabilities.js:197:43)
    at AndroidUiautomator2Driver.callee$0$0$ (C:\Users\Jenkins\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\commands\session.js:36:14)
    at tryCatch (C:\Users\Jenkins\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\Jenkins\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\Jenkins\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at invoke (C:\Users\Jenkins\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at enqueueResult (C:\Users\Jenkins\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:185:17)
    at new Promise (<anonymous>)
    at new F (C:\Users\Jenkins\AppData\Roaming\npm\node_modules\appium\node_modules\core-js\library\modules\$.export.js:30:36)
    at AsyncIterator.enqueue (C:\Users\Jenkins\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (C:\Users\Jenkins\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at Object.runtime.async (C:\Users\Jenkins\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:209:12)
    at AndroidUiautomator2Driver.callee$0$0 [as createSession] (C:\Users\Jenkins\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\build\lib\basedriver\commands\session.js:35:30)
    at AndroidUiautomator2Driver.createSession$ (C:\Users\Jenkins\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\driver.js:101:32)
    at tryCatch (C:\Users\Jenkins\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\Jenkins\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\Jenkins\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at invoke (C:\Users\Jenkins\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at enqueueResult (C:\Users\Jenkins\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:185:17)
    at new Promise (<anonymous>)
    at new F (C:\Users\Jenkins\AppData\Roaming\npm\node_modules\appium\node_modules\core-js\library\modules\$.export.js:30:36)
    at AsyncIterator.enqueue (C:\Users\Jenkins\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (C:\Users\Jenkins\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at Object.runtime.async (C:\Users\Jenkins\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:209:12)
    at AndroidUiautomator2Driver.createSession (C:\Users\Jenkins\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-driver\build\lib\driver.js:145:34)
    at AppiumDriver.callee$2$0$ (C:\Users\Jenkins\AppData\Roaming\npm\node_modules\appium\lib\appium.js:244:43)
    at tryCatch (C:\Users\Jenkins\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\Jenkins\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\Jenkins\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\Jenkins\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
	... 87 more

## Code To Reproduce Issue [ Good To Have ]

Provide the capability using Java variables, like this (look at the end of CLI):
java.exe -classpath c:\jenkins\tools\hudson.tasks.Maven_MavenInstallation\Maven_for_RTD_Android\boot\* -Dmaven.home=c:\jenkins\tools\hudson.tasks.Maven_MavenInstallation\Maven_for_RTD_Android -Dmaven.conf=c:\jenkins\tools\hudson.tasks.Maven_MavenInstallation\Maven_for_RTD_Android\conf -Dclassworlds.conf=c:\jenkins\tools\hudson.tasks.Maven_MavenInstallation\Maven_for_RTD_Android\bin\m2.conf -Dmaven.multiModuleProjectDirectory=c:\jenkins\workspace\qa_android org.codehaus.plexus.classworlds.launcher.Launcher -s C:\Users\Jenkins\.m2\settings.xml -pl android-acceptance integration-test post-integration-test -Dtest.env=test -Dupload.stubs=true "-Dcucumber.options=-t @RTDA-2" -Djavax.net.ssl.trustStore=C:\Users\Jenkins\ci_keystore -Dappium.app=c:\jenkins\workspace\qa_android\app-dev_test-release-signed.apk -Dappium.udid=WUJ01R4EKT **-Dappium.systemPort=8201**

**Comment by mykola-mokhnach** [comment]
Most likely this property is passed as a string, so you need to perform an explicit typecast before passing it to capabilities.

**Comment by aksenov007** [comment]
Of course, it's obvious. But using Appium 1.7.2 I could use the syntax like that: **-Dappium.systemPort=8201** and now it's broken. And I don't know how to provide this capability dynamically, having started instance of appium (so I can't use --default-capabilities).

**Comment by aksenov007** [comment]
> But I still don't get why the typecast cannot be done on the client side.

Because I just pass them from command line to Appium. And I don't know another way to provide `systemPort` capability value dynamically. If you know - please, tell me.

**Comment by thepoppingone** [comment]
```
[Appium] Creating new AndroidUiautomator2Driver (v1.19.0) session
[Appium] Capabilities:
[Appium]   platformName: Android
[Appium]   platformVersion: P
[Appium]   deviceName: Android-SDK-built-for-x86_1
[Appium]   udid: emulator-5554
[Appium]   systemPort: 8200
[Appium]   automationName: UiAutomator2
[Appium]   skipUnlock: true
[Appium]   app: app.apk
[Appium]   fullReset: true
[debug] [BaseDriver] W3C capabilities {"alwaysMatch":{"platformNa... and MJSONWP desired capabilities {"platformName":"Android","... were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"platformNa...
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1538019412503 (11:36:52 GMT+0800 (+08))
[debug] [W3C] Encountered internal error running command: InvalidArgumentError: 'systemPort' must be of type number
```
Any solutions to this similar issue?

**Comment by saikrishna321** [comment]
@thepoppingone Please provide the _systemPort_ as number.

Share your capabilties

**Comment by thepoppingone** [comment]
@saikrishna321 Thanks I have resolved the issue, the number was accidentally converted to string in the python library for Appium-Robotframework - had to overwrite the method and force the systemPort to be a number. 
```
desired_caps={}
    desired_caps['platformName'] = platform_name
    desired_caps['platformVersion'] = platform_version
    desired_caps['deviceName'] = device_name
    desired_caps['udid'] = udid
    desired_caps['systemPort'] = int(system_port)
```

**Comment by mykola-mokhnach** [comment]
The improvement has been published in appium@beta
