### ISSUE TITLE
java.lang.NoSuchMethodError: org.openqa.selenium.json.JsonOutput.write 

### ISSUE THREAD

**Issue by deepng** [appium/appium#10978]
## The problem

I get the error below. This error pop's up when trying to create a new Driver instance. 

```
java.lang.NoSuchMethodError: org.openqa.selenium.json.JsonOutput.write(Ljava/lang/Object;)Lorg/openqa/selenium/json/JsonOutput;

	at io.appium.java_client.remote.NewAppiumSessionPayload.writeTo(NewAppiumSessionPayload.java:265)
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:162)
	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:196)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:218)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:209)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:132)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:84)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:94)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:88)

```

## Environment

Appium 1.8.1. 
Running tests on Android.
pom.xml has just one external dependency.

<dependency>
            <groupId>io.appium</groupId>
            <artifactId>java-client</artifactId>
            <version>6.1.0</version>
        </dependency>
        <dependency>

## Details

This wasn't happening with the older Java-client version (5.4.0) that I had installed earlier.
I recently updated to Java-client 6.1.0 and this started showing up.

## Code To Reproduce Issue [ Good To Have ]

The code is below. The one extra capability is APP_WAIT_ACTIVITY.

     ```
        DesiredCapabilities capabilities = new DesiredCapabilities();
           capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, appConfig.getDeviceName());
                capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, appConfig.getPlatformVersion());
                capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, appConfig.getPlatformName());
                capabilities.setCapability(AndroidMobileCapabilityType.APP_PACKAGE, appConfig.getPackageName());
                capabilities.setCapability(AndroidMobileCapabilityType.APP_ACTIVITY, appConfig.getLaunchActivity());
                capabilities.setCapability(AndroidMobileCapabilityType.APP_WAIT_ACTIVITY, appConfig.getWaitActivity());
       AppiumDriver<MobileElement> driver = new AndroidDriver<>(new URL(url), capabilities);

```

**Comment by email2vimalraj** [comment]
@deepng : This look like a java-client issue. Kindly open this issue in the java-client repo.

**Comment by deepng** [comment]
ok.
