### ISSUE TITLE
Getting Webdriver exception while having comma in the text

### ISSUE THREAD

**Issue by arjungovindgv** [appium/appium#10997]
While using the command 
		findElementByAndroidUIAutomator("new UiScrollable(new UiSelector().resourceId(\"com.**.android:id/text\").instance(0)).setAsHorizontalList().scrollIntoView(new UiSelector().textContains(\""+"sum, average"+"\").instance(0))");		
If I remove the comma since its a text contain, its working fine.

the text -  sum, average having comma giving webdriver exception.
org.openqa.selenium.WebDriverException: Returned value cannot be converted to WebElement: new UiScrollable(new UiSelector().resourceId("com.***.android:id/text").instance(0)).setAsHorizontalList().scrollIntoView(new UiSelector().textContains("Sum, average and lookup, all without a hiccup.").instance(0))
Build info: version: '3.9.0', revision: '698b3178f0', time: '2018-02-05T14:56:13.134Z'
System info: host: 'user', ip: 'fe80:0:0:0:c5b:efc6:91d6:5d00%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.3', java.version: '1.8.0_77'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.RemoteWebElement.findElement(RemoteWebElement.java:187)
	at io.appium.java_client.DefaultGenericMobileElement.findElement(DefaultGenericMobileElement.java:65)
	at io.appium.java_client.MobileElement.findElement(MobileElement.java:1)
	at io.appium.java_client.android.AndroidElement.findElement(AndroidElement.java:1)
	at io.appium.java_client.FindsByAndroidUIAutomator.findElementByAndroidUIAutomator(FindsByAndroidUIAutomator.java:32)
	at com.adventnet.sheet.MobileAutomation.pagelisteners.impl.WalkthroughPageImpl.navigation(WalkthroughPageImpl.java:96)
	at com.adventnet.sheet.MobileAutomation.pagelisteners.impl.WalkthroughPageImpl.executeActionCases(WalkthroughPageImpl.java:47)
	at com.adventnet.sheet.MobileAutomation.pagelisteners.impl.WalkthroughPageImpl.<init>(WalkthroughPageImpl.java:33)
	at com.adventnet.sheet.MobileAutomation.Lander.launchAutomator(Lander.java:64)
	at com.adventnet.sheet.MobileAutomation.Lander.launchAndroidAutomator(Lander.java:91)
	at com.adventnet.sheet.MobileAutomation.Lander.main(Lander.java:121)
Caused by: java.lang.ClassCastException: com.google.common.collect.Maps$TransformedEntriesMap cannot be cast to org.openqa.selenium.WebElement
	at org.openqa.selenium.remote.RemoteWebElement.findElement(RemoteWebElement.java:185)
	... 10 more

**Comment by mykola-mokhnach** [comment]
Can you attach full server log?

**Comment by arjungovindgv** [comment]
[appium-server-logs.txt](https://github.com/appium/appium/files/2165796/appium-server-logs.txt)
If Removed comma from text, its working fine

**Comment by mykola-mokhnach** [comment]
Switch to uiautomator2

**Comment by arjungovindgv** [comment]
is there any documentation on that ? how to switch

**Comment by mykola-mokhnach** [comment]
http://appium.io/docs/en/drivers/android-uiautomator2/index.html

**Comment by arjungovindgv** [comment]
[appium-server-logs.txt](https://github.com/appium/appium/files/2166050/appium-server-logs.txt)
can't start session from uiAutomator2

**Comment by mykola-mokhnach** [comment]
Try to reset the device. logcat output might contain more information about why the crash has happened

**Comment by arjungovindgv** [comment]
[appium-server-logs.txt](https://github.com/appium/appium/files/2166460/appium-server-logs.txt)
When I tried that after app launch nothing happening...even log also not running

**Comment by arjungovindgv** [comment]
@mykola-mokhnach Any update ?

**Comment by imurchie** [comment]
I have a fix in the works. https://github.com/appium/appium-android-bootstrap/pull/62
