### ISSUE TITLE
iOS tests became fail after updating Appium to Version 1.8.2-beta

### ISSUE THREAD

**Issue by mihmonah** [appium/appium#11029]
## The problem

After update to new macOS Mojave, Xcode 10 and Appium 1.8.2-beta for trying parallel execution of iOS tests, tests which were passed become failed. One of maintainers of Appium python-client said that it is server problem, and sent me here. 

## Environment

* Appium version is 1.8.2-beta. Command for run was:
`appium --port=4723 --callback-port=4723 >> /dev/null `
* Last Appium version that did not exhibit the issue is 1.8.1
* Desktop OS is macOS Mojave Version 10.14 Beta (18A326g)
* Node.js version v8.11.1
* `desired_capabilities` of simulator are next:
```
{
  'app': '/path_to_app/myapp.app',
  'automationName': 'XCUITest',
  'deviceName': 'iPhone 7',
  'fullReset': True,
  'platformName': 'iOS',
  'platformVersion': '12.0',
  'udid': '$UDID',
  'updatedWDABundleId': 'us.project.WebDriverAgentRunner',
  'wdaLocalPort': '8100',
  'xcodeOrgId': '$ORG_ID',
  'xcodeSigningId': '$SIGNING_ID'
}
```
* Appium CLI or Appium.app is Version 1.6.2.

## Details

After running my tests with `py.test` (Python 3.6.1rc1, pytest-3.6.1) I got next fail for environment from above:

`ios_tests/tests/test_send_message.py::test_send_message [XCUITest] Error: Command 'osascript -e 'tell application "System Events" to count processes whose bundle identifier is "com.apple.iphonesimulator"'' exited with code 1
[XCUITest]     at ChildProcess.<anonymous> (/Users/mikhailmonakhov/.nvm/versions/node/v8.11.1/lib/node_modules/appium/node_modules/teen_process/lib/exec.js:94:19)
[XCUITest]     at emitTwo (events.js:126:13)
[XCUITest]     at ChildProcess.emit (events.js:214:7)
[XCUITest]     at maybeClose (internal/child_process.js:925:16)
[XCUITest]     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
[MJSONWP]` **Encountered internal error running command: Error: Command 'osascript -e 'tell application "System Events" to count processes whose bundle identifier is "com.apple.iphonesimulator"'' exited with code 1**
`[MJSONWP]     at ChildProcess.<anonymous> (/Users/mikhailmonakhov/.nvm/versions/node/v8.11.1/lib/node_modules/appium/node_modules/teen_process/lib/exec.js:94:19)
[MJSONWP]     at emitTwo (events.js:126:13)
[MJSONWP]     at ChildProcess.emit (events.js:214:7)
[MJSONWP]     at maybeClose (internal/child_process.js:925:16)
[MJSONWP]     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)`
**ERROR**

## Link to Appium logs

Link to logs is [here](https://gist.github.com/mihmonah/6c5709601f15ab5f177e30d912293077).

## Some additional info

In my case, only macOS, Appium and Xcode versions were changed, so before these changes all worked good. If some new option for parallel Appium execution after building with Xcode flags `-parallel-testing-enabled YES -maximum-concurrent-test-simulator-destinations 2 -parallel-testing-worker-count 2` are existed, it will great to see some tutorial for this.

**Comment by mykola-mokhnach** [comment]
I think this is know Mojave [restriction](https://stackoverflow.com/questions/51299066/macos-mojave-automator-not-authorized-to-send-apple-events-to-system-events). Try to downgrade the operating system.

**Comment by mihmonah** [comment]
But the main purpose to install Mojave was to try native parallel instruments. :(
Will the desktop version of Appium get the Beta release for Xcode 10 soon? Privacy allows the desktop version to operate with Systems Events (see attached screenshot).

![screenshot 2018-07-12 at 21 11 57](https://user-images.githubusercontent.com/5685937/42651741-f4c3dd72-8618-11e8-8495-57a8b504119a.png)

**Comment by mykola-mokhnach** [comment]
Try to execute the server from Terminal.app and give the Terminal necessary permissions. If this does not help then you are welcome to provide a better workaround.

**Comment by mihmonah** [comment]
I couldn't do it, cause it is about Apple events to System Events permission, and I can give only panel asking permission, which doesn't call for this. There is an [article ](https://www.felix-schwarz.org/blog/2018/06/apple-event-sandboxing-in-macos-mojave) about this problem, so I need the application (such as desktop Appium) to give necessary permissions. Can you help me to upgrade my desktop Appium to beta version? Because I can't give permission to terminal server now.

**Comment by mykola-mokhnach** [comment]
I have added a workaround to the apple script usage there. Instal appium@beta and try again.

**Comment by mihmonah** [comment]
I reinstalled appium:
```
$ appium -v
1.8.2-beta
```
and get the same error:
`E       selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Command 'osascript -e 'tell application "System Events" to count processes whose bundle identifier is "com.apple.iphonesimulator"'' exited with code 1`

Looks like nothing is changed. :(

**Comment by mykola-mokhnach** [comment]
Make sure the version of appium-ios-simulator component is at 2.14.2

**Comment by mihmonah** [comment]
The output of command `$ npm -g ls appium-ios-simulator` is next:
```
/Users/mikhailmonakhov/.nvm/versions/node/v9.11.2/lib
├─┬ appium@1.8.2-beta
│ ├─┬ appium-ios-driver@2.5.0
│ │ └── appium-ios-simulator@3.0.0 
│ └─┬ appium-xcuitest-driver@2.87.0
│   └── appium-ios-simulator@3.0.0  deduped
└── appium-ios-simulator@3.0.0 
```

**Comment by mykola-mokhnach** [comment]
Version 3.0.0 of this module does not exist: https://github.com/appium/appium-ios-simulator/commits/master

**Comment by mihmonah** [comment]
I reinstalled it, now the output is next:
```
/Users/mikhailmonakhov/.nvm/versions/node/v9.11.2/lib
├─┬ appium@1.8.2-beta
│ ├─┬ appium-ios-driver@2.5.0
│ │ └── appium-ios-simulator@3.0.0 
│ └─┬ appium-xcuitest-driver@2.87.0
│   └── appium-ios-simulator@3.0.0  deduped
└── appium-ios-simulator@2.14.2 
```
Still failing

**Comment by mihmonah** [comment]
I did
```
npm -g remove appium
npm -g remove appium@beta
```
and after
`npm -g install appium@beta`
After that I run appium from terminal via:
`appium --log appium_debug_logs --show-ios-log > appium_logs &`
and run my test. Current output of `npm -g ls appium-ios-simulator` is 
```
/Users/mikhailmonakhov/.nvm/versions/node/v9.11.2/lib
├─┬ appium@1.8.2-beta
│ ├─┬ appium-ios-driver@2.5.1
│ │ └── appium-ios-simulator@3.0.0 
│ └─┬ appium-xcuitest-driver@2.87.0
│   └── appium-ios-simulator@3.0.0  deduped
└── appium-ios-simulator@2.14.2 
```
So, current version of `appium-ios-simulator` is 2.14.2. Test is failed with error from above, in addition, the simulator did not even start (like in all previous attempts).

**Comment by mykola-mokhnach** [comment]
Can you attach the new log?

**Comment by mihmonah** [comment]
Of course ([gist](https://gist.github.com/mihmonah/b9bc8a4957c7d117045289f55270c15a)), but it looks like same error.

**Comment by mihmonah** [comment]
I did it by your advice:
`npm -g uninstall appium && npm -g install appium@beta --no-shrinkwrap`
but nothing is changed.

**Comment by mykola-mokhnach** [comment]
I don't have any other ideas. Try to debug it locally. This is the [PR](url
https://github.com/appium/appium-ios-simulator/pull/162), that was done in order to workaround the problem.

**Comment by akhand-pratap2807** [comment]
@mihmonah could you please give little idea about how did you have implemented parallel execution?

**Comment by janvennemann** [comment]
@mykola-mokhnach I'm also experiencing the same issue and i have a feeling there is a version mixup here. `appium-ios-simulator` has a version 3.0.0 from two months ago: https://www.npmjs.com/package/appium-ios-simulator/v/3.0.0. This version is also referenced in [appium-xcuitest-driver](https://github.com/appium/appium-xcuitest-driver/blob/master/package.json#L32) and [appium-ios-driver](https://github.com/appium/appium-ios-driver/blob/master/package.json#L32). So the patch for this issue released in version 2.4.12 wont be picked up.

**Comment by mykola-mokhnach** [comment]
@imurchie Do you know why npm version could be 3.0.0?

**Comment by janvennemann** [comment]
Thanks a lot, iOS tests on Mojave are working again for me after installing the latest appium@beta 👍

**Comment by thutran01** [comment]
@janvennemann Hi, I am using mojave os but I can not install app if i use `driver.installApp(path)`.
The log was:
XCUITest] Installing '/Users/thutran/sojo-automation-ios/src/test/resources/apps/SojoTravel.app' to the Simulator with UDID 5469F39D-1FAF-4D34-A41A-1424439A9DF5
[simctl] Error: simctl error running 'install': An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=1):
[simctl] This app could not be installed at this time.
Can you give me some suggestion to fix this issue?
any way my english is not good so sorry about it.
