### ISSUE TITLE
TypeError: Cannot read property 'count' of undefined while quitting driver 

### ISSUE THREAD

**Issue by mayureshshirodkar** [appium/appium#11048]
## The problem

I am trying to run Android and Selenium in parallel using TestNG. The Tests run fine and all the commands are being executed. But while quitting the iOS driver(first driver), there is the count  undefined error, while Android driver quits fine

## Environment

* Appium version (or git revision) that exhibits the issue: Appium v1.8.2-beta
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS 10.13.5
* Mobile platform/version under test: iOS 11.4
* Real device or emulator/simulator: Iphone 6

## Link to Appium logs

```
2018-07-16 12:27:48:382 - [HTTP] --> DELETE /wd/hub/session/b207d532-b6c4-43cc-95dc-497c469eded7
2018-07-16 12:27:48:383 - [HTTP] {}
2018-07-16 12:27:48:383 - [debug] [W3C] Calling AppiumDriver.deleteSession() with args: ["b207d532-b6c4-43cc-95dc-497c469eded7"]
2018-07-16 12:27:48:383 - [debug] [BaseDriver] Event 'quitSessionRequested' logged at 1531744068383 (17:57:48 GMT+0530 (IST))
2018-07-16 12:27:48:383 - [Appium] Removing session b207d532-b6c4-43cc-95dc-497c469eded7 from our master session list
2018-07-16 12:27:48:384 - [debug] [JSONWP Proxy] Proxying [DELETE /session/b207d532-b6c4-43cc-95dc-497c469eded7] to [DELETE http://localhost:8100/session/78370767-67D5-4727-B831-A33D837699E4] with no body
2018-07-16 12:27:48:395 - [Xcode]     t =  4523.96s Terminate com.eab.se:326
2018-07-16 12:27:48:395 - [Xcode] 
2018-07-16 12:27:48:888 - [debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n\n  },\n  \"sessionId\" : \"DA6417E4-C46F-41A6-9ECD-DB69096B0BC2\",\n  \"status\" : 0\n}"
2018-07-16 12:27:48:952 - [debug] [XCUITest] Started background XCTest logs cleanup: find -E /private/var/folders -regex '.*/Session-WebDriverAgentRunner.*\.log$|.*/StandardOutputAndStandardError\.txt$' -type f -exec sh -c 'echo "" > "{}"' \;
2018-07-16 12:27:48:953 - [XCUITest] Cleaning test logs in '/Users/shirodkm/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs' folder
2018-07-16 12:27:48:953 - [debug] [iOS] Clearing log files
2018-07-16 12:27:48:957 - [debug] [iOS] Deleting '/Users/shirodkm/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs'. Freeing 8.0K.
2018-07-16 12:27:48:959 - [debug] [iOS] Finished clearing log files
2018-07-16 12:27:48:960 - [debug] [XCUITest] In a web session. Removing remote debugger
2018-07-16 12:27:48:960 - [debug] [RemoteDebugger] Disconnecting from WebKit remote debugger
2018-07-16 12:27:48:960 - [Appium] Had trouble ending session b207d532-b6c4-43cc-95dc-497c469eded7: Cannot read property 'count' of undefined
2018-07-16 12:27:48:960 - [debug] [BaseDriver] Event 'quitSessionFinished' logged at 1531744068960 (17:57:48 GMT+0530 (IST))
2018-07-16 12:27:48:961 - [MJSONWP] Encountered internal error running command: TypeError: Cannot read property 'count' of undefined
2018-07-16 12:27:48:962 - [MJSONWP]     at IOSLog.stopCapture$ (/usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/lib/device-log/ios-log.js:213:9)
2018-07-16 12:27:48:962 - [MJSONWP]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
2018-07-16 12:27:48:962 - [MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
2018-07-16 12:27:48:962 - [MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
2018-07-16 12:27:48:962 - [MJSONWP]     at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
2018-07-16 12:27:48:962 - [MJSONWP]     at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
2018-07-16 12:27:48:962 - [MJSONWP]     at new Promise (<anonymous>)
2018-07-16 12:27:48:962 - [MJSONWP]     at new F (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
2018-07-16 12:27:48:962 - [MJSONWP]     at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
2018-07-16 12:27:48:962 - [MJSONWP]     at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
2018-07-16 12:27:48:962 - [MJSONWP]     at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
2018-07-16 12:27:48:962 - [MJSONWP]     at IOSLog.stopCapture (/usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/build/lib/device-log/ios-log.js:514:34)
2018-07-16 12:27:48:962 - [MJSONWP]     at XCUITestDriver.deleteSession$ (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:550:30)
2018-07-16 12:27:48:962 - [MJSONWP]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
2018-07-16 12:27:48:963 - [MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
2018-07-16 12:27:48:963 - [MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
2018-07-16 12:27:48:963 - [MJSONWP]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
2018-07-16 12:27:48:963 - [MJSONWP]     at <anonymous>
2018-07-16 12:27:48:964 - [HTTP] <-- DELETE /wd/hub/session/b207d532-b6c4-43cc-95dc-497c469eded7 500 581 ms - 212
```

## Code To Reproduce Issue [ Good To Have ]
Error occurs on executing driver.quit().

**Comment by imurchie** [comment]
Thanks for this report. I can see where the problem lies, and will work on a fix.

**Comment by imurchie** [comment]
Can you try the latest beta of Appium (`npm uninstall -g appium && npm install -g appium@beta --no-shrinkwrap`)? This ought to be fixed.

**Comment by mayureshshirodkar** [comment]
Check the latest beta and yes the issue is resolved. Thanks @imurchie for the quick fix.
