### ISSUE TITLE
Encountered internal error running command: Error: Command 'java' not found. Is it installed?

### ISSUE THREAD

**Issue by MeiJunZhang** [appium/appium#11059]
## The problem
When Execution code:
`driver = new RemoteWebDriver(new Uri("http://127.0.0.1:4723/wd/hub"), capabilities); ` prompt "Encountered internal error running command: Error: Command 'java' not found. Is it installed? ",I use appium-dotnet-driver (version:3.0.0.2) as client.
Full Code:
` var capabilities = new DesiredCapabilities(); capabilities.SetCapability(MobileCapabilityType.PlatformName, PlatformType.Android);
capabilities.SetCapability(MobileCapabilityType.DeviceName, "127.0.0.1:62001");
capabilities.SetCapability(MobileCapabilityType.App, @"D:\sogou.mobile.explorer_5.13.5_154189.apk");
capabilities.SetCapability(AndroidMobileCapabilityType.AppPackage, "sogou.mobile.explorer");
capabilities.SetCapability(AndroidMobileCapabilityType.AppActivity,"sogou.mobile.explorer.BrowserActivity");
driver = new RemoteWebDriver(new Uri("http://127.0.0.1:4723/wd/hub"), capabilities);`

## Environment

* Appium version (or git revision) that exhibits the issue:V1.8.1
* Desktop OS/version used to run Appium:1.6.2
* Mobile platform/version under test:7.0
* Real device or emulator/simulator:emulator
* Appium CLI or Appium.app|exe:Appium.exe

## Details

I used the appium-Desktop.exe (version:1.4.6) program to run normally, but when I update appium-Desktop.exe to 1.6.2, the program throws out "Encountered internal error running command: Error: Command'java'." please note that the code does not make any changes, I do not know what is Why, the trouble to reply, thank you!

## Link to Appium logs

[Appium] Welcome to Appium v1.8.1
[Appium] Non-default server args:
[Appium]   address: 127.0.0.1
[Appium]   sessionOverride: true
[Appium] Appium REST http interface listener started on 127.0.0.1:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"capabilities":{"alwaysMatch":{"appium:deviceName":"127.0.0.1:62001","appium:appActivity":"com.android.browser.BrowserActivity","platformName":"Android","appium:appPackage":"com.android.browser","appium:platformVersion":"4.4.2"},"firstMatch":[{}]},"desiredCapabilities":{"platformVersion":"4.4.2","deviceName":"127.0.0.1:62001","platformName":"Android","appActivity":"com.android.browser.BrowserActivity","appPackage":"com.android.browser"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformVersion":"4.4.2","deviceName":"127.0.0.1:62001","platformName":"Android","appActivity":"com.android.browser.BrowserActivity","appPackage":"com.android.browser"},null,{"alwaysMatch":{"appium:deviceName":"127.0.0.1:62001","appium:appActivity":"com.android.browser.BrowserActivity","platformName":"Android","appium:appPackage":"com.android.browser","appium:platformVersion":"4.4.2"},"firstMatch":[{}]}]
[BaseDriver] Event 'newSessionRequested' logged at 1531830995911 (20:36:35 GMT+0800 (中国标准时间))
[Appium] Creating new AndroidDriver (v2.7.0) session
[Appium] Capabilities:
[Appium]   platformName: Android
[Appium]   deviceName: 127.0.0.1:62001
[Appium]   appActivity: com.android.browser.BrowserActivity
[Appium]   appPackage: com.android.browser
[Appium]   platformVersion: 4.4.2
[BaseDriver] W3C capabilities {"alwaysMatch":{"platformNa... and MJSONWP desired capabilities [object Object] were provided
[BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"platformNa...
[BaseDriver] Session created with session id: 84c38c27-b2db-41f8-b94f-c3db60e4af14
[AndroidDriver] Getting Java version
[AndroidDriver] Shutting down Android driver
[AndroidDriver] Called deleteSession but bootstrap wasn't active
[BaseDriver] Event 'newSessionStarted' logged at 1531830995923 (20:36:35 GMT+0800 (中国标准时间))
**[W3C] Encountered internal error running command: Error: Command 'java' not found. Is it installed?**
[W3C]     at ChildProcess. (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\teen_process\lib\exec.js:39:14)
[W3C]     at emitOne (events.js:116:13)
[W3C]     at ChildProcess.emit (events.js:211:7)
[W3C]     at Process.ChildProcess._handle.onexit (internal/child_process.js:196:12)
[W3C]     at onErrorNT (internal/child_process.js:372:16)
[W3C]     at _combinedTickCallback (internal/process/next_tick.js:138:11)
[W3C]     at process._tickCallback (internal/process/next_tick.js:180:9)
[HTTP] <-- POST /wd/hub/session 500 14 ms - 1404
[HTTP]

**Comment by MeiJunZhang** [comment]
Sorry, I didn't restart the computer after setting up the JAVA environment variable. After restarting the computer, it's ok
