### ISSUE TITLE
IOS=>WebDriverException: An unknown server-side error occurred while processing the command. Original error: Unhandled endpoint

### ISSUE THREAD

**Issue by zhouzhangyin** [appium/appium#11055]
## The problem

After launching app,I get this exception:
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Unhandled endpoint: /session/370916E4-7CC5-4AEC-8474-69D9DDD52120/wda/screen -- http://localhost:62098/ with parameters {
    wildcards =     (
        "session/370916E4-7CC5-4AEC-8474-69D9DDD52120/wda/screen"
    );
}

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS X 10.13.6
* Node.js version (unless using Appium.app|exe):v7.0.0
* Mobile platform/version under test: ios 11.2.6
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe: Appium.app

##detail

Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'bogon', ip: 'fe80:0:0:0:8f:d1e1:dce1:85c1%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.6', java.version: '1.8.0_121'
Driver info: io.appium.java_client.AppiumDriver
Capabilities===>{app: /Users/zhouzhangyin/gitlab/..., automationName: XCuiTest, browserName: , bundleId: com.hyww.wisdomtrees, clearSystemFiles: true, databaseEnabled: false, deviceName: iPhone, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: false, platform: MAC, platformName: MAC, preventWDAAttachments: true, shouldUseSingletonTestManager: false, simpleIsVisibleCheck: true, startIWDP: true, takesScreenshot: true, udid: 5ce3a0adc5952986d1c0e90f1c3..., updatedWDABundleId: com.bbtree.WebDriverAgentRu..., useCarthageSsl: true, waitForAppScript: $.delay(5000); $.acceptAler..., wdaLocalPort: 62098, wdaStartupRetries: 6, webStorageEnabled: false, webkitDebugProxyPort: 62129, xcodeOrgId: 5EQ4X3VWN8, xcodeSigningId: iPhone Developer}

## Appium logs

2018-07-17 09:01:52:504 - warn: [Appium] Appium support for versions of node < 8 has been deprecated and will be removed in a future version. Please upgrade!
2018-07-17 09:01:52:539 - info: [Appium] Welcome to Appium v1.8.1
2018-07-17 09:01:52:541 - info: [Appium] Non-default server args:
2018-07-17 09:01:52:542 - info: [Appium]   address: 127.0.0.1
2018-07-17 09:01:52:542 - info: [Appium]   port: 40453
2018-07-17 09:01:52:542 - info: [Appium]   log: /Users/zhouzhangyin/gitlab/bbtree-maven-appium/target/appiumlogs/appium_logs.txt
2018-07-17 09:01:52:598 - info: [Appium] Appium REST http interface listener started on 127.0.0.1:40453
2018-07-17 09:01:52:713 - info: [HTTP] --> GET /wd/hub/status
2018-07-17 09:01:52:714 - info: [HTTP] {}
2018-07-17 09:01:52:718 - info: [debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
2018-07-17 09:01:52:732 - info: [debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.8.1","revision":null}}
2018-07-17 09:01:52:741 - info: [HTTP] <-- GET /wd/hub/status 200 23 ms - 83
2018-07-17 09:01:52:741 - info: [HTTP] 
2018-07-17 09:01:53:195 - info: [HTTP] --> POST /wd/hub/session
2018-07-17 09:01:53:196 - info: [HTTP] {"desiredCapabilities":{"app":"/Users/zhouzhangyin/gitlab/bbtree-maven-appium/build/WisdomTree.zip","preventWDAAttachments":true,"simpleIsVisibleCheck":true,"clearSystemFiles":true,"useCarthageSsl":true,"xcodeOrgId":"5EQ4X3VWN8","bundleId":"com.hyww.wisdomtrees","startIWDP":true,"deviceName":"iPhone","updatedWDABundleId":"com.bbtree.WebDriverAgentRunner","xcodeSigningId":"iPhone Developer","wdaLocalPort":62098,"shouldUseSingletonTestManager":false,"webkitDebugProxyPort":62129,"automationName":"XCuiTest","waitForAppScript":"$.delay(5000); $.acceptAlert(); true;","wdaStartupRetries":6,"platformName":"iOS","udid":"5ce3a0adc5952986d1c0e90f1c3b9540bc374d8e"},"capabilities":{"alwaysMatch":{"appium:app":"/Users/zhouzhangyin/gitlab/bbtree-maven-appium/build/WisdomTree.zip","appium:automationName":"XCuiTest","appium:bundleId":"com.hyww.wisdomtrees","appium:clearSystemFiles":true,"appium:deviceName":"iPhone","platformName":"ios","appium:preventWDAAttachments":true,"appium:shouldUseSingletonTestM
2018-07-17 09:01:53:197 - info: [debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/zhouzhangyin/gitlab/bbtree-maven-appium/build/WisdomTree.zip","preventWDAAttachments":true,"simpleIsVisibleCheck":true,"clearSystemFiles":true,"useCarthageSsl":true,"xcodeOrgId":"5EQ4X3VWN8","bundleId":"com.hyww.wisdomtrees","startIWDP":true,"deviceName":"iPhone","updatedWDABundleId":"com.bbtree.WebDriverAgentRunner","xcodeSigningId":"iPhone Developer","wdaLocalPort":62098,"shouldUseSingletonTestManager":false,"webkitDebugProxyPort":62129,"automationName":"XCuiTest","waitForAppScript":"$.delay(5000); $.acceptAlert(); true;","wdaStartupRetries":6,"platformName":"iOS","udid":"5ce3a0adc5952986d1c0e90f1c3b9540bc374d8e"},null,{"alwaysMatch":{"appium:app":"/Users/zhouzhangyin/gitlab/bbtree-maven-appium/build/WisdomTree.zip","appium:automationName":"XCuiTest","appium:bundleId":"com.hyww.wisdomtrees","appium:clearSystemFiles":true,"appium:deviceName":"iPhone","platformName":"ios","appium:preventWDAAttachments":true,"appium:shouldUseSingletonTestManager":false,"appium:simpleIsVisibleCheck":true,"app...
2018-07-17 09:01:53:198 - info: [debug] [BaseDriver] Event 'newSessionRequested' logged at 1531818113198 (17:01:53 GMT+0800 (CST))
2018-07-17 09:01:53:202 - warn: [BaseDriver] The capabilities ["webkitDebugProxyPort"] are not standard capabilities and should have an extension prefix
2018-07-17 09:01:53:210 - info: [Appium] Creating new XCUITestDriver (v2.84.0) session
2018-07-17 09:01:53:210 - info: [Appium] Capabilities:
2018-07-17 09:01:53:210 - info: [Appium]   platformName: ios
2018-07-17 09:01:53:210 - info: [Appium]   webkitDebugProxyPort: 62129
2018-07-17 09:01:53:210 - info: [Appium]   app: /Users/zhouzhangyin/gitlab/bbtree-maven-appium/build/WisdomTree.zip
2018-07-17 09:01:53:211 - info: [Appium]   automationName: XCuiTest
2018-07-17 09:01:53:211 - info: [Appium]   bundleId: com.hyww.wisdomtrees
2018-07-17 09:01:53:211 - info: [Appium]   clearSystemFiles: true
2018-07-17 09:01:53:212 - info: [Appium]   deviceName: iPhone
2018-07-17 09:01:53:212 - info: [Appium]   preventWDAAttachments: true
2018-07-17 09:01:53:212 - info: [Appium]   shouldUseSingletonTestManager: false
2018-07-17 09:01:53:212 - info: [Appium]   simpleIsVisibleCheck: true
2018-07-17 09:01:53:212 - info: [Appium]   startIWDP: true
2018-07-17 09:01:53:212 - info: [Appium]   udid: 5ce3a0adc5952986d1c0e90f1c3b9540bc374d8e
2018-07-17 09:01:53:213 - info: [Appium]   updatedWDABundleId: com.bbtree.WebDriverAgentRunner
2018-07-17 09:01:53:213 - info: [Appium]   useCarthageSsl: true
2018-07-17 09:01:53:213 - info: [Appium]   waitForAppScript: $.delay(5000); $.acceptAlert(); true;
2018-07-17 09:01:53:213 - info: [Appium]   wdaLocalPort: 62098
2018-07-17 09:01:53:213 - info: [Appium]   wdaStartupRetries: 6
2018-07-17 09:01:53:214 - info: [Appium]   xcodeOrgId: 5EQ4X3VWN8
2018-07-17 09:01:53:214 - info: [Appium]   xcodeSigningId: iPhone Developer
2018-07-17 09:01:53:220 - info: [debug] [BaseDriver] W3C capabilities {"alwaysMatch":{"platformNa... and MJSONWP desired capabilities [object Object] were provided
2018-07-17 09:01:53:220 - info: [debug] [BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"platformNa...
2018-07-17 09:01:53:271 - info: [BaseDriver] Session created with session id: 82bc2391-ca6e-4433-80c5-873858f98570
2018-07-17 09:01:53:285 - info: [debug] [XCUITest] Current user: 'zhouzhangyin'
2018-07-17 09:01:53:460 - info: [debug] [XCUITest] Xcode version set to '9.4.1' (tools v10.0.0.0.1.1527767617)
2018-07-17 09:01:53:474 - info: [debug] [XCUITest] iOS SDK Version set to '11.4'
2018-07-17 09:01:53:475 - info: [debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1531818113475 (17:01:53 GMT+0800 (CST))
2018-07-17 09:01:53:708 - info: [debug] [XCUITest] Available devices: 5ce3a0adc5952986d1c0e90f1c3b9540bc374d8e
2018-07-17 09:01:53:709 - info: [debug] [XCUITest] Creating iDevice object with udid '5ce3a0adc5952986d1c0e90f1c3b9540bc374d8e'
2018-07-17 09:01:53:711 - info: [XCUITest] Determining device to run tests on: udid: '5ce3a0adc5952986d1c0e90f1c3b9540bc374d8e', real device: true
2018-07-17 09:01:53:715 - info: [BaseDriver] Using local app '/Users/zhouzhangyin/gitlab/bbtree-maven-appium/build/WisdomTree.zip'
2018-07-17 09:01:53:716 - info: [debug] [BaseDriver] Copying local zip to tmp dir
2018-07-17 09:02:03:930 - info: [BaseDriver] Unzipping local app '/var/folders/f3/z8ry9sr12vd9l72ktbhxcxzm0000gn/T/2018617-38095-17aufuz.ezem2c5wmi/appium-app.zip'...
2018-07-17 09:02:04:215 - info: [debug] [BaseDriver] Unzipping /var/folders/f3/z8ry9sr12vd9l72ktbhxcxzm0000gn/T/2018617-38095-17aufuz.ezem2c5wmi/appium-app.zip
2018-07-17 09:02:04:215 - info: [debug] [BaseDriver] Testing zip archive: /var/folders/f3/z8ry9sr12vd9l72ktbhxcxzm0000gn/T/2018617-38095-17aufuz.ezem2c5wmi/appium-app.zip
2018-07-17 09:02:22:756 - info: [BaseDriver] Unzipped local app to '/var/folders/f3/z8ry9sr12vd9l72ktbhxcxzm0000gn/T/2018617-38095-17aufuz.ezem2c5wmi/Payload/WisdomTree.app'
2018-07-17 09:02:22:757 - info: [debug] [BaseDriver] Event 'appConfigured' logged at 1531818142757 (17:02:22 GMT+0800 (CST))
2018-07-17 09:02:22:758 - info: [debug] [XCUITest] Checking whether app '/var/folders/f3/z8ry9sr12vd9l72ktbhxcxzm0000gn/T/2018617-38095-17aufuz.ezem2c5wmi/Payload/WisdomTree.app' is actually present on file system
2018-07-17 09:02:22:758 - info: [debug] [XCUITest] App is present
2018-07-17 09:02:22:759 - info: [debug] [BaseDriver] Event 'resetStarted' logged at 1531818142759 (17:02:22 GMT+0800 (CST))
2018-07-17 09:02:22:760 - info: [debug] [XCUITest] Reset: running ios real device reset flow
2018-07-17 09:02:22:760 - info: [debug] [BaseDriver] Event 'resetComplete' logged at 1531818142760 (17:02:22 GMT+0800 (CST))
2018-07-17 09:02:22:762 - info: [debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
2018-07-17 09:02:22:764 - info: [debug] [iOSLog] Starting iOS device log capture with: 'idevicesyslog'
2018-07-17 09:02:23:156 - info: [debug] [XCUITest] Crash reports root '/Users/zhouzhangyin/Library/Logs/CrashReporter/MobileDevice/T09iG' does not exist. Got nothing to gather.
2018-07-17 09:02:23:157 - info: [debug] [BaseDriver] Event 'logCaptureStarted' logged at 1531818143157 (17:02:23 GMT+0800 (CST))
2018-07-17 09:02:23:158 - info: [XCUITest] Setting up real device
2018-07-17 09:02:23:159 - info: [debug] [XCUITest] Verifying application platform
2018-07-17 09:02:23:162 - info: [debug] [XCUITest] CFBundleSupportedPlatforms: ["iPhoneOS"]
2018-07-17 09:02:23:340 - info: [debug] [XCUITest] Reset requested. Removing app with id 'com.hyww.wisdomtrees' from the device
2018-07-17 09:02:23:704 - info: [debug] [XCUITest] Installing '/var/folders/f3/z8ry9sr12vd9l72ktbhxcxzm0000gn/T/2018617-38095-17aufuz.ezem2c5wmi/Payload/WisdomTree.app' on device with UUID '5ce3a0adc5952986d1c0e90f1c3b9540bc374d8e'...
2018-07-17 09:02:34:671 - info: [debug] [XCUITest] The app has been installed successfully.
2018-07-17 09:02:34:671 - info: [debug] [BaseDriver] Event 'appInstalled' logged at 1531818154671 (17:02:34 GMT+0800 (CST))
2018-07-17 09:02:34:673 - info: [XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
2018-07-17 09:02:34:674 - info: [XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
2018-07-17 09:02:34:945 - info: [debug] [XCUITest] No obsolete cached processes from previous WDA sessions listening on port 62098 have been found
2018-07-17 09:02:34:947 - info: [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:62098/status] with no body
2018-07-17 09:02:34:972 - info: [debug] [XCUITest] WDA is not listening at 'http://localhost:62098/'
2018-07-17 09:02:34:973 - info: [debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1531818154973 (17:02:34 GMT+0800 (CST))
2018-07-17 09:02:34:974 - info: [XCUITest] Launching WebDriverAgent on the device
2018-07-17 09:02:34:979 - info: [debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
2018-07-17 09:02:34:980 - info: [debug] [XCUITest] Killing running processes 'xcodebuild.*5ce3a0adc5952986d1c0e90f1c3b9540bc374d8e, iproxy 62098' for the device 5ce3a0adc5952986d1c0e90f1c3b9540bc374d8e...
2018-07-17 09:02:35:013 - info: [debug] [XCUITest] 'pgrep -nif xcodebuild.*5ce3a0adc5952986d1c0e90f1c3b9540bc374d8e' didn't detect any matching processes. Return code: 1
2018-07-17 09:02:35:044 - info: [debug] [XCUITest] 'pgrep -nif iproxy 62098' didn't detect any matching processes. Return code: 1
2018-07-17 09:02:35:045 - info: [debug] [XCUITest] Starting iproxy to forward traffic from local port 62098 to device port 8100 over USB
2018-07-17 09:02:40:060 - info: [debug] [XCUITest] Using Xcode 9.4.1, so fixing WDA codebase
2018-07-17 09:02:40:070 - info: [debug] [XCUITest] Successfully reset '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj/project.pbxproj' with bundle id 'com.facebook.WebDriverAgentRunner'
2018-07-17 09:02:40:080 - info: [debug] [XCUITest] Successfully updated '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj/project.pbxproj' with bundle id 'com.bbtree.WebDriverAgentRunner'
2018-07-17 09:02:40:082 - info: [debug] [XCUITest] Generating xcode config file for orgId '5EQ4X3VWN8' and signingId 'iPhone Developer'
2018-07-17 09:02:40:083 - info: [debug] [XCUITest] Writing xcode config file to /var/folders/f3/z8ry9sr12vd9l72ktbhxcxzm0000gn/T/2018617-38095-h0kkod.5bm6hnz5mi/appium-temp.xcconfig
2018-07-17 09:02:40:085 - warn: [XCUITest] Cannot parse major and minor version numbers from platformVersion "null". Will build for the default platform instead
2018-07-17 09:02:40:085 - info: [debug] [XCUITest] Using Xcode configuration file: '/var/folders/f3/z8ry9sr12vd9l72ktbhxcxzm0000gn/T/2018617-38095-h0kkod.5bm6hnz5mi/appium-temp.xcconfig'
2018-07-17 09:02:40:086 - info: [debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=5ce3a0adc5952986d1c0e90f1c3b9540bc374d8e -xcconfig /var/folders/f3/z8ry9sr12vd9l72ktbhxcxzm0000gn/T/2018617-38095-h0kkod.5bm6hnz5mi/appium-temp.xcconfig' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
2018-07-17 09:02:40:086 - info: [debug] [XCUITest] Output from xcodebuild will not be logged. To change this, use 'showXcodeLog' desired capability
2018-07-17 09:02:40:948 - info: [debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
2018-07-17 09:02:40:949 - info: [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:62098/status] with no body
2018-07-17 09:02:41:465 - info: [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:62098/status] with no body
2018-07-17 09:02:42:002 - info: [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:62098/status] with no body
2018-07-17 09:02:42:512 - info: [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:62098/status] with no body
2018-07-17 09:02:42:596 - info: [debug] [XCUITest] Log file for xcodebuild test: /var/folders/f3/z8ry9sr12vd9l72ktbhxcxzm0000gn/T/com.apple.dt.XCTest/IDETestRunSession-BC1DBC54-E3D6-4BBE-9A20-69C4C3A46C41/WebDriverAgentRunner-A14F8C24-B459-4653-99E6-657E54D796BB/Session-WebDriverAgentRunner-2018-07-17_170242-ZLnmne.log
2018-07-17 09:02:43:023 - info: [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:62098/status] with no body
2018-07-17 09:02:43:530 - info: [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:62098/status] with no body
2018-07-17 09:02:44:039 - info: [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:62098/status] with no body
2018-07-17 09:02:44:549 - info: [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:62098/status] with no body
2018-07-17 09:02:45:060 - info: [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:62098/status] with no body
2018-07-17 09:02:45:569 - info: [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:62098/status] with no body
2018-07-17 09:02:46:082 - info: [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:62098/status] with no body
2018-07-17 09:02:46:592 - info: [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:62098/status] with no body
2018-07-17 09:02:47:104 - info: [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:62098/status] with no body
2018-07-17 09:02:47:613 - info: [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:62098/status] with no body
2018-07-17 09:02:48:124 - info: [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:62098/status] with no body
2018-07-17 09:02:48:138 - info: [debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"11.2.6\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"11.2.6\",\n      \"ip\" : \"10.0.8.96\"\n    },\n    \"build\" : {\n      \"time\" : \"Jul 16 2018 19:31:02\"\n    }\n  },\n  \"sessionId\" : \"AB170076-4E5B-4A03-8CFC-C7215F238CD7\",\n  \"status\" : 0\n}"
2018-07-17 09:02:48:139 - info: [debug] [XCUITest] WebDriverAgent running on ip '10.0.8.96'
2018-07-17 09:02:48:140 - info: [debug] [XCUITest] WebDriverAgent successfully started after 8052ms
2018-07-17 09:02:48:142 - info: [debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1531818168142 (17:02:48 GMT+0800 (CST))
2018-07-17 09:02:48:143 - info: [debug] [XCUITest] Sending createSession command to WDA
2018-07-17 09:02:48:146 - info: [debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:62098/session] with body: {"desiredCapabilities":{"bundleId":"com.hyww.wisdomtrees","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":true,"maxTypingFrequency":60,"shouldUseSingletonTestManager":false}}
2018-07-17 09:02:52:774 - info: [debug] [JSONWP Proxy] Got response with status 200: {"value":{"sessionId":"370916E4-7CC5-4AEC-8474-69D9DDD52120","capabilities":{"device":"iphone","browserName":" ","sdkVersion":"11.2.6","CFBundleIdentifier":"com.apple.springboard"}},"sessionId":"370916E4-7CC5-4AEC-8474-69D9DDD52120","status":0}
2018-07-17 09:02:52:775 - info: [debug] [BaseDriver] Event 'wdaSessionStarted' logged at 1531818172775 (17:02:52 GMT+0800 (CST))
2018-07-17 09:02:52:968 - info: [debug] [XCUITest] Cannot find a match for DerivedData folder path from lsof. Trying to access logs
2018-07-17 09:02:52:978 - info: [XCUITest] Setting '555' permissions to '/Users/zhouzhangyin/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/Attachments' folder
2018-07-17 09:02:52:979 - info: [debug] [BaseDriver] Event 'wdaPermsAdjusted' logged at 1531818172979 (17:02:52 GMT+0800 (CST))
2018-07-17 09:02:52:980 - info: [debug] [BaseDriver] Event 'wdaStarted' logged at 1531818172980 (17:02:52 GMT+0800 (CST))
2018-07-17 09:02:52:981 - info: [XCUITest] Skipping setting of the initial display orientation. Set the "orientation" capability to either "LANDSCAPE" or "PORTRAIT", if this is an undesired behavior.
2018-07-17 09:02:52:981 - info: [debug] [BaseDriver] Event 'orientationSet' logged at 1531818172981 (17:02:52 GMT+0800 (CST))
2018-07-17 09:02:52:982 - info: [debug] [BaseDriver] Event 'iwdpStarting' logged at 1531818172982 (17:02:52 GMT+0800 (CST))
2018-07-17 09:02:52:985 - info: [debug] [iOS] Starting ios_webkit_debug_proxy at port 62129 on device 5ce3a0adc5952986d1c0e90f1c3b9540bc374d8e
2018-07-17 09:02:53:042 - info: [debug] [BaseDriver] Event 'iwdpStarted' logged at 1531818173042 (17:02:53 GMT+0800 (CST))
2018-07-17 09:02:53:043 - info: [debug] [XCUITest] Started ios_webkit_debug proxy server at: http://localhost:62129
2018-07-17 09:02:53:045 - info: [Appium] New XCUITestDriver session created successfully, session 82bc2391-ca6e-4433-80c5-873858f98570 added to master session list
2018-07-17 09:02:53:050 - info: [debug] [BaseDriver] Event 'newSessionStarted' logged at 1531818173047 (17:02:53 GMT+0800 (CST))
2018-07-17 09:02:53:051 - info: [debug] [W3C] Responding to client with driver.createSession() result: {"capabilities":{"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"platformName":"ios","webkitDebugProxyPort":62129,"app":"/Users/zhouzhangyin/gitlab/bbtree-maven-appium/build/WisdomTree.zip","automationName":"XCuiTest","bundleId":"com.hyww.wisdomtrees","clearSystemFiles":true,"deviceName":"iPhone","preventWDAAttachments":true,"shouldUseSingletonTestManager":false,"simpleIsVisibleCheck":true,"startIWDP":true,"udid":"5ce3a0adc5952986d1c0e90f1c3b9540bc374d8e","updatedWDABundleId":"com.bbtree.WebDriverAgentRunner","useCarthageSsl":true,"waitForAppScript":"$.delay(5000); $.acceptAlert(); true;","wdaLocalPort":62098,"wdaStartupRetries":6,"xcodeOrgId":"5EQ4X3VWN8","xcodeSigningId":"iPhone Developer"}}
2018-07-17 09:02:53:055 - info: [HTTP] <-- POST /wd/hub/session 200 59858 ms - 912
2018-07-17 09:02:53:057 - info: [HTTP] 
2018-07-17 09:02:53:099 - info: [HTTP] --> GET /wd/hub/session/82bc2391-ca6e-4433-80c5-873858f98570
2018-07-17 09:02:53:099 - info: [HTTP] {}
2018-07-17 09:02:53:100 - info: [debug] [W3C] Calling AppiumDriver.getSession() with args: ["82bc2391-ca6e-4433-80c5-873858f98570"]
2018-07-17 09:02:53:101 - info: [debug] [XCUITest] Executing command 'getSession'
2018-07-17 09:02:53:113 - info: [debug] [JSONWP Proxy] Proxying [GET /] to [GET http://localhost:62098/session/370916E4-7CC5-4AEC-8474-69D9DDD52120] with no body
2018-07-17 09:02:53:197 - info: [debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"sessionId\" : \"370916E4-7CC5-4AEC-8474-69D9DDD52120\",\n    \"capabilities\" : {\n      \"device\" : \"iphone\",\n      \"browserName\" : \" \",\n      \"sdkVersion\" : \"11.2.6\",\n      \"CFBundleIdentifier\" : \"com.apple.springboard\"\n    }\n  },\n  \"sessionId\" : \"370916E4-7CC5-4AEC-8474-69D9DDD52120\",\n  \"status\" : 0\n}"
2018-07-17 09:02:53:198 - info: [XCUITest] Merging WDA caps over Appium caps for session detail response
2018-07-17 09:02:53:199 - info: [debug] [JSONWP Proxy] Proxying [GET /wda/screen] to [GET http://localhost:62098/session/370916E4-7CC5-4AEC-8474-69D9DDD52120/wda/screen] with no body
2018-07-17 09:02:53:203 - info: [debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"Unhandled endpoint: \\/session\\/370916E4-7CC5-4AEC-8474-69D9DDD52120\\/wda\\/screen -- http:\\/\\/localhost:62098\\/ with parameters {\\n    wildcards =     (\\n        \\\"session\\/370916E4-7CC5-4AEC-8474-69D9DDD52120\\/wda\\/screen\\\"\\n    );\\n}\",\n  \"sessionId\" : \"370916E4-7CC5-4AEC-8474-69D9DDD52120\",\n  \"status\" : 1\n}"
2018-07-17 09:02:53:205 - info: [debug] [MJSONWP] Matched JSONWP error code 1 to UnknownError
2018-07-17 09:02:53:225 - info: [HTTP] <-- GET /wd/hub/session/82bc2391-ca6e-4433-80c5-873858f98570 500 125 ms - 1646
2018-07-17 09:02:53:226 - info: [HTTP] 
2018-07-17 09:02:54:818 - info: [Appium] Received SIGTERM - shutting down
2018-07-17 09:02:54:822 - error: uncaughtException: write EPIPE date=Tue Jul 17 2018 17:02:54 GMT+0800 (CST), pid=38095, uid=501, gid=20, cwd=/Users/zhouzhangyin/gitlab/bbtree-maven-appium, execPath=/usr/local/Cellar/node/7.0.0/bin/node, version=v7.0.0, argv=[/usr/local/Cellar/node/7.0.0/bin/node, /usr/local/lib/node_modules/appium/build/lib/main.js, --port, 40453, --address, 127.0.0.1, --log, /Users/zhouzhangyin/gitlab/bbtree-maven-appium/target/appiumlogs/appium_logs.txt], rss=213626880, heapTotal=96034816, heapUsed=79263520, loadavg=[4.02783203125, 3.1982421875, 2.75390625], uptime=28435, trace=[column=11, file=util.js, function=exports._errnoException, line=1026, method=_errnoException, native=false, column=14, file=net.js, function=WriteWrap.afterWrite, line=804, method=afterWrite, native=false], stack=[Error: write EPIPE,     at exports._errnoException (util.js:1026:11),     at WriteWrap.afterWrite (net.js:804:14)]

**Comment by mykola-mokhnach** [comment]
The WebDriverAgent binary on the device is out of date. Clear Xcode caches and reset the device. Closed as duplicate
