### ISSUE TITLE
Can't run the appium doctor in the terminal

### ISSUE THREAD

**Issue by maxsudik** [appium/appium#11066]
Can't run appium doctor after it was installed.

I'm using Appium version 1.6.2 and node 8.11.3, environment - Mac

Log from terminal:
```
QA-iMac:~ Maksym$ appium-doctor
Error: Cannot find module './build/Debug/buffertools.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/appium-doctor/node_modules/buffertools/buffertools.js:27:20)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/appium-doctor/node_modules/mjpeg-consumer/lib/mjpeg-consumer.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/appium-doctor/node_modules/mjpeg-consumer/index.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/appium-doctor/node_modules/appium-support/build/lib/mjpeg.js:43:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
QA-iMac:~ Maksym$ 
```

If you need additional details, I will provide it shortly. I'm new one here, so don't know how to create issues correct.

**Comment by dpgraham** [comment]
Which npm version did you install with?

**Comment by imurchie** [comment]
Can you uninstall and re-install (`npm uninstall -g appium-doctor && npm install -g appium-doctor`) and post the output?

**Comment by maxsudik** [comment]
Now I have this log:

QA-iMac:~ Maksym$ sudo npm uninstall -g appium-doctor
Password:
removed 248 packages in 4.151s
QA-iMac:~ Maksym$ sudo npm install -g appium-doctor
/usr/local/bin/appium-doctor -> /usr/local/lib/node_modules/appium-doctor/appium-doctor.js

> buffertools@2.1.6 install /usr/local/lib/node_modules/appium-doctor/node_modules/buffertools
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/Users/Maksym/.node-gyp/8.11.3"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/appium-doctor/node_modules/buffertools/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/appium-doctor/node_modules/buffertools/.node-gyp'
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/appium-doctor/node_modules/buffertools
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm ERR! Maximum call stack size exceeded

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Maksym/.npm/_logs/2018-07-19T16_53_23_072Z-debug.log
QA-iMac:~ Maksym$

**Comment by maxsudik** [comment]
The problem was Node version. After I installed v6.9.1, everything went well

Issue can be closed.
