### ISSUE TITLE
Appium would not navigate to URL on real devices

### ISSUE THREAD

**Issue by vytran9599** [appium/appium#11087]
I downloaded Appium here: https://github.com/appium/appium-desktop/releases/tag/v1.6.2
When I open the graphical Appium view, it would launch Safari on my real devices (iOS 11.3 & 10.3), but it would not navigate to the URL I tell it to. 

However, if I use Appium that I install from node (npm install -g appium) and run Appium from the terminal, it would launch Safari and navigate to the URL. 

Is there a way to fix this issue? Thank you. 

* Appium version (or git revision) that exhibits the issue: 1.8.0 and 1.8.1 (if downloaded from https://github.com/appium/appium-desktop/releases/tag/v1.6.2)
* Real device or emulator/simulator: Real device

**Comment by imurchie** [comment]
The issue could be any number of things. Can you please post the logs, as a link to a [gist](https://github.com) so that help can be given?

**Comment by vytran9599** [comment]
[debug] [BaseDriver] Creating session with MJSONWP desired capabilities: {"platformName":"iOS","auto...
[warn] [BaseDriver] Capability 'autoWebview' changed from string to boolean. This may cause unexpected behavior
[warn] [BaseDriver] Capability 'usePrebuiltWDA' changed from string to boolean. This may cause unexpected behavior
[warn] [BaseDriver] Capability 'startIWDP' changed from string to boolean. This may cause unexpected behavior
[warn] [BaseDriver] Capability 'newCommandTimeout' changed from string ('30000') to integer (30000). This may cause unexpected behavior
[warn] [BaseDriver] Capability 'wdaLocalPort' changed from string ('8100') to integer (8100). This may cause unexpected behavior
[info] [BaseDriver] Session created with session id: 71c13c2e-c03a-4536-b089-21215cafe028
[debug] [XCUITest] Current user: 'qatesters'[debug] [XCUITest] Xcode version set to '9.4.1' (tools v9.4.1.0.1.1528165917)
[debug] [XCUITest] iOS SDK Version set to '11.4'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1532112833100 (14:53:53 GMT-0400 (EDT))[debug] [XCUITest] Available devices: 22928c7eeb5be9a965d9d00a38c24de0d98dbaf3
[debug] [XCUITest] Creating iDevice object with udid '22928c7eeb5be9a965d9d00a38c24de0d98dbaf3'
[info] [XCUITest] Determining device to run tests on: udid: '22928c7eeb5be9a965d9d00a38c24de0d98dbaf3', real device: true
[info] [XCUITest] Safari test requested
[debug] [BaseDriver] Event 'appConfigured' logged at 1532112835473 (14:53:55 GMT-0400 (EDT))
[debug] [BaseDriver] Event 'resetStarted' logged at 1532112835473 (14:53:55 GMT-0400 (EDT))
[debug] [XCUITest] Reset: running ios real device reset flow
[debug] [BaseDriver] Event 'resetComplete' logged at 1532112835474 (14:53:55 GMT-0400 (EDT))
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Starting iOS device log capture with: 'idevicesyslog'[debug] [XCUITest] Crash reports root '/Users/qatesters/Library/Logs/CrashReporter/MobileDevice/MichaelGCGVPFL2HLJJ' does not exist. Got nothing to gather.
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1532112835802 (14:53:55 GMT-0400 (EDT))
[info] [XCUITest] Setting up real device
[info] [XCUITest] Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent'
[info] [XCUITest] Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'[debug] [XCUITest] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"11.3.1\",\n      \"sdkVersion\" : \"11.3\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"11.3.1\",\n      \"ip\" : \"10.65.5.211\"\n    },\n    \"build\" : {\n      \"time\" : \"Jul 19 2018 09:11:09\"\n    }\n  },\n  \"sessionId\" : \"EDCB153C-5402-4CE0-8850-C161D529486C\",\n  \"status\" : 0\n}"
[info] [XCUITest] Will reuse previously cached WDA instance at 'http://localhost:8100/'. Set the wdaLocalPort capability to a value different from 8100 if this is an undesired behavior.
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1532112836266 (14:53:56 GMT-0400 (EDT))
[info] [XCUITest] Using provided WebdriverAgent at 'http://localhost:8100/'
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1532112836266 (14:53:56 GMT-0400 (EDT))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"11.3.1\",\n      \"sdkVersion\" : \"11.3\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"11.3.1\",\n      \"ip\" : \"10.65.5.211\"\n    },\n    \"build\" : {\n      \"time\" : \"Jul 19 2018 09:11:09\"\n    }\n  },\n  \"sessionId\" : \"EDCB153C-5402-4CE0-8850-C161D529486C\",\n  \"status\" : 0\n}"
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.apple.mobilesafari","arguments":["-u","http://appium.io"],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}[debug] [JSONWP Proxy] Got response with status 200: {"value":{"sessionId":"D094205D-986C-447F-A525-8887B4D325C9","capabilities":{"device":"ipad","browserName":"Safari","sdkVersion":"11.3.1","CFBundleIdentifier":"com.apple.mobilesafari"}},"sessionId":"D094205D-986C-447F-A525-8887B4D325C9","status":0}
[debug] [BaseDriver] Event 'wdaSessionStarted' logged at 1532112838904 (14:53:58 GMT-0400 (EDT))
[debug] [BaseDriver] Event 'wdaStarted' logged at 1532112838904 (14:53:58 GMT-0400 (EDT))
[info] [XCUITest] Skipping setting of the initial display orientation. Set the "orientation" capability to either "LANDSCAPE" or "PORTRAIT", if this is an undesired behavior.
[debug] [BaseDriver] Event 'orientationSet' logged at 1532112838906 (14:53:58 GMT-0400 (EDT))
[debug] [BaseDriver] Event 'iwdpStarting' logged at 1532112838906 (14:53:58 GMT-0400 (EDT))
[debug] [iOS] Starting ios_webkit_debug_proxy at port 27753 on device 22928c7eeb5be9a965d9d00a38c24de0d98dbaf3[debug] [BaseDriver] Event 'iwdpStarted' logged at 1532112839445 (14:53:59 GMT-0400 (EDT))
[debug] [XCUITest] Started ios_webkit_debug proxy server at: http://localhost:27753
[debug] [XCUITest] Waiting for initial webview
[debug] [iOS] Waiting for 3000 ms before navigating to view.[debug] [iOS] Navigating to most recently opened webview
[debug] [iOS] Retrieving contexts and views
[debug] [iOS] Selecting by url: true (expected url: 'http://appium.io')
[debug] [RemoteDebugger] Getting WebKitRemoteDebugger pageArray: localhost, 27753
[debug] [RemoteDebugger] Sending request to: http://localhost:27753/json
[debug] [RemoteDebugger] Page element JSON: [{"devtoolsFrontendUrl":"/devtools/devtools.html?ws=localhost:27753/devtools/page/1","faviconUrl":"","thumbnailUrl":"/thumb/http://appium.io/","title":"Appium: Mobile App Automation Made Awesome.","url":"http://appium.io/","webSocketDebuggerUrl":"ws://localhost:27753/devtools/page/1","appId":"PID:532"}]
[debug] [iOS] Retrieving contexts and views
[debug] [iOS] Selecting by url: true (expected url: 'http://appium.io')
[debug] [RemoteDebugger] Getting WebKitRemoteDebugger pageArray: localhost, 27753
[debug] [RemoteDebugger] Sending request to: http://localhost:27753/json
[debug] [RemoteDebugger] Page element JSON: [{"devtoolsFrontendUrl":"/devtools/devtools.html?ws=localhost:27753/devtools/page/1","faviconUrl":"","thumbnailUrl":"/thumb/http://appium.io/","title":"Appium: Mobile App Automation Made Awesome.","url":"http://appium.io/","webSocketDebuggerUrl":"ws://localhost:27753/devtools/page/1","appId":"PID:532"}]
[debug] [iOS] Picking webview 'WEBVIEW_1'
[debug] [iOS] Attempting to set context to 'WEBVIEW_1'
[debug] [RemoteDebugger] WebKit debugger web socket connected to url: ws://localhost:27753/devtools/page/1
[debug] [RemoteDebugger] Starting to listen for JavaScript console
[debug] [RemoteDebugger] Sending WebKit data: {"method":"Console.enable","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true}}
[debug] [RemoteDebugger] Webkit response timeout: 5000
[debug] [RemoteDebugger] Receiving WebKit data: '{"result":{},"id":1}'
[debug] [RemoteDebugger] Found handler for message '1'
[debug] [RemoteDebugger] WebKit debugger got a message for 'Console.enable' and have no handler, doing nothing.[error] [XCUITest] TimeoutError: operation timed out
[error] [XCUITest]     at afterTimeout (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/timers.js:46:19)
[error] [XCUITest]     at Timeout.timeoutTimeout [as _onTimeout] (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/timers.js:76:13)
[error] [XCUITest]     at ontimeout (timers.js:475:11)
[error] [XCUITest]     at tryOnTimeout (timers.js:310:5)
[error] [XCUITest]     at Timer.listOnTimeout (timers.js:270:5)
[debug] [JSONWP Proxy] Proxying [DELETE /session/71c13c2e-c03a-4536-b089-21215cafe028] to [DELETE http://localhost:8100/session/D094205D-986C-447F-A525-8887B4D325C9] with no body[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n\n  },\n  \"sessionId\" : \"DBE277DD-88DC-4304-ABE9-D1791DF13580\",\n  \"status\" : 0\n}"
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [XCUITest] In a web session. Removing remote debugger
[debug] [RemoteDebugger] Disconnecting from WebKit remote debugger
[debug] [iOSLog] Stopping iOS log capture
[debug] [RemoteDebugger] WebKit remote debugger socket disconnected
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1532112848074 (14:54:08 GMT-0400 (EDT))
[error] [W3C] Encountered internal error running command: TimeoutError: operation timed out
[error] [W3C]     at afterTimeout (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/timers.js:46:19)
[error] [W3C]     at Timeout.timeoutTimeout [as _onTimeout] (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/timers.js:76:13)
[error] [W3C]     at ontimeout (timers.js:475:11)
[error] [W3C]     at tryOnTimeout (timers.js:310:5)
[error] [W3C]     at Timer.listOnTimeout (timers.js:270:5)
[info] [HTTP] <-- POST /wd/hub/session 500 15848 ms - 1328
[info] [HTTP] 

@imurchie

**Comment by vytran9599** [comment]
@mykola-mokhnach Which link do I use to download appium@beta? I don't want to install it by node.

**Comment by mykola-mokhnach** [comment]
Unfortunately there is no other way to do it
