### ISSUE TITLE
Update Java-client from 5.0.0-BETA8  to 6.0.0-BETA4 get java.lang.NoSuchMethodError: com.google.common.base.Throwables.throwIfUnchecked(Ljava/lang/Throwable;

### ISSUE THREAD

**Issue by 1aoying** [appium/appium#11108]
## The problem

I update my java-client version from
5.0.0-BETA8 to 6.0.0-BETA4 ，cast excetiion ：java.lang.NoClassDefFoundError: com/google/common/base/Function”Then，I import selenium-server-standalone-2.53.1.jar into my eclipse there have another question:

## Environment

Appium Server version: 1.8.1
Desktop OS/version used to run Appium:MACOS 10.13.5
Node.js version (unless using Appium.app|exe):v10.7.0
Mobile platform/version under test:11.4
Real device or emulator/simulator:iPhone 6P real device
Appium CLI or Appium.app|exe:Appium.app

## Details

my pom：

```
                <dependency>
                  <groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>6.9.10</version>
		</dependency>
		<dependency>
			<groupId>io.appium</groupId>
			<artifactId>java-client</artifactId>
			<!-- <version>5.0.0-BETA8</version> -->
			<version>6.0.0-BETA4</version>		
		</dependency>
		<dependency>
			<groupId>com.googlecode.json-simple</groupId>
			<artifactId>json-simple</artifactId>
			<version>1.1</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>commons-lang</groupId>
			<artifactId>commons-lang</artifactId>
			<version>2.6</version>
			<scope>test</scope>
		</dependency>
		<dependency>
    		<groupId>log4j</groupId>
    		<artifactId>log4j</artifactId>
    		<version>1.2.17</version>
		</dependency>
		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
			<version>2.2.4</version>
		</dependency>
```
		
## Link to Appium logs

FAILED CONFIGURATION: @BeforeClass setUp
java.lang.NoSuchMethodError: com.google.common.base.Throwables.throwIfUnchecked(Ljava/lang/Throwable;)V
at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:143)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:644)
at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:249)
at org.openqa.selenium.remote.RemoteWebDriver.(RemoteWebDriver.java:131)
at org.openqa.selenium.remote.RemoteWebDriver.(RemoteWebDriver.java:144)
at io.appium.java_client.DefaultGenericMobileDriver.(DefaultGenericMobileDriver.java:38)
at io.appium.java_client.AppiumDriver.(AppiumDriver.java:84)
at io.appium.java_client.AppiumDriver.(AppiumDriver.java:94)
at io.appium.java_client.ios.IOSDriver.(IOSDriver.java:82)
at com.netease.mailmaster.test.MailIOSUITest.BaseTest.setUp(BaseTest.java:84)
at com.netease.mailmaster.test.MailIOSUITest.LoginTest.setUp(LoginTest.java:24)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)

**Comment by mykola-mokhnach** [comment]
Like I said it is not a server issue. All java client issues should be reported to https://github.com/appium/java-client. Also I assume it is a duplicate and there are already similar reports there.
