### ISSUE TITLE
[W3C] - Encountered internal error running command: Error: Cannot start the 'uk.co.o2.android.ask.enterprise' application.

### ISSUE THREAD

**Issue by buchadep** [appium/appium#11101]
## The problem
Couldn't connect to the app after getting the ERROR 
2018-07-24 08:53:36:834 - error: [W3C] Encountered internal error running command: Error: Cannot start the 'uk.co.o2.android.ask.enterprise' application. Original error: Error executing adbExec. Original error: 'Command 'D\:\\Android\\platform-tools\\adb.exe -P 5037 -s D1AGAM2720900442 shell am start -W -n uk.co.o2.android.ask.enterprise/com.tuenti.messenger.ui.activity.MainActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' timed out after 20000ms'; Stderr: ''; Code: 'null'
2018-07-24 08:53:36:835 - error: [W3C]     at ADB.callee$0$0$ (C:\Users\Vibha\AppData\Roaming\npm\node_modules\appium\node_modules\appium-adb\lib\tools\apk-utils.js:125:11)
2018-07-24 08:53:36:835 - error: [W3C]     at tryCatch (C:\Users\Vibha\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
2018-07-24 08:53:36:836 - error: [W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\Vibha\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
2018-07-24 08:53:36:836 - error: [W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\Vibha\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
2018-07-24 08:53:36:837 - error: [W3C]     at GeneratorFunctionPrototype.invoke (C:\Users\Vibha\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
2018-07-24 08:53:36:837 - error: [W3C]     at <anonymous>

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.2 Beta , I have also reverted to 1.8.1 and issue still persists
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 7 64 bit
* Node.js version (unless using Appium.app|exe): 8.11.1
* Mobile platform/version under test: Android 8.0.0
* Real device or emulator/simulator: Real Device - Nokia 5
* Appium CLI or Appium.app|exe: 
* Appium Client: Java Client - 6.0.0-BETA5

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
[appiumServer.log](https://github.com/appium/appium/files/2222846/appiumServer.log)

## Code To Reproduce Issue [ Good To Have ]

public void startApp() {
        try {
            DesiredCapabilities capabilities = new DesiredCapabilities();
            //Default configuration
            capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "Android Device");
            capabilities.setCapability("deviceName", "SAMSUNG");
            capabilities.setCapability("platformVersion", "7.0");
            capabilities.setCapability("platformName", "Android");
            //capabilities.setCapability("setWebContentsDebuggingEnabled", true);
            capabilities.setCapability("automationName", "UiAutomator2");
            //capabilities.setCapability("appium.autoWebview", true);
            capabilities.setCapability("autoGrantPermissions", true);
            capabilities.setCapability("noReset", true);
            capabilities.setCapability("appPackage", "uk.co.o2.android.ask.enterprise");
            capabilities.setCapability("appActivity", "com.tuenti.messenger.ui.activity.MainActivity");
            //capabilities.setCapability("chromedriverExecutable", "src\\test\\resources\\browsers\\chromedriver.exe");
            capabilities.setCapability("newCommandTimeout", 2000);

            //Assign Capability from config.properties
            Set<Object> keys = configuration.getKeys("appiumCapabilities");
            Iterator iterator = keys.iterator();
            while (iterator.hasNext()) {
                Object property = iterator.next();
                capabilities.setCapability(property.toString().substring(property.toString().indexOf('.') + 1), configuration.getProperty(property.toString()));
                logger.info(property.toString() + "::" + configuration.getProperty(property.toString()));
            }
            String appName = configuration.getProperty("appiumCapabilities.appName");
            File file = new File(appName);
            capabilities.setCapability("app", file.getAbsoluteFile());
            androidDriver = new AndroidDriver<MobileElement>(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
            driver = androidDriver;
        } catch (Exception e) {
            logger.error(e.toString());
        }
    }

**Comment by buchadep** [comment]
I could successfully launch the app from command line using command:
adb.exe -P 5037 -s D1AGAM2720900442 shell am start -W -n uk.co.o2.android.ask.enterprise/com.tuenti.messenger.ui.activity.MainActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000

**Comment by mykola-mokhnach** [comment]
Perhaps this is not the name of the activity, which is the first visible. Try to set `appWaitActivity`  value

**Comment by buchadep** [comment]
I have now set capability suggested but still getting the same error.
capabilities.setCapability("appWaitActivity", "com.tuenti.messenger.secure.session.view.PinActivity");


ND1:/ $ dumpsys window windows | grep -E 'mCurrentFocus'
  mCurrentFocus=Window{bdc2f1e u0 uk.co.o2.android.ask.enterprise/com.tuenti.messenger.secure.session.view.PinActivity}

**Comment by mykola-mokhnach** [comment]
Try to also set appWaitPackage

**Comment by buchadep** [comment]
Still No luck:
capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "Android Device");
            capabilities.setCapability("deviceName", "SAMSUNG");
            capabilities.setCapability("platformVersion", "7.0");
            capabilities.setCapability("platformName", "Android");
            //capabilities.setCapability("setWebContentsDebuggingEnabled", true);
            capabilities.setCapability("automationName", "UiAutomator2");
            //capabilities.setCapability("appium.autoWebview", true);
            capabilities.setCapability("autoGrantPermissions", true);
            capabilities.setCapability("noReset", true);
            capabilities.setCapability("appPackage", "uk.co.o2.android.ask.enterprise");
            capabilities.setCapability("appActivity", "com.tuenti.messenger.ui.activity.MainActivity");
            capabilities.setCapability("appWaitPackage", "uk.co.o2.android.ask.enterprise");
            capabilities.setCapability("appWaitActivity", "com.tuenti.messenger.secure.session.view.PinActivity");
            //capabilities.setCapability("chromedriverExecutable", "src\\test\\resources\\browsers\\chromedriver.exe");
            capabilities.setCapability("newCommandTimeout", 60);

**Comment by mykola-mokhnach** [comment]
what if you change appActivity to `com.tuenti.messenger.*` ?

**Comment by buchadep** [comment]
2018-07-24 10:56:33:190 - error: [W3C] Encountered internal error running command: Error: Cannot start the 'uk.co.o2.android.ask.enterprise' application. Original error: Cannot start the 'uk.co.o2.android.ask.enterprise' application. Original error: Activity name '.com.tuenti.messenger.*' used to start the app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity
2018-07-24 10:56:33:190 - error: [W3C]     at ADB.callee$0$0$ (C:\Users\Vibha\AppData\Roaming\npm\node_modules\appium\node_modules\appium-adb\lib\tools\apk-utils.js:125:11)
2018-07-24 10:56:33:191 - error: [W3C]     at tryCatch (C:\Users\Vibha\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
2018-07-24 10:56:33:191 - error: [W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\Vibha\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
2018-07-24 10:56:33:192 - error: [W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\Vibha\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
2018-07-24 10:56:33:192 - error: [W3C]     at GeneratorFunctionPrototype.invoke (C:\Users\Vibha\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
2018-07-24 10:56:33:192 - error: [W3C]     at <anonymous>
2018-07-24 10:56:33:202 - info: [HTTP] <-- POST /wd/hub/session 500 19632 ms - 1886

**Comment by buchadep** [comment]
Thanks mykola-mokhnach !!!
capabilities.setCapability("appWaitPackage", "uk.co.o2.android.ask.enterprise");
capabilities.setCapability("appWaitActivity", "com.tuenti.messenger.ui.activity.MainActivity,com.tuenti.messenger.ui.activity.MainActivity,com.tuenti.messenger.secure.session.view.PinActivity");

After adding above suggested capabilities, finally I manage to launch the app. But joy didn't last for long... I am getting another error "ECONNRESET" after successfully completing couple of tests.

            
ERROR:

ERROR 2018-07-24 15:01:40,251 [main] SplashSteps:userLogsToOAskApp(245): org.openqa.selenium.WebDriverException: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET

**Comment by mykola-mokhnach** [comment]
Switch to UIAutomator2

**Comment by buchadep** [comment]
I think, I am using UIAutomator2. 
capabilities.setCapability("automationName", "UiAutomator2");

After the first run, it has stopped working again with the same initial error.
2018-07-25 08:48:06:656 - error: [W3C] Encountered internal error running command: Error: Cannot start the 'uk.co.o2.android.ask.enterprise' application. Original error: Error executing adbExec. Original error: 'Command 'D\:\\Android\\platform-tools\\adb.exe -P 5037 -s D1AGAM2720900442 shell am start -W -n uk.co.o2.android.ask.enterprise/com.tuenti.messenger.ui.activity.MainActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' timed out after 20000ms'; Stderr: ''; Code: 'null'

please see attached log.
[appiumServer.log](https://github.com/appium/appium/files/2227204/appiumServer.log)

Also noticed warning:
2018-07-25 08:47:08:157 - warn: [AndroidDriver] 'com.tuenti.messenger.global.novum.ui.view.StartActivity,com.tuenti.messenger.ui.activity.MainActivity,com.tuenti.messenger.secure.session.view.PinActivity' is expected to only include latin letters, digits, underscore, dot and asterisk characters.
2018-07-25 08:47:08:157 - warn: [AndroidDriver] 'com.tuenti.messenger.global.novum.ui.view.StartActivity,' <- the first non-matching character occurrence is at index 55.

**Comment by mykola-mokhnach** [comment]
This warning must be a parsing issue. @KazuCocoa can you please add comma to the list of acceptable chars?

**Comment by mykola-mokhnach** [comment]
Try the wildcard in the wait activity name like I suggested above

**Comment by buchadep** [comment]
Wild card (*) didn't help. No warning for the config but same error.
===
2018-07-25 09:01:27:721 - info: [AndroidDriver] Screen already unlocked, doing nothing
2018-07-25 09:01:27:721 - info: [UiAutomator2] UiAutomator2 did not start the activity we were waiting for, 'uk.co.o2.android.ask.enterprise/com.tuenti.messenger.*'. Starting it ourselves
2018-07-25 09:01:27:721 - info: [debug] [ADB] Device API level: 26
2018-07-25 09:01:27:721 - info: [debug] [ADB] Running 'D:\Android\platform-tools\adb.exe -P 5037 -s D1AGAM2720900442 shell am start -W -n uk.co.o2.android.ask.enterprise/com.tuenti.messenger.ui.activity.MainActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
2018-07-25 09:01:47:748 - info: [debug] [ADB] Running 'D:\Android\platform-tools\adb.exe -P 5037 -s D1AGAM2720900442 shell am start -W -n uk.co.o2.android.ask.enterprise/com.tuenti.messenger.ui.activity.MainActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
2018-07-25 09:02:07:755 - info: [debug] [UiAutomator2] Deleting UiAutomator2 session
2018-07-25 09:02:07:755 - info: [debug] [UiAutomator2] Deleting UiAutomator2 server session
2018-07-25 09:02:07:755 - info: [debug] [JSONWP Proxy] Proxying [DELETE /] to [DELETE http://localhost:8200/wd/hub/session/56ab358f-f34a-4be5-a576-ad2b0be4c26f] with no body
2018-07-25 09:02:07:823 - info: [debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"56ab358f-f34a-4be5-a576-ad2b0be4c26f\",\"status\":0,\"value\":\"Session deleted\"}"
2018-07-25 09:02:07:824 - info: [debug] [ADB] Running 'D:\Android\platform-tools\adb.exe -P 5037 -s D1AGAM2720900442 shell am force-stop uk.co.o2.android.ask.enterprise'
2018-07-25 09:02:08:052 - info: [debug] [Logcat] Stopping logcat capture
2018-07-25 09:02:08:052 - info: [debug] [ADB] Removing forwarded port socket connection: 8200 
2018-07-25 09:02:08:052 - info: [debug] [ADB] Running 'D:\Android\platform-tools\adb.exe -P 5037 -s D1AGAM2720900442 forward --remove tcp\:8200'
2018-07-25 09:02:08:083 - info: [debug] [BaseDriver] Event 'newSessionStarted' logged at 1532509328083 (10:02:08 GMT+0100 (GMT Daylight Time))
2018-07-25 09:02:08:083 - error: [W3C] Encountered internal error running command: Error: Cannot start the 'uk.co.o2.android.ask.enterprise' application. Original error: Error executing adbExec. Original error: 'Command 'D\:\\Android\\platform-tools\\adb.exe -P 5037 -s D1AGAM2720900442 shell am start -W -n uk.co.o2.android.ask.enterprise/com.tuenti.messenger.ui.activity.MainActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' timed out after 20000ms'; Stderr: ''; Code: 'null'

**Comment by KazuCocoa** [comment]
You can relax the `appWaitActivity` more with simply `*`. @buchadep 

```
capabilities.setCapability("appWaitActivity", "*");
```

Will something change?

**Comment by buchadep** [comment]
I have tried (*) full or partial(com.tuenti.messenger.*) wild card as suggested and didn't work either

**Comment by KazuCocoa** [comment]
Thanks!

Could you attach the output of `'Command 'D:\Android\platform-tools\adb.exe -P 5037 -s D1AGAM2720900442 shell am start -W -n uk.co.o2.android.ask.enterprise/com.tuenti.messenger.ui.activity.MainActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'` like below?

```
$ adb -P 5037 -s emulator-5554 shell am start -W -n io.appium.android.apis/io.appium.android.apis.ApiDemos -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000
Stopping: io.appium.android.apis
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=io.appium.android.apis/.ApiDemos }
Status: ok
Activity: io.appium.android.apis/.ApiDemos
ThisTime: 389
TotalTime: 389
WaitTime: 429
Complete
```

**Comment by buchadep** [comment]
c:\>D:\Android\platform-tools\adb.exe -P 5037 -s D1AGAM2720900442 shell am start -W -n uk.co.o2.android.ask.enterprise/com.tuenti.messenger.ui.activity.MainActivit
y -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000
Stopping: uk.co.o2.android.ask.enterprise
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=uk.co.o2.android.ask.enterprise/com.tuenti.messenger.ui
.activity.MainActivity }
Status: ok
Activity: uk.co.o2.android.ask.enterprise/com.tuenti.messenger.secure.session.view.PinActivity
ThisTime: 841
TotalTime: 50572
WaitTime: 4362
Complete

**Comment by mykola-mokhnach** [comment]
50 seconds for app load? that's serious. Try to adjust `appWaitDuration`

**Comment by KazuCocoa** [comment]
Yeah, as @mykola-mokhnach said, you need to coordinate `appWaitDuration` over below. @buchadep 

```
ThisTime: 841
TotalTime: 50572
WaitTime: 4362
```

Appium waits for the adb response. The default value is `20000` ms. But your app probably requires almost 50 seconds.
