### ISSUE TITLE
Expected condition incorrectly fails due to NoSuchElementException?

### ISSUE THREAD

**Issue by michaelnuovo** [appium/appium#11106]
## The problem

I am using `WebDriverWait` with `ExpectedConditions.not(presenceOfElementLocated(by))`.

`WebDriverWait` throws a `TimeoutException` caused by a `NoSuchElementException`. If the am using `ExpectedConditions.not(presenceOfElementLocated(by))` shouldn't a `NoSuchElementException` cuase the expected condition to test true?

new WebDriverWait(user.mDriver, timeOut)
        .ignoring(StaleElementReferenceException.class)
        .ignoring(NullPointerException.class)
        .ignoring(java.lang.ClassCastException.class)
        .ignoring(org.openqa.selenium.NoSuchElementException.class)
        .until(ExpectedConditions.not(presenceOfElementLocated(by)));

Here is the stack trace

org.openqa.selenium.TimeoutException: Expected condition failed: waiting for condition to not be valid: presence of element located by: By.id: talkerView (tried for 5 second(s) with 500 milliseconds interval)
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:81)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:271)
	at srcNew.Libs.Views.ViewUtils.lambda$isElementNotPresentBy$7(ViewUtils.java:848)
	at srcNew.Libs.Views.ViewUtils.evaluate(ViewUtils.java:1003)
	at srcNew.Libs.Views.ViewUtils.isElementNotPresentBy(ViewUtils.java:850)
	at srcNew.Libs.Framework.Client.AdrClient.verifyUserNotInCall(AdrClient.java:2558)
	at srcNew.Libs.Framework.Client.AdrClient.verifyUserNotInCall(AdrClient.java:61)
	at srcNew.Libs.Framework.Client.GenericClient.verifyUserNotInCall(GenericClient.java:961)
	at srcNew.Tests.Concourse.GroupCalls.GroupCalls.test(GroupCalls.java:44)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:105)
	at org.junit.runner.JUnitCore.runClasses(JUnitCore.java:62)
	at org.junit.runner.JUnitCore.runClasses(JUnitCore.java:49)
	at srcNew.Libs.TestRunner.TestRunner.runWithResult(TestRunner.java:388)
	at srcNew.Libs.TestRunner.TestRunner.runTest(TestRunner.java:207)
	at srcNew.Libs.TestRunner.TestRunner.runAll(TestRunner.java:163)
	at srcNew.Libs.TestRunner.Test.run(Test.java:42)
	at srcNew.Tests.Concourse.run_some_adr_pc_local.main(run_some_adr_pc_local.java:30)
Caused by: org.openqa.selenium.NoSuchElementException: Cannot locate an element using By.id: talkerView
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
System info: host: 'localhost.localdomain', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.14-300.fc27.x86_64', java.version: '10.0.1'
Driver info: driver.version: unknown
	at org.openqa.selenium.support.ui.ExpectedConditions.lambda$findElement$0(ExpectedConditions.java:896)
	at java.base/java.util.Optional.orElseThrow(Optional.java:397)
	at org.openqa.selenium.support.ui.ExpectedConditions.findElement(ExpectedConditions.java:895)
	at org.openqa.selenium.support.ui.ExpectedConditions.access$000(ExpectedConditions.java:44)
	at org.openqa.selenium.support.ui.ExpectedConditions$6.apply(ExpectedConditions.java:183)
	at org.openqa.selenium.support.ui.ExpectedConditions$6.apply(ExpectedConditions.java:180)
	at org.openqa.selenium.support.ui.ExpectedConditions$30.apply(ExpectedConditions.java:874)
	at org.openqa.selenium.support.ui.ExpectedConditions$30.apply(ExpectedConditions.java:871)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:248)
	... 46 more

## Environment

appium 1.8.1
osx high sierra 10.13.5
node 8.11.1
platform under test = android
simulator

## Details

If this is a bug, I will post Appium logs

## Code To Reproduce Issue [ Good To Have ]

new WebDriverWait(user.mDriver, timeOut)
        .ignoring(StaleElementReferenceException.class)
        .ignoring(NullPointerException.class)
        .ignoring(java.lang.ClassCastException.class)
        .ignoring(org.openqa.selenium.NoSuchElementException.class)
        .until(ExpectedConditions.not(presenceOfElementLocated(by)));

**Comment by mykola-mokhnach** [comment]
Yes the log is required. Might be a duplicate of 
https://github.com/appium/java-client/issues/976 though
