### ISSUE TITLE
Appium - An unknown server-side error...

### ISSUE THREAD

**Issue by AvrahamAtia** [appium/appium#11112]
The problem happen sometime, not always.

Environment
Desktop OS/version used to run Appium: 10.2.6
Node.js version (unless using Appium.app|exe): v7.5.0
Mobile platform/version under test: iOS
Real device or emulator/simulator: real device / simulator
Appium CLI or Appium.app|exe: 1.8.1

Details
Error: 
An unknown server-side error occurred while processing the command. Original error: An unknown server-side error occurred while processing the command. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 4.25 seconds
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'iOS-Auto-Haifa1.local', ip: '172.22.218.102', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.4', java.version: '1.8.0_171'
Driver info: infra.driver.initializations.IOS****Driver
Capabilities [{app=/Staging/Staging8.13.ipa, networkConnectionEnabled=false, commandTimeout=60, databaseEnabled=false, deviceName=Gal’s iPhone, platform=MAC, privateDevicesOnly=true, platformVersion=11.2.1, webStorageEnabled=false, locationContextEnabled=false, automationName=XCUITest, browserName=, takesScreenshot=true, javascriptEnabled=true, udid=e6918fd0c48522dbb1f32920fde1392f4311fd69, platformName=iOS}]
Session ID: c80efc4c-06ba-48de-8277-c073f2065a50
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: An unknown server-side error occurred while processing the command. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 4.25 seconds
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'iOS-Auto-Haifa1.local', ip: '172.22.218.102', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.4', java.version: '1.8.0_171'
Driver info: infra.driver.initializations.IOS***Driver
Capabilities [{app=/Staging/Staging8.13.ipa, networkConnectionEnabled=false, commandTimeout=60, databaseEnabled=false, deviceName=Gal’s iPhone, platform=MAC, privateDevicesOnly=true, platformVersion=11.2.1, webStorageEnabled=false, locationContextEnabled=false, automationName=XCUITest, browserName=, takesScreenshot=true, javascriptEnabled=true, udid=e6918fd0c48522dbb1f32920fde1392f4311fd69, platformName=iOS}]
Session ID: c80efc4c-06ba-48de-8277-c073f2065a50
	at sun.reflect.GeneratedConstructorAccessor16.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:40)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:235)
	at org.openqa.selenium.remote.RemoteWebDriver.getPageSource(RemoteWebDriver.java:511)
	at infra.driver.actions.IosActionBotImpl.getPageSource(IosActionBotImpl.java:524)
	at infra.pages.checkout.ios.CheckoutIP.waitForPageLoad(CheckoutIP.java:53)
	at infra.pages.checkout.ios.CheckoutIP.<init>(CheckoutIP.java:42)
	at infra.pages.cart.ios.CartTabIP.goToCheckoutScreen(CartTabIP.java:145)
	at tests.base.BaseiOSTest.checkout(BaseiOSTest.java:99)
	at tests.iOS.Checkout.FullCartCheckoutTest.start_logged_in(FullCartCheckoutTest.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by AvrahamAtia** [comment]
<script src="https://gist.github.com/AvrahamAtia/c4d6b5263b17fa146eb00fc34ac94895.js"></script>

**Comment by mykola-mokhnach** [comment]
Upgrade to appium@beta and try again

**Comment by AvrahamAtia** [comment]
Sorry I am working with 1.8.1!!

**Comment by mykola-mokhnach** [comment]
Also the device log is needed

**Comment by AvrahamAtia** [comment]
I don't have device log...
