### ISSUE TITLE
 [RemoteDebugger] WebKitRPCWarning: Did not find handler for the message

### ISSUE THREAD

**Issue by mayureshshirodkar** [appium/appium#11131]
## The problem

When switching from Native context to Web view context, an error message is being thrown, since it is not handled terminates the session, resulting in test cases failing.

Seen this issue on iOS only.
iOSCapabilities.setCapability("startIWDP",true);
iOSCapabilities.setCapability("autoWebview", true);		iOSCapabilities.setCapability("autoWebviewTimeout", 7000);

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.2 Beta
* Desktop OS/version used to run Appium: MAC OS 10.13.6
* Mobile platform/version under test: 11.4.1
* Real device or emulator/simulator: iPhone 6
* Appium CLI or Appium.app|exe:

## Details

```
2018-07-31 08:19:49:534 - [RemoteDebugger] WebKitRPCWarning: Did not find handler for the message
2018-07-31 08:19:49:534 - [RemoteDebugger]     at WebKitRpcClient.receive (/usr/local/lib/node_modules/appium/node_modules/appium-remote-debugger/lib/webkit-rpc-client.js:142:25)
2018-07-31 08:19:49:535 - [RemoteDebugger]     at WebSocket.emit (events.js:180:13)
2018-07-31 08:19:49:535 - [RemoteDebugger]     at Receiver.receiverOnMessage (/usr/local/lib/node_modules/appium/node_modules/ws/lib/websocket.js:720:20)
2018-07-31 08:19:49:535 - [RemoteDebugger]     at Receiver.emit (events.js:180:13)
2018-07-31 08:19:49:535 - [RemoteDebugger]     at Receiver.dataMessage (/usr/local/lib/node_modules/appium/node_modules/ws/lib/receiver.js:414:14)
2018-07-31 08:19:49:535 - [RemoteDebugger]     at Receiver.getData (/usr/local/lib/node_modules/appium/node_modules/ws/lib/receiver.js:346:17)
2018-07-31 08:19:49:535 - [RemoteDebugger]     at Receiver.startLoop (/usr/local/lib/node_modules/appium/node_modules/ws/lib/receiver.js:133:22)
2018-07-31 08:19:49:535 - [RemoteDebugger]     at Receiver._write (/usr/local/lib/node_modules/appium/node_modules/ws/lib/receiver.js:69:10)
2018-07-31 08:19:49:535 - [RemoteDebugger]     at doWrite (_stream_writable.js:410:12)
2018-07-31 08:19:49:535 - [RemoteDebugger]     at writeOrBuffer (_stream_writable.js:396:5)
2018-07-31 08:19:49:535 - [RemoteDebugger]     at Receiver.Writable.write (_stream_writable.js:294:11)
2018-07-31 08:19:49:535 - [RemoteDebugger]     at Socket.socketOnData (/usr/local/lib/node_modules/appium/node_modules/ws/lib/websocket.js:795:35)
2018-07-31 08:19:49:536 - [RemoteDebugger]     at Socket.emit (events.js:180:13)
2018-07-31 08:19:49:536 - [RemoteDebugger]     at addChunk (_stream_readable.js:274:12)
2018-07-31 08:19:49:536 - [RemoteDebugger]     at readableAddChunk (_stream_readable.js:261:11)
2018-07-31 08:19:49:536 - [RemoteDebugger]     at Socket.Readable.push (_stream_readable.js:218:10)
2018-07-31 08:19:49:536 - [RemoteDebugger]     at TCP.onread (net.js:581:20)
2018-07-31 08:19:49:539 - uncaughtException: Did not find handler for the message
```

## Link to Appium logs

Gist link:
https://gist.github.com/mayureshshirodkar/4d99d2971a820fbe75e4fe4c6beb4cbb

## Code To Reproduce Issue [ Good To Have ]

getWebDriver().context("WEBVIEW_1");

**Comment by mykola-mokhnach** [comment]
What is the version of appium-remote-debugger module on your system?

**Comment by mayureshshirodkar** [comment]
appium-remote-debugger module should be at appium-remote-debugger module appium-remote-debugger@3.18.0

**Comment by mykola-mokhnach** [comment]
Can you please try to apply https://github.com/appium/appium-remote-debugger/pull/90/files to your local source and check if it helps?

**Comment by mayureshshirodkar** [comment]
seems to be the same issue still. Pasting the logs below.

```
2018-07-31 12:02:12:952 - [HTTP] --> POST /wd/hub/session/237131d1-a853-44ae-b176-f054344e8d92/context
2018-07-31 12:02:12:952 - [HTTP] {"name":"WEBVIEW_1"}
2018-07-31 12:02:12:952 - [debug] [W3C] Calling AppiumDriver.setContext() with args: ["WEBVIEW_1","237131d1-a853-44ae-b176-f054344e8d92"]
2018-07-31 12:02:12:953 - [debug] [XCUITest] Executing command 'setContext'
2018-07-31 12:02:12:955 - [debug] [iOS] Attempting to set context to 'WEBVIEW_1'
2018-07-31 12:02:12:957 - [debug] [RemoteDebugger] WebKit debugger web socket connected to url: ws://localhost:27753/devtools/page/1
2018-07-31 12:02:12:957 - [debug] [RemoteDebugger] Starting to listen for JavaScript console
2018-07-31 12:02:12:957 - [debug] [RemoteDebugger] Sending WebKit data: {"method":"Console.enable","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true}}
2018-07-31 12:02:12:957 - [debug] [RemoteDebugger] Webkit response timeout: 20000
2018-07-31 12:02:12:973 - [debug] [RemoteDebugger] Received WebKit data: '{"result":{"result":{"type":"string","value":"{\"status\":0,\"value\":[{\"ELEMENT\":\":wdc:1533038476696\"}]}"},"wasThrown":false},"id":62}'
2018-07-31 12:02:12:980 - [RemoteDebugger] WebKitRPCWarning: Did not find handler for the message
2018-07-31 12:02:12:980 - [RemoteDebugger]     at WebKitRpcClient.receive (/usr/local/lib/node_modules/appium/node_modules/appium-remote-debugger/lib/webkit-rpc-client.js:144:25)
2018-07-31 12:02:12:980 - [RemoteDebugger]     at WebSocket.emit (events.js:180:13)
2018-07-31 12:02:12:980 - [RemoteDebugger]     at Receiver.receiverOnMessage (/usr/local/lib/node_modules/appium/node_modules/appium-remote-debugger/node_modules/ws/lib/websocket.js:720:20)
2018-07-31 12:02:12:980 - [RemoteDebugger]     at Receiver.emit (events.js:180:13)
2018-07-31 12:02:12:980 - [RemoteDebugger]     at Receiver.dataMessage (/usr/local/lib/node_modules/appium/node_modules/appium-remote-debugger/node_modules/ws/lib/receiver.js:414:14)
2018-07-31 12:02:12:981 - [RemoteDebugger]     at Receiver.getData (/usr/local/lib/node_modules/appium/node_modules/appium-remote-debugger/node_modules/ws/lib/receiver.js:346:17)
2018-07-31 12:02:12:981 - [RemoteDebugger]     at Receiver.startLoop (/usr/local/lib/node_modules/appium/node_modules/appium-remote-debugger/node_modules/ws/lib/receiver.js:133:22)
2018-07-31 12:02:12:981 - [RemoteDebugger]     at Receiver._write (/usr/local/lib/node_modules/appium/node_modules/appium-remote-debugger/node_modules/ws/lib/receiver.js:69:10)
2018-07-31 12:02:12:981 - [RemoteDebugger]     at doWrite (_stream_writable.js:410:12)
2018-07-31 12:02:12:981 - [RemoteDebugger]     at writeOrBuffer (_stream_writable.js:396:5)
2018-07-31 12:02:12:981 - [RemoteDebugger]     at Receiver.Writable.write (_stream_writable.js:294:11)
2018-07-31 12:02:12:981 - [RemoteDebugger]     at Socket.socketOnData (/usr/local/lib/node_modules/appium/node_modules/appium-remote-debugger/node_modules/ws/lib/websocket.js:795:35)
2018-07-31 12:02:12:981 - [RemoteDebugger]     at Socket.emit (events.js:180:13)
2018-07-31 12:02:12:981 - [RemoteDebugger]     at addChunk (_stream_readable.js:274:12)
2018-07-31 12:02:12:981 - [RemoteDebugger]     at readableAddChunk (_stream_readable.js:261:11)
2018-07-31 12:02:12:982 - [RemoteDebugger]     at Socket.Readable.push (_stream_readable.js:218:10)
2018-07-31 12:02:12:982 - [RemoteDebugger]     at TCP.onread (net.js:581:20)
2018-07-31 12:02:12:984 - uncaughtException: Did not find handler for the message
	{"date":"Tue Jul 31 2018 17:32:12 GMT+0530 (IST)","process":{"pid":84516,"uid":891244515,"gid":1897370479,"cwd":"/Users/shirodkm","execPath":"/usr/local/bin/node","version":"v9.11.1","argv":["/usr/local/bin/node","/usr/local/bin/appium","-a","127.0.0.1","-p","4725","--log-timestamp"],"memoryUsage":{"rss":198397952,"heapTotal":127315968,"heapUsed":113150872,"external":519301}},"os":{"loadavg":[3.595703125,3.05078125,2.693359375],"uptime":433545},"trace":[{"column":25,"file":"/usr/local/lib/node_modules/appium/node_modules/appium-remote-debugger/lib/webkit-rpc-client.js","function":"WebKitRpcClient.receive","line":144,"method":"receive","native":false},{"column":13,"file":"events.js","function":"WebSocket.emit","line":180,"method":"emit","native":false},{"column":20,"file":"/usr/local/lib/node_modules/appium/node_modules/appium-remote-debugger/node_modules/ws/lib/websocket.js","function":"Receiver.receiverOnMessage","line":720,"method":"receiverOnMessage","native":false},{"column":13,"file":"events.js","function":"Receiver.emit","line":180,"method":"emit","native":false},{"column":14,"file":"/usr/local/lib/node_modules/appium/node_modules/appium-remote-debugger/node_modules/ws/lib/receiver.js","function":"Receiver.dataMessage","line":414,"method":"dataMessage","native":false},{"column":17,"file":"/usr/local/lib/node_modules/appium/node_modules/appium-remote-debugger/node_modules/ws/lib/receiver.js","function":"Receiver.getData","line":346,"method":"getData","native":false},{"column":22,"file":"/usr/local/lib/node_modules/appium/node_modules/appium-remote-debugger/node_modules/ws/lib/receiver.js","function":"Receiver.startLoop","line":133,"method":"startLoop","native":false},{"column":10,"file":"/usr/local/lib/node_modules/appium/node_modules/appium-remote-debugger/node_modules/ws/lib/receiver.js","function":"Receiver._write","line":69,"method":"_write","native":false},{"column":12,"file":"_stream_writable.js","function":"doWrite","line":410,"method":null,"native":false},{"column":5,"file":"_stream_writable.js","function":"writeOrBuffer","line":396,"method":null,"native":false},{"column":11,"file":"_stream_writable.js","function":"Receiver.Writable.write","line":294,"method":"write","native":false},{"column":35,"file":"/usr/local/lib/node_modules/appium/node_modules/appium-remote-debugger/node_modules/ws/lib/websocket.js","function":"Socket.socketOnData","line":795,"method":"socketOnData","native":false},{"column":13,"file":"events.js","function":"Socket.emit","line":180,"method":"emit","native":false},{"column":12,"file":"_stream_readable.js","function":"addChunk","line":274,"method":null,"native":false},{"column":11,"file":"_stream_readable.js","function":"readableAddChunk","line":261,"method":null,"native":false},{"column":10,"file":"_stream_readable.js","function":"Socket.Readable.push","line":218,"method":"push","native":false},{"column":20,"file":"net.js","function":"TCP.onread","line":581,"method":"onread","native":false}],"stack":["WebKitRPCWarning: Did not find handler for the message","    at WebKitRpcClient.receive (/usr/local/lib/node_modules/appium/node_modules/appium-remote-debugger/lib/webkit-rpc-client.js:144:25)","    at WebSocket.emit (events.js:180:13)","    at Receiver.receiverOnMessage (/usr/local/lib/node_modules/appium/node_modules/appium-remote-debugger/node_modules/ws/lib/websocket.js:720:20)","    at Receiver.emit (events.js:180:13)","    at Receiver.dataMessage (/usr/local/lib/node_modules/appium/node_modules/appium-remote-debugger/node_modules/ws/lib/receiver.js:414:14)","    at Receiver.getData (/usr/local/lib/node_modules/appium/node_modules/appium-remote-debugger/node_modules/ws/lib/receiver.js:346:17)","    at Receiver.startLoop (/usr/local/lib/node_modules/appium/node_modules/appium-remote-debugger/node_modules/ws/lib/receiver.js:133:22)","    at Receiver._write (/usr/local/lib/node_modules/appium/node_modules/appium-remote-debugger/node_modules/ws/lib/receiver.js:69:10)","    at doWrite (_stream_writable.js:410:12)","    at writeOrBuffer (_stream_writable.js:396:5)","    at Receiver.Writable.write (_stream_writable.js:294:11)","    at Socket.socketOnData (/usr/local/lib/node_modules/appium/node_modules/appium-remote-debugger/node_modules/ws/lib/websocket.js:795:35)","    at Socket.emit (events.js:180:13)","    at addChunk (_stream_readable.js:274:12)","    at readableAddChunk (_stream_readable.js:261:11)","    at Socket.Readable.push (_stream_readable.js:218:10)","    at TCP.onread (net.js:581:20)"]}
```

**Comment by mykola-mokhnach** [comment]
did you execute `gulp transpile` after replacing the original file and restarted node?

**Comment by mayureshshirodkar** [comment]
Let me try that and let you know

**Comment by mykola-mokhnach** [comment]
the change has been published to beta. You could also try to reinstall your beta and check if it resolves your problem

**Comment by mayureshshirodkar** [comment]
@mykola-mokhnach 
I tried with the latest appium-remote-debugger 3.19.1 and issue still persists.

**Comment by mykola-mokhnach** [comment]
is error the same?

**Comment by mykola-mokhnach** [comment]
Please try the patch from https://github.com/appium/appium-remote-debugger/pull/91

**Comment by mayureshshirodkar** [comment]
@mykola-mokhnach 
The issue is fixed, not getting the error anymore.

**Comment by mykola-mokhnach** [comment]
Cool, can you please show the log?

**Comment by mayureshshirodkar** [comment]
Here you go:
```
2018-08-01 12:05:09:020 - [HTTP] --> POST /wd/hub/session/43a6c76e-808f-4b08-bd26-b68259b0d40b/context
2018-08-01 12:05:09:020 - [HTTP] {"name":"WEBVIEW_1"}
2018-08-01 12:05:09:020 - [debug] [W3C] Calling AppiumDriver.setContext() with args: ["WEBVIEW_1","43a6c76e-808f-4b08-bd26-b68259b0d40b"]
2018-08-01 12:05:09:021 - [debug] [XCUITest] Executing command 'setContext'
2018-08-01 12:05:09:022 - [debug] [iOS] Attempting to set context to 'WEBVIEW_1'
2018-08-01 12:05:09:023 - [debug] [RemoteDebugger] WebKit debugger web socket connected to url: ws://localhost:27753/devtools/page/1
2018-08-01 12:05:09:024 - [debug] [RemoteDebugger] Starting to listen for JavaScript console
2018-08-01 12:05:09:024 - [debug] [RemoteDebugger] Sending WebKit data: {"method":"Console.enable","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true}}
2018-08-01 12:05:09:024 - [debug] [RemoteDebugger] Webkit response timeout: 20000
2018-08-01 12:05:09:081 - [debug] [RemoteDebugger] Received WebKit data: '{"method":"Console.messageAdded","params":{"message":{"source":"console-api","level":"info","text":"%clog (info) 1533125093875 state change started my.feed","type":"log","line":1741,"column":28,"ur...'
2018-08-01 12:05:09:082 - [debug] [RemoteDebugger] Found method 'Console.messageAdded' 
2018-08-01 12:05:09:082 - [debug] [RemoteDebugger] There is no promise scheduled for method 'Console.messageAdded' in message 'undefined'
2018-08-01 12:05:09:082 - [debug] [RemoteDebugger] Received WebKit data: '{"method":"Console.messageAdded","params":{"message":{"source":"console-api","level":"log","text":"Firing document event: urbanairship.registration","type":"log","line":1741,"column":28,"url":"file...'
2018-08-01 12:05:09:083 - [debug] [RemoteDebugger] Found method 'Console.messageAdded' 
2018-08-01 12:05:09:083 - [debug] [RemoteDebugger] There is no promise scheduled for method 'Console.messageAdded' in message 'undefined'
2018-08-01 12:05:09:083 - [debug] [RemoteDebugger] Received WebKit data: '{"method":"Console.messageAdded","params":{"message":{"source":"console-api","level":"info","text":"%clog (info) 1533125098125 state change started my.courseSchedule.term","type":"log","line":1741,...'
2018-08-01 12:05:09:084 - [debug] [RemoteDebugger] Found method 'Console.messageAdded' 
2018-08-01 12:05:09:084 - [debug] [RemoteDebugger] There is no promise scheduled for method 'Console.messageAdded' in message 'undefined'
2018-08-01 12:05:09:084 - [debug] [RemoteDebugger] Received WebKit data: '{"result":{},"id":1}'
2018-08-01 12:05:09:084 - [debug] [RemoteDebugger] Found method 'Console.enable' for message '1'
2018-08-01 12:05:09:085 - [debug] [MJSONWP] Responding to client with driver.setContext() result: null
2018-08-01 12:05:09:085 - [HTTP] <-- POST /wd/hub/session/43a6c76e-808f-4b08-bd26-b68259b0d40b/context 200 65 ms - 76
2018-08-01 12:05:09:085 - [HTTP] 
2018-08-01 12:05:09:088 - [HTTP] --> POST /wd/hub/session/43a6c76e-808f-4b08-bd26-b68259b0d40b/elements
2018-08-01 12:05:09:088 - [HTTP] {"using":"xpath","value":"//button[@id='my-schedule-filter']"}
2018-08-01 12:05:09:088 - [debug] [W3C] Calling AppiumDriver.findElements() with args: ["xpath","//button[@id='my-schedule-filter']","43a6c76e-808f-4b08-bd26-b68259b0d40b"]
2018-08-01 12:05:09:088 - [debug] [XCUITest] Executing command 'findElements'
2018-08-01 12:05:09:089 - [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
2018-08-01 12:05:09:089 - [debug] [BaseDriver] Waiting up to 0 ms for condition
2018-08-01 12:05:09:090 - [debug] [RemoteDebugger] Executing 'find_elements' atom in default context
2018-08-01 12:05:09:090 - [debug] [RemoteDebugger] Sending javascript command (function(){return function(){var k=this;functi...
2018-08-01 12:05:09:090 - [debug] [RemoteDebugger] Sending WebKit data: {"method":"Runtime.evaluate","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true,"expression":"(function(){return function(){var k=this;functi...
2018-08-01 12:05:09:090 - [debug] [RemoteDebugger] Webkit response timeout: 20000
2018-08-01 12:05:09:104 - [debug] [RemoteDebugger] Received WebKit data: '{"result":{"result":{"type":"string","value":"{\"status\":0,\"value\":[{\"ELEMENT\":\":wdc:1533125098033\"}]}"},"wasThrown":false},"id":2}'
2018-08-01 12:05:09:104 - [debug] [RemoteDebugger] Found method 'Runtime.evaluate' for message '2'
2018-08-01 12:05:09:104 - [debug] [RemoteDebugger] Received result for atom 'find_elements' execution: [{"ELEMENT":":wdc:1533125098033"}]
2018-08-01 12:05:09:105 - [debug] [MJSONWP] Responding to client with driver.findElements() result: [{"ELEMENT":"5185"}]
2018-08-01 12:05:09:106 - [HTTP] <-- POST /wd/hub/session/43a6c76e-808f-4b08-bd26-b68259b0d40b/elements 200 18 ms - 92

```

**Comment by imurchie** [comment]
The error itself shouldn't be happening with the most recent `appium-remote-debugger`. There was a problem with the console logging, which has already been fixed.
