### ISSUE TITLE
It is impossible to create a new session because 'createSession' which takes HttpClient, InputStream and long was not found or it is not accessible

### ISSUE THREAD

**Issue by hm2286** [appium/appium#11136]
## The problem

I am trying to launch the android application through appium script. It is installed successfully but not getting launch.
## Environment
Capabilities: [Appium] Capabilities:
[Appium]   browserName: Android
[Appium]   platformName: android
[Appium]   skipUnlock: true
[Appium]   autoGrantPermissions: true
[Appium]   automationName: uiautomator2
[Appium]   noReset: true
[Appium]   platformVersion: 8.0.0

## Details
```
[RemoteTestNG] detected TestNG version 6.14.2
Appium Test Execution started
FAILED CONFIGURATION: @BeforeMethod setUp
org.openqa.selenium.WebDriverException: It is impossible to create a new session because 'createSession' which takes HttpClient, InputStream and long was not found or it is not accessible
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T15:15:03.216Z'
System info: host: 'BDC7-L-23ZN6C2', ip: '169.254.143.143', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_161'
Driver info: driver.version: AndroidDriver
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:182)
	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:196)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:218)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:207)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:84)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:94)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:88)
	at AWS_Appium.AWS_Appium.RefApp.setUp(RefApp.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.Delegati***ethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:520)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.Delegati***ethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:172)
	... 41 more
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Cannot start the '***' application. Original error: Error executing adbExec. Original error: 'Command ''C:\\Program Files (x86)\\Android\\android-sdk\\platform-tools\\adb.exe' -P 5037 -s ce0617164914d51704 shell am start -W -n ***/***.*** -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' exited with code 4294967295'; Stderr: 'Security exception: Permission Denial: starting Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=***/.*** } from null (pid=21196, uid=2000) not exported from uid 10331

java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=***/.*** } from null (pid=21196, uid=2000) not exported from uid 10331
	at com.android.server.am.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1921)
	at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:630)
	at com.android.server.am.ActivityStarter.startActivityLocked(ActivityStarter.java:410)
	at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1271)
	at com.android.server.am.ActivityManagerService.startActivityAndWait(ActivityManagerService.java:6215)
	at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:419)
	at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:142)
	at android.os.ShellCommand.exec(ShellCommand.java:96)
	at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:18739)
	at android.os.Binder.shellCommand(Binder.java:581)
	at android.os.Binder.onTransact(Binder.java:481)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:4767)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3818)
	at android.os.Binder.execTransact(Binder.java:682)'; Code: '4294967295'
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T15:15:03.216Z'
System info: host: 'BDC7-L-23ZN6C2', ip: '169.254.143.143', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_161'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot start the '***' application. Original error: Error executing adbExec. Original error: 'Command ''C:\\Program Files (x86)\\Android\\android-sdk\\platform-tools\\adb.exe' -P 5037 -s ce0617164914d51704 shell am start -W -n ***/***.*** -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' exited with code 4294967295'; Stderr: 'Security exception: Permission Denial: starting Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=***/.*** } from null (pid=21196, uid=2000) not exported from uid 10331
```

## Code To Reproduce Issue [ Good To Have ]
```
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability(CapabilityType.BROWSER_NAME, "Android");
capabilities.setCapability("deviceName", "Galaxy S8");	//Galaxy S8	//Moto X Play
capabilities.setCapability("platformVersion", "8.0.0"); //8.0.0
capabilities.setCapability("platformName", "Android");
capabilities.setCapability("automationName","uiautomator2");
capabilities.setCapability("app", app.getAbsolutePath());
capabilities.setCapability("appPackage", "***");
capabilities.setCapability("appActivity","***");
capabilities.setCapability("noReset", true);
capabilities.setCapability("skipUnlock", true);
capabilities.setCapability("autoGrantPermissions","true");
capabilities.setCapability("clearSystemFiles","true");
			
URL url = new URL("http://127.0.0.1:4723/wd/hub");
driver = new AndroidDriver(url, capabilities); //AndroidDriver<MobileElement>
driver.manage().timeouts().implicitlyWait(80, TimeUnit.SECONDS);
Thread.sleep(1000);
```

**Comment by mykola-mokhnach** [comment]
You must provide proper activity/waitActivity names. Closed as duplicate:
https://github.com/appium/appium/search?q=%22Permission+Denial%22&unscoped_q=%22Permission+Denial%22&type=Issues

**Comment by imurchie** [comment]
Remove 
```
capabilities.setCapability(CapabilityType.BROWSER_NAME, "Android");
```

**Comment by mykola-mokhnach** [comment]
The activity, which starts at first, is not necessary the same as the main app activity. This has been already discussed several times in the duplicated issues.

**Comment by hm2286** [comment]
@imurchie : Removed browser capability, issue still persist.
@mykola-mokhnach : Defined appwaitactivity  but no better luck. (@Note: Defined appWaitActivity is same as appActivity)
capabilities.setCapability("appWaitActivity ","***");

**Appium Log:**
 Encountered internal error running command: Error: Cannot start the '***' application. Original error: Error executing adbExec. Original error: 'Command ''C:\\Program Files (x86)\\Android\\android-sdk\\platform-tools\\adb.exe' -P 5037 -s ce0617164914d51704 shell am start -W -n *** -S' exited with code 4294967295'; Stderr: 'Security exception: Permission Denial: starting Intent { flg=0x10000000 cmp=***} from null (pid=27504, uid=2000) not exported from uid 10334
[W3C] 
[W3C] java.lang.SecurityException: Permission Denial: starting Intent { flg=0x10000000 cmp=*** } from null (pid=27504, uid=2000) not exported from uid 10334

Please suggest.

**Comment by mykola-mokhnach** [comment]
There are no other suggestions. This is not an issue of appium.

**Comment by hm2286** [comment]
Hi, I changed the appactivity by using * at the end & some other changes in calling the driver. App is launched successfully but got crash again with below error message
**Code changes:**
AppiumDriver driver = new AndroidDriver<MobileElement>(url, capabilities);

**Appium Log:**
[W3C] Encountered internal error running command: Error: Cannot start the '***' application. Original error: '***.' or '***.***.' never started
[W3C]     at ADB.callee$0$0$ (C:\Users\abc\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\apk-utils.js:125:11)
[W3C]     at tryCatch (C:\Users\abc\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\abc\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\abc\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[W3C]     at GeneratorFunctionPrototype.invoke (C:\Users\abc\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[W3C]     at 

Please suggest.
