### ISSUE TITLE
Unhandled rejection TypeError: Cannot read property 'count' of undefined

### ISSUE THREAD

**Issue by taitranvungle** [appium/appium#11152]
## The problem

Error "Unhandled rejection TypeError: Cannot read property 'count' of undefined" often throws after finish executed tests (self.driver.quit()). It causes the test failed

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Last Appium version that did not exhibit the issue (if applicable): 1.7.2
* Desktop OS/version used to run Appium: MacOS 10.13.6
* Node.js version (unless using Appium.app|exe): 10.1.0
* Mobile platform/version under test: iOS 11.4
* Real device or emulator/simulator: iPhone 7 - real device
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs

Unhandled rejection TypeError: Cannot read property 'count' of undefined
    at IOSLog.stopCapture$ (/usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/lib/device-log/ios-log.js:213:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at new Promise (<anonymous>)
    at new F (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at IOSLog.stopCapture (/usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/build/lib/device-log/ios-log.js:514:34)
    at XCUITestDriver.deleteSession$ (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:543:30)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by mykola-mokhnach** [comment]
This should be fixed in appium@beta

**Comment by taitranvungle** [comment]
Thank you @mykola-mokhnach , this error no longer appears in appium v1.8.2-beta
