### ISSUE TITLE
Cannot find elements when the selector is null.

### ISSUE THREAD

**Issue by CPPAlien** [appium/appium#11168]
## The problem
When I use findElement, I encountered the error below. 

```
java.lang.IllegalArgumentException: Cannot find elements when the selector is null.
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:314)
	at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:62)
	at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.findElement(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementById(RemoteWebDriver.java:363)
	at io.appium.java_client.DefaultGenericMobileDriver.findElementById(DefaultGenericMobileDriver.java:70)
	at io.appium.java_client.AppiumDriver.findElementById(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.findElementById(AndroidDriver.java:1)
	at com.qunhe.avocado.lib.Avocado.tap(Avocado.java:53)
	at com.qunhe.avocado.steps.MyStepdefs.tap(MyStepdefs.java:48)
	at ✽.tap "OK"(/Users/qunhe/IDEA/KoolTest/src/test/features/xigua.feature:3)
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.2-beta
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: android
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Link to Appium logs

https://gist.github.com/CPPAlien/3f9bfb849fe8033293ec6dcbc11d4022

**Comment by mykola-mokhnach** [comment]
This looks like a problem with the client code. I don't observe any issues in the attached log

**Comment by imurchie** [comment]
There is also no indication of a find element call ever getting to the server.
