### ISSUE TITLE
After upgrading to latest version of appium 1.8.2-beta error org.openqa.selenium.WebDriverException: Returned value cannot be converted to WebElement appears

### ISSUE THREAD

**Issue by mbogicevic** [appium/appium#11170]
## The problem

Hi,
After upgrading to latest version of appium 1.8.2-beta I get error "org.openqa.selenium.WebDriverException: Returned value cannot be converted to WebElement" appears when findElement method is called. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.2-beta
* Last Appium version that did not exhibit the issue (if applicable): 1.8.2-beta (3 months ago)
* Desktop OS/version used to run Appium: Mac OS X 10.11.6, Linux
* Node.js version (unless using Appium.app|exe): 7.5.0
* Mobile platform/version under test: Android
* Real device or emulator/simulator: emulator Nexus 8.1
* Appium CLI or Appium.app|exe:

Log:
`org.openqa.selenium.WebDriverException: Returned value cannot be converted to WebElement: {error=no such element, message=no such element: Unable to locate element: {"method":"xpath","selector":"//ion-col[@class='user col'][1]//button"}
  (Session info: chrome=68.0.3440.91)
  (Driver info: chromedriver=2.41.578706 (5f725d1b4f0a4acbf5259df887244095596231db),platform=Mac OS X 10.11.6 x86_64), stacktrace=NoSuchElementError: no such element: Unable to locate element: {"method":"xpath","selector":"//ion-col[@class='user col'][1]//button"}
  (Session info: chrome=68.0.3440.91)
  (Driver info: chromedriver=2.41.578706 (5f725d1b4f0a4acbf5259df887244095596231db),platform=Mac OS X 10.11.6 x86_64)
    at errorFromMJSONWPStatusCode (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/node_modules/appium-base-driver/lib/protocol/errors.js:784:12)
    at ProxyRequestError.getActualError (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/node_modules/appium-base-driver/lib/protocol/errors.js:681:14)
    at asyncHandler$ (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:354:25)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)}
Build info: version: '3.13.0', revision: '2f0d292', time: '2018-06-25T15:24:21.231Z'
System info: host: 'dt2017016', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-132-generic', java.version: '1.8.0_181'
Driver info: driver.version: AndroidDriver`

**Comment by mykola-mokhnach** [comment]
Can you please attach full server log?

**Comment by mykola-mokhnach** [comment]
@dpgraham It looks like java client does not properly parse our response and does not count it as an error, so it tries to unwrap the body and obviously fails to do that

**Comment by mykola-mokhnach** [comment]
It seems that it only happens if the session is proxied to chromedriver

**Comment by mbogicevic** [comment]
After changing java client problem was solved, you can close this issue.

**Comment by saikrishna321** [comment]
@mbogicevic what did u change to ?

**Comment by mbogicevic** [comment]
@saikrishna321 i change it in 6.1.0
