### ISSUE TITLE
python + appium 1.8.1 can not use  driver.implicitly_wait(10)

### ISSUE THREAD

**Issue by AlexDingSZ** [appium/appium#11192]
## The problem

Can't use  driver.implicitly_wait after i install appium server 1.8.1

## Environment

* Appium server 1.8.1
*Appium-Python-Client :0.28
*Python :3.6
*Test on real device 
* Android api :22
* node.js :v8.11.3
start appium command :appium --address 127.0.0.1 --port 4723 --session-override --platform-name Android --platform-version 22 --automation-name Appium --log-timestamp --local-timezone --no-reset

## Details

I want use implicitly  wait， the code is ：
driver.implicitly_wait(10)

but get the error message :selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: '[object Object]' type is not supported for MJSONWP timeout

## Link to Appium logs
2018-08-16 16:49:11:569 - [debug] [BaseDriver] Event 'newSessionStarted' logged
at 1534409351569 (16:49:11 GMT+0800 (中国标准时间))
2018-08-16 16:49:11:571 - [debug] [W3C] Responding to client with driver.createS
ession() result: {"capabilities":{"platform":"LINUX","webStorageEnabled":false,"
takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkC
onnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"
platformName":"Android","platformVersion":"5.1","automationName":"Uiautomator2",
"noReset":true,"deviceName":"Y9K0214B13002052","appPackage":"com.youdao.note","u
nicodeKeyboard":true,"resetKeyboard":true,"appActivity":"com.youdao.note.activit
y2.MainActivity"},"platformName":"Android","platformVersion":"5.1.1","automation
Name":"Uiautomator2","noReset":true,"deviceName":"Y9K0214B13002052","appPackage"
:"com.youdao.note","unicodeKeyboard":true,"resetKeyboard":true,"appActivity":"co
m.youdao.note.activity2.MainActivity","deviceUDID":"Y9K0214B13002052","deviceScr
eenSize":"1080x1920","deviceScreenDensity":480,"deviceModel":"HUAWEI MT7-TL10","
deviceManufacturer":"HUAWEI","deviceApiLevel":22,"pixelRatio":3,"statBarHeight":
75,"viewportRect":{"left":0,"top":75,"width":1080,"height":1737}}}
2018-08-16 16:49:11:573 - [HTTP] <-- POST /wd/hub/session 200 22361 ms - 1070
2018-08-16 16:49:11:574 - [HTTP]
2018-08-16 16:49:11:578 - [HTTP] --> POST /wd/hub/session/bec302c2-a8f9-4043-b49
7-36fc36f60e8a/timeouts
2018-08-16 16:49:11:580 - [HTTP] {"implicit":10000,"sessionId":"bec302c2-a8f9-40
43-b497-36fc36f60e8a"}
2018-08-16 16:49:11:581 - [debug] [W3C] Calling AppiumDriver.timeouts() with arg
s: [{"protocol":"W3C","implicit":10000},"bec302c2-a8f9-4043-b497-36fc36f60e8a"]
2018-08-16 16:49:11:584 - [debug] [BaseDriver] MJSONWP timeout arguments: {"type
":{"protocol":"W3C","implicit":10000},"ms":"bec302c2-a8f9-4043-b497-36fc36f60e8a
"}}
2018-08-16 16:49:11:586 - [W3C] Encountered internal error running command: Erro
r: '[object Object]' type is not supported for MJSONWP timeout
2018-08-16 16:49:11:587 - [W3C]     at AndroidUiautomator2Driver.callee$0$0$ (C:
\Users\Administrator\AppData\Roaming\npm\node_modules\appium\node_modules\_appiu
m-base-driver@3.5.1@appium-base-driver\lib\basedriver\commands\timeout.js:31:15)

2018-08-16 16:49:11:588 - [W3C]     at tryCatch (C:\Users\Administrator\AppData\
Roaming\npm\node_modules\appium\node_modules\_babel-runtime@5.8.24@babel-runtime
\regenerator\runtime.js:67:40)
2018-08-16 16:49:11:589 - [W3C]     at GeneratorFunctionPrototype.invoke [as _in
voke] (C:\Users\Administrator\AppData\Roaming\npm\node_modules\appium\node_modul
es\_babel-runtime@5.8.24@babel-runtime\regenerator\runtime.js:315:22)
2018-08-16 16:49:11:590 - [W3C]     at GeneratorFunctionPrototype.prototype.(ano
nymous function) [as next] (C:\Users\Administrator\AppData\Roaming\npm\node_modu
les\appium\node_modules\_babel-runtime@5.8.24@babel-runtime\regenerator\runtime.
js:100:21)
2018-08-16 16:49:11:591 - [W3C]     at invoke (C:\Users\Administrator\AppData\Ro
aming\npm\node_modules\appium\node_modules\_babel-runtime@5.8.24@babel-runtime\r
egenerator\runtime.js:136:37)
2018-08-16 16:49:11:593 - [W3C]     at enqueueResult (C:\Users\Administrator\App
Data\Roaming\npm\node_modules\appium\node_modules\_babel-runtime@5.8.24@babel-ru
ntime\regenerator\runtime.js:185:17)
2018-08-16 16:49:11:595 - [W3C]     at new Promise (<anonymous>)
2018-08-16 16:49:11:596 - [W3C]     at new F (C:\Users\Administrator\AppData\Roa
ming\npm\node_modules\appium\node_modules\_core-js@1.2.7@core-js\library\modules
\$.export.js:30:36)
2018-08-16 16:49:11:597 - [W3C]     at AsyncIterator.enqueue (C:\Users\Administr
ator\AppData\Roaming\npm\node_modules\appium\node_modules\_babel-runtime@5.8.24@
babel-runtime\regenerator\runtime.js:184:12)
2018-08-16 16:49:11:598 - [W3C]     at AsyncIterator.prototype.(anonymous functi
on) [as next] (C:\Users\Administrator\AppData\Roaming\npm\node_modules\appium\no
de_modules\_babel-runtime@5.8.24@babel-runtime\regenerator\runtime.js:100:21)
2018-08-16 16:49:11:599 - [W3C]     at Object.runtime.async (C:\Users\Administra
tor\AppData\Roaming\npm\node_modules\appium\node_modules\_babel-runtime@5.8.24@b
abel-runtime\regenerator\runtime.js:209:12)
2018-08-16 16:49:11:599 - [W3C]     at AndroidUiautomator2Driver.callee$0$0 [as
timeouts] (C:\Users\Administrator\AppData\Roaming\npm\node_modules\appium\node_m
odules\_appium-base-driver@3.5.1@appium-base-driver\build\lib\basedriver\command
s\timeout.js:40:30)
2018-08-16 16:49:11:600 - [W3C]     at C:\Users\Administrator\AppData\Roaming\np
m\node_modules\appium\node_modules\_appium-base-driver@3.5.1@appium-base-driver\
lib\basedriver\driver.js:296:26
2018-08-16 16:49:11:601 - [W3C]     at tryCatcher (C:\Users\Administrator\AppDat
a\Roaming\npm\node_modules\appium\node_modules\_bluebird@2.11.0@bluebird\js\main
\util.js:26:23)
2018-08-16 16:49:11:601 - [W3C]     at Promise._settlePromiseFromHandler (C:\Use
rs\Administrator\AppData\Roaming\npm\node_modules\appium\node_modules\_bluebird@
2.11.0@bluebird\js\main\promise.js:510:31)
2018-08-16 16:49:11:602 - [W3C]     at Promise._settlePromiseAt (C:\Users\Admini
strator\AppData\Roaming\npm\node_modules\appium\node_modules\_bluebird@2.11.0@bl
uebird\js\main\promise.js:584:18)
2018-08-16 16:49:11:603 - [W3C]     at Promise._settlePromiseAtPostResolution (C
:\Users\Administrator\AppData\Roaming\npm\node_modules\appium\node_modules\_blue
bird@2.11.0@bluebird\js\main\promise.js:248:10)
2018-08-16 16:49:11:604 - [W3C]     at Async._drainQueue (C:\Users\Administrator
\AppData\Roaming\npm\node_modules\appium\node_modules\_bluebird@2.11.0@bluebird\
js\main\async.js:128:12)
2018-08-16 16:49:11:604 - [W3C]     at Async._drainQueues (C:\Users\Administrato
r\AppData\Roaming\npm\node_modules\appium\node_modules\_bluebird@2.11.0@bluebird
\js\main\async.js:133:10)
2018-08-16 16:49:11:605 - [W3C]     at Immediate.Async.drainQueues [as _onImmedi
ate] (C:\Users\Administrator\AppData\Roaming\npm\node_modules\appium\node_module
s\_bluebird@2.11.0@bluebird\js\main\async.js:15:14)
2018-08-16 16:49:11:605 - [W3C]     at runCallback (timers.js:810:20)
2018-08-16 16:49:11:606 - [W3C]     at tryOnImmediate (timers.js:768:5)
2018-08-16 16:49:11:606 - [W3C]     at processImmediate [as _immediateCallback]
(timers.js:745:5)
2018-08-16 16:49:11:609 - [HTTP] <-- POST /wd/hub/session/bec302c2-a8f9-4043-b49
7-36fc36f60e8a/timeouts 500 30 ms - 1580
2018-08-16 16:49:11:613 - [HTTP]

## Code To Reproduce Issue [ Good To Have ]
python code :
desired_caps = {}
desired_caps['platformName'] = 'Android'
desired_caps['platformVersion'] = '5.1'
desired_caps['deviceName'] = 'Y9K0214B13002052'
desired_caps['appPackage'] = 'com.youdao.note'
desired_caps['appPackage'] = 'com.youdao.note'
desired_caps['unicodeKeyboard'] = True
desired_caps['resetKeyboard'] = True
desired_caps['automationName'] = 'Uiautomator2'
desired_caps['appActivity'] = 'com.youdao.note.activity2.SplashActivity'
desired_caps['appActivity'] = 'com.youdao.note.activity2.MainActivity'

driver = webdriver.Remote('http://127.0.0.1:4723/wd/hub', desired_caps)
driver.implicitly_wait(10)

pycharm ide error message:
D:\pycode\lesson_framework\venv\Scripts\python3.exe D:/pycode/lesson_framework/case/test_my_youdao.py
Traceback (most recent call last):
  File "D:/pycode/lesson_framework/case/test_my_youdao.py", line 17, in <module>
    driver.implicitly_wait(10)
  File "D:\pycode\lesson_framework\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 892, in implicitly_wait
    'implicit': int(float(time_to_wait) * 1000)})
  File "D:\pycode\lesson_framework\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 314, in execute
    self.error_handler.check_response(response)
  File "D:\pycode\lesson_framework\venv\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "D:\pycode\lesson_framework\venv\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "D:\pycode\lesson_framework\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: '[object Object]' type is not supported for MJSONWP timeout

Process finished with exit code 1

**Comment by AlexDingSZ** [comment]
how to resolve this problem? thanks!

**Comment by KazuCocoa** [comment]
Communication between base driver and uiautomator2 driver looks wrong. Could you try out latest `appium@beta`?
@AlexDingSZ 

```
2018-08-16 16:49:11:573 - [HTTP] <-- POST /wd/hub/session 200 22361 ms - 1070
2018-08-16 16:49:11:574 - [HTTP]
2018-08-16 16:49:11:578 - [HTTP] --> POST /wd/hub/session/bec302c2-a8f9-4043-b49
7-36fc36f60e8a/timeouts
2018-08-16 16:49:11:580 - [HTTP] {"implicit":10000,"sessionId":"bec302c2-a8f9-40
43-b497-36fc36f60e8a"}
2018-08-16 16:49:11:581 - [debug] [W3C] Calling AppiumDriver.timeouts() with arg
s: [{"protocol":"W3C","implicit":10000},"bec302c2-a8f9-4043-b497-36fc36f60e8a"]
2018-08-16 16:49:11:584 - [debug] [BaseDriver] MJSONWP timeout arguments: {"type
":{"protocol":"W3C","implicit":10000},"ms":"bec302c2-a8f9-4043-b497-36fc36f60e8a
"}}
2018-08-16 16:49:11:586 - [W3C] Encountered internal error running command: Erro
r: '[object Object]' type is not supported for MJSONWP timeout
2018-08-16 16:49:11:587 - [W3C] at AndroidUiautomator2Driver.callee$0$0$ (C:
\Users\Administrator\AppData\Roaming\npm\node_modules\appium\node_modules_appiu
m-base-driver@3.5.1@appium-base-driver\lib\basedriver\commands\timeout.js:31:15)
```

**Comment by AlexDingSZ** [comment]
@KazuCocoa  I installed appium 1.8.2-bata and tried again , the result is same

2018-08-16 19:29:42:045 - [debug] [W3C] Responding to client with driver.createS
ession() result: {"capabilities":{"platform":"LINUX","webStorageEnabled":false,"
takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkC
onnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"
platformName":"Android","platformVersion":"5.1","automationName":"Uiautomator2",
"noReset":true,"deviceName":"Y9K0214B13002052","appPackage":"com.youdao.note","u
nicodeKeyboard":true,"resetKeyboard":true,"appActivity":"com.youdao.note.activit
y2.MainActivity"},"platformName":"Android","platformVersion":"5.1.1","automation
Name":"Uiautomator2","noReset":true,"deviceName":"Y9K0214B13002052","appPackage"
:"com.youdao.note","unicodeKeyboard":true,"resetKeyboard":true,"appActivity":"co
m.youdao.note.activity2.MainActivity","deviceUDID":"Y9K0214B13002052","deviceScr
eenSize":"1080x1920","deviceScreenDensity":480,"deviceModel":"HUAWEI MT7-TL10","
deviceManufacturer":"HUAWEI","deviceApiLevel":22,"pixelRatio":3,"statBarHeight":
75,"viewportRect":{"left":0,"top":75,"width":1080,"height":1737}}}
2018-08-16 19:29:42:052 - [HTTP] <-- POST /wd/hub/session 200 48715 ms - 1070
2018-08-16 19:29:42:055 - [HTTP]
2018-08-16 19:29:45:765 - [HTTP] --> POST /wd/hub/session/d7fb7b03-6b0c-4f74-a5a
d-a4833ff6f00c/timeouts
2018-08-16 19:29:45:767 - [HTTP] {"implicit":10000,"sessionId":"d7fb7b03-6b0c-4f
74-a5ad-a4833ff6f00c"}
2018-08-16 19:29:45:770 - [debug] [W3C] Calling AppiumDriver.timeouts() with arg
s: [{"protocol":"W3C","implicit":10000},"d7fb7b03-6b0c-4f74-a5ad-a4833ff6f00c"]
2018-08-16 19:29:45:780 - [debug] [BaseDriver] MJSONWP timeout arguments: {"type
":{"protocol":"W3C","implicit":10000},"ms":"d7fb7b03-6b0c-4f74-a5ad-a4833ff6f00c
"}}
2018-08-16 19:29:45:784 - [W3C] Encountered internal error running command: Erro
r: '[object Object]' type is not supported for MJSONWP timeout
2018-08-16 19:29:45:787 - [W3C]     at AndroidUiautomator2Driver.callee$0$0$ (C:
\Users\Administrator\AppData\Roaming\npm\node_modules\appium\node_modules\_appiu
m-base-driver@3.5.1@appium-base-driver\lib\basedriver\commands\timeout.js:31:15)

2018-08-16 19:29:45:788 - [W3C]     at tryCatch (C:\Users\Administrator\AppData\
Roaming\npm\node_modules\appium\node_modules\_babel-runtime@5.8.24@babel-runtime
\regenerator\runtime.js:67:40)
2018-08-16 19:29:45:789 - [W3C]     at GeneratorFunctionPrototype.invoke [as _in
voke] (C:\Users\Administrator\AppData\Roaming\npm\node_modules\appium\node_modul
es\_babel-runtime@5.8.24@babel-runtime\regenerator\runtime.js:315:22)
2018-08-16 19:29:45:790 - [W3C]     at GeneratorFunctionPrototype.prototype.(ano
nymous function) [as next] (C:\Users\Administrator\AppData\Roaming\npm\node_modu
les\appium\node_modules\_babel-runtime@5.8.24@babel-runtime\regenerator\runtime.
js:100:21)
2018-08-16 19:29:45:791 - [W3C]     at invoke (C:\Users\Administrator\AppData\Ro
aming\npm\node_modules\appium\node_modules\_babel-runtime@5.8.24@babel-runtime\r
egenerator\runtime.js:136:37)
2018-08-16 19:29:45:792 - [W3C]     at enqueueResult (C:\Users\Administrator\App
Data\Roaming\npm\node_modules\appium\node_modules\_babel-runtime@5.8.24@babel-ru
ntime\regenerator\runtime.js:185:17)
2018-08-16 19:29:45:794 - [W3C]     at new Promise (<anonymous>)
2018-08-16 19:29:45:795 - [W3C]     at new F (C:\Users\Administrator\AppData\Roa
ming\npm\node_modules\appium\node_modules\_core-js@1.2.7@core-js\library\modules
\$.export.js:30:36)
2018-08-16 19:29:45:796 - [W3C]     at AsyncIterator.enqueue (C:\Users\Administr
ator\AppData\Roaming\npm\node_modules\appium\node_modules\_babel-runtime@5.8.24@
babel-runtime\regenerator\runtime.js:184:12)
2018-08-16 19:29:45:796 - [W3C]     at AsyncIterator.prototype.(anonymous functi
on) [as next] (C:\Users\Administrator\AppData\Roaming\npm\node_modules\appium\no
de_modules\_babel-runtime@5.8.24@babel-runtime\regenerator\runtime.js:100:21)
2018-08-16 19:29:45:797 - [W3C]     at Object.runtime.async (C:\Users\Administra
tor\AppData\Roaming\npm\node_modules\appium\node_modules\_babel-runtime@5.8.24@b
abel-runtime\regenerator\runtime.js:209:12)
2018-08-16 19:29:45:798 - [W3C]     at AndroidUiautomator2Driver.callee$0$0 [as
timeouts] (C:\Users\Administrator\AppData\Roaming\npm\node_modules\appium\node_m
odules\_appium-base-driver@3.5.1@appium-base-driver\build\lib\basedriver\command
s\timeout.js:40:30)
2018-08-16 19:29:45:798 - [W3C]     at C:\Users\Administrator\AppData\Roaming\np
m\node_modules\appium\node_modules\_appium-base-driver@3.5.1@appium-base-driver\
lib\basedriver\driver.js:296:26
2018-08-16 19:29:45:799 - [W3C]     at tryCatcher (C:\Users\Administrator\AppDat
a\Roaming\npm\node_modules\appium\node_modules\_bluebird@2.11.0@bluebird\js\main
\util.js:26:23)
2018-08-16 19:29:45:800 - [W3C]     at Promise._settlePromiseFromHandler (C:\Use
rs\Administrator\AppData\Roaming\npm\node_modules\appium\node_modules\_bluebird@
2.11.0@bluebird\js\main\promise.js:510:31)
2018-08-16 19:29:45:800 - [W3C]     at Promise._settlePromiseAt (C:\Users\Admini
strator\AppData\Roaming\npm\node_modules\appium\node_modules\_bluebird@2.11.0@bl
uebird\js\main\promise.js:584:18)
2018-08-16 19:29:45:801 - [W3C]     at Promise._settlePromiseAtPostResolution (C
:\Users\Administrator\AppData\Roaming\npm\node_modules\appium\node_modules\_blue
bird@2.11.0@bluebird\js\main\promise.js:248:10)
2018-08-16 19:29:45:802 - [W3C]     at Async._drainQueue (C:\Users\Administrator
\AppData\Roaming\npm\node_modules\appium\node_modules\_bluebird@2.11.0@bluebird\
js\main\async.js:128:12)
2018-08-16 19:29:45:803 - [W3C]     at Async._drainQueues (C:\Users\Administrato
r\AppData\Roaming\npm\node_modules\appium\node_modules\_bluebird@2.11.0@bluebird
\js\main\async.js:133:10)
2018-08-16 19:29:45:803 - [W3C]     at Immediate.Async.drainQueues [as _onImmedi
ate] (C:\Users\Administrator\AppData\Roaming\npm\node_modules\appium\node_module
s\_bluebird@2.11.0@bluebird\js\main\async.js:15:14)
2018-08-16 19:29:45:804 - [W3C]     at runCallback (timers.js:810:20)
2018-08-16 19:29:45:805 - [W3C]     at tryOnImmediate (timers.js:768:5)
2018-08-16 19:29:45:805 - [W3C]     at processImmediate [as _immediateCallback]
(timers.js:745:5)
2018-08-16 19:29:45:822 - [HTTP] <-- POST /wd/hub/session/d7fb7b03-6b0c-4f74-a5a
d-a4833ff6f00c/timeouts 500 57 ms - 1580
2018-08-16 19:29:45:827 - [HTTP]

the appium server is 1.8.2-beta
C:\Users\Administrator>appium -v
1.8.2-beta

**Comment by mykola-mokhnach** [comment]
Please uninstall beta completely and try again. Some fixes have been merged there recently.

**Comment by AlexDingSZ** [comment]
what is the total npm command to install the latest  appium code ?

**Comment by robin-xl** [comment]
Try this, `npm uninstall -g appium && npm install -g appium@beta`

**Comment by KazuCocoa** [comment]
When I investigated https://github.com/appium/ruby_lib_core/issues/128 , I noticed the version of `appium-base-driver` we could get via `appium@beta` was `"^2.20.2"`. Current master is `"^3.0.0"`. So, we should release a new beta which tagged `"^3.0.0"` to get `3.5.1` as beta..

```
  "dependencies": {
    "appium-android-driver": "3.x",
    "appium-base-driver": "^3.0.0",
    "appium-espresso-driver": "^1.0.0-beta.3",
    "appium-fake-driver": "^0.x",
    "appium-ios-driver": "2.x",
    "appium-mac-driver": "1.x",
    "appium-selendroid-driver": "1.x",
    "appium-support": "2.x",
    "appium-tizen-driver": "^1.0.0-beta",
    "appium-uiautomator2-driver": "1.x",
    "appium-windows-driver": "1.x",
    "appium-xcuitest-driver": "2.x",
    "appium-youiengine-driver": "1.x",
    "argparse": "^1.0.10",
    "async-lock": "^1.0.0",
    "asyncbox": "2.x",
    "babel-runtime": "=5.8.24",
    "bluebird": "3.x",
    "continuation-local-storage": "3.x",
    "dateformat": "^3.0.3",
    "find-root": "^1.1.0",
    "lodash": "=4.17.9",
    "longjohn": "^0.2.12",
    "npmlog": "4.x",
    "request": "^2.81.0",
    "request-promise": "4.x",
    "semver": "^5.5.0",
    "source-map-support": "0.x",
    "teen_process": "1.x",
    "winston": "2.x"
  },
```

**Comment by KazuCocoa** [comment]
@imurchie 
Do you have a chance to release new beta which is available `"appium-base-driver": "^3.0.0"` before 1.9.0?

The reason is above my comment. Users can get `"appium-base-driver": "^2.20.2"` as current beta. But some issues remain in the version like `timeouts` commands. They should work well with `^3.0.0`.

**Comment by imurchie** [comment]
Yes, we probably should.

**Comment by imurchie** [comment]
1.9.0-beta.1 has been released. Available as `appium@beta` (e.g., `npm uninstall -g appium && npm install -g appium@beta`)

**Comment by AlexDingSZ** [comment]
after installed appium@beta， run code “driver.implicitly_wait(10)”  sucessfully!
thank you all！

**Comment by KazuCocoa** [comment]
👍
