### ISSUE TITLE
Unable to long press on any element

### ISSUE THREAD

**Issue by rpatel29** [appium/appium#11196]
## The problem

Error (An unknown server-side error occurred while processing the command) is thrown when attempting to use long_press method

## Environment

* Appium version (or git revision) that exhibits the issue: v.1.8.1
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium:  macOS High Sierra 10.13.5 (17F77)
* Node.js version (unless using Appium.app|exe): v6.11.3
* Mobile platform/version under test: iPhone X 11.4
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Appium.app|exe

## Code To Reproduce Issue
```
    lp_action = TouchAction(self.driver)
    lp_action.long_press(selenium_element)
    lp_action.perform()
```

## Link to Appium logs

```
2018-08-17 00:04:53:486 - [HTTP] {"using":"id","value":"Email Body Field","sessionId":"daa76b2c-d77e-4a40-a1b4-d04b4f99a577"}
2018-08-17 00:04:53:487 - [debug] [W3C] Calling AppiumDriver.findElement() with args: ["id","Email Body Field","daa76b2c-d77e-4a40-a1b4-d04b4f99a577"]
2018-08-17 00:04:53:487 - [debug] [XCUITest] Executing command 'findElement'
2018-08-17 00:04:53:490 - [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
2018-08-17 00:04:53:491 - [debug] [BaseDriver] Waiting up to 0 ms for condition
2018-08-17 00:04:53:492 - [debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/4A2E4475-A1F5-4183-B662-5F8EB062D974/element] with body: {"using":"id","value":"Email Body Field"}
2018-08-17 00:04:53:692 - [debug] [JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"8F000000-0000-0000-EBCC-000000000000"},"sessionId":"4A2E4475-A1F5-4183-B662-5F8EB062D974","status":0}
2018-08-17 00:04:53:693 - [debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"8F000000-0000-0000-EBCC-000000000000"}
2018-08-17 00:04:53:694 - [HTTP] <-- POST /wd/hub/session/daa76b2c-d77e-4a40-a1b4-d04b4f99a577/element 200 208 ms - 122
2018-08-17 00:04:53:695 - [HTTP] 
2018-08-17 00:04:53:696 - [HTTP] --> POST /wd/hub/session/daa76b2c-d77e-4a40-a1b4-d04b4f99a577/touch/perform
2018-08-17 00:04:53:697 - [HTTP] {"actions":[{"action":"longPress","options":{"element":"8F000000-0000-0000-EBCC-000000000000","x":null,"y":null,"duration":1000}}],"sessionId":"daa76b2c-d77e-4a40-a1b4-d04b4f99a577"}
2018-08-17 00:04:53:698 - [debug] [W3C] Calling AppiumDriver.performTouch() with args: [[{"action":"longPress","options":{"element":"8F000000-0000-0000-EBCC-000000000000","x":null,"y":null,"duration":1000}}],"daa76b2c-d77e-4a40-a1b4-d04b4f99a577"]
2018-08-17 00:04:53:699 - [debug] [XCUITest] Executing command 'performTouch'
2018-08-17 00:04:53:700 - [debug] [XCUITest] Received the following touch action: longPress(options={"element":"8F000000-0000-0000-EBCC-000000000000","x":null,"y":null,"duration":1000})
2018-08-17 00:04:53:700 - [debug] [JSONWP Proxy] Proxying [POST /wda/touch/perform] to [POST http://localhost:8100/session/4A2E4475-A1F5-4183-B662-5F8EB062D974/wda/touch/perform] with body: {"actions":[{"action":"longPress","options":{"element":"8F000000-0000-0000-EBCC-000000000000","x":null,"y":null,"duration":1000}}]}
2018-08-17 00:04:53:767 - [debug] [JSONWP Proxy] Got response with status 200: {"value":"-[NSNull floatValue]: unrecognized selector sent to instance 0x108e72fc0\n\n(\n\t0   CoreFoundation                      0x0000000108baa1e6 __exceptionPreprocess + 294\n\t1   libobjc.A.dylib                     0x000000010823f031 objc_exception_throw + 48\n\t2   CoreFoundation                      0x0000000108c2b784 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132\n\t3   CoreFoundation                      0x0000000108b2c898 ___forwarding___ + 1432\n\t4   CoreFoundation                      0x0000000108b2c278 _CF_forwarding_prep_0 + 120\n\t5   WebDriverAgentLib                   0x0000000126b25565 -[FBAppiumGestureItem coordinatesWithOptions:error:] + 1125\n\t6   WebDriverAgentLib                   0x0000000126b24bea -[FBAppiumGestureItem initWithActionItem:application:atPosition:offset:error:] + 490\n\t7   WebDriverAgentLib                   0x0000000126b27e68 -[FBAppiumActionsSynthesizer eventPathsWithAction:error:] + 1432\n\t8   WebDriverAgentLib                   0x0000000126b28b20 -[FBA...
2018-08-17 00:04:53:780 - [MJSONWP] Encountered internal error running command: Error: An unknown server-side error occurred while processing the command.
2018-08-17 00:04:53:780 - [MJSONWP]     at JWProxy.command$ (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:176:15)
2018-08-17 00:04:53:781 - [MJSONWP]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
2018-08-17 00:04:53:781 - [MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
2018-08-17 00:04:53:781 - [MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
2018-08-17 00:04:53:781 - [MJSONWP]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
2018-08-17 00:04:53:782 - [HTTP] <-- POST /wd/hub/session/daa76b2c-d77e-4a40-a1b4-d04b4f99a577/touch/perform 500 86 ms - 238
2018-08-17 00:04:53:783 - [HTTP] 
2018-08-17 00:04:53:785 - [HTTP] --> GET /wd/hub/session/daa76b2c-d77e-4a40-a1b4-d04b4f99a577/screenshot
```

**Comment by mykola-mokhnach** [comment]
This is because of the [bug](https://github.com/appium/python-client/pull/214) in the python client. Make sure it is up to date.
