### ISSUE TITLE
WebDriverException: An unknown server-side error occurred while processing the command. Original error: Command 'java' not found

### ISSUE THREAD

**Issue by unrealgear** [appium/appium#11202]
## The problem

Android Driver cannot be instantiated as it cannot find my Java. My Java version is: 1.8.0_171-b11.

Error message:

```
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Command 'java' not found. Is it installed?

Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'nikita-ryabchenko', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-32-generic', java.version: '1.8.0_141'
Driver info: driver.version: AndroidDriver
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Last Appium version that did not exhibit the issue (if applicable): didn't try
* Desktop OS/version used to run Appium:  Ubuntu 16.04
* Node.js version (unless using Appium.app|exe): 8.11.3
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: CLI
* Java Client version: 6.1.0

## Details

I am using the sample code from https://github.com/appium/appium/blob/master/sample-code/java/src/AndroidCreateWebSessionTest.java. I have installed Android Studie, set up my virtual device and it launches without problems. I have installed Appium via npm. I write tests on Java, so it is definitely installed on my machine. 

With your default code of starting the service, there is an error which states that I have no Appium node installed. I have found a solution on the internet. Here it is how my code looks now:

```
@BeforeSuite
void globalSetup() throws IOException {

service = AppiumDriverLocalService.buildDefaultService()

service = new AppiumServiceBuilder()
                .withAppiumJS(new File("/home/ryabchenko/.nvm/versions/node/v8.11.3/lib/node_modules/appium/build/lib/main.js"))
                .usingAnyFreePort()
                .build()

service.start()
}
```

Now everything is fine with node Appium, but the application cannot see my installed Java when instantiating new AndroidDriver (last line of code below):

```
@BeforeClass
public void setUp() {
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("deviceName", "test");
        capabilities.setCapability("browserName", "Chrome");
        driver = new AndroidDriver<WebElement>(getServiceUrl(), capabilities);
}
```

I get this error message:

`Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Command 'java' not found. Is it installed?`

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/java-client/blob/master/docs/environment.md

Please attach full server log and the stack trace.

**Comment by unrealgear** [comment]
I have found out that this exception is thrown if I haven't started Appium before test execution. Which is somehow strange as on Mac there is no need to start Appium manually. 

Here is the log:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[TestNG] Running:
  /home/ryabchenko/.IntelliJIdea2017.2/system/temp-testng-customsuite.xml
[Appium] Appium support for versions of node < 8 has been deprecated and will be removed in a future version. Please upgrade!
[Appium] Welcome to Appium v1.8.1 (REV 93990ab7da37007c8d9db16415cfb939aa5dd201)
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.8.1","revision":"93990ab7da37007c8d9db16415cfb939aa5dd201"}}
[HTTP] <-- GET /wd/hub/status 200 17 ms - 121
[HTTP] 
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"browserName":"Chrome","platformName":"Android","deviceName":"Nexus 6P API 27"},"capabilities":{"alwaysMatch":{"browserName":"Chrome","appium:deviceName":"Nexus 6P API 27","platformName":"android"},"firstMatch":[{}]}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"browserName":"Chrome","platformName":"Android","deviceName":"Nexus 6P API 27"},null,{"alwaysMatch":{"browserName":"Chrome","appium:deviceName":"Nexus 6P API 27","platformName":"android"},"firstMatch":[{}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1534776109910 (17:41:49 GMT+0300 (EEST))
[Appium] Creating new AndroidDriver (v2.7.0) session
[Appium] Capabilities:
[Appium]   browserName: Chrome
[Appium]   platformName: android
[Appium]   deviceName: Nexus 6P API 27
[debug] [BaseDriver] W3C capabilities {"alwaysMatch":{"browserNam... and MJSONWP desired capabilities [object Object] were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"browserNam...
[BaseDriver] Session created with session id: 4ba3cc82-c987-4494-98ee-7e408b71b6d1
[debug] [AndroidDriver] Getting Java version
[debug] [AndroidDriver] Shutting down Android driver
[debug] [AndroidDriver] Called deleteSession but bootstrap wasn't active
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1534776109974 (17:41:49 GMT+0300 (EEST))
[W3C] Encountered internal error running command: Error: Command 'java' not found. Is it installed?
[W3C]     at ChildProcess.<anonymous> (/home/ryabchenko/.nvm/versions/node/v8.11.3/lib/node_modules/appium/node_modules/teen_process/lib/exec.js:39:14)
[W3C]     at emitOne (events.js:96:13)
[W3C]     at ChildProcess.emit (events.js:188:7)
[W3C]     at Process.ChildProcess._handle.onexit (internal/child_process.js:217:12)
[W3C]     at onErrorNT (internal/child_process.js:376:16)
[W3C]     at _combinedTickCallback (internal/process/next_tick.js:80:11)
[W3C]     at process._tickCallback (internal/process/next_tick.js:104:9)
[HTTP] <-- POST /wd/hub/session 500 96 ms - 1346
[HTTP] 

org.openqa.selenium.WebDriverException: It is impossible to create a new session because 'createSession' which takes HttpClient, InputStream and long was not found or it is not accessible
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'nikita-ryabchenko', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-32-generic', java.version: '1.8.0_141'
Driver info: driver.version: AndroidDriver
at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:195)
  at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:209)
  at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:231)
  at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
  at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
  at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
  at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
  at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:207)
  at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
  at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)
  at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:84)
  at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:94)
  at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:93)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
  at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
  at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
  at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)
  at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:194)
  at AndroidCreateWebSessionTest.setUp(AndroidCreateWebSessionTest.groovy:18)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
  at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
  at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
  at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:169)
  at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
  at org.testng.TestRunner.privateRun(TestRunner.java:756)
  at org.testng.TestRunner.run(TestRunner.java:610)
  at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
  at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
  at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  at org.testng.SuiteRunner.run(SuiteRunner.java:289)
  at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
  at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
  at org.testng.TestNG.runSuites(TestNG.java:1133)
  at org.testng.TestNG.run(TestNG.java:1104)
  at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
  at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
Caused by: java.lang.reflect.InvocationTargetException
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:185)
  ... 46 more
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Command 'java' not found. Is it installed?
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'nikita-ryabchenko', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-32-generic', java.version: '1.8.0_141'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Command 'java' not found. Is it installed?
    at getResponseForW3CError (/home/ryabchenko/.nvm/versions/node/v8.11.3/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:806:13)
    at asyncHandler$ (/home/ryabchenko/.nvm/versions/node/v8.11.3/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:361:37)
    at tryCatch (/home/ryabchenko/.nvm/versions/node/v8.11.3/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/home/ryabchenko/.nvm/versions/node/v8.11.3/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/home/ryabchenko/.nvm/versions/node/v8.11.3/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/home/ryabchenko/.nvm/versions/node/v8.11.3/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
  at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
  at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)
  at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
  at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
  at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
  at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
  at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
  at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
  at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
  at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
  at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
  at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
  ... 51 more

```
Plus to this, when the code executes (without Appium server), it starts its own Appium server on the default port which remains working even after throwing the exception / finishing the execution. Because of the default port is in use, the Appium server cannot be started. So I have to either find the process which listens to the default port and stop it or start Appium server on another port.

**Comment by mykola-mokhnach** [comment]
I don't observe any server issues here. It is a problem with process environment setup.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue. Try to raise a question on Appium forum is the problem still persists.
