### ISSUE TITLE
`remoteAdbHost` not being set for creating Webview context when using Chromdriver.

### ISSUE THREAD

**Issue by sumeet-singh04** [appium/appium#11206]
## Issue
`remoteAdbPort` not being set for creating Webview context when using Chromdriver.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Desktop OS/version used to run Appium: Ubuntu(16.04)
* Node.js version (unless using Appium.app|exe):8.x
* Mobile platform/version under test: Android 6.0
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: 1.8.1

## Details

Setting `remoteAdbHost` works when testing Native apps with UiAutomator2 driver, but as soon as test context is changed to WebView for Hybrid app, the Chrome driver fails 

```
Encountered internal error running command: Error: Failed to start Chromedriver session: An unknown server-side error occurred while processing the command. Original error: unknown error: Failed to run adb command with networking error: net::ERR_CONNECTION_REFUSED. Is the adb server running? Extra response: <>.
2018-08-17 19:31:16:813 - error: [MJSONWP]   (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.9.93-linuxkit-aufs x86_64)
2018-08-17 19:31:16:814 - error: [MJSONWP]     at Object.wrappedLogger.errorAndThrow (/home/docker-ima/.config/yarn/global/node_modules/appium-support/lib/logging.js:78:13)
2018-08-17 19:31:16:814 - error: [MJSONWP]     at Chromedriver.callee$2$0$ (/home/docker-ima/.config/yarn/global/node_modules/appium-chromedriver/lib/chromedriver.js:448:13)
2018-08-17 19:31:16:815 - error: [MJSONWP]     at tryCatch (/home/docker-ima/.config/yarn/global/node_modules/babel-runtime/regenerator/runtime.js:67:40)
2018-08-17 19:31:16:815 - error: [MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/home/docker-ima/.config/yarn/global/node_modules/babel-runtime/regenerator/runtime.js:315:22)
2018-08-17 19:31:16:816 - error: [MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/home/docker-ima/.config/yarn/global/node_modules/babel-runtime/regenerator/runtime.js:100:21)
2018-08-17 19:31:16:816 - error: [MJSONWP]     at GeneratorFunctionPrototype.invoke (/home/docker-ima/.config/yarn/global/node_modules/babel-runtime/regenerator/runtime.js:136:37)
```
In appium-chromedriver it seems we are reading the adb-port, but not setting the remoteAdbHost.
appium-chromedriver/lib/chromedriver.js
```
if (this.adb && this.adb.adbPort) {
      args = args.concat([`--adb-port=${this.adb.adbPort}`]);
    }
```

I have my adb and emulator running on my local, and appium running inside a docker container. 
I am setting remoteHostAdb to `host.docker.internal` which works perfectly for Native Android apps, but as soon as I switch the context to WebView, Appium loads the chromedriver and everything starts failing as Appium-Chromedriver tries to connect to adb without the `-H host.docker.internal` arg, and this get a ERR_CONNECTION_REFUSED.

**Comment by sumeet-singh04** [comment]
Closing this issues, ad it seems like ChromeDriver doesn't has the capability to connect with remote Adb Server socket. FYI I accomplished this by creating a port forwarding between the local port 5037 and routing traffic to a remote tcp connection using the `net` nodejs package.
