### ISSUE TITLE
Original error: 404 - "unknown command: session/f9dc30098067a7aa5fc5c34eda847e42/window/handles

### ISSUE THREAD

**Issue by WindInMay524** [appium/appium#11219]
## The problem
I want to get window handles,when I used the function "window_handles"
 File "Test002_ApproveSaleManagerRegister.py", line 26, in testApproveRegisterApplication
    print(self.appium_driver.window_handles)
  File "D:\software\python\3.6.6\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 723, in window_handles
    return self.execute(Command.W3C_GET_WINDOW_HANDLES)['value']
  File "D:\software\python\3.6.6\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "D:\software\python\3.6.6\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "D:\software\python\3.6.6\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "D:\software\python\3.6.6\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: 404 - "unknown command: session/f5bfe985c8e4cc6fec21888848e229e3/window/handles"
## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1   
* Last Appium version that did not exhibit the issue (if applicable): python3.6.4 didn't have this problem,now is python 3.6.6
* Desktop OS/version used to run Appium: Appium_Python_Client-0.28-py3.6.egg-info 0.28
* Mobile platform/version under test:android 7.1
* Real device or emulator/simulator:Real device

## Link to Appium logs
[W3C] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/ab3e4a4e-377f-4afd-a095-000e9e84dbbb/window/handles] to [GET http://127.0.0.1:8000/wd/hub/session/f5bfe985c8e4cc6fec21888848e229e3/window/handles] with body: {"sessionId":"ab3e4a4e-377f-4afd-a095-000e9e84dbbb"}
[JSONWP Proxy] Got unexpected response: unknown command: session/f5bfe985c8e4cc6fec21888848e229e3/window/handles
[W3C] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: 404 - "unknown command: session/f5bfe985c8e4cc6fec21888848e229e3/window/handles"
[W3C]     at doJwpProxy$ (D:\software\nodejs\node_global\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:456:13)
[W3C]     at tryCatch (D:\software\nodejs\node_global\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (D:\software\nodejs\node_global\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (D:\software\nodejs\node_global\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[W3C]     at GeneratorFunctionPrototype.invoke (D:\software\nodejs\node_global\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[HTTP] <-- GET /wd/hub/session/ab3e4a4e-377f-4afd-a095-000e9e84dbbb/window/handles 500 45 ms - 1557

## Code To Reproduce Issue [ Good To Have ]
    def testRefuseRegisterApplication(self):
        self.common.changeAccount(0)
        self.common.enterYiShiAccount()
        self.sale_manager.enterSaleManager()
        time.sleep(4)
        self.sale_manager.switchToWebview()
        print(self.appium_driver.window_handles)

**Comment by WindInMay524** [comment]
Appium_Python_Client-0.26 is ok

**Comment by mykola-mokhnach** [comment]
How does the server log where it works look like?

**Comment by mykola-mokhnach** [comment]
I think I know what the problem might be

**Comment by WindInMay524** [comment]
[HTTP] --> GET /wd/hub/session/05273e0f-e6d4-42e6-b659-bf7b2d7820de/window_handles
[HTTP] {"sessionId":"05273e0f-e6d4-42e6-b659-bf7b2d7820de"}
[W3C] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/05273e0f-e6d4-42e6-b659-bf7b2d7820de/window_handles] to [GET http://127.0.0.1:8000/wd/hub/session/3c42bf6dff6907b74ae4c295a5c616d0/window_handles] with body: {"sessionId":"05273e0f-e6d4-42e6-b659-bf7b2d7820de"}
[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"3c42bf6dff6907b74ae4c295a5c616d0\",\"status\":0,\"value\":[\"CDwindow-39043cbd-307b-4f9d-8e8c-dced9553517a\",\"CDwindow-ecd7c51f-c829-4c32-a0d9-af59d7ef39ce\",\"CDwindow-da3f808b-3407-4807-b4a6-3678130ab8e2\"]}"
[JSONWP Proxy] Replacing sessionId 3c42bf6dff6907b74ae4c295a5c616d0 with 05273e0f-e6d4-42e6-b659-bf7b2d7820de
[HTTP] <-- GET /wd/hub/session/05273e0f-e6d4-42e6-b659-bf7b2d7820de/window_handles 200 52 ms - 217
[HTTP]
[HTTP] --> DELETE /wd/hub/session/05273e0f-e6d4-42e6-b659-bf7b2d7820de
[HTTP] {"sessionId":"05273e0f-e6d4-42e6-b659-bf7b2d7820de"}
[debug] [W3C] Calling AppiumDriver.deleteSession() with args: ["05273e0f-e6d4-42e6-b659-bf7b2d7820de"]
[debug] [BaseDriver] Event 'quitSessionRequested' logged at 1534903634601 (10:07:14 GMT+0800 (GMT+08:00))
[Appium] Removing session 05273e0f-e6d4-42e6-b659-bf7b2d7820de from our master session list
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [AndroidDriver] Stopping chromedriver for context WEBVIEW_com.tencent.mm:tools
[debug] [Chromedriver] Changed state to 'stopping'
[debug] [JSONWP Proxy] Proxying [DELETE /] to [DELETE http://127.0.0.1:8000/wd/hub/session/3c42bf6dff6907b74ae4c295a5c616d0] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"3c42bf6dff6907b74ae4c295a5c616d0\",\"status\":0,\"value\":null}"
[debug] [Chromedriver] Changed state to 'stopped'
[debug] [UiAutomator2] Deleting UiAutomator2 server session
[debug] [JSONWP Proxy] Proxying [DELETE /] to [DELETE http://localhost:8200/wd/hub/session/6c90bb7a-8960-487f-82c7-ee503c614e2d] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"6c90bb7a-8960-487f-82c7-ee503c614e2d\",\"status\":0,\"value\":\"Session deleted\"}"
[debug] [ADB] Running 'D:\software\sdk\platform-tools\adb.exe -P 5037 -s 4b62e63e shell am force-stop com.tencent.mm'
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Removing forwarded port socket connection: 8200
[debug] [ADB] Running 'D:\software\sdk\platform-tools\adb.exe -P 5037 -s 4b62e63e forward --remove tcp\:8200'
[debug] [UiAutomator2] [UIAutomator2] io.appium.uiautomator2.server.test.AppiumUiAutomator2Server:.
[debug] [UiAutomator2] [UIAutomator2] Time: 44.082
[debug] [UiAutomator2] [UIAutomator2] OK (1 test)
[debug] [BaseDriver] Event 'quitSessionFinished' logged at 1534903635481 (10:07:15 GMT+0800 (GMT+08:00))
[debug] [MJSONWP] Received response: null
[debug] [MJSONWP] But deleting session, so not returning
[debug] [MJSONWP] Responding to client with driver.deleteSession() result: null
[HTTP] <-- DELETE /wd/hub/session/05273e0f-e6d4-42e6-b659-bf7b2d7820de 200 913 ms - 76
