### ISSUE TITLE
Keyboard is not found while trying to invoke soft keyboard from an Appium IOS WebApp test

### ISSUE THREAD

**Issue by sasanapu** [appium/appium#11230]
## The problem

My use case is to click ENTER/ RETURN after entering text in a text field, and i have issues with it. 
Ours is a web application and i'm running the test on IOS 11.x. 

My code actually uses SendKeys and clicks ENTER, but it clears text in IOS.

I'm trying to invoke soft keyboard for clicking ENTER with the code:
```
appiumDriver.getKeyboard().pressKey(Keys.RETURN);
```

And the error,
```
2018-08-21 15:32:36:314 - info: [debug] [JSONWP Proxy] Got response with status 200: {"value":"Error Domain=com.facebook.WebDriverAgent Code=1 \"Keyboard is not present\" UserInfo={NSLocalizedDescription=Keyboard is not present}","sessionId":"3E2BF853-9AB4-41BE-9052-B92455BCB003","status":13}
2018-08-21 15:32:36:351 - error: [MJSONWP] Encountered internal error running command: Error: An unknown server-side error occurred while processing the command.
    at JWProxy.command$ (/usr/local/avm/versions/1.7.2/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:176:15)
    at tryCatch (/usr/local/avm/versions/1.7.2/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/avm/versions/1.7.2/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/avm/versions/1.7.2/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/avm/versions/1.7.2/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
```

Desired capabilities used,
```
DesiredCapabilities capabilities = new DesiredCapabilities();
        
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, config.getDeviceName());
        capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, config.getPlatformName());
        capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, config.getBrowser());
        capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, config.getNewCommandTimeoutMobile());
        capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.IOS_XCUI_TEST);
        capabilities.setCapability(IOSMobileCapabilityType.CONNECT_HARDWARE_KEYBOARD, "False");
        capabilities.setCapability(IOSMobileCapabilityType.SEND_KEY_STRATEGY, "oneByOne");
        
        Logger.log("IOS capabilities %s", capabilities.asMap());
        AppiumDriver<MobileElement> driver = new AppiumDriver<MobileElement> (new URL(config.getAppiumEndpoint()), capabilities);
```

I have tried other workarounds as well,
- Setting CONNECT_HARDWARE_KEYBOARD to False for invoking the soft keypad
- Using Actions to click enter
- Using Touchaction to tap on element
- Using Robot for entering
- Appending the text with "\\n"

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): N/A 
* Desktop OS/version used to run Appium: n/a
* Node.js version (unless using Appium.app|exe): 5.0.4
* Mobile platform/version under test:  IOS 11.x
* Real device or emulator/simulator: both
* Appium CLI or Appium.app|exe: Appium CLI

**Comment by mykola-mokhnach** [comment]
Apiium 1.7.2 is out of date. Please upgrade it to the most recent version. 
Regarding the keyboard presence -we cannot control it due to known Simulator issue. You may try to switch this option manually on the Simulator and check if it works for you.

**Comment by sasanapu** [comment]
thanks for the response. I gave a type while defining CONNECT_HARDWARE_KEYBOARD and that's the reason it was not working. 
I appreciate your recommendation, but the service that we are using to run our tests on devices doesn't support 1.8.x and hence we are bound to use 1.7.2

**Comment by anilskv12** [comment]
Hi sasanapu. 
Were you able to resolve keyboard issue?
