### ISSUE TITLE
W3C NoSuchElementError when waiting for an element to appear

### ISSUE THREAD

**Issue by vjmaiky** [appium/appium#11245]
## The problem
W3 logs are a pain when waiting for an element to appear

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.0  beta 1
* Last Appium version that did not exhibit the issue (if applicable): 1.8.2 beta
* Desktop OS/version used to run Appium: mac os
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS 11.4
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:

## Details
When doing a wait for an element to appear a bunch of W3C logs appear until desired element is on screen. How to stop that logging?

## Link to Appium logs
[W3C] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
[W3C]     at AndroidUiautomator2Driver.callee$0$0$ (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/lib/commands/find.js:75:11)
[W3C]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[W3C]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[W3C]     at <anonymous>
[W3C] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
[W3C]     at AndroidUiautomator2Driver.callee$0$0$ (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/lib/commands/find.js:75:11)
[W3C]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[W3C]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[W3C]     at <anonymous>

**Comment by zuzeac** [comment]
@vjmaiky  is the issue fixed for you if you're using 1.9.1 beta?
I also tried to update the uiautomator2 to the latest version, Still have the problem.

**Comment by vjmaiky** [comment]
i saw some in beta 1; we need to install 1.9.0 (new one) and to see

**Comment by vjmaiky** [comment]
yep; tried now with 1.9.0 and still no difference

[W3C] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
[W3C]     at XCUITestDriver.callee$0$0$ (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:130:13)
[W3C]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[W3C]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[W3C]     at <anonymous>

**Comment by mykola-mokhnach** [comment]
I have removed an extra line in W3C error converter, however there is still another one with exactly the same text in https://github.com/appium/appium-base-driver/blob/5e9df93eebafcbc9995109b3d92b5e319ac91291/lib/protocol/protocol.js#L369

@imurchie do you think it makes sense to remove that one as well?

**Comment by waynema** [comment]
@mykola-mokhnach ,  I see the same issue in release 1.10.0 showing NoSuchElementError when waiting for an element to appear using exists function.  It used to be a warning, now it is an Error and stops the test.

[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":7,"value":"No element found"}
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [MJSONWP] Matched JSONWP error code 7 to NoSuchElementError
[debug] [W3C (06b43e89)] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
[debug] [W3C (06b43e89)]     at AndroidDriver.helpers.findElOrEls (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/lib/commands/find.js:75:11)
