### ISSUE TITLE
Appium failed to perform tap on screen due to, Coordinates [x, y] is outside of element rect: [,][,]"}

### ISSUE THREAD

**Issue by QA2Dev** [appium/appium#11244]
## The problem

io.appium.uiautomator2.common.exceptions.InvalidCoordinatesException: Coordinate [x=1795.0, y=662.0] is outside of element rect: [0,0][1794,1080]

Resolution of Screen is : 1920x1080
Resolution of Screen adopted by Appium is : Display bounds: [0,0][1794,1080]

## Environment

Device: HTC Desire (Real device - Smartphone)
Android OS: 6.0
Appium Version: 1.8.0
MacOS : 10.13.6
Xcode: 9.2
JavaClient: 5.0.4

## Details

Appium failed to perform tap on screen screen on HTC desire phone (Resolution : 1920x1080), stating the error :  Coordinate [x=1794.0, y=662.0] is outside of element rect: [0,0][1794,1080]
Resolution of Screen is : 1920x1080
Resolution of Screen adopted by Appium is : Display bounds: [0,0][1794,1080]
Action performed at Coordinates : [1795,662]

## Link to Appium logs

org.openqa.selenium.interactions.InvalidCoordinatesException: io.appium.uiautomator2.common.exceptions.InvalidCoordinatesException: Coordinate [x=1795.0, y=662.0] is outside of element rect: [0,0][1794,1080]
	at io.appium.uiautomator2.utils.PositionHelper.getAbsolutePosition(PositionHelper.java:71)
	at io.appium.uiautomator2.utils.PositionHelper.getDeviceAbsPos(PositionHelper.java:83)
	at io.appium.uiautomator2.handler.Drag.drag(Drag.java:42)
	at io.appium.uiautomator2.handler.Drag.safeHandle(Drag.java:34)
	at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:65)
	at io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:247)
	at io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:238)
	at io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:44)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:514)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:818)

**WorkAround**

Is it possible to get the  element rect: [0,0][1794,1080] displayed by appium in log, through script  in code?.

**Comment by mykola-mokhnach** [comment]
Please attach the full server log and `adb logcat` output

**Comment by QA2Dev** [comment]
@mykola-mokhnach please find below Appium log

https://gist.github.com/QA2Dev/1d6a14ba624e7ab78332fdba5e62ae6b

**Comment by mykola-mokhnach** [comment]
Linking https://github.com/appium/appium/issues/8724

**Comment by mykola-mokhnach** [comment]
Try the patch from https://github.com/appium/appium-uiautomator2-server/pull/184 locally and check if it helps to resolve the issue. I'll merge it only after you confirm it works for you.

**Comment by QA2Dev** [comment]
@mykola-mokhnach Is it possible to get the element rect:[1794,1080] displayed by appium, through script in code?., I'm not able to get display bounds [1794,1080] considered by Appium in the script

**Comment by mykola-mokhnach** [comment]
I assume it's not. This is UiAutomator limitation

**Comment by mykola-mokhnach** [comment]
Server deployment tutorial: https://github.com/appium/python-client/issues/244#issuecomment-414499267

**Comment by mykola-mokhnach** [comment]
There is a step-by-step description in the last link

**Comment by QA2Dev** [comment]
@mykola-mokhnach, I followed the steps you shared with me but I'm not able to build the project due to following issue, "A problem occurred evaluating root project 'appium-uiautomator2-server'.
> Cannot add task 'clean' as a task with that name already exists.

**Comment by QA2Dev** [comment]
@mykola-mokhnach I have got the apk builds of UI Automator 2 from @KazuCocoa and copied those to the folders as per the instruction and ran the tests, but i'm still facing the same issue i.e 
io.appium.uiautomator2.common.exceptions.InvalidCoordinatesException: 

kindly find below the appium log
https://gist.github.com/QA2Dev/7058ba0e8fbcd0a8977df73be0760c0a

**Comment by QA2Dev** [comment]
@mykola-mokhnach @KazuCocoa We are testing using appium-java client i.e io.appium:java-client:5.0.4

**Comment by QA2Dev** [comment]
@mykola-mokhnach Kindly let me know, how will I come to know does the apks such as appium-**uiautomator2-server-debug-androidTest**, **appium-uiautomator2-server-v1.15.0** kept in the path **/usr/local/lib/node_modules/appium-uiautomator2-server/apks/** will be considered by Appium while running tests.

**Comment by KazuCocoa** [comment]
I'm not familiar with Java Client, but you should probably use the latest one to work well with W3C protocol.

You need to figure out correct path in your environment.
For example, I use nodebrew and the path is `/Users/kazu/.nodebrew/current/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks` when I install node librari with `-g` option.
It is node topic. I guess you can find the path from `which npm`.

**Comment by QA2Dev** [comment]
@mykola-mokhnach @KazuCocoa I have kept the APks in the correct path where the Appium is installed in my system (/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/) but still I'm facing the InvalidCoordinatesException issue.

**Comment by QA2Dev** [comment]
@mykola-mokhnach Even if we keep the latest build (appium-uiautomator2-server-v1.15.0) in the path, appium is picking up the old build appium-uiautomator2-server-v1.12.0, I deleted the old one and renamed the new build with version 1.12.0.

I'm not getting the exception now seems like patch is proper but gestures are not working at that coordinates.

**Comment by mykola-mokhnach** [comment]
exactly

**Comment by mikesalvia** [comment]
Yeah, this looks to be an issue within the UIAutomator framework, I am currently trying to exit fullscreen video using a fullscreen button which is under the navigation bar and it refuses to work properly. I am going to use a BACK key press for now as a backup.

**Comment by superbigdog** [comment]
@yusunan  I exported  the server.apk and replace the same apk file exiting in this folder:
_nodejs\node_modules\appium\node_modules\appium-uiautomator2-server\apks_
and restart the appium ,but nothing changed. is there something wrong?

**Comment by superbigdog** [comment]
I resolved this problem by updating the appium version to 15.1 in npm tools.

**Comment by superbigdog** [comment]
@yusunan 我改了这块的代码，但是没有生效，并且我也修改了抛出的异常的返回信息，发现在输出日志里输出的错误信息并没有发生改变，我都怀疑是不是server并没有在实际操作中有啥作用。请问您是用的哪个版本，我用的华为mate20，appium版本是V1.13.0，server版本是3.5.1

**Comment by rlagu** [comment]
For my code  : 

await primaryButton.touchAction('tap'); was giving error

```
ERROR webdriver: Request failed due to invalid argument: Coordinate [x=1089.5, y=2704.0] is outside of element rect: [0,0][1440,2621]
    at getErrorFromResponseBody (/Users/rlagu/Documents/appium/node_modules/webdriver/build/utils.js:121:10)
    at Request._callback (/Users/rlagu/Documents/appium/node_modules/webdriver/build/request.js:121:64)
    at Request.self.callback (/Users/rlagu/Documents/appium/node_modules/request/request.js:185:22)
    at Request.emit (events.js:311:20)
    at Request.EventEmitter.emit (domain.js:482:12)
    at Request.<anonymous> (/Users/rlagu/Documents/appium/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:311:20)
    at Request.EventEmitter.emit (domain.js:482:12)
    at IncomingMessage.<anonymous> (/Users/rlagu/Documents/appium/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:417:28)
    at IncomingMessage.emit (events.js:323:22)
    at IncomingMessage.EventEmitter.emit (domain.js:482:12)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[0-4] invalid argument: Coordinate [x=1089.5, y=2704.0] is outside of element rect: [0,0][1440,2621]
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
    at Function.<anonymous> (/Users/rlagu/Documents/appium/src/screens/common/CommonScreen.ts:659:27)
    at fulfilled (/Users/rlagu/Documents/appium/node_modules/tslib/tslib.js:112:62)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  name: 'invalid argument'
}
```
with await primaryButton.click();  I can able to complete operation.

**Comment by sivaprasadtg** [comment]
Hi,
I'm facing the same issue. I'm running Appium v1.20.2, Electron 7.2.4 and Node.js 12.8.1.
I'm totally new with Appium and sorry but finding it difficult to understand the comments already posted here.

If this is a limitation with the UI Automator2, that still exists how to find a solution in any other way. Please assist.

**Comment by KazuCocoa** [comment]
This is basically your code tries to interact with an element which is our of screen as uiautomator framework (by Google).
So, you should make sure the element is in your screen. Or your code needs to wait a bit since sometimes uiautomator takes a few seconds to update the UI condition.

**Comment by sivaprasadtg** [comment]
Hi @KazuCocoa thank you. I'll try adding a wait and check on this.
In addition to this, is there any way to extend the screen area ? I read to reset the center position and reset the x, y coordinates or something from this link: https://github.com/appium/appium/issues/7402 
How does it work ?

**Comment by KazuCocoa** [comment]
The screen area depends on the result of Android side. So, probably the only way is to prepare bigger Android devices.
https://discuss.appium.io/ may also help fo find someways to handle coordinates

**Comment by cmlonder** [comment]
While my touchable Android Screen is 1080x2220, Appium says that it is 1080,2094.  When I check the coordinate that my app tries to click on which is [x=973.0, y=2100.0]  with Appium Desktop, I can see that area is clickable but Appium logs says that 2100 is out of maximum height 2094 which suppose to be 2220. Maybe viewport is being calculated wrongly?

* Size from Terminal
`adb shell wm size`
Physical size: 1080x2220


* Error Log
Got response with status 400: {"sessionId":"aacec956-a58a-4f88-bfc2-92e2a6259dd3","value":{"error":"invalid argument","message":"Coordinate [x=973.0, y=2100.0] is outside of element rect: [0,0][1080,2094]","stacktrace":"io.appium.uiautomator2.common.exceptions.InvalidCoordinatesException: Coordinate [x=973.0, y=2100.0] is outside of element rect: [0,0][1080,2094]\n\tat io.appium.uiautomator2.utils.PositionHelper.getAbsolutePosition(PositionHelper.java:64)\n\tat io.appium.uiautomator2.utils.PositionHelper.getDeviceAbsPos(PositionHelper.java:73)\n\tat io.appium.uiautomator2.handler.Tap.safeHandle(Tap.java:53)\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:41)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:262)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:256)\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:68)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abs...
[debug] [W3C] Matched W3C error code 'invalid argument' to InvalidArgumentError
[debug] [W3C (2ba19062)] Encountered internal error running command: io.appium.uiautomator2.common.exceptions.InvalidCoordinatesException: Coordinate [x=973.0, y=2100.0] is outside of element rect: [0,0][1080,2094]
[debug] [W3C (2ba19062)] 	at io.appium.uiautomator2.utils.PositionHelper.getAbsolutePosition(PositionHelper.java:64)
[debug] [W3C (2ba19062)] 	at io.appium.uiautomator2.utils.PositionHelper.getDeviceAbsPos(PositionHelper.java:73)
[debug] [W3C (2ba19062)] 	at io.appium.uiautomator2.handler.Tap.safeHandle(Tap.java:53)
[debug] [W3C (2ba19062)] 	at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:41)
[debug] [W3C (2ba19062)] 	at io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:262)
[debug] [W3C (2ba19062)] 	at io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:256)
