### ISSUE TITLE
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error getting device platform version. Original error: Error executing adbExec. Original error: 'Command 'C\:\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.release' exited with code 1'; Stderr: 'error: device unauthorized.

### ISSUE THREAD

**Issue by Senthilvel-S** [appium/appium#11254]
**The problem**
Trying to run an appium emulator test in Eclipse tool and it throws an following error 
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error getting device platform version. Original error: Error executing adbExec. Original error: 'Command 'C\:\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.release' exited with code 1'; Stderr: 'error: device unauthorized.

**Environment**
Appium version (or git revision) that exhibits the issue:
Last Appium version that did not exhibit the issue (if applicable): latest version
Desktop OS/version used to run Appium: Windows
Node.js version (unless using Appium.app|exe):
Mobile platform/version under test: Android 7.1.1
Real device or emulator/simulator: Emulator
Appium CLI or Appium.app|exe: CLI

**Code To Reproduce Issue [ Good To Have ]
Desired capabilities set :**
 `public void Test() throws MalformedURLException {
	File appDir = new File("E:\\");
   	//Set Drag-Sort Demos .apk file name.  
	File app = new File(appDir, "XXXX.apk");
	DesiredCapabilities capabilities = new DesiredCapabilities();
  	capabilities.setCapability("deviceName", "Nexus_5_API_25");
	capabilities.setCapability("browserName", "Android");
  	capabilities.setCapability("platformVersion", "7.1.1");
 	capabilities.setCapability("platformName", "Android"); 
  	//Set .apk file's path capabilities.
	capabilities.setCapability("app", app.getAbsolutePath());
  	capabilities.setCapability("appPackage", "com.mobeta.android.demodslv");
  	capabilities.setCapability("appActivity", "com.mobeta.android.demodslv.Launcher");
  	driver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
  	driver.manage().timeouts().implicitlyWait(15, TimeUnit.SECONDS);
 }`

**Appium logs:**

`org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error getting device platform version. Original error: Error executing adbExec. Original error: 'Command 'C\:\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.release' exited with code 1'; Stderr: 'error: device unauthorized.
This adb server's $ADB_VENDOR_KEYS is not set
Try 'adb kill-server' if that seems wrong.
Otherwise check for a confirmation dialog on your device.'; Code: '1' (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 6.10 seconds
Driver info: io.appium.java_client.android.AndroidDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:43)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:249)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:39)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:69)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:78)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:67)
	at Emulator.DrapandDrop.setUp(DrapandDrop.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.TestRunner.beforeRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:616)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
`

**Comment by saikrishna321** [comment]
@Senthilvel-S can you please check if your device is authorized and is present in adb devices.

**Comment by mykola-mokhnach** [comment]
>  Original error: 'Command 'C\:\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.release' exited with code 1'; Stderr: 'error: device unauthorized. This adb server's $ADB_VENDOR_KEYS is not set Try 'adb kill-server' if that seems wrong. Otherwise check for a confirmation dialog on your device.

The error message is quite self-descriptive. There is nothing to add.

**Comment by Senthilvel-S** [comment]
@saikrishna321- Thanks for your response. I have checked through CMD and its list my devices as authorized. But if I run the above code through eclipse I am getting the above error. Any idea on this would be helpful.

**Comment by mykola-mokhnach** [comment]
Set the correct value for `avd` capability
