### ISSUE TITLE
Drag and Drop doesn't work on iOS

### ISSUE THREAD

**Issue by hiteshsh** [appium/appium#11273]
## The problem

I'm trying to perform drag and drop. But it is throwing below error.
**Error:**
INFO: Detected dialect: W3C

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error Domain=com.facebook.WebDriverAgent Code=1 "The '{
    duration = 0;
    type = pause;
}' action item must be preceded by pointerMove item" UserInfo={NSLocalizedDescription=The '{
    duration = 0;
    type = pause;
}' action item must be preceded by pointerMove item}
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: 'INhiteshs.local', ip: '10.132.22.198', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_66'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities {app: /Users/hiteshs/Documents/QA..., browserName: , databaseEnabled: false, deviceName: iPhone X, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: false, platform: MAC, platformName: iOS, platformVersion: 11.2, takesScreenshot: true, udid: D4871E09-89C4-4321-AD2D-37E..., webStorageEnabled: false}
Session ID: ff64e38d-9b10-4ffb-8dbb-94d5e138a100

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.perform(RemoteWebDriver.java:614)
	at appium.GestureTest.dragAndDropNew(GestureTest.java:194)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.0-beta.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac & iOS Simulator
* Node.js version (unless using Appium.app|exe):v9.2.1
* Mobile platform/version under test: iPhone X Simulator(11.2)
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe:
* Appium java client: dfb285e3b8

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/hiteshsh/a1472458c6fdbae8db24f2e0d2edf43e

## Code To Reproduce Issue [ Good To Have ]

 DesiredCapabilities caps = new DesiredCapabilities();
        caps.setCapability(MobileCapabilityType.APP,
                "/Users/hiteshs/Documents/QA/vodqa.zip");
        caps.setCapability(MobileCapabilityType.DEVICE_NAME,
                "iPhone X");
        caps.setCapability(MobileCapabilityType.PLATFORM_VERSION,
                "11.2");
        driver = new IOSDriver(
                new URL("http://127.0.0.1:4723/wd/hub"), caps);
        Thread.sleep(3000);

        driver.findElementByAccessibilityId("login").click();
        Thread.sleep(2000);
        driver.findElementByAccessibilityId("dragAndDrop").click();
        MobileElement dragMe = (MobileElement) driver.findElementByAccessibilityId("dragMe");
        MobileElement drop =(MobileElement)driver.findElementByAccessibilityId("dropzone");

        Thread.sleep(2000);
        Point source = dragMe.getCenter();
        Point target = drop.getCenter();
        PointerInput finger = new PointerInput(PointerInput.Kind.TOUCH, "finger");
        Sequence dragNDrop = new Sequence(finger, 1);
        dragNDrop.addAction(finger.createPointerMove(Duration.ofSeconds(1),
                PointerInput.Origin.viewport(), source.x, source.y));
        dragNDrop.addAction(finger.createPointerDown(PointerInput.MouseButton.MIDDLE.asArg()));
        dragNDrop.addAction(finger.createPointerMove(Duration.ofSeconds(1),
                PointerInput.Origin.viewport(),target.x, target.y));
        dragNDrop.addAction(finger.createPointerUp(PointerInput.MouseButton.MIDDLE.asArg()));
        driver.perform(Arrays.asList(dragNDrop));

**Comment by mykola-mokhnach** [comment]
There is an unexpected pause before the first pointer move action in the chain. Are you sure you use the most recent version of selenium API?

**Comment by mykola-mokhnach** [comment]
https://github.com/SeleniumHQ/selenium/blob/07a18746ff756e90fd79ef253a328bd7dfa9e6dc/java/client/src/org/openqa/selenium/interactions/Sequence.java#L45

I think I know why the problem exists...

**Comment by mykola-mokhnach** [comment]
As a workaround you may try to set the initial length of Sequence to 0

**Comment by mykola-mokhnach** [comment]
Try to add a pause after `createPointerDown` action for at least 600ms. Also the first `createPointerMove` action should have zero duration

**Comment by hiteshsh** [comment]
@mykola-mokhnach 
Tried the above approach but still it didn't work on iOS. But for Android it worked again.
Attaching logs and screen recording link for your reference:
https://gist.github.com/hiteshsh/6e1bc68b7c6df43fd7c52cabb217a197
http://recordit.co/9kkZIwtMLE

**Comment by mykola-mokhnach** [comment]
I don't observe any pause after pointer down in the log above.

**Comment by saikrishna321** [comment]
@mykola-mokhnach if Pause is something xcui needs then how will doubleTap work ?

**Comment by manjunathkonkalmatth** [comment]
driver.perform(Arrays.asList(dragNDrop)); this line is giving compiler error.
