### ISSUE TITLE
IOS appium scripts fails

### ISSUE THREAD

**Issue by hemanthaSN** [appium/appium#11287]
while executing the below script am getting error . please help me on the same
package com.appium.IOS;

import java.net.MalformedURLException;

import java.net.URL;

import org.openqa.selenium.remote.DesiredCapabilities;

import io.appium.java_client.ios.IOSDriver;

import io.appium.java_client.ios.IOSElement;

import io.appium.java_client.remote.AutomationName;

import io.appium.java_client.remote.MobileCapabilityType;

public class base {

	public static void main(String[] args) throws MalformedURLException {

		// TODO Auto-generated method stub

		

		DesiredCapabilities DC=new DesiredCapabilities();

		DC.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone 6");

		DC.setCapability(MobileCapabilityType.PLATFORM_NAME, "IOS");

		DC.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.IOS_XCUI_TEST);

		DC.setCapability(MobileCapabilityType.APP, "//Users//hemanth//Documents//Appium//ios-uicatalog-master//UICatalog.xcodeproj//UICatalog.app");

		IOSDriver<IOSElement> driver=new IOSDriver<>(new URL("http://127.0.0.1:4723/wd/hub"),DC);

		

	}

}Exception in thread "main" org.openqa.selenium.WebDriverException: It is impossible to create a new session because 'createSession' which takes HttpClient, InputStream and long was not found or it is not accessible

Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:13:22.693Z'

System info: host: 'Oliviers-MacBook-Pro.local', ip: 'fdc8:94bb:1e85:2000:b9e6:be4d:66cf:4fb7%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.6', java.version: '1.8.0_181'

Driver info: driver.version: IOSDriver

	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:195)

	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:209)

	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:231)

	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)

	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)

	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)

	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)

	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:212)

	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)

	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)

	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:84)

	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:94)

	at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:95)

	at com.appium.IOS.base.main(base.java:23)

Caused by: java.lang.reflect.InvocationTargetException

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:185)

	... 13 more

Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Bad app: //Users//hemanth//Documents//Appium//ios-uicatalog-master//UICatalog.xcodeproj//UICatalog.app. App paths need to be absolute, or relative to the appium server install dir, or a URL to compressed file, or a special app name.

Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:13:22.693Z'

System info: host: 'Oliviers-MacBook-Pro.local', ip: 'fdc8:94bb:1e85:2000:b9e6:be4d:66cf:4fb7%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.6', java.version: '1.8.0_181'

Driver info: driver.version: IOSDriver

remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Bad app: //Users//hemanth//Documents//Appium//ios-uicatalog-master//UICatalog.xcodeproj//UICatalog.app. App paths need to be absolute, or relative to the appium server install dir, or a URL to compressed file, or a special app name.

    at getResponseForW3CError (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:806:13)

    at asyncHandler$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:361:37)

    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)

    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)

    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)

    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)

    at <anonymous>

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)

	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)

	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:122)

	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)

	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)

	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)

	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)

	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)

	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)

	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)

	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)

	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)

	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:125)

	... 18 more

Error:

**Comment by mykola-mokhnach** [comment]
> An unknown server-side error occurred while processing the command. Original error: Bad app: //Users//hemanth//Documents//Appium//ios-uicatalog-master//UICatalog.xcodeproj//UICatalog.app. App paths need to be absolute, or relative to the appium server install dir, or a URL to compressed file, or a special app name.

The error message is pretty clear there

**Comment by hemanthaSN** [comment]
Thank you

**Comment by priyankasonavane** [comment]
@hemanthaSN  I am getting the same error.In fact I have added the correct app path in my code.Not sure why getting this error.How did you fix it?
