### ISSUE TITLE
Reboot the phone connection problem

### ISSUE THREAD

**Issue by wqk317** [appium/appium#11285]
## The problem

Error after restarting the phone

## Environment

* Appium version (or git revision) that exhibits the issue:  v1.8.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 10 18219
* Node.js version (unless using Appium.app|exe): v10.8.0
* Mobile platform/version under test: Andro 8.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI

## Details

The phone needs to be restarted during the test. It is ok in another test, but this test is reported incorrectly (probably because this test contains UiAutomator?)
another test:
```
while True:
    driver = webdriver.Remote('http://127.0.0.1:4723/wd/hub', desired_caps)

    driver.find_element_by_id("btn_1_s").click()
    driver.find_element_by_id("btn_plus_s").click()
    driver.find_element_by_id("btn_1_s").click()
    driver.find_element_by_id("btn_equal_s").click()
    print "done !"
    driver.quit()
    os.system("adb reboot")
    os.system("adb wait-for-device")
    os.system("adb shell sleep 5s")
```
**it is ok**, But the bottom one will not work.
## Link to Appium logs

https://gist.github.com/wqk317/4f88a9e4ba9427ca4448b54ba4a4a1a9

## Code To Reproduce Issue [ Good To Have ]

Problematic code:(Used to detect the existence of a setting item)
```
while i < 5:
    driver = webdriver.Remote('http://127.0.0.1:4723/wd/hub', desired_caps)

    os.system("adb wait-for-device root")
    os.system("adb shell sleep 5s")
    os.system("adb shell am start -a android.intent.action.MAIN -n com.android.settings/.MainSettings")
    os.system("adb shell input swipe 500 1000 500 500")
    result = driver.find_element_by_android_uiautomator('text(\"锁屏、密码和指纹\")')

    if result:
        print '第', i, '次有*锁屏、密码和指纹*选项'
    else:
        print '第', i, '次没找到指纹选项!!!'
    driver.quit()
    i += 1
    os.system("adb reboot")
    os.system("adb wait-for-device")
    os.system("adb shell sleep 5s")
```

**Comment by mykola-mokhnach** [comment]
The described behaviour is expected. You must restart the driver after phone reboot because the session uiautomator session is killed.

Closed as not an issue

**Comment by mykola-mokhnach** [comment]
The error there

> Unhandled rejection Error: Error executing adbExec. Original error: 'Command 'D\:\\Android\\sdk\\platform-tools\\adb.exe -P 5037 -s 1a64c64b shell am force-stop com.android.settings' exited with code 1'; Stderr: 'error: device '1a64c64b' not found'; Code: '1'


Which means the device is still not visible by adb after reboot

**Comment by wqk317** [comment]
After I disconnected and reconnected here, I started to recognize the device clearly. Why did say that it has already shut down after the connection?
ps: Sorry, I am a newbie, I don't know much about this.
```
[HTTP]
[Logcat] Logcat terminated with code 0, signal null
[UiAutomator] UiAutomator exited unexpectedly with code 0, signal null
[debug] [UiAutomator] Moving to state 'stopped'
[debug] [AndroidDriver] Shutting down Android driver
[debug] [ADB] Running 'D:\Android\sdk\platform-tools\adb.exe -P 5037 -s 1a64c64b shell am force-stop com.android.settings'
[Appium] Closing session, cause was 'UiAUtomator shut down unexpectedly'
[Appium] Removing session 80a8d9c9-ab97-4636-87d7-31e6b9b3ae0b from our master session list
[ADB] Error sending command, reconnecting device and retrying: shell,am,force-stop,com.android.settings
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'D:\Android\sdk\platform-tools\adb.exe -P 5037 -s 1a64c64b shell am force-stop com.android.settings'
[debug] [ADB] Pressing the HOME button
[debug] [ADB] Running 'D:\Android\sdk\platform-tools\adb.exe -P 5037 -s 1a64c64b shell input keyevent 3'
[AndroidBootstrap] Cannot shut down Android bootstrap; it has already shut down
[debug] [Logcat] Stopping logcat capture
[debug] [Logcat] Logcat already stopped
[debug] [ADB] Running 'D:\Android\sdk\platform-tools\adb.exe -P 5037 -s 1a64c64b shell am force-stop io.appium.unlock'
[debug] [AndroidDriver] Not cleaning generated files. Add `clearSystemFiles` capability if wanted.
[HTTP] --> POST /wd/hub/session/80a8d9c9-ab97-4636-87d7-31e6b9b3ae0b/element
[HTTP] {"using":"-android uiautomator","sessionId":"80a8d9c9-ab97-4636-87d7-31e6b9b3ae0b","value":"text(\"锁屏、密码和指纹\")"}
[W3C] Encountered internal error running command: NoSuchDriverError: A session is either terminated or not started
[W3C]     at asyncHandler$ (C:\Users\mi\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:223:15)
[W3C]     at tryCatch (C:\Users\mi\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\mi\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\mi\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[W3C]     at invoke (C:\Users\mi\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[W3C]     at enqueueResult (C:\Users\mi\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:185:17)
[W3C]     at new Promise (<anonymous>)
```

**Comment by mykola-mokhnach** [comment]
The behaviour above does not depend on the appium or the driver itself, but rather on the device and/or ADB. ADB just stops detecting the device at some point, which kills the automation session, and I do not know why it happens.

**Comment by wqk317** [comment]
ok, I solve it
```
os.system("adb shell am start -a android.intent.action.MAIN -n com.android.settings/.MainSettings")
```
it is ok when I delete this line of code, although I don't know why, I think it should be the `appPackage` and `appActivity` of the app started to load, anyway, thanks!

**Comment by Ucoon** [comment]
There occured the same problem in my case after restarting the devices, But i connected 2 devices, 
How should i do?
