### ISSUE TITLE
Can't publish appium-xcuitest-driver in Node version >= 9

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#11296]
Attempting to run `npm version <versionType>` results in an error if Node version is above 8

Logs:

```
Daniel-Graham-SL0192:appium-xcuitest-driver danielgraham$ npm version patch
v2.92.1
npm ERR! code 1
npm ERR! Command failed: git commit -m 2.92.1
npm ERR! Pre-commit checks...
npm ERR! Error: The module '/Users/danielgraham/appium-xcuitest-driver/node_modules/buffertools/build/Release/buffertools.node'
npm ERR! was compiled against a different Node.js version using
npm ERR! NODE_MODULE_VERSION 57. This version of Node.js requires
npm ERR! NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
npm ERR! the module (for instance, using `npm rebuild` or `npm install`).
npm ERR!     at Object.Module._extensions..node (internal/modules/cjs/loader.js:707:18)
npm ERR!     at Module.load (internal/modules/cjs/loader.js:589:32)
npm ERR!     at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:520:3)
npm ERR!     at Module.require (internal/modules/cjs/loader.js:626:17)
npm ERR!     at require (internal/modules/cjs/helpers.js:20:18)
npm ERR!     at Object.<anonymous> (/Users/danielgraham/appium-xcuitest-driver/node_modules/buffertools/buffertools.js:24:20)
npm ERR!     at Module._compile (internal/modules/cjs/loader.js:678:30)
npm ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
npm ERR!     at Module.load (internal/modules/cjs/loader.js:589:32)
npm ERR!     at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:520:3)
npm ERR!     at Module.require (internal/modules/cjs/loader.js:626:17)
npm ERR!     at require (internal/modules/cjs/helpers.js:20:18)
npm ERR!     at Object.<anonymous> (/Users/danielgraham/appium-xcuitest-driver/node_modules/mjpeg-consumer/lib/mjpeg-consumer.js:3:1)
npm ERR!     at Module._compile (internal/modules/cjs/loader.js:678:30)
npm ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
npm ERR!     at Module.load (internal/modules/cjs/loader.js:589:32)
npm ERR!     at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:520:3)
npm ERR!     at Module.require (internal/modules/cjs/loader.js:626:17)
npm ERR!     at require (internal/modules/cjs/helpers.js:20:18)
npm ERR!     at Object.<anonymous> (/Users/danielgraham/appium-xcuitest-driver/node_modules/mjpeg-consumer/index.js:1:18)
npm ERR!     at Module._compile (internal/modules/cjs/loader.js:678:30)
npm ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
npm ERR!     at Module.load (internal/modules/cjs/loader.js:589:32)
npm ERR!     at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:520:3)
npm ERR! pre-commit: 
npm ERR! pre-commit: We've failed to pass the specified git pre-commit hooks as the `precommit-test`
npm ERR! pre-commit: hook returned an exit code (1). If you're feeling adventurous you can
npm ERR! pre-commit: skip the git pre-commit hooks by adding the following flags to your commit:
npm ERR! pre-commit: 
npm ERR! pre-commit:   git commit -n (or --no-verify)
npm ERR! pre-commit: 
npm ERR! pre-commit: This is ill-advised since the commit is broken.
npm ERR! pre-commit: 
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/danielgraham/.npm/_logs/2018-08-31T16_50_41_024Z-debug.log
```

**Comment by imurchie** [comment]
That means you installed the package with one version of node and then switched to another and try to run. This is a problem with having installed native packages.
