### ISSUE TITLE
Exception in thread "main" org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command.

### ISSUE THREAD

**Issue by heming199061** [appium/appium#11314]
## The problem

i can open app with appium，but can't click elements.

How to solve this problem?

## Environment

* Appium desktop:1.8.1
* java-client:6.0.0
* Xcode:9.4.1

## eclipse log

Exception in thread "main" org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Unhandled endpoint: /session/F885DA2F-2CFF-43CE-A609-5F6F8EA22505/wda/screen -- http://localhost:8100/ with parameters {
    wildcards =     (
        "session/F885DA2F-2CFF-43CE-A609-5F6F8EA22505/wda/screen"
    );
}
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'youuzdeMac-mini.local', ip: '192.168.110.5', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.6', java.version: '1.8.0_181'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities {app: /Users/hem/ShareSDKDemo.ipa, automationName: XCuiTest, browserName: , databaseEnabled: false, deviceName: iostest, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: false, platform: MAC, platformName: iOS, platformVersion: 10.3.1, sessionOverride: true, takesScreenshot: true, udid: 71b53307f6b547a37d6e2041443..., webStorageEnabled: false}
Session ID: 0c34de1d-e5a2-4e07-8895-300a2652500f
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:231)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:46)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at io.appium.java_client.HasSessionDetails.getSessionDetails(HasSessionDetails.java:39)
	at io.appium.java_client.HasSessionDetails.getSessionDetail(HasSessionDetails.java:56)
	at io.appium.java_client.HasSessionDetails.getPlatformName(HasSessionDetails.java:65)
	at io.appium.java_client.internal.JsonToMobileElementConverter.<init>(JsonToMobileElementConverter.java:49)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:89)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:94)
	at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:95)
	at gameAPI.appium.AppTest.main(AppTest.java:34)

##  Appium logs

[Appium] Welcome to Appium v1.8.1
[Appium] Non-default server args:
[Appium]   address: 127.0.0.1
[Appium] Appium REST http interface listener started on 127.0.0.1:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"app":"/Users/hem/ShareSDKDemo.ipa","platformVersion":"10.3.1","automationName":"XCuiTest","sessionOverride":true,"platformName":"iOS","udid":"71b53307f6b547a37d6e2041443bbfde2edab71f","deviceName":"iostest"},"capabilities":{"alwaysMatch":{"appium:app":"/Users/hem/ShareSDKDemo.ipa","appium:automationName":"XCuiTest","appium:deviceName":"iostest","platformName":"ios","appium:platformVersion":"10.3.1","sessionOverride":true,"appium:udid":"71b53307f6b547a37d6e2041443bbfde2edab71f"},"firstMatch":[{}]}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/hem/ShareSDKDemo.ipa","platformVersion":"10.3.1","automationName":"XCuiTest","sessionOverride":true,"platformName":"iOS","udid":"71b53307f6b547a37d6e2041443bbfde2edab71f","deviceName":"iostest"},null,{"alwaysMatch":{"appium:app":"/Users/hem/ShareSDKDemo.ipa","appium:automationName":"XCuiTest","appium:deviceName":"iostest","platformName":"ios","appium:platformVersion":"10.3.1","sessionOverride":true,"appium:udid":"71b53307f6b547a37d6e2041443bbfde2edab71f"},"firstMatch":[{}]}]
[BaseDriver] Event 'newSessionRequested' logged at 1536062754806 (20:05:54 GMT+0800 (CST))
[BaseDriver] The capabilities ["sessionOverride"] are not standard capabilities and should have an extension prefix
[Appium] Creating new XCUITestDriver (v2.84.0) session
[Appium] Capabilities:
[Appium]   platformName: ios
[Appium]   sessionOverride: true
[Appium]   app: /Users/hem/ShareSDKDemo.ipa
[Appium]   automationName: XCuiTest
[Appium]   deviceName: iostest
[Appium]   platformVersion: 10.3.1
[Appium]   udid: 71b53307f6b547a37d6e2041443bbfde2edab71f
[BaseDriver] W3C capabilities {"alwaysMatch":{"platformNa... and MJSONWP desired capabilities [object Object] were provided
[BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"platformNa...
[BaseDriver] The following capabilities were provided, but are not recognized by appium: sessionOverride.
[BaseDriver] Session created with session id: 0c34de1d-e5a2-4e07-8895-300a2652500f
[XCUITest] Current user: 'hem'
[XCUITest] Xcode version set to '9.4.1' (tools v9.4.1.0.1.1528165917)
[XCUITest] iOS SDK Version set to '11.4'
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1536062754885 (20:05:54 GMT+0800 (CST))
[XCUITest] Available devices: 71b53307f6b547a37d6e2041443bbfde2edab71f
[XCUITest] Creating iDevice object with udid '71b53307f6b547a37d6e2041443bbfde2edab71f'
[XCUITest] Determining device to run tests on: udid: '71b53307f6b547a37d6e2041443bbfde2edab71f', real device: true
[BaseDriver] Using local app '/Users/hem/ShareSDKDemo.ipa'
[BaseDriver] Copying local zip to tmp dir
[BaseDriver] Unzipping local app '/var/folders/n2/llwylmxn35sfm8xhj6df27m40000gp/T/201884-366-1d5rmmy.2hefh/appium-app.zip'...
[BaseDriver] Unzipping /var/folders/n2/llwylmxn35sfm8xhj6df27m40000gp/T/201884-366-1d5rmmy.2hefh/appium-app.zip
[BaseDriver] Testing zip archive: /var/folders/n2/llwylmxn35sfm8xhj6df27m40000gp/T/201884-366-1d5rmmy.2hefh/appium-app.zip
[BaseDriver] Unzipped local app to '/var/folders/n2/llwylmxn35sfm8xhj6df27m40000gp/T/201884-366-1d5rmmy.2hefh/Payload/ShareSDKDemo.app'
[BaseDriver] Event 'appConfigured' logged at 1536062755483 (20:05:55 GMT+0800 (CST))
[XCUITest] Checking whether app '/var/folders/n2/llwylmxn35sfm8xhj6df27m40000gp/T/201884-366-1d5rmmy.2hefh/Payload/ShareSDKDemo.app' is actually present on file system
[XCUITest] App is present
[iOS] Getting bundle ID from app '/var/folders/n2/llwylmxn35sfm8xhj6df27m40000gp/T/201884-366-1d5rmmy.2hefh/Payload/ShareSDKDemo.app': 'com.mob.product.ShareSDK'
[BaseDriver] Event 'resetStarted' logged at 1536062755527 (20:05:55 GMT+0800 (CST))
[XCUITest] Reset: running ios real device reset flow
[BaseDriver] Event 'resetComplete' logged at 1536062755527 (20:05:55 GMT+0800 (CST))
[iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[iOSLog] Starting iOS device log capture with: 'idevicesyslog'
[XCUITest] Crash reports root '/Users/hem/Library/Logs/CrashReporter/MobileDevice/iPhone 6s Plus' does not exist. Got nothing to gather.
[BaseDriver] Event 'logCaptureStarted' logged at 1536062755731 (20:05:55 GMT+0800 (CST))
[XCUITest] Setting up real device
[XCUITest] Verifying application platform
[XCUITest] CFBundleSupportedPlatforms: ["iPhoneOS"]
[XCUITest] Reset requested. Removing app with id 'com.mob.product.ShareSDK' from the device
[XCUITest] Installing '/var/folders/n2/llwylmxn35sfm8xhj6df27m40000gp/T/201884-366-1d5rmmy.2hefh/Payload/ShareSDKDemo.app' on device with UUID '71b53307f6b547a37d6e2041443bbfde2edab71f'...
[XCUITest] The app has been installed successfully.
[BaseDriver] Event 'appInstalled' logged at 1536062761174 (20:06:01 GMT+0800 (CST))
[XCUITest] Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[iProxy] Error connecting to device!
[XCUITest] WDA is not listening at 'http://localhost:8100/'
[BaseDriver] Event 'wdaStartAttempted' logged at 1536062761240 (20:06:01 GMT+0800 (CST))
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Killing running processes 'xcodebuild.*71b53307f6b547a37d6e2041443bbfde2edab71f, iproxy 8100' for the device 71b53307f6b547a37d6e2041443bbfde2edab71f...
[XCUITest] 'pgrep -nif xcodebuild.*71b53307f6b547a37d6e2041443bbfde2edab71f' didn't detect any matching processes. Return code: 1
[XCUITest] iproxy exited with code 'null'
[XCUITest] 'pgrep -nif iproxy 8100' didn't detect any matching processes. Return code: 1
[XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[XCUITest] Using Xcode 9.4.1, so fixing WDA codebase
[XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=71b53307f6b547a37d6e2041443bbfde2edab71f IPHONEOS_DEPLOYMENT_TARGET=10.3' in directory '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Output from xcodebuild will not be logged. To change this, use 'showXcodeLog' desired capability
[XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Log file for xcodebuild test: /var/folders/n2/llwylmxn35sfm8xhj6df27m40000gp/T/com.apple.dt.XCTest/IDETestRunSession-9EC58EF7-D379-4E98-B6E3-B16DCEADBC87/WebDriverAgentRunner-3A06D053-E98B-485E-957D-BB6856F06DFC/Session-WebDriverAgentRunner-2018-09-04_200607-hheHJS.log
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"10.3.1\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"10.3.1\",\n      \"ip\" : \"192.168.111.146\"\n    },\n    \"build\" : {\n      \"time\" : \"Sep  4 2018 15:33:02\"\n    }\n  },\n  \"sessionId\" : \"0E0C2FFC-2C40-4591-9D9B-9A416A25F38C\",\n  \"status\" : 0\n}"
[XCUITest] WebDriverAgent running on ip '192.168.111.146'
[XCUITest] WebDriverAgent successfully started after 6617ms
[BaseDriver] Event 'wdaSessionAttempted' logged at 1536062773105 (20:06:13 GMT+0800 (CST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.mob.product.ShareSDK","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[JSONWP Proxy] Got response with status 200: {"value":{"sessionId":"F885DA2F-2CFF-43CE-A609-5F6F8EA22505","capabilities":{"device":"iphone","browserName":"ShareSDK","sdkVersion":"10.3.1","CFBundleIdentifier":"com.mob.product.ShareSDK"}},"sessionId":"F885DA2F-2CFF-43CE-A609-5F6F8EA22505","status":0}
[BaseDriver] Event 'wdaSessionStarted' logged at 1536062775317 (20:06:15 GMT+0800 (CST))
[BaseDriver] Event 'wdaStarted' logged at 1536062775317 (20:06:15 GMT+0800 (CST))
[XCUITest] Skipping setting of the initial display orientation. Set the "orientation" capability to either "LANDSCAPE" or "PORTRAIT", if this is an undesired behavior.
[BaseDriver] Event 'orientationSet' logged at 1536062775318 (20:06:15 GMT+0800 (CST))
[Appium] New XCUITestDriver session created successfully, session 0c34de1d-e5a2-4e07-8895-300a2652500f added to master session list
[BaseDriver] Event 'newSessionStarted' logged at 1536062775319 (20:06:15 GMT+0800 (CST))
[W3C] Responding to client with driver.createSession() result: {"capabilities":{"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"platformName":"ios","sessionOverride":true,"app":"/Users/hem/ShareSDKDemo.ipa","automationName":"XCuiTest","deviceName":"iostest","platformVersion":"10.3.1","udid":"71b53307f6b547a37d6e2041443bbfde2edab71f"}}
[HTTP] <-- POST /wd/hub/session 200 20515 ms - 483
[HTTP] 
[HTTP] --> GET /wd/hub/session/0c34de1d-e5a2-4e07-8895-300a2652500f
[HTTP] {}
[W3C] Calling AppiumDriver.getSession() with args: ["0c34de1d-e5a2-4e07-8895-300a2652500f"]
[XCUITest] Executing command 'getSession'
[JSONWP Proxy] Proxying [GET /] to [GET http://localhost:8100/session/F885DA2F-2CFF-43CE-A609-5F6F8EA22505] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"sessionId\" : \"F885DA2F-2CFF-43CE-A609-5F6F8EA22505\",\n    \"capabilities\" : {\n      \"device\" : \"iphone\",\n      \"browserName\" : \"ShareSDK\",\n      \"sdkVersion\" : \"10.3.1\",\n      \"CFBundleIdentifier\" : \"com.mob.product.ShareSDK\"\n    }\n  },\n  \"sessionId\" : \"F885DA2F-2CFF-43CE-A609-5F6F8EA22505\",\n  \"status\" : 0\n}"
[XCUITest] Merging WDA caps over Appium caps for session detail response
[JSONWP Proxy] Proxying [GET /wda/screen] to [GET http://localhost:8100/session/F885DA2F-2CFF-43CE-A609-5F6F8EA22505/wda/screen] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"Unhandled endpoint: \\/session\\/F885DA2F-2CFF-43CE-A609-5F6F8EA22505\\/wda\\/screen -- http:\\/\\/localhost:8100\\/ with parameters {\\n    wildcards =     (\\n        \\\"session\\/F885DA2F-2CFF-43CE-A609-5F6F8EA22505\\/wda\\/screen\\\"\\n    );\\n}\",\n  \"sessionId\" : \"F885DA2F-2CFF-43CE-A609-5F6F8EA22505\",\n  \"status\" : 1\n}"
[MJSONWP] Matched JSONWP error code 1 to UnknownError
[HTTP] <-- GET /wd/hub/session/0c34de1d-e5a2-4e07-8895-300a2652500f 500 129 ms - 1895
[HTTP] 
[XCUITest] Connection to WDA timed out
[iProxy] recv failed: Operation not permitted

## Code 
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.DesiredCapabilities;

import io.appium.java_client.AppiumDriver;
import io.appium.java_client.MobileElement;
import io.appium.java_client.ios.IOSDriver;
import io.appium.java_client.remote.AutomationName;
import io.appium.java_client.remote.MobileCapabilityType;

/**
 * Unit test for simple App.
 */
public class AppTest 
  
{
	private static AppiumDriver<MobileElement> driver;
	
	public static void main(String[] args) throws MalformedURLException {
		DesiredCapabilities	capabilities = new DesiredCapabilities();
		capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "iphone 6s Plus");
		capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iostest");
		capabilities.setCapability("udid", "71b53307f6b547a37d6e2041443bbfde2edab71f");
		capabilities.setCapability("app", "/Users/hem/ShareSDKDemo.ipa");
		capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "10.3.1");
		capabilities.setCapability("sessionOverride", true);
		capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.IOS_XCUI_TEST);
		driver = new IOSDriver<MobileElement>(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
	
		driver.manage().timeouts().implicitlyWait(180,TimeUnit.SECONDS);
		System.out.println(driver.getDeviceTime()+"++++++++++");
	
		//driver.findElementByXPath("//XCUIElementTypeStaticText[@name=\"微信好友\"] ")
		System.out.println(driver.findElement(By.xpath("//XCUIElementTypeStaticText[@name=\"微信好友\"] ")).getText()+"------");
		try {
			Thread.sleep(10000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		//XCUIElementTypeStaticText[@name="微信好友"]    	shareMenuIcon
		driver.quit();
	}

}

**Comment by heming199061** [comment]
I have solved this problem.
Reinstall appium and use the WebDriverAgent that comes with appium.
