### ISSUE TITLE
`npm i` fails on appium-android-driver

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#11329]
## The problem

```
[13:16:01] Using gulpfile ~/appium-android-driver/gulpfile.js
[13:16:01] Starting 'prepublish'...
[13:16:01] Starting 'clean'...
[13:16:01] Finished 'clean' after 65 ms
[13:16:01] Starting 'transpile'...
[13:16:12] Finished 'transpile' after 11 s
[13:16:12] Starting 'ant-clean'...
[13:16:14] 'ant-clean' errored after 1.6 s
[13:16:14] Error: Command 'ant clean' exited with code 1
    at ChildProcess.<anonymous> (../../lib/teen_process.js:97:19)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)
[13:16:14] 'prepublish' errored after 12 s
[13:16:14] Error in plugin 'run-sequence(ant-clean)'
Message:
    Command 'ant clean' exited with code 1
Details:
    stdout: Buildfile: /Users/danielgraham/appium-android-driver/bootstrap/build.xml

    stderr: 
BUILD FAILED
/Users/danielgraham/appium-android-driver/bootstrap/build.xml:107: Cannot find /Users/danielgraham/Library/Android/sdk/tools/ant/uibuild.xml imported from /Users/danielgraham/appium-android-driver/bootstrap/build.xml

Total time: 0 seconds

    code: 1
Stack:
Error: Command 'ant clean' exited with code 1
    at ChildProcess.<anonymous> (../../lib/teen_process.js:97:19)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)

```

## Environment

* Appium version (or git revision) that exhibits the issue: appium-android-driver@4
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Code To Reproduce Issue [ Good To Have ]

```
git clone git@github.com:appium/appium-android-driver.git
cd appium-android-driver
npm i
```

**Comment by imurchie** [comment]
This is because of https://github.com/appium/appium-android-driver#building-the-bootstrap-jar
