### ISSUE TITLE
InvalidSelectorError CSS

### ISSUE THREAD

**Issue by roydekleijn** [appium/appium#11338]
In my script I'm using `name=onboarding.button.continue` and it worked for several weeks. But recently we updated appium to version and now we see the following error:

```
[W3C] Calling AppiumDriver.findElements() with args: ["css selector","*[name='onboarding.button.continue']","5220c453-414a-40c8-9c02-f7c7a1758504"]
[XCUITest] Executing command 'findElements'
[BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[W3C] Encountered internal error running command: InvalidSelectorError: Locator Strategy 'css selector' is not supported for this session
```

So somewhere it is converted to CSS...

What is wrong here?

**Comment by mykola-mokhnach** [comment]
This the problem on the client library side. Make sure you use the most recent version of it. Closed as duplicate

**Comment by roydekleijn** [comment]
I updated the client, but now I get:

```
[JSONWP Proxy] Proxying [GET /] to [GET http://localhost:8100/session/9038F09A-950E-484A-92D4-2F6D9990E8A9] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"sessionId\" : \"9038F09A-950E-484A-92D4-2F6D9990E8A9\",\n    \"capabilities\" : {\n      \"device\" : \"iphone\",\n      \"browserName\" : \"Tessa dev\",\n      \"sdkVersion\" : \"11.4.1\",\n      \"CFBundleIdentifier\" : \"company.tessabv.tessa.dev\"\n    }\n  },\n  \"sessionId\" : \"9038F09A-950E-484A-92D4-2F6D9990E8A9\",\n  \"status\" : 0\n}"
[JSONWP Proxy] Proxying [GET /wda/screen] to [GET http://localhost:8100/session/9038F09A-950E-484A-92D4-2F6D9990E8A9/wda/screen] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"Unhandled endpoint: \\/session\\/9038F09A-950E-484A-92D4-2F6D9990E8A9\\/wda\\/screen -- http:\\/\\/localhost:8100\\/ with parameters {\\n    wildcards =     (\\n        \\\"session\\/9038F09A-950E-484A-92D4-2F6D9990E8A9\\/wda\\/screen\\\"\\n    );\\n}\",\n  \"sessionId\" : \"9038F09A-950E-484A-92D4-2F6D9990E8A9\",\n  \"status\" : 1\n}"
[MJSONWP] Matched JSONWP error code 1 to UnknownError
[W3C] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Unhandled endpoint: /session/9038F09A-950E-484A-92D4-2F6D9990E8A9/wda/screen -- http://localhost:8100/ with parameters {
[W3C]     wildcards =     (
[W3C]         "session/9038F09A-950E-484A-92D4-2F6D9990E8A9/wda/screen"
[W3C]     );
[W3C] }
[W3C]     at errorFromMJSONWPStatusCode (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:787:10)
[W3C]     at ProxyRequestError.getActualError (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:681:14)
[W3C]     at JWProxy.command$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:369:19)
[W3C]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[W3C]     at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[W3C]     at 
[HTTP] <-- GET /wd/hub/session/f7400bdb-467f-4553-88e2-ffd2027122e4 500 1107 ms - 1910

```


Any idea?

**Comment by mykola-mokhnach** [comment]
Check https://github.com/appium/appium/search?q=%22wda%2Fscreen%22&type=Issues
