### ISSUE TITLE
Problem with annotations @iOSXCUITFindBy and @AndroidFindBy in appium 1.9.0

### ISSUE THREAD

**Issue by klebercsilva** [appium/appium#11336]
## The problem

I just downloaded appium 1.9.0 in an attempt to test some of the functionalities that we currently have in our mobile product against iOS 12 but this attempt was quickly frustrated. I tried to run the same exact testing code using appium 1.9.0 and the test didn't go too far. It seems that the annotations down below are still using CSS selector as a valid locator but in appium 1.9.0 it was removed. (We do not use any CSS Selector to find elements, it's mainly IDs and XPath).

@iOSXCUITFindBy(accessibility = "closeIcon")
@AndroidFindBy(id = "closeIcon")
MobileElement closeButton;

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.0
* Last Appium version that did not exhibit the issue (if applicable): 1.8.1
* Desktop OS/version used to run Appium: Mac OS High Sierra
* Node.js version (unless using Appium.app|exe): 10.5.0
* Mobile platform/version under test: Android 8.0 / iOS 11.4
* Real device or emulator/simulator: Real Device Nexus 5 / iPhone 7
* Appium CLI or Appium.app|exe: Appium CLI

### Android Log [Only part that matters]

[HTTP] --> POST /wd/hub/session/bb81c87f-26ee-4e9b-a088-a7fb40bd0e7e/element
[HTTP] {"value":"#closeIcon","using":"css selector"}
[debug] [W3C] Calling AppiumDriver.findElement() with args: ["css selector","#closeIcon","bb81c87f-26ee-4e9b-a088-a7fb40bd0e7e"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[W3C] Encountered internal error running command: InvalidSelectorError: Locator Strategy 'css selector' is not supported for this session
[W3C]     at AndroidDriver.validateLocatorStrategy (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:349:13)
[W3C]     at AndroidDriver.callee$0$0$ (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:26:8)
[W3C]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[W3C]     at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[W3C]     at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
[W3C]     at new Promise (<anonymous>)
[W3C]     at new F (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
[W3C]     at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
[W3C]     at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[W3C]     at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
[W3C]     at AndroidDriver.callee$0$0 [as findElOrElsWithProcessing] (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/build/lib/basedriver/commands/find.js:47:30)
[W3C]     at AndroidDriver.callee$0$0$ (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:46:21)
[W3C]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[W3C]     at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[W3C]     at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
[W3C]     at new Promise (<anonymous>)
[W3C]     at new F (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
[W3C]     at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
[W3C]     at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[W3C]     at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
[W3C]     at AndroidDriver.callee$0$0 [as findElement] (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/build/lib/basedriver/commands/find.js:88:30)
[W3C]     at /usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:296:26
[W3C]     at tryCatcher (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/util.js:26:23)
[W3C]     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/promise.js:510:31)
[W3C]     at Promise._settlePromiseAt (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/promise.js:584:18)
[W3C]     at Promise._settlePromiseAtPostResolution (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/promise.js:248:10)
[W3C]     at Async._drainQueue (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/async.js:128:12)
[W3C]     at Async._drainQueues (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/async.js:133:10)
[W3C]     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/async.js:15:14)
[W3C]     at runCallback (timers.js:696:18)
[W3C]     at tryOnImmediate (timers.js:667:5)
[W3C]     at processImmediate (timers.js:649:5)
[HTTP] <-- POST /wd/hub/session/bb81c87f-26ee-4e9b-a088-a7fb40bd0e7e/element 400 30 ms - 4651

### iOS Log [Only part that matters]

[HTTP] --> POST /wd/hub/session/d9112016-0788-4d1b-b349-56a291230a5f/element
[HTTP] {"value":"closeIcon","using":"accessibility id"}
[debug] [W3C] Calling AppiumDriver.findElement() with args: ["accessibility id","closeIcon","d9112016-0788-4d1b-b349-56a291230a5f"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Matched '/element' to command name 'findElement'
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/D954A713-C153-46E5-9520-876E27590B21/element] with body: {"using":"accessibility id","value":"closeIcon"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"using":"accessibility id","value":"closeIcon","description":"unable to find an element"},"sessionId":"D954A713-C153-46E5-9520-876E27590B21","status":7}
[debug] [MJSONWP] Matched JSONWP error code 7 to NoSuchElementError
[W3C] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
[W3C]     at XCUITestDriver.callee$0$0$ (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:130:13)
[W3C]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[W3C]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session/d9112016-0788-4d1b-b349-56a291230a5f/element 404 244 ms - 944

**Comment by klebercsilva** [comment]
The problem was solved after updating the libraries io.appium.java_client and org.seleniumhq.selenium.selenium-java to the versions: 6.1.0 and 3.14.0 respectively.
