### ISSUE TITLE
Could not proxy command to remote server. Original error: Error: socket hang up

### ISSUE THREAD

**Issue by 631068264** [appium/appium#11332]
appium 1.9   OSX desktop  Android 8.1
```
[JSONWP Proxy] Matched '/wd/hub/session/0d9e3faa-baae-4a77-b4ec-aad424bef9c4/source' to command name 'getPageSource'
[JSONWP Proxy] Proxying [GET /wd/hub/session/0d9e3faa-baae-4a77-b4ec-aad424bef9c4/source] to [GET http://localhost:8200/wd/hub/session/be2e9420-4cdc-4ed5-a402-a0fcb55022c3/source] with body: {"sessionId":"0d9e3faa-baae-4a77-b4ec-aad424bef9c4"}
[JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"be2e9420-4cdc-4ed5-a402-a0fcb55022c3\",\"status\":0,\"value\":\"
[JSONWP Proxy] Replacing sessionId be2e9420-4cdc-4ed5-a402-a0fcb55022c3 with 0d9e3faa-baae-4a77-b4ec-aad424bef9c4
[HTTP] <-- GET /wd/hub/session/0d9e3faa-baae-4a77-b4ec-aad424bef9c4/source 200 133 ms - 13070
[HTTP] 
[HTTP] --> POST /wd/hub/session/0d9e3faa-baae-4a77-b4ec-aad424bef9c4/touch/perform
[HTTP] {"actions":[{"action":"press","options":{"x":540,"y":1536}},{"action":"wait","options":{"ms":0}},{"action":"moveTo","options":{"x":540,"y":1152}},{"action":"release","options":{}}],"sessionId":"0d9e3faa-baae-4a77-b4ec-aad424bef9c4"}
[W3C] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":540,"y":1536}},{"action":"wait","options":{"ms":0}},{"action":"moveTo","options":{"x":540,"y":1152}},{"action":"release","options":{}}],"0d9e3faa-baae-4a77-b4ec-aad424bef9c4"]
[JSONWP Proxy] Matched '/touch/perform' to command name 'performTouch'
[JSONWP Proxy] Proxying [POST /touch/perform] to [POST http://localhost:8200/wd/hub/session/be2e9420-4cdc-4ed5-a402-a0fcb55022c3/touch/perform] with body: {"startX":540,"startY":1536,"endX":540,"endY":1152,"steps":22}
```
wait a long time can't get any response. And then get the error.  
```
[UiAutomator2] [UIAutomator2] io.appium.uiautomator2.server.test.AppiumUiAutomator2Server:
[Logcat] Logcat terminated with code 0, signal null
[W3C] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up
[W3C]     at JWProxy.command$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:371:13)
[W3C]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[W3C]     at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[W3C]     at 
[W3C]     at process._tickCallback (internal/process/next_tick.js:188:7)
[HTTP] <-- POST /wd/hub/session/0d9e3faa-baae-4a77-b4ec-aad424bef9c4/touch/perform 500 305 ms - 1350
[HTTP] 
```
sometimes get this error
```
[HTTP] {"actions":[{"action":"press","options":{"x":540,"y":1536}},{"action":"wait","options":{"ms":0}},{"action":"moveTo","options":{"x":540,"y":1152}},{"action":"release","options":{}}],"sessionId":"bf78e84d-d64e-4bc4-b4b5-791740497b10"}
[W3C] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":540,"y":1536}},{"action":"wait","options":{"ms":0}},{"action":"moveTo","options":{"x":540,"y":1152}},{"action":"release","options":{}}],"bf78e84d-d64e-4bc4-b4b5-791740497b10"]
[JSONWP Proxy] Matched '/touch/perform' to command name 'performTouch'
[JSONWP Proxy] Proxying [POST /touch/perform] to [POST http://localhost:8202/wd/hub/session/fad74813-b18a-4a73-b1b1-f181b541054e/touch/perform] with body: {"startX":540,"startY":1536,"endX":540,"endY":1152,"steps":22}
[W3C] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: ESOCKETTIMEDOUT
[W3C]     at JWProxy.command$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:371:13)
[W3C]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[W3C]     at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[W3C]     at 
[HTTP] <-- POST /wd/hub/session/bf78e84d-d64e-4bc4-b4b5-791740497b10/touch/perform 500 242791 ms - 1284
```
 After running my program a few minutes, it couldn't get any responses because **socket hang up**.

```
host = 'localhost'
port = 4723
url = 'http://{host}:{port}/wd/hub'.format(host=host, port=port)
desired_caps = {'deviceName': 'ONEPLUS_A5000', 'appPackage': 'com.kingnet.fiveline',
                'appActivity': 'com.kingnet.fiveline.ui.welcome.WelcomeActivity', 'platformName': 'Android',
                'noReset': True,
                'appWaitActivity': 'com.kingnet.fiveline.ui.main.MainActivity',
                'automationName': 'uiautomator2',
                'newCommandTimeout': 0,
                }
```

**Comment by mykola-mokhnach** [comment]
Such error means that the server stops responding. This might happen due to multiple reasons. I would try to investigate `adb logcat` output

**Comment by 631068264** [comment]
How to get that ? Do you mean that appium-server log with **[ADB]** ?
[whole appium-server log](https://gist.github.com/631068264/05e46afd0d75fc33079e4a5ccf2ee30d)

[five_line.logcat.zip](https://github.com/appium/appium/files/2359898/five_line.txt.zip)

**Comment by mykola-mokhnach** [comment]
I don't observe anything suspicious in the attached logs. Most likely it is an internal problem with the device or ADB. Try to run the test on the other device and make sure the developer tools are up to date.

**Comment by 631068264** [comment]
```
➜  ~ adb version
Android Debug Bridge version 1.0.40
Version 4986621
Installed as /Users/wyx/Library/Android/sdk/platform-tools/adb
```

Appium-Python-Client==0.28
selenium==3.14.0
py3.6

appium is the newest version

**Comment by KazuCocoa** [comment]
After facing the `getPageSource` error, what about restarting `adb` server by manual?
If the error is adb hang out, the restarting adb alleviates the issue.

---

memo

- crash
    - https://gist.github.com/KazuCocoa/d0fdd1971b3db8644d7b6f2032a569df
- Skipping invisible child 
    - https://gist.github.com/KazuCocoa/d0fdd1971b3db8644d7b6f2032a569df#gistcomment-2702487

**Comment by mykola-mokhnach** [comment]
There is nothing that can be done on Appium side. closed as third party issue
