### ISSUE TITLE
appium cant interact with elements of chromium window application 

### ISSUE THREAD

**Issue by MuhammadzaibLiquidsky** [appium/appium#11358]
## The problem
org.openqa.selenium.WebDriverException: Returned value cannot be converted to WebElement: {stacktrace=NoSuchElementError: An element could not be located on the page using the given search parameters.

tried using id/xpath/css nothing works 
appium java client anything over latest 5 version doesn't work or even runs appium. currently using 5.4, 6.0 or 6.1 doesn't work 

## Environment

* Appium version 1.9.0
* Desktop OS/version used to run Appium: windows 10

## Details
app launches but unable to interact with elements 

## Link to Appium logs

[gist logs
](https://gist.github.com/MuhammadzaibLiquidsky/069e3934b7352c7e8810e556047560e5)

**Comment by mykola-mokhnach** [comment]
I don't observe any issues in the log

**Comment by MuhammadzaibLiquidsky** [comment]
> I don't observe any issues in the log

{"using":"xpath","value":"//input[@id='loginEmailInput']"}
[WinAppDriver] [STDOUT] HTTP/1.1 404 Not Found
[WinAppDriver] [STDOUT] Content-Length: 139
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] {"status":7,"value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters."}}
[W3C] Encountered internal error running command:  {"w3cStatus":404,"w3c":{"error":"no such element","message":"An element could not be located on the page using the given search parameters."}} ProxyRequestError: Could not proxy command to remote server. Original error: 404 - {"status":7,"value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters."}}
[W3C]     at JWProxy.proxy$ (C:\Users\Muhammad Zaib\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:152:13)
[W3C]     at tryCatch (C:\Users\Muhammad Zaib\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\Muhammad Zaib\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\Muhammad Zaib\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[W3C]     at GeneratorFunctionPrototype.invoke (C:\Users\Muhammad Zaib\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[W3C]     at 
[W3C] Matched W3C error code 'no such element' to NoSuchElementError
[HTTP] <-- POST /wd/hub/session/5a152e9e-fd39-4382-8384-e7faad42aee2/element 404 140 ms - 1958
[HTTP]

**Comment by MuhammadzaibLiquidsky** [comment]
`
    public static WindowsDriver wd;


    @BeforeTest
    public static void WindowDr() throws MalformedURLException {

        DesiredCapabilities cap = new DesiredCapabilities();
        cap.setCapability("platformName", "Windows");
        cap.setCapability("deviceName", "Windows PC");
        cap.setCapability("app", "C:\\Users\\Muhammad Zaib\\AppData\\Roaming\\LiquidSky\\lib\\LiquidSkyV.exe.lnk");
        wd = new WindowsDriver(new URL("http://0.0.0.0:4723/wd/hub"), cap);
        wd.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS);


    }


    @Test
    public void setUp() throws InterruptedException {

        Thread.sleep(3000);
        Actions action = new Actions(wd);

     action.sendKeys(Keys.ENTER).build().perform();




    }
@Test
    public void login() throws InterruptedException {
        setUp();
        Thread.sleep(2000);
    Actions action = new Actions(wd);
    WebElement login = wd.findElement(By.xpath("//input[@id='loginEmailInput']"));
    action.moveToElement(login).sendKeys("okay").build().perform();

}

}
`
my code

**Comment by mykola-mokhnach** [comment]
Is such element present in page source?

**Comment by MuhammadzaibLiquidsky** [comment]
> Is such element present in page source?

![screenshot 4 _li](https://user-images.githubusercontent.com/42753613/45444854-9ff84e00-b696-11e8-93c4-5033debf7f13.jpg)

**Comment by mykola-mokhnach** [comment]
This is the html page source, but how about the page source that the driver itself generates? The accessibility structure is for sure different from the internal web page structure.

**Comment by MuhammadzaibLiquidsky** [comment]
`org.openqa.selenium.WebDriverException: Returned value cannot be converted to WebElement: {stacktrace=NoSuchElementError: Could not proxy command to remote server. Original error: 404 - {"status":7,"value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters."}}
    at errorFromW3CJsonCode (C:\Users\Muhammad Zaib\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:784:12)
    at ProxyRequestError.getActualError (C:\Users\Muhammad Zaib\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:676:14)
    at asyncHandler$ (C:\Users\Muhammad Zaib\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:354:25)
    at tryCatch (C:\Users\Muhammad Zaib\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\Muhammad Zaib\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\Muhammad Zaib\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\Muhammad Zaib\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at <anonymous>, error=no such element, message=Could not proxy command to remote server. Original error: 404 - {"status":7,"value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters."}}}
Build info: version: '3.9.1', revision: '63f7b50', time: '2018-02-07T22:25:02.294Z'
System info: host: 'DESKTOP-VBCSP1B', ip: '10.50.128.64', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '10.0.2'
Driver info: driver.version: WindowsDriver

	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:423)
	at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:62)
	at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
	at io.appium.java_client.windows.WindowsDriver.findElement(WindowsDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:518)
	at io.appium.java_client.DefaultGenericMobileDriver.findElementByXPath(DefaultGenericMobileDriver.java:152)
	at io.appium.java_client.AppiumDriver.findElementByXPath(AppiumDriver.java:1)
	at io.appium.java_client.windows.WindowsDriver.findElementByXPath(WindowsDriver.java:1)
	at org.openqa.selenium.By$ByXPath.findElement(By.java:361)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:408)
	at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:58)
	at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
	at io.appium.java_client.windows.WindowsDriver.findElement(WindowsDriver.java:1)
	at WindowSetUp.login(WindowSetUp.java:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
Caused by: java.lang.ClassCastException: com.google.common.collect.Maps$TransformedEntriesMap cannot be cast to org.openqa.selenium.WebElement
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:421)
	... 37 more`

**Comment by MuhammadzaibLiquidsky** [comment]
> This is the html page source, but how about the page source that the driver itself generates? The accessibility structure is for sure different from the internal web page structure.

assuming you're asking for selenium driver logs

**Comment by MuhammadzaibLiquidsky** [comment]
> I need `driver.getPageSource()`

`<?xml version="1.0" encoding="utf-16"?><Window AcceleratorKey="" AccessKey="" AutomationId="" ClassName="LiquidSky" FrameworkId="Win32" HasKeyboardFocus="True" HelpText="" IsContentElement="True" IsControlElement="True" IsEnabled="True" IsKeyboardFocusable="True" IsOffscreen="False" IsPassword="False" IsRequiredForForm="False" ItemStatus="" ItemType="" LocalizedControlType="window" Name="楌畱摩歓y" Orientation="None" ProcessId="10380" RuntimeId="42.11535292" x="0" y="0" width="1922" height="858" CanMaximize="True" CanMinimize="True" IsModal="False" WindowVisualState="Normal" WindowInteractionState="ReadyForUserInteraction" IsTopmost="False" CanRotate="False" CanResize="True" CanMove="True" IsAvailable="True"><TitleBar AcceleratorKey="" AutomationId="" ClassName="" FrameworkId="" HasKeyboardFocus="False" IsContentElement="False" IsControlElement="True" IsEnabled="True" IsKeyboardFocusable="True" IsOffscreen="False" IsPassword="False" IsRequiredForForm="False" ItemStatus="" ItemType="" LocalizedControlType="title bar" Orientation="None" ProcessId="10380" RuntimeId="42.11535292.3.-2147483647.11535292.-2.0" x="21" y="3" width="1900" height="35"><MenuBar AcceleratorKey="" AccessKey="Alt+Space" AutomationId="MenuBar" ClassName="" FrameworkId="" HasKeyboardFocus="False" IsContentElement="False" IsControlElement="True" IsEnabled="True" IsKeyboardFocusable="True" IsOffscreen="False" IsPassword="False" IsRequiredForForm="False" ItemStatus="" ItemType="" LocalizedControlType="menu bar" Name="System" Orientation="None" ProcessId="10380" RuntimeId="42.11535292.3.-2147483646.10380.1114239.0" x="1" y="9" width="28" height="28"><MenuItem AcceleratorKey="" AccessKey="Space" AutomationId="" ClassName="" FrameworkId="" HasKeyboardFocus="False" IsContentElement="True" IsControlElement="True" IsEnabled="True" IsKeyboardFocusable="True" IsOffscreen="False" IsPassword="False" IsRequiredForForm="False" ItemStatus="" ItemType="" LocalizedControlType="menu item" Name="System" Orientation="None" ProcessId="10380" RuntimeId="42.11535292.3.-2147483646.10380.1114239.1" x="1" y="9" width="28" height="28" ExpandCollapseState="Collapsed" IsAvailable="True" /></MenuBar><Button AcceleratorKey="" AutomationId="" ClassName="" FrameworkId="" HasKeyboardFocus="False" IsContentElement="False" IsControlElement="True" IsEnabled="True" IsKeyboardFocusable="False" IsOffscreen="False" IsPassword="False" IsRequiredForForm="False" ItemStatus="" ItemType="" LocalizedControlType="button" Name="Minimize" Orientation="None" ProcessId="10380" RuntimeId="42.11535292.3.-2147483647.11535292.-2.2" x="1743" y="1" width="60" height="37" /><Button AcceleratorKey="" AutomationId="" ClassName="" FrameworkId="" HasKeyboardFocus="False" IsContentElement="False" IsControlElement="True" IsEnabled="True" IsKeyboardFocusable="False" IsOffscreen="False" IsPassword="False" IsRequiredForForm="False" ItemStatus="" ItemType="" LocalizedControlType="button" Name="Maximize" Orientation="None" ProcessId="10380" RuntimeId="42.11535292.3.-2147483647.11535292.-2.3" x="1803" y="1" width="59" height="37" /><Button AcceleratorKey="" AutomationId="" ClassName="" FrameworkId="" HasKeyboardFocus="False" IsContentElement="False" IsControlElement="True" IsEnabled="True" IsKeyboardFocusable="False" IsOffscreen="False" IsPassword="False" IsRequiredForForm="False" ItemStatus="" ItemType="" LocalizedControlType="button" Name="Close" Orientation="None" ProcessId="10380" RuntimeId="42.11535292.3.-2147483647.11535292.-2.5" x="1862" y="1" width="60" height="37" /></TitleBar></Window>
`

**Comment by mykola-mokhnach** [comment]
there is no any element with `loginEmailInput` id in that XML, so I would assume the current behaviour is not a bug.
