### ISSUE TITLE
Unable to run test on Android with Selendroid - ECONNRESET

### ISSUE THREAD

**Issue by gramai** [appium/appium#11361]
## Problem description

I am trying to run tests on a hybrid app on both Android and iOS. I run the tests on multiple appium servers and everything works fine, except one device with Android 7.0 .
At first run, everything works fine. If I stop the test and retry, I get:

`[W3C] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: Error: read ECONNRESET`

## Environment

* Appium version that exhibits the issue:  1.8.2-beta
* Desktop OS/version used to run Appium: macOS High Sierra 10.13.6
* Node.js version (unless using Appium.app|exe): 10.6.0
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator: Samsung Galaxy S7 Edge
* Appium CLI or Appium.app|exe: Appium CLI

## Details

For this device, I am using the following args for the appium server:
`   
    '-p': 5123,
    '--webdriveragent-port': 8500,
    '--selendroid-port': 4644,
    '-c': udids['Samsung_Galaxy_S7']
`

## Link to Appium logs

[GIST](https://gist.github.com/gramai/1adffcb1f856291dd2650f68be1de794) 

## Code To Reproduce Issue 

I create a remote connection as following:
`                self.driver = webdriver.Remote('http://localhost:' + str(self.PORT) +
                                               '/wd/hub', self.DESIRED_CAPS)`
Afterwards, I check if the connection is ok by trying to do : 
`self.driver.implicitly_wait(40)`

After this, I get the following error (that is not present in the appium logs, because I redirect the output to a file using  '>>')
`
2018-09-13 11:09:28:030 - [W3C] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: Error: read ECONNRESET
2018-09-13 11:09:28:030 - [W3C]     at doJwpProxy$ (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:456:13)
2018-09-13 11:09:28:030 - [W3C]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
2018-09-13 11:09:28:031 - [W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
2018-09-13 11:09:28:031 - [W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
2018-09-13 11:09:28:031 - [W3C]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
2018-09-13 14:09:28,048: DEBUG: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: Error: read ECONNRESET
`
As I have previously said, I only get this error on this only device! I work with two other Android devices and have no problems doing so.
The Error is bypassed by reinstalling the app or restarting the device, both of this options are extremely inconvenient for me.
I stand by for any additional information.

**Comment by mykola-mokhnach** [comment]
Sendroid is considered obsolete for Android 5+. Use uiautomator2 automation backend instead

**Comment by mykola-mokhnach** [comment]
If web views are debuggable and can be seen in chome remote debugger then Appium should be able to see them as well. Have you checked http://appium.io/docs/en/writing-running-appium/web/hybrid/ ?

**Comment by gramai** [comment]
Yes, I have checked the site. I can't see the web views in chrome remote debugger but I can see them using selendroid as automationName

**Comment by gramai** [comment]
[Full appium logs](https://gist.github.com/gramai/741ba071a4ee2c5305142b104cb0f7f1)

**Comment by gramai** [comment]
As I can see, this seems to be the problem:
`2018-09-13 14:16:42:986 - [debug] [ADB] Getting focused package and activity
2018-09-13 14:16:42:987 - [debug] [ADB] Running '/Users/brdmobile/Library/Android/sdk/platform-tools/adb -P 5037 -s ce091719994f662403 shell dumpsys window windows'
2018-09-13 14:16:43:082 - [debug] [ADB] Found package: 'brd.bankingapp.android' and fully qualified activity name : 'ind.bankingapp.android.framework.activity.FragmentHolderActivity'
2018-09-13 14:16:43:082 - [debug] [ADB] Incorrect package and activity. Retrying.
2018-09-13 14:16:43:082 - [Selendroid] Selendroid did not start the activity we were waiting for, 'brd.bankingapp.android/ind.bankingapp.android.framework.activity.ActivatorActivity'. Starting it ourselves
`

**Comment by mykola-mokhnach** [comment]
Sorry, but like I said Selendroid is considered obsolete for Android 4.4+
You could still use it, but then you are all on your own.
