### ISSUE TITLE
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: An unknown server-side error occurred while processing the command. Original error: Command 'java' not found. Is it installed? (WARNING: The server did not provide any stacktrace information)

### ISSUE THREAD

**Issue by negruNG** [appium/appium#11413]
## The problem

Look at the title.

## Environment

* Appium v1.9.1
* Windows OS
* Android
* Real device 

## Code To Reproduce Issue [ Good To Have ]

```
package tests;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import org.openqa.selenium.remote.DesiredCapabilities;

import io.appium.java_client.AppiumDriver;
import io.appium.java_client.MobileElement;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.remote.MobileCapabilityType;

public class AppiumTest{
    public static void main(String[] args) throws MalformedURLException{
        AppiumDriver<?> driver;
        final String URL_STRING = "http://127.0.0.1:4723/wd/hub";
        URL url = new URL(URL_STRING);

		File f=new File("src");
		File fs=new File(f,"ApiDemos-debug.apk");

        DesiredCapabilities androidCapabilities = new DesiredCapabilities();
        //androidCapabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "Android");
        //androidCapabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "UiAutomator2");
        androidCapabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "PSP3512DUO");

        androidCapabilities.setCapability(MobileCapabilityType.APP, fs.getAbsolutePath());

        driver = new AndroidDriver<MobileElement>(url, androidCapabilities);
        driver.closeApp();
    }
}


```

Error log:

```
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: An unknown server-side error occurred while processing the command. Original error: Command 'java' not found. Is it installed? (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.3.1', revision: '5234b325d5', time: '2017-03-10 09:10:29 +0000'
System info: host: 'NEMANJA-PC', ip: '169.254.248.80', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_181'
Driver info: driver.version: AndroidDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:216)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:168)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:367)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:113)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:141)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:604)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:27)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:244)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:158)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:22)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:202)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:50)
	at tests.AppiumTest.main(AppiumTest.java:30)
```

**Comment by mykola-mokhnach** [comment]
This is the problem with the process environment. The link above must be helpful. 

Closed as not an issue.
