### ISSUE TITLE
[Error: Could not detect Mac OS X Version from sw_vers output: '10.14 ']

### ISSUE THREAD

**Issue by furmanjmx** [appium/appium#11422]
## The problem

I update my mac to new 10.14 Mojave and i have the problem

My appium is 1.9.0 

info AppiumDoctor Appium Doctor v.1.5.0
info AppiumDoctor ### Diagnostic starting ###
info AppiumDoctor  ✔ The Node.js binary was found at: /usr/local/bin/node
info AppiumDoctor  ✔ Node version is 10.8.0
info AppiumDoctor  ✔ Xcode is installed at: /Applications/Xcode.app/Contents/Developer
Error: Could not detect Mac OS X Version from sw_vers output: '10.14'
    at Object.macOsxVersion$ (/usr/local/lib/node_modules/appium-doctor/node_modules/appium-support/lib/system.js:43:11)
    at tryCatch (/usr/local/lib/node_modules/appium-doctor/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium-doctor/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium-doctor/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium-doctor/node_modules/babel-runtime/regenerator/runtime.js:136:37)

**Comment by zmeriksen** [comment]
I am getting the same issue

```~/D/_/C/_/f/a/specs ❯❯❯ appium-doctor                    master ✱ ◼
info AppiumDoctor Appium Doctor v.1.5.0
info AppiumDoctor ### Diagnostic starting ###
info AppiumDoctor  ✔ The Node.js binary was found at: /usr/local/bin/node
info AppiumDoctor  ✔ Node version is 10.9.0
info AppiumDoctor  ✔ Xcode is installed at: /Applications/Xcode-10.app/Contents/Developer
Error: Could not detect Mac OS X Version from sw_vers output: '10.14'
    at Object.macOsxVersion$ (/usr/local/lib/node_modules/appium-doctor/node_modules/appium-support/lib/system.js:43:11)
    at tryCatch (/usr/local/lib/node_modules/appium-doctor/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium-doctor/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium-doctor/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium-doctor/node_modules/babel-runtime/regenerator/runtime.js:136:37)```

**Comment by DeChrish** [comment]
Any ETA?

**Comment by pratikborole** [comment]
It would be helpful if theres a workaround for this.

**Comment by DeChrish** [comment]
any plans?

**Comment by imurchie** [comment]
The latest beta of Appium ought to work for this.

**Comment by ddaypunk06** [comment]
@imurchie the beta 1.9.2-beta.2 did not resolve the issue for me

**Comment by pratikborole** [comment]
v1.9.1 working fine for me.

**Comment by MythilyM** [comment]
With Appium 1.9.1, am facing this issue. 
@pratikborole, did you configure any thing else to have that working with v1.9.1?

**Comment by pratikborole** [comment]
@MythilyM I just updated appium (v1.9.1) and appium-doctor (v1.6.0). Worked as expected after that.

**Comment by MythilyM** [comment]
Awesome! @pratikborole, thank you for the quick reply.  Upgrading appium-doctor to v1.6.0 isn't giving me the above error.
