### ISSUE TITLE
Cannot retrieve version number from 'chromedriver' Chromedriver binary

### ISSUE THREAD

**Issue by chenchengyuan** [appium/appium#11431]
## The problem
I built a chromedriver from the Repository https://chromium.googlesource.com/chromium/src/+/57.0.2987.132.
It has a version number("2.27") in the default version file .
When I run ```driver.switch_to.context()``` , appium log error
```
[Chromedriver] Cannot retrieve version number from 'chromedriver' Chromedriver binary. Make sure it returns a valid version string in response to '--version' command line argument. Cannot parse the version string
[Chromedriver] Stdout: ChromeDriver 2.27 (4633807610a9c9ecf3e4a70b49380c949b64d329)
```
So, I think the regular expression in the ```node_modules/appium/node_modules/appium-chromedriver/lib/chromedriver.js```（line 167）can be modified (maybe ```/ChromeDriver\s(\d+\.\d+)/```), and it does not affect the release version, what do you think?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Desktop OS/version used to run Appium: Macos 10.13.6
* Node.js version (unless using Appium.app|exe): v8.12.0
* Mobile platform/version under test: Android8.1.0
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI 

## Link to Appium logs

```
[debug] [Chromedriver] Changed state to 'starting'
[debug] [Chromedriver] Found 1 executable in '/Users/chen/.nvm/versions/node/v8.12.0/lib/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac'
[Chromedriver] Cannot retrieve version number from 'chromedriver' Chromedriver binary. Make sure it returns a valid version string in response to '--version' command line argument. Cannot parse the version string
[Chromedriver] Stdout: ChromeDriver 2.27 (4633807610a9c9ecf3e4a70b49380c949b64d329)
[Chromedriver]
[Chromedriver] Error: No Chromedrivers found in '/Users/chen/.nvm/versions/node/v8.12.0/lib/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac'
[Chromedriver]     at Object.wrappedLogger.errorAndThrow (/Users/chen/.nvm/versions/node/v8.12.0/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[Chromedriver]     at Chromedriver.getChromedrivers$ (/Users/chen/.nvm/versions/node/v8.12.0/lib/node_modules/appium/node_modules/appium-chromedriver/lib/chromedriver.js:181:11)
[Chromedriver]     at tryCatch (/Users/chen/.nvm/versions/node/v8.12.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[Chromedriver]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/chen/.nvm/versions/node/v8.12.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[Chromedriver]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/chen/.nvm/versions/node/v8.12.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[Chromedriver]     at GeneratorFunctionPrototype.invoke (/Users/chen/.nvm/versions/node/v8.12.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[Chromedriver]     at <anonymous>
```

## Code To Reproduce Issue [ Good To Have ]

```
driver.switch_to.context('WEBVIEW_com.tencent.mm:toolsmp')
```

**Comment by mykola-mokhnach** [comment]
The fix has been published in appium@beta
