### ISSUE TITLE
IOS Appium Unable to use [swipe] method.

### ISSUE THREAD

**Issue by xukaixin11** [appium/appium#11430]
## The problem
use swipe method be error
## Environment
* Appium version (or git revision) that exhibits the issue: v1.8.1
* Desktop OS/version used to run Appium:Mac
* Node.js version (unless using Appium.app|exe): v10.9.0
* Mobile platform/version under test: Any iOS
* Real device or emulator/simulator: iPhone
## Details
Appium-version v1.8.1
IPhone-version v10.1
Xcode-version v9.4.1
Java-client v4.01
Using swipe or TouchAction class times wrong。

Hoping to get help.Thank you!
## Code To Reproduce Issue [ Good To Have ]
Code：driver.swipe(x - (x / 7), y / 2, x / 7, y / 2, 1000);
Appium Error log：
[HTTP] --> POST /wd/hub/session/5c8d18d5-6794-4be4-b909-bd26547221f6/touch/perform
[HTTP] {"actions":[{"action":"press","options":{"x":322,"y":333}},{"action":"wait","options":{"ms":1000}},{"action":"moveTo","options":{"x":-269,"y":0}},{"action":"release","options":{}}]}
[debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":322,"y":333}},{"action":"wait","options":{"ms":1000}},{"action":"moveTo","options":{"x":-269,"y":0}},{"action":"release","options":{}}],"5c8d18d5-6794-4be4-b909-bd26547221f6"]
[debug] [XCUITest] Executing command 'performTouch'
[debug] [XCUITest] Received the following touch action: press(options={"x":322,"y":333})-wait(options={"ms":1000})-moveTo(options={"x":-269,"y":0})-release(options={})
[debug] [JSONWP Proxy] Proxying [POST /wda/touch/perform] to [POST http://localhost:8100/session/6241A134-1BB9-40E7-B214-5FFAE73CE2B9/wda/touch/perform] with body: {"actions":[{"action":"press","options":{"x":322,"y":333}},{"action":"wait","options":{"ms":1000}},{"action":"moveTo","options":{"x":-269,"y":0}},{"action":"release","options":{}}]}
[debug] [JSONWP Proxy] Got response with status 200: {"value":"Unhandled endpoint: /session/6241A134-1BB9-40E7-B214-5FFAE73CE2B9/wda/touch/perform -- http://localhost:8100/ with parameters {\n    wildcards =     (\n        \"session/6241A134-1BB9-40E7-B214-5FFAE73CE2B9/wda/touch/perform\"\n    );\n}","sessionId":"6241A134-1BB9-40E7-B214-5FFAE73CE2B9","status":1}
[debug] [MJSONWP] Matched JSONWP error code 1 to UnknownError
[HTTP] <-- POST /wd/hub/session/5c8d18d5-6794-4be4-b909-bd26547221f6/touch/perform 500 10 ms - 408
Java Error log:
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Unhandled endpoint: /session/6241A134-1BB9-40E7-B214-5FFAE73CE2B9/wda/touch/perform -- http://localhost:8100/ with parameters {
    wildcards =     (
        "session/6241A134-1BB9-40E7-B214-5FFAE73CE2B9/wda/touch/perform"
    );
} (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 95 milliseconds
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'xukaixindeMac-mini.local', ip: '10.102.24.186', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.6', java.version: '1.8.0_181'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{app=/Users/xuhappy/Library/Developer/Xcode/DerivedData/HangJia-dmzxcmcimgnwfpatuwukcglqzdzp/Build/Products/Debug-iphonesimulator/HangJia.app, networkConnectionEnabled=false, noReset=true, noSign=true, bundleId=com.gzyghn.lifeplus, databaseEnabled=false, deviceName=iPhone 6, platform=MAC, platformVersion=10.1, webStorageEnabled=false, locationContextEnabled=false, automationName=XCUITest, browserName=, takesScreenshot=true, javascriptEnabled=true, platformName=iOS, udid=DBF78271-9608-49AE-A7D5-9A8F2532B7AE, autoAcceptAlerts=true}]
Session ID: 5c8d18d5-6794-4be4-b909-bd26547221f6
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:40)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at io.appium.java_client.AppiumDriver.performTouchAction(AppiumDriver.java:336)
	at io.appium.java_client.TouchAction.perform(TouchAction.java:323)
	at io.appium.java_client.AppiumDriver.doSwipe(AppiumDriver.java:383)
	at io.appium.java_client.ios.IOSDriver.swipe(IOSDriver.java:176)
	at com.yiqi.hj.util.AutomationApi.slideUI(AutomationApi.java:472)
	at com.yiqi.hj.util.AutomationApi.automaticOperation(AutomationApi.java:292)
	at com.yiqi.hj.activity.welcome.WelcomeActivityControl.testThere(WelcomeActivityControl.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

**Comment by saikrishna321** [comment]
@xukaixin11 

> Java-client v4.01

Please update to latest v 6.1.0 we don't support version 4.0.1.

Please ask for questions in discuss.appiu.io
