### ISSUE TITLE
org.openqa.selenium.UnsupportedCommandException: touchScroll

### ISSUE THREAD

**Issue by sjlnl** [appium/appium#11433]
## The problem
When I open h5 using chrome, I swipe the page by implementing the HasTouchScreen method, prompting failure and error

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Last Appium version that did not exhibit the issue (if applicable):
* Mobile platform/version under test: Android
* Real device or emulator/simulator: 8.0
* Appium CLI or Appium.app|exe:

## Details
I want to use the TouchActions scroll method, but when I implemented the HasTouchScreen interface, the page did not swipe, but directly reported an error. When I was in java-clien 5.0.4 and selenium 3.5.2 version, I could swipe normally, but I could not swipe at java-client 6.1.0 selenium 3.12.0 ~ 3.14.0, and there was an error

error log：
org.openqa.selenium.UnsupportedCommandException: touchScroll

Driver info: driver.version: AndroidDriver

	at org.openqa.selenium.remote.http.AbstractHttpCommandCodec.encode(AbstractHttpCommandCodec.java:218)
	at org.openqa.selenium.remote.http.AbstractHttpCommandCodec.encode(AbstractHttpCommandCodec.java:117)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:152)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:231)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at io.appium.java_client.AppiumExecutionMethod.execute(AppiumExecutionMethod.java:46)
	at org.openqa.selenium.remote.RemoteTouchScreen.scroll(RemoteTouchScreen.java:64)
	at org.openqa.selenium.interactions.touch.ScrollAction.perform(ScrollAction.java:46)
	at org.openqa.selenium.interactions.CompositeAction.perform(CompositeAction.java:36)
	at org.openqa.selenium.interactions.Actions$BuiltAction.perform(Actions.java:633)
	at org.openqa.selenium.interactions.Actions.perform(Actions.java:594)
	at TestCase.beforeMethod(TestCase.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

## Link to Appium logs
Can be provided if needed

## Code To Reproduce Issue [ Good To Have ]
public class TestCase implements HasTouchScreen{
    //
    private RemoteWebDriver driver;
    RemoteTouchScreen touch;

    public TouchScreen getTouch() {
        return touch;
    }
    @Test
    public void beforeMethod() {
        try {
            DesiredCapabilities caps = new DesiredCapabilities();
            caps.setCapability(MobileCapabilityType.PLATFORM_NAME, "android");
            caps.setCapability(MobileCapabilityType.DEVICE_NAME, "xxxxxxx");
            caps.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, 600);
            caps.setCapability(AndroidMobileCapabilityType.NO_SIGN, true);
            caps.setCapability(AndroidMobileCapabilityType.UNICODE_KEYBOARD, true);
            caps.setCapability(AndroidMobileCapabilityType.RESET_KEYBOARD, true);
            caps.setCapability(AndroidMobileCapabilityType.BROWSER_NAME,"Chrome");
            caps.setCapability(MobileCapabilityType.NO_RESET, true);
            caps.setCapability(AndroidMobileCapabilityType.RECREATE_CHROME_DRIVER_SESSIONS, true);
            driver = new AndroidDriverChild(new URL("http://127.0.0.1:4723/wd/hub"), caps);
            driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        try {
            Thread.sleep(5000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        driver.get("http://www.sogou.com");
        try {
            Thread.sleep(5000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        TouchActions touchActions = new TouchActions(driver);
        touchActions.scroll(600, 1200).perform();

    }
}

**Comment by mykola-mokhnach** [comment]
The problem has nothing to do with the server. Please report to java client's tracker
