### ISSUE TITLE
Doesn't work with new version of react(0.57)

### ISSUE THREAD

**Issue by tevanovich** [appium/appium#11466]
## The problem

Just upgraded to react native version 0.57. and Appium server only tells me an http error 500

## Environment

* Appium version 1.7.1:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOs 10.13.6
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium.app

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by dpgraham** [comment]
Can you post the logs

**Comment by mykola-mokhnach** [comment]
Also appium 1.7.1 is very old. Please upgrade to the newest version first

**Comment by Virtim** [comment]
We're having the same issue with React Native 0.57.1 but Appium version is 1.9.1. When I'm trying to use appium inspector It looks like appium can't get page source at all. Also, when I'm using uiautomatorviewer it works just fine. It shows page source and element ids

<img width="748" alt="screen shot 2018-10-03 at 1 11 13 pm" src="https://user-images.githubusercontent.com/16343020/46436523-e11bd500-c70d-11e8-9ad8-e268708003c9.png">

Let me know if you need any additional info

**Comment by mykola-mokhnach** [comment]
This screenshot does not look like the full server log

**Comment by Virtim** [comment]
You're right, my bad: 
Server logs: 
[appiumlogs.txt](https://github.com/appium/appium/files/2443932/appiumlogs.txt)

Error while running steps on real device with browserstack and circleci: 
`Promise was rejected with the following reason: Appium error: An unknown server-side error occurred while processing the command. Original error: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
	at io.appium.uiautomator2.model.internal.CustomUiDevice.findObjects(CustomUiDevice.java:165)
	at io.appium.uiautomator2.handler.FindElements.findElements(FindElements.java:135)
	at io.appium.uiautomator2.handler.FindElements.safeHandle(FindElements.java:85)
	at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:56)
	at io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:202)
	at io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:193)
	at io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:44)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:466)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:764)`

**Comment by mykola-mokhnach** [comment]
Are you sure you use the recent Appium version? The log says 
`2018-10-03 21:19:46:644 - [Appium] Creating new AndroidUiautomator2Driver (v0.5.2) session
`

And the actual version of this component in recent appium version is above 1.15

**Comment by Virtim** [comment]
@mykola-mokhnach You were right. I guess it's browserstack using old uiautomator version as engine. I was using uiautomator2 as automationName in capabilities. Which was working fine until we updated react native. Once I changed automationName to Appium it started to work. Thank you!

Shame on me.
