### ISSUE TITLE
Fatal TypeError: Class constructor BaseDriver cannot be invoked without 'new' when starting appium CLI

### ISSUE THREAD

**Issue by seavan** [appium/appium#11477]
## The problem

Cannot run appium cli after upgrading to 1.9.1. Last version which worked fine is 1.8.1. When running from the command line, I get the error `Fatal TypeError: Class constructor BaseDriver cannot be invoked without 'new'` (see below for the full output).

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Last Appium version that did not exhibit the issue (if applicable): 1.8.1
* Desktop OS/version used to run Appium: macOS High Sierra
* Node.js version (unless using Appium.app|exe): 9.11.1
* Mobile platform/version under test: N/A
* Real device or emulator/simulator: N/A
* Appium CLI or Appium.app|exe: CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

```
seavan@mbpro2016 peerio-mobile $ ./node_modules/.bin/appium
[Appium] Welcome to Appium v1.9.1
Fatal TypeError: Class constructor BaseDriver cannot be invoked without 'new'
    at new AppiumDriver (/Users/seavan/Documents/peerio/peerio-mobile/node_modules/appium/lib/appium.js:131:19)
    at main$ (/Users/seavan/Documents/peerio/peerio-mobile/node_modules/appium/lib/main.js:124:16)
    at tryCatch (/Users/seavan/Documents/peerio/peerio-mobile/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/seavan/Documents/peerio/peerio-mobile/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/seavan/Documents/peerio/peerio-mobile/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/seavan/Documents/peerio/peerio-mobile/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
```

## Code To Reproduce Issue [ Good To Have ]

Run the appium on fresh install (CLI).

**Comment by mykola-mokhnach** [comment]
@imurchie @dpgraham any ideas?

**Comment by mykola-mokhnach** [comment]
I saw the similar error recently in https://travis-ci.org/appium/appium/jobs/436632855

**Comment by dpgraham** [comment]
Can you see if that error happens when you install it globally? It may not be respecting the shrinkwrap.

**Comment by KazuCocoa** [comment]
Yesterday, I faced the error. But today, I haven't met it yet after removing `build` and `node_modules` (build github appium repository directly), or uninstalling appium (build via `npm -g`). I assume something was broken in `build` or `node_modules` on my env...

I confirmed with node v8.9.4/ npm 5.6.0, node v9.11.1/npm 5.6.0 and  node v10.11.0/npm 6.4.1.

**Comment by svetikshark** [comment]
having the same issue after uninstall and install appium -g

**Comment by mykola-mokhnach** [comment]
I would assume this is happening because some modules have been already transitioned to babel7 and some other still use the old version of it. It should be fine after the transitioning is completed.

**Comment by KazuCocoa** [comment]
Current master, 1.9.2-beta, probably works fine since they are built by babel7.
https://github.com/appium/appium/releases/tag/v1.9.1 can build since the tag's version includes shrinkwrap.

But v `1.9.1@beta` probably happens this issue.

I'm not sure why `npm install -g appium@1.9.1` happens this issue...
`appium@1.9.1-beta2`should happen tough.

```
+ appium@1.9.1-beta2
added 70 packages, removed 8 packages and updated 25 packages in 31.87s
$ appium
[Appium] Welcome to Appium v1.9.1-beta2
Fatal TypeError: Class constructor BaseDriver cannot be invoked without 'new'
    at new AppiumDriver (/Users/kazu/.nodebrew/node/v9.11.1/lib/node_modules/appium/lib/appium.js:131:19)
    at main$ (/Users/kazu/.nodebrew/node/v9.11.1/lib/node_modules/appium/lib/main.js:124:16)
    at tryCatch (/Users/kazu/.nodebrew/node/v9.11.1/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/kazu/.nodebrew/node/v9.11.1/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/kazu/.nodebrew/node/v9.11.1/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/kazu/.nodebrew/node/v9.11.1/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
```

**Comment by svetikshark** [comment]
i've been installing with intall appium@beta - and it installed 1.9.2-beta.1 - can I install 1.9.2-beta with same command to try if issue is gone ?

**Comment by nenaddrop** [comment]
I've just installed appium using "npm install -g appium@1.9.2-beta.1" and I'm seeing this issue when I try to run it.

**Comment by KazuCocoa** [comment]
Maybe, we must publish new beta to apply https://github.com/appium/appium/pull/11461/files in beta for 1.9.2 beta

cc @imurchie

**Comment by imurchie** [comment]
Indeed, this has caught us in the middle of the process of upgrading our build internals. Appium `1.9.2-beta.2` is now published. Please install with `npm uninstall -g appium && npm install -g appium@beta`.

**Comment by seavan** [comment]
@imurchie @mykola-mokhnach 

confirming that 1.9.2-beta.2 works fine:

```
+ appium@1.9.2-beta.2
added 628 packages in 66.46s
seavan@mbpro2016 peerio-mobile $ appium
[Appium] Welcome to Appium v1.9.2-beta.2
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
```

**Comment by zyy7259** [comment]
I use `yarn global add appium@beta` to install the beta version, and all I got is `appium@1.9.2-beta.1`. These is no `1.9.2-beta.2`, and `1.9.2-beta.1` still has this problem.

**Comment by KazuCocoa** [comment]
I haven't used `yarn` for Appium, but if it can get a package following https://www.npmjs.com/package/appium , you can get `1.9.2-beta.2`.
