### ISSUE TITLE
Connection to WDA timed out, while trying to click

### ISSUE THREAD

**Issue by akhand-pratap2807** [appium/appium#11485]
**Problem**:

While trying to click the element which is on the screen, got error:
   Connection to WDA timed out and then Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Last Appium version that did not exhibit the issue (if applicable): 1.8.1
* Desktop OS/version used to run Appium: Mac 10.13.6 (17G65)/Xcode 10.0
* Node.js version (unless using Appium.app|exe):v10.6.0
* Mobile platform/version under test: iOS 12
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs: https://gist.github.com/akhand-pratap2807/11654f79b1e05ae23744343c6c0da97a

Code: 
private void  pressOption(WebElement ele) {
		MultiTouchAction multiTouch = new MultiTouchAction(mAppiumDriver);
		IOSTouchAction tap = new IOSTouchAction(mAppiumDriver);	
		multiTouch.add(tap.press(IOSPressOptions.iosPressOptions().withElement(ElementOption.element(ele)))
				.waitAction(WaitOptions.waitOptions(Duration.ofMillis(2000)))
				.release());
		multiTouch.perform();
	}

**Comment by akhand-pratap2807** [comment]
I have changed with below code:
IOSTouchAction action = new IOSTouchAction(mAppiumDriver);
		action.press(IOSPressOptions.iosPressOptions().withElement(ElementOption.element(ele))).waitAction(WaitOptions.waitOptions(Duration.ofMillis(2000)));
		action.release();
		action.perform();

Again in same trouble:
05 06:48:18:685 - [debug] [JSONWP Proxy] Proxying [POST /wda/touch/perform] to [POST http://localhost:8100/session/2B0B1474-DFDD-4818-B5F7-75339056AA32/wda/touch/perform] with body: {"actions":[{"action":"press","options":{"element":"13000000-0000-0000-9303-000000000000"}},{"action":"wait","options":{"ms":2000}},{"action":"release","options":{}}]}
2018-10-05 06:48:18:978 - [debug] [XCUITest] Connection to WDA timed out
2018-10-05 06:48:18:978 - [debug] [iProxy] recv failed: Operation not permitted
2018-10-05 06:48:18:987 - [debug] [W3C] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up
2018-10-05 06:48:18:987 - [debug] [W3C]     at JWProxy.command$ (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:238:13)
2018-10-05 06:48:18:987 - [debug] [W3C]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
2018-10-05 06:48:18:988 - [debug] [W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
2018-10-05 06:48:18:988 - [debug] [W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
2018-10-05 06:48:18:988 - [debug] [W3C]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)

**Comment by akhand-pratap2807** [comment]
@mykola-mokhnach Thanks in advance

**Comment by mykola-mokhnach** [comment]
Where is the device log?

**Comment by akhand-pratap2807** [comment]
Attached logs here: https://gist.github.com/akhand-pratap2807/11654f79b1e05ae23744343c6c0da97a

**Comment by mykola-mokhnach** [comment]
I don't observe any issues in the attached log.
Try to set `showIOSLog` cap to true

**Comment by akhand-pratap2807** [comment]
Hi @mykola-mokhnach 

Even launching the app through appium blocking me to proceed.
Log is here:
2018-10-08 04:53:09:103 - [debug] [XCUITest] WebDriverAgent information:
2018-10-08 04:53:09:103 - [debug] [XCUITest] {
2018-10-08 04:53:09:103 - [debug] [XCUITest]   "state": "success",
2018-10-08 04:53:09:103 - [debug] [XCUITest]   "os": {
2018-10-08 04:53:09:103 - [debug] [XCUITest]     "name": "iOS",
2018-10-08 04:53:09:104 - [debug] [XCUITest]     "version": "11.3.1",
2018-10-08 04:53:09:104 - [debug] [XCUITest]     "sdkVersion": "12.0"
2018-10-08 04:53:09:104 - [debug] [XCUITest]   },
2018-10-08 04:53:09:105 - [debug] [XCUITest]   "ios": {
2018-10-08 04:53:09:105 - [debug] [XCUITest]     "simulatorVersion": "11.3.1",
2018-10-08 04:53:09:105 - [debug] [XCUITest]     "ip": "192.168.2.16"
2018-10-08 04:53:09:105 - [debug] [XCUITest]   },
2018-10-08 04:53:09:106 - [debug] [XCUITest]   "build": {
2018-10-08 04:53:09:106 - [debug] [XCUITest]     "upgradedAt": "1538719821317",
2018-10-08 04:53:09:106 - [debug] [XCUITest]     "time": "Oct  5 2018 15:30:23",
2018-10-08 04:53:09:106 - [debug] [XCUITest]     "productBundleIdentifier": "com.facebook.WebDriverAgentRunner"
2018-10-08 04:53:09:106 - [debug] [XCUITest]   }
2018-10-08 04:53:09:106 - [debug] [XCUITest] }
2018-10-08 04:53:09:107 - [debug] [XCUITest] WebDriverAgent successfully started after 11878ms
2018-10-08 04:53:09:107 - [debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1538974389107 (10:23:09 GMT+0530 (India Standard Time))
2018-10-08 04:53:09:107 - [debug] [XCUITest] Sending createSession command to WDA
2018-10-08 04:53:09:108 - [debug] [JSONWP Proxy] Matched '/session' to command name 'createSession'
2018-10-08 04:53:09:109 - [debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.adobe.PSMobile","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
2018-10-08 04:53:17:208 - [debug] [XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up). Retrying...
2018-10-08 04:53:17:214 - [XCUITest] xcodebuild exited with code 'null' and signal 'SIGSEGV'
2018-10-08 04:53:18:211 - [debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1538974398211 (10:23:18 GMT+0530 (India Standard Time))
2018-10-08 04:53:18:211 - [debug] [XCUITest] Sending createSession command to WDA
2018-10-08 04:53:18:212 - [debug] [JSONWP Proxy] Matched '/session' to command name 'createSession'
2018-10-08 04:53:18:213 - [debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.adobe.PSMobile","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
2018-10-08 04:53:18:509 - [debug] [XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET). Retrying...
2018-10-08 04:53:19:510 - [debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1538974399510 (10:23:19 GMT+0530 (India Standard Time))
2018-10-08 04:53:19:511 - [debug] [XCUITest] Sending createSession command to WDA
2018-10-08 04:53:19:512 - [debug] [JSONWP Proxy] Matched '/session' to command name 'createSession'
2018-10-08 04:53:19:513 - [debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.adobe.PSMobile","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
2018-10-08 04:53:19:518 - [debug] [XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET). Retrying...
2018-10-08 04:53:20:522 - [debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1538974400521 (10:23:20 GMT+0530 (India Standard Time))
2018-10-08 04:53:20:522 - [debug] [XCUITest] Sending createSession command to WDA
2018-10-08 04:53:20:522 - [debug] [JSONWP Proxy] Matched '/session' to command name 'createSession'
2018-10-08 04:53:20:522 - [debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.adobe.PSMobile","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
2018-10-08 04:53:21:364 - [debug] [XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET). Retrying...
2018-10-08 04:53:22:368 - [debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1538974402368 (10:23:22 GMT+0530 (India Standard Time))
2018-10-08 04:53:22:368 - [debug] [XCUITest] Sending createSession command to WDA

**Comment by mykola-mokhnach** [comment]
The log above contains no useful information for debugging

**Comment by akhand-pratap2807** [comment]
Ohk. Sorry about that.

Could you please guide me which is the right way to click on an element which is present on screen?

Way1:
IOSTouchAction action = new IOSTouchAction(mAppiumDriver);
action.press(IOSPressOptions.iosPressOptions().withElement(ElementOption.element(ele))).waitAction(WaitOptions.waitOptions(Duration.ofMillis(2000)));
action.release();
action.perform();

Way2:
WebElement ele = findElementUsingAccessibilityID(accessibilityID);
ele.click();

I am asking because I am seeing this two methods are not completely 100% working. Sometimes way-1 works and another time way-2 gives the expected result.

**Comment by mykola-mokhnach** [comment]
Connection timed out means that WebDriverAgent is terminated unexpectedly. This might happen due to multiple reasons and it is not possible to figure out which one without the detailed device log.

**Comment by akhand-pratap2807** [comment]
Sure, I will try to give you complete log.
Meanwhile, can you assist me here for below question?

What is the right way to click on an element which is present on screen?

Way1:
IOSTouchAction action = new IOSTouchAction(mAppiumDriver);
action.press(IOSPressOptions.iosPressOptions().withElement(ElementOption.element(ele))).waitAction(WaitOptions.waitOptions(Duration.ofMillis(2000)));
action.release();
action.perform();

Way2:
WebElement ele = findElementUsingAccessibilityID(accessibilityID);
ele.click();

I am asking because I am seeing this two methods are not completely 100% working. Sometimes way-1 works and another time way-2 gives the expected result.

**Comment by mykola-mokhnach** [comment]
Kindly use appium forum for questions. Here is the place for issues

**Comment by hqfking** [comment]
it seems that the issue with the click method. I am facing the same issue but only when calling the click method on a MobileElement.   use TouchAction to perform the tap works fine.

**Comment by akhand-pratap2807** [comment]
@hqfking How are you using touch action?
Because I am getting the error in both ways

**Comment by hqfking** [comment]
After I upgrade to Xcode 10, even click method is working for me. 

I am using touchAction as:
TouchAction(driver).tap(point(mobileElement.getLocation().getX() + 2, mobileElement.getLocation().getY() + 2)).perform()

**Comment by mykola-mokhnach** [comment]
I'm going to close the issue if no device log is available
