### ISSUE TITLE
用java-client6.1版本的setClipboardText和getClipboardText方法出错

### ISSUE THREAD

**Issue by sun-jing-tao** [appium/appium#11495]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by sun-jing-tao** [comment]
环境：java-client6.1  appium1.9.1
调用setClipboardText和getClipboardText提示
如下错误:
信息: HTTP Status: '404' -> incorrect JSON status mapping for 'unknown method' (405 expected)
Exception in thread "main" org.openqa.selenium.UnsupportedCommandException: Method has not yet been implemented
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'FN7IG561WJGGJE9', ip: '192.168.199.171', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_171'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {appActivity: com.youdao.note.activity2.S..., appPackage: com.youdao.note, automationName: Appium, databaseEnabled: false, desired: {appActivity: com.youdao.note.activity2.S..., appPackage: com.youdao.note, automationName: Appium, deviceName: 127.0.0.1:62001, newCommandTimeout: 24000, noReset: true, platformName: android, resetKeyboard: true, unicodeKeyboard: true}, deviceManufacturer: OPPO, deviceModel: OPPO R11, deviceName: 127.0.0.1:62001, deviceScreenSize: 1280x720, deviceUDID: 127.0.0.1:62001, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, newCommandTimeout: 24000, noReset: true, platform: LINUX, platformName: Android, platformVersion: 5.1.1, resetKeyboard: true, takesScreenshot: true, unicodeKeyboard: true, warnings: {}, webStorageEnabled: false}
Session ID: a432513c-f818-4a5e-a66a-ef42877ce0a6
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:231)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at io.appium.java_client.CommandExecutionHelper.execute(CommandExecutionHelper.java:27)
	at io.appium.java_client.clipboard.HasClipboard.setClipboard(HasClipboard.java:42)
	at io.appium.java_client.clipboard.HasClipboard.setClipboardText(HasClipboard.java:63)
	at com.test.YoudaoTest_old.main(YoudaoTest_old.java:45)
希望能尽快帮我解决，谢谢！

**Comment by saikrishna321** [comment]
This works only with UIAutomator2
