### ISSUE TITLE
Appium cannot find element on MacOS Mojave 

### ISSUE THREAD

**Issue by yeugeneu** [appium/appium#11491]
## The problem
Appium cannot find element on MacOS Mojave 

## Environment

* Appium version (or git revision) that exhibits the issue: Tried both v1.7 and v1.9.1
* Desktop OS/version used to run Appium: MacOS Mojave
* Mobile platform/version under test: iOS 11.4
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium.app

## Details
Unable to find elements. Also confirmed using Appium desktop tracker that the element can be found, but when trying to send 'Click()' event it does not click on the element. Using Tap By Coordinate and found out clicking on the coordinate about 50 pixel above the original target position will work.

The image shows the red square area will trigger NEXT button.
<img width="278" alt="screen shot 2018-10-05 at 12 12 25 pm" src="https://user-images.githubusercontent.com/1661795/46555413-12c0a780-c898-11e8-844f-8ce642ae4f80.png">

```
org.openqa.selenium.NoSuchElementException: Can't locate an element by this strategy: By.id: input_login_email

	at io.appium.java_client.pagefactory.AppiumElementLocator.findElement(AppiumElementLocator.java:102)
	at io.appium.java_client.pagefactory.interceptors.InterceptorOfASingleElement.intercept(InterceptorOfASingleElement.java:61)
	at io.appium.java_client.ios.IOSElement$$EnhancerByCGLIB$$d311658.click(<generated>)
	at util.InputMethods.fill(InputMethods.java:47)
	at controller.authentication.LoginVC.fill(LoginVC.java:61)
	at controller.authentication.LoginVC.login(LoginVC.java:31)
	at test.authentication.LoginVT.login(LoginVT.java:14)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1204)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
Caused by: org.openqa.selenium.TimeoutException: Expected condition failed: waiting for io.appium.java_client.pagefactory.AppiumElementLocator$WaitingFunction@4070ace9 (tried for 10 second(s) with 500 milliseconds interval)
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'EUGENE-MAC', ip: 'fe80:0:0:0:434:ee09:a4f9:302a%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14', java.version: '10.0.1'
Driver info: driver.version: unknown
	at org.openqa.selenium.support.ui.FluentWait.timeoutException(FluentWait.java:303)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:271)
	at io.appium.java_client.pagefactory.AppiumElementLocator.waitFor(AppiumElementLocator.java:76)
	at io.appium.java_client.pagefactory.AppiumElementLocator.findElement(AppiumElementLocator.java:95)
	... 31 more
```

## Link to Appium logs
[Appium Log](https://gist.github.com/yeugeneu/43eb54f7d5e4e964fbf1c5769e67de6b)

**Comment by yeugeneu** [comment]
> > [debug] [XCUITest] Executing command 'findElement'
> > [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
> > [debug] [W3C] Encountered internal error running command: InvalidSelectorError: Locator Strategy 'css selector' is not supported for this session
> 
> This must be a client issue. Make sure it is up to date

Updated the java-client to 6.1.0
Elements can be found now, but the automation is still interacting with the incorrect elements with incorrect y-axis location. 

Similar things happened in the desktop inspector. See attached image. The text meant to be entered into Email field using testNG annotaion @FindBy(id = "input_login_email") ended entering into the Password field 
<img width="1231" alt="screen shot 2018-10-05 at 10 36 16 pm" src="https://user-images.githubusercontent.com/1661795/46567825-23e8d300-c8ef-11e8-815c-26097de9dd52.png">

**Comment by mykola-mokhnach** [comment]
If this is a web view then you must not work with it in native context.

**Comment by yeugeneu** [comment]
> If this is a web view then you must not work with it in native context.

Both Email and Password textfields are class of SkyFloatingLabelTextField :UITextField in iOS.
Both lives under a UIStackView class.

I also verified using other apps such as Strava that the keypress and click action will interact with target element at the wrong location (a bit lower then the actual element is located at)

**Comment by yeugeneu** [comment]
I was experimenting with a simple view with only text fields on the view. Similar behaviour is observed that non of the "tap", "send keys", and "clear" action works on the selected element 'txtEmail'. Using Tap by coordinate at the red rectangle location will actually tap into the Email textfield.

<img width="1306" alt="screen shot 2018-10-06 at 12 12 35 am" src="https://user-images.githubusercontent.com/1661795/46568632-e25f2480-c8fc-11e8-865d-d7c24439e212.png">

**Comment by mykola-mokhnach** [comment]
The actual element coordinates are retrieved by XCTest. Please report the problem to https://github.com/facebook/WebDriverAgent as there is nothing to do there on appium side.
