### ISSUE TITLE
Failed to take screenshots in iOS 10 real devices (appium@v1.9.2-beta.2 )

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium#11501]
## The problem

After applying https://github.com/appium/WebDriverAgent/commit/ac44bd8c5d514732c32064194d179df92fc9f1ff , taking screenshots started failing in iOS 10 real devices.

After reverting the PR from https://github.com/appium/WebDriverAgent/commit/dea0ca8b823d6d8ac424ec8071df04488d367e93, it worked fine.
(the reverted branch=> https://github.com/KazuCocoa/WebDriverAgent/tree/km/revert-upstream, log: https://github.com/Magic-Pod/AppiumRegressionCheck/issues/22#issuecomment-428024555)

## Environment

* Appium version (or git revision) that exhibits the issue: appium@v1.9.2-beta.2
* Last Appium version that did not exhibit the issue (if applicable): 1.9.1
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe): v10.11.0
* Mobile platform/version under test: iOS 
* Real device or emulator/simulator: Real devices (iOS 10.3.3)
* Appium CLI or Appium.app|exe:

## Details

I ensured it worked fine in iOS 12 real devices and iOS 10 simulators. It probably happens only iOS 10 real devices. It happened both Xcode 9.4 and 10. I've already ensured it could reproduce after restarting real devices.

Logs about appium server and WDA when the issue happened: https://github.com/Magic-Pod/AppiumRegressionCheck/issues/22#issuecomment-427617888
I could see below lines in WDA log. I assumed WDA failed to capture screenshots.

```
10:12:00.091 WebDriverAgentRunner-Runner[222:5887] <XCTWaiter: 0x17748f70, state: XCTWaiterStateSucceeded> cleaning up `Request screenshot`
10:12:00.091 WebDriverAgentRunner-Runner[222:5887] Using legacy screenshot path, clipping image to rect {{0.0, 0.0}, {0.0, 320.0}} (scale 2.000000.1, scaled rect {{0.0, 0.0}, {0.0, 640.0}})
2018-10-07 10:12:00.099709+0900 WebDriverAgentRunner-Runner[222:5887] CGImageCreateWithImageProvider: invalid image size: 0 x 0.
Oct  7 10:12:00  WebDriverAgentRunner-Runner[222] <Error>: CGImageCreateWithImageProvider: invalid image size: 0 x 0.
10:12:00.115 xcodebuild[42728:1892799] 📱<DVTiOSDevice (0x7f818eac20b0), NozomiのiPhone, iPhone, 10.3.3 (14G60), a6b3c05b59692bcbd088d2126a55c860983ae9a3> ############## DID EXECUTE #################
```

- server log
```
018-10-07 10:12:00:130 - warn: [XCUITest] Error getting screenshot through 'idevicescreenshot': An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET
2018-10-07 10:12:00:130 - info: [debug] [XCUITest] Taking screenshot with WDA
2018-10-07 10:12:00:131 - info: [debug] [JSONWP Proxy] Matched '/screenshot' to command name 'getScreenshot'
2018-10-07 10:12:00:131 - info: [debug] [JSONWP Proxy] Proxying [GET /screenshot] to [GET http://localhost:8101/session/A8CCB82B-7647-41A6-87B6-C291ADDE4A82/screenshot] with no body
2018-10-07 10:12:00:136 - info: [debug] [iProxy] Error connecting to device!
2018-10-07 10:12:00:137 - warn: [JSONWP Proxy] Got an unexpected response: {"code":"ECONNRESET","errno":"ECONNRESET","syscall":"read"}
2018-10-07 10:12:01:138 - info: [debug] [XCUITest] Taking screenshot with WDA
2018-10-07 10:12:01:139 - info: [debug] [JSONWP Proxy] Matched '/screenshot' to command name 'getScreenshot'
2018-10-07 10:12:01:140 - info: [debug] [JSONWP Proxy] Proxying [GET /screenshot] to [GET http://localhost:8101/session/A8CCB82B-7647-41A6-87B6-C291ADDE4A82/screenshot] with no body
2018-10-07 10:12:01:146 - info: [debug] [iProxy] Error connecting to device!
2018-10-07 10:12:01:147 - warn: [JSONWP Proxy] Got an unexpected response: {"code":"ECONNRESET","errno":"ECONNRESET","syscall":"read"}
2018-10-07 10:12:01:157 - info: [debug] [MJSONWP (40da5ccd)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET
2018-10-07 10:12:01:158 - info: [debug] [MJSONWP (40da5ccd)]     at /Users/itonozomi/.nodebrew/node/v8.11.3/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:236:13
2018-10-07 10:12:01:158 - info: [debug] [MJSONWP (40da5ccd)]     at Generator.throw (<anonymous>)
2018-10-07 10:12:01:158 - info: [debug] [MJSONWP (40da5ccd)]     at asyncGeneratorStep (/Users/itonozomi/.nodebrew/node/v8.11.3/lib/node_modules/appium/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
2018-10-07 10:12:01:158 - info: [debug] [MJSONWP (40da5ccd)]     at _throw (/Users/itonozomi/.nodebrew/node/v8.11.3/lib/node_modules/appium/node_modules/@babel/runtime/helpers/asyncToGenerator.js:29:9)
2018-10-07 10:12:01:158 - info: [debug] [MJSONWP (40da5ccd)]     at <anonymous>
2018-10-07 10:12:01:160 - info: [HTTP] <-- GET /wd/hub/session/40da5ccd-dd6f-402b-9551-2787fd4b8e7e/screenshot 500 1579 ms - 251
2018-10-07 10:12:01:160 - info: [HTTP] 
```

I haven't confirmed the details yet.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Taking screenshots in real devices (iOS10)

**Comment by mykola-mokhnach** [comment]
This must be dropped sooner or later. I would assume iOS10 contains the SDK based on Xcode8, which we son't support anymore. You should use older appium version for it. Also, as far as I remember, there is a capability, that switches screenshooting to idevicescreenshot utility.

**Comment by KazuCocoa** [comment]
Ah. right.
I thought Xcode 9 includes iOS 10.3. (But it's my bad..)

I suggested idevicescreenshot but he told me it raised an error. I'll take a look at it later
