### ISSUE TITLE
Appium 1.9.1 giving me "An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET"

### ISSUE THREAD

**Issue by deepakg4all** [appium/appium#11538]
## The problem
Upgraded my appium from 1.7.1 to 1.9.1 and noticed that Android version 7.1.1 giving me an error  "An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET".

## Environment
Appium - 1.9.1
OS - Window 10
Robot Framework : Version:  3.0.2 (Python 2.7.13 on win32)
Android OS: 1.7.1
Emulator - Yes 
Appium CLI

## Details
With appium 1.7.1 it's working properly on Android 7.1.1 and Android 9. However, after upgrade it's working smoothly on Android 9 but not on 1.7.1.

## Link to Appium logs

![image](https://user-images.githubusercontent.com/13413519/47078159-48fb1100-d220-11e8-8583-d5df6abfde7b.png)

**Comment by mykola-mokhnach** [comment]
ECONNRESET means the server is unexpectedly terminated on the device. Please attach the full server log and the logcat output.

**Comment by lamquangthanh** [comment]
hello @deepakg4all 
try to remove 2 file: **io.appium.uiautomator2.server** and **io.appium.uiautomator2.server.test** in _Settings of devices-Application_ and run again. Hope it helped you.

**Comment by SelvakumarAnnamalaisamy** [comment]
Hi,
Same issue I am seeing it on iOS devices ranging from 11.4.1 to 12.0.1. Is there any workaround to solve this issue?

**Comment by deepakg4all** [comment]
Thanks @mykola-mokhnach  @lamquangthanh for your reply. Well, to diagnosed in detail, I have downgraded my appium version to 1.7.1 and then again upgraded back to 1.9.1 and also restarted all emulators. After this, issue is fixed. It working like a charm.  It might env issue, if it raise again this will reopen this ticket.

**Comment by SelvakumarAnnamalaisamy** [comment]
@deepakg4all yes you are right. I uninstalled Appium completely and re-installed Appium 1.9.1, also I had multiple Xcode version in my machine. Now I removed all Xcode older version and have only Xcode 10 alone.

Problem gets solved. Thanks.

**Comment by YGQ8988** [comment]
You should exit after ending a use case file。
like
`cls.driver.quit()`
or
`self.driver.quit()`

**Comment by Suban5** [comment]
This works for me:

  ```
  adb uninstall io.appium.uiautomator2.server
  adb uninstall io.appium.uiautomator2.server.test
  adb uninstall io.appium.unlock
  adb uninstall io.appium.settings
```

**Comment by SuryakiranP** [comment]
Hi,
currently, i am facing issue like
An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET

**Comment by SuryakiranP** [comment]
Please, can anyone kindly provide a solution

**Comment by SuryakiranP** [comment]
![Capture78998](https://user-images.githubusercontent.com/51612593/60441788-639dda80-9c35-11e9-8d49-f059411b0a28.PNG)

**Comment by SuryakiranP** [comment]
I have resolved the issue by re-installing Appium.

**Comment by adityabhargav** [comment]
appium Version :- 1.12 and 1.13.0
Xcode Version   :- 10.3
{
  "deviceName": "iPhone 8",
  "platformName": "IOS",
  "app": "/Users/aditya.pathivada/Desktop/TestingBotSampleApp.app",
  "udid": "707BD3C5-44A3-43E9-9396-AED9E1B9E0F9",
  "automationName": "XCUITest",
  "platformVersion": "12.1"
}

getting as An unknown server-side error occurred while processing the command. in the logs

**Comment by Bashimgeldi** [comment]
Facing sam issue with the latest appium

**Comment by coolvasanth** [comment]
Facing same issue, I think it is because  of the proxy issues of my office. They are ready to help me in all ways, but even they are unsure how to fix it.  Can anyone help me ? I have tried everything suggested above, nothing worked.

**Comment by wirahitaputramas** [comment]
Hello guys, I have faced the same problem, but now I just find the reason & also the solution. I realized that the error occurred when I made a test case that contains both "close server session" & "open new server session" command. I Think when running that kind of test case, the two different appium sessions overlap with each other, and then the error occurred. So my solution to this problem was very simple because I just separate "close server session" & "open new server session" command into two different test case, and then boom, the error has not occurred until now

**Comment by Jitu1888** [comment]
@wirahitaputramas Can you please tell me in more details how you resolve it.

**Comment by barnie-xero** [comment]
Hi all, I am experiencing this only in my Bitrise agents, doesn't happen on my local. Any help would be much appreciated. 
**[0-0] 2021-03-18T23:57:11.295Z INFO webdriver: COMMAND closeApp()
2021-03-18T23:57:11.295Z INFO webdriver: [POST] http://localhost:4723/session/301222d7-c727-495d-ba4a-8775f4bc6450/appium/app/close
[0-0] 2021-03-18T23:57:12.530Z INFO webdriver: COMMAND deleteSession()
[0-0] 2021-03-18T23:57:12.530Z INFO webdriver: [DELETE] http://localhost:4723/session/301222d7-c727-495d-ba4a-8775f4bc6450
[0-0] 2021-03-18T23:57:13.749Z WARN webdriver: Request failed with status 500 due to An unknown server-side error occurred while processing the command. Original error: _appiumSupport.logger.warn is not a function
[0-0] 2021-03-18T23:57:13.749Z INFO webdriver: Retrying 1/1
[0-0] 2021-03-18T23:57:13.749Z INFO webdriver: [DELETE] http://localhost:4723/session/301222d7-c727-495d-ba4a-8775f4bc6450
[0-0] 2021-03-18T23:57:13.798Z ERROR webdriver: Request failed with status 404 due to invalid session id: A session is either terminated or not started
[0-0] 2021-03-18T23:57:13.801Z ERROR @wdio/local-runner: Failed launching test session: invalid session id: A session is either terminated or not started
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Runner.endSession (/Users/vagrant/git/node_modules/@wdio/runner/build/index.js:192:30)
    at Runner.run (/Users/vagrant/git/node_modules/@wdio/runner/build/index.js:98:24)**

**Comment by haiya512** [comment]
> adb uninstall io.appium.uiautomator2.server
> adb uninstall io.appium.uiautomator2.server.test
> adb uninstall io.appium.unlock
> adb uninstall io.appium.settings

not work for me, i tried it

**Comment by surbhi-sanchita** [comment]
Hi Everyone, 

when i am running below code piece .. when i want to start the server for calculator app in android device..

import io.appium.java_client.android.AndroidDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import java.net.MalformedURLException;
import java.net.URL;


public class Clone {


    public AndroidDriver driver;

    @BeforeMethod
    public void setUp() throws MalformedURLException {


        String appiumServerURL = "http://127.0.0.1:4723/wd/hub";
        DesiredCapabilities dc =new DesiredCapabilities();
        dc.setCapability("deviceName","Huwaei Nova 3i");
        dc.setCapability("udid","JUC7N18710010424");
        dc.setCapability("platformName","Android");
        dc.setCapability("platformVersion","9");
        dc.setCapability("appPackage","com.android.calculator2");
        dc.setCapability("appActivity","com.android.calculator2.Calculator");

        System.out.println("Before Method executed.");
        driver= new AndroidDriver(new URL(appiumServerURL), dc);
    }

    @Test
    public void test()
    {
        int a=5;
        int b=10;
        System.out.println("Test");

    }

    @AfterMethod
    public void tearDown() {
        System.out.println("After Method executed");
    }
}


OUTPUT:


org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: An unknown server-side error occurred while processing the command. Original error: Could not find 'adb.exe' in ["C:\\Users\\surbhi.sanchita\\Desktop\\Android-Sdk\\platform-tools\\adb.exe","C:\\Users\\surbhi.sanchita\\Desktop\\Android-Sdk\\emulator\\adb.exe","C:\\Users\\surbhi.sanchita\\Desktop\\Android-Sdk\\cmdline-tools\\latest\\bin\\adb.exe","C:\\Users\\surbhi.sanchita\\Desktop\\Android-Sdk\\tools\\adb.exe","C:\\Users\\surbhi.sanchita\\Desktop\\Android-Sdk\\tools\\bin\\adb.exe","C:\\Users\\surbhi.sanchita\\Desktop\\Android-Sdk\\adb.exe"]. Do you have Android Build Tools installed at 'C:\Users\surbhi.sanchita\Desktop\Android-Sdk'?
Build info: version: '4.2.2', revision: '683ccb65d6'
System info: host: 'INC01079', ip: '192.168.29.152', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.15.1'
Driver info: io.appium.java_client.android.AndroidDriver
Command: [null, newSession {capabilities=[{appium:appActivity=com.android.calculator2.Calculator, appium:appPackage=com.android.calculator2, appium:deviceName=Huwaei Nova 3i, platformName=ANDROID, appium:platformVersion=9, appium:udid=JUC7N18710010424}], desiredCapabilities=Capabilities {appActivity: com.android.calculator2.Cal..., appPackage: com.android.calculator2, deviceName: Huwaei Nova 3i, platformName: ANDROID, platformVersion: 9, udid: JUC7N18710010424}}]
Capabilities {}

	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:144)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.appium.java_client.remote.AppiumProtocolHandshake.createSession(AppiumProtocolHandshake.java:126)
	at io.appium.java_client.remote.AppiumProtocolHandshake.createSession(AppiumProtocolHandshake.java:102)
	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:146)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:180)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:588)
	at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:224)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:184)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:79)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:87)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:116)
	at Clone.setUp(Clone.java:30)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296)
	at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:816)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:590)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.testng.TestRunner.privateRun(TestRunner.java:806)
	at org.testng.TestRunner.run(TestRunner.java:601)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
	at org.testng.SuiteRunner.run(SuiteRunner.java:330)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
	at org.testng.TestNG.runSuites(TestNG.java:1099)
	at org.testng.TestNG.run(TestNG.java:1067)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)



Please help me with this error :
Thanks in advance :-)

**Comment by Yasithe03** [comment]
<img width="1392" alt="Screenshot 2023-03-31 at 7 14 18 AM" src="https://user-images.githubusercontent.com/128848230/229002239-f7c0bf19-1c74-4697-852d-9ad8691f4faf.png">

Hi, im getting this when im trying to run appium inspector. would be glad if anyone can help me with this.
{
  "appium:deviceName": "Pixel XL API 30",
  "appium:platformVersion": "11",
  "appium:platformName": "Android",
  "appium:appPackage": "com.microimage.hcmv3",
  "appium:appActivity": ".auth.ui.activity.LoginActivity",
  "appium:automationName": "Appium",
  "appium:ignoreHiddenApiPolicyError": "true",
  "appium:appWaitForLaunch": "false",
  "appium:noReset": "true"
}

**Comment by farzane-shafiee** [comment]
{
  "platformName": "Android",
  "appium:platformVersion": "10",
  "appium:deviceName": "emulator-5554",
  "appium:app": "/home/farzaneh/Android/linkedin.apk",
  "appium:appPackage": "com.linkedin.android",
  "appium:appWaitForLaunch": false,
  "appium:automationName": "Appium",
  "appium:ignoreHiddenApiPolicyError": false,
  "appium:noReset": false
}

when run appium for test mobile app, often show this bug and often run correct.

bug is: 

UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.linkedin.android' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: 'com.linkedin.android.authenticator.LaunchActivity' or 'com.linkedin.android.com.linkedin.android.authenticator.LaunchActivity' never started. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting

**Comment by Sivasakthijio** [comment]
I'm also facing the same problem but other application is working fine. Only when i'm using the my project .apk apps cannot launch
