### ISSUE TITLE
Could not detect Mac OS X Version from sw_vers output: '10.14 '

### ISSUE THREAD

**Issue by seregajoys** [appium/appium#11530]
I update my mac to new 10.14 Mojave and i have the problem
How to resolve this issue?
info AppiumDoctor Appium Doctor v.1.4.3
info AppiumDoctor ### Diagnostic starting ###
info AppiumDoctor  ✔ The Node.js binary was found at: /usr/local/bin/node
info AppiumDoctor  ✔ Node version is 10.12.0
info AppiumDoctor  ✔ Xcode is installed at: /Applications/Xcode.app/Contents/Developer
Error: Could not detect Mac OS X Version from sw_vers output: '10.14'
    at Object.macOsxVersion$ (/usr/local/lib/node_modules/appium-doctor/node_modules/appium-support/lib/system.js:43:11)
    at tryCatch (/usr/local/lib/node_modules/appium-doctor/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium-doctor/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium-doctor/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium-doctor/node_modules/babel-runtime/regenerator/runtime.js:136:37)

**Comment by mykola-mokhnach** [comment]
This is fixed in appium@beta. Closed as duplicate
