### ISSUE TITLE
Appium - Android - Failed to instantiate new session in remote machine through Team city

### ISSUE THREAD

**Issue by kumarsplendid** [appium/appium#11547]
## The problem

When we execute our Android test suite through Teamcity, most of the tests fail with the below error. 40 to 50% of the tests will fail and remain will pass.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: Mac OS
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android 
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

## Error

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'android' defined in com.hm.apps.base.driverConfigurations.ConfigurationDriver: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.openqa.selenium.WebDriver]: Factory method 'android' threw exception; nested exception is org.openqa.selenium.WebDriverException: java.io.IOException: unexpected end of stream on Connection{semac2843:4723, proxy=DIRECT hostAddress=semac2843/10.60.242.121:4723 cipherSuite=none protocol=http/1.1}
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
System info: host: 'SRV15324', ip: '10.64.241.159', os.name: 'Windows Server 2016', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_172'
Driver info: driver.version: ConfigurationDriver
    at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:227)
    at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:212)
    at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
    at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
    at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
    at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
    at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
    at okhttp3.RealCall.execute(RealCall.java:77)
    at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:101)
    at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:101)
    at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
    at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
    at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:129)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
    at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
    at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
    at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
    at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:209)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:132)
    at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)
    at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:84)
    at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:94)
    at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:80)
    at com.hm.apps.base.driverConfigurations.ConfigurationDriver.android(ConfigurationDriver.java:42)
    at com.hm.apps.base.driverConfigurations.ConfigurationDriver$$EnhancerBySpringCGLIB$$570f5cc7.CGLIB$android$0(<generated>)
    at com.hm.apps.base.driverConfigurations.ConfigurationDriver$$EnhancerBySpringCGLIB$$570f5cc7$$FastClassBySpringCGLIB$$a70cd9c1.invoke(<generated>)
    at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
    at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:309)
    at com.hm.apps.base.driverConfigurations.ConfigurationDriver$$EnhancerBySpringCGLIB$$570f5cc7.android(<generated>)
    at sun.reflect.GeneratedMethodAccessor97.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
    at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1119)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1014)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:504)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:204)
    at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:974)
    at com.hm.apps.base.driverConfigurations.DriverManager.createDriver(DriverManager.java:51)
    at com.hm.apps.base.testBase.AppTestNGBase.initSession(AppTestNGBase.java:90)
    at com.hm.apps.android.tests.smokeTests.CustomerLoyaltyTests.setUp(CustomerLoyaltyTests.java:54)
------- Stdout: -------
08:50:14,907  INFO NewsLetterTest:75 - Surefire test ended.
08:50:14,929  INFO CustomerLoyaltyTests:58 - Starting Test: Surefire test
09:00:14,981 ERROR AppScreenshotHTMLReporter:130 - error generating screenshot: io.appium.java_client.NoSuchContextException: A session is either terminated or not started (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
System info: host: 'SRV15324', ip: '10.64.241.159', os.name: 'Windows Server 2016', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_172'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {app: /Users/testrays/NightlyBuil..., appActivity: .preview.PreviewLauncherAct..., appPackage: com.hm, appWaitActivity: .app.MainActivity,.features..., appWaitDuration: 500000, autoGrantPermissions: true, browserName: android, databaseEnabled: false, desired: {app: /Users/testrays/NightlyBuil..., appActivity: .preview.PreviewLauncherAct..., appPackage: com.hm, appWaitActivity: .app.MainActivity,.features..., appWaitDuration: 500000, autoGrantPermissions: true, browserName: android, deviceName: Galaxy S5, newCommandTimeout: 10000, optionalIntentArguments:  --es com.hm.preview.EXTRA_..., platformName: android, platformVersion: 6.0.1, resetKeyboard: true, unicodeKeyboard: true}, deviceManufacturer: samsung, deviceModel: SM-G900F, deviceName: dceb0604, deviceScreenSize: 1080x1920, deviceUDID: dceb0604, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, newCommandTimeout: 10000, optionalIntentArguments:  --es com.hm.preview.EXTRA_..., platform: LINUX, platformName: LINUX, platformVersion: 6.0.1, resetKeyboard: true, takesScreenshot: true, unicodeKeyboard: true, warnings: {}, webStorageEnabled: false}
Session ID: 2bee20aa-4bbe-44fb-ac7d-caefdf0e94a8

**Comment by kumarsplendid** [comment]
Any help would be really appreciated

**Comment by mykola-mokhnach** [comment]
1. Please attach the full server log
2. Appium 1.7.1 is outdated. Please upgrade to the most recent version
