### ISSUE TITLE
[1.9.1] org.openqa.selenium.NoSuchSessionException: A session is either terminated or not started

### ISSUE THREAD

**Issue by swekum** [appium/appium#11579]
## The problem

Getting below exception while running scripts on Android real devices for long run.

org.openqa.selenium.NoSuchSessionException: A session is either terminated or not started (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 4 milliseconds
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'Shwetas-MacBook-Pro.local', ip: 'fe80:0:0:0:cf3:19cf:fb02:4a53%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14', java.version: '1.8.0_152'
Driver info: io.appium.java_client.android.AndroidDriver

Appium Logs 
2018-10-26 10:48:24:819 - error: [UiAutomator] UiAutomator exited unexpectedly with code 0, signal null
2018-10-26 10:48:24:832 - warn: [Appium] Closing session, cause was 'UiAUtomator shut down unexpectedly'
2018-10-26 10:48:24:833 - info: [Appium] Removing session 2dd5e104-3d88-4bf1-af2d-54d328e15edc from our master session list
2018-10-26 10:48:25:027 - info: [HTTP] --> POST /wd/hub/session/2dd5e104-3d88-4bf1-af2d-54d328e15edc/element
2018-10-26 10:48:25:041 - info: [HTTP] <-- POST /wd/hub/session/2dd5e104-3d88-4bf1-af2d-54d328e15edc/element 404 13 ms - 131
2018-10-26 10:48:25:041 - info: [HTTP] 
2018-10-26 10:48:25:043 - info: [HTTP] --> POST /wd/hub/session/2dd5e104-3d88-4bf1-af2d-54d328e15edc/timeouts

## Environment

* Appium version (or git revision) that exhibits the issue:1.9.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS 10.14
* Node.js version (unless using Appium.app|exe):v 9.3.0
* Mobile platform/version under test: Android [4.4.2 - 9.0]
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI 

## Details
 On triggering scripts on devices with OS from 4.4.2 to 9.0 , after some time start getting this exception and nothing executes after that.

## Link to Appium logs

https://gist.github.com/swekum/e148b92c499bd3b6b943ef0f0799e475

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Makes sure you use UiAutomator2 for Android 6+

**Comment by mykola-mokhnach** [comment]
Also the client should be up to date. I observe you have selenium API at 3.4.0, which is very old

**Comment by swekum** [comment]
Could you help me out with below issues 

1. If I update it to UiAutomator2 and want to run regression cycle for devices with OS 4.4.2 , what can be the alternative , because after updating , below is the error I get.

2018-10-29 09:35:51:725 - error: [UiAutomator2] Error: UIAutomation2 is only supported since Android 5.0 (Lollipop). You could still use other supported backends in order to automate older Android versions.
2018-10-29 09:35:51:725 - error: [UiAutomator2]     at Object.wrappedLogger.errorAndThrow (/usr/local/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)


----------------------------------------------- 
2. I tried updating the java-client as well to 6.0.0-BETA5 version (Had to update the deprecated functions) , I am getting the below error 

org.openqa.selenium.WebDriverException: Connection refused (Connection refused)
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14', java.version: '1.8.0_152'
Driver info: driver.version: AndroidDriver
	at io.appium.java_client.remote.AppiumCommandExecutor.lambda$2(AppiumCommandExecutor.java:141)
	at java.util.Optional.orElseGet(Optional.java:267)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:140)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:209)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:132)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:84)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:94)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:80)
	at com.jio.appium.manager.AppiumParallelTest.startingServerInstance(AppiumParallelTest.java:449)
	at com.jio.appium.manager.AppiumParallelTest.startAppiumServerInParallel(AppiumParallelTest.java:417)
	at com.jio.appium.manager.AppiumParallelTest.setDriver(AppiumParallelTest.java:1528)
	at com.jio.appium.manager.AppiumParallelTest.startAppiumServer(AppiumParallelTest.java:323)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:451)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:163)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:125)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:238)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:158)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:256)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:101)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:101)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:129)
	... 35 more

**Comment by mykola-mokhnach** [comment]
> UIAutomation2 is only supported since Android 5.0 (Lollipop). You could still use other supported backends in order to automate older Android versions.

I assume the error message is pretty clear there. You cannot use UIA2 for Android 4.4
