### ISSUE TITLE
latest node-simctl breaks appium with an error "Cannot read property 'async' of undefined"

### ISSUE THREAD

**Issue by seavan** [appium/appium#11624]
## The problem

Reinstalling appium breaks the workflow. This is an example error produced when running tests:

```
[XCUITest] TypeError: Cannot read property 'async' of undefined
[XCUITest]     at getDevices (/Users/distiller/project/node_modules/node-simctl/build/lib/simctl.js:1094:30)
[XCUITest]     at /Users/distiller/project/node_modules/appium-xcuitest-driver/lib/simulator-management.js:34:25
[XCUITest]     at Generator.next (<anonymous>)
[XCUITest]     at asyncGeneratorStep (/Users/distiller/project/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
[XCUITest]     at _next (/Users/distiller/project/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
[XCUITest]     at /Users/distiller/project/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
[XCUITest]     at new Promise (<anonymous>)
[XCUITest]     at /Users/distiller/project/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12
[XCUITest]     at _getExistingSim (/Users/distiller/project/node_modules/appium-xcuitest-driver/build/lib/simulator-management.js:94:26)
[XCUITest]     at getExistingSim (/Users/distiller/project/node_modules/appium-xcuitest-driver/build/lib/simulator-management.js:47:26)
[XCUITest]     at /Users/distiller/project/node_modules/appium-xcuitest-driver/lib/driver.js:716:24
[XCUITest]     at Generator.next (<anonymous>)
[XCUITest]     at asyncGeneratorStep (/Users/distiller/project/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
[XCUITest]     at _next (/Users/distiller/project/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
[XCUITest]     at /Users/distiller/project/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
[XCUITest]     at new Promise (<anonymous>)
[XCUITest]     at /Users/distiller/project/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12
[XCUITest]     at XCUITestDriver.determineDevice (/Users/distiller/project/node_modules/appium-xcuitest-driver/lib/driver.js:673:28)
[XCUITest]     at determineDevice (/Users/distiller/project/node_modules/appium-xcuitest-driver/lib/driver.js:254:51)
[XCUITest]     at Generator.next (<anonymous>)
[XCUITest]     at asyncGeneratorStep (/Users/distiller/project/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
[XCUITest]     at _next (/Users/distiller/project/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
[MJSONWP] Encountered internal error running command: TypeError: Cannot read property 'async' of undefined
[MJSONWP]     at getDevices (/Users/distiller/project/node_modules/node-simctl/build/lib/simctl.js:1094:30)
[MJSONWP]     at /Users/distiller/project/node_modules/appium-xcuitest-driver/lib/simulator-management.js:34:25
[MJSONWP]     at Generator.next (<anonymous>)
[MJSONWP]     at asyncGeneratorStep (/Users/distiller/project/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
[MJSONWP]     at _next (/Users/distiller/project/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
[MJSONWP]     at /Users/distiller/project/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
[MJSONWP]     at new Promise (<anonymous>)
[MJSONWP]     at /Users/distiller/project/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12
[MJSONWP]     at _getExistingSim (/Users/distiller/project/node_modules/appium-xcuitest-driver/build/lib/simulator-management.js:94:26)
[MJSONWP]     at getExistingSim (/Users/distiller/project/node_modules/appium-xcuitest-driver/build/lib/simulator-management.js:47:26)
[MJSONWP]     at /Users/distiller/project/node_modules/appium-xcuitest-driver/lib/driver.js:716:24
[MJSONWP]     at Generator.next (<anonymous>)
[MJSONWP]     at asyncGeneratorStep (/Users/distiller/project/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
[MJSONWP]     at _next (/Users/distiller/project/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
[MJSONWP]     at /Users/distiller/project/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
[MJSONWP]     at new Promise (<anonymous>)
[MJSONWP]     at /Users/distiller/project/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12
[MJSONWP]     at XCUITestDriver.determineDevice (/Users/distiller/project/node_modules/appium-xcuitest-driver/lib/driver.js:673:28)
[MJSONWP]     at determineDevice (/Users/distiller/project/node_modules/appium-xcuitest-driver/lib/driver.js:254:51)
[MJSONWP]     at Generator.next (<anonymous>)
[MJSONWP]     at asyncGeneratorStep (/Users/distiller/project/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
[MJSONWP]     at _next (/Users/distiller/project/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
```

Fixing node-simctl to version 3.16.0 fixes the issue. Installing node-simctl@3.17.0 reproduces the issue again.

## Environment
* Appium version (or git revision) that exhibits the issue:
1.8.1 and up
* Last Appium version that did not exhibit the issue (if applicable):
Not applicable
* Desktop OS/version used to run Appium:
OS X

## Details

Extra question - Appium package seems to be very prone to breaking from updated dependencies. Is there any reason not to fix dependency versions so that it doesn't break out of the blue? I see that for node-simctl the package.json is specifying the following range:

```
        "from": "node-simctl@>=3.11.5 <4.0.0",
```

Why not fix it to something?

Thank you.

**Comment by mykola-mokhnach** [comment]
Are you using appium@beta?

**Comment by seavan** [comment]
@mykola-mokhnach for me it breaks on 1.8.1 as well as on beta

**Comment by mykola-mokhnach** [comment]
This error looks like there is a conflict between different transpiler versions. Make sure you have full deleted the previous appium stuff before installing beta.

**Comment by seavan** [comment]
@mykola-mokhnach yes, I am trying this on fully deleted node_modules and fresh npm install and it reproduces unless I fix the node-simctl version. I stumbled upon this error as our circleci tests stopped  working all of a sudden (nothing appium related changed).

**Comment by dpgraham** [comment]
I just went ahead and unpublished 3.17.0 given that something I did in the publish yesterday obviously broke it. I'll dig into it some more and then publish a new version shortly.

@seavan There's a bug in Appium 1.8 (when using npm@5) that causes shrinkwrap to be ignored, and that's why it's installing the latest versions of packages. I would recommend that you should either upgrade to 1.9 or install 1.8 with npm@3

**Comment by seavan** [comment]
@dpgraham thank you. I did have the same problem with appium@v1.9.2-beta.2. I removed node_modules before install. npm 6.4.1.

now both launch fine.

**Comment by dpgraham** [comment]
Just to give more clarification, we actually do fix dependencies. There was a bug in npm@3 that was causing them not to be fixed.

As for 1.9, the betas are _not_ fixed and the GA releases _are_ fixed. So `npm install -g appium@1.9` it would fix the dependencies.

**Comment by dpgraham** [comment]
And also, worth noting, we are planning on making the betas use fixed dependencies too: https://github.com/appium/appium/issues/11535

**Comment by seavan** [comment]
@dpgraham I cannot use 1.9.1 because of this issue - https://github.com/appium/appium/issues/11477
Only the beta works for me.

It's good to hear that fixed dependencies are going to be there for the newer releases. Waiting for the beta to go to release to switch to it.
