### ISSUE TITLE
android (UiAutomator2): cannot get available timeouts

### ISSUE THREAD

**Issue by DudaGod** [appium/appium#11627]
## The problem

When I try to get available timeouts in my hybrid app on android I get an error:
```
[HTTP] --> GET /wd/hub/session/333fbb2d-f981-49da-a36e-d5a8b4246677/timeouts
[HTTP] {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/333fbb2d-f981-49da-a36e-d5a8b4246677/timeouts] to [GET http://localhost:8205/wd/hub/session/5a834c1a-cee8-4b50-8bf1-56998c90e534/timeouts] with body: {}
[MJSONWP] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: 404 - ""
[MJSONWP]     at doJwpProxy$ (/Users/dudkevich/job/projects/dudkevich/FEI-10277_pp-test/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:456:13)
[MJSONWP]     at tryCatch (/Users/dudkevich/job/projects/dudkevich/FEI-10277_pp-test/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/dudkevich/job/projects/dudkevich/FEI-10277_pp-test/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/dudkevich/job/projects/dudkevich/FEI-10277_pp-test/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke (/Users/dudkevich/job/projects/dudkevich/FEI-10277_pp-test/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[MJSONWP]     at <anonymous>
[HTTP] <-- GET /wd/hub/session/333fbb2d-f981-49da-a36e-d5a8b4246677/timeouts 500 34 ms - 269
```

Reproduced in both contexts: native and hybrid. Moreover I get the same error with `UiAutomator` driver but only in webview context.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Last Appium version that did not exhibit the issue (if applicable): -
* Desktop OS/version used to run Appium: Mac Os
* Node.js version (unless using Appium.app|exe): 8.6.0
* Mobile platform/version under test: android 6.0
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: cli

## Link to Appium logs

[logs](https://gist.github.com/DudaGod/8d6dac664016f7da6b53ad9194a27d7e)

## Code To Reproduce Issue [ Good To Have ]

```
'use strict';

const webdriverio = require('webdriverio');

const browser = webdriverio.remote({
    port: '4723',
    baseUrl: 'https://yandex.ru/search/touch',

    desiredCapabilities: {
        platformName: 'Android',
        platformVersion: '6.0',
        deviceName: 'Android Emulator',
        automationName: 'UiAutomator2',
        nativeWebScreenshot: true,
        showChromedriverLog: true,
        appPackage: 'ru.yandex.searchplugin.dev',
        appActivity: 'ru.yandex.searchplugin.MainActivity',
        intentAction: 'android.intent.action.VIEW',
        optionalIntentArguments: '--esn data ya-search-app-open://?uri=https://yandex.ru/search/touch'
    }
});

browser
    .init()
    .timeouts()
    .then((timeouts) => console.log('TIMEOUTS:', timeouts))
    .end()
    .catch((e) => {
        console.log('EEEEERRRRROOOOOORRRRR:', e);
        return browser.end();
    })

```

**Comment by mykola-mokhnach** [comment]
getTimeouts is a W3C command and chromedriver operates in MJSONWP mode. That is why this endpoint does not work there. However for UIA2 driver the fix should be simple

**Comment by mykola-mokhnach** [comment]
the fix has been published in appium@beta

**Comment by DudaGod** [comment]
Thank you.

**Comment by DudaGod** [comment]
@mykola-mokhnach Hello.

I just checked appium@beta and it still does not work =(

I get similar error:
```
[HTTP] --> GET /wd/hub/session/fcb13882-e4e6-47fe-9951-7ae782da1750/timeouts
[HTTP] {}
[MJSONWP (fcb13882)] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Matched '/wd/hub/session/fcb13882-e4e6-47fe-9951-7ae782da1750/timeouts' to command name 'getTimeouts'
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/fcb13882-e4e6-47fe-9951-7ae782da1750/timeouts] to [GET http://127.0.0.1:8000/wd/hub/session/753a4383fef8d5e4f217751a715725a3/timeouts] with body: {}
[JSONWP Proxy] Got an unexpected response: unknown command: session/753a4383fef8d5e4f217751a715725a3/timeouts
[debug] [MJSONWP (fcb13882)] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: 404 - "unknown command: session/753a4383fef8d5e4f217751a715725a3/timeouts"
[debug] [MJSONWP (fcb13882)]     at /Users/dudkevich/job/projects/dudkevich/FEI-10277_pp-test/node_modules/appium-base-driver/lib/protocol/protocol.js:550:13
[debug] [MJSONWP (fcb13882)]     at Generator.next (<anonymous>)
[debug] [MJSONWP (fcb13882)]     at asyncGeneratorStep (/Users/dudkevich/job/projects/dudkevich/FEI-10277_pp-test/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
[debug] [MJSONWP (fcb13882)]     at _next (/Users/dudkevich/job/projects/dudkevich/FEI-10277_pp-test/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
[debug] [MJSONWP (fcb13882)]     at <anonymous>
[HTTP] <-- GET /wd/hub/session/fcb13882-e4e6-47fe-9951-7ae782da1750/timeouts 500 55 ms - 335
```

But now in original error I see - `unknown command: session/753a4383fef8d5e4f217751a715725a3/timeouts`.

Did you check that with your fix this command works correctly?

**Comment by mykola-mokhnach** [comment]
Which context is active?

**Comment by DudaGod** [comment]
webview

**Comment by mykola-mokhnach** [comment]
In won't work in web views and I've already explained why.
