### ISSUE TITLE
Error Nativa APP Android with APPIUM

### ISSUE THREAD

**Issue by suarez677** [appium/appium#11637]
## The problem
Hello,
I am automating a native Android application, and it always shows me this error when interacting with an element:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.viewnext.fwappium.executor.ScriptExecutor.executeTheStep(ScriptExecutor.java:293)
	at com.viewnext.fwappium.executor.ScriptExecutor.executeStepList(ScriptExecutor.java:259)
	at com.viewnext.fwappium.executor.ScriptExecutor.executeIterations(ScriptExecutor.java:144)
	at com.viewnext.fwappium.executor.ScriptExecutor.run(ScriptExecutor.java:196)
	at com.viewnext.fwappium.utils.Parallelizer$1.run(Parallelizer.java:227)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.openqa.selenium.InvalidSelectorException: Locator Strategy 'css selector' is not supported for this session
For documentation on this error, please visit: http://seleniumhq.org/exceptions/invalid_selector_exception.html
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T15:28:36.4Z'
System info: host: 'S4Q72466', ip: '192.168.203.126', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_141'
Driver info: io.appium.java_client.android.AndroidDriver

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: Windows 7
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: 

## Details

I select the element by its "ID", "resource-id" in this case, I do not use "CSS"

## Link to Appium logs

java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.viewnext.fwappium.executor.ScriptExecutor.executeTheStep(ScriptExecutor.java:293)
	at com.viewnext.fwappium.executor.ScriptExecutor.executeStepList(ScriptExecutor.java:259)
	at com.viewnext.fwappium.executor.ScriptExecutor.executeIterations(ScriptExecutor.java:144)
	at com.viewnext.fwappium.executor.ScriptExecutor.run(ScriptExecutor.java:196)
	at com.viewnext.fwappium.utils.Parallelizer$1.run(Parallelizer.java:227)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.openqa.selenium.InvalidSelectorException: Locator Strategy 'css selector' is not supported for this session
For documentation on this error, please visit: http://seleniumhq.org/exceptions/invalid_selector_exception.html
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T15:28:36.4Z'
System info: host: 'S4Q72466', ip: '192.168.203.126', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_141'
Driver info: io.appium.java_client.android.AndroidDriver

**Comment by mykola-mokhnach** [comment]
make sure you use the most recent client version and selenium API version is not overridden in local dependencies config.

closed as duplicate.
