### ISSUE TITLE
Original error: '10.3' does not exist in the list of simctl SDKs. Only the following Simulator SDK versions are available on your system: 12.0

### ISSUE THREAD

**Issue by Owen-ET** [appium/appium#11681]
## The problem

<img width="911" alt="default" src="https://user-images.githubusercontent.com/42259434/48464485-a59b1d00-e81a-11e8-9e9c-499a557b74e0.png">

<img width="755" alt="default" src="https://user-images.githubusercontent.com/42259434/48464506-b350a280-e81a-11e8-9d13-f5728c6057f6.png">

## Environment

* Appium version ：1.9.1
* Appium-desktop：1.7.1
* Xcode：10.0
* iPhone5S：IOS(10.3.3)
* Mac：10.13.6

## Details

The SDK in Xcode is 10.3, but there is still a problem. It has been searched for a long time and has not been solved. Ask for help.

## Link to Appium logs
====================
log：
[HTTP] --> GET /wd/hub/sessions
[HTTP] {}
[GENERIC] Calling AppiumDriver.getSessions() with args: []
[GENERIC] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 3 ms - 40
[HTTP] 
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"AutomationName":"XCUITest","NewCommandTimeout":"3600","Udid":"42ebab931b6b2d6a140b1a4f5bd55305dbfe2ff0","bundleId":"com.chen.CityMineSafetyOne","deviceName":"iPhone5s","platformName":"iOS","platformVersion":"10.3","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"AutomationName":"XCUITest","NewCommandTimeout":"3600","Udid":"42ebab931b6b2d6a140b1a4f5bd55305dbfe2ff0","bundleId":"com.chen.CityMineSafetyOne","deviceName":"iPhone5s","platformName":"iOS","platformVersion":"10.3","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1542176248722 (14:17:28 GMT+0800 (CST))
[Appium] Requested iOS support with version >= 10, using 'XCUITest' driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
[Appium] Creating new XCUITestDriver (v2.94.2) session
[Appium] Capabilities:
[Appium]   AutomationName: XCUITest
[Appium]   NewCommandTimeout: 3600
[Appium]   Udid: 42ebab931b6b2d6a140b1a4f5bd55305dbfe2ff0
[Appium]   bundleId: com.chen.CityMineSafetyOne
[Appium]   deviceName: iPhone5s
[Appium]   platformName: iOS
[Appium]   platformVersion: 10.3
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true
[BaseDriver] Creating session with MJSONWP desired capabilities: {"AutomationName":"XCUITest...
[BaseDriver] The following capabilities were provided, but are not recognized by appium: AutomationName, NewCommandTimeout, Udid.
[BaseDriver] Session created with session id: cffd6722-a241-452b-8c52-08aae76aba49
[XCUITest] Current user: 'zhangc'
[XCUITest] Xcode version set to '10.0' (tools v9.4.1.0.1.1528165917)
[XCUITest] iOS SDK Version set to '12.0'
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1542176248804 (14:17:28 GMT+0800 (CST))
[XCUITest] Error: '10.3' does not exist in the list of simctl SDKs. Only the following Simulator SDK versions are available on your system: 12.0
[XCUITest]     at getDevices$ (/Applications/Project/Appium1.7.1.app/Contents/Resources/app/node_modules/appium/node_modules/node-simctl/lib/simctl.js:554:13)
[XCUITest]     at tryCatch (/Applications/Project/Appium1.7.1.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[XCUITest]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Project/Appium1.7.1.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[XCUITest]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Project/Appium1.7.1.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[XCUITest]     at GeneratorFunctionPrototype.invoke (/Applications/Project/Appium1.7.1.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[XCUITest]     at 
[XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[BaseDriver] Event 'newSessionStarted' logged at 1542176249030 (14:17:29 GMT+0800 (CST))
[MJSONWP] Encountered internal error running command: Error: '10.3' does not exist in the list of simctl SDKs. Only the following Simulator SDK versions are available on your system: 12.0
[MJSONWP]     at getDevices$ (/Applications/Project/Appium1.7.1.app/Contents/Resources/app/node_modules/appium/node_modules/node-simctl/lib/simctl.js:554:13)
[MJSONWP]     at tryCatch (/Applications/Project/Appium1.7.1.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Project/Appium1.7.1.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Project/Appium1.7.1.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke (/Applications/Project/Appium1.7.1.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[MJSONWP]     at 
[HTTP] <-- POST /wd/hub/session 500 313 ms - 263
[HTTP] 
[HTTP] --> DELETE /wd/hub/session
[HTTP] {}
[HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- DELETE /wd/hub/session 404 3 ms - 57
[HTTP] 

====================

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by Owen-ET** [comment]
<img width="783" alt="default" src="https://user-images.githubusercontent.com/42259434/48466969-6a9ce780-e822-11e8-9fb6-1fba252c2688.png">
The reason is that there is no 10.3 version in my Xcode => Preference => Components, which was downloaded and solved. Thank you.

**Comment by parikhparth23** [comment]
its not closed...I am facing the same issue
I have Xcode 10.1 and I want to run omg 12.1
when I run "xcrun simctl list" I am able to see 12.1 listed

**Comment by parikhparth23** [comment]
== Devices ==
-- iOS 12.1 --
    iPhone 5s (CF4D8F85-F773-473C-8374-FFBD286DC46C) (Shutdown) 
    iPhone 6 (DE292AF8-0C6E-47EF-83B0-5865376CFEC2) (Shutdown) 
    iPhone 6 Plus (55C2DA6D-E2A6-46C4-B8C6-16763E58051C) (Shutdown) 
    iPhone 6s (7382AE6F-E26D-46F6-8857-C0A427CD03C9) (Shutdown) 
    iPhone 6s Plus (A3E28226-CEDC-4B6C-970A-13362DE91928) (Shutdown) 
    iPhone 7 (F020CF54-09C4-4E46-B4F3-7A42794EB118) (Shutdown) 
    iPhone 7 Plus (B9E2BC74-59B7-4177-A28D-C4C67125DDD3) (Shutdown) 
    iPhone 8 (8C78231F-C9E3-4771-B26A-CF35BE929B0A) (Shutdown) 
    iPhone 8 Plus (32972038-190A-4392-B394-F5F6D1FFC240) (Shutdown) 
    iPhone SE (C19CD3B6-EB89-45CF-A6AC-777EDEAD2642) (Shutdown) 
    iPhone X (26D0C477-36FB-421C-8CA8-9891F5380D81) (Shutdown) 
    iPhone XS (A07B8ED5-939A-4ED8-912B-18072AFCB09A) (Shutdown) 
    iPhone XS Max (322ADC01-0A00-41E2-8956-5000FC3C35C7) (Shutdown) 
    iPhone XR (2FAF7F78-32D4-4D8B-A044-2213B9B2DA28) (Shutdown) 
    iPad Air (7B6CAE6F-A9AE-4AF9-BBF6-5E697D3CD074) (Shutdown) 
    iPad Air 2 (D9385BE8-6F54-4F9C-8F86-88613AEC7EFE) (Shutdown) 
    iPad (5th generation) (1C3D8E14-CD24-4F8D-894B-4B0B7AADEEC0) (Shutdown) 
    iPad Pro (9.7-inch) (5329E861-E34B-41FE-8138-E5676388C11A) (Shutdown) 
    iPad Pro (12.9-inch) (0402A969-2D9F-4265-BA9F-DA5E449B066C) (Shutdown) 
    iPad Pro (12.9-inch) (2nd generation) (31B4653C-56EC-4277-A722-9948679EE0A8) (Shutdown) 
    iPad Pro (10.5-inch) (BCE50226-39E7-4632-B2C0-34E82B9F9F49) (Shutdown) 
    iPad (6th generation) (43844525-5A68-4513-B5F4-EA0CB545C7F0) (Shutdown) 
    iPad Pro (11-inch) (51DAD0A4-64D9-44BD-9FE6-7F7617C7F9AC) (Shutdown) 
    iPad Pro (12.9-inch) (3rd generation) (592DD2A9-4E39-4906-B640-C6A8EE278B35) (Shutdown)

**Comment by rmarinsky** [comment]
The same for me

**Comment by Victor-Jansson** [comment]
Same for me as well.

**Comment by kanu1713** [comment]
same for me please help in solving

**Comment by parikhparth23** [comment]
@rmarinsky @Victor-Jansson @kanu1713 please update your appium desktop app to the latest 1.12.0 (1.12.0.20190327.10) version....it will fix the issue.
please follow this thread: https://github.com/appium/appium/issues/12391#issuecomment-477400840
