### ISSUE TITLE
when I click element  through appium inspector,appium will crash and throw error:uncaughtException: no value passed to Element constructor 

### ISSUE THREAD

**Issue by joesky88** [appium/appium#11686]
## The problem
when I click element  through appium inspector,appium will crash and throw error: uncaughtException: no value passed to Element constructor date=Wed Nov 14 2018 20:12:56 GMT+0800 (CST), pid=82120, uid=501, gid=20, cwd=/, execPath=/Applications/Appium.app/Contents/MacOS/Appium, version=v8.9.3, argv=[/Applications/Appium.app/Contents/MacOS/Appium, ], rss=209334272, heapTotal=234758144, heapUsed=224361240, external=183769, loadavg=[5.6025390625, 5.35888671875, 5.4072265625], uptime=28666, trace=[column=1, file=/Applications/Appium.app/Contents/Resources/app/webpack:/~/wd/lib/element.js, function=PromiseElement.Element, line=15, method=Element, native=false, column=1, file=/Applications/Appium.app/Contents/Resources/app/webpack:/~/wd/lib/promise-webdriver.js, function=new PromiseElement, line=73, method=null, native=false, column=1, file=/Applications/Appium.app/Contents/Resources/app/webpack:/~/wd/lib/promise-webdriver.js, function=PromiseWebdriver.newElement, line=103, method=newElement, native=false, column=1, file=/Applications/Appium.app/Contents/Resources/app/webpack:/~/wd/lib/callbacks.js, function=null, line=137, method=null, native=false, column=1, file=/Applications/Appium.app/Contents/Resources/app/webpack:/~/wd/lib/callbacks.js, function=null, line=82, method=null, native=false, column=1, file=/Applications/Appium.app/Contents/Resources/app/webpack:/~/wd/lib/webdriver.js, function=null, line=179, method=null, native=false, column=1, file=/Applications/Appium.app/Contents/Resources/app/webpack:/~/wd/lib/http-utils.js, function=Request._callback, line=89, method=_callback, native=false, column=1, file=/Applications/Appium.app/Contents/Resources/app/webpack:/~/request/request.js, function=Request.self.callback, line=186, method=callback, native=false, column=13, file=events.js, function=emitTwo, line=126, method=null, native=false, column=7, file=events.js, function=Request.emit, line=214, method=emit, native=false, column=1, file=/Applications/Appium.app/Contents/Resources/app/webpack:/~/request/request.js, function=null, line=1163, method=null, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false, column=7, file=events.js, function=Request.emit, line=211, method=emit, native=false, column=1, file=/Applications/Appium.app/Contents/Resources/app/webpack:/~/request/request.js, function=null, line=1085, method=null, native=false, column=30, file=events.js, function=Object.onceWrapper, line=313, method=onceWrapper, native=false, column=20, file=events.js, function=emitNone, line=111, method=null, native=false, column=7, file=events.js, function=IncomingMessage.emit, line=208, method=emit, native=false, column=12, file=_stream_readable.js, function=endReadableNT, line=1056, method=null, native=false, column=11, file=internal/process/next_tick.js, function=_combinedTickCallback, line=138, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=180, method=_tickCallback, native=false], stack=[Error: no value passed to Element constructor,     at PromiseElement.Element (/Applications/Appium.app/Contents/Resources/app/webpack:/~/wd/lib/element.js:15:1),     at new PromiseElement (/Applications/Appium.app/Contents/Resources/app/webpack:/~/wd/lib/promise-webdriver.js:73:1),     at PromiseWebdriver.newElement (/Applications/Appium.app/Contents/Resources/app/webpack:/~/wd/lib/promise-webdriver.js:103:1),     at /Applications/Appium.app/Contents/Resources/app/webpack:/~/wd/lib/callbacks.js:137:1,     at /Applications/Appium.app/Contents/Resources/app/webpack:/~/wd/lib/callbacks.js:82:1,     at /Applications/Appium.app/Contents/Resources/app/webpack:/~/wd/lib/webdriver.js:179:1,     at Request._callback (/Applications/Appium.app/Contents/Resources/app/webpack:/~/wd/lib/http-utils.js:89:1),     at Request.self.callback (/Applications/Appium.app/Contents/Resources/app/webpack:/~/request/request.js:186:1),     at emitTwo (events.js:126:13),     at Request.emit (events.js:214:7),     at Request.<anonymous> (/Applications/Appium.app/Contents/Resources/app/webpack:/~/request/request.js:1163:1),     at emitOne (events.js:116:13),     at Request.emit (events.js:211:7),     at IncomingMessage.<anonymous> (/Applications/Appium.app/Contents/Resources/app/webpack:/~/request/request.js:1085:1),     at Object.onceWrapper (events.js:313:30),     at emitNone (events.js:111:20),     at IncomingMessage.emit (events.js:208:7),     at endReadableNT (_stream_readable.js:1056:12),     at _combinedTickCallback (internal/process/next_tick.js:138:11),     at process._tickCallback (internal/process/next_tick.js:180:9)]

## Environment

* Appium version :1.6.3
* Last Appium version that did not exhibit the issue (if applicable):1.6.3
* Desktop OS/version used to run Appium: Mac OS 10.14 (18A391)
* Node.js version :11.1.0
* Mobile platform/version under test:Android 8.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium.app

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by joesky88** [comment]
sorry  Appium version : 1.8.1,   Appium app version:1.6.3
