### ISSUE TITLE
wda problem

### ISSUE THREAD

**Issue by johanntony** [appium/appium#11697]
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Unhandled endpoint: /session/76931913-F27B-4166-BBCC-80B198C44FEF/wda/screen -- http://localhost:8100/ with parameters {
          wildcards =     (
              "session/76931913-F27B-4166-BBCC-80B198C44FEF/wda/screen"
          );
      }
      Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
      System info: host: 'jiahantangdeMacBook-Pro.local', ip: 'fe80:0:0:0:1495:a9e0:4739:2477%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14', java.version: '10.0.2'
      Driver info: io.appium.java_client.ios.IOSDriver
      Capabilities {autoGrantPermissions: true, automationName: Appium, browserName: , bundleId: com.bjlc.LuckinDriver, databaseEnabled: false, deviceName: iPhone(2), javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: false, newCommandTimeout: 300, noReset: true, platform: MAC, platformName: iOS, platformVersion: 12.1, resetKeyboard: true, takesScreenshot: true, udid: 68f73cf8b7676dd695ff9937a90..., unicodeKeyboard: true, webStorageEnabled: false}
      Session ID: b462a17c-dcdd-4052-8949-0a1fe13fefcd
      	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
      	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
      	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
      	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
      	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
      	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
      	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
      	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
      	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:231)
      	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
      	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:46)
      	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
      	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
      	at io.appium.java_client.HasSessionDetails.getSessionDetails(HasSessionDetails.java:39)
      	at io.appium.java_client.HasSessionDetails.getSessionDetail(HasSessionDetails.java:56)
      	at io.appium.java_client.HasSessionDetails.getPlatformName(HasSessionDetails.java:65)
      	at io.appium.java_client.internal.JsonToMobileElementConverter.<init>(JsonToMobileElementConverter.java:49)
      	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:89)
      	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:94)
      	at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:95)
      	at com.appium.lib.seleniumcucumber.base.AppiumController.startDriver(AppiumController.java:99)
      	at com.appium.lib.seleniumcucumber.stepdefinitions.PredefinedStepDefinitions.runAppDispatch(PredefinedStepDefinitions.java:34)
      	at ✽.Given Run APP DISPATCH(IosDispach.feature:6)

why i run the python everyThing is ok,but use java IDE .

**Comment by mykola-mokhnach** [comment]
WDA binary on the device is outdated. Makes sure it is built and deployed from the source, which is included into appium-xcuitest-driver. Closed as duplicate.

**Comment by johanntony** [comment]
but why python can ,i also clear cache, and every other things , but still can not

**Comment by mykola-mokhnach** [comment]
Make sure you use WDA sources from Appium's [fork(https://github.com/appium/WebDriverAgent/pulls). The one from facebook is not compatible.
