### ISSUE TITLE
App crashes randomly during tests, works fine otherwise

### ISSUE THREAD

**Issue by KthProg** [appium/appium#11712]
## Description

The app is crashing on startup but only when running tests through Appium. Running the app directly works just fine. Sometimes I have to clear the adb logs but that's about it.

## Environment

* .NET Core 2
* Appium Server 5.6.0
* Windows 10
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Android 7.0
* Real device but sometimes reproducible on emulator as well. Spontaneously resolves itself

## Details

Please provide more details, if necessary.

## Code To Reproduce Issue [ Good To Have ]

``` 
            AppiumLocalService service = AppiumLocalService.BuildDefaultService();
            service.Start();

            IWebDriver driver = null;
            AppiumOptions options = new AppiumOptions();

            options.AddAdditionalCapability(MobileCapabilityType.FullReset, true);
            options.AddAdditionalCapability(MobileCapabilityType.NoReset, false);

            options.AddAdditionalCapability(MobileCapabilityType.Udid, d.DeviceData.Serial);

            options.AddAdditionalCapability("useNewWDA", true);

            options.AddAdditionalCapability(MobileCapabilityType.DeviceName, d.DeviceData.Serial);
            options.AddAdditionalCapability("deviceModel", d.DeviceData.Model);
            options.AddAdditionalCapability(MobileCapabilityType.App, _AppSettings.ApkLocation);
            driver = new AndroidDriver<AndroidElement>(service, options);
```

## Exception stacktraces

No stack trace but heres adb logs:

```
11-19 16:05:21.499 28601 28601 W art     : JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
11-19 16:05:21.502 28601 28601 D AndroidRuntime: Shutting down VM
11-19 16:05:21.505 28601 28601 E AndroidRuntime: FATAL EXCEPTION: main
11-19 16:05:21.505 28601 28601 E AndroidRuntime: Process: com.lci1.one.v3, PID: 28601
11-19 16:05:21.505 28601 28601 E AndroidRuntime: android.runtime.JavaProxyThrowable: System.InvalidOperationException: Operation is not valid due to the current state of the object.
11-19 16:05:21.505 28601 28601 E AndroidRuntime:   at Xamarin.Forms.Internals.TypedBinding`2[TSource,TProperty].Apply (System.Boolean fromTarget) [0x00016] in <81ae0eb290e24f558e192928e3e37a57>:0 
11-19 16:05:21.505 28601 28601 E AndroidRuntime:   at Xamarin.Forms.Internals.TypedBinding`2+PropertyChangedProxy[TSource,TProperty].<OnPropertyChanged>b__16_0 () [0x00000] in <81ae0eb290e24f558e192928e3e37a57>:0 
11-19 16:05:21.505 28601 28601 E AndroidRuntime:   at Java.Lang.Thread+RunnableImplementor.Run () <0x8eb9034c + 0x0002f> in <6fc7b4d48a944f3ba908f80a890b1eba>:0 
11-19 16:05:21.505 28601 28601 E AndroidRuntime:   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) <0x8eb889ec + 0x00057> in <6fc7b4d48a944f3ba908f80a890b1eba>:0 
11-19 16:05:21.505 28601 28601 E AndroidRuntime:   at (wrapper dynamic-method) System.Object.17(intptr,intptr)
11-19 16:05:21.505 28601 28601 E AndroidRuntime:     at mono.java.lang.RunnableImplementor.n_run(Native Method)
11-19 16:05:21.505 28601 28601 E AndroidRuntime:     at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
11-19 16:05:21.505 28601 28601 E AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:751)
11-19 16:05:21.505 28601 28601 E AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
11-19 16:05:21.505 28601 28601 E AndroidRuntime:     at android.os.Looper.loop(Looper.java:154)
11-19 16:05:21.505 28601 28601 E AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:6317)
11-19 16:05:21.505 28601 28601 E AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
11-19 16:05:21.505 28601 28601 E AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
11-19 16:05:21.505 28601 28601 E AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
11-19 16:05:21.507  3365  8681 W ActivityManager:   Force finishing activity com.lci1.one.v3/md56746cd45cb2a397a35890e14accb4d9f.MainActivity
11-19 16:05:21.511  3365  8681 D InputDispatcher: Focus left window: Window{cc82747 u0 com.lci1.one.v3/md56746cd45cb2a397a35890e14accb4d9f.MainActivity}
11-19 16:05:21.512  3365  8681 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
11-19 16:05:21.540  3365  3383 D InputDispatcher: Focus entered window: Window{9ddf309 u0 Application Error: com.lci1.one.v3}
```

## Link to Appium logs

No logs. App fails to start.

**Comment by KthProg** [comment]
I'm not sure how to get the log entries since the driver fails to initialize when the app crashes.

**Comment by mykola-mokhnach** [comment]
I don't think there's anything that can be changed on Appium side. Although, make sure you use Uiautomator2 if you run your tests on Android 6+

**Comment by KthProg** [comment]
I switch to UiAutomator2 and same issue. For whatever reason, if I install the app directly through adb, then I have to clear the logs afterwards or it will not run. If I install from Visual Studio deploy then it's fine. It looks like an issue with the app.

**Comment by KthProg** [comment]
Ah. It's nothing to do with Appium or the logs. The first start always fails for no particular reason. Amazing... -_-
