### ISSUE TITLE
XCUITest requires Appium version >= 1.6.0

### ISSUE THREAD

**Issue by Rockwig-GSC** [appium/appium#11745]
## The problem

Just installed the new version `1.10.0` and I am now receiving the following error when trying to start a test:
`XCUITest requires Appium version >= 1.6.0`

## Environment

* Appium version (or git revision) that exhibits the issue: 1.10.0
* Last Appium version that did not exhibit the issue (if applicable): 1.9.1
* Desktop OS/version used to run Appium: macOS
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS 11.2
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

```
Failure/Error: @driver = Appium::Driver.new(desired_capabilities, true).start_driver

Appium::Core::Error::NotSupportedAppiumServer:
  XCUITest requires Appium version >= 1.6.0
# ./vendor/bundle/ruby/2.5.0/gems/appium_lib-9.16.0/lib/appium_lib/driver.rb:336:in `check_server_version_xcuitest'
# ./vendor/bundle/ruby/2.5.0/gems/appium_lib-9.16.0/lib/appium_lib/driver.rb:519:in `start_driver'
```

**Comment by dpgraham** [comment]
Thanks for reporting this!

**Comment by dpgraham** [comment]
This is a problem with the Ruby driver: https://github.com/appium/ruby_lib/blob/5172e19fc55d4649f679b50d0560d146b9e9ac71/lib/appium_lib/driver.rb

Transferring this issue to the `ruby_lib` repository

cc: @KazuCocoa
