### ISSUE TITLE
Appium ADB fail to execute

### ISSUE THREAD

**Issue by AvrahamAtia** [appium/appium#11757]
## The problem

Make sure the 'LayoutParams.FLAG_SECURE' is not set for the current view

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Node.js version (unless using Appium.app|exe): v10.4.1
* Mobile platform/version under test:  Android  8.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: appium 
appium -a 127.0.0.1 -p 4735 -bp 8120 --log 4735_AppiumServerLog.txt

## Details

[debug] [UiAutomator] Moving to state 'stopped'
[debug] [ADB] Running '/Users/auto_android_haifa_1/Library/Android/sdk/platform-tools/adb -P 5037 -s 00d23eb3d478beb9 shell /system/bin/rm /data/local/tmp/screenshot.png\; /system/bin/screencap -p /data/local/tmp/screenshot.png'
[debug] [AndroidDriver] Shutting down Android driver
[debug] [ADB] Running '/Users/auto_android_haifa_1/Library/Android/sdk/platform-tools/adb -P 5037 -s 00d23eb3d478beb9 shell am force-stop com.shutterfly.develop'
[Appium] Closing session, cause was 'UiAUtomator shut down unexpectedly'
[Appium] Removing session 32ef8ee0-70a6-4489-a837-132d44297ec1 from our master session list
[debug] [ADB] Running '/Users/auto_android_haifa_1/Library/Android/sdk/platform-tools/adb -P 5037 -s 00d23eb3d478beb9 shell am force-stop com.shutterfly.develop'
Unhandled rejection Error: Error executing adbExec. Original error: 'Command '/Users/auto_android_haifa_1/Library/Android/sdk/platform-tools/adb -P 5037 -s 00d23eb3d478beb9 shell am force-stop com.shutterfly.develop' exited with code 1'; Stderr: 'error: device '00d23eb3d478beb9' not found'; Code: '1'
    at ADB.execFunc$ (/usr/local/lib/node_modules/appium/node_modules/appium-adb/lib/tools/system-calls.js:317:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[debug] [ADB] Running '/Users/auto_android_haifa_1/Library/Android/sdk/platform-tools/adb -P 5037 -s 00d23eb3d478beb9 shell /system/bin/rm /data/local/tmp/screenshot.png\; /system/bin/screencap -p /data/local/tmp/screenshot.png'
[AndroidDriver] Error: Cannot get screenshot data because of 'Error executing adbExec. Original error: 'Command '/Users/auto_android_haifa_1/Library/Android/sdk/platform-tools/adb -P 5037 -s 00d23eb3d478beb9 shell /system/bin/rm /data/local/tmp/screenshot.png\; /system/bin/screencap -p /data/local/tmp/screenshot.png' exited with code 1'; Stderr: 'error: device '00d23eb3d478beb9' not found'; Code: '1''. Make sure the 'LayoutParams.FLAG_SECURE' is not set for the current view
[AndroidDriver]     at Object.wrappedLogger.errorAndThrow (/usr/local/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[AndroidDriver]     at AndroidDriver.callee$0$0$ (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/lib/commands/actions.js:375:11)
[AndroidDriver]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[AndroidDriver]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[AndroidDriver]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[AndroidDriver]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[MJSONWP] Encountered internal error running command: Error: Cannot get screenshot data because of 'Error executing adbExec. Original error: 'Command '/Users/auto_android_haifa_1/Library/Android/sdk/platform-tools/adb -P 5037 -s 00d23eb3d478beb9 shell /system/bin/rm /data/local/tmp/screenshot.png\; /system/bin/screencap -p /data/local/tmp/screenshot.png' exited with code 1'; Stderr: 'error: device '00d23eb3d478beb9' not found'; Code: '1''. Make sure the 'LayoutParams.FLAG_SECURE' is not set for the current view
[MJSONWP]     at Object.wrappedLogger.errorAndThrow (/usr/local/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[MJSONWP]     at AndroidDriver.callee$0$0$ (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/lib/commands/actions.js:375:11)
[MJSONWP]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <

**Comment by saikrishna321** [comment]
> [AndroidDriver] Error: Cannot get screenshot data because of 'Error executing adbExec. Original error: 'Command '/Users/auto_android_haifa_1/Library/Android/sdk/platform-tools/adb -P 5037 -s 00d23eb3d478beb9 shell /system/bin/rm /data/local/tmp/screenshot.png; /system/bin/screencap -p /data/local/tmp/screenshot.png' exited with code 1'; Stderr: 'error: device '00d23eb3d478beb9' not found'; Code: '1''. Make sure the 'LayoutParams.FLAG_SECURE' is not set for the current view

https://developer.android.com/reference/android/view/WindowManager.LayoutParams#FLAG_SECURE

You won't be able to capture screenshot when FLAG_SECURE is set to current view.
