### ISSUE TITLE
Error while opening a deeplink on Android

### ISSUE THREAD

**Issue by vuurtorenman** [appium/appium#11787]
## The problem

I'm trying to open a deeplink using the driver.get() function.
For iOS it works fine, but on an Android emulator I always get this error:

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error attempting to start URI. Original error: Error: Starting: Intent { act=android.intent.action.VIEW dat=https://MYURL }
Error: Activity not started, unable to resolve Intent { act=android.intent.action.VIEW dat=https://MYURL }
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.6', java.version: '1.8.0_144'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {app: XXX.apk appPackage: XXX, appWaitActivity: XXX, autoLaunch: true, avd: Nexus_5X_API_27, databaseEnabled: false, desired: {app: XXX, autoLaunch: true, avd: Nexus_5X_API_27, deviceName: emulator-5556, fullReset: false, noReset: true, platformName: android, showChromedriverLog: false}, deviceManufacturer: Google, deviceModel: Android SDK built for x86, deviceName: emulator-5554, deviceScreenSize: 1080x1920, deviceUDID: emulator-5554, fullReset: false, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, noReset: true, platform: LINUX, platformName: Android, platformVersion: 8.1.0, showChromedriverLog: false, takesScreenshot: true, warnings: {}, webStorageEnabled: false}
Session ID: 469f251a-d80f-40a2-96e7-2ba0a9fef7ca

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:231)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:271)

## Environment

* Appium version: 1.9.0 (1.9.0)
* Desktop OS/version used to run Appium: macOS High Sierra
* Mobile platform/version under test: Android API level 27
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: Appium.app

## Link to Appium logs

https://gist.github.com/vuurtorenman/ce7e349bc1779a6831cf2a31af132bb7

**Comment by mykola-mokhnach** [comment]
Did you read https://appiumpro.com/editions/7 ? Also, it is recommended to use UIAutomator2 for Android 6+

**Comment by vuurtorenman** [comment]
Yes, tried to use UIAutomator2 - the same result.

Log with UIAutomator2
https://gist.github.com/vuurtorenman/9379599d3bca6d84974505d4c28f6acd

**Comment by mykola-mokhnach** [comment]
Maybe you application does not handle the link properly? Which command works if you execute it directly from adb command line?
