### ISSUE TITLE
getting permission denial error

### ISSUE THREAD

**Issue by dgargd2524** [appium/appium#11804]
## The problem
I executed the code mentioned below but getting error permission denial. Here i am trying to open Google search app through appium.
package first;

import java.net.MalformedURLException;
import java.net.URL;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import io.appium.java_client.AppiumDriver;
import io.appium.java_client.MobileElement;
import io.appium.java_client.android.AndroidDriver;

public class testcode 
{
	
	public static void main(String[] args)
	{
	
	//Set the Desired Capabilities
			DesiredCapabilities caps = new DesiredCapabilities();
			caps.setCapability("deviceName", "Mi A1");
			caps.setCapability("udid", "78079bf90404"); //Give Device ID of your mobile phone
			caps.setCapability("platformName", "Android");
			caps.setCapability("platformVersion", "8.1.0");
			caps.setCapability("appPackage", "com.google.android.googlequicksearchbox");
			caps.setCapability("appActivity", "com.google.android.apps.gsa.searchnow.MultiInstanceSearchNowActivity");
			caps.setCapability("noReset", "true");
			caps.setCapability("autoGrantPermissions","true");
			caps.setCapability("appWaitActivity", "50000");
			caps.setCapability("appWaitDuration", "50000");
			
			//Instantiate Appium Driver
			try {
					AppiumDriver<MobileElement> driver = new AndroidDriver<MobileElement>(new URL("http://0.0.0.0:4723/wd/hub"), caps);
				
			} catch (MalformedURLException e) {
				System.out.println(e.getMessage());
			}
}
}

Result:
Exception in thread "main" org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.google.android.googlequicksearchbox' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Error executing adbExec. Original error: 'Command 'C\:\\Users\\DEEPAK\\AppData\\Local\\Android\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 78079bf90404 shell am start -W -n com.google.android.googlequicksearchbox/com.google.android.apps.gsa.searchnow.MultiInstanceSearchNowActivity -S' exited with code 4294967295'; Stderr: 'Security exception: Permission Denial: starting Intent { flg=0x10000000 cmp=com.google.android.googlequicksearchbox/com.google.android.apps.gsa.searchnow.MultiInstanceSearchNowActivity } from null (pid=12158, uid=2000) not exported from uid 10035

java.lang.SecurityException: Permission Denial: starting Intent { flg=0x10000000 cmp=com.google.android.googlequicksearchbox/com.google.android.apps.gsa.searchnow.MultiInstanceSearchNowActivity } from null (pid=12158, uid=2000) not exported from uid 10035
	at com.android.server.am.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1641)
	at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:443)
	at com.android.server.am.ActivityStarter.startActivityLocked(ActivityStarter.java:283)
	at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:822)
	at com.android.server.am.ActivityManagerService.startActivityAndWait(ActivityManagerService.java:4744)
	at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:412)
	at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:141)
	at android.os.ShellCommand.exec(ShellCommand.java:96)
	at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:15193)
	at android.os.Binder.shellCommand(Binder.java:594)
	at android.os.Binder.onTransact(Binder.java:492)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:4243)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2971)
	at android.os.Binder.execTransact(Binder.java:697)'; Code: '4294967295' (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 11.35 seconds
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'DESKTOP-Q35E6IJ', ip: '192.168.0.106', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_191'
Driver info: io.appium.java_client.android.AndroidDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:40)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:249)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:36)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:114)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:132)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:92)
	at first.testcode.main(testcode.java:33)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.0
* Desktop OS/version used to run Appium: windows 10
* Mobile platform/version under test: Android 8.1.0
* Real device or emulator/simulator: Real device

**Comment by mykola-mokhnach** [comment]
Did you read the page at the link above?

**Comment by dgargd2524** [comment]
Yes I read the link above
