### ISSUE TITLE
Unable to Unlock Device : Error finding unlock pin buttons!

### ISSUE THREAD

**Issue by guptarajatkn** [appium/appium#11812]
## The problem

Unable to Unlock The Device using unlockType capabilities of Appium

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.0
* Desktop OS/version used to run Appium: MacOS High Sierra
* Node.js version (unless using Appium.app|exe): v10.4.0
* Mobile platform/version under test:  Android 6.0 ( LeTv 1s)
* Real device or emulator/simulator: LeTv 1s
* Appium CLI or Appium.app|exe: Appium.app

## Details

**_Apium Capabilities:_**
```
{ 
"platformName":"Android",
"deviceName":"Letv 1s",
"unlockType":"pin",
"unlockKey":"1121",
"udid":"EAJB95CILVS8BY85",
"app":"Users/rg/runtime/apk/*****debug1***.apk",
"deviceReadyTimeout":14,
"appWaitActivity":"SplashActivity, OtherActivity, *.SplashActivity, MainActivity, mainActivity, *.mainActivity, *.MainActivity, OtpActivity, *.OtpActivity",
"autoGrantPermissions":true,
"noReset":true,
"androidInstallTimeout":100000
}
```

## Error :
```
Error: [init({"platformName":"Android","deviceName":"Letv 1s","unlockType":"pin","unlockKey":"1121","udid":"EAJB95CILVS8BY85","app":"/Users/rg/Automation/ui_automation/runtime/apk/*****debug1***.apk","deviceReadyTimeout":14,"appWaitActivity":"SplashActivity, OtherActivity, *.SplashActivity, MainActivity, mainActivity, *.mainActivity, *.MainActivity, OtpActivity, *.OtpActivity","autoGrantPermissions":true,"noReset":true,"androidInstallTimeout":100000})] The environment you requested was unavailable.
    **An unknown server-side error occurred while processing the command. Original error: Error finding unlock pin buttons!**
         at /Users/rg/Automation/ui_automation/node_modules/wd/lib/webdriver.js:138:15
         at Request._callback (/Users/rg/Automation/ui_automation/node_modules/wd/lib/http-utils.js:89:7)
         at Request.self.callback (/Users/rg/Automation/ui_automation/node_modules/wd/node_modules/request/request.js:186:22)
         at Request.emit (events.js:182:13)
         at Request.<anonymous> (/Users/rg/Automation/ui_automation/node_modules/wd/node_modules/request/request.js:1163:10)
         at Request.emit (events.js:182:13)
         at IncomingMessage.<anonymous> (/Users/rg/Automation/ui_automation/node_modules/wd/node_modules/request/request.js:1085:12)
         at Object.onceWrapper (events.js:273:13)
         at IncomingMessage.emit (events.js:187:15)
         at endReadableNT (_stream_readable.js:1081:12)
```

**Comment by mykola-mokhnach** [comment]
- Try appium@beta
- Please attach the full server log
