### ISSUE TITLE
Clean installed appium issues with CSS-selector 

### ISSUE THREAD

**Issue by parshav** [appium/appium#11859]
## The problem

Clean installed Appium 1.9.0 for macOS Mojave 10.14.1
appium-doctor shows no issues, green checkmark on everything.
Appium launches the android app, but shows this error and stops the test.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.0
* Desktop OS/version used to run Appium: macOS Mojave 10.14.1
* Mobile platform/version under test: Android 9
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: Both

## Link to Appium logs

```
[W3C (8572dabc)] Calling AppiumDriver.findElement() with args: ["css selector","#btn_help","8572dabc-4c30-4bbc-91b9-acde262edc11"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [W3C (8572dabc)] Encountered internal error running command: InvalidSelectorError: Locator Strategy 'css selector' is not supported for this session
[debug] [W3C (8572dabc)]     at AndroidDriver.validateLocatorStrategy (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:344:13)
[debug] [W3C (8572dabc)]     at AndroidDriver.helpers.findElOrElsWithProcessing (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:28:8)
[debug] [W3C (8572dabc)]     at AndroidDriver.commands.findElement (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:50:21)
[debug] [W3C (8572dabc)]     at curCommandCancellable._bluebird.default.resolve.then (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:291:18)
[debug] [W3C (8572dabc)]     at tryCatcher (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/util.js:26:23)
[debug] [W3C (8572dabc)]     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/promise.js:510:31)
[debug] [W3C (8572dabc)]     at Promise._settlePromiseAt (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/promise.js:584:18)
[debug] [W3C (8572dabc)]     at Promise._settlePromiseAtPostResolution (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/promise.js:248:10)
[debug] [W3C (8572dabc)]     at Async._drainQueue (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/async.js:128:12)
[debug] [W3C (8572dabc)]     at Async._drainQueues (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/async.js:133:10)
[debug] [W3C (8572dabc)]     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/async.js:15:14)
[debug] [W3C (8572dabc)]     at processImmediate (timers.js:632:19)
```
### Details

We use find element by id 
`@driver.find_element(:id, id)`
to find the id of a view, not sure why this error using `css selector` comes up.

**Comment by mykola-mokhnach** [comment]
this is client-side issue. Closed as duplicate: https://github.com/appium/appium/issues?q=is%3Aissue+%22+Locator+Strategy+%27css+selector%27+is+not+supported%22+is%3Aclosed

**Comment by zmeriksen** [comment]
@mykola-mokhnach Could you please link the original issue?

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium/issues/10874 has the biggest thread.
In general,

- Update to the latest appium client
- Use proper driver defined for Appium, not for pure selenium-webdriver

are related to this topic
