### ISSUE TITLE
'Error: Xcode version '0.1'. Support for Xcode 0.1 is not supported.' for Xcode 10.1

### ISSUE THREAD

**Issue by sushreetech** [appium/appium#11901]
## The problem
I am getting below error while launching app. Xcode version is 10.1. 

- Error: Xcode version '0.1'. Support for Xcode 0.1 is not supported. Please upgrade to version 7.3 or higher

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: Mac OS 10.14.1
* Node.js version (unless using Appium.app|exe):6.4.1
* Mobile platform/version under test:  Iphone 8 plus(12.1)
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: Appium.app

## Link to Appium logs

```
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"automationName":"XCUITest","bundleId":"ch.xyz.123","platformName":"iOS","deviceName":"iPhone 8 Plus","platformVersion":"12.1"},null,{"alwaysMatch":{"appium:automationName":"XCUITest","appium:bundleId":"ch.xyz.123","appium:deviceName":"iPhone 8 Plus","platformName":"ios","appium:platformVersion":"12.1"},"firstMatch":[{}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1545550914927 (13:11:54 GMT+0530 (India Standard Time))
[Appium] Creating new XCUITestDriver (v2.51.1) session
[Appium] Capabilities:
[Appium]   automationName: 'XCUITest'
[Appium]   bundleId: 'ch.xyz.123'
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'iPhone 8 Plus'
[Appium]   platformVersion: '12.1'
[BaseDriver] Session created with session id: 42dbc478-fe86-44bc-9759-18cee7d19e51
[XCUITest] Error: Xcode version '0.1'. Support for Xcode 0.1 is not supported. Please upgrade to version 7.3 or higher
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at getAndCheckXcodeVersion$ (../../lib/utils.js:62:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
 Error: Xcode version '0.1'. Support for Xcode 0.1 is not supported. Please upgrade to version 7.3 or higher
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at getAndCheckXcodeVersion$ (../../lib/utils.js:62:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
[XCUITest] Error: Xcode version '0.1'. Support for Xcode 0.1 is not supported. Please upgrade to version 7.3 or higher
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at getAndCheckXcodeVersion$ (../../lib/utils.js:62:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
 Error: Xcode version '0.1'. Support for Xcode 0.1 is not supported. Please upgrade to version 7.3 or higher
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at getAndCheckXcodeVersion$ (../../lib/utils.js:62:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[MJSONWP] Encountered internal error running command: Error: Xcode version '0.1'. Support for Xcode 0.1 is not supported. Please upgrade to version 7.3 or higher
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at getAndCheckXcodeVersion$ (../../lib/utils.js:62:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

## Code To Reproduce Issue [ Good To Have ]

I am not able to launch app from Eclipse IDE in simulator and getting the above issue.

**Comment by mykola-mokhnach** [comment]
Appium 1.7.1 is out of date and does not support newer Xcode versions. Closed as duplicate

**Comment by sushreetech** [comment]
I have updated the appium version to 1.9.1, but still not working.

**Comment by mykola-mokhnach** [comment]
`not working` is not very helpful. Any logs?
