### ISSUE TITLE
Getting NoSuchElementException when I try to execute an iOS script in appium. 

### ISSUE THREAD

**Issue by srikantharuban** [appium/appium#11921]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by srikantharuban** [comment]
Script Details 

Page object details 

@iOSXCUITBy(xpath="//XCUIElementTypeStaticText[@name=\"John Appleseed\"]")
public IOSElement e;

Capability details 
DesiredCapabilities cap = new DesiredCapabilities();
                 cap.setCapability("platformName", "iOS");
		cap.setCapability("platformVersion", "12.1");
		cap.setCapability("deviceName", "iPhone XR (12.1)");
		cap.setCapability("udid", "5A972FE2-30B7-450E-BAC4-D36008CAD0B8");
		cap.setCapability("bundleId", "com.apple.MobileAddressBook");
		cap.setCapability("automationName", "XCUITest");

Appium version : Appium v1.9.1
Java client : 6.1.0
XCode : Version 10.1 (10B61)

Exception 

[RemoteTestNG] detected TestNG version 6.14.3
Dec 31, 2018 8:38:41 AM io.appium.java_client.remote.AppiumCommandExecutor$1 lambda$0
INFO: Detected dialect: W3C
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by net.sf.cglib.core.ReflectUtils$1 (file:/Users/Srikanth/.m2/repository/cglib/cglib/3.2.6/cglib-3.2.6.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of net.sf.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
FAILED: testcase3
org.openqa.selenium.NoSuchElementException: Can't locate an element by this strategy: By.id: e
	at io.appium.java_client.pagefactory.AppiumElementLocator.findElement(AppiumElementLocator.java:126)
	at io.appium.java_client.pagefactory.interceptors.InterceptorOfASingleElement.intercept(InterceptorOfASingleElement.java:60)
	at io.appium.java_client.ios.IOSElement$$EnhancerByCGLIB$$d311658.click(<generated>)
	at com.mobilepoc.qa.pages.ContactPageIos.clickContactItem(ContactPageIos.java:40)
	at mobilepoc.Testsuite.testcase3(Testsuite.java:52)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: org.openqa.selenium.TimeoutException: Expected condition failed: waiting for io.appium.java_client.pagefactory.AppiumElementLocator$WaitingFunction@6999cd39 (tried for 1 second(s) with 500 milliseconds interval)
	at org.openqa.selenium.support.ui.FluentWait.timeoutException(FluentWait.java:303)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:271)
	at io.appium.java_client.pagefactory.AppiumElementLocator.waitFor(AppiumElementLocator.java:99)
	at io.appium.java_client.pagefactory.AppiumElementLocator.findElement(AppiumElementLocator.java:119)
	... 29 more
Caused by: org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters.
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'Srikantharubans-MacBook-Pro.local', ip: 'fe80:0:0:0:1066:966c:5cd4:f6b5%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14', java.version: '10'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities {automationName: XCUITest, browserName: , bundleId: com.apple.MobileAddressBook, databaseEnabled: false, deviceName: iPhone XR (12.1), javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: false, platform: MAC, platformName: iOS, platformVersion: 12.1, takesScreenshot: true, udid: 5A972FE2-30B7-450E-BAC4-D36..., webStorageEnabled: false}
Session ID: 566a307d-7b32-4621-ace8-4be24944de76
*** Element info: {Using=id, value=e}
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:231)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:317)
	at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:62)
	at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.findElement(IOSDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementById(RemoteWebDriver.java:363)
	at io.appium.java_client.DefaultGenericMobileDriver.findElementById(DefaultGenericMobileDriver.java:70)
	at io.appium.java_client.AppiumDriver.findElementById(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.findElementById(IOSDriver.java:1)
	at org.openqa.selenium.By$ById.findElement(By.java:188)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:309)
	at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:58)
	at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.findElement(IOSDriver.java:1)
	at io.appium.java_client.pagefactory.bys.ContentMappedBy.findElement(ContentMappedBy.java:50)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:309)
	at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:58)
	at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.findElement(IOSDriver.java:1)
	at io.appium.java_client.pagefactory.AppiumElementLocator.lambda$0(AppiumElementLocator.java:120)
	at io.appium.java_client.pagefactory.AppiumElementLocator$WaitingFunction.apply(AppiumElementLocator.java:172)
	at io.appium.java_client.pagefactory.AppiumElementLocator$WaitingFunction.apply(AppiumElementLocator.java:1)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:248)
	... 31 more


===============================================
    Default test
    Tests run: 1, Failures: 1, Skips: 0
===============================================


===============================================
Default suite
Total tests run: 1, Failures: 1, Skips: 0
===============================================

**Comment by KazuCocoa** [comment]
What page source you could get in the view and appium log?

**Comment by mykola-mokhnach** [comment]
I don't observe any errors in the log. The element with the given id simply does not  exist

**Comment by srikantharuban** [comment]
If you observe my Page object code I have used xpath as a locator, However error is trigger for Id. Please find my locator code below. 

@iOSXCUITBy(xpath="//XCUIElementTypeStaticText[@name="John Appleseed"]")
public IOSElement e;

**Comment by KazuCocoa** [comment]
You sent `{"using":"id","value":"e"}` to the server. What about using `iOSXCUITFindBy` instead of `iOSXCUITBy`?
(I'm not familiar with Java client implementation. I could see examples by `iOSXCUITFindBy` than `iOSXCUITBy`.)

```
[info] [HTTP] <-- GET /wd/hub/session/19ac7db1-3f90-4a5e-996b-0bfb24c35db7/context 200 6 ms - 22
[info] [HTTP] 
[info] [HTTP] --> POST /wd/hub/session/19ac7db1-3f90-4a5e-996b-0bfb24c35db7/element
[info] [HTTP] {"using":"id","value":"e"}
[debug] [W3C] Calling AppiumDriver.findElement() with args: ["id","e","19ac7db1-3f90-4a5e-996b-0bfb24c35db7"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 5000 ms for condition
[debug] [JSONWP Proxy] Matched '/element' to command name 'findElement'
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/2D05C984-6B6D-4EE5-8BA3-AD296FA3989A/element] with body: {"using":"id","value":"e"}
[info] [Xcode]     t = 79617.58s Find the Application 'com.apple.MobileAddressBook'
[info] [Xcode] 
[info] [Xcode]     t = 79617.58s     Snapshot accessibility hierarchy for app with pid 10409
[info] [Xcode] 
[info] [Xcode]     t = 79617.63s Snapshot accessibility hierarchy for app with pid 10409
[info] [Xcode] [info] [Xcode]     t = 79617.68s Find: Descendants matching type Any
[info] [Xcode] 
[info] [Xcode]     t = 79617.68s Find: Elements matching predicate '"e" IN identifiers'
[info] [Xcode] 
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"using":"id","value":"e","description":"unable to find an element"},"sessionId":"2D05C984-6B6D-4EE5-8BA3-AD296FA3989A","status":7}
[debug] [MJSONWP] Matched JSONWP error code 7 to NoSuchElementError
```

This issue looked Java client issue if this had an issue since the client sent `id` locator.
Can you report this in https://github.com/appium/java-client or ask the usage in [forum](https://discuss.appium.io/)?

**Comment by srikantharuban** [comment]
Thanks.. with @iOSXCUITFindBy I can continue my scripting. I will report above issue in java client forum.
