### ISSUE TITLE
chromeOptions is not accepting argument, unable to start Chromedriver session when switching from NATIVE to WEBVIEW

### ISSUE THREAD

**Issue by ABoterberg** [appium/appium#11958]
## The problem

I'm testing a feature where the app opens a browser window, I 'tap' succes and return to the app.

At first I had forgotten to add the chromeOptions (com.android.chrome), since I added this i keep getting the next error:
```
[Chromedriver] Error: Failed to start Chromedriver session: invalid argument: cannot parse capability: chromeOptions
[Chromedriver] from invalid argument: unrecognized chrome option: 0
[Chromedriver]   (Driver info: chromedriver=2.45.615291 (ec3682e3c9061c10f26ea9e5cdcf3c53f3f74387),platform=Windows NT 10.0.17134 x86_64)
[Chromedriver]     at Object.wrappedLogger.errorAndThrow (C:\Users\boteral\AppData\Roaming\npm\node_modules\appium\node_modules\appium-support\lib\logging.js:78:13)
[Chromedriver]     at C:\Users\boteral\AppData\Roaming\npm\node_modules\appium\node_modules\appium-chromedriver\lib\chromedriver.js:478:13
[Chromedriver] Chromedriver exited unexpectedly with code null, signal SIGTERM
[debug] [Chromedriver] Changed state to 'stopped'
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.10.0
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): v10.10.0
* Mobile platform/version under test: android 8.0
* Real device or emulator/simulator: Real Device (Huawei P20Lite)
* Appium CLI or Appium.app|exe: intelliJ + some CLI

## Details

I have tried different combinations of dependencies and chromeOptions, yet the issue persists.

## Link to Appium logs

<script src="https://gist.github.com/ABoterberg/7ad2eaf4186d8aa0ffd2ecb8e6e3df32.js"></script>

## Code To Reproduce Issue [ Good To Have ]

capabilities:
```
private DesiredCapabilities defaultAndroidCaps() {
        DesiredCapabilities caps = new DesiredCapabilities();
        caps.setCapability(MobileCapabilityType.APP, ArtifactoryDownloader.getOutputDirectory().resolve("app-stubs-debug.apk").toAbsolutePath().toString());
        caps.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.ANDROID_UIAUTOMATOR2);
        caps.setCapability(AndroidMobileCapabilityType.APP_ACTIVITY, "be.argenta.bankieren.ui.flows.login.SplashActivity");
        caps.setCapability(AndroidMobileCapabilityType.APP_PACKAGE, "be.argenta.bankieren.stub");
        caps.setCapability(AndroidMobileCapabilityType.IGNORE_UNIMPORTANT_VIEWS, true);
        caps.setCapability(AndroidMobileCapabilityType.NO_SIGN, true);
        caps.setCapability(AndroidMobileCapabilityType.SYSTEM_PORT, getAndroidProps().getSystemPort());


       caps.setCapability(AndroidMobileCapabilityType.CHROME_OPTIONS, "com.android.chrome");
       // caps.setCapability(AndroidMobileCapabilityType.CHROME_OPTIONS,"androidPackage");

        System.setProperty("webdriver.chrome.driver","C:\\Users\\boteral\\node_modules\\appium-android-driver\\node_modules\\appium-chromedriver\\chromedriver\\win\\chromedriver.exe");


        return caps;
    }
```

actual code:
```
package be.argenta.digital.testing.pages.accounts;

import be.argenta.digital.testing.pages.AbstractPage;
import io.appium.java_client.AppiumDriver;
import io.appium.java_client.MobileElement;
import io.appium.java_client.pagefactory.AndroidFindBy;
import javafx.scene.web.WebView;

import java.util.Set;

public class ConsentAuthorizationWebPage extends AbstractPage {

    @AndroidFindBy(xpath = "//*[className = 'View'][contains(@text 'SUCCES')]")
    private MobileElement SUCCES;

    public ConsentAuthorizationWebPage(AppiumDriver driver) {
        super(driver);
    }

    public ConsentAuthorizationWebPage changeContextAndVerify(){

        new ConsentAuthorizationWebPage(driver);

        driver.getContextHandles();

        Set<String> contextNames = driver.getContextHandles();
        // driver.context((String) contextNames.toArray()[2]); // crasht op array.
        System.out.println(contextNames);

        driver.context("WEBVIEW_chrome");

                System.out.println(" ");
                System.out.println("if this prints we're guud");
                System.out.println(" ");
                //TODO how to click SUCCES?

        driver.context("NATIVE_APP");
        return this;




        //ChromeOptions options = new ChromeOptions();
        //options.addArguments("'androidPackage': 'com.android.chrome'");

//        WebView webview = new WebView(this);
//        setContentView(webview);
//
//        WebView.setWebContentsDebuggingEnabled(true);
//        webview.setWebViewClient(new WebViewClient());
//        webview.setEnabled(true);

//        DesiredCapabilities caps = new DesiredCapabilities();
//        ChromeOptions chromeOpts = new ChromeOptions();
//        chromeOpts.setCapability("androidPackage", "com.android.chrome");
//        caps.setCapability(AndroidMobileCapabilityType.CHROME_OPTIONS, chromeOpts);


        //System.out.println(driver.getPageSource());


        //driver.context("WEBVIEW_chrome");


        //driver.context("NATIVE_APP");

    }

    }

```

**Comment by imurchie** [comment]
Appium expects `chromeOptions` to be a hash, not a string.

This is sending a string:
```java
caps.setCapability(AndroidMobileCapabilityType.CHROME_OPTIONS, "com.android.chrome");
```

You need something along the lines of:
```java
ChromeOptions co = new ChromeOptions();
co. setCapability("androidPackage", "com.android.chrome");
caps.setCapability(AndroidMobileCapabilityType.CHROME_OPTIONS, co);
```

See https://sites.google.com/a/chromium.org/chromedriver/capabilities

**Comment by imurchie** [comment]
I don't think you want _all_ the desired capabilities sent as ChromeOptions, since ChromeDriver does not accept everything Appium does, and will error out if they are wrong.

But you could try!

I'm not sure what this line is doing:
```java
ChromeDriver cDriver = new ChromeDriver(options);
```

**Comment by ABoterberg** [comment]
It was a remnant from the whole day googling and coding, I must have looked over it.
I think I now only need to set the browserName to null, since it won't play with my appPackage and it's filled out automatically i guess? Once I get this running I'll get back.
Thank you for your time!

**Comment by imurchie** [comment]
Sorry for the time spent. ChromeDriver is an odd thing, if you need to configure it.

Hopefully it will work with the bare minimum.

**Comment by mykola-mokhnach** [comment]
Closed as inactive
