### ISSUE TITLE
Failed to take element screenshot in Espresso because of converting WMJSON url

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium#11988]
## The problem

`appium@beta` converts as below for taking element screenshot. Espresso has no MJSONWP protocol mapping so it should not convert it _or_ we should prepare the mapping in Espresso driver for this converter.

```
[HTTP] --> GET /wd/hub/session/4f9bc8c9-23e2-46e1-bea2-7da5ad6af11d/element/77b0bf3b-9f50-428b-bfb4-639358930ff7/screenshot
[HTTP] {}
[W3C (4f9bc8c9)] Driver proxy active, passing request on via HTTP proxy
[debug] [WD Proxy] Matched '/wd/hub/session/4f9bc8c9-23e2-46e1-bea2-7da5ad6af11d/element/77b0bf3b-9f50-428b-bfb4-639358930ff7/screenshot' to command name 'getElementScreenshot'
[Protocol Converter] Rewrote the original URL '/wd/hub/session/4f9bc8c9-23e2-46e1-bea2-7da5ad6af11d/element/77b0bf3b-9f50-428b-bfb4-639358930ff7/screenshot' to '/wd/hub/session/4f9bc8c9-23e2-46e1-bea2-7da5ad6af11d/screenshot/77b0bf3b-9f50-428b-bfb4-639358930ff7' for MJSONWP protocol
[debug] [WD Proxy] Proxying [GET /wd/hub/session/4f9bc8c9-23e2-46e1-bea2-7da5ad6af11d/screenshot/77b0bf3b-9f50-428b-bfb4-639358930ff7] to [GET http://localhost:8200/session/4c77b29b-5f5a-49a1-9f70-d138408b4392/screenshot/77b0bf3b-9f50-428b-bfb4-639358930ff7] with body: {}
[debug] [W3C (4f9bc8c9)] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: 500 - "{\"id\":\"9a056096-7a4e-468f-933c-e8ef80433ca5\",\"sessionId\":null,\"status\":13,\"value\":\"No such route /session/4c77b29b-5f5a-49a1-9f70-d138408b4392/screenshot/77b0bf3b-9f50-428b-bfb4-639358930ff7\"}"
[debug] [W3C (4f9bc8c9)]     at JWProxy.proxy (/Users/kazuaki/.nodebrew/node/v9.3.0/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:180:13)
[debug] [W3C (4f9bc8c9)]     at <anonymous>
[debug] [MJSONWP] Matched JSONWP error code 13 to UnknownError
[HTTP] <-- GET /wd/hub/session/4f9bc8c9-23e2-46e1-bea2-7da5ad6af11d/element/77b0bf3b-9f50-428b-bfb4-639358930ff7/screenshot 500 60 ms - 954
[HTTP]
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.10.0, 1.11.0
* Last Appium version that did not exhibit the issue (if applicable): ??
* Desktop OS/version used to run Appium: mac os
* Node.js version (unless using Appium.app|exe): 10.11
* Mobile platform/version under test: android 8.1
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: cli

## Details

An error client got

```
> @driver.take_element_screenshot(e, 'take_element_screenshot.png')
Selenium::WebDriver::Error::UnknownError: An unknown server-side error occurred while processing the command. Original error: No such route /session/d14eb9c9-773f-45af-b072-1ccdfbbdaade/screenshot/d6d58a34-844f-440c-af4e-7661669eb33b
from UnknownError: An unknown server-side error occurred while processing the command. Original error: No such route /session/d14eb9c9-773f-45af-b072-1ccdfbbdaade/screenshot/d6d58a34-844f-440c-af4e-7661669eb33b
[3] pry(#<AppiumLibCoreTest::Android::DeviceTest>)> 
```

## Link to Appium logs

https://gist.github.com/KazuCocoa/84aea30b16eadc374365dbff626df86d

## Code To Reproduce Issue [ Good To Have ]

Call W3C taking element screenshot command like `/wd/hub/session/4f9bc8c9-23e2-46e1-bea2-7da5ad6af11d/element/77b0bf3b-9f50-428b-bfb4-639358930ff7/screenshot`

**Comment by KazuCocoa** [comment]
`this.downstreamProtocol` was `MJSONWP` then.
https://github.com/appium/appium-base-driver/blob/ee17aef91c6e0dbaee67ca1836d1e1371a107e8d/lib/jsonwp-proxy/protocol-converter.js

**Comment by KazuCocoa** [comment]
The response had `status`, so the converter thought it was MJSONWP

```
TTP] --> POST /wd/hub/session/05ba71d5-a371-43f9-8886-6ac4d38b4384/element
[HTTP] {"using":"accessibility id","value":"App"}
[debug] [W3C (05ba71d5)] Calling AppiumDriver.findElement() with args: ["accessibility id","App","05ba71d5-a371-43f9-8886-6ac4d38b4384"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 30000 ms for condition
[debug] [WD Proxy] Matched '/element' to command name 'findElement'
[debug] [WD Proxy] Proxying [POST /element] to [POST http://localhost:8200/wd/hub/session/900af47c-6de4-4a61-b378-97b178115315/element] with body: {"strategy":"accessibility id","selector":"App","context":"","multiple":false}
[debug] [WD Proxy] Got response with status 200: {"sessionId":"900af47c-6de4-4a61-b378-97b178115315","status":0,"value":{"ELEMENT":"941e831b-5d7a-4597-93d8-e5fd0b0992e6"}}
[debug] [W3C (05ba71d5)] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"941e831b-5d7a-4597-93d8-e5fd0b0992e6","ELEMENT":"941e831b-5d7a-4597-93d8-e5fd0b0992e6"}
[HTTP] <-- POST /wd/hub/session/05ba71d5-a371-43f9-8886-6ac4d38b4384/element 200 10271 ms - 137
[HTTP] 
[HTTP] --> GET /wd/hub/session/05ba71d5-a371-43f9-8886-6ac4d38b4384/element/941e831b-5d7a-4597-93d8-e5fd0b0992e6/screenshot
[HTTP] {}
```

**Comment by anuragipankaj** [comment]
i am facing same issue with appium version 1.14 with browserstack, any idea how to solve this ?

logs :
2019-11-20 09:54:19:712 - [MJSONWP (539d5cc2)] Driver proxy active, passing request on via HTTP proxy
2019-11-20 09:54:19:715 - [debug] [WD Proxy] Matched '/wd/hub/session/539d5cc2-4900-4769-ba78-29969a50d5aa/element/0.6852753992753218-1/screenshot' to command name 'getElementScreenshot'
2019-11-20 09:54:19:715 - [Protocol Converter] Rewrote the original URL '/wd/hub/session/539d5cc2-4900-4769-ba78-29969a50d5aa/element/0.6852753992753218-1/screenshot' to '/wd/hub/session/539d5cc2-4900-4769-ba78-29969a50d5aa/screenshot/0.6852753992753218-1' for MJSONWP protocol
2019-11-20 09:54:19:715 - [debug] [WD Proxy] Proxying [GET /wd/hub/session/539d5cc2-4900-4769-ba78-29969a50d5aa/screenshot/0.6852753992753218-1] to [GET http://127.0.0.1:18080/wd/hub/session/0c4e04a00daa128ed41a2e5638a25baa/screenshot/0.6852753992753218-1] with body: {"scroll":true}
2019-11-20 09:54:19:718 - [WD Proxy] Got an unexpected response: unknown command: session/0c4e04a00daa128ed41a2e5638a25baa/screenshot/0.6852753992753218-1
2019-11-20 09:54:19:718 - [debug] [MJSONWP (539d5cc2)] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: 404 - "unknown command: session/0c4e04a00daa128ed41a2e5638a25baa/screenshot/0.6852753992753218-1"
2019-11-20 09:54:19:718 - [debug] [MJSONWP (539d5cc2)]     at doJwpProxy (/usr/local/.browserstack/appium_1.14.0_bstack/node_modules/appium-base-driver/lib/protocol/protocol.js:547:13)

**Comment by KazuCocoa** [comment]
Could you ask the browserstack team?
Your path like `0c4e04a00daa128ed41a2e5638a25baa/screenshot/0.6852753992753218-1` is different from vanilla Appium like below. I assume they customise the path.

### Appium 1.14.1, espresso-driver
- w3c
```
[HTTP]
[HTTP] --> GET /wd/hub/session/2a8d916f-2173-42d2-a5df-e9094fee10a5/element/18261503-115b-4c71-8673-5c15e7de7839/screenshot
[HTTP] {}
[W3C (2a8d916f)] Driver proxy active, passing request on via HTTP proxy
[debug] [WD Proxy] Matched '/wd/hub/session/2a8d916f-2173-42d2-a5df-e9094fee10a5/element/18261503-115b-4c71-8673-5c15e7de7839/screenshot' to command name 'getElementScreenshot'
[Protocol Converter] Rewrote the original URL '/wd/hub/session/2a8d916f-2173-42d2-a5df-e9094fee10a5/element/18261503-115b-4c71-8673-5c15e7de7839/screenshot' to '/wd/hub/session/2a8d916f-2173-42d2-a5df-e9094fee10a5/screenshot/18261503-115b-4c71-8673-5c15e7de7839' for MJSONWP protocol
[debug] [WD Proxy] Proxying [GET /wd/hub/session/2a8d916f-2173-42d2-a5df-e9094fee10a5/screenshot/18261503-115b-4c71-8673-5c15e7de7839] to [GET http://localhost:8200/session/64900bfc-ee78-4601-b65b-6cf3786b5c9e/screenshot/18261503-115b-4c71-8673-5c15e7de7839] with body: {}
[debug] [WD Proxy] Got response with status 200: "{\"id\":\"a66a8b11-4a24-4877-aeb5-d0eda11479e8\",\"sessionId\":\"64900bfc-ee78-4601-b65b-6cf3786b5c9e\",\"status\":0,\"value\":\"iVBORw0KGgoAAAANSUhEUgAABDgAAAB+CAYAAADBXqHtAAAABHNCSVQICAgIfAhkiAAABvFJREFU\\neJzt3U2o5XUdx/G341OGpuVApVIZmSZFGUklWkaDpPagjU6b1oG1cOGmh0246GERbVpYEAWRRTkw\\nZRiaiqZWuIgwFSFSyyKpxgoLNWlscc5l/nO8c+feuffMnf+Z1wsO/D//8zvf81t/+T0UAAAAAAAA\\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwEgctdkTmJPTqq8O8o+r727SXAAAAIA5O2azJzAn\\n26rzB3lr9YPq+c2ZDgAAADBPWzZ7AnOwpdox8+7M9m14AAAAAAtkERscb6vOXeb95Yd6IgAAAMCh\\nsYgNjsv28/6j1amHciIAAADAobFoDY6TqqsG+Yb2nrtxfPW+Qz4jAAAAYO4WrcFxcfWyQf5ekxtU\\nllzd4t4cAwAAAEesRbtF5crB853VE9Ut1fbpu/OrN1UPr7LeMdUZg/y36j/T5y3V2dVZTba+7Kl2\\nT2s/epjUBwAAgCPCIjU4Xt9kBceSpZUbv6z+3uSq2KpLW32D45QmjZIl11S3Ve+vrmvSgFjOr6ov\\nVQ9scn0AAAA4IizSFpVLBs...
[WD Proxy] Replacing sessionId 64900bfc-ee78-4601-b65b-6cf3786b5c9e with 2a8d916f-2173-42d2-a5df-e9094fee10a5
[HTTP] <-- GET /wd/hub/session/2a8d916f-2173-42d2-a5df-e9094fee10a5/element/18261503-115b-4c71-8673-5c15e7de7839/screenshot 200 42 ms - 2652
[HTTP]
```

- mjsonwp
```
[HTTP]
[HTTP] --> GET /wd/hub/session/52ae6977-3ace-4b41-80ff-08579b7a35c6/element/5bdd0b2d-dd9a-4e8b-9dd8-74e7667c0e17/screenshot
[HTTP] {}
[MJSONWP (52ae6977)] Driver proxy active, passing request on via HTTP proxy
[debug] [WD Proxy] Matched '/wd/hub/session/52ae6977-3ace-4b41-80ff-08579b7a35c6/element/5bdd0b2d-dd9a-4e8b-9dd8-74e7667c0e17/screenshot' to command name 'getElementScreenshot'
[Protocol Converter] Rewrote the original URL '/wd/hub/session/52ae6977-3ace-4b41-80ff-08579b7a35c6/element/5bdd0b2d-dd9a-4e8b-9dd8-74e7667c0e17/screenshot' to '/wd/hub/session/52ae6977-3ace-4b41-80ff-08579b7a35c6/screenshot/5bdd0b2d-dd9a-4e8b-9dd8-74e7667c0e17' for MJSONWP protocol
[debug] [WD Proxy] Proxying [GET /wd/hub/session/52ae6977-3ace-4b41-80ff-08579b7a35c6/screenshot/5bdd0b2d-dd9a-4e8b-9dd8-74e7667c0e17] to [GET http://localhost:8200/session/1f14f609-372a-49d1-9942-7bffead437c1/screenshot/5bdd0b2d-dd9a-4e8b-9dd8-74e7667c0e17] with body: {}
[debug] [WD Proxy] Got response with status 200: "{\"id\":\"bde3f90b-88ff-4654-bef4-f171e91fb825\",\"sessionId\":\"1f14f609-372a-49d1-9942-7bffead437c1\",\"status\":0,\"value\":\"iVBORw0KGgoAAAANSUhEUgAABDgAAAB+CAYAAADBXqHtAAAABHNCSVQICAgIfAhkiAAABvFJREFU\\neJzt3U2o5XUdx/G341OGpuVApVIZmSZFGUklWkaDpPagjU6b1oG1cOGmh0246GERbVpYEAWRRTkw\\nZRiaiqZWuIgwFSFSyyKpxgoLNWlscc5l/nO8c+feuffMnf+Z1wsO/D//8zvf81t/+T0UAAAAAAAA\\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwEgctdkTmJPTqq8O8o+r727SXAAAAIA5O2azJzAn\\n26rzB3lr9YPq+c2ZDgAAADBPWzZ7AnOwpdox8+7M9m14AAAAAAtkERscb6vOXeb95Yd6IgAAAMCh\\nsYgNjsv28/6j1amHciIAAADAobFoDY6TqqsG+Yb2nrtxfPW+Qz4jAAAAYO4WrcFxcfWyQf5ekxtU\\nllzd4t4cAwAAAEesRbtF5crB853VE9Ut1fbpu/OrN1UPr7LeMdUZg/y36j/T5y3V2dVZTba+7Kl2\\nT2s/epjUBwAAgCPCIjU4Xt9kBceSpZUbv6z+3uSq2KpLW32D45QmjZIl11S3Ve+vrmvSgFjOr6ov\\nVQ9scn0AAAA4IizSFpVLBs...
[WD Proxy] Replacing sessionId 1f14f609-372a-49d1-9942-7bffead437c1 with 52ae6977-3ace-4b41-80ff-08579b7a35c6
[HTTP] <-- GET /wd/hub/session/52ae6977-3ace-4b41-80ff-08579b7a35c6/element/5bdd0b2d-dd9a-4e8b-9dd8-74e7667c0e17/screenshot 200 53 ms - 2652
```
