### ISSUE TITLE
Emulator Calculator is shutting down every time it is opened by automation script(Appium+Eclipse+Android Studio)

### ISSUE THREAD

**Issue by Automation-TestAnalyst** [appium/appium#11981]
## The problem

Running the script to test addition operation of calculator of android  emulator  ,calculator opens but it shuts down before performing the addition .

## Environment

* Appium version (1.10) that exhibits the issue:
* Windows 10 used to run Appium:
* Mobile platform/version under test:Android 7.0
* emulator
*  Appium.
![appium](https://user-images.githubusercontent.com/46591654/51021704-4d796080-15a8-11e9-9763-36b236577308.png)
exe:

## Link to Appium logs

[W3C] Calling AppiumDriver.createSession() with args: [{"appActivity":"com.android.calculator2.Calculator","appPackage":"com.android.calculator2","platformName":"Android","deviceName":"Emulator"},null,{"firstMatch":[{"platformName":"android"}]}]
[BaseDriver] Event 'newSessionRequested' logged at 1547193245169 (13:24:05 GMT+0530 (India Standard Time))
[Appium] Could not parse W3C capabilities: 'deviceName' can't be blank
[Appium] Trying to fix W3C capabilities by merging them with JSONWP caps
[BaseDriver] The capabilities ["appActivity","appPackage","deviceName"] are not standard capabilities and should have an extension prefix
[Appium] Creating new AndroidDriver (v4.8.0) session
[Appium] Capabilities:
[Appium]   appActivity: com.android.calculator2.Calculator
[Appium]   appPackage: com.android.calculator2
[Appium]   deviceName: Emulator
[Appium]   platformName: android
[BaseDriver] W3C capabilities {"alwaysMatch":{"appium:app... and MJSONWP desired capabilities {"appActivity":"com.android... were provided
[BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"appium:app...
[BaseDriver] Session created with session id: 93fd8dfd-5577-4aa6-9b18-37cc31014bfa
[AndroidDriver] Java version is: 1.8.0_191
[AndroidDriver] Retrieving device list
[ADB] Trying to find a connected android device
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[AndroidDriver] Using device: emulator-5554
[ADB] Setting device id to emulator-5554
[ADB] Running 'C:\Users\username\SDK\platform-tools\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.sdk'
[ADB] Current device property 'ro.build.version.sdk': 24
[ADB] Device API level: 24
[AndroidDriver] Consider setting 'automationName' capability to 'uiautomator2' on Android >= 6, since UIAutomator framework is not maintained anymore by the OS vendor.
[AndroidDriver] App file was not listed, instead we're going to run com.android.calculator2 directly on the device
[AndroidDriver] Checking whether package is present on the device
[ADB] Running 'C:\Users\username\SDK\platform-tools\adb.exe -P 5037 -s emulator-5554 shell pm list packages com.android.calculator2'
[ADB] Running 'C:\Users\username\SDK\platform-tools\adb.exe -P 5037 -s emulator-5554 shell pm list packages com.android.calculator2'
[AndroidDriver] Shutting down Android driver
[AndroidDriver] Called deleteSession but bootstrap wasn't active
[ADB] Running 'C:\Users\username\SDK\platform-tools\adb.exe -P 5037 -s emulator-5554 shell am force-stop io.appium.unlock'
[ADB] Running 'C:\Users\username\SDK\platform-tools\adb.exe -P 5037 -s emulator-5554 shell am force-stop io.appium.unlock'
[BaseDriver] Event 'newSessionStarted' logged at 1547193328697 (13:25:28 GMT+0530 (India Standard Time))
[W3C] Encountered internal error running command: Error: Error executing adbExec. Original error: 'Command 'C\:\\Users\\username\\SDK\\platform-tools\\adb.exe -P 5037 -s emulator-5554 shell pm list packages com.android.calculator2' timed out after 20000ms'; Stderr: ''; Code: 'null'
[W3C]     at execFunc (C:\Users\username\AppData\Local\appium-desktop\app-1.10.0\resources\app\node_modules\appium-adb\lib\tools\system-calls.js:326:13)
[HTTP] <-- POST /wd/hub/session 500 83567 ms - 1148
[HTTP]

## Code To Reproduce Issue [ Good To Have ]

Written script in eclipse(Selenium java) 
import java.net.MalformedURLException;
import java.net.URL;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;

import io.appium.java_client.remote.AndroidMobileCapabilityType;
import io.appium.java_client.remote.MobileCapabilityType;

public class Calculator2 {

	public static void main(String[] args) throws MalformedURLException, InterruptedException {
		// TODO Auto-generated method stub

WebDriver driver;

	DesiredCapabilities capabilities = new DesiredCapabilities();
	capabilities.setCapability("deviceName","Emulator");
	capabilities.setCapability("platformName","Android");
	capabilities.setCapability("VERSION", "7.0"); 

	  capabilities.setCapability("appPackage", "com.android.calculator2");
	
		capabilities.setCapability("appActivity","com.android.calculator2.Calculator"); 

	   driver = new RemoteWebDriver(new URL("http://0.0.0.0:4723/wd/hub"), capabilities);
	   driver.manage().deleteAllCookies();

   //locate the Text on the calculator by using By.name()
	   driver.findElement(By.name("2")).click();
	   driver.findElement(By.name("+")).click();
	   driver.findElement(By.name("4")).click();
	   driver.findElement(By.name("=")).click();
	   
	//close the app
	driver.quit();

	}

}

**Comment by mykola-mokhnach** [comment]
> [W3C] Encountered internal error running command: Error: Error executing adbExec. Original error: 'Command 'C:\Users\username\SDK\platform-tools\adb.exe -P 5037 -s emulator-5554 shell pm list packages com.android.calculator2' timed out after 20000ms'; Stderr: ''; Code: 'null'
[W3C] at execFunc (C:\Users\username\AppData\Local\appium-desktop\app-1.10.0\resources\app\node_modules\appium-adb\lib\tools\system-calls.js:326:13)

It looks like the emulator is too slow. You can try to increase the `adbExecTimeout` capability value to workaround the problem.

Another problem:

> [AndroidDriver] Consider setting 'automationName' capability to 'uiautomator2' on Android >= 6, since UIAutomator framework is not maintained anymore by the OS vendor.

**Comment by Automation-TestAnalyst** [comment]
> increase the `adbExecTimeout` capability value to workaround the problem.

I have added capabilities that you told:
	capabilities.setCapability("adbExecTimeout","80000");
	capabilities.setCapability("automationName","uiautomator2");
But still it is not able to perform the addition operation.Given below are the appium logs:


[HTTP] --> POST /wd/hub/session/8c426f60-6806-42cb-b56c-032dd772412d/element
[HTTP] {"value":"*[name='2']","using":"css selector"}
[W3C (8c426f60)] Calling AppiumDriver.findElement() with args: ["css selector","*[name='2']","8c426f60-6806-42cb-b56c-032dd772412d"]
[BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[W3C (8c426f60)] Encountered internal error running command: InvalidSelectorError: Locator Strategy 'css selector' is not supported for this session
[W3C (8c426f60)]     at AndroidDriver.validateLocatorStrategy (C:\Users\username\AppData\Local\appium-desktop\app-1.10.0\resources\app\node_modules\appium-base-driver\lib\basedriver\driver.js:344:13)
[W3C (8c426f60)]     at AndroidDriver.helpers.findElOrElsWithProcessing (C:\Users\username\AppData\Local\appium-desktop\app-1.10.0\resources\app\node_modules\appium-base-driver\lib\basedriver\commands\find.js:28:8)
[W3C (8c426f60)]     at AndroidDriver.commands.findElement (C:\Users\username\AppData\Local\appium-desktop\app-1.10.0\resources\app\node_modules\appium-base-driver\lib\basedriver\commands\find.js:50:21)
[W3C (8c426f60)]     at curCommandCancellable._bluebird.default.resolve.then (C:\Users\username\AppData\Local\appium-desktop\app-1.10.0\resources\app\node_modules\appium-base-driver\lib\basedriver\driver.js:291:18)
[W3C (8c426f60)]     at tryCatcher (C:\Users\username\AppData\Local\appium-desktop\app-1.10.0\resources\app\node_modules\appium-base-driver\node_modules\bluebird\js\main\util.js:26:23)
[W3C (8c426f60)]     at Promise._settlePromiseFromHandler (C:\Users\username\AppData\Local\appium-desktop\app-1.10.0\resources\app\node_modules\appium-base-driver\node_modules\bluebird\js\main\promise.js:510:31)
[W3C (8c426f60)]     at Promise._settlePromiseAt (C:\Users\username\AppData\Local\appium-desktop\app-1.10.0\resources\app\node_modules\appium-base-driver\node_modules\bluebird\js\main\promise.js:584:18)
[W3C (8c426f60)]     at Promise._settlePromiseAtPostResolution (C:\Users\username\AppData\Local\appium-desktop\app-1.10.0\resources\app\node_modules\appium-base-driver\node_modules\bluebird\js\main\promise.js:248:10)
[W3C (8c426f60)]     at Async._drainQueue (C:\Users\username\AppData\Local\appium-desktop\app-1.10.0\resources\app\node_modules\appium-base-driver\node_modules\bluebird\js\main\async.js:128:12)
[W3C (8c426f60)]     at Async._drainQueues (C:\Users\username\AppData\Local\appium-desktop\app-1.10.0\resources\app\node_modules\appium-base-driver\node_modules\bluebird\js\main\async.js:133:10)
[W3C (8c426f60)]     at Immediate.Async.drainQueues (C:\Users\username\AppData\Local\appium-desktop\app-1.10.0\resources\app\node_modules\appium-base-driver\node_modules\bluebird\js\main\async.js:15:14)
[W3C (8c426f60)]     at runCallback (timers.js:696:18)
[W3C (8c426f60)]     at tryOnImmediate (timers.js:667:5)
[W3C (8c426f60)]     at processImmediate (timers.js:649:5)
[HTTP] <-- POST /wd/hub/session/8c426f60-6806-42cb-b56c-032dd772412d/element 400 5 ms - 2600
[HTTP] 
[UiAutomator2] Deleting UiAutomator2 session
[UiAutomator2] Deleting UiAutomator2 server session
[JSONWP Proxy] Matched '/' to command name 'deleteSession'
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Trying to proxy a session command without session id
[ADB] Running 'C:\Users\username\SDK\platform-tools\adb.exe -P 5037 -s emulator-5554 shell am force-stop com.android.calculator2'
[AndroidDriver] Not cleaning generated files. Add `clearSystemFiles` capability if wanted.
[ADB] Removing forwarded port socket connection: 8200 
[ADB] Running 'C:\Users\username\SDK\platform-tools\adb.exe -P 5037 -s emulator-5554 forward --remove tcp\:8200'
[ADB] Running 'C:\Users\username\SDK\platform-tools\adb.exe -P 5037 -s emulator-5554 forward --remove tcp\:8200'
[UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original error: 'Command 'C\:\\Users\\username\\SDK\\platform-tools\\adb.exe -P 5037 -s emulator-5554 forward --remove tcp\:8200' exited with code 1'; Stderr: 'error: listener 'tcp:8200' not found'; Code: '1''
[ADB] Device API level: 24
[BaseDriver] Event 'newSessionStarted' logged at 1547536290017 (12:41:30 GMT+0530 (India Standard Time))
[W3C] Encountered internal error running command: Error: Error executing adbExec. Original error: 'Command 'C\:\\Users\\username\\SDK\\platform-tools\\adb.exe -P 5037 -s emulator-5554 install C\:\\Users\\username\\AppData\\Local\\appium-desktop\\app-1.10.0\\resources\\app\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-v3.1.1.apk' timed out after 20000ms'; Stderr: ''; Code: 'null'
[W3C]     at execFunc (C:\Users\username\AppData\Local\appium-desktop\app-1.10.0\resources\app\node_modules\appium-adb\lib\tools\system-calls.js:326:13)
[HTTP] <-- POST /wd/hub/session 500 86677 ms - 1462
[HTTP]

**Comment by mykola-mokhnach** [comment]
Is mister banned from search?

https://github.com/appium/appium/search?q=%22is+not+supported+for+this+session%22&type=Issues
