### ISSUE TITLE
appium session not running

### ISSUE THREAD

**Issue by sateesh-voleti** [appium/appium#12005]
## The problem

i have connected android tab and set desired capabilities, later i had run session but throwing error:
An unknown server-side error occurred while processing the command, original error: Command 'java -version' exited with code 1

## Environment

* Appium-desktop version 1.10.0
* Desktop OS/version : windows 10
* Mobile platform/version under test: Android 7.0
* Real device:Yes
![appium](https://user-images.githubusercontent.com/31164928/51173660-f2f14480-18c6-11e9-9590-0d3c6c354969.jpg)

**Comment by Phoenix124** [comment]
@sateesh-voleti you nedd to attach logs, too little information

**Comment by sateesh-voleti** [comment]
Note, below the log from appium server
{"appActivity":"com.compulynx.core.android.dukamili.app.PinLogin","appPackage":"com.compulynx.core.android.dukamili","deviceName":"K706","noRest":true,"platformName":"Android","platformVersion":"7.0","udid":"867618750894363","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"appActivity":"com.compulynx.core.android.dukamili.app.PinLogin","appPackage":"com.compulynx.core.android.dukamili","deviceName":"K706","noRest":true,"platformName":"Android","platformVersion":"7.0","udid":"867618750894363","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1547556044320 (15:40:44 GMT+0300 (E. Africa Standard Time))
[Appium] Consider setting 'automationName' capability to 'UiAutomator2' on Android >= 6, since UIAutomator framework is not maintained anymore by the OS vendor.
[Appium] Creating new AndroidDriver (v4.8.0) session
[Appium] Capabilities:
[Appium]   appActivity: com.compulynx.core.android.dukamili.app.PinLogin
[Appium]   appPackage: com.compulynx.core.android.dukamili
[Appium]   deviceName: K706
[Appium]   noRest: true
[Appium]   platformName: Android
[Appium]   platformVersion: 7.0
[Appium]   udid: 867618750894363
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true
[BaseDriver] Creating session with MJSONWP desired capabilities: {"appActivity":"com.compuly...
[BaseDriver] The following capabilities were provided, but are not recognized by appium: noRest, connectHardwareKeyboard.
[BaseDriver] Session created with session id: 12e18d2e-db8d-497c-a28f-f5d835253088
[AndroidDriver] Shutting down Android driver
[AndroidDriver] Called deleteSession but bootstrap wasn't active
[BaseDriver] Event 'newSessionStarted' logged at 1547556044582 (15:40:44 GMT+0300 (E. Africa Standard Time))
[MJSONWP] Encountered internal error running command: Error: Command 'java -version' exited with code 1
[MJSONWP]     at ChildProcess.proc.on.code (C:\Program Files (x86)\Appium\resources\app\node_modules\teen_process\lib\exec.js:94:19)
[MJSONWP]     at ChildProcess.emit (events.js:182:13)
[MJSONWP]     at maybeClose (internal/child_process.js:961:16)
[MJSONWP]     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
[HTTP] <-- POST /wd/hub/session 500 270 ms - 179
[HTTP] 
[HTTP] --> DELETE /wd/hub/session
[HTTP] {}
[HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- DELETE /wd/hub/session 404 7 ms - 57
[HTTP] 
[appium-server-logs.txt](https://github.com/appium/appium/files/2759667/appium-server-logs.txt)

**Comment by Phoenix124** [comment]
@sateesh-voleti `[MJSONWP] Encountered internal error running command: Error: Command 'java -version' exited with code 1` - have you already install Java?

**Comment by sateesh-voleti** [comment]
Yes, i have installed, 
From cmd when i run java -version:

C:\Users\sateesh>java -version
Picked up _JAVA_OPTIONS: -Xms512m -Xmx1024m -XX:MaxPermSize=1024m
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=1024m; support was removed in 8.0
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

**Comment by KazuCocoa** [comment]
Below improves your capabilities.

> [Appium] Consider setting 'automationName' capability to 'UiAutomator2' on Android >= 6, since UIAutomator framework is not maintained anymore by the OS vendor.

> [BaseDriver] The following capabilities were provided, but are not recognized by appium: noRest, connectHardwareKeyboard.

---

What about running appium-doctor?

**Comment by KazuCocoa** [comment]
What about the result of appium-doctor? > yet same problem appearing,
http://appium.io/docs/en/about-appium/getting-started/

The capability is supported by xcuitest driver.

http://appium.io/docs/en/writing-running-appium/caps/
https://github.com/appium/appium-xcuitest-driver#desired-capabilities

**Comment by sateesh-voleti** [comment]
when i run appium-doctor:

C:\Users\sateesh>appium-doctor
info AppiumDoctor Appium Doctor v.1.7.0
info AppiumDoctor ### Diagnostic for necessary dependencies starting ###
info AppiumDoctor  ✔ The Node.js binary was found at: C:\Program Files\nodejs\node.EXE
info AppiumDoctor  ✔ Node version is 10.15.0
info AppiumDoctor  ✔ ANDROID_HOME is set to: C:\Users\sateesh\AppData\Local\Android\Sdk
info AppiumDoctor  ✔ JAVA_HOME is set to: C:\Program Files\Java\jdk1.8.0_181
info AppiumDoctor  ✔ adb exists at: C:\Users\sateesh\AppData\Local\Android\Sdk\platform-tools\adb.exe
info AppiumDoctor  ✔ android exists at: C:\Users\sateesh\AppData\Local\Android\Sdk\tools\android.bat
info AppiumDoctor  ✔ emulator exists at: C:\Users\sateesh\AppData\Local\Android\Sdk\tools\emulator.exe
info AppiumDoctor  ✔ Bin directory of %JAVA_HOME% is set
info AppiumDoctor ### Diagnostic for necessary dependencies completed, no fix needed. ###
info AppiumDoctor
info AppiumDoctor ### Diagnostic for optional dependencies starting ###
WARN AppiumDoctor  ✖ opencv4nodejs cannot be found.
info AppiumDoctor ### Diagnostic for optional dependencies completed, one fix needed. ###
info AppiumDoctor
info AppiumDoctor ### Optional Manual Fixes ###
info AppiumDoctor The configuration can install optionally. Please do the following manually:
WARN AppiumDoctor  ➜ Why opencv4nodejs is needed and how to install it is: https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/image-comparison.md
info AppiumDoctor
info AppiumDoctor ###
info AppiumDoctor
info AppiumDoctor Bye! Run appium-doctor again when all manual fixes have been applied!
info AppiumDoctor

**Comment by KazuCocoa** [comment]
mmm. Thanks!

@dpgraham Do you have any idea about the `java -version` error message?

**Comment by sateesh-voleti** [comment]
@KazuCocoa managed to find the root cause, i have removed java_options in the environment variables later it work and did not show error "java -version".
**Another issue,**
when i run appium session with desired capabilities, app is crashing in the device, appium side there is a error message:
An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.compulynx.core.android.pos' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: The permission to start 'com.compulynx.core.android.pos.app.PinLogin' activity has been denied.Make sure the activity/package names are correct.
i have atatched appium server log file, any idea on this
**I had removed android settings app from device later tried above scenario but same issue
[appium-server-logs.txt](https://github.com/appium/appium/files/2764302/appium-server-logs.txt)
**
