### ISSUE TITLE
Appium android device parallel execution in version 1.7.2

### ISSUE THREAD

**Issue by anuragpattanayak3** [appium/appium#12022]
## The problem

Whenever i try to run on multiple devices, it throws a server side error. i am using two separate command prompts to run appium server as well as to run the commands. i am using node.js framework to handle the operation.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium :windows 10
* Node.js version (unless using Appium.app|exe): 10.15.0
* Mobile platform/version under test: 8.0,8.1
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:

## Details

i am starting appium server in 2 different command prompt and trying to run on 2 different devices. i am using two different json files and 2 different desired capabilities for this execution. Here 1 step is throwing error and other one is getting failed by default. Refer to the screenshot for the failed steps.

## Link to Appium logs

An unknown server-side error occurred while processing the command. Original error: java.lang.IllegalThreadStateException
        at java.lang.Thread.start(Thread.java:724)
        at io.appium.uiautomator2.model.NotificationListener.start(NotificationListener.java:32)
        at io.appium.uiautomator2.model.Session.<init>(Session.java:23)
        at io.appium.uiautomator2.model.AppiumUiAutomatorDriver.initializeSession(AppiumUiAutomatorDriver.java:19)
        at io.appium.uiautomator2.handler.NewSession.safeHandle(NewSession.java:31)
        at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:56)
        at io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:208)
        at io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:199)
        at io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:44)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:552)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:466)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:764)

    at C:\Agent(NewPack)\agentins3\nwjs-sdk-v0.25.2-win-x64\AutomationCode\node_modules\wd\lib\webdriver.js:134:15
    at Request._callback (C:\Agent(NewPack)\agentins3\nwjs-sdk-v0.25.2-win-x64\AutomationCode\node_modules\wd\lib\http-utils.js:89:7)
    at Request.self.callback (C:\Agent(NewPack)\agentins3\nwjs-sdk-v0.25.2-win-x64\node_modules\request\request.js:198:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (C:\Agent(NewPack)\agentins3\nwjs-sdk-v0.25.2-win-x64\node_modules\request\request.js:1035:10)
    at Request.emit (events.js:187:15)
    at IncomingMessage.<anonymous> (C:\Agent(NewPack)\agentins3\nwjs-sdk-v0.25.2-win-x64\node_modules\request\request.js:962:12)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  data:
   '{"status":13,"value":{"message":"An unknown server-side error occurred while processing the command. Original error: java.lang.IllegalThreadStateException\\n\\tat java.lang.Thread.start(Thread.java:724)\\n\\tat io.appium.uiautomator2.model.NotificationListener.start(NotificationListener.java:32)\\n\\tat io.appium.uiautomator2.model.Session.<init>(Session.java:23)\\n\\tat io.appium.uiautomator2.model.AppiumUiAutomatorDriver.initializeSession(AppiumUiAutomatorDriver.java:19)\\n\\tat io.appium.uiautomator2.handler.NewSession.safeHandle(NewSession.java:31)\\n\\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:56)\\n\\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:208)\\n\\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:199)\\n\\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:44)\\n\\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\\n\\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\\n\\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\\n\\tat io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)\\n\\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\\n\\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\\n\\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\\n\\tat io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)\\n\\tat io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)\\n\\tat io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)\\n\\tat io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)\\n\\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\\n\\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\\n\\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\\n\\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)\\n\\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\\n\\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\\n\\tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)\\n\\tat io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)\\n\\tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)\\n\\tat io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:552)\\n\\tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:466)\\n\\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)\\n\\tat io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)\\n\\tat io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)\\n\\tat java.lang.Thread.run(Thread.java:764)\\n"},"sessionId":null}' }

## Code To Reproduce Issue [ Good To Have ]

var desiredcapabilities1=mydata.argodata.desiredCapabilitiesBS1;
var desiredcapabilities2=mydata.argodata.desiredCapabilitiesBS2;

var driver1= wd.promiseChainRemote({//driver initialization for appium
         host: "127.0.0.1",
         port: "4723"})

var driver2= wd.promiseChainRemote({//driver initialization for appium
    host: "127.0.0.2",
    port: "4724"})

if(desiredcapabilities1!=null){
    (driver1).init(desiredcapabilities1).then(function(){abcd1();driver=driver1;})
    .catch(function(err){
        console.log("err occured for 1st driver",err)
    })}
    if(desiredcapabilities2!=null){
        (driver2).init(desiredcapabilities2).then(function(){abcd1();driver=driver2;})
        .catch(function(err){
            console.log("err occured for 2nd driver",err)
        })}
![screenshot 3](https://user-images.githubusercontent.com/46106819/51298681-7a67c080-1a4b-11e9-8362-b0ae3c5d3367.png)

**Comment by mykola-mokhnach** [comment]
Version 1.7.2 is out of date. Please use the most recent one

**Comment by anuragpattanayak3** [comment]
Ok i will definitely try that out..thank you for the quick response
