### ISSUE TITLE
Sendkeys not working while entering hint text

### ISSUE THREAD

**Issue by Amrutha0a3** [appium/appium#12041]
## The problem
Sendkeys not working while entering hint text

## Environment
* Appium version :1.10.0
* Desktop OS/version used to run Appium: windows 7 64 bit
* Mobile platform/version under test: Android version 7 Redmi Y1
* Real device 

##  Appium logs
[HTTP] --> POST /wd/hub/session/cb48ef72-6774-4a71-be62-30322d8d6c9c/element/1/v
alue
[HTTP] {"id":"1","text":"abc","value":["a","b","c"]}
[debug] [W3C (cb48ef72)] Calling AppiumDriver.setValue() with args: [["a","b","c
"],"1","cb48ef72-6774-4a71-be62-30322d8d6c9c"]
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":
"element:setText","params":{"elementId":"1","text":"abc","replace":false}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":
"action","action":"element:setText","params":{"elementId":"1","text":"abc","repl
ace":false}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: setText
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using element passed in: 1
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Attempting to clear using UiO
bject.clearText().
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Text not cleared. Assuming re
mainder is hint text.
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Sending plain text to element
: abc
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":1
3,"value":"Unknown error"}
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [MJSONWP] Matched JSONWP error code 13 to UnknownError
[debug] [W3C (cb48ef72)] Encountered internal error running command: UnknownErro
r: An unknown server-side error occurred while processing the command. Original
error: Unknown error
[debug] [W3C (cb48ef72)] at errorFromMJSONWPStatusCode (C:\Users\Om\AppData
Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\err
ors.js:789:10)
[debug] [W3C (cb48ef72)] at Socket.socketClient.on.data (C:\Users\Om\AppData
\Roaming\npm\node_modules\appium\node_modules\appium-android-driver\lib\bootstra
p.js:139:18)
[debug] [W3C (cb48ef72)] at Socket.emit (events.js:182:13)
[debug] [W3C (cb48ef72)] at addChunk (_stream_readable.js:283:12)
[debug] [W3C (cb48ef72)] at readableAddChunk (_stream_readable.js:260:13)
[debug] [W3C (cb48ef72)] at Socket.Readable.push (_stream_readable.js:219:10
)
[debug] [W3C (cb48ef72)] at TCP.onStreamRead [as onread] (internal/stream_ba
se_commons.js:94:17)
[HTTP] <-- POST /wd/hub/session/cb48ef72-6774-4a71-be62-30322d8d6c9c/element/1/v
alue 500 107 ms - 869
[HTTP]

## Code To Reproduce Issue
MobileElement email = driver.findElementsByClassName("android.widget.EditText").get(0);
if (email.isDisplayed()) {
System.out.println("Element displayed");
email.click();
email.sendKeys("abc");}

**Comment by Amrutha0a3** [comment]
> UIA1 is considered deprecated for Android 6+. Switch to UIA2/Espresso automation backend
> 
> Closed as not an issue



> UIA1 is considered deprecated for Android 6+. Switch to UIA2/Espresso automation backend
> 
> Closed as not an issue

Thank you..it worked.but facing another issue while using click() function with UIA2

[debug] [JSONWP Proxy] Matched '/element/67c80d24-ffa3-4ae8-ab80-060fb2822d4e/cl
ick' to command name 'click'
[debug] [JSONWP Proxy] Proxying [POST /element/67c80d24-ffa3-4ae8-ab80-060fb2822
d4e/click] to [POST http://localhost:8202/wd/hub/session/6a11abb1-40e4-41c7-b62a
-a4a82d87e3b4/element/67c80d24-ffa3-4ae8-ab80-060fb2822d4e/click] with body: {"e
lement":"67c80d24-ffa3-4ae8-ab80-060fb2822d4e"}
[JSONWP Proxy] Got an unexpected response: {"sessionId":"6a11abb1-40e4-41c7-b62a
-a4a82d87e3b4","status":13,"value":"java.lang.SecurityException: Injecting to an
other application requires INJECT_EVENTS permission\n\tat android.os.Parcel.read
Exception(Parcel.java:1684)\n\tat android.os.Parcel.readException(Parcel.java:16
37)\n\tat android.ap...
[debug] [MJSONWP] Matched JSONWP error code 13 to UnknownError
[debug] [W3C (009533bd)] Encountered internal error running command: UnknownErro
r: An unknown server-side error occurred while processing the command. Original
error: java.lang.SecurityException: Injecting to another application requires IN
JECT_EVENTS permission
