### ISSUE TITLE
gradle-version-upgrade script fails on npm version bump

### ISSUE THREAD

**Issue by mykola-mokhnach** [appium/appium#12040]
`io.appium.settings$ npm version minor`

```
> io.appium.settings@2.13.0 bump-gradle-version /Users/elf/code/io.appium.settings
> gulp gradle-version-update --package-version=${npm_package_version} && git add app/build.gradle

[08:17:17] Using gulpfile ~/code/io.appium.settings/gulpfile.js
[08:17:17] Starting 'gradle-version-update'...
[08:17:17] Updating gradle build file to version name '2.13.0'
[08:17:17] Updated files: app/build.gradle
[08:17:17] 'gradle-version-update' errored after 27 ms
[08:17:17] TypeError: changes.join is not a function
    at logFileChanges (/Users/elf/code/io.appium.settings/node_modules/appium-gulp-plugins/lib/tasks/gradle.js:9:33)
    at /Users/elf/code/io.appium.settings/node_modules/appium-gulp-plugins/lib/tasks/gradle.js:53:5
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! io.appium.settings@2.13.0 bump-gradle-version: `gulp gradle-version-update --package-version=${npm_package_version} && git add app/build.gradle`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the io.appium.settings@2.13.0 bump-gradle-version script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/elf/.npm/_logs/2019-01-21T07_17_17_843Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! io.appium.settings@2.13.0 version: `npm run bump-gradle-version && npm run build && git add apks`
npm ERR! Exit status 1
```

**Comment by mykola-mokhnach** [comment]
Thanks @imurchie
