### ISSUE TITLE
- Appium is unable to find Webview context on android emulator

### ISSUE THREAD

**Issue by mvaranasi123** [appium/appium#12058]
## The problem

I am trying to test my ionic angular app using protractor and appium, though my screen has webview available, appium is not able to find it 

## Environment

* Appium version (or git revision) that exhibits the issue:1.10.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: win 10
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: android 
* Real device or emulator/simulator:Android simulator 
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/mvaranasi123/a76ebde66e594dae99c8bbd448067503

## Code To Reproduce Issue [ Good To Have ]

My below script is failing with  a No SUCH CONTEXT FOUND error. I am sure there is web view available and able to find it with uiautomator viewer.

exports.config = {
    seleniumAddress: 'http://localhost:4723/wd/hub', //appium

    capabilities: { 
  browserName: '',
  //browser.driver:'chromedriver'
  'unicodeKeyboard': true,
  'resetKeyboard': true,
   autoWebview: true,
  deviceContext: '',
  autoWebviewTimeout: 20000,
  platformName: 'Android',
  deviceName: 'Nexus 5X API 25',
  app: 'C:\\Users\\mvaranasi\\Documents\\{{app path}}',
  'app-package': 'com.{{package name}}
  'app-activity': 'MainActivity',
  autoAcceptAlerts: true,
  autoGrantPermissions: 'true',
  newCommandTimeout: 500000,
  BaseUrl :'http://localhost:8100/#/login'
},

  // Framework to use. Jasmine is recommended.
  framework: 'jasmine',
  

  // Spec patterns are relative to the current working directory when
  // protractor is called.s
  specs: ['example_spec.js'],

  // Options to be passed to Jasmine.
  jasmineNodeOpts: {
    defaultTimeoutInterval: 100000
  },

**Comment by mvaranasi123** [comment]
any one facing the similar issue? or do you need some more details, let me know?

**Comment by mvaranasi123** [comment]
@mykola-mokhnach mykola-mokhnach  let me know if you need any more information from me

**Comment by rahulpatidar0191** [comment]
@mvaranasi123 , Did you manage to fix this issue? I am facing the exact same errors

**Comment by mvaranasi123** [comment]
well... No... Not yet, Looking out for help on this issue.From appium guys, or from some one who faced it and fixed the error.

**Comment by rahulpatidar0191** [comment]
@mvaranasi123 , which version of appium did  you use that did not face this issue?

**Comment by mvaranasi123** [comment]
Itried 1.7.2, 1.9.1, 1.10.1  versions of appium in all the version i faced this issue, am new to this stuff(in learning stage).

**Comment by mvaranasi123** [comment]
Rahul,

Did you resolve this issue?if so, please provide your steps to resolution.

Thanks in advance

-Madhavi

**Comment by rahulpatidar0191** [comment]
After doing some research and then trying it out myself I noticed that I cannot use protractor as a test runner for Native android apps, So I switched to pytest for now

**Comment by mvaranasi123** [comment]
ok, Thanks for the update and Good luck with pytest.

-Madhavi

**Comment by mykola-mokhnach** [comment]
Closed as inactive

**Comment by mvaranasi123** [comment]
This issue is not addressed, closing the bug is not making sense to me

**Comment by mvaranasi123** [comment]
Any plan to address this type of issue? Do you guys need any more details? Please let me know the plan

**Comment by khandelwalgarima** [comment]
Tried with appium 1.12.1 and seeing same issue. Any pointers or help appreciated

**Comment by rohitv-iprogrammer** [comment]
Facing the same issue with using protractor with appium application gets launched but giving error

**Comment by mvaranasi123** [comment]
@rohitv-iprogrammer   I am using like the same with protractor and  appium for mobile automation. let me know if you find a way to fix this

**Comment by khandelwalgarima** [comment]
@mvaranasi123 @rohitv-iprogrammer  I am using uiAutomator for web view automation and it is working fine.

**Comment by mvaranasi123** [comment]
@khandelwalgarima  I am using protractor and appium together for running my mobile test script on my angular app, so cant use ui automator viewer, if you also using the same combination, please help me with more details

**Comment by imurchie** [comment]
Please provide the _full_ server logs. There is lots of information that is necessary to make any sort of evaluation. As it is there is little to say.

**Comment by mvaranasi123** [comment]
I had already added the appium log.
Protractor log:

C:\Users\mvaranasi\eclipse-workspace\Drylink2>protractor conf.js
[13:51:52] I/launcher - Running 1 instances of WebDriver
[13:51:52] I/hosted - Using the selenium server at http://localhost:4723/wd/hub
[13:52:48] E/launcher - No such context found.
[13:52:48] E/launcher - WebDriverError: No such context found.
    at Object.checkLegacyResponse (C:\Users\mvaranasi\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:546:15)
    at parseHttpResponse (C:\Users\mvaranasi\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:509:13)
    at doSend.then.response (C:\Users\mvaranasi\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:441:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
From: Task: WebDriver.createSession()
    at Function.createSession (C:\Users\mvaranasi\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:769:24)
    at createDriver (C:\Users\mvaranasi\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\index.js:170:33)
    at Builder.build (C:\Users\mvaranasi\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\index.js:635:14)
    at Hosted.getNewDriver (C:\Users\mvaranasi\AppData\Roaming\npm\node_modules\protractor\built\driverProviders\driverProvider.js:53:33)
    at Runner.createBrowser (C:\Users\mvaranasi\AppData\Roaming\npm\node_modules\protractor\built\runner.js:195:43)
    at q.then.then (C:\Users\mvaranasi\AppData\Roaming\npm\node_modules\protractor\built\runner.js:339:29)
    at _fulfilled (C:\Users\mvaranasi\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\mvaranasi\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\mvaranasi\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:796:13)
    at C:\Users\mvaranasi\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:556:49
[13:52:48] E/launcher - Process exited with error code 199

**Comment by mvaranasi123** [comment]
If you are looking for any other log, please let me know.

**Comment by mvaranasi123** [comment]
Hey Appium people,

Any update on this? or from anyone, Any work around for this problem?

**Comment by khandelwalgarima** [comment]
can you try
 Android.tap_by_coordinate(x, y)

**Comment by dav1dls** [comment]
Any update on this?

**Comment by thejuskrishna** [comment]
Install chrome browser and make it as default browser. Restart the emulator and try again.
