### ISSUE TITLE
"this.adb.getApplicationInstallState" error when starting tests on android

### ISSUE THREAD

**Issue by ania-s** [appium/appium#12061]
## The problem

When starting the tests on android with the latest appium version from mac (I wanted to verify a fix for capturing screenshots with appium-espresso-driver and webview app), the tests don't get started as I get the following error:
```
ERROR: An unknown server-side error occurred while processing the command. Original error: this.adb.getApplicationInstallState is not a function
```

Please find the appium logs below:
```
2019-01-23 07:41:24:701 [Appium] Welcome to Appium v1.11.0-rc.3
2019-01-23 07:41:24:702 [Appium] Non-default server args:
2019-01-23 07:41:24:702 [Appium]   logFile: ./build/appium.log
2019-01-23 07:41:24:702 [Appium]   relaxedSecurityEnabled: true
2019-01-23 07:41:24:725 [Appium] Appium REST http interface listener started on 0.0.0.0:4723
2019-01-23 07:41:25:538 [HTTP] --> POST /wd/hub/session
2019-01-23 07:41:25:538 [HTTP] {"desiredCapabilities":{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"automationName":"Espresso","forceEspressoRebuild":true,"appActivity":"com.abc.app.MainActivity","appPackage":"com.abc.app.internal","autoWebview":true,"maxInstances":1,"platformName":"Android","deviceName":"Galaxy Tab S3","app":"/Users/ania/abc/runtime/platform/runtime-android/app/build/outputs/apk/internal/debug/app-internal-debug.apk","metadata":{"browser":{"name":"chrome","version":"unknown"},"device":"Galaxy Tab S3","platform":{"name":"android","version":"8.0.0"}},"requestOrigins":{"url":"http://webdriver.io","version":"4.8.0","name":"webdriverio"}}}
2019-01-23 07:41:25:540 [MJSONWP] Calling AppiumDriver.createSession() with args: [{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"automationName":"Espresso","forceEspressoRebuild":true,"appActivity":"com.abc.app.MainActivity","appPackage":"com.abc.app.internal","autoWebview":true,"maxInstances":1,"platformName":"Android","deviceName":"Galaxy Tab S3","app":"/Users/ania/abc/runtime/platform/runtime-android/app/build/outputs/apk/internal/debug/app-internal-debug.apk","metadata":{"browser":{"name":"chrome","version":"unknown"},"device":"Galaxy Tab S3","platform":{"name":"android","version":"8.0.0"}},"requestOrigins":{"url":"http://webdriver.io","version":"4.8.0","name":"webdriverio"}},null,null]
2019-01-23 07:41:25:541 [BaseDriver] Event 'newSessionRequested' logged at 1548229285540 (08:41:25 GMT+0100 (Central European Standard Time))
2019-01-23 07:41:25:543 [Appium] Creating new EspressoDriver (v1.7.1) session
2019-01-23 07:41:25:543 [Appium] Capabilities:
2019-01-23 07:41:25:543 [Appium]   javascriptEnabled: true
2019-01-23 07:41:25:543 [Appium]   locationContextEnabled: true
2019-01-23 07:41:25:543 [Appium]   handlesAlerts: true
2019-01-23 07:41:25:543 [Appium]   rotatable: true
2019-01-23 07:41:25:543 [Appium]   automationName: Espresso
2019-01-23 07:41:25:544 [Appium]   forceEspressoRebuild: true
2019-01-23 07:41:25:544 [Appium]   appActivity: com.abc.app.MainActivity
2019-01-23 07:41:25:544 [Appium]   appPackage: com.abc.app.internal
2019-01-23 07:41:25:544 [Appium]   autoWebview: true
2019-01-23 07:41:25:550 [Appium]   maxInstances: 1
2019-01-23 07:41:25:550 [Appium]   platformName: Android
2019-01-23 07:41:25:550 [Appium]   deviceName: Galaxy Tab S3
2019-01-23 07:41:25:550 [Appium]   app: /Users/ania/abc/runtime/platform/runtime-android/app/build/outputs/apk/internal/debug/app-internal-debug.apk
2019-01-23 07:41:25:550 [Appium]   metadata: {
2019-01-23 07:41:25:550 [Appium]     browser: {
2019-01-23 07:41:25:551 [Appium]       name: chrome
2019-01-23 07:41:25:551 [Appium]       version: unknown
2019-01-23 07:41:25:551 [Appium]     }
2019-01-23 07:41:25:551 [Appium]     device: Galaxy Tab S3
2019-01-23 07:41:25:551 [Appium]     platform: {
2019-01-23 07:41:25:551 [Appium]       name: android
2019-01-23 07:41:25:551 [Appium]       version: 8.0.0
2019-01-23 07:41:25:551 [Appium]     }
2019-01-23 07:41:25:551 [Appium]   }
2019-01-23 07:41:25:552 [Appium]   requestOrigins: {
2019-01-23 07:41:25:552 [Appium]     url: http://webdriver.io
2019-01-23 07:41:25:552 [Appium]     version: 4.8.0
2019-01-23 07:41:25:552 [Appium]     name: webdriverio
2019-01-23 07:41:25:552 [Appium]   }
2019-01-23 07:41:25:555 [Appium] Applying relaxed security to 'EspressoDriver' as per server command line argument
2019-01-23 07:41:25:557 [BaseDriver] Creating session with MJSONWP desired capabilities: {"javascriptEnabled":true,"...
2019-01-23 07:41:25:561 [BaseDriver] The following capabilities were provided, but are not recognized by appium: javascriptEnabled, locationContextEnabled, handlesAlerts, rotatable, maxInstances, metadata, requestOrigins.
2019-01-23 07:41:25:562 [BaseDriver] Session created with session id: eb3288ac-eefa-4ef8-a0fa-7f68f95236b7
2019-01-23 07:41:25:579 [BaseDriver] Using local app '/Users/ania/abc/runtime/platform/runtime-android/app/build/outputs/apk/internal/debug/app-internal-debug.apk'
2019-01-23 07:41:25:579 [Espresso] Checking whether app is actually present
2019-01-23 07:41:25:581 [Espresso] EspressoDriver version: 1.7.1
2019-01-23 07:41:25:663 [AndroidDriver] Java version is: 1.8.0_191
2019-01-23 07:41:25:666 [ADB] Checking whether adb is present
2019-01-23 07:41:25:670 [ADB] Found 1 'build-tools' folders under '/Users/ania/Library/Android/sdk' (newest first):
2019-01-23 07:41:25:670 [ADB]     /Users/ania/Library/Android/sdk/build-tools/28.0.3
2019-01-23 07:41:25:671 [ADB] Using adb from /Users/ania/Library/Android/sdk/platform-tools/adb
2019-01-23 07:41:25:671 [AndroidDriver] Retrieving device list
2019-01-23 07:41:25:671 [ADB] Trying to find a connected android device
2019-01-23 07:41:25:672 [ADB] Getting connected devices...
2019-01-23 07:41:25:682 [ADB] 1 device(s) connected
2019-01-23 07:41:25:682 [AndroidDriver] Using device: 5b8beaf1
2019-01-23 07:41:25:683 [ADB] Setting device id to 5b8beaf1
2019-01-23 07:41:25:685 [ADB] Running '/Users/ania/Library/Android/sdk/platform-tools/adb -P 5037 -s 5b8beaf1 shell getprop ro.build.version.sdk'
2019-01-23 07:41:25:749 [ADB] Current device property 'ro.build.version.sdk': 26
2019-01-23 07:41:25:749 [ADB] Device API level: 26
2019-01-23 07:41:25:762 [ADB] Running '/Users/ania/Library/Android/sdk/platform-tools/adb -P 5037 -s 5b8beaf1 wait-for-device'
2019-01-23 07:41:25:775 [ADB] Running '/Users/ania/Library/Android/sdk/platform-tools/adb -P 5037 -s 5b8beaf1 shell echo ping'
2019-01-23 07:41:25:836 [AndroidDriver] Pushing settings apk to device...
2019-01-23 07:41:25:837 [ADB] Getting install status for io.appium.settings
2019-01-23 07:41:25:838 [ADB] Running '/Users/ania/Library/Android/sdk/platform-tools/adb -P 5037 -s 5b8beaf1 shell pm list packages io.appium.settings'
2019-01-23 07:41:26:498 [ADB] App is installed
2019-01-23 07:41:26:499 [ADB] Getting package info for 'io.appium.settings'
2019-01-23 07:41:26:499 [ADB] Running '/Users/ania/Library/Android/sdk/platform-tools/adb -P 5037 -s 5b8beaf1 shell dumpsys package io.appium.settings'
2019-01-23 07:41:26:588 [ADB] Checking whether aapt is present
2019-01-23 07:41:26:590 [ADB] Using aapt from /Users/ania/Library/Android/sdk/build-tools/28.0.3/aapt
2019-01-23 07:41:26:605 [ADB] The installed 'io.appium.settings' package does not require upgrade ('2.3.0' >= '2.3.0')
2019-01-23 07:41:26:606 [ADB] Running '/Users/ania/Library/Android/sdk/platform-tools/adb -P 5037 -s 5b8beaf1 shell ps'
2019-01-23 07:41:26:763 [AndroidDriver] io.appium.settings is already running. There is no need to reset its permissions.
2019-01-23 07:41:26:764 [ADB] Device API level: 26
2019-01-23 07:41:26:764 [ADB] Running '/Users/ania/Library/Android/sdk/platform-tools/adb -P 5037 -s 5b8beaf1 shell appops set io.appium.settings android\:mock_location allow'
2019-01-23 07:41:26:839 [AndroidDriver] setDeviceLanguageCountry requires language or country.
2019-01-23 07:41:26:840 [AndroidDriver] Got language: 'null' and country: 'null'
2019-01-23 07:41:26:841 [Logcat] Starting logcat capture
2019-01-23 07:41:26:917 [AndroidDriver] Pushing unlock helper app to device...
2019-01-23 07:41:26:918 [ADB] Getting install status for io.appium.unlock
2019-01-23 07:41:26:919 [ADB] Running '/Users/ania/Library/Android/sdk/platform-tools/adb -P 5037 -s 5b8beaf1 shell pm list packages io.appium.unlock'
2019-01-23 07:41:27:564 [ADB] App is installed
2019-01-23 07:41:27:564 [ADB] Getting package info for 'io.appium.unlock'
2019-01-23 07:41:27:564 [ADB] Running '/Users/ania/Library/Android/sdk/platform-tools/adb -P 5037 -s 5b8beaf1 shell dumpsys package io.appium.unlock'
2019-01-23 07:41:27:645 [ADB] The installed 'io.appium.unlock' package does not require upgrade ('2.0.0' >= '2.0.0')
2019-01-23 07:41:27:651 [ADB] Running '/Users/ania/Library/Android/sdk/platform-tools/adb -P 5037 -s 5b8beaf1 shell settings get global animator_duration_scale'
2019-01-23 07:41:27:723 [ADB] Running '/Users/ania/Library/Android/sdk/platform-tools/adb -P 5037 -s 5b8beaf1 shell settings get global transition_animation_scale'
2019-01-23 07:41:27:803 [ADB] Running '/Users/ania/Library/Android/sdk/platform-tools/adb -P 5037 -s 5b8beaf1 shell settings get global window_animation_scale'
2019-01-23 07:41:27:888 [Espresso] Forwarding Espresso Server port 6791 to 8300
2019-01-23 07:41:27:888 [ADB] Forwarding system: 8300 to device: 6791
2019-01-23 07:41:27:889 [ADB] Running '/Users/ania/Library/Android/sdk/platform-tools/adb -P 5037 -s 5b8beaf1 forward tcp\:8300 tcp\:6791'
2019-01-23 07:41:27:903 [ADB] Running '/Users/ania/Library/Android/sdk/platform-tools/adb -P 5037 -s 5b8beaf1 shell dumpsys window'
2019-01-23 07:41:27:964 [AndroidDriver] Screen already unlocked, doing nothing
2019-01-23 07:41:27:965 [ADB] Checking app cert for /Users/ania/abc/runtime/platform/runtime-android/app/build/outputs/apk/internal/debug/app-internal-debug.apk
2019-01-23 07:41:27:967 [ADB] Using apksigner from /Users/ania/Library/Android/sdk/build-tools/28.0.3/apksigner
2019-01-23 07:41:27:968 [ADB] Starting '/Users/ania/Library/Android/sdk/build-tools/28.0.3/apksigner' with args '["verify","--print-certs","/Users/ania/abc/runtime/platform/runtime-android/app/build/outputs/apk/internal/debug/app-internal-debug.apk"]'
2019-01-23 07:41:28:358 [ADB] apksigner stdout: Signer #1 certificate DN: EMAILADDRESS=android@android.com, CN=Android, OU=Android, O=Android, L=Mountain View, ST=California, C=US
2019-01-23 07:41:28:358 [ADB] Signer #1 certificate SHA-256 digest: a40da80a59d170caa950cf15c18c454d47a39b26989d8b640ecd745ba71bf5dc
2019-01-23 07:41:28:358 [ADB] Signer #1 certificate SHA-1 digest: 61ed377e85d386a8dfee6b864bd85b0bfaa5af81
2019-01-23 07:41:28:358 [ADB] Signer #1 certificate MD5 digest: e89b158e4bcf988ebd09eb83f5378e87
2019-01-23 07:41:28:358 [ADB] WARNING: META-INF/android.arch.core_runtime.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
2019-01-23 07:41:28:359 [ADB] WARNING: META-INF/android.arch.lifecycle_livedata-core.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
2019-01-23 07:41:28:359 [ADB] WARNING: META-INF/android.arch.lifecycle_livedata.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
2019-01-23 07:41:28:359 [ADB] WARNING: META-INF/android.arch.lifecycle_runtime.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
2019-01-23 07:41:28:359 [ADB] WARNING: META-INF/android.arch.lifecycle_viewmodel.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
2019-01-23 07:41:28:359 [ADB] WARNING: META-INF/androidx.appcompat_appcompat.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
2019-01-23 07:41:28:359 [ADB] WARNING: META-INF/androidx.asynclayoutinflater_asynclayoutinflater.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
2019-01-23 07:41:28:359 [ADB] WARNING: META-INF/androidx.coordinatorlayout_coordinatorlayout.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
2019-01-23 07:41:28:359 [ADB] WARNING: META-INF/androidx.core_core.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
2019-01-23 07:41:28:360 [ADB] WARNING: META-INF/androidx.cursoradapter_cursoradapter.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
2019-01-23 07:41:28:360 [ADB] WARNING: META-INF/androidx.customview_customview.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
2019-01-23 07:41:28:360 [ADB] WARNING: META-INF/androidx.documentfile_documentfile.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
2019-01-23 07:41:28:360 [ADB] WARNING: META-INF/androidx.drawerlayout_drawerlayout.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
2019-01-23 07:41:28:360 [ADB] WARNING: META-INF/androidx.fragment_fragment.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
2019-01-23 07:41:28:360 [ADB] WARNING: META-INF/androidx.interpolator_interpolator.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
2019-01-23 07:41:28:360 [ADB] WARNING: META-INF/androidx.legacy_legacy-support-core-ui.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
2019-01-23 07:41:28:360 [ADB] WARNING: META-INF/androidx.legacy_legacy-support-core-utils.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
2019-01-23 07:41:28:361 [ADB] WARNING: META-INF/androidx.loader_loader.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
2019-01-23 07:41:28:361 [ADB] WARNING: META-INF/androidx.localbroadcastmanager_localbroadcastmanager.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
2019-01-23 07:41:28:361 [ADB] WARNING: META-INF/androidx.print_print.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
2019-01-23 07:41:28:361 [ADB] WARNING: META-INF/androidx.slidingpanelayout_slidingpanelayout.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
2019-01-23 07:41:28:361 [ADB] WARNING: META-INF/androidx.swiperefreshlayout_swiperefreshlayout.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
2019-01-23 07:41:28:361 [ADB] WARNING: META-INF/androidx.vectordrawable_vectordrawable-animated.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
2019-01-23 07:41:28:361 [ADB] WARNING: META-INF/androidx.vectordrawable_vectordrawable.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
2019-01-23 07:41:28:362 [ADB] WARNING: META-INF/androidx.versionedparcelable_versionedparcelable.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
2019-01-23 07:41:28:362 [ADB] WARNING: META-INF/androidx.viewpager_viewpager.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
2019-01-23 07:41:28:362 [ADB] 
2019-01-23 07:41:28:362 [ADB] '/Users/ania/abc/runtime/platform/runtime-android/app/build/outputs/apk/internal/debug/app-internal-debug.apk' is already signed.
2019-01-23 07:41:28:362 [ADB] Getting install status for com.abc.app.internal
2019-01-23 07:41:28:363 [ADB] Running '/Users/ania/Library/Android/sdk/platform-tools/adb -P 5037 -s 5b8beaf1 shell pm list packages com.abc.app.internal'
2019-01-23 07:41:28:929 [ADB] App is installed
2019-01-23 07:41:28:930 [ADB] Getting install status for com.abc.app.internal
2019-01-23 07:41:28:930 [ADB] Running '/Users/ania/Library/Android/sdk/platform-tools/adb -P 5037 -s 5b8beaf1 shell pm list packages com.abc.app.internal'
2019-01-23 07:41:29:564 [ADB] App is installed
2019-01-23 07:41:29:564 [ADB] Getting package info for 'com.abc.app.internal'
2019-01-23 07:41:29:565 [ADB] Running '/Users/ania/Library/Android/sdk/platform-tools/adb -P 5037 -s 5b8beaf1 shell dumpsys package com.abc.app.internal'
2019-01-23 07:41:29:652 [ADB] The installed 'com.abc.app.internal' package does not require upgrade ('1.0.0' >= '1.0.0')
2019-01-23 07:41:29:652 [AndroidDriver] Performing fast reset on 'com.abc.app.internal'
2019-01-23 07:41:29:653 [ADB] Getting install status for com.abc.app.internal
2019-01-23 07:41:29:653 [ADB] Running '/Users/ania/Library/Android/sdk/platform-tools/adb -P 5037 -s 5b8beaf1 shell pm list packages com.abc.app.internal'
2019-01-23 07:41:30:269 [ADB] App is installed
2019-01-23 07:41:30:270 [ADB] Running '/Users/ania/Library/Android/sdk/platform-tools/adb -P 5037 -s 5b8beaf1 shell am force-stop com.abc.app.internal'
2019-01-23 07:41:30:386 [ADB] Running '/Users/ania/Library/Android/sdk/platform-tools/adb -P 5037 -s 5b8beaf1 shell pm clear com.abc.app.internal'
2019-01-23 07:41:31:019 [AndroidDriver] Performed fast reset on the installed 'com.abc.app.internal' application (stop and clear)
2019-01-23 07:41:31:020 [Espresso] 'forceEspressoRebuild' capability is enabled
2019-01-23 07:41:31:020 [Espresso] Deleting the obsolete Espresso server package '/var/folders/b0/s7kwsw_50_337s6lxr0lkm69c34ybl/T/io.appium.espressoserver.test_1.7.1_com.abc.app.internal.apk'
2019-01-23 07:41:31:022 [Espresso] Repackaging espresso server for: 'com.abc.app.internal'
2019-01-23 07:41:31:024 [Espresso] Creating new manifest: '/var/folders/b0/s7kwsw_50_337s6lxr0lkm69c34ybl/T/AndroidManifest.xml'
2019-01-23 07:41:31:034 [ADB] Found the most recent Android platform: {"platform":"android-28","platformPath":"/Users/ania/Library/Android/sdk/platforms/android-28"}
2019-01-23 07:41:31:034 [ADB] Compiling the manifest: /Users/ania/Library/Android/sdk/build-tools/28.0.3/aapt package -M /var/folders/b0/s7kwsw_50_337s6lxr0lkm69c34ybl/T/AndroidManifest.xml --rename-manifest-package io.appium.espressoserver.test --rename-instrumentation-target-package com.abc.app.internal -I /Users/ania/Library/Android/sdk/platforms/android-28/android.jar -F /var/folders/b0/s7kwsw_50_337s6lxr0lkm69c34ybl/T/AndroidManifest.xml.apk -f
2019-01-23 07:41:31:081 [ADB] Compiled the manifest at '/var/folders/b0/s7kwsw_50_337s6lxr0lkm69c34ybl/T/AndroidManifest.xml.apk'
2019-01-23 07:41:31:081 [ADB] Inserting manifest, src: /Users/ania/abc/runtime/test/node_modules/appium-espresso-driver/espresso-server/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk dst: /var/folders/b0/s7kwsw_50_337s6lxr0lkm69c34ybl/T/io.appium.espressoserver.test_1.7.1_com.abc.app.internal.apk
2019-01-23 07:41:31:082 [ADB] Unzipping /var/folders/b0/s7kwsw_50_337s6lxr0lkm69c34ybl/T/AndroidManifest.xml.apk
2019-01-23 07:41:31:082 [ADB] Testing zip archive: '/var/folders/b0/s7kwsw_50_337s6lxr0lkm69c34ybl/T/AndroidManifest.xml.apk'
2019-01-23 07:41:31:091 [ADB] Unzip successful
2019-01-23 07:41:31:096 [ADB] Testing new tmp apk
2019-01-23 07:41:31:096 [ADB] Testing zip archive: '/var/folders/b0/s7kwsw_50_337s6lxr0lkm69c34ybl/T/io.appium.espressoserver.test_1.7.1_com.abc.app.internal.apk'
2019-01-23 07:41:31:097 [ADB] Moving manifest
2019-01-23 07:41:31:124 [ADB] Inserted manifest.
2019-01-23 07:41:31:124 [Espresso] Repackaged espresso server ready: '/var/folders/b0/s7kwsw_50_337s6lxr0lkm69c34ybl/T/io.appium.espressoserver.test_1.7.1_com.abc.app.internal.apk'
2019-01-23 07:41:31:124 [ADB] Checking app cert for /var/folders/b0/s7kwsw_50_337s6lxr0lkm69c34ybl/T/io.appium.espressoserver.test_1.7.1_com.abc.app.internal.apk
2019-01-23 07:41:31:125 [ADB] Starting '/Users/ania/Library/Android/sdk/build-tools/28.0.3/apksigner' with args '["verify","--print-certs","/var/folders/b0/s7kwsw_50_337s6lxr0lkm69c34ybl/T/io.appium.espressoserver.test_1.7.1_com.abc.app.internal.apk"]'
2019-01-23 07:41:31:363 [ADB] Got an error during apksigner execution: Command '/Users/ania/Library/Android/sdk/build-tools/28.0.3/apksigner verify --print-certs /var/folders/b0/s7kwsw_50_337s6lxr0lkm69c34ybl/T/io.appium.espressoserver.test_1.7.1_com.abc.app.internal.apk' exited with code 1
2019-01-23 07:41:31:363 [ADB] apksigner stderr: DOES NOT VERIFY
2019-01-23 07:41:31:363 [ADB] ERROR: JAR signer CERT.RSA: JAR signature META-INF/CERT.SF indicates the APK is signed using APK Signature Scheme v2 but no such signature was found. Signature stripped?
2019-01-23 07:41:31:363 [ADB] 
2019-01-23 07:41:31:364 [ADB] '/var/folders/b0/s7kwsw_50_337s6lxr0lkm69c34ybl/T/io.appium.espressoserver.test_1.7.1_com.abc.app.internal.apk' is not signed with debug cert.
2019-01-23 07:41:31:364 [ADB] Checking whether zipalign is present
2019-01-23 07:41:31:365 [ADB] Using zipalign from /Users/ania/Library/Android/sdk/build-tools/28.0.3/zipalign
2019-01-23 07:41:31:377 [ADB] /var/folders/b0/s7kwsw_50_337s6lxr0lkm69c34ybl/T/io.appium.espressoserver.test_1.7.1_com.abc.app.internal.apk' is already zip-aligned. Doing nothing
2019-01-23 07:41:31:378 [ADB] Signing '/var/folders/b0/s7kwsw_50_337s6lxr0lkm69c34ybl/T/io.appium.espressoserver.test_1.7.1_com.abc.app.internal.apk' with default cert
2019-01-23 07:41:31:378 [ADB] Starting '/Users/ania/Library/Android/sdk/build-tools/28.0.3/apksigner' with args '["sign","--key","/Users/ania/abc/runtime/test/node_modules/appium-espresso-driver/node_modules/appium-android-driver/node_modules/appium-adb/keys/testkey.pk8","--cert","/Users/ania/abc/runtime/test/node_modules/appium-espresso-driver/node_modules/appium-android-driver/node_modules/appium-adb/keys/testkey.x509.pem","/var/folders/b0/s7kwsw_50_337s6lxr0lkm69c34ybl/T/io.appium.espressoserver.test_1.7.1_com.abc.app.internal.apk"]'
2019-01-23 07:41:31:901 [ADB] Uninstalling io.appium.espressoserver.test
2019-01-23 07:41:31:901 [ADB] Getting install status for io.appium.espressoserver.test
2019-01-23 07:41:31:901 [ADB] Running '/Users/ania/Library/Android/sdk/platform-tools/adb -P 5037 -s 5b8beaf1 shell pm list packages io.appium.espressoserver.test'
2019-01-23 07:41:32:507 [ADB] App is not installed
2019-01-23 07:41:32:507 [ADB] io.appium.espressoserver.test was not uninstalled, because it was not present on the device
2019-01-23 07:41:32:509 [Espresso] Deleting espresso session
2019-01-23 07:41:32:510 [ADB] Running '/Users/ania/Library/Android/sdk/platform-tools/adb -P 5037 -s 5b8beaf1 shell am force-stop com.abc.app.internal'
2019-01-23 07:41:32:598 [Logcat] Stopping logcat capture
2019-01-23 07:41:32:601 [ADB] Device API level: 26
2019-01-23 07:41:32:602 [ADB] Removing forwarded port socket connection: 8300 
2019-01-23 07:41:32:602 [ADB] Running '/Users/ania/Library/Android/sdk/platform-tools/adb -P 5037 -s 5b8beaf1 forward --remove tcp\:8300'
2019-01-23 07:41:32:615 [BaseDriver] Event 'newSessionStarted' logged at 1548229292615 (08:41:32 GMT+0100 (Central European Standard Time))
2019-01-23 07:41:32:620 [MJSONWP] Encountered internal error running command: TypeError: this.adb.getApplicationInstallState is not a function
2019-01-23 07:41:32:620 [MJSONWP]     at EspressoRunner.installServer (/Users/ania/abc/runtime/test/node_modules/appium-espresso-driver/lib/espresso-runner.js:48:37)
2019-01-23 07:41:32:620 [MJSONWP]     at EspressoRunner.installTestApk (/Users/ania/abc/runtime/test/node_modules/appium-espresso-driver/lib/espresso-runner.js:102:16)
2019-01-23 07:41:32:624 [HTTP] <-- POST /wd/hub/session 500 7085 ms - 190
2019-01-23 07:41:32:624 [HTTP] 
```

**Comment by mykola-mokhnach** [comment]
Does reinstall help? It seems like the appium-adb component version in your installation is out of date

**Comment by ania-s** [comment]
> Does reinstall help? It seems like the appium-adb component version in your installation is out of date

No it doesn't. I cleaned my whole environment and reinstalled appium and I see this issue. Unless you mean to remove appium-adb independently and installing it manually?

**Comment by imurchie** [comment]
Seems to resolve correctly in `npm-shrinkwrap.json`.

What is the output of `npm -g ls appium-adb`?

**Comment by ania-s** [comment]
npm -g ls appium-adb
/usr/local/lib
└─┬ appium@1.11.0-beta.3
  ├─┬ appium-android-driver@4.8.0
  │ └── appium-adb@7.2.0 
  ├─┬ appium-espresso-driver@1.7.1
  │ ├── appium-adb@7.2.0 
  │ └─┬ appium-android-driver@4.8.0
  │   └── appium-adb@7.2.0  deduped
  ├─┬ appium-selendroid-driver@1.13.3
  │ └── appium-adb@7.2.0  deduped
  └─┬ appium-uiautomator2-driver@1.28.0
    └── appium-adb@7.2.0  deduped

**Comment by imurchie** [comment]
This is not the same version as in the logs above. Is that on purpose?

**Comment by ania-s** [comment]
> This is not the same version as in the logs above. Is that on purpose?

Sorry, I reinstalled appium quickly now to check the adb and maybe I mixed the version. I will do it one more time once I have a moment and make sure all the versions match.

**Comment by ania-s** [comment]
Here is the correct version:

>  npm -g ls appium-adb
> /usr/local/lib
> └─┬ appium@1.11.0-rc.3
>   ├─┬ appium-android-driver@4.8.0
>   │ └── appium-adb@7.1.2 
>   ├─┬ appium-espresso-driver@1.7.1
>   │ └── appium-adb@7.1.2  deduped
>   ├─┬ appium-selendroid-driver@1.13.3
>   │ └── appium-adb@7.1.2  deduped
>   └─┬ appium-uiautomator2-driver@1.27.0
>     └── appium-adb@7.1.2  deduped

**Comment by imurchie** [comment]
I'm at a loss here. I can't get it to fail with this setup. :(

**Comment by hcastro** [comment]
If you're using `yarn`, try deleting `yarn.lock`, `node_modules`, and then reinstall your dependencies

I ran into this same issue where `yarn.lock` saved multiple versions of `appium-adb`. This is what i saw when I kept running into the ```this.adb.getApplicationInstallState is not a function``` error

```
cat yarn.lock | grep appium-adb
  resolved "https://registry.yarnpkg.com/appium-adb/-/appium-adb-6.24.0.tgz#ae45514bafa3811d2d19d48ed2ef7011dc14da70"
  resolved "https://registry.yarnpkg.com/appium-adb/-/appium-adb-7.2.0.tgz#0e43615a8accbabcfa63dc26ae0b31c71f89909d"
```

**Comment by ania-s** [comment]
> If you're using `yarn`, try deleting `yarn.lock`, `node_modules`, and then reinstall your dependencies
> 
> I ran into this same issue where `yarn.lock` saved multiple versions of `appium-adb`. This is what i saw when I kept running into the `this.adb.getApplicationInstallState is not a function` error
> 
> ```
> cat yarn.lock | grep appium-adb
>   resolved "https://registry.yarnpkg.com/appium-adb/-/appium-adb-6.24.0.tgz#ae45514bafa3811d2d19d48ed2ef7011dc14da70"
>   resolved "https://registry.yarnpkg.com/appium-adb/-/appium-adb-7.2.0.tgz#0e43615a8accbabcfa63dc26ae0b31c71f89909d"
> ```

Thanks a lot @hcastro 
Indeed this was the issue in my case as well. Now everything works fine again :)
