### ISSUE TITLE
windows10 Waiting and trying again. Unexpected token function

### ISSUE THREAD

**Issue by Sanmejie** [appium/appium#12072]
C:\Users\mi>cnpm install appium@1.10 -g
Downloading appium to C:\Users\mi\AppData\Roaming\npm\node_modules\appium_tmp
Copying C:\Users\mi\AppData\Roaming\npm\node_modules\appium_tmp\_appium@1.10.1@appium to C:\Users\mi\AppData\Roaming\npm\node_modules\appium
Installing appium's dependencies to C:\Users\mi\AppData\Roaming\npm\node_modules\appium/node_modules
[1/32] @babel/runtime@^7.0.0 installed at node_modules\_@babel_runtime@7.3.1@@babel\runtime

WARN node unsupported "node@v6.11.4" is incompatible with appium-selendroid-driver@1.13.3 › request-promise@4.2.2 › tough-cookie@3.0.0 › ip-regex@^3.0.0, expected node@>=8
[2/32] appium-fake-driver@^0.x installed at node_modules\_appium-fake-driver@0.6.2@appium-fake-driver
[3/32] appium-windows-driver@1.x installed at node_modules\_appium-windows-driver@1.5.1@appium-windows-driver
[4/32] appium-mac-driver@1.x installed at node_modules\_appium-mac-driver@1.4.1@appium-mac-driver
[5/32] appium-base-driver@3.x installed at node_modules\_appium-base-driver@3.13.2@appium-base-driver
[6/32] appium-support@2.x installed at node_modules\_appium-support@2.25.0@appium-support
[7/32] async-lock@^1.0.0 existed at node_modules\_async-lock@1.1.3@async-lock
[8/32] asyncbox@2.x existed at node_modules\_asyncbox@2.5.2@asyncbox
[9/32] bluebird@3.x existed at node_modules\_bluebird@3.5.3@bluebird
[10/32] argparse@^1.0.10 installed at node_modules\_argparse@1.0.10@argparse
[11/32] dateformat@^3.0.3 installed at node_modules\_dateformat@3.0.3@dateformat
[12/32] find-root@^1.1.0 installed at node_modules\_find-root@1.1.0@find-root
[13/32] lodash@^4.17.9 existed at node_modules\_lodash@4.17.11@lodash
[14/32] continuation-local-storage@3.x installed at node_modules\_continuation-local-storage@3.2.1@continuation-local-storage
[15/32] npmlog@4.x existed at node_modules\_npmlog@4.1.2@npmlog
[16/32] request@^2.81.0 existed at node_modules\_request@2.88.0@request
[17/32] request-promise@4.x existed at node_modules\_request-promise@4.2.2@request-promise
[18/32] longjohn@^0.2.12 installed at node_modules\_longjohn@0.2.12@longjohn
[19/32] semver@^5.5.0 existed at node_modules\_semver@5.6.0@semver
[20/32] source-map-support@0.x existed at node_modules\_source-map-support@0.5.10@source-map-support
[21/32] teen_process@1.x existed at node_modules\_teen_process@1.14.1@teen_process
[22/32] appium-ios-driver@2.x installed at node_modules\_appium-ios-driver@2.13.2@appium-ios-driver
fsevents@2.0.1 download from binary mirror: {"host":"https://cdn.npm.taobao.org/dist/fsevents"}
platform unsupported fsevents@2.x Package require os(darwin) not compatible with your platform(win32)
[fsevents@2.x] optional install error: Package require os(darwin) not compatible with your platform(win32)
[npminstall:runscript] heapdump@0.x found binding.gyp file, auto run "node-gyp rebuild", root: "C:\\Users\\mi\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\_heapdump@0.3.12@heapdump"

C:\Users\mi\AppData\Roaming\npm\node_modules\appium\node_modules\_heapdump@0.3.12@heapdump>node "C:\Users\mi\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\node-gyp-bin\\node-gyp.js" rebuild
[24/32] winston@3.x installed at node_modules\_winston@3.1.0@winston
[25/32] appium-xcuitest-driver@^2.104.0 installed at node_modules\_appium-xcuitest-driver@2.107.0@appium-xcuitest-driver
[26/32] appium-tizen-driver@1.1.1-beta.2 installed at node_modules\_appium-tizen-driver@1.1.1-beta.2@appium-tizen-driver
[27/32] appium-youiengine-driver@^1.1.1 installed at node_modules\_appium-youiengine-driver@1.1.1@appium-youiengine-driver
[28/32] appium-android-driver@^4.0.0 installed at node_modules\_appium-android-driver@4.8.0@appium-android-driver
[29/32] appium-uiautomator2-driver@1.x installed at node_modules\_appium-uiautomator2-driver@1.28.1@appium-uiautomator2-driver
[30/32] appium-espresso-driver@^1.3.0 installed at node_modules\_appium-espresso-driver@1.7.1@appium-espresso-driver
[31/32] appium-selendroid-driver@1.x installed at node_modules\_appium-selendroid-driver@1.13.3@appium-selendroid-driver
Warning: Missing input files:
C:\Users\mi\AppData\Roaming\npm\node_modules\appium\node_modules\_heapdump@0.3.12@heapdump\build\..\src\compat-inl.h
C:\Users\mi\AppData\Roaming\npm\node_modules\appium\node_modules\_heapdump@0.3.12@heapdump\build\..\src\compat.h
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK ve
rsion in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\Users\mi\AppData\Roaming\npm\node_modules\appium\node_modules\_heapdump@0.3.12@heapdump\build\addon.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\mi\AppData\Roaming\npm\node_modules\cnpm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mi\\AppData\\Roaming\\npm\\node_modules\\cnpm\\node_modules\\npminstall\\node-gyp-bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\mi\AppData\Roaming\npm\node_modules\appium\node_modules\_heapdump@0.3.12@heapdump
gyp ERR! node -v v6.11.4
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
[npminstall:runscript:error] heapdump@0.x has binding.gyp file, run "node-gyp rebuild" error: Error: Run "C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild" error, exit code 1
[heapdump@0.x] optional install error: Error: Run "C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild" error, exit code 1
    at ChildProcess.proc.on.code (C:\Users\mi\AppData\Roaming\npm\node_modules\cnpm\node_modules\runscript\index.js:74:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
execute post install 3 scripts...
[1/3] scripts.install appium-android-driver@4.8.0 › appium-chromedriver@^4.8.0 run "node install-npm.js", root: "C:\\Users\\mi\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\_appium-chromedriver@4.10.1@appium-chromedriver"
Error trying to install Chromedriver binary. Waiting and trying again. Unexpected token function
Error trying to install Chromedriver binary. Waiting and trying again. Unexpected token function
Error trying to install Chromedriver binary. Waiting and trying again. Unexpected token function
Error trying to install Chromedriver binary. Waiting and trying again. Unexpected token function
Error trying to install Chromedriver binary. Waiting and trying again. Unexpected token function
Error trying to install Chromedriver binary. Waiting and trying again. Unexpected token function
Error trying to install Chromedriver binary. Waiting and trying again. Unexpected token function
Error trying to install Chromedriver binary. Waiting and trying again. Unexpected token function
Error trying to install Chromedriver binary. Waiting and trying again. Unexpected token function

**Comment by imurchie** [comment]
Node version? npm version? There were a bunch of questions at the top of the issue template that are there for a reason...

**Comment by mykola-mokhnach** [comment]
> WARN node unsupported "node@v6.11.4" is incompatible with appium-selendroid-driver@1.13.3 › request-promise@4.2.2 › tough-cookie@3.0.0 › ip-regex@^3.0.0, expected node@>=8


The minimum supported Node version is 8.

Closed as not an issue.
