### ISSUE TITLE
dyld: Library not loaded: @rpath/CarthageKit.framework/CarthageKit

### ISSUE THREAD

**Issue by swathijajula22** [appium/appium#12128]
## The problem

unable to launch application in Appium1.7.1 and Appium 1.10.0

## Environment

* Appium 1.7.1 and 1.0.0:
* MAC OS high sierra
* IOS Simulator 12.1:
* Appium.app:

## Details

I have started Appium desktop app and when i am trying to start session with below capabilities, i am getting attached error message and unable to proceed

{
  "app": "/Users/swathi/Downloads/Appmon_IOS/ABC.app",
  "platformVersion": "12.1",
  "deviceName": "iPhone X",
  "seleniumUrl": "http://127.0.0.1:4723",
  "environment": "stage",
  "platformName": "IOS",
  "noReset": "true",
  "fullReset": "false",
  "automationName": "XCUITest" //Also tried with Appium
}

With Appium 1.10.0, i got error message saying carthage is not under /user/local/bin.  So i installed carthage and copied the file to /user/local/bin. The i  started getting the attached error.

[https://gist.github.com/swathijajula22/cd6096a3f16c8446fae56ef5b4f051de](https://gist.github.com/swathijajula22/cd6096a3f16c8446fae56ef5b4f051de)

Then downgraded Appium to 1.7.1 and getting the same errors.

Can someone please look into this issue?

Copying error log as i face challenges attaching gist
```
[Appium] Welcome to Appium v1.9.1
[Appium] Non-default server args:
[Appium]   address: 127.0.0.1
[Appium]   sessionOverride: true
[Appium] Appium REST http interface listener started on 127.0.0.1:4723
[HTTP] --> GET /wd/hub/sessions
[HTTP] {}
[GENERIC] Calling AppiumDriver.getSessions() with args: []
[GENERIC] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 2 ms - 40
[HTTP] 
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"app":"/Users/jajus001/Downloads/Appmon_IOS/WDW.app","automationName":"XCUITest","deviceName":"iPhone X","environment":"stage","fullReset":"false","noReset":"true","platformName":"IOS","platformVersion":"12.1","seleniumUrl":"http://127.0.0.1:4723","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/jajus001/Downloads/Appmon_IOS/WDW.app","automationName":"XCUITest","deviceName":"iPhone X","environment":"stage","fullReset":"false","noReset":"true","platformName":"IOS","platformVersion":"12.1","seleniumUrl":"http://127.0.0.1:4723","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1549429497669 (00:04:57 GMT-0500 (EST))
[Appium] Creating new XCUITestDriver (v2.94.2) session
[Appium] Capabilities:
[Appium]   app: /Users/jajus001/Downloads/Appmon_IOS/WDW.app
[Appium]   automationName: XCUITest
[Appium]   deviceName: iPhone X
[Appium]   environment: stage
[Appium]   fullReset: false
[Appium]   noReset: true
[Appium]   platformName: IOS
[Appium]   platformVersion: 12.1
[Appium]   seleniumUrl: http://127.0.0.1:4723
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true
[BaseDriver] Creating session with MJSONWP desired capabilities: {"app":"/Users/jajus001/Dow...
[BaseDriver] Capability 'noReset' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] Capability 'fullReset' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by appium: environment, seleniumUrl.
[BaseDriver] Session created with session id: 35aa53e6-c8f9-4560-bb51-0a5bfdcc86c9
[XCUITest] Current user: 'jajus001'
[XCUITest] Xcode version set to '10.1' 
[XCUITest] iOS SDK Version set to '12.1'
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1549429498075 (00:04:58 GMT-0500 (EST))
[iOSSim] Constructing iOS simulator for Xcode version 10.1 with udid '44570290-E323-469E-B508-81F0762A21CD'
[XCUITest] Determining device to run tests on: udid: '44570290-E323-469E-B508-81F0762A21CD', real device: false
[BaseDriver] Using local app '/Users/jajus001/Downloads/Appmon_IOS/WDW.app'
[BaseDriver] Event 'appConfigured' logged at 1549429498972 (00:04:58 GMT-0500 (EST))
[XCUITest] Checking whether app '/Users/jajus001/Downloads/Appmon_IOS/WDW.app' is actually present on file system
[XCUITest] App is present
[iOS] Getting bundle ID from app '/Users/jajus001/Downloads/Appmon_IOS/WDW.app': 'com.disney.wdw.dev'
[BaseDriver] Event 'resetStarted' logged at 1549429498973 (00:04:58 GMT-0500 (EST))
[XCUITest] Reset: noReset is on. Leaving simulator as is
[BaseDriver] Event 'resetComplete' logged at 1549429498973 (00:04:58 GMT-0500 (EST))
[XCUITest] Starting log capture for iOS Simulator with udid '44570290-E323-469E-B508-81F0762A21CD', using 'xcrun simctl spawn 44570290-E323-469E-B508-81F0762A21CD log stream --style compact'
[BaseDriver] Event 'logCaptureStarted' logged at 1549429499974 (00:04:59 GMT-0500 (EST))
[XCUITest] Setting up simulator
[iOS] No reason to set locale
[iOS] No iOS / app preferences to set
[iOSSim] Matched 1 Simulator cache item for cleanup: /Users/jajus001/Library/Developer/CoreSimulator/Devices/44570290-E323-469E-B508-81F0762A21CD/data/Library/Caches/com.apple.mobile.installd.staging
[iOSSim] Setting preferences of 44570290-E323-469E-B508-81F0762A21CD Simulator to {"ConnectHardwareKeyboard":true}
[iOSSim] Setting common Simulator preferences to {"RotateWindowWhenSignaledByGuest":true,"ConnectHardwareKeyboard":true}
[iOSSim] Updated 44570290-E323-469E-B508-81F0762A21CD Simulator preferences at '/Users/jajus001/Library/Preferences/com.apple.iphonesimulator.plist' with {"DevicePreferences":{"44570290-E323-469E-B508-81F0762A21CD":{"ConnectHardwareKeyboard":true}},"RotateWindowWhenSignaledByGuest":true,"ConnectHardwareKeyboard":true}
[iOSSim] Got Simulator UI client PID: 83601
[iOSSim] Both Simulator with UDID 44570290-E323-469E-B508-81F0762A21CD and the UI client are currently running
[BaseDriver] Event 'simStarted' logged at 1549429500605 (00:05:00 GMT-0500 (EST))
[XCUITest] Verifying application platform
[XCUITest] CFBundleSupportedPlatforms: ["iPhoneSimulator"]
[XCUITest] App 'com.disney.wdw.dev' is already installed. No need to reinstall.
[BaseDriver] Event 'appInstalled' logged at 1549429500954 (00:05:00 GMT-0500 (EST))
[XCUITest] Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[JSONWP Proxy] Matched '/status' to command name 'getStatus'
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] WDA is not listening at 'http://localhost:8100/'
[XCUITest] WDA is currently not running. There is nothing to cache
[XCUITest] Trying to start WebDriverAgent 2 times with 10000ms interval
[BaseDriver] Event 'wdaStartAttempted' logged at 1549429501243 (00:05:01 GMT-0500 (EST))
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Running WebDriverAgent bootstrap script to install dependencies
[XCUITest] Fetching dependencies
[XCUITest] dyld: Library not loaded: @rpath/CarthageKit.framework/CarthageKit
[XCUITest]   Referenced from: /usr/local/bin/carthage
[XCUITest]   Reason: image not found
[XCUITest] Scripts/bootstrap.sh: line 45: 83761 Abort trap: 6           carthage bootstrap $USE_SSH
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Running WebDriverAgent bootstrap script to install dependencies
[XCUITest] Fetching dependencies
[XCUITest] dyld: Library not loaded: @rpath/CarthageKit.framework/CarthageKit
[XCUITest]   Referenced from: /usr/local/bin/carthage
[XCUITest]   Reason: image not found
[XCUITest] Scripts/bootstrap.sh: line 45: 83764 Abort trap: 6           carthage bootstrap $USE_SSH
[BaseDriver] Event 'wdaStartFailed' logged at 1549429501297 (00:05:01 GMT-0500 (EST))
[XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: "Command 'Scripts/bootstrap.sh -d' exited with code 134".
[XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Removing WDA application from device
[BaseDriver] Event 'wdaStartAttempted' logged at 1549429512703 (00:05:12 GMT-0500 (EST))
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Running WebDriverAgent bootstrap script to install dependencies
[XCUITest] Fetching dependencies
[XCUITest] dyld: Library not loaded: @rpath/CarthageKit.framework/CarthageKit
[XCUITest]   Referenced from: /usr/local/bin/carthage
[XCUITest]   Reason: image not found
[XCUITest] Scripts/bootstrap.sh: line 45: 83771 Abort trap: 6           carthage bootstrap $USE_SSH
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Running WebDriverAgent bootstrap script to install dependencies
[XCUITest] Fetching dependencies
[XCUITest] dyld: Library not loaded: @rpath/CarthageKit.framework/CarthageKit
[XCUITest]   Referenced from: /usr/local/bin/carthage
[XCUITest]   Reason: image not found
[XCUITest] Scripts/bootstrap.sh: line 45: 83774 Abort trap: 6           carthage bootstrap $USE_SSH
[BaseDriver] Event 'wdaStartFailed' logged at 1549429512755 (00:05:12 GMT-0500 (EST))
[XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: "Command 'Scripts/bootstrap.sh -d' exited with code 134".
[XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Removing WDA application from device
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: "Command 'Scripts/bootstrap.sh -d' exited with code 134".
[XCUITest]     at XCUITestDriver.quitAndUninstall$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:444:13)
[XCUITest]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[XCUITest]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[XCUITest]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[XCUITest]     at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[XCUITest]     at 
[XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[iOSLog] Stopping iOS log capture
[BaseDriver] Event 'newSessionStarted' logged at 1549429514086 (00:05:14 GMT-0500 (EST))
[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: "Command 'Scripts/bootstrap.sh -d' exited with code 134".
[MJSONWP]     at XCUITestDriver.quitAndUninstall$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:444:13)
[MJSONWP]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[MJSONWP]     at 
[HTTP] <-- POST /wd/hub/session 500 16419 ms - 259
[HTTP] 
[HTTP] --> DELETE /wd/hub/session
[HTTP] {}
[HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- DELETE /wd/hub/session 404 5 ms - 57
[HTTP] 
```

**Comment by mykola-mokhnach** [comment]
This looks like a problem with local carthage deployment/environment setup. Please check it with your developers/system administrators.

Make sure carthage runs properly if executed manually from the command line.

**Comment by imurchie** [comment]
Also, what is the output of `/usr/local/bin/carthage version`?
