### ISSUE TITLE
Bad app: /Users*****************iosApp/Smart2.app. App paths need to be absolute, or relative to the appium server install dir, or a URL to compressed file, or a special app name.

### ISSUE THREAD

**Issue by stranger2you** [appium/appium#12134]
## The problem

Bad app: /Users*****************iosApp/Smart2.app. App paths need to be absolute, or relative to the appium server install dir, or a URL to compressed file, or a special app name.
## Environment

* Appium version (or git revision) that exhibits the issue: 1.10.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 10.14 (18A391)
* Node.js version (unless using Appium.app|exe): v11.8.0
* Npm or Yarn package manager: 6.7.0
* Mobile platform/version under test: iOS/ 10.2
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: appium desktop

## Details

seems the app is not detected from the given path. I tried all possible ways 
1. same error noticed with Xcode 10.1. So downgraded to 9.1
2. Changed the app path
3. Tried with the latest application

## Link to Appium logs
```
[info] [35m[Appium][39m Welcome to Appium v1.10.0
[info] [35m[Appium][39m Appium REST http interface listener started on 0.0.0.0:4723[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m
[info] [35m[HTTP][39m [90m{"desiredCapabilities":{"app":"/Users/macbookpro/eclipse-workspace/CCWMobileTest/⁨iosApp/Smart2.app","bundleId":"com.launchship.DevSTTest","session-override":"true","deviceName":"iPhone 6","platform":"MAC","newCommandTimeout":20000,"VERSION":"11.1","automationName":"XCUITest","autoGrantPermissions":true,"platformName":"iOS","udid":"123920B4-9C20-4EBD-B928-908932807552","noResetValue":"false"},"capabilities":{"firstMatch":[{"VERSION":"11.1","appium:app":"/Users/macbookpro/eclipse-workspace/CCWMobileTest/⁨iosApp/Smart2.app","appium:autoGrantPermissions":true,"appium:automationName":"XCUITest","appium:bundleId":"com.launchship.DevSTTest","appium:deviceName":"iPhone 6","appium:newCommandTimeout":20000,"noResetValue":"false","platform":"MAC","platformName":"ios","session-override":"true","appium:udid":"123920B4-9C20-4EBD-B928-908932807552"}]}}[39m
[debug] [35m[W3C][39m Calling AppiumDriver.createSession() with args: [{"app":"/Users/macbookpro/eclipse-workspace/CCWMobileTest/⁨iosApp/Smart2.app","bundleId":"com.launchship.DevSTTest","session-override":"true","deviceName":"iPhone 6","platform":"MAC","newCommandTimeout":20000,"VERSION":"11.1","automationName":"XCUITest","autoGrantPermissions":true,"platformName":"iOS","udid":"123920B4-9C20-4EBD-B928-908932807552","noResetValue":"false"},null,{"firstMatch":[{"VERSION":"11.1","appium:app":"/Users/macbookpro/eclipse-workspace/CCWMobileTest/⁨iosApp/Smart2.app","appium:autoGrantPermissions":true,"appium:automationName":"XCUITest","appium:bundleId":"com.launchship.DevSTTest","appium:deviceName":"iPhone 6","appium:newCommandTimeout":20000,"noResetValue":"false","platform":"MAC","platformName":"ios","session-override":"true","appium:udid":"123920B4-9C20-4EBD-B928-908932807552"}]}]
[debug] [35m[BaseDriver][39m Event 'newSessionRequested' logged at 1549530903224 (14:45:03 GMT+0530 (IST))
[warn] [35m[BaseDriver][39m The capabilities ["VERSION","noResetValue","platform","session-override"] are not standard capabilities and should have an extension prefix
[info] [35m[Appium][39m Creating new XCUITestDriver (v2.104.0) session
[info] [35m[Appium][39m Capabilities:
[info] [35m[Appium][39m   VERSION: 11.1
[info] [35m[Appium][39m   noResetValue: false
[info] [35m[Appium][39m   platform: MAC
[info] [35m[Appium][39m   platformName: ios
[info] [35m[Appium][39m   session-override: true
[info] [35m[Appium][39m   app: /Users/macbookpro/eclipse-workspace/CCWMobileTest/⁨iosApp/Smart2.app
[info] [35m[Appium][39m   autoGrantPermissions: true
[info] [35m[Appium][39m   automationName: XCUITest
[info] [35m[Appium][39m   bundleId: com.launchship.DevSTTest
[info] [35m[Appium][39m   deviceName: iPhone 6
[info] [35m[Appium][39m   newCommandTimeout: 20000
[info] [35m[Appium][39m   udid: 123920B4-9C20-4EBD-B928-908932807552
[debug] [35m[BaseDriver][39m W3C capabilities {"alwaysMatch":{"appium:VER... and MJSONWP desired capabilities {"app":"/Users/macbookpro/e... were provided
[debug] [35m[BaseDriver][39m Creating session with W3C capabilities: {"alwaysMatch":{"appium:VER...
[warn] [35m[BaseDriver][39m The following capabilities were provided, but are not recognized by appium: VERSION, noResetValue, platform, session-override, autoGrantPermissions.
[info] [35m[BaseDriver][39m Session created with session id: 4e6496df-4b2b-43d3-a1c8-48e9db164d73
[debug] [35m[XCUITest][39m Current user: 'macbookpro'
[debug] [35m[XCUITest][39m Available devices: [info] [35m[iOSSim][39m Constructing iOS simulator for Xcode version 9.1 with udid '123920B4-9C20-4EBD-B928-908932807552'
[info] [35m[XCUITest][39m Determining device to run tests on: udid: '123920B4-9C20-4EBD-B928-908932807552', real device: false
[debug] [35m[XCUITest][39m Xcode version set to '9.1' (tools v10.1.0.0.1.1539992718)[debug] [35m[XCUITest][39m iOS SDK Version set to '11.1'
[debug] [35m[BaseDriver][39m Event 'xcodeDetailsRetrieved' logged at 1549530906710 (14:45:06 GMT+0530 (IST))
[info] [35m[XCUITest][39m No platformVersion specified. Using device version: '11.1'
[error] [35m[XCUITest][39m Error: The application at '/Users/macbookpro/eclipse-workspace/CCWMobileTest/⁨iosApp/Smart2.app' does not exist or is not accessible
[error] [35m[XCUITest][39m     at APPLICATIONS_CACHE_GUARD.acquire (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/lib/basedriver/helpers.js:147:13)
[error] [35m[XCUITest][39m Error: Bad app: /Users/macbookpro/eclipse-workspace/CCWMobileTest/⁨iosApp/Smart2.app. App paths need to be absolute, or relative to the appium server install dir, or a URL to compressed file, or a special app name.
[error] [35m[XCUITest][39m     at XCUITestDriver.configureApp (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/lib/driver.js:689:13)
[error] [35m[XCUITest][39m     at process._tickCallback (internal/process/next_tick.js:68:7)
[debug] [35m[XCUITest][39m Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [35m[BaseDriver][39m Event 'newSessionStarted' logged at 1549530906803 (14:45:06 GMT+0530 (IST))
[debug] [35m[W3C][39m Encountered internal error running command: Error: Bad app: /Users/macbookpro/eclipse-workspace/CCWMobileTest/⁨iosApp/Smart2.app. App paths need to be absolute, or relative to the appium server install dir, or a URL to compressed file, or a special app name.
[debug] [35m[W3C][39m     at XCUITestDriver.configureApp (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/lib/driver.js:689:13)
[debug] [35m[W3C][39m     at process._tickCallback (internal/process/next_tick.js:68:7)
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session [39m[31m500[39m [90m3596 ms - 1008[39m
[info] [35m[HTTP][39m [90m[39m
```

## Code To Reproduce Issue [ Good To Have ]
```java
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import io.appium.java_client.ios.IOSDriver;



public class CCW_iOSPOC {
	IOSDriver<?> driver;
	 

	@SuppressWarnings("rawtypes")
	@BeforeClass
	public void LaunchApp() throws InterruptedException {
				
		File test = new File("⁨iosApp/");
		File app = new File(test, "Smart2.app");
		
		DesiredCapabilities caps = new DesiredCapabilities();
		caps.setCapability("app", app.getAbsolutePath()); 
		caps.setCapability("platformName", "iOS");
                 caps.setCapability("platform", "Mac");
		caps.setCapability("deviceName", "iPhone 6");
		caps.setCapability("VERSION", "11.1");
		caps.setCapability("automationName", "XCUITest");
		caps.setCapability("session-override","true"); 
                 caps.setCapability("udid", "123920B4-9C20-4EBD-B928-908932807552");
                 caps.setCapability("bundleId", "com.launchship.DevSTTest");
                 caps.setCapability("noResetValue","false"); 
		caps.setCapability("autoGrantPermissions", true);
		caps.setCapability("newCommandTimeout", 20000);
		
		try {
			driver = new IOSDriver(new URL("http://0.0.0.0:4723/wd/hub"), caps);
		} catch (MalformedURLException e) {
			e.printStackTrace();
		}
	}
```

**Comment by imurchie** [comment]
Does the app exist at `/Users/macbookpro/eclipse-workspace/CCWMobileTest/⁨iosApp/Smart2.app`? And is it accessible?
