### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: javax/websocket/DeploymentException

### ISSUE THREAD

**Issue by NewUserMob** [appium/appium#12132]
## The problem

Exception in thread "main" java.lang.NoClassDefFoundError: javax/websocket/DeploymentException
	at io.appium.java_client.android.ListensToLogcatMessages.<clinit>(ListensToLogcatMessages.java:34)
	at scr.main(scr.java:36)
Caused by: java.lang.ClassNotFoundException: javax.websocket.DeploymentException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 2 more

## Environment

* Appium version (or git revision) that exhibits the issue:1.10.1 
* Node.js version (unless using Appium.app|exe):10.15.0
* Npm or Yarn package manager:6.4.1
* Mobile platform/version under test:Android 8.0
* Real device or emulator/simulator:Real Device
* Appium CLI :1.10.1
*Eclipse IDE:4.10
*Selenium server standalone jar:3.12
*Java-client jar:7.0
*Guava jar

## Details

Facing the No class found exception while running the automation scripts in eclipse.
Added the guava jar as suggested by https://github.com/SeleniumHQ/selenium/issues/4627. However, this does not resolve the issue. No logs are available in Appium. From my knowledge, it had issues while hitting the server.  We are trying Test.AI which requires us to use the latest version.

## Code To Reproduce Issue [ Good To Have ]
import java.net.*;
import java.util.HashMap;

import org.openqa.selenium.*;
import org.openqa.selenium.remote.DesiredCapabilities;

import io.appium.java_client.*;
import io.appium.java_client.android.AndroidDriver;

public class scr {
	
@SuppressWarnings("rawtypes")
public static AppiumDriver driver;

	@SuppressWarnings("rawtypes")
	public static void main(String[] args) throws MalformedURLException{
		// TODO Auto-generated method stub
		DesiredCapabilities capability=new DesiredCapabilities();
		capability.setCapability("platformName","Android");
		capability.setCapability("platformVersion","8.0");
		capability.setCapability("automationName", "uiautomator2");
		capability.setCapability("deviceName","Nexus 5X");
		capability.setCapability("noReset",true);
		capability.setCapability("browserName","chrome");
                 capability.setCapability("appPackage","com.flipkart.android");
		capability.setCapability("appActivity","com.flipkart.android.SplashActivity");
		HashMap<String, String> customFindModules = new HashMap<>();
	      customFindModules.put("ai", "test-ai-classifier");
	      capability.setCapability("customFindModules", customFindModules);
	      capability.setCapability("shouldUseCompactResponses", false); 
		 driver=new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"),capability);

		 driver.findElement("-custom","ai:cart").click();
		 driver.quit();

		
	}

}

**Comment by mykola-mokhnach** [comment]
Moved to java client issues tracker.

Make sure your client lib is up to date.
