### ISSUE TITLE
"Argument to isShown must be of type Element" is displayed 

### ISSUE THREAD

**Issue by israelsotos** [appium/appium#12133]
## The problem

When calling isElementDisplayed the next error always shows:
isElementDisplayed[ param-1: By.name: valPassword param-2: {"id":"0.7933803864225368-2"}] Result: An unknown server-side error occurred while processing the command. Original error: unknown error: Argument to isShown must be of type Element
After a few tries the test stops abruptly 
## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 1.8.1
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: Android 9
* Real device or emulator/simulator: Both
* Appium CLI or Appium.app|exe: Appium.exe

## Details

We're using QAF 2.1.14 which uses:
selenium-java 2.53.0
java-client 3.4.1

When it calls isElementDisplayed it always shows the next error:
[error.txt](https://github.com/appium/appium/files/2838873/error.txt)

## Link to Appium logs
[appium-server-logs.txt](https://github.com/appium/appium/files/2838875/appium-server-logs.txt)

## Code To Reproduce Issue [ Good To Have ]
	@QAFTestStep(description = "select {alldata-app} service")
	public void selectApp(String app) {

		CommonStep.waitForNotPresent("page.loader.loc");
		QAFTestBase.pause(3000);
		CommonUtils.waitForAjaxToComplete(3000);
		CommonUtils.waitForLoaderToDismiss();
		LoginStepsWebImple loginSteps = new LoginStepsWebImple();
		loginSteps.closeWalkManPopUp();

		AllDataApp.valueOf(app).getElement().waitForPresent();

		CommonUtils.waitForAjaxToComplete(3000);
		CommonUtils.waitForLoaderToDismiss();

		if (AllDataApp.valueOf(app).getElement().isPresent()
				&& AllDataApp.valueOf(app).getElement().isDisplayed()) {
			AllDataApp.valueOf(app).getElement().click();
			Reporter.log("Clicked on :" + app);
		}
	}

**Comment by mykola-mokhnach** [comment]
> [debug] [35m[ADB][39m Starting 'C:\Users\isoto\AppData\Local\Android\Sdk\build-tools\28.0.3\apksigner.bat' with args '["sign","--key","C:\\Program Files (x86)\\Appium\\resources\\app\\node_modules\\appium-adb\\keys\\testkey.pk8","--cert","C:\\Program Files (x86)\\Appium\\resources\\app\\node_modules\\appium-adb\\keys\\testkey.x509.pem","C:\\Program Files (x86)\\Appium\\resources\\app\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-debug-androidTest.apk"]'[warn] [35m[ADB][39m Got an error during apksigner execution: Command 'apksigner.bat sign --key 'C:\\Program Files (x86)\\Appium\\resources\\app\\node_modules\\appium-adb\\keys\\testkey.pk8' --cert 'C:\\Program Files (x86)\\Appium\\resources\\app\\node_modules\\appium-adb\\keys\\testkey.x509.pem' 'C:\\Program Files (x86)\\Appium\\resources\\app\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-debug-androidTest.apk'' exited with code 1
> [warn] [35m[ADB][39m apksigner stderr: Exception in thread "main" java.nio.file.AccessDeniedException: C:\Users\isoto\AppData\Local\Temp\apksigner4776702172889402562.apk -> C:\Program Files (x86)\Appium\resources\app\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk
> [warn] [35m[ADB][39m 	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
> [warn] [35m[ADB][39m 	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
> [warn] [35m[ADB][39m 	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
> [warn] [35m[ADB][39m 	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
> [warn] [35m[ADB][39m 	at java.nio.file.Files.move(Files.java:1395)
> [warn] [35m[ADB][39m 	at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:342)
> [warn] [35m[ADB][39m 	at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:89)
> [warn] [35m[ADB][39m 
> [warn] [35m[ADB][39m Cannot use apksigner tool for signing. Defaulting to sign.jar. Original error: Command 'apksigner.bat sign --key 'C:\\Program Files (x86)\\Appium\\resources\\app\\node_modules\\appium-adb\\keys\\testkey.pk8' --cert 'C:\\Program Files (x86)\\Appium\\resources\\app\\node_modules\\appium-adb\\keys\\testkey.x509.pem' 'C:\\Program Files (x86)\\Appium\\resources\\app\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-debug-androidTest.apk'' exited with code 1; StdErr: Exception in thread "main" java.nio.file.AccessDeniedException: C:\Users\isoto\AppData\Local\Temp\apksigner4776702172889402562.apk -> C:\Program Files (x86)\Appium\resources\app\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk
> [warn] [35m[ADB][39m 	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
> [warn] [35m[ADB][39m 	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
> [warn] [35m[ADB][39m 	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
> [warn] [35m[ADB][39m 	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
> [warn] [35m[ADB][39m 	at java.nio.file.Files.move(Files.java:1395)
> [warn] [35m[ADB][39m 	at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:342)
> [warn] [35m[ADB][39m 	at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:89)
> [warn] [35m[ADB][39m 

Make sure Appium process has appropriate read/write permissions in the folder where its files are installed.

**Comment by mykola-mokhnach** [comment]
Also the selenium version is seriously outdated. Make sure you use the most recent java client and selenium versions after server upgrade.

**Comment by israelsotos** [comment]
Thank you for your help @mykola-mokhnach , I updated to java-client 7.0.0 and selenium-java 3.141.59, and added automationName: UiAutomator2 as recommended in the logs.
I modified the folder permissions and the AccessDeniedException error is gone now.
However, the behavior is the same and it still crashes when calling isDisplayed() 
Do you have any recommendation or what other dependencies are related?
This are my ivy dependencies, I am not sure if maybe I am missing something else to update besides selenium-java and java-client

<dependencies>
		<dependency org="com.qmetry" name="qaf" rev="latest.integration" />
		<dependency org="com.qmetry" name="qaf-support" rev="latest.integration" />
		
		<dependency org="org.seleniumhq.selenium" name="selenium-java" rev="3.141.59"/>		
		<dependency org="io.appium" name="java-client" rev="7.0.0"/>
		
		<dependency org="org.aspectj" name="aspectjtools" rev="1.9.1" />
		<dependency org="org.aspectj" name="aspectjweaver" rev="1.9.1" />
		
		<dependency org="ant-contrib" name="ant-contrib" rev="1.0b3"/>
		<dependency org="com.paulhammant" name="ngwebdriver" rev="1.1.4" >
		<exclude org="org.testng" />
		</dependency>
		
	</dependencies>

[appium-server-logs-2-7-19.txt](https://github.com/appium/appium/files/2841995/appium-server-logs-2-7-19.txt)

**Comment by mykola-mokhnach** [comment]
> 	<dependency org="org.seleniumhq.selenium" name="selenium-java" rev="3.141.59"/>

This must be removed from deps list

**Comment by israelsotos** [comment]
Thank you for bearing with me, 
I did it and tried again and it failed again, what other configuration/information would be helpful to find out what is the root cause of this problem?
[appium-server-logs-2-7-19-2.txt](https://github.com/appium/appium/files/2842422/appium-server-logs-2-7-19-2.txt)

**Comment by mykola-mokhnach** [comment]
The error is still the same, which means that either the explicit selenium dependency has not been removed properly or the driver is not being created/used properly in the client code. Moving the problem to java client as this has nothing to do with the server.
