### ISSUE TITLE
Unable to identify object in iPAD device using Appium Inspector

### ISSUE THREAD

**Issue by ssoni001** [appium/appium#12163]
I am trying to identify an object which is back arrow (<) using Appium inspector.
I have written a code to install an app which is working fine. But when it comes to the @test annotation where I am trying to click on arrow , I am getting error.
Can someone please help me ....

Code:

I tried 3 ways -

           driver.findElementByXPath("//XCUIElementTypeButton[@name=\" \"]").click();
	  driver.findElementByXPath("//XCUIElementTypeButton[@x='0']").click();
	  
	  driver.findElementByXPath("(//XCUIElementTypeButton)[1]").click();

Eclipse Error:

FAILED: validateDragDrop
java.lang.NullPointerException
	at test.opporunitiesRegression.validateDragDrop(opporunitiesRegression.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

<img width="1326" alt="appium" src="https://user-images.githubusercontent.com/47416974/52786811-e7d63380-3081-11e9-84af-c801a5ec2f14.png">

**Comment by mykola-mokhnach** [comment]
Please use Appium forum to ask questions. this is the place for issues
