### ISSUE TITLE
Tests not starting when app is a bitrise URL

### ISSUE THREAD

**Issue by felipecpc** [appium/appium#12173]
## The problem

Not able to start the test with app as a bitrise URL. 

```
An unknown server-side error occurred while processing the command. Original error: Could not extract Info.plist from application: Plist file doesn't exist: '... appium-app.app/Info.plist' (Selenium::WebDriver::Error::UnknownError)
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.11.0
* Last Appium version that did not exhibit the issue (if applicable): 1.9.1
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe:

## Details

The file downloaded is saved as .app but it is actually an .ipa file, so tests are failing to start as there is no plist file on the root. 

```
An unknown server-side error occurred while processing the command. Original error: Could not extract Info.plist from application: Plist file doesn't exist: '... appium-app.app/Info.plist' (Selenium::WebDriver::Error::UnknownError)
```

On version 1.9.1 it is working properly as the app is downloaded as .ipa then unzipped and everything works. 

## Link to Appium logs
```
[Appium] Welcome to Appium v1.11.0
[Appium] Non-default server args:
[Appium]   port: 4725
[Appium] Appium REST http interface listener started on 0.0.0.0:4725
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"platformName":"ios","platformVersion":"12.1.2","deviceName":"ipod_unity","automationName":"XCUITest","app":"my-app-link","udid":"my_udid","reinstall":false,"fullReset":false,"noReset":true},"capabilities":{"alwaysMatch":{"platformName":"ios","appium:platformVersion":"12.1.2","appium:deviceName":"ipod_unity","appium:automationName":"XCUITest","appium:app":"my_app_link
[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"platformName":"ios","platformVersion":"12.1.2","deviceName":"ipod_unity","automationName":"XCUITest","app":"my_app_link","udid":"my_udid","reinstall":false,"fullReset":false,"noReset":true},null,{"alwaysMatch":{"platformName":"ios","appium:platformVersion":"12.1.2","appium:deviceName":"ipod_unity","appium:automationName":"XCUITest","appium:app":"my_app_link...
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1550328914060 (15:55:14 GMT+0100 (CET))
[Appium] Creating new XCUITestDriver (v2.105.1) session
[Appium] Capabilities:
[Appium]   platformName: ios
[Appium]   platformVersion: 12.1.2
[Appium]   deviceName: ipod_unity
[Appium]   automationName: XCUITest
[Appium]   app: my_app_link
[Appium]   udid: my_udid
[Appium]   reinstall: false
[Appium]   fullReset: false
[Appium]   noReset: true
[debug] [BaseDriver] W3C capabilities {"alwaysMatch":{"platformNa... and MJSONWP desired capabilities {"platformName":"ios","plat... were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"platformNa...
[BaseDriver] The following capabilities were provided, but are not recognized by appium: reinstall.
[BaseDriver] Session created with session id: e251c686-f945-4620-8efb-6c48c80e0fcf
[debug] [XCUITest] Current user: 'test'
[debug] [XCUITest] Available devices: my_udid
[debug] [XCUITest] Creating iDevice object with udid 'my_udid'
[XCUITest] Determining device to run tests on: udid: 'my_udid', real device: true
[debug] [XCUITest] Xcode version set to '10.1'
[debug] [XCUITest] iOS SDK Version set to '12.1'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1550328914742 (15:55:14 GMT+0100 (CET))
[BaseDriver] Using downloadable app 'my_app_link'
[debug] [BaseDriver] 'my_app_link' (11.51 MB) has been downloaded to '/var/folders/ts/1_cvp8455wvcm6ydygcw1yjw0000gn/T/2019116-40525-1g41zs4.0xklvgf1or/appium-app.app' in 24.567s
[debug] [BaseDriver] Approximate download speed: 4.54 MB/s
[debug] [BaseDriver] Event 'appConfigured' logged at 1550328939857 (15:55:39 GMT+0100 (CET))
[debug] [XCUITest] Checking whether app '.../appium-app.app' is actually present on file system
[debug] [XCUITest] App is present
[Support] Error: Plist file doesn't exist: '.../appium-app.app/Info.plist'
[Support]     at Object.wrappedLogger.errorAndThrow (node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[Support]     at Object.parsePlistFile (node_modules/appium/node_modules/appium-support/lib/plist.js:22:11)
[iOS] Error: Could not extract Info.plist from application: Plist file doesn't exist: '.../appium-app.app/Info.plist'
[iOS]     at Object.wrappedLogger.errorAndThrow (node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[iOS]     at extractPlist (node_modules/appium/node_modules/appium-ios-driver/lib/app-utils.js:14:9)
[XCUITest] Error: Could not extract Info.plist from application: Plist file doesn't exist: '.../appium-app.app/Info.plist'
[XCUITest]     at Object.wrappedLogger.errorAndThrow (node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[XCUITest]     at extractPlist (node_modules/appium/node_modules/appium-ios-driver/lib/app-utils.js:14:9)
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1550328939900 (15:55:39 GMT+0100 (CET))
[debug] [W3C] Encountered internal error running command: Error: Could not extract Info.plist from application: Plist file doesn't exist: .../appium-app.app/Info.plist'
[debug] [W3C]     at Object.wrappedLogger.errorAndThrow (node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[debug] [W3C]     at extractPlist (node_modules/appium/node_modules/appium-ios-driver/lib/app-utils.js:14:9)
[HTTP] <-- POST /wd/hub/session 500 25878 ms - 859
[HTTP]
```

**Comment by mykola-mokhnach** [comment]
Please attach the full log

**Comment by felipecpc** [comment]
Logs added in the original message

**Comment by mykola-mokhnach** [comment]
I don't see any problems here. The downloaded file is only going to be extracted if either response headers point to the fact it is an archive or the file extension itself.

**Comment by felipecpc** [comment]
umm I see, well I'm using a bitrise link, so the response header is what they are sending, I cannot change it, but the app available it is for sure .ipa not a .app, so it should be extracted first I guess. 

Anyway, I opened as an issue as it was working at 1.9.1 and from 1.9.2 upwards is not working anymore, but if it is supposed to be like that is fine, I can figure out a way to make an .app available than it should work. 

Thanks!

**Comment by mykola-mokhnach** [comment]
You can simply make sure the link ends with '.ipa'

**Comment by felipecpc** [comment]
The link looks like this:
```
https://bitrise-prod-build-storage.s3.amazonaws.com/builds/999999/artifacts/999999/app.ipa?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=HBHBHBHBHBHBHBHBHBHBHHB%2F20190216%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190216T145515Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=9384753984753984759384759387593875938345345
```

**Comment by mykola-mokhnach** [comment]
Ok, then it might be a problem with actual link format parsing

**Comment by mykola-mokhnach** [comment]
The fix has been published to appium@beta
