### ISSUE TITLE
w3c: No open port found

### ISSUE THREAD

**Issue by yxcSini** [appium/appium#12186]
## The problem
Suddenly the appium service could not be connected today, and the log did not output detailed reasons and solutions. Can you help me see the reason, thank you very much!

## Environment

* Appium version (or git revision) that exhibits the issue: 1.10.0
* Last Appium version that did not exhibit the issue (if applicable):yesterday can run
* Desktop OS/version used to run Appium:Docker run it,OS is Centos 7
* Node.js version (unless using Appium.app|exe):docker images is appium/appium:1.10.0-p0
* Npm or Yarn package manager:docker images is appium/appium:1.10.0-p0
* Mobile platform/version under test:7.0
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe:docker images is appium/appium:1.10.0-p0

## Link to Appium logs

```
2019-02-19T02:35:37.977993000Z [HTTP] --> POST /wd/hub/session
2019-02-19T02:35:37.978277000Z [HTTP] {"capabilities":{"firstMatch":[{}],"alwaysMatch":{"appium:chromeOptions":{"androidProcess":"com.junte"},"appium:recreateChromeDriverSessions":"true","appium:app":"http://admin:tuandai123888@10.100.11.222:8082/view/DevOps-Jenkins-And/job/TuandaiAS2-DevOps-Pipline-Merge-Request/lastSuccessfulBuild/artifact/integrations/apk/TuandaiAS2-performance-develop.apk","appium:udid":"A5R7N17C22027488","platformName":"Android","appium:platformVersion":"7.0","appium:deviceName":"A5R7N17C22027488","appium:noReset":"true","appium:autoGrantPermissions":"true","appium:appPackage":"com.junte","appium:resetKeyboard":"true","appium:unicodeKeyboard":"true","appium:useKeystore":"true","appium:chromedriverExecutableDir":"/root/webview/","appium:chromedriverChromeMappingFile":"/root/mapping.json","appium:keystorePath":"/root/tuandai_test.keystore","appium:keystorePassword":"xxxx","appium:keyAlias":"xxxxx","appium:keyPassword":"xxxxxxx","appium:automationName":"UiAutomator2","appium:noSign":"tru
2019-02-19T02:35:37.978535000Z [debug] [W3C] Calling AppiumDriver.createSession() with args: [{"chromeOptions":{"androidProcess":"com.junte"},"recreateChromeDriverSessions":"true","app":"http://xxxx/view/DevOps-Jenkins-And/job/TuandaiAS2-DevOps-Pipline-Merge-Request/lastSuccessfulBuild/artifact/integrations/apk/TuandaiAS2-performance-develop.apk","udid":"A5R7N17C22027488","platformName":"Android","platformVersion":"7.0","deviceName":"A5R7N17C22027488","noReset":"true","autoGrantPermissions":"true","appPackage":"com.junte","resetKeyboard":"true","unicodeKeyboard":"true","useKeystore":"true","chromedriverExecutableDir":"/root/webview/","chromedriverChromeMappingFile":"/root/mapping.json","keystorePath":"/root/tuandai_test.keystore","keystorePassword":"tuandai123888","keyAlias":"tuandai","keyPassword":"tuandai123888","automationName":"UiAutomator2","noSign":"true","newCommandTimeout":12000},null,{"firstMatch":[{}],"alwaysMatch":{"appium:chromeOptions":{"androidProcess":"com.junte"},"appium:recreateChromeDriverSessions":"true","appium:app":"http://xxx@...
2019-02-19T02:35:37.978833000Z [debug] [BaseDriver] Event 'newSessionRequested' logged at 1550543737978 (18:35:37 GMT-0800 (Pacific Standard Time))
2019-02-19T02:35:37.979062000Z [BaseDriver] Boolean capability passed in as string. Functionality may be compromised.
2019-02-19T02:35:37.979278000Z [Appium] Creating new AndroidUiautomator2Driver (v1.26.0) session
2019-02-19T02:35:37.979437000Z [Appium] Capabilities:
2019-02-19T02:35:37.979589000Z [Appium]   platformName: Android
2019-02-19T02:35:37.979749000Z [Appium]   chromeOptions: {
2019-02-19T02:35:37.979905000Z [Appium]     androidProcess: com.junte
2019-02-19T02:35:37.980090000Z [Appium]   }
2019-02-19T02:35:37.980251000Z [Appium]   recreateChromeDriverSessions: true
2019-02-19T02:35:37.980404000Z [Appium]   app: http://xxxx/view/DevOps-Jenkins-And/job/TuandaiAS2-DevOps-Pipline-Merge-Request/lastSuccessfulBuild/artifact/integrations/apk/TuandaiAS2-performance-develop.apk
2019-02-19T02:35:37.980557000Z [Appium]   udid: A5R7N17C22027488
2019-02-19T02:35:37.980713000Z [Appium]   platformVersion: 7.0
2019-02-19T02:35:37.980864000Z [Appium]   deviceName: A5R7N17C22027488
2019-02-19T02:35:37.981015000Z [Appium]   noReset: true
2019-02-19T02:35:37.981171000Z [Appium]   autoGrantPermissions: true
2019-02-19T02:35:37.981322000Z [Appium]   appPackage: com.junte
2019-02-19T02:35:37.981470000Z [Appium]   resetKeyboard: true
2019-02-19T02:35:37.981659000Z [Appium]   unicodeKeyboard: true
2019-02-19T02:35:37.981814000Z [Appium]   useKeystore: true
2019-02-19T02:35:37.981965000Z [Appium]   chromedriverExecutableDir: /root/webview/
2019-02-19T02:35:37.982117000Z [Appium]   chromedriverChromeMappingFile: /root/mapping.json
2019-02-19T02:35:37.982266000Z [Appium]   keystorePath: /root/tuandai_test.keystore
2019-02-19T02:35:37.982417000Z [Appium]   keystorePassword: xxxx
2019-02-19T02:35:37.982565000Z [Appium]   keyAlias: xxxxx
2019-02-19T02:35:37.982720000Z [Appium]   keyPassword: xxxxxx
2019-02-19T02:35:37.982871000Z [Appium]   automationName: UiAutomator2
2019-02-19T02:35:37.983020000Z [Appium]   noSign: true
2019-02-19T02:35:37.983203000Z [Appium]   newCommandTimeout: 12000
2019-02-19T02:35:37.983358000Z [debug] [BaseDriver] W3C capabilities {"alwaysMatch":{"platformNa... and MJSONWP desired capabilities {"chromeOptions":{"androidP... were provided
2019-02-19T02:35:37.983513000Z [debug] [BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"platformNa...
2019-02-19T02:35:37.983680000Z [BaseDriver] Boolean capability passed in as string. Functionality may be compromised.
2019-02-19T02:35:37.983847000Z [BaseDriver] Boolean capability passed in as string. Functionality may be compromised.
2019-02-19T02:35:37.984023000Z [BaseDriver] Boolean capability passed in as string. Functionality may be compromised.
2019-02-19T02:35:37.984181000Z [BaseDriver] Boolean capability passed in as string. Functionality may be compromised.
2019-02-19T02:35:37.984331000Z [BaseDriver] Boolean capability passed in as string. Functionality may be compromised.
2019-02-19T02:35:37.984479000Z [BaseDriver] Boolean capability passed in as string. Functionality may be compromised.
2019-02-19T02:35:37.984648000Z [BaseDriver] Capability 'noReset' changed from string to boolean. This may cause unexpected behavior
2019-02-19T02:35:37.984839000Z [BaseDriver] Capability 'useKeystore' changed from string to boolean. This may cause unexpected behavior
2019-02-19T02:35:37.985023000Z [BaseDriver] Capability 'unicodeKeyboard' changed from string to boolean. This may cause unexpected behavior
2019-02-19T02:35:37.985196000Z [BaseDriver] Capability 'resetKeyboard' changed from string to boolean. This may cause unexpected behavior
2019-02-19T02:35:37.985340000Z [BaseDriver] Capability 'noSign' changed from string to boolean. This may cause unexpected behavior
2019-02-19T02:35:37.985486000Z [BaseDriver] Capability 'autoGrantPermissions' changed from string to boolean. This may cause unexpected behavior
2019-02-19T02:35:37.985646000Z [BaseDriver] The following capabilities were provided, but are not recognized by appium: chromeOptions.
2019-02-19T02:35:37.985787000Z [BaseDriver] Session created with session id: 2c16a0cf-6f94-41d5-9b40-952acfc90749
2019-02-19T02:35:37.985974000Z [BaseDriver] Using downloadable app 'http://admin:tuandai123888@10.100.11.222:8082/view/DevOps-Jenkins-And/job/TuandaiAS2-DevOps-Pipline-Merge-Request/lastSuccessfulBuild/artifact/integrations/apk/TuandaiAS2-performance-develop.apk'
2019-02-19T02:35:38.128026000Z [debug] [BaseDriver] Last-Modified: Tue, 19 Feb 2019 02:15:14 GMT
2019-02-19T02:35:38.128254000Z [debug] [BaseDriver] Reusing already downloaded application at '/tmp/2019118-1-10oi6m5.n9p1/appium-app.apk'
2019-02-19T02:35:38.128507000Z [BaseDriver] Reusing the previously downloaded application at '/tmp/2019118-1-10oi6m5.n9p1/appium-app.apk'
2019-02-19T02:35:38.128789000Z [debug] [UiAutomator2] Checking whether app is actually present
2019-02-19T02:35:38.143006000Z [debug] [UiAutomator2] Deleting UiAutomator2 session
2019-02-19T02:35:38.143148000Z [debug] [BaseDriver] Event 'newSessionStarted' logged at 1550543738142 (18:35:38 GMT-0800 (Pacific Standard Time))
2019-02-19T02:35:38.143471000Z [debug] [W3C] Encountered internal error running command: Error: No open port found
2019-02-19T02:35:38.143627000Z [debug] [W3C]     at callback (/usr/lib/node_modules/appium/node_modules/portscanner/lib/promisify.js:13:25)
2019-02-19T02:35:38.143761000Z [debug] [W3C]     at /usr/lib/node_modules/appium/node_modules/portscanner/lib/portscanner.js:232:7
2019-02-19T02:35:38.143890000Z [debug] [W3C]     at /usr/lib/node_modules/appium/node_modules/async/dist/async.js:969:16
2019-02-19T02:35:38.144022000Z [debug] [W3C]     at next (/usr/lib/node_modules/appium/node_modules/async/dist/async.js:5225:18)
2019-02-19T02:35:38.144151000Z [debug] [W3C]     at /usr/lib/node_modules/appium/node_modules/portscanner/lib/portscanner.js:219:9
2019-02-19T02:35:38.144279000Z [debug] [W3C]     at Socket.<anonymous> (/usr/lib/node_modules/appium/node_modules/portscanner/lib/portscanner.js:132:5)
2019-02-19T02:35:38.144406000Z [debug] [W3C]     at Socket.emit (events.js:182:13)
2019-02-19T02:35:38.144533000Z [debug] [W3C]     at TCP._handle.close (net.js:610:12)
2019-02-19T02:35:38.144688000Z [HTTP] <-- POST /wd/hub/session 500 167 ms - 521
2019-02-19T02:35:38.144845000Z [HTTP] 
```

**Comment by mykola-mokhnach** [comment]
This means that UIA2 driver cannot find any free port in range `8200..8299` on the host system. Either set the `systemPort` capability or make sure any of these ports is free.

**Comment by yxcSini** [comment]
@mykola-mokhnach Can I expand the range of this port?

**Comment by mykola-mokhnach** [comment]
Only if you change the source code

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
