### ISSUE TITLE
cannot run appium on android 9 

### ISSUE THREAD

**Issue by weiqinxiao** [appium/appium#12188]
## Environment
* Appium version (or git revision) that exhibits the issue:1.11.0-beta.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: mac OS High Siera 10.14.0
* Node.js version (unless using Appium.app|exe): v9.8.0
* Mobile platform/version under test:Android 9
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe:

## Details
cannot run appium on Android 9, but on Android 6.0 is ok.

## Link to Appium logs
[debug] [ADB] Removing forwarded port socket connection: 8200 
[debug] [ADB] Running '/Users/xxx/Library/Android/sdk/platform-tools/adb -P 5037 -s 90cc1a85 forward --remove tcp\:8200'
[UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original error: 'Command '/Users/xxx/Library/Android/sdk/platform-tools/adb -P 5037 -s 90cc1a85 forward --remove tcp\:8200' exited with code 1'; Stderr: 'error: listener 'tcp:8200' not found'; Code: '1''
[UiAutomator2] Restoring hidden api policy to the device default configuration
[debug] [ADB] Running '/Users/xxx/Library/Android/sdk/platform-tools/adb -P 5037 -s 90cc1a85 shell settings delete global hidden_api_policy_pre_p_apps'
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1550548981582 (12:03:01 GMT+0800 (CST))
[debug] [W3C] Encountered internal error running command: Error executing adbExec. Original error: 'Command '/Users/xxx/Library/Android/sdk/platform-tools/adb -P 5037 -s 90cc1a85 shell settings delete global hidden_api_policy_pre_p_apps' exited with code 255'; Stderr: 'Security exception: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
[debug] [W3C] 
[debug] [W3C] java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
[debug] [W3C] 	at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:1815)
[debug] [W3C] 	at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1023)
[debug] [W3C] 	at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1006)
[debug] [W3C] 	at com.android.providers.settings.SettingsProvider.delete(SettingsProvider.java:592)
[debug] [W3C] 	at android.content.ContentProvider$Transport.delete(ContentProvider.java:343)
[debug] [W3C] 	at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:406)
[debug] [W3C] 	at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:289)
[debug] [W3C] 	at android.os.ShellCommand.exec(ShellCommand.java:103)
[debug] [W3C] 	at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:51)
[debug] [W3C] 	at android.os.Binder.shellCommand(Binder.java:634)
[debug] [W3C] 	at android.os.Binder.onTransact(Binder.java:532)
[debug] [W3C] 	at android.os.Binder.execTransact(Binder.java:733)'; Code: '255'
[debug] [W3C] Error: Command '/Users/xxx/Library/Android/sdk/platform-tools/adb -P 5037 -s 90cc1a85 shell settings delete global hidden_api_policy_pre_p_apps' exited with code 255
[debug] [W3C]     at ChildProcess.proc.on.code (/usr/local/lib/node_modules/appium/node_modules/teen_process/lib/exec.js:94:19)
[debug] [W3C]     at ChildProcess.emit (events.js:180:13)
[debug] [W3C]     at maybeClose (internal/child_process.js:936:16)
[debug] [W3C]     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)

**Comment by weiqinxiao** [comment]
fixed，close
