### ISSUE TITLE
Appium settings crashing

### ISSUE THREAD

**Issue by RamatiAriel** [appium/appium#12225]
Hey,
I've encountered a problem with appium settings, I'm getting the "appium settings has stopped" message from time to time.
after investigating little further it seems that I'm getting the following exception:
```
FATAL EXCEPTION: main
[2019-02-25T09:48:10+0200] [ALL] 02-25 09:47:37.427  4305  4305 E AndroidRuntime: Process: io.appium.settings, PID: 4305
[2019-02-25T09:48:10+0200] [ALL] 02-25 09:47:37.427  4305  4305 E AndroidRuntime: java.lang.IllegalStateException: GoogleApiClient is not connected yet.
[2019-02-25T09:48:10+0200] [ALL] 02-25 09:47:37.427  4305  4305 E AndroidRuntime: 	at com.google.android.gms.common.api.internal.zaak.execute(Unknown Source:129)
[2019-02-25T09:48:10+0200] [ALL] 02-25 09:47:37.427  4305  4305 E AndroidRuntime: 	at com.google.android.gms.common.api.internal.zabe.execute(Unknown Source:23)
[2019-02-25T09:48:10+0200] [ALL] 02-25 09:47:37.427  4305  4305 E AndroidRuntime: 	at com.google.android.gms.common.api.internal.zaaw.execute(Unknown Source:74)
[2019-02-25T09:48:10+0200] [ALL] 02-25 09:47:37.427  4305  4305 E AndroidRuntime: 	at com.google.android.gms.internal.location.zzq.requestLocationUpdates(Unknown Source:14)
[2019-02-25T09:48:10+0200] [ALL] 02-25 09:47:37.427  4305  4305 E AndroidRuntime: 	at io.appium.settings.LocationTracker.onConnected(LocationTracker.java:103)
[2019-02-25T09:48:10+0200] [ALL] 02-25 09:47:37.427  4305  4305 E AndroidRuntime: 	at com.google.android.gms.common.internal.GmsClientEventManager.onConnectionSuccess(Unknown Source:34)
[2019-02-25T09:48:10+0200] [ALL] 02-25 09:47:37.427  4305  4305 E AndroidRuntime: 	at com.google.android.gms.common.api.internal.zaaw.zab(Unknown Source:292)
[2019-02-25T09:48:10+0200] [ALL] 02-25 09:47:37.427  4305  4305 E AndroidRuntime: 	at com.google.android.gms.common.api.internal.zaak.zaaq(Unknown Source:125)
[2019-02-25T09:48:10+0200] [ALL] 02-25 09:47:37.427  4305  4305 E AndroidRuntime: 	at com.google.android.gms.common.api.internal.zaak.onConnected(Unknown Source:105)
[2019-02-25T09:48:10+0200] [ALL] 02-25 09:47:37.427  4305  4305 E AndroidRuntime: 	at com.google.android.gms.common.api.internal.zabe.onConnected(Unknown Source:101)
[2019-02-25T09:48:10+0200] [ALL] 02-25 09:47:37.427  4305  4305 E AndroidRuntime: 	at com.google.android.gms.common.api.internal.zaq.onConnected(Unknown Source:6)
[2019-02-25T09:48:10+0200] [ALL] 02-25 09:47:37.427  4305  4305 E AndroidRuntime: 	at com.google.android.gms.common.internal.zaf.onConnected(Unknown Source:2)
[2019-02-25T09:48:10+0200] [ALL] 02-25 09:47:37.427  4305  4305 E AndroidRuntime: 	at com.google.android.gms.common.internal.BaseGmsClient$zzf.zzm(Unknown Source:24)
[2019-02-25T09:48:10+0200] [ALL] 02-25 09:47:37.427  4305  4305 E AndroidRuntime: 	at com.google.android.gms.common.internal.BaseGmsClient$zza.zza(Unknown Source:12)
[2019-02-25T09:48:10+0200] [ALL] 02-25 09:47:37.427  4305  4305 E AndroidRuntime: 	at com.google.android.gms.common.internal.BaseGmsClient$zzc.zzo(Unknown Source:11)
[2019-02-25T09:48:10+0200] [ALL] 02-25 09:47:37.427  4305  4305 E AndroidRuntime: 	at com.google.android.gms.common.internal.BaseGmsClient$zzb.handleMessage(Unknown Source:48)
[2019-02-25T09:48:10+0200] [ALL] 02-25 09:47:37.427  4305  4305 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
[2019-02-25T09:48:10+0200] [ALL] 02-25 09:47:37.427  4305  4305 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
[2019-02-25T09:48:10+0200] [ALL] 02-25 09:47:37.427  4305  4305 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6541)
[2019-02-25T09:48:10+0200] [ALL] 02-25 09:47:37.427  4305  4305 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
[2019-02-25T09:48:10+0200] [ALL] 02-25 09:47:37.427  4305  4305 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
[2019-02-25T09:48:10+0200] [ALL] 02-25 09:47:37.427  4305  4305 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

using appium v1.10 on macOS high sierra
node v11.8.0, npm 6.5.0 using both emulator and real devices (nexus/ pixel /samsung)

i've attached logs from a different run with the same issue
[appium.log](https://github.com/appium/appium/files/2905656/appium.log)

**Comment by KazuCocoa** [comment]
Could you try out 1.11.1?

The latest code probably catches the exception (or avoid).
https://github.com/appium/io.appium.settings/blob/4cec677c0d157125597b37a08f4ba91859608bf0/app/src/main/java/io/appium/settings/LocationTracker.java#L90

**Comment by RamatiAriel** [comment]
I've upgraded- since this is a random issue I'm responding so the thread won't close due to inactivity.
I'll update if this solved the issue,
Thanks

**Comment by imurchie** [comment]
The settings app does not wait at all for Google Play services to be ready.

If, @RamatiAriel, you are comfortable updating the settings app locally to test things out (I can't reproduce this, unfortunately), the first thing I would try to do is increase the timeout on this call: https://github.com/appium/io.appium.settings/blob/master/app/src/main/java/io/appium/settings/Settings.java#L47
```diff
--- a/app/src/main/java/io/appium/settings/Settings.java
+++ b/app/src/main/java/io/appium/settings/Settings.java
@@ -44,7 +44,7 @@ public class Settings extends Activity {
         setContentView(R.layout.main);
         Log.d(TAG, "Entering the app");

-        LocationTracker.getInstance().start(this, 0, true);
+        LocationTracker.getInstance().start(this, 30000, true);

         final List<Class<? extends BroadcastReceiver>> receiverClasses = new ArrayList<>();
         receiverClasses.add(WiFiConnectionSettingReceiver.class);
```

The build and use that, to see if the problem is solved.

**Comment by RamatiAriel** [comment]
Hey,
this issue did not reproduced at this week so i assume this solved the issue.
thanks for the help
