### ISSUE TITLE
npm ERR! Failed at the appium-chromedriver@4.10.1 install script.

### ISSUE THREAD

**Issue by SusanAnna** [appium/appium#12319]
## The problem
Trying to install appium with npm . But getting the above error

## Environment

* Appium version (or git revision) that exhibits the issue: Latest version as i am trying command _npm install -g appium_
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): Version 10.15.3
* Npm or Yarn package manager: 6.4.1
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

```
C:\Users\sdsouza>npm install -g appium
npm WARN deprecated fsevents@2.0.1: Not Ready For Production
C:\Users\sdsouza\AppData\Roaming\npm\appium -> C:\Users\sdsouza\AppData\Roaming\npm\node_modules\appium\build\lib\main.js

> appium-chromedriver@4.10.1 install C:\Users\sdsouza\AppData\Roaming\npm\node_modules\appium\node_modules\appium-chromedriver
> node install-npm.js

[22:12:50] [Chromedriver Install] Installing Chromedriver version '2.31 npm install appium' for platform 'win' and architecture '32'
[22:12:50] [Chromedriver Install] Opening temp file to write 'chromedriver_win32' to...
[22:12:50] [Chromedriver Install] Opened temp file 'C:\Users\sdsouza\AppData\Local\Temp\2019215-10296-l9kp8m.o6q7\chromedriver_win32.zip'
[22:12:50] [Chromedriver Install] Downloading https://chromedriver.storage.googleapis.com/2.31 npm install appium/chromedriver_win32.zip...
StatusCodeError: 404 - "<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: chromedriver/2.31 npm install appium/chromedriver_win32.zip</Details></Error>"
    at new StatusCodeError (C:\Users\sdsouza\AppData\Roaming\npm\node_modules\appium\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (C:\Users\sdsouza\AppData\Roaming\npm\node_modules\appium\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\Users\sdsouza\AppData\Roaming\npm\node_modules\appium\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (C:\Users\sdsouza\AppData\Roaming\npm\node_modules\appium\node_modules\request\request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.<anonymous> (C:\Users\sdsouza\AppData\Roaming\npm\node_modules\appium\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:189:13)
    at IncomingMessage.<anonymous> (C:\Users\sdsouza\AppData\Roaming\npm\node_modules\appium\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.1 (node_modules\appium\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appium-chromedriver@4.10.1 install: `node install-npm.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the appium-chromedriver@4.10.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sdsouza\AppData\Roaming\npm-cache\_logs\2019-03-15T16_43_28_055Z-debug.log
```

## Code To Reproduce Issue [ Good To Have ]
npm install -g appium

**Comment by dpgraham** [comment]
It's trying to download https://chromedriver.storage.googleapis.com/2.31 (broken link)... should be downloading https://chromedriver.storage.googleapis.com/2.31/chromedriver_win32.zip

I'll need to have a look at this to see what's wrong with the downloading logic.

@imurchie does anything jump out at you? And is there a workaround for this? Would running `npm install -g appium-chromedriver@2.31` before `npm install -g appium` make this problem go away?

**Comment by imurchie** [comment]
Nothing jumps out at me. But I will explore a bit

**Comment by imurchie** [comment]
@SusanAnna How are you specifying the version of Chromedriver being downloaded? For some reason it appears to be getting in as `'2.31 npm install appium'`, which is breaking everything.

**Comment by SusanAnna** [comment]
I am not exclusively trying for chromedriver. I type the following command and then eventually we get this error


npm install -g appium

**Comment by SusanAnna** [comment]
Is there a workaround that an fix this quickly and allow me to proceed with installation ?

**Comment by imurchie** [comment]
Yes, `npm install -g appium-chromedriver@2.31` will never work.

This is odd. By default, `appium-chromedriver` version 4.10.1 (the version from your original logs) ought to be installing Chromedriver 2.45.

To change the Chromedriver version (to, say, `2.31`) either the `npm install` command needs the flag `--chromedriver_version="2.31"` or the environment variable `CHROMEDRIVER_VERSION` needs to be set to the version.

Is the `CHROMEDRIVER_VERSION` environment variable set? 

Also, can you post, as a link to a [gist](https://gist.github.com) the contents of C:\Users\sdsouza\AppData\Roaming\npm-cache\_logs\2019-03-15T16_43_28_055Z-debug.log

**Comment by SusanAnna** [comment]
No, the environment variable is not set. 
I tried the above mentioned once again now , and found the following logs
npm install -g appium --chromedriver_version='2.31' 

npm WARN deprecated fsevents@2.0.1: Not Ready For Production
C:\Users\sdsouza\AppData\Roaming\npm\appium -> C:\Users\sdsouza\AppData\Roaming\npm\node_modules\appium\build\lib\main.js

> appium-chromedriver@4.10.1 install C:\Users\sdsouza\AppData\Roaming\npm\node_modules\appium\node_modules\appium-chromedriver
> node install-npm.js

[22:46:56] [Chromedriver Install] Installing Chromedriver version ''2.31'' for platform 'win' and architecture '32'
[22:46:56] [Chromedriver Install] Opening temp file to write 'chromedriver_win32' to...
[22:46:56] [Chromedriver Install] Opened temp file 'C:\Users\sdsouza\AppData\Local\Temp\2019218-6572-u46xer.641x\chromedriver_win32.zip'
[22:46:56] [Chromedriver Install] Downloading https://chromedriver.storage.googleapis.com/'2.31'/chromedriver_win32.zip...
StatusCodeError: 404 - "<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: chromedriver/'2.31'/chromedriver_win32.zip</Details></Error>"
    at new StatusCodeError (C:\Users\sdsouza\AppData\Roaming\npm\node_modules\appium\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (C:\Users\sdsouza\AppData\Roaming\npm\node_modules\appium\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\Users\sdsouza\AppData\Roaming\npm\node_modules\appium\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (C:\Users\sdsouza\AppData\Roaming\npm\node_modules\appium\node_modules\request\request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.<anonymous> (C:\Users\sdsouza\AppData\Roaming\npm\node_modules\appium\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:189:13)
    at IncomingMessage.<anonymous> (C:\Users\sdsouza\AppData\Roaming\npm\node_modules\appium\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.1 (node_modules\appium\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appium-chromedriver@4.10.1 install: `node install-npm.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the appium-chromedriver@4.10.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sdsouza\AppData\Roaming\npm-cache\_logs\2019-03-18T17_17_37_448Z-debug.log

**Comment by SusanAnna** [comment]
[2019-03-18T17_17_37_448Z-debug.zip](https://github.com/appium/appium/files/2979415/2019-03-18T17_17_37_448Z-debug.zip)

**Comment by SusanAnna** [comment]
PFA logs

**Comment by SnehPandya18** [comment]
Particularly for me, this command worked:
`npm install -g appium --unsafe-perm=true --allow-root`

I am using Manjaro 18 latest stable edition, could successfully "install-npm.js" using node :)

**Comment by SusanAnna** [comment]
Woow , I am glad that fixed the issue. PFB logs


C:\Users\sdsouza>npm install -g appium --unsafe-perm=true --allow-root
npm WARN deprecated fsevents@2.0.1: Not Ready For Production
C:\Users\sdsouza\AppData\Roaming\npm\appium -> C:\Users\sdsouza\AppData\Roaming\npm\node_modules\appium\build\lib\main.js

> appium-chromedriver@4.10.1 install C:\Users\sdsouza\AppData\Roaming\npm\node_modules\appium\node_modules\appium-chromedriver
> node install-npm.js

[11:47:52] [Chromedriver Install] Installing Chromedriver version '2.45' for platform 'win' and architecture '32'
[11:47:52] [Chromedriver Install] Opening temp file to write 'chromedriver_win32' to...
[11:47:52] [Chromedriver Install] Opened temp file 'C:\Users\sdsouza\AppData\Local\Temp\2019219-15112-r1x1t5.otyfj\chromedriver_win32.zip'
[11:47:52] [Chromedriver Install] Downloading https://chromedriver.storage.googleapis.com/2.45/chromedriver_win32.zip...
[11:47:57] [Chromedriver Install] Writing binary content to C:\Users\sdsouza\AppData\Local\Temp\2019219-15112-r1x1t5.otyfj\chromedriver_win32.zip...
[11:47:57] [Chromedriver Install] Extracting C:\Users\sdsouza\AppData\Local\Temp\2019219-15112-r1x1t5.otyfj\chromedriver_win32.zip to C:\Users\sdsouza\AppData\Local\Temp\2019219-15112-r1x1t5.otyfj\chromedriver_win32
[11:47:58] [Chromedriver Install] Creating C:\Users\sdsouza\AppData\Roaming\npm\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win...
[11:47:58] [Chromedriver Install] Copying unzipped binary, reading from C:\Users\sdsouza\AppData\Local\Temp\2019219-15112-r1x1t5.otyfj\chromedriver_win32\chromedriver.exe...
[11:47:58] [Chromedriver Install] Writing to C:\Users\sdsouza\AppData\Roaming\npm\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe...
[11:47:58] [Chromedriver Install] C:\Users\sdsouza\AppData\Roaming\npm\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe successfully put in place

> appium-selendroid-driver@1.13.3 install C:\Users\sdsouza\AppData\Roaming\npm\node_modules\appium\node_modules\appium-selendroid-driver
> node ./bin/install.js

[11:48:20] Java version 10.0.1 found
[11:48:21] Ensuring C:\Users\sdsouza\AppData\Roaming\npm\node_modules\appium\node_modules\appium-selendroid-driver\selendroid\download exists
[11:48:21] Downloading Selendroid standalone server version 0.17.0 from https://repo1.maven.org/maven2/io/selendroid/selendroid-standalone/0.17.0/selendroid-standalone-0.17.0-with-dependencies.jar --> C:\Users\sdsouza\AppData\Roaming\npm\node_modules\appium\node_modules\appium-selendroid-driver\selendroid\download\selendroid-server-7cf7163ac47f1c46eff95b62f78b58c1dabdec534acc6632da3784739f6e9d82.jar
[11:48:35] Writing binary content to C:\Users\sdsouza\AppData\Roaming\npm\node_modules\appium\node_modules\appium-selendroid-driver\selendroid\download\selendroid-server.jar.tmp
[11:48:35] Selendroid standalone server downloaded
[11:48:35] Determining AndroidManifest location
[11:48:35] Determining server apk location
[11:48:36] Extracting manifest and apk to C:\Users\sdsouza\AppData\Roaming\npm\node_modules\appium\node_modules\appium-selendroid-driver\selendroid\download
[11:48:36] Copying manifest and apk to C:\Users\sdsouza\AppData\Roaming\npm\node_modules\appium\node_modules\appium-selendroid-driver\selendroid
[11:48:36] Cleaning up temp files
[11:48:36] Fixing AndroidManifest icon bug

> appium-windows-driver@1.5.1 install C:\Users\sdsouza\AppData\Roaming\npm\node_modules\appium\node_modules\appium-windows-driver
> node install-npm.js

info WinAppDriver You must use WinAppDriver version 1.1
info WinAppDriver Verifying WinAppDriver version 1.1 is installed via comparing the checksum.
info WinAppDriver WinAppDriver.exe doesn't exist at the correct version 1.1, setting up
WARNING: You are not running as an administrator so WinAppDriver cannot be installed for you; please reinstall as admin
WinAppDriver was not installed; please check your system and re-run npm install if you need WinAppDriver

> heapdump@0.3.12 install C:\Users\sdsouza\AppData\Roaming\npm\node_modules\appium\node_modules\heapdump
> node-gyp rebuild


C:\Users\sdsouza\AppData\Roaming\npm\node_modules\appium\node_modules\heapdump>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\sdsouza\AppData\Roaming\npm\node_modules\appium\node_modules\heapdump
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.1 (node_modules\appium\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: heapdump@0.3.12 (node_modules\appium\node_modules\heapdump):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: heapdump@0.3.12 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ appium@1.11.1
added 557 packages from 392 contributors in 183.904s

**Comment by imurchie** [comment]
I'm glad that was resolved. The original issue still makes no sense to me, but resolution is more important. Thanks everyone!
