### ISSUE TITLE
bug: Android Q kill process by name not permitted

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#12334]
Attempts to root the Android Q emulator are failing with `adbd cannot run as root in production builds` which makes `killProcessesByName` fail with `Operation not permitted'; Code: '1'`

Logs:

```
  adb commands
info ADB Checking whether adb is present
info ADB Found 10 'build-tools' folders under '/Users/danielgraham/Library/Android/sdk' (newest first):
info ADB     /Users/danielgraham/Library/Android/sdk/build-tools/28.0.3
info ADB     /Users/danielgraham/Library/Android/sdk/build-tools/27.0.3
info ADB     /Users/danielgraham/Library/Android/sdk/build-tools/27.0.1
info ADB     /Users/danielgraham/Library/Android/sdk/build-tools/26.0.2
info ADB     /Users/danielgraham/Library/Android/sdk/build-tools/26.0.1
info ADB     /Users/danielgraham/Library/Android/sdk/build-tools/25.0.3
info ADB     /Users/danielgraham/Library/Android/sdk/build-tools/25.0.0
info ADB     /Users/danielgraham/Library/Android/sdk/build-tools/24.0.1
info ADB     /Users/danielgraham/Library/Android/sdk/build-tools/23.0.1
info ADB     /Users/danielgraham/Library/Android/sdk/build-tools/23.0.0
info ADB Using adb from /Users/danielgraham/Library/Android/sdk/platform-tools/adb
dbug ADB Running '/Users/danielgraham/Library/Android/sdk/platform-tools/adb -P 5037 shell getprop ro.build.version.sdk'
dbug ADB Current device property 'ro.build.version.sdk': 28
dbug ADB Device API level: 28
dbug ADB Running '/Users/danielgraham/Library/Android/sdk/platform-tools/adb -P 5037 install -r /Users/danielgraham/appium-adb/test/fixtures/ContactManager.apk'
dbug ADB Install command stdout: Success
dbug ADB Running '/Users/danielgraham/Library/Android/sdk/platform-tools/adb -P 5037 shell am start -W -n com.example.android.contactmanager/ContactManager -S'
dbug ADB We tried to start an activity that doesn't exist, retrying with '.ContactManager' activity name
dbug ADB Running '/Users/danielgraham/Library/Android/sdk/platform-tools/adb -P 5037 shell am start -W -n com.example.android.contactmanager/.ContactManager -S'
dbug ADB Attempting to kill all com.example.android.contactmanager processes
dbug ADB Getting IDs of all 'com.example.android.contactmanager' processes
dbug ADB Running '/Users/danielgraham/Library/Android/sdk/platform-tools/adb -P 5037 shell 'pgrep --help; echo $?''
dbug ADB Running '/Users/danielgraham/Library/Android/sdk/platform-tools/adb -P 5037 shell pgrep -f \^com\\.example\\.android\\.contactmanager\$'
dbug ADB Attempting to kill process 30527
dbug ADB Running '/Users/danielgraham/Library/Android/sdk/platform-tools/adb -P 5037 shell kill -0 30527'
dbug ADB Running '/Users/danielgraham/Library/Android/sdk/platform-tools/adb -P 5037 shell whoami'
info ADB Cannot kill PID 30527 due to insufficient permissions. Retrying as root
WARN ADB Unable to root adb daemon: 'adbd cannot run as root in production builds'. Continuing
dbug ADB Running '/Users/danielgraham/Library/Android/sdk/platform-tools/adb -P 5037 shell kill -0 30527'
    1) killProcessesByName should kill process


  0 passing (6s)
  1 failing

  1) adb commands
       killProcessesByName should kill process:
     Error: Unable to kill com.example.android.contactmanager processes. Original error: Error executing adbExec. Original error: 'Command '/Users/danielgraham/Library/Android/sdk/platform-tools/adb -P 5037 shell kill -0 30527' exited with code 1'; Stderr: '/system/bin/sh: kill: 30527: Operation not permitted'; Code: '1'
      at ADB.<anonymous> (lib/tools/adb-commands.js:1252:11)
      at Generator.throw (<anonymous>)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _throw (node_modules/@babel/runtime/helpers/asyncToGenerator.js:29:9)
```

**Comment by mykola-mokhnach** [comment]
This is probably Google's bug. It should be possible to run adb as root on Emulators

**Comment by dpgraham** [comment]
Yeah I thought that might be the case too. I'll leave this issue open just to keep track of it.

**Comment by KazuCocoa** [comment]
link: https://github.com/appium/appium/issues/12311

**Comment by KazuCocoa** [comment]
ah... Has this been fixed?
https://dev.azure.com/AppiumCI/Appium%20CI/_build/results?buildId=5373

**Comment by dpgraham** [comment]
I think so!

**Comment by KazuCocoa** [comment]
👍 🎉
