### ISSUE TITLE
Appium 1.11.1 zipAlignApk failed if AutomationName=UIAUTOMATOR2, works if APPIUM

### ISSUE THREAD

**Issue by benfr1** [appium/appium#12355]
## The problem
 test stops at the beginning " Original error: zipAlignApk failed." if AutomationName = ANDROID_UIAUTOMATOR2

## Environment

* Appium version (or git revision) that exhibits the issue: 1.11.1, appium beta 
* Last Appium version that did not exhibit the issue (if applicable):N/A
* Desktop OS/version used to run Appium:windows 10
* Node.js version (unless using Appium.app|exe): v8.11.3
* Npm or Yarn package manager:5.6.0
* Mobile platform/version under test: Samsung S8, android 7.0
* Real device or emulator/simulator:Real
* Appium CLI or Appium.app|exe:

## Details
happens with : caps.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.ANDROID_UIAUTOMATOR2)
however,
the mentioned file exists  and can be open with 7-zip.
C:\Users\***\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v3.2.2.apk

it does not happen if caps.setCapability("automationName" , "Appium" ); and works fine.

## Link to Appium logs
org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: zipAlignApk failed. Original error: Command 'C\:\\Users\\xxx\\AppData\\Local\\Android\\Sdk\\build-tools\\28.0.3\\zipalign.exe -f 4 C\:\\Users\\xxx\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-v3.2.2.apk C\:\\Users\\xxx\\AppData\\Local\\Temp\\2019220-7052-kpw3v8.5ockb\\appium.tmp' exited with code 1. Stdout: ''; Stderr: 'Unable to open 'C:\Users\xxx\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v3.2.2.apk' as zip archive
'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'B998695', ip: '10.82.59.181', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.2'
Driver info: driver.version: AppiumDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: zipAlignApk failed. Original error: Command 'C\:\\Users\\xxx\\AppData\\Local\\Android\\Sdk\\build-tools\\28.0.3\\zipalign.exe -f 4 C\:\\Users\\xxx\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-v3.2.2.apk C\:\\Users\\xxx\\AppData\\Local\\Temp\\2019220-7052-kpw3v8.5ockb\\appium.tmp' exited with code 1. Stdout: ''; Stderr: 'Unable to open 'C:\Users\xxx\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v3.2.2.apk' as zip archive
'
    at getResponseForW3CError (C:\Users\xxx\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:826:9)
    at asyncHandler (C:\Users\xxx\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:447:37)
    at <anonymous>
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'B998695', ip: '10.82.59.181', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.2'
Driver info: driver.version: AppiumDriver

## Code To Reproduce Issue [ Good To Have ]

Please see details

**Comment by mykola-mokhnach** [comment]
Make sure the appium process has R/W permissions in `C:\Users\xxx\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\` folder

**Comment by mykola-mokhnach** [comment]
Did you also try to execute the command above manually?

**Comment by benfr1** [comment]
ok the directory was read only. in effect the error has disappeared.
I think you can close the issue.
please note that now it fails, Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not sign with default certificate. 
but I will take a look separately.
thanks a lot 🥇

**Comment by benfr1** [comment]
SOLUTION: set a RW or remove RO from directory C:\Users\xxx\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks
