### ISSUE TITLE
Not able to find elements using any locators for my mobile app

### ISSUE THREAD

**Issue by sensuraj92** [appium/appium#12359]
Not able to find elements using any locators for my mobile app

Hello,

I am not able find elements of my mobile app either from ID,X-PATH or classname

getting below exception

attached screenshot of code and app elements

please help in resolving the same

Exception in thread "main" org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters.

For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html

Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'

System info: host: 'AGI-LT-915', ip: '192.168.187.122', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_201'

Driver info: io.appium.java_client.android.AndroidDriver

Capabilities {app: D:\selenium\Workspace\eCOA\..., appActivity: cordova.LSeCOA.Production.M..., appPackage: cordova.LSeCOA.Production, appWaitActivity: cordova.LSeCOA.Production.M..., appWaitPackage: cordova.LSeCOA.Production, databaseEnabled: false, desired: {app: D:\selenium\Workspace\eCOA\..., deviceName: EDC, platformName: android}, deviceManufacturer: Google, deviceModel: Android SDK built for x86, deviceName: emulator-5554, deviceScreenSize: 1080x1920, deviceUDID: emulator-5554, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, platform: LINUX, platformName: Android, platformVersion: 8.1.0, takesScreenshot: true, warnings: {}, webStorageEnabled: false}

Session ID: 91b562da-f9aa-4cab-b6c5-9a69eeda88c6

*** Element info: {Using=id, value=serviceUrl}

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)

at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)

at java.lang.reflect.Constructor.newInstance(Unknown Source)

at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)

at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)

at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)

at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)

at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)

at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)

at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)

at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)

at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)

at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)

at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:62)

at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)

at io.appium.java_client.android.AndroidDriver.findElement(AndroidDriver.java:1)

at org.openqa.selenium.remote.RemoteWebDriver.findElementById(RemoteWebDriver.java:372)

at io.appium.java_client.DefaultGenericMobileDriver.findElementById(DefaultGenericMobileDriver.java:70)

at io.appium.java_client.AppiumDriver.findElementById(AppiumDriver.java:1)

at io.appium.java_client.android.AndroidDriver.findElementById(AndroidDriver.java:1)

at eCOA.login.main(login.java:17)
![code](https://user-images.githubusercontent.com/41458305/54745442-8a3c8600-4bef-11e9-920b-6573454ad91a.PNG)
![elements](https://user-images.githubusercontent.com/41458305/54745447-8e68a380-4bef-11e9-9349-5b561f02fb98.PNG)

thanks in advance

**Comment by mykola-mokhnach** [comment]
Please use appium forum for questions.
