### ISSUE TITLE
Appium server is returning 200 code but java error occurred after code execution

### ISSUE THREAD

**Issue by ajayunnam** [appium/appium#12360]
## The problem

Appium server returned with /wd/hub/session/790979f5-9836-4986-88ba-4e7b46dcca45 200 but error occurred in with main method as below

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

Mar 21, 2019 4:22:33 PM io.appium.java_client.remote.AppiumCommandExecutor$1 lambda$0
INFO: Detected dialect: W3C
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils
	at io.appium.java_client.HasSessionDetails.lambda$0(HasSessionDetails.java:49)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at com.google.common.collect.CollectSpliterators$1.lambda$forEachRemaining$1(CollectSpliterators.java:117)
	at java.util.Iterator.forEachRemaining(Unknown Source)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at com.google.common.collect.CollectSpliterators$1.forEachRemaining(CollectSpliterators.java:117)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.collect(Unknown Source)
	at io.appium.java_client.HasSessionDetails.getSessionDetails(HasSessionDetails.java:52)
	at io.appium.java_client.HasSessionDetails.getSessionDetail(HasSessionDetails.java:56)
	at io.appium.java_client.HasSessionDetails.getPlatformName(HasSessionDetails.java:65)
	at io.appium.java_client.internal.JsonToMobileElementConverter.<init>(JsonToMobileElementConverter.java:49)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:89)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:94)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:95)
	at com.ajay.test.Base.main(Base.java:21)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.StringUtils
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 19 more

## Link to Appium logs

[HTTP] --> GET /wd/hub/session/790979f5-9836-4986-88ba-4e7b46dcca45
[HTTP] {}
[W3C (790979f5)] Calling AppiumDriver.getSession() with args: ["790979f5-9836-4986-88ba-4e7b46dcca45"]
[W3C (790979f5)] Responding to client with driver.getSession() result: {"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platformName":"android","app":"C:\\Users\\pc\\Appium\\appiumtutorial\\src\\ApiDemos-debug.apk","deviceName":"Galaxy A6+"},"platformName":"android","app":"C:\\Users\\pc\\Appium\\appiumtutorial\\src\\ApiDemos-debug.apk","deviceName":"0f46902b","deviceUDID":"0f46902b","platformVersion":"8.0.0","deviceScreenSize":"1080x2220","deviceModel":"SM-A605G","deviceManufacturer":"samsung","appPackage":"io.appium.android.apis","appWaitPackage":"io.appium.android.apis","appActivity":"io.appium.android.apis.ApiDemos","appWaitActivity":"io.appium.android.apis.ApiDemos"}
[HTTP] <-- GET /wd/hub/session/790979f5-9836-4986-88ba-4e7b46dcca45 200 21 ms -

## Code To Reproduce Issue [ Good To Have ]

package com.ajju.test;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.remote.DesiredCapabilities;

import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.android.AndroidElement;
import io.appium.java_client.remote.MobileCapabilityType;

public class Base {
	public static void main(String[] args) throws MalformedURLException {
		File f = new File("src");
		File fs = new File(f, "ApiDemos-debug.apk");
		DesiredCapabilities cap = new DesiredCapabilities();
		cap.setCapability(MobileCapabilityType.DEVICE_NAME, "Galaxy A6+");
		cap.setCapability(MobileCapabilityType.APP, fs.getAbsolutePath());
		AndroidDriver<AndroidElement> driver = new AndroidDriver<>(new URL("http://127.0.0.1:4723/wd/hub"), cap);

		driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
	}
}

**Comment by mykola-mokhnach** [comment]
Moved to java client
