### ISSUE TITLE
appium-adb: disableIME not working on SDK 28

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#12448]
## The problem

The `disableIME` method in http://github.com/appium/appium-adb calls `adb -P 5037 shell ime enable com.google.android.apps.inputmethod/.SoftKeyboard` which gives the error:

```
Exception occurred while executing:
java.lang.IllegalArgumentException: Unknown id: com.google.android.inputmethod.pinyin/.PinyinIME
        at com.android.server.InputMethodManagerService.setInputMethodEnabledLocked(InputMethodManagerService.java:3991)
        at com.android.server.InputMethodManagerService.handleShellCommandEnableDisableInputMethod(InputMethodManagerService.java:4962)
        at com.android.server.InputMethodManagerService.access$1600(InputMethodManagerService.java:181)
        at com.android.server.InputMethodManagerService$ShellCommandImpl.onCommand(InputMethodManagerService.java:4753)
        at android.os.ShellCommand.exec(ShellCommand.java:103)
        at com.android.server.InputMethodManagerService.onShellCommand(InputMethodManagerService.java:4719)
        at android.os.Binder.shellCommand(Binder.java:634)
        at android.os.Binder.onTransact(Binder.java:532)
        at com.android.internal.view.IInputMethodManager$Stub.onTransact(IInputMethodManager.java:486)
        at com.android.server.InputMethodManagerService.onTransact(InputMethodManagerService.java:1497)
        at android.os.Binder.execTransact(Binder.java:731)
```

## Details

Only happens SDK 28, doesn't happen on 25 or 23.

## Code To Reproduce Issue [ Good To Have ]

Just run `adb -P 5037 shell ime enable com.google.android.apps.inputmethod/.SoftKeyboard` when a 28 emulator is running.

**Comment by KazuCocoa** [comment]
mmm.
It looks working on my env both real and emulator devices like below. (It works for non io.appium.settings like `com.google.android.inputmethod.latin/com.android.inputmethod.latin.LatinIME`)

```
$ adb shell ime disable io.appium.settings/.UnicodeIME
Input method io.appium.settings/.UnicodeIME: now disabled
$ adb shell ime enable io.appium.settings/.UnicodeIME
Input method io.appium.settings/.UnicodeIME: now enabled
```

**Comment by dpgraham** [comment]
Maybe it's specific to the emulator.

**Comment by KazuCocoa** [comment]
ah...

One my experience happened similar issue was:

1. Failed to install io.appium.settings app
2. Called `adb shell ime enable io.appium.settings/.UnicodeIME`
3. But the id did not exists, and got an error like `java.lang.IllegalArgumentException: Unknown id: com.google.android.inputmethod.pinyin/.PinyinIME` (The unknown id was picked randomly from existing ime name.)

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium/issues/12418 is related to the above comment about failing to install io.appium.settings. It raised the IME error. The latest master has a retry logic to install io.appium.settings

**Comment by dpgraham** [comment]
@KazuCocoa latest master of which repo?

This test is still failing in ADB: https://dev.azure.com/AppiumCI/Appium%20CI/_build/results?buildId=1783&view=ms.vss-test-web.build-test-results-tab

**Comment by KazuCocoa** [comment]
Over android-driver 4.13.0+
mmm, the test is calling adb, i see.

What about getting IME by [availableIMEs](https://github.com/appium/appium-adb/blob/d02d370d3ab4f6f01ffbe36d1ce3a08f9ea4535d/lib/tools/adb-commands.js#L431) and use one of it to disable/enable IME?
https://github.com/appium/appium-adb/blob/3bcfef9496a9ea2b5b2a4ee97bd579a5673ede0e/test/functional/adb-commands-e2e-specs.js#L52

**Comment by dpgraham** [comment]
I'm trying it with a different IME. Worked locally, waiting for CI result.
