### ISSUE TITLE
Unable to install Appium on Ubuntu 18.04

### ISSUE THREAD

**Issue by aipi** [appium/appium#12552]
I am trying to install appium@1.12.1 on Ubuntu 18.04 and its installation has broken with the following message:

```shell
> heapdump@0.3.12 install /home/aipi/Downloads/node_modules/appium/node_modules/heapdump
> node-gyp rebuild

make: Entering directory '/home/aipi/Downloads/node_modules/appium/node_modules/heapdump/build'
  CXX(target) Release/obj.target/addon/src/heapdump.o
In file included from /home/aipi/.node-gyp/12.0.0/include/node/node_object_wrap.h:26:0,
                 from ../../nan/nan.h:55,
                 from ../src/heapdump.cc:17:
../../nan/nan_object_wrap.h: In destructor ‘virtual Nan::ObjectWrap::~ObjectWrap()’:
../../nan/nan_object_wrap.h:24:25: error: ‘class Nan::Persistent<v8::Object>’ has no member named ‘IsNearDeath’
     assert(persistent().IsNearDeath());
                         ^
../../nan/nan_object_wrap.h: In static member function ‘static void Nan::ObjectWrap::WeakCallback(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’:
../../nan/nan_object_wrap.h:127:26: error: ‘class Nan::Persistent<v8::Object>’ has no member named ‘IsNearDeath’
     assert(wrap->handle_.IsNearDeath());
                          ^
../src/heapdump.cc: In function ‘void {anonymous}::Initialize(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’:
../src/heapdump.cc:128:67: error: no matching function for call to ‘v8::FunctionTemplate::GetFunction()’
            Nan::New<v8::FunctionTemplate>(Configure)->GetFunction());
                                                                   ^
In file included from /home/aipi/.node-gyp/12.0.0/include/node/node.h:63:0,
                 from ../src/heapdump.cc:15:
/home/aipi/.node-gyp/12.0.0/include/node/v8.h:5947:46: note: candidate: v8::MaybeLocal<v8::Function> v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>)
   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
                                              ^~~~~~~~~~~
/home/aipi/.node-gyp/12.0.0/include/node/v8.h:5947:46: note:   candidate expects 1 argument, 0 provided
../src/heapdump.cc:131:71: error: no matching function for call to ‘v8::FunctionTemplate::GetFunction()’
            Nan::New<v8::FunctionTemplate>(WriteSnapshot)->GetFunction());
                                                                       ^
In file included from /home/aipi/.node-gyp/12.0.0/include/node/node.h:63:0,
                 from ../src/heapdump.cc:15:
/home/aipi/.node-gyp/12.0.0/include/node/v8.h:5947:46: note: candidate: v8::MaybeLocal<v8::Function> v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>)
   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
                                              ^~~~~~~~~~~
/home/aipi/.node-gyp/12.0.0/include/node/v8.h:5947:46: note:   candidate expects 1 argument, 0 provided
addon.target.mk:107: recipe for target 'Release/obj.target/addon/src/heapdump.o' failed
make: *** [Release/obj.target/addon/src/heapdump.o] Error 1
make: Leaving directory '/home/aipi/Downloads/node_modules/appium/node_modules/heapdump/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Linux 4.15.0-47-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/aipi/Downloads/node_modules/appium/node_modules/heapdump
gyp ERR! node -v v12.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN saveError ENOENT: no such file or directory, open '/home/aipi/Downloads/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/aipi/Downloads/package.json'
npm WARN Downloads No description
npm WARN Downloads No repository field.
npm WARN Downloads No README data
npm WARN Downloads No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.6 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.6: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: heapdump@0.3.12 (node_modules/appium/node_modules/heapdump):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: heapdump@0.3.12 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ appium@1.12.1
updated 1 package and audited 161537 packages in 3.872s
found 2 vulnerabilities (1 low, 1 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details

```
I have no idea how can I solve it. Any help? I am following this tutorial to install: https://medium.com/testcult/configuring-appium-in-ubuntu-from-scratch-a9f8edc02d13

**Comment by mykola-mokhnach** [comment]
This is fine. `heapdump` is an optional dependency, so you can simply ignore these error message as Appium is anyway installed successfully.
