### ISSUE TITLE
Error: Cannot find module './runtime'

### ISSUE THREAD

**Issue by WESTBTC** [appium/appium#12565]
C:\Users\Ben-Test>appium
Error: Cannot find module './runtime'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Ben-Test\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\index.js:19:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

C:\Users\Ben-Test>

**Comment by dpgraham** [comment]
Please open a new issue with the template filled out.
