### ISSUE TITLE
Session delete doesn't work with webDriverAgentUrl

### ISSUE THREAD

**Issue by umutuzgur** [appium/appium#12584]
## The problem

iOS testing is failing on Appium 1.13.0 when webDriverAgentUrl is set

## Environment

* Appium version (or git revision) that exhibits the issue: 1.13.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Osx
* Node.js version (unless using Appium.app|exe): 8.16.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS and all xcuitest tests
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: Appium CLI 

## Details

session delete fails when webDriverAgentUrl cap is set

## Link to Appium logs
```
14:53:57 V [debug] [WD Proxy] Proxying [DELETE /session/e1fa7a7a-5eee-4a0c-a9c8-a181f1e05893] to [DELETE http://10.103.32.15:5710/session/B80F66B0-3180-4896-AF8E-22A369725ADD] with no body
11214:53:58 V [debug] [WD Proxy] Got response with status 200: "{\n  \"value\" : {\n\n  },\n  \"sessionId\" : \"F21E3E3B-4047-4E6B-8598-9DBE64CA0B55\",\n  \"status\" : 0\n}"
11314:53:59 V [XCUITest] Cannot retrieve WDA build settings. Original error: Command 'xcodebuild -project /Users/ios/appium/appium/1.13.0/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -showBuildSettings' exited with code 66
11414:53:59 V [Appium] Had trouble ending session e1fa7a7a-5eee-4a0c-a9c8-a181f1e05893: Path must be a string. Received undefined
11514:53:59 V [debug] [BaseDriver] Event 'quitSessionFinished' logged at 1556895239037 (16:53:59 GMT+0200 (CEST))
11614:53:59 V [debug] [MJSONWP (e1fa7a7a)] Encountered internal error running command: TypeError: Path must be a string. Received undefined
11714:53:59 V [debug] [MJSONWP (e1fa7a7a)]     at assertPath (path.js:28:11)
11814:53:59 V [debug] [MJSONWP (e1fa7a7a)]     at Object.normalize (path.js:1199:5)
11914:53:59 V [debug] [MJSONWP (e1fa7a7a)]     at XCUITestDriver.normalize [as deleteSession] (/Users/ios/appium/appium/1.13.0/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:610:39)
12014:53:59 V [debug] [MJSONWP (e1fa7a7a)]     at <anonymous>
12114:53:59 V [HTTP] <-- DELETE /wd/hub/session/e1fa7a7a-5eee-4a0c-a9c8-a181f1e05893 500 1579 ms - 212
```

## Code To Reproduce Issue [ Good To Have ]

Any iOS test that runs with webDriverAgentUrl

**Comment by imurchie** [comment]
For now, can you try setting the `derivedDataPath` desired capability?

**Comment by mykola-mokhnach** [comment]
The fix has been published to beta
