### ISSUE TITLE
ERROR: dump failed because no AndroidManifest.xml found

### ISSUE THREAD

**Issue by edgarjrg** [appium/appium#12587]
## The problem

A few months ago i useed appium exactly as today and it worked fine, a few days ago i started seeing this new error that could not launch the app.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.13.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: v1.13.0
* Node.js version (unless using Appium.app|exe): v8.15.0
* Npm or Yarn package manager: yarn@1.13.0
* Mobile platform/version under test: Android & iOS
* Real device or emulator/simulator: emulator: Pixel2xl $ real device: Moto G Play (android 7.1.1)
* Appium CLI or Appium.app|exe: Both  

## Details

This is a small part of the log: 

I tried to find issues with `[debug] [W3C] ERROR: dump failed because no AndroidManifest.xml found`but found nothing related, and this issue did not happened before.

```
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [ADB] Removing forwarded port socket connection: 8200
[debug] [ADB] Running '/Users/edgarrodriguez/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward --remove tcp\:8200'
[UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original error: 'Command '/Users/edgarrodriguez/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward --remove tcp\:8200' exited with code 1'; Stderr: 'adb: error: listener 'tcp:8200' not found'; Code: '1''
[UiAutomator2] Restoring hidden api policy to the device default configuration
[debug] [ADB] Running '/Users/edgarrodriguez/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell settings delete global hidden_api_policy_pre_p_apps'
[debug] [ADB] Running '/Users/edgarrodriguez/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell settings delete global hidden_api_policy_p_apps'
[debug] [ADB] Running '/Users/edgarrodriguez/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell settings delete global hidden_api_policy'
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1556915783426 (16:36:23 GMT-0400 (-04))
[debug] [W3C] Encountered internal error running command: Error: packageAndLaunchActivityFromManifest failed. Original error: Command '/Users/edgarrodriguez/Library/Android/sdk/build-tools/29.0.0-rc1/aapt dump badging /Users/edgarrodriguez/Documents/SimpliRoute/helios-mobile-test/app-release.apk' exited with code 1; StdErr: W/ziparchive(36827): Zip: missed a central dir sig (at 0)
[debug] [W3C] W/zipro   (36827): Error opening archive /Users/edgarrodriguez/Documents/SimpliRoute/helios-mobile-test/app-release.apk: Iteration ended
[debug] [W3C] ERROR: dump failed because no AndroidManifest.xml found
[debug] [W3C]
[debug] [W3C]     at ADB.<anonymous> (/Users/edgarrodriguez/Documents/SimpliRoute/helios-mobile-test/node_modules/appium-adb/lib/tools/android-manifest.js:188:9)
[debug] [W3C]     at Generator.throw (<anonymous>)
[debug] [W3C]     at asyncGeneratorStep (/Users/edgarrodriguez/Documents/SimpliRoute/helios-mobile-test/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
[debug] [W3C]     at _throw (/Users/edgarrodriguez/Documents/SimpliRoute/helios-mobile-test/node_modules/@babel/runtime/helpers/asyncToGenerator.js:29:9)
[debug] [W3C]     at <anonymous>
[HTTP] <-- POST /wd/hub/session 500 1364 ms - 1603
[HTTP]
[Appium] Received SIGINT - shutting down
```
## Link to Appium logs

https://gist.github.com/edgarjrg/53d0ad604f71dc1f57a05fdc53e21827

## Code To Reproduce Issue [ Good To Have ]

```
const wdio = require("webdriverio");
const assert = require("assert");

async function daTest() {

  const opts = {
    port: 4723,
    capabilities: {
      platformName: "Android",
      deviceName: "Android Emulator",
      app: "/Users/edgarrodriguez/Documents/SimpliRoute/helios-mobile-test/app-release.apk",
      automationName: "UiAutomator2",
    }
  };
  
  const client = await wdio.remote(opts);

  await client.setImplicitTimeout(1000 * 10);

  const userTextInput = await client.findElement('accessibility id', 'username');

  await client.elementSendKeys(userTextInput.ELEMENT, "hello")

}

daTest();
```

**Comment by mykola-mokhnach** [comment]
This is an issue with the recent build tools, that Google provides (29.0.0-rc1). As a workaround you must either rebuild your app using the recent build tools version or switch appium to use the older package. Use `buildToolsVersion` capability for this purpose.

**Comment by sarang06** [comment]
If you are facing this error in flutter then use command flutter clean, this will be deleting the previous build and cache.
