### ISSUE TITLE
WDA/iProxy crash: Connection to WDA timed out / recv failed: Operation not permitted

### ISSUE THREAD

**Issue by jzaratei** [appium/appium#12588]
## The problem

WDA crash with time out just after establish connection to real device (iOS 12.2) using Appium (v1.13). 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.13.0
* Desktop OS/version used to run Appium: MacBook Pro OS Mojave 10.14.4
* Mobile platform/version under test: iPhone Xs, iOS 12.2 (Xcode 10.2.1)
* Real device or emulator/simulator: Real device.

## Details

Starting tests on an iPhone Xs results in creating the appium session, launching the app and WDA establish connection to the device but just immediately responds with a timeout, according to the logs,  because of "an operation not permitted". This is causing the test fail without passing any cucumber step. Part of the logs:

2019-05-04 15:33:55:599 - [debug] [WD Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"width\" : 375,\n    \"height\" : 812\n  },\n  \"sessionId\" : \"8A0EF4E3-54C8-4C4C-B8A2-F1899FE6D676\",\n  \"status\" : 0\n}"
2019-05-04 15:33:55:600 - [XCUITest] Merging WDA caps over Appium caps for session detail response
2019-05-04 15:33:55:600 - [iOSLog] [IOS_SYSLOG_ROW]     1102
2019-05-04 15:33:55:600 - [iOSLog] [IOS_SYSLOG_ROW] ), got values <private>
2019-05-04 15:33:55:600 - [iOSLog] [IOS_SYSLOG_ROW] May  4 17:33:57 iPhone-de-Tienda testmanagerd[249] <Notice>: Got attributes, transferring to dictionary for return.
2019-05-04 15:33:55:600 - [debug] [XCUITest] Connection to WDA timed out
2019-05-04 15:33:55:600 - [debug] [iProxy] recv failed: Operation not permitted

i've already try any solution posted in the web, but nothing works . e.g:
- Increase timeout
capabilities.setCapability("wdaLaunchTimeout",240000);
capabilities.setCapability("wdaConnectionTimeout",240000);
- trying different capabilities

## Link to Appium logs

IOS logs: https://github.com/jzaratei/appium_logs/blob/master/ios_log.txt
xcode logs: https://github.com/jzaratei/appium_logs/blob/master/xcode_log.txt
Complete logs: https://github.com/jzaratei/appium_logs/blob/master/log_appium_ios.rtf

## Code To Reproduce Issue [ Good To Have ]

public class IOSCapabilities implements AppService {

    public IOSCapabilities() {
        System.out.println("IOSCapabilities constructor.");
    }

    @Override
    public DesiredCapabilities getCapabilities() {
        PropertiesManager properties = PropertiesManager.getInstance();
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(MobileCapabilityType.APP, properties.getPropertie(APP_PATH));
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, properties.getPropertie(DEVICE_NAME));
//        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone 6");
        capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, MobilePlatform.IOS);
        capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, properties.getPropertie(DEVICE_VERSION));
        capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, properties.getPropertie(DRIVER_AUTOMATOR));
        capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, properties.getPropertie(APPIUM_TIMEOUT));
        capabilities.setCapability(MobileCapabilityType.CLEAR_SYSTEM_FILES, true);
        capabilities.setCapability(MobileCapabilityType.UDID, properties.getPropertie(DEVICE_SERIAL));

//        capabilities.setCapability("derivedDataPath", "/app/Workspace/WebDriverAgent");
//        capabilities.setCapability("waitForQuiescence", false);
        capabilities.setCapability("showXcodeLog", true);
        capabilities.setCapability("noReset", false);
        capabilities.setCapability("restart", true);
        capabilities.setCapability("showIOSLog", true);

 //       capabilities.setCapability(IOSMobileCapabilityType.CONNECT_HARDWARE_KEYBOARD, false);
//        capabilities.setCapability(IOSMobileCapabilityType.BUNDLE_ID, properties.getPropertie(BUNDLE_ID));
//        capabilities.setCapability(IOSMobileCapabilityType.XCODE_ORG_ID, properties.getPropertie(ORG_ID));
//        capabilities.setCapability(IOSMobileCapabilityType.XCODE_SIGNING_ID, properties.getPropertie(SINGNING_ID));
        capabilities.setCapability(IOSMobileCapabilityType.WDA_LOCAL_PORT, NetworkHelper.getFreeLocalPort());
        capabilities.setCapability(IOSMobileCapabilityType.USE_NEW_WDA, true);
        capabilities.setCapability(IOSMobileCapabilityType.WDA_CONNECTION_TIMEOUT, 999999999);
        capabilities.setCapability(IOSMobileCapabilityType.WDA_LAUNCH_TIMEOUT, 999999999);
//        capabilities.setCapability(IOSMobileCapabilityType.USE_NEW_WDA, false);

        return capabilities;
    }

**Comment by mykola-mokhnach** [comment]
I don't observe any explicit issues in the attached logs. the session starts successfully and then is deleted by receiving the corresponding request:

> 2019-05-04 15:33:55:966 - [HTTP] --> DELETE /wd/hub/session/3f354d12-ea4b-4b64-a3bc-148d633fbd8e

What exact command fails?

**Comment by jzaratei** [comment]
@mykola-mokhnach, I tried to debug this issue in my code and i find out that is failing  at initializing the IOSDriver instance. Here is the method:

`private void startDriver() {
        DesiredCapabilities capabilities = PropertiesManager.getInstance().getDesiredCapabilities();
        String value = PropertiesManager.getInstance().getPropertie(PLATFORM_NAME);
        switch (value.toLowerCase()) {
            case "android":
                driver = new AndroidDriver<MobileElement>(service.getUrl(), capabilities);
                break;
            case "ios":
                driver = new IOSDriver<MobileElement>(service.getUrl(), capabilities); --fails here
                break;
            default:
                ExceptionController.hookFail("Option not available!  " + value.toLowerCase());
        }
    }`

**Comment by mykola-mokhnach** [comment]
What is the exception stack trace?

**Comment by jzaratei** [comment]
@mykola-mokhnach This what i get from Junit:

`Test ignored.
cucumber.runtime.CucumberException: Failed to instantiate class qa.Tienda.app.steps.PasswordCreatorSteps

	at cucumber.runtime.java.DefaultJavaObjectFactory.cacheNewInstance(DefaultJavaObjectFactory.java:47)
	at cucumber.runtime.java.DefaultJavaObjectFactory.getInstance(DefaultJavaObjectFactory.java:33)
	at cucumber.runtime.java.JavaBackend.buildWorld(JavaBackend.java:122)
	at cucumber.runner.Runner.buildBackendWorlds(Runner.java:120)
	at cucumber.runner.Runner.runPickle(Runner.java:38)
	at cucumber.runtime.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:146)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:68)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:23)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:73)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:122)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:64)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at cucumber.api.junit.Cucumber$1.evaluate(Cucumber.java:131)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:40)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:71)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at cucumber.runtime.java.DefaultJavaObjectFactory.cacheNewInstance(DefaultJavaObjectFactory.java:41)
	... 49 more
Caused by: java.lang.NullPointerException
	at qa.carrefour.app.steps.PasswordCreatorSteps.<init>(PasswordCreatorSteps.java:22)
	... 54 more`

Here is the complete log if I run with maven clean install: https://github.com/jzaratei/appium_logs/blob/master/log_maven.rtf
If you need more info just let me know. Thank you for your support.!!

**Comment by mykola-mokhnach** [comment]
This exception happens inside the client code. I don't see anything that might be related to the server code there

**Comment by jzaratei** [comment]
@mykola thank you for point me out my mistake. There was some classes in my code that weren't initialized correctly. Now all is working as expected, even if I still getting "[XCUITest] Connection to WDA timed out" in the logs. That's why i get confused in the first time. Anyway thank you for your support. Close this issue please.
