### ISSUE TITLE
mjpeg-consumer will not build for Node 12

### ISSUE THREAD

**Issue by imurchie** [appium/appium#12598]
## The problem

Appium uses [mjpeg-consumer](https://www.npmjs.com/package/mjpeg-consumer) to do mjpeg stuff, but it does not build with Node 12, because of [buffertools](https://www.npmjs.com/package/buffertools). Given that neither has been updated in a long time, it seems unlikely they'll get fixed, so perhaps another solution needs to be investigated?

This does not break Appium install, but does remove functionality.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.13.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe): 12.1.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Link to logs

https://gist.github.com/imurchie/7a983673d70724d56dccd0302a73715f

## Code To Reproduce Issue [ Good To Have ]

npm install mjpeg-consumer

**Comment by imurchie** [comment]
[opencv4nodejs](https://github.com/justadudewhohacks/opencv4nodejs) does not work, either. See https://github.com/justadudewhohacks/native-node-utils/issues/6

**Comment by nerdy-glasses-tester** [comment]
I am also seeing this issue when I decided to update my appium to the latest version. Appium doctor suddenly gave me a list of new dependencies I didn't have to install before. One of them I can't run - npm install mjpeg-consumer. I get the error below. Can I still use Appium without installing this dependency? Is there a workaround? I couldn't find much info on this except this ticket. Thanks for posting this ticket.

`npm install mjpeg-consumer

> buffertools@2.1.6 install /Users/angee/node_modules/buffertools
> node-gyp rebuild

  CXX(target) Release/obj.target/buffertools/buffertools.o
../buffertools.cc:32:11: error: no member named 'Handle' in namespace 'v8'
using v8::Handle;
      ~~~~^
../buffertools.cc:141:25: error: no matching member function for call to 'ToObject'
      target = args[0]->ToObject();
               ~~~~~~~~~^~~~~~~~
/Users/angee/.node-gyp/12.4.0/include/node/v8.h:2532:44: note: candidate function not viable: requires single argument
      'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/angee/.node-gyp/12.4.0/include/node/v8.h:2546:35: note: candidate function not viable: requires single argument
      'isolate', but no arguments were provided
                    Local<Object> ToObject(Isolate* isolate) const);
                                  ^
../buffertools.cc:143:7: warning: 'NewFromUtf8' is deprecated: Use maybe version [-Wdeprecated-declarations]
      UNI_THROW_EXCEPTION(Exception::TypeError,
      ^
../buffertools.cc:77:26: note: expanded from macro 'UNI_THROW_EXCEPTION'
        type(v8::String::NewFromUtf8(args.GetIsolate(), message)));
                         ^
/Users/angee/.node-gyp/12.4.0/include/node/v8.h:2890:10: note: 'NewFromUtf8' has been explicitly marked deprecated here
  static V8_DEPRECATED(
         ^
/Users/angee/.node-gyp/12.4.0/include/node/v8config.h:307:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../buffertools.cc:169:25: error: no matching member function for call to 'ToObject'
      target = args[0]->ToObject();
               ~~~~~~~~~^~~~~~~~
/Users/angee/.node-gyp/12.4.0/include/node/v8.h:2532:44: note: candidate function not viable: requires single argument
      'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/angee/.node-gyp/12.4.0/include/node/v8.h:2546:35: note: candidate function not viable: requires single argument
      'isolate', but no arguments were provided
                    Local<Object> ToObject(Isolate* isolate) const);
                                  ^
../buffertools.cc:171:7: warning: 'NewFromUtf8' is deprecated: Use maybe version [-Wdeprecated-declarations]
      UNI_THROW_EXCEPTION(Exception::TypeError,
      ^
../buffertools.cc:77:26: note: expanded from macro 'UNI_THROW_EXCEPTION'
        type(v8::String::NewFromUtf8(args.GetIsolate(), message)));
                         ^
/Users/angee/.node-gyp/12.4.0/include/node/v8.h:2890:10: note: 'NewFromUtf8' has been explicitly marked deprecated here
  static V8_DEPRECATED(
         ^
/Users/angee/.node-gyp/12.4.0/include/node/v8config.h:307:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../buffertools.cc:177:25: error: no matching constructor for initialization of 'String::Utf8Value'
      String::Utf8Value s(args[args_start]);
                        ^ ~~~~~~~~~~~~~~~~
/Users/angee/.node-gyp/12.4.0/include/node/v8.h:3002:5: note: candidate constructor not viable: no known conversion from
      'Local<v8::Value>' to 'const v8::String::Utf8Value' for 1st argument
    Utf8Value(const Utf8Value&) = delete;
    ^
/Users/angee/.node-gyp/12.4.0/include/node/v8.h:2995:5: note: candidate constructor not viable: requires 2 arguments,
      but 1 was provided
    Utf8Value(Isolate* isolate, Local<v8::Value> obj);
    ^
../buffertools.cc:187:47: error: no matching member function for call to 'ToObject'
      Local<Object> other = args[args_start]->ToObject();
                            ~~~~~~~~~~~~~~~~~~^~~~~~~~
/Users/angee/.node-gyp/12.4.0/include/node/v8.h:2532:44: note: candidate function not viable: requires single argument
      'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/angee/.node-gyp/12.4.0/include/node/v8.h:2546:35: note: candidate function not viable: requires single argument
      'isolate', but no arguments were provided
                    Local<Object> ToObject(Isolate* isolate) const);
                                  ^
../buffertools.cc:196:5: warning: 'NewFromUtf8' is deprecated: Use maybe version [-Wdeprecated-declarations]
    UNI_THROW_EXCEPTION(Exception::TypeError,
    ^
../buffertools.cc:77:26: note: expanded from macro 'UNI_THROW_EXCEPTION'
        type(v8::String::NewFromUtf8(args.GetIsolate(), message)));
                         ^
/Users/angee/.node-gyp/12.4.0/include/node/v8.h:2890:10: note: 'NewFromUtf8' has been explicitly marked deprecated here
  static V8_DEPRECATED(
         ^
/Users/angee/.node-gyp/12.4.0/include/node/v8config.h:307:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../buffertools.cc:256:44: error: too few arguments to function call, single argument 'context' was not specified
      int c = args[args_start]->Int32Value();
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/angee/.node-gyp/12.4.0/include/node/v8.h:2569:3: note: 'Int32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/angee/.node-gyp/12.4.0/include/node/v8config.h:347:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../buffertools.cc:261:25: error: no matching constructor for initialization of 'String::Utf8Value'
      String::Utf8Value s(args[args_start]);
                        ^ ~~~~~~~~~~~~~~~~
/Users/angee/.node-gyp/12.4.0/include/node/v8.h:3002:5: note: candidate constructor not viable: no known conversion from
      'Local<v8::Value>' to 'const v8::String::Utf8Value' for 1st argument
    Utf8Value(const Utf8Value&) = delete;
    ^
/Users/angee/.node-gyp/12.4.0/include/node/v8.h:2995:5: note: candidate constructor not viable: requires 2 arguments,
      but 1 was provided
    Utf8Value(Isolate* isolate, Local<v8::Value> obj);
    ^
../buffertools.cc:266:47: error: no matching member function for call to 'ToObject'
      Local<Object> other = args[args_start]->ToObject();
                            ~~~~~~~~~~~~~~~~~~^~~~~~~~
/Users/angee/.node-gyp/12.4.0/include/node/v8.h:2532:44: note: candidate function not viable: requires single argument
      'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/angee/.node-gyp/12.4.0/include/node/v8.h:2546:35: note: candidate function not viable: requires single argument
      'isolate', but no arguments were provided
                    Local<Object> ToObject(Isolate* isolate) const);
                                  ^
../buffertools.cc:272:5: warning: 'NewFromUtf8' is deprecated: Use maybe version [-Wdeprecated-declarations]
    UNI_THROW_EXCEPTION(Exception::TypeError,
    ^
../buffertools.cc:77:26: note: expanded from macro 'UNI_THROW_EXCEPTION'
        type(v8::String::NewFromUtf8(args.GetIsolate(), message)));
                         ^
/Users/angee/.node-gyp/12.4.0/include/node/v8.h:2890:10: note: 'NewFromUtf8' has been explicitly marked deprecated here
  static V8_DEPRECATED(
         ^
/Users/angee/.node-gyp/12.4.0/include/node/v8config.h:307:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../buffertools.cc:329:54: error: too few arguments to function call, single argument 'context' was not specified
    int32_t start = args[args_start + 1]->Int32Value();
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/angee/.node-gyp/12.4.0/include/node/v8.h:2569:3: note: 'Int32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/angee/.node-gyp/12.4.0/include/node/v8config.h:347:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../buffertools.cc:363:5: warning: 'NewFromUtf8' is deprecated: Use maybe version [-Wdeprecated-declarations]
    UNI_THROW_EXCEPTION(Exception::Error,
    ^
../buffertools.cc:77:26: note: expanded from macro 'UNI_THROW_EXCEPTION'
        type(v8::String::NewFromUtf8(args.GetIsolate(), message)));
                         ^
/Users/angee/.node-gyp/12.4.0/include/node/v8.h:2890:10: note: 'NewFromUtf8' has been explicitly marked deprecated here
  static V8_DEPRECATED(
         ^
/Users/angee/.node-gyp/12.4.0/include/node/v8config.h:307:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../buffertools.cc:381:7: warning: 'NewFromUtf8' is deprecated: Use maybe version [-Wdeprecated-declarations]
      UNI_THROW_EXCEPTION(Exception::Error, "This is not hexadecimal data.");
      ^
../buffertools.cc:77:26: note: expanded from macro 'UNI_THROW_EXCEPTION'
        type(v8::String::NewFromUtf8(args.GetIsolate(), message)));
                         ^
/Users/angee/.node-gyp/12.4.0/include/node/v8.h:2890:10: note: 'NewFromUtf8' has been explicitly marked deprecated here
  static V8_DEPRECATED(
         ^
/Users/angee/.node-gyp/12.4.0/include/node/v8config.h:307:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../buffertools.cc:419:12: warning: 'NewFromUtf8' is deprecated: Use maybe version [-Wdeprecated-declarations]
    return UNI_STRING_NEW(s.c_str(), s.size());
           ^
../buffertools.cc:65:17: note: expanded from macro 'UNI_STRING_NEW'
    v8::String::NewFromUtf8(args.GetIsolate(),                                \
                ^
/Users/angee/.node-gyp/12.4.0/include/node/v8.h:2890:10: note: 'NewFromUtf8' has been explicitly marked deprecated here
  static V8_DEPRECATED(
         ^
/Users/angee/.node-gyp/12.4.0/include/node/v8config.h:307:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../buffertools.cc:449:20: error: no matching member function for call to 'ToString'
      size += arg->ToString()->Utf8Length();
              ~~~~~^~~~~~~~
/Users/angee/.node-gyp/12.4.0/include/node/v8.h:2528:44: note: candidate function not viable: requires single argument
      'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
                                           ^
/Users/angee/.node-gyp/12.4.0/include/node/v8.h:2544:35: note: candidate function not viable: requires single argument
      'isolate', but no arguments were provided
                    Local<String> ToString(Isolate* isolate) const);
                                  ^
../buffertools.cc:452:41: error: no matching member function for call to 'ToObject'
      size += node::Buffer::Length(arg->ToObject());
                                   ~~~~~^~~~~~~~
/Users/angee/.node-gyp/12.4.0/include/node/v8.h:2532:44: note: candidate function not viable: requires single argument
      'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/angee/.node-gyp/12.4.0/include/node/v8.h:2546:35: note: candidate function not viable: requires single argument
      'isolate', but no arguments were provided
                    Local<Object> ToObject(Isolate* isolate) const);
                                  ^
../buffertools.cc:460:7: warning: 'NewFromUtf8' is deprecated: Use maybe version [-Wdeprecated-declarations]
      UNI_THROW_AND_RETURN(Exception::TypeError, errmsg);
      ^
../buffertools.cc:72:28: note: expanded from macro 'UNI_THROW_AND_RETURN'
          type(v8::String::NewFromUtf8(args.GetIsolate(), message)));         \
                           ^
/Users/angee/.node-gyp/12.4.0/include/node/v8.h:2890:10: note: 'NewFromUtf8' has been explicitly marked deprecated here
  static V8_DEPRECATED(
         ^
/Users/angee/.node-gyp/12.4.0/include/node/v8config.h:307:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../buffertools.cc:470:25: error: no matching constructor for initialization of 'String::Utf8Value'
      String::Utf8Value v(arg);
                        ^ ~~~
/Users/angee/.node-gyp/12.4.0/include/node/v8.h:3002:5: note: candidate constructor not viable: no known conversion from
      'Local<v8::Value>' to 'const v8::String::Utf8Value' for 1st argument
    Utf8Value(const Utf8Value&) = delete;
    ^
/Users/angee/.node-gyp/12.4.0/include/node/v8.h:2995:5: note: candidate constructor not viable: requires 2 arguments,
      but 1 was provided
    Utf8Value(Isolate* isolate, Local<v8::Value> obj);
    ^
../buffertools.cc:475:30: error: no matching member function for call to 'ToObject'
      Local<Object> b = arg->ToObject();
                        ~~~~~^~~~~~~~
/Users/angee/.node-gyp/12.4.0/include/node/v8.h:2532:44: note: candidate function not viable: requires single argument
      'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/angee/.node-gyp/12.4.0/include/node/v8.h:2546:35: note: candidate function not viable: requires single argument
      'isolate', but no arguments were provided
                    Local<Object> ToObject(Isolate* isolate) const);
                                  ^
../buffertools.cc:482:7: warning: 'NewFromUtf8' is deprecated: Use maybe version [-Wdeprecated-declarations]
      UNI_THROW_AND_RETURN(Exception::Error,
      ^
../buffertools.cc:72:28: note: expanded from macro 'UNI_THROW_AND_RETURN'
          type(v8::String::NewFromUtf8(args.GetIsolate(), message)));         \
                           ^
/Users/angee/.node-gyp/12.4.0/include/node/v8.h:2890:10: note: 'NewFromUtf8' has been explicitly marked deprecated here
  static V8_DEPRECATED(
         ^
/Users/angee/.node-gyp/12.4.0/include/node/v8config.h:307:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../buffertools.cc:492:6: error: variable has incomplete type 'void'
void RegisterModule(Handle<Object> target) {
     ^
../buffertools.cc:492:21: error: use of undeclared identifier 'Handle'
void RegisterModule(Handle<Object> target) {
                    ^
../buffertools.cc:492:28: error: 'Object' does not refer to a value
void RegisterModule(Handle<Object> target) {
                           ^
/Users/angee/.node-gyp/12.4.0/include/node/v8.h:3356:17: note: declared here
class V8_EXPORT Object : public Value {
                ^
../buffertools.cc:492:36: error: use of undeclared identifier 'target'
void RegisterModule(Handle<Object> target) {
                                   ^
../buffertools.cc:492:43: error: expected ';' after top level declarator
void RegisterModule(Handle<Object> target) {
                                          ^
                                          ;
9 warnings and 18 errors generated.
make: *** [Release/obj.target/buffertools/buffertools.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.6.0
gyp ERR! command "/usr/local/Cellar/node/12.4.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/angee/node_modules/buffertools
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN package.json@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! buffertools@2.1.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the buffertools@2.1.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/angee/.npm/_logs/2019-06-09T03_20_25_197Z-debug.log`
