### ISSUE TITLE
Error: Failed to start Chromedriver session: An error occurred (Original error: chrome not reachable

### ISSUE THREAD

**Issue by nancyboat** [appium/appium#12602]
## The problem

Chrome version 66,Chrome driver version 2.39, Webview name can see,but can not switch_to webview,log Error: Failed to start Chromedriver session: An error occurred (Original error: chrome not reachable

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
```
[debug] [35m[BaseDriver][39m Waiting up to 0 ms for condition
[debug] [35m[AndroidBootstrap][39m Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//*[contains(@resource-id,'dialogCancel')]","context":"","multiple":false}}
[debug] [35m[AndroidBootstrap][39m [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//*[contains(@resource-id,'dialogCancel')]","context":"","multiple":false}}
[debug] [35m[AndroidBootstrap][39m [BOOTSTRAP LOG] [debug] Got command of type ACTION
[debug] [35m[AndroidBootstrap][39m [BOOTSTRAP LOG] [debug] Got command action: find
[debug] [35m[AndroidBootstrap][39m [BOOTSTRAP LOG] [debug] Finding '//*[contains(@resource-id,'dialogCancel')]' using 'XPATH' with the contextId: '' multiple: false
[debug] [35m[AndroidBootstrap][39m [BOOTSTRAP LOG] [debug] Failed to locate element. Clearing Accessibility cache and retrying.
[debug] [35m[AndroidBootstrap][39m [BOOTSTRAP LOG] [debug] Finding '//*[contains(@resource-id,'dialogCancel')]' using 'XPATH' with the contextId: '' multiple: false
[debug] [35m[AndroidBootstrap][39m [BOOTSTRAP LOG] [debug] Returning result: {"status":7,"value":"No element found"}
[debug] [35m[AndroidBootstrap][39m Received command result from bootstrap
[debug] [35m[MJSONWP][39m Matched JSONWP error code 7 to NoSuchElementError
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session/94c70d69-ab0b-455d-8a64-7c5ebc018b1d/element [39m[31m500[39m [90m121 ms - 164[39m
[info] [35m[HTTP][39m [90m[39m[info] [35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/session/94c70d69-ab0b-455d-8a64-7c5ebc018b1d/contexts[39m
[info] [35m[HTTP][39m [90m{}[39m
[debug] [35m[MJSONWP][39m Calling AppiumDriver.getContexts() with args: ["94c70d69-ab0b-455d-8a64-7c5ebc018b1d"]
[debug] [35m[AndroidDriver][39m Getting a list of available webviews
[debug] [35m[ADB][39m Running 'E:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s M95CACP9X6NCY shell cat /proc/net/unix'
[debug] [35m[AndroidDriver][39m WEBVIEW_9666 mapped to pid 9666
[debug] [35m[AndroidDriver][39m Getting process name for webview
[debug] [35m[ADB][39m Running 'E:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s M95CACP9X6NCY shell ps'
[debug] [35m[AndroidDriver][39m WEBVIEW_10321 mapped to pid 10321
[debug] [35m[AndroidDriver][39m Getting process name for webview
[debug] [35m[ADB][39m Running 'E:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s M95CACP9X6NCY shell ps'[debug] [35m[AndroidDriver][39m Parsed pid: '9666' pkg: 'com.android.browser' from
[debug] [35m[AndroidDriver][39m     USER      PID   PPID  VSIZE  RSS   WCHAN              PC  NAME
[debug] [35m[AndroidDriver][39m     u0_a4     9666  383   1645892 258692 SyS_epoll_ 0000000000 S com.android.browser
[debug] [35m[AndroidDriver][39m Returning process name: 'com.android.browser'
[debug] [35m[AndroidDriver][39m Parsed pid: '10321' pkg: 'cn.com.vapp.ningbokaifa.app' from
[debug] [35m[AndroidDriver][39m     USER      PID   PPID  VSIZE  RSS   WCHAN              PC  NAME
[debug] [35m[AndroidDriver][39m     u0_a105   10321 383   2199816 296448 SyS_epoll_ 0000000000 S cn.com.vapp.ningbokaifa.app
[debug] [35m[AndroidDriver][39m Returning process name: 'cn.com.vapp.ningbokaifa.app'
[debug] [35m[AndroidDriver][39m Found webviews: ["WEBVIEW_com.android.browser","WEBVIEW_webview","WEBVIEW_cn.com.vapp.ningbokaifa.app"]
[debug] [35m[AndroidDriver][39m Available contexts: ["NATIVE_APP","WEBVIEW_com.android.browser","WEBVIEW_webview","WEBVIEW_cn.com.vapp.ningbokaifa.app"]
[debug] [35m[MJSONWP][39m Responding to client with driver.getContexts() result: ["NATIVE_APP","WEBVIEW_com.android.browser","WEBVIEW_webview","WEBVIEW_cn.com.vapp.ningbokaifa.app"]
[info] [35m[HTTP][39m [37m<-- GET /wd/hub/session/94c70d69-ab0b-455d-8a64-7c5ebc018b1d/contexts [39m[32m200[39m [90m344 ms - 172[39m
[info] [35m[HTTP][39m [90m[39m
[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/94c70d69-ab0b-455d-8a64-7c5ebc018b1d/context[39m
[info] [35m[HTTP][39m [90m{"name":"WEBVIEW_com.android.browser","sessionId":"94c70d69-ab0b-455d-8a64-7c5ebc018b1d"}[39m
[debug] [35m[MJSONWP][39m Calling AppiumDriver.setContext() with args: ["WEBVIEW_com.android.browser","94c70d69-ab0b-455d-8a64-7c5ebc018b1d"]
[debug] [35m[AndroidDriver][39m Getting a list of available webviews
[debug] [35m[ADB][39m Running 'E:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s M95CACP9X6NCY shell cat /proc/net/unix'[debug] [35m[AndroidDriver][39m WEBVIEW_9666 mapped to pid 9666
[debug] [35m[AndroidDriver][39m Getting process name for webview
[debug] [35m[ADB][39m Running 'E:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s M95CACP9X6NCY shell ps'
[debug] [35m[AndroidDriver][39m WEBVIEW_10321 mapped to pid 10321
[debug] [35m[AndroidDriver][39m Getting process name for webview
[debug] [35m[ADB][39m Running 'E:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s M95CACP9X6NCY shell ps'[debug] [35m[AndroidDriver][39m Parsed pid: '10321' pkg: 'cn.com.vapp.ningbokaifa.app' from
[debug] [35m[AndroidDriver][39m     USER      PID   PPID  VSIZE  RSS   WCHAN              PC  NAME
[debug] [35m[AndroidDriver][39m     u0_a105   10321 383   2199816 296448 SyS_epoll_ 0000000000 S cn.com.vapp.ningbokaifa.app
[debug] [35m[AndroidDriver][39m Returning process name: 'cn.com.vapp.ningbokaifa.app'
[debug] [35m[AndroidDriver][39m Parsed pid: '9666' pkg: 'com.android.browser' from
[debug] [35m[AndroidDriver][39m     USER      PID   PPID  VSIZE  RSS   WCHAN              PC  NAME
[debug] [35m[AndroidDriver][39m     u0_a4     9666  383   1645892 258692 SyS_epoll_ 0000000000 S com.android.browser
[debug] [35m[AndroidDriver][39m Returning process name: 'com.android.browser'
[debug] [35m[AndroidDriver][39m Found webviews: ["WEBVIEW_com.android.browser","WEBVIEW_webview","WEBVIEW_cn.com.vapp.ningbokaifa.app"]
[debug] [35m[AndroidDriver][39m Available contexts: ["NATIVE_APP","WEBVIEW_com.android.browser","WEBVIEW_webview","WEBVIEW_cn.com.vapp.ningbokaifa.app"]
[debug] [35m[AndroidDriver][39m Connecting to chrome-backed webview context 'WEBVIEW_com.android.browser'
[debug] [35m[AndroidDriver][39m A port was not given, using random port: 8000
[warn] [35m[AndroidDriver][39m Cannot pass option com.android.chrome because Appium needs it to make chromeDriver work
[debug] [35m[Chromedriver][39m Changed state to 'starting'[warn] [35m[Chromedriver][39m No old chromedrivers seemed to exist
[debug] [35m[Chromedriver][39m Cleaning any old adb forwarded port socket connections
[debug] [35m[ADB][39m List forwarding ports
[debug] [35m[ADB][39m Running 'E:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s M95CACP9X6NCY forward --list'[debug] [35m[ADB][39m Removing forwarded port socket connection: 51393 
[debug] [35m[ADB][39m Running 'E:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s M95CACP9X6NCY forward --remove tcp\:51393'
[debug] [35m[ADB][39m Removing forwarded port socket connection: 51403 
[debug] [35m[ADB][39m Running 'E:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s M95CACP9X6NCY forward --remove tcp\:51403'[debug] [35m[ADB][39m Removing forwarded port socket connection: 51413 
[debug] [35m[ADB][39m Running 'E:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s M95CACP9X6NCY forward --remove tcp\:51413'
[debug] [35m[ADB][39m Removing forwarded port socket connection: 51423 
[debug] [35m[ADB][39m Running 'E:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s M95CACP9X6NCY forward --remove tcp\:51423'[info] [35m[Chromedriver][39m Spawning chromedriver with: C:\Users\wangls\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe --url-base=wd/hub --port=8000 --adb-port=5037 --verbose
[debug] [35m[Chromedriver][39m Chromedriver version: '2.39.562718'
[debug] [35m[JSONWP Proxy][39m Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body[debug] [35m[JSONWP Proxy][39m Got response with status 200: "{\"sessionId\":\"\",\"status\":0,\"value\":{\"build\":{\"version\":\"alpha\"},\"os\":{\"arch\":\"x86_64\",\"name\":\"Windows NT\",\"version\":\"6.1.7601 SP1\"}}}"
[debug] [35m[JSONWP Proxy][39m Proxying [POST /session] to [POST http://127.0.0.1:8000/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.chrome","androidUseRunningApp":true,"androidDeviceSerial":"M95CACP9X6NCY"}}}[debug] [35m[JSONWP Proxy][39m Got response with status 200: {"sessionId":"18b35e72d9a649f18b614be386d94ebf","status":100,"value":{"message":"chrome not reachable\n  (Driver info: chromedriver=2.39.562718 (9a2698cba08cf5a471a29d30c8b3e12becabb0e9),platform=Windows NT 6.1.7601 SP1 x86_64)"}}
[error] [35m[Chromedriver][39m Error: Failed to start Chromedriver session: An error occurred (Original error: chrome not reachable
[error] [35m[Chromedriver][39m   (Driver info: chromedriver=2.39.562718 (9a2698cba08cf5a471a29d30c8b3e12becabb0e9),platform=Windows NT 6.1.7601 SP1 x86_64))
[error] [35m[Chromedriver][39m     at Object.wrappedLogger.errorAndThrow (C:\Users\wangls\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:78:13)
[error] [35m[Chromedriver][39m     at Chromedriver.callee$2$0$ (C:\Users\wangls\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-chromedriver\lib\chromedriver.js:411:13)
[error] [35m[Chromedriver][39m     at tryCatch (C:\Users\wangls\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[error] [35m[Chromedriver][39m     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\wangls\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[error] [35m[Chromedriver][39m     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\wangls\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[error] [35m[Chromedriver][39m     at GeneratorFunctionPrototype.invoke (C:\Users\wangls\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[error] [35m[Chromedriver][39m     at <anonymous>[debug] [35m[JSONWP Proxy][39m Proxying [POST /session] to [POST http://127.0.0.1:8000/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.chrome","androidUseRunningApp":true,"androidDeviceSerial":"M95CACP9X6NCY"}}}
```

## Code To Reproduce Issue [ Good To Have ]
```python
from appium import webdriver
import time
from selenium.common.exceptions import NoSuchElementException
desired_caps = {
    'platformName':'Android',
    'deviceName':'M95CACP9X6NCY',#91QEBP33AMC5  M95CACP9X6NCY
    'platformVersion':'7.1.1',
    #apk包名
    'appPackage':'cn.com.vapp.ningbokaifa.app',
    #'app':'D:\\py\\Appium_Autoframwork\\app\\宁波app1.apk',
    #apk的launcherActivity
    'appActivity':'toone.MainActivity',
    'browser': 'Chrome',
    'chromedriverExecutable':'C:\\Users\\wangls\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-chromedriver\\chromedriver\\win\\chromedriver.exe',
    'chromeOptions': {'androidPackage': 'com.android.chrome'},
    #'appWaitActivity':'com.taobao.tao.welcome.Welcome',
    'noReset':'True',
    'unicodeKeyboard':True,
    'resetKeyboard':True
}


driver = webdriver.Remote('http://127.0.0.1:4723/wd/hub',desired_caps)
time.sleep(20)

# driver.find_element_by_xpath("//*[contains(@class,'android.widget.EditText') and @index=8]").clear()
# # time.sleep(2)
# driver.find_element_by_xpath("//*[contains(@class,'android.widget.EditText') and @index=8]").send_keys('gongj')
# time.sleep(2)
# driver.find_element_by_xpath("//*[contains(@class,'android.widget.EditText') and @index=6]").send_keys(8)
# time.sleep(2)
driver.find_element_by_xpath("//*[contains(@class,'android.widget.Button')]").click()
time.sleep(8)

try:
    driver.find_element_by_xpath("//*[contains(@resource-id,'dialogCancel')]").click()
except NoSuchElementException:
    pass
time.sleep(10)

contexts = driver.contexts
print(contexts)
for context in contexts:
    if 'ningbokaifa' in context:
        print(context)
        driver.switch_to.context(context)

with open('testnbjg.html','w',encoding='utf-8') as f:
   page = driver.page_source
   f.write(page)
```

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Are you able to debug the web view in chrome remote debugger? Are you sure the current chromedriver version is compatible with the web view version?

**Comment by nancyboat** [comment]
> Are you able to debug the web view in chrome remote debugger? Are you sure the current chromedriver version is compatible with the web view version?
chrome://inspect/#devices --inspect the link write HTTP/1.1 404 Not Found
![image](https://user-images.githubusercontent.com/39328910/57425026-4f002000-724c-11e9-993e-4f97d0075723.png)
webview version is 51.0.2074.203,i tried chromedriver version 2.22 or 2.23 ,its also cant work 
![image](https://user-images.githubusercontent.com/39328910/57425469-d7cb8b80-724d-11e9-85f3-04ade2f9b074.png)

**Comment by mykola-mokhnach** [comment]
If the view is not debuggable via chrome then it obviously won't work for Appium. Make sure the application config is correct and the view is debuggable.
