### ISSUE TITLE
Appium unlock can't unlock phone

### ISSUE THREAD

**Issue by FirstAM** [appium/appium#12645]
## The problem

Hi , sometimes Appium unlock can't unlock phone. This problem usually exist on Goolge Pixel 2XL

## Environment

* Appium version (or git revision) that exhibits the issue: 1.13.0
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: Linux Ubuntu 
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager: 3.5.2
* Mobile platform/version under test: Android 9 
* Real device or emulator/simulator: Goolge Pixel 2XL
* Appium CLI or Appium.app|exe: Appium CLI 

## Details

` An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.topface.topface' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Error executing adbExec. Original error: 'Command '/android-sdk/platform-tools/adb -P 5037 -s 801KPWQ1374297 shell am start -W -n com.topface.topface/com.topface.topface.ui.splash_screen.SplashScreenActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'adbExecTimeout' capability (Selenium::WebDriver::Error::UnknownError)
 UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.topface.topface' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Error executing adbExec. Original error: 'Command '/android-sdk/platform-tools/adb -P 5037 -s 801KPWQ1374297 shell am start -W -n com.topface.topface/com.topface.topface.ui.splash_screen.SplashScreenActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'adbExecTimeout' capability
     at getResponseForW3CError (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:826:9)
     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:447:37)
`

## Link to Appium logs

[appium_logs_801KPWQ1374297_77.txt](https://github.com/appium/appium/files/3183074/appium_logs_801KPWQ1374297_77.txt)

**Comment by FirstAM** [comment]
When i run command
`adb shell am start -n io.appium.settings/.Unlock -c android.intent.category.LAUNCHER -a android.intent.action.MAIN -f 0x10200000`

I have answer 

```
Exception occurred while executing:
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.server.wm.AppWindowContainerController.reparent(com.android.server.wm.TaskWindowContainerController, int)' on a null object reference
	at com.android.server.am.ActivityRecord.reparent(ActivityRecord.java:1057)
	at com.android.server.am.ActivityStarter.addOrReparentStartingActivity(ActivityStarter.java:2336)
	at com.android.server.am.ActivityStarter.setTaskFromReuseOrCreateNewTask(ActivityStarter.java:2116)
	at com.android.server.am.ActivityStarter.startActivityUnchecked(ActivityStarter.java:1468)
	at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:1257)
	at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:879)
	at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:551)
	at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1156)
	at com.android.server.am.ActivityStarter.execute(ActivityStarter.java:490)
	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:5126)
	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:5100)
	at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:479)
	at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:161)
	at android.os.ShellCommand.exec(ShellCommand.java:103)
	at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:16071)
	at android.os.Binder.shellCommand(Binder.java:634)
	at android.os.Binder.onTransact(Binder.java:532)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3593)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3297)
	at android.os.Binder.execTransact(Binder.java:731)

```

**Comment by FirstAM** [comment]
So , Hello everyone ! In my case problem was with adnroid sdk platform tools. Last version ADB 1.0.41 (r28.0.3 -platform tools ) as i write before , can't run unlock app. I tried few previous version but in my case work only ADB adb 1.0.40 -  4986621  (r28.0.1 -platform tools). 

Or if this does not resolver you problem , you always can do this solution : 
1. Edit caps with skipUnloc = true
2. Do condition for you device with two adb command 
`adb  shell input keyevent 82`
`adb  shell input touchscreen swipe 930 880 930 380`

**Comment by safa-howaid** [comment]
If your device's display turns on and doesn't unlock, check the screen lock setting in your device's settings. It needs to be set to 'None' for the device to unlock.

**Comment by mykola-mokhnach** [comment]
Closed as obsolete
