### ISSUE TITLE
Getting_Started TestCode can't run ??

### ISSUE THREAD

**Issue by karmactonics** [appium/appium#12665]
## The problem

I ran the test code along Getting_Started.md, but it didn't work.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.13.0
* Desktop OS/version used to run Appium: macOS Mojave 10.14.4
* Node.js version (unless using Appium.app|exe): 11.12.0
* Npm or Yarn package manager: 6.7.0
* Mobile platform/version under test: Android 8.0 Oreo
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: CLI

### First issue
test.js detail
```
    const wdio = require('webdriverio');

    const options = {
        port: 4723,
        capabilities: {
            platformName: "Android",
            platformVersion: "8.0",
            deviceName: "emulator-5554",
            app: "apk path",
            automationName: "UiAutomator2",
        },
    };
    
    const client = wdio.remote(options);
    
    const field = await client.$("~TextField1");
    await field.setValue("Hello, World!");
    const value = await field.getValue();
    assert.equal(value,"Hello, World!");

```
run `node test.js` occurs this error.

```
    const field = await client.$("~TextField1");
                  ^^^^^

SyntaxError: await is only valid in async function
    at Module._compile (internal/modules/cjs/loader.js:743:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:862:12)
    at internal/main/run_main_module.js:21:11
```

### Second issue

fix test.js
```
(async () => {

    const wdio = require('webdriverio');

    const options = {
        port: 4723,
        capabilities: {
            platformName: "Android",
            platformVersion: "8.0",
            deviceName: "emulator-5554",
            app: "apk path",
            automationName: "UiAutomator2",
        },
    };
    
    const client = wdio.remote(options);
    
    const field = await client.$("~TextField1");
    await field.setValue("Hello, World!");
    const value = await field.getValue();
    assert.equal(value,"Hello, World!");

})();
```
run `node test.js` occurs this error.
```
    const field = await client.$("~TextField1");
                  ^^^^^

SyntaxError: await is only valid in async function
    at Module._compile (internal/modules/cjs/loader.js:743:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:862:12)
    at internal/main/run_main_module.js:21:11
```

### Third Issue
fix test.js again
```
    const client = wdio.remote(options);
```
↓
```
    const client = await wdio.remote(options);
```
run `node test.js` occurs this error.
```
(node:18483) UnhandledPromiseRejectionWarning: Error: Can't call setValue on element with selector "~TextField1" because element wasn't found
```

I use https://github.com/appium/appium/raw/master/sample-code/apps/ApiDemos-debug.apk along with Getting_Started.md.
Why element wasn't found?

**Comment by imurchie** [comment]
Try the following as the final test file (with adjustments for the location of the apk file, and the platform version if necessary):
```js
const wdio = require("webdriverio");
const assert = require("assert");

const opts = {
  port: 4723,
  capabilities: {
    platformName: "Android",
    platformVersion: "8",
    deviceName: "Android Emulator",
    app: "/path/to/the/downloaded/ApiDemos.apk",
    appPackage: "io.appium.android.apis",
    appActivity: ".view.TextFields",
    automationName: "UiAutomator2"
  }
};

async function main () {
  const client = await wdio.remote(opts);

  const field = await client.$("android.widget.EditText");
  await field.setValue("Hello World!");
  const value = await field.getText();
  assert.equal(value,"Hello World!");

  await client.deleteSession();
}

main();
```

**Comment by karmactonics** [comment]
It worked fine with the code you gave me. Thank you.

**Comment by imurchie** [comment]
Excellent! Thanks for bringing this to our attention. The "getting started" documentation will be better for it!
