### ISSUE TITLE
Appium tests stops after a while[Exception in thread "Thread-0" org.openqa.selenium.WebDriverException: Connection refused (Connection refused)]

### ISSUE THREAD

**Issue by eyalpartner** [appium/appium#12666]
## The problem
After a while the tests stop, the adb is still connected and network also, So it's not network or disconnection problem, Here is the Exception:
Exception in thread "Thread-0" org.openqa.selenium.WebDriverException: Connection refused (Connection refused)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'eyal', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.18.0-20-generic', java.version: '11.0.3'
Driver info: driver.version: AndroidDriver
	at io.appium.java_client.remote.AppiumCommandExecutor.lambda$5(AppiumCommandExecutor.java:251)
	at java.base/java.util.Optional.orElseGet(Optional.java:369)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:250)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at io.appium.java_client.CommandExecutionHelper.execute(CommandExecutionHelper.java:27)
	at io.appium.java_client.android.StartsActivity.getCurrentPackage(StartsActivity.java:67)
	at utils.BaseTest$1.run(BaseTest.java:119)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:240)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:129)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:245)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:165)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:103)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:155)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)

## Environment

* Appium version 1.13.0
* Desktop OS/version used to run Appium: Linux ubuntu
* Node.js version (unless using Appium.app|exe): 11.13.0
* Npm: 6.9.0
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator: Real Device
* Appium CLI

## Appium logs
<--- Last fewF AGTCAsL  -E-R-R>O
R
:[ 3I1n7e2f2f:e0cxt4i4v9ed 0mba0r]k -1c3o7m4p5a5c6t8s  mnse:a rM ahrke-sawpe elpi m1i3t1 7Al.l4o c(a1t4i5o6n. 7f)a i-l>e d1 3-1 7J.a0v a(S1c4r5i6p.t7 )h eMaBp,  o2u9t5 .o2f  /m e0m.o0r ym
s  (aver
Wraigtei nmgu  N=o d0e.j.s3 9r8e,p ocrutr rteon tf imlue :=  r0e.p4o4r2t). 2a0l1l9o0c5a2t0i.o1n3 0f9a0i6l.u3r1e7 2s2c.a0v.e0n0g1e .mjisgohnt not succeed
[31722:0x449d0b0] 13746008 ms: Mark-sweep 1317.4 (1456.7) -> 1317.0 (1456.7) MB, 308.6 / 0.0 ms  (average mu = 0.351, current mu = 0.298) allocation failure scavenge might not succeed

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x32b1df54fc5d]
    1: StubFrame [pc: 0x32b1df552698]
Security context: 0x0fe77f41d9d1 <JSObject>
    2: exec [0xfe77f409091](this=0x22884c2b1e01 <JSRegExp <String[159]: ; *([!#$%&'*+.^_`|~0-9A-Za-z-]+) *= *("(?:[\u000b\u0020\u0021\u0023-\u005b\u005d-\u007e\u0080-\u00ff]|\\[\u000b\u0020-\u00ff])*"|[!#$%&'*+.^_`|~0-9A-Za-z-]+) *>>,0x0915cb22fc29 <String[31]: application/json; charset=utf-8>)
    3: parse [0x33b0d97949...

Node.js report completed
 1: 0x95a770 node::Abort() [/home/eyal/node-v11.13.0-linux-x64/bin/node]
 2: 0x95b416 node::OnFatalError(char const*, char const*) [/home/eyal/node-v11.13.0-linux-x64/bin/node]
 3: 0xb3b32e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/home/eyal/node-v11.13.0-linux-x64/bin/node]
 4: 0xb3b564 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/home/eyal/node-v11.13.0-linux-x64/bin/node]
 5: 0xf3abb2  [/home/eyal/node-v11.13.0-linux-x64/bin/node]
 6: 0xf3acb8 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/home/eyal/node-v11.13.0-linux-x64/bin/node]
 7: 0xf473d8 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/home/eyal/node-v11.13.0-linux-x64/bin/node]
 8: 0xf47eeb v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/home/eyal/node-v11.13.0-linux-x64/bin/node]
 9: 0xf4ac21 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/home/eyal/node-v11.13.0-linux-x64/bin/node]
10: 0xf14e54 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/home/eyal/node-v11.13.0-linux-x64/bin/node]
11: 0x11cb15e v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/home/eyal/node-v11.13.0-linux-x64/bin/node]
12: 0x32b1df54fc5d 
13:09:06.331 [Thread-0] INFO  utils.Log - Connection refused (Connection refused)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'eyal', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.18.0-20-generic', java.version: '11.0.3'
Driver info: driver.version: RemoteWebDriver

**Comment by mykola-mokhnach** [comment]
The exception above is a nodejs out of memory error. We'll need a heap dump in order to debug it

**Comment by eyalpartner** [comment]
> The exception above is a nodejs out of memory error. We'll need a heap dump in order to debug it

How can I take heap dump ?

**Comment by mykola-mokhnach** [comment]
For node11, for example: https://marmelab.com/blog/2018/04/03/how-to-track-and-fix-memory-leak-with-nodejs.html

**Comment by eyalpartner** [comment]
> For node11, for example: https://marmelab.com/blog/2018/04/03/how-to-track-and-fix-memory-leak-with-nodejs.html

Looks too complicated

**Comment by mykola-mokhnach** [comment]
Memory leaks investigation has never been simple. Unfortunately we cannot do nothing there without such snapshots

**Comment by eyalpartner** [comment]
If you have any good tutorial or other way I will get this info,

Thanks

**Comment by eyalpartner** [comment]
> Memory leaks investigation has never been simple. Unfortunately we cannot do nothing there without such snapshots

I have json report, Can it be helpful ?

**Comment by mykola-mokhnach** [comment]
> report.20190520.1.zip

Nope, this information is not useful at all

**Comment by eyalpartner** [comment]
I have upgraded the node to newest version 12.3.0,
I also reinstall appium and delete folders, This doesn't solve this problem.

**Comment by mykola-mokhnach** [comment]
Nothing more to do here without the heap dump :(
