### ISSUE TITLE
keycode, keyevent to search not working

### ISSUE THREAD

**Issue by i-am-sanguine** [appium/appium#12716]
I am trying to automate an e-commerce app with appium and Python. the issue I have is with "Search". Nothing I have tried worked. I have tried the following:
```
self.driver.find_element_by_id(<search_button_id>).click
self.driver.press_keycode(84)
self.driver.press_keycode(66)
self.driver.keyevent(84)
self.driver.keyevent(66)
```

All of the above returned nothing. and here is the log: 
https://gist.github.com/i-am-sanguine/bd639467c49fd1d7b07107447c17b142
However, when I tried this:
`self.driver.execute_script('mobile:performEditorAction', {'action:' 'search'})`
it returned this error below:

```
Traceback (most recent call last):
  File "/Users/sanguine/PycharmProjects/KongaApp/check.py", line 30, in <module>
    driver.execute('mobile:performEditorAction', {'action:' 'search'})
  File "/Users/sanguine/.pyenv/versions/3.7.3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 307, in execute
    params['sessionId'] = self.session_id
TypeError: 'set' object does not support item assignment
```
And the Log from this error is:
https://gist.github.com/i-am-sanguine/e57702b2ca2212e8e2491d68c8847e4e

## Environment

* Appium version: v1.13.0
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Mac OS Mojave (10.14.5)
* Node.js version : v 10.15.3
* Mobile platform/version under test: 7.1.1
* Real device or emulator/simulator: Android Studio Emulator

**Comment by mykola-mokhnach** [comment]
The first approach is not going to work anyway. The second one is correct, howeverit looks like there is a problem in the python client. Moving the issue to the appropriate tracker.
