### ISSUE TITLE
Appium error: Error getting device platform version. Original error: Error executing adbExec

### ISSUE THREAD

**Issue by ElliotPalmer-94** [appium/appium#12779]
## The problem

When running my app test to run against the chrome browser within the device I get the following relating to **Error getting device platform version. Original error: Error executing adbExec**

## Environment

* Appium version (or git revision) that exhibits the issue: **1.13.0**
* Desktop OS/version used to run Appium: **Windows 10**
* Node.js version (unless using Appium.app|exe): **v10.15.3**
* Mobile platform/version under test: **Pixel** & **Android 8.1**
* Real device or emulator/simulator: **Emulator**
* Appium CLI or Appium.app|exe: **Appium CLI**

## Details

**My config setup:**
```
    capabilities: {
        browserName: 'chrome',
        platformName: 'Android',
        platformVersion: '8.1',
        deviceName: 'Pixel',
        automationName: 'UiAutomator2',
        chromedriverExecutableDir: 'C:\\Users\\Elliot\\Desktop\\App\\automation\\resources\\chromedrivers'
    },
```

**I have tried the following to TRY and resolve this issue**
- Fresh install of Appium
- Fresh install of Android Studio
- Correct JAVA_HOME and ANDROID PATH setup

Not really sure why this happens since when I run the following command while the emulator is running it will return the platform version:

```
C:\Users\Elliot>adb shell getprop ro.build.version.release
8.1.0
```

As soon as the test start to run I get the following error:
```
$ protractor config/app-browser-config.js
[15:11:50] I/launcher - Running 1 instances of WebDriver
[15:11:50] I/hosted - Using the selenium server at http://localhost:4723/wd/hub
[15:11:50] E/launcher - An unknown server-side error occurred while processing the command. Original error: Error getting device platform version. Original error: Error executing adbExec. Original error: 'Command 'C\:\\Users\\Elliot\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.release' exited with code 3221226356'; Stderr: ''; Code: '3221226356'
[15:11:50] E/launcher - WebDriverError: An unknown server-side error occurred while processing the command. Original error: Error getting device platform version. Original error: Error executing adbExec. Original error: 'Command 'C\:\\Users\\Elliot\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.release' exited with code 3221226356'; Stderr: ''; Code: '3221226356'
    at Object.checkLegacyResponse (C:\Users\Elliot\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:546:15)
    at parseHttpResponse (C:\Users\Elliot\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:509:13)
    at doSend.then.response (C:\Users\Elliot\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:441:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
From: Task: WebDriver.createSession()
    at Function.createSession (C:\Users\Elliot\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:769:24)
    at Function.createSession (C:\Users\Elliot\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\chrome.js:761:15)
    at createDriver (C:\Users\Elliot\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\index.js:170:33)
    at Builder.build (C:\Users\Elliot\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\index.js:626:16)
    at Hosted.getNewDriver (C:\Users\Elliot\AppData\Roaming\npm\node_modules\protractor\built\driverProviders\driverProvider.js:53:33)
    at Runner.createBrowser (C:\Users\Elliot\AppData\Roaming\npm\node_modules\protractor\built\runner.js:195:43)
    at q.then.then (C:\Users\Elliot\AppData\Roaming\npm\node_modules\protractor\built\runner.js:339:29)
    at _fulfilled (C:\Users\Elliot\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:834:54)
    at C:\Users\Elliot\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:863:30
    at Promise.promise.promiseDispatch (C:\Users\Elliot\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:796:13)
[15:11:50] E/launcher - Process exited with error code 199
```

## Link to Appium logs

```
[Appium] Welcome to Appium v1.13.0
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"browserName":"chrome","platformName":"Android","platformVersion":"8.1","deviceName":"Pixel1","automationName":"UiAutomator2","chromedriverExecutableDir":"C:\\Users\\Elliot\\Desktop\\App\\automation\\resources\\chromedrivers","count":1}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"browserName":"chrome","platformName":"Android","platformVersion":"8.1","deviceName":"Pixel1","automationName":"UiAutomator2","chromedriverExecutableDir":"C:\\Users\\Elliot\\Desktop\\App\\automation\\resources\\chromedrivers","count":1},null,null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1560608514224 (15:21:54 GMT+0100 (British Summer Time))
[Appium] Appium v1.13.0 creating new AndroidUiautomator2Driver (v1.33.1) session
[Appium] Capabilities:
[Appium]   browserName: chrome
[Appium]   platformName: Android
[Appium]   platformVersion: 8.1
[Appium]   deviceName: Pixel1
[Appium]   automationName: UiAutomator2
[Appium]   chromedriverExecutableDir: C:\Users\Elliot\Desktop\App\automation\resources\chromedrivers
[Appium]   count: 1
[debug] [BaseDriver] Creating session with MJSONWP desired capabilities: {"browserName":"chrome","pl...
[BaseDriver] The following capabilities were provided, but are not recognized by appium: count.
[BaseDriver] Session created with session id: e220cd43-6cfc-43ae-bb69-5196c49d3caa
[UiAutomator2] We're going to run a Chrome-based session
[UiAutomator2] Chrome-type package and activity are com.android.chrome and com.google.android.apps.chrome.Main
[ADB] Found 1 'build-tools' folders under 'C:\Users\Elliot\AppData\Local\Android\Sdk' (newest first):
[ADB]     C:/Users/Elliot/AppData/Local/Android/Sdk/build-tools/29.0.0
[ADB] Using 'adb.exe' from 'C:\Users\Elliot\AppData\Local\Android\Sdk\platform-tools\adb.exe'
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[AndroidDriver] Looking for a device with Android '8.1'
[debug] [ADB] Setting device id to emulator-5554
[ADB] Getting device platform version
[debug] [ADB] Running 'C:\Users\Elliot\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.release'
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1560608514938 (15:21:54 GMT+0100 (British Summer Time))
[debug] [MJSONWP] Encountered internal error running command: Error: Error getting device platform version. Original error: Error executing adbExec. Original error: 'Command 'C\:\\Users\\Elliot\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.release' exited with code 3221226356'; Stderr: ''; Code: '3221226356'
[debug] [MJSONWP]     at ADB.<anonymous> (C:\Users\Elliot\AppData\Roaming\npm\node_modules\appium\node_modules\appium-adb\lib\tools\adb-commands.js:115:11)
[debug] [MJSONWP]     at Generator.throw (<anonymous>)
[debug] [MJSONWP]     at asyncGeneratorStep (C:\Users\Elliot\AppData\Roaming\npm\node_modules\appium\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
[debug] [MJSONWP]     at _throw (C:\Users\Elliot\AppData\Roaming\npm\node_modules\appium\node_modules\@babel\runtime\helpers\asyncToGenerator.js:29:9)
[HTTP] <-- POST /wd/hub/session 500 744 ms - 459
```

## Code To Reproduce Issue [ Good To Have ]

```
// ================= DECLARE =================
const cowsay = require('cowsay');
const SpecReporter = require('jasmine-spec-reporter').SpecReporter;

// ================= WEBDRIVER SETTINGS =================
exports.config = {
    framework: 'jasmine',

    // Options to be passed to Jasmine-node.
    jasmineNodeOpts: {
        showColors: true, // Use colors in the command line report.
        print: function () { }
    },

    jasmineNodeOpts: {
        defaultTimeoutInterval: 30000
    },

    seleniumAddress: 'http://localhost:4723/wd/hub',
    maxInstances: 1,
    maxSessions: 1,

    // Browser Captabilities 
    // Capabilities to be passed to the webdriver instance.

    capabilities: {
        browserName: 'chrome',
        platformName: 'Android',
        platformVersion: '8.1',
        deviceName: 'Pixel1',
        automationName: 'UiAutomator2',
        chromedriverExecutableDir: 'C:\\Users\\Elliot\\Desktop\\App\\automation\\resources\\chromedrivers'
    },

    baseUrl: 'http://10.0.2.2:8000',

    // ================= SPECS =================
    specs: '../specs/e2e/*.js',

    suites: {

        simpletest1: '../specs/e2e/simpletest-1*',
        // simpletest2: '../specs/e2e/simpletest-2*',
        // simpletest3: '../specs/e2e/simpletest-3*',
        // simpletest4: '../specs/e2e/simpletest-4*',
        // simpletest5: '../specs/e2e/simpletest-5*',
        // simpletest6: '../specs/e2e/simpletest-6*',
        // simpletest7: '../specs/e2e/simpletest-7*',
        // simpletest8: '../specs/e2e/simpletest-8*',

    },

    //On start up do something
    onPrepare: function () {

        console.log(cowsay.say({
            text: "Automated test are running!",
            e: "oO",
            T: "U",
        }));

        //Jasmine spec report for clean reporting of test
        jasmine.getEnv().addReporter(new SpecReporter({
            spec: {
                displayStacktrace: true
            }
        }));
    },

    //When complete do something
    onComplete: function () {

    }
}
```

**Comment by mykola-mokhnach** [comment]
Closed as duplicate. The problems happens due to a bug in adb. It is said it has been fixed by Google several days ago
