### ISSUE TITLE
 Uncaught WebDriverError: An unknown server-side error occurred while processing the command. Original error: Error getting device platform version. Original error: Error executing adbExec

### ISSUE THREAD

**Issue by tejas900** [appium/appium#12787]
## The problem

I am automating a mobile app on android using selenium webdriver js with mocha fwk. when i run this sample test using npm run "test", i get the following error

Login to Jet Mobile app
       "before all" hook: Setup Driver and Navigate to Home Page:
     Uncaught WebDriverError: An unknown server-side error occurred while processing the command. Original error: Error getting device platform version. Original error: Error executing adbExec. Original error: 'Command 'D\:\\android-sdk_r24.4.1-windows\\android-sdk-windows\\platform-tools\\adb.exe -P 5037 -s ENU7N15A31001413 shell getprop ro.build.version.release' exited with code 3221226356'; Stderr: ''; Code: '3221226356'
      at Object.checkLegacyResponse (node_modules\selenium-webdriver\lib\error.js:546:15)
      at parseHttpResponse (node_modules\selenium-webdriver\lib\http.js:509:13)
      at doSend.then.response (node_modules\selenium-webdriver\lib\http.js:441:30)
      at processTicksAndRejections (internal/process/next_tick.js:81:5)
  From: Task: WebDriver.createSession()
      at Function.createSession (node_modules\selenium-webdriver\lib\webdriver.js:769:24)
      at createDriver (node_modules\selenium-webdriver\index.js:170:33)
      at Builder.build (node_modules\selenium-webdriver\index.js:635:14)
      at Function.<anonymous> (src\config\webdriver\DriverManager.ts:21:14)
      at step (src\config\webdriver\DriverManager.js:32:23)
      at Object.next (src\config\webdriver\DriverManager.js:13:53)
      at D:\OjetMobileAutoProto\src\config\webdriver\DriverManager.js:7:71
      at new Promise (<anonymous>)
      at __awaiter (src\config\webdriver\DriverManager.js:3:12)
      at Function.DriverManager.setDriver (src\config\webdriver\DriverManager.js:45:16)
      at Function.<anonymous> (src\config\webdriver\DriverManager.ts:33:33)
      at step (src\config\webdriver\DriverManager.js:32:23)
      at Object.next (src\config\webdriver\DriverManager.js:13:53)
      at D:\OjetMobileAutoProto\src\config\webdriver\DriverManager.js:7:71
      at new Promise (<anonymous>)
      at __awaiter (src\config\webdriver\DriverManager.js:3:12)
      at Function.DriverManager.getDriver (src\config\webdriver\DriverManager.js:73:16)
      at Context.<anonymous> (src\test\LoginAndNavigateObjects.ts:13:38)
      at step (src\test\LoginAndNavigateObjects.ts:32:23)
      at Object.next (src\test\LoginAndNavigateObjects.ts:13:53)
      at D:\OjetMobileAutoProto\src\test\LoginAndNavigateObjects.ts:7:71
      at new Promise (<anonymous>)
      at __awaiter (src\test\LoginAndNavigateObjects.ts:3:12)
      at Context.<anonymous> (src\test\LoginAndNavigateObjects.ts:48:16)

  2) Login to Jet Mobile app
       "after all" hook:
     TypeError: Cannot read property 'quit' of undefined
      at Context.<anonymous> (src\test\LoginAndNavigateObjects.ts:89:22)
      at step (src\test\LoginAndNavigateObjects.ts:32:23)
      at Object.next (src\test\LoginAndNavigateObjects.ts:13:53)
      at D:\OjetMobileAutoProto\src\test\LoginAndNavigateObjects.ts:7:71
      at new Promise (<anonymous>)
      at __awaiter (src\test\LoginAndNavigateObjects.ts:3:12)
      at Context.<anonymous> (src\test\LoginAndNavigateObjects.ts:165:16)

[mochawesome] Report JSON saved to D:\OjetMobileAutoProto\'reports\func-tests\android'\'index'.json

[mochawesome] Report HTML saved to D:\OjetMobileAutoProto\'reports\func-tests\android'\'index'.html

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-test-app@ test.android: `node ./node_modules/mocha/bin/mocha --deviceType=android --require ts-node/register --timeout=0 src/test/**/*.ts --reporter=mochawesome --reporter-options reportDir='reports/func-tests/android',reportFilename='index'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-test-app@ test.android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dtejas.ORADEV\AppData\Roaming\npm-cache\_logs\2019-06-18T00_28_34_350Z-debug.log

## Environment

* Appium version (or git revision) that exhibits the issue:V1.13.0
* Last Appium version that did not exhibit the issue (if applicable):NA
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager: NPM
* Mobile platform/version under test:: Android
* Real device or emulator/simulator: Real device (nexus 6p)
* Appium CLI or Appium.app|exe: CLI

## Details

as described above

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.

https://gist.github.com/tejas900/9d6b3f801069ff68d7aa5c5972a4ecc1

Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by KazuCocoa** [comment]
Is this related to https://github.com/appium/appium/issues/12736#issuecomment-502093453 ?

**Comment by tejas900** [comment]
Yes, exactly. I got the error resolved by upgrading to Android SDK Platform-Tools (revision: 29.0.1)
