### ISSUE TITLE
Socket hangup error  on ios real device

### ISSUE THREAD

**Issue by sharecommute** [appium/appium#12794]
## The problem

While clicking a element, getting the page source or sometimes with finding an element.  The socket is hanging up and causing the tests to fail.

## Environment

* Appium version (or git revision) that exhibits the issue: appium --version
1.13.0
* Last Appium version that did not exhibit the issue (if applicable): appium 1.10.x
* Desktop OS/version used to run Appium: 1.13 (I am not seeing this issue on appium desktop version)
* Node.js version (unless using Appium.app|exe): 6.9.0
* Npm or Yarn package manager:  npm
* Mobile platform/version under test: ios/11.4.1
* Real device or emulator/simulator: Real device (iphone7)
* Appium CLI or Appium.app|exe: appium client

## Details
appium : 1.13
Macos : 10.14
libimobiledevice : head
xcode : 10.2.1
python : 3.7.3
Real Device: iphone7 (11.4) 
## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
**https://gist.github.com/sharecommute/7c51b34d2d0227f008248853dd1532d8**

Noticable Errors:
**[WD Proxy] Got an unexpected response: {"code":"ECONNRESET"}**
**[debug] [W3C (7554bc26)] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: Error: socket hang up**
[debug] [W3C (7554bc26)]     at doJwpProxy (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:547:13)
[debug] [W3C (7554bc26)]     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:308:9)
[HTTP] <-- POST /wd/hub/session/7554bc26-9adf-4f0b-9cef-

## Code To Reproduce Issue [ Good To Have ]
In python, i used 
1. self.driver.find_element_by_ios_predicate(<element>) (intermittent)
2. self.driver.click_element(<element>) (intermittent)
3. self.driver.page_source ( this is for sure causing the socket hang up)

**Note: Getting the page source manually using the Desktop app is not getting any socket hang up, i can copy the page source and paste it into a editor.**

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by sharecommute** [comment]
Just an update related to desktop app. While executing the same test with "**printPageSourceOnFindFailure**" desired capability, desktop app also hanged up. Here is the snippet after last successful command.

[2019-06-18 09:18:45][iProxy] recv failed: Operation not permitted
[2019-06-18 09:18:45][W3C (eaa70759)] Responding to client with driver.execute() result: {}
[2019-06-18 09:18:45][HTTP] <-- POST /wd/hub/session/eaa70759-8094-4425-876b-63e446da4a66/execute/sync 200 338 ms - 12
[2019-06-18 09:18:45][HTTP] 
[2019-06-18 09:18:45][HTTP] --> POST /wd/hub/session/eaa70759-8094-4425-876b-63e446da4a66/element
[2019-06-18 09:18:45][HTTP] {"using":"-ios class chain","value":"**/XCUIElementTypeNavigationBar/XCUIElementTypeButton[`name IN {'Contacts', 'Cancel'}`]"}
[2019-06-18 09:18:45][W3C (eaa70759)] Calling AppiumDriver.findElement() with args: ["-ios class chain","**/XCUIElementTypeNavigationBar/XCUIElementTypeButton[`name IN {'Contacts', 'Cancel'}`]","eaa70759-8094-4425-876b-63e446da4a66"]
[2019-06-18 09:18:45][XCUITest] Executing command 'findElement'
[2019-06-18 09:18:45][BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[2019-06-18 09:18:45][BaseDriver] Waiting up to 0 ms for condition
[2019-06-18 09:18:45][WD Proxy] Matched '/element' to command name 'findElement'
[2019-06-18 09:18:45][WD Proxy] Proxying [POST /element] to [POST http://localhost:25352/session/05CB0770-1B32-4229-9282-FE73444A28E1/element] with body: {"using":"class chain","value":"**/XCUIElementTypeNavigationBar/XCUIElementTypeButton[`name IN {'Contacts', 'Cancel'}`]"}
[2019-06-18 09:18:46][WD Proxy] Got response with status 200: {"value":{"using":"class chain","value":"**/XCUIElementTypeNavigationBar/XCUIElementTypeButton[`name IN {'Contacts', 'Cancel'}`]","description":"unable to find an element"},"sessionId":"05CB0770-1B32-4229-9282-FE73444A28E1","status":7}
[2019-06-18 09:18:46][WD Proxy] Got an unexpected response: {"value":{"using":"class chain","value":"**/XCUIElementTypeNavigationBar/XCUIElementTypeButton[`name IN {'Contacts', 'Cancel'}`]","description":"unable to find an element"},"sessionId":"05CB0770-1B32-4229-9282-FE73444A28E1","status":7}
[2019-06-18 09:18:46][MJSONWP] Matched JSONWP error code 7 to NoSuchElementError
**[2019-06-18 09:18:46][WD Proxy] Matched '/source?format=json' to command name 'getPageSource'
[2019-06-18 09:18:46][WD Proxy] Proxying [GET /source?format=json] to [GET http://localhost:25352/session/05CB0770-1B32-4229-9282-FE73444A28E1/source?format=json] with no body
[2019-06-18 09:18:46][iProxy] recv failed: Connection reset by peer
[2019-06-18 09:18:46][iProxy] recv failed: Operation not permitted
[2019-06-18 09:18:51][iProxy] recv failed: Operation timed out
[2019-06-18 09:18:51][iProxy] recv failed: Operation timed out
[2019-06-18 09:18:51][WD Proxy] **Got an unexpected response: {"code":"ECONNRESET"}**
[2019-06-18 09:18:51][W3C (eaa70759)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up
[2019-06-18 09:18:51][W3C (eaa70759)]     at JWProxy.command (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:237:13)
[2019-06-18 09:18:51][HTTP] <-- POST /wd/hub/session/eaa70759-8094-4425-876b-63e446da4a66/element 500 5972 ms - 563
[2019-06-18 09:18:51][HTTP]**

**Comment by mykola-mokhnach** [comment]
Try to enable ios system logging and attach the output here. Socket hang up means that WebDriverAgent stopped responding to Appium requests, probably crashed. Also, make sure you use the most recent Appium version.

**Comment by sharecommute** [comment]
i am using the latest appium @mykola-mokhnach . I have added the log attachment with ios sytem logging enabled. Please let me know if you need more information

**Comment by mykola-mokhnach** [comment]
I don't observe any calls to /source in the updated log

**Comment by sharecommute** [comment]
ok @mykola-mokhnach . I will take new logs and attach it.

**Comment by sharecommute** [comment]
Here is the new log.https://gist.github.com/sharecommute/2e604ace700e43f35afb591482fd4919

**Comment by sharecommute** [comment]
@mykola-mokhnach, i have captured both appium and ios real device logs and attached in the below link. If this doesn't work please let me know the steps to capture particular log and i will try to capture them.

https://gist.github.com/sharecommute/077e7f4eda8297061e33ea94b79336da

**Comment by jonathan-tan-viki** [comment]
Hi, I am also facing the same problem - except that the same device worked fine on one machine but didn't work on another. 

Discovered that the problem was that one machine was ahead in commits for usbmuxd. I replaced it with my old version and I didn't have this problem anymore.

Perhaps you could give it a shot in trying to replace usbmuxd with an attached older commit.
If you used brew to install, you can run `brew info usbmuxd` to find the install location and just replace it manually. You also might need to change the name of the subfolder with the to match the git SHA which brew is using.
(Kind of a dirty solution for now but we'll work it out later if it works for you too)

Sorry i'm kinda new to this so if there's a better way of doing this please let me know haha.

[usbmuxd.zip](https://github.com/appium/appium/files/3309251/usbmuxd.zip)

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
