### ISSUE TITLE
Could not swipe in webview context

### ISSUE THREAD

**Issue by Phoenix124** [appium/appium#12798]
## The problem
Could not swipe in webview context

## Environment

* Appium version (or git revision) that exhibits the issue: 1.13.0
* Last Appium version that did not exhibit the issue (if applicable): 1.13.0
* Desktop OS/version used to run Appium: desktop
* Node.js version (unless using Appium.app|exe): 10.15.3
* Npm or Yarn package manager: 6.9.0
* Mobile platform/version under test: Android 8.0
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: appium.app

## Link to Appium logs
```
rg.openqa.selenium.WebDriverException: Method has not yet been implemented (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'mbp-maksim.iba', ip: 'fe80:0:0:0:442:3430:ea1e:bb89%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.5', java.version: '1.8.0_202'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {androidDeviceReadyTimeout: 50, app: /Users/maksimliakhavets/Ide..., appActivity: com.ronte.blackcatcard.dev...., appPackage: com.ronte.blackcatcard.dev, appWaitDuration: 50000, applicationCacheEnabled: true, autoAcceptAlerts: true, autoGrantPermissions: true, automationName: UiAutomator2, clearSystemFiles: true, databaseEnabled: false, desired: {androidDeviceReadyTimeout: 50, app: /Users/maksimliakhavets/Ide..., appActivity: com.ronte.blackcatcard.dev...., appPackage: com.ronte.blackcatcard.dev, appWaitDuration: 50000, applicationCacheEnabled: true, autoAcceptAlerts: true, autoGrantPermissions: true, automationName: UiAutomator2, clearSystemFiles: true, deviceName: Nexus_5X_API_26, deviceReadyTimeout: 50, ensureCleanSession: true, fullReset: false, javascriptEnabled: true, language: en, locale: US, newCommandTimeout: 50, noReset: false, pageLoadStrategy: normal, platformName: Android, platformVersion: 9.0, recreateChromeDriverSessions: true, resetKeyboard: true, setWebContentsDebuggingEnabled: true, showChromedriverLog : true, skipUnlock: true, startIWDP: true, udid: emulator-5554, unicodeKeyboard: true, useJSONSource: true, version: 9.0}, deviceApiLevel: 26, deviceManufacturer: Google, deviceModel: Android SDK built for x86, deviceName: emulator-5554, deviceReadyTimeout: 50, deviceScreenDensity: 420, deviceScreenSize: 1080x1920, deviceUDID: emulator-5554, ensureCleanSession: true, fullReset: false, javascriptEnabled: true, language: en, locale: US, locationContextEnabled: false, networkConnectionEnabled: true, newCommandTimeout: 50, noReset: false, pageLoadStrategy: normal, pixelRatio: 2.625, platform: LINUX, platformName: Android, platformVersion: 8.0.0, recreateChromeDriverSessions: true, resetKeyboard: true, setWebContentsDebuggingEnabled: true, showChromedriverLog : true, skipUnlock: true, startIWDP: true, statBarHeight: 63, takesScreenshot: true, udid: emulator-5554, unicodeKeyboard: true, useJSONSource: true, version: 9.0, viewportRect: {height: 1731, left: 0, top: 63, width: 1080}, warnings: {}, webStorageEnabled: false}
Session ID: 2f9ff89b-a330-4030-b022-b4d9ca688e0a

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at io.appium.java_client.PerformsTouchActions.performTouchAction(PerformsTouchActions.java:41)
	at io.appium.java_client.TouchAction.perform(TouchAction.java:187)
```
## Code To Reproduce Issue [ Good To Have ]
```
new TouchAction(driver)
                .tap(new PointOption().withCoordinates((int) fromX, (int) fromY))
                .waitAction(WaitOptions.waitOptions(Duration.ofSeconds((long) duration)))
                .moveTo(PointOption.point((int) toX, (int) toY))
                .release()
                .perform();
```

**Comment by mykola-mokhnach** [comment]
Please attach full server log.

In general, swipe should only work in native context (and it does), however in the recent UIA2 releases we've made this less strict. It means that using TouchAction would not fail being called from web context, but it is still invoked for the native context and uses native coordinates and elements.
