### ISSUE TITLE
Appium_Error : Returned value cannot be converted to WebElement with Xcode 10.0

### ISSUE THREAD

**Issue by bindacharyaj** [appium/appium#12846]
## The problem

Appium_Error : Returned value cannot be converted to WebElement with Xcode 10.0
Appium launches the app but not able to click on any of the native elements.

## Environment

Xcode Version : 10.0 
Appium Server Version : 1.9.1 / 1.13.0
Appium Client Version : 6.1.0 / 7.0.0
Selenium Version : 3.9.1 / 3.14.0
IOS Simulator Version : 11.4

## Details

If necessary, describe the problem you have been experiencing in more detail.

## No Error in Appium Logs for the same

Have tried with different versions as below:
Appium Server version : from 1.7.2 to 1.14.2 beta
Appium Client version : 5.0.4 to 7.0.0
Also tried to include implicit wait and explicit waits as well. No luck :(

Any help would be appreciated!!

Thanks in advance... !!!!

**Comment by mykola-mokhnach** [comment]
Sorry, but we cannot help nothing without detailed logs/code examples

**Comment by bindacharyaj** [comment]
Code is as below :


public class TestIOSAnother {

	public static final String APPIUM_SERVER_URL = "http://127.0.0.1:4723/wd/hub";

	public static final String AUTOMATION_NAME = "XCUITest";
	public static final String PLATFORM = "iOS";

	// iOS properties
	public static IOSDriver iosDriver;
	public static final String IOS = "iOS";
	public static final String BUNDLE_ID = "com.noo.xxxxx”;

	public static final String IOS_DEVICE_NAME = "iPhone 8";

	public static By element = By.xpath(
			"//XCUIElementTypeApplication[@name='نون أكاديمي']/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeCollectionView/XCUIElementTypeCell[2]/XCUIElementTypeOther/XCUIElementTypeImage");

	@BeforeSuite
	public static void setupDriver() throws IOException, InterruptedException {
		prepareIOSForAppium();
	}

	public static void prepareIOSForAppium() throws IOException, InterruptedException {
		// Set APP file path

		DesiredCapabilities capabilities = new DesiredCapabilities();
		// Mandatory capabilities
		capabilities.setCapability("deviceName", IOS_DEVICE_NAME);
		capabilities.setCapability("platformName", IOS);
		// Install IPA file from the above path
			capabilities.setCapability(MobileCapabilityType.APP,
					"/Users/XXXX/Documents/Simulator/IOSAPP-ios.app");


		capabilities.setCapability("platformVersion", "11.4");

		capabilities.setCapability("showXcodeLog", Boolean.TRUE);
		capabilities.setCapability("fullReset", Boolean.TRUE);
		capabilities.setCapability("automationName", AUTOMATION_NAME);
		capabilities.setCapability("useNewWDA", Boolean.TRUE);
		capabilities.setCapability(MobileCapabilityType.UDID, "4E3F1E99-0240-455B-9AFC-4F62F12E48A4");
		capabilities.setCapability("updatedWDABundleId", "com.facebook.wda.lib");
		capabilities.setCapability("wdaLocalPort", 8101);

		capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, "60");
		capabilities.setCapability("wdaStartupRetries", 5);
		capabilities.setCapability("autoAcceptAlerts", true);

		iosDriver = new IOSDriver(new URL(APPIUM_SERVER_URL), capabilities);
		iosDriver.manage().timeouts().implicitlyWait(15, TimeUnit.SECONDS);
		Thread.sleep(5000);
		MobileElement el2 = (MobileElement) iosDriver.findElementByAccessibilityId(“xxxxx”);
		Thread.sleep(2000);
		el2.click();

}






**Logs from Appium Server Side :** 





The server is running
[Xcode]     t =     7.41s Snapshot accessibility hierarchy for app with pid 31211
[Xcode] 
[Xcode]     t =     7.44s Find: Descendants matching type Alert
[Xcode] 
[Xcode]     t =     7.44s Snapshot accessibility hierarchy for app with pid 31211
[Xcode] 
[Xcode]     t =     7.46s Find: Descendants matching type Sheet
[Xcode] 
[Xcode]     t =     9.56s Snapshot accessibility hierarchy for app with pid 31211
[Xcode] 
[Xcode]     t =     9.58s Find: Descendants matching type Alert
[Xcode] 
[Xcode]     t =     9.58s Snapshot accessibility hierarchy for app with pid 31211
[Xcode] 
[Xcode]     t =     9.60s Find: Descendants matching type Sheet
[Xcode] 
[Xcode]     t =    11.70s Snapshot accessibility hierarchy for app with pid 31211
[Xcode] 
[Xcode]     t =    11.72s Find: Descendants matching type Alert
[Xcode] 
[Xcode]     t =    11.72s Snapshot accessibility hierarchy for app with pid 31211
[Xcode] 
[Xcode]     t =    11.74s Find: Descendants matching type Sheet
[Xcode] 
[HTTP] --> POST /wd/hub/session/5fc229a9-5c42-4b24-8d31-7ba0de473340/element
[HTTP] {"value":"إبدأ الأن!","using":"accessibility id"}
[W3C (5fc229a9)] Calling AppiumDriver.findElement() with args: ["accessibility id","إبدأ الأن!","5fc229a9-5c42-4b24-8d31-7ba0de473340"]
[XCUITest] Executing command 'findElement'
[BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[BaseDriver] Waiting up to 15000 ms for condition
[WD Proxy] Matched '/element' to command name 'findElement'
[WD Proxy] Proxying [POST /element] to [POST http://localhost:8101/session/DD203526-250F-4661-8E69-403065BBE820/element] with body: {"using":"accessibility id","value":"إبدأ الأن!"}
[Xcode]     t =    12.03s Find the Application 'com.noonEdu.k12App'
[Xcode]     t =    12.03s     Snapshot accessibility hierarchy for app with pid 31351
[Xcode] 
[Xcode]     t =    12.06s Snapshot accessibility hierarchy for app with pid 31351
[Xcode] 
[Xcode]     t =    12.08s Find: Descendants matching type Any
[Xcode] 
[Xcode]     t =    12.08s Find: Elements matching predicate '"إبدأ الأن!" IN identifiers'
[Xcode] 
[WD Proxy] Got response with status 200: {"value":{"using":"accessibility id","value":"إبدأ الأن!","description":"unable to find an element"},"sessionId":"DD203526-250F-4661-8E69-403065BBE820","status":7}
[WD Proxy] Got an unexpected response: {"value":{"using":"accessibility id","value":"إبدأ الأن!","description":"unable to find an element"},"sessionId":"DD203526-250F-4661-8E69-403065BBE820","status":7}
[MJSONWP] Matched JSONWP error code 7 to NoSuchElementError
[BaseDriver] Waited for 72 ms so far
[WD Proxy] Matched '/element' to command name 'findElement'
[WD Proxy] Proxying [POST /element] to [POST http://localhost:8101/session/DD203526-250F-4661-8E69-403065BBE820/element] with body: {"using":"accessibility id","value":"إبدأ الأن!"}
[Xcode]     t =    12.61s Find the Application 'com.noonEdu.k12App'
[Xcode] 
[Xcode]     t =    12.61s     Snapshot accessibility hierarchy for app with pid 31351
[Xcode] 
[Xcode]     t =    12.63s Snapshot accessibility hierarchy for app with pid 31351
[Xcode] 
[Xcode]     t =    12.65s Find: Descendants matching type Any
[Xcode] 
[Xcode]     t =    12.65s Find: Elements matching predicate '"إبدأ الأن!" IN identifiers'
[Xcode] 
[WD Proxy] Got response with status 200: {"value":{"using":"accessibility id","value":"إبدأ الأن!","description":"unable to find an element"},"sessionId":"DD203526-250F-4661-8E69-403065BBE820","status":7}
[WD Proxy] Got an unexpected response: {"value":{"using":"accessibility id","value":"إبدأ الأن!","description":"unable to find an element"},"sessionId":"DD203526-250F-4661-8E69-403065BBE820","status":7}
[MJSONWP] Matched JSONWP error code 7 to NoSuchElementError
[BaseDriver] Waited for 640 ms so far
[WD Proxy] Matched '/element' to command name 'findElement'
[WD Proxy] Proxying [POST /element] to [POST http://localhost:8101/session/DD203526-250F-4661-8E69-403065BBE820/element] with body: {"using":"accessibility id","value":"إبدأ الأن!"}
[Xcode]     t =    13.17s Find the Application 'com.noonEdu.k12App'
[Xcode] 
[Xcode]     t =    13.17s     Snapshot accessibility hierarchy for app with pid 31351
[Xcode] 
[Xcode]     t =    13.19s Snapshot accessibility hierarchy for app with pid 31351
[Xcode] 
[Xcode]     t =    13.20s Find: Descendants matching type Any
[Xcode] 
[Xcode]     t =    13.20s Find: Elements matching predicate '"إبدأ الأن!" IN identifiers'
[Xcode] 
[WD Proxy] Got response with status 200: {"value":{"using":"accessibility id","value":"إبدأ الأن!","description":"unable to find an element"},"sessionId":"DD203526-250F-4661-8E69-403065BBE820","status":7}
[WD Proxy] Got an unexpected response: {"value":{"using":"accessibility id","value":"إبدأ الأن!","description":"unable to find an element"},"sessionId":"DD203526-250F-4661-8E69-403065BBE820","status":7}
[MJSONWP] Matched JSONWP error code 7 to NoSuchElementError
[BaseDriver] Waited for 1195 ms so far
[WD Proxy] Matched '/element' to command name 'findElement'
[WD Proxy] Proxying [POST /element] to [POST http://localhost:8101/session/DD203526-250F-4661-8E69-403065BBE820/element] with body: {"using":"accessibility id","value":"إبدأ الأن!"}
[Xcode]     t =    13.73s Find the Application 'com.noonEdu.k12App'
[Xcode] 
[Xcode]     t =    13.73s     Snapshot accessibility hierarchy for app with pid 31351
[Xcode] 
[Xcode]     t =    13.75s Snapshot accessibility hierarchy for app with pid 31351
[Xcode] 
[Xcode]     t =    13.76s Find: Descendants matching type Any
[Xcode] 
[Xcode]     t =    13.76s Find: Elements matching predicate '"إبدأ الأن!" IN identifiers'
[Xcode] 
[WD Proxy] Got response with status 200: {"value":{"using":"accessibility id","value":"إبدأ الأن!","description":"unable to find an element"},"sessionId":"DD203526-250F-4661-8E69-403065BBE820","status":7}
[WD Proxy] Got an unexpected response: {"value":{"using":"accessibility id","value":"إبدأ الأن!","description":"unable to find an element"},"sessionId":"DD203526-250F-4661-8E69-403065BBE820","status":7}
[MJSONWP] Matched JSONWP error code 7 to NoSuchElementError
[BaseDriver] Waited for 1756 ms so far
[Xcode]     t =    13.83s Snapshot accessibility hierarchy for app with pid 31351
[Xcode] 
[Xcode]     t =    13.84s Find: Descendants matching type Alert
[Xcode] 
[Xcode]     t =    13.85s Snapshot accessibility hierarchy for app with pid 31351
[Xcode] 
[Xcode]     t =    13.86s Find: Descendants matching type Sheet
[Xcode] 
[WD Proxy] Matched '/element' to command name 'findElement'
[WD Proxy] Proxying [POST /element] to [POST http://localhost:8101/session/DD203526-250F-4661-8E69-403065BBE820/element] with body: {"using":"accessibility id","value":"إبدأ الأن!"}
[Xcode]     t =    14.29s Find the Application 'com.noonEdu.k12App'
[Xcode] 
[Xcode]     t =    14.29s     Snapshot accessibility hierarchy for app with pid 31351
[Xcode] 
[Xcode]     t =    14.31s Snapshot accessibility hierarchy for app with pid 31351
[Xcode] 
[Xcode]     t =    14.32s Find: Descendants matching type Any
[Xcode] 
[Xcode]     t =    14.32s Find: Elements matching predicate '"إبدأ الأن!" IN identifiers'
[Xcode] 
[WD Proxy] Got response with status 200: {"value":{"using":"accessibility id","value":"إبدأ الأن!","description":"unable to find an element"},"sessionId":"DD203526-250F-4661-8E69-403065BBE820","status":7}
[WD Proxy] Got an unexpected response: {"value":{"using":"accessibility id","value":"إبدأ الأن!","description":"unable to find an element"},"sessionId":"DD203526-250F-4661-8E69-403065BBE820","status":7}
[MJSONWP] Matched JSONWP error code 7 to NoSuchElementError
[BaseDriver] Waited for 2312 ms so far
[WD Proxy] Matched '/element' to command name 'findElement'
[WD Proxy] Proxying [POST /element] to [POST http://localhost:8101/session/DD203526-250F-4661-8E69-403065BBE820/element] with body: {"using":"accessibility id","value":"إبدأ الأن!"}
[Xcode]     t =    14.85s Find the Application 'com.noonEdu.k12App'
[Xcode] 
[Xcode]     t =    14.85s     Snapshot accessibility hierarchy for app with pid 31351
[Xcode] 
[Xcode]     t =    14.86s Snapshot accessibility hierarchy for app with pid 31351
[Xcode] 
[Xcode]     t =    14.88s Find: Descendants matching type Any
[Xcode] 
[Xcode]     t =    14.88s Find: Elements matching predicate '"إبدأ الأن!" IN identifiers'
[Xcode] 
[WD Proxy] Got response with status 200: {"value":{"using":"accessibility id","value":"إبدأ الأن!","description":"unable to find an element"},"sessionId":"DD203526-250F-4661-8E69-403065BBE820","status":7}
[WD Proxy] Got an unexpected response: {"value":{"using":"accessibility id","value":"إبدأ الأن!","description":"unable to find an element"},"sessionId":"DD203526-250F-4661-8E69-403065BBE820","status":7}
[MJSONWP] Matched JSONWP error code 7 to NoSuchElementError
[BaseDriver] Waited for 2870 ms so far
[WD Proxy] Matched '/element' to command name 'findElement'
[WD Proxy] Proxying [POST /element] to [POST http://localhost:8101/session/DD203526-250F-4661-8E69-403065BBE820/element] with body: {"using":"accessibility id","value":"إبدأ الأن!"}
[Xcode]     t =    15.40s Find the Application 'com.noonEdu.k12App'
[Xcode] 
[Xcode]     t =    15.41s     Snapshot accessibility hierarchy for app with pid 31351
[Xcode] 
[Xcode]     t =    15.42s Snapshot accessibility hierarchy for app with pid 31351
[Xcode] 
[Xcode]     t =    15.43s Find: Descendants matching type Any
[Xcode] 
[Xcode]     t =    15.44s Find: Elements matching predicate '"إبدأ الأن!" IN identifiers'
[Xcode] 
[WD Proxy] Got response with status 200: {"value":{"using":"accessibility id","value":"إبدأ الأن!","description":"unable to find an element"},"sessionId":"DD203526-250F-4661-8E69-403065BBE820","status":7}
[WD Proxy] Got an unexpected response: {"value":{"using":"accessibility id","value":"إبدأ الأن!","description":"unable to find an element"},"sessionId":"DD203526-250F-4661-8E69-403065BBE820","status":7}
[MJSONWP] Matched JSONWP error code 7 to NoSuchElementError
[BaseDriver] Waited for 3427 ms so far
[WD Proxy] Matched '/element' to command name 'findElement'
[WD Proxy] Proxying [POST /element] to [POST http://localhost:8101/session/DD203526-250F-4661-8E69-403065BBE820/element] with body: {"using":"accessibility id","value":"إبدأ الأن!"}
[Xcode]     t =    15.96s Find the Application 'com.noonEdu.k12App'
[Xcode] 
[Xcode]     t =    15.96s     Snapshot accessibility hierarchy for app with pid 31351
[Xcode] 
[Xcode]     t =    15.98s Snapshot accessibility hierarchy for app with pid 31351
[Xcode] 
[Xcode]     t =    15.99s Find: Descendants matching type Any
[Xcode] 
[Xcode]     t =    16.00s Find: Elements matching predicate '"إبدأ الأن!" IN identifiers'
[Xcode] 
[WD Proxy] Got response with status 200: {"value":{"using":"accessibility id","value":"إبدأ الأن!","description":"unable to find an element"},"sessionId":"DD203526-250F-4661-8E69-403065BBE820","status":7}
[WD Proxy] Got an unexpected response: {"value":{"using":"accessibility id","value":"إبدأ الأن!","description":"unable to find an element"},"sessionId":"DD203526-250F-4661-8E69-403065BBE820","status":7}
[MJSONWP] Matched JSONWP error code 7 to NoSuchElementError
[BaseDriver] Waited for 3987 ms so far
[Xcode]     t =    16.00s Snapshot accessibility hierarchy for app with pid 31351
[Xcode] 
[Xcode]     t =    16.01s Find: Descendants matching type Alert
[Xcode] 
[Xcode]     t =    16.01s Snapshot accessibility hierarchy for app with pid 31351
[Xcode] 
[Xcode]     t =    16.02s Find: Descendants matching type Sheet
[Xcode] 
[WD Proxy] Matched '/element' to command name 'findElement'
[WD Proxy] Proxying [POST /element] to [POST http://localhost:8101/session/DD203526-250F-4661-8E69-403065BBE820/element] with body: {"using":"accessibility id","value":"إبدأ الأن!"}
[Xcode]     t =    16.52s Find the Application 'com.noonEdu.k12App'
[Xcode] 
[Xcode]     t =    16.52s     Snapshot accessibility hierarchy for app with pid 31351
[Xcode] 
[Xcode]     t =    16.54s Snapshot accessibility hierarchy for app with pid 31351
[Xcode] 
[Xcode]     t =    16.55s Find: Descendants matching type Any
[Xcode] 
[Xcode]     t =    16.55s Find: Elements matching predicate '"إبدأ الأن!" IN identifiers'
[Xcode] 
[WD Proxy] Got response with status 200: {"value":{"using":"accessibility id","value":"إبدأ الأن!","description":"unable to find an element"},"sessionId":"DD203526-250F-4661-8E69-403065BBE820","status":7}
[WD Proxy] Got an unexpected response: {"value":{"using":"accessibility id","value":"إبدأ الأن!","description":"unable to find an element"},"sessionId":"DD203526-250F-4661-8E69-403065BBE820","status":7}
[MJSONWP] Matched JSONWP error code 7 to NoSuchElementError
[BaseDriver] Waited for 4546 ms so far
[WD Proxy] Matched '/element' to command name 'findElement'
[WD Proxy] Proxying [POST /element] to [POST http://localhost:8101/session/DD203526-250F-4661-8E69-403065BBE820/element] with body: {"using":"accessibility id","value":"إبدأ الأن!"}
[Xcode]     t =    17.08s Find the Application 'com.noonEdu.k12App'
[Xcode] 
[Xcode]     t =    17.08s     Snapshot accessibility hierarchy for app with pid 31351
[Xcode] 
[Xcode]     t =    17.09s Snapshot accessibility hierarchy for app with pid 31351
[Xcode] 
[Xcode]     t =    17.11s Find: Descendants matching type Any
[Xcode] 
[Xcode]     t =    17.11s Find: Elements matching predicate '"إبدأ الأن!" IN identifiers'
[Xcode] 
[WD Proxy] Got response with status 200: {"value":{"using":"accessibility id","value":"إبدأ الأن!","description":"unable to find an element"},"sessionId":"DD203526-250F-4661-8E69-403065BBE820","status":7}
[WD Proxy] Got an unexpected response: {"value":{"using":"accessibility id","value":"إبدأ الأن!","description":"unable to find an element"},"sessionId":"DD203526-250F-4661-8E69-403065BBE820","status":7}
[MJSONWP] Matched JSONWP error code 7 to NoSuchElementError
[BaseDriver] Waited for 5099 ms so far
[WD Proxy] Matched '/element' to command name 'findElement'
[WD Proxy] Proxying [POST /element] to [POST http://localhost:8101/session/DD203526-250F-4661-8E69-403065BBE820/element] with body: {"using":"accessibility id","value":"إبدأ الأن!"}
[Xcode]     t =    17.64s Find the Application 'com.noonEdu.k12App'
[Xcode] 
[Xcode]     t =    17.64s     Snapshot accessibility hierarchy for app with pid 31351
[Xcode] 
[Xcode]     t =    17.76s Snapshot accessibility hierarchy for app with pid 31351
[Xcode] 
[Xcode]     t =    17.79s Find: Descendants matching type Any
[Xcode] 
[Xcode]     t =    17.79s Find: Elements matching predicate '"إبدأ الأن!" IN identifiers'
[Xcode] 
[Xcode]     t =    17.79s Get all elements bound by accessibility element for: Elements matching predicate '"إبدأ الأن!" IN identifiers'
[Xcode] 
[Xcode]     t =    17.80s     Snapshot accessibility hierarchy for app with pid 31351
[Xcode] 
[Xcode]     t =    17.82s     Find: Descendants matching type Any
[Xcode] 
[Xcode]     t =    17.82s     Find: Elements matching predicate '"إبدأ الأن!" IN identifiers'
[Xcode] 
[Xcode]     t =    17.82s Snapshot accessibility hierarchy for app with pid 31351
[Xcode] 
[Xcode]     t =    17.84s Find: Descendants matching type Any
[Xcode] 
[Xcode]     t =    17.84s Find: Elements matching predicate '"إبدأ الأن!" IN identifiers'
[Xcode] 
[Xcode]     t =    17.84s Find: Identity Binding
[Xcode] 
[Xcode]     t =    17.84s Snapshot accessibility hierarchy for app with pid 31351
[Xcode] 
[Xcode]     t =    17.85s Find: Descendants matching type Any
[Xcode] 
[Xcode]     t =    17.85s Find: Elements matching predicate '"إبدأ الأن!" IN identifiers'
[Xcode] 
[Xcode]     t =    17.85s Find: Identity Binding
[Xcode] 
[WD Proxy] Got response with status 200: {"value":{"ELEMENT":"2B000000-0000-0000-777A-000000000000"},"sessionId":"DD203526-250F-4661-8E69-403065BBE820","status":0}
[W3C (5fc229a9)] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"2B000000-0000-0000-777A-000000000000","ELEMENT":"2B000000-0000-0000-777A-000000000000"}
[HTTP] <-- POST /wd/hub/session/5fc229a9-5c42-4b24-8d31-7ba0de473340/element 200 5845 ms - 137
[HTTP] 
[Xcode]     t =    18.09s Snapshot accessibility hierarchy for app with pid 31351
[Xcode] 
[Xcode]     t =    18.12s Find: Descendants matching type Alert
[Xcode] 
[Xcode]     t =    18.12s Snapshot accessibility hierarchy for app with pid 31351
[Xcode] 
[Xcode]     t =    18.14s Find: Descendants matching type Sheet
[Xcode] 
[Xcode]     t =    20.25s Snapshot accessibility hierarchy for app with pid 31351
[Xcode] 
[Xcode]     t =    20.26s Find: Descendants matching type Alert
[Xcode] 
[Xcode]     t =    20.26s Snapshot accessibility hierarchy for app with pid 31351
[Xcode] 
[Xcode]     t =    20.27s Find: Descendants matching type Sheet
[Xcode] 
[Xcode]     t =    22.38s Snapshot accessibility hierarchy for app with pid 31351
[Xcode] 
[Xcode]     t =    22.39s Find: Descendants matching type Alert
[Xcode] 
[Xcode]     t =    22.40s Snapshot accessibility hierarchy for app with pid 31351
[Xcode] 
[Xcode]     t =    22.41s Find: Descendants matching type Sheet
[Xcode] 
[Xcode]     t =    24.41s Snapshot accessibility hierarchy for app with pid 31351
[Xcode] 
[Xcode]     t =    24.43s Find: Descendants matching type Alert
[Xcode] 
[Xcode]     t =    24.43s Snapshot accessibility hierarchy for app with pid 31351
[Xcode] 
[Xcode]     t =    24.44s Find: Descendants matching type Sheet
[Xcode] 
[Xcode]     t =    26.47s Snapshot accessibility hierarchy for app with pid 31351
[Xcode] 
[Xcode]     t =    26.49s Find: Descendants matching type Alert
[Xcode] 
[Xcode]     t =    26.49s Snapshot accessibility hierarchy for app with pid 31351
[Xcode] 
[Xcode]     t =    26.50s Find: Descendants matching type Sheet
[Xcode] 
[Xcode]     t =    28.61s Snapshot accessibility hierarchy for app with pid 31351
[Xcode] 
[Xcode]     t =    28.63s Find: Descendants matching type Alert
[Xcode] 
[Xcode]     t =    28.63s Snapshot accessibility hierarchy for app with pid 31351
[Xcode] 
[Xcode]     t =    28.64s Find: Descendants matching type Sheet
[Xcode] 
[Xcode]     t =    30.75s Snapshot accessibility hierarchy for app with pid 31351
[Xcode] 
[Xcode]     t =    30.78s Find: Descendants matching type Alert
[Xcode] 
[Xcode]     t =    30.78s Snapshot accessibility hierarchy for app with pid 31351
[Xcode] 
[Xcode]     t =    30.80s Find: Descendants matching type Sheet
[Xcode] 
[Xcode]     t =    32.81s Snapshot accessibility hierarchy for app with pid 31351
[Xcode] 
[Xcode]     t =    32.84s Find: Descendants matching type Alert
[Xcode] 
[Xcode]     t =    32.84s Snapshot accessibility hierarchy for app with pid 31351
[Xcode] 
[Xcode]     t =    32.86s Find: Descendants matching type Sheet
[Xcode] 
[Xcode]     t =    34.88s Snapshot accessibility hierarchy for app with pid 31351
[Xcode] 
[Xcode]     t =    34.89s Find: Descendants matching type Alert
[Xcode] 
[Xcode]     t =    34.89s Snapshot accessibility hierarchy for app with pid 31351
[Xcode] 
[Xcode]     t =    34.91s Find: Descendants matching type Sheet
[Xcode] 
[Xcode]     t =    36.99s Snapshot accessibility hierarchy for app with pid 31351
[Xcode] 
[Xcode]     t =    37.01s Find: Descendants matching type Alert
[Xcode] 
[Xcode]     t =    37.02s Snapshot accessibility hierarchy for app with pid 31351
[Xcode] 
[Xcode]     t =    37.03s Find: Descendants matching type Sheet
[Xcode] 









**Appium Logs Client Side as below:** 





[RemoteTestNG] detected TestNG version 6.11.0
Jul 01, 2019 10:34:30 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
FAILED CONFIGURATION: @BeforeSuite setupDriver
org.openqa.selenium.WebDriverException: Returned value cannot be converted to WebElement: {element-6066-11e4-a52e-4f735466cecf=2B000000-0000-0000-777A-000000000000, ELEMENT=2B000000-0000-0000-777A-000000000000}
Build info: version: '3.5.2', revision: '10229a9', time: '2017-08-21T17:29:55.15Z'
System info: host: 'Bindacharyas-MacBook-Pro.local', ip: 'fe80:0:0:0:c4b:5bdc:c1c1:72f2%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.5', java.version: '1.8.0_211'
Driver info: driver.version: IOSDriver
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:421)
	at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:62)
	at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.findElement(IOSDriver.java:1)
	at io.appium.java_client.FindsByAccessibilityId.findElementByAccessibilityId(FindsByAccessibilityId.java:31)
	at com.noon.ui.tests.sanitySuites.TestIOSAnother.prepareIOSForAppium(TestIOSAnother.java:103)
	at com.noon.ui.tests.sanitySuites.TestIOSAnother.setupDriver(TestIOSAnother.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:326)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.ClassCastException: java.util.HashMap cannot be cast to org.openqa.selenium.WebElement
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:419)
	... 25 more



Please let me know in case of anything else is needed ... Thanks!!

**Comment by mykola-mokhnach** [comment]
> Build info: version: '3.5.2', 

You selenium client is out of date. The problem has nothing to do with Appium server

**Comment by bindacharyaj** [comment]
M using 3.14.0 currently. it's not working still. Which version is out of date?

**Comment by bindacharyaj** [comment]
@mykola-mokhnach : Please help me here

**Comment by mykola-mokhnach** [comment]
I don't know how the project dependencies are structured, but the stacktrace shows the version above. I'll move the issue to java client.
