### ISSUE TITLE
Can't find package bplist-creator's version: 0.0.8

### ISSUE THREAD

**Issue by liweiting** [appium/appium#12900]
## The problem

tnpm install appium 

Install fail! Error: [appium@1.14.0 鈥? appium-xcuitest-driver@2.122.0 鈥? appium-ios-device@0.3.0 鈥? bplist-creator@0.0.8] Can't find package bplist-creator's version: 0.0.8
Error: [appium@1.14.0 鈥? appium-xcuitest-driver@2.122.0 鈥? appium-ios-device@0.3.0 鈥? bplist-creator@0.0.8] Can't find package bplist-creator's version: 0.0.8
    at resolve (/usr/local/lib/node_modules/tnpm/node_modules/npminstall/lib/download/npm.js:97:11)
    at resolve.next (<anonymous>)
    at onFulfilled (/usr/local/lib/node_modules/tnpm/node_modules/co/index.js:65:19)
    at /usr/local/lib/node_modules/tnpm/node_modules/co/index.js:54:5
    at new Promise (<anonymous>)
    at co (/usr/local/lib/node_modules/tnpm/node_modules/co/index.js:50:10)
    at toPromise (/usr/local/lib/node_modules/tnpm/node_modules/co/index.js:118:63)
    at next (/usr/local/lib/node_modules/tnpm/node_modules/co/index.js:99:29)
    at onFulfilled (/usr/local/lib/node_modules/tnpm/node_modules/co/index.js:69:7)
    at /usr/local/lib/node_modules/tnpm/node_modules/co/index.js:54:5
npminstall version: 3.10.0
npminstall args: /usr/local/Cellar/node/10.7.0/bin/node /usr/local/lib/node_modules/tnpm/node_modules/npminstall/bin/install.js --tmp=/Users/weiting.lwt/.tnpm_tmp --no-proxy --disturl=https://tnpm-hz.oss-cn-hangzhou.aliyuncs.com/dist/node --userconfig=/Users/weiting.lwt/.tnpmrc --registry=http://registry.npm.alibaba-inc.com appium --china --prefix=/usr/local --forbidden-licenses=AGPL,CPAL,OSL --fix-bug-versions
[tnpm] subprocess:/usr/local/lib/node_modules/tnpm/node_modules/npminstall/bin/install.js exit code: 1, signal: null
[tnpm] mainprocess exit code: 1

**Comment by umutuzgur** [comment]
Hi @liweiting .There must be something wrong with your npm registry. I see no problem installing appium on my computer

**Comment by liweiting** [comment]
but tnpm install bplist-creator@0.0.8 

 tnpm install bplist-creator@0.0.8
鉁? Install fail! Error: [bplist-creator@0.0.8] Can't find package bplist-creator's version: 0.0.8
Error: [bplist-creator@0.0.8] Can't find package bplist-creator's version: 0.0.8
    at resolve (/usr/local/lib/node_modules/tnpm/node_modules/npminstall/lib/download/npm.js:97:11)
    at resolve.next (<anonymous>)
    at onFulfilled (/usr/local/lib/node_modules/tnpm/node_modules/co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npminstall version: 3.10.0
npminstall args: /usr/local/Cellar/node/10.7.0/bin/node /usr/local/lib/node_modules/tnpm/node_modules/npminstall/bin/install.js --tmp=/Users/weiting.lwt/.tnpm_tmp --no-proxy --disturl=https://tnpm-hz.oss-cn-hangzhou.aliyuncs.com/dist/node --userconfig=/Users/weiting.lwt/.tnpmrc --registry=http://registry.npm.alibaba-inc.com bplist-creator@0.0.8 --china --prefix=/usr/local --forbidden-licenses=AGPL,CPAL,OSL --fix-bug-versions
[tnpm] subprocess:/usr/local/lib/node_modules/tnpm/node_modules/npminstall/bin/install.js exit code: 1, signal: null
[tnpm] mainprocess exit code: 1

**Comment by KazuCocoa** [comment]
Is tnpm customised npm?

It looks the command refer http://registry.npm.alibaba-inc.com which might a private repository.
I think you should ask them if you can get the module via the repository.
