### ISSUE TITLE
Could not sign with default certificate. Original error Command '/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/bin/bin/java' not found.

### ISSUE THREAD

**Issue by aruvimal** [appium/appium#12914]
## The problem

Getting below Error on executing the capability with AutomationName as UiAutomator2

### **org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Could not sign with default certificate. Original error Command '/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/bin/bin/java' not found. Is it installed?
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'USCHAMNMOG0JK78', ip: '2606:a000:1215:c3b2:d22:d22f:13ce:257a', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.5', java.version: '1.8.0_91'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not sign with default certificate. Original error Command '/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/bin/bin/java' not found. Is it installed?
    at getResponseForW3CError (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:826:9)
    at asyncHandler (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:447:37)**

**But same script works fine when i run AutoamtionName as UiAutomator1**. Please advise

**Comment by mykola-mokhnach** [comment]
Please fill out the issue details properly and provide the full server log
