### ISSUE TITLE
Unable to start Appium server 1.14.0 with Client 7.1.0 programmatically. 

### ISSUE THREAD

**Issue by padmakarsrinivas** [appium/appium#12943]
## The problem

Unable to start Appium server 1.14.0 with Client 7.1.0 programmatically. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.14.0
* Desktop OS/version used to run Appium: MAC Mojave 10.14.5
* Npm or Yarn package manager:6.10.1

## Details

Appium server 1.14.0 
Appium Client 7.1.0. 

I have set the bash profile as 

export ANDROID_HOME=/Users/srinivasv/Library/Android/sdk
export PATH=$ANDROID_HOME/platform-tools:$PATH
export PATH=$ANDROID_HOME/tools:$PATH
export PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin

## Link to Appium logs

FAILED CONFIGURATION: @BeforeSuite globalSetup
io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: The local appium server has not been started. The given Node.js executable: /usr/local/Cellar/node/12.5.0/bin/node Arguments: [/usr/local/lib/node_modules/appium/build/lib/main.js, --port, 4723, --address, 0.0.0.0] 

	at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:161)
	at com.appium.base.BaseTest.globalSetup(BaseTest.java:18)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.NoSuchMethodError: com.google.common.util.concurrent.SimpleTimeLimiter.create(Ljava/util/concurrent/ExecutorService;)Lcom/google/common/util/concurrent/SimpleTimeLimiter;
	at org.openqa.selenium.net.UrlChecker.<init>(UrlChecker.java:62)
	at io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:125)
	at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:148)
	... 21 more

## Code To Reproduce Issue [ Good To Have ]

public class BaseTest {

	private static AppiumDriverLocalService service;

	@BeforeSuite
	public void globalSetup () throws IOException {
		service = AppiumDriverLocalService.buildDefaultService();
		service.start();
	}

	@AfterSuite
	public void globalTearDown () {
		service.stop();
	}

	public URL getServiceUrl () {
		return service.getUrl();
	}
}

**Comment by umutuzgur** [comment]
@padmakarsrinivas How does you pom.xml or gradle dependency config look like. It seems to be a problem with the guava dependency. Do you set a version explicit in your config?

**Comment by padmakarsrinivas** [comment]
Found what is wrong updated my guava dependency it is working now.
