### ISSUE TITLE
Issue in Running Appium from Terminal

### ISSUE THREAD

**Issue by aruvimal** [appium/appium#12950]
## The problem
i'm manually running Appium from Terminal by just typing Appium. But script is getting failed with below error message while installing Webdriver Agent in Simulator. 

**But Same script works fine when i trying  to running the script using Appium Desktop ** 

## Error In Terminal
```
USCHAMNMOG0JK78:~ vz8zw5$ Appium
[Appium] Welcome to Appium v1.14.0
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"proxy":{"proxyAutoconfigUrl":"https://10.47.196.150:9191","proxyType":"PAC"},"noReset":"false","platformVersion":"12.1","automationName":"XCUITest","browserName":"safari","platformName":"iOS","deviceName":"iPhone X"},"capabilities":{"firstMatch":[{"appium:automationName":"XCUITest","browserName":"safari","appium:deviceName":"iPhone X","appium:noReset":"false","platformName":"ios","appium:platformVersion":"12.1","proxy":{"proxyAutoconfigUrl":"https://10.47.196.150:9191","proxyType":"pac"}}]}}
[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"proxy":{"proxyAutoconfigUrl":"https://10.47.196.150:9191","proxyType":"PAC"},"noReset":"false","platformVersion":"12.1","automationName":"XCUITest","browserName":"safari","platformName":"iOS","deviceName":"iPhone X"},null,{"firstMatch":[{"appium:automationName":"XCUITest","browserName":"safari","appium:deviceName":"iPhone X","appium:noReset":"false","platformName":"ios","appium:platformVersion":"12.1","proxy":{"proxyAutoconfigUrl":"https://10.47.196.150:9191","proxyType":"pac"}}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1563832423801 (17:53:43 GMT-0400 (Eastern Daylight Time))
[Appium] Appium v1.14.0 creating new XCUITestDriver (v2.116.3) session
[Appium] Capabilities:
[Appium]   browserName: safari
[Appium]   platformName: ios
[Appium]   proxy: {
[Appium]     proxyAutoconfigUrl: https://10.47.196.150:9191
[Appium]     proxyType: pac
[Appium]   }
[Appium]   automationName: XCUITest
[Appium]   deviceName: iPhone X
[Appium]   noReset: false
[Appium]   platformVersion: 12.1
[debug] [BaseDriver] W3C capabilities {"alwaysMatch":{"browserNam... and MJSONWP desired capabilities {"proxy":{"proxyAutoconfigU... were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"browserNam...
[BaseDriver] Capability 'noReset' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by Appium:
[BaseDriver]   proxy
[BaseDriver] Session created with session id: 82a32fbf-7ab1-4246-936a-c53aeabf14c6
[debug] [XCUITest] Current user: 'vz8zw5'
[XCUITest] iOS SDK Version set to '12.1'
[iOSSim] Constructing iOS simulator for Xcode version 10.1 with udid 'F37B51B3-BB64-451F-A610-43ABADE495D4'
[XCUITest] Determining device to run tests on: udid: 'F37B51B3-BB64-451F-A610-43ABADE495D4', real device: false
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1563832425635 (17:53:45 GMT-0400 (Eastern Daylight Time))
[XCUITest] Safari test requested
[debug] [BaseDriver] Event 'appConfigured' logged at 1563832425636 (17:53:45 GMT-0400 (Eastern Daylight Time))
[debug] [BaseDriver] Event 'resetStarted' logged at 1563832425637 (17:53:45 GMT-0400 (Eastern Daylight Time))
[debug] [iOSSim] Cleaning mobile safari data files
[debug] [iOSSim] Checking whether simulator has been run before: yes
[debug] [iOSSim] Checking whether simulator has been run before: yes
[debug] [iOSSim] Building bundle path map
[debug] [BaseDriver] Event 'resetComplete' logged at 1563832427746 (17:53:47 GMT-0400 (Eastern Daylight Time))
[debug] [XCUITest] Starting log capture for iOS Simulator with udid 'F37B51B3-BB64-451F-A610-43ABADE495D4', using 'xcrun simctl spawn F37B51B3-BB64-451F-A610-43ABADE495D4 log stream --style compact'
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1563832428629 (17:53:48 GMT-0400 (Eastern Daylight Time))
[XCUITest] Setting up simulator
[debug] [iOS] No reason to set locale
[debug] [iOS] No iOS / app preferences to set
[debug] [iOS] Setting did not need to be updated
[debug] [iOSSim] Setting preferences of F37B51B3-BB64-451F-A610-43ABADE495D4 Simulator to {"ConnectHardwareKeyboard":false}
[debug] [iOSSim] Setting common Simulator preferences to {"RotateWindowWhenSignaledByGuest":true,"ConnectHardwareKeyboard":false}
[debug] [iOSSim] Updated F37B51B3-BB64-451F-A610-43ABADE495D4 Simulator preferences at '/Users/vz8zw5/Library/Preferences/com.apple.iphonesimulator.plist' with {"DevicePreferences":{"F37B51B3-BB64-451F-A610-43ABADE495D4":{"ConnectHardwareKeyboard":false}},"RotateWindowWhenSignaledByGuest":true,"ConnectHardwareKeyboard":false}
[iOSSim] Booting Simulator with UDID F37B51B3-BB64-451F-A610-43ABADE495D4...
[simctl] Error: simctl error running 'boot': An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=164):
[simctl] Unable to boot device in current state: Booted
[simctl]     at Object.wrappedLogger.errorAndThrow (/usr/local/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[simctl]     at errorAndThrow (/usr/local/lib/node_modules/appium/node_modules/node-simctl/lib/simctl.js:56:11)
[debug] [simctl] Simulator already in 'Booted' state. Continuing
[iOSSim] Starting Simulator UI with command: open -Fn /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID F37B51B3-BB64-451F-A610-43ABADE495D4 -ConnectHardwareKeyboard 0
[iOSSim] Simulator with UDID F37B51B3-BB64-451F-A610-43ABADE495D4 booted in 2 seconds
[debug] [IDB] Connecting idb service to 'F37B51B3-BB64-451F-A610-43ABADE495D4'
[XCUITest] idb will not be used for Simulator interaction. Original error: 'idb' has not been found in PATH. Is it installed? Read https://www.fbidb.io for more details
[debug] [BaseDriver] Event 'simStarted' logged at 1563832430714 (17:53:50 GMT-0400 (Eastern Daylight Time))
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[debug] [XCUITest] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[debug] [XCUITest] Parsed BUILD_DIR configuration value: '/Users/vz8zw5/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products'
[debug] [XCUITest] Got derived data root: '/Users/vz8zw5/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy'
[debug] [XCUITest] Starting WebDriverAgent initialization with the synchronization key '/Users/vz8zw5/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy'
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[debug] [XCUITest] WDA is not listening at 'http://localhost:8100/'
[debug] [XCUITest] WDA is currently not running. There is nothing to cache
[debug] [XCUITest] Trying to start WebDriverAgent 2 times with 10000ms interval
[debug] [XCUITest] These values can be customized by changing wdaStartupRetries/wdaStartupRetryInterval capabilities
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1563832435059 (17:53:55 GMT-0400 (Eastern Daylight Time))
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: 'node_modules/.bin/carthage'
[debug] [XCUITest] Killing running processes 'xcodebuild.*F37B51B3-BB64-451F-A610-43ABADE495D4, iproxy 8100, F37B51B3-BB64-451F-A610-43ABADE495D4.*XCTRunner' for the device F37B51B3-BB64-451F-A610-43ABADE495D4...
[debug] [XCUITest] 'pgrep -ifn xcodebuild.*F37B51B3-BB64-451F-A610-43ABADE495D4' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] 'pgrep -ifn iproxy 8100' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] 'pgrep -ifn F37B51B3-BB64-451F-A610-43ABADE495D4.*XCTRunner' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -derivedDataPath /Users/vz8zw5/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy -destination id=F37B51B3-BB64-451F-A610-43ABADE495D4 IPHONEOS_DEPLOYMENT_TARGET=12.1 GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will only be logged if any errors are present there. To change this, use 'showXcodeLog' desired capability
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[debug] [XCUITest] Log file for xcodebuild test: /Users/vz8zw5/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/Test-WebDriverAgentRunner-2019.07.22_17-53-57--0400.xcresult/2_Test/Diagnostics/WebDriverAgentRunner-95AC3289-226E-426D-875E-3E8B758B7A6C/WebDriverAgentRunner-D1769719-FB21-46B0-89D2-03376FC118B7/Session-WebDriverAgentRunner-2019-07-22_175358-43mz6D.log
[Xcode] 2019-07-22 17:53:58.385 xcodebuild[5170:293500] Error Domain=IDETestApplcationDependencyMapperErrorDomain Code=2 "The bundle identifier for IntegrationApp.app couldn’t be read." UserInfo={NSLocalizedFailureReason=The application may be damaged or incomplete: “/Users/vz8zw5/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/IntegrationApp.app”., NSURL=file:///Users/vz8zw5/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/IntegrationApp.app/, NSFilePath=/Users/vz8zw5/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/IntegrationApp.app, NSLocalizedDescription=The bundle identifier for IntegrationApp.app couldn’t be read.}
[Xcode] 
[Xcode] 2019-07-22 17:53:58.386 xcodebuild[5170:293500] Error Domain=IDETestOperationsObserverErrorDomain Code=4 "Failed to install or launch the test runner" UserInfo={NSLocalizedRecoverySuggestion=If you believe this error represents a bug, please attach the result bundle at /Users/vz8zw5/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/Test-WebDriverAgentRunner-2019.07.22_17-53-57--0400.xcresult, NSLocalizedDescription=Failed to install or launch the test runner, NSUnderlyingError=0x7f955eed09c0 {Error Domain=IDETestApplcationDependencyMapperErrorDomain Code=2 "The bundle identifier for IntegrationApp.app couldn’t be read." UserInfo={NSLocalizedFailureReason=The application may be damaged or incomplete: “/Users/vz8zw5/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/IntegrationApp.app”., NSURL=file:///Users/vz8zw5/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/IntegrationApp.app/, NSFilePath=/Users/vz8zw5/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/IntegrationApp.app, NSLocalizedDescription=The bundle identifier for IntegrationApp.app couldn’t be read.}}}
[Xcode] 
[Xcode] 
[Xcode] Testing failed:
[Xcode] 	The test runner encountered an error (Failed to install or launch the test runner. (Underlying error: The bundle identifier for IntegrationApp.app couldn’t be read. The application may be damaged or incomplete: “/Users/vz8zw5/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/IntegrationApp.app”.))
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[Xcode] Testing started on 'iPhone X'
[Xcode] 
[XCUITest] xcodebuild exited with code '65' and signal 'null'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: 'node_modules/.bin/carthage'
[debug] [XCUITest] Killing running processes 'xcodebuild.*F37B51B3-BB64-451F-A610-43ABADE495D4, iproxy 8100, F37B51B3-BB64-451F-A610-43ABADE495D4.*XCTRunner' for the device F37B51B3-BB64-451F-A610-43ABADE495D4...
[debug] [XCUITest] 'pgrep -ifn xcodebuild.*F37B51B3-BB64-451F-A610-43ABADE495D4' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] 'pgrep -ifn iproxy 8100' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] 'pgrep -ifn F37B51B3-BB64-451F-A610-43ABADE495D4.*XCTRunner' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -derivedDataPath /Users/vz8zw5/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy -destination id=F37B51B3-BB64-451F-A610-43ABADE495D4 IPHONEOS_DEPLOYMENT_TARGET=12.1 GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will only be logged if any errors are present there. To change this, use 'showXcodeLog' desired capability
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[debug] [XCUITest] Log file for xcodebuild test: /Users/vz8zw5/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/Test-WebDriverAgentRunner-2019.07.22_17-54-01--0400.xcresult/2_Test/Diagnostics/WebDriverAgentRunner-6BF2642D-698A-435A-A3C1-DA98AD00175B/WebDriverAgentRunner-B9A4D1CA-9BD7-4E54-91B9-3FF1BCD47220/Session-WebDriverAgentRunner-2019-07-22_175401-d5pbIy.log
[Xcode] 2019-07-22 17:54:01.846 xcodebuild[5179:293624] Error Domain=IDETestApplcationDependencyMapperErrorDomain Code=2 "The bundle identifier for IntegrationApp.app couldn’t be read." UserInfo={NSLocalizedFailureReason=The application may be damaged or incomplete: “/Users/vz8zw5/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/IntegrationApp.app”., NSURL=file:///Users/vz8zw5/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/IntegrationApp.app/, NSFilePath=/Users/vz8zw5/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/IntegrationApp.app, NSLocalizedDescription=The bundle identifier for IntegrationApp.app couldn’t be read.}
[Xcode] 
[Xcode] 2019-07-22 17:54:01.846 xcodebuild[5179:293624] Error Domain=IDETestOperationsObserverErrorDomain Code=4 "Failed to install or launch the test runner" UserInfo={NSLocalizedRecoverySuggestion=If you believe this error represents a bug, please attach the result bundle at /Users/vz8zw5/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/Test-WebDriverAgentRunner-2019.07.22_17-54-01--0400.xcresult, NSLocalizedDescription=Failed to install or launch the test runner, NSUnderlyingError=0x7fc8294627a0 {Error Domain=IDETestApplcationDependencyMapperErrorDomain Code=2 "The bundle identifier for IntegrationApp.app couldn’t be read." UserInfo={NSLocalizedFailureReason=The application may be damaged or incomplete: “/Users/vz8zw5/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/IntegrationApp.app”., NSURL=file:///Users/vz8zw5/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/IntegrationApp.app/, NSFilePath=/Users/vz8zw5/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/IntegrationApp.app, NSLocalizedDescription=The bundle identifier for IntegrationApp.app couldn’t be read.}}}
[Xcode] **
```

## Environment
nfo AppiumDoctor Appium Doctor v.1.11.1
info AppiumDoctor ### Diagnostic for necessary dependencies starting ###
info AppiumDoctor ✔ The Node.js binary was found at: /usr/local/bin/node
info AppiumDoctor ✔ Node version is 12.6.0
info AppiumDoctor ✔ Xcode is installed at: /Applications/Xcode.app/Contents/Developer
info AppiumDoctor ✔ Xcode Command Line Tools are installed in: /Applications/Xcode.app/Contents/Developer
info AppiumDoctor ✔ DevToolsSecurity is enabled.
info AppiumDoctor ✔ The Authorization DB is set up properly.
info AppiumDoctor ✔ Carthage was found at: /usr/local/bin/carthage. Installed version is: 0.33.0
info AppiumDoctor ✔ HOME is set to: /Users/vz8zw5
info AppiumDoctor ✔ ANDROID_HOME is set to: /Users/vz8zw5/Library/Android/sdk
info AppiumDoctor ✔ JAVA_HOME is set to: /Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home
info AppiumDoctor ✔ adb exists at: /Users/vz8zw5/Library/Android/sdk/platform-tools/adb
info AppiumDoctor ✔ android exists at: /Users/vz8zw5/Library/Android/sdk/tools/android
info AppiumDoctor ✔ emulator exists at: /Users/vz8zw5/Library/Android/sdk/tools/emulator
info AppiumDoctor ✔ Bin directory of $JAVA_HOME is set
info AppiumDoctor ### Diagnostic for necessary dependencies completed, no fix needed. ###
info AppiumDoctor
info AppiumDoctor ### Diagnostic for optional dependencies starting ###
WARN AppiumDoctor ✖ opencv4nodejs cannot be found.
WARN AppiumDoctor ✖ ffmpeg cannot be found
WARN AppiumDoctor ✖ mjpeg-consumer cannot be found.
WARN AppiumDoctor ✖ idb and idb_companion are not installed
WARN AppiumDoctor ✖ applesimutils cannot be found
WARN AppiumDoctor ✖ idevicelocation cannot be found
WARN AppiumDoctor ✖ ios-deploy cannot be found
WARN AppiumDoctor ✖ ios_webkit_debug_proxy cannot be found
WARN AppiumDoctor ✖ ifuse cannot be found
WARN AppiumDoctor ✖ bundletool.jar cannot be found
info AppiumDoctor ### Diagnostic for optional dependencies completed, 10 fixes possible. ###
info AppiumDoctor
info AppiumDoctor ### Optional Manual Fixes ###
info AppiumDoctor The configuration can install optionally. Please do the following manually:
WARN AppiumDoctor ➜ Why opencv4nodejs is needed and how to install it: https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/image-comparison.md
WARN AppiumDoctor ➜ ffmpeg is needed to record screen features. Please read https://www.ffmpeg.org/ to install it
WARN AppiumDoctor ➜ mjpeg-consumer module is required to use MJPEG-over-HTTP features. Please install it with 'npm i -g mjpeg-consumer'.
WARN AppiumDoctor ➜ Why idb is needed and how to install it: https://github.com/appium/appium-idb
WARN AppiumDoctor ➜ Why applesimutils is needed and how to install it: http://appium.io/docs/en/drivers/ios-xcuitest/
WARN AppiumDoctor ➜ idevicelocation is used to set geolocation for real device. Please read https://github.com/JonGabilondoAngulo/idevicelocation to install it
WARN AppiumDoctor ➜ ios-deploy is used to install iOS applications to real device. Please read http://appium.io/docs/en/drivers/ios-xcuitest-real-devices/ to install it
WARN AppiumDoctor ➜ ios_webkit_debug_proxy is used to proxy requests from Appium to MobileSafari running on real device. Please read https://github.com/google/ios-webkit-debug-proxy to install it
WARN AppiumDoctor ➜ ifuse is used to manage files/folders against a real device. Please read https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios/ios-xctest-file-movement.md to install it
WARN AppiumDoctor ➜ bundletool.jar is used to handle Android App Bundle. Please read http://appium.io/docs/en/writing-running-appium/android/android-appbundle/ to install it
info AppiumDoctor
info AppiumDoctor ###
info AppiumDoctor
info AppiumDoctor Bye! Run appium-doctor again when all manual fixes have been applied!
info AppiumDoctor

## Code To Reproduce Issue [ Good To Have ]
```java
        @Test
	public void manin1 () throws MalformedURLException
	{	
		
		DesiredCapabilities caps = new DesiredCapabilities();
		caps.setCapability("automationName", "XCUITest");
		caps.setCapability("noReset", "false");
		caps.setCapability("fullReset", "true");
		caps.setCapability("platformName", "iOS");
		caps.setCapability("platformVersion", "12.1");
		caps.setCapability("deviceName", "iPhone X");
		caps.setCapability(CapabilityType.BROWSER_NAME,"safari");
                URL url = new URL("http://127.0.0.1:4723/wd/hub");
		
		WebDriver driver = new AppiumDriver<MobileElement> (url,caps);
		driver.manage().timeouts().implicitlyWait(Constants.DEVICE_WAIT, TimeUnit.SECONDS);
		driver.manage().timeouts().setScriptTimeout(Constants.SYNC_WAIT, TimeUnit.SECONDS);
		driver.manage().timeouts().pageLoadTimeout(Constants.WAIT, TimeUnit.SECONDS);
		
		driver.get("http://www.google.com");
		driver.quit();
        }
```

**Comment by KazuCocoa** [comment]
Building `IntegrationApp.app` looks strange…
Did you open and update WebDriverAgent project before?

Uninstall, re-install Appium and remove data in `/Users/vz8zw5/Library/Developer/Xcode/DerivedData/` could help...

```
/Users/vz8zw5/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/Test-WebDriverAgentRunner-2019.07.22_17-54-01--0400.xcresult, NSLocalizedDescription=Failed to install or launch the test runner,
```

**Comment by aruvimal** [comment]
i have already tried but it is not working. 
Issue happening for both xcode simulator as well andriod emulator.  It is just invoking simulator/emulator but not launching the browser.

**Comment by KazuCocoa** [comment]
Can your environment build below command?
It is in your log.

```
xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -derivedDataPath /Users/vz8zw5/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy -destination id=F37B51B3-BB64-451F-A610-43ABADE495D4 IPHONEOS_DEPLOYMENT_TARGET=12.1 GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO
```


If it does not work, what about run below?

```
$ cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/
$ ./Scripts/bootstrap.sh

$ xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -derivedDataPath /Users/vz8zw5/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy -destination id=F37B51B3-BB64-451F-A610-43ABADE495D4 IPHONEOS_DEPLOYMENT_TARGET=12.1 GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO
```

If it worked, your CLI environment probably has an issue to resolve carthage command.

If you install your environment with `sudo`, it also could lead build errors as _Make sure you have not installed Node or Appium with sudo, otherwise you'll run into problems_ in http://appium.io/docs/en/about-appium/getting-started/

**Comment by mykola-mokhnach** [comment]
Closed as not an issue

**Comment by KazuCocoa** [comment]
I met the same issue when I changed some configurations in appium-webdriveragent and xcuites-driver directory.
I removed node_modules once and build again. Then this issue was fixed
