### ISSUE TITLE
UnknownError: An unknown server-side error occurred while processing the command. Original error: packageAndLaunchActivityFromManifest failed. 

### ISSUE THREAD

**Issue by itestevrythng** [appium/appium#12969]
## The problem

Unable to launch\install app to emulator device for the very 1st time.

## Environment

* Appium version (or git revision) that exhibits the issue:  1.14.0
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: win 10
* Node.js version (unless using Appium.app|exe):12.6.0
* Npm or Yarn package manager: 6.9.0
* Mobile platform/version under test: Andorid 6.0
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: appium from cmd

## Details

Eclipse error :

Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: packageAndLaunchActivityFromManifest failed. Original error: Could not find 'aapt.exe' in PATH. Please set the ANDROID_HOME or ANDROID_SDK_ROOT environment variables to the corect Android SDK root directory path.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
System info: host: 'DESKTOP-21U4G5L', ip: '192.168.0.23', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '12.0.1'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: packageAndLaunchActivityFromManifest failed. Original error: Could not find 'aapt.exe' in PATH. Please set the ANDROID_HOME or ANDROID_SDK_ROOT environment variables to the corect Android SDK root directory path.
    at getResponseForW3CError (C:\Users\anujb\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:826:9)
    at asyncHandler (C:\Users\anujb\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:447:37)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
System info: host: 'DESKTOP-21U4G5L', ip: '192.168.0.23', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '12.0.1'
Driver info: driver.version: AndroidDriver
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:208)
	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:217)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:323)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:37)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:86)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:96)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:94)
	at Bas.main(Bas.java:32)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:186)
	... 14 more
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: packageAndLaunchActivityFromManifest failed. Original error: Could not find 'aapt.exe' in PATH. Please set the ANDROID_HOME or ANDROID_SDK_ROOT environment variables to the corect Android SDK root directory path.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
System info: host: 'DESKTOP-21U4G5L', ip: '192.168.0.23', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '12.0.1'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: packageAndLaunchActivityFromManifest failed. Original error: Could not find 'aapt.exe' in PATH. Please set the ANDROID_HOME or ANDROID_SDK_ROOT environment variables to the corect Android SDK root directory path.
    at getResponseForW3CError (C:\Users\anujb\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:826:9)
    at asyncHandler (C:\Users\anujb\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:447:37)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	... 19 more

## Link to Appium logs

https://gist.github.com/itestevrythng/b041b106bba99878734260a3d76f3b31

## Code To Reproduce Issue [ Good To Have ]

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import org.openqa.selenium.remote.DesiredCapabilities;

import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.android.AndroidElement;
import io.appium.java_client.remote.AutomationName;
import io.appium.java_client.remote.MobileCapabilityType;

public class Bas {

	public static void main(String[] args) throws MalformedURLException {
		// TODO Auto-generated method stub

		//appium

		File f= new File("src");

		File fs=new File(f,"ApiDemos-debug.apk");

		DesiredCapabilities cap=new DesiredCapabilities();
		cap.setCapability(MobileCapabilityType.DEVICE_NAME,"AnAVD");
		cap.setCapability(MobileCapabilityType.AUTOMATION_NAME,"uiautomator2");
		cap.setCapability(MobileCapabilityType.APP,fs.getAbsolutePath());

		//conncetion to server create andorid driver 

		AndroidDriver<AndroidElement> driver= new AndroidDriver<>(new URL("http://127.0.0.1:4723/wd/hub"),cap);

	}

}

**Comment by KazuCocoa** [comment]
```
 Original error: Could not find 'aapt.exe' in PATH. Please set the ANDROID_HOME or ANDROID_SDK_ROOT environment variables to the corect Android SDK root directory path.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
System info: host: 'DESKTOP-21U4G5L', ip: '192.168.0.23', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '12.0.1'
```

Did your env have the `aapt.exe` in your PATH?
Usually, the path is `$ANDROID_HOME/build-tools/<build-tools-version>`

**Comment by itestevrythng** [comment]
@KazuCocoa 
Android_Home is set to "C:\Users\anujb\AppData\Local\Android\Sdk " 
and I have appended the PATH in system variables with "C:\Users\anujb\AppData\Local\Android\Sdk\build-tools\27.0.3"

![path](https://user-images.githubusercontent.com/23380912/61965030-47276080-af9d-11e9-8e80-778a9e3d1713.JPG)

**Comment by itestevrythng** [comment]
And , one more thing I want help on is, My ANDROID_HOME is set properly in the above ss you can see, But when I run appium-doctor in GIT bash or cmd  I get this error ..Screen shot below..
![Android_home](https://user-images.githubusercontent.com/23380912/61965991-91114600-af9f-11e9-81ee-40d14f38f107.JPG)

Please help me on this

**Comment by itestevrythng** [comment]
ANDORID_HOME 
![Capture1](https://user-images.githubusercontent.com/23380912/61966086-c9188900-af9f-11e9-9ab2-14a645ace19e.JPG)

**Comment by KazuCocoa** [comment]
mmm.

before, I got feedback if we set the pash as windows syntax, Appium works fine.
It is kindly node env tho.

```
$ cat ~/.config/fish/config.fish
# for Android SDK
set -x ANDROID_HOME C:\\Users\\0000910700\\AppData\\Local\\Android\\sdk # for appium-doctor
#set -x ANDROID_HOME /C/Users/0000910700/AppData/Local/Android/sdk
set -x PATH /c/Users/0000910700/AppData/Local/Android/sdk/platform-tools $PATH ^ /dev/null

# for JDK
set -x JAVA_HOME C:\\Program\ Files\\Java\\jdk1.8.0_131 # for appium-doctor
#set -x JAVA_HOME /C/Program\ Files/Java/jdk1.8.0_131
set -x PATH /C/Program\ Files/Java/jdk1.8.0_131/bin $PATH ^ /dev/null
```

**Comment by itestevrythng** [comment]
Thanks, will try this ...

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by itestevrythng** [comment]
Getting the below error, Please Help!!!
![image](https://user-images.githubusercontent.com/23380912/61995978-11e24780-b05d-11e9-8e05-2b7a50ab8358.png)

**Comment by KazuCocoa** [comment]
Did you check with android-doctor like https://github.com/appium/appium/issues/12969#issuecomment-515514715 and the ANDROID_HOME showed android root?

**Comment by mykola-mokhnach** [comment]
Closed as not an issue.

The problem lies in the local env setup and there is nothing to do there from Appium side.

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/java-client/blob/master/docs/environment.md

**Comment by Ravi9562** [comment]
Hello I am trying to work on Appium. But I am getting below error. I have set the path of JAVA_HOME, ANDROID_HOME and ADNROID_SDK as well. But still getting the same error. Can anyone help me in this regard.
![image](https://user-images.githubusercontent.com/40264556/158025954-51cd8c41-634b-4f5f-babc-9ba99a5d66e8.png)

Thanks in advance

**Comment by jlipps** [comment]
Looks like your JAVA_HOME is incorrect. It has two `bin`s in it.
