### ISSUE TITLE
Cannot run first appium test, got Please grant write permissions to this file or to its parent folder 

### ISSUE THREAD

**Issue by mrmourax** [appium/appium#12984]
## The problem

Hello. Trying to run my first appium test, but got an error that 
An unknown server-side error occurred while processing the command. Original error: The application at 'C:\Users\user\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk' is not writeable. Please grant write permissions to this file or to its parent folder 

I have such folder on my pc **C:\Users\user\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks**
but there is NO such a file **appium-uiautomator2-server-debug-androidTest.apk**
I have there a file with name **appium-uiautomator2-server-v3.7.0**.
Anyway I granted this folder to WRITE permission but the error still exists. Can you help me please?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.14.0
* Last Appium version that did not exhibit the issue (if applicable): 1.14.0
* Desktop OS/version used to run Appium: Windows 10, 64 bit
* Node.js version (unless using Appium.app|exe): 10.16.0
* Npm or Yarn package manager: 6.9.0
* Mobile platform/version under test: Android 9
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: The application at 'C:\Users\user\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk' is not writeable. Please grant write permissions to this file or to its parent folder 'C:\Users\user\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks' for the Appium process, so it could sign the application
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'DESKTOP-IOJ0BJF', ip: '192.168.0.100', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '10.0.2'
Driver info: driver.version: AppiumDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: The application at 'C:\Users\user\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk' is not writeable. Please grant write permissions to this file or to its parent folder 'C:\Users\user\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks' for the Appium process, so it could sign the application
    at getResponseForW3CError (C:\Users\user\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:826:9)
    at asyncHandler (C:\Users\user\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:447:37)
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'DESKTOP-IOJ0BJF', ip: '192.168.0.100', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '10.0.2'
Driver info: driver.version: AppiumDriver
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:208)
	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:217)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:84)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:94)
	at appiumtests.CalculatorTest.openCalculator(CalculatorTest.java:39)
	at appiumtests.CalculatorTest.main(CalculatorTest.java:20)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:186)
	... 12 more
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: The application at 'C:\Users\user\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk' is not writeable. Please grant write permissions to this file or to its parent folder 'C:\Users\user\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks' for the Appium process, so it could sign the application
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'DESKTOP-IOJ0BJF', ip: '192.168.0.100', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '10.0.2'
Driver info: driver.version: AppiumDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: The application at 'C:\Users\user\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk' is not writeable. Please grant write permissions to this file or to its parent folder 'C:\Users\user\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks' for the Appium process, so it could sign the application
    at getResponseForW3CError (C:\Users\user\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:826:9)
    at asyncHandler (C:\Users\user\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:447:37)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	... 17 more

## Code To Reproduce Issue [ Good To Have ]

package appiumtests;

import java.net.MalformedURLException;
import java.net.URL;

import org.openqa.selenium.remote.DesiredCapabilities;
import io.appium.java_client.AppiumDriver;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.MobileElement;

public class CalculatorTest {
	
	 //WebDriver driver;
	static AppiumDriver<MobileElement> driver;
	//AndroidDriver driver;

	public static void main(String[] args) throws MalformedURLException {
		// TODO Auto-generated method stub
		openCalculator();
	}
	
	public static void openCalculator() throws MalformedURLException {

		DesiredCapabilities cap = new DesiredCapabilities();
		cap.setCapability("deviceName", "Nokia 7.1");
		cap.setCapability("udid", "CTLGAP4892810013");
		cap.setCapability("platformName", "Android");
		cap.setCapability("version", "9");
		cap.setCapability("automationName", "uiautomator2");

		cap.setCapability("appPackage", "com.android.calculator2");
		cap.setCapability("appActivity", "com.android.calculator2.Calculator");
		
		//AndroidDriver driver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
		
		URL url = new URL("http://127.0.0.1:4723/wd/hub");
		driver = new AppiumDriver<MobileElement>(url, cap);
		System.out.println("Application started");
	}

}

**Comment by KazuCocoa** [comment]
I assume this happened when npm tried to resolve dependencies in `npm install`.
In general, npm gets uia2 servers like below in a part of `npm install -g appium`, but for example, the apk could be removed by security app etc.

```
$ ls /Users/kazu/.nodebrew/node/v10.16.0/lib/node_modules/appium/node_modules/appium-uiautomator2-server
LICENSE      README.md    apks         index.js     package.json
$ ls /Users/kazu/.nodebrew/node/v10.16.0/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/
appium-uiautomator2-server-debug-androidTest.apk appium-uiautomator2-server-v3.7.0.apk
```

Not sure the exact cause, but I got feedback some Windows users failed to get the apks correctly. (There were users who succeeded to download them correctly tho.)

As a workaround, you can build them on your local and move them properly.

```
$ git clone https://github.com/appium/appium-uiautomator2-server
$ cd appium-uiautomator2-server
$ git checkout v3.7.0
$ npm install && npm run build
# Then, apks will be in apks directory. Move them to `C:\Users\user\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\`
```

**Comment by mrmourax** [comment]
Not sure if I did all correct. I did get clone to my C:/ , then did CD, then did git checkout, then did npm install , then npm run build (got error here) and thene replace this folder appium-uiautomator2-server for a new one. And still got the same error message. May be some other ideas? I really need to setup appium, but on the Internet not much info.
![Capture](https://user-images.githubusercontent.com/37150816/62006258-ecca0380-b146-11e9-916e-d66ea14576be.JPG)

**Comment by KazuCocoa** [comment]
ah, on Windows, `./gradle` should be `gradlew.bat`.
You can run with `gradlew.bat` like:

```
gradlew.bat clean assembleServerDebug assembleServerDebugAndroidTest && npm run move-apks && npm run sign-apk
```

**Comment by mrmourax** [comment]
> ah, on Windows, `./gradle` should be `gradlew.bat`.
> You can run with `gradlew.bat` like:
> 
> ```
> gradlew.bat clean assembleServerDebug assembleServerDebugAndroidTest && npm run move-apks && npm run sign-apk
> ```

Same issue unfortunately :(
This is result of this command.
![Capture2](https://user-images.githubusercontent.com/37150816/62008089-dda28000-b15d-11e9-968b-bd42b38fff13.JPG)

**Comment by KazuCocoa** [comment]
You should convert https://github.com/appium/appium-uiautomator2-server/blob/master/package.json#L26-L35 to Windows command properly.

```
# Looks worked. Maybe the apks were in `app/build/outputs/apk/*`
$ gradlew.bat clean assembleServerDebug assembleServerDebugAndroidTest
# rm, makdir etc probably do not work. You should move all of apks in app/build/outputs/apk/* to /apk
$ rm -rf apks && mkdir -p apks && npm run move-server && npm run move-test
$ gulp sign-apk
```

It looks your `gradlew` command worked. So, maybe something happened on your env when npm gots dependencies from npm repository.
Anyway, after the above commands, please copy apks in `appium-uiautomator2-server/apks` to `C:\Users\user\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\`

**Comment by mrmourax** [comment]
> You should convert https://github.com/appium/appium-uiautomator2-server/blob/master/package.json#L26-L35 to Windows command properly.
> 
> ```
> # Looks worked. Maybe the apks were in `app/build/outputs/apk/*`
> $ gradlew.bat clean assembleServerDebug assembleServerDebugAndroidTest
> # rm, makdir etc probably do not work. You should move all of apks in app/build/outputs/apk/* to /apk
> $ rm -rf apks && mkdir -p apks && npm run move-server && npm run move-test
> $ gulp sign-apk
> ```
> 
> It looks your `gradlew` command worked. So, maybe something happened on your env when npm gots dependencies from npm repository.
> Anyway, after the above commands, please copy apks in `appium-uiautomator2-server/apks` to `C:\Users\user\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\`

The problem is that in my new folder appium-uiautomator2-server there is no folder apks.
Only this (screen)
![Capture3](https://user-images.githubusercontent.com/37150816/62010297-dab18a80-b171-11e9-9cb5-7620f06cd22a.JPG)

**Comment by KazuCocoa** [comment]
The `apkls` will be created by `mkdir -p apks`. If you did not create it by yourself with windows command like `mkdir -p apks` on mac, it is not there.
I also commented as _rm, makd ir etc probably do not work. You should move all of apks in app/build/outputs/apk/* to /apk_, you should

**Comment by mrmourax** [comment]
> The `apkls` will be created by `mkdir -p apks`. If you did not create it by yourself with windows command like `mkdir -p apks` on mac, it is not there.
> I also commented as _rm, makd ir etc probably do not work. You should move all of apks in app/build/outputs/apk/* to /apk_, you should

Is it possible that you can connect to me via Ammyy Admin for example and help with installation. I really can't understand what to do. I did with your steps ( I think ) but nothing good.

**Comment by mykola-mokhnach** [comment]
It might be that the file gets silently removed by some antivirus or similar software, which is running in background on your machine. Reinstall Appium and check the logs there. Perhaps, you simply should whitelist these apks.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
