### ISSUE TITLE
Failed to push a file for iOS real device after removing ifuse

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium#12983]
## The problem

After https://github.com/appium/appium-xcuitest-driver/pull/1015 , pushing a file to real device starts failing.

Error message: `Unexpected response PERMISSION_DENIED`

## Environment

* Appium version (or git revision) that exhibits the issue:  master
* Last Appium version that did not exhibit the issue (if applicable): 1.14.0
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe): 10.16.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: ios 12.2.1
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: cli

## Details

Simply, I did https://github.com/appium/ruby_lib_core/blob/99516950f88c123107f3ee94325a5f64f4985b1d/test/functional/ios/ios/device_test.rb#L149-L156 for real device.
It did pushing a file to `com.apple.Keynote` like `@@driver.push_file '@com.apple.Keynote:documents/higher.png', data`

- Appium log:
```
[HTTP] --> POST /wd/hub/session/3b96f4c3-34e9-4d0d-800e-746d9da644e0/appium/device/push_file
[HTTP] {"path":"@com.apple.Keynote:documents/higher.png","data":"iVBORw0KGgoAAAANSUhEUgAAAu4AAAU2CAYAAADK1zMGAAAAAXNSR0IArs4c6QAAABxpRE9UAAAAAgAAAAAAAAKbAAAAKAAAApsAAAKbAAH9bRJ2ye8AAEAASURBVHgB7N2Hl2ZFtQb8Meecc845ZxHJWXIYEYYZYFCSJBFEMQGCgCCCggQTigIKZkXC5AzivWL+7re+/+PWd35neJrD3Bl6mO6e7pfZvVatOm+dql279tm166l99qmeNWvWrFapZFA6UDpQOlA6UDpQOlA6UDpQOjDDdWDp0qWtUsmgdKB0oHSgdKB0oHSgdKB0oHRgZuvArMWLF7dKJYPSgdKB0oHSgdKB0oHSgdKB0oGZrQOzamc1s3dW9Xzq+ZQOlA6UDpQOlA6UDpQOlA7QgfK41xuHeuNSOlA6UDpQOlA6UDpQOlA6MAI6MGvJkiWtUsmgdKB0oHSgdKB0oHSgdKB0oHRgZutAhcrUx7n1cXLpQOlA6UDpQOlA6UDpQOnACOhAhcqMwGuR+lBkZn8oUs+nnk/pQOlA6UDpQOlA6cDm0IEJh8osW7asLV++vC1atKgtXLhwbLeGefcyCK9eBNXL1cv9mf5KBq/GNxxHeJePAv9D2bv2XDwLz0xadxx5TspdG//wWSrze6aPvfib2a/7ZsLzocuZz5nnmRN33HHHeudH+FYv15uao5F+zSmJzUEvuevhPFxfX+4PU+qEdmyuOrk3GXMY/2iiJSfLYV/Kw4N7rlMvY/VbOb4ie2WSOtpJ7kkrVqxoK1eu7Mu0CV39qq8MvaH8MubKyyaUDkyuDmROZl5nLmfuknfms2vzdaY8A7wM7Qy+8I9348o95X6rz65I7NB441APDXXlaGgzlM14NNZ3f8LAPYzFYGIug9NhHmKuMwB1pPUxNZPKjCeLBKEbZ8aahzCT+F2XF/LGL14XLF
[debug] [W3C (3b96f4c3)] Calling AppiumDriver.pushFile() with args: ["@com.apple.Keynote:documents/higher.png","iVBORw0KGgoAAAANSUhEUgAAAu4AAAU2CAYAAADK1zMGAAAAAXNSR0IArs4c6QAAABxpRE9UAAAAAgAAAAAAAAKbAAAAKAAAApsAAAKbAAH9bRJ2ye8AAEAASURBVHgB7N2Hl2ZFtQb8Meecc845ZxHJWXIYEYYZYFCSJBFEMQGCgCCCggQTigIKZkXC5AzivWL+7re+/+PWd35neJrD3Bl6mO6e7pfZvVatOm+dql279tm166l99qmeNWvWrFapZFA6UDpQOlA6UDpQOlA6UDpQOjDDdWDp0qWtUsmgdKB0oHSgdKB0oHSgdKB0oHRgZuvArMWLF7dKJYPSgdKB0oHSgdKB0oHSgdKB0oGZrQOzamc1s3dW9Xzq+ZQOlA6UDpQOlA6UDpQOlA7QgfK41xuHeuNSOlA6UDpQOlA6UDpQOlA6MAI6MGvJkiWtUsmgdKB0oHSgdKB0oHSgdKB0oHRgZutAhcrUx7n1cXLpQOlA6UDpQOlA6UDpQOnACOhAhcqMwGuR+lBkZn8oUs+nnk/pQOlA6UDpQOlA6cDm0IEJh8osW7asLV++vC1atKgtXLhwbLeGefcyCK9eBNXL1cv9mf5KBq/GNxxHeJePAv9D2bv2XDwLz0xadxx5TspdG//wWSrze6aPvfib2a/7ZsLzocuZz5nnmRN33HHHeudH+FYv15uao5F+zSmJzUEvuevhPFxfX+4PU+qEdmyuOrk3GXMY/2iiJSfLYV/Kw4N7rlMvY/VbOb4ie2WSOtpJ7kkrVqxoK1eu7Mu0CV39qq8MvaH8MubKyyaUDkyuDmROZl5nLmfuknfms2vzdaY8A7wM7Qy+8I9348o95X6rz65I7NB441APDXXlaGgzlM14NNZ3f8LAPYzFYGIug9NhHmKuMwB1pPUxNZPKjCeLBKEbZ8aahzCT+F2XF/LGL14XLFhwv8VsKH/jXF/SJvXk6GTc6q/bX/2eXKNY8...
[debug] [XCUITest] Executing command 'pushFile'
[debug] [XCUITest] Parsed container type: documents
[debug] [W3C (3b96f4c3)] Encountered internal error running command: Error: Unexpected response PERMISSION_DENIED
[debug] [W3C (3b96f4c3)]     at AfcService.checkStatus (/Users/kazu/GitHub/appium-xcuitest-driver/node_modules/appium-ios-device/lib/afc/index.js:191:13)
[debug] [W3C (3b96f4c3)]     at AfcService.checkStatus [as openFile] (/Users/kazu/GitHub/appium-xcuitest-driver/node_modules/appium-ios-device/lib/afc/index.js:98:12)
[HTTP] <-- POST /wd/hub/session/3b96f4c3-34e9-4d0d-800e-746d9da644e0/appium/device/push_file 500 1358 ms - 553
```

- Ruby log
```
[3] pry(#<AppiumLibCoreTest::Ios::DeviceTest>)> @@driver.push_file '@com.apple.Keynote:documents/higher.png', data
Selenium::WebDriver::Error::UnknownError: An unknown server-side error occurred while processing the command. Original error: Unexpected response PERMISSION_DENIED
from UnknownError: An unknown server-side error occurred while processing the command. Original error: Unexpected response PERMISSION_DENIED
```

## Link to Appium logs

The above

## Code To Reproduce Issue [ Good To Have ]

Should pass without error

**Comment by umutuzgur** [comment]
@KazuCocoa Will take a look at that. I didn't have an app to test the documents option

**Comment by KazuCocoa** [comment]
👍 
Apple keynote app has the ability. If you could get it on a real device, you can try this feature.
(Pull also can do like `driver.pull_folder '@com.apple.Keynote:documents/'`)
