### ISSUE TITLE
iOS: Unable to deploy ipa via ios-deploy (v1.14.0-beta.2)

### ISSUE THREAD

**Issue by mayureshshirodkar** [appium/appium#13011]
## The problem

On running the appium session, the ios-deploy of the ipa is getting timed out and fails to deploy.
Note that the ipa gets deployed successfully via ios-deploy -b <bundle> command.
ios-deploy version on my machine is 1.9.4, i tried reinstalling ios-deploy too.

## Environment

* Appium version (or git revision) that exhibits the issue: v1.14.0-beta.2
* Last Appium version that did not exhibit the issue (if applicable): v1.14.0
* Desktop OS/version used to run Appium: Mac OS 10.13.5
* Mobile platform/version under test: ios 12.3.1
* Real device or emulator/simulator: iPhone X

## Details

```
Installing '/var/folders/wp/fgdnh_qd7yg_myhbcb8n9c7nkssxpp/T/201971-67460-1m1i27.a9zf8/Payload/Navigate.app' on device with UUID '936c1853dc3b86942e3344c0bc9f978f8d749c62'...
2019-08-01 05:00:10:787 - [XCUITest] Error: Could not install app: 'operation timed out'
2019-08-01 05:00:10:788 - [XCUITest]     at IOSDeploy.install (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/ios-deploy.js:35:13)
2019-08-01 05:00:10:788 - [debug] [BaseDriver] Event 'newSessionStarted' logged at 1564635610788 (10:30:10 GMT+0530 (India Standard Time))
2019-08-01 05:00:10:788 - [debug] [W3C] Encountered internal error running command: Error: Could not install app: 'operation timed out'
2019-08-01 05:00:10:789 - [debug] [W3C]     at IOSDeploy.install (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/ios-deploy.js:35:13)
2019-08-01 05:00:10:790 - [HTTP] <-- POST /wd/hub/session 500 61696 ms - 585
```

## Link to Appium logs
https://gist.github.com/mayureshshirodkar/a9dcab07ca9b0caeb692d0cb90d2f964

**Comment by mayureshshirodkar** [comment]
duplicate of https://github.com/appium/appium/issues/12970
