### ISSUE TITLE
Running appium with android emulator on linux

### ISSUE THREAD

**Issue by navneetgarggate6** [appium/appium#13049]
## The problem

Running appium with android emulator on linux

## Environment

* Appium version (or git revision) that exhibits the issue: 1.14.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 1.13.0
* Node.js version (unless using Appium.app|exe): 12.6.0
* Npm or Yarn package manager: 6.9.0
* Mobile platform/version under test: Android
* Real device or emulator/simulator: emulator

## Details
Getting following error when i tried to start new session

An unknown server-side error occurred while processing the command. Original error: activity and pkg are required to start an application

## Link to Appium logs

[BaseDriver] Event 'newSessionStarted' logged at 1565255204478 (14:36:44 GMT+0530 (IST))
[MJSONWP] Encountered internal error running command: Error: activity and pkg are required to start an application
[MJSONWP]     at ADB. (/tmp/.mount_AppiumgxInPv/resources/app/node_modules/appium/node_modules/appium-adb/lib/tools/apk-utils.js:106:11)
[MJSONWP]     at Generator.next ()
[MJSONWP]     at asyncGeneratorStep (/tmp/.mount_AppiumgxInPv/resources/app/node_modules/appium/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
[MJSONWP]     at _next (/tmp/.mount_AppiumgxInPv/resources/app/node_modules/appium/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
[MJSONWP]     at /tmp/.mount_AppiumgxInPv/resources/app/node_modules/appium/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
[MJSONWP]     at new Promise (/tmp/.mount_AppiumgxInPv/resources/app/node_modules/appium/node_modules/core-js/modules/es6.promise.js:177:7)
[MJSONWP]     at ADB. (/tmp/.mount_AppiumgxInPv/resources/app/node_modules/appium/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12)
[MJSONWP]     at ADB.startApp (/tmp/.mount_AppiumgxInPv/resources/app/node_modules/appium/node_modules/appium-adb/lib/tools/apk-utils.js:104:1)
[MJSONWP]     at AndroidDriver.startApp (/tmp/.mount_AppiumgxInPv/resources/app/node_modules/appium/node_modules/appium-android-driver/lib/commands/general.js:234:18)
[MJSONWP]     at AndroidDriver.startAUT [as startAndroidSession] (/tmp/.mount_AppiumgxInPv/resources/app/node_modules/appium/node_modules/appium-android-driver/lib/driver.js:295:20)
[MJSONWP]     at process._tickCallback (internal/process/next_tick.js:68:7)
[HTTP] <-- POST /wd/hub/session 500 3449 ms - 190
[HTTP] 
[HTTP] --> DELETE /wd/hub/session
[HTTP] {}
[HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- DELETE /wd/hub/session 404 7 ms - 57
[HTTP]

**Comment by mykola-mokhnach** [comment]
It seems like the capabilities that you provide are missing some required fields, but I cannot say more without seeing the complete log

**Comment by navneetgarggate6** [comment]
[Appium] Welcome to Appium v1.13.0
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"BROWSER_NAME":"Android","appPackage":"de.migali.soft.apkinfo","appWaitActivity":".activities.*","appium-version":"1.6","deviceName":"Emulator","platformName":"Android","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"BROWSER_NAME":"Android","appPackage":"de.migali.soft.apkinfo","appWaitActivity":".activities.*","appium-version":"1.6","deviceName":"Emulator","platformName":"Android","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1565255875250 (14:47:55 GMT+0530 (IST))
[Appium] 
[Appium] ======================================================================
[Appium]   DEPRECATION WARNING:
[Appium] 
[Appium]   The 'automationName' capability was not provided in the desired 
[Appium]   capabilities for this Android session
[Appium] 
[Appium]   Setting 'automationName=UiAutomator1' by default and using the 
[Appium]   UiAutomator1 Driver
[Appium] 
[Appium]   The next minor version of Appium (1.14.x) will set 
[Appium]   'automationName=UiAutomator2' by default and use the UiAutomator2 
[Appium]   Driver
[Appium] 
[Appium]   The next major version of Appium (2.x) will **require** the 
[Appium]   'automationName' capability to be set for all sessions on all 
[Appium]   platforms
[Appium] 
[Appium]   If you are happy with 'UiAutomator1' and do not wish to upgrade 
[Appium]   Android drivers, please add 'automationName=UiAutomator1' to your 
[Appium]   desired capabilities
[Appium] 
[Appium]   For more information about drivers, please visit 
[Appium]   http://appium.io/docs/en/about-appium/intro/ and explore the 
[Appium]   'Drivers' menu
[Appium] 
[Appium] ======================================================================
[Appium] 
[Appium] Setting automation to 'UiAutomator1'. 
[Appium] Appium v1.13.0 creating new AndroidDriver (v4.15.1) session
[Appium] Capabilities:
[Appium]   BROWSER_NAME: Android
[Appium]   appPackage: de.migali.soft.apkinfo
[Appium]   appWaitActivity: .activities.*
[Appium]   appium-version: 1.6
[Appium]   deviceName: Emulator
[Appium]   platformName: Android
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true
[BaseDriver] Creating session with MJSONWP desired capabilities: {"BROWSER_NAME":"Android","...
[BaseDriver] The following capabilities were provided, but are not recognized by appium: BROWSER_NAME, appium-version, connectHardwareKeyboard.
[BaseDriver] Session created with session id: 24fbb6fa-c472-4db1-b03e-327d2b2bc3ed
[ADB] Found 15 'build-tools' folders under '/home/owner/Android/Sdk' (newest first):
[ADB]     /home/owner/Android/Sdk/build-tools/29.0.2
[ADB]     /home/owner/Android/Sdk/build-tools/29.0.1
[ADB]     /home/owner/Android/Sdk/build-tools/29.0.0
[ADB]     /home/owner/Android/Sdk/build-tools/28.0.3
[ADB]     /home/owner/Android/Sdk/build-tools/28.0.2
[ADB]     /home/owner/Android/Sdk/build-tools/28.0.1
[ADB]     /home/owner/Android/Sdk/build-tools/28.0.0
[ADB]     /home/owner/Android/Sdk/build-tools/27.0.3
[ADB]     /home/owner/Android/Sdk/build-tools/27.0.2
[ADB]     /home/owner/Android/Sdk/build-tools/27.0.1
[ADB]     /home/owner/Android/Sdk/build-tools/27.0.0
[ADB]     /home/owner/Android/Sdk/build-tools/26.0.3
[ADB]     /home/owner/Android/Sdk/build-tools/26.0.2
[ADB]     /home/owner/Android/Sdk/build-tools/26.0.1
[ADB]     /home/owner/Android/Sdk/build-tools/26.0.0
[ADB] Using 'adb' from '/home/owner/Android/Sdk/platform-tools/adb'
[AndroidDriver] Retrieving device list
[ADB] Trying to find a connected android device
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[AndroidDriver] Using device: emulator-5554
[ADB] Using 'adb' from '/home/owner/Android/Sdk/platform-tools/adb'
[ADB] Setting device id to emulator-5554
[ADB] Running '/home/owner/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell getprop ro.build.version.sdk'
[ADB] Current device property 'ro.build.version.sdk': 27
[ADB] Device API level: 27
[AndroidDriver] Consider setting 'automationName' capability to 'uiautomator2' on Android >= 6, since UIAutomator framework is not maintained anymore by the OS vendor.
[AndroidDriver] App file was not listed, instead we're going to run de.migali.soft.apkinfo directly on the device
[AndroidDriver] Checking whether package is present on the device
[ADB] Running '/home/owner/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell pm list packages de.migali.soft.apkinfo'
[AndroidDriver] Starting Android session
[ADB] Running '/home/owner/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 wait-for-device'
[ADB] Running '/home/owner/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell echo ping'
[AndroidDriver] Pushing settings apk to device...
[ADB] Getting install status for io.appium.settings
[ADB] Running '/home/owner/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package io.appium.settings'
[ADB] 'io.appium.settings' is installed
[ADB] Getting package info for 'io.appium.settings'
[ADB] Running '/home/owner/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package io.appium.settings'
[ADB] Using 'aapt' from '/home/owner/Android/Sdk/build-tools/29.0.2/aapt'
[ADB] The version name of the installed 'io.appium.settings' is greater or equal to the application version name ('2.14.0' >= '2.14.0')
[ADB] There is no need to install/upgrade '/tmp/.mount_Appium8IupV8/resources/app/node_modules/appium/node_modules/io.appium.settings/apks/settings_apk-debug.apk'
[ADB] Getting IDs of all 'io.appium.settings' processes
[ADB] Running '/home/owner/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell 'pgrep --help; echo $?''
[ADB] Running '/home/owner/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell pgrep -f io\\.appium\\.settings'
[AndroidDriver] io.appium.settings is already running. There is no need to reset its permissions.
[ADB] Running '/home/owner/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell appops set io.appium.settings android\:mock_location allow'
[Logcat] Starting logcat capture
[ADB] Getting device platform version
[ADB] Running '/home/owner/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell getprop ro.build.version.release'
[ADB] Current device property 'ro.build.version.release': 8.1.0
[ADB] Running '/home/owner/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell wm size'
[ADB] Running '/home/owner/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell getprop ro.product.model'

**Comment by mykola-mokhnach** [comment]
- UiAutomator1 backend should not be used for Android6+
- You must provide both activity and package capabilities if the application under test is already present on the device. Read https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for more details

**Comment by navneetgarggate6** [comment]
Still same issue

[Appium] Welcome to Appium v1.13.0
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"appPackage":"de.migali.soft.apkinfo","deviceName":"Emulator","platformName":"Android","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"appPackage":"de.migali.soft.apkinfo","deviceName":"Emulator","platformName":"Android","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1565257618793 (15:16:58 GMT+0530 (IST))
[Appium] 
[Appium] ======================================================================
[Appium]   DEPRECATION WARNING:
[Appium] 
[Appium]   The 'automationName' capability was not provided in the desired 
[Appium]   capabilities for this Android session
[Appium] 
[Appium]   Setting 'automationName=UiAutomator1' by default and using the 
[Appium]   UiAutomator1 Driver
[Appium] 
[Appium]   The next minor version of Appium (1.14.x) will set 
[Appium]   'automationName=UiAutomator2' by default and use the UiAutomator2 
[Appium]   Driver
[Appium] 
[Appium]   The next major version of Appium (2.x) will **require** the 
[Appium]   'automationName' capability to be set for all sessions on all 
[Appium]   platforms
[Appium] 
[Appium]   If you are happy with 'UiAutomator1' and do not wish to upgrade 
[Appium]   Android drivers, please add 'automationName=UiAutomator1' to your 
[Appium]   desired capabilities
[Appium] 
[Appium]   For more information about drivers, please visit 
[Appium]   http://appium.io/docs/en/about-appium/intro/ and explore the 
[Appium]   'Drivers' menu
[Appium] 
[Appium] ======================================================================
[Appium] 
[Appium] Setting automation to 'UiAutomator1'. 
[Appium] Appium v1.13.0 creating new AndroidDriver (v4.15.1) session
[Appium] Capabilities:
[Appium]   appPackage: de.migali.soft.apkinfo
[Appium]   deviceName: Emulator
[Appium]   platformName: Android
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true
[BaseDriver] Creating session with MJSONWP desired capabilities: {"appPackage":"de.migali.so...
[BaseDriver] The following capabilities were provided, but are not recognized by appium: connectHardwareKeyboard.
[BaseDriver] Session created with session id: ab3d18c8-b21f-4b37-9011-9ebc5bde0f2f
[ADB] Found 15 'build-tools' folders under '/home/owner/Android/Sdk' (newest first):
[ADB]     /home/owner/Android/Sdk/build-tools/29.0.2
[ADB]     /home/owner/Android/Sdk/build-tools/29.0.1
[ADB]     /home/owner/Android/Sdk/build-tools/29.0.0
[ADB]     /home/owner/Android/Sdk/build-tools/28.0.3
[ADB]     /home/owner/Android/Sdk/build-tools/28.0.2
[ADB]     /home/owner/Android/Sdk/build-tools/28.0.1
[ADB]     /home/owner/Android/Sdk/build-tools/28.0.0
[ADB]     /home/owner/Android/Sdk/build-tools/27.0.3
[ADB]     /home/owner/Android/Sdk/build-tools/27.0.2
[ADB]     /home/owner/Android/Sdk/build-tools/27.0.1
[ADB]     /home/owner/Android/Sdk/build-tools/27.0.0
[ADB]     /home/owner/Android/Sdk/build-tools/26.0.3
[ADB]     /home/owner/Android/Sdk/build-tools/26.0.2
[ADB]     /home/owner/Android/Sdk/build-tools/26.0.1
[ADB]     /home/owner/Android/Sdk/build-tools/26.0.0
[ADB] Using 'adb' from '/home/owner/Android/Sdk/platform-tools/adb'
[AndroidDriver] Retrieving device list
[ADB] Trying to find a connected android device
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[AndroidDriver] Using device: emulator-5554
[ADB] Using 'adb' from '/home/owner/Android/Sdk/platform-tools/adb'
[ADB] Setting device id to emulator-5554
[ADB] Running '/home/owner/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell getprop ro.build.version.sdk'
[ADB] Current device property 'ro.build.version.sdk': 27
[ADB] Device API level: 27
[AndroidDriver] Consider setting 'automationName' capability to 'uiautomator2' on Android >= 6, since UIAutomator framework is not maintained anymore by the OS vendor.
[AndroidDriver] App file was not listed, instead we're going to run de.migali.soft.apkinfo directly on the device
[AndroidDriver] Checking whether package is present on the device
[ADB] Running '/home/owner/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell pm list packages de.migali.soft.apkinfo'
[AndroidDriver] Starting Android session
[ADB] Running '/home/owner/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 wait-for-device'
[ADB] Running '/home/owner/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell echo ping'
[AndroidDriver] Pushing settings apk to device...
[ADB] Getting install status for io.appium.settings
[ADB] Running '/home/owner/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package io.appium.settings'
[ADB] 'io.appium.settings' is installed
[ADB] Getting package info for 'io.appium.settings'
[ADB] Running '/home/owner/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package io.appium.settings'
[ADB] Using 'aapt' from '/home/owner/Android/Sdk/build-tools/29.0.2/aapt'
[ADB] The version name of the installed 'io.appium.settings' is greater or equal to the application version name ('2.14.0' >= '2.14.0')
[ADB] There is no need to install/upgrade '/tmp/.mount_Appiumv1jiQa/resources/app/node_modules/appium/node_modules/io.appium.settings/apks/settings_apk-debug.apk'
[ADB] Getting IDs of all 'io.appium.settings' processes
[ADB] Running '/home/owner/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell 'pgrep --help; echo $?''
[ADB] Running '/home/owner/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell pgrep -f io\\.appium\\.settings'
[AndroidDriver] io.appium.settings is already running. There is no need to reset its permissions.
[ADB] Running '/home/owner/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell appops set io.appium.settings android\:mock_location allow'
[Logcat] Starting logcat capture
[ADB] Getting device platform version
[ADB] Running '/home/owner/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell getprop ro.build.version.release'
[ADB] Current device property 'ro.build.version.release': 8.1.0
[ADB] Running '/home/owner/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell wm size'
[ADB] Running '/home/owner/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell getprop ro.product.model'
[ADB] Current device property 'ro.product.model': Android SDK built for x86
[ADB] Running '/home/owner/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell getprop ro.product.manufacturer'
[ADB] Current device property 'ro.product.manufacturer': Google
[AndroidDriver] No app sent in, not parsing package/activity
[AndroidDriver] No app capability. Assuming it is already on the device
[ADB] Getting install status for de.migali.soft.apkinfo
[ADB] Running '/home/owner/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package de.migali.soft.apkinfo'
[ADB] 'de.migali.soft.apkinfo' is installed
[ADB] Running '/home/owner/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop de.migali.soft.apkinfo'
[ADB] Running '/home/owner/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell pm clear de.migali.soft.apkinfo'
[AndroidDriver] Performed fast reset on the installed 'de.migali.soft.apkinfo' application (stop and clear)
[AndroidBootstrap] Watching for bootstrap disconnect
[ADB] Forwarding system: 4724 to device: 4724
[ADB] Running '/home/owner/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 forward tcp\:4724 tcp\:4724'
[UiAutomator] Starting UiAutomator
[UiAutomator] Moving to state 'starting'
[UiAutomator] Parsing uiautomator jar
[UiAutomator] Found jar name: 'AppiumBootstrap.jar'
[ADB] Running '/home/owner/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell mkdir -p /data/local'
[ADB] Running '/home/owner/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 push /tmp/.mount_Appiumv1jiQa/resources/app/node_modules/appium/node_modules/appium-android-driver/bootstrap/bin/AppiumBootstrap.jar /data/local/tmp/'
[ADB] Attempting to kill all uiautomator processes
[ADB] Getting IDs of all 'uiautomator' processes
[ADB] Running '/home/owner/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell pgrep -f uiautomator'
[ADB] No 'uiautomator' process has been found
[UiAutomator] Starting UIAutomator
[ADB] Creating ADB subprocess with args: ["-P",5037,"-s","emulator-5554","shell","uiautomator","runtest","AppiumBootstrap.jar","-c","io.appium.android.bootstrap.Bootstrap","-e","pkg","de.migali.soft.apkinfo","-e","disableAndroidWatchers",false,"-e","acceptSslCerts",false]
[UiAutomator] Moving to state 'online'
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Registered crash watchers.
[AndroidBootstrap] Android bootstrap socket is now connected
[ADB] Running '/home/owner/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys window'
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Client connected
[AndroidDriver] Screen already unlocked, doing nothing
[AndroidDriver] Shutting down Android driver
[ADB] Running '/home/owner/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop de.migali.soft.apkinfo'
[ADB] Pressing the HOME button
[ADB] Running '/home/owner/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell input keyevent 3'
[AndroidBootstrap] Sending command to android: {"cmd":"shutdown"}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"shutdown"}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type SHUTDOWN
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":"OK, shutting down"}
[AndroidBootstrap] Received command result from bootstrap
[UiAutomator] Shutting down UiAutomator
[UiAutomator] Moving to state 'stopping'
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Closed client connection
[AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: numtests=1
[UiAutomator] UiAutomator shut down normally
[UiAutomator] Moving to state 'stopped'
[ADB] Attempting to kill all uiautomator processes
[ADB] Getting IDs of all 'uiautomator' processes
[ADB] Running '/home/owner/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell pgrep -f uiautomator'
[ADB] No 'uiautomator' process has been found
[UiAutomator] Moving to state 'stopped'
[Logcat] Stopping logcat capture
[ADB] Running '/home/owner/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop io.appium.unlock'
[AndroidDriver] Not cleaning generated files. Add `clearSystemFiles` capability if wanted.
[BaseDriver] Event 'newSessionStarted' logged at 1565257622767 (15:17:02 GMT+0530 (IST))
[MJSONWP] Encountered internal error running command: Error: activity and pkg are required to start an application
[MJSONWP]     at ADB. (/tmp/.mount_Appiumv1jiQa/resources/app/node_modules/appium/node_modules/appium-adb/lib/tools/apk-utils.js:106:11)
[MJSONWP]     at Generator.next ()
[MJSONWP]     at asyncGeneratorStep (/tmp/.mount_Appiumv1jiQa/resources/app/node_modules/appium/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
[MJSONWP]     at _next (/tmp/.mount_Appiumv1jiQa/resources/app/node_modules/appium/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
[MJSONWP]     at /tmp/.mount_Appiumv1jiQa/resources/app/node_modules/appium/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
[MJSONWP]     at new Promise (/tmp/.mount_Appiumv1jiQa/resources/app/node_modules/appium/node_modules/core-js/modules/es6.promise.js:177:7)
[MJSONWP]     at ADB. (/tmp/.mount_Appiumv1jiQa/resources/app/node_modules/appium/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12)
[MJSONWP]     at ADB.startApp (/tmp/.mount_Appiumv1jiQa/resources/app/node_modules/appium/node_modules/appium-adb/lib/tools/apk-utils.js:104:1)
[MJSONWP]     at AndroidDriver.startApp (/tmp/.mount_Appiumv1jiQa/resources/app/node_modules/appium/node_modules/appium-android-driver/lib/commands/general.js:234:18)
[MJSONWP]     at AndroidDriver.startAUT [as startAndroidSession] (/tmp/.mount_Appiumv1jiQa/resources/app/node_modules/appium/node_modules/appium-android-driver/lib/driver.js:295:20)
[MJSONWP]     at process._tickCallback (internal/process/next_tick.js:68:7)
[HTTP] <-- POST /wd/hub/session 500 4074 ms - 190
[HTTP] 
[HTTP] --> DELETE /wd/hub/session
[HTTP] {}
[HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- DELETE /wd/hub/session 404 6 ms - 57
[HTTP]

**Comment by mykola-mokhnach** [comment]
> Still same issue

Still no activity name in capabilities:

> [Appium] Capabilities:
> [Appium] appPackage: de.migali.soft.apkinfo
> [Appium] deviceName: Emulator
> [Appium] platformName: Android
> [Appium] newCommandTimeout: 0
> [Appium] connectHardwareKeyboard: true

**Comment by navneetgarggate6** [comment]
Sorry about previous log its working thanks for the help
