### ISSUE TITLE
Appium sometimes skip running the case

### ISSUE THREAD

**Issue by allenchann** [appium/appium#13050]
I was using appium 1.14.0 to run the test case.And i found that it will skip running some case.
I used iOS 12.4.
appium 1.14.0.
Here is some log when this issues occur.
```
[debug] [iOS] Attempting to set context to 'WEBVIEW_120'
[debug] [RemoteDebugger] Checking which communication style to use (non-Safari on platform version '12.4')
[debug] [RemoteDebugger] Platform version equal or higher than '12.2': true
[RemoteDebugger] Setting communication protocol: using full Web Inspector protocol communication
[debug] [RemoteDebugger] Connecting to WebKit socket: 'ws://localhost:9222/devtools/page/120'
[debug] [RemoteDebugger] WebKit debugger web socket connected to url: ws://localhost:9222/devtools/page/120
[debug] [RemoteDebugger] Starting to listen for JavaScript console
[debug] [RemoteDebugger] Sending WebKit data: {"method":"Console.enable","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true}}
[debug] [RemoteDebugger] Webkit response timeout: 10000
[debug] [RemoteDebugger] Received WebKit data: '{"method":"Target.targetCreated","params":{"targetInfo":{"targetId":"page-1","type":"page"}}}'
[debug] [RemoteDebugger] Found method 'Target.targetCreated' 
[debug] [RemoteDebugger] Target created: {"targetId":"page-1","type":"page"}
[debug] [RemoteDebugger] Received WebKit data: '{"error":{"code":-32601,"message":"'Console' domain was not found","data":[{"code":-32601,"message":"'Console' domain was not found"}]},"id":0}'
[debug] [RemoteDebugger] Found method 'Console.enable' 
[RemoteDebugger] Setting communication protocol: using Target-based communication
[debug] [RemoteDebugger] Sending WebKit data: {"method":"Target.sendMessageToTarget","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true,"message":{"method":"Console.enable","params":{}}}}
[debug] [RemoteDebugger] Webkit response timeout: 10000
[debug] [RemoteDebugger] Received WebKit data: '{"result":{},"id":1}'
[debug] [RemoteDebugger] Received receipt for message '1'
[debug] [RemoteDebugger] Received WebKit data: '{"method":"Target.dispatchMessageFromTarget","params":{"targetId":"page-1","message":"{\"result\":{},\"id\":1}"}}'
[debug] [RemoteDebugger] Found method 'Target.dispatchMessageFromTarget' for message '1'
[debug] [RemoteDebugger] Starting to listen for network events
[debug] [RemoteDebugger] Sending WebKit data: {"method":"Target.sendMessageToTarget","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true,"message":{"method":"Network.enable","params":{}}}}
[debug] [RemoteDebugger] Webkit response timeout: 10000
[debug] [iProxy] recv failed: Operation timed out
[debug] [WD Proxy] Matched '/session/c6d323ae-49a0-4ecf-8181-cb87d724bf09' to command name 'deleteSession'
[debug] [WD Proxy] Proxying [DELETE /session/c6d323ae-49a0-4ecf-8181-cb87d724bf09] to [DELETE http://localhost:8100/session/AD69D2E7-2A42-4B28-A8C0-75FB1AA4C69D] with no body
[debug] [WD Proxy] Got response with status 200: "{\n  \"value\" : {\n\n  },\n  \"sessionId\" : \"745A43E5-47C1-4F1C-AB59-9583537BAC70\",\n  \"status\" : 0\n}"
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down iproxy process (pid 72858)
[debug] [XCUITest] iproxy exited with code 'null'
[XCUITest] Shutting down xcodebuild process (pid 72859)
[debug] [XCUITest] Started background XCTest logs cleanup: find -E /private/var/folders -regex '.*/Session-WebDriverAgentRunner.*\.log$|.*/StandardOutputAndStandardError\.txt$' -type f -exec sh -c 'echo "" > "{}"' \;
[XCUITest] Cleaning test logs in '/Users/user/Library/Developer/Xcode/DerivedData/WebDriverAgent-bmnwvgncwcpxqgawgddnsvnqvyzy/Logs' folder
[debug] [iOS] Clearing log files
[debug] [iOS] Deleting '/Users/user/Library/Developer/Xcode/DerivedData/WebDriverAgent-bmnwvgncwcpxqgawgddnsvnqvyzy/Logs'. Freeing 68K.
[debug] [iOS] Finished clearing log files
[debug] [XCUITest] In a web session. Removing remote debugger
[debug] [RemoteDebugger] Disconnecting from WebKit remote debugger
[debug] [iOSLog] Stopping iOS log capture
[debug] [RemoteDebugger] WebKit remote debugger socket disconnected
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1565253169579 (16:32:49 GMT+0800 (Hong Kong Standard Time))
[debug] [MJSONWP] Encountered internal error running command: TimeoutError: operation timed out
[debug] [MJSONWP]     at afterTimeout (/Users/user/.jenkins/workspace/TNG 4.0-autotesting-iOS-DHC/node_modules/appium/node_modules/bluebird/js/release/timers.js:46:19)
[debug] [MJSONWP]     at Timeout.timeoutTimeout [as _onTimeout] (/Users/user/.jenkins/workspace/TNG 4.0-autotesting-iOS-DHC/node_modules/appium/node_modules/bluebird/js/release/timers.js:76:13)
[debug] [MJSONWP]     at ontimeout (timers.js:436:11)
[debug] [MJSONWP]     at tryOnTimeout (timers.js:300:5)
[debug] [MJSONWP]     at listOnTimeout (timers.js:263:5)
[debug] [MJSONWP]     at Timer.processTimers (timers.js:223:10)
[HTTP] <-- POST /wd/hub/session [31m500 43404 ms - 156
```
I found that once sending webkit data `Sending WebKit data: {"method":"Target.sendMessageToTarget","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true,"message":{"method":"Network.enable","params":{}}}}`failed.It will skip the whole case.

**Comment by imurchie** [comment]
Is there anything in the `ios-webkit-debug-proxy` logs?

**Comment by allenchann** [comment]
No.That is the whole log.And it cannot be reproducing manually.

**Comment by mykola-mokhnach** [comment]
@allenchann Try appium@beta

**Comment by allenchann** [comment]
Appium @beta cannot install app.In not occurs in iPhone X and iPhone XR.I think maybe it cause by the performance of the device.I finally resolve it by setting the `skipLogCapture` to `true`.

**Comment by mykola-mokhnach** [comment]
the application install issue in appium@beta is related to https://github.com/appium/appium/issues/12970

Make sure NodeJS is up to date
