### ISSUE TITLE
iOS: App ID gets disconnected during run (Encountered internal error running command: Error: appIdKey)

### ISSUE THREAD

**Issue by mayureshshirodkar** [appium/appium#13072]
## The problem

During an ongoing run the app gets disconnected resulting in a message saying 'Application 'PID:2073' disconnected. Removing from app dictionary.'

I have noticed this happening since appium-xcuitest 2.126.4 update.

After the app is reset via driver.reset_app(), the app gets attached back with a new PID and the execution continues from that point.

## Environment

* Appium version (or git revision) that exhibits the issue: v1.14.0-beta.2
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: Mac OS 10.14.5
* Node.js version (unless using Appium.app|exe): 10.16.2
* Npm or Yarn package manager: 6.9.0
* Mobile platform/version under test: 12.4 iOS
* Real device or emulator/simulator:iPhone X
* Appium CLI or Appium.app|exe:

## Details

Here are the logs:
```
2019-08-14 09:42:39:276 - [debug] [RemoteDebugger] Application 'PID:2073' disconnected. Removing from app dictionary.
2019-08-14 09:42:39:277 - [debug] [RemoteDebugger] Current app is PID:2073
2019-08-14 09:42:39:277 - [debug] [RemoteDebugger] No longer have app id. Attempting to find new one.
2019-08-14 09:42:43:143 - [HTTP] --> POST /wd/hub/session/b5464628-2dcf-4e88-aa33-98ff1d0c46b5/element
2019-08-14 09:42:43:143 - [HTTP] {"using":"xpath","value":"(//hi-checkbox)[1]"}
2019-08-14 09:42:43:143 - [debug] [W3C (b5464628)] Calling AppiumDriver.findElement() with args: ["xpath","(//hi-checkbox)[1]","b5464628-2dcf-4e88-aa33-98ff1d0c46b5"]
2019-08-14 09:42:43:143 - [debug] [XCUITest] Executing command 'findElement'
2019-08-14 09:42:43:144 - [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
2019-08-14 09:42:43:144 - [debug] [BaseDriver] Waiting up to 0 ms for condition
2019-08-14 09:42:43:144 - [debug] [RemoteDebugger] Executing atom 'find_element'
2019-08-14 09:42:43:144 - [debug] [RemoteDebugger] Executing 'find_element' atom in default context
2019-08-14 09:42:43:145 - [debug] [W3C (b5464628)] Encountered internal error running command: Error: appIdKey
2019-08-14 09:42:43:145 - [debug] [W3C (b5464628)]     at RemoteDebuggerRealDevice.execute (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-remote-debugger/lib/remote-debugger.js:609:13)
2019-08-14 09:42:43:145 - [debug] [W3C (b5464628)]     at RemoteDebuggerRealDevice.execute [as executeAtom] (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-remote-debugger/lib/remote-debugger.js:387:30)
2019-08-14 09:42:43:145 - [debug] [W3C (b5464628)]     at process._tickCallback (internal/process/next_tick.js:68:7)
2019-08-14 09:42:43:145 - [HTTP] <-- POST /wd/hub/session/b5464628-2dcf-4e88-aa33-98ff1d0c46b5/element 500 2 ms - 513
```

## Additional Details

**Gist :** https://gist.github.com/mayureshshirodkar/e177763131ac1e3621b030bcb05648db

**Comment by mayureshshirodkar** [comment]
@imurchie 
This issue is related to https://github.com/appium/appium/issues/11666
Where i get the same error as 'Application 'PID:' disconnected. Removing from app dictionary.'

**Comment by umutuzgur** [comment]
@mayureshshirodkar Could you try again with the latest beta? I added a fix for finding contexts. There is a chance it might fix this one as well

**Comment by mayureshshirodkar** [comment]
@umutuzgur Does appium-xcuitest@2.126.6 module contain this update?

**Comment by umutuzgur** [comment]
@mayureshshirodkar It should if you did reinstall the beta today. The fix is coming from a different package and appium-xcuitest-driver has loose versioning for that package. Meaning, if you installed appium-xcuitest-driver@2.126.6 yesterday, it shouldn't have it but if you installed it today, it should have it

**Comment by mayureshshirodkar** [comment]
Still facing the issue. Seems to be related to:
https://github.com/appium/appium/issues/13248

**Comment by mykola-mokhnach** [comment]
@mayureshshirodkar Is the problem above fixed in appium@beta?

**Comment by mayureshshirodkar** [comment]
@mykola-mokhnach Not sure if this is related to Appium directly but i get the below error.
The Appium instance crashed twice with similar error.

ERROR:
```
2019-10-07 13:50:01:820 - [HTTP] --> POST /wd/hub/session/cf620df2-c7b0-4fbe-880b-ac3676e1b601/element
2019-10-07 13:50:01:820 - [HTTP] {"using":"xpath","value":"//hi-icon[@kind='calender']/..//div/span[text()='Starts January 01, 2019']"}
2019-10-07 13:50:01:820 - [debug] [W3C (cf620df2)] Calling AppiumDriver.findElement() with args: ["xpath","//hi-icon[@kind='calender']/..//div/span[text()='Starts January 01, 2019']","cf620df2-c7b0-4fbe-880b-ac3676e1b601"]
2019-10-07 13:50:01:821 - [debug] [XCUITest] Executing command 'findElement'
2019-10-07 13:50:01:821 - [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
2019-10-07 13:50:01:821 - [debug] [BaseDriver] Waiting up to 0 ms for condition
2019-10-07 13:50:01:821 - [debug] [RemoteDebugger] Executing atom 'find_element'
2019-10-07 13:50:01:822 - [debug] [RemoteDebugger] Executing 'find_element' atom in default context
2019-10-07 13:50:01:822 - [debug] [RemoteDebugger] Sending javascript command: '(function(){return function(){var k=this;functi...'
2019-10-07 13:50:01:822 - [debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:5851', page '1' (id: 292)
2019-10-07 13:50:01:823 - [debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:5851', page '1' (id: 293)
2019-10-07 13:50:01:838 - [debug] [RemoteDebugger] Received response for message '292'
2019-10-07 13:50:01:839 - [debug] [RemoteDebugger] Handling message (id: '292')
2019-10-07 13:50:01:839 - [debug] [RemoteDebugger] Received data response from send (id: 292): '{"status":0,"value":null}'
2019-10-07 13:50:01:839 - [debug] [RemoteDebugger] Sending to Web Inspector took 17ms
2019-10-07 13:50:01:839 - [debug] [RemoteDebugger] Received result for atom 'find_element' execution: null
2019-10-07 13:50:01:839 - [debug] [RemoteDebugger] Received response for message '293'
2019-10-07 13:50:01:840 - [debug] [RemoteDebugger] Handling message (id: '293')
2019-10-07 13:50:01:840 - [debug] [RemoteDebugger] Received data response from send (id: 293): '1'
2019-10-07 13:50:01:840 - [debug] [W3C (cf620df2)] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
2019-10-07 13:50:01:840 - [debug] [W3C (cf620df2)]     at XCUITestDriver.findWebElementOrElements (/usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/lib/commands/web.js:184:13)
2019-10-07 13:50:01:841 - [HTTP] <-- POST /wd/hub/session/cf620df2-c7b0-4fbe-880b-ac3676e1b601/element 404 21 ms - 385
2019-10-07 13:50:01:841 - [HTTP] 
2019-10-07 13:50:02:346 - [HTTP] --> GET /wd/hub/session/cf620df2-c7b0-4fbe-880b-ac3676e1b601/screenshot
2019-10-07 13:50:02:347 - [HTTP] {}
2019-10-07 13:50:02:347 - [debug] [W3C (cf620df2)] Calling AppiumDriver.getScreenshot() with args: ["cf620df2-c7b0-4fbe-880b-ac3676e1b601"]
2019-10-07 13:50:02:347 - [debug] [XCUITest] Executing command 'getScreenshot'
2019-10-07 13:50:02:347 - [debug] [XCUITest] Taking screenshot with WDA
2019-10-07 13:50:02:349 - [debug] [WD Proxy] Matched '/screenshot' to command name 'getScreenshot'
2019-10-07 13:50:02:349 - [debug] [WD Proxy] Proxying [GET /screenshot] to [GET http://localhost:8100/session/EE30CF41-3E98-4479-A1DE-1339BB4F36AD/screenshot] with no body

<--- Last few GCs --->

[33786:0x102847000] 10928871 ms: Mark-sweep 1255.1 (1430.2) -> 1255.1 (1427.2) MB, 99.0 / 0.0 ms  (average mu = 0.292, current mu = 0.000) last resort GC in old space requested
[33786:0x102847000] 10928973 ms: Mark-sweep 1255.1 (1427.2) -> 1255.1 (1427.2) MB, 101.8 / 0.0 ms  (average mu = 0.171, current mu = 0.000) last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x2e45a84637b1 <JSObject>
    0: builtin exit frame: parse(this=0x2e45a8457d31 <Object map = 0x2e455ab842a9>,0x2e4563402201 <Very long string[1122739]>,0x2e45a8457d31 <Object map = 0x2e455ab842a9>)

    1: safeJsonParse [0x2e45724fa8c1] [/usr/local/lib/node_modules/appium/node_modules/appium-support/build/lib/util.js:118] [bytecode=0x2e45f21eefc9 offset=15](this=0x2e45724c0889 <Object map = 0x2e45e7f35a51>,obj=0x2e456340...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: 0x10003cff5 node::Abort() [/usr/local/bin/node]
 2: 0x10003d1ff node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 3: 0x1001b8265 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0x1005861c2 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
 5: 0x10058f6c4 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/local/bin/node]
 6: 0x100560f75 v8::internal::Factory::NewRawOneByteString(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 7: 0x10065787d v8::internal::Handle<v8::internal::String> v8::internal::JsonParser<true>::SlowScanJsonString<v8::internal::SeqOneByteString, unsigned char>(v8::internal::Handle<v8::internal::String>, int, int) [/usr/local/bin/node]
 8: 0x100656de4 v8::internal::JsonParser<true>::ParseJsonValue() [/usr/local/bin/node]
 9: 0x1006583cd v8::internal::JsonParser<true>::ParseJsonObject() [/usr/local/bin/node]
10: 0x10065712e v8::internal::JsonParser<true>::ParseJsonValue() [/usr/local/bin/node]
11: 0x100656961 v8::internal::JsonParser<true>::ParseJson() [/usr/local/bin/node]
12: 0x100656841 v8::internal::JsonParser<true>::Parse(v8::internal::Isolate*, v8::internal::Handle<v8::internal::String>, v8::internal::Handle<v8::internal::Object>) [/usr/local/bin/node]
13: 0x100279493 v8::internal::Builtin_Impl_JsonParse(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
14: 0x25991635bf9d 
15: 0x2599163118d5 
Abort trap: 6
```

**Comment by mykola-mokhnach** [comment]
This is OutOfMemory error. We would need to get the heap snapshot in the moment where the memory is quite full in order to investigate the problem

**Comment by mayureshshirodkar** [comment]
@mykola-mokhnach we ca close this issue, If i spot the above java script heap issue, i will open another issue for it, with some more info.

I have tried to increase the memory limit with
export NODE_OPTIONS=--max_old_space_size=4096
