### ISSUE TITLE
Could not find a driver for automationName 'XCUItest' and platformName 'iOS'

### ISSUE THREAD

**Issue by leeyc0704** [appium/appium#13070]
## The problem

On mac os ,i am a rookie,i could not find the solution from internet,who can help me? thanks

the error message below:
Encountered internal error running command: Error: Could not find a driver for automationName 'XCUItest' and platformName 'iOS'. Please check your desired capabilities.
my capabilities is
{
    "platformVersion":"10.3.1",
    "automationName":"XCUItest",
    "xcodeOrgId":"xxxxxxxxx",
    "xcodeSigningId":"iPhone Developer",
    "showXcodeLog":false,
    "wdaLocalPort":21132,
    "shouldLoadSnapshotWithAttributes":true,
    "useJSONSource":true,
    "usePrebuiltWDA":true,
    "clearSystemFiles":true,
    "sendKeyStrategy":"grouped",
    "connectHardwareKeyboard":true,
    "simpleIsVisibleCheck":true,
    "preventWDAAttachments":true,
    "waitForQuiescence":false,
    "waitForNoAnimationsActive":false,
    "noReset":true,
    "bundleId":"xxxxxx",
    "udid":"85d0849b62adbb0039759eb1aa07f79fbaxxxx",
    "platformName":"iOS",
    "deviceName":"“Administrator”的 iPhoneppl",
    "app":"/var/folders/r8/d00k_rzs551gc57nmh0np53w0000gn/T/25ae53e6-be43-11e9-bc8b-787b8ac79bc9/Payload/xxxx.app",
    "newCommandTimeout":900,
    "nativeWebScreenshot":true
}
## Environment

* Appium version 1.14.1

## Link to Appium logs

019-08-14 11:25:07:365 [Appium] Welcome to Appium v1.14.1
2019-08-14 11:25:07:367 [Appium] Non-default server args:
2019-08-14 11:25:07:367 [Appium]   port: 21127
2019-08-14 11:25:07:367 [Appium]   bootstrapPort: 21128
2019-08-14 11:25:07:368 [Appium]   sessionOverride: true
2019-08-14 11:25:07:368 [Appium]   logFile: /opt/wkdir/workspace/R-AUTO-APP/gjzq/log/appium-1563af9a-be43-11e9-bc8b-787b8ac79bc9.log
2019-08-14 11:25:07:368 [Appium]   logTimestamp: true
2019-08-14 11:25:07:368 [Appium]   localTimezone: true
2019-08-14 11:25:07:368 [Appium]   selendroidPort: 21129
2019-08-14 11:25:07:369 [Appium]   chromeDriverPort: 21130
2019-08-14 11:25:07:369 [Appium]   webkitDebugProxyPort: 21131
2019-08-14 11:25:07:450 [Appium] Appium REST http interface listener started on 0.0.0.0:21127
2019-08-14 11:25:08:374 [HTTP] --> GET /wd/hub/status
2019-08-14 11:25:08:374 [HTTP] {}
2019-08-14 11:25:08:376 [GENERIC] Calling AppiumDriver.getStatus() with args: []
2019-08-14 11:25:08:377 [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.14.1"}}
2019-08-14 11:25:08:381 [HTTP] <-- GET /wd/hub/status 200 6 ms - 57
2019-08-14 11:25:08:382 [HTTP] 
2019-08-14 11:25:12:482 [HTTP] --> POST /wd/hub/session
2019-08-14 11:25:12:482 [HTTP] {"desiredCapabilities":{"platformVersion":"10.3.1","automationName":"XCUItest","xcodeOrgId":"xxxx","xcodeSigningId":"iPhone Developer","showXcodeLog":false,"wdaLocalPort":21132,"shouldLoadSnapshotWithAttributes":true,"useJSONSource":true,"usePrebuiltWDA":true,"clearSystemFiles":true,"sendKeyStrategy":"grouped","connectHardwareKeyboard":true,"simpleIsVisibleCheck":true,"preventWDAAttachments":true,"waitForQuiescence":false,"waitForNoAnimationsActive":false,"noReset":true,"bundleId":"cn.com.gjzq.yjb.jy.3.EMULATE","udid":"85d0849b62adbb0039759eb1aa07f79fba4a1323","platformName":"iOS","deviceName":"“Administrator”的 iPhoneppl","app":"/var/folders/r8/d00k_rzs551gc57nmh0np53w0000gn/T/1ecfed14-be43-11e9-bc8b-787b8ac79bc9/Payload/xxxxEmulate).app","newCommandTimeout":900,"nativeWebScreenshot":true}}
2019-08-14 11:25:12:483 [MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformVersion":"10.3.1","automationName":"XCUItest","xcodeOrgId":"99G537LE8Y","xcodeSigningId":"iPhone Developer","showXcodeLog":false,"wdaLocalPort":21132,"shouldLoadSnapshotWithAttributes":true,"useJSONSource":true,"usePrebuiltWDA":true,"clearSystemFiles":true,"sendKeyStrategy":"grouped","connectHardwareKeyboard":true,"simpleIsVisibleCheck":true,"preventWDAAttachments":true,"waitForQuiescence":false,"waitForNoAnimationsActive":false,"noReset":true,"bundleId":"xxxxxEMULATE","udid":"85d0849b62adbb0039759eb1aa07f79fba4a1323","platformName":"iOS","deviceName":"“Administrator”的 iPhoneppl","app":"/var/folders/r8/d00k_rzs551gc57nmh0np53w0000gn/T/1ecfed14-be43-11e9-bc8b-787b8ac79bc9/Payload/YJBClient(Emulate).app","newCommandTimeout":900,"nativeWebScreenshot":true},null,null]
2019-08-14 11:25:12:483 [BaseDriver] Event 'newSessionRequested' logged at 1565753112483 (11:25:12 GMT+0800 (China Standard Time))
2019-08-14 11:25:13:842 [BaseDriver] Event 'newSessionStarted' logged at 1565753113841 (11:25:13 GMT+0800 (China Standard Time))
2019-08-14 11:25:13:895 [MJSONWP] Encountered internal error running command: Error: Could not find a driver for automationName 'XCUItest' and platformName 'iOS'. Please check your desired capabilities.
2019-08-14 11:25:13:895 [MJSONWP]     at AppiumDriver.getDriverAndVersionForCaps (/usr/local/lib/node_modules/appium/lib/appium.js:233:11)
2019-08-14 11:25:13:895 [MJSONWP]     at AppiumDriver.getDriverAndVersionForCaps [as createSession] (/usr/local/lib/node_modules/appium/lib/appium.js:309:66)
2019-08-14 11:25:13:895 [MJSONWP]     at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/node_modules/_appium-base-driver@3.20.1@appium-base-driver/lib/basedriver/driver.js:377:19)
2019-08-14 11:25:13:896 [MJSONWP]     at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/lib/appium.js:491:26)
2019-08-14 11:25:13:896 [MJSONWP]     at executeCommand (/usr/local/lib/node_modules/appium/node_modules/_appium-base-driver@3.20.1@appium-base-driver/lib/protocol/protocol.js:285:34)
2019-08-14 11:25:13:896 [MJSONWP]     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/_appium-base-driver@3.20.1@appium-base-driver/lib/protocol/protocol.js:410:15)
2019-08-14 11:25:13:896 [MJSONWP]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/_express@4.17.1@express/lib/router/layer.js:95:5)
2019-08-14 11:25:13:896 [MJSONWP]     at next (/usr/local/lib/node_modules/appium/node_modules/_express@4.17.1@express/lib/router/route.js:137:13)
2019-08-14 11:25:13:896 [MJSONWP]     at Route.dispatch (/usr/local/lib/node_modules/appium/node_modules/_express@4.17.1@express/lib/router/route.js:112:3)
2019-08-14 11:25:13:897 [MJSONWP]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/_express@4.17.1@express/lib/router/layer.js:95:5)
2019-08-14 11:25:13:897 [MJSONWP]     at /usr/local/lib/node_modules/appium/node_modules/_express@4.17.1@express/lib/router/index.js:281:22
2019-08-14 11:25:13:897 [MJSONWP]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/_express@4.17.1@express/lib/router/index.js:335:12)
2019-08-14 11:25:13:897 [MJSONWP]     at next (/usr/local/lib/node_modules/appium/node_modules/_express@4.17.1@express/lib/router/index.js:275:10)
2019-08-14 11:25:13:897 [MJSONWP]     at logger (/usr/local/lib/node_modules/appium/node_modules/_morgan@1.9.1@morgan/index.js:144:5)
2019-08-14 11:25:13:897 [MJSONWP]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/_express@4.17.1@express/lib/router/layer.js:95:5)
2019-08-14 11:25:13:897 [MJSONWP]     at trim_prefix (/usr/local/lib/node_modules/appium/node_modules/_express@4.17.1@express/lib/router/index.js:317:13)
2019-08-14 11:25:13:897 [MJSONWP]     at /usr/local/lib/node_modules/appium/node_modules/_express@4.17.1@express/lib/router/index.js:284:7
2019-08-14 11:25:13:898 [MJSONWP]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/_express@4.17.1@express/lib/router/index.js:335:12)
2019-08-14 11:25:13:898 [MJSONWP]     at next (/usr/local/lib/node_modules/appium/node_modules/_express@4.17.1@express/lib/router/index.js:275:10)
2019-08-14 11:25:13:898 [MJSONWP]     at /usr/local/lib/node_modules/appium/node_modules/_body-parser@1.19.0@body-parser/lib/read.js:130:5
2019-08-14 11:25:13:898 [MJSONWP]     at invokeCallback (/usr/local/lib/node_modules/appium/node_modules/_raw-body@2.4.0@raw-body/index.js:224:16)
2019-08-14 11:25:13:898 [MJSONWP]     at done (/usr/local/lib/node_modules/appium/node_modules/_raw-body@2.4.0@raw-body/index.js:213:7)
2019-08-14 11:25:13:900 [HTTP] <-- POST /wd/hub/session 500 1417 ms - 254

**Comment by mykola-mokhnach** [comment]
This might be happening if appium installation is corrupted, so it cannot dynamically load the `appium-xcuitest-driver` package. Try to reinstall the server or try on another machine

**Comment by leeyc0704** [comment]
perhaps i know de resason,i delete the webdriveragent project on path usr/local/lib/node_modules/appium/node_modules/_appium-xcuitest-driver@2.126.4@appium-xcuitest-driver/node_modules/appium-webdriveragent/ and use my own,recover it the proplem resolve

**Comment by klingham** [comment]
@leeyc0704 I am facing the same issue and followed the above steps mentioned, but no luck. Can you please help? I tried reinstalling and setting up appium from the start, but get the same error when trying to start an iOS session on Appium. Any help in this matter will be appreciated, Thanks!!!!

**Comment by sandeepmosali23** [comment]
@klingham  Deleting Appium and re-installing fixed issue for me

**Comment by luisxiaomai** [comment]
I met the same issue when I want to upgrade to appium 1.17.0 and xcode 11.3.1. 
I used `npm uninstall -g appium` and then `npm install -g appium` can not solved this issue. Please guide how to fix this issue? @mykola-mokhnach

**Comment by luisxiaomai** [comment]
uninstall node and reinstall solved this problem

**Comment by tvelev92** [comment]
Im still running into this issue

**Comment by AyushGarg1993** [comment]
Restarting the appium desktop client did solve my problem.

**Comment by hnkhuy** [comment]
I have the same trouble with start Appium Desktop Inspector. I also try all way above like restart Appium desktop, reinstall appium-xcuitest-driver...After all, sound stupid but restart the computer(mine is Macbook) works for me every time -_-

**Comment by youran1024** [comment]
> I have the same trouble with starting Appium Desktop Inspector. I also try all way above like restart Appium desktop, reinstall appium-xcuitest-driver...After all, sound stupid but restart the computer(mine is Macbook) works for me every time -_-

it is very useful for me ~

**Comment by pauline-swth** [comment]
Hello, 

I am seeing this issue when trying to execute an automation test using Appium and Cucumber framework:

org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Could not load a driver for automationName 'XCuiTest' and platformName 'ios'. Please verify your Appium installation
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Pauline-Mac.local', ip: 'fe80:0:0:0:1c81:5a5f:564:50af%en0', os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '12.6.1', java.version: '11.0.16'
Driver info: driver.version: IOSDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not load a driver for automationName 'XCuiTest' and platformName 'ios'. Please verify your Appium installation
    at getResponseForW3CError (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)
    at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:380:37)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Pauline-Mac.local', ip: 'fe80:0:0:0:1c81:5a5f:564:50af%en0', os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '12.6.1', java.version: '11.0.16'
Driver info: driver.version: IOSDriver

	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:208)
	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:217)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:336)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:37)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:88)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:98)
	at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:90)
	at com.qa.utils.DriverManager.initializeDriver(DriverManager.java:39)
	at com.qa.runners.RunnerBase.setUpClass(RunnerBase.java:64)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
	at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
	at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:186)
	... 36 more
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not load a driver for automationName 'XCuiTest' and platformName 'ios'. Please verify your Appium installation
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Pauline-Mac.local', ip: 'fe80:0:0:0:1c81:5a5f:564:50af%en0', os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '12.6.1', java.version: '11.0.16'
Driver info: driver.version: IOSDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not load a driver for automationName 'XCuiTest' and platformName 'ios'. Please verify your Appium installation
    at getResponseForW3CError (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)
    at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:380:37)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	... 41 more

[Utils] [ERROR] [Error] java.lang.NullPointerException
	at com.qa.runners.RunnerBase.scenarios(RunnerBase.java:76)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:77)
	at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:46)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:146)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:798)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:740)
	at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:59)
	at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:38)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:791)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by monilj** [comment]
I was also facing same issue, reinstalling Appium desktop resolved this issue temporary for me. It occurred even after reinstalling.
In that case I installed appium server using npm using `npm install -g appium` and using that appium server. It is not giving me any error while execution
