### ISSUE TITLE
Appium Won't Switch to Webview Because setContext is not a function

### ISSUE THREAD

**Issue by awhisler** [appium/appium#13078]
## The problem

I am trying to switch to the webview as my mobile app is some react-native and some react in a native wrapper. I can use getContexts() just fine but when I try to use setContext(contexts[1]) it says it is not a function

## Environment
* Appium version (or git revision) that exhibits the issue: 1.13.0
* Node.js version (unless using Appium.app|exe): 12.6.0
* Npm or Yarn package manager: 6.9.0
* Mobile platform/version under test: 12.4
* Real device or emulator/simulator: iOS Simulator iPhone 8
* Framework: webdriverio

## Details
let contexts = await driver.getContexts() returns [ 'NATIVE_APP', 'WEBVIEW_16604.4' ]
let webview = await driver.setContext(contexts[1]) says "TypeError: driver.setContext is not a function"

## Link to Appium logs

{
  matcherName: '',
  passed: false,
  expected: '',
  actual: '',
  error: TypeError: driver.setContext is not a function
}
[0-0] Error in "undefined"
TypeError: driver.setContext is not a function

## Code To Reproduce Issue

let contexts = await driver.getContexts()
console.log(await contexts)
let webview = await driver.setContext(contexts[1])

**Comment by imurchie** [comment]
The function is `switchContext`. https://webdriver.io/docs/api/mjsonwp.html#switchcontext

**Comment by awhisler** [comment]
@imurchie THANK YOU SO MUCH!!!!!!

**Comment by awhisler** [comment]
@imurchie I am now getting this error: 

`ERROR webdriver: Request failed due to unknown error: An unknown server-side error occurred while processing the command. Original error: No targets found, unable to communicate with device
    at getErrorFromResponseBody (/Users/ali.whisler/nutrien-gfa/node_modules/webdriver/build/utils.js:371:10)
    at Request._callback (/Users/ali.whisler/nutrien-gfa/node_modules/webdriver/build/request.js:120:64)
    at Request.self.callback (/Users/ali.whisler/nutrien-gfa/node_modules/request/request.js:185:22)
    at Request.emit (events.js:203:13)
    at Request.EventEmitter.emit (domain.js:471:20)
    at Request.<anonymous> (/Users/ali.whisler/nutrien-gfa/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:203:13)
    at Request.EventEmitter.emit (domain.js:471:20)
    at IncomingMessage.<anonymous> (/Users/ali.whisler/nutrien-gfa/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:291:20)
[0-0] {
  matcherName: '',
  passed: false,
  expected: '',
  actual: '',
  error: unknown error: An unknown server-side error occurred while processing the command. Original error: No targets found, unable to communicate with device
      at getErrorFromResponseBody (/Users/ali.whisler/nutrien-gfa/node_modules/webdriver/build/utils.js:371:10)
      at Request._callback (/Users/ali.whisler/nutrien-gfa/node_modules/webdriver/build/request.js:120:64)
      at Request.self.callback (/Users/ali.whisler/nutrien-gfa/node_modules/request/request.js:185:22)
      at Request.emit (events.js:203:13)
      at Request.EventEmitter.emit (domain.js:471:20)
      at Request.<anonymous> (/Users/ali.whisler/nutrien-gfa/node_modules/request/request.js:1161:10)
      at Request.emit (events.js:203:13)
      at Request.EventEmitter.emit (domain.js:471:20)
      at IncomingMessage.<anonymous> (/Users/ali.whisler/nutrien-gfa/node_modules/request/request.js:1083:12)
      at Object.onceWrapper (events.js:291:20) {
    name: 'unknown error'
  }
}
[0-0] Error in "undefined"
unknown error: An unknown server-side error occurred while processing the command. Original error: No targets found, unable to communicate with device`
