### ISSUE TITLE
switchingContext throws unknown server-side error

### ISSUE THREAD

**Issue by awhisler-nutrien** [appium/appium#13084]
## The problem

switchingContext throws unknown server-side error

## Environment
* Appium version (or git revision) that exhibits the issue: 1.13.0
* Node.js version (unless using Appium.app|exe): 12.6.0
* Npm or Yarn package manager: 6.9.0
* Mobile platform/version under test: 12.4
* Real device or emulator/simulator: iOS Simulator iPhone 8
* Automation Framework: webdriverio
* Development Framework: react-native (native) / react (web)

## Details

let contexts = await driver.getContexts() returns [ 'NATIVE_APP', 'WEBVIEW_16604.4' ]
let webview = await driver.switchContext(contexts[1]) FAILS

You can see that it does change to the webview though

`[0-0] 2019-08-15T19:59:51.676Z INFO webdriver: COMMAND getContexts()
[0-0] 2019-08-15T19:59:51.678Z INFO webdriver: [GET] http://127.0.0.1:4723/wd/hub/session/e45805b3-ca5b-40d2-a934-8cb7976762e6/contexts
[0-0] 2019-08-15T19:59:51.755Z INFO webdriver: RESULT [ 'NATIVE_APP', 'WEBVIEW_80692.4' ]
[0-0] 2019-08-15T19:59:51.756Z INFO webdriver: COMMAND switchContext("WEBVIEW_80692.4")
[0-0] 2019-08-15T19:59:51.756Z INFO webdriver: [POST] http://127.0.0.1:4723/wd/hub/session/e45805b3-ca5b-40d2-a934-8cb7976762e6/context
[0-0] 2019-08-15T19:59:51.756Z INFO webdriver: DATA { name: 'WEBVIEW_80692.4' }
[0-0] 2019-08-15T20:00:00.851Z WARN webdriver: Request failed due to An unknown server-side error occurred while processing the command. Original error: No targets found, unable to communicate with device
[0-0] 2019-08-15T20:00:00.851Z INFO webdriver: Retrying 1/3
[0-0] 2019-08-15T20:00:00.852Z INFO webdriver: [POST] http://127.0.0.1:4723/wd/hub/session/e45805b3-ca5b-40d2-a934-8cb7976762e6/context
[0-0] 2019-08-15T20:00:00.852Z INFO webdriver: DATA { name: 'WEBVIEW_80692.4' }
[0-0] 2019-08-15T20:00:09.889Z WARN webdriver: Request failed due to An unknown server-side error occurred while processing the command. Original error: No targets found, unable to communicate with device
[0-0] 2019-08-15T20:00:09.890Z INFO webdriver: Retrying 2/3
2019-08-15T20:00:09.890Z INFO webdriver: [POST] http://127.0.0.1:4723/wd/hub/session/e45805b3-ca5b-40d2-a934-8cb7976762e6/context
[0-0] 2019-08-15T20:00:09.890Z INFO webdriver: DATA { name: 'WEBVIEW_80692.4' }
[0-0] 2019-08-15T20:00:18.916Z WARN webdriver: Request failed due to An unknown server-side error occurred while processing the command. Original error: No targets found, unable to communicate with device
[0-0] 2019-08-15T20:00:18.916Z INFO webdriver: Retrying 3/3
[0-0] 2019-08-15T20:00:18.916Z INFO webdriver: [POST] http://127.0.0.1:4723/wd/hub/session/e45805b3-ca5b-40d2-a934-8cb7976762e6/context
[0-0] 2019-08-15T20:00:18.916Z INFO webdriver: DATA { name: 'WEBVIEW_80692.4' }
[0-0] 2019-08-15T20:00:27.947Z ERROR webdriver: Request failed due to unknown error: An unknown server-side error occurred while processing the command. Original error: No targets found, unable to communicate with device
    at getErrorFromResponseBody (node_modules/webdriver/build/utils.js:371:10)
    at Request._callback (node_modules/webdriver/build/request.js:120:64)
    at Request.self.callback (node_modules/request/request.js:185:22)
    at Request.emit (events.js:203:13)
    at Request.EventEmitter.emit (domain.js:471:20)
    at Request.<anonymous> (node_modules/request/request.js:1161:10)
    at Request.emit (events.js:203:13)
    at Request.EventEmitter.emit (domain.js:471:20)
    at IncomingMessage.<anonymous> (node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:291:20)
[0-0] {
  matcherName: '',
  passed: false,
  expected: '',
  actual: '',
  error: unknown error: An unknown server-side error occurred while processing the command. Original error: No targets found, unable to communicate with device
      at getErrorFromResponseBody (node_modules/webdriver/build/utils.js:371:10)
      at Request._callback (/node_modules/webdriver/build/request.js:120:64)
      at Request.self.callback (node_modules/request/request.js:185:22)
      at Request.emit (events.js:203:13)
      at Request.EventEmitter.emit (domain.js:471:20)
      at Request.<anonymous> (node_modules/request/request.js:1161:10)
      at Request.emit (events.js:203:13)
      at Request.EventEmitter.emit (domain.js:471:20)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1083:12)
      at Object.onceWrapper (events.js:291:20) {
    name: 'unknown error'
  }
}
[0-0] Error in "undefined"
unknown error: An unknown server-side error occurred while processing the command. Original error: No targets found, unable to communicate with device`

## Code To Reproduce Issue
let contexts = await driver.getContexts()//get list of available views. Returns array: ["NATIVE_APP","WEBVIEW_1"]
await driver.switchContext(contexts[1])//switches to WEBVIEW

**Comment by mykola-mokhnach** [comment]
Please try appium@beta

**Comment by mykola-mokhnach** [comment]
Closed as inactive
