### ISSUE TITLE
Unfortunately, io.appium.uiautomator2.server has stopped running?

### ISSUE THREAD

**Issue by dtboy1995** [appium/appium#13138]
## The problem

Very common running appium programs can cause such errors,

sometimes such error
```log
Error: connect ECONNREFUSED 127.0.0.1:4723
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
```

sometimes such error
```log
unknown error: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up
```

/data/system/dropbox log

```log
at /data/system/dropbox/data_app_crash@1566905885646.txt                      <
Process: io.appium.uiautomator2.server
Flags: 0x88be46
Package: io.appium.uiautomator2.server v33 (3.7.0)
Build: Android/sdk_phone_x86/generic_x86:5.1.1/LMY48X/4174727:userdebug/test-keys

java.lang.IllegalStateException: UiAutomation not connected!
        at android.app.UiAutomation.throwIfNotConnectedLocked(UiAutomation.java:914)
        at android.app.UiAutomation.disconnect(UiAutomation.java:236)
        at android.app.Instrumentation.finish(Instrumentation.java:198)
        at androidx.test.runner.MonitoringInstrumentation.finish(MonitoringInstrumentation.java:358)
        at androidx.test.runner.AndroidJUnitRunner.finish(AndroidJUnitRunner.java:408)
        at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:397)
        at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1853)
```
```log
Process: io.appium.uiautomator2.server
Flags: 0xa8be46
Package: io.appium.uiautomator2.server v33 (3.7.0)
Build: Android/sdk_phone_x86/generic_x86:5.1.1/LMY48X/4174727:userdebug/test-keys

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Android/sdk_phone_x86/generic_x86:5.1.1/LMY48X/4174727:userdebug/test-keys'
Revision: '0'
ABI: 'x86'
pid: 3902, tid: 4036, name: nioEventLoopGro  >>> io.appium.uiautomator2.server <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: 'art/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: illegal start byte 0xf0'
    eax 00000000  ebx 00000f3e  ecx 00000fc4  edx 00000006
    esi a2413db8  edi 0000000b
    xcs 00000073  xds 0000007b  xes 0000007b  xfs 000000af  xss 0000007b
    eip b74d8326  ebp 00000fc4  esp a2412690  flags 00200282

backtrace:
    #00 pc 00075326  /system/lib/libc.so (tgkill+22)
    #01 pc 0002217b  /system/lib/libc.so (pthread_kill+155)
    #02 pc 000239f4  /system/lib/libc.so (raise+36)
    #03 pc 0001bdf4  /system/lib/libc.so (abort+84)
    #04 pc 00377f56  /system/lib/libart.so (art::Runtime::Abort()+294)
    #05 pc 000ec704  /system/lib/libart.so (art::LogMessage::~LogMessage()+1876)
    #06 pc 00102c53  /system/lib/libart.so (art::JniAbort(char const*, char const*)+1683)
    #07 pc 0010359c  /system/lib/libart.so (art::JniAbortF(char const*, char const*, ...)+108)
    #08 pc 0010827e  /system/lib/libart.so (_ZN3art11ScopedCheck5CheckEbPKcz.constprop.131+3102)
    #09 pc 0010e21d  /system/lib/libart.so (art::CheckJNI::NewStringUTF(_JNIEnv*, char const*)+93)
    #10 pc 00045293  /system/lib/libjavacore.so
    #11 pc 002ee93e  /data/dalvik-cache/x86/system@framework@boot.oat
```
```log
Process: io.appium.uiautomator2.server
Flags: 0x88be46
Package: io.appium.uiautomator2.server v33 (3.7.0)
Build: Android/sdk_phone_x86/generic_x86:5.1.1/LMY48X/4174727:userdebug/test-keys

java.lang.RuntimeException: Error while connecting UiAutomation
        at android.app.UiAutomation.connect(UiAutomation.java:198)
        at android.app.Instrumentation.getUiAutomation(Instrumentation.java:1832)
        at androidx.test.uiautomator.UiDevice.getUiAutomation(UiDevice.java:1135)
        at androidx.test.uiautomator.QueryController.<init>(QueryController.java:95)
        at androidx.test.uiautomator.UiDevice.<init>(UiDevice.java:109)
        at androidx.test.uiautomator.UiDevice.getInstance(UiDevice.java:261)
        at io.appium.uiautomator2.utils.Device.getUiDevice(Device.java:25)
        at io.appium.uiautomator2.server.ServerInstrumentation.acquireWakeLock(ServerInstrumentation.java:86)
        at io.appium.uiautomator2.server.ServerInstrumentation.access$100(ServerInstrumentation.java:37)
        at io.appium.uiautomator2.server.ServerInstrumentation$HttpdThread.startServer(ServerInstrumentation.java:208)
        at io.appium.uiautomator2.server.ServerInstrumentation$HttpdThread.run(ServerInstrumentation.java:193)
Caused by: android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:496)
        at android.app.IUiAutomationConnection$Stub$Proxy.connect(IUiAutomationConnection.java:210)
        at android.app.UiAutomation.connect(UiAutomation.java:196)
        ... 10 more
```

## Environment

* Appium version 1.14.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Window10
* Node.js version (unless using Appium.app|exe): 10.16.1
* Npm or Yarn package manager: npm 
* Mobile platform/version under test: Android5.1
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: Appium cli

## Details

i refs to http://appium.io/docs/en/advanced-concepts/parallel-tests/ run 10 emulators 
it's always Appear error

**I've looked at a lot of issues, most of them are about third parties. I want to know why appium is so unstable. If there are requirements for third parties, what's the best third party device? Can I give you a clear suggestion because it's so unstable and I don't know why?**

Any help would be appreciated.:pensive::pensive::pensive::pensive:

**Comment by mykola-mokhnach** [comment]
UiAutomator2 is only stable since Android6. It is supported by Android5 theoretically, but the reality is different. Try uiautomator1 or Espresso there.

**Comment by dtboy1995** [comment]
it is Android kernel's bug
