### ISSUE TITLE
Setting Chrome options

### ISSUE THREAD

**Issue by sasanapu** [appium/appium#13209]
## The problem

I have problem setting chrome options while running Android Web TestNG Java tests. I have to disable the save password popup, that comes after login. I am trying to disable it by setting chrome preferences but Appium is not recognising the chrome options. 

## Environment
Appium version used: 1.7.1
Chrome version: 65

## Link to Appium logs
https://gist.github.com/sasanapu/b48c92940218720cbefc909e172368f9

## Code To Reproduce Issue [ Good To Have ]

DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "Android Emulator");
        capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, config.getPlatformName());
        capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, config.getPlatformVersion());
        capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, config.getBrowser());
        capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, NEW_COMMAND_TIMEOUT);
        capabilities.setCapability(AndroidMobileCapabilityType.NATIVE_WEB_SCREENSHOT, true);
        capabilities.setCapability(AndroidMobileCapabilityType.UNICODE_KEYBOARD, true);
        capabilities.setCapability(AndroidMobileCapabilityType.RESET_KEYBOARD, true);

        // Setting chrome options to disable save your password popup
        if(config.getBrowser().equalsIgnoreCase("Chrome")) {
            Logger.log("Disabling save password");
            ChromeOptions cOptions = new ChromeOptions();
            Map<String, Object> prefs = new HashMap<>();
            prefs.put("credentials_enable_service", false);
            prefs.put("profile.password_manager_enabled", false);
            cOptions.setExperimentalOption("prefs", prefs);

            capabilities.setCapability(ChromeOptions.CAPABILITY, cOptions);
        }
        
        AppiumDriver<MobileElement> driver = new AppiumDriver<MobileElement> (new URL(config.getAppiumEndpoint()), capabilities);
        return driver;
    }

**Comment by mykola-mokhnach** [comment]
`chromeOptions` is an appium capability in such case. It should not be prefixed with `goog`

**Comment by mykola-mokhnach** [comment]
Also Appium 1.7 is out of date

**Comment by sasanapu** [comment]
Thanks for you recommendation. I have tried running with Appium 1.13 but got the following error, 

```
Error: Failed to start Chromedriver session: An unknown server-side error occurred while processing the command. Original error: unknown error: cannot parse capability: chromeOptions
from unknown error: unrecognized chrome option: prefs
(Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Linux 3.13.0-139-generic x86_64)
at Object.wrappedLogger.errorAndThrow (/usr/local/avm/versions/1.13.0/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13) at errorAndThrow (/usr/local/avm/versions/1.13.0/node_modules/appium/node_modules/appium-chromedriver/lib/chromedriver.js:493:13) Chromedriver exited unexpectedly with code 1, signal null
```

Appium log : https://gist.github.com/sasanapu/c5e5600857f4def419a54cab7d6a22b3

**Comment by sasanapu** [comment]
> `chromeOptions` is an appium capability in such case. It should not be prefixed with `goog`

I have not prefixed it. "ChromeOptions.CAPABILITY" is getting resolved to "goog:chromeOptions". Should I use "AndroidMobileCapabilityType.CHROME_OPTIONS" instead as it gets resolved to "chromeOptions"

**Comment by mykola-mokhnach** [comment]
Yes you should
