### ISSUE TITLE
Not able to use setContext because of chromedriver capability

### ISSUE THREAD

**Issue by vjmaiky** [appium/appium#13215]
## The problem
Basically we have a payment system in our web which opens a webview. Using setContext we connect to that webview and start interacting with elements.
- updated to appium java library to 7.2

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15- beta 1
* Last Appium version that did not exhibit the issue (if applicable): 1.13 - beta 3
* Desktop OS/version used to run Appium: Mac OS Mojave 10.14.4
* Node.js version (unless using Appium.app|exe): 12.4.0
* Npm or Yarn package manager: 6.11.3
* Mobile platform/version under test: Android Q
* Real device or emulator/simulator: Pixel 3

## Link to Appium logs

```
[AndroidDriver] The 'chromeDriverPort' capability is deprecated. Please use 'chromedriverPort' instead
[Chromedriver] No old chromedrivers seem to exist
[Chromedriver] Failed to start Chromedriver session: A new session could not be created. Details: session not created: This version of ChromeDriver only supports Chrome version 76
[Chromedriver] Failed to start Chromedriver session: A new session could not be created. Details: session not created: This version of ChromeDriver only supports Chrome version 76
[Chromedriver] Failed to start Chromedriver session: A new session could not be created. Details: session not created: This version of ChromeDriver only supports Chrome version 76
[Chromedriver] Failed to start Chromedriver session: A new session could not be created. Details: session not created: This version of ChromeDriver only supports Chrome version 76
[Chromedriver] Chromedriver exited unexpectedly with code null, signal SIGTERM
[Chromedriver] Error: A new session could not be created. Details: session not created: This version of ChromeDriver only supports Chrome version 76
[Chromedriver]     at Object.wrappedLogger.errorAndThrow (/usr/local/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:79:13)
[Chromedriver]     at Chromedriver.errorAndThrow [as start] (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/lib/chromedriver.js:540:11)
[Chromedriver]     at AndroidUiautomator2Driver.setupNewChromedriver (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/lib/commands/context.js:429:3)
[Chromedriver]     at AndroidUiautomator2Driver.startChromedriverProxy (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/lib/commands/context.js:133:10)
[Chromedriver]     at AndroidUiautomator2Driver.switchContext (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/lib/commands/context.js:69:5)
[Chromedriver]     at AndroidUiautomator2Driver.setContext (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/lib/commands/context.js:60:3)
09-10-2019 13:33:21 - [core.helpers.ContextHandler / switchToContext][ERROR] - Could not switch to context WEBVIEW_stetho_de.telekom.hotspotlogin.de
io.appium.java_client.NoSuchContextException: An unknown server-side error occurred while processing the command. Original error: A new session could not be created. Details: session not created: This version of ChromeDriver only supports Chrome version 76
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Lucians-MacBook.local', ip: '172.16.117.249', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.4', java.version: '1.8.0_144'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {app: /Users/Shared/Appium/app-qa..., appActivity: de.telekom.conectivity.infl..., appPackage: de.telekom.conectivity.infl..., automationName: uiautomator2, databaseEnabled: false, desired: {app: /Users/Shared/Appium/app-qa..., appActivity: de.telekom.conectivity.infl..., appPackage: de.telekom.conectivity.infl..., automationName: uiautomator2, deviceName: HT8281A03687, newCommandTimeout: 600, platformName: android, systemPort: 8201, udid: HT8281A03687, unicodeKeyboard: true}, deviceApiLevel: 28, deviceManufacturer: Google, deviceModel: Pixel 2, deviceName: HT8281A03687, deviceScreenDensity: 420, deviceScreenSize: 1080x1920, deviceUDID: HT8281A03687, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, newCommandTimeout: 600, pixelRatio: 2.625, platform: LINUX, platformName: android, platformVersion: Q, statBarHeight: 63, systemPort: 8201, takesScreenshot: true, udid: HT8281A03687, unicodeKeyboard: true, viewportRect: {height: 1731, left: 0, top: 63, width: 1080}, warnings: {}, webStorageEnabled: false}
Session ID: b54f08e4-1c47-4b73-9beb-62ace7d6540c
	at io.appium.java_client.AppiumDriver.context(AppiumDriver.java:229)
	at core.helpers.ContextHandler.switchToContext(ContextHandler.java:40)
	at core.helpers.ContextHandler.switchToWebview(ContextHandler.java:57)
	at api.apps.inflight.endava.com.payment.view.PaymentView.purchaseWithCreditCard(PaymentView.java:209)
	at cucumber.inflight.tests.connectSteps.ConnectGuestStepsDefinition.userPaysWithUsingAnd(ConnectGuestStepsDefinition.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cucumber.runtime.Utils$1.call(Utils.java:40)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.Utils.invoke(Utils.java:34)
	at cucumber.runtime.java.JavaStepDefinition.execute(JavaStepDefinition.java:38)
	at cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:37)
	at cucumber.runtime.Runtime.runStep(Runtime.java:300)
	at cucumber.runtime.model.StepContainer.runStep(StepContainer.java:44)
	at cucumber.runtime.model.StepContainer.runSteps(StepContainer.java:39)
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:44)
	at cucumber.runtime.junit.ExecutionUnitRunner.run(ExecutionUnitRunner.java:102)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.runtime.junit.ExamplesRunner.run(ExamplesRunner.java:59)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.runtime.junit.ScenarioOutlineRunner.run(ScenarioOutlineRunner.java:53)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:63)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:18)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:70)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:95)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:38)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.api.junit.Cucumber.run(Cucumber.java:100)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: A new session could not be created. Details: session not created: This version of ChromeDriver only supports Chrome version 76
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Lucians-MacBook.local', ip: '172.16.117.249', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.4', java.version: '1.8.0_144'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {app: /Users/Shared/Appium/app-qa..., appActivity: de.telekom.conectivity.infl..., appPackage: de.telekom.conectivity.infl..., automationName: uiautomator2, databaseEnabled: false, desired: {app: /Users/Shared/Appium/app-qa..., appActivity: de.telekom.conectivity.infl..., appPackage: de.telekom.conectivity.infl..., automationName: uiautomator2, deviceName: HT8281A03687, newCommandTimeout: 600, platformName: android, systemPort: 8201, udid: HT8281A03687, unicodeKeyboard: true}, deviceApiLevel: 28, deviceManufacturer: Google, deviceModel: Pixel 2, deviceName: HT8281A03687, deviceScreenDensity: 420, deviceScreenSize: 1080x1920, deviceUDID: HT8281A03687, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, newCommandTimeout: 600, pixelRatio: 2.625, platform: LINUX, platformName: android, platformVersion: Q, statBarHeight: 63, systemPort: 8201, takesScreenshot: true, udid: HT8281A03687, unicodeKeyboard: true, viewportRect: {height: 1731, left: 0, top: 63, width: 1080}, warnings: {}, webStorageEnabled: false}
Session ID: b54f08e4-1c47-4b73-9beb-62ace7d6540c
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at io.appium.java_client.AppiumDriver.context(AppiumDriver.java:226)
```

What i do not understand is that i updated java library to 7.2 so basically new server arguments class is used, but when we are creating the local appium server, old flag is sent. And i think that causes the crash within appium server.

**Comment by vjmaiky** [comment]
after digging a bit i saw the following:

```
[AndroidDriver] The 'chromeDriverPort' capability is deprecated. Please use 'chromedriverPort' instead
[debug] [AndroidDriver] Using user-specified port 9539 for chromedriver
[debug] [AndroidDriver] Before starting chromedriver, androidPackage is 'apppackage'
[debug] [Chromedriver] Changed state to 'starting'
[debug] [Chromedriver] Found 1 executable in '/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac'
[debug] [Chromedriver] The following Chromedriver executables were found:
[debug] [Chromedriver]     '/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/chromedriver' (version '76.0.3809.126', minimum Chrome version '76.0.3809')
[debug] [ADB] Getting package info for 'com.android.chrome'
[debug] [ADB] Running '/Users/admin/Library/Android/sdk/platform-tools/adb -P 5037 -s HT8281A03687 shell dumpsys package com.android.chrome'
[debug] [Chromedriver] Found Chrome bundle 'com.android.chrome' version '76.0.3809'
[debug] [Chromedriver] Found 1 Chromedriver executable capable of automating Chrome '76.0.3809'.
[debug] [Chromedriver] Choosing the most recent, '/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/chromedriver'.
[debug] [Chromedriver] If a specific version is required, specify it with the `chromedriverExecutable`desired capability.
[Chromedriver] Set chromedriver binary as: /usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/chromedriver
[debug] [Chromedriver] Killing any old chromedrivers, running: pkill -15 -f "/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/chromedriver.*--port=9539"
[Chromedriver] No old chromedrivers seem to exist
[debug] [Chromedriver] Cleaning any old adb forwarded port socket connections
[debug] [ADB] List forwarding ports
[debug] [ADB] Running '/Users/admin/Library/Android/sdk/platform-tools/adb -P 5037 -s HT8281A03687 forward --list'
[debug] [ADB] Removing forwarded port socket connection: 55877 
[debug] [ADB] Running '/Users/admin/Library/Android/sdk/platform-tools/adb -P 5037 -s HT8281A03687 forward --remove tcp\:55877'
[debug] [ADB] Removing forwarded port socket connection: 55896 
[debug] [ADB] Running '/Users/admin/Library/Android/sdk/platform-tools/adb -P 5037 -s HT8281A03687 forward --remove tcp\:55896'
[debug] [ADB] Removing forwarded port socket connection: 55905 
[debug] [ADB] Running '/Users/admin/Library/Android/sdk/platform-tools/adb -P 5037 -s HT8281A03687 forward --remove tcp\:55905'
[debug] [ADB] Removing forwarded port socket connection: 55914 
[debug] [ADB] Running '/Users/admin/Library/Android/sdk/platform-tools/adb -P 5037 -s HT8281A03687 forward --remove tcp\:55914'
[Chromedriver] Spawning chromedriver with: /usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/chromedriver --url-base=wd/hub --port=9539 --adb-port=5037 --verbose
[debug] [Chromedriver] Chromedriver version: '76.0.3809.126'
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9539/wd/hub/status] with no body
[debug] [WD Proxy] Got response with status 200: {"value":{"build":{"version":"76.0.3809.126 (d80a294506b4c9d18015e755cee48f953ddc3f2f-refs/branch-heads/3809@{#1024})"},"message":"ChromeDriver ready for new sessions.","os":{"arch":"x86_64","name":"Mac OS X","version":"10.14.4"},"ready":true}}
[Chromedriver] Starting W3C Chromedriver session with capabilities: {
[Chromedriver]   "capabilities": {
[Chromedriver]     "alwaysMatch": {
[Chromedriver]       "goog:chromeOptions": {
[Chromedriver]         "androidPackage": "apppackage",
[Chromedriver]         "androidUseRunningApp": true,
[Chromedriver]         "androidDeviceSerial": "HT8281A03687"
[Chromedriver]       },
[Chromedriver]       "goog:loggingPrefs": {
[Chromedriver]         "browser": "ALL"
[Chromedriver]       }
[Chromedriver]     }
[Chromedriver]   }
[Chromedriver] }
[debug] [WD Proxy] Matched '/session' to command name 'createSession'
[debug] [WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:9539/wd/hub/session] with body: {"capabilities":{"alwaysMatch":{"goog:chromeOptions":{"androidPackage":"apppackage","androidUseRunningApp":true,"androidDeviceSerial":"HT8281A03687"},"goog:loggingPrefs":{"browser":"ALL"}}}}
[debug] [Chromedriver] Webview version: 'Chrome/73.0.3683.20'
[WD Proxy] Got an unexpected response with status 500: {"value":{"error":"session not created","message":"session not created: This version of ChromeDriver only supports Chrome version 76","stacktrace":"0   chromedriver                        0x0000000103d91f69 chromedriver + 3649385\n1   chromedriver                        0x0000000103d21f73 chromedriver + 3190643\n2   chromedriver                        0x0000000103ac2b1f chromedriver + 703263\n3   chromedriver                        0x0000000103a2e3fb chromedriver + 95227\n4   chromedriver                        0x0000000103a2850e chromedriver + 70926\n5   chromedriver                        0x0000000103a56f79 chromedriver + 262009\n6   chromedriver                        0x0000000103a54593 chromedriver + 251283\n7   chromedriver                        0x0000000103a305e2 chromedriver + 103906\n8   chromedriver                        0x0000000103a316a5 chromedriver + 108197\n9   chromedriver                        0x0000000103d4fa5f chromedriver + 3377759\n10  chromedriver                        0x0000000103...
[debug] [W3C] Matched W3C error code 'session not created' to SessionNotCreatedError
[Chromedriver] Failed to start Chromedriver session: A new session could not be created. Details: session not created: This version of ChromeDriver only supports Chrome version 76
[debug] [WD Proxy] Matched '/session' to command name 'createSession'
[debug] [WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:9539/wd/hub/session] with body: {"capabilities":{"alwaysMatch":{"goog:chromeOptions":{"androidPackage":"apppackage","androidUseRunningApp":true,"androidDeviceSerial":"HT8281A03687"},"goog:loggingPrefs":{"browser":"ALL"}}}}
[debug] [Chromedriver] Webview version: 'Chrome/73.0.3683.20'
[WD Proxy] Got an unexpected response with status 500: {"value":{"error":"session not created","message":"session not created: This version of ChromeDriver only supports Chrome version 76","stacktrace":"0   chromedriver                        0x0000000103d91f69 chromedriver + 3649385\n1   chromedriver                        0x0000000103d21f73 chromedriver + 3190643\n2   chromedriver                        0x0000000103ac2b1f chromedriver + 703263\n3   chromedriver                        0x0000000103a2e3fb chromedriver + 95227\n4   chromedriver                        0x0000000103a2850e chromedriver + 70926\n5   chromedriver                        0x0000000103a56f79 chromedriver + 262009\n6   chromedriver                        0x0000000103a54593 chromedriver + 251283\n7   chromedriver                        0x0000000103a305e2 chromedriver + 103906\n8   chromedriver                        0x0000000103a316a5 chromedriver + 108197\n9   chromedriver                        0x0000000103d4fa5f chromedriver + 3377759\n10  chromedriver                        0x0000000103...
[debug] [W3C] Matched W3C error code 'session not created' to SessionNotCreatedError
[Chromedriver] Failed to start Chromedriver session: A new session could not be created. Details: session not created: This version of ChromeDriver only supports Chrome version 76
[debug] [WD Proxy] Matched '/session' to command name 'createSession'
[debug] [WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:9539/wd/hub/session] with body: {"capabilities":{"alwaysMatch":{"goog:chromeOptions":{"androidPackage":"apppackage","androidUseRunningApp":true,"androidDeviceSerial":"HT8281A03687"},"goog:loggingPrefs":{"browser":"ALL"}}}}
[debug] [Chromedriver] Webview version: 'Chrome/73.0.3683.20'
[WD Proxy] Got an unexpected response with status 500: {"value":{"error":"session not created","message":"session not created: This version of ChromeDriver only supports Chrome version 76","stacktrace":"0   chromedriver                        0x0000000103d91f69 chromedriver + 3649385\n1   chromedriver                        0x0000000103d21f73 chromedriver + 3190643\n2   chromedriver                        0x0000000103ac2b1f chromedriver + 703263\n3   chromedriver                        0x0000000103a2e3fb chromedriver + 95227\n4   chromedriver                        0x0000000103a2850e chromedriver + 70926\n5   chromedriver                        0x0000000103a56f79 chromedriver + 262009\n6   chromedriver                        0x0000000103a54593 chromedriver + 251283\n7   chromedriver                        0x0000000103a305e2 chromedriver + 103906\n8   chromedriver                        0x0000000103a316a5 chromedriver + 108197\n9   chromedriver                        0x0000000103d4fa5f chromedriver + 3377759\n10  chromedriver                        0x0000000103...
[debug] [W3C] Matched W3C error code 'session not created' to SessionNotCreatedError
[Chromedriver] Failed to start Chromedriver session: A new session could not be created. Details: session not created: This version of ChromeDriver only supports Chrome version 76
[debug] [WD Proxy] Matched '/session' to command name 'createSession'
[debug] [WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:9539/wd/hub/session] with body: {"capabilities":{"alwaysMatch":{"goog:chromeOptions":{"androidPackage":"apppackage","androidUseRunningApp":true,"androidDeviceSerial":"HT8281A03687"},"goog:loggingPrefs":{"browser":"ALL"}}}}
[debug] [Chromedriver] Webview version: 'Chrome/73.0.3683.20'
[WD Proxy] Got an unexpected response with status 500: {"value":{"error":"session not created","message":"session not created: This version of ChromeDriver only supports Chrome version 76","stacktrace":"0   chromedriver                        0x0000000103d91f69 chromedriver + 3649385\n1   chromedriver                        0x0000000103d21f73 chromedriver + 3190643\n2   chromedriver                        0x0000000103ac2b1f chromedriver + 703263\n3   chromedriver                        0x0000000103a2e3fb chromedriver + 95227\n4   chromedriver                        0x0000000103a2850e chromedriver + 70926\n5   chromedriver                        0x0000000103a56f79 chromedriver + 262009\n6   chromedriver                        0x0000000103a54593 chromedriver + 251283\n7   chromedriver                        0x0000000103a305e2 chromedriver + 103906\n8   chromedriver                        0x0000000103a316a5 chromedriver + 108197\n9   chromedriver                        0x0000000103d4fa5f chromedriver + 3377759\n10  chromedriver                        0x0000000103...
[debug] [W3C] Matched W3C error code 'session not created' to SessionNotCreatedError
[Chromedriver] Failed to start Chromedriver session: A new session could not be created. Details: session not created: This version of ChromeDriver only supports Chrome version 76
[Chromedriver] Chromedriver exited unexpectedly with code null, signal SIGTERM
[debug] [Chromedriver] Changed state to 'stopped'
[Chromedriver] Error: A new session could not be created. Details: session not created: This version of ChromeDriver only supports Chrome version 76
[Chromedriver]     at Object.wrappedLogger.errorAndThrow (/usr/local/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:79:13)
[Chromedriver]     at Chromedriver.errorAndThrow [as start] (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/lib/chromedriver.js:540:11)
[Chromedriver]     at AndroidUiautomator2Driver.setupNewChromedriver (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/lib/commands/context.js:429:3)
[Chromedriver]     at AndroidUiautomator2Driver.startChromedriverProxy (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/lib/commands/context.js:133:10)
[Chromedriver]     at AndroidUiautomator2Driver.switchContext (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/lib/commands/context.js:69:5)
[Chromedriver]     at AndroidUiautomator2Driver.setContext (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/lib/commands/context.js:60:3)
[debug] [W3C (e99f388b)] Encountered internal error running command: Error: A new session could not be created. Details: session not created: This version of ChromeDriver only supports Chrome version 76
[debug] [W3C (e99f388b)]     at Object.wrappedLogger.errorAndThrow (/usr/local/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:79:13)
[debug] [W3C (e99f388b)]     at Chromedriver.errorAndThrow [as start] (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/lib/chromedriver.js:540:11)
[debug] [W3C (e99f388b)]     at AndroidUiautomator2Driver.setupNewChromedriver (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/lib/commands/context.js:429:3)
[debug] [W3C (e99f388b)]     at AndroidUiautomator2Driver.startChromedriverProxy (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/lib/commands/context.js:133:10)
[debug] [W3C (e99f388b)]     at AndroidUiautomator2Driver.switchContext (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/lib/commands/context.js:69:5)
[debug] [W3C (e99f388b)]     at AndroidUiautomator2Driver.setContext (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/lib/commands/context.js:60:3)
[HTTP] <-- POST /wd/hub/session/e99f388b-654f-4b3f-b75e-69cb1e73cc7c/context 500 2027 ms - 749
```

**Comment by vjmaiky** [comment]
what i understand is that webview version is older that the chromedriver which appium uses?
Question: how to handle this situation?

**Comment by mykola-mokhnach** [comment]
> [Chromedriver] Failed to start Chromedriver session: A new session could not be created. Details: session not created: This version of ChromeDriver only supports Chrome version 76

How this is related to java client version? The error says the ucrrent chromedriver version is not good for the given web view version (which is Chrome/73.0.3683.20)
You should downgrade chromedriver (see https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md)

**Comment by vjmaiky** [comment]
got it; thank you; long time no use of appium :)

**Comment by mykola-mokhnach** [comment]
Just FYI: in order to properly run W3C chromedriver session, which is supported since Chromedriver v76 you should use java client, which contains the fix made in https://github.com/appium/java-client/commit/1e80399ec649606d4ebf8330250cc4782168704b

Otherwise it will be necessary to explicitly fall back to jsonwp by setting the `w3c` chromedriver option to `false`
