### ISSUE TITLE
"Command 'Scripts/bootstrap.sh -d' exited with code 1`" when inspecting the ios app by appium-desktop

### ISSUE THREAD

**Issue by learningandworking** [appium/appium#13226]
## The problem
- Using appium-desktop on MAC to inspect an ios app, then get error as below
`An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 1`

## Environment

* Appium version (or git revision) that exhibits the issue: Version 1.13.0 (1.13.0.20190505.5)
* Desktop OS/version used to run Appium: MAC OS 10.13.6
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: simulator iPhone6S - iOS11
* Xcode version: Xcode 9.1
* Appium CLI or Appium.app|exe: Appium.app
* ipa file: https://github.com/webdriverio/native-demo-app/releases

## Details

- Configure in appium with desired capability
`{
  "platformName": "iOS",
  "platformVersion": "11.1",
  "deviceName": "iPhone 6s",
  "noReset": true,
  "app": " ./apps/iOS-Simulator-NativeDemoApp-0.2.1.app.zip",
  "automationName": "XCUITest"
}`
- Start Appium.app (not start by command line), check inspect.
## Link to Appium logs
```
[info]  [35m[Appium][39m Welcome to Appium v1.13.0
[info]  [35m[Appium][39m Appium REST http interface listener started on 0.0.0.0:4723[info]  [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m
[info]  [35m[HTTP][39m [90m{"desiredCapabilities":{"app":"./apps/iOS-Simulator-NativeDemoApp-0.2.1.app.zip","automationName":"XCUITest","deviceName":"iPhone 6s","noReset":true,"platformName":"iOS","platformVersion":"11.1","newCommandTimeout":0,"connectHardwareKeyboard":true}}[39m
[debug] [35m[MJSONWP][39m Calling AppiumDriver.createSession() with args: [{"app":"/apps/iOS-Simulator-NativeDemoApp-0.2.1.app.zip","automationName":"XCUITest","deviceName":"iPhone 6s","noReset":true,"platformName":"iOS","platformVersion":"11.1","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[debug] [35m[BaseDriver][39m Event 'newSessionRequested' logged at 1568301611982 (22:20:11 GMT+0700 (+07))
[info]  [35m[Appium][39m Appium v1.13.0 creating new XCUITestDriver (v2.113.2) session
[info]  [35m[Appium][39m Capabilities:
[info]  [35m[Appium][39m   app: /apps/iOS-Simulator-NativeDemoApp-0.2.1.app.zip
[info]  [35m[Appium][39m   automationName: XCUITest
[info]  [35m[Appium][39m   deviceName: iPhone 6s
[info]  [35m[Appium][39m   noReset: true
[info]  [35m[Appium][39m   platformName: iOS
[info]  [35m[Appium][39m   platformVersion: 11.1
[info]  [35m[Appium][39m   newCommandTimeout: 0
[info]  [35m[Appium][39m   connectHardwareKeyboard: true
[debug] [35m[BaseDriver][39m Creating session with MJSONWP desired capabilities: {"app":"/Users/test/Per...
[info]  [35m[BaseDriver][39m Session created with session id: 4f41800b-fd9f-4670-ba01-49f172f854a6[debug] [35m[XCUITest][39m Current user: 'test'
[info]  [35m[iOSSim][39m Constructing iOS simulator for Xcode version 9.1 with udid '11928CCB-CBFF-4557-AEA5-76FC6F2486A0'
[info]  [35m[XCUITest][39m Determining device to run tests on: udid: '11928CCB-CBFF-4557-AEA5-76FC6F2486A0', real device: false
[info]  [35m[XCUITest][39m iOS SDK Version set to '11.1'
[debug] [35m[BaseDriver][39m Event 'xcodeDetailsRetrieved' logged at 1568301612206 (22:20:12 GMT+0700 (+07))
[info]  [35m[BaseDriver][39m Using local app '/apps/iOS-Simulator-NativeDemoApp-0.2.1.app.zip'
[info]  [35m[BaseDriver][39m Will reuse previously cached application at '/var/folders/xy/5lg38fdx3gb42jvqpctm2ypjqrpdwd/T/2019812-1430-szedtd.vkgzm/iOS-Simulator-NativeDemoApp-0.2.1.app'
[debug] [35m[BaseDriver][39m Event 'appConfigured' logged at 1568301612243 (22:20:12 GMT+0700 (+07))
[debug] [35m[XCUITest][39m Checking whether app '/var/folders/xy/5lg38fdx3gb42jvqpctm2ypjqrpdwd/T/2019812-1430-szedtd.vkgzm/iOS-Simulator-NativeDemoApp-0.2.1.app' is actually present on file system
[debug] [35m[XCUITest][39m App is present
[debug] [35m[iOS][39m Getting bundle ID from app '/var/folders/xy/5lg38fdx3gb42jvqpctm2ypjqrpdwd/T/2019812-1430-szedtd.vkgzm/iOS-Simulator-NativeDemoApp-0.2.1.app': 'org.reactjs.native.example.wdioDemoApp'
[debug] [35m[BaseDriver][39m Event 'resetStarted' logged at 1568301612244 (22:20:12 GMT+0700 (+07))
[debug] [35m[XCUITest][39m Reset: noReset is on. Leaving simulator as is
[debug] [35m[BaseDriver][39m Event 'resetComplete' logged at 1568301612244 (22:20:12 GMT+0700 (+07))[debug] [35m[XCUITest][39m Starting log capture for iOS Simulator with udid '11928CCB-CBFF-4557-AEA5-76FC6F2486A0', using 'xcrun simctl spawn 11928CCB-CBFF-4557-AEA5-76FC6F2486A0 log stream --style compact'
[debug] [35m[BaseDriver][39m Event 'logCaptureStarted' logged at 1568301612499 (22:20:12 GMT+0700 (+07))
[info]  [35m[XCUITest][39m Setting up simulator
[debug] [35m[iOS][39m No reason to set locale
[debug] [35m[iOS][39m No iOS / app preferences to set
[debug] [35m[iOSSim][39m Setting preferences of 11928CCB-CBFF-4557-AEA5-76FC6F2486A0 Simulator to {"ConnectHardwareKeyboard":true}
[debug] [35m[iOSSim][39m Setting common Simulator preferences to {"RotateWindowWhenSignaledByGuest":true,"ConnectHardwareKeyboard":true}[debug] [35m[iOSSim][39m Updated 11928CCB-CBFF-4557-AEA5-76FC6F2486A0 Simulator preferences at '/Users/test/Library/Preferences/com.apple.iphonesimulator.plist' with {"DevicePreferences":{"11928CCB-CBFF-4557-AEA5-76FC6F2486A0":{"ConnectHardwareKeyboard":true}},"RotateWindowWhenSignaledByGuest":true,"ConnectHardwareKeyboard":true}
[debug] [35m[iOSSim][39m Got Simulator UI client PID: 2275
[info]  [35m[iOSSim][39m Both Simulator with UDID 11928CCB-CBFF-4557-AEA5-76FC6F2486A0 and the UI client are currently running
[debug] [35m[BaseDriver][39m Event 'simStarted' logged at 1568301612624 (22:20:12 GMT+0700 (+07))
[debug] [35m[XCUITest][39m Verifying application platform
[debug] [35m[XCUITest][39m CFBundleSupportedPlatforms: ["iPhoneSimulator"]
[debug] [35m[XCUITest][39m App 'org.reactjs.native.example.wdioDemoApp' is already installed. No need to reinstall.
[debug] [35m[BaseDriver][39m Event 'appInstalled' logged at 1568301612733 (22:20:12 GMT+0700 (+07))
[info]  [35m[XCUITest][39m Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[info]  [35m[XCUITest][39m Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'[debug] [35m[XCUITest][39m No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[debug] [35m[XCUITest][39m Starting WebDriverAgent initialization with the synchronization key 'XCUITestDriver'
[debug] [35m[WD Proxy][39m Matched '/status' to command name 'getStatus'
[debug] [35m[WD Proxy][39m Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[warn] [35m[WD Proxy][39m Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[debug] [35m[XCUITest][39m WDA is not listening at 'http://localhost:8100/'
[debug] [35m[XCUITest][39m WDA is currently not running. There is nothing to cache
[debug] [35m[XCUITest][39m Trying to start WebDriverAgent 2 times with 10000ms interval
[debug] [35m[XCUITest][39m These values can be customized by changing wdaStartupRetries/wdaStartupRetryInterval capabilities
[debug] [35m[BaseDriver][39m Event 'wdaStartAttempted' logged at 1568301612791 (22:20:12 GMT+0700 (+07))
[info]  [35m[XCUITest][39m Launching WebDriverAgent on the device
[debug] [35m[XCUITest][39m Carthage found: '/usr/local/bin/carthage'
[debug] [35m[XCUITest][39m Running WebDriverAgent bootstrap script to install dependencies
[error] [35m[XCUITest][39m [1mFetching dependencies
[error] [35m[XCUITest][39m Usage: simctl list [-j | --json] [devices|devicetypes|runtimes|pairs]
[error] [35m[XCUITest][39m Traceback (most recent call last):
[error] [35m[XCUITest][39m   File "<string>", line 1, in <module>
[error] [35m[XCUITest][39m   File "/Users/test/.pyenv/versions/2.7.15/lib/python2.7/json/__init__.py", line 291, in load
[error] [35m[XCUITest][39m     **kw)
[error] [35m[XCUITest][39m   File "/Users/test/.pyenv/versions/2.7.15/lib/python2.7/json/__init__.py", line 339, in loads
[error] [35m[XCUITest][39m     return _default_decoder.decode(s)
[error] [35m[XCUITest][39m   File "/Users/test/.pyenv/versions/2.7.15/lib/python2.7/json/decoder.py", line 364, in decode
[error] [35m[XCUITest][39m     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
[error] [35m[XCUITest][39m   File "/Users/test/.pyenv/versions/2.7.15/lib/python2.7/json/decoder.py", line 382, in raw_decode
[error] [35m[XCUITest][39m     raise ValueError("No JSON object could be decoded")
[error] [35m[XCUITest][39m ValueError: No JSON object could be decoded
[debug] [35m[BaseDriver][39m Event 'wdaStartFailed' logged at 1568301612896 (22:20:12 GMT+0700 (+07))
[debug] [35m[XCUITest][39m Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 1
[warn] [35m[XCUITest][39m Quitting and uninstalling WebDriverAgent
[info]  [35m[XCUITest][39m Shutting down sub-processes
[debug] [35m[XCUITest][39m Removing WDA application from device[debug] [35m[BaseDriver][39m Event 'wdaStartAttempted' logged at 1568301624001 (22:20:24 GMT+0700 (+07))
[info]  [35m[XCUITest][39m Retrying WDA startup (2 of 2)
[info]  [35m[XCUITest][39m Launching WebDriverAgent on the device
[debug] [35m[XCUITest][39m Carthage found: '/usr/local/bin/carthage'
[debug] [35m[XCUITest][39m Running WebDriverAgent bootstrap script to install dependencies[error] [35m[XCUITest][39m [1mFetching dependencies
[error] [35m[XCUITest][39m Usage: simctl list [-j | --json] [devices|devicetypes|runtimes|pairs]
[error] [35m[XCUITest][39m Traceback (most recent call last):
[error] [35m[XCUITest][39m   File "<string>", line 1, in <module>
[error] [35m[XCUITest][39m   File "/Users/test/.pyenv/versions/2.7.15/lib/python2.7/json/__init__.py", line 291, in load
[error] [35m[XCUITest][39m     **kw)
[error] [35m[XCUITest][39m   File "/Users/test/.pyenv/versions/2.7.15/lib/python2.7/json/__init__.py", line 339, in loads
[error] [35m[XCUITest][39m     return _default_decoder.decode(s)
[error] [35m[XCUITest][39m   File "/Users/test/.pyenv/versions/2.7.15/lib/python2.7/json/decoder.py", line 364, in decode
[error] [35m[XCUITest][39m     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
[error] [35m[XCUITest][39m   File "/Users/test/.pyenv/versions/2.7.15/lib/python2.7/json/decoder.py", line 382, in raw_decode
[error] [35m[XCUITest][39m     raise ValueError("No JSON object could be decoded")
[error] [35m[XCUITest][39m ValueError: No JSON object could be decoded
[debug] [35m[BaseDriver][39m Event 'wdaStartFailed' logged at 1568301624106 (22:20:24 GMT+0700 (+07))
[debug] [35m[XCUITest][39m Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 1
[warn] [35m[XCUITest][39m Quitting and uninstalling WebDriverAgent
[info]  [35m[XCUITest][39m Shutting down sub-processes
[debug] [35m[XCUITest][39m Removing WDA application from device[error] [35m[XCUITest][39m Error: Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 1
[error] [35m[XCUITest][39m     at quitAndUninstall (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:501:15)[debug] [35m[XCUITest][39m Parsed BUILD_DIR configuration value: '/Users/test/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products'
[debug] [35m[XCUITest][39m Got derived data root: '/Users/test/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs'
[debug] [35m[XCUITest][39m Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [35m[iOSLog][39m Stopping iOS log capture
[debug] [35m[BaseDriver][39m Event 'newSessionStarted' logged at 1568301626388 (22:20:26 GMT+0700 (+07))
[debug] [35m[MJSONWP][39m Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 1
[debug] [35m[MJSONWP][39m     at quitAndUninstall (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:501:15)
[info]  [35m[HTTP][39m [37m<-- POST /wd/hub/session [39m[31m500[39m [90m14409 ms - 252[39m
[info]  [35m[HTTP][39m [90m[39m
[info]  [35m[HTTP][39m [37m-->[39m [37mDELETE[39m [37m/wd/hub/session[39m
[info]  [35m[HTTP][39m [90m{}[39m
[debug] [35m[HTTP][39m No route found. Setting content type to 'text/plain'
[info]  [35m[HTTP][39m [37m<-- DELETE /wd/hub/session [39m[33m404[39m [90m3 ms - 57[39m
[info]  [35m[HTTP][39m [90m[39m
```

**Comment by learningandworking** [comment]
Cannot @mykola-mokhnach :(

**Comment by mykola-mokhnach** [comment]
Then you could only probably downgrade Appium and try older versions of it. We run our internal tests test starting from Xcode 9.3, so it's possible there were some changes in the internal tooling between minor versions on Apple side. We are not going to address this for master, since Xcode9 will be anyway deprecated soon after version 11 is fully released.
