### ISSUE TITLE
GetTimeouts is not working on iOS but only on Android

### ISSUE THREAD

**Issue by broetchenrackete36** [appium/appium#13233]
## The problem
Cannot get Timeouts from Appium-Server when connected to iOS. This works fine on Android.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.14.2
* Node.js version (unless using Appium.app|exe): 12.7.0
* Npm or Yarn package manager: 6.11.2
* Mobile platform/version under test: iOS 12.1
* Real device or emulator/simulator: iPhoneSimulator
* Appium CLI or Appium.app|exe: cli

## Details

The W3C WebDriver-Spec specifies a Get Timeouts endpoint (https://w3c.github.io/webdriver/#get-timeouts). This is implemented in Appium [route.js](https://github.com/appium/appium-base-driver/blob/db835c7f5c3b2f4cf06295cf2404bd19141f025b/lib/protocol/routes.js#L26). This works fine for Android (UIAutomator2) but not iOS.

I'm not sure but it looks like the WebDriverAgent is not accepting the proxied request?

## Link to Appium logs

[Logfile](https://gist.github.com/broetchenrackete36/939294e0358de4d713d3093b22b946b6)

Error happens here:
```
2019-09-13 11:44:50:374 [HTTP] --> GET /wd/hub/session/4e41a169-f1ee-42b4-8db6-d238bce34939/timeouts
2019-09-13 11:44:50:374 [HTTP] {}
2019-09-13 11:44:50:375 [MJSONWP (4e41a169)] Driver proxy active, passing request on via HTTP proxy
2019-09-13 11:44:50:376 [XCUITest] Executing command 'proxyReqRes'
2019-09-13 11:44:50:376 [WD Proxy] Matched '/wd/hub/session/4e41a169-f1ee-42b4-8db6-d238bce34939/timeouts' to command name 'getTimeouts'
2019-09-13 11:44:50:377 [WD Proxy] Proxying [GET /wd/hub/session/4e41a169-f1ee-42b4-8db6-d238bce34939/timeouts] to [GET http://localhost:8100/session/0A6746EC-9187-460B-A3DC-4BD46F3E550D/timeouts] with body: {}
2019-09-13 11:44:50:380 [WD Proxy] Got response with status 200: "{\n  \"value\" : \"Unhandled endpoint: \\/session\\/0A6746EC-9187-460B-A3DC-4BD46F3E550D\\/timeouts -- http:\\/\\/localhost:8100\\/ with parameters {\\n    wildcards =     (\\n        \\\"session\\/0A6746EC-9187-460B-A3DC-4BD46F3E550D\\/timeouts\\\"\\n    );\\n}\",\n  \"sessionId\" : \"0A6746EC-9187-460B-A3DC-4BD46F3E550D\",\n  \"status\" : 1\n}"
2019-09-13 11:44:50:388 [MJSONWP (4e41a169)] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: The request to /wd/hub/session/4e41a169-f1ee-42b4-8db6-d238bce34939/timeouts has failed
2019-09-13 11:44:50:388 [MJSONWP (4e41a169)]     at JWProxy.proxy (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:183:13)
2019-09-13 11:44:50:389 [MJSONWP (4e41a169)]     at ProtocolConverter.convertAndProxy (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/protocol-converter.js:226:12)
2019-09-13 11:44:50:389 [MJSONWP (4e41a169)]     at JWProxy.proxyCommand (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:227:12)
2019-09-13 11:44:50:389 [MJSONWP (4e41a169)]     at JWProxy.proxyReqRes (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:278:28)
2019-09-13 11:44:50:390 [MJSONWP] Matched JSONWP error code 1 to UnknownError
2019-09-13 11:44:50:391 [HTTP] <-- GET /wd/hub/session/4e41a169-f1ee-42b4-8db6-d238bce34939/timeouts 500 17 ms - 390
```
## Code To Reproduce Issue [ Good To Have ]
Getting Implicit-Wait in C#:
```csharp
TimeSpan previousTimeout = driver.Manage().Timeouts().ImplicitWait; // Fails on iOS, works on Android
driver.Manage().Timeouts().ImplicitWait = TimeSpan.Zero;
// ... some code here
driver.Manage().Timeouts().ImplicitWait = previousTimeout;
```

Or just cURL:
```
curl -X GET http://localhost:4723/wd/hub/session/4e41a169-f1ee-42b4-8db6-d238bce34939/timeouts
```

**Comment by mykola-mokhnach** [comment]
The request should not actually be proxied. I'll do the fix

**Comment by mykola-mokhnach** [comment]
The fix has been published in appium@beta
