### ISSUE TITLE
presenceOfElementLocated() by MobileBy.image finds not existing image on page

### ISSUE THREAD

**Issue by lubshilk** [appium/appium#13258]
## The problem
A part of image found also is not present
We use presenceOfElementLocated() to find a part of a main page. The part is found even with high threshold also it is not exactly the same view

## Environment
* Appium version (or git revision) that exhibits the issue: 1.14.2
* Desktop OS/version used to run Appium: macOS Mojave 10.14.5
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Android 8.0.0
* Real device or emulator/simulator: real

## Details
The screenshot on main page
![image](https://user-images.githubusercontent.com/20837714/65220150-c5e2da80-dac2-11e9-9395-6c13e6850aaa.png)
The image used to find the part of the main page
![image](https://user-images.githubusercontent.com/20837714/65220309-26721780-dac3-11e9-8985-3a7c1784a2b1.png)

## Link to Appium logs
https://gist.github.com/lubshilk/1906f5b7976f9f1288f5300f1ffb9a75

## Code To Reproduce Issue [ Good To Have ]
```
AppiumDriver<WebElement> driver = new AndroidDriver<WebElement>(server.getUrl(), capabilities);				
((AndroidDriver<WebElement>) driver).setSetting(Setting.IMAGE_ELEMENT_TAP_STRATEGY, "w3cActions"); //New Approach
/*Fix screenshot and device size mismatches*/
((AndroidDriver<WebElement>) driver).setSetting(Setting.FIX_IMAGE_FIND_SCREENSHOT_DIMENSIONS, false);
/*Fix the reference image size*/
((AndroidDriver<WebElement>) driver).setSetting(Setting.FIX_IMAGE_TEMPLATE_SIZE, true);
((AndroidDriver<WebElement>) driver).setSetting(Setting.CHECK_IMAGE_ELEMENT_STALENESS, false);
((AndroidDriver<WebElement>) driver).setSetting(Setting.UPDATE_IMAGE_ELEMENT_POSITION, true);
((AndroidDriver<WebElement>) driver).setSetting(Setting.IMAGE_MATCH_THRESHOLD, 0.9); 
wait = new WebDriverWait(driver, waitTime);
try { 
	WebElement elemByImg = wait.until(ExpectedConditions.presenceOfElementLocated(MobileBy.image(Base64.getEncoder().encodeToString(Files.readAllBytes(new File(imagePath).toPath())))));
	if(elemByImg.isDisplayed()) {
		return elemByImg;
	}
} catch (TimeoutException et) {
	return null;
} catch (Exception e) {
	return null;
}

```

**Comment by KazuCocoa** [comment]
You can see the selected image by https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/image-elements.md#debug .
Could you confirm the selected area?

**Comment by lubshilk** [comment]
Is getMatchedImageResult not available for java? It looks it is missing in java_client Setting enum

**Comment by KazuCocoa** [comment]
https://github.com/appium/java-client/blob/0a796983830613103180aeb9b434ea1fa748dd01/src/main/java/io/appium/java_client/Setting.java#L59

How about the latest one?

**Comment by lubshilk** [comment]
Thanks, I'll try

**Comment by lubshilk** [comment]
Using the latest java-client with all Settings available
Receive exception on
((AndroidDriver<WebElement>) driver).setSetting(Setting.GET_MATCHED_IMAGE_RESULT, true);
```
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: io.appium.uiautomator2.common.exceptions.UnsupportedSettingException: Setting 'getMatchedImageResult' is not supported. Only the following settings are supported: [actionAcknowledgmentTimeout, allowInvisibleElements, ignoreUnimportantViews, elementResponseAttributes, enableNotificationListener, keyInjectionDelay, scrollAcknowledgmentTimeout, shouldUseCompactResponses, waitForIdleTimeout, waitForSelectorTimeout, normalizeTagNames, shutdownOnPowerDisconnect, trackScrollEvents]
	at io.appium.uiautomator2.handler.UpdateSettings.getSetting(UpdateSettings.java:63)
	at io.appium.uiautomator2.handler.UpdateSettings.safeHandle(UpdateSettings.java:49)
	at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:37)
	at io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:252)
	at io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:243)
	at io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:44)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:466)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:764)

Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DVLUBASW', ip: '192.168.10.26', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {app: C:\MyFirst\screenshots\CC\S..., appActivity: com.cellact.secnum.activity..., appPackage: com.cellact.secnum, appWaitActivity: com.cellact.secnum.*, autoGrantPermissions: true, automationName: UIAutomator2, databaseEnabled: false, desired: {app: C:\MyFirst\screenshots\CC\S..., appActivity: com.cellact.secnum.activity..., appPackage: com.cellact.secnum, appWaitActivity: com.cellact.secnum.*, autoGrantPermissions: true, automationName: UIAutomator2, deviceName: MyCC, newCommandTimeout: 0, noReset: false, platformName: android, platformVersion: 8.0.0, udid: ce165f51}, deviceApiLevel: 26, deviceManufacturer: samsung, deviceModel: SM-G930T, deviceName: ce165f51, deviceScreenDensity: 480, deviceScreenSize: 1080x1920, deviceUDID: ce165f51, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, newCommandTimeout: 0, noReset: false, pixelRatio: 3, platform: LINUX, platformName: Android, platformVersion: 8.0.0, statBarHeight: 72, takesScreenshot: true, udid: ce165f51, viewportRect: {height: 1848, left: 0, top: 72, width: 1080}, warnings: {}, webStorageEnabled: false}
Session ID: 8eac257a-e1b6-443d-8aa3-edfe73a47a98
```

**Comment by KazuCocoa** [comment]
ah.. it is available from 1.15.0 https://github.com/appium/appium/pull/13264/files?short_path=4ac32a7#diff-4ac32a78649ca5bdd8e0ba38b7006a1e
(I thought 1.14 had it.)

**Comment by lubshilk** [comment]
Anyway, I don't understand, how should I use the base64 string if even receive it. Could you, please, explain?
Sorry, all this image finding is absolutely new for me

**Comment by KazuCocoa** [comment]
You need to decode the result by base64 decode methods and save it into a file. Then you can open it as `png` file. It is the same as taking screenshot feature. You can find similar logic in Appium or Selenium java client, I think.

**Comment by lubshilk** [comment]
Do you mean something like this?
```
String source = elemByImg .getAttribute("visual");
byte[] imageBytes = javax.xml.bind.DatatypeConverter.parseBase64Binary(source);
BufferedImage inputImage = ImageIO.read(new ByteArrayInputStream(imageBytes));
ImageIO.write(inputImage, "png", path);
```

**Comment by KazuCocoa** [comment]
yup

**Comment by lubshilk** [comment]
Here it is  
![LubaImg](https://user-images.githubusercontent.com/20837714/65578763-210f4400-df7f-11e9-9dd8-799dd7d2c9b2.png)

**Comment by KazuCocoa** [comment]
It depends on the provided image and OpenCV behaviour.
resolution/width x height/threshold etc affects the resutl.

You can try other settings to fit your situation.
https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/image-elements.md#related-settings

Appium compares the given image with the current screenshot.

**Comment by KazuCocoa** [comment]
Close once since the find by image feature looks working (pass the given image to opencv and return the result)

**Comment by NirBY** [comment]
I am having same issue, and I could not find how to change [Feature Matching](https://docs.opencv.org/trunk/dc/dc3/tutorial_py_matcher.html) in [Appium settings](https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/image-elements.md#related-settings), Is there a way changing it? Will you add it in the future vers?

**Comment by KazuCocoa** [comment]
The find element only provide template matching. (Internally, Appium server does similar thing)
You can do another way with https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/image-comparison.md
