### ISSUE TITLE
Appium 1.14.2 throwing NotImplementedError

### ISSUE THREAD

**Issue by vsadineni1** [appium/appium#13269]
## The problem
I am running appium version: 1.14.2 on my Mac machine (appium --port 4477)
When I try to run a test against our iOS Hybrid app, after the App is launched we click on the EULA button.

In my test, the app has launched successfully & I got a session back from appium server.
After that the appium server is throwing the below not implemented exception

[HTTP] --> POST /wd/hub/session/b5204b64-cf95-48bf-a18f-579d14a6802c/execute/sync
[HTTP] {"args":[{"element-6066-11e4-a52e-4f735466cecf":"20000000-0000-0000-F811-010000000000"}],"script":"return (function(){return function(){var k=this;function l(a){return void 0!==a}function m(a){return\"string\"==typeof a}function aa(a,b){a=a.split(\".\");var c=k;a[0]in c||!c.execScript||c.execScript(\"var \"+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&l(b)?c[d]=b:c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}}\nfunction ba(a){var b=typeof a;if(\"object\"==b)if(a){if(a instanceof Array)return\"array\";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(\"[object Window]\"==c)return\"object\";if(\"[object Array]\"==c||\"number\"==typeof a.length&&\"undefined\"!=typeof a.splice&&\"undefined\"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable(\"splice\"))return\"array\";if(\"[object Function]\"==c||\"undefined\"!=typeof a.call&&\"undefined\"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable(\"call\"))return\"function\"}else return\"null\";\nelse
[debug] [W3C (b5204b64)] Calling AppiumDriver.execute() with args: ["return (function(){return function(){var k=this;function l(a){return void 0!==a}function m(a){return\"string\"==typeof a}function aa(a,b){a=a.split(\".\");var c=k;a[0]in c||!c.execScript||c.execScript(\"var \"+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&l(b)?c[d]=b:c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}}\nfunction ba(a){var b=typeof a;if(\"object\"==b)if(a){if(a instanceof Array)return\"array\";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(\"[object Window]\"==c)return\"object\";if(\"[object Array]\"==c||\"number\"==typeof a.length&&\"undefined\"!=typeof a.splice&&\"undefined\"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable(\"splice\"))return\"array\";if(\"[object Function]\"==c||\"undefined\"!=typeof a.call&&\"undefined\"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable(\"call\"))return\"function\"}else return\"null\";\nelse if(\"function\"==b&&\"undefined\"==typeof a.call)return\"object\";return b}function ca(a,b,c){return a.call.apply(a.b...
[debug] [XCUITest] Executing command 'execute'
[debug] [W3C (b5204b64)] Encountered internal error running command: NotImplementedError: Method is not implemented
[debug] [W3C (b5204b64)]     at XCUITestDriver.execute (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/execute.js:13:11)
[debug] [W3C (b5204b64)]     at /usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:305:66
[debug] [W3C (b5204b64)]     at tryCatcher (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/release/util.js:16:23)
[debug] [W3C (b5204b64)]     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/release/promise.js:517:31)
[debug] [W3C (b5204b64)]     at Promise._settlePromise (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/release/promise.js:574:18)
[debug] [W3C (b5204b64)]     at Promise._settlePromiseCtx (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/release/promise.js:611:10)
[debug] [W3C (b5204b64)]     at _drainQueueStep (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/release/async.js:142:12)
[debug] [W3C (b5204b64)]     at _drainQueue (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/release/async.js:131:9)
[debug] [W3C (b5204b64)]     at Async._drainQueues (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/release/async.js:147:5)
[debug] [W3C (b5204b64)]     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/release/async.js:17:14)
[debug] [W3C (b5204b64)]     at processImmediate (internal/timers.js:439:21)
[HTTP] <-- POST /wd/hub/session/b5204b64-cf95-48bf-a18f-579d14a6802c/execute/sync 405 9 ms - 1351

## Environment

* Appium version (or git revision) that exhibits the issue: 1.14.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OSX 10.14.6 Mojave
* Node.js version (unless using Appium.app|exe): $ node --version (v12.8.0)

* Npm or Yarn package manager: 6.10.3
* Mobile platform/version under test: iOS 12.0 simulator (device skin is: iPhone 6)
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/vsadineni1/004c4b2677db94abf15a1d16c2d6dcd5

## Code To Reproduce Issue [ Good To Have ]
A similar issue is being reported by some other developer here - https://discuss.appium.io/t/method-is-not-implemented-error-for-native-ios-app/26965

**Comment by mykola-mokhnach** [comment]
This the problem of an outdated client
