### ISSUE TITLE
Using toggleWiFi() throws Method has not yet been implemented Error

### ISSUE THREAD

**Issue by awhisler-nutrien** [appium/appium#13275]
## The problem

When I try to run a test using driver.toggleWiFi() it fails saying "unknown method: Method has not yet been implemented"

## Environment

* Appium version that exhibits the issue: 1.13.0
* Desktop OS/version used to run Appium: iOS 13.0 and 12.4.1
* Node.js version (unless using Appium.app|exe): 12.6.0
* Yarn package manager: 1.17.3
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Simulator (automation) using webdriverio/appium

## Code To Reproduce Issue

`await browser.toggleWiFi();`

Error:
`2019-09-23T20:23:24.512Z INFO webdriver: [POST] http://127.0.0.1:4723/wd/hub/session/16293936-ed2f-4e36-ba67-15a36d48d29c/appium/device/toggle_wifi
[0-0] 2019-09-23T20:23:24.517Z ERROR webdriver: Request failed due to unknown method: Method has not yet been implemented
    at getErrorFromResponseBody (/Users/ali.whisler/nutrien-gfa/node_modules/webdriver/build/utils.js:371:10)
    at Request._callback (/Users/ali.whisler/nutrien-gfa/node_modules/webdriver/build/request.js:120:64)
    at Request.self.callback (/Users/ali.whisler/nutrien-gfa/node_modules/request/request.js:185:22)
    at Request.emit (events.js:203:13)
    at Request.EventEmitter.emit (domain.js:471:20)
    at Request.<anonymous> (/Users/ali.whisler/nutrien-gfa/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:203:13)
    at Request.EventEmitter.emit (domain.js:471:20)
    at IncomingMessage.<anonymous> (/Users/ali.whisler/nutrien-gfa/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:291:20)
[0-0] Error in "undefined"
unknown method: Method has not yet been implemented`

**Comment by awhisler-nutrien** [comment]
I guess this feature only supports Android
