### ISSUE TITLE
boot monitor issue on reboot iOS simulator 

### ISSUE THREAD

**Issue by bearxc** [appium/appium#13317]
Appium  server : latest  master branch

iOS simulator:  iOS13/Xcode 11

 Because  iOS13 sim easy to stuck ,  I try to reboot iOS simulator  during  automation,

Here is  my steps

1) driver.quit()

2)call  "xcrun simctl shutdown simID"

3)    init  a new session again  
driver = new IOSDriver<MobileElement>(new URL(configProperties.getServerUrl()), capabilities);

there is error on step 3 for  boot monitor issue, at that time , simulator does start up  already.
following is log from step 3

2019-09-29 21:53:04:852 - [Appium] Appium v1.16.0-beta.1 creating new XCUITestDriver (v3.0.0) session
2019-09-29 21:53:04:852 - [debug] [BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
2019-09-29 21:53:04:853 - [debug] [BaseDriver] Creating session with W3C capabilities: {
2019-09-29 21:53:04:853 - [debug] [BaseDriver]   "alwaysMatch": {
2019-09-29 21:53:04:854 - [debug] [BaseDriver]     "platformName": "ios",
2019-09-29 21:53:04:854 - [debug] [BaseDriver]     "appium:app": "/Users/test/test.app",
2019-09-29 21:53:04:854 - [debug] [BaseDriver]     "appium:automationName": "xcuitest",
2019-09-29 21:53:04:854 - [debug] [BaseDriver]     "appium:deviceName": "iPhone 8",
2019-09-29 21:53:04:854 - [debug] [BaseDriver]     "appium:newCommandTimeout": 1200,
2019-09-29 21:53:04:854 - [debug] [BaseDriver]     "appium:noReset": true,
2019-09-29 21:53:04:854 - [debug] [BaseDriver]     "appium:platformVersion": "13.0",
2019-09-29 21:53:04:854 - [debug] [BaseDriver]     "appium:simpleIsVisibleCheck": true
2019-09-29 21:53:04:854 - [debug] [BaseDriver]   },
2019-09-29 21:53:04:854 - [debug] [BaseDriver]   "firstMatch": [
2019-09-29 21:53:04:855 - [debug] [BaseDriver]     {}
2019-09-29 21:53:04:855 - [debug] [BaseDriver]   ]
2019-09-29 21:53:04:855 - [debug] [BaseDriver] }
2019-09-29 21:53:04:858 - [BaseDriver] Session created with session id: 904cb372-beec-46a2-ba91-8292171af055
2019-09-29 21:53:04:865 - [debug] [XCUITest] Current user: 'test'
2019-09-29 21:53:04:866 - [XCUITest] iOS SDK Version set to '13.0'
2019-09-29 21:53:05:110 - [iOSSim] Constructing iOS simulator for Xcode version 11.0 with udid '7A567ACA-404B-4CB8-BE37-2CB6E81E8352'
2019-09-29 21:53:05:110 - [XCUITest] Determining device to run tests on: udid: '7A567ACA-404B-4CB8-BE37-2CB6E81E8352', real device: false
2019-09-29 21:53:05:110 - [debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1569808385110 (21:53:05 GMT-0400 (Eastern Daylight Time))
2019-09-29 21:53:05:111 - [BaseDriver] Using local app '/Users/test/test.app'
2019-09-29 21:53:05:111 - [debug] [BaseDriver] Event 'appConfigured' logged at 1569808385111 (21:53:05 GMT-0400 (Eastern Daylight Time))
2019-09-29 21:53:05:112 - [debug] [XCUITest] Checking whether app '/Users/test/test.app' is actually present on file system
2019-09-29 21:53:05:112 - [debug] [XCUITest] App is present
2019-09-29 21:53:05:112 - [debug] [iOS] Getting bundle ID from app '/Users/test/test.app': 'com.test.test.development'
2019-09-29 21:53:05:112 - [debug] [BaseDriver] Event 'resetStarted' logged at 1569808385112 (21:53:05 GMT-0400 (Eastern Daylight Time))
2019-09-29 21:53:05:112 - [debug] [XCUITest] Reset: noReset is on. Leaving simulator as is
2019-09-29 21:53:05:112 - [debug] [BaseDriver] Event 'resetComplete' logged at 1569808385112 (21:53:05 GMT-0400 (Eastern Daylight Time))
2019-09-29 21:53:05:222 - [XCUITest] Continuing without capturing device logs: iOS Simulator with udid 7A567ACA-404B-4CB8-BE37-2CB6E81E8352 is not running
2019-09-29 21:53:05:222 - [XCUITest] Setting up simulator
2019-09-29 21:53:05:223 - [debug] [iOS] No reason to set locale
2019-09-29 21:53:05:223 - [debug] [iOS] No iOS / app preferences to set
2019-09-29 21:53:05:223 - [debug] [iOS] Setting did not need to be updated
2019-09-29 21:53:05:223 - [debug] [iOSSim] Setting preferences of 7A567ACA-404B-4CB8-BE37-2CB6E81E8352 Simulator to {"ConnectHardwareKeyboard":false}
2019-09-29 21:53:05:223 - [debug] [iOSSim] Setting common Simulator preferences to {"RotateWindowWhenSignaledByGuest":true,"ConnectHardwareKeyboard":false}
2019-09-29 21:53:05:245 - [debug] [iOSSim] Updated 7A567ACA-404B-4CB8-BE37-2CB6E81E8352 Simulator preferences at '/Users/test/Library/Preferences/com.apple.iphonesimulator.plist' with {"DevicePreferences":{"7A567ACA-404B-4CB8-BE37-2CB6E81E8352":{"ConnectHardwareKeyboard":false}},"RotateWindowWhenSignaledByGuest":true,"ConnectHardwareKeyboard":false}
2019-09-29 21:53:05:385 - [debug] [iOSSim] Got Simulator UI client PID: 48783
2019-09-29 21:53:05:385 - [iOSSim] Booting Simulator with UDID 7A567ACA-404B-4CB8-BE37-2CB6E81E8352...
2019-09-29 21:55:05:984 - [XCUITest] Error: The simulator 7A567ACA-404B-4CB8-BE37-2CB6E81E8352 has failed to finish booting after 120s. Original status: SIGTERM
2019-09-29 21:55:05:985 - [XCUITest]     at startBootMonitor (/Users/test/appium_master/master/node_modules/node-simctl/lib/simctl.js:901:13)
2019-09-29 21:55:05:985 - [DevCon Factory] Releasing connections for 7A567ACA-404B-4CB8-BE37-2CB6E81E8352 device on any port number
2019-09-29 21:55:05:985 - [DevCon Factory] No cached connections have been found
2019-09-29 21:55:05:986 - [debug] [BaseDriver] Event 'newSessionStarted' logged at 1569808505986 (21:55:05 GMT-0400 (Eastern Daylight Time))
2019-09-29 21:55:05:986 - [debug] [W3C] Encountered internal error running command: Error: The simulator 7A567ACA-404B-4CB8-BE37-2CB6E81E8352 has failed to finish booting after 120s. Original status: SIGTERM
2019-09-29 21:55:05:986 - [debug] [W3C]     at startBootMonitor (/Users/test/appium_master/master/node_modules/node-simctl/lib/simctl.js:901:13)
2019-09-29 21:55:06:001 - [HTTP] <-- POST /wd/hub/session 500 121150 ms - 731
2019-09-29 21:55:06:001 - [HTTP]

**Comment by mykola-mokhnach** [comment]
I don't observe any problems here. The code tried to call `boot` command and then failed to detect simulator in booted state. In general the solution would be that if you'd like to control the simulator lifecycle on your own then don't mix it with Appium's lifecycle controller.
Although, feel free to open a PR if you find an issue there.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
