### ISSUE TITLE
AppiumDriver.getGeoLocation()  has not been implemented on iOS simulator

### ISSUE THREAD

**Issue by bearxc** [appium/appium#13347]
Appum :lastest maste
Java Client:7.0
iOS13 simulator 

I try to make call to get current geo location  on iOS simulator 
location = iOSDriver.location();

get following errors. 

2019-10-02 15:23:15:045 - [HTTP] --> GET /wd/hub/session/024bd3b4-9d14-4abc-98f2-be5d1d31d306/location
2019-10-02 15:23:15:046 - [HTTP] {}
2019-10-02 15:23:15:046 - [debug] [W3C (024bd3b4)] Calling AppiumDriver.getGeoLocation() with args: ["024bd3b4-9d14-4abc-98f2-be5d1d31d306"]
2019-10-02 15:23:15:047 - [debug] [XCUITest] Executing command 'getGeoLocation'
2019-10-02 15:23:15:049 - [debug] [W3C (024bd3b4)] Encountered internal error running command: NotYetImplementedError: Method has not yet been implemented
2019-10-02 15:23:15:050 - [debug] [W3C (024bd3b4)]     at XCUITestDriver.executeCommand (/Users/test/appium_master/master/node_modules/appium-base-driver/lib/basedriver/driver.js:318:13)
2019-10-02 15:23:15:052 - [debug] [W3C (024bd3b4)]     at XCUITestDriver.executeCommand (/Users/test/appium_master/master/node_modules/appium-xcuitest-driver/lib/driver.js:702:24)
2019-10-02 15:23:15:052 - [debug] [W3C (024bd3b4)]     at AppiumDriver.executeCommand (/Users/test/appium_master/master/lib/appium.js:496:36)
2019-10-02 15:23:15:052 - [debug] [W3C (024bd3b4)]     at process.internalTickCallback (internal/process/next_tick.js:77:7)
2019-10-02 15:23:15:053 - [HTTP] <-- GET /wd/hub/session/024bd3b4-9d14-4abc-98f2-be5d1d31d306/location 404 8 ms - 601
2019-10-02 15:23:15:053 - [HTTP]

**Comment by mykola-mokhnach** [comment]
This is expected. Unfortunately, Apple does not provide any simple ways to make that possible.
