### ISSUE TITLE
Could not run applesimutils

### ISSUE THREAD

**Issue by Phoenix124** [appium/appium#13343]
## The problem

Hello
see some problem
Could not run tests applesimutils binary has not been found in your PATH

## Environment

<img width="1368" alt="Снимок экрана 2019-10-02 в 16 01 10" src="https://user-images.githubusercontent.com/19951392/66048764-cfdcf280-e532-11e9-8713-404efa550294.png">

## Details

Tests running via gradle but with maven everything is ok

## Link to Appium logs

```
debug] [XCUITest] Setting the requested permissions before WDA is started
[XCUITest] Error: applesimutils binary has not been found in your PATH. Please install it ('brew tap wix/brew && brew install wix/brew/applesimutils') to be able to change application permissions
[XCUITest]     at execWix (/usr/local/lib/node_modules/appium/node_modules/appium-ios-simulator/lib/permissions.js:42:11)
[DevCon Factory] Releasing connections for FE015887-3BC6-4AB7-9693-13947650AD93 device on any port number
[DevCon Factory] No cached connections have been found
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1570023231033 (16:33:51 GMT+0300 (Moscow Standard Time))
[debug] [MJSONWP] Encountered internal error running command: Error: applesimutils binary has not been found in your PATH. Please install it ('brew tap wix/brew && brew install wix/brew/applesimutils') to be able to change application permissions
[debug] [MJSONWP]     at execWix (/usr/local/lib/node_modules/appium/node_modules/appium-ios-simulator/lib/permissions.js:42:11)
[HTTP] <-- POST /wd/hub/session 500 4368 ms - 314
[HTTP] 
```

**Comment by mykola-mokhnach** [comment]
Is `/usr/local/bin` present in PATH environment variable passed to Appium process?

**Comment by Phoenix124** [comment]
@mykola-mokhnach fix it
