### ISSUE TITLE
UiautomatorViewer Issue- Ubuntu 18.4

### ISSUE THREAD

**Issue by PRATHEEKSHETTY** [appium/appium#13394]
## The problem  

Upon Running Uiautomatorviewer from the command prompt, i am getting the below errors.

Gdk-WARNING **: 14:34:41.467: The GDK_NATIVE_WINDOWS environment variable is not supported in GTK3.
See the documentation for gdk_window_ensure_native() on how to get native windows.
Exception in thread "main" java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	no swt-cairo-gtk-4919 in java.library.path
	no swt-cairo-gtk in java.library.path
	Can't load library: /usr/lib/jni/libswt-cairo-gtk-4919.so
	Can't load library: /usr/lib/jni/libswt-cairo-gtk.so
	Can't load library: /home/pavithra/.swt/lib/linux/x86_64/libswt-cairo-gtk-4919.so
	Can't load library: /home/pavithra/.swt/lib/linux/x86_64/libswt-cairo-gtk.so

	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:334)
	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:242)
	at org.eclipse.swt.internal.cairo.Cairo.<clinit>(Cairo.java:28)
	at org.eclipse.swt.widgets.Display.createDisplay(Display.java:1059)
	at org.eclipse.swt.widgets.Display.create(Display.java:1025)
	at org.eclipse.swt.graphics.Device.<init>(Device.java:179)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:590)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:581)
	at org.eclipse.swt.widgets.Display.getDefault(Display.java:2450)
	at org.eclipse.swt.widgets.Shell.<init>(Shell.java:271)
	at org.eclipse.swt.widgets.Shell.<init>(Shell.java:370)
	at org.eclipse.jface.window.Window.createShell(Window.java:487)
	at org.eclipse.jface.window.Window.create(Window.java:430)
	at org.eclipse.jface.window.Window.open(Window.java:790)
	at com.android.uiautomator.UiAutomatorViewer.main(UiAutomatorViewer.java:76)

**Comment by mykola-mokhnach** [comment]
Unfortunately the UiautomatorViewer tool is not part of Appium toolchain, so we cannot fix anything there. Please report the problem to Google or use Appium Desktop to inspect your apps.
