### ISSUE TITLE
Appium 1.15 installApp failure crashes appium

### ISSUE THREAD

**Issue by bennid** [appium/appium#13412]
## The problem

Unsure of the state of our app under test, but something appeared wrong with it.  The bad part is that appium just crashed with the error.

## Details
`2019-10-09 16:05:24:854 - uncaughtException: ENOENT: no such file or directory, open '/var/folders/ll/brhhr98d59j9yjzm3fmjbssw0000gp/T/201999-7374-1bith4f.lgw/Payload/MyApp.app/APDApplePayTourGradeCell.nib/objects-12.3+.nib'`

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15
* Last Appium version that did not exhibit the issue (if applicable): unknown
* Desktop OS/version used to run Appium: osx 10.14.6
* Node.js version (unless using Appium.app|exe): v12.10.0
* Npm or Yarn package manager: 5.6.0
* Mobile platform/version under test: iOS 13.2.1
* XCode version: 11.1
* Real device or emulator/simulator: iPhone Xr
* Appium CLI or Appium.app|exe: CLI

NOTE: We have 4 iPhones running separate appium instances for each on this same server (different ports etc...) running in a selenium grid.  Unsure if the "reusing previously downloaded application" would potentially use a downloaded file from one of the other appium uses

## Link to appium log
https://gist.github.com/bennid/d109f4b0bc1808276241249a91e8265c

## Code To Reproduce Issue [ Good To Have ]

Unsure how to reproduce it... it's a bad app build imo (still researching)... but appium shoudn't crash in this instance

**Comment by mykola-mokhnach** [comment]
Appium normally caches downloaded and unarchived applications to not spend time for downloading/unarchiving for the following runs. Each server instance maintains its own applications cache of applications, which could have up to 100 items. These applications are stored in temporary files and only get deleted if the count of items is above 100. Also the oldest items are deleted in the first priority (this is LRU cache).

In general I don't think there might be any issues where one server instance affects the other, although it might be that the operating system itself might decide to perform selective temporary files cleanup and thus corrupt the cache. The temporary solution might be to manually remove the root of the cached item in temp files, so appium knows it should be unpacked once again. Or restart the process, so the whole cache is reset.

You can check https://github.com/appium/appium-base-driver/blob/master/lib/basedriver/helpers.js for more details on the actual implementation

**Comment by mykola-mokhnach** [comment]
> it's a bad app build imo (still researching)

I also tend to think it is some issue with the app itself, although, like I said, the cache should be properly updated as soon as `Last-Modified` attribute is changed

**Comment by bennid** [comment]
I do believe you that the app itself may have an issue... however this shouldn't cause the appium instance to crash... but just fail the session POST

**Comment by mykola-mokhnach** [comment]
@imurchie Is it possible to handle such uncaught exception to prevent node process from being killed?

**Comment by mykola-mokhnach** [comment]
cc @umutuzgur

**Comment by umutuzgur** [comment]
It seems like the app path is deleted on the host by another process while it is being pushed to the device. I will checkout why the process is dying. I can't see any reason directly why this is happening

**Comment by bennid** [comment]
This seems to have happened again.  We're going to rollback to 1.14.2 (where we didn't see this) until this is resolved.

**Comment by bennid** [comment]
Actually... we've upgraded our phones to iOS 13.1.2, so we cannot roll back...  Please let us know asap if there's a beta we can test with.

**Comment by mykola-mokhnach** [comment]
Can you please try if the patch https://github.com/appium/appium-support/pull/135 works for you?

**Comment by bennid** [comment]
Rejected the diff for fs.js

**Comment by mykola-mokhnach** [comment]
Sorry, I don't get the meaning of the recent comment. Please use [this](https://github.com/appium/appium/issues/13227#issuecomment-531812534) tutorial in order to deploy the PR content properly to your local appium source (it's about webdriver agent, but you could do similar steps for appium-support)

**Comment by mykola-mokhnach** [comment]
The change has been recently published to appium@beta

**Comment by bennid** [comment]
I tried this on 1.16.0-beta.1 and just had an issue installing.  The same app installs perfectly fine with 1.15.0

https://github.com/appium/appium/issues/13453

**Comment by mykola-mokhnach** [comment]
We'll keep https://github.com/appium/appium/issues/13453 open to track this issue

**Comment by adiyarimi** [comment]
@mykola-mokhnach  so currently there is no way to run appium with ios 13.x ?
which appium version is a stable one that I can use for 1os 13.x ?

**Comment by bennid** [comment]
This is still happening on 1.16.0-rc.1.  We have 4 appium instances hosting 4 different iPhones for this install which may be affecting this.  Also this is still causing appium to crash, making our iPhones unusable.

```
2019-12-10 02:34:23:108 - [BaseDriver] Using downloadable app 'http://myserver.com:8000/files/mycompany-prerelease-1-34.5-191209026.ipa'
2019-12-10 02:34:23:146 - [debug] [BaseDriver] App Last-Modified: Tue, 10 Dec 2019 02:00:26 GMT
2019-12-10 02:34:23:150 - [BaseDriver] Reusing previously downloaded application at '/var/folders/ll/brhhr98d59j9yjzm3fmjbssw0000gp/T/2019119-79497-nq4b96.aoxjh/Payload/MyCompany.app'
2019-12-10 02:34:23:151 - [XCUITest] Installing '/var/folders/ll/brhhr98d59j9yjzm3fmjbssw0000gp/T/2019119-79497-nq4b96.aoxjh/Payload/MyCompany.app' to the real device with UDID 00008020-XXXXXXXX
2019-12-10 02:34:24:512 - [HTTP] --> GET /wd/hub/status
2019-12-10 02:34:24:512 - [HTTP] {}
2019-12-10 02:34:24:513 - [debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
2019-12-10 02:34:24:513 - [debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.16.0-rc.1"}}
2019-12-10 02:34:24:515 - [HTTP] <-- GET /wd/hub/status 200 2 ms - 73
2019-12-10 02:34:24:515 - [HTTP] 
2019-12-10 02:34:29:518 - [HTTP] --> GET /wd/hub/status
2019-12-10 02:34:29:519 - [HTTP] {}
2019-12-10 02:34:29:519 - [debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
2019-12-10 02:34:29:519 - [debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.16.0-rc.1"}}
2019-12-10 02:34:29:520 - [HTTP] <-- GET /wd/hub/status 200 1 ms - 73
2019-12-10 02:34:29:520 - [HTTP] 
2019-12-10 02:34:34:526 - [HTTP] --> GET /wd/hub/status
2019-12-10 02:34:34:527 - [HTTP] {}
2019-12-10 02:34:34:528 - [debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
2019-12-10 02:34:34:528 - [debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.16.0-rc.1"}}
2019-12-10 02:34:34:529 - [HTTP] <-- GET /wd/hub/status 200 2 ms - 73
2019-12-10 02:34:34:529 - [HTTP] 
2019-12-10 02:34:39:564 - [HTTP] --> GET /wd/hub/status
2019-12-10 02:34:39:565 - [HTTP] {}
2019-12-10 02:34:39:565 - [debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
2019-12-10 02:34:39:566 - [debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.16.0-rc.1"}}
2019-12-10 02:34:39:568 - [HTTP] <-- GET /wd/hub/status 200 4 ms - 73
2019-12-10 02:34:39:568 - [HTTP] 
2019-12-10 02:34:43:884 - [XCUITest] Falling back to ios-deploy usage
2019-12-10 02:34:43:885 - [XCUITest] Error: Cound't finish the operation "Open file 'PublicStaging/MyCompany.app/FormsResources.bundle/de-AT.lproj/Localizable.strings'". Failed to receive any data within the timeout: 10000
2019-12-10 02:34:43:885 - [XCUITest]     at Timeout._onTimeout (/Users/jenkins/build_tools/ios_phone/00008020-XXXXXXXX/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-ios-device/lib/afc/index.js:318:31)
2019-12-10 02:34:43:885 - [XCUITest]     at listOnTimeout (internal/timers.js:531:17)
2019-12-10 02:34:43:885 - [XCUITest]     at processTimers (internal/timers.js:475:7)
2019-12-10 02:34:44:576 - [HTTP] --> GET /wd/hub/status
2019-12-10 02:34:44:577 - [HTTP] {}
2019-12-10 02:34:44:577 - [debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
2019-12-10 02:34:44:577 - [debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.16.0-rc.1"}}
2019-12-10 02:34:44:579 - [HTTP] <-- GET /wd/hub/status 200 2 ms - 73
2019-12-10 02:34:44:579 - [HTTP] 
2019-12-10 02:34:47:562 - [Support] Got an error while walking '/var/folders/ll/brhhr98d59j9yjzm3fmjbssw0000gp/T/2019119-79497-nq4b96.aoxjh/Payload/MyCompany.app/icon_map_toolbar_my_location@2x.png': ENOENT: no such file or directory, stat '/var/folders/ll/brhhr98d59j9yjzm3fmjbssw0000gp/T/2019119-79497-nq4b96.aoxjh/Payload/MyCompany.app/icon_map_toolbar_my_location@2x.png'
2019-12-10 02:34:47:565 - uncaughtException: ENOENT: no such file or directory, open '/var/folders/ll/brhhr98d59j9yjzm3fmjbssw0000gp/T/2019119-79497-nq4b96.aoxjh/Payload/MyCompany.app/icon_hotel_amenity_ski_in_ski_out_60_gray@2x.png'
Error: ENOENT: no such file or directory, open '/var/folders/ll/brhhr98d59j9yjzm3fmjbssw0000gp/T/2019119-79497-nq4b96.aoxjh/Payload/MyCompany.app/icon_hotel_amenity_ski_in_ski_out_60_gray@2x.png'
```

**Comment by bennid** [comment]
note: this is using the install_app endpoint (we startup with running settings, as we need to do some pre-install steps before installing our app)

**Comment by yadavsvmx** [comment]
When is this fix going to be released ?

**Comment by bennid** [comment]
NOTE: This is fixed in latest appium-1.16.beta.3 and additional sub-module npm package updates (unsure which one fixed it though).

**Comment by adiyarimi** [comment]
currently we use appium 1.16.0 and it works without any issues with ios 13

**Comment by yadavsvmx** [comment]
> currently we use appium 1.16.0 and it works without any issues with ios 13

When is the 1.16.0 version releasing ?

**Comment by bennid** [comment]
It's already released

**Comment by yadavsvmx** [comment]
No appium desktop 1.16 was rolled back after release

**Comment by adiyarimi** [comment]
Im not using the desktop version on my mac
