### ISSUE TITLE
appium crashes on error uncaughtException: write EPIPE

### ISSUE THREAD

**Issue by wbulba** [appium/appium#13451]
appium v1.15.1
macOS: 10.15
Xcode: 11.1

after update appium for version 1.15.1 - appium crash on random time, it can still work 15 minutes after start or 2 minutes

in log appium a see 2 error for 2 different cases crashes:

~~~
===================================
[35m[HTTP]ESC[39m ESC[90mESC[39m
[debug] ESC[35m[XCUITest]ESC[39m Pushed the app files successfully after 143407ms
uncaughtException: write EPIPE
Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:87:16)
ESC[35m[XCUITest]ESC[39m Error was thrown during the installation process
ESC[35m[XCUITest]ESC[39m Error: Unexpected data: {"Error":"ApplicationVerificationFailed","ErrorDetail":-1,"ErrorDescription":"Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.RxjdBv/extracted/TestApp.app/Frameworks/Lottie.framework : 0xe8008001 (An unknown error has occurred.)"}
ESC[35m[XCUITest]ESC[39m     at InstallationProxyService._isFinished (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-ios-device/lib/installation-proxy/index.js:132:13)
ESC[35m[XCUITest]ESC[39m     at InstallationProxyService._isFinished [as _waitMessageCompletion] (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-ios-device/lib/installation-proxy/index.js:124:16)
ESC[35m[XCUITest]ESC[39m     at InstallationProxyService.installApplication (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-ios-device/lib/installation-proxy/index.js:24:12)
ESC[35m[XCUITest]ESC[39m     at IOSDeploy.installApplication (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/ios-deploy.js:52:7)
ESC[35m[XCUITest]ESC[39m     at IOSDeploy.install (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/ios-deploy.js:37:7)
ESC[35m[XCUITest]ESC[39m     at installToRealDevice (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/real-device-management.js:60:3)
ESC[35m[XCUITest]ESC[39m     at XCUITestDriver.installAUT (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:1128:7)
ESC[35m[XCUITest]ESC[39m     at XCUITestDriver.start (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:415:7)
ESC[35m[XCUITest]ESC[39m     at XCUITestDriver.createSession (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:214:7)
ESC[35m[XCUITest]ESC[39m     at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:353:35)
ESC[35m[XCUITest]ESC[39m     at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:376:13)
ESC[35m[XCUITest]ESC[39m     at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/lib/appium.js:482:14)
ESC[35m[XCUITest]ESC[39m     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:306:21)
ESC[35m[XCUITest]ESC[39m Error: Could not install app: 'Unexpected data: {"Error":"ApplicationVerificationFailed","ErrorDetail":-1,"ErrorDescription":"Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.RxjdBv/extracted/TestApp.app/Frameworks/Lottie.framework : 0xe8008001 (An unknown error has occurred.)"}'
ESC[35m[XCUITest]ESC[39m     at IOSDeploy.install (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/ios-deploy.js:41:13)
ESC[35m[DevCon Factory]ESC[39m Releasing connections for 0daf69ca81e3f01038387e3b497c26fac098ec3b device on any port number
ESC[35m[DevCon Factory]ESC[39m No cached connections have been found
[debug] ESC[35m[BaseDriver]ESC[39m Event 'newSessionStarted' logged at 1571387655919 (11:34:15 GMT+0300 (Moscow Standard Time))
[debug] ESC[35m[W3C]ESC[39m Encountered internal error running command: Error: Could not install app: 'Unexpected data: {"Error":"ApplicationVerificationFailed","ErrorDetail":-1,"ErrorDescription":"Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.RxjdBv/extracted/TestApp.app/Frameworks/Lottie.framework : 0xe8008001 (An unknown error has occurred.)"}'
[debug] ESC[35m[W3C]ESC[39m     at IOSDeploy.install (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/ios-deploy.js:41:13)
ESC[35m[HTTP]ESC[39m ESC[37m-->ESC[39m ESC[37mGETESC[39m ESC[37m/wd/hub/statusESC[39m
ESC[35m[HTTP]ESC[39m ESC[90m{}ESC[39m
[debug] ESC[35m[GENERIC]ESC[39m Calling AppiumDriver.getStatus() with args: []
[debug] ESC[35m[GENERIC]ESC[39m Responding to client with driver.getStatus() result: {"build":{"version":"1.15.1"}}
ESC[35m[HTTP]ESC[39m ESC[37m<-- GET /wd/hub/status ESC[39mESC[32m200ESC[39m ESC[90m1 ms - 68ESC[39m
ESC[35m[HTTP]ESC[39m ESC[90mESC[39m
===================================
~~~

~~~
===================================
[debug] ESC[35m[XCUITest]ESC[39m Installing '/opt/build-ios/ios/buildAutotestApplication/Build/Products/Debug-iphoneos/TestApp.app' on device with UUID 'aca24b2919ee80760f427d16698e97cec5055eeb'...
uncaughtException: write EPIPE
Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:87:16)
ESC[35m[HTTP]ESC[39m ESC[37m-->ESC[39m ESC[37mGETESC[39m ESC[37m/wd/hub/statusESC[39m
ESC[35m[HTTP]ESC[39m ESC[90m{}ESC[39m
[debug] ESC[35m[GENERIC]ESC[39m Calling AppiumDriver.getStatus() with args: []
[debug] ESC[35m[GENERIC]ESC[39m Responding to client with driver.getStatus() result: {"build":{"version":"1.15.1"}}
ESC[35m[HTTP]ESC[39m ESC[37m<-- GET /wd/hub/status ESC[39mESC[32m200ESC[39m ESC[90m4 ms - 68ESC[39m
ESC[35m[HTTP]ESC[39m ESC[90mESC[39m
===================================
~~~

**Comment by wbulba** [comment]
+ one more crashe
~~~
[debug] ESC[35m[iOS]ESC[39m Getting bundle ID from app '/opt/build-ios/ios/buildAutotestApplication/Build/Products/Debug-iphoneos/TestApp.app': 'com.testapp.testapp'
[debug] ESC[35m[BaseDriver]ESC[39m Event 'resetStarted' logged at 1571388773943 (11:52:53 GMT+0300 (Moscow Standard Time))
[debug] ESC[35m[XCUITest]ESC[39m Reset: running ios real device reset flow
[debug] ESC[35m[BaseDriver]ESC[39m Event 'resetComplete' logged at 1571388773943 (11:52:53 GMT+0300 (Moscow Standard Time))
uncaughtException: The frame is bigger than expected. Length: 544498511, max: 1000000
Error: The frame is bigger than expected. Length: 544498511, max: 1000000
    at LengthBasedSplitter._decode (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-ios-device/lib/util/transformer/length-based-splitter.js:38:13)
    at LengthBasedSplitter._decode [as _transform] (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-ios-device/lib/util/transformer/length-based-splitter.js:19:48)
    at LengthBasedSplitter.Transform._read (_stream_transform.js:189:10)
    at LengthBasedSplitter.Transform._write (_stream_transform.js:177:12)
    at doWrite (_stream_writable.js:428:12)
    at writeOrBuffer (_stream_writable.js:412:5)
    at LengthBasedSplitter.Writable.write (_stream_writable.js:302:11)
    at Socket.ondata (_stream_readable.js:722:22)
    at Socket.emit (events.js:209:13)
    at addChunk (_stream_readable.js:305:12)
    at readableAddChunk (_stream_readable.js:286:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:182:23)
[debug] ESC[35m[XCUITest]ESC[39m Crash reports root '/Users/test/Library/Logs/CrashReporter/MobileDevice/iPhone (TestApp)' does not exist. Got nothing to gather.
[debug] ESC[35m[BaseDriver]ESC[39m Event 'logCaptureStarted' logged at 1571388774231 (11:52:54 GMT+0300 (Moscow Standard Time))
ESC[35m[XCUITest]ESC[39m Setting up real device
[debug] ESC[35m[XCUITest]ESC[39m Verifying application platform
[debug] ESC[35m[XCUITest]ESC[39m CFBundleSupportedPlatforms: ["iPhoneOS"]
[debug] ESC[35m[XCUITest]ESC[39m Installing '/opt/build-ios/ios/buildAutotestApplication/Build/Products/Debug-iphoneos/TestApp.app' on device with UUID '6e438e9bb3cf23d9e9619607b318ed06acd23119'...
~~~

**Comment by uksahoo** [comment]
Test set Up:
Mac OS: 10.14.6
Appium: 1.13.0
Xcode: 10.2.1
Mobile: iPhone 8Plus (Version:11.4)

I am getting the same error "An unknown server-side error occurred while processing the command. Original error: write EPIPE", when trying to inspect element through Appium Inspector.
Once I am restarting my Mac the issue is getting solved only for one Test Case execution. Then from next executions it is throwing below error in console:

[35m[XCUITest][39m Error: Unknown device or simulator UDID: '6d47c0**********0091b'
[35m[XCUITest][39m     at XCUITestDriver.determineDevice (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:791:17)
[35m[XCUITest][39m     at XCUITestDriver.start (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:267:40)
[35m[XCUITest][39m     at XCUITestDriver.createSession (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:208:7)
[35m[XCUITest][39m     at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:362:35)
[35m[XCUITest][39m     at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:323:13)
[35m[XCUITest][39m     at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/lib/appium.js:491:14)
[35m[XCUITest][39m     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:352:21)

**Comment by mykola-mokhnach** [comment]
@wbulba Is the problem still reproducible with appium@beta?

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by bennid** [comment]
@mykola-mokhnach this was reproduced with beta.3

2019-12-19 02:48:58:423 - uncaughtException: write EPIPE
Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:87:16)
