### ISSUE TITLE
Question about ECONNRESET

### ISSUE THREAD

**Issue by singleboat** [appium/appium#13496]
# Problem Description
This exception(ECONNRESET) happens frequently during using appium, here is a part of log related to it
```
2019-10-27 07:49:58:232 [HTTP] --> GET /wd/hub/session/2b9198f8-760c-4268-9947-a5fd33c71198/source
2019-10-27 07:49:58:232 [HTTP] {}
2019-10-27 07:49:58:233 [W3C (2b9198f8)] Driver proxy active, passing request on via HTTP proxy
2019-10-27 07:49:58:234 [WD Proxy] Matched '/wd/hub/session/2b9198f8-760c-4268-9947-a5fd33c71198/source' to command name 'getPageSource'
2019-10-27 07:49:58:234 [WD Proxy] Proxying [GET /wd/hub/session/2b9198f8-760c-4268-9947-a5fd33c71198/source] to [GET http://localhost:8202/wd/hub/session/6171d915-18e9-4678-b355-a97d7f2888df/source] with body: {}
2019-10-27 07:49:58:237 [WD Proxy] Got an unexpected response with status undefined: {"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"}
2019-10-27 07:49:58:243 [W3C (2b9198f8)] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: Error: read ECONNRESET
2019-10-27 07:49:58:244 [W3C (2b9198f8)]     at doJwpProxy (C:\Users\xiazhzh\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:490:13)
2019-10-27 07:49:58:250 [HTTP] <-- GET /wd/hub/session/2b9198f8-760c-4268-9947-a5fd33c71198/source 500 17 ms - 785
```
#  Environment of Program
I run the program at Windows 10 to test Android application on both Huawei P9 and Sumsung S4. I test multiple application with creating new session in a loop, and driver.quit() is called on finishing of each app.
# Detail
In fact, this exception happens on different kinds of API, and it seems not related to specific driver's function, right? I feel that it happens at random. I have seen some similar issues recommended by github which say that it may be device-specific or due to the killed service of appium running in android by system. I want to make sure if it does have no solution to making my script running stably, because I'm trying to run an UI-based random test on multiple applications and obviously it is troublesome to stop and restart the program during the test.
By the way, I try to create a new session to solve this problem now while it still fails in some time. I want to know whether driver.quit() or some other function is needed to call even the connection seems to be crashed, because I see many adb.exe running in the background, and serval same info will be printed when I use taskkill to terminate all the progress named adb.exe.
Hope for any suggesstion, thanks very much.

**Comment by mykola-mokhnach** [comment]
This error means that Appium unexpectedly loses connection to the UIA2 agent running on the device. There might be multiple causes to this error like you've mentioned above, for example network or device/adb issues. Also, something worth checking is Doze mode, because Android itself might be terminating the connection to the server if it assumes it is being idle for longer time period.

The detailed logcat output for the period where connection is reset might also be useful.

**Comment by singleboat** [comment]
The log I paste above is all the log about the execution of driver.page_source, which throws the exception. The log brefore this part is debug info about driver.current_activity command which is executed successfully and the latter is about the creation of a new session after I catch the exception. Unfortunatly I have deleted previous log file, so addtional log info is not available now.
Does the log info mean that appium server received the command and forward it to my android device by http while received a response saying ECONNRESET? Does this response mean that the corressponding service doesn't exist in android background? Although the log refers to protocol.js, I think the code pointed to is just about catching of exception right?

**Comment by mykola-mokhnach** [comment]
Sorry, without the logcat output we cannot assume anything more. Did you try to exclude the Appium UIA2 server app from the Doze list?

**Comment by singleboat** [comment]
Here is some log info about ECONNRESET which is produced later.
# getStatus
```
2019-10-28 03:45:39:038 [UiAutomator2] Starting UIAutomator2 server 4.3.0
2019-10-28 03:45:39:039 [UiAutomator2] Using UIAutomator2 server from 'C:\Users\xiazhzh\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.3.0.apk' and test from 'C:\Users\xiazhzh\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk'
2019-10-28 03:45:39:039 [UiAutomator2] Waiting up to 30000ms for UiAutomator2 to be online...
2019-10-28 03:45:39:039 [ADB] Creating ADB subprocess with args: ["-P",5037,"-s","PBV0216803000315","shell","am","instrument","-w","io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner"]
2019-10-28 03:45:39:598 [Instrumentation] io.appium.uiautomator2.server.test.AppiumUiAutomator2Server:
2019-10-28 03:45:40:053 [WD Proxy] Matched '/status' to command name 'getStatus'
2019-10-28 03:45:40:055 [WD Proxy] Proxying [GET /status] to [GET http://localhost:8203/wd/hub/status] with no body
2019-10-28 03:45:40:060 [WD Proxy] Got an unexpected response with status undefined: {"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"}
2019-10-28 03:45:41:071 [WD Proxy] Matched '/status' to command name 'getStatus'
2019-10-28 03:45:41:071 [WD Proxy] Proxying [GET /status] to [GET http://localhost:8203/wd/hub/status] with no body
2019-10-28 03:45:41:091 [WD Proxy] Got response with status 200: {"sessionId":"None","value":{"ready":true,"message":"UiAutomator2 Server is ready to accept commands"}}
2019-10-28 03:45:41:091 [UiAutomator2] The initialization of the instrumentation process took 2053ms
```
This is the first and the most frequent exception log about ECONNRESET appearing in the log file, which is related to a command called "getStatus", but appium receieves a response with status 200 finally. I'm not sure whether this may have something with the latter exception.
# page_source
```
2019-10-28 03:50:28:000 [HTTP] --> GET /wd/hub/session/cd374460-2135-4f6d-8c7a-b5d94199b6a1/appium/device/current_activity
2019-10-28 03:50:28:001 [HTTP] {}
2019-10-28 03:50:28:001 [W3C (cd374460)] Calling AppiumDriver.getCurrentActivity() with args: ["cd374460-2135-4f6d-8c7a-b5d94199b6a1"]
2019-10-28 03:50:28:002 [ADB] Getting focused package and activity
2019-10-28 03:50:28:002 [ADB] Running 'D:\lib\android_sdk\platform-tools\adb.exe -P 5037 -s PBV0216803000315 shell dumpsys window windows'
2019-10-28 03:50:28:096 [W3C (cd374460)] Responding to client with driver.getCurrentActivity() result: ".ui.member.MemberDetailActivity"
2019-10-28 03:50:28:096 [HTTP] <-- GET /wd/hub/session/cd374460-2135-4f6d-8c7a-b5d94199b6a1/appium/device/current_activity 200 97 ms - 43
2019-10-28 03:50:28:097 [HTTP] 
2019-10-28 03:50:28:099 [HTTP] --> GET /wd/hub/session/cd374460-2135-4f6d-8c7a-b5d94199b6a1/source
2019-10-28 03:50:28:099 [HTTP] {}
2019-10-28 03:50:28:099 [W3C (cd374460)] Driver proxy active, passing request on via HTTP proxy
2019-10-28 03:50:28:100 [WD Proxy] Matched '/wd/hub/session/cd374460-2135-4f6d-8c7a-b5d94199b6a1/source' to command name 'getPageSource'
2019-10-28 03:50:28:100 [WD Proxy] Proxying [GET /wd/hub/session/cd374460-2135-4f6d-8c7a-b5d94199b6a1/source] to [GET http://localhost:8204/wd/hub/session/f9b3b565-1341-4b92-ba1b-ea797a0ee4fd/source] with body: {}
2019-10-28 03:50:28:104 [WD Proxy] Got an unexpected response with status undefined: {"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"}
2019-10-28 03:50:28:123 [W3C (cd374460)] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: Error: read ECONNRESET
2019-10-28 03:50:28:123 [W3C (cd374460)]     at doJwpProxy (C:\Users\xiazhzh\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:490:13)
2019-10-28 03:50:28:124 [HTTP] <-- GET /wd/hub/session/cd374460-2135-4f6d-8c7a-b5d94199b6a1/source 500 25 ms - 785
2019-10-28 03:50:28:124 [HTTP] 
2019-10-28 03:50:28:141 [HTTP] --> POST /wd/hub/session
2019-10-28 03:50:28:142 [HTTP] {"capabilities":{"firstMatch":[{"platformName":"Android","appium:automationName":"uiautomator2","appium:autoLaunch":false,"appium:disableAndroidWatchers":true,"appium:dontStopAppOnReset":true,"appium:newCommandTimeout":300,"appium:noSign":true,"appium:noReset":true,"appium:resetKeyboard":true,"appium:unicodeKeyboard":true,"appium:deviceName":"HUAWEI P9","appium:platformVersion":"7.0","appium:udid":"PBV0216803000315","appium:appPackage":"cn.xiaochuankeji.tieba","appium:appActivity":"cn.xiaochuankeji.tieba.ui.base.SplashActivity"}]},"desiredCapabilities":{"platformName":"Android","automationName":"uiautomator2","autoLaunch":false,"disableAndroidWatchers":true,"dontStopAppOnReset":true,"newCommandTimeout":300,"noSign":true,"noReset":true,"resetKeyboard":true,"unicodeKeyboard":true,"deviceName":"HUAWEI P9","platformVersion":"7.0","udid":"PBV0216803000315","appPackage":"cn.xiaochuankeji.tieba","appActivity":"cn.xiaochuankeji.tieba.ui.base.SplashActivity"}}
```
This part is same as the log I first pasted with more information before and after the ECONNRESET happening.
1. At first driver.current_activity is called and my device responses successfully.
2. Then driver.page_source is called and server receives a response with ECONNRESET.
3. My script catches this exception and begins to create a new session.

I think the first part is log about appium when ECONNRESET has not happened, and the last part is log after ECONNRESET happening and a new command begins to be executed, so this log should cover the process we care about.
Is there any more suggestion accorading to this? Thanks for response.

**Comment by singleboat** [comment]
And I have checked the setting about doze mode. I think power-saving mode is corressponding one in huawei rom, and it's not open. I'll use adb shell command to check the status of appium service, which may provide more information later.

**Comment by singleboat** [comment]
I was trapped at some other algorithm's bug in the last few days.
I have looked at the ps info in my device. Are _io.appium.settings_ and _io.appium.uiautomator2.server_ all the process needed to keep the appium working properly? 
Besides, since the log I provided before is considered not enough, is it useful  to provide all the log from the start of the session creation to the position refered to ECONNRESET? I think it may be too long .
Thanks.

**Comment by mykola-mokhnach** [comment]
> Besides, since the log I provided before is considered not enough, is it useful to provide all the log from the start of the session creation to the position refered to ECONNRESET? I think it may be too long .

We are talking here about the logcat output, not the Appium server log. Yes, it might be quite ago, although we only need the part of it, which matches in time with the first occurrence of connection reset event

**Comment by singleboat** [comment]
Does the "logcat output" mean the exception part log of my own code, or something else except the appium server log? I think I have not gotten the point.

**Comment by mykola-mokhnach** [comment]
https://developer.android.com/studio/command-line/logcat

**Comment by mykola-mokhnach** [comment]
https://appiumpro.com/editions/53

**Comment by singleboat** [comment]
i"m sorry for my poor experience. I always treat _log_ same with _logcat_ subconciously. I'll go on the experiment to wait for the exception and catch the logcat info.

**Comment by singleboat** [comment]
I have collected some logcat output.
```
11-04 13:09:23.309 28835 29448 I appium  : channel read invoked!
11-04 13:09:23.309 28835 29448 I appium  : channel read: POST /wd/hub/session/1c358a25-bda8-454c-beda-2b64ba2b76ac/element/9943d5e2-76cd-481d-a440-a9e88c39bbb4/click
11-04 13:09:23.310 28835 29448 I appium  : Click element command
11-04 13:09:23.318  1226  1288 E Process : isHighLoadProcess: get cpu failed
11-04 13:09:23.318  1804  1891 I AppTypeRecognise: input front pkg: com.jd.jrapp is gps ignore app
11-04 13:09:23.320 28876 28876 I HwPointEventFilter: ACTION_DOWN has not handle
11-04 13:09:23.324 28835 29448 I appium  : Waiting up to 10000ms for device to be idle
11-04 13:09:23.324 28835 29448 I appium  : AppiumResponse: {"sessionId":"1c358a25-bda8-454c-beda-2b64ba2b76ac","value":null}
11-04 13:09:24.351 28835 28856 I appium  : channel read invoked!
11-04 13:09:24.352 28835 28856 I appium  : channel read: DELETE /wd/hub/session/7e27b7a4-229d-4c7d-b372-112f2b5f65e3
11-04 13:09:24.353 28835 28856 I appium  : Delete session command
11-04 13:09:24.359 28835 28856 I appium  : Stopping uiautomator2 io.appium.uiautomator2.http io.appium.uiautomator2.server
11-04 13:09:24.364 28835 28856 I appium  : AppiumResponse: {"sessionId":"7e27b7a4-229d-4c7d-b372-112f2b5f65e3","value":null}
11-04 13:09:24.626 28835 28851 I TestRunner: finished: startServer(io.appium.uiautomator2.server.test.AppiumUiAutomator2Server)
......
11-04 13:09:31.430 30382 30382 W System  : ClassLoader referenced unknown path: /data/app/io.appium.uiautomator2.server.test-1/lib/arm64
......
11-04 13:09:31.581 30382 30398 I appium  : [AppiumUiAutomator2Server] Starting Server
......
```
My program catched WebDriverException during executing driver.page_source at 2019-11-04 13:09:26 (the error between my laptop and my phone seems to be less than 1 second according to my observation, so the time of the logcat should have reference value). After printing the time, a new driver is created.
```python
......
except WebDriverException:
    current_time = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())
    print('read ECONNREST during ' + func.__name__ + ' or get_log at ' + current_time)
    self.driver = self.create_driver()
```
It seems that the deleting of session happened at 11-04 13:09:24 should be the reason. Is there any suggestion? Is any more information needed?

**Comment by singleboat** [comment]
After I read more docs of appium and logcat info, I guess I have got the reason why ECONNRESET happened.
The first reason is about setting of 'autoWebviewTimeout', which I use a default value before.  Two seconds seems to be not enough. After I change it to 10 second, the time of ECONNRESET becomes less than before, especially for the condintion where re-creating a driver works to recover.
The second reason is that I do not realize _StaleElementReferenceException_ is subclass of _WebDriverException_. In fact I deal with _StaleElementReferenceException_ in another way, and treat all the _WebDriverException_ as ECONNRESET.
The third reason is that sometimes my device is still not idle after 10 seconds, which is default value for 'waitForIdleTimeout'. However, this default value should be reasonable. The logcat before the log hinting timeout of waiting device idle is about GC. It seems that this problem is device-specific or application-specific. I'll try to make the value of 'waitForIdleTimeout' longer and observe the further result.
By the way, sometimes error log of appium server is printed saying that the application is still alive after 500ms after calling of driver.terminate_app() and an exception is thrown. Is there any way to set the value of this in desired_capabilities or appium server?

**Comment by mykola-mokhnach** [comment]
> By the way, sometimes error log of appium server is printed saying that the application is still alive after 500ms after calling of driver.terminate_app() and an exception is thrown. Is there any way to set the value of this in desired_capabilities or appium server?

Please use Appium forum for questions.

Closed as not an issue

**Comment by dzajacapprentice** [comment]
Usually, this error means that WDA session is not closed correctly and you cannot connect again. I had it many times by running the tests on Github Actions Macos machines.
Simply add the command for cleaning of all ios simulators:

`xcrun simctl erase all`

After integrating this command as a part of the pipeline script - I have never had again the problem with ECONNRESET or similar.
