### ISSUE TITLE
[ANDROID] Unicode keyboard adb command fails sometimes 

### ISSUE THREAD

**Issue by Jiurong-Yang** [appium/appium#13491]
Like this title suggests. Sometime during an appium session instantiation the adb command to enable the unicode keyboard will randomly fail with an error code 255
```
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.15.1"}}
[HTTP] <-- GET /wd/hub/status 200 3 ms - 68
[HTTP] 
[ADB] The installation of 'settings_apk-debug.apk' took 2.071s
[debug] [ADB] Install command stdout: Success
[debug] [ADB] Getting IDs of all 'io.appium.settings' processes
[debug] [ADB] Running '/opt/android/platform-tools/adb -P 5037 -s ce03171321ca1b0503 shell 'pgrep --help; echo $?''
[debug] [ADB] Running '/opt/android/platform-tools/adb -P 5037 -s ce03171321ca1b0503 shell pgrep -f io\\.appium\\.settings'
[debug] [ADB] Running '/opt/android/platform-tools/adb -P 5037 -s ce03171321ca1b0503 shell am start -n io.appium.settings/.Settings -a android.intent.action.MAIN -c android.intent.category.LAUNCHER'
[debug] [ADB] Getting IDs of all 'io.appium.settings' processes
[debug] [ADB] Running '/opt/android/platform-tools/adb -P 5037 -s ce03171321ca1b0503 shell pgrep -f io\\.appium\\.settings'
[debug] [ADB] Getting IDs of all 'io.appium.settings' processes
[debug] [ADB] Running '/opt/android/platform-tools/adb -P 5037 -s ce03171321ca1b0503 shell pgrep -f io\\.appium\\.settings'
[debug] [ADB] Running '/opt/android/platform-tools/adb -P 5037 -s ce03171321ca1b0503 shell appops set io.appium.settings android\:mock_location allow'
[debug] [Logcat] Starting logcat capture
[debug] [AndroidDriver] Enabling Unicode keyboard support
[debug] [ADB] Running '/opt/android/platform-tools/adb -P 5037 -s ce03171321ca1b0503 shell settings get secure default_input_method'
[debug] [AndroidDriver] Unsetting previous IME com.sec.android.inputmethod/.SamsungKeypad
[debug] [AndroidDriver] Setting IME to 'io.appium.settings/.UnicodeIME'
[debug] [ADB] Running '/opt/android/platform-tools/adb -P 5037 -s ce03171321ca1b0503 shell ime enable io.appium.settings/.UnicodeIME'
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [ADB] Running '/opt/android/platform-tools/adb -P 5037 -s ce03171321ca1b0503 shell am force-stop com.hp.printercontrol.debug'
[debug] [UiAutomator2] Capability 'fullReset' set to 'true', Uninstalling 'com.hp.printercontrol.debug'
[debug] [ADB] Uninstalling com.hp.printercontrol.debug
[debug] [ADB] Getting install status for com.hp.printercontrol.debug
[debug] [ADB] Running '/opt/android/platform-tools/adb -P 5037 -s ce03171321ca1b0503 shell dumpsys package com.hp.printercontrol.debug'
[debug] [ADB] 'com.hp.printercontrol.debug' is not installed
[ADB] com.hp.printercontrol.debug was not uninstalled, because it was not present on the device
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Removing forwarded port socket connection: 10307 
[debug] [ADB] Running '/opt/android/platform-tools/adb -P 5037 -s ce03171321ca1b0503 forward --remove tcp\:10307'
[UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original error: 'Command '/opt/android/platform-tools/adb -P 5037 -s ce03171321ca1b0503 forward --remove tcp\:10307' exited with code 1'; Stderr: 'error: listener 'tcp:10307' not found'; Code: '1''
[UiAutomator2] Restoring hidden api policy to the device default configuration
[debug] [ADB] Running '/opt/android/platform-tools/adb -P 5037 -s ce03171321ca1b0503 shell settings delete global hidden_api_policy_pre_p_apps'
[debug] [ADB] Running '/opt/android/platform-tools/adb -P 5037 -s ce03171321ca1b0503 shell settings delete global hidden_api_policy_p_apps'
[debug] [ADB] Running '/opt/android/platform-tools/adb -P 5037 -s ce03171321ca1b0503 shell settings delete global hidden_api_policy'
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1571969533897 (19:12:13 GMT-0700 (Pacific Daylight Time))
[debug] [W3C] Encountered internal error running command: Error executing adbExec. Original error: 'Command '/opt/android/platform-tools/adb -P 5037 -s ce03171321ca1b0503 shell ime enable io.appium.settings/.UnicodeIME' exited with code 255'; Stderr: 'Exception occurred while executing:
[debug] [W3C] java.lang.IllegalArgumentException: Unknown id: com.sec.android.inputmethod/.SamsungKeypad
[debug] [W3C] 	at com.android.server.InputMethodManagerService.setInputMethodEnabledLocked(InputMethodManagerService.java:6096)
[debug] [W3C] 	at com.android.server.InputMethodManagerService.handleShellCommandEnableDisableInputMethod(InputMethodManagerService.java:8241)
[debug] [W3C] 	at com.android.server.InputMethodManagerService.access$4800(InputMethodManagerService.java:274)
[debug] [W3C] 	at com.android.server.InputMethodManagerService$ShellCommandImpl.onCommand(InputMethodManagerService.java:8032)
[debug] [W3C] 	at android.os.ShellCommand.exec(ShellCommand.java:103)
[debug] [W3C] 	at com.android.server.InputMethodManagerService.onShellCommand(InputMethodManagerService.java:7998)
[debug] [W3C] 	at android.os.Binder.shellCommand(Binder.java:642)
[debug] [W3C] 	at android.os.Binder.onTransact(Binder.java:540)
[debug] [W3C] 	at com.android.internal.view.IInputMethodManager$Stub.onTransact(IInputMethodManager.java:622)
[debug] [W3C] 	at com.android.server.InputMethodManagerService.onTransact(InputMethodManagerService.java:2386)
[debug] [W3C] 	at android.os.Binder.execTransact(Binder.java:739)'; Code: '255'
[debug] [W3C] Error: Command '/opt/android/platform-tools/adb -P 5037 -s ce03171321ca1b0503 shell ime enable io.appium.settings/.UnicodeIME' exited with code 255
[debug] [W3C]     at ChildProcess.proc.on.code (/usr/lib/node_modules/appium/node_modules/teen_process/lib/exec.js:113:19)
[debug] [W3C]     at ChildProcess.emit (events.js:198:13)
[debug] [W3C]     at maybeClose (internal/child_process.js:982:16)
[debug] [W3C]     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
[HTTP] <-- POST /wd/hub/session 500 8864 ms - 3113
[HTTP] 
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.15.1"}}
[HTTP] <-- GET /wd/hub/status 200 2 ms - 68
[HTTP] 
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.15.1"}}
[HTTP] <-- GET /wd/hub/status 200 2 ms - 68
[HTTP] 
[HTTP] --> GET /wd/hub/status
[HTTP] {}
--
[debug] [ADB] 'io.appium.settings' is installed
[debug] [ADB] Getting package info for 'io.appium.settings'
[debug] [ADB] Running '/opt/android/platform-tools/adb -P 5037 -s ce03171321ca1b0503 shell dumpsys package io.appium.settings'
[ADB] Using 'apkanalyzer' from '/opt/android/tools/bin/apkanalyzer'
[debug] [ADB] Starting '/opt/android/tools/bin/apkanalyzer' with args ["manifest","print","/usr/lib/node_modules/appium/node_modules/io.appium.settings/apks/settings_apk-debug.apk"]
[debug] [ADB] The version name of the installed 'io.appium.settings' is greater or equal to the application version name ('2.14.2' >= '2.14.2')
[debug] [ADB] There is no need to install/upgrade '/usr/lib/node_modules/appium/node_modules/io.appium.settings/apks/settings_apk-debug.apk'
[debug] [ADB] Getting IDs of all 'io.appium.settings' processes
[debug] [ADB] Running '/opt/android/platform-tools/adb -P 5037 -s ce03171321ca1b0503 shell 'pgrep --help; echo $?''
[debug] [ADB] Running '/opt/android/platform-tools/adb -P 5037 -s ce03171321ca1b0503 shell pgrep -f io\\.appium\\.settings'
[debug] [ADB] Running '/opt/android/platform-tools/adb -P 5037 -s ce03171321ca1b0503 shell am start -n io.appium.settings/.Settings -a android.intent.action.MAIN -c android.intent.category.LAUNCHER'
[debug] [ADB] Getting IDs of all 'io.appium.settings' processes
[debug] [ADB] Running '/opt/android/platform-tools/adb -P 5037 -s ce03171321ca1b0503 shell pgrep -f io\\.appium\\.settings'
[debug] [ADB] Getting IDs of all 'io.appium.settings' processes
[debug] [ADB] Running '/opt/android/platform-tools/adb -P 5037 -s ce03171321ca1b0503 shell pgrep -f io\\.appium\\.settings'
[debug] [ADB] Running '/opt/android/platform-tools/adb -P 5037 -s ce03171321ca1b0503 shell appops set io.appium.settings android\:mock_location allow'
[debug] [Logcat] Starting logcat capture
[debug] [AndroidDriver] Enabling Unicode keyboard support
[debug] [ADB] Running '/opt/android/platform-tools/adb -P 5037 -s ce03171321ca1b0503 shell settings get secure default_input_method'
[debug] [AndroidDriver] Unsetting previous IME com.sec.android.inputmethod/.SamsungKeypad
[debug] [AndroidDriver] Setting IME to 'io.appium.settings/.UnicodeIME'
[debug] [ADB] Running '/opt/android/platform-tools/adb -P 5037 -s ce03171321ca1b0503 shell ime enable io.appium.settings/.UnicodeIME'
[debug] [ADB] Running '/opt/android/platform-tools/adb -P 5037 -s ce03171321ca1b0503 shell ime set io.appium.settings/.UnicodeIME'
[UiAutomator2] Server package at '/usr/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v4.3.0.apk' is not writeable. Will copy it into the temporary location at '/tmp/2019924-11880-5ike3y.kc9n6' as a workaround. Consider making this file writeable manually in order to improve the performance of session startup.
[UiAutomator2] Server package at '/usr/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk' is not writeable. Will copy it into the temporary location at '/tmp/2019924-11880-5ike3y.kc9n6' as a workaround. Consider making this file writeable manually in order to improve the performance of session startup.
[debug] [ADB] Getting install status for io.appium.uiautomator2.server
[debug] [ADB] Running '/opt/android/platform-tools/adb -P 5037 -s ce03171321ca1b0503 shell dumpsys package io.appium.uiautomator2.server'
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.15.1"}}
[HTTP] <-- GET /wd/hub/status 200 3 ms - 68
[HTTP] 
[debug] [ADB] 'io.appium.uiautomator2.server' is not installed
[debug] [ADB] App '/tmp/2019924-11880-5ike3y.kc9n6/appium-uiautomator2-server-v4.3.0.apk' is not installed
[debug] [UiAutomator2] io.appium.uiautomator2.server installation state: notInstalled
[debug] [ADB] Checking app cert for /tmp/2019924-11880-5ike3y.kc9n6/appium-uiautomator2-server-v4.3.0.apk
[ADB] Using 'apksigner' from '/opt/android/build-tools/28.0.3/apksigner'
[debug] [ADB] Starting '/opt/android/build-tools/28.0.3/apksigner' with args '["verify","--print-certs","/tmp/2019924-11880-5ike3y.kc9n6/appium-uiautomator2-server-v4.3.0.apk"]'
[debug] [ADB] apksigner stdout: Signer #1 certificate DN: EMAILADDRESS=android@android.com, CN=Android, OU=Android, O=Android, L=Mountain View, ST=California, C=US
[debug] [ADB] Signer #1 certificate SHA-256 digest: a40da80a59d170caa950cf15c18c454d47a39b26989d8b640ecd745ba71bf5dc
[debug] [ADB] Signer #1 certificate SHA-1 digest: 61ed377e85d386a8dfee6b864bd85b0bfaa5af81
[debug] [ADB] Signer #1 certificate MD5 digest: e89b158e4bcf988ebd09eb83f5378e87
```

Appium Version: 1.15.1
Device OS Version: Android 9 
Device Manufacture: Samsung

I've seen this issue here and there on many different OS with many different Appium versions. I'm pretty sure a simple retry here would solve this weird issue.

PS: The next test that ran against this phone in our system started the driver session with no issues.

**Comment by Jiurong-Yang** [comment]
Actually found this thread. 
https://github.com/appium/io.appium.settings/issues/40
So I think it's an known issue just somehow this was closed without being fixed.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue.
I see nothing we can do on appium side to workaround the error
