### ISSUE TITLE
Getting Cannot get 'xml' source of the current application error on refreshing page source

### ISSUE THREAD

**Issue by faizanjaved** [appium/appium#13504]
## The problem

I am getting "Cannot get 'xml' source of the current application" error on refreshing page source in appium desktop on one page for a native application. 
The page has dynamic elements which are loaded on UI on a button click.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS mojave 10.14.6
* Node.js version (unless using Appium.app|exe): 12.10.0
* Npm or Yarn package manager: npm - 6.12.0
* Mobile platform/version under test: 13.1
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: CLI

## Details

Appium is taking about a minute to load one page on our native app.
This page has dynamic elements which are loaded on UI on a button click.
Appium fail to generate the page source once these elements are visible on UI.

## Link to Appium logs

Appium logs with showIOSLog and showXcodeLog caps: https://gist.github.com/faizanjaved/980c6ca01c648551fc97c34d17608590

**Comment by mykola-mokhnach** [comment]
I don't observe any errors in the attached log. Is it the correct one?

**Comment by faizanjaved** [comment]
> I don't observe any errors in the attached log. Is it the correct one?

Yes it is. View the full file and search "Cannot get 'xml' source of the current application"

**Comment by mykola-mokhnach** [comment]
Found it:

> [IOSSimulatorLog] [IOS_SYSLOG_ROW] 2019-10-29 12:51:21.593 E  testmanagerd[18589:4669b] [com.apple.dt.xctest:Default] XCTAS Error: XCTAutomationSupportErrorUnknownElement: Error getting main window kAXErrorIPCTimeout
> [IOSSimulatorLog] [IOS_SYSLOG_ROW] 2019-10-29 12:51:21.594 E  testmanagerd[18589:4669b] [com.apple.dt.xctest:Default] XCTAS Error: Error Domain=com.apple.dt.xctest.automation-support.error Code=8 "Error getting main window kAXErrorIPCTimeout" UserInfo={NSLocalizedDescription=Error getting main window kAXErrorIPCTimeout}
> [IOSSimulatorLog] [IOS_SYSLOG_ROW] 2019-10-29 12:51:21.594 E  testmanagerd[18589:496cd] [com.apple.dt.xctest:Default] XCTAS Error: Error Domain=com.apple.dt.xctest.automation-support.error Code=8 "Error getting main window kAXErrorIPCTimeout" UserInfo={NSLocalizedDescription=Error getting main window kAXErrorIPCTimeout}

The error is coming from XCTest itself and we cannot influence it from Appium side. 
What I would try: check your app using Xcode monitoring tools while it is showing that particular view. I was observing the situations where XCTest was not able to get a snapshot because the target app was never in idle state because of badly implemented view update logic.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue

**Comment by ansvijay** [comment]
Getting the same issue
The App is Native app and i have text box which has a text" Find a friend" . 
Device iPhoneXs - OS 13.1.2 and Appium 1.14

Exception (Exception handler)
Original error: Cannot get 'xml' source of the current application

Appium Logs

2019-11-26 05:27:55:103 - [debug] [MJSONWP] Matched JSONWP error code 13 to UnknownError
2019-11-26 05:27:55:103 - [debug] [BaseDriver] Waited for 4181 ms so far
2019-11-26 05:27:55:635 - [debug] [WD Proxy] Matched '/element' to command name 'findElement'
2019-11-26 05:27:55:636 - [debug] [WD Proxy] Proxying [POST /element] to [POST http://localhost:1802/session/3649F3F6-AFB3-4684-8452-D0CA9D2329D4/element] with body: {"using":"xpath","value":"//*[@*[contains(.,'Find a friend')]]"}
2019-11-26 05:27:57:565 - [debug] [WD Proxy] Got response with status 200: {"value":"Cannot evaluate results for XPath expression \"//*[@*[contains(.,'Find a friend')]]\"\n\n(\n\t0 CoreFoundation 0x00000001b9885c44 97285ACB-7B21-393A-ABF6-03F1DBB5D2A2 + 1256516\n\t1 libobjc.A.dylib 0x00000001b95a00c8 objc_exception_throw + 60\n\t2 WebDriverAgentLib 0x0000000102d55e14 +[FBXPath xmlStringWithRootElement:] + 0\n\t3 WebDriverAgentLib 0x0000000102d560a8 +[FBXPath matchesWithRootElement:forQuery:] + 368\n\t4 WebDriverAgentLib 0x0000000102d6ee98 -[XCUIElement(FBFind) fb_descendantsMatchingXPathQuery:shouldReturnAfterFirstMatch:] + 204\n\t5 WebDriverAgentLib 0x0000000102d93124 +[FBFindElementCommands elementsUsing:withValue:under:shouldReturnAfterFirstMatch:] + 968\n\t6 WebDriverAgentLib 0x0000000102d92cf8 +[FBFindElementCommands elementUsing:withValue:under:] + 156\n\t7 WebDriverAgentLib 0x0000000102d91bec +[FBFindElementCom...
2019-11-26 05:27:57:566 - [WD Proxy] Got an unexpected response: {"value":"Cannot evaluate results for XPath expression \"//*[@*[contains(.,'Find a friend')]]\"\n\n(\n\t0 CoreFoundation 0x00000001b9885c44 97285ACB-7B21-393A-ABF6-03F1DBB5D2A2 + 1256516\n\t1 libobjc.A.dylib 0x00000001b95a00c8 objc_exception_throw + 60...
2019-11-26 05:27:57:567 - [debug] [MJSONWP] Matched JSONWP error code 13 to UnknownError
2019-11-26 05:27:57:568 - [debug] [W3C (a2854690)] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
2019-11-26 05:27:57:568 - [debug] [W3C (a2854690)] at XCUITestDriver.doNativeFind (/Users/pbox/headspinio-pboxagent/appium/1.14.2/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:130:13)
2019-11-26 05:27:57:570 - [HTTP] <-- POST /wd/hub/session/a2854690-21b0-4cef-b9f5-e0ca8cd909eb/element 404 6651 ms - 411
2019-11-26 05:27:57:570 - [HTTP]
2019-11-26 05:27:57:602 - [HTTP] --> GET /wd/hub/session/a2854690-21b0-4cef-b9f5-e0ca8cd909eb/context
2019-11-26 05:27:57:602 - [HTTP] {}
2019-11-26 05:27:57:603 - [debug] [W3C (a2854690)] Calling AppiumDriver.getCurrentContext() with args: ["a2854690-21b0-4cef-b9f5-e0ca8cd909eb"]
2019-11-26 05:27:57:603 - [debug] [XCUITest] Executing command 'getCurrentContext'
2019-11-26 05:27:57:604 - [debug] [W3C (a2854690)] Responding to client with driver.getCurrentContext() result: "NATIVE_APP"
2019-11-26 05:27:57:605 - [HTTP] <-- GET /wd/hub/session/a2854690-21b0-4cef-b9f5-e0ca8cd909eb/context 200 2 ms - 22
2019-11-26 05:27:57:605 - [HTTP]

**Comment by ansvijay** [comment]
The same works fine on iPhone 8 with OS 12.2

**Comment by shivani-rana** [comment]
Hi,
Getting same issue with appium desktop 1.15.1 for iOS 13.3.
after doing refresh page source, "Cannot get 'xml' source of the current application error on refreshing page source"


I am not able load page for inspection. Could anyone pls help

logs :
Matched '/source' to command name 'getPageSource'
[debug] [WD Proxy] Proxying [GET /source] to [GET http://localhost:8100/session/6E9991CD-47DA-4C4B-9890-B63933A4FA01/source] with no body
[debug] [WD Proxy] Got response with status 500: {
[debug] [WD Proxy] "value" : {
[debug] [WD Proxy] "error" : "unknown error",
[debug] [WD Proxy] "message" : "Cannot get 'xml' source of the current application",
[debug] [WD Proxy] "traceback" : ""
[debug] [WD Proxy] },
[debug] [WD Proxy] "sessionId" : "6E9991CD-47DA-4C4B-9890-B63933A4FA01"
[debug] [WD Proxy] }
[debug] [W3C] Matched W3C error code 'unknown error' to UnknownError
[debug] [XCUITest] Taking screenshot with WDA
[debug] [WD Proxy] Matched '/screenshot' to command name 'getScreenshot'
[debug] [WD Proxy] Proxying [GET /screenshot] to [GET http://localhost:8100/session/6E9991CD-47DA-4C4B-9890-B63933A4FA01/screenshot] with no body
[debug] [MJSONWP (73907e02)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot get 'xml' source of the current application
[debug] [MJSONWP (73907e02)] at errorFromW3CJsonCode (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:802:25)
[debug] [MJSONWP (73907e02)] at ProxyRequestError.errorFromW3CJsonCode [as getActualError] (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:685:14)
[debug] [MJSONWP (73907e02)] at JWProxy.getActualError [as command] (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:259:19)

**Comment by kartikjain12** [comment]
Getting the same problem on a textBox with appium server 1.14.1 and ios 13.3. Using dot net client for appium 
OpenQA.Selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Cannot get 'xml' source of the current application
2019-12-31T02:34:19.0655450Z    at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
2019-12-31T02:34:19.0655480Z    at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
2019-12-31T02:34:19.0655520Z    at OpenQA.Selenium.Remote.RemoteWebDriver.get_PageSource()

**Comment by ansvijay** [comment]
Upgrade to Appium 1.15.x. It will solve the problem 

Regards, 
Vijay Jain

**Comment by kartikjain12** [comment]
@ansvijay How do you know this? Is this a known bug in 1.14.x. Upgrading the Appium server will not be so easy for me as I will have to go through heavy testing to make sure everything still works with 1.15.x.

**Comment by ansvijay** [comment]
Hi ,
I had the same issue and after update to 1.15.x it worked. I have tested on 1.15.x on iPhone 7,8, iphonX and xs and  didn’t encounter any issues. It’s completely safe.

Regards, 
Vijay Jain

**Comment by togo-darrel** [comment]
I have the same issue with appium 1.15.1. In my case it's a page containing a mapbox control

**Comment by mykola-mokhnach** [comment]
@togo-darrel You could try https://github.com/appium/appium/issues/13595#issuecomment-554256741 as workaround (the most recent Appium version should be installed)

**Comment by gwpetersenag** [comment]
I'm seeing this as well same issue

`info] [HTTP] <-- GET /wd/hub/session/fb525720-3df7-441d-b4e8-8e85b5827423 404 5 ms - 131
[info] [HTTP] 
[info] [HTTP] [37m-->[39m [37mGET[39m [37m/wd/hub/session/b9276ae2-664e-410d-9f52-8674c9b796b2[39m
[info] [HTTP] {}
[debug] [MJSONWP (b9276ae2)] Calling AppiumDriver.getSession() with args: ["b9276ae2-664e-410d-9f52-8674c9b796b2"]
[debug] [XCUITest] Executing command 'getSession'[error] [Xcode] 2020-01-07 10:28:05.859516-0800 WebDriverAgentRunner-Runner[36666:7196210] Failed to invoke libxml2>xmlTextWriterStartElement. Error code: -1
[error] [Xcode] 
[error] [Xcode] 2020-01-07 10:28:05.859701-0800 WebDriverAgentRunner-Runner[36666:7196210] Failed to generate XML presentation of a screen element
[error] [Xcode] 
[error] [Xcode] Entity: line 2: parser error : Extra content at the end of the document
[error] [Xcode] 
[error] [Xcode] ^
[error] [Xcode] 
[error] [Xcode] error : xmlTextWriterWriteDocCallback : XML error 5 !
[error] [Xcode] 
[debug] [WD Proxy] Got response with status 500: {
[debug] [WD Proxy]   "value" : {
[debug] [WD Proxy]     "error" : "unknown error",
[debug] [WD Proxy]     "message" : "Cannot get 'xml' source of the current application",
[debug] [WD Proxy]     "traceback" : ""
[debug] [WD Proxy]   },
[debug] [WD Proxy]   "sessionId" : "FA72E756-50A8-492B-95A3-9662396C91AE"
[debug] [WD Proxy] }
[debug] [W3C] Matched W3C error code 'unknown error' to UnknownError
[debug] [XCUITest] Taking screenshot with WDA
[debug] [WD Proxy] Matched '/screenshot' to command name 'getScreenshot'
[debug] [WD Proxy] Proxying [GET /screenshot] to [GET http://localhost:8100/session/FA72E756-50A8-492B-95A3-9662396C91AE/screenshot] with no body
[debug] [MJSONWP (b9276ae2)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot get 'xml' source of the current application
[debug] [MJSONWP (b9276ae2)]     at errorFromW3CJsonCode (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/appium-base-driver/lib/protocol/errors.js:780:25)
[debug] [MJSONWP (b9276ae2)]     at ProxyRequestError.errorFromW3CJsonCode [as getActualError] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/appium-base-driver/lib/protocol/errors.js:663:14)
[debug] [MJSONWP (b9276ae2)]     at JWProxy.getActualError [as command] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:259:19)
[info] [HTTP] <-- GET /wd/hub/session/b9276ae2-664e-410d-9f52-8674c9b796b2/source 500 93814 ms - 221
[info] [HTTP] [debug] [WD Proxy] Got response with status 200: {
[debug] [WD Proxy]   "value" : "iVBORw0KGgoAAAANSUhEUgAABNoAAAqACAIAAAD2w8zRAAAAAXNSR0IArs4c6QAA\r\nABxpRE9UAAAAAgAAAAAAAAVAAAAAKAAABUAAAAVAAAa9gX1trU4AAEAASURBVHgB\r\n7J0HnF1VubdPyqSTRq9SREAuWEC9fl4Vu4IIoV8bildFEe9VgZSZTE3vddIIvQVQ\r\nlN4SQkJv0nsPEFKmnN7P\/p6135mdk4QJM8mEM4H\/\/BaLdfZZe5Xn7LXz\/`

appium verison 1.10.1
xcode Version 11.1

**Comment by togo-darrel** [comment]
Thanks @mykola-mokhnach .. upgrading to 1.16.0 fixed it for me 😊. FYI, the main issue I was running into was the appium inspector hanging on one of my app pages since it does getPageSource() to populate the inspector.
