### ISSUE TITLE
Unable to open links in IOS

### ISSUE THREAD

**Issue by VT1Karthik** [appium/appium#13539]
[WD Proxy] Got response with status 200: {
[WD Proxy]   "value" : {
[WD Proxy]     "message" : "WebDriverAgent is ready to accept commands",
[WD Proxy]     "state" : "success",
[WD Proxy]     "os" : {
[WD Proxy]       "name" : "iOS",
[WD Proxy]       "version" : "13.2",
[WD Proxy]       "sdkVersion" : "13.0"
[WD Proxy]     },
[WD Proxy]     "ios" : {
[WD Proxy]       "simulatorVersion" : "13.2",
[WD Proxy]       "ip" : "192.168.1.65"
[WD Proxy]     },
[WD Proxy]     "ready" : true,
[WD Proxy]     "build" : {
[WD Proxy]       "upgradedAt" : "1572524921534",
[WD Proxy]       "time" : "Nov  1 2019 13:01:44",
[WD Proxy]       "productBundleIdentifier" : "com.facebook.WebDriverAgentRunner"
[WD Proxy]     }
[WD Proxy]   },
[WD Proxy]   "sessionId" : "C854BEB6-F090-4FA8-A0A5-3228316E73A7"
[WD Proxy] }
[XCUITest] WebDriverAgent information:
[XCUITest] {
[XCUITest]   "message": "WebDriverAgent is ready to accept commands",
[XCUITest]   "state": "success",
[XCUITest]   "os": {
[XCUITest]     "name": "iOS",
[XCUITest]     "version": "13.2",
[XCUITest]     "sdkVersion": "13.0"
[XCUITest]   },
[XCUITest]   "ios": {
[XCUITest]     "simulatorVersion": "13.2",
[XCUITest]     "ip": "192.168.1.65"
[XCUITest]   },
[XCUITest]   "ready": true,
[XCUITest]   "build": {
[XCUITest]     "upgradedAt": "1572524921534",
[XCUITest]     "time": "Nov  1 2019 13:01:44",
[XCUITest]     "productBundleIdentifier": "com.facebook.WebDriverAgentRunner"
[XCUITest]   }
[XCUITest] }
[XCUITest] WebDriverAgent successfully started after 29725ms
[BaseDriver] Event 'wdaSessionAttempted' logged at 1572862988567 (15:53:08 GMT+0530 (IST))
[XCUITest] Sending createSession command to WDA
[WD Proxy] Matched '/session' to command name 'createSession'
[WD Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.example.apple-samplecode.UICatalog","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}}
[WD Proxy] Got response with status 200: {"value":{"sessionId":"64EB68B6-BFA1-4E9E-9E43-68BF97350F5F","capabilities":{"device":"iphone","browserName":"UICatalog","sdkVersion":"13.2","CFBundleIdentifier":"com.example.apple-samplecode.UICatalog"}},"sessionId":"64EB68B6-BFA1-4E9E-9E43-68BF97350F5F"}
[WD Proxy] Determined the downstream protocol as 'W3C'
[BaseDriver] Event 'wdaSessionStarted' logged at 1572862995634 (15:53:15 GMT+0530 (IST))
[BaseDriver] Event 'wdaStarted' logged at 1572862995827 (15:53:15 GMT+0530 (IST))
[XCUITest] Skipping setting of the initial display orientation. Set the "orientation" capability to either "LANDSCAPE" or "PORTRAIT", if this is an undesired behavior.
[BaseDriver] Event 'orientationSet' logged at 1572862995828 (15:53:15 GMT+0530 (IST))
[Appium] New XCUITestDriver session created successfully, session a46258c7-7275-43ab-b969-0a539e4cb067 added to master session list
[BaseDriver] Event 'newSessionStarted' logged at 1572862995829 (15:53:15 GMT+0530 (IST))
[W3C (a46258c7)] Cached the protocol value 'W3C' for the new session a46258c7-7275-43ab-b969-0a539e4cb067
[W3C (a46258c7)] Responding to client with driver.createSession() result: {"capabilities":{"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"platformName":"ios","waitForQuietness":"false","app":"/Users/karthik/Desktop/UICatalog.app","automationName":"XCuiTest","deviceName":"iPhone XR","platformVersion":"13.2","useNewWDA":true,"udid":"93DEF7F0-CE20-40A7-8356-535140FDD7D8"}}
[HTTP] <-- POST /wd/hub/session 200 95512 ms - 509
[HTTP] 
[BaseDriver] Shutting down because we waited 60 seconds for a command
[Appium] Closing session, cause was 'New Command Timeout of 60 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'
[Appium] Removing session a46258c7-7275-43ab-b969-0a539e4cb067 from our master session list
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down xcodebuild process (pid 3322)
[XCUITest] xcodebuild exited with code 'null' and signal 'SIGTERM'
[DevCon Factory] Releasing connections for 93DEF7F0-CE20-40A7-8356-535140FDD7D8 device on any port number
[DevCon Factory] Found cached connections to release: ["93DEF7F0-CE20-40A7-8356-535140FDD7D8:8100"]
[DevCon Factory] Cached connections count: 0
[XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[XCUITest] Deleting simulator created for this run (udid: '93DEF7F0-CE20-40A7-8356-535140FDD7D8')
[XCUITest] Killing running processes 'xcodebuild.*93DEF7F0-CE20-40A7-8356-535140FDD7D8, 93DEF7F0-CE20-40A7-8356-535140FDD7D8.*XCTRunner' for the device 93DEF7F0-CE20-40A7-8356-535140FDD7D8...
[XCUITest] 'pgrep -ifn xcodebuild.*93DEF7F0-CE20-40A7-8356-535140FDD7D8' didn't detect any matching processes. Return code: 1
[XCUITest] 'pgrep -ifn 93DEF7F0-CE20-40A7-8356-535140FDD7D8.*XCTRunner' didn't detect any matching processes. Return code: 1

public static void main (String args []) throws MalformedURLException
	{
		IOSDriver <IOSElement> driver= Capabilities();
		
		driver.findElementByAccessibilityId("Alert Views").click();
		driver.findElementByXPath("//*[@value='Text Entry']").click();
		driver.findElementByClassName("XCUIElementTypeTextField").sendKeys("hello");
		driver.findElementByName("OK").click();
		
	}

public static  IOSDriver<IOSElement> Capabilities() throws MalformedURLException 
	{
		IOSDriver <IOSElement> driver;

		DesiredCapabilities d = new DesiredCapabilities();
		d.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone XR");
	
		d.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
		d.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.IOS_XCUI_TEST);//Mac OS version is GREATER than 10.2
		d.setCapability(MobileCapabilityType.APP, "/Users/karthik/Desktop/UICatalog.app");
		d.setCapability(MobileCapabilityType.PLATFORM_VERSION, "13.2");
		d.setCapability("useNewWDA","true");
		d.setCapability("waitForQuietness","false");

		driver = new IOSDriver<>(new URL("http://127.0.0.1:4723/wd/hub"),d);
		driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		return driver;
		
	}

**Comment by mykola-mokhnach** [comment]
Please describe the steps plus the expected and the actual results and fill out the environment information which is requested in the issue reporting form template.

**Comment by VT1Karthik** [comment]
Im trying to invoke an app called UICatalog(basic app) and perform few operations using t### he simulator through appium but the app is getting invoked but further operations are not executed ie,

driver.findElementByAccessibilityId("Alert Views").click();
	driver.findElementByXPath("//*[@value='Text Entry']").click();
	driver.findElementByClassName("XCUIElementTypeTextField").sendKeys("hello");
	driver.findElementByName("OK").click();
The server is closed after waiting for 60seconds.

The below error is shown in eclipse,
Nov 04, 2019 4:05:36 PM io.appium.java_client.remote.AppiumCommandExecutor$1 lambda$0
INFO: Detected dialect: W3C
Exception in thread "main" java.lang.NoClassDefFoundError: org/openqa/selenium/remote/codec/w3c/W3CHttpCommandCodec
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:262)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:323)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:37)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:86)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:96)
	at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:92)
	at Mobile_Testing.base.Capabilities(base.java:30)
	at Mobile_Testing.IOSTEST.main(IOSTEST.java:12)
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.remote.codec.w3c.W3CHttpCommandCodec
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 14 more

**Comment by mykola-mokhnach** [comment]
This must be a problem with your client suite setup. Moving the issue to the appropriate tracker
