### ISSUE TITLE
An unknown server-side error occurred while processing the command. Original error: appIdKey,pageIdKey

### ISSUE THREAD

**Issue by amitrparmar** [appium/appium#13582]
## The problem

While running a test on my iPhone, I am facing this issue. I could not find any related solution which work in my case. Could someone please have a look and suggest.

## Environment

appium - 1.15.1
npm - 6.12.1
node - 12.12.0
Java - openJDK '13'
Xcode - 11.1
MAC - macOS Cataline
platform - iPhone (iOS v. 11.3.1) (Real Device)
Test executed from windows machine.

## Details

I am using RemoteWebDrive and facing this issue while running a java script code using execute method. More function details can be view from below log.

## Link to Appium logs

[HTTP] --> POST /wd/hub/session/8c18d11f-286d-4a50-ba10-0009cce92365/execute
[HTTP] {"script":"return document.readyState === 'complete'","args":[]}
[debug] [MJSONWP (8c18d11f)] Calling AppiumDriver.execute() with args: ["return document.readyState === 'complete'",[],"8c18d11f-286d-4a50-ba10-0009cce92365"]
[debug] [XCUITest] Executing command 'execute'
[debug] [RemoteDebugger] Executing atom 'execute_script'
[debug] [RemoteDebugger] Executing 'execute_script' atom in default context
[debug] [MJSONWP (8c18d11f)] Encountered internal error running command: Error: pageIdKey
[debug] [MJSONWP (8c18d11f)]     at RemoteDebuggerRealDevice.execute (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-remote-debugger/lib/remote-debugger.js:687:13)
[debug] [MJSONWP (8c18d11f)]     at RemoteDebuggerRealDevice.execute [as executeAtom] (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-remote-debugger/lib/remote-debugger.js:401:30)
[debug] [MJSONWP (8c18d11f)]     at runMicrotasks (<anonymous>)
[debug] [MJSONWP (8c18d11f)]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[HTTP] <-- POST /wd/hub/session/8c18d11f-286d-4a50-ba10-0009cce92365/execute 500 2 ms - 180

[HTTP] {"script":"return !!(crm_core && crm_core.TouchUser && crm_core.TouchUser.get_instance && crm_core.TouchUser.get_instance().is_logged_in())","args":[]}
[debug] [MJSONWP (8c18d11f)] Calling AppiumDriver.execute() with args: ["return !!(crm_core && crm_core.TouchUser && crm_core.TouchUser.get_instance && crm_core.TouchUser.get_instance().is_logged_in())",[],"8c18d11f-286d-4a50-ba10-0009cce92365"]
[debug] [XCUITest] Executing command 'execute'
[debug] [RemoteDebugger] Executing atom 'execute_script'
[debug] [RemoteDebugger] Executing 'execute_script' atom in default context
[debug] [MJSONWP (8c18d11f)] Encountered internal error running command: Error: pageIdKey
[debug] [MJSONWP (8c18d11f)]     at RemoteDebuggerRealDevice.execute (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-remote-debugger/lib/remote-debugger.js:687:13)
[debug] [MJSONWP (8c18d11f)]     at RemoteDebuggerRealDevice.execute [as executeAtom] (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-remote-debugger/lib/remote-debugger.js:401:30)
[debug] [MJSONWP (8c18d11f)]     at runMicrotasks (<anonymous>)
[debug] [MJSONWP (8c18d11f)]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[HTTP] <-- POST /wd/hub/session/8c18d11f-286d-4a50-ba10-0009cce92365/execute 500 2 ms - 180

## Java Error
INFO: Setup completed successfully.

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: pageIdKey (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 2.01 seconds
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'COMPUTER000117', ip: '192.168.134.34', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_91'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{app=/Users/admin/Desktop/IPA/Touch_6_r44525.app, networkConnectionEnabled=false, databaseEnabled=false, deviceName=iPhone, fullReset=true, platform=MAC, wdaLocalPort=8116, newCommandTimeout=300, platformVersion=11.4.1, webStorageEnabled=false, locationContextEnabled=false, automationName=XCUITest, browserName=, takesScreenshot=true, javascriptEnabled=true, platformName=iOS, udid=79832d7fa7002fef9a98a01d83b0d1259ca0826b, autoAcceptAlerts=true}]
Session ID: b79f4864-fbb1-4d0f-8e06-7cda19eb672c

                at sun.reflect.GeneratedConstructorAccessor9.newInstance(Unknown Source)
                at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
                at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
                at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
                at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
                at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:40)
                at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
                at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
                at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:577)
                at stayinfront.test.automation.framework.pages.AuthLoginPage.isLoggedIn(AuthLoginPage.java:80)
                at stayinfront.test.automation.framework.pages.AuthLoginPage.loginAs(AuthLoginPage.java:37)
                at stayinfront.test.automation.framework.TestBase.loginAs(TestBase.java:73)
                at TestCases.LoginTest.LoginTest(LoginTest.java:71)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
                at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
                at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
                at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
                at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
                at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
                at org.testng.TestRunner.privateRun(TestRunner.java:782)
                at org.testng.TestRunner.run(TestRunner.java:632)
                at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
                at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
                at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
                at org.testng.SuiteRunner.run(SuiteRunner.java:268)
                at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
                at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
                at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
                at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
                at org.testng.TestNG.run(TestNG.java:1064)
                at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
                at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)

## Code To Reproduce Issue [ Good To Have ]

String script = "return !!(crm_core && crm_core.TouchUser && crm_core.TouchUser.get_instance && crm_core.TouchUser.get_instance().is_logged_in())";

    try {
        return (Boolean)controller.getDriver().executeScript(script, new Object[0]);
    } catch (WebDriverException var3) {
        if (!var3.getMessage().contains("is not defined") && !var3.getMessage().contains("Can't find variable")) {
            throw var3;
        } else {
            return false;
        }
    }

**Comment by mykola-mokhnach** [comment]
Please try if it works with appium@beta

**Comment by amitrparmar** [comment]
Thanks @mykola-mokhnach , Issue resolved in appium 1.16.0-beta.1. 

I have updated appium to beta using below command on my mac and issue is not replicating.

$ npm uninstall -g appium 
$ npm install -g appium@beta

Is it recommended to continue with beta? Where we should expect it to be merge in release?

**Comment by mykola-mokhnach** [comment]
there are still some problems we'd like to address before releasing a new version, but using beta is always appreciated. This way one could help us to catch issues before they go into the next release
