### ISSUE TITLE
driver.getContextHandles for iOS throws Exception 

### ISSUE THREAD

**Issue by EdulaSuryaKiranReddy** [appium/appium#13623]
driver.getContextHandles throws Exception in iOS 

 **Environment**

Appium Version: 1.15.1
OS: Mac OS Mojave
Node.js version: 12.5.0
Mobile OS: iPhone 6s (Real device)
Mobile OS Version: 11.1
Appium CLI

Tried with Appium 1.15 the issue exists.

**Error logs**

**_uncaughtException: write EPIPE
```
Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:83:16)_**
org.openqa.selenium.WebDriverException: Connection refused (Connection refused)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'capelrd64424445.inedc.corpintra.net', ip: 'fe80:0:0:0:1c57:bb1:149f:d88d%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '1.8.0_211'
Driver info: driver.version: AppiumDriver
	at io.appium.java_client.remote.AppiumCommandExecutor.lambda$5(AppiumCommandExecutor.java:251)
	at java.util.Optional.orElseGet(Optional.java:267)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:250)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:45)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at io.appium.java_client.AppiumDriver.getContextHandles(AppiumDriver.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodA
```

 **Code To Reproduce Issue**

```
AppiumDriver<MobileElement> driver = null;
DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
desiredCapabilities.setCapability(MobileCapabilityType.DEVICE_NAME, device.getName());
desiredCapabilities.setCapability(MobileCapabilityType.UDID, “xxxxx”);
desiredCapabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, 5000);
desiredCapabilities.setCapability(IOSMobileCapabilityType.BUNDLE_ID, “com.xxxx.xxxx”);
desiredCapabilities.setCapability(MobileCapabilityType.NO_RESET, true);
desiredCapabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, “iOS”);
desiredCapabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, “11.1”);
desiredCapabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "XCUITest");
desiredCapabilities.setCapability(IOSMobileCapabilityType.USE_PREBUILT_WDA, true);
desiredCapabilities.setCapability(IOSMobileCapabilityType.WDA_LOCAL_PORT, 8300);

driver = new IOSDriver<MobileElement>(new URL("http://127.0.0.1:4723/wd/hub"), desiredCapabilities);

driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
driver.getContextHandles();
```

**Comment by imurchie** [comment]
Can you provide the _full_ **Server** logs, as a link to a [gist](https://gist.github.com)? There is not much to say from this client stack trace.

**Comment by mykola-mokhnach** [comment]
Also, it makes sense to try if it works with appium@beta first

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by EdulaSuryaKiranReddy** [comment]
> Also, it makes sense to try if it works with appium@beta first

Thanks @mykola-mokhnach . I tried with Appium beta (1.16.0-beta.2).
There is an error while iOS driver initialisation.

Please find the below appium server logs:

[35m[Appium][39m Welcome to Appium v1.16.0-beta.2
[35m[Appium][39m Non-default server args:
[35m[Appium][39m   address: 127.0.0.1
[35m[Appium][39m   port: 4726
[35m[Appium][39m   sessionOverride: true
[35m[Appium][39m   deviceName: axxxxxxxxxxxxxxxxxxxxxxxxxxxxb
[35m[Appium][39m Deprecated server args:
[35m[Appium][39m   [31m--device-name[39m => --default-capabilities '{"deviceName":"axxxxxxxxxxxxxxxxxxxxxxxxxxxxb"}'
[35m[Appium][39m Default capabilities, which will be added to each request unless overridden by desired capabilities:
[35m[Appium][39m   deviceName: axxxxxxxxxxxxxxxxxxxxxxxxxxxxb
[35m[Appium][39m Appium REST http interface listener started on 127.0.0.1:4726
[35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/status[39m
[35m[HTTP][39m [90m{}[39m
[debug] [35m[GENERIC][39m Calling AppiumDriver.getStatus() with args: []
[debug] [35m[GENERIC][39m Responding to client with driver.getStatus() result: {"build":{"version":"1.16.0-beta.2"}}
[35m[HTTP][39m [37m<-- GET /wd/hub/status [39m[32m200[39m [90m5 ms - 75[39m
[35m[HTTP][39m [90m[39m
[35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/status[39m
[35m[HTTP][39m [90m{}[39m
[debug] [35m[GENERIC][39m Calling AppiumDriver.getStatus() with args: []
[debug] [35m[GENERIC][39m Responding to client with driver.getStatus() result: {"build":{"version":"1.16.0-beta.2"}}
[35m[HTTP][39m [37m<-- GET /wd/hub/status [39m[32m200[39m [90m7 ms - 75[39m
[35m[HTTP][39m [90m[39m
[35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m
[35m[HTTP][39m [90m{"desiredCapabilities":{"noReset":true,"newCommandTimeout":5000,"platformVersion":"11","automationName":"XCUITest","bundleId":"com.xxxxx.xxxxxxxx","platformName":"iOS","udid":"axxxxxxxxxxxxxxxxxxxxxxxxxxxxb","deviceName":"iPhone6s","wdaLocalPort":8300},"capabilities":{"firstMatch":[{"appium:automationName":"XCUITest","appium:bundleId":"com.xxxxx.xxxxxxxx","appium:deviceName":"iPhone6s","appium:newCommandTimeout":5000,"appium:noReset":true,"platformName":"ios","appium:platformVersion":"11","appium:udid":"axxxxxxxxxxxxxxxxxxxxxxxxxxxxb","appium:wdaLocalPort":8300}]}}[39m
[debug] [35m[W3C][39m Calling AppiumDriver.createSession() with args: [{"noReset":true,"newCommandTimeout":5000,"platformVersion":"11","automationName":"XCUITest","bundleId":"com.xxxxx.xxxxxxxx","platformName":"iOS","udid":"axxxxxxxxxxxxxxxxxxxxxxxxxxxxb","deviceName":"iPhone6s","wdaLocalPort":8300},null,{"firstMatch":[{"appium:automationName":"XCUITest","appium:bundleId":"com.xxxxx.xxxxxxxx","appium:deviceName":"iPhone6s","appium:newCommandTimeout":5000,"appium:noReset":true,"platformName":"ios","appium:platformVersion":"11","appium:udid":"axxxxxxxxxxxxxxxxxxxxxxxxxxxxb","appium:wdaLocalPort":8300}]}]
[debug] [35m[BaseDriver][39m Event 'newSessionRequested' logged at 1574662648283 (11:47:28 GMT+0530 (India Standard Time))
[35m[Appium][39m Appium v1.16.0-beta.2 creating new XCUITestDriver (v3.7.0) session
[debug] [35m[BaseDriver][39m W3C capabilities and MJSONWP desired capabilities were provided
[debug] [35m[BaseDriver][39m Creating session with W3C capabilities: {
[debug] [35m[BaseDriver][39m   "alwaysMatch": {
[debug] [35m[BaseDriver][39m     "platformName": "ios",
[debug] [35m[BaseDriver][39m     "appium:automationName": "XCUITest",
[debug] [35m[BaseDriver][39m     "appium:bundleId": "com.xxxxx.xxxxxxxx",
[debug] [35m[BaseDriver][39m     "appium:deviceName": "iPhone6s",
[debug] [35m[BaseDriver][39m     "appium:newCommandTimeout": 5000,
[debug] [35m[BaseDriver][39m     "appium:noReset": true,
[debug] [35m[BaseDriver][39m     "appium:platformVersion": "11",
[debug] [35m[BaseDriver][39m     "appium:udid": "axxxxxxxxxxxxxxxxxxxxxxxxxxxxb",
[debug] [35m[BaseDriver][39m     "appium:wdaLocalPort": 8300
[debug] [35m[BaseDriver][39m   },
[debug] [35m[BaseDriver][39m   "firstMatch": [
[debug] [35m[BaseDriver][39m     {}
[debug] [35m[BaseDriver][39m   ]
[debug] [35m[BaseDriver][39m }
[35m[BaseDriver][39m Session created with session id: db3b65c4-934b-4b66-8c12-4fb210704530
[debug] [35m[XCUITest][39m Current user: 'user'
[debug] [35m[XCUITest][39m Available devices: axxxxxxxxxxxxxxxxxxxxxxxxxxxxb
[debug] [35m[XCUITest][39m Creating iDevice object with udid 'axxxxxxxxxxxxxxxxxxxxxxxxxxxxb'
[35m[XCUITest][39m Determining device to run tests on: udid: 'axxxxxxxxxxxxxxxxxxxxxxxxxxxxb', real device: true
[35m[XCUITest][39m Normalized platformVersion capability value '11' to '11.0'
[debug] [35m[BaseDriver][39m Event 'xcodeDetailsRetrieved' logged at 1574662648659 (11:47:28 GMT+0530 (India Standard Time))
[debug] [35m[BaseDriver][39m Event 'appConfigured' logged at 1574662648660 (11:47:28 GMT+0530 (India Standard Time))
[debug] [35m[BaseDriver][39m Event 'resetStarted' logged at 1574662648661 (11:47:28 GMT+0530 (India Standard Time))
[debug] [35m[XCUITest][39m Reset: fullReset not set. Leaving as is
[debug] [35m[BaseDriver][39m Event 'resetComplete' logged at 1574662648661 (11:47:28 GMT+0530 (India Standard Time))
[debug] [35m[BaseDriver][39m Event 'logCaptureStarted' logged at 1574662648941 (11:47:28 GMT+0530 (India Standard Time))
[35m[XCUITest][39m Setting up real device
[35m[RemoteDebugger][39m Remote Debugger version 7.0.0
[debug] [35m[RemoteDebugger][39m useNewSafari --> false
[debug] [35m[RemoteDebugger][39m Checking which communication style to use (non-Safari on platform version '11.0')
[debug] [35m[RemoteDebugger][39m Platform version equal or higher than '12.2': false
[35m[RemoteDebugger][39m Setting communication protocol: using full Web Inspector protocol communication
[debug] [35m[RemoteDebugger][39m Sending connection key request
[debug] [35m[RemoteDebugger][39m Sending '_rpc_reportIdentifier:' message (id: 0)
uncaughtException: write EPIPE
**Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:83:16)**
[debug] [35m[RemoteDebugger][39m Sending to Web Inspector took 8ms
[debug] [35m[RemoteDebugger][39m Connected to application
[35m[XCUITest][39m Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent'
[35m[XCUITest][39m Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj'
[debug] [35m[XCUITest][39m No obsolete cached processes from previous WDA sessions listening on port 8300 have been found
[35m[DevCon Factory][39m Requesting connection for device axxxxxxxxxxxxxxxxxxxxxxxxxxxxb on local port 8300, device port 8300
[debug] [35m[DevCon Factory][39m Cached connections count: 0
[35m[DevCon Factory][39m Successfully requested the connection for axxxxxxxxxxxxxxxxxxxxxxxxxxxxb:8300
[debug] [35m[XCUITest][39m Parsed BUILD_DIR configuration value: '/Users/user/Library/Developer/Xcode/DerivedData/WebDriverAgent-aiaejbhejflmruhkhsmeebmhbaia/Build/Products'
[debug] [35m[XCUITest][39m Got derived data root: '/Users/user/Library/Developer/Xcode/DerivedData/WebDriverAgent-aiaejbhejflmruhkhsmeebmhbaia'
[debug] [35m[XCUITest][39m Starting WebDriverAgent initialization with the synchronization key '/Users/user/Library/Developer/Xcode/DerivedData/WebDriverAgent-aiaejbhejflmruhkhsmeebmhbaia'
[debug] [35m[WD Proxy][39m Matched '/status' to command name 'getStatus'
[debug] [35m[WD Proxy][39m Proxying [GET /status] to [GET http://localhost:8300/status] with no body
**org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Original error: unexpected end of stream on Connection{127.0.0.1:4726, proxy=DIRECT hostAddress=/127.0.0.1:4726 cipherSuite=none protocol=http/1.1}**
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'capelrd64424445.inedc.corpintra.net', ip: 'fe80:0:0:0:1c57:bb1:149f:d88d%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '1.8.0_211'
Driver info: driver.version: IOSDriver
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:208)
	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:217)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:336)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:37)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:88)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:98)
	at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
	at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:340)
	at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:294)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.testng.TestRunner.privateRun(TestRunner.java:770)
	at org.testng.TestRunner.run(TestRunner.java:591)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
	at org.testng.SuiteRunner.run(SuiteRunner.java:304)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
	at org.testng.TestNG.runSuites(TestNG.java:1032)
	at org.testng.TestNG.run(TestNG.java:1000)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:186)
	... 41 more
**Caused by: java.io.IOException: unexpected end of stream on Connection{127.0.0.1:4726, proxy=DIRECT hostAddress=/127.0.0.1:4726 cipherSuite=none protocol=http/1.1}**
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:208)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at org.openqa.selenium.remote.internal.OkHttpClient$Factory$1.lambda$createClient$1(OkHttpClient.java:152)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:103)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:105)
	... 46 more
Caused by: java.io.EOFException: \n not found: limit=0 content=…
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:237)
	at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:215)
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
	... 66 more





**Comment by EdulaSuryaKiranReddy** [comment]
> gist

Please find the gist link below.

https://gist.github.com/EdulaSuryaKiranReddy/d9af532093429f2b891b4c551d85b462

**Comment by EdulaSuryaKiranReddy** [comment]
> Also, it makes sense to try if it works with appium@beta first

Thanks it worked for me after upgrading to appium 1.16 beta.2
