### ISSUE TITLE
TypeError: driver.onUnexpectedShutdown is not a function

### ISSUE THREAD

**Issue by sebinjoseph1994** [appium/appium#13660]
## The problem

On running appium, once the test starts to run, test fails with the error _Encountered internal error running command: TypeError: driver.onUnexpectedShutdown is not a function_. 

## Environment

* Appium version (or git revision) that exhibits the issue: v1.16.0-rc.0
* Last Appium version that did not exhibit the issue (if applicable): v1.15.1
* Desktop OS/version used to run Appium: macOS 10.14.4 
* Node.js version (unless using Appium.app|exe): v13.2.0
* Npm or Yarn package manager: 6.13.1
* Mobile platform/version under test: iOS 12.4
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

[debug] [WD Proxy] Got response with status 200: {"value":{"shouldUseCompactResponses":true,"mjpegServerFramerate":10,"activeAppDetectionPoint":"153.60,153.60","acceptAlertButtonSelector":"","snapshotTimeout":15,"elementResponseAttributes":"type,label","keyboardPrediction":false,"screenshotQuality":1,"keyboardAutocorrection":false,"useFirstMatch":false,"reduceMotion":false,"defaultActiveApplication":"auto","mjpegScalingFactor":100,"mjpegServerScreenshotQuality":25,"dismissAlertButtonSelector":"","includeNonModalElements":false},"sessionId":"CA263DD1-F1FD-442E-89D2-856FD7487CB3"}
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1575264572437 (10:59:32 GMT+0530 (India Standard Time))
[debug] [W3C] Encountered internal error running command: TypeError: driver.onUnexpectedShutdown is not a function
[debug] [W3C]     at AppiumDriver.attachUnexpectedShutdownHandler (/usr/local/lib/node_modules/appium/lib/appium.js:431:14)
[debug] [W3C]     at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:374:12)
[HTTP] <-- POST /wd/hub/session 500 216702 ms - 587

**Comment by mykola-mokhnach** [comment]
Can you please provide the full log?

**Comment by sebinjoseph1994** [comment]
@mykola-mokhnach Please find the full logs at https://gist.github.com/sebinjoseph1994/c0026eaddb015b4ed5b7064fd5ce60aa

**Comment by mykola-mokhnach** [comment]
> XCUITestDriver (v3.7.0)

It looks like the driver is out of date. Try to install appium@beta and make sure the version of the driver is at 3.8.0

**Comment by sebinjoseph1994** [comment]
Oh okay. Thank you for your immediate support. Let me try this :)

**Comment by sebinjoseph1994** [comment]
It worked! Thank you so much @mykola-mokhnach.

**Comment by alcoredev** [comment]
We observed the same exception when trying to open Chrome session on Android device. I believe that exception is not related to XCUITestDriver. 

Also it is not clear why Beta version is advised to be used instead of RC:
- although Appium 1.16.0-beta.3 (installed by "npm install appium@beta") works with Chrome, it does not contain file 'npm-shrinkwrap.json'. Does it mean that update of any dependency might break it?

**Comment by mykola-mokhnach** [comment]
I think the rc0 has been locked in the middle of modules update process, which causes this issue. Just an unfortunate coincidence

**Comment by alcoredev** [comment]
> I think the rc0 has been locked in the middle of modules update process, which causes this issue. Just an unfortunate coincidence

Should we wait for a fix?

**Comment by mykola-mokhnach** [comment]
It's up to you. rc is is just a shrink-wrap of the recent beta snapshot
