### ISSUE TITLE
Appium 1.16.0-rc.0 cannot start Android 

### ISSUE THREAD

**Issue by bennid** [appium/appium#13684]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue: 1.16.0-rc.0
* Last Appium version that did not exhibit the issue (if applicable): 1.16.0-beta.2
* Desktop OS/version used to run Appium: MacOS 10.14.6
* Node.js version (unless using Appium.app|exe): 12.10.0
* Npm or Yarn package manager: npm 6.9.0
* Mobile platform/version under test: Android phone 8.0
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium cli

## Details

On trying to create a new session the session bommand failed with the following error

```
2019-12-04 16:04:43:008 - [debug] [BaseDriver] Event 'newSessionStarted' logged at 1575475483008 (11:04:43 GMT-0500 (Eastern Standard Time))
2019-12-04 16:04:43:033 - [debug] [W3C] Encountered internal error running command: TypeError: driver.onUnexpectedShutdown is not a function
2019-12-04 16:04:43:034 - [debug] [W3C]     at AppiumDriver.attachUnexpectedShutdownHandler (/Users/bdouglas/build_tools/android_phone/accf5280/node_modules/appium/lib/appium.js:431:14)
2019-12-04 16:04:43:034 - [debug] [W3C]     at AppiumDriver.createSession (/Users/bdouglas/build_tools/android_phone/accf5280/node_modules/appium/lib/appium.js:374:12)
```

## Code To Reproduce Issue [ Good To Have ]

Capabilities:

```
2019-12-04 16:04:25:097 - [debug] [BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
2019-12-04 16:04:25:097 - [debug] [BaseDriver] Creating session with W3C capabilities: {
2019-12-04 16:04:25:097 - [debug] [BaseDriver]   "alwaysMatch": {
2019-12-04 16:04:25:097 - [debug] [BaseDriver]     "appium:appPackage": "com.android.settings",
2019-12-04 16:04:25:097 - [debug] [BaseDriver]     "appium:clearSystemFiles": true,
2019-12-04 16:04:25:098 - [debug] [BaseDriver]     "appium:disableAndroidWatchers": true,
2019-12-04 16:04:25:098 - [debug] [BaseDriver]     "appium:ignoreUnimportantViews": true,
2019-12-04 16:04:25:098 - [debug] [BaseDriver]     "appium:appActivity": "com.android.settings.Settings",
2019-12-04 16:04:25:098 - [debug] [BaseDriver]     "appium:newCommandTimeout": 45,
2019-12-04 16:04:25:098 - [debug] [BaseDriver]     "appium:platformVersion": "8.0",
2019-12-04 16:04:25:098 - [debug] [BaseDriver]     "appium:automationName": "UIAutomator2",
2019-12-04 16:04:25:098 - [debug] [BaseDriver]     "appium:autoGrantPermissions": true,
2019-12-04 16:04:25:098 - [debug] [BaseDriver]     "appium:unicodeKeyboard": true,
2019-12-04 16:04:25:098 - [debug] [BaseDriver]     "appium:resetKeyboard": true,
2019-12-04 16:04:25:099 - [debug] [BaseDriver]     "browserName": "",
2019-12-04 16:04:25:099 - [debug] [BaseDriver]     "platformName": "android",
2019-12-04 16:04:25:099 - [debug] [BaseDriver]     "server:CONFIG_UUID": "e83cbb8e-7bd7-49fe-bc42-4ee688690bad",
2019-12-04 16:04:25:100 - [debug] [BaseDriver]     "appium:deviceName": "PHONE_ID",
2019-12-04 16:04:25:100 - [debug] [BaseDriver]     "appium:udid": "PHONE_ID",
2019-12-04 16:04:25:100 - [debug] [BaseDriver]     "appium:systemPort": 7833,
2019-12-04 16:04:25:100 - [debug] [BaseDriver]     "appium:wdaLocalPort": 7833
2019-12-04 16:04:25:100 - [debug] [BaseDriver]   },
2019-12-04 16:04:25:100 - [debug] [BaseDriver]   "firstMatch": [
2019-12-04 16:04:25:100 - [debug] [BaseDriver]     {}
2019-12-04 16:04:25:101 - [debug] [BaseDriver]   ]
2019-12-04 16:04:25:101 - [debug] [BaseDriver] }

```

**Comment by mykola-mokhnach** [comment]
Use [search](https://github.com/appium/appium/issues/13660), please

**Comment by bennid** [comment]
Thanks... was only searching for open bugs
