### ISSUE TITLE
Appium 1.16.0-beta.3 crashing with OBJECT_NOT_FOUND for iPhone (AfcService._checkStatus)

### ISSUE THREAD

**Issue by bennid** [appium/appium#13716]
## The problem

Calling install_app on an iPhone, we're getting the following exception:

```
2019-12-12 00:20:55:468 - [HTTP] --> POST /wd/hub/session/eddfadc9-8f0a-430b-b647-eaeac5be4944/appium/device/install_app
2019-12-12 00:20:55:469 - [HTTP] {"appPath":"http://mycompany.com:8000/files/myapp-prerelease-1-34.6-191216029.ipa"}
2019-12-12 00:20:55:470 - [debug] [W3C (eddfadc9)] Calling AppiumDriver.installApp() with args: ["http://mycompany.com:8000/files/myapp-prerelease-1-34.6-191216029.ipa",null,null,null,"eddfadc9-8f0a-430b-b647-eaeac5be4944"]
2019-12-12 00:20:55:471 - [debug] [XCUITest] Executing command 'installApp'
2019-12-12 00:20:55:474 - [BaseDriver] Using downloadable app 'http://mycompany.com:8000/files/myapp-prerelease-1-34.6-191216029.ipa'
2019-12-12 00:20:55:481 - [debug] [BaseDriver] App Last-Modified: Wed, 11 Dec 2019 02:00:24 GMT
2019-12-12 00:20:55:484 - [BaseDriver] Reusing previously downloaded application at '/var/folders/ll/brhhr98d59j9yjzm3fmjbssw0000gp/T/20191111-18845-yq7p1y.2gau/Payload/MyCompany.app'
2019-12-12 00:20:55:484 - [XCUITest] Installing '/var/folders/ll/brhhr98d59j9yjzm3fmjbssw0000gp/T/20191111-18845-yq7p1y.2gau/Payload/MyCompay.app' to the real device with UDID 00008020-XXXXXXXX
2019-12-12 00:20:55:744 - [XCUITest] Falling back to ios-deploy usage
2019-12-12 00:20:55:744 - [XCUITest] Error: Unexpected response OBJECT_NOT_FOUND
2019-12-12 00:20:55:745 - [XCUITest]     at AfcService._checkStatus (/Users/jenkins/build_tools/ios_phone/00008020-00156C622E82002E/node_modules/appium/node_modules/appium-ios-device/lib/afc/index.js:271:13)
2019-12-12 00:20:55:745 - [XCUITest]     at AfcService.openFile (/Users/jenkins/build_tools/ios_phone/00008020-00156C622E82002E/node_modules/appium/node_modules/appium-ios-device/lib/afc/index.js:118:12)
2019-12-12 00:20:55:745 - [XCUITest]     at AfcService.createWriteStream (/Users/jenkins/build_tools/ios_phone/00008020-00156C622E82002E/node_modules/appium/node_modules/appium-ios-device/lib/afc/index.js:131:24)
2019-12-12 00:20:55:745 - [XCUITest]     at /Users/jenkins/build_tools/ios_phone/00008020-00156C622E82002E/node_modules/appium/node_modules/appium-xcuitest-driver/lib/ios-deploy.js:95:31
2019-12-12 00:20:55:745 - [XCUITest]     at /Users/jenkins/build_tools/ios_phone/00008020-00156C622E82002E/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-support/lib/fs.js:96:47
2019-12-12 00:20:57:238 - uncaughtException: write EPIPE
Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:87:16)
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.0.16-beta.3
* Last Appium version that did not exhibit the issue (if applicable): 1.14.1
* Desktop OS/version used to run Appium: OSX 10.14.6
* Node.js version (unless using Appium.app|exe): 12.10.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iPhone Xr running ios 13.1.3
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: cli

## Details

Multiple phones connected to the same iMac running multiple appium instances (one per phone).  These are run through selenium grid.  Some other version info:

```
server-qa05:00008020-XXXXXXXX jenkins$ npm ls appium-ios-device
/Users/jenkins/build_tools/ios_phone/00008020-XXXXXXXX
└─┬ appium@1.16.0-beta.3
  └─┬ appium-xcuitest-driver@3.10.1
    └── appium-ios-device@1.2.1  extraneous

npm ERR! extraneous: appium-ios-device@1.2.1 /Users/jenkins/build_tools/ios_phone/00008020-XXXXXXXX/node_modules/appium-xcuitest-driver/node_modules/appium-ios-device
server-qa05:00008020-XXXXXXXX jenkins$ npm ls appium-xcuitest-driver
/Users/jenkins/build_tools/ios_phone/00008020-XXXXXXXX
└─┬ appium@1.16.0-beta.3
  ├─┬ appium-flutter-driver@0.0.20
  │ └── appium-xcuitest-driver@2.133.1  extraneous
  ├── appium-xcuitest-driver@3.10.1 
  └─┬ appium-youiengine-driver@1.2.3
    └── appium-xcuitest-driver@3.10.1  deduped

npm ERR! extraneous: appium-xcuitest-driver@2.133.1 /Users/jenkins/build_tools/ios_phone/00008020-XXXXXXXX/node_modules/appium-flutter-driver/node_modules/appium-xcuitest-driver
server-qa05:00008020-XXXXXXXX jenkins$ 
```

## Code To Reproduce Issue [ Good To Have ]

Just a call to install_app with a url to the ipa.  Unsure if it's related to multiple phones/appium instances on the same machine.

**Comment by mykola-mokhnach** [comment]
Do you have clearSystemFiles cap enabled? if yes then please disable it

**Comment by bennid** [comment]
Will try that, but appium probably shouldn't crash at this

**Comment by mykola-mokhnach** [comment]
We've added some improvements to appium@beta related to cache integrity control. Please check if that has resolved the issue above.

**Comment by mykola-mokhnach** [comment]
Closed because of no response
