### ISSUE TITLE
Closing session, cause was 'Unexpected shutdown'

### ISSUE THREAD

**Issue by qwertyI** [appium/appium#13712]
## The problem

as title.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.13.0
* Last Appium version that did not exhibit the issue (if applicable): 1.13.0
* Desktop OS/version used to run Appium: ContOS
* Node.js version (unless using Appium.app|exe): v12.5.0
* Npm or Yarn package manager: 6.9.0
* Mobile platform/version under test: Android 9.0
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: NO

## Details

Executed successfully on Mac, but failed on CentOS virtual machine. The steps to configure the environment are the same.

## Link to Appium logs

```shell
[Appium] Welcome to Appium v1.13.0
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"capabilities":{"firstMatch":[{"platformName":"Android","appium:appPackage":"com.android.settings","appium:appActivity":"com.android.settings.Settings","appium:unicodeKeyboard":"true","appium:resetKeyboard":"true","appium:automationName":"uiautomator2","appium:platformVersion":"9","appium:deviceName":"10.96.2.42:5555","appium:noReset":true}]},"desiredCapabilities":{"platformName":"Android","appPackage":"com.android.settings","appActivity":"com.android.settings.Settings","unicodeKeyboard":"true","resetKeyboard":"true","automationName":"uiautomator2","platformVersion":"9","deviceName":"10.96.2.42:5555","noReset":true}}
[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"platformName":"Android","appPackage":"com.android.settings","appActivity":"com.android.settings.Settings","unicodeKeyboard":"true","resetKeyboard":"true","automationName":"uiautomator2","platformVersion":"9","deviceName":"10.96.2.42:5555","noReset":true},null,{"firstMatch":[{"platformName":"Android","appium:appPackage":"com.android.settings","appium:appActivity":"com.android.settings.Settings","appium:unicodeKeyboard":"true","appium:resetKeyboard":"true","appium:automationName":"uiautomator2","appium:platformVersion":"9","appium:deviceName":"10.96.2.42:5555","appium:noReset":true}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1575994532528 (00:15:32 GMT+0800 (GMT+08:00))
[Appium] Appium v1.13.0 creating new AndroidUiautomator2Driver (v1.40.0) session
[Appium] Capabilities:
[Appium]   platformName: Android
[Appium]   appPackage: com.android.settings
[Appium]   appActivity: com.android.settings.Settings
[Appium]   unicodeKeyboard: true
[Appium]   resetKeyboard: true
[Appium]   automationName: uiautomator2
[Appium]   platformVersion: 9
[Appium]   deviceName: 10.96.2.42:5555
[Appium]   noReset: true
[debug] [BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {
[debug] [BaseDriver]   "alwaysMatch": {
[debug] [BaseDriver]     "platformName": "Android",
[debug] [BaseDriver]     "appium:appPackage": "com.android.settings",
[debug] [BaseDriver]     "appium:appActivity": "com.android.settings.Settings",
[debug] [BaseDriver]     "appium:unicodeKeyboard": "true",
[debug] [BaseDriver]     "appium:resetKeyboard": "true",
[debug] [BaseDriver]     "appium:automationName": "uiautomator2",
[debug] [BaseDriver]     "appium:platformVersion": "9",
[debug] [BaseDriver]     "appium:deviceName": "10.96.2.42:5555",
[debug] [BaseDriver]     "appium:noReset": true
[debug] [BaseDriver]   },
[debug] [BaseDriver]   "firstMatch": [
[debug] [BaseDriver]     {}
[debug] [BaseDriver]   ]
[debug] [BaseDriver] }
[BaseDriver] Capability 'unicodeKeyboard' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] Capability 'resetKeyboard' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] Session created with session id: cbf52f09-58ba-43ee-aa5d-bbeddb8b024d
[UiAutomator2] Starting 'com.android.settings' directly on the device
[ADB] Found 7 'build-tools' folders under '/root/sdk' (newest first):
[ADB]     /root/sdk/build-tools/29.0.2
[ADB]     /root/sdk/build-tools/29.0.1
[ADB]     /root/sdk/build-tools/29.0.0
[ADB]     /root/sdk/build-tools/28.0.3
[ADB]     /root/sdk/build-tools/28.0.2
[ADB]     /root/sdk/build-tools/28.0.1
[ADB]     /root/sdk/build-tools/28.0.0
[ADB] Using 'adb' from '/root/sdk/platform-tools/adb'
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...
[debug] [ADB] Connected devices: [{"udid":"10.96.2.42:5555","state":"device"}]
[AndroidDriver] Looking for a device with Android '9'
[debug] [ADB] Setting device id to 10.96.2.42:5555
[ADB] Getting device platform version
[debug] [ADB] Running '/root/sdk/platform-tools/adb -P 5037 -s 10.96.2.42\:5555 shell getprop ro.build.version.release'
[debug] [ADB] Current device property 'ro.build.version.release': 9
[AndroidDriver] Using device: 10.96.2.42:5555
[ADB] Using 'adb' from '/root/sdk/platform-tools/adb'
[debug] [ADB] Setting device id to 10.96.2.42:5555
[debug] [ADB] Running '/root/sdk/platform-tools/adb -P 5037 -s 10.96.2.42\:5555 shell getprop ro.build.version.sdk'
[debug] [ADB] Current device property 'ro.build.version.sdk': 28
[debug] [ADB] Running '/root/sdk/platform-tools/adb -P 5037 -s 10.96.2.42\:5555 shell getprop ro.build.version.release'
[debug] [ADB] Current device property 'ro.build.version.release': 9
[debug] [ADB] Device API level: 28
[UiAutomator2] Relaxing hidden api policy
[debug] [ADB] Running '/root/sdk/platform-tools/adb -P 5037 -s 10.96.2.42\:5555 shell settings put global hidden_api_policy_pre_p_apps 1'
[debug] [ADB] Running '/root/sdk/platform-tools/adb -P 5037 -s 10.96.2.42\:5555 shell settings put global hidden_api_policy_p_apps 1'
[debug] [ADB] Running '/root/sdk/platform-tools/adb -P 5037 -s 10.96.2.42\:5555 shell settings put global hidden_api_policy 1'
[AndroidDriver] No app sent in, not parsing package/activity
[debug] [ADB] Running '/root/sdk/platform-tools/adb -P 5037 -s 10.96.2.42\:5555 wait-for-device'
[debug] [ADB] Running '/root/sdk/platform-tools/adb -P 5037 -s 10.96.2.42\:5555 shell echo ping'
[debug] [AndroidDriver] Pushing settings apk to device...
[debug] [ADB] Getting install status for io.appium.settings
[debug] [ADB] Running '/root/sdk/platform-tools/adb -P 5037 -s 10.96.2.42\:5555 shell dumpsys package io.appium.settings'
[debug] [ADB] 'io.appium.settings' is installed
[debug] [ADB] Getting package info for 'io.appium.settings'
[debug] [ADB] Running '/root/sdk/platform-tools/adb -P 5037 -s 10.96.2.42\:5555 shell dumpsys package io.appium.settings'
[debug] [ADB] The version name of the installed 'io.appium.settings' is greater or equal to the application version name ('2.15.0' >= '2.15.0')
[debug] [ADB] There is no need to install/upgrade '/root/.nvm/versions/node/v12.5.0/lib/node_modules/appium/node_modules/_io.appium.settings@2.15.0@io.appium.settings/apks/settings_apk-debug.apk'
[debug] [ADB] Getting IDs of all 'io.appium.settings' processes
[debug] [ADB] Running '/root/sdk/platform-tools/adb -P 5037 -s 10.96.2.42\:5555 shell 'pgrep --help; echo $?''
[debug] [ADB] Running '/root/sdk/platform-tools/adb -P 5037 -s 10.96.2.42\:5555 shell pgrep -f io\\.appium\\.settings'
[debug] [AndroidDriver] io.appium.settings is already running. There is no need to reset its permissions.
[debug] [ADB] Running '/root/sdk/platform-tools/adb -P 5037 -s 10.96.2.42\:5555 shell appops set io.appium.settings android\:mock_location allow'
[debug] [Logcat] Starting logcat capture
[debug] [AndroidDriver] Enabling Unicode keyboard support
[debug] [ADB] Running '/root/sdk/platform-tools/adb -P 5037 -s 10.96.2.42\:5555 shell settings get secure default_input_method'
[debug] [AndroidDriver] Unsetting previous IME io.appium.settings/.UnicodeIME
[debug] [AndroidDriver] Setting IME to 'io.appium.settings/.UnicodeIME'
[debug] [ADB] Running '/root/sdk/platform-tools/adb -P 5037 -s 10.96.2.42\:5555 shell ime enable io.appium.settings/.UnicodeIME'
[debug] [ADB] Running '/root/sdk/platform-tools/adb -P 5037 -s 10.96.2.42\:5555 shell ime set io.appium.settings/.UnicodeIME'
[debug] [UiAutomator2] Forwarding UiAutomator2 Server port 6790 to 8201
[debug] [ADB] Forwarding system: 8201 to device: 6790
[debug] [ADB] Running '/root/sdk/platform-tools/adb -P 5037 -s 10.96.2.42\:5555 forward tcp\:8201 tcp\:6790'
[debug] [ADB] Getting install status for io.appium.uiautomator2.server
[debug] [ADB] Running '/root/sdk/platform-tools/adb -P 5037 -s 10.96.2.42\:5555 shell dumpsys package io.appium.uiautomator2.server'
[debug] [ADB] 'io.appium.uiautomator2.server' is installed
[debug] [ADB] Getting package info for 'io.appium.uiautomator2.server'
[debug] [ADB] Running '/root/sdk/platform-tools/adb -P 5037 -s 10.96.2.42\:5555 shell dumpsys package io.appium.uiautomator2.server'
[debug] [ADB] The version name of the installed 'io.appium.uiautomator2.server' is greater or equal to the application version name ('4.5.2' >= '4.5.2')
[debug] [UiAutomator2] io.appium.uiautomator2.server installation state: sameVersionInstalled
[debug] [ADB] Checking app cert for /root/.nvm/versions/node/v12.5.0/lib/node_modules/appium/node_modules/_appium-uiautomator2-server@4.5.2@appium-uiautomator2-server/apks/appium-uiautomator2-server-v4.5.2.apk
[ADB] Using 'apksigner' from '/root/sdk/build-tools/29.0.2/apksigner'
[debug] [ADB] Starting '/root/sdk/build-tools/29.0.2/apksigner' with args '["verify","--print-certs","/root/.nvm/versions/node/v12.5.0/lib/node_modules/appium/node_modules/_appium-uiautomator2-server@4.5.2@appium-uiautomator2-server/apks/appium-uiautomator2-server-v4.5.2.apk"]'
[debug] [ADB] apksigner stdout: Signer #1 certificate DN: EMAILADDRESS=android@android.com, CN=Android, OU=Android, O=Android, L=Mountain View, ST=California, C=US
[debug] [ADB] Signer #1 certificate SHA-256 digest: a40da80a59d170caa950cf15c18c454d47a39b26989d8b640ecd745ba71bf5dc
[debug] [ADB] Signer #1 certificate SHA-1 digest: 61ed377e85d386a8dfee6b864bd85b0bfaa5af81
[debug] [ADB] Signer #1 certificate MD5 digest: e89b158e4bcf988ebd09eb83f5378e87
[debug] [ADB]
[debug] [ADB] '/root/.nvm/versions/node/v12.5.0/lib/node_modules/appium/node_modules/_appium-uiautomator2-server@4.5.2@appium-uiautomator2-server/apks/appium-uiautomator2-server-v4.5.2.apk' is already signed.
[debug] [ADB] Getting install status for io.appium.uiautomator2.server.test
[debug] [ADB] Running '/root/sdk/platform-tools/adb -P 5037 -s 10.96.2.42\:5555 shell dumpsys package io.appium.uiautomator2.server.test'
[debug] [ADB] 'io.appium.uiautomator2.server.test' is installed
[debug] [ADB] Checking app cert for /root/.nvm/versions/node/v12.5.0/lib/node_modules/appium/node_modules/_appium-uiautomator2-server@4.5.2@appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk
[debug] [ADB] Starting '/root/sdk/build-tools/29.0.2/apksigner' with args '["verify","--print-certs","/root/.nvm/versions/node/v12.5.0/lib/node_modules/appium/node_modules/_appium-uiautomator2-server@4.5.2@appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk"]'
[debug] [ADB] apksigner stdout: Signer #1 certificate DN: EMAILADDRESS=android@android.com, CN=Android, OU=Android, O=Android, L=Mountain View, ST=California, C=US
[debug] [ADB] Signer #1 certificate SHA-256 digest: a40da80a59d170caa950cf15c18c454d47a39b26989d8b640ecd745ba71bf5dc
[debug] [ADB] Signer #1 certificate SHA-1 digest: 61ed377e85d386a8dfee6b864bd85b0bfaa5af81
[debug] [ADB] Signer #1 certificate MD5 digest: e89b158e4bcf988ebd09eb83f5378e87
[debug] [ADB]
[debug] [ADB] '/root/.nvm/versions/node/v12.5.0/lib/node_modules/appium/node_modules/_appium-uiautomator2-server@4.5.2@appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk' is already signed.
[UiAutomator2] Server packages are not going to be (re)installed
[debug] [UiAutomator2] Waiting up to 30000ms for services to be available
[debug] [ADB] Running '/root/sdk/platform-tools/adb -P 5037 -s 10.96.2.42\:5555 shell pm list instrumentation'
[debug] [UiAutomator2] Instrumentation target 'io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner' is available
[debug] [UiAutomator2] No app capability. Assuming it is already on the device
[debug] [UiAutomator2] Performing shallow cleanup of automation leftovers
[debug] [UiAutomator2] The following obsolete sessions are still running: ["e96d3780-67d2-4fc3-a014-98bd61076718"]
[debug] [UiAutomator2] Cleaning up the obsolete sessions
[debug] [ADB] Running '/root/sdk/platform-tools/adb -P 5037 -s 10.96.2.42\:5555 shell am force-stop io.appium.uiautomator2.server.test'
[UiAutomator2] Starting UIAutomator2 server 4.5.2
[UiAutomator2] Using UIAutomator2 server from '/root/.nvm/versions/node/v12.5.0/lib/node_modules/appium/node_modules/_appium-uiautomator2-server@4.5.2@appium-uiautomator2-server/apks/appium-uiautomator2-server-v4.5.2.apk' and test from '/root/.nvm/versions/node/v12.5.0/lib/node_modules/appium/node_modules/_appium-uiautomator2-server@4.5.2@appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk'
[UiAutomator2] Waiting up to 30000ms for UiAutomator2 to be online...
[debug] [ADB] Creating ADB subprocess with args: ["-P",5037,"-s","10.96.2.42:5555","shell","am","instrument","-w","io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner"]
[debug] [Instrumentation] io.appium.uiautomator2.server.test.AppiumUiAutomator2Server:
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8201/wd/hub/status] with no body
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8201/wd/hub/status] with no body
[debug] [WD Proxy] Got response with status 200: {"sessionId":"None","value":{"ready":true,"message":"UiAutomator2 Server is ready to accept commands"}}
[debug] [UiAutomator2] The initialization of the instrumentation process took 2036ms
[debug] [WD Proxy] Matched '/session' to command name 'createSession'
[debug] [WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8201/wd/hub/session] with body: {"capabilities":{"firstMatch":[{"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platformName":"Android","appPackage":"com.android.settings","appActivity":"com.android.settings.Settings","unicodeKeyboard":true,"resetKeyboard":true,"automationName":"uiautomator2","platformVersion":"9","deviceName":"10.96.2.42:5555","noReset":true},"platformName":"Android","appPackage":"com.android.settings","appActivity":"com.android.settings.Settings","unicodeKeyboard":true,"resetKeyboard":true,"automationName":"uiautomator2","platformVersion":"9","deviceName":"10.96.2.42:5555","noReset":true,"deviceUDID":"10.96.2.42:5555"}],"alwaysMatch":{}}}
[debug] [WD Proxy] Got response with status 200: {"sessionId":"7cde18e3-d5a7-4383-929b-63561c8f9729","value":{"sessionId":"7cde18e3-d5a7-4383-929b-63561c8f9729","capabilities":{"firstMatch":[{"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platformName":"Android","appPackage":"com.android.settings","appActivity":"com.android.settings.Settings","unicodeKeyboard":true,"resetKeyboard":true,"automationName":"uiautomator2","platformVersion":"9","deviceName":"10.96.2.42:5555","noReset":true},"platformName":"Android","appPackage":"com.android.settings","appActivity":"com.android.settings.Settings","unicodeKeyboard":true,"resetKeyboard":true,"automationName":"uiautomator2","platformVersion":"9","deviceName":"10.96.2.42:5555","noReset":true,"deviceUDID":"10.96.2.42:5555"}],"alwaysMatch":{}}}}
[WD Proxy] Determined the downstream protocol as 'W3C'
[debug] [WD Proxy] Proxying [GET /appium/device/info] to [GET http://127.0.0.1:8201/wd/hub/session/7cde18e3-d5a7-4383-929b-63561c8f9729/appium/device/info] with no body
[debug] [WD Proxy] Got response with status 200: {"sessionId":"7cde18e3-d5a7-4383-929b-63561c8f9729","value":{"androidId":"4e61bccbacf7eaf6","manufacturer":"VMware, Inc.","model":"VMware Virtual Platform","brand":"Android-x86","apiVersion":"28","platformVersion":"9","carrierName":"","realDisplaySize":"1024x768","displayDensity":160,"networks":[{"type":1,"typeName":"WIFI","subtype":0,"subtypeName":"","isConnected":true,"detailedState":"CONNECTED","state":"CONNECTED","extraInfo":null,"isAvailable":true,"isFailover":false,"isRoaming":false,"capabilities":{"transportTypes":"TRANSPORT_WIFI","networkCapabilities":"NET_CAPABILITY_NOT_METERED,NET_CAPABILITY_INTERNET,NET_CAPABILITY_NOT_RESTRICTED,NET_CAPABILITY_TRUSTED,NET_CAPABILITY_NOT_VPN,NET_CAPABILITY_NOT_ROAMING,NET_CAPABILITY_FOREGROUND,NET_CAPABILITY_NOT_CONGESTED,NET_CAPABILITY_NOT_SUSPENDED","linkUpstreamBandwidthKbps":1048576,"linkDownBandwidthKbps":1048576,"signalStrength":-50,"networkSpecifier":null,"SSID":null}}],"locale":"zh_CN_#Hans","timeZone":"Asia\/Shanghai","bluetooth":{"state":"OFF"}}}
[debug] [ADB] Running '/root/sdk/platform-tools/adb -P 5037 -s 10.96.2.42\:5555 shell dumpsys window'
[AndroidDriver] Screen already unlocked, doing nothing
[UiAutomator2] Starting 'com.android.settings/com.android.settings.Settings and waiting for 'com.android.settings/com.android.settings.Settings'
[debug] [ADB] Running '/root/sdk/platform-tools/adb -P 5037 -s 10.96.2.42\:5555 shell am start -W -n com.android.settings/com.android.settings.Settings -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
[debug] [WD Proxy] Proxying [GET /appium/device/pixel_ratio] to [GET http://127.0.0.1:8201/wd/hub/session/7cde18e3-d5a7-4383-929b-63561c8f9729/appium/device/pixel_ratio] with body: {}
[debug] [WD Proxy] Got response with status 200: {"sessionId":"7cde18e3-d5a7-4383-929b-63561c8f9729","value":1}
[debug] [WD Proxy] Matched '/appium/device/system_bars' to command name 'getSystemBars'
[debug] [WD Proxy] Proxying [GET /appium/device/system_bars] to [GET http://127.0.0.1:8201/wd/hub/session/7cde18e3-d5a7-4383-929b-63561c8f9729/appium/device/system_bars] with body: {}
[debug] [WD Proxy] Got response with status 200: {"sessionId":"7cde18e3-d5a7-4383-929b-63561c8f9729","value":{"statusBar":24}}
[debug] [WD Proxy] Matched '/window/current/size' to command name 'getWindowSize'
[debug] [WD Proxy] Proxying [GET /window/current/size] to [GET http://127.0.0.1:8201/wd/hub/session/7cde18e3-d5a7-4383-929b-63561c8f9729/window/current/size] with body: {}
[debug] [WD Proxy] Got response with status 200: {"sessionId":"7cde18e3-d5a7-4383-929b-63561c8f9729","value":{"height":720,"width":1024}}
[Appium] New AndroidUiautomator2Driver session created successfully, session cbf52f09-58ba-43ee-aa5d-bbeddb8b024d added to master session list
**[Appium] Closing session, cause was 'Unexpected shutdown'**
[Appium] Removing session cbf52f09-58ba-43ee-aa5d-bbeddb8b024d from our master session list
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1575994537743 (00:15:37 GMT+0800 (GMT+08:00))
[debug] [W3C (cbf52f09)] Cached the protocol value 'W3C' for the new session cbf52f09-58ba-43ee-aa5d-bbeddb8b024d
[debug] [W3C (cbf52f09)] Responding to client with driver.createSession() result: {"capabilities":{"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platformName":"Android","appPackage":"com.android.settings","appActivity":"com.android.settings.Settings","unicodeKeyboard":true,"resetKeyboard":true,"automationName":"uiautomator2","platformVersion":"9","deviceName":"10.96.2.42:5555","noReset":true},"platformName":"Android","appPackage":"com.android.settings","appActivity":"com.android.settings.Settings","unicodeKeyboard":true,"resetKeyboard":true,"automationName":"uiautomator2","platformVersion":"9","deviceName":"10.96.2.42:5555","noReset":true,"deviceUDID":"10.96.2.42:5555","deviceApiLevel":28,"deviceScreenSize":"1024x768","deviceScreenDensity":160,"deviceModel":"VMware Virtual Platform","deviceManufacturer":"VMware, Inc.","pixelRatio":1,"statBarHeight":24,"viewportRect":{"left":0,"top":24,"width":1024,"height":696}}}
[HTTP] <-- POST /wd/hub/session 200 5220 ms - 1065
[HTTP]
[HTTP] --> GET /wd/hub/session/cbf52f09-58ba-43ee-aa5d-bbeddb8b024d/source
[HTTP] {}
[debug] [W3C (cbf52f09)] Encountered internal error running command: NoSuchDriverError: A session is either terminated or not started
[debug] [W3C (cbf52f09)]     at asyncHandler (/root/.nvm/versions/node/v12.5.0/lib/node_modules/appium/node_modules/_appium-base-driver@3.21.2@appium-base-driver/lib/protocol/protocol.js:231:15)
[debug] [W3C (cbf52f09)]     at /root/.nvm/versions/node/v12.5.0/lib/node_modules/appium/node_modules/_appium-base-driver@3.21.2@appium-base-driver/lib/protocol/protocol.js:410:15
[debug] [W3C (cbf52f09)]     at Layer.handle [as handle_request] (/root/.nvm/versions/node/v12.5.0/lib/node_modules/appium/node_modules/_express@4.17.1@express/lib/router/layer.js:95:5)
[debug] [W3C (cbf52f09)]     at next (/root/.nvm/versions/node/v12.5.0/lib/node_modules/appium/node_modules/_express@4.17.1@express/lib/router/route.js:137:13)
[debug] [W3C (cbf52f09)]     at Route.dispatch (/root/.nvm/versions/node/v12.5.0/lib/node_modules/appium/node_modules/_express@4.17.1@express/lib/router/route.js:112:3)
[debug] [W3C (cbf52f09)]     at Layer.handle [as handle_request] (/root/.nvm/versions/node/v12.5.0/lib/node_modules/appium/node_modules/_express@4.17.1@express/lib/router/layer.js:95:5)
[debug] [W3C (cbf52f09)]     at /root/.nvm/versions/node/v12.5.0/lib/node_modules/appium/node_modules/_express@4.17.1@express/lib/router/index.js:281:22
[debug] [W3C (cbf52f09)]     at param (/root/.nvm/versions/node/v12.5.0/lib/node_modules/appium/node_modules/_express@4.17.1@express/lib/router/index.js:354:14)
[debug] [W3C (cbf52f09)]     at param (/root/.nvm/versions/node/v12.5.0/lib/node_modules/appium/node_modules/_express@4.17.1@express/lib/router/index.js:365:14)
[debug] [W3C (cbf52f09)]     at Function.process_params (/root/.nvm/versions/node/v12.5.0/lib/node_modules/appium/node_modules/_express@4.17.1@express/lib/router/index.js:410:3)
[debug] [W3C (cbf52f09)]     at next (/root/.nvm/versions/node/v12.5.0/lib/node_modules/appium/node_modules/_express@4.17.1@express/lib/router/index.js:275:10)
[debug] [W3C (cbf52f09)]     at logger (/root/.nvm/versions/node/v12.5.0/lib/node_modules/appium/node_modules/_morgan@1.9.1@morgan/index.js:144:5)
[debug] [W3C (cbf52f09)]     at Layer.handle [as handle_request] (/root/.nvm/versions/node/v12.5.0/lib/node_modules/appium/node_modules/_express@4.17.1@express/lib/router/layer.js:95:5)
[debug] [W3C (cbf52f09)]     at trim_prefix (/root/.nvm/versions/node/v12.5.0/lib/node_modules/appium/node_modules/_express@4.17.1@express/lib/router/index.js:317:13)
[debug] [W3C (cbf52f09)]     at /root/.nvm/versions/node/v12.5.0/lib/node_modules/appium/node_modules/_express@4.17.1@express/lib/router/index.js:284:7
[debug] [W3C (cbf52f09)]     at Function.process_params (/root/.nvm/versions/node/v12.5.0/lib/node_modules/appium/node_modules/_express@4.17.1@express/lib/router/index.js:335:12)
[debug] [W3C (cbf52f09)]     at next (/root/.nvm/versions/node/v12.5.0/lib/node_modules/appium/node_modules/_express@4.17.1@express/lib/router/index.js:275:10)
[debug] [W3C (cbf52f09)]     at jsonParser (/root/.nvm/versions/node/v12.5.0/lib/node_modules/appium/node_modules/_body-parser@1.19.0@body-parser/lib/types/json.js:110:7)
[debug] [W3C (cbf52f09)]     at Layer.handle [as handle_request] (/root/.nvm/versions/node/v12.5.0/lib/node_modules/appium/node_modules/_express@4.17.1@express/lib/router/layer.js:95:5)
[debug] [W3C (cbf52f09)]     at trim_prefix (/root/.nvm/versions/node/v12.5.0/lib/node_modules/appium/node_modules/_express@4.17.1@express/lib/router/index.js:317:13)
[debug] [W3C (cbf52f09)]     at /root/.nvm/versions/node/v12.5.0/lib/node_modules/appium/node_modules/_express@4.17.1@express/lib/router/index.js:284:7
[debug] [W3C (cbf52f09)]     at Function.process_params (/root/.nvm/versions/node/v12.5.0/lib/node_modules/appium/node_modules/_express@4.17.1@express/lib/router/index.js:335:12)
[HTTP] <-- GET /wd/hub/session/cbf52f09-58ba-43ee-aa5d-bbeddb8b024d/source 404 23 ms - 3385
[HTTP]
```

## Code To Reproduce Issue [ Good To Have ]

```python
from appium import webdriver
import time
if __name__ == '__main__':
    desired_caps = {
        'platformName': 'Android',
        'appPackage': 'com.android.settings',
        'appActivity': 'com.android.settings.Settings',
        'unicodeKeyboard': 'true',
        'resetKeyboard': 'true',
        'automationName': 'uiautomator2',
        'platformName': 'Android',
        'platformVersion': '9',
        'deviceName': '10.96.2.42:5555',
        'noReset': True
        }
    _driver = webdriver.Remote("127.0.0.1:4723/wd/hub", desired_caps)
    print(_driver.session_id)
    print(_driver.page_source)
```

**Result**

```shell
Traceback (most recent call last):
  File "/tmp/test.sh", line 25, in <module>
    print(_driver.page_source)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 679, in page_source
    return self.execute(Command.GET_PAGE_SOURCE)['value']
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/appium/webdriver/errorhandler.py", line 29, in check_response
    raise wde
  File "/usr/local/lib/python3.7/site-packages/appium/webdriver/errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: A session is either terminated or not started
```

**Comment by mykola-mokhnach** [comment]
Please use the most recent version of the server

**Comment by qwertyI** [comment]
This is not a server version issue. I used 1.13.0 on my Mac, but it failed on ContOS.

**Comment by mykola-mokhnach** [comment]
Unfortunately I cannot help nothing then if the Appium version cannot be updated
