### ISSUE TITLE
Timeout while finding element for Web App in iOS 13.* series with Appium 1.15.1

### ISSUE THREAD

**Issue by shibupanda** [appium/appium#13723]
## The problem
Find Element and Find Elements stuck with **Did not get any response after 300s** Error

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe): 10.*
* Npm or Yarn package manager:
* Mobile platform/version under test: iOS v13.* browser automation
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI
* Java Client: 6.0.0, 7.0.0, 7.2.0, 7.3.0
* Nunit Client(Appium.Webdriver nuget): 3.0.0, 4.1.1

## Details
2019-12-15 13:00:00:435 [MJSONWP (7f2870e5)] Encountered internal error running command: Error: Did not get any response after 300s
2019-12-15 13:00:00:436 [MJSONWP (7f2870e5)]     at XCUITestDriver.waitForAtom (/Users/radmin/.npm-packages/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/web.js:280:13)

## Link to Appium logs
https://gist.github.com/shibupanda/b01aae37fb8e4f709230234bb77511c1

## Code To Reproduce Issue [ Good To Have ]
Run any browser automation on iOS 13.* series devices and find any element.

**Comment by mykola-mokhnach** [comment]
Please try appium@beta

**Comment by shibupanda** [comment]
Sure @mykola-mokhnach let me check.

**Comment by shibupanda** [comment]
@mykola-mokhnach 
With 1.16.0-Beta3 driver it is not created due to below error.

2019-12-16 12:02:00:051 [iProxy@8710332c] Error: Connection was refused to port 30065
2019-12-16 12:02:00:051 [iProxy@8710332c]     at Usbmux.connect (/.npm-packages/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-ios-device/lib/usbmux/index.js:207:13)

https://gist.github.com/shibupanda/b795245e7d44d4ac9122b0bb41964663

**Comment by mykola-mokhnach** [comment]
I don't observe any errors in the log above

**Comment by shibupanda** [comment]
@mykola-mokhnach 
Please check **Connection was refused to port 30065** keyword you'll get below error in logs.
2019-12-16 12:02:00:051 [iProxy@8710332c] Error: Connection was refused to port 30065
2019-12-16 12:02:00:051 [iProxy@8710332c]     at Usbmux.connect (/Users/radmin/.npm-packages/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-ios-device/lib/usbmux/index.js:207:13)

And this is happening with Appium version 1.16.*

**Comment by mykola-mokhnach** [comment]
This is normal - the driver has sent the /status request to the server and got no response becasue the server was not running. Then xcodebuild has been executed in order to compile and kick the WDA server startup on the device under test. Although, there is no further logs

**Comment by shibupanda** [comment]
Let me send you the complete logs then.
But time being it has been resolved in appium 1.14.2.

**Comment by mykola-mokhnach** [comment]
Closed because of no reponse
