### ISSUE TITLE
org.openqa.selenium.UnsupportedCommandException: Method is not implemented

### ISSUE THREAD

**Issue by Akhila666** [appium/appium#13794]
Hi ,

Please find below appium server log . i am using latest version of Java client 7.2 but i am facing method is not implemented error . pls help out this issue . 

[HTTP] --> POST /wd/hub/session/f15d7601-4f93-4e48-b9ae-b8693adc55ee/element
[HTTP] {"value":"//[@content-desc='YTD SS (CFC)']/following::android.view.View[1]","using":"xpath"}
[W3C (f15d7601)] Calling AppiumDriver.findElement() with args: ["xpath","//[@content-desc='YTD SS (CFC)']/following::android.view.View[1]","f15d7601-4f93-4e48-b9ae-b8693adc55ee"]
[BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[BaseDriver] Waiting up to 0 ms for condition
[WD Proxy] Matched '/element' to command name 'findElement'
[WD Proxy] Proxying [POST /element] to [POST http://localhost:8222/wd/hub/session/39b5a19c-2ce4-4971-bcb5-ccc96495bbe4/element] with body: {"strategy":"xpath","selector":"//*[@content-desc='YTD SS (CFC)']/following::android.view.View[1]","context":"","multiple":false}
[WD Proxy] Got response with status 200: {"sessionId":"39b5a19c-2ce4-4971-bcb5-ccc96495bbe4","value":{"ELEMENT":"cf89e981-9c79-4c76-8cce-02a4ea37e43b","element-6066-11e4-a52e-4f735466cecf":"cf89e981-9c79-4c76-8cce-02a4ea37e43b"}}
[W3C (f15d7601)] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"cf89e981-9c79-4c76-8cce-02a4ea37e43b","ELEMENT":"cf89e981-9c79-4c76-8cce-02a4ea37e43b"}
[HTTP] <-- POST /wd/hub/session/f15d7601-4f93-4e48-b9ae-b8693adc55ee/element 200 771 ms - 137
[HTTP]
[HTTP] --> POST /wd/hub/session/f15d7601-4f93-4e48-b9ae-b8693adc55ee/execute/sync
[HTTP] {"script":"return (function(){return function(){var d=this;function f(a){return"string"==typeof a};function h(a,b){this.code=a;this.a=l[a]||m;this.message=b||"";a=this.a.replace(/((?:^|\s+)[a-z])/g,function(a){return a.toUpperCase().replace(/^[\s\xa0]+/g,"")});b=a.length-5;if(0>b||a.indexOf("Error",b)!=b)a+="Error";this.name=a;a=Error(this.message);a.name=this.name;this.stack=a.stack||""}\n(function(){var a=Error;function b(){}b.prototype=a.prototype;h.b=a.prototype;h.prototype=new b;h.prototype.constructor=h;h.a=function(b,c,g){for(var e=Array(arguments.length-2),k=2;k
[W3C (f15d7601)] Calling AppiumDriver.execute() with args: ["return (function(){return function(){var d=this;function f(a){return"string"==typeof a};function h(a,b){this.code=a;this.a=l[a]||m;this.message=b||"";a=this.a.replace(/((?:^|\s+)[a-z])/g,function(a){return a.toUpperCase().replace(/^[\s\xa0]+/g,"")});b=a.length-5;if(0>b||a.indexOf("Error",b)!=b)a+="Error";this.name=a;a=Error(this.message);a.name=this.name;this.stack=a.stack||""}\n(function(){var a=Error;function b(){}b.prototype=a.prototype;h.b=a.prototype;h.prototype=new b;h.prototype.constructor=h;h.a=function(b,c,g){for(var e=Array(arguments.length-2),k=2;k
[W3C (f15d7601)] Encountered internal error running command: NotImplementedError: Method is not implemented
[W3C (f15d7601)] at AndroidUiautomator2Driver.execute (/tmp/.mount_Appiumk7Fo0H/resources/app/node_modules/appium/node_modules/appium-android-driver/lib/commands/execute.js:14:11)
[W3C (f15d7601)] at curCommandCancellable._bluebird.default.resolve.then (/tmp/.mount_Appiumk7Fo0H/resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:353:75)
[W3C (f15d7601)] at tryCatcher (/tmp/.mount_Appiumk7Fo0H/resources/app/node_modules/appium/node_modules/bluebird/js/release/util.js:16:23)
[W3C (f15d7601)] at Promise._settlePromiseFromHandler (/tmp/.mount_Appiumk7Fo0H/resources/app/node_modules/appium/node_modules/bluebird/js/release/promise.js:547:31)
[W3C (f15d7601)] at Promise._settlePromise (/tmp/.mount_Appiumk7Fo0H/resources/app/node_modules/appium/node_modules/bluebird/js/release/promise.js:604:18)
[W3C (f15d7601)] at Promise._settlePromiseCtx (/tmp/.mount_Appiumk7Fo0H/resources/app/node_modules/appium/node_modules/bluebird/js/release/promise.js:641:10)
[W3C (f15d7601)] at _drainQueueStep (/tmp/.mount_Appiumk7Fo0H/resources/app/node_modules/appium/node_modules/bluebird/js/release/async.js:97:12)
[W3C (f15d7601)] at _drainQueue (/tmp/.mount_Appiumk7Fo0H/resources/app/node_modules/appium/node_modules/bluebird/js/release/async.js:86:9)
[W3C (f15d7601)] at Async._drainQueues (/tmp/.mount_Appiumk7Fo0H/resources/app/node_modules/appium/node_modules/bluebird/js/release/async.js:102:5)
[W3C (f15d7601)] at Immediate.Async.drainQueues (/tmp/.mount_Appiumk7Fo0H/resources/app/node_modules/appium/node_modules/bluebird/js/release/async.js:15:14)
[W3C (f15d7601)] at runCallback (timers.js:696:18)
[W3C (f15d7601)] at tryOnImmediate (timers.js:667:5)
[W3C (f15d7601)] at processImmediate (timers.js:649:5)
[HTTP] <-- POST /wd/hub/session/f15d7601-4f93-4e48-b9ae-b8693adc55ee/execute/sync 405 13 ms - 1725
[HTTP]

**Comment by mykola-mokhnach** [comment]
This is not a server issue.  The problem lies in the client. Like I said it is either outdated or the driver instance itself is not created properly.
