### ISSUE TITLE
Error when running ios-basic-interactions.test.js

### ISSUE THREAD

**Issue by arielelkin** [appium/appium#13860]
## The problem

I am trying to run the [ios-basic-interactions.test.js](https://github.com/appium/appium/blob/master/sample-code/javascript-wd/test/basic/ios-basic-interactions.test.js) but an error is thrown immediately after I try to run the test.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.16.0
* Desktop OS/version used to run Appium: macOS 10.14.6
* Node.js version (unless using Appium.app|exe): 13.6.0
* Mobile platform/version under test: iOS 13
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI

## Code To Reproduce Issue [ Good To Have ]

```
$ appium & node ios-basic-interactions.test.js 
[1] 32187
(node:32188) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
/Users/me/app/ios-basic-interactions.test.js:1
import wd from 'wd';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1060:16)
    at Module._compile (internal/modules/cjs/loader.js:1108:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
me:~/app $ [Appium] Welcome to Appium v1.16.0
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
```

**Comment by mykola-mokhnach** [comment]
the module must be transpiled before execution. The error is expected

**Comment by arielelkin** [comment]
this is a documentation issue then, as I followed the instructions on the homepage:

![image](https://user-images.githubusercontent.com/1756909/72811461-a0740200-3c57-11ea-8dbe-7161b4b172c7.png)

and here:
https://github.com/appium/appium/tree/master/sample-code/javascript-webdriverio#running-tests

Can you please let me know what are the other steps I need to do?

**Comment by mykola-mokhnach** [comment]
The readme describes the process properly. Tests should be run using `mocha` or `npm test` script, which are configured to properly run the preparation steps in advance. If you prefer to run the scripts by node directly then make sure to also do the preparation jobs first.

**Comment by arielelkin** [comment]
Well I thought that the "Easy setup process" took care of the preparation jobs... It would be good if that piece of the docs on the  homepage would explain what the preparation jobs were.

Note that running the tests with `mocha` doesn't seem to work either:

```
$ npm install
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN webdriverio-sample-appium-tests@1.0.0 No repository field.

added 222 packages from 617 contributors and audited 592 packages in 3.326s

17 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

$ mocha ios-basic-interactions.test.js 
/usr/local/lib/node_modules/mocha/node_modules/yargs/yargs.js:1163
      else throw err
           ^

Error: Cannot find module '../../helpers/caps'
Require stack:
- /Users/me/app/ios-basic-interactions.test.js
- /usr/local/lib/node_modules/mocha/lib/mocha.js
- /usr/local/lib/node_modules/mocha/lib/cli/one-and-dones.js
- /usr/local/lib/node_modules/mocha/lib/cli/options.js
- /usr/local/lib/node_modules/mocha/bin/mocha
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:973:15)
    at Function.Module._load (internal/modules/cjs/loader.js:855:27)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/me/app/ios-basic-interactions.test.js:2:20)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at /usr/local/lib/node_modules/mocha/lib/mocha.js:308:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/usr/local/lib/node_modules/mocha/lib/mocha.js:305:14)
    at Mocha.run (/usr/local/lib/node_modules/mocha/lib/mocha.js:846:10)
    at Object.exports.singleRun (/usr/local/lib/node_modules/mocha/lib/cli/run-helpers.js:108:16)
    at exports.runMocha (/usr/local/lib/node_modules/mocha/lib/cli/run-helpers.js:143:13)
    at Object.exports.handler (/usr/local/lib/node_modules/mocha/lib/cli/run.js:305:3)
    at Object.runCommand (/usr/local/lib/node_modules/mocha/node_modules/yargs/lib/command.js:242:26)
    at Object.parseArgs [as _parseArgs] (/usr/local/lib/node_modules/mocha/node_modules/yargs/yargs.js:1087:28)
    at Object.parse (/usr/local/lib/node_modules/mocha/node_modules/yargs/yargs.js:566:25)
    at Object.exports.main (/usr/local/lib/node_modules/mocha/lib/cli/cli.js:68:6)
    at Object.<anonymous> (/usr/local/lib/node_modules/mocha/bin/mocha:133:29)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/me/app/ios-basic-interactions.test.js',
    '/usr/local/lib/node_modules/mocha/lib/mocha.js',
    '/usr/local/lib/node_modules/mocha/lib/cli/one-and-dones.js',
    '/usr/local/lib/node_modules/mocha/lib/cli/options.js',
    '/usr/local/lib/node_modules/mocha/bin/mocha'
  ]
}
```

**Comment by euoia** [comment]
I just wanted to say this was the first thing I tried to do too, and I found the same error. I am still not entirely sure how it's supposed to be resolved, I followed the instructions in the README.

```
sample-code|master ⇒ $(npm bin)/mocha javascript-wd/test/basic/ios-basic-interactions.test.js

/Users/jamespickard/Code/tmp/appium/sample-code/javascript-wd/test/basic/ios-basic-interactions.test.js:1
```

From the instructions here:
https://github.com/appium/appium/blob/master/sample-code/README.md

**Comment by euoia** [comment]
Responding to my own comment, I may have been running the command from the wrong directory.

After running `npm test` in the `sample-code` directory, and then changing to the `javascript-wd` and re-running the command:
`javascript-wd|master ⇒ $(npm bin)/mocha test/basic/ios-basic-interactions.test.js`

I no longer got the previous error. I got another error, but it's probably unrelated.

**Comment by Andrewngabriel** [comment]
@mykola-mokhnach I have done a bit of research in this issue and was able to reproduce the errors. It seems like mocha library was updated as of version 8 to [no longer acknowledge `mocha.opts`](https://mochajs.org/#-opts-path) for configuration and instead use any user defined [configuration from `package.json`](https://mochajs.org/#configuring-mocha-nodejs). I was able to refactor the timeout configuration and all the tests are executing normally now. I just opened a PR to fix this [here](https://github.com/appium/appium/pull/15149).

**Comment by Andrewngabriel** [comment]
PR just merged so this issue can be closed

**Comment by biaji** [comment]
Ok,  I'm facing the same here, maybe there still something wrong or misconfigration:

```
 pwd
..../appium-master/sample-code/javascript-wd 

npm -v
6.14.6

npm run test

> javascript-wd@1.0.0 test /Users/biaji/workspace/zte/Tests/appium-master/sample-code/javascript-wd
> mocha test/**/*.test.js


/Users/biaji/workspace/zte/Tests/appium-master/sample-code/javascript-wd/test/basic/android-basic-interactions.test.js:1
import wd from 'wd';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.exports.requireOrImport (/Users/biaji/workspace/zte/Tests/appium-master/sample-code/javascript-wd/node_modules/mocha/lib/esm-utils.js:42:12)
    at Object.exports.loadFilesAsync (/Users/biaji/workspace/zte/Tests/appium-master/sample-code/javascript-wd/node_modules/mocha/lib/esm-utils.js:55:34)
    at Mocha.loadFilesAsync (/Users/biaji/workspace/zte/Tests/appium-master/sample-code/javascript-wd/node_modules/mocha/lib/mocha.js:473:19)
    at singleRun (/Users/biaji/workspace/zte/Tests/appium-master/sample-code/javascript-wd/node_modules/mocha/lib/cli/run-helpers.js:125:15)
    at exports.runMocha (/Users/biaji/workspace/zte/Tests/appium-master/sample-code/javascript-wd/node_modules/mocha/lib/cli/run-helpers.js:190:10)
    at Object.exports.handler (/Users/biaji/workspace/zte/Tests/appium-master/sample-code/javascript-wd/node_modules/mocha/lib/cli/run.js:362:11)
    at /Users/biaji/workspace/zte/Tests/appium-master/sample-code/javascript-wd/node_modules/yargs/build/index.cjs:443:71
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! javascript-wd@1.0.0 test: `mocha test/**/*.test.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the javascript-wd@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/biaji/.npm/_logs/2021-08-03T08_51_16_241Z-debug.log

```

It's wired the complain of "SyntaxError: Cannot use import statement outside a module".
