### ISSUE TITLE
Tap is not working using coordinates 

### ISSUE THREAD

**Issue by waqaszulfiqar** [appium/appium#13871]
## The problem

Appium- node.js - I am using this touch function and want to tap on this specific coordinate. But it gives me an error

Environment

* Appium version= 1.15.1
* Android 9.0

 Link to Appium logs[0-0] Error in "undefined"
unknown error: An unknown server-side error occurred while processing the command. Original error: unknown action undefined

Code To Reproduce Issue 

driver.touchAction({actions: 'tap', x: 269, y: 1605})

**Comment by mykola-mokhnach** [comment]
Please provide the full server log

**Comment by waqaszulfiqar** [comment]
@mykola-mokhnach 
here are the complete logs 

ERROR webdriver: Request failed due to unknown error: An unknown server-side error occurred while processing the command. Original error: unknown action undefined
    at getErrorFromResponseBody (F:\BUS AUTOMATION\bus.automation\node_modules\webdriver\build\utils.js:349:10)
    at Request._callback (F:\BUS AUTOMATION\bus.automation\node_modules\webdriver\build\request.js:121:64)
    at Request.self.callback (F:\BUS AUTOMATION\bus.automation\node_modules\request\request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.EventEmitter.emit (domain.js:475:20)
    at Request.<anonymous> (F:\BUS AUTOMATION\bus.automation\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:210:5)
    at Request.EventEmitter.emit (domain.js:475:20)
    at IncomingMessage.<anonymous> (F:\BUS AUTOMATION\bus.automation\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:299:28)
[0-0] Error in "undefined"
unknown error: An unknown server-side error occurred while processing the command. Original error: unknown action undefined

**Comment by mykola-mokhnach** [comment]
This is the error in the client code rather than in the server one. Consider reporting your issue to an appropriate tracker.

**Comment by waqaszulfiqar** [comment]
it's working fine on the Appium server. 
And I copy those commands from appium to my code than they don't work.

**Comment by mykola-mokhnach** [comment]
Unfortunately ew cannot help there. You could also try to ask at Appium forum
