### ISSUE TITLE
'XCUIHitPointResult.h' file not found

### ISSUE THREAD

**Issue by eclaires** [appium/appium#13992]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

We run automated tests on Android and iOS devices hooked to Jenkins slaves. Everything was working until we updated to xCode11/ Appium 1.16.0 and now  fails to install our app.

## Environment

* Appium version :  1.16.0
* Last Appium version that did not exhibit the issue :  1.14.0
* Desktop OS/version used to run Appium: MacOS 10.15.2
* Node.js version (unless using Appium.app|exe): 13.7.0
* Npm or Yarn package manager:
* Mobile platform: iOS
* Real device: YES
* Appium CLI

## Details

We manually sign our app and set WebDriverAgent
{
      "xcodeOrgId": "<Team ID>",
      "xcodeSigningId": "iPhone Developer"
}
I haven't been able to find a way to successfully run the automation tests for iOS since we updated. I worked around the signing errors I was getting (i think) but am now getting this:

2020-02-26 01:06:30:463 [Appium] Welcome to Appium v1.16.0
2020-02-26 01:06:30:465 [Appium] Non-default server args:
2020-02-26 01:06:30:465 [Appium]   port: 5000
2020-02-26 01:06:30:466 [Appium]   bootstrapPort: 6000
2020-02-26 01:06:30:466 [Appium]   launch: true
2020-02-26 01:06:30:467 [Appium]   logFile: /Users/jenkins/jenkins_home/workspace/xxx/QA/test2/appium/appium.log
2020-02-26 01:06:30:467 [Appium]   logTimestamp: true
2020-02-26 01:06:30:467 [Appium]   tmpDir: /Users/jenkins/jenkins_home/workspace/xxx/QA/test2/appium
2020-02-26 01:06:30:468 [Appium]   defaultCapabilities: {
2020-02-26 01:06:30:468 [Appium]     app: /Users/jenkins/jenkins_home/workspace/xxx/QA/test2/build.ipa
2020-02-26 01:06:30:468 [Appium]     udid: 21efcf552099fd3ec031cff44543f9e4eb5a7c9c
2020-02-26 01:06:30:469 [Appium]     platformName: ios
2020-02-26 01:06:30:469 [Appium]     platformVersion: 12.4.1
2020-02-26 01:06:30:469 [Appium]     deviceName:ABC
2020-02-26 01:06:30:470 [Appium]     showIOSLog: true
2020-02-26 01:06:30:470 [Appium]     bundleId: com.xxx.debug.yyy
2020-02-26 01:06:30:470 [Appium]     locationServicesEnabled: true
2020-02-26 01:06:30:470 [Appium]     autoAcceptAlerts: true
2020-02-26 01:06:30:471 [Appium]     xcodeOrgId: 37XXXXXXX
2020-02-26 01:06:30:471 [Appium]     xcodeSigningId: iPhone Developer
2020-02-26 01:06:30:471 [Appium]     useNewWDA: true
2020-02-26 01:06:30:472 [Appium]     updatedWDABundleId: com.xxx.debug.yyy
2020-02-26 01:06:30:472 [Appium]     showXcodeLog: true
2020-02-26 01:06:30:472 [Appium]     isHeadless: true
2020-02-26 01:06:30:472 [Appium]   }
2020-02-26 01:06:30:473 [Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
2020-02-26 01:06:30:473 [Appium]   app: /Users/jenkins/jenkins_home/workspace/xxx/QA/test2/build.ipa
2020-02-26 01:06:30:473 [Appium]   udid: 21efcf552099fd3ec031cff44543f9e4eb5a7c9c
2020-02-26 01:06:30:474 [Appium]   platformName: ios
2020-02-26 01:06:30:474 [Appium]   platformVersion: 12.4.1
2020-02-26 01:06:30:474 [Appium]   deviceName:ABC
2020-02-26 01:06:30:474 [Appium]   showIOSLog: true
2020-02-26 01:06:30:475 [Appium]   bundleId: com.xxx.debug.yyy
2020-02-26 01:06:30:475 [Appium]   locationServicesEnabled: true
2020-02-26 01:06:30:475 [Appium]   autoAcceptAlerts: true
2020-02-26 01:06:30:475 [Appium]   xcodeOrgId: 37XXXXXXX
2020-02-26 01:06:30:476 [Appium]   xcodeSigningId: iPhone Developer
2020-02-26 01:06:30:476 [Appium]   useNewWDA: true
2020-02-26 01:06:30:476 [Appium]   updatedWDABundleId: com.xxx.debug.yyy
2020-02-26 01:06:30:476 [Appium]   showXcodeLog: true
2020-02-26 01:06:30:477 [Appium]   isHeadless: true
2020-02-26 01:06:30:505 [Appium] Appium REST http interface listener started on 0.0.0.0:5000
2020-02-26 01:06:37:026 [HTTP] --> POST /wd/hub/session
2020-02-26 01:06:37:026 [HTTP] {"desiredCapabilities":{"platformName":"iOS"},"capabilities":{"desiredCapabilities":{"platformName":"iOS"},"firstMatch":[{"platformName":"ios"}]}}
2020-02-26 01:06:37:028 [W3C] Calling AppiumDriver.createSession() with args: [{"platformName":"iOS"},null,{"desiredCapabilities":{"platformName":"iOS"},"firstMatch":[{"platformName":"ios"}]}]
2020-02-26 01:06:37:029 [BaseDriver] Event 'newSessionRequested' logged at 1582679197028 (17:06:37 GMT-0800 (GMT-08:00))
2020-02-26 01:06:37:032 [BaseDriver] The capabilities ["app","udid","platformVersion","deviceName","showIOSLog","bundleId","locationServicesEnabled","autoAcceptAlerts","xcodeOrgId","xcodeSigningId","useNewWDA","updatedWDABundleId","showXcodeLog","isHeadless"] are not standard capabilities and should have an extension prefix
2020-02-26 01:06:37:036 [Appium] DeprecationWarning: 'automationName' capability was not provided. Future versions of Appium will require 'automationName' capability to be set for iOS sessions.
2020-02-26 01:06:37:037 [Appium] Requested iOS support with version >= 10, using 'XCUITest' driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
2020-02-26 01:06:37:512 [Appium] Appium v1.16.0 creating new XCUITestDriver (v3.10.1) session
2020-02-26 01:06:37:515 [BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
2020-02-26 01:06:37:515 [BaseDriver] Creating session with W3C capabilities: {
2020-02-26 01:06:37:515 [BaseDriver]   "alwaysMatch": {
2020-02-26 01:06:37:516 [BaseDriver]     "platformName": "ios",
2020-02-26 01:06:37:516 [BaseDriver]     "appium:app": "/Users/jenkins/jenkins_home/workspace/xxx/QA/test2/build.ipa",
2020-02-26 01:06:37:516 [BaseDriver]     "appium:udid": "21efcf552099fd3ec031cff44543f9e4eb5a7c9c",
2020-02-26 01:06:37:516 [BaseDriver]     "appium:platformVersion": "12.4.1",
2020-02-26 01:06:37:517 [BaseDriver]     "appium:deviceName": "Claire S",
2020-02-26 01:06:37:517 [BaseDriver]     "appium:showIOSLog": true,
2020-02-26 01:06:37:517 [BaseDriver]     "appium:bundleId": "com.xxx.debug.yyy",
2020-02-26 01:06:37:517 [BaseDriver]     "appium:locationServicesEnabled": true,
2020-02-26 01:06:37:518 [BaseDriver]     "appium:autoAcceptAlerts": true,
2020-02-26 01:06:37:518 [BaseDriver]     "appium:xcodeOrgId": "37xxxxxxx",
2020-02-26 01:06:37:518 [BaseDriver]     "appium:xcodeSigningId": "iPhone Developer",
2020-02-26 01:06:37:518 [BaseDriver]     "appium:useNewWDA": true,
2020-02-26 01:06:37:518 [BaseDriver]     "appium:updatedWDABundleId": "com.xxx.debug.yyy",
2020-02-26 01:06:37:519 [BaseDriver]     "appium:showXcodeLog": true,
2020-02-26 01:06:37:519 [BaseDriver]     "appium:isHeadless": true
2020-02-26 01:06:37:519 [BaseDriver]   },
2020-02-26 01:06:37:519 [BaseDriver]   "firstMatch": [
2020-02-26 01:06:37:520 [BaseDriver]     {}
2020-02-26 01:06:37:520 [BaseDriver]   ]
2020-02-26 01:06:37:520 [BaseDriver] }
2020-02-26 01:06:37:530 [BaseDriver] Session created with session id: d2f03112-0a1b-4d15-bbff-4ae193f5c8ae

...

2020-02-26 01:10:43:335 [W3C] Test session results, code coverage, and logs:
2020-02-26 01:10:43:335 [W3C] 	/Users/jenkins/Library/Developer/Xcode/DerivedData/WebDriverAgent-aiaejbhejflmruhkhsmeebmhbaia/Logs/Test/Test-WebDriverAgentRunner-2020.02.25_17-10-41--0800.xcresult
2020-02-26 01:10:43:335 [W3C] Testing started on 'Claire Sâ€™s iPhone'
2020-02-26 01:10:43:335 [W3C] Testing failed:
2020-02-26 01:10:43:335 [W3C] 	'XCUIHitPointResult.h' file not found
2020-02-26 01:10:43:336 [W3C] 	WebDriverAgentRunner:
2020-02-26 01:10:43:336 [W3C] 		WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: The file â€œWebDriverAgentRunner-Runnerâ€ couldnâ€™t be opened because you donâ€™t have permission to view it. You donâ€™t have permission. (Underlying error: The operation couldnâ€™t be completed. Permission denied)))
2020-02-26 01:10:43:336 [W3C] ** TEST EXECUTE FAILED **. Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
2020-02-26 01:10:43:336 [W3C]     at quitAndUninstall (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:519:15)
2020-02-26 01:10:43:336 [W3C]     at /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:549:11
2020-02-26 01:10:43:336 [W3C]     at wrapped (/usr/local/lib/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:35:13)
2020-02-26 01:10:43:336 [W3C]     at retry (/usr/local/lib/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:18:13)
2020-02-26 01:10:43:336 [W3C]     at retryInterval (/usr/local/lib/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:45:10)
2020-02-26 01:10:43:336 [W3C]     at /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:529:7
2020-0

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Make sure Appium has been installed properly. The mentioned header file does exist in the dist: https://github.com/appium/WebDriverAgent/blob/master/PrivateHeaders/XCTest/XCUIHitPointResult.h

**Comment by mykola-mokhnach** [comment]
Actually, it is possible to just copy that file manually to the desired location or use appium@beta

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by eclaires** [comment]
That was the problem! I uninstalled Appium and reinstalled to a specific version using npm install -g appium@$1.16.0 and it fixed the issue. Thank You!
