### ISSUE TITLE
 Encountered internal error running command: Error: Failed to launch Appium Settings app

### ISSUE THREAD

**Issue by xuwintery** [appium/appium#14010]
## The problem

 Encountered internal error running command: Error: Failed to launch Appium Settings app: Condition unmet after 5198 ms. Timing out

## Environment

Appium version ：Appium server  1.15.1
Mac OS : Mojave 10.14.4
Device ： SM-G9600 （Android 9）
desired_caps ：
desired_caps = {'deviceName': 'SM-G9600',
                'adbExecTimeout': '120000',
                'udid': '2c11ce08e53f7ece',
                'automationName': 'Uiautomator2',
                'systemPort': 8201,
                'noReset': True,
                'deviceReadyTimeout': '10000',
                'newCommandTimeout': '600',
                'platformVersion': '9',
                'connectHardwareKeyboard': False,
                'platformName': 'Android',           
         
    'app':'/Users/encompass/.jenkins/workspace/Android_DSDLinkTest_daily/Tool/Encompass.apk'}

## Details

When I started "appium" it would fail occasionally and could not work steadily，
I think it's because appium can't get its process ID when it starts，But it works when I execute this command alone
Appium logs：

2020-02-28 16:54:51:763 [Appium] Welcome to Appium v1.15.1
2020-02-28 16:54:51:764 [Appium] Non-default server args:
2020-02-28 16:54:51:765 [Appium]   address: 127.0.0.1
2020-02-28 16:54:51:765 [Appium]   logFile: /Users/encompass/.jenkins/workspace/Android_DSDLinkTest_daily/run_log/Android_DSDLinkTest_daily_460.log
2020-02-28 16:54:51:765 [Appium]   localTimezone: true
2020-02-28 16:54:51:790 [Appium] Appium REST http interface listener started on 127.0.0.1:4723
2020-02-28 16:54:53:714 [HTTP] --> POST /wd/hub/session
2020-02-28 16:54:53:714 [HTTP] {"capabilities":{"firstMatch":[{"appium:adbExecTimeout":"120000","appium:udid":"2c11ce08e53f7ece","appium:noReset":true,"appium:automationName":"Uiautomator2","appium:newCommandTimeout":"60000","appium:app":"/Users/encompass/.jenkins/workspace/Android_DSDLinkTest_daily/Tool/Encompass.apk","appium:deviceReadyTimeout":"100000","appium:deviceName":"SM-G9600","appium:platformVersion":"9","appium:connectHardwareKeyboard":false,"platformName":"Android","appium:systemPort":"7183"}]},"desiredCapabilities":{"deviceName":"SM-G9600","adbExecTimeout":"120000","udid":"2c11ce08e53f7ece","automationName":"Uiautomator2","systemPort":"7183","noReset":true,"deviceReadyTimeout":"100000","newCommandTimeout":"60000","platformVersion":"9","connectHardwareKeyboard":false,"platformName":"Android","app":"/Users/encompass/.jenkins/workspace/Android_DSDLinkTest_daily/Tool/Encompass.apk"}}
2020-02-28 16:54:53:716 [W3C] Calling AppiumDriver.createSession() with args: [{"deviceName":"SM-G9600","adbExecTimeout":"120000","udid":"2c11ce08e53f7ece","automationName":"Uiautomator2","systemPort":"7183","noReset":true,"deviceReadyTimeout":"100000","newCommandTimeout":"60000","platformVersion":"9","connectHardwareKeyboard":false,"platformName":"Android","app":"/Users/encompass/.jenkins/workspace/Android_DSDLinkTest_daily/Tool/Encompass.apk"},null,{"firstMatch":[{"appium:adbExecTimeout":"120000","appium:udid":"2c11ce08e53f7ece","appium:noReset":true,"appium:automationName":"Uiautomator2","appium:newCommandTimeout":"60000","appium:app":"/Users/encompass/.jenkins/workspace/Android_DSDLinkTest_daily/Tool/Encompass.apk","appium:deviceReadyTimeout":"100000","appium:deviceName":"SM-G9600","appium:platformVersion":"9","appium:connectHardwareKeyboard":false,"platformName":"Android","appium:systemPort":"7183"}]}]
2020-02-28 16:54:53:717 [BaseDriver] Event 'newSessionRequested' logged at 1582880093717 (16:54:53 GMT+0800 (China Standard Time))
2020-02-28 16:54:53:723 [BaseDriver] Number capability passed in as string. Functionality may be compromised.
2020-02-28 16:54:53:834 [Appium] Appium v1.15.1 creating new AndroidUiautomator2Driver (v1.37.2) session
2020-02-28 16:54:53:836 [BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
2020-02-28 16:54:53:837 [BaseDriver] Creating session with W3C capabilities: {
2020-02-28 16:54:53:837 [BaseDriver]   "alwaysMatch": {
2020-02-28 16:54:53:837 [BaseDriver]     "platformName": "Android",
2020-02-28 16:54:53:837 [BaseDriver]     "appium:adbExecTimeout": "120000",
2020-02-28 16:54:53:837 [BaseDriver]     "appium:udid": "2c11ce08e53f7ece",
2020-02-28 16:54:53:837 [BaseDriver]     "appium:noReset": true,
2020-02-28 16:54:53:837 [BaseDriver]     "appium:automationName": "Uiautomator2",
2020-02-28 16:54:53:837 [BaseDriver]     "appium:newCommandTimeout": "60000",
2020-02-28 16:54:53:838 [BaseDriver]     "appium:app": "/Users/encompass/.jenkins/workspace/Android_DSDLinkTest_daily/Tool/Encompass.apk",
2020-02-28 16:54:53:838 [BaseDriver]     "appium:deviceReadyTimeout": "100000",
2020-02-28 16:54:53:838 [BaseDriver]     "appium:deviceName": "SM-G9600",
2020-02-28 16:54:53:838 [BaseDriver]     "appium:platformVersion": "9",
2020-02-28 16:54:53:838 [BaseDriver]     "appium:connectHardwareKeyboard": false,
2020-02-28 16:54:53:838 [BaseDriver]     "appium:systemPort": "7183"
2020-02-28 16:54:53:838 [BaseDriver]   },
2020-02-28 16:54:53:838 [BaseDriver]   "firstMatch": [
2020-02-28 16:54:53:838 [BaseDriver]     {}
2020-02-28 16:54:53:838 [BaseDriver]   ]
2020-02-28 16:54:53:839 [BaseDriver] }
2020-02-28 16:54:53:840 [BaseDriver] Number capability passed in as string. Functionality may be compromised.
2020-02-28 16:54:53:840 [BaseDriver] Number capability passed in as string. Functionality may be compromised.
2020-02-28 16:54:53:840 [BaseDriver] Number capability passed in as string. Functionality may be compromised.
2020-02-28 16:54:53:841 [BaseDriver] Number capability passed in as string. Functionality may be compromised.
2020-02-28 16:54:53:842 [BaseDriver] Capability 'newCommandTimeout' changed from string ('60000') to integer (60000). This may cause unexpected behavior
2020-02-28 16:54:53:842 [BaseDriver] Capability 'systemPort' changed from string ('7183') to integer (7183). This may cause unexpected behavior
2020-02-28 16:54:53:843 [BaseDriver] Capability 'deviceReadyTimeout' changed from string ('100000') to integer (100000). This may cause unexpected behavior
2020-02-28 16:54:53:843 [BaseDriver] Capability 'adbExecTimeout' changed from string ('120000') to integer (120000). This may cause unexpected behavior
2020-02-28 16:54:53:845 [BaseDriver] The following capabilities were provided, but are not recognized by Appium:
2020-02-28 16:54:53:846 [BaseDriver]   connectHardwareKeyboard
2020-02-28 16:54:53:847 [BaseDriver] Session created with session id: 5ef42b71-6df0-438a-9cc1-dc60d8b8bbfa
2020-02-28 16:54:53:876 [BaseDriver] Using local app '/Users/encompass/.jenkins/workspace/Android_DSDLinkTest_daily/Tool/Encompass.apk'
2020-02-28 16:54:53:876 [UiAutomator2] Checking whether app is actually present
2020-02-28 16:54:53:884 [ADB] Found 29 'build-tools' folders under '/Users/encompass/Library/androidsdk' (newest first):
2020-02-28 16:54:53:884 [ADB]     /Users/encompass/Library/androidsdk/build-tools/28.0.3
2020-02-28 16:54:53:884 [ADB]     /Users/encompass/Library/androidsdk/build-tools/28.0.2
2020-02-28 16:54:53:885 [ADB]     /Users/encompass/Library/androidsdk/build-tools/28.0.1
2020-02-28 16:54:53:885 [ADB]     /Users/encompass/Library/androidsdk/build-tools/28.0.0
2020-02-28 16:54:53:885 [ADB]     /Users/encompass/Library/androidsdk/build-tools/28.0.0-preview
2020-02-28 16:54:53:885 [ADB]     /Users/encompass/Library/androidsdk/build-tools/27.0.3
2020-02-28 16:54:53:885 [ADB]     /Users/encompass/Library/androidsdk/build-tools/27.0.2
2020-02-28 16:54:53:885 [ADB]     /Users/encompass/Library/androidsdk/build-tools/27.0.1
2020-02-28 16:54:53:885 [ADB]     /Users/encompass/Library/androidsdk/build-tools/27.0.0
2020-02-28 16:54:53:885 [ADB]     /Users/encompass/Library/androidsdk/build-tools/26.0.3
2020-02-28 16:54:53:885 [ADB]     /Users/encompass/Library/androidsdk/build-tools/26.0.2
2020-02-28 16:54:53:886 [ADB]     /Users/encompass/Library/androidsdk/build-tools/26.0.1
2020-02-28 16:54:53:886 [ADB]     /Users/encompass/Library/androidsdk/build-tools/26.0.0
2020-02-28 16:54:53:886 [ADB]     /Users/encompass/Library/androidsdk/build-tools/26.0.0-preview
2020-02-28 16:54:53:886 [ADB]     /Users/encompass/Library/androidsdk/build-tools/25.0.3
2020-02-28 16:54:53:886 [ADB]     /Users/encompass/Library/androidsdk/build-tools/25.0.2
2020-02-28 16:54:53:886 [ADB]     /Users/encompass/Library/androidsdk/build-tools/25.0.1
2020-02-28 16:54:53:886 [ADB]     /Users/encompass/Library/androidsdk/build-tools/25.0.0
2020-02-28 16:54:53:886 [ADB]     /Users/encompass/Library/androidsdk/build-tools/24.0.3
2020-02-28 16:54:53:887 [ADB]     /Users/encompass/Library/androidsdk/build-tools/24.0.2
2020-02-28 16:54:53:887 [ADB]     /Users/encompass/Library/androidsdk/build-tools/24.0.1
2020-02-28 16:54:53:887 [ADB]     /Users/encompass/Library/androidsdk/build-tools/24.0.0
2020-02-28 16:54:53:887 [ADB]     /Users/encompass/Library/androidsdk/build-tools/23.0.3
2020-02-28 16:54:53:887 [ADB]     /Users/encompass/Library/androidsdk/build-tools/23.0.2
2020-02-28 16:54:53:887 [ADB]     /Users/encompass/Library/androidsdk/build-tools/23.0.1
2020-02-28 16:54:53:887 [ADB]     /Users/encompass/Library/androidsdk/build-tools/22.0.1
2020-02-28 16:54:53:887 [ADB]     /Users/encompass/Library/androidsdk/build-tools/21.1.2
2020-02-28 16:54:53:887 [ADB]     /Users/encompass/Library/androidsdk/build-tools/20.0.0
2020-02-28 16:54:53:888 [ADB]     /Users/encompass/Library/androidsdk/build-tools/19.1.0
2020-02-28 16:54:53:888 [ADB] Using 'adb' from '/Users/encompass/Library/androidsdk/platform-tools/adb'
2020-02-28 16:54:53:888 [AndroidDriver] Retrieving device list
2020-02-28 16:54:53:889 [ADB] Trying to find a connected android device
2020-02-28 16:54:53:889 [ADB] Getting connected devices...
2020-02-28 16:54:53:899 [ADB] Connected devices: [{"udid":"2c11ce08e53f7ece","state":"device"},{"udid":"R28M3368Z1P","state":"device"}]
2020-02-28 16:54:53:899 [AndroidDriver] Using device: 2c11ce08e53f7ece
2020-02-28 16:54:53:900 [ADB] Using 'adb' from '/Users/encompass/Library/androidsdk/platform-tools/adb'
2020-02-28 16:54:53:900 [ADB] Setting device id to 2c11ce08e53f7ece
2020-02-28 16:54:53:901 [ADB] Running '/Users/encompass/Library/androidsdk/platform-tools/adb -P 5037 -s 2c11ce08e53f7ece shell getprop ro.build.version.sdk'
2020-02-28 16:54:53:970 [ADB] Current device property 'ro.build.version.sdk': 28
2020-02-28 16:54:53:970 [ADB] Running '/Users/encompass/Library/androidsdk/platform-tools/adb -P 5037 -s 2c11ce08e53f7ece shell getprop ro.build.version.release'
2020-02-28 16:54:54:030 [ADB] Current device property 'ro.build.version.release': 9
2020-02-28 16:54:54:030 [ADB] Device API level: 28
2020-02-28 16:54:54:030 [UiAutomator2] Relaxing hidden api policy
2020-02-28 16:54:54:031 [ADB] Running '/Users/encompass/Library/androidsdk/platform-tools/adb -P 5037 -s 2c11ce08e53f7ece shell settings put global hidden_api_policy_pre_p_apps 1'
2020-02-28 16:54:54:124 [ADB] Running '/Users/encompass/Library/androidsdk/platform-tools/adb -P 5037 -s 2c11ce08e53f7ece shell settings put global hidden_api_policy_p_apps 1'
2020-02-28 16:54:54:244 [ADB] Running '/Users/encompass/Library/androidsdk/platform-tools/adb -P 5037 -s 2c11ce08e53f7ece shell settings put global hidden_api_policy 1'
2020-02-28 16:54:54:364 [AndroidDriver] Parsing package and activity from app manifest
2020-02-28 16:54:54:365 [ADB] Using 'apkanalyzer' from '/Users/encompass/Library/androidsdk/tools/bin/apkanalyzer'
2020-02-28 16:54:54:366 [ADB] Starting '/Users/encompass/Library/androidsdk/tools/bin/apkanalyzer' with args ["-h","manifest","print","/Users/encompass/.jenkins/workspace/Android_DSDLinkTest_daily/Tool/Encompass.apk"]
2020-02-28 16:54:55:360 [ADB] Package name: 'com.dsdlink'
2020-02-28 16:54:55:360 [ADB] Main activity name: 'com.dsdlink.main.MainActivity'
2020-02-28 16:54:55:361 [AndroidDriver] Parsed package and activity are: com.dsdlink/com.dsdlink.main.MainActivity
2020-02-28 16:54:55:361 [ADB] Running '/Users/encompass/Library/androidsdk/platform-tools/adb -P 5037 -s 2c11ce08e53f7ece wait-for-device'
2020-02-28 16:54:55:368 [ADB] Running '/Users/encompass/Library/androidsdk/platform-tools/adb -P 5037 -s 2c11ce08e53f7ece shell echo ping'
2020-02-28 16:54:55:427 [AndroidDriver] Pushing settings apk to device...
2020-02-28 16:54:55:428 [ADB] Getting install status for io.appium.settings
2020-02-28 16:54:55:428 [ADB] Running '/Users/encompass/Library/androidsdk/platform-tools/adb -P 5037 -s 2c11ce08e53f7ece shell dumpsys package io.appium.settings'
2020-02-28 16:54:55:538 [ADB] 'io.appium.settings' is installed
2020-02-28 16:54:55:539 [ADB] Getting package info for 'io.appium.settings'
2020-02-28 16:54:55:539 [ADB] Running '/Users/encompass/Library/androidsdk/platform-tools/adb -P 5037 -s 2c11ce08e53f7ece shell dumpsys package io.appium.settings'
2020-02-28 16:54:55:658 [ADB] Starting '/Users/encompass/Library/androidsdk/tools/bin/apkanalyzer' with args ["manifest","print","/usr/local/lib/node_modules/appium/node_modules/io.appium.settings/apks/settings_apk-debug.apk"]
2020-02-28 16:54:56:625 [ADB] The version name of the installed 'io.appium.settings' is greater or equal to the application version name ('2.14.2' >= '2.14.2')
2020-02-28 16:54:56:626 [ADB] There is no need to install/upgrade '/usr/local/lib/node_modules/appium/node_modules/io.appium.settings/apks/settings_apk-debug.apk'
2020-02-28 16:54:56:626 [ADB] Getting IDs of all 'io.appium.settings' processes
2020-02-28 16:54:56:627 [ADB] Running '/Users/encompass/Library/androidsdk/platform-tools/adb -P 5037 -s 2c11ce08e53f7ece shell 'pgrep --help; echo $?''
2020-02-28 16:54:56:707 [ADB] Running '/Users/encompass/Library/androidsdk/platform-tools/adb -P 5037 -s 2c11ce08e53f7ece shell pgrep -f io\\.appium\\.settings'
2020-02-28 16:54:56:833 [ADB] Running '/Users/encompass/Library/androidsdk/platform-tools/adb -P 5037 -s 2c11ce08e53f7ece shell am start -n io.appium.settings/.Settings -a android.intent.action.MAIN -c android.intent.category.LAUNCHER'
2020-02-28 16:54:56:975 [ADB] Getting IDs of all 'io.appium.settings' processes
2020-02-28 16:54:56:975 [ADB] Running '/Users/encompass/Library/androidsdk/platform-tools/adb -P 5037 -s 2c11ce08e53f7ece shell pgrep -f io\\.appium\\.settings'
2020-02-28 16:54:57:456 [ADB] Getting IDs of all 'io.appium.settings' processes
2020-02-28 16:54:57:456 [ADB] Running '/Users/encompass/Library/androidsdk/platform-tools/adb -P 5037 -s 2c11ce08e53f7ece shell pgrep -f io\\.appium\\.settings'
2020-02-28 16:54:57:968 [ADB] Getting IDs of all 'io.appium.settings' processes
2020-02-28 16:54:57:969 [ADB] Running '/Users/encompass/Library/androidsdk/platform-tools/adb -P 5037 -s 2c11ce08e53f7ece shell pgrep -f io\\.appium\\.settings'
2020-02-28 16:54:58:492 [ADB] Getting IDs of all 'io.appium.settings' processes
2020-02-28 16:54:58:492 [ADB] Running '/Users/encompass/Library/androidsdk/platform-tools/adb -P 5037 -s 2c11ce08e53f7ece shell pgrep -f io\\.appium\\.settings'
2020-02-28 16:54:59:012 [ADB] Getting IDs of all 'io.appium.settings' processes
2020-02-28 16:54:59:012 [ADB] Running '/Users/encompass/Library/androidsdk/platform-tools/adb -P 5037 -s 2c11ce08e53f7ece shell pgrep -f io\\.appium\\.settings'
2020-02-28 16:54:59:560 [ADB] Getting IDs of all 'io.appium.settings' processes
2020-02-28 16:54:59:560 [ADB] Running '/Users/encompass/Library/androidsdk/platform-tools/adb -P 5037 -s 2c11ce08e53f7ece shell pgrep -f io\\.appium\\.settings'
2020-02-28 16:55:00:002 [ADB] Getting IDs of all 'io.appium.settings' processes
2020-02-28 16:55:00:003 [ADB] Running '/Users/encompass/Library/androidsdk/platform-tools/adb -P 5037 -s 2c11ce08e53f7ece shell pgrep -f io\\.appium\\.settings'
2020-02-28 16:55:00:439 [ADB] Getting IDs of all 'io.appium.settings' processes
2020-02-28 16:55:00:440 [ADB] Running '/Users/encompass/Library/androidsdk/platform-tools/adb -P 5037 -s 2c11ce08e53f7ece shell pgrep -f io\\.appium\\.settings'
2020-02-28 16:55:00:905 [ADB] Getting IDs of all 'io.appium.settings' processes
2020-02-28 16:55:00:905 [ADB] Running '/Users/encompass/Library/androidsdk/platform-tools/adb -P 5037 -s 2c11ce08e53f7ece shell pgrep -f io\\.appium\\.settings'
2020-02-28 16:55:01:455 [ADB] Getting IDs of all 'io.appium.settings' processes
2020-02-28 16:55:01:456 [ADB] Running '/Users/encompass/Library/androidsdk/platform-tools/adb -P 5037 -s 2c11ce08e53f7ece shell pgrep -f io\\.appium\\.settings'
2020-02-28 16:55:02:043 [ADB] Getting IDs of all 'io.appium.settings' processes
2020-02-28 16:55:02:043 [ADB] Running '/Users/encompass/Library/androidsdk/platform-tools/adb -P 5037 -s 2c11ce08e53f7ece shell pgrep -f io\\.appium\\.settings'
2020-02-28 16:55:02:174 [AndroidDriver] Failed to launch Appium Settings app: Condition unmet after 5198 ms. Timing out.
2020-02-28 16:55:02:174 [UiAutomator2] Deleting UiAutomator2 session
2020-02-28 16:55:02:175 [ADB] Running '/Users/encompass/Library/androidsdk/platform-tools/adb -P 5037 -s 2c11ce08e53f7ece shell am force-stop com.dsdlink'
2020-02-28 16:55:02:378 [ADB] Removing forwarded port socket connection: 7183 
2020-02-28 16:55:02:379 [ADB] Running '/Users/encompass/Library/androidsdk/platform-tools/adb -P 5037 -s 2c11ce08e53f7ece forward --remove tcp\:7183'
2020-02-28 16:55:02:384 [UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original error: 'Command '/Users/encompass/Library/androidsdk/platform-tools/adb -P 5037 -s 2c11ce08e53f7ece forward --remove tcp\:7183' exited with code 1'; Stderr: 'error: listener 'tcp:7183' not found'; Code: '1''
2020-02-28 16:55:02:384 [UiAutomator2] Restoring hidden api policy to the device default configuration
2020-02-28 16:55:02:385 [ADB] Running '/Users/encompass/Library/androidsdk/platform-tools/adb -P 5037 -s 2c11ce08e53f7ece shell settings delete global hidden_api_policy_pre_p_apps'
2020-02-28 16:55:02:456 [ADB] Running '/Users/encompass/Library/androidsdk/platform-tools/adb -P 5037 -s 2c11ce08e53f7ece shell settings delete global hidden_api_policy_p_apps'
2020-02-28 16:55:02:532 [ADB] Running '/Users/encompass/Library/androidsdk/platform-tools/adb -P 5037 -s 2c11ce08e53f7ece shell settings delete global hidden_api_policy'
2020-02-28 16:55:02:624 [BaseDriver] Event 'newSessionStarted' logged at 1582880102624 (16:55:02 GMT+0800 (China Standard Time))
2020-02-28 16:55:02:631 [W3C] Encountered internal error running command: Error: Failed to launch Appium Settings app: Condition unmet after 5198 ms. Timing out.
2020-02-28 16:55:02:631 [W3C]     at spin (/usr/local/lib/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:127:9)
2020-02-28 16:55:02:660 [HTTP] <-- POST /wd/hub/session 500 8944 ms - 657
2020-02-28 16:55:02:660 [HTTP] 
2020-02-28 16:55:02:663 uncaughtException: write EPIPE
Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:66:16)

**Comment by xuwintery** [comment]
@KazuCocoa  I think I need your help. If you have time, thank you very much

**Comment by KazuCocoa** [comment]
Please try `appium@beta` out. It has improvements to detect processes

**Comment by xuwintery** [comment]
I've solved this problem with appium@beta，Thanks
