### ISSUE TITLE
Unable to create a new remote session: Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec

### ISSUE THREAD

**Issue by p0well493** [appium/appium#14050]
## The problem

I am still new to Appium and trying to run a few native applications on my mobile. I executed the calculator application successfully earlier BUT encountered the issue below after a few days. Kindly help with the issue and let me know what action or changes should I need to do. Thank you and good day. Please see the issue below. Thanks

## Environment

Appium version : v.1.16.0
Desktop OS/version used to run Appium: Windows 10 Pro 64-bit(10.0, Build 17763)
Node.js version : v10.16.3
Npm : 6.9.0
Mobile platform/version under test: Android/v6.0
Real device or emulator/simulator: Huawei
Appium CLI or Appium : Appium desktop

## Details

Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\mycv21cg\\android-sdk\\platform-tools\\adb.exe -P 5037 -s LHTDU17601000834 shell pm install -r /data/local/tmp/appium_cache/0cc1725a60a05dbb5d0d09256f2fc6ece7e3b10f.apk' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'uiautomator2ServerInstallTimeout' capability
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'

## Link to Appium logs
[appium-server-logs March 11 Calculator.txt](https://github.com/appium/appium/files/4317455/appium-server-logs.March.11.Calculator.txt)

## Code To Reproduce Issue [ Good To Have ]

package appiumtest;

import java.net.URL;

import org.openqa.selenium.By;
import org.openqa.selenium.remote.DesiredCapabilities;

import io.appium.java_client.AppiumDriver;
import io.appium.java_client.MobileElement;

public class CalculatorTest {

static AppiumDriver<MobileElement>driver;

public static void main(String[] args) {
	// TODO Auto-generated method stub
	
	try {
		openCalculator();
	} catch (Exception exp) {
		// TODO Auto-generated catch block
		
		System.out.println(exp.getCause());
		System.out.println(exp.getMessage());
		exp.printStackTrace();
		
	}

}

public static void openCalculator() throws Exception {
	
	DesiredCapabilities cap = new DesiredCapabilities();
	
	cap.setCapability("deviceName", "CAM-L21");
	cap.setCapability("udid", "LHTDU17601000834");
	cap.setCapability("platformName", "Android");
	cap.setCapability("platformVersion", "6.0");
	cap.setCapability("automationName", "UiAutomator2");
	cap.setCapability("appPackage", "com.android.calculator2");
	cap.setCapability("appActivity", "com.android.calculator2.Calculator");
	
	URL url = new URL("http://127.0.0.1:4723/wd/hub");
	
	driver = new AppiumDriver<MobileElement>(url, cap);
	
	System.out.println("Application Test Started...");
	
	MobileElement nine = driver.findElement(By.id("com.android.calculator2:id/digit9"));
	MobileElement plus = driver.findElement(By.id("com.android.calculator2:id/plus"));
	MobileElement eight = driver.findElement(By.id("com.android.calculator2:id/digit8"));
	MobileElement equals = driver.findElement(By.id("com.android.calculator2:id/equal"));
	
	MobileElement result = driver.findElement(By.className("android.widget.EditText"));
	
	nine.click();
	plus.click();
	eight.click();
	equals.click();
	
	String reslt = result.getText();
	System.out.println("\n Result is : "+reslt);
	System.out.println("\n Completed Testing Automation");
							
	
}

**ECLIPSE LOG:**
java.lang.reflect.InvocationTargetException
org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\mycv21cg\\android-sdk\\platform-tools\\adb.exe -P 5037 -s LHTDU17601000834 shell pm install -r /data/local/tmp/appium_cache/0cc1725a60a05dbb5d0d09256f2fc6ece7e3b10f.apk' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'uiautomator2ServerInstallTimeout' capability
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'MYCV21CG_NB', ip: '172.20.10.8', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_231'
Driver info: driver.version: AppiumDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\mycv21cg\\android-sdk\\platform-tools\\adb.exe -P 5037 -s LHTDU17601000834 shell pm install -r /data/local/tmp/appium_cache/0cc1725a60a05dbb5d0d09256f2fc6ece7e3b10f.apk' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'uiautomator2ServerInstallTimeout' capability
    at getResponseForW3CError (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:388:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'MYCV21CG_NB', ip: '172.20.10.8', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_231'
Driver info: driver.version: AppiumDriver
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:208)Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\mycv21cg\\android-sdk\\platform-tools\\adb.exe -P 5037 -s LHTDU17601000834 shell pm install -r /data/local/tmp/appium_cache/0cc1725a60a05dbb5d0d09256f2fc6ece7e3b10f.apk' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'uiautomator2ServerInstallTimeout' capability
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'MYCV21CG_NB', ip: '172.20.10.8', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_231'
Driver info: driver.version: AppiumDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\mycv21cg\\android-sdk\\platform-tools\\adb.exe -P 5037 -s LHTDU17601000834 shell pm install -r /data/local/tmp/appium_cache/0cc1725a60a05dbb5d0d09256f2fc6ece7e3b10f.apk' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'uiautomator2ServerInstallTimeout' capability
    at getResponseForW3CError (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:388:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'MYCV21CG_NB', ip: '172.20.10.8', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_231'
Driver info: driver.version: AppiumDriver

	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:217)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:323)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:37)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:86)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:96)
	at appiumtest.CalculatorTest.openCalculator(CalculatorTest.java:45)
	at appiumtest.CalculatorTest.main(CalculatorTest.java:19)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:186)
	... 13 more
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\mycv21cg\\android-sdk\\platform-tools\\adb.exe -P 5037 -s LHTDU17601000834 shell pm install -r /data/local/tmp/appium_cache/0cc1725a60a05dbb5d0d09256f2fc6ece7e3b10f.apk' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'uiautomator2ServerInstallTimeout' capability
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'MYCV21CG_NB', ip: '172.20.10.8', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_231'
Driver info: driver.version: AppiumDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\mycv21cg\\android-sdk\\platform-tools\\adb.exe -P 5037 -s LHTDU17601000834 shell pm install -r /data/local/tmp/appium_cache/0cc1725a60a05dbb5d0d09256f2fc6ece7e3b10f.apk' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'uiautomator2ServerInstallTimeout' capability
    at getResponseForW3CError (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:388:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	... 18 more

**Comment by p0well493** [comment]
Is the issue due to ADB execution timeout? how to increase the adb timeout by encoding or configuring it using an eclipse? Thank you

**Comment by mykola-mokhnach** [comment]
How much time the install command takes being executed manually from the terminal?

**Comment by p0well493** [comment]
hi @mykola-mokhnach , can you help clarify the install query you are asking? I am using a calculator native app on the android phone which is already there...install manually in the terminal what application? Kindly help to specify as I am still 2 weeks old learning the Appium tool. Thank you and good day.

**Comment by mykola-mokhnach** [comment]
In case you are looking for tutorials for beginners then consider using discuss.appium.io
Here is the place for issues.

> can you help clarify the install query you are asking? 

I was talking about the `C:\Users\mycv21cg\android-sdk\platform-tools\adb.exe -P 5037 -s LHTDU17601000834 shell pm install -r /data/local/tmp/appium_cache/0cc1725a60a05dbb5d0d09256f2fc6ece7e3b10f.apk` command

**Comment by p0well493** [comment]
hi @mykola-mokhnach , thanks for the response.  Regarding your question on the install of application, previously I run successfully the native calculator app on my Huawei Android device, but after 2-3 days, it is not working anymore. I am not sure what the adb is trying to install. Do I have to reinstall again my ADB for this? since I am using/learning on my native calculator on my native android device. Thanks Mykola.

**Comment by mykola-mokhnach** [comment]
ADB is trying to install the previously cached appium server binary. Although, I have no idea on why it takes to much time in order to complete it. Try to reset the device or get a new one for testing. Also make sure the Android SDK is up to date.

**Comment by p0well493** [comment]
Hi @mykola-mokhnach , i received this message after i updated my SDK.


**[UiAutomator2]** Error: The instrumentation process cannot be initialized. Make sure the application under test does not crash and investigate the logcat output.
**[UiAutomator2]**     at Object.wrappedLogger.errorAndThrow (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:79:13)
**[UiAutomator2]**     at UiAutomator2Server.errorAndThrow [as startSession] (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\uiautomator2.js:227:13)
[UiAutomator2] Deleting UiAutomator2 session
[UiAutomator2] Deleting UiAutomator2 server session
[WD Proxy] Matched '/' to command name 'deleteSession'
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Trying to proxy a session 
Encountered internal error running command: Error: The instrumentation process cannot be initialized. Make sure the application under test does not crash and investigate the logcat output.


I am using an Eclipse since I am also automating an Angular web url using a Protractor. Now using a hybrid, I am using Appium tool. In checking the error, do I have to check Appium server which contains the x icon in red fonts??

**Comment by mykola-mokhnach** [comment]
Please describe a new issue and attach the necessary info to it regarding the recent error message. Also don't forget to check what's stated in the error message first.

Closed as not an issue.
