### ISSUE TITLE
Not able to install appium in windows 10

### ISSUE THREAD

**Issue by arunan123** [appium/appium#14066]
## The problem

When I try to install appium it fails when installing chrome driver, I ran the following command,
`npm install -g appium`

`[13:42:43] [Chromedriver Install] Downloading https://chromedriver.storage.googleapis.com/78.0.3904.70/chromedriver_win32.zip...
[13:42:46] Error installing Chromedriver: Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 8888
[13:42:46] RequestError: Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 8888
    at new RequestError (C:\Users\raar9003\AppData\Roaming\npm\node_modules\appium\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (C:\Users\raar9003\AppData\Roaming\npm\node_modules\appium\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\Users\raar9003\AppData\Roaming\npm\node_modules\appium\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\Users\raar9003\AppData\Roaming\npm\node_modules\appium\node_modules\request\request.js:185:22)
    at Request.emit (events.js:209:13)
    at Request.onRequestError (C:\Users\raar9003\AppData\Roaming\npm\node_modules\appium\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:209:13)
    at ClientRequest.onError (C:\Users\raar9003\AppData\Roaming\npm\node_modules\appium\node_modules\tunnel-agent\index.js:179:21)
    at Object.onceWrapper (events.js:299:26)
    at ClientRequest.emit (events.js:209:13)
    at Socket.socketErrorListener (_http_client.js:406:9)
    at Socket.emit (events.js:209:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[`

I did a research and found it may be the proxy, then I spin up an http server and ran the command like this,

`npm install appium --chromedriver_cdnurl=http://localhost:8080`

But it again fails with the following message,

`[13:52:20] [Chromedriver Install] Downloading http://localhost:8080/78.0.3904.70/chromedriver_win32.zip...
[13:52:20] Error installing Chromedriver: Error: Invalid protocol: 10.245.130.94:
[13:52:20] RequestError: Error: Invalid protocol: 10.245.130.94:
    at new RequestError (C:\Users\raar9003\node_modules\appium\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (C:\Users\raar9003\node_modules\appium\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\Users\raar9003\node_modules\appium\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\Users\raar9003\node_modules\appium\node_modules\request\request.js:185:22)
    at Request.emit (events.js:209:13)
    at Request.init (C:\Users\raar9003\node_modules\appium\node_modules\request\request.js:458:17)
    at Request.RP$initInterceptor [as init] (C:\Users\raar9003\node_modules\appium\node_modules\request-promise-core\configure\request2.js:45:29)
    at new Request (C:\Users\raar9003\node_modules\appium\node_modules\request\request.js:127:8)
    at request (C:\Users\raar9003\node_modules\appium\node_modules\request\index.js:53:10)
    at Function.get (C:\Users\raar9003\node_modules\appium\node_modules\request\index.js:61:12)
    at installForPlatform (C:\Users\raar9003\node_modules\appium\node_modules\appium-chromedriver\lib\install.js:74:30)
    at install (C:\Users\raar9003\node_modules\appium\node_modules\appium-chromedriver\lib\install.js:104:3)
    at Object.doInstall (C:\Users\raar9003\node_modules\appium\node_modules\appium-chromedriver\lib\install.js:132:5)`

## Environment

* Appium version (or git revision) that exhibits the issue: latest version
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): v12.10.0 AND v13.11.0
* Npm or Yarn package manager: Npm 6.14.2

## Link to Appium logs

Running appium-doctor gives the following result,

`info AppiumDoctor Appium Doctor v.1.13.1
info AppiumDoctor ### Diagnostic for necessary dependencies starting ###
info AppiumDoctor  ✔ The Node.js binary was found at: C:\Program Files\nodejs\node.EXE
info AppiumDoctor  ✔ Node version is 13.11.0
info AppiumDoctor  ✔ ANDROID_HOME is set to: C:\Users\raar9003\AppData\Local\Android\sdk
info AppiumDoctor  ✔ JAVA_HOME is set to: C:\Program Files\Java\jdk1.8.0_231
info AppiumDoctor  ✔ adb exists at: C:\Users\raar9003\AppData\Local\Android\sdk\platform-tools\adb.exe
info AppiumDoctor  ✔ android exists at: C:\Users\raar9003\AppData\Local\Android\sdk\tools\android.bat
info AppiumDoctor  ✔ emulator exists at: C:\Users\raar9003\AppData\Local\Android\sdk\tools\emulator.exe
WARN AppiumDoctor  ✖ Bin directory for %JAVA_HOME% is not set
info AppiumDoctor ### Diagnostic for necessary dependencies completed, one fix needed. ###
info AppiumDoctor
info AppiumDoctor ### Diagnostic for optional dependencies starting ###
WARN AppiumDoctor  ✖ opencv4nodejs cannot be found.
WARN AppiumDoctor  ✖ ffmpeg cannot be found
WARN AppiumDoctor  ✖ mjpeg-consumer cannot be found.
WARN AppiumDoctor  ✖ bundletool.jar cannot be found
info AppiumDoctor ### Diagnostic for optional dependencies completed, 4 fixes possible. ###
info AppiumDoctor
info AppiumDoctor ### Manual Fixes Needed ###
info AppiumDoctor The configuration cannot be automatically fixed, please do the following first:
WARN AppiumDoctor  ➜ Add '%JAVA_HOME%\bin' to your PATH environment
info AppiumDoctor
info AppiumDoctor ### Optional Manual Fixes ###
info AppiumDoctor The configuration can install optionally. Please do the following manually:
WARN AppiumDoctor  ➜ Why opencv4nodejs is needed and how to install it: https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/image-comparison.md
WARN AppiumDoctor  ➜ ffmpeg is needed to record screen features. Please read https://www.ffmpeg.org/ to install it
WARN AppiumDoctor  ➜ mjpeg-consumer module is required to use MJPEG-over-HTTP features. Please install it with 'npm i -g mjpeg-consumer'.
WARN AppiumDoctor  ➜ bundletool.jar is used to handle Android App Bundle. Please read http://appium.io/docs/en/writing-running-appium/android/android-appbundle/ to install it. Also consider adding the ".jar" extension into your PATHEXT environment variable in order to fix the problem for Windows
info AppiumDoctor
info AppiumDoctor ###
info AppiumDoctor
info AppiumDoctor Bye! Run appium-doctor again when all manual fixes have been applied!
info AppiumDoctor`

**Comment by arunan123** [comment]
Also I am not connected to my office VPN.. but still it is happening..

**Comment by mykola-mokhnach** [comment]
The install fails because the script cannot connect to chromedriver web site. This might be happening due to the network misconfiguration on the machine or firewall restrictions. Consider contacting your system administrator to resolve these.
Also, there is a possibility to provide a custom url for chromedriver download. Check the troubleshooting section of https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md

Closed as not an issue
