### ISSUE TITLE
[Simulator] Take screenshot failed and find element failed as ECONNREFUSED

### ISSUE THREAD

**Issue by maggie5750** [appium/appium#14075]
## The problem
[Simulator] Take screenshot failed and find element failed as ECONNREFUSED

## Environment

* Appium version (or git revision) that exhibits the issue: 1.16.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS 10.14.4
* Node.js version (unless using Appium.app|exe): 10.13.0
* Npm or Yarn package manager: 6.9.0
* Mobile platform/version under test:
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe:

## Link to Appium logs
`2020-03-17 09:44:33:346 - [debug] [35m[W3C (5ad3b191)][39m Calling AppiumDriver.getScreenshot() with args: ["5ad3b191-b30b-49f2-bc97-b24694208813"]
2020-03-17 09:44:33:346 - [debug] [35m[XCUITest][39m Executing command 'getScreenshot'
2020-03-17 09:44:33:346 - [debug] [35m[XCUITest][39m Taking screenshot with WDA
2020-03-17 09:44:33:347 - [debug] [35m[WD Proxy][39m Matched '/screenshot' to command name 'getScreenshot'
2020-03-17 09:44:33:347 - [debug] [35m[WD Proxy][39m Proxying [GET /screenshot] to [GET http://localhost:8898/session/0606F97D-0700-4200-AA73-54F5A5FC5518/screenshot] with no body
2020-03-17 09:44:33:348 - [35m[WD Proxy][39m Got an unexpected response with status undefined: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8898}
2020-03-17 09:44:33:349 - [35m[XCUITest][39m Error getting screenshot: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8898
2020-03-17 09:44:33:349 - [35m[XCUITest][39m Falling back to 'simctl io screenshot' API
2020-03-17 09:44:33:608 - [35m[simctl][39m simctl error running 'io': Detected file type 'PNG' from extension
2020-03-17 09:44:33:608 - [35m[simctl][39m An error was encountered processing the command (domain=simctl.SimDisplayScreenshotWriter.ScreenshotError, code=2):
2020-03-17 09:44:33:608 - [35m[simctl][39m Error creating the image
2020-03-17 09:44:33:608 - [debug] [35m[W3C (5ad3b191)][39m Encountered internal error running command: Error: simctl error running 'io': Detected file type 'PNG' from extension
2020-03-17 09:44:33:608 - [debug] [35m[W3C (5ad3b191)][39m An error was encountered processing the command (domain=simctl.SimDisplayScreenshotWriter.ScreenshotError, code=2):
2020-03-17 09:44:33:609 - [debug] [35m[W3C (5ad3b191)][39m Error creating the image
2020-03-17 09:44:33:609 - [debug] [35m[W3C (5ad3b191)][39m     at Object.errorAndThrow (/Users/xxx/.nvm/versions/node/v10.16.3/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:74:35)
2020-03-17 09:44:33:609 - [debug] [35m[W3C (5ad3b191)][39m     at simCommand (/Users/xxx/.nvm/versions/node/v10.16.3/lib/node_modules/appium/node_modules/node-simctl/lib/simctl.js:52:11)
2020-03-17 09:44:33:609 - [35m[HTTP][39m [37m<-- GET /wd/hub/session/5ad3b191-b30b-49f2-bc97-b24694208813/screenshot [39m[31m500[39m [90m263 ms - 979[39m
2020-03-17 09:44:33:609 - [35m[HTTP][39m [90m[39m
2020-03-17 09:44:35:406 - [35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/sessions[39m
2020-03-17 09:44:35:407 - [35m[HTTP][39m [90m{}[39m
2020-03-17 09:44:35:407 - [debug] [35m[GENERIC][39m Calling AppiumDriver.getSessions() with args: []
2020-03-17 09:44:35:407 - [debug] [35m[GENERIC][39m Responding to client with driver.getSessions() result: [{"id":"5ad3b191-b30b-49f2-bc97-b24694208813","capabilities":{"platformName":"ios","autoWebView":true,"useJSONSource":false,"waitForQuiescence":false,"wdaEventloopIdleDelay":5,"webkitResponseTimeout":60000,"app":"xxx.zip","autoAcceptAlerts":false,"automationName":"xcuitest","deviceName":"iPhone 11 Pro Max","fullReset":true,"iosInstallPause":8000,"launchTimeout":180000,"locale":"en_US","maxTypingFrequency":60,"nativeWebTap":false,"newCommandTimeout":600,"noReset":false,"platformVersion":"13.3","processArguments":{"args":["-RCTestingMode","-AppleLocale","en_US"]},"simpleIsVisibleCheck":false,"startIWDP":true,"udid":"380E5BD9-4F13-492B-AB34-BE71C03F0D3F","useNewWDA":true,"usePrebuiltWDA":true,"wdaLocalPort":8898,"wdaStartupRetries":4,"wdaStartupRetryInterval":0}}]
2020-03-17 09:44:35:408 - [35m[HTTP][39m [37m<-- GET /wd/hub/sessions [39m[32m200[39m [90m1 ms - 858[39m
2020-03-17 09:44:35:408 - [35m[HTTP][39m [90m[39m
2020-03-17 09:44:41:801 - [35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/sessions[39m
2020-03-17 09:44:41:801 - [35m[HTTP][39m [90m{}[39m
2020-03-17 09:44:41:801 - [debug] [35m[GENERIC][39m Calling AppiumDriver.getSessions() with args: []
2020-03-17 09:44:41:802 - [debug] [35m[GENERIC][39m Responding to client with driver.getSessions() result: [{"id":"5ad3b191-b30b-49f2-bc97-b24694208813","capabilities":{"platformName":"ios","autoWebView":true,"useJSONSource":false,"waitForQuiescence":false,"wdaEventloopIdleDelay":5,"webkitResponseTimeout":60000,"app":"xxx.zip","autoAcceptAlerts":false,"automationName":"xcuitest","deviceName":"iPhone 11 Pro Max","fullReset":true,"iosInstallPause":8000,"launchTimeout":180000,"locale":"en_US","maxTypingFrequency":60,"nativeWebTap":false,"newCommandTimeout":600,"noReset":false,"platformVersion":"13.3","processArguments":{"args":["-RCTestingMode","-AppleLocale","en_US"]},"simpleIsVisibleCheck":false,"startIWDP":true,"udid":"380E5BD9-4F13-492B-AB34-BE71C03F0D3F","useNewWDA":true,"usePrebuiltWDA":true,"wdaLocalPort":8898,"wdaStartupRetries":4,"wdaStartupRetryInterval":0}}]
2020-03-17 09:44:41:802 - [35m[HTTP][39m [37m<-- GET /wd/hub/sessions [39m[32m200[39m [90m1 ms - 858[39m
2020-03-17 09:44:41:802 - [35m[HTTP][39m [90m[39m
2020-03-17 09:44:44:597 - [35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/session/5ad3b191-b30b-49f2-bc97-b24694208813/screenshot[39m
2020-03-17 09:44:44:597 - [35m[HTTP][39m [90m{}[39m
2020-03-17 09:44:44:597 - [debug] [35m[W3C (5ad3b191)][39m Calling AppiumDriver.getScreenshot() with args: ["5ad3b191-b30b-49f2-bc97-b24694208813"]
2020-03-17 09:44:44:597 - [debug] [35m[XCUITest][39m Executing command 'getScreenshot'
2020-03-17 09:44:44:597 - [debug] [35m[XCUITest][39m Taking screenshot with WDA
2020-03-17 09:44:44:598 - [debug] [35m[WD Proxy][39m Matched '/screenshot' to command name 'getScreenshot'
2020-03-17 09:44:44:598 - [debug] [35m[WD Proxy][39m Proxying [GET /screenshot] to [GET http://localhost:8898/session/0606F97D-0700-4200-AA73-54F5A5FC5518/screenshot] with no body
2020-03-17 09:44:44:601 - [35m[WD Proxy][39m Got an unexpected response with status undefined: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8898}
2020-03-17 09:44:44:601 - [35m[XCUITest][39m Error getting screenshot: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8898
2020-03-17 09:44:44:601 - [35m[XCUITest][39m Falling back to 'simctl io screenshot' API
2020-03-17 09:44:44:722 - [35m[simctl][39m simctl error running 'io': Detected file type 'PNG' from extension
2020-03-17 09:44:44:722 - [35m[simctl][39m An error was encountered processing the command (domain=simctl.SimDisplayScreenshotWriter.ScreenshotError, code=2):
2020-03-17 09:44:44:722 - [35m[simctl][39m Error creating the image
2020-03-17 09:44:44:723 - [debug] [35m[W3C (5ad3b191)][39m Encountered internal error running command: Error: simctl error running 'io': Detected file type 'PNG' from extension
2020-03-17 09:44:44:723 - [debug] [35m[W3C (5ad3b191)][39m An error was encountered processing the command (domain=simctl.SimDisplayScreenshotWriter.ScreenshotError, code=2):
2020-03-17 09:44:44:723 - [debug] [35m[W3C (5ad3b191)][39m Error creating the image
2020-03-17 09:44:44:723 - [debug] [35m[W3C (5ad3b191)][39m     at Object.errorAndThrow (/Users/xxx/.nvm/versions/node/v10.16.3/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:74:35)
2020-03-17 09:44:44:723 - [debug] [35m[W3C (5ad3b191)][39m     at simCommand (/Users/xxx/.nvm/versions/node/v10.16.3/lib/node_modules/appium/node_modules/node-simctl/lib/simctl.js:52:11)`
https://gist.github.com/maggie5750/e23dc95233e8fd4a4f1f80eed250bcc7

**Comment by mykola-mokhnach** [comment]
> 2020-03-17 09:44:33:348 - [35m[WD Proxy][39m Got an unexpected response with status undefined: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8898}
> 2020-03-17 09:44:33:349 - [35m[XCUITest][39m Error getting screenshot: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8898
> 2020-03-17 09:44:33:349 - [35m[XCUITest][39m Falling back to 'simctl io screenshot' API
> 2020-03-17 09:44:33:608 - [35m[simctl][39m simctl error running 'io': Detected file type 'PNG' from extension
> 2020-03-17 09:44:33:608 - [35m[simctl][39m An error was encountered processing the command (domain=simctl.SimDisplayScreenshotWriter.ScreenshotError, code=2):
> 2020-03-17 09:44:33:608 - [35m[simctl][39m Error creating the image
> 2020-03-17 09:44:33:608 - [debug] [35m[W3C (5ad3b191)][39m Encountered internal error running command: Error: simctl error running 'io': Detected file type 'PNG' from extension
> 2020-03-17 09:44:33:608 - [debug] [35m[W3C (5ad3b191)][39m An error was encountered processing the command (domain=simctl.SimDisplayScreenshotWriter.ScreenshotError, code=2):
> 2020-03-17 09:44:33:609 - [debug] [35m[W3C (5ad3b191)][39m Error creating the image

It looks like the device died unexpectedly during the test. So neither WDA server was running nor simctl was able to connect to it. Perhaps, the device log contains more info on what has happened there.

**Comment by maggie5750** [comment]
@mykola-mokhnach  So you mean get the simulator log to check?

**Comment by mykola-mokhnach** [comment]
yes

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
