### ISSUE TITLE
[Android] An unknown server-side error occurred while processing the command. Original error: Unable to stop the background screen recording: Error executing adbExec

### ISSUE THREAD

**Issue by HoLeAnh** [appium/appium#14083]
## The problem

I run test on Adnroid and screencapture but appium show error

## Environment
Real device : Android 10
Appium 1.16.0
Node : v12.13.0
Npm : 6.13.7

## Details

Full log error : 
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Unable to stop the background screen recording: Error executing adbExec. Original error: 'Command 'C:\\Users\\anhhl\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s 8d6ae269 shell kill -15 14655' exited with code 1'; Stderr: '/system/bin/sh: kill: 14655: Operation not permitted'; Code: '1'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'ANHHL-SPC', ip: '192.168.144.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_171'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {appActivity: feature.splash.SplashScreen..., appPackage: com.sendoseller, autoGrantPermissions: true, chromedriverExecutable: D:\Workspace\Sendo_SellerAp..., databaseEnabled: false, desired: {appActivity: feature.splash.SplashScreen..., appPackage: com.sendoseller, autoGrantPermissions: true, chromedriverExecutable: D:\Workspace\Sendo_SellerAp..., nativeWebScreenshot: true, orientation: PORTRAIT, platformName: android, systemPort: 5001, udid: 8d6ae269, unicodeKeyboard: true}, deviceApiLevel: 29, deviceManufacturer: Xiaomi, deviceModel: MI 8, deviceName: 8d6ae269, deviceScreenDensity: 440, deviceScreenSize: 1080x2248, deviceUDID: 8d6ae269, javascriptEnabled: true, locationContextEnabled: false, nativeWebScreenshot: true, networkConnectionEnabled: true, orientation: PORTRAIT, pixelRatio: 2.75, platform: LINUX, platformName: Android, platformVersion: 10, statBarHeight: 89, systemPort: 5001, takesScreenshot: true, udid: 8d6ae269, unicodeKeyboard: true, viewportRect: {height: 1940, left: 0, top: 89, width: 1080}, warnings: {}, webStorageEnabled: false}
Session ID: 25868496-1336-43e0-80c3-51e651589543
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at io.appium.java_client.CommandExecutionHelper.execute(CommandExecutionHelper.java:27)
	at io.appium.java_client.screenrecording.CanRecordScreen.startRecordingScreen(CanRecordScreen.java:38)
	at actions.ScreenRecord.start(ScreenRecord.java:175)
	at init.Testbase.BeforeMethod(Testbase.java:149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:589)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

## Code To Reproduce Issue [ Good To Have ]
public static synchronized void start(MobileDriver<MobileElement> driver) {
		if (ConfigData.DEVICE.equals("android")) {
			AndroidStartScreenRecordingOptions options = new AndroidStartScreenRecordingOptions();
			options.withTimeLimit(Duration.ofSeconds(300));
			((CanRecordScreen) driver).startRecordingScreen(options);
		} else {
			IOSStartScreenRecordingOptions options = new IOSStartScreenRecordingOptions();
			options.withVideoType("mpeg4");
			options.withTimeLimit(Duration.ofSeconds(1000));
			((CanRecordScreen) driver).startRecordingScreen(options);
		}
	}

**Comment by HoLeAnh** [comment]
[appiumLog.txt](https://github.com/appium/appium/files/4347860/appiumLog.txt)
Appium log

**Comment by mykola-mokhnach** [comment]
> [debug] [ADB] Running 'C:\Users\anhhl\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 8d6ae269 shell pgrep -f screenrecord'
> [debug] [ADB] Running 'C:\Users\anhhl\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 8d6ae269 shell kill -15 14655'
> [debug] [W3C (07d0f69e)] Encountered internal error running command: Error: Unable to stop the background screen recording: Error executing adbExec. Original error: 'Command 'C:\\Users\\anhhl\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s 8d6ae269 shell kill -15 14655' exited with code 1'; Stderr: '/system/bin/sh: kill: 14655: Operation not permitted'; Code: '1'

It looks like the device is already running a screen recording started by some other process. Make sure there are no active screen recording processes on the device before starting the test.

**Comment by HoLeAnh** [comment]
> > [debug] [ADB] Running 'C:\Users\anhhl\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 8d6ae269 shell pgrep -f screenrecord'
> > [debug] [ADB] Running 'C:\Users\anhhl\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 8d6ae269 shell kill -15 14655'
> > [debug] [W3C (07d0f69e)] Encountered internal error running command: Error: Unable to stop the background screen recording: Error executing adbExec. Original error: 'Command 'C:\Users\anhhl\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 8d6ae269 shell kill -15 14655' exited with code 1'; Stderr: '/system/bin/sh: kill: 14655: Operation not permitted'; Code: '1'
> 
> It looks like the device is already running a screen recording started by some other process. Make sure there are no active screen recording processes on the device before starting the test.

**Comment by HoLeAnh** [comment]
> > > [debug] [ADB] Running 'C:\Users\anhhl\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 8d6ae269 shell pgrep -f screenrecord'
> > > [debug] [ADB] Running 'C:\Users\anhhl\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 8d6ae269 shell kill -15 14655'
> > > [debug] [W3C (07d0f69e)] Encountered internal error running command: Error: Unable to stop the background screen recording: Error executing adbExec. Original error: 'Command 'C:\Users\anhhl\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 8d6ae269 shell kill -15 14655' exited with code 1'; Stderr: '/system/bin/sh: kill: 14655: Operation not permitted'; Code: '1'
> > 
> > 
> > It looks like the device is already running a screen recording started by some other process. Make sure there are no active screen recording processes on the device before starting the test.

No i just test by run "shell adb shell screenrecord /mnt/sdcard/Download/test.mp4" via cmd and turn of it by ctrl+C. After that i re-run test but still received this error. And i don't use any application for record.

**Comment by mykola-mokhnach** [comment]
does `shell pgrep -f screenrecord` show anything in `clean` state?

**Comment by HoLeAnh** [comment]
I fixed my issue by reboot my device.
I try find all process by : adb shell pgrep -f screenrecord and have 1 process , after that i kikill all it . but i cannot. Finally, i re

**Comment by kkallu** [comment]
Hi ,

I fixed it by upgrading my platform tools and restarting eclipse as well as restarting device as well ,

Try above one's ,it will solve this bug,

Thanks

**Comment by AishRS** [comment]
How do you kill the background process programatically when the test is eexecuting on a real device on the cloud?

**Comment by NinaPangaribuan** [comment]
I have the same issue

java.util.concurrent.ExecutionException: org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\pangaribuan\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s 3a6fc5ea shell pm clear com.android.settings' exited with code 1'; Command output: Error: java.lang.SecurityException: adb clearing user data is forbidden.

Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'NINA2905', ip: '192.168.43.21', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_282'
Driver info: driver.version: SwipeableAndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\pangaribuan\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s 3a6fc5ea shell pm clear com.android.settings' exited with code 1'; Command output: Error: java.lang.SecurityException: adb clearing user data is forbidden.

    at getResponseForW3CError (C:\Users\pangaribuan\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\pangaribuan\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:380:37)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'NINA2905', ip: '192.168.43.21', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_282'
Driver info: driver.version: SwipeableAndroidDriver
	at com.kms.katalon.composer.components.impl.dialogs.ProgressMonitorDialogWithThread.runAndWait(ProgressMonitorDialogWithThread.java:49)
	at com.kms.katalon.composer.mobile.objectspy.components.MobileLocalAppComposite$12.run(MobileLocalAppComposite.java:474)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\pangaribuan\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s 3a6fc5ea shell pm clear com.android.settings' exited with code 1'; Command output: Error: java.lang.SecurityException: adb clearing user data is forbidden.

Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'NINA2905', ip: '192.168.43.21', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_282'
Driver info: driver.version: SwipeableAndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\pangaribuan\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s 3a6fc5ea shell pm clear com.android.settings' exited with code 1'; Command output: Error: java.lang.SecurityException: adb clearing user data is forbidden.

    at getResponseForW3CError (C:\Users\pangaribuan\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\pangaribuan\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:380:37)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'NINA2905', ip: '192.168.43.21', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_282'
Driver info: driver.version: SwipeableAndroidDriver
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:208)
	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:217)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at com.kms.katalon.core.appium.driver.SwipeableAndroidDriver.execute(SwipeableAndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:84)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:85)
	at com.kms.katalon.core.appium.driver.SwipeableAndroidDriver.<init>(SwipeableAndroidDriver.java:24)
	at com.kms.katalon.core.appium.driver.AppiumDriverManager.createMobileDriver(AppiumDriverManager.java:498)
	at com.kms.katalon.core.appium.driver.AppiumDriverManager.createMobileDriver(AppiumDriverManager.java:480)
	at com.kms.katalon.core.mobile.keyword.internal.MobileDriverFactory.startMobileDriver(MobileDriverFactory.java:417)
	at com.kms.katalon.composer.mobile.objectspy.dialog.MobileInspectorController.startExistingApp(MobileInspectorController.java:143)
	at com.kms.katalon.composer.mobile.objectspy.components.MobileLocalAppComposite$12$1.call(MobileLocalAppComposite.java:482)
	at com.kms.katalon.composer.components.impl.dialogs.ProgressMonitorDialogWithThread.startThreadAndWait(ProgressMonitorDialogWithThread.java:36)
	at com.kms.katalon.composer.components.impl.dialogs.ProgressMonitorDialogWithThread.runAndWait(ProgressMonitorDialogWithThread.java:48)
	... 2 more
Caused by: java.lang.reflect.InvocationTargetException
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:186)
	... 22 more
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\pangaribuan\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s 3a6fc5ea shell pm clear com.android.settings' exited with code 1'; Command output: Error: java.lang.SecurityException: adb clearing user data is forbidden.

Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'NINA2905', ip: '192.168.43.21', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_282'
Driver info: driver.version: SwipeableAndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\pangaribuan\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s 3a6fc5ea shell pm clear com.android.settings' exited with code 1'; Command output: Error: java.lang.SecurityException: adb clearing user data is forbidden.

    at getResponseForW3CError (C:\Users\pangaribuan\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\pangaribuan\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:380:37)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	... 23 more

**Comment by amey18s** [comment]
some apps are not running or taking more time in  appium desktop
