### ISSUE TITLE
Questions about flutter Driver

### ISSUE THREAD

**Issue by ezuluagas** [appium/appium#14104]
## The problem

The appium version 1.16.0 had support for Flutter Driver in Beta Version https://github.com/appium/appium/pull/12945,  but the last version 1.17.0 don't have support for Flutter, so i want to know what is the reason that this doesn't work in this version furthermore i would like to know if you are planning to give support flutter-driver soon?

## Environment

* Appium version 1.16.0 beta support for flutter driver https://github.com/appium/appium/pull/12945
* The version 1.17.0 don't have the flutter driver

**Comment by imurchie** [comment]
The flutter driver is still there, and should be available.

What are the logs for trying to access it?

**Comment by ezuluagas** [comment]
hello i ran in version 1.16.0 and it works well, with the version 1.17.0 i get this error
```

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not load a driver for automationName 'Flutter' and platformName 'Android'. Please verify your Appium installation (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 2.04 seconds
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'CO-IT005188.local', ip: '192.168.1.2', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '1.8.0_221'
Driver info: io.appium.java_client.android.AndroidDriver

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:40)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:249)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:36)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:114)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:132)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:92)
	at example.appium.BaseDriver.setUp(BaseDriver.java:40)
	at example.appium.FlutterTest.setUp(FlutterTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

```

or something change

**Comment by imurchie** [comment]
Something unintentional was changed that broke this. I'll explore a little.

**Comment by imurchie** [comment]
@ezuluagas Can you provide the _full_ Appium server logs, as a link to a [gist](https://gist.github.com). My initial attempt does not cause this error, so I need more info.

**Comment by ezuluagas** [comment]
@imurchie 
```

[Appium] Welcome to Appium v1.17.0
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.17.0"}}
[HTTP] <-- GET /wd/hub/status 200 6 ms - 68
[HTTP] 
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.17.0"}}
[HTTP] <-- GET /wd/hub/status 200 1 ms - 68
[HTTP] 
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"app":"/Users/esteban.zuluaga/Documents/Disney/appiumFlutter/android-real-debug.apk","automationName":"Flutter","noReset":true,"platformName":"Android","deviceName":"Nexus 6p","platformVersion":"8.1"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/esteban.zuluaga/Documents/Disney/appiumFlutter/android-real-debug.apk","automationName":"Flutter","noReset":true,"platformName":"Android","deviceName":"Nexus 6p","platformVersion":"8.1"},null,null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1585152365460 (11:06:05 GMT-0500 (-05))
[debug] [Appium] SyntaxError: Invalid regular expression: /^[ \t]*(?<pid>\d+)[ \t]+(?<ppid>\d+)[ \t]+(?<uid>\d+)[ \t]+(?<cpu>\d+\.\d+)[ \t]+(?<memory>\d+\.\d+)[ \t]+/: Invalid group
[debug] [Appium]     at Object.<anonymous> (/Users/esteban.zuluaga/.nvm/versions/node/v8.16.1/lib/node_modules/appium/node_modules/ps-list/index.js:69:23)
[debug] [Appium]     at Module._compile (module.js:653:30)
[debug] [Appium]     at Object.Module._extensions..js (module.js:664:10)
[debug] [Appium]     at Module.load (module.js:566:32)
[debug] [Appium]     at tryModuleLoad (module.js:506:12)
[debug] [Appium]     at Function.Module._load (module.js:498:3)
[debug] [Appium]     at Module.require (module.js:597:17)
[debug] [Appium]     at require (internal/module.js:11:18)
[debug] [Appium]     at Object.<anonymous> (/Users/esteban.zuluaga/.nvm/versions/node/v8.16.1/lib/node_modules/appium/node_modules/fkill/index.js:8:16)
[debug] [Appium]     at Module._compile (module.js:653:30)
[debug] [Appium]     at Object.Module._extensions..js (module.js:664:10)
[debug] [Appium]     at Module.load (module.js:566:32)
[debug] [Appium]     at tryModuleLoad (module.js:506:12)
[debug] [Appium]     at Function.Module._load (module.js:498:3)
[debug] [Appium]     at Module.require (module.js:597:17)
[debug] [Appium]     at require (internal/module.js:11:18)
[debug] [Appium]     at Object.<anonymous> (/Users/esteban.zuluaga/.nvm/versions/node/v8.16.1/lib/node_modules/appium/node_modules/appium-ios-simulator/lib/utils.js:11:1)
[debug] [Appium]     at Module._compile (module.js:653:30)
[debug] [Appium]     at Object.Module._extensions..js (module.js:664:10)
[debug] [Appium]     at Module.load (module.js:566:32)
[debug] [Appium]     at tryModuleLoad (module.js:506:12)
[debug] [Appium]     at Function.Module._load (module.js:498:3)
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1585152367260 (11:06:07 GMT-0500 (-05))
[debug] [MJSONWP] Encountered internal error running command: Error: Could not load a driver for automationName 'Flutter' and platformName 'Android'. Please verify your Appium installation
[debug] [MJSONWP]     at AppiumDriver.getDriverAndVersionForCaps (/Users/esteban.zuluaga/.nvm/versions/node/v8.16.1/lib/node_modules/appium/lib/appium.js:237:11)
[debug] [MJSONWP]     at AppiumDriver.createSession (/Users/esteban.zuluaga/.nvm/versions/node/v8.16.1/lib/node_modules/appium/lib/appium.js:311:66)
[debug] [MJSONWP]     at commandExecutor (/Users/esteban.zuluaga/.nvm/versions/node/v8.16.1/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:330:9)
[debug] [MJSONWP]     at AppiumDriver.executeCommand (/Users/esteban.zuluaga/.nvm/versions/node/v8.16.1/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:344:15)
[debug] [MJSONWP]     at AppiumDriver.executeCommand (/Users/esteban.zuluaga/.nvm/versions/node/v8.16.1/lib/node_modules/appium/lib/appium.js:520:26)
[debug] [MJSONWP]     at asyncHandler (/Users/esteban.zuluaga/.nvm/versions/node/v8.16.1/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:309:34)
[debug] [MJSONWP]     at app.(anonymous function) (/Users/esteban.zuluaga/.nvm/versions/node/v8.16.1/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:447:15)
[debug] [MJSONWP]     at Layer.handle [as handle_request] (/Users/esteban.zuluaga/.nvm/versions/node/v8.16.1/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [MJSONWP]     at next (/Users/esteban.zuluaga/.nvm/versions/node/v8.16.1/lib/node_modules/appium/node_modules/express/lib/router/route.js:137:13)
[debug] [MJSONWP]     at Route.dispatch (/Users/esteban.zuluaga/.nvm/versions/node/v8.16.1/lib/node_modules/appium/node_modules/express/lib/router/route.js:112:3)
[debug] [MJSONWP]     at Layer.handle [as handle_request] (/Users/esteban.zuluaga/.nvm/versions/node/v8.16.1/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [MJSONWP]     at /Users/esteban.zuluaga/.nvm/versions/node/v8.16.1/lib/node_modules/appium/node_modules/express/lib/router/index.js:281:22
[debug] [MJSONWP]     at Function.process_params (/Users/esteban.zuluaga/.nvm/versions/node/v8.16.1/lib/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
[debug] [MJSONWP]     at next (/Users/esteban.zuluaga/.nvm/versions/node/v8.16.1/lib/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
[debug] [MJSONWP]     at logger (/Users/esteban.zuluaga/.nvm/versions/node/v8.16.1/lib/node_modules/appium/node_modules/morgan/index.js:144:5)
[debug] [MJSONWP]     at Layer.handle [as handle_request] (/Users/esteban.zuluaga/.nvm/versions/node/v8.16.1/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [MJSONWP]     at trim_prefix (/Users/esteban.zuluaga/.nvm/versions/node/v8.16.1/lib/node_modules/appium/node_modules/express/lib/router/index.js:317:13)
[debug] [MJSONWP]     at /Users/esteban.zuluaga/.nvm/versions/node/v8.16.1/lib/node_modules/appium/node_modules/express/lib/router/index.js:284:7
[debug] [MJSONWP]     at Function.process_params (/Users/esteban.zuluaga/.nvm/versions/node/v8.16.1/lib/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
[debug] [MJSONWP]     at next (/Users/esteban.zuluaga/.nvm/versions/node/v8.16.1/lib/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
[debug] [MJSONWP]     at /Users/esteban.zuluaga/.nvm/versions/node/v8.16.1/lib/node_modules/appium/node_modules/body-parser/lib/read.js:130:5
[debug] [MJSONWP]     at invokeCallback (/Users/esteban.zuluaga/.nvm/versions/node/v8.16.1/lib/node_modules/appium/node_modules/raw-body/index.js:224:16)
[debug] [MJSONWP] Destroying socket connection
[HTTP] <-- POST /wd/hub/session 500 1832 ms - 256
[HTTP] 

```

**Comment by mykola-mokhnach** [comment]
> [debug] [Appium] SyntaxError: Invalid regular expression: /^[ \t]*(?<pid>\d+)[ \t]+(?<ppid>\d+)[ \t]+(?<uid>\d+)[ \t]+(?<cpu>\d+\.\d+)[ \t]+(?<memory>\d+\.\d+)[ \t]+/: Invalid group

It looks like an outdated NodeJS version is used on the machine

**Comment by imurchie** [comment]
Yup. You need Node 10 at the least.

**Comment by ezuluagas** [comment]
thank you

**Comment by ezuluagas** [comment]
@imurchie hi the last question, are you continue gave support to Flutter? because i'll take a decision about if i can use it appium flutter or use flutter driver

**Comment by imurchie** [comment]
Appium will continue to bundle with the Flutter driver. The core team, however, does not have anything to do with the development of the driver, so how much work goes into it is not in our hands.
