### ISSUE TITLE
Unable to parse the command sent from webdriverIO properly on appium cloud server

### ISSUE THREAD

**Issue by Vardhan18** [appium/appium#14152]
## Environment
* Appium version (or git revision) that exhibits the issue: Appium v1.16.0-beta.1 on cloud
* Last Appium version that did not exhibit the issue (if applicable): Local Appium version v1.15.1 woked fine
* Desktop OS/version used to run Appium: Cloud Appium Server 
* Node.js version (unless using Appium.app|exe):[v 12.13.1]
* Npm or Yarn package manager:[6.12.1]
* Mobile platform/version under test: **[DeviceConnect from Mobile Labs](http://docs.mobilelabsinc.com/deviceConnect/deviceConnectDoc/aboutdC.html)**
* Real device or emulator/simulator: Android Device chrome browser

**Issue:**
Appium Cloud not able to parse the body properly: {"{\\"url\\":\"https://www.github.com/\"}":""}. WebdriverIO is sending the data correctly: INFO webdriver: DATA { url: 'https://github.com/' }

 
**Error:**
``` [debug] [WD Proxy] Matched '/wd/hub/session/ddd7089c-bddd-4df2-9a64-9e9de630cf51/url' to command name 'setUrl' 
 [debug] [WD Proxy] Proxying [POST /wd/hub/session/ddd7089c-bddd-4df2-9a64-9e9de630cf51/url] to [POST http://127.0.0.1:23260/wd/hub/session/3c62c83ce331d49ffc8ff00186d89366/url] with body: {"{\"url\":\"https://www.github.com/\"}":""}
 [WD Proxy] Got an unexpected response with status 400: {"value":{"error":"invalid argument","message":"invalid argument: 'url' must be a string\n
```

**Details**
Issue details as per the below link

[https://github.com/webdriverio/webdriverio/issues/5230](https://github.com/webdriverio/webdriverio/issues/5230)

**Expected behavior**
URL should be launched on the mobile browser with proper parsing

**WebDriverIo Logs:**
```log
 INFO webdriver: DATA { url: 'https://github.com/' }
[0-0] ERROR webdriver: Request failed due to Error: invalid argument: 'url' must be a string  (Session info: chrome=80.0.3987.149)
    at getErrorFromResponseBody (C:\U\Hello\node_modules\webdriver\build\utils.js:124:10)
    at WebDriverRequest._request (C:\U\Hello\node_modules\webdriver\build\request.js:118:56)    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Browser.wrapCommandFn (C:\U\Hello\node_modules\@wdio\utils\build\shim.js:74:23)
    at Browser.wrapCommandFn (C:\U\Hello\node_modules\@wdio\utils\build\shim.js:74:23)
    at World.<anonymous> (C:\U\Hello\tests\steps\/abcd.steps.js:5:5)
    at World.executeAsync (C:\U\Hello\node_modules\@wdio\utils\build\shim.js:123:12)
    at World.testFrameworkFnWrapper (C:\U\Hello\node_modules\@wdio\utils\build\test-framework\testFnWrapper.js:57:14)
[0-0] Error in "Example feature: Get size of an element: Given I go on the website "https://github.com/""
invalid argument: 'url' must be a string
  (Session info: chrome=80.0.3987.149)
[0-0] 2020-04-07T11:52:18.799Z INFO webdriver: COMMAND deleteSession()
```
 
**APPIUM logs:**
```log
[2020-04-07 07:52:40.3112, 26912] [HTTP] <-- POST /wd/hub/session 200 6277 ms - 1298
[2020-04-07 07:52:40.3112, 26912] [HTTP]
[2020-04-07 07:52:41.7949, 26912] [HTTP] --> POST /wd/hub/session/76dfd7df-dffd-4e2c-b287-10b67029c880/url
[2020-04-07 07:52:41.7950, 26912] [HTTP] {"{\"url\":\"https://github.com/\"}":""}
[2020-04-07 07:52:41.7971, 26912] [MJSONWP (76dfd7df)] Driver proxy active, passing request on via HTTP proxy
[2020-04-07 07:52:41.7976, 26912] [debug] [WD Proxy] Matched '/wd/hub/session/76dfd7df-dffd-4e2c-b287-10b67029c880/url' to command name 'setUrl'
[2020-04-07 07:52:41.7978, 26912] [debug] [WD Proxy] Proxying [POST /wd/hub/session/76dfd7df-dffd-4e2c-b287-10b67029c880/url] to [POST http://127.0.0.1:23266/wd/hub/session/332bee14d185b4173a5661043bba6ad7/url] with body: {"{\"url\":\"https://github.com/\"}":""}
[2020-04-07 07:52:41.8257, 26912] [WD Proxy] Got an unexpected response with status 400: {"value":{"error":"invalid argument","message":"invalid argument: 'url' must be a string\n  (Session info: chrome=80.0.3987.149)","stacktrace":"0   chromedriver-79.0.3945.36-79to79    0x000000010d687e29 chromedriver-79.0.3945.36-79to79 + 3817001\n1   chromedriver-79.0.3945.36-79to79    0x000000010d61bf33 chromedriver-79.0.3945.36-79to79 + 3374899\n2   chromedriver-79.0.3945.36-79to79    0x000000010d39c8bf chromedriver-79.0.3945.36-79to79 + 755903\n3   chromedriver-79.0.3945.36-79to79    0x000000010d3321e1 chromedriver-79.0.3945.36-79to79 + 319969\n4   chromedriver-79.0.3945.36-79to79    0x000000010d325192 chromedriver-79.0.3945.36-79to79 + 266642\n5   chromedriver-79.0.3945.36-79to79    0x000000010d331c1b chromedriver-79.0.3945.36-79to79 + 318491\n6   chromedriver-79.0.3945.36-79to79    0x000000010d3254a3 chromedriver-79.0.3945.36-79to79 + 267427\n7   chromedriver-79.0.3945.36-79to79    0x000000010d2fec0d chromedriver-79.0.3945.36-79to79 + 109581\n8   chromedriver-79.0.3945.36-79to79    0x000000010d2ffba5 ...
[2020-04-07 07:52:41.8474, 26912] [debug] [MJSONWP (76dfd7df)] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: 400 - {"value":{"error":"invalid argument","message":"invalid argument: 'url' must be a string\n  (Session info: chrome=80.0.3987.149)","stacktrace":"0   chromedriver-79.0.3945.36-79to79    0x000000010d687e29 chromedriver-79.0.3945.36-79to79 + 3817001\n1   chromedriver-79.0.3945.36-79to79    0x000000010d61bf33 chromedriver-79.0.3945.36-79to79 + 3374899\n2   chromedriver-79.0.3945.36-79to79    0x000000010d39c8bf chromedriver-79.0.3945.36-79to79 + 755903\n3   chromedriver-79.0.3945.36-79to79    0x000000010d3321e1 chromedriver-79.0.3945.36-79to79 + 319969\n4   chromedriver-79.0.3945.36-79to79    0x000000010d325192 chromedriver-79.0.3945.36-79to79 + 266642\n5   chromedriver-79.0.3945.36-79to79    0x000000010d331c1b chromedriver-79.0.3945.36-79to79 + 318491\n6   chromedriver-79.0.3945.36-79to79    0x000000010d3254a3 chromedriver-79.0.3945.36-79to79 + 267427\n7   chromedriver-79.0.3945.36-79to79    0x000000010d2fec0d chromedriver-79.0.3945.36-79to79 + 109581\n8   chromedriver-79.0.3945.36-79to79    0x000000010d2ffba5 chromedriver-79.0.3945.36-79to79 + 113573\n9   chromedriver-79.0.3945.36-79to79    0x000000010d649f6f chromedriver-79.0.3945.36-79to79 + 3563375\n10  chromedriver-79.0.3945.36-79to79    0x000000010d656e3a chromedriver-79.0.3945.36-79to79 + 3616314\n11  chromedriver-79.0.3945.36-79to79    0x000000010d656bf7 chromedriver-79.0.3945.36-79to79 + 3615735\n12  chromedriver-79.0.3945.36-79to79    0x000000010d629699 chromedriver-79.0.3945.36-79to79 + 3430041\n13  chromedriver-79.0.3945.36-79to79    0x000000010d657692 chromedriver-79.0.3945.36-79to79 + 3618450\n14  chromedriver-79.0.3945.36-79to79    0x000000010d63de17 chromedriver-79.0.3945.36-79to79 + 3513879\n15  chromedriver-79.0.3945.36-79to79    0x000000010d66cfe4 chromedriver-79.0.3945.36-79to79 + 3706852\n16  chromedriver-79.0.3945.36-79to79    0x000000010d68dfc7 chromedriver-79.0.3945.36-79to79 + 3841991\n17  libsystem_pthread.dylib             0x00007fff5e3f12eb _pthread_body + 126\n18  libsystem_pthread.dylib             0x00007fff5e3f4249 _pthread_start + 66\n19  libsystem_pthread.dylib             0x00007fff5e3f040d thread_start + 13\n"}}
[2020-04-07 07:52:41.8475, 26912] [debug] [MJSONWP (76dfd7df)]     at JWProxy.proxy (/usr/local/deviceconnect/Appium/dc-appium-1.16.0-beta.1/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:222:13)
[2020-04-07 07:52:41.8475, 26912] [debug] [W3C] Matched W3C error code 'invalid argument' to InvalidArgumentError
```

**Comment by mykola-mokhnach** [comment]
I don't observe any issues there:

> [2020-04-07 07:52:41.7949, 26912] [HTTP] --> POST /wd/hub/session/76dfd7df-dffd-4e2c-b287-10b67029c880/url
> [2020-04-07 07:52:41.7950, 26912] [HTTP] {"{\"url\":\"https://github.com/\"}":""}

The server receives an invalid argument for /url API call and responds with the error

**Comment by Vardhan18** [comment]
```
[2020-04-07 07:52:41.7949, 26912] [HTTP] --> POST /wd/hub/session/76dfd7df-dffd-4e2c-b287-10b67029c880/url
[2020-04-07 07:52:41.7950, 26912] [HTTP] {"{\\"url\\":\"https://github.com/\"}":""}
[2020-04-07 07:52:41.7971, 26912] [MJSONWP (76dfd7df)] Driver proxy active, passing request on via HTTP proxy
[2020-04-07 07:52:41.7976, 26912] [debug] [WD Proxy] Matched '/wd/hub/session/76dfd7df-dffd-4e2c-b287-10b67029c880/url' to command name 'setUrl'
[2020-04-07 07:52:41.7978, 26912] [debug] [WD Proxy] Proxying [POST /wd/hub/session/76dfd7df-dffd-4e2c-b287-10b67029c880/url] to [POST http://127.0.0.1:23266/wd/hub/session/332bee14d185b4173a5661043bba6ad7/url] with body: {"{\"url\":\"https://github.com/\"}":""}
[2020-04-07 07:52:41.8257, 26912] [WD Proxy] Got an unexpected response with status 400: {"value":{"error":"invalid argument","message":"invalid argument: 'url' must be a string\n  
```
This above particular log on Appium server on cloud 

But on local appium server the log displayed as 
```
[HTTP] --> POST /wd/hub/session/517c90fa-1e0e-4dac-9e26-c7149f843bea/url
[HTTP] {"url":"https://github.com/"}
[W3C (517c90fa)] Driver proxy active, passing request on via HTTP proxy
[WD Proxy] Matched '/wd/hub/session/517c90fa-1e0e-4dac-9e26-c7149f843bea/url' to command name 'setUrl'
[WD Proxy] Proxying [POST /wd/hub/session/517c90fa-1e0e-4dac-9e26-c7149f843bea/url] to [POST http://127.0.0.1:8000/wd/hub/session/8aec5225e33797256226465f52f8d3ab/url] with body: {"url":"https://github.com/"}
```

**Comment by mykola-mokhnach** [comment]
I don't have any good ideas why the request body is being escaped like that, but there is practically nothing that can be done on server side. You must check what is going on in your env before the client request reaches the server (it also might be the bug of the particular cloud provider)

**Comment by Vardhan18** [comment]
Thanks @mykola-mokhnach . we will try to reach out the cloud provider.
**Here is the request:**
```
[0-0] {
  request: {
    debugId: 1,
    uri: 'http://xx:80/Appium/session/ee7b2167-8fce-4a85-a4cc-e2a6e5ebe3a6/url',
    method: 'POST',
    headers: {
      Connection: 'keep-alive',
      Accept: 'application/json',
      'User-Agent': 'webdriver/5.22.4',
      'Content-Length': 29,
      host: 'xx.xx.xx.xx',
      'content-type': 'application/json'
    },
    body: '{"url":"https://github.com/"}'
  }
}
 ```

**Response:**
```
[0-0] {
  response: {
    debugId: 1,
    headers: {
      server: 'nginx',
      date: 'Wed, 08 Apr 2020 10:33:38 GMT',
      'content-type': 'application/json',
      'content-length': '167',
      connection: 'keep-alive',
      'cache-control': 'private',
      'x-ua-compatible': 'IE=edge',
      'x-path': '/Appium/session/ee7b2167-8fce-4a85-a4cc-e2a6e5ebe3a6/url'
    },
    statusCode: 200,
    body: {
      status: 61,
      value: [Object],
      sessionId: 'ca499da5-0f71-4f33-8042-7944c04a825f'
    }
  }
}
```

**Comment by mykola-mokhnach** [comment]
I don't observe any issues on the Appium server side here.
Closed as not an issue.
