### ISSUE TITLE
With appium 1.15.1 desired capabilities parameter fullContextList: 'true', shows error.

### ISSUE THREAD

**Issue by dipti-code** [appium/appium#14195]
## The problem
With appium 1.15.1 desired capabilities parameter fullContextList: 'true', shows error.

It showing Error: Malformed type for "name" parameter of command switchContext
Expected: string
Actual: object

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac
* Node.js version (unless using Appium.app|exe): 12.x.x
* Npm or Yarn package manager: 6.12.x
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

My config file has 

onfig.capabilities = [
    {
        // The defaults you need to have in your config
        platformName: 'iOS',
        maxInstances: 1,
        // For W3C the appium capabilities need to have an extension prefix
        // This is `appium:` for all Appium Capabilities which can be found here
        // http://appium.io/docs/en/writing-running-appium/caps/
          //  'appium:deviceName': 'iPhone XS Max',
        'appium:deviceName': 'iPhone 11',
        'appium:platformVersion': '13.3',
        'appium:orientation': 'PORTRAIT',
        // "useNewWDA": true,
        "startIWDP": true,
        // `automationName` will be mandatory, see
        // https://github.com/appium/appium/releases/tag/v1.13.0
        'appium:automationName': 'XCUITest',
        'appium:udid': 'auto',
        'appium:includeSafariInWebviews': 'true',
        fullContextList: 'true',
           
         'appium:app': join(process.cwd(), './apps/iOS-Simulator-NativeDemoApp-0.2.1.app.zip'),
        // Read the reset strategies very well, they differ per platform, see
        // http://appium.io/docs/en/writing-running-appium/other/reset-strategies/
        'appium:noReset': true,
        'appium:newCommandTimeout': 240,

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Please use the most recent server version and provide the full log from it

**Comment by dipti-code** [comment]
> Please use the most recent server version and provide the full log from it

@mykola-mokhnach if i upgrade may be my test cases starts failing, and i may revert back to old. So with that complication its very difficult. any other way.

**Comment by mykola-mokhnach** [comment]
Unfortunately, we don't provide patches to older Appium versions. I don't see any other good solutions here

**Comment by dipti-code** [comment]
but 'appium:includeSafariInWebviews': 'true',
fullContextList: 'true', command supports in 1.15.1? if yes what is the exact syntax.?

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium/blob/8cffb5274854c4cc1e639d56fb2e539c6a5c1786/CHANGELOG.md#L28
`fullContextList` was added in 1.17

**Comment by dipti-code** [comment]
Then how its working https://github.com/appium/appium/issues/13171
used by another user before.

**Comment by KazuCocoa** [comment]
ah, 1.17.0 start returning WebView data as the list.

We cannot say anything without the full server log as Mykola already commented. I guess your code sent _object_, but not sure what was wrong.

**Comment by dipti-code** [comment]
While upgrading to 1.17.0, then 

its not launching at all.





Execution of 1 spec files started at 2020-04-17T10:18:04.654Z

2020-04-17T10:18:04.655Z DEBUG @wdio/utils:initialiseServices: initialise service "appium" as NPM package
2020-04-17T10:18:04.660Z INFO @wdio/cli:launcher: Run onPrepare hook
2020-04-17T10:18:04.661Z DEBUG @wdio/appium-service: Will spawn Appium process: appium --base-path /
2020-04-17T10:18:05.285Z DEBUG @wdio/appium-service: Appium started with ID: 7762
2020-04-17T10:18:05.287Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2020-04-17T10:18:05.288Z INFO @wdio/local-runner: Start worker 0-0 with arg: ./config/wdio.ios.app.conf.js
[0-0] 2020-04-17T10:18:05.568Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2020-04-17T10:18:05.572Z DEBUG @wdio/local-runner:utils: init remote session
[0-0] 2020-04-17T10:18:05.574Z INFO webdriverio: Initiate new session using the ./protocol-stub protocol
[0-0] RUNNING in iOS - /tests/specs/app.webview.spec.js
[0-0] 2020-04-17T10:18:05.895Z DEBUG @wdio/utils:initialiseServices: initialise service "appium" as NPM package
[0-0] 2020-04-17T10:18:05.899Z DEBUG @wdio/local-runner:utils: init remote session
[0-0] 2020-04-17T10:18:05.900Z INFO webdriverio: Initiate new session using the webdriver protocol
[0-0] 2020-04-17T10:18:05.901Z INFO webdriver: [POST] http://localhost:4723/session
[0-0] 2020-04-17T10:18:05.901Z INFO webdriver: DATA {
capabilities: {
alwaysMatch: {
platformName: 'iOS',
'appium:deviceName': 'iPhone 11',
'appium:platformVersion': '13.3',
'appium:orientation': 'PORTRAIT',
startIWDP: true,
'appium:automationName': 'XCUITest',
'appium:udid': 'auto',
'appium:includeSafariInWebviews': 'true',
'appium:app': '/Users/drlenka/Documents/DeathStar_Appium/appium/apps/Hyland Mobile.app',
'appium:noReset': true,
'appium:newCommandTimeout': 240
},
firstMatch: [ {} ]
},
desiredCapabilities: {
platformName: 'iOS',
'appium:deviceName': 'iPhone 11',
'appium:platformVersion': '13.3',
'appium:orientation': 'PORTRAIT',
startIWDP: true,
'appium:automationName': 'XCUITest',
'appium:udid': 'auto',
'appium:includeSafariInWebviews': 'true',
'appium:app': '/Users/drlenka/Documents/DeathStar_Appium/appium/apps/Hyland Mobile.app',
'appium:noReset': true,
'appium:newCommandTimeout': 240
}
}
[0-0] 2020-04-17T10:18:06.895Z DEBUG webdriver: request failed due to response error: unknown error
[0-0] 2020-04-17T10:18:06.896Z WARN webdriver: Request failed with status 500 due to An unknown server-side error occurred while processing the command. Original error: Simulator architecture is unsupported by the '/Users/drlenka/Documents/DeathStar_Appium/appium/apps/Hyland Mobile.app' application. Make sure the correct deployment target has been selected for its compilation in Xcode.
[0-0] 2020-04-17T10:18:06.896Z INFO webdriver: Retrying 1/3
2020-04-17T10:18:06.896Z INFO webdriver: [POST] http://localhost:4723/session
[0-0] 2020-04-17T10:18:06.896Z INFO webdriver: DATA {
capabilities: {
alwaysMatch: {
platformName: 'iOS',
'appium:deviceName': 'iPhone 11',
'appium:platformVersion': '13.3',
'appium:orientation': 'PORTRAIT',
startIWDP: true,
'appium:automationName': 'XCUITest',
'appium:udid': 'auto',
'appium:includeSafariInWebviews': 'true',
'appium:app': '/Users/drlenka/Documents/DeathStar_Appium/appium/apps/Hyland Mobile.app',
'appium:noReset': true,
'appium:newCommandTimeout': 240
},
firstMatch: [ {} ]
},
desiredCapabilities: {
platformName: 'iOS',
'appium:deviceName': 'iPhone 11',
'appium:platformVersion': '13.3',
'appium:orientation': 'PORTRAIT',
startIWDP: true,
'appium:automationName': 'XCUITest',
'appium:udid': 'auto',
'appium:includeSafariInWebviews': 'true',
'appium:app': '/Users/drlenka/Documents/DeathStar_Appium/appium/apps/Hyland Mobile.app',
'appium:noReset': true,
'appium:newCommandTimeout': 240
}
}
[0-0] 2020-04-17T10:18:06.901Z ERROR webdriver: GotError: read ECON

**Comment by KazuCocoa** [comment]
> [0-0] 2020-04-17T10:18:06.896Z WARN webdriver: Request failed with status 500 due to An unknown server-side error occurred while processing the command. Original error: Simulator architecture is unsupported by the '/Users/drlenka/Documents/DeathStar_Appium/appium/apps/XX Mobile.app' application. Make sure the correct deployment target has been selected for its compilation in Xcode.

The log said your `.app` had no proper deployment target build for the simulator. (The error came from XCTest framework.)
Please make sure your `.app` works for the simulator via Xcode.

**Comment by dipti-code** [comment]
Yes its working perfectly with xcode. i thinks its a warning.

**Comment by dipti-code** [comment]
[0-0] 2020-04-17T10:31:59.025Z ERROR webdriver: GotError: read ECONNRESET
at onError (/Users/drlenka/Documents/DeathStar_Appium/appium/node_modules/got/dist/source/request-as-event-emitter.js:140:29)
at ClientRequest.<anonymous> (/Users/drlenka/Documents/DeathStar_Appium/appium/node_modules/got/dist/source/request-as-event-emitter.js:157:17)
at ClientRequest.emit (events.js:323:22)
at ClientRequest.EventEmitter.emit (domain.js:482:12)
at ClientRequest.origin.emit (/Users/drlenka/Documents/DeathStar_Appium/appium/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
at Socket.socketErrorListener (_http_client.js:426:9)
at Socket.emit (events.js:311:20)
at Socket.EventEmitter.emit (domain.js:482:12)
at emitErrorNT (internal/streams/destroy.js:92:8)
at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
[0-0] 2020-04-17T10:31:59.025Z ERROR @wdio/runner: Error: Failed to create session.
read ECONNRESET
at startWebDriverSession (/Users/drlenka/Documents/DeathStar_Appium/appium/node_modules/@wdio/runner/node_modules/webdriver/build/utils.js:45:11)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
[0-0] Error: Failed to create session.
read ECONNRESET
2020-04-17T10:31:59.140Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 1
[0-0] FAILED in iOS - /tests/specs/app.webview.spec.js
2020-04-17T10:31:59.141Z INFO @wdio/cli:launcher: Run onComplete hook
2020-04-17T10:31:59.141Z DEBUG @wdio/appium-service: Appium (pid: 8386) killed

Spec Files: 0 passed, 1 failed, 1 total (100% completed) in 00:00:02

2020-04-17T10:31:59.141Z INFO @wdio/local-runner: Shutting down spawned worker
2020-04-17T10:31:59.397Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2020-04-17T10:31:59.398Z INFO @wdio/local-runner: shutting down
npm ERR! code ELIFECYCLE

**Comment by KazuCocoa** [comment]
> [0-0] 2020-04-17T10:18:06.896Z WARN webdriver: Request failed with status 500 due to An unknown server-side error occurred while processing the command. Original error: Simulator architecture is unsupported by the '/Users/drlenka/Documents/DeathStar_Appium/appium/apps/XX Mobile.app' application. Make sure the correct deployment target has been selected for its compilation in Xcode.

ah, the 500 status error was not the error case?
(I'm not familiar with webdriverio's wrapped log)

Then, can you get the vanilla Appium server log? With `showXcodeLog` capability may also help.

**Comment by dipti-code** [comment]
what does fullContextList: 'true', do.?
i created my own context switching class that may be the reason. but what actually it returns ?

**Comment by KazuCocoa** [comment]
Do you mean the response? It is below.

```
[8] pry(#<AppiumLibCoreTest::DriverTest>)> @driver.available_contexts
=> [{"id"=>"NATIVE_APP"},
 {"id"=>"WEBVIEW_39627.1",
  "title"=>"WKWebView",
  "url"=>"file:///Users/kazu/Library/Developer/CoreSimulator/Devices/F9F30814-75E5-45DD-98A5-5650B97E63D2/data/Containers/Bundle/Application/C165B940-7949-4CE4-87E6-BF99A8983078/UICatalog.app/Base.lproj/content.html",
  "bundleId"=>"com.example.apple-samplecode.UICatalog"}]
```

**Comment by dipti-code** [comment]
I write in my code someting like this in a .js file which am using for switching the context.
e.g
export const CONTEXT_REF = {
    NATIVE: 'native',
    WEBVIEW: 'webview',
    
};


class WebView {
   
    waitForWebViewContextLoaded () {
        driver.waitUntil(
            () => {
                const currentContexts = this.getCurrentContexts();

                return currentContexts.length > 1 &&
                    currentContexts.find(context => context.toLowerCase().includes(CONTEXT_REF.WEBVIEW));
            }, {
                timeout: 10000,
                timeoutMsg: 'Webview context not loaded',
                interval: 100,
            },
        );
    }

    /**
     * Switch to native or webview context
     *
     * @param {string} context should be native or webview
     */
    switchToContext (context) {
        driver.switchContext(this.getCurrentContexts()[context === CONTEXT_REF.WEBVIEW ? 1 : 0]);
    }
    /**
     * Returns an object with the list of all available contexts
     *
     * @return {object} An object containing the list of all available contexts
     */
    getCurrentContexts () {
        return driver.getContexts();
    }


if i use that.js file in my code, then with fullContextList: 'true', in my desired capability, my application failed wehn it got someting in the spec file like.
**xyzscreen.switchToContext(CONTEXT_REF.WEBVIEW);**

But without using my cusom js file as above lines of code, fullContextList: 'true',  works fine , with manual swithing the context my driver.switchContext();

**Comment by KazuCocoa** [comment]
Please provide context id in the case as same as without `fullContextList` capability case. 
I mean something like `switchContext('NATIVE_APP')`.
http://appium.io/docs/en/commands/context/set-context/
