### ISSUE TITLE
Clarification on "automatic discovery of compatible Chromedriver" functionality

### ISSUE THREAD

**Issue by mcopjan** [appium/appium#14260]
I have 2 Android simulators with Chrome version 74 and I wanted to use the automatic chromedriver functionality. These are my session capabilities

**Appium v1.17.0**
```
Appium v1.17.0 creating new AndroidUiautomator2Driver (v1.44.2) session
2020-05-01 12:26:57:732 [Appium] Explicitly enabling use of insecure features:
2020-05-01 12:26:57:732 [Appium]     chromedriver_autodownload
2020-05-01 12:26:57:734 [BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
2020-05-01 12:26:57:734 [BaseDriver] Creating session with W3C capabilities: {
2020-05-01 12:26:57:734 [BaseDriver]   "alwaysMatch": {
2020-05-01 12:26:57:734 [BaseDriver]     "appium:newCommandTimeout": 180,
2020-05-01 12:26:57:734 [BaseDriver]     "appium:adbExecTimeout": 60000,
2020-05-01 12:26:57:734 [BaseDriver]     "appium:autoGrantPermissions": true,
2020-05-01 12:26:57:734 [BaseDriver]     "appium:uiautomator2ServerInstallTimeout": 30000,
2020-05-01 12:26:57:734 [BaseDriver]     "appium:uiautomator2ServerLaunchTimeout": 60000,
2020-05-01 12:26:57:734 [BaseDriver]     "appium:deviceName": "ANDROID",
2020-05-01 12:26:57:734 [BaseDriver]     "appium:platform": "ANDROID",
2020-05-01 12:26:57:735 [BaseDriver]     "browserName": "Chrome",
2020-05-01 12:26:57:735 [BaseDriver]     "goog:chromeOptions": {
2020-05-01 12:26:57:735 [BaseDriver]       "w3c": false
2020-05-01 12:26:57:735 [BaseDriver]     },
2020-05-01 12:26:57:735 [BaseDriver]     "platformName": "android",
2020-05-01 12:26:57:735 [BaseDriver]     "server:CONFIG_UUID": "0a954d64-b1e6-4482-8495-873fec81e78e",
2020-05-01 12:26:57:735 [BaseDriver]     "appium:systemPort": "8201",
2020-05-01 12:26:57:735 [BaseDriver]     "appium:chromedriverChromeMappingFile": "/Users/martinco/chromedrivers/mapping.json",
2020-05-01 12:26:57:735 [BaseDriver]     "appium:chromedriverExecutableDir": "/Users/martinco/chromedrivers",
2020-05-01 12:26:57:735 [BaseDriver]     "appium:udid": "emulator-5556",
2020-05-01 12:26:57:735 [BaseDriver]     "appium:chromedriverPort": 9101
2020-05-01 12:26:57:735 [BaseDriver]   },
2020-05-01 12:26:57:735 [BaseDriver]   "firstMatch": [
2020-05-01 12:26:57:735 [BaseDriver]     {}
2020-05-01 12:26:57:736 [BaseDriver]   ]
2020-05-01 12:26:57:736 [BaseDriver] }
```
Expected behaviour:

My mapping.json is empty. If I understand documentation correctly, Appium should detect browser version, download corresponding chromedriver.exe into the chromedriverExecutableDir and update the mapping.json file (permissions for both the Dir and .json are read/write for everyone)

Actual behaviour
```
2020-05-01 13:05:57:225 [AndroidDriver] Starting a chrome-based browser session
2020-05-01 13:05:57:225 [AndroidDriver] Using user-specified port 9101 for chromedriver
2020-05-01 13:05:57:226 [AndroidDriver] Merging 'goog:chromeOptions' into 'chromeOptions'. This may cause unexpected behavior
2020-05-01 13:05:57:226 [AndroidDriver] Before starting chromedriver, androidPackage is 'com.android.chrome'
2020-05-01 13:05:57:226 [Chromedriver] Changed state to 'starting'
2020-05-01 13:05:57:226 [Chromedriver] Attempting to use Chromedriver-Chrome mapping from '/Users/martinco/chromedrivers/mapping.json'
2020-05-01 13:05:57:227 [Chromedriver] Error parsing mapping from '/Users/martinco/chromedrivers/mapping.json': Unexpected end of JSON input
2020-05-01 13:05:57:227 [Chromedriver] Using default mapping
2020-05-01 13:05:57:228 [Chromedriver] Found 1 executable in '/Users/martinco/chromedrivers'
2020-05-01 13:05:57:236 [Chromedriver] Cannot retrieve version number from 'mapping.json' Chromedriver binary. Make sure it returns a valid version string in response to '--version' command line argument. Cannot parse the version string
2020-05-01 13:05:57:236 [Chromedriver] No Chromedrivers were found in '/Users/martinco/chromedrivers'
2020-05-01 13:05:57:237 [ADB] Getting package info for 'com.android.chrome'
2020-05-01 13:05:57:237 [ADB] Running '/Users/martinco/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5556 shell dumpsys package com.android.chrome'
2020-05-01 13:05:57:265 [Chromedriver] Found Chrome bundle 'com.android.chrome' version '74.0.3729'
2020-05-01 13:05:57:405 [Chromedriver] Cannot synchronize local chromedrivers with the remote storage at https://chromedriver.storage.googleapis.com: Error: self signed certificate in certificate chain
2020-05-01 13:05:57:405 [Chromedriver] RequestError: Error: self signed certificate in certificate chain
2020-05-01 13:05:57:405 [Chromedriver]     at new RequestError (/usr/local/lib/node_modules/appium/node_modules/request-promise-core/lib/errors.js:14:15)
2020-05-01 13:05:57:405 [Chromedriver]     at Request.plumbing.callback (/usr/local/lib/node_modules/appium/node_modules/request-promise-core/lib/plumbing.js:87:29)
2020-05-01 13:05:57:405 [Chromedriver]     at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/appium/node_modules/request-promise-core/lib/plumbing.js:46:31)
2020-05-01 13:05:57:406 [Chromedriver]     at self.callback (/usr/local/lib/node_modules/appium/node_modules/request/request.js:185:22)
2020-05-01 13:05:57:406 [Chromedriver]     at Request.emit (events.js:210:5)
2020-05-01 13:05:57:406 [Chromedriver]     at Request.onRequestError (/usr/local/lib/node_modules/appium/node_modules/request/request.js:877:8)
2020-05-01 13:05:57:406 [Chromedriver]     at ClientRequest.emit (events.js:215:7)
2020-05-01 13:05:57:406 [Chromedriver]     at TLSSocket.socketErrorListener (_http_client.js:406:9)
2020-05-01 13:05:57:406 [Chromedriver]     at TLSSocket.emit (events.js:210:5)
2020-05-01 13:05:57:406 [Chromedriver]     at emitErrorNT (internal/streams/destroy.js:92:8)
2020-05-01 13:05:57:406 [Chromedriver]     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
2020-05-01 13:05:57:407 [Chromedriver]     at processTicksAndRejections (internal/process/task_queues.js:80:21)
2020-05-01 13:05:57:407 [Chromedriver] Error: No Chromedriver found that can automate Chrome '74.0.3729'. See https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md for more details
2020-05-01 13:05:57:407 [Chromedriver]     at Chromedriver.getCompatibleChromedriver (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/lib/chromedriver.js:413:15)
2020-05-01 13:05:57:408 [Chromedriver] No Chromedriver found that can automate Chrome '74.0.3729'. See https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md for more details
2020-05-01 13:05:57:408 [UiAutomator2] Deleting UiAutomator2 session
2020-05-01 13:05:57:408 [UiAutomator2] Deleting UiAutomator2 server session
2020-05-01 13:05:57:408 [WD Proxy] Matched '/' to command name 'deleteSession'
```

Now I can see that there is a problem with my mapping.json so I tried to provide https://github.com/appium/appium-chromedriver/blob/master/config/mapping.json with not much difference, only a different error. So I assume I still have to provide version mapping, this is not happening automatically?

Other problem  I see is "Error: self signed certificate in certificate chain". Now, I have faced this problem when installing Appium and managed to sorted this out by modifying .npmrc and adding chromedriver_cdnurl=http://npm.taobao.org/mirrors/chromedriver as per https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md
I am confused Appium is still reaching https://chromedriver.storage.googleapis.com repository instead of the one specified in .npmrc. I also tried to add the Env variable into my .bash_profile, but I assume in incorrect format as some commands afterwards stopped working so I removed that.
Can you please advice on the above behaviour?

**Comment by mykola-mokhnach** [comment]
> Other problem I see is "Error: self signed certificate in certificate chain". Now, I have faced this problem when installing Appium and managed to sorted this out by modifying .npmrc and adding chromedriver_cdnurl=http://npm.taobao.org/mirrors/chromedriver as per https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md
> I am confused Appium is still reaching https://chromedriver.storage.googleapis.com repository instead of the one specified in .npmrc. I also tried to add the Env variable into my .bash_profile, but I assume in incorrect format as some commands afterwards stopped working so I removed that.
> Can you please advice on the above behaviour?

This URL is currently hardcoded for the autodownload feature. This could be customized though.

> "Error: self signed certificate in certificate chain" 

is probably happening because of great Chinese firewall

**Comment by mcopjan** [comment]
@mykola-mokhnach thanks for your quick answer, It would help if the Url was configurable, also in regards to the "Error parsing mapping from '/Users/martinco/chromedrivers/mapping.json': Unexpected end of JSON input". Is chromedriverChromeMappingFile desired capability even needed when using autodownload feature? If so is this file updated automatically or I still have to provide mapping chromedriver->browser?

**Comment by mykola-mokhnach** [comment]
Yes, the mapping is updated, but there were some known bugs in v 1.17. These should be addressed in appium@beta

**Comment by mykola-mokhnach** [comment]
The patch has been published to appium@beta
