### ISSUE TITLE
Scrolling does not work on iOS

### ISSUE THREAD

**Issue by George-BC** [appium/appium#14286]
## The problem
I have a scroll function that works perfectly fine on Android but not at all on iOS (crashes app). I tried using the example code from webdriverio documentation and even that doesn't work (no error is thrown, just no movement happens).

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.0
* Desktop OS/version used to run Appium: Mac OS 10.15.4 (19E287)
* Node.js version (unless using Appium.app|exe): 12.16.1
* Npm or Yarn package manager: 6.13.4
* Mobile platform/version under test: iOS 13.1
* Real device or emulator/simulator: Both

## Code To Reproduce Issue [ Good To Have ]

My own function (works on Android, crash on iOS):
```
async scrollAction (direction) {
        try {
            let yValue;
            const coordinates = await this.getScrollCoordinates();
            switch (direction) {
                case "up":
                    yValue = coordinates.yValueEndUp;
                    break;
                case "down":
                    yValue = coordinates.yValueEndDown;
                    break;
                }   
            await this.driver.touchPerform([
                { action: 'press', options: { x: coordinates.xValue, y: coordinates.yValueStart }},
                { action: 'wait', options: 80},
                { action: 'moveTo', options: { x: coordinates.xValue, y: yValue }},
                { action: 'release' }
              ]);
        } catch (error) {
            assert.fail("Unable to scroll. Error: " + error);
        }
    }

    // required for scroll to work seamlessly on different screen sizes
    async getScrollCoordinates () {
        try {
            let screenSize;
            screenSize = await this.driver.getWindowSize();

            return {
                xValue : screenSize.width*0.5,
                yValueStart : screenSize.height*0.5,
                yValueEndUp : screenSize.height*0.25,
                yValueEndDown : screenSize.height*0.75
            };
        } catch (error) {
            assert.fail("Unable to get scroll coordinates");
        }
    }
```

Code from webdriverio documentation that doesn't work (no movement):

```
 const startPercentage = 10;
const endPercentage = 90;
const anchorPercentage = 50;
 
const { width, height } = driver.getWindowSize(); 
const anchor = height * anchorPercentage / 100;
const startPoint = width * startPercentage / 100;
const endPoint = width * endPercentage / 100;
driver.touchPerform([
  {
     action: 'press',
     options: {
       x: startPoint,
       y: anchor,
     },
   },
   {
     action: 'wait',
     options: {
       ms: 100,
     },
   },
   {
     action: 'moveTo',
     options: {
       x: endPoint,
       y: anchor,
     },
   },
   {
     action: 'release',
     options: {},
   },
 ]);
```

## Link to Appium logs

```
debug] [W3C (31d3f8af)] Calling AppiumDriver.getWindowRect() with args: ["31d3f8af-80e2-43eb-95f8-7874063cbfdb"]
[debug] [XCUITest] Executing command 'getWindowRect'
[debug] [WD Proxy] Proxying [GET /window/size] to [GET http://127.0.0.1:8100/session/A790C2AC-233A-4BB5-937A-53CA817AD1E6/window/size] with no body
[debug] [WD Proxy] Got response with status 200: {
[debug] [WD Proxy]   "value" : {
[debug] [WD Proxy]     "width" : 375,
[debug] [WD Proxy]     "height" : 812
[debug] [WD Proxy]   },
[debug] [WD Proxy]   "sessionId" : "A790C2AC-233A-4BB5-937A-53CA817AD1E6"
[debug] [WD Proxy] }
[debug] [W3C (31d3f8af)] Responding to client with driver.getWindowRect() result: {"width":375,"height":812,"x":0,"y":0}
[HTTP] <-- GET /wd/hub/session/31d3f8af-80e2-43eb-95f8-7874063cbfdb/window/rect 200 196 ms - 48
[HTTP] 
[HTTP] --> POST /wd/hub/session/31d3f8af-80e2-43eb-95f8-7874063cbfdb/touch/perform
[HTTP] {"actions":[{"action":"press","options":{"x":187.5,"y":406}},{"action":"wait","options":80},{"action":"moveTo","options":{"x":187.5,"y":203}},{"action":"release"}]}
[debug] [W3C (31d3f8af)] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":187.5,"y":406}},{"action":"wait","options":80},{"action":"moveTo","options":{"x":187.5,"y":203}},{"action":"release"}],"31d3f8af-80e2-43eb-95f8-7874063cbfdb"]
[debug] [XCUITest] Executing command 'performTouch'
[debug] [XCUITest] Received the following touch action: press(options={"x":187.5,"y":406})-wait(options=80)-moveTo(options={"x":187.5,"y":203})-release
[debug] [WD Proxy] Proxying [POST /wda/touch/perform] to [POST http://127.0.0.1:8100/session/A790C2AC-233A-4BB5-937A-53CA817AD1E6/wda/touch/perform] with body: {"actions":[{"action":"press","options":{"x":187.5,"y":406}},{"action":"wait","options":80},{"action":"moveTo","options":{"x":187.5,"y":203}},{"action":"release"}]}
[WD Proxy] Got response with status 500: {"value":{"error":"unknown error","message":"-[__NSCFNumber objectForKey:]: unrecognized selector sent to instance 0xa0e6dfbba2730310","traceback":"(\n\t0   CoreFoundation                      0x00007fff23baa1ee __exceptionPreprocess + 350\n\t1   libobjc.A.dylib                     0x00007fff50864b20 objc_exception_throw + 48\n\t2   CoreFoundation                      0x00007fff23bcb154 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132\n\t3   CoreFoundation                      0x00007fff23baef6c ___forwarding___ + 1436\n\t4   CoreFoundation                      0x00007fff23bb10f8 _CF_forwarding_prep_0 + 120\n\t5   WebDriverAgentLib                   0x000000010c17b52b -[FBWaitItem durationWithOptions:] + 91\n\t6   WebDriverAgentLib                   0x000000010c179784 -[FBAppiumGestureItem initWithActionItem:application:atPosition:offset:error:] + 708\n\t7   WebDriverAgentLib                   0x000000010c17cb31 -[FBAppiumActionsSynthesizer eventPathsWithAction:error:] + 2129\n\t8   WebDriverAgentLib ...
[debug] [W3C] Matched W3C error code 'unknown error' to UnknownError
[debug] [W3C (31d3f8af)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: -[__NSCFNumber objectForKey:]: unrecognized selector sent to instance 0xa0e6dfbba2730310
[debug] [W3C (31d3f8af)]     at errorFromW3CJsonCode (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:780:25)
[debug] [W3C (31d3f8af)]     at ProxyRequestError.getActualError (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:663:14)
[debug] [W3C (31d3f8af)]     at JWProxy.command (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:264:19)
```

**Comment by mykola-mokhnach** [comment]
> {"action":"wait","options":80}

The error is expected, because the incorrect options are sent to `wait`. Also, on iOS the delay should be 600ms or more to be recognized as long press

**Comment by George-BC** [comment]
Oh wow, thats all it was. This a big help, much appreciated!
