### ISSUE TITLE
Unable to connect to a device with the below mentioned error. I am using UiAutomator2 and the android version in the device is 7.

### ISSUE THREAD

**Issue by DebojeetB** [appium/appium#14318]
[RemoteTestNG] detected TestNG version 7.0.0
FAILED: automateAmazonMusic
org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 21575ms.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 21575ms.
    at getResponseForW3CError (C:\Users\RDRL\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\RDRL\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:392:37)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
System info: host: 'LAPTOP-72VUACFQ', ip: '192.168.1.12', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_211'
Driver info: driver.version: AndroidDriver
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:208)
	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:217)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:84)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:94)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:95)
	at app_Info.AmazonMusic.Capabilities(AmazonMusic.java:22)
	at testApplications.TC_AmazonMusic.automateAmazonMusic(TC_AmazonMusic.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(Unknown Source)
	at org.testng.TestRunner.privateRun(TestRunner.java:770)
	at org.testng.TestRunner.run(TestRunner.java:591)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
	at org.testng.SuiteRunner.run(SuiteRunner.java:304)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
	at org.testng.TestNG.runSuites(TestNG.java:1032)
	at org.testng.TestNG.run(TestNG.java:1000)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:186)
	... 42 more
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 21575ms.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
System info: host: 'LAPTOP-72VUACFQ', ip: '192.168.1.12', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_211'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 21575ms.
    at getResponseForW3CError (C:\Users\RDRL\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\RDRL\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:392:37)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	... 47 more

===============================================
    Default test
    Tests run: 1, Failures: 1, Skips: 0
===============================================

===============================================
Default suite
Total tests run: 1, Passes: 0, Failures: 1, Skips: 0
===============================================

**Comment by shibupanda** [comment]
@DebojeetB 
Console error logs is not sufficient. Please fill the complete form while raising issue with uploaded Appium Logs using gist.

**Comment by DebojeetB** [comment]
Below is the Appium logs. Anything else that is required? Please let me know

C:\Users\RDRL>appium
[Appium] Welcome to Appium v1.17.1
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"appActivity":"com.amazon.mp3.activity.MusicHomeActivity","appPackage":"com.amazon.mp3","automationName":"UiAutomator2","platformName":"Android","deviceName":"Device"},"capabilities":{"firstMatch":[{"appium:appActivity":"com.amazon.mp3.activity.MusicHomeActivity","appium:appPackage":"com.amazon.mp3","appium:automationName":"UiAutomator2","appium:deviceName":"IPSetTopBox","platformName":"android"}]}}
[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"appActivity":"com.amazon.mp3.activity.MusicHomeActivity","appPackage":"com.amazon.mp3","automationName":"UiAutomator2","platformName":"Android","deviceName":"IPSetTopBox"},null,{"firstMatch":[{"appium:appActivity":"com.amazon.mp3.activity.MusicHomeActivity","appium:appPackage":"com.amazon.mp3","appium:automationName":"UiAutomator2","appium:deviceName":"IPSetTopBox","platformName":"android"}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1589172294115 (10:14:54 GMT+0530 (India Standard Time))
[Appium] Appium v1.17.1 creating new AndroidUiautomator2Driver (v1.44.2) session
[debug] [BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {
[debug] [BaseDriver]   "alwaysMatch": {
[debug] [BaseDriver]     "platformName": "android",
[debug] [BaseDriver]     "appium:appActivity": "com.amazon.mp3.activity.MusicHomeActivity",
[debug] [BaseDriver]     "appium:appPackage": "com.amazon.mp3",
[debug] [BaseDriver]     "appium:automationName": "UiAutomator2",
[debug] [BaseDriver]     "appium:deviceName": "IPSetTopBox"
[debug] [BaseDriver]   },
[debug] [BaseDriver]   "firstMatch": [
[debug] [BaseDriver]     {}
[debug] [BaseDriver]   ]
[debug] [BaseDriver] }
[BaseDriver] Session created with session id: 10cfcfb0-197c-4d27-ab7d-c20fb5641883
[UiAutomator2] Starting 'com.amazon.mp3' directly on the device
[ADB] Found 2 'build-tools' folders under 'C:\Users\RDRL\AppData\Local\Android\Sdk' (newest first):
[ADB]     C:/Users/RDRL/AppData/Local/Android/Sdk/build-tools/30.0.0-rc3
[ADB]     C:/Users/RDRL/AppData/Local/Android/Sdk/build-tools/29.0.1
[ADB] Using 'adb.exe' from 'C:\Users\RDRL\AppData\Local\Android\Sdk\platform-tools\adb.exe'
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...
[debug] [ADB] No connected devices have been detected
[debug] [ADB] Could not find devices, restarting adb server...
[debug] [ADB] Restarting adb
[debug] [ADB] Killing adb server on port '5037'
[debug] [ADB] Running 'C:\Users\RDRL\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 kill-server'
[debug] [ADB] Getting connected devices...
[debug] [ADB] No connected devices have been detected
[debug] [ADB] Could not find devices, restarting adb server...
[debug] [ADB] Restarting adb
[debug] [ADB] Killing adb server on port '5037'
[debug] [ADB] Running 'C:\Users\RDRL\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 kill-server'
[debug] [ADB] Getting connected devices...
[debug] [ADB] No connected devices have been detected
[debug] [ADB] Could not find devices, restarting adb server...
[debug] [ADB] Restarting adb
[debug] [ADB] Killing adb server on port '5037'
[debug] [ADB] Running 'C:\Users\RDRL\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 kill-server'
[debug] [ADB] Getting connected devices...
[debug] [ADB] No connected devices have been detected
[debug] [ADB] Could not find devices, restarting adb server...
[debug] [ADB] Restarting adb
[debug] [ADB] Killing adb server on port '5037'
[debug] [ADB] Running 'C:\Users\RDRL\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 kill-server'
[debug] [ADB] Getting connected devices...
[debug] [ADB] No connected devices have been detected
[debug] [ADB] Could not find devices, restarting adb server...
[debug] [ADB] Restarting adb
[debug] [ADB] Killing adb server on port '5037'
[debug] [ADB] Running 'C:\Users\RDRL\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 kill-server'
[debug] [ADB] Getting connected devices...
[debug] [ADB] No connected devices have been detected
[debug] [ADB] Could not find devices, restarting adb server...
[debug] [ADB] Restarting adb
[debug] [ADB] Killing adb server on port '5037'
[debug] [ADB] Running 'C:\Users\RDRL\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 kill-server'
[debug] [ADB] Getting connected devices...
[debug] [ADB] No connected devices have been detected
[debug] [ADB] Could not find devices, restarting adb server...
[debug] [ADB] Restarting adb
[debug] [ADB] Killing adb server on port '5037'
[debug] [ADB] Running 'C:\Users\RDRL\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 kill-server'
[debug] [ADB] Getting connected devices...
[debug] [ADB] No connected devices have been detected
[debug] [ADB] Could not find devices, restarting adb server...
[debug] [ADB] Restarting adb
[debug] [ADB] Killing adb server on port '5037'
[debug] [ADB] Running 'C:\Users\RDRL\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 kill-server'
[debug] [ADB] Getting connected devices...
[debug] [ADB] No connected devices have been detected
[debug] [ADB] Could not find devices, restarting adb server...
[debug] [ADB] Restarting adb
[debug] [ADB] Killing adb server on port '5037'
[debug] [ADB] Running 'C:\Users\RDRL\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 kill-server'
[debug] [ADB] Getting connected devices...
[debug] [ADB] No connected devices have been detected
[debug] [ADB] Could not find devices, restarting adb server...
[debug] [ADB] Restarting adb
[debug] [ADB] Killing adb server on port '5037'
[debug] [ADB] Running 'C:\Users\RDRL\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 kill-server'
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1589172318470 (10:15:18 GMT+0530 (India Standard Time))
[debug] [W3C] Encountered internal error running command: Error: Could not find a connected Android device in 21575ms.
[debug] [W3C]     at getDevices (C:\Users\RDRL\AppData\Roaming\npm\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:211:13)
[debug] [W3C]     at getDevices (C:\Users\RDRL\AppData\Roaming\npm\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:224:18)
[debug] [W3C]     at getDevices (C:\Users\RDRL\AppData\Roaming\npm\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:224:12)
[debug] [W3C]     at getDevices (C:\Users\RDRL\AppData\Roaming\npm\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:224:12)
[debug] [W3C]     at getDevices (C:\Users\RDRL\AppData\Roaming\npm\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:224:12)
[debug] [W3C]     at getDevices (C:\Users\RDRL\AppData\Roaming\npm\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:224:12)
[debug] [W3C]     at getDevices (C:\Users\RDRL\AppData\Roaming\npm\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:224:12)
[debug] [W3C]     at getDevices (C:\Users\RDRL\AppData\Roaming\npm\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:224:12)
[debug] [W3C]     at getDevices (C:\Users\RDRL\AppData\Roaming\npm\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:224:12)
[debug] [W3C]     at getDevices (C:\Users\RDRL\AppData\Roaming\npm\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:224:12)
[debug] [W3C]     at getDevices (C:\Users\RDRL\AppData\Roaming\npm\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:224:12)
[debug] [W3C]     at ADB.getDevicesWithRetry (C:\Users\RDRL\AppData\Roaming\npm\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:226:10)
[debug] [W3C]     at Object.getDeviceInfoFromCaps (C:\Users\RDRL\AppData\Roaming\npm\node_modules\appium\node_modules\appium-android-driver\lib\android-helpers.js:180:19)
[debug] [W3C]     at AndroidUiautomator2Driver.startUiAutomator2Session (C:\Users\RDRL\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\driver.js:290:26)
[debug] [W3C]     at AndroidUiautomator2Driver.createSession (C:\Users\RDRL\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\driver.js:212:7)
[debug] [W3C]     at AppiumDriver.createSession (C:\Users\RDRL\AppData\Roaming\npm\node_modules\appium\lib\appium.js:358:35)
[debug] [W3C] Destroying socket connection
[HTTP] <-- POST /wd/hub/session 500 24510 ms - 665
[HTTP]

**Comment by shibupanda** [comment]
@DebojeetB 
>[debug] [ADB] No connected devices have been detected

Device is not detected in adb. Check "adb devices" command whether device id is populating or not. It should not be unauthorised and offline.

**Comment by DebojeetB** [comment]
I checked using CMD and it showed as connected. It shows as connected before I try to execute my code and once after I run the code from Eclipse, the device automatically gets disconnected.

**Comment by shibupanda** [comment]
Nothing to be done in Appium Server side. Please check the usb connection.

**Comment by DebojeetB** [comment]
The connection seems to be okay as when I try to launch an app via CMD, it works fine. It is only causing an error when I am trying to launch it via Eclipse.

I am using Appium 1.17 and the android version is 7. Does that impact anyhow?

**Comment by mykola-mokhnach** [comment]
> [ADB] C:/Users/RDRL/AppData/Local/Android/Sdk/build-tools/30.0.0-rc3

These build tools require Java9+. Also, make sure the environment of the Appium process being executed from Eclipse is the same as the env of the process executed manually. Read https://github.com/appium/java-client/blob/master/docs/environment.md for more details.

**Comment by DebojeetB** [comment]
I installed 25.0.3 and tried executing but that also gave the same error. The same piece of code works fine on an emulator. 
Is it anyhow related to the Android version that I have in my device?

**Comment by mykola-mokhnach** [comment]
No, this should be related to the used adb executable and the process environment if manual execution shows the devices list

**Comment by mykola-mokhnach** [comment]
There is nothing here that could be done from Appium side
Closed as third party issue.
