### ISSUE TITLE
Getting "Encountered internal error running command: Error: end of central directory record signature not found"

### ISSUE THREAD

**Issue by krinaparmar** [appium/appium#14330]
Hello guys I am new to Appium and while running my every first program I am facing this issue.
variable defined:

```

ANDROID_HOME  C:\Users\admin\AppData\Local\Android\Sdk

JAVA_HOME C:\Program Files\Java\jdk1.8.0_221

paths:

C:\Users\admin\AppData\Local\Android\Sdk\tools\bin

C:\Users\admin\AppData\Local\Android\Sdk\tools

C:\Users\admin\AppData\Local\Android\Sdk\platform-tools



```
below are appium logs

   ```
 [Appium] Welcome to Appium v1.17.0
    [Appium] Non-default server args:
    [Appium] allowInsecure: {
    [Appium] }
    [Appium] denyInsecure: {
    [Appium] }
    [Appium] Appium REST http interface listener started on 0.0.0.0:4723
    [HTTP] --> POST /wd/hub/session
    [HTTP] {"desiredCapabilities":{"app":"https://github.com/appium/appium/blob/master/sample-code/apps/ApiDemos-debug.apk","automationName":"UiAutomator2","platformName":"Android","deviceName":"krinapixelxl8"},"capabilities":{"firstMatch":[{"appium:app":"https://github.com/appium/appium/blob/master/sample-code/apps/ApiDemos-debug.apk","appium:automationName":"UiAutomator2","appium:deviceName":"krinapixelxl8","platformName":"android"}]}}
    [W3C] Calling AppiumDriver.createSession() with args: [{"app":"https://github.com/appium/appium/blob/master/sample-code/apps/ApiDemos-debug.apk","automationName":"UiAutomator2","platformName":"Android","deviceName":"krinapixelxl8"},null,{"firstMatch":[{"appium:app":"https://github.com/appium/appium/blob/master/sample-code/apps/ApiDemos-debug.apk","appium:automationName":"UiAutomator2","appium:deviceName":"krinapixelxl8","platformName":"android"}]}]
    [BaseDriver] Event 'newSessionRequested' logged at 1589296546704 (20:45:46 GMT+0530 (India Standard Time))
    [Appium] Appium v1.17.0 creating new AndroidUiautomator2Driver (v1.44.2) session
    [BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
    [BaseDriver] Creating session with W3C capabilities: {
    [BaseDriver] "alwaysMatch": {
    [BaseDriver] "platformName": "android",
    [BaseDriver] "appium:app": "https://github.com/appium/appium/blob/master/sample-code/apps/ApiDemos-debug.apk",
    [BaseDriver] "appium:automationName": "UiAutomator2",
    [BaseDriver] "appium:deviceName": "krinapixelxl8"
    [BaseDriver] },
    [BaseDriver] "firstMatch": [
    [BaseDriver] {}
    [BaseDriver] ]
    [BaseDriver] }
    [BaseDriver] Session created with session id: 5a725ec3-daa8-4e78-982d-d2e80de7183c
    [BaseDriver] Using downloadable app 'https://github.com/appium/appium/blob/master/sample-code/apps/ApiDemos-debug.apk'
    [BaseDriver] Content-Type: text/html; charset=utf-8
    [BaseDriver] 'https://github.com/appium/appium/blob/master/sample-code/apps/ApiDemos-debug.apk' (68.66 KB) has been downloaded to 'C:\Users\admin\AppData\Local\Temp\2020412-2456-f9fy5h.x45fe\ApiDemos-debug.apk' in 0.701s
    [UiAutomator2] Checking whether app is actually present
    [ADB] Using 'adb.exe' from 'C:\Users\admin\AppData\Local\Android\Sdk\platform-tools\adb.exe'
    [AndroidDriver] Retrieving device list
    [ADB] Trying to find a connected android device
    [ADB] Getting connected devices...
    [ADB] Connected devices: [{"udid":"emulator-5554","state":"device"}]
    [AndroidDriver] Using device: emulator-5554
    [ADB] Using 'adb.exe' from 'C:\Users\admin\AppData\Local\Android\Sdk\platform-tools\adb.exe'
    [ADB] Setting device id to emulator-5554
    [ADB] Running 'C:\Users\admin\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.sdk'
    [ADB] Current device property 'ro.build.version.sdk': 27
    [ADB] Device API level: 27
    [AndroidDriver] Parsing package and activity from app manifest
    [UiAutomator2] Deleting UiAutomator2 session
    [BaseDriver] Event 'newSessionStarted' logged at 1589296562809 (20:46:02 GMT+0530 (India Standard Time))
    [W3C] Encountered internal error running command: Error: end of central directory record signature not found
    [W3C] at C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\yauzl\index.js:187:14
    [W3C] at C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\yauzl\index.js:631:5
    [W3C] at C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\fd-slicer\index.js:32:7
    [W3C] at FSReqCallback.wrapper [as oncomplete] (fs.js:477:5)
    [W3C] Destroying socket connection
    [HTTP] <-- POST /wd/hub/session 500 16108 ms - 667
    [HTTP]
```

These are eclipse logs
```

    [RemoteTestNG] detected TestNG version 7.0.0
    FAILED: capabilities
    org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: end of central directory record signature not found
    Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
    System info: host: 'LAPTOP-IAPOTV4F', ip: '192.168.43.58', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_221'
    Driver info: driver.version: AndroidDriver
    remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: end of central directory record signature not found
        at getResponseForW3CError (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
        at asyncHandler (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:392:37)
    Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
    System info: host: 'LAPTOP-IAPOTV4F', ip: '192.168.43.58', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_221'
    Driver info: driver.version: AndroidDriver
    	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:208)
    	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:217)
    	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
    	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
    	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
    	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
    	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
    	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
    	at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:336)
    	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
    	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:37)
    	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:88)
    	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:98)
    	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:94)
    	at base.base.capabilities(base.java:34)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    	at java.lang.reflect.Method.invoke(Unknown Source)
    	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
    	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
    	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
    	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
    	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
    	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
    	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
    	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
    	at java.util.ArrayList.forEach(Unknown Source)
    	at org.testng.TestRunner.privateRun(TestRunner.java:770)
    	at org.testng.TestRunner.run(TestRunner.java:591)
    	at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
    	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
    	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
    	at org.testng.SuiteRunner.run(SuiteRunner.java:304)
    	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
    	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
    	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
    	at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
    	at org.testng.TestNG.runSuites(TestNG.java:1032)
    	at org.testng.TestNG.run(TestNG.java:1000)
    	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
    	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
    	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
    Caused by: java.lang.reflect.InvocationTargetException
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    	at java.lang.reflect.Method.invoke(Unknown Source)
    	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:186)
    	... 42 more
    Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: end of central directory record signature not found
    Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
    System info: host: 'LAPTOP-IAPOTV4F', ip: '192.168.43.58', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_221'
    Driver info: driver.version: AndroidDriver
    remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: end of central directory record signature not found
        at getResponseForW3CError (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
        at asyncHandler (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:392:37)
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    	at java.lang.reflect.Constructor.newInstance(Unknown Source)
    	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
    	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
    	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
    	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
    	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
    	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
    	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
    	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
    	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
    	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
    	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
    	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
    	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
    	... 47 more
     
     
    ===============================================
        Default test
        Tests run: 1, Failures: 1, Skips: 0
    ===============================================
     
     
    ===============================================
    Default suite
    Total tests run: 1, Passes: 0, Failures: 1, Skips: 0
    ===============================================

```
Eclipse code:

> 
>     package base;
>      
>     import java.io.File;
>     import java.net.MalformedURLException;
>     import java.net.URL;
>      
>     import org.openqa.selenium.remote.DesiredCapabilities;
>     import org.testng.annotations.Test;
>      
>     import io.appium.java_client.android.AndroidDriver;
>     import io.appium.java_client.android.AndroidElement;
>     import io.appium.java_client.remote.MobileCapabilityType;
>      
>     public class base {
>     	
>      
>     @Test
>     	public void capabilities() throws MalformedURLException{
>     	
>      
>     	AndroidDriver driver;
>      
>     	// TODO Auto-generated method stub
>     	File appDir = new File("resources");
>     	     File app = new File(appDir, "ApiDemos-debug.apk");
>     	     DesiredCapabilities capabilities = new DesiredCapabilities();
>     	   
>     	     capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "krinapixelxl8");
>     	     capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "Android");
>     	     capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "8.1.0");
>     	     capabilities.setCapability(MobileCapabilityType.APP, "https://github.com/appium/appium/blob/master/sample-code/apps/ApiDemos-debug.apk");
>     	     capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "UiAutomator2");
>     	    driver = new AndroidDriver(new URL("http://192.168.43.58:4723/wd/hub"), capabilities);
>     	   
>     	  
>     	}
>     }
>      
> 

Below is the emulator run
![2020-05-12_20h53_15](https://user-images.githubusercontent.com/65011387/81722153-9c861d00-949e-11ea-9794-176368da70d5.png)

I have tried to reinstall Appium too as i was assuming it as a config issue.

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium/blob/master/sample-code/apps/ApiDemos-debug.apk

Returns a web page, not the app binary itself. Make sure you provide a correct app to your script.
