### ISSUE TITLE
Error: No valid exports main found for '/usr/local/lib/node_modules/appium-doctor/node_modules/uuid'

### ISSUE THREAD

**Issue by mgmpskywalker07** [appium/appium#14363]
## The problem

I've simply installed appium-doctor using 

**npm install appium-doctor -g**

When I try to run it, I immediately get an error.

## Environment

* Appium version (or git revision) that exhibits the issue: v1.15.1 (server)
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOS Mojave 10.14.6
* Node.js version (unless using Appium.app|exe): v13.3.0
* Npm or Yarn package manager: Npm
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

$ **npm install appium-doctor -g**
npm WARN deprecated authorize-ios@1.2.1: Moved into appium
/usr/local/bin/appium-doctor -> /usr/local/lib/node_modules/appium-doctor/appium-doctor.js

> core-js@3.6.5 postinstall /usr/local/lib/node_modules/appium-doctor/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

appium-doctor@1.15.1
added 263 packages from 239 contributors in 8.774s

$ **appium-doctor**
Error: No valid exports main found for '/usr/local/lib/node_modules/appium-doctor/node_modules/uuid'
    at resolveExportsTarget (internal/modules/cjs/loader.js:618:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:650:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:948:27)
    at Function.Module._load (internal/modules/cjs/loader.js:854:27)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/appium-doctor/node_modules/appium-support/lib/util.js:15:1)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:983:32)
    at Function.Module._load (internal/modules/cjs/loader.js:891:14)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/appium-doctor/node_modules/appium-support/lib/fs.js:12:1)

**Comment by mgmpskywalker07** [comment]
Need to update node.js to v14.3
