### ISSUE TITLE
An element command failed because the referenced element is no longer attached to the DOM

### ISSUE THREAD

**Issue by yaqiz16** [appium/appium#14399]
## The problem

I'm using the BDD structure to test the implementation. I'm running my tests at Jenkins.

"weekly discover list": "(//XCUIElementTypeCell[@name=\"FizyListForYouCellIdentifier\"]/XCUIElementTypeStaticText[@name='fizy_collection_info' and @value='Haftalık Keşif Listesi'])",

The above mentioned .JSON file registered in the element loglardaki get the error.The same error is received in different element definitions and the same Appium log appears.

## Environment

* Appium version (or git revision) that exhibits the issue: v1.16.0
* Desktop OS/version used to run Appium: Linux Ubuntu 18.04.3 LTS
* Node.js version (unless using Appium.app|exe):12.14.0
* Real device or emulator/simulator: iOS 12.4.1

## Details

An element command failed because the referenced element is no longer attached to the DOM
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'labsrv012', ip: '10.254.186.12', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-65-generic', java.version: '1.8.0_252'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities {automationName: XCuiTest, browserName: , bundleId: com.turkcell.gncplay, databaseEnabled: false, deviceName: IPHONE_6S, javascriptEnabled: true, locationContextEnabled: false, mjpegServerPort: 9197, networkConnectionEnabled: false, newCommandTimeout: 0, noReset: true, platform: MAC, platformName: iOS, platformVersion: 12.2.0, server:CONFIG_UUID: f41b81c7-bce7-4152-8ff3-190..., takesScreenshot: true, udid: 123456789, usePrebuiltWDA: true, wdaLaunchTimeout: 120000, wdaLocalPort: 8125, wdaStartupRetries: 3, webStorageEnabled: false}
Session ID: 09ba6477-ca60-4a1e-8590-21902ba0ae95

## Appium logs : 

**https://dosya.co/rhgck7eq2oo5/device_bf444c31592e637f5403af4492501b7f6da19138.log.html**

2020-06-01 10:05:26:732 [HTTP] --> GET /wd/hub/status
2020-06-01 10:05:26:732 [HTTP] {}
2020-06-01 10:05:26:732 [GENERIC] Calling AppiumDriver.getStatus() with args: []
2020-06-01 10:05:26:732 [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.16.0"}}
2020-06-01 10:05:26:733 [HTTP] <-- GET /wd/hub/status 200 1 ms - 68
2020-06-01 10:05:26:733 [HTTP] 
2020-06-01 10:05:26:881 [Xcode]     t = 331568.95s     Find: Children matching type Window
2020-06-01 10:05:26:882 [Xcode] 
2020-06-01 10:05:26:884 [Xcode]     t = 331568.96s     Find: Elements matching predicate 'wdUID IN {"05000000-0000-0000-9632-000000000000", "3D010000-0000-0000-9632-000000000000", "06000000-0000-0000-9632-000000000000"}'
2020-06-01 10:05:26:884 [Xcode] 
2020-06-01 10:05:26:890 [Xcode]     t = 331568.96s     Find: Identity Binding
2020-06-01 10:05:26:890 [Xcode] 
2020-06-01 10:05:26:960 [Xcode]     t = 331569.04s Checking existence of `StaticText`
2020-06-01 10:05:26:960 [Xcode] 
2020-06-01 10:05:26:964 [Xcode]     t = 331569.04s     Requesting snapshot of accessibility hierarchy for app with pid 12950
2020-06-01 10:05:26:964 [Xcode] 
2020-06-01 10:05:27:209 [Xcode]     t = 331569.28s     Find: Descendants matching type StaticText
2020-06-01 10:05:27:209 [Xcode] 
2020-06-01 10:05:27:214 [Xcode]     t = 331569.29s     Find: Elements matching predicate 'wdUID IN {"5F000000-0000-0000-9632-000000000000"}'
2020-06-01 10:05:27:214 [Xcode] 
2020-06-01 10:05:27:223 [Xcode]     t = 331569.30s Get all elements bound by accessibility element for: Elements matching predicate 'wdUID IN {"5F000000-0000-0000-9632-000000000000"}'
2020-06-01 10:05:27:223 [Xcode] 
2020-06-01 10:05:27:235 [Xcode]     t = 331569.30s     Requesting snapshot of accessibility hierarchy for app with pid 12950
2020-06-01 10:05:27:235 [Xcode] 
2020-06-01 10:05:27:497 [Xcode]     t = 331569.57s     Find: Descendants matching type StaticText
2020-06-01 10:05:27:498 [Xcode] 
2020-06-01 10:05:27:503 [Xcode]     t = 331569.58s     Find: Elements matching predicate 'wdUID IN {"5F000000-0000-0000-9632-000000000000"}'
2020-06-01 10:05:27:504 [Xcode] 
2020-06-01 10:05:27:541 [Xcode]     t = 331569.62s Checking existence of `"fizy_collection_info" StaticText`
2020-06-01 10:05:27:541 [Xcode] 
2020-06-01 10:05:27:546 [Xcode]     t = 331569.62s     Requesting snapshot of accessibility hierarchy for app with pid 12950
2020-06-01 10:05:27:546 [Xcode] 
2020-06-01 10:05:27:780 [Xcode]     t = 331569.85s     Find: Descendants matching type StaticText
2020-06-01 10:05:27:780 [Xcode] 
2020-06-01 10:05:27:782 [Xcode]     t = 331569.86s     Find: Elements matching predicate 'wdUID IN {"5F000000-0000-0000-9632-000000000000"}'
2020-06-01 10:05:27:782 [Xcode] 
2020-06-01 10:05:27:787 [Xcode]     t = 331569.86s     Find: Identity Binding
2020-06-01 10:05:27:787 [Xcode] 
2020-06-01 10:05:27:802 [Xcode]     t = 331569.87s Requesting snapshot of accessibility hierarchy for app with pid 12950
2020-06-01 10:05:27:802 [Xcode] 
2020-06-01 10:05:27:805 [Xcode]     t = 331569.88s     Using snapshot previously cached by query
2020-06-01 10:05:27:805 [Xcode] 
2020-06-01 10:05:27:812 [Xcode]     t = 331569.88s Find: Descendants matching type StaticText
2020-06-01 10:05:27:812 [Xcode] 
2020-06-01 10:05:27:818 [Xcode]     t = 331569.89s Find: Elements matching predicate 'wdUID IN {"5F000000-0000-0000-9632-000000000000"}'
2020-06-01 10:05:27:818 [Xcode] 
2020-06-01 10:05:27:825 [Xcode]     t = 331569.90s Find: Identity Binding
2020-06-01 10:05:27:825 [Xcode] 
2020-06-01 10:05:27:835 [WD Proxy] Got response with status 200: {"value":[{"ELEMENT":"5F000000-0000-0000-9632-000000000000","element-6066-11e4-a52e-4f735466cecf":"5F000000-0000-0000-9632-000000000000"}],"sessionId":"EEB405C2-AC85-42D0-A2E5-2E5E5C8C3917"}
2020-06-01 10:05:27:836 [W3C (09ba6477)] Responding to client with driver.findElements() result: [{"element-6066-11e4-a52e-4f735466cecf":"5F000000-0000-0000-9632-000000000000","ELEMENT":"5F000000-0000-0000-9632-000000000000"}]
2020-06-01 10:05:27:836 [HTTP] <-- POST /wd/hub/session/09ba6477-ca60-4a1e-8590-21902ba0ae95/elements 200 3364 ms - 139
2020-06-01 10:05:27:836 [HTTP] 
2020-06-01 10:05:28:012 [HTTP] --> GET /wd/hub/session/09ba6477-ca60-4a1e-8590-21902ba0ae95/element/5F000000-0000-0000-9632-000000000000/displayed
2020-06-01 10:05:28:012 [HTTP] {}
2020-06-01 10:05:28:012 [W3C (09ba6477)] Driver proxy active, passing request on via HTTP proxy
2020-06-01 10:05:28:012 [XCUITest] Executing command 'proxyReqRes'
2020-06-01 10:05:28:013 [WD Proxy] Matched '/wd/hub/session/09ba6477-ca60-4a1e-8590-21902ba0ae95/element/5F000000-0000-0000-9632-000000000000/displayed' to command name 'elementDisplayed'
2020-06-01 10:05:28:013 [WD Proxy] Proxying [GET /wd/hub/session/09ba6477-ca60-4a1e-8590-21902ba0ae95/element/5F000000-0000-0000-9632-000000000000/displayed] to [GET http://localhost:8125/session/EEB405C2-AC85-42D0-A2E5-2E5E5C8C3917/element/5F000000-0000-0000-9632-000000000000/displayed] with body: {}
2020-06-01 10:05:28:018 [WD Proxy] Got response with status 404: {
2020-06-01 10:05:28:018 [WD Proxy]   "value" : {
2020-06-01 10:05:28:018 [WD Proxy]     "error" : "stale element reference",
2020-06-01 10:05:28:018 [WD Proxy]     "message" : "An element command failed because the referenced element is no longer attached to the DOM",
2020-06-01 10:05:28:018 [WD Proxy]     "traceback" : ""
2020-06-01 10:05:28:018 [WD Proxy]   },
2020-06-01 10:05:28:018 [WD Proxy]   "sessionId" : "EEB405C2-AC85-42D0-A2E5-2E5E5C8C3917"
2020-06-01 10:05:28:018 [WD Proxy] }
2020-06-01 10:05:28:019 [W3C (09ba6477)] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: 404 - "{\n  \"value\" : {\n    \"error\" : \"stale element reference\",\n    \"message\" : \"An element command failed because the referenced element is no longer attached to the DOM\",\n    \"traceback\" : \"\"\n  },\n  \"sessionId\" : \"EEB405C2-AC85-42D0-A2E5-2E5E5C8C3917\"\n}"
2020-06-01 10:05:28:019 [W3C (09ba6477)]     at JWProxy.proxy (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:222:13)
2020-06-01 10:05:28:019 [W3C] Matched W3C error code 'stale element reference' to StaleElementReferenceError
2020-06-01 10:05:28:020 [HTTP] <-- GET /wd/hub/session/09ba6477-ca60-4a1e-8590-21902ba0ae95/element/5F000000-0000-0000-9632-000000000000/displayed 404 8 ms - 670
2020-06-01 10:05:28:020 [HTTP] 
2020-06-01 10:05:28:221 [HTTP] --> POST /wd/hub/session/09ba6477-ca60-4a1e-8590-21902ba0ae95/element/5F000000-0000-0000-9632-000000000000/click
2020-06-01 10:05:28:221 [HTTP] {"id":"5F000000-0000-0000-9632-000000000000"}
2020-06-01 10:05:28:222 [W3C (09ba6477)] Driver proxy active, passing request on via HTTP proxy
2020-06-01 10:05:28:222 [XCUITest] Executing command 'proxyReqRes'
2020-06-01 10:05:28:222 [WD Proxy] Matched '/wd/hub/session/09ba6477-ca60-4a1e-8590-21902ba0ae95/element/5F000000-0000-0000-9632-000000000000/click' to command name 'click'
2020-06-01 10:05:28:222 [WD Proxy] Proxying [POST /wd/hub/session/09ba6477-ca60-4a1e-8590-21902ba0ae95/element/5F000000-0000-0000-9632-000000000000/click] to [POST http://localhost:8125/session/EEB405C2-AC85-42D0-A2E5-2E5E5C8C3917/element/5F000000-0000-0000-9632-000000000000/click] with body: {"id":"5F000000-0000-0000-9632-000000000000"}
2020-06-01 10:05:28:227 [WD Proxy] Got an unexpected response with status 404: {"value":{"error":"stale element reference","message":"An element command failed because the referenced element is no longer attached to the DOM","traceback":""},"sessionId":"EEB405C2-AC85-42D0-A2E5-2E5E5C8C3917"}
2020-06-01 10:05:28:228 [W3C (09ba6477)] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: 404 - {"value":{"error":"stale element reference","message":"An element command failed because the referenced element is no longer attached to the DOM","traceback":""},"sessionId":"EEB405C2-AC85-42D0-A2E5-2E5E5C8C3917"}
2020-06-01 10:05:28:228 [W3C (09ba6477)]     at JWProxy.proxy (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:222:13)
2020-06-01 10:05:28:228 [W3C] Matched W3C error code 'stale element reference' to StaleElementReferenceError
2020-06-01 10:05:28:229 [HTTP] <-- POST /wd/hub/session/09ba6477-ca60-4a1e-8590-21902ba0ae95/element/5F000000-0000-0000-9632-000000000000/click 404 7 ms - 670
2020-06-01 10:05:28:229 [HTTP] 
2020-06-01 10:05:28:403 [HTTP] --> GET /wd/hub/session/09ba6477-ca60-4a1e-8590-21902ba0ae95/screenshot
2020-06-01 10:05:28:403 [HTTP] {}
2020-06-01 10:05:28:403 [W3C (09ba6477)] Calling AppiumDriver.getScreenshot() with args: ["09ba6477-ca60-4a1e-8590-21902ba0ae95"]
2020-06-01 10:05:28:403 [XCUITest] Executing command 'getScreenshot'
2020-06-01 10:05:28:403 [XCUITest] Taking screenshot with WDA
2020-06-01 10:05:28:404 [WD Proxy] Matched '/screenshot' to command name 'getScreenshot'

**Comment by mykola-mokhnach** [comment]
Please upgrade the server to the most recent version and try again

**Comment by yaqiz16** [comment]
> v

The system we use supports these versions, what is the main source of the problem?

**Comment by KazuCocoa** [comment]
The server returned below message. Perhaps it could not detect the visibility.
Not sure, but `simpleIsVisibleCheck` capability or newer Appium version help.

```
52-eb24456bfb91/elements 200 1393 ms - 139
2020-05-30 18:30:47:495 [HTTP] 
2020-05-30 18:30:47:664 [HTTP] --> GET /wd/hub/session/86f68aa1-a646-4318-9952-eb24456bfb91/element/64020000-0000-0000-C92F-000000000000/displayed
2020-05-30 18:30:47:664 [HTTP] {}
2020-05-30 18:30:47:664 [W3C (86f68aa1)] Driver proxy active, passing request on via HTTP proxy
2020-05-30 18:30:47:664 [XCUITest] Executing command 'proxyReqRes'
2020-05-30 18:30:47:665 [WD Proxy] Matched '/wd/hub/session/86f68aa1-a646-4318-9952-eb24456bfb91/element/64020000-0000-0000-C92F-000000000000/displayed' to command name 'elementDisplayed'
2020-05-30 18:30:47:665 [WD Proxy] Proxying [GET /wd/hub/session/86f68aa1-a646-4318-9952-eb24456bfb91/element/64020000-0000-0000-C92F-000000000000/displayed] to [GET http://localhost:8125/session/F6D333C1-E078-422C-9647-F425E87D90F5/element/64020000-0000-0000-C92F-000000000000/displayed] with body: {}
2020-05-30 18:30:47:676 [WD Proxy] Got response with status 404: {
2020-05-30 18:30:47:676 [WD Proxy]   "value" : {
2020-05-30 18:30:47:676 [WD Proxy]     "error" : "stale element reference",
2020-05-30 18:30:47:676 [WD Proxy]     "message" : "An element command failed because the referenced element is no longer attached to the DOM",
2020-05-30 18:30:47:676 [WD Proxy]     "traceback" : ""
2020-05-30 18:30:47:677 [WD Proxy]   },
2020-05-30 18:30:47:677 [WD Proxy]   "sessionId" : "F6D333C1-E078-422C-9647-F425E87D90F5"
2020-05-30 18:30:47:677 [WD Proxy] }
2020-05-30 18:30:47:677 [W3C (86f68aa1)] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: 404 - "{\n  \"value\" : {\n    \"error\" : \"stale element reference\",\n    \"message\" : \"An element command failed because the referenced element is no longer attached to the DOM\",\n    \"traceback\" : \"\"\n  },\n  \"sessionId\" : \"F6D333C1-E078-422C-9647-F425E87D90F5\"\n}"
2020-05-30 18:30:47:677 [W3C (86f68aa1)]     at JWProxy.proxy (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:222:13)
2020-05-30 18:30:47:677 [W3C] Matched W3C error code 'stale element reference' to StaleElementReferenceError
2020-05-30 18:30:47:678 [HTTP] <-- GET /wd/hub/session/86f68aa1-a646-4318-9952-eb24456bfb91/element/64020000-0000-0000-C92F-000000000000/displayed 404 14 ms - 670
2020-05-30 18:30:47:678 [HTTP] 
```

**Comment by mykola-mokhnach** [comment]
> The system we use supports these versions, what is the main source of the problem?

Unfortunately, we don't have resources to provide patches to older releases. So, if there is a bug then it must be confirmed with the most recent version first.

**Comment by mykola-mokhnach** [comment]
Closed because of no response
