### ISSUE TITLE
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8200

### ISSUE THREAD

**Issue by phemasundar** [appium/appium#14422]
## The problem
While executing the multiple automation test cases, randomly below error is coming and failing all the test cases post that.

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8200

As this is happening frequently, it is becoming very difficult to maintain the stability of automation test results.
## Environment

Windows 10
Appium 1.17.1
Mobile platform/version under test: 7.1.2
Real device
Appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

### Appium server logs:
https://gist.github.com/phemasundar/4473b07e30a9d172c08c100655ebebfb

### Logcat logs:
https://gist.github.com/phemasundar/74925ac2e19dd9a9ed9c1351ab3f9650

## Actual error from Appium server logs
[2020-06-06T15:16:45+0530] [ALL] [W3C (53f03416)] Calling AppiumDriver.findElements() with args: ["id","counts_linearlayout_adhoc_item","53f03416-208c-4ffc-938d-588743f9e4e7"]
[2020-06-06T15:16:45+0530] [ALL] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[2020-06-06T15:16:45+0530] [ALL] [BaseDriver] Waiting up to 1000 ms for condition
[2020-06-06T15:16:45+0530] [ALL] [WD Proxy] Matched '/elements' to command name 'findElements'
[2020-06-06T15:16:45+0530] [ALL] [WD Proxy] Proxying [POST /elements] to [POST http://127.0.0.1:8200/wd/hub/session/64f06652-6d53-4057-ac3c-cd1d222119ed/elements] with body: {"strategy":"id","selector":"counts_linearlayout_adhoc_item","context":"","multiple":true}
[2020-06-06T15:16:45+0530] [ALL] [WD Proxy] Got response with unknown status: {"code":"ECONNRESET"}
[2020-06-06T15:16:45+0530] [ALL] [W3C (53f03416)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up
[2020-06-06T15:16:45+0530] [ALL] [W3C (53f03416)]     at JWProxy.command (C:\AutomationTesting\Installations\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:266:13)
[2020-06-06T15:16:45+0530] [ALL] [HTTP] [37m<-- POST /wd/hub/session/53f03416-208c-4ffc-938d-588743f9e4e7/elements [39m[31m500[39m [90m52 ms - 545[39m
[2020-06-06T15:16:45+0530] [ALL] [HTTP] [90m[39m
[2020-06-06T15:16:45+0530] [ALL] [Logcat] Logcat terminated with code 0, signal null
[2020-06-06T15:16:45+0530] [ALL] [HTTP] [37m-->[39m [37mGET[39m [37m/wd/hub/session/53f03416-208c-4ffc-938d-588743f9e4e7/screenshot[39m
[2020-06-06T15:16:45+0530] [ALL] [HTTP] [90m{}[39m
[2020-06-06T15:16:45+0530] [ALL] [W3C (53f03416)] Calling AppiumDriver.getScreenshot() with args: ["53f03416-208c-4ffc-938d-588743f9e4e7"]
[2020-06-06T15:16:45+0530] [ALL] [WD Proxy] Matched '/screenshot' to command name 'getScreenshot'
[2020-06-06T15:16:45+0530] [ALL] [WD Proxy] Proxying [GET /screenshot] to [GET http://127.0.0.1:8200/wd/hub/session/64f06652-6d53-4057-ac3c-cd1d222119ed/screenshot] with no body
[2020-06-06T15:16:45+0530] [ALL] [Instrumentation] The process has exited with code 0
[2020-06-06T15:16:45+0530] [ALL] [WD Proxy] Got response with unknown status: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8200}
[2020-06-06T15:16:45+0530] [ALL] [W3C (53f03416)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8200
[2020-06-06T15:16:45+0530] [ALL] [W3C (53f03416)]     at JWProxy.command (C:\AutomationTesting\Installations\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:266:13)
[2020-06-06T15:16:45+0530] [ALL] [HTTP] [37m<-- GET /wd/hub/session/53f03416-208c-4ffc-938d-588743f9e4e7/screenshot [39m[31m500[39m [90m1015 ms - 587[39m
[2020-06-06T15:16:45+0530] [ALL] [HTTP] [90m[39m
[2020-06-06T15:16:45+0530] [ALL] [HTTP] [37m-->[39m [37mPOST[39m [37m/wd/hub/session/53f03416-208c-4ffc-938d-588743f9e4e7/appium/app/close[39m
[2020-06-06T15:16:45+0530] [ALL] [HTTP] [90m{}[39m
[2020-06-06T15:16:45+0530] [ALL] [W3C (53f03416)] Calling AppiumDriver.closeApp() with args: ["53f03416-208c-4ffc-938d-588743f9e4e7"]
[2020-06-06T15:16:45+0530] [ALL] [ADB] Running 'C:\AutomationTesting\Installations\Android\platform-tools\adb.exe -P 5037 -s 16317522504407 shell am force-stop com.tesco.pdacount'
[2020-06-06T15:16:45+0530] [ALL] [W3C (53f03416)] Encountered internal error running command: Error executing adbExec. Original error: 'Command 'C:\\AutomationTesting\\Installations\\Android\\platform-tools\\adb.exe -P 5037 -s 16317522504407 shell am force-stop com.tesco.pdacount' exited with code 1'; Stderr: 'adb.exe: device '16317522504407' not found'; Code: '1'
[2020-06-06T15:16:45+0530] [ALL] [W3C (53f03416)] Error: Command 'C:\\AutomationTesting\\Installations\\Android\\platform-tools\\adb.exe -P 5037 -s 16317522504407 shell am force-stop com.tesco.pdacount' exited with code 1
[2020-06-06T15:16:45+0530] [ALL] [W3C (53f03416)]     at ChildProcess.<anonymous> (C:\AutomationTesting\Installations\appium\node_modules\teen_process\lib\exec.js:113:19)
[2020-06-06T15:16:45+0530] [ALL] [W3C (53f03416)]     at ChildProcess.emit (events.js:310:20)
[2020-06-06T15:16:45+0530] [ALL] [W3C (53f03416)]     at maybeClose (internal/child_process.js:1021:16)
[2020-06-06T15:16:45+0530] [ALL] [W3C (53f03416)]     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
[2020-06-06T15:16:45+0530] [ALL] [HTTP] [37m<-- POST /wd/hub/session/53f03416-208c-4ffc-938d-588743f9e4e7/appium/app/close [39m[31m500[39m [90m98 ms - 1091[39m
[2020-06-06T15:16:45+0530] [ALL] [HTTP] [90m[39m
[2020-06-06T15:16:45+0530] [ALL] [HTTP] [37m-->[39m [37mPOST[39m [37m/wd/hub/session/53f03416-208c-4ffc-938d-588743f9e4e7/appium/stop_recording_screen[39m
[2020-06-06T15:16:45+0530] [ALL] [HTTP] [90m{}[39m

**Comment by KazuCocoa** [comment]
Do you have more logcat after `2020-06-06T15:16:44+0530`?
The error message in Appium side got an error around `[2020-06-06T15:16:45+0530]`, but the logcat did not have around `15:16:45+0530`

**Comment by phemasundar** [comment]
Nope.
I have taken the logcat logs(Pragramatically) after Appium exception displayed only.

**Comment by mykola-mokhnach** [comment]
It looks like the device stops responding to ADB. Please gett the logcat output from there manually using adb after the disconnect happens and attach it to the issue. Current logs are not very helpful.

Also make sure Doze mode is disabled on the device. See https://github.com/appium/appium-uiautomator2-server/issues/310

**Comment by phemasundar** [comment]
I tried getting the logcat logs manually. But post that there are no logs generated.

@mykola-mokhnach As mentioned in the other issue, Changed Battery settings (to Not Optimised) for the "Appium settings" app. But couldn't find any app with name contains UIAutomator2. And using capabilities skipServerInstallation & skipDeviceInitialization.

But still same issue is occurring.

**Comment by phemasundar** [comment]
Do I need to update the battery setting for Application under test as well?

**Comment by mykola-mokhnach** [comment]
It is impossible to say anything for sure without the logs. I would try a to replace the device under test with a different device model.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue

**Comment by KarthikMariGowda** [comment]
I am completely blocked with the same issue , some one please help

**Comment by KazuCocoa** [comment]
Perhaps we can help if you could get logcat when the issue happened and share it..

**Comment by phemasundar** [comment]
In my case:
* The Android device is managed by my company through SOTI (MobiControl) software
* Sometimes MobiControl is trying to auto-update some apps. At that time MobiControl is taking full control over the device by killing the UIAutomator2 session.
* It is working fine after I updated the MobiControl apps manually

@KarthikMariGowda Please check if it is a similar case with you.

**Comment by KarthikMariGowda** [comment]
@mykola-mokhnach 

On running my testNG xml file for parallel execution , i am getting socket hangup error , 
Here my first few test cases/ test classes will be executed smoothly and thereafter - time is getting out and ends up in socket hangup error, once after we see socket hangup ,  all the remaining  test scenarios will end up with same error.- this failures are happening inconsistently on test scenarios

**Note- On individual test script execution using testng , I am not facing any issue.**

Testing devices used- Samsung A30, Vivio , Moto x .

I have tried few approaches to resolve the issue by changing the system port from default to 8210, changing the automation engine,removing io.appium.uiautomator2.server and io.appium.uiautomator2.server.test from the device,downgrading appium server to the previous version -1.15.1 , testing on latest new device , removing junit from maven etc, ... .



**Appium Server Logs:**

 Calling AppiumDriver.click() with args: ["94429371-ee3d-4162-98fc-7102df7fb396","73abe4c1-ca63-4c6e-9c21-9a7548de3338"]
[WD Proxy] Matched '/element/94429371-ee3d-4162-98fc-7102df7fb396/click' to command name 'click'
[WD Proxy] Proxying [POST /element/94429371-ee3d-4162-98fc-7102df7fb396/click] to [POST http://127.0.0.1:8211/wd/hub/session/40c620cd-9f98-4c38-8155-45f0959d9e30/element/94429371-ee3d-4162-98fc-7102df7fb396/click] with body: {"element":"94429371-ee3d-4162-98fc-7102df7fb396"}
[WD Proxy] Got response with status 200: {"sessionId":"40c620cd-9f98-4c38-8155-45f0959d9e30","value":null}
[W3C (73abe4c1)] Responding to client with driver.click() result: null
[HTTP] <-- POST /wd/hub/session/73abe4c1-ca63-4c6e-9c21-9a7548de3338/element/94429371-ee3d-4162-98fc-7102df7fb396/click 200 22 ms - 14
[HTTP] 
[BaseDriver] Shutting down because we waited 60 seconds for a command
[Appium] Closing session, cause was 'New Command Timeout of 60 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'
[Appium] Removing session '1f358b42-75c1-4fd3-884b-b5ee4aba6a21' from our master session list
[UiAutomator2] Deleting UiAutomator2 session
[UiAutomator2] Deleting UiAutomator2 server session
[WD Proxy] Matched '/' to command name 'deleteSession'
[WD Proxy] Proxying [DELETE /] to [DELETE http://127.0.0.1:8211/wd/hub/session/dd9404e0-91b9-4351-9cb0-b97167ff12ee] with no body
[WD Proxy] Got response with status 200: {"sessionId":"dd9404e0-91b9-4351-9cb0-b97167ff12ee","value":null}
[ADB] Running 'C:\Users\vishr\Desktop\android-sdk\platform-tools\adb.exe -P 5037 -s 233e878 shell am force-stop test.ut.pahpal'
[Instrumentation] .
[Instrumentation] Time: 22.036
[Instrumentation] 
[Instrumentation] OK (1 test)
[Logcat] Stopping logcat capture
[ADB] Removing forwarded port socket connection: 8211 
[ADB] Running 'C:\Users\vishr\Desktop\android-sdk\platform-tools\adb.exe -P 5037 -s 233e878 forward --remove tcp\:8211'
[Instrumentation] The process has exited with code 0
[HTTP] --> POST /wd/hub/session/73abe4c1-ca63-4c6e-9c21-9a7548de3338/element
[HTTP] {"using":"xpath","value":"//*[contains(@resource-id,'test.ut.pahpal:id/edittext_reg_password')]"}
[W3C (73abe4c1)] Calling AppiumDriver.findElement() with args: ["xpath","//*[contains(@resource-id,'test.ut.pahpal:id/edittext_reg_password')]","73abe4c1-ca63-4c6e-9c21-9a7548de3338"]
[BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[BaseDriver] Waiting up to 25000000 ms for condition
[WD Proxy] Matched '/element' to command name 'findElement'
[WD Proxy] Proxying [POST /element] to [POST http://127.0.0.1:8211/wd/hub/session/40c620cd-9f98-4c38-8155-45f0959d9e30/element] with body: {"strategy":"xpath","selector":"//*[contains(@resource-id,'test.ut.pahpal:id/edittext_reg_password')]","context":"","multiple":false}
[WD Proxy] Got response with unknown status: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8211}
[W3C (73abe4c1)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8211
[W3C (73abe4c1)]     at JWProxy.command (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:266:13)
[HTTP] <-- POST /wd/hub/session/73abe4c1-ca63-4c6e-9c21-9a7548de3338/element 500 2045 ms - 606
[HTTP] 
[HTTP] --> POST /wd/hub/session/73abe4c1-ca63-4c6e-9c21-9a7548de3338/appium/app/close
[HTTP] {}
[W3C (73abe4c1)] Calling AppiumDriver.closeApp() with args: ["73abe4c1-ca63-4c6e-9c21-9a7548de3338"]
[ADB] Running 'C:\Users\vishr\Desktop\android-sdk\platform-tools\adb.exe -P 5037 -s 233e878 shell am force-stop test.ut.pahpal'
[W3C (73abe4c1)] Responding to client with driver.closeApp() result: null
[HTTP] <-- POST /wd/hub/session/73abe4c1-ca63-4c6e-9c21-9a7548de3338/appium/app/close 200 637 ms - 14
[HTTP] 
[BaseDriver] Shutting down because we waited 60 seconds for a command
[Appium] Closing session, cause was 'New Command Timeout of 60 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'
[Appium] Removing session '4327c9b8-b081-4882-bc36-bbc0ea355d36' from our master session list
[UiAutomator2] Deleting UiAutomator2 session
[UiAutomator2] Deleting UiAutomator2 server session
[WD Proxy] Matched '/' to command name 'deleteSession'
[WD Proxy] Proxying [DELETE /] to [DELETE http://127.0.0.1:8211/wd/hub/session/a62cc606-eda5-455f-b2b1-bb820a9743c5] with no body
[WD Proxy] Got response with unknown status: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8211}
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8211
[ADB] Running 'C:\Users\vishr\Desktop\android-sdk\platform-tools\adb.exe -P 5037 -s 233e878 shell am force-stop test.ut.pahpal'
[Logcat] Stopping logcat capture
[ADB] Removing forwarded port socket connection: 8211 


also @phemasundar : I have tried on my personal devices as well , so that should not be a problem :)

**Comment by KazuCocoa** [comment]
Please attach the full server log and maybe logcat also as GIST.
A new issue is preferred
(It looks port stuff though since the above error only uses 8211)

**Comment by kkallu** [comment]
Just FYI i see both issues very frequently with remotewebdriver i.e Econnreset and Socket hangUp[At times This persists in native as well] .So i started using webdriver in my scripts .
