### ISSUE TITLE
[Android] When trying to switch to a webview that is closed or reset appium hangs for a long time

### ISSUE THREAD

**Issue by Jiurong-Yang** [appium/appium#14434]
## The problem
When trying to switch into the webview that is either closed or no longer active. appium hangs for a very long time repeating the same thing. 

The repeating log looks like
1). Appium trying to send some command to chrome_driver but failing due to the page no longer exists
2). Wait for a certain period of time and trying again
3). Appium kills the chromedriver server and starts another one 
4). Appium trying to send the command to the new server which is still failing

## Environment

* Appium version: 1.17.0
* Desktop OS/version used to run Appium: Ubuntu 18.04
* Mobile platform/version under test: Android (All OS)
* Real device or emulator/simulator: Real device 
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs
This is the partial log exhibiting the behavior 
https://gist.github.com/Jiurong-Yang/f05e5466552539816dc28c39e2acacc3

## Code To Reproduce Issue [ Good To Have ]
1). Open an app with webview
2). Navigate to the webview, make sure you have more than 1 context now (Native, webview)
3). Close the webview or navigate away from the webview page
4). Call the command to switch into the closed webivew (driver.switch_to.context("WEBVIEW") for python)

The server should start doing what it's doing in the log, for a very long time.

**Comment by mykola-mokhnach** [comment]
I don't think there's is anything to there on Appium side. The delay is observed after the session startup command is sent to the chromedriver itself. You could also try to enable `ensureWebviewsHavePages` capability as recommended there and see if that helps

**Comment by Jiurong-Yang** [comment]
I had the ensureWebviewsHavePages turned on before, and it was exhibiting the same behavior. I was wondering if appium can fail gracefully here as it just keeps on trying to switch into the closed webview and relaunching the chrome driver. I'm assuming Appium is doing the retries? 

2020-06-10 17:47:16:256 - [WD Proxy] Got response with status 500: {"value":{"error":"unknown error","message":"unknown error: unable to discover open pages","stacktrace":"#0 0x5642e6a6a579 <unknown>\n"}}
2020-06-10 17:47:16:257 - [debug] [W3C] Matched W3C error code 'unknown error' to UnknownError
2020-06-10 17:47:16:257 - [Chromedriver] Failed to start Chromedriver session: An unknown server-side error occurred while processing the command. Original error: unknown error: unable to discover open pages
2020-06-10 17:47:16:259 - [debug] [Chromedriver] UnknownError: An unknown server-side error occurred while processing the command. Original error: unknown error: unable to discover open pages
2020-06-10 17:47:16:259 - [debug] [Chromedriver]     at errorFromW3CJsonCode (/usr/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:780:25)
2020-06-10 17:47:16:259 - [debug] [Chromedriver]     at ProxyRequestError.getActualError (/usr/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:663:14)
2020-06-10 17:47:16:259 - [debug] [Chromedriver]     at JWProxy.command (/usr/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:264:19)
2020-06-10 17:47:16:262 - [Chromedriver] Chromedriver exited unexpectedly with code null, signal SIGTERM
2020-06-10 17:47:16:263 - [debug] [Chromedriver] Changed state to 'stopped'
2020-06-10 17:47:16:263 - [Chromedriver] An unknown server-side error occurred while processing the command. Original error: unknown error: unable to discover open pages
2020-06-10 17:47:16:265 - [debug] [AndroidDriver] Getting a list of available webviews
2020-06-10 17:47:16:266 - [debug] [ADB] Running '/opt/android/platform-tools/adb -P 5037 -s 9885e64c50334b4355 shell cat /proc/net/unix'
2020-06-10 17:47:16:277 - [debug] [W3C (f9db2027)] Encountered internal error running command: Error: An unknown server-side error occurred while processing the command. Original error: unknown error: unable to discover open pages
2020-06-10 17:47:16:278 - [debug] [W3C (f9db2027)]     at Object.errorAndThrow (/usr/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:87:35)
2020-06-10 17:47:16:278 - [debug] [W3C (f9db2027)]     at Chromedriver.start (/usr/lib/node_modules/appium/node_modules/appium-chromedriver/lib/chromedriver.js:589:11)
2020-06-10 17:47:16:338 - [AndroidDriver] Not checking whether webviews have active pages; use the 'ensureWebviewsHavePages' cap to turn this check on
2020-06-10 17:47:16:339 - [debug] [AndroidDriver] WEBVIEW_32435 mapped to pid 32435
2020-06-10 17:47:16:339 - [debug] [AndroidDriver] Getting process name for webview
2020-06-10 17:47:16:339 - [debug] [ADB] Running '/opt/android/platform-tools/adb -P 5037 -s 9885e64c50334b4355 shell ps'
2020-06-10 17:47:16:461 - [HTTP] --> GET /wd/hub/status
2020-06-10 17:47:16:462 - [HTTP] {}
2020-06-10 17:47:16:462 - [debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
2020-06-10 17:47:16:462 - [debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.17.0"}}
2020-06-10 17:47:16:463 - [HTTP] <-- GET /wd/hub/status 200 2 ms - 68
2020-06-10 17:47:16:464 - [HTTP] 
2020-06-10 17:47:16:484 - [debug] [AndroidDriver] Parsed pid: '32435' pkg: 'com.hp.printercontrol.debug' from
2020-06-10 17:47:16:484 - [debug] [AndroidDriver]     USER           PID  PPID     VSZ    RSS WCHAN            ADDR S NAME
2020-06-10 17:47:16:484 - [debug] [AndroidDriver]     u0_a9515     32435  3298 3068828 300012 SyS_epoll_wait      0 S com.hp.printercontrol.debug
2020-06-10 17:47:16:484 - [debug] [AndroidDriver] Returning process name: 'com.hp.printercontrol.debug'
2020-06-10 17:47:16:485 - [debug] [AndroidDriver] Found webviews: ["WEBVIEW_stetho_com.hp.printercontrol.debug","WEBVIEW_chrome","WEBVIEW_com.hp.printercontrol.debug"]
2020-06-10 17:47:16:485 - [debug] [AndroidDriver] Available contexts: ["NATIVE_APP","WEBVIEW_stetho_com.hp.printercontrol.debug","WEBVIEW_chrome","WEBVIEW_com.hp.printercontrol.debug"]
2020-06-10 17:47:16:485 - [debug] [AndroidDriver] Connecting to chrome-backed webview context 'WEBVIEW_com.hp.printercontrol.debug'
2020-06-10 17:47:16:489 - [debug] [AndroidDriver] A port was not given, using random free port: 8000
2020-06-10 17:47:16:490 - [debug] [AndroidDriver] Before starting chromedriver, androidPackage is 'com.hp.printercontrol.debug'
2020-06-10 17:47:16:490 - [debug] [Chromedriver] Changed state to 'starting'
2020-06-10 17:47:16:491 - [Chromedriver] Set chromedriver binary as: /work/jay/MobileApps/resources/test_data/driver/latest/chromedriver
2020-06-10 17:47:16:491 - [debug] [Chromedriver] Killing any old chromedrivers, running: pkill -15 -f "/work/jay/MobileApps/resources/test_data/driver/latest/chromedriver.*--port=8000"
2020-06-10 17:47:16:529 - [Chromedriver] No old chromedrivers seem to exist
2020-06-10 17:47:16:529 - [debug] [Chromedriver] Cleaning any old adb forwarded port socket connections
2020-06-10 17:47:16:530 - [debug] [ADB] List forwarding ports
2020-06-10 17:47:16:530 - [debug] [ADB] Running '/opt/android/platform-tools/adb -P 5037 -s 9885e64c50334b4355 forward --list'
2020-06-10 17:47:16:543 - [debug] [ADB] Removing forwarded port socket connection: 40805 
2020-06-10 17:47:16:544 - [debug] [ADB] Running '/opt/android/platform-tools/adb -P 5037 -s 9885e64c50334b4355 forward --remove tcp\:40805'
2020-06-10 17:47:16:556 - [debug] [ADB] Removing forwarded port socket connection: 42313 
2020-06-10 17:47:16:557 - [debug] [ADB] Running '/opt/android/platform-tools/adb -P 5037 -s 9885e64c50334b4355 forward --remove tcp\:42313'
2020-06-10 17:47:16:568 - [debug] [ADB] Removing forwarded port socket connection: 36787 
2020-06-10 17:47:16:568 - [debug] [ADB] Running '/opt/android/platform-tools/adb -P 5037 -s 9885e64c50334b4355 forward --remove tcp\:36787'
2020-06-10 17:47:16:581 - [debug] [ADB] Removing forwarded port socket connection: 36341 
2020-06-10 17:47:16:581 - [debug] [ADB] Running '/opt/android/platform-tools/adb -P 5037 -s 9885e64c50334b4355 forward --remove tcp\:36341'
2020-06-10 17:47:16:592 - [Chromedriver] Spawning chromedriver with: /work/jay/MobileApps/resources/test_data/driver/latest/chromedriver --url-base=wd/hub --port=8000 --adb-port=5037 --verbose
2020-06-10 17:47:16:605 - [debug] [Chromedriver] Chromedriver version: '83.0.4103.39'
2020-06-10 17:47:16:606 - [debug] [WD Proxy] Matched '/status' to command name 'getStatus'
2020-06-10 17:47:16:606 - [debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body
2020-06-10 17:47:16:612 - [debug] [WD Proxy] Got response with status 200: {"value":{"build":{"version":"83.0.4103.39 (ccbf011cb2d2b19b506d844400483861342c20cd-refs/branch-heads/4103@{#416})"},"message":"ChromeDriver ready for new sessions.","os":{"arch":"x86_64","name":"Linux","version":"4.15.0-101-generic"},"ready":true}}
2020-06-10 17:47:16:612 - [Chromedriver] Starting W3C Chromedriver session with capabilities: {
2020-06-10 17:47:16:612 - [Chromedriver]   "capabilities": {
2020-06-10 17:47:16:613 - [Chromedriver]     "alwaysMatch": {
2020-06-10 17:47:16:613 - [Chromedriver]       "goog:chromeOptions": {
2020-06-10 17:47:16:613 - [Chromedriver]         "androidPackage": "com.hp.printercontrol.debug",
2020-06-10 17:47:16:613 - [Chromedriver]         "androidUseRunningApp": true,
2020-06-10 17:47:16:613 - [Chromedriver]         "androidDeviceSerial": "9885e64c50334b4355"
2020-06-10 17:47:16:613 - [Chromedriver]       },
2020-06-10 17:47:16:613 - [Chromedriver]       "goog:loggingPrefs": {
2020-06-10 17:47:16:613 - [Chromedriver]         "browser": "ALL"
2020-06-10 17:47:16:614 - [Chromedriver]       }
2020-06-10 17:47:16:614 - [Chromedriver]     }
2020-06-10 17:47:16:614 - [Chromedriver]   }
2020-06-10 17:47:16:614 - [Chromedriver] }

This portion of the log is when Appium got an unknown error and just closed the previous chromedriver session and launched another one and continue to try, this process could go on for hours.

**Comment by mykola-mokhnach** [comment]
Yes, currently the session startup retries count is hardcoded to 4:
https://github.com/appium/appium-chromedriver/blob/7c6cf495ec53e1148fb5dd97a5c5a838acab65db/lib/chromedriver.js#L583

I think it would be possible to customize this value from capabilities

**Comment by mykola-mokhnach** [comment]
Or we could even get rid of the retries, since I assume adb is now much more stable in comparison it was 4 years ago when this code was written...

**Comment by mykola-mokhnach** [comment]
I have published a new patch to the chromedriver in appium@beta where the retry has been removed

**Comment by Jiurong-Yang** [comment]
@mykola-mokhnach Addendum to this thread, when calling self.driver.current_window_handle (Python) when no webview is open hangs the appium servers as well just FYI. 

50/window' to command name 'getWindowHandle'
2020-06-15 17:08:16:927 - [debug] [Protocol Converter] Did not know how to rewrite the original URL '/wd/hub/session/bbe5f2f1-77b8-48b0-91b0-baff83d6da50/window' for W3C protocol
2020-06-15 17:08:16:928 - [debug] [WD Proxy] Proxying [GET /wd/hub/session/bbe5f2f1-77b8-48b0-91b0-baff83d6da50/window] to [GET http://127.0.0.1:11304/wd/hub/session/6d5c0eee-672b-46fe-bce0-3b0f1af1c10e/window] with body: {}

It seems like Appium have a systematic issue of giving support to these web command end points but they are not failing gracefully.

**Comment by mykola-mokhnach** [comment]
@Jiurong-Yang Unfortunately it's hard to address such issues from our side, since it is necessary to have at least the app under test itself to reproduce them. Although, I could point out to the area of server code, which is responsible for this logic, so you could debug it locally and perform the necessary fixes/improvements not only for yourself, but also for other people using Appium.
