### ISSUE TITLE
uncaughtException: The frame is bigger than expected. Length: 544109898, max: 1000000

### ISSUE THREAD

**Issue by kursatdostoglu** [appium/appium#14436]
## The problem

During the test run,the appium process was found have crashed on some real IOS devices.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.16.0
* Desktop OS/version used to run Appium: macOS 10.15.3
* Node.js version (unless using Appium.app|exe): Node.js v13.3.0
* Npm or Yarn package manager: npm 6.12.1
* Mobile platform/version under test: iOS 12.4
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe: CLI

## Details

2020-06-06 00:41:31:283 [HTTP] --> POST /wd/hub/session
2020-06-06 00:41:31:284 [HTTP] {"desiredCapabilities":{"fullreset":false,"server:CONFIG_UUID":"b5c8561a-7b8b-4b44-b6bd-25bee5609838","noReset":true,"newCommandTimeout":0,"platformVersion":"12.2","automationName":"XCUITest","bundleId":"com.netasautomation.bipdev","connectHardwareKeyboard":true,"platformName":"ios","udid":"4c48d7eae18093ab7f5733f4ab4873e17dd7c272","deviceName":"iPhone 5s"},"capabilities":{"firstMatch":[{"platformName":"ios","server:CONFIG_UUID":"b5c8561a-7b8b-4b44-b6bd-25bee5609838"}]}}
2020-06-06 00:41:31:287 [W3C] Calling AppiumDriver.createSession() with args: [{"fullreset":false,"server:CONFIG_UUID":"b5c8561a-7b8b-4b44-b6bd-25bee5609838","noReset":true,"newCommandTimeout":0,"platformVersion":"12.2","automationName":"XCUITest","bundleId":"com.netasautomation.bipdev","connectHardwareKeyboard":true,"platformName":"ios","udid":"4c48d7eae18093ab7f5733f4ab4873e17dd7c272","deviceName":"iPhone 5s"},null,{"firstMatch":[{"platformName":"ios","server:CONFIG_UUID":"b5c8561a-7b8b-4b44-b6bd-25bee5609838"}]}]
2020-06-06 00:41:31:294 [BaseDriver] Event 'newSessionRequested' logged at 1591393291292 (00:41:31 GMT+0300 (GMT+03:00))
2020-06-06 00:41:31:376 [BaseDriver] The capabilities ["mjpegServerPort","udid","usePrebuiltWDA","wdaLaunchTimeout","wdaLocalPort","wdaStartupRetries"] are not standard capabilities and should have an extension prefix
2020-06-06 00:41:31:398 [Appium] The following capabilities were provided in the JSONWP desired capabilities that are missing in W3C capabilities: ["fullreset","noReset","newCommandTimeout","platformVersion","automationName","bundleId","connectHardwareKeyboard","deviceName"]
2020-06-06 00:41:31:398 [Appium] Trying to fix W3C capabilities by merging them with JSONWP caps
2020-06-06 00:41:31:398 [BaseDriver] The capabilities ["fullreset","noReset","newCommandTimeout","platformVersion","automationName","bundleId","connectHardwareKeyboard","deviceName","mjpegServerPort","udid","usePrebuiltWDA","wdaLaunchTimeout","wdaLocalPort","wdaStartupRetries"] are not standard capabilities and should have an extension prefix
2020-06-06 00:41:31:443 [Appium] Appium v1.16.0 creating new XCUITestDriver (v3.10.1) session
2020-06-06 00:41:31:464 [Appium] Applying relaxed security to 'XCUITestDriver' as per server command line argument. All insecure features will be enabled unless explicitly disabled by --deny-insecure
2020-06-06 00:41:31:470 [BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
2020-06-06 00:41:31:470 [BaseDriver] Creating session with W3C capabilities: {
2020-06-06 00:41:31:470 [BaseDriver]   "alwaysMatch": {
2020-06-06 00:41:31:470 [BaseDriver]     "appium:fullreset": false,
2020-06-06 00:41:31:471 [BaseDriver]     "appium:noReset": true,
2020-06-06 00:41:31:471 [BaseDriver]     "appium:newCommandTimeout": 0,
2020-06-06 00:41:31:471 [BaseDriver]     "appium:platformVersion": "12.2",
2020-06-06 00:41:31:471 [BaseDriver]     "appium:automationName": "XCUITest",
2020-06-06 00:41:31:471 [BaseDriver]     "appium:bundleId": "com.netasautomation.bipdev",
2020-06-06 00:41:31:471 [BaseDriver]     "appium:connectHardwareKeyboard": true,
2020-06-06 00:41:31:471 [BaseDriver]     "appium:deviceName": "iPhone 5s",
2020-06-06 00:41:31:471 [BaseDriver]     "platformName": "ios",
2020-06-06 00:41:31:471 [BaseDriver]     "server:CONFIG_UUID": "b5c8561a-7b8b-4b44-b6bd-25bee5609838",
2020-06-06 00:41:31:471 [BaseDriver]     "appium:mjpegServerPort": 9182,
2020-06-06 00:41:31:471 [BaseDriver]     "appium:udid": "4c48d7eae18093ab7f5733f4ab4873e17dd7c272",
2020-06-06 00:41:31:471 [BaseDriver]     "appium:usePrebuiltWDA": true,
2020-06-06 00:41:31:471 [BaseDriver]     "appium:wdaLaunchTimeout": 120000,
2020-06-06 00:41:31:471 [BaseDriver]     "appium:wdaLocalPort": 8115,
2020-06-06 00:41:31:471 [BaseDriver]     "appium:wdaStartupRetries": 3
2020-06-06 00:41:31:471 [BaseDriver]   },
2020-06-06 00:41:31:471 [BaseDriver]   "firstMatch": [
2020-06-06 00:41:31:471 [BaseDriver]     {}
2020-06-06 00:41:31:471 [BaseDriver]   ]
2020-06-06 00:41:31:471 [BaseDriver] }
2020-06-06 00:41:31:513 [BaseDriver] The following capabilities were provided, but are not recognized by Appium:
2020-06-06 00:41:31:513 [BaseDriver]   server:CONFIG_UUID
2020-06-06 00:41:31:513 [BaseDriver]   fullreset
2020-06-06 00:41:31:517 [BaseDriver] Session created with session id: 367cea97-a047-4aad-99a5-c8191c3c0fd9
2020-06-06 00:41:31:559 [XCUITest] Current user: 'omernabiakdeniz'
2020-06-06 00:41:31:597 [XCUITest] Available devices: 3310fec0389e3c42696d7535593739048ea8f313, a47dd42d7ec55c60fbaae6105f7f8ddfa84e7362, 4c48d7eae18093ab7f5733f4ab4873e17dd7c272, c0cc27b6550f1237d32ace2ea9147405e203f03a, bf444c31592e637f5403af4492501b7f6da19138, 9b5bc7d2979b511236da2bf3e534786c41ff3592, cdbfe138f28c54795362c880f41f6c2786f3367a, c256bfc337b9a7e1e83ab6b669278798a2828964
2020-06-06 00:41:31:598 [XCUITest] Creating iDevice object with udid '4c48d7eae18093ab7f5733f4ab4873e17dd7c272'
2020-06-06 00:41:31:598 [XCUITest] Determining device to run tests on: udid: '4c48d7eae18093ab7f5733f4ab4873e17dd7c272', real device: true
2020-06-06 00:41:31:604 [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1591393291604 (00:41:31 GMT+0300 (GMT+03:00))
2020-06-06 00:41:31:605 [BaseDriver] Event 'appConfigured' logged at 1591393291605 (00:41:31 GMT+0300 (GMT+03:00))
2020-06-06 00:41:31:605 [BaseDriver] Event 'resetStarted' logged at 1591393291605 (00:41:31 GMT+0300 (GMT+03:00))
2020-06-06 00:41:31:616 [XCUITest] Reset: fullReset not set. Leaving as is
2020-06-06 00:41:31:616 [BaseDriver] Event 'resetComplete' logged at 1591393291616 (00:41:31 GMT+0300 (GMT+03:00))
2020-06-06 00:41:32:353 uncaughtException: The frame is bigger than expected. Length: 544109898, max: 1000000
Error: The frame is bigger than expected. Length: 544109898, max: 1000000
    at LengthBasedSplitter._decode (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-ios-device/lib/util/transformer/length-based-splitter.js:37:13)
    at LengthBasedSplitter._transform (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-ios-device/lib/util/transformer/length-based-splitter.js:19:48)
    at LengthBasedSplitter.Transform._read (_stream_transform.js:191:10)
    at LengthBasedSplitter.Transform._write (_stream_transform.js:179:12)
    at doWrite (_stream_writable.js:461:12)
    at writeOrBuffer (_stream_writable.js:443:5)
    at LengthBasedSplitter.Writable.write (_stream_writable.js:323:11)
    at Socket.ondata (_stream_readable.js:753:22)
    at Socket.emit (events.js:219:5)
    at addChunk (_stream_readable.js:332:12)
    at readableAddChunk (_stream_readable.js:307:11)
    at Socket.Readable.push (_stream_readable.js:241:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:185:23)

**Comment by mykola-mokhnach** [comment]
Please use the most recent appium version

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by kursatdostoglu** [comment]
Do you have a solution in this version?
