### ISSUE TITLE
'Boot completed' is incorrectly detected when '-no-boot-anim' parameter is passed to AVD

### ISSUE THREAD

**Issue by dtolstyi** [appium/appium#14488]
## The problem
The actual error is: `Appium Settings app is not running after 5000ms`
Here's the part of stacktrace:
```
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Appium Settings app is not running after 5000ms
    at getResponseForW3CError (C:\Users\Angel\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\Angel\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:392:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'ENIGMA', ip: '169.254.251.101', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_121'
Driver info: driver.version: AndroidDriver
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:208)
	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:217)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
```

## Environment

* Appium version (or git revision) that exhibits the issue: **v1.17.1**
* Last Appium version that did not exhibit the issue (if applicable): **-**
* Desktop OS/version used to run Appium: **Windows 8.1**
* Node.js version (unless using Appium.app|exe): **v10.3.0**
* Npm or Yarn package manager: **npm 6.1.0**
* Mobile platform/version under test: **Android**
* Real device or emulator/simulator: **AVD Emulator**
* Appium CLI or Appium.app|exe: 

## Details

This issue happens only when I add `-no-boot-anim` parameter to AVD to speed it up. All other settings stay absolutely the same.
Timeout happens because Appium starts searching for Appium Settings process even before the boot is completed that's why it fails to do it in 5 seconds timeout it got.

Here's the part of log **without** `-no-boot-anim` param:
```
[debug] [ADB] Running 'E:\Programs\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell getprop init.svc.bootanim'
[debug] [ADB] Running 'E:\Programs\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell getprop init.svc.bootanim'
[debug] [ADB] Running 'E:\Programs\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell pm get-install-location'
[AndroidDriver] Using device: emulator-5554
[ADB] Using 'adb.exe' from 'E:\Programs\Android\Sdk\platform-tools\adb.exe'
[debug] [ADB] Setting device id to emulator-5554
[debug] [ADB] Running 'E:\Programs\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.sdk'
[debug] [ADB] Current device property 'ro.build.version.sdk': 29
[ADB] Getting device platform version
[debug] [ADB] Running 'E:\Programs\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.release'
[debug] [ADB] Current device property 'ro.build.version.release': 10
[debug] [ADB] Device API level: 29
[UiAutomator2] Relaxing hidden api policy
[debug] [ADB] Running 'E:\Programs\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell settings put global hidden_api_policy_pre_p_apps 1'
[debug] [ADB] Running 'E:\Programs\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell settings put global hidden_api_policy_p_apps 1'
[debug] [ADB] Running 'E:\Programs\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell settings put global hidden_api_policy 1'
[ADB] [AVD OUTPUT] emulator: INFO: boot completed
```
And respective part of log **with** `-no-boot-anim` param:
```
[debug] [ADB] Running 'E:\Programs\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell getprop init.svc.bootanim'
[debug] [ADB] Running 'E:\Programs\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell pm get-install-location'
[AndroidDriver] Using device: emulator-5554
[ADB] Using 'adb.exe' from 'E:\Programs\Android\Sdk\platform-tools\adb.exe'
[debug] [ADB] Setting device id to emulator-5554
[debug] [ADB] Running 'E:\Programs\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.sdk'
[debug] [ADB] Current device property 'ro.build.version.sdk': 29
[ADB] Getting device platform version
[debug] [ADB] Running 'E:\Programs\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.release'
[debug] [ADB] Current device property 'ro.build.version.release': 10
[debug] [ADB] Device API level: 29
[UiAutomator2] Relaxing hidden api policy
[debug] [ADB] Running 'E:\Programs\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell settings put global hidden_api_policy_pre_p_apps 1'
[debug] [ADB] Running 'E:\Programs\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell settings put global hidden_api_policy_p_apps 1'
[debug] [ADB] Running 'E:\Programs\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell settings put global hidden_api_policy 1'
[debug] [AndroidDriver] Parsing package and activity from app manifest
[ADB] Package name: 'com.google.android.calculator'
[ADB] Main activity name: 'com.android.calculator2.Calculator'
[debug] [AndroidDriver] Parsed package and activity are: com.google.android.calculator/com.android.calculator2.Calculator
[debug] [ADB] Running 'E:\Programs\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 wait-for-device'
[debug] [ADB] Running 'E:\Programs\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell echo ping'
[debug] [AndroidDriver] Pushing settings apk to device...
[debug] [ADB] Getting install status for io.appium.settings
[debug] [ADB] Running 'E:\Programs\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys package io.appium.settings'
[debug] [ADB] 'io.appium.settings' is installed
[debug] [ADB] Getting package info for 'io.appium.settings'
[debug] [ADB] Running 'E:\Programs\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys package io.appium.settings'
[debug] [ADB] The version name of the installed 'io.appium.settings' is greater or equal to the application version name ('3.1.0' >= '3.1.0')
[debug] [ADB] There is no need to install/upgrade 'C:\Users\Angel\AppData\Roaming\npm\node_modules\appium\node_modules\io.appium.settings\apks\settings_apk-debug.apk'
[debug] [ADB] Getting IDs of all 'io.appium.settings' processes
[debug] [ADB] Running 'E:\Programs\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell 'pgrep --help; echo $?''
[debug] [ADB] Running 'E:\Programs\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell pgrep -f io\\.appium\\.settings'
[debug] [ADB] Getting IDs of all 'io.appium.settings' processes
[debug] [ADB] Running 'E:\Programs\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell pgrep -f io\\.appium\\.settings'
[debug] [ADB] Starting Appium Settings app
[debug] [ADB] Running 'E:\Programs\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell am start -n io.appium.settings/.Settings -a android.intent.action.MAIN -c android.intent.category.LAUNCHER'
[debug] [ADB] Getting IDs of all 'io.appium.settings' processes
[debug] [ADB] Running 'E:\Programs\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell pgrep -f io\\.appium\\.settings'
[debug] [ADB] Getting IDs of all 'io.appium.settings' processes
[debug] [ADB] Running 'E:\Programs\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell pgrep -f io\\.appium\\.settings'
[debug] [ADB] Getting IDs of all 'io.appium.settings' processes
[debug] [ADB] Running 'E:\Programs\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell pgrep -f io\\.appium\\.settings'
[debug] [ADB] Getting IDs of all 'io.appium.settings' processes
[debug] [ADB] Running 'E:\Programs\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell pgrep -f io\\.appium\\.settings'
[debug] [ADB] Getting IDs of all 'io.appium.settings' processes
[debug] [ADB] Running 'E:\Programs\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell pgrep -f io\\.appium\\.settings'
[debug] [ADB] Getting IDs of all 'io.appium.settings' processes
[debug] [ADB] Running 'E:\Programs\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell pgrep -f io\\.appium\\.settings'
[debug] [ADB] Getting IDs of all 'io.appium.settings' processes
[debug] [ADB] Running 'E:\Programs\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell pgrep -f io\\.appium\\.settings'
[debug] [ADB] Getting IDs of all 'io.appium.settings' processes
[debug] [ADB] Running 'E:\Programs\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell pgrep -f io\\.appium\\.settings'
[debug] [ADB] Getting IDs of all 'io.appium.settings' processes
[debug] [ADB] Running 'E:\Programs\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell pgrep -f io\\.appium\\.settings'
[debug] [ADB] Getting IDs of all 'io.appium.settings' processes
[debug] [ADB] Running 'E:\Programs\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell pgrep -f io\\.appium\\.settings'
[ADB] [AVD OUTPUT] emulator: INFO: boot completed
```

So, when emulator tells us that boot is completed with `-no-boot-anim` param we are already looking for Appium Settings app for quite some time and failing to do so in 5 seconds timeout.

## Link to Appium logs
https://gist.github.com/dtolstyi/15857f92a257703296bf6b4b0306c2e4

## Code To Reproduce Issue
```kotlin
val serviceBuilder = AppiumServiceBuilder().apply {
    usingAnyFreePort()
}
val server = AppiumDriverLocalService.buildService(serviceBuilder)

val capabilities = DesiredCapabilities().apply {
    setCapability(MobileCapabilityType.DEVICE_NAME, "Android Emulator");
    setCapability(MobileCapabilityType.PLATFORM_NAME, MobilePlatform.ANDROID)
    setCapability(MobileCapabilityType.APP, "D:\\a.apk")
    setCapability(AndroidMobileCapabilityType.AVD, "Nexus_5X_API_29_-_1")
    setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.ANDROID_UIAUTOMATOR2)
    setCapability(AndroidMobileCapabilityType.AVD_ARGS, "-noaudio -gpu auto -accel on -no-boot-anim -no-snapshot-save");
}
val driver = AndroidDriver<AndroidElement>(server.url, capabilities)
```

**Comment by mykola-mokhnach** [comment]
This is the expected behaviour. You could use appium@beta where the behaviour was updated to use the recent emulator features. Check https://github.com/appium/appium/issues/14347 for more details.

**Comment by dtolstyi** [comment]
Дякую, @mykola-mokhnach!
Good catch on `-delay-adb` param.
Strange that I didn't manage to find original issue when searching for respective error but, anyway, with Appium `v1.18.0-beta.0` everything seems to work fine and the work with Emulator does really start only after the boot/load is done and it's much later than it's in current stable Appium version (stable version starts working with emulator when it still loads launcher but the @beta work starts only after everything is loaded which is much better IMO).

Thank you for your help and all the best! Stay healthy!
