### ISSUE TITLE
An error on MacOS 10.13.3 (iOS 11.2 Simulator) after update from 1.15.1 > 1.17.1

### ISSUE THREAD

**Issue by tuobraun** [appium/appium#14522]
## The problem

When I updated from Appium Desktop 1.15.1 to 17.1.1 on MacOS 10.13.3 using iOS 11.2 iPhone X Simulator all my tests scripts written in Python 3.8.3 (Pytest 5.4.3) started to fail with an error.
I briefly took a look at the logs (attached) and it seems that it fails on the second step of my test script when I try to perform .clear() command.
But when I install Appium 1.15.1 again - everything runs fine.

## Environment

* Appium version (or git revision) that exhibits the issue: 17.1.1-1
* Last Appium version that did not exhibit the issue (if applicable): 1.15.1
* Desktop OS/version used to run Appium: MacOS 10.13.3
* Mobile platform/version under test: iOS 11.2
* Real device or emulator/simulator: iPhone X Simulator

## Details

Part of the code when the error appears first:
```
    def enter_credentials(self, url, usrnm, psswrd):
        url_name = self.app.wait_element(self.login_screen_url)
        url_name.clear()

    def test_login(mainfixture):
        mainfixture.login.enter_credentials("web_site_url", "user_name", "password")
```
Part of Appium Log:
```
[HTTP] --> POST /wd/hub/session/983d562f-3e61-466d-9044-97bf19ec9dca/element/24000000-0000-0000-28FE-000000000000/clear
[HTTP] {"id":"24000000-0000-0000-28FE-000000000000"}
[debug] [W3C (983d562f)] Calling AppiumDriver.clear() with args: ["24000000-0000-0000-28FE-000000000000","983d562f-3e61-466d-9044-97bf19ec9dca"]
[debug] [XCUITest] Executing command 'clear'
[debug] [WD Proxy] Matched '/element/24000000-0000-0000-28FE-000000000000/clear' to command name 'clear'
[debug] [WD Proxy] Proxying [POST /element/24000000-0000-0000-28FE-000000000000/clear] to [POST http://127.0.0.1:8100/session/8EC699B4-7920-40E2-AC0C-E52314C9B54B/element/24000000-0000-0000-28FE-000000000000/clear] with no body
[WD Proxy] Got response with status 500: {
[WD Proxy]   "value" : {
[WD Proxy]     "error" : "unknown error",
[WD Proxy]     "message" : "-[XCElementSnapshot hitPoint:]: unrecognized selector sent to instance 0x60400018f7d0",
[WD Proxy]     "traceback" : "(\n\t0   CoreFoundation                      0x000000010d93012b __exceptionPreprocess + 171\n\t1   libobjc.A.dylib                     0x000000010cfc4f41 objc_exception_throw + 48\n\t2   CoreFoundation                      0x000000010d9b1024 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132\n\t3   CoreFoundation                      0x000000010d8b2f78 ___forwarding___ + 1432\n\t4   CoreFoundation                      0x000000010d8b2958 _CF_forwarding_prep_0 + 120\n\t5   WebDriverAgentLib                   0x00000001223cdba2 -[XCElementSnapshot(FBHitPoint) fb_hitPoint] + 66\n\t6   WebDriverAgentLib                   0x00000001223ac43f -[FBBaseGestureItem hitpointWithElement:positionOffset:error:] + 847\n\t7   WebDriverAgentLib                   0x0000000122380ce4 -[FBAppiumGestureItem coordinatesWithOptions:error:] + 1284\n\t8   WebDri...
[debug] [W3C] Matched W3C error code 'unknown error' to UnknownError
[debug] [W3C (983d562f)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: -[XCElementSnapshot hitPoint:]: unrecognized selector sent to instance 0x60400018f7d0
[debug] [W3C (983d562f)]     at errorFromW3CJsonCode (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:780:25)
[debug] [W3C (983d562f)]     at ProxyRequestError.getActualError (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:663:14)
[debug] [W3C (983d562f)]     at JWProxy.command (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:264:19)
[HTTP] <-- POST /wd/hub/session/983d562f-3e61-466d-9044-97bf19ec9dca/element/24000000-0000-0000-28FE-000000000000/clear 500 176 ms - 810
```

## Link to Appium logs

https://gist.github.com/tuobraun/4c37c81743028e17c4fe18dbe567ac7d

## Code To Reproduce Issue

Link to the code sample: https://github.com/tuobraun/appium-testcases/blob/master/pytest/test-script.zip

**Comment by mykola-mokhnach** [comment]
Appium 1.17 does not support Xcode9 anymore, so the error is expected. Consider upgrading Xcode or switching back to the older Appium version

**Comment by tuobraun** [comment]
Oh, sorry, I didn't know. Thanks. Maybe I missed a mentioning of this in the release notes... I spent so much time trying to figure out what's going on :)
