### ISSUE TITLE
get location method has not yet been implemented

### ISSUE THREAD

**Issue by JunZheng007** [appium/appium#14526]
## The problem

When I try to get a geographic location from a real iOS device, I get method not yet been implemented ERROR

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.1
* Desktop OS/version used to run Appium: macOS Catalina 10.15.5
* Node.js version (unless using Appium.app|exe): 14.4.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iPhone 7 Plus 13.5.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium.app

## Details

I am running UI test on an iOS device, When I try to get the geographic location, I use this command:
```
self.driver.location()
```

Then I got an error message
```
self = <appium.webdriver.errorhandler.MobileErrorHandler object at 0x11bca7520>
response = {'status': 405, 'value': '{"value":{"error":"unknown method","message":"Method has not yet been implemented","stacktra...um.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:309:21)"}}'}

selenium.common.exceptions.WebDriverException: Message: Method has not yet been implemented
```

message from appium app:
```
[W3C (61f77549)] Calling AppiumDriver.getGeoLocation() with args: ["61f77549-aae3-4f27-aaa4-f14acc61d51f"]
[XCUITest] Executing command 'getGeoLocation'
[W3C (61f77549)] Encountered internal error running command: NotYetImplementedError: Method has not yet been implemented
[W3C (61f77549)]     at XCUITestDriver.executeCommand (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:323:13)
[W3C (61f77549)]     at XCUITestDriver.executeCommand (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:711:24)
[W3C (61f77549)]     at AppiumDriver.executeCommand (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/lib/appium.js:534:36)
[W3C (61f77549)]     at runMicrotasks ()
[W3C (61f77549)]     at processTicksAndRejections (internal/process/task_queues.js:85:5)
[W3C (61f77549)]     at asyncHandler (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:309:21)
[HTTP] <-- GET /wd/hub/session/61f77549-aae3-4f27-aaa4-f14acc61d51f/location 405 2 ms - 887
```

**Comment by mykola-mokhnach** [comment]
The error is expected. This API only works on Android. Apple does not provide any APIs which allow to retrieve location via XCTest.
