### ISSUE TITLE
java.lang.ClassCastException: com.google.common.collect.Maps$TransformedEntriesMap cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by sarabjit-singh** [appium/appium#14528]
## The problem

I have a Webview in my Android app which I am trying to automate. When I try to click on a value in a bootstrap dropdown then java.lang.ClassCastException: com.google.common.collect.Maps$TransformedEntriesMap cannot be cast to java.lang.String error is displayed.

## Environment

* Appium version : 7.0.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows
* Node.js version (unless using Appium.app|exe): 6.9.0
* Npm or Yarn package manager:
* Mobile platform/version under test: Android 9.0
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: 1.12.1

## Details

java.lang.ClassCastException: com.google.common.collect.Maps$TransformedEntriesMap cannot be cast to java.lang.String
	at org.openqa.selenium.remote.RemoteWebElement.getText(RemoteWebElement.java:167)
	at HeorkuApp.Heroku.Page.CreateLeadPage.selectLoanAmountUseOptionNew(CreateLeadPage.java:171)
	at HerokuApp.Heroku.Test.CreateLeadTest.createLead(CreateLeadTest.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

## Link to Appium logs

https://gist.github.com/sarabjit-singh/31546335add3580999489a3245620130

## Code To Reproduce Issue [ Good To Have ]

		for (WebElement option : list) {
			//System.out.println(option.getText());
			if(option.getText().equalsIgnoreCase("Test"));
			option.click();
		}
		Thread.sleep(2000);
		driver.hideKeyboard();

Options.getText().equals() is throwing the exception. I have already switched the context interacting with this webelement.

**Comment by mykola-mokhnach** [comment]
Please use the most recent server and client versions. Unfortunately, we don't provide patches to older releases
