### ISSUE TITLE
if send empty string to "replace_value" command, base driver will send null value to device, which will cause "org.json.JSONException" on device side 

### ISSUE THREAD

**Issue by JesseCodeBones** [appium/appium#14637]
## The problem

for the Appium command: '/session/:sessionId/appium/element/:elementId/replace_value'
if we send this command with empty string value, ie "".
the argument will be translated to null value:
`Calling AppiumDriver.replaceValue() with args: [null,"76e0fc0e-0832-4ac1-aadd-23c71ffcc973","a094795f-8508-40fa-8b5a-7df8e679acab"]`
and the device will response below exceptions:
`2020-08-06 17:53:01:705 [WD Proxy] Matched '/element/76e0fc0e-0832-4ac1-aadd-23c71ffcc973/value' to command name 'setValue'
2020-08-06 17:53:01:705 [WD Proxy] Proxying [POST /element/76e0fc0e-0832-4ac1-aadd-23c71ffcc973/value] to [POST http://127.0.0.1:28135/wd/hub/session/0cb21dc1-6221-476f-9422-09c6461b9eef/element/76e0fc0e-0832-4ac1-aadd-23c71ffcc973/value] with body: {"elementId":"76e0fc0e-0832-4ac1-aadd-23c71ffcc973","replace":true}
2020-08-06 17:53:01:797 [WD Proxy] Got response with status 400: {"sessionId":"0cb21dc1-6221-476f-9422-09c6461b9eef","value":{"error":"invalid argument","message":"org.json.JSONException: No value for text","stacktrace":"io.appium.uiautomator2.common.exceptions.InvalidArgumentException: org.json.JSONException: No value for text\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:44)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:251)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:241)\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:51)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\n\tat io.netty.handler.codec.MessageToMessageDecoder.channelRea...
2020-08-06 17:53:01:798 [W3C] Matched W3C error code 'invalid argument' to InvalidArgumentError
2020-08-06 17:53:01:835 [MJSONWP (a094795f)] Encountered internal error running command: io.appium.uiautomator2.common.exceptions.InvalidArgumentException: org.json.JSONException: No value for text
2020-08-06 17:53:01:835 [MJSONWP (a094795f)] 	at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:44)
2020-08-06 17:53:01:835 [MJSONWP (a094795f)] 	at io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:251)
2020-08-06 17:53:01:835 [MJSONWP (a094795f)] 	at io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:241)
2020-08-06 17:53:01:835 [MJSONWP (a094795f)] 	at io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:51)
2020-08-06 17:53:01:835 [MJSONWP (a094795f)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
2020-08-06 17:53:01:836 [MJSONWP (a094795f)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
2020-08-06 17:53:01:836 [MJSONWP (a094795f)] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
2020-08-06 17:53:01:836 [MJSONWP (a094795f)] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
2020-08-06 17:53:01:836 [MJSONWP (a094795f)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
2020-08-06 17:53:01:836 [MJSONWP (a094795f)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
2020-08-06 17:53:01:836 [MJSONWP (a094795f)] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
2020-08-06 17:53:01:836 [MJSONWP (a094795f)] 	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
2020-08-06 17:53:01:836 [MJSONWP (a094795f)] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
2020-08-06 17:53:01:836 [MJSONWP (a094795f)] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
2020-08-06 17:53:01:836 [MJSONWP (a094795f)] 	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
2020-08-06 17:53:01:836 [MJSONWP (a094795f)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
2020-08-06 17:53:01:836 [MJSONWP (a094795f)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
2020-08-06 17:53:01:836 [MJSONWP (a094795f)] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
2020-08-06 17:53:01:836 [MJSONWP (a094795f)] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
2020-08-06 17:53:01:836 [MJSONWP (a094795f)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
2020-08-06 17:53:01:836 [MJSONWP (a094795f)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
2020-08-06 17:53:01:836 [MJSONWP (a094795f)] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
2020-08-06 17:53:01:837 [MJSONWP (a094795f)] 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
2020-08-06 17:53:01:837 [MJSONWP (a094795f)] 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)
2020-08-06 17:53:01:837 [MJSONWP (a094795f)] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:514)
2020-08-06 17:53:01:837 [MJSONWP (a094795f)] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:468)
2020-08-06 17:53:01:837 [MJSONWP (a094795f)] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
2020-08-06 17:53:01:837 [MJSONWP (a094795f)] 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
2020-08-06 17:53:01:837 [MJSONWP (a094795f)] 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
2020-08-06 17:53:01:837 [MJSONWP (a094795f)] 	at java.lang.Thread.run(Thread.java:818)
2020-08-06 17:53:01:837 [MJSONWP (a094795f)] Caused by: org.json.JSONException: No value for text
2020-08-06 17:53:01:837 [MJSONWP (a094795f)] 	at org.json.JSONObject.get(JSONObject.java:389)
2020-08-06 17:53:01:837 [MJSONWP (a094795f)] 	at org.json.JSONObject.getString(JSONObject.java:550)
2020-08-06 17:53:01:837 [MJSONWP (a094795f)] 	at io.appium.uiautomator2.handler.SendKeysToElement.safeHandle(SendKeysToElement.java:70)
2020-08-06 17:53:01:837 [MJSONWP (a094795f)] 	at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:38)
2020-08-06 17:53:01:837 [MJSONWP (a094795f)] 	... 29 more
2020-08-06 17:53:01:837 [MJSONWP (a094795f)] 
2020-08-06 17:53:01:839 [HTTP] <-- POST /wd/hub/session/a094795f-8508-40fa-8b5a-7df8e679acab/appium/element/76e0fc0e-0832-4ac1-aadd-23c71ffcc973/replace_value 500 134 ms - 128`

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.0
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): 10.15.3
* Npm or Yarn package manager: Npm
* Mobile platform/version under test: Android 10
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium.exe

**Comment by mykola-mokhnach** [comment]
Please try the most recent server version

**Comment by JesseCodeBones** [comment]
> Please try the most recent server version

Hi mykola,
I fixed the issue with private fork version, master also have the issue.
the root cause is during the `makeArgs`, it generate null to device.
Here is my PR: https://github.com/appium/appium-base-driver/pull/423

Regards

**Comment by mykola-mokhnach** [comment]
The change has been published to appium@beta
