### ISSUE TITLE
Appium 1.18.0 won't install

### ISSUE THREAD

**Issue by sshock** [appium/appium#14638]
## The problem

I'm getting an error when I try to install appium@1.18.0 (in contrast, 1.17.1 worked fine).  The error has something to do with appium-windows-driver.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.0
* Last Appium version that did not exhibit the issue (if applicable): 1.17.1
* Desktop OS/version used to run Appium: Ubuntu Linux 18.04.4 LTS
* Node.js version (unless using Appium.app|exe): 8.10.0
* Npm or Yarn package manager: 3.5.2
* Mobile platform/version under test: n/a
* Real device or emulator/simulator: n/a
* Appium CLI or Appium.app|exe: cli

## Details

This error showed up when I ran `npm install appium@1.18.0`:

```
/home/deployer/node_modules/appium/node_modules/bluebird/js/release/promisify.js:270
        throw new TypeError("expecting a function but got " + util.classString(fn));
              ^
TypeError: expecting a function but got [object Undefined]
    at Function.promisify (/home/deployer/node_modules/appium/node_modules/bluebird/js/release/promisify.js:270:15)
    at Object.<anonymous> (/home/deployer/node_modules/appium/node_modules/appium-support/lib/zip.js:17:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/deployer/node_modules/appium/node_modules/appium-support/index.js:10:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
```

and this is what shows up at the end of the npm-debug.log:

```
109333 silly install appium-windows-driver@1.13.0 /home/deployer/node_modules/.staging/appium-windows-driver-4bc82b55
109334 info lifecycle appium-windows-driver@1.13.0~install: appium-windows-driver@1.13.0
109335 verbose lifecycle appium-windows-driver@1.13.0~install: unsafe-perm in lifecycle true
109336 verbose lifecycle appium-windows-driver@1.13.0~install: PATH: /usr/share/npm/bin/node-gyp-bin:/home/deployer/node_modules/appium/node_modules/appium-windows-driver/node_modules/.bin:/home/deployer/node_modules/appium/node_modules/.bin:/home/deployer/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/puppetlabs/bin:/usr/local/rvm/bin:/opt/puppetlabs/bin:/sbin
109337 verbose lifecycle appium-windows-driver@1.13.0~install: CWD: /home/deployer/node_modules/appium/node_modules/appium-windows-driver
109338 silly lifecycle appium-windows-driver@1.13.0~install: Args: [ '-c', 'node install-npm.js' ]
109339 silly lifecycle appium-windows-driver@1.13.0~install: Returned: code: 1  signal: null
109340 info lifecycle appium-windows-driver@1.13.0~install: Failed to exec install script
109341 verbose unlock done using /home/deployer/.npm/_locks/staging-91528af84a59626a.lock for /home/deployer/node_modules/.staging
109342 silly rollbackFailedOptional Starting
109343 silly rollbackFailedOptional Finishing
109344 silly runTopLevelLifecycles Starting
109345 silly runTopLevelLifecycles Finishing
109346 silly install printInstalled
109347 warn enoent ENOENT: no such file or directory, open '/home/deployer/package.json'
109348 warn deployer No description
109349 warn deployer No repository field.
109350 warn deployer No README data
109351 warn deployer No license field.
109352 verbose stack Error: appium-windows-driver@1.13.0 install: `node install-npm.js`
109352 verbose stack Exit status 1
109352 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
109352 verbose stack     at emitTwo (events.js:126:13)
109352 verbose stack     at EventEmitter.emit (events.js:214:7)
109352 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
109352 verbose stack     at emitTwo (events.js:126:13)
109352 verbose stack     at ChildProcess.emit (events.js:214:7)
109352 verbose stack     at maybeClose (internal/child_process.js:925:16)
109352 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
109353 verbose pkgid appium-windows-driver@1.13.0
109354 verbose cwd /home/deployer
109355 error Linux 4.15.0-112-generic
109356 error argv "/usr/bin/node" "/usr/bin/npm" "install" "appium@1.18.0"
109357 error node v8.10.0
109358 error npm  v3.5.2
109359 error code ELIFECYCLE
109360 error appium-windows-driver@1.13.0 install: `node install-npm.js`
109360 error Exit status 1
109361 error Failed at the appium-windows-driver@1.13.0 install script 'node install-npm.js'.
109361 error Make sure you have the latest version of node.js and npm installed.
109361 error If you do, this is most likely a problem with the appium-windows-driver package,
109361 error not with npm itself.
109361 error Tell the author that this fails on your system:
109361 error     node install-npm.js
109361 error You can get information on how to open an issue for this project with:
109361 error     npm bugs appium-windows-driver
109361 error Or if that isn't available, you can get their info via:
109361 error     npm owner ls appium-windows-driver
109361 error There is likely additional logging output above.
109362 verbose exit [ 1, true ]
```

## Summary

Is this happening because I need to update node and/or npm?  Also, is there a way to work around it for now by telling it to exclude appium-windows-driver?

**Comment by mykola-mokhnach** [comment]
The error is expected. Only NodeJS v 10+ is supported.

**Comment by sshock** [comment]
Good to know, thanks.
