### ISSUE TITLE
Unable to set custom CA certificate with recent openssl version

### ISSUE THREAD

**Issue by vania-pooh** [appium/appium#14666]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue: 1.16.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOS Catalina 10.15
* Node.js version (unless using Appium.app|exe): 12.18.3
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe:

## Details

Session does not create in case of setting `customSSLCert` capability with recent `openssl` version on MacOS Catalina.

## Link to Appium logs

```
2020-08-18 09:05:44:539 - [XCUITest] TypeError: Cannot read property '1' of null
2020-08-18 09:05:44:539 - [XCUITest]     at Certificate.getSubject (/Users/selenium/.nvm/versions/node/v12.18.3/lib/node_modules/appium/node_modules/appium-ios-simulator/lib/certificate.js:110:20)
2020-08-18 09:05:44:539 - [XCUITest]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-08-18 09:05:44:539 - [XCUITest]     at Certificate.has (/Users/selenium/.nvm/versions/node/v12.18.3/lib/node_modules/appium/node_modules/appium-ios-simulator/lib/certificate.js:40:19)
2020-08-18 09:05:44:540 - [XCUITest]     at XCUITestDriver.start (/Users/selenium/.nvm/versions/node/v12.18.3/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:378:13)
2020-08-18 09:05:44:540 - [XCUITest]     at XCUITestDriver.createSession (/Users/selenium/.nvm/versions/node/v12.18.3/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:215:7)
2020-08-18 09:05:44:540 - [XCUITest]     at AppiumDriver.createSession (/Users/selenium/.nvm/versions/node/v12.18.3/lib/node_modules/appium/lib/appium.js:358:35)
```

## Code To Reproduce Issue [ Good To Have ]

In recent `openssl` version output format for `x509` command has changed.

Before (working version):

```
$ openssl x509 -noout -subject -in MyCA.crt
subject= /CN=MyCA
$ openssl version
OpenSSL 1.0.2l  25 May 2017
```

Now (does not work):
```
$ openssl x509 -noout -subject -in myCA.crt
subject=CN = MyCA
$ openssl version
OpenSSL 1.1.1g  21 Apr 2020
```

Changed output leads to not matching regular expression here: https://github.com/appium/appium-ios-simulator/blob/master/lib/certificate.js#L109

**Comment by mykola-mokhnach** [comment]
Feel free to create a PR with a fix.

Btw, since Xcode 11.4 Apple added a built-in simctl subcommand to install simulator certificates, so this piece of code is not used anymore. The feature is available in the recent Appium release.

**Comment by vania-pooh** [comment]
@mykola-mokhnach could you please clarify an exact release version? Because this was reproducing with 1.18.0 too.

**Comment by mykola-mokhnach** [comment]
The patch has been published
