### ISSUE TITLE
UiAutomator2 Driver  `scrollIntoView` interprets comma-separated text as multiple arguments

### ISSUE THREAD

**Issue by rosemichaele** [appium/appium#14686]
## The problem

When attempting to scroll an element into view using a text contains locator with a comma-separated text value, UiAutomator2 driver throws an unexpected error. Removing commas from the text fixes the issue.

## Environment

* Appium version (or git revision) that exhibits the issue: `1.17.0`
* Last Appium version that did not exhibit the issue (if applicable): unknown
* Desktop OS/version used to run Appium: BrowserStack's Appium server, some flavor of Linux
* Node.js version (unless using Appium.app|exe): unsure, managed by BrowserStack
* Npm or Yarn package manager: unsure, managed by BrowserStack
* Mobile platform/version under test: Android 8.0
* Real device or emulator/simulator: Samsung Galaxy S9
* Appium CLI or Appium.app|exe: unsure, managed by BrowserStack

## Details

[BrowserStack test session](https://app-automate.browserstack.com/builds/c1a493e525ab2c1c4b7fbd7c10960ca5c1fc0581/sessions/5737148ab55f8dd15ce3a6ff3a4c2e0f3bd6f23e?auth_token=9beda659c7e3feeb094f3595ee40c86398a0e381d0631b53c9352aca54633172) (link good for 30 days)

## Link to Appium logs

https://gist.github.com/rosemichaele/a4ebbd610c69601e9146538c5740f702

## Code To Reproduce Issue [ Good To Have ]

Using the Ruby client:
```ruby
@driver.scroll_to('100 Walnut Street Suite 1000, Pleasantville, CA 12121')
```

Fixed on the client side like this:
```ruby
@driver.scroll_to('100 Walnut Street Suite 1000')
```

UiAutomator2 server-side element finder
```
2020-08-28 17:03:12:138 - [debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["-android uiautomator","new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().textContains(\"100 Walnut Street Suite 1000, Pleasantville, CA 12121\").instance(0));","d2faf7b8-3e25-40bf-8645-c0daace09e38"]
```  

Stack trace
```
io.appium.uiautomator2.common.exceptions.UiSelectorSyntaxException: Could not parse UiSelector argument: UiScrollable has no "scrollIntoView" method that takes 2 arguments
      at io.appium.uiautomator2.handler.FindElement.findByUiAutomator(FindElement.java:194)
      at io.appium.uiautomator2.handler.FindElement.findElement(FindElement.java:155) 
      at io.appium.uiautomator2.handler.FindElement.safeHandle(FindElement.java:102) 
      at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:56) 
      at io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:202) 
      at io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:193) 
      at io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:44) 
      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366) 
      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352) 
      at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345) 
      at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) 
      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366) 
      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352) 
      at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345) 
      at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435) 
      at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) 
      at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267) 
      at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250) 
      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366) 
      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352) 
      at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345) 
      at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294) 
      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366) 
      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352) 
      at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911) 
      at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) 
      at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611) 
      at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:552) 
      at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:466) 
      at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) 
      at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140) 
      at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144) 
      at java.lang.Thread.run(Thread.java:764)
```

**Comment by mykola-mokhnach** [comment]
>     at run (/usr/local/.browserstack/**appium_1.6.5_bstack**/node_modules/core-js/library/modules/es6.promise.js:108:47)

This looks rather like a BS issue. Make sure the proper Appium version is selected for your test (the most recent one is 1.18.1)

**Comment by rosemichaele** [comment]
> This looks rather like a BS issue. Make sure the proper Appium version is selected for your test (the most recent one is 1.18.1)

That was the problem - BrowserStack wasn't honoring the Appium version cap I had set (they have a custom one for this)

Thanks for the help.
