### ISSUE TITLE
uncaughtException: The frame is bigger than expected. Length: XXXXXX, max: 20971520

### ISSUE THREAD

**Issue by regiscaetano** [appium/appium#14700]
## The problem

uncaughtException: The frame is bigger than expected. Length: 24458470, max: 20971520

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.1
* Last Appium version that did not exhibit the issue (if applicable): n/a
* Desktop OS/version used to run Appium: MacOS 10.15.6
* Node.js version (unless using Appium.app|exe):v14.4.0
* Npm or Yarn package manager:n/a
* Mobile platform/version under test: iOS 13.6
* Real device or emulator/simulator: simulator iphone11
* Appium CLI or Appium.app|exe:n/a
*Hybrid APP
*AUTOWEBVIEW = ON

## Details

This problem was "fixed" in the past by bumping the max frame value to "20", however, it's going to fail if apps are bigger than that.

I fixed it in my environment by changing the frame  variable inside the file index.js, located on node_modules/appium-ios-device/build/lib/webinspector.

It would nice to have that as an easy configuration for appium (capability?) - using settings isn't very clear and doesn't have good documentation.

## Code To Reproduce Issue [ Good To Have ]
Just use an app which exceeds 20mb of frame

**Comment by regiscaetano** [comment]
uncaughtException: The frame is bigger than expected. Length: 24458470, max: 20971520
Error: The frame is bigger than expected. Length: 24458470, max: 20971520
    at LengthBasedSplitter._decode (/usr/local/lib/node_modules/appium/node_modules/appium-ios-device/lib/util/transformer/length-based-splitter.js:52:13)
    at LengthBasedSplitter._transform (/usr/local/lib/node_modules/appium/node_modules/appium-ios-device/lib/util/transformer/length-based-splitter.js:30:47)
    at LengthBasedSplitter.Transform._read (_stream_transform.js:191:10)
    at LengthBasedSplitter.Transform._write (_stream_transform.js:179:12)
    at writeOrBuffer (_stream_writable.js:352:12)
    at LengthBasedSplitter.Writable.write (_stream_writable.js:303:10)
    at StreamLogger.ondata (_stream_readable.js:712:22)
    at StreamLogger.emit (events.js:315:20)
    at addChunk (_stream_readable.js:302:12)
    at readableAddChunk (_stream_readable.js:278:9)
    at StreamLogger.Readable.push (_stream_readable.js:217:10)
    at StreamLogger.push (_stream_transform.js:152:32)
    at StreamLogger._transform (/usr/local/lib/node_modules/appium/node_modules/appium-ios-device/lib/util/transformer/stream-logger.js:30:10)
    at StreamLogger.Transform._read (_stream_transform.js:191:10)
    at StreamLogger.Transform._write (_stream_transform.js:179:12)
    at writeOrBuffer (_stream_writable.js:352:12)
    at StreamLogger.Writable.write (_stream_writable.js:303:10)
    at Socket.ondata (_stream_readable.js:712:22)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:302:12)
    at readableAddChunk (_stream_readable.js:278:9)
    at Socket.Readable.push (_stream_readable.js:217:10)

**Comment by KazuCocoa** [comment]
`safariWebInspectorMaxFrameLength` will be available in `appium@beta`
