### ISSUE TITLE
Application gives BadPaddingException when installing with Appium

### ISSUE THREAD

**Issue by donmezburak** [appium/appium#14704]
## The problem

When I downloaded application from google play store or online download websites like apkcombo.com, application starts without any problems. However, when I try downloaded application and start test with appium, appium installs and starts session and application but application gives BadPaddingException
## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.1
* Last Appium version that did not exhibit the issue (if applicable): -
* Desktop OS/version used to run Appium: macOS Catalina 10.15.6
* Node.js version (unless using Appium.app|exe): 14.4.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: android 9
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: Appium CLI 

## Details

I searched Android studio logs when application fails here:

`FATAL EXCEPTION: OkHttp Dispatcher
        java.lang.RuntimeException: javax.crypto.BadPaddingException: pad block corrupted
        at y5.b(SourceFile:23)
        at y5.a(SourceFile:81)
        at y5.c(SourceFile:5)
        at p8.intercept(SourceFile:3)
        at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:10)
        at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:1)
        at okhttp3.RealCall.getResponseWithInterceptorChain(SourceFile:13)
        at okhttp3.RealCall$AsyncCall.execute(SourceFile:2)
        at okhttp3.internal.NamedRunnable.run(SourceFile:3)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784)
     Caused by: javax.crypto.BadPaddingException: pad block corrupted
        at com.android.org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher$BufferedGenericBlockCipher.doFinal(BaseBlockCipher.java:1337)
        at com.android.org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineDoFinal(BaseBlockCipher.java:1170)
        at javax.crypto.Cipher.doFinal(Cipher.java:2055)`

## Link to Appium logs

https://gist.github.com/donmezburak/ab3702f1831d2e6705df00181319467b

## Code To Reproduce Issue [ Good To Have ]

I can send application upon request with mail.

`String absolutePath = file.getAbsolutePath();
            capabilities.setCapability(MobileCapabilityType.APP, absolutePath);
            capabilities.setCapability(MobileCapabilityType.UDID, "L2N4C19923004495");
            capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, Platform.ANDROID);
            capabilities.setCapability("autoGrantPermissions", true);
            String urlString = "http://127.0.0.1:4723/wd/hub";`

**Comment by mykola-mokhnach** [comment]
It could be the app has some internal integrity protection. Try to set `noSign` capability to `true` while running your tests.

**Comment by donmezburak** [comment]
It works. I guess that adding `noSign` capability is useful for just already signed applications like store applications etc. If so, is there any way to know whether application that will be tested on appium is signed or not and adding automatically sign decision options to appium ? Option like application is signed so not sign, or not signed ok I have to sign.

**Comment by mykola-mokhnach** [comment]
Good that it works. Kindly use Appum forum to ask questions.
