### ISSUE TITLE
Appium Settings crash :  Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.location.ILocationManager.isProviderEnabled(java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by fuzecheng** [appium/appium#14731]
appium version: 1.16

2020-09-14 15:28:12.685 3330-3330/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.appium.settings, PID: 3330
    java.lang.RuntimeException: Unable to start activity ComponentInfo{io.appium.settings/io.appium.settings.Settings}: java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.location.ILocationManager.isProviderEnabled(java.lang.String)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2671)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2732)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1483)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6141)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.location.ILocationManager.isProviderEnabled(java.lang.String)' on a null object reference
        at android.location.LocationManager.isProviderEnabled(LocationManager.java:1163)
        at io.appium.settings.LocationTracker.startLocationUpdatesWithoutPlayServices(LocationTracker.java:183)
        at io.appium.settings.LocationTracker.start(LocationTracker.java:159)
        at io.appium.settings.Settings.onCreate(Settings.java:47)
        at android.app.Activity.performCreate(Activity.java:6723)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2624)

**Comment by mykola-mokhnach** [comment]
Please use the most recent server version
