### ISSUE TITLE
Error: Failed to parse APK file: /data/local/tmp/LegadyWhatsApp.apk

### ISSUE THREAD

**Issue by N8-Yue** [appium/appium#14789]
I was trying with the program whatsapp key db extractor to extract the key, but it failed. Here is the log

=========================================================================
= This script will extract the WhatsApp Key file and DB on Android 4.0+ =
= You DO NOT need root for this to work but you DO need Java installed. =
= If your WhatsApp version is greater than 2.11.431 (most likely), then =
= a legacy version will be installed temporarily in order to get backup =
= permissions. You will NOT lose ANY data and your current version will =
= be restored at the end of the extraction process so try not to panic. =
= Script by: TripCode (Greets to all who visit: XDA Developers Forums). =
= Thanks to: dragomerlin for ABE and to Abinash Bishoyi for being cool. =
=         ###          Version: v4.7 (12/10/2016)          ###          =
=========================================================================

Please connect your Android device with USB Debugging enabled:

* daemon not running. starting it now on port 5037 *
* daemon started successfully *

WhatsApp 2.20.200.22 installed

Found legacy WhatsApp 2.11.431 in local folder

Backing up WhatsApp 2.20.200.22
remote object 'package:=' does not exist
Backup complete

Removing WhatsApp 2.20.200.22 skipping data
Success
Removal complete

Installing legacy WhatsApp 2.11.431
20 KB/s (251 bytes in 0.011s)
Error: Failed to parse APK file: /data/local/tmp/LegacyWhatsApp.apk

Exception occurred while executing:
java.lang.IllegalArgumentException: Error: Failed to parse APK file: /data/local/tmp/LegacyWhatsApp.apk
        at com.android.server.pm.PackageManagerShellCommand.setParamsSize(PackageManagerShellCommand.java:471)
        at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:1060)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:169)
        at android.os.ShellCommand.exec(ShellCommand.java:104)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:26762)
        at android.os.Binder.shellCommand(Binder.java:881)
        at android.os.Binder.onTransact(Binder.java:765)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:5433)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:5042)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
Caused by: android.content.pm.PackageParser$PackageParserException: Failed to parse /data/local/tmp/LegacyWhatsApp.apk
        at android.content.pm.PackageParser.parseApkLiteInner(PackageParser.java:1680)
        at android.content.pm.PackageParser.parseApkLite(PackageParser.java:1665)
        at com.android.server.pm.PackageManagerShellCommand.setParamsSize(PackageManagerShellCommand.java:464)
        ... 10 more
Install complete

Now unlock your device and confirm the backup operation.

Please enter your backup password (leave blank for none) and press Enter:

Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Don't know how to process version 5
        at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:420)
        at org.nick.abe.Main.main(Main.java:128)
        ... 5 more
Caused by: java.lang.IllegalArgumentException: Don't know how to process version 5
        at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:282)
        ... 6 more
bin\tar.exe: Cannot open tmp\whatsapp.tar: No such file or directory
bin\tar.exe: Error is not recoverable: exiting now
bin\tar.exe: Cannot open tmp\whatsapp.tar: No such file or directory
bin\tar.exe: Error is not recoverable: exiting now
bin\tar.exe: Cannot open tmp\whatsapp.tar: No such file or directory
bin\tar.exe: Error is not recoverable: exiting now
bin\tar.exe: Cannot open tmp\whatsapp.tar: No such file or directory
bin\tar.exe: Error is not recoverable: exiting now
bin\tar.exe: Cannot open tmp\whatsapp.tar: No such file or directory
bin\tar.exe: Error is not recoverable: exiting now

Cleaning up temporary files ...

Deleted file - E:\WhatsApp-Key-DB-Extractor-master\tmp\whatsapp.ab
Deleted file - E:\WhatsApp-Key-DB-Extractor-master\tmp\waplen.txt
Deleted file - E:\WhatsApp-Key-DB-Extractor-master\tmp\sdpath.txt
Deleted file - E:\WhatsApp-Key-DB-Extractor-master\tmp\wapath.txt
Deleted file - E:\WhatsApp-Key-DB-Extractor-master\tmp\wapver.txt
Deleted file - E:\WhatsApp-Key-DB-Extractor-master\tmp\sdkver.txt

Done

Downloading WhatsApp 2.20.200.22 to local folder
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

Operation complete

Press any key to continue . . .

**Comment by N8-Yue** [comment]
Now i get this : 
=========================================================================
= This script will extract the WhatsApp Key file and DB on Android 4.0+ =
= You DO NOT need root for this to work but you DO need Java installed. =
= If your WhatsApp version is greater than 2.11.431 (most likely), then =
= a legacy version will be installed temporarily in order to get backup =
= permissions. You will NOT lose ANY data and your current version will =
= be restored at the end of the extraction process so try not to panic. =
= Script by: TripCode (Greets to all who visit: XDA Developers Forums). =
= Thanks to: dragomerlin for ABE and to Abinash Bishoyi for being cool. =
=         ###          Version: v4.7 (12/10/2016)          ###          =
=========================================================================

Please connect your Android device with USB Debugging enabled:

* daemon not running. starting it now on port 5037 *
* daemon started successfully *

WhatsApp 2.20.200.22 installed

Downloading legacy WhatsApp 2.11.431 to local folder

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   251  100   251    0     0   3217      0 --:--:-- --:--:-- --:--:--  3217

Backing up WhatsApp 2.20.200.22
remote object 'tmp' does not exist
Backup complete

Removing WhatsApp 2.20.200.22 skipping data
Success
Removal complete

Installing legacy WhatsApp 2.11.431
40 KB/s (251 bytes in 0.005s)
Error: Failed to parse APK file: /data/local/tmp/LegacyWhatsApp.apk

Exception occurred while executing:
java.lang.IllegalArgumentException: Error: Failed to parse APK file: /data/local/tmp/LegacyWhatsApp.apk
        at com.android.server.pm.PackageManagerShellCommand.setParamsSize(PackageManagerShellCommand.java:471)
        at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:1060)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:169)
        at android.os.ShellCommand.exec(ShellCommand.java:104)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:26762)
        at android.os.Binder.shellCommand(Binder.java:881)
        at android.os.Binder.onTransact(Binder.java:765)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:5433)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:5042)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
Caused by: android.content.pm.PackageParser$PackageParserException: Failed to parse /data/local/tmp/LegacyWhatsApp.apk
        at android.content.pm.PackageParser.parseApkLiteInner(PackageParser.java:1680)
        at android.content.pm.PackageParser.parseApkLite(PackageParser.java:1665)
        at com.android.server.pm.PackageManagerShellCommand.setParamsSize(PackageManagerShellCommand.java:464)
        ... 10 more
Install complete

Now unlock your device and confirm the backup operation.

Please enter your backup password (leave blank for none) and press Enter:

Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Don't know how to process version 5
        at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:420)
        at org.nick.abe.Main.main(Main.java:128)
        ... 5 more
Caused by: java.lang.IllegalArgumentException: Don't know how to process version 5
        at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:282)
        ... 6 more

C:\Users\marce\Desktop\WhatsApp-Key-DB-Extractor-master\bin\tar.exe: Cannot open tmp\whatsapp.tar: No such file or directory
C:\Users\marce\Desktop\WhatsApp-Key-DB-Extractor-master\bin\tar.exe: Error is not recoverable: exiting now
C:\Users\marce\Desktop\WhatsApp-Key-DB-Extractor-master\bin\tar.exe: Cannot open tmp\whatsapp.tar: No such file or directory
C:\Users\marce\Desktop\WhatsApp-Key-DB-Extractor-master\bin\tar.exe: Error is not recoverable: exiting now
C:\Users\marce\Desktop\WhatsApp-Key-DB-Extractor-master\bin\tar.exe: Cannot open tmp\whatsapp.tar: No such file or directory
C:\Users\marce\Desktop\WhatsApp-Key-DB-Extractor-master\bin\tar.exe: Error is not recoverable: exiting now
C:\Users\marce\Desktop\WhatsApp-Key-DB-Extractor-master\bin\tar.exe: Cannot open tmp\whatsapp.tar: No such file or directory
C:\Users\marce\Desktop\WhatsApp-Key-DB-Extractor-master\bin\tar.exe: Error is not recoverable: exiting now
C:\Users\marce\Desktop\WhatsApp-Key-DB-Extractor-master\bin\tar.exe: Cannot open tmp\whatsapp.tar: No such file or directory
C:\Users\marce\Desktop\WhatsApp-Key-DB-Extractor-master\bin\tar.exe: Error is not recoverable: exiting now

Cleaning up temporary files ...
Done

Restoring WhatsApp 2.20.200.22
Missing APK file
Restore complete

Removing WhatsApp 2.20.200.22 temporary apk


Confirm
The item at C:\Users\marce\Desktop\WhatsApp-Key-DB-Extractor-master\tmp\ has children and the Recurse parameter was not
 specified. If you continue, all children will be removed with the item. Are you sure you want to continue?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): Y

Operation complete

Press any key to continue . . .

**Comment by KazuCocoa** [comment]
Please fill out the template you probably saw when you created this issue

**Comment by mykola-mokhnach** [comment]
I assume the issue has been posted into the wrong place. Closed as unrelated.
