### ISSUE TITLE
Terminate_app fails step after 500ms when the app terminates

### ISSUE THREAD

**Issue by Ashster808** [appium/appium#14818]
## The problem

I am currently creating an automation script for the feedback functionality in our native Android app. 

The original problem that I faced, occurred was when the script run more than once. During its run, it would follow a link to an email client where a draft email will be created. 

In our pipeline, the emulated device will be created specifically for the running of our Core scripts. Therefore It would not be signed into a Gmail account. So, when the link is followed. The Welcome to Gmail page in the Gmail app opens. Once this app has been opened though, it would continue to run in the background of the emulated device on every run until the app is closed manually or the device is changed/wiped. 

Which is fine most of the time unless the script needs to be debugged. As the link in the app would then not be able to launch the Gmail app correctly in the way that is expected in the script while the app is running in the background. Which is a bug in our app.

To work around this issue, I used the terminate_app command which does close the application. However, the script then fails at that step as an error occurs when this command is used when times out after 500ms.

As a workaround, I have used a try and except clause to catch the error. But I am not sure how we can be sure that the script has definitely closed the app.

I have also tried running the command with the timeout options added to the command. However, the command no longer closes the app when I do this.  

## Environment

* Appium version (or git revision) that exhibits the issue: Appium-windows-1.18.0-beta.1.exe
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Windows 10 Pro - Version 1909 - OS build 18363.1082 
* Node.js version (unless using Appium.app|exe): Appium.exe
* Npm or Yarn package manager: N/A
* Mobile platform/version under test: Android OS 9 
* Real device or emulator/simulator: Emulator - Android Studios - Pixel 2 - Android OS 9 
* Appium CLI or Appium.app|exe: Appium.exe

## Details

We use a Behave (BDD), Appium Python framework for executing our test scripts.

I am thinking that the 500ms timeout error is the part that is closing the app but I am not 100% sure.

## Appium Error

raise exception_class(message, screen, stacktrace)
      selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: 'com.google.android.gm' is still running after 500ms timeout

### Best way to reproduce this issue. Would be to have an application that can open a draft email in Gmail. Then attempt to close the Gmail app using the code below which is in python;

driver.terminate_app('com.google.android.gm')

### I have also tried;

driver.terminate_app('com.google.android.gm', 1)

**Comment by mykola-mokhnach** [comment]
Please provide the server log

I don't observe any Appium issues in the above description. The termination method must fail if the app remains opened.

**Comment by Ashster808** [comment]
Thank you for your response,

I have attached the log to this comment. I will attempt to resolve it with another termination method. The other method I used last week wouldn't work as it was only terminating our native app due to it being defined in the desired capabilities. However, something like driver.close_app('com.google.android.gm') might work better in this context.

[appium-server-logs.txt](https://github.com/appium/appium/files/5401221/appium-server-logs.txt)

**Comment by mykola-mokhnach** [comment]
I wouldn't recommend using close_app at all. It is slow and is affecting a normal session flow.

Also, it could be the app you are trying to terminate is restarted automatically. We, actually don't check if app has the same PID as before, but rather just verify the presence of its process.

**Comment by Ashster808** [comment]
Okay sure, thank you for your advice here. I think it might be best to keep the terminate_app method for now and have it run in a try and except clause. So, the error can be handled. As the Gmail application is getting terminated and we are not testing the Gmail application other than the link to it. By this stage in the script, we would have determined that our native app can launch the Gmail application. I suppose anything beyond that is then out of our scope.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue

**Comment by lucasdeeiroz** [comment]
I can't understand why this is not considered as an issue. It fails even with application being closed normally. Appium just seems to not recognize it under the 500ms timeout.

**Comment by itkhanz** [comment]
I am also facing this issue intermittently when executing tests on BrowserStack. 

When calling [mobile: terminateApp](https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#mobile-terminateapp) I get the same error that even though the application is apparently exited and no longer running.

`org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: 'APP_PACKAGE is still running after 500ms timeout`

Here are the server logs:

```
2024-09-04 12:52:14:677 - [HTTP] {"args":[{"appId":"com.app.package","bundleId":"com.app.package"}],"script":"mobile: terminateApp"}
2024-09-04 12:52:14:677 - [AndroidUiautomator2Driver@bc71 (fcc21f5d)] Calling AppiumDriver.execute() with args: ["mobile: terminateApp",[{"appId":"com.app.package","bundleId":"com.app.package"}],"fcc21f5d-8877-4395-b4e3-7c7a3f13b729"]
2024-09-04 12:52:14:677 - [AppiumDriver@34ce] Clearing new command timeout pre-emptively since plugin(s) will handle this command
2024-09-04 12:52:14:678 - [AppiumDriver@34ce] Plugins which can handle cmd 'execute': images
2024-09-04 12:52:14:678 - [AppiumDriver@34ce] Plugin images is now handling cmd 'execute'
2024-09-04 12:52:14:678 - [AppiumDriver@34ce] Executing default handling behavior for command 'execute'
2024-09-04 12:52:14:678 - [AndroidUiautomator2Driver@bc71 (fcc21f5d)] Executing native command 'mobile: terminateApp'
2024-09-04 12:52:14:679 - [AndroidUiautomator2Driver@bc71 (fcc21f5d)] Terminating 'com.app.package'
2024-09-04 12:52:14:680 - [ADB] Getting IDs of all 'com.app.package' processes
2024-09-04 12:52:14:680 - [ADB] Running '/usr/local/.browserstack/android-sdk/platform-tools/adb -P 5037 -s RZCX413KTZH shell pgrep -f \(\[\[:blank:\]\]\|\^\)com\.digitalchargingsolutions\.chargenow\.fleets\.integ\(\[\[:blank:\]\]\|\$\)'
2024-09-04 12:52:14:745 - [ADB] Running '/usr/local/.browserstack/android-sdk/platform-tools/adb -P 5037 -s RZCX413KTZH shell am force-stop com.app.package'
2024-09-04 12:52:14:829 - [AndroidUiautomator2Driver@bc71 (fcc21f5d)] Querying the state of 'com.app.package'
2024-09-04 12:52:14:829 - [ADB] Getting install status for com.app.package
2024-09-04 12:52:14:829 - [ADB] Running '/usr/local/.browserstack/android-sdk/platform-tools/adb -P 5037 -s RZCX413KTZH shell cmd package list packages'
2024-09-04 12:52:14:885 - [ADB] 'com.app.package' is installed
2024-09-04 12:52:14:885 - [ADB] Getting IDs of all 'com.app.package' processes
2024-09-04 12:52:14:885 - [ADB] Running '/usr/local/.browserstack/android-sdk/platform-tools/adb -P 5037 -s RZCX413KTZH shell pgrep -f \(\[\[:blank:\]\]\|\^\)com\.digitalchargingsolutions\.chargenow\.fleets\.integ\(\[\[:blank:\]\]\|\$\)'
2024-09-04 12:52:14:950 - [ADB] Running '/usr/local/.browserstack/android-sdk/platform-tools/adb -P 5037 -s RZCX413KTZH shell dumpsys window displays'
2024-09-04 12:52:15:092 - [AndroidUiautomator2Driver@bc71 (fcc21f5d)] Querying the state of 'com.app.package'
2024-09-04 12:52:15:092 - [ADB] Getting install status for com.app.package
2024-09-04 12:52:15:092 - [ADB] Running '/usr/local/.browserstack/android-sdk/platform-tools/adb -P 5037 -s RZCX413KTZH shell cmd package list packages'
2024-09-04 12:52:15:150 - [ADB] 'com.app.package' is installed
2024-09-04 12:52:15:150 - [ADB] Getting IDs of all 'com.app.package' processes
2024-09-04 12:52:15:151 - [ADB] Running '/usr/local/.browserstack/android-sdk/platform-tools/adb -P 5037 -s RZCX413KTZH shell pgrep -f \(\[\[:blank:\]\]\|\^\)com\.digitalchargingsolutions\.chargenow\.fleets\.integ\(\[\[:blank:\]\]\|\$\)'
2024-09-04 12:52:15:216 - [ADB] Running '/usr/local/.browserstack/android-sdk/platform-tools/adb -P 5037 -s RZCX413KTZH shell dumpsys window displays'
2024-09-04 12:52:15:330 - [AndroidUiautomator2Driver@bc71 (fcc21f5d)] Querying the state of 'com.app.package'
2024-09-04 12:52:15:330 - [ADB] Getting install status for com.app.package
2024-09-04 12:52:15:330 - [ADB] Running '/usr/local/.browserstack/android-sdk/platform-tools/adb -P 5037 -s RZCX413KTZH shell cmd package list packages'
2024-09-04 12:52:15:377 - [ADB] 'com.app.package' is installed
2024-09-04 12:52:15:377 - [ADB] Getting IDs of all 'com.app.package' processes
2024-09-04 12:52:15:377 - [ADB] Running '/usr/local/.browserstack/android-sdk/platform-tools/adb -P 5037 -s RZCX413KTZH shell pgrep -f \(\[\[:blank:\]\]\|\^\)com\.digitalchargingsolutions\.chargenow\.fleets\.integ\(\[\[:blank:\]\]\|\$\)'
2024-09-04 12:52:15:460 - [ADB] Running '/usr/local/.browserstack/android-sdk/platform-tools/adb -P 5037 -s RZCX413KTZH shell dumpsys window displays'
2024-09-04 12:52:15:499 - [AndroidUiautomator2Driver@bc71 (fcc21f5d)] 'com.app.package' is still running after 500ms timeout
2024-09-04 12:52:15:517 - [AndroidUiautomator2Driver@bc71 (fcc21f5d)] Encountered internal error running command: Error: 'com.app.package' is still running after 500ms timeout
2024-09-04 12:52:15:517 - [AndroidUiautomator2Driver@bc71 (fcc21f5d)]     at Object.wrappedLogger.errorWithException (/nix/store/9rsvl1x463mp6ffz8sdj4cj9lk2r3h4d-appium-2.6.0/packages/support/lib/logging.js:114:43)
2024-09-04 12:52:15:517 - [AndroidUiautomator2Driver@bc71 (fcc21f5d)]     at Object.wrappedLogger.errorAndThrow (/nix/store/9rsvl1x463mp6ffz8sdj4cj9lk2r3h4d-appium-2.6.0/packages/support/lib/logging.js:120:16)
2024-09-04 12:52:15:517 - [AndroidUiautomator2Driver@bc71 (fcc21f5d)]     at AndroidUiautomator2Driver.terminateApp (/nix/store/9rsvl1x463mp6ffz8sdj4cj9lk2r3h4d-appium-2.6.0/packages/appium/uiautomator2/3.5.2/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/app-management.js:202:14)
2024-09-04 12:52:15:517 - [AndroidUiautomator2Driver@bc71 (fcc21f5d)]     at AndroidUiautomator2Driver.mobileTerminateApp (/nix/store/9rsvl1x463mp6ffz8sdj4cj9lk2r3h4d-appium-2.6.0/packages/appium/uiautomator2/3.5.2/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/app-management.js:215:10)
2024-09-04 12:52:15:517 - [AndroidUiautomator2Driver@bc71 (fcc21f5d)]     at AndroidUiautomator2Driver.executeMobile (/nix/store/9rsvl1x463mp6ffz8sdj4cj9lk2r3h4d-appium-2.6.0/packages/appium/uiautomator2/3.5.2/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/execute.js:150:10)
2024-09-04 12:52:15:517 - [AndroidUiautomator2Driver@bc71 (fcc21f5d)]     at AndroidUiautomator2Driver.executeMobile (/nix/store/9rsvl1x463mp6ffz8sdj4cj9lk2r3h4d-appium-2.6.0/packages/appium/uiautomator2/3.5.2/node_modules/appium-uiautomator2-driver/lib/commands/execute.js:63:10)
2024-09-04 12:52:15:517 - [AndroidUiautomator2Driver@bc71 (fcc21f5d)]     at AndroidUiautomator2Driver.execute (/nix/store/9rsvl1x463mp6ffz8sdj4cj9lk2r3h4d-appium-2.6.0/packages/appium/uiautomator2/3.5.2/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/execute.js:115:12)
2024-09-04 12:52:15:531 - [HTTP] <-- POST /wd/hub/session/fcc21f5d-8877-4395-b4e3-7c7a3f13b729/execute/sync 500 854 ms - 700
2024-09-04 12:52:15:531 - [HTTP]
```

I would like to understand why this error is occuring in first place From server logs it seems that it says application is installed but even though I can see visually that application is not running (atleast in foreground) I still get this error intermittently.

For now, I have tried to enclose this terminateApp in try-catch block as follows and increased the timeout.
```
     /**
     * Terminate app (mobile: terminateApp)
     * @return True if the app has been successfully terminated.
     */
    @Override
    public boolean terminateApp() {
        log.info("Terminating the app with package {}",APP_PACKAGE);
        boolean isTerminated = false;
        try {
            isTerminated = driver.terminateApp(APP_PACKAGE, new AndroidTerminateApplicationOptions().withTimeout(Duration.ofMillis(5000)));
        } catch (WebDriverException e) {
            //handle exception
        }
        return isTerminated;
    }
```

**Comment by mykola-mokhnach** [comment]
@itkhanz Are you sure you use the most recent driver version? Recently I've added several improvements to verify the fact of process termination by ID rather than by bundle ID

**Comment by itkhanz** [comment]
> @itkhanz Are you sure you use the most recent driver version? Recently I've added several improvements to verify the fact of process termination by ID rather than by bundle ID

I am using Appium server 2.6.0 together with UiAutomator2 driver version 3.5.2 which is currently latest provided by [BrowserStack](https://www.browserstack.com/docs/app-automate/appium/set-up-tests/set-appium-version#appium-2x-versions) since we run tests on cloud provider's infrastructure. 

I will update here if I face this issue again after updating to newer driver version.

**Comment by du-pan** [comment]
I can see that this issue is new and a couple of us have same problem.
It's look I've solved this in the next way:
As documentation says [mobile: terminateApp](https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#mobile-terminateapp):

> The app state check can be skipped if the given timeout is lower or equal to zero since UIAutomator driver 2.9.0. The skip helps when you want to terminate the app process but do not want to check the process existence because the app under test may, for example, restart it automatically.

For me, setting timeout arg to 0 solves the problem, because right after the app termination our code will activate it again using: `mobile: activateApp`

Code in Java:

```
final Map<String, Object> appArgs = new HashMap<>();
appArgs.put("appId", "my.com.package"); // if tested on Android
appArgs.put("bundleId", "bundle.id"); // if tested on iOS
appArgs.put("timeout", 0);

appiumDriver.executeScript("mobile:terminateApp", appArgs)
appiumDriver.executeScript("mobile:activateApp", appArgs)
appiumDriver.getPageSource();
```
Hope this will help you guys!

**Comment by klauswuestefeld** [comment]
Hi @mykola-mokhnach , please reopen this issue. I have the exact same problem: using terminateApp with timeout 0 works and all other values I tried simply hang.

**Comment by klauswuestefeld** [comment]
"devDependencies": {
    "@wdio/appium-service": "^9.12.6",
    "@wdio/cli": "^9.16.2",
    "@wdio/junit-reporter": "^9.12.6",
    "@wdio/local-runner": "^9.12.7",
    "@wdio/mocha-framework": "^9.12.6",
    "@wdio/spec-reporter": "^9.12.6",
    "appium": "^2.11.5",
    "appium-uiautomator2-driver": "^4.2.3",
    "appium-xcuitest-driver": "^9.2.4"
  }

**Comment by mykola-mokhnach** [comment]
@klauswuestefeld Consider reporting a new issue and providing the required information to it.

**Comment by azaan-k18** [comment]
Hi if this helps anyone, the try catch method is best way to get a workaround this situation, because on cloud platforms some devices(especially samsung) restarts the app automatically therefore in my situation the app was in partial closed state and how i got error.
This is the java example code:

```
case "cloudTestAndroid": {
                Thread.sleep(1500);
                try {
                    boolean terminated = false;

                    try {
                        terminated = ((InteractsWithApps) driver).terminateApp(
                                "com.appbundleid.android",
                                new AndroidTerminateApplicationOptions().withTimeout(Duration.ofSeconds(5))
                        );
                    } catch (WebDriverException e) {
                        System.err.println("terminateApp threw exception: " + e.getMessage());
                    }

                    if (!terminated) {
                        System.err.println("terminateApp did not succeed, retrying with force-close logic...");
                        ((InteractsWithApps) driver).activateApp("com.appbundleid.android");
                        Thread.sleep(1500);
                        ((InteractsWithApps) driver).terminateApp("com.appbundleid.android");
                    }

                    Thread.sleep(1500);
                    ((InteractsWithApps) driver).activateApp("com.appbundleid.android");

                } catch (Exception e) {
                    throw new RuntimeException("App reset failed in cloudTestAndroid flow", e);
                }
                break;
            }
```
i am launching the app 2nd time because i want the app to be on homepage in every '@aftermethod'

**Comment by tking16** [comment]
@boundless018 I see, so it's a Samsung issue....

**Comment by Petrdontone** [comment]
I started getting this error after updating Appium to version 3+

UPD: It seems that when I set the timeout to 0, everything went away and the tests started running faster.
