### ISSUE TITLE
[XCUITest] Error: Xcode version '2.1'. Support for Xcode 2.1 is not supported. Please upgrade to version 7.3 or higher

### ISSUE THREAD

**Issue by fanzhiri** [appium/appium#14834]
[HTTP] <-- POST /wd/hub/session 500 250 ms - 237 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"automationName":"XCUITest","bundleId":"org.reactjs.native.example.ABChello","deviceName":"Slakomifi","platformName":"iOS","platformVersion":"14.0.1","udid":"15853ac68307240ff425885cd8a66613a43a88f9","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"automationName":"XCUITest","bundleId":"org.reactjs.native.example.ABChello","deviceName":"Slakomifi","platformName":"iOS","platformVersion":"14.0.1","udid":"15853ac68307240ff425885cd8a66613a43a88f9","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1603340900113 (12:28:20 GMT+0800 (CST))
[Appium] Creating new XCUITestDriver (v2.30.0) session
[Appium] Capabilities:
[Appium]   automationName: 'XCUITest'
[Appium]   bundleId: 'org.reactjs.native.example.ABChello'
[Appium]   deviceName: 'Slakomifi'
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '14.0.1'
[Appium]   udid: '15853ac68307240ff425885cd8a66613a43a88f9'
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true
[XCUITest] XCUITestDriver version: 2.30.0
[BaseDriver] Session created with session id: 526bc1e3-53ca-45c2-820d-2219eaae002a
[XCUITest] Error: Xcode version '2.1'. Support for Xcode 2.1 is not supported. Please upgrade to version 7.3 or higher
    at Object.wrappedLogger.errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:63:13)
    at getAndCheckXcodeVersion$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/utils.js:63:9)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)

**Comment by mykola-mokhnach** [comment]
You appium version is out of date. Please use the most recent one
