### ISSUE TITLE
我在用self.driver.get_performance_data('com.picc.nmms', 'cpuinfo', 5)报错 Error executing adbExec

### ISSUE THREAD

**Issue by tianyao1111** [appium/appium#14850]
## The problem
Execute self.driver.get_performance_data('com.picc.nmms','cpuinfo', 5) ，error: Error executing adbExec

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):1.18.0
* Desktop OS/version used to run Appium:win10
* Node.js version (unless using Appium.app|exe):v10.16.3
* Npm or Yarn package manager:6.9.0
* Mobile platform/version under test:android7.1
* Real device or emulator/simulator:simulator
* Appium CLI or Appium.app|exe:
* language：python

## Details

```
#coding=utf-8
import unittest
#将etong根目录加入环境变量
import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.realpath(__file__))))

from public.login import login
from public.get_driver import get_driver
from public.common2 import logcatlogger,when_error_screenshot
from public.excel_data import get_excel_data

from test_page.indexPage import indexPage
from test_page.TBCarRiskPage import TBCarRiskPage
from test_page.TBCarRiskInfoPage import TBCarRiskInfoPage
from test_page.TBCarRiskQuotePlanPage import TBCarRiskQuotePlanPage
from test_page.TBCarRiskComfirePage import TBCarRiskComfirePage
from test_page.TBCarRiskPayPage import TBCarRiskPayPage
from test_page.CarWXPage import CarWXPage
from test_page.CarPOSPage import CarPOSPage

from public.common import get_elements,is_newCar
from public.common1 import car_code,random_vin,car_engine_code
from public.MyTestCase import MyTestCase


class ET_TB_CX_case_01(MyTestCase):
	'''投保-车险-带牌新车-单商业全流程线上支付出单-个人'''

	def setUp(self):
		#获取本文件名
		self.name=os.path.split(__file__)[-1].split(".")[0]
		#获取数据文件路径
		path1=os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
		file=os.path.join(path1,r'test_data')
		file=os.path.join(file,r'TBCXData.xlsx')
		#获取数据
		self.data=get_excel_data(file,self.name)
		#生成driver
		self.driver=get_driver()

	@when_error_screenshot
	@logcatlogger
	def test_case_01(self):
		'''case 01'''
		# print(self.driver.get_performance_data_types())
		for i in range(3):
			print(self.driver.get_performance_data('com.picc.nmms', 'cpuinfo', 5))
		for i in range(3):
			print(self.driver.get_performance_data('com.picc.nmms', 'memoryinfo', 5))
		for i in range(3):
			print(self.driver.get_performance_data('com.picc.nmms', 'batteryinfo', 5))
	
	def tearDown(self):
		#退出
		self.driver.quit()

if __name__ == '__main__':
	from public.MyTestRunner import TextTestRunner1
	unittest.main(testRunner=TextTestRunner1)
```
hi!Mykola-Mokhnach,I got an error when executing self.driver.get_performance_data('com.picc.nmms','cpuinfo', 5), the error message is as follows：
```
E
======================================================================
ERROR: test_case_01 (__main__.ET_TB_CX_case_01)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\14221\Desktop\etong LJG\public\MyTestCase.py", line 23, in testPartExecutor
    yield
  File "C:\Users\14221\Desktop\etong LJG\public\MyTestCase.py", line 136, in run
    testMethod()
  File "C:\Users\14221\Desktop\etong LJG\public\common2.py", line 103, in wrapper
    func(self)
  File "C:\Users\14221\Desktop\etong LJG\public\common2.py", line 47, in wrapper
    func(self)
  File "ET_TB_CX_case_01.py", line 49, in test_case_01
    print(self.driver.get_performance_data('com.picc.nmms', 'cpuinfo', 5))
  File "C:\Users\14221\Anaconda3\lib\site-packages\appium\webdriver\extensions\android\performance.py", line 53, in get_performance_data
    return self.execute(Command.GET_PERFORMANCE_DATA, data)['value']
  File "C:\Users\14221\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\14221\Anaconda3\lib\site-packages\appium\webdriver\errorhandler.py", line 31, in check_response
    raise wde
  File "C:\Users\14221\Anaconda3\lib\site-packages\appium\webdriver\errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "C:\Users\14221\Anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\qianfeng\\learning\\software\\software\\adt-bundle-windows-x86_64\\sdk\\platform-tools\\adb.exe -P 5037 -s 127.0.0.1\:21533 shell dumpsys cpuinfo \| grep "'com.picc.nmms'"' exited with code 1'; Stderr: ''; Code: '1'


----------------------------------------------------------------------
Ran 1 test in 29.973s

FAILED (errors=1)

***Repl Closed***
```

## Link to Appium logs

When I started appium, it was set to only display the error log.
My start command：`appium --nodeconfig C:/Users/14221/Desktop/人保新架构/2.json --session-override  -p 4725 -bp 4726 -U  127.0.0.1:21533 --log-level error --relaxed-security`
When the above error occurs, appium does not have an error log printed.

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
We do not provide support in Chinese. Please translate or forward your request to a Chinese-speaking community.

**Comment by tianyao1111** [comment]
> We do not provide support in Chinese. Please translate or forward your request to a Chinese-speaking community.

I'm very sorry，I have used Google Translate to translate the question into English.

**Comment by mykola-mokhnach** [comment]
Please try appium@beta. This issue should be fixed there

**Comment by tianyao1111** [comment]
> 请尝试appium @ beta。这个问题应该在那里解决

3Q

**Comment by tianyao1111** [comment]
> > 请尝试appium @ beta。这个问题应该在那里解决
> 
> 第三季度



> > 请尝试appium @ beta。这个问题应该在那里解决
> 
> 第三季度

According to your suggestion, I used 1.19.0-beta.0, but it seems to be running unstable. Sometimes I can get it, sometimes I report an error
