### ISSUE TITLE
Intermittently an exception noticed while capturing screenshot of iOS App

### ISSUE THREAD

**Issue by narasimhanukala** [appium/appium#14853]
## The problem

While Capturing the Screenshot of our app screen in iPhone X(irrespective of device) an exception being thrown intermittently, tried with Jenkins integrated environment with allure report plugins configured also in eclipse.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.3
* Desktop OS/version used to run Appium: Mac OS Catalina 10.15.7
* Mobile platform/version under test:  iOS 14.1
* Real device or emulator/simulator: iPhone X 

## Details

During automation script there is a scenario where app screenshot to be generated, but intermittently gets the below exception... at
at org.openqa.selenium.remote.RemoteWebDriver.getScreenshotAs(RemoteWebDriver.java:295)

## Link to Appium logs
An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'MacBook-Pro-3.local', ip: '2401:4900:16b2:22d7:786a:9242:5ff5:a1aa%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.7', java.version: '1.8.0_181'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities {appPackage: com.weather.TWC, appium-version: 1.18.3, autoLaunch: true, automationName: XCUITest, browserName: , bundleId: com.weather.TWC, clearSystemFiles: true, databaseEnabled: false, device: iPhone, deviceName: =iPhone (14.1) [5261d156a27..., forceIphone: true, javascriptEnabled: true, launchTimeout: 60000, locationContextEnabled: false, networkConnectionEnabled: false, newCommandTimeout: 7200, noReset: true, platform: MAC, platformName: iOS, platformVersion: 14.1 (18A8395), realDeviceLogger: /Users/apple/node_modules/d..., takesScreenshot: true, udid: 5261d156a2753f975d3a4a2524a..., useNewWDA: true, wdaLocalPort: 9403, webStorageEnabled: false, xcodeConfigfile: /Applications/Appium 2.app/...}
Session ID: bdc9f8af-40e6-456b-9bf3-69f4a95d9cf5
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'MacBook-Pro-3.local', ip: '2401:4900:16b2:22d7:786a:9242:5ff5:a1aa%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.7', java.version: '1.8.0_181'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities {appPackage: com.weather.TWC, appium-version: 1.18.3, autoLaunch: true, automationName: XCUITest, browserName: , bundleId: com.weather.TWC, clearSystemFiles: true, databaseEnabled: false, device: iPhone, deviceName: =iPhone (14.1) [5261d156a27..., forceIphone: true, javascriptEnabled: true, launchTimeout: 60000, locationContextEnabled: false, networkConnectionEnabled: false, newCommandTimeout: 7200, noReset: true, platform: MAC, platformName: iOS, platformVersion: 14.1 (18A8395), realDeviceLogger: /Users/apple/node_modules/d..., takesScreenshot: true, udid: 5261d156a2753f975d3a4a2524a..., useNewWDA: true, wdaLocalPort: 9403, webStorageEnabled: false, xcodeConfigfile: /Applications/Appium 2.app/...}
Session ID: bdc9f8af-40e6-456b-9bf3-69f4a95d9cf5
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:45)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.getScreenshotAs(RemoteWebDriver.java:295)
	at com.Genaral.Driver.attachScreen(Driver.java:31)
	at com.Functions.Functions.enternewAddress(Functions.java:1527)
	at com.Functions.Smoke_Run.navigate_To_AllergyDetails_Page_from_lifestyle_card(Smoke_Run.java:2200)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

## Code To Reproduce Issue [ Good To Have ]
following is the method to capture screenshot
@Attachment("Screenshot")
    public static byte[] attachScreen() {
        logStep("Taking screenshot");
        return (((TakesScreenshot)Ad).getScreenshotAs(OutputType.BYTES));
       
    }

**Comment by mykola-mokhnach** [comment]
Please provide the server and device logs

**Comment by narasimhanukala** [comment]
> Please provide the server and device logs

how do i get them please?

**Comment by narasimhanukala** [comment]
Can someone respond me that how to get the device and server logs?

**Comment by mykola-mokhnach** [comment]
Please use Appium forum to ask questions. Unfortunately there is nothing to do on the issue without detailed logs
