### ISSUE TITLE
Switch to parent frame is not working in mobile safari(IOS)

### ISSUE THREAD

**Issue by tmshft** [appium/appium#14882]
## The problem

I try to switch to parent frame.
but it failed.

## Environment

* Java: AdoptOpenJDK 11.x
* Appium version : 1.17.1(SauceLabs)
* iOS version : 13.4(SauceLabs)
* Desktop OS/version: Windows10 
* Real device or emulator/simulator: iPhone XS Simulator
* Appium CLI

## Details(Selenium Log)

Error communicating with the remote browser. It may have died.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'S-NPC-1519', ip: 'x.x.x.x', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_252'
Driver info: driver.version: IOSDriver
Capabilities {autoAcceptAlerts: true, autoDismissAlerts: true, automationName: XCUITest, backendRetries: 4, bootstrapPath: /Volumes/Sauce/wda/wda-v1.1..., browserName: Safari, capabilities.path: capabilities-ios-web-sauce.yml, databaseEnabled: false, derivedDataPath: /Volumes/Sauce/wda/wda-v1.1..., deviceName: iPhone XS, eventTimings: true, hasMetadata: true, iosSimulatorLogsPredicate: --predicate 'process != "lo..., javascriptEnabled: true, keepKeyChains: true, launchTimeout: 180000, locationContextEnabled: false, maxTypingFrequency: 8, networkConnectionEnabled: false, newCommandTimeout: 1000, noReset: true, orientation: PORTRAIT, platform: MAC, platformName: iOS, platformVersion: 13.4, preventWDAAttachments: true, resetKeyboard: true, safariAllowPopups: true, showIOSLog: false, startIWDP: true, takesScreenshot: true, udid: 3049B218-27DC-4891-A6FF-CDF..., unicodeKeyboard: true, usePrebuiltWDA: true, webStorageEnabled: false, webdriver.remote.quietExceptions: false, webdriver.remote.sessionid: zzz...}
Session ID: zzz
org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.

## Link to Appium logs

```log
2020-11-12 14:50:24:485 - [HTTP] --> POST /wd/hub/session/67c9ff37-cf68-47e4-bfff-0ac4b04c1660/frame/parent
2020-11-12 14:50:24:485 - [HTTP] {}
2020-11-12 14:50:24:492 - [debug] [MJSONWP (67c9ff37)] Encountered internal error running command: NotImplementedError: Method is not implemented
2020-11-12 14:50:24:492 - [debug] [MJSONWP (67c9ff37)]     at asyncHandler (/Volumes/Sauce/selenium/appium-v1.17.1-patched/node_modules/appium-base-driver/lib/protocol/protocol.js:272:15)
2020-11-12 14:50:24:492 - [debug] [MJSONWP (67c9ff37)]     at /Volumes/Sauce/selenium/appium-v1.17.1-patched/node_modules/appium-base-driver/lib/protocol/protocol.js:447:15
2020-11-12 14:50:24:492 - [debug] [MJSONWP (67c9ff37)]     at Layer.handle [as handle_request] (/Volumes/Sauce/selenium/appium-v1.17.1-patched/node_modules/express/lib/router/layer.js:95:5)
2020-11-12 14:50:24:492 - [debug] [MJSONWP (67c9ff37)]     at next (/Volumes/Sauce/selenium/appium-v1.17.1-patched/node_modules/express/lib/router/route.js:137:13)
2020-11-12 14:50:24:493 - [debug] [MJSONWP (67c9ff37)]     at Route.dispatch (/Volumes/Sauce/selenium/appium-v1.17.1-patched/node_modules/express/lib/router/route.js:112:3)
2020-11-12 14:50:24:493 - [debug] [MJSONWP (67c9ff37)]     at Layer.handle [as handle_request] (/Volumes/Sauce/selenium/appium-v1.17.1-patched/node_modules/express/lib/router/layer.js:95:5)
2020-11-12 14:50:24:493 - [debug] [MJSONWP (67c9ff37)]     at /Volumes/Sauce/selenium/appium-v1.17.1-patched/node_modules/express/lib/router/index.js:281:22
2020-11-12 14:50:24:493 - [debug] [MJSONWP (67c9ff37)]     at param (/Volumes/Sauce/selenium/appium-v1.17.1-patched/node_modules/express/lib/router/index.js:354:14)
2020-11-12 14:50:24:493 - [debug] [MJSONWP (67c9ff37)]     at param (/Volumes/Sauce/selenium/appium-v1.17.1-patched/node_modules/express/lib/router/index.js:365:14)
2020-11-12 14:50:24:493 - [debug] [MJSONWP (67c9ff37)]     at Function.process_params (/Volumes/Sauce/selenium/appium-v1.17.1-patched/node_modules/express/lib/router/index.js:410:3)
2020-11-12 14:50:24:494 - [debug] [MJSONWP (67c9ff37)]     at next (/Volumes/Sauce/selenium/appium-v1.17.1-patched/node_modules/express/lib/router/index.js:275:10)
2020-11-12 14:50:24:494 - [debug] [MJSONWP (67c9ff37)]     at logger (/Volumes/Sauce/selenium/appium-v1.17.1-patched/node_modules/morgan/index.js:144:5)
2020-11-12 14:50:24:494 - [debug] [MJSONWP (67c9ff37)]     at Layer.handle [as handle_request] (/Volumes/Sauce/selenium/appium-v1.17.1-patched/node_modules/express/lib/router/layer.js:95:5)
2020-11-12 14:50:24:494 - [debug] [MJSONWP (67c9ff37)]     at trim_prefix (/Volumes/Sauce/selenium/appium-v1.17.1-patched/node_modules/express/lib/router/index.js:317:13)
2020-11-12 14:50:24:494 - [debug] [MJSONWP (67c9ff37)]     at /Volumes/Sauce/selenium/appium-v1.17.1-patched/node_modules/express/lib/router/index.js:284:7
2020-11-12 14:50:24:494 - [debug] [MJSONWP (67c9ff37)]     at Function.process_params (/Volumes/Sauce/selenium/appium-v1.17.1-patched/node_modules/express/lib/router/index.js:335:12)
2020-11-12 14:50:24:494 - [debug] [MJSONWP (67c9ff37)]     at next (/Volumes/Sauce/selenium/appium-v1.17.1-patched/node_modules/express/lib/router/index.js:275:10)
2020-11-12 14:50:24:495 - [debug] [MJSONWP (67c9ff37)]     at /Volumes/Sauce/selenium/appium-v1.17.1-patched/node_modules/body-parser/lib/read.js:130:5
2020-11-12 14:50:24:495 - [debug] [MJSONWP (67c9ff37)]     at invokeCallback (/Volumes/Sauce/selenium/appium-v1.17.1-patched/node_modules/raw-body/index.js:224:16)
2020-11-12 14:50:24:495 - [debug] [MJSONWP (67c9ff37)]     at done (/Volumes/Sauce/selenium/appium-v1.17.1-patched/node_modules/raw-body/index.js:213:7)
2020-11-12 14:50:24:495 - [debug] [MJSONWP (67c9ff37)]     at IncomingMessage.onEnd (/Volumes/Sauce/selenium/appium-v1.17.1-patched/node_modules/raw-body/index.js:273:7)
2020-11-12 14:50:24:495 - [debug] [MJSONWP (67c9ff37)]     at IncomingMessage.emit (events.js:327:22)
2020-11-12 14:50:24:497 - [HTTP] <-- POST /wd/hub/session/67c9ff37-cf68-47e4-bfff-0ac4b04c1660/frame/parent 501 11 ms - 113
```

## Code To Reproduce Issue [ Good To Have ]

```java
// try to switch nested frame.
WebDriverRunner.getWebDriver().switchTo().frame(0); // succeed
WebDriverRunner.getWebDriver().switchTo().frame(0); // succeed
// try to switch parent frame
WebDriverRunner.getWebDriver().switchTo().parentFrame(); // failed
```

**Comment by mykola-mokhnach** [comment]
The error is expected since such method is not implemented for mobile Safari

**Comment by tmshft** [comment]
thank you @mykola-mokhnach 
So, I'll wait with baited breath for Apple's response.

**Comment by mykola-mokhnach** [comment]
The remote debugger interface is maintained by Appium team. Although, we've recently added a separate Safari driver for Safari-only automation scenarios: https://github.com/appium/appium-safari-driver
It is going to be available as soon as the next beta version is published

**Comment by EgorPatutkin** [comment]
According to doc here https://webdriver.io/docs/api/webdriver/#switchtoframe

You can use `browser.switchToFrame(null)`

That helped me

**Comment by jlipps** [comment]
thanks @EgorPatutkin !
