### ISSUE TITLE
Getting `Method has not yet been implemented` while AppiumDriver.performActions()

### ISSUE THREAD

**Issue by pranay2611** [appium/appium#14907]
## The problem

Using UiAutomator1 for Os5 simulator with appium 1.19.0
and getting `Method has not yet been implemented` while AppiumDriver.performActions()

## Environment

* Appium version (or git revision) that exhibits the issue: 1.19.0 with UiAutomator1
* Android OS version : 5.1.1 and api level 22
* Real device or emulator/simulator: simulator

## Link to Appium logs

`2020-11-24 10:45:31:745 [HTTP] {"actions":[{"type":"key","actions":[{"type":"keyDown","value":"8"},{"type":"keyUp","value":"8"},{"type":"keyDown","value":"7"},{"type":"keyUp","value":"7"},{"type":"keyDown","value":"5"},{"type":"keyUp","value":"5"},{"type":"keyDown","value":"5"},{"type":"keyUp","value":"5"},{"type":"keyDown","value":"5"},{"type":"keyUp","value":"5"},{"type":"keyDown","value":"1"},{"type":"keyUp","value":"1"},{"type":"keyDown","value":"0"},{"type":"keyUp","value":"0"},{"type":"keyDown","value":"6"},{"type":"keyUp","value":"6"},{"type":"keyDown","value":"5"},{"type":"keyUp","value":"5"},{"type":"keyDown","value":"4"},{"type":"keyUp","value":"4"}],"id":"keyboard"}]}
2020-11-24 10:45:31:746 [W3C (4d9fe170)] Calling AppiumDriver.performActions() with args: [[{"type":"key","actions":[{"type":"keyDown","value":"8"},{"type":"keyUp","value":"8"},{"type":"keyDown","value":"7"},{"type":"keyUp","value":"7"},{"type":"keyDown","value":"5"},{"type":"keyUp","value":"5"},{"type":"keyDown","value":"5"},{"type":"keyUp","value":"5"},{"type":"keyDown","value":"5"},{"type":"keyUp","value":"5"},{"type":"keyDown","value":"1"},{"type":"keyUp","value":"1"},{"type":"keyDown","value":"0"},{"type":"keyUp","value":"0"},{"type":"keyDown","value":"6"},{"type":"keyUp","value":"6"},{"type":"keyDown","value":"5"},{"type":"keyUp","value":"5"},{"type":"keyDown","value":"4"},{"type":"keyUp","value":"4"}],"id":"keyboard"}],"4d9fe170-f90a-4125-a1fa-b2f15f4f5652"]
2020-11-24 10:45:31:810 [W3C (4d9fe170)] Encountered internal error running command: NotYetImplementedError: Method has not yet been implemented
2020-11-24 10:45:31:810 [W3C (4d9fe170)]     at AndroidDriver.executeCommand (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:327:13)
2020-11-24 10:45:31:810 [W3C (4d9fe170)]     at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/lib/appium.js:532:36)
2020-11-24 10:45:31:810 [W3C (4d9fe170)]     at runMicrotasks (<anonymous>)
2020-11-24 10:45:31:810 [W3C (4d9fe170)]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
2020-11-24 10:45:31:810 [W3C (4d9fe170)]     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:300:21)`

**Comment by mykola-mokhnach** [comment]
This is expected. UiAutomator1 driver is obsolete and does not implement/support W3C-specific endpoints.

**Comment by pranay2611** [comment]
@mykola-mokhnach 
i tried below piece of code

`TouchAction tAction = new TouchAction(driver);
        MobileElement element = driver.findElement(By.id("iv_welcome_image"));
        tAction.longPress(PointOption.point(element.getCenter().getX(), element.getCenter().getY())).waitAction(WaitOptions.waitOptions(Duration.ofMillis(200L))).perform();`

appium log

`[W3C (a95a15db)] Calling AppiumDriver.performTouch() with args: [[{"action":"longPress","options":{"x":540,"y":856}},{"action":"wait","options":{"ms":200}}],"a95a15db-dcba-4437-91ad-3b989635c3d7"]`

It worked properly with UiAutomator1 and appium 1.19.0 & os5.0 simulator

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
