### ISSUE TITLE
appium-windows-driver can not detect WinAppDriver installed on custom location

### ISSUE THREAD

**Issue by douniwan5788** [appium/appium#14943]
## The problem

appium-windows-driver can not detect WinAppDriver installed on Driver D:\

## Environment

Appium v1.19.1
appium-windows-driver@1.17.0

## Details

https://github.com/appium/appium-windows-driver/blob/eaabedb3c0bccb0376693baa33d376c5d89e9ea6/lib/installer.js#L14-L16

## Link to Appium logs
server:
```
[debug] [WinAppDriver] Deleting WinAppDriver session
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1607658904898 (11:55:04 GMT+0800 (中国标准时间))
[debug] [W3C] Encountered internal error running command: Error: Could not verify WinAppDriver install; re-run install
[debug] [W3C]     at WinAppDriver.start (C:\Users\<username>\AppData\Roaming\npm\node_modules\appium\node_modules\appium-windows-driver\lib\winappdriver.js:37:13)
[debug] [W3C]     at WindowsDriver.startWinAppDriverSession (C:\Users\<username>\AppData\Roaming\npm\node_modules\appium\node_modules\appium-windows-driver\lib\driver.js:73:5)
[debug] [W3C]     at WindowsDriver.createSession (C:\Users\<username>\AppData\Roaming\npm\node_modules\appium\node_modules\appium-windows-driver\lib\driver.js:46:7)
[debug] [W3C]     at AppiumDriver.createSession (C:\Users\<username>\AppData\Roaming\npm\node_modules\appium\lib\appium.js:358:35)
[debug] [W3C] Destroying socket connection
```
client:
```
C:\Program Files\nodejs\node.exe .\index.js
Could not load source map from acorn.js.map
2020-12-11T03:59:55.678Z INFO webdriverio: Initiate new session using the webdriver protocol
node_modules/@wdio/logger/build/node.js:76
2020-12-11T03:59:55.681Z INFO webdriver: [POST] http://localhost:4723/wd/hub/session
node_modules/@wdio/logger/build/node.js:76
2020-12-11T03:59:55.682Z INFO webdriver: DATA {capabilities: {…}, desiredCapabilities: {…}}
node_modules/@wdio/logger/build/node.js:76
2020-12-11T03:59:56.096Z DEBUG webdriver: request failed due to response error: unknown error
node_modules/@wdio/logger/build/node.js:76
2020-12-11T03:59:56.096Z WARN webdriver: Request failed with status 500 due to An unknown server-side error occurred while processing the command. Original error: Could not verify WinAppDriver install; re-run install
node_modules/@wdio/logger/build/node.js:76
2020-12-11T03:59:56.097Z INFO webdriver: Retrying 1/3
node_modules/@wdio/logger/build/node.js:76
2020-12-11T03:59:56.097Z INFO webdriver: [POST] http://localhost:4723/wd/hub/session
node_modules/@wdio/logger/build/node.js:76
2020-12-11T03:59:56.098Z INFO webdriver: DATA {capabilities: {…}, desiredCapabilities: {…}}

```

and please update to WinAppDriver v1.2.1

**Comment by mykola-mokhnach** [comment]
Unfortunately it is not possible to implement that, because the original installer from Microsoft does not store the install location anywhere (in general the package is not shown in the list of apps to uninstall). Please create an improvement request to the original WinAppDriver repository to add this info into the MSI install script.
