### ISSUE TITLE
socket hangup error for react native app (android)

### ISSUE THREAD

**Issue by GSalamancaLM** [appium/appium#14968]
Getting this error consistently for a react-native (v0.63) application using appium, eclipse, testng, 

node version v12.13.1, 
appium-desktop version 1.19.0-beta.0 (was also experiencing this using 1.18.x) 
have experienced this on both on mac and windows 
using emulator Pixel 3/ platform version 10 but also on real devices:

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '1.8.0_232'
Driver info: io.appium.java_client.AppiumDriver
Capabilities {appActivity: com.fg.alpine.MainActivity, appPackage: com.fg.alpine, automationName: UiAutomator2, browserName: , databaseEnabled: false, desired: {appActivity: com.fg.alpine.MainActivity, appPackage: com.fg.alpine, automationName: UiAutomator2, browserName: , deviceName: Pixel3, newCommandTimeout: 600, platformName: android, platformVersion: 10, resetKeyboard: true, systemPort: 8201, unicodeKeyboard: true}, deviceApiLevel: 29, deviceManufacturer: Google, deviceModel: Android SDK built for x86, deviceName: emulator-5554, deviceScreenDensity: 440, deviceScreenSize: 1080x2160, deviceUDID: emulator-5554, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, newCommandTimeout: 600, pixelRatio: 2.75, platform: LINUX, platformName: android, platformVersion: 10, resetKeyboard: true, statBarHeight: 66, systemPort: 8201, takesScreenshot: true, unicodeKeyboard: true, viewportRect: {height: 1962, left: 0, top: 66, width: 1080}, warnings: {}, webStorageEnabled: false}
Session ID: e378bb3b-3e13-4bb0-9873-a07bf99c14ac
*** Element info: {Using=accessibility id, value=Step 4 Section 4 bankRoutingNumber}
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:353)
at io.appium.java_client.DefaultGenericMobileDriver.findElements(DefaultGenericMobileDriver.java:53)
at io.appium.java_client.AppiumDriver.findElements(AppiumDriver.java:176)
at io.appium.java_client.FindsByAccessibilityId.findElementsByAccessibilityId(FindsByAccessibilityId.java:50)
at io.appium.java_client.AppiumDriver.findElementsByAccessibilityId(AppiumDriver.java:214)
at com.fg.alpine.app.lib.ScreenHelper.waitForStringValue(ScreenHelper.java:172)
at com.fg.alpine.app.lib.ScreenHelper.waitForStringValue(ScreenHelper.java:119)
at com.fg.alpine.app.lib.FlowScreen.getField(FlowScreen.java:57)
at com.fg.alpine.app.lib.FlowScreen.setValueAndCloseKeys(FlowScreen.java:141)
at com.fg.alpine.app.lib.FlowScreen.addBankDetails(FlowScreen.java:312)
at com.fg.alpine.app.lib.FlowScreen.addOrLinkBankAccount(FlowScreen.java:300)
at com.fg.alpine.app.screen.AOScreen4.completeStep4(AOScreen4.java:91)
at com.fg.alpine.app.lib.AppFunctions.create529Account(AppFunctions.java:105)
at com.fg.alpine.app.BankAccountFundFact.BankManagement.bankManager(BankManagement.java:75)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)Warning:

**Comment by mykola-mokhnach** [comment]
Please fill out the issue reporting template properly and provide the server log and the logcat output

**Comment by mykola-mokhnach** [comment]
Closed because of no response
