### ISSUE TITLE
After updating to appium 1.20.0 UnknownError happens on every test run

### ISSUE THREAD

**Issue by aguspeq** [appium/appium#15008]
## The problem

Since I updated to appium 1.20.0, all my android tests trigger this error 
```UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: timeout of 240000ms exceeded```

## Environment

* Appium version: 1.20.0
* Last Appium version that did not exhibit the issue: 1.19.1
* Desktop OS/version used to run Appium: macOs catalina 10.15.7
* Node.js version: v14.4.0
* Npm: 6.14.4
* Mobile platform/version under test: Android API 30 x86
* emulator/simulator: Pixel 3
* Appium CLI
* Capabilities: 
```
  automationName: UiAutomator2
  platformName: Android
  deviceName: Pixel_3_API_30
  app: app_path
  appPackage: app_package
  appActivity: app_main_activity_name
  udid: "emulator-5554"
  autoGrantPermissions: true
  newCommandTimeout: 60
```
## Link to Appium and ADB logs:

Appium logs: https://gist.github.com/aguspeq/7517cd1b2a16033f7eaf135b43d0d649
ADB logs: https://gist.github.com/aguspeq/070454971b0d1bb80ff0878d1cdade7c

## Code To Reproduce Issue 

The code is written in ruby, it happens when I call this method and it cannot find the element:
```driver.find_elements(accessibility_id: 'log_ind')```

## Notes 

- I have not modified my code before this issue happened
- I just ran my whole suite after updating to 1.20.0
- All my iOS tests works fine
- I have tried with Android API 8.1 x 86 on a Nexus 6p emulator and the issue is the same

**Comment by KazuCocoa** [comment]
Could you append around log for the logcat and run with `--log-timestamp` for appium server to check timeline?  

For logcat:
Probably like `xxxx /io.appium.uiautomator2.server I/appium: channel read: POST /wd/hub/session/yyyyy/element` log exists in the logcat after getting a request.

**Comment by aguspeq** [comment]
I have updated the appium logs with timestamp and abd logs, thanks for looking into it :)

**Comment by mykola-mokhnach** [comment]
It looks like the UIA2 server has been stopped by Android OS due to app under test crash:

```
01-10 12:57:07.215   565   603 W WindowManager: Failed to deliver inset state change to w=Window{b93f72d u0 ds.danskespil.lotto.staging/ds.danskespil.lotto.MainActivity}
01-10 12:57:07.215   565   603 W WindowManager: android.os.DeadObjectException
01-10 12:57:07.215   565   603 W WindowManager: 	at android.os.BinderProxy.transactNative(Native Method)
01-10 12:57:07.215   565   603 W WindowManager: 	at android.os.BinderProxy.transact(BinderProxy.java:540)
01-10 12:57:07.215   565   603 W WindowManager: 	at android.view.IWindow$Stub$Proxy.insetsControlChanged(IWindow.java:765)
01-10 12:57:07.215   565   603 W WindowManager: 	at com.android.server.wm.WindowState.notifyInsetsControlChanged(WindowState.java:3582)
01-10 12:57:07.215   565   603 W WindowManager: 	at com.android.server.wm.InsetsStateController.lambda$notifyPendingInsetsControlChanged$4$InsetsStateController(InsetsStateController.java:428)
01-10 12:57:07.215   565   603 W WindowManager: 	at com.android.server.wm.-$$Lambda$InsetsStateController$-1iOXDf-1s3wDHcMIHBKNk6MS3I.run(Unknown Source:2)
01-10 12:57:07.215   565   603 W WindowManager: 	at com.android.server.wm.WindowAnimator.executeAfterPrepareSurfacesRunnables(WindowAnimator.java:323)
01-10 12:57:07.215   565   603 W WindowManager: 	at com.android.server.wm.WindowAnimator.animate(WindowAnimator.java:204)
01-10 12:57:07.215   565   603 W WindowManager: 	at com.android.server.wm.WindowAnimator.lambda$new$1$WindowAnimator(WindowAnimator.java:100)
01-10 12:57:07.215   565   603 W WindowManager: 	at com.android.server.wm.-$$Lambda$WindowAnimator$ddXU8gK8rmDqri0OZVMNa3Y4GHk.doFrame(Unknown Source:2)
01-10 12:57:07.215   565   603 W WindowManager: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
01-10 12:57:07.215   565   603 W WindowManager: 	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
01-10 12:57:07.215   565   603 W WindowManager: 	at android.view.Choreographer.doFrame(Choreographer.java:727)
01-10 12:57:07.215   565   603 W WindowManager: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
01-10 12:57:07.215   565   603 W WindowManager: 	at android.os.Handler.handleCallback(Handler.java:938)
01-10 12:57:07.215   565   603 W WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-10 12:57:07.215   565   603 W WindowManager: 	at android.os.Looper.loop(Looper.java:223)
01-10 12:57:07.215   565   603 W WindowManager: 	at android.os.HandlerThread.run(HandlerThread.java:67)
01-10 12:57:07.215   565   603 W WindowManager: 	at com.android.server.ServiceThread.run(ServiceThread.java:44)
01-10 12:57:07.215   565   598 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ LISTEN id=660, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&FOREGROUND Uid: 10155 AdministratorUids: [] RequestorUid: 10155 RequestorPackageName: ds.danskespil.lotto.staging] ], android.os.BinderProxy@ff4a8e8)
01-10 12:57:07.215   565  1771 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ TRACK_DEFAULT id=659, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10155 AdministratorUids: [] RequestorUid: 10155 RequestorPackageName: ds.danskespil.lotto.staging] ], android.os.BinderProxy@212cb01)
01-10 12:57:07.217   565  2652 W WindowManager: Cannot find window which accessibility connection is added to
01-10 12:57:07.230   565  1776 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ TRACK_DEFAULT id=661, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10155 AdministratorUids: [] RequestorUid: 10155 RequestorPackageName: ds.danskespil.lotto.staging] ], android.os.BinderProxy@c60163d)
01-10 12:57:07.231   565   732 D ConnectivityService: releasing NetworkRequest [ TRACK_DEFAULT id=661, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10155 AdministratorUids: [] RequestorUid: 10155 RequestorPackageName: ds.danskespil.lotto.staging] ] (release request)
01-10 12:57:07.233   565  1736 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ LISTEN id=658, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN&FOREGROUND Uid: 10155 AdministratorUids: [] RequestorUid: 10155 RequestorPackageName: ds.danskespil.lotto.staging] ], android.os.BinderProxy@bde3e32)
01-10 12:57:07.240   565   732 D ConnectivityService: releasing NetworkRequest [ TRACK_DEFAULT id=659, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10155 AdministratorUids: [] RequestorUid: 10155 RequestorPackageName: ds.danskespil.lotto.staging] ] (release request)
01-10 12:57:07.241   465 32008 D NuPlayerDriver: reset(0xea6c0130) at state 2
01-10 12:57:07.243   565   602 W ActivityManager: setHasOverlayUi called on unknown pid: 24968
01-10 12:57:07.244   465  3725 D NuPlayerDriver: reset(0xea6c1720) at state 2
01-10 12:57:07.244   465 25412 D NuPlayerDriver: notifyResetComplete(0xea6c0130)
01-10 12:57:07.244   465 25415 D NuPlayerDriver: notifyResetComplete(0xea6c1720)
01-10 12:57:07.244   357   357 I Zygote  : Process 24968 exited due to signal 9 (Killed)
01-10 12:57:07.245   465 32008 D SurfaceUtils: disconnecting from surface 0xe44c4ba8, reason disconnectNativeWindow
01-10 12:57:07.246   465 32008 E SurfaceUtils: Failed to disconnect from surface 0xe44c4ba8, err -32
01-10 12:57:07.247   465  3725 D SurfaceUtils: disconnecting from surface 0xe44c3278, reason disconnectNativeWindow
01-10 12:57:07.247   465 32008 W MediaPlayerService: nativeWindowDisconnect returned an error: Broken pipe (-32)
01-10 12:57:07.249   465  3725 E SurfaceUtils: Failed to disconnect from surface 0xe44c3278, err -32
01-10 12:57:07.249   465  3725 W MediaPlayerService: nativeWindowDisconnect returned an error: Broken pipe (-32)
01-10 12:57:07.249   465   968 D NuPlayerDriver: reset(0xea6c0910) at state 2
01-10 12:57:07.250   465 25419 D NuPlayerDriver: notifyResetComplete(0xea6c0910)
01-10 12:57:07.250   465   968 D SurfaceUtils: disconnecting from surface 0xe44c0018, reason disconnectNativeWindow
01-10 12:57:07.255   565   610 I libprocessgroup: Successfully killed process cgroup uid 10155 pid 24968 in 269ms
01-10 12:57:07.261   465   968 E SurfaceUtils: Failed to disconnect from surface 0xe44c0018, err -32
01-10 12:57:07.261   465   968 W MediaPlayerService: nativeWindowDisconnect returned an error: Broken pipe (-32)
01-10 12:57:07.264   565   610 I libprocessgroup: Successfully killed process cgroup uid 99132 pid 25111 in 0ms
01-10 12:57:07.276  1113  1113 D Telephony: isEmergencyPreferredAccount: subId=1, activeData=1
01-10 12:57:07.277  1113  1113 D Telephony: isEmergencyPreferredAccount: Device does not require preference.
01-10 12:57:07.280   465   968 D NuPlayerDriver: reset(0xea6c1570) at state 2
01-10 12:57:07.281   465 25423 D NuPlayerDriver: notifyResetComplete(0xea6c1570)
01-10 12:57:07.282   465   968 D SurfaceUtils: disconnecting from surface 0xe44c7e08, reason disconnectNativeWindow
01-10 12:57:07.283   795   795 V KeyguardUpdateMonitor: onSubscriptionInfoChanged()
01-10 12:57:07.287   465   968 E SurfaceUtils: Failed to disconnect from surface 0xe44c7e08, err -32
01-10 12:57:07.287   465   968 W MediaPlayerService: nativeWindowDisconnect returned an error: Broken pipe (-32)
01-10 12:57:07.291 26260 26260 W ThreadPoolDumper: Queue length for executor EventBus is now 11. Perhaps some tasks are too long, or the pool is too small.
01-10 12:57:07.292  1113  1113 D Telephony: isEmergencyPreferredAccount: subId=1, activeData=1
01-10 12:57:07.292  1113  1113 D Telephony: isEmergencyPreferredAccount: Device does not require preference.
01-10 12:57:07.195   266   266 W Binder:266_3: type=1400 audit(0.0:21441): avc: denied { read } for name="wakeup34" dev="sysfs" ino=17466 scontext=u:r:system_suspend:s0 tcontext=u:object_r:sysfs:s0 tclass=dir permissive=0
01-10 12:57:07.315   795   795 V KeyguardUpdateMonitor: SubInfo:{id=1 iccId=890141032[****] simSlotIndex=0 carrierId=1 displayName=T-Mobile carrierName=T-Mobile nameSource=3 iconTint=-16746133 number=[****] dataRoaming=0 iconBitmap=android.graphics.Bitmap@5840911 mcc=310 mnc=260 countryIso=us isEmbedded=false nativeAccessRules=null cardString=890141032[****] cardId=-1 isOpportunistic=false groupUUID=null isGroupDisabled=false profileClass=-1 ehplmns=null hplmns=null subscriptionType=0 groupOwner=null carrierConfigAccessRules=null areUiccApplicationsEnabled=true}
01-10 12:57:07.199   266   266 W Binder:266_3: type=1400 audit(0.0:21442): avc: denied { read } for name="wakeup35" dev="sysfs" ino=17526 scontext=u:r:system_suspend:s0 tcontext=u:object_r:sysfs:s0 tclass=dir permissive=0
01-10 12:57:07.330   795   795 V KeyguardUpdateMonitor: onSubscriptionInfoChanged()
01-10 12:57:07.344   795   795 V KeyguardUpdateMonitor: SubInfo:{id=1 iccId=890141032[****] simSlotIndex=0 carrierId=1 displayName=T-Mobile carrierName=T-Mobile nameSource=3 iconTint=-16746133 number=[****] dataRoaming=0 iconBitmap=android.graphics.Bitmap@8213a76 mcc=310 mnc=260 countryIso=us isEmbedded=false nativeAccessRules=null cardString=890141032[****] cardId=-1 isOpportunistic=false groupUUID=null isGroupDisabled=false profileClass=-1 ehplmns=null hplmns=null subscriptionType=0 groupOwner=null carrierConfigAccessRules=null areUiccApplicationsEnabled=true}
01-10 12:57:07.363 25680 25684 I cmd     : oneway function results will be dropped but finished with status OK and parcel size 4
01-10 12:57:07.379 26260 26325 W LocationOracle: No location history returned by ContextManager
01-10 12:57:07.381 24843 24926 I MonitoringInstr: waitForActivitiesToComplete() took: 0ms
01-10 12:57:07.384   565  1771 W WindowManager: removeWindowToken: Attempted to remove non-existing token: android.os.Binder@9eca3a7
01-10 12:57:07.397   565  1771 I ActivityManager: Force stopping io.appium.uiautomator2.server appid=10162 user=0: finished inst
01-10 12:57:07.411   565  1771 I ActivityManager: Killing 24843:io.appium.uiautomator2.server/u0a162 (adj 0): stop io.appium.uiautomator2.server due to finished inst
01-10 12:57:07.422 24786 24786 D AndroidRuntime: Shutting down VM
```

**Comment by aguspeq** [comment]
Thank you :)  I will keep investigating why this happens then, I thought it was related to appium because it only happened after I updated my appium version yesterday, have a great weekend

**Comment by aguspeq** [comment]
In case somebody else runs into the same problem, the only way I found to get my tests running again was to downgrade back to 1.19.1

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
