### ISSUE TITLE
Socket hang up on iOS 

### ISSUE THREAD

**Issue by zarashima** [appium/appium#15016]
## The problem

Execute Appium tests causing 'socket hang up' issue and then timeout for every device I've tried

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.0
* Last Appium version that did not exhibit the issue (if applicable): 1.18
* Desktop OS/version used to run Appium: MacOS Big Sur 11.0.1
* Node.js version (unless using Appium.app|exe): 12.16.1
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iPhone XR 14.2
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

## Details

Went through setup iOS completely and able to install WDA on the device. Upon executing the tests, the Appium CLI keeps showing 'socket hang up' error without launching the application and then timed out.

Details logs:

```
2021-01-13 10:22:47:042 - [WD Proxy] socket hang up
2021-01-13 10:22:48:063 - [WD Proxy] socket hang up
2021-01-13 10:22:49:074 - [WD Proxy] socket hang up
2021-01-13 10:22:50:085 - [WD Proxy] socket hang up
2021-01-13 10:22:51:093 - [WD Proxy] socket hang up
2021-01-13 10:22:52:100 - [WD Proxy] socket hang up
2021-01-13 10:22:53:111 - [WD Proxy] socket hang up
2021-01-13 10:22:54:118 - [WD Proxy] socket hang up
2021-01-13 10:22:55:124 - [WD Proxy] socket hang up
2021-01-13 10:26:56:157 - [WD Proxy] Error: timeout of 240000ms exceeded
2021-01-13 10:26:56:158 - [WD Proxy]     at createError (/usr/local/lib/node_modules/appium/node_modules/axios/lib/core/createError.js:16:15)
2021-01-13 10:26:56:158 - [WD Proxy]     at RedirectableRequest.handleRequestTimeout (/usr/local/lib/node_modules/appium/node_modules/axios/lib/adapters/http.js:280:16)
2021-01-13 10:26:56:158 - [WD Proxy]     at Object.onceWrapper (events.js:417:28)
2021-01-13 10:26:56:159 - [WD Proxy]     at RedirectableRequest.emit (events.js:311:20)
2021-01-13 10:26:56:159 - [WD Proxy]     at Timeout._onTimeout (/usr/local/lib/node_modules/appium/node_modules/follow-redirects/index.js:166:13)
2021-01-13 10:26:56:159 - [WD Proxy]     at listOnTimeout (internal/timers.js:549:17)
2021-01-13 10:26:56:159 - [WD Proxy]     at processTimers (internal/timers.js:492:7)

```

Tried with many iOS devices and still observe the same issue

## Link to Appium logs

https://gist.github.com/zarashima/0f84895b8fd48c303fc7c2f016fc1783

## Code To Reproduce Issue [ Good To Have ]

My desired capabilities:
  ```
      desiredCapabilities.setCapability("platformName", "iOS");
        desiredCapabilities.setCapability("platformVersion", deviceVersion);
        desiredCapabilities.setCapability("deviceName", deviceName);
        desiredCapabilities.setCapability("udid", deviceId);
        desiredCapabilities.setCapability("wdaLocalPort", systemPort);
        desiredCapabilities.setCapability("xcodeOrgId",  "orgID);
        desiredCapabilities.setCapability("xcodeSigningId", "orgSigningID);
        desiredCapabilities.setCapability("automationName", "XCUITest");
        desiredCapabilities.setCapability("fullReset", true);
        desiredCapabilities.setCapability("noReset", false);
        desiredCapabilities.setCapability("sendKeyStrategy", "grouped");
        desiredCapabilities.setCapability("maxTypingFrequency", 60);
        desiredCapabilities.setCapability("newCommandTimeout", 360);
        desiredCapabilities.setCapability("showXcodeLog", true);
        desiredCapabilities.setCapability("showIOSLog", true);
        desiredCapabilities.setCapability("includeSafariInWebviews", true);
        desiredCapabilities.setCapability("shouldUseSingletonTestManager", true);
```

**Comment by KazuCocoa** [comment]
Could you try to uninstall & install appium again?

**Comment by zarashima** [comment]
Still the same, uninstall and re-install with Appium 1.20.0

**Comment by KazuCocoa** [comment]
Then, could you share the full appium log as GIST?
The attached one seems in the middle of the new session request.

We'd like to check the entire log in the new session request.

**Comment by zarashima** [comment]
Hi,

Just updated it here: https://gist.github.com/zarashima/0f84895b8fd48c303fc7c2f016fc1783.

**Comment by KazuCocoa** [comment]
thanks, but could you remove `showIOSLog` capability?
The log was probably dropped some data since the log size was huge.

**Comment by zarashima** [comment]
Here is the updated one with that capability removed: https://gist.github.com/zarashima/0f84895b8fd48c303fc7c2f016fc1783

By the way, I look at the log and it seems this is the root cause, is it?

`2021-01-13 13:39:34:292 - [Xcode] 2021-01-13 13:39:39.445074+0700 WebDriverAgentRunner-Runner[1414:314735] Enqueue Failure: Failed to launch dev.v-key.vtap: The operation couldn’t be completed. Application info provider (FBSApplicationLibrary) returned nil for "dev.v-key.vtap" /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgentRunner/UITestingUITests.m 39 1`

**Comment by KazuCocoa** [comment]
Yes, it seems so.

Error messages, socket hung and timeout, seems expected as startup time log.
Will check the startup log on a real device later, but the point you addressed should be an issue

**Comment by zarashima** [comment]
Ok thanks waiting for your checks later

**Comment by KazuCocoa** [comment]
I quickly tried with loglevel info as same as yours.
Below launched com.apple.Maps as the `bundleId`. WDA was built from source in the appium process as same as your case.
`socket hang up` printed in the log for a while before finishing the new session request. (The below logs was 2nd time so the `socket hang up` printed in a short period tho)

```
2021-01-13 07:24:00:737 - [Appium] Welcome to Appium v1.20.0-beta.0 (REV 842050de21e68ed1adfb311687ffc9dddf46abcc)
2021-01-13 07:24:00:740 - [Appium] Non-default server args:
2021-01-13 07:24:00:740 - [Appium]   loglevel: info
2021-01-13 07:24:00:741 - [Appium]   logTimestamp: true
2021-01-13 07:24:00:850 - [Appium] Appium REST http interface listener started on 0.0.0.0:4723
2021-01-13 07:24:05:982 - [HTTP] --> POST /wd/hub/session
2021-01-13 07:24:05:982 - [HTTP] {"desiredCapabilities":{"platformName":"ios","automationName":"XCUITest","udid":"242bfcc998fd156df0bd0ad1dde8ab8e0a032114","platformVersion":"14.2","deviceName":"iPhone 11","useNewWDA":false,"eventTimings":true,"useJSONSource":true,"someCapability":"some_capability","newCommandTimeout":120,"wdaLocalPort":8100,"waitForQuiescence":true,"reduceMotion":true,"orientation":"PORTRAIT","processArguments":{"args":["happy","tseting"],"env":{"HAPPY":"testing"}},"screenshotQuality":2,"connectHardwareKeyboard":false,"bundleId":"com.apple.Maps","derivedDataPath":"/Users/kazuaki/GitHub/ruby_lib_core/tmp/Simulator","bootstrapPath":"/Users/kazuaki/GitHub/ruby_lib_core/tmp/Simulator/Build/Products","useXctestrunFile":true},"capabilities":{"firstMatch":[{"platformName":"ios","appium:automationName":"XCUITest","appium:udid":"242bfcc998fd156df0bd0ad1dde8ab8e0a032114","appium:platformVersion":"14.2","appium:deviceName":"iPhone 11","appium:useNewWDA":false,"appium:eventTimings":true,"appium:useJSONSource":true,"appium:someCapabi...
2021-01-13 07:24:06:582 - [Appium] Appium v1.20.0-beta.0 creating new XCUITestDriver (v3.33.1) session
2021-01-13 07:24:06:592 - [BaseDriver] The following capabilities were provided, but are not recognized by Appium:
2021-01-13 07:24:06:593 - [BaseDriver]   someCapability
2021-01-13 07:24:06:593 - [BaseDriver] Session created with session id: 4ef942b3-c56c-4c41-b6c6-7ef34a959117
2021-01-13 07:24:06:659 - [XCUITest] Determining device to run tests on: udid: '242bfcc998fd156df0bd0ad1dde8ab8e0a032114', real device: true
2021-01-13 07:24:06:712 - [WebDriverAgent] Using WDA path: '/Users/kazuaki/GitHub/ruby_lib_core/tmp/Simulator/Build/Products'
2021-01-13 07:24:06:712 - [WebDriverAgent] Using WDA agent: '/Users/kazuaki/GitHub/ruby_lib_core/tmp/Simulator/Build/Products/WebDriverAgent.xcodeproj'
2021-01-13 07:24:06:925 - [XCUITest] Setting up real device
2021-01-13 07:24:07:189 - [DevCon Factory] Requesting connection for device 242bfcc998fd156df0bd0ad1dde8ab8e0a032114 on local port 8100, device port 8100
2021-01-13 07:24:07:193 - [DevCon Factory] Successfully requested the connection for 242bfcc998fd156df0bd0ad1dde8ab8e0a032114:8100
2021-01-13 07:24:07:227 - [WD Proxy] socket hang up
2021-01-13 07:24:07:230 - [WebDriverAgent] Launching WebDriverAgent on the device
2021-01-13 07:24:07:230 - [WebDriverAgent] Skipped WDA project cleanup according to the provided capabilities
2021-01-13 07:24:07:541 - [WebDriverAgent] Using '/Users/kazuaki/GitHub/ruby_lib_core/tmp/Simulator/Build/Products/242bfcc998fd156df0bd0ad1dde8ab8e0a032114_14.2.xctestrun' as xctestrun file copied by '/Users/kazuaki/GitHub/ruby_lib_core/tmp/Simulator/Build/Products/WebDriverAgentRunner_iphoneos14.2-arm64.xctestrun'
2021-01-13 07:24:08:489 - [WD Proxy] socket hang up
2021-01-13 07:24:09:497 - [WD Proxy] socket hang up
2021-01-13 07:24:10:509 - [WD Proxy] socket hang up
2021-01-13 07:24:11:523 - [WD Proxy] socket hang up
2021-01-13 07:24:17:153 - [WD Proxy] Determined the downstream protocol as 'W3C'
2021-01-13 07:24:17:732 - [XCUITest] Setting the quality of phone screenshot: '2'
2021-01-13 07:24:17:742 - [Appium] New XCUITestDriver session created successfully, session 4ef942b3-c56c-4c41-b6c6-7ef34a959117 added to master session list
2021-01-13 07:24:17:747 - [HTTP] <-- POST /wd/hub/session 200 11764 ms - 965
2021-01-13 07:24:17:747 - [HTTP]
2021-01-13 07:24:17:750 - [HTTP] --> POST /wd/hub/session/4ef942b3-c56c-4c41-b6c6-7ef34a959117/timeouts
2021-01-13 07:24:17:750 - [HTTP] {"implicit":0}
2021-01-13 07:24:17:757 - [HTTP] <-- POST /wd/hub/session/4ef942b3-c56c-4c41-b6c6-7ef34a959117/timeouts 200 7 ms - 14
2021-01-13 07:24:17:757 - [HTTP]
```

**Comment by zarashima** [comment]
So is it an issue?

**Comment by KazuCocoa** [comment]
No, the socket message was expected.
It just indicated the WDA was not running. (general massage)
The message is probably since 1.19 or 1.18? (not a new one in 1.20 at least)

The above my comment was an example of success to launch the com.apple.Maps from building WDA.

**Comment by zarashima** [comment]
The logs showing that Appium 1.20 is using, so it's 1.20 I believe.

Do you know how to address this? I've tried with different machines and still the same issue, maybe it's due to my app? Should I try with a different application?

**Comment by KazuCocoa** [comment]
>  it's due to my app?

Probably yes, afaik.
Appium's endpoint to launch an application is XCTest framework's one.
i.e. https://github.com/appium/WebDriverAgent/blob/a1824895274c60798b506f31054e4ce1e0400c71/WebDriverAgentLib/Routing/FBSession.m#L204

So if something had happened in the call, probably your app got an issue when XCTest framework launched it.

If yours worked with Appium 1.18, as you addressed in this description, with the same app, Xcode and OS versions, potentially capabilities like 
 `wdaEventloopIdleDelay` might help. https://github.com/appium/appium-xcuitest-driver
(but it would better to check your app as well.)

**Comment by mykola-mokhnach** [comment]
> 2021-01-13 13:39:34:292 - [Xcode] 2021-01-13 13:39:39.445074+0700 WebDriverAgentRunner-Runner[1414:314735] Enqueue Failure: Failed to launch app: The operation couldn’t be completed. Application info provider (FBSApplicationLibrary) returned nil for "app" /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgentRunner/UITestingUITests.m 39 1

https://stackoverflow.com/questions/63971418/unable-to-run-react-native-project-on-simulator-after-updating-to-xcode-12

This seems to be a common react issue, which for sure has nothing to do with Appium

**Comment by zarashima** [comment]
So I've tried another application here, still the same issue :(. If the above issue related to WebDriverAgent, should I use another version of WebDriverAgent?

**Comment by KazuCocoa** [comment]
> another application

Like with `bundleId` installed application I did in https://github.com/appium/appium/issues/15016#issuecomment-759260137 ?

Then, probably XCTest framework internal had an issue in your environment...
You could try another WebDriverAgent version, but I don't think the issue `Failed to launch app: The operation couldn’t be compl...` will fix.

**Comment by zarashima** [comment]
Ah I know why. I used `bundleId` parameter in my desired capabilities. When I removed it my application that having the original issue is started successfully
