### ISSUE TITLE
Encountered internal error running command when finding element on a new session

### ISSUE THREAD

**Issue by KageyamaRuka** [appium/appium#15045]
## The problem

The cases was executed one by one with the same port 8302 on real android device, several cases finished and then got an unknown server-side error for a new session when finding elemet by xpath. Is it an issue already known or something else?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOS 10.15.7
* Node.js version (unless using Appium.app|exe): v15.2.0
* Npm or Yarn package manager: 6.14.8
* Mobile platform/version under test: Android 10
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: connect ECONNREFUSED 127.0.0.1:8302

## Link to Appium logs

[appium.log](https://github.com/appium/appium/files/5853561/appium.log)

execution log
[Thread_FA68R0310604.log](https://github.com/appium/appium/files/5853584/Thread_FA68R0310604.log)

**Comment by KageyamaRuka** [comment]
```
2021-01-22 02:10:39:671 [HTTP] --> POST /wd/hub/session/edfba700-2c0c-4c89-adcb-7ae398134684/element
2021-01-22 02:10:39:671 [HTTP] {"using":"xpath","value":"//*[@text='相册']"}
2021-01-22 02:10:39:671 [W3C (edfba700)] Calling AppiumDriver.findElement() with args: ["xpath","//*[@text='相册']","edfba700-2c0c-4c89-adcb-7ae398134684"]
2021-01-22 02:10:39:671 [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
2021-01-22 02:10:39:671 [BaseDriver] Waiting up to 0 ms for condition
2021-01-22 02:10:39:672 [WD Proxy] Matched '/element' to command name 'findElement'
2021-01-22 02:10:39:672 [WD Proxy] Proxying [POST /element] to [POST http://127.0.0.1:8302/wd/hub/session/810c07ea-55f7-45c9-a58e-f8bf83044de6/element] with body: {"strategy":"xpath","selector":"//*[@text='相册']","context":"","multiple":false}
2021-01-22 02:10:39:674 [WD Proxy] connect ECONNREFUSED 127.0.0.1:8302
2021-01-22 02:10:39:689 [W3C (edfba700)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: connect ECONNREFUSED 127.0.0.1:8302
2021-01-22 02:10:39:689 [W3C (edfba700)]     at JWProxy.command (/Users/yukisou/.nvm/versions/node/v15.2.0/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:280:13)
2021-01-22 02:10:39:689 [W3C (edfba700)]     at runMicrotasks (<anonymous>)
2021-01-22 02:10:39:689 [W3C (edfba700)]     at processTicksAndRejections (node:internal/process/task_queues:93:5)
2021-01-22 02:10:39:689 [W3C (edfba700)]     at AndroidUiautomator2Driver.helpers.doFindElementOrEls (/Users/yukisou/.nvm/versions/node/v15.2.0/lib/node_modules/appium/node_modules/appium-uiautomator2-driver/lib/commands/find.js:27:12)
2021-01-22 02:10:39:689 [W3C (edfba700)]     at doFind (/Users/yukisou/.nvm/versions/node/v15.2.0/lib/node_modules/appium/node_modules/appium-android-driver/lib/commands/find.js:36:17)
2021-01-22 02:10:39:689 [W3C (edfba700)]     at wrappedCondFn (/Users/yukisou/.nvm/versions/node/v15.2.0/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/timeout.js:151:12)
2021-01-22 02:10:39:689 [W3C (edfba700)]     at spin (/Users/yukisou/.nvm/versions/node/v15.2.0/lib/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:113:20)
2021-01-22 02:10:39:689 [W3C (edfba700)]     at waitForCondition (/Users/yukisou/.nvm/versions/node/v15.2.0/lib/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:129:10)
2021-01-22 02:10:39:689 [W3C (edfba700)]     at AndroidUiautomator2Driver.implicitWaitForCondition (/Users/yukisou/.nvm/versions/node/v15.2.0/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/timeout.js:153:10)
2021-01-22 02:10:39:689 [W3C (edfba700)]     at AndroidUiautomator2Driver.findElOrEls (/Users/yukisou/.nvm/versions/node/v15.2.0/lib/node_modules/appium/node_modules/appium-android-driver/lib/commands/find.js:60:5)
2021-01-22 02:10:39:689 [W3C (edfba700)]     at AndroidUiautomator2Driver.findElOrElsWithProcessing (/Users/yukisou/.nvm/versions/node/v15.2.0/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:33:12)
2021-01-22 02:10:39:689 [W3C (edfba700)]     at AndroidUiautomator2Driver.findElement (/Users/yukisou/.nvm/versions/node/v15.2.0/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:53:10)
2021-01-22 02:10:39:690 [HTTP] <-- POST /wd/hub/session/edfba700-2c0c-4c89-adcb-7ae398134684/element 500 19 ms - 2235
2021-01-22 02:10:39:690 [HTTP] 
2021-01-22 02:10:39:695 [HTTP] --> POST /wd/hub/session/edfba700-2c0c-4c89-adcb-7ae398134684/appium/app/close
2021-01-22 02:10:39:695 [HTTP] {}
2021-01-22 02:10:39:696 [W3C (edfba700)] Calling AppiumDriver.closeApp() with args: ["edfba700-2c0c-4c89-adcb-7ae398134684"]
```
