### ISSUE TITLE
Session closed due to newCommandTimeout setting in desired capabilities

### ISSUE THREAD

**Issue by YukiSou** [appium/appium#15041]
## The problem

Closing session, cause was 'New Command Timeout of 600 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOS 10.15.7
* Node.js version (unless using Appium.app|exe): v15.2.0
* Npm or Yarn package manager: 6.14.8
* Mobile platform/version under test: Android 10
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

Since the `newCommandTimeout` in desired capabilities default to 60 and may cause session closed issues, why not set it to zero by default or just remove it from desired capabilities? Is there any use scenario for this option?

relate to
https://github.com/appium/appium/issues/5341
https://github.com/appium/appium/issues/13839

**Comment by mykola-mokhnach** [comment]
Changing the default value for this option would be a breaking change. The purpose of it is to be able to properly shut down the driver and free resources  if the client stops sending commands (for example if it forgets to quit a sessions).

**Comment by YukiSou** [comment]
If that's the case, then maybe any request by the client side should refresh this timeout, and the session shouldn't be closed when the client side still have a active session with the server side, but actually the session was closed by the server side even if the client side was doing something.

**Comment by mykola-mokhnach** [comment]
Currently this timer starts counting as soon as the server receives a new command. You could find the related logic in https://github.com/appium/appium-base-driver/blob/5521888b0fe3496ce21238cece05c6bb16244f93/lib/basedriver/commands/timeout.js

**Comment by KageyamaRuka** [comment]
```
2021-01-22 02:10:34:852 [HTTP] <-- POST /wd/hub/session/edfba700-2c0c-4c89-adcb-7ae398134684/element 404 642 ms - 875
2021-01-22 02:10:34:852 [HTTP] 
2021-01-22 02:10:35:857 [HTTP] --> POST /wd/hub/session/edfba700-2c0c-4c89-adcb-7ae398134684/element
2021-01-22 02:10:35:857 [HTTP] {"using":"xpath","value":"//*[@text='我有相机']"}
2021-01-22 02:10:35:857 [W3C (edfba700)] Calling AppiumDriver.findElement() with args: ["xpath","//*[@text='我有相机']","edfba700-2c0c-4c89-adcb-7ae398134684"]
2021-01-22 02:10:35:857 [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
2021-01-22 02:10:35:857 [BaseDriver] Waiting up to 0 ms for condition
2021-01-22 02:10:35:858 [WD Proxy] Matched '/element' to command name 'findElement'
2021-01-22 02:10:35:858 [WD Proxy] Proxying [POST /element] to [POST http://127.0.0.1:8302/wd/hub/session/810c07ea-55f7-45c9-a58e-f8bf83044de6/element] with body: {"strategy":"xpath","selector":"//*[@text='我有相机']","context":"","multiple":false}
2021-01-22 02:10:36:662 [WD Proxy] Got response with status 404: {"sessionId":"810c07ea-55f7-45c9-a58e-f8bf83044de6","value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters","stacktrace":"io.appium.uiautomator2.common.exceptions.ElementNotFoundException: An element could not be located on the page using the given search parameters\n\tat io.appium.uiautomator2.handler.FindElement.findElement(FindElement.java:96)\n\tat io.appium.uiautomator2.handler.FindElement.safeHandle(FindElement.java:71)\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:41)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:253)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:247)\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:68)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerCont...
2021-01-22 02:10:36:662 [W3C] Matched W3C error code 'no such element' to NoSuchElementError
2021-01-22 02:10:36:663 [W3C (edfba700)] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
2021-01-22 02:10:36:663 [W3C (edfba700)]     at AndroidUiautomator2Driver.findElOrEls (/Users/yukisou/.nvm/versions/node/v15.2.0/lib/node_modules/appium/node_modules/appium-android-driver/lib/commands/find.js:75:11)
2021-01-22 02:10:36:663 [W3C (edfba700)]     at runMicrotasks (<anonymous>)
2021-01-22 02:10:36:663 [W3C (edfba700)]     at processTicksAndRejections (node:internal/process/task_queues:93:5)
2021-01-22 02:10:36:663 [W3C (edfba700)]     at AndroidUiautomator2Driver.findElOrElsWithProcessing (/Users/yukisou/.nvm/versions/node/v15.2.0/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:33:12)
2021-01-22 02:10:36:663 [W3C (edfba700)]     at AndroidUiautomator2Driver.findElement (/Users/yukisou/.nvm/versions/node/v15.2.0/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:53:10)
2021-01-22 02:10:36:664 [HTTP] <-- POST /wd/hub/session/edfba700-2c0c-4c89-adcb-7ae398134684/element 404 807 ms - 911
2021-01-22 02:10:36:664 [HTTP] 
2021-01-22 02:10:38:083 [BaseDriver] Shutting down because we waited 600 seconds for a command
2021-01-22 02:10:38:083 [Appium] Closing session, cause was 'New Command Timeout of 600 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'
2021-01-22 02:10:38:083 [Appium] Removing session 'acad023d-4246-4e2f-9a70-aea2c8b29d51' from our master session list
2021-01-22 02:10:38:084 [UiAutomator2] Deleting UiAutomator2 session
2021-01-22 02:10:38:085 [UiAutomator2] Deleting UiAutomator2 server session
2021-01-22 02:10:38:085 [WD Proxy] Matched '/' to command name 'deleteSession'
2021-01-22 02:10:38:085 [WD Proxy] Proxying [DELETE /] to [DELETE http://127.0.0.1:8302/wd/hub/session/c0995452-2c79-48ac-994d-19765f2bcd67] with no body
2021-01-22 02:10:38:112 [WD Proxy] Got response with status 200: {"sessionId":"c0995452-2c79-48ac-994d-19765f2bcd67","value":null}
```
Will the `element` command refresh the timeout? it looks like the timer hasn't been refreshed even if `element` was called three seconds ago.
[appium.log](https://github.com/appium/appium/files/5853294/appium.log)

**Comment by YukiSou** [comment]
Thanks for explaining, looks like the issue i got was caused by some other reason, issued closed
