### ISSUE TITLE
IOS Real Device - proxy command timeout on 'mobile: scroll'

### ISSUE THREAD

**Issue by NirBY** [appium/appium#15074]
## The problem

Getting WDA command timeout when using gestures events.

## Environment

* Appium version (or git revision) that exhibits the issue: v1.20.0
* Last Appium version that did not exhibit the issue (if applicable):I think it is related to IOS ver, started in V14
* Desktop OS/version used to run Appium:MAC OS Big Sur 11.1
* Node.js version (unless using Appium.app|exe): v12.19.0
* Npm or Yarn package manager:npm
* Mobile platform/version under test:iPhone 8, real device, IOS V14.2
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe: Using Java's AppiumDriverLocalService

## Details

When using scroll to element, got proxy command timeout.
Also restarting driver didn't help, getting errors after few commands. it only solved after restarting both server & driver again.

## Link to Appium logs

[Appium Server Log](https://github.com/appium/appium/files/5903726/appiumServeriPhone8.log.txt)
[Page Source](https://github.com/appium/appium/files/5903732/20210131083045_080.txt)

## Code To Reproduce Issue [ Good To Have ]

                    driver.executeScript("mobile: scroll", new HashMap<String, String>() {{
                        put("predicateString", "name == '" + <Name> + "' AND value == '" + <Value> + "'");
                    }});

**Comment by mykola-mokhnach** [comment]
Try to enable xcodebuild and device logging as the current log does not contain any helpful data. In general I don't think there is much we could do there from WDA side.

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by NirBY** [comment]
Open Logs - 
[AppiumLog.txt](https://github.com/appium/appium/files/5951875/AppiumLog.txt)
Sorry it took so long, hope it helps.

The log is huge, I only took the last min. please let me know if you will need more.

**Comment by mykola-mokhnach** [comment]
At which timestamp there the issue happens?

**Comment by NirBY** [comment]
Page source is also attached 👆

**This one**:
`2021-02-08 20:22:01:013 [WD Proxy] Error: timeout of 240000ms exceeded`

**I got the Exception**:

> org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: timeout of 240000ms exceeded
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Cellacts-Mac-mini-2.local', ip: 'fe80:0:0:0:4db:22c1:876d:1521%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '1.8.0_221'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities {app: /Users/..., automationName: XCUITest, browserName: , commandTimeouts: 0, databaseEnabled: false, deviceName: iPhone8, javascriptEnabled: true, locationContextEnabled: false, maxTypingFrequency: 100, networkConnectionEnabled: false, newCommandTimeout: 300, noReset: false, platform: MAC, platformName: iOS, platformVersion: 14.2, showIOSLog: true, showXcodeLog: true, takesScreenshot: true, udid: 2cc4db222fa82ed91b632d3b6b4..., updatedWDABundleId: com.cellact.secnum2, useNewWDA: false, wdaStartupRetries: 5, wdaStartupRetryInterval: 2000, webStorageEnabled: false, xcodeOrgId: <ORGID>, xcodeSigningId: iPhone Developer}
Session ID: 9dc3c3ec-bedd-407a-9e43-8f70e7eee996
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:247)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:489)
