### ISSUE TITLE
Appium times out when trying to start app that takes long time to start. How to extend the timeout?

### ISSUE THREAD

**Issue by alexander-poulikakos** [appium/appium#15132]
## The problem

I'm testing an iOS app (on real device) that takes quit long time to start (about 80 seconds). It seems from the appium log that WebDriverAgent is trying to start the app (create a session), but times out after approx. 60 seconds. And then re-starts the app and tries again and so on.

I get this in the log:
```
2021-02-23 20:28:48.658 DEBUG [debug] [WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:3970/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"***********","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}} 
2021-02-23 20:29:48.669 INFO  [WD Proxy] Error: timeout of 480000ms exceeded 
```

If you compare the timestamp you'll see it takes approx. 60 seconds to timeout. Is it possible to extend this timeout somehow? 

I have tried using the WebDriverAgent capability `wdaConnectionTimeout=480000` but when set to higher than 60 seconds there seems to be something else capping it at 60 seconds. Even though the error message says `timeout of 480000ms exceeded`, which is a bit confusing.

See full log here: https://gist.github.com/alexander-poulikakos/7d062a5f49d869f71be898bd22ffa592

## Environment
* Node.js version (unless using Appium.app|exe): node v13.8.0

**Comment by KazuCocoa** [comment]
How about `commandTimeouts`?
https://github.com/appium/appium-xcuitest-driver#other

**Comment by alexander-poulikakos** [comment]
I have tried with this:
```
2021-02-24 07:56:37.824 DEBUG [debug] [BaseDriver]     "appium:commandTimeouts": "{\"createSession\":100000}", 
...
2021-02-24 07:56:52.107 DEBUG [debug] [XCUITest] Sending createSession command to WDA 
2021-02-24 07:56:52.107 DEBUG [debug] [XCUITest] Setting custom timeout to 100000 ms for 'createSession' command 
2021-02-24 07:56:52.107 DEBUG [debug] [WD Proxy] Matched '/session' to command name 'createSession' 
2021-02-24 07:56:52.109 DEBUG [debug] [WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:29723/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.midasplayer.test.candycrushsaga","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}} 
2021-02-24 07:57:52.117 INFO  [WD Proxy] Error: timeout of 240000ms exceeded 
2021-02-24 07:57:52.118 INFO  [WD Proxy]     at createError (/usr/local/lib/node_modules/appium/node_modules/axios/lib/core/createError.js:16:15) 
```
It still timeouts after 60 seconds (according to timestamps).

If I use a value less that 60 seconds then it seems to be obeyed:
```
2021-02-24 08:03:57.035 DEBUG [debug] [BaseDriver]     "appium:commandTimeouts": "{\"createSession\":20000}", 
...
2021-02-24 08:04:24.382 DEBUG [debug] [XCUITest] Sending createSession command to WDA 
2021-02-24 08:04:24.382 DEBUG [debug] [XCUITest] Setting custom timeout to 20000 ms for 'createSession' command 
2021-02-24 08:04:24.382 DEBUG [debug] [WD Proxy] Matched '/session' to command name 'createSession' 
2021-02-24 08:04:24.384 DEBUG [debug] [WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:26727/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.midasplayer.test.candycrushsaga","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}} 
2021-02-24 08:04:44.389 INFO  [DevCon Factory] Releasing connections for d4ce6a31ce15652867f6a0e6861283c4193a3d76 device on any port number 
2021-02-24 08:04:44.389 INFO  [DevCon Factory] Found cached connections to release: ["d4ce6a31ce15652867f6a0e6861283c4193a3d76:26727"] 
2021-02-24 08:04:44.390 INFO  [DevCon Factory] Releasing the listener for 'd4ce6a31ce15652867f6a0e6861283c4193a3d76:26727' 
2021-02-24 08:04:44.390 DEBUG [debug] [iProxy@d4ce6a31:26727] Closing the connection 
2021-02-24 08:04:44.390 DEBUG [debug] [DevCon Factory] Cached connections count: 0 
2021-02-24 08:04:44.391 DEBUG [debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on. 
2021-02-24 08:04:44.391 INFO  [XCUITest] Appium did not get any response from 'createSession' command in 20000 ms 
2021-02-24 08:04:44.425 DEBUG [debug] [XCUITest] Failed to create WDA session (Appium did not get any response from 'createSession' command in 20000 ms). Retrying... 

```

It is the same thing with `wdaConnectionTimeout`. A value higher than 60 seconds will be capped at 60 seconds (according to timestamp):
```
2021-02-24 08:11:55.490 DEBUG [debug] [BaseDriver]     "appium:wdaConnectionTimeout": 240000, 
...
2021-02-24 08:12:22.944 DEBUG [debug] [XCUITest] Sending createSession command to WDA 
2021-02-24 08:12:22.944 DEBUG [debug] [WD Proxy] Matched '/session' to command name 'createSession' 
2021-02-24 08:12:22.946 DEBUG [debug] [WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:24420/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.midasplayer.test.candycrushsaga","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}} 
2021-02-24 08:13:22.957 INFO  [WD Proxy] Error: timeout of 240000ms exceeded 
2021-02-24 08:13:22.957 INFO  [WD Proxy]     at createError (/usr/local/lib/node_modules/appium/node_modules/axios/lib/core/createError.js:16:15) 
```

but if a value less than 60 seconds is used, then it is obeyed:
```
2021-02-24 08:15:30.858 DEBUG [debug] [BaseDriver]     "appium:wdaConnectionTimeout": 30000, 
...
2021-02-24 08:15:49.141 DEBUG [debug] [XCUITest] Sending createSession command to WDA 
2021-02-24 08:15:49.141 DEBUG [debug] [WD Proxy] Matched '/session' to command name 'createSession' 
2021-02-24 08:15:49.143 DEBUG [debug] [WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:31906/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.midasplayer.test.candycrushsaga","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}} 
2021-02-24 08:16:19.155 INFO  [WD Proxy] Error: timeout of 30000ms exceeded 
2021-02-24 08:16:19.155 INFO  [WD Proxy]     at createError (/usr/local/lib/node_modules/appium/node_modules/axios/lib/core/createError.js:16:15) 
```

**Comment by KazuCocoa** [comment]
Does https://github.com/appium/appium-base-driver/pull/460 help?

**Comment by KazuCocoa** [comment]
fyi: I've updated the PR. (removed the timeout)

**Comment by KazuCocoa** [comment]
`appium-base-driver@7.5.1` should be available via `appium@beta`

**Comment by alexander-poulikakos** [comment]
thanks! I will try it out and report back.

**Comment by alexander-poulikakos** [comment]
The cap at 60 seconds seems to be gone with `v1.21.0-beta.0` :)
Below times out after 65 seconds.

```
2021-02-24 11:24:22.800 INFO  [Appium] Welcome to Appium v1.21.0-beta.0 
...
2021-02-24 11:24:24.195 DEBUG [debug] [BaseDriver]     "appium:wdaConnectionTimeout": 65000, 
...
2021-02-24 11:24:40.440 DEBUG [debug] [WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:37465/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.midasplayer.test.candycrushsaga","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}} 
2021-02-24 11:25:45.455 INFO  [WD Proxy] Error: timeout of 65000ms exceeded 
```


and when using the default `wdaConnectionTimeout` I get no timeout :) 
```
2021-02-24 12:13:58.542 DEBUG [debug] [WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:14277/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.midasplayer.test.candycrushsaga","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}} 
2021-02-24 12:15:05.526 DEBUG [debug] [WD Proxy] Got response with status 200: {"value":{"sessionId":"01BE7C0C-7C14-4809-BF3A-6221A0E94045","capabilities":{"device":"iphone","browserName":"","sdkVersion":"10.3.2","CFBundleIdentifier":"com.midasplayer.test.candycrushsaga"}},"sessionId":"01BE7C0C-7C14-4809-BF3A-6221A0E94045"} 
```
