### ISSUE TITLE
ActionChains Fail with appium@1.12.x

### ISSUE THREAD

**Issue by vong0** [appium/appium#15144]
## The problem

Hi, so I'm currently trying to use selenium "ActionChains" with the ["appium-python-client"](https://github.com/appium/python-client) on Windows 10 with the WinAppDriver.
- On appium versions v1.19.1 (+ any prior to v1.20.0), any action chain event seems to work
- However, on v1.20.0+ I keep receiving the following exception message

Note the the same:
- code and version of "appium-python-client" was used
- each version of appium tested also used the same WinAppDriver v1.2-RC

Therefore, it seems that the issue stems from the "appium" library and not "WinAppDriver" nor the "appium-python-client".

```
Traceback (most recent call last):
  File "C:/p4/perforce/depot/qa/tests/licensing/Fuse/dev/tests/failure.py", line 19, in <module>
    actions.double_click(two).perform()
  File "C:\p4\perforce\depot\qa\tests\licensing\Fuse\dev\venv-379\lib\site-packages\selenium\webdriver\common\action_chains.py", line 80, in perform
    self.w3c_actions.perform()
  File "C:\p4\perforce\depot\qa\tests\licensing\Fuse\dev\venv-379\lib\site-packages\selenium\webdriver\common\actions\action_builder.py", line 76, in perform
    self.driver.execute(Command.W3C_ACTIONS, enc)
  File "C:\p4\perforce\depot\qa\tests\licensing\Fuse\dev\venv-379\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\p4\perforce\depot\qa\tests\licensing\Fuse\dev\venv-379\lib\site-packages\appium\webdriver\errorhandler.py", line 31, in check_response
    raise wde
  File "C:\p4\perforce\depot\qa\tests\licensing\Fuse\dev\venv-379\lib\site-packages\appium\webdriver\errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "C:\p4\perforce\depot\qa\tests\licensing\Fuse\dev\venv-379\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Currently only pen and touch pointer input source types are supported
```

## Environment

* Python version: Python 3.7.9 (but reproducible on any Python3 version)
* Appium version (or git revision) that exhibits the issue: v.1.20.0+
* Last Appium version that did not exhibit the issue (if applicable): v1.19.1 (any version before v.1.20.0)
* Desktop OS/version used to run Appium: Windows 10 (any version)
* Node.js version: 14.15.4 (should not matter though)
* Npm version: 6.14.10 (should not matter though)

## Link to Appium logs

https://gist.github.com/vong0/727ef226073466324ae5631e029fcd13 (logs of both success and fail version)

## Code To Reproduce Issue [ Good To Have ]

1. Create a virtual environment and only install `Appium-Python-Client==1.0.2`
2. Install appium failing version `npm install -g appium@1.20.0`
3. Run the following code segment and check that it fails
4. Rerun the code segment for a successful version `npm install -g appium@1.19.1`

```python
from appium import webdriver
from selenium.webdriver.common.action_chains import ActionChains

"Microsoft.WindowsCalculator_8wekyb3d8bbwe!App"

desired_caps = {"app": "Microsoft.WindowsCalculator_8wekyb3d8bbwe!App",
                "platformName": "Windows",
                "deviceName": "WindowsPC",
                "newCommandTimeout": 10000}
app = webdriver.Remote(command_executor='http://127.0.0.1:4723/wd/hub',
                       desired_capabilities=desired_caps)

# Normal actions work
two = app.find_element_by_name("Two")
two.click()

# Any ActionChain event fails
actions = ActionChains(app)
actions.double_click(two).perform()
# actions.move_to_element(two).perform()
```

**Comment by KazuCocoa** [comment]
The reason was probably Appium prior W3C WebDriver spec between Appium server and other drivers like WinAppDriver.
Then, WinAppDriver behaved to follow W3C. (I thought it was already W3C before Appium 1.19.0 for WinAppDriver though)


So far, probably `forceMjsonwp` like https://github.com/appium/python-client/blob/344953a49c7d66c77b2fa9b998a89a26d0e1f0d7/test/unit/webdriver/webdriver_test.py#L65-L71 helps.

But Appium will follow only W3C in Appium 2.0, so the workaround will also not work. It would be great to update your action with following W3C spec action.

I haven't confirmed in Python, but if you could find a way to set `touch` https://github.com/SeleniumHQ/selenium/blob/0e0194b0e52a34e7df4b841f1ed74506beea5c3e/py/selenium/webdriver/common/actions/pointer_input.py#L61 , the w3C action may work as `touch` in based on current your python code.

**Comment by vong0** [comment]
So is the issue that the commands "appium-python-client" was sending to appium is now out of date?

So is the issue in the "appium-python-client" that needs to be fixed so it is sending the right actions? So should I create an issue there? There are a number of functions in "ActionChains" that I still need to use but none of them seem to work.

I'm not sure if I fully understand what you are saying. But I have confirmed that using ["TouchActions"](
https://selenium-python.readthedocs.io/api.html#module-selenium.webdriver.common.touch_actions) works.

```
from selenium.webdriver.common.touch_actions import TouchActions

action = TouchActions(app)
action.double_tap(two).perform()
```

**Comment by KazuCocoa** [comment]
The client itself is not out-of-date, but the communication protocol behind the client changed to W3C one.

appium-python-client sends commands following MJSONWP or W3C protocols. The behaviour depends on the response by the server.

So, even you used the same method in Python client, but:
When Appium is 1.19.0, then the python client behaved as MJSONWP because Appium sent MJSONWP formatted capabilities to WinAppDriver and behaved as MJSONWP. Appium 1.20.0 case was W3C.
(You can see different HTTP call in your attached log.)

Probably https://github.com/appium/appium-windows-driver/pull/91/files#diff-ed3c013edbc896bd87ef62539626fcdc8930a31f3cee7ecb37438e172af2c8e0L50 this change affected.

`forceMjsonwp` sends only MJSONWP style's capability by Python client, so your connection will be MJSONWP base (because of no W3C stuff). Then, your python code will work as MJSONWP based one.


You can see some JSON bodies in your server log from python <-> appium <-> WinAppDriver and it will help what i mean...

**Comment by KazuCocoa** [comment]
Afaik from taking a look at the python code a bit, the below code sends 'mouse' action type in W3C. But WinAppDriver accepts only 'touch' and 'pen'. This is how to build the action command, but probably you should update these command to use 'touch' action. (I don't know the way for now.).

```
from selenium.webdriver.common.touch_actions import TouchActions

action = TouchActions(app)
action.double_tap(two).perform()
```
