### ISSUE TITLE
android(uiAutomator2): performActions with type "key" does not work (Request failed with status code 501)

### ISSUE THREAD

**Issue by DudaGod** [appium/appium#15253]
## The problem

Hello.
I faced with problem that `performActions` from w3c does not work with android+uiAutomator2.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.2
* Desktop OS/version used to run Appium: Linux
* Node.js version (unless using Appium.app|exe): 12.18.1
* Npm or Yarn package manager: 6.14.5
* Mobile platform/version under test: Android 6.0
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: cli

## Link to Appium logs

Full logs from appium - https://gist.github.com/DudaGod/3c6247ca161dc028968c4cc9e8a9a6a4

## Code To Reproduce Issue [ Good To Have ]

Code written on wdio@7:
```
const {remote} = require('webdriverio')

let client;

(async function () {
    client = await remote({
        protocol: 'http',
        hostname: 'MY_GRID_URL,
        port: 4444,
        path: '/wd/hub',
        automationProtocol: 'webdriver',
        capabilities: {
            platformName: 'Android',
            deviceName: 'android',
            version: 'phone-67.1',
            browserName: 'chrome',
            automationName: 'UiAutomator2'
        }
    });

    await client.url('https://yandex.ru')

    await client.performActions([{
        type: 'key',
        id: 'keyboard',
        actions: [
            {type: 'keyDown', value: 'a'},
            {type: 'keyUp', value: 'a'},
        ]
    }]);

    await client.deleteSession();
})()
    .catch(async (e) => {
        console.error(e.stack)
        await client.deleteSession()
    });
```

Logs from cli:
```
2021-04-07T10:22:22.124Z INFO webdriver: Initiate new session using the WebDriver protocol
2021-04-07T10:22:22.131Z INFO webdriver: [POST] http://MY_GRID_URL:4444/wd/hub/session
2021-04-07T10:22:22.131Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: {
      platformName: 'Android',
      deviceName: 'android',
      version: 'phone-67.1',
      browserName: 'chrome',
      automationName: 'UiAutomator2'
    },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    platformName: 'Android',
    deviceName: 'android',
    version: 'phone-67.1',
    browserName: 'chrome',
    automationName: 'UiAutomator2'
  }
}
2021-04-07T10:22:38.192Z INFO webdriver: COMMAND navigateTo("https://yandex.ru/")
2021-04-07T10:22:38.192Z INFO webdriver: [POST] http://MY_GRID_URL:4444/wd/hub/session/14f9624e25a639856e838b1c5437eef89b3b266b-180b-48d1-a5ff-6293bd508c94/url
2021-04-07T10:22:38.192Z INFO webdriver: DATA { url: 'https://yandex.ru/' }
2021-04-07T10:22:39.497Z INFO webdriver: COMMAND performActions(<object>)
2021-04-07T10:22:39.497Z INFO webdriver: [POST] http://MY_GRID_URL:4444/wd/hub/session/14f9624e25a639856e838b1c5437eef89b3b266b-180b-48d1-a5ff-6293bd508c94/actions
2021-04-07T10:22:39.497Z INFO webdriver: DATA { actions: [ { type: 'key', id: 'keyboard', actions: [Array] } ] }
2021-04-07T10:22:39.631Z WARN webdriver: Request failed with status 500 due to An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Request failed with status code 501
2021-04-07T10:22:39.632Z INFO webdriver: Retrying 1/3
2021-04-07T10:22:39.632Z INFO webdriver: [POST] http://MY_GRID_URL:4444/wd/hub/session/14f9624e25a639856e838b1c5437eef89b3b266b-180b-48d1-a5ff-6293bd508c94/actions
2021-04-07T10:22:39.632Z INFO webdriver: DATA { actions: [ { type: 'key', id: 'keyboard', actions: [Array] } ] }
2021-04-07T10:22:39.699Z WARN webdriver: Request failed with status 500 due to An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Request failed with status code 501
2021-04-07T10:22:39.699Z INFO webdriver: Retrying 2/3
2021-04-07T10:22:39.699Z INFO webdriver: [POST] http://MY_GRID_URL:4444/wd/hub/session/14f9624e25a639856e838b1c5437eef89b3b266b-180b-48d1-a5ff-6293bd508c94/actions
2021-04-07T10:22:39.699Z INFO webdriver: DATA { actions: [ { type: 'key', id: 'keyboard', actions: [Array] } ] }
2021-04-07T10:22:39.760Z WARN webdriver: Request failed with status 500 due to An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Request failed with status code 501
2021-04-07T10:22:39.760Z INFO webdriver: Retrying 3/3
2021-04-07T10:22:39.761Z INFO webdriver: [POST] http://MY_GRID_URL:4444/wd/hub/session/14f9624e25a639856e838b1c5437eef89b3b266b-180b-48d1-a5ff-6293bd508c94/actions
2021-04-07T10:22:39.761Z INFO webdriver: DATA { actions: [ { type: 'key', id: 'keyboard', actions: [Array] } ] }
2021-04-07T10:22:39.819Z ERROR webdriver: Request failed with status 500 due to unknown error: An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Request failed with status code 501
unknown error: An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Request failed with status code 501
    at Object.getErrorFromResponseBody (/Users/dudkevich/job/projects/dudkevich-scripts/FEI-20461.wdio_6/node_modules/webdriver/build/utils.js:189:12)
    at WebDriverRequest._request (/Users/dudkevich/job/projects/dudkevich-scripts/FEI-20461.wdio_6/node_modules/webdriver/build/request.js:168:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Browser.wrapCommandFn (/Users/dudkevich/job/projects/dudkevich-scripts/FEI-20461.wdio_6/node_modules/@wdio/utils/build/shim.js:79:29)
    at async /Users/dudkevich/job/projects/dudkevich-scripts/FEI-20461.wdio_6/chrome-phone-perform-actions.js:23:5
```

**Comment by mykola-mokhnach** [comment]
The error is expected. You are trying to send W3C /actions command to Chromedriver, that only supports jsonwp protocol.

**Comment by DudaGod** [comment]
> The error is expected. You are trying to send W3C /actions command to Chromedriver, that only supports jsonwp protocol.

I correctly understood you, that I just need to update the version of Chromedriver to a more recent one which supports w3c protocol?

**Comment by mykola-mokhnach** [comment]
Depending on what you are trying to achieve. You won't be able to update the driver if your browser version is too old. In such case one could try switching to the native context.

**Comment by DudaGod** [comment]
Okay, i understood. Thank you.

I close it.

**Comment by RayMan504** [comment]
I'm currently in native context within android device and I'm still having problems with driver.keys. Current Appium config. 

![image](https://user-images.githubusercontent.com/13529051/148089499-06996863-066c-4d88-a5f5-5226ba3f52e8.png)
