### ISSUE TITLE
Appium server stops responding with message 'An attempt was made to operate on a modal dialog when one was not open' in the log on ios devices

### ISSUE THREAD

**Issue by NSDInesh30** [appium/appium#15280]
## The problem

I am working on hybrid app(ionic app, cordava) .Script runs fine for first few minutes and then suddenly Appium server stops receiving request with this message **'An attempt was made to operate on a modal dialog when one was not open'**. Once this message is occurred no other request and response are observed in appium log. This message is the last line in the appium logs. Also this issue happens at different iphone devices(both iphone and iPad) at different time frame (between 15 to 1 hour). The same code is  working fine on Android(tried with several smartphone and tablet).  Every element in the application is from html (I  used to switch context to perform some native actions and switch back to webview again).  when trying to do any action (findElement, click, wait etc) suddenly this message is thrown in Appium log  and appium stops receiving further commands and get stopped

Sometimes the appium stops when trying to switch context also. In this case the last line in the appium log is **'Sending '_rpc_forwardGetListing:' message to app 'PID:363' (id: 4560): 'connectToApp'**. Attached logs for this as well

**Note: 
These 2 issues are not with specific elements or in specific lines of code. At each run, it happens on different elements and at different stage of execution. script executes fine for first few minutes , then suddenly this is happening at different time frame based on device. Both above issues happening only on iOS devices. In Android, the same code  runs smoothly till all testcases completes execution**

## Environment

* Appium version (or git revision) that exhibits the issue: 1.19.0,1.20.1
* Desktop OS/version used to run Appium: Running on TestObject cloud service
* Mobile platform/version under test: iPhone and iPad(Tried with different platform version 13.7,14.4,14.4.2,14.5 etc..)
* Real device or emulator/simulator: Real device

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/NSDInesh30/7a86705376ee8af0fcd468e900d1e4df
https://gist.github.com/NSDInesh30/69b514972402c2f381a71d5c2663b5d4
https://gist.github.com/NSDInesh30/e9ac97dc7f1a8ce408078be9063842c4

Context switch issue log
https://gist.github.com/NSDInesh30/80d4ee0ef6ba41d15420a96e5b5c675a
https://gist.github.com/NSDInesh30/a091158ee5e6f21b9e989cc9a6423263

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by NSDInesh30** [comment]
Any update on this?

**Comment by mykola-mokhnach** [comment]
Sorry, I cannot help on that

**Comment by NSDInesh30** [comment]
Hello guys, Could someone please provide the reason for this issue and any workaround?
I am not able to run automation suite. All I could see is Appium server stops receiving request from client and eventually it gets timeout

**Comment by jlipps** [comment]
When you run a web related command in Appium, Appium tries to check if an alert popped up in the middle of the command. This is because alerts block the JS execution thread, and Appium uses JS to perform web commands. If an alert happens as a result of one of your web commands, then the test script would hang forever. So Appium tries to detect alerts by asking WDA for the text of any visible alerts. If so, it's up to you to handle the alert.

It could be this is the context for what you're experiencing. But I'm not sure what the specific problem would be. It's most likely one of three things:

1. Appium is failing to detect an alert which is present, so it is hanging forever
2. Appium thinks an alert is present when it isn't, and this is causing problems somehow in this logic
3. You are failing to address an alert which is present, so no further commands can be run and the session times out

**Comment by NSDInesh30** [comment]
@jlipps 
Thank you for the detailed explanation. In my case, it looks like the second reason - Appium thinks an alert is present when it isn't, and this is causing problems somehow in this logic

So how could I handle in this case if I don't see any alert in the screen?

To elaborate further

The application which I work is ionic which contains 3 screens. The only alert display in my application is ionic-alert(radio ionic-alerts), which is also been handled properly using locators(I select radio button and click Ok using xpath locators) . Does dealing with this ionic alert frequently causes this issue?(not sure, since script fails with different elements which doesn't  come inside ionic-alert tags in html)
Lets say I have 20 automation test cases, so all these 20 automation test cases runs the same piece of code. If there is some logic mistake in my code, the script should fail in the first test case itself. But what is happening is first few test cases runs fine(which all uses the same reusable piece of code), then all of a sudden script stops due to above reason.(while watching the complete execution I didn't see any strange behavior in AUT)

Any help on this will be really appreciated. I tried several things that I know from my knowledge, nothing worked

**Comment by jlipps** [comment]
Do you see this problem running locally as well as on TestObject? There may be a bug here but it sounds like a really tricky one that will be impossible to address without a solid repro case.

**Comment by NSDInesh30** [comment]
Unfortunately I don't have a local setup to run script in iOS devices. So I have to rely on cloud platform to run my script in iOS devices

**Comment by jlipps** [comment]
It might be worth having TestObject investigate the error, then. Without a clear Appium repro case it's going to be tough for us to do anything about it.

**Comment by KazuCocoa** [comment]
I haven't dug in this cause (so just a comment, sorry), but afaik, this is a possible issue in Safari/Web Inspector..

**Comment by NSDInesh30** [comment]
@jlipps @KazuCocoa 

Thank you .. Finally somehow I find an workaround

The application I am working is hybrid app. I need to switch to webview immediately after application is launched. Every test scripts will be running in that webview. 

**Workaround done**
I updated the script to close the app and relaunch (after running 5 test cases/ after 10 min , something like this), so after few test case completes running, I deliberately close and relaunch the app , so that I get a new webview, and i am not seeing the above problem. So getting new webview often instead of continuing script with same webview, somehow solves this(but it is only a workaround, even resticting working on same webview for limited time ~10 min, I get the issue rarely)

So it looks like due to some reason(might be issue on Safari/Web Inspector, as said by KazuCocoa), running script on same webview for a long time causing some issue due to which Appium server becomes unresponsive. Might be the root cause be something else.

Tried running automation suite with couple of iOS devices which runs for around 2-3 hours(~ 50 test cases) and occurance of issue stopped with the workaround

**Comment by githubdhina** [comment]
My automation on iOS is failing with the same error as mentioned. I'm using appium 1.22.1 and iOS 15.3.1 device. I have tried the workaround of relaunching the app and it still fails. Any other suggestions, please to overcome this issue?

**Comment by DukeYe** [comment]
@KazuCocoa Could you please provide a link to the question or provide suggestions? Thank you
I also encountered similar issues when running automated tests on my mobile Safari browser.
Steps to reproduce:
1. Run automation on the mobile Safari browser and click a button on the page, which triggers a pop-up window that says "Website is opening a pop-up window. Block or Allow."
2. After the pop-up appears, I switch to the native context and perform an alert accept operation by running `alert = self.driver.switch_to.alert`, but I get the following error:
run code:
```
                    self.driver.switch_to.context('NATIVE_APP')
                    time.sleep(10)
                    logger.info(f"Switch to native context")
                    alert = self.driver.switch_to.alert
                    alert.accept()

```
error log
   ```
 alert = self.driver.switch_to.alert
D:\python3.7\lib\site-packages\selenium\webdriver\remote\switch_to.py:55: in alert
    _ = alert.text
D:\python3.7\lib\site-packages\selenium\webdriver\common\alert.py:59: in text
    return self.driver.execute(Command.W3C_GET_ALERT_TEXT)["value"]
D:\python3.7\lib\site-packages\selenium\webdriver\remote\webdriver.py:440: in execute
    self.error_handler.check_response(response)
D:\python3.7\lib\site-packages\appium\webdriver\errorhandler.py:122: in check_response
    raise exception_class(msg=message, stacktrace=format_stacktrace(stacktrace))
E   selenium.common.exceptions.NoAlertPresentException: Message: An attempt was made to operate on a modal dialog when one was not open
E   Stacktrace:
E   NoSuchAlertError: An attempt was made to operate on a modal dialog when one was not open
E       at errorFromW3CJsonCode (/Users/nano/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/protocol/errors.js:1112:25)
E       at ProxyRequestError.getActualError (/Users/nano/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/protocol/errors.js:981:14)
E       at JWProxy.command (/Users/nano/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:353:19)
E       at runMicrotasks (<anonymous>)
E       at processTicksAndRejections (internal/process/task_queues.js:95:5)
E       at XCUITestDriver.proxyCommand (/Users/nano/.appium/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:103:35)
E       at XCUITestDriver.getAlertText (/Users/nano/.appium/node_modules/appium-xcuitest-driver/lib/commands/alert.js:19:40)

```

> 我还没有深入研究这个原因（所以只是一条评论，抱歉），但据我所知，这可能是 Safari/Web Inspector 中的一个问题。

**Comment by vivekaccelq** [comment]
Hi, is there a way to skip this check? I see this issue with Appium 2.11 also

**Comment by mykola-mokhnach** [comment]
I assume this issue should happen less with recent remote debugger updates.
I've also updated error messages to highlight cases where iOS blocks javascript execution in the remote debugger
