### ISSUE TITLE
npm ERR! appium-chromedriver@4.26.2 postinstall: `node install-npm.js`

### ISSUE THREAD

**Issue by SGK2425** [appium/appium#15311]
Please check below logs for ref.

C:\WINDOWS\system32>npm install -g appium@1.20.2
C:\Users\sgopikri\AppData\Roaming\npm\appium -> C:\Users\sgopikri\AppData\Roaming\npm\node_modules\appium\build\lib\main.js

> appium-windows-driver@1.17.0 install C:\Users\sgopikri\AppData\Roaming\npm\node_modules\appium\node_modules\appium-windows-driver
> node install-npm.js

info WinAppDriver WinAppDriver version 1.2-RC already exists with correct checksum, not re-downloading

> core-js@2.6.12 postinstall C:\Users\sgopikri\AppData\Roaming\npm\node_modules\appium\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

> appium-chromedriver@4.26.2 postinstall C:\Users\sgopikri\AppData\Roaming\npm\node_modules\appium\node_modules\appium-chromedriver
> node install-npm.js

[08:21:07] [Chromedriver Install] Installing Chromedriver version '86.0.4240.22' for platform 'win' and architecture '32'
[08:21:07] [Chromedriver Install] Opening temp file to write 'chromedriver_win32' to...
[08:21:07] [Chromedriver Install] Opened temp file 'C:\Users\sgopikri\AppData\Local\Temp\2021330-4708-1dxunye.9d2e\chromedriver_win32.zip'
[08:21:07] [Chromedriver Install] Downloading https://chromedriver.storage.googleapis.com/86.0.4240.22/chromedriver_win32.zip to 'C:\Users\sgopikri\AppData\Local\Temp\2021330-4708-1dxunye.9d2e\chromedriver_win32.zip'
[08:21:07] Error installing Chromedriver: Cannot download the file from https://chromedriver.storage.googleapis.com/86.0.4240.22/chromedriver_win32.zip: self signed certificate in certificate chain
[08:21:08] Error: Cannot download the file from https://chromedriver.storage.googleapis.com/86.0.4240.22/chromedriver_win32.zip: self signed certificate in certificate chain
    at Object.downloadFile (C:\Users\sgopikri\AppData\Roaming\npm\node_modules\appium\node_modules\appium-support\lib\net.js:228:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at installForPlatform (C:\Users\sgopikri\AppData\Roaming\npm\node_modules\appium\node_modules\appium-chromedriver\lib\install.js:75:3)
    at install (C:\Users\sgopikri\AppData\Roaming\npm\node_modules\appium\node_modules\appium-chromedriver\lib\install.js:103:3)
    at Object.doInstall (C:\Users\sgopikri\AppData\Roaming\npm\node_modules\appium\node_modules\appium-chromedriver\lib\install.js:131:5)
[08:21:08] Downloading Chromedriver can be skipped by using the '--chromedriver-skip-install' flag or setting the 'APPIUM_SKIP_CHROMEDRIVER_INSTALL' environment variable.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appium-chromedriver@4.26.2 postinstall: `node install-npm.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the appium-chromedriver@4.26.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sgopikri\AppData\Roaming\npm-cache\_logs\2021-04-30T02_51_18_317Z-debug.log

C:\WINDOWS\system32>npm install appium --chromedriver_version="4.26.2"

> appium-windows-driver@1.17.0 install C:\WINDOWS\system32\node_modules\appium\node_modules\appium-windows-driver
> node install-npm.js

info WinAppDriver WinAppDriver version 1.2-RC already exists with correct checksum, not re-downloading

> core-js@2.6.12 postinstall C:\WINDOWS\system32\node_modules\appium\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

> appium-chromedriver@4.26.2 postinstall C:\WINDOWS\system32\node_modules\appium\node_modules\appium-chromedriver
> node install-npm.js

[08:26:40] [Chromedriver Install] Installing Chromedriver version '4.26.2' for platform 'win' and architecture '32'
[08:26:40] [Chromedriver Install] Opening temp file to write 'chromedriver_win32' to...
[08:26:40] [Chromedriver Install] Opened temp file 'C:\Users\sgopikri\AppData\Local\Temp\2021330-11272-oj3uyu.5zph\chromedriver_win32.zip'
[08:26:40] [Chromedriver Install] Downloading https://chromedriver.storage.googleapis.com/4.26.2/chromedriver_win32.zip to 'C:\Users\sgopikri\AppData\Local\Temp\2021330-11272-oj3uyu.5zph\chromedriver_win32.zip'
[08:26:41] Error installing Chromedriver: Cannot download the file from https://chromedriver.storage.googleapis.com/4.26.2/chromedriver_win32.zip: self signed certificate in certificate chain
[08:26:41] Error: Cannot download the file from https://chromedriver.storage.googleapis.com/4.26.2/chromedriver_win32.zip: self signed certificate in certificate chain
    at Object.downloadFile (C:\WINDOWS\system32\node_modules\appium\node_modules\appium-support\lib\net.js:228:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at installForPlatform (C:\WINDOWS\system32\node_modules\appium\node_modules\appium-chromedriver\lib\install.js:75:3)
    at install (C:\WINDOWS\system32\node_modules\appium\node_modules\appium-chromedriver\lib\install.js:103:3)
    at Object.doInstall (C:\WINDOWS\system32\node_modules\appium\node_modules\appium-chromedriver\lib\install.js:131:5)
[08:26:41] Downloading Chromedriver can be skipped by using the '--chromedriver-skip-install' flag or setting the 'APPIUM_SKIP_CHROMEDRIVER_INSTALL' environment variable.
npm WARN enoent ENOENT: no such file or directory, open 'C:\WINDOWS\system32\package.json'
npm WARN system32 No description
npm WARN system32 No repository field.
npm WARN system32 No README data
npm WARN system32 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appium-chromedriver@4.26.2 postinstall: `node install-npm.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the appium-chromedriver@4.26.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sgopikri\AppData\Roaming\npm-cache\_logs\2021-04-30T02_56_51_604Z-debug.log

**Comment by mykola-mokhnach** [comment]
> self signed certificate in certificate chain

The error is expected. It seems like your network infra has a proxy or something similar, which invalidates the https certificate.

You could also skip chromedriver install by defining the `APPIUM_SKIP_CHROMEDRIVER_INSTALL` environment variable.

**Comment by mykola-mokhnach** [comment]
closed as not an issue
