### ISSUE TITLE
element.click() resolving in a timeout error.

### ISSUE THREAD

**Issue by heychirag** [appium/appium#15321]
## The problem

I have an `await element.click()` in my test code. But the promise never gets resolved even when the button is clicked without fail in the Webview. After ~120000ms, the promise returns a timeout error.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.2
* Last Appium version that did not exhibit the issue (if applicable): Not Sure
* Desktop OS/version used to run Appium: macOS 10.15.7
* Node.js version (unless using Appium.app|exe): v15.14.0
* Npm or Yarn package manager: Npm
* Mobile platform/version under test: iOS 14.5
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

## Details

Even though I can see `element.click()` to be working on the app, the promise never gets resolved. After around 120000ms, the promise gets rejected and results in an error. If I don't `await` the promise, the tests hang for 120000ms, but continue normally after that. 

## Link to Appium logs

Nothing usefull ever emitted in the Logs. Here is log from NodeJS catch.

```
Error: [element.click()] Error response status: 13, UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command. Original error: Did not get any response for atom execution after 120009ms
    at exports.newError (/Volumes/workplace/I18nPickerMobileAutomationTests/src/I18nPickerMobileAutomationTests/node_modules/wd/lib/utils.js:152:13)
    at /Volumes/workplace/I18nPickerMobileAutomationTests/src/I18nPickerMobileAutomationTests/node_modules/wd/lib/callbacks.js:36:19
    at /Volumes/workplace/I18nPickerMobileAutomationTests/src/I18nPickerMobileAutomationTests/node_modules/wd/lib/webdriver.js:196:5
    at Request._callback (/Volumes/workplace/I18nPickerMobileAutomationTests/src/I18nPickerMobileAutomationTests/node_modules/wd/lib/http-utils.js:89:7)
    at Request.self.callback (/Volumes/workplace/I18nPickerMobileAutomationTests/src/I18nPickerMobileAutomationTests/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/Volumes/workplace/I18nPickerMobileAutomationTests/src/I18nPickerMobileAutomationTests/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/Volumes/workplace/I18nPickerMobileAutomationTests/src/I18nPickerMobileAutomationTests/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  status: 13,
  cause: {
    status: 13,
    value: {
      message: 'An unknown server-side error occurred while processing the command. Original error: Did not get any response for atom execution after 120009ms'
    },
    sessionId: '6963c41c-1a7c-4646-9696-d0bbbfbd9211'
  },
  inspect: [Function (anonymous)],
  'jsonwire-error': {
    status: 13,
    summary: 'UnknownError',
    detail: 'An unknown server-side error occurred while processing the command.'
  }
}
```

## Code To Reproduce Issue [ Good To Have ]

This issue is happening on testing of an hybrid app. When a button is clicked inside a `Webview`.

**Comment by mykola-mokhnach** [comment]
Please provide the full server log

**Comment by heychirag** [comment]
@mykola-mokhnach I would have liked to provide it but I updated my iOS and XCode and now I am stuck because of #15325

**Comment by mykola-mokhnach** [comment]
So this issue is no more relevant?

**Comment by mykola-mokhnach** [comment]
Closed because of no response
