### ISSUE TITLE
org.openqa.selenium.StaleElementReferenceException: Cached elements 'By.xpath: //*[@class = 'android.view.View']' do not exist in DOM anymore

### ISSUE THREAD

**Issue by studyJavaForLive** [appium/appium#15348]
## The problem
StaleElementReferenceException has occured when I use 'driver.findElementsByXPath()' method to test.  

"org.openqa.selenium.StaleElementReferenceException: Cached elements 'By.xpath: //*[@class = 'android.view.View']' do not exist in DOM anymore"

## Environment

* Appium version : 1.20.2
* Desktop OS/version used to run Appium: Windows10
* Node.js version (unless using Appium.app|exe): v14.16.1
* Npm or Yarn package manager: 6.14.12
* Mobile platform/version under test: 6.0
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

## Details

2021-05-08 21:59:53:832 [HTTP] --> POST /wd/hub/session/d0163967-05b4-4b05-8299-fe06a2f6d232/element/9109de42-2abb-406a-b56f-ff5e88f32243/elements
2021-05-08 21:59:53:832 [HTTP] {"id":"9109de42-2abb-406a-b56f-ff5e88f32243","using":"xpath","value":"//*[@text='Close']"}
2021-05-08 21:59:53:832 [W3C (d0163967)] Calling AppiumDriver.findElementsFromElement() with args: ["xpath","//*[@text='Close']","9109de42-2abb-406a-b56f-ff5e88f32243","d0163967-05b4-4b05-8299-fe06a2f6d232"]
2021-05-08 21:59:53:832 [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, css selector, -android uiautomator
2021-05-08 21:59:53:832 [BaseDriver] Waiting up to 0 ms for condition
2021-05-08 21:59:53:832 [WD Proxy] Matched '/elements' to command name 'findElements'
2021-05-08 21:59:53:832 [WD Proxy] Proxying [POST /elements] to [POST http://127.0.0.1:8227/wd/hub/session/b116782c-84d9-4d34-9909-583415afc522/elements] with body: {"strategy":"xpath","selector":"//*[@text='Close']","context":"9109de42-2abb-406a-b56f-ff5e88f32243","multiple":true}
2021-05-08 21:59:54:965 [WD Proxy] Got response with status 404: {"sessionId":"b116782c-84d9-4d34-9909-583415afc522","value":{"error":"stale element reference","message":"Cached elements 'By.xpath: //*[@class = 'android.view.View']' do not exist in DOM anymore","stacktrace":"io.appium.uiautomator2.common.exceptions.StaleElementReferenceException: Cached elements 'By.xpath: //*[@class = 'android.view.View']' do not exist in DOM anymore\n\tat io.appium.uiautomator2.model.ElementsCache.restore(ElementsCache.java:72)\n\tat io.appium.uiautomator2.model.ElementsCache.get(ElementsCache.java:145)\n\tat io.appium.uiautomator2.handler.FindElements.findElements(FindElements.java:122)\n\tat io.appium.uiautomator2.handler.FindElements.safeHandle(FindElements.java:80)\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:41)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:261)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:255)\n\tat io.appium.uiautomator2.http.ServerHa...
2021-05-08 21:59:54:965 [W3C] Matched W3C error code 'stale element reference' to StaleElementReferenceError
2021-05-08 21:59:55:032 [W3C (d0163967)] Encountered internal error running command: io.appium.uiautomator2.common.exceptions.StaleElementReferenceException: Cached elements 'By.xpath: //*[@class = 'android.view.View']' do not exist in DOM anymore
2021-05-08 21:59:55:032 [W3C (d0163967)] 	at io.appium.uiautomator2.model.ElementsCache.restore(ElementsCache.java:72)
2021-05-08 21:59:55:032 [W3C (d0163967)] 	at io.appium.uiautomator2.model.ElementsCache.get(ElementsCache.java:145)
2021-05-08 21:59:55:033 [W3C (d0163967)] 	at io.appium.uiautomator2.handler.FindElements.findElements(FindElements.java:122)
2021-05-08 21:59:55:033 [W3C (d0163967)] 	at io.appium.uiautomator2.handler.FindElements.safeHandle(FindElements.java:80)
2021-05-08 21:59:55:033 [W3C (d0163967)] 	at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:41)
2021-05-08 21:59:55:033 [W3C (d0163967)] 	at io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:261)
2021-05-08 21:59:55:033 [W3C (d0163967)] 	at io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:255)
2021-05-08 21:59:55:033 [W3C (d0163967)] 	at io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:68)
2021-05-08 21:59:55:033 [W3C (d0163967)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
2021-05-08 21:59:55:033 [W3C (d0163967)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
2021-05-08 21:59:55:033 [W3C (d0163967)] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
2021-05-08 21:59:55:033 [W3C (d0163967)] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
2021-05-08 21:59:55:033 [W3C (d0163967)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
2021-05-08 21:59:55:033 [W3C (d0163967)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
2021-05-08 21:59:55:033 [W3C (d0163967)] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
2021-05-08 21:59:55:033 [W3C (d0163967)] 	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
2021-05-08 21:59:55:033 [W3C (d0163967)] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
2021-05-08 21:59:55:033 [W3C (d0163967)] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
2021-05-08 21:59:55:033 [W3C (d0163967)] 	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
2021-05-08 21:59:55:033 [W3C (d0163967)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
2021-05-08 21:59:55:033 [W3C (d0163967)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
2021-05-08 21:59:55:033 [W3C (d0163967)] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
2021-05-08 21:59:55:033 [W3C (d0163967)] 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
2021-05-08 21:59:55:033 [W3C (d0163967)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
2021-05-08 21:59:55:033 [W3C (d0163967)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
2021-05-08 21:59:55:033 [W3C (d0163967)] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
2021-05-08 21:59:55:033 [W3C (d0163967)] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
2021-05-08 21:59:55:033 [W3C (d0163967)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
2021-05-08 21:59:55:033 [W3C (d0163967)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
2021-05-08 21:59:55:033 [W3C (d0163967)] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
2021-05-08 21:59:55:033 [W3C (d0163967)] 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
2021-05-08 21:59:55:033 [W3C (d0163967)] 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)
2021-05-08 21:59:55:033 [W3C (d0163967)] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:514)
2021-05-08 21:59:55:033 [W3C (d0163967)] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:468)
2021-05-08 21:59:55:033 [W3C (d0163967)] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
2021-05-08 21:59:55:033 [W3C (d0163967)] 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
2021-05-08 21:59:55:033 [W3C (d0163967)] 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
2021-05-08 21:59:55:033 [W3C (d0163967)] 	at java.lang.Thread.run(Thread.java:818)
2021-05-08 21:59:55:033 [W3C (d0163967)] 
2021-05-08 21:59:55:034 [HTTP] <-- POST /wd/hub/session/d0163967-05b4-4b05-8299-fe06a2f6d232/element/9109de42-2abb-406a-b56f-ff5e88f32243/elements 404 1202 ms - 4055

## Code To Reproduce Issue [ Good To Have ]

driver.findElementsByXPath("//*[@class = 'android.view.View']")

**Comment by studyJavaForLive** [comment]
##LogCat Log：
05-08 20:59:34.958 12062 12090 I appium  : method: 'xpath', selector: '//*[@text='Close']', contextId: '9109de42-2abb-406a-b56f-ff5e88f32243'

05-08 20:59:34.997   234   688 E BufferQueueProducer: [Expanded Home Panel] dequeueBuffer: can't dequeue multiple buffers without setting the buffer count

05-08 20:59:35.204 12551 12551 I CHK:ver : ***.*** | D0DX1450 0.49 

05-08 20:59:35.237  1323  1323 I SSETTINGS:: FE:Reducer action.type=HIDE_ORIGINAL_LOADING -- From line 1 of /scripts/main.js

05-08 20:59:35.238  1323  1323 I SSETTINGS:: FE:mapStateToProps -- From line 1 of /scripts/main.js

05-08 20:59:35.271  1323  1323 I SSETTINGS:: FE:Root render state=frontEnd, loading=false -- From line 1 of /scripts/main.js

05-08 20:59:35.272  1323  2460 I SSETTINGS:FrontEndJavascriptInterface: getLanguage() = en

05-08 20:59:35.299  1323  1323 I SSETTINGS:: FE:Reducer action.type=HIDE_ORIGINAL_LOADING -- From line 1 of /scripts/main.js

05-08 20:59:35.300  1323  1323 I SSETTINGS:: FE:mapStateToProps -- From line 1 of /scripts/main.js

05-08 20:59:35.305  1323  1323 I SSETTINGS:: FE:Root render state=frontEnd, loading=false -- From line 1 of /scripts/main.js

05-08 20:59:35.307  1323  2460 I SSETTINGS:FrontEndJavascriptInterface: getLanguage() = en

05-08 20:59:35.777 12555 12555 I CHK:eMMC: 042.000 | 0x0000 0x0008 0x0005 

05-08 20:59:36.072 12062 12090 I appium  : The element identified by '9109de42-2abb-406a-b56f-ff5e88f32243' has been reported as stale (null). Trying to restore it

05-08 20:59:36.077 12062 12090 I appium  : AppiumResponse: {"sessionId":"b116782c-84d9-4d34-9909-583415afc522","value":{"error":"stale element reference","message":"Cached elements 'By.xpath: //*[@class = 'android.view.View']' do not exist in DOM anymore","stacktrace":"io.appium.uiautomator2.common.exceptions.StaleElementReferenceException: Cached elements 'By.xpath: //*[@class = 'android.view.View']' do not exist in DOM anymore\n\tat io.appium.uiautomator2.model.ElementsCache.restore(ElementsCache.java:72)\n\tat io.appium.uiautomator2.model.ElementsCache.get(ElementsCache.java:145)\n\tat io.appium.uiautomator2.handler.FindElements.findElements(FindElements.java:122)\n\tat io.appium.uiautomator2.handler.FindElements.safeHandle(FindElements.java:80)\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:41)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:261)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:255)\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:68)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\n\tat io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\n\tat io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)\n\tat io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)\n\tat io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)\n\tat io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\n\tat io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\n\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)\n\tat io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:514)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:468)\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)\n\tat io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.jav

05-08 20:59:36.300 12558 12558 I CHK:ver : ***.*** | D0DX1450 0.49 

05-08 20:59:36.862 12565 12565 I CHK:pid : 043.000 | pkg,jp.co.ricoh.advop.remotecontrolservice,10046,1,1592995509000,1619050051000,? 

05-08 20:59:36.981  2433  2433 I Inst:NatSetSrv: onStart ACTION=NO_ACTIONfirstNaSet:true

05-08 20:59:37.382 12566 12566 I CHK:pid : 043.001 | pkg,jp.co.ricoh.advop.simpledirectconnection,10084,15,1593477977000,1616745792613,jp.co.ricoh.advop.simpledirectconnection 

05-08 20:59:37.903 12569 12569 I CHK:pid : 043.002 | pkg,jp.co.ricoh.advop.tonerstate,10093,1,1593477985000,1616745976595,jp.co.ricoh.advop.tonerstate 

05-08 20:59:38.338  1255  1255 I BnrServ::   update mPrintTimeText clear

05-08 20:59:38.340  1255  1255 I BnrServ:: message switch: current=0,next=1

05-08 20:59:38.381  1310 12164 E global  : InetAddress.java lookupHostByName() ip=/fe80::226:73ff:fe0c:d60f%usb0%4 len=1

05-08 20:59:38.381  1310 12164 E global  : InetAddress.java lookupHostByName() save cache

05-08 20:59:38.427 12571 12571 I CHK:pid : 043.003 | pkg,io.appium.settings,10101,28,1619766486425,1619766486425,? 

05-08 20:59:38.459   650  1040 W WindowManager: Attempted to remove non-existing token: android.os.Binder@bddfb47

05-08 20:59:38.951 12572 12572 I CHK:pid : 043.004 | pkg,com.ricoh.multidevicehub,10066,1,1593477958000,1620465812924,com.ricoh.multidevicehub 

05-08 20:59:39.475 12573 12573 I CHK:pid : 043.005 | pkg,com.android.providers.calendar,10001,23,1592995292000,1619049926000,? 

05-08 20:59:39.889  1008  1008 I LegacyUIapl: send MoniServStateAsk

05-08 20:59:39.891  1200  1200 I MoniServ:AppBrdcastHndl(R: Recv[jp.co.ricoh.advop.legacy.MONITOR_SERVICE_STATE_ASK]

05-08 20:59:39.892  1008  1008 I LegacyUIapl: MoniServPolling: 1047->1048

05-08 20:59:40.001 12577 12577 I CHK:pid : 043.006 | pkg,jp.co.ricoh.advop.helpservice,10089,10,1593477966000,1616745879573,jp.co.ricoh.advop.helpservice 

05-08 20:59:40.038  2411  2424 E global  : InetAddress.java lookupHostByName() ip=/fe80::226:73ff:fe0c:d60f%usb0%4 len=1

05-08 20:59:40.038  2411  2424 E global  : InetAddress.java lookupHostByName() save cache

05-08 20:59:40.523 12583 12583 I CHK:pid : 043.007 | pkg,com.android.providers.media,10004,800,1592995292000,1619049926000,? 

05-08 20:59:40.627 12581 12581 I imx6.gralloc: open gpu gralloc module!

05-08 20:59:41.046 12589 12589 I CHK:pid : 043.008 | pkg,jp.co.omronsoft.iwnnime.languagepack.kokr,10085,6,1593477958000,1612245596294,jp.co.omronsoft.iwnnime.languagepack.kokr 

05-08 20:59:41.514  1808  1808 I SrvServ : Jettystate:STARTED server:org.eclipse.jetty.server.Server@64eafda on port 55101 ServiceEnabled:true

05-08 20:59:41.566 12594 12594 I CHK:pid : 043.009 | pkg,jp.co.omronsoft.iwnnime.languagepack.zhcn,10087,6,1593477958000,1612245598173,jp.co.omronsoft.iwnnime.languagepack.zhcn 

05-08 20:59:41.618  1362  1362 I CSPF_SWS: [SystemWrapperService]onStartCommand

05-08 20:59:42.022  2433  2433 I Inst:NatSetSrv: onStart ACTION=NO_ACTIONfirstNaSet:true

05-08 20:59:42.089 12600 12600 I CHK:pid : 043.010 | pkg,jp.co.omronsoft.iwnnime.languagepack.zhtw,10096,6,1593477959000,1612245599788,jp.co.omronsoft.iwnnime.languagepack.zhtw 

05-08 20:59:42.118 12588 12588 E memtrack: Couldn't load memtrack module (No such file or directory)

05-08 20:59:42.118 12588 12588 E android.os.Debug: failed to load memtrack module: -2

05-08 20:59:42.121 12588 12588 I ethernet: Loading ethernet jni class

05-08 20:59:42.129 12588 12588 I Radio-JNI: register_android_hardware_Radio DONE

05-08 20:59:42.180  2411  2424 E global  : InetAddress.java lookupHostByName() ip=/fe80::226:73ff:fe0c:d60f%usb0%4 len=1

05-08 20:59:42.180  2411  2424 E global  : InetAddress.java lookupHostByName() save cache

05-08 20:59:42.193   650  2675 W MountService: No primary storage defined yet; hacking together a stub

05-08 20:59:42.611 12606 12606 I CHK:pid : 043.011 | pkg,jp.co.ricoh.advop.remotesupport,1000,1,1616745786989,1620465825094,jp.co.ricoh.advop.remotesupport 

05-08 20:59:43.131 12607 12607 I CHK:pid : 043.012 | pkg,jp.co.ricoh.advop.serverservice,10049,10000096,1592995509000,1619050051000,? 

05-08 20:59:43.641 12604 12604 E memtrack: Couldn't load memtrack module (No such file or directory)

05-08 20:59:43.641 12604 12604 E android.os.Debug: failed to load memtrack module: -2

05-08 20:59:43.645 12604 12604 I ethernet: Loading ethernet jni class

05-08 20:59:43.653 12604 12604 I Radio-JNI: register_android_hardware_Radio DONE

05-08 20:59:43.654 12613 12613 I CHK:pid : 043.013 | pkg,jp.co.ricoh.advop.systemmessage,10060,1,1592995509000,1619050051000,? 

05-08 20:59:44.174 12617 12617 I CHK:pid : 043.014 | pkg,com.android.wallpapercropper,10015,23,1592995332000,1619049926000,? 

05-08 20:59:44.338  1255  1255 I BnrServ::   update mPrintTimeText clear

05-08 20:59:44.695 12620 12620 I CHK:pid : 043.015 | pkg,jp.co.ricoh.isdk.appsite,10063,2021031701,1593477987000,1616745833313,jp.co.ricoh.isdk.appsite 

05-08 20:59:44.820 12604 12604 W AccessibilityNodeInfoDumper: Fetch time: 68ms

05-08 20:59:44.821   650  2675 W WindowManager: Attempted to remove non-existing token: android.os.Binder@f87c043

05-08 20:59:45.215 12622 12622 I CHK:pid : 043.016 | pkg,jp.co.ricoh.initilize,1000,6,1592995509000,1619050051000,? 

05-08 20:59:45.735 12625 12625 I CHK:pid : 043.017 | pkg,com.android.launcher,10006,23,1592995359000,1619049926000,? 

05-08 20:59:46.221   249   431 I LegacyUIocsx: [MN][1,0,0,1620468175.148,0,0,0,0x0,255,0x0,0,0,0,0,0]

05-08 20:59:46.257 12628 12628 I CHK:pid : 043.018 | pkg,jp.co.ricoh.advop.counterservice,10023,6,1592995509000,1619050051000,? 

05-08 20:59:46.777 12629 12629 I CHK:pid : 043.019 | pkg,com.android.documentsui,10024,23,1592995509000,1619050051000,? 

05-08 20:59:47.056  2433  2433 I Inst:NatSetSrv: onStart ACTION=NO_ACTIONfirstNaSet:true

05-08 20:59:47.299 12633 12633 I CHK:pid : 043.020 | pkg,jp.co.ricoh.advop.voicecontrolservice,10070,1,1593477986000,1616745804406,jp.co.ricoh.advop.voicecontrolservice 

05-08 20:59:47.308  2411  2424 E global  : InetAddress.java lookupHostByName() ip=/fe80::226:73ff:fe0c:d60f%usb0%4 len=1

05-08 20:59:47.308  2411  2424 E global  : InetAddress.java lookupHostByName() save cache

05-08 20:59:47.820 12635 12635 I CHK:pid : 043.021 | pkg,com.android.externalstorage,10005,23,1592995292000,1619049926000,? 

05-08 20:59:48.341 12636 12636 I CHK:pid : 043.022 | pkg,com.android.htmlviewer,10027,23,1592995509000,1619050051000,? 

05-08 20:59:48.384  1310 12164 E global  : InetAddress.java lookupHostByName() ip=/fe80::226:73ff:fe0c:d60f%usb0%4 len=1

05-08 20:59:48.385  1310 12164 E global  : InetAddress.java lookupHostByName() save cache

**Comment by mykola-mokhnach** [comment]
The error looks valid to me. What are you trying to achieve there?

**Comment by studyJavaForLive** [comment]
Thank u for your reply. 
I found the exception in three places：
app\src\main\java\io\appium\uiautomator2\model\ElementsCache.java
final By by = element.getBy();
if (by == null) {
    throw new StaleElementReferenceException(String.format(
            "The element '%s' does not exist in DOM anymore", element.getId()));
}
// We cannot restore a single element from a locator that matches multiple items
  if (!element.isSingleMatch()) {
      throw new StaleElementReferenceException(String.format(
              "Cached elements '%s' do not exist in DOM anymore", by));
  }
if (ui2Object == null) {
    throw new StaleElementReferenceException(String.format(
            "The element '%s' does not exist in DOM anymore", by));
}
I want to know whether this error can be avoided. Looking forward to your reply. Thank u!

**Comment by mykola-mokhnach** [comment]
No, it cannot be avoided

**Comment by mykola-mokhnach** [comment]
> What dose the mean of 'element.isSingleMatch()'?

This method returns true if the locator is expected to return a single element

> Is the [driver.findElementsByXPath("//*[@Class = 'android.view.View']")] I have used not suitable?

No idea. depending on what you are trying to achieve

**Comment by studyJavaForLive** [comment]
Thank u very much! Thanks for your patience!
 I still have a uncertain question.
'driver.findElementsByXPath' should get multiple element. Isn‘t it？

**Comment by mykola-mokhnach** [comment]
yes it should

**Comment by mykola-mokhnach** [comment]
It would be null if the given identifier does not exist in the cache.
Please use Appium forum to ask generic questions or join Appium slack if you'd like to join the project development.
Closed as not an issue
