### ISSUE TITLE
raise exception adb.exe -P 5037 -s 1561c4e6 forward --remove tcp\:10900' exited with code 1'; Stderr: 'adb.exe: error: listener 'tcp:10900' not found'; Code: '1' 

### ISSUE THREAD

**Issue by leeyc0704** [appium/appium#15390]
## The problem

i use appium for parallel testing of two phones，when i use appium version 1.13，everything is ok，but when i use appium version 1.18，very high chance appear " forward --remove tcp\:10900' exited with code 1'; Stderr: 'adb.exe: error: listener 'tcp:10900' not found'; Code: '1'"
see the log，version 1.13 will adb.exe -P 5037 -s phoneuuid forward tcp\:31015 tcp\:6790 once and never remove，but version 1.18 will  forward tcp many times then remove many timies， why log is different and why adb remove port will fail, i have tried many sdk version but still can not resolve.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.13 and 1.18
* Mobile platform/version under test:android 8 and android 7
* Real device or emulator/simulator: real
* Appium CLI or Appium.app|exe:appium cmd

## Link to Appium logs

`
1.13 part log bellow
**2021-05-18 15:34:32:903 [UiAutomator2] Forwarding UiAutomator2 Server port 6790 to 31015**
**2021-05-18 15:34:32:904 [ADB] Forwarding system: 31015 to device: 6790**
2021-05-18 15:34:32:905 [ADB] Running 'E:\sdk\platform-tools\adb.exe -P 5037 -s 1561c4e6 forward tcp\:31015 tcp\:6790'
2021-05-18 15:34:33:112 [UiAutomator2] No app capability. Assuming it is already on the device
2021-05-18 15:34:33:116 [UiAutomator2] Performing shallow cleanup of automation leftovers
2021-05-18 15:34:33:173 [UiAutomator2] The following obsolete sessions are still running: ["e6cb1099-ac6b-42b0-9b0f-24587b9c57b4"]
2021-05-18 15:34:33:174 [UiAutomator2] Cleaning up the obsolete sessions
2021-05-18 15:34:34:205 [ADB] Running 'E:\sdk\platform-tools\adb.exe -P 5037 -s 1561c4e6 shell am force-stop io.appium.uiautomator2.server.test'
2021-05-18 15:34:34:501 [UiAutomator2] Starting UIAutomator2 server 3.7.0

1.18 part log bellow
2021-05-19 13:40:57:876 [ADB] Running 'F:\software\sdk\platform-tools\adb.exe -P 5037 -s SWYDU16521001468 forward tcp:10900 localabstract:webview_devtools_remote_22125'
2021-05-19 13:40:58:131 [ADB] Removing forwarded port socket connection: 10900 
2021-05-19 13:40:58:131 [ADB] Running 'F:\software\sdk\platform-tools\adb.exe -P 5037 -s SWYDU16521001468 forward --remove tcp:10900'
2021-05-19 13:40:58:411 [MJSONWP (15b5b17d)] Encountered internal error running command: Error executing adbExec. **Original error: 'Command 'F:\\software\\sdk\\platform-tools\\adb.exe -P 5037 -s SWYDU16521001468 forward --remove tcp\:10900' exited with code 1'; Stderr: 'error: listener 'tcp:10900' not found'; Code: '1'**
2021-05-19 13:40:58:412 [MJSONWP (15b5b17d)] Error: Command 'F:\\software\\sdk\\platform-tools\\adb.exe -P 5037 -s SWYDU16521001468 forward --remove tcp\:10900' exited with code 1
2021-05-19 13:40:58:412 [MJSONWP (15b5b17d)]     at ChildProcess.<anonymous> (G:\Software\nodejs\node_global\node_modules\appium\node_modules\_teen_process@1.15.0@teen_process\lib\exec.js:113:19)
2021-05-19 13:40:58:412 [MJSONWP (15b5b17d)]     at ChildProcess.emit (events.js:314:20)
2021-05-19 13:40:58:413 [MJSONWP (15b5b17d)]     at maybeClose (internal/child_process.js:1047:16)
2021-05-19 13:40:58:413 [MJSONWP (15b5b17d)]     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
2021-05-19 13:40:58:416 [HTTP] <-- GET /wd/hub/session/15b5b17d-f6a5-427d-aebf-7d8e29bbd41c/contexts 500 812 ms - 410

`

**Comment by leeyc0704** [comment]
> Unfortunately we do not patch old versions. Please try with the most recent server release (1.21). Also, please attach the full log if it still fails

I will try the latest version later, this issue is temporarily closed

**Comment by Jiurong-Yang** [comment]
I see this error show up all the time for many versions, we are currently using version 1.20.2. Not the latest but I do not see this patched in the release notes.

**Comment by Jiurong-Yang** [comment]
Ok I found the issue. 
https://github.com/appium/appium-android-driver/blob/c3a1e8c29f1a87761f5112bc8fe36198e2762287/lib/webview-helpers.js#L147
For the port that's being used here it was not stated in the desired_capabilities that the "webviewDevtoolsPort" dc is the start of a range of 100 ports that could be allocated. I assumed the port specified by the dc is what Appium will always use but that's not True apparently. 

So there is a race condition for parallel execution. 
When allocating for the port https://github.com/appium/appium-android-driver/blob/c3a1e8c29f1a87761f5112bc8fe36198e2762287/lib/webview-helpers.js#L236

Race condition happens, then fails into the catch block, then the catch block tries to remove a forward that never happened. Hence the failure. 
The solution is simple (but annoying) on our end, we just have to make sure we space out the "webviewDevtoolsPort" value by 100 to avoid a race condition from happening. But I would ask what's the reason for "webviewDevtoolsPort" to use a range of ports instead of just the one specified?

**Comment by mykola-mokhnach** [comment]
Do you run parallel tests in scope of a process single or as separate node processes?
I can observe that there is a lock for the port allocation, but it is only applicable if a single-process approach is used

**Comment by mykola-mokhnach** [comment]
> But I would ask what's the reason for "webviewDevtoolsPort" to use a range of ports instead of just the one specified?

The initial idea was that the driver could automatically select the target port if the capability is not set while running parallel tests in scope of the SAME process. Then the AsyncLock in memory lock works as expected and does not allow port conflict to happen. Although it's completely useless when sessions are executed on per-process basis, because this lock type is not shared. Then the best way to make sure ports are unique would be to tune the `webviewDevtoolsPort` value manually for each session

**Comment by Jiurong-Yang** [comment]
> 
> 
> > But I would ask what's the reason for "webviewDevtoolsPort" to use a range of ports instead of just the one specified?
> 
> The initial idea was that the driver could automatically select the target port if the capability is not set while running parallel tests in scope of the SAME process. Then the AsyncLock in-memory lock works as expected and does not allow port conflict to happen. Although it's completely useless when sessions are executed on per-process basis, because this lock type is not shared. Then the best way to make sure ports are unique would be to tune the `webviewDevtoolsPort` value manually for each session

Yeah I see how that solves the issues for when running parallel tests on the SAME process. For the longest time as I recall Appium did not support multiple sessions on a single server so that's not our default mode of usage (we do per process). But having to block off hundreds of ports just to avoid a race condition in the per process model is not ideal. I'm glad you put in a fix to use file lock, but I see in the comments you said spacing out the ports are still preferred. 

Is there a way maybe we can reduce the range to something like 50 or 25, or make them be ranges (since you are using these as ranges anyways). If you allocated 100 ports per port needed per process
That's 100 systemPort + 100 webDevtool + X chromedriverPort (depending on config) and optional 100 for espresso. That's a lot of ports allocated for 1 device. For setups that run a lot of devices this can be a burden on the system. Especially when working in an enterprise environment and the cyber security people are trying to lock down as many ports as possible.

**Comment by mykola-mokhnach** [comment]
> Especially when working in an enterprise environment and the cyber security people are trying to lock down as many ports as possible.

It is a pure localhost connection. These ports must not be opened to the outside IP addresses

**Comment by Jiurong-Yang** [comment]
It's not about having to close our ports. It's that cyber security scans the hosts so much that we have to put up firewalls to prevent getting ddosed. But I mean I'm sure it might be an unique situation for us.
