### ISSUE TITLE
Script timeout - NotImplementedError

### ISSUE THREAD

**Issue by DmitryMishtal** [appium/appium#15391]
Hello community,

Appium version: 1.21.0
Appium java client: 7.5.1

When i'm trying to set timeout to script with command below:

`
driver.manage().timeouts().setScriptTimeout(3, TimeUnit.SECONDS);
`
, i'm getting exception:

```
[HTTP] --> POST /wd/hub/session/78738a54-c681-4410-9beb-71199e8a3b6d/timeouts
[HTTP] {"script":3000}
[debug] [W3C (78738a54)] Calling AppiumDriver.timeouts() with args: [null,null,3000,null,null,"78738a54-c681-4410-9beb-71199e8a3b6d"]
[debug] [BaseDriver] W3C timeout argument: {"script":3000}}
[debug] [W3C (78738a54)] Encountered internal error running command: NotImplementedError: Not implemented yet for script.
[debug] [W3C (78738a54)]     at Mac2Driver.scriptTimeoutW3C (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/timeout.js:94:9)
[debug] [W3C (78738a54)]     at Mac2Driver.timeouts (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/timeout.js:37:16)
[debug] [W3C (78738a54)]     at commandExecutor (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:335:9)
[debug] [W3C (78738a54)]     at /usr/local/lib/node_modules/appium/node_modules/async-lock/lib/index.js:137:12
[debug] [W3C (78738a54)]     at AsyncLock._promiseTry (/usr/local/lib/node_modules/appium/node_modules/async-lock/lib/index.js:261:31)
[debug] [W3C (78738a54)]     at exec (/usr/local/lib/node_modules/appium/node_modules/async-lock/lib/index.js:136:9)
[debug] [W3C (78738a54)]     at AsyncLock.acquire (/usr/local/lib/node_modules/appium/node_modules/async-lock/lib/index.js:152:3)
[debug] [W3C (78738a54)]     at Mac2Driver.executeCommand (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:348:39)
[debug] [W3C (78738a54)]     at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/lib/appium.js:563:36)
[debug] [W3C (78738a54)]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[debug] [W3C (78738a54)]     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:297:21)
```
On appium version 1.20 i did not observed such error. It appeared only after install of 1.21 vesion

**Comment by mykola-mokhnach** [comment]
This is expected. mac2 driver does not support such feature

**Comment by DmitryMishtal** [comment]
Thanks for response. If there is no need to add this feature, i'm closing the ticket
