### ISSUE TITLE
Cannot verify the signature of ‘appium-uiautomator2-server-v4.17.4.apk ’.

### ISSUE THREAD

**Issue by studyJavaForLive** [appium/appium#15563]
## The problem

Encountered internal error running command: Error: Cannot verify the signature of 'C:\Users\xx\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.17.4.apk'. Original error: java.lang.UnsupportedClassVersionError: com/android/apksigner/ApkSignerTool has been compiled by a more recent version of the Java Runtime **(class file version 53.0)**, this version of the Java Runtime only recognizes class file **versions up to 52.0**

Android SDK build-tools API info:
ANDROID_HOME/build-tools/30.0.0/lib/apksigner.jar

Is the version of android sdk api required when appium-uiautomator2-server-v4.17.4.apk is signing? 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.2
* Last Appium version that did not exhibit the issue (if applicable):1.20.2
* Desktop OS/version used to run Appium: windows10
* Node.js version (unless using Appium.app|exe): v14.16.1
* Npm or Yarn package manager: npm
* Mobile platform/version under test: 6.0
* Real device or emulator/simulator:Real
* Appium CLI or Appium.app|exe:CLI

## Details

Android SDK build-tools API info:
ANDROID_HOME/build-tools/30.0.0/lib/apksigner.jar

## Appium logs

2021-06-21 19:44:34:855 [Appium] Welcome to Appium v1.20.2
2021-06-21 19:44:34:856 [Appium] Non-default server args:
2021-06-21 19:44:34:856 [Appium]   port: 4494
2021-06-21 19:44:34:856 [Appium]   logFile: ./appiumLog/appium_CheetahCase_06211939_Test_3.log
2021-06-21 19:44:34:857 [Appium]   loglevel: error:debug
2021-06-21 19:44:34:857 [Appium]   logTimestamp: true
2021-06-21 19:44:34:857 [Appium]   localTimezone: true
2021-06-21 19:44:34:910 [Appium] Appium REST http interface listener started on 0.0.0.0:4494
2021-06-21 19:45:43:616 [HTTP] Request idempotency key: a98a75ea-fbce-4c6d-b66f-84b7e10cf02c
2021-06-21 19:45:43:857 [HTTP] --> POST /wd/hub/session
2021-06-21 19:45:43:857 [HTTP] {"desiredCapabilities":{"noSign":true,"uiautomator2ServerInstallTimeout":120000,"deviceName":"165.96.211.127:49110","ignoreUnimportantViews":false,"appWaitDuration":40000,"newCommandTimeout":864000,"adbExecTimeout":120000,"platformVersion":"6.0","automationName":"UiAutomator2","unicodeKeyboard":true,"platformName":"Android","udid":"165.96.211.127:49110","resetKeyboard":true,"systemPort":"8200"},"capabilities":{"firstMatch":[{"appium:adbExecTimeout":120000,"appium:appWaitDuration":40000,"appium:automationName":"UiAutomator2","appium:deviceName":"165.96.211.127:49110","appium:ignoreUnimportantViews":false,"appium:newCommandTimeout":864000,"appium:noSign":true,"platformName":"android","appium:platformVersion":"6.0","appium:resetKeyboard":true,"appium:systemPort":"8200","appium:udid":"165.96.211.127:49110","uiautomator2ServerInstallTimeout":120000,"appium:unicodeKeyboard":true}]}}
2021-06-21 19:45:43:858 [W3C] Calling AppiumDriver.createSession() with args: [{"noSign":true,"uiautomator2ServerInstallTimeout":120000,"deviceName":"165.96.211.127:49110","ignoreUnimportantViews":false,"appWaitDuration":40000,"newCommandTimeout":864000,"adbExecTimeout":120000,"platformVersion":"6.0","automationName":"UiAutomator2","unicodeKeyboard":true,"platformName":"Android","udid":"165.96.211.127:49110","resetKeyboard":true,"systemPort":"8200"},null,{"firstMatch":[{"appium:adbExecTimeout":120000,"appium:appWaitDuration":40000,"appium:automationName":"UiAutomator2","appium:deviceName":"165.96.211.127:49110","appium:ignoreUnimportantViews":false,"appium:newCommandTimeout":864000,"appium:noSign":true,"platformName":"android","appium:platformVersion":"6.0","appium:resetKeyboard":true,"appium:systemPort":"8200","appium:udid":"165.96.211.127:49110","uiautomator2ServerInstallTimeout":120000,"appium:unicodeKeyboard":true}]}]
2021-06-21 19:45:43:904 [BaseDriver] Event 'newSessionRequested' logged at 1624272343859 (19:45:43 GMT+0900 (鏃ユ湰妯欐簴鏅�))
2021-06-21 19:45:43:907 [BaseDriver] The following capabilities are not standard capabilities and should have an extension prefix:
2021-06-21 19:45:43:907 [BaseDriver]   uiautomator2ServerInstallTimeout
2021-06-21 19:45:52:770 [Appium] Appium v1.20.2 creating new AndroidUiautomator2Driver (v1.61.2) session
2021-06-21 19:45:52:772 [BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
2021-06-21 19:45:52:772 [BaseDriver] Creating session with W3C capabilities: {
2021-06-21 19:45:52:772 [BaseDriver]   "alwaysMatch": {
2021-06-21 19:45:52:772 [BaseDriver]     "platformName": "android",
2021-06-21 19:45:52:772 [BaseDriver]     "appium:uiautomator2ServerInstallTimeout": 120000,
2021-06-21 19:45:52:773 [BaseDriver]     "appium:adbExecTimeout": 120000,
2021-06-21 19:45:52:773 [BaseDriver]     "appium:appWaitDuration": 40000,
2021-06-21 19:45:52:773 [BaseDriver]     "appium:automationName": "UiAutomator2",
2021-06-21 19:45:52:773 [BaseDriver]     "appium:deviceName": "165.96.211.127:49110",
2021-06-21 19:45:52:773 [BaseDriver]     "appium:ignoreUnimportantViews": false,
2021-06-21 19:45:52:773 [BaseDriver]     "appium:newCommandTimeout": 864000,
2021-06-21 19:45:52:773 [BaseDriver]     "appium:noSign": true,
2021-06-21 19:45:52:773 [BaseDriver]     "appium:platformVersion": "6.0",
2021-06-21 19:45:52:773 [BaseDriver]     "appium:resetKeyboard": true,
2021-06-21 19:45:52:773 [BaseDriver]     "appium:systemPort": "8200",
2021-06-21 19:45:52:773 [BaseDriver]     "appium:udid": "165.96.211.127:49110",
2021-06-21 19:45:52:773 [BaseDriver]     "appium:unicodeKeyboard": true
2021-06-21 19:45:52:773 [BaseDriver]   },
2021-06-21 19:45:52:773 [BaseDriver]   "firstMatch": [
2021-06-21 19:45:52:773 [BaseDriver]     {}
2021-06-21 19:45:52:773 [BaseDriver]   ]
2021-06-21 19:45:52:773 [BaseDriver] }
2021-06-21 19:45:52:775 [BaseDriver] Number capability passed in as string. Functionality may be compromised.
2021-06-21 19:45:52:778 [BaseDriver] Capability 'systemPort' changed from string ('8200') to integer (8200). This may cause unexpected behavior
2021-06-21 19:45:52:784 [BaseDriver] The following capabilities were provided, but are not recognized by Appium:
2021-06-21 19:45:52:784 [BaseDriver]   ignoreUnimportantViews
2021-06-21 19:45:52:785 [BaseDriver] Session created with session id: fbb7fd0e-0d29-43c2-b632-a335b64548e4
2021-06-21 19:45:52:785 [UiAutomator2] Neither 'app' nor 'appPackage' was set. Starting UiAutomator2 without the target application
2021-06-21 19:45:52:816 [ADB] Found 1 'build-tools' folders under 'C:\Users\xx\AppData\Local\Android\Sdk' (newest first):
2021-06-21 19:45:52:816 [ADB]     C:/Users/xx/AppData/Local/Android/Sdk/build-tools/30.0.0
2021-06-21 19:45:52:817 [ADB] Using 'adb.exe' from 'C:\Users\xx\AppData\Local\Android\Sdk\platform-tools\adb.exe'
2021-06-21 19:45:52:817 [ADB] Running 'C:\Users\xx\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 start-server'
2021-06-21 19:45:53:794 [AndroidDriver] Retrieving device list
2021-06-21 19:45:53:794 [ADB] Trying to find a connected android device
2021-06-21 19:45:53:795 [ADB] Getting connected devices
2021-06-21 19:45:54:307 [ADB] Connected devices: [{"udid":"165.96.211.127:49110","state":"device"}]
2021-06-21 19:45:54:308 [AndroidDriver] Using device: 165.96.211.127:49110
2021-06-21 19:45:54:309 [ADB] Using 'adb.exe' from 'C:\Users\xx\AppData\Local\Android\Sdk\platform-tools\adb.exe'
2021-06-21 19:45:54:309 [ADB] Running 'C:\Users\xx\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 start-server'
2021-06-21 19:45:54:822 [ADB] Setting device id to 165.96.211.127:49110
2021-06-21 19:45:54:823 [ADB] Running 'C:\Users\xx\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 165.96.211.127:49110 shell getprop ro.build.version.sdk'
2021-06-21 19:45:55:376 [ADB] Current device property 'ro.build.version.sdk': 23
2021-06-21 19:45:55:376 [ADB] Device API level: 23
2021-06-21 19:45:55:377 [AndroidDriver] No app sent in, not parsing package/activity
2021-06-21 19:45:55:377 [ADB] Running 'C:\Users\xx\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 165.96.211.127:49110 wait-for-device'
2021-06-21 19:45:55:931 [ADB] Running 'C:\Users\xx\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 165.96.211.127:49110 shell echo ping'
2021-06-21 19:45:56:515 [AndroidDriver] Pushing settings apk to device...
2021-06-21 19:45:56:515 [ADB] Getting install status for io.appium.settings
2021-06-21 19:45:56:515 [ADB] Running 'C:\Users\xx\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 165.96.211.127:49110 shell dumpsys package io.appium.settings'
2021-06-21 19:45:57:122 [ADB] 'io.appium.settings' is installed
2021-06-21 19:45:57:122 [ADB] Getting package info for 'io.appium.settings'
2021-06-21 19:45:57:123 [ADB] Running 'C:\Users\xx\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 165.96.211.127:49110 shell dumpsys package io.appium.settings'
2021-06-21 19:45:57:866 [ADB] The version name of the installed 'io.appium.settings' is greater or equal to the application version name ('3.2.1' >= '3.2.1')
2021-06-21 19:45:57:866 [ADB] There is no need to install/upgrade 'C:\Users\xx\AppData\Roaming\npm\node_modules\appium\node_modules\io.appium.settings\apks\settings_apk-debug.apk'
2021-06-21 19:45:57:867 [ADB] Getting IDs of all 'io.appium.settings' processes
2021-06-21 19:45:57:867 [ADB] Running 'C:\Users\xx\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 165.96.211.127\:49110 shell 'pgrep --help; echo $?''
2021-06-21 19:45:58:680 [ADB] Running 'C:\Users\xx\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 165.96.211.127:49110 shell pgrep -f \(\[\[:blank:\]\]\|\^\)io\.appium\.settings\(\[\[:blank:\]\]\|\$\)'
2021-06-21 19:45:59:300 [AndroidDriver] io.appium.settings is already running. There is no need to reset its permissions.
2021-06-21 19:45:59:301 [ADB] Running 'C:\Users\xx\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 165.96.211.127:49110 shell appops set io.appium.settings android:mock_location allow'
2021-06-21 19:46:01:300 [Logcat] Starting logs capture with command: C:\\Users\\xx\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s 165.96.211.127\:49110 logcat -v threadtime
2021-06-21 19:46:01:899 [AndroidDriver] Enabling Unicode keyboard support
2021-06-21 19:46:01:900 [ADB] Running 'C:\Users\xx\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 165.96.211.127:49110 shell settings get secure default_input_method'
2021-06-21 19:46:03:998 [AndroidDriver] Unsetting previous IME io.appium.settings/.UnicodeIME
2021-06-21 19:46:03:998 [AndroidDriver] Setting IME to 'io.appium.settings/.UnicodeIME'
2021-06-21 19:46:03:999 [ADB] Running 'C:\Users\xx\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 165.96.211.127:49110 shell ime enable io.appium.settings/.UnicodeIME'
2021-06-21 19:46:05:916 [ADB] Running 'C:\Users\xx\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 165.96.211.127:49110 shell ime set io.appium.settings/.UnicodeIME'
2021-06-21 19:46:07:809 [UiAutomator2] Forwarding UiAutomator2 Server port 6790 to local port 8200
2021-06-21 19:46:07:809 [ADB] Forwarding system: 8200 to device: 6790
2021-06-21 19:46:07:809 [ADB] Running 'C:\Users\xx\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 165.96.211.127:49110 forward tcp:8200 tcp:6790'
2021-06-21 19:46:08:469 [ADB] Getting install status for io.appium.uiautomator2.server
2021-06-21 19:46:08:470 [ADB] Running 'C:\Users\xx\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 165.96.211.127:49110 shell dumpsys package io.appium.uiautomator2.server'
2021-06-21 19:46:09:101 [ADB] 'io.appium.uiautomator2.server' is installed
2021-06-21 19:46:09:101 [ADB] Getting package info for 'io.appium.uiautomator2.server'
2021-06-21 19:46:09:101 [ADB] Running 'C:\Users\xx\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 165.96.211.127:49110 shell dumpsys package io.appium.uiautomator2.server'
2021-06-21 19:46:09:719 [ADB] The installed 'io.appium.uiautomator2.server' package is older than 'C:\Users\xx\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.17.4.apk' (31 < 79 or '3.5.1' < '4.17.4')'
2021-06-21 19:46:09:719 [UiAutomator2] io.appium.uiautomator2.server installation state: olderVersionInstalled
2021-06-21 19:46:09:720 [ADB] Checking app cert for C:\Users\xx\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.17.4.apk
2021-06-21 19:46:09:781 [ADB] Using 'apksigner.jar' from 'C:\Users\xx\AppData\Local\Android\Sdk\build-tools\30.0.0\lib\apksigner.jar'
2021-06-21 19:46:09:782 [ADB] Starting apksigner: 'C:\\Program Files\\Java\\jdk1.8.0_202\\bin\\java.exe' -Xmx1024M -Xss1m -jar C:\\Users\\xx\\AppData\\Local\\Android\\Sdk\\build-tools\\30.0.0\\lib\\apksigner.jar verify --print-certs C:\\Users\\xx\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-v4.17.4.apk
2021-06-21 19:46:10:096 [UiAutomator2] Deleting UiAutomator2 session
2021-06-21 19:46:10:097 [UiAutomator2] Deleting UiAutomator2 server session
2021-06-21 19:46:10:098 [WD Proxy] Matched '/' to command name 'deleteSession'
2021-06-21 19:46:10:108 [UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Trying to proxy a session command without session id
2021-06-21 19:46:10:108 [UiAutomator2] Resetting IME to 'io.appium.settings/.UnicodeIME'
2021-06-21 19:46:10:108 [ADB] Running 'C:\Users\xx\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 165.96.211.127:49110 shell ime set io.appium.settings/.UnicodeIME'
2021-06-21 19:46:12:022 [Logcat] Stopping logcat capture
2021-06-21 19:46:12:025 [ADB] Removing forwarded port socket connection: 8200 
2021-06-21 19:46:12:026 [ADB] Running 'C:\Users\xx\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 165.96.211.127:49110 forward --remove tcp:8200'
2021-06-21 19:46:12:613 [BaseDriver] Event 'newSessionStarted' logged at 1624272372613 (19:46:12 GMT+0900 (鏃ユ湰妯欐簴鏅�))
2021-06-21 19:46:12:663 [W3C] Encountered internal error running command: Error: Cannot verify the signature of 'C:\Users\xx\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.17.4.apk'. Original error: java.lang.UnsupportedClassVersionError: com/android/apksigner/ApkSignerTool has been compiled by a more recent version of the Java Runtime **(class file version 53.0)**, this version of the Java Runtime only recognizes class file **versions up to 52.0**

2021-06-21 19:46:12:664 [W3C] 	at java.lang.ClassLoader.defineClass1(Native Method)

2021-06-21 19:46:12:664 [W3C] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)

2021-06-21 19:46:12:664 [W3C] 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)

2021-06-21 19:46:12:664 [W3C] 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)

2021-06-21 19:46:12:664 [W3C] 	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)

2021-06-21 19:46:12:664 [W3C] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)

2021-06-21 19:46:12:664 [W3C] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)

2021-06-21 19:46:12:664 [W3C] 	at java.security.AccessController.doPrivileged(Native Method)

2021-06-21 19:46:12:664 [W3C] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)

2021-06-21 19:46:12:664 [W3C] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)

2021-06-21 19:46:12:664 [W3C] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)

2021-06-21 19:46:12:664 [W3C] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

2021-06-21 19:46:12:664 [W3C] 	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)

2021-06-21 19:46:12:664 [W3C] Error: A JNI error has occurred, please check your installation and try again

2021-06-21 19:46:12:664 [W3C] Picked up JAVA_TOOL_OPTIONS: -Dsun.jnu.encoding=UTF-8 -Dfile.encoding=UTF-8
2021-06-21 19:46:12:664 [W3C] Exception in thread "main" 
2021-06-21 19:46:12:664 [W3C]     at ADB.checkApkCert (C:\Users\xx\AppData\Roaming\npm\node_modules\appium\node_modules\appium-adb\lib\tools\apk-signing.js:270:11)
2021-06-21 19:46:12:665 [W3C]     at UiAutomator2Server.installServerApk (C:\Users\xx\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\uiautomator2.js:111:13)
2021-06-21 19:46:12:665 [W3C]     at AndroidUiautomator2Driver.initUiAutomator2Server (C:\Users\xx\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\driver.js:485:7)
2021-06-21 19:46:12:665 [W3C]     at AndroidUiautomator2Driver.startUiAutomator2Session (C:\Users\xx\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\driver.js:379:5)
2021-06-21 19:46:12:665 [W3C]     at AndroidUiautomator2Driver.createSession (C:\Users\xx\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\driver.js:224:7)
2021-06-21 19:46:12:665 [W3C]     at AppiumDriver.createSession (C:\Users\xx\AppData\Roaming\npm\node_modules\appium\lib\appium.js:371:35)
2021-06-21 19:46:12:709 [HTTP] <-- POST /wd/hub/session 500 28829 ms - 3573

**Comment by mykola-mokhnach** [comment]
This means that at least Java9 is required by Android SDK 30. This is also mentioned in the driver documentation. Closed as not an issue.

**Comment by studyJavaForLive** [comment]
@mykola-mokhnach 
Thank you very much!

**Comment by studyJavaForLive** [comment]
BYW,Where i can find the document?

> driver documentation

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium-uiautomator2-driver#requirements
