### ISSUE TITLE
otherApps on iOS Simulator fails with "An application bundle was not found at the provided path."

### ISSUE THREAD

**Issue by sidster-io** [appium/appium#15596]
## The problem

Trying to install a dependent app to test open-in scenario from App_A to App_B. Currently the otherApps caps work on Android Emulator but on iOS Simulator I get, `An unknown server-side error occurred while processing the command. Original error: Error running 'install': An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2): Failed to install the requested application An application bundle was not found at the provided path. Provide a valid path to the desired application bundle.` and here is the [details about the cap](http://appium.io/docs/en/writing-running-appium/caps/) 
<img width="892" alt="Screen Shot 2021-06-30 at 2 09 25 PM" src="https://user-images.githubusercontent.com/6657673/124010453-d3720780-d9ac-11eb-8f3b-11df529cfb5c.png">

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21.0
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: macOS 11.4
* Node.js version (unless using Appium.app|exe): 12.16.2
* Npm or Yarn package manager: N/A
* Mobile platform/version under test: iOS 14.0
* Real device or emulator/simulator: iOS Simulator
* Appium CLI or Appium.app|exe: Appium.app

## Details

Capabilities set: `{
  "platformName": "iOS",
  "app": "/Users/User/Desktop/Apps/App_A.app",
  "platformVersion": "14.0",
  "deviceName": "iPhone Simulator",
  "otherApps": "http://appium.github.io/appium/assets/TestApp9.4.app.zip"
}`

The otherApps URL http://appium.github.io/appium/assets/TestApp9.4.app.zip is from the [doc site](http://appium.io/docs/en/writing-running-appium/caps/) and it is a live working link. I also tried with my own `.app.zip` that installs when set in `app` capabilities but fails when set under otherApps.

## Link to Appium logs
```
[simctl] Error running 'install': An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
[XCUITest] {"stdout":"","stderr":"An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):\nFailed to install the requested application\nAn application bundle was not found at the provided path.\nProvide a valid path to the desired application bundle.\n","code":2}
[DevCon Factory] Releasing connections for ED06BAE3-0E7B-4621-B6C6-DBD53347707A device on any port number
[DevCon Factory] No cached connections have been found
[XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[IOSSimulatorLog] Stopping iOS log capture
[BaseDriver] Event 'newSessionStarted' logged at 1625076422377 (14:07:02 GMT-0400 (Eastern Daylight Time))
[MJSONWP] Encountered internal error running command: Error running 'install': An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
[MJSONWP] Failed to install the requested application
[MJSONWP] An application bundle was not found at the provided path.
[MJSONWP] Provide a valid path to the desired application bundle.
[MJSONWP] Error: Command '/usr/bin/xcrun simctl install ED06BAE3-0E7B-4621-B6C6-DBD53347707A http\://appium.github.io/appium/assets/TestApp9.4.app.zip' exited with code 2
[MJSONWP]     at ChildProcess. (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/teen_process/lib/exec.js:113:19)
[MJSONWP]     at ChildProcess.emit (events.js:203:13)
[MJSONWP]     at maybeClose (internal/child_process.js:1021:16)
[MJSONWP]     at Socket. (internal/child_process.js:430:11)
[MJSONWP]     at Socket.emit (events.js:203:13)
[MJSONWP]     at Pipe. (net.js:588:12)
[HTTP] <-- POST /wd/hub/session 500
```

**Comment by sidster-io** [comment]
Using installApp command works as a workaround 
```[XCUITest] Executing command 'installApp'
[BaseDriver] Using downloadable app 'http://appium.github.io/appium/assets/TestApp9.4.app.zip'
[BaseDriver] Last-Modified: Thu, 24 Jan 2019 18:15:12 GMT
[BaseDriver] Cache-Control: max-age=600
[BaseDriver] A fresh copy of the application is going to be downloaded from http://appium.github.io/appium/assets/TestApp9.4.app.zip
[BaseDriver] Content-Type: application/zip
[Support] http://appium.github.io/appium/assets/TestApp9.4.app.zip (53.59 KB) has been downloaded to '/var/folders/bj/_vk9yk257vdfg_ct5hq11sqr0000gn/T/2021530-97076-f1bvad.qfma8/TestApp9.4.app.zip' in 0.013s
[BaseDriver] Unzipping '/var/folders/bj/_vk9yk257vdfg_ct5hq11sqr0000gn/T/2021530-97076-f1bvad.qfma8/TestApp9.4.app.zip'
[BaseDriver] Extracted 12 items from '/var/folders/bj/_vk9yk257vdfg_ct5hq11sqr0000gn/T/2021530-97076-f1bvad.qfma8/TestApp9.4.app.zip' in 23ms
[BaseDriver] Matched 1 item in the extracted archive. Assuming 'TestApp.app' is the correct bundle
[BaseDriver] Unzipped local app to '/var/folders/bj/_vk9yk257vdfg_ct5hq11sqr0000gn/T/2021530-97076-tlfqjs.cr7g/TestApp.app'
[XCUITest] Installing '/var/folders/bj/_vk9yk257vdfg_ct5hq11sqr0000gn/T/2021530-97076-tlfqjs.cr7g/TestApp.app' to the Simulator with UDID '29786899-8502-40D4-AEA1-9F8965972D80'
[XCUITest] Installation of '/var/folders/bj/_vk9yk257vdfg_ct5hq11sqr0000gn/T/2021530-97076-tlfqjs.cr7g/TestApp.app' succeeded
[MJSONWP (438adddc)] Responding to client with driver.installApp() result: null
[HTTP] <-- POST /wd/hub/session/438adddc-fec3-42d2-b94b-8d7676e3a9d2/appium/device/install_app 200```

**Comment by mykola-mokhnach** [comment]
The patch has been published to appium@beta
