### ISSUE TITLE
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command

### ISSUE THREAD

**Issue by dipakkumar1225** [appium/appium#15604]
Randomly getting below issue: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command.
Appium Desktop : 1.21.0

Below are the error:

```
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Cannot invoke method private android.view.accessibility.AccessibilityNodeInfo androidx.test.uiautomator.UiObject2.getAccessibilityNodeInfo() on object androidx.test.uiautomator.UiObject2@1a17b with parameters []
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'WJLP-1626', ip: '192.168.247.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '14.0.2'
Driver info: io.appium.java_client.android.AndroidDriver
fullReset: false, newCommandTimeout: 30, noReset: false, platformName: android, platformVersion: 9, systemPort: 8200, udid: FARCT84DU8KZJZR8}, 
deviceApiLevel: 28, deviceManufacturer: OPPO, deviceModel: CPH2083, deviceName: FARCT84DU8KZJZR8, deviceScreenDensity: 272, deviceScreenSize: 720x1520, deviceUDID: 
FARCT84DU8KZJZR8, disableWindowAnimation: true, fullReset: false, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, 
newCommandTimeout: 30, noReset: false, pixelRatio: 1.7, platform: LINUX, platformName: Android, platformVersion: 9, statBarHeight: 56, systemPort: 8200, 
takesScreenshot: true, udid: FARCT84DU8KZJZR8, viewportRect: {height: 1333, left: 0, top: 56, width: 720}, warnings: {}, webStorageEnabled: false}
Session ID: f2147fc0-945d-4221-9dc2-e2c7f9fd86c6
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:247)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285)
	at io.appium.java_client.DefaultGenericMobileElement.execute(DefaultGenericMobileElement.java:45)
	at io.appium.java_client.MobileElement.execute(MobileElement.java:1)
	at io.appium.java_client.android.AndroidElement.execute(AndroidElement.java:1)
	at org.openqa.selenium.remote.RemoteWebElement.isDisplayed(RemoteWebElement.java:326)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at io.appium.java_client.pagefactory.ElementInterceptor.getObject(ElementInterceptor.java:40)
	at io.appium.java_client.pagefactory.interceptors.InterceptorOfASingleElement.intercept(InterceptorOfASingleElement.java:60)
	at io.appium.java_client.android.AndroidElement$$EnhancerByCGLIB$$b598166c.isDisplayed(<generated>)
	at org.openqa.selenium.support.ui.ExpectedConditions.elementIfVisible(ExpectedConditions.java:314)
	at org.openqa.selenium.support.ui.ExpectedConditions.access$000(ExpectedConditions.java:43)
	at org.openqa.selenium.support.ui.ExpectedConditions$10.apply(ExpectedConditions.java:300)
	at org.openqa.selenium.support.ui.ExpectedConditions$10.apply(ExpectedConditions.java:297)
	at org.openqa.selenium.support.ui.ExpectedConditions$25.apply(ExpectedConditions.java:731)
	at org.openqa.selenium.support.ui.ExpectedConditions$25.apply(ExpectedConditions.java:727)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:249)
	at activitiesobject.commonmodule.header.HeaderMenu.isHeaderNavigationScreenDisplayed(HeaderMenu.java:125)
	at activitiesobject.commonmodule.header.HeaderMenu.isNavigatedToScreen(HeaderMenu.java:140)
	at activitiesobject.commonmodule.TermsAndConditions.isTermsAndConditionScreenDisplayed(TermsAndConditions.java:37)
	at screens.TestPermission.navigatedToTermsAndConditionsScreen(TestPermission.java:42)
	at ✽.Navigated to terms and conditions screen(classpath:features/01_Pre-Registration.feature:24)
```

**Comment by KazuCocoa** [comment]
Please attach the full Appium log.

**Comment by dipakkumar1225** [comment]
[appium-server-logs.txt](https://github.com/appium/appium/files/6758978/appium-server-logs.txt)
Please find the attached Appium log

Below are my desired capabilities

```
public class AndroidManager extends GenericDriverManager {

    Configuration configuration = ConfigurationManager.getConfiguration();

    @Override
    protected void createDriver(String platform, String udid, String systemPort, String automationName) {

        URL url = null;
        try {
            url = new URL("http://localhost:4723/wd/hub");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }

        String[] platformInfo = platform.split(" ");

        DesiredCapabilities capabilities = new DesiredCapabilities();

        capabilities.setCapability(AndroidMobileCapabilityType.DISABLE_WINDOW_ANIMATION,true);
        capabilities.setCapability(MobileCapabilityType.UDID, udid);
        capabilities.setCapability(AndroidMobileCapabilityType.SYSTEM_PORT, Integer.parseInt(systemPort));
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "Android Emulator");
        capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, 30);
        capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, platformInfo[0]);
        capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, platformInfo[1]);
        capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, automationName);
        capabilities.setCapability(MobileCapabilityType.APP, new File(configuration.androidAppPath()).getAbsolutePath());
        capabilities.setCapability(AndroidMobileCapabilityType.APP_PACKAGE, configuration.androidAppPackage());
        capabilities.setCapability(AndroidMobileCapabilityType.APP_ACTIVITY, configuration.androidAppActivity());
        capabilities.setCapability(AndroidMobileCapabilityType.AUTO_GRANT_PERMISSIONS, true);
        capabilities.setCapability(MobileCapabilityType.FULL_RESET, false);
        capabilities.setCapability(MobileCapabilityType.NO_RESET, configuration.noReset());

        if (url != null) {
            mobileDriver = new AndroidDriver<>(url, capabilities);
        }
        mobileDriver.setSetting(Setting.WAIT_FOR_SELECTOR_TIMEOUT, 0);
        mobileDriver.setSetting(Setting.WAIT_FOR_IDLE_TIMEOUT, 0);
    }
}
```
And this is my BasePage

```
public class BasePage {

    @Getter(AccessLevel.PROTECTED)
    private final AppiumDriver<MobileElement> baseMobileDriver;

    @Getter(AccessLevel.PROTECTED)
    private final WebDriverWait webDriverWait;
    
    Configuration configuration = ConfigurationManager.getConfiguration();

    protected BasePage(AppiumDriver<MobileElement> baseMobileDriver) {
        this.baseMobileDriver = baseMobileDriver;
        this.webDriverWait = new WebDriverWait(this.baseMobileDriver, 150);
        AppiumFieldDecorator appiumFieldDecorator = new AppiumFieldDecorator(this.baseMobileDriver, Duration.ofSeconds(150));
        PageFactory.initElements(appiumFieldDecorator, this);
    }
}
```

**Comment by mykola-mokhnach** [comment]
This exception basically means that the destination element is stale. I've added a patch, so a proper exception class will be used in the future, but it would still still happen there. Check https://developer.mozilla.org/en-US/docs/Web/WebDriver/Errors/StaleElementReference for more details

**Comment by dipakkumar1225** [comment]
To avoid element stale I was using; 
`getWebDriverWait().until(ExpectedConditions.refreshed(ExpectedConditions.visibilityOf(mobileElementLocateUSTitle)));`
but as I said earlier that the issue was random. So how can I handle this?

**Comment by mykola-mokhnach** [comment]
You could try to ask at Appium forum if you are looking for concrete recipes for the java client.

The general advice to avoid stale element exception is to repeat element search instead of using the cached web element instance.

**Comment by mykola-mokhnach** [comment]
The patch has been published to appium@beta
