### ISSUE TITLE
An unknown server-side error occurred while processing the command. Original error: Error executing adbExec

### ISSUE THREAD

**Issue by Amrkamel1** [appium/appium#15648]
## The problem

unable to execute the automation test when emulator is launched using the following command, the same test is executed normally when the emulator is run without -accel off

`emulator @nexus -verbose -no-boot-anim -no-window -gpu off -accel off &`

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21.0
* Last Appium version that did not exhibit the issue (if applicable): n/a
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe): 14.17.2
* Npm or Yarn package manager: 6.14.13
* Mobile platform/version under test: nexus 6
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs
```

Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/home/amrka/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 install -g /usr/lib/node_modules/appium/node_modules/io.appium.settings/apks/settings_apk-debug.apk' exited with code 1'; Stderr: 'adb: failed to install /usr/lib/node_modules/appium/node_modules/io.appium.settings/apks/settings_apk-debug.apk: cmd: Can't find service: package'; Code: '1'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'warrior', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-77-generic', java.version: '11.0.9'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/home/amrka/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 install -g /usr/lib/node_modules/appium/node_modules/io.appium.settings/apks/settings_apk-debug.apk' exited with code 1'; Stderr: 'adb: failed to install /usr/lib/node_modules/appium/node_modules/io.appium.settings/apks/settings_apk-debug.apk: cmd: Can't find service: package'; Code: '1'
    at getResponseForW3CError (/usr/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)
    at asyncHandler (/usr/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:380:37)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'warrior', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-77-generic', java.version: '11.0.9'
Driver info: driver.version: AndroidDriver
Caused by: java.lang.reflect.InvocationTargetException
Caused by: org.openqa.selenium.WebDriverException: 
An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/home/amrka/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 install -g /usr/lib/node_modules/appium/node_modules/io.appium.settings/apks/settings_apk-debug.apk' exited with code 1'; Stderr: 'adb: failed to install /usr/lib/node_modules/appium/node_modules/io.appium.settings/apks/settings_apk-debug.apk: cmd: Can't find service: package'; Code: '1'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'warrior', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-77-generic', java.version: '11.0.9'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/home/amrka/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 install -g /usr/lib/node_modules/appium/node_modules/io.appium.settings/apks/settings_apk-debug.apk' exited with code 1'; Stderr: 'adb: failed to install /usr/lib/node_modules/appium/node_modules/io.appium.settings/apks/settings_apk-debug.apk: cmd: Can't find service: package'; Code: '1'
    at getResponseForW3CError (/usr/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)
    at asyncHandler (/usr/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:380:37)

[ERROR] Tests.Android.LoginPageTest.StartingPoint  Time elapsed: 0.016 s  <<< FAILURE!
java.lang.NullPointerException

[ERROR] Tests.Android.LoginPageTest.StartingPoint  Time elapsed: 0.003 s  <<< FAILURE!
java.lang.NullPointerException

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR] Tests.Android.LoginPageTest.StartingPoint
[ERROR]   Run 1: LoginPageTest>BaseSetup.run:71->BaseSetup.StartingPoint:169 » NullPointer
[ERROR]   Run 2: LoginPageTest>BaseSetup.run:71->BaseSetup.StartingPoint:169 » NullPointer
```

**Comment by mykola-mokhnach** [comment]
> remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/home/amrka/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 install -g /usr/lib/node_modules/appium/node_modules/io.appium.settings/apks/settings_apk-debug.apk' exited with code 1'; Stderr: 'adb: failed to install /usr/lib/node_modules/appium/node_modules/io.appium.settings/apks/settings_apk-debug.apk: cmd: Can't find service: package'; Code: '1'

Most likely the reason for the above failure is the emulator is still not booted fully when the automated test starts. This issue has nothing to do with Appium. You could try to change your emulator startup script, so it detects the booted state properly and only after that starts tests execution as a possible workaround.

**Comment by Amrkamel1** [comment]
@mykola-mokhnach , i have already created a script that after the device is fully booted test will start, but still getting the same error

**Comment by mykola-mokhnach** [comment]
Perhaps it needs some fixes/improvements. Try to ask at Appium forum.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
