### ISSUE TITLE
wda: the test runner exited with code 74 before finishing runnint tests.

### ISSUE THREAD

**Issue by wgywgy** [appium/appium#15665]
## The problem

issue: after run python test code ( function is take turns to open 3 apps), the WDA xcode project is exit.

## Environment

wda project: v3.12 and v3.11
macOS 11.4
Real device iOS 13 and 14

## Details

the xcode project error:
the test runner exited with code 74 before finishing runnint tests.
![截屏2021-07-26 下午3 03 30](https://user-images.githubusercontent.com/2408246/127113683-31cb5ceb-4f85-48f2-a979-9595d6dc626b.png)

## Link to Appium logs

the python test script is run with airTest.

[6274] Failed to execute script AirtestIDE
Traceback (most recent call last):
  File "site-packages/urllib3/connectionpool.py", line 677, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 426, in _make_request
  File "<string>", line 3, in raise_from
  File "site-packages/urllib3/connectionpool.py", line 421, in _make_request
  File "http/client.py", line 1331, in getresponse
  File "http/client.py", line 297, in begin
  File "http/client.py", line 266, in _read_status
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/AirtestIDE.app/Contents/MacOS/requests/adapters.py", line 449, in send
    timeout=timeout
  File "site-packages/urllib3/connectionpool.py", line 725, in urlopen
  File "site-packages/urllib3/util/retry.py", line 403, in increment
  File "site-packages/urllib3/packages/six.py", line 734, in reraise
  File "site-packages/urllib3/connectionpool.py", line 677, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 426, in _make_request
  File "<string>", line 3, in raise_from
  File "site-packages/urllib3/connectionpool.py", line 421, in _make_request
  File "http/client.py", line 1331, in getresponse
  File "http/client.py", line 297, in begin
  File "http/client.py", line 266, in _read_status
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "AirtestIDE.py", line 82, in <module>
  File "AirtestIDE.py", line 58, in main
  File "app/widgets/code_runner/tracer.py", line 72, in run_pyfile
  File "/Users/guanyu/Documents/airTest/airTest_2.py", line 246, in <module>
    mainCheck()
  File "/Users/guanyu/Documents/airTest/airTest_2.py", line 187, in mainCheck
    checkOnce()
  File "/Users/guanyu/Documents/airTest/airTest_2.py", line 239, in checkOnce
    meituan_back_lookup_more()
  File "/Users/guanyu/Documents/airTest/airTest_2.py", line 143, in meituan_back_lookup_more
    swipe((500,1600),(500,700))
  File "airtest/utils/logwraper.py", line 90, in wrapper
  File "airtest/core/api.py", line 437, in swipe
  File "/Applications/AirtestIDE.app/Contents/MacOS/airtest/core/ios/ios.py", line 34, in wrapper
    return func(self, *args, **kwargs)
  File "/Applications/AirtestIDE.app/Contents/MacOS/airtest/core/ios/ios.py", line 352, in swipe
    self.driver.swipe(fx, fy, tx, ty, duration)
  File "site-packages/wda/__init__.py", line 947, in swipe
  File "site-packages/wda/utils.py", line 47, in _inner
  File "site-packages/wda/__init__.py", line 454, in _fetch
  File "site-packages/wda/__init__.py", line 124, in httpdo
  File "site-packages/wda/__init__.py", line 154, in _unsafe_httpdo
  File "/Applications/AirtestIDE.app/Contents/MacOS/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/Applications/AirtestIDE.app/Contents/MacOS/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/Applications/AirtestIDE.app/Contents/MacOS/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
[15:41:55][INFO]<airtest.core.ios.rotation> orientationWatcher has ended

**Comment by mykola-mokhnach** [comment]
Unfortunately we do not support third-party WDA integrations. Consider contacting their authors.
