### ISSUE TITLE
Support `enablePerformanceLogging` for iOS

### ISSUE THREAD

**Issue by christian-bromann** [appium/appium#15685]
If you run Appium on iOS simulators with the capability `enablePerformanceLogging: true` set, the session fails due to:

```
2021-08-03 10:02:56:438 - [debug] [XCUITest] Starting performance log on '4226.1'
2021-08-03 10:02:56:438 - [debug] [iOSLog] Starting performance (Timeline) log capture
2021-08-03 10:02:56:438 - [debug] [RemoteDebugger] Starting to record the timeline
(node:3964) UnhandledPromiseRejectionWarning: Error: Unknown command: 'startTimeline'
    at getProtocolCommand (/Volumes/Sauce/selenium/appium-v1.20.1/node_modules/appium-remote-debugger/lib/protocol/index.js:123:11)
    at RemoteMessages.getRemoteCommand (/Volumes/Sauce/selenium/appium-v1.20.1/node_modules/appium-remote-debugger/lib/rpc/remote-messages.js:242:10)
    at /Volumes/Sauce/selenium/appium-v1.20.1/node_modules/appium-remote-debugger/lib/rpc/rpc-client.js:227:39
    at Promise.cancellationExecute [as _execute] (/Volumes/Sauce/selenium/appium-v1.20.1/node_modules/bluebird/js/release/debuggability.js:406:9)
    at Promise._resolveFromExecutor (/Volumes/Sauce/selenium/appium-v1.20.1/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/Volumes/Sauce/selenium/appium-v1.20.1/node_modules/bluebird/js/release/promise.js:103:10)
    at RpcClientSimulator.sendToDevice (/Volumes/Sauce/selenium/appium-v1.20.1/node_modules/appium-remote-debugger/lib/rpc/rpc-client.js:198:18)
    at RpcClientSimulator.send (/Volumes/Sauce/selenium/appium-v1.20.1/node_modules/appium-remote-debugger/lib/rpc/rpc-client.js:175:25)
    at RemoteDebugger.startTimeline (/Volumes/Sauce/selenium/appium-v1.20.1/node_modules/appium-remote-debugger/lib/remote-debugger.js:160:33)
    at IOSPerformanceLog.startCapture (/Volumes/Sauce/selenium/appium-v1.20.1/node_modules/appium-ios-driver/lib/device-log/ios-performance-log.js:17:38)
    at XCUITestDriver.setContext (/Volumes/Sauce/selenium/appium-v1.20.1/node_modules/appium-xcuitest-driver/lib/commands/context.js:164:33)
    at spinHandles (/Volumes/Sauce/selenium/appium-v1.20.1/node_modules/appium-ios-driver/lib/commands/context.js:531:7)
    at spinHandles (/Volumes/Sauce/selenium/appium-v1.20.1/node_modules/appium-ios-driver/lib/commands/context.js:546:14)
    at XCUITestDriver.navToViewWithTitle (/Volumes/Sauce/selenium/appium-v1.20.1/node_modules/appium-ios-driver/lib/commands/context.js:564:3)
    at XCUITestDriver.navToInitialWebview (/Volumes/Sauce/selenium/appium-v1.20.1/node_modules/appium-xcuitest-driver/lib/commands/context.js:29:5)
    at XCUITestDriver.start (/Volumes/Sauce/selenium/appium-v1.20.1/node_modules/appium-xcuitest-driver/lib/driver.js:479:7)
    at XCUITestDriver.createSession (/Volumes/Sauce/selenium/appium-v1.20.1/node_modules/appium-xcuitest-driver/lib/driver.js:215:7)
    at AppiumDriver.createSession (/Volumes/Sauce/selenium/appium-v1.20.1/lib/appium.js:371:35)
(Use `node-darwin --trace-warnings ...` to show where the warning was created)
(node:3964) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 22)
(node:3964) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I am not entirely sure if Appium has support for this on iOS or if this is more a feature request.

To reproduce, run a job on Sauce Labs using these capabilities:

```js
{
        browserName: 'Safari',
        platformName: 'iOS',
        build: 'Customer Test',
        automationName: 'XCUITest',
        deviceName: 'iPhone 11 Pro Max Simulator',
        enablePerformanceLogging: true,
        idleTimeout: 60000,
        newCommandTimeout: 60000,
        deviceOrientation: 'PORTRAIT',
        platformVersion: '14.3'
}
```

Example: https://app.saucelabs.com/tests/be0d6d12a9f64e60a71e02b8fd9428b2

**Comment by mykola-mokhnach** [comment]
cc @jlipps

**Comment by jlipps** [comment]
It looks like the remote debugger has removed support for the startTimeline event, or otherwise introduced some breaking change. We'll need to examine updates to the remote debug API and modernize our remote debugger code.

**Comment by KozhevnikovSergey** [comment]
Hello!
Do you have any updates? I have faced with this problem in BrowserStack (
