### ISSUE TITLE
v1.22.0 beta -Error converting element ID for using in WD atoms

### ISSUE THREAD

**Issue by mayureshshirodkar** [appium/appium#15738]
## The problem

On trying to execute the below command on Appium version 1.22.0 beta, 500 error is throws with the error.
`Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error converting element ID for using in WD atoms: ':wdc:1629201728496'`

AppiumDriver.elementDisplayed() fails with 500 error but AppiumDriver.findElement() passes with 200.
These 2 apis pass with 200 code on Appium 1.21.0 as shown in log gist.

Also i have switched to Web context to execute the commands on hybrid application

On appium 1.22.0 beta - 
```
[HTTP] --> POST /wd/hub/session/247480b9-be99-4bad-b8dd-a0214f7f6157/element
[HTTP] {"using":"xpath","value":"//*[text()='Welcome to Navigate!']"}
[debug] [W3C (247480b9)] Calling AppiumDriver.findElement() with args: ["xpath","//*[text()='Welcome to Navigate!']","247480b9-be99-4bad-b8dd-a0214f7f6157"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id, css selector
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [RemoteDebugger] Executing atom 'find_element' with 'args=["xpath","//*[text()='Welcome to Navigate!']",null]; frames='
[debug] [RemoteDebugger] Executing 'find_element' atom in default context
[debug] [RemoteDebugger] Sending javascript command: '(function(){return function(){var k=this;functi...'
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:689', page '1', target 'page-6' (id: 34): 'Runtime.evaluate'
[debug] [RemoteDebugger] Received data response from send (id: 34): '"{\"status\":0,\"value\":{\"ELEMENT\":\":wdc:1629201728496\"}}"'
[debug] [RemoteDebugger] Sending to Web Inspector took 26ms
[debug] [RemoteDebugger] Received result for atom 'find_element' execution: {"ELEMENT":":wdc:1629201728496"}
[debug] [W3C (247480b9)] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":":wdc:1629201728496","ELEMENT":":wdc:1629201728496"}
[HTTP] <-- POST /wd/hub/session/247480b9-be99-4bad-b8dd-a0214f7f6157/element 200 29 ms - 101



[HTTP] --> GET /wd/hub/session/247480b9-be99-4bad-b8dd-a0214f7f6157/element/:wdc:1629201728496/displayed
[HTTP] {}
[debug] [W3C (247480b9)] Calling AppiumDriver.elementDisplayed() with args: [":wdc:1629201728496","247480b9-be99-4bad-b8dd-a0214f7f6157"]
[debug] [XCUITest] Executing command 'elementDisplayed'
[debug] [W3C (247480b9)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error converting element ID for using in WD atoms: ':wdc:1629201728496'
[debug] [W3C (247480b9)]     at XCUITestDriver.useAtomsElement (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/web.js:255:11)
[debug] [W3C (247480b9)]     at XCUITestDriver.elementDisplayed (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/element.js:12:31)
[debug] [W3C (247480b9)]     at commandExecutor (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:335:9)
[debug] [W3C (247480b9)]     at /usr/local/lib/node_modules/appium/node_modules/async-lock/lib/index.js:146:12
[debug] [W3C (247480b9)]     at AsyncLock._promiseTry (/usr/local/lib/node_modules/appium/node_modules/async-lock/lib/index.js:280:31)
[debug] [W3C (247480b9)]     at exec (/usr/local/lib/node_modules/appium/node_modules/async-lock/lib/index.js:145:9)
[debug] [W3C (247480b9)]     at AsyncLock.acquire (/usr/local/lib/node_modules/appium/node_modules/async-lock/lib/index.js:162:3)
[debug] [W3C (247480b9)]     at XCUITestDriver.executeCommand (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:348:39)
[debug] [W3C (247480b9)]     at XCUITestDriver.executeCommand (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:743:24)
[debug] [W3C (247480b9)]     at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/lib/appium.js:563:36)
[debug] [W3C (247480b9)]     at runMicrotasks (<anonymous>)
[debug] [W3C (247480b9)]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
[debug] [W3C (247480b9)]     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:297:21)
[HTTP] <-- GET /wd/hub/session/247480b9-be99-4bad-b8dd-a0214f7f6157/element/:wdc:1629201728496/displayed 500 52 ms - 1787
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.0 beta
* Last Appium version that did not exhibit the issue (if applicable): 1.21.0
* Desktop OS/version used to run Appium: Mac OS Big Sur 11.4
* Node.js version (unless using Appium.app|exe): v14.17.0
* Npm or Yarn package manager: 6.14.13
* Mobile platform/version under test: v14.7.1/1 v12.4.2
* Real device or emulator/simulator: iPhone X
* Appium CLI or Appium.app|exe: Appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Appium 1.22.0 beta log - https://gist.github.com/mayureshshirodkar/7e8da1d9ea3db682de2760280463bbea
Appium 1.21.0 log - https://gist.github.com/mayureshshirodkar/7d0b4b1c8d0ea36fa3c5c29038271d4c
 

## Code To Reproduce Issue [ Good To Have ]

`        return WebDriverWait(get_driver(context), wait_time).until(EC.presence_of_element_located((By.XPATH, xpath)))`

**Comment by mykola-mokhnach** [comment]
From the description it looks like you have some leftovers in your beta deployment. Try to reinstall it from scratch

**Comment by mayureshshirodkar** [comment]
@mykola-mokhnach i had installed 1.22.0 beta first and then after uninstalling it, installed 1.21.0.
Uninstalled using - 
`npm uninstall -g appium`

**Comment by KazuCocoa** [comment]
> [Appium] Appium v1.22.0-beta.0 creating new XCUITestDriver (v3.50.2) session

So, the 1.22 beta had old xcuitest driver version.
Once you re-install the version or `@rc`, then XCUITestDriver 3.52.0 should be there. Then the `:wdc:` prefix element should work.

> [Appium] Appium v1.21.0 creating new XCUITestDriver (v3.52.0) session

Btw, the 1.21.0 had the 3.52.0. I guess you installed the version recently.
