### ISSUE TITLE
switch from UiAutomator2 to espresso -> socket hangup

### ISSUE THREAD

**Issue by StephanB75** [appium/appium#15878]
## The problem

i tried to "simply" switch my UiAutomator testsuite to espresso, but i don't know if i had missed some configuration.
Currently the espresso server is compiled and installed on the emulator, but the driver initialization could not connect to the espresso server on the simulator.

## Environment

* Appium version (or git revision) that exhibits the issue: 2.0 beta 18
* Last Appium version that did not exhibit the issue (if applicable): (never used espresso before)
* Desktop OS/version used to run Appium: macOS BigSur
* Node.js version (unless using Appium.app|exe): 12.19.1
* Npm or Yarn package manager: 6.4.18
* Mobile platform/version under test: Android 10
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

GIST logcat exception :
https://gist.github.com/StephanB75/bf1c62f7b3dc71aa62216f6a0caf73df

GIST logcat complete :
https://gist.github.com/StephanB75/3bfd8eaf9e67f1192125ae187c9edc74

GIST appium 
https://gist.github.com/StephanB75/059857c55e6c62b426a218bc8f5f9d66

**Comment by KazuCocoa** [comment]
According to your logcat, the crash started from here.

```
09-23 07:00:44.844 22249 22249 E AndroidJUnitRunner: An unhandled exception was thrown by the app.
09-23 07:00:44.849 22249 22249 E InstrumentationResultPrinter: Failed to mark test No Tests as finished after process crash
09-23 07:00:44.849 22249 22249 I AndroidJUnitRunner: Bringing down the entire Instrumentation process.
09-23 07:00:44.854 22249 22249 E MonitoringInstr: Exception encountered by: de.projectX.app.android.core.projectXApplication@2491578. Dumping thread state to outputs and pining for the fjords.
09-23 07:00:44.854 22249 22249 E MonitoringInstr: java.lang.IllegalStateException: WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider.
09-23 07:00:44.854 22249 22249 E MonitoringInstr: 	at androidx.work.impl.WorkManagerImpl.getInstance(WorkManagerImpl.java:156)
09-23 07:00:44.854 22249 22249 E MonitoringInstr: 	at androidx.work.WorkManager.getInstance(WorkManager.java:184)
09-23 07:00:44.854 22249 22249 E MonitoringInstr: 	at de.projectX.app.android.core.projectXApplication.startBackgroundSync(projectXApplication.java:150)
09-23 07:00:44.854 22249 22249 E MonitoringInstr: 	at de.projectX.app.android.core.projectXApplication.onApplicationCreate(projectXApplication.java:127)
09-23 07:00:44.854 22249 22249 E MonitoringInstr: 	at com.ad4screen.sdk.A4SApplication.onCreate(SourceFile:3)
09-23 07:00:44.854 22249 22249 E MonitoringInstr: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1182)
09-23 07:00:44.854 22249 22249 E MonitoringInstr: 	at androidx.test.runner.MonitoringInstrumentation.callApplicationOnCreate(MonitoringInstrumentation.java:428)
09-23 07:00:44.854 22249 22249 E MonitoringInstr: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
09-23 07:00:44.854 22249 22249 E MonitoringInstr: 	at android.app.ActivityThread.access$1300(ActivityThread.java:219)
09-23 07:00:44.854 22249 22249 E MonitoringInstr: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
09-23 07:00:44.854 22249 22249 E MonitoringInstr: 	at android.os.Handler.dispatchMessage(Handler.java:107)
09-23 07:00:44.854 22249 22249 E MonitoringInstr: 	at android.os.Looper.loop(Looper.java:214)
09-23 07:00:44.854 22249 22249 E MonitoringInstr: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
09-23 07:00:44.854 22249 22249 E MonitoringInstr: 	at java.lang.reflect.Method.invoke(Native Method)
09-23 07:00:44.854 22249 22249 E MonitoringInstr: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
09-23 07:00:44.854 22249 22249 E MonitoringInstr: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
09-23 07:00:44.878 22249 22249 E THREAD_STATE:   Thread[main,5,main]
09-23 07:00:44.878 22249 22249 E THREAD_STATE:     dalvik.system.VMStack.getThreadStackTrace(Native Method)
09-23 07:00:44.878 22249 22249 E THREAD_STATE:     java.lang.Thread.getStackTrace(Thread.java:1720)
09-23 07:00:44.878 22249 22249 E THREAD_STATE:     java.lang.Thread.getAllStackTraces(Thread.java:1796)
09-23 07:00:44.878 22249 22249 E THREAD_STATE:     androidx.test.runner.MonitoringInstrumentation.getThreadState(MonitoringInstrumentation.java:680)
09-23 07:00:44.878 22249 22249 E THREAD_STATE:     androidx.test.runner.MonitoringInstrumentation.dumpThreadStateToOutputs(MonitoringInstrumentation.java:675)
09-23 07:00:44.878 22249 22249 E THREAD_STATE:     androidx.test.runner.MonitoringInstrumentation.onException(MonitoringInstrumentation.java:669)
09-23 07:00:44.878 22249 22249 E THREAD_STATE:     androidx.test.runner.AndroidJUnitRunner.onException(AndroidJUnitRunner.java:554)
09-23 07:00:44.878 22249 22249 E THREAD_STATE:     android.app.ActivityThread.handleBindApplication(ActivityThread.java:6462)
09-23 07:00:44.878 22249 22249 E THREAD_STATE:     android.app.ActivityThread.access$1300(ActivityThread.java:219)
09-23 07:00:44.878 22249 22249 E THREAD_STATE:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
09-23 07:00:44.878 22249 22249 E THREAD_STATE:     android.os.Handler.dispatchMessage(Handler.java:107)
09-23 07:00:44.878 22249 22249 E THREAD_STATE:     android.os.Looper.loop(Looper.java:214)
09-23 07:00:44.878 22249 22249 E THREAD_STATE:     android.app.ActivityThread.main(ActivityThread.java:7356)
09-23 07:00:44.878 22249 22249 E THREAD_STATE:     java.lang.reflect.Method.invoke(Native Method)
09-23 07:00:44.878 22249 22249 E THREAD_STATE:     com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
09-23 07:00:44.878 22249 22249 E THREAD_STATE:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
09-23 07:00:44.878 22249 22249 E THREAD_STATE: 
09-23 07:00:44.878 22249 22249 E THREAD_STATE:   Thread[Binder:22249_2,5,main]
09-23 07:00:44.878 22249 22249 E THREAD_STATE: 
09-23 07:00:44.878 22249 22249 E THREAD_STATE:   Thread[RxCachedWorkerPoolEvictor-1,5,main]
09-23 07:00:44.878 22249 22249 E THREAD_STATE:     sun.misc.Unsafe.park(Native Method)
09-23 07:00:44.878 22249 22249 E THREAD_STATE:     java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
09-23 07:00:44.878 22249 22249 E THREAD_STATE:     java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2109)
09-23 07:00:44.878 22249 22249 E THREAD_STATE:     java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1132)
09-23 07:00:44.878 22249 22249 E THREAD_STATE:     java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:849)
09-23 07:00:44.878 22249 22249 E THREAD_STATE:     java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
09-23 07:00:44.878 22249 22249 E THREAD_STATE:     java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
09-23 07:00:44.878 22249 22249 E THREAD_STATE:     java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
09-23 07:00:44.878 22249 22249 E THREAD_STATE:     java.lang.Thread.run(Thread.java:919)
09-23 07:00:44.878 22249 22249 E THREAD_STATE: 
09-23 07:00:44.878 22249 22249 E THREAD_STATE:   Thread[Profile Saver,5,system]
09-23 07:00:44.878 22249 22249 E THREAD_STATE: 
09-23 07:00:44.878 22249 22249 E THREAD_STATE:   Thread[Signal Catcher,5,system]
09-23 07:00:44.878 22249 22249 E THREAD_STATE: 
09-23 07:00:44.878 22249 22249 E THREAD_STATE:   Thread[RxComputationThreadPool-1,5,main]
09-23 07:00:44.878 22249 22249 E THREAD_STATE:     sun.misc.Unsafe.park(Native Method)
09-23 07:00:44.878 22249 22249 E THREAD_STATE:     java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
09-23 07:00:44.878 22249 22249 E THREAD_STATE:     java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2067)
09-23 07:00:44.878 22249 22249 E THREAD_STATE:     java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1120)
09-23 07:00:44.878 22249 22249 E THREAD_STATE:     java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:849)
09-23 07:00:44.878 22249 22249 E THREAD_STATE:     java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
09-23 07:00:44.878 22249 22249 E THREAD_STATE:     java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
09-23 07:00:44.878 22249 22249 E THREAD_STATE:     java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
09-23 07:00:44.878 22249 22249 E THREAD_STATE:     java.lang.Thread.run(Thread.java:919)
09-23 07:00:44.878 22249 22249 E THREAD_STATE: 
09-23 07:00:44.878 22249 22249 E THREAD_STATE:   Thread[ScionFrontendApi,5,main]
09-23 07:00:44.878 22249 22249 E THREAD_STATE:     sun.misc.Unsafe.park(Native Method)
09-23 07:00:44.878 22249 22249 E THREAD_STATE:     java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
09-23 07:00:44.878 22249 22249 E THREAD_STATE:     java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2109)
09-23 07:00:44.878 22249 22249 E THREAD_STATE:     java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
09-23 07:00:44.878 22249 22249 E THREAD_STATE:     java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1091)
09-23 07:00:44.878 22249 22249 E THREAD_STATE:     java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
09-23 07:00:44.878 22249 22249 E THREAD_STATE:     java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
09-23 07:00:44.878 22249 22249 E THREAD_STATE:     java.lang.Thread.run(Thread.java:919)
09-23 07:00:44.878 22249 22249 E THREAD_STATE: 
09-23 07:00:44.878 22249 22249 E THREAD_STATE:   Thread[RxCachedThreadScheduler-1,5,main]
09-23 07:00:44.878 22249 22249 E THREAD_STATE:     sun.misc.Unsafe.park(Native Method)
09-23 07:00:44.878 22249 22249 E THREAD_STATE:     java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
09-23 07:00:44.878 22249 22249 E THREAD_STATE:     java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2067)
09-23 07:00:44.878 22249 22249 E THREAD_STATE:     java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1120)
09-23 07:00:44.878 22249 22249 E THREAD_STATE:     java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:849)
09-23 07:00:44.878 22249 22249 E THREAD_STATE:     java.util.concurrent.ThreadPoolEx
09-23 07:00:44.878 22249 22249 E MonitoringInstr: Dying now...
09-23 07:00:44.879 22249 22249 D AndroidRuntime: Shutting down VM
09-23 07:00:44.880 22249 22249 E AndroidRuntime: FATAL EXCEPTION: main
09-23 07:00:44.880 22249 22249 E AndroidRuntime: Process: de.projectX.app.android.debug, PID: 22249
```

**Comment by StephanB75** [comment]
true, but i have no idea why instrumentation crashed there :D

**Comment by mykola-mokhnach** [comment]
I don't think the original issues has anything to do with Appium. there are multiple mentions of the same crash in google search: https://stackoverflow.com/questions/55875198/illegalstateexception-workmanager-is-already-initialized

**Comment by StephanB75** [comment]
ok thank you, i think i have maybe missed something on the configuration part.
Do we have to add "stuff" to the app under test, that it works with espresso ?

**Comment by mykola-mokhnach** [comment]
We don't know. For simple apps one usually should not add anything, they work out of the box. For more complicated apps with lots of dependencies or code obfuscation it might be necessary to disable the obfuscation or add some extra dependencies based on what Espresso complains about. Unfortunately there is no universal recipe.

**Comment by StephanB75** [comment]
Thanks for the quick response. Obfuscation might be the problem. I will disable it and try again !

**Comment by StephanB75** [comment]
had to add additionalAppDependecies for the workmanager
Thank you very much for the help!

**Comment by mykola-mokhnach** [comment]
You could also mention what exactly you've added, so the post could be helpful to others who face the same issue

**Comment by StephanB75** [comment]
i have added the capability
`"appium:espressoBuildConfig": {
    "toolsVersions": {
        "compileSdk": 30,
        "targetSdk": 30,
        "androidGradlePlugin": "4.2.2",
        "buildTools": "30.0.3",
        "kotlin": "1.5.10",
        "minSdk": 23
    },
    "additionalAppDependencies": ["androidx.work:work-runtime:2.6.0-rc01", "androidx.work:work-rxjava2:2.6.0-rc01"] 
 }"`

**Comment by jlipps** [comment]
thanks for the update @StephanB75 I think this will be helpful for others too.
