### ISSUE TITLE
A memory leak when running auto tests on IOS

### ISSUE THREAD

**Issue by enforse** [appium/appium#15928]
## The problem

The problem is related to a memory leak when running auto tests on IOS, after an error "no such alert error" 
a critical jump in RAM occurs and the Appium server is disconnected.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.0 - 1.22.0
* Last Appium version that did not exhibit the issue (if applicable): 1.18.0
* Desktop OS / version used to run Appium: macOS Big Sur
* Node.js version (unless using Appium.app | exe): v14.4.0
* Npm or Yarn package manager: npm
* Mobile platform / version under test: IOS 15.0
* Real device or emulator / simulator: Real device
* Appium CLI or Appium.app | exe: CLI

## Details

On version Appium 1.20.0 - 1.22.0 tests on IOS 14-15.0 causes a leak of memory, when Appium does not find element.
Existing error "No such alert" and subsequent attempts to trigger a search for an element cause an increase in RAM.
On version 1.18.2 this problem don't reproduced. 
However, the speed of tests drops sharp due to the lack of optimization.

## Link to Appium logs
Last logs for session terminate:

2021-10-04 13:56:43:920 [W3C] Matched W3C error code 'no such alert' to NoSuchAlertError
2021-10-04 13:56:43:921 [WD Proxy] Matched '/alert/text' to command name 'getAlertText'
2021-10-04 13:56:43:921 [WD Proxy] Proxying [GET /alert/text] to [GET http://127.0.0.1:8100/session/C10653A3-214E-47F9-8C89-64066AC32B30/alert/text] with no body
2021-10-04 13:56:43:996 [WD Proxy] Got response with status 404: {"value":{"error":"no such alert","message":"An attempt was made to operate on a modal dialog when one was not open","traceback":""},"sessionId":"C10653A3-214E-47F9-8C89-64066AC32B30"}
2021-10-04 13:56:43:996 [W3C] Matched W3C error code 'no such alert' to NoSuchAlertError
2021-10-04 13:56:43:998 [WD Proxy] Matched '/alert/text' to command name 'getAlertText'
2021-10-04 13:56:43:998 [WD Proxy] Proxying [GET /alert/text] to [GET http://127.0.0.1:8100/session/C10653A3-214E-47F9-8C89-64066AC32B30/alert/text] with no body
2021-10-04 13:56:44:068 [WD Proxy] Got response with status 404: {"value":{"error":"no such alert","message":"An attempt was made to operate on a modal dialog when one was not open","traceback":""},"sessionId":"C10653A3-214E-47F9-8C89-64066AC32B30"}
2021-10-04 13:56:44:068 [W3C] Matched W3C error code 'no such alert' to NoSuchAlertError
2021-10-04 13:56:44:070 [WD Proxy] Matched '/alert/text' to command name 'getAlertText'
2021-10-04 13:56:44:070 [WD Proxy] Proxying [GET /alert/text] to [GET http://127.0.0.1:8100/session/C10653A3-214E-47F9-8C89-64066AC32B30/alert/text] with no body
2021-10-04 13:56:44:142 [WD Proxy] Got response with status 404: {"value":{"error":"no such alert","message":"An attempt was made to operate on a modal dialog when one was not open","traceback":""},"sessionId":"C10653A3-214E-47F9-8C89-64066AC32B30"}
2021-10-04 13:56:44:142 [W3C] Matched W3C error code 'no such alert' to NoSuchAlertError
2021-10-04 13:56:44:143 [WD Proxy] Matched '/alert/text' to command name 'getAlertText'
2021-10-04 13:56:44:143 [WD Proxy] Proxying [GET /alert/text] to [GET http://127.0.0.1:8100/session/C10653A3-214E-47F9-8C89-64066AC32B30/alert/text] with no body
2021-10-04 13:56:44:226 [WD Proxy] Got response with status 404: {"value":{"error":"no such alert","message":"An attempt was made to operate on a modal dialog when one was not open","traceback":""},"sessionId":"C10653A3-214E-47F9-8C89-64066AC32B30"}
2021-10-04 13:56:44:227 [W3C] Matched W3C error code 'no such alert' to NoSuchAlertError
2021-10-04 13:56:44:229 [WD Proxy] Matched '/alert/text' to command name 'getAlertText'
2021-10-04 13:56:44:229 [WD Proxy] Proxying [GET /alert/text] to [GET http://127.0.0.1:8100/session/C10653A3-214E-47F9-8C89-64066AC32B30/alert/text] with no body
2021-10-04 13:56:44:246 [HTTP] --> DELETE /wd/hub/session/13b868a3-e19d-4ece-8fa4-e913c5a9397d
2021-10-04 13:56:44:246 [HTTP] {}
2021-10-04 13:56:44:247 [W3C (13b868a3)] Calling AppiumDriver.deleteSession() with args: ["13b868a3-e19d-4ece-8fa4-e913c5a9397d"]
2021-10-04 13:56:44:247 [BaseDriver] Event 'quitSessionRequested' logged at 1633355804247 (16:56:44 GMT+0300 (Moscow Standard Time))
2021-10-04 13:56:44:248 [Appium] Removing session 13b868a3-e19d-4ece-8fa4-e913c5a9397d from our master session list
2021-10-04 13:56:44:250 [WD Proxy] Matched '/session/13b868a3-e19d-4ece-8fa4-e913c5a9397d' to command name 'deleteSession'
2021-10-04 13:56:44:250 [WD Proxy] Proxying [DELETE /session/13b868a3-e19d-4ece-8fa4-e913c5a9397d] to [DELETE http://127.0.0.1:8100/session/C10653A3-214E-47F9-8C89-64066AC32B30] with no body
2021-10-04 13:56:44:311 [WD Proxy] Got response with status 404: {"value":{"error":"no such alert","message":"An attempt was made to operate on a modal dialog when one was not open","traceback":""},"sessionId":"C10653A3-214E-47F9-8C89-64066AC32B30"}
2021-10-04 13:56:44:311 [W3C] Matched W3C error code 'no such alert' to NoSuchAlertError
2021-10-04 13:56:44:315 [WD Proxy] Matched '/alert/text' to command name 'getAlertText'
2021-10-04 13:56:44:316 [WD Proxy] Proxying [GET /alert/text] to [GET http://127.0.0.1:8100/session/C10653A3-214E-47F9-8C89-64066AC32B30/alert/text] with no body
2021-10-04 13:56:44:323 [RemoteDebugger] Application 'PID:988' disconnected. Removing from app dictionary.
2021-10-04 13:56:44:323 [RemoteDebugger] Current app is 'PID:988'
2021-10-04 13:56:44:323 [RemoteDebugger] No longer have app id. Attempting to find new one.
2021-10-04 13:56:44:331 [RemoteDebugger] Application 'PID:994' disconnected. Removing from app dictionary.
2021-10-04 13:56:44:331 [RemoteDebugger] Current app is 'undefined'
2021-10-04 13:56:44:333 [RemoteDebugger] Application 'PID:992' disconnected. Removing from app dictionary.
2021-10-04 13:56:44:333 [RemoteDebugger] Current app is 'undefined'
2021-10-04 13:56:44:530 [HTTP] <-- POST /wd/hub/session/13b868a3-e19d-4ece-8fa4-e913c5a9397d/execute/sync - - ms - -
2021-10-04 13:56:44:530 [HTTP] 
2021-10-04 13:56:44:537 [HTTP] --> POST /wd/hub/session/13b868a3-e19d-4ece-8fa4-e913c5a9397d/execute/sync
2021-10-04 13:56:44:538 [HTTP] {"script":"return (() => document.readyState).apply(null, arguments)","args":[]}
2021-10-04 13:56:44:555 [W3C (13b868a3)] Encountered internal error running command: NoSuchDriverError: A session is either terminated or not started
2021-10-04 13:56:44:555 [W3C (13b868a3)]     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:243:15)
2021-10-04 13:56:44:555 [W3C (13b868a3)]     at /usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:423:15
2021-10-04 13:56:44:555 [W3C (13b868a3)]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
2021-10-04 13:56:44:555 [W3C (13b868a3)]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:137:13)
2021-10-04 13:56:44:555 [W3C (13b868a3)]     at Route.dispatch (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:112:3)
2021-10-04 13:56:44:555 [W3C (13b868a3)]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
2021-10-04 13:56:44:555 [W3C (13b868a3)]     at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:281:22
2021-10-04 13:56:44:555 [W3C (13b868a3)]     at param (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:354:14)
2021-10-04 13:56:44:555 [W3C (13b868a3)]     at param (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:365:14)
2021-10-04 13:56:44:555 [W3C (13b868a3)]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:410:3)
2021-10-04 13:56:44:555 [W3C (13b868a3)]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
2021-10-04 13:56:44:555 [W3C (13b868a3)]     at logger (/usr/local/lib/node_modules/appium/node_modules/morgan/index.js:144:5)
2021-10-04 13:56:44:555 [W3C (13b868a3)]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
2021-10-04 13:56:44:555 [W3C (13b868a3)]     at trim_prefix (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:317:13)
2021-10-04 13:56:44:555 [W3C (13b868a3)]     at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:284:7
2021-10-04 13:56:44:555 [W3C (13b868a3)]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
2021-10-04 13:56:44:559 [HTTP] <-- POST /wd/hub/session/13b868a3-e19d-4ece-8fa4-e913c5a9397d/execute/sync 404 20 ms - 1886
2021-10-04 13:56:44:559 [HTTP] 
2021-10-04 13:56:44:562 [HTTP] --> POST /wd/hub/session/13b868a3-e19d-4ece-8fa4-e913c5a9397d/execute/sync
2021-10-04 13:56:44:562 [HTTP] {"script":"return (() => document.readyState).apply(null, arguments)","args":[]}
2021-10-04 13:56:44:562 [W3C (13b868a3)] Encountered internal error running command: NoSuchDriverError: A session is either terminated or not started
2021-10-04 13:56:44:563 [W3C (13b868a3)]     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:243:15)
2021-10-04 13:56:44:563 [W3C (13b868a3)]     at /usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:423:15
2021-10-04 13:56:44:563 [W3C (13b868a3)]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
2021-10-04 13:56:44:563 [W3C (13b868a3)]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:137:13)
2021-10-04 13:56:44:563 [W3C (13b868a3)]     at Route.dispatch (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:112:3)
2021-10-04 13:56:44:563 [W3C (13b868a3)]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
2021-10-04 13:56:44:563 [W3C (13b868a3)]     at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:281:22
2021-10-04 13:56:44:563 [W3C (13b868a3)]     at param (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:354:14)
2021-10-04 13:56:44:563 [W3C (13b868a3)]     at param (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:365:14)
2021-10-04 13:56:44:563 [W3C (13b868a3)]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:410:3)
2021-10-04 13:56:44:563 [W3C (13b868a3)]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
2021-10-04 13:56:44:563 [W3C (13b868a3)]     at logger (/usr/local/lib/node_modules/appium/node_modules/morgan/index.js:144:5)
2021-10-04 13:56:44:563 [W3C (13b868a3)]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
2021-10-04 13:56:44:563 [W3C (13b868a3)]     at trim_prefix (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:317:13)
2021-10-04 13:56:44:563 [W3C (13b868a3)]     at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:284:7
2021-10-04 13:56:44:563 [W3C (13b868a3)]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
2021-10-04 13:56:44:564 [HTTP] <-- POST /wd/hub/session/13b868a3-e19d-4ece-8fa4-e913c5a9397d/execute/sync 404 2 ms - 1886
2021-10-04 13:56:44:564 [HTTP] 
2021-10-04 13:56:44:566 [HTTP] --> POST /wd/hub/session/13b868a3-e19d-4ece-8fa4-e913c5a9397d/execute/sync
2021-10-04 13:56:44:567 [HTTP] {"script":"return (() => document.readyState).apply(null, arguments)","args":[]}
2021-10-04 13:56:44:568 [W3C (13b868a3)] Encountered internal error running command: NoSuchDriverError: A session is either terminated or not started
2021-10-04 13:56:44:568 [W3C (13b868a3)]     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:243:15)
2021-10-04 13:56:44:568 [W3C (13b868a3)]     at /usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:423:15
2021-10-04 13:56:44:568 [W3C (13b868a3)]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
2021-10-04 13:56:44:568 [W3C (13b868a3)]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:137:13)
2021-10-04 13:56:44:568 [W3C (13b868a3)]     at Route.dispatch (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:112:3)
2021-10-04 13:56:44:568 [W3C (13b868a3)]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
2021-10-04 13:56:44:568 [W3C (13b868a3)]     at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:281:22
2021-10-04 13:56:44:568 [W3C (13b868a3)]     at param (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:354:14)
2021-10-04 13:56:44:568 [W3C (13b868a3)]     at param (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:365:14)
2021-10-04 13:56:44:568 [W3C (13b868a3)]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:410:3)
2021-10-04 13:56:44:568 [W3C (13b868a3)]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
2021-10-04 13:56:44:568 [W3C (13b868a3)]     at logger (/usr/local/lib/node_modules/appium/node_modules/morgan/index.js:144:5)
2021-10-04 13:56:44:568 [W3C (13b868a3)]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
2021-10-04 13:56:44:568 [W3C (13b868a3)]     at trim_prefix (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:317:13)
2021-10-04 13:56:44:568 [W3C (13b868a3)]     at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:284:7
2021-10-04 13:56:44:568 [W3C (13b868a3)]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
2021-10-04 13:56:44:569 [HTTP] <-- POST /wd/hub/session/13b868a3-e19d-4ece-8fa4-e913c5a9397d/execute/sync 404 2 ms - 1886
2021-10-04 13:56:44:569 [HTTP] 
2021-10-04 13:56:45:360 [WD Proxy] Got response with status 200: {"value":null,"sessionId":null}
2021-10-04 13:56:45:362 [DevCon Factory] Releasing connections for 00008030-000E78D01150402E device on any port number
2021-10-04 13:56:45:362 [DevCon Factory] Found cached connections to release: ["00008030-000E78D01150402E:8100"]
2021-10-04 13:56:45:363 [DevCon Factory] Releasing the listener for '00008030-000E78D01150402E:8100'
2021-10-04 13:56:45:364 [iProxy@00008030:8100] Closing the connection
2021-10-04 13:56:45:364 [DevCon Factory] Cached connections count: 0
2021-10-04 13:56:45:364 [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
2021-10-04 13:56:45:364 [XCUITest] Found a remote debugger session. Removing...
2021-10-04 13:56:45:365 [RemoteDebugger] Disconnecting from remote debugger
2021-10-04 13:56:45:365 [RemoteDebugger] Cleaning up listeners
2021-10-04 13:56:45:368 [BaseDriver] Event 'quitSessionFinished' logged at 1633355805367 (16:56:45 GMT+0300 (Moscow Standard Time))
2021-10-04 13:56:45:368 [W3C (13b868a3)] Received response: null
2021-10-04 13:56:45:368 [W3C (13b868a3)] But deleting session, so not returning
2021-10-04 13:56:45:368 [W3C (13b868a3)] Responding to client with driver.deleteSession() result: null
2021-10-04 13:56:45:370 [HTTP] <-- DELETE /wd/hub/session/13b868a3-e19d-4ece-8fa4-e913c5a9397d 200 1123 ms - 14
2021-10-04 13:56:45:370 [HTTP] 
2021-10-04 13:56:45:374 [WD Proxy] Got response with status 404: {"value":{"error":"invalid session id","message":"Session does not exist","traceback":"(\n\t0   CoreFoundation                      0x000000018392f070 6174789A-E88C-3F5C-BA39-DE2E9EDC0750 + 626800\n\t1   libobjc.A.dylib                     0x000000019be49f54 objc_exception_throw + 60\n\t2   CoreFoundation                      0x0000000183a05494 6174789A-E88C-3F5C-BA39-DE2E9EDC0750 + 1504404\n\t3   WebDriverAgentLib                   0x0000000106df8c30 -[FBRoute raiseNoSessionException] + 104\n\t4   WebDriverAgentLib                   0x0000000106df8b64 -[FBRoute decorateRequest:] + 264\n\t5   WebDriverAgentLib                   0x0000000106df7e74 -[FBRoute_TargetAction mountRequest:intoResponse:] + 108\n\t6   WebDriverAgentLib                   0x0000000106de1f08 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 500\n\t7   WebDriverAgentLib                   0x0000000106e1b13c -[RoutingHTTPServer handleRoute:withRequest:response:] + 184\n\t8   WebDriverAgentLib                   0x0000000106e1bd3c _...

______
Error to terminal after memory overflow:

[26758:0x1045e0000]   518338 ms: Mark-sweep 2047.3 (2051.0) -> 2046.8 (2051.3) MB, 903.5 / 0.0 ms  (average mu = 0.047, current mu = 0.005) allocation failure scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x101230f15 node::Abort() (.cold.1) [/usr/local/bin/node]
 2: 0x10009e0a9 node::Abort() [/usr/local/bin/node]
 3: 0x10009e20f node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 4: 0x1001da277 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0x1001da217 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 6: 0x10036af45 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
 7: 0x10036c7ba v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/usr/local/bin/node]
 8: 0x100368787 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/bin/node]
 9: 0x100366187 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
10: 0x10037342a v8::internal::Heap::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
11: 0x1003734b1 v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
12: 0x10033fd5b v8::internal::Factory::AllocateRawFixedArray(int, v8::internal::AllocationType) [/usr/local/bin/node]
13: 0x100341819 v8::internal::Factory::NewFrameArray(int) [/usr/local/bin/node]
14: 0x10030d693 v8::internal::(anonymous namespace)::CaptureStackTrace(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::(anonymous namespace)::CaptureStackTraceOptions) [/usr/local/bin/node]
15: 0x10030de61 v8::internal::Isolate::CaptureAndSetSimpleStackTrace(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::FrameSkipMode, v8::internal::Handle<v8::internal::Object>) [/usr/local/bin/node]
16: 0x100320cda v8::internal::ErrorUtils::Construct(v8::internal::Isolate*, v8::internal::Handle<v8::internal::JSFunction>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::FrameSkipMode, v8::internal::Handle<v8::internal::Object>, v8::internal::ErrorUtils::StackTraceCollection) [/usr/local/bin/node]
17: 0x10026969f v8::internal::Builtin_ErrorConstructor(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
18: 0x1009eba39 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit [/usr/local/bin/node]

**Comment by mykola-mokhnach** [comment]
Please provide a memory dump of the Node process before it crashes.

**Comment by enforse** [comment]
> Пожалуйста, предоставьте дамп памяти процесса Node, прежде чем он выйдет из строя.
[Heap.20210930.111509.44619.0.001.heapsnapshot.zip](https://github.com/appium/appium/files/7283832/Heap.20210930.111509.44619.0.001.heapsnapshot.zip)

**Comment by mykola-mokhnach** [comment]
I don't observe any issues in the provided snapshot file. Are you sure it is takes at the moment while the memory usage was close to critical?
