### ISSUE TITLE
Failed to get display density property on android 12 emulator

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium#15929]
## The problem

It seems Android 12 does not have `ro.sf.lcd_density`
https://github.com/appium/appium-android-driver/blob/e5bba2e4a5139abfa75a7d13061d11f459fe194d/lib/commands/general.js#L271-L281

## Environment

* Appium version (or git revision) that exhibits the issue: Appium 1.22.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator: Android 12 emulator.
* Appium CLI or Appium.app|exe:

## Details

```
[HTTP] --> GET /wd/hub/session/b31dd067-1826-4863-8863-51b76be41b9a/appium/device/display_density
[HTTP] {}
[debug] [W3C (b31dd067)] Calling AppiumDriver.getDisplayDensity() with args: ["b31dd067-1826-4863-8863-51b76be41b9a"]
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell getprop ro.sf.lcd_density'
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell getprop qemu.sf.lcd_density'
[AndroidDriver] Failed to get display density property.
[debug] [W3C (b31dd067)] Encountered internal error running command: Error: Failed to get display density property.
[debug] [W3C (b31dd067)]     at Object.errorAndThrow (/Users/kazuaki/.nodebrew/node/v12.21.0/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:94:35)
[debug] [W3C (b31dd067)]     at AndroidUiautomator2Driver.getDisplayDensity (/Users/kazuaki/.nodebrew/node/v12.21.0/lib/node_modules/appium/node_modules/appium-android-driver/lib/commands/general.js:309:7)
[HTTP] <-- GET /wd/hub/session/b31dd067-1826-4863-8863-51b76be41b9a/appium/device/display_density 500 120 ms - 631
[HTTP]
```

logcat:
```
10-05 00:09:10.583   546   603 W ProcessStats: Tracking association SourceState{148b235 system/1000 BTopFgs #19547} whose proc state 2 is better than process ProcessState{4388d98 com.google.android.gms.persistent/10101 pkg=com.google.android.gms} proc state 3 (12 skipped)
10-05 00:09:10.638   546  1722 D WifiNl80211Manager: Scan result ready event
10-05 00:09:10.639   546  1722 D WifiNative: Scan result ready event
10-05 00:09:10.694 10594 23231 I ChimeraConfigurator: Starting update, reason: 4 urgentFeatures: vision.ocr:-1
10-05 00:09:10.722  7001  7001 D LocationTracker: Got an updated location
10-05 00:09:10.783 10594 23231 I GmsDebugLogger: [73] 1801
10-05 00:09:10.799 10594 23231 I GmsDebugLogger: [30] [VisionOcr.optional:212420100800]
10-05 00:09:10.812 10594 23231 W ChimeraConfigService: Retry attempt was throttled. [CONTEXT service_id=264 ]
10-05 00:09:10.813 10594 23231 I GmsDebugLogger: [83] 1 [vision.ocr]
10-05 00:09:10.824 10594 23230 W Vision  : Request for optional module download of ocr failed. Request again.
10-05 00:09:10.824 10594 23230 I Vision  : Schedule retrying download ocr at 1398665 with backoff 640 seconds
10-05 00:09:15.174 23237 23237 W libc    : Access denied finding property "qemu.sf.lcd_density"
10-05 00:09:15.168 23237 23237 W getprop : type=1400 audit(0.0:195): avc: denied { read } for name="u:object_r:qemu_sf_lcd_density_prop:s0" dev="tmpfs" ino=221 scontext=u:r:shell:s0 tcontext=u:object_r:qemu_sf_lcd_density_prop:s0 tclass=file permissive=0
10-05 00:09:15.964   546   842 D ConnectivityService: releasing NetworkRequest [ REQUEST id=142, [ Transports: CELLULAR Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN&NOT_VCN_MANAGED Uid: 10102 RequestorUid: 10102 RequestorPkg: com.google.android.googlequicksearchbox] ] (release request)
10-05 00:09:15.971   321   321 I netd    : networkSetPermissionForNetwork(101, 1) <4.75ms>
10-05 00:09:25.871   546  2077 W ProcessStats: Tracking association SourceState{148b235 system/1000 BTopFgs #19583} whose proc state 2 is better than process ProcessState{4388d98 com.google.android.gms.persistent/10101 pkg=com.google.android.gms} proc state 3 (19 skipped)
```
## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by KazuCocoa** [comment]
probably we can get the density via uia2-server.

**Comment by KazuCocoa** [comment]
mm it seems espresso driver as well.

**Comment by mykola-mokhnach** [comment]
Created PRs for both UIA2 and Espresso

**Comment by KazuCocoa** [comment]
thank you!

**Comment by mykola-mokhnach** [comment]
Both PRs have been published
