### ISSUE TITLE
mobile:backdoor may have an issue in Android 12

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium#15933]
## The problem

`mobile:backdoor` test failed on Android 12 by e2e in espresso driver and ruby_lib_core lib test suite

```
  2) mobile
       mobile: backdoor
         should get element type face:
     {"message":"[execute(\"mobile: backdoor\",{\"target\":\"element\",\"elementId\":\"45a0b286-2f1a-41f9-ab9b-91951e3a161a\",\"methods\":[{\"name\":\"getTypeface\"}]})] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up","status":13,"cause":{"status":13,"value":{"me...
  Error: [execute("mobile: backdoor",{"target":"element","elementId":"45a0b286-2f1a-41f9-ab9b-91951e3a161a","methods":[{"name":"getTypeface"}]})] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
      at exports.newError (node_modules/wd/lib/utils.js:152:13)
      at /Users/kazuaki/GitHub/appium-espresso-driver/node_modules/wd/lib/callbacks.js:94:19
      at /Users/kazuaki/GitHub/appium-espresso-driver/node_modules/wd/lib/webdriver.js:205:5
      at Request._callback (node_modules/wd/lib/http-utils.js:89:7)
      at Request.self.callback (node_modules/request/request.js:185:22)
      at Request.<anonymous> (node_modules/request/request.js:1161:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1083:12)
      at endReadableNT (_stream_readable.js:1241:12)
      at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator: Andorid 12 emulator
* Appium CLI or Appium.app|exe:

## Details

The below is logcat by https://github.com/appium/ruby_lib_core/pull/338/files#diff-085e3c89b00c8cc24570774fb0ac5c5696a336ec6adc773b96740155a8aec45dR216
```
        # 10-05 18:20:30.419   524  2427 W ActivityManager: Crash of app io.appium.android.apis running instrumentation ComponentInfo{io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner}
        # 10-05 18:20:30.420   524  2427 I ActivityManager: Force stopping io.appium.android.apis appid=10151 user=0: finished inst
        # 10-05 18:20:30.421   524  2798 W WindowManager: Cannot find window which accessibility connection is added to
        # 10-05 18:20:30.424  6066  6078 W Binder  : Caught a RuntimeException from the binder stub implementation.
        # 10-05 18:20:30.424  6066  6078 W Binder  : java.lang.SecurityException: Calling from not trusted UID!
        # 10-05 18:20:30.424  6066  6078 W Binder  : 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:601)
        # 10-05 18:20:30.424  6066  6078 W Binder  : 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:505)
        # 10-05 18:20:30.424  6066  6078 W Binder  : 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:437)
        # 10-05 18:20:30.424  6066  6078 W Binder  : 	at android.os.Binder.execTransactInternal(Binder.java:1184)
        # 10-05 18:20:30.424  6066  6078 W Binder  : 	at android.os.Binder.execTransact(Binder.java:1143)
        # 10-05 18:20:30.433  1366  1366 I A       : onApplyWindowInsets: systemWindowInsets=Insets{left=0, top=83, right=0, bottom=132}
        # 10-05 18:20:30.433  1366  1366 I A       : onApplyWindowInsets: systemWindowInsets=Insets{left=0, top=83, right=0, bottom=132}
        # 10-05 18:20:30.436   329   467 D goldfish-address-space: claimShared: Ask to claim region [0x3f4b32000 0x3f5497000]
        # 10-05 18:20:30.448   329   467 D goldfish-address-space: claimShared: Ask to claim region [0x3f5497000 0x3f5dfc000]
```

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
cc @rajdeepv

**Comment by mykola-mokhnach** [comment]
I would say we could skip this test if executing for API 31+. The exception is internal to Android system itself and I'm not quite sure we could be able to find a viable workaround for it.

**Comment by KazuCocoa** [comment]
Yes, agree with the skip.
btw, currently, latest 31 emulator was not available on Azure yet (yesterday).

**Comment by mykola-mokhnach** [comment]
Thanks for the update @rajdeepv 
Feel free to raise a PR if you know how to fix this issue

**Comment by KazuCocoa** [comment]
I see, okay. Thank you!

note:
We should mention this point in releasenote users who use backdoor should tune their query.
