### ISSUE TITLE
Testing react native application doesn't launch application correctly

### ISSUE THREAD

**Issue by hashika2** [appium/appium#15941]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.0
* Last Appium version that did not exhibit the issue (if applicable): 1.22.0
* Desktop OS/version used to run Appium: 1.22.0
* Node.js version (unless using Appium.app|exe): v14.17.5
* Npm or Yarn package manager: npm
* Mobile platform/version under test:
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:

## Details

When I launch the application using node js configuration. They said can't find an element like that. So I think my appActivity direction is wrong. Can You tell me how to set appActivity in react native application?

My capabilities are : 
   capabilities: {
      platformName: "Android",
      platformVersion: "6.0.1",
      deviceName: "420032eb96995400",
      app: "C:/Users/Click/Documents/appium/app-release.apk",
      appPackage: "com.mobileappmart.conferwithfull",
      appActivity: ".MainActivity",
      automationName: "UiAutomator2"
    }

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

2021-10-08T10:50:59.046Z INFO webdriver: COMMAND findElements("accessibility id", "username")
2021-10-08T10:50:59.047Z INFO webdriver: [POST] http://127.0.0.1:4723/wd/hub/session/536474c0-55ec-4d30-acb1-d23bb6895ff0/elements
2021-10-08T10:50:59.048Z INFO webdriver: DATA { using: 'accessibility id', value: 'username' }
Error: Can't call setValue on element with selector "~username" because element wasn't found
    at Object.implicitWait [as default] (C:\Users\Click\Documents\appium\node_modules\webdriverio\build\utils\implicitWait.js:34:19)
    at async Element.elementErrorHandlerCallbackFn (C:\Users\Click\Documents\appium\node_modules\webdriverio\build\middlewares.js:20:29)
    at async Element.wrapCommandFn (C:\Users\Click\Documents\appium\node_modules\@wdio\utils\build\shim.js:131:29)
    at async main (C:\Users\Click\Documents\appium\index.js:27:7)
2021-10-08T10:50:59.174Z INFO webdriver: RESULT []

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
