### ISSUE TITLE
alert monitoring prevents returning response of 'page source' command after get available contexts command

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium#16036]
## The problem

I just noticed, but haven't dug this yet.

1. Open a session with browserName: safari
2. Calls `get available contexts` endpoint
3. Calls `page source` endpoint
   - Then, as the below, alert monitoring `getAlertText` works. It results in the page source response 12000ms delay. The result was 500.

When I set `NATIVE_APP` explicitly before the step 3, this did not occur.

```
[debug] [XCUITest] No web frames found.
[debug] [W3C (71c8b9f1)] Responding to client with driver.getContexts() result: ["NATIVE_APP"]
[HTTP] <-- GET /wd/hub/session/71c8b9f1-c581-4bb4-be71-4b8d3067229b/contexts 200 10022 ms - 24
[HTTP]
[HTTP] --> GET /wd/hub/session/71c8b9f1-c581-4bb4-be71-4b8d3067229b/source
[HTTP] {}
[debug] [W3C (71c8b9f1)] Calling AppiumDriver.getPageSource() with args: ["71c8b9f1-c581-4bb4-be71-4b8d3067229b"]
[debug] [XCUITest] Executing command 'getPageSource'
[debug] [RemoteDebugger] Executing atom 'execute_script' with 'args=["return document.documentElement.outerHTML",[]]; frames='
[debug] [RemoteDebugger] Executing 'execute_script' atom in default context
[debug] [RemoteDebugger] Sending javascript command: '(function(){return function(){var f=this;
[debug] [RemoteDebugger] funct...'
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:9967', page '1', target 'page-10' (id: 44): 'Runtime.evaluate'
[debug] [WD Proxy] Matched '/alert/text' to command name 'getAlertText'
[debug] [WD Proxy] Proxying [GET /alert/text] to [GET http://169.254.168.134:8100/session/DE617DE7-DF82-4FEA-A1FD-7615C5328FCD/alert/text] with no body
[WD Proxy] Got response with status 404: {"value":{"error":"no such alert","message":"An attempt was made to operate on a modal dialog when one was not open","traceback":""},"sessionId":"DE617DE7-DF82-4FEA-A1FD-7615C5328FCD"}
[debug] [W3C] Matched W3C error code 'no such alert' to NoSuchAlertError
[debug] [WD Proxy] Matched '/alert/text' to command name 'getAlertText'
[debug] [WD Proxy] Proxying [GET /alert/text] to [GET http://169.254.168.134:8100/session/DE617DE7-DF82-4FEA-A1FD-7615C5328FCD/alert/text] with no body
[WD Proxy] Got response with status 404: {"value":{"error":"no such alert","message":"An attempt was made to operate on a modal dialog when one was not open","traceback":""},"sessionId":"DE617DE7-DF82-4FEA-A1FD-7615C5328FCD"}
[debug] [W3C] Matched W3C error code 'no such alert' to NoSuchAlertError
[debug] [WD Proxy] Matched '/alert/text' to command name 'getAlertText'
[debug] [WD Proxy] Proxying [GET /alert/text] to [GET http://169.254.168.134:8100/session/DE617DE7-DF82-4FEA-A1FD-7615C5328FCD/alert/text] with no body
....
[debug] [W3C] Matched W3C error code 'no such alert' to NoSuchAlertError
[debug] [WD Proxy] Matched '/alert/text' to command name 'getAlertText'
[debug] [WD Proxy] Proxying [GET /alert/text] to [GET http://169.254.168.134:8100/session/C75FC048-5BB0-4986-853C-8F07C779E19D/alert/text] with no body
[WD Proxy] Got response with status 404: {"value":{"error":"no such alert","message":"An attempt was made to operate on a modal dialog when one was not open","traceback":""},"sessionId":"C75FC048-5BB0-4986-853C-8F07C779E19D"}
[debug] [W3C] Matched W3C error code 'no such alert' to NoSuchAlertError
[debug] [XCUITest] Error received while executing atom: operation timed out
[debug] [W3C (d98f4707)] Encountered internal error running command: Error: Did not get any response for atom execution after 120005ms
[debug] [W3C (d98f4707)]     at handlePromiseError (/Users/kazuaki/.nodebrew/node/v12.21.0/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/web.js:550:15)
[HTTP] <-- GET /wd/hub/session/d98f4707-3442-4397-8c7a-6ee14b1cd252/source 500 120011 ms - 669
[HTTP]
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.1-rc3, 1.22.0
* Last Appium version that did not exhibit the issue (if applicable): not sure
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator: Real Device, iOS 15.2 beta
* Appium CLI or Appium.app|exe:

**Comment by mykola-mokhnach** [comment]
What should it prevent returning the response? The alert monitor is executed if a web atom is blocking for too long (more than 1 second). and is executed in native context, so it should not affect anything.

**Comment by KazuCocoa** [comment]
Ah... probably this behavior happened when:

1. establish a session with `browserName: safari`
2. open uicatalog (our test app)
3. open its WebView page
4. calls 'get available context' (Only 'NATIVE_APP' is available)
5. get the page source

then, the log is as the description's one.
But this steps are wrong, so this should not be an issue

**Comment by KazuCocoa** [comment]
Btw, when I open the home screen without bundleId and app and calls `getContexts`, `Cannot enter web frame without a bundle ID` error message was returned.

```
[HTTP] {}
[debug] [W3C (9697da0c)] Calling AppiumDriver.getContexts() with args: ["9697da0c-3f2c-4a39-b365-06f0546c7f88"]
[debug] [XCUITest] Executing command 'getContexts'
[debug] [XCUITest] Getting list of available contexts
[debug] [iOS] Retrieving contexts and views
[XCUITest] Cannot enter web frame without a bundle ID
[debug] [W3C (9697da0c)] Encountered internal error running command: Error: Cannot enter web frame without a bundle ID
[debug] [W3C (9697da0c)]     at Object.errorAndThrow (/Users/kazuaki/.nodebrew/node/v12.21.0/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:94:35)
[debug] [W3C (9697da0c)]     at XCUITestDriver.listWebFrames (/Users/kazuaki/.nodebrew/node/v12.21.0/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/context.js:194:9)
[debug] [W3C (9697da0c)]     at XCUITestDriver.getContextsAndViews (/Users/kazuaki/.nodebrew/node/v12.21.0/lib/node_modules/appium/node_modules/appium-ios-driver/lib/commands/context.js:160:29)
[debug] [W3C (9697da0c)]     at XCUITestDriver.getContexts (/Users/kazuaki/.nodebrew/node/v12.21.0/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/context.js:247:31)
[debug] [W3C (9697da0c)]     at commandExecutor (/Users/kazuaki/.nodebrew/node/v12.21.0/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:335:9)
[debug] [W3C (9697da0c)]     at /Users/kazuaki/.nodebrew/node/v12.21.0/lib/node_modules/appium/node_modules/async-lock/lib/index.js:137:12
[debug] [W3C (9697da0c)]     at AsyncLock._promiseTry (/Users/kazuaki/.nodebrew/node/v12.21.0/lib/node_modules/appium/node_modules/async-lock/lib/index.js:261:31)
[debug] [W3C (9697da0c)]     at exec (/Users/kazuaki/.nodebrew/node/v12.21.0/lib/node_modules/appium/node_modules/async-lock/lib/index.js:136:9)
[debug] [W3C (9697da0c)]     at AsyncLock.acquire (/Users/kazuaki/.nodebrew/node/v12.21.0/lib/node_modules/appium/node_modules/async-lock/lib/index.js:152:3)
[debug] [W3C (9697da0c)]     at XCUITestDriver.executeCommand (/Users/kazuaki/.nodebrew/node/v12.21.0/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:348:39)
[debug] [W3C (9697da0c)]     at XCUITestDriver.executeCommand (/Users/kazuaki/.nodebrew/node/v12.21.0/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:731:24)
[debug] [W3C (9697da0c)]     at AppiumDriver.executeCommand (/Users/kazuaki/.nodebrew/node/v12.21.0/lib/node_modules/appium/lib/appium.js:563:36)
[debug] [W3C (9697da0c)]     at runMicrotasks (<anonymous>)
[debug] [W3C (9697da0c)]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[debug] [W3C (9697da0c)]     at asyncHandler (/Users/kazuaki/.nodebrew/node/v12.21.0/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:297:21)
[HTTP] <-- GET /wd/hub/session/9697da0c-3f2c-4a39-b365-06f0546c7f88/contexts 500 16 ms - 637
[HTTP]
```

This behavior itself is expected for the current implementation, but in this case, we cannot achieve the below scenario that could when `autoLaunch: false` worked.

1. launch a bundle id with `autoLaunch: false`
2. do some setup before launching the bundle id
3. launch the bundle id
4. access to the webview

Do you remember why this line restricts the bundle id? @mykola-mokhnach 
https://github.com/appium/appium-xcuitest-driver/blob/808f17192bc8ae8a404abc22d4c76d51c1622f94/lib/commands/context.js#L383

**Comment by mykola-mokhnach** [comment]
Unfortunately I don't know nothing about nitty-gritty details of safari remote debugger. Maybe @jlipps could help

**Comment by KazuCocoa** [comment]
thanks. I've created https://github.com/appium/appium-xcuitest-driver/pull/1348 to remove it.

It looks like imurchie added it, but probably we did not discuss this point well since that time we supported `autoLaunch: false` usage I addressed in the above.
