### ISSUE TITLE
End-to-end tests with Appium failing in CI, WebDriverAgent not listening on 8100 with no failure

### ISSUE THREAD

**Issue by juicemia** [appium/appium#16045]
## The problem

WebDriverAgent not listening on port 8100.

## Environment

* Appium version (or git revision) that exhibits the issue: v1.22.0
* Node.js version (unless using Appium.app|exe): NodeJS 16
* Npm or Yarn package manager: NPM
* Mobile platform/version under test: iOS 15
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Appium CLI

## Details

I'm trying to run end-to-end tests on Github Actions for our React Native app.

I can't see anything in the logs about any errors or anything, I just see that WDA isn't listening on port 8100 with no indication as to why.

## Link to Appium logs

[Appium Logs](https://gist.github.com/juicemia/a029669be774837600607ce9502bb5d7)

## Code
[Actions Workflow](https://gist.github.com/juicemia/cade3b2ee4dce8182e0cad4b857702d8)

**Comment by KazuCocoa** [comment]
I guess it needed a longer time to build WDA. Could you get the log with `showXcodeLog` capability?
It will tell you if the xcodebuild has been finished or in the middle.

```
debug] [35m[WebDriverAgent][39m Output from xcodebuild will only be logged if any errors are present there. To change this, use 'showXcodeLog' desired capability
[debug] [35m[WebDriverAgent][39m Waiting up to 60000ms for WebDriverAgent to start
[debug] [35m[WD Proxy][39m Matched '/status' to command name 'getStatus'
[debug] [35m[WD Proxy][39m Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[35m[WD Proxy][39m connect ECONNREFUSED 127.0.0.1:8100
```
```
[35m[WD Proxy][39m connect ECONNREFUSED 127.0.0.1:8100
[debug] [35m[XCUITest][39m Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: connect ECONNREFUSED 127.0.0.1:8100). Retrying...
[debug] [35m[XCUITest][39m UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: connect ECONNREFUSED 127.0.0.1:8100
[debug] [35m[XCUITest][39m     at JWProxy.command (/Users/runner/hostedtoolcache/node/16.13.0/x64/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:274:13)
[debug] [35m[XCUITest][39m     at runMicrotasks (<anonymous>)
[debug] [35m[XCUITest][39m     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[debug] [35m[XCUITest][39m     at XCUITestDriver.proxyCommand (/Users/runner/hostedtoolcache/node/16.13.0/x64/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:96:12)
[debug] [35m[XCUITest][39m     at /Users/runner/hostedtoolcache/node/16.13.0/x64/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:639:62
[debug] [35m[XCUITest][39m     at wrapped (/Users/runner/hostedtoolcache/node/16.13.0/x64/lib/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:60:13)
[debug] [35m[XCUITest][39m     at retry (/Users/runner/hostedtoolcache/node/16.13.0/x64/lib/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:43:13)
[debug] [35m[XCUITest][39m     at retryInterval (/Users/runner/hostedtoolcache/node/16.13.0/x64/lib/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:70:10)
[debug] [35m[XCUITest][39m     at /Users/runner/hostedtoolcache/node/16.13.0/x64/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:635:11
[debug] [35m[XCUITest][39m     at wrapped (/Users/runner/hostedtoolcache/node/16.13.0/x64/lib/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:60:13)
[debug] [35m[XCUITest][39m     at retry (/Users/runner/hostedtoolcache/node/16.13.0/x64/lib/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:43:13)
[debug] [35m[XCUITest][39m     at retryInterval (/Users/runner/hostedtoolcache/node/16.13.0/x64/lib/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:70:10)
[debug] [35m[XCUITest][39m     at /Users/runner/hostedtoolcache/node/16.13.0/x64/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:607:7
[debug] [35m[XCUITest][39m Unable to start WebDriverAgent session because of xcodebuild failure: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: connect ECONNREFUSED 127.0.0.1:8100
[35m[XCUITest][39m Quitting and uninstalling WebDriverAgent
[35m[WebDriverAgent][39m Shutting down sub-processes
[35m[WebDriverAgent][39m Shutting down 'xcodebuild' process (pid '16799')
[35m[WebDriverAgent][39m Sending 'SIGTERM'...
[debug] [35m[iOSSim][39m Building bundle path map
```

https://github.com/appium/appium-xcuitest-driver/blob/master/ci-jobs/templates/xcuitest-e2e-template.yml is our Azure pipeline. It also may help.

**Comment by mykola-mokhnach** [comment]
Perhaps it just needs more time to compile WDA sources. Try to increase the timeout represented by [wdaLaunchTimeout](https://github.com/appium/appium-xcuitest-driver#webdriveragent) capability

**Comment by juicemia** [comment]
Thank you for answering so fast. I'll try increasing the timeout and adding the extra logging.

**Comment by juicemia** [comment]
Ok I updated the capabilities and got [this log output](https://gist.github.com/juicemia/bfbac690cc88deb43b1c8de27f31a92c).

I tried updating `wdaLaunchTimeout` but it didn't work. Maybe I'm doing something wrong.

This is how we set the capabilities in the JavaScript:


```
const driverConfig: any = {
  path: "/wd/hub",
  host: "localhost",
  port: 4723,
  capabilities: {
    "appium:platformName": "iOS",
    "appium:platformVersion": "15.0",
    "appium:connectHardwareKeyboard": true,
    "appium:wdaLaunchTimeout": 60000 * 5 // 5 minutes
  },
}
```

**Comment by juicemia** [comment]
I realized I left some of the code out that sets the capabilities. Here's the full code:

```
const driverConfig: any = {
  path: "/wd/hub",
  host: "localhost",
  port: 4723,
  capabilities: {
    "appium:platformName": "iOS",
    "appium:platformVersion": "15.0", // must correct the stimuator
    "appium:connectHardwareKeyboard": true,
    "appium:wdaLaunchTimeout": 60000 * 5 // 5 minutes
  },
}

// Check if APP_PATH is set to run the simulator from Appium with the app installed directly.
// This is useful in CI but at the same time allows the user the flexibility of using other
// methods, like Expo itself, to run the app for the end-to-end tests.
const appPath = process.env['APP_PATH'];
if (appPath) {
  driverConfig.capabilities["appium:app"] = appPath;
}

const simulatorDeviceID = process.env['IPHONE_UDID'];
if (simulatorDeviceID) {
  console.log('IPHONE_UDID set, setting udid and deviceName');
  driverConfig.capabilities["appium:udid"] = simulatorDeviceID;
  driverConfig.capabilities["appium:deviceName"] = 'TestIPhone13';
} else {
  console.log('IPHONE_UDID not set, defaulting deviceName to iPhone 13 Pro');
  driverConfig.capabilities["appium:deviceName"] = "iPhone 13 Pro";
}

const ciLoggingEnabled = process.env['CI_LOGGING_ENABLED'];
if (ciLoggingEnabled) {
  console.log('CI logging enabled');
  driverConfig.capabilities["appium:showIOSLog"] = true;
  driverConfig.capabilities["appium:showXcodeLog"] = true;
}

```

**Comment by mykola-mokhnach** [comment]
Have you tried to run the xcodebuild command separate in the terminal? What is the output of it? How much time it takes to complete?

> [35m[HTTP][39m [37m<-- POST /wd/hub/session [39m[32m-[39m [90m- ms - -[39m

This log line usually means the client gives up waiting, so than session creation never completes for you.

**Comment by juicemia** [comment]
I haven't tried that because this is running in CI. I can't even reproduce this issue on my Mac. When I run the CI steps on my Mac everything works.

Is there any way of putting timestamps in the logs? It would be useful to see the times at which each log line is printed to see if Appium is actually waiting for the desired `wdaLaunchTimeout`. I set it to 5 minutes but the whole CI step for the end-to-end tests ran in 2 minutes and 14 seconds. I would expect it to have taken more than 5 minutes.

**Comment by KazuCocoa** [comment]
`--log-timestamp` leaves timestamp in appium log. https://appium.io/docs/en/writing-running-appium/server-args/

**Comment by juicemia** [comment]
Ok, so I have a passing CI run. It seems like it came down to setting our timeouts appropriately. Thank you for the help in debugging.

**Comment by anirbandan** [comment]
Hi @juicemia, what timeout value you opted for? I am facing the exact same issue on github actions with Appium 1.22 + ios15 simulator.
I used the following capabilities with my ruby framework and it still failed with same error

caps['launchTimeout'] = 500000
