### ISSUE TITLE
Sometimes Execute self.driver.get_performance_data('com.picc.nmms','cpuinfo', 5) ，error: Unable to parse cpu usage data for 'com.cloudpower.netsale.activity'

### ISSUE THREAD

**Issue by tianyao1111** [appium/appium#16074]
## The problem

Execute self.driver.get_performance_data('com.picc.nmms','cpuinfo', 5) ，error: Unable to parse cpu usage data for 'com.cloudpower.netsale.activity'

## Environment

* Appium version (or git revision) that exhibits the issue:1.22.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:win10
* Node.js version (unless using Appium.app|exe):V14.16.0
* Npm or Yarn package manager:npm 6.14.11
* Mobile platform/version under test:10
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe:
* language：python

## Details

```
print(self.driver.get_performance_data_types())
print(self.driver.get_performance_data('com.cloudpower.netsale.activity', 'cpuinfo', 5))
```
I got an error when executing self.driver.get_performance_data('com.picc.nmms','cpuinfo', 5), the error message is as follows：
```
['cpuinfo', 'memoryinfo', 'batteryinfo', 'networkinfo']
E
======================================================================
ERROR: test_case_01 (paramunittest.RB_TB_CX_case_03_0)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\14221\Desktop\项目-git\UITestAND_PICC_RenBao_App\public\MyTestCase.py", line 23, in testPartExecutor
    yield
  File "C:\Users\14221\Desktop\项目-git\UITestAND_PICC_RenBao_App\public\MyTestCase.py", line 136, in run
    testMethod()
  File "C:\Users\14221\Desktop\项目-git\UITestAND_PICC_RenBao_App\public\common2.py", line 100, in wrapper
    func(self)
  File "C:\Users\14221\Desktop\项目-git\UITestAND_PICC_RenBao_App\public\common2.py", line 72, in wrapper
    func(self)
  File "C:\Users\14221\Desktop\项目-git\UITestAND_PICC_RenBao_App\public\common2.py", line 21, in wrapper
    func(self)
  File "RB_TB_CX_case_03.py", line 57, in test_case_01
    print(self.driver.get_performance_data('com.cloudpower.netsale.activity', 'cpuinfo', 5))
  File "C:\Users\14221\Anaconda3\lib\site-packages\appium\webdriver\extensions\android\performance.py", line 53, in get_performance_data
    return self.execute(Command.GET_PERFORMANCE_DATA, data)['value']
  File "C:\Users\14221\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\14221\Anaconda3\lib\site-packages\appium\webdriver\errorhandler.py", line 31, in check_response
    raise wde
  File "C:\Users\14221\Anaconda3\lib\site-packages\appium\webdriver\errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "C:\Users\14221\Anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Unable to parse cpu usage data for 'com.cloudpower.netsale.activity'. Check the server log for more details
```

## Link to Appium logs

```
[debug] [35m[AndroidDriver][39m  +0% 11078/kworker/u16:4: 0% user + 0% kernel

[debug] [35m[AndroidDriver][39m  +0% 11079/kworker/u16:5: 0% user + 0% kernel

[debug] [35m[AndroidDriver][39m  +0% 11380/com.baidu.input_huawei: 0% user + 0% kernel

[debug] [35m[AndroidDriver][39m  +0% 11408/kworker/5:2: 0% user + 0% kernel

[debug] [35m[AndroidDriver][39m 8.2% TOTAL: 5.2% user + 2.7% kernel + 0% iowait + 0.2% softirq
[debug] [35m[W3C (17a5a4a0)][39m Encountered internal error running command: Error: Unable to parse cpu usage data for 'com.cloudpower.netsale.activity'. Check the server log for more details
[debug] [35m[W3C (17a5a4a0)][39m     at C:\Users\14221\AppData\Roaming\npm\node_modules\appium\node_modules\appium-android-driver\lib\commands\performance.js:87:13
[debug] [35m[W3C (17a5a4a0)][39m     at wrapped (C:\Users\14221\AppData\Roaming\npm\node_modules\appium\node_modules\asyncbox\lib\asyncbox.js:60:13)
[debug] [35m[W3C (17a5a4a0)][39m     at retry (C:\Users\14221\AppData\Roaming\npm\node_modules\appium\node_modules\asyncbox\lib\asyncbox.js:43:13)
[debug] [35m[W3C (17a5a4a0)][39m     at retryInterval (C:\Users\14221\AppData\Roaming\npm\node_modules\appium\node_modules\asyncbox\lib\asyncbox.js:70:10)
[debug] [35m[W3C (17a5a4a0)][39m     at AndroidUiautomator2Driver.getCPUInfo (C:\Users\14221\AppData\Roaming\npm\node_modules\appium\node_modules\appium-android-driver\lib\commands\performance.js:70:10)
[debug] [35m[W3C (17a5a4a0)][39m     at AndroidUiautomator2Driver.getPerformanceData (C:\Users\14221\AppData\Roaming\npm\node_modules\appium\node_modules\appium-android-driver\lib\commands\performance.js:50:14)
[35m[HTTP][39m [37m<-- POST /wd/hub/session/17a5a4a0-75c2-4a26-b04b-7477e497e03a/appium/getPerformanceData [39m[31m500[39m [90m8228 ms - 775[39m

```

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
There is a [TODO](https://github.com/appium/appium-android-driver/blob/dcf8c6a016eba557d6b8abd8097c78358a166ea7/lib/commands/performance.js#L65) comment about this in the code. Basically, it look like dumpsys needs time to pick up the process, so doing more retries could help.

**Comment by tianyao1111** [comment]
> There is a [TODO](https://github.com/appium/appium-android-driver/blob/dcf8c6a016eba557d6b8abd8097c78358a166ea7/lib/commands/performance.js#L65) comment about this in the code. Basically, it looks like dumpsys needs time to pick up the process, so doing more retries could help.

thank you!

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
