### ISSUE TITLE
Hey I m new to coding, I am getting " Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\lenovo\\OneDrive\\Android-sdk\\platform-tools\\adb.exe -P 5037 -s fc7cdc750407 install -g 'C:\\Users\\lenovo\\AppData\\Local\\Programs\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\io.appium.settings\\apks\\settings_apk-debug.apk'' exited with code 1'; Stderr: 'adb: failed to install C:\Users\lenovo\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\io.appium.settings\apks\settings_apk-debug.apk:  Exception occurred while executing 'install': " error

### ISSUE THREAD

**Issue by SnehaReddy2** [appium/appium#16096]
**Code:** 

package appium;

import java.net.URL;
import org.openqa.selenium.remote.DesiredCapabilities;
import io.appium.java_client.AppiumDriver;
import io.appium.java_client.MobileElement;

public class calculator {
 static AppiumDriver<MobileElement> driver;
	public static void main(String[] args) {
		
		try 
		{ 
			openCalculator();
		}catch(Exception exp) {
		System.out.println(exp.getCause());
			System.out.println(exp.getMessage());
			exp.printStackTrace();
		}
	}
public static void openCalculator() throws Exception {
	
	DesiredCapabilities cap = new DesiredCapabilities();
	cap.setCapability("Device Name", "POCO M2");
	cap.setCapability("udid", "fc7cdc750407");
	cap.setCapability("platformName", "Android");
	cap.setCapability("automationName", "UiAutomator1");
	cap.setCapability("platformVersion", "11");
	cap.setCapability("appPackage", "com.miui.calculator");
	cap.setCapability("appActivity", "com.miui.calculator.cal.CalculatorActivity");

	URL url= new URL("http://127.0.0.1:4723/wd/hub");
driver = new AppiumDriver<MobileElement>(url, cap);	
System.out.println("Application Started");

}

}

**Console**
java.lang.reflect.InvocationTargetException
org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\lenovo\\OneDrive\\Android-sdk\\platform-tools\\adb.exe -P 5037 -s fc7cdc750407 install -g 'C:\\Users\\lenovo\\AppData\\Local\\Programs\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\io.appium.settings\\apks\\settings_apk-debug.apk'' exited with code 1'; Stderr: 'adb: failed to install C:\Users\lenovo\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\io.appium.settings\apks\settings_apk-debug.apk: 
Exception occurred while executing 'install':
java.lang.SecurityException: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag
	at com.android.server.pm.PackageInstallerService.createSessionInternal(PackageInstallerService.java:628)
	at com.android.server.pm.PackageInstallerService.createSession(PackageInstallerService.java:502)
	at com.android.server.pm.PackageManagerShellCommand.doCreateSession(PackageManagerShellC'; Code: '1'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-OS4CBJ6', ip: '192.168.172.176', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.1'
Driver info: driver.version: AppiumDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\lenovo\\OneDrive\\Android-sdk\\platform-tools\\adb.exe -P 5037 -s fc7cdc750407 install -g 'C:\\Users\\lenovo\\AppData\\Local\\Programs\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\io.appium.settings\\apks\\settings_apk-debug.apk'' exited with code 1'; Stderr: 'adb: failed to install C:\Users\lenovo\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\io.appium.settings\apks\settings_apk-debug.apk: 
Exception occurred while executing 'install':
java.lang.SecurityException: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag
	at com.android.server.pm.PackageInstallerService.createSessionInternal(PackageInstallerService.java:628)
	at com.android.server.pm.PackageInstallerService.createSession(PackageInstallerService.java:502)
	at com.android.server.pm.PackageManagerShellCommand.doCreateSession(PackageManagerShellC'; Code: '1'
    at getResponseForW3CError (C:\Users\lenovo\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\lenovo\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:380:37)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-OS4CBJ6', ip: '192.168.172.176', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.1'
Driver info: driver.version: AppiumDriver
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:216)
	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:225)
Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\lenovo\\OneDrive\\Android-sdk\\platform-tools\\adb.exe -P 5037 -s fc7cdc750407 install -g 'C:\\Users\\lenovo\\AppData\\Local\\Programs\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\io.appium.settings\\apks\\settings_apk-debug.apk'' exited with code 1'; Stderr: 'adb: failed to install C:\Users\lenovo\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\io.appium.settings\apks\settings_apk-debug.apk: 
Exception occurred while executing 'install':
java.lang.SecurityException: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag
	at com.android.server.pm.PackageInstallerService.createSessionInternal(PackageInstallerService.java:628)
	at com.android.server.pm.PackageInstallerService.createSession(PackageInstallerService.java:502)
	at com.android.server.pm.PackageManagerShellCommand.doCreateSession(PackageManagerShellC'; Code: '1'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-OS4CBJ6', ip: '192.168.172.176', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.1'
Driver info: driver.version: AppiumDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\lenovo\\OneDrive\\Android-sdk\\platform-tools\\adb.exe -P 5037 -s fc7cdc750407 install -g 'C:\\Users\\lenovo\\AppData\\Local\\Programs\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\io.appium.settings\\apks\\settings_apk-debug.apk'' exited with code 1'; Stderr: 'adb: failed to install C:\Users\lenovo\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\io.appium.settings\apks\settings_apk-debug.apk: 
Exception occurred while executing 'install':
java.lang.SecurityException: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag
	at com.android.server.pm.PackageInstallerService.createSessionInternal(PackageInstallerService.java:628)
	at com.android.server.pm.PackageInstallerService.createSession(PackageInstallerService.java:502)
	at com.android.server.pm.PackageManagerShellCommand.doCreateSession(PackageManagerShellC'; Code: '1'
    at getResponseForW3CError (C:\Users\lenovo\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\lenovo\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:380:37)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-OS4CBJ6', ip: '192.168.172.176', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.1'
Driver info: driver.version: AppiumDriver
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:250)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:363)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:37)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:89)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:99)
	at appium.calculator.openCalculator(calculator.java:34)
	at appium.calculator.main(calculator.java:15)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:193)
	... 13 more
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\lenovo\\OneDrive\\Android-sdk\\platform-tools\\adb.exe -P 5037 -s fc7cdc750407 install -g 'C:\\Users\\lenovo\\AppData\\Local\\Programs\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\io.appium.settings\\apks\\settings_apk-debug.apk'' exited with code 1'; Stderr: 'adb: failed to install C:\Users\lenovo\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\io.appium.settings\apks\settings_apk-debug.apk: 
Exception occurred while executing 'install':
java.lang.SecurityException: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag
	at com.android.server.pm.PackageInstallerService.createSessionInternal(PackageInstallerService.java:628)
	at com.android.server.pm.PackageInstallerService.createSession(PackageInstallerService.java:502)
	at com.android.server.pm.PackageManagerShellCommand.doCreateSession(PackageManagerShellC'; Code: '1'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-OS4CBJ6', ip: '192.168.172.176', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.1'
Driver info: driver.version: AppiumDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\lenovo\\OneDrive\\Android-sdk\\platform-tools\\adb.exe -P 5037 -s fc7cdc750407 install -g 'C:\\Users\\lenovo\\AppData\\Local\\Programs\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\io.appium.settings\\apks\\settings_apk-debug.apk'' exited with code 1'; Stderr: 'adb: failed to install C:\Users\lenovo\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\io.appium.settings\apks\settings_apk-debug.apk: 
Exception occurred while executing 'install':
java.lang.SecurityException: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag
	at com.android.server.pm.PackageInstallerService.createSessionInternal(PackageInstallerService.java:628)
	at com.android.server.pm.PackageInstallerService.createSession(PackageInstallerService.java:502)
	at com.android.server.pm.PackageManagerShellCommand.doCreateSession(PackageManagerShellC'; Code: '1'
    at getResponseForW3CError (C:\Users\lenovo\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\lenovo\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:380:37)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	... 18 more

**Comment by mykola-mokhnach** [comment]
Please use [Appium forum](https;//discuss.appium.io) to ask questions.
