### ISSUE TITLE
Fix for appium-beta base-driver caching

### ISSUE THREAD

**Issue by bennid** [appium/appium#16146]
## The problem

The following PR to fix the appium caching of remote apps breaks when the app is expired: https://github.com/appium/appium-base-driver/pull/541 (FYI @mykola-mokhnach )

This was using appium 1.23 beta

```
2021-11-22 09:00:03:458 - [HTTP] --> POST /wd/hub/session/238ba444-8f90-45f1-bc24-1816f753f60a/appium/device/install_app
2021-11-22 09:00:03:458 - [HTTP] {"appPath":"http://qa01-dev.dhcp.tripadvisor.com:8000/files/prerelease-7.8.0-2022004436.ipa"}
2021-11-22 09:00:03:458 - [debug] [W3C (238ba444)] Calling AppiumDriver.installApp() with args: ["http://qa01-dev.dhcp.tripadvisor.com:8000/files/prerelease-7.8.0-2022004436.ipa",null,null,null,"238ba444-8f90-45f1-bc24-1816f753f60a"]
2021-11-22 09:00:03:458 - [debug] [XCUITest] Executing command 'installApp'
2021-11-22 09:00:03:458 - [BaseDriver] The application 'http://qa01-dev.dhcp.tripadvisor.com:8000/files/prerelease-7.8.0-2022004436.ipa' cached at '/var/folders/jz/df6zx5h10cx55f9b1zk8dbrw0000gq/T/20211019-4625-1tmwik9.iq8/Viator.app' has expired after 86400000ms
2021-11-22 09:00:03:459 - [debug] [W3C (238ba444)] Encountered internal error running command: TypeError: Callback must be a function. Received 0
2021-11-22 09:00:03:459 - [debug] [W3C (238ba444)]     at setTimeout (node:timers:141:3)
2021-11-22 09:00:03:459 - [debug] [W3C (238ba444)]     at LRUCache.dispose (/Users/jenkins/build_tools/ios_phone/00008020-000C11002E3A002E/node_modules/appium-base-driver/lib/basedriver/helpers.js:24:5)
2021-11-22 09:00:03:459 - [debug] [W3C (238ba444)]     at del (/Users/jenkins/build_tools/ios_phone/00008020-000C11002E3A002E/node_modules/lru-cache/index.js:305:20)
2021-11-22 09:00:03:459 - [debug] [W3C (238ba444)]     at get (/Users/jenkins/build_tools/ios_phone/00008020-000C11002E3A002E/node_modules/lru-cache/index.js:264:7)
2021-11-22 09:00:03:459 - [debug] [W3C (238ba444)]     at LRUCache.get (/Users/jenkins/build_tools/ios_phone/00008020-000C11002E3A002E/node_modules/lru-cache/index.js:212:12)
2021-11-22 09:00:03:459 - [debug] [W3C (238ba444)]     at Object.configureApp (/Users/jenkins/build_tools/ios_phone/00008020-000C11002E3A002E/node_modules/appium-base-driver/lib/basedriver/helpers.js:177:44)
2021-11-22 09:00:03:459 - [debug] [W3C (238ba444)]     at XCUITestDriver.mobileInstallApp (/Users/jenkins/build_tools/ios_phone/00008020-000C11002E3A002E/node_modules/appium-xcuitest-driver/lib/commands/app-management.js:22:41)
2021-11-22 09:00:03:459 - [debug] [W3C (238ba444)]     at XCUITestDriver.installApp (/Users/jenkins/build_tools/ios_phone/00008020-000C11002E3A002E/node_modules/appium-xcuitest-driver/lib/commands/app-management.js:87:14)
2021-11-22 09:00:03:459 - [debug] [W3C (238ba444)]     at commandExecutor (/Users/jenkins/build_tools/ios_phone/00008020-000C11002E3A002E/node_modules/appium-base-driver/lib/basedriver/driver.js:335:9)
2021-11-22 09:00:03:459 - [debug] [W3C (238ba444)]     at /Users/jenkins/build_tools/ios_phone/00008020-000C11002E3A002E/node_modules/async-lock/lib/index.js:146:12
2021-11-22 09:00:03:459 - [debug] [W3C (238ba444)]     at AsyncLock._promiseTry (/Users/jenkins/build_tools/ios_phone/00008020-000C11002E3A002E/node_modules/async-lock/lib/index.js:280:31)
2021-11-22 09:00:03:459 - [debug] [W3C (238ba444)]     at exec (/Users/jenkins/build_tools/ios_phone/00008020-000C11002E3A002E/node_modules/async-lock/lib/index.js:145:9)
2021-11-22 09:00:03:459 - [debug] [W3C (238ba444)]     at AsyncLock.acquire (/Users/jenkins/build_tools/ios_phone/00008020-000C11002E3A002E/node_modules/async-lock/lib/index.js:162:3)
2021-11-22 09:00:03:459 - [debug] [W3C (238ba444)]     at XCUITestDriver.executeCommand (/Users/jenkins/build_tools/ios_phone/00008020-000C11002E3A002E/node_modules/appium-base-driver/lib/basedriver/driver.js:348:39)
2021-11-22 09:00:03:459 - [debug] [W3C (238ba444)]     at XCUITestDriver.executeCommand (/Users/jenkins/build_tools/ios_phone/00008020-000C11002E3A002E/node_modules/appium-xcuitest-driver/lib/driver.js:786:24)
2021-11-22 09:00:03:459 - [debug] [W3C (238ba444)]     at AppiumDriver.executeCommand (/Users/jenkins/build_tools/ios_phone/00008020-000C11002E3A002E/node_modules/appium/lib/appium.js:563:36)
2021-11-22 09:00:03:460 - [HTTP] <-- POST /wd/hub/session/238ba444-8f90-45f1-bc24-1816f753f60a/appium/device/install_app 500 2 ms - 631
```

**Comment by mykola-mokhnach** [comment]
Thanks for checking it @bennid 
The fix should be simple

**Comment by mykola-mokhnach** [comment]
The patch has been merged and published

**Comment by bennid** [comment]
@mykola-mokhnach What's the plan for getting 7.11.2 into 1.23.0 beta?

**Comment by mykola-mokhnach** [comment]
It's already there. beta versions are not shrinkwrapped, which means by reinstalling it you always get recent module versions

**Comment by bennid** [comment]
Hmmm... for some reason removing the directory and reinstalling is only grabbing 7.11.1.... maybe local caching :/

**Comment by bennid** [comment]
Still having issues:
```
 ➜ 7090eac95fe26e87ec013646c75a289c235003c7 yarn add appium@beta
yarn add v1.22.17
warning package.json: No license field
warning No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
warning No license field
success Saved 1 new dependency.
info Direct dependencies
└─ appium@1.23.0-beta.0
info All dependencies
└─ appium@1.23.0-beta.0
✨  Done in 19.40s.
 ➜ 7090eac95fe26e87ec013646c75a289c235003c7 npm ls 
 ➜ 7090eac95fe26e87ec013646c75a289c235003c7 npm ls --depth 1 | grep base-driver
  ├── appium-base-driver@7.11.0
 ➜ 7090eac95fe26e87ec013646c75a289c235003c7 
```
