### ISSUE TITLE
POST /appium/device/press_keycode'cannot be proxied to UiAutomator2 server because the instrumentation process is not running 

### ISSUE THREAD

**Issue by WuXiaoJun111** [appium/appium#16152]
## The problem

An unknown server-side error occurred while processing the command. Original error: 'POST /appium/device/press_keycode' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
18:06:01  Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
18:06:01  System info: host: 'ZRFG051588', ip: '165.96.211.176', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_202'
18:06:01  Driver info: io.appium.java_client.android.AndroidDriver
18:06:01  Capabilities {adbExecTimeout: 120000, appWaitDuration: 40000, automationName: UiAutomator2, databaseEnabled: false, desired: {adbExecTimeout: 120000, appWaitDuration: 40000, automationName: UiAutomator2, deviceName: 165.96.211.79:49110, ignoreUnimportantViews: false, newCommandTimeout: 864000, noSign: true, platformName: android, platformVersion: 6.0, resetKeyboard: true, systemPort: 8224, udid: 165.96.211.79:49110, uiautomator2ServerInstallTimeout: 120000, unicodeKeyboard: true}, deviceApiLevel: 29, deviceManufacturer: Renesas, deviceModel: HIHOPE_RZG2N-r8a774b1, deviceName: 165.96.211.79:49110, deviceScreenDensity: 160, deviceScreenSize: 1024x600, deviceUDID: 165.96.211.79:49110, ignoreUnimportantViews: false, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, newCommandTimeout: 864000, noSign: true, pixelRatio: 1, platform: LINUX, platformName: Android, platformVersion: 10, resetKeyboard: true, statBarHeight: 40, systemPort: 8224, takesScreenshot: true, udid: 165.96.211.79:49110, uiautomator2ServerInstallTimeout: 120000, unicodeKeyboard: true, viewportRect: {height: 520, left: 0, top: 40, width: 1024}, warnings: {}, webStorageEnabled: false}
18:06:01  Session ID: 40894110-f0e1-4aad-9e2a-9373dd18501d ·· ·· ·· ·· ·· × 】

## Environment

* Appium version (or git revision) that exhibits the issue:V1.20.2
* Mobile platform/version under test: Android10.0
* Real device or emulator/simulator:Real device

## Details

An unknown server-side error occurred while processing the command. Original error: 'POST /appium/device/press_keycode' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
18:06:01  Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
18:06:01  System info: host: 'ZRFG051588', ip: '165.96.211.176', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_202'
18:06:01  Driver info: io.appium.java_client.android.AndroidDriver
18:06:01  Capabilities {adbExecTimeout: 120000, appWaitDuration: 40000, automationName: UiAutomator2, databaseEnabled: false, desired: {adbExecTimeout: 120000, appWaitDuration: 40000, automationName: UiAutomator2, deviceName: 165.96.211.79:49110, ignoreUnimportantViews: false, newCommandTimeout: 864000, noSign: true, platformName: android, platformVersion: 6.0, resetKeyboard: true, systemPort: 8224, udid: 165.96.211.79:49110, uiautomator2ServerInstallTimeout: 120000, unicodeKeyboard: true}, deviceApiLevel: 29, deviceManufacturer: Renesas, deviceModel: HIHOPE_RZG2N-r8a774b1, deviceName: 165.96.211.79:49110, deviceScreenDensity: 160, deviceScreenSize: 1024x600, deviceUDID: 165.96.211.79:49110, ignoreUnimportantViews: false, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, newCommandTimeout: 864000, noSign: true, pixelRatio: 1, platform: LINUX, platformName: Android, platformVersion: 10, resetKeyboard: true, statBarHeight: 40, systemPort: 8224, takesScreenshot: true, udid: 165.96.211.79:49110, uiautomator2ServerInstallTimeout: 120000, unicodeKeyboard: true, viewportRect: {height: 520, left: 0, top: 40, width: 1024}, warnings: {}, webStorageEnabled: false}
18:06:01  Session ID: 40894110-f0e1-4aad-9e2a-9373dd18501d ·· ·· ·· ·· ·· × 】

## Link to Appium logs

2021-11-23 19:01:44:808 [BaseDriver] Event 'newSessionStarted' logged at 1637661704808 (19:01:44 GMT+0900 (日本標準時))
2021-11-23 19:01:44:809 [W3C (ec465b19)] Cached the protocol value 'W3C' for the new session ec465b19-14fb-4be5-9391-e574a2858a3d
2021-11-23 19:01:44:810 [W3C (ec465b19)] Responding to client with driver.createSession() result: {"capabilities":{"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platformName":"android","uiautomator2ServerInstallTimeout":120000,"adbExecTimeout":120000,"appWaitDuration":40000,"automationName":"UiAutomator2","deviceName":"165.96.211.79:49110","ignoreUnimportantViews":false,"newCommandTimeout":864000,"noSign":true,"platformVersion":"6.0","resetKeyboard":true,"systemPort":8223,"udid":"165.96.211.79:49110","unicodeKeyboard":true},"platformName":"android","uiautomator2ServerInstallTimeout":120000,"adbExecTimeout":120000,"appWaitDuration":40000,"automationName":"UiAutomator2","deviceName":"165.96.211.79:49110","ignoreUnimportantViews":false,"newCommandTimeout":864000,"noSign":true,"platformVersion":"10","resetKeyboard":true,"systemPort":8223,"udid":"165.96.211.79:49110","unicodeKeyboard":true,"deviceUDID":"165.96.211.79:49110","deviceApiLevel":29,"devic...
2021-11-23 19:01:44:812 [HTTP] <-- POST /wd/hub/session 200 9033 ms - 1297
2021-11-23 19:01:44:813 [HTTP] 
2021-11-23 19:01:44:843 [HTTP] --> POST /wd/hub/session/ec465b19-14fb-4be5-9391-e574a2858a3d/appium/settings
2021-11-23 19:01:44:843 [HTTP] {"settings":{"allowInvisibleElements":true}}
2021-11-23 19:01:44:848 [W3C (ec465b19)] Calling AppiumDriver.updateSettings() with args: [{"allowInvisibleElements":true},"ec465b19-14fb-4be5-9391-e574a2858a3d"]
2021-11-23 19:01:44:848 [UiAutomator2] Forwarding the following settings to the UiAutomator2 server: ["allowInvisibleElements"]
2021-11-23 19:01:44:849 [WD Proxy] Matched '/appium/settings' to command name 'updateSettings'
2021-11-23 19:01:44:849 [WD Proxy] Proxying [POST /appium/settings] to [POST http://127.0.0.1:8223/wd/hub/session/4bef3bba-c940-46fb-b794-b1facb6669e6/appium/settings] with body: {"settings":{"allowInvisibleElements":true}}
2021-11-23 19:01:44:875 [WD Proxy] Got response with status 200: {"sessionId":"4bef3bba-c940-46fb-b794-b1facb6669e6","value":null}
2021-11-23 19:01:44:875 [W3C (ec465b19)] Responding to client with driver.updateSettings() result: null
2021-11-23 19:01:44:876 [HTTP] <-- POST /wd/hub/session/ec465b19-14fb-4be5-9391-e574a2858a3d/appium/settings 200 33 ms - 14
2021-11-23 19:01:44:876 [HTTP] 
2021-11-23 19:01:44:888 [HTTP] --> POST /wd/hub/session/ec465b19-14fb-4be5-9391-e574a2858a3d/timeouts
2021-11-23 19:01:44:888 [HTTP] {"implicit":10000}
2021-11-23 19:01:44:889 [W3C (ec465b19)] Calling AppiumDriver.timeouts() with args: [null,null,null,null,10000,"ec465b19-14fb-4be5-9391-e574a2858a3d"]
2021-11-23 19:01:44:889 [BaseDriver] W3C timeout argument: {"implicit":10000}}
2021-11-23 19:01:44:889 [BaseDriver] Set implicit wait to 10000ms
2021-11-23 19:01:44:889 [W3C (ec465b19)] Responding to client with driver.timeouts() result: null
2021-11-23 19:01:44:890 [HTTP] <-- POST /wd/hub/session/ec465b19-14fb-4be5-9391-e574a2858a3d/timeouts 200 1 ms - 14
2021-11-23 19:01:44:890 [HTTP] 
2021-11-23 19:05:55:715 [HTTP] --> POST /wd/hub/session/40894110-f0e1-4aad-9e2a-9373dd18501d/appium/device/press_keycode
2021-11-23 19:05:55:715 [HTTP] {"keycode":3}
**2021-11-23 19:05:55:715 [W3C (40894110)] Calling AppiumDriver.pressKeyCode() with args: [3,null,null,null,null,"40894110-f0e1-4aad-9e2a-9373dd18501d"]
2021-11-23 19:05:55:729 [W3C (40894110)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: 'POST /appium/device/press_keycode' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
2021-11-23 19:05:55:729 [W3C (40894110)]     at UIA2Proxy.command (C:\Users\autotestuser\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:275:13)
2021-11-23 19:05:55:729 [W3C (40894110)]     at runMicrotasks (<anonymous>)
2021-11-23 19:05:55:729 [W3C (40894110)]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
2021-11-23 19:05:55:729 [W3C (40894110)]     at AndroidUiautomator2Driver.commands.pressKeyCode (C:\Users\autotestuser\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\commands\actions.js:6:10)
2021-11-23 19:05:55:730 [HTTP] <-- POST /wd/hub/session/40894110-f0e1-4aad-9e2a-9373dd18501d/appium/device/press_keycode 500 15 ms - 1143
2021-11-23 19:05:55:730 [HTTP]**

**Comment by WuXiaoJun111** [comment]
[logcat-presskeyCode.txt](https://github.com/appium/appium/files/7587344/logcat-presskeyCode.txt)

**Comment by mykola-mokhnach** [comment]
Unfortunately I don't observe any explicit errors in the attached logcat.

**Comment by mykola-mokhnach** [comment]
Maybe there is some connectivity issue happening during that long pause between commands:

> 2021-11-23 19:01:44:890 [HTTP] <-- POST /wd/hub/session/ec465b19-14fb-4be5-9391-e574a2858a3d/timeouts 200 1 ms - 14
> 2021-11-23 19:01:44:890 [HTTP]
> 2021-11-23 19:05:55:715 [HTTP] --> POST /wd/hub/session/40894110-f0e1-4aad-9e2a-9373dd18501d/appium/device/press_keycode

**Comment by WuXiaoJun111** [comment]
> Maybe there is some connectivity issue happening during that long pause between commands

Thank you for your answer. 
Is the connection problem caused by the device, appium, or network instability？
Is there a way to retry when this happens？

**Comment by KazuCocoa** [comment]
Do you have more logs related to https://github.com/appium/appium/issues/16152#issuecomment-976387741 and full appium server log?
I was not able to track all of logs related to `ec465b19-14fb-4be5-9391-e574a2858a3d` session since the logcat was probably ended a bit before than the session end.

Instead, I found a similar situation in the logcat. The below is it.

After calling `appium/settings`, it seems appium did cleanup https://github.com/appium/appium-uiautomator2-driver/blob/7b89e509e44941f9c1a2e3b1fcab453aae7e7f99/lib/uiautomator2.js#L304 like the below.
I wonder your appium server got SIGINT signal or another new session request was started https://github.com/appium/appium-uiautomator2-driver/blob/7b89e509e44941f9c1a2e3b1fcab453aae7e7f99/lib/uiautomator2.js#L205 
No appium debug log around `cleanupAutomationLeftovers` steps in the session's appium log, I guess another appium instance did the cleanup to the device. It means on your environment, two appium server instances tried to handle the same device. It caused this situation. (A session wanted to keep the session, but the other killed it to start a session)

```
11-23 18:51:15.828 I/appium  (12784): Get window size of the device
11-23 18:51:15.836 I/appium  (12784): AppiumResponse: {"sessionId":"a7ae5c36-5cf4-4250-af6f-d6ab3dc47912","value":{"height":560,"width":1024}}
11-23 18:51:15.863 I/appium  (12784): channel read: POST /wd/hub/session/a7ae5c36-5cf4-4250-af6f-d6ab3dc47912/appium/settings
11-23 18:51:15.866 I/appium  (12784): UpdateSettings command
11-23 18:51:15.874 I/appium  (12784): AppiumResponse: {"sessionId":"a7ae5c36-5cf4-4250-af6f-d6ab3dc47912","value":null}
11-23 18:51:16.699 I/BnrServ:( 3730):   update mPrintTimeText clear
...
11-23 19:00:54.564 D/ActivityManager( 2802): false
11-23 19:00:54.566 I/SdkServ ( 3836): CMN:SYS:checkLocks
11-23 19:00:54.567 I/SdkServ ( 3836): CMN:SRV:onStartCommand
11-23 19:00:55.322 E/global  ( 4680): InetAddressUtils.java lookupHostByName() - String Address from Method as : gw.machine.address
11-23 19:00:55.328 E/global  ( 4680): Inet6Address.java lookupHostByName() ip=/fd00::226:73ff:fe0c:d60f len=1
11-23 19:00:55.328 E/global  ( 4680): Inet6Address.java lookupHostByName() family=10
11-23 19:00:55.328 E/global  ( 4680): Inet6Address.java lookupHostByName() address=0
11-23 19:00:55.328 E/global  ( 4680): InetAddress.java lookupHostByName() save cache
11-23 19:00:56.930 I/appium  (12784): channel read: GET /wd/hub/sessions
11-23 19:00:56.931 I/appium  (12784): GetSessions command
11-23 19:00:56.943 I/appium  (12784): AppiumResponse: {"sessionId":"None","value":[{"capabilities":{"allowInvisibleElements":true,"uiautomator2ServerInstallTimeout":120000.0,"deviceName":"165.96.211.79:49110","platform":"LINUX","ignoreUnimportantViews":false,"deviceUDID":"165.96.211.79:49110","desired":{"platformName":"android","uiautomator2ServerInsta…
11-23 19:00:56.961 I/appium  (12784): channel read: DELETE /wd/hub/session/undefined
11-23 19:00:56.962 I/appium  (12784): DeleteSession command
11-23 19:00:56.964 I/PowerManagerService( 2802): Going to sleep due to timeout (uid 1000)...
11-23 19:00:56.964 I/PowerManagerService( 2802): ignore goToSleep
11-23 19:00:56.965 I/appium  (12784): Stopping uiautomator2 io.appium.uiautomator2.http io.appium.uiautomator2.server
11-23 19:00:56.967 I/LegacyUIocsx( 2706): [MN][1,0,0,1637568542.504,0,0,0,0x0,6,0x0,0,0,0,1,0]
11-23 19:00:56.976 I/appium  (12784): AppiumResponse: {"sessionId":"undefined","value":null}
11-23 19:00:57.298 I/PowerManagerService( 2802): Going to sleep due to timeout (uid 1000)...
11-23 19:00:57.298 I/PowerManagerService( 2802): ignore goToSleep
```

**Comment by WuXiaoJun111** [comment]
> Do you have more logs related to [#16152 (comment)](https://github.com/appium/appium/issues/16152#issuecomment-976387741) and full appium server log? I was not able to track all of logs related to `ec465b19-14fb-4be5-9391-e574a2858a3d` session since the logcat was probably ended a bit before than the session end.
> 
> Instead, I found a similar situation in the logcat. The below is it.
> 
> After calling `appium/settings`, it seems appium did cleanup https://github.com/appium/appium-uiautomator2-driver/blob/7b89e509e44941f9c1a2e3b1fcab453aae7e7f99/lib/uiautomator2.js#L304 like the below. I wonder your appium server got SIGINT signal or another new session request was started https://github.com/appium/appium-uiautomator2-driver/blob/7b89e509e44941f9c1a2e3b1fcab453aae7e7f99/lib/uiautomator2.js#L205 No appium debug log around `cleanupAutomationLeftovers` steps in the session's appium log, I guess another appium instance did the cleanup to the device. It means on your environment, two appium server instances tried to handle the same device. It caused this situation. (A session wanted to keep the session, but the other killed it to start a session)
> 
> ```
> 11-23 18:51:15.828 I/appium  (12784): Get window size of the device
> 11-23 18:51:15.836 I/appium  (12784): AppiumResponse: {"sessionId":"a7ae5c36-5cf4-4250-af6f-d6ab3dc47912","value":{"height":560,"width":1024}}
> 11-23 18:51:15.863 I/appium  (12784): channel read: POST /wd/hub/session/a7ae5c36-5cf4-4250-af6f-d6ab3dc47912/appium/settings
> 11-23 18:51:15.866 I/appium  (12784): UpdateSettings command
> 11-23 18:51:15.874 I/appium  (12784): AppiumResponse: {"sessionId":"a7ae5c36-5cf4-4250-af6f-d6ab3dc47912","value":null}
> 11-23 18:51:16.699 I/BnrServ:( 3730):   update mPrintTimeText clear
> ...
> 11-23 19:00:54.564 D/ActivityManager( 2802): false
> 11-23 19:00:54.566 I/SdkServ ( 3836): CMN:SYS:checkLocks
> 11-23 19:00:54.567 I/SdkServ ( 3836): CMN:SRV:onStartCommand
> 11-23 19:00:55.322 E/global  ( 4680): InetAddressUtils.java lookupHostByName() - String Address from Method as : gw.machine.address
> 11-23 19:00:55.328 E/global  ( 4680): Inet6Address.java lookupHostByName() ip=/fd00::226:73ff:fe0c:d60f len=1
> 11-23 19:00:55.328 E/global  ( 4680): Inet6Address.java lookupHostByName() family=10
> 11-23 19:00:55.328 E/global  ( 4680): Inet6Address.java lookupHostByName() address=0
> 11-23 19:00:55.328 E/global  ( 4680): InetAddress.java lookupHostByName() save cache
> 11-23 19:00:56.930 I/appium  (12784): channel read: GET /wd/hub/sessions
> 11-23 19:00:56.931 I/appium  (12784): GetSessions command
> 11-23 19:00:56.943 I/appium  (12784): AppiumResponse: {"sessionId":"None","value":[{"capabilities":{"allowInvisibleElements":true,"uiautomator2ServerInstallTimeout":120000.0,"deviceName":"165.96.211.79:49110","platform":"LINUX","ignoreUnimportantViews":false,"deviceUDID":"165.96.211.79:49110","desired":{"platformName":"android","uiautomator2ServerInsta…
> 11-23 19:00:56.961 I/appium  (12784): channel read: DELETE /wd/hub/session/undefined
> 11-23 19:00:56.962 I/appium  (12784): DeleteSession command
> 11-23 19:00:56.964 I/PowerManagerService( 2802): Going to sleep due to timeout (uid 1000)...
> 11-23 19:00:56.964 I/PowerManagerService( 2802): ignore goToSleep
> 11-23 19:00:56.965 I/appium  (12784): Stopping uiautomator2 io.appium.uiautomator2.http io.appium.uiautomator2.server
> 11-23 19:00:56.967 I/LegacyUIocsx( 2706): [MN][1,0,0,1637568542.504,0,0,0,0x0,6,0x0,0,0,0,1,0]
> 11-23 19:00:56.976 I/appium  (12784): AppiumResponse: {"sessionId":"undefined","value":null}
> 11-23 19:00:57.298 I/PowerManagerService( 2802): Going to sleep due to timeout (uid 1000)...
> 11-23 19:00:57.298 I/PowerManagerService( 2802): ignore goToSleep
> ```

Thank you for answer. this is full appium log
[appium_CheetahCase_LS_01LS_ScanLS_all_No36-20211123070556782.log](https://github.com/appium/appium/files/7592370/appium_CheetahCase_LS_01LS_ScanLS_all_No36-20211123070556782.log)

**Comment by KazuCocoa** [comment]
Thanks. The appium log did not have relevant logs as `cleanupAutomationLeftovers`.
Did another session by another appium instance try to establish a new session to the same device? According to the device log, I only got this possibility.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
