### ISSUE TITLE
open_notification says 'Method has not yet been implemented'

### ISSUE THREAD

**Issue by poobalanc** [appium/appium#16161]
## The problem

open_notification says 'Method has not yet been implemented'

## Environment

*Appium Desktop version: 1.17.0
*Appium python client version 1.2.0
* Appium version (or git revision) that exhibits the issue: 
* Last Appium version that did not exhibit the issue (if applicable): it never worked
* Desktop OS/version used to run Appium: Mac OS - 11.5.2
* Node.js version (unless using Appium.app|exe): 14.3.0, app
* Npm or Yarn package manager:
* Mobile platform/version under test: iOS 14.7.1
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: Appium.app

## Details
I am trying to automate my app which throws notification, so i want to verify whether notification thrown and details are correct.

## Link to Appium logs

Traceback (most recent call last):
  File "/Users/poobalan.chitravel/ios-pulse-python/pcpTest.py", line 18, in <module>
    httpixel.open_notifications()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/appium/webdriver/extensions/android/common.py", line 54, in open_notifications
    self.execute(Command.OPEN_NOTIFICATIONS, {})
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 323, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/appium/webdriver/errorhandler.py", line 31, in check_response
    raise wde
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/appium/webdriver/errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Method has not yet been implemented

## Code To Reproduce Issue [ Good To Have ]
desired_caps_httpixel = {}
desired_caps_httpixel['platformName'] = platformName
desired_caps_httpixel['platformVersion'] = platformVersion
desired_caps_httpixel['deviceName'] = deviceName
desired_caps_httpixel['automationName'] = 'xcuitest'
desired_caps_httpixel['udid'] = udid
desired_caps_httpixel['app'] = 'com.taskalia.httpixel'
httpixel = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps_httpixel)

httpixel.open_notifications()

**Comment by mykola-mokhnach** [comment]
This is expected. This method only works in Android.

**Comment by poobalanc** [comment]
Thank you so much for the prompt response.
could you please guide me the alternate ways to do the same on iOS?
your help is very much appreciated.
Thanks,
Poobalan.

**Comment by mykola-mokhnach** [comment]
unfortunately Apple does not provide any "shortcut" APIs to do such action. You could use Appium forum though to ask questions.
