### ISSUE TITLE
UIAutomator2 is using appium-android-driver instead of appium-uiautomator2-driver

### ISSUE THREAD

**Issue by emilioDuarte** [appium/appium#16213]
## The problem

I have specified in the desired capabilities to use the automationName: UIAutomator2, however, I ran in several issues and saw that the driver that was used is appium-android-driver.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOS Big Sur 11.6
* Node.js version (unless using Appium.app|exe): v16.13.1
* Npm or Yarn package manager: YARN
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real Device and Emulator
* Appium CLI or Appium.app|exe: Appium CLI

## Details

I was trying to perform an action over an element. isClickable() using WebDriverIO. However, I found that it was not possible to perform the action since there was an error saying: Method not implemented at 
at AndroidUiautomator2Driver.execute (/Users/emilio.duarte/Documents/QuadPay/mobile-app-auto-tests/node_modules/appium/node_modules/appium-android-driver/lib/commands/execute.js:14:11)
![image](https://user-images.githubusercontent.com/94387063/144900091-ebdfd9c4-e43b-4976-a023-6ec61e904942.png)

I supposed that it's because is using appium-android-driver instead of appium-uiautomator2-driver, even if I specified it on my desired capabilities:
config.capabilities = [
    {
        platformName: 'Android',
        automationName: 'UiAutomator2',
        deviceName: 'Pixel_3',
        platformVersion: '',
        maxInstances: 1,
        appWaitActivity: '*',
        app: join(process.cwd(), './apps/myApp.apk'),
        noReset: true,
        newCommandTimeout: 240

    },
];

I have logged an issue in WDIO. but they said that is not an issue of the framework more like is an issue from appium:
https://github.com/webdriverio/webdriverio/issues/7773

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Could you please attach the full server log?

**Comment by emilioDuarte** [comment]
Not sure if this is the log you are looking for 

script: 'return (function isElementClickable(elem) {\n' +
[0-0]     '    if (!elem.getBoundingClientRect || !elem.scrollIntoView || !elem.contains || !elem.getClientRects || !document.elementFromPoint) {\n' +
[0-0]     '        return false;\n' +
[0-0]     '    }\n' +
[0-0]     '    // Edge before switching to Chromium\n' +
[0-0]     '    const isOldEdge = !!window.StyleMedia;\n' +
[0-0]     '    // returns true for Chrome and Firefox and false for Safari, Edge and IE\n' +
[0-0]     '    const scrollIntoViewFullSupport = !(window.safari || isOldEdge);\n' +
[0-0]     '    // get overlapping element\n' +
[0-0]     '    function getOverlappingElement(elem, context) {\n' +
[0-0]     '        context = context || document;\n' +
[0-0]     '        const elemDimension = elem.getBoundingClientRect();\n' +
[0-0]     '        const x = elemDimension.left + (elem.clientWidth / 2);\n' +
[0-0]     '        const y = elemDimension.top + (elem.clientHeight / 2);\n' +
[0-0]     '        return context.elementFromPoint(x, y);\n' +
[0-0]     '    }\n' +
[0-0]     '    // get overlapping element rects (currently only the first)\n' +
[0-0]     "    // applicable if element's text is multiline.\n" +
[0-0]     '    function getOverlappingRects(elem, context) {\n' +
[0-0]     '        context = context || document;\n' +
[0-0]     '        const elems = [];\n' +
[0-0]     '        const rects = elem.getClientRects();\n' +
[0-0]     "        // webdriver clicks on center of the first element's rect (line of text), it might change in future\n" +
[0-0]     '        const rect = rects[0];\n' +
[0-0]     '        const x = rect.left + (rect.width / 2);\n' +
[0-0]     '        const y = rect.top + (rect.height / 2);\n' +
[0-0]     '        elems.push(context.elementFromPoint(x, y));\n' +
[0-0]     '        return elems;\n' +
[0-0]     '    }\n' +
[0-0]     '    // get overlapping elements\n' +
[0-0]     '    function getOverlappingElements(elem, context) {\n' +
[0-0]     '        return [getOverlappingElement(elem, context)].concat(getOverlappingRects(elem, context));\n' +
[0-0]     '    }\n' +
[0-0]     '    // is a node a descendant of a given node\n' +
[0-0]     '    function nodeContains(elem, otherNode) {\n' +
[0-0]     "        // Edge doesn't support neither Shadow Dom nor contains if ShadowRoot polyfill is used\n" +
[0-0]     '        if (isOldEdge) {\n' +
[0-0]     '            let tmpElement = otherNode;\n' +
[0-0]     '            while (tmpElement) {\n' +
[0-0]     '                if (tmpElement === elem) {\n' +
[0-0]     '                    return true;\n' +
[0-0]     '                }\n' +
[0-0]     '                tmpElement = tmpElement.parentNode;\n' +
[0-0]     '                // DocumentFragment / ShadowRoot polyfill like ShadyRoot\n' +
[0-0]     '                if (tmpElement && tmpElement.nodeType === 11 && tmpElement.host) {\n' +
[0-0]     '                    tmpElement = tmpElement.host;\n' +
[0-0]     '                }\n' +
[0-0]     '            }\n' +
[0-0]     '            return false;\n' +
[0-0]     '        }\n' +
[0-0]     '        return elem.contains(otherNode);\n' +
[0-0]     '    }\n' +
[0-0]     '    // is one of overlapping elements the `elem` or one of its child\n' +
[0-0]     '    function isOverlappingElementMatch(elementsFromPoint, elem) {\n' +
[0-0]     '        if (elementsFromPoint.some(function (elementFromPoint) {\n' +
[0-0]     '            return elementFromPoint === elem || nodeContains(elem, elementFromPoint);\n' +
[0-0]     '        })) {\n' +
[0-0]     '            return true;\n' +
[0-0]     '        }\n' +
[0-0]     '        // shadow root\n' +
[0-0]     '        // filter unique elements with shadowRoot\n' +
[0-0]     '        // @ts-ignore\n' +
[0-0]     '        let elemsWithShadowRoot = [].concat(elementsFromPoint);\n' +
[0-0]     '        elemsWithShadowRoot = elemsWithShadowRoot.filter(function (x) {\n' +
[0-0]     '            return x && x.shadowRoot && x.shadowRoot.elementFromPoint;\n' +
[0-0]     '        });\n' +
[0-0]     '        // getOverlappingElements of every element with shadowRoot\n' +
[0-0]     '        let shadowElementsFromPoint = [];\n' +
[0-0]     '        for (let i = 0; i < elemsWithShadowRoot.length; ++i) {\n' +
[0-0]     '            let shadowElement = elemsWithShadowRoot[i];\n' +
[0-0]     '            shadowElementsFromPoint = shadowElementsFromPoint.concat(getOverlappingElements(elem, shadowElement.shadowRoot));\n' +
[0-0]     '        }\n' +
[0-0]     '        // remove duplicates and parents\n' +
[0-0]     '        // @ts-ignore\n' +
[0-0]     '        shadowElementsFromPoint = [].concat(shadowElementsFromPoint);\n' +
[0-0]     '        shadowElementsFromPoint = shadowElementsFromPoint.filter(function (x) {\n' +
[0-0]     '            return !elementsFromPoint.includes(x);\n' +
[0-0]     '        });\n' +
[0-0]     '        if (shadowElementsFromPoint.length === 0) {\n' +
[0-0]     '            return false;\n' +
[0-0]     '        }\n' +
[0-0]     '        return isOverlappingElementMatch(shadowElementsFromPoint, elem);\n' +
[0-0]     '    }\n' +
[0-0]     '    // copied from `isElementInViewport.js`\n' +
[0-0]     '    function isElementInViewport(elem) {\n' +
[0-0]     '        if (!elem.getBoundingClientRect) {\n' +
[0-0]     '            return false;\n' +
[0-0]     '        }\n' +
[0-0]     '        const rect = elem.getBoundingClientRect();\n' +
[0-0]     '        const windowHeight = (window.innerHeight || document.documentElement.clientHeight);\n' +
[0-0]     '        const windowWidth = (window.innerWidth || document.documentElement.clientWidth);\n' +
[0-0]     '        const vertInView = (rect.top <= windowHeight) && ((rect.top + rect.height) > 0);\n' +
[0-0]     '        const horInView = (rect.left <= windowWidth) && ((rect.left + rect.width) > 0);\n' +
[0-0]     '        return (vertInView && horInView);\n' +
[0-0]     '    }\n' +
[0-0]     '    function isClickable(elem) {\n' +
[0-0]     '        return (isElementInViewport(elem) && elem.disabled !== true &&\n' +
[0-0]     '            isOverlappingElementMatch(getOverlappingElements(elem), elem));\n' +
[0-0]     '    }\n' +
[0-0]     "    // scroll to the element if it's not clickable\n" +
[0-0]     '    if (!isClickable(elem)) {\n' +
[0-0]     '        // works well in dialogs, but the element may be still overlapped by some sticky header/footer\n' +
[0-0]     "        elem.scrollIntoView(scrollIntoViewFullSupport ? { block: 'nearest', inline: 'nearest' } : false);\n" +
[0-0]     '        // if element is still not clickable take another scroll attempt\n' +
[0-0]     '        if (!isClickable(elem)) {\n' +
[0-0]     '            // scroll to element, try put it in the screen center.\n' +
[0-0]     '            // Should definitely work even if element was covered with sticky header/footer\n' +
[0-0]     "            elem.scrollIntoView(scrollIntoViewFullSupport ? { block: 'center', inline: 'center' } : true);\n" +
[0-0]     '            return isClickable(elem);\n' +
[0-0]     '        }\n' +
[0-0]     '    }\n' +
[0-0]     '    return true;\n' +
[0-0]     '}).apply(null, arguments)',
[0-0]   args: [
[0-0]     {
[0-0]       'element-6066-11e4-a52e-4f735466cecf': '00000000-0000-04bf-ffff-ffff00000021',
[0-0]       ELEMENT: '00000000-0000-04bf-ffff-ffff00000021'
[0-0]     }
[0-0]   ]
[0-0] }

**Comment by emilioDuarte** [comment]
NotImplementedError: Method is not implemented
    at AndroidUiautomator2Driver.execute (/Users/emilio.duarte/Documents/QuadPay/quadpay-mobile-app/node_modules/appium-android-driver/lib/commands/execute.js:14:11)
    at commandExecutor (/Users/emilio.duarte/Documents/QuadPay/quadpay-mobile-app/node_modules/appium-base-driver/lib/basedriver/driver.js:335:9)
    at /Users/emilio.duarte/Documents/QuadPay/quadpay-mobile-app/node_modules/async-lock/lib/index.js:146:12
    at AsyncLock._promiseTry (/Users/emilio.duarte/Documents/QuadPay/quadpay-mobile-app/node_modules/async-lock/lib/index.js:280:31)
    at exec (/Users/emilio.duarte/Documents/QuadPay/quadpay-mobile-app/node_modules/async-lock/lib/index.js:145:9)
    at AsyncLock.acquire (/Users/emilio.duarte/Documents/QuadPay/quadpay-mobile-app/node_modules/async-lock/lib/index.js:162:3)
    at AndroidUiautomator2Driver.executeCommand (/Users/emilio.duarte/Documents/QuadPay/quadpay-mobile-app/node_modules/appium-base-driver/lib/basedriver/driver.js:348:39)
    at AppiumDriver.executeCommand (/Users/emilio.duarte/Documents/QuadPay/quadpay-mobile-app/node_modules/appium/lib/appium.js:563:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at asyncHandler (/Users/emilio.duarte/Documents/QuadPay/quadpay-mobile-app/node_modules/appium-base-driver/lib/protocol/protocol.js:297:21)

**Comment by mykola-mokhnach** [comment]
It is only the stack trace. We need the full log though

**Comment by emilioDuarte** [comment]
[wdio-appium.log](https://github.com/appium/appium/files/7669909/wdio-appium.log)

**Comment by mykola-mokhnach** [comment]
> [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/session/bc879cc7-f1e1-4b47-86a2-118fb0e11e82/execute/sync[39m
> [35m[HTTP][39m [90m{"script":"return (function isElementClickable(elem) {\n    if (!elem.getBoundingClientRect || !elem.scrollIntoView || !elem.contains || !elem.getClientRects || !document.elementFromPoint) {\n        return false;\n    }\n    // Edge before switching to Chromium\n    const isOldEdge = !!window.StyleMedia;\n    // returns true for Chrome and Firefox and false for Safari, Edge and IE\n    const scrollIntoViewFullSupport = !(window.safari || isOldEdge);\n    // get overlapping element\n    function getOverlappingElement(elem, context) {\n        context = context || document;\n        const elemDimension = elem.getBoundingClientRect();\n        const x = elemDimension.left + (elem.clientWidth / 2);\n        const y = elemDimension.top + (elem.clientHeight / 2);\n        return context.elementFromPoint(x, y);\n    }\n    // get overlapping element rects (currently only the first)\n    // applicable if element's text is multiline.\n    function getOverlappingRects(elem, context) {\n        context = context || ...[39m
> [debug] [35m[W3C (bc879cc7)][39m Calling AppiumDriver.execute() with args: ["return (function isElementClickable(elem) {\n    if (!elem.getBoundingClientRect || !elem.scrollIntoView || !elem.contains || !elem.getClientRects || !document.elementFromPoint) {\n        return false;\n    }\n    // Edge before switching to Chromium\n    const isOldEdge = !!window.StyleMedia;\n    // returns true for Chrome and Firefox and false for Safari, Edge and IE\n    const scrollIntoViewFullSupport = !(window.safari || isOldEdge);\n    // get overlapping element\n    function getOverlappingElement(elem, context) {\n        context = context || document;\n        const elemDimension = elem.getBoundingClientRect();\n        const x = elemDimension.left + (elem.clientWidth / 2);\n        const y = elemDimension.top + (elem.clientHeight / 2);\n        return context.elementFromPoint(x, y);\n    }\n    // get overlapping element rects (currently only the first)\n    // applicable if element's text is multiline.\n    function getOverlappingRects(elem, context) {\n        context = context || document;...
> [debug] [35m[W3C (bc879cc7)][39m Encountered internal error running command: NotImplementedError: Method is not implemented
> [debug] [35m[W3C (bc879cc7)][39m     at AndroidUiautomator2Driver.execute (/Users/emilio.duarte/Documents/QuadPay/mobile-app-auto-tests/node_modules/appium/node_modules/appium-android-driver/lib/commands/execute.js:14:11)
> [debug] [35m[W3C (bc879cc7)][39m     at commandExecutor (/Users/emilio.duarte/Documents/QuadPay/mobile-app-auto-tests/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:335:9)
> [debug] [35m[W3C (bc879cc7)][39m     at /Users/emilio.duarte/Documents/QuadPay/mobile-app-auto-tests/node_modules/appium/node_modules/async-lock/lib/index.js:146:12
> [debug] [35m[W3C (bc879cc7)][39m     at AsyncLock._promiseTry (/Users/emilio.duarte/Documents/QuadPay/mobile-app-auto-tests/node_modules/appium/node_modules/async-lock/lib/index.js:280:31)
> [debug] [35m[W3C (bc879cc7)][39m     at exec (/Users/emilio.duarte/Documents/QuadPay/mobile-app-auto-tests/node_modules/appium/node_modules/async-lock/lib/index.js:145:9)
> [debug] [35m[W3C (bc879cc7)][39m     at AsyncLock.acquire (/Users/emilio.duarte/Documents/QuadPay/mobile-app-auto-tests/node_modules/appium/node_modules/async-lock/lib/index.js:162:3)
> [debug] [35m[W3C (bc879cc7)][39m     at AndroidUiautomator2Driver.executeCommand (/Users/emilio.duarte/Documents/QuadPay/mobile-app-auto-tests/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:348:39)
> [debug] [35m[W3C (bc879cc7)][39m     at AppiumDriver.executeCommand (/Users/emilio.duarte/Documents/QuadPay/mobile-app-auto-tests/node_modules/appium/lib/appium.js:563:36)
> [debug] [35m[W3C (bc879cc7)][39m     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> [debug] [35m[W3C (bc879cc7)][39m     at asyncHandler (/Users/emilio.duarte/Documents/QuadPay/mobile-app-auto-tests/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:297:21)
> [35m[HTTP][39m [37m<-- POST /session/bc879cc7-f1e1-4b47-86a2-118fb0e11e82/execute/sync [39m[33m405[39m [90m49 ms - 1656[39m

WDIO sends a javascript snippet for isClickable check, so that expectedly fails (it probably still assumes we are running a browser rather than a native mobile device). As a possible workaround try to check the [clickable](https://github.com/appium/appium-uiautomator2-driver#element-attributes) element attribute

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
