### ISSUE TITLE
'getAlertText' command executed but there is no alert  while trying to run 'getPageSource' script in webcontext

### ISSUE THREAD

**Issue by billychen2014** [appium/appium#16222]
### Discussed in https://github.com/appium/appium/discussions/16218

<div type='discussions-op-text'>

<sup>Originally posted by **billychen2014** December  7, 2021</sup>
hello ,
story is this:

1. enable "autoWebview" in caps
2. execute js at page A (this will let app turn into page B)
3. wait 3 seconds [i want the page_source change to page B's]
4. excute another js

result: i wait a long long time till time out 
consult two questions:

1. from the server logs below ,i found one weird logs(marked as bold), hmm, why there are some logs about alert (the page B don't have alert popup).
2. is there one flag to indicate  that  Page B page source  re-load successfully ? i just set time.sleep() which looks like not a good solution
 

2021-12-07 11:19:42:295 - [debug] [W3C (3ba053cc)] Calling AppiumDriver.getPageSource() with args: ["3ba053cc-18f9-424d-ad39-6a481247fa86"]
2021-12-07 11:19:42:295 - [debug] [XCUITest] Executing command 'getPageSource'
2021-12-07 11:19:42:296 - [debug] [RemoteDebugger] Executing atom 'execute_script' with 'args=["return document.documentElement.outerHTML",[]]; frames='
2021-12-07 11:19:42:296 - [debug] [RemoteDebugger] Executing 'execute_script' atom in default context
2021-12-07 11:19:42:296 - [debug] [RemoteDebugger] Sending javascript command: '(function(){return function(){var f=this;
2021-12-07 11:19:42:296 - [debug] [RemoteDebugger] funct...'
**2021-12-07 11:19:42:296 - [debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:36158', page '15', target 'page-64' (id: 64): 'Runtime.evaluate'
2021-12-07 11:19:42:708 - [debug] [WD Proxy] Matched '/alert/text' to command name 'getAlertText'**
2021-12-07 11:19:42:708 - [debug] [WD Proxy] Proxying [GET /alert/text] to [GET http://127.0.0.1:8100/session/FAFEE1A8-8E2D-4B33-B6CE-A8E403A4E552/alert/text] with no body
2021-12-07 11:19:42:834 - [WD Proxy] Got response with status 404: {"value":{"error":"no such alert","message":"An attempt was made to operate on a modal dialog when one was not open","traceback":""},"sessionId":"FAFEE1A8-8E2D-4B33-B6CE-A8E403A4E552"}
2021-12-07 11:19:42:835 - [debug] [W3C] Matched W3C error code 'no such alert' to NoSuchAlertError
2021-12-07 11:21:42:302 - [debug] [XCUITest] Error received while executing atom: operation timed out
2021-12-07 11:21:42:303 - [debug] [XCUITest] No alert found: Did not get any response for atom execution after 120004ms
2021-12-07 11:21:42:305 - [debug] [W3C (3ba053cc)] Encountered internal error running command: Error: Did not get any response for atom execution after 120004ms
2021-12-07 11:21:42:305 - [debug] [W3C (3ba053cc)]     at /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/web.js:283:15
2021-12-07 11:21:42:305 - [debug] [W3C (3ba053cc)]     at tryCatcher (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/release/util.js:16:23)
2021-12-07 11:21:42:305 - [debug] [W3C (3ba053cc)]     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/release/promise.js:547:31)
2021-12-07 11:21:42:307 - [debug] [W3C (3ba053cc)]     at Promise._settlePromise (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/release/promise.js:604:18)
2021-12-07 11:21:42:307 - [debug] [W3C (3ba053cc)]     at Promise._settlePromise0 (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/release/promise.js:649:10)
2021-12-07 11:21:42:307 - [debug] [W3C (3ba053cc)]     at Promise._settlePromises (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/release/promise.js:725:18)
2021-12-07 11:21:42:308 - [debug] [W3C (3ba053cc)]     at _drainQueueStep (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/release/async.js:93:12)
2021-12-07 11:21:42:308 - [debug] [W3C (3ba053cc)]     at _drainQueue (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/release/async.js:86:9)
2021-12-07 11:21:42:308 - [debug] [W3C (3ba053cc)]     at Async._drainQueues (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/release/async.js:102:5)
2021-12-07 11:21:42:308 - [debug] [W3C (3ba053cc)]     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/release/async.js:15:14)
2021-12-07 11:21:42:308 - [debug] [W3C (3ba053cc)]     at processImmediate (internal/timers.js:464:21)
2021-12-07 11:21:42:310 - [HTTP] <-- GET /wd/hub/session/3ba053cc-18f9-424d-ad39-6a481247fa86/source 500 120012 ms - 613

details ENV:
server: Appium v1.21.0
app: iOS hybird app
iOS OS version: 13.6
lan : python

</div>

**Comment by billychen2014** [comment]
comes from discussion , maybe one potential problem.

**Comment by mykola-mokhnach** [comment]
I saw timeouts happening when trying to perform an operation on a page that did not finished loading. Try to make sure the readyState of the page is ok before requesting its source. The log above seems to be ok though

**Comment by billychen2014** [comment]
hello, i modified the title ,maybe that's more clear for this issue

**Comment by mykola-mokhnach** [comment]
The alert checking behaviour is expected. The logic is to wait for an atom to complete for maximum one second. If the completion takes more than that then execute an alert checking loop to verify if there is a native alert which covers the view and preventing the atom from being completed. If there is an alert then an error will be thrown otherwise the loop continues until a timeout is reached and the above error is thrown.

**Comment by billychen2014** [comment]
close it as it's correct behavior

**Comment by divi243** [comment]
how can we resolve this kind of issue? has anyone found the reason for execution to cross 1 sec?  i faced the same in my case i can see that find element tries to find the element and the element is still present and enabled  but still element is not found after waiting and throws the error as mentioned in this ticket
