### ISSUE TITLE
FindElement command timeout in mobile browser

### ISSUE THREAD

**Issue by AndreiTsialenchanka** [appium/appium#16220]
## The problem

When I run a test with steps that redirects me to the browser view I get findElement command timeout. The problem here is that I have 3 similar tests with different users and the test is failing randomly on different users. In Appium logs I see the findElement command that takes more than 240seconds. I get this error locally and in BrowserStack.

## Environment

* Appium version (or git revision) that exhibits the issue: Appium v1.22.0 creating new XCUITestDriver (v3.53.3) session
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: BrowserStack, Desktop
* Node.js version (unless using Appium.app|exe): locally: 17.0.1
* Npm or Yarn package manager: npm
* Mobile platform/version under test: IOS
* Real device or emulator/simulator: emulator locally\real on BS
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
[https://gist.github.com/AndreiTsialenchanka/dbb471c42d020fb3c73f36e97d48e8e1](url)

**Comment by mykola-mokhnach** [comment]
Where exactly the issue happens in the attached log? Is the target element present in the page source? have you tried to change element locator type (e.g. xpath->class chain)?

**Comment by AndreiTsialenchanka** [comment]
I have tried changing locator and strategies and still get this inconsistent results.
[https://gist.githubusercontent.com/AndreiTsialenchanka/dbb471c42d020fb3c73f36e97d48e8e1/raw/3c555ab17d1d67d2407b089fd36211fffbc3c474/Appium%2520logs](url)

`2021-12-07 07:56:51:485 - [HTTP] <-- POST /wd/hub/session/2e1169ef-e11e-47bd-9f4e-3042f38019b3/element 404 1061 ms - 1187
2021-12-07 07:56:51:485 - [HTTP] 
2021-12-07 07:56:52:624 - [debug] [WD Proxy] Got response with status 200: {"value":[],"sessionId":"69070FA0-222C-49CB-A14B-4B647A06DBF0"}
2021-12-07 07:56:52:625 - [debug] [W3C (2e1169ef)] Responding to client with driver.findElements() result: []
2021-12-07 07:56:52:626 - [HTTP] <-- POST /wd/hub/session/2e1169ef-e11e-47bd-9f4e-3042f38019b3/elements 200 1212 ms - 12
2021-12-07 07:56:52:626 - [HTTP] 
2021-12-07 07:56:52:714 - [HTTP] --> POST /wd/hub/session/2e1169ef-e11e-47bd-9f4e-3042f38019b3/elements
2021-12-07 07:56:52:715 - [HTTP] {"using":"xpath","value":"//XCUIElementTypeOther[@name=\"My Account\"]"}
2021-12-07 07:56:52:715 - [debug] [W3C (2e1169ef)] Calling AppiumDriver.findElements() with args: ["xpath","//XCUIElementTypeOther[@name=\"My Account\"]","2e1169ef-e11e-47bd-9f4e-3042f38019b3"]
2021-12-07 07:56:52:715 - [debug] [XCUITest] Executing command 'findElements'
2021-12-07 07:56:52:715 - [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id, css selector
2021-12-07 07:56:52:715 - [debug] [BaseDriver] Waiting up to 0 ms for condition
2021-12-07 07:56:52:716 - [debug] [WD Proxy] Matched '/elements' to command name 'findElements'
2021-12-07 07:56:52:716 - [debug] [WD Proxy] Proxying [POST /elements] to [POST http://127.0.0.1:8404/session/69070FA0-222C-49CB-A14B-4B647A06DBF0/elements] with body: {"using":"xpath","value":"//XCUIElementTypeOther[@name=\"My Account\"]"}
2021-12-07 07:57:21:689 - [HTTP] --> POST /wd/hub/session/2e1169ef-e11e-47bd-9f4e-3042f38019b3/element
2021-12-07 07:57:21:690 - [HTTP] {"using":"xpath","value":"//XCUIElementTypeOther[@name=\"My Account\"]"}
2021-12-07 07:57:21:692 - [debug] [W3C (2e1169ef)] Calling AppiumDriver.findElement() with args: ["xpath","//XCUIElementTypeOther[@name=\"My Account\"]","2e1169ef-e11e-47bd-9f4e-3042f38019b3"]
2021-12-07 07:57:21:693 - [debug] [XCUITest] Executing command 'findElement'
2021-12-07 07:58:52:854 - [HTTP] --> POST /wd/hub/session/2e1169ef-e11e-47bd-9f4e-3042f38019b3/elements
2021-12-07 07:58:52:855 - [HTTP] {"using":"xpath","value":"//XCUIElementTypeOther[@name=\"My Account\"]"}
2021-12-07 07:58:52:857 - [debug] [W3C (2e1169ef)] Calling AppiumDriver.findElements() with args: ["xpath","//XCUIElementTypeOther[@name=\"My Account\"]","2e1169ef-e11e-47bd-9f4e-3042f38019b3"]
2021-12-07 07:58:52:857 - [debug] [XCUITest] Executing command 'findElements'
2021-12-07 07:59:21:949 - [HTTP] --> POST /wd/hub/session/2e1169ef-e11e-47bd-9f4e-3042f38019b3/element
2021-12-07 07:59:21:949 - [HTTP] {"using":"xpath","value":"//XCUIElementTypeOther[@name=\"My Account\"]"}
2021-12-07 07:59:21:949 - [debug] [W3C (2e1169ef)] Calling AppiumDriver.findElement() with args: ["xpath","//XCUIElementTypeOther[@name=\"My Account\"]","2e1169ef-e11e-47bd-9f4e-3042f38019b3"]
2021-12-07 07:59:21:950 - [debug] [XCUITest] Executing command 'findElement'
2021-12-07 08:00:52:954 - [WD Proxy] Error: timeout of 240000ms exceeded
2021-12-07 08:00:52:955 - [WD Proxy]     at createError (/nix/store/v95a8w5whs53p701j706qa641j2swgdv-appium-1.22.0/node_modules/axios/lib/core/createError.js:16:15)
2021-12-07 08:00:52:955 - [WD Proxy]     at RedirectableRequest.handleRequestTimeout (/nix/store/v95a8w5whs53p701j706qa641j2swgdv-appium-1.22.0/node_modules/axios/lib/adapters/http.js:328:16)
2021-12-07 08:00:52:955 - [WD Proxy]     at RedirectableRequest.emit (events.js:315:20)
2021-12-07 08:00:52:955 - [WD Proxy]     at Timeout.<anonymous> (/nix/store/v95a8w5whs53p701j706qa641j2swgdv-appium-1.22.0/node_modules/follow-redirects/index.js:164:12)
2021-12-07 08:00:52:955 - [WD Proxy]     at listOnTimeout (internal/timers.js:554:17)
2021-12-07 08:00:52:955 - [WD Proxy]     at processTimers (internal/timers.js:497:7)
2021-12-07 08:00:52:963 - [HTTP] --> POST /wd/hub/session/2e1169ef-e11e-47bd-9f4e-3042f38019b3/elements
2021-12-07 08:00:52:964 - [HTTP] {"using":"xpath","value":"//XCUIElementTypeOther[@name=\"My Account\"]"}
2021-12-07 08:00:52:966 - [debug] [W3C (2e1169ef)] Calling AppiumDriver.findElements() with args: ["xpath","//XCUIElementTypeOther[@name=\"My Account\"]","2e1169ef-e11e-47bd-9f4e-3042f38019b3"]
2021-12-07 08:00:52:967 - [debug] [XCUITest] Executing command 'findElements'
2021-12-07 08:00:52:968 - [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id, css selector
2021-12-07 08:00:52:968 - [debug] [BaseDriver] Waiting up to 0 ms for condition
2021-12-07 08:00:52:973 - [debug] [WD Proxy] Matched '/element' to command name 'findElement'
2021-12-07 08:00:52:974 - [debug] [WD Proxy] Proxying [POST /element] to [POST http://127.0.0.1:8404/session/69070FA0-222C-49CB-A14B-4B647A06DBF0/element] with body: {"using":"xpath","value":"//XCUIElementTypeOther[@name=\"My Account\"]"}
2021-12-07 08:00:52:979 - [debug] [W3C (2e1169ef)] Responding to client with driver.findElements() result: []
2021-12-07 08:00:52:983 - [HTTP] <-- POST /wd/hub/session/2e1169ef-e11e-47bd-9f4e-3042f38019b3/elements 200 240159 ms - 12
2021-12-07 08:00:52:983 - [HTTP] 
2021-12-07 08:01:21:964 - [HTTP] --> POST /wd/hub/session/2e1169ef-e11e-47bd-9f4e-3042f38019b3/element
2021-12-07 08:01:21:965 - [HTTP] {"using":"xpath","value":"//XCUIElementTypeOther[@name=\"My Account\"]"}
2021-12-07 08:01:21:965 - [debug] [W3C (2e1169ef)] Calling AppiumDriver.findElement() with args: ["xpath","//XCUIElementTypeOther[@name=\"My Account\"]","2e1169ef-e11e-47bd-9f4e-3042f38019b3"]`

**Comment by mykola-mokhnach** [comment]
Could you please attach logs where other locator types are used?

Usually xpath locators are the least effective ones, because WDA needs to snapshot the whole app hierarchy to execute these.

If the element still cannot be found using any other locator type then we cannot do much on Appium side, since element location is fully controlled by XCTest. So it either does not present at all in the app accessibility or there is an issue in XCTest

**Comment by AndreiTsialenchanka** [comment]
I'm not sure why my gist link does not work so I paste a bit more here

`2021-12-07 07:56:51:482 - [WD Proxy] Got response with status 404: {"value":{"error":"no such element","message":"unable to find an element using 'accessibility id', value 'Done'","traceback":"(\n\t0   WebDriverAgentLib                   0x000000010249d8f4 FBNoSuchElementErrorResponseForRequest + 312\n\t1   WebDriverAgentLib                   0x000000010249d6bc +[FBFindElementCommands handleFindElement:] + 448\n\t2   WebDriverAgentLib                   0x000000010244819c -[FBRoute_TargetAction mountRequest:intoResponse:] + 208\n\t3   WebDriverAgentLib                   0x000000010242dfdc __37-[FBWebServer registerRouteHandlers:]_block_invoke + 496\n\t4   WebDriverAgentLib                   0x000000010247ebe0 -[RoutingHTTPServer handleRoute:withRequest:response:] + 240\n\t5   WebDriverAgentLib                   0x000000010247f93c __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 76\n\t6   libdispatch.dylib                   0x00000001b2199fd8 D174E751-B542-3A69-A593-7AA69CF30F23 + 12248\n\t7   libdispatch.dylib                   0x...
2021-12-07 07:56:51:482 - [debug] [W3C] Matched W3C error code 'no such element' to NoSuchElementError
2021-12-07 07:56:51:483 - [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id, css selector
2021-12-07 07:56:51:483 - [debug] [BaseDriver] Waiting up to 0 ms for condition
2021-12-07 07:56:51:483 - [debug] [WD Proxy] Matched '/elements' to command name 'findElements'
2021-12-07 07:56:51:483 - [debug] [WD Proxy] Proxying [POST /elements] to [POST http://127.0.0.1:8404/session/69070FA0-222C-49CB-A14B-4B647A06DBF0/elements] with body: {"using":"xpath","value":"//XCUIElementTypeOther[@name=\"My Account\"]"}
2021-12-07 07:56:51:484 - [debug] [W3C (2e1169ef)] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
2021-12-07 07:56:51:484 - [debug] [W3C (2e1169ef)]     at XCUITestDriver.doNativeFind (/nix/store/v95a8w5whs53p701j706qa641j2swgdv-appium-1.22.0/node_modules/appium-xcuitest-driver/lib/commands/find.js:130:11)
2021-12-07 07:56:51:484 - [debug] [W3C (2e1169ef)]     at runMicrotasks (<anonymous>)
2021-12-07 07:56:51:484 - [debug] [W3C (2e1169ef)]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
2021-12-07 07:56:51:484 - [debug] [W3C (2e1169ef)]     at XCUITestDriver.findNativeElementOrElements (/nix/store/v95a8w5whs53p701j706qa641j2swgdv-appium-1.22.0/node_modules/appium-xcuitest-driver/lib/commands/find.js:90:10)
2021-12-07 07:56:51:484 - [debug] [W3C (2e1169ef)]     at XCUITestDriver.findElOrEls (/nix/store/v95a8w5whs53p701j706qa641j2swgdv-appium-1.22.0/node_modules/appium-xcuitest-driver/lib/commands/find.js:23:12)
2021-12-07 07:56:51:484 - [debug] [W3C (2e1169ef)]     at XCUITestDriver.findElOrElsWithProcessing (/nix/store/v95a8w5whs53p701j706qa641j2swgdv-appium-1.22.0/node_modules/appium-base-driver/lib/basedriver/commands/find.js:33:12)
2021-12-07 07:56:51:484 - [debug] [W3C (2e1169ef)]     at XCUITestDriver.findElement (/nix/store/v95a8w5whs53p701j706qa641j2swgdv-appium-1.22.0/node_modules/appium-base-driver/lib/basedriver/commands/find.js:53:10)
2021-12-07 07:56:51:485 - [HTTP] <-- POST /wd/hub/session/2e1169ef-e11e-47bd-9f4e-3042f38019b3/element 404 1061 ms - 1187
2021-12-07 07:56:51:485 - [HTTP] 
2021-12-07 07:56:52:624 - [debug] [WD Proxy] Got response with status 200: {"value":[],"sessionId":"69070FA0-222C-49CB-A14B-4B647A06DBF0"}
2021-12-07 07:56:52:625 - [debug] [W3C (2e1169ef)] Responding to client with driver.findElements() result: []
2021-12-07 07:56:52:626 - [HTTP] <-- POST /wd/hub/session/2e1169ef-e11e-47bd-9f4e-3042f38019b3/elements 200 1212 ms - 12
2021-12-07 07:56:52:626 - [HTTP] 
2021-12-07 07:56:52:714 - [HTTP] --> POST /wd/hub/session/2e1169ef-e11e-47bd-9f4e-3042f38019b3/elements
2021-12-07 07:56:52:715 - [HTTP] {"using":"xpath","value":"//XCUIElementTypeOther[@name=\"My Account\"]"}
2021-12-07 07:56:52:715 - [debug] [W3C (2e1169ef)] Calling AppiumDriver.findElements() with args: ["xpath","//XCUIElementTypeOther[@name=\"My Account\"]","2e1169ef-e11e-47bd-9f4e-3042f38019b3"]
2021-12-07 07:56:52:715 - [debug] [XCUITest] Executing command 'findElements'
2021-12-07 07:56:52:715 - [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id, css selector
2021-12-07 07:56:52:715 - [debug] [BaseDriver] Waiting up to 0 ms for condition
2021-12-07 07:56:52:716 - [debug] [WD Proxy] Matched '/elements' to command name 'findElements'
2021-12-07 07:56:52:716 - [debug] [WD Proxy] Proxying [POST /elements] to [POST http://127.0.0.1:8404/session/69070FA0-222C-49CB-A14B-4B647A06DBF0/elements] with body: {"using":"xpath","value":"//XCUIElementTypeOther[@name=\"My Account\"]"}
2021-12-07 07:57:21:689 - [HTTP] --> POST /wd/hub/session/2e1169ef-e11e-47bd-9f4e-3042f38019b3/element
2021-12-07 07:57:21:690 - [HTTP] {"using":"xpath","value":"//XCUIElementTypeOther[@name=\"My Account\"]"}
2021-12-07 07:57:21:692 - [debug] [W3C (2e1169ef)] Calling AppiumDriver.findElement() with args: ["xpath","//XCUIElementTypeOther[@name=\"My Account\"]","2e1169ef-e11e-47bd-9f4e-3042f38019b3"]
2021-12-07 07:57:21:693 - [debug] [XCUITest] Executing command 'findElement'
2021-12-07 07:58:52:854 - [HTTP] --> POST /wd/hub/session/2e1169ef-e11e-47bd-9f4e-3042f38019b3/elements
2021-12-07 07:58:52:855 - [HTTP] {"using":"xpath","value":"//XCUIElementTypeOther[@name=\"My Account\"]"}
2021-12-07 07:58:52:857 - [debug] [W3C (2e1169ef)] Calling AppiumDriver.findElements() with args: ["xpath","//XCUIElementTypeOther[@name=\"My Account\"]","2e1169ef-e11e-47bd-9f4e-3042f38019b3"]
2021-12-07 07:58:52:857 - [debug] [XCUITest] Executing command 'findElements'
2021-12-07 07:59:21:949 - [HTTP] --> POST /wd/hub/session/2e1169ef-e11e-47bd-9f4e-3042f38019b3/element
2021-12-07 07:59:21:949 - [HTTP] {"using":"xpath","value":"//XCUIElementTypeOther[@name=\"My Account\"]"}
2021-12-07 07:59:21:949 - [debug] [W3C (2e1169ef)] Calling AppiumDriver.findElement() with args: ["xpath","//XCUIElementTypeOther[@name=\"My Account\"]","2e1169ef-e11e-47bd-9f4e-3042f38019b3"]
2021-12-07 07:59:21:950 - [debug] [XCUITest] Executing command 'findElement'
2021-12-07 08:00:52:954 - [WD Proxy] Error: timeout of 240000ms exceeded
2021-12-07 08:00:52:955 - [WD Proxy]     at createError (/nix/store/v95a8w5whs53p701j706qa641j2swgdv-appium-1.22.0/node_modules/axios/lib/core/createError.js:16:15)
2021-12-07 08:00:52:955 - [WD Proxy]     at RedirectableRequest.handleRequestTimeout (/nix/store/v95a8w5whs53p701j706qa641j2swgdv-appium-1.22.0/node_modules/axios/lib/adapters/http.js:328:16)
2021-12-07 08:00:52:955 - [WD Proxy]     at RedirectableRequest.emit (events.js:315:20)
2021-12-07 08:00:52:955 - [WD Proxy]     at Timeout.<anonymous> (/nix/store/v95a8w5whs53p701j706qa641j2swgdv-appium-1.22.0/node_modules/follow-redirects/index.js:164:12)
2021-12-07 08:00:52:955 - [WD Proxy]     at listOnTimeout (internal/timers.js:554:17)
2021-12-07 08:00:52:955 - [WD Proxy]     at processTimers (internal/timers.js:497:7)
2021-12-07 08:00:52:963 - [HTTP] --> POST /wd/hub/session/2e1169ef-e11e-47bd-9f4e-3042f38019b3/elements
2021-12-07 08:00:52:964 - [HTTP] {"using":"xpath","value":"//XCUIElementTypeOther[@name=\"My Account\"]"}
2021-12-07 08:00:52:966 - [debug] [W3C (2e1169ef)] Calling AppiumDriver.findElements() with args: ["xpath","//XCUIElementTypeOther[@name=\"My Account\"]","2e1169ef-e11e-47bd-9f4e-3042f38019b3"]
2021-12-07 08:00:52:967 - [debug] [XCUITest] Executing command 'findElements'
2021-12-07 08:00:52:968 - [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id, css selector
2021-12-07 08:00:52:968 - [debug] [BaseDriver] Waiting up to 0 ms for condition
2021-12-07 08:00:52:973 - [debug] [WD Proxy] Matched '/element' to command name 'findElement'
2021-12-07 08:00:52:974 - [debug] [WD Proxy] Proxying [POST /element] to [POST http://127.0.0.1:8404/session/69070FA0-222C-49CB-A14B-4B647A06DBF0/element] with body: {"using":"xpath","value":"//XCUIElementTypeOther[@name=\"My Account\"]"}
2021-12-07 08:00:52:979 - [debug] [W3C (2e1169ef)] Responding to client with driver.findElements() result: []
2021-12-07 08:00:52:983 - [HTTP] <-- POST /wd/hub/session/2e1169ef-e11e-47bd-9f4e-3042f38019b3/elements 200 240159 ms - 12
2021-12-07 08:00:52:983 - [HTTP] 
2021-12-07 08:01:21:964 - [HTTP] --> POST /wd/hub/session/2e1169ef-e11e-47bd-9f4e-3042f38019b3/element
2021-12-07 08:01:21:965 - [HTTP] {"using":"xpath","value":"//XCUIElementTypeOther[@name=\"My Account\"]"}
2021-12-07 08:01:21:965 - [debug] [W3C (2e1169ef)] Calling AppiumDriver.findElement() with args: ["xpath","//XCUIElementTypeOther[@name=\"My Account\"]","2e1169ef-e11e-47bd-9f4e-3042f38019b3"]
2021-12-07 08:01:21:965 - [debug] [XCUITest] Executing command 'findElement'
2021-12-07 08:01:31:777 - [HTTP] <-- POST /wd/hub/session/2e1169ef-e11e-47bd-9f4e-3042f38019b3/element - - ms - -
2021-12-07 08:01:31:778 - [HTTP] `

**Comment by AndreiTsialenchanka** [comment]
The problem is that before this timeout find element commands are usually fast. I have a redirect on this page maybe this is the problem here

**Comment by StephanB75** [comment]
unable to find an element using 'accessibility id'

have you tried to use "name" or "id" as locator strategy ?

**Comment by mykola-mokhnach** [comment]
Maybe the element is really not there? Could you attach the actual page source?

**Comment by AndreiTsialenchanka** [comment]
`

Find By | Selector
-- | --
-ios class chain (docs) | **/XCUIElementTypeOther[`label == "My Account"`]
-ios predicate string (docs) | label == "My Account" AND name == "My Account" AND value == "1" AND type == "XCUIElementTypeOther"
xpath | //XCUIElementTypeOther[@name="My Account"]

`
This is what I have in inspector

**Comment by AndreiTsialenchanka** [comment]
> unable to find an element using 'accessibility id'
> 
> have you tried to use "name" or "id" as locator strategy ?

this one with "accessibility id" is not part of the question here.

**Comment by mykola-mokhnach** [comment]
The fact the element is visible In the inspector does not mean it is also present in the automated test. Please take the page source snapshot from your actual test before locating the element  and share it here

**Comment by mykola-mokhnach** [comment]
Closed because of no response
