### ISSUE TITLE
Unable to start appium server with Selenium 4

### ISSUE THREAD

**Issue by skhandekar1** [appium/appium#16242]
I am using Selenium 4.1.0 with Appium server 6.1.0.

When programmatically starting Appium server using service builder I get the following error:

TestNG: Procedure 2 .log { display: none;} .stack-trace { display: none;}

`java.lang.AbstractMethodError: org.openqa.selenium.remote.service.DriverService$Builder.createArgs()Ljava/util/List; at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:441) at io.appium.java_client.service.local.AppiumDriverLocalService.buildService(AppiumDriverLocalService.java:86) at framework.testWriting.NaluTestSection.startAppiumService(NaluTestSection.java:227) at framework.testWriting.NaluTestSection.doInit(NaluTestSection.java:106) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133) at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper
`
How do I figure out the compatibilities for the selenium and Appium versions? I tried Appium 7.1.0 with Selenium 4 with no luck either. Appium 6.1.0, does only work with Selenium 3.141.59 though. Please help.

**Comment by KazuCocoa** [comment]
I would try out https://github.com/appium/java-client/releases/tag/v8.0.0-beta
