### ISSUE TITLE
Unable to launch App on IOS simulators

### ISSUE THREAD

**Issue by ajmeraaxesh** [appium/appium#16258]
Hi,

Completely new to Appium. I am just trying to get my hands dirty. I am able to run the app on Android simulator.  It fails to launch on IOS. I can see it getting installed

* Appium version:  1.22.1
* Desktop OS/version used to run Appium:
* Node.js version: 16.13.1
* Npm or Yarn package manager:
* Mobile platform/version under test: IOS
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Both CLI and App

{
  path: '/wd/hub',
    port: 4723,
   capabilities: {
         platformName: 'iOS',
    platformVersion: '15.0',
    deviceName: 'iPhone 11',
    automationName: 'XCUITest',
    showXcodeLog: true,
        app: <app-path-zip-file>,
    },
   connectionRetryTimeout: 30000,
}

Appium Server Logs Gist:
https://gist.github.com/ajmeraaxesh/084838e416cfa21c664c76a1d3248f58

Tried launching using Appium Inspector with the same capabilities suggested above. Any suggestion what should be done

**Comment by mykola-mokhnach** [comment]
I don't observe any explicit errors in the attached log. Usually it takes a while to build WDA, especially on weaker machines, so expect up to several minutes delay until session creation is completed

**Comment by ajmeraaxesh** [comment]
so any capabilities  fields or anything I can do to run it on low end machine. I am using MacBook air2017

**Comment by ajmeraaxesh** [comment]
Error on Javascript client code

2021-12-20T08:56:22.024Z ERROR webdriver: RequestError: socket hang up
    at ClientRequest.<anonymous> (/Users/aajmera/Documents/AxeshProjects/Appium-Tuts/appium-docs-getting-started/node_modules/got/dist/source/core/index.js:962:111)
    at Object.onceWrapper (node:events:510:26)
    at ClientRequest.emit (node:events:402:35)
    at ClientRequest.emit (node:domain:475:12)
    at ClientRequest.origin.emit (/Users/aajmera/Documents/AxeshProjects/Appium-Tuts/appium-docs-getting-started/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at Socket.socketOnEnd (node:_http_client:471:9)
    at Socket.emit (node:events:402:35)
    at Socket.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at connResetException (node:internal/errors:691:14)
    at Socket.socketOnEnd (node:_http_client:471:23)
    at Socket.emit (node:events:402:35)
    at Socket.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
/Users/aajmera/Documents/AxeshProjects/Appium-Tuts/appium-docs-getting-started/node_modules/webdriver/build/utils.js:71
        throw new Error('Failed to create session.\n' + message);
              ^

**Comment by mykola-mokhnach** [comment]
I would try to increase all sorts of timeouts there, for example `wdaLaunchTimeout` and `wdaConnectionTimeout`. Also it makes sense to try WDA compilation with xcode. Usually the very first project compilation is the longest one. All the following operations take less time because of caching.

**Comment by ajmeraaxesh** [comment]
Looks like it definitely takes time to install the WDA on the simulator  for first time. So here is the solution I tried and it works. Please do suggest if this is the right so that if anyone stumbles on issue like this in future, they know what to do

{
    platformName: 'iOS',
    platformVersion: '15.0',
    deviceName: 'iPhone 11',
    automationName: 'XCUITest',
    showXcodeLog: true,
    clearSystemFiles: true,
    wdaLocalPort: 4000,
    usePrebuiltWDA: true,
    //useNewWDA: true,
    wdaLaunchTimeout: 60 * 1000 * 4,
    wdaConnectionTimeout: 60 * 1000 * 4,
}

I used a different port for wdaLocalPort, that certainly helped and plus the timeout as suggested by you

**Comment by mykola-mokhnach** [comment]
Yes, the optimisation above makes sense to me.
