### ISSUE TITLE
Unknown Error to get Element Size

### ISSUE THREAD

**Issue by fazzyh** [appium/appium#16316]
## The problem

All my automation scripts failed when trying to check the element size. Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Request failed with status code 501
Traceback (most recent call last):
  File "C:\Users\<user>\Downloads\simple_ui_test.py", line 29, in <module>
    size = tab.size
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 587, in size
    size = self._execute(Command.GET_ELEMENT_RECT)['value']
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 710, in _execute
    return self._parent.execute(command, params)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Python38\lib\site-packages\appium\webdriver\errorhandler.py", line 31, in check_response
    raise wde
  File "C:\Python38\lib\site-packages\appium\webdriver\errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Request failed with status code 501
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Request failed with status code 501
    at getResponseForW3CError (C:\Users\<user>\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\<user>\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:380:37)
    at runMicrotasks (<anonymous>)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processImmediate (node:internal/timers:437:9)

It was working fine before. What changes that causing it to fail now? Simple script below. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.2
* Last Appium version that did not exhibit the issue (if applicable): 1.3.0
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): 16.13.1
* Npm or Yarn package manager: npm 8.1.2
* Mobile platform/version under test: Desktop application
* Real device or emulator/simulator: Real

## Code To Reproduce Issue [ Good To Have ]
#Contextual_Ribbon_POC
    desired_caps = {
        "platformName": "Windows",
        "platformVersion": "10",
        "deviceName": "WindowsPC",
        "app": "C:\\Program Files\\Materialise\\3-matic 0.0 (x64) Internal\\3-matic.exe"
    }

    url = "http://127.0.0.1:4723/wd/hub"

    driver = webdriver.Remote(url, desired_caps)
    driver.implicitly_wait(10)
    screenshot_folder = 'C:\\Test_Report\\screenshot\\'

    tab = driver.find_element(By.XPATH, "//TabItem[@Name='{}']".format("Options & Help"))
    tab.click()

    size = tab.size
    w,h = size['width'], size['height']

    print(size)
    print(w,h)

**Comment by KazuCocoa** [comment]
Could you share the full log and your client version information as well?
I wonder something WinAppDriver error related to w3c webdriver stuff.  (since WinAppDriver does not support W3C WebDriver yet)

**Comment by fazzyh** [comment]
Link to full log: 
https://gist.github.com/fazzyh/a93824d778ae1274dbe7f220f1ac6ca7

**Comment by mykola-mokhnach** [comment]
Yes, this is another w3c issue we could/need to workaround in the driver. I'll create a PR later

**Comment by mykola-mokhnach** [comment]
The patch has been published in the driver version 1.21.0

**Comment by fazzyh** [comment]
Is the patch ready ? The PR failed 2 out 5 checks?

**Comment by KazuCocoa** [comment]
the failure itself was recent colorsjs stuff.
