### ISSUE TITLE
Original error: '15' does not exist in the list of simctl SDKs.

### ISSUE THREAD

**Issue by bhargavas12** [appium/appium#16355]
Updated to macos-latest (11.6.2) in azure devops pipeline for automation
1. xcode version - 13.1
2. appium version - appium@1.22.2

Error:

W/launcher - Ignoring uncaught error WebDriverError: An unknown server-side error occurred while processing the command. Original error: '15' does not exist in the list of simctl SDKs. Only the following Simulator SDK versions are available on your system: 15.2, 14.3, 13.4, 8.0, 14.5, 13.7, 8.3, 14.4, 15.0, 6.2, 7.4, 7.2

Tried giving it as '15.0' as well but still same error.

**Comment by mykola-mokhnach** [comment]
Please provide the full server log

**Comment by bhargavas12** [comment]
Emitted 'error' event on Request instance at:
    at Request.onRequestError (/Users/runner/work/1/s/test/ui-test/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:412:35)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -54,
  code: 'ECONNRESET',
  syscall: 'read'
}
[05:08:46] gulp-angular-protractor - Webdriver standalone is updated
[05:08:46] gulp-angular-protractor - Webdriver standalone server will be started
[05:08:46] [05:08:46] E/start - Selenium Standalone is not present. Install with webdriver-manager update --standalone

[05:08:46] gulp-angular-protractor - Webdriver standalone server will be closed
[05:08:46] gulp-angular-protractor - We will run the Protractor engine
[05:08:47] I/launcher - Running 1 instances of WebDriver
[05:08:47] I/local - Starting selenium standalone server...
[05:08:47] I/local - Selenium standalone server started at http://10.79.2.122:4723/wd/hub
[05:08:56] W/launcher - Ignoring uncaught error WebDriverError: An unknown server-side error occurred while processing the command. Original error: '15' does not exist in the list of simctl SDKs. Only the following Simulator SDK versions are available on your system: 15.2, 14.3, 13.4, 8.0, 14.5, 13.7, 8.3, 14.4, 15.0, 6.2, 7.4, 7.2
[05:08:56] E/launcher - BUG: launcher exited with 1 tasks remaining
[05:08:56] gulp-angular-protractor - We will stop the Protractor engine
Java terminated  

*** Process has finished ***
##[error]PowerShell exited with code '1'.
Finishing: Running UI Test

**Comment by mykola-mokhnach** [comment]
Unfortunately this one is not very useful. I need the server log

**Comment by KazuCocoa** [comment]
it looks like the environment had _15.2, 14.3, 13.4, 8.0, 14.5, 13.7, 8.3, 14.4, 15.0, 6.2, 7.4, 7.2_ images, but the client specified platformVersion as 15.
Anyway, the server log will tell more details.

**Comment by mykola-mokhnach** [comment]
Closed because of no response
