### ISSUE TITLE
Issue with "stale element reference" error in iOS 15.0

### ISSUE THREAD

**Issue by ddvibhashyam** [appium/appium#16354]
## The problem

We are observing a "stale element reference" error while getting the selected option from the dropdown in iOS 15.0. After selecting the value in the dropdown, we are getting the selected value using the getFirstSelectedOption().getAttribute("value") method and it is failing with a stale element error. We even tried to get the value in the try-catch block and observed the same. When we execute the same run in iOS 14.5, we are able to get the value. This issue is seen consistently (10/10).

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.0
* Last Appium version that did not exhibit the issue (if applicable):1.21.0
* Mobile platform/version under test: iOS 15.0
* Real device or emulator/simulator: iPad Simulator

## Details

We are seeing the stale element error with both IOSDriver and AppiumDriver even if we use "appium:useNativeCachingStrategy" the capability to "false".

## Link to Appium logs

https://gist.github.com/ddvibhashyam/e6f54f636ff2086bddc70d3b51125039

## Code To Reproduce Issue [ Good To Have ]
========================================
Select credential = new Select(driver.findElement(By.xpath("(//div[contains(@data-aura-class,\"ahmWriteInForm\")]//div[contains(@class,\"slds-p-vertical_x-small slds-p-right_small slds-p-left_small slds-size_12-of-12\")]//select)[1]")));

credential.selectByValue("AS");

Select credential2 = new Select(wait.until(ExpectedConditions.visibilityOf(driver.findElement(By.xpath("(//div[contains(@data-aura-class,\"ahmWriteInForm\")]//div[contains(@class,\"slds-p-vertical_x-small slds-p-right_small slds-p-left_small slds-size_12-of-12\")]//select)[1]")))));

System.out.println(credential2.getFirstSelectedOption().getAttribute("value"));
========================================

Please let me know in case of any further information is required.

**Comment by KazuCocoa** [comment]
it seems the error was Safari (via Web inspector protocol behind appium) was not able to find the element.
What about using newer iOS version? I wonder newer Safari (WebKit module) could prevent the error.

```
2022-01-20 05:57:38:792 - [HTTP] --> GET /wd/hub/session/84ce14b6-16f3-4a13-8054-12f7ecea7e93/element/%3Awdc%3A1642658189077/selected
2022-01-20 05:57:38:792 - [HTTP] {}
2022-01-20 05:57:38:793 - [debug] [W3C (84ce14b6)] Calling AppiumDriver.elementSelected() with args: [":wdc:1642658189077","84ce14b6-16f3-4a13-8054-12f7ecea7e93"]
2022-01-20 05:57:38:793 - [debug] [XCUITest] Executing command 'elementSelected'
2022-01-20 05:57:38:828 - [debug] [W3C (84ce14b6)] Encountered internal error running command: StaleElementReferenceError: An element command failed because the referenced element is no longer attached to the DOM.
2022-01-20 05:57:38:829 - [debug] [W3C (84ce14b6)]     at XCUITestDriver.getAtomsElement (/Volumes/Sauce/selenium/appium-v1.22.0/node_modules/appium-xcuitest-driver/lib/commands/web.js:269:11)
2022-01-20 05:57:38:829 - [debug] [W3C (84ce14b6)]     at XCUITestDriver.elementSelected (/Volumes/Sauce/selenium/appium-v1.22.0/node_modules/appium-xcuitest-driver/lib/commands/element.js:32:31)
2022-01-20 05:57:38:829 - [debug] [W3C (84ce14b6)]     at commandExecutor (/Volumes/Sauce/selenium/appium-v1.22.0/node_modules/appium-base-driver/lib/basedriver/driver.js:335:9)
2022-01-20 05:57:38:829 - [debug] [W3C (84ce14b6)]     at /Volumes/Sauce/selenium/appium-v1.22.0/node_modules/async-lock/lib/index.js:146:12
2022-01-20 05:57:38:829 - [debug] [W3C (84ce14b6)]     at AsyncLock._promiseTry (/Volumes/Sauce/selenium/appium-v1.22.0/node_modules/async-lock/lib/index.js:280:31)
2022-01-20 05:57:38:829 - [debug] [W3C (84ce14b6)]     at exec (/Volumes/Sauce/selenium/appium-v1.22.0/node_modules/async-lock/lib/index.js:145:9)
2022-01-20 05:57:38:829 - [debug] [W3C (84ce14b6)]     at AsyncLock.acquire (/Volumes/Sauce/selenium/appium-v1.22.0/node_modules/async-lock/lib/index.js:162:3)
2022-01-20 05:57:38:829 - [debug] [W3C (84ce14b6)]     at XCUITestDriver.executeCommand (/Volumes/Sauce/selenium/appium-v1.22.0/node_modules/appium-base-driver/lib/basedriver/driver.js:348:39)
2022-01-20 05:57:38:829 - [debug] [W3C (84ce14b6)]     at XCUITestDriver.executeCommand (/Volumes/Sauce/selenium/appium-v1.22.0/node_modules/appium-xcuitest-driver/lib/driver.js:786:24)
2022-01-20 05:57:38:829 - [debug] [W3C (84ce14b6)]     at AppiumDriver.executeCommand (/Volumes/Sauce/selenium/appium-v1.22.0/lib/appium.js:563:36)
2022-01-20 05:57:38:830 - [debug] [W3C (84ce14b6)]     at runMicrotasks (<anonymous>)
2022-01-20 05:57:38:830 - [debug] [W3C (84ce14b6)]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
2022-01-20 05:57:38:830 - [debug] [W3C (84ce14b6)]     at asyncHandler (/Volumes/Sauce/selenium/appium-v1.22.0/node_modules/appium-base-driver/lib/protocol/protocol.js:297:21)
2022-01-20 05:57:38:831 - [HTTP] <-- GET /wd/hub/session/84ce14b6-16f3-4a13-8054-12f7ecea7e93/element/%3Awdc%3A1642658189077/selected 404 39 ms - 1724
```

**Comment by ddvibhashyam** [comment]
We are using the latest version supported by the cloud provider which is iOS 15.0 with appium 1.22.0 and observing this issue. Also, it is happening only for some dropdowns. On the same page, we can get the value for other dropdowns even though they are built the same as the one with the issue.

**Comment by mykola-mokhnach** [comment]
Please try the most recent server version (preferably Appium2 with xcuitest driver up to date).

**Comment by mykola-mokhnach** [comment]
Btw, the `useNativeCachingStrategy` setting has no effect for the web context

**Comment by ddvibhashyam** [comment]
@mykola-mokhnach I've tested with java-client 8.0.0-beta2 and still observing the stale element reference error. 

https://gist.github.com/ddvibhashyam/83338096bae086c75b26e0bb719c86c5

Also, I observed that this is happening when the dropdown is having a huge number of options. I have two environments of the applications in which the dropdown has 50 options and in another environment, it has 1400 options. The getFirstSelectedOption().getAttribute("value") method able to return the value in the first environment and it is giving me stale element error in second environment. I've tested both with the same capabilities.

**Comment by mykola-mokhnach** [comment]
> We are using the latest version supported by the cloud provider which is iOS 15.0 with appium 1.22.0 and observing this issue.

Version 1.22.0 is not the latest. Consider then contacting their customer support.

**Comment by ddvibhashyam** [comment]
@mykola-mokhnach 

> > We are using the latest version supported by the cloud provider which is iOS 15.0 with appium 1.22.0 and observing this issue.
> 
> Version 1.22.0 is not the latest. Consider then contacting their customer support.

We are observing this issue even with Appium v1.22.2 with iOS 15.2.

Gist: https://gist.github.com/ddvibhashyam/f1bf653d1b2c786da3cc204034139893

**Comment by ddvibhashyam** [comment]
> @mykola-mokhnach
> 
> > > We are using the latest version supported by the cloud provider which is iOS 15.0 with appium 1.22.0 and observing this issue.
> > 
> > 
> > Version 1.22.0 is not the latest. Consider then contacting their customer support.
> 
> We are observing this issue even with Appium v1.22.2 with iOS 15.2.
> 
> Gist: https://gist.github.com/ddvibhashyam/f1bf653d1b2c786da3cc204034139893

@mykola-mokhnach We are still observing the issue with iOS 15.4 and Appium 1.22.3.

GIST: https://gist.github.com/ddvibhashyam/9158e8c01d0bc84fc0de1305b60663da

Could you please check and provide any update on this?

**Comment by mykola-mokhnach** [comment]
I don't know if anybody was working on this issue (probably not if there are no new comments here). I cannot help much as I don't have any experience working with Safari remote debugger.

**Comment by ddvibhashyam** [comment]
> I don't know if anybody was working on this issue (probably not if there are no new comments here). I cannot help much as I don't have any experience working with Safari remote debugger.

@mykola-mokhnach Could you please suggest if you want me to post this anywhere else?

**Comment by jlipps** [comment]
I might be able to look into it if there's a standalone repro case that I can use. It won't be solvable just by looking at logs etc... @ddvibhashyam can you construct an html file that reproduces this issue?

**Comment by ddvibhashyam** [comment]
> I might be able to look into it if there's a standalone repro case that I can use. It won't be solvable just by looking at logs etc... @ddvibhashyam can you construct an html file that reproduces this issue?

@jlipps Thank you for the response. I'm able to replicate this issue in a sample [website](https://formstone.it/components/dropdown/demo/). I've added the rows to the existing dropdown by executing a script and selecting the value. While getting the selected value, I see the stale element error. Here is the [gist](https://gist.github.com/ddvibhashyam/08b481c57c1095e544096fbd18655bb0) of the WebDriver code.

Please check and do the needful. Let me know in case of any further information is required.

**Comment by ddvibhashyam** [comment]
> > I might be able to look into it if there's a standalone repro case that I can use. It won't be solvable just by looking at logs etc... @ddvibhashyam can you construct an html file that reproduces this issue?
> 
> @jlipps Thank you for the response. I'm able to replicate this issue in a sample [website](https://formstone.it/components/dropdown/demo/). I've added the rows to the existing dropdown by executing a script and selecting the value. While getting the selected value, I see the stale element error. Here is the [gist](https://gist.github.com/ddvibhashyam/08b481c57c1095e544096fbd18655bb0) of the WebDriver code.
> 
> Please check and do the needful. Let me know in case of any further information is required.

@jlipps Could you please provide any update on this issue?

**Comment by jlipps** [comment]
Sorry, haven't had time to look at this yet

**Comment by ddvibhashyam** [comment]
> Sorry, haven't had time to look at this yet

@jlipps Could you please take this as a priority and provide any solution for the issue. It is impacting our test executions.

**Comment by jlipps** [comment]
I'm sorry the issue is affecting you. I don't know when I'll have time to look into it, as it is not one of my assigned work priorities at the moment.

**Comment by jlipps** [comment]
Sorry, no update

**Comment by msabya** [comment]
I have same issue with Appium 2.4 and xcuitest 7.1 with mobile safari browser

I have moved from Native app to Safari Web interface. When the safari opens up a popup window all the element reference becomes stale?

So I have 2 windows in safari but i got 3 context 
- one for Native app
- One context for Parent window
- One context for child/popup window
All the pop window elements are throwing stale element exception.

So appreciate a speedy solution to this problem

**Comment by mykola-mokhnach** [comment]
iOS 15 is not supported anymore. Closing as obsolete
