### ISSUE TITLE
Application crashes when it should be prompted to allow access to contacts (AUTO_GRANT_PERMISSIONS = true)

### ISSUE THREAD

**Issue by smowin** [appium/appium#16407]
## The problem

Application crashes when it should be prompted to allow access to contacts. 
**AUTO_GRANT_PERMISSIONS** setting is set to **TRUE**
`capabilities.setCapability(AUTO_GRANT_PERMISSIONS, true);`

## Environment

* Appium version (or git revision) that exhibits the issue: [1.22.2](https://www.npmjs.com/package/appium/v/1.22.2), [1.23.0-beta.0](https://www.npmjs.com/package/appium/v/1.23.0-beta.0)
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOS Monerey 12.2
* Node.js version (unless using Appium.app|exe): 17.4.0
* Npm or Yarn package manager: npm 8.4.0
* Mobile platform/version under test: Android 11 (UiAutomator2)
* Real device or emulator/simulator: both (with Google Services)
* Appium CLI or Appium.app|exe: 

## Capabilities
` Proxying [POST /session] to [POST http://127.0.0.1:8201/wd/hub/session] with body: {"capabilities":{"firstMatch":[{"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platformName":"android","app":"*some app*","appWaitActivity":"OnboardingActivity","autoGrantPermissions":true,"automationName":"Appium","clearSystemFiles":true,"deviceName":"OnePlus 7T","udid":"7d9a3123"},"platformName":"android","app":"*some app*","appWaitActivity":"OnboardingActivity","autoGrantPermissions":true,"automationName":"Appium","clearSystemFiles":true,"deviceName":"7d9a3123","udid":"7d9a3123","deviceUDID":"7d9a3123","appPackage":"*some app*"}],"alwaysMatch":{}}}`

**Comment by smowin** [comment]
Thanks for the parameter, I caught the crash
In logs, this is displayed:
`2022-02-04 09:26:38.698 16769-16769/*app* E/ViewConfiguration: Tried to access UI constants from a non-visual Context:*app*.App@55b5249UI constants, such as display metrics or window metrics, must be accessed from Activity or other visual Context. Use an Activity or a Context created with Context#createWindowContext(int, Bundle), which are adjusted to the configuration and visual bounds of an area on screen
    java.lang.IllegalArgumentException: Tried to access UI constants from a non-visual Context:ru.alfabank.oavdo.amc.App@55b5249
        at android.view.ViewConfiguration.get(ViewConfiguration.java:510)
        at android.view.View.<init>(View.java:5317)
        at android.view.View.<init>(View.java:5467)
        at android.view.ViewGroup.<init>(ViewGroup.java:697)
        at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:56)
        at android.webkit.WebView.<init>(WebView.java:413)
        at android.webkit.WebView.<init>(WebView.java:355)
        at android.webkit.WebView.<init>(WebView.java:337)
        at android.webkit.WebView.<init>(WebView.java:324)
        at android.webkit.WebView.<init>(WebView.java:314)
        at f7.<init>(SourceFile:4)
        at g3$a.run(SourceFile:1)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)`
I'll watch with the developers
