### ISSUE TITLE
UIA2 driver throws an exception if updateSettings is called

### ISSUE THREAD

**Issue by mykola-mokhnach** [appium/appium#16411]
## The problem

Every time one calls updateSettings API UIA2 driver throws an exception similar to

```
2022-01-31T11:08:35.0738310Z     [HTTP] --> POST /session/a1430ea4-cf1b-4284-b31d-94b505a60538/appium/settings
2022-01-31T11:08:35.0742790Z     [HTTP] {"settings":{"ignoreUnimportantViews":true}}
2022-01-31T11:08:35.0744850Z     [debug] [W3C (a1430ea4)] Calling AppiumDriver.updateSettings() with args: [{"ignoreUnimportantViews":true},"a1430ea4-cf1b-4284-b31d-94b505a60538"]
2022-01-31T11:08:35.2623950Z     [debug] [W3C (a1430ea4)] Encountered internal error running command: TypeError: Cannot read property 'includes' of undefined
2022-01-31T11:08:35.2636830Z     [debug] [W3C (a1430ea4)]     at AndroidUiautomator2Driver.commands.updateSettings (/Users/runner/.appium/appium-uiautomator2-driver/node_modules/appium-uiautomator2-driver/lib/commands/general.js:241:37)
2022-01-31T11:08:35.2639430Z     [debug] [W3C (a1430ea4)]     at commandExecutor (/Users/runner/.appium/appium-uiautomator2-driver/node_modules/@appium/base-driver/lib/basedriver/driver.js:333:7)
2022-01-31T11:08:35.2674630Z     [debug] [W3C (a1430ea4)]     at /Users/runner/.appium/appium-uiautomator2-driver/node_modules/async-lock/lib/index.js:146:12
2022-01-31T11:08:35.2679230Z     [debug] [W3C (a1430ea4)]     at AsyncLock._promiseTry (/Users/runner/.appium/appium-uiautomator2-driver/node_modules/async-lock/lib/index.js:280:31)
2022-01-31T11:08:35.2681500Z     [debug] [W3C (a1430ea4)]     at exec (/Users/runner/.appium/appium-uiautomator2-driver/node_modules/async-lock/lib/index.js:145:9)
2022-01-31T11:08:35.2699400Z     [debug] [W3C (a1430ea4)]     at AsyncLock.acquire (/Users/runner/.appium/appium-uiautomator2-driver/node_modules/async-lock/lib/index.js:162:3)
2022-01-31T11:08:35.2702000Z     [debug] [W3C (a1430ea4)]     at AndroidUiautomator2Driver.executeCommand (/Users/runner/.appium/appium-uiautomator2-driver/node_modules/@appium/base-driver/lib/basedriver/driver.js:346:39)
2022-01-31T11:08:35.2727000Z     [debug] [W3C (a1430ea4)]     at wrappedCmd (/Users/runner/.nvm/versions/node/v14.18.3/lib/node_modules/appium/lib/appium.js:540:31)
2022-01-31T11:08:35.2775050Z     [debug] [W3C (a1430ea4)]     at AppiumDriver.executeWrappedCommand (/Users/runner/.nvm/versions/node/v14.18.3/lib/node_modules/appium/lib/appium.js:618:22)
2022-01-31T11:08:35.2777240Z     [debug] [W3C (a1430ea4)]     at AppiumDriver.executeCommand (/Users/runner/.nvm/versions/node/v14.18.3/lib/node_modules/appium/lib/appium.js:547:28)
2022-01-31T11:08:35.2788230Z     [debug] [W3C (a1430ea4)]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
2022-01-31T11:08:35.2793520Z     [debug] [W3C (a1430ea4)]     at asyncHandler (/Users/runner/.nvm/versions/node/v14.18.3/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:302:19)
2022-01-31T11:08:35.2802530Z     [HTTP] <-- POST /session/a1430ea4-cf1b-4284-b31d-94b505a60538/appium/settings 500 75 ms - 649
2022-01-31T11:08:35.2808610Z     [HTTP] 
```

This only happens in Appium 2 after the base driver was bumped to v8

## Environment

* Appium version (or git revision) that exhibits the issue: v2.beta25
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS
* Node.js version (unless using Appium.app|exe): 14
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Android 8
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: CLI

**Comment by mykola-mokhnach** [comment]
Linking https://github.com/appium/appium-uiautomator2-driver/pull/499

**Comment by mykola-mokhnach** [comment]
This particular issue has been patched. A better fix is in progress
