### ISSUE TITLE
Probably `--pct-syskeys 0` needs as monkey command in Android

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium#16427]
## The problem

I haven't tested well yet, so let me leave this error here for now.

https://github.com/appium/ruby_lib_core/pull/359#issuecomment-1033462989
I've observed the below error in a test. 
```
2022-02-09 07:24:08:572 - [HTTP] --> POST /wd/hub/session/ee29d011-cfb2-4de4-b317-98406137c6cc/appium/device/activate_app
2022-02-09 07:24:08:573 - [HTTP] {"bundleId":"io.appium.android.apis"}
2022-02-09 07:24:08:573 - [debug] [W3C (ee29d011)] Calling AppiumDriver.activateApp() with args: ["io.appium.android.apis",null,null,null,"ee29d011-cfb2-4de4-b317-98406137c6cc"]
2022-02-09 07:24:08:574 - [Appium] Plugins which can handle cmd 'activateApp': images
2022-02-09 07:24:08:574 - [Appium] Plugin images is now handling cmd 'activateApp'
2022-02-09 07:24:08:574 - [Appium] Executing default handling behavior for command 'activateApp'
2022-02-09 07:24:08:574 - [debug] [AndroidDriver] Activating 'io.appium.android.apis' with 'adb shell monkey -p io.appium.android.apis -c android.intent.category.LAUNCHER 1' command
2022-02-09 07:24:08:574 - [debug] [ADB] Running '/Users/runner/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell monkey -p io.appium.android.apis -c android.intent.category.LAUNCHER 1'
2022-02-09 07:24:10:780 - [AndroidDriver] Cannot activate 'io.appium.android.apis'. Original error: Error executing adbExec. Original error: 'Command '/Users/runner/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell monkey -p io.appium.android.apis -c android.intent.category.LAUNCHER 1' exited with code 251'; Command output: args: [-p, io.appium.android.apis, -c, android.intent.category.LAUNCHER, 1]
2022-02-09 07:24:10:780 - [AndroidDriver]  arg: "-p"
2022-02-09 07:24:10:780 - [AndroidDriver]  arg: "io.appium.android.apis"
2022-02-09 07:24:10:780 - [AndroidDriver]  arg: "-c"
2022-02-09 07:24:10:780 - [AndroidDriver]  arg: "android.intent.category.LAUNCHER"
2022-02-09 07:24:10:781 - [AndroidDriver]  arg: "1"
2022-02-09 07:24:10:781 - [AndroidDriver] data="io.appium.android.apis"
2022-02-09 07:24:10:781 - [AndroidDriver] data="android.intent.category.LAUNCHER"
2022-02-09 07:24:10:781 - [AndroidDriver] ** SYS_KEYS has no physical keys but with factor 2.0%.
2022-02-09 07:24:10:781 - [AndroidDriver] 
2022-02-09 07:24:10:841 - [debug] [W3C (ee29d011)] Encountered internal error running command: Error: Cannot activate 'io.appium.android.apis'. Original error: Error executing adbExec. Original error: 'Command '/Users/runner/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell monkey -p io.appium.android.apis -c android.intent.category.LAUNCHER 1' exited with code 251'; Command output: args: [-p, io.appium.android.apis, -c, android.intent.category.LAUNCHER, 1]
2022-02-09 07:24:10:841 - [debug] [W3C (ee29d011)]  arg: "-p"
2022-02-09 07:24:10:841 - [debug] [W3C (ee29d011)]  arg: "io.appium.android.apis"
2022-02-09 07:24:10:841 - [debug] [W3C (ee29d011)]  arg: "-c"
2022-02-09 07:24:10:841 - [debug] [W3C (ee29d011)]  arg: "android.intent.category.LAUNCHER"
2022-02-09 07:24:10:843 - [debug] [W3C (ee29d011)]  arg: "1"
2022-02-09 07:24:10:845 - [debug] [W3C (ee29d011)] data="io.appium.android.apis"
2022-02-09 07:24:10:845 - [debug] [W3C (ee29d011)] data="android.intent.category.LAUNCHER"
2022-02-09 07:24:10:845 - [debug] [W3C (ee29d011)] ** SYS_KEYS has no physical keys but with factor 2.0%.
2022-02-09 07:24:10:845 - [debug] [W3C (ee29d011)] 
2022-02-09 07:24:10:845 - [debug] [W3C (ee29d011)]     at Object.errorAndThrow (/Users/runner/.appium/appium-uiautomator2-driver/node_modules/@appium/support/lib/logging.js:94:35)
2022-02-09 07:24:10:845 - [debug] [W3C (ee29d011)]     at AndroidUiautomator2Driver.activateApp (/Users/runner/.appium/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/app-management.js:66:9)
2022-02-09 07:24:10:867 - [HTTP] <-- POST /wd/hub/session/ee29d011-cfb2-4de4-b317-98406137c6cc/appium/device/activate_app 500 2294 ms - 1835
2022-02-09 07:24:10:867 - [HTTP]
```

According to https://stackoverflow.com/questions/44860475/how-to-use-the-monkey-command-with-an-android-system-that-doesnt-have-physical and https://stackoverflow.com/questions/20911714/disable-system-level-events-on-android-monkey , it seems like https://github.com/appium/appium-android-driver/blob/e18495b3bc8858dbd0c7b77a5c37642b732b462e/lib/commands/app-management.js#L56-L59 needs `--pct-syskeys 0`.

I need to run the command on real devices as well as emulators. The test failure was on an emulator only.

## Environment

* Appium version (or git revision) that exhibits the issue: v2.0.0-beta.25, uiautomator2@2.0.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS Azure instance
* Node.js version (unless using Appium.app|exe): 12
* Npm or Yarn package manager: npm
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

Described in the above:

## Link to Appium logs

https://github.com/appium/ruby_lib_core/pull/359#issuecomment-1033462989

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
feel free to add that argument if that fixes the above issue

**Comment by KazuCocoa** [comment]
`--pct-syskeys 0` seems working on both a real device and an emulator.
Maybe it does not break existing one while it helps non-hw keyboard env like CI https://stackoverflow.com/questions/44860475/how-to-use-the-monkey-command-with-an-android-system-that-doesnt-have-physical

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium/issues/16941
Potentially this fix affects another case.

So, it seems like we should return an error message to try out mobile:startActivity command instead of this activateApp instead of this PR.
