### ISSUE TITLE
Issue with appium shake feature with iOS 

### ISSUE THREAD

**Issue by amitkumar3-qa** [appium/appium#16461]
Hi Team,
I am trying to automate app feature which popup only when shaking a device. I am using shake feature as below:
driver.shake(); for iOS device
Details:
Using below capabilities and iOS simulator:
`capabilities.setCapability("platformName","iOS");
		capabilities.setCapability("platformVersion", "14.5");
		capabilities.setCapability("appiumVersion", "6.1.0");
		capabilities.setCapability("name", methodName.getName());
		capabilities.setCapability("automationName", "XCUITest");
		capabilities.setCapability(MobileCapabilityType.DEVICE_NAME,"iPhone 8 Plus");`
Getting below error in test execution:
`java.lang.NullPointerException
Session ID: b1b3d7bd-7f85-4694-a231-ff2591697500
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
        at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:231)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
        at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:46)
        at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
        at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
        at io.appium.java_client.HasSessionDetails.getSessionDetails(HasSessionDetails.java:39)
        at io.appium.java_client.HasSessionDetails.getSessionDetail(HasSessionDetails.java:56)
        at io.appium.java_client.HasSessionDetails.getPlatformName(HasSessionDetails.java:65)
        at io.appium.java_client.internal.JsonToMobileElementConverter.<init>(JsonToMobileElementConverter.java:49)
        at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:89)
        at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:94)
        at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:95)
`
Looking forward for any input for the same.

Thanks

**Comment by mykola-mokhnach** [comment]
Please fill out the issue report properly and provide the full server log

**Comment by amitkumar3-qa** [comment]
@mykola-mokhnach  After a temporary fix, above error is not appearing now but its not shaking the device :
Please check below code snipet and server logs:
`@Test
    public void shakeTest(){
        for(int i=0; i<50; i++) {
            driver.shake();
            System.out.println("shaking device");
        }
    }`

logs:

`16 Feb 2022 12:51:15  INFO logger - Appium started on http://0.0.0.0:18241/wd/hub
16 Feb 2022 12:51:15  INFO logger - Appium server started successfully
16 Feb 2022 12:51:15  INFO logger - --------------------------------------
Feb 16, 2022 12:51:37 PM io.appium.java_client.remote.AppiumCommandExecutor$1 lambda$0
INFO: Detected dialect: W3C
Driver created successfully
16 Feb 2022 12:51:37  INFO logger - iOS driver created
shaking device
shaking device
shaking device
shaking device
shaking device
shaking device
shaking device
shaking device
shaking device
shaking device
shaking device
shaking device
shaking device
shaking device
shaking device
shaking device
shaking device
shaking device
shaking device
shaking device
shaking device
shaking device
shaking device
shaking device
shaking device
shaking device
shaking device
shaking device
shaking device
shaking device
shaking device
shaking device
shaking device
shaking device
shaking device
shaking device
shaking device
shaking device
shaking device
shaking device
[WebDriverAgent] xcodebuild exited with code '65' and signal 'null'
shaking device
shaking device
shaking device
shaking device
shaking device
shaking device
shaking device
shaking device
shaking device
shaking device
16 Feb 2022 12:51:55  INFO logger - Shutting down driver
16 Feb 2022 12:51:55  INFO logger - Appium server stopped
16 Feb 2022 12:51:55  INFO logger - Appium server stopped successfully
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 43.057 sec - in TestSuite

`

**Comment by mykola-mokhnach** [comment]
The log above is not the Appium server one. Please provide the correct log record. We cannot help nothing without it

**Comment by mykola-mokhnach** [comment]
Closed because of no response
