### ISSUE TITLE
Android OS 11 - Unable to perform keyboard action using executeScript

### ISSUE THREAD

**Issue by KritikaSahare1611** [appium/appium#16491]
## The problem

Unable to perform the keyboard actions by using the executeScript option. Below is the sample code

driver.executeScript(“mobile: performEditorAction”, ImmutableMap.of(“action”, “search”));

The same code is working fine on Android 10 or below OS versions.

## Environment

Android

**Comment by mykola-mokhnach** [comment]
Please fill out the issue properly and provide both the server and the device (logcat) logs

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by KritikaSahare1611** [comment]
org.openqa.selenium.WebDriverException: Appium error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'android-sdk/platform-tools/adb -P 5037 -s R5CT238S5CP shell ime set io.appium.settings/.AppiumIME' exited with code 255'; Stderr: 'Unknown input method io.appium.settings/.AppiumIME cannot be selected for user #0'; Code: '255' (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'TECH-KRITIKAS', ip: '172.30.144.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '16.0.2'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {64bit: false, acceptSslCert: false, acceptSslCerts: false, adbExecTimeout: 120000, appActivity: com.healthkart.healthkart.r..., appPackage: com.healthkart.healthkart, autoGrantPermissions: true, automationName: uiautomator2, browserstack-tunnel: true, browserstack.appium_version: 1.17.0, browserstack.is_hub_canary: false, browserstack.minOSVersion: 5.0, buildName: Java Android, bundleID: com.healthkart.healthkart, bundleId: com.healthkart.healthkart, cap_browserstack.idleTimeout: 300, capabilities: {64bit: false, acceptSslCert: false, acceptSslCerts: false, adbExecTimeout: 120000, appActivity: com.healthkart.healthkart.r..., appPackage: com.healthkart.healthkart, autoGrantPermissions: true, automationName: uiautomator2, browserstack-tunnel: true, browserstack.appium_version: 1.17.0, browserstack.is_hub_canary: false, browserstack.minOSVersion: 5.0, buildName: Java Android, bundleID: com.healthkart.healthkart, bundleId: com.healthkart.healthkart, cap_browserstack.idleTimeout: 300, chromeOptions: {w3c: false}, chromedriverPort: 18082, chromedriverPorts: [[18122, 18132]], customFullReset: true, databaseEnabled: false, desired: {64bit: false, acceptSslCert: false, acceptSslCerts: false, adbExecTimeout: 120000, appActivity: com.healthkart.healthkart.r..., appPackage: com.healthkart.healthkart, autoGrantPermissions: true, automationName: uiautomator2, browserstack-tunnel: true, browserstack.appium_version: 1.17.0, browserstack.is_hub_canary: false, browserstack.minOSVersion: 5.0, buildName: Java Android, bundleID: com.healthkart.healthkart, bundleId: com.healthkart.healthkart, cap_browserstack.idleTimeout: 300, chromeOptions: {w3c: false}, chromedriverPort: 18082, chromedriverPorts: [[18122, 18132]], customFullReset: true, detected_language: selenium/3.141.59 (java win..., device: samsung galaxy s22 ultra, deviceName: Android, disableSuppressAccessibilityService: true, enablePerformanceLogging: false, mobile: {browser: mobile, version: Samsung Galaxy S22 Ultra-12.0}, nativeWebScreenshot: true, newCommandTimeout: 0, new_bucketing: true, normalizeTagNames: true, orig_os: android, osVersion: 12.0, os_version: 12.0, platform: ANDROID, platformName: Android, projectName: Android Suite Master, realMobile: true, resetKeyboard: true, sessionName: testPromptOrderPlaceCOD, skipServerInstallation: true, systemPort: 8202, udid: R5CT238S5CP, uiautomator2ServerLaunchTimeout: 60000, unicodeKeyboard: false, version: }, detected_language: selenium/3.141.59 (java win..., device: samsung galaxy s22 ultra, deviceApiLevel: 31, deviceManufacturer: samsung, deviceModel: SM-S908E, deviceName: R5CT238S5CP, deviceScreenDensity: 450, deviceScreenSize: 1080x2316, deviceUDID: R5CT238S5CP, disableSuppressAccessibilityService: true, enablePerformanceLogging: false, javascriptEnabled: true, locationContextEnabled: false, mobile: {browser: mobile, version: Samsung Galaxy S22 Ultra-12.0}, nativeWebScreenshot: true, networkConnectionEnabled: true, newCommandTimeout: 0, new_bucketing: true, normalizeTagNames: true, orig_os: android, osVersion: 12.0, os_version: 12.0, pixelRatio: 2.8125, platform: ANDROID, platformName: Android, platformVersion: 12, projectName: Android Suite Master, realMobile: true, resetKeyboard: true, sessionId: 48fe489d025c30c9dfa39e9ebbe..., sessionName: testPromptOrderPlaceCOD, skipServerInstallation: true, statBarHeight: 75, systemPort: 8202, takesScreenshot: true, udid: R5CT238S5CP, uiautomator2ServerLaunchTimeout: 60000, unicodeKeyboard: false, version: , viewportRect: {height: 2031, left: 0, top: 75, width: 1080}, warnings: {}, webStorageEnabled: false}, chromeOptions: {w3c: false}, chromedriverPort: 18082, chromedriverPorts: [[18122, 18132]], customFullReset: true, databaseEnabled: false, detected_language: selenium/3.141.59 (java win..., device: samsung galaxy s22 ultra, deviceApiLevel: 31, deviceManufacturer: samsung, deviceModel: SM-S908E, deviceName: R5CT238S5CP, deviceScreenDensity: 450, deviceScreenSize: 1080x2316, deviceUDID: R5CT238S5CP, disableSuppressAccessibilityService: true, enablePerformanceLogging: false, javascriptEnabled: true, locationContextEnabled: false, mobile: {browser: mobile, version: Samsung Galaxy S22 Ultra-12.0}, nativeWebScreenshot: true, networkConnectionEnabled: true, newCommandTimeout: 0, new_bucketing: true, normalizeTagNames: true, orig_os: android, osVersion: 12.0, os_version: 12.0, pixelRatio: 2.8125, platform: ANDROID, platformName: Android, platformVersion: 12, projectName: Android Suite Master, realMobile: true, resetKeyboard: true, sessionId: 48fe489d025c30c9dfa39e9ebbe..., sessionName: testPromptOrderPlaceCOD, skipServerInstallation: true, statBarHeight: 75, systemPort: 8202, takesScreenshot: true, udid: R5CT238S5CP, uiautomator2ServerLaunchTimeout: 60000, unicodeKeyboard: false, version: , viewportRect: {height: 2031, left: 0, top: 75, width: 1080}, warnings: {}, webStorageEnabled: false}
Session ID: 48fe489d025c30c9dfa39e9ebbec69358214410f
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:250)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:489)
	at com.healthkart.hkMobileAutomation.business.HK_Home_Steps_Android.searchProductFromHomePage(HK_Home_Steps_Android.java:186)
	at com.healthkart.hkMobileAutomation.regression.HK_Test_Prompt_Order_Place_COD_Android.testPromptOrderPlaceCOD(HK_Test_Prompt_Order_Place_COD_Android.java:31)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by KritikaSahare1611** [comment]
[mykola-mokhnach](https://github.com/mykola-mokhnach)
