### ISSUE TITLE
An unknown server-side error occurred while processing the command. Original error: The attribute 'x' is unknown

### ISSUE THREAD

**Issue by sobolewska** [appium/appium#16533]
## The problem

Console output is spamed with following type messages.

```
[Test worker] WARN com.codeborne.selenide.impl.Describe - Failed to get attribute class: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: The attribute 'class' is unknown. Valid attribute names are: (
    UID,
    accessibilityContainer,
    accessible,
    enabled,
    frame,
    index,
    label,
    name,
    rect,
    selected,
    type,
    value,
    visible,
    wdAccessibilityContainer,
    wdAccessible,
    wdEnabled,
    wdFrame,
    wdIndex,
    wdLabel,
    wdName,
    wdRect,
    wdSelected,
    wdType,
    wdUID,
    wdValue,
    wdVisible
)
Build info: version: '4.1.2', revision: '9a5a329c5a'
System info: host: '***', ip: 'fe80:0:0:0:455:f8c5:5900:8bf1%en0', os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '12.2.1', java.version: '17.0.2'
Driver info: io.appium.java_client.ios.IOSDriver
Command: [c3c8a584-759a-4432-996a-72c906a6b189, getElementAttribute {id=AC010000-0000-0000-9203-000000000000, name=class}]
Capabilities {acceptInsecureCerts: true, appium:acceptSslCerts: true, appium:automationName: XCuiTest, appium:bundleId: ***, appium:databaseEnabled: false, appium:deviceName: ***, appium:handlesAlerts: true, appium:javascriptEnabled: true, appium:locationContextEnabled: false, appium:networkConnectionEnabled: false, appium:platformVersion: 15.3.1, appium:takesScreenshot: true, appium:udid: ***, appium:webStorageEnabled: false, appium:xcodeOrgId: ***, appium:xcodeSigningId: Apple Development: ***, pageLoadStrategy: normal, platformName: ios}
Element: [[IOSDriver:  on ios (c3c8a584-759a-4432-996a-72c906a6b189)] -> css selector: XCUIElementTypeStaticText[name='Synchronizing']]
Session ID: c3c8a584-759a-4432-996a-72c906a6b189
```

The 'original error' varies, e.g. 
- Original error: The attribute 'onchange' is unknown. 
- Original error: The attribute 'class' is unknown. 
- Original error: The attribute 'placeholder' is unknown
- etc.

## Environment

build.gradle

```
dependencies {
    implementation 'org.slf4j:slf4j-simple:1.7.36'
    implementation 'org.apache.logging.log4j:log4j-api:2.17.1'
    implementation 'org.apache.logging.log4j:log4j-core:2.17.1'
    implementation 'com.codeborne:selenide:6.3.3'
    implementation 'org.apache.commons:commons-lang3:3.12.0'
    implementation 'io.qameta.allure:allure-selenide:2.17.3'
    implementation 'io.qameta.allure:allure-junit5:2.17.3'
    implementation 'org.junit.jupiter:junit-jupiter-api:5.8.2'
    implementation 'org.junit.jupiter:junit-jupiter-params:5.8.2'
    implementation 'org.aspectj:aspectjweaver:1.9.8' // needed to use @Step annotation
    implementation 'org.apache.httpcomponents:httpclient:4.5.13'
    implementation 'com.googlecode.json-simple:json-simple:1.1.1'
    implementation 'com.google.code.gson:gson:2.9.0'
    implementation 'io.appium:java-client:8.0.0-beta2'
    implementation 'org.awaitility:awaitility:4.1.1'
    implementation 'org.awaitility:awaitility-proxy:3.1.6'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.2'
}
```

* using real device iPad iOS 15.3.1
* running from MacOs 12.2.1 
* Appium ver: 8.0.0-beta2
* using selenide 6.3.3

## Question

How to hide this logs?

**Comment by sobolewska** [comment]
Intended to raise this on selenide git-hub (https://github.com/selenide/selenide/issues/1751), not here. Closing.

**Comment by sobolewska** [comment]
Can I respectfully disagree?

The readme of selenide-appium states:

> NB! This library is only needed if you want to use PageFactory (annotations like @AndroidFindBy).
> 
> If you don't need @FooFindBy annotations, consider using a [more simple approach](https://github.com/selenide-examples/selenide-appium). It just uses usual Selenide $ calls to find elements in mobile app.

I'm not using mentioned annotations etc.

Also after adding selenide-appium to dependencies simple `element.click()` fails, and I need to use `element.toWebElement().click()`.

`element.click()` fails with error:

```
NoClassDefFoundError: io/appium/java_client/MobileDriver
Screenshot: file: ...
Page source: file: ...
Timeout: 4 s.
Caused by: java.lang.NoClassDefFoundError: io/appium/java_client/MobileDriver
	at app//com.codeborne.selenide.ex.UIAssertionError.wrapToUIAssertionError(UIAssertionError.java:103)
	at app//com.codeborne.selenide.ex.UIAssertionError.wrapThrowable(UIAssertionError.java:86)
	at app//com.codeborne.selenide.ex.UIAssertionError.wrap(UIAssertionError.java:75)
	at app//com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:88)
	at app/jdk.proxy3/jdk.proxy3.$Proxy34.click(Unknown Source)
	at app//****.ipad.LoginPage.loginAsUser(LoginPage.java:24)
	(...)
```
