### ISSUE TITLE
When I run the app with GRID4, it says "Unable to determine element locating strategy for -android uiautomator"

### ISSUE THREAD

**Issue by tianyao1111** [appium/appium#16550]
## The problem
When I run the app with GRID4, it says "Unable to determine element locating strategy for -android uiautomator"

## Environment

* Appium version (or git revision) that exhibits the issue:1.22.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:win10
* Node.js version (unless using Appium.app|exe):v14.16.0
* Npm or Yarn package manager:npm
* Mobile platform/version under test:
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe: Appium CLI 

## Details

- hub
`java -jar selenium-server-4.1.1.jar hub`

- node
1.tom:
```
[server]
port = 5555

[node]
detect-drivers = false
grid-url = "http://localhost:4444"
hub = "http://localhost:4444"

[relay]
# Default Appium server endpoint
url = "http://localhost:4726/wd/hub"
status-endpoint = "/status"
# Stereotypes supported by the service
[[relay.configs]]
max-sessions = 1
stereotype = '{"browserName": "chrome", "platformName": "android", "appium:platformVersion": "11","nodename:applicationName":"huawei honor 10"}}'

[events]
publish = "tcp://localhost:4442"
subscribe = "tcp://localhost:4443"
```
`java -jar selenium-server-4.1.1.jar node --config  C:\Users\14221\Desktop\项目资料\人保E通新架构\1.toml`

- client
get_driver.py:
```
#selenium GRID专用
def get_driver():
	'''生成deiver'''
	caps = {}
	caps["platformName"] = "Android"
	# caps["platformVersion"] = "7.1.2"
	# caps["deviceName"] = "P7CDU18C03003486        device"
	# caps["deviceName"] = udid
	# caps["udid"] = udid
	# caps["deviceName"] = "127.0.0.1:62001 device"

	# 新架构app
	#caps["appPackage"] = "com.picc.etong"
	# caps["appActivity"] = "com.picc.etong.etongmain.main.GroupLoginActivity"
	#caps["appActivity"] = "com.picc.nmmslogin.activity.GroupWelcomeActivity"

	#老版app
	caps["appPackage"] = "com.picc.nx"
	# caps["appActivity"] = "com.picc.nx.ui.activity.MainActivity"
	# caps["appActivity"] = "com.picc.nx.ui.activity.common.locker.WholePatternCheckingActivity"

	# caps["appActivity"] = "com.picc.nx.ui.activity.user.LoginActivity"

	caps["appActivity"] = "com.picc.nx.ui.activity.extras.SplashActivity"

	#Don't reset app state before this session. 
	caps["noReset"] = True
	#Have Appium automatically determine which permissions your app requires and grant them to the app on install. Defaults to false. If noReset is true, this capability doesn't work.
	# caps["autoGrantPermissions"] = True
	#为了输入框输入中文
	caps["unicodeKeyboard"] = True
	caps["resetKeyboard"] = True
	#How long (in seconds) Appium will wait for a new command from the client before assuming the client quit and ending the session
	caps["newCommandTimeout"] = 180
	#Timeout in milliseconds used to wait for adb command execution. Defaults to 20000
	caps["adbExecTimeout"] = 180000
	# caps["automationName"] = "UiAutomator1"
	#Set the output format for logcat messages since Appium 1.18.0. Supported formats are listed in here. Please read logcat#outputFormat for more details about each format. Defaults to threadtime.
	caps["logcatFormat"] = "time"
	#Set the output filter rule for logcat messages since Appium 1.18.0. Please read logcat#filteringOutput for more details about the rule. Write and View Logs with Logcat is also helpful.
	caps["logcatFilterSpecs"] = ['*:E']
	#在每次会话开始时清除logcat日志
	caps["clearDeviceLogsOnStart"] = True
	caps["chromeOptions"] = {"w3c": False}
	driver = webdriver.Remote('http://localhost:4444/wd/hub', caps)
	driver.implicitly_wait(60)

	return driver
```
YZB_CB_HKT_case_01.py:
```
LP=LoginPage(self.logging)

        #登录耘智保
        LP.login_by_sss(self.driver)

        self.logging.info("*********************首页*********************")

        IDP = CBIndexPage(self.logging)
        #检测是否在正确的账号下，不是就切换
        CheckIsRightAccount().check_account(self)

        # 点击清单管理
        IDP.click_menu(self.driver, self.data['nav_menu'])

        self.logging.info("*********************新建验标页面*********************")

        LSP=ListStandardPage(self.logging)

        #选择投保方式
        LSP.click_standard_type(self.driver,'投保方式','个体投保')
```
ListStandardPage.py:
```
def click_standard_type(self,driver,title,val):
        self.logging.info('*投保方式*-%s'%val)
        wait(driver,2)
        # id_name = ''
        # if val =='个人投保':
        #     id_name = 'com.picc.nx:id/rb_private'
        # else:
        #     id_name = "com.picc.nx:id/rb_public"
        ele = scroll_to_element2(driver,'xpath','//android.widget.RadioButton[contains(@text,"'+val+'")]',{'class':'android.widget.ScrollView'})
        
        if attr(ele,'checked')=="false":
            ele.click()
```
common.py:
```
def scroll_to_begin(driver,d1={},direction="V",maxSwipe="30"):
    '''滑动顶部'''
    # flingToEnd
    #d1={"id":'com.picc.nmms:id/tv_usenaturecode',"class":android.widget.TextView,"text":'211-家庭自用汽车',"scrollable":'false',"index":'0'},d1为scrollable=True的元素的属性,注意scrollable必选在index前面
    #direction:滑动方向 H-->水平， V-->垂直
    #maxSwipe:最大滑动次数，默认是30次
    str1="new UiScrollable(new UiSelector()"
    for key,value in d1.items():
        if key=='id':
            str1+='.resourceId(\"'+value+'\")'

        elif key=='class':
            str1+='.className(\"'+value+'\")'

        elif key=="text":
            str1+='.textContains(\"'+value+'\")'
        elif key=="scrollable":
            str1+=".scrollable("+value+")"
        elif key=="index":
            str1+='.instance('+value+')'
    str1+=")"
    if direction=="V":
        str1+=".setAsVerticalList()"
    else:
        str1+=".setAsHorizontalList()"
    str1+=".setMaxSearchSwipes("+maxSwipe+")"
    str1+=".flingToBeginning("+maxSwipe+")"
    e1=driver.find_element_by_android_uiautomator(str1)
    return e1

def scroll_to_element2(driver,method,value,d1={},num=1,maxSwipe=40,direction="V",noScrollArea=0.3):
    '''滑动并找到第N个重复属性的元素'''
    #d1：滑动容器
    #methd:要找元素的定位方法
    #value：要找元素的定位属性
    #num：要找第几个元素
    #例如：找确认页面的第二个名字，scroll_to_element2(driver,"id","com.picc.nmms:id/tv_insured_name",{"class":"android.widget.ScrollView","id":"com.picc.nmms:id/my_scrollview"},2)
    ID1=[]
    new1=[]
    scroll_to_begin(driver,d1)
    m=0
    driver.implicitly_wait(0)
    for i in get_elements(driver,method,value):
        if i.id not in ID1:
            new1.append(i)
            ID1.append(i.id)
    while len(new1)<num and m<maxSwipe:
        scroll_forward(driver,d1,direction=direction,noScrollArea=noScrollArea)
        for i in get_elements(driver,method,value):
            if i.id not in ID1:
                new1.append(i)
                ID1.append(i.id)
        m+=1
    if len(new1)<num:
        print("未找到指定元素！")
    driver.implicitly_wait(global_wait)
    return new1[num-1]
```
- error
```
ft1.1: Traceback (most recent call last):
  File "C:\Users\14221\Desktop\project-git\UITestAND_PICC_YZB\public\MyTestCase.py", line 27, in testPartExecutor
    yield
  File "C:\Users\14221\Desktop\project-git\UITestAND_PICC_YZB\public\MyTestCase.py", line 188, in run
    testMethod()
  File "C:\Users\14221\Desktop\project-git\UITestAND_PICC_YZB\public\common2.py", line 123, in wrapper
    func(self)
  File "C:\Users\14221\Desktop\project-git\UITestAND_PICC_YZB\public\common2.py", line 45, in wrapper
    func(self)
  File "C:\Users\14221\Desktop\project-git\UITestAND_PICC_YZB\test_case\YZB_CB_HKT_case_01.py", line 122, in test_case_01
    LSP.click_standard_type(self.driver,'投保方式','个体投保')
  File "C:\Users\14221\Desktop\project-git\UITestAND_PICC_YZB\test_page\ListStandardPage.py", line 23, in click_standard_type
    ele = scroll_to_element2(driver,'xpath','//android.widget.RadioButton[contains(@text,"'+val+'")]',{'class':'android.widget.ScrollView'})
  File "C:\Users\14221\Desktop\project-git\UITestAND_PICC_YZB\public\common.py", line 164, in scroll_to_element2
    scroll_to_begin(driver,d1)
  File "C:\Users\14221\Desktop\project-git\UITestAND_PICC_YZB\public\common.py", line 239, in scroll_to_begin
    e1=driver.find_element_by_android_uiautomator(str1)
  File "C:\Python39\lib\site-packages\appium\webdriver\extensions\search_context\android.py", line 171, in find_element_by_android_uiautomator
    return self.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value=uia_string)
  File "C:\Python39\lib\site-packages\appium\webdriver\webdriver.py", line 414, in find_element
    return self.execute(RemoteCommand.FIND_ELEMENT, {'using': by, 'value': value})['value']
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 418, in execute
    self.error_handler.check_response(response)
  File "C:\Python39\lib\site-packages\appium\webdriver\errorhandler.py", line 30, in check_response
    raise wde
  File "C:\Python39\lib\site-packages\appium\webdriver\errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: Unable to determine element locating strategy for -android uiautomator
```

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
I believe this error is thrown by the grid, which we don't have any control.

@diemol Do you have any hints there? Does grid reject custom locators by default?

**Comment by diemol** [comment]
I believe these custom locators are not working in Grid 4 because they are not W3C. However, there are ways to add them. We need to know which locators Appium uses so we can add them to Grid. @mykola-mokhnach, is there a place we can check for them? Or maybe you can share them here?

**Comment by mykola-mokhnach** [comment]
yes, I can do, but generally Appium allows to use any custom locators. The general agreement is these usually start with single dash (`-`) character

**Comment by mykola-mokhnach** [comment]
I assume https://github.com/appium/java-client/blob/master/src/main/java/io/appium/java_client/AppiumBy.java contains all custom locator strategies we have so far

**Comment by jlipps** [comment]
> The general agreement is these usually start with a single dash (-) character

At one point I think this was officially supported in the spec, however I don't see anything mentioning it there now. I know I heard about this rule from one of the Selenium devs, maybe Simon? At any rate, all Appium's non-W3C locator strategies start with `-` (although in some cases appium still supports pre-W3C strategies under their usual rendering, e.g., `name`)

**Comment by jevgenijsklimovs** [comment]
Any hints how to make it work on GRID 4?

**Comment by titusfortner** [comment]
@jlipps how hard would it be to move non w3c locators to use an appium name spaced endpoint?

Spec says

If location strategy is not present as a keyword in the [table of location strategies](https://w3c.github.io/webdriver/#dfn-table-of-location-strategies), return [error](https://w3c.github.io/webdriver/#dfn-error) with [error code](https://w3c.github.io/webdriver/#dfn-error-code) [invalid argument](https://w3c.github.io/webdriver/#dfn-invalid-argument).

**Comment by jlipps** [comment]
It would be unreasonably difficult. Everything out there assumes the standard /element endpoint for finding elements. My understanding of the spec was that there was allowance for custom locator strategies. If that's not the case then I think this is one area where Appium will not be spec compliant. Unfortunately it makes the spec non extensible to insist on a small set of web-only locators.

**Comment by titusfortner** [comment]
Yeah looks like as of October 2016 — https://github.com/w3c/webdriver/commit/cfb2083a1c1de231ee1b89a6f1cae66ddf83f3b2

Selenium bindings have been supporting non-compliant locators, but they convert them into compliant locators when sending to selenium grid/drivers. 

How much processing does Appium server do? Could Appium accept a POST to `session-id/appium/element` and just redirect it to `session-id/element` for the various appium drivers? Then it would just need to be the bindings parsing the locator strategy and sending to the appium endpoint if not on w3c list?

Unless I'm missing something (I'm probably missing something) it seems annoying but straightforward?

Otherwise maybe we can raise the issue with the spec. Would it be easier to change the appium locators to have keys like `appium:accessibility-id`, etc?

**Comment by mykola-mokhnach** [comment]
Unfortunately it's not the case in Appium that we could easily convert one locator to another. Different locator types have different performance and sometimes they are also not interchangeable.

**Comment by titusfortner** [comment]
Right, I'm not suggesting that as an option, just describing what Selenium does to make it seem like we support non-compliant locators.

I chatted with @jlipps and I understand now that the server is only deciding which driver processes the requests, so a new endpoint would need to be created in each of them, even if the logic is just to send the payload to the original endpoint.

It would be doable and I can think of a couple strategies to maintain backwards compatibility even, but the easiest fix would be if we could change the spec, so I raised an issue and we can see what the rest of the working group says — https://github.com/w3c/webdriver/issues/1649

**Comment by primus11** [comment]
In Java same error causes StackOverflowError (adding here so that other can find this issue faster)

`        at io.appium.java_client.AppiumBy.findElement(AppiumBy.java:45)
        at org.openqa.selenium.remote.ElementLocation$ElementFinder$1.findElement(ElementLocation.java:136)
        at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:80)
        at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:367)
        at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:359)
        at io.appium.java_client.AppiumBy.findElement(AppiumBy.java:45)
        at org.openqa.selenium.remote.ElementLocation$ElementFinder$1.findElement(ElementLocation.java:136)
        at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:80)
        at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:367)
        at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:359)`

**Comment by nocomply78** [comment]
> Some updates here. We have some code in a [PR for Grid](https://github.com/SeleniumHQ/selenium/pull/10790), but we do not want to merge that before the spec is fixed, and there is a [PR for that](https://github.com/w3c/webdriver/pull/1671) too.
> 
> Will share updates here when something new comes up.

Given that it looks like there's [no need to change the spec](https://github.com/w3c/webdriver/pull/1671#issuecomment-1183475796), am I right in thinking that the PR for Grid may get merged soon?
Or some other approach will be taken instead?
I'm really keen to upgrade to Selenium & Grid 4, but have been unable to do so because of my reliance on Appium for both mobile & Windows driver-related tests.
It's really good to see some progress on this conversation though :-)

**Comment by diemol** [comment]
We need to make changes in the Grid but they will be smaller. We will work on that in the next couple of weeks. Next Selenium release is targeted to be during the first week of August.

**Comment by mykola-mokhnach** [comment]
I assume the original issue has been addressed in the recent grid releases. Closing as fixed.
