### ISSUE TITLE
Error: The session with id 'undefined' does not exist

### ISSUE THREAD

**Issue by StephanB75** [appium/appium#16736]
## The problem

Since yesterday evening my tests throwing this error

## Environment

* Appium version (or git revision) that exhibits the issue: beta27/beta28
* Last Appium version that did not exhibit the issue (if applicable): beta27
* Desktop OS/version used to run Appium: Monterey
* Node.js version (unless using Appium.app|exe): 14
* Npm or Yarn package manager: 6.14
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI

## Details

The server is started via AppiumServiceBuilder in java

## Link to Appium logs

```
2022-04-08 08:24:35:798 - [Appium] Attempting to load plugin images...
2022-04-08 08:24:35:800 - [debug] [Appium] Requiring plugin at /Users/jenkins/HomeOfQA/workspace/RMA-iOS-Versions/uitesting/.appium/node_modules/@appium/images-plugin
2022-04-08 08:24:37:030 - [Appium] Welcome to Appium v2.0.0-beta.28 (REV 28603c381745d77b6e6efb8b70e8de870638eb29)
2022-04-08 08:24:37:032 - [Appium] Non-default server args:
2022-04-08 08:24:37:034 - [Appium] { address: '127.0.0.1',
2022-04-08 08:24:37:034 - [Appium]   allowInsecure: [ 'adb_shell' ],
2022-04-08 08:24:37:035 - [Appium]   localTimezone: true,
2022-04-08 08:24:37:035 - [Appium]   logTimestamp: true,
2022-04-08 08:24:37:035 - [Appium]   port: 4727,
2022-04-08 08:24:37:035 - [Appium]   usePlugins: [ 'images' ] }
2022-04-08 08:24:37:035 - [Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
2022-04-08 08:24:37:035 - [Appium] { 'appium:noReset': 'false' }
2022-04-08 08:24:37:036 - [Appium] Attempting to load driver xcuitest...
2022-04-08 08:24:37:038 - [debug] [Appium] Requiring driver at /Users/jenkins/HomeOfQA/workspace/RMA-iOS-Versions/uitesting/.appium/node_modules/appium-xcuitest-driver
2022-04-08 08:24:38:485 - [Appium] Appium REST http interface listener started on 127.0.0.1:4727
2022-04-08 08:24:38:486 - [Appium] Available drivers:
2022-04-08 08:24:38:486 - [Appium]   - xcuitest@4.3.5 (automationName 'XCUITest')
2022-04-08 08:24:38:486 - [Appium] Available plugins:
2022-04-08 08:24:38:486 - [Appium]   - images@1.2.4 (ACTIVE)
2022-04-08 08:24:38:498 - [HTTP] --> GET /status
2022-04-08 08:24:38:498 - [HTTP] {}
2022-04-08 08:24:38:499 - [debug] [AppiumDriver@1229] Calling AppiumDriver.getStatus() with args: []
2022-04-08 08:24:38:523 - [debug] [AppiumDriver@1229] Encountered internal error running command: Error: The session with id 'undefined' does not exist
2022-04-08 08:24:38:523 - [debug] [AppiumDriver@1229]     at AppiumDriver.executeCommand (/Users/jenkins/HomeOfQA/workspace/RMA-iOS-Versions/uitesting/node_modules/appium/lib/appium.js:549:15)
2022-04-08 08:24:38:523 - [debug] [AppiumDriver@1229]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
2022-04-08 08:24:38:523 - [debug] [AppiumDriver@1229]     at asyncHandler (/Users/jenkins/HomeOfQA/workspace/RMA-iOS-Versions/uitesting/node_modules/@appium/base-driver/lib/protocol/protocol.js:313:19)
2022-04-08 08:24:38:540 - [HTTP] <-- GET /status 500 41 ms - 716
```

**Comment by StephanB75** [comment]
@mykola-mokhnach 
Do i have to install a different version as beta.28 to get this fix ?
Because i still get the same error when starting the tests.
Appium and drivers are fresh installs every test run.

**Comment by mykola-mokhnach** [comment]
The only way to get the update is to publish a new server version

**Comment by StephanB75** [comment]
@jlipps 
can you please release a new beta version with that fix ? because its completely blocking my current release tests :(

**Comment by alei01** [comment]
> @jlipps can you please release a new beta version with that fix ? because its completely blocking my current release tests :(
I haven't faced this issue with the previous versions, so as a possible workaround you could downgrade the appium to beta-26 (as far as I remember it worked for me)

**Comment by jlipps** [comment]
beta 29 has been published

**Comment by StephanB75** [comment]
Seems to be fixed with beta@30
Thank you @jlipps for the quick release
