### ISSUE TITLE
supportedLogTypes does not get assigned properly on driver init since beta27

### ISSUE THREAD

**Issue by mykola-mokhnach** [appium/appium#16738]
## The problem

After base driver update to 8.4.0 `getLogTypes` and `getLog` commands of appium-android-driver stopped working properly because `this.supportedLogTypes` property does not get initialized. I assume this is related to the recent typing refactoring in `base-driver/lib/basedriver/commands/log.js`. Previously this variable has been assigned by defining `extensions.supportedLogTypes`, which was equal to `{}` by default and is overridden in each driver if necessary. Now it always equals to `{}`. See https://dev.azure.com/AppiumCI/Appium%20CI/_build/results?buildId=20705&view=logs&j=12e12a94-6f82-50bd-49c9-566fb2052675&t=7ba1c276-5935-513a-f217-d07020732771 for more details.

## Environment

* Appium version (or git revision) that exhibits the issue: base-driver 8.3.0
* Last Appium version that did not exhibit the issue (if applicable): base-driver 8.4.0
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

**Comment by boneskull** [comment]
still trying to figure this one out.  I'm having trouble reproducing it for our fake driver...

**Comment by mykola-mokhnach** [comment]
> still trying to figure this one out. I'm having trouble reproducing it for our fake driver...

you could test it on my branch: https://github.com/appium/appium-android-driver/pull/735

**Comment by boneskull** [comment]
I can reproduce for appium-android-driver, but I am unsure what the minimal reproducible example is, which is why I was trying w/ fake-driver.

**Comment by StephanB75** [comment]
@mykola-mokhnach 
is that error in the log below, the issue you are talking about here ?
`
2022-04-13 07:53:00:409 - [HTTP] --> POST /session/c67e667d-5bc7-4ca8-be98-8d1cd7c7d7da/se/log
2022-04-13 07:53:00:409 - [HTTP] {"type":"logcat"}
2022-04-13 07:53:00:410 - [debug] [AndroidUiautomator2Driver@decd (c67e667d)] Calling AppiumDriver.getLog() with args: ["logcat","c67e667d-5bc7-4ca8-be98-8d1cd7c7d7da"]
2022-04-13 07:53:00:410 - [AppiumDriver@cb49] Plugins which can handle cmd 'getLog': images
2022-04-13 07:53:00:410 - [AppiumDriver@cb49] Plugin images is now handling cmd 'getLog'
2022-04-13 07:53:00:410 - [AppiumDriver@cb49] Executing default handling behavior for command 'getLog'
2022-04-13 07:53:00:410 - [debug] [AndroidUiautomator2Driver@decd (c67e667d)] Retrieving 'logcat' logs
2022-04-13 07:53:00:410 - [debug] [AndroidUiautomator2Driver@decd (c67e667d)] Retrieving supported log types
2022-04-13 07:53:00:411 - [debug] [AndroidUiautomator2Driver@decd (c67e667d)] Encountered internal error running command: Error: Unsupported log type 'logcat'. Supported types: {}
2022-04-13 07:53:00:411 - [debug] [AndroidUiautomator2Driver@decd (c67e667d)]     at AndroidUiautomator2Driver.getLog (/Users/jenkins/HomeOfQA/workspace/RMA-Android-Stage-Java-Releases/uitesting/.appium/node_modules/appium-uiautomator2-driver/node_modules/@appium/base-driver/lib/basedriver/commands/log.js:42:15)
2022-04-13 07:53:00:411 - [debug] [AndroidUiautomator2Driver@decd (c67e667d)]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
2022-04-13 07:53:00:411 - [debug] [AndroidUiautomator2Driver@decd (c67e667d)]     at AndroidUiautomator2Driver.getLog (/Users/jenkins/HomeOfQA/workspace/RMA-Android-Stage-Java-Releases/uitesting/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/log.js:137:10)`

**Comment by mykola-mokhnach** [comment]
> is that error in the log below, the issue you are talking about here ?

@StephanB75 Yes, it's the same

**Comment by StephanB75** [comment]
Ok thank you, than it still occurs in beta@30 
I hope you will find a solution

**Comment by StephanB75** [comment]
@mykola-mokhnach 
Is it known that this also occurs vor iOS logging ? (noticed this some minutes ago)
`Session ID: a97acc72-d85f-4e86-b414-4aab5bce1789
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:180)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:558)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:613)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:263)
	at org.openqa.selenium.remote.RemoteExecuteMethod.execute(RemoteExecuteMethod.java:40)
	at org.openqa.selenium.remote.RemoteLogs.getRemoteEntries(RemoteLogs.java:81)
	at org.openqa.selenium.remote.RemoteLogs.get(RemoteLogs.java:77)
	at iOS_ross.helpers.Helpers.captureLog(Helpers.java:1378)
	at iOS_ross.helpers.TestFlow.testWatcherFailed(TestFlow.java:102)
	at iOS_ross.Backend_Test$1.failed(Backend_Test.java:66)
	at org.junit.rules.TestWatcher.failedQuietly(TestWatcher.java:84)
	at org.junit.rules.TestWatcher.access$300(TestWatcher.java:46)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:62)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:236)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Unsupported log type 'crashlog'. Supported types: {}
Build info: version: '4.1.2', revision: '9a5a329c5a'
System info: host: 'ebwao-ciios03.intern.rossmann.de', ip: 'fe80:0:0:0:c33:57be:42df:d110%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '1.8.0_312'
Driver info: io.appium.java_client.ios.IOSDriver
Command: [a97acc72-d85f-4e86-b414-4aab5bce1789, getLog {type=crashlog}]`

**Comment by mykola-mokhnach** [comment]
Ofc, the original bug was introduced in the base driver, so all other drivers that depend on it would experience the same

**Comment by boneskull** [comment]
Resolved in #16829
