### ISSUE TITLE
appium should be a peer dep of extentensions

### ISSUE THREAD

**Issue by JuanCarlos-Arceredillo** [appium/appium#16747]
## The problem

I have made some tries to run tests on iOS using XCUiTest and on Android using Espresso with Appium 2.0, but each time that I try to create the session, Appium shows an internal error.

## Environment

* Appium version v2.0.0-beta 28:
* Node.js version: v14.17.0
* Npm or Yarn package manager: NPM
* Mobile platform/version under test: iOS & Android
* Real device or emulator/simulator: Simulator & Device
* Appium CLI or Appium.app|exe: Appium command line

## Details

I have installed the drivers:
- xcuitest version 4.3.5
- uiautomator2 version 2.0.7
- espresso verision 2.2.1

iOS
`
[debug] [AppiumDriver@94a2] Event 'newSessionRequested' logged at 1649674844863 (13:00:44 GMT+0200 (Central European Summer Time))
[Appium] Attempting to find matching driver for automationName 'XCUITest' and platformName 'iOS'
[Appium] The 'xcuitest' driver was installed and matched caps.
[Appium] Will require it at /Users/SYS_CIBER_ADMIN/.appium/node_modules/appium-xcuitest-driver
[debug] [Appium] Requiring driver at /Users/SYS_CIBER_ADMIN/.appium/node_modules/appium-xcuitest-driver
[AppiumDriver@94a2] Appium v2.0.0-beta.28 creating new XCUITestDriver (v4.3.5) session
[AppiumDriver@94a2] Checking BaseDriver versions for Appium and XCUITestDriver
[AppiumDriver@94a2] Appium's BaseDriver version is 8.4.0
[AppiumDriver@94a2] XCUITestDriver's BaseDriver version is 8.3.1
[debug] [AppiumDriver@94a2] Event 'newSessionStarted' logged at 1649674844867 (13:00:44 GMT+0200 (Central European Summer Time))

[debug] [AppiumDriver@94a2] Encountered internal error running command: TypeError: driverInstance.assignServer is not a function
[debug] [AppiumDriver@94a2]     at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:282:22)
[debug] [AppiumDriver@94a2]     at commandExecutor (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.js:74:9)
[debug] [AppiumDriver@94a2]     at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.js:94:15)
[debug] [AppiumDriver@94a2]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
[debug] [AppiumDriver@94a2]     at defaultBehavior (/usr/local/lib/node_modules/appium/lib/appium.js:601:16)
[debug] [AppiumDriver@94a2]     at AppiumDriver.executeWrappedCommand (/usr/local/lib/node_modules/appium/lib/appium.js:683:16)
[debug] [AppiumDriver@94a2]     at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/lib/appium.js:612:17)
[debug] [AppiumDriver@94a2]     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:313:19)
[HTTP] <-- POST /wd/hub/session 500 7 ms - 589
`

Android
`
[debug] [AppiumDriver@94a2] Event 'newSessionRequested' logged at 1649675270462 (13:07:50 GMT+0200 (Central European Summer Time))
[Appium] Attempting to find matching driver for automationName 'Espresso' and platformName 'android'
[Appium] The 'espresso' driver was installed and matched caps.
[Appium] Will require it at /Users/SYS_CIBER_ADMIN/.appium/node_modules/appium-espresso-driver
[debug] [Appium] Requiring driver at /Users/SYS_CIBER_ADMIN/.appium/node_modules/appium-espresso-driver
[AppiumDriver@94a2] Appium v2.0.0-beta.28 creating new EspressoDriver (v2.2.1) session
[AppiumDriver@94a2] Checking BaseDriver versions for Appium and EspressoDriver
[AppiumDriver@94a2] Appium's BaseDriver version is 8.4.0
[AppiumDriver@94a2] EspressoDriver's BaseDriver version is 8.3.1
[debug] [AppiumDriver@94a2] Event 'newSessionStarted' logged at 1649675270465 (13:07:50 GMT+0200 (Central European Summer Time))

[debug] [AppiumDriver@94a2] Encountered internal error running command: TypeError: driverInstance.assignServer is not a function
[debug] [AppiumDriver@94a2]     at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:282:22)
[debug] [AppiumDriver@94a2]     at commandExecutor (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.js:74:9)
[debug] [AppiumDriver@94a2]     at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.js:94:15)
[debug] [AppiumDriver@94a2]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
[debug] [AppiumDriver@94a2]     at defaultBehavior (/usr/local/lib/node_modules/appium/lib/appium.js:601:16)
[debug] [AppiumDriver@94a2]     at AppiumDriver.executeWrappedCommand (/usr/local/lib/node_modules/appium/lib/appium.js:683:16)
[debug] [AppiumDriver@94a2]     at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/lib/appium.js:612:17)
[debug] [AppiumDriver@94a2]     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:313:19)
[HTTP] <-- POST /wd/hub/session 500 7 ms - 589
`

## Code To Reproduce Issue [ Good To Have ]
I run Appium from a terminal with this command:

`
Appium -pa /wd/hub
`

And I'm launching the sessions from the Appium-Inspector with the following capabilities

iOS
`
{
  "platformName": "iOS",
  "appium:deviceName": "iPhone 11 Pro Max",
  "appium:automationName": "XCUITest",
  "appium:language": "es",
  "appium:locale": "ES",
  "appium:platformVersion": "14.2"
}
`

Android
`
{
  "platformName": "Android",
  "appium:deviceName": "pixel_2_9_0",
  "appium:automationName": "Espresso",
  "appium:language": "es",
  "appium:locale": "ES",
  "appium:app": "MY_APK_FILE",
}
`

If I do the same tests with the Appium Desktop v1.21 or v1.22.2, I can create the session and connect with Appium properly.

**Comment by mykola-mokhnach** [comment]
> [AppiumDriver@94a2] Appium's BaseDriver version is 8.4.0
> [AppiumDriver@94a2] XCUITestDriver's BaseDriver version is 8.3.1

This basically creates the issue. Upgrade the driver to the most recent version, which depends on Base driver 8.4.0 and the issue will be fixed.

cc @jlipps @boneskull 
This is a nice example of what could happen if a breaking change is added to the base driver in `@appium/appium`

**Comment by mykola-mokhnach** [comment]
Perhaps, it would make sense to make base driver dependency in appium drivers transitive, so it always uses one from the server deployment.

**Comment by shaky** [comment]
thank you for the reply @mykola-mokhnach, how do I do the update? thanks

**Comment by shaky** [comment]
tried that already (guessing you're talking about `appium driver install xcuitest `)

I did the following:
`rm -rf ~/.appium`
`npm uninstall -g appium`
`npm install -g appium@next`
`appium plugin install relaxed-caps`
`appium driver install xcuitest `

then started appium using `appium --base-path /wd/hub --use-plugins=relaxed-caps`

and I get the same error `driverInstance.assignServer is not a function`

Thank you

**Comment by mykola-mokhnach** [comment]
Maybe NPM caches the stuff. Try to reset its [cache](https://coder-coder.com/npm-clear-cache/) before installing the stuff. Also, make sure no driver leftovers are present in the appium home folder (usually $HOME/.appium)

**Comment by shaky** [comment]
hi @mykola-mokhnach, thank you for your replies.

I've tried cleaning the npm cache and I get the same output. I even tried to after clean npm install.

**Comment by jlipps** [comment]
> This basically creates the issue. Upgrade the driver to the most recent version, which depends on Base driver 8.4.0+ and the issue will be fixed.

Yes, that's one reason I added that logging. I was thinking we should add something in the appium manifest in package.json for drivers that allow for specifying min basedriver versions, so a nice error can be presented to the user by the server, instead of whatever random conflict pops up.

**Comment by mykola-mokhnach** [comment]
> hi @mykola-mokhnach, thank you for your replies.
> 
> I've tried cleaning the npm cache and I get the same output. I even tried to after clean npm install.

I've just published a new xcuitest driver's patch, which bumps the minimum base driver version. Try to reinstall it now

**Comment by mykola-mokhnach** [comment]
> > This basically creates the issue. Upgrade the driver to the most recent version, which depends on Base driver 8.4.0+ and the issue will be fixed.
> 
> Yes, that's one reason I added that logging. I was thinking we should add something in the appium manifest in package.json for drivers that allow for specifying min basedriver versions, so a nice error can be presented to the user by the server, instead of whatever random conflict pops up.

What bothers me in this situation is that there is no clean path to resolve such issues. Let say one has appium server version X  installed with a couple of drivers. Then the server gets updated to version X+1, but drivers remain the same. How should the updated server behave in such situation? What would be the user's strategy to resolve the issue?

**Comment by boneskull** [comment]
this is how many plugin systems work in JS land, anyway. we could expose Basedriver thru Appium, as a class, but this way the driver would always use whatever basedriver comes with appium

**Comment by mykola-mokhnach** [comment]
> this is how many plugin systems work in JS land, anyway. we could expose Basedriver thru Appium, as a class, but this way the driver would always use whatever basedriver comes with appium

I would prefer this strategy

**Comment by boneskull** [comment]
> I would prefer this strategy. Although there still should be a clear strategy on what to do if base driver gets some breaking changes

If base driver gets breaking changes, then appium gets breaking changes.

another way to mitigate _some_ risk is to remove `DriverCore`, put all that stuff back into `BaseDriverCore`, and copy/paste whatever `AppiumDriver` needs (or, alternatively, put all that stuff into mixins and compose the classes). this would break the inheritance chain and allow us more wiggle room with `AppiumDriver` (though it wouldn't have avoided this particular problem).

anyhow, using the peerdependencies thing could work, but may require some extra attention given that `npm install my-driver` will automatically install `appium` for later versions of npm, and if that command happens to run in `~/.appium`--now the user has two `appium`s.  there's a flag to disable this behavior, anyhow.  the peer dep essentially functions as "minimal supported appium version" for the driver, and we could check that value the actual install step of `appium driver install` to ensure that the currently-running appium satisfies the constraint.  a user running `npm install my-driver` instead will get the standard messaging from `npm` about an invalid peer dep.

**Comment by boneskull** [comment]
> 
What bothers me in this situation is that there is no clean path to resolve such issues. Let say one has appium server version X installed with a couple of drivers. Then the server gets updated to version X+1, but drivers remain the same. How should the updated server behave in such situation? What would be the user's strategy to resolve the issue?

With the peer dep strategy, if the semver constraint was satisfied, there would be no issue. but if it wasn't, the user will be prompted to either a) upgrade the driver (we should be able to re-use the "outdated" check here) if applicable, or b) downgrade the server if there is no newer driver version.

**Comment by mykola-mokhnach** [comment]
> > What bothers me in this situation is that there is no clean path to resolve such issues. Let say one has appium server version X installed with a couple of drivers. Then the server gets updated to version X+1, but drivers remain the same. How should the updated server behave in such situation? What would be the user's strategy to resolve the issue?
> 
> With the peer dep strategy, if the semver constraint was satisfied, there would be no issue. but if it wasn't, the user will be prompted to either a) upgrade the driver (we should be able to re-use the "outdated" check here) if applicable, or b) downgrade the server if there is no newer driver version.

Would you have some time to implement such approach? I don't have much exp with NPM infra to make that magic become reality.

**Comment by boneskull** [comment]
Yeah, I'll put it on my list

**Comment by rurikoaraki** [comment]
> Hi all, I'm running into a similar issue with the appium-windows-driver and the 28 beta update. The installed version 2.0.1 resolves the base driver version to 8.2.4 according to the shrinkwrap file in the package that gets installed. Would it be possible to get a similar fix on the windows driver as well so I can update to the latest beta version?

I think someone pushed out a new version of the package for a separate reason and the version of the base driver is now 8.4.0 for the windows driver, so this is now resolved.

**Comment by jlipps** [comment]
Just weighing in on the peer dependency approach. Something like that can probably work. In the past drivers were standalone, so we didn't envision that model. 

An alternative would be to have drivers explicitly say in the manifest the latest known version of basedriver they support, and if basedriver has been updated with some kind of breaking change, appium can flag a warning saying the driver's not compatible. but if we can transparently manage the peer dependency stuff so that's not a big issue for users, it's probably the way to go, as it is semantically what we are trying to achieve.

**Comment by JuanCarlos-Arceredillo** [comment]
Hi all,

I have tried updating the iOS driver with the command

`
appium driver update xcuitest
`

and after updating from the version 4.3.5 to the 4.3.7. It seems that at least this driver is correct.
Nevertheless, I'm trying just to open an App on an iOS simulator with the Appium Inspector and I'm facing several issues.

- The simulator isn't opened as with Appium server GUI.
- Appium log shows this error message `Encountered internal error running command: Error: The simulator EFDBA3DC-1DC9-48AB-9955-C86D904B4FED has failed to finish booting after 120s.`
- The appium Inspector reports a timeout error.

After a while, it seems that Appium tries again to install the WDA on the simulator and it starts the common connecting retries like:

`
Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
connect ECONNREFUSED 127.0.0.1:8100
`

But instead to opening the simulator or connecting as it's the normal workflow with Appium 1.X.
Maybe it's all related to the issue that the simulator is not opened, but I'm not sure. I have also tried opening manually the simulator but the behavior is the same.

Please, if you prefer to split this issue in a different thread to not mix things, I can open a new one with this information.

Thank you for your support.

**Comment by jlipps** [comment]
@JuanCarlos-Arceredillo that's a separate issue, do you mind opening a new issue so we can treat it on its own.

**Comment by boneskull** [comment]
> An alternative would be to have drivers explicitly say in the manifest the latest known version of basedriver they support

that's exactly what `peerDependencies` does.  the advantage with `peerDependencies` is if a user is using `npm` to install drivers, they will get the extra checks npm performs when it cannot resolve a conflict.  but when using `appium driver install`, we will still need to figure it out.  in other words, if we _don't_ use `peerDependencies`, _unless appium performs these checks on startup_ (instead of just at install time), those users installing extensions via `npm` will get runtime errors, like they do now.

**Comment by boneskull** [comment]
anyway, I think this one is going to be my next task.  it may take some time, so if users are blocking, I would suggest reverting the addition of `assignServer()`, and instead assign the properties explicitly.

**Comment by boneskull** [comment]
For those if you running into this, #16797 will workaround the issue for now.  I'll update this issue when it's released, but will be working on a proper solution otherwise.

**Comment by attrideepak** [comment]
Is this resolved? I am getting the same issue.
`2022-04-20 06:37:38:725 [Appium] Welcome to Appium v2.0.0-beta.30 (REV 5b3d188b83f27ec31d97f3f3e6e49220e09b6985)
2022-04-20 06:37:38:728 [Appium] Non-default server args:
2022-04-20 06:37:38:730 [Appium] { allowInsecure: [ 'chromedriver_autodownload' ], port: 65043 }
2022-04-20 06:37:38:730 [Appium] Attempting to load driver espresso...
2022-04-20 06:37:38:732 [Appium] Requiring driver at /Users/deepak.attri/.appium/node_modules/appium-espresso-driver
2022-04-20 06:37:39:856 [Appium] Attempting to load driver xcuitest...
2022-04-20 06:37:39:857 [Appium] Requiring driver at /Users/deepak.attri/.appium/node_modules/appium-xcuitest-driver
2022-04-20 06:37:41:335 [Appium] Appium REST http interface listener started on 0.0.0.0:65043
2022-04-20 06:37:41:336 [Appium] Available drivers:
2022-04-20 06:37:41:336 [Appium]   - espresso@2.2.1 (automationName 'Espresso')
2022-04-20 06:37:41:336 [Appium]   - xcuitest@4.4.0 (automationName 'XCUITest')
2022-04-20 06:37:41:337 [Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.
2022-04-20 06:37:42:119 [HTTP] --> GET /status
2022-04-20 06:37:42:119 [HTTP] {}
2022-04-20 06:37:42:121 [AppiumDriver@cc1e] Calling AppiumDriver.getStatus() with args: []
2022-04-20 06:37:42:122 [AppiumDriver@cc1e] Responding to client with driver.getStatus() result: {"build":{"version":"2.0.0-beta.30","git-sha":"5b3d188b83f27ec31d97f3f3e6e49220e09b6985","built":"2021-10-07 10:11:35 -0700"}}
2022-04-20 06:37:42:127 [HTTP] <-- GET /status 200 7 ms - 136
2022-04-20 06:37:42:127 [HTTP] 
2022-04-20 06:37:42:135 [HTTP] --> GET /status
2022-04-20 06:37:42:135 [HTTP] {}
2022-04-20 06:37:42:135 [AppiumDriver@cc1e] Calling AppiumDriver.getStatus() with args: []
2022-04-20 06:37:42:136 [AppiumDriver@cc1e] Responding to client with driver.getStatus() result: {"build":{"version":"2.0.0-beta.30","git-sha":"5b3d188b83f27ec31d97f3f3e6e49220e09b6985","built":"2021-10-07 10:11:35 -0700"}}
2022-04-20 06:37:42:137 [HTTP] <-- GET /status 200 1 ms - 136
2022-04-20 06:37:42:137 [HTTP] 
2022-04-20 06:37:45:288 [HTTP] Request idempotency key: 18b3bca5-1790-4bcc-92b9-097b6c9618fd
2022-04-20 06:37:45:301 [HTTP] --> POST /session
2022-04-20 06:37:45:301 [HTTP] {"capabilities":{"firstMatch":[{}],"alwaysMatch":{"appium:allowTestPackages":true,"appium:app":"/Users/deepak.attri/Documents/grab-automation/dakota-test-automation/apps/digibank.apk","appium:appWaitActivity":"com.grab.digibank.sdk.auth.internal.ui.HostActivity","appium:automationName":"Espresso","appium:deviceName":"nexus","appium:espressoBuildConfig":"{\n  \"additionalAndroidTestDependencies\": [\n    \"androidx.core:core-ktx:1.5.0\",\n    \"androidx.activity:activity-ktx:1.2.0-beta01\"\n  ],\n  \"additionalAppDependencies\": [\n    \"org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.10\",\n    \"org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.0\",\n    \"androidx.compose.ui:ui:1.1.0-rc01\"\n  ],\n  \"toolsVersions\": {\n    \"kotlin\": \"1.6.10\",\n    \"minSdk\": \"26\",\n    \"compileSdk\": \"31\"\n  }\n}","appium:forceEspressoRebuild":true,"appium:showGradleLog":true,"appium:udid":"emulator-5554","platformName":"android"}}}
2022-04-20 06:37:45:302 [AppiumDriver@cc1e] Calling AppiumDriver.createSession() with args: [null,null,{"firstMatch":[{}],"alwaysMatch":{"appium:allowTestPackages":true,"appium:app":"/Users/deepak.attri/Documents/grab-automation/dakota-test-automation/apps/digibank.apk","appium:appWaitActivity":"com.grab.digibank.sdk.auth.internal.ui.HostActivity","appium:automationName":"Espresso","appium:deviceName":"nexus","appium:espressoBuildConfig":"{\n  \"additionalAndroidTestDependencies\": [\n    \"androidx.core:core-ktx:1.5.0\",\n    \"androidx.activity:activity-ktx:1.2.0-beta01\"\n  ],\n  \"additionalAppDependencies\": [\n    \"org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.10\",\n    \"org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.0\",\n    \"androidx.compose.ui:ui:1.1.0-rc01\"\n  ],\n  \"toolsVersions\": {\n    \"kotlin\": \"1.6.10\",\n    \"minSdk\": \"26\",\n    \"compileSdk\": \"31\"\n  }\n}","appium:forceEspressoRebuild":true,"appium:showGradleLog":true,"appium:udid":"emulator-5554","platformName":"android"}}]
2022-04-20 06:37:45:303 [AppiumDriver@cc1e] Event 'newSessionRequested' logged at 1650436665302 (12:07:45 GMT+0530 (India Standard Time))
2022-04-20 06:37:45:306 [Appium] Attempting to find matching driver for automationName 'Espresso' and platformName 'android'
2022-04-20 06:37:45:307 [Appium] The 'espresso' driver was installed and matched caps.
2022-04-20 06:37:45:307 [Appium] Will require it at /Users/deepak.attri/.appium/node_modules/appium-espresso-driver
2022-04-20 06:37:45:307 [Appium] Requiring driver at /Users/deepak.attri/.appium/node_modules/appium-espresso-driver
2022-04-20 06:37:45:307 [AppiumDriver@cc1e] Appium v2.0.0-beta.30 creating new EspressoDriver (v2.2.1) session
2022-04-20 06:37:45:307 [AppiumDriver@cc1e] Checking BaseDriver versions for Appium and EspressoDriver
2022-04-20 06:37:45:307 [AppiumDriver@cc1e] Appium's BaseDriver version is 8.4.2
2022-04-20 06:37:45:307 [AppiumDriver@cc1e] EspressoDriver's BaseDriver version is 8.3.1
2022-04-20 06:37:45:309 [AppiumDriver@cc1e] Explicitly enabling use of insecure features:
2022-04-20 06:37:45:310 [AppiumDriver@cc1e]     chromedriver_autodownload
2022-04-20 06:37:45:311 [AppiumDriver@cc1e] Event 'newSessionStarted' logged at 1650436665311 (12:07:45 GMT+0530 (India Standard Time))
2022-04-20 06:37:45:328 [AppiumDriver@cc1e] Encountered internal error running command: TypeError: driverInstance.assignServer is not a function
2022-04-20 06:37:45:329 [AppiumDriver@cc1e]     at AppiumDriver.createSession (/Users/deepak.attri/.nvm/versions/node/v17.3.0/lib/node_modules/appium/lib/appium.js:280:22)
2022-04-20 06:37:45:329 [AppiumDriver@cc1e]     at commandExecutor (/Users/deepak.attri/.nvm/versions/node/v17.3.0/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.js:74:9)
2022-04-20 06:37:45:329 [AppiumDriver@cc1e]     at AppiumDriver.executeCommand (/Users/deepak.attri/.nvm/versions/node/v17.3.0/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.js:94:15)
2022-04-20 06:37:45:329 [AppiumDriver@cc1e]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-04-20 06:37:45:329 [AppiumDriver@cc1e]     at defaultBehavior (/Users/deepak.attri/.nvm/versions/node/v17.3.0/lib/node_modules/appium/lib/appium.js:594:16)
2022-04-20 06:37:45:329 [AppiumDriver@cc1e]     at AppiumDriver.executeWrappedCommand (/Users/deepak.attri/.nvm/versions/node/v17.3.0/lib/node_modules/appium/lib/appium.js:676:16)
2022-04-20 06:37:45:329 [AppiumDriver@cc1e]     at AppiumDriver.executeCommand (/Users/deepak.attri/.nvm/versions/node/v17.3.0/lib/node_modules/appium/lib/appium.js:605:17)
2022-04-20 06:37:45:329 [AppiumDriver@cc1e]     at asyncHandler (/Users/deepak.attri/.nvm/versions/node/v17.3.0/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:313:19)
2022-04-20 06:37:45:335 [HTTP] <-- POST /session 500 34 ms - 661
2022-04-20 06:37:45:335 [HTTP] 
2022-04-20 06:37:45:640 [HTTP] --> GET /status
2022-04-20 06:37:45:641 [HTTP] {}
2022-04-20 06:37:45:641 [AppiumDriver@cc1e] Calling AppiumDriver.getStatus() with args: []
2022-04-20 06:37:45:641 [AppiumDriver@cc1e] Responding to client with driver.getStatus() result: {"build":{"version":"2.0.0-beta.30","git-sha":"5b3d188b83f27ec31d97f3f3e6e49220e09b6985","built":"2021-10-07 10:11:35 -0700"}}
2022-04-20 06:37:45:642 [HTTP] <-- GET /status 200 1 ms - 136
2022-04-20 06:37:45:642 [HTTP] 
2022-04-20 06:37:45:650 [Appium] Received SIGTERM - shutting down
2022-04-20 06:37:45:650 [AppiumDriver@cc1e] There are no active sessions for cleanup`

**Comment by attrideepak** [comment]
Is this resolved? I am getting the same error while running tests with espresso.

**Comment by JuanCarlos-Arceredillo** [comment]
Hi @attrideepak ,
At the moment this issue has been fixed only with XCUITest because it was updated.

UiAutomator2 & Espresso need to be updated to patch this issue.

**Comment by boneskull** [comment]
The workaround for this has been published as `2.0.0-beta.33`; please upgrade

**Comment by mykola-mokhnach** [comment]
I think it would also make sense to make @babel/runtime and source-map-support peer dependencies in drivers

**Comment by jlipps** [comment]
> I think it would also make sense to make @babel/runtime and source-map-support peer dependencies in drivers

Is this so that they will use the ones that come with the Appium server?

**Comment by mykola-mokhnach** [comment]
> > I think it would also make sense to make @babel/runtime and source-map-support peer dependencies in drivers
> 
> Is this so that they will use the ones that come with the Appium server?

exactly

**Comment by boneskull** [comment]
Ah, actually, we should do 3), because if `@appium/test-support` got out-of-date, that will cause problems due to the peer dependency.

**Comment by jlipps** [comment]
OK, but I'm not happy about having a vanilla `npm install -g appium` bring in a bunch of test-related dependencies that are only used by extension authors for dev purposes. seems like it will add time and size to the install :-(

**Comment by mykola-mokhnach** [comment]
Closed as fixed
