### ISSUE TITLE
Did not get any response for atom execution after 120000ms in IOS Real device

### ISSUE THREAD

**Issue by mathewkuruvila** [appium/appium#16851]
## The problem

I have a hybrid IOS app. Login to the app is through a WebView. Once I click on the button to this WebView, initially I will wait for the WebView to be available using 'getContextHandles'. Once it is available, will switch to it. Then will check if document.ready is complete using JavaScriptExecutor. This ensures WebView is properly loaded. Sometimes I get an exception in the command document.ready executed in the WebView when using JavaScript Executor. Once this error occurs, it will be stuck for 2 minutes. This is visible in  [Appium Log](https://gist.github.com/mathewkuruvila/6c4799eadfda7bb7a5de73d70bf98624#file-appium-log-L112)

I tried to reload the WebView using window.location.reload after this exception. But again it was returning the same error after being stuck for 2 minutes.

Note : I don't get this error always. It is intermittent.

## Environment

* Appium v1.21.0
* Running in BrowserStack cloud
* Real iPhone - iPhone 13 Pro, OS : 15.2

## Link to Appium logs

[Appium Logs](https://gist.github.com/mathewkuruvila/6c4799eadfda7bb7a5de73d70bf98624)

## Code To Reproduce Issue 

public Boolean waitForPageToLoad() {
		JavascriptExecutor jsExecutor = (JavascriptExecutor)driver;
		String readyState = "";

		for(int i = 0; i < 20; i++) {  
			try {
				readyState = (String) jsExecutor.executeScript("return document.readyState");  // Fails here
				if(readyState.equals("complete")) {
					return true;
				} 
			} catch (ClassCastException e) {  // Temporary fix to handle ClassCastException
				e.printStackTrace();
				reloadWebView();  // Method to call window.location.reload
			}
			   	
			waitFor(1);
		}

		System.out.println("WebView is not loaded after 20 seconds");
		return false;
	}

**Comment by jlipps** [comment]
I don't see anything off in the logs, it seems like we did the check for the alert, it came back empty as expected, and then the atom just literally took two more mins to do anything. Not sure if there's anything we can do if Safari doesn't return something. maybe it's a safari remote debug connection flake?

**Comment by mathewkuruvila** [comment]
Thanks @jlipps. Not sure why this is happening. Is this 2 minutes due to some capability which I am passing? Also I was going through some of the WebView related issues in IOS and I think it was @jlipps who suggested to do a WebView refresh using window.location.reload() or click on the WebView to make it load. Executing that reload is also causing the 2 minutes wait. Not sure what to do in this case. Is there any other logging which needs to be done so that you guys can debug the issue. : )

**Comment by mathewkuruvila** [comment]
Thanks @jlipps will remove the code to check document.readyState. Like you suggested will wait for other elements in the screen. Thanks for the help.

**Comment by mathewkuruvila** [comment]
@jlipps I tried the same. It seems error is not just specific to document.readyState. It is there for other elements in the WebView too. I used a findElements for an element //input[@id='idToken2'] in the WebView and got the same exception after 2 minutes. I tried one more thing. There was an option provided in the native app to refresh Web UI. Did the same, but again same exception. So I feel once I get this exception no matter what I do, each command to safari takes 2 minutes.

2022-04-28 23:20:26:967 - [debug] [W3C (f9eecf79)] Responding to client with driver.setContext() result: null
2022-04-28 23:20:26:968 - [HTTP] <-- POST /wd/hub/session/f9eecf79-24e2-4ca8-86e0-2532684e530d/context 200 16100 ms - 14
2022-04-28 23:20:26:968 - [HTTP] 
2022-04-28 23:20:27:296 - [HTTP] --> POST /wd/hub/session/f9eecf79-24e2-4ca8-86e0-2532684e530d/elements
2022-04-28 23:20:27:296 - [HTTP] {"using":"xpath","value":"//input[@id='idToken2']"}
2022-04-28 23:20:27:297 - [debug] [W3C (f9eecf79)] Calling AppiumDriver.findElements() with args: ["xpath","//input[@id='idToken2']","f9eecf79-24e2-4ca8-86e0-2532684e530d"]
2022-04-28 23:20:27:297 - [debug] [XCUITest] Executing command 'findElements'
2022-04-28 23:20:27:297 - [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id, css selector
2022-04-28 23:20:27:297 - [debug] [BaseDriver] Waiting up to 0 ms for condition
2022-04-28 23:20:27:297 - [debug] [RemoteDebugger] Executing atom 'find_elements' with 'args=["xpath","//input[@id='idToken2']",null]; frames='
2022-04-28 23:20:27:298 - [debug] [RemoteDebugger] Executing 'find_elements' atom in default context
2022-04-28 23:20:27:298 - [debug] [RemoteDebugger] Sending javascript command: '(function(){return function(){var k=this;functi...'
2022-04-28 23:20:27:299 - [debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:781', page '3' (id: 44): 'Runtime.evaluate'
2022-04-28 23:20:27:306 - [debug] [RemoteDebugger] Handling message (id: '45')
2022-04-28 23:20:27:709 - [debug] [WD Proxy] Matched '/alert/text' to command name 'getAlertText'
2022-04-28 23:20:27:709 - [debug] [WD Proxy] Proxying [GET /alert/text] to [GET http://127.0.0.1:8401/session/0BECF384-8D7C-4994-AC71-6251DA98E57E/alert/text] with no body
2022-04-28 23:20:27:928 - [WD Proxy] Got response with status 404: {"value":{"error":"no such alert","message":"An attempt was made to operate on a modal dialog when one was not open","traceback":""},"sessionId":"0BECF384-8D7C-4994-AC71-6251DA98E57E"}
2022-04-28 23:20:27:929 - [debug] [W3C] Matched W3C error code 'no such alert' to NoSuchAlertError
2022-04-28 23:22:27:304 - [debug] [XCUITest] Error received while executing atom: operation timed out
2022-04-28 23:22:27:306 - [debug] [XCUITest] No alert found: Did not get any response for atom execution after 120010ms
2022-04-28 23:22:27:309 - [debug] [W3C (f9eecf79)] Encountered internal error running command: Error: Did not get any response for atom execution after 120010ms
2022-04-28 23:22:27:309 - [debug] [W3C (f9eecf79)]     at /nix/store/prdh6ka6vv24b1g8h2iv0zg1pm0ib6cs-appium-1.21.0/node_modules/appium-xcuitest-driver/lib/commands/web.js:575:15
2022-04-28 23:22:27:309 - [debug] [W3C (f9eecf79)]     at tryCatcher (/nix/store/prdh6ka6vv24b1g8h2iv0zg1pm0ib6cs-appium-1.21.0/node_modules/bluebird/js/release/util.js:16:23)
2022-04-28 23:22:27:309 - [debug] [W3C (f9eecf79)]     at Promise._settlePromiseFromHandler (/nix/store/prdh6ka6vv24b1g8h2iv0zg1pm0ib6cs-appium-1.21.0/node_modules/bluebird/js/release/promise.js:547:31)
2022-04-28 23:22:27:310 - [debug] [W3C (f9eecf79)]     at Promise._settlePromise (/nix/store/prdh6ka6vv24b1g8h2iv0zg1pm0ib6cs-appium-1.21.0/node_modules/bluebird/js/release/promise.js:604:18)
2022-04-28 23:22:27:310 - [debug] [W3C (f9eecf79)]     at Promise._settlePromise0 (/nix/store/prdh6ka6vv24b1g8h2iv0zg1pm0ib6cs-appium-1.21.0/node_modules/bluebird/js/release/promise.js:649:10)
2022-04-28 23:22:27:310 - [debug] [W3C (f9eecf79)]     at Promise._settlePromises (/nix/store/prdh6ka6vv24b1g8h2iv0zg1pm0ib6cs-appium-1.21.0/node_modules/bluebird/js/release/promise.js:725:18)
2022-04-28 23:22:27:310 - [debug] [W3C (f9eecf79)]     at _drainQueueStep (/nix/store/prdh6ka6vv24b1g8h2iv0zg1pm0ib6cs-appium-1.21.0/node_modules/bluebird/js/release/async.js:93:12)
2022-04-28 23:22:27:310 - [debug] [W3C (f9eecf79)]     at _drainQueue (/nix/store/prdh6ka6vv24b1g8h2iv0zg1pm0ib6cs-appium-1.21.0/node_modules/bluebird/js/release/async.js:86:9)
2022-04-28 23:22:27:310 - [debug] [W3C (f9eecf79)]     at Async._drainQueues (/nix/store/prdh6ka6vv24b1g8h2iv0zg1pm0ib6cs-appium-1.21.0/node_modules/bluebird/js/release/async.js:102:5)
2022-04-28 23:22:27:310 - [debug] [W3C (f9eecf79)]     at Immediate.Async.drainQueues (/nix/store/prdh6ka6vv24b1g8h2iv0zg1pm0ib6cs-appium-1.21.0/node_modules/bluebird/js/release/async.js:15:14)
2022-04-28 23:22:27:310 - [debug] [W3C (f9eecf79)]     at processImmediate (internal/timers.js:464:21)
2022-04-28 23:22:27:315 - [HTTP] <-- POST /wd/hub/session/f9eecf79-24e2-4ca8-86e0-2532684e530d/elements 500 120019 ms - 659
2022-04-28 23:22:27:315 - [HTTP] 
2022-04-28 23:22:28:993 - [HTTP] --> POST /wd/hub/session/f9eecf79-24e2-4ca8-86e0-2532684e530d/appium/app/close

**Comment by KazuCocoa** [comment]
How the latest version, at least v1.22?
There are some alert handling tuning after the version e.g. https://github.com/appium/appium-xcuitest-driver/pull/1320
They might improve the behavior.

**Comment by mathewkuruvila** [comment]
Thanks @KazuCocoa Will give that a try.

**Comment by mathewkuruvila** [comment]
@KazuCocoa Tried in v1.22. Again same error. 

`2022-04-29 05:21:43:354 - [debug] [W3C] Matched W3C error code 'no such alert' to NoSuchAlertError
2022-04-29 05:21:43:866 - [debug] [WD Proxy] Matched '/alert/text' to command name 'getAlertText'
2022-04-29 05:21:43:866 - [debug] [WD Proxy] Proxying [GET /alert/text] to [GET http://127.0.0.1:8404/session/FA9C74BF-4EE3-4168-9C7B-C6D31F1AF733/alert/text] with no body
2022-04-29 05:21:44:027 - [WD Proxy] Got response with status 404: {"value":{"error":"no such alert","message":"An attempt was made to operate on a modal dialog when one was not open","traceback":""},"sessionId":"FA9C74BF-4EE3-4168-9C7B-C6D31F1AF733"}
2022-04-29 05:21:44:027 - [debug] [W3C] Matched W3C error code 'no such alert' to NoSuchAlertError
2022-04-29 05:21:44:106 - [debug] [XCUITest] Error received while executing atom: operation timed out
2022-04-29 05:21:44:126 - [debug] [W3C (960fdd9e)] Encountered internal error running command: Error: Did not get any response for atom execution after 120017ms
2022-04-29 05:21:44:126 - [debug] [W3C (960fdd9e)]     at handlePromiseError (/nix/store/v95a8w5whs53p701j706qa641j2swgdv-appium-1.22.0/node_modules/appium-xcuitest-driver/lib/commands/web.js:550:15)
2022-04-29 05:21:44:146 - [HTTP] <-- POST /wd/hub/session/960fdd9e-15d3-468e-ab4a-e088c439b86e/execute/sync 500 120059 ms - 659
2022-04-29 05:21:44:146 - [HTTP] 
2022-04-29 05:21:45:655 - [HTTP] --> POST /wd/hub/session/960fdd9e-15d3-468e-ab4a-e088c439b86e/appium/app/close
`

**Comment by KazuCocoa** [comment]
then, what about adding `appium:safariLogAllCommunication` capability to track the response by WebInspector?

**Comment by mathewkuruvila** [comment]
Sure I will.

**Comment by mathewkuruvila** [comment]
@KazuCocoa Please find below logs with appium:safariLogAllCommunication
[AppiumLogs](https://gist.github.com/mathewkuruvila/c8b8e5f99813498bbd59cb836ee5bbe2)

**Comment by KazuCocoa** [comment]
probably https://gist.github.com/mathewkuruvila/c8b8e5f99813498bbd59cb836ee5bbe2 does not include `targetId` https://github.com/appium/appium-ios/blob/a4f8e52166e011630ef8991e6abc14aaafe1a095/packages/remote-debugger/lib/rpc/remote-messages.js#L122 ?

**Comment by mathewkuruvila** [comment]
Sorry @KazuCocoa not sure what that targetId is? I hope I not am doing something wrong here which leads to this issue.

**Comment by KazuCocoa** [comment]
Sorry, it was just a comment about possible error place from your attached one. We need more debugging here.
Can it happen in a accessible general web page as well?

**Comment by mathewkuruvila** [comment]
I am sorry @KazuCocoa. Can't share the url details. It's under VPN and can't be accessed from outside.

**Comment by mathewkuruvila** [comment]
@KazuCocoa Am I the only person who is affected by this intermittent issue? Let me check if I can share the webview details.

**Comment by KazuCocoa** [comment]
Afaik, no, but I only know reported in this repository. Potentially some persons also have.
Generally, the `targetId` should exist, so it would be helpful if you have a reproducible app.

**Comment by n-eq** [comment]
> @KazuCocoa Am I the only person who is affected by this intermittent issue? Let me check if I can share the webview details.

Hello @KazuCocoa, I've been struggling with exactly the same issue using a real iOS device with a mobile app. I have so far conclusion that the command times out in 2 minutes due to this variable definition.

https://github.com/mykola-mokhnach/appium-xcuitest-driver/blob/master/lib/commands/web.js#L29

My understanding is that all commands must run under 2 minutes otherwise you get the "Did not get any response for atom execution..." exception:

https://github.com/mykola-mokhnach/appium-xcuitest-driver/blob/29a376521e5d4f107989f863f98c3963214ecbd2/lib/commands/web.js#L616-L627

However, all my attempts to increase this value using capabilities were unsuccessful.

**Comment by KazuCocoa** [comment]
Basically, the response depends on how maccOS's WebInspeccctor replies.
`appium:safariLogAllCommunication` log might help to see if the remote debugger (WebInspeccctor) replied or something.

**Comment by 7999** [comment]
I got same issue on the real iPad device with a hybrid app, below is log:
[appium.log](https://github.com/appium/appium/files/11704240/appium.log)

**Comment by jlipps** [comment]
It looks like the execute atom never returned. Maybe `document.readyState` is not accessible or something on your webpage? At any rate we just updated the atoms, so try again with the latest xcuitest driver. If that doesn't work, there's likely nothing we'll be able to do about it.

**Comment by robbbowes** [comment]
@abdul-qadir92 I'm not sure if this is still an issue but I was running into the same problem.
Updating to the latest xcuitest driver didn't help, but I found that switching from the webview context to the native context and then back again resolves the issue for me.
