### ISSUE TITLE
setAsyncTimeout not implemented in WDIO

### ISSUE THREAD

**Issue by emalysz** [appium/appium#16865]
## The problem
When trying to use setAsyncTimeout according to [WDIO documentation](https://webdriver.io/docs/api/jsonwp/#setasynctimeout), you will receive an error:
```
Method has not yet been implemented
```

## Environment
WDIO/Appium 

* Appium version (or git revision) that exhibits the issue: Any 
* Last Appium version that did not exhibit the issue (if applicable): n/a
* Desktop OS/version used to run Appium: n/a
* Node.js version (unless using Appium.app|exe): 12.x, 14.x, 16.x, etc
* Npm or Yarn package manager: n/a
* Mobile platform/version under test: n/a
* Real device or emulator/simulator: n/a
* Appium CLI or Appium.app|exe: n/a

## Code To Reproduce Issue [ Good To Have ]
browser.setAsyncTimeout(ms)

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Please provide the server log

**Comment by emalysz** [comment]
```
2022-04-21 18:27:34:606 - [HTTP] --> POST /wd/hub/session/3622d55e-c110-416a-ad47-89b8fc3470a8/timeouts/async_script
2022-04-21 18:27:34:606 - [HTTP] {"ms":5000}
2022-04-21 18:27:34:607 - [debug] [MJSONWP (3622d55e)] Calling AppiumDriver.asyncScriptTimeout() with args: [5000,"3622d55e-c110-416a-ad47-89b8fc3470a8"]
2022-04-21 18:27:34:629 - [debug] [MJSONWP (3622d55e)] Encountered internal error running command: NotYetImplementedError: Method has not yet been implemented
2022-04-21 18:27:34:629 - [debug] [MJSONWP (3622d55e)]     at AndroidUiautomator2Driver.executeCommand (/nix/store/k4nnyxsa9v0cbsg504n1ckm1qmsz9yx8-appium-1.17.0/node_modules/appium-uiautomator2-driver/node_modules/appium-base-driver/lib/basedriver/driver.js:323:13)
2022-04-21 18:27:34:629 - [debug] [MJSONWP (3622d55e)]     at AppiumDriver.executeCommand (/nix/store/k4nnyxsa9v0cbsg504n1ckm1qmsz9yx8-appium-1.17.0/lib/appium.js:534:36)
2022-04-21 18:27:34:629 - [debug] [MJSONWP (3622d55e)]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2022-04-21 18:27:34:630 - [debug] [MJSONWP (3622d55e)]     at asyncHandler (/nix/store/k4nnyxsa9v0cbsg504n1ckm1qmsz9yx8-appium-1.17.0/node_modules/appium-base-driver/lib/protocol/protocol.js:309:21)
```

**Comment by mykola-mokhnach** [comment]
This is expected. Setting timeouts for async scripts does not make much sense for UIA2 driver

**Comment by mykola-mokhnach** [comment]
Also the endpoint itself seems to be a part of JSONWP protocol. I don't think it is even present in W3C spec

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
