### ISSUE TITLE
Linting of all modules that depend on @appium monorepo now fails with "Error: Failed to load config "prettier" to extend from."

### ISSUE THREAD

**Issue by mykola-mokhnach** [appium/appium#16890]
## The problem

Running linter on any package that depends on `@appium` monorepo now fails with `Error: Failed to load config "prettier" to extend from.`. The issue started happening after [beta34](https://github.com/appium/appium/commit/5482c921bc187ed8807922c00bd2355585f4971a) has been published.

```
[04:52:11] Starting 'eslint'...
[04:52:11] 'eslint' errored after 102 ms
[04:52:11] Error: Failed to load config "prettier" to extend from.
Referenced from: /Users/runner/work/1/s/node_modules/@appium/eslint-config-appium/index.js
    at configMissingError (/Users/runner/work/1/s/node_modules/gulp-eslint/node_modules/eslint/lib/cli-engine/config-array-factory.js:265:9)
    at ConfigArrayFactory._loadExtendedShareableConfig (/Users/runner/work/1/s/node_modules/gulp-eslint/node_modules/eslint/lib/cli-engine/config-array-factory.js:826:23)
    at ConfigArrayFactory._loadExtends (/Users/runner/work/1/s/node_modules/gulp-eslint/node_modules/eslint/lib/cli-engine/config-array-factory.js:731:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/runner/work/1/s/node_modules/gulp-eslint/node_modules/eslint/lib/cli-engine/config-array-factory.js:660:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/Users/runner/work/1/s/node_modules/gulp-eslint/node_modules/eslint/lib/cli-engine/config-array-factory.js:596:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/runner/work/1/s/node_modules/gulp-eslint/node_modules/eslint/lib/cli-engine/config-array-factory.js:660:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/Users/runner/work/1/s/node_modules/gulp-eslint/node_modules/eslint/lib/cli-engine/config-array-factory.js:596:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at createConfigArray (/Users/runner/work/1/s/node_modules/gulp-eslint/node_modules/eslint/lib/cli-engine/config-array-factory.js:340:25)
    at ConfigArrayFactory.loadInDirectory (/Users/runner/work/1/s/node_modules/gulp-eslint/node_modules/eslint/lib/cli-engine/config-array-factory.js:433:16)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/Users/runner/work/1/s/node_modules/gulp-eslint/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:328:46)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/Users/runner/work/1/s/node_modules/gulp-eslint/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:272:18)
    at CLIEngine.isPathIgnored (/Users/runner/work/1/s/node_modules/gulp-eslint/node_modules/eslint/lib/cli-engine/cli-engine.js:951:18)
```

 See https://dev.azure.com/AppiumCI/Appium%20CI/_build/results?buildId=21080&view=logs&j=79d2116f-87ea-55f5-8e39-97f4c12282d9&t=72eec8ce-d00c-580f-262c-f0fb5359d77c for more details

**Comment by mykola-mokhnach** [comment]
We are slowly bumping depending modules to include the major update. This bug could probably be fixed
