### ISSUE TITLE
Appium-ios test running in AWS Device Farm is skipping the test after few test exuection 

### ISSUE THREAD

**Issue by chhabrasaurabh80** [appium/appium#16933]
## The problem

While running the automation test scripts in AWS Device farm for iOS Mobile devices, we observed that automation test are getting skipped after few pass or fail test. Noticed following error in the logs

Command: NoSuchDriverError: A session is either terminated or not started
2022-05-11 08:33:11:848 - [debug] [35m[W3C (09b20622)][39m     at asyncHandler (/usr/local/avm/versions/1.22.2/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:243:15)
2022-05-11 08:33:11:848 - [debug] [35m[W3C (09b20622)][39m     at /usr/local/avm/versions/1.22.2/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:423:15
2022-05-11 08:33:11:848 - [debug] [35m[W3C (09b20622)][39m     at Layer.handle [as handle_request] (/usr/local/avm/versions/1.22.2/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
2022-05-11 08:33:11:849 - [debug] [35m[W3C (09b20622)][39m     at next (/usr/local/avm/versions/1.22.2/node_modules/appium/node_modules/express/lib/router/route.js:137:13)
2022-05-11 08:33:11:849 - [debug] [35m[W3C (09b20622)][39m     at Route.dispatch (/usr/local/avm/versions/1.22.2/node_modules/appium/node_modules/express/lib/router/route.js:112:3)
2022-05-11 08:33:11:849 - [debug] [35m[W3C (09b20622)][39m     at Layer.handle [as handle_request] (/usr/local/avm/versions/1.22.2/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
2022-05-11 08:33:11:849 - [debug] [35m[W3C (09b20622)][39m     at /usr/local/avm/versions/1.22.2/node_modules/appium/node_modules/express/lib/router/index.js:281:22
2022-05-11 08:33:11:849 - [debug] [35m[W3C (09b20622)][39m     at param (/usr/local/avm/versions/1.22.2/node_modules/appium/node_modules/express/lib/router/index.js:354:14)
2022-05-11 08:33:11:849 - [debug] [35m[W3C (09b20622)][39m     at param (/usr/local/avm/versions/1.22.2/node_modules/appium/node_modules/express/lib/router/index.js:365:14)
2022-05-11 08:33:11:849 - [debug] [35m[W3C (09b20622)][39m     at Function.process_params (/usr/local/avm/versions/1.22.2/node_modules/appium/node_modules/express/lib/router/index.js:410:3)
2022-05-11 08:33:11:849 - [debug] [35m[W3C (09b20622)][39m     at next (/usr/local/avm/versions/1.22.2/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
2022-05-11 08:33:11:849 - [debug] [35m[W3C (09b20622)][39m     at logger (/usr/local/avm/versions/1.22.2/node_modules/appium/node_modules/morgan/index.js:144:5)
2022-05-11 08:33:11:850 - [debug] [35m[W3C (09b20622)][39m     at Layer.handle [as handle_request] (/usr/local/avm/versions/1.22.2/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
2022-05-11 08:33:11:850 - [debug] [35m[W3C (09b20622)][39m     at trim_prefix (/usr/local/avm/versions/1.22.2/node_modules/appium/node_modules/express/lib/router/index.js:317:13)
2022-05-11 08:33:11:850 - [debug] [35m[W3C (09b20622)][39m     at /usr/local/avm/versions/1.22.2/node_modules/appium/node_modules/express/lib/router/index.js:284:7
2022-05-11 08:33:11:850 - [debug] [35m[W3C (09b20622)][39m     at Function.process_params (/usr/local/avm/versions/1.22.2/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
2022-05-11 08:33:11:861 - [35m[HTTP][39m [37m<-- GET /wd/hub/session/09b20622-df30-4b83-9e26-e391767f97e7/screenshot [39m[33m404[39m [90m55 ms - 2142[39m
2022-05-11 08:33:11:861 - [35m[HTTP][39m [90m[39m
2022-05-11 08:33:11:864 - [debug] [35m[WebDriverAgent][39m Upgrade timestamp of the currently bundled WDA: 1652250520062
2022-05-11 08:33:11:864 - [debug] [35m[WebDriverAgent][39m Upgrade timestamp of the WDA on the device: 1652250520062
2022-05-11 08:33:11:865 - [35m[WebDriverAgent][39m Will reuse previously cached WDA instance at 'http://127.0.0.1:8100/' with 'com.facebook.WebDriverAgentRunner'. Set the wdaLocalPort capability to a value different from 8100 if this is an undesired behavior.
2022-05-11 08:33:11:865 - [debug] [35m[XCUITest][39m Trying to start WebDriverAgent 1 times with 10000ms interval
2022-05-11 08:33:11:865 - [debug] [35m[XCUITest][39m These values can be customized by changing wdaStartupRetries/wdaStartupRetryInterval capabilities
2022-05-11 08:33:11:865 - [debug] [35m[BaseDriver][39m Event 'wdaStartAttempted' logged at 1652257991865 (01:33:11 GMT-0700 (Pacific Daylight Time))
2022-05-11 08:33:11:865 - [debug] [35m[BaseDriver][39m Event 'wdaStartFailed' logged at 1652257991865 (01:33:11 GMT-0700 (Pacific Daylight Time))
2022-05-11 08:33:11:865 - [debug] [35m[XCUITest][39m Unable to launch WebDriverAgent because of xcodebuild failure: Cannot read property 'launch' of null. Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
2022-05-11 08:33:11:865 - [35m[XCUITest][39m Quitting and uninstalling WebDriverAgent
2022-05-11 08:33:11:866 - [35m[XCUITest][39m Something went wrong while launching the '/tmp/2022410-1085-codxoc.iqdak/vs.app' app.
2022-05-11 08:33:12:056 - [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/09b20622-df30-4b83-9e26-e391767f97e7/appium/app/close[39m
2022-05-11 08:33:12:056 - [35m[HTTP][39m [90m{}[39m
2022-05-11 08:33:12:065 - [debug] [35m[W3C (09b20622)][39m Encountered internal error running command: NoSuchDriverError: A session is either terminated or not started
2022-05-11 08:33:12:065 - [debug] [35m[W3C (09b20622)][39m     at asyncHandler (/usr/local/avm/versions/1.22.2/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:243:15)
2022-05-11 08:33:12:066 - [debug] [35m[W3C (09b20622)][39m     at /usr/local/avm/versions/1.22.2/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:423:15
2022-05-11 08:33:12:066 - [debug] [35m[W3C (09b20622)][39m     at Layer.handle [as handle_request] (/usr/local/avm/versions/1.22.2/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
2022-05-11 08:33:12:066 - [debug] [35m[W3C (09b20622)][39m     at next (/usr/local/avm/versions/1.22.2/node_modules/appium/node_modules/express/lib/router/route.js:137:13)
2022-05-11 08:33:12:066 - [debug] [35m[W3C (09b20622)][39m     at Route.dispatch (/usr/local/avm/versions/1.22.2/node_modules/appium/node_modules/express/lib/router/route.js:112:3)
2022-05-11 08:33:12:066 - [debug] [35m[W3C (09b20622)][39m     at Layer.handle [as handle_request] (/usr/local/avm/versions/1.22.2/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
2022-05-11 08:33:12:066 - [debug] [35m[W3C (09b20622)][39m     at /usr/local/avm/versions/1.22.2/node_modules/appium/node_modules/express/lib/router/index.js:281:22
2022-05-11 08:33:12:066 - [debug] [35m[W3C (09b20622)][39m     at param (/usr/local/avm/versions/1.22.2/node_modules/appium/node_modules/express/lib/router/index.js:354:14)
2022-05-11 08:33:12:066 - [debug] [35m[W3C (09b20622)][39m     at param (/usr/local/avm/versions/1.22.2/node_modules/appium/node_modules/express/lib/router/index.js:365:14)
2022-05-11 08:33:12:066 - [debug] [35m[W3C (09b20622)][39m     at Function.process_params (/usr/local/avm/versions/1.22.2/node_modules/appium/node_modules/express/lib/router/index.js:410:3)
2022-05-11 08:33:12:067 - [debug] [35m[W3C (09b20622)][39m     at next (/usr/local/avm/versions/1.22.2/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
2022-05-11 08:33:12:067 - [debug] [35m[W3C (09b20622)][39m     at logger (/usr/local/avm/versions/1.22.2/node_modules/appium/node_modules/morgan/index.js:144:5)
2022-05-11 08:33:12:067 - [debug] [35m[W3C (09b20622)][39m     at Layer.handle [as handle_request] (/usr/local/avm/versions/1.22.2/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
2022-05-11 08:33:12:067 - [debug] [35m[W3C (09b20622)][39m     at trim_prefix (/usr/local/avm/versions/1.22.2/node_modules/appium/node_modules/express/lib/router/index.js:317:13)
2022-05-11 08:33:12:067 - [debug] [35m[W3C (09b20622)][39m     at /usr/local/avm/versions/1.22.2/node_modules/appium/node_modules/express/lib/router/index.js:284:7
2022-05-11 08:33:12:067 - [debug] [35m[W3C (09b20622)][39m     at Function.process_params (/usr/local/avm/versions/1.22.2/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
2022-05-11 08:33:12:069 - [35m[HTTP][39m [37m<-- POST /wd/hub/session/09b20622-df30-4b83-9e26-e391767f97e7/appium/app/close [39m[33m404[39m [90m12 ms - 2142[39m
2022-05-11 08:33:12:069 - [35m[HTTP][39m [90m[39m
2022-05-11 08:33:12:113 - [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/09b20622-df30-4b83-9e26-e391767f97e7/appium/app/launch[39m
2022-05-11 08:33:12:113 - [35m[HTTP][39m [90m{}[39m
2

**Comment by chhabrasaurabh80** [comment]
[Uploading appiumlog.txt…]
I am attaching the appiumlog file for your reference please let me know if anything else is needed

**Comment by chhabrasaurabh80** [comment]
[appiumlog.txt](https://github.com/appium/appium/files/8675026/appiumlog.txt)

**Comment by mykola-mokhnach** [comment]
The error seems to be expected. I can observe the following log line above it:

> 2022-05-11 08:33:11:577 - [debug] [35m[W3C (09b20622)][39m Encountered internal error running command: Error: New Command Timeout of 160 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability

**Comment by chhabrasaurabh80** [comment]
Problem is we run in AWS Device Farm these test and they have a limit of 150 mins per session. If test exceeds this time the session is getting stopped without any results. So this seems to be not the best solution any other solution can be for this issue.

**Comment by mykola-mokhnach** [comment]
I'm still not quite sure what the issue above has to do with Appium server or driver functionality.

**Comment by chhabrasaurabh80** [comment]
Not sure whom should I raise this issue. As Appium is losing the driver and due to new command time out max time, it is skipping all the test. It works perfectly fine same test in andriod devices. But when we try to run in iOS it is damm slow.

**Comment by mykola-mokhnach** [comment]
There might be multiple reasons of that slowness. Some of them might be mitigated by refactoring the client code, some other are genuine XCTest issues, others are related to how the app under test or iOS itself works. Consider reading the set of articles at Appium Pro: https://appiumpro.com/editions/19-making-your-appium-tests-fast-and-reliable-part-1-test-flakiness and/or hiring a professional consultant who knows how to improve the performance of the tests

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
