### ISSUE TITLE
Appium2 Issue with /timeouts endpoint going to Images plugin

### ISSUE THREAD

**Issue by VinayBerry** [appium/appium#16934]
## The problem

When I run with Images plugin loaded, and I try to set Implicit Wait for WinAppDriver with the timeouts endpoint it's instead getting forwarded to the images plugin and throwing an error.

**Appium Logs:**
```
[HTTP] --> POST /wd/hub/session/33cd6d4f-5153-4a16-9b99-bd092c0923b7/timeouts
[HTTP] {"implicit":5000}
[debug] [WindowsDriver@acd2 (33cd6d4f)] Would have proxied command directly, but a plugin exists which might require its value, so will let its value be collected internally and made part of plugin chain
[debug] [WindowsDriver@acd2 (33cd6d4f)] Calling AppiumDriver.timeouts() with args: [null,null,null,null,5000,"33cd6d4f-5153-4a16-9b99-bd092c0923b7"]
[AppiumDriver@c18b] Plugins which can handle cmd 'timeouts': images
[AppiumDriver@c18b] Plugin images is now handling cmd 'timeouts'
[AppiumDriver@c18b] Executing default handling behavior for command 'timeouts'
[debug] [WindowsDriver@acd2 (33cd6d4f)] Encountered internal error running command: Error: The default behavior for this command was to proxy, but the driver did not have the 'proxyCommand' method defined. To fully support plugins, drivers should have 'proxyCommand' set to a jwpProxy object's 'command()' method, in addition to the normal 'proxyReqRes'
[debug] [WindowsDriver@acd2 (33cd6d4f)]     at next (C:\Users\VBerry\AppData\Roaming\npm\node_modules\appium\lib\appium.js:585:17)
[debug] [WindowsDriver@acd2 (33cd6d4f)]     at ImageElementPlugin.handle (C:\Users\VBerry\.appium\node_modules\@appium\images-plugin\lib\plugin.js:78:18)
[debug] [WindowsDriver@acd2 (33cd6d4f)]     at wrappedCmd (C:\Users\VBerry\AppData\Roaming\npm\node_modules\appium\lib\appium.js:647:29)
[debug] [WindowsDriver@acd2 (33cd6d4f)]     at AppiumDriver.executeWrappedCommand (C:\Users\VBerry\AppData\Roaming\npm\node_modules\appium\lib\appium.js:680:22)
[debug] [WindowsDriver@acd2 (33cd6d4f)]     at AppiumDriver.executeCommand (C:\Users\VBerry\AppData\Roaming\npm\node_modules\appium\lib\appium.js:609:28)
[debug] [WindowsDriver@acd2 (33cd6d4f)]     at asyncHandler (C:\Users\VBerry\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\protocol.js:313:32)
[debug] [WindowsDriver@acd2 (33cd6d4f)]     at C:\Users\VBerry\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\protocol.js:411:15
[debug] [WindowsDriver@acd2 (33cd6d4f)]     at Layer.handle [as handle_request] (C:\Users\VBerry\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\layer.js:95:5)
[debug] [WindowsDriver@acd2 (33cd6d4f)]     at next (C:\Users\VBerry\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\route.js:144:13)
[debug] [WindowsDriver@acd2 (33cd6d4f)]     at Route.dispatch (C:\Users\VBerry\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\route.js:114:3)
[debug] [WindowsDriver@acd2 (33cd6d4f)]     at Layer.handle [as handle_request] (C:\Users\VBerry\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\layer.js:95:5)
[debug] [WindowsDriver@acd2 (33cd6d4f)]     at C:\Users\VBerry\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:284:15
[debug] [WindowsDriver@acd2 (33cd6d4f)]     at param (C:\Users\VBerry\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:365:14)
[debug] [WindowsDriver@acd2 (33cd6d4f)]     at param (C:\Users\VBerry\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:376:14)
[debug] [WindowsDriver@acd2 (33cd6d4f)]     at Function.process_params (C:\Users\VBerry\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:421:3)
[debug] [WindowsDriver@acd2 (33cd6d4f)]     at next (C:\Users\VBerry\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:280:10)
[debug] [WindowsDriver@acd2 (33cd6d4f)]     at logger (C:\Users\VBerry\AppData\Roaming\npm\node_modules\appium\node_modules\morgan\index.js:144:5)
[debug] [WindowsDriver@acd2 (33cd6d4f)]     at Layer.handle [as handle_request] (C:\Users\VBerry\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\layer.js:95:5)
[debug] [WindowsDriver@acd2 (33cd6d4f)]     at trim_prefix (C:\Users\VBerry\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:328:13)
[debug] [WindowsDriver@acd2 (33cd6d4f)]     at C:\Users\VBerry\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:286:9
[debug] [WindowsDriver@acd2 (33cd6d4f)]     at Function.process_params (C:\Users\VBerry\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:346:12)
[debug] [WindowsDriver@acd2 (33cd6d4f)]     at next (C:\Users\VBerry\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:280:10)
[debug] [WindowsDriver@acd2 (33cd6d4f)]     at C:\Users\VBerry\AppData\Roaming\npm\node_modules\appium\node_modules\body-parser\lib\read.js:137:5
[debug] [WindowsDriver@acd2 (33cd6d4f)]     at AsyncResource.runInAsyncScope (node:async_hooks:199:9)
[debug] [WindowsDriver@acd2 (33cd6d4f)]     at invokeCallback (C:\Users\VBerry\AppData\Roaming\npm\node_modules\appium\node_modules\raw-body\index.js:231:16)
[debug] [WindowsDriver@acd2 (33cd6d4f)]     at done (C:\Users\VBerry\AppData\Roaming\npm\node_modules\appium\node_modules\raw-body\index.js:220:7)
[debug] [WindowsDriver@acd2 (33cd6d4f)]     at IncomingMessage.onEnd (C:\Users\VBerry\AppData\Roaming\npm\node_modules\appium\node_modules\raw-body\index.js:280:7)
[debug] [WindowsDriver@acd2 (33cd6d4f)]     at IncomingMessage.emit (node:events:402:35)
[debug] [WindowsDriver@acd2 (33cd6d4f)]     at endReadableNT (node:internal/streams/readable:1343:12)
[debug] [WindowsDriver@acd2 (33cd6d4f)]     at processTicksAndRejections (node:internal/process/task_queues:83:21)
[HTTP] <-- POST /wd/hub/session/33cd6d4f-5153-4a16-9b99-bd092c0923b7/timeouts 500 294 ms - 1166
```

## Environment

* Appium version: 2.0.0-beta.35

## Details

If I run without Images plugin this works fine for me.

**Comment by mykola-mokhnach** [comment]
The fix for that should be simple

**Comment by jlipps** [comment]
yeah I don't think the images command should be handling `timeouts`

**Comment by jlipps** [comment]
in this case i guess the windows driver should define the proxyCommand method instead of just proxyReqRes or whatever is already defined.

**Comment by mykola-mokhnach** [comment]
The issue should be resolved in the recent windows driver patch
