### ISSUE TITLE
Appium 2.0: Android: Can't start  driver

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium#16963]
## The problem

installed appium with:
```
  npm install -g appium@next
  appium driver install uiautomator2
```

## Environment

* Appium version (or git revision) that exhibits the issue: 2.0.0-beta.35
* Last Appium version that did not exhibit the issue (if applicable): 1.23.0-beta.0
* Driver version that exhibits the issue (only for Appium2): uiautomator2@2.1.2
* Last driver version that did not exhibit the issue (if applicable, only for Appium2): -
* Desktop OS/version used to run Appium: macOS
* Mobile platform/version under test: android
* Real device or emulator/simulator: real device

## Link to Appium logs

```
[14:56:18.223] [myTest]     AppiumDriverFactory:        | configureLocalAppium(): devicePlatform: android , env: DEV, testBuild: trunk, deviceName: nokia_5.3_13 
[14:56:18.230] [myTest]      AppiumDriverFactory():     | configureLocalAppium(): Driver DO NORMAL start
[14:56:18.230] [myTest]Capabilities {allowTestPackages: true, app: /Users/myUSER/Doc..., appWaitActivity: com.xxx.*, autoGrantPermissions: true, automationName: UIAutomator2, clearSystemFiles: true, deviceName: nokia_5.3_13, disableAndroidWatchers: true, enableMultiWindows: true, fullReset: false, newCommandTimeout: 180, noReset: true, noSign: true, platformName: Android, skipDeviceInitialization: true, skipServerInstallation: true, systemPort: 5413, udid: N0AA003811K62001102, useNewWDA: false, usePrebuiltWDA: true}
[14:56:18.241] [myTest]      AppiumDriverFactory():     | configureLocalAppium(): AndroidDriver: http://localhost:5013
2022-05-18 11:56:18:794 - [debug] [HTTP] Request idempotency key: c6a4da75-b1ba-4784-b4f3-fec596af9c1e
2022-05-18 11:56:18:809 - [HTTP] --> POST /session
2022-05-18 11:56:18:809 - [HTTP] {"desiredCapabilities":{"app":"/Users/myUSER/Documents/test/app/app-dev-debug.apk","allowTestPackages":true,"clearSystemFiles":true,"noReset":true,"enableMultiWindows":true,"noSign":"true","appWaitActivity":"com.xxx.*","disableAndroidWatchers":true,"deviceName":"nokia_5.3_13","fullReset":false,"usePrebuiltWDA":true,"newCommandTimeout":180,"automationName":"UIAutomator2","useNewWDA":false,"autoGrantPermissions":true,"skipDeviceInitialization":true,"skipServerInstallation":true,"platformName":"Android","udid":"N0AA003811K62001102","systemPort":5413},"capabilities":{"firstMatch":[{"appium:allowTestPackages":true,"appium:app":"/Users/myUSER/Documents/test/app/app-dev-debug.apk","appium:appWaitActivity":"com.xxx.*","appium:autoGrantPermissions":true,"appium:automationName":"UIAutomator2","appium:clearSystemFiles":true,"appium:deviceName":"nokia_5.3_13","appium:disableAndroidWatchers":true,"enableMultiWindows":true,"appium:fullReset":false,"...
2022-05-18 11:56:18:810 - [debug] [AppiumDriver@2376] Calling AppiumDriver.createSession() with args: [{"app":"/Users/myUSER/Documents/test/app/app-dev-debug.apk","allowTestPackages":true,"clearSystemFiles":true,"noReset":true,"enableMultiWindows":true,"noSign":"true","appWaitActivity":"com.xxx.*","disableAndroidWatchers":true,"deviceName":"nokia_5.3_13","fullReset":false,"usePrebuiltWDA":true,"newCommandTimeout":180,"automationName":"UIAutomator2","useNewWDA":false,"autoGrantPermissions":true,"skipDeviceInitialization":true,"skipServerInstallation":true,"platformName":"Android","udid":"N0AA003811K62001102","systemPort":5413},null,{"firstMatch":[{"appium:allowTestPackages":true,"appium:app":"/Users/myUSER/Documents/test/app/app-dev-debug.apk","appium:appWaitActivity":"com.xxx.*","appium:autoGrantPermissions":true,"appium:automationName":"UIAutomator2","appium:clearSystemFiles":true,"appium:deviceName":"nokia_5.3_13","appium:disableAndroidWatchers":true,"enableMultiWindows":true,"appium:fullReset":false,"appium:newCommandTimeout":180,"a...
2022-05-18 11:56:18:817 - [debug] [AppiumDriver@2376] Event 'newSessionRequested' logged at 1652874978811 (14:56:18 GMT+0300 (Eastern European Summer Time))
2022-05-18 11:56:18:820 - [Appium] Could not parse W3C capabilities: All non-standard capabilities should have a vendor prefix. The following capabilities did not have one: enableMultiWindows,skipServerInstallation
2022-05-18 11:56:18:820 - [debug] [AppiumDriver@2376] Event 'newSessionStarted' logged at 1652874978820 (14:56:18 GMT+0300 (Eastern European Summer Time))
2022-05-18 11:56:18:861 - [debug] [AppiumDriver@2376] Encountered internal error running command: InvalidArgumentError: All non-standard capabilities should have a vendor prefix. The following capabilities did not have one: enableMultiWindows,skipServerInstallation
2022-05-18 11:56:18:861 - [debug] [AppiumDriver@2376]     at parseCaps (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/capabilities.js:179:11)
2022-05-18 11:56:18:861 - [debug] [AppiumDriver@2376]     at processCapabilities (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/capabilities.js:243:43)
2022-05-18 11:56:18:861 - [debug] [AppiumDriver@2376]     at parseCapsForInnerDriver (/usr/local/lib/node_modules/appium/lib/utils.js:111:21)
2022-05-18 11:56:18:861 - [debug] [AppiumDriver@2376]     at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:213:26)
2022-05-18 11:56:18:861 - [debug] [AppiumDriver@2376]     at commandExecutor (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.js:74:9)
2022-05-18 11:56:18:861 - [debug] [AppiumDriver@2376]     at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.js:94:15)
2022-05-18 11:56:18:861 - [debug] [AppiumDriver@2376]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-05-18 11:56:18:861 - [debug] [AppiumDriver@2376]     at defaultBehavior (/usr/local/lib/node_modules/appium/lib/appium.js:598:16)
2022-05-18 11:56:18:861 - [debug] [AppiumDriver@2376]     at AppiumDriver.executeWrappedCommand (/usr/local/lib/node_modules/appium/lib/appium.js:680:16)
2022-05-18 11:56:18:861 - [debug] [AppiumDriver@2376]     at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/lib/appium.js:609:17)
2022-05-18 11:56:18:861 - [debug] [AppiumDriver@2376]     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:313:19)
2022-05-18 11:56:18:862 - [HTTP] <-- POST /session 400 53 ms - 1591
```

Questions:
 - 'enableMultiWindows', 'skipServerInstallation' not supported any more?
 - why it simply just ignore unrecognized capabilities?
 - I failed to find how to configure bootstrap port while running multiple devices with Appium 2.0?

**Comment by jlipps** [comment]
with appium 2 all non-w3c-standard capabilities must be prefixed by `appium:`. so you should use `appium:enableMultiWindows`. some clients automatically add these prefixes, and some don't. should have a look at the [2.0 migration doc](https://github.com/appium/appium/blob/2.0/docs/en/advanced-concepts/migrating-to-appium-2.0.md)
