### ISSUE TITLE
relaxed-caps-plugin loading problems

### ISSUE THREAD

**Issue by boneskull** [appium/appium#16981]
Pasted from [this discussion](https://github.com/appium/appium/discussions/15818) as reported by @shraeyakbasu:

* * *

Hi
I am facing issue to start the server using desired-caps plugin
Installed appium using - npm install -g appium@next
Installed driver using - appium driver install uiautomator2
Installed plugin using - appium plugin install desired-caps
Activating the plugin using - appium --use-plugins desired-caps

*** I am not able to activate relaxed-caps plugin but could activate images and execute-driver plugin
............

Microsoft Windows [Version 10.0.19044.1706]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Santosh>appium plugin list
√ Listing available plugins

images@1.1.10 [installed (NPM)]
execute-driver@1.0.5 [installed (NPM)]
relaxed-caps@1.0.0-beta.6 [installed (NPM)]
C:\Users\Santosh>appium --use-plugins relaxed-caps
[Appium] Attempting to load plugin relaxed-caps...
[debug] [Appium] Requiring plugin at C:\Users\Santosh.appium\node_modules@appium\relaxed-caps-plugin
[Appium] Could not load plugin 'relaxed-caps', so it will not be available. Error in loading the plugin was: Cannot set property 'pluginName' of undefined
[debug] [Appium] TypeError: Cannot set property 'pluginName' of undefined
[debug] [Appium] at map (C:\Users\Santosh\AppData\Roaming\npm\node_modules\appium\lib\extension\index.js:55:11)
[debug] [Appium] at Array.map ()
[debug] [Appium] at getActivePlugins (C:\Users\Santosh\AppData\Roaming\npm\node_modules\appium\lib\extension\index.js:50:8)
[debug] [Appium] at main (C:\Users\Santosh\AppData\Roaming\npm\node_modules\appium\lib\main.js:263:25)
[Appium] Welcome to Appium v2.0.0-beta.35
[Appium] Non-default server args:
[Appium] {
[Appium] usePlugins: [
[Appium] 'relaxed-caps'
[Appium] ]
[Appium] }
[Appium] Attempting to load driver uiautomator2...
[debug] [Appium] Requiring driver at C:\Users\Santosh.appium\node_modules\appium-uiautomator2-driver
[Appium] Attempting to load driver windows...
[debug] [Appium] Requiring driver at C:\Users\Santosh.appium\node_modules\appium-windows-driver
[Appium] Attempting to load driver xcuitest...
[debug] [Appium] Requiring driver at C:\Users\Santosh.appium\node_modules\appium-xcuitest-driver
[Appium] Attempting to load driver YouiEngine...
[debug] [Appium] Requiring driver at C:\Users\Santosh.appium\node_modules\appium-youiengine-driver
[Appium] Attempting to load driver espresso...
[debug] [Appium] Requiring driver at C:\Users\Santosh.appium\node_modules\appium-espresso-driver
(node:4524) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(Use node --trace-warnings ... to show where the warning was created)
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[Appium] Available drivers:
[Appium] - uiautomator2@2.1.3 (automationName 'UiAutomator2')
[Appium] - windows@2.0.5 (automationName 'Windows')
[Appium] - xcuitest@4.4.2 (automationName 'XCUITest')
[Appium] - YouiEngine@1.2.9 (automationName 'YouiEngine')
[Appium] - espresso@2.3.0 (automationName 'Espresso')
[Appium] Available plugins:
[Appium] - images@1.1.10
[Appium] - execute-driver@1.0.5
[Appium] - relaxed-caps@1.0.0-beta.6
[Appium] No plugins activated. Use the --use-plugins flag with names of plugins to activate
[Appium] Received SIGINT - shutting down
[debug] [AppiumDriver@f086] There are no active sessions for cleanup
[HTTP] Waiting until the server is closed
[HTTP] Received server close event
Terminate batch job (Y/N)? y

C:\Users\Santosh>appium --use-plugins images
[Appium] Attempting to load plugin images...
[debug] [Appium] Requiring plugin at C:\Users\Santosh.appium\node_modules@appium\images-plugin
[Appium] Welcome to Appium v2.0.0-beta.35
[Appium] Non-default server args:
[Appium] {
[Appium] usePlugins: [
[Appium] 'images'
[Appium] ]
[Appium] }
[Appium] Attempting to load driver uiautomator2...
[debug] [Appium] Requiring driver at C:\Users\Santosh.appium\node_modules\appium-uiautomator2-driver
[Appium] Attempting to load driver windows...
[debug] [Appium] Requiring driver at C:\Users\Santosh.appium\node_modules\appium-windows-driver
[Appium] Attempting to load driver xcuitest...
[debug] [Appium] Requiring driver at C:\Users\Santosh.appium\node_modules\appium-xcuitest-driver
[Appium] Attempting to load driver YouiEngine...
[debug] [Appium] Requiring driver at C:\Users\Santosh.appium\node_modules\appium-youiengine-driver
[Appium] Attempting to load driver espresso...
[debug] [Appium] Requiring driver at C:\Users\Santosh.appium\node_modules\appium-espresso-driver
(node:10180) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(Use node --trace-warnings ... to show where the warning was created)
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[Appium] Available drivers:
[Appium] - uiautomator2@2.1.3 (automationName 'UiAutomator2')
[Appium] - windows@2.0.5 (automationName 'Windows')
[Appium] - xcuitest@4.4.2 (automationName 'XCUITest')
[Appium] - YouiEngine@1.2.9 (automationName 'YouiEngine')
[Appium] - espresso@2.3.0 (automationName 'Espresso')
[Appium] Available plugins:
[Appium] - images@1.1.10 (ACTIVE)
[Appium] - execute-driver@1.0.5
[Appium] - relaxed-caps@1.0.0-beta.6

**Comment by boneskull** [comment]
The problem here is that the relaxed caps plugin has a default export of its main class, but not a _named_ export equal to its `appium.mainClass` prop in its `package.json`.

**Comment by shraeyakbasu** [comment]
I am still facing the same problem
Is the issue resolved ?

**Comment by jlipps** [comment]
this particular issue is fixed, but another one came up that prevents the plugin working entirely. once https://github.com/appium/appium/pull/17028 is merged and released, hopefully things will work again.
