### ISSUE TITLE
error: 'opencv4nodejs' module is required to use OpenCV features

### ISSUE THREAD

**Issue by crus16** [appium/appium#17041]
## The problem

I solved the problem for screenshot with de PIL's library. On the other hand, when I launch the following command:
el = driver.find_element(AppiumBy.IMAGE, 'battle.png')
I get this error: 
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\NMX-Celia\AppData\Local\Programs\Python\Python310\lib\site-packages\appium\webdriver\webdriver.py", line 414, in find_element
    return self.execute(RemoteCommand.FIND_ELEMENT, {'using': by, 'value': value})['value']
  File "C:\Users\NMX-Celia\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "C:\Users\NMX-Celia\AppData\Local\Programs\Python\Python310\lib\site-packages\appium\webdriver\errorhandler.py", line 30, in check_response
    raise wde
  File "C:\Users\NMX-Celia\AppData\Local\Programs\Python\Python310\lib\site-packages\appium\webdriver\errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "C:\Users\NMX-Celia\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: 'opencv4nodejs' module is required to use OpenCV features. Please install it first ('npm i -g opencv4nodejs') and restart Appium. Read https://github.com/justadudewhohacks/opencv4nodejs#how-to-install for more details on this topic.
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: 'opencv4nodejs' module is required to use OpenCV features. Please install it first ('npm i -g opencv4nodejs') and restart Appium. Read https://github.com/justadudewhohacks/opencv4nodejs#how-to-install for more details on this topic.
    at getResponseForW3CError (C:\Users\NMX-Celia\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\NMX-Celia\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:380:37)

I have followed these steps: https://www.npmjs.com/package/opencv4nodejs
But I keep getting the same error, do you know what it could be?

## Environment

* Appium version: 1.22.3
* Android version: 11

**Comment by crus16** [comment]
Where can I download Appium 2 and the images-plugin?

**Comment by mykola-mokhnach** [comment]
https://appiumpro.com/editions/122-installing-appium-20-and-the-driver-and-plugins-cli

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
