### ISSUE TITLE
Unable to run automation on the desired device

### ISSUE THREAD

**Issue by rekha86sundararajan** [appium/appium#17075]
## The problem

I am moving from Appium 1.x to 2.0. When I try to run my automation on a particular device by providing deviceName, I am getting the below error: 
InvalidArgumentError: property 'deviceName' should not exist on both primary 
    at processCapabilities (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/capabilities.js:290:13)
    at parseCapsForInnerDriver (/usr/local/lib/node_modules/appium/lib/utils.js:127:21)
    at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:241:26)
    at commandExecutor (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.js:73:9)
    at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.js:90:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at defaultBehavior (/usr/local/lib/node_modules/appium/lib/appium.js:666:16) <traceback object at 0x10c580980>

## Environment

* Appium version (or git revision) that exhibits the issue: appium@2.0.0-beta.40
* Last Appium version that did not exhibit the issue (if applicable):
* Driver version that exhibits the issue (only for Appium2): 
             - uiautomator2@2.2.0 [installed (NPM)]
             - xcuitest@4.4.6 [installed (NPM)]
* Last driver version that did not exhibit the issue (if applicable, only for Appium2):
* Desktop OS/version used to run Appium: macOS Big Sur 11.6.6
* Node.js version (unless using Appium.app|exe): v18.3.0
* Package manager name and version (we only officially support NPM): 8.11.0
* Mobile platform/version under test: Android 11
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

## Details

I want to run my automation on specific real device. If I provide the deviceName, it throws the above error. If I don't, it will execute on any of the devices attached. How to overcome this dependency? 

## Link to Appium logs

https://gist.github.com/rekha86sundararajan/a75e8c4178555c8cb21d99b443aa0b77.js

**Comment by mykola-mokhnach** [comment]
To me it looks like there is an issue with the device farm plugin. Does it work properly if you start the same test with this plugin being disabled?

**Comment by rekha86sundararajan** [comment]
Yes. It works without device-farm plugin.

**Comment by saikrishna321** [comment]
@rekha86sundararajan Are you using https://github.com/AppiumTestDistribution/appium-device-farm plugin ?

**Comment by saikrishna321** [comment]
@rekha86sundararajan I see from logs you are using **`device-farm`** plugin. Can you please remove deviceName from your capabilities and try.

**Comment by saikrishna321** [comment]
Not an appium issue. Closing.
