### ISSUE TITLE
session override flag is not working in Appium 1.22.3

### ISSUE THREAD

**Issue by EdulaSuryaKiranReddy** [appium/appium#17101]
## The problem

I'm starting the appium server using java (AppiumDriverLocalService). Post the execution the appium remote session is not closed, when I rerun the same suite appium is using the same port numbers which is causing the failure of the suite (Port already in use). I added the session override flag to overcome the issue, still I'm facing the same issue

Below are the logs:

    [Appium] Welcome to Appium v1.22.3
    [Appium] Non-default server args:
    [Appium]   address: 127.0.0.1
    [Appium]   sessionOverride: true
    [HTTP] Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.
    Fatal Error: listen EADDRINUSE: address already in use 127.0.0.1:4723
    at Server.setupListenHandle [as _listen2] (node:net:1372:16)
    at listenInCluster (node:net:1420:12)
    at doListen (node:net:1559:7)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)

      org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Original error: unexpected end of stream on Connection{127.0.0.1:4723, proxy=DIRECT hostAddress=/127.0.0.1:4723 cipherSuite=none protocol=http/1.1}
      Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
      System info: host: ‘XXXXXXXXX’, ip: '192.168.0.5', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '11.0.10'
      Driver info: driver.version: IOSDriver

	 at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:216)
	 at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:225)
	 at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:247)
	 at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	 at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
	 at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	 at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	 at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	 at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:338)
	 at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	 at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:37)
	 at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:89)
	 at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:99)
	 at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:90)`

## Environment

* Appium version : 1.22.3
* Java Client : 7.5

## Code To Reproduce Issue [ Good To Have ]

    AppiumDriverLocalService service = AppiumDriverLocalService.buildService(new AppiumServiceBuilder().usingPort(4723).usingDriverExecutable(new File("/usr/local/bin/node")).withAppiumJS(new File("/Applications/Appium-1.22.3.app/Contents/Resources/app/node_modules/appium/build/lib/main.js"))
							.withIPAddress("127.0.0.1").withArgument(sessionOverride));

     service.start();

     private static ServerArgument sessionOverride = new ServerArgument() {
		@Override
		public String getArgument() {
			return "--session-override";
		}
	};

**Comment by mykola-mokhnach** [comment]
The session-override flag has nothing to do with the above behaviour. It only enforces a single session to be active at any point of time. Appium does not have any flags to monitor ports for server startup and this is completely the user's responsibility.

**Comment by EdulaSuryaKiranReddy** [comment]
> The session-override flag has nothing to do with the above behaviour. It only enforces a single session to be active at any point of time. Appium does not have any flags to monitor ports for server startup and this is completely the user's responsibility.


but isn't the flag is supposed to kill the previous session before launching the new session on the same port.

Found the previous bug for the same: https://github.com/appium/appium/pull/6445

**Comment by mykola-mokhnach** [comment]
In general I would not rely on these implicit behaviours and make sure the automated test script itself always calls session teardown properly before starting a new one

**Comment by EdulaSuryaKiranReddy** [comment]
Got it, Thanks.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
