### ISSUE TITLE
Can't install appium on ubuntu

### ISSUE THREAD

**Issue by zhangmx** [appium/appium#17130]
## The problem

I have same npm mirror config both in my windows and ubuntu Environment. The windows machine could install appium normally,but ubuntu got some links with 404.

## Environment

* Ubuntu 20.04

## Details

```logs
1120 http fetch GET 200 https://cdn.npmmirror.com/packages/npmlog/4.1.2/npmlog-4.1.2.tgz 29725ms (cache miss)
1121 timing reifyNode:node_modules/appium/node_modules/npmlog Completed in 30186ms
1122 http fetch POST 404 https://registry.npmmirror.com/-/npm/v1/security/audits/quick 28928ms (cache skip)
1123 verbose audit error HttpErrorGeneral: 404 Not Found - POST https://registry.npmmirror.com/-/npm/v1/security/audits/quick
1123 verbose audit error     at /home/mingxing/.nvm/versions/node/v14.19.3/lib/node_modules/npm/node_modules/npm-registry-fetch/lib/check-response.js:93:15
1123 verbose audit error     at runMicrotasks (<anonymous>)
1123 verbose audit error     at processTicksAndRejections (internal/process/task_queues.js:95:5)
1123 verbose audit error     at async Map.[getReport] (/home/mingxing/.nvm/versions/node/v14.19.3/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:333:21)
1123 verbose audit error     at async Map.run (/home/mingxing/.nvm/versions/node/v14.19.3/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:106:19) {
1123 verbose audit error   headers: [Object: null prototype] {
1123 verbose audit error     server: [ 'Tengine' ],
1123 verbose audit error     'content-type': [ 'text/html; charset=utf-8' ],
1123 verbose audit error     'content-length': [ '41' ],
1123 verbose audit error     connection: [ 'keep-alive' ],
1123 verbose audit error     'strict-transport-security': [ 'max-age=5184000' ],
1123 verbose audit error     date: [ 'Tue, 05 Jul 2022 02:17:26 GMT' ],
1123 verbose audit error     vary: [ 'Origin' ],
1123 verbose audit error     'x-frame-options': [ 'SAMEORIGIN' ],
1123 verbose audit error     'x-xss-protection': [ '1; mode=block' ],
1123 verbose audit error     'x-content-type-options': [ 'nosniff' ],
1123 verbose audit error     'x-download-options': [ 'noopen' ],
1123 verbose audit error     'x-readtime': [ '1.969' ],
1123 verbose audit error     'content-encoding': [ 'gzip' ],
1123 verbose audit error     'ali-swift-global-savetime': [ '1656987446' ],
1123 verbose audit error     via: [
1123 verbose audit error       'cache28.l2cn1837[27,27,404-1280,M], cache5.l2cn1837[28,0], kunlun3.cn1361[47,46,404-1280,M], kunlun8.cn1361[50,0]'
1123 verbose audit error     ],
1123 verbose audit error     'x-cache': [ 'MISS TCP_MISS dirn:-2:-2' ],
1123 verbose audit error     'x-swift-savetime': [ 'Tue, 05 Jul 2022 02:17:26 GMT' ],
1123 verbose audit error     'x-swift-cachetime': [ '1' ],
1123 verbose audit error     'x-swift-error': [ 'orig response 4XX error' ],
1123 verbose audit error     'timing-allow-origin': [ '*' ],
1123 verbose audit error     eagleid: [ 'b706e79c16569874460441920e' ],
1123 verbose audit error     'x-fetch-attempts': [ '1' ],
1123 verbose audit error     'x-local-cache-status': [ 'skip' ]
1123 verbose audit error   },
1123 verbose audit error   statusCode: 404,
```

## Link to Appium logs

[npm install appium logs ](https://gist.github.com/zhangmx/ec83fd5c2a5a4007244b9a056efa5c00)

## Thank you for help me

I'm using the desktop version now，but realy want to know how to fix it.

I have tried run below commands many times,but it does not work.

```
npm cache clear --force
npm config set registry https://registry.npmjs.org
```

**Comment by zhangmx** [comment]
I do not know why,but after reboot ubuntu system and run:
```
npm install -g appium --unsafe-perm=true --allow-root
```
it works.

https://github.com/appium/appium/issues/12319#issuecomment-474211593

when I use `yarn global add appium` ,I got error with appium-chromedriver 404.
