### ISSUE TITLE
Every test is failing on CI machine but not locally for some reason

### ISSUE THREAD

**Issue by tking16** [appium/appium#17249]
## The problem

Hi, all my tests have suddenly started failing for some reason when running on our Macmini, when I try to replicate the issue on my local machine all is well... The iOS devs on my team are also confused when I show them this error/warning 
```
WARNING: Failed to gather app_strings: Message: An unknown server-side error occurred while processing the command. Original error: No '/Users/jenkins/build-workspace/workspace/ios-at-tests/testing/app-at/testApp.app/en.lproj' resources folder has been found
``` 
(I'm not even sure this is what's failing all the tests)

## Environment

* Appium version: Latest Beta
* Mac OS Montery 12.2.1
* Node.js version: v16.16.0
* Npm v8.11.0
* iPhone 11 Pro Emulator: 15.2
* Appium CLI

[## Link to Appium logs](https://gist.github.com/tking16/925bbb58918a3cb9b555658ecd92fbff)

Thanks for any insights

**Comment by KazuCocoa** [comment]
What files/directories did the app have?

```
/Users/jenkins/build-workspace/workspace/ios-at-tests/testing/app-at/TestApp.app
```

**Comment by tking16** [comment]
@KazuCocoa No directories, The app is basically created via a Jenkins job using [gym](https://docs.fastlane.tools/actions/gym/). That .app then gets compressed and pushed up to SonaType where the test job then pulls it down via a curl command and starts running the tests.

Is looking for something? As it's been like this for ages but is only now failing.

**Comment by KazuCocoa** [comment]
> No '/Users/jenkins/build-workspace/workspace/ios-at-tests/testing/app-at/testApp.app/en.lproj' resources folder has been found

Appium tried to parse the language resources in the server, but no resource was found. I wonder if what kind of files/directories existed in the `TestApp.app`. Usually, you can see the files with `ls` command like `ls /Users/jenkins/build-workspace/workspace/ios-at-tests/testing/app-at/TestApp.app` if the app exists.

```
2022-07-20 12:57:31:411 [HTTP] --> POST /wd/hub/session/6728f8c8-65d0-475c-b88c-48539dd56ce5/appium/app/strings
2022-07-20 12:57:31:411 [HTTP] {}
2022-07-20 12:57:31:416 [XCUITestDriver@49d7 (6728f8c8)] Calling AppiumDriver.getStrings() with args: [null,null,"6728f8c8-65d0-475c-b88c-48539dd56ce5"]
2022-07-20 12:57:31:416 [XCUITestDriver@49d7 (6728f8c8)] Executing command 'getStrings'
2022-07-20 12:57:31:416 [XCUITestDriver@49d7 (6728f8c8)] Gettings strings for language 'undefined' and string file 'null'
2022-07-20 12:57:31:423 [XCUITestDriver@49d7 (6728f8c8)] Encountered internal error running command: Error: No '/Users/jenkins/build-workspace/workspace/ios-at-tests/testing/app-at/TestApp.app/en.lproj' resources folder has been found
2022-07-20 12:57:31:424 [XCUITestDriver@49d7 (6728f8c8)]     at parseLocalizableStrings (/Users/jenkins/build-workspace/workspace/ios-at-tests/testing/app-at/node_modules/appium-xcuitest-driver/lib/app-utils.js:105:13)
2022-07-20 12:57:31:424 [XCUITestDriver@49d7 (6728f8c8)]     at XCUITestDriver.getStrings (/Users/jenkins/build-workspace/workspace/ios-at-tests/testing/app-at/node_modules/appium-xcuitest-driver/lib/commands/general.js:179:10)
2022-07-20 12:57:31:442 [HTTP] <-- POST /wd/hub/session/6728f8c8-65d0-475c-b88c-48539dd56ce5/appium/app/strings 500 32 ms - 829
2022-07-20 12:57:31:443 [HTTP] 
```

**Comment by tking16** [comment]
Here's the `ls` if it's at all helpful

```
0c158c11-bb0f-48ac-8004-609fd2a5f5e0.png
0d14ab89-212f-4f7c-8f80-4301f12092ba.png
0fd3fcd1-b3b7-4b70-aca7-a1b4ca4c1e1a.png
18fd98b4-4dd6-44cf-ab68-ec3a147b6b21.png
1cea19ab-867b-44b9-9db4-fbe41abdc745.png
214aff64-9060-46c4-8b6e-346111ff880b.png
376472ce-2f35-44ab-bf4e-75991bc1e3e5.png
383a0930-9d54-4abc-be09-822d51e513cd.png
38bfc48f-9da8-4f21-ad29-bb6c17861074.png
390619cb-4a6a-4452-8be9-39ddabef7961.png
4ae380f1-85b9-4d31-9f4b-05d3daa14618.png
54f21448-4842-471f-bf74-f56dc13ae602.png
57096816-cab1-42af-8adc-2bab1cb32f7d.png
5788afe3-9167-479b-af17-12eb9589c9a1.png
64451211-0e03-4344-85e6-daff113827bc.png
64ca43ba-7e8c-4cd9-ace9-c749e60e6216.png
6addfb3a-83fb-432d-bdd8-8d1ca5a20a48.png
72ef0125-46a3-4876-9d93-23dc97ed92d5.png
827ba3c3-f807-47f6-980c-b9bb96d0b97f.png
84b61061-66a2-4f98-b7b1-b843be88bfc9.png
85d642aa-9f7e-4031-8601-f4e0a517908b.png
86ec4301-155c-4a45-9373-600c3d124545.png
95d5fdb2-8b2c-4894-96ef-c24f6c5a1b18.png
98e37d96-1d42-4c8f-98a8-c696821b9985.png
9a1eb6eb-15f0-4317-975e-7348253d5798.png
AppIcon60x60@2x.png
AppIcon76x76@2x~ipad.png
Assets.car
BebasNeue-Regular.ttf
FeatureFlags.json
Frameworks
GlobalConfig.json
TestApp
GoogleService-Info-Debug.plist
GoogleService-Info-Release.plist
Info.plist
LaunchScreen.storyboardc
PkgInfo
PlugIns
_CodeSignature
a231e4ba-904a-4bf9-a3fe-70e0c951ebcd.png
c0701807-b9c5-4ba0-80c8-ffebdffcff15.png
ce4ca9c2-f3fb-4c49-a185-ab51c8547fc4.png
d03cbe9e-bc9e-4b46-8c81-a4c697fb8d72.png
d5119e87-1ba3-485d-876b-b2ad29d135f8.png
da346ece-9789-4b0c-9883-fb96a4c445c1.png
dfd00046-6d08-49b8-bad0-408278b56b91.png
ec115c55-f2ae-4409-a985-ca7a1028ba74.png
ee0fb1e4-899e-45d5-82ec-f936b917ceba.png
f54b9332-5bf1-427f-abb3-8af66e08d117.png
f6ef9109-6b51-4b3f-a3cb-392715e5af34.png
placeholder.mp4
```

**Comment by tking16** [comment]
No it happens after booting up appium. Oddly enough in the exact same environment it works completely fine when I run it not from Jenkins, their may be an issue with the build commands or something

**Comment by tking16** [comment]
After restarting the machine it seems to be running okay again... This is probably gonna happen again so a bit annoyed I never figured out what the issue was 🤔. Thanks for the help anyway @KazuCocoa

**Comment by KazuCocoa** [comment]
Hmm, It's weird... but let me close this for now. Maybe something packaging creation? or something got weird
