### ISSUE TITLE
Update fails for espresso driver from 2.7.1 to 2.8.0.

### ISSUE THREAD

**Issue by cmaganu** [appium/appium#17278]
## The problem

Update fails for espresso driver from 2.7.1 to 2.8.0.

## Environment

* Appium version (or git revision) that exhibits the issue: 2.0.0-beta.40
* Last Appium version that did not exhibit the issue (if applicable): -
* Desktop OS/version used to run Appium: Linux(Ubuntu 20.10)
* Node.js version (unless using Appium.app|exe): v16.14.2
* Npm or Yarn package manager: npm 8.13.2
* Mobile platform/version under test: -
* Real device or emulator/simulator: -
* Appium CLI or Appium.app|exe: -

## Details

```
cmaganu@cma-x1:~$ appium driver update espresso
✔ Checking if driver 'espresso' is updatable
✔ Checking if driver 'espresso' needs an update
✖ Installing 'espresso' using NPM install spec 'appium-espresso-driver@2.8.0'
✖ Updating driver 'espresso' from 2.7.1 to 2.8.0
ℹ Update report:
✖   - 'espresso' failed to update: Error: ✖ Encountered an error when installing package: npm command 'install --save-dev --save-exact --global-style --no-package-lock appium-espresso-driver@2.8.0 --json' failed with code 1.

STDOUT:


STDERR:
npm ERR! code 1
npm ERR! path /home/cmaganu/.appium/node_modules/appium-espresso-driver/node_modules/appium-chromedriver
npm ERR! command failed
npm ERR! command sh -c /tmp/postinstall65899685932.sh
npm ERR! [11:26:56] Project not yet built; building...
npm ERR! /home/cmaganu/.appium/node_modules/appium-espresso-driver/node_modules/teen_process/lib/exec.js:113
npm ERR!         let err = new Error(`Command '${rep}' exited with code ${code}`);
npm ERR!                   ^
npm ERR! Error: Command 'npm run build' exited with code 127
npm ERR!     at ChildProcess.<anonymous> (/home/cmaganu/.appium/node_modules/appium-espresso-driver/node_modules/teen_process/lib/exec.js:113:19)
npm ERR!     at ChildProcess.emit (node:events:526:28)
npm ERR!     at maybeClose (node:internal/child_process:1092:16)
npm ERR!     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
{
  "error": {
    "code": 1,
    "summary": "command failed",
    "detail": "sh -c /tmp/postinstall65899685932.sh\n[11:26:56] Project not yet built; building...\n/home/cmaganu/.appium/node_modules/appium-espresso-driver/node_modules/teen_process/lib/exec.js:113\n        let err = new Error(`Command '${rep}' exited with code ${code}`);\n                  ^\nError: Command 'npm run build' exited with code 127\n    at ChildProcess.<anonymous> (/home/cmaganu/.appium/node_modules/appium-espresso-driver/node_modules/teen_process/lib/exec.js:113:19)\n    at ChildProcess.emit (node:events:526:28)\n    at maybeClose (node:internal/child_process:1092:16)\n    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)"
  }
}

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/cmaganu/.npm/_logs/2022-07-28T08_26_32_131Z-debug-0.log
```

## Link to Appium logs

https://gist.github.com/cmaganu/de61e3370a06e207c870c2bf683b912a

**Comment by mykola-mokhnach** [comment]
Are you able to run `npm install appium-chromedriver`? What is the actual error if not?

**Comment by cmaganu** [comment]
No.
```
cmaganu@cma-x1:~$ npm install appium-chromedriver
npm ERR! code 1
npm ERR! path /home/cmaganu/node_modules/appium-chromedriver
npm ERR! command failed
npm ERR! command sh -c /tmp/postinstall65899832274.sh
npm ERR! [11:51:42] Project not yet built; building...
npm ERR! /home/cmaganu/node_modules/teen_process/lib/exec.js:113
npm ERR!         let err = new Error(`Command '${rep}' exited with code ${code}`);
npm ERR!                   ^
npm ERR! Error: Command 'npm run build' exited with code 127
npm ERR!     at ChildProcess.<anonymous> (/home/cmaganu/node_modules/teen_process/lib/exec.js:113:19)
npm ERR!     at ChildProcess.emit (node:events:526:28)
npm ERR!     at maybeClose (node:internal/child_process:1092:16)
npm ERR!     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/cmaganu/.npm/_logs/2022-07-28T08_51_22_755Z-debug-0.log
```
full log https://gist.github.com/cmaganu/1ca5f53fd0403a3af4966c7d2c299e0a

**Comment by cmaganu** [comment]
It's fixed. Update to 2.8.1 now works.

**Comment by mykola-mokhnach** [comment]
Closed as fixed
