### ISSUE TITLE
Cannot switch to Chrome web context from native: Cannot proxy command

### ISSUE THREAD

**Issue by nextlevelbeard** [appium/appium#17275]
Version: 2.0.0-beta.40
Chrome version on Android: latest 103+
Chromedriver autodownloaded compatible version.

1. On Appium Inspector, open basic Android session, No app packages/activities/apps capabilities defined.
3. Open Chrome on Android.
4. With Inspector switch context to "WEBVIEW_chrome"

Command times outs. Error is 

```shell
[debug] [Chromedriver@e03a] UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: timeout of 240000ms exceeded
[debug] [Chromedriver@e03a]     at JWProxy.command (/Users//repos//node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:342:13)
[debug] [Chromedriver@e03a]     at runMicrotasks (<anonymous>)
[debug] [Chromedriver@e03a]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[debug] [Chromedriver@e03a]     at Chromedriver.startSession (/Users//repos//node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/lib/chromedriver.js:598:5)
[debug] [Chromedriver@e03a]     at Chromedriver.start (/Users//repos//node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/lib/chromedriver.js:529:7)
[debug] [Chromedriver@e03a]     at AndroidUiautomator2Driver.setupNewChromedriver (/Users//repos//node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/context.js:471:3)
[debug] [Chromedriver@e03a]     at AndroidUiautomator2Driver.startChromedriverProxy (/Users//repos//node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/context.js:217:10)
[debug] [Chromedriver@e03a]     at AndroidUiautomator2Driver.switchContext (/Users//repos//node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/context.js:124:5)
[debug] [Chromedriver@e03a]     at AndroidUiautomator2Driver.setContext (/Users//repos//node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/context.js:51:3)
[Chromedriver@e03a] Chromedriver exited unexpectedly with code null, signal SIGTERM
[debug] [Chromedriver@e03a] Changed state to 'stopped'
[Chromedriver@e03a] An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: timeout of 240000ms exceeded
[debug] [AndroidUiautomator2Driver@0317 (43ccfa0c)] Encountered internal error running command: Error: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: timeout of 240000ms exceeded
[debug] [AndroidUiautomator2Driver@0317 (43ccfa0c)]     at Object.errorAndThrow (/Users//repos//node_modules/@appium/support/lib/logging.js:115:34)
[debug] [AndroidUiautomator2Driver@0317 (43ccfa0c)]     at Chromedriver.start (/Users//repos//node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/lib/chromedriver.js:554:16)
[debug] [AndroidUiautomator2Driver@0317 (43ccfa0c)]     at AndroidUiautomator2Driver.setupNewChromedriver (/Users//repos//node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/context.js:471:3)
[debug] [AndroidUiautomator2Driver@0317 (43ccfa0c)]     at AndroidUiautomator2Driver.startChromedriverProxy (/Users//repos//node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/context.js:217:10)
[debug] [AndroidUiautomator2Driver@0317 (43ccfa0c)]     at AndroidUiautomator2Driver.switchContext (/Users//repos//node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/context.js:124:5)
[debug] [AndroidUiautomator2Driver@0317 (43ccfa0c)]     at AndroidUiautomator2Driver.setContext (/Users//repos//node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/context.js:51:3)
```

Previous output:
```shell
[debug] [AndroidDriver] Getting a list of available webviews
[debug] [ADB] Running '/Users//Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell cat /proc/net/unix'
[debug] [AndroidDriver] Parsed 1 active devtools socket: ["@chrome_devtools_remote"]
[debug] [AndroidDriver] Collecting CDP data of 1 webview
[debug] [AndroidDriver] Forwarding remote port chrome_devtools_remote to a local port in range 10900..11000
[debug] [AndroidDriver] You could use the 'webviewDevtoolsPort' capability to customize the starting port number
[debug] [ADB] Running '/Users//Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward tcp:10900 localabstract:chrome_devtools_remote'
[debug] [ADB] Removing forwarded port socket connection: 10900
[debug] [ADB] Running '/Users//Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward --remove tcp:10900'
[debug] [AndroidDriver] CDP data collection completed
[debug] [AndroidDriver] Found 1 webview: ["WEBVIEW_chrome"]
[debug] [AndroidUiautomator2Driver@0317 (43ccfa0c)] Available contexts: ["NATIVE_APP","WEBVIEW_chrome"]
[debug] [AndroidUiautomator2Driver@0317 (43ccfa0c)] Responding to client with driver.getContexts() result: ["NATIVE_APP","WEBVIEW_chrome"]
[HTTP] <-- GET /session/43ccfa0c-a4ec-407b-a496-d980a276f6f6/contexts 200 160 ms - 41
[HTTP] --> POST /session/43ccfa0c-a4ec-407b-a496-d980a276f6f6/context
[HTTP] {"name":"WEBVIEW_chrome"}
[debug] [AndroidUiautomator2Driver@0317 (43ccfa0c)] Calling AppiumDriver.setContext() with args: ["WEBVIEW_chrome","43ccfa0c-a4ec-407b-a496-d980a276f6f6"]
[debug] [AndroidDriver] Getting a list of available webviews
[debug] [ADB] Running '/Users//Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell cat /proc/net/unix'
[debug] [AndroidDriver] Parsed 1 active devtools socket: ["@chrome_devtools_remote"]
[debug] [AndroidDriver] Collecting CDP data of 1 webview
[debug] [AndroidDriver] Forwarding remote port chrome_devtools_remote to a local port in range 10900..11000
[debug] [AndroidDriver] You could use the 'webviewDevtoolsPort' capability to customize the starting port number
[debug] [ADB] Running '/Users//Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward tcp:10900 localabstract:chrome_devtools_remote'
[debug] [ADB] Removing forwarded port socket connection: 10900
[debug] [ADB] Running '/Users//Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward --remove tcp:10900'
[debug] [AndroidDriver] CDP data collection completed
[debug] [AndroidDriver] Found 1 webview: ["WEBVIEW_chrome"]
[debug] [AndroidUiautomator2Driver@0317 (43ccfa0c)] Available contexts: ["NATIVE_APP","WEBVIEW_chrome"]
[debug] [AndroidUiautomator2Driver@0317 (43ccfa0c)] Connecting to chrome-backed webview context 'WEBVIEW_chrome'
[AndroidUiautomator2Driver@0317 (43ccfa0c)] The 'chromeDriverPort' capability is deprecated. Please use 'chromedriverPort' instead
[debug] [AndroidUiautomator2Driver@0317 (43ccfa0c)] Using user-specified port 51579 for chromedriver
[debug] [AndroidUiautomator2Driver@0317 (43ccfa0c)] Passing web view details to the Chromedriver constructor: {
[debug] [AndroidUiautomator2Driver@0317 (43ccfa0c)]   "info": {
[debug] [AndroidUiautomator2Driver@0317 (43ccfa0c)]     "Android-Package": "com.android.chrome",
[debug] [AndroidUiautomator2Driver@0317 (43ccfa0c)]     "Browser": "Chrome/103.0.5060.129",
[debug] [AndroidUiautomator2Driver@0317 (43ccfa0c)]     "Protocol-Version": "1.3",
[debug] [AndroidUiautomator2Driver@0317 (43ccfa0c)]     "User-Agent": "Mozilla/5.0 (Linux; Android 12; sdk_gphone64_arm64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Mobile Safari/537.36",
[debug] [AndroidUiautomator2Driver@0317 (43ccfa0c)]     "V8-Version": "10.3.174.20",
[debug] [AndroidUiautomator2Driver@0317 (43ccfa0c)]     "WebKit-Version": "537.36 (@3b966227dfaedec608752547bbc8bcbb4d7f400d)",
[debug] [AndroidUiautomator2Driver@0317 (43ccfa0c)]     "webSocketDebuggerUrl": "ws://127.0.0.1:10900/devtools/browser"
[debug] [AndroidUiautomator2Driver@0317 (43ccfa0c)]   },
[debug] [AndroidUiautomator2Driver@0317 (43ccfa0c)]   "process": {
[debug] [AndroidUiautomator2Driver@0317 (43ccfa0c)]     "name": "chrome",
[debug] [AndroidUiautomator2Driver@0317 (43ccfa0c)]     "id": null
[debug] [AndroidUiautomator2Driver@0317 (43ccfa0c)]   }
[debug] [AndroidUiautomator2Driver@0317 (43ccfa0c)] }
[debug] [AndroidDriver] Precalculated Chromedriver capabilities: {
[debug] [AndroidDriver]   "androidPackage": "com.android.chrome",
[debug] [AndroidDriver]   "androidUseRunningApp": true,
[debug] [AndroidDriver]   "androidDeviceSerial": "emulator-5554"
[debug] [AndroidDriver] }
[debug] [AndroidUiautomator2Driver@0317 (43ccfa0c)] Before starting chromedriver, androidPackage is 'com.android.chrome'
[debug] [Chromedriver@e03a] Changed state to 'starting'
[debug] [Chromedriver@e03a] Using the static Chromedriver->Chrome mapping
[debug] [Chromedriver@e03a] The most recent known Chrome version: 103.0.5060
[debug] [Chromedriver@e03a] Found 3 executables in '/Users//repos//node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/chromedriver/mac'
[debug] [Chromedriver@e03a] The following Chromedriver executables were found:
[debug] [Chromedriver@e03a]     '/Users//repos//node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver_mac64_v103.0.5060.53' (version '103.0.5060.53', minimum Chrome version '103.0.5060')
[debug] [Chromedriver@e03a]     '/Users//repos//node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver_mac64_v91.0.4472.101' (version '91.0.4472.101', minimum Chrome version '91.0.4472')
[debug] [Chromedriver@e03a]     '/Users//repos//node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver_mac64_v91.0.4472.19' (version '91.0.4472.19', minimum Chrome version '91.0.4472')
[debug] [Chromedriver@e03a] Browser version in the supplied details: Chrome/103.0.5060.129
[debug] [Chromedriver@e03a] Found Chrome bundle 'undefined' version '103.0.5060'
[debug] [Chromedriver@e03a] Found 1 executable capable of automating Chrome '103.0.5060'.
[debug] [Chromedriver@e03a] Choosing the most recent, '/Users//repos//node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver_mac64_v103.0.5060.53'.
[debug] [Chromedriver@e03a] If a specific version is required, specify it with the `chromedriverExecutable`desired capability.
[Chromedriver@e03a] Set chromedriver binary as: /Users//repos//node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver_mac64_v103.0.5060.53
[debug] [Chromedriver@e03a] Killing any old chromedrivers, running: pkill -15 -f "/Users//repos//node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver_mac64_v103.0.5060.53.*--port=51579"
[Chromedriver@e03a] No old chromedrivers seem to exist
[debug] [Chromedriver@e03a] Cleaning this device's adb forwarded port socket connections: emulator-5554
[debug] [ADB] List forwarding ports
[debug] [ADB] Running '/Users//Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward --list'
[Chromedriver@e03a] Spawning chromedriver with: /Users//repos//node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver_mac64_v103.0.5060.53 --port=51579 --adb-port=5037 --verbose
[debug] [Chromedriver@e03a] Chromedriver version: '103.0.5060.53'
[debug] [Chromedriver@e03a] Matched '/status' to command name 'getStatus'
[debug] [Chromedriver@e03a] Proxying [GET /status] to [GET http://127.0.0.1:51579/status] with no body
[Chromedriver@e03a] connect ECONNREFUSED 127.0.0.1:51579
[debug] [Chromedriver@e03a] Matched '/status' to command name 'getStatus'
[debug] [Chromedriver@e03a] Proxying [GET /status] to [GET http://127.0.0.1:51579/status] with no body
[debug] [Chromedriver@e03a] Got response with status 200: {"value":{"build":{"version":"103.0.5060.53 (a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853})"},"message":"ChromeDriver ready for new sessions.","os":{"arch":"arm64","name":"Mac OS X","version":"12.4.0"},"ready":true}}
[Chromedriver@e03a] Starting W3C Chromedriver session with capabilities: {
[Chromedriver@e03a]   "capabilities": {
[Chromedriver@e03a]     "alwaysMatch": {
[Chromedriver@e03a]       "goog:chromeOptions": {
[Chromedriver@e03a]         "androidPackage": "com.android.chrome",
[Chromedriver@e03a]         "androidUseRunningApp": true,
[Chromedriver@e03a]         "androidDeviceSerial": "emulator-5554"
[Chromedriver@e03a]       },
[Chromedriver@e03a]       "goog:loggingPrefs": {
[Chromedriver@e03a]         "browser": "ALL"
[Chromedriver@e03a]       }
[Chromedriver@e03a]     }
[Chromedriver@e03a]   }
[Chromedriver@e03a] }
[debug] [Chromedriver@e03a] Matched '/session' to command name 'createSession'
[debug] [Chromedriver@e03a] Proxying [POST /session] to [POST http://127.0.0.1:51579/session] with body: {"capabilities":{"alwaysMatch":{"goog:chromeOptions":{"androidPackage":"com.android.chrome","androidUseRunningApp":true,"androidDeviceSerial":"emulator-5554"},"goog:loggingPrefs":{"browser":"ALL"}}}}
[debug] [Chromedriver@e03a] Webview version: 'Chrome/103.0.5060.129'
```

**Comment by mykola-mokhnach** [comment]
I don't observe any issues with Appium there. It tries to proxy the request to chromedriver and the latter times out. Try reporting your issue to Google.

**Comment by mykola-mokhnach** [comment]
You could also check logcat - it might contain some more useful information.

**Comment by KazuCocoa** [comment]
Potentially this is in chrome custom tab's issue(?).
I was able to switch webview like `WEBVIEW_io.appium.android.apis` with our sample app on a real device.
The OS was 11, it had `Chrome/103.0.5060.129` and chromedriver was `chromedriver_mac64_v103.0.5060.53`

**Comment by KazuCocoa** [comment]
Used https://github.com/GoogleChrome/android-browser-helper/tree/main/demos/custom-tabs-example-app as an example. https://gist.github.com/KazuCocoa/fb96bc842db67523d5c060515bf1b211

It seems like chromedriver failed to create a session.
```
[Chromedriver@64d4] Starting W3C Chromedriver session with capabilities: {
[Chromedriver@64d4]   "capabilities": {
[Chromedriver@64d4]     "alwaysMatch": {
[Chromedriver@64d4]       "goog:chromeOptions": {
[Chromedriver@64d4]         "androidPackage": "com.brave.browser",
[Chromedriver@64d4]         "androidUseRunningApp": true,
[Chromedriver@64d4]         "androidDeviceSerial": "D0AA002182JC0202126",
[Chromedriver@64d4]         "args": [
[Chromedriver@64d4]           "--disable-popup-blocking"
[Chromedriver@64d4]         ]
[Chromedriver@64d4]       },
[Chromedriver@64d4]       "goog:loggingPrefs": {
[Chromedriver@64d4]         "browser": "ALL"
[Chromedriver@64d4]       }
[Chromedriver@64d4]     }
[Chromedriver@64d4]   }
[Chromedriver@64d4] }
[debug] [Chromedriver@64d4] Matched '/session' to command name 'createSession'
[debug] [Chromedriver@64d4] Proxying [POST /session] to [POST http://127.0.0.1:8000/session] with body: {"capabilities":{"alwaysMatch":{"goog:chromeOptions":{"androidPackage":"com.brave.browser","androidUseRunningApp":true,"androidDeviceSerial":"D0AA002182JC0202126","args":["--disable-popup-blocking"]},"goog:loggingPrefs":{"browser":"ALL"}}}}
[Chromedriver@64d4] Got response with status 500: {"value":{"error":"unknown error","message":"unknown error: Failed to get sockets matching: @weblayer_devtools_remote_.*32236\n  (make sure the app has its WebView/WebLayer configured for debugging)","stacktrace":"0   chromedriver_mac64_v103.0.5060.53   0x0000000107dfa079 chromedriver_mac64_v103.0.5060.53 + 4444281\n1   chromedriver_mac64_v103.0.5060.53   0x0000000107d86403 chromedriver_mac64_v103.0.5060.53 + 3970051\n2   chromedriver_mac64_v103.0.5060.53   0x0000000107a21038 chromedriver_mac64_v103.0.5060.53 + 409656\n3   chromedriver_mac64_v103.0.5060.53   0x00000001079fe393 chromedriver_mac64_v103.0.5060.53 + 267155\n4   chromedriver_mac64_v103.0.5060.53   0x0000000107a08fb0 chromedriver_mac64_v103.0.5060.53 + 311216\n5   chromedriver_mac64_v103.0.5060.53   0x0000000107a084ae chromedriver_mac64_v103.0.5060.53 + 308398\n6   chromedriver_mac64_v103.0.5060.53   0x0000000107a4110f chromedriver_mac64_v103.0.5060.53 + 540943\n7   chromedriver_mac64_v103.0.5060.53   0x0000000107a7a44a chromedriver_mac64_v103.0...
[debug] [W3C] Matched W3C error code 'unknown error' to UnknownError
[debug] [Chromedriver@64d4] UnknownError: An unknown server-side error occurred while processing the command. Original error: unknown error: Failed to get sockets matching: @weblayer_devtools_remote_.*32236
[debug] [Chromedriver@64d4]   (make sure the app has its WebView/WebLayer configured for debugging)
[debug] [Chromedriver@64d4]     at errorFromW3CJsonCode (/Users/kazuaki/GitHub/appium-flutter-driver/driver/node_modules/@appium/base-driver/lib/protocol/errors.js:923:25)
[debug] [Chromedriver@64d4]     at ProxyRequestError.getActualError (/Users/kazuaki/GitHub/appium-flutter-driver/driver/node_modules/@appium/base-driver/lib/protocol/errors.js:798:14)
[debug] [Chromedriver@64d4]     at JWProxy.command (/Users/kazuaki/GitHub/appium-flutter-driver/driver/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:340:19)
[debug] [Chromedriver@64d4]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[debug] [Chromedriver@64d4]     at Chromedriver.startSession (/Users/kazuaki/GitHub/appium-flutter-driver/driver/node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/lib/chromedriver.js:598:5)
[debug] [Chromedriver@64d4]     at Chromedriver.start (/Users/kazuaki/GitHub/appium-flutter-driver/driver/node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/lib/chromedriver.js:529:7)
[debug] [Chromedriver@64d4]     at AndroidUiautomator2Driver.setupNewChromedriver (/Users/kazuaki/GitHub/appium-flutter-driver/driver/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/context.js:471:3)
[debug] [Chromedriver@64d4]     at AndroidUiautomator2Driver.startChromedriverProxy (/Users/kazuaki/GitHub/appium-flutter-driver/driver/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/context.js:217:10)
[debug] [Chromedriver@64d4]     at AndroidUiautomator2Driver.switchContext (/Users/kazuaki/GitHub/appium-flutter-driver/driver/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/context.js:124:5)
[debug] [Chromedriver@64d4]     at AndroidUiautomator2Driver.setContext (/Users/kazuaki/GitHub/appium-flutter-driver/driver/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/context.js:51:3)
[Chromedriver@64d4] Chromedriver exited unexpectedly with code null, signal SIGTERM
[debug] [Chromedriver@64d4] Changed state to 'stopped'
```

**Comment by nextlevelbeard** [comment]
I've noticed something on the logs I posted:
```
The 'chromeDriverPort' capability is deprecated. Please use 'chromedriverPort' instead
```

Maybe we need to update this?
I would imagine that not being able to pass a port properly would make the connection unreachable.

**Comment by KazuCocoa** [comment]
I observed this error before. Rebooting the device fixed this error at that time. Then, chrome itself seems not to respond. chromedriver raised a timeout error when I sent the new session request directly to the chromedriver.

```
[debug] [Chromedriver@e03a] UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: timeout of 240000ms exceeded
```

if so (I mean chrome/chromedriver's behavior), only Google can fix it

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
