### ISSUE TITLE
uncaughtException: write EPIPE in appium server log file (using custom log file)

### ISSUE THREAD

**Issue by cmaganu** [appium/appium#17280]
## The problem
Errors are written to the appium server log file when the server is shutting down.

## Environment

* Appium version (or git revision) that exhibits the issue: 2.0.0-beta.40
* Last Appium version that did not exhibit the issue (if applicable): -
* Desktop OS/version used to run Appium: Ubuntu 20.10
* Node.js version (unless using Appium.app|exe): v16.14.2
* Npm or Yarn package manager: 8.13.2
* Mobile platform/version under test: Android 12
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: -

## Details
I'm starting the appium from the java-client with the following log related options
```
  .withLogFile(new File("./logs/appium-server.log"))
  .withArgument(GeneralServerFlag.LOG_TIMESTAMP)
```
the test runs ok, but I get errors like
```
2022-07-28 13:46:27:711 [Appium] Received SIGTERM - shutting down
2022-07-28 13:46:27:765 [AppiumDriver@2a63] There are no active sessions for cleanup
2022-07-28 13:46:27:769 uncaughtException: write EPIPE
Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:795:11)
    at Socket._write (node:net:807:8)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at Console.log (/home/cmaganu/.nvm/versions/node/v16.14.2/lib/node_modules/appium/node_modules/winston/lib/winston/transports/console.js:79:23)
    at Console._write (/home/cmaganu/.nvm/versions/node/v16.14.2/lib/node_modules/appium/node_modules/winston-transport/index.js:103:17)
    at doWrite (/home/cmaganu/.nvm/versions/node/v16.14.2/lib/node_modules/appium/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/home/cmaganu/.nvm/versions/node/v16.14.2/lib/node_modules/appium/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at Console.Writable.write (/home/cmaganu/.nvm/versions/node/v16.14.2/lib/node_modules/appium/node_modules/readable-stream/lib/_stream_writable.js:307:11)
    at DerivedLogger.ondata (/home/cmaganu/.nvm/versions/node/v16.14.2/lib/node_modules/appium/node_modules/readable-stream/lib/_stream_readable.js:681:20)
    at DerivedLogger.emit (node:events:538:35)
```
in the server log file

## Link to Appium logs
[full log](https://gist.github.com/cmaganu/87f6ff225ba7c63d95a2ca579bb9ae35) - errors at the end

**Comment by mykola-mokhnach** [comment]
This could be an issue in [winston](https://www.npmjs.com/package/winston) logger. Although I have no idea on why it happens or how it could be resolved.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
