### ISSUE TITLE
Appium inspector stopped working after upgrading iOS version!

### ISSUE THREAD

**Issue by Robot1988** [appium/appium#17293]
<img width="1314" alt="Screenshot 2022-07-31 at 12 58 30 PM" src="https://user-images.githubusercontent.com/94165470/182022471-7df1298b-7332-45b0-b474-649f73c95d3a.png">

All the configurations were made for mobile ios automation and was working perfectly fine.
Once I upgraded my mobile iOS to latest things stopped working, I upgraded XCode, Appium desktop, Appium inspector everything to latest. Using XCode I am able to access my mobile iOS now, but Appium inspector is failing, its showing “Gathering initial app source” and keeps looping. I am unable to downgrade iOS version to older version as its against my company policy, how to get this fixed. Tried everything from internet its not working.

Appium desktop Version - 1.22.3
Appium Inspector Version - 2022.7.1
Xcode Version - 13.4.1
iOS Version - 15.6

**Comment by mykola-mokhnach** [comment]
Sorry, we cannot help without the server logs.

Also, we don't maintain Appium 1 anymore. Consider switching to Appium 2

**Comment by Robot1988** [comment]
[debug] [35m[WebDriverAgent][39m WebDriverAgent successfully started after 19784ms
[debug] [35m[BaseDriver][39m Event 'wdaSessionAttempted' logged at 1659325265016 (09:11:05 GMT+0530 (India Standard Time))
[debug] [35m[XCUITest][39m Sending createSession command to WDA
[debug] [35m[WD Proxy][39m Matched '/session' to command name 'createSession'
[debug] [35m[WD Proxy][39m Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"org.worldbank.wbapprovalsiphoneemsqa","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true,"shouldTerminateApp":true,"forceAppLaunch":true,"useNativeCachingStrategy":true,"forceSimulatorSoftwareKeyboardPresence":false}],"alwaysMatch":{}}}[debug] [35m[WD Proxy][39m Got response with status 200: {"value":{"sessionId":"46E1C0CD-4256-4203-8A2C-01C88DDAF54D","capabilities":{"device":"iphone","browserName":"Approvals_QA","sdkVersion":"15.6","CFBundleIdentifier":"org.worldbank.wbapprovalsiphoneemsqa"}},"sessionId":"46E1C0CD-4256-4203-8A2C-01C88DDAF54D"}
[info] [35m[WD Proxy][39m Determined the downstream protocol as 'W3C'
[debug] [35m[BaseDriver][39m Event 'wdaSessionStarted' logged at 1659325328093 (09:12:08 GMT+0530 (India Standard Time))
[debug] [35m[BaseDriver][39m Event 'wdaStarted' logged at 1659325328094 (09:12:08 GMT+0530 (India Standard Time))
[info] [35m[XCUITest][39m Skipping setting of the initial display orientation. Set the "orientation" capability to either "LANDSCAPE" or "PORTRAIT", if this is an undesired behavior.
[debug] [35m[BaseDriver][39m Event 'orientationSet' logged at 1659325328094 (09:12:08 GMT+0530 (India Standard Time))
[debug] [35m[BaseDriver][39m The value of 'elementResponseAttributes' setting did not change. Skipping the update for it
[debug] [35m[BaseDriver][39m The value of 'shouldUseCompactResponses' setting did not change. Skipping the update for it
[info] [35m[Appium][39m New XCUITestDriver session created successfully, session 266873f7-bdb3-479c-967a-e8905dc86ee7 added to master session list
[debug] [35m[BaseDriver][39m Event 'newSessionStarted' logged at 1659325328098 (09:12:08 GMT+0530 (India Standard Time))
[debug] [35m[W3C (266873f7)][39m Cached the protocol value 'W3C' for the new session 266873f7-bdb3-479c-967a-e8905dc86ee7
[debug] [35m[W3C (266873f7)][39m Responding to client with driver.createSession() result: {"capabilities":{"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"platformName":"iOS","platformVersion":"15.6","deviceName":"iPhone 11","automationName":"XCUITest","udid":"00008030-000C71060201402E","xcodeOrgId":"PLAPEP5JQ9","xcodeSigningId":"Apple Development","updatedWDABundleId":"com.ashwin1123.IntegrationApp","bundleId":"org.worldbank.wbapprovalsiphoneemsqa","useNewWDA":true,"includeSafariInWebviews":true,"newCommandTimeout":3600,"connectHardwareKeyboard":true}}
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session [39m[32m200[39m [90m84940 ms - 679[39m
[info] [35m[HTTP][39m [90m[39m[info] [35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/session/266873f7-bdb3-479c-967a-e8905dc86ee7/screenshot[39m
[info] [35m[HTTP][39m [90m{}[39m
[debug] [35m[W3C (266873f7)][39m Calling AppiumDriver.getScreenshot() with args: ["266873f7-bdb3-479c-967a-e8905dc86ee7"]
[debug] [35m[XCUITest][39m Executing command 'getScreenshot'
[debug] [35m[XCUITest][39m Taking screenshot with WDA
[debug] [35m[WD Proxy][39m Matched '/screenshot' to command name 'getScreenshot'
[debug] [35m[WD Proxy][39m Proxying [GET /screenshot] to [GET http://127.0.0.1:8100/session/46E1C0CD-4256-4203-8A2C-01C88DDAF54D/screenshot] with no body
[info] [35m[WD Proxy][39m socket hang up
[warn] [35m[XCUITest][39m Error getting screenshot: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
[debug] [35m[XCUITest][39m Taking screenshot with WDA
[debug] [35m[WD Proxy][39m Matched '/screenshot' to command name 'getScreenshot'
[debug] [35m[WD Proxy][39m Proxying [GET /screenshot] to [GET http://127.0.0.1:8100/session/46E1C0CD-4256-4203-8A2C-01C88DDAF54D/screenshot] with no body
[debug] [35m[iProxy@00008030:8100][39m Connection was refused to port 8100
[info] [35m[WD Proxy][39m socket hang up[error] [35m[WebDriverAgent][39m xcodebuild exited with code '65' and signal 'null'
[debug] [35m[XCUITest][39m Taking screenshot with WDA
[debug] [35m[WD Proxy][39m Matched '/screenshot' to command name 'getScreenshot'
[debug] [35m[WD Proxy][39m Proxying [GET /screenshot] to [GET http://127.0.0.1:8100/session/46E1C0CD-4256-4203-8A2C-01C88DDAF54D/screenshot] with no body
[debug] [35m[iProxy@00008030:8100][39m Connection was refused to port 8100
[info] [35m[WD Proxy][39m socket hang up
[debug] [35m[W3C (266873f7)][39m Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
[debug] [35m[W3C (266873f7)][39m     at JWProxy.command (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:274:13)
[debug] [35m[W3C (266873f7)][39m     at runMicrotasks (<anonymous>)
[debug] [35m[W3C (266873f7)][39m     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[debug] [35m[W3C (266873f7)][39m     at XCUITestDriver.proxyCommand (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:96:12)
[debug] [35m[W3C (266873f7)][39m     at getScreenshotFromWDA (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/screenshots.js:11:18)
[debug] [35m[W3C (266873f7)][39m     at wrapped (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:60:13)
[debug] [35m[W3C (266873f7)][39m     at retry (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:43:13)
[debug] [35m[W3C (266873f7)][39m     at retryInterval (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:70:10)
[debug] [35m[W3C (266873f7)][39m     at XCUITestDriver.getScreenshot (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/screenshots.js:42:10)
[info] [35m[HTTP][39m [37m<-- GET /wd/hub/session/266873f7-bdb3-479c-967a-e8905dc86ee7/screenshot [39m[31m500[39m [90m1130 ms - 1660[39m
[info] [35m[HTTP][39m [90m[39m[info] [35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/session/266873f7-bdb3-479c-967a-e8905dc86ee7/window/rect[39m
[info] [35m[HTTP][39m [90m{}[39m
[debug] [35m[W3C (266873f7)][39m Calling AppiumDriver.getWindowRect() with args: ["266873f7-bdb3-479c-967a-e8905dc86ee7"]
[debug] [35m[XCUITest][39m Executing command 'getWindowRect'
[debug] [35m[WD Proxy][39m Proxying [GET /window/size] to [GET http://127.0.0.1:8100/session/46E1C0CD-4256-4203-8A2C-01C88DDAF54D/window/size] with no body
[debug] [35m[iProxy@00008030:8100][39m Connection was refused to port 8100
[info] [35m[WD Proxy][39m socket hang up
[debug] [35m[W3C (266873f7)][39m Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
[debug] [35m[W3C (266873f7)][39m     at JWProxy.command (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:274:13)
[debug] [35m[W3C (266873f7)][39m     at runMicrotasks (<anonymous>)
[debug] [35m[W3C (266873f7)][39m     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[debug] [35m[W3C (266873f7)][39m     at XCUITestDriver.proxyCommand (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:96:12)
[debug] [35m[W3C (266873f7)][39m     at XCUITestDriver.getWindowSizeNative (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/general.js:78:10)
[debug] [35m[W3C (266873f7)][39m     at XCUITestDriver.getWindowSize (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/general.js:87:12)
[debug] [35m[W3C (266873f7)][39m     at XCUITestDriver.getWindowRect (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/general.js:160:27)
[info] [35m[HTTP][39m [37m<-- GET /wd/hub/session/266873f7-bdb3-479c-967a-e8905dc86ee7/window/rect [39m[31m500[39m [90m47 ms - 1424[39m
[info] [35m[HTTP][39m [90m[39m
[info] [35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/session/266873f7-bdb3-479c-967a-e8905dc86ee7/source[39m
[info] [35m[HTTP][39m [90m{}[39m
[debug] [35m[W3C (266873f7)][39m Calling AppiumDriver.getPageSource() with args: ["266873f7-bdb3-479c-967a-e8905dc86ee7"]
[debug] [35m[XCUITest][39m Executing command 'getPageSource'
[debug] [35m[WD Proxy][39m Matched '/source?scope=AppiumAUT' to command name 'getPageSource'
[debug] [35m[WD Proxy][39m Proxying [GET /source?scope=AppiumAUT] to [GET http://127.0.0.1:8100/session/46E1C0CD-4256-4203-8A2C-01C88DDAF54D/source?scope=AppiumAUT] with no body
[debug] [35m[iProxy@00008030:8100][39m Connection was refused to port 8100
[info] [35m[WD Proxy][39m socket hang up
[debug] [35m[W3C (266873f7)][39m Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
[debug] [35m[W3C (266873f7)][39m     at JWProxy.command (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:274:13)
[debug] [35m[W3C (266873f7)][39m     at runMicrotasks (<anonymous>)
[debug] [35m[W3C (266873f7)][39m     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[debug] [35m[W3C (266873f7)][39m     at XCUITestDriver.proxyCommand (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:96:12)
[debug] [35m[W3C (266873f7)][39m     at XCUITestDriver.getNativePageSource (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/source.js:26:19)
[debug] [35m[W3C (266873f7)][39m     at XCUITestDriver.getPageSource (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/source.js:22:10)
[info] [35m[HTTP][39m [37m<-- GET /wd/hub/session/266873f7-bdb3-479c-967a-e8905dc86ee7/source [39m[31m500[39m [90m32 ms - 1237[39m
[info] [35m[HTTP][39m [90m[39m[info] [35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/session/266873f7-bdb3-479c-967a-e8905dc86ee7/timeouts[39m
[info] [35m[HTTP][39m [90m{}[39m
[debug] [35m[W3C (266873f7)][39m Calling AppiumDriver.getTimeouts() with args: ["266873f7-bdb3-479c-967a-e8905dc86ee7"]
[debug] [35m[XCUITest][39m Executing command 'getTimeouts'
[debug] [35m[W3C (266873f7)][39m Responding to client with driver.getTimeouts() result: {"command":3600000,"implicit":0}
[info] [35m[HTTP][39m [37m<-- GET /wd/hub/session/266873f7-bdb3-479c-967a-e8905dc86ee7/timeouts [39m[32m200[39m [90m8 ms - 42[39m
[info] [35m[HTTP][39m [90m[39m[info] [35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/session/266873f7-bdb3-479c-967a-e8905dc86ee7/timeouts[39m
[info] [35m[HTTP][39m [90m{}[39m
[debug] [35m[W3C (266873f7)][39m Calling AppiumDriver.getTimeouts() with args: ["266873f7-bdb3-479c-967a-e8905dc86ee7"]
[debug] [35m[XCUITest][39m Executing command 'getTimeouts'
[debug] [35m[W3C (266873f7)][39m Responding to client with driver.getTimeouts() result: {"command":3600000,"implicit":0}
[info] [35m[HTTP][39m [37m<-- GET /wd/hub/session/266873f7-bdb3-479c-967a-e8905dc86ee7/timeouts [39m[36m304[39m [90m3 ms - -[39m
[info] [35m[HTTP][39m [90m[39m[info] [35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/session/266873f7-bdb3-479c-967a-e8905dc86ee7/timeouts[39m
[info] [35m[HTTP][39m [90m{}[39m
[debug] [35m[W3C (266873f7)][39m Calling AppiumDriver.getTimeouts() with args: ["266873f7-bdb3-479c-967a-e8905dc86ee7"]
[debug] [35m[XCUITest][39m Executing command 'getTimeouts'
[debug] [35m[W3C (266873f7)][39m Responding to client with driver.getTimeouts() result: {"command":3600000,"implicit":0}
[info] [35m[HTTP][39m [37m<-- GET /wd/hub/session/266873f7-bdb3-479c-967a-e8905dc86ee7/timeouts [39m[36m304[39m [90m11 ms - -[39m
[info] [35m[HTTP][39m [90m[39m[info] [35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/session/266873f7-bdb3-479c-967a-e8905dc86ee7/timeouts[39m

**Comment by mykola-mokhnach** [comment]
It looks like some old WebDriverAgent binary is cached on the device. Please follow the above advice and update server components to continue using XCUITest driver with newer iOS releases

**Comment by Robot1988** [comment]
Thank you, you mean to upgrade to Appium 2.0?

**Comment by mykola-mokhnach** [comment]
> Thank you, you mean to upgrade to Appium 2.0?

Right. Upgrade to Appium 2 as recent driver releases are only available there.

**Comment by Robot1988** [comment]
I have upgraded to Appium 2 and now getting the below error in appium inspector!

<img width="1289" alt="Screenshot 2022-08-01 at 10 06 46 PM" src="https://user-images.githubusercontent.com/94165470/182199972-013fe470-a3dd-4419-a8e5-b3e2efcc8687.png">

[debug] [HTTP] No route found for /wd/hub/session
[HTTP] <-- POST /wd/hub/session 404 6 ms - 211
[HTTP]
