### ISSUE TITLE
Password field is not loaded in modal pop-up on android devices

### ISSUE THREAD

**Issue by bhadrikishore** [appium/appium#17324]
## The problem

Actual issue is, When I am trying to run the automation scripts through Appium on SauceLabs real devices or physical devices, Password screen is not getting loaded (Given 50 seconds as wait time but not working) which is resulting script failures but password screen is getting loaded within 2 secs when I open it manually on devices. 

## Environment

* Appium version (or git revision) that exhibits the issue: V1.22.2 
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: Android 11
* Real device or emulator/simulator: Real devices
* Appium CLI or Appium.app|exe:

## Details
Password field is loaded  in Appium desktop without issues but it is not working through appium Java code.

<img width="955" alt="image" src="https://user-images.githubusercontent.com/12868414/183260459-402dd90a-ce4f-410d-8967-829631eff2ba.png">

<img width="199" alt="image" src="https://user-images.githubusercontent.com/12868414/183260784-ad44ff21-7edc-465f-ad39-bd6a235cb3fe.png">

## Code To Reproduce Issue [ Good To Have ]
MutableCapabilities capabilitiesForAppium = new MutableCapabilities();
				capabilitiesForAppium.setCapability("platformName", "Android");
				capabilitiesForAppium.setCapability("appium:deviceName", "Google_Pixel_4a_real_us");
				capabilitiesForAppium.setCapability("appium:app", "winappp.aab");
				capabilitiesForAppium.setCapability("appium:automationName", "UiAutomator2");
				//capabilitiesForAppium.setCapability("appium:allowInvisibleElements", true);
		       
		        MutableCapabilities sauceOptions = new MutableCapabilities();
		        sauceOptions.setCapability("username", "test123");
		        sauceOptions.setCapability("accesskey", "xyz");
		        sauceOptions.setCapability("name", "R4 mobile Android Test");
		        sauceOptions.setCapability("public", "public");
		        sauceOptions.setCapability("appiumVersion", "1.22.2");
		        capabilitiesForAppium.setCapability("sauce:options", sauceOptions);
		        driverURL="https://" + userName + ":" + accessKey + "@ondemand.us-west-1.saucelabs.com:443/wd/hub";
			appiumDriver = new AndroidDriver<>(new URL(driverURL), capabilitiesForAppium);
			appiumDriver.rotate(ScreenOrientation.PORTRAIT);

                click(loginPage.loginButtoninInitPage,"Login button");
		Thread.sleep(10000);
		type(loginPage.userNameTextBox, data.get("Username"), "Username textfeild");
		click(loginPage.loginButton,"Login button");
		Thread.sleep(50000);
		**type(loginPage.passwordTextBox,data.get("Password"),"Password textfeild");**

**Comment by KazuCocoa** [comment]
Could the logcat have something?

**Comment by mykola-mokhnach** [comment]
I would try to apply additional logging to the app under test to see where exactly it is stuck (which API call). It is impossible to advice anything without such details.

**Comment by bhadrikishore** [comment]
I have captured the logcat. Here is the extracted logs. 

08 Aug 09:53:49,746 INFO : ++++++++++++++++++++++++++++++++++++++++++++++++++++++++ ++++++++++++++
08 Aug 09:53:49,746 INFO : TIME TAKEN TO EXECUTE0
First and last ten lines of log: 
[2022-08-08T09:53:32+0530] [ALL] 08-07 21:23:33.334 11729 23864 W HttpCallTransport: [Service][Jni][user=e54b7281] Unauthorized. CelloHttpCall{method=GET, url=https://www.googleapis.com/drive/v2internal/about?fields=rootFolderId&reason=304&openDrive=false&syncType=2&featureLabel=android-sync-native, tags=Suppliers.memoize(<supplier that returned HttpRequestTags{celloDescription=GetAccount}>), hasRequestBody=false, acceptHttpResponseGzipEncoding=true, failOnNonHttpsUrl=false, failOnCleartextPermitted=false, contextRequestHeaders=Host : www.googleapis.com,User-Agent : Cakemix/2.22.297.00.90x (flame RQ1A.201205.008) Google.Drive/2.22.297.00.90x (OS=Android;OSVer=11;Manufacturer=Google;Model=Pixel 4;SyncEngine=Cello) Mozilla/5.0 (Linux; U; Android 11; en-gb; Pixel 4 Build/RQ1A.201205.008) AppleWebKit/525.10+ (KHTML, like Gecko) Version/3.0.4 Mobile Safari/523.12.2,Accept-Encoding : gzip, additionalHeaders=Authorization : Bearer ya29.m.CrwCATbaLaz7RR48xjfnXA09ZsfgkTig2ULMi9p0NM_pwZ3M-rFhi6Yjn5mljCvfZQt39ERulroSQjgxzjLS3Sqxx0gwbG222hc3u4FAZMqPpz2GJSd3C57dJDSiSLLN-emsg40FsivmBJ2Cw5i9bo4PRiBt7TaM4AYBP-F2woeMQtqccMpe-lZQnQOAOkhsQm6oA0vbjpeUs9FSt-3gTQw9KfSH8YwPkHxP_QDssqxmWXV5h7NAKDDJRK7WQ19b-4GvD4UgnNRNRVsW8a6pfVM4FSUEzJw91KQvq3Fdc_YzPgFYoSJPNWK_Q9LtP9Azif9I91rNWzHBBovJjuHWPcgJyj_Q8b7LQGY1R8gX6ycuE6u5sjZxAslZJ0UJLYDg-YPkQnnT0iHGUFifrEApUmH3zH6L5nL0eEdcyfn5cBIgCAESGQoUICEDBAUGJgcICQoQERMWGBobHB4Qoz8Y1yIaIA4W9h-Ayn7W_tJfGqHbj7S8QaCeaScfh3y4mtiai0lqIgIIAQ}
[2022-08-08T09:53:32+0530] [ALL] 08-07 21:23:33.335 11729 23864 W HttpCallTransport: [Service][Jni][user=e54b7281] Unauthorized. CelloHttpCall{method=GET, url=https://www.googleapis.com/drive/v2internal/about?fields=rootFolderId&reason=304&openDrive=false&syncType=2&featureLabel=android-sync-native, tags=Suppliers.memoize(<supplier that returned HttpRequestTags{celloDescription=GetAccount}>), hasRequestBody=false, acceptHttpResponseGzipEncoding=true, failOnNonHttpsUrl=false, failOnCleartextPermitted=false, contextRequestHeaders=Host : www.googleapis.com,User-Agent : Cakemix/2.22.297.00.90x (flame RQ1A.201205.008) Google.Drive/2.22.297.00.90x (OS=Android;OSVer=11;Manufacturer=Google;Model=Pixel 4;SyncEngine=Cello) Mozilla/5.0 (Linux; U; Android 11; en-gb; Pixel 4 Build/RQ1A.201205.008) AppleWebKit/525.10+ (KHTML, like Gecko) Version/3.0.4 Mobile Safari/523.12.2,Accept-Encoding : gzip, additionalHeaders=Authorization : Bearer ya29.m.CrwCATbaLaz7RR48xjfnXA09ZsfgkTig2ULMi9p0NM_pwZ3M-rFhi6Yjn5mljCvfZQt39ERulroSQjgxzjLS3Sqxx0gwbG222hc3u4FAZMqPpz2GJSd3C57dJDSiSLLN-emsg40FsivmBJ2Cw5i9bo4PRiBt7TaM4AYBP-F2woeMQtqccMpe-lZQnQOAOkhsQm6oA0vbjpeUs9FSt-3gTQw9KfSH8YwPkHxP_QDssqxmWXV5h7NAKDDJRK7WQ19b-4GvD4UgnNRNRVsW8a6pfVM4FSUEzJw91KQvq3Fdc_YzPgFYoSJPNWK_Q9LtP9Azif9I91rNWzHBBovJjuHWPcgJyj_Q8b7LQGY1R8gX6ycuE6u5sjZxAslZJ0UJLYDg-YPkQnnT0iHGUFifrEApUmH3zH6L5nL0eEdcyfn5cBIgCAESGQoUICEDBAUGJgcICQoQERMWGBobHB4Qoz8Y1yIaIA4W9h-Ayn7W_tJfGqHbj7S8QaCeaScfh3y4mtiai0lqIgIIAQ}
[2022-08-08T09:53:32+0530] [ALL] 08-07 21:23:33.336 11729 23864 W HttpCallTransport: [Service][Jni][user=e54b7281] Runtime error null processing CelloHttpCall{method=GET, url=https://www.googleapis.com/drive/v2internal/about?fields=rootFolderId&reason=304&openDrive=false&syncType=2&featureLabel=android-sync-native, tags=Suppliers.memoize(<supplier that returned HttpRequestTags{celloDescription=GetAccount}>), hasRequestBody=false, acceptHttpResponseGzipEncoding=true, failOnNonHttpsUrl=false, failOnCleartextPermitted=false, contextRequestHeaders=Host : www.googleapis.com,User-Agent : Cakemix/2.22.297.00.90x (flame RQ1A.201205.008) Google.Drive/2.22.297.00.90x (OS=Android;OSVer=11;Manufacturer=Google;Model=Pixel 4;SyncEngine=Cello) Mozilla/5.0 (Linux; U; Android 11; en-gb; Pixel 4 Build/RQ1A.201205.008) AppleWebKit/525.10+ (KHTML, like Gecko) Version/3.0.4 Mobile Safari/523.12.2,Accept-Encoding : gzip, additionalHeaders=Authorization : Bearer ya29.m.CrwCATbaLaz7RR48xjfnXA09ZsfgkTig2ULMi9p0NM_pwZ3M-rFhi6Yjn5mljCvfZQt39ERulroSQjgxzjLS3Sqxx0gwbG222hc3u4FAZMqPpz2GJSd3-emsg40FsivmBJ2Cw5i9bo4PRiBt7TaM4AYBP-F2woeMQtqccMpe-lZQnQOAOkhsQm6oA0vbjpeUs9FSt-3gTQw9KfSH8YwPkHxP_QDssqxmWXV5h7NAKDDJRK7WQ19b-4GvD4UgnNRNRVsW8a6pfVM4FSUEzJw91KQvq3Fdc_YzPgFYoSJPNWK_Q9LtP9Azif9I91rNWzHBBovJjuHWPcgJyj_Q8b7LQGY1R8gX6ycuE6u5sjZxAslZJ0UJLYDg-YPkQnnT0iHGUFifrEApUmH3zH6L5nL0eEdcyfn5cBIgCAESGQoUICEDBAUGJgcICQoQERMWGBobHB4Qoz8Y1yIaIA4W9h-Ayn7W_tJfGqHbj7S8QaCeaScfh3y4mtiai0lqIgIIAQ}
[2022-08-08T09:53:32+0530] [ALL] 08-07 21:23:33.336 11729 23864 W HttpCallTransport: android.accounts.AuthenticatorException
[2022-08-08T09:53:32+0530] [ALL] 08-07 21:23:33.336 11729 23864 W HttpCallTransport: 	at jng.c(PG:29)
[2022-08-08T09:53:32+0530] [ALL] 08-07 21:23:33.336 11729 23864 W HttpCallTransport: 	at jng.b(PG:15)
[2022-08-08T09:53:32+0530] [ALL] 08-07 21:23:33.336 11729 23864 W HttpCallTransport: 	at jng.a(PG:3)
[2022-08-08T09:53:32+0530] [ALL] 08-07 21:23:33.336 11729 23864 W HttpCallTransport: 	at ixz.run(PG:26)
[2022-08-08T09:53:32+0530] [ALL] 08-07 21:23:33.336 11729 23864 W HttpCallTransport: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[2022-08-08T09:53:32+0530] [ALL] 08-07 21:23:33.336 11729 23864 W HttpCallTransport: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
...
[2022-08-08T09:53:49+0530] [ALL] 08-07 21:23:50.513 24130 24157 I app_process: WaitForGcToComplete blocked Alloc on HeapTrim for 284.673ms
[2022-08-08T09:53:49+0530] [ALL] 08-07 21:23:50.513 24130 24157 I app_process: Starting a blocking GC Alloc
[2022-08-08T09:53:49+0530] [ALL] 08-07 21:23:50.523 24130 24157 I app_process: Waiting for a blocking GC Alloc
[2022-08-08T09:53:49+0530] [ALL] 08-07 21:23:50.584 24630 24664 I appium  : channel read: POST /wd/hub/session/a60d0399-dbb3-4463-affc-4442a13d232c/element/00000000-0000-0078-0000-008300000036/click
[2022-08-08T09:53:49+0530] [ALL] 08-07 21:23:50.585 24630 24664 I appium  : Click command
[2022-08-08T09:53:49+0530] [ALL] 08-07 21:23:50.623 24004 24158 I TOOLKIT SERVICE: Request body '{"type":"GET_SCREEN_ORIENTATION"}'
[2022-08-08T09:53:49+0530] [ALL] 08-07 21:23:50.623 24004 24158 I DEVICE MANAGER: JSON string:{"type":"GET_SCREEN_ORIENTATION"}
[2022-08-08T09:53:49+0530] [ALL] 08-07 21:23:50.623 24004 24158 I TOOLKIT SERVICE: Responding to client with: '{"orientation":"PORTRAIT"}'
[2022-08-08T09:53:49+0530] [ALL] 08-07 21:23:50.628 24630 24664 I appium  : Waiting up to 10000ms for the device to idle
[2022-08-08T09:53:49+0530] [ALL] 08-07 21:23:50.628 24630 24664 I appium  : AppiumResponse: {"sessionId":"a60d0399-dbb3-4463-affc-4442a13d232c","value":null}
08 Aug 09:54:40,096 INFO : +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
08 Aug 09:54:40,096 INFO : Class namer4mobile.lib.loginlibMethod name : LoginToTheAppWithValidCredentials
08 Aug 09:54:50,314 INFO : An element could not be located on the page using the given search parameters.
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'VDIWX-LFM206', ip: '10.35.156.181', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_201'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {adbPort: 15021, appActivity: com.usfoods.ecomr4.MainActi..., appPackage: com.usfoods.ecomr4.sit, automationName: UiAutomator2, chromedriverChromeMappingFile: /root/.testobject_devices/w..., chromedriverExecutableDir: /root/.testobject_devices/w..., chromedriverPorts: [[26210, 26220]], databaseEnabled: false, desired: {adbPort: 15021, appActivity: com.usfoods.ecomr4.MainActi..., appPackage: com.usfoods.ecomr4.sit, automationName: UiAutomator2, chromedriverChromeMappingFile: /root/.testobject_devices/w..., chromedriverExecutableDir: /root/.testobject_devices/w..., chromedriverPorts: [[26210, 26220]], deviceName: Google_Pixel_4_real_us, platformName: Android, remoteAppsCacheLimit: 0, sauce:options: {accesskey: 6dc3307f-9b4b-4682-b9c2-c2f..., appiumVersion: 1.22.2, name: R4 mobile Android Test, public: public, username: kishorekumar.bhadri}, suppressKillServer: true, systemPort: 8221, uiautomator2ServerInstallTimeout: 60000}, deviceApiLevel: 30, deviceContextId: 93034862-0498-4ed4-b0fa-ffc..., deviceManufacturer: Google, deviceModel: Pixel 4, deviceName: 10.101.64.11:16020, deviceScreenDensity: 440, deviceScreenSize: 1080x2280, deviceUDID: 10.101.64.11:16020, javascriptEnabled: true, jobUuid: 47fb3eac7e9e475e961a1cc3ce0..., locationContextEnabled: false, networkConnectionEnabled: true, pixelRatio: 2.75, platform: LINUX, platformName: Android, platformVersion: 11, remoteAppsCacheLimit: 0, sauce:options: {accesskey: 6dc3307f-9b4b-4682-b9c2-c2f..., appiumVersion: 1.22.2, name: R4 mobile Android Test, public: public, username: kishorekumar.bhadri}, statBarHeight: 83, suppressKillServer: true, systemPort: 8221, takesScreenshot: true, testobject_device: Google_Pixel_4_real_us, testobject_device_name: Google Pixel 4, testobject_device_session_id: 61170975-8897-4c40-a902-9d4..., testobject_test_report_api_url: https://api.us-west-1.sauce..., testobject_test_report_url: https://app.saucelabs.com/t..., testobject_user_id: kiran_ku, uiautomator2ServerInstallTimeout: 60000, usedCachedDevice: false, viewportRect: {height: 2153, left: 0, top: 83, width: 1080}, warnings: {}, webStorageEnabled: false}
Session ID: e021e32d-1a07-438e-a881-9d7ec55e5f61
*** Element info: {Using=xpath, value=//android.widget.EditText[@resource-id='modal-input']}
08 Aug 09:54:50,315 INFO : resultDir = results\Google_Pixel_4_real_us-Android-11
Aug 08, 2022 9:54:50 AM org.openqa.selenium.remote.Augmenter extractRemoteWebDriver
WARNING: Augmenter should be applied to the instances of @Augmentable classes or previously augmented instances only (instance class was: class io.appium.java_client.android.AndroidDriver)
08 Aug 09:54:50,961 INFO : resultDir = results\Google_Pixel_4_real_us-Android-11
java.lang.Exception: Unable_To_Type_On_Password_textfeild
	at com.r4mobile.report.CReporter_Mobile.failureReport(CReporter_Mobile.java:1328)
	at com.r4mobile.accelerators.ActionEngineMobile.type(ActionEngineMobile.java:319)
	at r4mobile.lib.loginlib.LoginToTheAppWithValidCredentials(loginlib.java:74)
	at r4mobile.scripts.TC001_verifyLogintest.verifySuccessfullLogin(TC001_verifyLogintest.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

**Comment by mykola-mokhnach** [comment]
I were observing issue with third party SDKs when the original APK gets resigned/instrumented. Make sure it does not.

Btw, do you observe a similar issue when you run tests locally?

**Comment by bhadrikishore** [comment]
Yes, I asked separate team to test on physical device. They are also facing same issue. Is it issue with third party SDK? FYI, we don't face any issues while testing manually on physical device or cloud real devices. This is happening only through automation scripts.

**Comment by mykola-mokhnach** [comment]
Please check it with the cloud provider customer support. UIA2 driver has `noSign` capability, which prevents it from resigning binaries. Although this does not guarantee that the cloud itself does not modify your binaries.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
