### ISSUE TITLE
Not able to add properties in plugin schema

### ISSUE THREAD

**Issue by saikrishna321** [appium/appium#17388]
Unable to add properties under schema in package.json 

Example: 

```
 "appium": {
    "pluginName": "device-farm",
    "mainClass": "DevicePlugin",
    "schema": {
      "$schema": "http://json-schema.org/draft-07/schema",
      "additionalProperties": false,
      "description": "Appium configuration schema for the Device Farm plugin.",
      "properties": {
        "platform": {
          "type": "string"
        },
        "include-simulators": {
          "type": "boolean"
        },
        "remote": {
          "type": "object",
          "properties": {
            "port": {
              "type": "number"
            },
            "host": {
              "type": "string"
            }
          }
        }
      },
      "title": "Appium device farm plugin",
      "type": "object"
    }
  },
```

When the server is started with config as below 

```
{
    "server": {
      "port": 31337,
      "plugin": {
        "device-farm": {
          "platform": "both",
          "include-simulators": true,
          "remote": {
            "port": 4723,
            "host": "127.0.0.1"
          }
        }
      }
    }
  }
```

Server command: `./node_modules/.bin/appium server -ka 800 --config=./server-config.json --use-plugins=device-farm -pa /wd/hub`
Error: 
```
Fatal ReferenceError: Unknown argument with key port, extType plugin and extName device-farm. This is a bug.
    at AppiumSchema.flatten (/Users/saikrishna/Documents/git/appium-device-farm/node_modules/appium/lib/schema/schema.js:474:19)
    at wrapper (/Users/saikrishna/Documents/git/appium-device-farm/node_modules/lodash/lodash.js:4991:19)
    at toParserArgs (/Users/saikrishna/Documents/git/appium-device-farm/node_modules/appium/lib/schema/cli-args.js:222:21)
    at getServerArgs (/Users/saikrishna/Documents/git/appium-device-farm/node_modules/appium/lib/cli/args.js:230:22)
    at Function._addServerToParser (/Users/saikrishna/Documents/git/appium-device-farm/node_modules/appium/lib/cli/parser.js:185:24)
    at new ArgParser (/Users/saikrishna/Documents/git/appium-device-farm/node_modules/appium/lib/cli/parser.js:72:34)
    at getParser (/Users/saikrishna/Documents/git/appium-device-farm/node_modules/appium/lib/cli/parser.js:270:10)
    at init (/Users/saikrishna/Documents/git/appium-device-farm/node_modules/appium/lib/main.js:177:18)
    at main (/Users/saikrishna/Documents/git/appium-device-farm/node_modules/appium/lib/main.js:287:5)
```

**Comment by saikrishna321** [comment]
@boneskull Am I missing something here??

**Comment by mykola-mokhnach** [comment]
I assume the error is expected. The [tutorial](https://github.com/appium/appium/blob/master/packages/appium/docs/en/ecosystem/build-drivers.md) says:  `The schema must be of type `object` (`{"type": "object"}`), containing the arguments in a `properties` keyword. Nested properties are unsupported.`

And in the definition above I can observe `port` and `host` nested into `remote`.
