### ISSUE TITLE
iOS 16 - driver.get_clipboard_text() gets stuck

### ISSUE THREAD

**Issue by shaky** [appium/appium#17392]
hi there,

I'm using:
- Python3 
- 2.0.0-beta.42 
- Xcode 14 Beta 5 

Problem: 
My tests get stuck when it tries to execute `driver.get_clipboard_text()` - that's because of this new iOS 16 behavior https://9to5mac.com/2022/06/06/ios-16-permission-copy-paste-between-apps/

Is there a workaround for this? A simple solution will be to make `driver.get_clipboard_text()` fast fail with exception if it cannot read the clipboard data so we can catch the exception and then tap on 'Allow Paste'.

for example:
`  try:
        clipboard_text = self.driver.get_clipboard_text()
    except ClipboardException:
        self.driver.find_element_by_accessibility_id('Allow Paste')
`

Not even sure what's best.
Thank You!

**Comment by mykola-mokhnach** [comment]
Which API call fails? Are there any logs/stacktraces available?

**Comment by mykola-mokhnach** [comment]
If we are talking about https://developer.apple.com/forums/thread/649996 then there is not much that could be done. The call to the downstream API gets blocked internally unless the appropriate alert is accepted. You could probably try to enable `autoAcceptAlerts` together with `acceptAlertButtonSelector` for this test as a possible workaround.

**Comment by shaky** [comment]
```
[debug] [XCUITestDriver@44ae (f44a83db)] Calling AppiumDriver.getClipboard() with args: ["plaintext","f44a83db-fba8-4df1-ab0f-ff0dddb39882"]
[debug] [XCUITestDriver@44ae (f44a83db)] Executing command 'getClipboard'
[XCUITestDriver@44ae (f44a83db)] Proxying to WDA with an unknown route: POST /wda/getPasteboard
[debug] [XCUITestDriver@44ae (f44a83db)] Proxying [POST /wda/getPasteboard] to [POST http://127.0.0.1:8100/session/82625277-6F62-4EFE-B92F-058F782F412E/wda/getPasteboard] with body: {"contentType":"plaintext"}
[XCUITestDriver@44ae (f44a83db)] undefined
[debug] [XCUITestDriver@44ae (f44a83db)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: timeout of 240000ms exceeded
[debug] [XCUITestDriver@44ae (f44a83db)]     at JWProxy.command (/Users/rcreanga/.appium/node_modules/appium/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:342:13)
[debug] [XCUITestDriver@44ae (f44a83db)]     at runMicrotasks (<anonymous>)
[debug] [XCUITestDriver@44ae (f44a83db)]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
[debug] [XCUITestDriver@44ae (f44a83db)]     at XCUITestDriver.proxyCommand (/Users/rcreanga/.appium/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:95:12)
[debug] [XCUITestDriver@44ae (f44a83db)]     at XCUITestDriver.getClipboard (/Users/rcreanga/.appium/node_modules/appium-xcuitest-driver/lib/commands/clipboard.js:27:10)
[HTTP] <-- POST /wd/hub/session/f44a83db-fba8-4df1-ab0f-ff0dddb39882/appium/device/get_clipboard 500 240023 ms - 934

```

**Comment by shaky** [comment]
```
[debug] [XCUITestDriver@44ae (f44a83db)] Calling AppiumDriver.getClipboard() with args: ["plaintext","f44a83db-fba8-4df1-ab0f-ff0dddb39882"]
[debug] [XCUITestDriver@44ae (f44a83db)] Executing command 'getClipboard'
[XCUITestDriver@44ae (f44a83db)] Proxying to WDA with an unknown route: POST /wda/getPasteboard
[debug] [XCUITestDriver@44ae (f44a83db)] Proxying [POST /wda/getPasteboard] to [POST http://127.0.0.1:8100/session/82625277-6F62-4EFE-B92F-058F782F412E/wda/getPasteboard] with body: {"contentType":"plaintext"}
[XCUITestDriver@44ae (f44a83db)] undefined
[debug] [XCUITestDriver@44ae (f44a83db)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: timeout of 240000ms exceeded
[debug] [XCUITestDriver@44ae (f44a83db)]     at JWProxy.command (/Users/tester/.appium/node_modules/appium/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:342:13)
[debug] [XCUITestDriver@44ae (f44a83db)]     at runMicrotasks (<anonymous>)
[debug] [XCUITestDriver@44ae (f44a83db)]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
[debug] [XCUITestDriver@44ae (f44a83db)]     at XCUITestDriver.proxyCommand (/Users/tester/.appium/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:95:12)
[debug] [XCUITestDriver@44ae (f44a83db)]     at XCUITestDriver.getClipboard (/Users/tester/.appium/node_modules/appium-xcuitest-driver/lib/commands/clipboard.js:27:10)
[HTTP] <-- POST /wd/hub/session/f44a83db-fba8-4df1-ab0f-ff0dddb39882/appium/device/get_clipboard 500 240023 ms - 934

```

**Comment by shaky** [comment]
I've tried using:
```
'autoAcceptAlerts': 'true',
'acceptAlertButtonSelector': 'true'
```
but no success.

**Comment by KazuCocoa** [comment]
Is this on a simulator...?

I remember https://github.com/appium/ruby_lib_core/issues/384 for a simulator. Then, probably the alert appeared around https://github.com/appium/WebDriverAgent/blob/a1824895274c60798b506f31054e4ce1e0400c71/WebDriverAgentLib/Utilities/FBPasteboard.m#L53

Real devices need WDA to be foreground as https://appium.io/docs/en/commands/device/clipboard/get-clipboard/ since ios 14 or 15 to get the clipboard

**Comment by shaky** [comment]
this is a simulator indeed @KazuCocoa

**Comment by mykola-mokhnach** [comment]
> 'acceptAlertButtonSelector': 'true'

Have you eventually read the tutorial on this setting?

**Comment by shaky** [comment]
hi, @mykola-mokhnach do you mind sharing a python example? saw some js examples on the web but nothing works.

**Comment by mykola-mokhnach** [comment]
and it failed with the same timeout error? ^

**Comment by shaky** [comment]
yeah, same thing

```
[debug] [XCUITestDriver@e407 (ff088195)] Calling AppiumDriver.updateSettings() with args: [{"acceptAlertButtonSelector":"**/XCUIElementTypeButton[`label == 'Allow Paste'`]"},"ff088195-c1c8-42f4-8533-2e1dd56e65c1"]
[debug] [XCUITestDriver@e407 (ff088195)] Executing command 'updateSettings'
[debug] [XCUITestDriver@e407 (ff088195)] Matched '/appium/settings' to command name 'updateSettings'
[debug] [XCUITestDriver@e407 (ff088195)] Proxying [POST /appium/settings] to [POST http://127.0.0.1:8100/session/E8765679-43C6-44AC-9584-3F6EA35CAFD2/appium/settings] with body: {"settings":{"acceptAlertButtonSelector":"**/XCUIElementTypeButton[`label == 'Allow Paste'`]"}}
[debug] [XCUITestDriver@e407 (ff088195)] Got response with status 200: {"value":{"boundElementsByIndex":false,"mjpegServerFramerate":10,"screenshotOrientation":"auto","reduceMotion":true,"elementResponseAttributes":"type,label","screenshotQuality":1,"mjpegScalingFactor":100,"keyboardPrediction":0,"defaultActiveApplication":"auto","mjpegServerScreenshotQuality":25,"defaultAlertAction":"accept","keyboardAutocorrection":0,"useFirstMatch":false,"shouldUseCompactResponses":true,"customSnapshotTimeout":15,"dismissAlertButtonSelector":"","activeAppDetectionPoint":"64.00,64.00","snapshotMaxDepth":50,"waitForIdleTimeout":10,"includeNonModalElements":false,"acceptAlertButtonSelector":"**/XCUIElementTypeButton[`label == 'Allow Paste'`]","animationCoolOffTimeout":2},"sessionId":"E8765679-43C6-44AC-9584-3F6EA35CAFD2"}
[debug] [XCUITestDriver@e407 (ff088195)] Responding to client with driver.updateSettings() result: null
[HTTP] <-- POST /wd/hub/session/ff088195-c1c8-42f4-8533-2e1dd56e65c1/appium/settings 200 7 ms - 14
[HTTP] 
[HTTP] --> POST /wd/hub/session/ff088195-c1c8-42f4-8533-2e1dd56e65c1/appium/device/get_clipboard
[HTTP] {"contentType":"plaintext"}
[debug] [XCUITestDriver@e407 (ff088195)] Calling AppiumDriver.getClipboard() with args: ["plaintext","ff088195-c1c8-42f4-8533-2e1dd56e65c1"]
[debug] [XCUITestDriver@e407 (ff088195)] Executing command 'getClipboard'
[XCUITestDriver@e407 (ff088195)] Proxying to WDA with an unknown route: POST /wda/getPasteboard
[debug] [XCUITestDriver@e407 (ff088195)] Proxying [POST /wda/getPasteboard] to [POST http://127.0.0.1:8100/session/E8765679-43C6-44AC-9584-3F6EA35CAFD2/wda/getPasteboard] with body: {"contentType":"plaintext"}
[XCUITestDriver@e407 (ff088195)] undefined
[debug] [XCUITestDriver@e407 (ff088195)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: timeout of 240000ms exceeded
[debug] [XCUITestDriver@e407 (ff088195)]     at JWProxy.command (/Users/tester/.appium/node_modules/appium/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:342:13)
[debug] [XCUITestDriver@e407 (ff088195)]     at runMicrotasks (<anonymous>)
[debug] [XCUITestDriver@e407 (ff088195)]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
[debug] [XCUITestDriver@e407 (ff088195)]     at XCUITestDriver.proxyCommand (/Users/tester/.appium/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:95:12)
[debug] [XCUITestDriver@e407 (ff088195)]     at XCUITestDriver.getClipboard (/Users/tester/.appium/node_modules/appium-xcuitest-driver/lib/commands/clipboard.js:27:10)
[HTTP] <-- POST /wd/hub/session/ff088195-c1c8-42f4-8533-2e1dd56e65c1/appium/device/get_clipboard 500 240022 ms - 934

```

**Comment by shaky** [comment]
> this is my attempt
> 
> ```
>     def test_appium_clipboard(self):
>         self.driver.update_settings(
>             {
>                 "acceptAlertButtonSelector": "**/XCUIElementTypeButton[`label == 'Allow Paste'`]"
>             }
>         )
> 
>         clipboard_text = self.driver.get_clipboard_text()
> ```
> 
> I also have `'autoAcceptAlerts': 'true'` in capabs

I've tried the same thing with a location dialog (Allow Once, While While Using The App, Don't Allow") and the dialog is handled correctly.

**Comment by mykola-mokhnach** [comment]
ok, let me try one possible workaround in WDA code, I'll update this issue when I have some results out of this experiment

**Comment by shaky** [comment]
many thanks @mykola-mokhnach

**Comment by mykola-mokhnach** [comment]
I assume alerts handling works if we put pasteboard content retrieval into an async queue. 
@shaky you could patch your local WDA sources to check if the fix works for you

**Comment by shaky** [comment]
hi @mykola-mokhnach,

I've replaced `FBPasteboard.m` in` /Users/tester/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgentLib/Utilities`

then disabled `usePrebuiltWDA` and `derivedDataPath`

then ran the test and I think we're good now :) the dialog gets automatically dismissed by pressing 'Allow Paste' , it also reads the data from the clipboard.

can we have this tweak in master?
forgot to mention that it's working fine without `'autoAcceptAlerts': True`

Thanks!
