### ISSUE TITLE
 the appium server reports 500 errors

### ISSUE THREAD

**Issue by guangxun123** [appium/appium#17586]
## The problem
After clicking Start Session from the appium inspector, click Refresh for the first time, wait a few minutes, and click Refresh again,
and then the appium server reports 500 errors

## Environment
Appium( No GUI) :  v1.22.3
Appium inspector:  App version : 2022.8.1
Windows 10
Nodde.js: v18.8.0

Real device 
platformName: Android
platformVersion: 10

## Link to Appium logs

[debug] [W3C (a71b76de)] Calling AppiumDriver.getScreenshot() with args: ["a71b76de-4dc6-4d0c-8591-f03ddbe7cc21"]
[debug] [W3C (a71b76de)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: 'GET /screenshot' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
[debug] [W3C (a71b76de)]     at UIA2Proxy.command (C:\project\UIAuto\APP\node-v18.8.0-win-x64\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:274:13)
[debug] [W3C (a71b76de)]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[debug] [W3C (a71b76de)]     at AndroidUiautomator2Driver.commands.getScreenshot (C:\project\UIAuto\APP\node-v18.8.0-win-x64\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\commands\screenshot.js:14:10)
[HTTP] <-- GET /wd/hub/session/a71b76de-4dc6-4d0c-8591-f03ddbe7cc21/screenshot 500 29 ms - 1078
[HTTP]
[HTTP] --> GET /wd/hub/session/a71b76de-4dc6-4d0c-8591-f03ddbe7cc21/source
[HTTP] {}
[W3C (a71b76de)] Driver proxy active, passing request on via HTTP proxy
[debug] [W3C (a71b76de)] Encountered internal error running command: Error: Could not proxy. Proxy error: 'GET /wd/hub/session/a71b76de-4dc6-4d0c-8591-f03ddbe7cc21/source' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
[debug] [W3C (a71b76de)]     at doJwpProxy (C:\project\UIAuto\APP\node-v18.8.0-win-x64\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:481:13)
[debug] [W3C (a71b76de)]     at asyncHandler (C:\project\UIAuto\APP\node-v18.8.0-win-x64\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:253:9)
[HTTP] <-- GET /wd/hub/session/a71b76de-4dc6-4d0c-8591-f03ddbe7cc21/source 500 35 ms - 1115

![8340155698](https://user-images.githubusercontent.com/49149787/194743137-ca9aa6a2-4a8d-4ea5-b87e-54e275df2b36.png)

**Comment by adriatikgashi** [comment]
Please join our community for real time help on discord: https://discord.gg/DK3x8fvj

**Comment by guangxun123** [comment]
> Please join our community for real time help on discord: https://discord.gg/DK3x8fvj

Sorry,  I can't access [](https://discord.gg/DK3x8fvj)

**Comment by guangxun123** [comment]
Let's solve it here，Thanks!
