### ISSUE TITLE
[Appium Driver Update] error is raised when updating windows-appium-driver

### ISSUE THREAD

**Issue by bwomsm1** [appium/appium#17580]
## The problem
I would like to upgrade the windows driver to the latest version, I am running the following CLI command:
`appium driver update windows`

## Environment
* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

Error I get
```
C:\WINDOWS\system32>appium driver update windows
info Appium Setting NODE_PATH to 'C:\Users\qahw\AppData\Roaming\npm\node_modules'
√ Checking if driver 'windows' is updatable
√ Checking if driver 'windows' needs an update
× Installing 'windows' using NPM install spec 'appium-windows-driver@2.1.0'
× Updating driver 'windows' from 2.0.7 to 2.1.0
i Update report:
×   - 'windows' failed to update: Error: × Encountered an error when installing package: npm command 'install --save-dev --omit=peer --save-exact --global-style --no-package-lock appium-windows-driver@2.1.0 --json' failed with code 1.

STDOUT:


STDERR:
npm ERR! code 1
npm ERR! path C:\Users\qahw\.appium\node_modules\appium-windows-driver
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node install-npm.js
npm ERR! node:internal/modules/cjs/loader:959
npm ERR!   throw err;
npm ERR!   ^
npm ERR!
npm ERR! Error: Cannot find module 'fancy-log'
npm ERR! Require stack:
npm ERR! - C:\Users\qahw\.appium\node_modules\appium-windows-driver\install-npm.js
npm ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:804:27)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1028:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:102:18)
npm ERR!     at Object.<anonymous> (C:\Users\qahw\.appium\node_modules\appium-windows-driver\install-npm.js:3:13)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1126:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1004:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:839:12)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: [
npm ERR!     'C:\\Users\\qahw\\.appium\\node_modules\\appium-windows-driver\\install-npm.js'
npm ERR!   ]
npm ERR! }
{
  "error": {
    "code": 1,
    "summary": "command failed",
    "detail": "C:\\WINDOWS\\system32\\cmd.exe /d /s /c node install-npm.js\nnode:internal/modules/cjs/loader:959\r\n  throw err;\r\n  ^\r\n\r\nError: Cannot find module 'fancy-log'\r\nRequire stack:\r\n- C:\\Users\\qahw\\.appium\\node_modules\\appium-windows-driver\\install-npm.js\r\n    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)\r\n    at Function.Module._load (node:internal/modules/cjs/loader:804:27)\r\n    at Module.require (node:internal/modules/cjs/loader:1028:19)\r\n    at require (node:internal/modules/cjs/helpers:102:18)\r\n    at Object.<anonymous> (C:\\Users\\qahw\\.appium\\node_modules\\appium-windows-driver\\install-npm.js:3:13)\r\n    at Module._compile (node:internal/modules/cjs/loader:1126:14)\r\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)\r\n    at Module.load (node:internal/modules/cjs/loader:1004:32)\r\n    at Function.Module._load (node:internal/modules/cjs/loader:839:12)\r\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {\r\n  code: 'MODULE_NOT_FOUND',\r\n  requireStack: [\r\n    'C:\\\\Users\\\\qahw\\\\.appium\\\\node_modules\\\\appium-windows-driver\\\\install-npm.js'\r\n  ]\r\n}"
  }
}

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\qahw\AppData\Local\npm-cache\_logs\2022-10-07T07_52_46_878Z-debug-0.log
```

## Code To Reproduce Issue [ Good To Have ]
Run the following command from CLI:
`appium driver update windows`

**Comment by KazuCocoa** [comment]
Yes, maybe https://github.com/appium/appium-windows-driver/pull/140 will fix this. I noticed this when i checked the published one's installation

**Comment by bwomsm1** [comment]
Thanks @KazuCocoa for the super fast response. I will wait for it to be merged.

**Comment by KazuCocoa** [comment]
Please try out 2.1.1, thank you

**Comment by bwomsm1** [comment]
Issue is solved, thanks @KazuCocoa
