### ISSUE TITLE
Mobile command 'refreshGpsCache' for UIAutomator2 is failing with a 500 error code (reading 'defaultArgs')

### ISSUE THREAD

**Issue by semeguze** [appium/appium#17641]
## The problem

Using the mobile command `mobile: refreshGpsCache` is generating a 500 error.

## Environment

* Appium version: `2.0.0-beta.46`
* Last Appium version that did not exhibit the issue: N/A
* Desktop OS/version used to run Appium: `MacOS Monterrey 12.6 (21G115)`
* Node.js version: `v16.17.1`
* Npm version: `8.15.0`
* Mobile platform/version under test: `Android 12 - S 31 - x86_64`
* Real device or emulator/simulator: `Pixel 3a XL Simulator`
* Appium CLI: `Appium service on WDIO && Appium Inspector`
* WDIO version: `7.25.2`
* UIAutomator2 version: `2.9.0`

## Details

I'm trying to refresh the GPS cache using the mobile command. (https://github.com/appium/appium-uiautomator2-driver#mobile-refreshgpscache)

However I'm gettin an error:

```javascript
[HTTP] <-- POST /session/81f92f98-bbbd-4d45-9bd1-570cea06aaa8/execute/sync 500

TypeError: Cannot read properties of undefined (reading 'defaultArgs')
```

When I try to execute the mobile command from WebdriverIO of from Appium Inspector I'm getting the same error.

If I use an empty JSON for args or specify the `timeoutMs` argument, I'm getting the same response.

## Link to Appium logs

Gist: https://gist.github.com/semeguze/46dd5c670a7397853fb7092b4230d4cf
Error in Gist: https://gist.github.com/semeguze/46dd5c670a7397853fb7092b4230d4cf#file-appium-log-L242

Same error but specifying args:
```bash
[HTTP] --> POST /session/91120a46-edab-4935-bad1-405eff7ebebd/execute/sync
[HTTP] {"script":"mobile: refreshGpsCache","args":[{"timeoutMs":60000}]}
[debug] [AndroidUiautomator2Driver@922c (91120a46)] Calling AppiumDriver.execute() with args: ["mobile: refreshGpsCache",[{"timeoutMs":60000}],"91120a46-edab-4935-bad1-405eff7ebebd"]
[AndroidUiautomator2Driver@922c (91120a46)] Executing native command 'mobile: refreshGpsCache'
[debug] [AndroidUiautomator2Driver@922c (91120a46)] Encountered internal error running command: TypeError: Cannot read properties of undefined (reading 'defaultArgs')
[debug] [AndroidUiautomator2Driver@922c (91120a46)]     at ADB.refreshGeoLocationCache (/Users/sebastian.mesa/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-adb/lib/tools/settings-client-commands.js:317:19)
[debug] [AndroidUiautomator2Driver@922c (91120a46)]     at AndroidUiautomator2Driver.mobileRefreshGpsCache (/Users/sebastian.mesa/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/network.js:164:18)
[debug] [AndroidUiautomator2Driver@922c (91120a46)]     at AndroidUiautomator2Driver.executeMobile (/Users/sebastian.mesa/.appium/node_modules/appium-uiautomator2-driver/lib/commands/general.js:193:58)
[debug] [AndroidUiautomator2Driver@922c (91120a46)]     at AndroidUiautomator2Driver.execute (/Users/sebastian.mesa/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/execute.js:10:23)
[debug] [AndroidUiautomator2Driver@922c (91120a46)]     at commandExecutor (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.js:126:9)
[debug] [AndroidUiautomator2Driver@922c (91120a46)]     at /usr/local/lib/node_modules/appium/node_modules/async-lock/lib/index.js:154:12
[debug] [AndroidUiautomator2Driver@922c (91120a46)]     at AsyncLock._promiseTry (/usr/local/lib/node_modules/appium/node_modules/async-lock/lib/index.js:287:31)
[debug] [AndroidUiautomator2Driver@922c (91120a46)]     at exec (/usr/local/lib/node_modules/appium/node_modules/async-lock/lib/index.js:153:9)
[debug] [AndroidUiautomator2Driver@922c (91120a46)]     at AsyncLock.acquire (/usr/local/lib/node_modules/appium/node_modules/async-lock/lib/index.js:170:3)
[debug] [AndroidUiautomator2Driver@922c (91120a46)]     at AndroidUiautomator2Driver.executeCommand (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.js:142:39)
[debug] [AndroidUiautomator2Driver@922c (91120a46)]     at runMicrotasks (<anonymous>)
[debug] [AndroidUiautomator2Driver@922c (91120a46)]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[debug] [AndroidUiautomator2Driver@922c (91120a46)]     at defaultBehavior (/usr/local/lib/node_modules/appium/lib/appium.js:672:14)
[debug] [AndroidUiautomator2Driver@922c (91120a46)]     at AppiumDriver.executeWrappedCommand (/usr/local/lib/node_modules/appium/lib/appium.js:762:16)
[debug] [AndroidUiautomator2Driver@922c (91120a46)]     at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/lib/appium.js:684:17)
[debug] [AndroidUiautomator2Driver@922c (91120a46)]     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:346:19)
[HTTP] <-- POST /session/91120a46-edab-4935-bad1-405eff7ebebd/execute/sync 500 63 ms - 617
```

## Code To Reproduce Issue [ Good To Have ]

Start Appium Inspector, with any capabilities (No app required):
```json
{
  "appium:avd": "Android_Emulator",
  "platformName": "Android",
  "appium:automationName": "UiAutomator2",
  "appium:noReset": true
}
```

Once it fully loads, try to send one script command to test its working fine. Navigate to commands:
<img width="805" alt="image" src="https://user-images.githubusercontent.com/30412804/197310329-97fc534a-75fb-42cb-aba3-da7272343df9.png">

Try to retrieve listSms (`mobile: listSms`):
<img width="606" alt="image" src="https://user-images.githubusercontent.com/30412804/197310390-a6712ed0-163a-4785-9449-df0e029e0552.png"> 
<img width="638" alt="image" src="https://user-images.githubusercontent.com/30412804/197310397-a23d145c-01f8-4753-8f6f-22875ff6bb45.png">

Now, try to refresh the GPS cache (`mobile: refreshGpsCache`)
<img width="567" alt="image" src="https://user-images.githubusercontent.com/30412804/197310465-67adeb87-1231-4dfb-a129-cd7db53ca295.png">
<img width="456" alt="image" src="https://user-images.githubusercontent.com/30412804/197310474-96a72bf2-267e-4031-99e9-b2f8c4da043e.png">

-------

Using `WDIO` I can see the same error message:

Capabilities:
```javascript
  capabilities: [
    {
      'platformName': 'Android',
      'appium:browserName': '',
      'appium:appiumVersion': '2.0.0-beta.46',
      'appium:deviceName': 'Android Emulator',
      'appium:deviceOrientation': 'portrait',
      'appium:platformVersion': '12.0',
      'appium:app': process.env.APP_URL,
      'appium:appPackage': process.env.APP_PCK,
      'appium:appActivity': process.env.APP_ACTIVITY,
      'appium:automationName': 'UiAutomator2',
      'appium:ignoreHiddenApiPolicyError': true,
      'appium:ignoreUnimportantViews': false,
      'appium:disableAndroidWatchers': false,
      'appium:disableWindowAnimation': false,
      'appium:skipServerInstallation': false,
      'appium:waitForIdleTimeout': 0,
      'appium:noSign': true,
      'appium:newCommandTimeout': 480,
      'appium:fullReset': true,
      'appium:reboot': false,
      'appium:avd': 'Android_Emulator',
      'appium:gpsEnabled': true,
      'appium:tags': [
        currentDateTime
      ]
    }
  ],
```

Command line:
```javascript
await browser.execute('mobile: refreshGpsCache', {timeoutMs: 20000})
```

Terminal response
```bash
unknown error: An unknown server-side error occurred while processing the command. Original error: Cannot read properties of undefined (reading 'defaultArgs')
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SelectStorePage.setCoordinates (/Users/sebastian.mesa/Redacted/code/Redacted-mobile-test-automation/src/pageobjects/Redacted/select.Redacted.page.js:108:5)
    at async World.<anonymous> (/Users/sebastian.mesa/Redacted/code/Redacted-mobile-test-automation/src/step-definitions/MOO.js:54:75)
```

I don't know if maybe I'm invoking it in a wrong way, or if is a bug itself.

Appreciate any help!! 😄 
Thanks! 🚀

**Comment by mykola-mokhnach** [comment]
The patch has been published. Thanks for fixing it @KazuCocoa

**Comment by semeguze** [comment]
Thanks!! 🚀
