### ISSUE TITLE
Not able to run parallel Automation on 2 Android devices connected to a MAC system

### ISSUE THREAD

**Issue by Jitu1888** [appium/appium#17802]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Econnrefused is coming. For more details please go through the logs

### Expected Behavior

It should run parallel

### Minimal Reproducible Example

Its always coming. But we we run on single mobile its working fine.It's

### Environment

- Operating system:
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`):
  - Node.js version (output of `node --version`):
  - `npm` version (output of `npm --version`): 
  - Last `appium` version which did _not_ exhibit the problem: 
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Platform and version under test:
- Real device or emulator/simulator:

### Link to Appium Logs

https://gist.github.com/Jitu1888/f06d21a02481546a80e13795f272f025

### Futher Information

Please go through the logs.

**Comment by Jitu1888** [comment]
Appium : 1.22.3
Node : 16.12.1

**Comment by Jitu1888** [comment]
@saikrishna321 Please help me on this

**Comment by Jitu1888** [comment]
devicelab:~ jenkins$ sudo lsof -i -n -P | grep TCP | grep node | grep 8286
node      93922        jenkins   27u  IPv4 0xab1e53cc0b8d55cb      0t0    TCP 127.0.0.1:58260->127.0.0.1:8286 (ESTABLISHED)
devicelab:~ jenkins$ sudo lsof -i -n -P | grep TCP | grep node | grep 8286
node      93922        jenkins   27u  IPv4 0xab1e53cc0b8d55cb      0t0    TCP 127.0.0.1:58260->127.0.0.1:8286 (ESTABLISHED)


ESTABLISHED is getting disappear after sometime

**Comment by KazuCocoa** [comment]
Probably the `HNB31Z9C` was disconnected in the middle? Then, such a port forward could get disconnected.
`"appium:systemPort": 8286,` for `"appium:udid": "HNB31Z9C",`

```
2022-11-19 21:48:38:875 [WD Proxy] Proxying [POST /appium/tap] to [POST http://127.0.0.1:8286/wd/hub/session/3e17974d-c9ba-49fc-9c6f-9b2ee76dab13/appium/tap] with body: {"x":1803,"y":91,"undefined":null}
2022-11-19 21:48:38:876 [WD Proxy] connect ECONNREFUSED 127.0.0.1:8286
2022-11-19 21:48:38:889 [W3C (993f8358)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: connect ECONNREFUSED 127.0.0.1:8286
2022-11-19 21:48:38:889 [W3C (993f8358)]     at UIA2Proxy.command (/Users/jenkins/.nvm/versions/node/v18.12.1/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:274:13)
2022-11-19 21:48:38:889 [W3C (993f8358)]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
2022-11-19 21:48:38:890 [W3C (993f8358)]     at AndroidUiautomator2Driver.commands.tap (/Users/jenkins/.nvm/versions/node/v18.12.1/lib/node_modules/appium/node_modules/appium-uiautomator2-driver/lib/commands/element.js:102:7)
2022-11-19 21:48:38:890 [W3C (993f8358)]     at AndroidUiautomator2Driver.doTouchAction (/Users/jenkins/.nvm/versions/node/v18.12.1/lib/node_modules/appium/node_modules/appium-android-driver/lib/commands/touch.js:39:14)
2022-11-19 21:48:38:890 [W3C (993f8358)]     at AndroidUiautomator2Driver.performGesture (/Users/jenkins/.nvm/versions/node/v18.12.1/lib/node_modules/appium/node_modules/appium-android-driver/lib/commands/touch.js:143:12)
2022-11-19 21:48:38:890 [W3C (993f8358)]     at AndroidUiautomator2Driver.performTouch (/Users/jenkins/.nvm/versions/node/v18.12.1/lib/node_modules/appium/node_modules/appium-android-driver/lib/commands/touch.js:237:7)
2022-11-19 21:48:38:890 [HTTP] <-- POST /wd/hub/session/993f8358-e96a-4115-a3fc-fb67574601f7/touch/perform 500 17 ms - 1402
2022-11-19 21:48:38:890 [HTTP] 
```

Btw, it seems like... this issue was not parallel running stuff since the attached log implied it was only one session for `HNB31Z9C`

**Comment by mykola-mokhnach** [comment]
It also makes sense to update the driver to the most recent version (available in Appium2). We do not maintain Appium 1 anymore

**Comment by Jitu1888** [comment]
@mykola-mokhnach Thanks for the reply. I am using 2 different system ports and 2 different appium sessions. But always on one device we observed connect ECONNREFUSED 127.0.0.1:8286.

**Comment by mykola-mokhnach** [comment]
The driver is stable. Only the server is in beta, although it is also stable enough to be used in production. 
Unfortunately we do not have much resources to maintain older versions.

**Comment by mykola-mokhnach** [comment]
Closed because of no response
