### ISSUE TITLE
Getting "No WDAs installed on device" when running on iPhone 14 Pro Max simulator 16.1 

### ISSUE THREAD

**Issue by miriarte33** [appium/appium#17828]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

My tests are not able to run because I am getting "No WDAs installed on device"

Device capabilities:
![image](https://user-images.githubusercontent.com/25909515/204059008-408af2ec-61ce-4df4-9474-6f0852412ec0.png)
Error messages:
![image](https://user-images.githubusercontent.com/25909515/204059045-e46d0be5-2485-498f-966d-34617e79d135.png)

Appium version: 1.22.3
node version: 16.17.1

### Expected Behavior

When I install appium using `npm install -g appium`, run it and run my e2e tests, I expect them to run on the iPhone simulator. 

### Minimal Reproducible Example

```typescript
import { remote, RemoteOptions } from "webdriverio";

// Normal timeout was 2 minutes, but this takes the WDA launch timeout into account.
// eslint-disable-next-line no-undef
jest.setTimeout(120000);

let driverConnection: WebdriverIO.Browser | null = null;

const driverConfig: RemoteOptions = {
  path: "/wd/hub",
  hostname: "localhost",
  port: 4723,
  waitforTimeout: 30000,
  capabilities: {
    "appium:udid": process.env["IPHONE_UDID"],
    "appium:deviceName": process.env["IPHONE_UDID"]
      ? "TestIPhone13"
      : "iPhone 14 Pro Max",
    "appium:showIOSLog": process.env["CI_LOGGING_ENABLED"] ? true : false,
    "appium:showXcodeLog": process.env["CI_LOGGING_ENABLED"] ? true : false,
    "appium:app": process.env["APP_PATH"],
    "appium:platformName": "iOS",
    "appium:platformVersion": 16.1, // must correct the stimuator
    "appium:connectHardwareKeyboard": true,
    "appium:wdaStartupRetryInterval": 20000,
    "appium:wdaStartupRetries": 4,
    "appium:iosInstallPause": 8000,
    "appium:wdaLaunchTimeout": 60000 * 5, // 5 minutes
  },
};

const getDriver = async () => {
  if (!driverConnection) {
    driverConnection = await remote(driverConfig);
    driverConnection.updateSettings({ snapshotMaxDepth: 100 });
  }

  return driverConnection;
};

export { getDriver };
```

### Environment

- Operating system: macOS
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): 1.22.3
  - Node.js version (output of `node --version`): 16.17.1
  - `npm` version (output of `npm --version`): 8.15.0
  - Last `appium` version which did _not_ exhibit the problem: 
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s): 
- Appium plugin(s) and their version(s):
- Platform and version under test: iPhone 14 Pro Max 16.1
- Real device or emulator/simulator: Simulator

### Link to Appium Logs

https://gist.github.com/miriarte33/0687442e4381c1fcb1fac1cebb32ebea

### Futher Information

The app is running in expo. The tests were running before I upgraded my Mac to Ventura on an iPhone 13 simulator. I don't remember the appium version I had at that point that's why I didn't include it.

**Comment by mykola-mokhnach** [comment]
It does not even make sense to try it as the driver supplied with Appium 1 does not support iOS 16+
Consider getting the most recent version of it available in Appium2 
Also make sure WDA is signed properly as described in https://github.com/appium/appium-xcuitest-driver#real-devices

**Comment by miriarte33** [comment]
> It does not even make sense to try it as the driver supplied with Appium 1 does not support iOS 16+
> 
> Consider getting the most recent version of it available in Appium2 
> 
> Also make sure WDA is signed properly as described in https://github.com/appium/appium-xcuitest-driver#real-devices

I installed appium with npm install -g appium. Uninstalled and reinstalled multiple times. Is there a different way to install to get appium 2?

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium#server is the brief Appium 2.0 installation steps.
https://github.com/appium/appium/blob/master/packages/appium/docs/en/guides/migrating-1-to-2.md is the preparing migration guide

**Comment by miriarte33** [comment]
Okay, thank you. Will let you know how that works out

**Comment by miriarte33** [comment]
I am now getting 

```
[debug] [HTTP] No route found for /wd/hub/session
[HTTP] <-- POST /wd/hub/session 404 1 ms - 211
```
And after removing `path: "/wd/hub"` from my driverConfig I got:

```
[debug] [AppiumDriver@0f23] Calling AppiumDriver.createSession() with args: [{"appium:deviceName":"iPhone 14 Pro Max","appium:showIOSLog":false,"appium:showXcodeLog":false,"appium:platformName":"iOS","appium:platformVersion":"16.1","appium:connectHardwareKeyboard":true,"appium:wdaLaunchTimeout":300000},null,{"alwaysMatch":{"appium:deviceName":"iPhone 14 Pro Max","appium:showIOSLog":false,"appium:showXcodeLog":false,"appium:platformName":"iOS","appium:platformVersion":"16.1","appium:connectHardwareKeyboard":true,"appium:wdaLaunchTimeout":300000},"firstMatch":[{}]}]
[debug] [AppiumDriver@0f23] Event 'newSessionRequested' logged at 1669436810501 (23:26:50 GMT-0500 (Eastern Standard Time))
[BaseDriver] The capabilities ["platformName"] are standard capabilities and do not require "appium:" prefix
[Appium] Could not parse W3C capabilities: 'automationName' can't be blank
[debug] [AppiumDriver@0f23] Event 'newSessionStarted' logged at 1669436810502 (23:26:50 GMT-0500 (Eastern Standard Time))
[debug] [AppiumDriver@0f23] Encountered internal error running command: InvalidArgumentError: 'automationName' can't be blank
```

Is there any documentation for how to migrate a driverConfig?

**Comment by miriarte33** [comment]
> I am now getting
> 
> ```
> [debug] [HTTP] No route found for /wd/hub/session
> [HTTP] <-- POST /wd/hub/session 404 1 ms - 211
> ```
> 
> And after removing `path: "/wd/hub"` from my driverConfig I got:
> 
> ```
> [debug] [AppiumDriver@0f23] Calling AppiumDriver.createSession() with args: [{"appium:deviceName":"iPhone 14 Pro Max","appium:showIOSLog":false,"appium:showXcodeLog":false,"appium:platformName":"iOS","appium:platformVersion":"16.1","appium:connectHardwareKeyboard":true,"appium:wdaLaunchTimeout":300000},null,{"alwaysMatch":{"appium:deviceName":"iPhone 14 Pro Max","appium:showIOSLog":false,"appium:showXcodeLog":false,"appium:platformName":"iOS","appium:platformVersion":"16.1","appium:connectHardwareKeyboard":true,"appium:wdaLaunchTimeout":300000},"firstMatch":[{}]}]
> [debug] [AppiumDriver@0f23] Event 'newSessionRequested' logged at 1669436810501 (23:26:50 GMT-0500 (Eastern Standard Time))
> [BaseDriver] The capabilities ["platformName"] are standard capabilities and do not require "appium:" prefix
> [Appium] Could not parse W3C capabilities: 'automationName' can't be blank
> [debug] [AppiumDriver@0f23] Event 'newSessionStarted' logged at 1669436810502 (23:26:50 GMT-0500 (Eastern Standard Time))
> [debug] [AppiumDriver@0f23] Encountered internal error running command: InvalidArgumentError: 'automationName' can't be blank
> ```
> 
> Is there any documentation for how to migrate a driverConfig?

After adding `automationName: xcuitest` I am getting this error 

```
[XCUITestDriver@15b9 (f90bcb00)] Got response with status 404: {"value":{"error":"invalid session id","message":"Session does not exist","traceback":"(\n\t0   CoreFoundation                      0x00007ff8004278cb __exceptionPreprocess + 242\n\t1   libobjc.A.dylib                     0x00007ff80004dba3 objc_exception_throw + 48\n\t2   CoreFoundation                      0x00007ff80042753d -[NSException init] + 0\n\t3   WebDriverAgentLib                   0x0000000115b4bcb6 -[FBRoute raiseNoSessionException] + 86\n\t4   WebDriverAgentLib                   0x0000000115b4bc03 -[FBRoute decorateRequest:] + 259\n\t5   WebDriverAgentLib                   0x0000000115b4b02a -[FBRoute_TargetAction mountRequest:intoResponse:] + 90\n\t6   WebDriverAgentLib                   0x0000000115b343f3 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 499\n\t7   WebDriverAgentLib                   0x0000000115b6dfed -[RoutingHTTPServer handleRoute:withRequest:response:] + 189\n\t8   WebDriverAgentLib                   0x0000000115b6ede1 __72-[RoutingHTTPServer routeMethod:withPath...
[debug] [W3C] Matched W3C error code 'invalid session id' to NoSuchDriverError
[debug] [XCUITestDriver@15b9 (f90bcb00)] Encountered internal error running command: NoSuchDriverError: Session does not exist
[debug] [XCUITestDriver@15b9 (f90bcb00)]     at errorFromW3CJsonCode (/Users/manrique/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/protocol/errors.js:923:25)
[debug] [XCUITestDriver@15b9 (f90bcb00)]     at ProxyRequestError.getActualError (/Users/manrique/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/protocol/errors.js:798:14)
[debug] [XCUITestDriver@15b9 (f90bcb00)]     at JWProxy.command (/Users/manrique/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:340:19)
[debug] [XCUITestDriver@15b9 (f90bcb00)]     at runMicrotasks (<anonymous>)
[debug] [XCUITestDriver@15b9 (f90bcb00)]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[debug] [XCUITestDriver@15b9 (f90bcb00)]     at XCUITestDriver.proxyCommand (/Users/manrique/.appium/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:95:12)
[debug] [XCUITestDriver@15b9 (f90bcb00)]     at XCUITestDriver.onSettingsUpdate (/Users/manrique/.appium/node_modules/appium-xcuitest-driver/lib/driver.js:189:14)
[debug] [XCUITestDriver@15b9 (f90bcb00)]     at DeviceSettings.update (/Users/manrique/.nvm/versions/node/v16.17.1/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/device-settings.js:65:7)
[debug] [XCUITestDriver@15b9 (f90bcb00)]     at XCUITestDriver.updateSettings (/Users/manrique/.nvm/versions/node/v16.17.1/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/commands/settings.js:17:14)
[HTTP] <-- POST /session/f90bcb00-991a-4757-b493-a1c305481c6e/appium/settings 404 176 ms - 1326
[HTTP]
[HTTP] --> POST /session/2ca37599-ba8e-49b7-b4bc-a47129ccfe7e/elements
[HTTP] {"using":"accessibility id","value":"login-screen-button"}
[debug] [XCUITestDriver@0454 (2ca37599)] Calling AppiumDriver.findElements() with args: ["accessibility id","login-screen-button","2ca37599-ba8e-49b7-b4bc-a47129ccfe7e"]
[debug] [XCUITestDriver@0454 (2ca37599)] Executing command 'findElements'
[debug] [XCUITestDriver@0454 (2ca37599)] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id, css selector
[debug] [XCUITestDriver@0454 (2ca37599)] Waiting up to 0 ms for condition
[debug] [XCUITestDriver@0454 (2ca37599)] Matched '/elements' to command name 'findElements'
[debug] [XCUITestDriver@0454 (2ca37599)] Proxying [POST /elements] to [POST http://127.0.0.1:8100/session/5AA457F4-152F-498B-BA36-9DE57FA5B475/elements] with body: {"using":"accessibility id","value":"login-screen-button"}
[HTTP] --> POST /session/f90bcb00-991a-4757-b493-a1c305481c6e/appium/settings
[HTTP] {"settings":{"snapshotMaxDepth":100}}
[debug] [XCUITestDriver@15b9 (f90bcb00)] Calling AppiumDriver.updateSettings() with args: [{"snapshotMaxDepth":100},"f90bcb00-991a-4757-b493-a1c305481c6e"]
[debug] [XCUITestDriver@15b9 (f90bcb00)] Executing command 'updateSettings'
[debug] [XCUITestDriver@15b9 (f90bcb00)] Matched '/appium/settings' to command name 'updateSettings'
[debug] [XCUITestDriver@15b9 (f90bcb00)] Proxying [POST /appium/settings] to [POST http://127.0.0.1:8100/session/BDF4F38D-4A70-466F-83D0-7B6A0068474E/appium/settings] with body: {"settings":{"snapshotMaxDepth":100}}
[debug] [XCUITestDriver@0454 (2ca37599)] Got response with status 200: {"value":[{"ELEMENT":"35000000-0000-0000-470E-000000000000","element-6066-11e4-a52e-4f735466cecf":"35000000-0000-0000-470E-000000000000"}],"sessionId":"5AA457F4-152F-498B-BA36-9DE57FA5B475"}
[debug] [XCUITestDriver@0454 (2ca37599)] Responding to client with driver.findElements() result: [{"element-6066-11e4-a52e-4f735466cecf":"35000000-0000-0000-470E-000000000000","ELEMENT":"35000000-0000-0000-470E-000000000000"}]
[HTTP] <-- POST /session/2ca37599-ba8e-49b7-b4bc-a47129ccfe7e/elements 200 154 ms - 139
[HTTP]
[XCUITestDriver@15b9 (f90bcb00)] Got response with status 404: {"value":{"error":"invalid session id","message":"Session does not exist","traceback":"(\n\t0   CoreFoundation                      0x00007ff8004278cb __exceptionPreprocess + 242\n\t1   libobjc.A.dylib                     0x00007ff80004dba3 objc_exception_throw + 48\n\t2   CoreFoundation                      0x00007ff80042753d -[NSException init] + 0\n\t3   WebDriverAgentLib                   0x0000000115b4bcb6 -[FBRoute raiseNoSessionException] + 86\n\t4   WebDriverAgentLib                   0x0000000115b4bc03 -[FBRoute decorateRequest:] + 259\n\t5   WebDriverAgentLib                   0x0000000115b4b02a -[FBRoute_TargetAction mountRequest:intoResponse:] + 90\n\t6   WebDriverAgentLib                   0x0000000115b343f3 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 499\n\t7   WebDriverAgentLib                   0x0000000115b6dfed -[RoutingHTTPServer handleRoute:withRequest:response:] + 189\n\t8   WebDriverAgentLib                   0x0000000115b6ede1 __72-[RoutingHTTPServer routeMethod:withPath...
[debug] [W3C] Matched W3C error code 'invalid session id' to NoSuchDriverError
[debug] [XCUITestDriver@15b9 (f90bcb00)] Encountered internal error running command: NoSuchDriverError: Session does not exist
[debug] [XCUITestDriver@15b9 (f90bcb00)]     at errorFromW3CJsonCode (/Users/manrique/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/protocol/errors.js:923:25)
[debug] [XCUITestDriver@15b9 (f90bcb00)]     at ProxyRequestError.getActualError (/Users/manrique/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/protocol/errors.js:798:14)
[debug] [XCUITestDriver@15b9 (f90bcb00)]     at JWProxy.command (/Users/manrique/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:340:19)
[debug] [XCUITestDriver@15b9 (f90bcb00)]     at runMicrotasks (<anonymous>)
[debug] [XCUITestDriver@15b9 (f90bcb00)]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[debug] [XCUITestDriver@15b9 (f90bcb00)]     at XCUITestDriver.proxyCommand (/Users/manrique/.appium/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:95:12)
[debug] [XCUITestDriver@15b9 (f90bcb00)]     at XCUITestDriver.onSettingsUpdate (/Users/manrique/.appium/node_modules/appium-xcuitest-driver/lib/driver.js:189:14)
[debug] [XCUITestDriver@15b9 (f90bcb00)]     at DeviceSettings.update (/Users/manrique/.nvm/versions/node/v16.17.1/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/device-settings.js:65:7)
[debug] [XCUITestDriver@15b9 (f90bcb00)]     at XCUITestDriver.updateSettings (/Users/manrique/.nvm/versions/node/v16.17.1/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/commands/settings.js:17:14)
[HTTP] <-- POST /session/f90bcb00-991a-4757-b493-a1c305481c6e/appium/settings 404 151 ms - 1326
[HTTP]
[HTTP] --> DELETE /session/2ca37599-ba8e-49b7-b4bc-a47129ccfe7e
[HTTP] {}
[debug] [XCUITestDriver@0454 (2ca37599)] Calling AppiumDriver.deleteSession() with args: ["2ca37599-ba8e-49b7-b4bc-a47129ccfe7e"]
[debug] [AppiumDriver@2b1e] Event 'quitSessionRequested' logged at 1669437411106 (23:36:51 GMT-0500 (Eastern Standard Time))
[AppiumDriver@2b1e] Removing session 2ca37599-ba8e-49b7-b4bc-a47129ccfe7e from our master session list
[debug] [XCUITestDriver@0454 (2ca37599)] Matched '/session/2ca37599-ba8e-49b7-b4bc-a47129ccfe7e' to command name 'deleteSession'
[debug] [XCUITestDriver@0454 (2ca37599)] Proxying [DELETE /session/2ca37599-ba8e-49b7-b4bc-a47129ccfe7e] to [DELETE http://127.0.0.1:8100/session/5AA457F4-152F-498B-BA36-9DE57FA5B475] with no body
[debug] [XCUITestDriver@0454 (2ca37599)] Got response with status 200: {"value":null,"sessionId":null}
[DevCon Factory] Releasing connections for 710D1AC1-2386-4E84-946D-F328238676A8 device on any port number
[DevCon Factory] Found cached connections to release: ["710D1AC1-2386-4E84-946D-F328238676A8:8100"]
[debug] [DevCon Factory] Cached connections count: 0
[debug] [XCUITestDriver@0454 (2ca37599)] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [IOSSimulatorLog] Stopping iOS log capture
[debug] [AppiumDriver@2b1e] Event 'quitSessionFinished' logged at 1669437411117 (23:36:51 GMT-0500 (Eastern Standard Time))
[debug] [AppiumDriver@2b1e] Received response: null
[debug] [AppiumDriver@2b1e] But deleting session, so not returning
[debug] [AppiumDriver@2b1e] Responding to client with driver.deleteSession() result: null
[HTTP] <-- DELETE /session/2ca37599-ba8e-49b7-b4bc-a47129ccfe7e 200 12 ms - 14
[HTTP]
[XCUITestDriver@8bc2 (d7650be5)] Shutting down because we waited 60 seconds for a command
[AppiumDriver@2b1e] Ending session, cause was 'New Command Timeout of 60 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'
[AppiumDriver@2b1e] Removing session 'd7650be5-8d7e-4b8a-bcc0-7ea9b00519c7' from our master session list
[DevCon Factory] Releasing connections for 710D1AC1-2386-4E84-946D-F328238676A8 device on any port number
[DevCon Factory] No cached connections have been found
[debug] [XCUITestDriver@8bc2 (d7650be5)] Not clearing log files. Use `clearSystemFiles` capability to turn on.
```

Seems like it is unable to find some sessionId. I installed the `xcuitest` driver because I am running this on iOS, but I am actually using webdriverio

**Comment by miriarte33** [comment]
Got it. Looks like automationName is case sensitive. It had to be `"appium:automationName": "XCUITest",`

**Comment by KazuCocoa** [comment]
> [debug] [AppiumDriver@0f23] Calling AppiumDriver.createSession() with args: [{"appium:deviceName":"iPhone 14 Pro Max","appium:showIOSLog":false,"appium:showXcodeLog":false,"appium:platformName":"iOS","appium:platformVersion":"16.1","appium:connectHardwareKeyboard":true,"appium:wdaLaunchTimeout":300000},null,{"alwaysMatch":{"appium:deviceName":"iPhone 14 Pro Max","appium:showIOSLog":false,"appium:showXcodeLog":false,"appium:platformName":"iOS","appium:platformVersion":"16.1","appium:connectHardwareKeyboard":true,"appium:wdaLaunchTimeout":300000},"firstMatch":[{}]}]

`automationName` can be case insensitive, but the script did not sent `appium:automationName`. `invalid session id` might be different reason.
