### ISSUE TITLE
autograntpermission capability on android does not work with certain devices

### ISSUE THREAD

**Issue by rajpatta** [appium/appium#17877]
autograntpermission capability on android does not work with certain devices eg: Oppo 

the [following command runs](https://github.com/appium/appium-adb/blob/f14a6609dd7059e951976ffa56ca8aaac78fa7b8/lib/tools/adb-commands.js#L367) to get and set the permissions, output of the same comand on oppo devices includes a suffix : `restricted=true`

```
adb -s XXXXX shell dumpsys package com.sample.login | sed -n '/requested permissions:/,/install permissions:/{//!p;}' | grep "android.permission"

android.permission.INTERNET
      android.permission.SEND_SMS: restricted=true
      android.permission.READ_SMS: restricted=true
      android.permission.GET_ACCOUNTS
      android.permission.RECEIVE_BOOT_COMPLETED
      android.permission.ACCESS_NETWORK_STATE
      android.permission.ACCESS_FINE_LOCATION
      android.permission.ACCESS_COARSE_LOCATION
      android.permission.READ_EXTERNAL_STORAGE: restricted=true
      android.permission.WRITE_EXTERNAL_STORAGE: restricted=true
      android.permission.WAKE_LOCK
      android.permission.USE_BIOMETRIC
      android.permission.USE_FINGERPRINT
      android.permission.RECORD_AUDIO
      android.permission.QUERY_ALL_PACKAGES
```
We we try to grant the permission on a permission like ` android.permission.SEND_SMS: restricted=true` it fails with an exception 
```
adb -s XXXXX shell pm grant com.sample.login android.permission.SEND_SMS: restricted=true

Exception occurred while executing:
java.lang.IllegalArgumentException: Unknown permission: android.permission.SEND_SMS:
	at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:2256)
	at com.android.server.pm.permission.PermissionManagerService.access$900(PermissionManagerService.java:133)
	at com.android.server.pm.permission.PermissionManagerService$PermissionManagerServiceInternalImpl.grantRuntimePermission(PermissionManagerService.java:3338)
	at com.android.server.pm.PackageManagerService.grantRuntimePermission(PackageManagerService.java:6617)
	at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:2030)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:238)
	at android.os.ShellCommand.exec(ShellCommand.java:104)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:23965)
	at android.os.Binder.shellCommand(Binder.java:881)
	at android.os.Binder.onTransact(Binder.java:765)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:5400)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4765)
	at com.android.server.pm.OppoPackageManagerService.onTransact(OppoPackageManagerService.java:83)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)
```
Which is flagged as an [error](https://github.com/appium/appium-adb/blob/f14a6609dd7059e951976ffa56ca8aaac78fa7b8/lib/tools/adb-commands.js#L376) and ignored silently.

**Comment by mykola-mokhnach** [comment]
I don't quite understand "does not work". What should be the expected result above?

**Comment by rajpatta** [comment]
> I don't quite understand "does not work". What should be the expected result above?

the capability should ideally auto-grant permissions requested by the app. Due to the issue mentioned above , permissions are not granted which results in unexpected permissions pop-ups post session start.

**Comment by mykola-mokhnach** [comment]
Permissions like SEND_SMS cannot be granted using `pm`. This is the reason for the "restricted" label presence there. We basically do what we can (or rather what Android shell tools allow to do)

**Comment by mykola-mokhnach** [comment]
btw, the below line is invalid:
> adb -s XXXXX shell pm grant com.sample.login android.permission.SEND_SMS: restricted=true

The correct permission name would be `android.permission.SEND_SMS`.
Do you have a server log with an actual tack trace?

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by pri-gadhiya** [comment]
@mykola-mokhnach 

> Permissions like SEND_SMS cannot be granted using pm. This is the reason for the "restricted" label presence there. We basically do what we can (or rather what Android shell tools allow to do)
We raised this because on other devices its working fine, we get this issue with Oppo device for now.
