### ISSUE TITLE
bug: Appium 2 fails to install drivers

### ISSUE THREAD

**Issue by milesj** [appium/appium#18006]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to install a driver (any driver), it fails with the following:

```
$ appium driver install xcuitest
✖ Installing 'xcuitest' using NPM install spec 'appium-xcuitest-driver'
Error: ✖ Encountered an error when installing package: npm command 'install --save-dev --omit=peer --save-exact --global-style --no-package-lock appium-xcuitest-driver --json' failed with code null.

STDOUT:


STDERR:
```

### Expected Behavior

It works, or at least provides me with some output.

### Minimal Reproducible Example

N/A

### Environment

- Operating system: macos
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): 2.0.0-beta.48
  - Node.js version (output of `node --version`): 16.16
  - `npm` version (output of `npm --version`):  8.11 / Yarn 3
  - Last `appium` version which did _not_ exhibit the problem: N/A
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Platform and version under test:
- Real device or emulator/simulator: simulator

**Comment by mykola-mokhnach** [comment]
do you get any output if the npm command above is executed from the command prompt?

**Comment by mykola-mokhnach** [comment]
> npm version (output of npm --version): N/A, using Yarn 3

btw we do not officially support yarn neither test for compatibility with it

**Comment by milesj** [comment]
@mykola-mokhnach Ok yeah, running the command directly bubbled up the problem. The project this command is being ran in is using private packages (via yarn), so npm is unable to resolve them.

Do we need to use this command? Or can we just add the `appium-xcuitest-driver` package to our deps manually?

**Comment by mykola-mokhnach** [comment]
> Do we need to use this command? Or can we just add the appium-xcuitest-driver package to our deps manually?

You still need to use the `driver install` subcommand. It is not only about installing node packages, but also modifying the server config and doing all the other necessary checks.

**Comment by milesj** [comment]
This is with npm 8.11

**Comment by jlipps** [comment]
couple things:
- what is the value of the environment variable `APPIUM_HOME`?
- running the npm command in your folder is irrelevant. when you use `appium driver` it runs all NPM commands in APPIUM_HOME (defaults to `~/.appium`)
- try `rm -rf ~/.appium` and then try again.

**Comment by milesj** [comment]
Ok, wiping `~/.appium` seemed to do the trick. Was able to install xcuitest and uiautomator2, however, chromium fails.

```
✖ Installing 'chromium' using NPM install spec 'appium-chromium-driver'
Error: ✖ Encountered an error when installing package: npm command 'install --save-dev --omit=peer --save-exact --global-style --no-package-lock appium-chromium-driver --json' failed with code 1.

STDOUT:


STDERR:
npm ERR! code 1
npm ERR! path /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/appium-chromedriver
npm ERR! command failed
npm ERR! command sh -c node install-npm.js
npm ERR! [15:32:16] Error installing Chromedriver: Cannot find module '@appium/types'
npm ERR! Require stack:
npm ERR! - /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/@appium/base-driver/build/lib/basedriver/driver.js
npm ERR! - /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/@appium/base-driver/build/lib/index.js
npm ERR! - /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/@appium/base-driver/index.js
npm ERR! - /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/appium-chromedriver/build/lib/utils.js
npm ERR! - /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/appium-chromedriver/build/lib/storage-client.js
npm ERR! - /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/appium-chromedriver/build/lib/install.js
npm ERR! - /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/appium-chromedriver/install-npm.js
npm ERR! [15:32:16] Error: Cannot find module '@appium/types'
npm ERR! Require stack:
npm ERR! - /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/@appium/base-driver/build/lib/basedriver/driver.js
npm ERR! - /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/@appium/base-driver/build/lib/index.js
npm ERR! - /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/@appium/base-driver/index.js
npm ERR! - /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/appium-chromedriver/build/lib/utils.js
npm ERR! - /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/appium-chromedriver/build/lib/storage-client.js
npm ERR! - /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/appium-chromedriver/build/lib/install.js
npm ERR! - /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/appium-chromedriver/install-npm.js
npm ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1005:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:102:18)
npm ERR!     at Object.<anonymous> (/Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/@appium/base-driver/lib/basedriver/driver.js:18:1)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1105:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1005:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:102:18)
npm ERR!     at Object.<anonymous> (/Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/@appium/base-driver/lib/index.js:8:1)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1105:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
npm ERR! [15:32:16] Downloading Chromedriver can be skipped by setting the'APPIUM_SKIP_CHROMEDRIVER_INSTALL' environment variable.
{
  "error": {
    "code": 1,
    "summary": "command failed",
    "detail": "sh -c node install-npm.js\n[15:32:16] Error installing Chromedriver: Cannot find module '@appium/types'\nRequire stack:\n- /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/@appium/base-driver/build/lib/basedriver/driver.js\n- /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/@appium/base-driver/build/lib/index.js\n- /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/@appium/base-driver/index.js\n- /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/appium-chromedriver/build/lib/utils.js\n- /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/appium-chromedriver/build/lib/storage-client.js\n- /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/appium-chromedriver/build/lib/install.js\n- /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/appium-chromedriver/install-npm.js\n[15:32:16] Error: Cannot find module '@appium/types'\nRequire stack:\n- /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/@appium/base-driver/build/lib/basedriver/driver.js\n- /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/@appium/base-driver/build/lib/index.js\n- /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/@appium/base-driver/index.js\n- /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/appium-chromedriver/build/lib/utils.js\n- /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/appium-chromedriver/build/lib/storage-client.js\n- /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/appium-chromedriver/build/lib/install.js\n- /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/appium-chromedriver/install-npm.js\n    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)\n    at Function.Module._load (node:internal/modules/cjs/loader:778:27)\n    at Module.require (node:internal/modules/cjs/loader:1005:19)\n    at require (node:internal/modules/cjs/helpers:102:18)\n    at Object.<anonymous> (/Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/@appium/base-driver/lib/basedriver/driver.js:18:1)\n    at Module._compile (node:internal/modules/cjs/loader:1105:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)\n    at Module.load (node:internal/modules/cjs/loader:981:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:822:12)\n    at Module.require (node:internal/modules/cjs/loader:1005:19)\n    at require (node:internal/modules/cjs/helpers:102:18)\n    at Object.<anonymous> (/Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/@appium/base-driver/lib/index.js:8:1)\n    at Module._compile (node:internal/modules/cjs/loader:1105:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)\n    at Module.load (node:internal/modules/cjs/loader:981:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:822:12)\n[15:32:16] Downloading Chromedriver can be skipped by setting the'APPIUM_SKIP_CHROMEDRIVER_INSTALL' environment variable."
  }
}

```

**Comment by jlipps** [comment]
This is what I ran to try and reproduce, but I couldn't:

```
npm uninstall -g appium && npm install -g appium@next
rm -rf ~/.appium
appium driver install xcuitest
appium driver install uiautomator2
appium driver install chromium
```

All of these commands were successful. Please try running them and let me know if it still fails. And if so, what is the output of `npm -v`?

**Comment by milesj** [comment]
This is on 8.11:

```
 npm uninstall -g appium && npm install -g appium@next
rm -rf ~/.appium
appium driver install xcuitest
appium driver install uiautomator2
appium driver install chromium
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

removed 453 packages, and audited 1 package in 1s

found 0 vulnerabilities
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

added 453 packages, and audited 454 packages in 12s

49 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
✔ Installing 'xcuitest' using NPM install spec 'appium-xcuitest-driver'
ℹ Driver xcuitest@4.16.6 successfully installed
- automationName: XCUITest
- platformNames: ["iOS","tvOS"]
✔ Installing 'uiautomator2' using NPM install spec 'appium-uiautomator2-driver'
ℹ Driver uiautomator2@2.12.1 successfully installed
- automationName: UiAutomator2
- platformNames: ["Android"]
✖ Installing 'chromium' using NPM install spec 'appium-chromium-driver'
Error: ✖ Encountered an error when installing package: npm command 'install --save-dev --omit=peer --save-exact --global-style --no-package-lock appium-chromium-driver --json' failed with code 1.

STDOUT:


STDERR:
npm ERR! code 1
npm ERR! path /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/appium-chromedriver
npm ERR! command failed
npm ERR! command sh -c node install-npm.js
npm ERR! [11:54:36] Error installing Chromedriver: Cannot find module '@appium/types'
npm ERR! Require stack:
npm ERR! - /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/@appium/base-driver/build/lib/basedriver/driver.js
npm ERR! - /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/@appium/base-driver/build/lib/index.js
npm ERR! - /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/@appium/base-driver/index.js
npm ERR! - /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/appium-chromedriver/build/lib/utils.js
npm ERR! - /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/appium-chromedriver/build/lib/storage-client.js
npm ERR! - /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/appium-chromedriver/build/lib/install.js
npm ERR! - /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/appium-chromedriver/install-npm.js
npm ERR! [11:54:36] Error: Cannot find module '@appium/types'
npm ERR! Require stack:
npm ERR! - /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/@appium/base-driver/build/lib/basedriver/driver.js
npm ERR! - /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/@appium/base-driver/build/lib/index.js
npm ERR! - /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/@appium/base-driver/index.js
npm ERR! - /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/appium-chromedriver/build/lib/utils.js
npm ERR! - /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/appium-chromedriver/build/lib/storage-client.js
npm ERR! - /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/appium-chromedriver/build/lib/install.js
npm ERR! - /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/appium-chromedriver/install-npm.js
npm ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1005:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:102:18)
npm ERR!     at Object.<anonymous> (/Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/@appium/base-driver/lib/basedriver/driver.js:18:1)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1105:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1005:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:102:18)
npm ERR!     at Object.<anonymous> (/Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/@appium/base-driver/lib/index.js:8:1)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1105:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
npm ERR! [11:54:36] Downloading Chromedriver can be skipped by setting the'APPIUM_SKIP_CHROMEDRIVER_INSTALL' environment variable.
{
  "error": {
    "code": 1,
    "summary": "command failed",
    "detail": "sh -c node install-npm.js\n[11:54:36] Error installing Chromedriver: Cannot find module '@appium/types'\nRequire stack:\n- /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/@appium/base-driver/build/lib/basedriver/driver.js\n- /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/@appium/base-driver/build/lib/index.js\n- /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/@appium/base-driver/index.js\n- /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/appium-chromedriver/build/lib/utils.js\n- /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/appium-chromedriver/build/lib/storage-client.js\n- /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/appium-chromedriver/build/lib/install.js\n- /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/appium-chromedriver/install-npm.js\n[11:54:36] Error: Cannot find module '@appium/types'\nRequire stack:\n- /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/@appium/base-driver/build/lib/basedriver/driver.js\n- /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/@appium/base-driver/build/lib/index.js\n- /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/@appium/base-driver/index.js\n- /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/appium-chromedriver/build/lib/utils.js\n- /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/appium-chromedriver/build/lib/storage-client.js\n- /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/appium-chromedriver/build/lib/install.js\n- /Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/appium-chromedriver/install-npm.js\n    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)\n    at Function.Module._load (node:internal/modules/cjs/loader:778:27)\n    at Module.require (node:internal/modules/cjs/loader:1005:19)\n    at require (node:internal/modules/cjs/helpers:102:18)\n    at Object.<anonymous> (/Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/@appium/base-driver/lib/basedriver/driver.js:18:1)\n    at Module._compile (node:internal/modules/cjs/loader:1105:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)\n    at Module.load (node:internal/modules/cjs/loader:981:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:822:12)\n    at Module.require (node:internal/modules/cjs/loader:1005:19)\n    at require (node:internal/modules/cjs/helpers:102:18)\n    at Object.<anonymous> (/Users/milesjohnson/.appium/node_modules/appium-chromium-driver/node_modules/@appium/base-driver/lib/index.js:8:1)\n    at Module._compile (node:internal/modules/cjs/loader:1105:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)\n    at Module.load (node:internal/modules/cjs/loader:981:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:822:12)\n[11:54:36] Downloading Chromedriver can be skipped by setting the'APPIUM_SKIP_CHROMEDRIVER_INSTALL' environment variable."
  }
}

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/milesjohnson/.npm/_logs/2023-01-05T19_54_33_028Z-debug-0.log
```

**Comment by milesj** [comment]
Here's the log file if it helps:
[log.txt](https://github.com/appium/appium/files/10355325/log.txt)

**Comment by jlipps** [comment]
@milesj i'm on npm 8.19; maybe upgrade in case that helps (doubtful). what's your node version?

@boneskull any ideas what could be going on? seems like an issue with the postinstall script for appium-chromedriver, but i can't repro with what seems like a relevantly similar setup.

**Comment by milesj** [comment]
Tried it with npm 9 and getting the same error.

At least android/ios is working and I can unblock myself for now.

**Comment by jlipps** [comment]
this is very strange. if you create a new empty directory somewhere, go into it, and simply run `npm install appium-chromium-driver`, do you get the same error?

**Comment by boneskull** [comment]
Please show the result of `appium --version` and `which appium`

**Comment by boneskull** [comment]
I think the problem is that base-driver is missing a dependency.

**Comment by boneskull** [comment]
See https://github.com/appium/appium/pull/18016

**Comment by jlipps** [comment]
interesting. maybe because i have something installed globally with `@appium/types` in it, it's working for me?

**Comment by JoaoMosmann** [comment]
This issue seems to still to be present on latest appium version.

I had to manually install the package `@appium/types` globally so to be able to install chromium driver.

**Comment by jlipps** [comment]
@JoaoMosmann how are you reproducing this?

**Comment by JoaoMosmann** [comment]
I've latest appium `2.0.0-beta.71`

I ran the script mentioned above
```
npm uninstall -g appium && npm install -g appium@next
rm -rf ~/.appium
appium driver install xcuitest
appium driver install uiautomator2
appium driver install chromium
```
And still got the same error when it tried to install the `chromium` driver.

My env:
```
Node v18.16.0
Npm 9.5.1
MacOS 13.3.1 (a)
Macbook M2
```

**Comment by akhnoos1** [comment]
Hi team, i have install appium v2.4.1 and npm v10.2.4 .  while installing driver with command **appium driver install xcuitest**. 
im getting error like 
Error : npm command 'info appium-xcuitest-driver peerDependencies dependecies --json' failed with code 243. 
STDOUT:
{
error{
code: 'EACCES',
summary : 'your cache folder contains root-owned files, due to a bug in previous version of npm which has since been addressed. . to permanently fix this problem . please run sudo chown -R 501:20' /users/user name/.npm
details: ""
}
}


Any suggest would be helpful . i also tried 

npm uninstall -g appium && npm install -g appium@next

now, getting error like,


permission denied,please find attachments.

![Uploading mac_error.png…]()

**Comment by KazuCocoa** [comment]
Did you run `chown` as the suggestion? It is maybe node environment-related that ran the `sudo` privilege before but not sudo at that time.
