### ISSUE TITLE
bug:  'automationName' can't be blank

### ISSUE THREAD

**Issue by rmarinho** [appium/appium#18017]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trying to run tests on iOS simulator with Xcode 14.2 iOS 16.2 
but I get this error , but capability is there. 

```
HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"reportDirectory":"reports","reportFormat":"xml","testName":"MainPageTests","fullReset":"false","platformName":"iOS","automationName":"XCUITest","deviceName":"iPad (10th generation)","platformVersion":"16.2","udid":"E198E6C0-0337-4990-8494-7B078BAD3070","bundleId":"com.microsoft.maui.sandbox"},"capabilities":{"firstMatch":[{"platformName":"iOS"}]}}
[debug] [AppiumDriver@25ef] Calling AppiumDriver.createSession() with args: [{"reportDirectory":"reports","reportFormat":"xml","testName":"MainPageTests","fullReset":"false","platformName":"iOS","automationName":"XCUITest","deviceName":"iPad (10th generation)","platformVersion":"16.2","udid":"E198E6C0-0337-4990-8494-7B078BAD3070","bundleId":"com.microsoft.maui.sandbox"},null,{"firstMatch":[{"platformName":"iOS"}]}]
[debug] [AppiumDriver@25ef] Event 'newSessionRequested' logged at 1672961250768 (23:27:30 GMT+0000 (Western European Standard Time))
[Appium] Could not parse W3C capabilities: 'automationName' can't be blank
[debug] [AppiumDriver@25ef] Event 'newSessionStarted' logged at 1672961250771 (23:27:30 GMT+0000 (Western European Standard Time))
[debug] [AppiumDriver@25ef] Encountered internal error running command: InvalidArgumentError: 'automationName' can't be blank
[debug] [AppiumDriver@25ef]     at processCapabilities (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/capabilities.js:329:13)
[debug] [AppiumDriver@25ef]     at parseCapsForInnerDriver (/usr/local/lib/node_modules/appium/lib/utils.js:135:40)
[debug] [AppiumDriver@25ef]     at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:241:49)
[debug] [AppiumDriver@25ef]     at commandExecutor (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.js:127:18)
[debug] [AppiumDriver@25ef]     at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.js:144:15)
[debug] [AppiumDriver@25ef]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[debug] [AppiumDriver@25ef]     at defaultBehavior (/usr/local/lib/node_modules/appium/lib/appium.js:668:16)
[debug] [AppiumDriver@25ef]     at AppiumDriver.executeWrappedCommand (/usr/local/lib/node_modules/appium/lib/appium.js:762:16)
[debug] [AppiumDriver@25ef]     at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/lib/appium.js:684:17)
[debug] [AppiumDriver@25ef]     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:346:19)
```

### Expected Behavior

Should be able to run iOS tests

### Minimal Reproducible Example

npm install -g appium@next  
appium driver install xcuitest  
appium server --base-path=/wd/hub

### Environment

- Operating system: macOS
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): 2.0.0-beta.48
  - Node.js version (output of `node --version`): v19.3.0
  - `npm` version (output of `npm --version`): 9.2.0
  - Last `appium` version which did _not_ exhibit the problem: 
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s):
  - xcuitest@4.16.6 [installed (NPM)]
  - uiautomator2@2.12.1 [installed (NPM)]
- Appium plugin(s) and their version(s): none
- Platform and version under test: iOS
- Real device or emulator/simulator: simulator

**Comment by jlipps** [comment]
Looks like you're using old (non-w3c compatible) capabilities (the `desiredCapabilities` key is no longer supported). The solution is to use a newer appium client.

**Comment by rmarinho** [comment]
@jlipps is there new cababilities in the c# client?

**Comment by rmarinho** [comment]
Thanks, I figure it out I just needed to use the beta client

**Comment by moshemc1** [comment]
Thank you the problem was resolved I use:
appiumOptions.AddAdditionalCapability("appium:automationName", "UiAutomator2");
