### ISSUE TITLE
How to run app on a simulator iPhone 14 iOS - 16.2

### ISSUE THREAD

**Issue by majdalden** [appium/appium#18056]
Why fix this error?

I am using Xcode 14.2 and a simulator iPhone 14 - iOS 16.2

`SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.

org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: An unknown server-side error occurred while processing the command. Original error: Unknown device or simulator UDID: '3897E6A7-D3A9-401E-A20F-9A467D87CF72' 
Host info: host: 'MAJD-ALDEN.local', ip: 'fe80:0:0:0:466:a366:1633:3f2%en0'
Build info: version: '4.7.1', revision: 'c6795baf1a3'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '13.1', java.version: '18.0.2.1'
Driver info: io.appium.java_client.ios.IOSDriver
Command: [null, newSession {capabilities=[{appium:app=com.apple.MobileAddressBook, appium:automationName=XCuiTest, appium:bundleId=com.apple.MobileAddressBook, appium:deviceName=iPhone 14, platformName=IOS, appium:platformVersion=16.2, appium:udid=3897E6A7-D3A9-401E-A20F-9A467D87CF72}], desiredCapabilities=Capabilities {app: com.apple.MobileAddressBook, automationName: XCuiTest, bundleId: com.apple.MobileAddressBook, deviceName: iPhone 14, platformName: IOS, platformVersion: 16.2, udid: 3897E6A7-D3A9-401E-A20F-9A4...}}]
Capabilities {}

	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:148)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at io.appium.java_client.remote.AppiumProtocolHandshake.createSession(AppiumProtocolHandshake.java:133)
	at io.appium.java_client.remote.AppiumProtocolHandshake.createSession(AppiumProtocolHandshake.java:102)
	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:194)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:262)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:551)
	at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:229)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:159)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:80)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:92)
	at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:106)
	at OpenNativeIOSApp.setUp(OpenNativeIOSApp.java:49)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:829)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
	at org.testng.SuiteRunner.run(SuiteRunner.java:330)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
	at org.testng.TestNG.runSuites(TestNG.java:1099)
	at org.testng.TestNG.run(TestNG.java:1067)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)`
	
	This is my code
	
	`public class OpenNativeIOSApp {
    @Test
    public void setUp() {
        DesiredCapabilities caps = new DesiredCapabilities();
        caps.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.IOS_XCUI_TEST);
        caps.setCapability(MobileCapabilityType.PLATFORM_NAME, "ios");
        caps.setCapability(MobileCapabilityType.PLATFORM_VERSION, "16.2");
        caps.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone 14");
        caps.setCapability(MobileCapabilityType.UDID, "3897E6A7-D3A9-401E-A20F-9A467D87CF72");
        caps.setCapability(MobileCapabilityType.APP, "com.apple.MobileAddressBook");
        caps.setCapability(IOSMobileCapabilityType.BUNDLE_ID, "com.apple.MobileAddressBook");
        try {
            IOSDriver driver = new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"), caps);
        } catch (MalformedURLException e) {
            throw new RuntimeException(e);
        }
    }
}`

**Comment by jlipps** [comment]
```
Unknown device or simulator UDID: '3897E6A7-D3A9-401E-A20F-9A467D87CF72'
```

so you've confirmed that the device with this id shows up in `xcrun simctl list`?

**Comment by majdalden** [comment]
> ```
> Unknown device or simulator UDID: '3897E6A7-D3A9-401E-A20F-9A467D87CF72'
> ```
> 
> so you've confirmed that the device with this id shows up in `xcrun simctl list`?

<img width="910" alt="Screenshot 2023-01-13 at 9 34 01 PM" src="https://user-images.githubusercontent.com/11462480/212404390-4afe4ff5-86a8-4565-9d6c-91b0f2179e7b.png">

**Comment by mykola-mokhnach** [comment]
Please provide the full server log along with your environment information as requested in the issue template

**Comment by majdalden** [comment]
> Please provide the full server log along with your environment information as requested in the issue template

[appium-server-logs.txt](https://github.com/appium/appium/files/10417081/appium-server-logs.txt)

**Comment by mykola-mokhnach** [comment]
xcuitest driver supplied with Appium 1 does not support Xcode 14/ios16
Consider upgrading to Appium 2 to be able to use most recent driver version.
Closed as duplicate
