### ISSUE TITLE
bug: Error thrown unless fake package.json is added to drop

### ISSUE THREAD

**Issue by DaveTryon** [appium/appium#18057]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

My team owns [Accessibility Insights for Android](https://github.com/microsoft/accessibility-insights-web), which is an electron app that successfully uses `appium-adb` version 9.10.2. However, when we try to upgrade to any newer version of `appium-adb`, our app throws the following error (paths have been sanitized):

```
Uncaught Error: Cannot find the root folder of the appium-adb Node.js module
    at getModuleRoot (.../node_modules/appium-adb/build/lib/helpers.js:61:1)
    at memoized (.../node_modules/lodash/lodash.js:10620:1)
    at Object../node_modules/appium-adb/build/lib/tools/apk-signing.js (.../node_modules/appium-adb/build/lib/tools/apk-signing.js:17:1)
    at __webpack_require__ (.../webpack/bootstrap:19:1)
    at Object../node_modules/appium-adb/build/lib/tools/index.js (.../node_modules/appium-adb/build/lib/tools/index.js:18:42)
    at __webpack_require__ (.../webpack/bootstrap:19:1)
    at Object../node_modules/appium-adb/build/lib/adb.js (.../node_modules/appium-adb/build/lib/adb.js:23:38)
    at __webpack_require__ (.../webpack/bootstrap:19:1)
    at Object../node_modules/appium-adb/build/index.js (.../node_modules/appium-adb/build/index.js:8:35)
    at __webpack_require__ (.../webpack/bootstrap:19:1)
    at Module../src/electron/platform/android/live-appium-adb-creator.ts (device-focus-controller.ts:38:2)
    at __webpack_require__ (.../webpack/bootstrap:19:1)
    at node module decorator:5:1
    at renderer-initializer.ts:637:26
    at renderer-initializer.ts:637:26
```

Digging through the code, this error first appears in https://github.com/appium/appium-adb/pull/610, where the path gets walked until a suitable `package.json` file is found; https://github.com/appium/appium-adb/pull/619 imported the code from the support library instead of having a separate copy.

The error disappears if we drop a "fake" `package.json` file literally anywhere in the path--even the root, although I can _guarantee_ you that there are no ADB-related files in the root.

Is this run-time dependence on `package.json` by design? If so, is there a way to suppress the execution of the code in `getModuleRoot` ?

### Expected Behavior

There should be no need to add a fake `package.json` file to satisfy a method that seems to not play a runtime role.

### Minimal Reproducible Example

You can use the branch at https://github.com/microsoft/accessibility-insights-web/tree/dependabot/npm_and_yarn/appium-adb-9.10.22

### Environment

- Operating system: Windows 11, MacOS Ventura 13.1
- Real device or emulator/simulator: Happens on both

### Futher Information

I checked all of the support channels before filing this--nothing there, so this feels like a code issue

**Comment by mykola-mokhnach** [comment]
Is a valid package.json actually present in the `node_modules/appium-adb` folder?

**Comment by mykola-mokhnach** [comment]
> Is this run-time dependence on package.json by design?

Yes, we need a way to determine the root folder where the module is installed to be able to fetch resources included with it. And the assumption is this folder is always an ancestor folder of the current file where a valid appium-adb's package.json is located

**Comment by mykola-mokhnach** [comment]
Your scenario is quite specific, although it does make sense to isolate these particular calls and only use them when the corresponding APIs are called. 

https://github.com/appium/appium-adb/pull/634 should do the trick

**Comment by mykola-mokhnach** [comment]
The patch has been merged
