### ISSUE TITLE
Appium sometimes could not start session

### ISSUE THREAD

**Issue by DimitarLazarov** [appium/appium#18079]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Sometimes Appium could not start session - error is 
Caused by: org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: An unknown server-side error occurred while processing the command. Original error: Cannot start the ' X ' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Cannot start the ' X ' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Activity name '.Y' used to start the app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity.

appActivity is set to Y and error is Activity name .Y cannot be launched. I think problem is '.' in front of activity name. Our activiti name is constant and we do not change it during tests and there is no '.' at beginning.

### Expected Behavior

Session is started with no SessionNotCreatedException.

### Minimal Reproducible Example

It is reproduced not every time.

### Environment

- Operating system:
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`):
  - Node.js version (output of `node --version`):
  - `npm` version (output of `npm --version`): 
  - Last `appium` version which did _not_ exhibit the problem: 
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by mykola-mokhnach** [comment]
Please provide a proper issue description along with the environment info and server logs

**Comment by DimitarLazarov** [comment]
Appium version 1.22.3

appPackage is "tempPackage"
appActivity is "tempActivity"

org.junit.AssumptionViolatedException: attempt == RETRIES_COUNT           RETRIES_COUNT = 30
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: An unknown server-side error occurred while processing the command. Original error: Cannot start the 'tempPackage' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Cannot start the 'tempPackage' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Activity name '.tempActivity' used to start the app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity 

Build info: version: '4.6.0', revision: '79f1c02ae20'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.12'
Driver info: io.appium.java_client.android.AndroidDriver
Command: [null, newSession {capabilities=[{appium:noReset=true, appium:systemPort=4731, appium:intentAction=, appium:udid=QV72143R24, appium:chromedriverPort=4730, appium:appActivity=tempActivity, appium:deviceName=QV72143R24-name, platformName=ANDROID, appium:automationName=UIAutomator2, appium:appPackage=tempPackage}], desiredCapabilities=Capabilities {appium:appActivity: tempActivity, appium:appPackage: tempPackage, appium:automationName: UIAutomator2, appium:chromedriverPort: 4730, appium:deviceName: QV72143R24-name, appium:intentAction: , appium:noReset: true, appium:systemPort: 4731, appium:udid: QV72143R24, platformName: ANDROID}}]
Capabilities {}
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:146)
	at jdk.internal.reflect.GeneratedMethodAccessor53.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.appium.java_client.remote.AppiumProtocolHandshake.createSession(AppiumProtocolHandshake.java:126)
	at io.appium.java_client.remote.AppiumProtocolHandshake.createSession(AppiumProtocolHandshake.java:102)
	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:155)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:189)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:541)
	at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:229)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:157)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:80)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:92)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:117)
	... 7 more


Original error: Activity name '.tempActivity' used to start the app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity

**Comment by mykola-mokhnach** [comment]
Sorry, the log above is not the server one
Also, we do not support Appium 1 anymore. Consider upgrading to Appium 2 in order to use the most recent UIA2 driver

**Comment by mykola-mokhnach** [comment]
Closed because of no response
