### ISSUE TITLE
bug: UIA2 driver fails to install io.appium.settings apk when appium:avd is specified

### ISSUE THREAD

**Issue by rerorero** [appium/appium#18233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Creating a new session with uiautomator2 driver + Android emulator fails at installing io.appium.settings apk.
This only happens when I specify `appium:avd` on ubuntu, to let Appium launch when creating a new session.
I don't see this issue on M1 mac book or when I launch the emulator beforehand even on ubuntu.

### Expected Behavior

Appium successfully installs settings app and start a new session.

### Minimal Reproducible Example

run appium server and start a new session like

```
curl -H 'Content-type: application/json' -X POST http://localhost:4723/wd/hub/session -d '{ "capabilities": { "alwaysMatch": { "platformName": "android", "appium:automationName": "UIautomator2", "appium:app": "/path/to/app", "appium:newCommandTimeout": 900, "appium:mjpegServerPort": "9102", "appium:isHeadless": true, "appium:appPackage": "com.google.samples.apps.sunflower", "appium:appActivity": "com.google.samples.apps.sunflower.GardenActivity", "appium:avd": "emulator", "appium:reboot": true }, "firstMatch": [ {} ] } }'
```

### Environment

- Operating system:
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): 2.0.0-beta.45
  - Node.js version (output of `node --version`): v18.11.0
  - `npm` version (output of `npm --version`): 
  - Last `appium` version which did _not_ exhibit the problem: 
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s): 2.8.0
- Appium plugin(s) and their version(s):
- Platform and version under test: system-images;android-31;google_apis;x86_64
- Real device or emulator/simulator: emulator

### Futher Information

This seems to be the same issue reported here https://github.com/appium/appium/issues/17279#issuecomment-1203603894

I confirmed that the same error occurs by running the adb install command immediately after starting the emulator with the emulator command, without using Appium. After trying several times, I found out that this problem only occurs for a short period of time right after the emulator starts. About 10 seconds after the emulator goes online, it can be installed without any problems in my environment, i.e. this error can happen within 10 secs after online.
Let me list all errors I faced during my attempts.

```
$ adb -P 5037 -s emulator-60000 install -g ./node_modules/io.appium.settings/apks/settings_apk-debug.apk
Performing Streamed Install
adb: failed to install /home/ubuntu/repos/mobile-android/node_modules/io.appium.settings/apks/settings_apk-debug.apk:
Exception occurred while executing 'install':
java.lang.IllegalStateException: Cannot access system provider: 'settings' before system providers are installed!
	at com.android.server.am.ContentProviderHelper.getContentProviderImpl(ContentProviderHelper.java:337)
	at com.android.server.am.ContentProviderHelper.getContentProvider(ContentProviderHelper.java:125)
	at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:6002)
	at android.app.ActivityThread.acquireProvider(ActivityThread.java:6973)
	at android.app.ContextImpl$ApplicationContentResolver.acquireProvider(ContextImpl.java:3317)
	at android.content.ContentResolver.acquireProvider(ContentResolver.java:2510)
	at android.provider.Settings$ContentProviderHolder.getProvider(Settings.java:2737)
	at android.provider.Settings$NameValueCache.getStringForUser(Settings.java:2910)
	at android.provider.Settings$Global.getStringForUser(Settings.java:15036)
	at android.provider.Settings$Global.getString(Settings.java:15024)
	at android.provider.Settings$Global.getInt(Settings.java:15229)
	at com.android.internal.content.PackageHelper$1.getForceAllowOnExternalSetting(PackageHelper.java:108)
	at com.android.internal.content.PackageHelper.resolveInstallVolume(PackageHelper.java:187)
	at com.android.internal.content.PackageHelper.resolveInstallVolume(PackageHelper.java:147)
	at com.android.internal.content.PackageHelper.resolveInstallVolume(PackageHelper.java:162)
	at com.android.server.pm.PackageInstallerService.createSessionInternal(PackageInstallerService.java:773)
	at com.android.server.pm.PackageInstallerService.createSession(PackageInstallerService.java:558)
	at com.android.server.pm.PackageManagerShellCommand.doCreateSession(PackageManagerShellCommand.java:3143)
	at com.android.server.pm.PackageManagerShellCommand.doRunInstall(PackageManagerShellCommand.java:1341)
	at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:1303)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:193)
	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
	at android.os.ShellCommand.exec(ShellCommand.java:38)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:24616)
	at android.os.Binder.shellCommand(Binder.java:950)
	at android.os.Binder.onTransact(Binder.java:834)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4818)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:8506)
	at android.os.Binder.execTransactInternal(Binder.java:1184)
	at android.os.Binder.execTransact(Binder.java:1143)
```

```
Performing Streamed Install
adb: failed to install /home/ubuntu/repos/mobile-android/node_modules/io.appium.settings/apks/settings_apk-debug.apk:
```

```
Performing Streamed Install
adb: failed to install /home/ubuntu/repos/mobile-android/node_modules/io.appium.settings/apks/settings_apk-debug.apk:
Exception occurred while executing 'install':
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.content.pm.PackageManagerInternal.freeStorage(java.lang.String, long, int)' on a null object reference
	at com.android.server.StorageManagerService.allocateBytes(StorageManagerService.java:4030)
	at android.os.storage.StorageManager.allocateBytes(StorageManager.java:2340)
	at android.os.storage.StorageManager.allocateBytes(StorageManager.java:2419)
	at com.android.server.pm.PackageInstallerSession.doWriteInternal(PackageInstallerSession.java:1556)
	at com.android.server.pm.PackageInstallerSession.write(PackageInstallerSession.java:1469)
	at android.content.pm.PackageInstaller$Session.write(PackageInstaller.java:1045)
	at com.android.server.pm.PackageManagerShellCommand.doWriteSplit(PackageManagerShellCommand.java:3338)
	at com.android.server.pm.PackageManagerShellCommand.doWriteSplits(PackageManagerShellCommand.java:3300)
	at com.android.server.pm.PackageManagerShellCommand.doRunInstall(PackageManagerShellCommand.java:1351)
	at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:1303)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:193)
	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
	at android.os.ShellCommand.exec(ShellCommand.java:38)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:24616)
	at android.os.Binder.shellCommand(Binder.java:950)
	at android.os.Binder.onTransact(Binder.java:834)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4818)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:8506)
	at android.os.Binder.execTransactInternal(Binder.java:1184)
	at android.os.Binder.execTransact(Binder.java:1143)
```

Since it happens during the unstable period immediately after the startup, this is unlikely to happen when you launch the emulator in advance and don't specify `appium:avd`.

I understand this is a third-party issue but could we have a workaround for this?
The appium-android-driver only [retries twice without any intervals](https://github.com/appium/appium-android-driver/blob/e391cbd01038e2e8e48628b10430755618cb43f6/lib/android-helpers.js#L608). In my environment, these retries run for that unstable period in most cases.
Is it possible to consider adding an option to adjust the interval or the number of retries?

**Comment by mykola-mokhnach** [comment]
Could you please provide the full server log?

**Comment by rerorero** [comment]
Thank you for taking a look, here is the log.
[appium.log](https://github.com/appium/appium/files/10803166/appium.log)

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium-android-driver/pull/785 should help

**Comment by rerorero** [comment]
wow, thank you for an amazing fast fix! 3 retries * 5 sec = 15 sec should work for this.

**Comment by mykola-mokhnach** [comment]
The patch has been published
