### ISSUE TITLE
error running command: Error: Could not find MIME for Buffer

### ISSUE THREAD

**Issue by nanatlantica** [appium/appium#18273]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[debug] [XCUITestDriver@1409 (ee666642)] Got response with status 200: {"value":"iVBORw0KGgoAAAANSUhEUgAABJIAAAnkCAYAAABWQUsDAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAEkqADAAQAAAABAAAJ5AAAAADL9lqOAAAAHGlET1QAAAACAAAAAAAABPIAAAAoAAAE8gAABPIAAYuUDPiD6AAAQABJREFUeAHsXQeAVcXVTv5Ue9SYmMRETWx0trFLR2wRRXpdFpYmTVDsNRKNvXfFhoqIlKhY6CzL9l0WAgJKF5AiUpRe9/znm93vOu/6lq7srmd03sydcubMdx/z7nx75tyfSQUIRUVFbhY33HCD/N///Z+89dZb7nrv3r2CyLBnzx6XXbp0qfzsZz9zbU888URWu/Rf//qXq0P966+/HtR98cUX8vOf/9zVHX/88UE5MmlpaUGfunXrRtTNnz/f1bHvl19+GVFP/TgHVoavUc4yzoPX7MPy8DXbMd29ezebSIMGDYJ53XzzzUIZTIOGh5gpbX4sh9iZM2fKyy+/LHfccYd06NBBWrVqJf369ZN7771XJkyYEHEP2c/Xj2VUkXXh8sLCQnnhhRfktttuc2N07txZBg0aJEOGDJGFCxe67sCIOFEe07A8lP/mN78J7j2+MytWrHDNo8lg29K+CxznYFJ/nK5du7p7iX8D0KV+/fr7FUWs2PCmm26K+L6ed955rIq4D0GhZQwBQ8AQMAQMAUPAEDAEDAFDwBAwBH5SCPysvM+Wm/trrrnGbaK5SX/66acjpkbyZNeuXQJSqKwQSVASc7jzzjsFRBhSEB233nqr3H777S5/4403yi233OKuN23aFMwL/Th/EgpImQ8almTC5bj+5z//GRAh/fv3L7VvWNbBXJOsYAqdkR8+fLiAeAPx8Ytf/CKCwMD9wb385S9/Kaeeeqpce+21wrlzjkyhC+8v8v44KH/33XclKSkpmCdk8/4zD5KnRYs...
[ImageElementPlugin] Verifying screenshot size and aspect ratio
[ImageElementPlugin] Screenshot aspect ratio '0.46208530805687204' (1170x2532) matched screen aspect ratio '0.46208530805687204' (390x844)
[ImageElementPlugin] Scaling screenshot from 1170x2532 to match screen at 390x844
[AppiumDriver@2b5f] Command 'findElement' was *not* handled by the following behaviours or plugins, even though they were registered to handle it: ["default"]. The command *was* handled by these: ["images"].
[debug] [XCUITestDriver@1409 (ee666642)] Encountered internal error running command: Error: Could not find MIME for Buffer <null>
[debug] [XCUITestDriver@1409 (ee666642)]     at Jimp.parseBitmap (/Users/atlantica/.appium/node_modules/@appium/images-plugin/node_modules/@jimp/core/src/utils/image-bitmap.js:156:15)

### Expected Behavior

Image-plugin can findElement(MobileBy.IMAGE, "../01.png") correctly

### Minimal Reproducible Example

element = driver.find_element(MobileBy.IMAGE, 'imgs/01.PNG')

### Environment

- Operating system:
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`):
  - Node.js version (output of `node --version`):
  - `npm` version (output of `npm --version`): 
  - Last `appium` version which did _not_ exhibit the problem: 
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by mykola-mokhnach** [comment]
Is the provided image a valid one or it fails for all given images?

**Comment by mykola-mokhnach** [comment]
@jlipps @boneskull I've recently seen then jimp is maintained again. Shall we remove the forced version override from corresponding packages? Might that be related to the above issue?

**Comment by mykola-mokhnach** [comment]
Also please provide the full log and the environment info

**Comment by nanatlantica** [comment]
[full img base64 code.txt](https://github.com/appium/appium/files/10867045/full.img.base64.code.txt)

**Comment by nanatlantica** [comment]
More Logs

[debug] [XCUITestDriver@063a (9ea90c18)] Calling AppiumDriver.updateSettings() with args: [{"getMatchedImageResult":true},"9ea90c18-9895-4d34-8fdf-96811b081034"]
[AppiumDriver@4b49] Plugins which can handle cmd 'updateSettings': images
[AppiumDriver@4b49] Plugin images is now handling cmd 'updateSettings'
[AppiumDriver@4b49] Executing default handling behavior for command 'updateSettings'
[debug] [XCUITestDriver@063a (9ea90c18)] Executing command 'updateSettings'
[debug] [XCUITestDriver@063a (9ea90c18)] Matched '/appium/settings' to command name 'updateSettings'
[debug] [XCUITestDriver@063a (9ea90c18)] Proxying [POST /appium/settings] to [POST http://127.0.0.1:8100/session/B83F19BD-693A-4DA3-B21A-FA8D6470DB48/appium/settings] with body: {"settings":{"getMatchedImageResult":true}}
[debug] [XCUITestDriver@063a (9ea90c18)] Got response with status 200: {"value":{"boundElementsByIndex":false,"mjpegServerFramerate":10,"screenshotOrientation":"auto","reduceMotion":false,"elementResponseAttributes":"type,label","screenshotQuality":1,"mjpegScalingFactor":100,"keyboardPrediction":0,"defaultActiveApplication":"auto","mjpegServerScreenshotQuality":25,"defaultAlertAction":"","keyboardAutocorrection":0,"useFirstMatch":false,"shouldUseCompactResponses":true,"customSnapshotTimeout":15,"dismissAlertButtonSelector":"","activeAppDetectionPoint":"64.00,64.00","snapshotMaxDepth":50,"waitForIdleTimeout":10,"includeNonModalElements":false,"acceptAlertButtonSelector":"","animationCoolOffTimeout":2},"sessionId":"B83F19BD-693A-4DA3-B21A-FA8D6470DB48"}
[debug] [XCUITestDriver@063a (9ea90c18)] Responding to client with driver.updateSettings() result: null
[HTTP] <-- POST /session/9ea90c18-9895-4d34-8fdf-96811b081034/appium/settings 200 13 ms - 14
[HTTP]
[HTTP] --> POST /session/9ea90c18-9895-4d34-8fdf-96811b081034/element
[HTTP] {"using":"-image","value":"imgs/IMG_0154.PNG"}
[debug] [XCUITestDriver@063a (9ea90c18)] Calling AppiumDriver.findElement() with args: ["-image","imgs/IMG_0154.PNG","9ea90c18-9895-4d34-8fdf-96811b081034"]
[AppiumDriver@4b49] Plugins which can handle cmd 'findElement': images
[AppiumDriver@4b49] Plugin images is now handling cmd 'findElement'
[ImageElementPlugin] Finding image element with match threshold 0.4
[debug] [XCUITestDriver@063a (9ea90c18)] Proxying [GET /window/size] to [GET http://127.0.0.1:8100/session/B83F19BD-693A-4DA3-B21A-FA8D6470DB48/window/size] with no body
[debug] [XCUITestDriver@063a (9ea90c18)] Got response with status 200: {"value":{"width":390,"height":844},"sessionId":"B83F19BD-693A-4DA3-B21A-FA8D6470DB48"}
[debug] [XCUITestDriver@063a (9ea90c18)] Waiting up to 0 ms for condition
[debug] [XCUITestDriver@063a (9ea90c18)] Taking screenshot with WDA
[debug] [XCUITestDriver@063a (9ea90c18)] Matched '/screenshot' to command name 'getScreenshot'
[debug] [XCUITestDriver@063a (9ea90c18)] Proxying [GET /screenshot] to [GET http://127.0.0.1:8100/session/B83F19BD-693A-4DA3-B21A-FA8D6470DB48/screenshot] with no body
[debug] [XCUITestDriver@063a (9ea90c18)] Got response with status 200: {"value":"iVBORw0KGgoAAAANSUhEUgAABJIAAAnkCAYAAABWQUsDAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAEkqADAAQAAAABAAAJ5AAAAADL9lqOAAAAHGlET1QAAAACAAAAAAAABPIAAAAoAAAE8gAABPIAAV8tWxGI2wAAQABJREFUeAHs3Qe8XFW5/nH9X/sVvfaCn6veawFJLycVQhGwAum9klACCKEqYEMFrigqYkMsiEiRIh0M6Tk5JR1I6Akl1AABEtKT9/8+65x3XGdyDpnBkDa/4bOy9+xZe++1v3PYZ/Zz1l7zJuOBAAIIIIAAAggggAACCCCAAAIIIIBACQJvKqEOVRBAAAEEEEAAAQQQQAABBBBAAAEEEDCCJH4IEEAAAQQQQAABBBBAAAEEEEAAAQRKEiBIKomJSggggAACCCCAAAIIIIAAAggggAACBEn8DCCAAAIIIIAAAggggAACCCCAAAIIlCRAkFQSE5UQQAABBBBAAAEEEEAAAQQQQAABBAiS+BlAAAEEEEAAAQQQQAABBBBAAAEEEChJgCCpJCYqIYAAAggggAACCCCAAAIIIIAAAggQJPEzgAACCCCAAAIIIIAAAggggAACCCBQkgBBUklMVEIAAQQQQAABBBBAAAEEEEAAAQQQIEjiZwABBBBAAAEEEEAAAQQQQAABBBBAoCQBgqSSmKiEAAIIIIAAAggggAACCCCAAAIIIECQxM8AAggggAACCCCAAAIIIIAAAggggEBJAgRJJTFRCQEEEEAAAQQQQAABBBBAAAEEEECAIImfAQQQQAABBBBAAAEEEEAAAQQQQACBkgQIkkpiohICCCCAAAIIIIAAAggggAACCCCAAEESPwMIIIAAAggggAACCCCAAAIIIIAAAiUJECSVxEQlBBBAAAEEEEAAAQQQQAABBBBAAAGCJH4GEEAAAQQQQAA...
[ImageElementPlugin] Verifying screenshot size and aspect ratio
[ImageElementPlugin] Screenshot aspect ratio '0.46208530805687204' (1170x2532) matched screen aspect ratio '0.46208530805687204' (390x844)
[ImageElementPlugin] Scaling screenshot from 1170x2532 to match screen at 390x844
[AppiumDriver@4b49] Command 'findElement' was *not* handled by the following behaviours or plugins, even though they were registered to handle it: ["default"]. The command *was* handled by these: ["images"].
[debug] [XCUITestDriver@063a (9ea90c18)] Encountered internal error running command: Error: Could not find MIME for Buffer <null>
[debug] [XCUITestDriver@063a (9ea90c18)]     at Jimp.parseBitmap (/Users/atlantica/.appium/node_modules/@appium/images-plugin/node_modules/@jimp/core/src/utils/image-bitmap.js:156:15)

**Comment by nanatlantica** [comment]
I called appium through python like this :

appium_server_url = 'http://localhost:4723'
driver = webdriver.Remote(appium_server_url, caps)
element = driver.find_element(MobileBy.IMAGE, 'imgs/IMG_0154.PNG')

Appium take a screenshot for my iPhone device,  plugin pass this screen shot as base64 code , then I got the error described in this issue (can't get MIME type)

**Comment by nanatlantica** [comment]
<img width="569" alt="截屏2023-03-02 10 51 54" src="https://user-images.githubusercontent.com/6023483/222319253-99c6b52a-abd2-46f4-9f4c-4ea05096a7b8.png">

More related Log

**Comment by mykola-mokhnach** [comment]
> driver.find_element(MobileBy.IMAGE, 'imgs/IMG_0154.PNG')

AFAIK this is not supported. You must encode the image data to base64 in your client and pass the encoded string as an argument instead of a path.

**Comment by mykola-mokhnach** [comment]
> data:image/png;base64,iVBO

this is still not a valid base64. Simply try to copy the code from the provided example

**Comment by nanatlantica** [comment]
@mykola-mokhnach ,I really appreciate your input. It's extremely informative.

**Comment by mykola-mokhnach** [comment]
Shall we close the issue?

**Comment by nanatlantica** [comment]
Sure
