### ISSUE TITLE
On clicking on a link in native app opens a new browser however when trying to verify the url by switching context to WEBVIEW_chrome gives no such context exception

### ISSUE THREAD

**Issue by kushalchitransh** [appium/appium#18331]
I am trying to automate a scenario in which I am trying to click on a link in Native app which opens a new chrome browser on android.
the scenario works perfectly in android emulator but gives noSuchContext exception in AWS device farm. It prints all the 3 contexts on console but is unable to switch to it.

Following is the exception in logs of AWS:
2023-03-10T14:00:11.570+0000 [DEBUG] [TestEventLogger] mobile-automation-framework > automation-tests > main.SwaCucumberRunner > runScenario[0]("Log in to rmac and verify earn point widget buttons on rapid rewards page.", "MyAccount_Validate_Rapid_Rewards_Page_Earn_Points_Widget_Testing_10208") FAILED
2023-03-10T14:00:11.571+0000 [DEBUG] [TestEventLogger]     org.openqa.selenium.TimeoutException: Expected condition failed: waiting for testframework.GenericMethods$$Lambda$519/1693865078@74f4a755 (tried for 500 second(s) with 500 milliseconds interval)
2023-03-10T14:00:11.571+0000 [DEBUG] [TestEventLogger]         at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:81)
2023-03-10T14:00:11.571+0000 [DEBUG] [TestEventLogger]         at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:271)
2023-03-10T14:00:11.571+0000 [DEBUG] [TestEventLogger]         at testframework.GenericMethods.waitUntil(GenericMethods.java:645)
2023-03-10T14:00:11.571+0000 [DEBUG] [TestEventLogger]         at testframework.GenericMethods.switchContext(GenericMethods.java:822)
2023-03-10T14:00:11.571+0000 [DEBUG] [TestEventLogger]         at testframework.GenericMethods.switchToNewTabAndSwitchBack(GenericMethods.java:897)
2023-03-10T14:00:11.571+0000 [DEBUG] [TestEventLogger]         at businessLogic.ResponsiveMyAccount.RapidRewardsPage.EarnPoints.EarnPointsLogic.navigateToTheFlyingSouthwestPage(EarnPointsLogic.java:145)
2023-03-10T14:00:11.571+0000 [DEBUG] [TestEventLogger]         at stepdefinition.ResponsiveMyAccount.ResponsiveMyAccountRapidRewards.EarnPointsWidget.EarnPointsWidgetSteps.iVerifyINavigatedToTheFlyingSouthwestBookAFlightPage(EarnPointsWidgetSteps.java:39)
2023-03-10T14:00:11.571+0000 [DEBUG] [TestEventLogger]         at ✽.I verify I Navigated to the "Rapid Rewards Shopping" Site(file:src/test/resources/features/RMAC/SWCOMXP-10208.feature:24)
2023-03-10T14:00:11.571+0000 [DEBUG] [TestEventLogger] 
2023-03-10T14:00:11.571+0000 [DEBUG] [TestEventLogger]         Caused by:
2023-03-10T14:00:11.571+0000 [DEBUG] [TestEventLogger]         io.appium.java_client.NoSuchContextException: An unknown server-side error occurred while processing the command. Original error: Process didn't end after 10000ms (cmd: '/opt/chromedriver/linux/65/chromedriver --url-base\=wd/hub --port\=8019 --adb-port\=5037 --verbose')
2023-03-10T14:00:11.571+0000 [DEBUG] [TestEventLogger]         Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
2023-03-10T14:00:11.571+0000 [DEBUG] [TestEventLogger]         System info: host: 'ip-172-31-13-65', ip: '172.31.13.65', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-139-generic', java.version: '1.8.0_65'
2023-03-10T14:00:11.571+0000 [DEBUG] [TestEventLogger]         Driver info: io.appium.java_client.android.AndroidDriver
2023-03-10T14:00:11.571+0000 [DEBUG] [TestEventLogger]         Capabilities {app: /tmp/scratchMxyxlW.scratch/..., appActivity: com.southwestairlines.mobil..., appPackage: com.southwestairlines.mobil..., autoAcceptAlerts: true, autoWebView: true, autoWebviewTimeout: 60, automationName: UiAutomator2, chromeOptions: {w3c: false}, chromedriverExecutable: /opt/chromedriver/linux/65/..., databaseEnabled: false, desired: {app: /tmp/scratchMxyxlW.scratch/..., appActivity: com.southwestairlines.mobil..., appPackage: com.southwestairlines.mobil..., autoAcceptAlerts: true, autoWebView: true, autoWebviewTimeout: 60, automationName: UiAutomator2, chromeOptions: {w3c: false}, chromedriverExecutable: /opt/chromedriver/linux/65/..., deviceName: Android Test, enableWebviewDetailsCollection: true, ensureWebviewsHavePages: true, fullContextList: true, newCommandTimeout: 180, platformName: android, platformVersion: 12, udid: R3CT103AZ4J, webviewConnectRetries: 12}, deviceApiLevel: 31, deviceManufacturer: samsung, deviceModel: SM-S906U1, deviceName: R3CT103AZ4J, deviceScreenDensity: 450, deviceScreenSize: 1080x2340, deviceUDID: R3CT103AZ4J, enableWebviewDetailsCollection: true, ensureWebviewsHavePages: true, fullContextList: true, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, newCommandTimeout: 180, pixelRatio: 2.8125, platform: LINUX, platformName: Android, platformVersion: 12, statBarHeight: 74, takesScreenshot: true, udid: R3CT103AZ4J, viewportRect: {height: 2057, left: 0, top: 74, width: 1080}, warnings: {}, webStorageEnabled: false, webviewConnectRetries: 12}
2023-03-10T14:00:11.571+0000 [DEBUG] [TestEventLogger]         Session ID: 44de9967-93d0-4035-8231-d460907d1e35
2023-03-10T14:00:11.571+0000 [DEBUG] [TestEventLogger]             at io.appium.java_client.AppiumDriver.context(AppiumDriver.java:201)
2023-03-10T14:00:11.571+0000 [DEBUG] [TestEventLogger]             at testframework.GenericMethods.lambda$switchContext$12(GenericMethods.java:835)
2023-03-10T14:00:11.571+0000 [DEBUG] [TestEventLogger]             at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:248)
2023-03-10T14:00:11.571+0000 [DEBUG] [TestEventLogger]             at testframework.GenericMethods.waitUntil(GenericMethods.java:645)
2023-03-10T14:00:11.571+0000 [DEBUG] [TestEventLogger]             at testframework.GenericMethods.switchContext(GenericMethods.java:822)
2023-03-10T14:00:11.573+0000 [DEBUG] [TestEventLogger]             at testframework.GenericMethods.switchToNewTabAndSwitchBack(GenericMethods.java:897)
2023-03-10T14:00:11.573+0000 [DEBUG] [TestEventLogger]             at businessLogic.ResponsiveMyAccount.RapidRewardsPage.EarnPoints.EarnPointsLogic.navigateToTheFlyingSouthwestPage(EarnPointsLogic.java:145)
2023-03-10T14:00:11.573+0000 [DEBUG] [TestEventLogger]             at stepdefinition.ResponsiveMyAccount.ResponsiveMyAccountRapidRewards.EarnPointsWidget.EarnPointsWidgetSteps.iVerifyINavigatedToTheFlyingSouthwestBookAFlightPage(EarnPointsWidgetSteps.java:39)
2023-03-10T14:00:11.573+0000 [DEBUG] [TestEventLogger]             at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-03-10T14:00:11.573+0000 [DEBUG] [TestEventLogger]             at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2023-03-10T14:00:11.573+0000 [DEBUG] [TestEventLogger]             at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-03-10T14:00:11.573+0000 [DEBUG] [TestEventLogger]             at java.lang.reflect.Method.invoke(Method.java:497)
2023-03-10T14:00:11.573+0000 [DEBUG] [TestEventLogger]             at cucumber.runtime.Utils$1.call(Utils.java:26)
2023-03-10T14:00:11.573+0000 [DEBUG] [TestEventLogger]             at cucumber.runtime.Timeout.timeout(Timeout.java:16)
2023-03-10T14:00:11.573+0000 [DEBUG] [TestEventLogger]             at cucumber.runtime.Utils.invoke(Utils.java:20)
2023-03-10T14:00:11.573+0000 [DEBUG] [TestEventLogger]             at cucumber.runtime.java.JavaStepDefinition.execute(JavaStepDefinition.java:57)
2023-03-10T14:00:11.573+0000 [DEBUG] [TestEventLogger]             at cucumber.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:50)
2023-03-10T14:00:11.573+0000 [DEBUG] [TestEventLogger]             at cucumber.runner.TestStep.executeStep(TestStep.java:65)
2023-03-10T14:00:11.573+0000 [DEBUG] [TestEventLogger]             at cucumber.runner.TestStep.run(TestStep.java:50)
2023-03-10T14:00:11.573+0000 [DEBUG] [TestEventLogger]             at cucumber.runner.PickleStepTestStep.run(PickleStepTestStep.java:43)
2023-03-10T14:00:11.573+0000 [DEBUG] [TestEventLogger]             at cucumber.runner.TestCase.run(TestCase.java:46)
2023-03-10T14:00:11.573+0000 [DEBUG] [TestEventLogger]             at cucumber.runner.Runner.runPickle(Runner.java:50)
2023-03-10T14:00:11.573+0000 [DEBUG] [TestEventLogger]             at io.cucumber.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:79)
2023-03-10T14:00:11.573+0000 [DEBUG] [TestEventLogger]             at main.SwaCucumberRunner.runScenario(SwaCucumberRunner.java:68)
2023-03-10T14:00:11.573+0000 [DEBUG] [TestEventLogger]             at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-03-10T14:00:11.574+0000 [DEBUG] [TestEventLogger]             at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2023-03-10T14:00:11.574+0000 [DEBUG] [TestEventLogger]             at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-03-10T14:00:11.574+0000 [DEBUG] [TestEventLogger]             at java.lang.reflect.Method.invoke(Method.java:497)
2023-03-10T14:00:11.574+0000 [DEBUG] [TestEventLogger]             at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
2023-03-10T14:00:11.574+0000 [DEBUG] [TestEventLogger]             at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
2023-03-10T14:00:11.574+0000 [DEBUG] [TestEventLogger]             at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
2023-03-10T14:00:11.574+0000 [DEBUG] [TestEventLogger]             at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
2023-03-10T14:00:11.574+0000 [DEBUG] [TestEventLogger]             at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
2023-03-10T14:00:11.574+0000 [DEBUG] [TestEventLogger]             at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
2023-03-10T14:00:11.574+0000 [DEBUG] [TestEventLogger]             at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
2023-03-10T14:00:11.574+0000 [DEBUG] [TestEventLogger]             at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
2023-03-10T14:00:11.574+0000 [DEBUG] [TestEventLogger]             at java.util.ArrayList.forEach(ArrayList.java:1249)
2023-03-10T14:00:11.574+0000 [DEBUG] [TestEventLogger]             at org.testng.TestRunner.privateRun(TestRunner.java:808)
2023-03-10T14:00:11.574+0000 [DEBUG] [TestEventLogger]             at org.testng.TestRunner.run(TestRunner.java:603)
2023-03-10T14:00:11.574+0000 [DEBUG] [TestEventLogger]             at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
2023-03-10T14:00:11.574+0000 [DEBUG] [TestEventLogger]             at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
2023-03-10T14:00:11.574+0000 [DEBUG] [TestEventLogger]             at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
2023-03-10T14:00:11.574+0000 [DEBUG] [TestEventLogger]             at org.testng.SuiteRunner.run(SuiteRunner.java:326)
2023-03-10T14:00:11.574+0000 [DEBUG] [TestEventLogger]             at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
2023-03-10T14:00:11.574+0000 [DEBUG] [TestEventLogger]             at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
2023-03-10T14:00:11.574+0000 [DEBUG] [TestEventLogger]             at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
2023-03-10T14:00:11.574+0000 [DEBUG] [TestEventLogger]             at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
2023-03-10T14:00:11.574+0000 [DEBUG] [TestEventLogger]             at org.testng.TestNG.runSuites(TestNG.java:1092)
2023-03-10T14:00:11.574+0000 [DEBUG] [TestEventLogger]             at org.testng.TestNG.run(TestNG.java:1060)
2023-03-10T14:00:11.574+0000 [DEBUG] [TestEventLogger]             at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.runTests(TestNGTestClassProcessor.java:141)
2023-03-10T14:00:11.574+0000 [DEBUG] [TestEventLogger]             at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.stop(TestNGTestClassProcessor.java:90)
2023-03-10T14:00:11.574+0000 [DEBUG] [TestEventLogger]             at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
2023-03-10T14:00:11.574+0000 [DEBUG] [TestEventLogger]             at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-03-10T14:00:11.574+0000 [DEBUG] [TestEventLogger]             at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2023-03-10T14:00:11.574+0000 [DEBUG] [TestEventLogger]             at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-03-10T14:00:11.574+0000 [DEBUG] [TestEventLogger]             at java.lang.reflect.Method.invoke(Method.java:497)
2023-03-10T14:00:11.574+0000 [DEBUG] [TestEventLogger]             at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
2023-03-10T14:00:11.575+0000 [DEBUG] [TestEventLogger]             at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
2023-03-10T14:00:11.575+0000 [DEBUG] [TestEventLogger]             at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
2023-03-10T14:00:11.575+0000 [DEBUG] [TestEventLogger]             at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
2023-03-10T14:00:11.575+0000 [DEBUG] [TestEventLogger]             at com.sun.proxy.$Proxy2.stop(Unknown Source)
2023-03-10T14:00:11.575+0000 [DEBUG] [TestEventLogger]             at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:133)
2023-03-10T14:00:11.575+0000 [DEBUG] [TestEventLogger]             at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-03-10T14:00:11.575+0000 [DEBUG] [TestEventLogger]             at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2023-03-10T14:00:11.575+0000 [DEBUG] [TestEventLogger]             at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-03-10T14:00:11.575+0000 [DEBUG] [TestEventLogger]             at java.lang.reflect.Method.invoke(Method.java:497)
2023-03-10T14:00:11.575+0000 [DEBUG] [TestEventLogger]             at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
2023-03-10T14:00:11.575+0000 [DEBUG] [TestEventLogger]             at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
2023-03-10T14:00:11.575+0000 [DEBUG] [TestEventLogger]             at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
2023-03-10T14:00:11.575+0000 [DEBUG] [TestEventLogger]             at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
2023-03-10T14:00:11.575+0000 [DEBUG] [TestEventLogger]             at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
2023-03-10T14:00:11.575+0000 [DEBUG] [TestEventLogger]             at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
2023-03-10T14:00:11.575+0000 [DEBUG] [TestEventLogger]             at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
2023-03-10T14:00:11.575+0000 [DEBUG] [TestEventLogger]             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2023-03-10T14:00:11.575+0000 [DEBUG] [TestEventLogger]             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2023-03-10T14:00:11.575+0000 [DEBUG] [TestEventLogger]             at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
2023-03-10T14:00:11.575+0000 [DEBUG] [TestEventLogger]             at java.lang.Thread.run(Thread.java:745)
2023-03-10T14:00:11.575+0000 [DEBUG] [TestEventLogger] 
2023-03-10T14:00:11.575+0000 [DEBUG] [TestEventLogger]             Caused by:
2023-03-10T14:00:11.575+0000 [DEBUG] [TestEventLogger]             org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Process didn't end after 10000ms (cmd: '/opt/chromedriver/linux/65/chromedriver --url-base\=wd/hub --port\=8019 --adb-port\=5037 --verbose')
2023-03-10T14:00:11.575+0000 [DEBUG] [TestEventLogger]             Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
2023-03-10T14:00:11.575+0000 [DEBUG] [TestEventLogger]             System info: host: 'ip-172-31-13-65', ip: '172.31.13.65', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-139-generic', java.version: '1.8.0_65'
2023-03-10T14:00:11.577+0000 [DEBUG] [TestEventLogger]             Driver info: io.appium.java_client.android.AndroidDriver
2023-03-10T14:00:11.577+0000 [DEBUG] [TestEventLogger]             Capabilities {app: /tmp/scratchMxyxlW.scratch/..., appActivity: com.southwestairlines.mobil..., appPackage: com.southwestairlines.mobil..., autoAcceptAlerts: true, autoWebView: true, autoWebviewTimeout: 60, automationName: UiAutomator2, chromeOptions: {w3c: false}, chromedriverExecutable: /opt/chromedriver/linux/65/..., databaseEnabled: false, desired: {app: /tmp/scratchMxyxlW.scratch/..., appActivity: com.southwestairlines.mobil..., appPackage: com.southwestairlines.mobil..., autoAcceptAlerts: true, autoWebView: true, autoWebviewTimeout: 60, automationName: UiAutomator2, chromeOptions: {w3c: false}, chromedriverExecutable: /opt/chromedriver/linux/65/..., deviceName: Android Test, enableWebviewDetailsCollection: true, ensureWebviewsHavePages: true, fullContextList: true, newCommandTimeout: 180, platformName: android, platformVersion: 12, udid: R3CT103AZ4J, webviewConnectRetries: 12}, deviceApiLevel: 31, deviceManufacturer: samsung, deviceModel: SM-S906U1, deviceName: R3CT103AZ4J, deviceScreenDensity: 450, deviceScreenSize: 1080x2340, deviceUDID: R3CT103AZ4J, enableWebviewDetailsCollection: true, ensureWebviewsHavePages: true, fullContextList: true, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, newCommandTimeout: 180, pixelRatio: 2.8125, platform: LINUX, platformName: Android, platformVersion: 12, statBarHeight: 74, takesScreenshot: true, udid: R3CT103AZ4J, viewportRect: {height: 2057, left: 0, top: 74, width: 1080}, warnings: {}, webStorageEnabled: false, webviewConnectRetries: 12}
2023-03-10T14:00:11.577+0000 [DEBUG] [TestEventLogger]             Session ID: 44de9967-93d0-4035-8231-d460907d1e35
2023-03-10T14:00:11.577+0000 [DEBUG] [TestEventLogger]                 at sun.reflect.GeneratedConstructorAccessor48.newInstance(Unknown Source)
2023-03-10T14:00:11.577+0000 [DEBUG] [TestEventLogger]                 at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2023-03-10T14:00:11.577+0000 [DEBUG] [TestEventLogger]                 at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
2023-03-10T14:00:11.577+0000 [DEBUG] [TestEventLogger]                 at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
2023-03-10T14:00:11.577+0000 [DEBUG] [TestEventLogger]                 at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
2023-03-10T14:00:11.577+0000 [DEBUG] [TestEventLogger]                 at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
2023-03-10T14:00:11.577+0000 [DEBUG] [TestEventLogger]                 at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
2023-03-10T14:00:11.577+0000 [DEBUG] [TestEventLogger]                 at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:231)
2023-03-10T14:00:11.577+0000 [DEBUG] [TestEventLogger]                 at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
2023-03-10T14:00:11.577+0000 [DEBUG] [TestEventLogger]                 at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
2023-03-10T14:00:11.577+0000 [DEBUG] [TestEventLogger]                 at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
2023-03-10T14:00:11.577+0000 [DEBUG] [TestEventLogger]                 at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
2023-03-10T14:00:11.578+0000 [DEBUG] [TestEventLogger]                 at io.appium.java_client.AppiumDriver.context(AppiumDriver.java:198)
2023-03-10T14:00:11.578+0000 [DEBUG] [TestEventLogger]                 ... 76 more

**Comment by mykola-mokhnach** [comment]
please provide a proper issue description according to the given reporting template
