### ISSUE TITLE
Chromedriver not found for arm64 system(raspberrypi 4)

### ISSUE THREAD

**Issue by antipov-v** [appium/appium#18377]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm not very experienced in unix os and try to run Appium test on Android Chrome browser from raspberrypi 4 and getting the following error:
```
[Chromedriver@0664] Cannot retrieve version number from 'chromedriver_linux64_v111.0.5563.19' Chromedriver binary. 
Make sure it returns a valid version string in response to '--version' command line argument. 
Command '/home/vant/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/chromedriver/linux/chromedriver_linux64_v111.0.5563.19 --version' exited with code 2
....
[debug] [Chromedriver@0664] Found Chrome bundle 'com.android.chrome' version '111.0.5563'
[debug] [Chromedriver@0664] Error: No Chromedriver found that can automate Chrome '111.0.5563'. You could also try to enable automated chromedrivers download as a possible workaround.
[debug] [Chromedriver@0664]     at Chromedriver.getCompatibleChromedriver (/home/vant/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/lib/chromedriver.js:454:15)
[debug] [Chromedriver@0664]     at Chromedriver.initChromedriverPath (/home/vant/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/lib/chromedriver.js:486:11)
[debug] [Chromedriver@0664]     at Chromedriver.start (/home/vant/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/lib/chromedriver.js:567:32)
[debug] [Chromedriver@0664]     at AndroidUiautomator2Driver.setupNewChromedriver (/home/vant/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/context.js:471:3)
[debug] [Chromedriver@0664]     at AndroidUiautomator2Driver.startChromeSession (/home/vant/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/context.js:324:23)
[debug] [Chromedriver@0664]     at AndroidUiautomator2Driver.startUiAutomator2Session (/home/vant/.appium/node_modules/appium-uiautomator2-driver/lib/driver.js:440:7)
[debug] [Chromedriver@0664]     at AndroidUiautomator2Driver.createSession (/home/vant/.appium/node_modules/appium-uiautomator2-driver/lib/driver.js:240:7)
[debug] [Chromedriver@0664]     at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:349:35)
[Chromedriver@0664] No Chromedriver found that can automate Chrome '111.0.5563'. You could also try to enable automated chromedrivers download as a possible workaround.

```
As I understand the downloaded by Appium chromedriver is not compatible with my system, because it's arm64, is there could be any solution?

### Expected Behavior

Appium could find compatible driver

### Minimal Reproducible Example

```
from appium import webdriver

des_caps = {
    "platformName": "Android",
    "deviceName": "Android",
    "browserName": "Chrome",
    "automationName": "UiAutomator2",
    "udid": "0A051JEC208152"
}

driver = webdriver.Remote("http://localhost:4723", des_caps)
```

### Environment

- OS: Linux raspberrypi 5.15.84-v8+ https://github.com/appium/appium/issues/1613 SMP PREEMPT Thu Jan 5 12:03:08 GMT 2023 aarch64 GNU/Linux
- Appium: 2.0.0-beta.57
- Node.js version: v19.8.1
- `npm` version: 9.6.2
- Appium driver(s): uiautomator2@2.12.6
- device/platform: Google Pixel 4a, Andoid 13, Build: TQ1A.230205.002,  Chrome bundle 'com.android.chrome' version '111.0.5563'

**Comment by mykola-mokhnach** [comment]
Are you sure the chromedriver binary is executable there? have you tried to run it manually by providing the `--version` arg?

**Comment by mykola-mokhnach** [comment]
There was recently a fix applied to uia2 driver related to automated chrome drivers download. Update the driver to the most recent version and try again.
