### ISSUE TITLE
Failed to create session on window 11

### ISSUE THREAD

**Issue by Schepetkov** [appium/appium#18474]
Failed to create session. An unknown server-side error occurred while processing the command. Original error: WinAppDriver server is not listening within 10000ms timeout.

**Preparation steps:**
[WinAppDriver v1.3 Release Candidate 1 (1.2.99)](https://github.com/microsoft/WinAppDriver/releases/tag/v1.2.99)

npm i -g appium@next
appium driver install --source=npm appium-windows-driver

**AddAdditionalCapability:**
{
  "appium:app": "Microsoft.WindowsCalculator_8wekyb3d8bbwe!App",
  "appium:automationName": "windows",
  "platformName": "Windows",
  "ms:experimental-webdriver": true
}
![image](https://user-images.githubusercontent.com/29506847/230587967-7f1b2999-96a6-4e3a-be61-351e30a61bb7.png)

**Result:**
```
PS C:\Users\schep> appium
[Appium] Welcome to Appium v2.0.0-beta.61
[Appium] Attempting to load driver windows...
[debug] [Appium] Requiring driver at C:\Users\schep\.appium\node_modules\appium-windows-driver
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[Appium] Available drivers:
[Appium]   - windows@2.7.1 (automationName 'Windows')
[Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.
[HTTP] --> POST /session
[HTTP] {"capabilities":{"alwaysMatch":{"appium:app":"Microsoft.WindowsCalculator_8wekyb3d8bbwe!App","appium:automationName":"windows","platformName":"Windows","ms:experimental-webdriver":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]},"desiredCapabilities":{"appium:app":"Microsoft.WindowsCalculator_8wekyb3d8bbwe!App","appium:automationName":"windows","platformName":"Windows","ms:experimental-webdriver":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true}}
[debug] [AppiumDriver@d314] Calling AppiumDriver.createSession() with args: [{"appium:app":"Microsoft.WindowsCalculator_8wekyb3d8bbwe!App","appium:automationName":"windows","platformName":"Windows","ms:experimental-webdriver":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},null,{"alwaysMatch":{"appium:app":"Microsoft.WindowsCalculator_8wekyb3d8bbwe!App","appium:automationName":"windows","platformName":"Windows","ms:experimental-webdriver":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]}]
[debug] [AppiumDriver@d314] Event 'newSessionRequested' logged at 1680860478372 (11:41:18 GMT+0200 (Central European Summer Time))
[Appium] Attempting to find matching driver for automationName 'windows' and platformName 'Windows'
[Appium] The 'windows' driver was installed and matched caps.
[Appium] Will require it at C:\Users\schep\.appium\node_modules\appium-windows-driver
[debug] [Appium] Requiring driver at C:\Users\schep\.appium\node_modules\appium-windows-driver
[AppiumDriver@d314] Appium v2.0.0-beta.61 creating new WindowsDriver (v2.7.1) session
[AppiumDriver@d314] Checking BaseDriver versions for Appium and WindowsDriver
[AppiumDriver@d314] Appium's BaseDriver version is 9.3.5
[AppiumDriver@d314] WindowsDriver's BaseDriver version is 9.3.5
[debug] [WindowsDriver@5812] Creating session with W3C capabilities: {
[debug] [WindowsDriver@5812]   "alwaysMatch": {
[debug] [WindowsDriver@5812]     "platformName": "Windows",
[debug] [WindowsDriver@5812]     "ms:experimental-webdriver": true,
[debug] [WindowsDriver@5812]     "appium:app": "Microsoft.WindowsCalculator_8wekyb3d8bbwe!App",
[debug] [WindowsDriver@5812]     "appium:automationName": "windows",
[debug] [WindowsDriver@5812]     "appium:newCommandTimeout": 3600,
[debug] [WindowsDriver@5812]     "appium:connectHardwareKeyboard": true
[debug] [WindowsDriver@5812]   },
[debug] [WindowsDriver@5812]   "firstMatch": [
[debug] [WindowsDriver@5812]     {}
[debug] [WindowsDriver@5812]   ]
[debug] [WindowsDriver@5812] }
[WindowsDriver@5812] The following capabilities were provided, but are not recognized by Appium:
[WindowsDriver@5812]   connectHardwareKeyboard
[WindowsDriver@5812 (c67457fe)] Session created with session id: c67457fe-fd1f-4b24-a5f6-7b3cb882d61a
[WindowsDriver@5812 (c67457fe)] Spawning 'C:\Program Files\Windows Application Driver\WinAppDriver.exe' with args: ["4724/wd/hub"]
[debug] [WindowsDriver@5812 (c67457fe)] Matched '/status' to command name 'getStatus'
[debug] [WindowsDriver@5812 (c67457fe)] Proxying [GET /status] to [GET http://127.0.0.1:4724/wd/hub/status] with no body
[debug] [WindowsDriver@5812 (c67457fe)] Windows Application Driver listening for requests at: http://127.0.0.1:4724/wd/hub
[debug] [WindowsDriver@5812 (c67457fe)] Press ENTER to exit.
[debug] [WindowsDriver@5812 (c67457fe)] ==========================================
[debug] [WindowsDriver@5812 (c67457fe)] GET /wd/hub/status HTTP/1.1
[debug] [WindowsDriver@5812 (c67457fe)] Accept: application/json, */*
[debug] [WindowsDriver@5812 (c67457fe)] Accept-Encoding: gzip, compress, deflate, br
[debug] [WindowsDriver@5812 (c67457fe)] Connection: keep-alive
[debug] [WindowsDriver@5812 (c67457fe)] Content-Type: application/json; charset=utf-8
[debug] [WindowsDriver@5812 (c67457fe)] Host: 127.0.0.1:4724
[debug] [WindowsDriver@5812 (c67457fe)] User-Agent: appium
[WindowsDriver@5812 (c67457fe)] Got response with status 500: {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[debug] [W3C] Matched W3C error code 'unknown error' to UnknownError
[debug] [WindowsDriver@5812 (c67457fe)] HTTP/1.1 500 Internal Error
[debug] [WindowsDriver@5812 (c67457fe)] Content-Length: 133
[debug] [WindowsDriver@5812 (c67457fe)] Content-Type: application/json
[debug] [WindowsDriver@5812 (c67457fe)] Matched '/status' to command name 'getStatus'
[debug] [WindowsDriver@5812 (c67457fe)] Proxying [GET /status] to [GET http://127.0.0.1:4724/wd/hub/status] with no body
[debug] [WindowsDriver@5812 (c67457fe)] ==========================================
[debug] [WindowsDriver@5812 (c67457fe)] GET /wd/hub/status HTTP/1.1
[debug] [WindowsDriver@5812 (c67457fe)] Accept: application/json, */*
[debug] [WindowsDriver@5812 (c67457fe)] Accept-Encoding: gzip, compress, deflate, br
[debug] [WindowsDriver@5812 (c67457fe)] Connection: keep-alive
[debug] [WindowsDriver@5812 (c67457fe)] Content-Type: application/json; charset=utf-8
[debug] [WindowsDriver@5812 (c67457fe)] Host: 127.0.0.1:4724
[debug] [WindowsDriver@5812 (c67457fe)] User-Agent: appium
[WindowsDriver@5812 (c67457fe)] Got response with status 500: {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[debug] [W3C] Matched W3C error code 'unknown error' to UnknownError
[debug] [WindowsDriver@5812 (c67457fe)] HTTP/1.1 500 Internal Error
[debug] [WindowsDriver@5812 (c67457fe)] Content-Length: 133
[debug] [WindowsDriver@5812 (c67457fe)] Content-Type: application/json
[debug] [WindowsDriver@5812 (c67457fe)]
[debug] [WindowsDriver@5812 (c67457fe)] {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[debug] [WindowsDriver@5812 (c67457fe)] Matched '/status' to command name 'getStatus'
[debug] [WindowsDriver@5812 (c67457fe)] Proxying [GET /status] to [GET http://127.0.0.1:4724/wd/hub/status] with no body
[debug] [WindowsDriver@5812 (c67457fe)] ==========================================
[debug] [WindowsDriver@5812 (c67457fe)] GET /wd/hub/status HTTP/1.1
[debug] [WindowsDriver@5812 (c67457fe)] Accept: application/json, */*
[debug] [WindowsDriver@5812 (c67457fe)] Accept-Encoding: gzip, compress, deflate, br
[debug] [WindowsDriver@5812 (c67457fe)] Connection: keep-alive
[debug] [WindowsDriver@5812 (c67457fe)] Content-Type: application/json; charset=utf-8
[debug] [WindowsDriver@5812 (c67457fe)] Host: 127.0.0.1:4724
[debug] [WindowsDriver@5812 (c67457fe)] User-Agent: appium
[WindowsDriver@5812 (c67457fe)] Got response with status 500: {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[debug] [W3C] Matched W3C error code 'unknown error' to UnknownError
[debug] [WindowsDriver@5812 (c67457fe)] HTTP/1.1 500 Internal Error
[debug] [WindowsDriver@5812 (c67457fe)] Content-Length: 133
[debug] [WindowsDriver@5812 (c67457fe)] Content-Type: application/json
[debug] [WindowsDriver@5812 (c67457fe)]
[debug] [WindowsDriver@5812 (c67457fe)] {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[debug] [WindowsDriver@5812 (c67457fe)] Matched '/status' to command name 'getStatus'
[debug] [WindowsDriver@5812 (c67457fe)] Proxying [GET /status] to [GET http://127.0.0.1:4724/wd/hub/status] with no body
[debug] [WindowsDriver@5812 (c67457fe)] ==========================================
[debug] [WindowsDriver@5812 (c67457fe)] GET /wd/hub/status HTTP/1.1
[debug] [WindowsDriver@5812 (c67457fe)] Accept: application/json, */*
[debug] [WindowsDriver@5812 (c67457fe)] Accept-Encoding: gzip, compress, deflate, br
[debug] [WindowsDriver@5812 (c67457fe)] Connection: keep-alive
[debug] [WindowsDriver@5812 (c67457fe)] Content-Type: application/json; charset=utf-8
[debug] [WindowsDriver@5812 (c67457fe)] Host: 127.0.0.1:4724
[debug] [WindowsDriver@5812 (c67457fe)] User-Agent: appium
[WindowsDriver@5812 (c67457fe)] Got response with status 500: {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[debug] [W3C] Matched W3C error code 'unknown error' to UnknownError
[debug] [WindowsDriver@5812 (c67457fe)] HTTP/1.1 500 Internal Error
[debug] [WindowsDriver@5812 (c67457fe)] Content-Length: 133
[debug] [WindowsDriver@5812 (c67457fe)] Content-Type: application/json
[debug] [WindowsDriver@5812 (c67457fe)]
[debug] [WindowsDriver@5812 (c67457fe)] {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[debug] [WindowsDriver@5812 (c67457fe)] Matched '/status' to command name 'getStatus'
[debug] [WindowsDriver@5812 (c67457fe)] Proxying [GET /status] to [GET http://127.0.0.1:4724/wd/hub/status] with no body
[debug] [WindowsDriver@5812 (c67457fe)] ==========================================
[debug] [WindowsDriver@5812 (c67457fe)] GET /wd/hub/status HTTP/1.1
[debug] [WindowsDriver@5812 (c67457fe)] Accept: application/json, */*
[debug] [WindowsDriver@5812 (c67457fe)] Accept-Encoding: gzip, compress, deflate, br
[debug] [WindowsDriver@5812 (c67457fe)] Connection: keep-alive
[debug] [WindowsDriver@5812 (c67457fe)] Content-Type: application/json; charset=utf-8
[debug] [WindowsDriver@5812 (c67457fe)] Host: 127.0.0.1:4724
[debug] [WindowsDriver@5812 (c67457fe)] User-Agent: appium
[debug] [WindowsDriver@5812 (c67457fe)]
[debug] [WindowsDriver@5812 (c67457fe)]
[debug] [WindowsDriver@5812 (c67457fe)] HTTP/1.1 500 Internal Error
[debug] [WindowsDriver@5812 (c67457fe)] Content-Length: 133
[debug] [WindowsDriver@5812 (c67457fe)] Content-Type: application/json
[debug] [WindowsDriver@5812 (c67457fe)]
[debug] [WindowsDriver@5812 (c67457fe)] {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[WindowsDriver@5812 (c67457fe)] Got response with status 500: {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[debug] [W3C] Matched W3C error code 'unknown error' to UnknownError
[debug] [WindowsDriver@5812 (c67457fe)] Matched '/status' to command name 'getStatus'
[debug] [WindowsDriver@5812 (c67457fe)] Proxying [GET /status] to [GET http://127.0.0.1:4724/wd/hub/status] with no body
[debug] [WindowsDriver@5812 (c67457fe)] ==========================================
[debug] [WindowsDriver@5812 (c67457fe)] GET /wd/hub/status HTTP/1.1
[debug] [WindowsDriver@5812 (c67457fe)] Accept: application/json, */*
[debug] [WindowsDriver@5812 (c67457fe)] Accept-Encoding: gzip, compress, deflate, br
[debug] [WindowsDriver@5812 (c67457fe)] Connection: keep-alive
[debug] [WindowsDriver@5812 (c67457fe)] Content-Type: application/json; charset=utf-8
[debug] [WindowsDriver@5812 (c67457fe)] Host: 127.0.0.1:4724
[debug] [WindowsDriver@5812 (c67457fe)] User-Agent: appium
[WindowsDriver@5812 (c67457fe)] Got response with status 500: {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[debug] [W3C] Matched W3C error code 'unknown error' to UnknownError
[debug] [WindowsDriver@5812 (c67457fe)] HTTP/1.1 500 Internal Error
[debug] [WindowsDriver@5812 (c67457fe)] Content-Length: 133
[debug] [WindowsDriver@5812 (c67457fe)] Content-Type: application/json
[debug] [WindowsDriver@5812 (c67457fe)]
[debug] [WindowsDriver@5812 (c67457fe)] {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[debug] [WindowsDriver@5812 (c67457fe)] Matched '/status' to command name 'getStatus'
[debug] [WindowsDriver@5812 (c67457fe)] Proxying [GET /status] to [GET http://127.0.0.1:4724/wd/hub/status] with no body
[debug] [WindowsDriver@5812 (c67457fe)] ==========================================
[debug] [WindowsDriver@5812 (c67457fe)] GET /wd/hub/status HTTP/1.1
[debug] [WindowsDriver@5812 (c67457fe)] Accept: application/json, */*
[debug] [WindowsDriver@5812 (c67457fe)] Accept-Encoding: gzip, compress, deflate, br
[debug] [WindowsDriver@5812 (c67457fe)] Connection: keep-alive
[debug] [WindowsDriver@5812 (c67457fe)] Content-Type: application/json; charset=utf-8
[debug] [WindowsDriver@5812 (c67457fe)] Host: 127.0.0.1:4724
[debug] [WindowsDriver@5812 (c67457fe)] User-Agent: appium
[WindowsDriver@5812 (c67457fe)] Got response with status 500: {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[debug] [W3C] Matched W3C error code 'unknown error' to UnknownError
[debug] [WindowsDriver@5812 (c67457fe)] HTTP/1.1 500 Internal Error
[debug] [WindowsDriver@5812 (c67457fe)] Content-Length: 133
[debug] [WindowsDriver@5812 (c67457fe)] Content-Type: application/json
[debug] [WindowsDriver@5812 (c67457fe)]
[debug] [WindowsDriver@5812 (c67457fe)] {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[debug] [WindowsDriver@5812 (c67457fe)] Matched '/status' to command name 'getStatus'
[debug] [WindowsDriver@5812 (c67457fe)] Proxying [GET /status] to [GET http://127.0.0.1:4724/wd/hub/status] with no body
[debug] [WindowsDriver@5812 (c67457fe)] ==========================================
[debug] [WindowsDriver@5812 (c67457fe)] GET /wd/hub/status HTTP/1.1
[debug] [WindowsDriver@5812 (c67457fe)] Accept: application/json, */*
[debug] [WindowsDriver@5812 (c67457fe)] Accept-Encoding: gzip, compress, deflate, br
[debug] [WindowsDriver@5812 (c67457fe)] Connection: keep-alive
[debug] [WindowsDriver@5812 (c67457fe)] Content-Type: application/json; charset=utf-8
[debug] [WindowsDriver@5812 (c67457fe)] Host: 127.0.0.1:4724
[debug] [WindowsDriver@5812 (c67457fe)] User-Agent: appium
[WindowsDriver@5812 (c67457fe)] Got response with status 500: {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[debug] [W3C] Matched W3C error code 'unknown error' to UnknownError
[debug] [WindowsDriver@5812 (c67457fe)] HTTP/1.1 500 Internal Error
[debug] [WindowsDriver@5812 (c67457fe)] Content-Length: 133
[debug] [WindowsDriver@5812 (c67457fe)] Content-Type: application/json
[debug] [WindowsDriver@5812 (c67457fe)]
[debug] [WindowsDriver@5812 (c67457fe)] {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[debug] [WindowsDriver@5812 (c67457fe)] Matched '/status' to command name 'getStatus'
[debug] [WindowsDriver@5812 (c67457fe)] Proxying [GET /status] to [GET http://127.0.0.1:4724/wd/hub/status] with no body
[debug] [WindowsDriver@5812 (c67457fe)] ==========================================
[debug] [WindowsDriver@5812 (c67457fe)] GET /wd/hub/status HTTP/1.1
[debug] [WindowsDriver@5812 (c67457fe)] Accept: application/json, */*
[debug] [WindowsDriver@5812 (c67457fe)] Accept-Encoding: gzip, compress, deflate, br
[debug] [WindowsDriver@5812 (c67457fe)] Connection: keep-alive
[debug] [WindowsDriver@5812 (c67457fe)] Content-Type: application/json; charset=utf-8
[debug] [WindowsDriver@5812 (c67457fe)] Host: 127.0.0.1:4724
[debug] [WindowsDriver@5812 (c67457fe)] User-Agent: appium
[WindowsDriver@5812 (c67457fe)] Got response with status 500: {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[debug] [W3C] Matched W3C error code 'unknown error' to UnknownError
[debug] [WindowsDriver@5812 (c67457fe)] HTTP/1.1 500 Internal Error
[debug] [WindowsDriver@5812 (c67457fe)] Content-Length: 133
[debug] [WindowsDriver@5812 (c67457fe)] Content-Type: application/json
[debug] [WindowsDriver@5812 (c67457fe)]
[debug] [WindowsDriver@5812 (c67457fe)] {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[debug] [WindowsDriver@5812 (c67457fe)] Matched '/status' to command name 'getStatus'
[debug] [WindowsDriver@5812 (c67457fe)] Proxying [GET /status] to [GET http://127.0.0.1:4724/wd/hub/status] with no body
[debug] [WindowsDriver@5812 (c67457fe)] ==========================================
[debug] [WindowsDriver@5812 (c67457fe)] GET /wd/hub/status HTTP/1.1
[debug] [WindowsDriver@5812 (c67457fe)] Accept: application/json, */*
[debug] [WindowsDriver@5812 (c67457fe)] Accept-Encoding: gzip, compress, deflate, br
[debug] [WindowsDriver@5812 (c67457fe)] Connection: keep-alive
[debug] [WindowsDriver@5812 (c67457fe)] Content-Type: application/json; charset=utf-8
[debug] [WindowsDriver@5812 (c67457fe)] Host: 127.0.0.1:4724
[debug] [WindowsDriver@5812 (c67457fe)] User-Agent: appium
[debug] [WindowsDriver@5812 (c67457fe)]
[debug] [WindowsDriver@5812 (c67457fe)]
[debug] [WindowsDriver@5812 (c67457fe)] HTTP/1.1 500 Internal Error
[debug] [WindowsDriver@5812 (c67457fe)] Content-Length: 133
[debug] [WindowsDriver@5812 (c67457fe)] Content-Type: application/json
[debug] [WindowsDriver@5812 (c67457fe)]
[debug] [WindowsDriver@5812 (c67457fe)] {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[WindowsDriver@5812 (c67457fe)] Got response with status 500: {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[debug] [W3C] Matched W3C error code 'unknown error' to UnknownError
[debug] [WindowsDriver@5812 (c67457fe)] Matched '/status' to command name 'getStatus'
[debug] [WindowsDriver@5812 (c67457fe)] Proxying [GET /status] to [GET http://127.0.0.1:4724/wd/hub/status] with no body
[debug] [WindowsDriver@5812 (c67457fe)] ==========================================
[debug] [WindowsDriver@5812 (c67457fe)] GET /wd/hub/status HTTP/1.1
[debug] [WindowsDriver@5812 (c67457fe)] Accept: application/json, */*
[debug] [WindowsDriver@5812 (c67457fe)] Accept-Encoding: gzip, compress, deflate, br
[debug] [WindowsDriver@5812 (c67457fe)] Connection: keep-alive
[debug] [WindowsDriver@5812 (c67457fe)] Content-Type: application/json; charset=utf-8
[debug] [WindowsDriver@5812 (c67457fe)] Host: 127.0.0.1:4724
[debug] [WindowsDriver@5812 (c67457fe)] User-Agent: appium
[WindowsDriver@5812 (c67457fe)] Got response with status 500: {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[debug] [W3C] Matched W3C error code 'unknown error' to UnknownError
[debug] [WindowsDriver@5812 (c67457fe)] Deleting WinAppDriver session
[debug] [WindowsDriver@5812 (c67457fe)] HTTP/1.1 500 Internal Error
[debug] [WindowsDriver@5812 (c67457fe)] Content-Length: 133
[debug] [WindowsDriver@5812 (c67457fe)] Content-Type: application/json
[debug] [WindowsDriver@5812 (c67457fe)]
[debug] [WindowsDriver@5812 (c67457fe)] {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[WindowsDriver@5812 (c67457fe)] WinAppDriver exited with code null, signal SIGTERM
[debug] [AppiumDriver@d314] Event 'newSessionStarted' logged at 1680860488423 (11:41:28 GMT+0200 (Central European Summer Time))
[debug] [AppiumDriver@d314] Encountered internal error running command: Error: WinAppDriver server is not listening within 10000ms timeout. Make sure it could be started manually
[debug] [AppiumDriver@d314]     at WinAppDriver.start (C:\Users\schep\.appium\node_modules\appium-windows-driver\lib\winappdriver.js:157:15)
[debug] [AppiumDriver@d314]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[debug] [AppiumDriver@d314]     at WindowsDriver.startWinAppDriverSession (C:\Users\schep\.appium\node_modules\appium-windows-driver\lib\driver.js:92:5)
[debug] [AppiumDriver@d314]     at WindowsDriver.createSession (C:\Users\schep\.appium\node_modules\appium-windows-driver\lib\driver.js:80:7)
[debug] [AppiumDriver@d314]     at AppiumDriver.createSession (C:\Users\schep\AppData\Roaming\npm\node_modules\appium\lib\appium.js:346:35)
[HTTP] <-- POST /session 500 10077 ms - 764
```
**PS:** On my work computer with window 10, everything works fine with the same settings.

_Edited by @boneskull: reformatting_

**Comment by boneskull** [comment]
If you go to the command line and launch `'C:\Program Files\Windows Application Driver\WinAppDriver.exe 4724/wd/hub`, what happens?

**Comment by Schepetkov** [comment]
@boneskull Hi, thanks for try to help me.
![image](https://user-images.githubusercontent.com/29506847/230710126-c1498949-682f-4419-8196-cd4604ed5992.png)

**Comment by jlipps** [comment]
Pretty sure the Appium Inspector isn't compatible with the windows driver. But to see what the exact issue is: try to use curl or some other http tool to make a `GET` request to `http://127.0.0.1:4724/wd/hub/status` with WAD running. What happens?

**Comment by Schepetkov** [comment]
@jlipps Hi, thanks for trying to help me, sorry for the late reply, lots of work.  I sent via postman, is this ok? 
![image](https://user-images.githubusercontent.com/29506847/231868998-e38af674-f449-4329-8297-e9ad05776f41.png)

**Comment by Schepetkov** [comment]
If I sent to http://127.0.0.1:4724/wd/hub/status
![image](https://user-images.githubusercontent.com/29506847/231871870-5ebfd44b-d33e-4041-84c1-65dc9979b94f.png)
![image](https://user-images.githubusercontent.com/29506847/231871978-fd9d3653-c523-4891-95ed-46a2dda76cbd.png)

**Comment by Schepetkov** [comment]
I think I understand, you need to send a request with the conditions from the previous step, sorry.
![image](https://user-images.githubusercontent.com/29506847/231875149-300652db-d00f-490d-af28-b33db6286408.png)

**Comment by jlipps** [comment]
In the last image, WAD is not running. You have a problem in your shell command (a space). In the second to last image WAD is running on port 4723 but you're making a request to port 4724. Please fix so we can see what happens when you make a request to the server.

**Comment by Schepetkov** [comment]
> WinAppDriver.exe 4724/wd/hub
Sorry, I was already asleep on the go and didn't notice.
![image](https://user-images.githubusercontent.com/29506847/232223619-cac35042-1260-4a55-805e-bc14eeb7497d.png)

**Comment by jlipps** [comment]
Seems like WAD errored during the /status command. This is therefore an issue with WAD and I would report it there!
