### ISSUE TITLE
Error: iOS 15, An unknown server-side error, Unable to rotate device

### ISSUE THREAD

**Issue by rasim-sitmanbetov** [appium/appium#18907]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm trying to rotate iOS device to LANDSCAPE orientation and getting next server error:
`org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Unable To Rotate Device
Build info: version: '4.8.3', revision: 'e5e76298c3'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-1030-aws', java.version: '11.0.19'
Driver info: com.ring.aqa.mobilecommon.engine.appium.driver.DockerizedXCUIManager$1
Command: [aaa76ca0ebefac40a22469e27de802c3b938c00c-2c07-4213-a408-142c52fc0d2d, setScreenOrientation {orientation=LANDSCAPE}]
Capabilities {appium:app: https://aqa-http-file-serve/..., appium:appInstallStrategy: ios-deploy, appium:appPushTimeout: 300000, appium:automationName: XCuiTest, appium:clearSystemFiles: true, appium:connectHardwareKeyboard: true, appium:databaseEnabled: false, appium:derivedDataPath: /jenkins/workspace/mobile-t..., appium:deviceName: iPhone, appium:fullReset: false, appium:javascriptEnabled: true, appium:locationContextEnabled: false, appium:networkConnectionEnabled: false, appium:newCommandTimeout: 3600, appium:noReset: true, appium:orientation: PORTRAIT, appium:platformVersion: 15.3, appium:processArguments: {args: [], env: {}}, appium:showXcodeLog: true, appium:takesScreenshot: true, appium:udid: 00008030-001960AC1ED0402E, appium:useJSONSource: true, appium:usePrebuiltWDA: true, appium:webStorageEnabled: false, browserVersion: 14.4, platformName: IOS}
Session ID: aaa76ca0ebefac40a22469e27de802c3b938c00c-2c07-4213-a408-142c52fc0d2d
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:193)
at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:262)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:598)
at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:267)
at com.ring.aqa.mobilecommon.engine.appium.driver.DockerizedXCUIManager$1.execute(DockerizedXCUIManager.java:110)
at io.appium.java_client.remote.SupportsRotation.rotate(SupportsRotation.java:46)`

from appium log:
`2023-07-24 14:16:38:989 [HTTP] --> POST /wd/hub/session/b6e2550d-a415-4766-aebb-c26e5879ec85/orientation
2023-07-24 14:16:38:989 [HTTP] {"orientation":"LANDSCAPE"}
2023-07-24 14:16:38:989 [XCUITestDriver@31f5 (b6e2550d)] Driver proxy active, passing request on via HTTP proxy
2023-07-24 14:16:38:989 [XCUITestDriver@31f5 (b6e2550d)] Executing command 'proxyReqRes'
2023-07-24 14:16:38:990 [XCUITestDriver@31f5 (b6e2550d)] Matched '/wd/hub/session/b6e2550d-a415-4766-aebb-c26e5879ec85/orientation' to command name 'setOrientation'
2023-07-24 14:16:38:990 [XCUITestDriver@31f5 (b6e2550d)] Proxying [POST /wd/hub/session/b6e2550d-a415-4766-aebb-c26e5879ec85/orientation] to [POST http://127.0.0.1:8100/session/F6D65903-A1C6-4B89-A974-239A3A69FFDD/orientation] with body: {"orientation":"LANDSCAPE"}
2023-07-24 14:16:39:022 [XCUITestDriver@31f5 (b6e2550d)] Got response with status 500: {"value":{"error":"unknown error","message":"Unable To Rotate Device","traceback":""},"sessionId":"F6D65903-A1C6-4B89-A974-239A3A69FFDD"}
2023-07-24 14:16:39:023 [W3C] Matched W3C error code 'unknown error' to UnknownError
2023-07-24 14:16:39:024 [HTTP] <-- POST /wd/hub/session/b6e2550d-a415-4766-aebb-c26e5879ec85/orientation 500 35 ms - 874`

### Expected Behavior

Screen rotated to LANDSCAPE

### Minimal Reproducible Example
`try {
		URL url = new URL("http://127.0.0.1:4723");
		IOSDriver driver = new IOSDriver(url, options);
		...
                driver.rotate(ScreenOrientation.LANDSCAPE);
		driver.quit();
		service.stop();
	} catch (Exception e) {
		// TODO Auto-generated catch block
		service.stop();
		e.printStackTrace();
}`

### Environment

- Operating system: MacOS
- Appium server version (output of `appium --version`): 2.0.0
- Appium driver(s) and their version(s): xcuitest@4.21.7
- Appium plugin(s) and their version(s):
- Last component(s) version which did _not_ exhibit the problem: no problems on iOS 16
- Platform and version under test: iOS 15
- Real device or emulator/simulator: real device

### Link to Appium Logs

https://gist.github.com/rasim-sitmanbetov/f62936b4d7c08346bfcf49bdc8d781b3

**Comment by KazuCocoa** [comment]
It means https://developer.apple.com/documentation/xctest/xcuidevice/1619046-orientation?language=objc returned an error. Appium/WDA calls the XCTest api as  the endpoint.

Afaik, the typical situation is the device model/OS version has an issue for the orientation, or the the device had weird state so rebooting the device helped. so far, I saw iPhone probably 13 had the issue in various OS versions. Of course, the error also cold depends on OS. Then, reporting it to Apple is more proper than here as the XCTest API's response as Appium/WDA.
