### ISSUE TITLE
Appium crashed when page is having huge dom structure on ios native application

### ISSUE THREAD

**Issue by bijitbiswas** [appium/appium#18925]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Our application is having a page with 40k+ records which is like 40k+ XCUIElementTypeCell in scrollable view and inside each of them have 5 XCUIElementTypeText. So basically the DOM structure is huge.
The response as page structure is huge unable to load 

When trying to inspect or load page having a huge dom structure the appium is crashing. Is there a way that I can stop appium from identifying elements or like just load page till the part its visible?
 
**My Appium logs**
```
[W3C (e3d08ab8)] Responding to client with driver.getPageSource() result: "\n\n  \n    \n      \n        \n          \n            \n              
[HTTP] <-- GET /wd/hub/session/e3d08ab8-5132-48e6-9c45-cc1408b1d848/source 200 2328 ms - 43235
[HTTP] 
[HTTP] --> GET /wd/hub/session/e3d08ab8-5132-48e6-9c45-cc1408b1d848/screenshot
[HTTP] {}
[W3C (e3d08ab8)] Calling AppiumDriver.getScreenshot() with args: ["e3d08ab8-5132-48e6-9c45-cc1408b1d848"]
[XCUITest] Executing command 'getScreenshot'
[XCUITest] Taking screenshot with WDA
[WD Proxy] Matched '/screenshot' to command name 'getScreenshot'
[WD Proxy] Proxying [GET /screenshot] to [GET http://127.0.0.1:8100/session/AD84FE98-182F-4836-8B51-00FD1AC1041A/screenshot] with no body
[WD Proxy] Got response with status 200: {"value":"iVBORw0KGgoAAAANSUhEUgAABmgAAAk4CAYAAABsvzLGAAAAAXNSR0IArs4c6QAAADhlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAAqACAAQAAAABAAAGaKADAAQAAAABAAAJOAAAAABN+1utAAAAHGlET1QAAAACAAAAAAAABJwAAAAoAAAEnAAABJwAAi4bIKvXLgAAQABJREFUeAHs3Qe8lNWd//Fsdv9uko0bo0YT3RRdddWY1TV2BQW7Yif2EuzGiIqaoMaoFKVIkaYggoAoTXqXIr33LiAICIpI7wi///k++IzPnTtz7zP3ztx5Zubz+Hq8c2eecs77DIOe75xzfmBsCCCAAAIIIIAAAgUlMHHi5IKqL5VFAAEEEEAAAQQQQAABBBBAIIoCP4hioSgTAggggAACCCCAQOYECGgyZ8uVEUAAAQQQQAABBBBAAAEEEAgrQEATVorjEEAAAQQQQACBPBEgoMmThqQaCCCAAAIIIIAAAggggAACOS1AQJPTzUfhEUAAAQQQQACB1AUIaFI34wwEEEAAAQQQQAABBBBAAAEE0i1AQJNuUa6HAAIIIIAAAghEXICAJuINRPEQQAABBBBAAAEEEEAAAQQKQoCApiCamUoigAACCCCAAALfCxDQfG/BIwQQQAABBBBAAAEEEEAAAQSyJUBAky157osAAggggAACCGRJgIAmS/DcFgEEEEAAAQQQQAABBBBAAIGAAAFNAIOHCCCAAAIIIIBAIQgQ0BRCK1NHBBBAAAEEEEAAAQQQQACBqAsQ0ES9hSgfAggggAACCCCQZgECmjSDcjkEEEAAAQQQQAABBBBAAAEEyiBAQFMGNE5BAAEEEEAAAQRyWYCAJpdbj7IjgAACCCCAAAIIIIAAAgjkiwABTb60JPVAAAEEEEAAAQRCChDQhITiMAQQQAABBBBAAAEEEEAAAQQyKEBAk0FcLo0AAggggAACCERRgIAmiq1CmRBAAAEEEEAAAQQQQAA...
[W3C (e3d08ab8)] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAABmgAAAk4CAYAAABsvzLGAAAAAXNSR0IArs4c6QAAADhlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAAqACAAQAAAABAAAGaKADAAQAAAABAAAJOAAAAABN+1utAAAAHGlET1QAAAACAAAAAAAABJwAAAAoAAAEnAAABJwAAi4bIKvXLgAAQABJREFUeAHs3Qe8lNWd//Fsdv9uko0bo0YT3RRdddWY1TV2BQW7Yif2EuzGiIqaoMaoFKVIkaYggoAoTXqXIr33LiAICIpI7wi///k++IzPnTtz7zP3ztx5Zubz+Hq8c2eecs77DIOe75xzfmBsCCCAAAIIIIAAAgUlMHHi5IKqL5VFAAEEEEAAAQQQQAABBBBAIIoCP4hioSgTAggggAACCCCAQOYECGgyZ8uVEUAAAQQQQAABBBBAAAEEEAgrQEATVorjEEAAAQQQQACBPBEgoMmThqQaCCCAAAIIIIAAAggggAACOS1AQJPTzUfhEUAAAQQQQACB1AUIaFI34wwEEEAAAQQQQAABBBBAAAEE0i1AQJNuUa6HAAIIIIAAAghEXICAJuINRPEQQAABBBBAAAEEEEAAAQQKQoCApiCamUoigAACCCCAAALfCxDQfG/BIwQQQAABBBBAAAEEEEAAAQSyJUBAky157osAAggggAACCGRJgIAmS/DcFgEEEEAAAQQQQAABBBBAAIGAAAFNAIOHCCCAAAIIIIBAIQgQ0BRCK1NHBBBAAAEEEEAAAQQQQACBqAsQ0ES9hSgfAggggAACCCCQZgECmjSDcjkEEEAAAQQQQAABBBBAAAEEyiBAQFMGNE5BAAEEEEAAAQRyWYCAJpdbj7IjgAACCCCAAAIIIIAAAgjkiwABTb60JPVAAAEEEEAAAQRCChDQhITiMAQQQAABBBBAAAEEEEAAAQQyKEBAk0FcLo0AAggggAACCERRgIAmiq1CmRBAAAEEEEAAAQQQQAABBIICX3/9...
[HTTP] <-- GET /wd/hub/session/e3d08ab8-5132-48e6-9c45-cc1408b1d848/screenshot 200 239 ms - 419368
[HTTP] 
[HTTP] --> GET /wd/hub/session/e3d08ab8-5132-48e6-9c45-cc1408b1d848/window/rect
[HTTP] {}
[W3C (e3d08ab8)] Calling AppiumDriver.getWindowRect() with args: ["e3d08ab8-5132-48e6-9c45-cc1408b1d848"]
[XCUITest] Executing command 'getWindowRect'
[WD Proxy] Proxying [GET /window/size] to [GET http://127.0.0.1:8100/session/AD84FE98-182F-4836-8B51-00FD1AC1041A/window/size] with no body
[HTTP] --> GET /wd/hub/session/e3d08ab8-5132-48e6-9c45-cc1408b1d848/timeouts
[HTTP] {}
[W3C (e3d08ab8)] Calling AppiumDriver.getTimeouts() with args: ["e3d08ab8-5132-48e6-9c45-cc1408b1d848"]
[XCUITest] Executing command 'getTimeouts'
[HTTP] --> GET /wd/hub/session/e3d08ab8-5132-48e6-9c45-cc1408b1d848/timeouts
[HTTP] {}
[W3C (e3d08ab8)] Calling AppiumDriver.getTimeouts() with args: ["e3d08ab8-5132-48e6-9c45-cc1408b1d848"]
[XCUITest] Executing command 'getTimeouts'
[WD Proxy] socket hang up
[W3C (e3d08ab8)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
[W3C (e3d08ab8)]     at JWProxy.command (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:274:13)
[W3C (e3d08ab8)]     at runMicrotasks ()
[W3C (e3d08ab8)]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[W3C (e3d08ab8)]     at XCUITestDriver.proxyCommand (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:96:12)
[W3C (e3d08ab8)]     at XCUITestDriver.getWindowSizeNative (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/general.js:78:10)
[W3C (e3d08ab8)]     at XCUITestDriver.getWindowSize (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/general.js:87:12)
[W3C (e3d08ab8)]     at XCUITestDriver.getWindowRect (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/general.js:160:27)
[HTTP] <-- GET /wd/hub/session/e3d08ab8-5132-48e6-9c45-cc1408b1d848/window/rect 500 60350 ms - 1424
[HTTP] 
[W3C (e3d08ab8)] Responding to client with driver.getTimeouts() result: {"command":3600000,"implicit":0}
[HTTP] <-- GET /wd/hub/session/e3d08ab8-5132-48e6-9c45-cc1408b1d848/timeouts 200 58784 ms - 42
[HTTP] 
[W3C (e3d08ab8)] Responding to client with driver.getTimeouts() result: {"command":3600000,"implicit":0}
[HTTP] <-- GET /wd/hub/session/e3d08ab8-5132-48e6-9c45-cc1408b1d848/timeouts 200 18783 ms - 42
[HTTP] 
[HTTP] --> GET /wd/hub/session/e3d08ab8-5132-48e6-9c45-cc1408b1d848/source
[HTTP] {}
[W3C (e3d08ab8)] Calling AppiumDriver.getPageSource() with args: ["e3d08ab8-5132-48e6-9c45-cc1408b1d848"]
[XCUITest] Executing command 'getPageSource'
[WD Proxy] Matched '/source?format=json&scope=AppiumAUT' to command name 'getPageSource'
[WD Proxy] Proxying [GET /source?format=json&scope=AppiumAUT] to [GET http://127.0.0.1:8100/session/AD84FE98-182F-4836-8B51-00FD1AC1041A/source?format=json&scope=AppiumAUT] with no body
[HTTP] --> GET /wd/hub/session/e3d08ab8-5132-48e6-9c45-cc1408b1d848/timeouts
[HTTP] {}
[W3C (e3d08ab8)] Calling AppiumDriver.getTimeouts() with args: ["e3d08ab8-5132-48e6-9c45-cc1408b1d848"]
[XCUITest] Executing command 'getTimeouts'
[iProxy@00008101:8100] Connection was refused to port 8100
[WD Proxy] socket hang up
[W3C (e3d08ab8)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
[W3C (e3d08ab8)]     at JWProxy.command (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:274:13)
[W3C (e3d08ab8)]     at runMicrotasks ()
[W3C (e3d08ab8)]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[W3C (e3d08ab8)]     at XCUITestDriver.proxyCommand (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:96:12)
[W3C (e3d08ab8)]     at XCUITestDriver.mobileGetSource (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/source.js:51:10)
[W3C (e3d08ab8)]     at XCUITestDriver.getPageSource (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/source.js:19:21)
[HTTP] <-- GET /wd/hub/session/e3d08ab8-5132-48e6-9c45-cc1408b1d848/source 500 51 ms - 1233
[HTTP] 
[W3C (e3d08ab8)] Responding to client with driver.getTimeouts() result: {"command":3600000,"implicit":0}
[HTTP] <-- GET /wd/hub/session/e3d08ab8-5132-48e6-9c45-cc1408b1d848/timeouts 304 37 ms - -
[HTTP] 
[HTTP] --> GET /wd/hub/session/e3d08ab8-5132-48e6-9c45-cc1408b1d848/timeouts
[HTTP] {}
[W3C (e3d08ab8)] Calling AppiumDriver.getTimeouts() with args: ["e3d08ab8-5132-48e6-9c45-cc1408b1d848"]
[XCUITest] Executing command 'getTimeouts'
[W3C (e3d08ab8)] Responding to client with driver.getTimeouts() result: {"command":3600000,"implicit":0}
[HTTP] <-- GET /wd/hub/session/e3d08ab8-5132-48e6-9c45-cc1408b1d848/timeouts 304 7 ms - -
[HTTP] 
[HTTP] --> GET /wd/hub/session/e3d08ab8-5132-48e6-9c45-cc1408b1d848/timeouts
[HTTP] {}
[W3C (e3d08ab8)] Calling AppiumDriver.getTimeouts() with args: ["e3d08ab8-5132-48e6-9c45-cc1408b1d848"]
[XCUITest] Executing command 'getTimeouts'
[W3C (e3d08ab8)] Responding to client with driver.getTimeouts() result: {"command":3600000,"implicit":0}
[HTTP] <-- GET /wd/hub/session/e3d08ab8-5132-48e6-9c45-cc1408b1d848/timeouts 304 10 ms - -
[HTTP] 
```

### Expected Behavior

The appium inspector should load the page dom at least how much is visible and should not crash the server

### Minimal Reproducible Example

1. Currently using basic Appium inspector 2023.7.1
2. Connected my device (tried on both simulator and physical device)
3. Started session
4. Navigated to the page with huge dom structure and made a refresh on inspector
5. Appium server gets hanged and crashed

### Environment

- Operating system:
- Appium server version (output of `appium --version`): v1.22.3-4
- Node.js version (output of `node --version`):  v18.17.0
- `npm` version (output of `npm --version`): 9.6.7
- Last component(s) version which did _not_ exhibit the problem: NONE
- Platform and version under test: iOS v16
- Real device or emulator/simulator: Same for both

**Comment by mykola-mokhnach** [comment]
> Have you tried to fetch the page source using vanilla XCTest? If the native approach fails then there is no way WDA would work.

**Comment by mykola-mokhnach** [comment]
Btw, we do not support Appium 1 anymore.

**Comment by bijitbiswas** [comment]
@mykola-mokhnach 
Which version should I use ? Can you help me by providing anything that I can try ?

**Comment by mykola-mokhnach** [comment]
You should switch to Appium2 as described in the readme: https://github.com/appium/appium

Although I am still not sure this could help in your case as it is most likely an XCTest issue and could only be addressed by Apple itself.

**Comment by bijitbiswas** [comment]
Yes I switched from the desktop app to appium 2.0.1
<img width="451" alt="image" src="https://github.com/appium/appium/assets/67964914/cab553a5-dd92-4dcb-a754-aa4e68015bce">

but still the same issue. 
I was asking if there is a way we can control on how much elements to load on the inspector. 
I mean suppose there are 100 XCUIElementTypeCell on actuall DOM but currently only 10 are visible and remaining will be visible only on scroll . Then is there a way to override getPageSource method to stop after suppose 30 secs ?

**Comment by mykola-mokhnach** [comment]
> I was asking if there is a way we can control on how much elements to load on the inspector.

There is no way to control that. You can only control the actual tree depth by providing a custom value to `snapshotMaxDepth` setting

**Comment by bijitbiswas** [comment]
Ok got it. Also can you please confirm is it possible to update the `settings['snapshotMaxDepth']` in between of the test ?

**Comment by mykola-mokhnach** [comment]
yes, this is possible. The whole point of settings is in having a possibility of changing them mid-session

**Comment by bijitbiswas** [comment]
Is it possible to send a syntax of it how to do that 
For example 
```
driver.findElementByXpath("xyz").click()
// code to change snapshotMaxDepth. Can you add the code here ?
driver.findElementByXpath("abc").click()
```

**Comment by mykola-mokhnach** [comment]
Consider using Appium forum to ask questions.

**Comment by bijitbiswas** [comment]
Thank you got the solution https://github.com/appium/java-client/issues/1475

Used `(IOSDriver).setSetting("snapshotMaxDepth", 12)`
Need to use java-client version 7.3.0 or above
We can close this issue
