### ISSUE TITLE
bug: SendKeysToElement cause io.appium.uiautomator2.server frozen in ColorOS 13.1 (Android 13)

### ISSUE THREAD

**Issue by hbc007** [appium/appium#18998]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm encountering a timeout issue when using the sendKey command on Oppo Reno7 and OnePlus 11 devices, both of which are running ColorOS 13.1. This issue is impacting my automated tests. After executing the sendKey command on an element (which is a visible input field), subsequent test cases are timing out, ultimately leading to session termination when the newCommandTimeout is reached. 

* The issue is consistently triggered after the sendKey command, and there's a possibility of encountering same issue during other test operations.
* Notably, the io.appium.uiautomator2.server seems to be indicated as "frozen" in the adb logcat logs.
* I've taken specific actions to address the issue but not work, including:
  * Disabling battery optimization for Appium Settings and io.appium.uiautomator2.server.
  * Granting all permissions to Appium Settings.

### Expected Behavior

Upon using the sendKey command, the test cases should continue to execute without causing subsequent test cases to timeout. The test suite should operate as intended on all devices, including Oppo Reno7 and OnePlus 11.

### Minimal Reproducible Example

l use WebdriverIO + Mocha test framework to run the script
```
it('login', async () => {
    await $("#ks_et_account_id").sendKeys("123456".split(""));
    console.log('just throw timeout error, this line never reached');
});
```

### Environment

- Operating system: Windows 10 22H2
- Appium server version (output of `appium --version`): 2.0.1
- Appium driver(s) and their version(s): appium-uiautomator2-driver@2.29.3
- Node.js version (output of `node --version`): v18.15.0
- `npm` version (output of `npm --version`): 9.6.1
- Real device or emulator/simulator: Oppo Reno7 and OnePlus 11 (both are Color OS 13.1)

#### Appium Logs
```
2023-08-17 10:48:01:889 [HTTP] {"using":"css selector","value":"#ks_et_sms_code"}
2023-08-17 10:48:01:889 [AndroidUiautomator2Driver@fa06 (bbafc22e)] Calling AppiumDriver.findElement() with args: ["css selector","#ks_et_sms_code","bbafc22e-c860-4967-9375-6a22e74fc389"]
2023-08-17 10:48:11:883 [HTTP] <-- POST /session/bbafc22e-c860-4967-9375-6a22e74fc389/element - - ms - -
2023-08-17 10:48:11:883 [HTTP] 
2023-08-17 10:48:11:885 [HTTP] --> POST /session/bbafc22e-c860-4967-9375-6a22e74fc389/element
2023-08-17 10:48:11:885 [HTTP] {"using":"css selector","value":"#ks_et_sms_code"}
2023-08-17 10:48:11:885 [AndroidUiautomator2Driver@fa06 (bbafc22e)] Calling AppiumDriver.findElement() with args: ["css selector","#ks_et_sms_code","bbafc22e-c860-4967-9375-6a22e74fc389"]
2023-08-17 10:48:21:892 [HTTP] --> DELETE /session/bbafc22e-c860-4967-9375-6a22e74fc389
2023-08-17 10:48:21:892 [HTTP] {}
2023-08-17 10:48:21:892 [AndroidUiautomator2Driver@fa06 (bbafc22e)] Calling AppiumDriver.deleteSession() with args: ["bbafc22e-c860-4967-9375-6a22e74fc389"]
2023-08-17 10:48:21:893 [AppiumDriver@6633] Event 'quitSessionRequested' logged at 1692269301893 (18:48:21 GMT+0800 (中国标准时间))
2023-08-17 10:48:21:893 [AppiumDriver@6633] Removing session bbafc22e-c860-4967-9375-6a22e74fc389 from our master session list
2023-08-17 10:48:21:893 [AndroidUiautomator2Driver@fa06 (bbafc22e)] Deleting UiAutomator2 session
2023-08-17 10:48:21:893 [AndroidUiautomator2Driver@fa06 (bbafc22e)] Deleting UiAutomator2 server session
2023-08-17 10:48:21:893 [AndroidUiautomator2Driver@fa06 (bbafc22e)] Matched '/' to command name 'deleteSession'
2023-08-17 10:48:21:894 [AndroidUiautomator2Driver@fa06 (bbafc22e)] Proxying [DELETE /] to [DELETE http://127.0.0.1:20001/session/0adf77f5-37ac-4313-883e-f45832df3d8a] with no body
2023-08-17 10:48:50:106 [HTTP] <-- POST /session/bbafc22e-c860-4967-9375-6a22e74fc389/element - - ms - -
2023-08-17 10:48:50:106 [HTTP] 
2023-08-17 10:48:50:121 [AndroidUiautomator2Driver@fa06 (bbafc22e)] AxiosError: timeout of 240000ms exceeded
2023-08-17 10:48:50:121 [AndroidUiautomator2Driver@fa06 (bbafc22e)]     at RedirectableRequest.handleRequestTimeout (C:\project\autotest-agent\node_modules\axios\lib\adapters\http.js:628:16)
2023-08-17 10:48:50:121 [AndroidUiautomator2Driver@fa06 (bbafc22e)]     at RedirectableRequest.emit (node:events:513:28)
2023-08-17 10:48:50:121 [AndroidUiautomator2Driver@fa06 (bbafc22e)]     at Timeout.<anonymous> (C:\project\autotest-agent\node_modules\follow-redirects\index.js:169:12)
2023-08-17 10:48:50:122 [AndroidUiautomator2Driver@fa06 (bbafc22e)]     at listOnTimeout (node:internal/timers:569:17)
2023-08-17 10:48:50:122 [AndroidUiautomator2Driver@fa06 (bbafc22e)]     at processTimers (node:internal/timers:512:7)
2023-08-17 10:48:50:122 [AndroidUiautomator2Driver@fa06 (bbafc22e)] Valid locator strategies for this request: xpath, id, class name, accessibility id, css selector, -android uiautomator
2023-08-17 10:48:50:123 [AndroidUiautomator2Driver@fa06 (bbafc22e)] Waiting up to 0 ms for condition
2023-08-17 10:48:50:123 [AndroidUiautomator2Driver@fa06 (bbafc22e)] Matched '/element' to command name 'findElement'
2023-08-17 10:48:50:123 [AndroidUiautomator2Driver@fa06 (bbafc22e)] Proxying [POST /element] to [POST http://127.0.0.1:20001/session/0adf77f5-37ac-4313-883e-f45832df3d8a/element] with body: {"strategy":"-android uiautomator","selector":"new UiSelector().resourceId(\"com.jufang.guanwang.mysy:id/ks_et_account_id\")","context":"","multiple":false}
2023-08-17 10:48:50:123 [AppiumDriver@6633] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: timeout of 240000ms exceeded
2023-08-17 10:48:50:123 [AppiumDriver@6633]     at UIA2Proxy.command (C:\project\autotest-agent\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:355:13)
2023-08-17 10:48:50:123 [AppiumDriver@6633]     at runNextTicks (node:internal/process/task_queues:60:5)
2023-08-17 10:48:50:123 [AppiumDriver@6633]     at listOnTimeout (node:internal/timers:538:9)
2023-08-17 10:48:50:123 [AppiumDriver@6633]     at processTimers (node:internal/timers:512:7)
2023-08-17 10:48:50:123 [AppiumDriver@6633]     at AndroidUiautomator2Driver.helpers.doFindElementOrEls (C:\project\autotest-agent\node_modules\appium-uiautomator2-driver\lib\commands\find.js:30:10)
2023-08-17 10:48:50:123 [AppiumDriver@6633]     at doFind (C:\project\autotest-agent\node_modules\appium-uiautomator2-driver\node_modules\appium-android-driver\lib\commands\find.js:36:17)
2023-08-17 10:48:50:124 [AppiumDriver@6633]     at wrappedCondFn (C:\project\autotest-agent\node_modules\@appium\base-driver\lib\basedriver\commands\timeout.ts:137:14)
2023-08-17 10:48:50:124 [AppiumDriver@6633]     at spin (C:\project\autotest-agent\node_modules\asyncbox\lib\asyncbox.js:221:20)
2023-08-17 10:48:50:124 [AppiumDriver@6633]     at waitForCondition (C:\project\autotest-agent\node_modules\asyncbox\lib\asyncbox.js:238:10)
2023-08-17 10:48:50:124 [AppiumDriver@6633]     at AndroidUiautomator2Driver.implicitWaitForCondition (C:\project\autotest-agent\node_modules\@appium\base-driver\lib\basedriver\commands\timeout.ts:139:12)
2023-08-17 10:48:50:124 [AppiumDriver@6633]     at AndroidUiautomator2Driver.findElOrEls (C:\project\autotest-agent\node_modules\appium-uiautomator2-driver\node_modules\appium-android-driver\lib\commands\find.js:60:5)
2023-08-17 10:48:50:124 [AppiumDriver@6633]     at AndroidUiautomator2Driver.findElOrElsWithProcessing (C:\project\autotest-agent\node_modules\@appium\base-driver\lib\basedriver\commands\find.ts:60:12)
2023-08-17 10:48:50:124 [AppiumDriver@6633]     at AndroidUiautomator2Driver.findElement (C:\project\autotest-agent\node_modules\@appium\base-driver\lib\basedriver\commands\find.ts:75:12)
2023-08-17 10:48:56:875 [HTTP] <-- POST /session/bbafc22e-c860-4967-9375-6a22e74fc389/element - - ms - -
```
#### ADB Logcat
```
08-18 15:33:05.343 24035 24082 I appium  : FindElement command
08-18 15:33:05.345 24035 24082 I appium  : method: '-android uiautomator', selector: 'new UiSelector().resourceId("com.jufang.guanwang.mysy:id/ks_et_account_id")'
08-18 15:33:05.345 24035 24082 I appium  : Waiting up to 10000ms for the device to idle
08-18 15:33:05.852 24035 24082 I appium  : AppiumResponse: {"sessionId":"23003c76-8374-4e4d-b5b8-eca25e6b8684","value":{"ELEMENT":"00000000-0000-0035-ffff-ffff000000f1","element-6066-11e4-a52e-4f735466cecf":"00000000-0000-0035-ffff-ffff000000f1"}}
08-18 15:33:05.864 24035 24082 I appium  : channel read: POST /session/23003c76-8374-4e4d-b5b8-eca25e6b8684/element/00000000-0000-0035-ffff-ffff000000f1/click
08-18 15:33:05.866 24035 24082 I appium  : Click command
08-18 15:33:05.928 24035 24082 I appium  : Waiting up to 10000ms for the device to idle
08-18 15:33:05.928 24035 24082 I appium  : AppiumResponse: {"sessionId":"23003c76-8374-4e4d-b5b8-eca25e6b8684","value":null}
08-18 15:33:05.936 24035 24082 I appium  : channel read: POST /session/23003c76-8374-4e4d-b5b8-eca25e6b8684/keys
08-18 15:33:05.936 24035 24082 I appium  : SendKeysToElement command
08-18 15:33:07.014  3313  4855 I OplusHansManager : uid=10336, pkg=io.appium.uiautomator2.server can transition from M to F
08-18 15:33:07.015  3313  4855 I OplusHansManager : uid=10336, pkg=io.appium.uiautomator2.server F enter(), M stay=8
08-18 15:33:07.017  3313  4855 I OplusHansManager : freeze uid: 10336 io.appium.uiautomator2.server pids: [24035] scene: LcdOn
08-18 15:33:07.021  3313  4862 I OplusHansManager : p_BC uid=10336 pkg=io.appium.uiautomator2.server
08-18 15:33:07.023  3313  4862 I OplusBinderProxy: proxyBinder uid: 10336 pkg: io.appium.uiautomator2.server proxy: true calling: OFreezer
```

**Comment by hbc007** [comment]
While altering the implementation of keyboard input might help mitigate the issue caused by sendKey, there remains a slight probability that other operations could still result in the same problem. In my recent attempt, it was triggered by the getText operation.

### Appium
```
2023-08-17 10:48:01:888 [HTTP] --> POST /session/bbafc22e-c860-4967-9375-6a22e74fc389/element
2023-08-17 10:48:01:889 [HTTP] {"using":"css selector","value":"#ks_et_sms_code"}
2023-08-17 10:48:01:889 [AndroidUiautomator2Driver@fa06 (bbafc22e)] Calling AppiumDriver.findElement() with args: ["css selector","#ks_et_sms_code","bbafc22e-c860-4967-9375-6a22e74fc389"]
2023-08-17 10:48:11:883 [HTTP] <-- POST /session/bbafc22e-c860-4967-9375-6a22e74fc389/element - - ms - -
2023-08-17 10:48:11:883 [HTTP] 
2023-08-17 10:48:11:885 [HTTP] --> POST /session/bbafc22e-c860-4967-9375-6a22e74fc389/element
2023-08-17 10:48:11:885 [HTTP] {"using":"css selector","value":"#ks_et_sms_code"}
2023-08-17 10:48:11:885 [AndroidUiautomator2Driver@fa06 (bbafc22e)] Calling AppiumDriver.findElement() with args: ["css selector","#ks_et_sms_code","bbafc22e-c860-4967-9375-6a22e74fc389"]
2023-08-17 10:48:21:892 [HTTP] --> DELETE /session/bbafc22e-c860-4967-9375-6a22e74fc389
2023-08-17 10:48:21:892 [HTTP] {}
2023-08-17 10:48:21:892 [AndroidUiautomator2Driver@fa06 (bbafc22e)] Calling AppiumDriver.deleteSession() with args: ["bbafc22e-c860-4967-9375-6a22e74fc389"]
2023-08-17 10:48:21:893 [AppiumDriver@6633] Event 'quitSessionRequested' logged at 1692269301893 (18:48:21 GMT+0800 (中国标准时间))
2023-08-17 10:48:21:893 [AppiumDriver@6633] Removing session bbafc22e-c860-4967-9375-6a22e74fc389 from our master session list
2023-08-17 10:48:21:893 [AndroidUiautomator2Driver@fa06 (bbafc22e)] Deleting UiAutomator2 session
2023-08-17 10:48:21:893 [AndroidUiautomator2Driver@fa06 (bbafc22e)] Deleting UiAutomator2 server session
2023-08-17 10:48:21:893 [AndroidUiautomator2Driver@fa06 (bbafc22e)] Matched '/' to command name 'deleteSession'
2023-08-17 10:48:21:894 [AndroidUiautomator2Driver@fa06 (bbafc22e)] Proxying [DELETE /] to [DELETE http://127.0.0.1:20001/session/0adf77f5-37ac-4313-883e-f45832df3d8a] with no body
2023-08-17 10:48:50:106 [HTTP] <-- POST /session/bbafc22e-c860-4967-9375-6a22e74fc389/element - - ms - -
2023-08-17 10:48:50:106 [HTTP] 
2023-08-17 10:48:50:121 [AndroidUiautomator2Driver@fa06 (bbafc22e)] AxiosError: timeout of 240000ms exceeded
2023-08-17 10:48:50:121 [AndroidUiautomator2Driver@fa06 (bbafc22e)]     at RedirectableRequest.handleRequestTimeout (C:\project\autotest-agent\node_modules\axios\lib\adapters\http.js:628:16)
2023-08-17 10:48:50:121 [AndroidUiautomator2Driver@fa06 (bbafc22e)]     at RedirectableRequest.emit (node:events:513:28)
2023-08-17 10:48:50:121 [AndroidUiautomator2Driver@fa06 (bbafc22e)]     at Timeout.<anonymous> (C:\project\autotest-agent\node_modules\follow-redirects\index.js:169:12)
2023-08-17 10:48:50:122 [AndroidUiautomator2Driver@fa06 (bbafc22e)]     at listOnTimeout (node:internal/timers:569:17)
2023-08-17 10:48:50:122 [AndroidUiautomator2Driver@fa06 (bbafc22e)]     at processTimers (node:internal/timers:512:7)
2023-08-17 10:48:50:122 [AndroidUiautomator2Driver@fa06 (bbafc22e)] Valid locator strategies for this request: xpath, id, class name, accessibility id, css selector, -android uiautomator
2023-08-17 10:48:50:123 [AndroidUiautomator2Driver@fa06 (bbafc22e)] Waiting up to 0 ms for condition
2023-08-17 10:48:50:123 [AndroidUiautomator2Driver@fa06 (bbafc22e)] Matched '/element' to command name 'findElement'
2023-08-17 10:48:50:123 [AndroidUiautomator2Driver@fa06 (bbafc22e)] Proxying [POST /element] to [POST http://127.0.0.1:20001/session/0adf77f5-37ac-4313-883e-f45832df3d8a/element] with body: {"strategy":"-android uiautomator","selector":"new UiSelector().resourceId(\"com.jufang.guanwang.mysy:id/ks_et_account_id\")","context":"","multiple":false}
2023-08-17 10:48:50:123 [AppiumDriver@6633] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: timeout of 240000ms exceeded
2023-08-17 10:48:50:123 [AppiumDriver@6633]     at UIA2Proxy.command (C:\project\autotest-agent\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:355:13)
2023-08-17 10:48:50:123 [AppiumDriver@6633]     at runNextTicks (node:internal/process/task_queues:60:5)
2023-08-17 10:48:50:123 [AppiumDriver@6633]     at listOnTimeout (node:internal/timers:538:9)
2023-08-17 10:48:50:123 [AppiumDriver@6633]     at processTimers (node:internal/timers:512:7)
2023-08-17 10:48:50:123 [AppiumDriver@6633]     at AndroidUiautomator2Driver.helpers.doFindElementOrEls (C:\project\autotest-agent\node_modules\appium-uiautomator2-driver\lib\commands\find.js:30:10)
2023-08-17 10:48:50:123 [AppiumDriver@6633]     at doFind (C:\project\autotest-agent\node_modules\appium-uiautomator2-driver\node_modules\appium-android-driver\lib\commands\find.js:36:17)
2023-08-17 10:48:50:124 [AppiumDriver@6633]     at wrappedCondFn (C:\project\autotest-agent\node_modules\@appium\base-driver\lib\basedriver\commands\timeout.ts:137:14)
2023-08-17 10:48:50:124 [AppiumDriver@6633]     at spin (C:\project\autotest-agent\node_modules\asyncbox\lib\asyncbox.js:221:20)
2023-08-17 10:48:50:124 [AppiumDriver@6633]     at waitForCondition (C:\project\autotest-agent\node_modules\asyncbox\lib\asyncbox.js:238:10)
2023-08-17 10:48:50:124 [AppiumDriver@6633]     at AndroidUiautomator2Driver.implicitWaitForCondition (C:\project\autotest-agent\node_modules\@appium\base-driver\lib\basedriver\commands\timeout.ts:139:12)
2023-08-17 10:48:50:124 [AppiumDriver@6633]     at AndroidUiautomator2Driver.findElOrEls (C:\project\autotest-agent\node_modules\appium-uiautomator2-driver\node_modules\appium-android-driver\lib\commands\find.js:60:5)
2023-08-17 10:48:50:124 [AppiumDriver@6633]     at AndroidUiautomator2Driver.findElOrElsWithProcessing (C:\project\autotest-agent\node_modules\@appium\base-driver\lib\basedriver\commands\find.ts:60:12)
2023-08-17 10:48:50:124 [AppiumDriver@6633]     at AndroidUiautomator2Driver.findElement (C:\project\autotest-agent\node_modules\@appium\base-driver\lib\basedriver\commands\find.ts:75:12)
2023-08-17 10:48:56:875 [HTTP] <-- POST /session/bbafc22e-c860-4967-9375-6a22e74fc389/element - - ms - -
```
### ADB Logcat
```
8-18 18:09:34.630  5627  6007 I appium  : channel read: POST /session/f2c0da2a-1f72-427d-a651-56e17d827f41/element/00000000-0000-0058-ffff-ffff000000b7/click
08-18 18:09:34.630  5627  6007 I appium  : Click command
08-18 18:09:34.667  5627  6007 I appium  : Waiting up to 10000ms for the device to idle
08-18 18:09:34.668  5627  6007 I appium  : AppiumResponse: {"sessionId":"f2c0da2a-1f72-427d-a651-56e17d827f41","value":null}
08-18 18:09:34.677  5627  6007 I appium  : channel read: POST /session/f2c0da2a-1f72-427d-a651-56e17d827f41/element
08-18 18:09:34.677  5627  6007 I appium  : FindElement command
08-18 18:09:34.678  5627  6007 I appium  : method: '-android uiautomator', selector: 'new UiSelector().resourceId("com.jufang.guanwang.mysy:id/ks_title")'
08-18 18:09:34.678  5627  6007 I appium  : Waiting up to 10000ms for the device to idle
08-18 18:09:34.723  5627  6007 I appium  : AppiumResponse: {"sessionId":"f2c0da2a-1f72-427d-a651-56e17d827f41","value":{"ELEMENT":"00000000-0000-0058-ffff-ffff0000009b","element-6066-11e4-a52e-4f735466cecf":"00000000-0000-0058-ffff-ffff0000009b"}}
08-18 18:09:34.731  5627  6007 I appium  : channel read: GET /session/f2c0da2a-1f72-427d-a651-56e17d827f41/element/00000000-0000-0058-ffff-ffff0000009b/text
08-18 18:09:34.731  5627  6007 I appium  : GetText command
08-18 18:09:35.202  3313  4855 I OplusHansManager : uid=10336, pkg=io.appium.uiautomator2.server can transition from M to F
08-18 18:09:35.202  3313  4855 I OplusHansManager : uid=10336, pkg=io.appium.uiautomator2.server F enter(), M stay=1
08-18 18:09:35.203  3313  4855 I OplusHansManager : freeze uid: 10336 io.appium.uiautomator2.server pids: [5627] scene: LcdOn
08-18 18:09:35.204  3313  4862 I OplusHansManager : p_BC uid=10336 pkg=io.appium.uiautomator2.server
08-18 18:09:35.204  3313  4862 I OplusBinderProxy: proxyBinder uid: 10336 pkg: io.appium.uiautomator2.server proxy: true calling: OFreezer
08-18 18:10:26.702  4904  4904 I ModemAciService: UTF LO: OplusAppTrafficInfo{ date=08-18 18:10:26.698 trafficC={com.jufang.guanwang.mysy=55798, com.azure.authenticator=129104, com.unionpay=28489, com.tencent.mm=1009874, com.xunmeng.pinduoduo=3619, com.heytap.cloud=38104, com.oplus.location=61943, com.coloros.weather.service=10235, com.baidu.tieba_mini=103014, com.oplus.pantanal.ums=170399, com.android.bankabc=881242, com.heytap.market=102969, com.luckyzyx.luckytool=393, com.tencent.tim=62452, com.google.uid.shared=19698, iot.clz.me=42031, com.heytap.osec.kms=8562, com.heytap.health=9952, com.baidu.netdisk=1455543, io.appium.uiautomator2.server=102486, com.coloros.weather2=24941, com.alibaba.android.rimet=2682, com.baidu.input=72620}}
08-18 18:11:41.098  7511  8204 E Battery : AppStats: Uid = 10366; pkgName = io.appium.settings; WifiRxBytes = 315433 Bytes; WifiTxBytes = 99596 Bytes; WifiRxPackets = 609 ; WifiTxPackets = 508 ; WiFiScanTimeMs = 0 ; WiFiBatchScanTimeMs = 0
08-18 18:11:41.099  7511  8204 E Battery : AppStats: Uid = 10366; pkgName = io.appium.settings; WifiRxPacketsPower = 0.14146563410758972 mAh; WifiTxPacketsPower = 0.11800416558980942 mAh; WifiScanPower = 0.0 mAh; WifiBatchScanPower = 0.0 mAh; WiFiTotalPower = 0.25946980714797974 mAh
08-18 18:11:41.129  7511  8204 E Battery : AppStats: Uid = 10336; pkgName = io.appium.uiautomator2.server; WifiRxBytes = 210598 Bytes; WifiTxBytes = 22261 Bytes; WifiRxPackets = 227 ; WifiTxPackets = 195 ; WiFiScanTimeMs = 0 ; WiFiBatchScanTimeMs = 0
08-18 18:11:41.129  7511  8204 E Battery : AppStats: Uid = 10336; pkgName = io.appium.uiautomator2.server; WifiRxPacketsPower = 0.05273021012544632 mAh; WifiTxPacketsPower = 0.04529687389731407 mAh; WifiScanPower = 0.0 mAh; WifiBatchScanPower = 0.0 mAh; WiFiTotalPower = 0.09802708774805069 mAh
```

**Comment by mykola-mokhnach** [comment]
I believe the original cause is the same. Consider reporting the issue to Google.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
