### ISSUE TITLE
Too many screenshot attempts with timeout

### ISSUE THREAD

**Issue by pkboom** [appium/appium#19060]
Sometimes screenshot times out and my app keeps trying to take a screenshot too many times. It takes almost 3 minutes until it stops doing it and restarts a new session. I don’t mind it timing out. But I don’t understand why it takes about 3 minutes before giving up? Please help me with this.

Thanks.

```
capabilities = {
  platformName: 'Android',
  'appium:options': {
    automationName: 'UiAutomator2',
    noReset: true,
    uiautomator2ServerReadTimeout: 10000,
    adbExecTimeout: 10000,
  },
}
```

Here's the log:
2023-08-25 11:07:43:493 [HTTP] --> GET /session/73dc6a5a-b57c-492b-b80b-a7d2ab37eebd/screenshot
2023-08-25 11:07:43:493 [HTTP] {}
2023-08-25 11:07:43:494 [AndroidUiautomator2Driver@d696 (73dc6a5a)] Calling AppiumDriver.getScreenshot() with args: ["73dc6a5a-b57c-492b-b80b-a7d2ab37eebd"]
2023-08-25 11:07:43:494 [AndroidUiautomator2Driver@d696 (73dc6a5a)] Matched '/screenshot' to command name 'getScreenshot'
2023-08-25 11:07:43:494 [AndroidUiautomator2Driver@d696 (73dc6a5a)] Proxying [GET /screenshot] to [GET http://127.0.0.1:8200/session/056d59ea-e211-4dc4-9bc5-1c460eae2e7a/screenshot] with no body
2023-08-25 11:07:53:519 [AndroidUiautomator2Driver@d696 (73dc6a5a)] AxiosError: timeout of 10000ms exceeded
2023-08-25 11:07:53:519 [AndroidUiautomator2Driver@d696 (73dc6a5a)]     at RedirectableRequest.handleRequestTimeout (/opt/homebrew/lib/node_modules/appium/node_modules/axios/lib/adapters/http.js:628:16)
2023-08-25 11:07:53:519 [AndroidUiautomator2Driver@d696 (73dc6a5a)]     at RedirectableRequest.emit (node:events:512:28)
2023-08-25 11:07:53:519 [AndroidUiautomator2Driver@d696 (73dc6a5a)]     at Timeout.<anonymous> (/opt/homebrew/lib/node_modules/appium/node_modules/follow-redirects/index.js:169:12)
2023-08-25 11:07:53:519 [AndroidUiautomator2Driver@d696 (73dc6a5a)]     at listOnTimeout (node:internal/timers:573:17)
2023-08-25 11:07:53:519 [AndroidUiautomator2Driver@d696 (73dc6a5a)]     at processTimers (node:internal/timers:514:7)
2023-08-25 11:07:53:524 [AndroidUiautomator2Driver@d696 (73dc6a5a)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: timeout of 10000ms exceeded
2023-08-25 11:07:53:524 [AndroidUiautomator2Driver@d696 (73dc6a5a)]     at UIA2Proxy.command (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:355:13)
2023-08-25 11:07:53:524 [AndroidUiautomator2Driver@d696 (73dc6a5a)]     at runNextTicks (node:internal/process/task_queues:60:5)
2023-08-25 11:07:53:524 [AndroidUiautomator2Driver@d696 (73dc6a5a)]     at listOnTimeout (node:internal/timers:540:9)
2023-08-25 11:07:53:524 [AndroidUiautomator2Driver@d696 (73dc6a5a)]     at processTimers (node:internal/timers:514:7)
2023-08-25 11:07:53:524 [AndroidUiautomator2Driver@d696 (73dc6a5a)]     at AndroidUiautomator2Driver.commands.getScreenshot (/Users/rendering/.appium/node_modules/appium-uiautomator2-driver/lib/commands/screenshot.js:18:10)
2023-08-25 11:07:53:525 [HTTP] <-- GET /session/73dc6a5a-b57c-492b-b80b-a7d2ab37eebd/screenshot 500 10032 ms - 877
2023-08-25 11:07:53:525 [HTTP] 
...
... **This screenshot request repeats 15times. **
...
2023-08-25 11:10:52:249 [HTTP] 
2023-08-25 11:11:23:245 [Instrumentation] The process has exited with code 0
2023-08-25 11:11:23:245 [Logcat] Logcat terminated with code 0, signal null
2023-08-25 11:11:52:495 [Appium] Received SIGINT - shutting down
2023-08-25 11:11:52:499 [AppiumDriver@4da7] Cleaning up 1 active session
2023-08-25 11:11:52:500 [AppiumDriver@4da7] Ending session, cause was 'The process has received SIGINT signal'
2023-08-25 11:11:52:500 [AppiumDriver@4da7] Removing session '73dc6a5a-b57c-492b-b80b-a7d2ab37eebd' from our master session list
2023-08-25 11:11:52:501 [AndroidUiautomator2Driver@d696 (73dc6a5a)] Deleting UiAutomator2 session
2023-08-25 11:11:52:502 [AndroidUiautomator2Driver@d696 (73dc6a5a)] Deleting UiAutomator2 server session
2023-08-25 11:11:52:503 [AndroidUiautomator2Driver@d696 (73dc6a5a)] Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: 'DELETE /' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
2023-08-25 11:11:52:505 [ADB] Running '/Users/rendering/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys activity services io.appium.settings/.recorder.RecorderService'
2023-08-25 11:11:52:506 [Logcat] Stopping logcat capture
2023-08-25 11:11:52:507 [Logcat] Logcat already stopped
2023-08-25 11:11:52:508 [ADB] Removing forwarded port socket connection: 8200 
2023-08-25 11:11:52:508 [ADB] Running '/Users/rendering/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward --remove tcp:8200'
2023-08-25 11:11:52:522 [AndroidUiautomator2Driver@d696 (73dc6a5a)] Unable to remove system port forward: Error executing adbExec. Original error: 'Command '/Users/rendering/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward --remove tcp\:8200' exited with code 1'; Command output: adb: error: listener 'tcp:8200' not found
2023-08-25 11:11:52:522 [AndroidUiautomator2Driver@d696 (73dc6a5a)] 
2023-08-25 11:11:52:522 [AndroidUiautomator2Driver@d696 (73dc6a5a)] Restoring hidden api policy to the device default configuration
2023-08-25 11:11:52:522 [ADB] Running '/Users/rendering/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy''
2023-08-25 11:11:52:971 [HTTP] Waiting until the server is closed
2023-08-25 11:11:52:972 [HTTP] Received server close event

**Comment by mykola-mokhnach** [comment]
I also don't know. This is something you need to clear to for the client library being used.

Closed as third party issue.
