### ISSUE TITLE
bug: failed to parse SMS messages on specific devices

### ISSUE THREAD

**Issue by hbc007** [appium/appium#19141]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On specific devices, the adb command output string is incorrectly truncated, resulting in the failure of the `mobile: listSms` to accurately retrieve SMS data.

### Expected Behavior

The SMS data string can be processed correctly.

### Minimal Reproducible Example

On some devices, the result returned by the smsReader Intent includes an additional "extras" field at the end, such as `extras: Bundle[mParcelledData.dataSize=52]`.
```bash
$ adb shell am broadcast -n io.appium.settings/.receivers.SmsReader -a io.appium.settings.sms.read
Broadcasting: Intent { act=io.appium.settings.sms.read flg=0x400000 cmp=io.appium.settings/.receivers.SmsReader
 }
Broadcast completed: result=-1, data="{"items":{"id":"1","address":"xxxxxx","person":null,"date":"xxxxxxx","read":"0","status":"-1","type":"1","subject":null,"body":"xxxxx","serviceCenter":null}],"total":1}", extras: Bundle[mParcelledData.dataSize=52]
```
`helper->parseJsonData` function is unable to handle such strings correctly, ultimately leading to a failure in `mobile: listSms`.

```log
2023-09-11 08:53:33:294 [HTTP] {"script":"mobile: listSms","args":[]}
2023-09-11 08:53:33:294 [AndroidUiautomator2Driver@ef9f (90d6c794)] Calling AppiumDriver.execute() with args: ["mobile: listSms",[],"90d6c794-a27e-43ad-a95e-cffea10d527c"]
2023-09-11 08:53:33:294 [AndroidUiautomator2Driver@ef9f (90d6c794)] Executing native command 'mobile: listSms'
2023-09-11 08:53:33:295 [ADB] Retrieving the recent SMS messages
2023-09-11 08:53:33:295 [ADB] Getting IDs of all 'io.appium.settings' processes
2023-09-11 08:53:33:295 [ADB] Running 'D:\ProgramFiles\AndroidSDK\platform-tools\adb.exe -P 5037 -s 0123456789ABCDEF shell pgrep -f \(\[\[:blank:\]\]\|\^\)io\.appium\.settings\(\[\[:blank:\]\]\|\$\)'
2023-09-11 08:53:33:361 [ADB] Running 'D:\ProgramFiles\AndroidSDK\platform-tools\adb.exe -P 5037 -s 0123456789ABCDEF shell am broadcast -n io.appium.settings/.receivers.SmsReader -a io.appium.settings.sms.read'
2023-09-11 08:53:33:462 [ADB] {"items":[{"id":"1","address":"xxxxx","person":null,"date":"xxxx","read":"0","status":"-1","type":"1","subject":null,"body":"xxxxx","serviceCenter":null}],"total":1}", extras: Bundle[mParcelledData.dataSize=52]
2023-09-11 08:53:33:463 [AndroidUiautomator2Driver@ef9f (90d6c794)] Encountered internal error running command: Error: Cannot parse SMS list from the resulting data string. Check the server log for more details
2023-09-11 08:53:33:463 [AndroidUiautomator2Driver@ef9f (90d6c794)]     at parseJsonData (C:\project\autotest-agent\node_modules\appium-uiautomator2-driver\node_modules\appium-adb\lib\helpers.js:883:11)
2023-09-11 08:53:33:463 [AndroidUiautomator2Driver@ef9f (90d6c794)]     at ADB.getSmsList (C:\project\autotest-agent\node_modules\appium-uiautomator2-driver\node_modules\appium-adb\lib\tools\settings-client-commands.js:618:23)
2023-09-11 08:53:33:463 [AndroidUiautomator2Driver@ef9f (90d6c794)]     at AndroidUiautomator2Driver.mobileListSms (C:\project\autotest-agent\node_modules\appium-uiautomator2-driver\node_modules\appium-android-driver\lib\commands\general.js:319:10)
2023-09-11 08:53:33:463 [AndroidUiautomator2Driver@ef9f (90d6c794)]     at AndroidUiautomator2Driver.extensions.executeMobile (C:\project\autotest-agent\node_modules\appium-uiautomator2-driver\lib\commands\general.js:178:10)
2023-09-11 08:53:33:463 [AndroidUiautomator2Driver@ef9f (90d6c794)]     at AndroidUiautomator2Driver.execute (C:\project\autotest-agent\node_modules\appium-uiautomator2-driver\node_modules\appium-android-driver\lib\commands\execute.js:10:12)
2023-09-11 08:53:33:464 [HTTP] <-- POST /session/90d6c794-a27e-43ad-a95e-cffea10d527c/execute/sync 500 170 ms - 680
```

### Environment

- Appium server version (output of `appium --version`): 2.1.2
- Appium driver(s) and their version(s): appium-uiautomator2-driver@2.29.5

**Comment by mykola-mokhnach** [comment]
This will be fixed as soon as the above fix is published in the driver.
For now you could try to apply the above patch locally as a possible workaround.

**Comment by mykola-mokhnach** [comment]
The patch has been published
