### ISSUE TITLE
((AppiumDriver)driver).getScreenshotAs() closing the socket (xcode 15.0)

### ISSUE THREAD

**Issue by Jiyvn** [appium/appium#19178]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Testing code
```java
((AppiumDriver) driver).getScreenshotAs(OutputType.BYTES);
```

Error
socket hang up
> org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
Build info: version: '4.9.1', revision: 'eb2032df7f'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '13.4.1', java.version: '1.8.0_302'
Driver info: io.appium.java_client.ios.IOSDriver
Command: [f29fbf99-1957-49b5-a69f-5f2085fd2499, screenshot {}]
Capabilities {appium:app: /Users/viu_qaauto_mac_studi..., appium:autoGrantPermissions: true, appium:automationName: XCUITest, appium:bundleID: com.viu.phone, appium:chromeOptions: {w3c: true}, appium:databaseEnabled: false, appium:deviceName: iphone_XR, appium:fullContextList: true, appium:javascriptEnabled: true, appium:language: en, appium:locationContextEnabled: false, appium:mjpegServerPort: 9100, appium:networkConnectionEnabled: false, appium:newCommandTimeout: 2400, appium:noReset: false, appium:platformVersion: 14.4, appium:takesScreenshot: true, appium:udid: 00008020-000248E602D8002E, appium:wdaLocalPort: 10102, appium:webStorageEnabled: false, appium:xcodeOrgId: xxxxxxxx, appium:xcodeSigningId: iPhone Developer, platformName: IOS}
Session ID: f29fbf99-1957-49b5-a69f-5f2085fd2499
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
    at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
    at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
    at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:193)
    at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:250)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:598)
    at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:313)
    at org.openqa.selenium.remote.RemoteWebDriver.getScreenshotAs(RemoteWebDriver.java:318)
    at io.appium.java_client.AppiumDriver.getScreenshotAs(AppiumDriver.java:322)

### Expected Behavior

able to capture fullscreen with ((AppiumDriver) driver).getScreenshotAs(OutputType.BYTES);

### Minimal Reproducible Example

provided above

### Environment

- Operating system: MacOS 13.5 (m2)
- Appium server version (output of `appium --version`): 2.1.3 
- Appium driver(s) and their version(s): xcuitest 5.2.1
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`): v20.5.0
- `npm` version (output of `npm --version`): v9.8.0
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: 
- Real device: iPhoneXR 14.4
- Xcode: 15.0

### Further Information

[appium_screenshot_socket_hang_up.log](https://github.com/appium/appium/files/12671602/appium_screenshot_socket_hang_up.log)
> 2023-09-20 17:17:03:268 - [38;5;0m[HTTP][0m [37m-->[39m [37mGET[39m [37m/session/694b61dc-d80f-45af-b415-f1e3381bdf06/screenshot[39m
2023-09-20 17:17:03:268 - [38;5;0m[HTTP][0m [90m{}[39m
2023-09-20 17:17:03:269 - [debug] [38;5;32m[XCUITestDriver@0b1b (694b61dc)][0m Calling AppiumDriver.getScreenshot() with args: ["694b61dc-d80f-45af-b415-f1e3381bdf06"]
2023-09-20 17:17:03:269 - [debug] [38;5;32m[XCUITestDriver@0b1b (694b61dc)][0m Executing command 'getScreenshot'
2023-09-20 17:17:03:269 - [debug] [38;5;32m[XCUITestDriver@0b1b (694b61dc)][0m Taking screenshot with WDA
2023-09-20 17:17:03:270 - [debug] [38;5;32m[XCUITestDriver@0b1b (694b61dc)][0m Matched '/screenshot' to command name 'getScreenshot'
2023-09-20 17:17:03:270 - [debug] [38;5;32m[XCUITestDriver@0b1b (694b61dc)][0m Proxying [GET /screenshot] to [GET http://127.0.0.1:4728/session/638521F3-11B2-4E81-966D-97F97A78CB92/screenshot] with no body
2023-09-20 17:17:03:319 - [38;5;32m[XCUITestDriver@0b1b (694b61dc)][0m socket hang up
2023-09-20 17:17:03:319 - [38;5;32m[XCUITestDriver@0b1b (694b61dc)][0m Error getting screenshot: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
2023-09-20 17:17:03:319 - [debug] [38;5;32m[XCUITestDriver@0b1b (694b61dc)][0m Taking screenshot with WDA
2023-09-20 17:17:03:320 - [debug] [38;5;32m[XCUITestDriver@0b1b (694b61dc)][0m Matched '/screenshot' to command name 'getScreenshot'
2023-09-20 17:17:03:321 - [debug] [38;5;32m[XCUITestDriver@0b1b (694b61dc)][0m Proxying [GET /screenshot] to [GET http://127.0.0.1:4728/session/638521F3-11B2-4E81-966D-97F97A78CB92/screenshot] with no body
2023-09-20 17:17:03:330 - [debug] [38;5;128m[iProxy@00008020:4728][0m Connection was refused to port 4728
2023-09-20 17:17:03:330 - [38;5;32m[XCUITestDriver@0b1b (694b61dc)][0m socket hang up
2023-09-20 17:17:04:332 - [debug] [38;5;32m[XCUITestDriver@0b1b (694b61dc)][0m Taking screenshot with WDA
2023-09-20 17:17:04:332 - [debug] [38;5;32m[XCUITestDriver@0b1b (694b61dc)][0m Matched '/screenshot' to command name 'getScreenshot'
2023-09-20 17:17:04:332 - [debug] [38;5;32m[XCUITestDriver@0b1b (694b61dc)][0m Proxying [GET /screenshot] to [GET http://127.0.0.1:4728/session/638521F3-11B2-4E81-966D-97F97A78CB92/screenshot] with no body
2023-09-20 17:17:04:336 - [debug] [38;5;128m[iProxy@00008020:4728][0m Connection was refused to port 4728
2023-09-20 17:17:04:337 - [38;5;32m[XCUITestDriver@0b1b (694b61dc)][0m socket hang up
2023-09-20 17:17:04:340 - [debug] [38;5;32m[XCUITestDriver@0b1b (694b61dc)][0m Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
2023-09-20 17:17:04:341 - [debug] [38;5;32m[XCUITestDriver@0b1b (694b61dc)][0m     at JWProxy.command (/Users/viu_qaauto_mac_studio/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:355:13)
2023-09-20 17:17:04:341 - [debug] [38;5;32m[XCUITestDriver@0b1b (694b61dc)][0m     at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-09-20 17:17:04:341 - [debug] [38;5;32m[XCUITestDriver@0b1b (694b61dc)][0m     at XCUITestDriver.proxyCommand (/Users/viu_qaauto_mac_studio/.appium/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:112:35)
2023-09-20 17:17:04:341 - [debug] [38;5;32m[XCUITestDriver@0b1b (694b61dc)][0m     at getScreenshotFromWDA (/Users/viu_qaauto_mac_studio/.appium/node_modules/appium-xcuitest-driver/lib/commands/screenshots.js:12:20)
2023-09-20 17:17:04:341 - [debug] [38;5;32m[XCUITestDriver@0b1b (694b61dc)][0m     at wrapped (/Users/viu_qaauto_mac_studio/.appium/node_modules/appium-xcuitest-driver/node_modules/asyncbox/lib/asyncbox.js:95:13)
2023-09-20 17:17:04:341 - [debug] [38;5;32m[XCUITestDriver@0b1b (694b61dc)][0m     at retry (/Users/viu_qaauto_mac_studio/.appium/node_modules/appium-xcuitest-driver/node_modules/asyncbox/lib/asyncbox.js:68:13)
2023-09-20 17:17:04:341 - [debug] [38;5;32m[XCUITestDriver@0b1b (694b61dc)][0m     at retryInterval (/Users/viu_qaauto_mac_studio/.appium/node_modules/appium-xcuitest-driver/node_modules/asyncbox/lib/asyncbox.js:105:10)
2023-09-20 17:17:04:341 - [debug] [38;5;32m[XCUITestDriver@0b1b (694b61dc)][0m     at XCUITestDriver.getScreenshot (/Users/viu_qaauto_mac_studio/.appium/node_modules/appium-xcuitest-driver/lib/commands/screenshots.js:46:12)
2023-09-20 17:17:04:341 - [38;5;0m[HTTP][0m [37m<-- GET /session/694b61dc-d80f-45af-b415-f1e3381bdf06/screenshot [39m[31m500[39m [90m1073 ms - 1479[39m
2023-09-20 17:17:04:341 - [38;5;0m[HTTP][0m [90m[39m

related issue:
https://github.com/appium/appium/issues/17596
https://github.com/appium/appium/issues/16467
https://github.com/appium/appium/issues/16604
https://github.com/appium/appium/issues/18749

**Comment by mykola-mokhnach** [comment]
This is expected. The recent WDA only supports iOS 15 and later.
Consider using an older version of xcuitest driver to with with iOS 14.

**Comment by Jiyvn** [comment]
@mykola-mokhnach can you suggest the xcuitest version? as I can't find the related release note https://github.com/appium/appium-xcuitest-driver/releases

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium-xcuitest-driver/blob/master/docs/setup.md#xcode-version-support

Xcode versions could be usually matched to real device versions as `DeviceMajorVersion` = `XcodeMajorVersion` + 2
