### ISSUE TITLE
bug: [ADB] Got an unexpected error while fetching connected devices list: Unexpected output while trying to get devices:

### ISSUE THREAD

**Issue by ljppttfn** [appium/appium#19213]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Appium Inspector start session，
the appium server throw exception below：

```
C:\Users\User>appium
[Appium] Welcome to Appium v2.1.3
[Appium] Attempting to load driver uiautomator2...
[debug] [Appium] Requiring driver at C:\Users\User\.appium\node_modules\appium-uiautomator2-driver
[Appium] Appium REST http interface listener started on http://0.0.0.0:4723
[Appium] You can provide the following URL in your client code to connect to this server:
[Appium]        http://127.0.0.1:4723/ (only accessible from the same host)
[Appium] Available drivers:
[Appium]   - uiautomator2@2.29.10 (automationName 'UiAutomator2')
[Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.
[HTTP] --> POST /session
[HTTP] {"capabilities":{"alwaysMatch":{"platformName":"Android","appium:platformVersion":"12","appium:deviceName":"127.0.0.1：7555","appium:appPackage":"cn.Userlife.MobileAgent.dev","appium:appActivity":"cn.Userlife.MobileAgent.HomeActivity","appium:noReset":true,"appium:automationName":"UiAutomator2","appium:ensureWebviewsHavePages":true,"appium:nativeWebScreenshot":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]},"desiredCapabilities":{"platformName":"Android","appium:platformVersion":"12","appium:deviceName":"127.0.0.1：7555","appium:appPackage":"cn.Userlife.MobileAgent.dev","appium:appActivity":"cn.Userlife.MobileAgent.HomeActivity","appium:noReset":true,"appium:automationName":"UiAutomator2","appium:ensureWebviewsHavePages":true,"appium:nativeWebScreenshot":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true}}
[debug] [AppiumDriver@5193] Calling AppiumDriver.createSession() with args: [{"platformName":"Android","appium:platformVersion":"12","appium:deviceName":"127.0.0.1：7555","appium:appPackage":"cn.Userlife.MobileAgent.dev","appium:appActivity":"cn.Userlife.MobileAgent.HomeActivity","appium:noReset":true,"appium:automationName":"UiAutomator2","appium:ensureWebviewsHavePages":true,"appium:nativeWebScreenshot":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},null,{"alwaysMatch":{"platformName":"Android","appium:platformVersion":"12","appium:deviceName":"127.0.0.1：7555","appium:appPackage":"cn.Userlife.MobileAgent.dev","appium:appActivity":"cn.Userlife.MobileAgent.HomeActivity","appium:noReset":true,"appium:automationName":"UiAutomator2","appium:ensureWebviewsHavePages":true,"appium:nativeWebScreenshot":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]}]
[debug] [AppiumDriver@5193] Event 'newSessionRequested' logged at 1695784619981 (11:16:59 GMT+0800 (中国标准时间))
[Appium] Attempting to find matching driver for automationName 'UiAutomator2' and platformName 'Android'
[Appium] The 'uiautomator2' driver was installed and matched caps.
[Appium] Will require it at C:\Users\User\.appium\node_modules\appium-uiautomator2-driver
[debug] [Appium] Requiring driver at C:\Users\User\.appium\node_modules\appium-uiautomator2-driver
[AppiumDriver@5193] Appium v2.1.3 creating new AndroidUiautomator2Driver (v2.29.10) session
[AppiumDriver@5193] Checking BaseDriver versions for Appium and AndroidUiautomator2Driver
[AppiumDriver@5193] Appium's BaseDriver version is 9.3.20
[AppiumDriver@5193] AndroidUiautomator2Driver's BaseDriver version is 9.3.20
[debug] [AndroidUiautomator2Driver@2eac] Creating session with W3C capabilities: {
[debug] [AndroidUiautomator2Driver@2eac]   "alwaysMatch": {
[debug] [AndroidUiautomator2Driver@2eac]     "platformName": "Android",
[debug] [AndroidUiautomator2Driver@2eac]     "appium:platformVersion": "12",
[debug] [AndroidUiautomator2Driver@2eac]     "appium:deviceName": "127.0.0.1：7555",
[debug] [AndroidUiautomator2Driver@2eac]     "appium:appPackage": "cn.Userlife.MobileAgent.dev",
[debug] [AndroidUiautomator2Driver@2eac]     "appium:appActivity": "cn.Userlife.MobileAgent.HomeActivity",
[debug] [AndroidUiautomator2Driver@2eac]     "appium:noReset": true,
[debug] [AndroidUiautomator2Driver@2eac]     "appium:automationName": "UiAutomator2",
[debug] [AndroidUiautomator2Driver@2eac]     "appium:ensureWebviewsHavePages": true,
[debug] [AndroidUiautomator2Driver@2eac]     "appium:nativeWebScreenshot": true,
[debug] [AndroidUiautomator2Driver@2eac]     "appium:newCommandTimeout": 3600,
[debug] [AndroidUiautomator2Driver@2eac]     "appium:connectHardwareKeyboard": true
[debug] [AndroidUiautomator2Driver@2eac]   },
[debug] [AndroidUiautomator2Driver@2eac]   "firstMatch": [
[debug] [AndroidUiautomator2Driver@2eac]     {}
[debug] [AndroidUiautomator2Driver@2eac]   ]
[debug] [AndroidUiautomator2Driver@2eac] }
[AndroidUiautomator2Driver@2eac] The following capabilities were provided, but are not recognized by Appium:
[AndroidUiautomator2Driver@2eac]   deviceName
[AndroidUiautomator2Driver@2eac]   connectHardwareKeyboard
[AndroidUiautomator2Driver@2eac (f3314d03)] Session created with session id: f3314d03-8773-44d9-aaea-9cf66065eed6
[AndroidUiautomator2Driver@2eac (f3314d03)] Starting 'cn.Userlife.MobileAgent.dev' directly on the device
[ADB] Found 1 'build-tools' folders under 'D:\libs\android_sdk' (newest first):
[ADB]     D:\libs\android_sdk\build-tools\33.0.2
[ADB] Using 'adb.exe' from 'D:\libs\android_sdk\platform-tools\adb.exe'
[debug] [ADB] Running 'D:\libs\android_sdk\platform-tools\adb.exe -P 5037 start-server'
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find connected Android devices
[debug] [ADB] Getting connected devices
[debug] [ADB] Error: Unexpected output while trying to get devices:
[debug] [ADB]     at ADB.getConnectedDevices (C:\Users\User\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-adb\lib\tools\system-calls.js:251:11)
[debug] [ADB]     at waitMs (C:\Users\User\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-adb\lib\tools\system-calls.js:299:19)
[debug] [ADB]     at spin (C:\Users\User\.appium\node_modules\appium-uiautomator2-driver\node_modules\asyncbox
```

Run `adb devices -l`，shows below:
```
PS C:\Users\XX> adb devices -l
List of devices attached
127.0.0.1:7555         device product:BAL-AL80 model:BAL_AL80 device:BAL-AL80 transport_id:1
```

The same devices run success on another Windows,
All the Appium Server\Appium Inspector\jdk\android-sdk version are same.

### Expected Behavior

Run success

### Minimal Reproducible Example

Start Session by Appium Inspector.

Connect to Appium Server which started by cmd。

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

```
[Appium] Welcome to Appium v2.1.3
[Appium] Attempting to load driver uiautomator2...
[debug] [Appium] Requiring driver at C:\Users\PICC\.appium\node_modules\appium-uiautomator2-driver
[Appium] Appium REST http interface listener started on http://0.0.0.0:4723
[Appium] You can provide the following URL in your client code to connect to this server:
[Appium]        http://127.0.0.1:4723/ (only accessible from the same host)
[Appium] Available drivers:
[Appium]   - uiautomator2@2.29.10 (automationName 'UiAutomator2')
[Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.
[HTTP] --> POST /session
[HTTP] {"capabilities":{"alwaysMatch":{"platformName":"Android","appium:platformVersion":"12","appium:deviceName":"127.0.0.1:7555","appium:appPackage":"cn.picclife.MobileAgent.dev","appium:appActivity":"cn.picclife.MobileAgent.HomeActivity","appium:noReset":true,"appium:automationName":"UiAutomator2","appium:ensureWebviewsHavePages":true,"appium:nativeWebScreenshot":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]},"desiredCapabilities":{"platformName":"Android","appium:platformVersion":"12","appium:deviceName":"127.0.0.1:7555","appium:appPackage":"cn.picclife.MobileAgent.dev","appium:appActivity":"cn.picclife.MobileAgent.HomeActivity","appium:noReset":true,"appium:automationName":"UiAutomator2","appium:ensureWebviewsHavePages":true,"appium:nativeWebScreenshot":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true}}
```

**Comment by mykola-mokhnach** [comment]
This exception is thrown if `List of devices` header cannot be found in the `adb devices` output. 
Looks like on your machine the actual output is just an empty string. Maybe try to update platform tools as a possible workaround

**Comment by ljppttfn** [comment]
> This exception is thrown if `List of devices` header cannot be found in the `adb devices` output. Looks like on your machine the actual output is just an empty string. Maybe try to update platform tools as a possible workaround

I download the `platform-tools` from https://developer.android.google.cn/studio/releases/platform-tools?hl=zh-cn, version is : `platform-tools_r34.0.4-windows` 。

The results are same. Still can't get devices.

**Comment by mykola-mokhnach** [comment]
What is the output of `D:\libs\android_sdk\platform-tools\adb.exe -P 5037 devices` command?

**Comment by ljppttfn** [comment]
> What is the output of `D:\libs\android_sdk\platform-tools\adb.exe -P 5037 devices` command?

```
D:\libs\android_sdk\platform-tools\adb.exe -P 5037 devices
List of devices attached
127.0.0.1:7555  device
```

**Comment by ljppttfn** [comment]
I want to debug the program...
I modify the code: `C:\Users\User\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-adb\lib\tools\system-calls.js:299:19`,
add some debug logs, like below:

```
systemCallMethods.getConnectedDevices = async function getConnectedDevices (opts = {}) {
  log.debug('>>>>> LJ Debug .....')
  log.debug('Getting connected devices');
  const args = [...this.executable.defaultArgs, 'devices'];
  if (opts.verbose) {
    args.push('-l');
  }
....
```
Then save the js, and  rerun appium, but the debug log doesn't print.
Why?

**Comment by mykola-mokhnach** [comment]
because this code is not being executed. Consider editing the transpiled version of it located under `build/lib` folder

**Comment by mykola-mokhnach** [comment]
Closed as third party issue

**Comment by markovaka** [comment]
Good day. I have the same problem. What is the solution for this?

**Comment by markovaka** [comment]
> I want to debug the program... I modify the code: `C:\Users\User\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-adb\lib\tools\system-calls.js:299:19`, add some debug logs, like below:
> 
> ```
> systemCallMethods.getConnectedDevices = async function getConnectedDevices (opts = {}) {
>   log.debug('>>>>> LJ Debug .....')
>   log.debug('Getting connected devices');
>   const args = [...this.executable.defaultArgs, 'devices'];
>   if (opts.verbose) {
>     args.push('-l');
>   }
> ....
> ```
> 
> Then save the js, and rerun appium, but the debug log doesn't print. Why?
Good day. did you manage to solve the problem?
