### ISSUE TITLE
Can't restart when we're not online

### ISSUE THREAD

**Issue by afathonih** [appium/appium#19224]
Recently, I've facing many of the following error:
```
[debug] [AndroidDriver] Found 1 webview: ["WEBVIEW_chrome"]
[debug] [AndroidUiautomator2Driver@d0f7 (3b85fdcf)] Available contexts: ["NATIVE_APP","WEBVIEW_chrome"]
[debug] [AndroidUiautomator2Driver@d0f7 (3b85fdcf)] Connecting to chrome-backed webview context 'WEBVIEW_chrome'
[debug] [AndroidUiautomator2Driver@d0f7 (3b85fdcf)] Found existing Chromedriver for context 'WEBVIEW_chrome'. Using it.
[debug] [Chromedriver@6b45] Matched '/url' to command name 'getUrl'
[debug] [Chromedriver@6b45] Proxying [GET /url] to [GET http://127.0.0.1:63550/session/bdadde77897a4902d8e069aaa5063008/url] with no body
[Chromedriver@6b45] connect ECONNREFUSED 127.0.0.1:63550
[debug] [AndroidUiautomator2Driver@d0f7 (3b85fdcf)] ChromeDriver is not associated with a window. Re-initializing the session.
[Chromedriver@6b45] Restarting chromedriver
[debug] [AndroidUiautomator2Driver@d0f7 (3b85fdcf)] Encountered internal error running command: Error: Can't restart when we're not online
[debug] [AndroidUiautomator2Driver@d0f7 (3b85fdcf)]     at Chromedriver.restart (/Users/ci/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/lib/chromedriver.js:706:13)
[debug] [AndroidUiautomator2Driver@d0f7 (3b85fdcf)]     at setupExistingChromedriver (/Users/ci/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/context.js:357:24)
[debug] [AndroidUiautomator2Driver@d0f7 (3b85fdcf)]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[debug] [AndroidUiautomator2Driver@d0f7 (3b85fdcf)]     at AndroidUiautomator2Driver.startChromedriverProxy (/Users/ci/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/context.js:171:5)
[debug] [AndroidUiautomator2Driver@d0f7 (3b85fdcf)]     at AndroidUiautomator2Driver.switchContext (/Users/ci/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/context.js:124:5)
[debug] [AndroidUiautomator2Driver@d0f7 (3b85fdcf)]     at AndroidUiautomator2Driver.setContext (/Users/ci/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/context.js:51:3)
```

I don't have an exact step to reproduce this.

Android version: 9
Chrome version: 95 (also reproducible on chrome 117)
Appium version: 2.1.3

**Comment by KazuCocoa** [comment]
Please fill out the bug template. Then, please add `appium:showChromedriverLog` capability to print chromedriver side's log as well.

**Comment by mykola-mokhnach** [comment]
Closed because of no response
