### ISSUE TITLE
Appium inspector can't get screenshot due to socket hang up issue.

### ISSUE THREAD

**Issue by gebitang** [appium/appium#19267]
Appium version: 2.1.3 
xcuitest driver: 4.35.0
wda version: 5.10.0 

iPhone X, OS version: iOS 14.4.1
Xcode: 15 
MacOS: 13.5.2 

Appium Inspecor version: 2023.4.1 

cap: 
```
{
  "platformName": "iOS",
  "appium:deviceName": "iPhone X",
  "appium:unicodeKeyboard": true,
  "appium:resetKeyboard": true,
  "appium:udid": "06f5c9774862b482452da0b126ad3bd169a2d366",
  "appium:bundleId": "com.facebook.wda.integrationApp",
  "appium:automationName": "XCUITest"
}
```

step to reproduce: just click start session button. 

here is the [appium detail log](https://gist.githubusercontent.com/gebitang/6331f9688683406f8d8eaf8065c43c16/raw/2862347564669767018678f287cc7c5c929a9d8d/appium2.log) 

WDA was built  successfully via xcodebuilt command, installed successfully. integrationApp was also launched.  then test failed due to socket hang up issue which was displayed from start to end. 

here is the related log:

```
2023-10-08 08:45:47:213 [Xcode]     /usr/bin/codesign --force --sign C620958B712FCC593CFD192AD0A0AD3114554318 --entitlements /Users/zhiwei/Library/Developer/Xcode/DerivedData/WebDriverAgent-grjrgvrtihmklwglkvbpjlikjizn/Build/Intermediates.noindex/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentRunner.build/WebDriverAgentRunner.xctest.xcent --timestamp\=none --generate-entitlement-der /Users/zhiwei/Library/Developer/Xcode/DerivedData/WebDriverAgent-grjrgvrtihmklwglkvbpjlikjizn/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app
2023-10-08 08:45:47:213 [Xcode] 
2023-10-08 08:45:47:421 [Xcode] /Users/zhiwei/Library/Developer/Xcode/DerivedData/WebDriverAgent-grjrgvrtihmklwglkvbpjlikjizn/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app: replacing existing signature
2023-10-08 08:45:47:421 [Xcode] 
2023-10-08 08:45:47:423 [Xcode] 
2023-10-08 08:45:47:423 [Xcode] 
2023-10-08 08:45:47:440 [Xcode] ** TEST BUILD SUCCEEDED **
2023-10-08 08:45:47:440 [Xcode] 
2023-10-08 08:45:47:440 [Xcode] 
2023-10-08 08:45:47:963 [XCUITestDriver@06e3 (9bf6ab2b)] Matched '/status' to command name 'getStatus'
2023-10-08 08:45:47:964 [XCUITestDriver@06e3 (9bf6ab2b)] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
2023-10-08 08:45:47:969 [iProxy@06f5c977:8100] Connection was refused to port 8100
2023-10-08 08:45:47:971 [XCUITestDriver@06e3 (9bf6ab2b)] socket hang up
2023-10-08 08:45:48:972 [XCUITestDriver@06e3 (9bf6ab2b)] Matched '/status' to command name 'getStatus'
2023-10-08 08:45:48:972 [XCUITestDriver@06e3 (9bf6ab2b)] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
2023-10-08 08:45:48:976 [iProxy@06f5c977:8100] Connection was refused to port 8100
2023-10-08 08:45:48:976 [XCUITestDriver@06e3 (9bf6ab2b)] socket hang up
2023-10-08 08:45:49:977 [XCUITestDriver@06e3 (9bf6ab2b)] Matched '/status' to command name 'getStatus'
2023-10-08 08:45:49:977 [XCUITestDriver@06e3 (9bf6ab2b)] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
2023-10-08 08:45:49:992 [iProxy@06f5c977:8100] Connection was refused to port 8100
2023-10-08 08:45:49:993 [XCUITestDriver@06e3 (9bf6ab2b)] socket hang up
2023-10-08 08:45:50:995 [XCUITestDriver@06e3 (9bf6ab2b)] Matched '/status' to command name 'getStatus'
2023-10-08 08:45:50:995 [XCUITestDriver@06e3 (9bf6ab2b)] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
2023-10-08 08:45:51:004 [iProxy@06f5c977:8100] Connection was refused to port 8100
2023-10-08 08:45:51:004 [XCUITestDriver@06e3 (9bf6ab2b)] socket hang up
2023-10-08 08:45:52:006 [XCUITestDriver@06e3 (9bf6ab2b)] Matched '/status' to command name 'getStatus'
2023-10-08 08:45:52:007 [XCUITestDriver@06e3 (9bf6ab2b)] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
2023-10-08 08:45:52:016 [iProxy@06f5c977:8100] Connection was refused to port 8100
2023-10-08 08:45:52:018 [XCUITestDriver@06e3 (9bf6ab2b)] socket hang up
2023-10-08 08:45:53:019 [XCUITestDriver@06e3 (9bf6ab2b)] Matched '/status' to command name 'getStatus'
2023-10-08 08:45:53:019 [XCUITestDriver@06e3 (9bf6ab2b)] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
2023-10-08 08:45:53:026 [iProxy@06f5c977:8100] Connection was refused to port 8100
2023-10-08 08:45:53:027 [XCUITestDriver@06e3 (9bf6ab2b)] socket hang up
2023-10-08 08:45:54:027 [XCUITestDriver@06e3 (9bf6ab2b)] Matched '/status' to command name 'getStatus'
2023-10-08 08:45:54:027 [XCUITestDriver@06e3 (9bf6ab2b)] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
2023-10-08 08:45:54:034 [iProxy@06f5c977:8100] Connection was refused to port 8100
2023-10-08 08:45:54:034 [XCUITestDriver@06e3 (9bf6ab2b)] socket hang up
2023-10-08 08:45:55:035 [XCUITestDriver@06e3 (9bf6ab2b)] Matched '/status' to command name 'getStatus'
2023-10-08 08:45:55:036 [XCUITestDriver@06e3 (9bf6ab2b)] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
2023-10-08 08:45:55:041 [iProxy@06f5c977:8100] Connection was refused to port 8100
2023-10-08 08:45:55:042 [XCUITestDriver@06e3 (9bf6ab2b)] socket hang up
2023-10-08 08:45:55:277 [Xcode] 2023-10-08 16:45:51.300972+0800 WebDriverAgentRunner-Runner[637:25992] [Default] Running tests...
2023-10-08 08:45:55:277 [Xcode] 
2023-10-08 08:45:55:535 [Xcode] Test Suite 'All tests' started at 2023-10-08 16:45:51.560.
2023-10-08 08:45:55:536 [Xcode] 
2023-10-08 08:45:55:539 [Xcode] Test Suite 'WebDriverAgentRunner.xctest' started at 2023-10-08 16:45:51.564.
2023-10-08 08:45:55:540 [Xcode] 
2023-10-08 08:45:55:541 [Xcode] Test Suite 'UITestingUITests' started at 2023-10-08 16:45:51.565.
2023-10-08 08:45:55:542 [Xcode]     t =      nans Suite Set Up
2023-10-08 08:45:55:542 [Xcode] 
2023-10-08 08:45:55:560 [Xcode] 2023-10-08 16:45:51.584608+0800 WebDriverAgentRunner-Runner[637:25992] [User Defaults] Couldn't write values for keys (
2023-10-08 08:45:55:560 [Xcode]     KeyboardAutocorrection
2023-10-08 08:45:55:560 [Xcode] ) in CFPrefsPlistSource<0x283ec4400> (Domain: com.apple.Preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access
2023-10-08 08:45:55:560 [Xcode] 
2023-10-08 08:45:55:572 [Xcode] 2023-10-08 16:45:51.596077+0800 WebDriverAgentRunner-Runner[637:25992] [User Defaults] Couldn't write values for keys (
2023-10-08 08:45:55:572 [Xcode]     KeyboardPrediction
2023-10-08 08:45:55:572 [Xcode] ) in CFPrefsPlistSource<0x283ec4400> (Domain: com.apple.Preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access
2023-10-08 08:45:55:572 [Xcode] 
2023-10-08 08:45:55:573 [Xcode] 2023-10-08 16:45:51.597170+0800 WebDriverAgentRunner-Runner[637:25992] [User Defaults] Couldn't write values for keys (
2023-10-08 08:45:55:573 [Xcode]     KeyboardShowPredictionBar
2023-10-08 08:45:55:573 [Xcode] ) in CFPrefsPlistSource<0x283ec4400> (Domain: com.apple.Preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access
2023-10-08 08:45:55:573 [Xcode] 
2023-10-08 08:45:55:574 [Xcode] 2023-10-08 16:45:51.598087+0800 WebDriverAgentRunner-Runner[637:25992] [User Defaults] Couldn't write values for keys (
2023-10-08 08:45:55:574 [Xcode]     DidShowGestureKeyboardIntroduction
2023-10-08 08:45:55:574 [Xcode] ) in CFPrefsPlistSource<0x283ec4400> (Domain: com.apple.Preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access
2023-10-08 08:45:55:574 [Xcode] 
2023-10-08 08:45:55:580 [Xcode] Test Case '-[UITestingUITests testRunner]' started.
2023-10-08 08:45:55:580 [Xcode] 
2023-10-08 08:45:55:584 [Xcode]     t =     0.00s Start Test at 2023-10-08 16:45:51.605
2023-10-08 08:45:55:584 [Xcode]     t =     0.00s Set Up
2023-10-08 08:45:55:584 [Xcode] 
2023-10-08 08:45:55:585 [Xcode] 2023-10-08 16:45:51.608632+0800 WebDriverAgentRunner-Runner[637:25992] Built at Oct  8 2023 16:44:13
2023-10-08 08:45:55:585 [Xcode] 
2023-10-08 08:45:55:599 [Xcode] 2023-10-08 16:45:51.622952+0800 WebDriverAgentRunner-Runner[637:25992] ServerURLHere->http://169.254.161.129:8100<-ServerURLHere
2023-10-08 08:45:55:599 [Xcode] 
2023-10-08 08:45:56:042 [XCUITestDriver@06e3 (9bf6ab2b)] Matched '/status' to command name 'getStatus'
2023-10-08 08:45:56:042 [XCUITestDriver@06e3 (9bf6ab2b)] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
2023-10-08 08:45:56:053 [Xcode] 2023-10-08 16:45:52.078189+0800 WebDriverAgentRunner-Runner[637:25992] Using singleton test manager
2023-10-08 08:45:56:054 [Xcode] 
2023-10-08 08:45:56:060 [XCUITestDriver@06e3 (9bf6ab2b)] Got response with status 200: {"value":{"build":{"upgradedAt":"1695710477315","time":"Oct  8 2023 16:44:14","productBundleIdentifier":"com.facebook.WebDriverAgentRunner"},"os":{"testmanagerdVersion":65535,"name":"iOS","sdkVersion":"17.0","version":"14.4.1"},"device":"iphone","ios":{"ip":"169.254.161.129"},"message":"WebDriverAgent is ready to accept commands","state":"success","ready":true},"sessionId":null}
2023-10-08 08:45:56:061 [XCUITestDriver@06e3 (9bf6ab2b)] WebDriverAgent information:
2023-10-08 08:45:56:061 [XCUITestDriver@06e3 (9bf6ab2b)] {
2023-10-08 08:45:56:061 [XCUITestDriver@06e3 (9bf6ab2b)]   "build": {
2023-10-08 08:45:56:061 [XCUITestDriver@06e3 (9bf6ab2b)]     "upgradedAt": "1695710477315",
2023-10-08 08:45:56:061 [XCUITestDriver@06e3 (9bf6ab2b)]     "time": "Oct  8 2023 16:44:14",
2023-10-08 08:45:56:062 [XCUITestDriver@06e3 (9bf6ab2b)]     "productBundleIdentifier": "com.facebook.WebDriverAgentRunner"
2023-10-08 08:45:56:062 [XCUITestDriver@06e3 (9bf6ab2b)]   },
2023-10-08 08:45:56:062 [XCUITestDriver@06e3 (9bf6ab2b)]   "os": {
2023-10-08 08:45:56:062 [XCUITestDriver@06e3 (9bf6ab2b)]     "testmanagerdVersion": 65535,
2023-10-08 08:45:56:062 [XCUITestDriver@06e3 (9bf6ab2b)]     "name": "iOS",
2023-10-08 08:45:56:062 [XCUITestDriver@06e3 (9bf6ab2b)]     "sdkVersion": "17.0",
2023-10-08 08:45:56:062 [XCUITestDriver@06e3 (9bf6ab2b)]     "version": "14.4.1"
2023-10-08 08:45:56:062 [XCUITestDriver@06e3 (9bf6ab2b)]   },
2023-10-08 08:45:56:062 [XCUITestDriver@06e3 (9bf6ab2b)]   "device": "iphone",
2023-10-08 08:45:56:062 [XCUITestDriver@06e3 (9bf6ab2b)]   "ios": {
2023-10-08 08:45:56:062 [XCUITestDriver@06e3 (9bf6ab2b)]     "ip": "169.254.161.129"
2023-10-08 08:45:56:062 [XCUITestDriver@06e3 (9bf6ab2b)]   },
2023-10-08 08:45:56:062 [XCUITestDriver@06e3 (9bf6ab2b)]   "message": "WebDriverAgent is ready to accept commands",
2023-10-08 08:45:56:062 [XCUITestDriver@06e3 (9bf6ab2b)]   "state": "success",
2023-10-08 08:45:56:062 [XCUITestDriver@06e3 (9bf6ab2b)]   "ready": true
2023-10-08 08:45:56:062 [XCUITestDriver@06e3 (9bf6ab2b)] }
2023-10-08 08:45:56:063 [XCUITestDriver@06e3 (9bf6ab2b)] WebDriverAgent successfully started after 112320ms
2023-10-08 08:45:56:064 [XCUITestDriver@06e3 (9bf6ab2b)] Event 'wdaSessionAttempted' logged at 1696754756064 (16:45:56 GMT+0800 (中国标准时间))
2023-10-08 08:45:56:064 [XCUITestDriver@06e3 (9bf6ab2b)] Sending createSession command to WDA
2023-10-08 08:45:56:065 [XCUITestDriver@06e3 (9bf6ab2b)] Matched '/session' to command name 'createSession'
2023-10-08 08:45:56:066 [XCUITestDriver@06e3 (9bf6ab2b)] Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.facebook.wda.integrationApp","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true,"shouldTerminateApp":true,"forceAppLaunch":true,"useNativeCachingStrategy":true,"forceSimulatorSoftwareKeyboardPresence":false}],"alwaysMatch":{}}}
2023-10-08 08:45:56:120 [Xcode]     t =     0.54s Open com.facebook.wda.integrationApp
2023-10-08 08:45:56:120 [Xcode]     t =     0.54s     Launch com.facebook.wda.integrationApp
2023-10-08 08:45:56:120 [Xcode]     t =     0.54s         Terminate com.facebook.wda.integrationApp:616
2023-10-08 08:45:56:120 [Xcode] 
2023-10-08 08:45:57:345 [Xcode]     t =     1.76s         Setting up automation session
2023-10-08 08:45:57:345 [Xcode] 
2023-10-08 08:45:57:412 [Xcode] 2023-10-08 16:45:53.433712+0800 WebDriverAgentRunner-Runner[637:25992] Waiting up to 10s until com.facebook.wda.integrationApp is in idle state (including animations)
2023-10-08 08:45:57:413 [Xcode]     t =     1.83s         Wait for com.facebook.wda.integrationApp to idle
2023-10-08 08:45:57:413 [Xcode] 
2023-10-08 08:45:58:448 [XCUITestDriver@06e3 (9bf6ab2b)] Got response with status 200: {"value":{"sessionId":"F8ACC9DB-3162-41B7-9EC6-1EE0CFA414E9","capabilities":{"sdkVersion":"14.4.1","device":"iphone"}},"sessionId":"F8ACC9DB-3162-41B7-9EC6-1EE0CFA414E9"}
2023-10-08 08:45:58:448 [XCUITestDriver@06e3 (9bf6ab2b)] Determined the downstream protocol as 'W3C'
2023-10-08 08:45:58:449 [XCUITestDriver@06e3 (9bf6ab2b)] Event 'wdaSessionStarted' logged at 1696754758448 (16:45:58 GMT+0800 (中国标准时间))
2023-10-08 08:45:58:449 [XCUITestDriver@06e3 (9bf6ab2b)] Event 'wdaStarted' logged at 1696754758449 (16:45:58 GMT+0800 (中国标准时间))
2023-10-08 08:45:58:450 [BaseDriver] The value of 'elementResponseAttributes' setting did not change. Skipping the update for it
2023-10-08 08:45:58:451 [BaseDriver] The value of 'shouldUseCompactResponses' setting did not change. Skipping the update for it
2023-10-08 08:45:58:452 [AppiumDriver@377f] New XCUITestDriver session created successfully, session 9bf6ab2b-e423-4560-8c36-e50e430cd7b4 added to master session list
2023-10-08 08:45:58:453 [AppiumDriver@377f] Event 'newSessionStarted' logged at 1696754758453 (16:45:58 GMT+0800 (中国标准时间))
2023-10-08 08:45:58:454 [XCUITestDriver@06e3 (9bf6ab2b)] Cached the protocol value 'W3C' for the new session 9bf6ab2b-e423-4560-8c36-e50e430cd7b4
2023-10-08 08:45:58:454 [XCUITestDriver@06e3 (9bf6ab2b)] Responding to client with driver.createSession() result: {"capabilities":{"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"platformName":"iOS","deviceName":"iPhone X","unicodeKeyboard":true,"resetKeyboard":true,"udid":"06f5c9774862b482452da0b126ad3bd169a2d366","bundleId":"com.facebook.wda.integrationApp","automationName":"XCUITest","includeSafariInWebviews":true,"newCommandTimeout":3600,"connectHardwareKeyboard":true}}
2023-10-08 08:45:58:459 [HTTP] <-- POST /session 200 121709 ms - 574
2023-10-08 08:45:58:459 [HTTP] 
2023-10-08 08:45:59:173 [HTTP] --> GET /session/9bf6ab2b-e423-4560-8c36-e50e430cd7b4/screenshot
2023-10-08 08:45:59:174 [HTTP] {}
2023-10-08 08:45:59:177 [XCUITestDriver@06e3 (9bf6ab2b)] Calling AppiumDriver.getScreenshot() with args: ["9bf6ab2b-e423-4560-8c36-e50e430cd7b4"]
2023-10-08 08:45:59:177 [XCUITestDriver@06e3 (9bf6ab2b)] Executing command 'getScreenshot'
2023-10-08 08:45:59:178 [XCUITestDriver@06e3 (9bf6ab2b)] Taking screenshot with WDA
2023-10-08 08:45:59:180 [XCUITestDriver@06e3 (9bf6ab2b)] Matched '/screenshot' to command name 'getScreenshot'
2023-10-08 08:45:59:180 [XCUITestDriver@06e3 (9bf6ab2b)] Proxying [GET /screenshot] to [GET http://127.0.0.1:8100/session/F8ACC9DB-3162-41B7-9EC6-1EE0CFA414E9/screenshot] with no body
2023-10-08 08:45:59:188 [Xcode] 2023-10-08 16:45:55.212651+0800 WebDriverAgentRunner-Runner[637:25992] The device under test does not support HEIC image encoding. Falling back to PNG
2023-10-08 08:45:59:188 [Xcode] 
2023-10-08 08:45:59:196 [XCUITestDriver@06e3 (9bf6ab2b)] socket hang up
2023-10-08 08:45:59:196 [XCUITestDriver@06e3 (9bf6ab2b)] Error getting screenshot: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
2023-10-08 08:45:59:197 [XCUITestDriver@06e3 (9bf6ab2b)] Taking screenshot with WDA
2023-10-08 08:45:59:197 [XCUITestDriver@06e3 (9bf6ab2b)] Matched '/screenshot' to command name 'getScreenshot'
2023-10-08 08:45:59:197 [XCUITestDriver@06e3 (9bf6ab2b)] Proxying [GET /screenshot] to [GET http://127.0.0.1:8100/session/F8ACC9DB-3162-41B7-9EC6-1EE0CFA414E9/screenshot] with no body
2023-10-08 08:45:59:199 [Xcode] 2023-10-08 16:45:55.216079+0800 WebDriverAgentRunner-Runner[637:26189] [Default] Exiting due to IDE disconnection.
2023-10-08 08:45:59:199 [Xcode] 
2023-10-08 08:45:59:204 [iProxy@06f5c977:8100] Connection was refused to port 8100
2023-10-08 08:45:59:205 [XCUITestDriver@06e3 (9bf6ab2b)] socket hang up
2023-10-08 08:46:00:207 [XCUITestDriver@06e3 (9bf6ab2b)] Taking screenshot with WDA
2023-10-08 08:46:00:207 [XCUITestDriver@06e3 (9bf6ab2b)] Matched '/screenshot' to command name 'getScreenshot'
2023-10-08 08:46:00:208 [XCUITestDriver@06e3 (9bf6ab2b)] Proxying [GET /screenshot] to [GET http://127.0.0.1:8100/session/F8ACC9DB-3162-41B7-9EC6-1EE0CFA414E9/screenshot] with no body
2023-10-08 08:46:00:213 [iProxy@06f5c977:8100] Connection was refused to port 8100
2023-10-08 08:46:00:214 [XCUITestDriver@06e3 (9bf6ab2b)] socket hang up
2023-10-08 08:46:00:226 [XCUITestDriver@06e3 (9bf6ab2b)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
2023-10-08 08:46:00:226 [XCUITestDriver@06e3 (9bf6ab2b)]     at JWProxy.command (/Users/zhiwei/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:355:13)
2023-10-08 08:46:00:226 [XCUITestDriver@06e3 (9bf6ab2b)]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-10-08 08:46:00:226 [XCUITestDriver@06e3 (9bf6ab2b)]     at XCUITestDriver.proxyCommand (/Users/zhiwei/.appium/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:112:35)
2023-10-08 08:46:00:226 [XCUITestDriver@06e3 (9bf6ab2b)]     at getScreenshotFromWDA (/Users/zhiwei/.appium/node_modules/appium-xcuitest-driver/lib/commands/screenshots.js:12:20)
2023-10-08 08:46:00:226 [XCUITestDriver@06e3 (9bf6ab2b)]     at wrapped (/Users/zhiwei/.appium/node_modules/appium-xcuitest-driver/node_modules/asyncbox/lib/asyncbox.js:95:13)
2023-10-08 08:46:00:226 [XCUITestDriver@06e3 (9bf6ab2b)]     at retry (/Users/zhiwei/.appium/node_modules/appium-xcuitest-driver/node_modules/asyncbox/lib/asyncbox.js:68:13)
2023-10-08 08:46:00:226 [XCUITestDriver@06e3 (9bf6ab2b)]     at retryInterval (/Users/zhiwei/.appium/node_modules/appium-xcuitest-driver/node_modules/asyncbox/lib/asyncbox.js:105:10)
2023-10-08 08:46:00:227 [XCUITestDriver@06e3 (9bf6ab2b)]     at XCUITestDriver.getScreenshot (/Users/zhiwei/.appium/node_modules/appium-xcuitest-driver/lib/commands/screenshots.js:46:12)
2023-10-08 08:46:00:227 [HTTP] <-- GET /session/9bf6ab2b-e423-4560-8c36-e50e430cd7b4/screenshot 500 1054 ms - 1374
2023-10-08 08:46:00:228 [HTTP] 
```

try with another iPhone ( os version: 12.3.1),  WDA was built fail with message---

Failed to start remote service "com.apple.instruments.remoteserver.DVTSecureSocketProxy" on device.  [whole log detail](https://gist.github.com/gebitang/54b148af3aa7555b99402c6385b656ee)

```
2023-10-08 06:53:06:494 [Xcode] 2023-10-08 14:53:06.494 xcodebuild[99582:6796288]  DTDKRemoteDeviceConnection: Failed to start remote service "com.apple.instruments.remoteserver.DVTSecureSocketProxy" on device. Error: Error Domain=com.apple.dtdevicekit Code=811 "Failed to start remote service "com.apple.instruments.remoteserver.DVTSecureSocketProxy" on device." UserInfo={NSUnderlyingError=0x6000027d67c0 {Error Domain=com.apple.dt.MobileDeviceErrorDomain Code=-402653150 "The service is invalid." UserInfo={MobileDeviceErrorCode=(0xE8000022), com.apple.dtdevicekit.stacktrace=(
2023-10-08 06:53:06:495 [Xcode] 	0   DTDeviceKitBase                     0x000000011b98d5fc DTDKCreateNSErrorFromAMDErrorCode + 229
2023-10-08 06:53:06:495 [Xcode] 	1   DTDeviceKitBase                     0x000000011b99b595 __63-[DTDKRemoteDeviceConnection startFirstServiceOf:unlockKeybag:]_block_invoke + 612
2023-10-08 06:53:06:523 [Xcode] 	2   DTDeviceKitBase                     0x000000011b99ac4f __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_4 + 22
2023-10-08 06:53:06:523 [Xcode] 	3   DTDeviceKitBase                     0x000000011b98f96e __DTDKExecuteInSession_block_invoke_2 + 52
2023-10-08 06:53:06:523 [Xcode] 	4   DTDeviceKitBase                     0x000000011b98efa6 __DTDKExecuteWithConnection_block_invoke_2 + 219
2023-10-08 06:53:06:524 [Xcode] 	5   DTDeviceKitBase                     0x000000011b98eea0 __DTDKExecuteWithConnection_block_invoke + 119
2023-10-08 06:53:06:524 [Xcode] 	6   libdispatch.dylib                   0x00007ff80b632033 _dispatch_client_callout + 8
2023-10-08 06:53:06:524 [Xcode] 	7   libdispatch.dylib                   0x00007ff80b63fba1 _dispatch_lane_barrier_sync_invoke_and_complete + 60
2023-10-08 06:53:06:524 [Xcode] 	8   DVTFoundation                       0x000000010c5a1f24 DVTDispatchBarrierSync + 148
2023-10-08 06:53:06:524 [Xcode] 	9   DVTFoundation                       0x000000010c577d43 -[DVTDispatchLock performLockedBlock:] + 60
2023-10-08 06:53:06:524 [Xcode] 	10  DTDeviceKitBase                     0x000000011b98ed96 DTDKExecuteWithConnection + 221
2023-10-08 06:53:06:524 [Xcode] 	11  DTDeviceKitBase                     0x000000011b98f7f4 DTDKExecuteInSession + 275
2023-10-08 06:53:06:525 [Xcode] 	12  DTDeviceKitBase                     0x000000011b99aa22 __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_2 + 207
2023-10-08 06:53:06:525 [Xcode] 	13  DVTFoundation                       0x000000010c5a1134 __DVT_CALLING_CLIENT_BLOCK__ + 7
2023-10-08 06:53:06:525 [Xcode] 	14  DVTFoundation                       0x000000010c5a1c20 __DVTDispatchAsync_block_invoke + 196
2023-10-08 06:53:06:525 [Xcode] 	15  libdispatch.dylib                   0x00007ff80b630d91 _dispatch_call_block_and_release + 12
2023-10-08 06:53:06:525 [Xcode] 	16  libdispatch.dylib                   0x00007ff80b632033 _dispatch_client_callout + 8
2023-10-08 06:53:06:525 [Xcode] 	17  libdispatch.dylib                   0x00007ff80b638200 _dispatch_lane_serial_drain + 769
2023-10-08 06:53:06:525 [Xcode] 	18  libdispatch.dylib                   0x00007ff80b638d6c _dispatch_lane_invoke + 417
2023-10-08 06:53:06:525 [Xcode] 	19  libdispatch.dylib                   0x00007ff80b6433fc _dispatch_workloop_worker_thread + 765
2023-10-08 06:53:06:525 [Xcode] 	20  libsystem_pthread.dylib             0x00007ff80b7cfc55 _pthread_wqthread + 327
2023-10-08 06:53:06:528 [Xcode] 	21  libsystem_pthread.dylib             0x00007ff80b7cebbf start_wqthread + 15
2023-10-08 06:53:06:529 [Xcode] ), DVTRadarComponentKey=261622, NSLocalizedDescription=The service is invalid.}}, NSLocalizedRecoverySuggestion=Please check your connection to your device., DVTRadarComponentKey=261622, NSLocalizedDescription=Failed to start remote service "com.apple.instruments.remoteserver.DVTSecureSocketProxy" on device.}
2023-10-08 06:53:06:529 [Xcode] 
2023-10-08 06:53:06:529 [Xcode] 2023-10-08 14:53:06.494 xcodebuild[99582:6797404]  DTDKRemoteDeviceConnection: Unable to start com.apple.instruments.remoteserver.DVTSecureSocketProxy on device “00008020-000910E91AB9002E”. Falling back to service without proxy.
2023-10-08 06:53:06:530 [Xcode] 
2023-10-08 06:53:06:913 [Xcode] 2023-10-08 14:53:07.104890+0800 WebDriverAgentRunner-Runner[278:8502] [Default] Running tests...
2023-10-08 06:53:06:914 [Xcode] 
```

**Comment by mykola-mokhnach** [comment]
The error is expected. the current xcuitest driver only supports iOS 15+

Consider downgrading the driver to use it with older versions.
