### ISSUE TITLE
iOS 17, Xcode 15 ，appium can not connect to iphone via wifi

### ISSUE THREAD

**Issue by HaoWShi** [appium/appium#19309]
issue copy from https://github.com/appium/appium-xcuitest-driver/issues/2097

I set up a local development environment.
Mac::2019 MacBook Pro, MacOS Sonoma 14.0
Xcode: 15.0
Iphone: Iphone14 Pro ,IOS17.0.3
Appium2

I can run test case in appium when iphone connect to mac by usb. And I make iphone and mac connect to same Wifi(other iphone's wifi hotspot). Then I disconnect usb between Mac and Iphone, XCode connect to Iphone via Wifi successfully
2)
Next, I run my script again, there is a error
**
No Real device with udid '*****', Looking for a simulator
Encountered internal error running command: Error: Unknow device or simulator UUID:'****'
at XCUITestDriver.determineDevice
atXCUITestDriver.start()
at XCUITestDriver.createSession()
at AppiumDriver.createSession()
**
3)
I run command 'idevice_id -n' and 'idevice_id -l' can not find the iphone connect to mac via wifi
4)
When I use Appium Inspector to connect , there is a same error.

Very much looking forward to a reply

**Comment by HaoWShi** [comment]
This problem is tracked at this link.: (https://github.com/appium/appium/issues/19311)
