### ISSUE TITLE
bug: ExternalDriver unable to execute commands when handling deleteSession

### ISSUE THREAD

**Issue by kandji-joel** [appium/appium#19405]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am working on creating a plugin to handle some device setup / cleanup and would like to extend functionality of `deleteSession()` and `createSession()`. 

I noticed that when handling the `deleteSession` command, the ExternalDriver is unable to execute any commands. For a bit, I thought it was something I was doing wrong in code, but seems like it is exclusive to the `deleteSession` command. Is there any obvious reason why the driver would be unable to execute commands at the start of the `deleteSession` command?

I've tried a bunch of commands and they all throw an `[XCUITestDriver@ed5f (22d510c0)] Encountered internal error running command: TypeError: driver.activateApp is not a function` error, regardless of command. If I drop the same code into another command, like `getPageSource`, the driver is able to execute the command.

### Expected Behavior

ExternalDriver should be able to execute commands when handling `deleteSession` up until  calling `await next()` where Appium finishes up deleting session

### Minimal Reproducible Example

Relevant Python code for testing plugin
```python
driver = get_mobile_driver()
# tests handling `getPageSource`
_ = driver.page_source
# tests handling `deleteSession`
driver.quit()
```

Relevant plugin code for handling commands
```typescript
import { log } from '../logger';
import { NextPluginCallback, ExternalDriver } from '@appium/types';

export default async function handle(next: NextPluginCallback, driver: ExternalDriver, commandName: string, ...args: any) {
  log.info(`Received ${commandName} request on driver - ${driver}`);

  try {
    if (commandName == "getPageSource") {
      // calling `activateApp()` when handling `driver.page_source` successfully opens Safari on device
      const _ = await driver.activateApp("com.apple.mobilesafari");
    } else if (commandName == "deleteSession") {
      // calling `activateApp()` when handling `driver.quit()` DOES NOT open Safari on device and throws error
      const _ = await driver.activateApp("com.apple.mobilesafari");
    }
  } catch(err) {
    log.error(err)
  } finally {
    return await next();
  }
}
```

```log
2023-11-10 13:09:46:108 - [HTTP] --> DELETE /wd/hub/session/c5e6bb2a-39b8-452c-921b-ba1c751d5f70
2023-11-10 13:09:46:109 - [HTTP] {}
2023-11-10 13:09:46:109 - [XCUITestDriver@fdf7 (c5e6bb2a)] Calling AppiumDriver.deleteSession() with args: ["c5e6bb2a-39b8-452c-921b-ba1c751d5f70"]
2023-11-10 13:09:46:110 - [AppiumDriver@b4d1] Clearing new command timeout pre-emptively since plugin(s) will handle this command
2023-11-10 13:09:46:110 - [AppiumDriver@b4d1] Plugins which can handle cmd 'deleteSession': appium-plugin
2023-11-10 13:09:46:110 - [AppiumDriver@b4d1] Plugin appium-plugin is now handling cmd 'deleteSession'
2023-11-10 13:09:46:110 - [AppiumPlugin] Received deleteSession request on driver - [object Object]
2023-11-10 13:09:46:133 - [AppiumPlugin] TypeError: driver.activateApp is not a function
2023-11-10 13:09:46:133 - [AppiumPlugin]     at AppiumPlugin.<anonymous> (/Users/<user>/Documents/GitHub/internal-appium-plugin/src/commands/handle.ts:13:30)
2023-11-10 13:09:46:133 - [AppiumPlugin]     at Generator.next (<anonymous>)
2023-11-10 13:09:46:133 - [AppiumPlugin]     at /Users/<user>/Documents/GitHub/internal-appium-plugin/build/commands/handle.js:8:71
2023-11-10 13:09:46:133 - [AppiumPlugin]     at new Promise (<anonymous>)
2023-11-10 13:09:46:133 - [AppiumPlugin]     at __awaiter (/Users/<user>/Documents/GitHub/internal-appium-plugin/build/commands/handle.js:4:12)
2023-11-10 13:09:46:133 - [AppiumPlugin]     at AppiumPlugin.handle (/Users/<user>/Documents/GitHub/internal-appium-plugin/build/commands/handle.js:14:12)
2023-11-10 13:09:46:133 - [AppiumPlugin]     at /Users/<user>/Documents/GitHub/internal-appium-plugin/node_modules/appium/lib/appium.js:791:29
2023-11-10 13:09:46:133 - [AppiumPlugin]     at AppiumDriver.executeWrappedCommand (/Users/<user>/Documents/GitHub/internal-appium-plugin/node_modules/appium/lib/appium.js:828:22)
2023-11-10 13:09:46:133 - [AppiumPlugin]     at AppiumDriver.executeCommand (/Users/<user>/Documents/GitHub/internal-appium-plugin/node_modules/appium/lib/appium.js:734:28)
2023-11-10 13:09:46:133 - [AppiumPlugin]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-11-10 13:09:46:133 - [AppiumPlugin]     at asyncHandler (/Users/<user>/Documents/GitHub/internal-appium-plugin/node_modules/@appium/base-driver/lib/protocol/protocol.js:393:1
```

### Environment

- Operating system: macOS
- Appium server version (output of `appium --version`): Appium v2.2.1 (REV ee76bd21b9736a1a25413ab2af035e2f2472290b)
- Appium driver(s) and their version(s): xcuitest@5.8.2 (automationName 'XCUITest')
- Appium plugin(s) and their version(s): appium-plugin@0.0.2 (ACTIVE)
- Node.js version (output of `node --version`): v18.9.1
- `npm` version (output of `npm --version`): 8.19.1
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: iOS 
- Real device or emulator/simulator: Real device

**Comment by mykola-mokhnach** [comment]
I assume this happens because in such case the `driver` instance is passed from the umbrella AppiumDriver and not the actual target driver instance. You may verify that by checking the `driver.constuctor.name` value. I would try to reference the "real" driver instance from any previous call, similarly to https://github.com/mykola-mokhnach/appium-devtools-plugin/blob/b8857ba5335645c1064d8cedb32898399b4d19a0/lib/plugin.js#L127

**Comment by kandji-joel** [comment]
@mykola-mokhnach good catch, it looks like that's what's happening


`Received getPageSource request on driver - XCUITestDriver`
```logs
2023-11-11 09:17:37:213 - [XCUITestDriver@2eba (2b71c689)] Calling AppiumDriver.getPageSource() with args: ["2b71c689-f0a6-436b-a8c9-1fdb88ea5f54"]
2023-11-11 09:17:37:213 - [AppiumDriver@1067] Clearing new command timeout pre-emptively since plugin(s) will handle this command
2023-11-11 09:17:37:214 - [AppiumDriver@1067] Plugins which can handle cmd 'getPageSource': appium-plugin
2023-11-11 09:17:37:215 - [AppiumDriver@1067] Plugin appium-plugin is now handling cmd 'getPageSource'
2023-11-11 09:17:37:215 - [🐝🐝🐝🐝🐝🐝🐝🐝] Received getPageSource request on driver - XCUITestDriver
```

`Received deleteSession request on driver - AppiumDriver`
```logs
2023-11-11 09:17:48:129 - [XCUITestDriver@2eba (2b71c689)] Calling AppiumDriver.deleteSession() with args: ["2b71c689-f0a6-436b-a8c9-1fdb88ea5f54"]
2023-11-11 09:17:48:129 - [AppiumDriver@1067] Clearing new command timeout pre-emptively since plugin(s) will handle this command
2023-11-11 09:17:48:130 - [AppiumDriver@1067] Plugins which can handle cmd 'deleteSession': appium-plugin
2023-11-11 09:17:48:130 - [AppiumDriver@1067] Plugin appium-plugin is now handling cmd 'deleteSession'
2023-11-11 09:17:48:130 - [🐝🐝🐝🐝🐝🐝🐝🐝] Received deleteSession request on driver - AppiumDriver
```

--------------

So your proposed solution is to hold on to the driver instance from a previous call and use that. I tried with a single device and this seems to work well.

How would this work when running multiple devices / driver instances in parallel? Couldn't it potentially reference the wrong driver instance when handling the requests coming through? Maybe I could hang on to a mapping of driver instances and session ids to make sure the correct driver instance is handling each request.

Tbh it would be nice if driver passed when handling deleteSession is the actual target driver instance (in this case, XCUITestDriver). Is is expected that the umbrella AppiumDriver is handling deleteSession and not the actual target driver?

**Comment by mykola-mokhnach** [comment]
> How would this work when running multiple devices / driver instances in parallel?

This should work just fine. A separate plugin instance is created for each driver instance. And you cannot handle more than one device by a single driver.

> Is is expected that the umbrella AppiumDriver is handling deleteSession and not the actual target driver?

Yes, it Is expected that such requests are handled by the umbrella driver.

**Comment by kandji-joel** [comment]
Oh perfect, I didn't realize a separate plugin instance was created for each driver instance. Thanks again

**Comment by jlipps** [comment]
@kandji-joel don't forget to share more with us about this plugin if you want later on--if it seems useful for other people we can add it to our ecosystem list!

**Comment by kandji-joel** [comment]
Will do, thank you @mykola-mokhnach @jlipps
