### ISSUE TITLE
session not created: This version of ChromeDriver only supports Chrome version 115 Current browser version is 119.0.6045.66

### ISSUE THREAD

**Issue by zhouhyi** [appium/appium#19420]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Create Docker appium container code:
`docker run -d -p $docker_port:4723 --log-driver json-file --log-opt max-size=200M --restart always --device /dev/bus/usb/004/$port:/dev/bus/usb/004/001 -v /home/qauser/viu_build:/tmp/viu_build --name $1 -e APPIUM_ADDITIONAL_PARAMS="--allow-insecure chromedriver_autodownload" $docker_image_name`

Error:
io.appium.java_client.NoSuchContextException: An unknown server-side error occurred while processing the command. Original error: A new session could not be created. Details: session not created: This version of ChromeDriver only supports Chrome version 115
Current browser version is 119.0.6045.66 with package name com.viu.phone
Build info: version: '4.9.1', revision: 'eb2032df7f'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '13.5.2', java.version: '1.8.0_345'
Driver info: io.appium.java_client.android.AndroidDriver
Command: [797cbf37-4aa1-4595-82b6-2c7db7d9fa89, switchToContext {name=WEBVIEW_Terrace}]
Capabilities {appium:app: /tmp/viu_build/viu.apk, appium:appPackage: com.viu.phone, appium:appWaitActivity: com.viu.phone.ui.activity.G..., appium:appWaitDuration: 90000, appium:autoGrantPermissions: true, appium:automationName: UIAutomator2, appium:bundleID: com.viu.phone, appium:chromeOptions: {w3c: true}, appium:clearDeviceLogsOnStart: true, appium:databaseEnabled: false, appium:desired: {app: /tmp/viu_build/viu.apk, appWaitActivity: com.viu.phone.ui.activity.G..., appWaitDuration: 90000, autoGrantPermissions: true, automationName: UIAutomator2, bundleID: com.viu.phone, chromeOptions: {w3c: true}, clearDeviceLogsOnStart: true, deviceName: SAMSUNG_S22, intentAction: android.intent.action.MAIN, intentCategory: android.intent.category.LAU..., intentFlags: 0x10200000, language: en, locale: sg, newCommandTimeout: 2400, noReset: false, platformName: ANDROID, platformVersion: 13, systemPort: 10102, udid: R5CT12HL5EV}, appium:deviceApiLevel: 33, appium:deviceManufacturer: samsung, appium:deviceModel: SM-S9010, appium:deviceName: R5CT12HL5EV, appium:deviceScreenDensity: 480, appium:deviceScreenSize: 1080x2340, appium:deviceUDID: R5CT12HL5EV, appium:intentAction: android.intent.action.MAIN, appium:intentCategory: android.intent.category.LAU..., appium:intentFlags: 0x10200000, appium:javascriptEnabled: true, appium:language: en, appium:locale: sg, appium:locationContextEnabled: false, appium:networkConnectionEnabled: true, appium:newCommandTimeout: 2400, appium:noReset: false, appium:pixelRatio: 3, appium:platformVersion: 13, appium:statBarHeight: 81, appium:systemPort: 10102, appium:takesScreenshot: true, appium:udid: R5CT12HL5EV, appium:viewportRect: {height: 2034, left: 0, top: 81, width: 1080}, appium:warnings: {}, appium:webStorageEnabled: false, platformName: ANDROID}
Session ID: 797cbf37-4aa1-4595-82b6-2c7db7d9fa89
    at io.appium.java_client.remote.SupportsContextSwitching.context(SupportsContextSwitching.java:48)
    at utility.WebDriverUtils.setContextAsWebview(WebDriverUtils.java:2747)
    at utility.gesture.WebElementWaitingHelper.getVisibleWebElement(WebElementWaitingHelper.java:120)
    at utility.gesture.WebElementWaitingHelper.isWebElementVisible(WebElementWaitingHelper.java:112)
    at pageObject.LoginRegisterPage.atLoginRegisterPage(LoginRegisterPage.java:82)
    at pageObject.LoginRegisterPage.atLoginRegisterPage(LoginRegisterPage.java:74)
    at stepDefination.Login.i_login_a_premium_account_with_email(Login.java:63)
    at ✽.When I login a premium account with email(Viu_RegressionTest/Login.feature:27)
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: A new session could not be created. Details: session not created: This version of ChromeDriver only supports Chrome version 115
Current browser version is 119.0.6045.66 with package name com.viu.phone
Build info: version: '4.9.1', revision: 'eb2032df7f'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '13.5.2', java.version: '1.8.0_345'
Driver info: io.appium.java_client.android.AndroidDriver
Command: [797cbf37-4aa1-4595-82b6-2c7db7d9fa89, switchToContext {name=WEBVIEW_Terrace}]
Capabilities {appium:app: /tmp/viu_build/viu.apk, appium:appPackage: com.viu.phone, appium:appWaitActivity: com.viu.phone.ui.activity.G..., appium:appWaitDuration: 90000, appium:autoGrantPermissions: true, appium:automationName: UIAutomator2, appium:bundleID: com.viu.phone, appium:chromeOptions: {w3c: true}, appium:clearDeviceLogsOnStart: true, appium:databaseEnabled: false, appium:desired: {app: /tmp/viu_build/viu.apk, appWaitActivity: com.viu.phone.ui.activity.G..., appWaitDuration: 90000, autoGrantPermissions: true, automationName: UIAutomator2, bundleID: com.viu.phone, chromeOptions: {w3c: true}, clearDeviceLogsOnStart: true, deviceName: SAMSUNG_S22, intentAction: android.intent.action.MAIN, intentCategory: android.intent.category.LAU..., intentFlags: 0x10200000, language: en, locale: sg, newCommandTimeout: 2400, noReset: false, platformName: ANDROID, platformVersion: 13, systemPort: 10102, udid: R5CT12HL5EV}, appium:deviceApiLevel: 33, appium:deviceManufacturer: samsung, appium:deviceModel: SM-S9010, appium:deviceName: R5CT12HL5EV, appium:deviceScreenDensity: 480, appium:deviceScreenSize: 1080x2340, appium:deviceUDID: R5CT12HL5EV, appium:intentAction: android.intent.action.MAIN, appium:intentCategory: android.intent.category.LAU..., appium:intentFlags: 0x10200000, appium:javascriptEnabled: true, appium:language: en, appium:locale: sg, appium:locationContextEnabled: false, appium:networkConnectionEnabled: true, appium:newCommandTimeout: 2400, appium:noReset: false, appium:pixelRatio: 3, appium:platformVersion: 13, appium:statBarHeight: 81, appium:systemPort: 10102, appium:takesScreenshot: true, appium:udid: R5CT12HL5EV, appium:viewportRect: {height: 2034, left: 0, top: 81, width: 1080}, appium:warnings: {}, appium:webStorageEnabled: false, platformName: ANDROID}
Session ID: 797cbf37-4aa1-4595-82b6-2c7db7d9fa89
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
    at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
    at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
    at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:193)
    at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:250)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:598)
    at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:308)
    at io.appium.java_client.remote.SupportsContextSwitching.context(SupportsContextSwitching.java:45)
    at utility.WebDriverUtils.setContextAsWebview(WebDriverUtils.java:2747)
    at utility.gesture.WebElementWaitingHelper.getVisibleWebElement(WebElementWaitingHelper.java:120)
    at utility.gesture.WebElementWaitingHelper.isWebElementVisible(WebElementWaitingHelper.java:112)
    at pageObject.LoginRegisterPage.atLoginRegisterPage(LoginRegisterPage.java:82)
    at pageObject.LoginRegisterPage.atLoginRegisterPage(LoginRegisterPage.java:74)
    at stepDefination.Login.i_login_a_premium_account_with_email(Login.java:63)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at cucumber.runtime.Utils$1.call(Utils.java:40)
    at cucumber.runtime.Timeout.timeout(Timeout.java:16)
    at cucumber.runtime.Utils.invoke(Utils.java:34)
    at cucumber.runtime.java.JavaStepDefinition.execute(JavaStepDefinition.java:38)
    at cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:37)
    at cucumber.runtime.ExtendedRuntime.runStep(ExtendedRuntime.java:319)
    at cucumber.runtime.model.StepContainer.runStep(StepContainer.java:44)
    at cucumber.runtime.model.StepContainer.runSteps(StepContainer.java:39)
    at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:44)
    at com.github.mkolisnyk.cucumber.runner.ExtendedExecutionUnitRunner.run(ExtendedExecutionUnitRunner.java:32)
    at com.github.mkolisnyk.cucumber.runner.ExtendedFeatureRunner.runChild(ExtendedFeatureRunner.java:81)
    at com.github.mkolisnyk.cucumber.runner.ExtendedFeatureRunner.runChild(ExtendedFeatureRunner.java:23)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:70)
    at com.github.mkolisnyk.cucumber.runner.ExtendedCucumber.runChild(ExtendedCucumber.java:108)
    at com.github.mkolisnyk.cucumber.runner.ExtendedCucumber.runChild(ExtendedCucumber.java:32)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at com.github.mkolisnyk.cucumber.runner.ExtendedCucumber.run(ExtendedCucumber.java:148)
    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:377)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:284)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:248)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:167)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
    at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
    at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)

### Expected Behavior

The appium service is configured to automatically download Chromedrive, which can automatically download the chromedriver that matches the chrome browser and open web pages

### Minimal Reproducible Example

`docker run -d -p $docker_port:4723 --log-driver json-file --log-opt max-size=200M --restart always --device /dev/bus/usb/004/$port:/dev/bus/usb/004/001 -v /home/qauser/viu_build:/tmp/viu_build --name $1 -e APPIUM_ADDITIONAL_PARAMS="--allow-insecure chromedriver_autodownload" $docker_image_name`

### Environment

- Operating system: Android 13
- Appium server version (output of `appium --version`): 2.1.3
- Appium driver(s) and their version(s): uiautomator2@2.29.9
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator: SAMSUNG_S22
- Device chrome version:
   `dumpsys package com.android.chrome`
   package versionName=119.0.6045.66
   hidden system package versionName=108.0.5359.128

### Further Information

[ChromeDriver_only _supports_Chrome version_115_logcat.log](https://github.com/appium/appium/files/13361216/ChromeDriver_only._supports_Chrome.version_115_logcat.log)

**Comment by mykola-mokhnach** [comment]
Please provide the server log.

You may try to manually provide the necessary chromedriver version. Check https://github.com/appium/appium-uiautomator2-driver#hybrid-mode

**Comment by zhouhyi** [comment]
@mykola-mokhnach 
Here is the server log of the above issue:
[autodownload_chromedriver_not_support_android13.log](https://github.com/appium/appium/files/13363263/autodownload_chromedriver_not_support_android13.log)

My current chrome browser version is 119. Manually updating the chromedriver version to version 119 and the automation can be executed successfully.

In addition, in Android 11, device SAMSUNG_A52, the chrome browser version is also 119.0.6045.66, the appium server is set to automatically download chromedriver, and the automation can be executed successfully.
Successful appium server log:
[autodownload_chromedriver_support_android11.log](https://github.com/appium/appium/files/13363288/autodownload_chromedriver_support_android11.log)

Therefore, I would like to know if the appium server setting to automatically download chromedriver on Android 13 system is not compatible with the version of chrome browser?

**Comment by mykola-mokhnach** [comment]
If we are talking about autodownload then make sure you have the most recent driver version. Google has changed the repository address with Chrome 116 release, so older drivers can only fetch Chromedrivers up to v115 from the old repository.

**Comment by zhouhyi** [comment]
II confirmed that my appium version is the latest version (2.1.3), and upgraded uiautomator2 from 2.29.9 to the latest version 2.34.1.
The driver version is already the latest, but Chromedriver versions higher than 115 still cannot be downloaded automatically.
This is the service log for upgrading to the latest driver:
[appium.log](https://github.com/appium/appium/files/13363987/appium.log)

**Comment by mykola-mokhnach** [comment]
I don't observe any traces related to chromedriver downloads in the above log

**Comment by mykola-mokhnach** [comment]
Closed as not an issue

**Comment by zhouhyi** [comment]
@mykola-mokhnach Thanks for your help.
After upgrading appium version and uia2 version, the problem was solved.
appium version 2.1.3 upgraded to 2.2.2,
uiautomator2 2.29.11 upgraded to 2.34.1
