### ISSUE TITLE
APPIUM_Getting No Context Exception on switching to webview

### ISSUE THREAD

**Issue by Prawin06** [appium/appium#19461]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am seeing No Context Exception when trying to switch to webview in a hybrid app

### Expected Behavior

I should be able to switch to webview and interact with the elements

### Minimal Reproducible Example

desiredCapabilities.setCapability("deviceName", "2B131FDH300167");// RZCW3096SNZ // 10.76.241.4:7429
			desiredCapabilities.setCapability("AndroidVersion","13");
			
			desiredCapabilities.setCapability("newCommandTimeout", "90000");
			desiredCapabilities.setCapability("appPackage", "com.vzbusiness");
			desiredCapabilities.setCapability("appActivity", "com.vzbusiness.ui.login.LauncherActivityQA");
			desiredCapabilities.setCapability("automationName", "UiAutomator2");
			desiredCapabilities.setCapability("platformName", "Android");
			desiredCapabilities.setCapability("noReset", true);
			desiredCapabilities.setCapability("unicodeKeyboard", true);
			desiredCapabilities.setCapability("clearSystemFiles", true);
			desiredCapabilities.setCapability("-session-override", true);
			
			desiredCapabilities.setCapability("chromedriverExecutable", "/Users/*****/Downloads/chrome/chromedriver");
			driver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"), desiredCapabilities);

### Environment

- Operating system: MAC
- Appium server version (output of `appium --version`): 1.22.3
- Platform and version under test: Android
- Real device or emulator/simulator: Real Device

### Further Information

ECLIPSE Logs:

io.appium.java_client.NoSuchContextException: Error communicating with the remote browser. It may have died.
Build info: version: '4.8.1', revision: '8ebccac989'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '11.5', java.version: '16.0.2'
Driver info: io.appium.java_client.android.AndroidDriver
Command: [2f8db1f4-5e64-4ece-97a0-37582041434c, switchToContext {name=WEBVIEW_com.vzbusiness}]
Capabilities {appium:-session-override: true, appium:AndroidVersion: 13, appium:appActivity: com.vzbusiness.ui.login.Lau..., appium:appPackage: com.vzbusiness, appium:automationName: UiAutomator2, appium:chromedriverExecutable: /Users/MPR36B5/Downloads/ch..., appium:clearSystemFiles: true, appium:databaseEnabled: false, appium:desired: {-session-override: true, AndroidVersion: 13, appActivity: com.vzbusiness.ui.login.Lau..., appPackage: com.vzbusiness, automationName: UiAutomator2, chromedriverExecutable: /Users/MPR36B5/Downloads/ch..., clearSystemFiles: true, deviceName: 2B131FDH300167, newCommandTimeout: 90000, noReset: true, platformName: android, unicodeKeyboard: true}, appium:deviceApiLevel: 33, appium:deviceManufacturer: Google, appium:deviceModel: Pixel 7 Pro, appium:deviceName: 2B131FDH300167, appium:deviceScreenDensity: 420, appium:deviceScreenSize: 1080x2340, appium:deviceUDID: 2B131FDH300167, appium:javascriptEnabled: true, appium:locationContextEnabled: false, appium:networkConnectionEnabled: true, appium:newCommandTimeout: 90000, appium:noReset: true, appium:pixelRatio: 2.625, appium:platformVersion: 13, appium:statBarHeight: 144, appium:takesScreenshot: true, appium:unicodeKeyboard: true, appium:viewportRect: {height: 2025, left: 0, top: 144, width: 1080}, appium:warnings: {}, appium:webStorageEnabled: false, platformName: ANDROID}
Session ID: 2f8db1f4-5e64-4ece-97a0-37582041434c
	at io.appium.java_client.remote.SupportsContextSwitching.context(SupportsContextSwitching.java:48)
	at Initializer.BaseClass.switchingWebContext(BaseClass.java:101)
	at pages.DeviceTradeInPage.enteringDeviceName(DeviceTradeInPage.java:12)
	at steps.DeviceTradeInSteps.theUserProceedsWithAllMandatorySelectionForDeviceTradeInAndSubmitsTheTransaction(DeviceTradeInSteps.java:14)
	at ✽.the user proceeds with all mandatory selection for Device Trade In and submits the transaction(src/test/java/features/DeviceTradeIn.feature:15)
Caused by: org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: '4.8.1', revision: '8ebccac989'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '11.5', java.version: '16.0.2'
Driver info: io.appium.java_client.android.AndroidDriver
Command: [2f8db1f4-5e64-4ece-97a0-37582041434c, switchToContext {name=WEBVIEW_com.vzbusiness}]
Capabilities {appium:-session-override: true, appium:AndroidVersion: 13, appium:appActivity: com.vzbusiness.ui.login.Lau..., appium:appPackage: com.vzbusiness, appium:automationName: UiAutomator2, appium:chromedriverExecutable: /Users/MPR36B5/Downloads/ch..., appium:clearSystemFiles: true, appium:databaseEnabled: false, appium:desired: {-session-override: true, AndroidVersion: 13, appActivity: com.vzbusiness.ui.login.Lau..., appPackage: com.vzbusiness, automationName: UiAutomator2, chromedriverExecutable: /Users/MPR36B5/Downloads/ch..., clearSystemFiles: true, deviceName: 2B131FDH300167, newCommandTimeout: 90000, noReset: true, platformName: android, unicodeKeyboard: true}, appium:deviceApiLevel: 33, appium:deviceManufacturer: Google, appium:deviceModel: Pixel 7 Pro, appium:deviceName: 2B131FDH300167, appium:deviceScreenDensity: 420, appium:deviceScreenSize: 1080x2340, appium:deviceUDID: 2B131FDH300167, appium:javascriptEnabled: true, appium:locationContextEnabled: false, appium:networkConnectionEnabled: true, appium:newCommandTimeout: 90000, appium:noReset: true, appium:pixelRatio: 2.625, appium:platformVersion: 13, appium:statBarHeight: 144, appium:takesScreenshot: true, appium:unicodeKeyboard: true, appium:viewportRect: {height: 2025, left: 0, top: 144, width: 1080}, appium:warnings: {}, appium:webStorageEnabled: false, platformName: ANDROID}
Session ID: 2f8db1f4-5e64-4ece-97a0-37582041434c
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:567)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:598)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:267)
	at io.appium.java_client.remote.SupportsContextSwitching.context(SupportsContextSwitching.java:45)
	at Initializer.BaseClass.switchingWebContext(BaseClass.java:101)
	at pages.DeviceTradeInPage.enteringDeviceName(DeviceTradeInPage.java:12)
	at steps.DeviceTradeInSteps.theUserProceedsWithAllMandatorySelectionForDeviceTradeInAndSubmitsTheTransaction(DeviceTradeInSteps.java:14)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at cucumber.runtime.Utils$1.call(Utils.java:26)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.Utils.invoke(Utils.java:20)
	at cucumber.runtime.java.JavaStepDefinition.execute(JavaStepDefinition.java:57)
	at cucumber.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:50)
	at cucumber.runner.TestStep.executeStep(TestStep.java:63)
	at cucumber.runner.TestStep.run(TestStep.java:49)
	at cucumber.runner.PickleStepTestStep.run(PickleStepTestStep.java:43)
	at cucumber.runner.TestCase.run(TestCase.java:44)
	at cucumber.runner.Runner.runPickle(Runner.java:40)
	at cucumber.api.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:65)
	at cucumber.api.testng.AbstractTestNGCucumberTests.runScenario(AbstractTestNGCucumberTests.java:22)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:766)
	at org.testng.TestRunner.run(TestRunner.java:587)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
	at org.testng.TestNG.runSuites(TestNG.java:1039)
	at org.testng.TestNG.run(TestNG.java:1007)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.io.UncheckedIOException: org.asynchttpclient.exception.RemotelyClosedException: Remotely closed
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:73)
	at io.appium.java_client.AppiumUserAgentFilter.lambda$apply$0(AppiumUserAgentFilter.java:88)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:49)
	at io.appium.java_client.AppiumUserAgentFilter.lambda$apply$0(AppiumUserAgentFilter.java:88)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
	at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:99)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:181)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:262)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	... 50 more
Caused by: org.asynchttpclient.exception.RemotelyClosedException: Remotely closed
	at org.asynchttpclient.exception.RemotelyClosedException.INSTANCE(Unknown Source)

FAILED: runScenario("E2E Trade In Txn via Shop", "Device Trade In Feature")
        Runs Cucumber Scenarios
io.appium.java_client.NoSuchContextException: Error communicating with the remote browser. It may have died.
Build info: version: '4.8.1', revision: '8ebccac989'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '11.5', java.version: '16.0.2'
Driver info: io.appium.java_client.android.AndroidDriver
Command: [2f8db1f4-5e64-4ece-97a0-37582041434c, switchToContext {name=WEBVIEW_com.vzbusiness}]
Capabilities {appium:-session-override: true, appium:AndroidVersion: 13, appium:appActivity: com.vzbusiness.ui.login.Lau..., appium:appPackage: com.vzbusiness, appium:automationName: UiAutomator2, appium:chromedriverExecutable: /Users/MPR36B5/Downloads/ch..., appium:clearSystemFiles: true, appium:databaseEnabled: false, appium:desired: {-session-override: true, AndroidVersion: 13, appActivity: com.vzbusiness.ui.login.Lau..., appPackage: com.vzbusiness, automationName: UiAutomator2, chromedriverExecutable: /Users/MPR36B5/Downloads/ch..., clearSystemFiles: true, deviceName: 2B131FDH300167, newCommandTimeout: 90000, noReset: true, platformName: android, unicodeKeyboard: true}, appium:deviceApiLevel: 33, appium:deviceManufacturer: Google, appium:deviceModel: Pixel 7 Pro, appium:deviceName: 2B131FDH300167, appium:deviceScreenDensity: 420, appium:deviceScreenSize: 1080x2340, appium:deviceUDID: 2B131FDH300167, appium:javascriptEnabled: true, appium:locationContextEnabled: false, appium:networkConnectionEnabled: true, appium:newCommandTimeout: 90000, appium:noReset: true, appium:pixelRatio: 2.625, appium:platformVersion: 13, appium:statBarHeight: 144, appium:takesScreenshot: true, appium:unicodeKeyboard: true, appium:viewportRect: {height: 2025, left: 0, top: 144, width: 1080}, appium:warnings: {}, appium:webStorageEnabled: false, platformName: ANDROID}
Session ID: 2f8db1f4-5e64-4ece-97a0-37582041434c
	at io.appium.java_client.remote.SupportsContextSwitching.context(SupportsContextSwitching.java:48)
	at Initializer.BaseClass.switchingWebContext(BaseClass.java:101)
	at pages.DeviceTradeInPage.enteringDeviceName(DeviceTradeInPage.java:12)
	at steps.DeviceTradeInSteps.theUserProceedsWithAllMandatorySelectionForDeviceTradeInAndSubmitsTheTransaction(DeviceTradeInSteps.java:14)
	at ✽.the user proceeds with all mandatory selection for Device Trade In and submits the transaction(src/test/java/features/DeviceTradeIn.feature:15)
Caused by: org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: '4.8.1', revision: '8ebccac989'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '11.5', java.version: '16.0.2'
Driver info: io.appium.java_client.android.AndroidDriver
Command: [2f8db1f4-5e64-4ece-97a0-37582041434c, switchToContext {name=WEBVIEW_com.vzbusiness}]
Capabilities {appium:-session-override: true, appium:AndroidVersion: 13, appium:appActivity: com.vzbusiness.ui.login.Lau..., appium:appPackage: com.vzbusiness, appium:automationName: UiAutomator2, appium:chromedriverExecutable: /Users/MPR36B5/Downloads/ch..., appium:clearSystemFiles: true, appium:databaseEnabled: false, appium:desired: {-session-override: true, AndroidVersion: 13, appActivity: com.vzbusiness.ui.login.Lau..., appPackage: com.vzbusiness, automationName: UiAutomator2, chromedriverExecutable: /Users/MPR36B5/Downloads/ch..., clearSystemFiles: true, deviceName: 2B131FDH300167, newCommandTimeout: 90000, noReset: true, platformName: android, unicodeKeyboard: true}, appium:deviceApiLevel: 33, appium:deviceManufacturer: Google, appium:deviceModel: Pixel 7 Pro, appium:deviceName: 2B131FDH300167, appium:deviceScreenDensity: 420, appium:deviceScreenSize: 1080x2340, appium:deviceUDID: 2B131FDH300167, appium:javascriptEnabled: true, appium:locationContextEnabled: false, appium:networkConnectionEnabled: true, appium:newCommandTimeout: 90000, appium:noReset: true, appium:pixelRatio: 2.625, appium:platformVersion: 13, appium:statBarHeight: 144, appium:takesScreenshot: true, appium:unicodeKeyboard: true, appium:viewportRect: {height: 2025, left: 0, top: 144, width: 1080}, appium:warnings: {}, appium:webStorageEnabled: false, platformName: ANDROID}
Session ID: 2f8db1f4-5e64-4ece-97a0-37582041434c
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:567)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:598)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:267)
	at io.appium.java_client.remote.SupportsContextSwitching.context(SupportsContextSwitching.java:45)
	at Initializer.BaseClass.switchingWebContext(BaseClass.java:101)
	at pages.DeviceTradeInPage.enteringDeviceName(DeviceTradeInPage.java:12)
	at steps.DeviceTradeInSteps.theUserProceedsWithAllMandatorySelectionForDeviceTradeInAndSubmitsTheTransaction(DeviceTradeInSteps.java:14)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at cucumber.runtime.Utils$1.call(Utils.java:26)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.Utils.invoke(Utils.java:20)
	at cucumber.runtime.java.JavaStepDefinition.execute(JavaStepDefinition.java:57)
	at cucumber.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:50)
	at cucumber.runner.TestStep.executeStep(TestStep.java:63)
	at cucumber.runner.TestStep.run(TestStep.java:49)
	at cucumber.runner.PickleStepTestStep.run(PickleStepTestStep.java:43)
	at cucumber.runner.TestCase.run(TestCase.java:44)
	at cucumber.runner.Runner.runPickle(Runner.java:40)
	at cucumber.api.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:65)
	at cucumber.api.testng.AbstractTestNGCucumberTests.runScenario(AbstractTestNGCucumberTests.java:22)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:766)
	at org.testng.TestRunner.run(TestRunner.java:587)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
	at org.testng.TestNG.runSuites(TestNG.java:1039)
	at org.testng.TestNG.run(TestNG.java:1007)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.io.UncheckedIOException: org.asynchttpclient.exception.RemotelyClosedException: Remotely closed
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:73)
	at io.appium.java_client.AppiumUserAgentFilter.lambda$apply$0(AppiumUserAgentFilter.java:88)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:49)
	at io.appium.java_client.AppiumUserAgentFilter.lambda$apply$0(AppiumUserAgentFilter.java:88)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
	at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:99)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:181)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:262)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	... 50 more
Caused by: org.asynchttpclient.exception.RemotelyClosedException: Remotely closed
	at org.asynchttpclient.exception.RemotelyClosedException.INSTANCE(Unknown Source)

--------------------------------------------------

**Comment by Prawin06** [comment]
Plz help me in resolving this issue..Got held up here for a while

**Comment by mykola-mokhnach** [comment]
We do not support or maintain Appium 1. Please upgrade to the latest driver version and provide the updated log

**Comment by Prawin06** [comment]
For project reasons we are sticking to Appium 1...Due to this we can't update to Appium2..

Also can u plz let me know the reason why we are getting "io.appium.java_client.NoSuchContextException: Error communicating with the remote browser. It may have died" error in appium

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
