### ISSUE TITLE
bug: XPATH issues on iOS

### ISSUE THREAD

**Issue by nicodn** [appium/appium#19519]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We're working to complete the migration from Appium `1.22.3` to `2.0.1` and have noticed unstable behavior with some of our existing Xpath locators:

Eg `By.xpath("//*[@label='NHL']")` -> does not find anything on a page with at least 2 elements that should match. Appium `1.22.3` would find these elements without issue.

These can also be found using the Appium Inspector and using the Accessibility Inspector.

Appium 2 returns the error:

```
2023-12-11 16:15:53:139 [HTTP] --> POST /session/0a658a4e-9dce-453a-a5c2-2f163d3ef11b/element
2023-12-11 16:15:53:139 [HTTP] {"using":"xpath","value":"//*[@label='NHL']"}
2023-12-11 16:15:53:139 [XCUITestDriver@da40 (0a658a4e)] Calling AppiumDriver.findElement() with args: ["xpath","//*[@label='NHL']","0a658a4e-9dce-453a-a5c2-2f163d3ef11b"]
2023-12-11 16:15:53:139 [XCUITestDriver@da40 (0a658a4e)] Executing command 'findElement'
2023-12-11 16:15:53:139 [XCUITestDriver@da40 (0a658a4e)] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id, css selector
2023-12-11 16:15:53:139 [XCUITestDriver@da40 (0a658a4e)] Waiting up to 0 ms for condition
2023-12-11 16:15:53:139 [XCUITestDriver@da40 (0a658a4e)] Matched '/element' to command name 'findElement'
2023-12-11 16:15:53:140 [XCUITestDriver@da40 (0a658a4e)] Proxying [POST /element] to [POST http://127.0.0.1:60194/session/075F7BEC-A782-4817-B652-3862BB9E379C/element] with body: {"using":"xpath","value":"//*[@label='NHL']"}
2023-12-11 16:15:53:968 [XCUITestDriver@da40 (0a658a4e)] Got response with status 404: {"value":{"error":"no such element","message":"unable to find an element using 'xpath', value '//*[@label='NHL']'","traceback":"(\n\t0   WebDriverAgentLib                   0x000000010ba70d68 FBNoSuchElementErrorResponseForRequest + 252\n\t1   WebDriverAgentLib                   0x000000010ba70b98 +[FBFindElementCommands handleFindElement:] + 312\n\t2   WebDriverAgentLib                   0x000000010ba355f0 -[FBRoute_TargetAction mountRequest:intoResponse:] + 168\n\t3   WebDriverAgentLib                   0x000000010ba2042c __37-[FBWebServer registerRouteHandlers:]_block_invoke + 404\n\t4   WebDriverAgentLib                   0x000000010ba57468 -[RoutingHTTPServer handleRoute:withRequest:response:] + 168\n\t5   WebDriverAgentLib                   0x000000010ba57f58 __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 64\n\t6   libdispatch.dylib                   0x0000000180135768 _dispatch_client_callout + 16\n\t7   libdispatch.dylib                   0x0000000180146...
2023-12-11 16:15:53:974 [W3C] Matched W3C error code 'no such element' to NoSuchElementError
2023-12-11 16:15:53:988 [XCUITestDriver@da40 (0a658a4e)] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
2023-12-11 16:15:53:988 [XCUITestDriver@da40 (0a658a4e)]     at XCUITestDriver.doNativeFind (/Users/nicodn/.appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:143:13)
2023-12-11 16:15:53:988 [XCUITestDriver@da40 (0a658a4e)]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-12-11 16:15:53:988 [XCUITestDriver@da40 (0a658a4e)]     at XCUITestDriver.findNativeElementOrElements (/Users/nicodn/.appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:97:12)
2023-12-11 16:15:53:988 [XCUITestDriver@da40 (0a658a4e)]     at XCUITestDriver.findElOrEls (/Users/nicodn/.appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:24:14)
2023-12-11 16:15:53:988 [XCUITestDriver@da40 (0a658a4e)]     at XCUITestDriver.findElOrElsWithProcessing (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:60:12)
2023-12-11 16:15:53:989 [XCUITestDriver@da40 (0a658a4e)]     at XCUITestDriver.findElement (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:75:12)
```

### Expected Behavior

List of locators tried on Appium 2:
- `By.xpath("//*[@label='NHL']")` -> not found
- `By.xpath("//*[text()='NHL']")` -> not found
- `By.xpath("//*[contains(@label, 'NHL')]")` -> not found
- `By.xpath("//XCUIElementTypeButton[@label='NHL']")` -> not found
- `By.xpath("//*")` -> then iterate all of these and `.getAttribute("label")` finds both elements, but as you know this is not an acceptable approach due to the number of requests required
- `By.xpath("//XCUIElementTypeStaticText[@label='NHL']")` -> finds one of the elements:

```
2023-12-11 16:15:54:777 [HTTP] --> POST /session/0a658a4e-9dce-453a-a5c2-2f163d3ef11b/element
2023-12-11 16:15:54:777 [HTTP] {"using":"xpath","value":"//XCUIElementTypeStaticText[@label='NHL']"}
2023-12-11 16:15:54:777 [XCUITestDriver@da40 (0a658a4e)] Calling AppiumDriver.findElement() with args: ["xpath","//XCUIElementTypeStaticText[@label='NHL']","0a658a4e-9dce-453a-a5c2-2f163d3ef11b"]
2023-12-11 16:15:54:777 [XCUITestDriver@da40 (0a658a4e)] Executing command 'findElement'
2023-12-11 16:15:54:777 [XCUITestDriver@da40 (0a658a4e)] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id, css selector
2023-12-11 16:15:54:777 [XCUITestDriver@da40 (0a658a4e)] Waiting up to 0 ms for condition
2023-12-11 16:15:54:777 [XCUITestDriver@da40 (0a658a4e)] Matched '/element' to command name 'findElement'
2023-12-11 16:15:54:777 [XCUITestDriver@da40 (0a658a4e)] Proxying [POST /element] to [POST http://127.0.0.1:60194/session/075F7BEC-A782-4817-B652-3862BB9E379C/element] with body: {"using":"xpath","value":"//XCUIElementTypeStaticText[@label='NHL']"}
2023-12-11 16:15:55:773 [XCUITestDriver@da40 (0a658a4e)] Got response with status 200: {"value":{"ELEMENT":"E5000000-0000-0000-855B-000000000000","element-6066-11e4-a52e-4f735466cecf":"E5000000-0000-0000-855B-000000000000"},"sessionId":"075F7BEC-A782-4817-B652-3862BB9E379C"}
2023-12-11 16:15:55:776 [XCUITestDriver@da40 (0a658a4e)] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"E5000000-0000-0000-855B-000000000000","ELEMENT":"E5000000-0000-0000-855B-000000000000"}
2023-12-11 16:15:55:779 [HTTP] <-- POST /session/0a658a4e-9dce-453a-a5c2-2f163d3ef11b/element 200 1001 ms - 137
```

### Minimal Reproducible Example

The element shows up in the xpath:

```
...
<XCUIElementTypeButton type="XCUIElementTypeButton" name="com.thescore.sports_list_item_cell" label="NHL" enabled="true" visible="true" accessible="true" x="0" y="243" width="390" height="60" index="3">
                                    <XCUIElementTypeOther type="XCUIElementTypeOther" name="com.thescore.background_view" enabled="true" visible="false" accessible="false" x="0" y="243" width="390" height="60" index="0">
                                      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" accessible="false" x="0" y="243" width="390" height="60" index="0"/>
                                    </XCUIElementTypeOther>
                                    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" accessible="false" x="0" y="243" width="390" height="60" index="1">
                                      <XCUIElementTypeImage type="XCUIElementTypeImage" name="com.thescore.sports_list_item_cell.league_icon" enabled="true" visible="true" accessible="false" x="16" y="259" width="28" height="28" index="0"/>
                                      <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" value="NHL" name="com.thescore.sports_list_item_cell.title" label="NHL" enabled="true" visible="true" accessible="false" x="60" y="262" width="32" height="22" index="1"/>
                                    </XCUIElementTypeOther>
                                    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" accessible="false" x="0" y="302" width="390" height="1" index="2"/>
                                  </XCUIElementTypeButton>
...
```

### Environment

- Operating system: `macOS 14.0`
- Appium server version (output of `appium --version`): `2.0.1`
- Appium driver(s) and their version(s): `xcuitest@4.35.0 [installed (npm)]`
- Appium plugin(s) and their version(s): N/A
- Node.js version (output of `node --version`): `v20.3.1`
- `npm` version (output of `npm --version`): `9.6.7`
- Last component(s) version which did _not_ exhibit the problem: `1.22.3`
- Platform and version under test: `iOS 16.0`
- Real device or emulator/simulator: Simulator

### Further Information

While I was able to get an alternative working locator, troubleshooting these unexpected locators issues throughout the framework as we look to upgrade is not desirable.
We also look to prefer `id` / accessibility ID locators wherever possible, but in some places our team has found xpath to be the most reliable, so I'm trying to fix the backwards compatibility here.

Hoping to get any clues or pointers to known issues or capabilities that might have changed that we need to investigate 🙏

**Comment by nicodn** [comment]
Will try again with xcuitest `5.12.1`. thanks
