### ISSUE TITLE
bug: `remoteAdbHost` not being set for switching Webview context.

### ISSUE THREAD

**Issue by aerfafish** [appium/appium#19533]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

2023-12-15 10:35:53:950 - [AndroidUiautomator2Driver@cc96 (1e916462)] [AndroidUiautomator2Driver@cc96 (1e916462)] Replacing sessionId 41645aca-75aa-4320-8ac6-17514ed9bc5b with 1e916462-1d70-426d-8bb2-704d5c6d2456
2023-12-15 10:35:53:953 - [HTTP] [HTTP] <-- GET /wd/hub/session/1e916462-1d70-426d-8bb2-704d5c6d2456/source 200 295 ms - 49778
2023-12-15 10:35:53:953 - [HTTP] [HTTP]
2023-12-15 10:35:53:958 - [HTTP] [HTTP] --> POST /wd/hub/session/1e916462-1d70-426d-8bb2-704d5c6d2456/context
2023-12-15 10:35:53:958 - [HTTP] [HTTP] {"name":"WEBVIEW_com.huawei.browser"}
2023-12-15 10:35:53:959 - [debug] [AndroidUiautomator2Driver@cc96 (1e916462)] [AndroidUiautomator2Driver@cc96 (1e916462)] Calling AppiumDriver.setContext() with args: ["WEBVIEW_com.huawei.browser","1e916462-1d70-426d-8bb2-704d5c6d2456"]
2023-12-15 10:35:53:960 - [debug] [AndroidDriver] [AndroidDriver] Getting a list of available webviews
2023-12-15 10:35:53:960 - [debug] [ADB] [ADB] Running '/root/platform-tools/adb -H mqc-agent -P 5037 -s GBB0220B03000150 shell cat /proc/net/unix'
2023-12-15 10:35:53:989 - [debug] [AndroidDriver] [AndroidDriver] Parsed 1 active devtools socket: ["@huawei_webview_devtools_remote_4979"]
2023-12-15 10:35:53:990 - [debug] [AndroidDriver] [AndroidDriver] Collecting CDP data of 1 webview
2023-12-15 10:35:53:991 - [debug] [AndroidDriver] [AndroidDriver] Forwarding remote port huawei_webview_devtools_remote_4979 to a local port in range 10900..11000
2023-12-15 10:35:53:991 - [debug] [AndroidDriver] [AndroidDriver] You could use the 'webviewDevtoolsPort' capability to customize the starting port number
2023-12-15 10:35:53:994 - [debug] [ADB] [ADB] Running '/root/platform-tools/adb -H mqc-agent -P 5037 -s GBB0220B03000150 forward tcp:10900 localabstract:huawei_webview_devtools_remote_4979'
2023-12-15 10:35:54:009 - [debug] [AndroidDriver] [AndroidDriver] Error: connect ECONNREFUSED 127.0.0.1:10900
2023-12-15 10:35:54:009 - [debug] [AndroidDriver] [AndroidDriver]     at Function.AxiosError.from (/root/.appium/node_modules/appium-uiautomator2-driver/node_modules/axios/lib/core/AxiosError.js:89:14)
2023-12-15 10:35:54:010 - [debug] [AndroidDriver] [AndroidDriver]     at RedirectableRequest.handleRequestError (/root/.appium/node_modules/appium-uiautomator2-driver/node_modules/axios/lib/adapters/http.js:577:25)
2023-12-15 10:35:54:010 - [debug] [AndroidDriver] [AndroidDriver]     at RedirectableRequest.emit (node:events:525:35)
2023-12-15 10:35:54:010 - [debug] [AndroidDriver] [AndroidDriver]     at ClientRequest.eventHandlers.<computed> (/root/.appium/node_modules/appium-uiautomator2-driver/node_modules/follow-redirects/index.js:14:24)
2023-12-15 10:35:54:010 - [debug] [AndroidDriver] [AndroidDriver]     at ClientRequest.emit (node:events:513:28)
2023-12-15 10:35:54:010 - [debug] [AndroidDriver] [AndroidDriver]     at Socket.socketErrorListener (node:_http_client:488:9)
2023-12-15 10:35:54:010 - [debug] [AndroidDriver] [AndroidDriver]     at Socket.emit (node:events:513:28)
2023-12-15 10:35:54:010 - [debug] [AndroidDriver] [AndroidDriver]     at emitErrorNT (node:internal/streams/destroy:151:8)
2023-12-15 10:35:54:010 - [debug] [AndroidDriver] [AndroidDriver]     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
2023-12-15 10:35:54:010 - [debug] [AndroidDriver] [AndroidDriver]     at processTicksAndRejections (node:internal/process/task_queues:82:21)
2023-12-15 10:35:54:010 - [debug] [ADB] [ADB] Removing forwarded port socket connection: 10900
2023-12-15 10:35:54:010 - [debug] [ADB] [ADB] Running '/root/platform-tools/adb -H mqc-agent -P 5037 -s GBB0220B03000150 forward --remove tcp:10900'
2023-12-15 10:35:54:016 - [debug] [AndroidDriver] [AndroidDriver] CDP data collection completed
2023-12-15 10:35:54:016 - [debug] [AndroidDriver] [AndroidDriver] WEBVIEW_4979 mapped to pid 4979

### Expected Behavior

connect adbRemoteHost:10900 instead of 127.0.0.1:10900

### Minimal Reproducible Example

set adbRemoteHost then execute
self.driver.switch_to.context(context)

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by mykola-mokhnach** [comment]
> 2023-12-15 10:35:53:994 - [debug] [ADB] [ADB] Running '/root/platform-tools/adb -H mqc-agent -P 5037 -s GBB0220B03000150 forward tcp:10900 localabstract:huawei_webview_devtools_remote_4979'

I can observe that the `-H` argument is set properly. 
Not sure how the 

> connect adbRemoteHost:10900 instead of 127.0.0.1:10900

expectation can be represented as a valid adb command though. Have you actually tried to run it manually?

**Comment by aerfafish** [comment]
> Error: connect ECONNREFUSED 127.0.0.1:10900

"I think -H is effective. It successfully listens on the forward port, but this port is listened on remotely. However, the driver tries to connect to 127.0.0.1:10900. I believe it should connect to the remote 10900.

**Comment by mykola-mokhnach** [comment]
> > Error: connect ECONNREFUSED 127.0.0.1:10900
> 
> "I think -H is effective. It successfully listens on the forward port, but this port is listened on remotely. However, the driver tries to connect to 127.0.0.1:10900. I believe it should connect to the remote 10900.

This makes sense to me. Could you please check if https://github.com/appium/appium-android-driver/pull/890 fixes the issue?
