### ISSUE TITLE
bug: images plugin not loaded

### ISSUE THREAD

**Issue by RSM-SBA** [appium/appium#19555]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

updated the latest appium version to 2.3.0 and images plugin to 3.0.0 and the plugin is not found

ℹ Driver uiautomator2@2.35.0 successfully installed
- automationName: UiAutomator2
- platformNames: ["Android"]
✔ Installing 'images' using NPM install spec '@appium/images-plugin'
ℹ Plugin images@3.0.0 successfully installed

Process output: Fatal Error: Could not load the plugin 'images' because it is not installed. Only the following plugins are available: 
    at getActivePlugins (/Users/xx.yy/git/rs-android-uitesting-java/node_modules/appium/lib/extension/index.js:102:15)
    at main (/Users/xx.yy/git/rs-android-uitesting-java/node_modules/appium/lib/main.js:342:47)

### Expected Behavior

images plugin could be found

### Minimal Reproducible Example

Occurs with Android Tests also as with iOS tests.
installed appium, driver and plugins to a custom appiumHome
started a test 

### Environment

- Operating system: Mac OS Sonoma
- Appium server version (output of `appium --version`): 2.3.0
- Appium driver(s) and their version(s): UiAutomator2 2.35.0
- Appium plugin(s) and their version(s): images 3.0.0
- Node.js version (output of `node --version`): 20.10.0
- `npm` version (output of `npm --version`): 10.2.3
- Last component(s) version which did _not_ exhibit the problem: 
    "appium": "^2.0.0"
    "@appium/images-plugin": "^2.1.2",
    "appium-uiautomator2-driver": "^2.29.2"

- Platform and version under test: MacOS 
- Real device or emulator/simulator: Simulator

**Comment by RSM-SBA** [comment]
was a fault on my site, system variable was not set correctly appium _home
