### ISSUE TITLE
Cannot push file into com.apple.mobileslideshow in real iOS App

### ISSUE THREAD

**Issue by luckhiem** [appium/appium#19581]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
Calling AppiumDriver.execute() with args: ["mobile: pushFile",[{"remotePath":"@com.apple.mobileslideshow/qr.png","payload":"iVBORw0KGgoAAAANSUhEUgAABQQAAAraEAIAAACLEFs5AAABdWlDQ1BrQ0dDb2xvclNwYWNlRGlzcGxheVAzAAAokXWQvUvDUBTFT6tS0DqIDh0cMolD1NIKdnFoKxRFMFQFq1OafgltfCQpUnETVyn4H1jBWXCwiFRwcXAQRAcR3Zw6KbhoeN6XVNoi3sfl/Ticc7lcwBtQGSv2AijplpFMxKS11Lrke4OHnlOqZrKooiwK/v276/PR9d5PiFlNu3YQ2U9cl84ul3aeAlN//V3Vn8maGv3f1EGNGRbgkYmVbYsJ3iUeMWgp4qrgvMvHgtMunzuelWSc+JZY0gpqhrhJLKc79HwHl4plrbWD2N6f1VeXxRzqUcxhEyYYilBRgQQF4X/8044/ji1yV2BQLo8CLMpESRETssTz0KFhEjJxCEHqkLhz634PrfvJbW3vFZhtcM4v2tpCAzidoZPV29p4BBgaAG7qTDVUR+qh9uZywPsJMJgChu8os2HmwiF3e38M6Hvh/GMM8B0CdpXzryPO7RqFn4Er/QcXKWq8UwZBywAAQABJREFUeAHs3QucXGVhN/5NgBC5LggSEZgVQaMirooQED0LAuaebd9q/b9eZqsCEVHXamu01klbRbTou1qktl7OoiB47YIoeD0LBgiCuAiBcDFnIVwi4bKGAAGE+Yc89uNph9mcvWb2zLd8PuvpM888l+9zZjIzv3NpeaJ0d3lJn78ECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgUFSBlqJOzLwIECBAgAABAgQIECBAgAABAgQIECBAgAABAgQIECBAIAgIhp0tTYAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAgYILCIYLvsCOgCBAgAABAgQIECBAgAABAgQIECBAgAABAgQIECBAgIBgWDBMgAA...
[XCUITestDriver@ee67 (a37cafd0)] Executing command 'execute'
[XCUITestDriver@ee67 (a37cafd0)] Encountered internal error running command: Error: Failed to vend into the application container. Error: InstallationLookupFailed
[XCUITestDriver@ee67 (a37cafd0)]     at HouseArrestService.vendContainer (/Users/khiemluc/node_modules/appium-xcuitest-driver/node_modules/appium-ios-device/lib/house-arrest/index.js:47:13)
[XCUITestDriver@ee67 (a37cafd0)]     at createAfcClient (/Users/khiemluc/node_modules/appium-xcuitest-driver/lib/commands/file-movement.js:72:7)
[XCUITestDriver@ee67 (a37cafd0)]     at createService (/Users/khiemluc/node_modules/appium-xcuitest-driver/lib/commands/file-movement.js:82:21)
[XCUITestDriver@ee67 (a37cafd0)]     at pushFileToRealDevice (/Users/khiemluc/node_modules/appium-xcuitest-driver/lib/commands/file-movement.js:161:35)
[XCUITestDriver@ee67 (a37cafd0)]     at XCUITestDriver.pushFile (/Users/khiemluc/node_modules/appium-xcuitest-driver/lib/commands/file-movement.js:367:9)
[XCUITestDriver@ee67 (a37cafd0)]     at XCUITestDriver.mobilePushFile (/Users/khiemluc/node_modules/appium-xcuitest-driver/lib/commands/file-movement.js:379:12)
[XCUITestDriver@ee67 (a37cafd0)]     at XCUITestDriver.executeMethod (/Users/khiemluc/node_modules/@appium/base-driver/lib/basedriver/commands/execute.ts:36:12)
[XCUITestDriver@ee67 (a37cafd0)]     at XCUITestDriver.execute (/Users/khiemluc/node_modules/appium-xcuitest-driver/lib/commands/execute.js:118:14)
[HTTP] <-- POST /session/a37cafd0-899e-4693-9c23-67e33fbcb507/execute/sync 500
```

### Expected Behavior

Can upload photo file

### Minimal Reproducible Example

```
 ((PushesFiles) getDriver()).pushFile("@com.apple.mobileslideshow/qr.png", new File("/Users/user1/qr.png"));
```

### Environment

- Operating system:
- Appium server version (output of `appium --version`): 2.2.2
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by KazuCocoa** [comment]
Does the app has `UIFileSharingEnabled` flag?

https://appium.github.io/appium-xcuitest-driver/5.12/execute-methods/#mobile-listapps
https://github.com/appium/appium-xcuitest-driver/blob/master/docs/ios-xctest-file-movement.md#real-device

https://github.com/appium/appium/issues/16409

https://developer.apple.com/documentation/bundleresources/information_property_list/uifilesharingenabled?language=objc

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
