### ISSUE TITLE
driver.get_window_size() not work on some iOS devices

### ISSUE THREAD

**Issue by zhu-xiaowei** [appium/appium#19640]
appium version: v2.3.0
xcuitest version: v5.13.1
failed devices: 
iPhone 14 Pro  iOS 16.1
Apple iPhone 14 Pro Max  iOS16.0

The error log is:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/shopping_ios_test.py:86: in scroll_down_half_screen
    window_size = self.driver.get_window_size()
/Users/device-farm/.pyenv/versions/3.10.6/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:877: in get_window_size
    size = self.get_window_rect()
/Users/device-farm/.pyenv/versions/3.10.6/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:927: in get_window_rect
    return self.execute(Command.GET_WINDOW_RECT)["value"]
/Users/device-farm/.pyenv/versions/3.10.6/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:348: in execute
    self.error_handler.check_response(response)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = &lt;appium.webdriver.errorhandler.MobileErrorHandler object at 0x10912ab00&gt;
response = {'status': 404, 'value': '{"value":{"error":"stale element reference","message":"The previously found element \\"Appli...iver.getWindowRect (/Users/device-farm/.appium/node_modules/appium-xcuitest-driver/lib/commands/general.js:121:29)"}}'}

    def check_response(self, response: Dict[str, Any]) -&gt; None:
        """
        https://www.w3.org/TR/webdriver/#errors
        """
        payload = response.get('value', '')
        if isinstance(payload, dict):
            payload_dict = payload
        else:
            try:
                payload_dict = json.loads(payload)
            except (json.JSONDecodeError, TypeError):
                return
            if not isinstance(payload_dict, dict):
                return
        value = payload_dict.get('value')
        if not isinstance(value, dict):
            return
        error = value.get('error')
        if not error:
            return
    
        message = value.get('message', error)
        stacktrace = value.get('stacktrace', '')
        # In theory, we should also be checking HTTP status codes.
        # Java client, for example, prints a warning if the actual `error`
        # value does not match to the response's HTTP status code.
        exception_class: Type[sel_exceptions.WebDriverException] = ERROR_TO_EXC_MAPPING.get(
            error, sel_exceptions.WebDriverException
        )
        if exception_class is sel_exceptions.WebDriverException and message:
            if message == 'No such context found.':
                exception_class = appium_exceptions.NoSuchContextException
            elif message == 'That command could not be executed in the current context.':
                exception_class = appium_exceptions.InvalidSwitchToTargetException
    
        if exception_class is sel_exceptions.UnexpectedAlertPresentException:
            raise sel_exceptions.UnexpectedAlertPresentException(
                msg=message,
                stacktrace=format_stacktrace(stacktrace),
                alert_text=value.get('data'),
            )
&gt;       raise exception_class(msg=message, stacktrace=format_stacktrace(stacktrace))
E       selenium.common.exceptions.StaleElementReferenceException: Message: The previously found element "Application 'software.xxxx.ModerneShopping'" is not present in the current view anymore. Make sure the application UI has the expected state. Original error: XCTPerformOnMainRunLoop work timed out after 60.0s; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
E       Stacktrace:
E       StaleElementReferenceError: The previously found element "Application 'software.xxxx.ModerneShopping'" is not present in the current view anymore. Make sure the application UI has the expected state. Original error: XCTPerformOnMainRunLoop work timed out after 60.0s
E           at errorFromW3CJsonCode (/Users/device-farm/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/protocol/errors.js:1059:25)
E           at ProxyRequestError.getActualError (/Users/device-farm/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/protocol/errors.js:928:14)
E           at JWProxy.command (/Users/device-farm/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:353:19)
E           at runMicrotasks (&lt;anonymous&gt;)
E           at processTicksAndRejections (node:internal/process/task_queues:96:5)
E           at XCUITestDriver.proxyCommand (/Users/device-farm/.appium/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:109:35)
E           at XCUITestDriver.getWindowSizeNative (/Users/device-farm/.appium/node_modules/appium-xcuitest-driver/lib/commands/general.js:278:12)
E           at XCUITestDriver.getWindowSize (/Users/device-farm/.appium/node_modules/appium-xcuitest-driver/lib/commands/general.js:52:14)
E           at XCUITestDriver.getWindowRect (/Users/device-farm/.appium/node_modules/appium-xcuitest-driver/lib/commands/general.js:121:29)

/Users/device-farm/.pyenv/versions/3.10.6/lib/python3.10/site-packages/appium/webdriver/errorhandler.py:125: StaleElementReferenceException</failure></testcase></testsuite></testsuites>

**Comment by KazuCocoa** [comment]
Could you sahre the full appium server log as well?

**Comment by mykola-mokhnach** [comment]
Duplicate of https://github.com/appium/appium/issues/16379

The error itself is thrown by XCTest and there is nothing we can do about it. It is obviously not documented, but according to the description it looks like the app under test is locking the main thread for too long, so XCTest is unable to use it and run any actions. Consider changing your app code, so it idles enough time as a possible workaround.

Closed as duplicate
