### ISSUE TITLE
Crash on Compose Material3 alpha12

### ISSUE THREAD

**Issue by MiladVS** [appium/appium#19679]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Since the Android App updated from "androidx.compose.material3:material3:1.2.0-alpha11" to "androidx.compose.material3:material3:1.2.0-alpha12" (we even tried with beta2 "latest version") we are getting a crash when we try to find an XPath, we already adjusted our capabilities like shown below 
java.lang.IllegalArgumentException occurs: 

Got response with status 500: {"id":"5b3d0e90-206a-4c3e-bd55-7d0cd0460d63","sessionId":"92471bbf-5f9c-4d45-ac07-0e97c33a3e4c","value":{"error":"unknown error","message":"java.lang.IllegalArgumentException: Callable expects 4 arguments, but 3 were provided.","stacktrace":"java.lang.IllegalArgumentException: Callable expects 4 arguments, but 3 were provided.\n\tat kotlin.reflect.jvm.internal.calls.Caller$DefaultImpls.checkArguments(Caller.kt:20)\n\tat kotlin.reflect.jvm.internal.calls.CallerImpl.checkArguments(CallerImpl.kt:15)\n\tat kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:112)\n\tat kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)\n\tat io.appium.espressoserver.lib.model.SourceDocument.rootSemanticNodes(SourceDocument.kt:342)\n\tat io.appium.espressoserver.lib.model.SourceDocument.toStream(SourceDocument.kt:289)\n\tat io.appium.espressoserver.lib.model.SourceDocument.access$toStream(SourceDocument.kt:90)\n\tat io.appium.espressoserver.lib.model.SourceDocument$toXMLString$1.invo...

Logcat: 
Responding to server with error: {error=unknown error, message=java.lang.IllegalArgumentException: Callable expects 4 arguments, but 3 were provided., stacktrace=java.lang.IllegalArgumentException: Callable expects 4 arguments, but 3 were provided.
01-19 10:21:26.584 23116 24316 I appium  : 	at kotlin.reflect.jvm.internal.calls.Caller$DefaultImpls.checkArguments(Caller.kt:20)
01-19 10:21:26.584 23116 24316 I appium  : 	at kotlin.reflect.jvm.internal.calls.CallerImpl.checkArguments(CallerImpl.kt:15)
01-19 10:21:26.584 23116 24316 I appium  : 	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:112)
01-19 10:21:26.584 23116 24316 I appium  : 	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
01-19 10:21:26.584 23116 24316 I appium  : 	at io.appium.espressoserver.lib.model.SourceDocument.rootSemanticNodes(SourceDocument.kt:342)
01-19 10:21:26.584 23116 24316 I appium  : 	at io.appium.espressoserver.lib.model.SourceDocument.toStream(SourceDocument.kt:289)
01-19 10:21:26.584 23116 24316 I appium  : 	at io.appium.espressoserver.lib.model.SourceDocument.access$toStream(SourceDocument.kt:90)
01-19 10:21:26.584 23116 24316 I appium  : 	at io.appium.espressoserver.lib.model.SourceDocument$toXMLString$1.invoke(SourceDocument.kt:356)
01-19 10:21:26.584 23116 24316 I appium  : 	at io.appium.espressoserver.lib.model.SourceDocument$toXMLString$1.invoke(SourceDocument.kt:355)
01-19 10:21:26.584 23116 24316 I appium  : 	at io.appium.espressoserver.lib.helpers.extensions.SemaphoreKt.withPermit(Semaphore.kt:17)
01-19 10:21:26.584 23116 24316 I appium  : 	at io.appium.espressoserver.lib.model.SourceDocument.toXMLString(SourceDocument.kt:355)
01-19 10:21:26.584 23116 24316 I appium  : 	at io.appium.espressoserver.lib.handlers.Source.handleInternal(Source.kt:27)
01-19 10:21:26.584 23116 24316 I appium  : 	at io.appium.espressoserver.lib.handlers.Source.handleInternal(Source.kt:23)
01-19 10:21:26.584 23116 24316 I appium  : 	at io.appium.espressoserver.lib.handlers.RequestHandler$DefaultImpls.handle(RequestHandler.kt:57)
01-19 10:21:26.584 23116 24316 I appium  : 	at io.appium.espressoserver.lib.handlers.Source.handle(Source.kt:23)
01-19 10:21:26.584 23116 24316 I appium  : 	at io.appium.espressoserver.lib.handlers.Source.handle(Source.kt:23)
01-19 10:21:26.584 23116 24316 I appium  : 	at io.appium.espressoserver.lib.http.Router.route(Router.kt:231)
01-19 10:21:26.584 23116 24316 I appium  : 	at io.appium.espressoserver.lib.http.Server.serve(Server.kt:54)
01-19 10:21:26.584 23116 24316 I appium  : 	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)
01-19 10:21:26.584 23116 24316 I appium  : 	at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
01-19 10:21:26.584 23116 24316 I appium  : 	at java.lang.Thread.run(Thread.java:920)
01-19 10:21:26.584 23116 24316 I appium  : }

### Expected Behavior

Searching/clicking for XPath shouldn't throw a java.lang.IllegalArgumentException from the server site

### Minimal Reproducible Example

Espresso Build:
{
  "platformName": "ANDROID",
  "appium:app": "our_url",
  "appium:appWaitActivity": "*",
  "appium:automationName": "Espresso",
  "appium:deviceName": "Pixel_XL_API_32",
  "appium:espressoBuildConfig": "{\"additionalAndroidTestDependencies\":[\"androidx.lifecycle:lifecycle-viewmodel-compose:2.6.2\",\"androidx.compose.material3:material3:1.2.0-alpha12\",\"androidx.activity:activity-compose:1.8.1\",\"androidx.activity:activity-ktx:1.8.1\"],\"toolsVersions\":{\"gradle\":\"8.0.2\",\"targetCompatibility\":\"VERSION_17\",\"minSdk\":24,\"composeVersion\":\"1.5.5\",\"kotlin\":\"1.9.20\",\"jvmTarget\":\"17\",\"targetSdk\":34,\"sourceCompatibility\":\"VERSION_17\",\"compileSdk\":\"34\"}}",
  "appium:forceEspressoRebuild": true,
  "appium:newCommandTimeout": 180,
  "appium:showGradleLog": true,
  "appium:udid": "emulator-5554"
}

Go to a composition layout.

Set the driver to compose: 
{
  "driver": "compose"
}

Search for a XPath: java.lang.IllegalArgumentException

### Environment

- Operating system: MacBook Air
- Appium server version (output of `appium --version`): 2.4.1
- Appium driver(s) and their version(s): Espresso-Driver 2.33.1
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`): 21.5.0
- `npm` version (output of `npm --version`): 10.2.4
- composeVersion: 1.5.5
- Kotlin : 1.9.20
- jvmTarget: 17
- targetSdk: 34
- compileSdk: 34
- Last component(s) version which did _not_ exhibit the problem: androidx.compose.material3:material3:1.2.0-alpha11
- Platform and version under test: 
- Real device or emulator/simulator: Both

### Further Information

Since I'm not 100% sure if it's an Appium or appium-espresso-driver Bug, I opened the bug on the Espresso-driver too:

**Comment by KazuCocoa** [comment]
Do you have a small sample app we could try out?

**Comment by bronik** [comment]
hi everyone
I'm facing the same error: java.lang.IllegalArgumentException: Callable expects 4 arguments, but 3 were provided

after my app upgrade dependencies:
compose 1.4.2 -> 1.6.2
composeCompiler 1.4.2 -> 1.5.10
kotlin 1.8.10 -> 1.9.22

unfortunately I can't provide my app for testing :(

**Comment by KazuCocoa** [comment]
@sravanmedarapu do you have any idea about the `material3`...?

**Comment by bronik** [comment]
@KazuCocoa 
I made small test, maybe it would be interesting for you:

trouble was:
espresso-server 
class: SourceDocument 
line 342: 
it.call(EspressoServerRunnerTest.composeTestRule.onRoot(useUnmergedTree = true), true, null)

I modified line above:
it.call(EspressoServerRunnerTest.composeTestRule.onRoot(useUnmergedTree = true), true, null, true)

and it does the trick. no more crash and everything seems work as expected

any thoughts on this?

**Comment by bronik** [comment]
any updates on this?

**Comment by bronik** [comment]
still facing this issue
any updates?

"kotlin":"1.9.23"
"composeVersion":"1.6.5"

**Comment by mykola-mokhnach** [comment]
I assume this issue has been addresses by @pr4bh4sh in https://github.com/appium/appium-espresso-driver/pull/995

**Comment by pr4bh4sh** [comment]
Yes, my last changes had fixed this issue.
