### ISSUE TITLE
Not able to run test in real device using Appium 1.22.3 and NodeJS 18

### ISSUE THREAD

**Issue by reemadaga** [appium/appium#19682]
### Do I have the most recent component updates?

- [ ] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Webdriver agent fails to install the app in iPhone 10 with iOS 16.7.2.  (Do not see the issue when run in simulator)
Using Appium 1.22.3 with web driverio 8 and Nodejs 18
This is an upgrade from webdriverio 6 to 8
Tests were working fine with wedriverio 6

### Expected Behavior

To be able to run tests in real device with Appium 1.22 and NodeJS 18

### Minimal Reproducible Example

Pasting the capabilities here:
case MobilePlatform.IOS: {
        return [
            {
                platformName: 'iOS',
                'appium:automationName': 'XCUITest',
                'appium:deviceName': DEVICE_NAME,
                'appium:udid': UDID,
                acceptInsecureCerts: true,
                'appium:app': APP_URL,
                'appium:fullReset': false,
                'appium:noReset': true,
                'appium:newCommandTimeout': 300,
                'appium:waitForIdleTimeout': 10,
            },
        ];
    }

### Environment

- Operating system:
- Appium server version (output of `appium --version`): 1.22.3
- Appium driver(s) and their version(s): 3.62.0
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`): v18.18.0
- `npm` version (output of `npm --version`): 9.8.1
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: iOS 16.7.2
- Real device or emulator/simulator: Read device

### Link to Appium Logs

https://gist.github.com/reemadaga/9cc1284e3e614a346214e26546d40402

### Further Information

024-01-20T00:03:48.764Z ERROR webdriver: Request failed with status 500 due to unknown error: An unknown server-side error occurred while processing the command. Original error: Failed to receive any data within the timeout: 5000
[0-0] 2024-01-20T00:03:48.764Z ERROR webdriver: unknown error: An unknown server-side error occurred while processing the command. Original error: Failed to receive any data within the timeout: 5000
[0-0]     at getErrorFromResponseBody (xxx/node_modules/webdriver/build/utils.js:195:12)
[0-0]     at NodeJSRequest._request (xxx/node_modules/webdriver/build/request/index.js:193:23)
[0-0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-0]     at async startWebDriverSession (xxx/node_modules/webdriver/build/utils.js:64:20)
[0-0]     at async WebDriver.newSession (xxx/node_modules/webdriver/build/index.js:19:45)
[0-0]     at async remote (xxx/node_modules/webdriverio/build/index.js:45:22)
[0-0]     at async Runner._startSession (xxx/node_modules/@wdio/runner/build/index.js:224:29)
[0-0]     at async Runner._initSession (xxx/node_modules/@wdio/runner/build/index.js:190:25)
[0-0]     at async Runner.run (xxx/node_modules/@wdio/runner/build/index.js:79:19)
[0-0] 2024-01-20T00:03:48.765Z ERROR @wdio/runner: Error: Failed to create session.
[0-0] An unknown server-side error occurred while processing the command. Original error: Failed to receive any data within the timeout: 5000
[0-0]     at startWebDriverSession (xxx/node_modules/webdriver/build/utils.js:69:15)
[0-0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-0]     at async WebDriver.newSession (xxx/node_modules/webdriver/build/index.js:19:45)
[0-0]     at async remote (xxx/node_modules/webdriverio/build/index.js:45:22)
[0-0]     at async Runner._startSession (xxx/node_modules/@wdio/runner/build/index.js:224:29)
[0-0]     at async Runner._initSession (xxx/node_modules/@wdio/runner/build/index.js:190:25)
[0-0]     at async Runner.run (xxx/node_modules/@wdio/runner/build/index.js:79:19)

**Comment by KazuCocoa** [comment]
Please provide the appium server log. The attached log was webdriverio's log.

**Comment by mykola-mokhnach** [comment]
Appium 1 is not supported anymore and won't work for iOS 15+. Consider using the latest xcuitest supplied with Appium 2.

**Comment by reemadaga** [comment]
I am using Appium-service and starting the server from my tests. How do I upgrade Appium for my package. It is upgrading it globally but still using v1.22.3
