### ISSUE TITLE
bug: Cannot start a session from Appium inspector with Appium server and XCUITest

### ISSUE THREAD

**Issue by ErodriguezQA** [appium/appium#19690]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Appium server throws the following error:
`Encountered internal error running command: Error: Could not find a driver for automationName 'XCUITest' and platformName 'iOS'. Have you installed a driver that supports those capabilities? Run 'appium driver list --installed' to see. (Lower-level error: require() of ES Module /Users/qalified/node_modules/chalk/source/index.js from /Users/qalified/node_modules/@babel/code-frame/lib/index.js not supported.
[AppiumDriver@1af0] Instead change the require of /Users/qalified/node_modules/chalk/source/index.js in /Users/qalified/node_modules/@babel/code-frame/lib/index.js to a dynamic import() which is available in all CommonJS modules.)
[AppiumDriver@1af0]     at DriverConfig.findMatchingDriver (/opt/homebrew/lib/node_modules/appium/lib/extension/driver-config.js:175:13)
[AppiumDriver@1af0]     at AppiumDriver.createSession (/opt/homebrew/lib/node_modules/appium/lib/appium.js:644:11)
`

### Expected Behavior

To start the application succesfully

### Minimal Reproducible Example

{
  "appium:udid": "00008101-00053094213A001E",
  "appium:bundleId": "com.example",
  "appium:deviceName": "iPhone",
  "appium:platformName": "iOS",
  "appium:automationName": "XCUITest",
  "appium:platformVersion": "16.3.1"
}

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

### Further Information

This is the output of the `appium driver list --installed`:
`✔ Listing installed drivers
- xcuitest@5.14.0 [installed (npm)]
`

**Comment by mykola-mokhnach** [comment]
Make sure the Node.JS is up to date (we advice the latest LTS)
Then reinstall the server. To cleanup installed drivers it is necessary to delete the `$HOME/.appium` folder

**Comment by ErodriguezQA** [comment]
I just did all of that but i'm getting the same output.

This is the output of `node -v`:
`v20.11.0`

**Comment by ErodriguezQA** [comment]
```
[Appium] Welcome to Appium v2.4.1 (REV 1c612baa096c69f2fcb221c74e6f5b9979efdcee)
[Appium] The autodetected Appium home path: /Users/qalified/.appium
[Appium] Attempting to load driver xcuitest...
[Appium] Requiring driver at /Users/qalified/.appium/node_modules/appium-xcuitest-driver/build/index.js
[Appium] Could not load driver 'xcuitest', so it will not be available. Error in loading the driver was: require() of ES Module /Users/qalified/node_modules/chalk/source/index.js from /Users/qalified/node_modules/@babel/code-frame/lib/index.js not supported.
[Appium] Instead change the require of /Users/qalified/node_modules/chalk/source/index.js in /Users/qalified/node_modules/@babel/code-frame/lib/index.js to a dynamic import() which is available in all CommonJS modules.
[Appium] Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/qalified/node_modules/chalk/source/index.js from /Users/qalified/node_modules/@babel/code-frame/lib/index.js not supported.
[Appium] Instead change the require of /Users/qalified/node_modules/chalk/source/index.js in /Users/qalified/node_modules/@babel/code-frame/lib/index.js to a dynamic import() which is available in all CommonJS modules.
[Appium]     at Object.<anonymous> (/Users/qalified/node_modules/@babel/code-frame/lib/index.js:9:38)
[Appium]     at Object.<anonymous> (/Users/qalified/node_modules/parse-json/index.js:5:28)
[Appium]     at Object.<anonymous> (/Users/qalified/node_modules/read-pkg/index.js:5:19)
[Appium]     at Object.<anonymous> (/Users/qalified/node_modules/@appium/support/build/lib/fs.js:18:36)
[Appium] Appium REST http interface listener started on http://0.0.0.0:4723
[Appium] You can provide the following URLs in your client code to connect to this server:
[Appium] 	http://127.0.0.1:4723/ (only accessible from the same host)
[Appium] 	http://192.168.1.4:4723/
[Appium] 	http://169.254.56.213:4723/
[Appium] 	http://169.254.134.8:4723/
[Appium] Available drivers:
[Appium]   - xcuitest@5.14.0 (automationName 'XCUITest')
[Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.
[HTTP] --> POST /session
[HTTP] {"capabilities":{"alwaysMatch":{"appium:udid":"00008101-00053094213A001E","appium:bundleId":"com.gia.dev2021","appium:deviceName":"iPhone equipo técnico","platformName":"iOS","appium:automationName":"XCUITest","appium:xcodeOrgId":"6U86FCFMS3","appium:xcodeSigningId":"iPhone Developer","appium:updatedWDABundleId":"qalified.WebDriverAgentRunnerQalified","appium:includeSafariInWebviews":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]},"desiredCapabilities":{"appium:udid":"00008101-00053094213A001E","appium:bundleId":"com.gia.dev2021","appium:deviceName":"iPhone equipo técnico","platformName":"iOS","appium:automationName":"XCUITest","appium:xcodeOrgId":"6U86FCFMS3","appium:xcodeSigningId":"iPhone Developer","appium:updatedWDABundleId":"qalified.WebDriverAgentRunnerQalified","appium:includeSafariInWebviews":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true}}
[AppiumDriver@79e8] Calling AppiumDriver.createSession() with args: [{"appium:udid":"00008101-00053094213A001E","appium:bundleId":"com.gia.dev2021","appium:deviceName":"iPhone equipo técnico","platformName":"iOS","appium:automationName":"XCUITest","appium:xcodeOrgId":"6U86FCFMS3","appium:xcodeSigningId":"iPhone Developer","appium:updatedWDABundleId":"qalified.WebDriverAgentRunnerQalified","appium:includeSafariInWebviews":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},null,{"alwaysMatch":{"appium:udid":"00008101-00053094213A001E","appium:bundleId":"com.gia.dev2021","appium:deviceName":"iPhone equipo técnico","platformName":"iOS","appium:automationName":"XCUITest","appium:xcodeOrgId":"6U86FCFMS3","appium:xcodeSigningId":"iPhone Developer","appium:updatedWDABundleId":"qalified.WebDriverAgentRunnerQalified","appium:includeSafariInWebviews":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]}]
[AppiumDriver@79e8] Event 'newSessionRequested' logged at 1705943722334 (14:15:22 GMT-0300 (Uruguay Standard Time))
[Appium] Attempting to find matching driver for automationName 'XCUITest' and platformName 'iOS'
[Appium] The 'xcuitest' driver was installed and matched caps.
[Appium] Will require it at /Users/qalified/.appium/node_modules/appium-xcuitest-driver
[Appium] Requiring driver at /Users/qalified/.appium/node_modules/appium-xcuitest-driver/build/index.js
[AppiumDriver@79e8] Event 'newSessionStarted' logged at 1705943722341 (14:15:22 GMT-0300 (Uruguay Standard Time))
[AppiumDriver@79e8] Encountered internal error running command: Error: Could not find a driver for automationName 'XCUITest' and platformName 'iOS'. Have you installed a driver that supports those capabilities? Run 'appium driver list --installed' to see. (Lower-level error: require() of ES Module /Users/qalified/node_modules/chalk/source/index.js from /Users/qalified/node_modules/@babel/code-frame/lib/index.js not supported.
[AppiumDriver@79e8] Instead change the require of /Users/qalified/node_modules/chalk/source/index.js in /Users/qalified/node_modules/@babel/code-frame/lib/index.js to a dynamic import() which is available in all CommonJS modules.)
[AppiumDriver@79e8]     at DriverConfig.findMatchingDriver (/opt/homebrew/lib/node_modules/appium/lib/extension/driver-config.js:175:13)
[AppiumDriver@79e8]     at AppiumDriver.createSession (/opt/homebrew/lib/node_modules/appium/lib/appium.js:644:11)
[HTTP] <-- POST /session 500 21 ms - 1646
[HTTP] 
∑©^C[Appium] Received SIGINT - shutting down
[AppiumDriver@79e8] There are no active sessions for cleanup
[HTTP] Waiting until the server is closed
[HTTP] Received server close event
```

**Comment by ErodriguezQA** [comment]
```
[Appium] Welcome to Appium v2.4.1 (REV 1c612baa096c69f2fcb221c74e6f5b9979efdcee)
[Appium] The autodetected Appium home path: /Users/qalified/.appium
[Appium] Attempting to load driver xcuitest...
[Appium] Requiring driver at /Users/qalified/.appium/node_modules/appium-xcuitest-driver/build/index.js
[Appium] Could not load driver 'xcuitest', so it will not be available. Error in loading the driver was: require() of ES Module /Users/qalified/node_modules/chalk/source/index.js from /Users/qalified/node_modules/@babel/code-frame/lib/index.js not supported.
[Appium] Instead change the require of /Users/qalified/node_modules/chalk/source/index.js in /Users/qalified/node_modules/@babel/code-frame/lib/index.js to a dynamic import() which is available in all CommonJS modules.
[Appium] Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/qalified/node_modules/chalk/source/index.js from /Users/qalified/node_modules/@babel/code-frame/lib/index.js not supported.
[Appium] Instead change the require of /Users/qalified/node_modules/chalk/source/index.js in /Users/qalified/node_modules/@babel/code-frame/lib/index.js to a dynamic import() which is available in all CommonJS modules.
[Appium]     at Object.<anonymous> (/Users/qalified/node_modules/@babel/code-frame/lib/index.js:9:38)
[Appium]     at Object.<anonymous> (/Users/qalified/node_modules/parse-json/index.js:5:28)
[Appium]     at Object.<anonymous> (/Users/qalified/node_modules/read-pkg/index.js:5:19)
[Appium]     at Object.<anonymous> (/Users/qalified/node_modules/@appium/support/build/lib/fs.js:18:36)
[Appium] Appium REST http interface listener started on http://0.0.0.0:4723
[Appium] You can provide the following URLs in your client code to connect to this server:
[Appium] 	http://127.0.0.1:4723/ (only accessible from the same host)
[Appium] 	http://192.168.1.4:4723/
[Appium] 	http://169.254.56.213:4723/
[Appium] 	http://169.254.134.8:4723/
[Appium] Available drivers:
[Appium]   - xcuitest@5.14.0 (automationName 'XCUITest')
[Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.
[HTTP] --> POST /session
[HTTP] {"capabilities":{"alwaysMatch":{"appium:udid":"00008101-00053094213A001E","appium:bundleId":"com.gia.dev2021","appium:deviceName":"iPhone equipo técnico","platformName":"iOS","appium:automationName":"XCUITest","appium:xcodeOrgId":"6U86FCFMS3","appium:xcodeSigningId":"iPhone Developer","appium:updatedWDABundleId":"qalified.WebDriverAgentRunnerQalified","appium:includeSafariInWebviews":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]},"desiredCapabilities":{"appium:udid":"00008101-00053094213A001E","appium:bundleId":"com.gia.dev2021","appium:deviceName":"iPhone equipo técnico","platformName":"iOS","appium:automationName":"XCUITest","appium:xcodeOrgId":"6U86FCFMS3","appium:xcodeSigningId":"iPhone Developer","appium:updatedWDABundleId":"qalified.WebDriverAgentRunnerQalified","appium:includeSafariInWebviews":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true}}
[AppiumDriver@79e8] Calling AppiumDriver.createSession() with args: [{"appium:udid":"00008101-00053094213A001E","appium:bundleId":"com.gia.dev2021","appium:deviceName":"iPhone equipo técnico","platformName":"iOS","appium:automationName":"XCUITest","appium:xcodeOrgId":"6U86FCFMS3","appium:xcodeSigningId":"iPhone Developer","appium:updatedWDABundleId":"qalified.WebDriverAgentRunnerQalified","appium:includeSafariInWebviews":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},null,{"alwaysMatch":{"appium:udid":"00008101-00053094213A001E","appium:bundleId":"com.gia.dev2021","appium:deviceName":"iPhone equipo técnico","platformName":"iOS","appium:automationName":"XCUITest","appium:xcodeOrgId":"6U86FCFMS3","appium:xcodeSigningId":"iPhone Developer","appium:updatedWDABundleId":"qalified.WebDriverAgentRunnerQalified","appium:includeSafariInWebviews":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]}]
[AppiumDriver@79e8] Event 'newSessionRequested' logged at 1705943722334 (14:15:22 GMT-0300 (Uruguay Standard Time))
[Appium] Attempting to find matching driver for automationName 'XCUITest' and platformName 'iOS'
[Appium] The 'xcuitest' driver was installed and matched caps.
[Appium] Will require it at /Users/qalified/.appium/node_modules/appium-xcuitest-driver
[Appium] Requiring driver at /Users/qalified/.appium/node_modules/appium-xcuitest-driver/build/index.js
[AppiumDriver@79e8] Event 'newSessionStarted' logged at 1705943722341 (14:15:22 GMT-0300 (Uruguay Standard Time))
[AppiumDriver@79e8] Encountered internal error running command: Error: Could not find a driver for automationName 'XCUITest' and platformName 'iOS'. Have you installed a driver that supports those capabilities? Run 'appium driver list --installed' to see. (Lower-level error: require() of ES Module /Users/qalified/node_modules/chalk/source/index.js from /Users/qalified/node_modules/@babel/code-frame/lib/index.js not supported.
[AppiumDriver@79e8] Instead change the require of /Users/qalified/node_modules/chalk/source/index.js in /Users/qalified/node_modules/@babel/code-frame/lib/index.js to a dynamic import() which is available in all CommonJS modules.)
[AppiumDriver@79e8]     at DriverConfig.findMatchingDriver (/opt/homebrew/lib/node_modules/appium/lib/extension/driver-config.js:175:13)
[AppiumDriver@79e8]     at AppiumDriver.createSession (/opt/homebrew/lib/node_modules/appium/lib/appium.js:644:11)
[HTTP] <-- POST /session 500 21 ms - 1646
[HTTP] 
∑©^C[Appium] Received SIGINT - shutting down
[AppiumDriver@79e8] There are no active sessions for cleanup
[HTTP] Waiting until the server is closed
[HTTP] Received server close event
```

**Comment by ErodriguezQA** [comment]
```
[Appium] Welcome to Appium v2.4.1 (REV 1c612baa096c69f2fcb221c74e6f5b9979efdcee)
[Appium] The autodetected Appium home path: /Users/qalified/.appium
[Appium] Attempting to load driver xcuitest...
[Appium] Requiring driver at /Users/qalified/.appium/node_modules/appium-xcuitest-driver/build/index.js
[Appium] Could not load driver 'xcuitest', so it will not be available. Error in loading the driver was: require() of ES Module /Users/qalified/node_modules/chalk/source/index.js from /Users/qalified/node_modules/@babel/code-frame/lib/index.js not supported.
[Appium] Instead change the require of /Users/qalified/node_modules/chalk/source/index.js in /Users/qalified/node_modules/@babel/code-frame/lib/index.js to a dynamic import() which is available in all CommonJS modules.
[Appium] Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/qalified/node_modules/chalk/source/index.js from /Users/qalified/node_modules/@babel/code-frame/lib/index.js not supported.
[Appium] Instead change the require of /Users/qalified/node_modules/chalk/source/index.js in /Users/qalified/node_modules/@babel/code-frame/lib/index.js to a dynamic import() which is available in all CommonJS modules.
[Appium]     at Object.<anonymous> (/Users/qalified/node_modules/@babel/code-frame/lib/index.js:9:38)
[Appium]     at Object.<anonymous> (/Users/qalified/node_modules/parse-json/index.js:5:28)
[Appium]     at Object.<anonymous> (/Users/qalified/node_modules/read-pkg/index.js:5:19)
[Appium]     at Object.<anonymous> (/Users/qalified/node_modules/@appium/support/build/lib/fs.js:18:36)
[Appium] Appium REST http interface listener started on http://0.0.0.0:4723
[Appium] You can provide the following URLs in your client code to connect to this server:
[Appium] 	http://127.0.0.1:4723/ (only accessible from the same host)
[Appium] 	http://192.168.1.4:4723/
[Appium] 	http://169.254.56.213:4723/
[Appium] 	http://169.254.134.8:4723/
[Appium] Available drivers:
[Appium]   - xcuitest@5.14.0 (automationName 'XCUITest')
[Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.
[HTTP] --> POST /session
[HTTP] {"capabilities":{"alwaysMatch":{"appium:udid":"00008101-00053094213A001E","appium:bundleId":"com.gia.dev2021","appium:deviceName":"iPhone equipo técnico","platformName":"iOS","appium:automationName":"XCUITest","appium:xcodeOrgId":"6U86FCFMS3","appium:xcodeSigningId":"iPhone Developer","appium:updatedWDABundleId":"qalified.WebDriverAgentRunnerQalified","appium:includeSafariInWebviews":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]},"desiredCapabilities":{"appium:udid":"00008101-00053094213A001E","appium:bundleId":"com.gia.dev2021","appium:deviceName":"iPhone equipo técnico","platformName":"iOS","appium:automationName":"XCUITest","appium:xcodeOrgId":"6U86FCFMS3","appium:xcodeSigningId":"iPhone Developer","appium:updatedWDABundleId":"qalified.WebDriverAgentRunnerQalified","appium:includeSafariInWebviews":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true}}
[AppiumDriver@3da1] Calling AppiumDriver.createSession() with args: [{"appium:udid":"00008101-00053094213A001E","appium:bundleId":"com.gia.dev2021","appium:deviceName":"iPhone equipo técnico","platformName":"iOS","appium:automationName":"XCUITest","appium:xcodeOrgId":"6U86FCFMS3","appium:xcodeSigningId":"iPhone Developer","appium:updatedWDABundleId":"qalified.WebDriverAgentRunnerQalified","appium:includeSafariInWebviews":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},null,{"alwaysMatch":{"appium:udid":"00008101-00053094213A001E","appium:bundleId":"com.gia.dev2021","appium:deviceName":"iPhone equipo técnico","platformName":"iOS","appium:automationName":"XCUITest","appium:xcodeOrgId":"6U86FCFMS3","appium:xcodeSigningId":"iPhone Developer","appium:updatedWDABundleId":"qalified.WebDriverAgentRunnerQalified","appium:includeSafariInWebviews":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]}]
[AppiumDriver@3da1] Event 'newSessionRequested' logged at 1706027596840 (13:33:16 GMT-0300 (Uruguay Standard Time))
[Appium] Attempting to find matching driver for automationName 'XCUITest' and platformName 'iOS'
[Appium] The 'xcuitest' driver was installed and matched caps.
[Appium] Will require it at /Users/qalified/.appium/node_modules/appium-xcuitest-driver
[Appium] Requiring driver at /Users/qalified/.appium/node_modules/appium-xcuitest-driver/build/index.js
[AppiumDriver@3da1] Event 'newSessionStarted' logged at 1706027596846 (13:33:16 GMT-0300 (Uruguay Standard Time))
[AppiumDriver@3da1] Encountered internal error running command: Error: Could not find a driver for automationName 'XCUITest' and platformName 'iOS'. Have you installed a driver that supports those capabilities? Run 'appium driver list --installed' to see. (Lower-level error: require() of ES Module /Users/qalified/node_modules/chalk/source/index.js from /Users/qalified/node_modules/@babel/code-frame/lib/index.js not supported.
[AppiumDriver@3da1] Instead change the require of /Users/qalified/node_modules/chalk/source/index.js in /Users/qalified/node_modules/@babel/code-frame/lib/index.js to a dynamic import() which is available in all CommonJS modules.)
[AppiumDriver@3da1]     at DriverConfig.findMatchingDriver (/opt/homebrew/lib/node_modules/appium/lib/extension/driver-config.js:175:13)
[AppiumDriver@3da1]     at AppiumDriver.createSession (/opt/homebrew/lib/node_modules/appium/lib/appium.js:644:11)
[HTTP] <-- POST /session 500 23 ms - 1646
[HTTP] 
```

**Comment by mykola-mokhnach** [comment]
Something is wrong with your local node deployment. I see the server is installed in /opt/homebrew/lib/node_modules/, while drivers are in /Users/qalified/.appium/node_modules/

So it is not clear why it tries to load anything from /Users/qalified/node_modules. Are you sure the above folder is needed?

**Comment by ErodriguezQA** [comment]
Yes, i have seen that on the logs. What happened is that this laptop had installed a node version through Homebrew and that was causing conflicts with some applications. I used `brew uninstall node` to get rid of it and installed node from other source, installing it on '/usr/local/bin/node'. Do i have to do some extra steps to delete the Homebrew version of it?

**Comment by jlipps** [comment]
Does `/Users/qalified/node_modules` exist? If so, just delete it. NPM will resolve packages in parent directories sometimes.

**Comment by ErodriguezQA** [comment]
That did the trick! Thank you very much!
