### ISSUE TITLE
bug: XCUITestDriver throwing the error: _**"Failed to create WDA session (A new session could not be created. Details: Cannot launch life.nuggets.app application. Make sure the correct bundle identifier has been provided in capabilities and check the device log for possible crash report occurrences). Retrying..."** specifically in circle ci.

### ISSUE THREAD

**Issue by lloydasamoah26** [appium/appium#19753]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running appium in circle ci to perform test execution(WebdriverIO) against our react native ios application on an ios simulator I am getting the following error from the XCUITestDriver: _**"Failed to create WDA session (A new session could not be created. Details: Cannot launch XXXXX.app application. Make sure the correct bundle identifier has been provided in capabilities and check the device log for possible crash report occurrences). Retrying..."**_ however when i run the same setup locally appium is able to launch the application on the simulator no issue and the tests run just fine.

### Expected Behavior

I expected the appium to launch the ios application and begin running the tests

### Minimal Reproducible Example

Unfortunately the project where this issue has occurred can't be shared for security reasons and I am unable to share the .app file publicly, However this issue can be recreated using any react native application . Please find the structure for the the appium tests within the project in question:
<img width="793" alt="Screenshot 2024-02-05 at 00 29 31" src="https://github.com/appium/appium/assets/14199615/b8c2ffaf-292c-4206-bbdb-ac494bafe4d7">

This should help you to understand the paths used within the config.yml, wdio.ios.simulator.conf.js, and wdio.ios.real.conf.js i have included here: https://gist.github.com/lloydasamoah26/65e1ae98034730a21eae9a5f05cb5d80 to help you get your project set up  to recreate the issue. I have the appium-tests directory sitting within a react native project as follows:
<img width="536" alt="Screenshot 2024-02-05 at 00 43 10" src="https://github.com/appium/appium/assets/14199615/bf11dfaf-527b-4f84-a8b7-0ef366b10299">

### Environment

All the details below are in relation to the circle environment where this issue occurs:
- Operating system: macOS 12.6 (21G115)( [Circle CI Image](https://circle-macos-docs.s3.amazonaws.com/image-manifest/v10821/manifest.txt))
- Appium server version (output of `appium --version`): 2.4.1
- Appium driver(s) and their version(s): Xcuitest-driver 5.12.2
- Appium plugin(s) and their version(s): N/A
- Node.js version (output of `node --version`):  16.20.1
- `npm` version (output of `npm --version`): Not sure
- Last component(s) version which did _not_ exhibit the problem: 
- Platform and version under [test:](url)
- Real device or emulator/simulator: Simulator

### Link to Appium Logs

https://gist.github.com/lloydasamoah26/75499f8a561288d409b66f47178a1588

**Comment by KazuCocoa** [comment]
What the result of logs with `showXcodeLog` capability?


```
[38;5;32m[XCUITestDriver@2c30 (c1cd7689)][0m Beginning **** with command 'xcodebuild build-for-****ing ****-without-building -project /Users/distiller/nuggets/mobile/react-native/appium-****s/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -derivedDataPath /Users/distiller/Library/Developer/Xcode/DerivedData/WebDriverAgent-bthntghqwpxelefdtqmrfsgiegry -destination id=17D29414-B320-4BD1-AB35-F487D5AEA0CA IPHONEOS_DEPLOYMENT_TARGET=16.2 GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO' in directory '/Users/distiller/nuggets/mobile/react-native/appium-****s/node_modules/appium-webdriveragent'
[38;5;32m[XCUITestDriver@2c30 (c1cd7689)][0m Output from xcodebuild will only be logged if any errors are present there. To change this, use 'showXcodeLog' desired capability
[38;5;32m[XCUITestDriver@2c30 (c1cd7689)][0m Waiting up to 60000ms for WebDriverAgent to start
```

Or I guess `test` was replaced with `****` in the log but that the result of below command issued by Appium:


> xcodebuild build-for-****ing ****-without-building -project /Users/distiller/nuggets/mobile/react-native/appium-****s/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -derivedDataPath /Users/distiller/Library/Developer/Xcode/DerivedData/WebDriverAgent-bthntghqwpxelefdtqmrfsgiegry -destination id=17D29414-B320-4BD1-AB35-F487D5AEA0CA IPHONEOS_DEPLOYMENT_TARGET=16.2 GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO

**Comment by mykola-mokhnach** [comment]
> [38;5;32m[XCUITestDriver@2c30 (c1cd7689)][0m Got response with status 500: {"value":{"error":"session not created","message":"Cannot launch life.nuggets.app application. Make sure the correct bundle identifier has been provided in capabilities and check the device log for possible crash report occurrences","traceback":""},"sessionId":null}

From what I see in the above log the WDA starts properly, but the app itself fails to start. Are you sure it does not crash? Hve you tried to manually run it on a simulator?

**Comment by lloydasamoah26** [comment]
Hi @KazuCocoa pease find the appium logs with Xcode Logs enabled here: https://gist.github.com/lloydasamoah26/35058967dfa3c820a7617425f7d47db0

**Comment by lloydasamoah26** [comment]
@mykola-mokhnach thats what i thought initially but then 

1. Using the xcode application on my machine i was able to build the .app file then install and launch it on the simulator just fine.

2. I then built the .app file using fastlane and and used the following commands to install it and launch it on the simulator on my machine successfully:

- xcrun simctl install booted /Users/lloydasamoah/Library/Developer/Xcode/DerivedData/NuggetsLife-fhqbpughyfbychfqikoukyonsesk/Build/Products/Release-iphonesimulator/NuggetsLife.app

- xcrun simctl launch booted life.nuggets.app

3. I was then able to run appium against our application locally no issues

4. So as part of the circle ci job i decided to run the above xcrun commands before attempting to run appium and starting the tests and there was no issue.

It is now only when webdriver attempts to launch the application do i get the error "Failed to create WDA session (A new session could not be created. Details: Cannot launch life.nuggets.app application. Make sure the correct bundle identifier has been provided in capabilities and check the device log for possible crash report occurrences). Retrying...".

**Comment by mykola-mokhnach** [comment]
Have you actually checked the device log from CircleCI? Might it be your machine is building for arm, but the remote one is Intel one?

**Comment by mykola-mokhnach** [comment]
I don't have any other ideas. Fetch the Simulator log. Most likely the app just crashes on execution

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by pradeipp** [comment]
Hi @mykola-mokhnach, I'm facing the same issue now. 

Here's the specs of my setup: 
Operating system: macOS 12.6 (21G115)
Appium server version (output of appium --version): 2.12.1
Appium driver(s) and their version(s): Xcuitest-driver 7.32.0
Appium plugin(s) and their version(s): None
Node.js version (output of node --version): 20.17.0
npm version (output of npm --version): 10.8.2
Last component(s) version which did not exhibit the problem: The current one
Real device or emulator/simulator: Real device, iphone 6 max, ios 15.7.9

And here's my setup: 
A macos machine hosts a flask server, which triggers a script to start appium server, and run appium/python test commands and run tests. 
Test apps are sent from github to the flask server and appium takes that app and runs a boilerplate open-and-screencap test on it.

This is a stable setup which works for some test apps while it doesn't for some test apps. The error I get is the exact same as the author of this post. 

```log
2024-12-02 08:35:14:481 [ce65f368][XCUITestDriver@4e88] WebDriverAgent successfully started after 7909ms
2024-12-02 08:35:14:481 [ce65f368][XCUITestDriver@4e88] Event 'wdaSessionAttempted' logged at 1733128514481 (15:35:14 GMT+0700 (Indochina Time))
2024-12-02 08:35:14:481 [ce65f368][XCUITestDriver@4e88] Sending createSession command to WDA
2024-12-02 08:35:14:483 [ce65f368][XCUITestDriver@4e88] Matched '/session' to command name 'createSession'
2024-12-02 08:35:14:483 [ce65f368][XCUITestDriver@4e88] Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.dummy.testapp","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true,"shouldTerminateApp":true,"forceAppLaunch":true,"useNativeCachingStrategy":true,"forceSimulatorSoftwareKeyboardPresence":true}],"alwaysMatch":{}}}
2024-12-02 08:35:14:501 [ce65f368][Xcode]     t =     0.73s Open com.dummy.testapp
2024-12-02 08:35:14:503 [ce65f368][Xcode]     t =     0.73s     Launch com.dummy.testapp
2024-12-02 08:35:14:842 [ce65f368][Xcode]     t =     1.06s         Setting up automation session
2024-12-02 08:36:14:920 [ce65f368][Xcode] 2024-12-02 15:36:15.106420+0700 WebDriverAgentRunner-Runner[73154:10667636] Waiting up to 10s until com.dummy.testapp is in idle state (including animations)
2024-12-02 08:36:14:920 [ce65f368][Xcode]     t =    61.14s         Wait for com.dummy.testapp to idle
2024-12-02 08:36:15:950 [ce65f368][XCUITestDriver@4e88] Got response with status 500: {"value":{"error":"session not created","message":"Cannot launch com.dummy.testapp application. Make sure the correct bundle identifier has been provided in capabilities and check the device log for possible crash report occurrences","traceback":""},"sessionId":null}
2024-12-02 08:36:15:950 [ce65f368][W3C] Matched W3C error code 'session not created' to SessionNotCreatedError
2024-12-02 08:36:15:951 [ce65f368][XCUITestDriver@4e88] Event 'wdaSessionFailed' logged at 1733128575951 (15:36:15 GMT+0700 (Indochina Time))
2024-12-02 08:36:15:959 [ce65f368][XCUITestDriver@4e88] SessionNotCreatedError: A new session could not be created. Details: Cannot launch com.dummy.testapp application. Make sure the correct bundle identifier has been provided in capabilities and check the device log for possible crash report occurrences
    at errorFromW3CJsonCode (/Users/testuser/.nvm/versions/node/v20.17.0/lib/node_modules/appium-webdriveragent/node_modules/@appium/base-driver/lib/protocol/errors.js:1112:25)
    at ProxyRequestError.getActualError (/Users/testuser/.nvm/versions/node/v20.17.0/lib/node_modules/appium-webdriveragent/node_modules/@appium/base-driver/lib/protocol/errors.js:981:14)
    at JWProxy.command (/Users/testuser/.nvm/versions/node/v20.17.0/lib/node_modules/appium-webdriveragent/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:348:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at XCUITestDriver.proxyCommand (/Users/testuser/.appium/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:103:35)
    at XCUITestDriver.startWdaSession (/Users/testuser/.appium/node_modules/appium-xcuitest-driver/lib/driver.js:1308:5)
    at /Users/testuser/.appium/node_modules/appium-xcuitest-driver/lib/driver.js:881:11
    at wrapped (/Users/testuser/.appium/node_modules/appium-xcuitest-driver/node_modules/asyncbox/lib/asyncbox.js:93:13)
    at retry (/Users/testuser/.appium/node_modules/appium-xcuitest-driver/node_modules/asyncbox/lib/asyncbox.js:66:13)
    at retryInterval (/Users/testuser/.appium/node_modules/appium-xcuitest-driver/node_modules/asyncbox/lib/asyncbox.js:103:10)
    at /Users/testuser/.appium/node_modules/appium-xcuitest-driver/lib/driver.js:835:7
2024-12-02 08:36:15:960 [ce65f368][XCUITestDriver@4e88] {}
2024-12-02 08:36:15:960 [ce65f368][DevCon Factory] Releasing connections for f72b8eb7b9c31b412a7e11248577fa937515b344 device on any port number
2024-12-02 08:36:15:961 [ce65f368][DevCon Factory] Found cached connections to release: ["f72b8eb7b9c31b412a7e11248577fa937515b344:8100"]
2024-12-02 08:36:15:961 [ce65f368][DevCon Factory] Releasing the listener for 'f72b8eb7b9c31b412a7e11248577fa937515b344:8100'
2024-12-02 08:36:15:961 [ce65f368][iProxy@f72b8eb7:8100] Closing the connection
2024-12-02 08:36:15:961 [ce65f368][DevCon Factory] Cached connections count: 0
2024-12-02 08:36:15:961 [ce65f368][XCUITestDriver@4e88] Not clearing log files. Use `clearSystemFiles` capability to turn on.
2024-12-02 08:36:15:963 [ce65f368][AppiumDriver@6055] Event 'newSessionStarted' logged at 1733128575963 (15:36:15 GMT+0700 (Indochina Time))
2024-12-02 08:36:15:964 [ce65f368][AppiumDriver@6055] Encountered internal error running command: Error: Unable to start WebDriverAgent session. Original error: A new session could not be created. Details: Cannot launch com.dummy.testapp application. Make sure the correct bundle identifier has been provided in capabilities and check the device log for possible crash report occurrences
    at /Users/testuser/.appium/node_modules/appium-xcuitest-driver/lib/driver.js:895:17
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at wrapped (/Users/testuser/.appium/node_modules/appium-xcuitest-driver/node_modules/asyncbox/lib/asyncbox.js:93:13)
    at retry (/Users/testuser/.appium/node_modules/appium-xcuitest-driver/node_modules/asyncbox/lib/asyncbox.js:66:13)
    at retryInterval (/Users/testuser/.appium/node_modules/appium-xcuitest-driver/node_modules/asyncbox/lib/asyncbox.js:103:10)
    at /Users/testuser/.appium/node_modules/appium-xcuitest-driver/lib/driver.js:835:7
2024-12-02 08:36:15:974 [ce65f368][HTTP] <-- POST /wd/hub/session 500 77473 ms - 1140 
2024-12-02 08:36:16:085 [Appium] Received SIGTERM - shutting down

```

**Comment by pradeipp** [comment]
Hi @KazuCocoa @mykola-mokhnach, could you please have a look at this? This issue was closed due to no response from the author in february and I'm facing it again now

**Comment by KazuCocoa** [comment]
> and check the device log for possible crash report occurrences

Have you investigated the device log? It looks like XCTest could not launch the app or the app's main thread was not an idle state so long

**Comment by pradeipp** [comment]
Hi @KazuCocoa, sorry for the late response, I got occupied in other stuff. 
I looked at the device logs, and even compared it to the logs from the same device for a job that was successfully run. 

There's a lot of stuff, but I've narrowed the logs down to ~2k lines, which corresponds to the timeframe from when WebdriverAgent starts(`WebDriverAgentRunner-Runner(WebDriverAgentLib)[18240] <Notice>: Using singleton test manager`), up to the point where the app is terminated(`runningboardd(RunningBoard)[33] <Notice>: [app<com.pradeep.testapp>:18241] termination reported by launchd (2, 6, 6)`)

Feel free to have a look
[trimmed_device_logs_for_github_issue_19753.log](https://github.com/user-attachments/files/18072280/device_logs_for_github_issue_19753.log)

**Comment by KazuCocoa** [comment]
Does your app run with Flutter? I'm wondering around below lines are related. I'm not sure how you could error in the Dart VM initialization, but one possible case in your case is maybe the Dart VM got an issue in the launching time.

```
Dec  9 12:28:19 iPhone12-17 Runner(Flutter)[18241] <Notice>: [FATAL:flutter/runtime/dart_vm_initializer.cc(89)] Error while initializing the Dart VM: Invalid vm isolate snapshot seen
Dec  9 12:28:19 iPhone12-17 SpringBoard(libxpc.dylib)[34] <Notice>: [0xd226aad00] invalidated because the client process (pid 18241) either cancelled the connection or exited
Dec  9 12:28:19 iPhone12-17 SpringBoard(FrontBoard)[34] <Notice>: [0x302496400:(FBSceneManager):sceneID:com.pradeep.testapp-default] Pretending scene creation was successful, even though we got no response (<rdar://problem/62751231>). This does *not* mean there is a problem in FrontBoard, only that we are working around a bug in UIKit.
Dec  9 12:28:19 iPhone12-17 SpringBoard(FrontBoard)[34] <Notice>: [0x302496400:(FBSceneManager):sceneID:com.pradeep.testapp-default] Scene action [Logical Activate][0x34c8] completed with success: 1
Dec  9 12:28:19 iPhone12-17 SpringBoard(libxpc.dylib)[34] <Notice>: [0xd226a8b40] invalidated because the client process (pid 18241) either cancelled the connection or exited
Dec  9 12:28:19 iPhone12-17 SpringBoard(FrontBoard)[34] <Notice>: [app<com.pradeep.testapp>:18241] Workspace connection invalidated.
Dec  9 12:28:19 iPhone12-17 SpringBoard(FrontBoard)[34] <Notice>: [app<com.pradeep.testapp>:18241] Now flagged as pending exit for reason: workspace client connection invalidated
Dec  9 12:28:19 iPhone12-17 SpringBoard(FrontBoard)[34] <Notice>: [(FBSceneManager):sceneID:com.pradeep.testapp-default] scene content state changed: ready
Dec  9 12:28:19 iPhone12-17 kernel[0] <Notice>: Runner[18241] Corpse allowed 1 of 5
```

**Comment by pradeipp** [comment]
Hi @KazuCocoa, it turned out that the test app we were using had issue with flutter. Our dev is working to resolve it internally, but I don't think I can disclose much about it, or anything that would be helpful to this discussion. 
Thank you very much for your help 😇 Have a good one
