### ISSUE TITLE
bug: getGeoLocation error on ios simulators: Location service must be set to 'Always' 

### ISSUE THREAD

**Issue by fleytman** [appium/appium#19761]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When i use getGeoLocation on ios simulator, appium put error
`ein order to retrive the current geolocation data. Please set it up manually via 'Settings > Privacy > Location Services -> WebDriverAgentRunner-Runner'`

### Expected Behavior

getGeoLocation work correctly

### Minimal Reproducible Example

{
  "platformName": "iOS",
  "appium:platformVersion": "15.5",
  "appium:deviceName": "13_15.5",
  "appium:automationName": "XCUITest"
}

### Environment

- Operating system: macos
- Appium server version (output of `appium --version`): 2.4.1
- Appium driver(s) and their version(s): xcuitest@5.16.1 [installed (npm)]
- Node.js version (output of `node --version`): v21.5.0
- `npm` version (output of `npm --version`):10.2.4
- Real device or emulator/simulator: xcode 15.2, simulators 15.5, 16.4

### Further Information

```
[XCUITestDriver@2d1f (17584d5e)] Executing command 'setGeoLocation'
[XCUITestDriver@2d1f (17584d5e)] Responding to client with driver.setGeoLocation() result: {"latitude":43.238255,"longitude":76.945465,"altitude":0}
[HTTP] <-- POST /wd/hub/session/17584d5e-b5f8-40dd-9cb2-9ab187ecf31e/location 200 680 ms - 67
[HTTP]
[HTTP] --> GET /wd/hub/session/17584d5e-b5f8-40dd-9cb2-9ab187ecf31e/location
[HTTP] {}
[XCUITestDriver@2d1f (17584d5e)] Calling AppiumDriver.getGeoLocation() with args: ["17584d5e-b5f8-40dd-9cb2-9ab187ecf31e"]
[XCUITestDriver@2d1f (17584d5e)] Executing command 'getGeoLocation'
[XCUITestDriver@2d1f (17584d5e)] Proxying to WDA with an unknown route: GET /wda/device/location
[XCUITestDriver@2d1f (17584d5e)] Proxying [GET /wda/device/location] to [GET http://127.0.0.1:8100/session/E9FD0172-4344-46B5-8108-26EC04D4209B/wda/device/location] with no body
[XCUITestDriver@2d1f (17584d5e)] Got response with status 200: {"value":{"latitude":0,"authorizationStatus":0,"longitude":0,"altitude":0},"sessionId":"E9FD0172-4344-46B5-8108-26EC04D4209B"}
[XCUITestDriver@2d1f (17584d5e)] Location service must be set to 'Always' in order to retrive the current geolocation data. Please set it up manually via 'Settings > Privacy > Location Services -> WebDriverAgentRunner-Runner'
[XCUITestDriver@2d1f (17584d5e)] Encountered internal error running command: Error: Location service must be set to 'Always' in order to retrive the current geolocation data. Please set it up manually via 'Settings > Privacy > Location Services -> WebDriverAgentRunner-Runner'
[XCUITestDriver@2d1f (17584d5e)]     at Object.wrappedLogger.errorWithException (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/support/lib/logging.js:114:43)
[XCUITestDriver@2d1f (17584d5e)]     at Object.wrappedLogger.errorAndThrow (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/support/lib/logging.js:120:16)
[XCUITestDriver@2d1f (17584d5e)]     at XCUITestDriver.getGeoLocation (/Users/fleitmanmikhail/.appium/node_modules/appium-xcuitest-driver/lib/commands/location.js:34:16)
[XCUITestDriver@2d1f (17584d5e)]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by KazuCocoa** [comment]
I thought simulators also had the config but It looks like Apple removed the config for simulators: https://forums.developer.apple.com/forums/thread/693317

Maybe we could address the error message is older simulators and all real devices.

Instead, could you use `mobile: setSimulatedLocation`, `mobile: getSimulatedLocation` and `mobile: resetSimulatedLocation` to modify location via `xcrun`'s feature?
https://appium.github.io/appium-xcuitest-driver/6.0/reference/execute-methods/#mobile-getsimulatedlocation

**Comment by fleytman** [comment]
Case 1:
1. Use setGeoLocation: location change on simulator
2. Use mobile:getSimulatedLocation - all values return null
```
[HTTP] --> POST /wd/hub/session/159201eb-b546-43b0-a9ec-10615e4e9b0b/location
[HTTP] {"location":{"altitude":0,"latitude":26.3243,"class":"org.openqa.selenium.html5.Location","longitude":57.23432}}
[XCUITestDriver@1b03 (159201eb)] Calling AppiumDriver.setGeoLocation() with args: [{"altitude":0,"latitude":26.3243,"class":"org.openqa.selenium.html5.Location","longitude":57.23432},"159201eb-b546-43b0-a9ec-10615e4e9b0b"]
[XCUITestDriver@1b03 (159201eb)] Executing command 'setGeoLocation'
[XCUITestDriver@1b03 (159201eb)] Responding to client with driver.setGeoLocation() result: {"latitude":26.3243,"longitude":57.23432,"altitude":0}
[HTTP] <-- POST /wd/hub/session/159201eb-b546-43b0-a9ec-10615e4e9b0b/location 200 762 ms - 64
[HTTP]
[HTTP] --> POST /wd/hub/session/159201eb-b546-43b0-a9ec-10615e4e9b0b/execute/sync
[HTTP] {"script":"mobile:getSimulatedLocation","args":[]}
[XCUITestDriver@1b03 (159201eb)] Calling AppiumDriver.execute() with args: ["mobile:getSimulatedLocation",[],"159201eb-b546-43b0-a9ec-10615e4e9b0b"]
[XCUITestDriver@1b03 (159201eb)] Executing command 'execute'
[XCUITestDriver@1b03 (159201eb)] Proxying to WDA with an unknown route: GET /wda/simulatedLocation
[XCUITestDriver@1b03 (159201eb)] Proxying [GET /wda/simulatedLocation] to [GET http://127.0.0.1:8100/session/CA7914C0-F814-481B-BC9D-11BEB219DF07/wda/simulatedLocation] with no body
[XCUITestDriver@1b03 (159201eb)] Got response with status 200: {"value":{"altitude":null,"longitude":null,"latitude":null},"sessionId":"CA7914C0-F814-481B-BC9D-11BEB219DF07"}
[XCUITestDriver@1b03 (159201eb)] Responding to client with driver.execute() result: {"altitude":null,"longitude":null,"latitude":null}
[HTTP] <-- POST /wd/hub/session/159201eb-b546-43b0-a9ec-10615e4e9b0b/execute/sync 200 214 ms - 60     
```

Case 2:
1. Use mobile:setSimulatedLocation: location change on simulator
2. Use mobile:getSimulatedLocation - all values return values from 1 step
```
[HTTP] --> POST /wd/hub/session/159201eb-b546-43b0-a9ec-10615e4e9b0b/execute/sync
[HTTP] {"script":"mobile:setSimulatedLocation","args":[{"latitude":25.3432,"longitude":55.42342}]}
[XCUITestDriver@1b03 (159201eb)] Calling AppiumDriver.execute() with args: ["mobile:setSimulatedLocation",[{"latitude":25.3432,"longitude":55.42342}],"159201eb-b546-43b0-a9ec-10615e4e9b0b"]
[XCUITestDriver@1b03 (159201eb)] Executing command 'execute'
[XCUITestDriver@1b03 (159201eb)] Proxying to WDA with an unknown route: POST /wda/simulatedLocation
[XCUITestDriver@1b03 (159201eb)] Proxying [POST /wda/simulatedLocation] to [POST http://127.0.0.1:8100/session/CA7914C0-F814-481B-BC9D-11BEB219DF07/wda/simulatedLocation] with body: {"latitude":25.3432,"longitude":55.42342}
[XCUITestDriver@1b03 (159201eb)] Got response with status 200: {"value":null,"sessionId":"CA7914C0-F814-481B-BC9D-11BEB219DF07"}
[XCUITestDriver@1b03 (159201eb)] Responding to client with driver.execute() result: null
[HTTP] <-- POST /wd/hub/session/159201eb-b546-43b0-a9ec-10615e4e9b0b/execute/sync 200 172 ms - 14
[HTTP]
[HTTP] --> POST /wd/hub/session/159201eb-b546-43b0-a9ec-10615e4e9b0b/execute/sync
[HTTP] {"script":"mobile:getSimulatedLocation","args":[]}
[XCUITestDriver@1b03 (159201eb)] Calling AppiumDriver.execute() with args: ["mobile:getSimulatedLocation",[],"159201eb-b546-43b0-a9ec-10615e4e9b0b"]
[XCUITestDriver@1b03 (159201eb)] Executing command 'execute'
[XCUITestDriver@1b03 (159201eb)] Proxying to WDA with an unknown route: GET /wda/simulatedLocation
[XCUITestDriver@1b03 (159201eb)] Proxying [GET /wda/simulatedLocation] to [GET http://127.0.0.1:8100/session/CA7914C0-F814-481B-BC9D-11BEB219DF07/wda/simulatedLocation] with no body
[XCUITestDriver@1b03 (159201eb)] Got response with status 200: {"value":{"altitude":0,"longitude":55.42342,"latitude":25.3432},"sessionId":"CA7914C0-F814-481B-BC9D-11BEB219DF07"}
[XCUITestDriver@1b03 (159201eb)] Responding to client with driver.execute() result: {"altitude":0,"longitude":55.42342,"latitude":25.3432}
[HTTP] <-- POST /wd/hub/session/159201eb-b546-43b0-a9ec-10615e4e9b0b/execute/sync 200 133 ms - 64                    
```

**Comment by fleytman** [comment]
On ios 15.5 mobile:getSimulatedLocation

```
[HTTP] --> POST /wd/hub/session/0075c395-9e62-45bd-aeed-5487420f81c7/execute/sync
[HTTP] {"script":"mobile:getSimulatedLocation","args":[]}
[XCUITestDriver@e89f (0075c395)] Calling AppiumDriver.execute() with args: ["mobile:getSimulatedLocation",[],"0075c395-9e62-45bd-aeed-5487420f81c7"]
[XCUITestDriver@e89f (0075c395)] Executing command 'execute'
[XCUITestDriver@e89f (0075c395)] Proxying to WDA with an unknown route: GET /wda/simulatedLocation
[XCUITestDriver@e89f (0075c395)] Proxying [GET /wda/simulatedLocation] to [GET http://127.0.0.1:8100/session/720C020B-9B86-4009-BCCC-3751D812C03D/wda/simulatedLocation] with no body
[XCUITestDriver@e89f (0075c395)] Got response with status 500: {"value":{"error":"unknown error","message":"Error Domain=com.facebook.WebDriverAgent Code=1 \"Your device does not support location simulation\" UserInfo={NSLocalizedDescription=Your device does not support location simulation}","traceback":""},"sessionId":"720C020B-9B86-4009-BCCC-3751D812C03D"}
[W3C] Matched W3C error code 'unknown error' to UnknownError
[XCUITestDriver@e89f (0075c395)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error Domain=com.facebook.WebDriverAgent Code=1 "Your device does not support location simulation" UserInfo={NSLocalizedDescription=Your device does not support location simulation}
[XCUITestDriver@e89f (0075c395)]     at errorFromW3CJsonCode (/Users/fleitmanmikhail/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/protocol/errors.js:1085:25)
[XCUITestDriver@e89f (0075c395)]     at ProxyRequestError.getActualError (/Users/fleitmanmikhail/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/protocol/errors.js:954:14)
[XCUITestDriver@e89f (0075c395)]     at JWProxy.command (/Users/fleitmanmikhail/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:353:19)
[XCUITestDriver@e89f (0075c395)]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[XCUITestDriver@e89f (0075c395)]     at XCUITestDriver.proxyCommand (/Users/fleitmanmikhail/.appium/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:109:35)
[XCUITestDriver@e89f (0075c395)]     at XCUITestDriver.mobileGetSimulatedLocation (/Users/fleitmanmikhail/.appium/node_modules/appium-xcuitest-driver/lib/commands/geolocation.js:23:10)
[XCUITestDriver@e89f (0075c395)]     at XCUITestDriver.executeMethod (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/commands/execute.ts:36:12)
[XCUITestDriver@e89f (0075c395)]     at XCUITestDriver.execute (/Users/fleitmanmikhail/.appium/node_modules/appium-xcuitest-driver/lib/commands/execute.js:118:14)
[HTTP] <-- POST /wd/hub/session/0075c395-9e62-45bd-aeed-5487420f81c7/execute/sync 500 51 ms - 1757
[HTTP]
```

**Comment by fleytman** [comment]
It turns out that on ios 15.5 there is no way to check what location is set. And on ios 16.4 you can only get the location that is set using mobile:setSimulatedLocation.

**Comment by KazuCocoa** [comment]
Yes, `getSimulatedLocation` returns set geolocation by `setSimulatedLocation`.
https://appium.github.io/appium-xcuitest-driver/6.0/reference/execute-methods/#mobile-getsimulatedlocation

They use Apple's method in the backend, so the version limitation also came from that. It looks like they stopped providing location modification for simulators for lower than ios 16.4 as https://forums.developer.apple.com/forums/thread/693317 ...?

**Comment by KazuCocoa** [comment]
- Apple stop providing location config for simulators according to https://forums.developer.apple.com/forums/thread/693317
    - So this method might not work for simulators
- Simulated location via XCTest feature may work for newer iOS versions such as 16.4+

**Comment by fleytman** [comment]
Also probably need to update the logic in java-client. Instead of `setGeoLocation` it should use `mobile: setSimulatedLocation` (similar to get and reset) for iOS 16.4+.

**Comment by fleytman** [comment]
@KazuCocoa please update the get and set location method in java-client. On the latest version, the error is reproduced by default. I think it's not obvious to everyone that you need to use the wrong method as in java-client, but using mobile: setSimulatedLocation
