### ISSUE TITLE
bug: <iOS Allow Location Pop is not handled by the Appium>

### ISSUE THREAD

**Issue by nikhil-anand-ext-volansys** [appium/appium#19771]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

iOS Allow Location Pop is not handled by the Appium 

We have obsrved that Appium is Working Properly on iOS Application but when it comes to the Handle Location Allow System Pop up then Appium is not clicking on that Pop Up

Xcode Version : 15.2
MAC : 15
Appium : 2.4.1

### Expected Behavior

Appium Should Click and Handle Location Allow Pop Up

### Minimal Reproducible Example

100%

### Environment

- Operating system: MAC OS
- Appium server version (output of `appium --version`): 2.4.1
- Appium driver(s) and their version(s): 5.43 
- Appium plugin(s) and their version(s): 
- Node.js version (output of `node --version`): 20.6
- `npm` version (output of `npm --version`): 
- Real device or emulator/simulator: iPhone 14

**Comment by mykola-mokhnach** [comment]
Please provide the server log and an example for the client code

**Comment by nikhil-anand-ext-volansys** [comment]
Hi 

Attached Server Logs : 

:8107/status] with no body
[iProxy@00008030:8107] Connection was refused to port 8107
[XCUITestDriver@5eba (44d2e4cf)] socket hang up
[XCUITestDriver@5eba (44d2e4cf)] Matched '/status' to command name 'getStatus'
[XCUITestDriver@5eba (44d2e4cf)] Proxying [GET /status] to [GET http://127.0.0.1:8107/status] with no body
[iProxy@00008030:8107] Connection was refused to port 8107
[XCUITestDriver@5eba (44d2e4cf)] socket hang up
[XCUITestDriver@5eba (44d2e4cf)] Matched '/status' to command name 'getStatus'
[XCUITestDriver@5eba (44d2e4cf)] Proxying [GET /status] to [GET http://127.0.0.1:8107/status] with no body
[iProxy@00008030:8107] Connection was refused to port 8107
[XCUITestDriver@5eba (44d2e4cf)] socket hang up
[XCUITestDriver@5eba (44d2e4cf)] Matched '/status' to command name 'getStatus'
[XCUITestDriver@5eba (44d2e4cf)] Proxying [GET /status] to [GET http://127.0.0.1:8107/status] with no body
[iProxy@00008030:8107] Connection was refused to port 8107
[XCUITestDriver@5eba (44d2e4cf)] socket hang up
[XCUITestDriver@5eba (44d2e4cf)] Matched '/status' to command name 'getStatus'
[XCUITestDriver@5eba (44d2e4cf)] Proxying [GET /status] to [GET http://127.0.0.1:8107/status] with no body
[iProxy@00008030:8107] Connection was refused to port 8107
[XCUITestDriver@5eba (44d2e4cf)] socket hang up
[XCUITestDriver@5eba (44d2e4cf)] Matched '/status' to command name 'getStatus'
[XCUITestDriver@5eba (44d2e4cf)] Proxying [GET /status] to [GET http://127.0.0.1:8107/status] with no body
[iProxy@00008030:8107] Connection was refused to port 8107
[XCUITestDriver@5eba (44d2e4cf)] socket hang up
[XCUITestDriver@5eba (44d2e4cf)] Matched '/status' to command name 'getStatus'
[XCUITestDriver@5eba (44d2e4cf)] Proxying [GET /status] to [GET http://127.0.0.1:8107/status] with no body
[iProxy@00008030:8107] Connection was refused to port 8107
[XCUITestDriver@5eba (44d2e4cf)] socket hang up
[XCUITestDriver@5eba (44d2e4cf)] Matched '/status' to command name 'getStatus'
[XCUITestDriver@5eba (44d2e4cf)] Proxying [GET /status] to [GET http://127.0.0.1:8107/status] with no body
[iProxy@00008030:8107] Connection was refused to port 8107
[XCUITestDriver@5eba (44d2e4cf)] socket hang up
[XCUITestDriver@5eba (44d2e4cf)] Matched '/status' to command name 'getStatus'
[XCUITestDriver@5eba (44d2e4cf)] Proxying [GET /status] to [GET http://127.0.0.1:8107/status] with no body
[iProxy@00008030:8107] Connection was refused to port 8107
[XCUITestDriver@5eba (44d2e4cf)] socket hang up
[XCUITestDriver@5eba (44d2e4cf)] Matched '/status' to command name 'getStatus'
[XCUITestDriver@5eba (44d2e4cf)] Proxying [GET /status] to [GET http://127.0.0.1:8107/status] with no body
[iProxy@00008030:8107] Connection was refused to port 8107
[XCUITestDriver@5eba (44d2e4cf)] socket hang up
[XCUITestDriver@5eba (44d2e4cf)] Matched '/status' to command name 'getStatus'
[XCUITestDriver@5eba (44d2e4cf)] Proxying [GET /status] to [GET http://127.0.0.1:8107/status] with no body
[iProxy@00008030:8107] Connection was refused to port 8107
[XCUITestDriver@5eba (44d2e4cf)] socket hang up
[XCUITestDriver@5eba (44d2e4cf)] Matched '/status' to command name 'getStatus'
[XCUITestDriver@5eba (44d2e4cf)] Proxying [GET /status] to [GET http://127.0.0.1:8107/status] with no body
[iProxy@00008030:8107] Connection was refused to port 8107
[XCUITestDriver@5eba (44d2e4cf)] socket hang up
[XCUITestDriver@5eba (44d2e4cf)] Matched '/status' to command name 'getStatus'
[XCUITestDriver@5eba (44d2e4cf)] Proxying [GET /status] to [GET http://127.0.0.1:8107/status] with no body
[iProxy@00008030:8107] Connection was refused to port 8107
[XCUITestDriver@5eba (44d2e4cf)] socket hang up
[XCUITestDriver@5eba (44d2e4cf)] Matched '/status' to command name 'getStatus'
[XCUITestDriver@5eba (44d2e4cf)] Proxying [GET /status] to [GET http://127.0.0.1:8107/status] with no body
[iProxy@00008030:8107] Connection was refused to port 8107
[XCUITestDriver@5eba (44d2e4cf)] socket hang up
[XCUITestDriver@5eba (44d2e4cf)] Matched '/status' to command name 'getStatus'
[XCUITestDriver@5eba (44d2e4cf)] Proxying [GET /status] to [GET http://127.0.0.1:8107/status] with no body
[iProxy@00008030:8107] Connection was refused to port 8107
[XCUITestDriver@5eba (44d2e4cf)] socket hang up
[XCUITestDriver@5eba (44d2e4cf)] Matched '/status' to command name 'getStatus'
[XCUITestDriver@5eba (44d2e4cf)] Proxying [GET /status] to [GET http://127.0.0.1:8107/status] with no body
[iProxy@00008030:8107] Connection was refused to port 8107
[XCUITestDriver@5eba (44d2e4cf)] socket hang up
[XCUITestDriver@5eba (44d2e4cf)] Matched '/status' to command name 'getStatus'
[XCUITestDriver@5eba (44d2e4cf)] Proxying [GET /status] to [GET http://127.0.0.1:8107/status] with no body
[iProxy@00008030:8107] Connection was refused to port 8107
[XCUITestDriver@5eba (44d2e4cf)] socket hang up
[XCUITestDriver@5eba (44d2e4cf)] Matched '/status' to command name 'getStatus'
[XCUITestDriver@5eba (44d2e4cf)] Proxying [GET /status] to [GET http://127.0.0.1:8107/status] with no body
[iProxy@00008030:8107] Connection was refused to port 8107
[XCUITestDriver@5eba (44d2e4cf)] socket hang up
[Xcode] 2024-02-09 18:59:45.272 xcodebuild[41705:3065963] [MT] IDETestOperationsObserverDebug: 23.995 elapsed -- Testing started completed.
[Xcode] 2024-02-09 18:59:45.272 xcodebuild[41705:3065963] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
[Xcode] 
[Xcode] 2024-02-09 18:59:45.272 xcodebuild[41705:3065963] [MT] IDETestOperationsObserverDebug: 23.995 sec, +23.995 sec -- end
[Xcode] 
[Xcode] 
[Xcode] Test session results, code coverage, and logs:
[Xcode] 	/Users/shraddha.shah/Library/Developer/Xcode/DerivedData/WebDriverAgent-gmtdnpvhiqyaxrctjlabywydfbtt/Logs/Test/Test-WebDriverAgentRunner-2024.02.09_18-58-17-+0530.xcresult
[Xcode] 
[Xcode] 
[Xcode] Testing failed:
[Xcode] 	WebDriverAgentRunner-Runner encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted. (Underlying Error: Test runner exited before starting test execution.))
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[Xcode] Testing started
[Xcode] 
[Xcode] xcodebuild exited with code '65' and signal 'null'
[XCUITestDriver@5eba (44d2e4cf)] Event 'wdaStartFailed' logged at 1707485385474 (18:59:45 GMT+0530 (India Standard Time))
[XCUITestDriver@5eba (44d2e4cf)] Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65. This usually indicates an issue with the local Xcode setup or WebDriverAgent project configuration or the driver-to-platform version mismatch. Consider setting 'showXcodeLog' capability to true in order to check the Appium server log for build-related error messages.. Make sure you follow the tutorial at https://appium.github.io/appium-xcuitest-driver/latest/preparation/real-device-config/. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
[XCUITestDriver@5eba (44d2e4cf)] Quitting and uninstalling WebDriverAgent
[XCUITestDriver@5eba (44d2e4cf)] Shutting down sub-processes
[XCUITestDriver@5eba (44d2e4cf)] Uninstalling WDAs: 'com.facebook.WebDriverAgentRunner.xctrunner'
[XCUITestDriver@5eba (44d2e4cf)] {}
[DevCon Factory] Releasing connections for 00008030-001130940C82802E device on any port number
[DevCon Factory] Found cached connections to release: ["00008030-001130940C82802E:8107"]
[DevCon Factory] Releasing the listener for '00008030-001130940C82802E:8107'
[iProxy@00008030:8107] Closing the connection
[DevCon Factory] Cached connections count: 0
[XCUITestDriver@5eba (44d2e4cf)] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[iProxy@00008030:8107] The connection has been closed
[AppiumDriver@6781] Event 'newSessionStarted' logged at 1707485385961 (18:59:45 GMT+0530 (India Standard Time))
[AppiumDriver@6781] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65. This usually indicates an issue with the local Xcode setup or WebDriverAgent project configuration or the driver-to-platform version mismatch. Consider setting 'showXcodeLog' capability to true in order to check the Appium server log for build-related error messages.. Make sure you follow the tutorial at https://appium.github.io/appium-xcuitest-driver/latest/preparation/real-device-config/. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
[AppiumDriver@6781]     at quitAndUninstall (/Users/shraddha.shah/.appium/node_modules/appium-xcuitest-driver/lib/driver.js:794:15)
[AppiumDriver@6781]     at /Users/shraddha.shah/.appium/node_modules/appium-xcuitest-driver/lib/driver.js:880:13
[AppiumDriver@6781]     at wrapped (/Users/shraddha.shah/.appium/node_modules/appium-xcuitest-driver/node_modules/asyncbox/lib/asyncbox.js:93:13)
[AppiumDriver@6781]     at retry (/Users/shraddha.shah/.appium/node_modules/appium-xcuitest-driver/node_modules/asyncbox/lib/asyncbox.js:66:13)
[AppiumDriver@6781]     at retryInterval (/Users/shraddha.shah/.appium/node_modules/appium-xcuitest-driver/node_modules/asyncbox/lib/asyncbox.js:103:10)
[AppiumDriver@6781]     at /Users/shraddha.shah/.appium/node_modules/appium-xcuitest-driver/lib/driver.js:819:7
[HTTP] <-- POST /session 500 202964 ms - 1810
[HTTP] 
[XCUITestDriver@5eba] Matched '/status' to command name 'getStatus'
[XCUITestDriver@5eba] Proxying [GET /status] to [GET http://127.0.0.1:8107/status] with no body
[XCUITestDriver@5eba] connect ECONNREFUSED 127.0.0.1:8107
[XCUITestDriver@5eba] Matched '/status' to command name 'getStatus'
[XCUITestDriver@5eba] Proxying [GET /status] to [GET http://127.0.0.1:8107/status] with no body
[XCUITestDriver@5eba] connect ECONNREFUSED 127.0.0.1:8107
[XCUITestDriver@5eba] Matched '/status' to command name 'getStatus'
[XCUITestDriver@5eba] Proxying [GET /status] to [GET http://127.0.0.1:8107/status] with no body
[XCUITestDriver@5eba] connect ECONNREFUSED 127.0.0.1:8107
[XCUITestDriver@5eba] Matched '/status' to command name 'getStatus'
[XCUITestDriver@5eba] Proxying [GET /status] to [GET http://127.0.0.1:8107/status] with no body
[XCUITestDriver@5eba] connect ECONNREFUSED 127.0.0.1:8107
[XCUITestDriver@5eba] Matched '/status' to command name 'getStatus'
[XCUITestDriver@5eba] Proxying [GET /status] to [GET http://127.0.0.1:8107/status] with no body
[XCUITestDriver@5eba] connect ECONNREFUSED 127.0.0.1:8107
[XCUITestDriver@5eba] Matched '/status' to command name 'getStatus'
[XCUITestDriver@5eba] Proxying [GET /status] to [GET http://127.0.0.1:8107/status] with no body
[XCUITestDriver@5eba] connect ECONNREFUSED 127.0.0.1:8107
[XCUITestDriver@5eba] Matched '/status' to command name 'getStatus'
[XCUITestDriver@5eba] Proxying [GET /status] to [GET http://127.0.0.1:8107/status] with no body
[XCUITestDriver@5eba] connect ECONNREFUSED 127.0.0.1:8107
[XCUITestDriver@5eba] Matched '/status' to command name 'getStatus'
[XCUITestDriver@5eba] Proxying [GET /status] to [GET http://127.0.0.1:8107/status] with no body
[XCUITestDriver@5eba] connect ECONNREFUSED 127.0.0.1:8107
[XCUITestDriver@5eba] Matched '/status' to command name 'getStatus'
[XCUITestDriver@5eba] Proxying [GET /status] to [GET http://127.0.0.1:8107/status] with no body
[XCUITestDriver@5eba] connect ECONNREFUSED 127.0.0.1:8107
[XCUITestDriver@5eba] Matched '/status' to command name 'getStatus'
[XCUITestDriver@5eba] Proxying [GET /status] to [GET http://127.0.0.1:8107/status] with no body
[XCUITestDriver@5eba] connect ECONNREFUSED 127.0.0.1:8107
[XCUITestDriver@5eba] Matched '/status' to command name 'getStatus'
[XCUITestDriver@5eba] Proxying [GET /status] to [GET http://127.0.0.1:8107/status] with no body
[XCUITestDriver@5eba] connect ECONNREFUSED 127.0.0.1:8107
[XCUITestDriver@5eba] Matched '/status' to command name 'getStatus'
[XCUITestDriver@5eba] Proxying [GET /status] to [GET http://127.0.0.1:8107/status] with no body
[XCUITestDriver@5eba] connect ECONNREFUSED 127.0.0.1:8107
[XCUITestDriver@5eba] Matched '/status' to command name 'getStatus'
[XCUITestDriver@5eba] Proxying [GET /status] to [GET http://127.0.0.1:8107/status] with no body
[XCUITestDriver@5eba] connect ECONNREFUSED 127.0.0.1:8107
[XCUITestDriver@5eba] Matched '/status' to command name 'getStatus'
[XCUITestDriver@5eba] Proxying [GET /status] to [GET http://127.0.0.1:8107/status] with no body
[XCUITestDriver@5eba] connect ECONNREFUSED 127.0.0.1:8107
[XCUITestDriver@5eba] Matched '/status' to command name 'getStatus'
[XCUITestDriver@5eba] Proxying [GET /status] to [GET http://127.0.0.1:8107/status] with no body
[XCUITestDriver@5eba] connect ECONNREFUSED 127.0.0.1:8107

**Comment by mykola-mokhnach** [comment]
> Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65. This usually indicates an issue with the local Xcode setup or WebDriverAgent project configuration or the driver-to-platform version mismatch. Consider setting 'showXcodeLog' capability to true in order to check the Appium server log for build-related error messages.. Make sure you follow the tutorial at https://appium.github.io/appium-xcuitest-driver/latest/preparation/real-device-config/. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.

Is this your error? Have you tried to do what it suggests?

**Comment by mykola-mokhnach** [comment]
Closed because of no response
