### ISSUE TITLE
Appium v2.4.1 get error write EPIPE

### ISSUE THREAD

**Issue by yyuanmeme** [appium/appium#19837]
2024-02-28 14:35:03:885 uncaughtException: write EPIPE
Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:952:11)
    at Socket._write (node:net:964:8)
    at writeOrBuffer (node:internal/streams/writable:556:12)
    at _write (node:internal/streams/writable:490:10)
    at Socket.Writable.write (node:internal/streams/writable:494:10)
    at Console.log (/usr/local/lib/node_modules/appium/node_modules/winston/lib/winston/transports/console.js:79:23)
    at Console._write (/usr/local/lib/node_modules/appium/node_modules/winston-transport/index.js:103:17)
    at doWrite (/usr/local/lib/node_modules/appium/node_modules/readable-stream/lib/_stream_writable.js:390:139)
    at writeOrBuffer (/usr/local/lib/node_modules/appium/node_modules/readable-stream/lib/_stream_writable.js:381:5)
    at Console.Writable.write (/usr/local/lib/node_modules/appium/node_modules/readable-stream/lib/_stream_writable.js:302:11)
    at DerivedLogger.ondata (/usr/local/lib/node_modules/appium/node_modules/readable-stream/lib/_stream_readable.js:629:20)
    at DerivedLogger.emit (node:events:527:35)
    at addChunk (/usr/local/lib/node_modules/appium/node_modules/readable-stream/lib/_stream_readable.js:279:12)
    at readableAddChunk (/usr/local/lib/node_modules/appium/node_modules/readable-stream/lib/_stream_readable.js:262:11)
    at DerivedLogger.Readable.push (/usr/local/lib/node_modules/appium/node_modules/readable-stream/lib/_stream_readable.js:228:10)
    at DerivedLogger.Transform.push (/usr/local/lib/node_modules/appium/node_modules/readable-stream/lib/_stream_transform.js:132:32)
    at DerivedLogger._transform (/usr/local/lib/node_modules/appium/node_modules/winston/lib/winston/logger.js:313:12)
    at DerivedLogger.Transform._read (/usr/local/lib/node_modules/appium/node_modules/readable-stream/lib/_stream_transform.js:166:10)
    at DerivedLogger.Transform._write (/usr/local/lib/node_modules/appium/node_modules/readable-stream/lib/_stream_transform.js:155:83)
    at doWrite (/usr/local/lib/node_modules/appium/node_modules/readable-stream/lib/_stream_writable.js:390:139)
    at writeOrBuffer (/usr/local/lib/node_modules/appium/node_modules/readable-stream/lib/_stream_writable.js:381:5)
    at DerivedLogger.Writable.write (/usr/local/lib/node_modules/appium/node_modules/readable-stream/lib/_stream_writable.js:302:11)
    at DerivedLogger.<computed> [as info] (/usr/local/lib/node_modules/appium/node_modules/winston/lib/winston/create-logger.js:81:14)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/appium/lib/logsink.js:220:22)
    at EventEmitter.emit (node:events:515:28)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/appium/node_modules/npmlog/lib/log.js:247:8)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/appium/node_modules/npmlog/lib/log.js:377:23)
    at Object.wrappedLogger.<computed> [as info] (/usr/local/lib/node_modules/appium/node_modules/@appium/support/lib/logging.js:106:24)
    at process.onSignal (/usr/local/lib/node_modules/appium/lib/main.js:419:14)
    at Object.onceWrapper (node:events:630:26)
    at process.emit (node:events:527:35)

**Comment by yyuanmeme** [comment]
driver log
[Uploading log.txt…]()

**Comment by eglitise** [comment]
Please fill out the issue report according to the provided issue template.
Closing as incomplete
