### ISSUE TITLE
Appium doesn't locate iOS keyboard toolbar buttons on iOS 17.4

### ISSUE THREAD

**Issue by itkhanz** [appium/appium#19889]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have an iOS application running on real device iOS version 17.4.
I am trying to hide keyboard on iOS by tapping on `Done` button that appears on UI as part of keyboard. This Done button appears on top-right of the keyboard as part of iOS system and not something that can be controlled by developers.

I have tried to locate this element via Appium Inspector but it does not show up in the Appium Inspector.

In attached screenshot, you can see the Done button on top-right of keyboard.
![Screenshot 2024-03-12 at 15 52 03](https://github.com/appium/appium/assets/62521743/d098ad76-04a8-433c-99ec-0aace5b43d61)

It shows the whole toolbar as `XCUIElementTypeOther` and does not allow to locate the elements within it.
![Screenshot 2024-03-12 at 15 59 49](https://github.com/appium/appium/assets/62521743/293e4aca-ab3b-4b4c-ae48-c9c5e2042606)

### Expected Behavior

Appium Inspector should allow me to locate this element, so I can find the locator and pass it to my test scripts for interacting with keyboard.

Please note that this issue started happening with latest iOS 17.4 update. This button was locatable with iOS 17.2 and also on iOS 16 but after I updated to iOS 17.4, I am not able to locate this button. 
This is how this button is shown in the Appium Inspector if I inspect it on simulator with iOS 17.2

![Screenshot 2024-03-13 at 06 51 52](https://github.com/appium/appium/assets/62521743/8348c85d-6f69-4bdd-a3b2-165f211a0498)
 
so as per the image above, if I use the locator on device with iOS version 17.4
`@iOSXCUITFindBy(xpath = "//XCUIElementTypeToolbar[@name='Toolbar']//XCUIElementTypeButton[contains(@name, 'Done')]")`

Appium is unable to locate this element and throws error

```
org.openqa.selenium.NoSuchElementException: Can't locate an element by this strategy: By.chained({By.xpath: //XCUIElementTypeToolbar[@name='Toolbar']//XCUIElementTypeButton[contains(@name, 'Done')]})
	at app//io.appium.java_client.pagefactory.AppiumElementLocator.findElement(AppiumElementLocator.java:166)
	at app//io.appium.java_client.pagefactory.interceptors.InterceptorOfASingleElement.call(InterceptorOfASingleElement.java:64)
	at app//io.appium.java_client.proxy.Interceptor.intercept(Interceptor.java:78)
	at org.openqa.selenium.remote.RemoteWebElement$ByteBuddy$j1qJKSUY.click(Unknown Source)
```

### Minimal Reproducible Example

```
public class Login {

@iOSXCUITFindBy(xpath = "//XCUIElementTypeToolbar[@name='Toolbar']//XCUIElementTypeButton[contains(@name, 'Done')]")
private WebElement doneButton;

public void hideKeyboard() {
        doneButton.click();
}

}
```

### Environment

Operating system: MacOS Sonoma 14.2.1
Appium server version (output of appium --version): 2.4.1
Appium driver(s) and their version(s): xcuitest@5.16.1
Node.js version (output of node --version): 20.11.0
npm version (output of npm --version): 10.2.4
Appium Inspector version: 2023.12.2
Real device or emulator/simulator: iPhone 13 Pro (real device) - iOS 17.4

### Link to Appium Logs

https://gist.github.com/itkhanz/62b0b97819dca51d71c1cedc1cc18e4f

### Further Information

Appium Server logs
```

[XCUITestDriver@d9d1 (cd990c3b)] Calling AppiumDriver.getCurrentContext() with args: ["cd990c3b-37a2-46f8-9174-88f0f4fba7cc"]
[XCUITestDriver@d9d1 (cd990c3b)] Executing command 'getCurrentContext'
[XCUITestDriver@d9d1 (cd990c3b)] Responding to client with driver.getCurrentContext() result: "NATIVE_APP"
[HTTP] <-- GET /session/cd990c3b-37a2-46f8-9174-88f0f4fba7cc/context 200 1 ms - 22
[HTTP] 
[HTTP] --> POST /session/cd990c3b-37a2-46f8-9174-88f0f4fba7cc/element
[HTTP] {"using":"xpath","value":"//XCUIElementTypeToolbar[@name='Toolbar']//XCUIElementTypeButton[contains(@name, 'Done')]"}
[XCUITestDriver@d9d1 (cd990c3b)] Calling AppiumDriver.findElement() with args: ["xpath","//XCUIElementTypeToolbar[@name='Toolbar']//XCUIElementTypeButton[contains(@name, 'Done')]","cd990c3b-37a2-46f8-9174-88f0f4fba7cc"]
[XCUITestDriver@d9d1 (cd990c3b)] Executing command 'findElement'
[XCUITestDriver@d9d1 (cd990c3b)] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id, css selector
[XCUITestDriver@d9d1 (cd990c3b)] Waiting up to 3000 ms for condition
[XCUITestDriver@d9d1 (cd990c3b)] Matched '/element' to command name 'findElement'
[XCUITestDriver@d9d1 (cd990c3b)] Proxying [POST /element] to [POST http://127.0.0.1:8006/session/DA5D4B79-465E-48D4-AF26-469C149C4DF0/element] with body: {"using":"xpath","value":"//XCUIElementTypeToolbar[@name='Toolbar']//XCUIElementTypeButton[contains(@name, 'Done')]"}
[XCUITestDriver@d9d1 (cd990c3b)] Got response with status 404: {"value":{"error":"no such element","message":"unable to find an element using 'xpath', value '//XCUIElementTypeToolbar[@name='Toolbar']//XCUIElementTypeButton[contains(@name, 'Done')]'","traceback":"(\n\t0   WebDriverAgentLib                   0x000000010727c84c FBNoSuchElementErrorResponseForRequest + 252\n\t1   WebDriverAgentLib                   0x000000010727c67c +[FBFindElementCommands handleFindElement:] + 312\n\t2   WebDriverAgentLib                   0x0000000107240c10 -[FBRoute_TargetAction mountRequest:intoResponse:] + 168\n\t3   WebDriverAgentLib                   0x000000010722c064 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 404\n\t4   WebDriverAgentLib                   0x0000000107262bf4 -[RoutingHTTPServer handleRoute:withRequest:response:] + 168\n\t5   WebDriverAgentLib                   0x00000001072636e4 __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 64\n\t6   libdispatch.dylib                   0x0000000199ee6dd4 7835E829-0652-3C...
[W3C] Matched W3C error code 'no such element' to NoSuchElementError
[XCUITestDriver@d9d1 (cd990c3b)] Waited for 529 ms so far
[XCUITestDriver@d9d1 (cd990c3b)] Matched '/element' to command name 'findElement'
[XCUITestDriver@d9d1 (cd990c3b)] Proxying [POST /element] to [POST http://127.0.0.1:8006/session/DA5D4B79-465E-48D4-AF26-469C149C4DF0/element] with body: {"using":"xpath","value":"//XCUIElementTypeToolbar[@name='Toolbar']//XCUIElementTypeButton[contains(@name, 'Done')]"}
[XCUITestDriver@d9d1 (cd990c3b)] Got response with status 404: {"value":{"error":"no such element","message":"unable to find an element using 'xpath', value '//XCUIElementTypeToolbar[@name='Toolbar']//XCUIElementTypeButton[contains(@name, 'Done')]'","traceback":"(\n\t0   WebDriverAgentLib                   0x000000010727c84c FBNoSuchElementErrorResponseForRequest + 252\n\t1   WebDriverAgentLib                   0x000000010727c67c +[FBFindElementCommands handleFindElement:] + 312\n\t2   WebDriverAgentLib                   0x0000000107240c10 -[FBRoute_TargetAction mountRequest:intoResponse:] + 168\n\t3   WebDriverAgentLib                   0x000000010722c064 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 404\n\t4   WebDriverAgentLib                   0x0000000107262bf4 -[RoutingHTTPServer handleRoute:withRequest:response:] + 168\n\t5   WebDriverAgentLib                   0x00000001072636e4 __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 64\n\t6   libdispatch.dylib                   0x0000000199ee6dd4 7835E829-0652-3C...
[W3C] Matched W3C error code 'no such element' to NoSuchElementError
[XCUITestDriver@d9d1 (cd990c3b)] Waited for 1561 ms so far
[XCUITestDriver@d9d1 (cd990c3b)] Matched '/element' to command name 'findElement'
[XCUITestDriver@d9d1 (cd990c3b)] Proxying [POST /element] to [POST http://127.0.0.1:8006/session/DA5D4B79-465E-48D4-AF26-469C149C4DF0/element] with body: {"using":"xpath","value":"//XCUIElementTypeToolbar[@name='Toolbar']//XCUIElementTypeButton[contains(@name, 'Done')]"}
[XCUITestDriver@d9d1 (cd990c3b)] Got response with status 404: {"value":{"error":"no such element","message":"unable to find an element using 'xpath', value '//XCUIElementTypeToolbar[@name='Toolbar']//XCUIElementTypeButton[contains(@name, 'Done')]'","traceback":"(\n\t0   WebDriverAgentLib                   0x000000010727c84c FBNoSuchElementErrorResponseForRequest + 252\n\t1   WebDriverAgentLib                   0x000000010727c67c +[FBFindElementCommands handleFindElement:] + 312\n\t2   WebDriverAgentLib                   0x0000000107240c10 -[FBRoute_TargetAction mountRequest:intoResponse:] + 168\n\t3   WebDriverAgentLib                   0x000000010722c064 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 404\n\t4   WebDriverAgentLib                   0x0000000107262bf4 -[RoutingHTTPServer handleRoute:withRequest:response:] + 168\n\t5   WebDriverAgentLib                   0x00000001072636e4 __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 64\n\t6   libdispatch.dylib                   0x0000000199ee6dd4 7835E829-0652-3C...
[W3C] Matched W3C error code 'no such element' to NoSuchElementError
[XCUITestDriver@d9d1 (cd990c3b)] Waited for 2598 ms so far
[XCUITestDriver@d9d1 (cd990c3b)] Matched '/element' to command name 'findElement'
[XCUITestDriver@d9d1 (cd990c3b)] Proxying [POST /element] to [POST http://127.0.0.1:8006/session/DA5D4B79-465E-48D4-AF26-469C149C4DF0/element] with body: {"using":"xpath","value":"//XCUIElementTypeToolbar[@name='Toolbar']//XCUIElementTypeButton[contains(@name, 'Done')]"}
[XCUITestDriver@d9d1 (cd990c3b)] Got response with status 404: {"value":{"error":"no such element","message":"unable to find an element using 'xpath', value '//XCUIElementTypeToolbar[@name='Toolbar']//XCUIElementTypeButton[contains(@name, 'Done')]'","traceback":"(\n\t0   WebDriverAgentLib                   0x000000010727c84c FBNoSuchElementErrorResponseForRequest + 252\n\t1   WebDriverAgentLib                   0x000000010727c67c +[FBFindElementCommands handleFindElement:] + 312\n\t2   WebDriverAgentLib                   0x0000000107240c10 -[FBRoute_TargetAction mountRequest:intoResponse:] + 168\n\t3   WebDriverAgentLib                   0x000000010722c064 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 404\n\t4   WebDriverAgentLib                   0x0000000107262bf4 -[RoutingHTTPServer handleRoute:withRequest:response:] + 168\n\t5   WebDriverAgentLib                   0x00000001072636e4 __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 64\n\t6   libdispatch.dylib                   0x0000000199ee6dd4 7835E829-0652-3C...
[W3C] Matched W3C error code 'no such element' to NoSuchElementError
[XCUITestDriver@d9d1 (cd990c3b)] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
[XCUITestDriver@d9d1 (cd990c3b)]     at XCUITestDriver.doNativeFind (/Users/xxxx/.appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:143:13)
[XCUITestDriver@d9d1 (cd990c3b)]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[XCUITestDriver@d9d1 (cd990c3b)]     at XCUITestDriver.findNativeElementOrElements (/Users/xxxx/.appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:97:12)
[XCUITestDriver@d9d1 (cd990c3b)]     at XCUITestDriver.findElOrEls (/Users/xxxx/.appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:24:14)
[XCUITestDriver@d9d1 (cd990c3b)]     at XCUITestDriver.findElOrElsWithProcessing (/Users/xxxx/.nvm/versions/node/v20.11.0/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:60:12)
[XCUITestDriver@d9d1 (cd990c3b)]     at XCUITestDriver.findElement (/Users/xxxx/.nvm/versions/node/v20.11.0/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:75:12)
[HTTP] <-- POST /session/cd990c3b-37a2-46f8-9174-88f0f4fba7cc/element 404 3533 ms - 1093
```

**Comment by mykola-mokhnach** [comment]
Unfortunately it is impossible for us to influence this behaviour. The page tree is retrieved by XCTest based on the accessibility info. Most likely that element is not accessible and only Apple itself could change that.

Closed as third party issue

**Comment by itkhanz** [comment]
> Unfortunately it is impossible for us to influence this behaviour. The page tree is retrieved by XCTest based on the accessibility info. Most likely that element is not accessible and only Apple itself could change that.
> 
> Closed as third party issue

The issue I was facing occured when I upgraded my iOS to 17.4 and also updated Appium XCUITest driver to 5.16.1 which caused Appium to not interact with this button.


I have removed the Appium WebDriverAgent from system, and uninstalled the xcuitest driver.

@mykola-mokhnach Interestingly I managed to resolve this issue by downgrading XCUITest driver to version 5.14.2. Now it works with the iOS version 17.4 as well.

I am not sure what caused this to not work with XCUITest driver 5.16.1 and latest WebDriverAgent

**Comment by eglitise** [comment]
@itkhanz please be aware that the current version of XCUITest driver is 7.3.0. Version 5.16.1 is merely the last 5.x version.

I have also occasionally noticed similar issues after updating the minor iOS version, where some elements are no longer visible, or change their attribute values. It's possible that this is the case here as well.

**Comment by KazuCocoa** [comment]
Then, perhaps the area was managed by springboard.
https://appium.github.io/appium-xcuitest-driver/latest/guides/troubleshooting/#interact-with-dialogs-managed-by-comapplespringboard might help in some cases

**Comment by mykola-mokhnach** [comment]
Use methods that are dedicated for working with alerts: https://github.com/appium/appium/issues/19889#issuecomment-1994155625
