### ISSUE TITLE
Not able to take screenshot on Tizen TV

### ISSUE THREAD

**Issue by Jiyvn** [appium/appium#19905]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Not able to capture screen on Tizen TV
> Mar 18, 2024 6:38:31 PM org.openqa.selenium.remote.ErrorCodes toStatus
INFO: HTTP Status: '408' -> incorrect JSON status mapping for 'timeout' (500 expected)
      org.openqa.selenium.TimeoutException: timeout: Timed out receiving message from renderer: 9.999
  (Session info: chrome=69.0.3497.128)
  (Driver info: chromedriver=2.44.609545 (c2f88692e98ce7233d2df7c724465ecacfe74df5),platform=Mac OS X 10.16.0 x86_64)
Build info: version: '4.18.1', revision: 'b1d3319b48'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '14.0', java.version: '17.0.7'
Driver info: io.appium.java_client.AppiumDriver
Command: [16a06b95-908c-4ae5-a9fe-c1eb2aa673fb, screenshot {}]
Capabilities {appium:app: /Users/$USER/aviu/apps/Viu_..., appium:appLaunchCooldown: 3000, appium:appPackage: TXSXgdzhCp.Viu, appium:automationName: TizenTV, appium:chromedriverExecutableDir: /Users/$USER/aviu/apps/tv/c..., appium:deviceAddress: 192.168.10.184:26101, appium:deviceName: Tizen5.5 2020, appium:fullContextList: true, appium:noReset: false, appium:rcMode: remote, appium:rcToken: 15615414, appium:udid: 192.168.10.184:26101, platformName: TizenTV}
Session ID: 16a06b95-908c-4ae5-a9fe-c1eb2aa673fb
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
        at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
        at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:190)
        at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:237)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:519)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:592)
        at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:307)
        at org.openqa.selenium.remote.RemoteWebDriver.getScreenshotAs(RemoteWebDriver.java:322)
        at io.appium.java_client.AppiumDriver.getScreenshotAs(AppiumDriver.java:316)
        at steps.tizenTVDemoStepDef.afterScenario(tizenTVDemoStepDef.java:59)

### Expected Behavior

able to take screenshot

### Minimal Reproducible Example

```java
BaseOptions options = new BaseOptions()
        .amend("appium:deviceName", "Tizen5.5 2020")
        .amend("platformName", "TizenTV")
        .amend("appium:automationName", "TizenTV")
        .amend("appium:udid", "192.168.10.184:26101")
        .amend("appium:deviceAddress", "192.168.10.184:26101")
        .amend("appium:noReset", false)
        .amend("appium:fullContextList", true)
        .amend("appium:app", "/Users/$USER/aviu/apps/Viu_dev.wgt")
        .amend("appium:chromedriverExecutableDir", "/Users/$USER/aviu/apps/tv/chromedriver/")
        .amend("appium:rcMode", "remote")
        .amend("appium:rcToken", "15615414")
        .amend("appium:appPackage", "TXSXgdzhCp");

driver = new AppiumDriver(new URL("http://127.0.0.1:4723"), options);
// sleep for a while
...
byte[] bytes = ((TakesScreenshot) driver).getScreenshotAs(OutputType.BYTES);
```

### Environment

- Operating system: MacOS 14.0 (m1)
- JDK Version: 17
- Appium server version (output of `appium --version`): 2.5.1
- Appium Java cllient: 9.1.0
- Appium driver(s) and their version(s):  tizentv@0.10.0 (headspin)
- Appium plugin(s) and their version(s): images@2.1.2 (not loaded)
- Node.js version (output of `node --version`): v20.11.1
- `npm` version (output of `npm --version`): 10.2.4
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: Tizen 5.5
- Real device or emulator/simulator: Tizen TV 2020

### Link to Appium Logs

https://gist.github.com/Jiyvn/755599c542a3475eaf399473161b3a1c

**Comment by KazuCocoa** [comment]
Please report to proper repository. The driver is not maintained by Appium team.
