### ISSUE TITLE
_XCT_requestScreenshot in iOS 13.1.2 real device，doesn't work

### ISSUE THREAD

**Issue by yutiya** [appium/appium#19925]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![WX20240327-111600](https://github.com/appium/appium/assets/12824969/a429209a-9d47-43d3-91f2-ff037898765e)
当程序执行到该行后，未执行回调。导致程序停止运行

### Expected Behavior

在模拟器中执行，正常返回屏幕截图，Appium Inspector能正常显示屏幕图像
真机执行，直接停止运行，导致不显示图像

### Minimal Reproducible Example

```
[proxy _XCT_requestScreenshot:screnshotRequest
                      withReply:^(id image, NSError *err) {
    if (nil != err) {
      innerError = err;
    } else {
      screenshotData = [image data];
    }
    dispatch_semaphore_signal(sem);
  }];
  int64_t timeoutNs = (int64_t)(timeout * NSEC_PER_SEC);
  if (0 != dispatch_semaphore_wait(sem, dispatch_time(DISPATCH_TIME_NOW, timeoutNs))) {
    NSString *timeoutMsg = [NSString stringWithFormat:@"Cannot take a screenshot within %@ timeout", formatTimeInterval(SCREENSHOT_TIMEOUT)];
    if (nil == error) {
      [FBLogger log:timeoutMsg];
    } else if (nil == innerError) {
      [[[FBErrorBuilder builder]
        withDescription:timeoutMsg]
       buildError:error];
    }
  };
```

### Environment

- Operating system: macOS Sonoma 版本14.2 (23C64)
- Appium server version (output of `appium --version`): 2.5.1
- Appium driver(s) and their version(s):  7.5.4
- Appium plugin(s) and their version(s): none
- Node.js version (output of `node --version`): v20.4.0
- `npm` version (output of `npm --version`): 9.7.2
- Last component(s) version which did _not_ exhibit the problem: none
- Platform and version under test: Xcode 15.1, iOS SDK 17.0
- Real device or emulator/simulator: read device iOS 13.1.2，appium:platformVersion 11.0

### Further Information

Call POST http://127.0.0.1:8100/session 
Next：
```
Calling AppiumDriver.getScreenshot() with args: ["a4974b03-ccf1-43cb-9697-0168804e5aa9"]
[XCUITestDriver@a8cc (a4974b03)] Executing command 'getScreenshot'
[XCUITestDriver@a8cc (a4974b03)] Taking screenshot with WDA
[XCUITestDriver@a8cc (a4974b03)] Matched '/screenshot' to command name 'getScreenshot'
[XCUITestDriver@a8cc (a4974b03)] Proxying [GET /screenshot] to [GET http://127.0.0.1:8100/session/205987AE-91CA-4098-A29D-D5507554AE33/screenshot] with no body
[XCUITestDriver@a8cc (a4974b03)] socket hang up
[XCUITestDriver@a8cc (a4974b03)] Error getting screenshot: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
[XCUITestDriver@a8cc (a4974b03)] Taking screenshot with WDA
[XCUITestDriver@a8cc (a4974b03)] Matched '/screenshot' to command name 'getScreenshot'
[XCUITestDriver@a8cc (a4974b03)] Proxying [GET /screenshot] to [GET http://127.0.0.1:8100/session/205987AE-91CA-4098-A29D-D5507554AE33/screenshot] with no body
[iProxy@00008030:8100] Connection was refused to port 8100
[XCUITestDriver@a8cc (a4974b03)] socket hang up
[XCUITestDriver@a8cc (a4974b03)] Taking screenshot with WDA
[XCUITestDriver@a8cc (a4974b03)] Matched '/screenshot' to command name 'getScreenshot'
[XCUITestDriver@a8cc (a4974b03)] Proxying [GET /screenshot] to [GET http://127.0.0.1:8100/session/205987AE-91CA-4098-A29D-D5507554AE33/screenshot] with no body
[iProxy@00008030:8100] Connection was refused to port 8100
[XCUITestDriver@a8cc (a4974b03)] socket hang up
[XCUITestDriver@a8cc (a4974b03)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
[XCUITestDriver@a8cc (a4974b03)]     at JWProxy.command (/Users/xusong/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:355:13)
[XCUITestDriver@a8cc (a4974b03)]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[XCUITestDriver@a8cc (a4974b03)]     at XCUITestDriver.proxyCommand (/Users/xusong/.appium/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:103:35)
[XCUITestDriver@a8cc (a4974b03)]     at getScreenshotFromWDA (/Users/xusong/.appium/node_modules/appium-xcuitest-driver/lib/commands/screenshots.js:12:20)
[XCUITestDriver@a8cc (a4974b03)]     at wrapped (/Users/xusong/.appium/node_modules/appium-xcuitest-driver/node_modules/asyncbox/lib/asyncbox.js:93:13)
[XCUITestDriver@a8cc (a4974b03)]     at retry (/Users/xusong/.appium/node_modules/appium-xcuitest-driver/node_modules/asyncbox/lib/asyncbox.js:66:13)
[XCUITestDriver@a8cc (a4974b03)]     at retryInterval (/Users/xusong/.appium/node_modules/appium-xcuitest-driver/node_modules/asyncbox/lib/asyncbox.js:103:10)
[XCUITestDriver@a8cc (a4974b03)]     at XCUITestDriver.getScreenshot (/Users/xusong/.appium/node_modules/appium-xcuitest-driver/lib/commands/screenshots.js:46:12)
[HTTP] <-- GET /session/a4974b03-ccf1-43cb-9697-0168804e5aa9/screenshot 500 1051 ms - 1374
[HTTP] 
[HTTP] --> GET /session/a4974b03-ccf1-43cb-9697-0168804e5aa9/window/rect
[HTTP] {}
[XCUITestDriver@a8cc (a4974b03)] Calling AppiumDriver.getWindowRect() with args: ["a4974b03-ccf1-43cb-9697-0168804e5aa9"]
[XCUITestDriver@a8cc (a4974b03)] Executing command 'getWindowRect'
[XCUITestDriver@a8cc (a4974b03)] Proxying [GET /window/size] to [GET http://127.0.0.1:8100/session/205987AE-91CA-4098-A29D-D5507554AE33/window/size] with no body
[iProxy@00008030:8100] Connection was refused to port 8100
[XCUITestDriver@a8cc (a4974b03)] socket hang up
[XCUITestDriver@a8cc (a4974b03)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
[XCUITestDriver@a8cc (a4974b03)]     at JWProxy.command (/Users/xusong/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:355:13)
[XCUITestDriver@a8cc (a4974b03)]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[XCUITestDriver@a8cc (a4974b03)]     at XCUITestDriver.proxyCommand (/Users/xusong/.appium/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:103:35)
[XCUITestDriver@a8cc (a4974b03)]     at XCUITestDriver.getWindowSizeNative (/Users/xusong/.appium/node_modules/appium-xcuitest-driver/lib/commands/general.js:278:12)
[XCUITestDriver@a8cc (a4974b03)]     at XCUITestDriver.getWindowSize (/Users/xusong/.appium/node_modules/appium-xcuitest-driver/lib/commands/general.js:52:14)
[XCUITestDriver@a8cc (a4974b03)]     at XCUITestDriver.getWindowRect (/Users/xusong/.appium/node_modules/appium-xcuitest-driver/lib/commands/general.js:121:29)
[HTTP] <-- GET /session/a4974b03-ccf1-43cb-9697-0168804e5aa9/window/rect 500 21 ms - 1144
[HTTP] 
[HTTP] --> GET /session/a4974b03-ccf1-43cb-9697-0168804e5aa9/source
[HTTP] {}
[XCUITestDriver@a8cc (a4974b03)] Calling AppiumDriver.getPageSource() with args: ["a4974b03-ccf1-43cb-9697-0168804e5aa9"]
[XCUITestDriver@a8cc (a4974b03)] Executing command 'getPageSource'
[XCUITestDriver@a8cc (a4974b03)] Matched '/source?format=xml&scope=AppiumAUT' to command name 'getPageSource'
[XCUITestDriver@a8cc (a4974b03)] Proxying [GET /source?format=xml&scope=AppiumAUT] to [GET http://127.0.0.1:8100/session/205987AE-91CA-4098-A29D-D5507554AE33/source?format=xml&scope=AppiumAUT] with no body
[iProxy@00008030:8100] Connection was refused to port 8100
[XCUITestDriver@a8cc (a4974b03)] socket hang up
[XCUITestDriver@a8cc (a4974b03)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
[XCUITestDriver@a8cc (a4974b03)]     at JWProxy.command (/Users/xusong/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:355:13)
[XCUITestDriver@a8cc (a4974b03)]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[XCUITestDriver@a8cc (a4974b03)]     at XCUITestDriver.proxyCommand (/Users/xusong/.appium/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:103:35)
[XCUITestDriver@a8cc (a4974b03)]     at XCUITestDriver.mobileGetSource (/Users/xusong/.appium/node_modules/appium-xcuitest-driver/lib/commands/source.js:50:35)
[XCUITestDriver@a8cc (a4974b03)]     at XCUITestDriver.getPageSource (/Users/xusong/.appium/node_modules/appium-xcuitest-driver/lib/commands/source.js:25:9)
[HTTP] <-- GET /session/a4974b03-ccf1-43cb-9697-0168804e5aa9/source 500 18 ms - 1008
[HTTP] 
[HTTP] --> GET /session/a4974b03-ccf1-43cb-9697-0168804e5aa9/timeouts
[HTTP] {}
```
![WX20240327-112809](https://github.com/appium/appium/assets/12824969/8ca2f6c3-f7b8-48f5-96de-ee7bdad0da3b)

经过调试，当真机执行
```
[proxy _XCT_requestScreenshot:screnshotRequest
                      withReply:^(id image, NSError *err) {
    if (nil != err) {
      innerError = err;
    } else {
      screenshotData = [image data];
    }
    dispatch_semaphore_signal(sem);
  }];
```
一直未回调，并停止运行，导致xcuitest不执行后续 http响应

real device iOS 13.1.2
use Xcode 15.1，iOS SDK 17.0
```
{
  "platformName": "ios",
  "appium:platformVersion": "11.0",
  "appium:app": "xxxx",
  "appium:udid": "xxxx",
  "appium:noReset": true,
  "appium:automationName": "XCUITest",
  "appium:newCommandTimeout": "10000",
  "appium:showXcodeLog": false,
  "appium:showIOSLog": false
}
```

**Comment by KazuCocoa** [comment]
It is expected. XCTest driver 4.27.2+ support iOS 15+ only. We removed several workarounds for older OS versions over the version.
https://appium.github.io/appium-xcuitest-driver/latest/installation/requirements/

**Comment by yutiya** [comment]
3q，iOS 15.4.1 运行正常
