### ISSUE TITLE
Support for bun in appium-adb

### ISSUE THREAD

**Issue by heri16** [appium/appium#19920]
Using bun got this error:
```bash
$ bun demo2.ts
583 |     if (aNeedle[aLineName] <= 0) {
584 |       throw new TypeError('Line must be greater than or equal to 1, got '
585 |                           + aNeedle[aLineName]);
586 |     }
587 |     if (aNeedle[aColumnName] < 0) {
588 |       throw new TypeError('Column must be greater than or equal to 0, got '
                  ^
TypeError: Column must be greater than or equal to 0, got -1
      at SourceMapConsumer_findMapping (/Users/heri/work/bankscan/node_modules/source-map/lib/source-map-consumer.js:588:13)
      at SourceMapConsumer_originalPositionFor (/Users/heri/work/bankscan/node_modules/source-map/lib/source-map-consumer.js:653:17)
      at mapSourcePosition (/Users/heri/work/bankscan/node_modules/source-map-support/source-map-support.js:244:28)
      at wrapCallSite (/Users/heri/work/bankscan/node_modules/source-map-support/source-map-support.js:397:20)
      at prepareStackTrace (/Users/heri/work/bankscan/node_modules/source-map-support/source-map-support.js:446:39)
      at /Users/heri/work/bankscan/node_modules/bluebird/js/release/debuggability.js:903:13
      at new CapturedTrace (/Users/heri/work/bankscan/node_modules/bluebird/js/release/debuggability.js:807:5)
      at longStackTracesCaptureStackTrace (/Users/heri/work/bankscan/node_modules/bluebird/js/release/debuggability.js:482:19)
      at doThenable (/Users/heri/work/bankscan/node_modules/bluebird/js/release/thenables.js:60:5)
      at tryConvertToPromise (/Users/heri/work/bankscan/node_modules/bluebird/js/release/thenables.js:28:20)
      at /Users/heri/work/bankscan/node_modules/bluebird/js/release/promise.js:222:15
      at glob (/Users/heri/work/bankscan/node_modules/@appium/support/build/lib/fs.js:146:117)
      at /Users/heri/work/bankscan/node_modules/appium-adb/build/lib/helpers.js:453:32
      at getBuildToolsDirs (/Users/heri/work/bankscan/node_modules/appium-adb/build/lib/helpers.js:452:85)
      at memoized (/Users/heri/work/bankscan/node_modules/lodash/lodash.js:10620:22)
      at /Users/heri/work/bankscan/node_modules/appium-adb/build/lib/tools/system-calls.js:102:36
      at getBinaryFromSdkRoot (/Users/heri/work/bankscan/node_modules/appium-adb/build/lib/tools/system-calls.js:94:78)
      at /Users/heri/work/bankscan/node_modules/appium-adb/build/lib/tools/system-calls.js:48:18
      at getSdkBinaryPath (/Users/heri/work/bankscan/node_modules/appium-adb/build/lib/tools/system-calls.js:47:70)
      at /Users/heri/work/bankscan/node_modules/appium-adb/build/lib/tools/adb-commands.js:91:34
      at getAdbWithCorrectAdbPath (/Users/heri/work/bankscan/node_modules/appium-adb/build/lib/tools/adb-commands.js:90:78)
      at /Users/heri/work/bankscan/node_modules/appium-adb/build/lib/adb.js:90:15
```

Using node was fine:
```bash
$ npx vite-node demo2.ts
info ADB Found 0 'build-tools' folders under '/Users/heri/homebrew/Caskroom/android-platform-tools/35.0.0' (newest first):
info ADB Using 'adb' from '/Users/heri/homebrew/Caskroom/android-platform-tools/35.0.0/platform-tools/adb'
dbug ADB Running '/Users/heri/homebrew/Caskroom/android-platform-tools/35.0.0/platform-tools/adb -P 5037 start-server'
dbug SettingsApp Retrieving the recent SMS messages
dbug ADB Running '/Users/heri/homebrew/Caskroom/android-platform-tools/35.0.0/platform-tools/adb -P 5037 shell getprop ro.build.version.sdk'
dbug ADB Current device property 'ro.build.version.sdk': 33
info ADB Getting device platform version
dbug ADB Running '/Users/heri/homebrew/Caskroom/android-platform-tools/35.0.0/platform-tools/adb -P 5037 shell getprop ro.build.version.release'
dbug ADB Current device property 'ro.build.version.release': 13
dbug ADB Device API level: 33
dbug ADB Running '/Users/heri/homebrew/Caskroom/android-platform-tools/35.0.0/platform-tools/adb -P 5037 shell dumpsys activity services io.appium.settings'
dbug ADB Running '/Users/heri/homebrew/Caskroom/android-platform-tools/35.0.0/platform-tools/adb -P 5037 shell am broadcast -n io.appium.settings/.receivers.SmsReader -a io.appium.settings.sms.read --es max 10'
{
  items: [
```

demo2.ts
```typescript
import ADB from 'appium-adb';
import { SettingsApp } from 'io.appium.settings';

async function main() {
  const adb = await ADB.createADB();
  const app = new SettingsApp({ adb: adb });
  console.info(await app.getSmsList({ max: 10 }));
}

main();
```

**Comment by mykola-mokhnach** [comment]
Sorry, but we don't have resources for that. We only officially support NPM. Consider creating a PR to fix that or forking the project.
