### ISSUE TITLE
Start appium with plugin - appium server starts with error when uiautomator2 or xcuitest drivers are installed

### ISSUE THREAD

**Issue by bwomsm1** [appium/appium#19984]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I am starting appium with the following CLI:
`appium --base-path=/wd/hub`

I am getting the following error:
```
[Appium] Welcome to Appium v2.5.2
[Appium] Non-default server args:
[Appium] {
[Appium]   basePath: '/wd/hub'
[Appium] }
[Appium] The autodetected Appium home path: /Users/boazwarshawsky/.appium
[Appium] Attempting to load driver uiautomator2...
[Appium] Attempting to load driver xcuitest...
[Appium] Requiring driver at /Users/boazwarshawsky/.appium/node_modules/appium-xcuitest-driver/build/index.js
[Appium] Requiring driver at /Users/boazwarshawsky/.appium/node_modules/appium-uiautomator2-driver/build/index.js
[Appium] Could not load driver 'xcuitest', so it will not be available. Error in loading the driver was: Cannot find module 'appium/driver'
[Appium] Require stack:
[Appium] - /Users/boazwarshawsky/.appium/node_modules/appium-xcuitest-driver/build/lib/driver.js
[Appium] - /Users/boazwarshawsky/.appium/node_modules/appium-xcuitest-driver/build/index.js
[Appium] Error: Cannot find module 'appium/driver'
[Appium] Require stack:
[Appium] - /Users/boazwarshawsky/.appium/node_modules/appium-xcuitest-driver/build/lib/driver.js
[Appium] - /Users/boazwarshawsky/.appium/node_modules/appium-xcuitest-driver/build/index.js
[Appium]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
[Appium]     at Function.Module._load (node:internal/modules/cjs/loader:981:27)
[Appium]     at Module.require (node:internal/modules/cjs/loader:1231:19)
[Appium]     at require (node:internal/modules/helpers:177:18)
[Appium]     at Object.<anonymous> (/Users/boazwarshawsky/.appium/node_modules/appium-xcuitest-driver/lib/driver.js:4:1)
[Appium]     at Module._compile (node:internal/modules/cjs/loader:1364:14)
[Appium]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
[Appium]     at Module.load (node:internal/modules/cjs/loader:1203:32)
[Appium]     at Function.Module._load (node:internal/modules/cjs/loader:1019:12)
[Appium]     at Module.require (node:internal/modules/cjs/loader:1231:19)
[Appium]     at require (node:internal/modules/helpers:177:18)
[Appium]     at Object.<anonymous> (/Users/boazwarshawsky/.appium/node_modules/appium-xcuitest-driver/build/index.js:27:18)
[Appium]     at Module._compile (node:internal/modules/cjs/loader:1364:14)
[Appium]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
[Appium]     at Module.load (node:internal/modules/cjs/loader:1203:32)
[Appium]     at Function.Module._load (node:internal/modules/cjs/loader:1019:12)
[Appium]     at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:203:29)
[Appium]     at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
[Appium]     at ModuleLoader.import (node:internal/modules/esm/loader:337:24)
[Appium]     at importModuleDynamicallyWrapper (node:internal/vm/module:432:15)
[Appium]     at DriverConfig.requireAsync (/usr/local/lib/node_modules/appium/lib/extension/extension-config.js:600:24)
[Appium]     at /usr/local/lib/node_modules/appium/lib/extension/index.js:53:26
[Appium] Could not load driver 'uiautomator2', so it will not be available. Error in loading the driver was: Cannot find module 'appium/driver'
[Appium] Require stack:
[Appium] - /Users/boazwarshawsky/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/build/lib/driver.js
[Appium] - /Users/boazwarshawsky/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/build/lib/index.js
[Appium] - /Users/boazwarshawsky/.appium/node_modules/appium-uiautomator2-driver/build/lib/driver.js
[Appium] - /Users/boazwarshawsky/.appium/node_modules/appium-uiautomator2-driver/build/index.js
[Appium] Error: Cannot find module 'appium/driver'
[Appium] Require stack:
[Appium] - /Users/boazwarshawsky/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/build/lib/driver.js
[Appium] - /Users/boazwarshawsky/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/build/lib/index.js
[Appium] - /Users/boazwarshawsky/.appium/node_modules/appium-uiautomator2-driver/build/lib/driver.js
[Appium] - /Users/boazwarshawsky/.appium/node_modules/appium-uiautomator2-driver/build/index.js
[Appium]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
[Appium]     at Function.Module._load (node:internal/modules/cjs/loader:981:27)
[Appium]     at Module.require (node:internal/modules/cjs/loader:1231:19)
[Appium]     at require (node:internal/modules/helpers:177:18)
[Appium]     at Object.<anonymous> (/Users/boazwarshawsky/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/driver.ts:16:1)
[Appium]     at Module._compile (node:internal/modules/cjs/loader:1364:14)
[Appium]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
[Appium]     at Module.load (node:internal/modules/cjs/loader:1203:32)
[Appium]     at Function.Module._load (node:internal/modules/cjs/loader:1019:12)
[Appium]     at Module.require (node:internal/modules/cjs/loader:1231:19)
[Appium]     at require (node:internal/modules/helpers:177:18)
[Appium]     at Object.<anonymous> (/Users/boazwarshawsky/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/index.ts:4:1)
[Appium]     at Module._compile (node:internal/modules/cjs/loader:1364:14)
[Appium]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
[Appium]     at Module.load (node:internal/modules/cjs/loader:1203:32)
[Appium]     at Function.Module._load (node:internal/modules/cjs/loader:1019:12)
[Appium]     at Module.require (node:internal/modules/cjs/loader:1231:19)
[Appium]     at require (node:internal/modules/helpers:177:18)
[Appium]     at Object.<anonymous> (/Users/boazwarshawsky/.appium/node_modules/appium-uiautomator2-driver/lib/driver.ts:13:1)
[Appium]     at Module._compile (node:internal/modules/cjs/loader:1364:14)
[Appium]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
[Appium]     at Module.load (node:internal/modules/cjs/loader:1203:32)
[Appium]     at Function.Module._load (node:internal/modules/cjs/loader:1019:12)
[Appium]     at Module.require (node:internal/modules/cjs/loader:1231:19)
[Appium]     at require (node:internal/modules/helpers:177:18)
[Appium]     at Object.<anonymous> (/Users/boazwarshawsky/.appium/node_modules/appium-uiautomator2-driver/index.js:5:1)
[Appium]     at Module._compile (node:internal/modules/cjs/loader:1364:14)
[Appium]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
[Appium] Appium REST http interface listener started on http://0.0.0.0:4723/wd/hub
[Appium] You can provide the following URLs in your client code to connect to this server:
[Appium] 	http://127.0.0.1:4723/wd/hub (only accessible from the same host)
[Appium] 	http://192.168.31.192:4723/wd/hub
[Appium] 	http://10.100.102.5:4723/wd/hub
[Appium] 	http://10.212.134.170:4723/wd/hub
[Appium] Available drivers:
[Appium]   - uiautomator2@3.0.6 (automationName 'UiAutomator2')
[Appium]   - xcuitest@7.11.1 (automationName 'XCUITest')
[Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.
```

### Expected Behavior

Appium server should start correctly.

### Minimal Reproducible Example

Just run 
`appium --base-path=/wd/hub`

### Environment

- Operating system:
- Appium server version (output of `appium --version`): 2.5.2
- Appium driver(s) and their version(s):- uiautomator2@3.0.6 [installed (npm)]. xcuitest@7.11.1 [installed (npm)]
- 
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):18
- `npm` version (output of `npm --version`):10.5.0
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

### Further Information

I am using mac os,
I tried solving that issue with node version 20 or 18, but both are showing the error.
I tried also to uninstall and reinstall appium

**Comment by bwomsm1** [comment]
@jlipps hi,
We have discussed this issue in the past, and it seems that I am getting this error again. 
Last time, if I remember correctly I unisntalled and reinstalled Node, but it did not help this time. 

I have a brand new Mac that I am trying to setup. 


node version: v18.20.1
appium: latest and greatest. 


Can you please help me with that issue?

**Comment by bwomsm1** [comment]
> @mykola-mokhnach @jlipps Any news about this issue? I am experiencing the problem with another Mac

This time I installed node 18 on that machine but the same error is still raising

**Comment by jlipps** [comment]
What happens if you go into `/Users/boazwarshawsky/.appium/node_modules/appium-xcuitest-driver` and run `node -e 'require("appium/driver")`

**Comment by jlipps** [comment]
also, double check there are no `package.json` files at `/`, `/Users`, or `/Users/boazwarshawsky`

**Comment by bwomsm1** [comment]
> What happens if you go into `/Users/boazwarshawsky/.appium/node_modules/appium-xcuitest-driver` and run `node -e 'require("appium/driver")`

I get this:
```
node:internal/modules/cjs/loader:1143
  throw err;
  ^

Error: Cannot find module 'appium/driver'
Require stack:
- /Users/boazwarshawsky/.appium/node_modules/appium-xcuitest-driver/[eval]
    at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
    at Module._load (node:internal/modules/cjs/loader:981:27)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:177:18)
    at [eval]:1:1
    at runScriptInThisContext (node:internal/vm:143:10)
    at node:internal/process/execution:100:14
    at [eval]-wrapper:6:24
    at runScript (node:internal/process/execution:83:62)
    at evalScript (node:internal/process/execution:114:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/boazwarshawsky/.appium/node_modules/appium-xcuitest-driver/[eval]'
  ]
}

Node.js v18.20.1
```

**Comment by bwomsm1** [comment]
> also, double check there are no `package.json` files at `/`, `/Users`, or `/Users/boazwarshawsky`

No `package.json` in those paths.

**Comment by jlipps** [comment]
How do you have appium installed?

**Comment by jlipps** [comment]
when Appium is installed via `npm install -g`, then the above command should work in basically any directory.

**Comment by bwomsm1** [comment]
> when Appium is installed via `npm install -g`, then the above command should work in basically any directory.

Yes, I installed as follow:
`npm install -g appium`

**Comment by jlipps** [comment]
Then something seems very odd with your node/npm install. You should be able to run `node -e 'require("appium/driver")` with no exceptions printed out, from any place on your system where you can run `appium`. Can you run `appium` in that xcuitest driver directory?

**Comment by jlipps** [comment]
Great. Yeah, it seemed like something was off with your node/npm install.
