### ISSUE TITLE
getScreenshot failing with 500 and then everything goes into a bad state

### ISSUE THREAD

**Issue by rohanp-91** [appium/appium#19999]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We are using appium 2.0.1, appium-xcuitest-driver 4.35.0, Xcode 15 and running tests on macOS 13 (arm64). We are frequently seeing the below issue happening (I have highlighted the interesting logs):

2024-04-14T17:26:54.5310190Z 2024-04-14 17:26:54:529 - [38;5;0m[HTTP][0m [90m[39m
2024-04-14T17:26:54.5368080Z   console.log
2024-04-14T17:26:54.5369160Z     Saving screenshot 2024-04-14-17-26-54-533.found.satisfiedCondition.png for query {"XPath":"//XCUIElementTypeButton[@name=\"No, Thanks\"]"}
2024-04-14T17:26:54.5369530Z 
2024-04-14T17:26:54.5370370Z       at log (__tests__/appium/library/action.js:19:13)
2024-04-14T17:26:54.5370550Z 
2024-04-14T17:26:54.5668340Z 2024-04-14 17:26:54:565 - [38;5;0m[HTTP][0m --> GET /session/21ce1aaa-0403-4930-8420-f43afeefc2d0/screenshot
2024-04-14T17:26:54.5670400Z 2024-04-14 17:26:54:565 - [38;5;0m[HTTP][0m [90m{}[39m
2024-04-14T17:26:54.5671470Z 2024-04-14 17:26:54:566 - [debug] [38;5;32m[XCUITestDriver@d5c8 (21ce1aaa)][0m Calling AppiumDriver.getScreenshot() with args: ["21ce1aaa-0403-4930-8420-f43afeefc2d0"]
2024-04-14T17:26:54.5671880Z 2024-04-14 17:26:54:566 - [debug] [38;5;32m[XCUITestDriver@d5c8 (21ce1aaa)][0m Executing command 'getScreenshot'
2024-04-14T17:26:54.5672390Z 2024-04-14 17:26:54:566 - [debug] [38;5;32m[XCUITestDriver@d5c8 (21ce1aaa)][0m Taking screenshot with WDA
2024-04-14T17:26:54.5672710Z 2024-04-14 17:26:54:567 - [debug] [38;5;32m[XCUITestDriver@d5c8 (21ce1aaa)][0m Setting custom timeout to 80000 ms for 'getScreenshot' command
2024-04-14T17:26:54.5673270Z 2024-04-14 17:26:54:567 - [debug] [38;5;32m[XCUITestDriver@d5c8 (21ce1aaa)][0m Matched '/screenshot' to command name 'getScreenshot'
2024-04-14T17:26:54.5677620Z 2024-04-14 17:26:54:567 - [debug] [38;5;32m[XCUITestDriver@d5c8 (21ce1aaa)][0m Proxying [GET /screenshot] to [GET http://127.0.0.1:8100/session/E7F99808-8343-4D3D-B679-64E2DB848729/screenshot] with no body
2024-04-14T17:26:54.5729150Z 2024-04-14 17:26:54:572 - [38;5;176m[Xcode][0m 2024-04-14 17:26:54.569500+0000 WebDriverAgentRunner-Runner[72441:354889] The device under test does not support HEIC image encoding. Falling back to PNG
2024-04-14T17:26:54.5729690Z 2024-04-14 17:26:54:572 - [38;5;176m[Xcode][0m 
2024-04-14T17:27:14.5753310Z 2024-04-14 17:27:14:573 - [38;5;32m[XCUITestDriver@d5c8 (21ce1aaa)][0m **Got response with status 500: {"value":{"error":"unable to capture screen","message":"Error Domain=com.facebook.WebDriverAgent Code=1 \"Cannot take a screenshot within 20000 ms timeout\" UserInfo={NSLocalizedDescription=Cannot take a screenshot within 20000 ms timeout}","traceback":""},"sessionId":"E7F99808-8343-4D3D-B679-64E2DB848729"}**
2024-04-14T17:27:14.5764010Z 2024-04-14 17:27:14:575 - [debug] [38;5;192m[W3C][0m Matched W3C error code 'unable to capture screen' to UnableToCaptureScreen
2024-04-14T17:27:14.5981970Z 2024-04-14 17:27:14:597 - [38;5;32m[XCUITestDriver@d5c8 (21ce1aaa)][0m Error getting screenshot: Error Domain=com.facebook.WebDriverAgent Code=1 "Cannot take a screenshot within 20000 ms timeout" UserInfo={NSLocalizedDescription=Cannot take a screenshot within 20000 ms timeout}
2024-04-14T17:27:14.5982520Z 2024-04-14 17:27:14:597 - [38;5;32m[XCUITestDriver@d5c8 (21ce1aaa)][0m Falling back to 'simctl io screenshot' API
2024-04-14T17:27:15.2812980Z 2024-04-14 17:27:15:280 - [debug] [38;5;32m[XCUITestDriver@d5c8 (21ce1aaa)][0m Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAABQoAAArsCAYAAACYCMQuAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAFCqADAAQAAAABAAAK7AAAAADZjcgLAABAAElEQVR4AezdB5xU1b3A8T9s78uysPQq0hFBFBUU7C1GTTQxUWPKM+pLbybqS0zvMe3FdKMmxqdJjMbeC1YUAVFAirSF3WWBXbZX3vnPMnBn5t7Zmdlp987vfBxn5pZzz/ney92Z/5wySK68+4CQEEAAAQQQQAABBBBAAAEEEEAAAQQQQCCjBQZndO2pPAIIIIAAAggggAACCCCAAAIIIIAAAgj4BAgUciEggAACCCCAAAIIIIAAAggggAACCCCAgBAo5CJAAAEEEEAAAQQQQAABBBBAAAEEEEAAAQKFXAMIIIAAAggggAACCCCAAAIIIIAAAgggIAQKuQgQQAABBBBAAAEEEEAAAQQQQAABBBBAgEAh1wACCCCAAAIIIIAAAggggAACCCCAAAIIGAHGKOQyQAABBBBAAAEEEEAAAQQQQAABBBBAAAEChVwDCCCAAAIIIIAAAggggAACCCCAAAIIIECLQq4BBBBAAAEEEEAAAQQQQAABBBBAAAEEEDACdD3mMkAAAQQQQAABBBBAAAEEEEAAAQQQQAABAoVcAwgggAACCCCAAAIIIIAAAggggAACCCBAi0KuAQQQQAABBBBAAAEEEEAAAQQQQAABBBAwAnQ95jJAAAEEEEAAAQQQQAABBBBAAAEEEEAAAQKFXAMIIIAAAggggAACCCCAAAIIIIAAAgggQItCrgEEEEAAAQQQQAABBBBAAAEEEEAAAQQQMAJ0PeYyQAABBBBAAAEEEEAAAQQQQAABBBBAAAEChVwDCCCAAAIIIIAAAggggAACCCCAAAIIIECLQq4BBBBAAAEEEEAAAQQQQAABBBBAAAEEEDACdD3mMkAA...
2024-04-14T17:27:15.2912920Z 2024-04-14 17:27:15:288 - [38;5;0m[HTTP][0m [37m<-- GET /session/21ce1aaa-0403-4930-8420-f43afeefc2d0/screenshot [39m[32m200[39m [90m20722 ms - 738564[39m
2024-04-14T17:27:15.2914520Z 2024-04-14 17:27:15:288 - [38;5;0m[HTTP][0m [90m[39m
2024-04-14T17:27:16.4043140Z 2024-04-14 17:27:16:402 - [38;5;0m[HTTP][0m --> POST /session/21ce1aaa-0403-4930-8420-f43afeefc2d0/element
2024-04-14T17:27:16.4143970Z 2024-04-14 17:27:16:402 - [38;5;0m[HTTP][0m [90m{"using":"accessibility id","value":"No, Thanks"}[39m
2024-04-14T17:27:16.4249370Z 2024-04-14 17:27:16:403 - [debug] [38;5;32m[XCUITestDriver@d5c8 (21ce1aaa)][0m Calling AppiumDriver.findElement() with args: ["accessibility id","No, Thanks","21ce1aaa-0403-4930-8420-f43afeefc2d0"]
2024-04-14T17:27:16.4344600Z 2024-04-14 17:27:16:403 - [debug] [38;5;32m[XCUITestDriver@d5c8 (21ce1aaa)][0m Executing command 'findElement'
2024-04-14T17:27:16.4366020Z 2024-04-14 17:27:16:404 - [debug] [38;5;32m[XCUITestDriver@d5c8 (21ce1aaa)][0m Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id, css selector
2024-04-14T17:27:16.4367840Z 2024-04-14 17:27:16:404 - [debug] [38;5;32m[XCUITestDriver@d5c8 (21ce1aaa)][0m Waiting up to 0 ms for condition
2024-04-14T17:27:16.4371460Z 2024-04-14 17:27:16:407 - [debug] [38;5;32m[XCUITestDriver@d5c8 (21ce1aaa)][0m Matched '/element' to command name 'findElement'
2024-04-14T17:27:16.4372070Z 2024-04-14 17:27:16:407 - [debug] [38;5;32m[XCUITestDriver@d5c8 (21ce1aaa)][0m Proxying [POST /element] to [POST http://127.0.0.1:8100/session/E7F99808-8343-4D3D-B679-64E2DB848729/element] with body: {"using":"accessibility id","value":"No, Thanks"}
2024-04-14T17:27:16.4372540Z 2024-04-14 17:27:16:416 - [38;5;176m[Xcode][0m 2024-04-14 17:27:16.415708+0000 WebDriverAgentRunner-Runner[72441:354889] Getting the most recent active application (out of 1 total items)
2024-04-14T17:27:16.4373160Z 2024-04-14 17:27:16:416 - [38;5;176m[Xcode][0m 
2024-04-14T17:27:16.4373900Z 2024-04-14 17:27:16:419 - [38;5;176m[Xcode][0m     t =   207.32s Get all elements bound by accessibility element for: Elements matching predicate 'BLOCKPREDICATE(0x600001a87cf0)'
2024-04-14T17:27:16.4374350Z 2024-04-14 17:27:16:419 - [38;5;176m[Xcode][0m 
2024-04-14T17:27:16.4374680Z 2024-04-14 17:27:16:420 - [38;5;176m[Xcode][0m     t =   207.32s     Requesting snapshot of accessibility hierarchy for app with pid 76264
2024-04-14T17:27:16.4375460Z 2024-04-14 17:27:16:420 - [38;5;176m[Xcode][0m 
2024-04-14T17:27:16.6145090Z 2024-04-14 17:27:16:613 - [38;5;176m[Xcode][0m     t =   207.51s     Find: Descendants matching type Any
2024-04-14T17:27:16.6181260Z 2024-04-14 17:27:16:613 - [38;5;176m[Xcode][0m 
2024-04-14T17:27:16.6183630Z 2024-04-14 17:27:16:615 - [38;5;176m[Xcode][0m     t =   207.52s     Find: Elements matching predicate 'BLOCKPREDICATE(0x600001a87cf0)'
2024-04-14T17:27:16.6184360Z 2024-04-14 17:27:16:615 - [38;5;176m[Xcode][0m 
2024-04-14T17:27:16.6366150Z 2024-04-14 17:27:16:634 - [38;5;176m[Xcode][0m     t =   207.53s Requesting snapshot of accessibility hierarchy for app with pid 76264
2024-04-14T17:27:16.6467310Z 2024-04-14 17:27:16:635 - [38;5;176m[Xcode][0m 
2024-04-14T17:27:16.8110980Z 2024-04-14 17:27:16:799 - [38;5;176m[Xcode][0m     t =   207.70s Find: Descendants matching type Any
2024-04-14T17:27:16.8112060Z 2024-04-14 17:27:16:799 - [38;5;176m[Xcode][0m 
2024-04-14T17:27:16.8144770Z 2024-04-14 17:27:16:800 - [38;5;176m[Xcode][0m     t =   207.70s Find: Elements matching predicate 'BLOCKPREDICATE(0x600001a87cf0)'
2024-04-14T17:27:16.8145170Z 2024-04-14 17:27:16:800 - [38;5;176m[Xcode][0m 
2024-04-14T17:27:16.8145450Z 2024-04-14 17:27:16:802 - [38;5;176m[Xcode][0m     t =   207.70s Find: Identity Binding
2024-04-14T17:27:16.8145660Z 2024-04-14 17:27:16:802 - [38;5;176m[Xcode][0m 
2024-04-14T17:27:16.8146530Z 2024-04-14 17:27:16:812 - [debug] [38;5;32m[XCUITestDriver@d5c8 (21ce1aaa)][0m Got response with status 200: {"value":{"ELEMENT":"38010000-0000-0000-E829-010000000000","element-6066-11e4-a52e-4f735466cecf":"38010000-0000-0000-E829-010000000000"},"sessionId":"E7F99808-8343-4D3D-B679-64E2DB848729"}
2024-04-14T17:27:16.8147210Z 2024-04-14 17:27:16:812 - [debug] [38;5;32m[XCUITestDriver@d5c8 (21ce1aaa)][0m Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"38010000-0000-0000-E829-010000000000","ELEMENT":"38010000-0000-0000-E829-010000000000"}
2024-04-14T17:27:16.8147640Z 2024-04-14 17:27:16:813 - [38;5;0m[HTTP][0m [37m<-- POST /session/21ce1aaa-0403-4930-8420-f43afeefc2d0/element [39m[32m200[39m [90m411 ms - 137[39m
2024-04-14T17:27:16.8147910Z 2024-04-14 17:27:16:813 - [38;5;0m[HTTP][0m [90m[39m
2024-04-14T17:27:16.8188590Z 2024-04-14 17:27:16:818 - [38;5;0m[HTTP][0m --> POST /session/21ce1aaa-0403-4930-8420-f43afeefc2d0/element/38010000-0000-0000-E829-010000000000/click
2024-04-14T17:27:16.8188980Z 2024-04-14 17:27:16:818 - [38;5;0m[HTTP][0m [90m{}[39m
2024-04-14T17:27:16.8189250Z 2024-04-14 17:27:16:818 - [38;5;32m[XCUITestDriver@d5c8 (21ce1aaa)][0m Driver proxy active, passing request on via HTTP proxy
2024-04-14T17:27:16.8189830Z 2024-04-14 17:27:16:818 - [debug] [38;5;32m[XCUITestDriver@d5c8 (21ce1aaa)][0m Executing command 'proxyReqRes'
2024-04-14T17:27:16.8193040Z 2024-04-14 17:27:16:819 - [debug] [38;5;32m[XCUITestDriver@d5c8 (21ce1aaa)][0m Matched '/session/21ce1aaa-0403-4930-8420-f43afeefc2d0/element/38010000-0000-0000-E829-010000000000/click' to command name 'click'
2024-04-14T17:27:16.8194070Z 2024-04-14 17:27:16:819 - [debug] [38;5;32m[XCUITestDriver@d5c8 (21ce1aaa)][0m Proxying [POST /session/21ce1aaa-0403-4930-8420-f43afeefc2d0/element/38010000-0000-0000-E829-010000000000/click] to [POST http://127.0.0.1:8100/session/E7F99808-8343-4D3D-B679-64E2DB848729/element/38010000-0000-0000-E829-010000000000/click] with body: {}
2024-04-14T17:27:16.8255470Z 2024-04-14 17:27:16:822 - [38;5;176m[Xcode][0m     t =   207.72s Requesting snapshot of accessibility hierarchy for app with pid 76264
2024-04-14T17:27:16.8284790Z 2024-04-14 17:27:16:823 - [38;5;176m[Xcode][0m 
2024-04-14T17:27:16.9946350Z 2024-04-14 17:27:16:993 - [38;5;176m[Xcode][0m     t =   207.89s Find: Descendants matching type Any
2024-04-14T17:27:16.9956040Z 2024-04-14 17:27:16:994 - [38;5;176m[Xcode][0m 
2024-04-14T17:27:16.9956490Z 2024-04-14 17:27:16:994 - [38;5;176m[Xcode][0m     t =   207.90s Find: Elements matching predicate 'BLOCKPREDICATE(0x600001a87cf0)'
2024-04-14T17:27:16.9956720Z 2024-04-14 17:27:16:995 - [38;5;176m[Xcode][0m 
2024-04-14T17:27:16.9968320Z 2024-04-14 17:27:16:996 - [38;5;176m[Xcode][0m     t =   207.90s Find: Identity Binding
2024-04-14T17:27:16.9970790Z 2024-04-14 17:27:16:996 - [38;5;176m[Xcode][0m 
2024-04-14T17:27:17.0249280Z 2024-04-14 17:27:17:024 - [38;5;176m[Xcode][0m     t =   207.91s Tap "No, Thanks" Button
2024-04-14T17:27:17.0354330Z 2024-04-14 17:27:17:024 - [38;5;176m[Xcode][0m 2024-04-14 17:27:17.005479+0000 WebDriverAgentRunner-Runner[72441:354889] Waiting up to 10s until com.company.testapp is in idle state (including animations)
2024-04-14T17:27:17.0379490Z 2024-04-14 17:27:17:024 - [38;5;176m[Xcode][0m     t =   207.91s     Wait for com.company.testapp to idle
2024-04-14T17:27:17.0380500Z 2024-04-14 17:27:17:024 - [38;5;176m[Xcode][0m     t =   207.91s     Find the "No, Thanks" Button
2024-04-14T17:27:17.0381340Z 2024-04-14 17:27:17:024 - [38;5;176m[Xcode][0m     t =   207.91s         Requesting snapshot of accessibility hierarchy for app with pid 76264
2024-04-14T17:27:17.0384420Z 2024-04-14 17:27:17:024 - [38;5;176m[Xcode][0m 
2024-04-14T17:27:17.2015190Z 2024-04-14 17:27:17:201 - [38;5;176m[Xcode][0m     t =   208.10s         Find: Descendants matching type Any
2024-04-14T17:27:17.2016200Z 2024-04-14 17:27:17:201 - [38;5;176m[Xcode][0m 
2024-04-14T17:27:17.2126800Z 2024-04-14 17:27:17:209 - [38;5;176m[Xcode][0m     t =   208.10s         Find: Elements matching predicate 'BLOCKPREDICATE(0x600001a87cf0)'
2024-04-14T17:27:17.2133040Z 2024-04-14 17:27:17:209 - [38;5;176m[Xcode][0m 
2024-04-14T17:27:17.2136320Z 2024-04-14 17:27:17:211 - [38;5;176m[Xcode][0m     t =   208.11s         Find: Identity Binding
2024-04-14T17:27:17.2141230Z 2024-04-14 17:27:17:211 - [38;5;176m[Xcode][0m     t =   208.11s Application is configured to skip UI interruption handling
2024-04-14T17:27:17.2143460Z 2024-04-14 17:27:17:211 - [38;5;176m[Xcode][0m     t =   208.11s     Synthesize event
2024-04-14T17:27:17.2144040Z 2024-04-14 17:27:17:211 - [38;5;176m[Xcode][0m 
2024-04-14T17:27:17.5267300Z 2024-04-14 17:27:17:524 - [38;5;176m[Xcode][0m 2024-04-14 17:27:17.515746+0000 WebDriverAgentRunner-Runner[72441:354889] Waiting up to 10s until com.company.testapp is in idle state (including animations)
2024-04-14T17:27:17.5268330Z 2024-04-14 17:27:17:524 - [38;5;176m[Xcode][0m     t =   208.42s     Wait for com.company.testapp to idle
2024-04-14T17:27:17.5269220Z 2024-04-14 17:27:17:524 - [38;5;176m[Xcode][0m 
2024-04-14T17:27:27.5261050Z 2024-04-14 17:27:27:525 - [38;5;176m[Xcode][0m     t =   218.43s         App event loop idle notification not received, will attempt to continue.
2024-04-14T17:27:27.5281100Z 2024-04-14 17:27:27:525 - [38;5;176m[Xcode][0m 
2024-04-14T17:27:27.5281440Z 2024-04-14 17:27:27:527 - [debug] [38;5;32m[XCUITestDriver@d5c8 (21ce1aaa)][0m Got response with status 200: {"value":null,"sessionId":"E7F99808-8343-4D3D-B679-64E2DB848729"}
2024-04-14T17:27:27.5281870Z 2024-04-14 17:27:27:527 - [38;5;32m[XCUITestDriver@d5c8 (21ce1aaa)][0m Replacing sessionId E7F99808-8343-4D3D-B679-64E2DB848729 with 21ce1aaa-0403-4930-8420-f43afeefc2d0
2024-04-14T17:27:27.5286130Z 2024-04-14 17:27:27:528 - [38;5;0m[HTTP][0m [37m<-- POST /session/21ce1aaa-0403-4930-8420-f43afeefc2d0/element/38010000-0000-0000-E829-010000000000/click [39m[32m200[39m [90m10710 ms - 65[39m
2024-04-14T17:27:27.5286460Z 2024-04-14 17:27:27:528 - [38;5;0m[HTTP][0m [90m[39m
2024-04-14T17:27:29.5412390Z 2024-04-14 17:27:29:540 - [38;5;0m[HTTP][0m --> POST /session/21ce1aaa-0403-4930-8420-f43afeefc2d0/elements
2024-04-14T17:27:29.5412900Z 2024-04-14 17:27:29:540 - [38;5;0m[HTTP][0m [90m{"using":"accessibility id","value":"Account selector and settings menu"}[39m
2024-04-14T17:27:29.5413510Z 2024-04-14 17:27:29:541 - [debug] [38;5;32m[XCUITestDriver@d5c8 (21ce1aaa)][0m Calling AppiumDriver.findElements() with args: ["accessibility id","Account selector and settings menu","21ce1aaa-0403-4930-8420-f43afeefc2d0"]
2024-04-14T17:27:29.5416180Z 2024-04-14 17:27:29:541 - [debug] [38;5;32m[XCUITestDriver@d5c8 (21ce1aaa)][0m Executing command 'findElements'
2024-04-14T17:27:29.5416530Z 2024-04-14 17:27:29:541 - [debug] [38;5;32m[XCUITestDriver@d5c8 (21ce1aaa)][0m Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id, css selector
2024-04-14T17:27:29.5416840Z 2024-04-14 17:27:29:541 - [debug] [38;5;32m[XCUITestDriver@d5c8 (21ce1aaa)][0m Waiting up to 0 ms for condition
2024-04-14T17:27:29.5424270Z 2024-04-14 17:27:29:542 - [debug] [38;5;32m[XCUITestDriver@d5c8 (21ce1aaa)][0m Matched '/elements' to command name 'findElements'
2024-04-14T17:27:29.5425260Z 2024-04-14 17:27:29:542 - [debug] [38;5;32m[XCUITestDriver@d5c8 (21ce1aaa)][0m Proxying [POST /elements] to [POST http://127.0.0.1:8100/session/E7F99808-8343-4D3D-B679-64E2DB848729/elements] with body: {"using":"accessibility id","value":"Account selector and settings menu"}
2024-04-14T17:27:29.5475740Z 2024-04-14 17:27:29:547 - [38;5;176m[Xcode][0m 2024-04-14 17:27:29.546479+0000 WebDriverAgentRunner-Runner[72441:354889] Getting the most recent active application (out of 1 total items)
2024-04-14T17:27:29.5476140Z 2024-04-14 17:27:29:547 - [38;5;176m[Xcode][0m 
2024-04-14T17:27:29.5476430Z 2024-04-14 17:27:29:547 - [38;5;176m[Xcode][0m     t =   220.45s Get all elements bound by accessibility element for: Elements matching predicate 'BLOCKPREDICATE(0x600001b31c50)'
2024-04-14T17:27:29.5477240Z 2024-04-14 17:27:29:547 - [38;5;176m[Xcode][0m 
2024-04-14T17:27:29.5486000Z 2024-04-14 17:27:29:548 - [38;5;176m[Xcode][0m     t =   220.45s     Requesting snapshot of accessibility hierarchy for app with pid 76264
2024-04-14T17:27:29.5487500Z 2024-04-14 17:27:29:548 - [38;5;176m[Xcode][0m 
2024-04-14T17:28:29.6478090Z 2024-04-14 17:28:29:573 - [38;5;32m[XCUITestDriver@d5c8 (21ce1aaa)][0m **AxiosError: timeout of 60000ms exceeded
2024-04-14T17:28:29.6909800Z 2024-04-14 17:28:29:573 - [38;5;32m[XCUITestDriver@d5c8 (21ce1aaa)][0m     at RedirectableRequest.handleRequestTimeout (/Users/runner/work/1/s/node_modules/axios/lib/adapters/http.js:614:16)
2024-04-14T17:28:29.6911320Z 2024-04-14 17:28:29:573 - [38;5;32m[XCUITestDriver@d5c8 (21ce1aaa)][0m     at RedirectableRequest.emit (node:events:513:28)
2024-04-14T17:28:29.6911630Z 2024-04-14 17:28:29:573 - [38;5;32m[XCUITestDriver@d5c8 (21ce1aaa)][0m     at Timeout.<anonymous> (/Users/runner/work/1/s/node_modules/follow-redirects/index.js:169:12)
2024-04-14T17:28:29.6911950Z 2024-04-14 17:28:29:573 - [38;5;32m[XCUITestDriver@d5c8 (21ce1aaa)][0m     at listOnTimeout (node:internal/timers:559:17)
2024-04-14T17:28:29.6914710Z 2024-04-14 17:28:29:574 - [38;5;32m[XCUITestDriver@d5c8 (21ce1aaa)][0m     at processTimers (node:internal/timers:502:7)**
2024-04-14T17:28:29.6915160Z 2024-04-14 17:28:29:574 - [38;5;176m[Xcode][0m 2024-04-14 17:28:29.557734+0000 WebDriverAgentRunner-Runner[72441:354889] Issue type: 0
2024-04-14T17:28:29.6915550Z 2024-04-14 17:28:29:574 - [38;5;176m[Xcode][0m 2024-04-14 17:28:29.557850+0000 WebDriverAgentRunner-Runner[72441:354889] Enqueue Failure: Failed to resolve query: XCTPerformOnMainRunLoop work timed out after 60.0s ((null)) (null) 0 0
2024-04-14T17:28:29.6915950Z 2024-04-14 17:28:29:574 - [38;5;176m[Xcode][0m 
2024-04-14T17:28:29.6916200Z 2024-04-14 17:28:29:575 - [debug] [38;5;32m[XCUITestDriver@d5c8 (21ce1aaa)][0m Responding to client with driver.findElements() result: []
2024-04-14T17:28:29.6916500Z 2024-04-14 17:28:29:576 - [38;5;0m[HTTP][0m [37m<-- POST /session/21ce1aaa-0403-4930-8420-f43afeefc2d0/elements [39m[32m200[39m [90m60035 ms - 12[39m
2024-04-14T17:28:29.6916840Z 2024-04-14 17:28:29:576 - [38;5;0m[HTTP][0m [90m[39m
2024-04-14T17:28:30.5867160Z 2024-04-14 17:28:30:586 - [38;5;0m[HTTP][0m --> POST /session/21ce1aaa-0403-4930-8420-f43afeefc2d0/elements
2024-04-14T17:28:30.5869490Z 2024-04-14 17:28:30:586 - [38;5;0m[HTTP][0m [90m{"using":"accessibility id","value":"Account selector and settings menu"}[39m
2024-04-14T17:28:30.5870150Z 2024-04-14 17:28:30:586 - [debug] [38;5;32m[XCUITestDriver@d5c8 (21ce1aaa)][0m Calling AppiumDriver.findElements() with args: ["accessibility id","Account selector and settings menu","21ce1aaa-0403-4930-8420-f43afeefc2d0"]
2024-04-14T17:28:30.5870460Z 2024-04-14 17:28:30:586 - [debug] [38;5;32m[XCUITestDriver@d5c8 (21ce1aaa)][0m Executing command 'findElements'
2024-04-14T17:28:30.5870820Z 2024-04-14 17:28:30:586 - [debug] [38;5;32m[XCUITestDriver@d5c8 (21ce1aaa)][0m Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id, css selector
2024-04-14T17:28:30.5871140Z 2024-04-14 17:28:30:586 - [debug] [38;5;32m[XCUITestDriver@d5c8 (21ce1aaa)][0m Waiting up to 0 ms for condition
2024-04-14T17:28:30.5878610Z 2024-04-14 17:28:30:587 - [debug] [38;5;32m[XCUITestDriver@d5c8 (21ce1aaa)][0m Matched '/elements' to command name 'findElements'
2024-04-14T17:28:30.5879940Z 2024-04-14 17:28:30:587 - [debug] [38;5;32m[XCUITestDriver@d5c8 (21ce1aaa)][0m Proxying [POST /elements] to [POST http://127.0.0.1:8100/session/E7F99808-8343-4D3D-B679-64E2DB848729/elements] with body: {"using":"accessibility id","value":"Account selector and settings menu"}
2024-04-14T17:28:30.6046390Z 2024-04-14 17:28:30:601 - [38;5;176m[Xcode][0m 2024-04-14 17:28:30.592855+0000 WebDriverAgentRunner-Runner[72441:354889] Getting the most recent active application (out of 1 total items)
2024-04-14T17:28:30.6148790Z 2024-04-14 17:28:30:601 - [38;5;176m[Xcode][0m     t =   281.50s Get all elements bound by accessibility element for: Elements matching predicate 'BLOCKPREDICATE(0x600001d976f0)'
2024-04-14T17:28:30.6182070Z 2024-04-14 17:28:30:601 - [38;5;176m[Xcode][0m     t =   281.50s     Requesting snapshot of accessibility hierarchy for app with pid 76264
2024-04-14T17:28:30.6184530Z 2024-04-14 17:28:30:603 - [38;5;176m[Xcode][0m 
2024-04-14T17:29:30.6007720Z 2024-04-14 17:29:30:591 - [38;5;32m[XCUITestDriver@d5c8 (21ce1aaa)][0m AxiosError: timeout of 60000ms exceeded
2024-04-14T17:29:30.6098680Z 2024-04-14 17:29:30:592 - [38;5;32m[XCUITestDriver@d5c8 (21ce1aaa)][0m     at RedirectableRequest.handleRequestTimeout (/Users/runner/work/1/s/node_modules/axios/lib/adapters/http.js:614:16)
2024-04-14T17:29:30.6213260Z 2024-04-14 17:29:30:592 - [38;5;32m[XCUITestDriver@d5c8 (21ce1aaa)][0m     at RedirectableRequest.emit (node:events:513:28)
2024-04-14T17:29:30.6238450Z 2024-04-14 17:29:30:592 - [38;5;32m[XCUITestDriver@d5c8 (21ce1aaa)][0m     at Timeout.<anonymous> (/Users/runner/work/1/s/node_modules/follow-redirects/index.js:169:12)
2024-04-14T17:29:30.6239780Z 2024-04-14 17:29:30:592 - [38;5;32m[XCUITestDriver@d5c8 (21ce1aaa)][0m     at listOnTimeout (node:internal/timers:559:17)
2024-04-14T17:29:30.6240340Z 2024-04-14 17:29:30:592 - [38;5;32m[XCUITestDriver@d5c8 (21ce1aaa)][0m     at processTimers (node:internal/timers:502:7)
2024-04-14T17:29:30.6240800Z 2024-04-14 17:29:30:597 - [debug] [38;5;32m[XCUITestDriver@d5c8 (21ce1aaa)][0m Responding to client with driver.findElements() result: []

As you can see, first the screenshot issue happens, then we keep getting the AxiosError: timeout of 60000ms exceeded and then no other tests pass on this run, seems like it goes into a bad state.

### Expected Behavior

Even if getScreenshot fails, it shouldn't go into a bad state.

### Minimal Reproducible Example

N/A

### Environment

- Operating system: macOs 13 arm4 device
- Appium server version (output of `appium --version`): 2.0.1
- Appium driver(s) and their version(s): "appium-xcuitest-driver": "4.35.0"
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: iOS
- Real device or emulator/simulator: simulator iphone 15 pro max

**Comment by mykola-mokhnach** [comment]
Please use the most recent driver version.
What is the iOS version of the destination device?

**Comment by rohanp-91** [comment]
@mykola-mokhnach The iOS version of destination device is iOS 17.2. Will the latest driver version work with appium 2.0.1?

**Comment by mykola-mokhnach** [comment]
> Will the latest driver version work with appium 2.0.1?

No. it won't work. It is also necessary to update the server. Unfortunately we do not provide patches to older driver or server versions
