### ISSUE TITLE
Possible bug - I get certain errors ONLY when "isHeadless" is set to true

### ISSUE THREAD

**Issue by tking16** [appium/appium#20086]
Here's the error, seems to occur during a scroll action:

```
E       selenium.common.exceptions.UnknownMethodException: Message: Unhandled endpoint: /session/0A8F63DD-BB55-499D-A17D-5750AA76A299/touch/perform -- http://127.0.0.1:8100/ with parameters {
E           wildcards =     (
E               "session/0A8F63DD-BB55-499D-A17D-5750AA76A299/touch/perform"
E           );
E       }
E       Stacktrace:
E       UnknownCommandError: Unhandled endpoint: /session/0A8F63DD-BB55-499D-A17D-5750AA76A299/touch/perform -- http://127.0.0.1:8100/ with parameters {
E           wildcards =     (
E               "session/0A8F63DD-BB55-499D-A17D-5750AA76A299/touch/perform"
E           );
E       }
E           at errorFromW3CJsonCode (/Users/theo.king/code/guacamole/testing/app-at/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/protocol/errors.js:1112:25)
E           at ProxyRequestError.getActualError (/Users/theo.king/code/guacamole/testing/app-at/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/protocol/errors.js:981:14)
E           at JWProxy.proxyReqRes (/Users/theo.king/code/guacamole/testing/app-at/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:415:58)
E           at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

[Logs if they help at all](https://gist.github.com/tking16/bdd2e32bc7373ae637fe747830246854)

[logs of the failing test specifially](https://gist.github.com/tking16/17596cf554fbe08e8d82c027b107559a), bit less info but might be easier to read

Appium 2.5.4
"appium-xcuitest-driver": "^7.15.1"

**Comment by tking16** [comment]
I think this is the functions that's causing this, just verified it works when not headless

```
    def scroll_to_center(self, origin_el, end_el=None):
        phone_width = self._driver.get_window_size().get("width")
        phone_height = self._driver.get_window_size().get("height")
        center_y = phone_height / 2
        if origin_el.location.get('y') > center_y:
            # if el is on bottom half of screen, swipe up a tiny bit
            self.partial_scroll(distance=150)
        else:
            # if el is on top half of screen, swipe down a tiny bit
            self.partial_scroll(direction="up", distance=150)

    def partial_scroll(self, direction='down', distance=250):
        phone_width_center = self._driver.get_window_size().get("width") / 2
        phone_height_center = self._driver.get_window_size().get("height") / 2
        actions = TouchAction(self._driver)
        if direction == 'down':
            end_loc = (phone_width_center, (phone_height_center - distance))
        elif direction == 'up':
            end_loc = (phone_width_center, (phone_height_center + distance))
        elif direction == 'right':
            end_loc = ((phone_width_center - distance), phone_height_center)
        elif direction == 'left':
            end_loc = ((phone_width_center + distance), phone_height_center)
        actions.long_press(x=phone_width_center, y=phone_height_center).move_to(x=end_loc[0], y=end_loc[1]).release()
        actions.perform()
```

**Comment by mykola-mokhnach** [comment]
This error is expected. All touch actions-related APIs have been deprecated a while ago and removed from android and ios drivers. Consider using W3C actions or gesture shortcuts instead
