### ISSUE TITLE
regression: "Cannot extract Info.plist from *.ipa"

### ISSUE THREAD

**Issue by evgenyvalavin** [appium/appium#20125]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1. Try to start a test with *.ipa file.
2. Get an error "WebDriverException : An unknown server-side error occurred while processing the command. Original error: Cannot extract Info.plist from '/Users/user/Downloads/application.ipa'. Is it a valid application bundle?"

The *.ipa does not contain Info.plist. Building an .ipa with dotnet publish doesn't generate Info.plist in an .ipa file.
I've updated to xcuitest 7.15.3 yesterday.

### Expected Behavior

1. Try to start a test with *.ipa file with no Info.plist inside of the .ipa.
2. No error. Test starts as usual.

This behavior worked fine in xcuitest 7.15.1. 

### Minimal Reproducible Example

A "dotnet publish" generated .api only contains "Payload" folder.
Try running a test with xcuitest

### Environment

- Operating system: macOS
- Appium server version (output of `appium --version`): 2.5.4
- Appium driver(s) and their version(s) (`appium driver list`): xcuitest 7.15.3
- Last component(s) version which did _not_ exhibit the problem: xcuitest 7.15.1
- Platform and version under test: iOS 17.4.1
- Real device or emulator/simulator: real device

**Comment by KazuCocoa** [comment]
> A "dotnet publish" generated .api only contains "Payload" folder.

Is it valid `ipa` without `Info.plist`...? Usually xcodebuild/Xcode generates it in the building. Maybe old tools might not add them though. I wondered if it could also include 3rd party tools matter they should add info.plist.

Perhaps https://github.com/appium/appium-xcuitest-driver/blob/f00d231d6ab0986de7c6d5fa090ec4f9f283dc80/lib/driver.js#L1562 could have a capability to avoid app validation.

**Comment by evgenyvalavin** [comment]
> Is it valid `ipa` without `Info.plist`...?

I don't see a reason why it should not be valid, because Apple Store accepts an .ipa without Info.plist. I upload an .api via fastline with no issues for years.
I also want to note building with "dotnet publish" is the only way to build a .NET iOS application and this way of building is not old.

Some info from the Internet:
**.app** are application bundles. They contain the executable file, an **Info.plist** file, an icon, a launch image, and some other application resources. Application bundles are the only ones that actually get installed onto your device.

**.ipa** are archives that contain .app bundles as well as some other files meant only for iTunes to use, for instance iTunesArtwork. They are how iTunes manages applications, and as far as I can tell have little to do with the applications themselves other than App Store information.
[Link](https://stackoverflow.com/questions/2949916/what-is-the-difference-betwen-ipa-and-app-format-in-ios)

An .app file does contain Info.plist. Why there should be two places to contain Info.plist?

**Comment by KazuCocoa** [comment]
So, your app does not have `Payload/yourapp.app/Info.plist`, correct? The `Payload`'s zip is `.ipa`. The logic in https://github.com/appium/appium-xcuitest-driver/blob/f00d231d6ab0986de7c6d5fa090ec4f9f283dc80/lib/driver.js#L1562 reads the info.plist in `Payload/yourapp.app` in this case.

Could you share the full appium log as well? Possibly some extracting steps would be missed.

**Comment by evgenyvalavin** [comment]
> So, your app does not have `Payload/yourapp.app/Info.plist`, correct?

No, this is incorrect.

1. I have an .ipa.
2. The .ipa only has Payload folder.
3. Inside Payload there's the .app
4. Inside the .app there's Info.plist

.ipa -> Payload -> .app -> Info.plist

**Comment by evgenyvalavin** [comment]
I've been using .ipa for testing until xcuitest 7.15.3.
I am able to test with xcuitest 7.15.3 now only after extracting .app from .ipa.

**Comment by KazuCocoa** [comment]
Could you share the appium log? This is my local sample ipa which has `Payload/sample.app/Info.plist` with xcuitest driver `v7.15.3`.

```
[Appium] Attempting to find matching driver for automationName 'xcuitest' and platformName 'ios'
[Appium] The 'xcuitest' driver was installed and matched caps.
[Appium] Will require it at /Users/kazu/.appium/node_modules/appium-xcuitest-driver
[Appium] Requiring driver at /Users/kazu/.appium/node_modules/appium-xcuitest-driver/build/index.js
[AppiumDriver@473b] Appium v2.5.4 creating new XCUITestDriver (v7.15.3) session
[AppiumDriver@473b] Checking BaseDriver versions for Appium and XCUITestDriver
[AppiumDriver@473b] Appium's BaseDriver version is 9.6.0
[AppiumDriver@473b] XCUITestDriver's BaseDriver version is 9.6.0
[XCUITestDriver@dbad] Creating session with W3C capabilities: {
[XCUITestDriver@dbad]   "alwaysMatch": {
[XCUITestDriver@dbad]     "platformName": "ios",
[XCUITestDriver@dbad]     "appium:automationName": "xcuitest",
[XCUITestDriver@dbad]     "appium:platformVersion": "17.2",
[XCUITestDriver@dbad]     "appium:deviceName": "iPhone 15",
[XCUITestDriver@dbad]     "appium:webDriverAgentUrl": "http://192.168.5.6:8100",
[XCUITestDriver@dbad]     "appium:udid": "00008020-000E5CDA0A23002E",
[XCUITestDriver@dbad]     "appium:app": "/Users/kazu/Desktop/sample.ipa"
[XCUITestDriver@dbad]   },
[XCUITestDriver@dbad]   "firstMatch": [
[XCUITestDriver@dbad]     {}
[XCUITestDriver@dbad]   ]
[XCUITestDriver@dbad] }
[XCUITestDriver@dbad (571d9203)] Session created with session id: 571d9203-0abd-4ee1-9f74-9b6fe12f3235
[XCUITest] Current user: 'kazu'
[XCUITestDriver@dbad (571d9203)] Skipping checking of the real devices availability since the session specifies appium:webDriverAgentUrl
[XCUITestDriver@dbad (571d9203)] Creating iDevice object with udid '00008020-000E5CDA0A23002E'
[XCUITestDriver@dbad (571d9203)] Determining device to run tests on: udid: '00008020-000E5CDA0A23002E', real device: true
[XCUITestDriver@dbad (571d9203)] Event 'xcodeDetailsRetrieved' logged at 1716276181173 (00:23:01 GMT-0700 (Pacific Daylight Time))
[BaseDriver] Using local app '/Users/kazu/Desktop/sample.ipa'
[XCUITestDriver@dbad (571d9203)] Caching the manifest 'Payload/sample.app/Info.plist' for com.kazucocoa.sample app from the compressed source using the key '2785503245'
[XCUITestDriver@dbad (571d9203)] Event 'appConfigured' logged at 1716276181383 (00:23:01 GMT-0700 (Pacific Daylight Time))
[XCUITest] Checking whether app '/Users/kazu/Desktop/sample.ipa' is actually present on file system
[XCUITest] App is present
[XCUITestDriver@dbad (571d9203)] CFBundleIdentifier: "com.kazucocoa.sample"
[XCUITestDriver@dbad (571d9203)] Event 'resetStarted' logged at 1716276181405 (00:23:01 GMT-0700 (Pacific Daylight Time))
[XCUITestDriver@dbad (571d9203)] Reset: running ios real device reset flow
[XCUITestDriver@dbad (571d9203)] Event 'resetComplete' logged at 1716276181405 (00:23:01 GMT-0700 (Pacific Daylight Time))
[XCUITestDriver@dbad (571d9203)] Using WDA path: '/Users/kazu/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent'
[XCUITestDriver@dbad (571d9203)] Using WDA agent: '/Users/kazu/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj'
[XCUITest] Crash reports root '/Users/kazu/Library/Logs/CrashReporter/MobileDevice/iPad' does not exist. Got nothing to gather.
[XCUITestDriver@dbad (571d9203)] Event 'logCaptureStarted' logged at 1716276181650 (00:23:01 GMT-0700 (Pacific Daylight Time))
[XCUITestDriver@dbad (571d9203)] Setting up real device
[XCUITestDriver@dbad (571d9203)] Verifying application platform
[XCUITestDriver@dbad (571d9203)] CFBundleSupportedPlatforms: ["iPhoneOS"]
[XCUITestDriver@dbad (571d9203)] App 'com.kazucocoa.sample' is not installed yet or it has an offload and cannot be detected, which might keep the local data.
[XCUITestDriver@dbad (571d9203)] Installing '/Users/kazu/Desktop/sample.ipa' on the device with UUID '00008020-000E5CDA0A23002E'
[XCUITest] Successfully pushed the file payload (75.30 MB) to the remote location '/sample.ipa' in 5865ms
```

**Comment by KazuCocoa** [comment]
Based on recent changes, perhaps https://github.com/appium/appium-xcuitest-driver/pull/2394 could be related

**Comment by evgenyvalavin** [comment]
```
[Appium] Attempting to find matching driver for automationName 'XCuiTest' and platformName 'iOS'
[Appium] The 'xcuitest' driver was installed and matched caps.
[Appium] Will require it at /Users/evgenyvalavin/.appium/node_modules/appium-xcuitest-driver
[Appium] Requiring driver at /Users/evgenyvalavin/.appium/node_modules/appium-xcuitest-driver/build/index.js
[AppiumDriver@ac48] Appium v2.5.4 creating new XCUITestDriver (v7.15.3) session
[AppiumDriver@ac48] Checking BaseDriver versions for Appium and XCUITestDriver
[AppiumDriver@ac48] Appium's BaseDriver version is 9.6.0
[AppiumDriver@ac48] XCUITestDriver's BaseDriver version is 9.6.0
[XCUITestDriver@c5c9] Creating session with W3C capabilities: {
[XCUITestDriver@c5c9]   "alwaysMatch": {
[XCUITestDriver@c5c9]     "platformName": "iOS",
[XCUITestDriver@c5c9]     "appium:automationName": "XCuiTest",
[XCUITestDriver@c5c9]     "appium:udid": "device_id",
[XCUITestDriver@c5c9]     "appium:xcodeOrgId": "org_id",
[XCUITestDriver@c5c9]     "appium:xcodeSigningId": "Apple Development"
[XCUITestDriver@c5c9]   },
[XCUITestDriver@c5c9]   "firstMatch": [
[XCUITestDriver@c5c9]     {}
[XCUITestDriver@c5c9]   ]
[XCUITestDriver@c5c9] }
[XCUITestDriver@c5c9] The desired capabilities include neither an app nor a bundleId. WebDriverAgent will be started without the default app
[XCUITestDriver@c5c9] 'platformVersion' capability ('undefined') is not a valid version number. Consider fixing it or be ready to experience an inconsistent driver behavior.
[XCUITestDriver@c5c9 (84020c06)] Session created with session id: 84020c06-c49e-45fd-a9f2-a7d3fe35d478
[XCUITest] Current user: 'evgenyvalavin'
[XCUITestDriver@c5c9 (84020c06)] Available real devices: device_id
[XCUITestDriver@c5c9 (84020c06)] Creating iDevice object with udid 'device_id'
[XCUITestDriver@c5c9 (84020c06)] Determining device to run tests on: udid: 'device_id', real device: true
[XCUITestDriver@c5c9 (84020c06)] No platformVersion specified. Using device version: '17.4.1'
[XCUITestDriver@c5c9 (84020c06)] Normalized platformVersion capability value '17.4.1' to '17.4'
[XCUITestDriver@c5c9 (84020c06)] Event 'xcodeDetailsRetrieved' logged at 1716276519508 (10:28:39 GMT+0300 (Eastern European Summer Time))
[XCUITestDriver@c5c9 (84020c06)] Event 'appConfigured' logged at 1716276519508 (10:28:39 GMT+0300 (Eastern European Summer Time))
[XCUITestDriver@c5c9 (84020c06)] Event 'resetStarted' logged at 1716276519508 (10:28:39 GMT+0300 (Eastern European Summer Time))
[XCUITestDriver@c5c9 (84020c06)] Reset: running ios real device reset flow
[XCUITestDriver@c5c9 (84020c06)] Event 'resetComplete' logged at 1716276519508 (10:28:39 GMT+0300 (Eastern European Summer Time))
[XCUITestDriver@c5c9 (84020c06)] Using WDA path: '/Users/evgenyvalavin/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent'
[XCUITestDriver@c5c9 (84020c06)] Using WDA agent: '/Users/evgenyvalavin/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj'
[XCUITest] Crash reports root '/Users/evgenyvalavin/Library/Logs/CrashReporter/MobileDevice/Evgeny’s iPhone' does not exist. Got nothing to gather.
[XCUITestDriver@c5c9 (84020c06)] Event 'logCaptureStarted' logged at 1716276519623 (10:28:39 GMT+0300 (Eastern European Summer Time))
[XCUITestDriver@c5c9 (84020c06)] Setting up real device
[XCUITestDriver@c5c9 (84020c06)] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[DevCon Factory] Requesting connection for device device_id on local port 8100, device port 8100
[DevCon Factory] Cached connections count: 0
[DevCon Factory] Successfully requested the connection for device_id:8100
[XCUITestDriver@c5c9 (84020c06)] Starting WebDriverAgent initialization with the synchronization key 'XCUITestDriver'
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] Got response with status 200: {"value":{"build":{"upgradedAt":"1714642396281","version":"8.5.6","time":"May 20 2024 22:33:25","productBundleIdentifier":"com.facebook.WebDriverAgentRunner"},"os":{"testmanagerdVersion":65535,"name":"iOS","sdkVersion":"17.4","version":"17.4.1"},"device":"iphone","ios":{"ip":"192.168.1.105"},"message":"WebDriverAgent is ready to accept commands","state":"success","ready":true},"sessionId":null}
[XCUITestDriver@c5c9 (84020c06)] Upgrade timestamp of the currently bundled WDA: 1714642396281
[XCUITestDriver@c5c9 (84020c06)] Upgrade timestamp of the WDA on the device: 1714642396281
[XCUITestDriver@c5c9 (84020c06)] Will reuse previously cached WDA instance at 'http://127.0.0.1:8100/' with 'com.facebook.WebDriverAgentRunner'. Set the wdaLocalPort capability to a value different from 8100 if this is an undesired behavior.
[XCUITestDriver@c5c9 (84020c06)] Trying to start WebDriverAgent 1 times with 10000ms interval
[XCUITestDriver@c5c9 (84020c06)] These values can be customized by changing wdaStartupRetries/wdaStartupRetryInterval capabilities
[XCUITestDriver@c5c9 (84020c06)] Event 'wdaStartAttempted' logged at 1716276519675 (10:28:39 GMT+0300 (Eastern European Summer Time))
[XCUITestDriver@c5c9 (84020c06)] Using provided WebdriverAgent at 'http://127.0.0.1:8100/'
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] Got response with status 200: {"value":{"build":{"upgradedAt":"1714642396281","version":"8.5.6","time":"May 20 2024 22:33:25","productBundleIdentifier":"com.facebook.WebDriverAgentRunner"},"os":{"testmanagerdVersion":65535,"name":"iOS","sdkVersion":"17.4","version":"17.4.1"},"device":"iphone","ios":{"ip":"192.168.1.105"},"message":"WebDriverAgent is ready to accept commands","state":"success","ready":true},"sessionId":null}
[XCUITestDriver@c5c9 (84020c06)] Event 'wdaSessionAttempted' logged at 1716276519681 (10:28:39 GMT+0300 (Eastern European Summer Time))
[XCUITestDriver@c5c9 (84020c06)] Sending createSession command to WDA
[XCUITestDriver@c5c9 (84020c06)] Matched '/session' to command name 'createSession'
[XCUITestDriver@c5c9 (84020c06)] Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true,"shouldTerminateApp":true,"forceAppLaunch":true,"useNativeCachingStrategy":true,"forceSimulatorSoftwareKeyboardPresence":true}],"alwaysMatch":{}}}
[XCUITestDriver@c5c9 (84020c06)] Got response with status 200: {"value":{"sessionId":"4E624494-2D59-46E9-B7BF-B7CE75F559AE","capabilities":{"sdkVersion":"17.4.1","device":"iphone"}},"sessionId":"4E624494-2D59-46E9-B7BF-B7CE75F559AE"}
[XCUITestDriver@c5c9 (84020c06)] Determined the downstream protocol as 'W3C'
[XCUITestDriver@c5c9 (84020c06)] WDA session startup took 8ms
[XCUITestDriver@c5c9 (84020c06)] Event 'wdaSessionStarted' logged at 1716276519690 (10:28:39 GMT+0300 (Eastern European Summer Time))
[XCUITestDriver@c5c9 (84020c06)] Event 'wdaStarted' logged at 1716276519690 (10:28:39 GMT+0300 (Eastern European Summer Time))
[BaseDriver] The value of 'elementResponseAttributes' setting did not change. Skipping the update for it
[BaseDriver] The value of 'shouldUseCompactResponses' setting did not change. Skipping the update for it
[AppiumDriver@ac48] New XCUITestDriver session created successfully, session 84020c06-c49e-45fd-a9f2-a7d3fe35d478 added to master session list
[AppiumDriver@ac48] Event 'newSessionStarted' logged at 1716276519690 (10:28:39 GMT+0300 (Eastern European Summer Time))
[XCUITestDriver@c5c9 (84020c06)] Cached the protocol value 'W3C' for the new session 84020c06-c49e-45fd-a9f2-a7d3fe35d478
[XCUITestDriver@c5c9 (84020c06)] Responding to client with driver.createSession() result: {"capabilities":{"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"platformName":"iOS","automationName":"XCuiTest","udid":"device_id","xcodeOrgId":"org_id","xcodeSigningId":"Apple Development","platformVersion":"17.4"}}
[HTTP] <-- POST /session 200 252 ms - 447
[HTTP] 
[HTTP] Request idempotency key: 977efecd-66b3-4331-b149-eca76167feef
[HTTP] --> POST /session/84020c06-c49e-45fd-a9f2-a7d3fe35d478/timeouts
[HTTP] {"implicit":2000}
[XCUITestDriver@c5c9 (84020c06)] Calling AppiumDriver.timeouts() with args: [null,null,null,null,2000,"84020c06-c49e-45fd-a9f2-a7d3fe35d478"]
[XCUITestDriver@c5c9 (84020c06)] Executing command 'timeouts'
[XCUITestDriver@c5c9 (84020c06)] W3C timeout argument: {"implicit":2000}}
[XCUITestDriver@c5c9 (84020c06)] Set implicit wait to 2000ms
[XCUITestDriver@c5c9 (84020c06)] Responding to client with driver.timeouts() result: null
[HTTP] <-- POST /session/84020c06-c49e-45fd-a9f2-a7d3fe35d478/timeouts 200 1 ms - 14
[HTTP] 
[HTTP] Request idempotency key: e66c0047-d108-45e2-b415-eb370d2bc04a
[HTTP] --> POST /session/84020c06-c49e-45fd-a9f2-a7d3fe35d478/appium/device/remove_app
[HTTP] {"appId":"app.bundle.id"}
[XCUITestDriver@c5c9 (84020c06)] Calling AppiumDriver.removeApp() with args: ["app.bundle.id",null,null,null,"84020c06-c49e-45fd-a9f2-a7d3fe35d478"]
[XCUITestDriver@c5c9 (84020c06)] Executing command 'removeApp'
[XCUITestDriver@c5c9 (84020c06)] Uninstalling the application with bundle identifier 'app.bundle.id' from the real device with UDID 'device_id'
[XCUITestDriver@c5c9 (84020c06)] Removal of 'app.bundle.id' succeeded
[XCUITestDriver@c5c9 (84020c06)] Responding to client with driver.removeApp() result: true
[HTTP] <-- POST /session/84020c06-c49e-45fd-a9f2-a7d3fe35d478/appium/device/remove_app 200 413 ms - 14
[HTTP] 
[HTTP] Request idempotency key: cd5ef714-088b-43e9-a12d-9e3880dd7dfa
[HTTP] --> POST /session/84020c06-c49e-45fd-a9f2-a7d3fe35d478/appium/device/install_app
[HTTP] {"appPath":"/Users/evgenyvalavin/Downloads/application.ipa"}
[XCUITestDriver@c5c9 (84020c06)] Calling AppiumDriver.installApp() with args: ["/Users/evgenyvalavin/Downloads/application.ipa",null,null,null,"84020c06-c49e-45fd-a9f2-a7d3fe35d478"]
[XCUITestDriver@c5c9 (84020c06)] Executing command 'installApp'
[BaseDriver] Using local app '/Users/evgenyvalavin/Downloads/application.ipa'
[XCUITestDriver@c5c9 (84020c06)] Encountered internal error running command: Error: Cannot extract Info.plist from '/Users/evgenyvalavin/Downloads/application.ipa'. Is it a valid application bundle?
[XCUITestDriver@c5c9 (84020c06)]     at AppInfosCache._putIpa (/Users/evgenyvalavin/.appium/node_modules/appium-xcuitest-driver/lib/app-infos-cache.js:140:13)
[XCUITestDriver@c5c9 (84020c06)]     at AppInfosCache.put (/Users/evgenyvalavin/.appium/node_modules/appium-xcuitest-driver/lib/app-infos-cache.js:86:9)
[XCUITestDriver@c5c9 (84020c06)]     at XCUITestDriver.onPostConfigureApp (/Users/evgenyvalavin/.appium/node_modules/appium-xcuitest-driver/lib/app-utils.js:654:5)
[XCUITestDriver@c5c9 (84020c06)]     at /usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/helpers.js:361:22
[HTTP] <-- POST /session/84020c06-c49e-45fd-a9f2-a7d3fe35d478/appium/device/install_app 500 78 ms - 726
[HTTP] 
[HTTP] --> DELETE /session/84020c06-c49e-45fd-a9f2-a7d3fe35d478
[HTTP] {}
```

**Comment by evgenyvalavin** [comment]
I guess in your case you use "appium:app": "/Users/kazu/Desktop/sample.ipa"
In my case I use "AppiumDriver.installApp()"

**Comment by KazuCocoa** [comment]
Could you share the ipa, or mimimal project like template and build with dotnet publish? Via install_app endpoint also had no issue with my local ipa. Or perhaps dumpling your app structure, especially Info.plist would help. e.g. it may have multiple info.plist


```
[HTTP] --> POST /session/8f0b07e1-d893-40fe-90a2-d67ebd988e07/appium/device/install_app
[HTTP] {"appPath":"/Users/kazu/Desktop/sample.ipa"}
[XCUITestDriver@d7ac (8f0b07e1)] Calling AppiumDriver.installApp() with args: ["/Users/kazu/Desktop/sample.ipa",null,null,null,"8f0b07e1-d893-40fe-90a2-d67ebd988e07"]
[XCUITestDriver@d7ac (8f0b07e1)] Executing command 'installApp'
[BaseDriver] Using local app '/Users/kazu/Desktop/sample.ipa'
[XCUITestDriver@d7ac (8f0b07e1)] Installing '/Users/kazu/Desktop/sample.ipa' to the real device with UDID '00008020-000E5CDA0A23002E'
```

The error itself is maybe in https://github.com/appium/appium-xcuitest-driver/blob/480c061428db46e24583ce5cf63c3d42bcd6228c/lib/app-infos-cache.js#L100-L133

**Comment by evgenyvalavin** [comment]
IPA
https://www.transfernow.net/dl/20240521HDuG1UWa

**Comment by KazuCocoa** [comment]
Thanks. the reason was the app name had `.`. maybe https://github.com/appium/appium-xcuitest-driver/blob/480c061428db46e24583ce5cf63c3d42bcd6228c/lib/app-infos-cache.js#L13-L15 needs to turn up the pattern.

`Payload/appname.something.app/Info.plist`

**Comment by KazuCocoa** [comment]
just a note.
Maybe reading zip content part has an issue -> https://github.com/appium/appium/blob/2b2fb185a6bc882717e4aa0580b0136bf5ae2942/packages/support/lib/zip.js ...?

Perhaps... it could take time but extracting `ipa` to `app` would help at least (although it is not good for performance tho https://github.com/appium/appium-xcuitest-driver/pull/2388 tried to improve)

**Comment by KazuCocoa** [comment]
@evgenyvalavin Could you try out `7.16.1`? I checked `Payload/appname.something.app` naming as ipa parsed the info plist.

**Comment by evgenyvalavin** [comment]
Confirm. Fixed!
@KazuCocoa thanks!
