### ISSUE TITLE
Appium 2.6.0 error:  selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot read properties of null (reading 'unpipe')

### ISSUE THREAD

**Issue by tking16** [appium/appium#20185]
Getting a couple test failures, never seen this one before but I recently updated Appium.

From the test report it seems to have failed during Teardown
```
>           yield from driver(request, _driver_class, _driver_kwargs)

_env/lib/python3.9/site-packages/pytest_appium/conftest.py:175: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
_env/lib/python3.9/site-packages/pytest_appium/conftest.py:90: in driver
    driver.quit()
_env/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:469: in quit
    self.execute(Command.QUIT)
_env/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:347: in execute
    self.error_handler.check_response(response)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <appium.webdriver.errorhandler.MobileErrorHandler object at 0x1049985b0>
response = {'status': 500, 'value': '{"value":{"error":"unknown error","message":"An unknown server-side error occurred while pro...Handler (/Users/jenkins/guacamole/testing/app-at/node_modules/@appium/base-driver/lib/protocol/protocol.js:491:57)"}}'}
[...]
>       raise exception_class(msg=message, stacktrace=format_stacktrace(stacktrace))
E       selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot read properties of null (reading 'unpipe')
E       Stacktrace:
E       UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot read properties of null (reading 'unpipe')
E           at getResponseForW3CError (/Users/jenkins/guacamole/testing/app-at/node_modules/@appium/base-driver/lib/protocol/errors.js:1145:9)
E           at asyncHandler (/Users/jenkins/guacamole/testing/app-at/node_modules/@appium/base-driver/lib/protocol/protocol.js:491:57)
```
Below are logs of currently running tests with the failure in motion
[unpipe.log](https://github.com/user-attachments/files/15546113/unpipe.log)

Other info:
```
  "devDependencies": {
    "appium-dashboard": "^2.0.2",
    "appium-device-farm": "^8.2.3",
    "appium-uiautomator2-driver": "^2.43.4",
    "appium-xcuitest-driver": "^7.15.2"
  }
```
Selenium Grid version: 21.0
All Simulators, no real devices

**Comment by mykola-mokhnach** [comment]
```
[38;5;32m[XCUITestDriver@7143 (d6547b25)][0m Closing MJPEG stream
[38;5;16m[AppiumDriver@4e77][0m Had trouble ending session d6547b25-9b4b-4847-a164-419d19d702f3: Cannot read properties of null (reading 'unpipe')
[38;5;16m[AppiumDriver@4e77][0m Event 'quitSessionFinished' logged at 1717491017118 (09:50:17 GMT+0100 (British Summer Time))
[38;5;16m[AppiumDriver@4e77][0m Encountered internal error running command: TypeError: Cannot read properties of null (reading 'unpipe')
[38;5;16m[AppiumDriver@4e77][0m     at MJpegStream.stop (/Users/Jenkins/guacamole/testing/app-at/node_modules/@appium/support/lib/mjpeg.js:179:25)
[38;5;16m[AppiumDriver@4e77][0m     at XCUITestDriver.deleteSession (/Users/Jenkins/guacamole/testing/app-at/node_modules/appium-xcuitest-driver/lib/driver.js:978:24)
[38;5;16m[AppiumDriver@4e77][0m     at AppiumDriver.deleteSession (/Users/Jenkins/guacamole/testing/app-at/node_modules/appium/lib/appium.js:887:16)
```

This exception is related to the fact MJPEG streaming is used.

**Comment by mykola-mokhnach** [comment]
The patch has been published in the recent server update

**Comment by tking16** [comment]
Thanks @mykola-mokhnach , it's probably too late to update now but I completely forgot. I was getting the error because I accidentally set `mjpegScreenshotUrl` to `localhost/9101` instead of `localhost:9101` but thank you for resolving
