### ISSUE TITLE
appium 2.7.0 runtime failure

### ISSUE THREAD

**Issue by chenrui333** [appium/appium#20206]
Trying to install using node 22, but failed to run, error is below:

```
$ appium --version
node:internal/modules/cjs/loader:1189
  throw err;
  ^

Error: Cannot find module '@appium/logger'
Require stack:
- /Users/rui/.nvm/versions/node/v22.2.0/lib/node_modules/appium/build/lib/logsink.js
- /Users/rui/.nvm/versions/node/v22.2.0/lib/node_modules/appium/build/lib/main.js
- /Users/rui/.nvm/versions/node/v22.2.0/lib/node_modules/appium/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1186:15)
    at Module._load (node:internal/modules/cjs/loader:1012:27)
    at Module.require (node:internal/modules/cjs/loader:1271:19)
    at require (node:internal/modules/helpers:123:16)
    at Object.<anonymous> (/Users/rui/.nvm/versions/node/v22.2.0/lib/node_modules/appium/build/lib/logsink.js:7:34)
    at Module._compile (node:internal/modules/cjs/loader:1434:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1518:10)
    at Module.load (node:internal/modules/cjs/loader:1249:32)
    at Module._load (node:internal/modules/cjs/loader:1065:12)
    at Module.require (node:internal/modules/cjs/loader:1271:19)
    at require (node:internal/modules/helpers:123:16)
    at Object.<anonymous> (/Users/rui/.nvm/versions/node/v22.2.0/lib/node_modules/appium/build/lib/main.js:9:19)
    at Module._compile (node:internal/modules/cjs/loader:1434:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1518:10)
    at Module.load (node:internal/modules/cjs/loader:1249:32)
    at Module._load (node:internal/modules/cjs/loader:1065:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/rui/.nvm/versions/node/v22.2.0/lib/node_modules/appium/build/lib/logsink.js',
    '/Users/rui/.nvm/versions/node/v22.2.0/lib/node_modules/appium/build/lib/main.js',
    '/Users/rui/.nvm/versions/node/v22.2.0/lib/node_modules/appium/index.js'
  ]
}

Node.js v22.2.0
```

relates to https://github.com/Homebrew/homebrew-core/pull/173894

**Comment by eglitise** [comment]
This should be fixed in Appium 2.8.0
