### ISSUE TITLE
bug: Protocol bs:// is not supported for mobile:installApp XCUITest IOSDriver as app parameter value

### ISSUE THREAD

**Issue by itkhanz** [appium/appium#20252]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi,
I am executing my Appium tests for IOS App via XCUITest driver on BrowserStack. BrowserStack provides the Hashed App ID which we are using in the app capability of driver options to install the app. This hashed app ID starts with `bs://`

This works fine for normal app installation for creating the session, however after uninstalling the app via [mobile: removeApp](https://appium.github.io/appium-xcuitest-driver/latest/reference/execute-methods/#mobile-removeapp), Appium server/driver fails to install the app via [mobile: installApp](https://appium.github.io/appium-xcuitest-driver/latest/reference/execute-methods/#mobile-installapp)
```
import io.appium.java_client.ios.IOSDriver;

driver.executeScript(
                    "mobile: installApp", ImmutableMap.of(
                            "app", HASHED_APP_URL
            ));
```

The above command and code works fine locally, when i specify the path to app on my PC.

Moreover, I am able to use this Hashed App ID perfectly fine with UIAutomator2 Android driver as describer here via below code snippet:
https://github.com/appium/appium-uiautomator2-driver/?tab=readme-ov-file#mobile-installapp

` driver.installApp(HASHED_APP_URL, new AndroidInstallApplicationOptions().withReplaceEnabled());
`

I do not know why Appium is throwing this error when I execute this script to install iOS app and IOSDriver:

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: The protocol 'bs:' used in 'bs://77c5ewsfcd3443432d726c2a88de4ce587' is not supported. Only http: and https: protocols are supported
Build info: version: '4.19.0', revision: '5f9cec8963'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '14.5', java.version: '17.0.2'
Driver info: io.appium.java_client.ios.IOSDriver
Command: [fd5d4f019c99232007d0fc14bb5e92a6f3726aaf, executeScript {args=[{app=bs://77c5ewsfcd3443432d726c2a88de4ce587}], script=mobile: installApp}]
Capabilities {appium:automationName: xcuitest, appium:bootstrapPath: /usr/local/.browserstack/co..., appium:browserstack.isTargetBased: true, appium:build: ios local test run 2024-06-13, appium:bundleID: com.digital..., appium:bundleId: com.digital..., appium:databaseEnabled: false, appium:deviceName: iphone 15 pro max, appium:deviceOrientation: PORTRAIT, appium:javascriptEnabled: true, appium:keychainPassword: [REDACTED VALUE], appium:keychainPath: [REDACTED VALUE], appium:language: en_gb, appium:locale: gb, appium:locationContextEnabled: false, appium:name: debugtest.test_app_actions, appium:networkConnectionEnabled: false, appium:newCommandTimeout: 200, appium:noReset: false, appium:orientation: PORTRAIT, appium:project: test run for:b2c ios, appium:realMobile: true, appium:safariIgnoreFraudWarning: true, appium:safariInitialUrl: http://mobile-internet-chec..., appium:takesScreenshot: true, appium:udid: 00008130-001425541E2B803A, appium:useXctestrunFile: true, appium:waitForQuiescence: false, appium:wdaLocalPort: 8006, appium:wdaStartupRetries: 3, appium:webStorageEnabled: false, appium:webkitResponseTimeout: 20000, platformName: IOS}
Session ID: fd5d4f019c99232007d0fc14bb5e92a6f3726aaf
	at java.base@17.0.2/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base@17.0.2/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base@17.0.2/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base@17.0.2/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base@17.0.2/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at app//org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
	at app//org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
	at app//org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
	at app//org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:190)
	at app//io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:237)
	at app//org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:518)
	at app//org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:463)
	at app//com.dcs.appium.core.actions.application.IOSAppManager.installApp(IOSAppManager.java:44)
	at app//com.dcs.appium.testing.tests.DebugTest.test_app_actions(DebugTest.java:47)
	at java.base@17.0.2/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.2/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17.0.2/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17.0.2/java.lang.reflect.Method.invoke(Method.java:568)
	at app//org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
	at app//org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
	at app//org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
	at app//org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
	at app//org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
	at app//org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
	at app//org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
	at app//org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
	at java.base@17.0.2/java.util.ArrayList.forEach(ArrayList.java:1511)
	at app//org.testng.TestRunner.privateRun(TestRunner.java:739)
	at app//org.testng.TestRunner.run(TestRunner.java:614)
	at app//org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
	at app//org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
	at app//org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
	at app//org.testng.SuiteRunner.run(SuiteRunner.java:312)
	at app//org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at app//org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at app//org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
	at app//org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
	at app//org.testng.TestNG.runSuites(TestNG.java:1112)
	at app//org.testng.TestNG.run(TestNG.java:1079)
	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.runTests(TestNGTestClassProcessor.java:153)
	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.stop(TestNGTestClassProcessor.java:96)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:62)
	at java.base@17.0.2/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.2/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17.0.2/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17.0.2/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)

### Expected Behavior

Application should be installed successfully using HASHED APP URL starting with `bs://` as in below snippet
```
driver.executeScript(
      "mobile: installApp", ImmutableMap.of(
              "app", APP_URL
));
```

### Minimal Reproducible Example

You will need to pass the HASHED APP ID that starts with bs:// as app parameter.

Start the XCUITest IOS Driver session.

First uninstall the app as:
```
driver.executeScript(
      "mobile: removeApp", ImmutableMap.of(
              "bundleId", BUNDLE_ID
));

```

Then install the app as shown below and use the APP_URL provided  by BrowserStack (the same URL works fine when passing as value for app in XCUITtest driver session options at the time of creating session):
```
driver.executeScript(
      "mobile: installApp", ImmutableMap.of(
              "app", APP_URL
 ));
```

gf

### Environment

- Operating system: macOS
- Appium server version (output of `appium --version`): 2.4.1
- Appium driver(s) and their version(s) (`appium driver list`): xcuitest@5.14.0
- Node.js version (output of `node --version`): v20.11.0
- `npm` version (output of `npm --version`): 10.2.4
- Last component(s) version which did _not_ exhibit the problem: works fine with local app URL as well as with uiautomator2@2.45.1
- Platform and version under test: iOS 17.2, iOS 17.3
- Real device or emulator/simulator: Real device iOS 15 Pro Max

Appium Java Client 9.2.3

### Further Information

Appium Server logs where I am first uninstalling the app via BUNDLE_ID, and then installing it via APP_URL:-

```
2024-06-13 14:03:13:509 - [XCUITestDriver@a861 (3bf52052)] Calling AppiumDriver.execute() with args: ["mobile: removeApp",[{"bundleId":"com.digital.abc"}],"3bf52052-79e3-4ae6-b459-16a9a5d6cad7"]
2024-06-13 14:03:13:509 - [AppiumDriver@2385] Clearing new command timeout pre-emptively since plugin(s) will handle this command
2024-06-13 14:03:13:509 - [AppiumDriver@2385] Plugins which can handle cmd 'execute': images
2024-06-13 14:03:13:509 - [AppiumDriver@2385] Plugin images is now handling cmd 'execute'
2024-06-13 14:03:13:509 - [AppiumDriver@2385] Executing default handling behavior for command 'execute'
2024-06-13 14:03:13:509 - [XCUITestDriver@a861 (3bf52052)] Executing command 'execute'
2024-06-13 14:03:13:510 - [XCUITestDriver@a861 (3bf52052)] Uninstalling the application with bundle identifier 'com.digital.b2c' from the real device with UDID '00008130-001425541E2B803A'
2024-06-13 14:03:13:874 - [XCUITestDriver@a861 (3bf52052)] Removal of 'com.digital.abc' succeeded
2024-06-13 14:03:13:875 - [XCUITestDriver@a861 (3bf52052)] Responding to client with driver.execute() result: true
2024-06-13 14:03:13:876 - [HTTP] <-- POST /wd/hub/session/3bf52052-79e3-4ae6-b459-16a9a5d6cad7/execute/sync 200 376 ms - 14
2024-06-13 14:03:13:876 - [HTTP] 
2024-06-13 14:03:13:994 - [HTTP] --> POST /wd/hub/session/3bf52052-79e3-4ae6-b459-16a9a5d6cad7/execute/sync
2024-06-13 14:03:13:994 - [HTTP] {"args":[{"app":"bs://77c54deb7507724d06f9c02d726c2a88de4ce587"}],"script":"mobile: installApp"}
2024-06-13 14:03:13:997 - [XCUITestDriver@a861 (3bf52052)] Calling AppiumDriver.execute() with args: ["mobile: installApp",[{"app":"bs://77c5ewsfcd3443432d726c2a88de4ce587"}],"3bf52052-79e3-4ae6-b459-16a9a5d6cad7"]
2024-06-13 14:03:13:997 - [AppiumDriver@2385] Clearing new command timeout pre-emptively since plugin(s) will handle this command
2024-06-13 14:03:13:997 - [AppiumDriver@2385] Plugins which can handle cmd 'execute': images
2024-06-13 14:03:13:998 - [AppiumDriver@2385] Plugin images is now handling cmd 'execute'
2024-06-13 14:03:13:998 - [AppiumDriver@2385] Executing default handling behavior for command 'execute'
2024-06-13 14:03:13:998 - [XCUITestDriver@a861 (3bf52052)] Executing command 'execute'
2024-06-13 14:03:14:011 - [XCUITestDriver@a861 (3bf52052)] Encountered internal error running command: Error: The protocol 'bs:' used in 'bs://77c5ewsfcd3443432d726c2a88de4ce587' is not supported. Only http: and https: protocols are supported
2024-06-13 14:03:14:011 - [XCUITestDriver@a861 (3bf52052)]     at /nix/store/x8mln24649289b9bmfnjv351cgs4m7jm-appium-2.4.1/packages/base-driver/lib/basedriver/helpers.js:276:13
2024-06-13 14:03:14:027 - [HTTP] <-- POST /wd/hub/session/3bf52052-79e3-4ae6-b459-16a9a5d6cad7/execute/sync 500 33 ms - 796
2024-06-13 14:03:14:028 - [HTTP] 
```

**Comment by mykola-mokhnach** [comment]
This behaviour is expected for vanilla appium. Please report you issue to Browserstack

**Comment by itkhanz** [comment]
> This behaviour is expected for vanilla appium. Please report you issue to Browserstack

Thank you for looking into this issue.
Is this behaviour expected only for XCUITest driver? I am confused as to why then UIAutomator2 driver is able to install the app with bs:// protocol and the XCUITest driver fails with the same vanilla Appium.

Please let me know if this error is causing because of Appium XCUITest driver or Appium Server?

**Comment by KazuCocoa** [comment]
Could you share the working vanilla uia2 driver appium log?
https://github.com/appium/appium/blob/4345a40a15d2473bb13524593ab66ff8ae3d8a7e/packages/base-driver/lib/basedriver/helpers.js#L618-L625 is our supported protocol. Others are vendor customization.

**Comment by itkhanz** [comment]
> Could you share the working vanilla uia2 driver appium log?
> 
> https://github.com/appium/appium/blob/4345a40a15d2473bb13524593ab66ff8ae3d8a7e/packages/base-driver/lib/basedriver/helpers.js#L618-L625
> 
> is our supported protocol. Others are vendor customization.

you are right probably. 
I think BrowserStack has done some customisation of the Appium at their end because of which i am getting this error. I have also asked their support team this issue. I tried to find the logs for install command for UIAutomator2 driver session in BrowserStack Appium server logs, but I could not locate this command installApp being executed in logs. Not sure why is this not being depicted in logs although test ran just fine.

I performed following command in sequence:

1. removeApp
2. isAppInstalled
3. installApp
4. isAppInstalled
5. activateApp

Here are the logs:-


```
2024-06-13 16:47:55:278 - [HTTP] 
2024-06-13 16:47:55:361 - [HTTP] --> POST /wd/hub/session/ba0d38ab-938c-48ec-999b-8677e7bb6642/execute/sync
2024-06-13 16:47:55:361 - [HTTP] {"args":[{"appId":"com.digitalchargingsolutions.b2c.integ","bundleId":"com.digitalchargingsolutions.b2c.integ"}],"script":"mobile: removeApp"}
2024-06-13 16:47:55:365 - [AndroidUiautomator2Driver@362a (ba0d38ab)] Calling AppiumDriver.execute() with args: ["mobile: removeApp",[{"appId":"com.digitalchargingsolutions.b2c.integ","bundleId":"com.digitalchargingsolutions.b2c.integ"}],"ba0d38ab-938c-48ec-999b-8677e7bb6642"]
2024-06-13 16:47:55:365 - [AppiumDriver@2e41] Clearing new command timeout pre-emptively since plugin(s) will handle this command
2024-06-13 16:47:55:365 - [AppiumDriver@2e41] Plugins which can handle cmd 'execute': images
2024-06-13 16:47:55:365 - [AppiumDriver@2e41] Plugin images is now handling cmd 'execute'
2024-06-13 16:47:55:365 - [AppiumDriver@2e41] Executing default handling behavior for command 'execute'
2024-06-13 16:47:55:366 - [AndroidUiautomator2Driver@362a (ba0d38ab)] Executing method 'mobile: removeApp'
2024-06-13 16:47:55:367 - [ADB] Uninstalling com.digitalchargingsolutions.b2c.integ
2024-06-13 16:47:55:367 - [ADB] Getting install status for com.digitalchargingsolutions.b2c.integ
2024-06-13 16:47:55:367 - [ADB] Running '/usr/local/.browserstack/android-sdk/platform-tools/adb -P 5037 -s RZCX413MH7X shell pm path com.digitalchargingsolutions.b2c.integ'
2024-06-13 16:47:55:449 - [ADB] 'com.digitalchargingsolutions.b2c.integ' is installed
2024-06-13 16:47:55:449 - [ADB] Running '/usr/local/.browserstack/android-sdk/platform-tools/adb -P 5037 -s RZCX413MH7X shell am force-stop com.digitalchargingsolutions.b2c.integ'
2024-06-13 16:47:55:538 - [ADB] Running '/usr/local/.browserstack/android-sdk/platform-tools/adb -P 5037 -s RZCX413MH7X uninstall com.digitalchargingsolutions.b2c.integ'
2024-06-13 16:47:55:755 - [ADB] 'adb uninstall com.digitalchargingsolutions.b2c.integ' command output: Success
2024-06-13 16:47:55:755 - [ADB] com.digitalchargingsolutions.b2c.integ was successfully uninstalled
2024-06-13 16:47:55:755 - [AndroidUiautomator2Driver@362a (ba0d38ab)] Responding to client with driver.execute() result: true
2024-06-13 16:47:55:756 - [HTTP] <-- POST /wd/hub/session/ba0d38ab-938c-48ec-999b-8677e7bb6642/execute/sync 200 395 ms - 14
2024-06-13 16:47:55:756 - [HTTP] 
2024-06-13 16:47:55:851 - [HTTP] --> POST /wd/hub/session/ba0d38ab-938c-48ec-999b-8677e7bb6642/execute/sync
2024-06-13 16:47:55:851 - [HTTP] {"args":[{"bundleId":"com.digitalchargingsolutions.b2c.integ","appId":"com.digitalchargingsolutions.b2c.integ"}],"script":"mobile: isAppInstalled"}
2024-06-13 16:47:55:855 - [AndroidUiautomator2Driver@362a (ba0d38ab)] Calling AppiumDriver.execute() with args: ["mobile: isAppInstalled",[{"bundleId":"com.digitalchargingsolutions.b2c.integ","appId":"com.digitalchargingsolutions.b2c.integ"}],"ba0d38ab-938c-48ec-999b-8677e7bb6642"]
2024-06-13 16:47:55:855 - [AppiumDriver@2e41] Clearing new command timeout pre-emptively since plugin(s) will handle this command
2024-06-13 16:47:55:856 - [AppiumDriver@2e41] Plugins which can handle cmd 'execute': images
2024-06-13 16:47:55:856 - [AppiumDriver@2e41] Plugin images is now handling cmd 'execute'
2024-06-13 16:47:55:856 - [AppiumDriver@2e41] Executing default handling behavior for command 'execute'
2024-06-13 16:47:55:856 - [AndroidUiautomator2Driver@362a (ba0d38ab)] Executing method 'mobile: isAppInstalled'
2024-06-13 16:47:55:857 - [ADB] Getting install status for com.digitalchargingsolutions.b2c.integ
2024-06-13 16:47:55:857 - [ADB] Running '/usr/local/.browserstack/android-sdk/platform-tools/adb -P 5037 -s RZCX413MH7X shell pm path com.digitalchargingsolutions.b2c.integ'
2024-06-13 16:47:55:949 - [ADB] 'com.digitalchargingsolutions.b2c.integ' is not installed
2024-06-13 16:47:55:949 - [AndroidUiautomator2Driver@362a (ba0d38ab)] Responding to client with driver.execute() result: false
2024-06-13 16:47:55:950 - [HTTP] <-- POST /wd/hub/session/ba0d38ab-938c-48ec-999b-8677e7bb6642/execute/sync 200 99 ms - 15
2024-06-13 16:47:55:950 - [HTTP] 
2024-06-13 16:48:02:208 - [HTTP] --> POST /wd/hub/session/ba0d38ab-938c-48ec-999b-8677e7bb6642/execute/sync
2024-06-13 16:48:02:208 - [HTTP] {"args":[{"bundleId":"com.digitalchargingsolutions.b2c.integ","appId":"com.digitalchargingsolutions.b2c.integ"}],"script":"mobile: isAppInstalled"}
2024-06-13 16:48:02:209 - [AndroidUiautomator2Driver@362a (ba0d38ab)] Calling AppiumDriver.execute() with args: ["mobile: isAppInstalled",[{"bundleId":"com.digitalchargingsolutions.b2c.integ","appId":"com.digitalchargingsolutions.b2c.integ"}],"ba0d38ab-938c-48ec-999b-8677e7bb6642"]
2024-06-13 16:48:02:209 - [AppiumDriver@2e41] Clearing new command timeout pre-emptively since plugin(s) will handle this command
2024-06-13 16:48:02:209 - [AppiumDriver@2e41] Plugins which can handle cmd 'execute': images
2024-06-13 16:48:02:209 - [AppiumDriver@2e41] Plugin images is now handling cmd 'execute'
2024-06-13 16:48:02:209 - [AppiumDriver@2e41] Executing default handling behavior for command 'execute'
2024-06-13 16:48:02:209 - [AndroidUiautomator2Driver@362a (ba0d38ab)] Executing method 'mobile: isAppInstalled'
2024-06-13 16:48:02:210 - [ADB] Getting install status for com.digitalchargingsolutions.b2c.integ
2024-06-13 16:48:02:210 - [ADB] Running '/usr/local/.browserstack/android-sdk/platform-tools/adb -P 5037 -s RZCX413MH7X shell pm path com.digitalchargingsolutions.b2c.integ'
2024-06-13 16:48:02:255 - [ADB] 'com.digitalchargingsolutions.b2c.integ' is installed
2024-06-13 16:48:02:255 - [AndroidUiautomator2Driver@362a (ba0d38ab)] Responding to client with driver.execute() result: true
2024-06-13 16:48:02:256 - [HTTP] <-- POST /wd/hub/session/ba0d38ab-938c-48ec-999b-8677e7bb6642/execute/sync 200 48 ms - 14
2024-06-13 16:48:02:256 - [HTTP] 
2024-06-13 16:48:02:356 - [HTTP] --> POST /wd/hub/session/ba0d38ab-938c-48ec-999b-8677e7bb6642/execute/sync
2024-06-13 16:48:02:356 - [HTTP] {"args":[{"appId":"com.digitalchargingsolutions.b2c.integ","bundleId":"com.digitalchargingsolutions.b2c.integ"}],"script":"mobile: activateApp"}
2024-06-13 16:48:02:357 - [AndroidUiautomator2Driver@362a (ba0d38ab)] Calling AppiumDriver.execute() with args: ["mobile: activateApp",[{"appId":"com.digitalchargingsolutions.b2c.integ","bundleId":"com.digitalchargingsolutions.b2c.integ"}],"ba0d38ab-938c-48ec-999b-8677e7bb6642"]
2024-06-13 16:48:02:357 - [AppiumDriver@2e41] Clearing new command timeout pre-emptively since plugin(s) will handle this command
2024-06-13 16:48:02:357 - [AppiumDriver@2e41] Plugins which can handle cmd 'execute': images
2024-06-13 16:48:02:357 - [AppiumDriver@2e41] Plugin images is now handling cmd 'execute'
2024-06-13 16:48:02:357 - [AppiumDriver@2e41] Executing default handling behavior for command 'execute'
2024-06-13 16:48:02:357 - [AndroidUiautomator2Driver@362a (ba0d38ab)] Executing method 'mobile: activateApp'
2024-06-13 16:48:02:357 - [AndroidUiautomator2Driver@362a (ba0d38ab)] Activating 'com.digitalchargingsolutions.b2c.integ'
2024-06-13 16:48:02:358 - [ADB] Running '/usr/local/.browserstack/android-sdk/platform-tools/adb -P 5037 -s RZCX413MH7X shell cmd package resolve-activity --brief com.digitalchargingsolutions.b2c.integ'
2024-06-13 16:48:02:397 - [ADB] Running '/usr/local/.browserstack/android-sdk/platform-tools/adb -P 5037 -s RZCX413MH7X shell am start-activity -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n com.digitalchargingsolutions.b2c.integ/com.bmw.chargenow.presentation.views.welcome.SplashActivity'
2024-06-13 16:48:02:467 - [AndroidUiautomator2Driver@362a (ba0d38ab)] Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.digitalchargingsolutions.b2c.integ/com.bmw.chargenow.presentation.views.welcome.SplashActivity }
2024-06-13 16:48:02:467 - [AndroidUiautomator2Driver@362a (ba0d38ab)] Responding to client with driver.execute() result: null
2024-06-13 16:48:02:468 - [HTTP] <-- POST /wd/hub/session/ba0d38ab-938c-48ec-999b-8677e7bb6642/execute/sync 200 112 ms - 14
2024-06-13 16:48:02:468 - [HTTP] 
```
