### ISSUE TITLE
TypeError: this.unwrap(...).updateAsyncStorage is not a function when starting new session

### ISSUE THREAD

**Issue by zach-fetch** [appium/appium#20303]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Cannot connect to appium to create new sessions for testing. When my automation tries to create a new driver instance, appium crashes with the following stack trace:

```
Failure/Error: Unable to infer file and line number from backtrace

     Selenium::WebDriver::Error::UnknownError:
       An unknown server-side error occurred while processing the command: this.unwrap(...).updateAsyncStorage is not a function
     # TypeError: this.unwrap(...).updateAsyncStorage is not a function
     #     at Object.updateAsyncContext (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/node_modules/@appium/support/lib/logging.js:50:21)
     #     at handleLogContext (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/express/middleware.js:86:7)
     #     at Layer.handle [as handle_request] (/opt/homebrew/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
     #     at trim_prefix (/opt/homebrew/lib/node_modules/appium/node_modules/express/lib/router/index.js:328:13)
     #     at /opt/homebrew/lib/node_modules/appium/node_modules/express/lib/router/index.js:286:9
     #     at Function.process_params (/opt/homebrew/lib/node_modules/appium/node_modules/express/lib/router/index.js:346:12)
     #     at next (/opt/homebrew/lib/node_modules/appium/node_modules/express/lib/router/index.js:280:10)
     #     at logger (/opt/homebrew/lib/node_modules/appium/node_modules/morgan/index.js:144:5)
     #     at Layer.handle [as handle_request] (/opt/homebrew/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
     #     at trim_prefix (/opt/homebrew/lib/node_modules/appium/node_modules/express/lib/router/index.js:328:13)
     #     at /opt/homebrew/lib/node_modules/appium/node_modules/express/lib/router/index.js:286:9
     #     at Function.process_params (/opt/homebrew/lib/node_modules/appium/node_modules/express/lib/router/index.js:346:12)
     #     at next (/opt/homebrew/lib/node_modules/appium/node_modules/express/lib/router/index.js:280:10)
     #     at expressInit (/opt/homebrew/lib/node_modules/appium/node_modules/express/lib/middleware/init.js:40:5)
     #     at Layer.handle [as handle_request] (/opt/homebrew/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
     #     at trim_prefix (/opt/homebrew/lib/node_modules/appium/node_modules/express/lib/router/index.js:328:13)
     #     at /opt/homebrew/lib/node_modules/appium/node_modules/express/lib/router/index.js:286:9
     #     at Function.process_params (/opt/homebrew/lib/node_modules/appium/node_modules/express/lib/router/index.js:346:12)
     #     at next (/opt/homebrew/lib/node_modules/appium/node_modules/express/lib/router/index.js:280:10)
     #     at query (/opt/homebrew/lib/node_modules/appium/node_modules/express/lib/middleware/query.js:45:5)
     #     at Layer.handle [as handle_request] (/opt/homebrew/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
     #     at trim_prefix (/opt/homebrew/lib/node_modules/appium/node_modules/express/lib/router/index.js:328:13)
     #     at /opt/homebrew/lib/node_modules/appium/node_modules/express/lib/router/index.js:286:9
     #     at Function.process_params (/opt/homebrew/lib/node_modules/appium/node_modules/express/lib/router/index.js:346:12)
     #     at next (/opt/homebrew/lib/node_modules/appium/node_modules/express/lib/router/index.js:280:10)
     #     at Function.handle (/opt/homebrew/lib/node_modules/appium/node_modules/express/lib/router/index.js:175:3)
     #     at Function.handle (/opt/homebrew/lib/node_modules/appium/node_modules/express/lib/application.js:181:10)
     #     at Server.app (/opt/homebrew/lib/node_modules/appium/node_modules/express/lib/express.js:39:9)
     #     at Server.emit (node:events:532:35)
     #     at parserOnIncoming (node:_http_server:1149:12)
     #     at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
```

I am not sure why this is happening. It seems like a dependency issue, but I have uninstalled and reinstalled a number of times without fixing the issue.

### Expected Behavior

Should be able to create new driver session

### Minimal Reproducible Example

Run the code in https://github.com/appium/appium/tree/master/packages/appium/sample-code/quickstarts/rb

Appium server crashes

### Environment

- Operating system: MacOS
- Appium server version (output of `appium --version`): 2.4.1, 2.0.1, 2.0.0, 2.3.0 (2.4.1 and 2.0.1 are required by browserstack, that is what we use)
- Appium driver(s) and their version(s) (`appium driver list`): - uiautomator2@2.42.1, uiautomator2@2.30, uiautomator2@2.29.2 (2.29.2 and 2.42.1 are required by browserstack, that is what we use)
- Appium plugin(s) and their version(s) (`appium plugin list`): no plugins
- Node.js version (output of `node --version`): 22.2.0
- `npm` version (output of `npm --version`): 10.8.1
- Last component(s) version which did _not_ exhibit the problem: n/a - just started today and I don't know why
- Platform and version under test: Android
- Real device or emulator/simulator: both

**Comment by KazuCocoa** [comment]
Perhaps https://github.com/appium/appium/pull/20250 change affected this behavior.

**Comment by KazuCocoa** [comment]
It looks like this affects users who use `appium@2.6.0` and lower

**Comment by KazuCocoa** [comment]
Maybe... the line `this.unwrap().updateAsyncStorage(contextInfo, replace);` should apply the change only when the function is available

**Comment by KazuCocoa** [comment]
A fresh installation should fix this
