### ISSUE TITLE
when launch release application than showing error "Cannot extract a manifest from 'C:...\MyCo1.apk'. Is it a valid Android application? bug: <title>

### ISSUE THREAD

**Issue by Achalkumartrivedi** [appium/appium#20359]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when used debug build than it opened but it is not opened when release apk try to open
[Appium] Welcome to Appium v2.11.1
[Appium] Non-default server args:
[Appium] { address: '127.0.0.1', basePath: '/wd/hub/', port: 44102, sessionOverride: true }
[Appium] The autodetected Appium home path: C:\Users\LG-20\.appium
[Appium] Attempting to load driver uiautomator2...
[Appium] Requiring driver at C:\Users\LG-20\.appium\node_modules\appium-uiautomator2-driver\build\index.js
[Appium] AndroidUiautomator2Driver has been successfully loaded in 1.393s
[Appium] Appium REST http interface listener started on http://127.0.0.1:44102/wd/hub
[Appium] Available drivers:
[Appium]   - uiautomator2@3.7.1 (automationName 'UiAutomator2')
[Appium] Available plugins:
[Appium]   - execute-driver@3.0.31
[Appium]   - relaxed-caps@1.0.6
[Appium]   - images@3.0.16
[Appium]   - universal-xml@1.0.20
[Appium] No plugins activated. Use the --use-plugins flag with names of plugins to activate
[HTTP] --> GET /wd/hub/status {}
[AppiumDriver@5867] Calling AppiumDriver.getStatus() with args: []
[AppiumDriver@5867] Responding to client with driver.getStatus() result: {"ready":true,"message":"The server is ready to accept new connections","build":{"version":"2.11.1"}}
[HTTP] <-- GET /wd/hub/status 200 8 ms - 111 
Appium server started
Platform Name:Android
Product Verisom:13
Device UDID:emulator-5554
Model Number:sdk_gphone64_x86_64
Build Version:33
[HTTP] --> GET /wd/hub/status {}
[AppiumDriver@5867] Calling AppiumDriver.getStatus() with args: []
[AppiumDriver@5867] Responding to client with driver.getStatus() result: {"ready":true,"message":"The server is ready to accept new connections","build":{"version":"2.11.1"}}
[HTTP] <-- GET /wd/hub/status 200 1 ms - 111 
[HTTP] Request idempotency key: a8c09404-1696-484e-9617-3d7e07ee15f8
[HTTP] --> POST /wd/hub/session {"capabilities":{"firstMatch":[{"appium:noReset":true,"appium:udid":"emulator-5554","appium:ignoreHiddenApiPolicyError":true,"appium:allowTestPackages":true,"appium:deviceName":"sdk_gphone64_x86_64","platformName":"ANDROID","appium:automationName":"UIAutomator2","appium:app":"C:\\Users\\LG-20\\IdeaProjects\\MyCo\\src\\test\\resources\\apkfiles\\MyCo1.apk","appium:platformVersion":"13"}]}}
[AppiumDriver@5867] Calling AppiumDriver.createSession() with args: [null,null,{"firstMatch":[{"appium:noReset":true,"appium:udid":"emulator-5554","appium:ignoreHiddenApiPolicyError":true,"appium:allowTestPackages":true,"appium:deviceName":"sdk_gphone64_x86_64","platformName":"ANDROID","appium:automationName":"UIAutomator2","appium:app":"C:\\Users\\LG-20\\IdeaProjects\\MyCo\\src\\test\\resources\\apkfiles\\MyCo1.apk","appium:platformVersion":"13"}]}]
[AppiumDriver@5867] Event 'newSessionRequested' logged at 1720593689728 (12:11:29 GMT+0530 (India Standard Time))
[Appium] Attempting to find matching driver for automationName 'UIAutomator2' and platformName 'ANDROID'
[Appium] The 'uiautomator2' driver was installed and matched caps.
[Appium] Will require it at C:\Users\LG-20\.appium\node_modules\appium-uiautomator2-driver
[Appium] Requiring driver at C:\Users\LG-20\.appium\node_modules\appium-uiautomator2-driver\build\index.js
[AppiumDriver@5867] Appium v2.11.1 creating new AndroidUiautomator2Driver (v3.7.1) session
[AppiumDriver@5867] Checking BaseDriver versions for Appium and AndroidUiautomator2Driver
[AppiumDriver@5867] Appium's BaseDriver version is 9.11.1
[AppiumDriver@5867] AndroidUiautomator2Driver's BaseDriver version is 9.11.1
[AppiumDriver@5867] There are no active sessions for cleanup
[38;5;-57m[AndroidUiautomator2Driver@1f6e] undefined
[38;5;-57m[AndroidUiautomator2Driver@1f6e] Creating session with W3C capabilities: {
  "alwaysMatch": {
    "platformName": "ANDROID",
    "appium:noReset": true,
    "appium:udid": "emulator-5554",
    "appium:ignoreHiddenApiPolicyError": true,
    "appium:allowTestPackages": true,
    "appium:deviceName": "sdk_gphone64_x86_64",
    "appium:automationName": "UIAutomator2",
    "appium:app": "C:\\Users\\LG-20\\IdeaProjects\\MyCo\\src\\test\\resources\\apkfiles\\MyCo1.apk",
    "appium:platformVersion": "13"
  },
  "firstMatch": [
    {}
  ]
}
[09a9d0fe][38;5;-57m[AndroidUiautomator2Driver@1f6e] Session created with session id: 09a9d0fe-0789-4833-8df9-b7e053296380
[09a9d0fe][ADB] Found 2 'build-tools' folders under 'C:\Users\LG-20\AppData\Local\Android\Sdk' (newest first):
[09a9d0fe][ADB]     C:\Users\LG-20\AppData\Local\Android\Sdk\build-tools\35.0.0
[09a9d0fe][ADB]     C:\Users\LG-20\AppData\Local\Android\Sdk\build-tools\34.0.0
[09a9d0fe][ADB] Using 'adb.exe' from 'C:\Users\LG-20\AppData\Local\Android\Sdk\platform-tools\adb.exe'
[09a9d0fe][ADB] Running 'C:\Users\LG-20\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 start-server'
[09a9d0fe][38;5;-57m[AndroidUiautomator2Driver@1f6e] Retrieving device list
[09a9d0fe][ADB] Trying to find connected Android devices
[09a9d0fe][ADB] Getting connected devices
[09a9d0fe][ADB] Connected devices: [{"udid":"emulator-5554","state":"device"}]
[09a9d0fe][38;5;-57m[AndroidUiautomator2Driver@1f6e] Using device: emulator-5554
[09a9d0fe][ADB] Using 'adb.exe' from 'C:\Users\LG-20\AppData\Local\Android\Sdk\platform-tools\adb.exe'
[09a9d0fe][ADB] Running 'C:\Users\LG-20\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 start-server'
[09a9d0fe][ADB] Setting device id to emulator-5554
[09a9d0fe][BaseDriver] Using local app 'C:\Users\LG-20\IdeaProjects\MyCo\src\test\resources\apkfiles\MyCo1.apk'
[09a9d0fe][38;5;-57m[AndroidUiautomator2Driver@1f6e] Checking whether app is actually present
[09a9d0fe][ADB] Running 'C:\Users\LG-20\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.sdk'
[09a9d0fe][ADB] Current device property 'ro.build.version.sdk': 33
[09a9d0fe][ADB] Getting device platform version
[09a9d0fe][ADB] Running 'C:\Users\LG-20\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.release'
[09a9d0fe][ADB] Current device property 'ro.build.version.release': 13
[09a9d0fe][ADB] Device API level: 33
[09a9d0fe][38;5;-57m[AndroidUiautomator2Driver@1f6e] Relaxing hidden api policy
[09a9d0fe][ADB] Running 'C:\Users\LG-20\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell 'settings put global hidden_api_policy_pre_p_apps 1;settings put global hidden_api_policy_p_apps 1;settings put global hidden_api_policy 1''
[09a9d0fe][38;5;-57m[AndroidUiautomator2Driver@1f6e] Parsing package and activity from app manifest
[09a9d0fe][ADB] Running 'C:\Users\LG-20\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 wait-for-device'
[09a9d0fe][ADB] Error: end of central directory record signature not found
    at C:\Users\LG-20\.appium\node_modules\appium-uiautomator2-driver\node_modules\@devicefarmer\adbkit-apkreader\node_modules\yauzl\index.js:187:14
    at Immediate._onImmediate (C:\Users\LG-20\.appium\node_modules\appium-uiautomator2-driver\node_modules\@devicefarmer\adbkit-apkreader\node_modules\yauzl\index.js:624:38)
    at processImmediate (node:internal/timers:478:21)
    at process.callbackTrampoline (node:internal/async_hooks:130:17)
 OperationalError: end of central directory record signature not found
    at C:\Users\LG-20\.appium\node_modules\appium-uiautomator2-driver\node_modules\@devicefarmer\adbkit-apkreader\node_modules\yauzl\index.js:187:14
    ... 2 lines matching cause stack trace ...
    at process.callbackTrampoline (node:internal/async_hooks:130:17) {
  cause: Error: end of central directory record signature not found
      at C:\Users\LG-20\.appium\node_modules\appium-uiautomator2-driver\node_modules\@devicefarmer\adbkit-apkreader\node_modules\yauzl\index.js:187:14
      at Immediate._onImmediate (C:\Users\LG-20\.appium\node_modules\appium-uiautomator2-driver\node_modules\@devicefarmer\adbkit-apkreader\node_modules\yauzl\index.js:624:38)
      at processImmediate (node:internal/timers:478:21)
      at process.callbackTrampoline (node:internal/async_hooks:130:17),
  isOperational: true
}
[09a9d0fe][38;5;-57m[AndroidUiautomator2Driver@1f6e] Deleting UiAutomator2 session
[09a9d0fe][ADB] Running 'C:\Users\LG-20\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys activity services io.appium.settings/.recorder.RecorderService'
[09a9d0fe][ADB] Running 'C:\Users\LG-20\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell echo ping'
[09a9d0fe][38;5;-57m[AndroidUiautomator2Driver@1f6e] Restoring hidden api policy to the device default configuration
[09a9d0fe][ADB] Running 'C:\Users\LG-20\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy''
[09a9d0fe][38;5;-57m[AndroidUiautomator2Driver@1f6e] Pushing settings apk to the device...
[09a9d0fe][ADB] Getting package info for 'io.appium.settings'
[09a9d0fe][ADB] Running 'C:\Users\LG-20\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys package io.appium.settings'
[09a9d0fe][ADB] The version name of the installed 'io.appium.settings' is greater or equal to the application version name ('5.12.4' >= '5.12.4')
[09a9d0fe][ADB] There is no need to install/upgrade 'C:\Users\LG-20\.appium\node_modules\appium-uiautomator2-driver\node_modules\io.appium.settings\apks\settings_apk-debug.apk'
[09a9d0fe][ADB] Running 'C:\Users\LG-20\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys activity services io.appium.settings'
[09a9d0fe][AppiumDriver@5867] Event 'newSessionStarted' logged at 1720593690347 (12:11:30 GMT+0530 (India Standard Time))
[09a9d0fe][AppiumDriver@5867] Encountered internal error running command: Error: Cannot extract a manifest from 'C:\Users\LG-20\IdeaProjects\MyCo\src\test\resources\apkfiles\MyCo1.apk'. Is it a valid Android application?
    at ADB.packageAndLaunchActivityFromManifest (C:\Users\LG-20\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-adb\lib\tools\android-manifest.js:40:11)
    at AndroidUiautomator2Driver.getLaunchInfo (C:\Users\LG-20\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-android-driver\lib\commands\device\common.js:164:37)
    at C:\Users\LG-20\.appium\node_modules\appium-uiautomator2-driver\lib\driver.ts:572:17
[09a9d0fe][HTTP] <-- POST /wd/hub/session 500 637 ms - 862 
[09a9d0fe][38;5;-57m[AndroidUiautomator2Driver@1f6e] io.appium.settings is already running. There is no need to reset its permissions.
[09a9d0fe][Logcat] Starting logs capture with command: C:\\Users\\LG-20\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 logcat -v threadtime
App is not run:Could not start a new session. Response code 500. Message: An unknown server-side error occurred while processing the command. Original error: Cannot extract a manifest from 'C:\Users\LG-20\IdeaProjects\MyCo\src\test\resources\apkfiles\MyCo1.apk'. Is it a valid Android application? 
Host info: host: 'DESKTOP-G1FPPEV', ip: '192.168.1.150'
Build info: version: '4.22.0', revision: 'c5f3146703*'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.22'
Driver info: io.appium.java_client.android.AndroidDriver
Command: [null, newSession {capabilities=[Capabilities {appium:allowTestPackages: true, appium:app: C:\Users\LG-20\IdeaProjects..., appium:automationName: UIAutomator2, appium:deviceName: sdk_gphone64_x86_64, appium:ignoreHiddenApiPolicyError: true, appium:noReset: true, appium:platformVersion: 13, appium:udid: emulator-5554, platformName: ANDROID}]}]
Capabilities {appium:allowTestPackages: true, appium:app: C:\Users\LG-20\IdeaProjects..., appium:automationName: UIAutomator2, appium:deviceName: sdk_gphone64_x86_64, appium:ignoreHiddenApiPolicyError: true, appium:noReset: true, appium:platformVersion: 13, appium:udid: emulator-5554, platformName: ANDROID}
**org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: An unknown server-side error occurred while processing the command. Original error: Cannot extract a manifest from 'C:\Users\LG-20\IdeaProjects\MyCo\src\test\resources\apkfiles\MyCo1.apk'. Is it a valid Android application? 
Host info: host: 'DESKTOP-G1FPPEV', ip: '192.168.1.150'**

### Expected Behavior

Release apk should open

### Minimal Reproducible Example

[Appium] Welcome to Appium v2.11.1
[Appium] Non-default server args:
[Appium] { address: '127.0.0.1', basePath: '/wd/hub/', port: 44102, sessionOverride: true }
[Appium] The autodetected Appium home path: C:\Users\LG-20\.appium
[Appium] Attempting to load driver uiautomator2...
[Appium] Requiring driver at C:\Users\LG-20\.appium\node_modules\appium-uiautomator2-driver\build\index.js
[Appium] AndroidUiautomator2Driver has been successfully loaded in 1.393s
[Appium] Appium REST http interface listener started on http://127.0.0.1:44102/wd/hub
[Appium] Available drivers:
[Appium]   - uiautomator2@3.7.1 (automationName 'UiAutomator2')
[Appium] Available plugins:
[Appium]   - execute-driver@3.0.31
[Appium]   - relaxed-caps@1.0.6
[Appium]   - images@3.0.16
[Appium]   - universal-xml@1.0.20
[Appium] No plugins activated. Use the --use-plugins flag with names of plugins to activate
[HTTP] --> GET /wd/hub/status {}
[AppiumDriver@5867] Calling AppiumDriver.getStatus() with args: []
[AppiumDriver@5867] Responding to client with driver.getStatus() result: {"ready":true,"message":"The server is ready to accept new connections","build":{"version":"2.11.1"}}
[HTTP] <-- GET /wd/hub/status 200 8 ms - 111 
Appium server started
Platform Name:Android
Product Verisom:13
Device UDID:emulator-5554
Model Number:sdk_gphone64_x86_64
Build Version:33
[HTTP] --> GET /wd/hub/status {}
[AppiumDriver@5867] Calling AppiumDriver.getStatus() with args: []
[AppiumDriver@5867] Responding to client with driver.getStatus() result: {"ready":true,"message":"The server is ready to accept new connections","build":{"version":"2.11.1"}}
[HTTP] <-- GET /wd/hub/status 200 1 ms - 111 
[HTTP] Request idempotency key: a8c09404-1696-484e-9617-3d7e07ee15f8
[HTTP] --> POST /wd/hub/session {"capabilities":{"firstMatch":[{"appium:noReset":true,"appium:udid":"emulator-5554","appium:ignoreHiddenApiPolicyError":true,"appium:allowTestPackages":true,"appium:deviceName":"sdk_gphone64_x86_64","platformName":"ANDROID","appium:automationName":"UIAutomator2","appium:app":"C:\\Users\\LG-20\\IdeaProjects\\MyCo\\src\\test\\resources\\apkfiles\\MyCo1.apk","appium:platformVersion":"13"}]}}
[AppiumDriver@5867] Calling AppiumDriver.createSession() with args: [null,null,{"firstMatch":[{"appium:noReset":true,"appium:udid":"emulator-5554","appium:ignoreHiddenApiPolicyError":true,"appium:allowTestPackages":true,"appium:deviceName":"sdk_gphone64_x86_64","platformName":"ANDROID","appium:automationName":"UIAutomator2","appium:app":"C:\\Users\\LG-20\\IdeaProjects\\MyCo\\src\\test\\resources\\apkfiles\\MyCo1.apk","appium:platformVersion":"13"}]}]
[AppiumDriver@5867] Event 'newSessionRequested' logged at 1720593689728 (12:11:29 GMT+0530 (India Standard Time))
[Appium] Attempting to find matching driver for automationName 'UIAutomator2' and platformName 'ANDROID'
[Appium] The 'uiautomator2' driver was installed and matched caps.
[Appium] Will require it at C:\Users\LG-20\.appium\node_modules\appium-uiautomator2-driver
[Appium] Requiring driver at C:\Users\LG-20\.appium\node_modules\appium-uiautomator2-driver\build\index.js
[AppiumDriver@5867] Appium v2.11.1 creating new AndroidUiautomator2Driver (v3.7.1) session
[AppiumDriver@5867] Checking BaseDriver versions for Appium and AndroidUiautomator2Driver
[AppiumDriver@5867] Appium's BaseDriver version is 9.11.1
[AppiumDriver@5867] AndroidUiautomator2Driver's BaseDriver version is 9.11.1
[AppiumDriver@5867] There are no active sessions for cleanup
[38;5;-57m[AndroidUiautomator2Driver@1f6e] undefined
[38;5;-57m[AndroidUiautomator2Driver@1f6e] Creating session with W3C capabilities: {
  "alwaysMatch": {
    "platformName": "ANDROID",
    "appium:noReset": true,
    "appium:udid": "emulator-5554",
    "appium:ignoreHiddenApiPolicyError": true,
    "appium:allowTestPackages": true,
    "appium:deviceName": "sdk_gphone64_x86_64",
    "appium:automationName": "UIAutomator2",
    "appium:app": "C:\\Users\\LG-20\\IdeaProjects\\MyCo\\src\\test\\resources\\apkfiles\\MyCo1.apk",
    "appium:platformVersion": "13"
  },
  "firstMatch": [
    {}
  ]
}
[09a9d0fe][38;5;-57m[AndroidUiautomator2Driver@1f6e] Session created with session id: 09a9d0fe-0789-4833-8df9-b7e053296380
[09a9d0fe][ADB] Found 2 'build-tools' folders under 'C:\Users\LG-20\AppData\Local\Android\Sdk' (newest first):
[09a9d0fe][ADB]     C:\Users\LG-20\AppData\Local\Android\Sdk\build-tools\35.0.0
[09a9d0fe][ADB]     C:\Users\LG-20\AppData\Local\Android\Sdk\build-tools\34.0.0
[09a9d0fe][ADB] Using 'adb.exe' from 'C:\Users\LG-20\AppData\Local\Android\Sdk\platform-tools\adb.exe'
[09a9d0fe][ADB] Running 'C:\Users\LG-20\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 start-server'
[09a9d0fe][38;5;-57m[AndroidUiautomator2Driver@1f6e] Retrieving device list
[09a9d0fe][ADB] Trying to find connected Android devices
[09a9d0fe][ADB] Getting connected devices
[09a9d0fe][ADB] Connected devices: [{"udid":"emulator-5554","state":"device"}]
[09a9d0fe][38;5;-57m[AndroidUiautomator2Driver@1f6e] Using device: emulator-5554
[09a9d0fe][ADB] Using 'adb.exe' from 'C:\Users\LG-20\AppData\Local\Android\Sdk\platform-tools\adb.exe'
[09a9d0fe][ADB] Running 'C:\Users\LG-20\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 start-server'
[09a9d0fe][ADB] Setting device id to emulator-5554
[09a9d0fe][BaseDriver] Using local app 'C:\Users\LG-20\IdeaProjects\MyCo\src\test\resources\apkfiles\MyCo1.apk'
[09a9d0fe][38;5;-57m[AndroidUiautomator2Driver@1f6e] Checking whether app is actually present
[09a9d0fe][ADB] Running 'C:\Users\LG-20\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.sdk'
[09a9d0fe][ADB] Current device property 'ro.build.version.sdk': 33
[09a9d0fe][ADB] Getting device platform version
[09a9d0fe][ADB] Running 'C:\Users\LG-20\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.release'
[09a9d0fe][ADB] Current device property 'ro.build.version.release': 13
[09a9d0fe][ADB] Device API level: 33
[09a9d0fe][38;5;-57m[AndroidUiautomator2Driver@1f6e] Relaxing hidden api policy
[09a9d0fe][ADB] Running 'C:\Users\LG-20\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell 'settings put global hidden_api_policy_pre_p_apps 1;settings put global hidden_api_policy_p_apps 1;settings put global hidden_api_policy 1''
[09a9d0fe][38;5;-57m[AndroidUiautomator2Driver@1f6e] Parsing package and activity from app manifest
[09a9d0fe][ADB] Running 'C:\Users\LG-20\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 wait-for-device'
[09a9d0fe][ADB] Error: end of central directory record signature not found
    at C:\Users\LG-20\.appium\node_modules\appium-uiautomator2-driver\node_modules\@devicefarmer\adbkit-apkreader\node_modules\yauzl\index.js:187:14
    at Immediate._onImmediate (C:\Users\LG-20\.appium\node_modules\appium-uiautomator2-driver\node_modules\@devicefarmer\adbkit-apkreader\node_modules\yauzl\index.js:624:38)
    at processImmediate (node:internal/timers:478:21)
    at process.callbackTrampoline (node:internal/async_hooks:130:17)
 OperationalError: end of central directory record signature not found
    at C:\Users\LG-20\.appium\node_modules\appium-uiautomator2-driver\node_modules\@devicefarmer\adbkit-apkreader\node_modules\yauzl\index.js:187:14
    ... 2 lines matching cause stack trace ...
    at process.callbackTrampoline (node:internal/async_hooks:130:17) {
  cause: Error: end of central directory record signature not found
      at C:\Users\LG-20\.appium\node_modules\appium-uiautomator2-driver\node_modules\@devicefarmer\adbkit-apkreader\node_modules\yauzl\index.js:187:14
      at Immediate._onImmediate (C:\Users\LG-20\.appium\node_modules\appium-uiautomator2-driver\node_modules\@devicefarmer\adbkit-apkreader\node_modules\yauzl\index.js:624:38)
      at processImmediate (node:internal/timers:478:21)
      at process.callbackTrampoline (node:internal/async_hooks:130:17),
  isOperational: true
}
[09a9d0fe][38;5;-57m[AndroidUiautomator2Driver@1f6e] Deleting UiAutomator2 session
[09a9d0fe][ADB] Running 'C:\Users\LG-20\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys activity services io.appium.settings/.recorder.RecorderService'
[09a9d0fe][ADB] Running 'C:\Users\LG-20\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell echo ping'
[09a9d0fe][38;5;-57m[AndroidUiautomator2Driver@1f6e] Restoring hidden api policy to the device default configuration
[09a9d0fe][ADB] Running 'C:\Users\LG-20\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy''
[09a9d0fe][38;5;-57m[AndroidUiautomator2Driver@1f6e] Pushing settings apk to the device...
[09a9d0fe][ADB] Getting package info for 'io.appium.settings'
[09a9d0fe][ADB] Running 'C:\Users\LG-20\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys package io.appium.settings'
[09a9d0fe][ADB] The version name of the installed 'io.appium.settings' is greater or equal to the application version name ('5.12.4' >= '5.12.4')
[09a9d0fe][ADB] There is no need to install/upgrade 'C:\Users\LG-20\.appium\node_modules\appium-uiautomator2-driver\node_modules\io.appium.settings\apks\settings_apk-debug.apk'
[09a9d0fe][ADB] Running 'C:\Users\LG-20\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys activity services io.appium.settings'
[09a9d0fe][AppiumDriver@5867] Event 'newSessionStarted' logged at 1720593690347 (12:11:30 GMT+0530 (India Standard Time))
[09a9d0fe][AppiumDriver@5867] Encountered internal error running command: Error: Cannot extract a manifest from 'C:\Users\LG-20\IdeaProjects\MyCo\src\test\resources\apkfiles\MyCo1.apk'. Is it a valid Android application?
    at ADB.packageAndLaunchActivityFromManifest (C:\Users\LG-20\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-adb\lib\tools\android-manifest.js:40:11)
    at AndroidUiautomator2Driver.getLaunchInfo (C:\Users\LG-20\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-android-driver\lib\commands\device\common.js:164:37)
    at C:\Users\LG-20\.appium\node_modules\appium-uiautomator2-driver\lib\driver.ts:572:17
[09a9d0fe][HTTP] <-- POST /wd/hub/session 500 637 ms - 862 
[09a9d0fe][38;5;-57m[AndroidUiautomator2Driver@1f6e] io.appium.settings is already running. There is no need to reset its permissions.
[09a9d0fe][Logcat] Starting logs capture with command: C:\\Users\\LG-20\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 logcat -v threadtime
App is not run:Could not start a new session. Response code 500. Message: An unknown server-side error occurred while processing the command. Original error: Cannot extract a manifest from 'C:\Users\LG-20\IdeaProjects\MyCo\src\test\resources\apkfiles\MyCo1.apk'. Is it a valid Android application? 
Host info: host: 'DESKTOP-G1FPPEV', ip: '192.168.1.150'
Build info: version: '4.22.0', revision: 'c5f3146703*'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.22'
Driver info: io.appium.java_client.android.AndroidDriver
Command: [null, newSession {capabilities=[Capabilities {appium:allowTestPackages: true, appium:app: C:\Users\LG-20\IdeaProjects..., appium:automationName: UIAutomator2, appium:deviceName: sdk_gphone64_x86_64, appium:ignoreHiddenApiPolicyError: true, appium:noReset: true, appium:platformVersion: 13, appium:udid: emulator-5554, platformName: ANDROID}]}]
Capabilities {appium:allowTestPackages: true, appium:app: C:\Users\LG-20\IdeaProjects..., appium:automationName: UIAutomator2, appium:deviceName: sdk_gphone64_x86_64, appium:ignoreHiddenApiPolicyError: true, appium:noReset: true, appium:platformVersion: 13, appium:udid: emulator-5554, platformName: ANDROID}
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: An unknown server-side error occurred while processing the command. Original error: Cannot extract a manifest from 'C:\Users\LG-20\IdeaProjects\MyCo\src\test\resources\apkfiles\MyCo1.apk'. Is it a valid Android application? 
Host info: host: 'DESKTOP-G1FPPEV', ip: '192.168.1.150'

### Environment

- Operating system:
- Appium server version (9.2.3`):
- Node.js version (output of `node --`):
- `npm` version (v20.15.0`):
- Last component(s) version which did _not_ exhibit the problem: not exhibit in debug apk
- emulator: Android 13 13.0 (T) - API 33

### Further Information

org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: An unknown server-side error occurred while processing the command. Original error: Cannot extract a manifest from 'C:\Users\LG-20\IdeaProjects\MyCo\src\test\resources\apkfiles\MyCo1.apk'. Is it a valid Android application? 
Host info: host: 'DESKTOP-G1FPPEV', ip: '192.168.1.150'

**Comment by mykola-mokhnach** [comment]
Are you sure the provided .apk is not corrupted? Have you tried to install it manually using adb?

**Comment by Achalkumartrivedi** [comment]
yes it is not corrupted

**Comment by mykola-mokhnach** [comment]
> yes it is not corrupted

How did you verify it?

**Comment by Achalkumartrivedi** [comment]
> > yes it is not corrupted
> 
> How did you verify it?

it is used for manual testing ,and same debug version has not issue at all
