### ISSUE TITLE
 Locator Strategy 'xpath,//XCUIElementTypeButton[@width="41"]' is not supported for this session

### ISSUE THREAD

**Issue by samsul-kabir-cihub** [appium/appium#20360]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I am trying to locate element using find_elements(locator), then I am getting this issue.

### Expected Behavior

find_elements(locator) should return list of element

### Minimal Reproducible Example

I am using appium + selenium + python to automation mac os desktop application. I am trying to get list of element in a page. My code is given below:

Base class
```
class BasePage:

    def __init__(self, driver):
        self.driver = driver
        self.time_to_wait = 30

    def get_element_count(self, by_locator):
        elem = self.driver.find_elements(by_locator)
        return len(elem)
```

Page class
```
class ConnectionPage(BasePage):
       PLUS_ICON_TO_ADD_CONNECTION_loc = (AppiumBy.XPATH, '//XCUIElementTypeButton[@width="41"]')
       
       def __init__(self, driver):
          super().__init__(driver)
          self.driver = driver


        def get_total_item_in_search_result(self):
            time.sleep(2)
            count = self.get_element_count(self.PLUS_ICON_TO_ADD_CONNECTION_loc)
            print("Total item in list: " + str(count))
            assert count == 1
```

Step class
```
@then(u'User see connection appear in the list')
def step_impl(context):
    context.drive_connection.get_total_item_in_search_result()

```

Error log:
```
'11:13:25 - selenium.webdriver.remote.remote_connection - DEBUG - Finished Request'
'11:13:25 - selenium.webdriver.remote.remote_connection - DEBUG - POST http://localhost:56279/session/c46a68762b199b376504aba2b213c068/timeouts {'implicit': 10000}'
'11:13:25 - urllib3.connectionpool - DEBUG - http://localhost:56279 "POST /session/c46a68762b199b376504aba2b213c068/timeouts HTTP/11" 200 0'
'11:13:25 - selenium.webdriver.remote.remote_connection - DEBUG - Remote response: status=200 | data={"value":null} | headers=HTTPHeaderDict({'Content-Length': '14', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})'
'11:13:25 - selenium.webdriver.remote.remote_connection - DEBUG - Finished Request'
'11:13:32 - root - ERROR - Message: Locator Strategy 'xpath,//XCUIElementTypeButton[@width="41"]' is not supported for this session; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalid-selector-exception
Stacktrace:
InvalidSelectorError: Locator Strategy 'xpath,//XCUIElementTypeButton[@width="41"]' is not supported for this session
    at Mac2Driver.validateLocatorStrategy (/usr/local/opt/brew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/core.ts:318:13)
    at Mac2Driver.findElOrElsWithProcessing (/usr/local/opt/brew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:57:8)
    at Mac2Driver.findElements (/usr/local/opt/brew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:79:23)
    at commandExecutor (/usr/local/opt/brew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.ts:106:18)
    at /usr/local/opt/brew/lib/node_modules/appium/node_modules/async-lock/lib/index.js:171:12
    at AsyncLock._promiseTry (/usr/local/opt/brew/lib/node_modules/appium/node_modules/async-lock/lib/index.js:306:31)
    at exec (/usr/local/opt/brew/lib/node_modules/appium/node_modules/async-lock/lib/index.js:170:9)
    at AsyncLock.acquire (/usr/local/opt/brew/lib/node_modules/appium/node_modules/async-lock/lib/index.js:189:3)
    at Mac2Driver.executeCommand (/usr/local/opt/brew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.ts:122:39)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at defaultBehavior (/usr/local/opt/brew/lib/node_modules/appium/lib/appium.js:1123:14)
    at AppiumDriver.executeWrappedCommand (/usr/local/opt/brew/lib/node_modules/appium/lib/appium.js:1229:16)
    at AppiumDriver.executeCommand (/usr/local/opt/brew/lib/node_modules/appium/lib/appium.js:1135:17)
    at asyncHandler (/usr/local/opt/brew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:387:19)'
'11:13:32 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106123080>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/c46a68762b199b376504aba2b213c068/window'
'11:13:32 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106123320>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/c46a68762b199b376504aba2b213c068/window'
'11:13:32 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106123800>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/c46a68762b199b376504aba2b213c068/window'
HOOK-ERROR in after_all: MaxRetryError: HTTPConnectionPool(host='localhost', port=56279): Max retries exceeded with url: /session/c46a68762b199b376504aba2b213c068/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1061239b0>: Failed to establish a new connection: [Errno 61] Connection refused'))

ABORTED: By user.
```

Appium Server log:
```
[8cc5ae78][WD Proxy] Got response with status 200: {"value":null,"sessionId":"534C0BEF-0D40-43D6-9203-7E9000C451A3"}
[8cc5ae78][WD Proxy] Replacing sessionId 534C0BEF-0D40-43D6-9203-7E9000C451A3 with 8cc5ae78-0586-45b9-a911-f29e62d2de03
[8cc5ae78][HTTP] <-- POST /session/8cc5ae78-0586-45b9-a911-f29e62d2de03/element/24F63B45-5E58-450C-9A94-CB880F475564/value 200 340 ms - 65
[8cc5ae78][HTTP] --> POST /session/8cc5ae78-0586-45b9-a911-f29e62d2de03/elements {"using":["xpath","//XCUIElementTypeButton[@width=\"41\"]"],"value":null}
[8cc5ae78][Mac2Driver@c589] Calling AppiumDriver.findElements() with args: [["xpath","//XCUIElementTypeButton[@width=\"41\"]"],null,"8cc5ae78-0586-45b9-a911-f29e62d2de03"]
[8cc5ae78][Mac2Driver@c589] Valid locator strategies for this request: id, name, accessibility id, xpath, class name, -ios predicate string, predicate string, -ios class chain, class chain
[8cc5ae78][Mac2Driver@c589] Encountered internal error running command: InvalidSelectorError: Locator Strategy 'xpath,//XCUIElementTypeButton[@width="41"]' is not supported for this session
    at Mac2Driver.validateLocatorStrategy (/usr/local/opt/brew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/core.ts:318:13)
    at Mac2Driver.findElOrElsWithProcessing (/usr/local/opt/brew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:57:8)
    at Mac2Driver.findElements (/usr/local/opt/brew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:79:23)
    at commandExecutor (/usr/local/opt/brew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.ts:106:18)
    at /usr/local/opt/brew/lib/node_modules/appium/node_modules/async-lock/lib/index.js:171:12
    at AsyncLock._promiseTry (/usr/local/opt/brew/lib/node_modules/appium/node_modules/async-lock/lib/index.js:306:31)
    at exec (/usr/local/opt/brew/lib/node_modules/appium/node_modules/async-lock/lib/index.js:170:9)
    at AsyncLock.acquire (/usr/local/opt/brew/lib/node_modules/appium/node_modules/async-lock/lib/index.js:189:3)
    at Mac2Driver.executeCommand (/usr/local/opt/brew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.ts:122:39)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at defaultBehavior (/usr/local/opt/brew/lib/node_modules/appium/lib/appium.js:1123:14)
    at AppiumDriver.executeWrappedCommand (/usr/local/opt/brew/lib/node_modules/appium/lib/appium.js:1229:16)
    at AppiumDriver.executeCommand (/usr/local/opt/brew/lib/node_modules/appium/lib/appium.js:1135:17)
    at asyncHandler (/usr/local/opt/brew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:387:19)
[8cc5ae78][HTTP] <-- POST /session/8cc5ae78-0586-45b9-a911-f29e62d2de03/elements 400 16 ms - 1972
```

Any help would be much appreciated. Thank you.

### Environment

- Operating system:
Mac OS X 14.5
- Appium server version (output of `appium --version`): 
2.10.3

- Appium driver(s) and their version(s) (`appium driver list`):
espresso@2.38.3 [installed (npm)]
xcuitest@7.15.1 [installed (npm)]
chromium@1.3.26 [installed (npm)]
uiautomator2@3.2.0 [installed (npm)]
safari@3.5.12 [installed (npm)]
gecko@1.3.3 [installed (npm)]
mac2@1.17.4 [installed (npm)]
windows [not installed]

- Appium plugin(s) and their version(s) (`appium plugin list`):
images@3.0.6 [installed (npm)]
execute-driver@3.0.28 [installed (npm)]
relaxed-caps@1.0.6 [installed (npm)]
universal-xml@1.0.18 [installed (npm)]

Node.js version (output of `node --version`):
v22.3.0
- `npm` version (output of `npm --version`):
10.8.1
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: 
- Real device or emulator/simulator: real device

**Comment by mykola-mokhnach** [comment]
the error looks valid to me. The provided locator string is invalid. Most likely there is a syntax error in the client script

**Comment by samsul-kabir-cihub** [comment]
@mykola-mokhnach The locator works fine when I am clicking on it. So the locator is working fine.

For your convenience, I am attaching xml document. You can run the following query for the xpath:
`xmllint --xpath '//XCUIElementTypeButton[@width="41"]' /Users/samsul/Documents/Development/appiumForMac/psc_click_add_connection.xml`

Please rename the file and change the extension to `xml`

[psc_click_add_connection.txt](https://github.com/user-attachments/files/16158955/psc_click_add_connection.txt)

**Comment by mykola-mokhnach** [comment]
> [8cc5ae78][HTTP] --> POST /session/8cc5ae78-0586-45b9-a911-f29e62d2de03/elements {"using":["xpath","//XCUIElementTypeButton[@width=\"41\"]"],"value":null}
> [8cc5ae78][Mac2Driver@c589] Calling AppiumDriver.findElements() with args: [["xpath","//XCUIElementTypeButton[@width=\"41\"]"],null,"8cc5ae78-0586-45b9-a911-f29e62d2de03"]
> [8cc5ae78][Mac2Driver@c589] Valid locator strategies for this request: id, name, accessibility id, xpath, class name, -ios predicate string, predicate string, -ios class chain, class chain
> [8cc5ae78][Mac2Driver@c589] Encountered internal error running command: InvalidSelectorError: Locator Strategy 'xpath,//XCUIElementTypeButton[@width="41"]' is not supported for this session

Sorry, I don't know much about the details of the used technology, you'd probably ask at their support forum. The server exception above just states the HTTP request payload to find the element is wrong and this payload is compiled by the client lib.

**Comment by samsul-kabir-cihub** [comment]
okay. I am quite sure that locator is correct and content is there. What could be the other reason to have such error? if this is not a bug, please give me some clue if I am missing something.

**Comment by eglitise** [comment]
I believe your syntax is incorrect. You are defining a tuple here:
```
PLUS_ICON_TO_ADD_CONNECTION_loc = (AppiumBy.XPATH, '//XCUIElementTypeButton[@width="41"]')
```
But `find_elements` expects two parameters.
A simple fix would be to extract the tuple items using indices:
```
elem = self.driver.find_elements(by_locator[0], by_locator[1])
```
A slightly better fix would be to also specify which value is used for which parameter:
```
elem = self.driver.find_elements(by=by_locator[0], value=by_locator[1])
```

**Comment by samsul-kabir** [comment]
@eglitise That indeed solved my problem. Thanks a lot
