### ISSUE TITLE
Original error: socket hang up    Cannot invoke method android.app.UiAutomation androidx.test.uiautomator.UiDevice.getUiAutomation() on object androidx.test.uiautomator.UiDevice@578ff17 with parameters []

### ISSUE THREAD

**Issue by printf172** [appium/appium#20394]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

同时间多次执行任务可以复现  selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up

Stacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up\n    at UIA2Proxy.command (/Users/mac/.nvm/versions/node/v18.20.3/lib/node_modules/appium/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:355:13)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at AndroidUiautomator2Driver.getWindowSize (/Users/mac/.appium/node_modules/appium-uiautomator2-driver/lib/commands/viewport.js:90:5)\n    at AndroidUiautomator2Driver.getWindowRect (/Users/mac/.appium/node_modules/appium-uiautomator2-driver/lib/commands/viewport.js:61:27)\n'}}[39m       Nest] 84479 - 2024/07/17 13:29:03    ERROR: [global]: [2024-07-17 13:29:03,239][xhs_task][ERROR][task.py][357 line] 设备b9cde5ea:任务执行失败, Exception = Traceback (most recent call last):
  File "task/task.py", line 254, in <module>
    driver = init_driver_android_with_retry(device_udid, device_port, system_port, 'xhs')
  File "/Users/sunhuaxiao/Documents/workspace/skywheel/skywheel-python-job-b9cde5ea/src/task/android_driver.py", line 81, in init_driver_android_with_retry
    return retry_action_when_except(
  File "/Users/sunhuaxiao/Documents/workspace/skywheel/skywheel-python-job-b9cde5ea/src/util/exception_utils.py", line 20, in retry_action_when_except
    raise e
  File "/Users/sunhuaxiao/Documents/workspace/skywheel/skywheel-python-job-b9cde5ea/src/util/exception_utils.py", line 17, in retry_action_when_except
    return action()
  File "/Users/sunhuaxiao/Documents/workspace/skywheel/skywheel-python-job-b9cde5ea/src/task/android_driver.py", line 82, in <lambda>
    lambda: init_driver_android(device_udid, device_port, system_port, type, with_chrome_driver)
  File "/Users/sunhuaxiao/Documents/workspace/skywheel/skywheel-python-job-b9cde5ea/src/task/android_driver.py", line 74, in init_driver_android
    driver = webdriver.Remote(f'http://127.0.0.1:{device_port}/wd/hub', options)
  File "/Users/sunhuaxiao/.pyenv/versions/v3812env/lib/python3.8/site-packages/appium/webdriver/webdriver.py", line 257, in __init__
    super().__init__(
  File "/Users/sunhuaxiao/.pyenv/versions/v3812env/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 212, in __init__
    self.start_session(capabilities)
  File "/Users/sunhuaxiao/.pyenv/versions/v3812env/lib/python3.8/site-packages/appium/webdriver/webdriver.py", line 346, in start_session
    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)
  File "/Users/sunhuaxiao/.pyenv/versions/v3812env/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/Users/sunhuaxiao/.pyenv/versions/v3812env/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: A new session could not be created. Details: io.appium.uiautomator2.common.exceptions.UiAutomator2Exception: Cannot invoke method android.app.UiAutomation androidx.test.uiautomator.UiDevice.getUiAutomation() on object androidx.test.uiautomator.UiDevice@578ff17 with parameters []
Stacktrace:
io.appium.uiautomator2.common.exceptions.SessionNotCreatedException: io.appium.uiautomator2.common.exceptions.UiAutomator2Exception: Cannot invoke method android.app.UiAutomation androidx.test.uiautomator.UiDevice.getUiAutomation() on object androidx.test.uiautomator.UiDevice@578ff17 with parameters []
	at io.appium.uiautomator2.handler.NewSession.safeHandle(NewSession.java:60)
	at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:59)
	at io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:259)
	at io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:253)
	at io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:77)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:466)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:764)
Caused by: io.appium.uiautomator2.common.exceptions.UiAutomator2Exception: Cannot invoke method android.app.UiAutomation androidx.test.uiautomator.UiDevice.getUiAutomation() on object androidx.test.uiautomator.UiDevice@578ff17 with parameters []
	at io.appium.uiautomator2.utils.ReflectionUtils.invoke(ReflectionUtils.java:85)
	at io.appium.uiautomator2.core.UiAutomatorBridge.getUiAutomation(UiAutomatorBridge.java:57)
	at io.appium.uiautomator2.core.UiAutomation.<init>(UiAutomation.java:32)
	at io.appium.uiautomator2.core.UiAutomation.getInstance(UiAutomation.java:37)
	at io.appium.uiautomator2.model.NotificationListener.<init>(NotificationListener.java:43)
	at io.appium.uiautomator2.model.NotificationListener.getInstance(NotificationListener.java:48)
	at io.appium.uiautomator2.model.settings.EnableNotificationListener.getValue(EnableNotificationListener.java:31)
	at io.appium.uiautomator2.model.settings.EnableNotificationListener.getValue(EnableNotificationListener.java:21)
	at io.appium.uiautomator2.model.settings.AbstractSetting.reset(AbstractSetting.java:57)
	at io.appium.uiautomator2.model.settings.Settings.resetForNewSession(Settings.java:73)
	at io.appium.uiautomator2.handler.NewSession.safeHandle(NewSession.java:52)
	... 34 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at io.appium.uiautomator2.utils.ReflectionUtils.invoke(ReflectionUtils.java:83)
	... 44 more
Caused by: java.lang.IllegalStateException: UiAutomation not connected!

### Expected Behavior

群控的时候希望能更加稳定  现在只能重启手机

### Minimal Reproducible Example

暂时没

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s) (`appium driver list`):
- Appium plugin(s) and their version(s) (`appium plugin list`):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by KazuCocoa** [comment]
> Caused by: java.lang.IllegalStateException: UiAutomation not connected!

This error usually occurs in the device internal, the UiAutomation framework in Android state related. It is basically out of control by Appium.
Based on my past experience, rebooting the device or uninstalling instrument related apks such as UI2 server from device might help. Factory reset also helped before.

**Comment by printf172** [comment]
> > 原因：java.lang.IllegalStateException：UiAutomation 未连接！
> 
> 此错误通常发生在设备内部，与 Android 状态中的 UiAutomation 框架相关。它基本上不受 Appium 的控制。 根据我过去的经验，重新启动设备或从设备上卸载仪器相关的 apk（例如 UI2 服务器）可能会有所帮助。恢复出厂设置以前也有帮助。

我们现在的方案就是重启手机    但是在群控上千台或者任务量大的时候这种方式就变得非常低效   有不用重启手机的方式吗

**Comment by KazuCocoa** [comment]
Could you leave comment in English? (after translation with any app is fine)

**Comment by printf172** [comment]
> Could you leave comment in English? (after translation with any app is fine)

我们现在的方案就是重启手机 但是在群控上千台或者任务量大的时候这种方式就变得非常低效 有不用重启手机的方式吗

**Comment by printf172** [comment]
> Could you leave comment in English? (after translation with any app is fine)

Our current solution is to restart the phone, but this method becomes very inefficient when there are thousands of group controls or a large workload. Is there a way to not restart the phone

**Comment by KazuCocoa** [comment]
Thank you.

No, unfortunately. This is device internal stuff, so what we could do is that doing something after getting the error from Appium. So for example in your test code, you could issue a device reboot `adb` command to the device when your test code gets `UiAutomation not connected` error message, and sent the same new session request to the device via Appium.

**Comment by printf172** [comment]
> Thank you.
> 
> No, unfortunately. This is device internal stuff, so what we could do is that doing something after getting the error from Appium. So for example in your test code, you could issue a device reboot `adb` command to the device when your test code gets `UiAutomation not connected` error message, and sent the same new session request to the device via Appium.

Can you modify the source code of uiautomaton server to start two instances on different ports? If one fails, use the other

**Comment by KazuCocoa** [comment]
This UiAutomation in the error message is device wide's one. Two UIA2 server on the same device does not help (even if it could), if you meant running two UIA2 server.
If you have a good reproducible method, reporting it to Google would help. Reporting manufacture also potentially better than here to fix it since potentially manufacture customization also could affect system software.

**Comment by printf172** [comment]
> This UiAutomation in the error message is device wide's one. Two UIA2 server on the same device does not help (even if it could), if you meant running two UIA2 server. If you have a good reproducible method, reporting it to Google would help. Reporting manufacture also potentially better than here to fix it since potentially manufacture customization also could affect system software.

Is the internal communication of the device through uiautomator2 server? This bug should also be due to a problem with this server. If this server can start two instances, wouldn't it achieve high availability?

**Comment by KazuCocoa** [comment]
The error itself comes from https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/core/java/android/app/UiAutomation.java?q=%22UiAutomation%20not%20connected%22

Appium UIA2 server gets them via https://github.com/appium/appium-uiautomator2-server/blob/17956721dc7c82b8f61958876c1f8736ded52dfa/app/src/main/java/io/appium/uiautomator2/core/UiAutomation.java#L24-L56 's wrapper.

I assumed two instances might not helpful since when the connection issue occurred, it kept happening on the device until the device gets restarted when I saw this issue before. It means even a device has two servers, both could keep getting the same error.

If you'd like to verify it by yourself, feel free to try it out as this is OSS under a license. Perhaps modifying package name, `appium:disableSuppressAccessibilityService` (since two instances mean the device has two accessibility service apps), port stuff, and uia2 driver's uia2 server handling might be necessary.

**Comment by KazuCocoa** [comment]
I don't have such an error-wise device so can't test it out, but if the error occurs randomly without device restart, adding retry in https://github.com/appium/appium-uiautomator2-server/blob/17956721dc7c82b8f61958876c1f8736ded52dfa/app/src/main/java/io/appium/uiautomator2/core/UiAutomation.java#L24-L56 potentially helps. Then, it should be more helpful than running multiple duplicated instances on the same device.

**Comment by mykola-mokhnach** [comment]
it is impossible to run two server instances on a single device. The accessibility access is single threaded.

**Comment by printf172** [comment]
> I don't have such an error-wise device so can't test it out, but if the error occurs randomly without device restart, adding retry in https://github.com/appium/appium-uiautomator2-server/blob/17956721dc7c82b8f61958876c1f8736ded52dfa/app/src/main/java/io/appium/uiautomator2/core/UiAutomation.java#L24-L56 potentially helps. Then, it should be more helpful than running multiple duplicated instances on the same device.

thank you

**Comment by printf172** [comment]
> it is impossible to run two server instances on a single device. The accessibility access is single threaded.

Is it really necessary to restart the phone? Can changing the ROM achieve the goal of not restarting the phone

**Comment by printf172** [comment]
> it is impossible to run two server instances on a single device. The accessibility access is single threaded.

Isn't appium not dependent on accessibility services

**Comment by KazuCocoa** [comment]
uiautomation test framework itself depends on accessibility services.

**Comment by printf172** [comment]
> uiautomation test framework itself depends on accessibility services.
Why not activate accessibility services
