### ISSUE TITLE
"x is still running after 500ms timeout"

### ISSUE THREAD

**Issue by tking16** [appium/appium#20436]
I haven't seen any concrete solutions online to this issue. I have a certain test which uses `self.driver.terminate_app()` to then open a deep link. For some reason this is now failing with the following error:
```
*** selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: 'com.app.d' is still running after 500ms timeout
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: 'com.app.d' is still running after 500ms timeout
    at getResponseForW3CError (/Users/theo.king/code/guacamole/testing/app-at/node_modules/@appium/base-driver/lib/protocol/errors.js:1145:9)
    at asyncHandler (/Users/theo.king/code/guacamole/testing/app-at/node_modules/@appium/base-driver/lib/protocol/protocol.js:491:57)
```

`self.driver.terminate_app()` works fine for iOS. Am I supposed to use something else for Android?

**Comment by mykola-mokhnach** [comment]
This behaviour is expected if, for example, the system fails to terminate the given application or restarts it right after  termination. You may set the timeout value to a zero or negative value in order to skip that check.

**Comment by tking16** [comment]
Thanks, changing it to `self._driver.execute_script('mobile:terminateApp', {"appId": bundle_id, "timeout": 0})` seems to have to stopped the error
