### ISSUE TITLE
Cannot find element from element using Image plugin

### ISSUE THREAD

**Issue by MikitaKarbanovich** [appium/appium#20476]
### **Is your feature request related to a problem? Please describe.**
I cannot find element from element using image plugin

When I try to use search any element by Image inside Appium element, I receive the following error inside Appium logs:
```
 [AppiumDriver@16c0] Clearing new command timeout pre-emptively since plugin(s) will handle this command
 [AppiumDriver@16c0] Plugins which can handle cmd 'findElementFromElement': images
 [AppiumDriver@16c0] Plugin images is now handling cmd 'findElementFromElement'
 [AppiumDriver@16c0] Executing default handling behavior for command 'findElementFromElement'
 [AndroidUiautomator2Driver@6eaa (1ca9d653)] Valid locator strategies for this request: xpath, id, class name, accessibility id, css selector, -android uiautomato
```

### **Describe the solution you'd like**
I would like to have the ability to search by image inside Appium element. For example, I find a row inside some table and I want to find element using image plugin inside the necessary row. I saw the following RP https://github.com/appium/appium/pull/18555, but it does not work for me. Maybe I missed something?

### **Additional context**
Appium v2.11.3
images@3.0.3
[dotnet-client] 5.1.0

**Comment by mykola-mokhnach** [comment]
> I saw the following RP https://github.com/appium/appium/pull/18555, but it does not work for me. Maybe I missed something?

It is impossible to advice anything there without having the full log.

> I would like to have the ability to search by image inside Appium element. For example, I find a row inside some table and I want to find element using image plugin inside the necessary row

Are you sure the template matching works as expected using vanilla opencv? It is possible to configure some matching options via settings, for example the matching coefficient, but the low-level matching is still done by opencv, we cannot control it match.

**Comment by MikitaKarbanovich** [comment]
@mykola-mokhnach Hi, thank you for being included into the thread.
> It is impossible to advice anything there without having the full log.

I attached more detailed logs where you can noticed that finding on screen works properly (**I mean driver.findElement()** ), but when I tried to use **AppiumDriver.findElementFromElement()** I receive the error. 
I marked these parts. If you need additionally some specific part of logs, please specify the area of interest.

2024-08-22 14:06:05:416 - [HTTP] --> POST /session/52afc1fc-a017-4d0a-a7f6-e74d0f72ebd5/element
2024-08-22 14:06:05:416 - [HTTP] {"using":"-image","value":"iVBORw0KGgoAAAANSUhEUgAAAGsAAABrCAYAAABwv3wMAAAAAXNSR0IArs4c6QAAAARzQklUCAgICHwIZIgAABV2SURBVHic7Z1pkFxXdYC/+7bep2empRktlrFsZDDYlkEsdgiR44CRkZewuajgOEUquCpJ4UpBQSqVUEAVBGOXK2ZzVSiWQo4D3nBhygkYL8KAEYtlG8uSjC3Jlq1tlu7pmd7eevPj9Sy9TPfrnt6k6Psz02+975137zn3nHPvFVJKSRvYtk02m8WyrHZObwtVVTGMELqho6kaqqqiKApCCIQAIUTNOVJKpPT/ep6H67o4roNt2ViWieu6LZdhfHy8YpvluFy1o8CJQu39qxHATe8J855NWt39z0957JtwOZyVHMp4lBzJ+oTCWSMK9c9oQqFQYGZmpp1TW8IwDMKRCIZuoGkaitL8ZVQzL0gQqKqCrmtACGL+fs+TOI6DZVuUisWmH18oFKrZ9oOn8pwoKIHK87m/qC+oY3OS254w+ekLTp2z/A+qZWFls1ny+XyrpwUmEokSiUQxDL0t4bSKoggMQ8cwdOKxGJ4nsSybYrFAsVioOT4cDtdse/CFYI3Tp94Z4przal/5956y+cYuE6tJJQ8sLCklmUyGUqkU9JTAGIZBLJ4gZBg9EVAjFEUQDhuEwwbJZBLTssjn5rAsCyFETc06OmPyfFptet3NaxQ+slmv2X7nMzb/8SszUNkCCctxHDKZDLZtB7poUGKxONFYFF1rqzXuOooiiIRDRMIhbMfBMq0avfjIixa+JmrMtRcYNdse2O9wyy+CCQoCCMu2bdLpdMuKuBHxRIJYNIaqBmvnBwFd0+p+VDtf8oDGNSsRgsur9NScCV94rLVWqqGwLMsinU7jeV5LF12OWCxOPB4/qYTUjH1TzWvVB96oo1c98g/32k11VDXLCsuyLKanp2nTsq/AMAySyeGyJXbqYLpQcJp/ePc9Z5MuSK56vc5bzlARwF...
2024-08-22 14:06:05:417 - [AndroidUiautomator2Driver@8b9d (52afc1fc)] Calling AppiumDriver.findElement() with args: ["-image","iVBORw0KGgoAAAANSUhEUgAAAGsAAABrCAYAAABwv3wMAAAAAXNSR0IArs4c6QAAAARzQklUCAgICHwIZIgAABV2SURBVHic7Z1pkFxXdYC/+7bep2empRktlrFsZDDYlkEsdgiR44CRkZewuajgOEUquCpJ4UpBQSqVUEAVBGOXK2ZzVSiWQo4D3nBhygkYL8KAEYtlG8uSjC3Jlq1tlu7pmd7eevPj9Sy9TPfrnt6k6Psz02+975137zn3nHPvFVJKSRvYtk02m8WyrHZObwtVVTGMELqho6kaqqqiKApCCIQAIUTNOVJKpPT/ep6H67o4roNt2ViWieu6LZdhfHy8YpvluFy1o8CJQu39qxHATe8J855NWt39z0957JtwOZyVHMp4lBzJ+oTCWSMK9c9oQqFQYGZmpp1TW8IwDMKRCIZuoGkaitL8ZVQzL0gQqKqCrmtACGL+fs+TOI6DZVuUisWmH18oFKrZ9oOn8pwoKIHK87m/qC+oY3OS254w+ekLTp2z/A+qZWFls1ny+XyrpwUmEokSiUQxDL0t4bSKoggMQ8cwdOKxGJ4nsSybYrFAsVioOT4cDtdse/CFYI3Tp94Z4przal/5956y+cYuE6tJJQ8sLCklmUyGUqkU9JTAGIZBLJ4gZBg9EVAjFEUQDhuEwwbJZBLTssjn5rAsCyFETc06OmPyfFptet3NaxQ+slmv2X7nMzb/8SszUNkCCctxHDKZDLZtB7poUGKxONFYFF1rqzXuOooiiIRDRMIhbMfBMq0avfjIixa+JmrMtRcYNdse2O9wyy+CCQoCCMu2bdLpdMuKuBHxRIJYNIaqBmvnBwFd0+p+VDtf8oDGNSsRgsur9NScCV94rLVWqqGwLMsinU7jeV5LF12OWCxOPB4/qYTUjH1TzWvVB96oo1c98g/32k11VDXLCsuyLKanp2nTsq/AMAySyeGyJXbqYLpQcJp/ePc9Z5MuSK56vc5bzlARwF3Ptt7lqfv25pu+Tg...
2024-08-22 14:06:05:418 - [AppiumDriver@511e] Clearing new command timeout pre-emptively since plugin(s) will handle this command
2024-08-22 14:06:05:418 - [AppiumDriver@511e] Plugins which can handle cmd 'findElement': images
2024-08-22 14:06:05:418 - [AppiumDriver@511e] Plugin images is now handling cmd 'findElement'
2024-08-22 14:06:05:419 - [ImageElementPlugin] Finding image element with match threshold 0.4
2024-08-22 14:06:05:419 - [AndroidUiautomator2Driver@8b9d (52afc1fc)] Matched '/window/current/size' to command name 'getWindowSize'
2024-08-22 14:06:05:420 - [AndroidUiautomator2Driver@8b9d (52afc1fc)] Proxying [GET /window/current/size] to [GET http://127.0.0.1:8202/session/92b1c6bd-d936-4a19-8306-2bf507e217ef/window/current/size] with no body
2024-08-22 14:06:05:432 - [AndroidUiautomator2Driver@8b9d (52afc1fc)] Got response with status 200: {"sessionId":"92b1c6bd-d936-4a19-8306-2bf507e217ef","value":{"height":2400,"width":1080}}
2024-08-22 14:06:05:433 - [AndroidUiautomator2Driver@8b9d (52afc1fc)] Waiting up to 0 ms for condition
2024-08-22 14:06:05:434 - [AndroidUiautomator2Driver@8b9d (52afc1fc)] Matched '/screenshot' to command name 'getScreenshot'
2024-08-22 14:06:05:434 - [AndroidUiautomator2Driver@8b9d (52afc1fc)] Proxying [GET /screenshot] to [GET http://127.0.0.1:8202/session/92b1c6bd-d936-4a19-8306-2bf507e217ef/screenshot] with no body
2024-08-22 14:06:05:849 - [AndroidUiautomator2Driver@8b9d (52afc1fc)] Got response with status 200: {"sessionId":"92b1c6bd-d936-4a19-8306-2bf507e217ef","value":"iVBORw0KGgoAAAANSUhEUgAABDgAAAlgCAYAAABtGofVAAABJGlDQ1BTa2lhAAAokX2Rv0vDQBiGH0sXpQ6ig4NDxi5KVeiiLlUIOkms0OqUpmkV2houKdXZ1T+im7OjCJ27CILgJP4N4uAa37RDAqW+x3f33Mt3P747yK0j5UvQ7UXGsStWrX5hkZHrhQHztQC/H0kP75v/5M3TYtMPPY3fisjocG3ZFK+1p3ybcGPKDwmbqnMoHoqL7Qw3MjyIgkg8TvK9wCT8Kd7vdvpeem8Kfu/8TGNNsUGIg00FiyoGl56cFr7YYsA1EVeiI1FIQEcZd5qfsqve1qxLXzkzSt/z/gsORnEcv6TeyQieyrD0nHrFPVgpwPg1cI07sfKKXKsFP4+wXIfVN625nD0j/Ys5tVqTWm1u1NqqwpdzrFo9tkQ7lNim/AfUy02wCLYnZAAAAARzQklUCAgICHwIZIgAACAASURBVHic7N15XFT1/j/w15kBhmWURUUEUcHtupCaiJlLi4RaKtriTetqJVbelptm12uaafXLzFK7pZWWfsvSUnPram6oibihBSKKiGzKLqvAzDDL+f0xcpqRAQYYwNHX8z66MjPnnPmMDjDndT6f91sQRVEEEREREREREZEdk7X0AIiIiIiIiIiIGosBBxERERERERHZPQYcRERERERERGT3GHAQERERERERkd1jwEFEREREREREdo8BBxERERERERHZPQYcRERERERERGT3GHAQERERERERkd1jwEFEREREREREdo8BBxERERERERHZPQYcRERERERERGT3GHAQERERERERkd1jwEFEREREREREdo8BBxERERERERHZPQYcRERERERERGT3GHAQERERERERkd1jwEFEREREREREdo8BBxERERERERHZPQYcRERERERERGT3GHAQERERERERkd1jwEFERERERERE...
2024-08-22 14:06:05:850 - [ImageElementPlugin] Verifying screenshot size and aspect ratio
2024-08-22 14:06:05:853 - [ImageElementPlugin] Screenshot size matched screen size
2024-08-22 14:06:06:863 - [ImageElementPlugin] Image template matched: {"x":118,"y":1055,"width":107,"height":107}
2024-08-22 14:06:06:863 - [AppiumDriver@511e] Command 'findElement' was *not* handled by the following behaviours or plugins, even though they were registered to handle it: ["default"]. The command *was* handled by these: ["images"].
2024-08-22 14:06:06:863 - [AppiumDriver@511e] Restarting new command timeout via umbrella driver since plugin did not allow default handler to execute
**2024-08-22 14:06:06:863 - [AndroidUiautomator2Driver@8b9d (52afc1fc)] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"appium-image-element-28e8d66a-2d0a-4101-925b-e75e5f4a7e63","ELEMENT":"appium-image-element-28e8d66a-2d0a-4101-925b-e75e5f4a7e63"}**
2024-08-22 14:06:06:864 - [HTTP] <-- POST /session/52afc1fc-a017-4d0a-a7f6-e74d0f72ebd5/element 200 1447 ms - 179
2024-08-22 14:06:06:864 - [HTTP] 
2024-08-22 14:06:06:945 - [HTTP] --> GET /session/52afc1fc-a017-4d0a-a7f6-e74d0f72ebd5/element/00000000-0000-7b40-ffff-ffff000002e8/displayed
2024-08-22 14:06:06:945 - [HTTP] {}
2024-08-22 14:06:06:945 - [AndroidUiautomator2Driver@8b9d (52afc1fc)] Calling AppiumDriver.elementDisplayed() with args: ["00000000-0000-7b40-ffff-ffff000002e8","52afc1fc-a017-4d0a-a7f6-e74d0f72ebd5"]
2024-08-22 14:06:06:945 - [AppiumDriver@511e] Clearing new command timeout pre-emptively since plugin(s) will handle this command
2024-08-22 14:06:06:945 - [AppiumDriver@511e] Plugins which can handle cmd 'elementDisplayed': images
2024-08-22 14:06:06:945 - [AppiumDriver@511e] Plugin images is now handling cmd 'elementDisplayed'
2024-08-22 14:06:06:945 - [AppiumDriver@511e] Executing default handling behavior for command 'elementDisplayed'
2024-08-22 14:06:06:947 - [AndroidUiautomator2Driver@8b9d (52afc1fc)] Matched '/element/00000000-0000-7b40-ffff-ffff000002e8/attribute/displayed' to command name 'getAttribute'
2024-08-22 14:06:06:947 - [AndroidUiautomator2Driver@8b9d (52afc1fc)] Proxying [GET /element/00000000-0000-7b40-ffff-ffff000002e8/attribute/displayed] to [GET http://127.0.0.1:8202/session/92b1c6bd-d936-4a19-8306-2bf507e217ef/element/00000000-0000-7b40-ffff-ffff000002e8/attribute/displayed] with no body
2024-08-22 14:06:06:993 - [AndroidUiautomator2Driver@8b9d (52afc1fc)] Got response with status 200: {"sessionId":"92b1c6bd-d936-4a19-8306-2bf507e217ef","value":"true"}
2024-08-22 14:06:06:993 - [AndroidUiautomator2Driver@8b9d (52afc1fc)] Responding to client with driver.elementDisplayed() result: true
2024-08-22 14:06:06:994 - [HTTP] <-- GET /session/52afc1fc-a017-4d0a-a7f6-e74d0f72ebd5/element/00000000-0000-7b40-ffff-ffff000002e8/displayed 200 49 ms - 14
2024-08-22 14:06:06:994 - [HTTP] 
2024-08-22 14:06:07:068 - [HTTP] Request idempotency key: 86367172-2ce1-4262-9104-418eb74c76e7
**2024-08-22 14:06:07:264 - [HTTP] --> POST /session/52afc1fc-a017-4d0a-a7f6-e74d0f72ebd5/element/00000000-0000-7b40-ffff-ffff000002e8/element
2024-08-22 14:06:07:264 - [HTTP] {"using":"-image","value":"iVBORw0KGgoAAAANSUhEUgAAAGsAAABrCAYAAABwv3wMAAAAAXNSR0IArs4c6QAAAARzQklUCAgICHwIZIgAABV2SURBVHic7Z1pkFxXdYC/+7bep2empRktlrFsZDDYlkEsdgiR44CRkZewuajgOEUquCpJ4UpBQSqVUEAVBGOXK2ZzVSiWQo4D3nBhygkYL8KAEYtlG8uSjC3Jlq1tlu7pmd7eevPj9Sy9TPfrnt6k6Psz02+975137zn3nHPvFVJKSRvYtk02m8WyrHZObwtVVTGMELqho6kaqqqiKApCCIQAIUTNOVJKpPT/ep6H67o4roNt2ViWieu6LZdhfHy8YpvluFy1o8CJQu39qxHATe8J855NWt39z0957JtwOZyVHMp4lBzJ+oTCWSMK9c9oQqFQYGZmpp1TW8IwDMKRCIZuoGkaitL8ZVQzL0gQqKqCrmtACGL+fs+TOI6DZVuUisWmH18oFKrZ9oOn8pwoKIHK87m/qC+oY3OS254w+ekLTp2z/A+qZWFls1ny+XyrpwUmEokSiUQxDL0t4bSKoggMQ8cwdOKxGJ4nsSybYrFAsVioOT4cDtdse/CFYI3Tp94Z4przal/5956y+cYuE6tJJQ8sLCklmUyGUqkU9JTAGIZBLJ4gZBg9EVAjFEUQDhuEwwbJZBLTssjn5rAsCyFETc06OmPyfFptet3NaxQ+slmv2X7nMzb/8SszUNkCCctxHDKZDLZtB7poUGKxONFYFF1rqzXuOooiiIRDRMIhbMfBMq0avfjIixa+JmrMtRcYNdse2O9wyy+CCQoCCMu2bdLpdMuKuBHxRIJYNIaqBmvnBwFd0+p+VDtf8oDGNSsRgsur9NScCV94rLVWqqGwLMsinU7jeV5LF12OWCxOPB4/qYTUjH1TzWvVB96oo1c98g/32k11VDXLCsuyLKanp2nTsq/AMAySyeGyJXbqYLpQcJp/ePc9Z5MuSK56vc5bzlARwF...
2024-08-22 14:06:07:265 - [AndroidUiautomator2Driver@8b9d (52afc1fc)] Calling AppiumDriver.findElementFromElement() with args: ["-image","iVBORw0KGgoAAAANSUhEUgAAAGsAAABrCAYAAABwv3wMAAAAAXNSR0IArs4c6QAAAARzQklUCAgICHwIZIgAABV2SURBVHic7Z1pkFxXdYC/+7bep2empRktlrFsZDDYlkEsdgiR44CRkZewuajgOEUquCpJ4UpBQSqVUEAVBGOXK2ZzVSiWQo4D3nBhygkYL8KAEYtlG8uSjC3Jlq1tlu7pmd7eevPj9Sy9TPfrnt6k6Psz02+975137zn3nHPvFVJKSRvYtk02m8WyrHZObwtVVTGMELqho6kaqqqiKApCCIQAIUTNOVJKpPT/ep6H67o4roNt2ViWieu6LZdhfHy8YpvluFy1o8CJQu39qxHATe8J855NWt39z0957JtwOZyVHMp4lBzJ+oTCWSMK9c9oQqFQYGZmpp1TW8IwDMKRCIZuoGkaitL8ZVQzL0gQqKqCrmtACGL+fs+TOI6DZVuUisWmH18oFKrZ9oOn8pwoKIHK87m/qC+oY3OS254w+ekLTp2z/A+qZWFls1ny+XyrpwUmEokSiUQxDL0t4bSKoggMQ8cwdOKxGJ4nsSybYrFAsVioOT4cDtdse/CFYI3Tp94Z4przal/5956y+cYuE6tJJQ8sLCklmUyGUqkU9JTAGIZBLJ4gZBg9EVAjFEUQDhuEwwbJZBLTssjn5rAsCyFETc06OmPyfFptet3NaxQ+slmv2X7nMzb/8SszUNkCCctxHDKZDLZtB7poUGKxONFYFF1rqzXuOooiiIRDRMIhbMfBMq0avfjIixa+JmrMtRcYNdse2O9wyy+CCQoCCMu2bdLpdMuKuBHxRIJYNIaqBmvnBwFd0+p+VDtf8oDGNSsRgsur9NScCV94rLVWqqGwLMsinU7jeV5LF12OWCxOPB4/qYTUjH1TzWvVB96oo1c98g/32k11VDXLCsuyLKanp2nTsq/AMAySyeGyJXbqYLpQcJp/ePc9Z5MuSK56vc5bzlARwF3Ptt7lqfv25pu+Tg...
2024-08-22 14:06:07:265 - [AppiumDriver@511e] Clearing new command timeout pre-emptively since plugin(s) will handle this command
2024-08-22 14:06:07:266 - [AppiumDriver@511e] Plugins which can handle cmd 'findElementFromElement': images
2024-08-22 14:06:07:266 - [AppiumDriver@511e] Plugin images is now handling cmd 'findElementFromElement'
2024-08-22 14:06:07:266 - [AppiumDriver@511e] Executing default handling behavior for command 'findElementFromElement'
2024-08-22 14:06:07:266 - [AndroidUiautomator2Driver@8b9d (52afc1fc)] Valid locator strategies for this request: xpath, id, class name, accessibility id, css selector, -android uiautomator
2024-08-22 14:06:07:279 - [AndroidUiautomator2Driver@8b9d (52afc1fc)] Encountered internal error running command: InvalidSelectorError: Locator Strategy '-image' is not supported for this session
2024-08-22 14:06:07:279 - [AndroidUiautomator2Driver@8b9d (52afc1fc)]     at AndroidUiautomator2Driver.validateLocatorStrategy (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/core.ts:318:13)
2024-08-22 14:06:07:279 - [AndroidUiautomator2Driver@8b9d (52afc1fc)]     at AndroidUiautomator2Driver.findElOrElsWithProcessing (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:57:8)
2024-08-22 14:06:07:279 - [AndroidUiautomator2Driver@8b9d (52afc1fc)]     at AndroidUiautomator2Driver.findElementFromElement (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:88:23)
2024-08-22 14:06:07:279 - [AndroidUiautomator2Driver@8b9d (52afc1fc)]     at commandExecutor (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.ts:106:18)
2024-08-22 14:06:07:279 - [AndroidUiautomator2Driver@8b9d (52afc1fc)]     at /opt/homebrew/lib/node_modules/appium/node_modules/async-lock/lib/index.js:171:12
2024-08-22 14:06:07:279 - [AndroidUiautomator2Driver@8b9d (52afc1fc)]     at AsyncLock._promiseTry (/opt/homebrew/lib/node_modules/appium/node_modules/async-lock/lib/index.js:306:31)
2024-08-22 14:06:07:279 - [AndroidUiautomator2Driver@8b9d (52afc1fc)]     at exec (/opt/homebrew/lib/node_modules/appium/node_modules/async-lock/lib/index.js:170:9)
2024-08-22 14:06:07:279 - [AndroidUiautomator2Driver@8b9d (52afc1fc)]     at AsyncLock.acquire (/opt/homebrew/lib/node_modules/appium/node_modules/async-lock/lib/index.js:189:3)
2024-08-22 14:06:07:279 - [AndroidUiautomator2Driver@8b9d (52afc1fc)]     at AndroidUiautomator2Driver.executeCommand (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.ts:122:39)
2024-08-22 14:06:07:279 - [AndroidUiautomator2Driver@8b9d (52afc1fc)]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-08-22 14:06:07:280 - [AndroidUiautomator2Driver@8b9d (52afc1fc)]     at defaultBehavior (/opt/homebrew/lib/node_modules/appium/lib/appium.js:1109:14)
2024-08-22 14:06:07:280 - [AndroidUiautomator2Driver@8b9d (52afc1fc)]     at ImageElementPlugin.handle (/Users/dev/.appium/node_modules/@appium/images-plugin/lib/plugin.js:84:12)
2024-08-22 14:06:07:280 - [AndroidUiautomator2Driver@8b9d (52afc1fc)]     at /opt/homebrew/lib/node_modules/appium/lib/appium.js:1178:16
2024-08-22 14:06:07:280 - [AndroidUiautomator2Driver@8b9d (52afc1fc)]     at AppiumDriver.executeWrappedCommand (/opt/homebrew/lib/node_modules/appium/lib/appium.js:1215:16)
2024-08-22 14:06:07:280 - [AndroidUiautomator2Driver@8b9d (52afc1fc)]     at AppiumDriver.executeCommand (/opt/homebrew/lib/node_modules/appium/lib/appium.js:1121:17)
2024-08-22 14:06:07:280 - [AndroidUiautomator2Driver@8b9d (52afc1fc)]     at asyncHandler (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:393:19)
2024-08-22 14:06:07:281 - [HTTP] <-- POST /session/52afc1fc-a017-4d0a-a7f6-e74d0f72ebd5/element/00000000-0000-7b40-ffff-ffff000002e8/element 400 16 ms - 2066**

**Comment by mykola-mokhnach** [comment]
It is only possible to find image element inside of another matched image element. Lookup inside native elements was newer supported

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
