### ISSUE TITLE
Appium automation tests not working after upgrading the device to iOS 17.6.1

### ISSUE THREAD

**Issue by margi-margi** [appium/appium#20569]
XCUITestDriver version - 7.26.2
MacOS version - 14.6.1
Appium version 2.11.3

I got below error when executing automated tests. 

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: pyidevice binary cannot be found in PATH. Please make sure it is installed. Visit [https://github.com/YueChen-C/py-ios-device] for more details.

I installed pyidevice binary but after that started getting following error. Can someone please  look into it?

Logs 

WARNING: Could not start a new session. Response code 500. Message: An unknown server-side error occurred while processing the command. Original error: '/Library/Frameworks/Python.framework/Versions/3.10/bin/pyidevice crash list --udid 00008101-000XXXXXXXXXX --network --format json' failed. Original error: 2024-09-11 11:23:56 [INFO] [LockDown] lockdown.py[line:350] ios 17 and above versions require the use of RemoteLockdownClient
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/pyidevice", line 8, in <module>
    sys.exit(cli())
  File "/Users/bharath980/Library/Python/3.10/lib/python/site-packages/ios_device/main.py", line 10, in cli
    cli_commands()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/bharath980/Library/Python/3.10/lib/python/site-packages/ios_device/cli/mobile.py", line 59, in crash_list
    crash_server.get_list()
  File "/Users/bharath980/Library/Python/3.10/lib/python/site-packages/ios_device/servers/crash_log.py", line 19, in get_list
    crash_list = self.crash_server.read_directory('/')
  File "/Users/bharath980/Library/Python/3.10/lib/python/site-packages/ios_device/servers/afc.py", line 210, in read_directory
    status, data = self.do_operation(AFC_OP_READ_DIR, dirname)
TypeError: cannot unpack non-iterable NoneType object

**Comment by eglitise** [comment]
Please provide your full Appium server log where you are seeing this error.
Also, your title implies that your tests were working before upgrading to iOS 17.6.1 - was it working on an older iOS version?

**Comment by margi-margi** [comment]
Below are Appium logs but I dont see any error there. 

@mykola-mokhnach We have iOS 16 devices where automation is executing without any issue but those are connected to a different machine. We are facing this issue on a different machine that is newly set up and using iOS 17.6.1 devices. I cannot confirm if it is because of iOS 17.6.1 iPhone. 

2024-09-12 13:55:07:306 [Appium] Attempting to load plugin relaxed-caps...
2024-09-12 13:55:07:307 [Appium] Requiring plugin at [/Users/bharath980/.appium/node_modules/@appium/relaxed-caps-plugin/index.js](mailto:/Users/bharath980/.appium/node_modules/@appium/relaxed-caps-plugin/index.js)
2024-09-12 13:55:07:320 [Appium] RelaxedCapsPlugin has been successfully loaded in 0.013s
2024-09-12 13:55:07:353 [Appium] Welcome to Appium v2.11.3
2024-09-12 13:55:07:354 [Appium] Non-default server args:
2024-09-12 13:55:07:355 [Appium] { address: '192.168.1.213',
  allowCors: true,
  basePath: '/wd/hub/',
  localTimezone: true,
  port: 59868,
  usePlugins: [ 'relaxed-caps' ] }
2024-09-12 13:55:07:355 [Appium] The autodetected Appium home path: /Users/bharath980/.appium
2024-09-12 13:55:07:355 [Appium] Attempting to load driver uiautomator2...
2024-09-12 13:55:07:356 [Appium] Attempting to load driver xcuitest...
2024-09-12 13:55:07:356 [Appium] Requiring driver at /Users/bharath980/.appium/node_modules/appium-uiautomator2-driver/build/index.js
2024-09-12 13:55:07:884 [Appium] AndroidUiautomator2Driver has been successfully loaded in 0.528s
2024-09-12 13:55:07:885 [Appium] Requiring driver at /Users/bharath980/.appium/node_modules/appium-xcuitest-driver/build/index.js
2024-09-12 13:55:08:498 [Appium] XCUITestDriver has been successfully loaded in 1.142s
2024-09-12 13:55:08:503 [Appium] You have enabled CORS requests from any host. Be careful not to visit sites which could maliciously try to start Appium sessions on your machine
2024-09-12 13:55:08:504 [Appium] Appium REST http interface listener started on http://192.168.1.213:59868/wd/hub
2024-09-12 13:55:08:504 [Appium] Available drivers:
2024-09-12 13:55:08:504 [Appium]   - [uiautomator2@3.7.7](mailto:uiautomator2@3.7.7) (automationName 'UiAutomator2')
2024-09-12 13:55:08:504 [Appium]   - [xcuitest@7.26.0](mailto:xcuitest@7.26.0) (automationName 'XCUITest')
2024-09-12 13:55:08:504 [Appium] Available plugins:
2024-09-12 13:55:08:504 [Appium]   - [relaxed-caps@1.0.6](mailto:relaxed-caps@1.0.6) (ACTIVE)
2024-09-12 13:55:08:751 [HTTP] --> GET /wd/hub/status {}
2024-09-12 13:55:08:751 [AppiumDriver@0682] Calling AppiumDriver.getStatus() with args: []
2024-09-12 13:55:08:752 [AppiumDriver@0682] Responding to client with driver.getStatus() result: {"ready":true,"message":"The server is ready to accept new connections","build":{"version":"2.11.3"}}
2024-09-12 13:55:08:754 [HTTP] <-- GET /wd/hub/status 200 2 ms - 111 
2024-09-12 13:55:08:757 [HTTP] --> GET /wd/hub/status {}
2024-09-12 13:55:08:757 [AppiumDriver@0682] Calling AppiumDriver.getStatus() with args: []
2024-09-12 13:55:08:758 [AppiumDriver@0682] Responding to client with driver.getStatus() result: {"ready":true,"message":"The server is ready to accept new connections","build":{"version":"2.11.3"}}
2024-09-12 13:55:08:758 [HTTP] <-- GET /wd/hub/status 200 1 ms - 111

**Comment by mykola-mokhnach** [comment]
This logs looks irrelevant to the above issue. Unfortunately we cannot help without it.

**Comment by margi-margi** [comment]
But there is nothing else in appium server logs. I tried to execute the command "pyidevice syslog" and I got similar error. 
In this case there is no appium server running. 

bharath980@TC599LXK776 ~ % **pyidevice devices**
[serial:00008101-000XXXXXXXXXXX, ConnectionType:USB]
bharath980@TC599LXK776 ~ % **pyidevice syslog**
2024-09-12 15:08:14 [INFO] [LockDown] **lockdown.py[line:350] ios 17 and above versions require the use of RemoteLockdownClient**
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/pyidevice", line 8, in <module>
    sys.exit(cli())
  File "/Users/bharath980/Library/Python/3.10/lib/python/site-packages/ios_device/main.py", line 10, in cli
    cli_commands()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/bharath980/Library/Python/3.10/lib/python/site-packages/ios_device/cli/mobile.py", line 140, in cmd_syslog
    server.watch(log_file=path, filter=filter)
  File "/Users/bharath980/Library/Python/3.10/lib/python/site-packages/ios_device/servers/syslog.py", line 60, in watch
    d = self.c.recv(4096)
AttributeError: 'NoneType' object has no attribute 'recv'

**Comment by eglitise** [comment]
Could you provide the capabilities you are using when attempting to create a new session?

**Comment by margi-margi** [comment]
Capabilities 
{appium:automationName: XCUITest, appium:bundleId: com.metro.XXXXXXX.test, appium:clearSystemFiles: true, appium:databaseEnabled: false, appium:deviceName:00008101-000XXXXXXXXXXX, appium:javascriptEnabled: true, appium:locationContextEnabled: false, appium:mjpegServerPort: 9106, appium:networkConnectionEnabled: false, appium:newCommandTimeout: 800, appium:noReset: true, appium:platformVersion: 17.6, appium:shouldTerminateApp: true, appium:takesScreenshot: true, appium:udid:00008101-000XXXXXXXXXXX, appium:usePrebuiltWDA: true, appium:wdaConnectionTimeout: 240000000, appium:wdaLaunchTimeout: 240000000, appium:wdaLocalPort: 57441, appium:wdaStartupRetries: 6, appium:wdaStartupRetryInterval: 20000000, appium:webStorageEnabled: false, platformName: IOS}

**Comment by KazuCocoa** [comment]
`pyidevice` might not support iOS 17+.
https://github.com/YueChen-C/py-ios-device?tab=readme-ov-file#support-ios-17-command-line-is-not-supported-

Could you share the appium server log after uninstalling `pyidevice` so that Appium will not refer to the binary?

**Comment by margi-margi** [comment]
In that case we get the error below(highlighted in bold).

{appium:automationName: XCUITest, appium:bundleId: com.metro.mymetro.test, appium:clearSystemFiles: true, appium:deviceName: XXXXXXXXXX, appium:mjpegServerPort: 9106, appium:newCommandTimeout: 800, appium:noReset: true, appium:platformVersion: 17.6.1, appium:shouldTerminateApp: true, appium:udid: XXXXXXXX, appium:usePrebuiltWDA: true, appium:wdaConnectionTimeout: 240000000, appium:wdaLaunchTimeout: 240000000, appium:wdaLocalPort: 57441, appium:wdaStartupRetries: 6, appium:wdaStartupRetryInterval: 20000000, platformName: IOS}
Sep 11, 2024 12:46:36 PM com.tmo.testngfw.setup.ResultContainer initLogger
INFO: FileName init log method::: Reports/2024-09-11_12-46-26/MOBILE/00008030-001249180168802E//Logs/Login_g_01_2024-09-11_12-46-26v24r8
Sep 11, 2024 12:46:36 PM com.tmo.testngfw.setup.InitializerScript beforeMethod
WARNING: BeforeClass Method
org.openqa.selenium.WebDriverException: **An unknown server-side error occurred while processing the command. Original error: pyidevice binary cannot be found in PATH. Please make sure it is installed. Visit [https://github.com/YueChen-C/py-ios-device] for more details.**
Build info: version: '4.18.1', revision: 'b1d3319b48'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '14.6.1', java.version: '11.0.23'
Driver info: io.appium.java_client.ios.IOSDriver
Command: [0cb7a5f5-7eac-4b01-9124-bfcfda7e8d4c, getLog {type=crashlog}]
Capabilities {appium:automationName: XCUITest, appium:bundleId: com.metro.mymetro.test, appium:clearSystemFiles: true, appium:databaseEnabled: false, appium:deviceName: XXXXX, appium:javascriptEnabled: true, appium:locationContextEnabled: false, appium:mjpegServerPort: 9106, appium:networkConnectionEnabled: false, appium:newCommandTimeout: 800, appium:noReset: true, appium:platformVersion: 17.6, appium:shouldTerminateApp: true, appium:takesScreenshot: true, appium:udid: XXXXX, appium:usePrebuiltWDA: true, appium:wdaConnectionTimeout: 240000000, appium:wdaLaunchTimeout: 240000000, appium:wdaLocalPort: 57441, appium:wdaStartupRetries: 6, appium:wdaStartupRetryInterval: 20000000, appium:webStorageEnabled: false, platformName: IOS}
Session ID: 0cb7a5f5-7eac-4b01-9124-bfcfda7e8d4c
                at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
                at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
                at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
                at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
                at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
                at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
                at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
                at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:190)
                at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:237)
                at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:519)
                at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:592)
                at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:302)
                at org.openqa.selenium.remote.RemoteExecuteMethod.execute(RemoteExecuteMethod.java:39)
                at org.openqa.selenium.remote.RemoteLogs.getRemoteEntries(RemoteLogs.java:77)
                at org.openqa.selenium.remote.RemoteLogs.get(RemoteLogs.java:73)
                at com.tmo.testngfw.setup.BaseInitializer.initDeviceLogs(BaseInitializer.java:662)

**Comment by KazuCocoa** [comment]
Could you share the appium server log instead of client-side log?

I guess your client called getting crash log getLog endpoint call, which requires `pyidevice`. The scenario should avoid calling it to not refer to `pyidevice`.

**Comment by margi-margi** [comment]
@KazuCocoa I have commented out the code that was making call to get the crash log. And the error is gone. I also had to uninstall the pyidevice binary for it to work.

Thank you support team.

**Comment by dmitcardata** [comment]
@margi-margi I am getting the same error and I uninstalled pyidevice but I have no idea what to comment out with respect to crashlog. I do not even think I am using it... can you provide more details on what you commented out?

**Comment by margi-margi** [comment]
Can you look at the stack trace to see which line of code is throwing error? Try commenting it out and see.Sent from my iPhoneOn Oct 8, 2024, at 9:22 PM, dmitcardata ***@***.***> wrote:﻿
@margi-margi I am getting the same error and I uninstalled pyidevice but I have no idea what to comment out with respect to crashlog. I do not even think I am using it... can you provide more details on what you commented out?
