### ISSUE TITLE
Appium windows driver compatibility in windows 11

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [appium/appium#20742]
I am trying to automate calculator in my windows 11 machine in java.

Below are the dependencies i have added in in pom file.

```
<!-- https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-java -->
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>3.141.59</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/io.appium/java-client -->
        <dependency>
            <groupId>io.appium</groupId>
            <artifactId>java-client</artifactId>
            <version>7.6.0</version>
        </dependency>
```

I have installed appium server and android windows driver via cmd. 

When i am running the program i am getting below logs.

In IDE:

```
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: WinAppDriver server is not listening within 10000ms timeout. Make sure it could be started manually
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DHARSHI', ip: '10.100.4.8', os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.13'
Driver info: driver.version: WindowsDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: WinAppDriver server is not listening within 10000ms timeout. Make sure it could be started manually
    at getResponseForW3CError (C:\Users\Dharshi\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\errors.js:1145:9)
    at asyncHandler (C:\Users\Dharshi\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\protocol.js:485:57)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DHARSHI', ip: '10.100.4.8', os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.13'
Driver info: driver.version: WindowsDriver
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:216)
	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:225)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:250)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.windows.WindowsDriver.execute(WindowsDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:363)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:37)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:89)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:99)
	at io.appium.java_client.windows.WindowsDriver.<init>(WindowsDriver.java:43)
	at org.example.CalculatorAutomation.<init>(CalculatorAutomation.java:25)
	at org.example.Main.main(Main.java:7)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:193)
	... 15 more
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: WinAppDriver server is not listening within 10000ms timeout. Make sure it could be started manually
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DHARSHI', ip: '10.100.4.8', os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.13'
Driver info: driver.version: WindowsDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: WinAppDriver server is not listening within 10000ms timeout. Make sure it could be started manually
    at getResponseForW3CError (C:\Users\Dharshi\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\errors.js:1145:9)
    at asyncHandler (C:\Users\Dharshi\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\protocol.js:485:57)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	... 20 more
```

Appium log: 

```
[Appium] Welcome to Appium v2.12.1
[Appium] The autodetected Appium home path: C:\Users\Dharshi\.appium
[Appium] Attempting to load driver windows...
[Appium] Requiring driver at C:\Users\Dharshi\.appium\node_modules\appium-windows-driver\build\index.js
[Appium] WindowsDriver has been successfully loaded in 0.287s
[Appium] Appium REST http interface listener started on http://0.0.0.0:4723
[Appium] You can provide the following URLs in your client code to connect to this server:
        http://10.100.4.8:4723/
        http://127.0.0.1:4723/ (only accessible from the same host)
[Appium] Available drivers:
[Appium]   - windows@3.0.2 (automationName 'Windows')
[Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.
[HTTP] Request idempotency key: d5152b7a-3820-45b7-9bb6-bf9385ab073d
[HTTP] --> POST /session {"desiredCapabilities":{"app":"Microsoft.WindowsCalculator_8wekyb3d8bbwe!App","automationName":"Windows","ms:experimental-webdriver":true,"platformName":"Windows","deviceName":"WindowsPC"},"capabilities":{"firstMatch":[{"appium:app":"Microsoft.WindowsCalculator_8wekyb3d8bbwe!App","appium:automationName":"Windows","appium:deviceName":"WindowsPC","ms:experimental-webdriver":true,"platformName":"windows"}]}}
[AppiumDriver@c483] Calling AppiumDriver.createSession() with args: [{"app":"Microsoft.WindowsCalculator_8wekyb3d8bbwe!App","automationName":"Windows","ms:experimental-webdriver":true,"platformName":"Windows","deviceName":"WindowsPC"},null,{"firstMatch":[{"appium:app":"Microsoft.WindowsCalculator_8wekyb3d8bbwe!App","appium:automationName":"Windows","appium:deviceName":"WindowsPC","ms:experimental-webdriver":true,"platformName":"windows"}]}]
[AppiumDriver@c483] Event 'newSessionRequested' logged at 1731383505569 (09:21:45 GMT+0530 (India Standard Time))
[Appium] Attempting to find matching driver for automationName 'Windows' and platformName 'windows'
[Appium] The 'windows' driver was installed and matched caps.
[Appium] Will require it at C:\Users\Dharshi\.appium\node_modules\appium-windows-driver
[Appium] Requiring driver at C:\Users\Dharshi\.appium\node_modules\appium-windows-driver\build\index.js
[AppiumDriver@c483] Appium v2.12.1 creating new WindowsDriver (v3.0.2) session
[AppiumDriver@c483] Checking BaseDriver versions for Appium and WindowsDriver
[AppiumDriver@c483] Appium's BaseDriver version is 9.12.1
[AppiumDriver@c483] WindowsDriver's BaseDriver version is 9.12.1
[WindowsDriver@4d6c]
[WindowsDriver@4d6c] Creating session with W3C capabilities: {
  "alwaysMatch": {
    "ms:experimental-webdriver": true,
    "platformName": "windows",
    "appium:app": "Microsoft.WindowsCalculator_8wekyb3d8bbwe!App",
    "appium:automationName": "Windows",
    "appium:deviceName": "WindowsPC"
  },
  "firstMatch": [
    {}
  ]
}
[WindowsDriver@4d6c] The following provided capabilities were not recognized by this driver:
[WindowsDriver@4d6c]   deviceName
[9cbc00e3][WindowsDriver@4d6c] Session created with session id: 9cbc00e3-d2d1-45f5-81ec-2836f83352c3
[9cbc00e3][WindowsDriver@4d6c] Spawning 'C:\Program Files\Windows Application Driver\WinAppDriver.exe' with args: ["4724/wd/hub"]
[9cbc00e3][WindowsDriver@4d6c] Matched '/status' to command name 'getStatus'
[9cbc00e3][WindowsDriver@4d6c] Proxying [GET /status] to [GET http://127.0.0.1:4724/wd/hub/status] with no body
[9cbc00e3][WindowsDriver@4d6c] connect ECONNREFUSED 127.0.0.1:4724
[9cbc00e3][WindowsDriver@4d6c] Windows Application Driver listening for requests at: http://127.0.0.1:4724/wd/hub
Press ENTER to exit.
[9cbc00e3][WindowsDriver@4d6c] Matched '/status' to command name 'getStatus'
[9cbc00e3][WindowsDriver@4d6c] Proxying [GET /status] to [GET http://127.0.0.1:4724/wd/hub/status] with no body
[9cbc00e3][WindowsDriver@4d6c] ==========================================
GET /wd/hub/status HTTP/1.1
Accept: application/json, */*
Accept-Encoding: gzip, compress, deflate, br
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Host: 127.0.0.1:4724
User-Agent: appium
[9cbc00e3][WindowsDriver@4d6c] Got response with status 500: {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[9cbc00e3][W3C] Matched W3C error code 'unknown error' to UnknownError
[9cbc00e3][WindowsDriver@4d6c] HTTP/1.1 500 Internal Error
Content-Length: 133
Content-Type: application/json
[9cbc00e3][WindowsDriver@4d6c] Matched '/status' to command name 'getStatus'
[9cbc00e3][WindowsDriver@4d6c] Proxying [GET /status] to [GET http://127.0.0.1:4724/wd/hub/status] with no body
[9cbc00e3][WindowsDriver@4d6c] ==========================================
GET /wd/hub/status HTTP/1.1
Accept: application/json, */*
Accept-Encoding: gzip, compress, deflate, br
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Host: 127.0.0.1:4724
User-Agent: appium
[9cbc00e3][WindowsDriver@4d6c] Got response with status 500: {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[9cbc00e3][W3C] Matched W3C error code 'unknown error' to UnknownError
[9cbc00e3][WindowsDriver@4d6c] HTTP/1.1 500 Internal Error
Content-Length: 133
Content-Type: application/json

{"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[9cbc00e3][WindowsDriver@4d6c] Matched '/status' to command name 'getStatus'
[9cbc00e3][WindowsDriver@4d6c] Proxying [GET /status] to [GET http://127.0.0.1:4724/wd/hub/status] with no body
[9cbc00e3][WindowsDriver@4d6c] ==========================================
GET /wd/hub/status HTTP/1.1
Accept: application/json, */*
Accept-Encoding: gzip, compress, deflate, br
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Host: 127.0.0.1:4724
User-Agent: appium
[9cbc00e3][WindowsDriver@4d6c] Got response with status 500: {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[9cbc00e3][W3C] Matched W3C error code 'unknown error' to UnknownError
[9cbc00e3][WindowsDriver@4d6c] HTTP/1.1 500 Internal Error
Content-Length: 133
Content-Type: application/json

{"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[9cbc00e3][WindowsDriver@4d6c] Matched '/status' to command name 'getStatus'
[9cbc00e3][WindowsDriver@4d6c] Proxying [GET /status] to [GET http://127.0.0.1:4724/wd/hub/status] with no body
[9cbc00e3][WindowsDriver@4d6c] ==========================================
GET /wd/hub/status HTTP/1.1
Accept: application/json, */*
Accept-Encoding: gzip, compress, deflate, br
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Host: 127.0.0.1:4724
User-Agent: appium
[9cbc00e3][WindowsDriver@4d6c] Got response with status 500: {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[9cbc00e3][W3C] Matched W3C error code 'unknown error' to UnknownError
[9cbc00e3][WindowsDriver@4d6c] HTTP/1.1 500 Internal Error
Content-Length: 133
Content-Type: application/json

{"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[9cbc00e3][WindowsDriver@4d6c] Matched '/status' to command name 'getStatus'
[9cbc00e3][WindowsDriver@4d6c] Proxying [GET /status] to [GET http://127.0.0.1:4724/wd/hub/status] with no body
[9cbc00e3][WindowsDriver@4d6c] ==========================================
GET /wd/hub/status HTTP/1.1
Accept: application/json, */*
Accept-Encoding: gzip, compress, deflate, br
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Host: 127.0.0.1:4724
User-Agent: appium
[9cbc00e3][WindowsDriver@4d6c] Got response with status 500: {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[9cbc00e3][W3C] Matched W3C error code 'unknown error' to UnknownError
[9cbc00e3][WindowsDriver@4d6c] HTTP/1.1 500 Internal Error
Content-Length: 133
Content-Type: application/json

{"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[9cbc00e3][WindowsDriver@4d6c] Matched '/status' to command name 'getStatus'
[9cbc00e3][WindowsDriver@4d6c] Proxying [GET /status] to [GET http://127.0.0.1:4724/wd/hub/status] with no body
[9cbc00e3][WindowsDriver@4d6c] ==========================================
GET /wd/hub/status HTTP/1.1
Accept: application/json, */*
Accept-Encoding: gzip, compress, deflate, br
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Host: 127.0.0.1:4724
User-Agent: appium
[9cbc00e3][WindowsDriver@4d6c] Got response with status 500: {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[9cbc00e3][W3C] Matched W3C error code 'unknown error' to UnknownError
[9cbc00e3][WindowsDriver@4d6c] HTTP/1.1 500 Internal Error
Content-Length: 133
Content-Type: application/json

{"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[9cbc00e3][WindowsDriver@4d6c] Matched '/status' to command name 'getStatus'
[9cbc00e3][WindowsDriver@4d6c] Proxying [GET /status] to [GET http://127.0.0.1:4724/wd/hub/status] with no body
[9cbc00e3][WindowsDriver@4d6c] ==========================================
GET /wd/hub/status HTTP/1.1
Accept: application/json, */*
Accept-Encoding: gzip, compress, deflate, br
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Host: 127.0.0.1:4724
User-Agent: appium
[9cbc00e3][WindowsDriver@4d6c] Got response with status 500: {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[9cbc00e3][W3C] Matched W3C error code 'unknown error' to UnknownError
[9cbc00e3][WindowsDriver@4d6c] HTTP/1.1 500 Internal Error
Content-Length: 133
Content-Type: application/json

{"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[9cbc00e3][WindowsDriver@4d6c] Matched '/status' to command name 'getStatus'
[9cbc00e3][WindowsDriver@4d6c] Proxying [GET /status] to [GET http://127.0.0.1:4724/wd/hub/status] with no body
[9cbc00e3][WindowsDriver@4d6c] ==========================================
GET /wd/hub/status HTTP/1.1
Accept: application/json, */*
Accept-Encoding: gzip, compress, deflate, br
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Host: 127.0.0.1:4724
User-Agent: appium
[9cbc00e3][WindowsDriver@4d6c] Got response with status 500: {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[9cbc00e3][W3C] Matched W3C error code 'unknown error' to UnknownError
[9cbc00e3][WindowsDriver@4d6c] HTTP/1.1 500 Internal Error
Content-Length: 133
Content-Type: application/json

{"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[9cbc00e3][WindowsDriver@4d6c] Matched '/status' to command name 'getStatus'
[9cbc00e3][WindowsDriver@4d6c] Proxying [GET /status] to [GET http://127.0.0.1:4724/wd/hub/status] with no body
[9cbc00e3][WindowsDriver@4d6c] ==========================================
GET /wd/hub/status HTTP/1.1
Accept: application/json, */*
Accept-Encoding: gzip, compress, deflate, br
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Host: 127.0.0.1:4724
User-Agent: appium
[9cbc00e3][WindowsDriver@4d6c] Got response with status 500: {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[9cbc00e3][W3C] Matched W3C error code 'unknown error' to UnknownError
[9cbc00e3][WindowsDriver@4d6c] HTTP/1.1 500 Internal Error
Content-Length: 133
Content-Type: application/json

{"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[9cbc00e3][WindowsDriver@4d6c] Matched '/status' to command name 'getStatus'
[9cbc00e3][WindowsDriver@4d6c] Proxying [GET /status] to [GET http://127.0.0.1:4724/wd/hub/status] with no body
[9cbc00e3][WindowsDriver@4d6c] ==========================================
GET /wd/hub/status HTTP/1.1
Accept: application/json, */*
Accept-Encoding: gzip, compress, deflate, br
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Host: 127.0.0.1:4724
User-Agent: appium
[9cbc00e3][WindowsDriver@4d6c] Got response with status 500: {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[9cbc00e3][W3C] Matched W3C error code 'unknown error' to UnknownError
[9cbc00e3][WindowsDriver@4d6c] Deleting WinAppDriver session
[9cbc00e3][WindowsDriver@4d6c] HTTP/1.1 500 Internal Error
Content-Length: 133
Content-Type: application/json

{"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[9cbc00e3][WindowsDriver@4d6c] WinAppDriver exited with code null, signal SIGTERM
[9cbc00e3][AppiumDriver@c483] Event 'newSessionStarted' logged at 1731383515625 (09:21:55 GMT+0530 (India Standard Time))
[9cbc00e3][AppiumDriver@c483] Encountered internal error running command: Error: WinAppDriver server is not listening within 10000ms timeout. Make sure it could be started manually
    at WinAppDriver.start (C:\Users\Dharshi\.appium\node_modules\appium-windows-driver\lib\winappdriver.js:164:15)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at WindowsDriver.startWinAppDriverSession (C:\Users\Dharshi\.appium\node_modules\appium-windows-driver\lib\driver.js:104:5)
    at WindowsDriver.createSession (C:\Users\Dharshi\.appium\node_modules\appium-windows-driver\lib\driver.js:92:7)
    at AppiumDriver.createSession (C:\Users\Dharshi\AppData\Roaming\npm\node_modules\appium\lib\appium.js:739:35)
[9cbc00e3][HTTP] <-- POST /session 500 10096 ms - 768

```

I dont know what is the mistake i have done. Do i need to start winapp driver as well? Or this is beause of the version of the windows, which is 11. 

Can anyone pls help me pls?

**Comment by KazuCocoa** [comment]
Possibly related to https://github.com/microsoft/WinAppDriver/issues/2036 ?
https://github.com/microsoft/WinAppDriver/issues/1985 etc.

It looks like searching https://github.com/search?q=repo%3Amicrosoft%2FWinAppDriver++%22An+unknown+error+occurred+in+the+remote+end+while+processing+the+command%22+Windows+11&type=issues would be more helpful as WinAppDriver side reason. (closing as more WinAppDriver side)
