### ISSUE TITLE
bug: iOS Application got freeze after login in Mac OS 15.1, XCode 16.1, Device OS 18.0

### ISSUE THREAD

**Issue by UJethva4** [appium/appium#20784]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am using hybrid application, when we execute .IPA on iPhone 18.0 x XCode 16.1 then application launch successfully, but after login it is stuck and application gets freeze.

After login application context convert to Native to WebView and we process further steps base on webview selector.

### Expected Behavior

Same application is running successfully on Mac 13.5 with below version details:
Mac machine: admin’s New iMac 
- macOS: Ventura 13.5
- Xcode: 15
- Device: iOS 17, 17.7
- macOS: Ventura 13.5
- Appium: 2.0.1
- ipa file: Created on Xcode 15.4

### Minimal Reproducible Example

Used capabilities

        setProperty(propertyFile);

        DesiredCapabilities capabilities = new DesiredCapabilities(); 
        capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, m_platform.name());
        capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, m_platformVersion);
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, m_deviceName);
        capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, EMPTY_STRING); 
        capabilities.setCapability(MobileCapabilityType.APP, m_appPath);
        capabilities.setCapability(MobileCapabilityType.UDID, m_deviceId);
        capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, "300");
        capabilities.setCapability("useJSONSource", true);
        capabilities.setCapability("appium:chromeOptions", ImmutableMap.of("w3c", false));

        capabilities.setCapability(MobileCapabilityType.FULL_RESET, true);
        if(m_fullReset){
            capabilities.setCapability(MobileCapabilityType.FULL_RESET, false);
            capabilities.setCapability(MobileCapabilityType.NO_RESET, false);
        }
       capabilities.setCapability(IOSMobileCapabilityType.AUTO_ACCEPT_ALERTS, true);
       capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "XCUITest");

       if((m_wdaLocalPort !=null) && (!(m_wdaLocalPort.equals(""))) ) {
                capabilities.setCapability("wdaLocalPort", m_wdaLocalPort);
            }

      m_driver = new IOSDriver(new URL(m_serverUrl), capabilities);

### Environment

Issue facing in below version details:

**Below are the Mac version details:**
MAC OS : 15.1
Appium version : 2.11.5
npm version : 10.5.2
xcode : 16.1
appium-xcuitest-driver : 7.27.0

**Framwork version details:**
selenium-java : 3.141.59
appium client : 7.2.0

**Device version details:**
iPhone version : 18.0

### Further Information

Please help me to solve this issue, is there any application side issue or out automation setup issue... and also let me know if you need any other details

**Comment by mykola-mokhnach** [comment]
Please provide server logs along with the device logs for the time range where the app actually freezes

**Comment by UJethva4** [comment]
@mykola-mokhnach Thanks for your response,

We are using physical device iPhone 18.0.

**Below are the Appium command log where app gets freeze:**

[9164e9a2][RemoteDebugger] Executing 'execute_script' atom in default context
[9164e9a2][RemoteDebugger] Sending javascript command: '(function(){return (function(){var e=this||self...'
[9164e9a2][RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:1386', page '2', target 'page-35' (id: 152): 'Runtime.evaluate'
[9164e9a2][RemoteDebugger] Received data response from send (id: 152): '{"status":0,"value":null}'
[9164e9a2][RemoteDebugger] Sending to Web Inspector took 16ms
[9164e9a2][RemoteDebugger] Received result for atom 'execute_script' execution: null
[9164e9a2][XCUITestDriver@74f2] Responding to client with driver.execute() result: null
[9164e9a2][HTTP] <-- POST /session/9164e9a2-f4c3-4dbe-a60c-138983d41de4/execute/sync 200 19 ms - 14 
[a399beae][Xcode] 2024-11-28 12:31:53.413956+0530 WebDriverAgentRunner-Runner[1370:751018] Waiting up to 10s until com.apple.springboard is in idle state (including animations)
[a399beae][Xcode]     t =   317.45s     Wait for com.apple.springboard to idle
[9164e9a2][HTTP] --> POST /session/9164e9a2-f4c3-4dbe-a60c-138983d41de4/execute/sync {"script":"var interval = setInterval(function() {\n\tif (crm_core && crm_core.pageEvents && crm_core.pageEvents.genericEvents && crm_core.pageEvents.genericEvents.formShown) {\n\t\tclearInterval(interval);\n\t\tvar pageId;\n\t\tcrm_core.pageEvents.genericEvents.formShown.one(function(view) {\n            pageId = view.model.get(\"pageId\");\n\n\t\t    console.log(\"=================================form shown===================================\");\n\t\t    crm_core.pageEvents(pageId).fixup.one(function(view) {\n                crm_core.automatedTesting = {};\n                crm_core.automatedTesting.pageLoaded = true;\n                console.log(\"=================================flag set ===================================\");\n            });\n\t\t});\n\t}\n}, 10);","args":[]}
[9164e9a2][XCUITestDriver@74f2] Calling AppiumDriver.execute() with args: ["var interval = setInterval(function() {\n\tif (crm_core && crm_core.pageEvents && crm_core.pageEvents.genericEvents && crm_core.pageEvents.genericEvents.formShown) {\n\t\tclearInterval(interval);\n\t\tvar pageId;\n\t\tcrm_core.pageEvents.genericEvents.formShown.one(function(view) {\n            pageId = view.model.get(\"pageId\");\n\n\t\t    console.log(\"=================================form shown===================================\");\n\t\t    crm_core.pageEvents(pageId).fixup.one(function(view) {\n                crm_core.automatedTesting = {};\n                crm_core.automatedTesting.pageLoaded = true;\n                console.log(\"=================================flag set ===================================\");\n            });\n\t\t});\n\t}\n}, 10);",[],"9164e9a2-f4c3-4dbe-a60c-138983d41de4"]
[9164e9a2][XCUITestDriver@74f2] Executing command 'execute'
[9164e9a2][RemoteDebugger] Executing atom 'execute_script' with 'args=["var interval = setInterval(function() {\n\tif (crm_core && crm_core.pageEvents && crm_core.pageEvents.genericEvents && crm_core.pageEvents.genericEvents.formShown) {\n\t\tclearInterval(interval);\n\t\tvar pageId;\n\t\tcrm_core.pageEvents.genericEvents.formShown.one(function(view) {\n            pageId = view.model.get(\"pageId\");\n\n\t\t    console.log(\"=================================form shown===================================\");\n\t\t    crm_core.pageEvents(pageId).fixup.one(function(view) {\n                crm_core.automatedTesting = {};\n                crm_core.automatedTesting.pageLoaded = true;\n                console.log(\"=================================flag set ===================================\");\n            });\n\t\t});\n\t}\n}, 10);",[]]; frames='
[9164e9a2][RemoteDebugger] Executing 'execute_script' atom in default context
[9164e9a2][RemoteDebugger] Sending javascript command: '(function(){return (function(){var e=this||self...'
[9164e9a2][RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:1386', page '2', target 'page-35' (id: 154): 'Runtime.evaluate'
[9164e9a2][RemoteDebugger] Received data response from send (id: 154): '{"status":0,"value":null}'
[9164e9a2][RemoteDebugger] Sending to Web Inspector took 3ms
[9164e9a2][RemoteDebugger] Received result for atom 'execute_script' execution: null
[9164e9a2][XCUITestDriver@74f2] Responding to client with driver.execute() result: null
[9164e9a2][HTTP] <-- POST /session/9164e9a2-f4c3-4dbe-a60c-138983d41de4/execute/sync 200 4 ms - 14 
[9164e9a2][HTTP] --> POST /session/9164e9a2-f4c3-4dbe-a60c-138983d41de4/execute/sync {"script":"var interval = setInterval(function() {\n\tif (crm_core && crm_core.pageEvents && crm_core.pageEvents.genericEvents && crm_core.pageEvents.genericEvents.formShown) {\n\t\tclearInterval(interval);\n\t\tvar pageId;\n\t\tcrm_core.pageEvents.genericEvents.formShown.one(function(view) {\n            pageId = view.model.get(\"pageId\");\n\n\t\t    console.log(\"=================================form shown===================================\");\n\t\t    crm_core.pageEvents(pageId).fixup.one(function(view) {\n                crm_core.automatedTesting = {};\n                crm_core.automatedTesting.pageLoaded = true;\n                console.log(\"=================================flag set ===================================\");\n            });\n\t\t});\n\t}\n}, 10);","args":[]}
[9164e9a2][XCUITestDriver@74f2] Calling AppiumDriver.execute() with args: ["var interval = setInterval(function() {\n\tif (crm_core && crm_core.pageEvents && crm_core.pageEvents.genericEvents && crm_core.pageEvents.genericEvents.formShown) {\n\t\tclearInterval(interval);\n\t\tvar pageId;\n\t\tcrm_core.pageEvents.genericEvents.formShown.one(function(view) {\n            pageId = view.model.get(\"pageId\");\n\n\t\t    console.log(\"=================================form shown===================================\");\n\t\t    crm_core.pageEvents(pageId).fixup.one(function(view) {\n                crm_core.automatedTesting = {};\n                crm_core.automatedTesting.pageLoaded = true;\n                console.log(\"=================================flag set ===================================\");\n            });\n\t\t});\n\t}\n}, 10);",[],"9164e9a2-f4c3-4dbe-a60c-138983d41de4"]
[9164e9a2][XCUITestDriver@74f2] Executing command 'execute'
[9164e9a2][RemoteDebugger] Executing atom 'execute_script' with 'args=["var interval = setInterval(function() {\n\tif (crm_core && crm_core.pageEvents && crm_core.pageEvents.genericEvents && crm_core.pageEvents.genericEvents.formShown) {\n\t\tclearInterval(interval);\n\t\tvar pageId;\n\t\tcrm_core.pageEvents.genericEvents.formShown.one(function(view) {\n            pageId = view.model.get(\"pageId\");\n\n\t\t    console.log(\"=================================form shown===================================\");\n\t\t    crm_core.pageEvents(pageId).fixup.one(function(view) {\n                crm_core.automatedTesting = {};\n                crm_core.automatedTesting.pageLoaded = true;\n                console.log(\"=================================flag set ===================================\");\n            });\n\t\t});\n\t}\n}, 10);",[]]; frames='
[9164e9a2][RemoteDebugger] Executing 'execute_script' atom in default context
[9164e9a2][RemoteDebugger] Sending javascript command: '(function(){return (function(){var e=this||self...'
[9164e9a2][RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:1386', page '2', target 'page-35' (id: 156): 'Runtime.evaluate'
[9164e9a2][RemoteDebugger] Received data response from send (id: 156): '{"status":0,"value":null}'
[9164e9a2][RemoteDebugger] Sending to Web Inspector took 4ms
[9164e9a2][RemoteDebugger] Received result for atom 'execute_script' execution: null
[9164e9a2][XCUITestDriver@74f2] Responding to client with driver.execute() result: null
[9164e9a2][HTTP] <-- POST /session/9164e9a2-f4c3-4dbe-a60c-138983d41de4/execute/sync 200 6 ms - 14 
[9164e9a2][HTTP] --> POST /session/9164e9a2-f4c3-4dbe-a60c-138983d41de4/execute/sync {"script":"return (!!crm_core.automatedTesting && crm_core.automatedTesting.pageLoaded);","args":[]}
[9164e9a2][XCUITestDriver@74f2] Calling AppiumDriver.execute() with args: ["return (!!crm_core.automatedTesting && crm_core.automatedTesting.pageLoaded);",[],"9164e9a2-f4c3-4dbe-a60c-138983d41de4"]
[9164e9a2][XCUITestDriver@74f2] Executing command 'execute'
[9164e9a2][RemoteDebugger] Executing atom 'execute_script' with 'args=["return (!!crm_core.automatedTesting && crm_core.automatedTesting.pageLoaded);",[]]; frames='
[9164e9a2][RemoteDebugger] Executing 'execute_script' atom in default context
[9164e9a2][RemoteDebugger] Sending javascript command: '(function(){return (function(){var e=this||self...'
[9164e9a2][RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:1386', page '2', target 'page-35' (id: 158): 'Runtime.evaluate'
[9164e9a2][RemoteDebugger] Received data response from send (id: 158): '{"status":0,"value":false}'
[9164e9a2][RemoteDebugger] Sending to Web Inspector took 3ms
[9164e9a2][RemoteDebugger] Received result for atom 'execute_script' execution: false
[9164e9a2][XCUITestDriver@74f2] Responding to client with driver.execute() result: false
[9164e9a2][HTTP] <-- POST /session/9164e9a2-f4c3-4dbe-a60c-138983d41de4/execute/sync 200 4 ms - 15 
[9164e9a2][HTTP] --> POST /session/9164e9a2-f4c3-4dbe-a60c-138983d41de4/execute/sync {"script":"return (!!crm_core.automatedTesting && crm_core.automatedTesting.pageLoaded);","args":[]}
[9164e9a2][XCUITestDriver@74f2] Calling AppiumDriver.execute() with args: ["return (!!crm_core.automatedTesting && crm_core.automatedTesting.pageLoaded);",[],"9164e9a2-f4c3-4dbe-a60c-138983d41de4"]

**Comment by mykola-mokhnach** [comment]
I don't observe any issues in the above log. Please provide the device log as well

**Comment by UJethva4** [comment]
We are using selenium + java framework and execute code on iPhone 18.x device. so we have get logs on inteliJ console and an Appium port. 

Actually, when application is freeze, Code try to access element of the page, but location of element is not able to find, so it give error "Can't locate element".

After freezing application only title is displayed and whole application page got blank.

**Below are the logs of InteliJ Console:** 

Nov 28, 2024 5:01:56 PM stayinfront.test.automation.framework.MobileAutomationController logInfo
INFO: Sidebar expanded.

java.lang.AssertionError: Can't locate sidebar item:[Visits]

	at org.testng.Assert.fail(Assert.java:94)
	at stayinfront.test.automation.touchcg.pages.Sidebar.clickSidebarItem(Sidebar.java:606)
	at stayinfront.test.automation.touchcg.pages.Sidebar.selectSidebarItem(Sidebar.java:617)
	at stayinfront.test.automation.touchcg.pages.Sidebar.selectSidebarItem(Sidebar.java:612)
	at stayinfront.test.automation.cg.Test91884.step13(Test91884.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)

**Comment by UJethva4** [comment]
@mykola-mokhnach : No, the same app is working properly on older platform like Mac OS 14.x and device OS 17.7, when we try to execute same IPA file on updated Mac OS 15.1 and device OS 18.0 then it freeze after login, So I think there is something missing. but don't know what is impacted here..
  
1. Is there any Application issue? 
2. Is there any Automation setup issue which we done on latest mac OS system?
3. Is there any library missing issue which need for latest MAC OS : 15.1, Appium version : 2.11.5, npm version : 10.5.2, xcode : 16.1, appium-xcuitest-driver : 7.27.0?

But the thing is that same IPA file is successfully running on old mac(14.x), so is there possible that application development side issue? 

**Please recheck the New update mac version detail for automation setup.**
Below are the Mac version details:
MAC OS : 15.1
Appium version : 2.11.5
npm version : 10.5.2
xcode : 16.1
appium-xcuitest-driver : 7.27.0

Framwork version details:
selenium-java : 3.141.59
appium client : 7.2.0

Device version details:
iPhone version : 18.0


Please help us to solve this issue..

**Comment by mykola-mokhnach** [comment]
Like I said I don't observe any driver issues based on the provided information. I cannot say anything about the application itself because I don't have access to its source code neither a possibility to debug it.

**Comment by ScorpioNicks** [comment]
I am facing a similar issue. The application becomes completely unresponsive when we click the button, and at that point, the page gets stuck.

We are now encountering a issue where the application freezes after login and displays the error:
“An element could not be located on the page using the given search parameters.”

We have been working on a solution, but the issue remains unresolved. Could you please assist us in resolving this?

Here are the details of the environment where the issue was replicated:

Mac and iOS Device Details:
Mac Machine: Admin’s Mac Mini
macOS: Sonoma 14.4 and 14.7
Xcode: 15 and 16
Devices: iPad 17, 17.7, 18.0.1
Appium Versions: 2.0.1 and 2.11.5
IPA File: Created on Xcode 15.4 and 16
Issue:
The page goes blank and gets stuck after login.

Steps Taken to Resolve:
Updated Xcode, Appium, XCUITest, and macOS to the required versions for iOS 18 devices.
Created and tested a new Touch build.
Despite these efforts, the automation test still fails after login, causing the page to become unresponsive.

I am handling a page in my automation code where it throws a timeout exception, but it still gets stuck on the next page. This happens the I click the 'Add' button, so I am a bit confused if this is an issue with the app or webdriveragent.

If you need more details, please let me know.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
