### ISSUE TITLE
bug: "io.appium.java_client.NoSuchContextException: Appium unexpectedly ended the connection. It may have quit abnormally" when switching context

### ISSUE THREAD

**Issue by anna-yujeong** [appium/appium#20785]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1. `(((SupportsContextSwitching) driver).getContextHandles());` to get current contexts (and i do see "WEBVIEW_xx" here)
2. ((SupportsContextSwitching) driver).context(context); if there is webview context
3. instead of setting the context to webview, it throws `io.appium.java_client.NoSuchContextException: Appium unexpectedly ended the connection. It may have quit abnormally.`

it cannot be reproduced all time but pretty frequent

### Expected Behavior

Set context without throwing error io.appium.java_client.NoSuchContextException

### Minimal Reproducible Example

```
Set<String> contextNames = getContexts();
		for (String contextName : contextNames) {
			if (contextName.contains("WEBVIEW")) {
					((SupportsContextSwitching) driver).context(context);
				}
		}
```

### Environment

- Operating system: macos
- Appium server version (output of `appium --version`): 2.11.5
- Appium driver(s) and their version(s) (`appium driver list`): - xcuitest@7.27.0 [installed (npm)]
- Appium plugin(s) and their version(s) (`appium plugin list`):
- Node.js version (output of `node --version`): v18.20.1
- `npm` version (output of `npm --version`): 10.5.0
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: iOS 17
- Real device or emulator/simulator: real device

**Comment by mykola-mokhnach** [comment]
Please provide the full server log

**Comment by jamesPodo** [comment]
Hi @mykola-mokhnach, Here is the appium log. it seems the process got stuck after calling getCurrentContext. we have 60 secs for new command timeout so it waits for new command, then it shuts down the connection after this timeout.
[appium.log](https://github.com/user-attachments/files/17984286/appium.log)

**Comment by jamesPodo** [comment]
- at the very bottom of the log, you will see no new command requested after calling getCurrentContext.
- I can't really tell as I am not actively working on the project at the moment. the person who created this issue is current unavailable so I can update you once the original author is back.
- In the meantime, I'll also try to contact Saucelab customer supports. Thank you!

**Comment by mykola-mokhnach** [comment]
> io.appium.java_client.NoSuchContextException: Appium unexpectedly ended the connection. It may have quit abnormally.

The above error message is definitely not generated by XCUITest driver or Appium server, and must be related to an internal Saucelabs stuff.  I don't observe any explicit issues in the server log though.

**Comment by anna-yujeong** [comment]
> Have you tried to reproduce the issue locally? Are you sure it is not a Saucelabs-specific issue?
It's hard to tell as it's randomly reproducible. However a colleague of mine and I have seen the test freeze after getContext and trying to switch context when running the test locally on xcode simulator. Not exactly sure if the error message was same, but i will try to repro to collect any logs. Also the colleague i mentioned is on vacation right now so I can gather more info on this once she's back.

Meanwhile, this issue https://github.com/appium/java-client/issues/2075 seems to be the same as what i see - was wondering if there was previous investigation on it?

**Comment by mykola-mokhnach** [comment]
In order to even start a basic investigation it is necessary to have a sample application and the automation script which is able to stable reproduce the context lookup issue. Without this data I don't think we would be able to help much.

**Comment by anna-yujeong** [comment]
This is a part of appium log when running into this issue on local simulator. Please note that i took out sensitive info with '***'
```
[a66552aa][XCUITestDriver@1b59] Responding to client with driver.getContexts() result: ["NATIVE_APP","WEBVIEW_96144.12"]
[a66552aa][HTTP] <-- GET /session/a66552aa-a4f0-41a9-a0bb-563f30eb8463/contexts 200 70 ms - 43 
[a66552aa][HTTP] --> GET /session/a66552aa-a4f0-41a9-a0bb-563f30eb8463/context {}
[a66552aa][XCUITestDriver@1b59] Calling AppiumDriver.getCurrentContext() with args: ["a66552aa-a4f0-41a9-a0bb-563f30eb8463"]
[a66552aa][XCUITestDriver@1b59] Executing command 'getCurrentContext'
[a66552aa][XCUITestDriver@1b59] Responding to client with driver.getCurrentContext() result: "NATIVE_APP"
[a66552aa][HTTP] <-- GET /session/a66552aa-a4f0-41a9-a0bb-563f30eb8463/context 200 1 ms - 22 
[a66552aa][HTTP] --> POST /session/a66552aa-a4f0-41a9-a0bb-563f30eb8463/context {"name":"WEBVIEW_96144.11"}
[a66552aa][XCUITestDriver@1b59] Calling AppiumDriver.setContext() with args: ["WEBVIEW_96144.11","a66552aa-a4f0-41a9-a0bb-563f30eb8463"]
[a66552aa][XCUITestDriver@1b59] Executing command 'setContext'
[a66552aa][XCUITestDriver@1b59] Attempting to set context to 'WEBVIEW_96144.11' from 'NATIVE_APP'
[a66552aa][XCUITestDriver@1b59] Encountered internal error running command: NoSuchContextError: No such context found.
    at XCUITestDriver.setContext (/Users/***/.appium/node_modules/appium-xcuitest-driver/lib/commands/context.js:539:13)
    at runCommandPromise (/Users/***/.nodenv/versions/18.20.1/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.ts:115:20)
    at /Users/***/.nodenv/versions/18.20.1/lib/node_modules/appium/node_modules/async-lock/lib/index.js:171:12
    at AsyncLock._promiseTry (/Users/***/.nodenv/versions/18.20.1/lib/node_modules/appium/node_modules/async-lock/lib/index.js:306:31)
    at exec (/Users/***/.nodenv/versions/18.20.1/lib/node_modules/appium/node_modules/async-lock/lib/index.js:170:9)
    at AsyncLock.acquire (/Users/***/.nodenv/versions/18.20.1/lib/node_modules/appium/node_modules/async-lock/lib/index.js:189:3)
    at XCUITestDriver.executeCommand (/Users/***/.nodenv/versions/18.20.1/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.ts:159:39)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at XCUITestDriver.executeCommand (/Users/***/.appium/node_modules/appium-xcuitest-driver/lib/driver.js:1044:12)
    at defaultBehavior (/Users/***/.nodenv/versions/18.20.1/lib/node_modules/appium/lib/appium.js:1136:14)
    at AppiumDriver.executeWrappedCommand (/Users/***/.nodenv/versions/18.20.1/lib/node_modules/appium/lib/appium.js:1242:16)
    at AppiumDriver.executeCommand (/Users/***/.nodenv/versions/18.20.1/lib/node_modules/appium/lib/appium.js:1148:17)
    at asyncHandler (/Users/***/.nodenv/versions/18.20.1/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:387:19)
```

And stacktrace:

```
Dec. 11, 2024 2:02:55 P.M. org.openqa.selenium.remote.ErrorCodes toStatus
INFO: HTTP Status: '400' -> incorrect JSON status mapping for 'unknown error' (500 expected)

io.appium.java_client.NoSuchContextException: No such context found.
Build info: version: '4.25.0', revision: '8a8aea2337'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '14.7', java.version: '17.0.12'
Driver info: io.appium.java_client.ios.IOSDriver
Command: [a66552aa-a4f0-41a9-a0bb-563f30eb8463, switchToContext {name=WEBVIEW_96144.11}]
Capabilities {appium:appWaitDuration: 120000, appium:appWaitPackage: 120000, appium:automationName: XCUITest, appium:bundleId: ***, appium:databaseEnabled: false, appium:deviceName: iPad Air (4th generation), appium:javascriptEnabled: true, appium:locationContextEnabled: false, appium:networkConnectionEnabled: false, appium:platformVersion: 17.2, appium:takesScreenshot: true, appium:udid: 7D55554F-CD0A-4B8E-8D6B-FB9..., appium:webStorageEnabled: false, platformName: IOS, sauce:options: {}}
Session ID: a66552aa-a4f0-41a9-a0bb-563f30eb8463

	at io.appium.java_client.remote.SupportsContextSwitching.context(SupportsContextSwitching.java:48)
	at com.sac.mobile.appiumlib.Appium.setWebViewContext(Appium.java:1573)
	at ***
	at ***
	at ***
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:848)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
	at org.testng.SuiteRunner.run(SuiteRunner.java:336)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
	at org.testng.TestNG.runSuites(TestNG.java:1114)
	at org.testng.TestNG.run(TestNG.java:1082)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
Caused by: org.openqa.selenium.WebDriverException: No such context found.
Build info: version: '4.25.0', revision: '8a8aea2337'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '14.7', java.version: '17.0.12'
Driver info: io.appium.java_client.ios.IOSDriver
Command: [a66552aa-a4f0-41a9-a0bb-563f30eb8463, switchToContext {name=WEBVIEW_96144.11}]
Capabilities {appium:appWaitDuration: 120000, appium:appWaitPackage: 120000, appium:automationName: XCUITest, appium:bundleId: com.sap.epm.fpa.CloudForAna..., appium:databaseEnabled: false, appium:deviceName: iPad Air (4th generation), appium:javascriptEnabled: true, appium:locationContextEnabled: false, appium:networkConnectionEnabled: false, appium:platformVersion: 17.2, appium:takesScreenshot: true, appium:udid: 7D55554F-CD0A-4B8E-8D6B-FB9..., appium:webStorageEnabled: false, platformName: IOS, sauce:options: {}}
Session ID: a66552aa-a4f0-41a9-a0bb-563f30eb8463
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:190)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:237)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:527)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:600)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:302)
	at io.appium.java_client.remote.SupportsContextSwitching.context(SupportsContextSwitching.java:45)
	... 31 more
```

this is the code setWebViewContext in Appium
```
Set<String> allContexts = getContexts();
		String contextAfterSwitch = null;
		for (String ctx : allContexts) {
			if (ctx.contains(MobileAutomationConstants.WEB_VIEW_CONTEXT_PREFIX) && !ctx.contains("WEBVIEW_chrome")) {
				setContext(ctx);
				if (driver instanceof AndroidDriver) {
					if (((SupportsContextSwitching) driver).context(ctx).getTitle().equals(webViewTitle))
						break;
				} else if (driver instanceof IOSDriver) {
					if (((SupportsContextSwitching) driver).context(ctx).getTitle().equals(webViewTitle))
						break;
				}

			}
		}
```

and inside setContext
```
((SupportsContextSwitching) driver).context(context);
```

Please let me know if you need more details.
