### ISSUE TITLE
Failed to switch back and forth between webview & native view

### ISSUE THREAD

**Issue by raycheung** [appium/appium#3177]
I'm using Protractor to drive Appium , and use wd-bridge to switch the context via the following function:

```
switch_context_to = (context) ->
  wdBrowser.contexts().then (contexts) ->
    throw "Unknown context: [#{context}] ! Available contexts: [#{contexts}]" unless context in contexts
    wdBrowser.context context
```

and protractor.conf.coffee is set with:

```
autoWebview: true
autoWebviewTimeout: 10
```

I'm able to switch the context from the webview to the `NATIVE_APP`, click through the buttons in the emulated camera view (of the android emulator), then switched back to the webview, the immediate next action is always fail with the following error:

```
debug: Proxying command to 127.0.0.1:9515
debug: Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session/50080a17d90e3b63eb84f3950b0e468b/execute_async","method":"POST","json":{"script":"try { return (function (selector, callback) {\n  var el = document.querySelector(selector);\n  try {\n    angular.element(el).injector().get('$browser').\n        notifyWhenNoOutstandingRequests(callback);\n  } catch (e) {\n    callback(e);\n  }\n}).apply(this, arguments); }\ncatch(e) { throw (e instanceof Error) ? e : new Error(e); }","args":["body"]}}
debug: Responding to client with error: {"status":28,"value":{"message":"A script did not complete before its timeout expired.","origValue":"asynchronous script timeout: result was not received in 0 seconds\n  (Session info: webview=)\n  (Driver info: chromedriver=2.10.267517,platform=Mac OS X 10.9.4 x86_64)"},"sessionId":"24d3ad6797e84db1c395ad7820dd7100"}
info: <-- POST /wd/hub/session/24d3ad6797e84db1c395ad7820dd7100/execute_async 500 345.137 ms - 320 
F

Failures:

  1) An new customer signs up and applies the first loan application
   Message:
     ScriptTimeoutError: A script did not complete before its timeout expired.
   Stacktrace:
     ScriptTimeoutError: A script did not complete before its timeout expired.
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:919:16
    at process._tickCallback (node.js:419:13)
```

**Comment by bhawani2008** [comment]
Hello,
I am using protractor to automate an Hybrid mobile app. I am facing issues in automating Date picker wheel, as it is not recognizing the appium xpath's or classname. Kindly Advise.... 
I am not able to switch to Native App mode from Webview mode...

**Comment by jlipps** [comment]
We now retain a map of chromedrivers and re-use them
