### ISSUE TITLE
Selendroid element "clear" does not work on Android 4.4 Emulators

### ISSUE THREAD

**Issue by filmaj** [appium/appium#3186]
I am running a [selendroid-based test](http://github.com/filmaj/appium-test/tests/android-selendroid.js) against appium v0.18.2.

I'm running against an x86-based Android 4.4.2 emulator (the Nexus 4 device profile).

It looks like any attempts at calling `clear` on an input element fail at the selendroid level:

```
debug: Appium request initiated at /wd/hub/session/c7ae3b3a-8397-4b5a-e702-8bb6b322ca88/element/a622975b-e63d-ace0-2634-f28459ae81fb/clear
debug: Request received with params: {}
debug: Proxying command to localhost:8080
info: Making http request with opts: {"url":"http://localhost:8080/wd/hub/session/c7ae3b3a-8397-4b5a-e702-8bb6b322ca88/element/a622975b-e63d-ace0-2634-f28459ae81fb/clear","method":"POST","json":{}}
info: [SELENDROID] 0
info: [SELENDROID] Clear element command
info: [SELENDROID] {"ELEMENT":":wdc:1405971686301"}
info: [SELENDROID] {"ELEMENT":":wdc:1405971686301"}
info: [SELENDROID] {"status":12,"value":{"message":"Element is not currently interactable and may not be manipulated"}}
info: [SELENDROID] error while clearing the element:
info: [SELENDROID ERR] {"message":"Element is not currently interactable and may not be manipulated"}
info: [SELENDROID ERR]  at io.selendroid.server.model.SelendroidWebDriver.executeAtom(SelendroidWebDriver.java:199)
info: [SELENDROID ERR]  at io.selendroid.server.model.SelendroidWebDriver.executeAtom(SelendroidWebDriver.java:169)
info: [SELENDROID ERR]  at io.selendroid.server.model.AndroidWebElement.clear(AndroidWebElement.java:286)
info: [SELENDROID ERR]  at io.selendroid.server.handler.ClearElement.handle(ClearElement.java:42)
info: [SELENDROID ERR]  at io.selendroid.server.AndroidServlet.handleRequest(AndroidServlet.java:286)
info: [SELENDROID ERR]  at io.selendroid.server.BaseServlet.handleHttpRequest(BaseServlet.java:70)
info: [SELENDROID ERR]  at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
info: [SELENDROID ERR]  at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)
info: [SELENDROID ERR]  at io.selendroid.server.inspector.InspectorServlet.handleHttpRequest(InspectorServlet.java:78)
info: [SELENDROID ERR]  at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
info: [SELENDROID ERR]  at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)
info: [SELENDROID ERR]  at org.webbitserver.handler.PathMatchHandler.handleHttpRequest(PathMatchHandler.java:33)
info: [SELENDROID ERR]  at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
info: [SELENDROID ERR]  at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)
info: [SELENDROID ERR]  at org.webbitserver.handler.DateHeaderHandler.handleHttpRequest(DateHeaderHandler.java:21)
info: [SELENDROID ERR]  at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
info: [SELENDROID ERR]  at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)
info: [SELENDROID ERR]  at org.webbitserver.handler.ServerHeaderHandler.handleHttpRequest(ServerHeaderHandler.java:25)
info: [SELENDROID ERR]  at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
info: [SELENDROID ERR]  at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:67)
info: [SELENDROID ERR]  at org.webbitserver.netty.NettyHttpChannelHandler$2.run(NettyHttpChannelHandler.java:72)
info: [SELENDROID ERR]  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
info: [SELENDROID ERR]  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
info: Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command.","origValue":"{\"message\":\"Element is not currently interactable and may not be manipulated\"}\nio.selendroid.exceptions.SelendroidException: {\"message\":\"Element is not currently interactable and may not be manipulated\"}\n\tat io.selendroid.server.model.SelendroidWebDriver.executeAtom(SelendroidWebDriver.java:199)\n\tat io.selendroid.server.model.SelendroidWebDriver.executeAtom(SelendroidWebDriver.java:169)\n\tat io.selendroid.server.model.AndroidWebElement.clear(AndroidWebElement.java:286)\n\tat io.selendroid.server.handler.ClearElement.handle(ClearElement.java:42)\n\tat io.selendroid.server.AndroidServlet.handleRequest(AndroidServlet.java:286)\n\tat io.selendroid.server.BaseServlet.handleHttpRequest(BaseServlet.java:70)\n\tat org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)\n\tat org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)\n\tat io.selendroid.server.inspector.InspectorServlet.handleHttpRequest(InspectorServlet.java:78)\n\tat org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)\n\tat org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)\n\tat org.webbitserver.handler.PathMatchHandler.handleHttpRequest(PathMatchHandler.java:33)\n\tat org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)\n\tat org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)\n\tat org.webbitserver.handler.DateHeaderHandler.handleHttpRequest(DateHeaderHandler.java:21)\n\tat org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)\n\tat org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)\n\tat org.webbitserver.handler.ServerHeaderHandler.handleHttpRequest(ServerHeaderHandler.java:25)\n\tat org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)\n\tat org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:67)\n\tat org.webbitserver.netty.NettyHttpChannelHandler$2.run(NettyHttpChannelHandler.java:72)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)\n\tat java.lang.Thread.run(Thread.java:841)\n"},"sessionId":"c7ae3b3a-8397-4b5a-e702-8bb6b322ca88"}
POST /wd/hub/session/c7ae3b3a-8397-4b5a-e702-8bb6b322ca88/element/a622975b-e63d-ace0-2634-f28459ae81fb/clear 500 70ms - 2.39kb
```

**Comment by 0x1mason** [comment]
Reproducible on Samsung S4 real device.

**Comment by 0x1mason** [comment]
Here's a workaround example using the Python client:
```python
def clearText(el):
    sz = len(el.get_attribute('value')) # this works for webview, text does not, but may need to switch
    s = ""
    for i in range(0, sz):
        s += Keys.BACKSPACE
    el.send_keys(s)
```

**Comment by jlipps** [comment]
text clearing should now work across android devices
