### ISSUE TITLE
Application getting crashed while getting the page details in appium inspector

### ISSUE THREAD

**Issue by sjrjanardhana** [appium/appium#3421]
Hi, i am trying to get the screenshot and and objects of the application, all of sudden application getting crashed, it works absolutely fine with other pages in the app. please find the log below

2014-08-19T07:18:20.614Z - info: --> GET /wd/hub/session/96b24319-09c7-45d0-b1f8-857298cb6142/source {}

2014-08-19T07:18:20.615Z - debug: Appium request initiated at /wd/hub/session/96b24319-09c7-45d0-b1f8-857298cb6142/source

2014-08-19T07:18:20.615Z - debug: Request received with params: {}
2014-08-19T07:18:20.615Z - debug: Pushing command to appium work queue: "au.mainApp().getTreeForXML()"
2014-08-19T07:18:20.616Z - debug: Sending command to instruments: au.mainApp().getTreeForXML()
2014-08-19T07:18:20.616Z - debug: Sending command to instruments: au.mainApp().getTreeForXML()

2014-08-19T07:18:21.551Z - debug: [INST] 2014-08-19 07:18:21 +0000 Debug: Got new command 9 from instruments: au.mainApp().getTreeForXML()
       

2014-08-19T07:18:21.553Z - debug: [INST] 2014-08-19 07:18:21 +0000 Debug: evaluating au.mainApp().getTreeForXML()
       

2014-08-19T07:18:46.173Z - info: --> GET /wd/hub/status {}

2014-08-19T07:18:46.173Z - debug: Appium request initiated at /wd/hub/status

2014-08-19T07:18:46.174Z - info: <-- GET /wd/hub/status 200 1.720 ms - 155 {"status":0,"value":{"build":{"version":"1.2.0","revision":"e53f49c706a25242e66d36685c268b599cc18da5"}},"sessionId":"96b24319-09c7-45d0-b1f8-857298cb6142"}

2014-08-19T07:18:46.173Z - debug: Request received with params: {}
2014-08-19T07:18:46.173Z - debug: Responding to client with success: {"status":0,"value":{"build":{"version":"1.2.0","revision":"e53f49c706a25242e66d36685c268b599cc18da5"}},"sessionId":"96b24319-09c7-45d0-b1f8-857298cb6142"}

2014-08-19T07:18:52.056Z - debug: [INST] 2014-08-19 07:18:52 +0000 Debug: evaluation finished
       

2014-08-19T07:18:52.059Z - debug: [INST] 2014-08-19 07:18:52 +0000 Debug: Result is not protocol compliant, wrapping
       

2014-08-19T07:18:52.063Z - debug: [INST] 2014-08-19 07:18:52 +0000 Debug: Running system command #10: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":{"UIAApplication":{"@":{"name":"Anywhere","label":"Anywhere","value":null,"dom"...
       

2014-08-19T07:18:52.122Z - debug: Socket data received (8192 bytes)

2014-08-19T07:18:52.125Z - debug: Socket data received (8192 bytes)

2014-08-19T07:18:52.134Z - info: <-- GET /wd/hub/session/96b24319-09c7-45d0-b1f8-857298cb6142/source 200 31520.676 ms - 23211 {"status":0,"value":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<AppiumAUT>\n    <UIAApplication name=\"Anywhere\" label=\"Anywhere\" value=\"\" dom=\"\" enabled=\"true\" valid=\"true\" visible=\"true\" hint=\"\" path=\"/0\" x=\"0\" y=\"20\" width=\"1024\" height=\"748\">\n        <UIAWindow name=\"\" label=\"\" value=\"\" dom=\"\" enabled=\"true\" valid=\"true\" visible=\"true\" hint=\"\" path=\"/0/0\" x=\"0\" y=\"0\" width=\"1024\" height=\"768\">\n            <UIANavigationBar name=\"DAMediaCardView\" label=\"\" value=\"\" dom=\"\" enabled=\"true\" valid=\"true\" visible=\"true\" hint=\"\" path=\"/0/0/0\" x=\"0\" y=\"20\" width=\"1024\" height=\"44\">\n                <UIAImage name=\"\" label=\"\" value=\"\" dom=\"\" enabled=\"true\" valid=\"true\" visible=\"false\" hint=\"\" path=\"/0/0/0/0\" x=\"0\" y=\"0\" width=\"1024\" height=\"64\">\n                    <UIAImage name=\"\" label=\"\" value=\"\" dom=\"\" enabled=\"true\" valid=\"true\" visible=\"false\" hint=\"\" path=\"/0/0/0/0/0\" x=\"0\" y=\"64\" width=\"1024\" height=\"0.5\">\n                    </UIAImage>\n                </UIAImage>\n                <UIAButton name=\"UINavigation...","sessionId":"96b24319-09c7-45d0-b1f8-857298cb6142"}

2014-08-19T07:18:52.125Z - debug: Socket data received (3774 bytes)
2014-08-19T07:18:52.126Z - debug: Socket data being routed.
2014-08-19T07:18:52.126Z - debug: Got result from instruments: {"status":0,"value":{"UIAApplication":{"@":{"name":"Anywhere","label":"Anywhere","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0","x":0,"y":20,"width":1024,"height":748},">":[{"UIAWindow":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,
2014-08-19T07:18:52.133Z - debug: Responding to client with success: {"status":0,"value":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<AppiumAUT>\n    <UIAApplication name=\"Anywhere\" label=\"Anywhere\" value=\"\" dom=\"\" enabled=\"true\" valid=\"true\" visible=\"true\" hint=\"\" path=\"/0\" x=\"0\" y=\"20\" width=\"1024\" height=\"748\">\n        <UIAWindow name=\"\" label=\"\" value=\"\" dom=\"\" enabled=\"true\" valid=\"true\" visible=\"true\" hint=\"\" path=\"/0/0\" x=\"0\" y=\"0\" width=\"1024\" height=\"768\">\n            <UIANavigationBar name=\"DAMediaCardView\" label=\"\" value=\"\" dom=\"\" enabled=\"true\" valid=\"true\" visible=\"true\" hint=\"\" path=\"/0/0/0\" x=\"0\" y=\"20\" width=\"1024\" height=\"44\">\n                <UIAImage name=\"\" label=\"\" value=\"\" dom=\"\" enabled=\"true\" valid=\"true\" visible=\"false\" hint=\"\" path=\"/0/0/0/0\" x=\"0\" y=\"0\" width=\"1024\" height=\"64\">\n                    <UIAImage name=\"\" label=\"\" value=\"\" dom=\"\" enabled=\"true\" valid=\"true\" visible=\"false\" hint=\"\" path=\"/0/0/0/0/0\" x=\"0\" y=\"64\" width=\"1024\" height=\"0.5\">\n                    </UIAImage>\n                </UIAImage>\n                <UIAButton name=\"UINavigation...","sessionId":"96b24319-09c7-45d0-b1f8-857298cb6142"}

2014-08-19T07:18:52.136Z - info: --> GET /wd/hub/session/96b24319-09c7-45d0-b1f8-857298cb6142/screenshot {}

2014-08-19T07:18:52.137Z - debug: Appium request initiated at /wd/hub/session/96b24319-09c7-45d0-b1f8-857298cb6142/screenshot
2014-08-19T07:18:52.137Z - debug: Request received with params: {}
2014-08-19T07:18:52.137Z - debug: Pushing command to appium work queue: "au.getScreenOrientation()"
2014-08-19T07:18:52.138Z - debug: Sending command to instruments: au.getScreenOrientation()
2014-08-19T07:18:52.138Z - debug: Sending command to instruments: au.getScreenOrientation()

2014-08-19T07:18:52.316Z - debug: [INST] 2014-08-19 07:18:52 +0000 Fail: The target application appears to have died
       

2014-08-19T07:18:54.415Z - debug: [INST] Instruments Trace Complete (Duration : 271.946411s; Output : /Applications/Appium.app/Contents/Resources/node_modules/appium/instrumentscli0.trace)
       

2014-08-19T07:18:54.471Z - debug: [INSTSERVER] Instruments exited with code 0

2014-08-19T07:18:54.471Z - debug: Cleaning up after instruments exit
2014-08-19T07:18:54.472Z - debug: Instruments exited unexpectedly
2014-08-19T07:18:54.472Z - debug: Closing socket server.

2014-08-19T07:18:54.473Z - debug: Instruments socket server was closed
2014-08-19T07:18:54.474Z - debug: Pushing command to appium work queue: "au.capture('screenshot6d37f95e-46d9-4ebe-b47c-f33f61919d05')"
2014-08-19T07:18:54.477Z - debug: Deleted tracedir we heard about from instruments (/Applications/Appium.app/Contents/Resources/node_modules/appium/instrumentscli0.trace)
2014-08-19T07:18:54.478Z - debug: Stopping iOS log capture
2014-08-19T07:18:54.478Z - debug: Killing the simulator process

2014-08-19T07:18:54.498Z - debug: Killing any other simulator daemons

2014-08-19T07:18:54.539Z - debug: Cleaning app state.

2014-08-19T07:18:54.693Z - debug: Deleted /Users/slinger/Library/Application Support/iPhone Simulator/7.1/Applications

2014-08-19T07:18:54.693Z - debug: Deleted /Users/slinger/Library/Application Support/iPhone Simulator/7.1/Library/TCC

2014-08-19T07:18:54.694Z - debug: Deleted /Users/slinger/Library/Application Support/iPhone Simulator/7.1/Library/Caches/locationd
2014-08-19T07:18:54.696Z - debug: Deleted /Users/slinger/Library/Application Support/iPhone Simulator/7.1/Media
2014-08-19T07:18:54.697Z - debug: Deleted /Users/slinger/Library/Application Support/iPhone Simulator/7.1/Library/Keychains
2014-08-19T07:18:54.698Z - debug: Cleaning up appium session

2014-08-19T07:19:00.798Z - error: uncaughtException: undefined is not a function date=Tue Aug 19 2014 12:49:00 GMT+0530 (IST), pid=24178, uid=501, gid=20, cwd=/Applications/Appium.app/Contents/Resources/node_modules/appium, execPath=/Applications/Appium.app/Contents/Resources/node/bin/node, version=v0.10.29, argv=[/Applications/Appium.app/Contents/Resources/node/bin/node, /Applications/Appium.app/Contents/Resources/node_modules/appium/lib/server/main.js, --address, 127.0.0.1, --port, 4723, --command-timeout, 7200, --session-override, --pre-launch, --log-timestamp, --webhook, localhost:9876, --app, /Users/slinger/Library/Developer/Xcode/DerivedData/Dish-iPad-arndvvltxxvxdjavbfgdrsakyvuh/Build/Products/Debug-iphonesimulator/DISH-iPad.app, --device-name, iPad Retina, --launch-timeout, 90000, --native-instruments-lib], rss=92524544, heapTotal=61307648, heapUsed=32872064, loadavg=[1.98095703125, 1.72119140625, 1.62548828125], uptime=227996, trace=[column=11, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios-controller.js, function=null, line=1154, method=null, native=false, column=28, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js, function=null, line=709, method=null, native=false, column=24, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios-controller.js, function=null, line=1144, method=null, native=false, column=20, file=fs.js, function=null, line=207, method=null, native=false, column=15, file=fs.js, function=Object.oncomplete, line=107, method=oncomplete, native=false], stack=[TypeError: undefined is not a function,     at /Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios-controller.js:1154:11,     at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:709:28,     at /Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios-controller.js:1144:24,     at fs.js:207:20,     at Object.oncomplete (fs.js:107:15)]

**Comment by Jonahss** [comment]
Hm. so I know this is silly but, how about on the latest version now?

**Comment by sjrjanardhana** [comment]
It looks like some issue within the instruments itself. i have simulated the same scenarios with instruments tool and response same. Application is getting killed by the system process and instruments is getting exited with error code 0

**Comment by Jonahss** [comment]
Ah. Well if it's due to an instruments error, there's not much we can do right now :(
A potential workaround would be to use the UIAutomation locator strategy to find elements using javascript UIAutomation commands, and traverse the tree yourself.

**Comment by Jitu1888** [comment]
Same issue with UIAUTOMATOR
