### ISSUE TITLE
Unable to hide keyboard using built-in method 'hide_keyboard'. Selenium::WebDriver::Error::UnknownError Exception: ERROR running Appium command: Object [object Object] has no method 'hideKeyboard'

### ISSUE THREAD

**Issue by kirillzh** [appium/appium#4012]
**Language:** Ruby
**Appium server version:** v1.3.3-pre
**Device:** HTC One M8, Android 4.4.4.

Calling hide_method within **native** context and getting next exception:
`Selenium::WebDriver::Error::UnknownError Exception: ERROR running Appium command: Object [object Object] has no method 'hideKeyboard'`

**Server Log:**
`info: --> POST /wd/hub/session/8d84118d-10af-868a-9525-cca6d2706b2b/appium/device/hide_keyboard {"strategy":"tapOutside"}
info: <-- POST /wd/hub/session/8d84118d-10af-868a-9525-cca6d2706b2b/appium/device/hide_keyboard 500 0.845 ms - 105
TypeError: Object [object Object] has no method 'hideKeyboard'
    at Object.exports.hideKeyboard [as handle] (/Users/kirill/appium/lib/server/controller.js:649:14)
    at next_layer (/Users/kirill/appium/node_modules/express/lib/router/route.js:113:13)
    at Route.dispatch (/Users/kirill/appium/node_modules/express/lib/router/route.js:117:5)
    at /Users/kirill/appium/node_modules/express/lib/router/index.js:222:24
    at param (/Users/kirill/appium/node_modules/express/lib/router/index.js:307:14)
    at param (/Users/kirill/appium/node_modules/express/lib/router/index.js:323:14)
    at Function.proto.process_params (/Users/kirill/appium/node_modules/express/lib/router/index.js:367:3)
    at next (/Users/kirill/appium/node_modules/express/lib/router/index.js:216:19)
    at next (/Users/kirill/appium/node_modules/express/lib/router/index.js:180:38)
    at next (/Users/kirill/appium/node_modules/express/lib/router/index.js:180:38)`

**Comment by imurchie** [comment]
Closing for lack of action.
