### ISSUE TITLE
Got error "error: [REMOTE] Could not connect to WebKitRemoteDebugger server"

### ISSUE THREAD

**Issue by scnymc** [appium/appium#4112]
I want to test safari on real device (ipad), below are my configurations:
1. Mac os: 10.10; xCode: 6.1
2. Appium 1.3.1 (install using npm)
3. SafariLauncher, I got the source from github and sign it with my developer signature, and has installed to my iPad
4. iOS-webkit-debug-proxy, I have installed it using brew command, and run it using command "iOS_webkit_debug_proxy" (i'm not sure whether this command is right)
5. My capabilities:
capabilities.setCapability("platformName", "iOS");
capabilities.setCapability("platformVersion", "7.1.2");
capabilities.setCapability("deviceName", "iPad");
capabilities.setCapability("udid","xxxxx");
capabilities.setCapability("app", "com.sas.safarilauncher");
driver = new AppiumDriver(new URL("http://127.0.0.1:4723/wd/hub"),capabilities);
6. My test cases:
e.g. driver.findElement(By.xpath(//xxx/xx/xxx)).click();

When the test case is running, the 'SafariLauncher' is launched, and the mobileSafari is opened, but from the log I notice that "error: [REMOTE] Could not connect to WebKitRemoteDebugger server".

and the test case is not excited, e.g. I could not see the click method on screen, seems the device is not receive the command.

So, is it caused by the iOS_webkit_debug_proxy? is it a bug of appium or others?

**Comment by adigrinvald** [comment]
The exact same thing... any ideas on how to solve this?

**Comment by sebv** [comment]
try with `./bin/ios-webkit-debug-proxy-launcher.js -c <UDID>:27753 -d`

**Comment by adigrinvald** [comment]
Do I need it even if I don't use safari in my tests ? I am running tests on a native app with Ios real device and it used to run but since yesterday I started getting this safarilauncher errors.does it make any sense ?

**Comment by Rakeshvallabhaneni** [comment]
@sebv @adigrinvald  Even i am facing the issue 1.3.3 
1) If the app(Native) already installed in the device .and i click on inspector button in the appium here i am able to launch the app and screen shot also showing in the inspetor but unable to locate element in that.

error: [REMOTE] Could not connect to WebKitRemoteDebugger server

info: [debug] [REMOTE] Getting WebKitRemoteDebugger pageArray
info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command. (Original error: connect ECONNREFUSED)","code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","origValue":"connect ECONNREFUSED"},"sessionId":"834ca544-77f4-498f-8232-0a4f788e9dca"}
info: <-- GET /wd/hub/session/834ca544-77f4-498f-8232-0a4f788e9dca/contexts 500 7.407 ms - 293 


2)If the app is not installed in the device when i click on inspector it should install and launch but 

error: Failed to start an Appium session, err was: Error: Unable to install [com.esi-estech.ditto] to device with id [db683f62be2549a89f2f4a0012239a9b947da62e]. Error [Error: Command failed: Assertion failed: (access(app_path, F_OK) == 0), function main, file fruitstrap.c, line 718.
]

info: [debug] Error: Unable to install [com.esi-estech.ditto] to device with id [db683f62be2549a89f2f4a0012239a9b947da62e]. Error [Error: Command failed: Assertion failed: (access(app_path, F_OK) == 0), function main, file fruitstrap.c, line 718.
]
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/common.js:147:10
    at ChildProcess.exithandler (child_process.js:652:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Socket.<anonymous> (child_process.js:969:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Unable to install [com.esi-estech.ditto] to device with id [db683f62be2549a89f2f4a0012239a9b947da62e]. Error [Error: Command failed: Assertion failed: (access(app_path, F_OK) == 0), function main, file fruitstrap.c, line 718.\n])","origValue":"Unable to install [com.esi-estech.ditto] to device with id [db683f62be2549a89f2f4a0012239a9b947da62e]. Error [Error: Command failed: Assertion failed: (access(app_path, F_OK) == 0), function main, file fruitstrap.c, line 718.\n]"},"sessionId":null}

info: <-- POST /wd/hub/session 500 7046.653 ms - 578 


Please help me around these problem.

Thanks..

**Comment by moizjv** [comment]
@Rakeshvallabhaneni @scnymc can you try steps mentioned in [documentation](https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/ios-webkit-debug-proxy.md) here to see if it fixes the issue?

**Comment by Jonahss** [comment]
@adigrinvald you shouldn't need the webkit-debug-proxy just to test native apps without webviews.

**Comment by Jonahss** [comment]
Closing due to inactivity. Please comment here if there's still an issue.

**Comment by shadeimi** [comment]
2015-05-18 13:39:57:517 - info: Welcome to Appium v1.4.0 (REV 8f63e2f91ef7907aed8bda763f4e5ca08e86970a)
2015-05-18 13:39:57:520 - info: Appium REST http interface listener started on localhost:4736
2015-05-18 13:39:57:523 - info: [debug] Non-default server args: {"udid":"198d79290272ed914232da7c31885ff704228ce3","address":"localhost","port":4736,"bootstrapPort":2251,"logTimestamp":true,"logNoColors":true,"nodeconfig":"/var/folders/vm/c1lc7w594t91zbdxrb7ytjhw0000gn/T/tmphjr_eQ","chromeDriverPort":9516}
2015-05-18 13:39:57:524 - info: Console LogLevel: debug
2015-05-18 13:39:57:525 - info: [debug] starting auto register thread for grid. Will try to register every 5000 ms.
2015-05-18 13:40:02:548 - info: [debug] Appium successfully registered with the grid on localhost:4444
Device arrived: Bus 020 Device 007: ID 05ac:0250
Device arrived: Bus 020 Device 005: ID 05e3:0608
Device arrived: Bus 020 Device 002: ID 05ac:1006
2015-05-18 13:40:08:554 - info: --> GET /wd/hub/status {}
2015-05-18 13:40:08:556 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.0","revision":"8f63e2f91ef7907aed8bda763f4e5ca08e86970a"}}}
2015-05-18 13:40:08:560 - info: <-- GET /wd/hub/status 200 5.948 ms - 104 {"status":0,"value":{"build":{"version":"1.4.0","revision":"8f63e2f91ef7907aed8bda763f4e5ca08e86970a"}}}
2015-05-18 13:40:14:568 - info: --> GET /wd/hub/status {}
2015-05-18 13:40:14:568 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.0","revision":"8f63e2f91ef7907aed8bda763f4e5ca08e86970a"}}}
2015-05-18 13:40:14:570 - info: <-- GET /wd/hub/status 200 2.271 ms - 104 {"status":0,"value":{"build":{"version":"1.4.0","revision":"8f63e2f91ef7907aed8bda763f4e5ca08e86970a"}}}
Device arrived: Bus 020 Device 001: ID 05e3:0608
Device arrived: Bus 020 Device 129: ID 05ac:8007
Device arrived: Bus 021 Device 128: ID 05ac:8007
2015-05-18 13:40:20:574 - info: --> GET /wd/hub/status {}
2015-05-18 13:40:20:574 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.0","revision":"8f63e2f91ef7907aed8bda763f4e5ca08e86970a"}}}
2015-05-18 13:40:20:575 - info: <-- GET /wd/hub/status 200 0.933 ms - 104 {"status":0,"value":{"build":{"version":"1.4.0","revision":"8f63e2f91ef7907aed8bda763f4e5ca08e86970a"}}}
2015-05-18 13:40:21:425 - info: --> POST /wd/hub/session {"desiredCapabilities":{"platformVersion":"8.3","browserName":"Safari","autoWebview":"True","id":"DMPM4NSFF4YD","udid":"198d79290272ed914232da7c31885ff704228ce3","platformName":"iOS","deviceName":"iPad Air QA"}}
2015-05-18 13:40:21:426 - info: Client User-Agent string: Python-urllib/2.7
2015-05-18 13:40:21:426 - warn: Converting cap autoWebview from string to boolean. This might cause unexpected behavior.
2015-05-18 13:40:21:427 - info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : id
2015-05-18 13:40:21:428 - info: [debug] Configuring Safari session
2015-05-18 13:40:21:429 - info: [debug] Using local .zip from command line: /Users/shadeimi/git/appium/build/SafariLauncher/SafariLauncher.zip
2015-05-18 13:40:21:429 - info: [debug] Copying local zip to tmp dir
2015-05-18 13:40:21:437 - info: [debug] /Users/shadeimi/git/appium/build/SafariLauncher/SafariLauncher.zip copied to /var/folders/vm/c1lc7w594t91zbdxrb7ytjhw0000gn/T/115418-9347-3sfdpa/appium-app.zip
2015-05-18 13:40:21:471 - info: [debug] Unzipping /var/folders/vm/c1lc7w594t91zbdxrb7ytjhw0000gn/T/115418-9347-3sfdpa/appium-app.zip
2015-05-18 13:40:21:471 - info: [debug] Testing zip archive: /var/folders/vm/c1lc7w594t91zbdxrb7ytjhw0000gn/T/115418-9347-3sfdpa/appium-app.zip
2015-05-18 13:40:21:498 - info: [debug] Zip archive tested clean
2015-05-18 13:40:21:533 - info: [debug] Unzip successful
2015-05-18 13:40:21:534 - info: [debug] Using locally extracted app: /var/folders/vm/c1lc7w594t91zbdxrb7ytjhw0000gn/T/115418-9347-3sfdpa/node_modules/safari-launcher/build/Release-iphoneos/SafariLauncher.app
2015-05-18 13:40:21:535 - info: [debug] Creating new appium session d67afae0-1e08-4d4d-b08e-b9d2e2664aa6
2015-05-18 13:40:21:536 - info: [debug] Removing any remaining instruments sockets
2015-05-18 13:40:21:537 - info: [debug] Cleaned up instruments socket /tmp/instruments_sock
2015-05-18 13:40:21:537 - info: [debug] Auto-detecting iOS udid...
2015-05-18 13:40:21:537 - info: [debug] Not auto-detecting udid, running on sim
2015-05-18 13:40:21:538 - info: [debug] Could not parse plist file (as binary) at /var/folders/vm/c1lc7w594t91zbdxrb7ytjhw0000gn/T/115418-9347-3sfdpa/node_modules/safari-launcher/build/Release-iphoneos/SafariLauncher.app/en.lproj/Localizable.strings
2015-05-18 13:40:21:538 - info: Will try to parse the plist file as XML
2015-05-18 13:40:21:538 - info: [debug] Could not parse plist file (as XML) at /var/folders/vm/c1lc7w594t91zbdxrb7ytjhw0000gn/T/115418-9347-3sfdpa/node_modules/safari-launcher/build/Release-iphoneos/SafariLauncher.app/en.lproj/Localizable.strings
2015-05-18 13:40:21:539 - warn: Could not parse app Localizable.strings assuming it doesn't exist
2015-05-18 13:40:21:539 - info: [debug] Getting bundle ID from app
2015-05-18 13:40:21:542 - info: [debug] Parsed app Info.plist (as binary)
2015-05-18 13:40:21:542 - info: [debug] Creating instruments
2015-05-18 13:40:21:543 - info: [debug] Preparing uiauto bootstrap
2015-05-18 13:40:21:543 - info: [debug] Dynamic bootstrap dir: /Users/shadeimi/Library/Application Support/appium/bootstrap
2015-05-18 13:40:21:544 - info: [debug] Dynamic env: {"nodePath":"/usr/local/Cellar/node/0.12.2_1/bin/node","commandProxyClientPath":"/Users/shadeimi/git/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"grouped"}
...5-05-18 13:40:21:548 - info: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
2015-05-18 13:40:21:548 - info: [debug] Dynamic bootstrap path: /Users/shadeimi/Library/Application Support/appium/bootstrap/bootstrap-48b203b4ed0e08b8.js
2015-05-18 13:40:21:551 - info: [debug] Reusing dynamic bootstrap: /Users/shadeimi/Library/Application Support/appium/bootstrap/bootstrap-48b203b4ed0e08b8.js
2015-05-18 13:40:21:553 - info: [debug] Attempting iOS device log capture via libimobiledevice idevicesyslog
2015-05-18 13:40:21:721 - info: [debug] Creating iDevice object with udid 198d79290272ed914232da7c31885ff704228ce3
2015-05-18 13:40:26:041 - info: [debug] Starting command proxy.
2015-05-18 13:40:26:043 - info: [debug] Instruments socket server started at /tmp/instruments_sock
2015-05-18 13:40:26:043 - info: [debug] Starting instruments
2015-05-18 13:40:26:121 - info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
2015-05-18 13:40:26:121 - info: Launching instruments
2015-05-18 13:40:26:130 - info: [debug] Attempting to run app on real device with UDID 198d79290272ed914232da7c31885ff704228ce3
2015-05-18 13:40:26:130 - info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w 198d79290272ed914232da7c31885ff704228ce3 com.bytearc.SafariLauncher -e UIASCRIPT "/Users/shadeimi/Library/Application Support/appium/bootstrap/bootstrap-48b203b4ed0e08b8.js" -e UIARESULTSPATH /tmp/appium-instruments
2015-05-18 13:40:26:131 - info: [debug] And extra without-delay env: {}
2015-05-18 13:40:26:131 - info: [debug] And launch timeouts (in ms): {"global":90000}
2015-05-18 13:40:26:579 - info: --> GET /wd/hub/status {}
2015-05-18 13:40:26:580 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.0","revision":"8f63e2f91ef7907aed8bda763f4e5ca08e86970a"},"isShuttingDown":false},"sessionId":"d67afae0-1e08-4d4d-b08e-b9d2e2664aa6"}
2015-05-18 13:40:26:580 - info: <-- GET /wd/hub/status 200 1.207 ms - 178 {"status":0,"value":{"build":{"version":"1.4.0","revision":"8f63e2f91ef7907aed8bda763f4e5ca08e86970a"},"isShuttingDown":false},"sessionId":"d67afae0-1e08-4d4d-b08e-b9d2e2664aa6"}
2015-05-18 13:40:26:781 - info: [debug] [INST STDERR] 2015-05-18 15:40:26.781 instruments[9415:35692] WebKit Threading Violation - initial use of WebKit from a secondary thread.
2015-05-18 13:40:28:034 - info: Instruments is ready to receive commands
2015-05-18 13:40:28:034 - info: [debug] Instruments launched. Starting poll loop for new commands.
2015-05-18 13:40:28:035 - info: [debug] Setting bootstrap config keys/values
2015-05-18 13:40:28:035 - info: [debug] Pushing command to appium work queue: "target = $.target();\nau = $;\n$.isVerbose = true;\n"
2015-05-18 13:40:28:037 - info: [debug] Socket data received (2 bytes)
2015-05-18 13:40:28:038 - info: [debug] Socket data being routed.
2015-05-18 13:40:28:038 - info: [debug] Sending command to instruments: target = $.target();
au = $;
$.isVerbose = true;

2015-05-18 13:40:29:078 - info: [debug] [INST] 2015-05-18 13:39:43 +0000 Debug: evaluation finished
2015-05-18 13:40:29:079 - info: [debug] [INST] 2015-05-18 13:39:43 +0000 Debug: responding with:
2015-05-18 13:40:29:080 - info: [debug] [INST] 2015-05-18 13:39:43 +0000 Debug: Running system command #1: /usr/local/Cellar/node/0.12.2_1/bin/node /Users/shadeimi/git/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":true}...
2015-05-18 13:40:29:128 - info: [debug] Socket data received (27 bytes)
2015-05-18 13:40:29:129 - info: [debug] Socket data being routed.
2015-05-18 13:40:29:129 - info: [debug] Got result from instruments: {"status":0,"value":true}
2015-05-18 13:40:29:129 - info: [debug] Not setting initial orientation because we're on SafariLauncher
2015-05-18 13:40:29:129 - info: [debug] Setting auto webview
2015-05-18 13:40:29:129 - info: [debug] Waiting for 6000 ms before navigating to view.
2015-05-18 13:40:32:586 - info: --> GET /wd/hub/status {}
2015-05-18 13:40:32:586 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.0","revision":"8f63e2f91ef7907aed8bda763f4e5ca08e86970a"},"isShuttingDown":false},"sessionId":"d67afae0-1e08-4d4d-b08e-b9d2e2664aa6"}
2015-05-18 13:40:32:587 - info: <-- GET /wd/hub/status 200 0.982 ms - 178 {"status":0,"value":{"build":{"version":"1.4.0","revision":"8f63e2f91ef7907aed8bda763f4e5ca08e86970a"},"isShuttingDown":false},"sessionId":"d67afae0-1e08-4d4d-b08e-b9d2e2664aa6"}
2015-05-18 13:40:35:134 - info: [debug] Navigating to most recently opened webview
2015-05-18 13:40:35:136 - info: [debug] [REMOTE] Getting WebKitRemoteDebugger pageArray
2015-05-18 13:40:35:139 - warn: Could not find any webviews yet, refreshing/retrying
2015-05-18 13:40:35:643 - info: [debug] [REMOTE] Getting WebKitRemoteDebugger pageArray
2015-05-18 13:40:35:645 - warn: Could not find any webviews yet, refreshing/retrying
2015-05-18 13:40:36:147 - info: [debug] [REMOTE] Getting WebKitRemoteDebugger pageArray
2015-05-18 13:40:36:148 - warn: Could not find any webviews yet, refreshing/retrying
2015-05-18 13:40:36:652 - info: [debug] [REMOTE] Getting WebKitRemoteDebugger pageArray
2015-05-18 13:40:36:653 - warn: Could not find any webviews yet, refreshing/retrying
2015-05-18 13:40:37:159 - info: [debug] [REMOTE] Getting WebKitRemoteDebugger pageArray
2015-05-18 13:40:37:160 - warn: Could not find any webviews yet, refreshing/retrying

**Comment by Uvarajkrishna-CSAA** [comment]
Facing a same issue regularly but in a rare occurence it identified a webview and proceeded further.
Appium version: 1.4.0
iOS Device: iPad , OS Version: 8.1

Log:
2015-06-22 16:30:08:474 - info: [debug] Clicked button, safari should be launching.
2015-06-22 16:30:08:474 - info: [debug] Waiting for 6000 ms before navigating to view.
2015-06-22 16:30:14:476 - info: [debug] Navigating to most recently opened webview
2015-06-22 16:30:14:477 - info: [debug] [REMOTE] Getting WebKitRemoteDebugger pageArray
2015-06-22 16:30:14:483 - error: [REMOTE] Could not connect to WebKitRemoteDebugger server
2015-06-22 16:30:14:483 - info: [debug] Cleaning up appium session
2015-06-22 16:30:14:487 - info: [debug] Error: Could not navigate to webview! Err: Error: connect ECONNREFUSED     at [object Object].<anonymous>(/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js:1663:12)     at [object Object].<anonymous>  (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js:1557:21)     at [object Object].<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js:1544:21)   at [object Object].<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios-hybrid.js:62:21)     at [object Object].<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/webkit-remote-debugger.js:77:14)     at ClientRequest.<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/underscore/underscore.js:890:21)     at ClientRequest.emit (events.js:107:17)
    at Socket.socketErrorListener (_http_client.js:271:9)
    at Socket.emit (events.js:107:17)
    at net.js:459:14
    at process._tickDomainCallback (node.js:381:11)
2015-06-22 16:30:14:488 - info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Could not navigate to webview! Err: Error: connect ECONNREFUSED)","origValue":"Could not navigate to webview! Err: Error: connect ECONNREFUSED"},"sessionId":null}
2015-06-22 16:30:14:489 - info: <-- POST /wd/hub/session 500 16114.423 ms - 248 
2015-06-22 16:30:14:484 - error: Failed to start an Appium session, err was: Error: Could not navigate to webview! Err: Error: connect ECONNREFUSED

**Comment by vinay3579** [comment]
Hi ,
Pls help me as i am stuck in web browser testing in iOS real device but i am able to run automation steps in app on same iOS real device.
I have installed Safari launcher in my iOS phone using Xcode and my app is signed with dev account .
when i am running my code its open safari launcher click on open button but when safari browser open my iOS webkit getting crash 
in logs i am getting bellow error 
info: [debug] Navigating to most recently opened web view

 info: [debug] [REMOTE] Getting WebKitRemoteDebugger pageArray

info: [debug] Cleaning up appium session

error: [REMOTE] Could not connect to WebKitRemoteDebugger server

and in iOS webkit i am getting error 
Last login: Mon Sep 14 11:25:33 on ttys000

 Administrators-Mac-mini:~ administrator$ ios_webkit_debug_proxy

Listing devices on :9221

Connected :9222 to iPhone 5S (90a0078ff099927f79ba49043a3240147a6f0efb)

Unknown app_id PID:184

Invalid message _rpc_applicationSentListing: <dict>

<key>WIRApplicationIdentifierKey</key>

<string>PID:184</string>

<key>WIRListingKey</key>

<dict>

</dict>

</dict>

Disconnected :9222 from iPhone 5S (90a0078ff099927f79ba49043a3240147a6f0efb)

my code is 

  WebDriver wd;
	

		DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setCapability("appium-version", "1.4.8");
		capabilities.setCapability("platformName", "iOS");
		capabilities.setCapability("platformVersion", "8.4");
        capabilities.setCapability("deviceName", "iPhone 5s");
		capabilities.setCapability("bundleId", "com.pyramidci.SafariLauncher");
		capabilities.setCapability("autoWebView", "true");
		capabilities.setCapability("udid", "90a0078ff099927f79ba49043a3240147a6f0efb");
	
		capabilities.setCapability("app", "/Users/administrator/Library/Developer/Xcode/DerivedData/iOSSampleApp-hgjbrohpjbndcfhiazafhzdvnlet/Build/Products/Debug-iphoneos/iOSSampleApp.app");
		wd = new RemoteWebDriver(new URL("http://0.0.0.0:4723/wd/hub"), capabilities);
		wd.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS);
	
		wd.findElement(By.name("launch safari")).click();
