### ISSUE TITLE
Getting Error "Failed to Dump Window Hierarchy","status":13" while i am using appium inspector on windows + Android 

### ISSUE THREAD

**Issue by sanjaykumar5115** [appium/appium#4151]
Hi all,
I am Getting Error "Failed to Dump Window Hierarchy","status":13" while i am using appium inspector on windows + Android 
Complete log cat are as

---

iQEHaloControlHA.apk","address":"127.0.0.1","logNoColors":true,"androidDeviceReadyTimeout":"300","deviceName":"Ngdcs s5","platformName":"Android","platformVersion":"18","automationName":"Appium"}

> info: Console LogLevel: debug
> info: [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m [90m{"desiredCapabilities":{"deviceName":"Ngdcs s5","app":"E:\APPium\iQEHaloControlHA.apk","deviceReadyTimeout":"300","platformName":"Android"}}[39m
> info: [debug] No appActivity desired capability or server param. Parsing from apk.
> info: [debug] No appPackage desired capability or server param. Parsing from apk.
> info: [debug] Using local app from desired caps: E:\APPium\iQEHaloControlHA.apk
> info: [debug] Creating new appium session c3d8f381-0598-4dca-89ee-9b5fe735c515
> info: Starting android appium
> info: [debug] Using fast reset? true
> info: [debug] Preparing device for session
> info: [debug] Checking whether app is actually present
> info: [debug] Checking whether adb is present
> info: [debug] Using adb from C:\AndroidSdk\sdk\platform-tools\adb.exe
> info: Retrieving device
> info: [debug] Trying to find a connected android device
> info: [debug] Getting connected devices...
> info: [debug] executing: "C:\AndroidSdk\sdk\platform-tools\adb.exe" devices
> info: [debug] 1 device(s) connected
> info: Found device 4d00b2c14b294157
> info: [debug] Setting device id to 4d00b2c14b294157
> info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 300)
> info: [debug] executing: "C:\AndroidSdk\sdk\platform-tools\adb.exe" -s 4d00b2c14b294157 wait-for-device
> info: [debug] executing: "C:\AndroidSdk\sdk\platform-tools\adb.exe" -s 4d00b2c14b294157 shell "echo 'ready'"
> info: [debug] Starting logcat capture
> info: [debug] Parsing package and activity from app manifest
> info: [debug] Checking whether aapt is present
> info: [debug] Using aapt from C:\AndroidSdk\sdk\build-tools\android-4.3\aapt.exe
> info: [debug] packageAndLaunchActivityFromManifest: "C:\AndroidSdk\sdk\build-tools\android-4.3\aapt.exe" dump badging "E:\APPium\iQEHaloControlHA.apk"
> info: [debug] badging package: com.hybrid.ngdcs.android
> info: [debug] badging act: com.hybrid.ngdcs.android.iQEHaloControlHA
> info: [debug] Parsed package and activity are: com.hybrid.ngdcs.android/com.hybrid.ngdcs.android.iQEHaloControlHA
> info: [debug] Getting device API level
> info: [debug] executing: "C:\AndroidSdk\sdk\platform-tools\adb.exe" -s 4d00b2c14b294157 shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 19
> info: Device API level is: 19
> info: [debug] executing: "C:\AndroidSdk\sdk\platform-tools\adb.exe" -s 4d00b2c14b294157 shell "getprop persist.sys.language"
> info: [debug] Current device language: en
> info: [debug] java -jar "E:\APPium\appium-dotnet-driver-master\Appium\node_modules\appium\node_modules\appium-adb\jars\appium_apk_tools.jar" "stringsFromApk" "E:\APPium\iQEHaloControlHA.apk" "C:\Windows\Temp\com.hybrid.ngdcs.android" en
> info: [debug] No strings.xml for language 'en', getting default strings.xml
> info: [debug] java -jar "E:\APPium\appium-dotnet-driver-master\Appium\node_modules\appium\node_modules\appium-adb\jars\appium_apk_tools.jar" "stringsFromApk" "E:\APPium\iQEHaloControlHA.apk" "C:\Windows\Temp\com.hybrid.ngdcs.android"
> info: [debug] executing: "C:\AndroidSdk\sdk\platform-tools\adb.exe" -s 4d00b2c14b294157 push "C:\Windows\Temp\com.hybrid.ngdcs.android\strings.json" /data/local/tmp
> info: [debug] Checking whether aapt is present
> info: [debug] Using aapt from C:\AndroidSdk\sdk\build-tools\android-4.3\aapt.exe
> info: [debug] processFromManifest: "C:\AndroidSdk\sdk\build-tools\android-4.3\aapt.exe" dump xmltree "E:\APPium\iQEHaloControlHA.apk" AndroidManifest.xml
> info: [debug] Set app process to: com.hybrid.ngdcs.android
> info: [debug] Not uninstalling app since server not started with --full-reset
> info: [debug] Checking app cert for E:\APPium\iQEHaloControlHA.apk: java -jar "E:\APPium\appium-dotnet-driver-master\Appium\node_modules\appium\node_modules\appium-adb\jars\verify.jar" "E:\APPium\iQEHaloControlHA.apk"
> info: [debug] App already signed.
> info: [debug] Zip-aligning E:\APPium\iQEHaloControlHA.apk
> info: [debug] Checking whether zipalign is present
> info: [debug] Using zipalign from C:\AndroidSdk\sdk\build-tools\19.1.0\zipalign.exe
> info: [debug] zipAlignApk: "C:\AndroidSdk\sdk\build-tools\19.1.0\zipalign.exe" -f 4 "E:\APPium\iQEHaloControlHA.apk" "C:\Users\sanjaykr\AppData\Local\Temp\appium1141024-6036-17drgf0.tmp"
> info: [debug] MD5 for app is d6e0de5e1f7ebb0b1379dbfd52682be4
> info: [debug] executing: "C:\AndroidSdk\sdk\platform-tools\adb.exe" -s 4d00b2c14b294157 shell "ls /data/local/tmp/d6e0de5e1f7ebb0b1379dbfd52682be4.apk"
> info: [debug] Getting install status for com.hybrid.ngdcs.android
> info: [debug] Getting device API level
> info: [debug] executing: "C:\AndroidSdk\sdk\platform-tools\adb.exe" -s 4d00b2c14b294157 shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 19
> info: [debug] executing: "C:\AndroidSdk\sdk\platform-tools\adb.exe" -s 4d00b2c14b294157 shell "pm list packages -3 com.hybrid.ngdcs.android"
> info: [debug] App is installed
> info: App is already installed, resetting app
> info: [debug] Running fast reset (stop and clear)
> info: [debug] executing: "C:\AndroidSdk\sdk\platform-tools\adb.exe" -s 4d00b2c14b294157 shell "am force-stop com.hybrid.ngdcs.android"
> info: [debug] executing: "C:\AndroidSdk\sdk\platform-tools\adb.exe" -s 4d00b2c14b294157 shell "pm clear com.hybrid.ngdcs.android"
> info: [debug] Forwarding system:4724 to device:4724
> info: [debug] executing: "C:\AndroidSdk\sdk\platform-tools\adb.exe" -s 4d00b2c14b294157 forward tcp:4724 tcp:4724
> info: [debug] Pushing appium bootstrap to device...
> info: [debug] executing: "C:\AndroidSdk\sdk\platform-tools\adb.exe" -s 4d00b2c14b294157 push "E:\APPium\appium-dotnet-driver-master\Appium\node_modules\appium\build\android_bootstrap\AppiumBootstrap.jar" /data/local/tmp/
> info: [debug] Pushing settings apk to device...
> info: [debug] executing: "C:\AndroidSdk\sdk\platform-tools\adb.exe" -s 4d00b2c14b294157 install "E:\APPium\appium-dotnet-driver-master\Appium\node_modules\appium\build\settings_apk\settings_apk-debug.apk"
> info: [debug] Pushing unlock helper app to device...
> info: [debug] executing: "C:\AndroidSdk\sdk\platform-tools\adb.exe" -s 4d00b2c14b294157 install "E:\APPium\appium-dotnet-driver-master\Appium\node_modules\appium\build\unlock_apk\unlock_apk-debug.apk"
> info: Starting App
> info: [debug] Attempting to kill all 'uiautomator' processes
> info: [debug] Getting all processes with 'uiautomator'
> info: [debug] executing: "C:\AndroidSdk\sdk\platform-tools\adb.exe" -s 4d00b2c14b294157 shell "ps 'uiautomator'"
> info: [debug] No matching processes found
> info: [debug] Running bootstrap
> info: [debug] spawning: C:\AndroidSdk\sdk\platform-tools\adb.exe -s 4d00b2c14b294157 shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.Bootstrap
> info: [debug] [90m[UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] io.appium.android.bootstrap.Bootstrap:[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 1[39m
> info: [debug] [BOOTSTRAP] [debug] Socket opened on port 4724
> info: [debug] [BOOTSTRAP] [debug] Appium Socket Server Ready
> info: [debug] [BOOTSTRAP] [debug] Loading json...
> info: [debug] Waking up device if it's not alive
> info: [debug] Pushing command to appium work queue: ["wake",{}]
> info: [debug] [BOOTSTRAP] [debug] json loading complete.
> info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.
> info: [debug] [BOOTSTRAP] [debug] Client connected
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"wake","params":{}}
> info: [debug] executing: "C:\AndroidSdk\sdk\platform-tools\adb.exe" -s 4d00b2c14b294157 shell "dumpsys window"
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: wake
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}
> info: [debug] Writing dumpsys output to E:\APPium\appium-dotnet-driver-master\Appium\node_modules\appium.dumpsys.log
> info: [debug] Screen already unlocked, continuing.
> info: [debug] Pushing command to appium work queue: ["getDataDir",{}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"getDataDir","params":{}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: getDataDir
> info: [debug] dataDir set to: /data/local/tmp
> info: [debug] Pushing command to appium work queue: ["compressedLayoutHierarchy",{"compressLayout":false}]
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"\/data\/local\/tmp","status":0}
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"compressedLayoutHierarchy","params":{"compressLayout":false}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: compressedLayoutHierarchy
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":false,"status":0}
> info: [debug] Getting device API level
> info: [debug] executing: "C:\AndroidSdk\sdk\platform-tools\adb.exe" -s 4d00b2c14b294157 shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 19
> info: [debug] executing: "C:\AndroidSdk\sdk\platform-tools\adb.exe" -s 4d00b2c14b294157 shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n com.hybrid.ngdcs.android/com.hybrid.ngdcs.android.iQEHaloControlHA"
> info: [debug] Waiting for pkg "com.hybrid.ngdcs.android" and activity "com.hybrid.ngdcs.android.iQEHaloControlHA" to be focused
> info: [debug] Getting focused package and activity
> info: [debug] executing: "C:\AndroidSdk\sdk\platform-tools\adb.exe" -s 4d00b2c14b294157 shell "dumpsys window windows"
> info: [debug] Device launched! Ready for commands
> info: [debug] Setting command timeout to the default of 60 secs
> info: [debug] Appium session started with sessionId c3d8f381-0598-4dca-89ee-9b5fe735c515
> info: [37m<-- POST /wd/hub/session [39m[36m303[39m[90m 10097.208 ms - 9[39m [90m[39m
> info: [37m-->[39m [37mGET[39m [37m/wd/hub/session/c3d8f381-0598-4dca-89ee-9b5fe735c515[39m [90m{}[39m
> info: [debug] Responding to client with success: {"status":0,"value":{"platform":"LINUX","browserName":"Android","platformVersion":"4.1","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"deviceName":"Ngdcs s5","app":"E:\APPium\iQEHaloControlHA.apk","deviceReadyTimeout":"300","platformName":"Android"},"deviceName":"Ngdcs s5","app":"E:\APPium\iQEHaloControlHA.apk","deviceReadyTimeout":"300","platformName":"Android"},"sessionId":"c3d8f381-0598-4dca-89ee-9b5fe735c515"}
> info: [37m<-- GET /wd/hub/session/c3d8f381-0598-4dca-89ee-9b5fe735c515 [39m[32m200[39m[90m 2.913 ms - 561[39m [90m{"status":0,"value":{"platform":"LINUX","browserName":"Android","platformVersion":"4.1","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"deviceName":"Ngdcs s5","app":"E:\APPium\iQEHaloControlHA.apk","deviceReadyTimeout":"300","platformName":"Android"},"deviceName":"Ngdcs s5","app":"E:\APPium\iQEHaloControlHA.apk","deviceReadyTimeout":"300","platformName":"Android"},"sessionId":"c3d8f381-0598-4dca-89ee-9b5fe735c515"}[39m
> info: [37m-->[39m [37mGET[39m [37m/wd/hub/session/c3d8f381-0598-4dca-89ee-9b5fe735c515/source[39m [90m{}[39m
> info: [debug] Pushing command to appium work queue: ["source",{}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"source","params":{}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: source
> info: [debug] [90m[UIAUTOMATOR STDOUT] java.io.FileNotFoundException: /data/local/tmp/local/tmp/dump.xml: open failed: ENOENT (No such file or directory)[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] at libcore.io.IoBridge.open(IoBridge.java:409)[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] at java.io.FileInputStream.<init>(FileInputStream.java:78)[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] at java.io.FileReader.<init>(FileReader.java:42)[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] at io.appium.android.bootstrap.utils.XMLHierarchy.getRawXMLHierarchy(XMLHierarchy.java:88)[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] at io.appium.android.bootstrap.utils.XMLHierarchy.getFormattedXMLDoc(XMLHierarchy.java:96)[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] at io.appium.android.bootstrap.handler.Source.execute(Source.java:25)[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] at io.appium.android.bootstrap.AndroidCommandExecutor.execute(AndroidCommandExecutor.java:64)[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] at[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] io.appium.android.bootstrap.SocketServer.runCommand(SocketServer.java:167)[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] at io.appium.android.bootstrap.SocketServer.handleClientData(SocketServer.java:88)[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] at io.appium.android.bootstrap.SocketServer.listenForever(SocketServer.java:132)[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] at io.appium.android.bootstrap.Bootstrap.testRunServer(Bootstrap.java:16)[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] at[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] java.lang.reflect.Method.invokeNative(Native Method)[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] at java.lang.reflect.Method.invoke(Method.java:515)[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] at junit.framework.TestCase.runTest(TestCase.java:168)[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] at junit.framework.TestCase.runBare(TestCase.java:134)[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] at junit.framework.TestResult$1.protect(TestResult.java:115)[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] at junit.framework.TestResult.runProtected(TestResult.java:133)[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] at junit.framework.TestResult.run(TestResult.java:118)[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] at junit.framework.TestCase.run(TestCase.java:124)[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] at com.android.uiautomator.testrunner.UiAutomatorTestRunner.start(UiAutomatorTestRunner.java:160)[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] at com.android.uiautomator.testrunner.UiAutomatorTestRunner.run(UiAutomatorTestRunner.java:96)[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] at com.android.commands.uiautomator.RunTestCommand.run(RunTestCommand.java:91)[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] at com.android.commands.uiautomator.Launcher.main(Launcher.java:83)[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:301)[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] at dalvik.system.NativeStart.main(Native Method)[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] Caused by: libcore.io.ErrnoException: open failed: ENOENT (No such file or directory)[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] at libcore.io.Posix.open(Native Method)[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] at libcore.io.IoBridge.open(IoBridge.java:393)[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] ... 25[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] more[39m
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"Failed to Dump Window Hierarchy","status":13}
> info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command.","origValue":"Failed to Dump Window Hierarchy"},"sessionId":"c3d8f381-0598-4dca-89ee-9b5fe735c515"}
> info: [37m<-- GET /wd/hub/session/c3d8f381-0598-4dca-89ee-9b5fe735c515/source [39m[31m500[39m[90m 23.727 ms - 200[39m [90m[39m
> info: [37m-->[39m [37mGET[39m [37m/wd/hub/session/c3d8f381-0598-4dca-89ee-9b5fe735c515/screenshot[39m [90m{}[39m
> info: [debug] executing: "C:\AndroidSdk\sdk\platform-tools\adb.exe" -s 4d00b2c14b294157 shell "/system/bin/rm /data/local/tmp/screenshot.png; /system/bin/screencap -p /data/local/tmp/screenshot.png "
> info: [debug] executing: "C:\AndroidSdk\sdk\platform-tools\adb.exe" -s 4d00b2c14b294157 pull /data/local/tmp/screenshot.png "C:\Users\sanjaykr\AppData\Local\Temp\appium1141024-6036-wad1jt.png"
> info: [debug] Responding to client with success: {"status":0,"value":"iVBORw0KGgoAAAANSUhEUgAABDgAAAeACAYAAAArYecKAAAABHNCSVQICAgIfAhkiAAAIABJREFUeJzs3Xd4VWW+9//PTiUNEkKCBEhCh9AhFGkCIhIVROIAF5KRoiQzPjM8ch5ksDwz54AwHs7ljFPOQ5xhxhFELAERFVQQIiCCCRBKQpESYihJIJSQXn5/5LfXyU4jfWeF9+u6vMxua90Jyd5rfdZ9f7+WwMDAEgEAAAAAAJiYg70HAAAAAAAAUF8EHAAAAAAAwPQIOAAAAAAAgOkRcAAAAAAAANMj4AAAAAAAAKZHwAEAAAAAAEyPgAMAAAAAAJgeAQcAAAAAADA9Ag4AAAAAAGB6TvYeAAAAAFBX7u7u8vb2VqtWreTm5iZ3d3dJkouLi1xdXSVJeXl5ys/PlyRlZ2crJydHubm5unnzprKzs+02dgBAw2qxAUf37t2VkpKivLw8ew8FAAAADcTZ2Vn+/v7y9fVVmzZt5OzsfM/XuLq6GmGHl5eXzWMFBQW6deuWrl+/rrS0NBUUFDTKuAEAjc8SGBhYYu9BNDRnZ2ctXrxYFy9e1Mcff2zv4QAAAKAeLBaL2rdvr/bt28vX17dR93X9+nVdvXpVaWlpKilpcYfJuE8MHjxYPj4+NX5+Zmamjhw50ogjAppGi5zBERoaqj59+igwMFCxsbFKT0+395DQjDk4OOiBBx5Q165dFRwcLG9vb3l6ekqS7ty5oxs3bujixYs6f/48BzsAADQhJycnBQQEKDAwUC4uLk2yT19fX/n6+qpHjx66dOmSLl++rMLCwibZt5nMnj1bmzZtsvcwAMBGiws4PD09NW7cOLm5ucnV1VVhYWF6//33TT/dcOPGjY2+j7S0NP3zn/9UQkJCo+/Lnjw8PNSxY0d169ZNISEh6tatm7y9ve/5upKSEt24cUM//vijEhMTde7cOV2+fFm5ublNMGoAAO4fFotFnTt3VnBwsJyc7HO46uLiou7duys4...","sessionId":"c3d8f381-0598-4dca-89ee-9b5fe735c515"}
> info: [37m<-- GET /wd/hub/session/c3d8f381-0598-4dca-89ee-9b5fe735c515/screenshot [39m[32m200[39m[90m 901.275 ms - 38854[39m [90m{"status":0,"value":"iVBORw0KGgoAAAANSUhEUgAABDgAAAeACAYAAAArYecKAAAABHNCSVQICAgIfAhkiAAAIABJREFUeJzs3Xd4VWW+9//PTiUNEkKCBEhCh9AhFGkCIhIVROIAF5KRoiQzPjM8ch5ksDwz54AwHs7ljFPOQ5xhxhFELAERFVQQIiCCCRBKQpESYihJIJSQXn5/5LfXyU4jfWeF9+u6vMxua90Jyd5rfdZ9f7+WwMDAEgEAAAAAAJiYg70HAAAAAAAAUF8EHAAAAAAAwPQIOAAAAAAAgOkRcAAAAAAAANMj4AAAAAAAAKZHwAEAAAAAAEyPgAMAAAAAAJgeAQcAAAAAADA9Ag4AAAAAAGB6TvYeAAAAAFBX7u7u8vb2VqtWreTm5iZ3d3dJkouLi1xdXSVJeXl5ys/PlyRlZ2crJydHubm5unnzprKzs+02dgBAw2qxAUf37t2VkpKivLw8ew8FAAAADcTZ2Vn+/v7y9fVVmzZt5OzsfM/XuLq6GmGHl5eXzWMFBQW6deuWrl+/rrS0NBUUFDTKuAEAjc8SGBhYYu9BNDRnZ2ctXrxYFy9e1Mcff2zv4QAAAKAeLBaL2rdvr/bt28vX17dR93X9+nVdvXpVaWlpKilpcYfJuE8MHjxYPj4+NX5+Zmamjhw50ogjAppGi5zBERoaqj59+igwMFCxsbFKT0+395DQjDk4OOiBBx5Q165dFRwcLG9vb3l6ekqS7ty5oxs3bujixYs6f/48BzsAADQhJycnBQQEKDAwUC4uLk2yT19fX/n6+qpHjx66dOmSLl++rMLCwibZt5nMnj1bmzZtsvcwAMBGiws4PD09NW7cOLm5ucnV1VVhYWF6//33TT/dcOPGjY2+j7S0NP3zn/9UQkJCo+/Lnjw8PNSxY0d169ZNISEh6tatm7y9ve/5upKSEt24cUM//vijEhMTde7cOV2+fFm5ublNMGoAAO4fFotFnTt3VnBwsJyc7HO46uLiou7duys4...","sessionId":"c3d8f381-0598-4dca-89ee-9b5fe735c515"}[39m
> info: [debug] Didn't get a new command in 60 secs, shutting down...

**Comment by sanjaykumar5115** [comment]
any update

**Comment by bootstraponline** [comment]
this might be fixed by https://github.com/appium/appium/pull/4252

**Comment by moizjv** [comment]
@sanjaykumar5115 can you retry with latest version?

**Comment by moizjv** [comment]
Closing due to inactivity

**Comment by momenimohammad23** [comment]
i have the same issue 
i use appium version 1.4.0.0 
How i can solve it ? 
please help me !!
@moizjv @imurchie  @sanjaykumar5115

**Comment by TFry** [comment]
Not fixed, just ran into this on Android 4.4.3 Nexus 7 using the latest Appium 1.4.8 

Same error: "failed to dump window hierarchy - status 13"

I can recreate this with 100% success on a specific window in my app that populates with bluetooth devices. 

@moizjv @bootstraponline

**Comment by bootstraponline** [comment]
won't be solved until the new android driver is completed. This is a known bug in uiautomator v1.

**Comment by TFry** [comment]
Thanks for the feedback @bootstraponline 

Extra information:
The xpath depth is the culprit as the number of items populated on the list determines if the problem occurs or not.
Depth of 9 steps into an xpath hierarchy is the cutoff point where the error shows up.

**Comment by bootstraponline** [comment]
Specifically for find by xpath, I'm hoping the new Android driver will be able to use [droiddriver's implementation](https://github.com/appium/droiddriver) which shouldn't suffer from this limitation.

**Comment by bootstraponline** [comment]
Reopening because this is a bug that's not fixed and more info has been provided.

**Comment by jeangb** [comment]
Hello I'm experiencing the same issue with Appium v1.4.16 on Windows with real android device.
This happens when I run a java test which iterates with several datas (using testng dataproviders).
It works the first iteration but failed at the second.

**Comment by mykola-mokhnach** [comment]
Closed as obsolete

**Comment by Yakupvarli** [comment]
ben de hata alıyorum
