### ISSUE TITLE
"Instrument crashed at startup" when using iOS 8 on real iPad

### ISSUE THREAD

**Issue by raugustin** [appium/appium#4166]
Does  appium 1.3.1 support iOS8 on real device?

I tried these combination which leads me to ask the question...
All these are using iOS_debug_proxy 1.4  
xcode 5.1.1/appium 1.2.3/iOS7.0.4 device: test runs
xcode 6/appium 1.2.3/iOS7.0.4 device:Test runs
xcode6/appium 1.3.1/iOS7.0.4 device:Test runs
xcode6/appium 1.3.1/iOS8.1.1 device:get "Instruments crashed at startup"
 or device get disconnected from debug proxy server(test passed randomly)

instruments seems to crashed specifically with iOS 8

This is the message i get on the appium console:
[[info: --> POST /wd/hub/session {"sessionId":null,"desiredCapabilities":{"deviceName":"iPad","browserName":"Safari","platformName":"ios","javascriptEnabled":true,"cssSelectorsEnabled":true}}
info: Client User-Agent string: Python-urllib/2.6
info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : javascriptEnabled, cssSelectorsEnabled
info: [debug] Configuring Safari session
info: [debug] Using local .zip from command line: /Users/raugustin/node_modules/appium/build/SafariLauncher/SafariLauncher.zip
info: [debug] Copying local zip to tmp dir
info: [debug] /Users/raugustin/node_modules/appium/build/SafariLauncher/SafariLauncher.zip copied to /var/folders/mv/chw8950d4tq4nsyxzv8ddfqmldk3j1/T/1141025-7303-1s3iqbu/appium-app.zip
info: [debug] Unzipping /var/folders/mv/chw8950d4tq4nsyxzv8ddfqmldk3j1/T/1141025-7303-1s3iqbu/appium-app.zip
info: [debug] Testing zip archive: /var/folders/mv/chw8950d4tq4nsyxzv8ddfqmldk3j1/T/1141025-7303-1s3iqbu/appium-app.zip
info: [debug] Zip archive tested clean
info: [debug] Unzip successful
info: [debug] Using locally extracted app: /var/folders/mv/chw8950d4tq4nsyxzv8ddfqmldk3j1/T/1141025-7303-1s3iqbu/submodules/SafariLauncher/build/Release-iphoneos/SafariLauncher.app
info: [debug] Creating new appium session 7ceb6ac5-1763-43ed-86fb-dc81d6132a51
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode folder
info: [debug] Setting Xcode version
info: [debug] Setting iOS SDK Version
info: [debug] Getting sdk version from xcrun with a timeout
info: [debug] iOS SDK Version set to 8.1
info: [debug] Not checking whether simulator is available since we're on a real device
info: [debug] Detecting automation tracetemplate
info: [debug] Not auto-detecting udid, running on sim
info: [debug] Could not parse plist file (as binary) at /var/folders/mv/chw8950d4tq4nsyxzv8ddfqmldk3j1/T/1141025-7303-1s3iqbu/submodules/SafariLauncher/build/Release-iphoneos/SafariLauncher.app/en.lproj/Localizable.strings
info: Will try to parse the plist file as XML
info: [debug] Could not parse plist file (as XML) at /var/folders/mv/chw8950d4tq4nsyxzv8ddfqmldk3j1/T/1141025-7303-1s3iqbu/submodules/SafariLauncher/build/Release-iphoneos/SafariLauncher.app/en.lproj/Localizable.strings
warn: Could not parse app Localizable.strings; assuming it doesn't exist
info: [debug] Getting bundle ID from app
info: [debug] Parsed app Info.plist (as binary)
info: [debug] Creating instruments
info: On some xcode 6 platforms, instruments-without-delay does not work. If you experience this, you will need to re-run appium with the --native-instruments-lib flag
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/raugustin/Library/Application Support/appium/bootstrap
info: [debug] Dynamic env: {"nodePath":"/usr/local/bin/node","commandProxyClientPath":"/Users/raugustin/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"sendKeyStrategy":"grouped"}
info: [debug] Dynamic bootstrap code: // This file is autom...cally generated. Do not manually modify!
info: [debug] Dynamic bootstrap path: /Users/raugustin/Library/Application Support/appium/bootstrap/bootstrap-020134ca99feaa7c.js
info: [debug] Reusing dynamic bootstrap: /Users/raugustin/Library/Application Support/appium/bootstrap/bootstrap-020134ca99feaa7c.js
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.1","iOSSDKVersion":"8.1","deviceName":"iPad","platformVersion":null}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPad (8.1 Simulator)'
info: [debug] Not setting device type since we're on a real device
info: [debug] Checking whether we need to set app preferences
info: [debug] Not setting iOS and app preferences since we're on a real device
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killall iOS Simulator
info: [debug] Killing any other simulator daemons
info: [debug] On a real device; cannot clean device state
info: [debug] Not setting locale because we're using a real device
info: [debug] No iOS / app preferences to set
info: [debug] Starting iOS device log capture via deviceconsole
info: [debug] Not pre-launching simulator
info: [debug] Checking app install status using: /Users/raugustin/node_modules/appium/build/fruitstrap/fruitstrap isInstalled --id 1463dc062265b92e8248b18c0fbe76795a8d6838 --bundle com.bytearc.SafariLauncher
info: [debug] Starting command proxy.
info: [debug] Instruments socket server started at /tmp/instruments_sock
info: [debug] Starting instruments
info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
info: Launching instruments
info: [debug] Attempting to run app on real device with UDID 1463dc062265b92e8248b18c0fbe76795a8d6838
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w 1463dc062265b92e8248b18c0fbe76795a8d6838 com.bytearc.SafariLauncher -e UIASCRIPT "/Users/raugustin/Library/Application Support/appium/bootstrap/bootstrap-020134ca99feaa7c.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {}
info: [debug] And launch timeouts (in ms): {"global":30000}
info: [debug] [INST STDERR] 2014-11-25 11:31:12.739 instruments[7432:1d03] WebKit Threading Violation - initial use of WebKit from a secondary thread.
info: [debug] [INST] 2014-11-25 16:31:13 +0000 Fail: The target application appears to have died
info: [debug] [INST] Instruments Trace Complete (Duration : 172.544510s; Output : /tmp/appium-instruments/instrumentscli0.trace)
info: [debug] [INSTSERVER] Instruments exited with code 0
info: [debug] Cleaning up after instruments exit
info: [debug] Instruments exited unexpectedly
info: [debug] Shutting down command proxy and ignoring any errors
info: [debug] Destroying instruments client socket.
info: [debug] Closing socket server.
info: [debug] Instruments socket server was closed
info: [debug] Stopping iOS log capture
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killall iOS Simulator
info: [debug] Killing any other simulator daemons
info: [debug] On a real device; cannot clean device state
info: [debug] [INST] 2014-11-25 16:31:15 +0000 Error: Script threw an uncaught JavaScript error: Error getting next command, shutting down :-( on line 2673 of bootstrap-020134ca99feaa7c.js
info: [debug] [INST] 2014-11-25 16:31:16 +0000 Stopped: Script was stopped by the user
info: [debug] [INST] Instruments Trace Complete (Duration : 3.469100s; Output : /tmp/appium-instruments/instrumentscli0.trace)
info: [debug] [INSTSERVER] Instruments exited with code 0
info: [debug] Killall instruments
info: [debug] Instruments crashed on startup
info: [debug] Attempting to retry launching instruments, this is retry #1
info: [debug] Killall iOS Simulator
info: Launching instruments
info: [debug] Attempting to run app on real device with UDID 1463dc062265b92e8248b18c0fbe76795a8d6838
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w 1463dc062265b92e8248b18c0fbe76795a8d6838 com.bytearc.SafariLauncher -e UIASCRIPT "/Users/raugustin/Library/Application Support/appium/bootstrap/bootstrap-020134ca99feaa7c.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {}
info: [debug] And launch timeouts (in ms): {"global":30000}
info: [debug] [INST STDERR] 2014-11-25 11:31:22.908 instruments[7450:581b] WebKit Threading Violation - initial use of WebKit from a secondary thread.
info: [debug] [INST] 2014-11-25 16:31:25 +0000 Error: Script threw an uncaught JavaScript error: Error getting next command, shutting down :-( on line 2673 of bootstrap-020134ca99feaa7c.js
info: [debug] [INST] 2014-11-25 16:31:25 +0000 Stopped: Script was stopped by the user
info: [debug] [INST] Instruments Trace Complete (Duration : 3.530915s; Output : /tmp/appium-instruments/instrumentscli0.trace)
info: [debug] [INSTSERVER] Instruments exited with code 0
info: [debug] Killall instruments
info: [debug] Instruments crashed on startup
info: [debug] Attempting to retry launching instruments, this is retry #2
info: [debug] Killall iOS Simulator
info: Launching instruments
info: [debug] Attempting to run app on real device with UDID 1463dc062265b92e8248b18c0fbe76795a8d6838
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w 1463dc062265b92e8248b18c0fbe76795a8d6838 com.bytearc.SafariLauncher -e UIASCRIPT "/Users/raugustin/Library/Application Support/appium/bootstrap/bootstrap-020134ca99feaa7c.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {}
info: [debug] And launch timeouts (in ms): {"global":30000}
info: [debug] [INST STDERR] 2014-11-25 11:31:32.518 instruments[7456:1307] WebKit Threading Violation - initial use of WebKit from a secondary thread.
info: [debug] [INST] 2014-11-25 16:31:35 +0000 Error: Script threw an uncaught JavaScript error: Error getting next command, shutting down :-( on line 2673 of bootstrap-020134ca99feaa7c.js
info: [debug] [INST] 2014-11-25 16:31:35 +0000 Stopped: Script was stopped by the user
info: [debug] [INST] Instruments Trace Complete (Duration : 3.351833s; Output : /tmp/appium-instruments/instrumentscli0.trace)
info: [debug] [INSTSERVER] Instruments exited with code 0
info: [debug] Killall instruments
info: [debug] Instruments crashed on startup
info: [debug] Attempting to retry launching instruments, this is retry #3
info: [debug] Killall iOS Simulator
info: Launching instruments
info: [debug] Attempting to run app on real device with UDID 1463dc062265b92e8248b18c0fbe76795a8d6838
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w 1463dc062265b92e8248b18c0fbe76795a8d6838 com.bytearc.SafariLauncher -e UIASCRIPT "/Users/raugustin/Library/Application Support/appium/bootstrap/bootstrap-020134ca99feaa7c.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {}
info: [debug] And launch timeouts (in ms): {"global":30000}
info: [debug] [INST STDERR] 2014-11-25 11:31:42.059 instruments[7461:4c1b] WebKit Threading Violation - initial use of WebKit from a secondary thread.
info: [debug] [INST] 2014-11-25 16:31:44 +0000 Error: Script threw an uncaught JavaScript error: Error getting next command, shutting down :-( on line 2673 of bootstrap-020134ca99feaa7c.js
info: [debug] [INST] 2014-11-25 16:31:44 +0000 Stopped: Script was stopped by the user
info: [debug] [INST] Instruments Trace Complete (Duration : 3.402201s; Output : /tmp/appium-instruments/instrumentscli0.trace)
info: [debug] [INSTSERVER] Instruments exited with code 0
info: [debug] Killall instruments
info: [debug] Instruments crashed on startup
info: [debug] We exceeded the number of retries allowed for instruments to successfully start; failing launch
info: [debug] Stopping iOS log capture
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killall iOS Simulator
info: [debug] Killing any other simulator daemons
info: [debug] On a real device; cannot clean device state
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: Instruments crashed on startup
info: [debug] Error: Instruments crashed on startup
    at Instruments.onInstrumentsExit (/Users/raugustin/node_modules/appium/node_modules/appium-instruments/lib/instruments.js:387:31)
    at null.<anonymous> (/Users/raugustin/node_modules/appium/node_modules/appium-instruments/lib/instruments.js:308:12)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:807:12)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Instruments crashed on startup)","origValue":"Instruments crashed on startup"},"sessionId":null}
info: <-- POST /wd/hub/session 500 36938.259 ms - 182

There is also this message on debug console after instruments crashed while tests are running.
Invalid message _rpc_applicationUpdated: <dict>
	<key>WIRApplicationBundleIdentifierKey</key>
	<string>com.apple.mobilesafari</string>
	<key>WIRApplicationNameKey</key>
	<string>Safari</string>
	<key>WIRIsApplicationProxyKey</key>
	<false/>
	<key>WIRIsApplicationActiveKey</key>
	<integer>0</integer>
	<key>WIRApplicationIdentifierKey</key>
	<string>PID:189</string>
</dict>
ss.remove_fd(10)
Disconnected :27753 from Rodney Augustin’s iPad (1463dc062265b92e8248b18c0fbe76795a8d6838)
ss.remove_server_fd(4)

This could be an issue with appium support for iOS 8 since appium 1.3.1 works well with iOS 7

**Comment by ASYB** [comment]
Have you run ./bin/ios-webkit-debug-proxy-launcher.js -c <UDID>:27753 if you are using latest Appium??

**Comment by 0x1mason** [comment]
Closing due to inactivity.
