### ISSUE TITLE
Include JSON full text in the invalid error message

### ISSUE THREAD

**Issue by bootstraponline** [appium/appium#4217]
The stack trace and error message on Invalid JSON are not helpful.

```
info: <-- POST /wd/hub/session/871a862a-13a9-45a3-87a7-11d836149186/appium/element/6/value 500 11.600 ms - 66 
Error: invalid json
    at parse (/appium/node_modules/body-parser/lib/types/json.js:60:15)
    at /appium/node_modules/body-parser/lib/read.js:96:18
    at IncomingMessage.onEnd (/appium/node_modules/body-parser/node_modules/raw-body/index.js:135:7)
    at IncomingMessage.g (events.js:180:16)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickDomainCallback (node.js:463:13)
```

It'd be nice to include the full text of the invalid JSON that was posted to the server. Currently I'm working around this by instrumenting the client library to dump the JSON before it's sent to the server.

**Comment by jlipps** [comment]
This is moot since we've redone appium-express
