### ISSUE TITLE
Calling driver.close then driver.quit causes segmentation fault in ios_webkit_debug_proxy

### ISSUE THREAD

**Issue by shivshankark** [appium/appium#4225]
I am testing webpages in safari on iPad 7.1 with Appium 1.3.3. The test suite has multiple tests and at end of each test, I close browser windows with driver.close() and in the end, I call driver.quit(). 
The first test runs fine, then during cleanup ( close and quit ) causes ios_webkit_debug_proxy to segfault. Effectively, causing connection refused error in appium from second test onwards.

The partial log shows - 
```
info: [debug] [REMOTE] Getting WebKitRemoteDebugger pageArray
error: [REMOTE] Could not connect to WebKitRemoteDebugger server
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: Could not navigate to webview! Err: Error: connect ECONNREFUSED
info: [debug] Error: Could not navigate to webview! Err: Error: connect ECONNREFUSED
    at null.<anonymous> (/Applications/Appium-1.3.3.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js:1556:12)
    at null.<anonymous> (/Applications/Appium-1.3.3.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios-controller.js:1532:14)
    at null.<anonymous> (/Applications/Appium-1.3.3.app/Contents/Resources/node_modules/appium/lib/devices/ios/webkit-remote-debugger.js:73:14)
    at ClientRequest.<anonymous> (/Applications/Appium-1.3.3.app/Contents/Resources/node_modules/appium/node_modules/underscore/underscore.js:754:19)
    at ClientRequest.emit (events.js:95:17)
    at Socket.socketErrorListener (http.js:1551:9)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickDomainCallback (node.js:463:13)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Could not navigate to webview! Err: Error: connect ECONNREFUSED)","origValue":"Could not navigate to webview! Err: Error: connect ECONNREFUSED"},"sessionId":null}
```

Here is a simple code to repro this issue. This code tries to run example test multiple times, it runs successfully only the first time .

```java
       for (int i = 0; i < 5; i++) {
            System.out.println("\n Test number " + (i + 1));

            DesiredCapabilities capabilities = new DesiredCapabilities();
            capabilities.setCapability("deviceName", "auto");
            capabilities.setCapability("platformName", "iOS");
            capabilities.setCapability("browserName", "safari");

            System.out.println("creating driver");
            driver = new RemoteWebDriver(new URL("http://<server_addr>:4723/wd/hub"), capabilities);

            System.out.println("Navigating to page");
            driver.get("http://saucelabs.com/test/guinea-pig");
            Thread.sleep(1000);
            WebElement idElement = driver.findElement(By.id("i_am_an_id"));
            assertNotNull(idElement);
            assertEquals("I am a div", idElement.getText());

            System.out.println("Closing windows");

            for (String window : driver.getWindowHandles()) {
                driver.close();
            }
            driver.quit();
       }
```

**Comment by moizjv** [comment]
Closing as it is tracked in another issue
