### ISSUE TITLE
appium crashing on dump xml

### ISSUE THREAD

**Issue by ASADZAMAN2012** [appium/appium#4228]
appium is crashing on iOS when invoking get tree for xml using xcode 6.1.1 on MAC 10.9.5

```
info: Welcome to Appium v1.3.4 (REV efd0bf0e53093cee2fd185742c9a1a1c344bdf87)
info: Appium REST http interface listener started on 0.0.0.0:4723
info: Console LogLevel: debug

info: [debug] Error: Bad response from getTreeForXML. Err was undefined and res was undefined
    at Object.cb [as callback] (/appium/lib/devices/ios/ios-controller.js:251:11)
    at next (/appium/node_modules/async/lib/async.js:801:43)
    at /appium/node_modules/async/lib/async.js:32:16
    at null.<anonymous> (/appium/lib/devices/ios/ios.js:1414:36)
    at Object.q.process [as _onImmediate] (/appium/node_modules/async/lib/async.js:809:21)
    at processImmediate [as _immediateCallback] (timers.js:345:15)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Bad response from getTreeForXML. Err was undefined and res was undefined)","origValue":"Bad response from getTreeForXML. Err was undefined and res was undefined"},"sessionId":null}
info: <-- POST /wd/hub/session 500 20587.835 ms - 266 
```

**Comment by sebv** [comment]
closing, no activity.

**Comment by jj973r** [comment]
I also am encountering this issue. Here are the logs:
info: [debug] Using local app from command line: /Users/jasminejames/Library/Developer/Xcode/DerivedData/DigitalUI-cbljniinqjflaoeifywovlgphhnd/Build/Products/Debug-iphonesimulator/Digital2.0.app
info: [debug] Creating new appium session d5f48c03-b174-4840-b653-e6472665802b
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode folder
info: [debug] Setting Xcode version
info: [debug] Setting iOS SDK Version
info: [debug] Getting sdk version from xcrun with a timeout
info: [debug] iOS SDK Version set to 8.1
info: [debug] Checking whether instruments supports our device string
info: [debug] Getting list of devices instruments supports
info: [debug] Instruments is at: /Applications/Xcode61.app/Contents/Developer/usr/bin/instruments
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.1.1","iOSSDKVersion":"8.1","deviceName":null,"platformVersion":"7.1"}
info: [debug] fixDevice is on
info: [debug] Fixing device. Changed from: "iPhone Simulator (7.1 Simulator)" to: "iPhone 5s (7.1 Simulator)"
info: [debug] Final device string is: 'iPhone 5s (7.1 Simulator)'
info: [debug] iOS sim UDID is E9E529FC-XXXX-4F6E-B6E4-8C9E89C95AA1
info: [debug] Detecting automation tracetemplate
info: [debug] Not auto-detecting udid, running on sim
info: [debug] Parsed app Info.plist (as binary)
info: [debug] Parsed app Localizable.strings
info: [debug] Getting bundle ID from app
info: [debug] Parsed app Info.plist (as binary)
info: [debug] Creating instruments
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/jasminees/Library/Application Support/appium/bootstrap
info: [debug] Dynamic env: {"nodePath":"/Applications/Appium.app/Contents/Resources/node/bin/node","commandProxyClientPath":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"sendKeyStrategy":"oneByOne"}
info: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...
info: [debug] Dynamic bootstrap path: /Users/jasminees/Library/Application Support/appium/bootstrap/bootstrap-a4a902c9cce7b6cb.js
info: [debug] Reusing dynamic bootstrap: /Users/jasminejames/Library/Application Support/appium/bootstrap/bootstrap-a4a902c9cce7b6cb.js
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.1.1","iOSSDKVersion":"8.1","deviceName":null,"platformVersion":"7.1"}
info: [debug] fixDevice is on
info: [debug] Fixing device. Changed from: "iPhone Simulator (7.1 Simulator)" to: "iPhone 5s (7.1 Simulator)"
info: [debug] Final device string is: 'iPhone 5s (7.1 Simulator)'
info: [debug] We're on iOS7.1+ so forcing defaultDevice on
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.1.1","iOSSDKVersion":"8.1","deviceName":null,"platformVersion":"7.1"}
info: [debug] fixDevice is on
info: [debug] Fixing device. Changed from: "iPhone Simulator (7.1 Simulator)" to: "iPhone 5s (7.1 Simulator)"
info: [debug] Final device string is: 'iPhone 5s (7.1 Simulator)'
info: [debug] Parsed app Info.plist (as binary)
info: [debug] Wrote new app Info.plist with device type
info: [debug] Checking whether we need to set app preferences
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killall
 iOS Simulator
info: [debug] Killing any other simulator daemons
info: [debug] Cleaning sim data files
info: [debug] Executing: xcrun simctl erase E9E529FC-XXXX-4F6E-B6E4-8C9E89C95AA1
info: [debug] Cleaning app data files
warn: Applications directory /Users/jasminees/Library/Developer/CoreSimulator/Devices/E9E529FC-D69A-4F6E-XXXX-8C9E89C95AA1/data/Applications doesn't exist. Have you run this simulator before?
info: Couldn't find app directories to delete. Probably it's not installed
info: [debug] Not setting locale
info: [debug] No iOS / app preferences to set
info: [debug] Starting iOS 8.* simulator log capture
info: [debug] Not pre-launching simulator
info: [debug] No device id or app, not installing to real device.
info: [debug] Starting command proxy.
info: [debug] Instruments socket server started at /tmp/instruments_sock
info: [debug] Starting instruments
info: [debug] Instruments is at: /Applications/Xcode61.app/Contents/Developer/usr/bin/instruments
info: Launching instruments
info: [debug] Attempting to run app on iPhone 5s (7.1 Simulator)
info: [debug] Spawning instruments with command: /Applications/Xcode61.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode61.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w "iPhone 5s (7.1 Simulator)" "/Users/jasminejames/Library/Developer/Xcode/DerivedData/DigitalUI-cbljniinqjflaoeifywovlgphhnd/Build/Products/Debug-iphonesimulator/Digital2.0.app" -e UIASCRIPT "/Users/jasminejes/Library/Application Support/appium/bootstrap/bootstrap-a4a902c9cce7b6cb.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {}
info: [debug] And launch timeouts (in ms): {"global":90000}
info: [debug] [INST] Waiting for device to boot...

info: [debug] [INST STDERR] 2015-01-26 14:13:44.128 ScriptAgent[92205:2d0f] CLTilesManagerClient: initialize, sSharedTilesManagerClient
info: [debug] [INST STDERR] 2015-01-26 14:13:44.129 ScriptAgent[92205:2d0f] CLTilesManagerClient: init
info: [debug] [INST STDERR] 2015-01-26 14:13:44.129 ScriptAgent[92205:2d0f] CLTilesManagerClient: reconnecting, 0x111b13e70

info: [debug] [INST STDERR] 2015-01-26 14:13:45.010 ScriptAgent[92205:2d0f] AX Lookup problem! 1102 com.apple.iphone.axserver:92202
info: Instruments is ready to receive commands
info: [debug] Instruments launched. Starting poll loop for new commands.
info: [debug] Setting bootstrap config keys/values
info: [debug] Pushing command to appium work queue: "target = $.target();\nau = $;\n$.isVerbose = true;\n"
info: [debug] Socket data received (2 bytes)
info: [debug] Socket data being routed.
info: [debug] Sending command to instruments: target = $.target();
au = $;
$.isVerbose = true;

info: [debug] [INST] 2015-01-26 19:13:46 +0000 Debug: evaluation finished
info: [debug] [INST] 2015-01-26 19:13:46 +0000 Debug: responding with:
info: [debug] [INST] 2015-01-26 19:13:46 +0000 Debug: Running system command #1: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":true}...
info: [debug] Socket data received (27 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":true}
info: [debug] Setting initial orientation to PORTRAIT
info: [debug] Pushing command to appium work queue: "au.setScreenOrientation('PORTRAIT')"
info: [debug] Sending command to instruments: au.setScreenOrientation('PORTRAIT')
info: [debug] [INST] 2015-01-26 19:13:46 +0000 Fail: The target application appears to have died

info: [debug] [INST] Instruments Trace Complete (Duration : 5.602597s; Output : /tmp/appium-instruments/instrumentscli0.trace)
info: [debug] [INSTSERVER] Instruments exited with code 0
info: [debug] Cleaning up after instruments exit
info: [debug] Instruments exited unexpectedly
info: [debug] Shutting down command proxy and ignoring any errors
info: [debug] Closing socket server.
info: [debug] Instruments socket server was closed
info: [debug] Stopping iOS log capture
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killall iOS Simulator
info: [debug] Killing any other simulator daemons
info: [debug] Cleaning sim data files
info: [debug] Executing: xcrun simctl erase E9E529FC-XXXX-4F6E-B6E4-8C9E89C95AA1
info: [debug] Cleaning app data files
warn: Applications directory /Users/jasminees/Library/Developer/CoreSimulator/Devices/E9E529FC-D69A-XXXX-B6E4-8C9E89C95AA1/data/Applications doesn't exist. Have you run this simulator before?
info: Couldn't find app directories to delete. Probably it's not installed
info: [debug] We were in the middle of processing a command when instruments died; responding with a generic error
info: [debug] Cleaning up appium session
warn: Setting initial orientation did not work!

**Comment by eliasnogueira** [comment]
Bug persist in XCode Version 6.2 (6C131e)

**Comment by jlipps** [comment]
> info: [debug] [INST] 2015-01-26 19:13:46 +0000 Fail: The target application appears to have died

This is the actual cause of the issue. Your app crashed on startup, so Appium got into a confused state.

**Comment by eliasnogueira** [comment]
It's exactly behavior in my script. If you close the app of course the commands will return an error.
In my case the script is a push/notification test, and it appears just with app closed. When I closed the app and the next command depends on driver instance I get this error.

Just to log: my solution for that was close the app and open it again via driver.launchApp(), and between that a command to simulate push/notification.

**Comment by mayureshshirodkar** [comment]
Facing the same issue. Below is the log:

info: [debug] Responding to client with success: {"status":0,"value":"","sessionId":"ed0f8e7d-14f0-4e05-9e42-7aaa19f5e816"}
info: <-- POST /wd/hub/session/ed0f8e7d-14f0-4e05-9e42-7aaa19f5e816/refresh 200 16.613 ms - 74 {"status":0,"value":"","sessionId":"ed0f8e7d-14f0-4e05-9e42-7aaa19f5e816"}

info: [debug] [INST] 2016-07-14 22:13:03 +0000 Fail: The target application appears to have died

info: [debug] [INST STDERR] 2016-07-14 18:13:04.054 instruments[14689:9326122] Attempting to change event horizon while disengage

info: [debug] [INST] Instruments Trace Complete (Duration : 641.779785s; Output : /tmp/appium-instruments/instrumentscli0.trace)

info: [debug] [INSTSERVER] Instruments exited with code 0

info: [debug] Cleaning up after instruments exit
info: [debug] Instruments exited unexpectedly
info: [debug] Shutting down command proxy and ignoring any errors
info: [debug] Destroying instruments client socket.
info: [debug] Closing socket server.
info: [debug] Instruments socket server was closed
info: [debug] Stopping iOS log capture
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killing any other simulator daemons
info: [debug] Killall Simulator
info: [debug] [REMOTE] Disconnecting from remote debugger
info: [debug] fullReset requested. Will try to uninstall the app.

info: --> POST /wd/hub/session/ed0f8e7d-14f0-4e05-9e42-7aaa19f5e816/element {"using":"xpath","value":"//div/a[1]/span"}

error: Error getting source, can't continue finding element by XPath

info: [debug] Waiting up to 0ms for condition
info: [debug] Pushing command to appium work queue: "au.mainApp().getTreeForXML()"
info: [debug] Condition unmet after 1ms. Timing out.
info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command. (Original error: Bad response from getTreeForXML. Err was undefined and res was undefined)","origValue":"Bad response from getTreeForXML. Err was undefined and res was undefined"},"sessionId":"ed0f8e7d-14f0-4e05-9e42-7aaa19f5e816"}
info: <-- POST /wd/hub/session/ed0f8e7d-14f0-4e05-9e42-7aaa19f5e816/element 500 2.797 ms - 332 

info: --> GET /wd/hub/session/ed0f8e7d-14f0-4e05-9e42-7aaa19f5e816/screenshot {}
info: [debug] Pushing command to appium work queue: "au.getScreenOrientation()"
info: [debug] Pushing command to appium work queue: "au.capture('screenshotfeb213d5-231d-44a8-9075-8d996b2d2f10')"
info: [debug] Waiting 10000 ms for screenshot to ge generated.

info: [debug] Removed com.eab.se

info: [debug] Cleaning up appium session

error: Unhandled error: TypeError: cb is not a function
    at /usr/local/lib/node_modules/appium/lib/devices/ios/ios-controller.js:1292:24
    at Object.async.until (/usr/local/lib/node_modules/appium/node_modules/async/lib/async.js:712:13)
    at /usr/local/lib/node_modules/appium/node_modules/async/lib/async.js:708:23
    at ReadFileContext.callback (/usr/local/lib/node_modules/appium/lib/devices/ios/ios-controller.js:1286:19)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:324:13) context: [GET /wd/hub/session/ed0f8e7d-14f0-4e05-9e42-7aaa19f5e816/screenshot {}]

info: --> GET /wd/hub/status {}
