### ISSUE TITLE
1.3.4 - Android's doTouchDrag crashes

### ISSUE THREAD

**Issue by sbonebrake** [appium/appium#4255]
Using Appium v1.3.4 (REV e9bd71460fc080648d968e87515677030b7dcade)
In ruby_lib I create the following action:

``` ruby
TouchAction.new.long_press(x: 250, y: 700, duration: 250).move_to(x: 250, y: 200).release.perform
```

Maybe this is because i'm not using an element, but I think it should work without one:

There is a special case for longPress, moveTo, release at
https://github.com/appium/appium/blob/master/lib/devices/android/android-controller.js#L973

This causes appium to crash entirely:

```
info: --> POST /wd/hub/session/ae807300-6dbb-4205-ae37-28710c7318b6/touch/perform {"actions":[{"action":"longPress","options":{"x":250,"y":700}},{"action":"moveTo","options":{"x":250,"y":200}},{"action":"release"}]}
info: [debug] Pushing command to appium work queue: ["element:getLocation",{}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:getLocation","params":{}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: getLocation
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":7}
error: Unhandled error: TypeError: Cannot read property 'x' of undefined
    at null.<anonymous> (/Users/sbonebrake/Code/appium/lib/devices/android/android-controller.js:871:29)
    at next (/Users/sbonebrake/Code/appium/node_modules/async/lib/async.js:801:43)
    at /Users/sbonebrake/Code/appium/node_modules/async/lib/async.js:32:16
    at exports.respond (/Users/sbonebrake/Code/appium/lib/devices/common.js:28:9)
    at null.<anonymous> (/Users/sbonebrake/Code/appium/lib/devices/android/android.js:497:16)
    at null.<anonymous> (/Users/sbonebrake/Code/appium/lib/devices/android/uiautomator.js:93:9)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10) context: [POST /wd/hub/session {"desiredCapabilities":{"deviceType":"phone","platform":"Mac","platformName":"Android","deviceName":"Android Emulator","platformVersion":"4.4"]
```

**Comment by SrinivasanTarget** [comment]
Closing this because of inactivity. @triager please close
