### ISSUE TITLE
Could not determine Xcode version error

### ISSUE THREAD

**Issue by vladisx** [appium/appium#4280]
Using Appium 1.3.3 and Java 2.1 sometimes I am getting this error in appium console:

2014-12-17 08:12:36:005 - info: [debug] Setting Xcode folder
2014-12-17 08:12:36:446 - info: [debug] Setting Xcode version
2014-12-17 08:12:39:504 - info: [debug] Setting iOS SDK Version
2014-12-17 08:12:39:502 - error: Could not determine Xcode version:Could not parse Xcode version (xcodebuild output was: )
2014-12-17 08:12:41:142 - info: [debug] Getting sdk version from xcrun with a timeout
2014-12-17 08:12:41:212 - info: [debug] iOS SDK Version set to 8.1
2014-12-17 08:12:41:212 - info: [debug] Checking whether instruments supports our device string
2014-12-17 08:12:41:213 - info: [debug] Getting list of devices instruments supports
2014-12-17 08:12:41:273 - info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
2014-12-17 08:12:53:305 - error: Failed getting devices. Err: Error: Command failed: . Stdout: . Stderr: 
2014-12-17 08:12:53:307 - info: [debug] Getting list of devices instruments supports
2014-12-17 08:12:53:314 - info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
2014-12-17 08:12:54:290 - info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":null,"iOSSDKVersion":"8.1","deviceName":"iPhone 5s","platformVersion":"7.1"}
2014-12-17 08:12:54:355 - error: Unhandled error: TypeError: Cannot read property '0' of null
    at Function.IOS.getDeviceStringFromOpts (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js:924:35)
    at IOS.getDeviceString (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js:1005:14)
    at null.<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js:1089:24)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:525:46
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:254:17
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:151:21
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:251:21
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:615:34
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:516:25
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-instruments/lib/instruments.js:111:7 context: [POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/vladr/Documents/Developer/workspaceBuild/mobileNativeIOS/IBMECM/build/Debug-iphonesimulator/Navigator.app","showIOSLog":true,"platformVersion":"7.1","bundleId":"c]

**Comment by vladisx** [comment]
It happens more frequently after calling to driver.resetApp()

**Comment by KazuCocoa** [comment]
Once I tried re-select xcode path with xcode-select, the error fixed.

```$ sudo xcode-select -s /Applications/Xcode.app/Contents/Developer/```

( I used Appium 1.3.5, Xcode6.1.1 )

**Comment by 0x1mason** [comment]
#4556 should resolve this problem.

**Comment by SrinivasanTarget** [comment]
Not able to repro this in Appium 1.5.Closing this.

**Comment by SrinivasanTarget** [comment]
@triager please close
