### ISSUE TITLE
selendroid error：[SELENDROID ERR] ENOENT(No such file or directory)

### ISSUE THREAD

**Issue by abyssalknight** [appium/appium#4302]
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/session/1f5bb3fc-0613-5fad-b790-86c77041b7eb","method":"GET"}
> info: [debug] Proxied response received with status 200: "{\"value\":{\"automationName\":\"selendroid\",\"platform\":\"android\",\"app\":\"E:\\\\mobileTest\\\\CinemaTest\\\\apps\\\\2345Cinema(100)2.3.9.RSO.apk\",\"acceptSslCerts\":true,\"javascriptEnabled\":true,\"browserName\":\"selendroid\",\"networkConnectionEnabled\":true,\"rotatable\":true,\"desired\":{\"automationName\":\"Selendroid\",\"app\":\"E:\\\\mobileTest\\\\CinemaTest\\\\apps\\\\2345Cinema(100)2.3.9.RSO.apk\",\"platformVersion\":\"4.1\",\"platformName\":\"Android\",\"deviceName\":\"Android Emulator\",\"browserName\":\"\"},\"version\":\"0.12.0\",\"platformVersion\":\"16\",\"platformName\":\"android\",\"deviceName\":\"Android Emulator\",\"handlesAlerts\":true,\"warnings\":{},\"takesScreenshot\":true},\"status\":0,\"sessionId\":\"1f5bb3fc-0613-5fad-b790-86c77041b7eb\"}"
> info: <-- GET /wd/hub/session/1f5bb3fc-0613-5fad-b790-86c77041b7eb 200 40.378 ms - 686 
> info: --> POST /wd/hub/session/1f5bb3fc-0613-5fad-b790-86c77041b7eb/timeouts/implicit_wait {"ms":10000}
> info: [debug] Proxying command to localhost:8080
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/session/1f5bb3fc-0613-5fad-b790-86c77041b7eb/timeouts/implicit_wait","method":"POST","json":{"ms":10000}}
> info: [debug] Proxied response received with status 200: {"value":"","status":0,"sessionId":"1f5bb3fc-0613-5fad-b790-86c77041b7eb"}
> info: <-- POST /wd/hub/session/1f5bb3fc-0613-5fad-b790-86c77041b7eb/timeouts/implicit_wait 200 35.482 ms - 74 
> info: [debug] [SELENDROID ERR] ENOENT (No such file or directory)
> info: [debug] [SELENDROID ERR] 	at libcore.io.IoBridge.open(IoBridge.java:416)
> info: [debug] [SELENDROID ERR] 	at java.io.FileInputStream.<init>(FileInputStream.java:78)
> info: [debug] [SELENDROID ERR] 	at com.cinema2345.f.i.e(FileCache.java:273)
> info: [debug] [SELENDROID ERR] 	at com.cinema2345.service.NetWorkService.a(NetWorkService.java:135)
> info: [debug] [SELENDROID ERR] 	at com.cinema2345.activity.ae.run(MainActivity.java:261)
> info: [debug] [SELENDROID ERR] 	at java.lang.Thread.run(Thread.java:864)
> info: [debug] [SELENDROID ERR] ENOENT (No such file or directory)
> info: [debug] [SELENDROID ERR] 	at libcore.io.Posix.open(Native Method)
> info: [debug] [SELENDROID ERR] 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
> info: [debug] [SELENDROID ERR] 	at libcore.io.IoBridge.open(IoBridge.java:400)
> info: [debug] [SELENDROID ERR] 	... 5 more
> info: [debug] [SELENDROID] mSeq=0 mSystemUiVisibility=0x0
> info: [debug] [SELENDROID] mSystemDecorRect=[0,38][480,800] last=[0,38][480,800]
> Killed Node Server.
> Node Server Process Ended

**Comment by sebv** [comment]
Is this still happening?

**Comment by sebv** [comment]
Closing, old issue, no activity (Sorry for our late response), may be reopened if needed.
