### ISSUE TITLE
driver.setLocation() method not working with android device/simulator

### ISSUE THREAD

**Issue by hungl** [appium/appium#4309]
Hi,

I am trying to set geo location for my app every time it runs a test. I use driver.setLocation(). It works perfectly for iOS, but does not work for Android. It does not work on genymotion as well as Android device. The app starts and shut down right away, and the test fails. I'm running tests on Appium 1.3.4
Here are the logs:

IDE log:

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 7 milliseconds
Build info: version: '2.43.1', revision: '5163bceef1bc36d43f3dc0b83c88998168a363a0', time: '2014-09-10 09:43:55'
System info: host: 'Hungs-MacBook-Pro.local', ip: '192.168.1.14', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.5', java.version: '1.7.0_71'
Session ID: 09069989-3dd7-4182-8b06-73f304b29344
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{automationName=Appium, platform=LINUX, app=/Users/hunglac/Documents/tests-mobile-ui/xxxxx-android/xxxxx.apk, javascriptEnabled=true, appActivity=.ui.splash.SplashActivity, browserName=Android, networkConnectionEnabled=true, desired={automationName=Appium, app=/Users/hunglac/Documents/tests-mobile-ui/xxxxxx-android/xxxxxx.apk, fullReset=true, deviceName=Android Emulator, platformName=Android, appActivity=.ui.splash.SplashActivity, appWaitActivity=.ui.login.LoginActivity,.ui.splash.SplashActivity, appPackage=com.xxxxxx.ordering, noReset=true}, locationContextEnabled=false, appPackage=com.xxx.ordering, noReset=true, platformVersion=4.1, databaseEnabled=false, fullReset=true, deviceName=Android Emulator, platformName=Android, webStorageEnabled=false, appWaitActivity=.ui.login.LoginActivity,.ui.splash.SplashActivity, warnings={}, takesScreenshot=true}]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
    at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:180)
    at io.appium.java_client.AppiumExecutionMethod.execute(AppiumExecutionMethod.java:22)
    at org.openqa.selenium.remote.html5.RemoteLocationContext.setLocation(RemoteLocationContext.java:49)
    at io.appium.java_client.AppiumDriver.setLocation(AppiumDriver.java:602)
    at com.ncr.automation.tools.AutomatedTest.setUp(AutomatedTest.java:76)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)

Appium log:

info: [debug] Sending telnet command to device: geo fix -104.984859 39.738436
info: [debug] Getting running emulator port
error: Unhandled error: Error: connect EADDRNOTAVAIL
    at errnoException (net.js:904:11)
    at connect (net.js:766:19)
    at net.js:845:9
    at asyncCallback (dns.js:68:16)
    at Object.onanswer [as oncomplete](dns.js:121:9) context: [POST /wd/hub/session/016087f6-3038-43ed-b151-9a3e1edcc660/location {"location":{"altitude":33,"class":"org.openqa.selenium.html5.Location","longitude":-104.984859,"latitude":39.738436,"hCode":2079822107}}]
info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command.","origValue":"Could not set geolocation via telnet to device"},"sessionId":"016087f6-3038-43ed-b151-9a3e1edcc660"}
info: <-- POST /wd/hub/session/016087f6-3038-43ed-b151-9a3e1edcc660/location 500 1.635 ms - 215 
info: --> DELETE /wd/hub/session/016087f6-3038-43ed-b151-9a3e1edcc660 {}

**Comment by jlipps** [comment]
Can you please provide a full set of logs from running against an emulator? It definitely won't work on a real android device (see #3259). But it does work against emulators.

**Comment by luonglne** [comment]
Hi jlipss,

I saw lots of comments mentioning that setLocation() only works on emulator (Android) and simulator (iOS).  Do you know if Appium plans to implement this function to work on the real devices both Android and iOS?  Or it is an impossible thing to hack that Appium won't look into it any longer?

**Comment by jlipps** [comment]
we can't do it on android because we need root. I thought it did work on real iOS devices...?

**Comment by luonglne** [comment]
I tried it on the real iPhone 6, and it didn't work.  I wonder whether anyone else has any success with the real iOS devices.

**Comment by jlipps** [comment]
It's possible it doesn't work; I haven't tried it myself

**Comment by tajmulhussainr** [comment]
Could you please help me to set mock location in emulator. I'm using geny motion android emulator and getting following error.

Here is my code 

        File app = new File(Constant.appDir, "xxxx.apk"); 
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(CapabilityType.BROWSER_NAME, "");
        capabilities.setCapability("deviceName", Constant.DeviceName);
        capabilities.setCapability("platformVersion", Constant.PlatformVersion);
        capabilities.setCapability("platformName","Android");
        capabilities.setCapability("app", app.getAbsolutePath());
        driver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);

      // Setting mock location
      Location location = new Location(77.59974003, 12.91024781, 909);
      driver.setLocation(location);

-Thanks in advance

appium log 

info: [debug] Responding to client with success: {"status":0,"value":{"platform":"LINUX","browserName":"","platformVersion":"4.4.4","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platformVersion":"4.4.4","app":"/Users/xxxxxx/Downloads/xxxxxxx.apk","deviceName":"BUZHL7TWWSOVQ8D6","platformName":"Android","browserName":""},"app":"/Users/xxxxxxx/Downloads/xxxxxxxx.apk","deviceName":"BUZHL7TWWSOVQ8D6","platformName":"Android"},"sessionId":"61947353-41d1-4026-9125-4b883182180e"}
info: <-- GET /wd/hub/session/61947353-41d1-4026-9125-4b883182180e 200 1.064 ms - 631 {"status":0,"value":{"platform":"LINUX","browserName":"","platformVersion":"4.4.4","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platformVersion":"4.4.4","app":"/Users/xxx/Downloads/xxxxxxx.apk","deviceName":"BUZHL7TWWSOVQ8D6","platformName":"Android","browserName":""},"app":"/Users/tajmulhussain/Downloads/xxxxxxx.apk","deviceName":"BUZHL7TWWSOVQ8D6","platformName":"Android"},"sessionId":"61947353-41d1-4026-9125-4b883182180e"}

info: --> POST /wd/hub/session/61947353-41d1-4026-9125-4b883182180e/timeouts/implicit_wait {"ms":10000}
info: [debug] Set Android implicit wait to 10000ms
info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"61947353-41d1-4026-9125-4b883182180e"}
info: <-- POST /wd/hub/session/61947353-41d1-4026-9125-4b883182180e/timeouts/implicit_wait 200 1.485 ms - 76 {"status":0,"value":null,"sessionId":"61947353-41d1-4026-9125-4b883182180e"}

info: --> POST /wd/hub/session/61947353-41d1-4026-9125-4b883182180e/location {"location":{"altitude":909,"class":"org.openqa.selenium.html5.Location","longitude":12.91024781,"latitude":77.59974003,"hCode":1224243735}}
info: [debug] Sending telnet command to device: geo fix 12.91024781 77.59974003
info: [debug] Getting running emulator port
info: <-- POST /wd/hub/session/61947353-41d1-4026-9125-4b883182180e/location 500 2.910 ms - 87 

RangeError: port should be > 0 and < 65536: 0
    at Socket.connect (net.js:901:13)
    at Object.exports.connect.exports.createConnection (net.js:92:35)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-adb/lib/adb.js:1503:20
    at ADB.getEmulatorPort (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-adb/lib/adb.js:641:12)
    at ADB.sendTelnetCommand (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-adb/lib/adb.js:1501:8)
    at androidController.setLocation (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/android/android-controller.js:696:12)
    at Object.exports.setLocation [as handle] (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/server/controller.js:846:14)
    at next_layer (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:113:13)
    at Route.dispatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:117:5)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/index.js:222:24

info: --> DELETE /wd/hub/session/61947353-41d1-4026-9125-4b883182180e {}
info: Shutting down appium session
info: [debug] Pressing the HOME button
info: [debug] executing cmd: /Users/xxx/Library/Android/sdk/platform-tools/adb -s 192.168.56.101:5555 shell "input keyevent 3"

info: [debug] Stopping logcat capture

info: [debug] Logcat terminated with code null, signal SIGTERM

console log
org.openqa.selenium.WebDriverException: ERROR running Appium command: port should be > 0 and < 65536: 0
Command duration or timeout: 20 milliseconds
Build info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:03:00'
System info: host: 'Tajmuls-MacBook-Pro.local', ip: '172.16.6.51', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.2', java.version: '1.7.0_71'
Session ID: 402bf760-655b-4b65-a381-0e65c34affe1
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{platformVersion=4.4.4, app=/Users/tajmulhussain/Downloads/fabric-droid-releaseConfig-debug.apk, platform=LINUX, databaseEnabled=false, javascriptEnabled=true, deviceName=BUZHL7TWWSOVQ8D6, platformName=Android, browserName=, webStorageEnabled=false, networkConnectionEnabled=true, desired={app=/Users/tajmulhussain/Downloads/fabric-droid-releaseConfig-debug.apk, platformVersion=4.4.4, platformName=Android, deviceName=BUZHL7TWWSOVQ8D6, browserName=}, locationContextEnabled=false, warnings={}, takesScreenshot=true}]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
    at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:180)
    at io.appium.java_client.AppiumExecutionMethod.execute(AppiumExecutionMethod.java:22)
    at org.openqa.selenium.remote.html5.RemoteLocationContext.setLocation(RemoteLocationContext.java:49)
    at io.appium.java_client.AppiumDriver.setLocation(AppiumDriver.java:602)
    at com.test.Functional.test(Functional.java:45)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
    at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
    at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
    at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
    at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
    at org.testng.TestRunner.privateRun(TestRunner.java:767)
    at org.testng.TestRunner.run(TestRunner.java:617)
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
    at org.testng.SuiteRunner.run(SuiteRunner.java:240)
    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
    at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
    at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
    at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
    at org.testng.TestNG.run(TestNG.java:1057)
    at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
    at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
    at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)

**Comment by hungl** [comment]
I don't think setLocation works on Geny Motion simulator. I tried. But let me know if you can make it work.

**Comment by sergioescoto** [comment]
While I have not gotten driver setLocation to work, I was thinking maybe you could write some script or method to interact with the genymotion shell and set the GPS location that way.

**Comment by amedvedjev** [comment]
there is a solution for genymotion programmatically set needed GPS location.
genymotion console has following commands: 
 - gps setstatus enabled
 - gps setlatitude XX.xxxxx
 - gps setlongitude XX.xxxx

i successfully managed to do same java code.

in test code it is look like:
 - start genymotion emulator with needed device name
 - after app start open genymotion console and execute needed commands
 - continue test

**Comment by sebv** [comment]
TODO: investigate better genymotion support.

**Comment by aluedeke** [comment]
hey why not just implementing a app which provides a mock location provider? This should work for Android on Genymotion, Emulator and Real devices!

**Comment by tajmulhussainr** [comment]
@aluedeke - I solved the issue by setting up mock locations using fakegps app in my tests.

**Comment by clample** [comment]
I just tried setting mock location on a real device with Appium 1.5.3 and it worked. I think that this issue could be closed since this has been resolved in more recent Appium versions.

**Comment by jlipps** [comment]
I'm not sure why I pulled this into a sprint as it apparently works already. Thanks @clample.

**Comment by ibizaman** [comment]
Sorry for necrobumping this but on appium 1.6.3, I couldn't make `setLocation()` work without going in the emulator's developer menu and enabling the `io.appium.settings` as the mock location app.

Well there's a pretty easy way to grant mock_location_provider permission to appium automatically: `adb shell pm grant io.appium.settings android.permission.ACCESS_MOCK_LOCATION`. I just found it from http://stackoverflow.com/a/38587260/1013628.

By running this at the beginning of the tests, I can make `setLocation()` work in an emulator with a freshly created emulator.

**Comment by mykola-mokhnach** [comment]
@ibizaman This all has been recently [implemented](https://github.com/appium/appium-adb/pull/208/files) in Appium@1.6.4-beta

**Comment by ibizaman** [comment]
@mykola-mokhnach thanks! Missed that version, sorry.
