### ISSUE TITLE
Multitouch API with tap and hold command fails with:  Cannot read property 'element' of undefined

### ISSUE THREAD

**Issue by glorylo** [appium/appium#4310]
Tapping and holding use to work in 1.2.9 however in 1.3.4 we get a cannot read property 'element' of undefined issue.  I am using precise coordinates on my tap and hold command and i suspect this has something to do w/ the element property not found.

``` 
new TouchAction(driver)
                .Press(center.X, center.Y)
                .Wait(seconds * 1000)
                .Release()
                .Perform(); 
```

```
> info: <-- GET /wd/hub/session/22ef432c-d8e5-4d7d-85b0-762c5af029fe/element/27/size 200 39.835 ms - 98 {"status":0,"value":{"width":149,"height":117},"sessionId":"22ef432c-d8e5-4d7d-85b0-762c5af029fe"}
> info: --> POST /wd/hub/session/22ef432c-d8e5-4d7d-85b0-762c5af029fe/touch/perform {"actions":[{"action":"press","options":{"x":1002,"y":1714}},{"action":"wait","options":{"ms":12000}},{"action":"release"}]}
> info: <-- POST /wd/hub/session/22ef432c-d8e5-4d7d-85b0-762c5af029fe/touch/perform 500 2.281 ms - 97 
> TypeError: Cannot read property 'element' of undefined
>     at null.<anonymous> (C:\Apps\Appium_1.3.4\node_modules\appium\lib\devices\android\android-controller.js:901:26)
>     at androidController.performTouch (C:\Apps\Appium_1.3.4\node_modules\appium\lib\devices\android\android-controller.js:985:5)
>     at Object.exports.performTouch [as handle] (C:\Apps\Appium_1.3.4\node_modules\appium\lib\server\controller.js:331:14)
>     at next_layer (C:\Apps\Appium_1.3.4\node_modules\appium\node_modules\express\lib\router\route.js:113:13)
>     at Route.dispatch (C:\Apps\Appium_1.3.4\node_modules\appium\node_modules\express\lib\router\route.js:117:5)
>     at C:\Apps\Appium_1.3.4\node_modules\appium\node_modules\express\lib\router\index.js:222:24
>     at param (C:\Apps\Appium_1.3.4\node_modules\appium\node_modules\express\lib\router\index.js:307:14)
>     at param (C:\Apps\Appium_1.3.4\node_modules\appium\node_modules\express\lib\router\index.js:323:14)
>     at Function.proto.process_params (C:\Apps\Appium_1.3.4\node_modules\appium\node_modules\express\lib\router\index.js:367:3)
>     at next (C:\Apps\Appium_1.3.4\node_modules\appium\node_modules\express\lib\router\index.js:216:19)
> info: [debug] Didn't get a new command in 60 secs, shutting down...
> info: Shutting down appium session
> info: [debug] Pressing the HOME button
> info: [debug] executing cmd: C:\Apps\adt\sdk\platform-tools\adb.exe -s 035e156913ad31ec shell "input keyevent 3"
> info: [debug] Stopping logcat capture
```

**Comment by imurchie** [comment]
What client are you using? I'm trying to reproduce.

**Comment by glorylo** [comment]
Using .net client testing on real device (nexus 5)

**Comment by imurchie** [comment]
The problem is that the dotnet driver doesn't send in options with the `release` action, and the server expects them. I've opened a pull request to handle the case on the server-side (#4339). Could you pull that and try?

**Comment by glorylo** [comment]
I am on vacation..  If you guys can wait when I am back I will try it!

**Comment by glorylo** [comment]
i verified on master and tap and hold works!  thanks @imurchie !
