### ISSUE TITLE
Adb restart during the test cause issue

### ISSUE THREAD

**Issue by lyzero** [appium/appium#4328]
As part of the test, adb will be stoped and restarted. This actually causes appium session lost. How should I deal with this situation.

Log attached:
error: UiAutomator quit before it successfully launched
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: UiAutomator quit before it successfully launched
info: [debug] Error: UiAutomator quit before it successfully launched
    at null.<anonymous> (/usr/local/lib/node_modules/appium/lib/devices/android/android.js:202:23)
    at Object.async.eachSeries (/usr/local/lib/node_modules/appium/node_modules/async/lib/async.js:145:20)
    at androidHybrid.stopChromedriverProxies (/usr/local/lib/node_modules/appium/lib/devices/android/android-hybrid.js:234:9)
    at null.<anonymous> (/usr/local/lib/node_modules/appium/lib/devices/android/android.js:197:10)
    at null.<anonymous> (/usr/local/lib/node_modules/appium/lib/devices/android/android.js:219:9)
    at androidCommon.uninstallApp (/usr/local/lib/node_modules/appium/lib/devices/android/android-common.js:465:5)
    at null.<anonymous> (/usr/local/lib/node_modules/appium/lib/devices/android/android.js:217:12)
    at null.<anonymous> (/usr/local/lib/node_modules/appium/lib/devices/android/android.js:226:11)
    at /usr/local/lib/node_modules/appium/node_modules/appium-adb/lib/adb.js:902:7
    at null.<anonymous> (/usr/local/lib/node_modules/appium/node_modules/appium-adb/lib/adb.js:172:9)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: UiAutomator quit before it successfully launched)","origValue":"UiAutomator quit before it successfully launched"},"sessionId":null}
info: <-- POST /wd/hub/session 500 260354.273 ms - 218

**Comment by moizjv** [comment]
@lyzero appium heavily relies on adb, I am not sure if there is work around that.

**Comment by moizjv** [comment]
@lyzero why do you want to restart adb, if its a valid usecase we can think about a feature request?

**Comment by sebv** [comment]
Closing, no activity, may be reopened if needed.
