### ISSUE TITLE
Could not launch native app on android mobile using appium v.1.3.4

### ISSUE THREAD

**Issue by sakthithasan** [appium/appium#4389]
Hi All,

I just started working in latest appium and client libraries (Java). I am getting an error "error: Logcat capture failed: spawn ENOENT", Also my app is not launching in the android device. Please help me with this issue. Please find the below appium logs.

My Capabilities are,
File app = new File("./APK/", "EriBank_com.experitest.ExperiBank_1.0_1.apk");
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "");
capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "52b60143");
capabilities.setCapability(MobileCapabilityType.APP, app.getAbsolutePath());
capabilities.setCapability(MobileCapabilityType.APP_ACTIVITY, "com.experitest.ExperiBank.LoginActivity");
capabilities.setCapability(MobileCapabilityType.APP_PACKAGE, "com.experitest.ExperiBank");
driver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);

Appium logs:
> Starting Node Server
> info: Welcome to Appium v1.3.4 (REV c8c79a85fbd6870cd6fc3d66d038a115ebe22efe)
> info: Appium REST http interface listener started on 127.0.0.1:4723
> info: [debug] Non-default server args: {"address":"127.0.0.1","logNoColors":true,"platformName":"Android","platformVersion":"18","automationName":"Appium"}
> info: Console LogLevel: debug
> info: --> POST /wd/hub/session {"desiredCapabilities":{"app":"C:\\Users\\28474\\workspace\\Appium_Native\\.\\APK\\EriBank_com.experitest.ExperiBank_1.0_1.apk","deviceName":"52b60143","platformName":"Android","appActivity":"com.experitest.ExperiBank.LoginActivity","browserName":"","appPackage":"com.experitest.ExperiBank"}}
> info: Client User-Agent string: Apache-HttpClient/4.3.2 (java 1.5)
> info: [debug] Using local app from desired caps: C:\Users\28474\workspace\Appium_Native\APK\EriBank_com.experitest.ExperiBank_1.0_1.apk
> info: [debug] Creating new appium session c33bb190-bcf4-48fd-8ebe-26924376198e
> info: Starting android appium
> info: [debug] Getting Java version
> info: Java version is: 1.7.0_60
> info: [debug] Using fast reset? true
> info: [debug] Preparing device for session
> info: [debug] Checking whether app is actually present
> info: [debug] Checking whether adb is present
> warn: The ANDROID_HOME environment variable is not set to the Android SDK root directory path. ANDROID_HOME is required for compatibility with SDK 23+. Checking along PATH for adb.
> info: [debug] executing cmd: where adb
> info: [debug] Using adb from D:\adt-bundle-windows-x86-20140321\sdk\platform-tools\adb.exe
> 
> info: Retrieving device
> info: [debug] Trying to find a connected android device
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: "D:\adt-bundle-windows-x86-20140321\sdk\platform-tools\adb.exe" devices
> info: [debug] 1 device(s) connected
> info: Found device 52b60143
> info: [debug] Setting device id to 52b60143
> info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
> info: [debug] executing cmd: "D:\adt-bundle-windows-x86-20140321\sdk\platform-tools\adb.exe" -s 52b60143 wait-for-device
> info: [debug] executing cmd: "D:\adt-bundle-windows-x86-20140321\sdk\platform-tools\adb.exe" -s 52b60143 shell "echo 'ready'"
> info: [debug] Starting logcat capture
> error: Logcat capture failed: spawn ENOENT
> info: [debug] Stopping logcat capture
> Killed Node Server.
> Node Server Process Ended

**Comment by amedvedjev** [comment]
if you run "adb.exe" while device connected to PC is device name "52b60143" get printed out?

**Comment by sakthithasan** [comment]
yes.. it does... you could see it in appium logs as well that device is connected and its found.

**Comment by amedvedjev** [comment]
indeed. you have 1 device connected why not to try:
capabilities = DesiredCapabilities.android();
capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "Appium");
capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "Android");
capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, MobilePlatform.ANDROID);
capabilities.setCapability(MobileCapabilityType.APP_ACTIVITY, ".LoginActivity");
capabilities.setCapability(MobileCapabilityType.APP_PACKAGE, "com.experitest.ExperiBank");
capabilities.setCapability(MobileCapabilityType.APP, app.getAbsolutePath());
driver = new AndroidDriver(new URL("http://127.0.0.1:4725/wd/hub"), capabilities);

**Comment by sakthithasan** [comment]
Yes I tried with capabilities you mentioned above, now also am unable to launch application.. Please guide.

Appium logs:
> Starting Node Server
> info: Welcome to Appium v1.3.4 (REV c8c79a85fbd6870cd6fc3d66d038a115ebe22efe)
> info: Appium REST http interface listener started on 127.0.0.1:4723
> info: [debug] Non-default server args: {"address":"127.0.0.1","logNoColors":true,"platformName":"Android","platformVersion":"18","automationName":"Appium"}
> info: Console LogLevel: debug
> info: --> POST /wd/hub/session {"desiredCapabilities":{"automationName":"Appium","app":"C:\\Users\\28474\\workspace\\Appium_Native\\.\\APK\\Facebook_com.facebook.katana_24.0.0.30.15_5955490.apk","platform":"ANDROID","platformName":"Android","deviceName":"52b60143","appActivity":"com.facebook.katna.FacebookLoginActivity","browserName":"android","appPackage":"com.facebook.katan","version":""}}
> info: Client User-Agent string: Apache-HttpClient/4.3.2 (java 1.5)
> info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : platform, version
> info: [debug] Using local app from desired caps: C:\Users\28474\workspace\Appium_Native\APK\Facebook_com.facebook.katana_24.0.0.30.15_5955490.apk
> info: [debug] Creating new appium session dd543ea6-636d-4681-bde1-bee649600ed4
> info: Starting android appium
> info: [debug] Getting Java version
> info: Java version is: 1.7.0_60
> info: [debug] Using fast reset? true
> info: [debug] Preparing device for session
> error: Unhandled error: Error: ENOENT, no such file or directory 'D:\adt-bundle-windows-x86-20140702;\build-tools'
>     at Object.fs.readdirSync (fs.js:654:18)
>     at exports.getDirectories (C:\Users\28474\Downloads\Appium\node_modules\appium\node_modules\appium-adb\lib\helpers.js:99:18)
>     at ADB.checkSdkBinaryPresent (C:\Users\28474\Downloads\Appium\node_modules\appium\node_modules\appium-adb\lib\adb.js:89:25)
>     at ADB.checkAdbPresent (C:\Users\28474\Downloads\Appium\node_modules\appium\node_modules\appium-adb\lib\adb.js:126:8)
>     at null.<anonymous> (C:\Users\28474\Downloads\Appium\node_modules\appium\lib\devices\android\android-common.js:325:30)
>     at C:\Users\28474\Downloads\Appium\node_modules\appium\node_modules\async\lib\async.js:610:21
>     at C:\Users\28474\Downloads\Appium\node_modules\appium\node_modules\async\lib\async.js:249:17
>     at iterate (C:\Users\28474\Downloads\Appium\node_modules\appium\node_modules\async\lib\async.js:149:13)
> info: [debug] Checking whether app is actually present
>     at C:\Users\28474\Downloads\Appium\node_modules\appium\node_modules\async\lib\async.js:160:25
>     at C:\Users\28474\Downloads\Appium\node_modules\appium\node_modules\async\lib\async.js:251:21 context: [POST /wd/hub/session {"desiredCapabilities":{"automationName":"Appium","app":"C:\\Users\\28474\\workspace\\Appium_Native\\.\\APK\\Facebook_com.facebook.katana_24.0.0.30.15_5955490.apk","platform":"ANDROID","platformName":]
> info: [debug] Checking whether adb is present

**Comment by amedvedjev** [comment]
try google with "adb server is out of date"

**Comment by moizjv** [comment]
@sakthithasan is this still and issue? Can you try with latest appium version and try running as admin?

**Comment by sebv** [comment]
Closing, no activity, may be reopened if needed.

**Comment by Rakeshvallabhaneni** [comment]
@moizjv @sebv @sakthithasan 

Error: Could not find adb. Please set the ANDROID_HOME environment variable with the Android SDK root directory path.


Still this issue is noticed with the appium 1.3.3 and 1.3.6 and 1.4.3 .. while starting appium server through java code the below error log is displayed .

Appium start server code :+1:
public static void startAppiumServer() throws ExecuteException,
IOException, InterruptedException {

CommandLine command = new CommandLine(
"/usr/local/bin/node");
command.addArgument(
"/usr/local/lib/node_modules/appium/bin/appium.js",
false);
command.addArgument("--address", false);
command.addArgument("127.0.0.1");
command.addArgument("--port", false);
command.addArgument("4723");
command.addArgument("--no-reset", false);
DefaultExecuteResultHandler resultHandler = new DefaultExecuteResultHandler();
DefaultExecutor executor = new DefaultExecutor();
executor.setExitValue(1);
executor.execute(command, resultHandler);

Thread.sleep(5000);
System.out.println("Appium server started");

}

Error Log :
[TestNG] Running:
/private/var/folders/gd/c4rghf9d5zv8phtq6zbf99t40000gp/T/testng-eclipse--418167106/testng-customsuite.xml

Appium server stop
Appium server started
[36minfo[39m: Welcome to Appium v1.4.3 (REV a357c7f)
[36minfo[39m: Appium REST http interface listener started on 127.0.0.1:4723
[36minfo[39m: [debug] Non-default server args: {"address":"127.0.0.1","noReset":true}
[36minfo[39m: Console LogLevel: debug
log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
log4j:WARN Please initialize the log4j system properly.
[36minfo[39m: [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m [90m{"desiredCapabilities":{"platformVersion":"5.0.1","platformName":"Android","deviceName":"HTC One_M8","browserName":"Android","appActivity":"com.digby.lptester.activity.DetailsActivity","uuid":"SH43WWM15617","appPackage":"com.digby.lptester"}}[39m
[36minfo[39m: Client User-Agent string: Apache-HttpClient/4.3.3 (java 1.5)
[36minfo[39m: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : uuid
[36minfo[39m: [debug] Didn't get app but did get Android package, will attempt to launch it on the device
[36minfo[39m: [debug] Creating new appium session e408a90a-d0a9-42e9-9b68-7f7c3659607d
[36minfo[39m: Starting android appium
[36minfo[39m: [debug] Getting Java version
[36minfo[39m: Java version is: 1.8.0_25
[36minfo[39m: [debug] Checking whether adb is present
[33mwarn[39m: The ANDROID_HOME environment variable is not set to the Android SDK root directory path. ANDROID_HOME is required for compatibility with SDK 23+. Checking along PATH for adb.
[36minfo[39m: [debug] executing cmd: which adb
[36minfo[39m: [debug] Cleaning up android objects
[36minfo[39m: [debug] Cleaning up appium session
[31merror[39m: Failed to start an Appium session, err was: Error: Could not find adb. Please set the ANDROID_HOME environment variable with the Android SDK root directory path.
[36minfo[39m: [debug] Error: Could not find adb. Please set the ANDROID_HOME environment variable with the Android SDK root directory path.
at [object Object]. (/usr/local/lib/node_modules/appium/node_modules/appium-adb/lib/adb.js:126:12)
at ChildProcess.exithandler (child_process.js:758:5)
at ChildProcess.emit (events.js:110:17)
at maybeClose (child_process.js:1015:16)
at Socket. (child_process.js:1183:11)
at Socket.emit (events.js:107:17)
at Pipe.close (net.js:485:12)
[36minfo[39m: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Could not find adb. Please set the ANDROID_HOME environment variable with the Android SDK root directory path.)","origValue":"Could not find adb. Please set the ANDROID_HOME environment variable with the Android SDK root directory path."},"sessionId":null}
[36minfo[39m: [37m<-- POST /wd/hub/session [39m[31m500[39m[90m 874.709 ms - 342[39m [90m[39m

Please help me out for the above error since from one week back i am facing this issue with android platform.

**Comment by sebv** [comment]
@Rakeshvallabhaneni , please go to appium discuss for support.

**Comment by Rakeshvallabhaneni** [comment]
@sebv Thank you for your reply can you please elobrate what i need to fix in my config .
Mac OSX Yosemite
Android_Home is set as expected and i am able run adb commands in my terminal mac machine 
Java 1.8 
adt up to date in eclipse 
SDK latest version.

What still need to config in my system . Please ?

**Comment by sebv** [comment]
Wow Déjà vu #953.

**Comment by marinatouceda** [comment]
I have the same issue . I am not able to start appium. It shows 2 devices when there is only one, and I am getting the error that adb is out of date. Which solution did you find?
Thanks!
Marina

**Comment by Rakeshvallabhaneni** [comment]
Hi @marinatouceda if adb is out of date issue means you need to update android sdk or else if you able to see your connected devices in terminal but coming to appium the issue was android_home not set means its diff issue so can you please elaborate the issue .
