### ISSUE TITLE
My script errors out when it comes to an end or it calls another method

### ISSUE THREAD

**Issue by bgrimes78** [appium/appium#4418]
Appium 1.3.4
Python 3.4.2
Eclipse 4

I can only get my script to work on the Android device if I have no methods in my code.  If I try to break things up by method to be easily reusable then it just breaks with the error below as soon as a method is called.  However, If I just run all the code inline with no methods, then this error appears after the script hits the end.

error: Failed to start an Appium session, err was: Error: Requested a new session but one was in progress

info: --> POST /wd/hub/session {"desiredCapabilities":{"platformVersion":"4.4","deviceName":"lge-nexus_4-04fd40531d5001c1","platformName":"Android","appActivity":".activity.MainActivity","appPackage":"com.hbo.android.app"}}
info: Client User-Agent string: Python-urllib/2.7
info: [debug] Error: Requested a new session but one was in progress
    at Appium.start (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/appium.js:127:15)
    at Object.exports.createSession [as handle] (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/server/controller.js:182:16)
    at next_layer (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:113:13)
    at Route.dispatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:117:5)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/index.js:222:24
    at Function.proto.process_params (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/index.js:288:12)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/index.js:216:19)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/index.js:180:38)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/index.js:180:38)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/index.js:180:38)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Requested a new session but one was in progress)","origValue":"Requested a new session but one was in progress"},"sessionId":"77dd4976-498b-4cf2-8a11-5d521e254016"}
info: <-- POST /wd/hub/session 500 2.829 ms - 250

**Comment by bgrimes78** [comment]
helps to call the method :)
