### ISSUE TITLE
Still have Automation.tracetemplate error with 1.3.4 (OSX 10.10, XCode 6.1)

### ISSUE THREAD

**Issue by fspirit** [appium/appium#4448]
info: Welcome to Appium v1.3.4 (REV c8c79a85fbd6870cd6fc3d66d038a115ebe22efe)
info: Appium REST http interface listener started on 0.0.0.0:4724
info: Console LogLevel: info
info: --> POST /wd/hub/session {"desiredCapabilities":{"newCommandTimeout":999999,"platformName":"iOS","deviceName":"iPhone Simulator","platformVersion":"8.1","app":"/Users/fs/Documents/Code/ForceCuBe-ios-sdk-tests/TestApp/build/Debug-iphonesimulator/TestApp.app"}}
debug: Using local app from desired caps: /Users/fs/Documents/Code/ForceCuBe-ios-sdk-tests/TestApp/build/Debug-iphonesimulator/TestApp.app
debug: Creating new appium session f6ad2a8f-dd48-47ef-8ca8-e9dc263f6642
debug: Removing any remaining instruments sockets
debug: Cleaned up instruments socket /tmp/instruments_sock
debug: Setting Xcode folder
debug: Setting Xcode version
debug: Setting iOS SDK Version
debug: iOS SDK Version set to 8.1
debug: Detecting automation tracetemplate
error: Could not find Automation.tracetemplate in /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.bundle/Contents/Resources/Automation.tracetemplate
debug: Cleaning up appium session
error: Failed to start an Appium session, err was: Error: Could not find Automation.tracetemplate in /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.bundle/Contents/Resources/Automation.tracetemplate
debug: Error: Could not find Automation.tracetemplate in /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.bundle/Contents/Resources/Automation.tracetemplate
    at null.<anonymous> (/usr/local/lib/node_modules/appium/lib/devices/ios/ios.js:726:14)
    at /usr/local/lib/node_modules/appium/lib/helpers.js:490:9
    at ChildProcess.exithandler (child_process.js:646:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)

**Comment by sebv** [comment]
Does it work when you run instruments auomation on it's own?

**Comment by sebv** [comment]
Closing, no activity, reopen if needed.
