### ISSUE TITLE
cannot install app on iPhone

### ISSUE THREAD

**Issue by michaazran** [appium/appium#4477]
i am trying to open the inspector on the CoreData app example, it worked several days ago and now i am getting the following error on the log

please advice

error: Failed to start an Appium session, err was: Error: Unable to install [/Users/amirzur/Downloads/UITableView-Examples-master/CoreData/build/Release-iphonesimulator/CoreData.app] to device with id [e9983227ac46e133c3429044f05293726bd187cf]. Error [Error: Command failed: /bin/sh: /Applications/Appium: No such file or directory
]

info: [debug] Error: Unable to install [/Users/amirzur/Downloads/UITableView-Examples-master/CoreData/build/Release-iphonesimulator/CoreData.app] to device with id [e9983227ac46e133c3429044f05293726bd187cf]. Error [Error: Command failed: /bin/sh: /Applications/Appium: No such file or directory
]
    at /Applications/Appium 1.3.app/Contents/Resources/node_modules/appium/lib/devices/common.js:147:10
    at ChildProcess.exithandler (child_process.js:652:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Socket.<anonymous> (child_process.js:969:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)

info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Unable to install [/Users/amirzur/Downloads/UITableView-Examples-master/CoreData/build/Release-iphonesimulator/CoreData.app] to device with id [e9983227ac46e133c3429044f05293726bd187cf]. Error [Error: Command failed: /bin/sh: /Applications/Appium: No such file or directory\n])","origValue":"Unable to install [/Users/amirzur/Downloads/UITableView-Examples-master/CoreData/build/Release-iphonesimulator/CoreData.app] to device with id [e9983227ac46e133c3429044f05293726bd187cf]. Error [Error: Command failed: /bin/sh: /Applications/Appium: No such file or directory\n]"},"sessionId":null}
info: <-- POST /wd/hub/session 500 2948.519 ms - 674

**Comment by jlipps** [comment]
@michaazran if you're still having this problem, can you please link to a gist of the full log?

**Comment by moizjv** [comment]
Closing due to inactivity
