### ISSUE TITLE
Time out after responding back to request.

### ISSUE THREAD

**Issue by eggman87** [appium/appium#4484]
When running a test on our build server, for some reason a command timeout always occurs while entering in a long string (76 character), which results in the killing instruments/sim and the current session hanging. (test hangs until an eventual SessonNotFoundException is thrown). 

**Machine Details:**
Xcode 6
Fairly new Mac Mini 
Appium 1.3.4
Java Client 2.1.0
Running as jenkins slave (admin account)
Appium is run from the command line as a new process, other tests operate normally - just this test hangs. 

**Main command it is failing on (from the logs below):**

```
au.getElement('12').setValueByType('8bwxkn3glrk51i33a9xoc1rif0w4pdbfc8dk63kcntunw0mcb4kmau451unksnzsiuel5becmw1x')[39m
```

**We can see it fails on the n character in this case (but the character it fails at is different each time):**

```
target.frontMostApp().keyboard().typeString("n")[39m
[36minfo[39m: [debug] Didn't get a new command in 60 secs, shutting down...
[36minfo[39m: Shutting down appium session
```

**Any ideas as to what maybe going wrong?** 

Is the word perhaps so long that the command actually times out before it finishes? Wouldn't that result in appium throwing a exception in our test? (right now it just hangs).

```
[36minfo[39m: [debug] Socket data received (39 bytes)
[36minfo[39m: [debug] Socket data being routed.
[36minfo[39m: [debug] Got result from instruments: {"status":0,"value":{"ELEMENT":"12"}}
[36minfo[39m: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":"12"},"sessionId":"3b05e27a-f4ce-410d-af56-f8c34db1e311"}
[36minfo[39m: [37m<-- POST /wd/hub/session/3b05e27a-f4ce-410d-af56-f8c34db1e311/element [39m[32m200[39m[90m 1038.812 ms - 88[39m [90m{"status":0,"value":{"ELEMENT":"12"},"sessionId":"3b05e27a-f4ce-410d-af56-f8c34db1e311"}[39m
[36minfo[39m: [37m-->[39m [37mPOST[39m [37m/wd/hub/session/3b05e27a-f4ce-410d-af56-f8c34db1e311/element/12/value[39m [90m{"id":"12","value":["8bwxkn3glrk51i33a9xoc1rif0w4pdbfc8dk63kcntunw0mcb4kmau451unksnzsiuel5becmw1x"]}[39m
[36minfo[39m: [debug] Pushing command to appium work queue: "au.getElement('12').setValueByType('8bwxkn3glrk51i33a9xoc1rif0w4pdbfc8dk63kcntunw0mcb4kmau451unksnzsiuel5becmw1x')"
[36minfo[39m: [debug] Sending command to instruments: au.getElement('12').setValueByType('8bwxkn3glrk51i33a9xoc1rif0w4pdbfc8dk63kcntunw0mcb4kmau451unksnzsiuel5becmw1x')
[36minfo[39m: [debug] [32m[INST] 2015-02-03 23:18:14 +0000 Debug: Got new command 32 from instruments: au.getElement('12').setValueByType('8bwxkn3glrk51i33a9xoc1rif0w4pdbfc8dk63kcntunw0mcb4kmau451unksnzsiuel5becmw1x')[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-03 23:18:14 +0000 Debug: evaluating au.getElement('12').setValueByType('8bwxkn3glrk51i33a9xoc1rif0w4pdbfc8dk63kcntunw0mcb4kmau451unksnzsiuel5becmw1x')[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-03 23:18:14 +0000 Debug: target.frontMostApp().keyboard().typeString("8")[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-03 23:18:15 +0000 Debug: target.frontMostApp().keyboard().typeString("b")[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-03 23:18:17 +0000 Debug: target.frontMostApp().keyboard().typeString("w")[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-03 23:18:18 +0000 Debug: target.frontMostApp().keyboard().typeString("x")[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-03 23:18:19 +0000 Debug: target.frontMostApp().keyboard().typeString("k")[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-03 23:18:20 +0000 Debug: target.frontMostApp().keyboard().typeString("n")[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-03 23:18:21 +0000 Debug: target.frontMostApp().keyboard().typeString("3")[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-03 23:18:23 +0000 Debug: target.frontMostApp().keyboard().typeString("g")[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-03 23:18:24 +0000 Debug: target.frontMostApp().keyboard().typeString("l")[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-03 23:18:25 +0000 Debug: target.frontMostApp().keyboard().typeString("r")[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-03 23:18:26 +0000 Debug: target.frontMostApp().keyboard().typeString("k")[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-03 23:18:27 +0000 Debug: target.frontMostApp().keyboard().typeString("5")[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-03 23:18:29 +0000 Debug: target.frontMostApp().keyboard().typeString("1")[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-03 23:18:30 +0000 Debug: target.frontMostApp().keyboard().typeString("i")[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-03 23:18:32 +0000 Debug: target.frontMostApp().keyboard().typeString("3")[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-03 23:18:34 +0000 Debug: target.frontMostApp().keyboard().typeString("3")[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-03 23:18:35 +0000 Debug: target.frontMostApp().keyboard().typeString("a")[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-03 23:18:36 +0000 Debug: target.frontMostApp().keyboard().typeString("9")[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-03 23:18:39 +0000 Debug: target.frontMostApp().keyboard().typeString("x")[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-03 23:18:40 +0000 Debug: target.frontMostApp().keyboard().typeString("o")[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-03 23:18:41 +0000 Debug: target.frontMostApp().keyboard().typeString("c")[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-03 23:18:42 +0000 Debug: target.frontMostApp().keyboard().typeString("1")[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-03 23:18:44 +0000 Debug: target.frontMostApp().keyboard().typeString("r")[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-03 23:18:46 +0000 Debug: target.frontMostApp().keyboard().typeString("i")[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-03 23:18:47 +0000 Debug: target.frontMostApp().keyboard().typeString("f")[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-03 23:18:48 +0000 Debug: target.frontMostApp().keyboard().typeString("0")[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-03 23:18:50 +0000 Debug: target.frontMostApp().keyboard().typeString("w")[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-03 23:18:52 +0000 Debug: target.frontMostApp().keyboard().typeString("4")[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-03 23:18:54 +0000 Debug: target.frontMostApp().keyboard().typeString("p")[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-03 23:18:56 +0000 Debug: target.frontMostApp().keyboard().typeString("d")[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-03 23:18:57 +0000 Debug: target.frontMostApp().keyboard().typeString("b")[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-03 23:18:58 +0000 Debug: target.frontMostApp().keyboard().typeString("f")[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-03 23:18:58 +0000 Debug: target.frontMostApp().keyboard().typeString("c")[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-03 23:18:59 +0000 Debug: target.frontMostApp().keyboard().typeString("8")[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-03 23:19:02 +0000 Debug: target.frontMostApp().keyboard().typeString("d")[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-03 23:19:03 +0000 Debug: target.frontMostApp().keyboard().typeString("k")[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-03 23:19:04 +0000 Debug: target.frontMostApp().keyboard().typeString("6")[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-03 23:19:06 +0000 Debug: target.frontMostApp().keyboard().typeString("3")[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-03 23:19:07 +0000 Debug: target.frontMostApp().keyboard().typeString("k")[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-03 23:19:09 +0000 Debug: target.frontMostApp().keyboard().typeString("c")[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-03 23:19:10 +0000 Debug: target.frontMostApp().keyboard().typeString("n")[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-03 23:19:11 +0000 Debug: target.frontMostApp().keyboard().typeString("t")[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-03 23:19:11 +0000 Debug: target.frontMostApp().keyboard().typeString("u")[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-03 23:19:12 +0000 Debug: target.frontMostApp().keyboard().typeString("n")[39m
[36minfo[39m: [debug] Didn't get a new command in 60 secs, shutting down...
[36minfo[39m: Shutting down appium session
[36minfo[39m: [debug] Stopping ios
[36minfo[39m: [debug] Closing socket server.
[36minfo[39m: [debug] Instruments socket server was closed
[36minfo[39m: [debug] Sending sigterm to instruments
[36minfo[39m: [debug] [32m[INST] 2015-02-03 23:19:13 +0000 Stopped: Script was stopped by the user[39m
[36minfo[39m: [debug] [32m[INST] Instruments Trace Complete (Duration : 114.969551s; Output : /tmp/appium-instruments/instrumentscli0.trace)[39m
[36minfo[39m: [debug] [90m[INSTSERVER] Instruments exited with code 0[39m
[36minfo[39m: [debug] Cleaning up after instruments exit
[36minfo[39m: [debug] Stopping iOS log capture
[36minfo[39m: [debug] Running ios sim reset flow
[36minfo[39m: [debug] Killing the simulator process
[36minfo[39m: [debug] Killall iOS Simulator
[36minfo[39m: [debug] Killing any other simulator daemons
[36minfo[39m: [debug] Cleaning sim data files
[36minfo[39m: [debug] Executing: xcrun simctl erase 65E8E677-A92D-4868-AB7A-845E03173A2F
[36minfo[39m: [debug] Cleaning app data files
[33mwarn[39m: Applications directory /Users/administrator/Library/Developer/CoreSimulator/Devices/65E8E677-A92D-4868-AB7A-845E03173A2F/data/Applications doesn't exist. Have you run this simulator before?
[36minfo[39m: Couldn't find app directories to delete. Probably it's not installed
[36minfo[39m: [debug] Resetting Content and Settings for Simulator
[36minfo[39m: [debug] Executing: xcrun simctl erase 65E8E677-A92D-4868-AB7A-845E03173A2F
[36minfo[39m: [debug] Cleaning up appium session
```

**Eventual stack trace in java client**

```
.account.LoginTests > complexLoginTest STANDARD_OUT
    Hostname is: iosminibuildserver.local
    try 1 out of 270
    Checking server: http://127.0.0.1:4723/wd/hub
    Appium server is free. Running test...
    Debug: 7.1
.account.LoginTests > complexLoginTest STANDARD_ERROR
    complexLoginTest(.account.LoginTests): run 1 failed
    org.junit.internal.runners.model.MultipleFailureException: There were 3 errors:
      org.openqa.selenium.remote.SessionNotFoundException(
    Command duration or timeout: 602.01 seconds
    Build info: version: '2.43.1', revision: '5163bceef1bc36d43f3dc0b83c88998168a363a0', time: '2014-09-10 09:43:55'
    System info: host: 'iosminibuildserver.local', ip: '153.86.243.192', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.5', java.version: '1.7.0_67'
    Session ID: 3b05e27a-f4ce-410d-af56-f8c34db1e311
    Driver info: io.appium.java_client.ios.IOSDriver
    Capabilities [{platform=MAC, app=/Users/administrator/Documents/jenkins/workspace/ui_ios_company-2/company-ios/company.app, javascriptEnabled=true, browserName=iOS, networkConnectionEnabled=false, desired={app=/Users/administrator/Documents/jenkins/workspace/ui_ios_company-2/company-ios/company.app, platformVersion=7.1, fullReset=true, deviceName=iPhone 5s, platformName=iOS, device=iPhone}, locationContextEnabled=false, platformVersion=7.1, databaseEnabled=false, platformName=iOS, deviceName=iPhone 5s, fullReset=true, webStorageEnabled=false, device=iPhone, warnings={}, takesScreenshot=true}])
      org.openqa.selenium.remote.SessionNotFoundException(
    Command duration or timeout: 6 milliseconds
    Build info: version: '2.43.1', revision: '5163bceef1bc36d43f3dc0b83c88998168a363a0', time: '2014-09-10 09:43:55'
    System info: host: 'iosminibuildserver.local', ip: '153.86.243.192', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.5', java.version: '1.7.0_67'
    Session ID: 3b05e27a-f4ce-410d-af56-f8c34db1e311
    Driver info: io.appium.java_client.ios.IOSDriver
    Capabilities [{platform=MAC, app=/Users/administrator/Documents/jenkins/workspace/ui_ios_company-2/company-ios/company.app, javascriptEnabled=true, browserName=iOS, networkConnectionEnabled=false, desired={app=/Users/administrator/Documents/jenkins/workspace/ui_ios_company-2/company-ios/company.app, platformVersion=7.1, fullReset=true, deviceName=iPhone 5s, platformName=iOS, device=iPhone}, locationContextEnabled=false, platformVersion=7.1, databaseEnabled=false, platformName=iOS, deviceName=iPhone 5s, fullReset=true, webStorageEnabled=false, device=iPhone, warnings={}, takesScreenshot=true}])
      org.openqa.selenium.remote.SessionNotFoundException(
    Command duration or timeout: 4 milliseconds
    Build info: version: '2.43.1', revision: '5163bceef1bc36d43f3dc0b83c88998168a363a0', time: '2014-09-10 09:43:55'
    System info: host: 'iosminibuildserver.local', ip: '153.86.243.192', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.5', java.version: '1.7.0_67'
    Session ID: 3b05e27a-f4ce-410d-af56-f8c34db1e311
    Driver info: io.appium.java_client.ios.IOSDriver
    Capabilities [{platform=MAC, app=/Users/administrator/Documents/jenkins/workspace/ui_ios_company-2/company-ios/company.app, javascriptEnabled=true, browserName=iOS, networkConnectionEnabled=false, desired={app=/Users/administrator/Documents/jenkins/workspace/ui_ios_company-2/company-ios/company.app, platformVersion=7.1, fullReset=true, deviceName=iPhone 5s, platformName=iOS, device=iPhone}, locationContextEnabled=false, platformVersion=7.1, databaseEnabled=false, platformName=iOS, deviceName=iPhone 5s, fullReset=true, webStorageEnabled=false, device=iPhone, warnings={}, takesScreenshot=true}])
        at org.junit.runners.model.MultipleFailureException.assertEmpty(MultipleFailureException.java:62)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:39)
        at com.ncr.automation.tools.RetryTestRule$1.evaluate(RetryTestRule.java:50)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:48)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
        at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:355)
        at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by eggman87** [comment]
Some more notes after further investigation:

1. This only happens when running appium from the command line with no GUI. When the GUI is used, the command does not end up timing out (from the same machine). 

Noticed there are different non default arguments being passed for the GUI (including command timeout), going to try starting from command line with these and see how it goes. 

2. In the previous post I said the letter that it fails on is always different, however that does not mean it is not failing at the same spot/time....the string we are sending from test is a random string.

**Comment by eggman87** [comment]
Issue is resolved when using a larger command timeout when starting appium. 

Not sure if the session hanging for an eventual SessionNotFoundException is desired behavior though, so will not close for now until I hear back. Also - is there a way to specify a larger timeout for specific send keys command?

**Comment by moizjv** [comment]
@eggman87 thanks for reporting. Ideally we should be timing out after we have responded back to request. I will put this in as bug in 1.5 milestone.

**Comment by Jonahss** [comment]
+1
