### ISSUE TITLE
Unable to reset Selendroid on OS X Yosemite

### ISSUE THREAD

**Issue by rcolby** [appium/appium#4490]
I tried running ./reset.sh and I get an error when trying to reset Selendroid. I don't really need it at the moment, so I just add the --ios and --android flags and everything works fine. Using the --force flag doesn't help.

This is what I'm seeing:
```
RESETTING SELENDROID
* Clearing out any old modified server apks
* Cloning/updating selendroid
* Building selendroid server and supporting libraries
Running "buildSelendroidServer" task
Building selendroid server
Getting Selendroid version
Selendroid version is 0.13.0
Unable to build selendroid server. Stdout was: 
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] selendroid
[INFO] android-driver-app
[INFO] selendroid-server-common
[INFO] selendroid-server
[INFO] selendroid-grid-plugin
[INFO] selendroid-common
[INFO] selendroid-standalone
[INFO] selendroid-client
[INFO] selendroid-test-app
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building selendroid 0.13.0
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] selendroid ......................................... SKIPPED
[INFO] android-driver-app ................................. SKIPPED
[INFO] selendroid-server-common ........................... SKIPPED
[INFO] selendroid-server .................................. SKIPPED
[INFO] selendroid-grid-plugin ............................. SKIPPED
[INFO] selendroid-common .................................. SKIPPED
[INFO] selendroid-standalone .............................. SKIPPED
[INFO] selendroid-client .................................. SKIPPED
[INFO] selendroid-test-app ................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.809 s
[INFO] Finished at: 2015-02-04T10:01:30-08:00
[INFO] Final Memory: 12M/245M
[INFO] ------------------------------------------------------------------------
---------------------------------------------------
constituent[0]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/aether-api-1.0.0.v20140518.jar
constituent[1]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/aether-connector-basic-1.0.0.v20140518.jar
constituent[2]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/aether-impl-1.0.0.v20140518.jar
constituent[3]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/aether-spi-1.0.0.v20140518.jar
constituent[4]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/aether-transport-wagon-1.0.0.v20140518.jar
constituent[5]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/aether-util-1.0.0.v20140518.jar
constituent[6]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/aopalliance-1.0.jar
constituent[7]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/cdi-api-1.0.jar
constituent[8]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/commons-cli-1.2.jar
constituent[9]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/commons-io-2.2.jar
constituent[10]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/commons-lang-2.6.jar
constituent[11]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/guava-18.0.jar
constituent[12]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/javax.inject-1.jar
constituent[13]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/jsoup-1.7.2.jar
constituent[14]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/jsr250-api-1.0.jar
constituent[15]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/maven-aether-provider-3.2.5.jar
constituent[16]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/maven-artifact-3.2.5.jar
constituent[17]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/maven-compat-3.2.5.jar
constituent[18]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/maven-core-3.2.5.jar
constituent[19]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/maven-embedder-3.2.5.jar
constituent[20]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/maven-model-3.2.5.jar
constituent[21]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/maven-model-builder-3.2.5.jar
constituent[22]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/maven-plugin-api-3.2.5.jar
constituent[23]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/maven-repository-metadata-3.2.5.jar
constituent[24]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/maven-settings-3.2.5.jar
constituent[25]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/maven-settings-builder-3.2.5.jar
constituent[26]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/org.eclipse.sisu.inject-0.3.0.M1.jar
constituent[27]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/org.eclipse.sisu.plexus-0.3.0.M1.jar
constituent[28]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/plexus-cipher-1.7.jar
constituent[29]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/plexus-component-annotations-1.5.5.jar
constituent[30]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/plexus-interpolation-1.21.jar
constituent[31]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/plexus-sec-dispatcher-1.3.jar
constituent[32]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/plexus-utils-3.0.20.jar
constituent[33]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/sisu-guice-3.2.3-no_aop.jar
constituent[34]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/slf4j-api-1.7.5.jar
constituent[35]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/slf4j-simple-1.7.5.jar
constituent[36]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/wagon-file-2.8.jar
constituent[37]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/wagon-http-2.8-shaded.jar
constituent[38]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/wagon-http-shared-2.8.jar
constituent[39]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/wagon-provider-api-2.8.jar
constituent[40]: file:/usr/local/Cellar/maven/3.2.5/libexec/conf/logging/
---------------------------------------------------

Exception in thread "pool-1-thread-1" java.lang.NoClassDefFoundError: org/eclipse/aether/spi/connector/Transfer$State
	at org.eclipse.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:608)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.eclipse.aether.spi.connector.Transfer$State
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 5 more
Exception in thread "main" java.lang.NoClassDefFoundError: org/eclipse/aether/spi/connector/Transfer$State
	at org.eclipse.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:608)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.eclipse.aether.spi.connector.Transfer$State
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 5 more

Warning: Command failed: Exception in thread "pool-1-thread-1" java.lang.NoClassDefFoundError: org/eclipse/aether/spi/connector/Transfer$State
	at org.eclipse.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:608)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.eclipse.aether.spi.connector.Transfer$State
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 5 more
Exception in thread "main" java.lang.NoClassDefFoundError: org/eclipse/aether/spi/connector/Transfer$State
	at org.eclipse.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:608)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.eclipse.aether.spi.connector.Transfer$State
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 5 more
 Use --force to continue.

Aborted due to warnings.
```

Here's my maven info:
```
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T09:29:23-08:00)
Maven home: /usr/local/Cellar/maven/3.2.5/libexec
Java version: 1.7.0_75, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.7.0_75.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.2", arch: "x86_64", family: "mac"
```
and Java...
```
java version "1.7.0_75"
Java(TM) SE Runtime Environment (build 1.7.0_75-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.75-b04, mixed mode)
```

**Comment by irivas** [comment]
Hi there, I have the same problem. This is my info:

```
RESETTING SELENDROID
* Clearing out any old modified server apks
* Cloning/updating selendroid
* Building selendroid server and supporting libraries
Running "buildSelendroidServer" task
Building selendroid server
Getting Selendroid version
Selendroid version is 0.13.0
Unable to build selendroid server. Stdout was:
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] selendroid
[INFO] android-driver-app
[INFO] selendroid-server-common
[INFO] selendroid-server
[INFO] selendroid-grid-plugin
[INFO] selendroid-common
[INFO] selendroid-standalone
[INFO] selendroid-client
[INFO] selendroid-test-app
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building selendroid 0.13.0
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] selendroid ......................................... SKIPPED
[INFO] android-driver-app ................................. SKIPPED
[INFO] selendroid-server-common ........................... SKIPPED
[INFO] selendroid-server .................................. SKIPPED
[INFO] selendroid-grid-plugin ............................. SKIPPED
[INFO] selendroid-common .................................. SKIPPED
[INFO] selendroid-standalone .............................. SKIPPED
[INFO] selendroid-client .................................. SKIPPED
[INFO] selendroid-test-app ................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.775 s
[INFO] Finished at: 2015-02-05T12:40:46+01:00
[INFO] Final Memory: 14M/220M
[INFO] ------------------------------------------------------------------------
---------------------------------------------------
constituent[0]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/aether-api-1.0.0.v20140518.jar
constituent[1]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/aether-connector-basic-1.0.0.v20140518.jar
constituent[2]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/aether-impl-1.0.0.v20140518.jar
constituent[3]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/aether-spi-1.0.0.v20140518.jar
constituent[4]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/aether-transport-wagon-1.0.0.v20140518.jar
constituent[5]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/aether-util-1.0.0.v20140518.jar
constituent[6]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/aopalliance-1.0.jar
constituent[7]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/cdi-api-1.0.jar
constituent[8]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/commons-cli-1.2.jar
constituent[9]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/commons-io-2.2.jar
constituent[10]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/commons-lang-2.6.jar
constituent[11]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/guava-18.0.jar
constituent[12]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/javax.inject-1.jar
constituent[13]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/jsoup-1.7.2.jar
constituent[14]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/jsr250-api-1.0.jar
constituent[15]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/maven-aether-provider-3.2.5.jar
constituent[16]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/maven-artifact-3.2.5.jar
constituent[17]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/maven-compat-3.2.5.jar
constituent[18]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/maven-core-3.2.5.jar
constituent[19]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/maven-embedder-3.2.5.jar
constituent[20]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/maven-model-3.2.5.jar
constituent[21]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/maven-model-builder-3.2.5.jar
constituent[22]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/maven-plugin-api-3.2.5.jar
constituent[23]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/maven-repository-metadata-3.2.5.jar
constituent[24]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/maven-settings-3.2.5.jar
constituent[25]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/maven-settings-builder-3.2.5.jar
constituent[26]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/org.eclipse.sisu.inject-0.3.0.M1.jar
constituent[27]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/org.eclipse.sisu.plexus-0.3.0.M1.jar
constituent[28]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/plexus-cipher-1.7.jar
constituent[29]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/plexus-component-annotations-1.5.5.jar
constituent[30]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/plexus-interpolation-1.21.jar
constituent[31]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/plexus-sec-dispatcher-1.3.jar
constituent[32]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/plexus-utils-3.0.20.jar
constituent[33]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/sisu-guice-3.2.3-no_aop.jar
constituent[34]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/slf4j-api-1.7.5.jar
constituent[35]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/slf4j-simple-1.7.5.jar
constituent[36]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/wagon-file-2.8.jar
constituent[37]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/wagon-http-2.8-shaded.jar
constituent[38]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/wagon-http-shared-2.8.jar
constituent[39]: file:/usr/local/Cellar/maven/3.2.5/libexec/lib/wagon-provider-api-2.8.jar
constituent[40]: file:/usr/local/Cellar/maven/3.2.5/libexec/conf/logging/
---------------------------------------------------

Exception in thread "pool-1-thread-1" java.lang.NoClassDefFoundError: org/eclipse/aether/spi/connector/Transfer$State
	at org.eclipse.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:608)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.eclipse.aether.spi.connector.Transfer$State
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 5 more
Exception in thread "main" java.lang.NoClassDefFoundError: org/eclipse/aether/spi/connector/Transfer$State
	at org.eclipse.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:608)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.eclipse.aether.spi.connector.Transfer$State
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 5 more

Warning: Command failed: Exception in thread "pool-1-thread-1" java.lang.NoClassDefFoundError: org/eclipse/aether/spi/connector/Transfer$State
	at org.eclipse.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:608)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.eclipse.aether.spi.connector.Transfer$State
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 5 more
Exception in thread "main" java.lang.NoClassDefFoundError: org/eclipse/aether/spi/connector/Transfer$State
	at org.eclipse.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:608)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.eclipse.aether.spi.connector.Transfer$State
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 5 more
 Use --force to continue.

Aborted due to warnings.
---- FAILURE: reset.sh exited with status 1 ----
```

Maven
```
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T18:29:23+01:00)
Maven home: /usr/local/Cellar/maven/3.2.5/libexec
Java version: 1.8.0_31, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre
Default locale: es_ES, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.2", arch: "x86_64", family: "mac"
```

Java
```
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)
```

**Comment by vrunoa** [comment]
Yeah, I have the same the problem here on Yosemite. 
```
Warning: Command failed: Exception in thread "pool-1-thread-1" java.lang.NoClassDefFoundError: org/eclipse/aether/spi/connector/Transfer$State
	at org.eclipse.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:608)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.eclipse.aether.spi.connector.Transfer$State
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 5 more
Exception in thread "main" java.lang.NoClassDefFoundError: org/eclipse/aether/spi/connector/Transfer$State
	at org.eclipse.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:608)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.eclipse.aether.spi.connector.Transfer$State
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 5 more
 Use --force to continue.
```

**Comment by imurchie** [comment]
This is a problem with Maven 3.2.5 and dependencies therein. I would open an issue in the Selendroid project, and use Maven 3.1.1.

**Comment by rcolby** [comment]
Switching to the older version of Maven fixed the issue. Thanks.

**Comment by vrunoa** [comment]
It works, thanks @imurchie :+1: 

====
Extra tip: change maven version if installed with brew
```bash
brew install homebrew/versions/maven31
sudo ln -s /usr/local/Cellar/maven31/3.1.1 /usr/local/Cellar/maven/
brew switch maven 3.1.1
```

**Comment by srampv** [comment]
these commands worked for me 

brew install homebrew/versions/maven31
sudo ln -s /usr/local/Cellar/maven31/3.1.1 /usr/local/Cellar/maven/
brew switch maven 3.1.1
