### ISSUE TITLE
TouchAction do not work in iPad Safari 

### ISSUE THREAD

**Issue by baubakg** [appium/appium#4529]
Hi,

Since I am not getting anywhere on this on the forums, I had to do some tests, and it seems that although TouchActions work perfectly well with the WebViewApp they do not work at all with Safari.

My Environment:
- Appium 1.3.4 (reporduced this in 1.3.x)
- java-client 2.1.0
- XCode 6.1
- IOS 8.1

This worked at least in Appium 1.2.4.

Here is the code for my tests:

```
	@Test
	public void testDragAndDrop_Safari() throws InterruptedException,
			MalformedURLException, ElementNotFoundException {

		DesiredCapabilities l_capabilities = new DesiredCapabilities();
		l_capabilities
				.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
		l_capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION,
				"8.1");
		l_capabilities.setCapability(MobileCapabilityType.BROWSER_NAME,
				"Safari");

		l_capabilities.setCapability(MobileCapabilityType.DEVICE_NAME,
				"iPad Retina");
		
		   
		URL url = new URL(CNXN_Tools.appiumAddress);
		AppiumDriver driver = new IOSDriver(url,
				l_capabilities);
		
		driver.get("http://lukasolson.github.io/multi-touch-draw/");


		TouchAction action = new TouchAction((MobileDriver) driver);
		for (int x = 100; x < 1000; x += 10) {
			action.press(x, x).perform();
		}

		System.out.println("Finished Drag Drop!");
		
		driver.quit();
	}
```

This code causes the following error:

```
FAILED: testDragAndDrop_Safari
org.openqa.selenium.WebDriverException: Not yet implemented. Please help us: http://appium.io/get-involved.html (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 6 milliseconds
Build info: version: '2.43.1', revision: '5163bce', time: '2014-09-10 16:27:33'
System info: host: 'gandomi-osx', ip: '10.131.150.133', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.5', java.version: '1.8.0_31'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{networkConnectionEnabled=false, safari=true, warnings={}, databaseEnabled=false, deviceName=iPad Retina, platform=MAC, desired={platformVersion=8.1, browserName=Safari, platformName=iOS, deviceName=iPad Retina}, platformVersion=8.1, webStorageEnabled=false, locationContextEnabled=false, browserName=Safari, takesScreenshot=true, javascriptEnabled=true, platformName=iOS}]
Session ID: 70fe3615-76ea-4456-85a6-8bf617e01d38
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:180)
	at io.appium.java_client.AppiumDriver.performTouchAction(AppiumDriver.java:304)
	at io.appium.java_client.TouchAction.perform(TouchAction.java:253)
	at com.adobe.campaign.uitests.tests.TestWebApp.testDragAndDrop_Safari(TestWebApp.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
```

Here is the log from Appium:
```
info: [debug] [REMOTE] Waiting for frame navigated...

info: [IOS_SYSLOG_ROW ] Feb 11 17:05:16 gandomi-osx lsuseractivityd[36313]: [SFActivityAdvertiser] ERROR: no XPC proxy, queuing advertisement <799f5509 acacb001 a6>

info: [debug] [REMOTE] Checking document readyState
info: [debug] [REMOTE] Sending javascript command
info: [debug] [REMOTE] Sending _rpc_forwardSocketData: message to remote debugger
info: [debug] [REMOTE] Receiving data from remote debugger
info: [debug] [REMOTE] Receiving data from remote debugger
info: [debug] [REMOTE] got applicationSentData response
info: [debug] [REMOTE] readyState was complete
info: [debug] [REMOTE] Page is ready, calling onload cbs

info: [IOS_SYSLOG_ROW ] Feb 11 17:05:16 gandomi-osx syncdefaultsd[36305]: (Note ) Found new store com.apple.CoreSuggestions

info: [IOS_SYSLOG_ROW ] Feb 11 17:05:16 gandomi-osx syncdefaultsd[36305]: (Note ) Found new store com.apple.coretelephony
info: [IOS_SYSLOG_ROW ] Feb 11 17:05:16 gandomi-osx syncdefaultsd[36305]: (Note ) Found new store com.apple.cmfsyncagent
info: [IOS_SYSLOG_ROW ] Feb 11 17:05:16 gandomi-osx syncdefaultsd[36305]: (Note ) Found new store com.apple.Maps
info: [IOS_SYSLOG_ROW ] Feb 11 17:05:16 gandomi-osx syncdefaultsd[36305]: (Note ) Found new store com.apple.VoiceOverTouch
info: [IOS_SYSLOG_ROW ] Feb 11 17:05:16 gandomi-osx syncdefaultsd[36305]: (Note ) Found new store com.apple.accessibility.heard
info: [IOS_SYSLOG_ROW ] Feb 11 17:05:16 gandomi-osx syncdefaultsd[36305]: (Note ) Found new store com.apple.UIKit.fileprovider.default

info: [IOS_SYSLOG_ROW ] Feb 11 17:05:16 gandomi-osx syncdefaultsd[36305]: (Note ) Found new store com.apple.TextInput.kbd
info: [IOS_SYSLOG_ROW ] Feb 11 17:05:16 gandomi-osx syncdefaultsd[36305]: (Note ) Found new store com.apple.Maps(com.apple.Maps.recents)
info: [IOS_SYSLOG_ROW ] Feb 11 17:05:16 gandomi-osx syncdefaultsd[36305]: (Note ) Found new store com.apple.Maps(com.apple.MapsSupport.history)
info: [IOS_SYSLOG_ROW ] Feb 11 17:05:16 gandomi-osx syncdefaultsd[36305]: (Note ) Found new store com.apple.Maps(com.apple.MapsSupport.bookmarks)
info: [IOS_SYSLOG_ROW ] Feb 11 17:05:16 gandomi-osx syncdefaultsd[36305]: (Note ) Found new store com.apple.mobilesafari(com.apple.Safari.WebFeedSubscriptions)
info: [IOS_SYSLOG_ROW ] Feb 11 17:05:16 gandomi-osx syncdefaultsd[36305]: (Note ) Found new store com.apple.cloudrecents.CloudRecentsAgent(com.apple.cloudrecents.phone)

info: [debug] [REMOTE] Receiving data from remote debugger

info: [debug] [REMOTE] {"__selector":"_rpc_applicationSentListing:","__argument":{"WIRApplicationIdentifierKey":"PID:36288","WIRListingKey":{}}}
info: [debug] [REMOTE] New page listing did not match the app id we are currently using, ignoring

info: [debug] [REMOTE] Frame navigated, calling cbs

info: [debug] [REMOTE] Waiting for dom...
info: [debug] [REMOTE] Page loaded, verifying whether ready through readyState

info: [debug] [REMOTE] Checking document readyState

info: [debug] [REMOTE] Sending javascript command
info: [debug] [REMOTE] Sending _rpc_forwardSocketData: message to remote debugger

info: [debug] [REMOTE] Receiving data from remote debugger
info: [debug] [REMOTE] got applicationSentData response
info: [debug] [REMOTE] readyState was complete
info: [debug] [REMOTE] Page is ready, calling onload cbs
info: [debug] Responding to client with success: {"status":0,"value":"","sessionId":"f578734f-2179-45e9-88a6-1f5aa8452ef9"}
info: <-- POST /wd/hub/session/f578734f-2179-45e9-88a6-1f5aa8452ef9/url 200 2010.494 ms - 74 {"status":0,"value":"","sessionId":"f578734f-2179-45e9-88a6-1f5aa8452ef9"}
info: --> POST /wd/hub/session/f578734f-2179-45e9-88a6-1f5aa8452ef9/touch/perform {"actions":[{"options":{"x":100,"y":100},"action":"press"}]}
info: [debug] Responding to client that a method is not implemented
info: <-- POST /wd/hub/session/f578734f-2179-45e9-88a6-1f5aa8452ef9/touch/perform 501 1.155 ms - 158 

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.4","revision":"c8c79a85fbd6870cd6fc3d66d038a115ebe22efe"},"isShuttingDown":false},"sessionId":"f578734f-2179-45e9-88a6-1f5aa8452ef9"}
info: <-- GET /wd/hub/status 200 0.873 ms - 178 {"status":0,"value":{"build":{"version":"1.3.4","revision":"c8c79a85fbd6870cd6fc3d66d038a115ebe22efe"},"isShuttingDown":false},"sessionId":"f578734f-2179-45e9-88a6-1f5aa8452ef9"}
```
The same example works just fine in the WebViewApp, but not when we use Safari. Any insight in this matter is most welcome.

**Comment by sebv** [comment]
Try to switch to native context before performing the Touch Action.

**Comment by baubakg** [comment]
Thanks for the comment. I didn't know that was possible. Could you suggest how I should do this?

**Comment by baubakg** [comment]
Wow,

That does work! Thanks. 
Before lauching the touchActions I performed 

    driver.context("NATIVE_APP");

This does work as a workaround for me. But I suppose this is not a '"Works as Planned" :) ?

Now as to my observations:
- Drag&Drop using elements causes appium to crash. (This was still an issue in 1.2.2 for Web Automation)
- Drag&Drop only works when you use the element locations....

**Comment by sebv** [comment]
I think it works as planned, but maybe the Safari doc not clear enough. 
@jlipps is it correct or should we infer tap action directly to the NATIVE context?

For drag and drop related issue, could you open another issue with a concrete example (opensource app better since we can reproduce).

**Comment by baubakg** [comment]
Great. I will create the issue. 

In regards to the Safari doc. Which one are we talking about? 
This one?
http://appium.io/slate/en/v1.3.4/?java#automating-mobile-gestures
