### ISSUE TITLE
Appium::iOS_Real device :- Unale to launch the safari browser in real device.

### ISSUE THREAD

**Issue by ramyasree1** [appium/appium#4535]
Hi All,

Unable to launch the safari browser in real device .Please find below the details.

  DesiredCapabilities cap = new DesiredCapabilities();
   cap.setCapability("deviceName", "iPhone 5");
    cap.setCapability("browserName", "Safari");
    cap.setCapability("platformVersion", "8.1");
    cap.setCapability("platformName", "iOS");
    cap.setCapability("udid", UDID);

console error

FAILED CONFIGURATION: @BeforeMethod setUp
org.openqa.selenium.SessionNotCreatedException: A new session could not be created. (Original error: Unable to install [/var/folders/dm/vsjfqr2d4zn5r90z2jp6l1100000gn/T/115112-4513-1glny3r/submodules/SafariLauncher/build/Release-iphoneos/SafariLauncher.app] to device with id [a44a6e73e811b70878e2c0b7852ff7e90e30afec]. Error [Error: Command failed: /bin/sh -c /Applications/Appium.app/Contents/Resources/node_modules/appium/build/fruitstrap/fruitstrap install --id a44a6e73e811b70878e2c0b7852ff7e90e30afec --bundle "/var/folders/dm/vsjfqr2d4zn5r90z2jp6l1100000gn/T/115112-4513-1glny3r/submodules/SafariLauncher/build/Release-iphoneos/SafariLauncher.app"
]) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 6.34 seconds
Build info: version: '2.33.0', revision: '4e90c97', time: '2013-05-22 15:32:38'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.2', java.version: '1.8.0_31'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:191)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:145)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:554)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:216)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:111)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:129)
	at test.SampleTest.setUp(SampleTest.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:653)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)

Appium version:1.3.5
Xcode 6.1.1
OS X 10.10.2

**Comment by slk9** [comment]
You need to sign SafariLauncher first with your iOS certificate, like 
cd appium
./reset.sh --ios --real-safari
See http://appium.io/slate/en/master/?ruby#mobile-safari-on-a-real-ios-device

After that you run into mine problem: https://github.com/appium/appium/issues/4532

**Comment by sebv** [comment]
Was it solved? You'll also need to run this script: 

https://github.com/appium/appium/blob/master/bin/ios-webkit-debug-proxy-launcher.js

**Comment by slk9** [comment]
Yes.It works fine for me with signed SafariLauncher, ios-webkit-debug-proxy and latest appium 1.3.7.

**Comment by rvsqa** [comment]
signed SafariLauncher need to install in real device or do we need to copy paste the .app file into any folder of appium?

**Comment by moofnbg** [comment]
Hi guys, could you give me too a answer to the question from rvsqa: 
"signed SafariLauncher need to install in real device or do we need to copy paste the .app file into any folder of appium?" And in which folder?
