### ISSUE TITLE
Appium crashing with "Bad response from getTreeForXML"

### ISSUE THREAD

**Issue by cbalea** [appium/appium#4560]
Appium crashed with the following error: Bad response from getTreeForXML. Err was undefined and res was undefined

Logs following:

[36minfo[39m: [debug] Pushing command to appium work queue: "au.getElementByIndexPath('/0/0/1')"
[36minfo[39m: [debug] Sending command to instruments: au.getElementByIndexPath('/0/0/1')
[36minfo[39m: [debug] [32m[INST] 2015-02-18 13:01:37 +0000 Debug: Got new command 117 from instruments: au.getElementByIndexPath('/0/0/1')[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-18 13:01:37 +0000 Debug: evaluating au.getElementByIndexPath('/0/0/1')[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-18 13:01:37 +0000 Error: VerboseError: Could not find element with path /0/0/1[39m
[36minfo[39m: [debug] Socket data received (64 bytes)
[36minfo[39m: [debug] Socket data being routed.
[36minfo[39m: [debug] Got result from instruments: {"status":7,"value":"Could not find element with path /0/0/1"}
[36minfo[39m: [debug] Got a warning from uiauto that some index paths could not be resolved, trying again
[36minfo[39m: [debug] Pushing command to appium work queue: "au.mainApp().getTreeForXML()"
[36minfo[39m: [debug] Sending command to instruments: au.mainApp().getTreeForXML()
[36minfo[39m: [debug] [32m[INST] 2015-02-18 13:01:37 +0000 Error: Error during eval: _handleIndexPathError@file:///usr/local/lib/node_modules/appium/E316E6D3-7CCF-43CE-8C11-313A12D64FCC/bootstrap-06a3f3a7491d04aa.js:1870:43
       getElementByIndexPath@file:///usr/local/lib/node_modules/appium/E316E6D3-7CCF-43CE-8C11-313A12D64FCC/bootstrap-06a3f3a7491d04aa.js:1883:41
eval code
eval@[native code]
startProcessing@file:///usr/local/lib/node_modules/appium/E316E6D3-7CCF-43CE-8C11-313A12D64FCC/bootstrap-06a3f3a7491d04aa.js:2660:30
bootstrap@file:///usr/local/lib/node_modules/appium/E316E6D3-7CCF-43CE-8C11-313A12D64FCC/bootstrap-06a3f3a7491d04aa.js:2726:31
global code@file:///usr/local/lib/node_modules/appium/E316E6D3-7CCF-43CE-8C11-313A12D64FCC/bootstrap-06a3f3a7491d04aa.js:2735:10[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-18 13:01:37 +0000 Debug: responding with:
       2015-02-18 13:01:37 +0000 Debug: Running system command #118: /usr/local/Cellar/node/0.10.33/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":7,"value":"Could not find element with path /0/0/1"}...[39m
[36minfo[39m: [debug] [32m[INST] Instruments Trace Complete (Duration : 81.633110s; Output : /tmp/appium-instruments/instrumentscli0.trace)[39m
[36minfo[39m: [debug] [90m[INSTSERVER] Instruments exited with code 0[39m
[36minfo[39m: [debug] Cleaning up after instruments exit
[36minfo[39m: [debug] Instruments exited unexpectedly
[36minfo[39m: [debug] Shutting down command proxy and ignoring any errors
[36minfo[39m: [debug] Closing socket server.
[36minfo[39m: [debug] Instruments socket server was closed
[36minfo[39m: [debug] Stopping iOS log capture
[36minfo[39m: [debug] Running ios sim reset flow
[36minfo[39m: [debug] Killing the simulator process
[36minfo[39m: [debug] Killall iOS Simulator
[36minfo[39m: [debug] Killing any other simulator daemons
[36minfo[39m: [debug] Cleaning sim data files
[36minfo[39m: [debug] Executing: xcrun simctl erase A54A2F10-FB6D-4B59-A207-58A991BF23D1
[36minfo[39m: [debug] Executing: xcrun simctl erase A54A2F10-FB6D-4B59-A207-58A991BF23D1
[36minfo[39m: [debug] Executing: xcrun simctl erase A54A2F10-FB6D-4B59-A207-58A991BF23D1
[36minfo[39m: [debug] Executing: xcrun simctl erase A54A2F10-FB6D-4B59-A207-58A991BF23D1
[36minfo[39m: [debug] Executing: xcrun simctl erase A54A2F10-FB6D-4B59-A207-58A991BF23D1
[31merror[39m: Could not reset simulator. Leaving as is. Error: Command failed:  // stderr: 
[36minfo[39m: [debug] Cleaning app data files
[33mwarn[39m: Applications directory /Users/telegraph/Library/Developer/CoreSimulator/Devices/A54A2F10-FB6D-4B59-A207-58A991BF23D1/data/Applications doesn't exist. Have you run this simulator before?
[36minfo[39m: Couldn't find app directories to delete. Probably it's not installed
[36minfo[39m: [debug] We were in the middle of processing a command when instruments died; responding with a generic error
[36minfo[39m: [debug] Cleaning up appium session
[31merror[39m: Error getting source, can't continue finding element by XPath
[36minfo[39m: [debug] Waited for 17700ms so far
[36minfo[39m: [debug] Pushing command to appium work queue: "au.mainApp().getTreeForXML()"
[31merror[39m: Error getting source, can't continue finding element by XPath
[36minfo[39m: [debug] Waited for 18208ms so far
[36minfo[39m: [debug] Pushing command to appium work queue: "au.mainApp().getTreeForXML()"
[31merror[39m: Error getting source, can't continue finding element by XPath
[36minfo[39m: [debug] Waited for 18719ms so far
[36minfo[39m: [debug] Pushing command to appium work queue: "au.mainApp().getTreeForXML()"
[31merror[39m: Error getting source, can't continue finding element by XPath
[36minfo[39m: [debug] Waited for 19226ms so far
[36minfo[39m: [debug] Pushing command to appium work queue: "au.mainApp().getTreeForXML()"
[31merror[39m: Error getting source, can't continue finding element by XPath
[36minfo[39m: [debug] Waited for 19731ms so far
[36minfo[39m: [debug] Pushing command to appium work queue: "au.mainApp().getTreeForXML()"
[31merror[39m: Error getting source, can't continue finding element by XPath
[36minfo[39m: [debug] Waited for 20242ms so far
[36minfo[39m: [debug] Pushing command to appium work queue: "au.mainApp().getTreeForXML()"
[31merror[39m: Error getting source, can't continue finding element by XPath
[36minfo[39m: [debug] Waited for 20749ms so far
[36minfo[39m: [debug] Pushing command to appium work queue: "au.mainApp().getTreeForXML()"
[31merror[39m: Error getting source, can't continue finding element by XPath
[36minfo[39m: [debug] Waited for 21251ms so far
[36minfo[39m: [debug] Pushing command to appium work queue: "au.mainApp().getTreeForXML()"
[31merror[39m: Error getting source, can't continue finding element by XPath
[36minfo[39m: [debug] Waited for 21761ms so far
[36minfo[39m: [debug] Pushing command to appium work queue: "au.mainApp().getTreeForXML()"
[31merror[39m: Error getting source, can't continue finding element by XPath
[36minfo[39m: [debug] Waited for 22271ms so far
[36minfo[39m: [debug] Pushing command to appium work queue: "au.mainApp().getTreeForXML()"
[31merror[39m: Error getting source, can't continue finding element by XPath
[36minfo[39m: [debug] Waited for 22777ms so far
[36minfo[39m: [debug] Pushing command to appium work queue: "au.mainApp().getTreeForXML()"
[31merror[39m: Error getting source, can't continue finding element by XPath
[36minfo[39m: [debug] Waited for 23280ms so far
[36minfo[39m: [debug] Pushing command to appium work queue: "au.mainApp().getTreeForXML()"
[31merror[39m: Error getting source, can't continue finding element by XPath
[36minfo[39m: [debug] Waited for 23790ms so far
[36minfo[39m: [debug] Pushing command to appium work queue: "au.mainApp().getTreeForXML()"
[31merror[39m: Error getting source, can't continue finding element by XPath
[36minfo[39m: [debug] Waited for 24297ms so far
[36minfo[39m: [debug] Pushing command to appium work queue: "au.mainApp().getTreeForXML()"
[31merror[39m: Error getting source, can't continue finding element by XPath
[36minfo[39m: [debug] Waited for 24799ms so far
[36minfo[39m: [debug] Pushing command to appium work queue: "au.mainApp().getTreeForXML()"
[31merror[39m: Error getting source, can't continue finding element by XPath
[36minfo[39m: [debug] Waited for 25309ms so far
[36minfo[39m: [debug] Pushing command to appium work queue: "au.mainApp().getTreeForXML()"
[31merror[39m: Error getting source, can't continue finding element by XPath
[36minfo[39m: [debug] Waited for 25816ms so far
[36minfo[39m: [debug] Pushing command to appium work queue: "au.mainApp().getTreeForXML()"
[31merror[39m: Error getting source, can't continue finding element by XPath
[36minfo[39m: [debug] Waited for 26318ms so far
[36minfo[39m: [debug] Pushing command to appium work queue: "au.mainApp().getTreeForXML()"
[31merror[39m: Error getting source, can't continue finding element by XPath
[36minfo[39m: [debug] Waited for 26827ms so far
[36minfo[39m: [debug] Pushing command to appium work queue: "au.mainApp().getTreeForXML()"
[31merror[39m: Error getting source, can't continue finding element by XPath
[36minfo[39m: [debug] Waited for 27330ms so far
[36minfo[39m: [debug] Pushing command to appium work queue: "au.mainApp().getTreeForXML()"
[31merror[39m: Error getting source, can't continue finding element by XPath
[36minfo[39m: [debug] Waited for 27836ms so far
[36minfo[39m: [debug] Pushing command to appium work queue: "au.mainApp().getTreeForXML()"
[31merror[39m: Error getting source, can't continue finding element by XPath
[36minfo[39m: [debug] Waited for 28345ms so far
[36minfo[39m: [debug] Pushing command to appium work queue: "au.mainApp().getTreeForXML()"
[31merror[39m: Error getting source, can't continue finding element by XPath
[36minfo[39m: [debug] Waited for 28846ms so far
[36minfo[39m: [debug] Pushing command to appium work queue: "au.mainApp().getTreeForXML()"
[31merror[39m: Error getting source, can't continue finding element by XPath
[36minfo[39m: [debug] Waited for 29350ms so far
[36minfo[39m: [debug] Pushing command to appium work queue: "au.mainApp().getTreeForXML()"
[31merror[39m: Error getting source, can't continue finding element by XPath
[36minfo[39m: [debug] Waited for 29856ms so far
[36minfo[39m: [debug] Pushing command to appium work queue: "au.mainApp().getTreeForXML()"
[31merror[39m: Error getting source, can't continue finding element by XPath
[36minfo[39m: [debug] Condition unmet after 30363ms. Timing out.
[36minfo[39m: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command. (Original error: Bad response from getTreeForXML. Err was undefined and res was undefined)","origValue":"Bad response from getTreeForXML. Err was undefined and res was undefined"},"sessionId":null}

**Comment by cbalea** [comment]
Seems to be related to https://github.com/appium/appium/issues/4228

**Comment by mayureshshirodkar** [comment]
Facing the same issue. 
My App is a hybrid one. and the error happens after a certain number of app reloading.
Seen on iOS 8.0.2

Below is the log:

info: [debug] Responding to client with success: {"status":0,"value":"","sessionId":"ed0f8e7d-14f0-4e05-9e42-7aaa19f5e816"}
info: <-- POST /wd/hub/session/ed0f8e7d-14f0-4e05-9e42-7aaa19f5e816/refresh 200 16.613 ms - 74 {"status":0,"value":"","sessionId":"ed0f8e7d-14f0-4e05-9e42-7aaa19f5e816"}

info: [debug] [INST] 2016-07-14 22:13:03 +0000 Fail: The target application appears to have died

info: [debug] [INST STDERR] 2016-07-14 18:13:04.054 instruments[14689:9326122] Attempting to change event horizon while disengage

info: [debug] [INST] Instruments Trace Complete (Duration : 641.779785s; Output : /tmp/appium-instruments/instrumentscli0.trace)

info: [debug] [INSTSERVER] Instruments exited with code 0

info: [debug] Cleaning up after instruments exit
info: [debug] Instruments exited unexpectedly
info: [debug] Shutting down command proxy and ignoring any errors
info: [debug] Destroying instruments client socket.
info: [debug] Closing socket server.
info: [debug] Instruments socket server was closed
info: [debug] Stopping iOS log capture
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killing any other simulator daemons
info: [debug] Killall Simulator
info: [debug] [REMOTE] Disconnecting from remote debugger
info: [debug] fullReset requested. Will try to uninstall the app.

info: --> POST /wd/hub/session/ed0f8e7d-14f0-4e05-9e42-7aaa19f5e816/element {"using":"xpath","value":"//div/a[1]/span"}

error: Error getting source, can't continue finding element by XPath

info: [debug] Waiting up to 0ms for condition
info: [debug] Pushing command to appium work queue: "au.mainApp().getTreeForXML()"
info: [debug] Condition unmet after 1ms. Timing out.
info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command. (Original error: Bad response from getTreeForXML. Err was undefined and res was undefined)","origValue":"Bad response from getTreeForXML. Err was undefined and res was undefined"},"sessionId":"ed0f8e7d-14f0-4e05-9e42-7aaa19f5e816"}
info: <-- POST /wd/hub/session/ed0f8e7d-14f0-4e05-9e42-7aaa19f5e816/element 500 2.797 ms - 332

info: --> GET /wd/hub/session/ed0f8e7d-14f0-4e05-9e42-7aaa19f5e816/screenshot {}
info: [debug] Pushing command to appium work queue: "au.getScreenOrientation()"
info: [debug] Pushing command to appium work queue: "au.capture('screenshotfeb213d5-231d-44a8-9075-8d996b2d2f10')"
info: [debug] Waiting 10000 ms for screenshot to ge generated.

info: [debug] Removed com.eab.se

info: [debug] Cleaning up appium session

error: Unhandled error: TypeError: cb is not a function
at /usr/local/lib/node_modules/appium/lib/devices/ios/ios-controller.js:1292:24
at Object.async.until (/usr/local/lib/node_modules/appium/node_modules/async/lib/async.js:712:13)
at /usr/local/lib/node_modules/appium/node_modules/async/lib/async.js:708:23
at ReadFileContext.callback (/usr/local/lib/node_modules/appium/lib/devices/ios/ios-controller.js:1286:19)
at FSReqWrap.readFileAfterOpen as oncomplete context: [GET /wd/hub/session/ed0f8e7d-14f0-4e05-9e42-7aaa19f5e816/screenshot {}]

info: --> GET /wd/hub/status {}

**Comment by SrinivasanTarget** [comment]
Closing this because of inactivity. @triager please close
