### ISSUE TITLE
Selendroid mode - Error: apk does not have INTERNET permissions

### ISSUE THREAD

**Issue by ChristopheOGER** [appium/appium#4562]
I've used app "selendroid-test-app-0.12.0.apk" with Appium@1.3.3 + automationName=Selendroid in Linux env. 
As you know, INTERNET permission is enabled in AndroidManifest.xml of this selendroid test apk.
Meanwhile I have the following issue whatever I use avd or real device, appium @1.2.0, @1.3.0. 

info: [debug] Using aapt from /opt/android-sdk-linux/build-tools/21.1.2/aapt
info: [debug] hasInternetPermissionFromManifest: "/opt/android-sdk-linux/build-tools/21.1.2/aapt" dump badging "/vagrant/conf/selendroid-test-app-0.11.0.apk"
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: apk does not have INTERNET permissions. Selendroid needs internet permission to proceed, please check if you have <uses-permission android:name="android.**permission.INTERNET"/> in your AndroidManifest.xml
info: [debug] Error: apk does not have INTERNET permissions. Selendroid needs internet permission to proceed, please check if you have <uses-permission android:name="android.**permission.INTERNET"/> in your AndroidManifest.xml
    at /home/vagrant/.local/lib/node_modules/appium/lib/devices/android/selendroid.js:213:10
    at /home/vagrant/.local/lib/node_modules/appium/node_modules/appium-adb/lib/adb.js:1677:7
    at ChildProcess.exithandler (child_process.js:656:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: apk does not have INTERNET permissions. Selendroid needs internet permission to proceed, please check if you have <uses-permission android:name=\"android.**permission.INTERNET\"/> in your AndroidManifest.xml)","origValue":"apk does not have INTERNET permissions.

Hereafter the appium server command line I run in linux (virtual machine)
appium --nodeconfig /vagrant/conf/appiumnode2.json -p 4733

Hereafter the appium webdriver control from eclipse in Windows:
    @Before
    public void setUp() throws Exception {
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(CapabilityType.BROWSER_NAME, "android");  // MANDATORY
        capabilities.setCapability("platformName", "Android");	
        capabilities.setCapability("deviceName","BX90374W9Z"); // REAL DEVICE	
        capabilities.setCapability("automationName","Selendroid");
        
        capabilities.setCapability("app", "/vagrant/conf/selendroid-test-app-0.12.0.apk");        
        capabilities.setCapability("appPackage", "io.selendroid.testapp");
        capabilities.setCapability("appActivity", ".HomeScreenActivity");
       
        driver = new AndroidDriver(new URL("http://192.168.50.5:4733/wd/hub"), capabilities);
//        driver = new AndroidDriver(new URL("http://192.168.56.1:4444/wd/hub"), capabilities);
    }

The issue should not come from my environment since appium working well remotely for an avd 4.4.
 Thank you for your help.

**Comment by ChristopheOGER** [comment]
If I use appium@1.3.4 instead, I have no more the permission issue described above and then application is installed but another kind of issue is raised later:

[debug] App is installed
 App is already installed, resetting app
 [debug] Running fast reset (stop and clear)
 [debug] executing cmd: /opt/android-sdk-linux/platform-tools/adb -s BX90374W9Z shell "am force-stop io.selendroid.testapp"
 [debug] executing cmd: /opt/android-sdk-linux/platform-tools/adb -s BX90374W9Z shell "pm clear io.selendroid.testapp"
 [37m-->[39m [37mGET[39m [37m/wd/hub/status[39m [90m{}[39m
 [debug] Proxying command to localhost:8080
 [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/status","method":"GET"}
 [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command.","origValue":"Did not successfully proxy server command"},"sessionId":"f67f6ea2-da3c-4f17-bd81-f3454a5de883"}
 [37m<-- GET /wd/hub/status [39m[31m500[39m[90m 13.446 ms - 210[39m [90m[39m
 [debug] Forwarding system:8080 to device:8080
 [debug] executing cmd: /opt/android-sdk-linux/platform-tools/adb -s BX90374W9Z forward tcp:8080 tcp:8080
 [debug] Pushing settings apk to device...
 [debug] executing cmd: /opt/android-sdk-linux/platform-tools/adb -s BX90374W9Z install "/home/vagrant/.local/lib/node_modules/appium/build/settings_apk/settings_apk-debug.apk"
 [debug] Pushing unlock helper app to device...
 [debug] executing cmd: /opt/android-sdk-linux/platform-tools/adb -s BX90374W9Z install "/home/vagrant/.local/lib/node_modules/appium/build/unlock_apk/unlock_apk-debug.apk"
 [37m-->[39m [37mGET[39m [37m/wd/hub/status[39m [90m{}[39m
 [debug] Proxying command to localhost:8080
 [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/status","method":"GET"}
 [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command.","origValue":"Did not successfully proxy server command"},"sessionId":"f67f6ea2-da3c-4f17-bd81-f3454a5de883"}
 [37m<-- GET /wd/hub/status [39m[31m500[39m[90m 18.621 ms - 210[39m [90m[39m
 [debug] executing cmd: /opt/android-sdk-linux/platform-tools/adb -s BX90374W9Z shell "dumpsys window"
 [debug] Screen already unlocked, continuing.
 [debug] executing cmd: /opt/android-sdk-linux/platform-tools/adb -s BX90374W9Z shell "am instrument -e main_activity 'io.selendroid.testapp.HomeScreenActivity' io.selendroid.testapp.selendroid/io.selendroid.ServerInstrumentation"
 [debug] Cleaning up appium session
 [debug] Error: android.util.AndroidException: INSTRUMENTATION_FAILED: io.selendroid.testapp.selendroid/io.selendroid.ServerInstrumentation
    at /home/vagrant/.local/lib/node_modules/appium/node_modules/appium-adb/lib/adb.js:1378:17
    at null.<anonymous> (/home/vagrant/.local/lib/node_modules/appium/node_modules/appium-adb/lib/adb.js:172:9)
    at ChildProcess.exithandler (child_process.js:656:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)
 [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: android.util.AndroidException: INSTRUMENTATION_FAILED: io.selendroid.testapp.selendroid/io.selendroid.ServerInstrumentation\r)","origValue":"android.util.AndroidException: INSTRUMENTATION_FAILED: io.selendroid.testapp.selendroid/io.selendroid.ServerInstrumentation\r"},"sessionId":null}

**Comment by morphysk** [comment]
is there any progress in this issue? I have the same problem after update to v1.3.6

**Comment by sebv** [comment]
Did you follow this: http://appium.io/slate/en/master/?ruby#additional-setup-for-older-versions-of-android?

**Comment by morphysk** [comment]
I am using Nexus5 with android 4.4.4. Our application have proper permission.    
<uses-permission android:name="android.permission.INTERNET" />

**Comment by sebv** [comment]
I've just tried avd api 18/api 19 against master, I cannot repro, work fine for me.

**Comment by sebv** [comment]
By the way I didn't set  appPackage/appActivity, see log here:

https://gist.github.com/sebv/16e3157a256436055074

**Comment by moizjv** [comment]
Closing due to inactivity
