### ISSUE TITLE
Issue with Appium 1.3.4  - Unhandled error: TypeError: Cannot read property 'args' of null

### ISSUE THREAD

**Issue by rahulk06** [appium/appium#4570]
Hi ,

I am sending request on appium server (version 1.3.4) one after the another in a sequential order. As I know appium can run only one session at a time. But when I send multiple request I see the below error in the logs  :-

2015-02-13 05:51:35:339 - [36minfo[39m: [37m<-- DELETE /wd/hub/session [39m[32m200[39m[90m 2783.225 ms - 76[39m [90m{"status":0,"value":null,"sessionId":"4b51d604-7022-4d7e-bd24-bdbf6c8bb43e"}[39m
2015-02-13 05:51:36:079 - [36minfo[39m: [debug] http://XXX.XX.XX.XX/jenkins/job/XXX_Android_PlayStore/lastSuccessfulBuild/artifact/XXXApp/bin/XXXAndroid-release.apk downloaded to C:\Windows\TEMP\115112-232-izuhrb\appium-app.apk
2015-02-13 05:51:36:079 - [36minfo[39m: [debug] Creating new appium session ed4c7d8c-50e2-4204-b9a9-c72d43ed971e
2015-02-13 05:51:36:129 - [31merror[39m: Unhandled error: TypeError: Cannot read property 'args' of null
    at Appium.invoke (C:\Users\vdl\AppData\Roaming\npm\node_modules\appium\lib\appium.js:247:18)
    at null.<anonymous> (C:\Users\vdl\AppData\Roaming\npm\node_modules\appium\lib\appium.js:112:14)
    at null.<anonymous> (C:\Users\vdl\AppData\Roaming\npm\node_modules\appium\lib\devices\android\android-common.js:61:5)
    at null.<anonymous> (C:\Users\vdl\AppData\Roaming\npm\node_modules\appium\lib\devices\device.js:121:9)
    at WriteStream.<anonymous> (C:\Users\vdl\AppData\Roaming\npm\node_modules\appium\lib\helpers.js:22:7)
    at WriteStream.emit (events.js:117:20)
    at fs.js:1610:14
    at Object.oncomplete (fs.js:108:15) context: [POST /wd/hub/session {"desiredCapabilities":{"isWait":"false","Version":"4.2","platform":"android","platformVersion":"4.2","app":"http://XXX.XX.XX.XX/jenkins/job/XXX_Android_PlayStore/lastSuccessfulBuild/artifact/XXXApp/bin/XXXAndroid-release.apk]
2015-02-13 05:51:41:442 - [36minfo[39m: [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m [90m{"desiredCapabilities":{"isWait":"false","Version":"4.2","platform":"android","platformVersion":"4.2","app":"http://XXX.XX.XX.XX/jenkins/job/XXX_Android_PlayStore/lastSuccessfulBuild/artifact/XXXApp/bin/XXXAndroid-release.apk ","deviceId":"057bedea","deviceName":"Google Nexus 7 (MTV)*","tempSessionId":"d394e32b-ce9f-4069-b102-943e995c252c","browserName":"android","deviceCategory":"phone","platformName":"android"}}[39m

~~On close inspection, I found that there is no POST call made for session creation after the DELETE call in above log, but still the log says : " Creating new appium session ed4c7d8c-50e2-4204-b9a9-c72d43ed971e" also since there was no POST call , there is no payload sent for this and therefore it goes into a state where it creates a session but never deletes it, therefore no more session creation call succeeds and all the requests fails saying "Error: Requested a new session but one was in progress".~~

I think this is the POST call (printed some lines below the error mesage "Unhandled error" in above log) for which it was trying to create the session and then it failed :

at Object.oncomplete (fs.js:108:15) context: [POST /wd/hub/session {"desiredCapabilities":{"isWait":"false","Version":"4.2","platform":"android","platformVersion":"4.2","app":"http://XXX.XX.XX.XX/jenkins/job/XXX_Android_PlayStore/lastSuccessfulBuild/artifact/XXXApp/bin/XXXAndroid-release.apk]

It is happening very frequently, for some request it works and then it fails with this error.
Can you please help me with this issue. I have not seen this issue on older versions of appium like 1.1. Please let me know if there is any work around.

Thanks,
Rahul.

**Comment by moizjv** [comment]
@rahulk06 what do you mean by multiple requests?

**Comment by sebv** [comment]
Closing no activity, could be reopened if needed.
