### ISSUE TITLE
stdout maxBuffer exceeded

### ISSUE THREAD

**Issue by bayandin** [appium/appium#4602]
```
info: Welcome to Appium v1.3.5 (REV a124a15677e26b33db16e81c4b3b34d9c6b8cac9)
info: Appium REST http interface listener started on 0.0.0.0:4723
info: Console LogLevel: debug
info: --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"Android","deviceName":"192.168.56.101:5555","platformVersion":"4.4.2","browserName":"Chrome","newCommandTimeout":360}}
info: Client User-Agent string: appium/ruby_lib/6.0.0
info: Set mode: Proxying straight through to Chromedriver
info: [debug] Looks like we want chrome on android
info: [debug] Creating new appium session 43107f65-55e4-452b-9c0a-1d74866d160c
info: [debug] Using fast reset? true
info: [debug] Preparing device for session
info: [debug] Not checking whether app is present since we are assuming it's already on the device
info: Retrieving device
info: [debug] Trying to find a connected android device
info: [debug] Getting connected devices...
info: [debug] executing cmd: adb devices
info: [debug] 1 device(s) connected
info: Found device LGD855810fa0c2
info: [debug] Setting device id to LGD855810fa0c2
info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
info: [debug] executing cmd: adb -s LGD855810fa0c2 wait-for-device
info: [debug] executing cmd: adb -s LGD855810fa0c2 shell "echo 'ready'"
info: [debug] Starting logcat capture
info: [debug] Pushing unlock helper app to device...
info: [debug] executing cmd: adb -s LGD855810fa0c2 install "/usr/local/lib/node_modules/appium/build/unlock_apk/unlock_apk-debug.apk"
info: [debug] executing cmd: adb -s LGD855810fa0c2 shell "dumpsys window"
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: stdout maxBuffer exceeded.
info: [debug] Error: stdout maxBuffer exceeded.
    at Socket.<anonymous> (child_process.js:689:13)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:764:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at emitReadable (_stream_readable.js:422:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
    at Pipe.onread (net.js:528:21)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: stdout maxBuffer exceeded.)","origValue":"stdout maxBuffer exceeded."},"sessionId":null}
```

**Comment by bayandin** [comment]
Restarts the device fixed this error.

**Comment by moizjv** [comment]
Does not look like an issue any more

**Comment by VenkateshPS** [comment]
I can see this issue happening on 1.4.16.

Steps:

I create two appium instances running on ports 4723 and 4725 and bootstrap port 4724 and 4726.

Tests run on first server for an hour and then I trigger different tests using different appium server , then I get "Error: stdout maxBuffer exceeded.info: [debug] Error: stdout maxBuffer" on second Appium server console.

**Comment by jlipps** [comment]
@VenkateshPS this has been fixed for over a year, you have a very old version of Appium.

**Comment by VenkateshPS** [comment]
@jlipps Please tell the build on which it was fixed.
