### ISSUE TITLE
Appium 1.3.4 Error: Could not initialize ideviceinstaller

### ISSUE THREAD

**Issue by LimeDang** [appium/appium#4626]
Appium 1.3.4
iOS 8.1.3
Xcode 6.1

I have just re-installed Appium v1.3.4 and always get this "Error: Could not initialize ideviceinstaller" when running tests with native application on iOS device 8.1.3
Note: the latest ideviceinstaller is installed as Guide and work properly when type "ideviceinstaller" on Terminal.

2015-03-02 09:47:33:893 - info: Welcome to Appium v1.3.4 (REV c8c79a85fbd6870cd6fc3d66d038a115ebe22efe)
2015-03-02 09:47:33:897 - info: Appium REST http interface listener started on 0.0.0.0:4723
2015-03-02 09:47:33:900 - info: [debug] Non-default server args: {"udid":"223f8c744f08c7776c6b38642920749566e396d2","fullReset":true,"log":"/liemdang/Applications/eclipse/WP/branch_2.0.0.39/MobileLibs/target/classes/MobileLog/Appium.log","defaultCommandTimeout":3600,"tmpDir":"/Users/admin/Appium_Temp"}
2015-03-02 09:47:33:901 - info: Console LogLevel: debug
2015-03-02 09:47:33:901 - info: File LogLevel: debug
2015-03-02 09:47:35:640 - info: --> GET /wd/hub/status {}
2015-03-02 09:47:35:642 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.4","revision":"c8c79a85fbd6870cd6fc3d66d038a115ebe22efe"}}}
2015-03-02 09:47:35:653 - info: <-- GET /wd/hub/status 200 13.027 ms - 104 {"status":0,"value":{"build":{"version":"1.3.4","revision":"c8c79a85fbd6870cd6fc3d66d038a115ebe22efe"}}}
2015-03-02 09:48:01:804 - info: --> POST /wd/hub/session {"desiredCapabilities":{"waitForAppScript":true,"app":"/liemdang/Applications/eclipse/WP/branch_2.0.0.39/MobileLibs/target/classes/drivers/ios/ATCShowRoom.app","autoAcceptAlerts":false,"platformName":"iOS","deviceName":"iPhone5.mobile testing (8.1.3) [223f8c744f08c7776c6b38642920749566e396d2]"}}
2015-03-02 09:48:01:805 - info: Client User-Agent string: Apache-HttpClient/4.3.3 (java 1.5)
2015-03-02 09:48:01:807 - info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : waitForAppScript
2015-03-02 09:48:01:809 - info: [debug] Using local app from desired caps: /liemdang/Applications/eclipse/WP/branch_2.0.0.39/MobileLibs/target/classes/drivers/ios/ATCShowRoom.app
2015-03-02 09:48:01:811 - info: [debug] Creating new appium session 623551b0-0ec3-4c84-8207-5c3e4ab3ac90
2015-03-02 09:48:01:814 - info: [debug] Removing any remaining instruments sockets
2015-03-02 09:48:01:828 - info: [debug] Cleaned up instruments socket /Users/admin/Appium_Temp/instruments_sock
2015-03-02 09:48:01:829 - info: [debug] Setting Xcode folder
2015-03-02 09:48:01:877 - info: [debug] Setting Xcode version
2015-03-02 09:48:02:099 - info: [debug] Setting iOS SDK Version
2015-03-02 09:48:02:167 - info: [debug] Getting sdk version from xcrun with a timeout
2015-03-02 09:48:02:174 - info: [debug] iOS SDK Version set to 8.1
2015-03-02 09:48:02:174 - info: [debug] Not checking whether simulator is available since we're on a real device
2015-03-02 09:48:02:175 - info: [debug] Detecting automation tracetemplate
2015-03-02 09:48:02:183 - info: [debug] Not auto-detecting udid, running on sim
2015-03-02 09:48:02:212 - info: [debug] Could not parse plist file (as binary) at /liemdang/Applications/eclipse/WP/branch_2.0.0.39/MobileLibs/target/classes/drivers/ios/ATCShowRoom.app/en.lproj/Localizable.strings
2015-03-02 09:48:02:212 - info: Will try to parse the plist file as XML
2015-03-02 09:48:02:213 - info: [debug] Could not parse plist file (as XML) at /liemdang/Applications/eclipse/WP/branch_2.0.0.39/MobileLibs/target/classes/drivers/ios/ATCShowRoom.app/en.lproj/Localizable.strings
2015-03-02 09:48:02:214 - warn: Could not parse app Localizable.strings; assuming it doesn't exist
2015-03-02 09:48:02:214 - info: [debug] Getting bundle ID from app
2015-03-02 09:48:02:221 - info: [debug] Parsed app Info.plist (as binary)
2015-03-02 09:48:02:221 - info: [debug] Creating instruments
2015-03-02 09:48:02:222 - info: On some xcode 6 platforms, instruments-without-delay does not work. If you experience this, you will need to re-run appium with the --native-instruments-lib flag
2015-03-02 09:48:02:223 - info: [debug] Preparing uiauto bootstrap
2015-03-02 09:48:02:223 - info: [debug] Dynamic bootstrap dir: /Users/admin/Library/Application Support/appium/bootstrap
2015-03-02 09:48:02:224 - info: [debug] Dynamic env: {"nodePath":"/usr/local/Cellar/node/0.12.0/bin/node","commandProxyClientPath":"/usr/local/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/Users/admin/Appium_Temp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"sendKeyStrategy":"grouped"}
2015-03-02 09:48:02:259 - info: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...
2015-03-02 09:48:02:260 - info: [debug] Dynamic bootstrap path: /Users/admin/Library/Application Support/appium/bootstrap/bootstrap-296c1adf41b0a290.js
2015-03-02 09:48:02:293 - info: [debug] Reusing dynamic bootstrap: /Users/admin/Library/Application Support/appium/bootstrap/bootstrap-296c1adf41b0a290.js
2015-03-02 09:48:02:294 - info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.1","iOSSDKVersion":"8.1","deviceName":"iPhone5.mobile testing (8.1.3) [223f8c744f08c7776c6b38642920749566e396d2]","platformVersion":null}
2015-03-02 09:48:02:294 - info: [debug] fixDevice is on
2015-03-02 09:48:02:295 - info: [debug] Final device string is: 'iPhone5.mobile testing (8.1.3) [223f8c744f08c7776c6b38642920749566e396d2] (8.1 Simulator)'
2015-03-02 09:48:02:296 - info: [debug] Not setting device type since we're on a real device
2015-03-02 09:48:02:297 - info: [debug] Checking whether we need to set app preferences
2015-03-02 09:48:02:297 - info: [debug] Not setting iOS and app preferences since we're on a real device
2015-03-02 09:48:02:297 - info: [debug] Running ios sim reset flow
2015-03-02 09:48:02:298 - info: [debug] Killing the simulator process
2015-03-02 09:48:02:298 - info: [debug] Killall iOS Simulator
2015-03-02 09:48:02:301 - info: [debug] Killing any other simulator daemons
2015-03-02 09:48:02:485 - info: [debug] On a real device; cannot clean device state
2015-03-02 09:48:02:486 - info: [debug] Not setting locale because we're using a real device
2015-03-02 09:48:02:486 - info: [debug] No iOS / app preferences to set
2015-03-02 09:48:02:487 - info: [debug] Starting iOS device log capture via deviceconsole
2015-03-02 09:48:03:783 - info: [debug] Not pre-launching simulator
2015-03-02 09:48:03:783 - info: [debug] Creating iDevice object with udid 223f8c744f08c7776c6b38642920749566e396d2
2015-03-02 09:48:03:784 - info: [debug] Couldn't find ideviceinstaller, trying built-in at /usr/local/lib/node_modules/appium/build/libimobiledevice-macosx/ideviceinstaller
2015-03-02 09:48:03:785 - error: Could not initialize ideviceinstaller; make sure it is installed and works on your system
2015-03-02 09:48:03:785 - info: [debug] Cleaning up appium session
2015-03-02 09:48:03:786 - error: Failed to start an Appium session, err was: Error: Could not initialize ideviceinstaller; make sure it is installed and works on your system
2015-03-02 09:48:03:787 - info: [debug] Error: Could not initialize ideviceinstaller; make sure it is installed and works on your system
    at IOS.getIDeviceObj (/usr/local/lib/node_modules/appium/lib/devices/ios/ios.js:903:13)
    at IOS.installToRealDevice (/usr/local/lib/node_modules/appium/lib/devices/ios/ios.js:850:32)
    at /usr/local/lib/node_modules/appium/node_modules/async/lib/async.js:610:21
    at /usr/local/lib/node_modules/appium/node_modules/async/lib/async.js:249:17
    at iterate (/usr/local/lib/node_modules/appium/node_modules/async/lib/async.js:149:13)
    at /usr/local/lib/node_modules/appium/node_modules/async/lib/async.js:160:25
    at /usr/local/lib/node_modules/appium/node_modules/async/lib/async.js:251:21
    at /usr/local/lib/node_modules/appium/node_modules/async/lib/async.js:615:34
    at IOS.prelaunchSimulator (/usr/local/lib/node_modules/appium/lib/devices/ios/ios.js:1184:12)
    at /usr/local/lib/node_modules/appium/node_modules/async/lib/async.js:610:21
2015-03-02 09:48:03:788 - info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Could not initialize ideviceinstaller; make sure it is installed and works on your system)","origValue":"Could not initialize ideviceinstaller; make sure it is installed and works on your system"},"sessionId":null}
2015-03-02 09:48:03:790 - info: <-- POST /wd/hub/session 500 1986.730 ms - 300

**Comment by imurchie** [comment]
Please see #4584
