### ISSUE TITLE
Appium intermittently (but regularly) fails

### ISSUE THREAD

**Issue by umara123** [appium/appium#4630]
Originally raised in ruby_lib but was told this is an Appium Server issue. (link - https://github.com/appium/ruby_lib/issues/307)

When I run appium on Jenkins I sometimes get a failure resulting in the following trace:

```
[36minfo[39m: Welcome to Appium v1.3.5 (REV a124a15677e26b33db16e81c4b3b34d9c6b8cac9)
[36minfo[39m: Appium REST http interface listener started on 0.0.0.0:10763
[36minfo[39m: [debug] Non-default server args: {"udid":"MY_DEVICE_SERIAL_WAS_HERE","port":10763,"bootstrapPort":20168,"fullReset":true}
[36minfo[39m: Console LogLevel: debug
[36minfo[39m: [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m [90m{"desiredCapabilities":{"platformName":"Android","deviceName":"Android","browserName":"","version":"4.2","app":"http://localhost:8080/job/JOB_TITLE/lastSuccessfulBuild/artifact/thepath/to/apk/my-apk-name.apk","appPackage":"com.my.package.was.here","appActivity":"com.my.package.StartupActivity","newCommandTimeout":300}}[39m
[36minfo[39m: Client User-Agent string: appium/ruby_lib/5.0.1
[36minfo[39m: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : version
[36minfo[39m: [debug] http://localhost:8080/job/JOB_TITLE/lastSuccessfulBuild/artifact/thepath/to/apk/my-apk-name.apk downloaded to /var/folders/23/fwdd50sn3cz33s4q_6h_z_jc0000gn/T/115126-79489-14704i1/appium-app.apk
[36minfo[39m: [debug] Creating new appium session 5d537ef9-61dd-4bcd-bb6a-3eebe1e2988f
[36minfo[39m: Starting android appium
[36minfo[39m: [debug] Getting Java version
[36minfo[39m: Java version is: 1.7.0_51
[36minfo[39m: [debug] Checking whether adb is present
[36minfo[39m: [debug] Using adb from /Users/Android/sdk/platform-tools/adb
[36minfo[39m: [debug] Using fast reset? false
[36minfo[39m: [debug] Preparing device for session
[36minfo[39m: [debug] Checking whether app is actually present
[36minfo[39m: Retrieving device
[36minfo[39m: [debug] Trying to find a connected android device
[36minfo[39m: [debug] Getting connected devices...
[36minfo[39m: [debug] executing cmd: /Users/Android/sdk/platform-tools/adb devices
[36minfo[39m: [debug] 5 device(s) connected
[36minfo[39m: Found device MY_DEVICE_SERIAL_WAS_HERE
[36minfo[39m: [debug] Setting device id to MY_DEVICE_SERIAL_WAS_HERE
[36minfo[39m: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
[36minfo[39m: [debug] executing cmd: /Users/Android/sdk/platform-tools/adb -s MY_DEVICE_SERIAL_WAS_HERE wait-for-device
[36minfo[39m: [debug] executing cmd: /Users/Android/sdk/platform-tools/adb -s MY_DEVICE_SERIAL_WAS_HERE shell "echo 'ready'"
[36minfo[39m: [debug] Starting logcat capture
[36minfo[39m: [debug] Getting device API level
[36minfo[39m: [debug] executing cmd: /Users/Android/sdk/platform-tools/adb -s MY_DEVICE_SERIAL_WAS_HERE shell "getprop ro.build.version.sdk"
[36minfo[39m: [debug] Device is at API Level 19
[36minfo[39m: Device API level is: 19
[36minfo[39m: [debug] executing cmd: /Users/Android/sdk/platform-tools/adb -s MY_DEVICE_SERIAL_WAS_HERE shell "getprop persist.sys.language"
[36minfo[39m: [debug] Current device persist.sys.language: en
[36minfo[39m: [debug] java -jar "/usr/local/lib/node_modules/appium/node_modules/appium-adb/jars/appium_apk_tools.jar" "stringsFromApk" "/var/folders/23/fwdd50sn3cz33s4q_6h_z_jc0000gn/T/115126-79489-14704i1/appium-app.apk" "/tmp/com.my.package.was.here" en
[36minfo[39m: [debug] No strings.xml for language 'en', getting default strings.xml
[36minfo[39m: [debug] java -jar "/usr/local/lib/node_modules/appium/node_modules/appium-adb/jars/appium_apk_tools.jar" "stringsFromApk" "/var/folders/23/fwdd50sn3cz33s4q_6h_z_jc0000gn/T/115126-79489-14704i1/appium-app.apk" "/tmp/com.my.package.was.here"
[31merror[39m: Unhandled error: SyntaxError: Unexpected end of input
    at Object.parse (native)
    at null.<anonymous> (/usr/local/lib/node_modules/appium/lib/devices/android/android-common.js:839:30)
    at null.<anonymous> (/usr/local/lib/node_modules/appium/lib/devices/android/android-common.js:816:7)
    at ChildProcess.exithandler (child_process.js:646:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Socket.<anonymous> (child_process.js:969:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:465:12) context: [POST /wd/hub/session {"desiredCapabilities":{"platformName":"Android","deviceName":"Android","browserName":"","version":"4.2","app":"http://localhost:8080/job/JOB_TITLE/lastSuccessfulBuild/artifact/thepa]
[36minfo[39m: [37m<-- POST /wd/hub/session [39m[32m-[39m[90m - ms - -[39m [90m[39m
```

NOTE: the desired capabilities in the last line cuts off the full path to the .apk

The cucumber output to the console however contains the full path, as expected :

```
{
          :caps[0;37m => [0m{
             :platformName[0;37m => [0m[0;33m"Android"[0m,
               :deviceName[0;37m => [0m[0;33m"Android"[0m,
              :browserName[0;37m => [0m[0;33m""[0m,
                  :version[0;37m => [0m[0;33m"4.2"[0m,
                      :app[0;37m => [0m[0;33m"ttp://localhost:8080/job/JOB_TITLE/lastSuccessfulBuild/artifact/thepath/to/apk/my-apk-name.apk"[0m,
               :appPackage[0;37m => [0m[0;33m"com.my.package.was.here"[0m,
              :appActivity[0;37m => [0m[0;33m"com.my.package.StartupActivity"[0m,
        :newCommandTimeout[0;37m => [0m[1;34m300[0m
    },
    :appium_lib[0;37m => [0m{
        :port[0;37m => [0m[0;33m"10763"[0m
    }
}
```

And the error output from the Cucumber report:
```
end of file reached (EOFError)
/Users/mobile/.rubies/2.1.0/lib/ruby/2.1.0/net/protocol.rb:153:in `read_nonblock'
/Users/mobile/.rubies/2.1.0/lib/ruby/2.1.0/net/protocol.rb:153:in `rbuf_fill'
/Users/mobile/.rubies/2.1.0/lib/ruby/2.1.0/net/protocol.rb:134:in `readuntil'
/Users/mobile/.rubies/2.1.0/lib/ruby/2.1.0/net/protocol.rb:144:in `readline'
/Users/mobile/.rubies/2.1.0/lib/ruby/2.1.0/net/http/response.rb:39:in `read_status_line'
/Users/mobile/.rubies/2.1.0/lib/ruby/2.1.0/net/http/response.rb:28:in `read_new'
/Users/mobile/.rubies/2.1.0/lib/ruby/2.1.0/net/http.rb:1408:in `block in transport_request'
/Users/mobile/.rubies/2.1.0/lib/ruby/2.1.0/net/http.rb:1405:in `catch'
/Users/mobile/.rubies/2.1.0/lib/ruby/2.1.0/net/http.rb:1405:in `transport_request'
/Users/mobile/.rubies/2.1.0/lib/ruby/2.1.0/net/http.rb:1378:in `request'
/Users/mobile/.rubies/2.1.0/lib/ruby/2.1.0/net/http.rb:1371:in `block in request'
/Users/mobile/.rubies/2.1.0/lib/ruby/2.1.0/net/http.rb:853:in `start'
/Users/mobile/.rubies/2.1.0/lib/ruby/2.1.0/net/http.rb:1369:in `request'
/Users/mobile/.gem/ruby/2.1.0/gems/selenium-webdriver-2.41.0/lib/selenium/webdriver/remote/http/default.rb:83:in `response_for'
/Users/mobile/.gem/ruby/2.1.0/gems/selenium-webdriver-2.41.0/lib/selenium/webdriver/remote/http/default.rb:39:in `request'
/Users/mobile/.gem/ruby/2.1.0/gems/selenium-webdriver-2.41.0/lib/selenium/webdriver/remote/http/common.rb:40:in `call'
/Users/mobile/.gem/ruby/2.1.0/gems/appium_lib-5.0.1/lib/appium_lib/common/patch.rb:118:in `raw_execute'
/Users/mobile/.gem/ruby/2.1.0/gems/selenium-webdriver-2.41.0/lib/selenium/webdriver/remote/bridge.rb:99:in `create_session'
/Users/mobile/.gem/ruby/2.1.0/gems/selenium-webdriver-2.41.0/lib/selenium/webdriver/remote/bridge.rb:68:in `initialize'
/Users/mobile/.gem/ruby/2.1.0/gems/selenium-webdriver-2.41.0/lib/selenium/webdriver/common/driver.rb:33:in `new'
/Users/mobile/.gem/ruby/2.1.0/gems/selenium-webdriver-2.41.0/lib/selenium/webdriver/common/driver.rb:33:in `for'
/Users/mobile/.gem/ruby/2.1.0/gems/selenium-webdriver-2.41.0/lib/selenium/webdriver.rb:67:in `for'
/Users/mobile/.gem/ruby/2.1.0/gems/appium_lib-5.0.1/lib/appium_lib/driver.rb:474:in `start_driver'
```

I'm starting the appium server first, then using Cucumber to run the tests.

When this occurs, this causes all the other tests to also fail with this message:
```
[31merror[39m: Failed to start an Appium session, err was: Error: Requested a new session but one was in progress
```

Appium v1.3.5
appium_lib 5.0.1

**Comment by vietnq254** [comment]
Please try ```--session-override``` for Appium server

**Comment by umara123** [comment]
Tried that, still got the same error:

```
[31merror[39m: Unhandled error: SyntaxError: Unexpected end of input
    at Object.parse (native).......etc. etc....same as above
```

**Comment by jhuska** [comment]
I am getting the same exception. My dependencies are as follows:
* appium current master
* java-client:2.2.0

Please, let me know if any of my logs would be helpful.
