### ISSUE TITLE
error: Could not pre-launch appium: Error: spawn OK

### ISSUE THREAD

**Issue by sudhirsingh1** [appium/appium#4632]
Unable to run script in real devices

> Checking if an update is available
> Update not available
> Starting Node Server
> info: [debug] Starting Appium in pre-launch mode
> info: Pre-launching app
> info: [debug] No appActivity desired capability or server param. Parsing from apk.
> info: [debug] No appPackage desired capability or server param. Parsing from apk.
> info: [debug] Using local app from command line: C:\Users\admin\Desktop\Android\adt-bundle-windows-x86-20131030\sdk\tools\TrustYoo(9).apk
> info: [debug] Creating new appium session a0e4596f-bb27-4918-8c44-775358541d52
> info: Starting android appium
> info: [debug] Getting Java version
> info: Java version is: 1.8.0_31
> info: [debug] Using fast reset? true
> info: [debug] Preparing device for session
> info: [debug] Checking whether app is actually present
> info: [debug] Checking whether adb is present
> info: [debug] Using adb from C:\Users\admin\Desktop\Android\adt-bundle-windows-x86-20131030\sdk\platform-tools\adb.exe
> info: [debug] executing cmd: C:\Users\admin\Desktop\Android\adt-bundle-windows-x86-20131030\sdk\platform-tools\adb.exe shell "getprop persist.sys.language"
> error: Error getting device property persist.sys.language: Error: spawn OK
> info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
> warn: UiAutomator did not shut down fast enough, calling it gone
> error: Could not pre-launch appium: Error: spawn OK
> 
> 
> Node Server Process Ended

**Comment by sudhirsingh1** [comment]
How to fix this error ?

**Comment by sebv** [comment]
Could you try with latest appium and provide full server log? thx.

**Comment by sebv** [comment]
Closing, old issue, no activity (sorry for the late response). May be reopened if needed.

**Comment by crhoads1024** [comment]
I am using Appium 1.4.13.1 and I got the same issue.
Full server log here.

> Checking if an update is available
> Starting Node Server
> info: [debug] Starting Appium in pre-launch mode
> info: Pre-launching app
> info: [debug] No appActivity desired capability or server param. Parsing from apk.
> info: [debug] No appPackage desired capability or server param. Parsing from apk.
> info: [debug] Using local app from command line: C:\Automation\Android_Mobile_App_Repository\FlipKart_APK_3.1\flipkart.apk
> info: [debug] Creating new appium session a9b6f426-8475-46aa-b3c7-d4cf62ec6fc5
> info: Starting android appium
> info: [debug] Getting Java version
> info: Java version is: 1.8.0_65
> info: [debug] Using fast reset? false
> info: [debug] Preparing device for session
> info: [debug] Checking whether app is actually present
> info: [debug] Checking whether adb is present
> info: [debug] Using adb from C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe
> info: [debug] executing cmd: "C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe" shell "getprop persist.sys.language"
> error: Error getting device property persist.sys.language: Error: spawn OK
> info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
> warn: UiAutomator did not shut down fast enough, calling it gone
> 
> 
> Node Server Process Ended

**Comment by sudhirsingh1** [comment]
[Appium] Welcome to Appium v1.6.3

[Appium] Non-default server args:

[Appium]   port: 4727

[Appium]   launch: true
[Appium]   robotPort: 4
[Appium]   debugLogSpacing: true
[Appium]   platformName: 'iOS'

[Appium]   platformVersion: '10.1.1'
[Appium]   deviceName: 'iPhone'
[Appium]   app: 'com.app.CGR'
[Appium]   udid: 'e7c69546539cc06d5351e33c6a4aa8cd1f13d263'
[Appium]   fullReset: true
[Appium] Deprecated server args:
[Appium]   --platform-name => --default-capabilities '{"platformName":"iOS"}'
[Appium]   --platform-version => --default-capabilities '{"platformVersion":"10.1.1"}'
[Appium]   --device-name => --default-capabilities '{"deviceName":"iPhone"}'
[Appium]   --app => --default-capabilities '{"app":"com.app.CGR"}'

[Appium]   -U,--udid => --default-capabilities '{"udid":"e7c69546539cc06d5351e33c6a4aa8cd1f13d263"}'
[Appium]   --full-reset => --default-capabilities '{"fullReset":true}'
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '10.1.1'
[Appium]   deviceName: 'iPhone'
[Appium]   app: 'com.app.CGR'
[Appium]   udid: 'e7c69546539cc06d5351e33c6a4aa8cd1f13d263'
[Appium]   fullReset: true

[Appium] Appium REST http interface listener started on 0.0.0.0:4727

[HTTP] --> GET /wd/hub/status {}

[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []

[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.3","revision":null}}

[HTTP] <-- GET /wd/hub/status 200 33 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []

[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.3","revision":null}}

[HTTP] <-- GET /wd/hub/status 200 19 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []

[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.3","revision":null}}

[HTTP] <-- GET /wd/hub/status 200 15 ms - 83 
[HTTP] --> GET /wd/hub/sessions {}
[debug] [MJSONWP] Calling AppiumDriver.getSessions() with args: []
[debug] [MJSONWP] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 4 ms - 40 

[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"iOS","app":"/Users/developer/Downloads/Payload (3).ipa","deviceName":"iPhone","platformVersion":"10.1.1","udid":"e7c69546539cc06d5351e33c6a4aa8cd1f13d263","bundleId":"com.app.CGR","automationName":"Appium"}}

[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"iOS","app":"/Users/developer/Downloads/Payload (3).ipa","deviceName":"iPhone","platformVersion":"10.1.1","udid":"e7c69546539cc06d5351e33c6a4aa8cd1f13d263","bundleId":"com.app.CGR","automationName":"Appium"},null,null,null,null]

[Appium] Requested iOS support with version >= 10, using XCUITest driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.

[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   platformName: 'iOS'
[Appium]   app: '/Users/developer/Downloads/Payload (3).ipa'
[Appium]   deviceName: 'iPhone'
[Appium]   platformVersion: '10.1.1'
[Appium]   udid: 'e7c69546539cc06d5351e33c6a4aa8cd1f13d263'
[Appium]   bundleId: 'com.app.CGR'
[Appium]   automationName: 'Appium'
[Appium]   fullReset: true
[debug] [XCUITest] XCUITestDriver version: 2.4.2

[BaseDriver] Session created with session id: 2b41d900-11c6-4570-9e07-1c71fa79bb4e

[debug] [XCUITest] Xcode version set to '8.2.1'

[debug] [XCUITest] iOS SDK Version set to '10.2'

[debug] [XCUITest] Available devices: e7c69546539cc06d5351e33c6a4aa8cd1f13d263

[debug] [XCUITest] Creating iDevice object with udid e7c69546539cc06d5351e33c6a4aa8cd1f13d263

[XCUITest] Determining device to run tests on: udid: 'e7c69546539cc06d5351e33c6a4aa8cd1f13d263', real device: true
[BaseDriver] Using local app '/Users/developer/Downloads/Payload (3).ipa'
[debug] [BaseDriver] Copying local zip to tmp dir

[debug] [BaseDriver] Unzipping /var/folders/vq/85xfnb8d3f1gbbflrnvy9q1h0000gn/T/20161128-5895-68gmnc.yrhciyhkt9/appium-app.zip

[debug] [BaseDriver] Testing zip archive: /var/folders/vq/85xfnb8d3f1gbbflrnvy9q1h0000gn/T/20161128-5895-68gmnc.yrhciyhkt9/appium-app.zip

[BaseDriver] Unzipped local app to '/var/folders/vq/85xfnb8d3f1gbbflrnvy9q1h0000gn/T/20161128-5895-68gmnc.yrhciyhkt9/Payload/CGR.app'

[debug] [XCUITest] Checking whether app '/var/folders/vq/85xfnb8d3f1gbbflrnvy9q1h0000gn/T/20161128-5895-68gmnc.yrhciyhkt9/Payload/CGR.app' is actually present

[debug] [XCUITest] App is present
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog

[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'

[XCUITest] Setting up real device

[debug] [XCUITest] Error checking install status: Command 'ios-deploy --exists --id e7c69546539cc06d5351e33c6a4aa8cd1f13d263 --bundle_id com.app.CGR' exited with code 255

[debug] [XCUITest] App is not installed. Will try to install.

[debug] [XCUITest] App installed successfully.

[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'

[XCUITest] Launching WebDriverAgent on the device

[debug] [XCUITest] Carthage found: /usr/local/bin/carthage

[debug] [XCUITest] Killing hanging processes

[debug] [XCUITest] Using real device logger 'idevicesyslog'

[debug] [XCUITest] Beginning test with command 'xcodebuild build test -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=e7c69546539cc06d5351e33c6a4aa8cd1f13d263 -configuration Debug' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'

[debug] [XCUITest] Unable to get device time. Using local system time

[debug] [XCUITest] Output from idevicedate: Wed Dec 28 11:56:35 IST 2016


[HTTP] --> GET /wd/hub/status {}

[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []

[XCUITest] Waiting for WebDriverAgent to start on device

[HTTP] <-- GET /wd/hub/status - - ms - - 

[XCUITest] xcodebuild exited with code '70' and signal 'null'

[XCUITest] Error: xcodebuild failed with code 70
    at SubProcess.<anonymous> (../../lib/webdriveragent.js:355:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (../../lib/teen_process.js:197:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
 Error: xcodebuild failed with code 70
    at SubProcess.<anonymous> (../../lib/webdriveragent.js:355:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (../../lib/teen_process.js:197:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

[XCUITest] Shutting down sub-processes

[XCUITest] Shutting down Logger process (pid 6066)
[XCUITest] System log exited with code '0'
[debug] [XCUITest] Running ios real device reset flow
[debug] [XCUITest] Full reset requested. Will try to uninstall the app 'com.app.CGR'.

[HTTP] --> GET /wd/hub/status {}

[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []

[debug] [XCUITest] Removed 'com.app.CGR'

[debug] [XCUITest] Resetting simulator
[debug] [iOSLog] Stopping iOS log capture

[MJSONWP] Encountered internal error running command: Error: xcodebuild failed with code 70
    at SubProcess.<anonymous> (../../lib/webdriveragent.js:355:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (../../lib/teen_process.js:197:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

[HTTP] <-- POST /wd/hub/session 500 81835 ms - 167 

[HTTP] <-- GET /wd/hub/status - - ms - - 

[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.3","revision":null}}

[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.3","revision":null}}

[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.3","revision":null}}

[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.3","revision":null}}

[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.3","revision":null}}

[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.3","revision":null}}

[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.3","revision":null}}

[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.3","revision":null}}
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.3","revision":null}}

[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.3","revision":null}}

[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.3","revision":null}}

[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.3","revision":null}}

[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.3","revision":null}}

[HTTP] --> GET /wd/hub/status {}

[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []

[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.3","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 19 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []

[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.3","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 16 ms - 83 

[Appium] Received SIGTERM - shutting down

**Comment by imurchie** [comment]
Please start a new issue rather than updating an old, closed one.
