### ISSUE TITLE
info: [debug] Checking whether adb is present error: Unhandled error: Error: ENOENT, no such file or directory '/home/vinod/vinod/adt-bundle-linux/sdk/build-tools'     at Error (native)

### ISSUE THREAD

**Issue by vinodakumarsr** [appium/appium#4666]
vinod@vinod-HP-540:~$ appium
info: Welcome to Appium v1.3.6 (REV 004f52f249d3513809e7d0734d9205d1fec19f8e)
info: Appium REST http interface listener started on 0.0.0.0:4723
info: Console LogLevel: debug
info: --> POST /wd/hub/session {"desiredCapabilities":{"platformVersion":"4.4.4","deviceName":"ZX1B338NH2","app":"/home/vinod/SanDiskMemoryZone-com.sandisk.mz-92-v2.1.2.apk","platformName":"Android"}}
info: Client User-Agent string: Python-urllib/2.7
info: [debug] No appActivity desired capability or server param. Parsing from apk.
info: [debug] No appPackage desired capability or server param. Parsing from apk.
info: [debug] Using local app from desired caps: /home/vinod/SanDiskMemoryZone-com.sandisk.mz-92-v2.1.2.apk
info: [debug] Creating new appium session 83b0df5a-eeaa-4b92-a3bb-cd7bae333d3f
info: Starting android appium
info: [debug] Getting Java version
info: Java version is: 1.8.0_40
info: [debug] Checking whether adb is present
error: Unhandled error: Error: ENOENT, no such file or directory '/home/vinod/adt-bundle-linux/sdk/build-tools'
    at Error (native)
    at Object.fs.readdirSync (fs.js:765:18)
    at exports.getDirectories (/home/vinod/.linuxbrew/lib/node_modules/appium/node_modules/appium-adb/lib/helpers.js:100:18)
    at ADB.checkSdkBinaryPresent (/home/vinod/.linuxbrew/lib/node_modules/appium/node_modules/appium-adb/lib/adb.js:97:25)
    at ADB.checkAdbPresent (/home/vinod/.linuxbrew/lib/node_modules/appium/node_modules/appium-adb/lib/adb.js:134:8)
    at Function.ADB.createADB (/home/vinod/.linuxbrew/lib/node_modules/appium/node_modules/appium-adb/lib/adb.js:73:7)
    at androidCommon.initAdb (/home/vinod/.linuxbrew/lib/node_modules/appium/lib/devices/android/android-common.js:1059:9)
    at /home/vinod/.linuxbrew/lib/node_modules/appium/node_modules/async/lib/async.js:610:21
    at /home/vinod/.linuxbrew/lib/node_modules/appium/node_modules/async/lib/async.js:249:17
    at iterate (/home/vinod/.linuxbrew/lib/node_modules/appium/node_modules/async/lib/async.js:149:13) context: [POST /wd/hub/session {"desiredCapabilities":{"platformVersion":"4.4.4","deviceName":"ZX1B338NH2","app":"/home/vinod/SanDiskMemoryZone-com.sandisk.mz-92-v2.1.2.apk","platformName":"Android"}}]

Hi friends pls help me out from the above issue

**Comment by 0x1mason** [comment]
Dup
