### ISSUE TITLE
long press , drag and drop is not working

### ISSUE THREAD

**Issue by vikramvi** [appium/appium#4686]
Please refer to https://github.com/appium/ruby_lib/issues/306#issuecomment-76879007

Hi,
Kindly look into this bug and fix.

normal press , drag and drop is working perfectly but long press , drag and drop is failing with below server error

2015-02-06 18:03:57:563 - info: --> POST /wd/hub/session/ef4ddd59-1899-4f80-ba7c-e3d6ade853d8/touch/perform {"actions":[{"action":"longPress","options":{"x":223,"y":531.5}},{"action":"moveTo","options":{"x":200.5,"y":1017.5}},{"action":"release"}]}
2015-02-06 18:03:57:563 - info: [debug] Pushing command to appium work queue: ["element:getLocation",{}]
2015-02-06 18:03:57:566 - info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:getLocation","params":{}}
2015-02-06 18:03:57:566 - info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
2015-02-06 18:03:57:567 - info: [debug] [BOOTSTRAP] [debug] Got command action: getLocation
2015-02-06 18:03:57:567 - info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":7}

2015-02-06 18:03:57:585 - error: Unhandled error: TypeError: Cannot read property 'x' of undefined
at null. (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/android/android-controller.js:871:29)
at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:801:43)
at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:32:16
at exports.respond (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/common.js:28:9)
at null. (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/android/android.js:484:16)
at null. (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/android/uiautomator.js:93:9)

------- code
ele1_center = center_position text(ele1)
ele1_center.merge(fingers: 1, duration: 3000)
ele2_center = center_position text(ele2)
action = Appium::TouchAction.new.long_press(ele1_center)
action.release.perform.move_to(ele2_center)
action.release.perform

Thanks & Regards,
Vikram

**Comment by imurchie** [comment]
As it stands, [the code for dragging](https://github.com/appium/appium/blob/master/lib/devices/android/android-controller.js#L869) expects the `longPress` to have an element, not coordinates. This, I guess, ought to be changed to handle both coordinates and an element with an offset.

**Comment by imurchie** [comment]
I have a solution for this. I will get it in tomorrow, I hope.

**Comment by imurchie** [comment]
That being said, if you just use the element rather than the position of the element, it ought to work as is.
