### ISSUE TITLE
Unexpected orientation returned: unknown

### ISSUE THREAD

**Issue by sjrjanardhana** [appium/appium#4725]
Appium is not supporting all iOS device orientations, if the device orientation is other than PORTRAIT/LANDSCAPE. I am getting below exception if the orientation is set to UNKNOWN below exception is thrown.

org.openqa.selenium.WebDriverException: Unexpected orientation returned: unknown
Build info: version: '2.42.2', revision: '6a6995d', time: '2014-06-03 17:42:30'
System info: host: 'IN2997-01', ip: '10.102.8.153', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.5', java.version: '1.8.0'
Driver info: driver.version: DAIOSDriver
	at io.appium.java_client.AppiumDriver.getOrientation(AppiumDriver.java:580)
	at com.slingmedia.ios_utils.DAIOSDriver.switchToLandscape(DAIOSDriver.java:608)
	at com.slingmedia.ios_utils.DAiOSUtilities.getStreamingProgramName(DAiOSUtilities.java:413)
	at com.slingmedia.ios_utils.DAiOSUtilities.validateProgramName(DAiOSUtilities.java:490)
	at com.slingmedia.da_ios_test.playback_screen.UC_01_CheckWatchOnPhoneFromMediaCard.test_UC_01_CheckWatchOnPhoneFromMediaCard(UC_01_CheckWatchOnPhoneFromMediaCard.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)

**Comment by tarunsujit** [comment]
Can you send us Appium Logs, so that we can analyse the issue.

**Comment by moizjv** [comment]
@sjrjanardhana thanks for reporting issue. Now you should not be seeing this error. Currently JSON wire protocol supports only LANDSCAPE or PORTRAIT, but we will soon propose to have detailed orientation for iOS.

**Comment by 0x1mason** [comment]
@moiz We're not constrained from offering more than what's contained in the standard. I don't see any reason not to go ahead and add this feature. @jlipps thoughts?

**Comment by jlipps** [comment]
@0x1mason what I'm going to do is make a concrete proposal to the jsonwp-spec group, this is the kind of thing we've already talked about in that discussion group and everyone has agreed it should be part of the new mobile jsonwp in some way. I'm therefore hesitant to just do our own thing since we'd likely have to undo it later.
