### ISSUE TITLE
Parse strings.json Failed When parallel run Appium

### ISSUE THREAD

**Issue by WindOfWestLand** [appium/appium#4759]
Appium Version: 1.3.6
Error Log:
2015-03-23 12:22:44:430 - info: [debug] java -jar "d:\Users\[username]\AppData\Roaming\npm\node_modules\appium\node_modules\appium-adb\jars\appium_apk_tools.jar" "stringsFromApk" "d:\Users\\[username]\.cap\asserts\copy\[APPNAME]" "d:\Users\\[username]\AppData\Local\Temp\\[app_package_name]"
2015-03-23 12:22:45:862 - error: Unhandled error: SyntaxError: Unexpected end of input
    at Object.parse (native)
    at null.<anonymous> (d:\Users\[userna me]\AppData\Roaming\npm\node_modules\appium\lib\devices\android\android-common.js:839:30)
    at null.<anonymous> (d:\Users\[username]\AppData\Roaming\npm\node_modules\appium\lib\devices\android\android-common.js:816:7)
    at ChildProcess.exithandler (child_process.js:735:7)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1080:5) context: [POST /wd/hub/session {"desiredCapabilities":{"automationName":"Appium","app":"d:\\Users\\[username]\\.cap\\asserts\\copy\\[APPNAME]","deviceName":"Android Phone","fullReset":false,"pl]

Perhaps, one process to get strings from apk, another process execute "this.apkStrings = JSON.parse(file);".

**Comment by jhuska** [comment]
As I commented here:
https://github.com/appium/appium/issues/4630#issuecomment-95568616

I am getting the same exception. IMHO these two issues are the same.
