### ISSUE TITLE
Appium iOS real device - issue with ideviceinstaller

### ISSUE THREAD

**Issue by Rajesh902** [appium/appium#4761]
I am running the appium test script on iOS real device., where I am getting the ideviceinstaller error. 
I have installed ideviceinstaller manually using "brew install --HEAD ideviceinstaller" still getting the same error.

**

error: Failed to start an Appium session, err was: Error: Command failed: /bin/sh -c ideviceinstaller -u 0e0615c84ad9c68c7b0f42d2651541c3f38fd4b9 -l dyld: Library not loaded: /usr/local/lib/libplist.3.dylib Referenced from: /usr/local/bin/ideviceinstaller Reason: image not found
========================================================================

**

Please check the below logs.Using xcode 6.1.1 and iOS 8.1.

info: Appium REST http interface listener started on 0.0.0.0:4723
info: Console LogLevel: debug
info: --> POST /wd/hub/session {"desiredCapabilities":{"platformVersion":"8.1.1","app":"/Users/rajesh.madaswamy/FlydotREZ.ipa","deviceName":"iPhone","platformName":"iOS","fullReset":true,"browserName":"","bundleId":"com.accenture.ams.dev.london.Voyage-Air","udid":"0e0615c84ad9c68c7b0f42d2651541c3f38fd4b9"}}
info: Client User-Agent string: Apache-HttpClient/4.3.6 (java 1.5)
info: [debug] Using local .ipa from desired caps: /Users/rajesh.madaswamy/FlydotREZ.ipa
info: [debug] Copying local zip to tmp dir
info: [debug] /Users/rajesh.madaswamy/FlydotREZ.ipa copied to /var/folders/bc/7qkw5sfd221dbcm_fg2fp0g9dhyybh/T/115224-74086-ga247s/appium-app.zip
info: [debug] Unzipping /var/folders/bc/7qkw5sfd221dbcm_fg2fp0g9dhyybh/T/115224-74086-ga247s/appium-app.zip
info: [debug] Testing zip archive: /var/folders/bc/7qkw5sfd221dbcm_fg2fp0g9dhyybh/T/115224-74086-ga247s/appium-app.zip
info: [debug] Zip archive tested clean
info: [debug] Unzip successful
info: [debug] Using locally extracted app: /var/folders/bc/7qkw5sfd221dbcm_fg2fp0g9dhyybh/T/115224-74086-ga247s/Payload/Fly dotREZ.app
info: [debug] Creating new appium session 153304f6-3daf-4ee3-b72c-3f181d3a8ffa
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode folder
info: [debug] Setting Xcode version
info: [debug] Setting iOS SDK Version
info: [debug] Getting sdk version from xcrun with a timeout
info: [debug] iOS SDK Version set to 8.1
info: [debug] Not checking whether simulator is available since we're on a real device
info: [debug] Detecting automation tracetemplate
info: [debug] Not auto-detecting udid, running on sim
info: [debug] Parsed app Info.plist (as binary)
info: [debug] Parsed app Localizable.strings
info: [debug] Creating instruments
info: On some xcode 6 platforms, instruments-without-delay does not work. If you experience this, you will need to re-run appium with the --native-instruments-lib flag
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/rajesh.madaswamy/Library/Application Support/appium/bootstrap
info: [debug] Dynamic env: {"nodePath":"/usr/local/Cellar/node/0.12.0_1/bin/node","commandProxyClientPath":"/Users/rajesh.madaswamy/.npm-packages/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"grouped"}
info: [debug] Dynamic bootstrap code: // This file is automatically generated. D...ot manually modify!
info: [debug] Dynamic bootstrap path: /Users/rajesh.madaswamy/Library/Application Support/appium/bootstrap/bootstrap-4f4c08d246c5f17c.js
info: [debug] Reusing dynamic bootstrap: /Users/rajesh.madaswamy/Library/Application Support/appium/bootstrap/bootstrap-4f4c08d246c5f17c.js
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.1.1","iOSSDKVersion":"8.1","deviceName":"iPhone","platformVersion":"8.1.1"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone (8.1.1 Simulator)'
info: [debug] Not setting device type since we're on a real device
info: [debug] Checking whether we need to set app preferences
info: [debug] Not setting iOS and app preferences since we're on a real device
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killall iOS Simulator
info: [debug] Killing any other simulator daemons
info: [debug] On a real device; cannot clean device state
info: [debug] Not setting locale because we're using a real device
info: [debug] No iOS / app preferences to set
info: [debug] Starting iOS device log capture via deviceconsole
info: [debug] Not pre-launching simulator
info: [debug] Creating iDevice object with udid 0e0615c84ad9c68c7b0f42d2651541c3f38fd4b9
info: [debug] Checking app install status using: /Users/rajesh.madaswamy/.npm-packages/lib/node_modules/appium/build/fruitstrap/fruitstrap isInstalled --id 0e0615c84ad9c68c7b0f42d2651541c3f38fd4b9 --bundle com.accenture.ams.dev.london.Voyage-Air
info: [debug] App is installed.
info: [debug] fullReset requested. Forcing app install.
info: [debug] Installing ipa found at /Users/rajesh.madaswamy/FlydotREZ.ipa
info: [debug] Creating iDevice object with udid 0e0615c84ad9c68c7b0f42d2651541c3f38fd4b9
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: Command failed: /bin/sh -c ideviceinstaller -u 0e0615c84ad9c68c7b0f42d2651541c3f38fd4b9 -l 
dyld: Library not loaded: /usr/local/lib/libplist.3.dylib
  Referenced from: /usr/local/bin/ideviceinstaller
  Reason: image not found

info: [debug] Error: Command failed: /bin/sh -c ideviceinstaller -u 0e0615c84ad9c68c7b0f42d2651541c3f38fd4b9 -l 
dyld: Library not loaded: /usr/local/lib/libplist.3.dylib
  Referenced from: /usr/local/bin/ideviceinstaller
  Reason: image not found

    at ChildProcess.exithandler (child_process.js:744:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Socket.<anonymous> (child_process.js:1176:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:476:12)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Command failed: /bin/sh -c ideviceinstaller -u 0e0615c84ad9c68c7b0f42d2651541c3f38fd4b9 -l \ndyld: Library not loaded: /usr/local/lib/libplist.3.dylib\n  Referenced from: /usr/local/bin/ideviceinstaller\n  Reason: image not found\n)","killed":false,"code":null,"signal":"SIGTRAP","cmd":"/bin/sh -c ideviceinstaller -u 0e0615c84ad9c68c7b0f42d2651541c3f38fd4b9 -l ","origValue":"Command failed: /bin/sh -c ideviceinstaller -u 0e0615c84ad9c68c7b0f42d2651541c3f38fd4b9 -l \ndyld: Library not loaded: /usr/local/lib/libplist.3.dylib\n  Referenced from: /usr/local/bin/ideviceinstaller\n  Reason: image not found\n"},"sessionId":null}
info: <-- POST /wd/hub/session 500 2042.905 ms - 714

**Comment by tarunsujit** [comment]
once try, 'brew unlink ideviceinstaller'  and 'brew link ideviceinstaller'

**Comment by sebv** [comment]
Did you manage to solve this? Not sure why `brew install --HEAD ideviceinstaller` would not work, maybe some permission issues, some old versions...

**Comment by sebv** [comment]
Closing, no activity, may be reopened if needed.

**Comment by srk9ravi** [comment]
I am facing the same above issue with 
appium 1.4.13 and ios 9 

error: Failed to start an Appium session, err was: Error: Command failed: /bin/sh -c ideviceinstaller -u 0e0615c84ad9c68c7b0f42d2651541c3f38fd4b9 -l dyld: Library not loaded: /usr/local/lib/libplist.3.dylib Referenced from: /usr/local/bin/ideviceinstaller Reason: image not found

**Comment by tarumalik** [comment]
I do get the same error, appium 1.4.13 and iOS 9.1

error: Failed to start an Appium session, err was: Error: Command failed: /bin/sh -c /usr/local/bin/idevice_id -l
dyld: Library not loaded: /usr/local/lib/libusbmuxd.4.dylib
  Referenced from: /usr/local/bin/idevice_id
  Reason: image not found


Does anyone has any pointers to update this?

**Comment by taoness** [comment]
I was facing the same error as above.  Appium 1.5.0b6, iOS 9.2.1. I, too, installed ideviceinstaller -HEAD via brew, executed relink and was still encountering the following error:

```
[MJSONWP] Encountered internal error running command: Error: Command failed: ideviceinstaller -u <DEVICE UDID> -l 
dyld: Library not loaded: /usr/local/lib/libusbmuxd.4.dylib
  Referenced from: /usr/local/opt/libimobiledevice/lib/libimobiledevice.6.dylib
  Reason: image not found

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:827:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:475:12)
```

Eventually, I wound up uninstalling ideviceinstaller, then had to relink libtool, libtasn1, libplist, libusb and usbmuxd, and lastly reinstalled ideviceinstaller.  I'm still encounter problems, but I seemingly moved past the previous error.
