### ISSUE TITLE
Can't find Java version

### ISSUE THREAD

**Issue by filipesperandio** [appium/appium#4763]
Version 1.3.6

```
error: Failed to start an Appium session, err was: Error: Could not get the Java version. Is Java installed?
info: [debug] Error: Could not get the Java version. Is Java installed?
    at /Users/filipesperandio/petrofeed/mobile-smoke-tests/node_modules/appium/lib/devices/android/android-common.js:1040:17
    at ChildProcess.exithandler (child_process.js:646:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Socket.<anonymous> (child_process.js:969:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Could not get the Java version. Is Java installed?)","origValue":"Could not get the Java version. Is Java installed?"},"sessionId":null}
info: <-- POST /wd/hub/session 500 175.016 ms - 222
^Cmake: *** [appium-debug] Error 130
```

Version 1.3.3 works with no Java problem with the same setup.

**Comment by filipesperandio** [comment]
I have _JAVA_OPTS set, if I unset it, appium 1.3.6 works, but I don't have any problems with this on 1.3.3.

```
$ echo $_JAVA_OPTIONS
-Djava.awt.headless=true

$ java -version
Picked up _JAVA_OPTIONS: -Djava.awt.headless=true
java version "1.8.0_20"
Java(TM) SE Runtime Environment (build 1.8.0_20-b26)
Java HotSpot(TM) 64-Bit Server VM (build 25.20-b23, mixed mode)

$ unset _JAVA_OPTIONS

$ java -version
java version "1.8.0_20"
Java(TM) SE Runtime Environment (build 1.8.0_20-b26)
Java HotSpot(TM) 64-Bit Server VM (build 25.20-b23, mixed mode)

```

**Comment by tarunsujit** [comment]
try setting JAVA_HOME environment variable

**Comment by filipesperandio** [comment]
It is set. Problem is with parser getting only the first line from `java -version` 
Pull request is on the way.
