### ISSUE TITLE
Error : info: [debug] Zip-aligning C:\Users\amit.ja\Desktop\android\Flipkart.3.0.apk > error: Unhandled error: TypeError: Object [object Object] has no method 'checkZipAlignPresent' > at ADB.zipAlignApk (C:\Users\amit.ja\Desktop\android\AppiumForWindows-1.3.4.1\Appium\node_modules\appium\node_modules\appium-adb\lib\adb.js:449:8) > at null.<anonymous> (C:\Users\amit.ja\Desktop\android\AppiumForWindows-1.3.4.1\Appium\node_modules\appium\node_modules\appium-adb\lib\adb.js:488:10) > at ChildProcess.exithandler (child_process.js:635:7) > at ChildProcess.EventEmitter.emit (events.js:98:17) > at maybeClose (child_process.js:743:16) (#176)

### ISSUE THREAD

**Issue by amitjaincoer191** [appium/appium#4765]
I am getting this error while launching app using appium on real android device

I am using AppiumForWindows-1.3.4.1.zip. Please help me, please

Error logs:

    Checking if an update is available
    Update not available
    Starting Node Server
    info: Welcome to Appium v1.3.4 (REV c8c79a85fbd6870cd6fc3d66d038a115ebe22efe)
    info: Appium REST http interface listener started on 127.0.0.1:4725
    info: [debug] Non-default server args: {"app":"C:\Users\amit.ja\Desktop\android\Flipkart.3.0.apk","address":"127.0.0.1","port":4725,"logNoColors":true,"androidPackage":"com.flipkart.android","androidActivity":"com.flipkart.android.SplashActivity","androidDeviceReadyTimeout":"60","platformName":"Android","platformVersion":"19","automationName":"Appium"}
    info: Console LogLevel: debug
    Killed Node Server.
    Node Server Process Ended
    Starting Node Server
    info: Welcome to Appium v1.3.4 (REV c8c79a85fbd6870cd6fc3d66d038a115ebe22efe)
    info: Appium REST http interface listener started on 127.0.0.1:4725
    info: [debug] Non-default server args: {"address":"127.0.0.1","port":4725,"logNoColors":true,"androidDeviceReadyTimeout":"60","platformName":"Android","platformVersion":"19","automationName":"Appium"}
    info: Console LogLevel: debug
    info: --> POST /wd/hub/session {"desiredCapabilities":{"platformVersion":"4.4.4","app":"C:\Users\amit.ja\Desktop\android\Flipkart.3.0.apk","deviceName":"ZX1B32HNBD","platformName":"Android","browserName":"","appActivity":"com.example.wiziqandroid","device":"MOTOE","appPackage":"com.flipkart.wiziqandroid.SplashActivity"}}
    info: Client User-Agent string: Apache-HttpClient/4.3.6 (java 1.5)
    info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : device
    info: [debug] Using local app from desired caps: C:\Users\amit.ja\Desktop\android\Flipkart.3.0.apk
    info: [debug] Creating new appium session 65207327-762e-4a15-8cda-d2ce096810b6
    info: Starting android appium
    info: [debug] Getting Java version
    info: Java version is: 1.7.0_55
    info: [debug] Using fast reset? true
    info: [debug] Preparing device for session
    info: [debug] Checking whether app is actually present
    info: [debug] Checking whether adb is present
    info: [debug] Using adb from C:\amjain\adt-bundle-windows-x86-20130522\sdk\platform-tools\adb.exe
    info: Retrieving device
    info: [debug] Trying to find a connected android device
    info: [debug] Getting connected devices...
    info: [debug] executing cmd: C:\amjain\adt-bundle-windows-x86-20130522\sdk\platform-tools\adb.exe devices
    info: [debug] 1 device(s) connected
    info: Found device ZX1B32HNBD
    info: [debug] Setting device id to ZX1B32HNBD
    info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 60)
    info: [debug] executing cmd: C:\amjain\adt-bundle-windows-x86-20130522\sdk\platform-tools\adb.exe -s ZX1B32HNBD wait-for-device
    info: [debug] executing cmd: C:\amjain\adt-bundle-windows-x86-20130522\sdk\platform-tools\adb.exe -s ZX1B32HNBD shell "echo 'ready'"
    info: [debug] Starting logcat capture
    info: [debug] Getting device API level
    info: [debug] executing cmd: C:\amjain\adt-bundle-windows-x86-20130522\sdk\platform-tools\adb.exe -s ZX1B32HNBD shell "getprop ro.build.version.sdk"
    info: [debug] Device is at API Level 19
    info: Device API level is: 19
    info: [debug] executing cmd: C:\amjain\adt-bundle-windows-x86-20130522\sdk\platform-tools\adb.exe -s ZX1B32HNBD shell "getprop persist.sys.language"
    info: [debug] Current device persist.sys.language: en
    info: [debug] java -jar "C:\Users\amit.ja\Desktop\android\AppiumForWindows-1.3.4.1\Appium\node_modules\appium\node_modules\appium-adb\jars\appium_apk_tools.jar" "stringsFromApk" "C:\Users\amit.ja\Desktop\android\Flipkart.3.0.apk" "C:\Users\amit.ja\AppData\Local\Temp\com.flipkart.wiziqandroid.SplashActivity" en
    info: [debug] No strings.xml for language 'en', getting default strings.xml
    info: [debug] java -jar "C:\Users\amit.ja\Desktop\android\AppiumForWindows-1.3.4.1\Appium\node_modules\appium\node_modules\appium-adb\jars\appium_apk_tools.jar" "stringsFromApk" "C:\Users\amit.ja\Desktop\android\Flipkart.3.0.apk" "C:\Users\amit.ja\AppData\Local\Temp\com.flipkart.wiziqandroid.SplashActivity"
    info: [debug] executing cmd: C:\amjain\adt-bundle-windows-x86-20130522\sdk\platform-tools\adb.exe -s ZX1B32HNBD push "C:\Users\amit.ja\AppData\Local\Temp\com.flipkart.wiziqandroid.SplashActivity\strings.json" /data/local/tmp
    info: [debug] Checking whether aapt is present
    info: [debug] Using aapt from C:\amjain\adt-bundle-windows-x86-20130522\sdk\build-tools\android-4.2.2\aapt.exe
    info: [debug] Retrieving process from manifest.
    info: [debug] executing cmd: C:\amjain\adt-bundle-windows-x86-20130522\sdk\build-tools\android-4.2.2\aapt.exe dump xmltree C:\Users\amit.ja\Desktop\android\Flipkart.3.0.apk AndroidManifest.xml
    info: [debug] Set app process to: com.flipkart.wiziqandroid.SplashActivity
    info: [debug] Not uninstalling app since server not started with --full-reset
    info: [debug] Checking app cert for C:\Users\amit.ja\Desktop\android\Flipkart.3.0.apk.
    info: [debug] executing cmd: java -jar C:\Users\amit.ja\Desktop\android\AppiumForWindows-1.3.4.1\Appium\node_modules\appium\node_modules\appium-adb\jars\verify.jar C:\Users\amit.ja\Desktop\android\Flipkart.3.0.apk
    info: [debug] App already signed.
    info: [debug] Zip-aligning C:\Users\amit.ja\Desktop\android\Flipkart.3.0.apk
    error: Unhandled error: TypeError: Object [object Object] has no method 'checkZipAlignPresent'
    at ADB.zipAlignApk (C:\Users\amit.ja\Desktop\android\AppiumForWindows-1.3.4.1\Appium\node_modules\appium\node_modules\appium-adb\lib\adb.js:449:8)
    at null. (C:\Users\amit.ja\Desktop\android\AppiumForWindows-1.3.4.1\Appium\node_modules\appium\node_modules\appium-adb\lib\adb.js:488:10)
    at ChildProcess.exithandler (child_process.js:635:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:743:16)
    at Process.ChildProcess._handle.onexit (child_process.js:810:5) context: [POST /wd/hub/session {"desiredCapabilities":{"platformVersion":"4.4.4","app":"C:\Users\amit.ja\Desktop\android\Flipkart.3.0.apk","deviceName":"ZX1B32HNBD","platformName":"Android","browserName":"","appActivity":"com.]

**Comment by moizjv** [comment]
@amitjaincoer191 can you retry with [appium 1.3.7](https://bitbucket.org/appium/appium.app/downloads/).  also are you running as admin?

**Comment by sebv** [comment]
And change the issue title...

**Comment by sebv** [comment]
Closing no activity, may be reopened if needed.
