### ISSUE TITLE
IsDisplayed returning false for a visible element , making it inaccessible. 

### ISSUE THREAD

**Issue by jainswati02** [appium/appium#4781]
Hi All,

My team is using appium for automation of our ipad app.
For a text field I am getting weird behaviour.
When I get text field value it is working fine but if I am trying to tap on it & set a value using send key it is not working.

when I checked appium log I figured out isDisplayed() function is returning false for this element.
I see various post related to this problem but didn't got any solution.

Adding sleep is also not working.

Appium version : 1.3.6
Ios version : 8.1

Please suggest how I can resolve this issue.

**Comment by sofaking** [comment]
1) Are you sure you have only one text field element with parameters you're searching it with? For example in complicated collection view sometimes you can have several absolutely identical elements except that only one of them isDisplayed == true.
2) Please, attach some logs here.

**Comment by jainswati02** [comment]
@sofaking : Thanks for looking into it.

I checked again though appium inspector , xpath which I am using is only referencing to the text field I am trying to access.
 
Below are the appium log :-1: 

015-03-25 19:45:12:316 - info: [debug] [INST] 2015-03-25 19:45:12 +0000 Debug: Got new command 46 from instruments: au.getElementsByIndexPaths(["/0/0/16/0/8"])
2015-03-25 19:45:12:320 - info: [debug] [INST] 2015-03-25 19:45:12 +0000 Debug: evaluating au.getElementsByIndexPaths(["/0/0/16/0/8"])
2015-03-25 19:45:12:324 - info: [debug] [INST] 2015-03-25 19:45:12 +0000 Debug: evaluation finished
2015-03-25 19:45:12:329 - info: [debug] [INST] 2015-03-25 19:45:12 +0000 Debug: Lookup returned [object UIATextField] with the name "Friendly Account Name" (id: 18).
2015-03-25 19:45:12:334 - info: [debug] [INST] 2015-03-25 19:45:12 +0000 Debug: responding with:
2015-03-25 19:45:12:340 - info: [debug] [INST] 2015-03-25 19:45:12 +0000 Debug: Running system command #47: /usr/local/Cellar/node/0.12.0/bin/node /usr/local/Cellar/node/0.12.0/libexec/npm/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":[{"ELEMENT":"18"}]}...
2015-03-25 19:45:12:362 - info: [debug] Socket data received (41 bytes)
2015-03-25 19:45:12:363 - info: [debug] Socket data being routed.
2015-03-25 19:45:12:363 - info: [debug] Got result from instruments: {"status":0,"value":[{"ELEMENT":"18"}]}
2015-03-25 19:45:12:363 - info: [debug] Responding to client with success: {"status":0,"value":[{"ELEMENT":"18"}],"sessionId":"73f24014-0d46-491d-af3d-661d510fc38a"}
2015-03-25 19:45:12:363 - info: <-- POST /wd/hub/session/73f24014-0d46-491d-af3d-661d510fc38a/elements 200 211.334 ms - 90 {"status":0,"value":[{"ELEMENT":"18"}],"sessionId":"73f24014-0d46-491d-af3d-661d510fc38a"}
2015-03-25 19:45:12:365 - info: --> GET /wd/hub/session/73f24014-0d46-491d-af3d-661d510fc38a/element/18/displayed {}
2015-03-25 19:45:12:366 - info: [debug] Pushing command to appium work queue: "au.getElement('18').isDisplayed()"
2015-03-25 19:45:12:366 - info: [debug] Sending command to instruments: au.getElement('18').isDisplayed()
2015-03-25 19:45:12:430 - info: [debug] Socket data received (28 bytes)
2015-03-25 19:45:12:430 - info: [debug] Socket data being routed.
2015-03-25 19:45:12:430 - info: [debug] Got result from instruments: {"status":0,"value":false}
2015-03-25 19:45:12:430 - info: [debug] Responding to client with success: {"status":0,"value":false,"sessionId":"73f24014-0d46-491d-af3d-661d510fc38a"}
2015-03-25 19:45:12:431 - info: <-- GET /wd/hub/session/73f24014-0d46-491d-af3d-661d510fc38a/element/18/displayed 200 65.371 ms - 77 {"status":0,"value":false,"sessionId":"73f24014-0d46-491d-af3d-661d510fc38a"}
2015-03-25 19:45:12:434 - info: [debug] [INST] 2015-03-25 19:45:12 +0000 Debug: Got new command 47 from instruments: au.getElement('18').isDisplayed()

isDisplayed function is returning false
###############################################

Below are the log from my text case :-1: 

KEYWORD: CatamaranAccountManagementScreenKeywords.Verify account field at index is Friendly Account Name, 1, ${Friendly Name} Expand All
Documentation:	
Find a text field with the given name in the cell at the given index and
Start / End / Elapsed:	20150325 14:45:06.721 / 20150325 14:45:07.005 / 00:00:00.284
KEYWORD: ${Actual Value} = AppiumLibrary.Get Element Value xpath=//UIATableView[@name="AccountTableView"]/UIATableCell[${Index}]/UIATextField[@name="${Field Name}"] Expand All
Start / End / Elapsed:	20150325 14:45:06.722 / 20150325 14:45:07.004 / 00:00:00.282
14:45:06.723	TRACE	Arguments: [ u'xpath=//UIATableView[@name="AccountTableView"]/UIATableCell[1]/UIATextField[@name="Friendly Account Name"]' ]	
14:45:06.723	DEBUG	POST http://127.0.0.1:63072/wd/hub/session/73f24014-0d46-491d-af3d-661d510fc38a/elements {"using": "xpath", "sessionId": "73f24014-0d46-491d-af3d-661d510fc38a", "value": "//UIATableView[@name=\"AccountTableView\"]/UIATableCell[1]/UIATextField[@name=\"Friendly Account Name\"]"}	
14:45:06.938	DEBUG	Finished Request	
14:45:06.938	DEBUG	GET http://127.0.0.1:63072/wd/hub/session/73f24014-0d46-491d-af3d-661d510fc38a/element/13/attribute/value {"sessionId": "73f24014-0d46-491d-af3d-661d510fc38a", "name": "value", "id": "13"}	
14:45:07.004	DEBUG	Finished Request	
14:45:07.004	TRACE	Return: u'user@server.company.com'	
14:45:07.004	INFO	${Actual Value} = user@server.company.com	
KEYWORD: BuiltIn.Should Be Equal ${Expected Value}, ${Actual Value}, Field '${Field Name}' was supposed to be '${Expected Value}' but it was '${Actual Value}' Expand All
14:45:06.722	TRACE	Arguments: [ ${Field Name}=u'Friendly Account Name' | ${Index}=u'1' | ${Expected Value}=u'user@server.company.com' ]	
14:45:07.005	TRACE	Return: None	
KEYWORD: CatamaranAccountManagementScreenKeywords.Set account field at index to Friendly Account Name, 1, ${Friendly Name2} Expand All
Documentation:	
Find a text field with the given name in the cell at the given index and
Start / End / Elapsed:	20150325 14:45:07.006 / 20150325 14:45:12.433 / 00:00:05.427
KEYWORD: AppiumLibrary.Tap xpath=//UIATableView[@name="AccountTableView"]/UIATableCell[${Index}]/UIATextField[@name="${Field Name}"] Expand All
Start / End / Elapsed:	20150325 14:45:07.007 / 20150325 14:45:12.432 / 00:00:05.425
14:45:07.007	TRACE	Arguments: [ u'xpath=//UIATableView[@name="AccountTableView"]/UIATableCell[1]/UIATextField[@name="Friendly Account Name"]' ]	
14:45:07.007	DEBUG	POST http://127.0.0.1:63072/wd/hub/session/73f24014-0d46-491d-af3d-661d510fc38a/elements {"using": "xpath", "sessionId": "73f24014-0d46-491d-af3d-661d510fc38a", "value": "//UIATableView[@name=\"AccountTableView\"]/UIATableCell[1]/UIATextField[@name=\"Friendly Account Name\"]"}	
14:45:07.219	DEBUG	Finished Request	
14:45:07.219	DEBUG	GET http://127.0.0.1:63072/wd/hub/session/73f24014-0d46-491d-af3d-661d510fc38a/element/14/displayed {"sessionId": "73f24014-0d46-491d-af3d-661d510fc38a", "id": "14"}	
14:45:07.286	DEBUG	Finished Request	
14:45:08.291	DEBUG	POST http://127.0.0.1:63072/wd/hub/session/73f24014-0d46-491d-af3d-661d510fc38a/elements {"using": "xpath", "sessionId": "73f24014-0d46-491d-af3d-661d510fc38a", "value": "//UIATableView[@name=\"AccountTableView\"]/UIATableCell[1]/UIATextField[@name=\"Friendly Account Name\"]"}	
14:45:08.505	DEBUG	Finished Request	
14:45:08.505	DEBUG	GET http://127.0.0.1:63072/wd/hub/session/73f24014-0d46-491d-af3d-661d510fc38a/element/15/displayed {"sessionId": "73f24014-0d46-491d-af3d-661d510fc38a", "id": "15"}	
14:45:08.577	DEBUG	Finished Request	
14:45:09.583	DEBUG	POST http://127.0.0.1:63072/wd/hub/session/73f24014-0d46-491d-af3d-661d510fc38a/elements {"using": "xpath", "sessionId": "73f24014-0d46-491d-af3d-661d510fc38a", "value": "//UIATableView[@name=\"AccountTableView\"]/UIATableCell[1]/UIATextField[@name=\"Friendly Account Name\"]"}	
14:45:09.799	DEBUG	Finished Request	
14:45:09.799	DEBUG	GET http://127.0.0.1:63072/wd/hub/session/73f24014-0d46-491d-af3d-661d510fc38a/element/16/displayed {"sessionId": "73f24014-0d46-491d-af3d-661d510fc38a", "id": "16"}	
14:45:09.867	DEBUG	Finished Request	
14:45:10.870	DEBUG	POST http://127.0.0.1:63072/wd/hub/session/73f24014-0d46-491d-af3d-661d510fc38a/elements {"using": "xpath", "sessionId": "73f24014-0d46-491d-af3d-661d510fc38a", "value": "//UIATableView[@name=\"AccountTableView\"]/UIATableCell[1]/UIATextField[@name=\"Friendly Account Name\"]"}	
14:45:11.079	DEBUG	Finished Request	
14:45:11.079	DEBUG	GET http://127.0.0.1:63072/wd/hub/session/73f24014-0d46-491d-af3d-661d510fc38a/element/17/displayed {"sessionId": "73f24014-0d46-491d-af3d-661d510fc38a", "id": "17"}	
14:45:11.149	DEBUG	Finished Request	
14:45:12.150	DEBUG	POST http://127.0.0.1:63072/wd/hub/session/73f24014-0d46-491d-af3d-661d510fc38a/elements {"using": "xpath", "sessionId": "73f24014-0d46-491d-af3d-661d510fc38a", "value": "//UIATableView[@name=\"AccountTableView\"]/UIATableCell[1]/UIATextField[@name=\"Friendly Account Name\"]"}	
14:45:12.364	DEBUG	Finished Request	
14:45:12.364	DEBUG	GET http://127.0.0.1:63072/wd/hub/session/73f24014-0d46-491d-af3d-661d510fc38a/element/18/displayed {"sessionId": "73f24014-0d46-491d-af3d-661d510fc38a", "id": "18"}	
14:45:12.432	DEBUG	Finished Request	
14:45:12.432	FAIL	Timeout exceeded waiting for screen to contain xpath=//UIATableView[@name="AccountTableView"]/UIATableCell[1]/UIATextField[@name="Friendly Account Name"]	
14:45:12.432	DEBUG	Traceback (most recent call last):
  File "/Users/sjain/SourceCode/Automation/Keywords/iOS/AppiumLibrary/keywords/_interactions.py", line 9, in tap
    self.wait_for_screen_to_contain_element(locator)
  File "/Users/sjain/SourceCode/Automation/Keywords/iOS/AppiumLibrary/keywords/_interactions.py", line 196, in wait_for_screen_to_contain_element
    raise AssertionError(error)	
14:45:07.007	TRACE	Arguments: [ ${Field Name}=u'Friendly Account Name' | ${Index}=u'1' | ${Value}=u'user2@server.company2.com' ]


First I just tried to get the value & it worked.
But setting a new value in it is not working

**Comment by jainswati02** [comment]
@sofaking : Any suggestion?

**Comment by sofaking** [comment]
No idea, to be honest. But I don't think this issue is caused by appium.
For further investigation I'd suggest reproduce the issue with Instruments and go to the developers with the results. They usually come up with some ideas what can be changed to make an element visible.

BTW, just to let you know. Once I saw similar issue with UIAStaticText. `nil` was assigned as it's value and as a result not only the element itself become invisible, but I wasn't able to see even it's container.

**Comment by sebv** [comment]
Could you print a page source before the send key. Maybe you need to do some scrolling to make the element visible. It's the same as if you were testing the app manually, if it is not visible how do you send key to it?

**Comment by sebv** [comment]
Closing, no activity, may be reopened if needed.
