### ISSUE TITLE
Specified target process is invalid for ipa while installing in real device

### ISSUE THREAD

**Issue by chandrakanth1984** [appium/appium#4786]
Hi,

I am using latest Appium version 1.3.6 for automation and tried to install an ipa file in real device which was created with xcode 6.1.1.

But always I am getting below error saying "Specified target process is invalid" 

Appium Version: 1.3.6
XCode used for creating ipa: XCode 6.1.1
Executing the Appium tests against XCode 6.2

I am able to run .app files in simulator using same appium version and xcode version.

Appium Log:
info: [debug] Nothing found on device, going ahead and installing.

info: [debug] Starting command proxy.

info: [debug] Instruments socket server started at /tmp/instruments_sock

info: [debug] Starting instruments
info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
info: Launching instruments

info: [debug] Attempting to run app on real device with UDID 61b987111b9e8c695f0752902619ddf8470be286
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w 61b987111b9e8c695f0752902619ddf8470be286 com.macquarie.pb.mbanking.Banking -e UIASCRIPT "/Users/pbtester2/Library/Application Support/appium/bootstrap/bootstrap-2911698fabce8e2c.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {}
info: [debug] And launch timeouts (in ms): {"global":90000}

info: [IOS_SYSLOG_ROW ] Mar 26 11:26:29 PBTesters-iPhone syslog_relay[203] <Notice>: syslog_relay found the ASL prompt. Starting...

info: [IOS_SYSLOG_ROW ] Mar 26 11:26:31 PBTesters-iPhone notification_proxy[155] <Error>: 0x100484000 -[MNPLockdownConnection receiveMessage]: lockdown_receive_message error!

info: [debug] [INST STDERR] 2015-03-26 11:26:33.069 instruments[842:1307] WebKit Threading Violation - initial use of WebKit from a secondary thread.

info: [debug] [INST STDERR] Instruments Usage Error : Specified target process is invalid: com.macquarie.pb.mbanking.Banking

**Comment by sebv** [comment]
Could you post full log (in a gist)? thx.

**Comment by sebv** [comment]
Closing, old issue, no activity (and sorry for the late response). May be reopened if needed.

**Comment by chandrakanth1984** [comment]
Hi,

Sorry I did not respond as I have gone out of track for this issue because I raised the issue on Mar 26 and there is no response until Jun 3.

Please let me know the how we can reopen this issue?

Also please find the full appium log with latest details below,

Appium Version: 1.4.8
Executing the Appium tests against XCode 6.4

Appium Full Log:
Launching Appium with command: '/Applications/Appium.app/Contents/Resources/node/bin/node' lib/server/main.js --address "127.0.0.1" --command-timeout "7200" --session-override --debug-log-spacing --log-timestamp --platform-version "8.4" --platform-name "iOS" --app "/Users/pbtester2/Documents/Chandrakanth/MobileAppsAutomation/mbanking-ios-dev-0.1.171-20150804.050827-4.ipa" --udid "2b6c6c99a9f861eed7b1237b26207c71a472ab2c" --show-ios-log --show-ios-log --backend-retries "1" --device-name "Chandrakanth Achyuta’s iPad" --launch-timeout "90000" --native-instruments-lib

2015-08-04 06:07:51:025 - info: Welcome to Appium v1.4.8 (REV c8179bd8352d3c62d98fa58b324491230df9342a)

2015-08-04 06:07:51:028 - info: Appium REST http interface listener started on 127.0.0.1:4723

2015-08-04 06:07:51:032 - info: [debug] Non-default server args: {"app":"/Users/pbtester2/Documents/Chandrakanth/MobileAppsAutomation/mbanking-ios-dev-0.1.171-20150804.050827-4.ipa","udid":"2b6c6c99a9f861eed7b1237b26207c71a472ab2c","address":"127.0.0.1","backendRetries":1,"sessionOverride":true,"launchTimeout":"90000","logTimestamp":true,"nativeInstrumentsLib":true,"deviceName":"Chandrakanth Achyuta’s iPad","platformName":"iOS","platformVersion":"8.4","showIOSLog":true,"defaultCommandTimeout":7200,"debugLogSpacing":true}
2015-08-04 06:07:51:033 - info: Console LogLevel: debug

2015-08-04 06:07:51:423 - info: --> GET /wd/hub/status {}

2015-08-04 06:07:51:425 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}}}

2015-08-04 06:07:51:433 - info: <-- GET /wd/hub/status 200 10.162 ms - 104 {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}}}

2015-08-04 06:07:51:918 - info: --> GET /wd/hub/status {}

2015-08-04 06:07:51:919 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}}}

2015-08-04 06:07:51:922 - info: <-- GET /wd/hub/status 200 4.392 ms - 104 {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}}}

2015-08-04 06:07:52:266 - info: --> GET /wd/hub/status {}

2015-08-04 06:07:52:267 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}}}
2015-08-04 06:07:52:269 - info: <-- GET /wd/hub/status 200 2.617 ms - 104 {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}}}
2015-08-04 06:07:52:271 - info: --> GET /wd/hub/sessions {}
2015-08-04 06:07:52:272 - info: [debug] Responding to client with success: {"status":0,"value":[]}
2015-08-04 06:07:52:273 - info: <-- GET /wd/hub/sessions 200 1.420 ms - 23 {"status":0,"value":[]}

2015-08-04 06:07:52:303 - info: --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"iOS","platformVersion":"8.4","newCommandTimeout":"999999","automationName":"Appium","deviceName":"Chandrakanth Achyuta’s iPad"}}

2015-08-04 06:07:52:304 - info: Client User-Agent string: Appium (unknown version) CFNetwork/720.3.13 Darwin/14.3.0 (x86_64)
2015-08-04 06:07:52:304 - info: *************************************

2015-08-04 06:07:52:304 - info: *************************************
2015-08-04 06:07:52:305 - info: *************************************
2015-08-04 06:07:52:305 - info: *************************************
2015-08-04 06:07:52:305 - info: *************************************
2015-08-04 06:07:52:305 - info: *************************************
2015-08-04 06:07:52:305 - info: *************************************
2015-08-04 06:07:52:305 - info: *************************************
2015-08-04 06:07:52:305 - info: ****        NEW SESSION           ***
2015-08-04 06:07:52:305 - info: ****        NEW SESSION           ***
2015-08-04 06:07:52:305 - info: ****        NEW SESSION           ***
2015-08-04 06:07:52:306 - info: ****        NEW SESSION           ***
2015-08-04 06:07:52:306 - info: ****        NEW SESSION           ***
2015-08-04 06:07:52:306 - info: ****        NEW SESSION           ***
2015-08-04 06:07:52:306 - info: ****        NEW SESSION           ***
2015-08-04 06:07:52:306 - info: ****        NEW SESSION           ***
2015-08-04 06:07:52:306 - info: *************************************
2015-08-04 06:07:52:306 - info: *************************************
2015-08-04 06:07:52:307 - info: *************************************
2015-08-04 06:07:52:307 - info: *************************************
2015-08-04 06:07:52:307 - info: *************************************
2015-08-04 06:07:52:307 - info: *************************************
2015-08-04 06:07:52:307 - info: *************************************
2015-08-04 06:07:52:308 - info: *************************************
2015-08-04 06:07:52:312 - info: [debug] Using local .ipa from command line: /Users/pbtester2/Documents/Chandrakanth/MobileAppsAutomation/mbanking-ios-dev-0.1.171-20150804.050827-4.ipa
2015-08-04 06:07:52:312 - info: [debug] Copying local zip to tmp dir

2015-08-04 06:07:52:438 - info: [debug] /Users/pbtester2/Documents/Chandrakanth/MobileAppsAutomation/mbanking-ios-dev-0.1.171-20150804.050827-4.ipa copied to /var/folders/r5/y0yjny7n74z6t_xsvzkzn1j00000gn/T/11574-4560-9on1z6/appium-app.zip

2015-08-04 06:07:52:461 - info: [debug] Unzipping /var/folders/r5/y0yjny7n74z6t_xsvzkzn1j00000gn/T/11574-4560-9on1z6/appium-app.zip

2015-08-04 06:07:52:461 - info: [debug] Testing zip archive: /var/folders/r5/y0yjny7n74z6t_xsvzkzn1j00000gn/T/11574-4560-9on1z6/appium-app.zip

2015-08-04 06:07:52:831 - info: [debug] Zip archive tested clean

2015-08-04 06:07:53:370 - info: [debug] Unzip successful

2015-08-04 06:07:53:371 - info: [debug] Using locally extracted app: /var/folders/r5/y0yjny7n74z6t_xsvzkzn1j00000gn/T/11574-4560-9on1z6/Payload/Banking.app

2015-08-04 06:07:53:372 - info: [debug] Creating new appium session 52884aa5-0743-46c6-97b1-6be0d52a81c4
2015-08-04 06:07:53:374 - info: [debug] Removing any remaining instruments sockets
2015-08-04 06:07:53:376 - info: [debug] Cleaned up instruments socket /tmp/instruments_sock
2015-08-04 06:07:53:376 - info: [debug] Auto-detecting iOS udid...
2015-08-04 06:07:53:376 - info: [debug] Not auto-detecting udid, running on sim
2015-08-04 06:07:53:377 - info: [debug] Could not parse plist file (as binary) at /var/folders/r5/y0yjny7n74z6t_xsvzkzn1j00000gn/T/11574-4560-9on1z6/Payload/Banking.app/en.lproj/Localizable.strings
2015-08-04 06:07:53:377 - info: Will try to parse the plist file as XML
2015-08-04 06:07:53:378 - info: [debug] Could not parse plist file (as XML) at /var/folders/r5/y0yjny7n74z6t_xsvzkzn1j00000gn/T/11574-4560-9on1z6/Payload/Banking.app/en.lproj/Localizable.strings
2015-08-04 06:07:53:378 - warn: Could not parse app Localizable.strings assuming it doesn't exist
2015-08-04 06:07:53:378 - info: [debug] Getting bundle ID from app
2015-08-04 06:07:53:383 - info: [debug] Parsed app Info.plist (as binary)
2015-08-04 06:07:53:383 - info: [debug] Creating instruments

2015-08-04 06:07:53:384 - info: [debug] Preparing uiauto bootstrap
2015-08-04 06:07:53:384 - info: [debug] Dynamic bootstrap dir: /Users/pbtester2/Library/Application Support/appium/bootstrap
2015-08-04 06:07:53:384 - info: [debug] Dynamic env: {"nodePath":"/Applications/Appium.app/Contents/Resources/node/bin/node","commandProxyClientPath":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"grouped"}

2015-08-04 06:07:53:421 - info: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...
2015-08-04 06:07:53:421 - info: [debug] Dynamic bootstrap path: /Users/pbtester2/Library/Application Support/appium/bootstrap/bootstrap-6745615c424bb0c0.js

2015-08-04 06:07:53:426 - info: [debug] Reusing dynamic bootstrap: /Users/pbtester2/Library/Application Support/appium/bootstrap/bootstrap-6745615c424bb0c0.js
2015-08-04 06:07:53:428 - info: [debug] Attempting iOS device log capture via libimobiledevice idevicesyslog

2015-08-04 06:07:53:649 - info: [debug] Creating iDevice object with udid 2b6c6c99a9f861eed7b1237b26207c71a472ab2c

2015-08-04 06:07:55:021 - info: --> GET /wd/hub/status {}

2015-08-04 06:07:55:022 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"},"isShuttingDown":false},"sessionId":"52884aa5-0743-46c6-97b1-6be0d52a81c4"}

2015-08-04 06:07:55:024 - info: <-- GET /wd/hub/status 200 2.307 ms - 178 {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"},"isShuttingDown":false},"sessionId":"52884aa5-0743-46c6-97b1-6be0d52a81c4"}
2015-08-04 06:07:55:025 - info: --> GET /wd/hub/status {}
2015-08-04 06:07:55:025 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"},"isShuttingDown":false},"sessionId":"52884aa5-0743-46c6-97b1-6be0d52a81c4"}
2015-08-04 06:07:55:026 - info: <-- GET /wd/hub/status 200 1.213 ms - 178 {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"},"isShuttingDown":false},"sessionId":"52884aa5-0743-46c6-97b1-6be0d52a81c4"}

2015-08-04 06:07:55:305 - info: [debug] App is not installed. Will try to install the app.

2015-08-04 06:07:55:305 - info: [debug] Installing ipa found at /Users/pbtester2/Documents/Chandrakanth/MobileAppsAutomation/mbanking-ios-dev-0.1.171-20150804.050827-4.ipa

2015-08-04 06:07:55:519 - info: [debug] Nothing found on device, going ahead and installing.

2015-08-04 06:08:00:635 - info: [IOS_SYSLOG_ROW ] Aug  4 16:07:54 Chandrakanth-Achyutas-iPad installd[36] <Notice>: 0x443000 -[MIInstaller performInstallationWithError:]: Installing <MIInstallableBundle ID=com.macquarie.pb.mbanking.Banking; Version=1, ShortVersion=0.1.171>

2015-08-04 06:08:00:915 - info: [IOS_SYSLOG_ROW ] Aug  4 16:07:54 Chandrakanth-Achyutas-iPad MobileStorageMounter[434] <Error>: 0x34f3f9dc Device-O-Matic: iterate_ancestors IORegistryEntryGetParentIterator failed: No such process

2015-08-04 06:08:00:986 - info: [IOS_SYSLOG_ROW ] Aug  4 16:07:54 Chandrakanth-Achyutas-iPad MobileStorageMounter[434] <Error>: 0x34f3f9dc Device-O-Matic: iterate_ancestors IORegistryEntryGetParentIterator failed: No such file or directory

2015-08-04 06:08:00:990 - info: [IOS_SYSLOG_ROW ] Aug  4 16:07:54 Chandrakanth-Achyutas-iPad MobileStorageMounter[434] <Error>: 0x34f3f9dc Device-O-Matic: iterate_ancestors IORegistryEntryGetParentIterator failed: No such file or directory

2015-08-04 06:08:00:994 - info: [IOS_SYSLOG_ROW ] Aug  4 16:07:54 Chandrakanth-Achyutas-iPad MobileStorageMounter[434] <Error>: 0x34f3f9dc Device-O-Matic: iterate_ancestors IORegistryEntryGetParentIterator failed: No such file or directory
2015-08-04 06:08:01:000 - info: [IOS_SYSLOG_ROW ] Aug  4 16:07:54 Chandrakanth-Achyutas-iPad profiled[108] <Notice>: (Note ) MC: Provisioning profiles changed
2015-08-04 06:08:01:000 - info: [IOS_SYSLOG_ROW ] Aug  4 16:07:54 Chandrakanth-Achyutas-iPad installd[36] <Error>:  SecTrustEvaluate  [leaf CriticalExtensions IssuerCommonName]

2015-08-04 06:08:01:772 - info: [IOS_SYSLOG_ROW ] Aug  4 16:07:55 Chandrakanth-Achyutas-iPad installd[36] <Error>: resource deleted: /private/var/mobile/Library/Caches/com.apple.mobile.installd.staging/temp.qmv567/extracted/Payload/Banking.app/archived-expanded-entitlements.xcent

2015-08-04 06:08:01:779 - info: [IOS_SYSLOG_ROW ] Aug  4 16:07:55 Chandrakanth-Achyutas-iPad installd[36] <Error>: 0x443000 -[MICodeSigningVerifier performValidationWithError:]: 188: Failed to verify code signature of <MIExecutableBundle : path = /private/var/mobile/Library/Caches/com.apple.mobile.installd.staging/temp.qmv567/extracted/Payload/Banking.app identifier = com.macquarie.pb.mbanking.Banking type = User App> : 0xe8008017 (Signed resources have been added, removed, or modified)

2015-08-04 06:08:01:784 - info: [IOS_SYSLOG_ROW ] Aug  4 16:07:55 Chandrakanth-Achyutas-iPad installd[36] <Error>: 0x443000 -[MIInstaller performInstallationWithError:]: Verification stage failed

2015-08-04 06:08:01:816 - info: [IOS_SYSLOG_ROW ] Aug  4 16:07:55 Chandrakanth-Achyutas-iPad mobile_installation_proxy[196] <Error>: 0x361000 __MobileInstallationInstallForLaunchServices_block_invoke240: Returned error Error Domain=MIInstallerErrorDomain Code=13 "Failed to verify code signature of <MIExecutableBundle : path = /private/var/mobile/Library/Caches/com.apple.mobile.installd.staging/temp.qmv567/extracted/Payload/Banking.app identifier = com.macquarie.pb.mbanking.Banking type = User App> : 0xe8008017 (Signed resources have been added, removed, or modified)" UserInfo=0x14d87200 {LibMISErrorNumber=-402620393, LegacyErrorString=ApplicationVerificationFailed, FunctionName=-[MICodeSigningVerifier performValidationWithError:], NSLocalizedDescription=Failed to verify code signature of <MIExecutableBundle : path = /private/var/mobile/Library/Caches/com.apple.mobile.installd.staging/temp.qmv567/extracted/Payload/Banking.app identifier = com.macquarie.pb.mbanking.Banking type = User App> : 0xe8008017 (Signed resources have been added, removed, or modified), SourceFileLine=188}
2015-08-04 06:08:01:822 - info: [IOS_SYSLOG_ROW ] Aug  4 16:07:55 Chandrakanth-Achyutas-iPad mobile_installation_proxy[196] <Warning>: ERROR: MobileInstallationInstallForLaunchServices returned nil
2015-08-04 06:08:01:823 - info: [IOS_SYSLOG_ROW ] Aug  4 16:07:55 Chandrakanth-Achyutas-iPad mobile_installation_proxy[196] <Error>: 0x2dd000 handle_install: Installation failed: Error Domain=LaunchServicesError Code=0 "The operation couldn’t be completed. (LaunchServicesError error 0.)" UserInfo=0x14d87280 {Error=ApplicationVerificationFailed, ErrorDetail=-402620393, ErrorDescription=Failed to verify code signature of <MIExecutableBundle : path = /private/var/mobile/Library/Caches/com.apple.mobile.installd.staging/temp.qmv567/extracted/Payload/Banking.app identifier = com.macquarie.pb.mbanking.Banking type = User App> : 0xe8008017 (Signed resources have been added, removed, or modified)}

2015-08-04 06:08:01:861 - info: [debug] Starting command proxy.
2015-08-04 06:08:01:864 - info: [debug] Instruments socket server started at /tmp/instruments_sock
2015-08-04 06:08:01:864 - info: [debug] Starting instruments

2015-08-04 06:08:01:935 - info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
2015-08-04 06:08:01:936 - info: Launching instruments

2015-08-04 06:08:01:939 - info: [debug] Attempting to run app on real device with UDID 2b6c6c99a9f861eed7b1237b26207c71a472ab2c
2015-08-04 06:08:01:941 - info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w 2b6c6c99a9f861eed7b1237b26207c71a472ab2c com.macquarie.pb.mbanking.Banking -e UIASCRIPT "/Users/pbtester2/Library/Application Support/appium/bootstrap/bootstrap-6745615c424bb0c0.js" -e UIARESULTSPATH /tmp/appium-instruments
2015-08-04 06:08:01:941 - info: [debug] And extra without-delay env: {}
2015-08-04 06:08:01:941 - info: [debug] And launch timeouts (in ms): {"global":90000}

2015-08-04 06:08:02:549 - info: --> GET /wd/hub/status {}

2015-08-04 06:08:02:550 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"},"isShuttingDown":false},"sessionId":"52884aa5-0743-46c6-97b1-6be0d52a81c4"}

2015-08-04 06:08:02:553 - info: <-- GET /wd/hub/status 200 3.402 ms - 178 {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"},"isShuttingDown":false},"sessionId":"52884aa5-0743-46c6-97b1-6be0d52a81c4"}

2015-08-04 06:08:02:924 - info: --> GET /wd/hub/status {}

2015-08-04 06:08:02:925 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"},"isShuttingDown":false},"sessionId":"52884aa5-0743-46c6-97b1-6be0d52a81c4"}
2015-08-04 06:08:02:926 - info: <-- GET /wd/hub/status 200 1.762 ms - 178 {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"},"isShuttingDown":false},"sessionId":"52884aa5-0743-46c6-97b1-6be0d52a81c4"}

2015-08-04 06:08:03:669 - info: [debug] [INST STDERR] Instruments Usage Error : Specified target process is invalid: com.macquarie.pb.mbanking.Banking

2015-08-04 06:08:03:670 - info: [debug] [INST STDERR] instruments, version 6.4 (57082)
usage: instruments [-t template] [-D document] [-l timeLimit] [-i #] [-w device] [[-p pid] | [application [-e variable value] [argument ...]]]

2015-08-04 06:08:03:685 - info: [debug] [INSTSERVER] Instruments exited with code 255
2015-08-04 06:08:03:686 - info: [debug] Killall instruments
2015-08-04 06:08:03:688 - info: [debug] Instruments crashed on startup
2015-08-04 06:08:03:689 - info: [debug] Attempting to retry launching instruments, this is retry #1
2015-08-04 06:08:03:689 - info: [debug] Killall iOS Simulator
2015-08-04 06:08:03:691 - info: [IOS_SYSLOG_ROW ] Aug  4 16:07:57 Chandrakanth-Achyutas-iPad DTMobileIS[360] <Warning>: Could not create service named com.apple.instruments.server.services.launchdaemon
2015-08-04 06:08:03:691 - info: [IOS_SYSLOG_ROW ] Aug  4 16:07:57 Chandrakanth-Achyutas-iPad DTMobileIS[360] <Warning>: Could not create service named com.apple.instruments.server.services.processcontrol.posixspawn
2015-08-04 06:08:03:694 - info: [IOS_SYSLOG_ROW ] Aug  4 16:07:57 Chandrakanth-Achyutas-iPad notification_proxy[190] <Error>: 0x3a5000 -[MNPLockdownConnection receiveMessage]: lockdown_receive_message error!
2015-08-04 06:08:03:717 - info: [IOS_SYSLOG_ROW ] Aug  4 16:07:57 Chandrakanth-Achyutas-iPad notification_proxy[190] <Error>: 0x3a5000 -[MNPLockdownConnection receiveMessage]: lockdown_receive_message error!

2015-08-04 06:08:08:691 - info: Launching instruments

2015-08-04 06:08:08:692 - info: [debug] Attempting to run app on real device with UDID 2b6c6c99a9f861eed7b1237b26207c71a472ab2c

2015-08-04 06:08:08:694 - info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w 2b6c6c99a9f861eed7b1237b26207c71a472ab2c com.macquarie.pb.mbanking.Banking -e UIASCRIPT "/Users/pbtester2/Library/Application Support/appium/bootstrap/bootstrap-6745615c424bb0c0.js" -e UIARESULTSPATH /tmp/appium-instruments
2015-08-04 06:08:08:694 - info: [debug] And extra without-delay env: {}
2015-08-04 06:08:08:694 - info: [debug] And launch timeouts (in ms): {"global":90000}

2015-08-04 06:08:09:775 - info: [debug] [INST STDERR] Instruments Usage Error : Specified target process is invalid: com.macquarie.pb.mbanking.Banking
instruments, version 6.4 (57082)
usage: instruments [-t template] [-D document] [-l timeLimit] [-i #] [-w device] [[-p pid] | [application [-e variable value] [argument ...]]]

2015-08-04 06:08:09:789 - info: [debug] [INSTSERVER] Instruments exited with code 255

2015-08-04 06:08:09:790 - info: [debug] Killall instruments
2015-08-04 06:08:09:793 - info: [debug] Instruments crashed on startup
2015-08-04 06:08:09:794 - info: [debug] We exceeded the number of retries allowed for instruments to successfully start; failing launch
2015-08-04 06:08:09:794 - info: [debug] Stopping iOS log capture
2015-08-04 06:08:09:795 - info: [debug] Running ios sim reset flow
2015-08-04 06:08:09:796 - info: [debug] Killing the simulator process
2015-08-04 06:08:09:797 - info: [debug] Killing any other simulator daemons
2015-08-04 06:08:09:801 - info: [debug] Killall iOS Simulator
2015-08-04 06:08:09:806 - info: [IOS_SYSLOG_ROW ] Aug  4 16:08:03 Chandrakanth-Achyutas-iPad DTMobileIS[360] <Warning>: Could not create service named com.apple.instruments.server.services.processcontrol.posixspawn

2015-08-04 06:08:09:870 - error: Failed to start an Appium session, err was: Error: Instruments crashed on startup

2015-08-04 06:08:09:869 - info: [debug] On a real device; cannot clean device state
2015-08-04 06:08:09:869 - info: [debug] Cleaning up appium session
2015-08-04 06:08:09:872 - info: [debug] Error: Instruments crashed on startup
    at [object Object].Instruments.onInstrumentsExit (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-instruments/lib/instruments.js:440:31)
    at [object Object].<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-instruments/lib/instruments.js:353:12)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
2015-08-04 06:08:09:872 - info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Instruments crashed on startup)","origValue":"Instruments crashed on startup"},"sessionId":null}
2015-08-04 06:08:09:874 - info: <-- POST /wd/hub/session 500 17570.508 ms - 182

**Comment by SnigdhaSuchismitaDash** [comment]
Instrument crashed error will be removed. If we open code before running
test.

**Comment by Jonahss** [comment]
@sebv reopened

**Comment by SrinivasanTarget** [comment]
Closing this because of inactivity. @triager please close
