### ISSUE TITLE
error: Failed getting devices

### ISSUE THREAD

**Issue by krish300** [appium/appium#4791]
2015-03-26 14:25:07:606 - info: Welcome to Appium v1.3.5 (REV a124a15677e26b33db16e81c4b3b34d9c6b8cac9)
2015-03-26 14:25:07:611 - info: Appium REST http interface listener started on 0.0.0.0:4726
2015-03-26 14:25:07:712 - info: [debug] Non-default server args: {"app":"/Users/ksurapaneni/Desktop/current app/FactSet.app","port":4726,"callbackPort":4726,"log":"/Users/ksurapaneni/appium_log/appium.log","deviceName":"iPad 2 (77FAAE2D-4F93-4D4D-BE4C-9D58255EE29F)","platformName":"iOS","platformVersion":"8.1","showIOSLog":true,"tmpDir":"/Users/ksurapaneni/tmp"}
2015-03-26 14:25:07:712 - info: Console LogLevel: debug
2015-03-26 14:25:07:713 - info: File LogLevel: debug
2015-03-26 14:25:08:631 - info: --> GET /wd/hub/status {}
2015-03-26 14:25:08:642 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.5","revision":"a124a15677e26b33db16e81c4b3b34d9c6b8cac9"}}}
2015-03-26 14:25:08:653 - info: <-- GET /wd/hub/status 200 22.049 ms - 104 {"status":0,"value":{"build":{"version":"1.3.5","revision":"a124a15677e26b33db16e81c4b3b34d9c6b8cac9"}}}
2015-03-26 14:25:19:751 - info: --> GET /wd/hub/status {}
2015-03-26 14:25:19:753 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.5","revision":"a124a15677e26b33db16e81c4b3b34d9c6b8cac9"}}}
2015-03-26 14:25:19:757 - info: <-- GET /wd/hub/status 200 5.609 ms - 104 {"status":0,"value":{"build":{"version":"1.3.5","revision":"a124a15677e26b33db16e81c4b3b34d9c6b8cac9"}}}
2015-03-26 14:25:53:553 - info: --> GET /wd/hub/status {}
2015-03-26 14:25:53:553 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.5","revision":"a124a15677e26b33db16e81c4b3b34d9c6b8cac9"}}}
2015-03-26 14:25:53:556 - info: <-- GET /wd/hub/status 200 3.022 ms - 104 {"status":0,"value":{"build":{"version":"1.3.5","revision":"a124a15677e26b33db16e81c4b3b34d9c6b8cac9"}}}
2015-03-26 14:25:53:559 - info: --> GET /wd/hub/sessions {}
2015-03-26 14:25:53:560 - info: [debug] Responding to client with success: {"status":0,"value":[]}
2015-03-26 14:25:53:561 - info: <-- GET /wd/hub/sessions 200 1.885 ms - 23 {"status":0,"value":[]}
2015-03-26 14:25:53:591 - info: --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"iOS","platformVersion":"8.1","newCommandTimeout":"999999","automationName":"Appium","deviceName":"iPad 2 (77FAAE2D-4F93-4D4D-BE4C-9D58255EE29F)"}}
2015-03-26 14:25:53:593 - info: Client User-Agent string: Appium (unknown version) CFNetwork/720.2.4 Darwin/14.1.0 (x86_64)
2015-03-26 14:25:53:599 - info: [debug] Using local app from command line: /Users/ksurapaneni/Desktop/current app/FactSet.app
2015-03-26 14:25:53:602 - info: [debug] Creating new appium session cbca2298-4fb6-4e6c-8087-4d1280de881f
2015-03-26 14:25:53:606 - info: [debug] Removing any remaining instruments sockets
2015-03-26 14:25:53:607 - info: [debug] Cleaned up instruments socket /Users/ksurapaneni/tmp/instruments_sock
2015-03-26 14:25:53:608 - info: [debug] Setting Xcode folder
2015-03-26 14:25:53:722 - info: [debug] Setting Xcode version
2015-03-26 14:25:56:792 - info: [debug] Setting iOS SDK Version
2015-03-26 14:25:59:963 - info: [debug] Getting sdk version from xcrun with a timeout
2015-03-26 14:25:59:986 - info: [debug] iOS SDK Version set to 8.2
2015-03-26 14:25:59:987 - info: [debug] Checking whether instruments supports our device string
2015-03-26 14:25:59:988 - info: [debug] Getting list of devices instruments supports
2015-03-26 14:26:00:049 - info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
2015-03-26 14:26:12:218 - error: Failed getting devices. Err: Error: Command failed: /bin/sh -c '/Applications/Xcode.app/Contents/Developer/usr/bin/instruments' -s devices
Failed to find matching kernel in /System/Library/Kernels
. Stdout: . Stderr: Failed to find matching kernel in /System/Library/Kernels
.
2015-03-26 14:26:12:219 - info: [debug] Getting list of devices instruments supports
2015-03-26 14:26:12:245 - info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
2015-03-26 14:26:20:789 - info: --> GET /wd/hub/status {}
2015-03-26 14:26:20:790 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.5","revision":"a124a15677e26b33db16e81c4b3b34d9c6b8cac9"},"isShuttingDown":false},"sessionId":"cbca2298-4fb6-4e6c-8087-4d1280de881f"}
2015-03-26 14:26:20:792 - info: <-- GET /wd/hub/status 200 3.433 ms - 178 {"status":0,"value":{"build":{"version":"1.3.5","revision":"a124a15677e26b33db16e81c4b3b34d9c6b8cac9"},"isShuttingDown":false},"sessionId":"cbca2298-4fb6-4e6c-8087-4d1280de881f"}
2015-03-26 14:26:23:358 - info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.2","iOSSDKVersion":"8.2","deviceName":"iPad 2 (77FAAE2D-4F93-4D4D-BE4C-9D58255EE29F)","platformVersion":"8.1"}
2015-03-26 14:26:23:359 - info: [debug] fixDevice is on
2015-03-26 14:26:23:361 - info: [debug] Final device string is: 'iPad 2 (77FAAE2D-4F93-4D4D-BE4C-9D58255EE29F) (8.1 Simulator)'
2015-03-26 14:26:23:362 - error: Could not find a device to launch. You requested 'iPad 2 (77FAAE2D-4F93-4D4D-BE4C-9D58255EE29F) (8.1 Simulator)', but the available devices were: ["iPad 2 (7.1 Simulator) [08EF17DF-3EFE-4D6C-893E-D08F4D495395]","iPad 2 (8.1 Simulator) [3C1EB8C2-BC60-4EB1-9371-6C77367D4D3F]","iPad 2 (8.2 Simulator) [77FAAE2D-4F93-4D4D-BE4C-9D58255EE29F]","iPad Air (8.2 Simulator) [76C96853-893A-4C98-9226-C67F1E97484C]","iPad Retina (8.2 Simulator) [EA896810-06E5-4FA5-B0FF-CE518D116371]","iPhone 4s (8.2 Simulator) [493CFA6E-5F55-4572-A31F-8E5AA2FF9B70]","iPhone 5 (8.2 Simulator) [9061E3B8-3584-4546-8CC5-27F72A85EF86]","iPhone 5s (8.2 Simulator) [9EF0537F-7889-4EAC-8E01-F142CC802AE6]","iPhone 6 (8.2 Simulator) [920BC52A-7327-4316-B07D-7529A608E9C2]","iPhone 6 Plus (8.2 Simulator) [57685A2D-77AE-4484-A48E-F35CFAA774EF]"]
2015-03-26 14:26:23:365 - info: [debug] Cleaning up appium session
2015-03-26 14:26:23:366 - error: Failed to start an Appium session, err was: Error: Could not find a device to launch. You requested 'iPad 2 (77FAAE2D-4F93-4D4D-BE4C-9D58255EE29F) (8.1 Simulator)', but the available devices were: ["iPad 2 (7.1 Simulator) [08EF17DF-3EFE-4D6C-893E-D08F4D495395]","iPad 2 (8.1 Simulator) [3C1EB8C2-BC60-4EB1-9371-6C77367D4D3F]","iPad 2 (8.2 Simulator) [77FAAE2D-4F93-4D4D-BE4C-9D58255EE29F]","iPad Air (8.2 Simulator) [76C96853-893A-4C98-9226-C67F1E97484C]","iPad Retina (8.2 Simulator) [EA896810-06E5-4FA5-B0FF-CE518D116371]","iPhone 4s (8.2 Simulator) [493CFA6E-5F55-4572-A31F-8E5AA2FF9B70]","iPhone 5 (8.2 Simulator) [9061E3B8-3584-4546-8CC5-27F72A85EF86]","iPhone 5s (8.2 Simulator) [9EF0537F-7889-4EAC-8E01-F142CC802AE6]","iPhone 6 (8.2 Simulator) [920BC52A-7327-4316-B07D-7529A608E9C2]","iPhone 6 Plus (8.2 Simulator) [57685A2D-77AE-4484-A48E-F35CFAA774EF]"]
2015-03-26 14:26:23:369 - info: [debug] Error: Could not find a device to launch. You requested 'iPad 2 (77FAAE2D-4F93-4D4D-BE4C-9D58255EE29F) (8.1 Simulator)', but the available devices were: ["iPad 2 (7.1 Simulator) [08EF17DF-3EFE-4D6C-893E-D08F4D495395]","iPad 2 (8.1 Simulator) [3C1EB8C2-BC60-4EB1-9371-6C77367D4D3F]","iPad 2 (8.2 Simulator) [77FAAE2D-4F93-4D4D-BE4C-9D58255EE29F]","iPad Air (8.2 Simulator) [76C96853-893A-4C98-9226-C67F1E97484C]","iPad Retina (8.2 Simulator) [EA896810-06E5-4FA5-B0FF-CE518D116371]","iPhone 4s (8.2 Simulator) [493CFA6E-5F55-4572-A31F-8E5AA2FF9B70]","iPhone 5 (8.2 Simulator) [9061E3B8-3584-4546-8CC5-27F72A85EF86]","iPhone 5s (8.2 Simulator) [9EF0537F-7889-4EAC-8E01-F142CC802AE6]","iPhone 6 (8.2 Simulator) [920BC52A-7327-4316-B07D-7529A608E9C2]","iPhone 6 Plus (8.2 Simulator) [57685A2D-77AE-4484-A48E-F35CFAA774EF]"]
    at noDevicesError (/Users/ksurapaneni/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js:1106:10)
    at null.<anonymous> (/Users/ksurapaneni/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js:1112:16)
    at /Users/ksurapaneni/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:525:46
    at /Users/ksurapaneni/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:254:17
    at /Users/ksurapaneni/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:151:21
    at /Users/ksurapaneni/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:251:21
    at /Users/ksurapaneni/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:615:34
    at /Users/ksurapaneni/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:516:25
    at /Users/ksurapaneni/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-instruments/lib/instruments.js:111:7
    at ChildProcess.exithandler (child_process.js:735:7)
2015-03-26 14:26:23:370 - info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Could not find a device to launch. You requested 'iPad 2 (77FAAE2D-4F93-4D4D-BE4C-9D58255EE29F) (8.1 Simulator)', but the available devices were: [\"iPad 2 (7.1 Simulator) [08EF17DF-3EFE-4D6C-893E-D08F4D495395]\",\"iPad 2 (8.1 Simulator) [3C1EB8C2-BC60-4EB1-9371-6C77367D4D3F]\",\"iPad 2 (8.2 Simulator) [77FAAE2D-4F93-4D4D-BE4C-9D58255EE29F]\",\"iPad Air (8.2 Simulator) [76C96853-893A-4C98-9226-C67F1E97484C]\",\"iPad Retina (8.2 Simulator) [EA896810-06E5-4FA5-B0FF-CE518D116371]\",\"iPhone 4s (8.2 Simulator) [493CFA6E-5F55-4572-A31F-8E5AA2FF9B70]\",\"iPhone 5 (8.2 Simulator) [9061E3B8-3584-4546-8CC5-27F72A85EF86]\",\"iPhone 5s (8.2 Simulator) [9EF0537F-7889-4EAC-8E01-F142CC802AE6]\",\"iPhone 6 (8.2 Simulator) [920BC52A-7327-4316-B07D-7529A608E9C2]\",\"iPhone 6 Plus (8.2 Simulator) [57685A2D-77AE-4484-A48E-F35CFAA774EF]\"])","origValue":"Could not find a device to launch. You requested 'iPad 2 (77FAAE2D-4F93-4D4D-BE4C-9D58255EE29F) (8.1 Simulator)', but the available devices were: [\"iPad 2 (7.1 Simulator) [08EF17DF-3EFE-4D6C-893E-D08F4D495395]\",\"iPad 2 (8.1 Simulator) [3C1EB8C2-BC60-4EB1-9371-6C77367D4D3F]\",\"iPad 2 (8.2 Simulator) [77FAAE2D-4F93-4D4D-BE4C-9D58255EE29F]\",\"iPad Air (8.2 Simulator) [76C96853-893A-4C98-9226-C67F1E97484C]\",\"iPad Retina (8.2 Simulator) [EA896810-06E5-4FA5-B0FF-CE518D116371]\",\"iPhone 4s (8.2 Simulator) [493CFA6E-5F55-4572-A31F-8E5AA2FF9B70]\",\"iPhone 5 (8.2 Simulator) [9061E3B8-3584-4546-8CC5-27F72A85EF86]\",\"iPhone 5s (8.2 Simulator) [9EF0537F-7889-4EAC-8E01-F142CC802AE6]\",\"iPhone 6 (8.2 Simulator) [920BC52A-7327-4316-B07D-7529A608E9C2]\",\"iPhone 6 Plus (8.2 Simulator) [57685A2D-77AE-4484-A48E-F35CFAA774EF]\"]"},"sessionId":null}
2015-03-26 14:26:23:373 - info: <-- POST /wd/hub/session 500 29782.230 ms - 1784

**Comment by 0x1mason** [comment]
Can you update to the latest version and see if the problem persists?

**Comment by krish-300** [comment]
Resolved after update and system restart.
can be resolved.
