### ISSUE TITLE
[iOS 8] Cannot move slider to any location using sendKeys("0.x")

### ISSUE THREAD

**Issue by ijazsarwar** [appium/appium#4804]
It works fine on iOS 7.1 device. But on iOS 8.2 device it always move the slider to beginning no matter what value I send in sendKeys.

Appium code:
driver().findElementByAccessibilityId("scrubber").sendKeys("1");

Appium logs:
2015-03-27 11:54:31:355 - info: [debug] Socket data received (27 bytes)
2015-03-27 11:54:31:356 - info: [debug] Socket data being routed.
2015-03-27 11:54:31:356 - info: [debug] Got result from instruments: {"status":0,"value":true}
2015-03-27 11:54:31:356 - info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"a66ef246-cbea-4581-93d7-bc39293b8798"}
2015-03-27 11:54:31:356 - info: <-- GET /wd/hub/session/a66ef246-cbea-4581-93d7-bc39293b8798/element/0/displayed 200 947.898 ms - 76 {"status":0,"value":true,"sessionId":"a66ef246-cbea-4581-93d7-bc39293b8798"}
2015-03-27 11:54:31:359 - info: --> POST /wd/hub/session/a66ef246-cbea-4581-93d7-bc39293b8798/elements {"using":"id","value":"scrubber"}
2015-03-27 11:54:31:360 - info: [debug] Waiting up to 10000ms for condition
2015-03-27 11:54:31:360 - info: [debug] Pushing command to appium work queue: "au.getElementsByAccessibilityId('scrubber')"
2015-03-27 11:54:31:360 - info: [debug] Sending command to instruments: au.getElementsByAccessibilityId('scrubber')
2015-03-27 11:54:32:383 - info: [debug] [INST] 2015-03-27 18:54:33 +0000 Debug: Got new command 29 from instruments: au.getElementsByAccessibilityId('scrubber')
2015-03-27 11:54:32:387 - info: [debug] [INST] 2015-03-27 18:54:33 +0000 Debug: evaluating au.getElementsByAccessibilityId('scrubber')
2015-03-27 11:54:32:667 - info: [debug] [INST] 2015-03-27 18:54:33 +0000 Debug: evaluation finished
2015-03-27 11:54:32:671 - info: [debug] [INST] 2015-03-27 18:54:33 +0000 Debug: Lookup returned [object UIASlider] with the name "scrubber" (id: 1).
2015-03-27 11:54:32:675 - info: [debug] [INST] 2015-03-27 18:54:33 +0000 Debug: responding with:
2015-03-27 11:54:32:678 - info: [debug] [INST] 2015-03-27 18:54:33 +0000 Debug: Running system command #30: /usr/local/Cellar/node/0.12.0/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":[{"ELEMENT":"1"}]}...
2015-03-27 11:54:32:732 - info: [debug] Socket data received (40 bytes)
2015-03-27 11:54:32:733 - info: [debug] Socket data being routed.
2015-03-27 11:54:32:733 - info: [debug] Got result from instruments: {"status":0,"value":[{"ELEMENT":"1"}]}
2015-03-27 11:54:32:733 - info: [debug] Responding to client with success: {"status":0,"value":[{"ELEMENT":"1"}],"sessionId":"a66ef246-cbea-4581-93d7-bc39293b8798"}
2015-03-27 11:54:32:734 - info: <-- POST /wd/hub/session/a66ef246-cbea-4581-93d7-bc39293b8798/elements 200 1374.671 ms - 89 {"status":0,"value":[{"ELEMENT":"1"}],"sessionId":"a66ef246-cbea-4581-93d7-bc39293b8798"}
2015-03-27 11:54:32:737 - info: --> GET /wd/hub/session/a66ef246-cbea-4581-93d7-bc39293b8798/element/1/displayed {}
2015-03-27 11:54:32:737 - info: [debug] Pushing command to appium work queue: "au.getElement('1').isDisplayed()"
2015-03-27 11:54:32:737 - info: [debug] Sending command to instruments: au.getElement('1').isDisplayed()
2015-03-27 11:54:33:755 - info: [debug] [INST] 2015-03-27 18:54:34 +0000 Debug: Got new command 30 from instruments: au.getElement('1').isDisplayed()
2015-03-27 11:54:33:758 - info: [debug] [INST] 2015-03-27 18:54:34 +0000 Debug: evaluating au.getElement('1').isDisplayed()
2015-03-27 11:54:33:761 - info: [debug] [INST] 2015-03-27 18:54:34 +0000 Debug: evaluation finished
2015-03-27 11:54:33:765 - info: [debug] [INST] 2015-03-27 18:54:34 +0000 Debug: responding with:
2015-03-27 11:54:33:768 - info: [debug] [INST] 2015-03-27 18:54:34 +0000 Debug: Running system command #31: /usr/local/Cellar/node/0.12.0/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":true}...
2015-03-27 11:54:33:815 - info: [debug] Socket data received (27 bytes)
2015-03-27 11:54:33:815 - info: [debug] Socket data being routed.
2015-03-27 11:54:33:815 - info: [debug] Got result from instruments: {"status":0,"value":true}
2015-03-27 11:54:33:815 - info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"a66ef246-cbea-4581-93d7-bc39293b8798"}
2015-03-27 11:54:33:816 - info: <-- GET /wd/hub/session/a66ef246-cbea-4581-93d7-bc39293b8798/element/1/displayed 200 1079.246 ms - 76 {"status":0,"value":true,"sessionId":"a66ef246-cbea-4581-93d7-bc39293b8798"}
2015-03-27 11:54:33:819 - info: --> POST /wd/hub/session/a66ef246-cbea-4581-93d7-bc39293b8798/element {"using":"accessibility id","value":"scrubber"}
2015-03-27 11:54:33:819 - info: [debug] Waiting up to 10000ms for condition
2015-03-27 11:54:33:820 - info: [debug] Pushing command to appium work queue: "au.getElementByAccessibilityId('scrubber')"
2015-03-27 11:54:33:820 - info: [debug] Sending command to instruments: au.getElementByAccessibilityId('scrubber')
2015-03-27 11:54:34:706 - info: [debug] [INST] 2015-03-27 18:54:35 +0000 Debug: Got new command 31 from instruments: au.getElementByAccessibilityId('scrubber')
2015-03-27 11:54:34:711 - info: [debug] [INST] 2015-03-27 18:54:35 +0000 Debug: evaluating au.getElementByAccessibilityId('scrubber')
2015-03-27 11:54:34:855 - info: [debug] [INST] 2015-03-27 18:54:35 +0000 Debug: evaluation finished
2015-03-27 11:54:34:860 - info: [debug] [INST] 2015-03-27 18:54:35 +0000 Debug: Lookup returned [object UIASlider] with the name "scrubber" (id: 2).
2015-03-27 11:54:34:864 - info: [debug] [INST] 2015-03-27 18:54:35 +0000 Debug: responding with:
2015-03-27 11:54:34:868 - info: [debug] [INST] 2015-03-27 18:54:35 +0000 Debug: Running system command #32: /usr/local/Cellar/node/0.12.0/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":{"ELEMENT":"2"}}...
2015-03-27 11:54:34:916 - info: [debug] Socket data received (38 bytes)
2015-03-27 11:54:34:916 - info: [debug] Socket data being routed.
2015-03-27 11:54:34:916 - info: [debug] Got result from instruments: {"status":0,"value":{"ELEMENT":"2"}}
2015-03-27 11:54:34:916 - info: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":"2"},"sessionId":"a66ef246-cbea-4581-93d7-bc39293b8798"}
2015-03-27 11:54:34:917 - info: <-- POST /wd/hub/session/a66ef246-cbea-4581-93d7-bc39293b8798/element 200 1097.984 ms - 87 {"status":0,"value":{"ELEMENT":"2"},"sessionId":"a66ef246-cbea-4581-93d7-bc39293b8798"}
2015-03-27 11:54:34:920 - info: --> POST /wd/hub/session/a66ef246-cbea-4581-93d7-bc39293b8798/element/2/value {"id":"2","value":["1"]}
2015-03-27 11:54:34:920 - info: [debug] Pushing command to appium work queue: "au.getElement('2').setValueByType('1')"
2015-03-27 11:54:34:920 - info: [debug] Sending command to instruments: au.getElement('2').setValueByType('1')
2015-03-27 11:54:35:946 - info: [debug] [INST] 2015-03-27 18:54:36 +0000 Debug: Got new command 32 from instruments: au.getElement('2').setValueByType('1')
2015-03-27 11:54:35:951 - info: [debug] [INST] 2015-03-27 18:54:36 +0000 Debug: evaluating au.getElement('2').setValueByType('1')
2015-03-27 11:54:35:954 - info: [debug] [INST] 2015-03-27 18:54:36 +0000 Debug: UIASlider.dragToValue("1")
2015-03-27 11:54:37:308 - info: [debug] [INST] 2015-03-27 18:54:38 +0000 Debug: evaluation finished
2015-03-27 11:54:37:313 - info: [debug] [INST] 2015-03-27 18:54:38 +0000 Debug: responding with:
2015-03-27 11:54:37:316 - info: [debug] [INST] 2015-03-27 18:54:38 +0000 Debug: Running system command #33: /usr/local/Cellar/node/0.12.0/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":""}...

**Comment by imurchie** [comment]
What version of Appium are you using? This seems to work for me.

7.1: https://saucelabs.com/tests/649c4fc4a65349549df57b7855ae8011
8.2: https://saucelabs.com/tests/c8d0b18b89544822b97456ada72cc7a5

**Comment by ijazsarwar** [comment]
@imurchie thanks for looking into it.

I tried with Appium Version 1.3.7 (Ophiuchus) just now and can still see the issue. Also I tried running it from the code and same issue.

My xcode is Version 6.2 (6C131e) which is running on OS X Yosemite version 10.10.2.

**Comment by ijazsarwar** [comment]
@imurchie which orientation you ran your test? We run test on landscape orientation.

**Comment by imurchie** [comment]
Works with landscape, too. See [here](https://saucelabs.com/tests/3ac8b5c43971464199616d4cbcb88926). 

Can you provide the commands you are using?

**Comment by imurchie** [comment]
Also, what happens when you retrieve the value after having set it? What is returned?

**Comment by ijazsarwar** [comment]
@imurchie before scrubbing I get the "value" attribute and it gives me "11%" (which sounds correct by visually looking at it). Once I do sendKeys("1") it moves the slider to beginning and now "value" attribute is returning "1%".

So "value" attribute is giving the correct results. But we still can't move the slider.

**Comment by ijazsarwar** [comment]
@imurchie also did you tried to device or simulator? not sure if that would make a diff. But we only run tests on real device (since our app is not supported by simulator).

**Comment by imurchie** [comment]
What happens when you do `sendkeys("100")`?

**Comment by ijazsarwar** [comment]
@imurchie yeah I tried that it gave me some error. I just ran it again and I get below error (with sendKeys("100")):
2015-04-03 11:32:41,470 INFO  [pool-8-thread-1] (SendMessage.java:85) - Successfully sent message: {"step_events":[{"index":8,"guid":"com.netflix.nts.iOS.appium.stanley.ui.steps.ScrubToPosition","type":"status_update","marker_id":"30361786","nano_time":25344274315296,"status":{"result":"RUNNING","finished":false,"duration":"","index":8,"started":"2015-04-03T18:32:41.455Z"},"time_stamp":"2015-04-03T11:32:41.456"}],"marker_id":"30361786"} to marathon, sending websocket message took: 0 milliseconds.
org.openqa.selenium.WebDriverException: An error occurred while executing user supplied JavaScript. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1.87 seconds
Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
System info: host: 'lgml-isarwar', ip: '10.2.177.194', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.2', java.version: '1.8.0_20'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{app=com.netflix.Netflix, networkConnectionEnabled=false, warnings={}, databaseEnabled=false, processArguments=-kFactoryReset 1 -site https://tenfootui.netflix.com/tablet/trunk/prod/latest/release/, deviceName=iPad, platform=MAC, desired={app=com.netflix.Netflix, ipa=, udid=31202203e1f96545720638b0e2d1096855c732a9, processArguments=-kFactoryReset 1 -site https://tenfootui.netflix.com/tablet/trunk/prod/latest/release/, platformName=iOS, deviceName=iPad}, webStorageEnabled=false, locationContextEnabled=false, browserName=iOS, takesScreenshot=true, javascriptEnabled=true, ipa=, udid=31202203e1f96545720638b0e2d1096855c732a9, platformName=iOS}]
Session ID: 63792214-7c83-49e5-9f48-b1a6b21af6db
2015-04-03 11:33:01,247 INFO  [TestRunner-0] (TestStepRunner.java:150) - Got test step state (from future): PASSED for step -Scrub to position
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:180)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:268)
	at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:89)
	at com.netflix.nts.iOS.appium.stanley.ui.steps.ScrubToPosition.execute(ScrubToPosition.java:27)
	at com.netflix.nts.harness.testcase.TestStep.runStep(TestStep.java:214)
	at com.netflix.nts.harness.core.TestStepThread.call(TestStepThread.java:44)
	at com.netflix.nts.harness.core.TestStepThread.call(TestStepThread.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by imurchie** [comment]
What error occurred in the server logs?

**Comment by imurchie** [comment]
Alright. On a real device it is broken. I'll add it to the bug list.

In the meantime, can you try `slider.setValue('100%')`?

**Comment by Jitu1888** [comment]
slider.setValue('100%')? is also
 not working

**Comment by Jitu1888** [comment]
I am using
IOSElement jitu=(IOSElement) driver.findElementByClassName("UIASlider");
			((IOSElement)jitu).setValue("1%");
This code to move the header of the slider

**Comment by SrinivasanTarget** [comment]
Closing this because of inactivity. @triager please close

**Comment by Jitu1888** [comment]
Why you close this issue?
its an issue right

**Comment by suganeby** [comment]
@Jitu1888 
I am using appium 1.6.3. I have same issue, not able set value to the slider. Do you have any work around for sending value to the slider?

**Comment by mathewkuruvila** [comment]
Is this issue fixed? Below is my code and it is failing

                String xpath = "//UIASlider";
		IOSElement  element = (IOSElement)aDriver.findElement(By.xpath(xpath));
		element.setValue("100%");

I am just trying to set Settings > Display & Brightness to 100%

**Comment by mykola-mokhnach** [comment]
Slider values must be in range [0.0, 1.0] for XCTest driver

**Comment by mathewkuruvila** [comment]
I tried giving ".5". But that is also not working. 

A getText() from the webelement returns the value : 2%

**Comment by mathewkuruvila** [comment]
Can someone confirm this issue is still open or i am doing something wrong

**Comment by mykola-mokhnach** [comment]
@mathewkuruvila What is your code?

**Comment by mathewkuruvila** [comment]
In IOS, open Settings > Display & Brightness.

String xpath = "//UIASlider";
IOSElement  element = (IOSElement)aDriver.findElement(By.xpath(xpath));
element.setValue("100%");

where aDriver = IOSDriver
A getText() on the element "xpath", is retrieving the value 2%, which is the initial value.

**Comment by suganeby** [comment]
@mathewkuruvila,
Did you figure out, how to set value to the slider? 
I am using appium 1.6.5. I still see the issue in the real device.

**Comment by suganeby** [comment]
@SrinivasanTarget, @mykola-mokhnach 
Do we have open ticket for this issue? This ticket seems to be closed and the issue appears even in the latest build.

**Comment by vbutzke** [comment]
Facing this issue as well... Any updates?

**Comment by canrosinabutar** [comment]
I tried this and it works:
IOSElement elemenSlider=(IOSElement) driver.findElementByClassName("XCUITypeSlider");
((IOSElement) elemenSlider).setValue("0.5");

note : Set the value between [0.0 - 1.0]

**Comment by ivantay2003** [comment]
This is still not working on my side for slider on emulator

Using Appium v1.9.1. I am testing on the UICatalog which came with appium examples. 


driver.findElement(By.xpath("//XCUIElementTypeApplication[@name='UICatalog']/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeTable/XCUIElementTypeCell[3]/XCUIElementTypeSlider")).setValue("0.9");

**Comment by suganeby** [comment]
@ivantay2003,
What is the version of XCode ?
