### ISSUE TITLE
[iOS] Interacting with iOS Springboard fails

### ISSUE THREAD

**Issue by GindiKhangura** [appium/appium#4810]
I could not fit the description of the actual issue in the title. Though I am able to interact with the Springboard just fine, it won't work if the page (the Springboard pages where the app shortcuts are displayed) is anything other than the 1st (default).

For iOS, I access the Springboard using *driver.runAppInBackground(x)* since I couldn't find the equivalent of pressing the Home key on Android. I then call *driver.getPageSource()*, but the junit never completes. I have disabled all the timeouts, so I did not expect the server to auto-terminate. Note: to reproduce the issue, swipe the Springboard page to any page other than the 1st before executing the test. You can also leave the device in an unusable state by executing a test, hiding the app, then swiping the Springboard page to any other; executing any interactions on the Springboard from here will result in the same issue.

At this point, there are no error messages in either the node's log or the hub's log. I then kill the node server, which throws an error on the hub, as seen below:
```
10:26:48.325 ERROR - cannot forward the request 10.184.197.31:5252 failed to respond
org.apache.http.NoHttpResponseException: 10.184.197.31:5252 failed to respond
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:1
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:153)
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:254)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:115)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
        at org.openqa.grid.internal.TestSession.sendRequestToNode(TestSession.java:371)
        at org.openqa.grid.internal.TestSession.forward(TestSession.java:227)
        at org.openqa.grid.web.servlet.handler.RequestHandler.forwardRequest(RequestHandler.java:96)
        at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:129)
        at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:83)
        at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:67)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.seleniumhq.jetty7.servlet.ServletHolder.handle(ServletHolder.java:565)
        at org.seleniumhq.jetty7.servlet.ServletHandler.doHandle(ServletHandler.java:479)
        at org.seleniumhq.jetty7.server.session.SessionHandler.doHandle(SessionHandler.java:225)
        at org.seleniumhq.jetty7.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
        at org.seleniumhq.jetty7.servlet.ServletHandler.doScope(ServletHandler.java:406)
        at org.seleniumhq.jetty7.server.session.SessionHandler.doScope(SessionHandler.java:186)
        at org.seleniumhq.jetty7.server.handler.ContextHandler.doScope(ContextHandler.java:965)
        at org.seleniumhq.jetty7.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
        at org.seleniumhq.jetty7.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
        at org.seleniumhq.jetty7.server.Server.handle(Server.java:349)
        at org.seleniumhq.jetty7.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:452)
        at org.seleniumhq.jetty7.server.BlockingHttpConnection.handleRequest(BlockingHttpConnection.java:47)
        at org.seleniumhq.jetty7.server.AbstractHttpConnection.content(AbstractHttpConnection.java:894)
        at org.seleniumhq.jetty7.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:948)
        at org.seleniumhq.jetty7.http.HttpParser.parseNext(HttpParser.java:857)
        at org.seleniumhq.jetty7.http.HttpParser.parseAvailable(HttpParser.java:235)
        at org.seleniumhq.jetty7.server.BlockingHttpConnection.handle(BlockingHttpConnection.java:66)
        at org.seleniumhq.jetty7.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:254)
        at org.seleniumhq.jetty7.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599)
        at org.seleniumhq.jetty7.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534)
        at java.lang.Thread.run(Thread.java:744)
```
The error seems to state that there is a connection issue, but I can successfully run tests on the device using the hub just fine. It just seems that the case I mentioned does not work.

I have gotten Android to spy on elements regardless which dashboard page (not sure what the correct terminology is) it is on.

I have tested on an iPad Air (retina) on iOS 8.1 and also on a iPhone 5 on iOS 8.1.3. The issue is reproducable on both.

**Comment by GindiKhangura** [comment]
@jlipps Is there somebody who can help with this issue? I have not received a response for some time now.

**Comment by jlipps** [comment]
on iOS, interacting with the springboard is not supported. The backgroundApp functionality has been provided by Apple to background your app for a specific duration, then to bring your app back. They don't support automating other apps or the springboard during an automation session. Sorry!

**Comment by nkllkc** [comment]
Does this still holds? The fact that you can only automate your own app? 

[Kobiton](https://kobiton.com/real-device-testing) claims that they are using Appium as their core and the are able to run third party apps? 

Also, interaction with springboard in XCUITest is possible.

**Comment by jlipps** [comment]
This doesn't still hold. The XCUITest driver can automate 3rd party apps including the home screen.

**Comment by nkllkc** [comment]
Thank you Jonathan!

Do you know by any chance what was the turning point, when the automation of 3rd party apps was made available?

**Comment by jlipps** [comment]
@nkllkc the turning point was the introduction of the xcuitest driver, which I believe was over 4 years ago now.
