### ISSUE TITLE
Unhandled error: TypeError: Cannot read property 'isInstalled' of undefined ios.js:1473

### ISSUE THREAD

**Issue by nikolmarku1** [appium/appium#4819]
OS    :  OS X Yosemite
Appium : I installed latest commit :  commit 84e8458404

I was having issue with fruitstrap quit unexpectedly so tried the latest code ixes while trying to run test on iPad mini 1 and on safari browser

I am using selenium 2.45 and running test on the grid

- error: Unhandled error: TypeError: Cannot read property 'isInstalled' of undefined
    at IOS.isAppInstalled (/Users/qa/automation/apps/appium/newAppiumGit/appium/lib/devices/ios/ios.js:1473:20)

Am I missing some sort of flag been set?

Could you advice please?

Thanks
Niko

appium logs

2015-03-31 12:55:41:752 - info: [debug] Configuring Safari session
2015-03-31 12:55:41:753 - info: [debug] Using local .zip from desired caps: /Users/qa/automation/apps/appium/newAppiumGit/appium/build/SafariLauncher/SafariLauncher.zip
2015-03-31 12:55:41:754 - info: [debug] Copying local zip to tmp dir
2015-03-31 12:55:41:759 - info: [debug] /Users/qa/automation/apps/appium/newAppiumGit/appium/build/SafariLauncher/SafariLauncher.zip copied to /var/folders/xn/zxrl7n3x6vd33s2_mt6b696c0000gn/T/115231-887-3ys8yi/appium-app.zip
2015-03-31 12:55:41:767 - info: [debug] Unzipping /var/folders/xn/zxrl7n3x6vd33s2_mt6b696c0000gn/T/115231-887-3ys8yi/appium-app.zip
2015-03-31 12:55:41:768 - info: [debug] Testing zip archive: /var/folders/xn/zxrl7n3x6vd33s2_mt6b696c0000gn/T/115231-887-3ys8yi/appium-app.zip
2015-03-31 12:55:41:774 - info: [debug] Zip archive tested clean
2015-03-31 12:55:41:784 - info: [debug] Unzip successful
2015-03-31 12:55:41:785 - info: [debug] Using locally extracted app: /var/folders/xn/zxrl7n3x6vd33s2_mt6b696c0000gn/T/115231-887-3ys8yi/submodules/SafariLauncher/build/Release-iphoneos/SafariLauncher.app
2015-03-31 12:55:41:786 - info: [debug] Creating new appium session 4dc50e61-1ea1-457b-8416-b862afd89cfa
2015-03-31 12:55:41:789 - info: [debug] Removing any remaining instruments sockets
2015-03-31 12:55:41:790 - info: [debug] Cleaned up instruments socket /tmp/instruments_sock
2015-03-31 12:55:41:791 - info: [debug] Setting Xcode folder
2015-03-31 12:55:41:800 - info: [debug] Setting Xcode version
2015-03-31 12:55:41:814 - info: [debug] Setting iOS SDK Version
2015-03-31 12:55:41:828 - info: [debug] Getting sdk version from xcrun with a timeout
2015-03-31 12:55:41:834 - info: [debug] iOS SDK Version set to 8.2
2015-03-31 12:55:41:834 - info: [debug] Not checking whether simulator is available since we're on a real device
2015-03-31 12:55:41:835 - info: [debug] Detecting automation tracetemplate
2015-03-31 12:55:41:843 - info: [debug] Not auto-detecting udid, running on sim
2015-03-31 12:55:41:844 - info: [debug] Could not parse plist file (as binary) at /var/folders/xn/zxrl7n3x6vd33s2_mt6b696c0000gn/T/115231-887-3ys8yi/submodules/SafariLauncher/build/Release-iphoneos/SafariLauncher.app/en.lproj/Localizable.strings
2015-03-31 12:55:41:845 - info: Will try to parse the plist file as XML
2015-03-31 12:55:41:845 - info: [debug] Could not parse plist file (as XML) at /var/folders/xn/zxrl7n3x6vd33s2_mt6b696c0000gn/T/115231-887-3ys8yi/submodules/SafariLauncher/build/Release-iphoneos/SafariLauncher.app/en.lproj/Localizable.strings
2015-03-31 12:55:41:845 - warn: Could not parse app Localizable.strings assuming it doesn't exist
2015-03-31 12:55:41:845 - info: [debug] Creating instruments
2015-03-31 12:55:41:847 - info: [debug] Preparing uiauto bootstrap
2015-03-31 12:55:41:848 - info: [debug] Dynamic bootstrap dir: /Users/qa/Library/Application Support/appium/bootstrap
2015-03-31 12:55:41:848 - info: [debug] Dynamic env: {"nodePath":"/usr/local/bin/node","commandProxyClientPath":"/Users/qa/automation/apps/appium/newAppiumGit/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"grouped"}
...5-03-31 12:55:41:853 - info: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
2015-03-31 12:55:41:853 - info: [debug] Dynamic bootstrap path: /Users/qa/Library/Application Support/appium/bootstrap/bootstrap-62bba7ccd62cb101.js
2015-03-31 12:55:41:855 - info: [debug] Reusing dynamic bootstrap: /Users/qa/Library/Application Support/appium/bootstrap/bootstrap-62bba7ccd62cb101.js
2015-03-31 12:55:41:856 - info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.2","iOSSDKVersion":"8.2","deviceName":"iPad 1 mini","platformVersion":"8.2"}
2015-03-31 12:55:41:856 - info: [debug] fixDevice is on
2015-03-31 12:55:41:856 - info: [debug] Final device string is: 'iPad 1 mini (8.2 Simulator)'
2015-03-31 12:55:41:857 - info: [debug] Not setting device type since we're on a real device
2015-03-31 12:55:41:858 - info: [debug] Checking whether we need to set app preferences
2015-03-31 12:55:41:858 - info: [debug] Not setting iOS and app preferences since we're on a real device
2015-03-31 12:55:41:858 - info: [debug] Running ios sim reset flow
2015-03-31 12:55:41:858 - info: [debug] Killing the simulator process
2015-03-31 12:55:41:859 - info: [debug] Killall iOS Simulator
2015-03-31 12:55:41:861 - info: [debug] Killing any other simulator daemons
2015-03-31 12:55:41:883 - info: [debug] On a real device; cannot clean device state
2015-03-31 12:55:41:884 - info: [debug] Not setting locale because we're using a real device
2015-03-31 12:55:41:884 - info: [debug] No iOS / app preferences to set
2015-03-31 12:55:41:885 - info: [debug] Starting iOS device log capture via deviceconsole
2015-03-31 12:55:42:914 - info: --> GET /wd/hub/status {}
2015-03-31 12:55:42:915 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.7","revision":"84e84584042d0242704c8a98e92b87a7ac74ceda"},"isShuttingDown":false},"sessionId":"4dc50e61-1ea1-457b-8416-b862afd89cfa"}
2015-03-31 12:55:42:916 - info: <-- GET /wd/hub/status 200 1.444 ms - 178 {"status":0,"value":{"build":{"version":"1.3.7","revision":"84e84584042d0242704c8a98e92b87a7ac74ceda"},"isShuttingDown":false},"sessionId":"4dc50e61-1ea1-457b-8416-b862afd89cfa"}
2015-03-31 12:55:42:986 - info: [debug] Not pre-launching simulator
2015-03-31 12:55:42:988 - error: Unhandled error: TypeError: Cannot read property 'isInstalled' of undefined
    at IOS.isAppInstalled (/Users/qa/automation/apps/appium/newAppiumGit/appium/lib/devices/ios/ios.js:1473:20)
    at Safari.installToRealDevice (/Users/qa/automation/apps/appium/newAppiumGit/appium/lib/devices/ios/safari.js:118:10)
    at /Users/qa/automation/apps/appium/newAppiumGit/appium/node_modules/async/lib/async.js:610:21
    at /Users/qa/automation/apps/appium/newAppiumGit/appium/node_modules/async/lib/async.js:249:17
    at iterate (/Users/qa/automation/apps/appium/newAppiumGit/appium/node_modules/async/lib/async.js:149:13)
    at /Users/qa/automation/apps/appium/newAppiumGit/appium/node_modules/async/lib/async.js:160:25
    at /Users/qa/automation/apps/appium/newAppiumGit/appium/node_modules/async/lib/async.js:251:21
    at /Users/qa/automation/apps/appium/newAppiumGit/appium/node_modules/async/lib/async.js:615:34
    at IOS.prelaunchSimulator (/Users/qa/automation/apps/appium/newAppiumGit/appium/lib/devices/ios/ios.js:1191:12)
    at /Users/qa/automation/apps/appium/newAppiumGit/appium/node_modules/async/lib/async.js:610:21 context: [POST /wd/hub/session {"desiredCapabilities":{"newCommandTimeout":60,"app":"Safari","platformVersion":"8.2","javascriptEnabled":"true","elementScrollBehavior":"elementScrollBehavior","deviceName":"iPad 1 mini","platformNam]
2015-03-31 12:55:48:087 - info: --> GET /wd/hub/status {}
2015-03-31 12:55:48:088 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.7","revision":"84e84584042d0242704c8a98e92b87a7ac74ceda"},"isShuttingDown":false},"sessionId":"4dc50e61-1ea1-457b-8416-b862afd89cfa"}

**Comment by jlipps** [comment]
can you include the beginning of the appium log so we see what caps are sent in?

**Comment by ivasylchenko** [comment]
Same issue with following capabilities:
```javascript
private static WebDriver createIOSDriver(Device iOSDevice) {
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("platfromName", "iOS");
        capabilities.setCapability("browserName", "Safari");
        capabilities.setCapability("autoWebview", true);
        capabilities.setCapability("deviceName", iOSDevice.getName());
        capabilities.setCapability("platfromVersion", iOSDevice.getVersion());
        capabilities.setCapability("udid", iOSDevice.getSerial());

        IOSDriver driver = new IOSDriver(getUrl(iOSDevice.getRemote()), capabilities);
        return driver;
    }
```

**Comment by nikolmarku1** [comment]
full log from appium console

Last login: Wed Apr  1 10:21:17 on ttys002
admins-imac:~ qa$ /Users/qa/automation/selenium/appium/ios/4_start-appium-ios-MiniTablet.csh ; exit;
Start Appium Server
On port : 4724
2015-04-01 10:21:35:954 - info: Welcome to Appium v1.3.7 (REV 72fbfaa116d3d9f6a862600ee99cf02f6d0e2182)
2015-04-01 10:21:35:959 - info: Appium REST http interface listener started on 10.24.208.210:4724
2015-04-01 10:21:35:963 - info: [debug] Non-default server args: {"app":"/Users/qa/automation/apps/SafariLauncher.app","udid":"8f3875eefad92b632c7f9227de1b49027dc13066","address":"10.24.208.210","port":4724,"fullReset":true,"launchTimeout":"40000","log":"/tmp/appiumIpad100.log","logTimestamp":true,"localTimezone":true,"nativeInstrumentsLib":true,"deviceName":"iPad 1 mini","platformName":"iOS","platformVersion":"8.2","orientation":"Landscape","nodeconfig":"/Users/qa/automation/selenium/appium/ios/configIpadmini.json","defaultCommandTimeout":100}
2015-04-01 10:21:35:964 - info: Console LogLevel: debug
2015-04-01 10:21:35:964 - info: File LogLevel: debug
2015-04-01 10:21:35:968 - info: [debug] starting auto register thread for grid. Will try to register every 7000 ms.
2015-04-01 10:21:43:309 - info: [debug] Appium successfully registered with the grid on usb-etbuild5:4444
2015-04-01 10:21:48:400 - info: --> GET /wd/hub/status {}
2015-04-01 10:21:48:401 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.7","revision":"72fbfaa116d3d9f6a862600ee99cf02f6d0e2182"}}}
2015-04-01 10:21:48:406 - info: <-- GET /wd/hub/status 200 6.098 ms - 104 {"status":0,"value":{"build":{"version":"1.3.7","revision":"72fbfaa116d3d9f6a862600ee99cf02f6d0e2182"}}}
2015-04-01 10:21:53:577 - info: --> GET /wd/hub/status {}
2015-04-01 10:21:53:577 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.7","revision":"72fbfaa116d3d9f6a862600ee99cf02f6d0e2182"}}}
2015-04-01 10:21:53:579 - info: <-- GET /wd/hub/status 200 2.689 ms - 104 {"status":0,"value":{"build":{"version":"1.3.7","revision":"72fbfaa116d3d9f6a862600ee99cf02f6d0e2182"}}}
2015-04-01 10:21:58:750 - info: --> GET /wd/hub/status {}
2015-04-01 10:21:58:750 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.7","revision":"72fbfaa116d3d9f6a862600ee99cf02f6d0e2182"}}}
2015-04-01 10:21:58:751 - info: <-- GET /wd/hub/status 200 1.284 ms - 104 {"status":0,"value":{"build":{"version":"1.3.7","revision":"72fbfaa116d3d9f6a862600ee99cf02f6d0e2182"}}}
2015-04-01 10:22:03:924 - info: --> GET /wd/hub/status {}
2015-04-01 10:22:03:924 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.7","revision":"72fbfaa116d3d9f6a862600ee99cf02f6d0e2182"}}}
2015-04-01 10:22:03:925 - info: <-- GET /wd/hub/status 200 1.269 ms - 104 {"status":0,"value":{"build":{"version":"1.3.7","revision":"72fbfaa116d3d9f6a862600ee99cf02f6d0e2182"}}}
2015-04-01 10:22:09:096 - info: --> GET /wd/hub/status {}
2015-04-01 10:22:09:096 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.7","revision":"72fbfaa116d3d9f6a862600ee99cf02f6d0e2182"}}}
2015-04-01 10:22:09:097 - info: <-- GET /wd/hub/status 200 1.120 ms - 104 {"status":0,"value":{"build":{"version":"1.3.7","revision":"72fbfaa116d3d9f6a862600ee99cf02f6d0e2182"}}}
2015-04-01 10:22:14:268 - info: --> GET /wd/hub/status {}
2015-04-01 10:22:14:268 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.7","revision":"72fbfaa116d3d9f6a862600ee99cf02f6d0e2182"}}}
2015-04-01 10:22:14:269 - info: <-- GET /wd/hub/status 200 1.066 ms - 104 {"status":0,"value":{"build":{"version":"1.3.7","revision":"72fbfaa116d3d9f6a862600ee99cf02f6d0e2182"}}}
2015-04-01 10:22:19:441 - info: --> GET /wd/hub/status {}
2015-04-01 10:22:19:442 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.7","revision":"72fbfaa116d3d9f6a862600ee99cf02f6d0e2182"}}}
2015-04-01 10:22:19:442 - info: <-- GET /wd/hub/status 200 0.935 ms - 104 {"status":0,"value":{"build":{"version":"1.3.7","revision":"72fbfaa116d3d9f6a862600ee99cf02f6d0e2182"}}}
2015-04-01 10:22:24:660 - info: --> GET /wd/hub/status {}
2015-04-01 10:22:24:660 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.7","revision":"72fbfaa116d3d9f6a862600ee99cf02f6d0e2182"}}}
2015-04-01 10:22:24:661 - info: <-- GET /wd/hub/status 200 1.164 ms - 104 {"status":0,"value":{"build":{"version":"1.3.7","revision":"72fbfaa116d3d9f6a862600ee99cf02f6d0e2182"}}}
2015-04-01 10:22:29:831 - info: --> GET /wd/hub/status {}
2015-04-01 10:22:29:831 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.7","revision":"72fbfaa116d3d9f6a862600ee99cf02f6d0e2182"}}}
2015-04-01 10:22:29:832 - info: <-- GET /wd/hub/status 200 1.127 ms - 104 {"status":0,"value":{"build":{"version":"1.3.7","revision":"72fbfaa116d3d9f6a862600ee99cf02f6d0e2182"}}}
2015-04-01 10:22:32:740 - info: --> POST /wd/hub/session {"desiredCapabilities":{"newCommandTimeout":60,"app":"Safari","platformVersion":"8.2","javascriptEnabled":"true","elementScrollBehavior":"elementScrollBehavior","deviceName":"iPad 1 mini","platformName":"iOS","browserName":"safari","launchTimeout":40000,"bundleId":"SafariLauncher","networkConnectionEnabled":"true","safariOpenLinksInBackground":true,"udid":"8f3875eefad92b632c7f9227de1b49027dc13066","takesScreenshot":"true"}}
2015-04-01 10:22:32:740 - info: Client User-Agent string: Apache-HttpClient/4.3.3 (java 1.5)
2015-04-01 10:22:32:741 - warn: Converting cap javascriptEnabled from string to boolean. This might cause unexpected behavior.
2015-04-01 10:22:32:741 - warn: Converting cap networkConnectionEnabled from string to boolean. This might cause unexpected behavior.
2015-04-01 10:22:32:741 - warn: Converting cap takesScreenshot from string to boolean. This might cause unexpected behavior.
2015-04-01 10:22:32:743 - info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : javascriptEnabled, elementScrollBehavior, networkConnectionEnabled, takesScreenshot
2015-04-01 10:22:32:744 - info: [debug] Configuring Safari session
2015-04-01 10:22:32:745 - info: [debug] Using local .zip from desired caps: /Applications/Appium.app/Contents/Resources/node_modules/appium/build/SafariLauncher/SafariLauncher.zip
2015-04-01 10:22:32:746 - info: [debug] Copying local zip to tmp dir
2015-04-01 10:22:32:751 - info: [debug] /Applications/Appium.app/Contents/Resources/node_modules/appium/build/SafariLauncher/SafariLauncher.zip copied to /var/folders/xn/zxrl7n3x6vd33s2_mt6b696c0000gn/T/11531-2254-17gmw6f/appium-app.zip
2015-04-01 10:22:32:760 - info: [debug] Unzipping /var/folders/xn/zxrl7n3x6vd33s2_mt6b696c0000gn/T/11531-2254-17gmw6f/appium-app.zip
2015-04-01 10:22:32:761 - info: [debug] Testing zip archive: /var/folders/xn/zxrl7n3x6vd33s2_mt6b696c0000gn/T/11531-2254-17gmw6f/appium-app.zip
2015-04-01 10:22:32:768 - info: [debug] Zip archive tested clean
2015-04-01 10:22:32:777 - info: [debug] Unzip successful
2015-04-01 10:22:32:778 - info: [debug] Using locally extracted app: /var/folders/xn/zxrl7n3x6vd33s2_mt6b696c0000gn/T/11531-2254-17gmw6f/submodules/SafariLauncher/build/Release-iphoneos/SafariLauncher.app
2015-04-01 10:22:32:779 - info: [debug] Creating new appium session 9ff80806-90a4-476b-b6d6-47f477976a3c
2015-04-01 10:22:32:781 - info: [debug] Removing any remaining instruments sockets
2015-04-01 10:22:32:782 - info: [debug] Cleaned up instruments socket /tmp/instruments_sock
2015-04-01 10:22:32:784 - info: [debug] Setting Xcode folder
2015-04-01 10:22:32:793 - info: [debug] Setting Xcode version
2015-04-01 10:22:32:808 - info: [debug] Setting iOS SDK Version
2015-04-01 10:22:32:823 - info: [debug] Getting sdk version from xcrun with a timeout
2015-04-01 10:22:32:829 - info: [debug] iOS SDK Version set to 8.2
2015-04-01 10:22:32:830 - info: [debug] Not checking whether simulator is available since we're on a real device
2015-04-01 10:22:32:830 - info: [debug] Detecting automation tracetemplate
2015-04-01 10:22:32:838 - info: [debug] Not auto-detecting udid, running on sim
2015-04-01 10:22:32:839 - info: [debug] Could not parse plist file (as binary) at /var/folders/xn/zxrl7n3x6vd33s2_mt6b696c0000gn/T/11531-2254-17gmw6f/submodules/SafariLauncher/build/Release-iphoneos/SafariLauncher.app/en.lproj/Localizable.strings
2015-04-01 10:22:32:840 - info: Will try to parse the plist file as XML
2015-04-01 10:22:32:840 - info: [debug] Could not parse plist file (as XML) at /var/folders/xn/zxrl7n3x6vd33s2_mt6b696c0000gn/T/11531-2254-17gmw6f/submodules/SafariLauncher/build/Release-iphoneos/SafariLauncher.app/en.lproj/Localizable.strings
2015-04-01 10:22:32:840 - warn: Could not parse app Localizable.strings assuming it doesn't exist
2015-04-01 10:22:32:840 - info: [debug] Creating instruments
2015-04-01 10:22:32:841 - info: [debug] Preparing uiauto bootstrap
2015-04-01 10:22:32:843 - info: [debug] Dynamic bootstrap dir: /Users/qa/Library/Application Support/appium/bootstrap
2015-04-01 10:22:32:843 - info: [debug] Dynamic env: {"nodePath":"/usr/local/bin/node","commandProxyClientPath":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"grouped"}
...5-04-01 10:22:32:849 - info: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
2015-04-01 10:22:32:849 - info: [debug] Dynamic bootstrap path: /Users/qa/Library/Application Support/appium/bootstrap/bootstrap-718f2dc32d2dcc82.js
2015-04-01 10:22:32:851 - info: [debug] Reusing dynamic bootstrap: /Users/qa/Library/Application Support/appium/bootstrap/bootstrap-718f2dc32d2dcc82.js
2015-04-01 10:22:32:851 - info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.2","iOSSDKVersion":"8.2","deviceName":"iPad 1 mini","platformVersion":"8.2"}
2015-04-01 10:22:32:852 - info: [debug] fixDevice is on
2015-04-01 10:22:32:852 - info: [debug] Final device string is: 'iPad 1 mini (8.2 Simulator)'
2015-04-01 10:22:32:853 - info: [debug] Not setting device type since we're on a real device
2015-04-01 10:22:32:853 - info: [debug] Checking whether we need to set app preferences
2015-04-01 10:22:32:853 - info: [debug] Not setting iOS and app preferences since we're on a real device
2015-04-01 10:22:32:853 - info: [debug] Running ios sim reset flow
2015-04-01 10:22:32:854 - info: [debug] Killing the simulator process
2015-04-01 10:22:32:854 - info: [debug] Killall iOS Simulator
2015-04-01 10:22:32:856 - info: [debug] Killing any other simulator daemons
2015-04-01 10:22:32:875 - info: [debug] On a real device; cannot clean device state
2015-04-01 10:22:32:875 - info: [debug] Not setting locale because we're using a real device
2015-04-01 10:22:32:876 - info: [debug] No iOS / app preferences to set
2015-04-01 10:22:32:877 - info: [debug] Starting iOS device log capture via deviceconsole
2015-04-01 10:22:33:975 - info: [debug] Not pre-launching simulator
2015-04-01 10:22:33:975 - info: [debug] Checking app install status using: /Applications/Appium.app/Contents/Resources/node_modules/appium/build/fruitstrap/fruitstrap isInstalled --id 8f3875eefad92b632c7f9227de1b49027dc13066 --bundle com.bytearc.SafariLauncher
2015-04-01 10:22:34:855 - info: [debug] Installing app using cmd: /Applications/Appium.app/Contents/Resources/node_modules/appium/build/fruitstrap/fruitstrap install --id 8f3875eefad92b632c7f9227de1b49027dc13066 --bundle "/var/folders/xn/zxrl7n3x6vd33s2_mt6b696c0000gn/T/11531-2254-17gmw6f/submodules/SafariLauncher/build/Release-iphoneos/SafariLauncher.app"
2015-04-01 10:22:35:004 - info: --> GET /wd/hub/status {}
2015-04-01 10:22:35:005 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.7","revision":"72fbfaa116d3d9f6a862600ee99cf02f6d0e2182"},"isShuttingDown":false},"sessionId":"9ff80806-90a4-476b-b6d6-47f477976a3c"}
2015-04-01 10:22:35:006 - info: <-- GET /wd/hub/status 200 1.466 ms - 178 {"status":0,"value":{"build":{"version":"1.3.7","revision":"72fbfaa116d3d9f6a862600ee99cf02f6d0e2182"},"isShuttingDown":false},"sessionId":"9ff80806-90a4-476b-b6d6-47f477976a3c"}
2015-04-01 10:22:37:122 - info: [debug] Starting command proxy.
2015-04-01 10:22:37:132 - info: [debug] Instruments socket server started at /tmp/instruments_sock
2015-04-01 10:22:37:133 - info: [debug] Starting instruments
2015-04-01 10:22:37:139 - info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
2015-04-01 10:22:37:140 - info: Launching instruments
2015-04-01 10:22:37:141 - info: [debug] Attempting to run app on real device with UDID 8f3875eefad92b632c7f9227de1b49027dc13066
2015-04-01 10:22:37:142 - info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w 8f3875eefad92b632c7f9227de1b49027dc13066 SafariLauncher -e UIASCRIPT "/Users/qa/Library/Application Support/appium/bootstrap/bootstrap-718f2dc32d2dcc82.js" -e UIARESULTSPATH /tmp/appium-instruments
2015-04-01 10:22:37:142 - info: [debug] And extra without-delay env: {}
2015-04-01 10:22:37:142 - info: [debug] And launch timeouts (in ms): {"global":40000}
2015-04-01 10:22:38:138 - info: [debug] [INST STDERR] 2015-04-01 10:22:38.138 instruments[2285:878764] WebKit Threading Violation - initial use of WebKit from a secondary thread.
2015-04-01 10:22:40:177 - info: --> GET /wd/hub/status {}
2015-04-01 10:22:40:177 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.7","revision":"72fbfaa116d3d9f6a862600ee99cf02f6d0e2182"},"isShuttingDown":false},"sessionId":"9ff80806-90a4-476b-b6d6-47f477976a3c"}
2015-04-01 10:22:40:178 - info: <-- GET /wd/hub/status 200 1.095 ms - 178 {"status":0,"value":{"build":{"version":"1.3.7","revision":"72fbfaa116d3d9f6a862600ee99cf02f6d0e2182"},"isShuttingDown":false},"sessionId":"9ff80806-90a4-476b-b6d6-47f477976a3c"}
^Clogout

**Comment by nikolmarku1** [comment]
capabilities 

=======
---------------------
        String platformName = "iOS";
        String browserName  = "safari";
        String deviceName   = "iPad 1 mini";
        String version      = "8.2"; // "8.1.3";
       
            capability = new DesiredCapabilities(); 
            
            capability.setCapability("app","Safari");
            capability.setCapability("udid","8f3875eefad92b632c7f9227de1b49027dc13066");
            capability.setCapability("bundleId", "SafariLauncher");            
            capability.setCapability("safariOpenLinksInBackground", true);
            capability.setCapability("newCommandTimeout", 60);
            capability.setCapability("launchTimeout", 40000);// todo - remove
 -----------------------
        capability.setCapability(MobileCapabilityType.SUPPORTS_JAVASCRIPT, "true");
        capability.setCapability(MobileCapabilityType.SUPPORTS_NETWORK_CONNECTION, "true");
        capability.setCapability(MobileCapabilityType.TAKES_SCREENSHOT, "true");
        capability.setCapability(MobileCapabilityType.LAUNCH_TIMEOUT, "40000");
          

 -------------------------     
        capability.setCapability(MobileCapabilityType.PLATFORM_NAME, platformName);   
        capability.setCapability(MobileCapabilityType.PLATFORM_VERSION, version);
        capability.setCapability(MobileCapabilityType.BROWSER_NAME, browserName);
        capability.setCapability(MobileCapabilityType.DEVICE_NAME, deviceName);
        capability.setCapability(MobileCapabilityType.ELEMENT_SCROLL_BEHAVIOR, "elementScrollBehavior");
       
    
----------------------

**Comment by ivasylchenko** [comment]
After applying https://github.com/imurchie/appium/commit/fa568637eb622dd5a538d581f5c2f07fc9159e89
error gone. 
Thanks

**Comment by ASYB** [comment]
Still I am facing problem in Simulator, where as in real device working fine
