### ISSUE TITLE
App download from HTTPS URL is not supported by Appium

### ISSUE THREAD

**Issue by rahulk06** [appium/appium#4832]
Hi,

Downloading the app from the URL with HTTPS  fails with the below error :

error: Unhandled error: Error: read ECONNRESET
    at errnoException (net.js:904:11)
    at TCP.onread (net.js:558:19) context: [POST /wd/hub/session {"desiredCapabilities":{"headers"
:{"Authorization":"apikey=prdakyresOf3EvFMkqSNMQKA6qYIyRmEO06Is4fS"},"platfor
mVersion":"4.4.2","app":"https://build.xxxxx.com/gala/android/release/trunk/xxx.com.4.2.0.2185.debug.apk]

Can someone please help me on this.

Thanks,
Rahul.

**Comment by jlipps** [comment]
`headers` is not a capability appium supports. Is it necessary for connecting to your server?

**Comment by rahulk06** [comment]
I know that headers is not a capability supported by Appium. We are passing is as a capability because our service is behind the gateway and therefore it is used for Authorization. (Here is the discussion link : https://github.com/SeleniumHQ/selenium/pull/276 ) 

Further I saw that Appium uses Request.js - that supports HTTPS but I think for that we may need to pass extra options which is not supported at present. I found this below function in Helper.js file which I think is used for downloading the apk.

exports.downloadFile = function (fileUrl, suffix, cb) {
  // We will be downloading the files to a directory, so make sure it's there
  // This step is not required if you have manually created the directory
  logger.debug('fileUrl ==='+fileUrl);
  tempDir.open({prefix: 'appium-app', suffix: suffix}).nodeify(function (err, info) {
    fs.close(info.fd);
    var file = fs.createWriteStream(info.path);
    request(fileUrl).pipe(file).on('close', function () {
      logger.debug(fileUrl + ' downloaded to ' + info.path);
      cb(info.path);
    });
  });
};

**Comment by jlipps** [comment]
Yeah, what about just including the http auth in the url itself? e.g. the app capability would be `https://<user>:<pass>@<host>/<app>`

**Comment by rahulk06** [comment]
Thanks Jonathan !

But the thing is when I hit the APP URL from a browser , I am able to download the app, there I don't have to specify any username/password. Therefore , I think , if I use use the same URL in app capability then appium should be able to download the app. Please refer to below screenshot :

![image](https://cloud.githubusercontent.com/assets/9517306/7017698/fbc4d268-dd18-11e4-9157-26f5d1c612c4.png)

**Comment by jlipps** [comment]
does it work without HTTPS?

**Comment by rahulk06** [comment]
Yes, when we download the app from browser and upload it in a nexus repo with a HTTP URL, then appium is able to download the apk.

**Comment by jlipps** [comment]
does the https url have a self-signed cert?

**Comment by rahulk06** [comment]
Looks like it doesn't have a self-signed cert. Refer to the below screenshot :

![image](https://cloud.githubusercontent.com/assets/9517306/7112776/cdfe5ca6-e1ea-11e4-8dba-d5a7274d8ee0.png)

**Comment by rahulk06** [comment]
Looks like it doesn't have a self-signed cert. Refer to the below screenshot :

![image](https://cloud.githubusercontent.com/assets/9517306/7112811/0c8c2e94-e1eb-11e4-8c4d-8561e6391286.png)

**Comment by rahulk06** [comment]
Looks like it doesn't have a self-signed cert. Refer to the below screenshot :

![image](https://cloud.githubusercontent.com/assets/9517306/7112832/5c5212e0-e1eb-11e4-8f1b-825fec725556.png)

**Comment by jlipps** [comment]
i'm not sure this is an issue with appium yet, but I did uncover a bug that meant errors were getting silently ignored in this case. i just merged some code that should communicate any errors more clearly. if you're running from master you can give it a try

**Comment by moizjv** [comment]
Closing due to inactivity
