### ISSUE TITLE
Responding to client that a method is not implemented

### ISSUE THREAD

**Issue by Harbhawan** [appium/appium#4834]
Appium With Protractor for Android App

capabilities: {
    'browserName': '',
    'appium-version': '1.3.5',
    'platformName': 'Android',
    'platformVersion': '5.0',
    'deviceName': 'Android Device',
    'app-package': "com.****.android",
    'app-activity': "******.******MainActivity",
    'app': "/Users/*********.apk",
      'udid':'BA99301YYA',
      'autoWebview': true
  },

Appium Server log:
info: --> POST /wd/hub/session/9b2b0805-2cc6-4d6c-b63d-143bbde5d32f/timeouts/async_script {"ms":120000}
info: [debug] Responding to client that a method is not implemented
info: <-- POST /wd/hub/session/9b2b0805-2cc6-4d6c-b63d-143bbde5d32f/timeouts/async_script 501 0.942 ms - 158 
info: [debug] Didn't get a new command in 60 secs, shutting down...

Execution Log:
Using the selenium server at http://localhost:4723/wd/hub
[launcher] Running 1 instances of WebDriver

/Users/360_Logica/Documents/AutomationCode/androidApp/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:113
  var template = new Error(this.message);
                 ^
UnknownError: Not yet implemented. Please help us: http://appium.io/get-involved.html
    at new bot.Error (/Users/test/Documents/AutomationCode/androidApp/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:113:18)
    at Object.bot.response.checkResponse (/Users/test/Documents/AutomationCode/androidApp/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/response.js:106:9)
    at /Users/test/Documents/AutomationCode/androidApp/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:362:20
    at /Users/test/Documents/AutomationCode/androidApp/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1582:15
    at [object Object].webdriver.promise.ControlFlow.runInNewFrame_ (/Users/test/Documents/AutomationCode/androidApp/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1654:20)
    at notify (/Users/test/Documents/AutomationCode/androidApp/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:465:12)
    at notifyAll (/Users/test/Documents/AutomationCode/androidApp/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:442:7)
    at resolve (/Users/test/Documents/AutomationCode/androidApp/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:420:7)
    at [object Object].fulfill (/Users/test/Documents/AutomationCode/androidApp/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:535:5)
    at /Users/test/Documents/AutomationCode/androidApp/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1520:10
==== async task ====
WebDriver.manage().timeouts().setScriptTimeout(120000)
    at webdriver.WebDriver.schedule (/Users/test/Documents/AutomationCode/androidApp/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:345:15)
    at webdriver.WebDriver.Timeouts.setScriptTimeout (/Users/test/Documents/AutomationCode/androidApp/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:1301:23)
    at Runner.createBrowser (/Users/test/Documents/AutomationCode/androidApp/node_modules/protractor/lib/runner.js:181:30)
    at /Users/test/Documents/AutomationCode/androidApp/node_modules/protractor/lib/runner.js:257:21
    at _fulfilled (/Users/test/Documents/AutomationCode/androidApp/node_modules/protractor/node_modules/q/q.js:797:54)
    at self.promiseDispatch.done (/Users/test/Documents/AutomationCode/androidApp/node_modules/protractor/node_modules/q/q.js:826:30)
    at Promise.promise.promiseDispatch (/Users/test/Documents/AutomationCode/androidApp/node_modules/protractor/node_modules/q/q.js:759:13)
    at /Users/test/Documents/AutomationCode/androidApp/node_modules/protractor/node_modules/q/q.js:573:44
    at flush (/Users/test/Documents/AutomationCode/androidApp/node_modules/protractor/node_modules/q/q.js:108:17)
[launcher] Process exited with error code 1

**Comment by amaanmemon** [comment]
use wd module for android apps instead of selenium-webdriver

**Comment by imurchie** [comment]
No matter what client you use, the Appium server doesn't implement that endpoint for Android. 

https://github.com/appium/appium/blob/master/lib/devices/android/android-controller.js#L229

**Comment by Harbhawan** [comment]
@imurchie, thanks for the update

**Comment by imurchie** [comment]
I'm not sure what the actual issue is. Just don't call whatever method is sending to the `async_script` endpoint.

**Comment by jlipps** [comment]
protractor is for web testing, not native app testing. if you have a hybrid app, you can set the autoWebview capability to true so you can automate with protractor.

**Comment by Harbhawan** [comment]
@jlipps I am using protractor framework for native app automation testing,
protactor framework execution more faster than other framework

**Comment by jlipps** [comment]
I thought protractor was for testing angular apps?

**Comment by moizjv** [comment]
closing due to inactivity

**Comment by Harbhawan** [comment]
Hi @moizjv 

Please do not close this issue, I am still facing issue for Android App

**Comment by Harbhawan** [comment]
Hi @jlipps 

You are right Protractor using for Angular App
protractor framework execution more faster than other framework (TestNg)

**Comment by Harbhawan** [comment]
Hi All,

Please let me know any more information required from my side.

**Comment by moizjv** [comment]
@Harbhawan can you paste what part of code is causing this issue?

**Comment by sebv** [comment]
@Harbhawan you need to switch context before calling native method.

**Comment by sebv** [comment]
Closing, no activity, may be reopened if needed.
