### ISSUE TITLE
Can execute JavascriptExecutor in IOSDriver

### ISSUE THREAD

**Issue by Kolyall** [appium/appium#4849]
Here is code of my test
public class iOS_Tablet_Test {
	private static IOSDriver wd;
        @Before //for Junit
	public void setUp () throws MalformedURLException{
		DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setCapability("appium-version", "1.0");
		capabilities.setCapability("platformName", "iOS");
		capabilities.setCapability("platformVersion", "7.1");
		capabilities.setCapability("deviceName", "Paul's iPad");
		capabilities.setCapability("app", "/Users/user/Dropbox/android_libs_for_projects/appcas/skeleton.ipa");
		try {
			wd = new IOSDriver(new URL("http://0.0.0.0:4723/wd/hub"), capabilities);
		} catch (MalformedURLException e) {
			e.printStackTrace();
		}
		wd.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
		}

@Test
	public void test_01_SwipeToFeaturedPresets(){
		((JavascriptExecutor)wd).executeScript(	"mobile: swipe", new HashMap<String, Double>() 			{{ put("touchCount", 1.0); put("startX", 984.0); put("startY", 364.0); put("endX", 217.0);	put("endY", 377.0); put("duration", 0.5); }});
		}

Error is 
org.openqa.selenium.WebDriverException: Not yet implemented. Please help us: http://appium.io/get-involved.html (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 15 milliseconds
Build info: version: '2.45.0', revision: '32a636c', time: '2015-03-05 22:01:35'
System info: host: 'Mac-mini-User.elilink.by', ip: '172.17.1.56', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.2', java.version: '1.8.0_40'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{app=/Users/user/Dropbox/android_libs_for_projects/appcas/skeleton.ipa, networkConnectionEnabled=false, warnings={}, databaseEnabled=false, deviceName=Paul's iPad, platform=MAC, desired={app=/Users/user/Dropbox/android_libs_for_projects/appcas/skeleton.ipa, appium-version=1.0, platformVersion=7.1, platformName=iOS, deviceName=Paul's iPad}, appium-version=1.0, platformVersion=7.1, webStorageEnabled=false, locationContextEnabled=false, browserName=iOS, takesScreenshot=true, javascriptEnabled=true, platformName=iOS}]
Session ID: be6c3adf-3545-4873-8ddb-08cb8
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:180)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:508)
	at iOS_Zik2_Tablet_Test.test_01_SwipeToFeaturedPresets(iOS_Zik2_Tablet_Test.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

**Comment by developerqa** [comment]
Appium v1.3.6 


Have same issue with using swipe()

	public void swipe() {
		Dimension size = ((IOSDriver)driverClient.getDriver()).manage().window().getSize();
		System.out.println(size);
		//((IOSDriver)driverClient.getDriver()).switchTo().window("webView");
	    int startX = (int)(size.width * 0.10);
	    int endX = (int)(size.width * 0.80);
	    int startY = size.height/2;
		((IOSDriver)driverClient.getDriver()).swipe(startX,startY,endX,startY,1000);		
	}


org.openqa.selenium.WebDriverException: Not yet implemented. Please help us: http://appium.io/get-involved.html

org.openqa.selenium.WebDriverException: Not yet implemented. Please help us: http://appium.io/get-involved.html (WARNING: The server did not provide any stacktrace information)
      Command duration or timeout: 5 milliseconds
      Build info: version: '2.43.1', revision: '5163bceef1bc36d43f3dc0b83c88998168a363a0', time: '2014-09-10 09:43:55'
      System info: host: 'ENGInEQA.dunton.ford.com', ip: '19.151.154.233', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.2', java.version: '1.7.0_75'
      Session ID: d890f24e-245b-43fd-a1ad-a53dcdb4374d
      Driver info: io.appium.java_client.ios.IOSDriver
      Capabilities [{automationName=iOS, platform=MAC, javascriptEnabled=true, browserName=Safari, networkConnectionEnabled=false, desired={automationName=iOS, platformVersion=8.1, deviceName=iPhone 5s, platformName=iOS, browserName=Safari}, locationContextEnabled=false, platformVersion=8.1, databaseEnabled=false, platformName=iOS, deviceName=iPhone 5s, safari=true, webStorageEnabled=false, warnings={}, takesScreenshot=true}]
      	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
      	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
      	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
      	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
      	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
      	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
      	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
      	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:180)
      	at io.appium.java_client.AppiumDriver.performTouchAction(AppiumDriver.java:304)
      	at io.appium.java_client.TouchAction.perform(TouchAction.java:253)
      	at io.appium.java_client.AppiumDriver.swipe(AppiumDriver.java:359)
      	at com.engine.automation.mobile.pages.HomePage.swipe(HomePage.java:59)
      	at com.engine.automation.mobile.example.guxHomePageVehiclesViewing.the_user_swipes_the_carrousel(guxHomePageVehiclesViewing.java:73)
      	at ✽.When the user swipes the carrousel(com/engine/automation/mobile/example/guxHomePageVehiclesViewing.feature:8)

**Comment by moizjv** [comment]
@developerqa can you put complete appium logs?

**Comment by Jonahss** [comment]
Also, how does it work on version 1.4 (from 1.4 branch)

**Comment by sebv** [comment]
Closing, no activity, may be reopened if needed.
