### ISSUE TITLE
java -version' failed. Error: spawn ENOENT    while running the scripts

### ISSUE THREAD

**Issue by Rakeshvallabhaneni** [appium/appium#4876]
Hi,

 Using appium + java , while running the scripts an java -version' failed. Error: spawn ENOENT  occured .

Please find below appium Log:

> Starting Node Server
> info: Welcome to Appium v1.3.4 (REV c8c79a85fbd6870cd6fc3d66d038a115ebe22efe)
> info: Appium REST http interface listener started on 127.0.0.1:4723
> info: [debug] Non-default server args: {"app":"C:\\rose\\mobile\\contacts.apk","address":"127.0.0.1","logNoColors":true,"platformName":"Android","platformVersion":"18","automationName":"Appium"}
> info: Console LogLevel: debug
> info: --> POST /wd/hub/session {"desiredCapabilities":{"appPackage":"nexg.contactbackup","appActivity":"com.example.readcontacts.HomeActivity","VERSION":"4.3","platformName":"Android","deviceName":"Google Nexus 7"}}
> info: Client User-Agent string: Apache-HttpClient/4.3.4 (java 1.5)
> info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : VERSION
> error: Failed to start an Appium session, err was: Error: 'java -version' failed. Error: spawn ENOENT
> info: [debug] Using local app from command line: C:\rose\mobile\contacts.apk
> info: [debug] Creating new appium session 86d4652f-fbd4-4793-82e4-f51d40f9f5fe
> info: Starting android appium
> info: [debug] Getting Java version
> info: [debug] Cleaning up android objects
> info: [debug] Cleaning up appium session
> info: [debug] Error: 'java -version' failed. Error: spawn ENOENT
>     at C:\Appium\node_modules\appium\lib\devices\android\android-common.js:1033:17
>     at exithandler (child_process.js:633:7)
>     at ChildProcess.errorhandler (child_process.js:649:5)
>     at ChildProcess.EventEmitter.emit (events.js:95:17)
>     at Process.ChildProcess._handle.onexit (child_process.js:795:12)
> info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: 'java -version' failed. Error: spawn ENOENT)","origValue":"'java -version' failed. Error: spawn ENOENT"},"sessionId":null}
> info: <-- POST /wd/hub/session 500 18.190 ms - 208

1.3.4 and 1.3.7 versions used still facing the issue able to identify java version from cmd prompt , Please provide the solution .

Thanks ,
Rakesh kumar

**Comment by moizjv** [comment]
@Rakeshvallabhaneni is your `JAVA_HOME` set correctly?

**Comment by sebv** [comment]
Closing, no activity, may be reopened if needed.

**Comment by aaaxxxccc** [comment]
I  met the same problem. Have you solved it ?     help... ~~>_<~~

**Comment by vict0ry** [comment]
Hello, it's old but maybe it could help someone.
This error causes due to difference in java version, so you can change relative path in windows to right java version or if you starting your script with .bat you can write smth like this : 

SET PATH=c:\Program Files\Java\jdk1.7.0_79\bin;%PATH%
SET JAVA_HOME="c:\Program Files\Java\jdk1.7.0_79"
