### ISSUE TITLE
Appium Crashes - Not able to run Safari Tests in iOS 8.X Simulator with Appium 1.3.7.

### ISSUE THREAD

**Issue by MUI-Fazy** [appium/appium#4902]
Hi,

Today I have updated the Appium from 1.3.4 to 1.3.7 and noted that Appium Crashes for Safari Browser Test Runs.

Following is the log:

error: Could not find button to click to get into webview. Proceeding on the assumption we have a working one.

error: uncaughtException: Object [object Object] has no method 'navToView' date=Mon Apr 13 2015 07:48:33 GMT-0400 (EDT), pid=47016, uid=502, gid=20, cwd=/Applications/Appium3.app/Contents/Resources/node_modules/appium, execPath=/usr/local/Cellar/node/0.10.36/bin/node, version=v0.10.36, argv=[node, /Applications/Appium3.app/Contents/Resources/node_modules/appium/bin/appium.js, -a, mac5, --session-override, --no-reset], rss=84606976, heapTotal=69563136, heapUsed=32157736, loadavg=[1.9833984375, 1.9951171875, 2.18359375], uptime=87004, trace=[column=19, file=/Applications/Appium3.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js, function=, line=1578, method=null, native=false, column=12, file=/Applications/Appium3.app/Contents/Resources/node_modules/appium/lib/devices/common.js, function=, line=77, method=null, native=false, column=5, file=/Applications/Appium3.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios-controller.js, function=iOSController.handleFindCb, line=302, method=handleFindCb, native=false, column=14, file=/Applications/Appium3.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios-controller.js, function=, line=101, method=null, native=false, column=14, file=/Applications/Appium3.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios-controller.js, function=, line=200, method=null, native=false, column=7, file=/Applications/Appium3.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios-controller.js, function=Object.cb [as callback], line=250, method=cb [as callback], native=false, column=43, file=/Applications/Appium3.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js, function=next, line=801, method=null, native=false, column=16, file=/Applications/Appium3.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js, function=null, line=32, method=null, native=false, column=9, file=/Applications/Appium3.app/Contents/Resources/node_modules/appium/lib/devices/common.js, function=exports.respond, line=28, method=respond, native=false, column=18, file=/Applications/Appium3.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js, function=, line=1457, method=null, native=false], stack=[TypeError: Object [object Object] has no method 'navToView', at null. (/Applications/Appium3.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js:1578:19), at null. (/Applications/Appium3.app/Contents/Resources/node_modules/appium/lib/devices/common.js:77:12), at iOSController.handleFindCb (/Applications/Appium3.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios-controller.js:302:5), at null. (/Applications/Appium3.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios-controller.js:101:14), at null. (/Applications/Appium3.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios-controller.js:200:14), at Object.cb as callback, at next (/Applications/Appium3.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:801:43), at /Applications/Appium3.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:32:16, at exports.respond (/Applications/Appium3.app/Contents/Resources/node_modules/appium/lib/devices/common.js:28:9), at null. (/Applications/Appium3.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js:1457:18)]

**Comment by MUI-Fazy** [comment]
This is happening when the flag '--no-reset' is set, seems ok with that flag removed

**Comment by MUI-Fazy** [comment]
I have pulled master, it is fine now. Seems @jlipps fixed in the commit 6264aae00b548532b4d1eae6d3d2e1080d1535bf
