### ISSUE TITLE
uncaughtException: Cannot read property 'sockets' of null date

### ISSUE THREAD

**Issue by KimMatt** [appium/appium#4927]
Just running the server

error: uncaughtException: Cannot read property 'sockets' of null date=Wed Apr 15 2015 16:56:04 GMT-0400 (EDT), pid=806, uid=677516420, gid=90124439, cwd=/Applications/Appium.app/Contents/Resources/node_modules/appium, execPath=/Applications/Appium.app/Contents/Resources/node/bin/node, version=v0.12.1, argv=[/Applications/Appium.app/Contents/Resources/node/bin/node, /Applications/Appium.app/Contents/Resources/node_modules/appium/lib/server/main.js, --command-timeout, 7200, --session-override, --pre-launch, --automation-name, Appium, --platform-name, Android, --platform-version, 4.4, --app, /Users/mkim/Documents/AUT/app/build/outputs/apk/app-debug-unaligned.apk, --avd, Nexus_5_API_21_x86], rss=89870336, heapTotal=68977920, heapUsed=45535088, loadavg=[2.37158203125, 1.89453125, 1.32568359375], uptime=1252, trace=[column=25, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/android/uiautomator.js, function=, line=193, method=null, native=false, column=9, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/underscore/underscore.js, function=Function._.each._.forEach, line=145, method=_.each._.forEach, native=false, column=5, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/android/uiautomator.js, function=UiAutomator.handleBootstrapOutput, line=183, method=handleBootstrapOutput, native=false, column=8, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/android/uiautomator.js, function=UiAutomator.outputStreamHandler, line=172, method=outputStreamHandler, native=false, column=17, file=events.js, function=Socket.emit, line=107, method=emit, native=false, column=16, file=_stream_readable.js, function=readableAddChunk, line=163, method=null, native=false, column=10, file=_stream_readable.js, function=Socket.Readable.push, line=126, method=Readable.push, native=false, column=20, file=net.js, function=Pipe.onread, line=529, method=onread, native=false], stack=[TypeError: Cannot read property 'sockets' of null,     at null.<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/android/uiautomator.js:193:25),     at Function._.each._.forEach (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/underscore/underscore.js:145:9),     at UiAutomator.handleBootstrapOutput (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/android/uiautomator.js:183:5),     at UiAutomator.outputStreamHandler (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/android/uiautomator.js:172:8),     at Socket.emit (events.js:107:17),     at readableAddChunk (_stream_readable.js:163:16),     at Socket.Readable.push (_stream_readable.js:126:10),     at Pipe.onread (net.js:529:20)]

**Comment by KimMatt** [comment]
Changing the API version fixed it.
