### ISSUE TITLE
Communication to host lost with real iOS 8.3 device and Unable to find app dir (Safari) on Simulator iOS 8.3 after upgrading to Xcode 6.3

### ISSUE THREAD

**Issue by ivasylchenko** [appium/appium#4934]
**Environment:**
Mac 10.10.3
Xcode 6.3
Appium 1.3.7 (source)
ios_webkit_debug_proxy (source)
iPhone 6 iOS 8.3 (real device) and iPhone 6 iOS 8.3 Simulator
Application: Safari

**Problem:**
After upgrading Xcode to 6.3 appium loosing connection after installing SafariLauncher and launching Safari. 
On java console I got 
```java
org.openqa.selenium.remote.SessionNotCreatedException: A new session could not be created. (Original error: Could not navigate to webview! Err: Error: connect ECONNREFUSED)
```
Looks like problem caused by ios_webkit_debug_proxy disconnecting. See https://github.com/google/ios-webkit-debug-proxy/issues/79
I've tried https://github.com/jchuong/ios-webkit-debug-proxy version and there was no error and disconnecting message in ios_webkit_debug_proxy output, but appium log showed same.

Also I've tried to run same on iPhone 6 (iOS 8.3) Simulator, but got another problem:

```
info: [debug] Unable to find app dir /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulatornull.sdk/Applications
info: [debug] Trying app dir /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS null.simruntime/Contents/Resources/RuntimeRoot/Applications
warn: App is also not at /tmp/Appium-MobileSafari-null.app
error: Could not prepare mobile safari: Error: Couldn't find built in app in its home or temp dir!
```
Since iOS 8.x appium shouldn't do this installation actions for Safari, I guess this is a real appium issue.
Please let me know if I should split this issue into two, describing different bugs (disconnection on real device and unabe to find app on simulator).
  
**Capabilities:**
```java
private static WebDriver createIOSDriver(Device iOSDevice) {
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("platfromName", "iOS");
        capabilities.setCapability("browserName", "Safari");
        capabilities.setCapability("autoWebview", true);
        capabilities.setCapability("deviceName", iOSDevice.getName()); // MWS iPhone 6
        capabilities.setCapability("platfromVersion", iOSDevice.getVersion()); // 8.3
        capabilities.setCapability("udid", iOSDevice.getSerial()); // d154b25d17a9f262251b58f48f3da446dc746415 OPTION COMMENTED ON SIMULATOR RUN

        IOSDriver driver = new IOSDriver(getUrl(iOSDevice.getRemote()), capabilities);
        return driver;
    }
```

**ios_webkit_debug_proxy full log:**
```
$ios_webkit_debug_proxy -u d154b25d17a9f262251b58f48f3da446dc746415:27753
Connected :27753 to MWS iPhone 6 M0164 (d154b25d17a9f262251b58f48f3da446dc746415)
Invalid message _rpc_applicationUpdated: <dict>
	<key>WIRApplicationIdentifierKey</key>
	<string>PID:327</string>
	<key>WIRIsApplicationProxyKey</key>
	<true/>
	<key>WIRApplicationNameKey</key>
	<string></string>
	<key>WIRApplicationBundleIdentifierKey</key>
	<string>com.apple.WebKit.WebContent</string>
	<key>WIRIsApplicationActiveKey</key>
	<integer>0</integer>
	<key>WIRHostApplicationIdentifierKey</key>
	<string>PID:325</string>
</dict>
Disconnected :27753 from MWS iPhone 6 M0164 (d154b25d17a9f262251b58f48f3da446dc746415)
```

**Appium full log on real device:**
```
info: Welcome to Appium v1.3.7 (REV 2f9f0ba52d4cea52b4a82286400666bffe2d35a7)
info: Appium REST http interface listener started on 0.0.0.0:4723
info: Console LogLevel: debug
info: --> POST /wd/hub/session {"desiredCapabilities":{"platfromName":"iOS","browserName":"Safari","autoWebview":true,"udid":"d154b25d17a9f262251b58f48f3da446dc746415","platformName":"iOS","deviceName":"MWS iPhone 6","platfromVersion":"8.3"}}
info: Client User-Agent string: Apache-HttpClient/4.3.4 (java 1.5)
info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : platfromName, platfromVersion
info: [debug] Configuring Safari session
info: [debug] Using local .zip from command line: /Users/local_adm/Documents/playtech/appium/build/SafariLauncher/SafariLauncher.zip
info: [debug] Copying local zip to tmp dir
info: [debug] /Users/local_adm/Documents/playtech/appium/build/SafariLauncher/SafariLauncher.zip copied to /var/folders/mr/q9hz80r94xx39p6w_2qyshgm0000gp/T/115316-1408-zzhqbn/appium-app.zip
info: [debug] Unzipping /var/folders/mr/q9hz80r94xx39p6w_2qyshgm0000gp/T/115316-1408-zzhqbn/appium-app.zip
info: [debug] Testing zip archive: /var/folders/mr/q9hz80r94xx39p6w_2qyshgm0000gp/T/115316-1408-zzhqbn/appium-app.zip
info: [debug] Zip archive tested clean
info: [debug] Unzip successful
info: [debug] Using locally extracted app: /var/folders/mr/q9hz80r94xx39p6w_2qyshgm0000gp/T/115316-1408-zzhqbn/submodules/SafariLauncher/build/Release-iphoneos/SafariLauncher.app
info: [debug] Creating new appium session 84e229ee-2bcb-409f-a691-fc3578d66877
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Auto-detecting iOS udid...
info: [debug] Not auto-detecting udid, running on sim
info: [debug] Could not parse plist file (as binary) at /var/folders/mr/q9hz80r94xx39p6w_2qyshgm0000gp/T/115316-1408-zzhqbn/submodules/SafariLauncher/build/Release-iphoneos/SafariLauncher.app/en.lproj/Localizable.strings
info: Will try to parse the plist file as XML
info: [debug] Could not parse plist file (as XML) at /var/folders/mr/q9hz80r94xx39p6w_2qyshgm0000gp/T/115316-1408-zzhqbn/submodules/SafariLauncher/build/Release-iphoneos/SafariLauncher.app/en.lproj/Localizable.strings
warn: Could not parse app Localizable.strings assuming it doesn't exist
info: [debug] Getting bundle ID from app
info: [debug] Parsed app Info.plist (as binary)
info: [debug] Creating instruments
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/local_adm/Library/Application Support/appium/bootstrap
info: [debug] Dynamic env: {"nodePath":"/usr/local/Cellar/node/0.12.2_1/bin/node","commandProxyClientPath":"/Users/local_adm/Documents/playtech/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":true,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"grouped"}
...o: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
info: [debug] Dynamic bootstrap path: /Users/local_adm/Library/Application Support/appium/bootstrap/bootstrap-7c978884f7ff710b.js
info: [debug] Creating or overwritting dynamic bootstrap: /Users/local_adm/Library/Application Support/appium/bootstrap/bootstrap-7c978884f7ff710b.js
info: [debug] Attempting iOS device log capture via libimobiledevice idevicesyslog
info: [debug] Creating iDevice object with udid d154b25d17a9f262251b58f48f3da446dc746415
info: [debug] Not starting command proxy since we're expecting that Instruments won't be able to talk to it anyway
info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
info: Launching instruments
info: [debug] Attempting to run app on real device with UDID d154b25d17a9f262251b58f48f3da446dc746415
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w d154b25d17a9f262251b58f48f3da446dc746415 com.bytearc.SafariLauncher -e UIASCRIPT "/Users/local_adm/Library/Application Support/appium/bootstrap/bootstrap-7c978884f7ff710b.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {}
info: [debug] And launch timeouts (in ms): {"global":90000}
info: [debug] [INST STDERR] 2015-04-16 14:32:03.165 instruments[1425:13187] WebKit Threading Violation - initial use of WebKit from a secondary thread.
info: [debug] [INST] 2015-04-16 11:32:24 +0000 Error: Script threw an uncaught JavaScript error: Communication to the host was lost, and the task performed on host was terminated due to timeout. on line 2721 of bootstrap-7c978884f7ff710b.js
info: [debug] [INST] 2015-04-16 11:32:24 +0000 Stopped: Script was stopped by the user
info: [debug] [INST STDERR] 2015-04-16 14:32:24.643 instruments[1425:13193] Attempting to set event horizon when core is not engaged, request ignored
info: [debug] [INST STDERR] 2015-04-16 14:32:24.643 instruments[1425:13193] Attempting to set event horizon when core is not engaged, request ignored
info: [debug] [INST] Instruments Trace Complete (Duration : 21.299273s; Output : /tmp/appium-instruments/instrumentscli0.trace)
info: [debug] [INSTSERVER] Instruments exited with code 0
info: [debug] Cleaning up after instruments exit
info: [debug] Not worrying about instruments exit since we're using SafariLauncher
info: [debug] Instruments launched. Starting poll loop for new commands.
info: [debug] Not setting bootstrap config because we're on SafariLauncher
info: [debug] Not setting initial orientation because we're on SafariLauncher
info: [debug] Setting auto webview
info: [debug] Waiting for 6000 ms before navigating to view.
info: [debug] Navigating to most recently opened webview
info: [debug] [REMOTE] Getting WebKitRemoteDebugger pageArray
error: [REMOTE] Could not connect to WebKitRemoteDebugger server
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: Could not navigate to webview! Err: Error: connect ECONNREFUSED
info: [debug] Error: Could not navigate to webview! Err: Error: connect ECONNREFUSED
    at [object Object].<anonymous> (/Users/local_adm/Documents/playtech/appium/lib/devices/ios/ios.js:1644:12)
    at /Users/local_adm/Documents/playtech/appium/lib/devices/ios/ios.js:1548:21
    at [object Object].<anonymous> (/Users/local_adm/Documents/playtech/appium/lib/devices/ios/ios.js:1535:21)
    at [object Object].<anonymous> (/Users/local_adm/Documents/playtech/appium/lib/devices/ios/ios-hybrid.js:62:21)
    at [object Object].<anonymous> (/Users/local_adm/Documents/playtech/appium/lib/devices/ios/webkit-remote-debugger.js:73:14)
    at ClientRequest.<anonymous> (/Users/local_adm/Documents/playtech/appium/node_modules/underscore/underscore.js:890:21)
    at ClientRequest.emit (events.js:107:17)
    at Socket.socketErrorListener (_http_client.js:271:9)
    at Socket.emit (events.js:107:17)
    at net.js:459:14
    at process._tickDomainCallback (node.js:381:11)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Could not navigate to webview! Err: Error: connect ECONNREFUSED)","origValue":"Could not navigate to webview! Err: Error: connect ECONNREFUSED"},"sessionId":null}
info: <-- POST /wd/hub/session 500 33887.641 ms - 248 
warn: Instruments socket client never checked in; timing out (global)
info: [debug] Killall instruments
```

**Appium full log on simulator:**
```
info: Welcome to Appium v1.3.7 (REV 2f9f0ba52d4cea52b4a82286400666bffe2d35a7)
info: Appium REST http interface listener started on 0.0.0.0:4723
info: Console LogLevel: debug
info: --> POST /wd/hub/session {"desiredCapabilities":{"browserName":"Safari","platfromName":"iOS","autoWebview":true,"platformName":"iOS","deviceName":"iPhone 6","platfromVersion":"8.3"}}
info: Client User-Agent string: Apache-HttpClient/4.3.4 (java 1.5)
info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : platfromName, platfromVersion
info: [debug] Configuring Safari session
info: [debug] Creating new appium session 2b4870a8-9464-401f-b661-a34fe69ddbc4
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode version
info: [debug] Setting iOS SDK Version
info: [debug] iOS SDK Version set to 8.3
info: [debug] Checking whether instruments supports our device string
info: [debug] Getting list of devices instruments supports
info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.3","iOSSDKVersion":"8.3","deviceName":"iPhone 6","platformVersion":null}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone 6 (8.3 Simulator)'
info: [debug] iOS sim UDID is 9DBBA4B8-DDB7-4898-BB84-83C5DD2F731D
info: [debug] Trying to use mobile safari, version null
info: [debug] Looking for built in app MobileSafari
info: [debug] Unable to find app dir /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulatornull.sdk/Applications
info: [debug] Trying app dir /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS null.simruntime/Contents/Resources/RuntimeRoot/Applications
warn: App is also not at /tmp/Appium-MobileSafari-null.app
error: Could not prepare mobile safari: Error: Couldn't find built in app in its home or temp dir!
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: Couldn't find built in app in its home or temp dir!
info: [debug] Error: Couldn't find built in app in its home or temp dir!
    at /Users/local_adm/Documents/playtech/appium/lib/devices/ios/simulator.js:451:21
    at FSReqWrap.oncomplete (fs.js:95:15)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Couldn't find built in app in its home or temp dir!)","origValue":"Couldn't find built in app in its home or temp dir!"},"sessionId":null}
info: <-- POST /wd/hub/session 500 564.395 ms - 224
```

**Comment by vasudarch** [comment]
not able to run safari script due to this issue

**Comment by Jonahss** [comment]
This should be fixed in version 1.4  You can try the 1.4 branch to check for yourself

**Comment by tfcardoso** [comment]
info: [debug] [INST STDERR] 2015-04-16 14:32:24.643 instruments[1425:13193] Attempting to set event horizon when core is not engaged, request ignored
    info: [debug] [INST STDERR] 2015-04-16 14:32:24.643 instruments[1425:13193] Attempting to set event horizon when core is not engaged, request ignored

This is happening to me also with ios8.3 / xcode6.3/ appium 1.4, but it is not in all tests

**Comment by ivasylchenko** [comment]
Cannot confirm issue is gone, because I've faced with another issue now after upgrading appium (to 1.4.0), java (to 1.8.0_25) and ios_webkit_debug_proxy today to latest: 
```
Failed to start Instruments daemon on 'MWS iPhone 6 M0164 (8.3)' (The service is invalid.) 
Waiting for device to boot...
```

**Comment by Jonahss** [comment]
@ivasylchenko You need to open Xcode while the device is connected via USB.
UiAutomation needs to be enabled in the Developer Settings on the device, and when you restart a device those settings disappear until you plug it into xcode (or theres a libimobiledevice tool to mount developer image or something)

**Comment by ivasylchenko** [comment]
@Jonahss That helped, thanks!
But another issue discovered:
```

warn: Could not any webviews yet, refreshing/retrying
```

Is it also known isue and I forgot to configure something?

**Comment by huangzhichong** [comment]
@ivasylchenko i met the same issue about 'Could not navigate to webview'

it was resolved by 

  *  adding more waiting time after launching SafariLaunche

  *  start ios-webkit-debug-proxy from appium's source, 
       
        node bin/ios-webkit-debug-proxy-launcher.js -c d154b25d17a9f262251b58f48f3da446dc746415:27753
