### ISSUE TITLE
Error: Instruments never checked, running tests against IOS real device using APPIUM

### ISSUE THREAD

**Issue by thaiching** [appium/appium#4972]
Hi,
   I am trying to execute cucumber ruby tests on iOS real device using Appium and I'm seeing the following error in the Appium logs. 

FYI, the SafariLauncher app is launched and the Safari browser navigates to apple.com website but after that it does nothing instead of navigating to the base URL

I am using

Mac OS X 10.9.5
Appium latest source
IOS 7.1.1
Xcode 6.2

Here is the console logs:

info: Welcome to Appium v1.3.7 (REV b0e85af63e6d78684416d2df92c90f38fc56cc0f)
info: Appium REST http interface listener started on 0.0.0.0:4723
info: [debug] Non-default server args: {"udid":"a25698e035ca02f6586ceeda03aa6ae0ac5e2708"}
info: Console LogLevel: debug
info: --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"iOS","deviceName":"Michal Kot's iPhone","udid":"a25698e035ca02f6586ceeda03aa6ae0ac5e2708","app":"Safari","bundleId":"SafariLauncher","version":"7.1.1","browserName":"Safari"}}
info: Client User-Agent string: Ruby
info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : version
info: [debug] Configuring Safari session
info: [debug] Using local .zip from desired caps: /Users/tchong/appium/build/SafariLauncher/SafariLauncher.zip
info: [debug] Copying local zip to tmp dir
info: [debug] /Users/tchong/appium/build/SafariLauncher/SafariLauncher.zip copied to /var/folders/b9/8b7t1gz538j6714r67890tnjd51cz8/T/115321-5588-plt4uf/appium-app.zip
info: [debug] Unzipping /var/folders/b9/8b7t1gz538j6714r67890tnjd51cz8/T/115321-5588-plt4uf/appium-app.zip
info: [debug] Testing zip archive: /var/folders/b9/8b7t1gz538j6714r67890tnjd51cz8/T/115321-5588-plt4uf/appium-app.zip
info: [debug] Zip archive tested clean
info: [debug] Unzip successful
info: [debug] Using locally extracted app: /var/folders/b9/8b7t1gz538j6714r67890tnjd51cz8/T/115321-5588-plt4uf/submodules/SafariLauncher/build/Release-iphoneos/SafariLauncher.app
info: [debug] Creating new appium session 12ee98cd-47e9-4e39-8fdb-ef133ad73309
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Auto-detecting iOS udid...
info: [debug] Not auto-detecting udid, running on sim
info: [debug] Could not parse plist file (as binary) at /var/folders/b9/8b7t1gz538j6714r67890tnjd51cz8/T/115321-5588-plt4uf/submodules/SafariLauncher/build/Release-iphoneos/SafariLauncher.app/en.lproj/Localizable.strings
info: Will try to parse the plist file as XML
info: [debug] Could not parse plist file (as XML) at /var/folders/b9/8b7t1gz538j6714r67890tnjd51cz8/T/115321-5588-plt4uf/submodules/SafariLauncher/build/Release-iphoneos/SafariLauncher.app/en.lproj/Localizable.strings
warn: Could not parse app Localizable.strings assuming it doesn't exist
info: [debug] Creating instruments
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/tchong/Library/Application Support/appium/bootstrap
info: [debug] Dynamic env: {"nodePath":"/usr/local/bin/node","commandProxyClientPath":"/Users/tchong/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":true,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"grouped"}
...o: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
info: [debug] Dynamic bootstrap path: /Users/tchong/Library/Application Support/appium/bootstrap/bootstrap-192d25672fe371e8.js
info: [debug] Reusing dynamic bootstrap: /Users/tchong/Library/Application Support/appium/bootstrap/bootstrap-192d25672fe371e8.js
info: [debug] Attempting iOS device log capture via libimobiledevice idevicesyslog
info: [debug] Creating iDevice object with udid a25698e035ca02f6586ceeda03aa6ae0ac5e2708
info: [debug] Not starting command proxy since we're expecting that Instruments won't be able to talk to it anyway
info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
info: Launching instruments
info: [debug] Attempting to run app on real device with UDID a25698e035ca02f6586ceeda03aa6ae0ac5e2708
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w a25698e035ca02f6586ceeda03aa6ae0ac5e2708 SafariLauncher -e UIASCRIPT "/Users/tchong/Library/Application Support/appium/bootstrap/bootstrap-192d25672fe371e8.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {}
info: [debug] And launch timeouts (in ms): {"global":90000}
info: [debug] [INST STDERR] 2015-04-21 09:50:55.254 instruments[5606:1307] WebKit Threading Violation - initial use of WebKit from a secondary thread.
info: <-- POST /wd/hub/session - - ms - - 
undefined
warn: Instruments socket client never checked in; timing out (global)
info: [debug] Killall instruments
info: [debug] [INSTSERVER] Instruments exited with code null
info: [debug] Killall instruments
info: [debug] Instruments never checked in
info: [debug] Attempting to retry launching instruments, this is retry #1
info: [debug] Killall iOS Simulator
info: Launching instruments
info: [debug] Attempting to run app on real device with UDID a25698e035ca02f6586ceeda03aa6ae0ac5e2708
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w a25698e035ca02f6586ceeda03aa6ae0ac5e2708 SafariLauncher -e UIASCRIPT "/Users/tchong/Library/Application Support/appium/bootstrap/bootstrap-192d25672fe371e8.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {}
info: [debug] And launch timeouts (in ms): {"global":90000}
info: [debug] [INST STDERR] 2015-04-21 09:52:30.243 instruments[5613:2307] WebKit Threading Violation - initial use of WebKit from a secondary thread.
warn: Instruments socket client never checked in; timing out (global)
info: [debug] Killall instruments
info: [debug] [INSTSERVER] Instruments exited with code null
info: [debug] Killall instruments
info: [debug] Instruments never checked in
info: [debug] Attempting to retry launching instruments, this is retry #2
info: [debug] Killall iOS Simulator
info: Launching instruments
info: [debug] Attempting to run app on real device with UDID a25698e035ca02f6586ceeda03aa6ae0ac5e2708
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w a25698e035ca02f6586ceeda03aa6ae0ac5e2708 SafariLauncher -e UIASCRIPT "/Users/tchong/Library/Application Support/appium/bootstrap/bootstrap-192d25672fe371e8.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {}
info: [debug] And launch timeouts (in ms): {"global":90000}
info: [debug] [INST STDERR] 2015-04-21 09:54:05.230 instruments[5682:2307] WebKit Threading Violation - initial use of WebKit from a secondary thread.
warn: Instruments socket client never checked in; timing out (global)
info: [debug] Killall instruments
info: [debug] [INSTSERVER] Instruments exited with code null
info: [debug] Killall instruments
info: [debug] Instruments never checked in
info: [debug] Attempting to retry launching instruments, this is retry #3
info: [debug] Killall iOS Simulator
info: Launching instruments
info: [debug] Attempting to run app on real device with UDID a25698e035ca02f6586ceeda03aa6ae0ac5e2708
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w a25698e035ca02f6586ceeda03aa6ae0ac5e2708 SafariLauncher -e UIASCRIPT "/Users/tchong/Library/Application Support/appium/bootstrap/bootstrap-192d25672fe371e8.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {}
info: [debug] And launch timeouts (in ms): {"global":90000}
info: [debug] [INST STDERR] 2015-04-21 09:55:40.229 instruments[5691:1307] WebKit Threading Violation - initial use of WebKit from a secondary thread.
warn: Instruments socket client never checked in; timing out (global)
info: [debug] Killall instruments
info: [debug] [INSTSERVER] Instruments exited with code null
info: [debug] Killall instruments
info: [debug] Instruments never checked in
info: [debug] We exceeded the number of retries allowed for instruments to successfully start; failing launch
info: [debug] Stopping iOS log capture
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killing any other simulator daemons
info: [debug] Killall iOS Simulator
info: [debug] On a real device; cannot clean device state
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: Instruments never checked in
info: [debug] Error: Instruments never checked in
    at [object Object].Instruments.onInstrumentsExit (/Users/tchong/appium/node_modules/appium-instruments/lib/instruments.js:436:31)
    at [object Object].<anonymous> (/Users/tchong/appium/node_modules/appium-instruments/lib/instruments.js:353:12)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Instruments never checked in)","origValue":"Instruments never checked in"},"sessionId":null}

**Comment by Jonahss** [comment]
Can you try the latest code? this has been upgraded very recently

**Comment by sebv** [comment]
Closing, no activity, may be reopened if needed.
