### ISSUE TITLE
permission to start activity denied even after changing activity name

### ISSUE THREAD

**Issue by chandan1989** [appium/appium#4988]
org.openqa.selenium.SessionNotCreatedException: A new session could not be created. (Original error: Permission to start activity denied.) (WARNING: The server did not provide any stacktrace information)

Even though I change the permission of apk file. Once I will run the test case it will change the permission to (-rwx--x--x to -rw-r--r--)

**Comment by imurchie** [comment]
Can you provide the Appium server logs? I don't think this is a local permissions issue, but the activity being used to start does not have permission to start on the device.

**Comment by chandan1989** [comment]
Hi I am trying to automate lync 2013 app but I am getting this error

Package Name : com.microsoft.office.lync15

Activity name : com.microsoft.office.lync.ui.splash.EntryPoint

If I run with above information than it is giving this error.

 FAILED CONFIGURATION: @BeforeMethod testClassSetup

org.openqa.selenium.SessionNotCreatedException: A new session could not be created. (Original error: com.microsoft.office.lync15/com.microsoft.office.lync.ui.splash.EntryPoint never started. Current: com.microsoft.office.lync15/com.microsoft.office.lync.ui.login.SigninActivity) (WARNING: The server did not provide any stacktrace information)

Command duration or timeout: 43.83 seconds

Build info: version: '2.45.0', revision: '32a636c', time: '2015-03-05 22:01:35'

System info: host: ‘Chandans-Mac-mini.local', ip: '10.227.132.162', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10', java.version: '1.7.0_75'

Driver info: io.appium.java_client.android.AndroidDriver

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)

at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

at java.lang.reflect.Constructor.newInstance(Constructor.java:526)

at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)

at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)

at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)

at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:176)

at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:240)

at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:126)

at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:153)

at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:107)

at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:40)

at com.ckb.test.BasePage.startDriver(BasePage.java:61)

at com.ckb.test.AndroidLyncTest.testClassSetup(AndroidLyncTest.java:15)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:606)

at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)

at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)

at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)

at org.testng.internal.Invoker.invokeMethod(Invoker.java:653)

at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)

at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)

at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)

at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)

at org.testng.TestRunner.privateRun(TestRunner.java:767)

at org.testng.TestRunner.run(TestRunner.java:617)

at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)

at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)

at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)

at org.testng.SuiteRunner.run(SuiteRunner.java:240)

at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)

at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)

at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)

at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)

at org.testng.TestNG.run(TestNG.java:1057)

at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)

at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)

at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)



SKIPPED CONFIGURATION: @AfterMethod tearDown

SKIPPED: verifyLync



===============================================

    Default test

    Tests run: 1, Failures: 0, Skips: 1

    Configuration Failures: 1, Skips: 1

===============================================





===============================================

Default suite

Total tests run: 1, Failures: 0, Skips: 1

Configuration Failures: 1, Skips: 1

===============================================



[TestNG] Time taken by [FailedReporter passed=0 failed=0 skipped=0]: 24 ms

[TestNG] Time taken by org.testng.reporters.EmailableReporter2@30563456: 8 ms

[TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@512f0124: 30 ms

[TestNG] Time taken by org.testng.reporters.jq.Main@5175f214: 39 ms

[TestNG] Time taken by org.testng.reporters.JUnitReportReporter@c1d5a3: 6 ms

[TestNG] Time taken by org.testng.reporters.XMLReporter@68cd6d94: 31 ms



or else if I change activity name

Activity Nmae : com.microsoft.office.lync.ui.login.SigninActivity

it is giving the following error


FAILED CONFIGURATION: @BeforeMethod testClassSetup
org.openqa.selenium.SessionNotCreatedException: A new session could not be created. (Original error: Permission to start activity denied.) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 10.52 seconds
Build info: version: '2.45.0', revision: '32a636c', time: '2015-03-05 22:01:35'
System info: host: ‘Chandans-Mac-mini.local', ip: '10.227.132.162', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10', java.version: '1.7.0_75'
Driver info: io.appium.java_client.android.AndroidDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:176)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:240)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:126)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:153)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:107)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:40)
	at com.ckb.test.BasePage.startDriver(BasePage.java:61)
	at com.ckb.test.AndroidLyncTest.testClassSetup(AndroidLyncTest.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:653)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)

SKIPPED CONFIGURATION: @AfterMethod tearDown
SKIPPED: verifyLync

===============================================
    Default test
    Tests run: 1, Failures: 0, Skips: 1
    Configuration Failures: 1, Skips: 1
===============================================


===============================================
Default suite
Total tests run: 1, Failures: 0, Skips: 1
Configuration Failures: 1, Skips: 1
===============================================

[TestNG] Time taken by org.testng.reporters.XMLReporter@61917b9e: 34 ms
[TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@ef8e761: 7 ms
[TestNG] Time taken by org.testng.reporters.JUnitReportReporter@72fd5ba8: 26 ms
[TestNG] Time taken by org.testng.reporters.EmailableReporter2@43c83579: 6 ms
[TestNG] Time taken by [FailedReporter passed=0 failed=0 skipped=0]: 4 ms
[TestNG] Time taken by org.testng.reporters.jq.Main@4c583f4c: 32 ms




EVEN IF I CHANGE THE PERMISSION IT IS NOT WORKING

**Comment by imurchie** [comment]
If you could leave the Appium server log that would be most useful.

As it stands, it looks like the wrong activity is starting: `com.microsoft.office.lync15/com.microsoft.office.lync.ui.login.SigninActivity`. What happens if you use that package/activity?

You can also try using the `appWaitPackage` and `appWaitActivity` desired capabilities.

**Comment by sebv** [comment]
Closing, no activity, may be reopened if needed.
