### ISSUE TITLE
org.openqa.selenium.WebDriverException: ERROR running Appium command: undefined is not a function

### ISSUE THREAD

**Issue by akash-chaudhary** [appium/appium#5026]
Appium version -- 1.3.7
iOS(iPAD ) version ---8.1
Firstly --App got launched and then this error was thrown .
Now this error is repetitive as soon as appium is launched.

**Comment by akash-chaudhary** [comment]
TypeError: undefined is not a function
    at serveStatic (/Applications/Appium1.3.7.app/Contents/Resources/node_modules/appium/node_modules/express/node_modules/serve-static/index.js:63:32)
    at Layer.handle [as handle_request] (/Applications/Appium1.3.7.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/layer.js:82:5)
    at trim_prefix (/Applications/Appium1.3.7.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/index.js:302:13)
    at /Applications/Appium1.3.7.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/index.js:270:7
    at Function.proto.process_params (/Applications/Appium1.3.7.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/index.js:321:12)
    at next (/Applications/Appium1.3.7.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/index.js:261:10)
    at favicon (/Applications/Appium1.3.7.app/Contents/Resources/node_modules/appium/node_modules/serve-favicon/index.js:63:7)
    at Layer.handle [as handle_request] (/Applications/Appium1.3.7.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/layer.js:82:5)
    at trim_prefix (/Applications/Appium1.3.7.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/index.js:302:13)
    at /Applications/Appium1.3.7.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/index.js:270:7

**Comment by moizjv** [comment]
@akash-chaudhary can you paste complete log please?

**Comment by akash-chaudhary** [comment]
Sir my this issue has been solved . It was due to incomplete download of appium.
But i am facing a different issue. The issue is related to scrolling through appium.

Sir my iOS mobile app has page which contains TableView and CollectionView . At this page appium driver as well as javaScriptExecutor both are unable to scroll . But at those pages which contain scrollView they both are working fine .No exception is thrown at the time of scrolling.Seems like it scrolls at its end but the end effect is zero...(will it be considered as an appium bug).
 My dependency details are listed below....


macosx -----yosomite
appium version ---- 1.3.7
iPad version-----8.1
xcode version -----6.3

**Comment by akash-chaudhary** [comment]
Thanks for your support earlier.

**Comment by moizjv** [comment]
@akash-chaudhary can you look at [documentaion](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/touch-actions.md) it may solve your issues related to scroll. Also you can try asking at [forum](http://discuss.appium.com) for questions. Closing this issue.
