### ISSUE TITLE
in some cases chromedriver doesn't start because of a Promise error

### ISSUE THREAD

**Issue by jlipps** [appium/appium#5046]
get logs like these:

```
622015-05-04 18:55:26:450 - info: Killing any old chromedrivers, running: ps -ef | grep /home/chef/chromedriver32-sendkeys | grep -v grep |grep -e '--port=9515\(\s.*\)\?$' | awk '{ print $2 }' | xargs kill -15
632015-05-04 18:55:26:461 - error: Unhandled error: TypeError: Object #<Promise> has no method 'nodeify'
64 at [object Object].ChromeAndroid.createSession (/home/chef/appium/lib/devices/android/chrome.js:155:33)
65 at /home/chef/appium/node_modules/async/lib/async.js:610:21
66 at /home/chef/appium/node_modules/async/lib/async.js:249:17
67 at iterate (/home/chef/appium/node_modules/async/lib/async.js:149:13)
68 at /home/chef/appium/node_modules/async/lib/async.js:160:25
69 at /home/chef/appium/node_modules/async/lib/async.js:251:21
70 at /home/chef/appium/node_modules/async/lib/async.js:615:34
71 at [object Object].<anonymous> (/home/chef/appium/lib/devices/android/android.js:542:5)
72 at next (/home/chef/appium/node_modules/async/lib/async.js:801:43)
73 at /home/chef/appium/node_modules/async/lib/async.js:32:16
74 at [object Object].exports.respond (/home/chef/appium/lib/devices/common.js:28:9)
75 at [object Object].<anonymous> (/home/chef/appium/lib/devices/android/android.js:508:16)
76 at [object Object].<anonymous> (/home/chef/appium/lib/devices/android/uiautomator.js:95:9)
77 at Socket.EventEmitter.emit (events.js:95:17)
78 at Socket.<anonymous> (_stream_readable.js:746:14)
79 at Socket.EventEmitter.emit (events.js:92:17)
80 at emitReadable_ (_stream_readable.js:408:10)
81 at emitReadable (_stream_readable.js:404:5)
82 at readableAddChunk (_stream_readable.js:165:9)
83 at Socket.Readable.push (_stream_readable.js:127:10)
84 at TCP.onread (net.js:526:21) context: [POST /wd/hub/session {"desiredCapabilities":{"platformVersion":"4.4","deviceName":"Samsung Galaxy S5 Device","webdriver.remote.quietExceptions":true,"platformName":"Android","proxy":{"proxyAutoconfigUrl":"http://127.0.0.1]
```

**Comment by jlipps** [comment]
this is a bug in node 0.10 only
