### ISSUE TITLE
Android `execute_script("mobile: scroll"` crashes

### ISSUE THREAD

**Issue by cyrilchampier** [appium/appium#5065]
```
info: --> POST /wd/hub/session/dddfbd39-2c9c-468f-b869-29061b105e0c/execute {"script":"mobile: scroll","args":[{"direction":"up"}]}

TypeError: string is not a function
    at androidController.scroll (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/android/android-controller.js:687:3)
    at Object.exports.mobileScroll [as scroll] (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/server/controller.js:639:14)
    at Object.exports.executeMobileMethod (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/server/controller.js:966:22)
    at exports.execute (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/server/controller.js:922:15)
    at Layer.handle [as handle_request] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/layer.js:82:5)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/layer.js:82:5)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/index.js:267:22
    at param (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/index.js:340:14)
```

Because of this line: controller.js:639 
 `req.device.scroll(element, direction, getResponseHandler(req, res));`
that call this function: android-controller.js:686 
`androidController.scroll = function (direction, cb) {`
which lacks the first element argument

**Comment by moizjv** [comment]
This method is not implemented for Android its only for iOS, you should be using [touch api](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/touch-actions.md)
