### ISSUE TITLE
Unable to start appium-Mac OS X-10.3.3

### ISSUE THREAD

**Issue by SathiyaRengarajan** [appium/appium#5074]
> brew install node 
> npm install -g appium  
> npm install wd        
> appium &         
Logs:
Could not find config file: /usr/local/lib/node_modules/appium/.appiumconfig.json; looks like config hasn't been run. Please run reset.sh or appium configure.
error: uncaughtException: Could not find config file: /usr/local/lib/node_modules/appium/.appiumconfig.json; looks like config hasn't been run. Please run reset.sh or appium configure. date=Thu May 07 2015 14:12:06 GMT+0530 (IST), pid=3457, uid=502, gid=20, cwd=/usr/local/lib/node_modules/appium, execPath=/usr/local/Cellar/node/0.12.2_1/bin/node, version=v0.12.2, argv=[node, /usr/local/bin/appium], rss=87052288, heapTotal=70021888, heapUsed=36271280, loadavg=[3.06787109375, 2.2373046875, 2.03369140625], uptime=18977, trace=[column=13, file=/usr/local/lib/node_modules/appium/lib/helpers.js, function=exports.getAppiumConfig, line=317, method=getAppiumConfig, native=false, column=23, file=/usr/local/lib/node_modules/appium/lib/server/main.js, function=null, line=131, method=null, native=false, column=21, file=/usr/local/lib/node_modules/appium/node_modules/async/lib/async.js, function=null, line=610, method=null, native=false, column=17, file=/usr/local/lib/node_modules/appium/node_modules/async/lib/async.js, function=null, line=249, method=null, native=false, column=13, file=/usr/local/lib/node_modules/appium/node_modules/async/lib/async.js, function=iterate, line=149, method=null, native=false, column=9, file=/usr/local/lib/node_modules/appium/node_modules/async/lib/async.js, function=async.eachSeries, line=165, method=eachSeries, native=false, column=13, file=/usr/local/lib/node_modules/appium/node_modules/async/lib/async.js, function=_asyncMap, line=248, method=null, native=false, column=23, file=/usr/local/lib/node_modules/appium/node_modules/async/lib/async.js, function=Object.mapSeries, line=231, method=mapSeries, native=false, column=19, file=/usr/local/lib/node_modules/appium/node_modules/async/lib/async.js, function=Object.async.series, line=608, method=async.series, native=false, column=9, file=/usr/local/lib/node_modules/appium/lib/server/main.js, function=Object.main [as run], line=129, method=main [as run], native=false], stack=[Error: Could not find config file: /usr/local/lib/node_modules/appium/.appiumconfig.json; looks like config hasn't been run. Please run reset.sh or appium configure.,     at exports.getAppiumConfig (/usr/local/lib/node_modules/appium/lib/helpers.js:317:13),     at /usr/local/lib/node_modules/appium/lib/server/main.js:131:23,     at /usr/local/lib/node_modules/appium/node_modules/async/lib/async.js:610:21,     at /usr/local/lib/node_modules/appium/node_modules/async/lib/async.js:249:17,     at iterate (/usr/local/lib/node_modules/appium/node_modules/async/lib/async.js:149:13),     at async.eachSeries (/usr/local/lib/node_modules/appium/node_modules/async/lib/async.js:165:9),     at _asyncMap (/usr/local/lib/node_modules/appium/node_modules/async/lib/async.js:248:13),     at Object.mapSeries (/usr/local/lib/node_modules/appium/node_modules/async/lib/async.js:231:23),     at Object.async.series (/usr/local/lib/node_modules/appium/node_modules/async/lib/async.js:608:19),     at Object.main [as run] (/usr/local/lib/node_modules/appium/lib/server/main.js:129:9)]

**Comment by raldred** [comment]
Have you tried doing what the error say?
cd /usr/local/lib/node_modules/appium/ && ./reset.sh

**Comment by SathiyaRengarajan** [comment]
I am getting error as
/reset.sh: No such file or directory.

**Comment by raldred** [comment]
Ok maybe homebrew doesn't have reset.sh.
try running `appium-doctor`

**Comment by SathiyaRengarajan** [comment]
✔ Xcode is installed at /Applications/Xcode.app/Contents/Developer
✔ Xcode Command Line Tools are installed.
✔ DevToolsSecurity is enabled.
✔ The Authorization DB is set up properly.
✔ Node binary found at /usr/local/bin/node
✔ iOS Checks were successful.

Running Android Checks
✖ ANDROID_HOME is not set
Appium-Doctor detected problems. Please fix and rerun Appium-Doctor.
SR6-SM-PRORT:~ sathiya$

**Comment by amedvedjev** [comment]
try:
 - install Gui client 1.3.6: https://bitbucket.org/appium/appium.app/downloads/appium-1.3.6.dmg
then
 - npm install -g appium@1.3.6

**Comment by SathiyaRengarajan** [comment]
Tried it. This is what i could see in Terminal. Appium GUI is not opening
SR6-SM-PRORT:~ sathiya$ info: Welcome to Appium v1.3.6 (REV 004f52f249d3513809e7d0734d9205d1fec19f8e)
info: Appium REST http interface listener started on 0.0.0.0:4723
info: Console LogLevel: debug

**Comment by Jonahss** [comment]
Well it looks like the appium server is starting then. What's the issue now?
Also, try installing appium again via npm. Version 1.4 is now published.

**Comment by sebv** [comment]
Closing, no activity, may be reopened if needed.
