### ISSUE TITLE
Can't switch from Native to Webview context on real iOS device on Safari

### ISSUE THREAD

**Issue by Makavelic** [appium/appium#5078]
Here's my code:

                changeContext(1); //Switches to webview_1
		
		driver.get("http://www.google.com"); 
		changeContext(0); //Switch to Native Context
		int x=284;
		int y=200;
		TouchAction touchAction = new TouchAction((AppiumDriver)driver)
		.longPress(x,y,100)
		.release();
		touchAction.perform();
		
               //Everything works up until this point.
		changeContext(1); //Switch to webview_1
		
		driver.get("http://www.reddit.com");

Appium Log:
Debugger web socket received data :  {"result":{"result":{"type":"string","value":"complete"},"wasThrown":false},"id":2}
info: [debug] [REMOTE] readyState was complete
info: [debug] [REMOTE] Page is ready, calling onload cbs
info: [debug] Responding to client with success: {"status":0,"value":"","sessionId":"e1ae0c48-dc36-4a96-a613-f0331d546a0a"}
info: <-- POST /wd/hub/session/e1ae0c48-dc36-4a96-a613-f0331d546a0a/url 200 2054.123 ms - 74 {"status":0,"value":"","sessionId":"e1ae0c48-dc36-4a96-a613-f0331d546a0a"}
info: --> POST /wd/hub/session/e1ae0c48-dc36-4a96-a613-f0331d546a0a/context {"name":"NATIVE_APP"}
info: [debug] Attempting to set context to 'NATIVE_APP'
info: [debug] Responding to client with success: {"status":0,"value":"","sessionId":"e1ae0c48-dc36-4a96-a613-f0331d546a0a"}
info: <-- POST /wd/hub/session/e1ae0c48-dc36-4a96-a613-f0331d546a0a/context 200 2.335 ms - 74 {"status":0,"value":"","sessionId":"e1ae0c48-dc36-4a96-a613-f0331d546a0a"}
info: [debug] [REMOTE] Disconnecting from remote debugger

info: --> POST /wd/hub/session/e1ae0c48-dc36-4a96-a613-f0331d546a0a/touch/perform {"actions":[{"action":"longPress","options":{"x":284,"y":200,"duration":100}},{"action":"release","options":{}}]}
info: [debug] Pushing command to appium work queue: "target.touch([{\"touch\":[{\"x\":284,\"y\":200}],\"time\":0.2}])"
info: [debug] Sending command to instruments: target.touch([{"touch":[{"x":284,"y":200}],"time":0.2}])

info: [debug] [INST] 2015-05-07 15:59:43 +0000 Debug: Got new command 3 from instruments: target.touch([{"touch":[{"x":284,"y":200}],"time":0.2}])
info: [debug] [INST] 2015-05-07 15:59:43 +0000 Debug: evaluating target.touch([{"touch":[{"x":284,"y":200}],"time":0.2}])

info: [debug] [INST] 2015-05-07 15:59:43 +0000 Debug: target.touch(__NSCFArray)

info: [debug] Socket data received (25 bytes)

info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":""}
info: [debug] Responding to client with success: {"status":0,"value":"","sessionId":"e1ae0c48-dc36-4a96-a613-f0331d546a0a"}
info: <-- POST /wd/hub/session/e1ae0c48-dc36-4a96-a613-f0331d546a0a/touch/perform 200 1910.272 ms - 74 {"status":0,"value":"","sessionId":"e1ae0c48-dc36-4a96-a613-f0331d546a0a"}

info: --> POST /wd/hub/session/e1ae0c48-dc36-4a96-a613-f0331d546a0a/context {"name":"WEBVIEW_1"}
info: [debug] Attempting to set context to 'WEBVIEW_1'
info: <-- POST /wd/hub/session/e1ae0c48-dc36-4a96-a613-f0331d546a0a/context 500 5.704 ms - 95 
info: --> DELETE /wd/hub/session/e1ae0c48-dc36-4a96-a613-f0331d546a0a {}
info: Shutting down appium session
info: [debug] Stopping ios
info: [debug] Destroying instruments client socket.
info: [debug] Closing socket server.
info: [debug] Instruments socket server was closed
info: [debug] Sending sigterm to instruments
info: [debug] [INST] 2015-05-07 15:59:44 +0000 Debug: evaluation finished
info: [debug] [INST] 2015-05-07 15:59:43 +0000 Stopped: Script was stopped by the user

TypeError: Cannot read property 'disconnect' of null
    at null.<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios-controller.js:1644:26)
    at null.<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios-controller.js:1657:9)
    at iOSController.setContext (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios-controller.js:1672:7)
    at exports.setContext (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/server/controller.js:1005:16)
    at Layer.handle [as handle_request] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/layer.js:82:5)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/layer.js:82:5)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/index.js:267:22
    at param (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/index.js:340:14)

info: [debug] [INST] 2015-05-07 15:59:44 +0000 Debug: responding with:
       2015-05-07 15:59:44 +0000 Debug: Running system command #4: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":""}...

I tested using iOS 8.3, Appium 1.3.7 (and Appium Beta), and Safari using the iso-webkit-debug-proxy from the appium source.

**Comment by Makavelic** [comment]
Duplicate of https://github.com/appium/appium/issues/4825
