### ISSUE TITLE
Unable to run using SafariLauncher on ipad

### ISSUE THREAD

**Issue by ASYB** [appium/appium#5123]
Hi 

Using com.bytearc.SafariLauncher I am unable to install SafariLauncher in Device, forcibly I have to give the bundle Identifile as com.MyCompanyName.SafarilLauncher to install SafariLauncher in my device and While running my scripts I am getting the below error 
info: [debug] Error: Command failed: /bin/sh -c ideviceinstaller -u be9c05c4344748a52f99c75672a4cda4715a44ca -i /var/folders/x9/rbf6yqz137dc3jc89m26zh81n71drv/T/115415-20154-k0wyzl/node_modules/safari-launcher/build/Release-iphoneos/SafariLauncher.app
ERROR: Install failed. Got error "ApplicationVerificationFailed" with code 0xe8008015: Failed to verify code signature of <MIExecutableBundle : path = /private/var/mobile/Library/Caches/com.apple.mobile.installd.staging/temp.0urLtJ/extracted/SafariLauncher.app identifier = com.bytearc.SafariLauncher type = 4> : 0xe8008015 (Signer did not match any installed provisioning profile)

Also please find the complete logs below

34363bcbbc8a:appium z001hgg$ node lib/server/main.js -U be9c05c4344748a52f99c75672a4cda4715a44ca
info: Welcome to Appium v1.4.0 (REV 011215111a4aa33029a1a33ea0417688a9359a72)
info: Appium REST http interface listener started on 0.0.0.0:4723
info: [debug] Non-default server args: {"udid":"be9c05c4344748a52f99c75672a4cda4715a44ca"}
info: Console LogLevel: debug
info: --> POST /wd/hub/session {"desiredCapabilities":{"browserName":"Safari","platformName":"iOS","deviceName":"Automation","platformVersion":"8.1.3"}}
info: Client User-Agent string: Apache-HttpClient/4.3.4 (java 1.5)
info: [debug] Configuring Safari session
info: [debug] Using local .zip from command line: /Users/z001hgg/Documents/shaik/appium/build/SafariLauncher/SafariLauncher.zip
info: [debug] Copying local zip to tmp dir
info: [debug] /Users/z001hgg/Documents/shaik/appium/build/SafariLauncher/SafariLauncher.zip copied to /var/folders/x9/rbf6yqz137dc3jc89m26zh81n71drv/T/115415-20154-k0wyzl/appium-app.zip
info: [debug] Unzipping /var/folders/x9/rbf6yqz137dc3jc89m26zh81n71drv/T/115415-20154-k0wyzl/appium-app.zip
info: [debug] Testing zip archive: /var/folders/x9/rbf6yqz137dc3jc89m26zh81n71drv/T/115415-20154-k0wyzl/appium-app.zip
info: [debug] Zip archive tested clean
info: [debug] Unzip successful
info: [debug] Using locally extracted app: /var/folders/x9/rbf6yqz137dc3jc89m26zh81n71drv/T/115415-20154-k0wyzl/node_modules/safari-launcher/build/Release-iphoneos/SafariLauncher.app
info: [debug] Creating new appium session ca114a2e-5b90-4d9e-aeff-53348075860a
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Auto-detecting iOS udid...
info: [debug] Not auto-detecting udid, running on sim
info: [debug] Could not parse plist file (as binary) at /var/folders/x9/rbf6yqz137dc3jc89m26zh81n71drv/T/115415-20154-k0wyzl/node_modules/safari-launcher/build/Release-iphoneos/SafariLauncher.app/en.lproj/Localizable.strings
info: Will try to parse the plist file as XML
info: [debug] Could not parse plist file (as XML) at /var/folders/x9/rbf6yqz137dc3jc89m26zh81n71drv/T/115415-20154-k0wyzl/node_modules/safari-launcher/build/Release-iphoneos/SafariLauncher.app/en.lproj/Localizable.strings
warn: Could not parse app Localizable.strings assuming it doesn't exist
info: [debug] Getting bundle ID from app
info: [debug] Parsed app Info.plist (as binary)
info: [debug] Creating instruments
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/z001hgg/Library/Application Support/appium/bootstrap
info: [debug] Dynamic env: {"nodePath":"/usr/local/Cellar/node/0.12.0/bin/node","commandProxyClientPath":"/Users/z001hgg/Documents/shaik/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"grouped"}
...o: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
info: [debug] Dynamic bootstrap path: /Users/z001hgg/Library/Application Support/appium/bootstrap/bootstrap-50d7e0b7dc4c623b.js
info: [debug] Reusing dynamic bootstrap: /Users/z001hgg/Library/Application Support/appium/bootstrap/bootstrap-50d7e0b7dc4c623b.js
info: [debug] Attempting iOS device log capture via libimobiledevice idevicesyslog
info: [debug] Creating iDevice object with udid be9c05c4344748a52f99c75672a4cda4715a44ca
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: Command failed: /bin/sh -c ideviceinstaller -u be9c05c4344748a52f99c75672a4cda4715a44ca -i /var/folders/x9/rbf6yqz137dc3jc89m26zh81n71drv/T/115415-20154-k0wyzl/node_modules/safari-launcher/build/Release-iphoneos/SafariLauncher.app
ERROR: Install failed. Got error "ApplicationVerificationFailed" with code 0xe8008015: Failed to verify code signature of <MIExecutableBundle : path = /private/var/mobile/Library/Caches/com.apple.mobile.installd.staging/temp.0urLtJ/extracted/SafariLauncher.app identifier = com.bytearc.SafariLauncher type = 4> : 0xe8008015 (Signer did not match any installed provisioning profile)

info: [debug] Error: Command failed: /bin/sh -c ideviceinstaller -u be9c05c4344748a52f99c75672a4cda4715a44ca -i /var/folders/x9/rbf6yqz137dc3jc89m26zh81n71drv/T/115415-20154-k0wyzl/node_modules/safari-launcher/build/Release-iphoneos/SafariLauncher.app
ERROR: Install failed. Got error "ApplicationVerificationFailed" with code 0xe8008015: Failed to verify code signature of <MIExecutableBundle : path = /private/var/mobile/Library/Caches/com.apple.mobile.installd.staging/temp.0urLtJ/extracted/SafariLauncher.app identifier = com.bytearc.SafariLauncher type = 4> : 0xe8008015 (Signer did not match any installed provisioning profile)

    at ChildProcess.exithandler (child_process.js:744:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Command failed: /bin/sh -c ideviceinstaller -u be9c05c4344748a52f99c75672a4cda4715a44ca -i /var/folders/x9/rbf6yqz137dc3jc89m26zh81n71drv/T/115415-20154-k0wyzl/node_modules/safari-launcher/build/Release-iphoneos/SafariLauncher.app\nERROR: Install failed. Got error \"ApplicationVerificationFailed\" with code 0xe8008015: Failed to verify code signature of <MIExecutableBundle : path = /private/var/mobile/Library/Caches/com.apple.mobile.installd.staging/temp.0urLtJ/extracted/SafariLauncher.app identifier = com.bytearc.SafariLauncher type = 4> : 0xe8008015 (Signer did not match any installed provisioning profile)\n)","killed":false,"code":128,"signal":null,"cmd":"/bin/sh -c ideviceinstaller -u be9c05c4344748a52f99c75672a4cda4715a44ca -i /var/folders/x9/rbf6yqz137dc3jc89m26zh81n71drv/T/115415-20154-k0wyzl/node_modules/safari-launcher/build/Release-iphoneos/SafariLauncher.app","origValue":"Command failed: /bin/sh -c ideviceinstaller -u be9c05c4344748a52f99c75672a4cda4715a44ca -i /var/folders/x9/rbf6yqz137dc3jc89m26zh81n71drv/T/115415-20154-k0wyzl/node_modules/safari-launcher/build/Release-iphoneos/SafariLauncher.app\nERROR: Install failed. Got error \"ApplicationVerificationFailed\" with code 0xe8008015: Failed to verify code signature of <MIExecutableBundle : path = /private/var/mobile/Library/Caches/com.apple.mobile.installd.staging/temp.0urLtJ/extracted/SafariLauncher.app identifier = com.bytearc.SafariLauncher type = 4> : 0xe8008015 (Signer did not match any installed provisioning profile)\n"},"sessionId":null}
info: <-- POST /wd/hub/session 500 3279.900 ms - 1619

**Comment by ASYB** [comment]
Any updates please ...

**Comment by ASYB** [comment]
Working fine now, hence closing
