### ISSUE TITLE
Set the orientation, but app refused to rotate

### ISSUE THREAD

**Issue by AlexTrofimchik** [appium/appium#5172]
Hi guys!

I'm trying to change device orientation using AppiumDriver#rotate(ScreenOrientation orientation) and have got an exception. This is stack trace: 
```java
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 2.06 seconds
Build info: version: '2.42.2', revision: '6a6995d31c7c56c340d6f45a76976d43506cd6cc', time: '2014-06-03 10:52:47'
System info: host: 'mypc', ip: '192.168.56.1', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.7.0_67'
Session ID: f0fb1f4a-19f8-4e85-bd61-4a90b619e399
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{tags=Android, platform=LINUX, app=D:\WORK\apk-repo\myapp.apk, javascriptEnabled=true, browserName=Android, networkConnectionEnabled=true, rotatable=true, noSign=true, desired={tags=Android, newCommandTimeout=300, app=D:\WORK\nativeautomation\target\apk-repo\RewardsAmazon-debug.apk, fullReset=true, deviceName=Android, platformName=Android, appiumVersion=1.4.0, name=testDeviceRotation: , noSign=true, rotatable=true, language=en, device-orientation=portrait}, locationContextEnabled=false, newCommandTimeout=300, platformVersion=5.1, databaseEnabled=false, fullReset=true, deviceName=02c99365e077218a, platformName=Android, appiumVersion=1.4.0, webStorageEnabled=false, name=testDeviceRotation: , language=en, warnings={}, takesScreenshot=true, device-orientation=portrait}]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:180)
	at io.appium.java_client.AppiumDriver.rotate(AppiumDriver.java:556)
	at com.mycomp.util.DeviceUtil.rotateDevice(DeviceUtil.java:19)
```

And this is Appium logs:

```
> info: --> GET /wd/hub/session/f0fb1f4a-19f8-4e85-bd61-4a90b619e399/orientation {}
> info: [debug] Pushing command to appium work queue: ["orientation",{}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"orientation","params":{}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: orientation
> info: [debug] [BOOTSTRAP] [debug] Current rotation: ROTATION_0
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":"PORTRAIT"}
> info: [debug] Responding to client with success: {"status":0,"value":"PORTRAIT","sessionId":"f0fb1f4a-19f8-4e85-bd61-4a90b619e399"}
> info: <-- GET /wd/hub/session/f0fb1f4a-19f8-4e85-bd61-4a90b619e399/orientation 200 11.847 ms - 82 {"status":0,"value":"PORTRAIT","sessionId":"f0fb1f4a-19f8-4e85-bd61-4a90b619e399"}
> info: --> POST /wd/hub/session/f0fb1f4a-19f8-4e85-bd61-4a90b619e399/orientation {"orientation":"LANDSCAPE"}
> info: [debug] Pushing command to appium work queue: ["orientation",{"orientation":"LANDSCAPE"}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"orientation","params":{"orientation":"LANDSCAPE"}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: orientation
> info: [debug] [BOOTSTRAP] [debug] Desired orientation: LANDSCAPE
> info: [debug] [BOOTSTRAP] [debug] Current rotation: ROTATION_0
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":13,"value":"Set the orientation, but app refused to rotate."}
> info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command.","origValue":"Set the orientation, but app refused to rotate."},"sessionId":"f0fb1f4a-19f8-4e85-bd61-4a90b619e399"}
> info: <-- POST /wd/hub/session/f0fb1f4a-19f8-4e85-bd61-4a90b619e399/orientation 500 2055.831 ms - 216 
```

I have tested orientation changes with Appium 1.3.4, 1.3.7 and 1.4.0. java_client version - 2.2.0
I have tried everything I found on the web:
- use the driver as AndroidDriver
- cast the driver to Rotatable
- convert the driver to AugmentedDriver (also cast as Rotatable)

And all the time I get the same exception.

**Comment by imurchie** [comment]
Is this a real device or an emulator?

**Comment by AlexTrofimchik** [comment]
The issue reproduced on both device and emulator.

Also, maybe it would be helpful, this is Activity declaration in AndroidManifest.xml:
```java
<activity
    android:name=".RootActivity"
    android:label="@string/app_name"
    android:screenOrientation="portrait"
    android:theme="@style/customTheme"
    android:windowSoftInputMode="adjustPan" >
</activity>
```

Also I have tried to test app without **android:screenOrientation="portrait"**

**Comment by sebv** [comment]
Similar issue here: https://discuss.appium.io/t/android-set-the-orientation-but-app-refused-to-rotate/3200/3
Could it be the app which is blocking rotation?

**Comment by sebv** [comment]
Closing, likely to be app specific, may be reopened as needed.

**Comment by shaswat5** [comment]
@imurchie   ::

Is this a real device or an emulator?
--

Yes it is real device please help me i am also getting same issues
