### ISSUE TITLE
Cannot call method 'start' of null

### ISSUE THREAD

**Issue by ghost** [appium/appium#5194]
Hi!

When we are testing the selendroid-test-app for a longer time, the connection to the AVD dies after a indeterminate period of time. The hub is getting full with requests and the tests won't be executed anymore.

My enviroment:
Appium: 1.3.4.1
Android version: 4.4.2
Writing the tests with C# using the WebDriver.

Follwoing error throws the appium log:
error: Unhandled error: TypeError: Cannot call method 'start' of null
    at async.series.didLaunch (C:\Users\Administrator\Documents\Android_install_tools_native_apps\Appium\node_modules\appium\lib\devices\android\android.js:115:37)
    at C:\Users\Administrator\Documents\Android_install_tools_native_apps\Appium\node_modules\appium\node_modules\async\lib\async.js:610:21
    at C:\Users\Administrator\Documents\Android_install_tools_native_apps\Appium\node_modules\appium\node_modules\async\lib\async.js:249:17
    at iterate (C:\Users\Administrator\Documents\Android_install_tools_native_apps\Appium\node_modules\appium\node_modules\async\lib\async.js:149:13)
    at C:\Users\Administrator\Documents\Android_install_tools_native_apps\Appium\node_modules\appium\node_modules\async\lib\async.js:160:25
    at C:\Users\Administrator\Documents\Android_install_tools_native_apps\Appium\node_modules\appium\node_modules\async\lib\async.js:251:21
    at C:\Users\Administrator\Documents\Android_install_tools_native_apps\Appium\node_modules\appium\node_modules\async\lib\async.js:615:34
    at null.<anonymous> (C:\Users\Administrator\Documents\Android_install_tools_native_apps\Appium\node_modules\appium\node_modules\appium-adb\lib\adb.js:172:9)
    at ChildProcess.exithandler (child_process.js:635:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17) context: [POST /wd/hub/session {"desiredCapabilities":{"platformVersion":"4.4.2","platformName":"Android","deviceName":"Android_native_app_testing"}}]

**Comment by sebv** [comment]
We are currently rewriting appium so we don't have this kind of nested callback issues anymore, stay tuned.

**Comment by marmbah** [comment]
When is the expected release?

**Comment by sebv** [comment]
Follow this here: https://github.com/appium/appium/issues/5169
