### ISSUE TITLE
iOS 8.3 mobile: scrollTo not working

### ISSUE THREAD

**Issue by nabeel-ibrahim** [appium/appium#5195]
I am trying to scroll element to view but i can't seem to. Below is the code i am trying to execute:
HashMap<String, String> scrollObject = new HashMap<String, String>();
			scrollObject.put("element", element.getText());
			JavascriptExecutor js = driver;
			js.executeScript("mobile: scrollTo", scrollObject);
I always get the following error:
org.openqa.selenium.WebDriverException: An error occurred while executing user supplied JavaScript. (WARNING: The server did not provide any stacktrace information)
I am using appium 1.4.1 on iPhone 6 iOS version 8.3

**Comment by imurchie** [comment]
Can you provide the Appium server logs?

**Comment by sebv** [comment]
Closing, no activity, may be reopened if needed.

**Comment by ChiWhiteSox56** [comment]
I am experiencing this issue as well. The odd thing is that mobile: scroll works perfectly for one list on my app, but for a different list I continue to receive the following error: "org.openqa.selenium.WebDriverException: An error occurred while executing user supplied JavaScript. (WARNING: The server did not provide any stacktrace information)"

I am running my tests on an 8.3 iPhone 6 Simulator using Appium version 1.4.8 (Draco)

The code that I am using is shown below. Again, I am using the same code for two different lists in the app, and it does work for one of the lists:

JavascriptExecutor js = (JavascriptExecutor) driver;
HashMap<String, String> scrollObject = new HashMap<String, String>();	
scrollObject.put("direction", "down");
js.executeScript("mobile: scroll", scrollObject);

I have confirmed that both lists are UIAScrollViews.

Failure Trace:
org.openqa.selenium.WebDriverException: An error occurred while executing user supplied JavaScript. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 808 milliseconds
Build info: version: '2.45.0', revision: '32a636c', time: '2015-03-05 22:01:35'
System info: host: 'MacbookPro', ip: '192.168.10.158', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.8.0_45'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{app=/Users/cmichalowski/Desktop/mycompany.app, networkConnectionEnabled=false, warnings={}, databaseEnabled=false, version=8.3, deviceName=iPhone 6, platform=MAC, desired={app=/Users/cmichalowski/Desktop/mycompany.app, browserName=iOS, platformName=iOS, version=8.3, deviceName=iPhone 6, platform=MAC}, webStorageEnabled=false, locationContextEnabled=false, browserName=iOS, takesScreenshot=true, javascriptEnabled=true, platformName=iOS}]
Session ID: 1406e1c0-5e5f-4209-9fa8-39f38e258280
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:180)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:508)
	at mycompanyMobileAppTestsIOS.DashboardPageTests.clickBloodPressureContainer(DashboardPageTests.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

Any assistance would be greatly appreciated.

**Comment by fionazj** [comment]
hi, I'm facing same issues, any update for it?..
