### ISSUE TITLE
Instruments not starting, error Unhandled error: TypeError: undefined is not a function

### ISSUE THREAD

**Issue by Simon-Kaz** [appium/appium#5218]
Hey, guys I've updated just now to Appium 1.4.1 (using the command line/npm version). 

When I try to run my tests on:
osx 10.10.3
iPhone 6
ios 8.1.2
xcode 6.3.2
app pre-installed (I'm providing bundleID to run the app)

The following error occurs. I'm not sure how to handle this, any tips? The server doesn't crash, it just hangs there with this error.

Logs:

```
 info: [debug] App is installed.
info: [debug] fullReset not requested. No need to install.
info: [debug] Starting command proxy.
info: [debug] Instruments socket server started at /tmp/instruments_sock
info: [debug] Starting instruments
WARN Finding XcodePath by symlink because TypeError: Invalid attempt to destructure non-iterable instance
error: Unhandled error: TypeError: undefined is not a function
    at [object Object].<anonymous> (/usr/local/lib/node_modules/appium/node_modules/appium-instruments/lib/instruments.js:175:27)
    at tryCatcher (/usr/local/lib/node_modules/appium/node_modules/appium-instruments/node_modules/appium-support/node_modules/bluebird/js/main/util.js:24:31)
    at Promise.successAdapter (/usr/local/lib/node_modules/appium/node_modules/appium-instruments/node_modules/appium-support/node_modules/bluebird/js/main/nodeify.js:22:30)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/appium/node_modules/appium-instruments/node_modules/appium-support/node_modules/bluebird/js/main/promise.js:528:21)
    at Promise._settlePromises (/usr/local/lib/node_modules/appium/node_modules/appium-instruments/node_modules/appium-support/node_modules/bluebird/js/main/promise.js:646:14)
    at bound (domain.js:254:14)
    at Promise.runBound (domain.js:267:12)
    at Async._drainQueue (/usr/local/lib/node_modules/appium/node_modules/appium-instruments/node_modules/appium-support/node_modules/bluebird/js/main/async.js:182:12)
    at Async._drainQueues (/usr/local/lib/node_modules/appium/node_modules/appium-instruments/node_modules/appium-support/node_modules/bluebird/js/main/async.js:187:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/appium/node_modules/appium-instruments/node_modules/appium-support/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17) context: [POST /wd/hub/session {"desiredCapabilities":{"app":"hereGoesAppLocation","newCommandTimeout":"180","platformVersion":"8.1.2","bundleId":"hereGoesBundleID]
```

My caps:
```

        capabilities.setCapability("platformName", "iOS");
        capabilities.setCapability("platformVersion", "8.1.2");
        capabilities.setCapability("deviceName", "iPhone 6");
        capabilities.setCapability("udid","udidGoesHere");
        capabilities.setCapability("bundleId","bundleIdGoesHere");
        capabilities.setCapability("autoAcceptAlerts", true);        
        capabilities.setCapability("newCommandTimeout","180");
        driver = new IOSDriver(new URL("http://0.0.0.0:4723/wd/hub"), capabilities);
```

**Comment by Simon-Kaz** [comment]
FYI - I reverted back to appium 1.3.7 and it works fine, so some issue must've been introduced between 1.3.7 and 1.4.1!

**Comment by sebv** [comment]
@Simon-Kaz could you provide full log, we need the git sha at the beginning.

ping @jlipps looks like a new bug in the es2015 conversion.

**Comment by sebv** [comment]
This is due to a regenerator package upgrade, we need to devise a strategy to avoid that.

**Comment by Simon-Kaz** [comment]
Hey @sebv do you still need the logs?

**Comment by sebv** [comment]
nope, I've tracked this one down.

**Comment by khallbec** [comment]
Happening to us too. is there a work around?

**Comment by khallbec** [comment]
This also happens in 1.4.0. I reverted back to 1.3.7 till there is a working version.

**Comment by sGuid** [comment]
I just tried downloading 1.4.2 and ran into the same issue. Reverting to 1.3.7 is working for me.

**Comment by sebv** [comment]
Confirmed...we missed one dependency...https://github.com/appium/appium-instruments/blob/master/package.json#L30

cc @jlipps

**Comment by sebv** [comment]
Am holding off until San Francisco wakes up, need to talk about the fix with the rest of the team.

**Comment by wensj** [comment]
Now should I Reverting to 1.3.7 ,or any other can do?

**Comment by sebv** [comment]
I've just published temporary 1.4.3-beta version:

Let me know if you see any issue with it.

Install with:
```
npm install appium@1.4.3-beta
```

**Comment by DavidSelby** [comment]
Thanks Seb, that's working great for me.

**Comment by sebv** [comment]
1.4.3 is out.

**Comment by wensj** [comment]
when I use command "npm install appium@1.4.3",try to upgrade appium,get error:

Downloading http://chromedriver.storage.googleapis.com/2.16/chromedriver_mac32.zip...
RequestError: Error: connect ETIMEDOUT
    at new RequestError (/Users/wensj/node_modules/appium/node_modules/appium-chromedriver/node_modules/request-promise/lib/errors.js:11:15)
    at Request.RP$callback [as _callback] (/Users/wensj/node_modules/appium/node_modules/appium-chromedriver/node_modules/request-promise/lib/rp.js:50:34)
    at self.callback (/Users/wensj/node_modules/appium/node_modules/appium-chromedriver/node_modules/request/request.js:354:22)
    at Request.emit (events.js:95:17)
    at Request.onRequestError (/Users/wensj/node_modules/appium/node_modules/appium-chromedriver/node_modules/request/request.js:1011:8)
    at ClientRequest.emit (events.js:95:17)
    at Socket.socketErrorListener (http.js:1551:9)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "appium@1.4.3"
npm ERR! node v0.10.33
npm ERR! npm  v2.1.8
npm ERR! code ELIFECYCLE

npm ERR! appium-chromedriver@2.1.2 install: `node install-npm.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appium-chromedriver@2.1.2 install script 'node install-npm.js'.
npm ERR! This is most likely a problem with the appium-chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install-npm.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls appium-chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/wensj/npm-debug.log
