### ISSUE TITLE
[appium 1.4.1][xcode 6.2]unhandled error: TypeError: Object #<Object> has no method 'slice'

### ISSUE THREAD

**Issue by wensj** [appium/appium#5229]
When I run appium 1.4.1 from mac terminal,I get this error:
WARN Finding XcodePath by symlink because TypeError: Invalid attempt to destructure non-iterable instance 
error: Unhandled error: TypeError: Object #<Object> has no method 'slice'
    at [object Object].<anonymous> (/usr/local/lib/node_modules/appium/lib/devices/ios/ios.js:536:51)
    at /usr/local/lib/node_modules/appium/node_modules/q/q.js:1920:17
    at flush (/usr/local/lib/node_modules/appium/node_modules/q/q.js:110:17)
    at process._tickDomainCallback (node.js:463:13) context: [POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/wensj/Downloads/TEST_PERFECT_2.3.5/app/assets/testscript/superadmin/ios/TestApp/TestApp.app","userDevice":"iphoneSimulator","projectId":"38","suiteExId":"20156916]

**Comment by wensj** [comment]
But when I use appium app 1.3.4,no error.

**Comment by sebv** [comment]
Duplicate: https://github.com/appium/appium/issues/5218
