### ISSUE TITLE
Running Reset.sh fails for Android

### ISSUE THREAD

**Issue by djoubran** [appium/appium#5264]
My reset.sh fails for android with the following error during build:

djoubr$ ./reset.sh --android --verbose
.... successful steps omitted
BUILD SUCCESSFUL
Total time: 0 seconds
Buildfile: /Users/djoubr/DevTools/appiumStuff/appium/submodules/unlock_apk/build.xml

-set-mode-check:

-set-debug-files:

-check-env:
 [checkenv] Android SDK Tools Revision 24.3.2
 [checkenv] Installed at /Users/djoubr/Library/Android/sdk

-setup:
     [echo] Project Name: unlock_apk
  [gettype] Project Type: Application

-set-debug-mode:

-debug-obfuscation-check:

-pre-build:

-build-setup:
[getbuildtools] Using latest Build Tools: 23.0.0 rc2
     [echo] Resolving Build Target for unlock_apk...
[gettarget] Project Target:   Android 4.4.2
[gettarget] API level:        19
[gettarget] WARNING: No minSdkVersion value set. Application will install on all Android versions.
     [echo] ----------
     [echo] Creating output directories if needed...
    [mkdir] Created dir: /Users/djoubr/DevTools/appiumStuff/appium/submodules/unlock_apk/bin
    [mkdir] Created dir: /Users/djoubr/DevTools/appiumStuff/appium/submodules/unlock_apk/bin/res
    [mkdir] Created dir: /Users/djoubr/DevTools/appiumStuff/appium/submodules/unlock_apk/bin/rsObj
    [mkdir] Created dir: /Users/djoubr/DevTools/appiumStuff/appium/submodules/unlock_apk/bin/rsLibs
    [mkdir] Created dir: /Users/djoubr/DevTools/appiumStuff/appium/submodules/unlock_apk/gen
    [mkdir] Created dir: /Users/djoubr/DevTools/appiumStuff/appium/submodules/unlock_apk/bin/classes
    [mkdir] Created dir: /Users/djoubr/DevTools/appiumStuff/appium/submodules/unlock_apk/bin/dexedLibs
     [echo] ----------
     [echo] Resolving Dependencies for unlock_apk...
[dependency] Library dependencies:
[dependency] No Libraries
[dependency] 
[dependency] ------------------
     [echo] ----------
     [echo] Building Libraries with 'debug'...
   [subant] No sub-builds to iterate on

-code-gen:
[mergemanifest] Merging AndroidManifest files into one.
[mergemanifest] Manifest merger disabled. Using project manifest only.
     [echo] Handling aidl files...
     [aidl] No AIDL files to compile.
     [echo] ----------
     [echo] Handling RenderScript files...
     [echo] ----------
     [echo] Handling Resources...
     [aapt] Generating resource IDs...

BUILD FAILED
/Users/djoubr/Library/Android/sdk/tools/ant/build.xml:649: The following error occurred while executing this line:
/Users/djoubr/Library/Android/sdk/tools/ant/build.xml:694: Execute failed: java.io.IOException: Cannot run program "/Users/djoubr/DevTools/appiumStuff/appium/submodules/unlock_apk/${aapt}": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1041)
	at java.lang.Runtime.exec(Runtime.java:617)
	at org.apache.tools.ant.taskdefs.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:41)
	at org.apache.tools.ant.taskdefs.Execute.launch(Execute.java:428)
	at org.apache.tools.ant.taskdefs.Execute.execute(Execute.java:442)
	at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:628)
	at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:669)
	at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:495)
	at com.android.ant.AaptExecTask.execute(AaptExecTask.java:703)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
	at com.android.ant.IfElseTask.execute(IfElseTask.java:120)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:396)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
	at org.apache.tools.ant.Main.runBuild(Main.java:851)
	at org.apache.tools.ant.Main.startAnt(Main.java:235)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:135)
	at java.lang.ProcessImpl.start(ProcessImpl.java:130)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1022)
	... 46 more

This is preventing me from running on Android entirely. I just did a pull from master for appium and tried installing all sdk's that were available from google. If I omit the unlock step from the build, it fails on the very next step with the below error:

BUILD SUCCESSFUL
Total time: 0 seconds
Buildfile: /Users/djoubr/DevTools/appiumStuff/appium/submodules/io.appium.android.ime/build.xml

-set-mode-check:

-set-debug-files:

-check-env:
 [checkenv] Android SDK Tools Revision 24.3.2
 [checkenv] Installed at /Users/djoubr/Library/Android/sdk

-setup:
     [echo] Project Name: UnicodeIME
  [gettype] Project Type: Application

-set-debug-mode:

-debug-obfuscation-check:

-pre-build:

-build-setup:
[getbuildtools] Using latest Build Tools: 23.0.0 rc2
     [echo] Resolving Build Target for UnicodeIME...
[gettarget] Project Target:   Android 4.4.2
[gettarget] API level:        19
     [echo] ----------
     [echo] Creating output directories if needed...
    [mkdir] Created dir: /Users/djoubr/DevTools/appiumStuff/appium/submodules/io.appium.android.ime/libs
    [mkdir] Created dir: /Users/djoubr/DevTools/appiumStuff/appium/submodules/io.appium.android.ime/bin
    [mkdir] Created dir: /Users/djoubr/DevTools/appiumStuff/appium/submodules/io.appium.android.ime/bin/res
    [mkdir] Created dir: /Users/djoubr/DevTools/appiumStuff/appium/submodules/io.appium.android.ime/bin/rsObj
    [mkdir] Created dir: /Users/djoubr/DevTools/appiumStuff/appium/submodules/io.appium.android.ime/bin/rsLibs
    [mkdir] Created dir: /Users/djoubr/DevTools/appiumStuff/appium/submodules/io.appium.android.ime/gen
    [mkdir] Created dir: /Users/djoubr/DevTools/appiumStuff/appium/submodules/io.appium.android.ime/bin/classes
    [mkdir] Created dir: /Users/djoubr/DevTools/appiumStuff/appium/submodules/io.appium.android.ime/bin/dexedLibs
     [echo] ----------
     [echo] Resolving Dependencies for UnicodeIME...
[dependency] Library dependencies:
[dependency] No Libraries
[dependency] 
[dependency] ------------------
     [echo] ----------
     [echo] Building Libraries with 'debug'...
   [subant] No sub-builds to iterate on

-code-gen:
[mergemanifest] Merging AndroidManifest files into one.
[mergemanifest] Manifest merger disabled. Using project manifest only.
     [echo] Handling aidl files...
     [aidl] No AIDL files to compile.
     [echo] ----------
     [echo] Handling RenderScript files...
     [echo] ----------
     [echo] Handling Resources...
     [aapt] Generating resource IDs...

BUILD FAILED
/Users/djoubr/Library/Android/sdk/tools/ant/build.xml:649: The following error occurred while executing this line:
/Users/djoubr/Library/Android/sdk/tools/ant/build.xml:694: Execute failed: java.io.IOException: Cannot run program "/Users/djoubr/DevTools/appiumStuff/appium/submodules/io.appium.android.ime/${aapt}": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1041)
	at java.lang.Runtime.exec(Runtime.java:617)
	at org.apache.tools.ant.taskdefs.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:41)
	at org.apache.tools.ant.taskdefs.Execute.launch(Execute.java:428)
	at org.apache.tools.ant.taskdefs.Execute.execute(Execute.java:442)
	at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:628)
	at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:669)
	at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:495)
	at com.android.ant.AaptExecTask.execute(AaptExecTask.java:703)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
	at com.android.ant.IfElseTask.execute(IfElseTask.java:120)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:396)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
	at org.apache.tools.ant.Main.runBuild(Main.java:851)
	at org.apache.tools.ant.Main.startAnt(Main.java:235)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:135)
	at java.lang.ProcessImpl.start(ProcessImpl.java:130)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1022)
	... 46 more

It seems like it's all around the missing property ${aapt}

**Comment by sebv** [comment]
There are some serious PATH issue, example,
```
 "/Users/djoubr/DevTools/appiumStuff/appium/submodules/unlock_apk/${aapt}"
```

Not sure what causing that. @jlipps any idea, the path pattern is weird, but likely cause is misconfigured aapt.

Also try with the `--hardcore` flag, that would delete everything.

**Comment by djoubran** [comment]
Thanks for the quick reply. I don't understand how that line shows path issues. The "/Users/djoubr/DevTools/appiumStuff/appium" directory is my download of the appium source. It works  for iOS. I am even able to run mobile web on a physical device. Can you elaborate?

I attempted rerunning with --hardcore flag, but got the exact same error.

**Comment by sebv** [comment]
Yes aapt is an android tool, so no surprise it works with iOS.

**Comment by djoubran** [comment]
finally got it figured out. I got a temporary workaround by directly editing my [Android sdk]/tools/ant/build.xml file to point to the aapt (and also dx and zipalign) executables for the versions of android that I'm targeting. Not sure where in the install/setup process that gets put in place, but it seems like some android sdk / appium communication failure? I don't really know.
