### ISSUE TITLE
uncaught exception: ECONNRESET

### ISSUE THREAD

**Issue by chris1248** [appium/appium#5348]
I was attempting to run over a hundred rspec tests on the IOS simulator (again), and this time appium failed with a new exception I have never seen before:

    error: uncaughtException: read ECONNRESET date=Tue Jul 07 2015 16:36:21 GMT-0600 (MDT), pid=4161, uid=1465707852, gid=1095186886, cwd=/Users/cjohnson/code/appium, execPath=/usr/local/Cellar/node/0.12.4/bin/node, version=v0.12.4, argv=[node, /Users/cjohnson/code/appium/lib/server/main.js, --session-override], rss=262033408, heapTotal=133905664, heapUsed=79829944, loadavg=[2.87158203125, 3.49072265625, 3.13525390625], uptime=18379, trace=[column=11, file=util.js, function=exports._errnoException, line=746, method=_errnoException, native=false, column=26, file=net.js, function=TCP.onread, line=559, method=onread, native=false], stack=[Error: read ECONNRESET,     at exports._errnoException (util.js:746:11),     at TCP.onread (net.js:559:26)]

Not sure how to attach the log file with the terminal output from appium???
So here is a snippet of the last few pages of that:

info: <-- GET /wd/hub/session/1bd57f30-dc4d-4dbe-b634-b6619568df9a/element/5009/displayed 200 8.773 ms - 76 {"status":0,"value":true,"sessionId":"1bd57f30-dc4d-4dbe-b634-b6619568df9a"}
info: --> POST /wd/hub/session/1bd57f30-dc4d-4dbe-b634-b6619568df9a/elements {"using":"css selector","value":".answer-list__item--correct"}
info: [debug] Waiting up to 0ms for condition
info: [debug] [REMOTE] Executing 'find_elements' atom in default context
info: [debug] [REMOTE] Sending javascript command
info: [debug] [REMOTE] Sending _rpc_forwardSocketData: message to remote debugger
info: [debug] [REMOTE] Receiving data from remote debugger
info: [debug] [REMOTE] got applicationSentData response
info: [debug] Responding to client with success: {"status":0,"value":[{"ELEMENT":"5010"}],"sessionId":"1bd57f30-dc4d-4dbe-b634-b6619568df9a"}
info: <-- POST /wd/hub/session/1bd57f30-dc4d-4dbe-b634-b6619568df9a/elements 200 6.303 ms - 92 {"status":0,"value":[{"ELEMENT":"5010"}],"sessionId":"1bd57f30-dc4d-4dbe-b634-b6619568df9a"}
info: --> GET /wd/hub/session/1bd57f30-dc4d-4dbe-b634-b6619568df9a/element/5010/displayed {}
info: [debug] [REMOTE] Executing 'is_displayed' atom in default context
info: [debug] [REMOTE] Sending javascript command
info: [debug] [REMOTE] Sending _rpc_forwardSocketData: message to remote debugger
info: [debug] [REMOTE] Receiving data from remote debugger
info: [debug] [REMOTE] got applicationSentData response
info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"1bd57f30-dc4d-4dbe-b634-b6619568df9a"}
info: <-- GET /wd/hub/session/1bd57f30-dc4d-4dbe-b634-b6619568df9a/element/5010/displayed 200 8.293 ms - 76 {"status":0,"value":true,"sessionId":"1bd57f30-dc4d-4dbe-b634-b6619568df9a"}
info: --> POST /wd/hub/session/1bd57f30-dc4d-4dbe-b634-b6619568df9a/elements {"using":"css selector","value":".answer-list__item--incorrect"}
info: [debug] Waiting up to 0ms for condition
info: [debug] [REMOTE] Executing 'find_elements' atom in default context
info: [debug] [REMOTE] Sending javascript command
info: [debug] [REMOTE] Sending _rpc_forwardSocketData: message to remote debugger
info: [debug] [REMOTE] Receiving data from remote debugger
info: [debug] [REMOTE] got applicationSentData response
info: [debug] Responding to client with success: {"status":0,"value":[{"ELEMENT":"5011"}],"sessionId":"1bd57f30-dc4d-4dbe-b634-b6619568df9a"}
info: <-- POST /wd/hub/session/1bd57f30-dc4d-4dbe-b634-b6619568df9a/elements 200 6.199 ms - 92 {"status":0,"value":[{"ELEMENT":"5011"}],"sessionId":"1bd57f30-dc4d-4dbe-b634-b6619568df9a"}
info: --> GET /wd/hub/session/1bd57f30-dc4d-4dbe-b634-b6619568df9a/element/5011/displayed {}
info: [debug] [REMOTE] Executing 'is_displayed' atom in default context
info: [debug] [REMOTE] Sending javascript command
info: [debug] [REMOTE] Sending _rpc_forwardSocketData: message to remote debugger
info: [debug] [REMOTE] Receiving data from remote debugger
info: [debug] [REMOTE] got applicationSentData response
info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"1bd57f30-dc4d-4dbe-b634-b6619568df9a"}
info: <-- GET /wd/hub/session/1bd57f30-dc4d-4dbe-b634-b6619568df9a/element/5011/displayed 200 7.991 ms - 76 {"status":0,"value":true,"sessionId":"1bd57f30-dc4d-4dbe-b634-b6619568df9a"}
info: --> POST /wd/hub/session/1bd57f30-dc4d-4dbe-b634-b6619568df9a/elements {"using":"css selector","value":".answer-list__item--selected"}
info: [debug] Waiting up to 0ms for condition
info: [debug] [REMOTE] Executing 'find_elements' atom in default context
info: [debug] [REMOTE] Sending javascript command
info: [debug] [REMOTE] Sending _rpc_forwardSocketData: message to remote debugger
info: [debug] [REMOTE] Receiving data from remote debugger
info: [debug] [REMOTE] got applicationSentData response
info: [debug] Responding to client with success: {"status":0,"value":[{"ELEMENT":"5012"}],"sessionId":"1bd57f30-dc4d-4dbe-b634-b6619568df9a"}
info: <-- POST /wd/hub/session/1bd57f30-dc4d-4dbe-b634-b6619568df9a/elements 200 6.361 ms - 92 {"status":0,"value":[{"ELEMENT":"5012"}],"sessionId":"1bd57f30-dc4d-4dbe-b634-b6619568df9a"}
info: --> GET /wd/hub/session/1bd57f30-dc4d-4dbe-b634-b6619568df9a/element/5012/displayed {}
info: [debug] [REMOTE] Executing 'is_displayed' atom in default context
info: [debug] [REMOTE] Sending javascript command
info: [debug] [REMOTE] Sending _rpc_forwardSocketData: message to remote debugger
info: [debug] [REMOTE] Receiving data from remote debugger
info: [debug] [REMOTE] Receiving data from remote debugger
info: [debug] [REMOTE] got applicationSentData response
info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"1bd57f30-dc4d-4dbe-b634-b6619568df9a"}
info: <-- GET /wd/hub/session/1bd57f30-dc4d-4dbe-b634-b6619568df9a/element/5012/displayed 200 8.965 ms - 76 {"status":0,"value":true,"sessionId":"1bd57f30-dc4d-4dbe-b634-b6619568df9a"}
info: --> GET /wd/hub/session/1bd57f30-dc4d-4dbe-b634-b6619568df9a/element/5010/text {}
info: [debug] [REMOTE] Executing 'get_text' atom in default context
info: [debug] [REMOTE] Sending javascript command
info: [debug] [REMOTE] Sending _rpc_forwardSocketData: message to remote debugger
info: [debug] [REMOTE] Receiving data from remote debugger
info: [debug] [REMOTE] got applicationSentData response
info: [debug] Responding to client with success: {"status":0,"value":"Correctly chosen answer\nTrue","sessionId":"1bd57f30-dc4d-4dbe-b634-b6619568df9a"}
info: <-- GET /wd/hub/session/1bd57f30-dc4d-4dbe-b634-b6619568df9a/element/5010/text 200 9.806 ms - 103 {"status":0,"value":"Correctly chosen answer\nTrue","sessionId":"1bd57f30-dc4d-4dbe-b634-b6619568df9a"}
info: --> GET /wd/hub/session/1bd57f30-dc4d-4dbe-b634-b6619568df9a/element/5012/text {}
info: [debug] [REMOTE] Executing 'get_text' atom in default context
info: [debug] [REMOTE] Sending javascript command
info: [debug] [REMOTE] Sending _rpc_forwardSocketData: message to remote debugger
info: [debug] [REMOTE] Receiving data from remote debugger
info: [debug] [REMOTE] Receiving data from remote debugger
info: [debug] [REMOTE] got applicationSentData response
info: [debug] Responding to client with success: {"status":0,"value":"Correctly chosen answer\nTrue","sessionId":"1bd57f30-dc4d-4dbe-b634-b6619568df9a"}
info: <-- GET /wd/hub/session/1bd57f30-dc4d-4dbe-b634-b6619568df9a/element/5012/text 200 9.851 ms - 103 {"status":0,"value":"Correctly chosen answer\nTrue","sessionId":"1bd57f30-dc4d-4dbe-b634-b6619568df9a"}
info: --> GET /wd/hub/session/1bd57f30-dc4d-4dbe-b634-b6619568df9a/element/5011/text {}
info: [debug] [REMOTE] Executing 'get_text' atom in default context
info: [debug] [REMOTE] Sending javascript command
info: [debug] [REMOTE] Sending _rpc_forwardSocketData: message to remote debugger
info: [debug] [REMOTE] Receiving data from remote debugger
info: [debug] [REMOTE] Receiving data from remote debugger
info: [debug] [REMOTE] got applicationSentData response
info: [debug] Responding to client with success: {"status":0,"value":"Incorrect answer\nFalse","sessionId":"1bd57f30-dc4d-4dbe-b634-b6619568df9a"}
info: <-- GET /wd/hub/session/1bd57f30-dc4d-4dbe-b634-b6619568df9a/element/5011/text 200 9.657 ms - 97 {"status":0,"value":"Incorrect answer\nFalse","sessionId":"1bd57f30-dc4d-4dbe-b634-b6619568df9a"}
info: --> GET /wd/hub/session/1bd57f30-dc4d-4dbe-b634-b6619568df9a/element/5012/text {}
info: [debug] [REMOTE] Executing 'get_text' atom in default context
info: [debug] [REMOTE] Sending javascript command
info: [debug] [REMOTE] Sending _rpc_forwardSocketData: message to remote debugger
info: [debug] [REMOTE] Receiving data from remote debugger
info: [debug] [REMOTE] Receiving data from remote debugger
info: [debug] [REMOTE] got applicationSentData response
info: [debug] Responding to client with success: {"status":0,"value":"Correctly chosen answer\nTrue","sessionId":"1bd57f30-dc4d-4dbe-b634-b6619568df9a"}
info: <-- GET /wd/hub/session/1bd57f30-dc4d-4dbe-b634-b6619568df9a/element/5012/text 200 9.653 ms - 103 {"status":0,"value":"Correctly chosen answer\nTrue","sessionId":"1bd57f30-dc4d-4dbe-b634-b6619568df9a"}
info: --> GET /wd/hub/session/1bd57f30-dc4d-4dbe-b634-b6619568df9a/url {}
info: [debug] [REMOTE] Sending javascript command
info: [debug] [REMOTE] Sending _rpc_forwardSocketData: message to remote debugger
info: [debug] [REMOTE] Receiving data from remote debugger
info: [debug] [REMOTE] Receiving data from remote debugger
info: [debug] [REMOTE] got applicationSentData response
info: [debug] Responding to client with success: {"status":0,"value":"http://0.0.0.0:5567/learner/courses/2/slide/4","sessionId":"1bd57f30-dc4d-4dbe-b634-b6619568df9a"}
info: <-- GET /wd/hub/session/1bd57f30-dc4d-4dbe-b634-b6619568df9a/url 200 1.830 ms - 119 {"status":0,"value":"http://0.0.0.0:5567/learner/courses/2/slide/4","sessionId":"1bd57f30-dc4d-4dbe-b634-b6619568df9a"}
info: --> POST /wd/hub/session/1bd57f30-dc4d-4dbe-b634-b6619568df9a/execute {"script":"\n        window.location = \"about:blank\";\n      ","args":[]}
info: [debug] [REMOTE] Executing 'execute_script' atom in default context
info: [debug] [REMOTE] Sending javascript command
info: [debug] [REMOTE] Sending _rpc_forwardSocketData: message to remote debugger
info: [debug] [REMOTE] Receiving data from remote debugger
info: [debug] [REMOTE] Receiving data from remote debugger
info: [debug] [REMOTE] got applicationSentData response
info: [debug] [REMOTE] Got a blank data response from debugger
info: [debug] [REMOTE] got applicationSentData response
info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"1bd57f30-dc4d-4dbe-b634-b6619568df9a"}
info: <-- POST /wd/hub/session/1bd57f30-dc4d-4dbe-b634-b6619568df9a/execute 200 3.423 ms - 76 {"status":0,"value":null,"sessionId":"1bd57f30-dc4d-4dbe-b634-b6619568df9a"}
info: [debug] [REMOTE] Receiving data from remote debugger
info: [debug] [REMOTE] got applicationSentData response
info: [debug] [REMOTE] Got a blank data response from debugger
info: [debug] [REMOTE] Receiving data from remote debugger
info: [debug] [REMOTE] Receiving data from remote debugger
info: [debug] [REMOTE] got applicationSentData response
info: [debug] [REMOTE] Frame navigated, unloading page
info: [debug] [REMOTE] Frame navigated, calling cbs
info: [debug] [REMOTE] Receiving data from remote debugger
info: [debug] [REMOTE] got applicationSentData response
info: [debug] [REMOTE] Page loaded, verifying whether ready through readyState
info: [debug] [REMOTE] got applicationSentData response
info: [debug] [REMOTE] Got a blank data response from debugger
info: [debug] [REMOTE] got applicationSentData response
info: [debug] [REMOTE] Got a blank data response from debugger
info: [debug] [REMOTE] got applicationSentData response
info: [debug] [REMOTE] Got a blank data response from debugger
info: --> POST /wd/hub/session/1bd57f30-dc4d-4dbe-b634-b6619568df9a/appium/app/reset {}
info: [debug] Resetting app mid-session
info: [debug] Running generic full reset
info: Shutting down appium session
info: [debug] Stopping ios
info: [debug] Destroying instruments client socket.
info: [debug] Closing socket server.
info: [debug] Instruments socket server was closed
info: [debug] Sending sigterm to instruments
info: [debug] [INST] 2015-07-07 22:36:20 +0000 Stopped: Script was stopped by the user
info: [debug] [REMOTE] Receiving data from remote debugger
info: [debug] [REMOTE] {"__argument":{"WIRApplicationIdentifierKey":"PID:20119","WIRIsApplicationProxyKey":false,"WIRApplicationNameKey":"Safari","WIRApplicationBundleIdentifierKey":"com.apple.mobilesafari","WIRIsApplicationActiveKey":1},"__selector":"_rpc_applicationDisconnected:"}
info: [debug] [REMOTE] {"__argument":{"WIRApplicationIdentifierKey":"PID:20126","WIRIsApplicationProxyKey":true,"WIRApplicationNameKey":"","WIRApplicationBundleIdentifierKey":"com.apple.WebKit.WebContent","WIRIsApplicationActiveKey":0,"WIRHostApplicationIdentifierKey":"PID:20119"},"__selector":"_rpc_applicationDisconnected:"}
info: [debug] [INST] 2015-07-07 22:36:20 +0000 Error: Script threw an uncaught JavaScript error: JSON Parse error: Unexpected EOF on line 2606 of bootstrap-99f9c43741cbff3c.js
info: [debug] [INST STDERR] 2015-07-07 16:36:21.039 instruments[20068:154983] Attempting to set event horizon when core is not engaged, request ignored
info: [debug] [INST STDERR] 2015-07-07 16:36:21.039 instruments[20068:154980] Attempting to set event horizon when core is not engaged, request ignored
info: [debug] [INST STDERR] 2015-07-07 16:36:21.061 instruments[20068:154983] Attempting to set event horizon when core is not engaged, request ignored
info: [debug] [INST STDERR] 2015-07-07 16:36:21.062 instruments[20068:155194] Attempting to set event horizon when core is not engaged, request ignored
info: [debug] [INST] Instruments Trace Complete (Duration : 16.217344s; Output : /tmp/appium-instruments/instrumentscli0.trace)
info: [debug] [INSTSERVER] Instruments exited with code 0
info: [debug] Cleaning up after instruments exit
info: [debug] Stopping iOS log capture
info: [debug] [REMOTE] Executing 'execute_script' atom in default context
info: [debug] [REMOTE] Sending javascript command
info: [debug] [REMOTE] Sending _rpc_forwardSocketData: message to remote debugger
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killing any other simulator daemons
info: [debug] Killall iOS Simulator
info: [debug] [REMOTE] Checking document readyState
info: [debug] [REMOTE] Sending javascript command
info: [debug] [REMOTE] Sending _rpc_forwardSocketData: message to remote debugger
error: uncaughtException: read ECONNRESET date=Tue Jul 07 2015 16:36:21 GMT-0600 (MDT), pid=4161, uid=1465707852, gid=1095186886, cwd=/Users/cjohnson/code/appium, execPath=/usr/local/Cellar/node/0.12.4/bin/node, version=v0.12.4, argv=[node, /Users/cjohnson/code/appium/lib/server/main.js, --session-override], rss=262033408, heapTotal=133905664, heapUsed=79829944, loadavg=[2.87158203125, 3.49072265625, 3.13525390625], uptime=18379, trace=[column=11, file=util.js, function=exports._errnoException, line=746, method=_errnoException, native=false, column=26, file=net.js, function=TCP.onread, line=559, method=onread, native=false], stack=[Error: read ECONNRESET,     at exports._errnoException (util.js:746:11),     at TCP.onread (net.js:559:26)]

**Comment by Jonahss** [comment]
I don't suppose there's a reliable way to reproduce it? Has something to do with the reset command seems like. Do you call a lot of successful reset commands before this?

**Comment by SrinivasanTarget** [comment]
Closing this because of inactivity.

**Comment by SrinivasanTarget** [comment]
@triager please close

**Comment by vikasg52** [comment]
is there no solution to the above mentioned bug? I am also facing the same while executing test on Android app using appium.

**Comment by jlipps** [comment]
@vikasg52 it was never clear whether this was a bug. The last information we got about this was a year and a half ago, so we closed the issue. If you are running into something, open a new issue and follow the template, ensuring you send us a gist of your full appium logs.

**Comment by vikasg52** [comment]
Hi jlipps,

Thanks for your revert, however I found out the route cause of the issue and it got resolved. The issue was coming due to connectivity at mobile device's end so when appium was trying to fire bootstrap command it was unable to get a connection due to which the issue was occurring. I disconnected the device and connected it again and the issue got resolved.

Regards
Vikas
