### ISSUE TITLE
adm-zip ~0.4.7 throw new RangeError('index out of range') when zip some apk in appium

### ISSUE THREAD

**Issue by spdayu** [appium/appium#5381]
ENV:
appium 1.4.1 + NodeJs v0.12.7 + Linux ud43d7ec95f9d5208a422 3.13.0-57-generic #95~precise1-Ubuntu SMP Mon Jun 22 09:43:07 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Promblem:
When I running test on on our latest APK file with debug keystore, appium throw "error: Unhandled error: RangeError: index out of range " and test run was blocked. After looking into the stack information, I found this exception is caused by adm-zip. and this issue was gone after I replaced arm-zip with a lower version.
Appium start command:
appium -a 127.0.0.1 -p 4726 --use-keystore --keystore-path /home/local/ANT/tianyuu/debug.keystore --full-reset --app /home/local/ANT/tianyuu/apk/latest.apk --udid 4d0083874acb211d
Exception in Appium log:
error: Unhandled error: RangeError: index out of range
    at checkOffset (buffer.js:506:11)
    at Buffer.readUInt16LE (buffer.js:552:5)
    at parseExtra (/usr/local/lib/node_modules/appium/node_modules/adm-zip/zipEntry.js:154:25)
    at Object.extra (/usr/local/lib/node_modules/appium/node_modules/adm-zip/zipEntry.js:209:13)
    at readEntries (/usr/local/lib/node_modules/appium/node_modules/adm-zip/zipFile.js:40:29)
    at readMainHeader (/usr/local/lib/node_modules/appium/node_modules/adm-zip/zipFile.js:72:9)
    at new module.exports (/usr/local/lib/node_modules/appium/node_modules/adm-zip/zipFile.js:18:9)
    at new module.exports (/usr/local/lib/node_modules/appium/node_modules/adm-zip/adm-zip.js:17:20)
    at [object Object].ADB.checkApkKeystoreMatch (/usr/local/lib/node_modules/appium/node_modules/appium-adb/lib/adb.js:546:13)
    at [object Object].<anonymous> (/usr/local/lib/node_modules/appium/node_modules/appium-adb/lib/adb.js:515:12)
    at /usr/local/lib/node_modules/appium/node_modules/appium-adb/lib/adb.js:532:5
    at ChildProcess.exithandler (child_process.js:742:7)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)

**Comment by esoests** [comment]
Any reason why this happen? I have the same issue on my test environment.

**Comment by sebv** [comment]
Are you sure that the zip is not corrupted, otherwise might try to upgrade adm-zip.

**Comment by spdayu** [comment]
I am pretty sure the zip file is good, and the latest version for adm-zip is 0.4.7, anyway I downgrade adm-zip to 0.4.4 and this issue has been resolved.
