### ISSUE TITLE
App is crashing and throwing this error.

### ISSUE THREAD

**Issue by bhawnaa** [appium/appium#5388]
error: Unhandled error: Error: write EPIPE
    at exports._errnoException (util.js:746:11)
    at WriteWrap.afterWrite (net.js:775:14) context: [GET /wd/hub/session/3b421f06-dcdc-4c3e-b7f6-4ed294292d76/orientation {}]

**Comment by vinaybalepur** [comment]
I am also facing the same issue. When I try to start node using shell script from java I face this issue. The log for the same is as follows.
Unhandled error: Error: write EPIPE
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at WriteWrap.afterWrite (net.js:760:14) context: [GET /wd/hub/status {}]

**Comment by dukedvl** [comment]
I am seeing a similar error. When starting up the Appium Server using the GUI, I can initiate the AndroidDriver. When starting up the AppiumServer programatically and using TimedWaits to wait for the server to be up, I can initiate the AndroidDriver. HOWEVER, When I redirect StandardOutput and text-check the output to know whether or not the server is running, (And it starts up succesfully, for sure) I too, run into the EPIPE exception upon instantiating the AppiumDriver. 


I am running Appium v1.4.0.0 for the GUI.
I am writing in C# with the Appium Webdriver pulled from NuGet as 1.4.0.3
Node.js v4.0.0 Installed

![image](https://cloud.githubusercontent.com/assets/9894325/10178761/b9453dba-66cf-11e5-893b-bc3395550c37.png)
^Stack trace of exception



Standard Error log: 

2015-09-29 17:22:00:377 - error: Unhandled error: Error: This socket is closed.
    at Socket._writeGeneric (net.js:640:19)
    at Socket._write (net.js:694:8)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at Socket.Writable.write (_stream_writable.js:207:11)
    at Socket.write (net.js:618:40)
    at [object Object].Console.log (C:\Program Files (x86)\Appium\node_modules\a
ppium\node_modules\winston\lib\winston\transports\console.js:88:20)
    at emit (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\wins
ton\lib\winston\logger.js:180:17)
    at C:\Program Files (x86)\Appium\node_modules\appium\node_modules\async\lib\
async.js:125:13
    at Array.forEach (native)
    at _each (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\asy
nc\lib\async.js:46:24)
    at Object.async.each (C:\Program Files (x86)\Appium\node_modules\appium\node
_modules\async\lib\async.js:124:9)
    at [object Object].Logger.log (C:\Program Files (x86)\Appium\node_modules\ap
pium\node_modules\winston\lib\winston\logger.js:208:9)
    at [object Object].target.(anonymous function) [as info] (C:\Program Files (
x86)\Appium\node_modules\appium\node_modules\winston\lib\winston\common.js:52:18
)
    at C:\Program Files (x86)\Appium\node_modules\appium\lib\server\main.js:111:
12
    at Array.logRequest (C:\Program Files (x86)\Appium\node_modules\appium\node_
modules\morgan\index.js:118:18)
    at listener (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\
morgan\node_modules\on-finished\index.js:164:15)
    at onFinish (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\
morgan\node_modules\on-finished\index.js:95:5)
    at callback (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\
morgan\node_modules\on-finished\node_modules\ee-first\index.js:33:10)
    at ServerResponse.onevent (C:\Program Files (x86)\Appium\node_modules\appium
\node_modules\morgan\node_modules\on-finished\node_modules\ee-first\index.js:66:
5)
    at emitNone (events.js:72:20)
    at ServerResponse.emit (events.js:166:7) context: [GET /wd/hub {}]
Error: write EPIPE
    at exports._errnoException (util.js:837:11)
    at Socket._writeGeneric (net.js:675:26)
    at Socket._write (net.js:694:8)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at Socket.Writable.write (_stream_writable.js:207:11)
    at Socket.write (net.js:618:40)
    at [object Object].Console.log (C:\Program Files (x86)\Appium\node_modules\a
ppium\node_modules\winston\lib\winston\transports\console.js:88:20)
    at emit (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\wins
ton\lib\winston\logger.js:180:17)
    at C:\Program Files (x86)\Appium\node_modules\appium\node_modules\async\lib\
async.js:125:13
    at Array.forEach (native)
    at _each (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\asy
nc\lib\async.js:46:24)
    at Object.async.each (C:\Program Files (x86)\Appium\node_modules\appium\node
_modules\async\lib\async.js:124:9)
    at [object Object].Logger.log (C:\Program Files (x86)\Appium\node_modules\ap
pium\node_modules\winston\lib\winston\logger.js:208:9)
    at [object Object].target.(anonymous function) [as info] (C:\Program Files (
x86)\Appium\node_modules\appium\node_modules\winston\lib\winston\common.js:52:18
)
    at rest.use.morgan.immediate (C:\Program Files (x86)\Appium\node_modules\app
ium\lib\server\main.js:131:12)
    at logRequest (C:\Program Files (x86)\Appium\node_modules\appium\node_module
s\morgan\index.js:118:18)
    at logger (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\mo
rgan\index.js:131:7)
    at Layer.handle [as handle_request] (C:\Program Files (x86)\Appium\node_modu
les\appium\node_modules\express\lib\router\layer.js:82:5)
    at trim_prefix (C:\Program Files (x86)\Appium\node_modules\appium\node_modul
es\express\lib\router\index.js:302:13)
    at C:\Program Files (x86)\Appium\node_modules\appium\node_modules\express\li
b\router\index.js:270:7
    at Function.proto.process_params (C:\Program Files (x86)\Appium\node_modules
\appium\node_modules\express\lib\router\index.js:321:12)





Yet, the node.exe process is running in the background, with the correct port and address, well-ahead of when I instantiate the AppiumDriver. The Driver just pukes on trying to create the connection after redirecting StandardOutput.

**Comment by SrinivasanTarget** [comment]
@bhawnaa please give a shot in recent version of appium i.e 1.5.1.install the same by using: npm install -g appium. Also raise a new issue if any concerns with logs inform of gist.Closing this.

**Comment by SrinivasanTarget** [comment]
@triager please close
