### ISSUE TITLE
Unable to run tests on Appium higher than 1.3.7

### ISSUE THREAD

**Issue by senevit4** [appium/appium#5392]
Using Appium higher than 1.3.7 with iPod touch 8.0.2 i always get the following problem:
info: <-- POST /wd/hub/session/799f4d9a-4b04-4aa6-b888-efbac9b54854/appium/device/app_installed 500 1.342 ms - 101 
TypeError: Cannot read property 'isInstalled' of undefined
    at [object Object].IOS.isAppInstalled (/usr/local/lib/node_modules/appium/lib/devices/ios/ios.js:1487:20)
    at exports.isAppInstalled (/usr/local/lib/node_modules/appium/lib/server/controller.js:113:16)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:82:5)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:82:5)
    at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:267:22
    at param (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:340:14)
    at param (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:356:14)
    at Function.proto.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:400:3)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:261:10)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:100:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at exports.sessionBeforeFilter (/usr/local/lib/node_modules/appium/lib/server/controller.js:56:5)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:82:5)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:110:13)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)

On Appium 1.3.7 everything works fine.

**Comment by imurchie** [comment]
I presume you are using `autoLaunch = false` in your desired capabilities?

This bug was introduced when Fruitstrap was removed. I will look into how to fix it in a sensical way.

**Comment by senevit4** [comment]
I am starting appium 1.4.8 with the following parameters (application is native):
appium --address "127.0.0.1" --port "4725" --command-timeout "7200" --session-override --nodeconfig "/Volumes/Data/Grid/selenium/appium/appiumNode.json" --platform-version "8.0.2" --platform-name "iOS" --app "/Volumes/Data/unify-localrepo/mobileclient/ios/Build/Products/Debug-iphoneos/ansible.app" --udid "f315e023d63e62a4dd604a6d86423ca3c7fcf0f0" --device-name "AppleMobileDevice"
I tried to use autoLaunch=true and now instead of the previous issue i have the follwing one:
info: --> POST /wd/hub/session/c0cc77ed-b367-4c0c-adf3-d7bcea7f49e1/appium/app/launch {}
error: Trying to start a session but instruments is still around
info: [debug] Responding to client with error: {"status":1,"value":{"message":"Unable to launch the app: Error: Trying to start a session but instruments is still around"},"sessionId":"c0cc77ed-b367-4c0c-adf3-d7bcea7f49e1"}
info: <-- POST /wd/hub/session/c0cc77ed-b367-4c0c-adf3-d7bcea7f49e1/appium/app/launch 500 1.640 ms - 176
