### ISSUE TITLE
Error getting device property persist.sys.language: -> more than one device and emulator 

### ISSUE THREAD

**Issue by nikolmarku1** [appium/appium#5396]
Hi,

Appium v1.4.1

I have 2 real devices attached :
1. IPad 1 Mini - OS 8.3
2. Nexus 10 Android version 5.1.1

I have registered both devices on Selenium grid

I tried to run the test and got the error below, see logs
This error is not shown if I remove the connection cable from Ipad

Thanks for your help
# Logs

autotestmac:~ qa$ /Users/qa/automation/selenium/appium/2_start-appium-android-tablet.csh ; exit;
2015-07-17 10:24:53:785 - info: Welcome to Appium v1.4.1 (REV ce6220829063679bcccf5724515c29569c4a16d9)
2015-07-17 10:24:53:789 - info: Appium REST http interface listener started on 10.24.208.226:4723
2015-07-17 10:24:53:793 - info: [debug] Non-default server args: {"address":"10.24.208.226","fullReset":true,"log":"/tmp/appium1.log","logTimestamp":true,"localTimezone":true,"androidDeviceReadyTimeout":"25","deviceName":"Nexus 10","platformName":"Android","platformVersion":"5.0.2","automationName":"Appium","language":"en","locale":"GB","nodeconfig":"/Users/qa/automation/selenium/appium/configAndroid.json","keystorePassword":"","keyAlias":"","keyPassword":"","defaultCommandTimeout":150}
2015-07-17 10:24:53:793 - info: Console LogLevel: debug
2015-07-17 10:24:53:793 - info: File LogLevel: debug
2015-07-17 10:24:53:797 - info: [debug] starting auto register thread for grid. Will try to register every 20000 ms.
2015-07-17 10:25:14:116 - info: [debug] Appium successfully registered with the grid on usb-etbuild5:4444
2015-07-17 10:26:34:316 - info: [debug] Appium successfully registered with the grid on usb-etbuild5:4444
2015-07-17 10:27:54:333 - info: [debug] Appium successfully registered with the grid on usb-etbuild5:4444
2015-07-17 10:28:32:629 - info: --> POST /wd/hub/session {"desiredCapabilities":{"platformVersion":"5.1.1","javascriptEnabled":"true","elementScrollBehavior":"elementScrollBehavior","deviceName":"NexusOne","platformName":"Android","appActivity":"","browserName":"Chrome","launchTimeout":"40000","networkConnectionEnabled":"true","deviceReadyTimeout":35,"takesScreenshot":"true"}}
2015-07-17 10:28:32:631 - info: Client User-Agent string: Apache-HttpClient/4.3.3 (java 1.5)
2015-07-17 10:28:32:632 - warn: Converting cap javascriptEnabled from string to boolean. This might cause unexpected behavior.
2015-07-17 10:28:32:632 - warn: Converting cap networkConnectionEnabled from string to boolean. This might cause unexpected behavior.
2015-07-17 10:28:32:632 - warn: Converting cap takesScreenshot from string to boolean. This might cause unexpected behavior.
2015-07-17 10:28:32:633 - info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : javascriptEnabled, elementScrollBehavior, networkConnectionEnabled, takesScreenshot
2015-07-17 10:28:32:634 - info: Set mode: Proxying straight through to Chromedriver
2015-07-17 10:28:32:635 - info: [debug] Looks like we want chrome on android
2015-07-17 10:28:32:636 - info: [debug] Creating new appium session 9ed1d2df-543b-473a-87ae-c630c3090e84
2015-07-17 10:28:32:638 - info: [debug] Checking whether adb is present
2015-07-17 10:28:32:639 - info: [debug] Using adb from /Applications/Utilities/mobile/android-sdk-macosx/platform-tools/adb
2015-07-17 10:28:32:640 - info: [debug] Using fast reset? false
2015-07-17 10:28:32:640 - info: [debug] Preparing device for session
2015-07-17 10:28:32:641 - info: [debug] Not checking whether app is present since we are assuming it's already on the device
2015-07-17 10:28:32:643 - info: [debug] executing cmd: /Applications/Utilities/mobile/android-sdk-macosx/platform-tools/adb shell "getprop persist.sys.language"
2015-07-17 10:28:35:691 - error: Error getting device property persist.sys.language: Error: Command failed: /bin/sh -c /Applications/Utilities/mobile/android-sdk-macosx/platform-tools/adb shell "getprop persist.sys.language"
error: more than one device and emulator

2015-07-17 10:28:35:692 - info: [debug] Cleaning up appium session
2015-07-17 10:28:35:693 - error: Failed to start an Appium session, err was: Error: Command failed: /bin/sh -c /Applications/Utilities/mobile/android-sdk-macosx/platform-tools/adb shell "getprop persist.sys.language"
error: more than one device and emulator

2015-07-17 10:28:35:695 - info: [debug] Error: Command failed: /bin/sh -c /Applications/Utilities/mobile/android-sdk-macosx/platform-tools/adb shell "getprop persist.sys.language"
error: more than one device and emulator

```
at ChildProcess.exithandler (child_process.js:744:12)
at ChildProcess.emit (events.js:110:17)
at maybeClose (child_process.js:1008:16)
at Socket.<anonymous> (child_process.js:1176:11)
at Socket.emit (events.js:107:17)
at Pipe.close (net.js:476:12)
```

2015-07-17 10:28:35:696 - info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Command failed: /bin/sh -c /Applications/Utilities/mobile/android-sdk-macosx/platform-tools/adb shell \"getprop persist.sys.language\"\nerror: more than one device and emulator\n)","killed":false,"code":255,"signal":null,"cmd":"/bin/sh -c /Applications/Utilities/mobile/android-sdk-macosx/platform-tools/adb shell \"getprop persist.sys.language\"","origValue":"Command failed: /bin/sh -c /Applications/Utilities/mobile/android-sdk-macosx/platform-tools/adb shell \"getprop persist.sys.language\"\nerror: more than one device and emulator\n"},"sessionId":null}

**Comment by sebv** [comment]
Just run `adb devices` to see what is really connected. It's a straightforward adb issue.

**Comment by nikolmarku1** [comment]
same issue on V1-4-13

**Comment by mrabaev48** [comment]
I have same problem(and one more - org.openqa.selenium.SessionNotCreatedException). But I have two connected devices(i checked it in adb console) and two appium servers for run test parallel.

Can u tell me, how I fix it?

thank you,
Best regards

**Comment by pearlselvan** [comment]
Hi ,

Any update or fix  on this issue ?  This is throwing the error : error : error: Command failed: error: more than one device and emulator when running mobile script .

Thanks ,
Muthu Selvan SR

**Comment by filmaj** [comment]
as @sebv points out, you have multiple devices that `adb` can interact with, but your appium instance does not know which one to interact with. Use `adb devices` to get a list of devices and their unique identifiers. Then, feed the unique identifier for the device you want to interact with by passing the `-U` or `--udid` when you start Appium.

See http://appium.io/slate/en/master/?ruby#server-flags for more information on the `-U` server flag.
