### ISSUE TITLE
Need more stack trace on Appium server node.js exception: A new session could not be created. (Original error: Could not push strings.json) 

### ISSUE THREAD

**Issue by KyleChihCheng** [appium/appium#5406]
This is a cross posting from discuss.appium.io just in case it doesn't get answered :-)

When I try to allocate a WebDriver from Selenium Hub, sometimes it will not return a driver due to this log message: A new session could not be created. (Original error: Could not push strings.json) This happens occasionally.

Appium Version: 1.4.1 (node.js version)
Appium client: io.appium:java-client:1.6.1
Settings: 1 Selenium Hub, multiple Linux Hosts, multiple emulators per Linux Host.
Emulators: Android Stock Emulators, SDK level 19 (KitKat)

[Log]
Error Message
java.lang.RuntimeException: Webdriver was unable to be created (Appium): org.openqa.selenium.SessionNotCreatedException: A new session could not be created. (Original error: Could not push strings.json) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 11.25 seconds
Build info: version: '2.42.2', revision: '6a6995d31c7c56c340d6f45a76976d43506cd6cc', time: '2014-06-03 10:52:47'
System info: host: 'dbuildslave11.tag-dev.com', ip: '172.17.42.1', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.32-358.18.1.el6.x86_64', java.version: '1.8.0_45'
Driver info: com.tagged.appium.utils.SwipeableAppiumDriver
Stacktrace

java.lang.RuntimeException: Webdriver was unable to be created (Appium): org.openqa.selenium.SessionNotCreatedException: A new session could not be created. (Original error: Could not push strings.json) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 11.25 seconds
Build info: version: '2.42.2', revision: '6a6995d31c7c56c340d6f45a76976d43506cd6cc', time: '2014-06-03 10:52:47'
System info: host: 'dbuildslave11.tag-dev.com', ip: '172.17.42.1', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.32-358.18.1.el6.x86_64', java.version: '1.8.0_45'
Driver info: com.tagged.appium.utils.SwipeableAppiumDriver
at com.tagged.appium.utils.WebDriverFactory.createDriver(WebDriverFactory.java:79)
at com.tagged.appium.tests.DashboardTest.testNavigation(DashboardTest.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)

Since allocation of WebDriver failed at Selenium Hub level, no Appium log is available.

However, "Could not push strings.json" is message from Appium:
appium/lib/devices/android/android.js -- line 347

var jsonFile = path.resolve(outputPath, stringsJson);
this.adb.push(jsonFile, remotePath, function (err) {
  if (err) return cb(new Error("Could not push strings.json"));
  cb();
});

I need more stack traces from android.js to find out why.

**Comment by imurchie** [comment]
Do you have access to the `adb` logs for the job? That would provide the most information. But I think we ought to be able to send along at least the message from the error.

**Comment by KyleChihCheng** [comment]
Thank you, when will this propagate to a release branch?

**Comment by imurchie** [comment]
That I don't know. But You can run it from source.
