### ISSUE TITLE
error: Could not remove app from device

### ISSUE THREAD

**Issue by ivan-baranovski-intellectsoft** [appium/appium#5407]
I am using appium version 1.4.8, xcode 6.4 and i am running a tests on the ipad of IOS - 8.3. After finishing the tests i am getting the below error:
info: [debug] Stopping iOS log capture
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killing any other simulator daemons
info: [debug] Killall iOS Simulator

info: [debug] fullReset requested. Will try to uninstall the app.

info: [debug] [INSTSERVER] Instruments exited with code null
info: [debug] Cleaning up after instruments exit
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killing any other simulator daemons

info: [debug] Killall iOS Simulator

info: [debug] fullReset requested. Will try to uninstall the app.

info: [debug] Removed com.cirruspath.temp.intellectsoft.CirrusInsight

info: [debug] Cleaning up appium session
info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"e3794f69-ef6e-47a1-afdd-5ce6f457551b"}
info: <-- DELETE /wd/hub/session/e3794f69-ef6e-47a1-afdd-5ce6f457551b 200 8799.223 ms - 76 {"status":0,"value":null,"sessionId":"e3794f69-ef6e-47a1-afdd-5ce6f457551b"}

info: [debug] Cleaning up appium session

error: Could not remove com.cirruspath.temp.intellectsoft.CirrusInsight from device

info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"e3794f69-ef6e-47a1-afdd-5ce6f457551b"}

error: Unexpected error: Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
    at ServerResponse.header (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/response.js:695:10)
    at ServerResponse.send (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/response.js:146:12)
    at ServerResponse.json (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/response.js:235:15)
    at ServerResponse.send (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/response.js:134:21)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/lib/server/responses.js:89:21
    at safely (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/server/helpers.js:306:5)
    at exports.respondSuccess (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/server/responses.js:88:3)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/lib/server/responses.js:120:9
    at [object Object].Appium.cleanupSession (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/appium.js:338:5)
    at [object Object].<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/appium.js:376:10)
    at [object Object].<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js:1372:5)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:251:17
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:148:21
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:248:21
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:612:34
    at [object Object].<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js:1296:13)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/node-idevice/main.js:140:6
    at ChildProcess.exithandler (child_process.js:758:5)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12) context: [DELETE /wd/hub/session/e3794f69-ef6e-47a1-afdd-5ce6f457551b {}]

The problem is only for real device.

**Comment by imurchie** [comment]
Is the app not removed? I'm trying to reproduce this but having trouble.

**Comment by ivan-baranovski-intellectsoft** [comment]
App is removed but if error is displayed second test isn't started. Maybe do you need more information?

**Comment by imurchie** [comment]
As much information as possible would be useful. I will continue to try to reproduce.

**Comment by cjtcwyk** [comment]
my env is OSX10.9.4, Appium1.4.7, JavaClient2.2, iPhone5s iOS8.1. I use the --full-reset flag to start Appium. But when the test case fails, Appium would probability of occurrence doesn‘t remove the app. I have try to add driver.removeApp() and driver.resetApp() before driver.quit() in tearDown(), but looks like tearDown() is not executed. Is this a bug in using iOS real devices? @imurchie

**Comment by cjtcwyk** [comment]
tearDown() is not executed makes next case goes wrong, Log: org.openqa.selenium.remote.SessionNotFoundException: Session ID is null. Using WebDriver after calling quit()?

**Comment by ivan-baranovski-intellectsoft** [comment]
Can somebody help me? I can't run my tests.

**Comment by mathias21** [comment]
Hi @ivan-baranovski-intellectsoft 

I'm getting the same error after deleting the app and reinstalling it again. The funny thing here is that I get the app reinstalled, I can get a new session from the server but once I try to start the new test, then Appium server is dropping a message saying:
"Session ID is null. Using WebDriver after calling quit()?"

Of course I used quit() before uninstalling, then I install the app and then I get the new driver. I get a new session, as I can see this in the server log:
(Second session)
[debug] App is an iOS bundle, will attempt to run as pre-existing
[debug] Creating new appium session 290a3101-71ca-42ef-a259-9b0693df2d75
...
[debug] Instruments launched. Starting poll loop for new commands.
...
[debug] Device launched! Ready for commands
info: [debug] Setting command timeout to the default of 7200 secs
info: [debug] Appium session started with sessionId 290a3101-71ca-42ef-a259-9b0693df2d75
info: <-- POST /wd/hub/session 303 9944.284 ms - 74 
info: --> GET /wd/hub/session/290a3101-71ca-42ef-a259-9b0693df2d75 {}

I will try to solve this, if you find something about it, let me know.

**Comment by ivan-baranovski-intellectsoft** [comment]
Hi @mathias21

I'll inform you if know something about it. 
Thanks.

**Comment by mathias21** [comment]
@ivan-baranovski-intellectsoft 
I'm working on a workaround launching and closing dynamically Appium server, then I don't need to call driver.quit(). This is working fine, not getting the Session null, if I restart the server from Terminal, but I couldn't launch Appium server from the code. Maybe this can be applied in your case.

**Comment by KateOgar** [comment]
have the same problem( 
With removeApp() i got the error  
- RemovingApplication (50%)
- GeneratingApplicationMap (90%)
- Error occurred: APIInternalError
and i found this issue: https://github.com/libimobiledevice/ideviceinstaller/issues/21

May be there is some other way to remove the app from the real ios device? I really stuck with this(

**Comment by imurchie** [comment]
@KateOgar Can you provide your Appium server logs so we can debug this? Thank you.

**Comment by KateOgar** [comment]
here are my appium logs:

info: [debug] [INST] 2016-04-28 14:50:19 +0000 Debug: evaluating au.getElement('33').isDisplayed()

info: [debug] [INST] 2016-04-28 14:50:19 +0000 Debug: evaluation finished
info: [debug] [INST] 2016-04-28 14:50:19 +0000 Debug: responding with:
info: [debug] [INST] 2016-04-28 14:50:19 +0000 Debug: Running system command #39: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":true}...

info: [debug] Socket data received (27 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":true}
info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"463e0b5c-1470-4e20-94d7-39bf46518d80"}
info: <-- GET /wd/hub/session/463e0b5c-1470-4e20-94d7-39bf46518d80/element/33/displayed 200 957.480 ms - 76 {"status":0,"value":true,"sessionId":"463e0b5c-1470-4e20-94d7-39bf46518d80"}
info: --> POST /wd/hub/session/463e0b5c-1470-4e20-94d7-39bf46518d80/appium/app/close {}
info: [debug] Stopping ios
info: [debug] Destroying instruments client socket.
info: [debug] Closing socket server.
info: [debug] Instruments socket server was closed
info: [debug] Sending sigterm to instruments

info: [debug] [INST] 2016-04-28 14:50:19 +0000 Stopped: Script was stopped by the user
info: [debug] [INST STDERR] 2016-04-28 17:50:19.334 instruments[23412:760348] Attempting to change event horizon while disengage

info: [debug] [INST] Instruments Trace Complete (Duration : 69.230186s; Output : /tmp/appium-instruments/instrumentscli0.trace)

info: [debug] [INSTSERVER] Instruments exited with code 0
info: [debug] Cleaning up after instruments exit
info: [debug] Stopping iOS log capture
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killing any other simulator daemons
info: [debug] Killall iOS Simulator

info: [debug] On a real device; cannot clean device state
info: [debug] Responding to client with success: {"status":0,"value":"Successfully closed the [YandexMobileMail.app] app.","sessionId":"463e0b5c-1470-4e20-94d7-39bf46518d80"}
info: <-- POST /wd/hub/session/463e0b5c-1470-4e20-94d7-39bf46518d80/appium/app/close 200 478.071 ms - 125 {"status":0,"value":"Successfully closed the [YandexMobileMail.app] app.","sessionId":"463e0b5c-1470-4e20-94d7-39bf46518d80"}
info: --> POST /wd/hub/session/463e0b5c-1470-4e20-94d7-39bf46518d80/appium/device/remove_app {"bundleId":"YandexMobileMail.app"}
info: --> GET /wd/hub/status {}
info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"},"isShuttingDown":false},"sessionId":"463e0b5c-1470-4e20-94d7-39bf46518d80"}
info: <-- GET /wd/hub/status 200 0.965 ms - 179 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"},"isShuttingDown":false},"sessionId":"463e0b5c-1470-4e20-94d7-39bf46518d80"}

info: [debug] Responding to client with error: {"status":1,"value":{"message":"Uninstalling 'YandexMobileMail.app'\n - RemovingApplication (50%)\n\r - GeneratingApplicationMap (90%)\n - Error occurred: APIInternalError\n"},"sessionId":"463e0b5c-1470-4e20-94d7-39bf46518d80"}

info: <-- POST /wd/hub/session/463e0b5c-1470-4e20-94d7-39bf46518d80/appium/device/remove_app 500 1569.663 ms - 227 
info: --> DELETE /wd/hub/session/463e0b5c-1470-4e20-94d7-39bf46518d80 {}
info: Shutting down appium session
info: [debug] Stopping ios
info: [debug] Trying to stop instruments but it already exited
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killing any other simulator daemons
info: [debug] Killall iOS Simulator

info: [debug] On a real device; cannot clean device state
info: [debug] Cleaning up appium session
info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"463e0b5c-1470-4e20-94d7-39bf46518d80"}
info: <-- DELETE /wd/hub/session/463e0b5c-1470-4e20-94d7-39bf46518d80 200 28.303 ms - 76 {"status":0,"value":null,"sessionId":"463e0b5c-1470-4e20-94d7-39bf46518d80"}

Appium version 1.4.13

**Comment by SrinivasanTarget** [comment]
@KateOgar Latest version of appium logs would help much.please update to latest appium i.e 1.5.2 and update the logs in form of gist.

**Comment by KateOgar** [comment]
now i have problem with installing the app (appium 1.5.2)
Logs:
[debug] [iOS] Creating instruments
[debug] [UIAuto] Preparing bootstrap code
[debug] [UIAuto] Dynamic bootstrap dir: /Users/kateogar/Library/Application Support/appium/bootstrap
[debug] [UIAuto] Dynamic env: {"nodePath":"/Applications/Appium.app/Contents/Resources/node/bin/node","commandProxyClientPath":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js","instrumentsSock":"/var/folders/2g/gfsgrctx5bz2fkkrg05k5wjm9xxv5z/T/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":true,"autoDismissAlerts":false,"sendKeyStrategy":"grouped"}

[debug] [UIAuto] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...

[debug] [UIAuto] Dynamic bootstrap path: /Users/kateogar/Library/Application Support/appium/bootstrap/bootstrap-b06295ef2252fff6.js

[debug] [UIAuto] Reusing dynamic bootstrap: /Users/kateogar/Library/Application Support/appium/bootstrap/bootstrap-b06295ef2252fff6.js
[debug] [iOS] Running ios real device reset flow
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog

[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'

[debug] [iOS] Creating iDevice object with udid f097ce20a2f72eb208eeefdb135f73c6ddf805ec

[debug] [iOS] App is not installed. Will try to install the app.

[MJSONWP] Encountered internal error running command: Error: Installing MyNew.app failed
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/node-idevice/main.js:159:6
    at ChildProcess.exithandler (child_process.js:193:7)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)

**Comment by KateOgar** [comment]
Also, if remove closeApp() before removeApp(), that logs would be:

[MJSONWP] Encountered internal error running command: Error: Command failed: ideviceinstaller -u f097ce20a2f72eb208eeefdb135f73c6ddf805ec -u MyName.app
WARNING: Using "-u" for "--uninstall" is deprecated. Please use "-U" instead.

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)

**Comment by SrinivasanTarget** [comment]
@KateOgar Fixed here https://github.com/OniOni/node-idevice/pull/6

**Comment by SrinivasanTarget** [comment]
@KateOgar Feel free to reopen the issue if you hit the same.Closing this as fix is already released.

**Comment by SrinivasanTarget** [comment]
@triager please close

**Comment by abdul-rehman** [comment]
@SrinivasanTarget , i am using appium v:1.5.3, Xcode 7.3 and iOS 9.2 iphone 5S device. I am unable to execute IOSDriver.isAppInstalled(bundleId), IOSDriver.removeApp(bundleId). it throws exception "Driver is not ready, cannot execute isAppInstalled." . Please help

**Comment by SrinivasanTarget** [comment]
@abdul-rehman Can you please raise a new issue and add full list of appium logs as gist. Entire logs will help in debugging.
