### ISSUE TITLE
Appium v1.4.7 crashes on startup when used with chromium apk

### ISSUE THREAD

**Issue by bootstraponline** [appium/appium#5414]
See https://saucelabs.com/beta/tests/fe5458a178d24b7e9117b2abd5082c26/logs

ChromePublic.apk is available on this [linux build node](http://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Android/339607/)

```
2015-07-22 03:16:21:179 - warn: Appium support for versions of node < 0.12 has been deprecated and will be removed in a future version. Please upgrade!
2015-07-22 03:16:21:228 - info: Welcome to Appium v1.4.7 (REV 3b1a3b3ddffa1b74ce39015a7a6d46a55028e32c)
2015-07-22 03:16:21:229 - info: Appium REST http interface listener started on 0.0.0.0:4443
2015-07-22 03:16:21:231 - info: [debug] Non-default server args: {"app":"/tmp/tmp2Q9vbP/ChromePublic.apk","udid":"emulator-5554","port":4443,"callbackAddress":"127.0.0.1","logTimestamp":true,"logNoColors":true,"orientation":"portrait","selendroidPort":4725,"defaultCommandTimeout":0}
2015-07-22 03:16:21:231 - info: Console LogLevel: debug
2015-07-22 03:16:21:332 - info: --> POST /wd/hub/session {"desiredCapabilities":{"deviceName":"Android Emulator","webdriver.remote.quietExceptions":true,"proxy":{"proxyAutoconfigUrl":"http://127.0.0.1:19876/pac.js","proxyType":"PAC"},"newCommandTimeout":false,"platformVersion":"5.1","platformName":"Android"}}
2015-07-22 03:16:21:334 - info: Client User-Agent string: undefined
2015-07-22 03:16:21:335 - info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : webdriver.remote.quietExceptions, proxy
2015-07-22 03:16:21:337 - info: [debug] No appActivity desired capability or server param. Parsing from apk.
2015-07-22 03:16:21:337 - info: [debug] No appPackage desired capability or server param. Parsing from apk.
2015-07-22 03:16:21:337 - info: [debug] Using local app from command line: /tmp/tmp2Q9vbP/ChromePublic.apk
2015-07-22 03:16:21:338 - info: [debug] Creating new appium session 94fc0969-134d-457c-b448-98be3cff73fd
2015-07-22 03:16:21:339 - info: Starting android appium
2015-07-22 03:16:21:340 - info: [debug] Getting Java version
2015-07-22 03:16:21:423 - info: Java version is: 1.6.0_34
2015-07-22 03:16:21:424 - info: [debug] Checking whether adb is present
2015-07-22 03:16:21:425 - info: [debug] Using adb from /home/chef/android-sdk-linux/platform-tools/adb
2015-07-22 03:16:21:425 - info: [debug] Parsing package and activity from app manifest
2015-07-22 03:16:21:426 - info: [debug] Checking whether aapt is present
2015-07-22 03:16:21:426 - info: [debug] Using aapt from /home/chef/android-sdk-linux/build-tools/19.1.0/aapt
2015-07-22 03:16:21:426 - info: [debug] Extracting package and launch activity from manifest.
2015-07-22 03:16:21:427 - info: [debug] executing cmd: /home/chef/android-sdk-linux/build-tools/19.1.0/aapt dump badging /tmp/tmp2Q9vbP/ChromePublic.apk
2015-07-22 03:16:21:459 - info: [debug] badging package: org.chromium.chrome
2015-07-22 03:16:21:459 - info: [debug] badging act: null
2015-07-22 03:16:21:667 - warn: Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file
    at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:54)
    at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:540)
    at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:76)
    at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:68)
    at io.appium.apktools.AndroidManifestActivityHelper.decodeManifestXML(AndroidManifestActivityHelper.java:26)
    at io.appium.apktools.Main.main(Main.java:33)
Caused by: java.io.IOException: Expected: 0x001c0001, got: 0x00000000
    at brut.util.ExtDataInput.skipCheckInt(ExtDataInput.java:48)
    at brut.androlib.res.decoder.StringBlock.read(StringBlock.java:43)
    at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:100)
    at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:81)
    at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:49)
    ... 5 more
```

**Comment by bootstraponline** [comment]
In terms of chrome + appium on arm emulators, it looks like [google hasn't made any progress in two years](https://code.google.com/p/chromedriver/issues/detail?id=352). I'll give up on that for now.

**Comment by bootstraponline** [comment]
Even with an x86 build of chrome, [this error](https://code.google.com/p/chromedriver/issues/detail?id=845) keeps happening. The appium chromedriver is out of date (2.16 is out).

https://saucelabs.com/beta/tests/f39c00bba89644efbb5f080aa54dd2d7/logs

**Comment by bootstraponline** [comment]
Appium crashes on [regular chrome](https://saucelabs.com/beta/tests/c99902002e3d40ceb23d21fcb6c9ab52/logs) as well. It's painful because even if you specify `appPackage` and `appActivity`, appium happily ignores that `app` was set and uses the on device version instead of attempting to install the newer version (via app apk).
