### ISSUE TITLE
error: Error. Could not find button to launch Safari. Make sure you are using the latest version of SafariLauncher that appium is using

### ISSUE THREAD

**Issue by nikolmarku1** [appium/appium#5419]
Appium v1.4.8 (REV ca00c8b799957b8e69e513d981d98c6f507f269b)   same with 1.4.1
"iPad 1 mini",
"platformName":"iOS",
"platformVersion":"8.4","

Safari browser is open and it shows the blank page as configured on pref
SafariLauncher base app download from  :https://github.com/budhash/SafariLauncher 

log
====
Last login: Wed Jul 22 16:21:46 on ttys001
autotestmac:~ qa$ /Users/qa/automation/selenium/appium/ios/4_start-appium-ios-MiniTablet-latest.csh ; exit;
Start Appium Server
On port : 4724
2015-07-22 16:23:58:350 - info: Welcome to Appium v1.4.8 (REV ca00c8b799957b8e69e513d981d98c6f507f269b)
2015-07-22 16:23:58:354 - info: Appium REST http interface listener started on 10.24.208.226:4724
2015-07-22 16:23:58:358 - info: [debug] Non-default server args: {"udid":"8f3875eefad92b632c7f9227de1b49027dc13066","address":"10.24.208.226","port":4724,"sessionOverride":true,"fullReset":true,"launchTimeout":"40000","log":"/tmp/appiumNM.log","logTimestamp":true,"localTimezone":true,"safari":true,"deviceName":"iPad 1 mini","platformName":"iOS","platformVersion":"8.4","nodeconfig":"/Users/qa/automation/selenium/appium/ios/configIpadmini.json","defaultCommandTimeout":70000}
2015-07-22 16:23:58:358 - info: Console LogLevel: debug
2015-07-22 16:23:58:359 - info: File LogLevel: debug
2015-07-22 16:23:58:362 - info: [debug] starting auto register thread for grid. Will try to register every 7000 ms.
2015-07-22 16:24:05:694 - info: [debug] Appium successfully registered with the grid on usb-etbuild5:4444
2015-07-22 16:24:14:898 - info: --> POST /wd/hub/session {"desiredCapabilities":{"app":"Safari","elementScrollBehavior":"elementScrollBehavior","javascriptEnabled":"true","browserName":"safari","appActivity":"","launchTimeout":40000,"networkConnectionEnabled":"true","safariOpenLinksInBackground":true,"udid":"8f3875eefad92b632c7f9227de1b49027dc13066","newCommandTimeout":60,"platformVersion":"8.4","platformName":"iOS","deviceName":"iPad 1 mini","bundleId":"com.englishtown.mobile","takesScreenshot":"true"}}
2015-07-22 16:24:14:900 - info: Client User-Agent string: Apache-HttpClient/4.3.3 (java 1.5)
2015-07-22 16:24:14:901 - warn: Converting cap javascriptEnabled from string to boolean. This might cause unexpected behavior.
2015-07-22 16:24:14:901 - warn: Converting cap networkConnectionEnabled from string to boolean. This might cause unexpected behavior.
2015-07-22 16:24:14:901 - warn: Converting cap takesScreenshot from string to boolean. This might cause unexpected behavior.
2015-07-22 16:24:14:903 - info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : elementScrollBehavior, javascriptEnabled, networkConnectionEnabled, takesScreenshot
2015-07-22 16:24:14:904 - info: [debug] Configuring Safari session
2015-07-22 16:24:14:905 - info: [debug] Using local .zip from desired caps: /Users/qa/automation/appium/appium1-4-8/build/SafariLauncher/SafariLauncher.zip
2015-07-22 16:24:14:905 - info: [debug] Copying local zip to tmp dir
2015-07-22 16:24:14:910 - info: [debug] /Users/qa/automation/appium/appium1-4-8/build/SafariLauncher/SafariLauncher.zip copied to /var/folders/xn/zxrl7n3x6vd33s2_mt6b696c0000gn/T/115622-834-nj7xfb/appium-app.zip
2015-07-22 16:24:14:920 - info: [debug] Unzipping /var/folders/xn/zxrl7n3x6vd33s2_mt6b696c0000gn/T/115622-834-nj7xfb/appium-app.zip
2015-07-22 16:24:14:920 - info: [debug] Testing zip archive: /var/folders/xn/zxrl7n3x6vd33s2_mt6b696c0000gn/T/115622-834-nj7xfb/appium-app.zip
2015-07-22 16:24:14:928 - info: [debug] Zip archive tested clean
2015-07-22 16:24:14:937 - info: [debug] Unzip successful
2015-07-22 16:24:14:937 - info: [debug] Using locally extracted app: /var/folders/xn/zxrl7n3x6vd33s2_mt6b696c0000gn/T/115622-834-nj7xfb/SafariLauncher.app
2015-07-22 16:24:14:938 - info: [debug] Creating new appium session 3686ec37-ea6c-4d61-bf3e-ee65081e4a34
2015-07-22 16:24:14:940 - info: [debug] Removing any remaining instruments sockets
2015-07-22 16:24:14:941 - info: [debug] Cleaned up instruments socket /tmp/instruments_sock
2015-07-22 16:24:14:941 - info: [debug] Auto-detecting iOS udid...
2015-07-22 16:24:14:942 - info: [debug] Not auto-detecting udid, running on sim
2015-07-22 16:24:14:943 - info: [debug] Could not parse plist file (as binary) at /var/folders/xn/zxrl7n3x6vd33s2_mt6b696c0000gn/T/115622-834-nj7xfb/SafariLauncher.app/en.lproj/Localizable.strings
2015-07-22 16:24:14:943 - info: Will try to parse the plist file as XML
2015-07-22 16:24:14:943 - info: [debug] Could not parse plist file (as XML) at /var/folders/xn/zxrl7n3x6vd33s2_mt6b696c0000gn/T/115622-834-nj7xfb/SafariLauncher.app/en.lproj/Localizable.strings
2015-07-22 16:24:14:944 - warn: Could not parse app Localizable.strings assuming it doesn't exist
2015-07-22 16:24:14:944 - info: [debug] Creating instruments
2015-07-22 16:24:14:945 - info: [debug] Preparing uiauto bootstrap
2015-07-22 16:24:14:945 - info: [debug] Dynamic bootstrap dir: /Users/qa/Library/Application Support/appium/bootstrap
2015-07-22 16:24:14:945 - info: [debug] Dynamic env: {"nodePath":"/usr/local/bin/node","commandProxyClientPath":"/Users/qa/automation/appium/appium1-4-8/submodules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"grouped"}
...5-07-22 16:24:14:950 - info: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
2015-07-22 16:24:14:950 - info: [debug] Dynamic bootstrap path: /Users/qa/Library/Application Support/appium/bootstrap/bootstrap-6b7249f1b0d1faef.js
2015-07-22 16:24:14:953 - info: [debug] Reusing dynamic bootstrap: /Users/qa/Library/Application Support/appium/bootstrap/bootstrap-6b7249f1b0d1faef.js
2015-07-22 16:24:14:955 - info: [debug] Attempting iOS device log capture via libimobiledevice idevicesyslog
2015-07-22 16:24:15:095 - info: [debug] Creating iDevice object with udid 8f3875eefad92b632c7f9227de1b49027dc13066
2015-07-22 16:24:19:368 - info: [debug] Starting command proxy.
2015-07-22 16:24:19:369 - info: [debug] Instruments socket server started at /tmp/instruments_sock
2015-07-22 16:24:19:370 - info: [debug] Starting instruments
2015-07-22 16:24:19:400 - info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
2015-07-22 16:24:19:400 - info: Launching instruments
2015-07-22 16:24:19:408 - info: [debug] Attempting to run app on real device with UDID 8f3875eefad92b632c7f9227de1b49027dc13066
2015-07-22 16:24:19:420 - info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w 8f3875eefad92b632c7f9227de1b49027dc13066 com.englishtown.mobile -e UIASCRIPT "/Users/qa/Library/Application Support/appium/bootstrap/bootstrap-6b7249f1b0d1faef.js" -e UIARESULTSPATH /tmp/appium-instruments
2015-07-22 16:24:19:420 - info: [debug] And extra without-delay env: {}
2015-07-22 16:24:19:420 - info: [debug] And launch timeouts (in ms): {"global":40000}
2015-07-22 16:24:20:219 - info: [debug] [INST STDERR] 2015-07-22 16:24:20.218 instruments[857:111932] WebKit Threading Violation - initial use of WebKit from a secondary thread.
2015-07-22 16:24:22:205 - info: Instruments is ready to receive commands
2015-07-22 16:24:22:206 - info: [debug] Instruments launched. Starting poll loop for new commands.
2015-07-22 16:24:22:206 - info: [debug] Setting bootstrap config keys/values
2015-07-22 16:24:22:206 - info: [debug] Pushing command to appium work queue: "target = $.target();\nau = $;\n$.isVerbose = true;\n"
2015-07-22 16:24:22:209 - info: [debug] Socket data received (2 bytes)
2015-07-22 16:24:22:210 - info: [debug] Socket data being routed.
2015-07-22 16:24:22:210 - info: [debug] Sending command to instruments: target = $.target();
au = $;
$.isVerbose = true;

2015-07-22 16:24:23:089 - info: [debug] [INST] 2015-07-22 15:24:23 +0000 Debug: evaluation finished
2015-07-22 16:24:23:090 - info: [debug] [INST] 2015-07-22 15:24:23 +0000 Debug: responding with:
2015-07-22 16:24:23:091 - info: [debug] [INST] 2015-07-22 15:24:23 +0000 Debug: Running system command #1: /usr/local/bin/node /Users/qa/automation/appium/appium1-4-8/submodules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":true}...
2015-07-22 16:24:23:172 - info: [debug] Socket data received (27 bytes)
2015-07-22 16:24:23:173 - info: [debug] Socket data being routed.
2015-07-22 16:24:23:173 - info: [debug] Got result from instruments: {"status":0,"value":true}
2015-07-22 16:24:23:174 - info: [debug] Not setting initial orientation because we're on SafariLauncher
2015-07-22 16:24:23:175 - info: [debug] Waiting for app source to contain elements
2015-07-22 16:24:23:176 - info: [debug] Pushing command to appium work queue: "au.mainApp().getTreeForXML()"
2015-07-22 16:24:23:177 - info: [debug] Sending command to instruments: au.mainApp().getTreeForXML()
2015-07-22 16:24:24:180 - info: [debug] [INST] 2015-07-22 15:24:24 +0000 Debug: Got new command 1 from instruments: au.mainApp().getTreeForXML()
2015-07-22 16:24:24:181 - info: [debug] [INST] 2015-07-22 15:24:24 +0000 Debug: evaluating au.mainApp().getTreeForXML()
2015-07-22 16:24:24:330 - info: [debug] [INST] 2015-07-22 15:24:24 +0000 Debug: evaluation finished
2015-07-22 16:24:24:330 - info: [debug] [INST] 2015-07-22 15:24:24 +0000 Debug: responding with:"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0","x":0,"y":0,"width":1024,"height":768},">":[{"UIAStaticText":{"@":{"name":"Safari Launcher","label":"Safari Launcher","value":"Safari Launcher","dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/0","x":256,"y":384,"width":512,"height":50},">":[]}},{"UIAStaticText":{"@":{"name":"  Pausing 05 seconds before launch","label":"  Pausing 05 seconds before launch","value":"  Pausing 05 seconds before launch","dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/1","x":0,"y":718,"width":1024,"height":50},">":[]}}]}},{"UIAWindow":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/1","x":0,"y":0,"width":1024,"height":768},">":[{"UIAStatusBar":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/1/0","x":0,"y":0,"width":1024,"height":20},">":[{"UIAElement":{"@":{"name":"iPad","label":"iPad","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":"Swipe down with three fingers to reveal the notification center., Swipe up with three fingers to reveal the control center, Double-tap to scroll to top","path":"/0/1/0/0","x":6,"y":0,"width":26,"height":20},">":[]}},{"UIAElement":{"@":{"name":"3 of 3 Wi-Fi bars","label":"3 of 3 Wi-Fi bars","value":"EF-Staff","dom":null,"enabled":true,"valid":true,"visible":true,"hint":"Swipe down with three fingers to reveal the notification center., Swipe up with three fingers to reveal the control center, Double-tap to scroll to top","path":"/0/1/0/1","x":37,"y":0,"width":13,"height":20},">":[]}},{"UIAElement":{"@":{"name":"16:24","label":"16:24","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":"Swipe down with three fingers to reveal the notification center., Swipe up with three fingers to reveal the control center, Double-tap to scroll to top","path":"/0/1/0/2","x":497,"y":0,"width":30,"height":20},">":[]}},{"UIAElement":{"@":{"name":"100% battery power, On AC Power","label":"100% battery power, On AC Power","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":"Swipe down with three fingers to reveal the notification center., Swipe up with three fingers to reveal the control center, Double-tap to scroll to top","path":"/0/1/0/3","x":951,"y":0,"width":68,"height":20},">":[]}}]}}]}}]}}}
2015-07-22 16:24:24:331 - info: [debug] [INST] 2015-07-22 15:24:24 +0000 Debug: Running system command #2: /usr/local/bin/node /Users/qa/automation/appium/appium1-4-8/submodules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":{"UIAApplication":{"@":{"name":"SafariLauncher","label":"SafariLauncher","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hi...
2015-07-22 16:24:24:423 - info: [debug] Socket data received (2766 bytes)
2015-07-22 16:24:24:423 - info: [debug] Socket data being routed.
2015-07-22 16:24:24:423 - info: [debug] Got result from instruments: {"status":0,"value":{"UIAApplication":{"@":{"name":"SafariLauncher","label":"SafariLauncher","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0","x":20,"y":-256,"width":748,"height":1024},">":[{"UIAWindow":{"@":{"name":null,"label":null,"value":null,"dom":null,
2015-07-22 16:24:24:424 - info: [debug] On Safari Launcher. Tapping button to launch Safari
2015-07-22 16:24:24:425 - info: [debug] Waiting up to 0ms for condition
2015-07-22 16:24:24:426 - info: [debug] Pushing command to appium work queue: "au.getElementByAccessibilityId('launch safari')"
2015-07-22 16:24:24:426 - info: [debug] Sending command to instruments: au.getElementByAccessibilityId('launch safari')
2015-07-22 16:24:25:429 - info: [debug] [INST] 2015-07-22 15:24:25 +0000 Debug: Got new command 2 from instruments: au.getElementByAccessibilityId('launch safari')
2015-07-22 16:24:25:430 - info: [debug] [INST] 2015-07-22 15:24:25 +0000 Debug: evaluating au.getElementByAccessibilityId('launch safari')
2015-07-22 16:24:25:431 - info: [debug] [INST] 2015-07-22 15:24:25 +0000 Debug: evaluation finished
2015-07-22 16:24:25:432 - info: [debug] [INST] 2015-07-22 15:24:25 +0000 Debug: responding with:
2015-07-22 16:24:25:433 - info: [debug] [INST] 2015-07-22 15:24:25 +0000 Debug: Running system command #3: /usr/local/bin/node /Users/qa/automation/appium/appium1-4-8/submodules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":""}...
2015-07-22 16:24:25:520 - info: [debug] Socket data received (25 bytes)
2015-07-22 16:24:25:520 - info: [debug] Socket data being routed.
2015-07-22 16:24:25:521 - info: [debug] Got result from instruments: {"status":0,"value":""}
2015-07-22 16:24:25:521 - info: [debug] Condition unmet after 1095ms. Timing out.
2015-07-22 16:24:25:521 - error: Error. Could not find button to launch Safari. Make sure you are using the latest version of SafariLauncher that appium is using
2015-07-22 16:24:25:522 - info: [debug] Cleaning up appium session
2015-07-22 16:24:25:523 - error: Failed to start an Appium session, err was: Error: Error. Could not find button to launch Safari. Make sure you are using the latest version of SafariLauncher that appium is using
2015-07-22 16:24:25:527 - info: [debug] Error: Error. Could not find button to launch Safari. Make sure you are using the latest version of SafariLauncher that appium is using
    at [object Object].<anonymous> (/Users/qa/automation/appium/appium1-4-8/lib/devices/ios/safari.js:70:17)
    at [object Object].<anonymous> (/Users/qa/automation/appium/appium1-4-8/lib/devices/common.js:77:12)
    at [object Object].iOSController.handleFindCb (/Users/qa/automation/appium/appium1-4-8/lib/devices/ios/ios-controller.js:313:5)
    at [object Object].<anonymous> (/Users/qa/automation/appium/appium1-4-8/lib/devices/ios/ios-controller.js:138:14)
    at next (/Users/qa/automation/appium/appium1-4-8/node_modules/async/lib/async.js:798:43)
    at /Users/qa/automation/appium/appium1-4-8/node_modules/async/lib/async.js:32:16
    at [object Object].exports.respond (/Users/qa/automation/appium/appium1-4-8/lib/devices/common.js:28:9)
    at [object Object].<anonymous> (/Users/qa/automation/appium/appium1-4-8/lib/devices/ios/ios.js:1479:18)
    at getResultAndSendNext (/Users/qa/automation/appium/appium1-4-8/submodules/appium-uiauto/lib/command-proxy.js:146:20)
    at Socket.<anonymous> (/Users/qa/automation/appium/appium1-4-8/submodules/appium-uiauto/lib/command-proxy.js:88:7)
    at Socket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickDomainCallback (node.js:381:11)
2015-07-22 16:24:25:527 - info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Error. Could not find button to launch Safari. Make sure you are using the latest version of SafariLauncher that appium is using)","origValue":"Error. Could not find button to launch Safari. Make sure you are using the latest version of SafariLauncher that appium is using"},"sessionId":null}
2015-07-22 16:24:25:531 - info: <-- POST /wd/hub/session 500 10633.739 ms - 378 
====

**Comment by nikolmarku1** [comment]
updated safari launcher using https://github.com/snevesbarros/SafariLauncher
and now this error is gone but getting a new error: tried ios 8.2 and 8.4  [ipad real device]

2015-07-23 12:23:19:357 - info: [debug] Navigating to most recently opened webview
2015-07-23 12:23:19:357 - info: [debug] [REMOTE] Getting WebKitRemoteDebugger pageArray
2015-07-23 12:23:19:359 - warn: Could not find any webviews yet, refreshing/retrying
....
2015-07-23 12:23:31:480 - warn: Could not find any webviews yet, refreshing/retrying
2015-07-23 12:23:31:984 - info: [debug] [REMOTE] Getting WebKitRemoteDebugger pageArray
2015-07-23 12:23:31:986 - error: [REMOTE] Could not connect to WebKitRemoteDebugger server
2015-07-23 12:23:31:986 - info: [debug] Cleaning up appium session
2015-07-23 12:23:31:987 - error: Failed to start an Appium session, err was: Error: Could not navigate to webview! Err: Error: connect ECONNREFUSED
2015-07-23 12:23:31:990 - info: [debug] Error: Could not navigate to webview! Err: Error: connect ECONNREFUSED
    at [object Object].<anonymous> (/Users/qa/automation/appium/appium1-4-8/lib/devices/ios/ios.js:1701:12)
    at [object Object].<anonymous> (/Users/qa/automation/appium/appium1-4-8/lib/devices/ios/ios.js:1592:21)
    at [object Object].<anonymous> (/Users/qa/automation/appium/appium1-4-8/lib/devices/ios/ios.js:1579:21)
    at [object Object].<anonymous> (/Users/qa/automation/appium/appium1-4-8/lib/devices/ios/ios-hybrid.js:62:21)
    at [object Object].<anonymous> (/Users/qa/automation/appium/appium1-4-8/lib/devices/ios/webkit-remote-debugger.js:77:14)
    at ClientRequest.<anonymous> (/Users/qa/automation/appium/appium1-4-8/node_modules/underscore/underscore.js:890:21)
    at ClientRequest.emit (events.js:107:17)
    at Socket.socketErrorListener (_http_client.js:272:9)
    at Socket.emit (events.js:107:17)
    at net.js:451:14
    at process._tickDomainCallback (node.js:381:11)
2015-07-23 12:23:31:990 - info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Could not navigate to webview! Err: Error: connect ECONNREFUSED)","origValue":"Could not navigate to webview! Err: Error: connect ECONNREFUSED"},"sessionId":null}
2015-07-23 12:23:31:991 - info: <-- POST /wd/hub/session 500 26250.703 ms - 248 

------
on ios proxy  disconnected error is shown
------------
i.recv_packet[348]:
 00 00 01 58 62 70 6C 69 73 74 30 30 D1 01 02 5F 10 12 57  ...Xbplist00..._..W
 49 52 46 69 6E 61 6C 4D 65 73 73 61 67 65 4B 65 79 4F 11  IRFinalMessageKeyO.
 01 0E 62 70 6C 69 73 74 30 30 D2 01 02 03 04 5A 5F 5F 73  ..bplist00.....Z__s
 65 6C 65 63 74 6F 72 5A 5F 5F 61 72 67 75 6D 65 6E 74 5F  electorZ__argument_
 10 1C 5F 72 70 63 5F 61 70 70 6C 69 63 61 74 69 6F 6E 53  .._rpc_applicationS
 65 6E 74 4C 69 73 74 69 6E 67 3A D2 05 06 07 08 5F 10 1B  entListing:....._..
 57 49 52 41 70 70 6C 69 63 61 74 69 6F 6E 49 64 65 6E 74  WIRApplicationIdent
 69 66 69 65 72 4B 65 79 5D 57 49 52 4C 69 73 74 69 6E 67  ifierKey]WIRListing
 4B 65 79 57 50 49 44 3A 32 30 32 D1 09 0A                 KeyWPID:202...
 51 31 D4 0B 0C 0D 0E 0F 10 11 12 5F 10 14 57 49 52 50 61  Q1........._..WIRPa
 67 65 49 64 65 6E 74 69 66 69 65 72 4B 65 79 59 57 49 52  geIdentifierKeyYWIR
 55 52 4C 4B 65 79 5B 57 49 52 54 69 74 6C 65 4B 65 79 5A  URLKey[WIRTitleKeyZ
 57 49 52 54 79 70 65 4B 65 79 10 01 5B 61 62 6F 75 74 3A  WIRTypeKey..[about:
 62 6C 61 6E 6B 50 5A 57 49 52 54 79 70 65 57 65 62 08 0D  blankPZWIRTypeWeb..
 18 23 42 47 65 73 7B 7E 80 89 A0 AA B6 C1 C3 CF D0 00 00  .#BGes{~...........
 00 00 00 00 01 01 00 00 00 00 00 00 00 13 00 00 00 00 00  ...................
 00 00 00 00 00 00 00 00 00 00 DB 00 08 00 0B 00 20 00 00  ................ ..
 00 00 00 00 02 01 00 00 00 00 00 00 00 03 00 00 00 00 00  ...................
 00 00 00 00 00 00 00 00 00 01 32                          ..........2
ss.remove_fd(6)
Disconnected :27753 from iPad (5c51da6a55e9c416506eefd0b25a214f17408d7e)
ss.remove_server_fd(4)
ss.remove_fd(3)

child process exited with code 0
stdout: ss.add_fd(3)
ss.recv fd=3 len=294
ss.recv fd=3 len=685
ss.add_server_fd(4)
ss.add_fd(6)
wi.send_packet[245]:
 00 00 00 F1 62 70 6C 69 73 74 30 30 D1 01 02 5F 10 12 57  ....bplist00..._..W
 49 52 46 69 6E 61 6C 4D 65 73 73 61 67 65


thanks for your help

**Comment by rahuljawale** [comment]
Wild guess, do you have `autoWebview` capability set by any chance?

**Comment by nikolmarku1** [comment]
capability.setCapability(MobileCapabilityType.PLATFORM_NAME, platformName);
        capability.setCapability(MobileCapabilityType.PLATFORM_VERSION, version);
        capability.setCapability(MobileCapabilityType.BROWSER_NAME, browserName);
        capability.setCapability(MobileCapabilityType.DEVICE_NAME, deviceName);
        capability.setCapability(MobileCapabilityType.ELEMENT_SCROLL_BEHAVIOR, "elementScrollBehavior");
        capability.setCapability(MobileCapabilityType.APP_ACTIVITY, "");
 capability.setCapability(MobileCapabilityType.SUPPORTS_JAVASCRIPT, "true");
        capability.setCapability(MobileCapabilityType.SUPPORTS_NETWORK_CONNECTION, "true");
        capability.setCapability(MobileCapabilityType.TAKES_SCREENSHOT, "true");
        capability.setCapability(MobileCapabilityType.LAUNCH_TIMEOUT, "40000");

              capability.setCapability("app","Safari");
            capability.setCapability("udid","8f3875eefad92b632c7f9227de1b49027dc13066");
            capability.setCapability("bundleId", "SafariLauncher");
            //capability.setCapability("safariAllowPopups", false);
            capability.setCapability("safariOpenLinksInBackground", true);
            capability.setCapability("newCommandTimeout", 60);
            capability.setCapability("launchTimeout", 40000);

**Comment by nikolmarku1** [comment]
Thanks rahul; 
I will close this and raise a new one as I have made many changes - update/reset - new app .... hope all of these setup issues will be fixed ....  so easy on android ....
Appium log error I think is due to the wrong version of SafariLauncher - that had not defined accessibility for launching button in the middle of the app -  Used a different repository and  fixed that issue. 
Building the app SafariLauncher for version iOS tablet 8.4 still have issues; but building it for 8.2 works ; at least some of the time-> very temperamental ->  

still see the ios proxy issue though ...

Note: raised a new issue on : https://github.com/appium/appium/issues/5431

**Comment by nikolmarku1** [comment]
thanks
