### ISSUE TITLE
Appium server error taking screenshot 1.4.8: uncaughtException: undefined is not a function

### ISSUE THREAD

**Issue by nikolmarku1** [appium/appium#5431]
iTab mini iOS 8.4 run from source 1.4.8
Welcome to Appium v1.4.8 (REV ca00c8b799957b8e69e513d981d98c6f507f269b)

I think probably something to do with :
Could not take screenshot
/Users/qa/automation/appium/appium1-4-8/node_modules/async/lib/async.js:712
            callback();
            ^
           TypeError: undefined is not a function
Thanks
Niko
# log

Welcome to Appium v1.4.8 (REV ca00c8b799957b8e69e513d981d98c6f507f269b)
2015-07-24 09:20:38:939 - info: Appium REST http interface listener started on 10.24.208.226:4724
2015-07-24 09:20:38:943 - info: [debug] Non-default server args: {"udid":"8f3875eefad92b632c7f9227de1b49027dc13066","address":"10.24.208.226","port":4724,"sessionOverride":true,"fullReset":true,"launchTimeout":"40000","log":"/tmp/appiumNM.log","logTimestamp":true,"localTimezone":true,"safari":true,"deviceName":"iPad 1 mini","platformName":"iOS","platformVersion":"8.4","nodeconfig":"/Users/qa/automation/selenium/appium/ios/configIpadmini.json","defaultCommandTimeout":40000}

---

2015-07-24 09:36:50:661 - info: [debug] Socket data received (28 bytes)
2015-07-24 09:36:50:662 - info: [debug] Socket data being routed.
2015-07-24 09:36:50:662 - info: [debug] Got result from instruments: {"status":0,"value":false}
2015-07-24 09:36:50:663 - info: [debug] Pushing command to appium work queue: "au.capture('screenshotda075b88-bea9-459d-b0ca-c50e542b4f4a')"
2015-07-24 09:36:50:663 - info: [debug] Waiting 10000 ms for screenshot to ge generated.
2015-07-24 09:36:56:239 - error: Could not remove com.apple.mobilesafari from device
2015-07-24 09:36:56:240 - info: [debug] Cleaning up appium session
2015-07-24 09:36:56:240 - info: [debug] We shut down because no new commands came in
2015-07-24 09:37:00:934 - error: uncaughtException: undefined is not a function date=Fri Jul 24 2015 09:37:00 GMT+0100 (BST), pid=571, uid=501, gid=20, cwd=/Users/qa/automation/appium/appium1-4-8, execPath=/usr/local/bin/node, version=v0.12.1, argv=[node, /Users/qa/automation/appium/appium1-4-8, -p, 4724, --address, 10.24.208.226, --command-timeout, 40000, --session-override, --log, /tmp/appiumNM.log, --log-timestamp, --nodeconfig, /Users/qa/automation/selenium/appium/ios/configIpadmini.json, --local-timezone, --platform-version, 8.4, --platform-name, iOS, --udid, 8f3875eefad92b632c7f9227de1b49027dc13066, --safari, --full-reset, --device-name, iPad 1 mini, --launch-timeout, 40000], rss=145215488, heapTotal=121522432, heapUsed=70629640, loadavg=[1.115234375, 1.1396484375, 1.029296875], uptime=1475, trace=[column=24, file=/Users/qa/automation/appium/appium1-4-8/lib/devices/ios/ios-controller.js, function=null, line=1296, method=null, native=false, column=13, file=/Users/qa/automation/appium/appium1-4-8/node_modules/async/lib/async.js, function=Object.async.until, line=712, method=async.until, native=false, column=23, file=/Users/qa/automation/appium/appium1-4-8/node_modules/async/lib/async.js, function=null, line=708, method=null, native=false, column=19, file=/Users/qa/automation/appium/appium1-4-8/lib/devices/ios/ios-controller.js, function=null, line=1290, method=null, native=false, column=20, file=fs.js, function=null, line=265, method=null, native=false, column=15, file=fs.js, function=FSReqWrap.oncomplete, line=99, method=oncomplete, native=false], stack=[TypeError: undefined is not a function,     at /Users/qa/automation/appium/appium1-4-8/lib/devices/ios/ios-controller.js:1296:24,     at Object.async.until (/Users/qa/automation/appium/appium1-4-8/node_modules/async/lib/async.js:712:13),     at /Users/qa/automation/appium/appium1-4-8/node_modules/async/lib/async.js:708:23,     at /Users/qa/automation/appium/appium1-4-8/lib/devices/ios/ios-controller.js:1290:19,     at fs.js:265:20,     at FSReqWrap.oncomplete (fs.js:99:15)]

/Users/qa/automation/appium/appium1-4-8/node_modules/async/lib/async.js:712
            callback();
            ^
TypeError: undefined is not a function
    at /Users/qa/automation/appium/appium1-4-8/lib/devices/ios/ios-controller.js:1296:24
    at Object.async.until (/Users/qa/automation/appium/appium1-4-8/node_modules/async/lib/async.js:712:13)
    at /Users/qa/automation/appium/appium1-4-8/node_modules/async/lib/async.js:708:23
    at /Users/qa/automation/appium/appium1-4-8/lib/devices/ios/ios-controller.js:1290:19
    at fs.js:265:20
    at FSReqWrap.oncomplete (fs.js:99:15)
logout

**Comment by sebv** [comment]
Looks like a bug during shutdown.
