### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: unknown error: an X display is required for keycode conversions, consider using Xvfb

### ISSUE THREAD

**Issue by shadeimi** [appium/appium#5446]
I've this test:
from appium import webdriver
from selenium.webdriver.common.keys import Keys

capabilities = {"version":"5.0", "deviceName":"ANDROID","browserName":"chrome","platformName":"ANDROID","id":"5bf1e9de2372193b"}

driver = webdriver.Remote(
   command_executor='http://selenium.preprod.xxxx.com:4444/wd/hub',
   desired_capabilities=capabilities)

driver.get("http://www.python.org")
assert "Python" in driver.title
elem = driver.find_element_by_name("q")
elem.send_keys("pycon")
elem.send_keys(Keys.RETURN)
assert "No results found." not in driver.page_source
driver.close()

executing it using appium 1.4.8 i got:

(rfSandbox)[qaautomation@localhost ~]$ python grid.py
Traceback (most recent call last):
  File "grid.py", line 17, in <module>
    elem.send_keys("pycon")
  File "/home/qaautomation/.virtualenvs/rfSandbox/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 321, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT, {'value': typing})
  File "/home/qaautomation/.virtualenvs/rfSandbox/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 447, in _execute
    return self._parent.execute(command, params)
  File "/home/qaautomation/.virtualenvs/rfSandbox/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 193, in execute
    self.error_handler.check_response(response)
  File "/home/qaautomation/.virtualenvs/rfSandbox/lib/python2.7/site-packages/appium/webdriver/errorhandler.py", line 29, in check_response
    raise wde
selenium.common.exceptions.WebDriverException: Message: unknown error: an X display is required for keycode conversions, consider using Xvfb
  (Session info: chrome=43.0.2357.93)
  (Driver info: chromedriver=2.16.333243 (0bfa1d3575fc1044244f21ddb82bf870944ef961),platform=Linux 3.10.0-229.7.2.el7.x86_64 x86_64)

these are the appium logs:

2015-07-29 15:07:08:900 - info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : id, version
2015-07-29 15:07:08:901 - info: Set mode: Proxying straight through to Chromedriver
2015-07-29 15:07:08:901 - info: [debug] Looks like we want chrome on android
2015-07-29 15:07:08:901 - info: [debug] Creating new appium session f4f1c7b9-c085-419b-b05d-3ed6fbd44c29
2015-07-29 15:07:08:901 - info: [debug] Checking whether adb is present
2015-07-29 15:07:08:902 - info: [debug] Using adb from /opt/android-sdk-linux/platform-tools/adb
2015-07-29 15:07:08:902 - info: [debug] Using fast reset? true
2015-07-29 15:07:08:902 - info: [debug] Preparing device for session
2015-07-29 15:07:08:902 - info: [debug] Not checking whether app is present since we are assuming it's already on the device
2015-07-29 15:07:08:902 - info: Retrieving device
2015-07-29 15:07:08:902 - info: [debug] Trying to find a connected android device
2015-07-29 15:07:08:902 - info: [debug] Getting connected devices...
2015-07-29 15:07:08:903 - info: [debug] executing cmd: /opt/android-sdk-linux/platform-tools/adb devices
2015-07-29 15:07:08:914 - info: [debug] 1 device(s) connected
2015-07-29 15:07:08:914 - info: Found device LGD855c00a8047
2015-07-29 15:07:08:914 - info: [debug] Setting device id to LGD855c00a8047
2015-07-29 15:07:08:914 - info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
2015-07-29 15:07:08:914 - info: [debug] executing cmd: /opt/android-sdk-linux/platform-tools/adb -s LGD855c00a8047 wait-for-device
2015-07-29 15:07:08:925 - info: [debug] executing cmd: /opt/android-sdk-linux/platform-tools/adb -s LGD855c00a8047 shell "echo 'ready'"
2015-07-29 15:07:09:004 - info: [debug] Starting logcat capture
2015-07-29 15:07:09:113 - info: [debug] Pushing unlock helper app to device...
2015-07-29 15:07:09:114 - info: [debug] executing cmd: /opt/android-sdk-linux/platform-tools/adb -s LGD855c00a8047 install "/opt/appium_v1.4.8/build/unlock_apk/unlock_apk-debug.apk"
2015-07-29 15:07:10:729 - info: --> GET /wd/hub/status {}
2015-07-29 15:07:10:730 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}},"sessionId":"f4f1c7b9-c085-419b-b05d-3ed6fbd44c29"}
2015-07-29 15:07:10:731 - info: <-- GET /wd/hub/status 200 4.665 ms - 155 {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}},"sessionId":"f4f1c7b9-c085-419b-b05d-3ed6fbd44c29"}
2015-07-29 15:07:13:776 - info: [debug] executing cmd: /opt/android-sdk-linux/platform-tools/adb -s LGD855c00a8047 shell "dumpsys window"
2015-07-29 15:07:13:966 - info: [debug] Screen already unlocked, continuing.
2015-07-29 15:07:13:966 - info: [debug] Forwarding system:2254 to device:4724
2015-07-29 15:07:13:967 - info: [debug] executing cmd: /opt/android-sdk-linux/platform-tools/adb -s LGD855c00a8047 forward tcp:2254 tcp:4724
2015-07-29 15:07:13:994 - info: [debug] Pushing appium bootstrap to device...
2015-07-29 15:07:13:996 - info: [debug] executing cmd: /opt/android-sdk-linux/platform-tools/adb -s LGD855c00a8047 push "/opt/appium_v1.4.8/build/android_bootstrap/AppiumBootstrap.jar" /data/local/tmp/
2015-07-29 15:07:14:201 - info: Starting App
2015-07-29 15:07:14:201 - info: [debug] Attempting to kill all 'uiautomator' processes
2015-07-29 15:07:14:202 - info: [debug] Getting all processes with 'uiautomator'
2015-07-29 15:07:14:202 - info: [debug] executing cmd: /opt/android-sdk-linux/platform-tools/adb -s LGD855c00a8047 shell "ps 'uiautomator'"
2015-07-29 15:07:14:385 - info: [debug] No matching processes found
2015-07-29 15:07:14:386 - info: [debug] Running bootstrap
2015-07-29 15:07:14:386 - info: [debug] spawning: /opt/android-sdk-linux/platform-tools/adb -s LGD855c00a8047 shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.Bootstrap -e pkg com.android.chrome -e disableAndroidWatchers false
2015-07-29 15:07:15:011 - info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
2015-07-29 15:07:15:011 - info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
2015-07-29 15:07:15:012 - info: [debug] [UIAUTOMATOR STDOUT] io.appium.android.bootstrap.Bootstrap:
2015-07-29 15:07:15:012 - info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
2015-07-29 15:07:15:013 - info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
2015-07-29 15:07:15:013 - info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
2015-07-29 15:07:15:014 - info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
2015-07-29 15:07:15:014 - info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 1
2015-07-29 15:07:15:031 - info: [debug] [BOOTSTRAP] [debug] Socket opened on port 4724
2015-07-29 15:07:15:034 - info: [debug] [BOOTSTRAP] [debug] Appium Socket Server Ready
2015-07-29 15:07:15:035 - info: [debug] [BOOTSTRAP] [debug] Loading json...
2015-07-29 15:07:15:036 - info: [debug] Pushing command to appium work queue: ["getDataDir",{}]
2015-07-29 15:07:15:039 - info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.
2015-07-29 15:07:15:043 - info: [debug] [BOOTSTRAP] [debug] Client connected
2015-07-29 15:07:15:045 - info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"getDataDir","params":{}}
2015-07-29 15:07:15:047 - info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
2015-07-29 15:07:15:049 - info: [debug] [BOOTSTRAP] [debug] Got command action: getDataDir
2015-07-29 15:07:15:057 - info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":"\/data\/local\/tmp"}
2015-07-29 15:07:15:059 - info: [debug] dataDir set to: /data/local/tmp
2015-07-29 15:07:15:084 - info: Chromedriver: Set chromedriver binary as: /opt/appium_v1.4.8/node_modules/appium-chromedriver/chromedriver/linux/chromedriver_64
2015-07-29 15:07:15:085 - info: Chromedriver: Killing any old chromedrivers, running: ps -ef | grep /opt/appium_v1.4.8/node_modules/appium-chromedriver/chromedriver/linux/chromedriver_64 | grep -v grep |grep -e '--port=9519\(\s.*\)\?$' | awk '{ print $2 }' | xargs kill -15
2015-07-29 15:07:15:126 - info: Chromedriver: No old chromedrivers seemed to exist
2015-07-29 15:07:15:126 - info: Chromedriver: Spawning chromedriver with: /opt/appium_v1.4.8/node_modules/appium-chromedriver/chromedriver/linux/chromedriver_64 --url-base=wd/hub --port=9519
2015-07-29 15:07:15:144 - info: Chromedriver: [STDOUT] Starting ChromeDriver 2.16.333243 (0bfa1d3575fc1044244f21ddb82bf870944ef961) on port 9519
Only local connections are allowed.
2015-07-29 15:07:15:145 - info: JSONWP Proxy: Proxying [GET /status] to [GET http://127.0.0.1:9519/wd/hub/status] with no body
2015-07-29 15:07:15:149 - info: JSONWP Proxy: Got response with status 200: {"sessionId":"","status":0,"value":{"build":{"version":"alpha"},"os":{"arch":"x86_64","name":"Linux","version":"3.10.0-229.7.2.el7.x86_64"}}}
2015-07-29 15:07:15:150 - info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9519/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.chrome","androidDeviceSerial":"LGD855c00a8047"}}}
2015-07-29 15:07:15:776 - info: --> GET /wd/hub/status {}
2015-07-29 15:07:15:777 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}},"sessionId":"f4f1c7b9-c085-419b-b05d-3ed6fbd44c29"}
2015-07-29 15:07:15:779 - info: <-- GET /wd/hub/status 200 3.827 ms - 155 {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}},"sessionId":"f4f1c7b9-c085-419b-b05d-3ed6fbd44c29"}
2015-07-29 15:07:20:819 - info: --> GET /wd/hub/status {}
2015-07-29 15:07:20:819 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}},"sessionId":"f4f1c7b9-c085-419b-b05d-3ed6fbd44c29"}
2015-07-29 15:07:20:821 - info: <-- GET /wd/hub/status 200 2.512 ms - 155 {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}},"sessionId":"f4f1c7b9-c085-419b-b05d-3ed6fbd44c29"}
2015-07-29 15:07:20:854 - info: JSONWP Proxy: Got response with status 200: {"sessionId":"ea8ef0120f9ba75135835464b7cc67e9","status":0,"value":{"acceptSslCerts":true,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"browserName":"chrome","chrome":{},"cssSelect...
2015-07-29 15:07:20:855 - info: [debug] Overriding session id with "ea8ef0120f9ba75135835464b7cc67e9"
2015-07-29 15:07:20:856 - info: [debug] Device launched! Ready for commands
2015-07-29 15:07:20:856 - info: [debug] Setting command timeout to the default of 120 secs
2015-07-29 15:07:20:857 - info: [debug] Appium session started with sessionId ea8ef0120f9ba75135835464b7cc67e9
2015-07-29 15:07:20:858 - info: <-- POST /wd/hub/session 303 11958.246 ms - 70
2015-07-29 15:07:20:922 - info: --> GET /wd/hub/session/ea8ef0120f9ba75135835464b7cc67e9 {}
2015-07-29 15:07:20:924 - info: JSONWP Proxy: Proxying [GET /wd/hub/session/ea8ef0120f9ba75135835464b7cc67e9] to [GET http://127.0.0.1:9519/wd/hub/session/ea8ef0120f9ba75135835464b7cc67e9] with body: {}
2015-07-29 15:07:20:930 - info: JSONWP Proxy: Got response with status 200: {"sessionId":"ea8ef0120f9ba75135835464b7cc67e9","status":0,"value":{"acceptSslCerts":true,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"browserName":"chrome","chrome":{},"cssSelect...
2015-07-29 15:07:20:931 - info: JSONWP Proxy: Replacing sessionId ea8ef0120f9ba75135835464b7cc67e9 with ea8ef0120f9ba75135835464b7cc67e9
2015-07-29 15:07:20:932 - info: <-- GET /wd/hub/session/ea8ef0120f9ba75135835464b7cc67e9 200 10.475 ms - 529
2015-07-29 15:07:21:037 - info: --> POST /wd/hub/session/ea8ef0120f9ba75135835464b7cc67e9/url {"url":"http://www.python.org","sessionId":"ea8ef0120f9ba75135835464b7cc67e9"}
2015-07-29 15:07:21:040 - info: JSONWP Proxy: Proxying [POST /wd/hub/session/ea8ef0120f9ba75135835464b7cc67e9/url] to [POST http://127.0.0.1:9519/wd/hub/session/ea8ef0120f9ba75135835464b7cc67e9/url] with body: {"url":"http://www.python.org","sessionId":"ea8ef0120f9ba75135835464b7cc67e9"}
2015-07-29 15:07:25:179 - info: JSONWP Proxy: Got response with status 200: {"sessionId":"ea8ef0120f9ba75135835464b7cc67e9","status":0,"value":null}
2015-07-29 15:07:25:180 - info: JSONWP Proxy: Replacing sessionId ea8ef0120f9ba75135835464b7cc67e9 with ea8ef0120f9ba75135835464b7cc67e9
2015-07-29 15:07:25:181 - info: <-- POST /wd/hub/session/ea8ef0120f9ba75135835464b7cc67e9/url 200 4144.002 ms - 72
2015-07-29 15:07:25:265 - info: --> GET /wd/hub/session/ea8ef0120f9ba75135835464b7cc67e9/title {}
2015-07-29 15:07:25:267 - info: JSONWP Proxy: Proxying [GET /wd/hub/session/ea8ef0120f9ba75135835464b7cc67e9/title] to [GET http://127.0.0.1:9519/wd/hub/session/ea8ef0120f9ba75135835464b7cc67e9/title] with body: {}
2015-07-29 15:07:25:326 - info: JSONWP Proxy: Got response with status 200: {"sessionId":"ea8ef0120f9ba75135835464b7cc67e9","status":0,"value":"Welcome to Python.org"}
2015-07-29 15:07:25:327 - info: JSONWP Proxy: Replacing sessionId ea8ef0120f9ba75135835464b7cc67e9 with ea8ef0120f9ba75135835464b7cc67e9
2015-07-29 15:07:25:332 - info: <-- GET /wd/hub/session/ea8ef0120f9ba75135835464b7cc67e9/title 200 67.594 ms - 91
2015-07-29 15:07:25:414 - info: --> POST /wd/hub/session/ea8ef0120f9ba75135835464b7cc67e9/element {"using":"css selector","sessionId":"ea8ef0120f9ba75135835464b7cc67e9","value":"[name=\"q\"]"}
2015-07-29 15:07:25:415 - info: JSONWP Proxy: Proxying [POST /wd/hub/session/ea8ef0120f9ba75135835464b7cc67e9/element] to [POST http://127.0.0.1:9519/wd/hub/session/ea8ef0120f9ba75135835464b7cc67e9/element] with body: {"using":"css selector","sessionId":"ea8ef0120f9ba75135835464b7cc67e9","value":"[name=\"q\"]"}
2015-07-29 15:07:25:612 - info: JSONWP Proxy: Got response with status 200: {"sessionId":"ea8ef0120f9ba75135835464b7cc67e9","status":0,"value":{"ELEMENT":"0.28304815595038235-1"}}
2015-07-29 15:07:25:613 - info: JSONWP Proxy: Replacing sessionId ea8ef0120f9ba75135835464b7cc67e9 with ea8ef0120f9ba75135835464b7cc67e9
2015-07-29 15:07:25:614 - info: <-- POST /wd/hub/session/ea8ef0120f9ba75135835464b7cc67e9/element 200 200.568 ms - 103
2015-07-29 15:07:25:696 - info: --> POST /wd/hub/session/ea8ef0120f9ba75135835464b7cc67e9/element/0.28304815595038235-1/value {"sessionId":"ea8ef0120f9ba75135835464b7cc67e9","id":"0.28304815595038235-1","value":["p","y","c","o","n"]}
2015-07-29 15:07:25:698 - info: JSONWP Proxy: Proxying [POST /wd/hub/session/ea8ef0120f9ba75135835464b7cc67e9/element/0.28304815595038235-1/value] to [POST http://127.0.0.1:9519/wd/hub/session/ea8ef0120f9ba75135835464b7cc67e9/element/0.28304815595038235-1/value] with body: {"sessionId":"ea8ef0120f9ba75135835464b7cc67e9","id":"0.28304815595038235-1","value":["p","y","c","o","n"]}
2015-07-29 15:07:25:864 - info: --> GET /wd/hub/status {}
2015-07-29 15:07:25:865 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}},"sessionId":"ea8ef0120f9ba75135835464b7cc67e9"}
2015-07-29 15:07:25:867 - info: <-- GET /wd/hub/status 200 2.391 ms - 151 {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}},"sessionId":"ea8ef0120f9ba75135835464b7cc67e9"}
2015-07-29 15:07:26:474 - info: JSONWP Proxy: Got response with status 200: {"sessionId":"ea8ef0120f9ba75135835464b7cc67e9","status":13,"value":{"message":"unknown error: an X display is required for keycode conversions, consider using Xvfb\n  (Session info: chrome=43.0.2357....
2015-07-29 15:07:26:475 - info: JSONWP Proxy: Replacing sessionId ea8ef0120f9ba75135835464b7cc67e9 with ea8ef0120f9ba75135835464b7cc67e9
2015-07-29 15:07:26:476 - info: <-- POST /wd/hub/session/ea8ef0120f9ba75135835464b7cc67e9/element/0.28304815595038235-1/value 200 780.009 ms - 340
2015-07-29 15:07:30:907 - info: --> GET /wd/hub/status {}
2015-07-29 15:07:30:909 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}},"sessionId":"ea8ef0120f9ba75135835464b7cc67e9"}
2015-07-29 15:07:30:910 - info: <-- GET /wd/hub/status 200 2.976 ms - 151 {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}},"sessionId":"ea8ef0120f9ba75135835464b7cc67e9"}
2015-07-29 15:07:35:961 - info: --> GET /wd/hub/status {}
2015-07-29 15:07:35:961 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}},"sessionId":"ea8ef0120f9ba75135835464b7cc67e9"}
2015-07-29 15:07:35:963 - info: <-- GET /wd/hub/status 200 2.955 ms - 151 {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}},"sessionId":"ea8ef0120f9ba75135835464b7cc67e9"}
2015-07-29 15:07:41:009 - info: --> GET /wd/hub/status {}
2015-07-29 15:07:41:010 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}},"sessionId":"ea8ef0120f9ba75135835464b7cc67e9"}
2015-07-29 15:07:41:012 - info: <-- GET /wd/hub/status 200 2.935 ms - 151 {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}},"sessionId":"ea8ef0120f9ba75135835464b7cc67e9"}
2015-07-29 15:07:46:053 - info: --> GET /wd/hub/status {}
2015-07-29 15:07:46:054 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}},"sessionId":"ea8ef0120f9ba75135835464b7cc67e9"}
2015-07-29 15:07:46:056 - info: <-- GET /wd/hub/status 200 2.420 ms - 151 {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}},"sessionId":"ea8ef0120f9ba75135835464b7cc67e9"}
2015-07-29 15:07:49:295 - info: --> GET /wd/hub/status {}
2015-07-29 15:07:49:296 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}},"sessionId":"ea8ef0120f9ba75135835464b7cc67e9"}
2015-07-29 15:07:49:298 - info: <-- GET /wd/hub/status 200 2.256 ms - 151 {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}},"sessionId":"ea8ef0120f9ba75135835464b7cc67e9"}
2015-07-29 15:07:51:096 - info: --> GET /wd/hub/status {}
2015-07-29 15:07:51:096 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}},"sessionId":"ea8ef0120f9ba75135835464b7cc67e9"}
2015-07-29 15:07:51:098 - info: <-- GET /wd/hub/status 200 2.361 ms - 151 {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}},"sessionId":"ea8ef0120f9ba75135835464b7cc67e9"}
2015-07-29 15:07:56:138 - info: --> GET /wd/hub/status {}
2015-07-29 15:07:56:139 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}},"sessionId":"ea8ef0120f9ba75135835464b7cc67e9"}
2015-07-29 15:07:56:140 - info: <-- GET /wd/hub/status 200 2.403 ms - 151 {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}},"sessionId":"ea8ef0120f9ba75135835464b7cc67e9"}
2015-07-29 15:07:57:025 - info: --> DELETE /wd/hub/session/ea8ef0120f9ba75135835464b7cc67e9 {}
2015-07-29 15:07:57:048 - info: Shutting down appium session
2015-07-29 15:07:57:049 - info: JSONWP Proxy: Proxying [DELETE /] to [DELETE http://127.0.0.1:9519/wd/hub/session/ea8ef0120f9ba75135835464b7cc67e9] with no body
2015-07-29 15:07:58:521 - info: JSONWP Proxy: Got response with status 200: {"sessionId":"ea8ef0120f9ba75135835464b7cc67e9","status":0,"value":null}
2015-07-29 15:07:58:595 - info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"shutdown"}
2015-07-29 15:07:58:638 - info: [debug] [BOOTSTRAP] [debug] Got command of type SHUTDOWN
2015-07-29 15:07:58:711 - info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":"OK, shutting down"}
2015-07-29 15:07:58:712 - info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
2015-07-29 15:07:58:744 - info: [debug] [BOOTSTRAP] [debug] Closed client connection
2015-07-29 15:07:58:785 - info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
2015-07-29 15:07:58:786 - info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=.
2015-07-29 15:07:58:786 - info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
2015-07-29 15:07:58:786 - info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
2015-07-29 15:07:58:787 - info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
2015-07-29 15:07:58:790 - info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
2015-07-29 15:07:58:790 - info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 0
2015-07-29 15:07:58:815 - info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
2015-07-29 15:07:58:815 - info: [debug] [UIAUTOMATOR STDOUT] Test results for WatcherResultPrinter=.
2015-07-29 15:07:58:816 - info: [debug] [UIAUTOMATOR STDOUT] Time: 43.855
2015-07-29 15:07:58:816 - info: [debug] [UIAUTOMATOR STDOUT] OK (1 test)
2015-07-29 15:07:58:816 - info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: -1
2015-07-29 15:07:59:118 - info: [debug] UiAutomator shut down normally
2015-07-29 15:07:59:119 - info: [debug] executing cmd: /opt/android-sdk-linux/platform-tools/adb -s LGD855c00a8047 shell "am force-stop com.android.chrome"
2015-07-29 15:07:59:719 - info: [debug] Stopping logcat capture
2015-07-29 15:07:59:721 - info: [debug] Logcat terminated with code null, signal SIGTERM
2015-07-29 15:07:59:721 - info: [debug] Cleaning up appium session
2015-07-29 15:07:59:722 - info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"ea8ef0120f9ba75135835464b7cc67e9"}
2015-07-29 15:07:59:724 - info: <-- DELETE /wd/hub/session/ea8ef0120f9ba75135835464b7cc67e9 200 2698.518 ms - 72 {"status":0,"value":null,"sessionId":"ea8ef0120f9ba75135835464b7cc67e9"}
2015-07-29 15:08:01:183 - info: --> GET /wd/hub/status {}
2015-07-29 15:08:01:183 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}}}
2015-07-29 15:08:01:185 - info: <-- GET /wd/hub/status 200 2.374 ms - 104 {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}}}
2015-07-29 15:08:06:228 - info: --> GET /wd/hub/status {}
2015-07-29 15:08:06:228 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}}}
2015-07-29 15:08:06:230 - info: <-- GET /wd/hub/status 200 2.290 ms - 104 {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}}}
2015-07-29 15:08:06:299 - info: --> GET /wd/hub/status {}
2015-07-29 15:08:06:300 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}}}
2015-07-29 15:08:06:302 - info: <-- GET /wd/hub/status 200 2.251 ms - 104 {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}}}

**Comment by sebv** [comment]
I guess you are trying to run Appium outside a DISPLAY.

**Comment by shadeimi** [comment]
yes, do you need some other logs?

**Comment by sebv** [comment]
nope, just set DISPLAY, it's common unix error.

**Comment by shadeimi** [comment]
Installed Xffb and:
/usr/bin/Xvfb :1 -screen 0 1024x768x24 &
export DISPLAY=:1

**Comment by SrinivasanTarget** [comment]
@triager please close
