### ISSUE TITLE
Chrome not Reachable

### ISSUE THREAD

**Issue by shadeimi** [appium/appium#5450]
2015-07-29 11:59:06:216 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.3","revision":"a357c7fa73222315dd85c3d2dd8334767cca1b0d"}}}
2015-07-29 11:59:06:217 - info: <-- GET /wd/hub/status 200 1.415 ms - 104 {"status":0,"value":{"build":{"version":"1.4.3","revision":"a357c7fa73222315dd85c3d2dd8334767cca1b0d"}}}
2015-07-29 11:59:06:734 - info: JSONWP Proxy: Got response with status 200: {"sessionId":"44d45b8e3ce852570367789cd99633e9","status":100,"value":{"message":"chrome not reachable\n  (Driver info: chromedriver=2.15.322455 (ae8db840dac8d0c45
3355d3d922c91adfb61df8f),platform=Mac ...
2015-07-29 11:59:06:948 - info: Chromedriver stopped unexpectedly on us, shutting down then calling back up with the on-die callback
2015-07-29 11:59:06:951 - info: [debug] Cleaning up appium session
2015-07-29 11:59:06:952 - info: [debug] Error: An error occurred (Original error: chrome not reachable
  (Driver info: chromedriver=2.15.322455 (ae8db840dac8d0c453355d3d922c91adfb61df8f),platform=Mac OS X 10.10.4 x86_64))
    at JWProxy.command$ (lib/proxy.js:149:15)
    at tryCatch (/Users/qaautomation/git/appium_1.4.8/node_modules/appium-chromedriver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke](/Users/qaautomation/git/appium_1.4.8/node_modules/appium-chromedriver/node_modules/babel-runtime/regenerator/runtime.js:294:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next](/Users/qaautomation/git/appium_1.4.8/node_modules/appium-chromedriver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/qaautomation/git/appium_1.4.8/node_modules/appium-chromedriver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at bound (domain.js:254:14)
    at GeneratorFunctionPrototype.runBound (domain.js:267:12)
    at run (/Users/qaautomation/git/appium_1.4.8/node_modules/appium-chromedriver/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:89:39)
    at /Users/qaautomation/git/appium_1.4.8/node_modules/appium-chromedriver/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:100:28
    at process._tickDomainCallback (node.js:381:11)
2015-07-29 11:59:06:952 - info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: An error occurred (Original error: chrome not reachable\n  (Driver info: chromedriver=2.15.322455 (ae8db840dac8d0c453355d3d922c91adfb61df8f),platform=Mac OS X 10.10.4 x86_64)))","status":100,"value":{"message":"chrome not reachable\n  (Driver info: chromedriver=2.15.322455 (ae8db840dac8d0c453355d3d922c91adfb61df8f),platform=Mac OS X 10.10.4 x86_64)"},"httpCode":200,"origValue":"An error occurred (Original error: chrome not reachable\n  (Driver info: chromedriver=2.15.322455 (ae8db840dac8d0c453355d3d922c91adfb61df8f),platform=Mac OS X 10.10.4 x86_64))"},"sessionId":null}
2015-07-29 11:59:06:953 - info: <-- POST /wd/hub/session 500 261813.979 ms - 662
2015-07-29 11:59:06:954 - info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"shutdown"}
2015-07-29 11:59:06:954 - info: [debug] [BOOTSTRAP] [debug] Got command of type SHUTDOWN
2015-07-29 11:59:06:954 - info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"OK, shutting down","status":0}
2015-07-29 11:59:06:955 - info: [debug] [BOOTSTRAP] [debug] Closed client connection
2015-07-29 11:59:06:955 - info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
2015-07-29 11:59:06:955 - info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=.
2015-07-29 11:59:06:955 - info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
2015-07-29 11:59:06:955 - info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
2015-07-29 11:59:06:955 - info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
2015-07-29 11:59:06:955 - info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
2015-07-29 11:59:06:956 - info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 0
2015-07-29 11:59:06:956 - info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
2015-07-29 11:59:06:956 - info: [debug] [UIAUTOMATOR STDOUT] Test results for WatcherResultPrinter=.
2015-07-29 11:59:06:956 - info: [debug] [UIAUTOMATOR STDOUT] Time: 259.156
2015-07-29 11:59:06:956 - info: [debug] [UIAUTOMATOR STDOUT] OK (1 test)
2015-07-29 11:59:06:957 - info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
2015-07-29 11:59:06:957 - info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: -1
2015-07-29 11:59:06:960 - info: [debug] UiAutomator shut down normally
2015-07-29 11:59:06:960 - info: [debug] executing cmd: /Users/qaautomation/Library/Android/sdk/platform-tools/adb -s 936d819f shell "am force-stop com.android.chrome"
2015-07-29 11:59:07:710 - info: [debug] Stopping logcat capture
2015-07-29 11:59:07:711 - info: [debug] Logcat terminated with code null, signal SIGTERM
2015-07-29 11:59:07:712 - info: [debug] Cleaning up appium session

**Comment by sebv** [comment]
Could you provide full log in gist?

**Comment by rkavalap** [comment]
Closing due to inactivity
