### ISSUE TITLE
Something is not implemented, but it's not clear what

### ISSUE THREAD

**Issue by shadeimi** [appium/appium#5451]
==============================================================================
20150730 15:55:54.055 - INFO - + START SUITE: TgiochissimoSuite [ ]
==============================================================================
20150730 15:55:54.056 - INFO - +- START TEST: Tgiochissimo_CheckIframe_Vodafone [ ]
------------------------------------------------------------------------------
20150730 15:55:54.056 - INFO - +-- START KW: Selenium2LibraryB.Set Selenium Speed [ 1 ]
20150730 15:55:54.057 - INFO - +-- END KW: Selenium2LibraryB.Set Selenium Speed (1)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
20150730 15:55:54.057 - INFO - +-- START KW: selenium.Open Browser [ ${URL}/subscribe ]
20150730 15:55:54.059 - INFO - +--- START KW: BuiltIn.Log [ ${url}:${browser}:${remote_url}:${desired_capabilities}:${ff_profile_dir} ]
20150730 15:55:54.059 - INFO - http://www.giochissimo.it/subscribe:None:None:None:None
20150730 15:55:54.060 - INFO - +--- END KW: BuiltIn.Log (0)
20150730 15:55:54.060 - INFO - +--- START KW: BuiltIn.Log [ System V:${BROWSERNAME}:${WEBDRIVER}:${CAPABILITIES} ]
20150730 15:55:54.060 - INFO - System V:chrome:http://selenium.buongiorno.com:4444/wd/hub:deviceName:ANDROID,tags:1438260953,udid:936d819f,browserName:chrome,version:4.4.4,model:SM-G360F,platformName:ANDROID,id:25590676b6a489e8,crais_host:10.57.11.11
20150730 15:55:54.060 - INFO - +--- END KW: BuiltIn.Log (0)
20150730 15:55:54.061 - INFO - +--- START KW: ${b} = BuiltIn.Set Variable If [ "${browser}"!="None" | ${browser} | ${BROWSERNAME} ]
20150730 15:55:54.061 - INFO - ${b} = chrome
20150730 15:55:54.061 - INFO - +--- END KW: ${b} = BuiltIn.Set Variable If (0)
20150730 15:55:54.062 - INFO - +--- START KW: ${ru} = BuiltIn.Set Variable If [ "${remote_url}"!="None" | ${remote_url} | ${WEBDRIVER} ]
20150730 15:55:54.062 - INFO - ${ru} = http://selenium.buongiorno.com:4444/wd/hub
20150730 15:55:54.062 - INFO - +--- END KW: ${ru} = BuiltIn.Set Variable If (0)
20150730 15:55:54.063 - INFO - +--- START KW: ${c} = BuiltIn.Set Variable If [ "${desired_capabilities}"!="None" | ${desired_capabilities} | ${CAPABILITIES} ]
20150730 15:55:54.063 - INFO - ${c} = deviceName:ANDROID,tags:1438260953,udid:936d819f,browserName:chrome,version:4.4.4,model:SM-G360F,platformName:ANDROID,id:25590676b6a489e8,crais_host:10.57.11.11
20150730 15:55:54.063 - INFO - +--- END KW: ${c} = BuiltIn.Set Variable If (1)
20150730 15:55:54.063 - INFO - +--- START KW: ${ff_pd} = BuiltIn.Set Variable If [ "${ff_profile_dir}"!="None" | ${ff_profile_dir} | ${None} ]
20150730 15:55:54.064 - INFO - ${ff_pd} = None
20150730 15:55:54.064 - INFO - +--- END KW: ${ff_pd} = BuiltIn.Set Variable If (1)
20150730 15:55:54.064 - INFO - +--- START KW: BuiltIn.Log [ ${url}:${b}:${ru}:${c}:${ff_pd} ]
20150730 15:55:54.065 - INFO - http://www.giochissimo.it/subscribe:chrome:http://selenium.buongiorno.com:4444/wd/hub:deviceName:ANDROID,tags:1438260953,udid:936d819f,browserName:chrome,version:4.4.4,model:SM-G360F,platformName:ANDROID,id:25590676b6a489e8,crais_host:10.57.11.11:None
20150730 15:55:54.065 - INFO - +--- END KW: BuiltIn.Log (1)
20150730 15:55:54.065 - INFO - +--- START KW: Selenium2LibraryB.Open Browser [ url=${url} | browser=${b} | remote_url=${ru} | desired_capabilities=${c} | ff_profile_dir=${ff_pd} ]
20150730 15:55:54.066 - INFO - Opening browser 'chrome' to base url 'http://www.giochissimo.it/subscribe' through remote server at 'http://selenium.buongiorno.com:4444/wd/hub'
20150730 15:56:08.076 - INFO - +---- START KW: selenium.Capture Page Screenshot [ ]
20150730 15:56:08.078 - INFO - +----- START KW: ${status}, ${message} = BuiltIn.Run Keyword And Ignore Error [ Variable Should Exist | ${IMAGE_SCREENSHOT_COUNTER} ]
20150730 15:56:08.079 - INFO - +------ START KW: BuiltIn.Variable Should Exist [ ${IMAGE_SCREENSHOT_COUNTER} ]
20150730 15:56:08.087 - FAIL - Variable ${IMAGE_SCREENSHOT_COUNTER} does not exist.
20150730 15:56:08.088 - DEBUG - Traceback (most recent call last):
  File "/jhub/_prod/server_ptiqaaeryn_core_daemon/lib/python2.7/site-packages/robot/libraries/BuiltIn.py", line 991, in variable_should_exist
    asserts.fail_unless(name in self._variables, msg)
  File "/jhub/_prod/server_ptiqaaeryn_core_daemon/lib/python2.7/site-packages/robot/utils/asserts.py", line 119, in fail_unless
    if not expr: _report_failure(msg)
  File "/jhub/_prod/server_ptiqaaeryn_core_daemon/lib/python2.7/site-packages/robot/utils/asserts.py", line 230, in _report_failure
    raise AssertionError(msg)
20150730 15:56:08.088 - INFO - +------ END KW: BuiltIn.Variable Should Exist (9)
20150730 15:56:08.088 - INFO - ${status} = FAIL
20150730 15:56:08.088 - INFO - ${message} = Variable ${IMAGE_SCREENSHOT_COUNTER} does not exist.
20150730 15:56:08.088 - INFO - +----- END KW: ${status}, ${message} = BuiltIn.Run Keyword And Ignore Error (10)
20150730 15:56:08.089 - INFO - +----- START KW: BuiltIn.Log [ ${status} ]
20150730 15:56:08.089 - INFO - FAIL
20150730 15:56:08.089 - INFO - +----- END KW: BuiltIn.Log (0)
20150730 15:56:08.090 - INFO - +----- START KW: BuiltIn.Run Keyword If [ "${status}" == "FAIL" | Set Global Variable | ${IMAGE_SCREENSHOT_COUNTER} | 0 ]
20150730 15:56:08.090 - INFO - +------ START KW: BuiltIn.Set Global Variable [ ${IMAGE_SCREENSHOT_COUNTER} | 0 ]
20150730 15:56:08.093 - INFO - ${IMAGE_SCREENSHOT_COUNTER} = 0
20150730 15:56:08.093 - INFO - +------ END KW: BuiltIn.Set Global Variable (3)
20150730 15:56:08.093 - INFO - +----- END KW: BuiltIn.Run Keyword If (3)
20150730 15:56:08.094 - INFO - +----- START KW: ${tmp} = BuiltIn.Evaluate [ ${IMAGE_SCREENSHOT_COUNTER} + 1 ]
20150730 15:56:08.094 - INFO - ${tmp} = 1
20150730 15:56:08.094 - INFO - +----- END KW: ${tmp} = BuiltIn.Evaluate (0)
20150730 15:56:08.095 - INFO - +----- START KW: ${base} = BuiltIn.Set Variable If [ "${filename}"!="None" | ${filename} | img ]
20150730 15:56:08.095 - INFO - ${base} = img
20150730 15:56:08.095 - INFO - +----- END KW: ${base} = BuiltIn.Set Variable If (0)
20150730 15:56:08.096 - INFO - +----- START KW: BuiltIn.Set Global Variable [ ${IMAGE_SCREENSHOT_COUNTER} | ${tmp} ]
20150730 15:56:08.096 - INFO - ${IMAGE_SCREENSHOT_COUNTER} = 1
20150730 15:56:08.096 - INFO - +----- END KW: BuiltIn.Set Global Variable (0)
20150730 15:56:08.097 - INFO - +----- START KW: BuiltIn.Log [ ${IMAGE_SCREENSHOT_COUNTER} ]
20150730 15:56:08.097 - INFO - 1
20150730 15:56:08.097 - INFO - +----- END KW: BuiltIn.Log (1)
20150730 15:56:08.097 - INFO - +----- START KW: Selenium2LibraryB.Capture Page Screenshot [ ${base}${IMAGE_SCREENSHOT_COUNTER}.png ]
20150730 15:56:08.099 - FAIL - No browser is open
20150730 15:56:08.099 - DEBUG - Traceback (most recent call last):
  File "<string>", line 2, in capture_page_screenshot
  File "/jhub/_prod/server_ptiqaaeryn_core_daemon/lib/python2.7/site-packages/Selenium2Library/keywords/keywordgroup.py", line 12, in _run_on_failure_decorator
    return method(*args, **kwargs)
  File "/jhub/_prod/server_ptiqaaeryn_core_daemon/lib/python2.7/site-packages/Selenium2Library/keywords/_screenshot.py", line 28, in capture_page_screenshot
    if hasattr(self._current_browser(), 'get_screenshot_as_file'):
  File "/jhub/_prod/server_ptiqaaeryn_core_daemon/lib/python2.7/site-packages/Selenium2Library/keywords/_browsermanagement.py", line 471, in _current_browser
    raise RuntimeError('No browser is open')
20150730 15:56:08.099 - INFO - +----- END KW: Selenium2LibraryB.Capture Page Screenshot (2)
20150730 15:56:08.099 - INFO - +---- END KW: selenium.Capture Page Screenshot (23)
20150730 15:56:08.099 - WARN - Keyword 'Capture Page Screenshot' could not be run on failure: No browser is open
20150730 15:56:08.103 - FAIL - WebDriverException: Message: u'Not yet implemented. Please help us: http://appium.io/get-involved.html'
20150730 15:56:08.103 - DEBUG - Traceback (most recent call last):
  File "<string>", line 2, in open_browser
  File "/jhub/_prod/server_ptiqaaeryn_core_daemon/lib/python2.7/site-packages/Selenium2Library/keywords/keywordgroup.py", line 12, in _run_on_failure_decorator
    return method(*args, **kwargs)
  File "/jhub/_prod/server_ptiqaaeryn_core_daemon/lib/python2.7/site-packages/Selenium2Library/keywords/_browsermanagement.py", line 113, in open_browser
    browser = self._make_browser(browser_name,desired_capabilities,ff_profile_dir,remote_url)
  File "/jhub/_prod/server_ptiqaaeryn_core_daemon/lib/python2.7/site-packages/Selenium2Library/keywords/_browsermanagement.py", line 487, in _make_browser
    browser.set_script_timeout(self._timeout_in_secs)
  File "/jhub/_prod/server_ptiqaaeryn_core_daemon/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 633, in set_script_timeout
    {'ms': float(time_to_wait) * 1000})
  File "/jhub/_prod/server_ptiqaaeryn_core_daemon/lib/python2.7/site-packages/Selenium2Library/webdrivermonkeypatches.py", line 11, in execute
    result = self._base_execute(driver_command, params)
  File "/jhub/_prod/server_ptiqaaeryn_core_daemon/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 173, in execute
    self.error_handler.check_response(response)
  File "/jhub/_prod/server_ptiqaaeryn_core_daemon/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 166, in check_response
    raise exception_class(message, screen, stacktrace)
20150730 15:56:08.103 - INFO - +--- END KW: Selenium2LibraryB.Open Browser (14038)
20150730 15:56:08.104 - INFO - +-- END KW: selenium.Open Browser (14047)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
20150730 15:56:08.105 - INFO - +-- START TEARDOWN: giochissimo.Finish Test [ ]
20150730 15:56:08.107 - INFO - +--- START KW: BuiltIn.Comment [ Return From Keyword If | ${ALREADY_CLOSED} ]
20150730 15:56:08.108 - INFO - +--- END KW: BuiltIn.Comment (0)
20150730 15:56:08.108 - INFO - +--- START KW: Selenium2LibraryB.Close All Browsers [ ]
20150730 15:56:08.108 - DEBUG - Closing all browsers
20150730 15:56:08.109 - INFO - +--- END KW: Selenium2LibraryB.Close All Browsers (0)
20150730 15:56:08.109 - INFO - +--- START KW: BuiltIn.Comment [ Set Global Variable | ${ALREADY_CLOSED} | True ]
20150730 15:56:08.109 - INFO - +--- END KW: BuiltIn.Comment (0)
20150730 15:56:08.110 - INFO - +-- END TEARDOWN: giochissimo.Finish Test (5)
------------------------------------------------------------------------------
20150730 15:56:08.110 - INFO - +- END TEST: Tgiochissimo_CheckIframe_Vodafone (14055)
------------------------------------------------------------------------------
20150730 15:56:08.111 - INFO - + END SUITE: TgiochissimoSuite (14784)
==============================================================================

**Comment by sebv** [comment]
Could you provide the appium server log in gist?

**Comment by SrinivasanTarget** [comment]
@scottdixon @imurchie can we please close this, as we have better logging in Appium 1.5
