### ISSUE TITLE
Not able to install apk file - warn: ERROR: dump failed because no AndroidManifest.xml found

### ISSUE THREAD

**Issue by vikramvi** [appium/appium#5471]
Hi,

I'm having Appium v1.4.8  , while trying to start automation with our apk file got below error

Kindly look into it , am not pretty sure if it's our apk issue or appium latest server bug 

Thanks & Regards,
Vikram

----info: [debug] Checking whether adb is present
info: [debug] Using adb from /Users/vikram-anna/Documents/workspace/Android/Android-sdk/platform-tools/adb
info: [debug] Parsing package and activity from app manifest
info: [debug] Checking whether aapt is present
info: [debug] Using aapt from /Users/vikram-anna/Documents/workspace/Android/Android-sdk/build-tools/android-4.4.2/aapt
info: [debug] Extracting package and launch activity from manifest.
info: [debug] executing cmd: /Users/Android/Android-sdk/build-tools/android-4.4.2/aapt dump badging /Users/vikram-anna/Documents/workspace/Android/build/outputs/apk/wl-android-nightly-release.apk
warn: ERROR: dump failed because no AndroidManifest.xml found

error: Problem parsing package and activity from manifest: Error: packageAndLaunchActivityFromManifest failed. Error: Command failed: /bin/sh -c /Users/vikram-anna/Documents/workspace/Android/Android-sdk/build-tools/android-4.4.2/aapt dump badging /Users/vikram-anna/Documents/workspace/Android/build/outputs/apk/wl-android-nightly-release.apk
ERROR: dump failed because no AndroidManifest.xml found

info: [debug] Cleaning up android objects
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: packageAndLaunchActivityFromManifest failed. Error: Command failed: /bin/sh -c /Users/vikram-anna/Documents/workspace/Android/Android-sdk/build-tools/android-4.4.2/aapt dump badging /Users/vikram-anna/Documents/workspace/Android/build/outputs/apk/wl-android-nightly-release.apk
ERROR: dump failed because no AndroidManifest.xml found

info: [debug] Error: packageAndLaunchActivityFromManifest failed. Error: Command failed: /bin/sh -c /Users/vikram-anna/Documents/workspace/Android/Android-sdk/build-tools/android-4.4.2/aapt dump badging /Users/vikram-anna/Documents/workspace/Android/build/outputs/apk/wl-android-nightly-release.apk
ERROR: dump failed because no AndroidManifest.xml found

```
at /usr/local/lib/node_modules/appium/node_modules/appium-adb/lib/adb.js:259:19
at ChildProcess.exithandler (child_process.js:758:5)
at ChildProcess.emit (events.js:110:17)
at maybeClose (child_process.js:1015:16)
at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
```

info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: packageAndLaunchActivityFromManifest failed. Error: Command failed: /bin/sh -c /Users/vikram-anna/Documents/workspace/Android/Android-sdk/build-tools/android-4.4.2/aapt dump badging /Users/vikram-anna/Documents/workspace/Android/build/outputs/apk/wl-android-nightly-release.apk\nERROR: dump failed because no AndroidManifest.xml found\n)","origValue":"packageAndLaunchActivityFromManifest failed. Error: Command failed: /bin/sh -c /Users/vikram-anna/Documents/workspace/Android/Android-sdk/build-tools/android-4.4.2/aapt dump badging /Users/vikram-anna/Documents/workspace/Android/build/outputs/apk/wl-android-nightly-release.apk\nERROR: dump failed because no AndroidManifest.xml found\n"},"sessionId":null}
info: <-- POST /wd/hub/session 500 222.584 ms - 888 

---

**Comment by sebv** [comment]
Just try to figure out why this does not work, it is a straightforward aapt command:

```
 info: [debug] executing cmd: /Users/Android/Android-sdk/build-tools/android-4.4.2/aapt dump badging /Users/vikram-anna/Documents/workspace/Android/build/outputs/apk/wl-android-nightly-release.apk
warn: ERROR: dump failed because no AndroidManifest.xml found
```

**Comment by rkavalap** [comment]
Closing due to inactivity
