### ISSUE TITLE
can not install appium!

### ISSUE THREAD

**Issue by lieliefengzheng** [appium/appium#5491]
My environment is:
OSX 10.10.4
I tried to download appium by "sudo npm install -g appium"
but the result it like this:
[> appium-chromedriver@2.1.3 install /usr/local/lib/node_modules/appium/node_modules/appium-chromedriver
> node install-npm.js

info Chromedriver Install Opening temp file to write chromedriver_mac32 to...
info Chromedriver Install Downloading http://chromedriver.storage.googleapis.com/2.15/chromedriver_mac32.zip...
RequestError: Error: connect ETIMEDOUT
    at new RequestError (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/node_modules/request-promise/lib/errors.js:11:15)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/node_modules/request-promise/lib/rp.js:56:32)
    at self.callback (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/node_modules/request/request.js:198:22)
    at Request.emit (events.js:107:17)
    at Request.onRequestError (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/node_modules/request/request.js:861:8)
    at ClientRequest.emit (events.js:107:17)
    at Socket.socketErrorListener (_http_client.js:271:9)
    at Socket.emit (events.js:107:17)
    at net.js:459:14
    at process._tickCallback (node.js:355:11)
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "appium"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! appium-chromedriver@2.1.3 install: `node install-npm.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the appium-chromedriver@2.1.3 install script 'node install-npm.js'.
npm ERR! This is most likely a problem with the appium-chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install-npm.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls appium-chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/zhangmanying/npm-debug.log
]

could u tell me how to solve it ! thanks!

**Comment by jlipps** [comment]
are you able to download that chromedriver zipfile manually?

**Comment by sebv** [comment]
Yeah try `wget http://chromedriver.storage.googleapis.com/2.15/chromedriver_mac32.zip` maybe some firewall issue.

**Comment by lieliefengzheng** [comment]
yep,I can download the zipfile from the web manually,and I've tried to create a new folder to replace the chromedriver in the local place,but still failed.

npm install appium-chromedriver --chromedriver_version='2.15'
npm WARN package.json appium@1.4.0 No license field.
\
> appium-chromedriver@2.1.3 install /Users/zhangmanying/code/appium/node_modules/appium-chromedriver
> node install-npm.js

info Chromedriver Install Opening temp file to write chromedriver_mac32 to...
info Chromedriver Install Downloading http://chromedriver.storage.googleapis.com/2.15/chromedriver_mac32.zip...
RequestError: Error: connect ETIMEDOUT
    at new RequestError (/Users/zhangmanying/code/appium/node_modules/appium-chromedriver/node_modules/request-promise/lib/errors.js:11:15)
    at Request.RP$callback [as _callback] (/Users/zhangmanying/code/appium/node_modules/appium-chromedriver/node_modules/request-promise/lib/rp.js:56:32)
    at self.callback (/Users/zhangmanying/code/appium/node_modules/appium-chromedriver/node_modules/request/request.js:198:22)
    at Request.emit (events.js:107:17)
    at Request.onRequestError (/Users/zhangmanying/code/appium/node_modules/appium-chromedriver/node_modules/request/request.js:861:8)
    at ClientRequest.emit (events.js:107:17)
    at Socket.socketErrorListener (_http_client.js:271:9)
    at Socket.emit (events.js:107:17)
    at net.js:459:14
    at process._tickCallback (node.js:355:11)
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "appium-chromedriver" "--chromedriver_version=2.15"
npm ERR! node v0.12.7
npm ERR! npm  v2.12.1
npm ERR! code ELIFECYCLE

npm ERR! appium-chromedriver@2.1.3 install: `node install-npm.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the appium-chromedriver@2.1.3 install script 'node install-npm.js'.
npm ERR! This is most likely a problem with the appium-chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install-npm.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls appium-chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/zhangmanying/code/appium/node_modules/npm-debug.log

**Comment by SrinivasanTarget** [comment]
@lieliefengzheng Download appium using: npm install -g appium i.e without sudo command.Will be closing this and please raise a new one incase of any issues with npm-debug.log if any installation failure.

**Comment by SrinivasanTarget** [comment]
@triager please close
