### ISSUE TITLE
Not able to run in chrome on real android device - Failing a start a new session

### ISSUE THREAD

**Issue by ArkasaliR** [appium/appium#5495]
Hello All,

I am new to appium and doing mobile browser automation. Tried many ways and with many different devices with different android versions, not able to execute the scenario in chrome on real android device but the same scenario is working fine on emulator. The chrome browser is opening in phone but nothing happening further.As it is showing already there is an existing session but i even tried by checking "Override Existing Sessions" but no progress.

Have got to know many have successfully performed browser automation on real android device. Please need your help in getting resolved this.

I am using cucumber along with Selenium and Capybara with Appium.

My desired capabilities are:
=============================================================

require 'rubygems'
require 'Capybara/cucumber'
require 'bddfire'
require 'rspec'

Capybara.configure do |config|
  config.run_server = false
  config.default_driver = (ENV['DRIVER'] || 'selenium').to_sym
  config.default_wait_time = 60
end

Capybara.register_driver :appium do |app|
    capabilities = { :platformName => 'Android', :platformVersion => '4.1', :deviceName => 'RV1C328JN6N', :browserName => 'Chrome' }
Capybara::Selenium::Driver.new(app,
                                 :browser => :remote,
                                 :desired_capabilities => capabilities,
                                 :url => "http://0.0.0.0:4723/wd/hub")
end

================================================================

In place of deviceName have tried the below: But getting the same response on all

=========================================================
List of devices attached 
001961b21c053f	device

001961b21c053f, also the phone's Serial Number and Model number
=========================================================

The below is the server log:
==============================================================================
Launching Appium with command: '/Applications/Appium.app/Contents/Resources/node/bin/node' lib/server/main.js --command-timeout "7200" --debug-log-spacing --automation-name "Appium" --platform-name "Android" --platform-version "4.3" --app "browser" --dont-stop-app-on-reset --browser-name "Browser" --device-name "RV1C328JN6N" --device-ready-timeout "5"

info: Welcome to Appium v1.4.8 (REV c8179bd8352d3c62d98fa58b324491230df9342a)

info: Appium REST http interface listener started on 0.0.0.0:4723

info: [debug] Non-default server args: {"app":"browser","deviceName":"RV1C328JN6N","platformName":"Android","platformVersion":"4.3","automationName":"Appium","browserName":"Browser","defaultCommandTimeout":7200,"dontStopAppOnReset":true,"debugLogSpacing":true}
info: Console LogLevel: debug

info: --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"Android","platformVersion":"4.1","deviceName":"RV1C328JN6N","browserName":"Chrome"}}

info: Client User-Agent string: Ruby

info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************

info: Set mode: Proxying straight through to Chromedriver
info: [debug] Looks like we want chrome on android
info: [debug] Creating new appium session a86f7306-d2e9-4b83-a012-0b897108d58d
info: [debug] Checking whether adb is present
info: [debug] Using adb from /Users/RaviArkasali/Library/Android/sdk/platform-tools/adb
info: [debug] Using fast reset? true

info: [debug] Preparing device for session
info: [debug] Not checking whether app is present since we are assuming it's already on the device
info: Retrieving device
info: [debug] Trying to find a connected android device
info: [debug] Getting connected devices...
info: [debug] executing cmd: /Users/RaviArkasali/Library/Android/sdk/platform-tools/adb devices

info: [debug] 1 device(s) connected
info: Found device 001961b21c053f
info: [debug] Setting device id to 001961b21c053f
info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
info: [debug] executing cmd: /Users/RaviArkasali/Library/Android/sdk/platform-tools/adb -s 001961b21c053f wait-for-device

info: [debug] executing cmd: /Users/RaviArkasali/Library/Android/sdk/platform-tools/adb -s 001961b21c053f shell "echo 'ready'"

info: [debug] Starting logcat capture

info: [debug] Pushing unlock helper app to device...

info: [debug] executing cmd: /Users/RaviArkasali/Library/Android/sdk/platform-tools/adb -s 001961b21c053f install "/Applications/Appium.app/Contents/Resources/node_modules/appium/build/unlock_apk/unlock_apk-debug.apk"

info: [debug] executing cmd: /Users/RaviArkasali/Library/Android/sdk/platform-tools/adb -s 001961b21c053f shell "dumpsys window"

info: [debug] Screen already unlocked, continuing.

info: [debug] Forwarding system:4724 to device:4724
info: [debug] executing cmd: /Users/RaviArkasali/Library/Android/sdk/platform-tools/adb -s 001961b21c053f forward tcp:4724 tcp:4724

info: [debug] Pushing appium bootstrap to device...

info: [debug] executing cmd: /Users/RaviArkasali/Library/Android/sdk/platform-tools/adb -s 001961b21c053f push "/Applications/Appium.app/Contents/Resources/node_modules/appium/build/android_bootstrap/AppiumBootstrap.jar" /data/local/tmp/

info: Starting App
info: [debug] Attempting to kill all 'uiautomator' processes
info: [debug] Getting all processes with 'uiautomator'
info: [debug] executing cmd: /Users/RaviArkasali/Library/Android/sdk/platform-tools/adb -s 001961b21c053f shell "ps 'uiautomator'"

info: [debug] No matching processes found
info: [debug] Running bootstrap
info: [debug] spawning: /Users/RaviArkasali/Library/Android/sdk/platform-tools/adb -s 001961b21c053f shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.Bootstrap -e pkg com.android.browser -e disableAndroidWatchers false

info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1

info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
info: [debug] [UIAUTOMATOR STDOUT] io.appium.android.bootstrap.Bootstrap:
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 1

info: [debug] [BOOTSTRAP] [debug] Socket opened on port 4724

info: [debug] [BOOTSTRAP] [debug] Appium Socket Server Ready
info: [debug] [BOOTSTRAP] [debug] Loading json...
info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.
info: [debug] Pushing command to appium work queue: ["getDataDir",{}]
info: [debug] [BOOTSTRAP] [debug] Client connected
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"getDataDir","params":{}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: getDataDir

info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"\/data\/local\/tmp","status":0}
info: [debug] dataDir set to: /data/local/tmp
info: Chromedriver: Set chromedriver binary as: /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/chromedriver
info: Chromedriver: Killing any old chromedrivers, running: ps -ef | grep /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/chromedriver | grep -v grep |grep -e '--port=9515\(\s.*\)\?$' | awk '{ print $2 }' | xargs kill -15

info: Chromedriver: Successfully cleaned up old chromedrivers
info: Chromedriver: Spawning chromedriver with: /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/chromedriver --url-base=wd/hub --port=9515

info: Chromedriver: [STDOUT] Starting ChromeDriver 2.15.322455 (ae8db840dac8d0c453355d3d922c91adfb61df8f) on port 9515
Only local connections are allowed.
info: JSONWP Proxy: Proxying [GET /status] to [GET http://127.0.0.1:9515/wd/hub/status] with no body

info: JSONWP Proxy: Got response with status 200: {"sessionId":"","status":0,"value":{"build":{"version":"alpha"},"os":{"arch":"x86_64","name":"Mac OS X","version":"10.10.4"}}}
info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.browser","androidActivity":"com.android.browser.BrowserActivity","androidDeviceSerial":"001961b21c053f"}}}

info: <-- POST /wd/hub/session - - ms - - 

info: --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"Android","platformVersion":"4.1","deviceName":"RV1C328JN6N","browserName":"Chrome"}}

error: Failed to start an Appium session, err was: Error: Requested a new session but one was in progress

info: Client User-Agent string: Ruby
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: [debug] Error: Requested a new session but one was in progress
    at [object Object].Appium.start (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/appium.js:139:15)
    at exports.createSession (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/server/controller.js:188:16)
    at Layer.handle [as handle_request] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/layer.js:82:5)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/layer.js:82:5)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/index.js:267:22
    at Function.proto.process_params (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/index.js:321:12)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/index.js:261:10)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:100:14)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/lib/ser
ver/controller.js:39:7
    at Layer.handle [as handle_request] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/layer.js:82:5)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:110:13)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Requested a new session but one was in progress)","origValue":"Requested a new session but one was in progress"},"sessionId":"a86f7306-d2e9-4b83-a012-0b897108d58d"}
info: <-- POST /wd/hub/session 500 25.278 ms - 250 

undefined

info: [debug] Cleaning up appium session

error: Failed to start an Appium session, err was: TypeError: Cannot read property 'done' of undefined

info: [debug] TypeError: Cannot read property 'done' of undefined
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/regenerator/runtime.js:193:20
    at run (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:89:39)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:100:28
    at process._tickDomainCallback (node.js:381:11)

info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Cannot read property 'done' of undefined)","origValue":"Cannot read property 'done' of undefined"},"sessionId":null}

==============================================================================

**Comment by ndziuban** [comment]
Same problem here, works fine on emulator but not on a real device. I tried with Chrome and Native browser.

**Comment by scottdixon** [comment]
@ArkasaliR @ndziuban - does the issue persist in more recent versions of Appium?

**Comment by SrinivasanTarget** [comment]
Closing this because of inactivity.Please raise a new issue incase if you hit the same in latest appium versions.

**Comment by SrinivasanTarget** [comment]
@triager please close
