### ISSUE TITLE
Error while installing Appium-chrome driver

### ISSUE THREAD

**Issue by AkkinapuramUdayKiran** [appium/appium#5513]
Hi,
             I tried installing appium, but unable to install appium due to appium-chromedriver@2.1.3 is not getting installed. So tried installing appium-chromedriver@2.1.3 but was facing issues as mensioned below

Error:- 
suryateja@suryateja-PC:~$ sudo npm install appium-chromedriver /usr/lib/node_modules/appium/node_modules/appium-chromedriver
npm WARN cannot run in wd appium-chromedriver@2.1.3 gulp prepublish (wd=/usr/lib/node_modules/appium/node_modules/appium-chromedriver)
-
> appium-chromedriver@2.1.3 install /home/suryateja/node_modules/appium-chromedriver
> node install-npm.js

info Chromedriver Install Opening temp file to write chromedriver_linux64 to...
info Chromedriver Install Downloading http://chromedriver.storage.googleapis.com/2.15/chromedriver_linux64.zip...
RequestError: Error: read ECONNRESET
    at new RequestError (/home/suryateja/node_modules/appium-chromedriver/node_modules/request-promise/lib/errors.js:11:15)
    at Request.RP$callback [as _callback] (/home/suryateja/node_modules/appium-chromedriver/node_modules/request-promise/lib/rp.js:56:32)
    at self.callback (/home/suryateja/node_modules/appium-chromedriver/node_modules/request/request.js:198:22)
    at Request.emit (events.js:107:17)
    at Request.onRequestError (/home/suryateja/node_modules/appium-chromedriver/node_modules/request/request.js:861:8)
    at ClientRequest.emit (events.js:107:17)
    at Socket.socketErrorListener (_http_client.js:271:9)
    at Socket.emit (events.js:107:17)
    at net.js:459:14
    at process._tickCallback (node.js:355:11)
npm ERR! Linux 3.2.0-23-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "appium-chromedriver@2.1.0" "install" "/usr/lib/node_modules/appium/node_modules/appium-chromedriver"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! appium-chromedriver@2.1.3 install: `node install-npm.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appium-chromedriver@2.1.3 install script 'node install-npm.js'.
npm ERR! This is most likely a problem with the appium-chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install-npm.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls appium-chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/suryateja/npm-debug.log

Thanks in advance..!

**Comment by grawk** [comment]
I got a similar error to this. In my case, it seems my company has put a restriction on connections to google drive resources. I wonder if it is the same issue for you, @AkkinapuramUdayKiran

**Comment by scottdixon** [comment]
@AkkinapuramUdayKiran please try a more recent version. Reopen if any issues.

**Comment by HRZhou** [comment]
@markshao I met the right same issue with yours, how did you resolve it?

**Comment by Archer456** [comment]
C:\Users\cmd>npm i appium -g
D:\nodejs\node-global\appium -> D:\nodejs\node-global\node_modules\appium\build\lib\main.js                             node_modules
                                                                                                                        e-debugger@3
> appium-chromedriver@3.0.1 install D:\nodejs\node-global\node_modules\appium\node_modules\appium-chromedriver
> node install-npm.js

info Chromedriver Install Installing Chromedriver version '2.30' for platform 'win' and architecture '32'
info Chromedriver Install Opening temp file to write chromedriver_win32 to...
info Chromedriver Install Downloading https://chromedriver.storage.googleapis.com/2.30/chromedriver_win32.zip...
RequestError: Error: read ECONNRESET
    at new RequestError (D:\nodejs\node-global\node_modules\appium\node_modules\request-promise\lib\errors.js:11:15)
    at Request.RP$callback [as _callback] (D:\nodejs\node-global\node_modules\appium\node_modules\request-promise\lib\rp.js:60:32)
    at self.callback (D:\nodejs\node-global\node_modules\appium\node_modules\request\request.js:186:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (D:\nodejs\node-global\node_modules\appium\node_modules\request\request.js:878:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\appium\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appium-chromedriver@3.0.1 install: `node install-npm.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the appium-chromedriver@3.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\nodejs\node-cache\_logs\2017-11-27T00_50_33_490Z-debug.log
