### ISSUE TITLE
error on running: ./bin/ios-webkit-debug-proxy-launcher.js -c <UDID>:27753 -d

### ISSUE THREAD

**Issue by tinnitweet** [appium/appium#5518]
Error message displayed on terminal:

module.js:338
    throw err;
          ^
Error: Cannot find module 'underscore'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/manitpalsidhu/Downloads/appium-1.4.8/bin/ios-webkit-debug-proxy-launcher.js:22:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

Steps performed:
1. Downloaded the source for Appium
2. Reached the Appium source directory
3. Executed the command
4. IOS-8.4.1, Appium-1.4.8
I was hoping that i will be able to launch the webkit proxy successfully. Please see if it is a defect or my set-up is incorrect. Thank you.

Note: before this i brew installed node.js as script was throwing error related to node.

**Comment by scottdixon** [comment]
Please try Appium 1.5 - you can run `npm install -g appium`

Reopen if you have any issues.

**Comment by krishnapujari** [comment]
I am also facing the same issue, did we got any workaround on the above issue

**Comment by krishnapujari** [comment]
Even with 1.5 i am facing the same issue

**Comment by imurchie** [comment]
The simplest workaround would be to run `npm install underscore` (or `npm install -g underscore` if you are running globally.

The latest Appium will automatically manage the webkit debug proxy for you. See https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/ios-webkit-debug-proxy.md
