### ISSUE TITLE
Application is not launching on ios simulator 8.4 / 8.3

### ISSUE THREAD

**Issue by shrikantkaramkar** [appium/appium#5524]
Trying to open native app for mobile using Appium on iOS Simulators 8.3 / 8.4. It is giving issues:
 Below is the log:
```  https://gist.github.com/shrikantkaramkar/7a144da1c950a83fa52c  ```
```
Details about my systems:
MAC OS Version: OS X YOSEMITE 10.10.4
Appium Version: 1.4.0
XCODE Version: 6.4 [6E35b]
Simulators installed: 8.3 and 8.4
```

```
Issue Description: It opens the simulator with application and disappears back and forth all the time and then crashes with the above error mentioned.
I tried to open application using Appium Inspector, that is also giving same errors.
Another problem is, when I am giving deviceName as "iPhone 6" with "8.3" simulator, it is by default taking "iPhone 6" with "8.4" simulator.
I tried following options:
- Deleted all instruments and installed fresh
- Checked all the entries in com.apple.iPhoneSimulator.plist
- Changed the .plist to use 8.3 or 8.4 sdk
```
Please help me out.

**Comment by abatgit** [comment]
@shrikantkaramkar ,

As per your log:

info: --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/skaram200/Documents/workspace/XfinityMyAccount-1.10.0.3.ipa","automationName":null,"port":0,"deviceName":null,"udid":null,"platformName":"iOS","newCommandTimeout":null}}
info: Client User-Agent string: appium/ruby_lib/7.0.0
info: [debug] The following desired capabilities were provided, but not recognized by appium.

You need to provide "deviceName" and "udid" in DesiredCapabilities.

You can get "udid" for devices by executing "instruments -s devices" from command line.

**Comment by shrikantkaramkar** [comment]
I am trying to use ios simulator instead of real devices with Appium for my Automation.
My Desired Caps are:
``` 
automationName = "Appium"
platformName = "iOS"
platformVersion = "8.3"
deviceName = "iPhone 5s"
app = "/Users/skaram200/Desktop/ios_build/XfinityMyAccount_6.3.app"
```

Few captured errors are:
```
[INST STDERR] 2015-09-10 10:46:57.279 instruments[36708:1269740] WebKit Threading Violation - initial use of WebKit from a secondary thread.
info: [debug] [INST STDERR] Instruments Trace Error : Target failed to run: Unable to install app with path: /Users/skaram200/Desktop/ios_build/XfinityMyAccount_6.3.app: "(null)"
```
```
nfo: [debug] [INST STDERR] 2015-09-10 10:47:20.672 instruments[36855:1272282] WebKit Threading Violation - initial use of WebKit from a secondary thread.
info: [debug] [INST] Waiting for device to boot...
info: [debug] [INST STDERR] Instruments Trace Error : Target failed to run: Unable to install app with path: /Users/skaram200/Desktop/ios_build/XfinityMyAccount_6.3.app: "(null)"
info: [debug] [INSTSERVER] Instruments exited with code 253
info: [debug] Killall instruments
info: [debug] Instruments crashed on startup
info: [debug] We exceeded the number of retries allowed for instruments to successfully start; failing launch
info: [debug] Stopping iOS log capture
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killing any other simulator daemons
info: [debug] Killall iOS Simulator
info: [debug] Cleaning sim data files
info: Executing: xcrun simctl erase F54870E7-17FD-4A07-B6EE-1636F6AB5757 with timeout 2000
info: Executing: xcrun simctl erase F54870E7-17FD-4A07-B6EE-1636F6AB5757 with timeout 2000
info: [debug] Cleaning app data files
warn: Applications directory /Users/skaram200/Library/Developer/CoreSimulator/Devices/F54870E7-17FD-4A07-B6EE-1636F6AB5757/data/Applications doesn't exist. Have you run this simulator before?
info: Couldn't find app directories to delete. Probably it's not installed
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: Instruments crashed on startup
info: [debug] Error: Instruments crashed on startup
    at [object Object].Instruments.onInstrumentsExit (/Users/skaram200/Documents/workspace/appium_1/node_modules/appium-instruments/lib/instruments.js:440:31)
    at [object Object].<anonymous> (/Users/skaram200/Documents/workspace/appium_1/node_modules/appium-instruments/lib/instruments.js:353:12)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Instruments crashed on startup)","origValue":"Instruments crashed on startup"},"sessionId":null}
info: <-- POST /wd/hub/session 500 30057.679 ms - 182 
```

I used grunt command to authorize on ios also, I am using Xcode 6.3.2, appium 1.4.0 and MAC OS 10.10.x

**Comment by scottdixon** [comment]
Is your device able to run the app without Appium?

**Comment by SrinivasanTarget** [comment]
Closing this because of inactivity.

**Comment by SrinivasanTarget** [comment]
@triager please close
