### ISSUE TITLE
Problem Handling Javascript Dialogs/ Alerts

### ISSUE THREAD

**Issue by reqr27** [appium/appium#5528]
Hello, im Using Appium.App for Mac (Yosemite) on a samsung Galaxy S4 (5.0,1) and im getting this error (see below), if someone knows how to fix it please tell me.

Error
Traceback (most recent call last):
  File "C:\Users\QA\PycharmProjects\BantasyTestSuite\BantasyTestSuite_modified_new_design.py", line 938, in runTest
    alert.accept()
  File "C:\Python27\lib\site-packages\selenium\webdriver\common\alert.py", line 80, in accept
    self.driver.execute(Command.ACCEPT_ALERT)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 196, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
WebDriverException: Message: unknown error: unhandled inspector error: {"code":-32603,"message":"Could not handle JavaScript dialog"}
  (Session info: chrome=44.0.2403.90)
  (Driver info: chromedriver=2.15.322455 (ae8db840dac8d0c453355d3d922c91adfb61df8f),platform=Mac OS X 10.10.5 x86_64)

**Comment by scottdixon** [comment]
Closing old issue. Please try a more recent version of Appium. Reopen if the issue persists.
