### ISSUE TITLE
failed to install app on device

### ISSUE THREAD

**Issue by Kolyall** [appium/appium#5542]
failed to install app on device, Same app push from xcode was able to launch and use UI inspector
Please see the complete log. 

Launching Appium with command: '/Applications/Appium.app/Contents/Resources/node/bin/node' lib/server/main.js --command-timeout "7200" --debug-log-spacing --platform-version "8.3" --platform-name "iOS" --app "com.parrot.flowerpower2" --udid "6c91fea6d26ff7034e1f380d67513e75108f0277" --show-ios-log --device-name "iPhone6"

info: Welcome to Appium v1.4.8 (REV c8179bd8352d3c62d98fa58b324491230df9342a)

info: Appium REST http interface listener started on 0.0.0.0:4723
info: [debug] Non-default server args: {"app":"com.parrot.flowerpower2","udid":"6c91fea6d26ff7034e1f380d67513e75108f0277","deviceName":"iPhone6","platformName":"iOS","platformVersion":"8.3","showIOSLog":true,"defaultCommandTimeout":7200,"debugLogSpacing":true}
info: Console LogLevel: debug

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}}}

info: <-- GET /wd/hub/status 200 15.893 ms - 104 {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}}}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}}}
info: <-- GET /wd/hub/status 200 4.683 ms - 104 {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}}}
info: --> GET /wd/hub/sessions {}

info: [debug] Responding to client with success: {"status":0,"value":[]}
info: <-- GET /wd/hub/sessions 200 4.624 ms - 23 {"status":0,"value":[]}

info: --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"iOS","platformVersion":"8.3","newCommandTimeout":"999999","automationName":"Appium","deviceName":"iPhone6"}}

info: Client User-Agent string: Appium (unknown version) CFNetwork/720.5.7 Darwin/14.5.0 (x86_64)
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************

info: [debug] App is an iOS bundle, will attempt to run as pre-existing

info: [debug] Creating new appium session b2729037-4f4c-4518-8500-d5e493dda066
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Auto-detecting iOS udid...
info: [debug] Not auto-detecting udid, running on sim
info: [debug] Could not parse plist file (as binary) at /Applications/Appium.app/Contents/Resources/node_modules/appium/com.parrot.flowerpower2/en.lproj/Localizable.strings
info: Will try to parse the plist file as XML
info: [debug] Could not parse plist file (as XML) at /Applications/Appium.app/Contents/Resources/node_modules/appium/com.parrot.flowerpower2/en.lproj/Localizable.strings
warn: Could not parse app Localizable.strings assuming it doesn't exist
info: [debug] Creating instruments
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/user/Library/Application Support/appium/bootstrap
info: [debug] Dynamic env: {"nodePath":"/Applications/Appium.app/Contents/Resources/node/bin/node","commandProxyClientPath":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"grouped"}

info: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...
info: [debug] Dynamic bootstrap path: /Users/user/Library/Application Support/appium/bootstrap/bootstrap-6745615c424bb0c0.js

info: [debug] Reusing dynamic bootstrap: /Users/user/Library/Application Support/appium/bootstrap/bootstrap-6745615c424bb0c0.js
info: [debug] Attempting iOS device log capture via libimobiledevice idevicesyslog

info: [debug] Creating iDevice object with udid 6c91fea6d26ff7034e1f380d67513e75108f0277

info: [debug] App is not installed. Will try to install the app.

info: [debug] Cleaning up appium session
info: [debug] Error: Installing com.parrot.flowerpower2 failed
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/node-idevice/main.js:159:6
    at ChildProcess.exithandler (child_process.js:742:7)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Installing com.parrot.flowerpower2 failed)","origValue":"Installing com.parrot.flowerpower2 failed"},"sessionId":null}

error: Failed to start an Appium session, err was: Error: Installing com.parrot.flowerpower2 failed

info: <-- POST /wd/hub/session 500 3547.001 ms - 204 

info: [IOS_SYSLOG_ROW ] Aug 28 13:11:52 iPhone6 syslog_relay[2304] <Notice>: syslog_relay found the ASL prompt. Starting...

info: [IOS_SYSLOG_ROW ] Aug 28 13:11:53 iPhone6 CLTM[20] <Error>: CLTM: _subscription 0x0, _subscribedChannels 0x0

info: [IOS_SYSLOG_ROW ] Aug 28 13:11:54 iPhone6 mobile_installation_proxy[2306] <Error>: 0x100594000 handle_connection: Could not receive request from host.

info: [IOS_SYSLOG_ROW ] Aug 28 13:11:58 iPhone6 CLTM[20] <Error>: CLTM: _subscription 0x0, _subscribedChannels 0x0

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}}}
info: <-- GET /wd/hub/status 200 2.201 ms - 104 {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}}}

info: [IOS_SYSLOG_ROW ] Aug 28 13:12:03 iPhone6 CLTM[20] <Error>: CLTM: _subscription 0x0, _subscribedChannels 0x0

**Comment by Kolyall** [comment]
found
need to set on device settings -> developer->Enable UI automation to ON
