### ISSUE TITLE
Error (Original error: 'java -version' failed. Error: Command failed: ) while running appium testcase

### ISSUE THREAD

**Issue by hmsingh197** [appium/appium#5602]
I am trying to run below code 

public static void main(String args[]) throws Exception{
		
		AndroidDriver driver ;
		DesiredCapabilities cap = new DesiredCapabilities();
		cap.setCapability("deviceName", "MotoE2");
		cap.setCapability("platformName", "Android");
		cap.setCapability("version", "5.1");
		cap.setCapability("androidPackage", "com.whatsapp");
		cap.setCapability("app-activity", "com.whatsapp.Main");

driver= new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"),cap);

**Comment by hmsingh197** [comment]
Updating further , as it saved before I complete....

When I run above code, it gives error on last line...as below
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: A new session could not be created. (Original error: 'java -version' failed. Error: Command failed: ) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 357 milliseconds
Build info: version: '2.46.0', revision: '61506a4624b13675f24581e453592342b7485d71', time: '2015-06-04 10:22:50'
System info: host: 'har-PC', ip: '192.168.43.1', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.7.0_71'
Driver info: io.appium.java_client.android.AndroidDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:605)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:27)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:242)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:128)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:155)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:22)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:202)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:50)
	at test.main(test.java:52)

Environment Details : 

1. OS : Windows 10
2. Appium version : 1.4.0.0
3. Phone : Motorola MOTO E2
4. Java version : 1.7

I have set JAVA_HOME , ANDROID_HOME correctly. Device is identied in the eclipse. 

Actuall everything was running good some time back , but suddendly this error started coming.

**Comment by hmsingh197** [comment]
Log from Appium:
info: <-- POST /wd/hub/session 500 121.132 ms - 216 
> info: --> POST /wd/hub/session {"desiredCapabilities":{"androidPackage":"com.whatsapp","deviceName":"MotoE2","platformName":"Android","app-activity":"com.whatsapp.Main","version":"5.1"}}
> info: Client User-Agent string: Apache-HttpClient/4.3.3 (java 1.5)
> info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : androidPackage, app-activity, version
> info: [debug] No appActivity desired capability or server param. Parsing from apk.
> info: [debug] Didn't get app but did get Android package, will attempt to launch it on the device
> info: [debug] Creating new appium session 2c679d40-2715-4ae5-9ccf-59aa80570286
> info: Starting android appium
> info: [debug] Getting Java version
> info: [debug] Cleaning up android objects
> error: Failed to start an Appium session, err was: Error: 'java -version' failed. Error: Command failed: 
> info: [debug] Cleaning up appium session
> info: [debug] Error: 'java -version' failed. Error: Command failed: 
>     at [object Object].<anonymous> (C:\Program Files (x86)\Appium\node_modules\appium\lib\devices\android\android-common.js:1057:17)
>     at ChildProcess.exithandler (child_process.js:641:7)
>     at ChildProcess.EventEmitter.emit (events.js:98:17)
>     at maybeClose (child_process.js:743:16)
>     at Process.ChildProcess._handle.onexit (child_process.js:810:5)
> info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: 'java -version' failed. Error: Command failed: )","origValue":"'java -version' failed. Error: Command failed: "},"sessionId":null}
> info: <-- POST /wd/hub/session 500 114.736 ms - 216

**Comment by hmsingh197** [comment]
I have observed one thing that my adb command is also not working. It gives error "adb.exe has stopped working" Window is checking solution for your problem."  

I updated my sdk through sdk manager but still problem exists.

Is this something to do with Windows upgrdae from Window 7 to Window 10. I have done that sometime back.

**Comment by scottdixon** [comment]
Closing old issue. Please try a more recent version of Appium. Reopen if the issue persists.
