### ISSUE TITLE
TypeError: Cannot read property 'toLowerCase' of null

### ISSUE THREAD

**Issue by Simon-Kaz** [appium/appium#5621]
Following error pops up when creating a new session.  I'm on node v0.12.2 and using the latest beta v1.5.0-beta4

I'm on slack if you need more information, it's currently blocking me from trying out the beta :(

``` 
info: [HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"test.app","sendKeyStrategy":"setValue","newCommandTimeout":180,"platformVersion":"9.0","bundleId":"com.test.test","platformName":"iOS","udid":"hereGoesMyUdidNumber","deviceName":"iPhone 6 Plus","fullReset":true,"autoAcceptAlerts":true}}
info: [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"test.app","sendKeyStrategy":"setValue","newCommandTimeout":180,"platformV...
info: [Appium] Creating new IosDriver session
info: [BaseDriver] Session created with session id: fc0fc482-bb64-4032-9596-60998f7ffafd
error: [MJSONWP] Encountered internal error running command: TypeError: Cannot read property 'toLowerCase' of null
    at Object.prepareIosOpts (lib/utils.js:39:23)
    at IosDriver.createSession$ (lib/driver.js:105:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:89:39)
    at /usr/local/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:100:28
    at flush (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:17:13)
    at process._tickCallback (node.js:355:11)
info: [HTTP] <-- POST /wd/hub/session 500 10.963 ms - 179

````

**Comment by ivan-baranovski-intellectsoft** [comment]
I have the same problem.
I updated appium to the latest beta v1.5.0-beta4 today. I use node v0.12.7.

info: [HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/karpeko/Documents/workspace/Tests/Test.app.zip","orientation":"PORTRAIT","nativeInstrumentsLib":true,"noReset":false,"platformVersion":"9.0","bundleId":"com.cirruspath.temp.intellectsoft.Test","keepKeyChains":false,"platformName":"iOS","udid":"876adebc56d2fb4ea46787d2d5ef9c80e0c3962c","deviceName":"iPhone 6","fullReset":true}}
info: [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/karpeko/Documents/workspace/Tests/Test.app.zip","orientation":"PORTRAIT","nativeInstrumentsLib":...
info: [Appium] Creating new IosDriver session
info: [BaseDriver] Session created with session id: d04e4521-a5c0-447d-8c66-b8a495508b47
error: [MJSONWP] Encountered internal error running command: TypeError: Cannot read property 'toLowerCase' of null
    at Object.prepareIosOpts (lib/utils.js:39:23)
    at IosDriver.createSession$ (lib/driver.js:105:11)
    at tryCatch (/Users/karpeko/.nvm/versions/node/v0.12.7/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/karpeko/.nvm/versions/node/v0.12.7/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/karpeko/.nvm/versions/node/v0.12.7/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/karpeko/.nvm/versions/node/v0.12.7/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Users/karpeko/.nvm/versions/node/v0.12.7/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:89:39)
    at /Users/karpeko/.nvm/versions/node/v0.12.7/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:100:28
    at flush (/Users/karpeko/.nvm/versions/node/v0.12.7/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:17:13)
    at process._tickCallback (node.js:355:11)
info: [HTTP] <-- POST /wd/hub/session 500 6.635 ms - 179
