### ISSUE TITLE
Failed to adjust network connection before launching the app (autoLaunch: false)

### ISSUE THREAD

**Issue by imsardine** [appium/appium#5654]
With `autoLaunch: false`, more than one test cases can be run in a session. Because monkey testing runs on the same device, chances are that Wi-Fi may be turned off by the monkey, and Wi-Fi should be turned on (if needed) before the first test case starts.

Adjusting network connection before launching the app runs into the following error: (Appium 1.4.11)

    info: --> POST /wd/hub/session/ccbf3b1f-ac63-4ff9-9e41-1634bfc1461d/network_connection {"sessionId":"ccbf3b1f-ac63-4ff9-9e41-1634bfc1461d","parameters":{"type":2}}
    info: Setting network connection
    info: [debug] executing cmd: /path/to/android-sdk-macosx/platform-tools/adb shell "settings put global airplane_mode_on 0"
    info: [debug] executing cmd: /path/to/android-sdk-macosx/platform-tools/adb kill-server
    info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
    info: [debug] executing cmd: /path/to/android-sdk-macosx/platform-tools/adb wait-for-device
    info: [debug] executing cmd: /path/to/android-sdk-macosx/platform-tools/adb shell "echo 'ready'"
    info: [debug] Starting logcat capture
    error: Unhandled error: TypeError: Cannot read property 'start' of null
        at [object Object].Android.restartUiautomator (/usr/local/lib/node_modules/appium/lib/devices/android/android.js:174:23)
        at /usr/local/lib/node_modules/appium/node_modules/async/lib/async.js:607:21
        at /usr/local/lib/node_modules/appium/node_modules/async/lib/async.js:246:17
        at iterate (/usr/local/lib/node_modules/appium/node_modules/async/lib/async.js:146:13)
        at /usr/local/lib/node_modules/appium/node_modules/async/lib/async.js:157:25
        at /usr/local/lib/node_modules/appium/node_modules/async/lib/async.js:248:21
        at /usr/local/lib/node_modules/appium/node_modules/async/lib/async.js:612:34
        at /usr/local/lib/node_modules/appium/node_modules/async/lib/async.js:251:17
        at /usr/local/lib/node_modules/appium/node_modules/async/lib/async.js:154:25
        at /usr/local/lib/node_modules/appium/node_modules/async/lib/async.js:248:21
        at [object Object].onLogcatStart (/usr/local/lib/node_modules/appium/node_modules/async/lib/async.js:612:34)
        at [object Object].Logcat.onOutput (/usr/local/lib/node_modules/appium/node_modules/appium-adb/lib/logcat.js:81:12)
        at [object Object].Logcat.onStdout (/usr/local/lib/node_modules/appium/node_modules/appium-adb/lib/logcat.js:61:8)
        at Stream.stream.write (/usr/local/lib/node_modules/appium/node_modules/through/index.js:26:11)
        at Socket.ondata (_stream_readable.js:540:20)
        at Socket.emit (events.js:107:17)
        at readableAddChunk (_stream_readable.js:163:16)
        at Socket.Readable.push (_stream_readable.js:126:10)
        at Pipe.onread (net.js:538:20) context: [POST /wd/hub/session/ccbf3b1f-ac63-4ff9-9e41-1634bfc1461d/network_connection {"sessionId":"ccbf3b1f-ac63-4ff9-9e41-1634bfc1461d","parameters":{"type":2}}]
    info: <-- POST /wd/hub/session/ccbf3b1f-ac63-4ff9-9e41-1634bfc1461d/network_connection - - ms - -
    undefined

I'm curious about the necessity of "starting logcat capture" during adjusting network connection.

**Comment by scottdixon** [comment]
@imsardine - can you see if you have better luck with 1.5?

Reopen + post logs if the issue persists.
