### ISSUE TITLE
Issue with click()

### ISSUE THREAD

**Issue by dhirendragupta** [appium/appium#5655]
I have issue with click() on some element click() method is not working. I tried with 4 click() on the same element then it was able to click.

Same script some times runs as expected and sometimes fails. When it fails I had to restart the system and then it worked. Can anyone explain this unexpected behavior of Appium.

**Comment by moizjv** [comment]
@dhirendragupta try using `tap`

**Comment by amaricleroberts** [comment]
I've been having the same problem on Appium 1.4.11 on my iOS simulator.  It finds the WebElement but is unable to click it.  This wasn't happening on Appium 1.4.8.


org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1.36 seconds
Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
System info: host: 'Amandas-MacBook-Pro.local', ip: '192.168.88.144', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.8.0_51'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{app=/Users/amanda/Desktop/RHR.app, networkConnectionEnabled=false, warnings={}, bundleId=com.homespotter.rhr, databaseEnabled=false, deviceName=iPhone 6, platform=UNIX, desired={app=/Users/amanda/Desktop/RHR.app, locationServicesAuthorized=true, platformVersion=8.4, bundleId=com.homespotter.rhr, platformName=iOS, deviceName=iPhone 6, platform=iOS}, locationServicesAuthorized=true, platformVersion=8.4, webStorageEnabled=false, locationContextEnabled=false, browserName=iOS, takesScreenshot=true, javascriptEnabled=true, platformName=iOS}]
Session ID: 339a7554-58f5-4457-b0e8-8e2e6b336d1e
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:180)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:268)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:79)
	at com.mobilerealtyapps.testing.PageObjects.MapView.openContactSlider(MapView.java:61)
	at com.mobilerealtyapps.testing.tests.ContactSliderTests.BrandToAgent.BrandToAgent(BrandToAgent.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

**Comment by moizjv** [comment]
@amaricleroberts try `tap`

**Comment by amaricleroberts** [comment]
@moizjv I don't have that option with WebElement

**Comment by amaricleroberts** [comment]
I tried casting the elements to MobileElement and using that tap but I am having the same problem

**Comment by dhirendragupta** [comment]
I am testing a Salesforce1 apk with some custom app, But somehow custom buttons xpaths looks weird.  Actual button is somewhere at the top and  xpath points it to the footer of the screen.
