### ISSUE TITLE
Java.lang.IllegalAccessError from PageFactory when I switch to java-client 3.2.0 

### ISSUE THREAD

**Issue by mkataokaelementum** [appium/appium#5683]
If I do "PageFactory.initElements(new AppiumFieldDecorator(driver), this);" with java-client 2.2.0 it works. If I switch to java-client 3.2.0, java.lang.IllegalAccessError occurs.

Does anyone know what is going on?

Here are the logs.

java.lang.IllegalAccessError: tried to access method org.openqa.selenium.support.pagefactory.Annotations.assertValidAnnotations()V from class io.appium.java_client.pagefactory.AppiumAnnotations
at io.appium.java_client.pagefactory.AppiumAnnotations.assertValidAnnotations(AppiumAnnotations.java:222)
at io.appium.java_client.pagefactory.AppiumAnnotations.buildBy(AppiumAnnotations.java:315)
at io.appium.java_client.pagefactory.AppiumElementLocator.(AppiumElementLocator.java:109)
at io.appium.java_client.pagefactory.AppiumElementLocatorFactory.createLocator(AppiumElementLocatorFactory.java:41)
at io.appium.java_client.pagefactory.AppiumFieldDecorator.decorate(AppiumFieldDecorator.java:102)
at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:112)
at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:104)
at com.elementum.qe.clients.android.exposure.pages.LoginPage.(LoginPage.java:29)
at com.elementum.qe.clients.android.exposure.testng.NewCreateIssueTest.beforeTest(NewCreateIssueTest.java:42)

**Comment by SouWilliams** [comment]
Maybe you need to change as below:

PageFactory.initElements(new AppiumFieldDecorator(driver, 5,TimeUnit.SECONDS), this);

It works on my laptop

**Comment by mkataokaelementum** [comment]
Tested with java-client 3.2.0.  It did not work.... Below is my partial code.  Any idea? 

public class CommonMobileLoginPage extends PageObjectBase implements ILoginPage {

    public AppiumDriver driver;

    public CommonMobileLoginPage(AppiumDriver driver) {
        super();
        this.driver = driver;
        PageFactory.initElements(new AppiumFieldDecorator(driver,5, TimeUnit.SECONDS), this);
    }

**Comment by SrinivasanTarget** [comment]
@mkataokaelementum please give a try in appium 1.5.1 and java-client 3.4.1.Incase of issues, please report here,https://github.com/appium/java-client/issues

FYI https://github.com/appium/java-client/blob/master/docs/Page-objects.md

**Comment by SrinivasanTarget** [comment]
@triager please close
