### ISSUE TITLE
WebDriverException when searching for an element after switching to a frame

### ISSUE THREAD

**Issue by kisialiu** [appium/appium#5688]
Hello,

I have a problem with Appium (I tried 1.4.11+) when running tests on iOS (8-9). Android works perfect. The problem is that I need to switch to the frame to click the link. But it throws WebDriverException:

``` java
org.openqa.selenium.WebDriverException: undefined is not an object (evaluating 'a.querySelectorAll') (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 246 milliseconds
Build info: version: '2.47.1', revision: 'unknown', time: '2015-07-30 11:02:44'
System info: host: 'epbyminw3013.minsk.epam.com', ip: '10.6.88.51', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.4', java.version: '1.8.0_60'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{networkConnectionEnabled=false, safari=true, warnings={}, webdriver.remote.quietExceptions=true, hasMetadata=true, databaseEnabled=false, deviceName=iPhone Simulator, platform=MAC, desired={safariIgnoreFraudWarning=true, platformVersion=9.0, safariAllowPopups=true, webdriver.remote.quietExceptions=true, platformName=iOS, deviceName=iPhone Simulator}, webdriver.remote.sessionid=ed1d895b7e544ef7af4dd57f93bf0f2a, safariIgnoreFraudWarning=true, safariAllowPopups=true, platformVersion=9.0, locationContextEnabled=false, webStorageEnabled=false, takesScreenshot=true, browserName=iOS, javascriptEnabled=true, platformName=iOS}]
Session ID: ed1d895b7e544ef7af4dd57f93bf0f2a
*** Element info: {Using=link text, value=Behind-the-scenes at the LISTERINE® Brand laboratory – See Why Brushing is not Enough}
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:595)
    at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
    at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
    at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
    at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:373)
    at org.openqa.selenium.remote.RemoteWebDriver.findElementsByLinkText(RemoteWebDriver.java:401)
    at io.appium.java_client.DefaultGenericMobileDriver.findElementsByLinkText(DefaultGenericMobileDriver.java:76)
    at io.appium.java_client.AppiumDriver.findElementsByLinkText(AppiumDriver.java:94)
    at org.openqa.selenium.By$ByLinkText.findElements(By.java:238)
    at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:336)
    at io.appium.java_client.DefaultGenericMobileDriver.findElements(DefaultGenericMobileDriver.java:47)
    at io.appium.java_client.AppiumDriver.findElements(AppiumDriver.java:85)
    at com.jjconsumer.dte.selenium.Test.main(Test.java:29)
```

Steps to reproduce:

``` java
DesiredCapabilities caps = DesiredCapabilities.iphone();
caps.setCapability("appiumVersion", "1.4.11");
caps.setCapability("deviceName", "iPhone Simulator");
caps.setCapability("deviceOrientation", "portrait");
caps.setCapability("platformVersion", "9.0");
caps.setCapability("platformName", "iOS");
caps.setCapability("browserName", "Safari");
caps.setCapability("safariIgnoreFraudWarning", true);
caps.setCapability("safariAllowPopups", true);

IOSDriver<WebElement> driver = new IOSDriver<>(new URL("http://user:key@ondemand.saucelabs.com:80/wd/hub"), caps);
driver.get("http://www.listerine.com");
driver.switchTo().frame(driver.findElement(By.xpath("//iframe[contains(@src,'Ltl6mZ4vMZQ')]")));
driver.findElements(By.linkText("Behind-the-scenes at the LISTERINE® Brand laboratory – See Why Brushing is not Enough"));
```

I wonder, if it is possible to make this work, since Android and Desktop is ok?

**Comment by Nishant-Taksande** [comment]
I ran into the same issue.

Below is the application reference:
1. Launch browser and navigate to "http://m.ebay.com.au"
2. Click on Sign in / Register link (Sign in page will be displayed with Register Tab).
3. Click on Register tab.
4. Try entering data in any field.

iFrame: id = regFrame

At present i am blocked due to this issue, and i had to sacrifice my registration scripts due to this.

**Comment by htorresrocca** [comment]
I have the same problem on iOS device and simulator tests.  The same tests work fine when run through an android device's browser (both real device and simulator) but not on either an iOS device or simulator.  I have not found much information on the web about anyone encountering this issue so my questions are:
1.  What approach do you take when attempting to access an element in a child iframe?  I am using the same approach that kisialiu outlines above.

2. Is this a known bug?

Cheers.

**Comment by rkavalap** [comment]
Closing this as dup for #5832
