### ISSUE TITLE
Issue: org.openqa.selenium.remote.SessionNotFoundException: 

### ISSUE THREAD

**Issue by murlismiles** [appium/appium#5697]
I am getting the Session not found exception while executing the command executor.executeScript("mobile:tap", e). I am using the appium 1.4 version.  Initially was using appium version 1.3.4 and there was no issue.
Note: I am automating the app in the web view.

Exception in thread "main" org.openqa.selenium.remote.SessionNotFoundException: 
Command duration or timeout: 127 milliseconds
Build info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:03:00'
System info: host: '01HW508967', ip: '157.227.50.234', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.7.0_45'
Session ID: 9b9909b99bf9e6555a8b120402831aa7
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities [{platform=ANDROID, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, applicationCacheEnabled=false, takesScreenshot=true}]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:162)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:508)

**Comment by SrinivasanTarget** [comment]
@murlismiles give a try on appium 1.5.1.If you still face an issue with 1.5.1, raise a new issue with more description and with logs in form of gist.

**Comment by SrinivasanTarget** [comment]
@triager please close
