### ISSUE TITLE
Cannot read property 'init' of undefined

### ISSUE THREAD

**Issue by frbk** [appium/appium#5745]
I keep getting this error when I try to start appium on yosemity 10.10.2.
I am using appium 1.4.13.

Here is full error log:
```
Launching Appium with command: '/Applications/Appium.app/Contents/Resources/node/bin/node' 
lib/server/main.js --command-timeout "7200" --debug-log-spacing --platform-version "8.4" 
--platform-name "iOS" --app "/Users/qac/Desktop/Catch (51).ipa" --show-ios-log --show-ios-log
 --device-name "iPhone 6 Plus"

error: uncaughtException: Cannot read property 'init' of undefined date=Tue Oct 20
 2015 10:59:18 GMT-0400 (EDT), pid=6614, uid=501, gid=20, cwd=/Applications/Appium.app/Contents/Resources/node_modules/appium,
 execPath=/Applications/Appium.app/Contents/Resources/node/bin/node, version=v0.12.7,
 argv=[/Applications/Appium.app/Contents/Resources/node/bin/node, /Applications/Appium.app/Contents/Resources/node_modules/appium/lib/server/main.js,
 --command-timeout, 7200, --debug-log-spacing, --platform-version, 8.4, --platform-name, iOS, --app, /Users/qac/Desktop/Catch (51).ipa, --show-ios-log,
 --show-ios-log, --device-name, iPhone 6 Plus], rss=115720192, heapTotal=97848064, heapUsed=67946200, loadavg=[2.23876953125, 2.3125, 1.79296875],
 uptime=6113, trace=[column=7, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/uiauto.js, function=, line=7,
 method=null, native=false, column=26, file=module.js, function=Module._compile, line=460, method=_compile, native=false, column=10, file=module.js,
 function=Object.Module._extensions..js, line=478, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load,
 line=355, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=310, method=Module._load, native=false, 
column=17, file=module.js, function=Module.require, line=365, method=require, native=false, column=17, file=module.js, function=require, line=384, 
method=null, native=false, column=24, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js, function=, line=28,
 method=null, native=false, column=26, file=module.js, function=Module._compile, line=460, method=_compile, native=false, column=10, file=module.js,
 function=Object.Module._extensions..js, line=478, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=355,
 method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=310, method=Module._load, native=false, column=17, file=module.js, 
function=Module.require, line=365, method=require, native=false, column=17, file=module.js, function=require, line=384, method=null, native=false, column=11,
file=/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/appium.js, function=, line=8, method=null, native=false, column=26, file=module.js,
 function=Module._compile, line=460, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=478, 
method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=355, method=load, native=false, column=12, file=module.js,
 function=Function.Module._load, line=310, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=365, method=require,
 native=false, column=17, file=module.js, function=require, line=384, method=null, native=false, column=14, 
file=/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/server/main.js, function=, line=54, method=null, native=false, column=26,
 file=module.js, function=Module._compile, line=460, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, 
line=478, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=355, method=load, native=false, column=12,
 file=module.js, function=Function.Module._load, line=310, method=Module._load, native=false, column=10, file=module.js, function=Function.Module.runMain,
 line=501, method=Module.runMain, native=false, column=16, file=node.js, function=startup, line=129, method=null, native=false, column=3, file=node.js,
 function=null, line=814, method=null, native=false], stack=[TypeError: Cannot read property 'init' of undefined, 
    at Object.<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/uiauto.js:7:7),
     at Module._compile (module.js:460:26),     at Object.Module._extensions..js (module.js:478:10),     at Module.load (module.js:355:32),   
  at Function.Module._load (module.js:310:12),     at Module.require (module.js:365:17),     at require (module.js:384:17), 
    at Object.<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js:28:24),  
   at Module._compile (module.js:460:26),     at Object.Module._extensions..js (module.js:478:10),     at Module.load (module.js:355:32),   
  at Function.Module._load (module.js:310:12),     at Module.require (module.js:365:17),     at require (module.js:384:17),  
   at Object.<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/appium.js:8:11),  
   at Module._compile (module.js:460:26),     at Object.Module._extensions..js (module.js:478:10),     at Module.load (module.js:355:32),  
   at Function.Module._load (module.js:310:12),     at Module.require (module.js:365:17),     at require (module.js:384:17),    
 at Object.<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/server/main.js:54:14),   
  at Module._compile (module.js:460:26),     at Object.Module._extensions..js (module.js:478:10),    
 at Module.load (module.js:355:32),     at Function.Module._load (module.js:310:12), 
    at Function.Module.runMain (module.js:501:10),     at startup (node.js:129:16),   
  at node.js:814:3]
```

**Comment by scottdixon** [comment]
Is there any output prior to `Cannot read property 'init'`?

**Comment by rets5s** [comment]
There is nothing before the error.

**Comment by scottdixon** [comment]
hmm... can you try running Appium from source?

**Comment by SrinivasanTarget** [comment]
@frbk Please use a latest version of appium. Incase of issues on recent versions post logs in form of gist.

**Comment by SrinivasanTarget** [comment]
Closing this because of inactivity.

**Comment by SrinivasanTarget** [comment]
@triager please close
