### ISSUE TITLE
Xcode 7 - iwd patch not working for npm installed appium

### ISSUE THREAD

**Issue by calin-ciobanu** [appium/appium#5754]
The script does not input the correct paths into .plist file if appium is installed via npm (osx 10.10.5 - appium 1.4.13)

In the script:
https://github.com/appium/appium/blob/master/bin/xcode_iwd.sh

To fix this scenario the line
```
iwd_path=$2/node_modules/appium_instruments/thridparty/iwd7
```

should be replaced with
```
iwd_path=$2/node_modules/appium-instruments/thirdparty/iwd7
```
[third is misspelled and - in appium-instruments]

and the example usage is
```
sh ./bin/xcode_iwd.sh /Applications/Xcode.app /usr/local/lib/node_modules/appium
```
NOTE: Even with the script injecting the correct paths in .plist for me the speed is still the same (slow). Using Xcode 7.1-beta3

**Comment by scottdixon** [comment]
Nice catch! If you've made this change, please submit a PR.

**Comment by nabeel-ibrahim** [comment]
I have the same issue, I corrected the errors in the script but my tests are still running very slowly

**Comment by moizjv** [comment]
https://github.com/appium/appium/pull/5772

**Comment by moizjv** [comment]
@nabeel-ibrahim it only works for 9.0 and 9.1 not for other versions. 

can you print plist file using `/usr/libexec/PlistBuddy -c print <xcodepath>/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/Developer/Library/LaunchDaemons/com.apple.instruments.deviceservice.plist`?

**Comment by nabeel-ibrahim** [comment]
`Dict {
    JetsamProperties = Dict {
        JetsamMemoryLimit = 0
    }
    Program = /Developer/Library/PrivateFrameworks/DVTInstrumentsFoundation.framework/DTServiceHub
    Label = com.apple.instruments.deviceservice
    POSIXSpawnType = Adaptive
    MachServices = Dict {
        com.apple.instruments.deviceservice.xpc = true
        com.apple.instruments.deviceservice.lockdown = true
    }
    EnableTransactions = true
}
`

**Comment by nabeel-ibrahim** [comment]
@moizjv I have xcode 7.1 with ios 9.1

**Comment by moizjv** [comment]
@nabeel-ibrahim it should have `EnvironmentVariables = Dict {
        LIB_PATH = ./node_modules/appium-instruments/thirdparty/iwd7/
        DYLD_INSERT_LIBRARIES = /Users/appium/node_modules/appium-instruments/thirdparty/iwd7/DTMobileISShim.dylib
    }`; try rerunning the script with latest changes from #5772

**Comment by nabeel-ibrahim** [comment]
I see what the issue was I had to use sudo before running the script, but now appium is crashing

**Comment by moizjv** [comment]
can you print plist file now?

**Comment by nabeel-ibrahim** [comment]
`Dict {
    Program = /Developer/Library/PrivateFrameworks/DVTInstrumentsFoundation.framework/DTServiceHub
    EnvironmentVariables = Dict {
        LIB_PATH = /Users/nibrahim/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd7/
        DYLD_INSERT_LIBRARIES = /Users/nibrahim/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd7/DTMobileISShim.dylib
    }
    JetsamProperties = Dict {
        JetsamMemoryLimit = 0
    }
    POSIXSpawnType = Adaptive
    MachServices = Dict {
        com.apple.instruments.deviceservice.xpc = true
        com.apple.instruments.deviceservice.lockdown = true
    }
    EnableTransactions = true
    Label = com.apple.instruments.deviceservice
}
`

**Comment by moizjv** [comment]
this looks good; can you paste appium logs?

**Comment by nabeel-ibrahim** [comment]
`info: --> POST /wd/hub/session/e9ed3d48-7c37-4a9f-9607-3e18eed05d78/appium/app/close {}
info: <-- POST /wd/hub/session/e9ed3d48-7c37-4a9f-9607-3e18eed05d78/appium/app/close 404 0.284 ms - 40 
info: --> POST /wd/hub/session/e9ed3d48-7c37-4a9f-9607-3e18eed05d78/execute {"script":"function getElement() {var el = target.frontMostApp().mainWindow().navigationBars()[0].staticTexts().firstWithPredicate(\"name = 'Menu'\");if(!el.isVisible()){el.scrollToVisible();}return el;};getElement();","args":[""]}
info: <-- POST /wd/hub/session/e9ed3d48-7c37-4a9f-9607-3e18eed05d78/execute 404 0.610 ms - 40 
info: --> POST /wd/hub/session/e9ed3d48-7c37-4a9f-9607-3e18eed05d78/element {"using":"name","value":"Back"}
info: <-- POST /wd/hub/session/e9ed3d48-7c37-4a9f-9607-3e18eed05d78/element 404 0.398 ms - 40 
Oct 28, 2015 12:14:28 PM org.openqa.selenium.support.ui.ExpectedConditions findElement
WARNING: WebDriverException thrown by findElement(By.name: Back)
org.openqa.selenium.remote.SessionNotFoundException: 
Command duration or timeout: 2 milliseconds
Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:55:52'
System info: host: 'nibrahim-mbp.local', ip: '192.168.45.246', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.1', java.version: '1.8.0_66'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{app=/Users/nibrahim/Desktop/Automation/QA_Automation/iOS/theScore.app, networkConnectionEnabled=false, warnings={}, bundleId=com.thescore.ios.develop, databaseEnabled=false, deviceName=iPhone 6, platform=MAC, showIOSLog=true, desired={app=/Users/nibrahim/Desktop/Automation/QA_Automation/iOS/theScore.app, showIOSLog=true, nativeInstrumentsLib=false, platformVersion=9.1, bundleId=com.thescore.ios.develop, waitForAppScript=true, platformName=iOS, deviceName=iPhone 6, autoAcceptAlerts=true}, nativeInstrumentsLib=false, platformVersion=9.1, webStorageEnabled=false, locationContextEnabled=false, browserName=iOS, takesScreenshot=true, waitForAppScript=true, javascriptEnabled=true, platformName=iOS, autoAcceptAlerts=true}]
Session ID: e9ed3d48-7c37-4a9f-9607-3e18eed05d78
*** Element info: {Using=name, value=Back}
	at sun.reflect.GeneratedConstructorAccessor9.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:164)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:647)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:353)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByName(RemoteWebDriver.java:451)
	at io.appium.java_client.DefaultGenericMobileDriver.findElementByName(DefaultGenericMobileDriver.java:102)
	at io.appium.java_client.AppiumDriver.findElementByName(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.findElementByName(IOSDriver.java:1)
	at org.openqa.selenium.By$ByName.findElement(By.java:303)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:345)
	at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:52)
	at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.findElement(IOSDriver.java:1)
	at org.openqa.selenium.support.ui.ExpectedConditions.findElement(ExpectedConditions.java:911)
	at org.openqa.selenium.support.ui.ExpectedConditions.access$0(ExpectedConditions.java:909)
	at org.openqa.selenium.support.ui.ExpectedConditions$6.apply(ExpectedConditions.java:181)
	at org.openqa.selenium.support.ui.ExpectedConditions$6.apply(ExpectedConditions.java:1)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:238)
	at com.GeneralUtility.GeneralUtility.getWebElement(GeneralUtility.java:172)
	at com.GeneralUtility.GeneralUtility.tapMobileElement(GeneralUtility.java:589)
	at com.GeneralUtility.IOSUtility.navigateTo(IOSUtility.java:958)
	at com.GeneralUtility.IOSUtility.selectMainMenuItem(IOSUtility.java:989)
	at com.GeneralUtility.IOSUtility.followFromMyScore(IOSUtility.java:1114)
	at com.score.app.iOSTests.ScoreSanityiOS_37.C1241(ScoreSanityiOS_37.java:371)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at com.Rules.ScreenshotTestRule$1.evaluate(ScreenshotTestRule.java:37)
	at com.Rules.Retry$1.evaluate(Retry.java:38)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)


org.openqa.selenium.remote.SessionNotFoundException: 
Command duration or timeout: 3 milliseconds
Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:55:52'
System info: host: 'nibrahim-mbp.local', ip: '192.168.45.246', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.1', java.version: '1.8.0_66'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{app=/Users/nibrahim/Desktop/Automation/QA_Automation/iOS/theScore.app, networkConnectionEnabled=false, warnings={}, bundleId=com.thescore.ios.develop, databaseEnabled=false, deviceName=iPhone 6, platform=MAC, showIOSLog=true, desired={app=/Users/nibrahim/Desktop/Automation/QA_Automation/iOS/theScore.app, showIOSLog=true, nativeInstrumentsLib=false, platformVersion=9.1, bundleId=com.thescore.ios.develop, waitForAppScript=true, platformName=iOS, deviceName=iPhone 6, autoAcceptAlerts=true}, nativeInstrumentsLib=false, platformVersion=9.1, webStorageEnabled=false, locationContextEnabled=false, browserName=iOS, takesScreenshot=true, waitForAppScript=true, javascriptEnabled=true, platformName=iOS, autoAcceptAlerts=true}]
Session ID: e9ed3d48-7c37-4a9f-9607-3e18eed05d78
	at sun.reflect.GeneratedConstructorAccessor9.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:164)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:647)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:189)
	at io.appium.java_client.AppiumDriver.closeApp(AppiumDriver.java:245)
	at com.Rules.Retry$1.evaluate(Retry.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

`

**Comment by nabeel-ibrahim** [comment]
so the app gets terminated due to this error: 
`info: [IOS_SYSLOG_ROW ] Oct 28 12:29:39 nibrahim-mbp assertiond[6705]: assertion failed: 15B42 13B137: assertiond + 12188 [93FFE0B6-5C27-387F-B32A-6EE378BBB22A]: 0x1
info: [IOS_SYSLOG_ROW ] Oct 28 12:29:39 --- last message repeated 1 time ---
info: [IOS_SYSLOG_ROW ] Oct 28 12:29:39 nibrahim-mbp theScore[7860]: *** Assertion failure in -[UICollectionViewData validateLayoutInRect:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3512.29.5/UICollectionViewData.m:399
info: [IOS_SYSLOG_ROW ] Oct 28 12:29:39 nibrahim-mbp theScore[7860]: *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'UICollectionView received layout attributes for a cell with an index path that does not exist: <NSIndexPath: 0xc000000000000016> {length = 2, path = 0 - 0}'
info: [IOS_SYSLOG_ROW ] *** First throw call stack:
info: [IOS_SYSLOG_ROW ] (
info: [IOS_SYSLOG_ROW ] 0   CoreFoundation                      0x000000010b1caf45 __exceptionPreprocess + 165
info: [IOS_SYSLOG_ROW ] 1   libobjc.A.dylib                     0x000000010f603deb objc_exception_throw + 48
info: [IOS_SYSLOG_ROW ] 2   CoreFoundation                      0x000000010b1cadaa +[NSException raise:format:arguments:] + 106
info: [IOS_SYSLOG_ROW ] 3   Foundation                          0x000000010f2505ee -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 198
info: [IOS_SYSLOG_ROW ] 4   UIKit                               0x000000010d1d9dc5 __45-[UICollectionViewData validateLayoutInRect:]_block_invoke + 1285
info: [IOS_SYSLOG_ROW ] 5   UIKit                               0x000000010d1d939c -[UICollectionViewData validateLayoutInRect:] + 3067
info: [IOS_SYSLOG_ROW ] 6   UIKit                               0x000000010d18854c -[UICollectionView layoutSubviews] + 194
info: [IOS_SYSLOG_ROW ] 7   UIKit                               0x000000010c9ece40 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 710
info: [IOS_SYSLOG_ROW ] 8   QuartzCore                          0x000000010c3cb59a -[CALayer layoutSublayers] + 146
info: [IOS_SYSLOG_ROW ] 9   QuartzCore                          0x000000010c3bfe70 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 366
info: [IOS_SYSLOG_ROW ] 10  QuartzCore                          0x000000010c3bfcee _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 24
info: [IOS_SYSLOG_ROW ] 11  QuartzCore                          0x000000010c3b4475 _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 277
info: [IOS_SYSLOG_ROW ] 12  QuartzCore                          0x000000010c3e1c0a _ZN2CA11Transaction6commitEv + 486
info: [IOS_SYSLOG_ROW ] 13  QuartzCore                          0x000000010c3e237c _ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv + 92
info: [IOS_SYSLOG_ROW ] 14  CoreFoundation                      0x000000010b0f6947 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
info: [IOS_SYSLOG_ROW ] 15  CoreFoundation                      0x000000010b0f68b7 __CFRunLoopDoObservers + 391
info: [IOS_SYSLOG_ROW ] 16  CoreFoundation                      0x000000010b0ec50b __CFRunLoopRun + 1147
info: [IOS_SYSLOG_ROW ] 17  CoreFoundation                      0x000000010b0ebe08 CFRunLoopRunSpecific + 488
info: [IOS_SYSLOG_ROW ] 18  GraphicsServices                    0x000000011297dad2 GSEventRunModal + 161
info: [IOS_SYSLOG_ROW ] 19  UIKit                               0x000000010c93830d UIApplicationMain + 171
info: [IOS_SYSLOG_ROW ] 20  theScore                            0x0000000108fb9951 main + 65
info: [IOS_SYSLOG_ROW ] 21  libdyld.dylib                       0x0000000110a8392d start + 1`

**Comment by nabeel-ibrahim** [comment]
@moizjv it was an issue with the app itself but the tests are now running fine

**Comment by moizjv** [comment]
+1 thanks @calin-ciobanu for pointing out
