### ISSUE TITLE
The problem described in https://github.com/appium/appium/issues/5392 is back

### ISSUE THREAD

**Issue by senevit4** [appium/appium#5766]
The problem described in https://github.com/appium/appium/issues/5392 is back now on appium 1.4.13 with the same error log:
info: <-- POST /wd/hub/session/efc7943d-1ff7-4e07-ac37-80a7b006128e/appium/device/app_installed 500 1.062 ms - 101 
TypeError: Cannot read property 'isInstalled' of undefined
    at [object Object].IOS.isAppInstalled (/usr/local/lib/node_modules/appium/lib/devices/ios/ios.js:1512:20)
    at exports.isAppInstalled (/usr/local/lib/node_modules/appium/lib/server/controller.js:113:16)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:82:5)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:82:5)
    at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:267:22
    at param (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:340:14)
    at param (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:356:14)
    at Function.proto.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:400:3)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:261:10)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:100:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at exports.sessionBeforeFilter (/usr/local/lib/node_modules/appium/lib/server/controller.js:56:5)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:82:5)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:110:13)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at Route.dispatch (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:82:5)
    at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:267:22
    at Function.proto.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:321:12)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:261:10)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:100:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)

**Comment by scottdixon** [comment]
Can you please provide a gist of the entire Appium logs up to this error?

**Comment by senevit4** [comment]
Sure:
--address "127.0.0.1" --port "4724" --command-timeout "14400" --session-override --debug-log-spacing --nodeconfig "/Volumes/Data/Grid/selenium/appium/appiumNode.json" --platform-version "9.0" --platform-name "iOS" --app "com.myapp.app" --udid "4c37487a1779a90918713f536337b6a9cc12a3ad" --show-ios-log --device-name "AppleDevice"
info: Welcome to Appium v1.4.13 (REV c75d8adcb66a75818a542fe1891a34260c21f76a)
info: Appium REST http interface listener started on 127.0.0.1:4724
info: [debug] Non-default server args: {"app":"com.myapp.app","udid":"4c37487a1779a90918713f536337b6a9cc12a3ad","address":"127.0.0.1","port":4724,"sessionOverride":true,"deviceName":"AppleDevice","platformName":"iOS","platformVersion":"9.0","showIOSLog":true,"nodeconfig":"/Volumes/Data/Grid/selenium/appium/appiumNode.json","defaultCommandTimeout":14400,"debugLogSpacing":true}
info: Console LogLevel: debug
info: [debug] starting auto register thread for grid. Will try to register every 5000 ms.
info: --> GET /wd/hub/status {}
info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
info: <-- GET /wd/hub/status 200 15.886 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
info: --> POST /wd/hub/session {"desiredCapabilities":{"autoLaunch":false,"setCommandTimeout":"300","browserName":"iPhone5s","platformName":"iOS","deviceName":"AppleMobileDevice","platform":"MAC"}}
info: Client User-Agent string: Apache-HttpClient/4.3.4 (java 1.5)
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : setCommandTimeout, platform
info: [debug] App is an iOS bundle, will attempt to run as pre-existing
info: [debug] Creating new appium session b5b55dc6-0d08-45ab-af0b-bfd23fc10474
info: [debug] Appium session started with sessionId b5b55dc6-0d08-45ab-af0b-bfd23fc10474
info: <-- POST /wd/hub/session 303 10.169 ms - 74 
info: --> GET /wd/hub/session/b5b55dc6-0d08-45ab-af0b-bfd23fc10474 {}
info: [debug] Responding to client with success: {"status":0,"value":{"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"iPhone5s","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"warnings":{},"desired":{"autoLaunch":false,"setCommandTimeout":"300","browserName":"iPhone5s","platformName":"iOS","deviceName":"AppleMobileDevice","platform":"MAC"},"autoLaunch":false,"setCommandTimeout":"300","platformName":"iOS","deviceName":"AppleMobileDevice"},"sessionId":"b5b55dc6-0d08-45ab-af0b-bfd23fc10474"}
info: <-- GET /wd/hub/session/b5b55dc6-0d08-45ab-af0b-bfd23fc10474 200 2.215 ms - 543 {"status":0,"value":{"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"iPhone5s","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"warnings":{},"desired":{"autoLaunch":false,"setCommandTimeout":"300","browserName":"iPhone5s","platformName":"iOS","deviceName":"AppleMobileDevice","platform":"MAC"},"autoLaunch":false,"setCommandTimeout":"300","platformName":"iOS","deviceName":"AppleMobileDevice"},"sessionId":"b5b55dc6-0d08-45ab-af0b-bfd23fc10474"}
info: --> POST /wd/hub/session/b5b55dc6-0d08-45ab-af0b-bfd23fc10474/appium/device/app_installed {"bundleId":"com.myapp.app"}
info: <-- POST /wd/hub/session/b5b55dc6-0d08-45ab-af0b-bfd23fc10474/appium/device/app_installed 500 3.789 ms - 101 
TypeError: Cannot read property 'isInstalled' of undefined
    at [object Object].IOS.isAppInstalled (/usr/local/lib/node_modules/appium/lib/devices/ios/ios.js:1512:20)
    at exports.isAppInstalled (/usr/local/lib/node_modules/appium/lib/server/controller.js:113:16)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:82:5)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:82:5)
    at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:267:22
    at param (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:340:14)
    at param (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:356:14)
    at Function.proto.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:400:3)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:261:10)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:100:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at exports.sessionBeforeFilter (/usr/local/lib/node_modules/appium/lib/server/controller.js:56:5)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:82:5)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:110:13)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at Route.dispatch (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:82:5)
    at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:267:22
    at Function.proto.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:321:12)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:261:10)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:100:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
info: [debug] Appium successfully registered with the grid on 10.6.86.65:4444
info: --> GET /wd/hub/status {}
info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"},"isShuttingDown":false},"sessionId":"b5b55dc6-0d08-45ab-af0b-bfd23fc10474"}
info: <-- GET /wd/hub/status 200 1.650 ms - 179 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"},"isShuttingDown":false},"sessionId":"b5b55dc6-0d08-45ab-af0b-bfd23fc10474"}
^C

**Comment by shady333** [comment]
I'm also faced with the problem "isInstalled".
In ver. 1.3.7 - all is fibe.
Here's a full appium log (ver 1.4.13):

2016-01-11 15:41:25:151 - [36minfo[39m: Welcome to Appium v1.4.13 (REV c75d8adcb66a75818a542fe1891a34260c21f76a)
2016-01-11 15:41:25:155 - [36minfo[39m: Appium REST http interface listener started on 10.25.14.116:4723
2016-01-11 15:41:25:159 - [36minfo[39m: [debug] Non-default server args: {"app":"MY_APP.app","udid":"DEVICE_UDID","address":"10.25.14.116","sessionOverride":true,"logTimestamp":true,"platformName":"ios","nodeconfig":"/selenium/nodeAppiumiPad.json","defaultCommandTimeout":1000,"tmpDir":"/appiumtmp"}
2016-01-11 15:41:25:159 - [36minfo[39m: Console LogLevel: debug
2016-01-11 15:41:25:162 - [36minfo[39m: [debug] starting auto register thread for grid. Will try to register every 5000 ms.
2016-01-11 15:41:30:189 - [36minfo[39m: [debug] Appium successfully registered with the grid on 10.25.14.116:4444
2016-01-11 15:41:38:192 - [36minfo[39m: [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m [90m{"desiredCapabilities":{"platform":"MAC","platformName":"iOS","deviceName":"AppleMobileDevice","browserName":"iPad","setCommandTimeout":"180","autoLaunch":false}}[39m
2016-01-11 15:41:38:194 - [36minfo[39m: Client User-Agent string: Apache-HttpClient/4.3.4 (java 1.5)
2016-01-11 15:41:38:196 - [36minfo[39m: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : platform, setCommandTimeout
2016-01-11 15:41:38:199 - [36minfo[39m: [debug] Using local app from command line: MY_APP.app
2016-01-11 15:41:38:200 - [36minfo[39m: [debug] Creating new appium session 8a8b4a13-98e6-4bcf-8fbd-f178a854b7d7
2016-01-11 15:41:38:200 - [36minfo[39m: [debug] Appium session started with sessionId 8a8b4a13-98e6-4bcf-8fbd-f178a854b7d7
2016-01-11 15:41:38:204 - [36minfo[39m: [37m<-- POST /wd/hub/session [39m[36m303[39m[90m 11.908 ms - 74[39m [90m[39m
2016-01-11 15:41:38:238 - [36minfo[39m: [37m-->[39m [37mGET[39m [37m/wd/hub/session/8a8b4a13-98e6-4bcf-8fbd-f178a854b7d7[39m [90m{}[39m
2016-01-11 15:41:38:239 - [36minfo[39m: [debug] Responding to client with success: {"status":0,"value":{"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"iPad","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"warnings":{},"desired":{"platform":"MAC","platformName":"iOS","deviceName":"AppleMobileDevice","browserName":"iPad","setCommandTimeout":"180","autoLaunch":false},"platformName":"iOS","deviceName":"AppleMobileDevice","setCommandTimeout":"180","autoLaunch":false},"sessionId":"8a8b4a13-98e6-4bcf-8fbd-f178a854b7d7"}
2016-01-11 15:41:38:242 - [36minfo[39m: [37m<-- GET /wd/hub/session/8a8b4a13-98e6-4bcf-8fbd-f178a854b7d7 [39m[32m200[39m[90m 4.326 ms - 535[39m [90m{"status":0,"value":{"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"iPad","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"warnings":{},"desired":{"platform":"MAC","platformName":"iOS","deviceName":"AppleMobileDevice","browserName":"iPad","setCommandTimeout":"180","autoLaunch":false},"platformName":"iOS","deviceName":"AppleMobileDevice","setCommandTimeout":"180","autoLaunch":false},"sessionId":"8a8b4a13-98e6-4bcf-8fbd-f178a854b7d7"}[39m
2016-01-11 15:41:38:405 - [36minfo[39m: [37m-->[39m [37mPOST[39m [37m/wd/hub/session/8a8b4a13-98e6-4bcf-8fbd-f178a854b7d7/appium/device/app_installed[39m [90m{"bundleId":"BUNDLE_ID"}[39m
2016-01-11 15:41:38:410 - [36minfo[39m: [37m<-- POST /wd/hub/session/8a8b4a13-98e6-4bcf-8fbd-f178a854b7d7/appium/device/app_installed [39m[31m500[39m[90m 5.321 ms - 101[39m [90m[39m
TypeError: Cannot read property 'isInstalled' of undefined
    at [object Object].IOS.isAppInstalled (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js:1512:20)
    at exports.isAppInstalled (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/server/controller.js:113:16)
    at Layer.handle [as handle_request] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/layer.js:82:5)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/layer.js:82:5)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/index.js:267:22
    at param (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/index.js:340:14)
    at param (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/index.js:356:14)
    at Function.proto.process_params (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/index.js:400:3)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/index.js:261:10)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:100:14)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at exports.sessionBeforeFilter (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/server/controller.js:56:5)
    at Layer.handle [as handle_request] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/layer.js:82:5)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:110:13)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at Route.dispatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/layer.js:82:5)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/index.js:267:22
    at Function.proto.process_params (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/index.js:321:12)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/index.js:261:10)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:100:14)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:104:14)

**Comment by scottdixon** [comment]
@senevit4 @shady333 - please try with the latest Appium 1.5 beta `npm install -g appium@beta`

Let me know if the issue persists.

**Comment by shady333** [comment]
@scottdixon , Hi
Now I'm getting an error that not all capabilities are supported. I'm using selenium grid.
The log is:

2016-01-12 14:17:24:161 - [Appium] Welcome to Appium v1.5.0-beta11 (REV 5b4713a677bb0f195485a91b356ade895e8db1b7)
2016-01-12 14:17:24:163 - [Appium] Non-default server args:
2016-01-12 14:17:24:164 - [Appium]   address: '10.25.14.116'
2016-01-12 14:17:24:165 - [Appium]   sessionOverride: true
2016-01-12 14:17:24:165 - [Appium]   logTimestamp: true
2016-01-12 14:17:24:165 - [Appium]   nodeconfig: '/selenium/nodeAppiumiPad.json'
2016-01-12 14:17:24:166 - [Appium]   defaultCommandTimeout: 1000
2016-01-12 14:17:24:166 - [Appium]   tmpDir: '/appiumtmp'
2016-01-12 14:17:24:169 - [Appium]   platformName: 'ios'
2016-01-12 14:17:24:171 - [Appium]   app: 'PATH_TO_APP.app'
2016-01-12 14:17:24:172 - [Appium]   udid: 'c4a93d9d8819728a34c355bc8b6a46d988c7bdae'
2016-01-12 14:17:24:174 - [Appium] Deprecated server args:
2016-01-12 14:17:24:174 - [Appium]   --platform-name => --default-capabilities '{"platformName":"ios"}'
2016-01-12 14:17:24:175 - [Appium]   --app => --default-capabilities '{"app":"PATH_TO_APP.app"}'
2016-01-12 14:17:24:176 - [Appium]   -U,--udid => --default-capabilities '{"udid":"DEVICE_UDID"}'
2016-01-12 14:17:24:176 - [Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
2016-01-12 14:17:24:196 - [Appium]   platformName: 'ios'
2016-01-12 14:17:24:196 - [Appium]   app: 'PATH_TO_APP.app'
2016-01-12 14:17:24:196 - [Appium]   udid: 'DEVICE_UDID'
2016-01-12 14:17:24:243 - [debug] [Appium] Starting auto register thread for grid. Will try to register every 5000 ms.
2016-01-12 14:17:24:244 - [Appium] Appium REST http interface listener started on 10.25.14.116:4723
2016-01-12 14:17:29:269 - [debug] [Appium] Appium successfully registered with the grid on 10.25.14.116:4444
2016-01-12 14:17:37:658 - [HTTP] --> POST /wd/hub/session 
2016-01-12 14:17:37:681 - [MJSONWP] Calling AppiumDriver.createSession() with args: [{"platform":"MAC","platformName":"iOS","deviceName":"AppleMobileDevice","browserName":"iPad","setCommandTimeout":"180"},null,null,null]
2016-01-12 14:17:37:687 - [Appium] Creating new IosDriver session
2016-01-12 14:17:37:687 - [Appium] Capabilities:
2016-01-12 14:17:37:689 - [Appium]   platform: 'MAC'
2016-01-12 14:17:37:690 - [Appium]   platformName: 'iOS'
2016-01-12 14:17:37:690 - [Appium]   deviceName: 'AppleMobileDevice'
2016-01-12 14:17:37:690 - [Appium]   browserName: 'iPad'
2016-01-12 14:17:37:691 - [Appium]   setCommandTimeout: '180'
2016-01-12 14:17:37:691 - [Appium]   app: 'PATH_TO_APP.app'
2016-01-12 14:17:37:691 - [Appium]   udid: 'DEVICE_UDID'
2016-01-12 14:17:37:739 - [BaseDriver] SessionNotCreatedError: A new session could not be created. Details: The desiredCapabilities object was not valid for the following reason(s): browserName iPad is not included in the list.
    at IosDriver.validateDesiredCaps (lib/driver.js:120:25)
    at IosDriver.validateDesiredCaps (lib/driver.js:41:16)
    at IosDriver.callee$0$0$ (lib/commands/session.js:13:8)

**Comment by shady333** [comment]
according to issue in my previous post - I'm using "--tmp /appiumtmp" parameter while starting appium, looks like it not supported in version 1.5

**Comment by scottdixon** [comment]
@shady333 it looks like you're specifying an app and a browserName. You'll need to specify one or the other. If you choose to specify a browserName, you'll need to set the value to `Safari`.

**Comment by shady333** [comment]
@scottdixon I'm testing native application. should I leave browserName as empty string? Also I connecting appium node to seleniumgrid.

**Comment by scottdixon** [comment]
In that case you can omit browserName from your desired capabilities all together.

If you need a hand with Selenium Grid, you might find these docs useful: http://appium.io/slate/en/1.5/?ruby#selenium-grid
