### ISSUE TITLE
Failed to start an Appium session, err was: TypeError: undefined is not a function

### ISSUE THREAD

**Issue by SameenJavid** [appium/appium#5771]
Hi All, 
I just created a scrip to successfully run my application using appium. Script was run successfully once , I opened my script after a day and launched it and got following error
Could not determine iOS SDK version
error: Failed to start an Appium session, err was: TypeError: undefined is not a function

Below are detailed logs from appium

info: [debug] Using local app from command line: /Users/techlogix/Library/Developer/Xcode/DerivedData/xiQ-blzbmdoahbnifubfcrlokmnxcfkd/Build/Products/Debug-iphonesimulator/xiQ.app
info: [debug] Creating new appium session c79fa01b-ca6c-4de9-a666-2cbe47521485
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode version
info: [debug] Xcode version set to undefined
info: [debug] Setting iOS SDK Version
info: [debug] Cleaning up appium session
info: [debug] TypeError: undefined is not a function
    at getPathFromSymlink$ (lib/xcode.js:63:22)
    at tryCatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-xcode/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-xcode/node_modules/babel-runtime/regenerator/runtime.js:294:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-xcode/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-xcode/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at bound (domain.js:254:14)
    at GeneratorFunctionPrototype.runBound (domain.js:267:12)
    at run (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-xcode/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:89:39)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-xcode/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:100:28
    at process._tickDomainCallback (node.js:381:11)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: undefined is not a function)","origValue":"undefined is not a function"},"sessionId":null}
info: <-- POST /wd/hub/session 500 10.410 ms - 176 

error: Could not determine iOS SDK version
error: Failed to start an Appium session, err was: TypeError: undefined is not a function

Following is the exception from java code

Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: A new session could not be created. (Original error: undefined is not a function) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 2.79 seconds
Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:59:12'
System info: host: 'nerldap.lahore.techlogix.com', ip: '172.20.3.218', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.8.0_60'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:647)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:247)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:129)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:156)
	at tesssss.LoginxiQ.main(LoginxiQ.java:32)
Please help

**Comment by scottdixon** [comment]
Closing old issue. Please try a more recent version of Appium. Reopen if the issue persists.
