### ISSUE TITLE
[Android] Unable to parse manifest that has '<intent-filter android:autoVerify="true">'  under launcher activity

### ISSUE THREAD

**Issue by jpkrause** [appium/appium#5786]
Use of this attribute is described here: http://developer.android.com/training/app-links/index.html

Below is the appium log for the failing session:

```
2015-10-30 16:12:24:654 - info: [debug] Extracting package and launch activity from manifest.
2015-10-30 16:12:24:654 - info: [debug] executing cmd: /Users/jkrause/Library/Android/sdk/build-tools/23.0.2/aapt dump badging /Users/jkrause/github/android-automation/app/com.app-debug.apk
2015-10-30 16:12:24:667 - info: [debug] badging package: com.app
2015-10-30 16:12:24:667 - info: [debug] badging act: null
2015-10-30 16:12:26:166 - warn: Oct 30, 2015 4:12:26 PM brut.androlib.res.decoder.AXmlResourceParser getAttributeValue
WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=autoVerify, value=0xffffffff
brut.androlib.err.UndefinedResObject: resource spec: 0x010104ee
	at brut.androlib.res.data.ResPackage.getResSpec(ResPackage.java:59)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:58)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:54)
	at brut.androlib.res.decoder.ResAttrDecoder.decode(ResAttrDecoder.java:36)
	at brut.androlib.res.decoder.AXmlResourceParser.getAttributeValue(AXmlResourceParser.java:369)
	at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeValue(XmlPullParserDelegate.java:69)
	at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:267)
	at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)
	at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:83)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:141)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPullStreamDecoder.java:153)
	at brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecoder.java:131)
	at brut.androlib.res.AndrolibResources.decodeManifest(AndrolibResources.java:164)
	at io.appium.apktools.AndroidManifestActivityHelper.decodeManifestXML(AndroidManifestActivityHelper.java:27)
	at io.appium.apktools.Main.main(Main.java:33)


2015-10-30 16:12:26:167 - info: [debug] Cleaning up android objects
2015-10-30 16:12:26:167 - info: [debug] Cleaning up appium session
2015-10-30 16:12:26:168 - error: Failed to start an Appium session, err was: Error: Cannot parse launchActivity from manifest.null
2015-10-30 16:12:26:169 - info: [debug] Error: Cannot parse launchActivity from manifest.null
    at [object Object].<anonymous> (/Users/jkrause/automationFramework/.npm-packages/lib/node_modules/appium/lib/devices/android/android-common.js:693:21)
    at ChildProcess.exithandler (child_process.js:742:7)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
2015-10-30 16:12:26:169 - info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Cannot parse launchActivity from manifest.null)","origValue":"Cannot parse launchActivity from manifest.null"},"sessionId":null}
```

**Comment by hanbiao1987** [comment]
Solved? how to solve?

**Comment by scottdixon** [comment]
Please provide the test code you're using, in particular your desired caps.

**Comment by jpkrause** [comment]
Here's the desired capabilities
`2016-03-08 00:12:13:824 - info: --> POST /wd/hub/session {"desiredCapabilities":{"app":"/path/to/app","appPackage":"com.app","dontStopAppOnReset":true,"noSign":true,"appWaitActivity":".activities.search.SearchResultsActivity","deviceName":"android-phone-nexus6-version5.1.0-api22-res1440x2560-dpi480","appActivity":".activities.StartActivity","newCommandTimeout":2147482,"platformVersion":"5.1.0","browserName":"","unicodeKeyboard":true,"platformName":"Android","udid":"192.168.56.101:5555","resetKeyboard":true}}`

**Comment by scottdixon** [comment]
Looks like it's having a hard time parsing the manifest. `manifest.null`.

Can you please try Appium 1.5 @jpkrause ?

**Comment by jpkrause** [comment]
Yeah I hadn't checked this in a good while. It works fine on 1.5, had to add that back to the intent filter tag to try it out. Thanks for checking in on this @scottdixon

**Comment by scottdixon** [comment]
Good to know. Thanks for the update!
