### ISSUE TITLE
click and sendkeys function were not working in appium 1.4.13

### ISSUE THREAD

**Issue by ryan-cl** [appium/appium#5798]
###### Version information
Appium 1.4.13, IOS 4S 9.1, OS X 10.10.5, Xcode,7.1

###### Debug information
```js 
Error: invalid json

    at parse (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/body-parser/lib/types/json.js:79:15)

    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/body-parser/lib/read.js:102:18

    at done (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/body-parser/node_modules/raw-body/index.js:248:14)

    at IncomingMessage.onEnd (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/body-parser/node_modules/raw-body/index.js:294:7)

    at IncomingMessage.g (events.js:199:16)

    at IncomingMessage.emit (events.js:104:17)

    at _stream_readable.js:908:16

    at process._tickDomainCallback (node.js:381:11)

info: [debug] Socket data being routed.

info: [debug] Got result from instruments: {"status":0,"value":{"origin":{"x":16,"y":192},"size":{"width":288,"height":48}}}

info: <-- POST /tap 500 1.069 ms - 66

info: [debug] Responding to client with error: {"status":1,"value":{"message":"undefined status object"},"sessionId":"fd36b327-11d8-4f17-87ff-81521b8b4ba9"}

info: <-- POST /wd/hub/session/fd36b327-11d8-4f17-87ff-81521b8b4ba9/element/0/click 500 1048.807 ms - 109
```

**Comment by v0l0d** [comment]
I spent so many days with the same issue and finally I found the solution:
just reset Appium settings: Appium -> Reset Preferences

I see Appium uses wrong client or kind of that, but I failed to find it

**Comment by scottdixon** [comment]
Please use a more recent version of appium. Reopen + provide entire server log as a gist if the issue persists. Thanks!
