### ISSUE TITLE
Can't test app on saucelabs - multiple errors

### ISSUE THREAD

**Issue by TelmoNeves** [appium/appium#5803]
2015-11-06T09:39:00.319Z - info: Welcome to Appium v0.18.2 (REV 42bf11ab933185316a57ffa7f283f184ea4635b8)
2015-11-06T09:39:00.321Z - info: Appium REST http interface listener started on 0.0.0.0:4443
2015-11-06T09:39:00.324Z - info: socket.io started
2015-11-06T09:39:00.329Z - info: Non-default server args: {"app":"/tmp/tmp9m02A1/myapp.apk","udid":"emulator-5554","port":4443,"logTimestamp":true,"logNoColors":true,"merciful":true,"orientation":"portrait","selendroidPort":4725,"defaultCommandTimeout":0}
2015-11-06T09:39:00.367Z - debug: Appium request initiated at /wd/hub/session
2015-11-06T09:39:00.367Z - debug: Request received with params: {"desiredCapabilities":{"deviceName":"Google Nexus 7 HD Emulator","app-package":"com.sgiggle.production","webdriver.remote.quietExceptions":true,"proxy":{"proxyAutoconfigUrl":"http://127.0.0.1:19876/pac.js","proxyType":"PAC"},"platformVersion":"4.4","app-activity":"com.sgiggle.production.SplashScreen","platformName":"Android"}}
2015-11-06T09:39:00.368Z - warn: Converting cap proxy to string, since it was an object. This might be a user error. Original value was: {"proxyAutoconfigUrl":"http://127.0.0.1:19876/pac.js","proxyType":"PAC"}
2015-11-06T09:39:00.371Z - info: Using local app from command line: /tmp/tmp9m02A1/myapp.apk
2015-11-06T09:39:00.373Z - info: Creating new appium session 6bc5f174-aac8-4047-b1ef-66b6b530695f
2015-11-06T09:39:00.374Z - info: Starting android appium
2015-11-06T09:39:00.374Z - debug: Using fast reset? true
2015-11-06T09:39:00.376Z - info: Preparing device for session
2015-11-06T09:39:00.376Z - info: Checking whether app is actually present
2015-11-06T09:39:00.377Z - info: Checking whether adb is present
2015-11-06T09:39:00.378Z - info: [ADB] Using adb from /home/chef/android-sdk-linux/platform-tools/adb
2015-11-06T09:39:00.378Z - info: Trying to find a connected android device
2015-11-06T09:39:00.378Z - info: [ADB] Getting connected devices...
2015-11-06T09:39:00.379Z - debug: executing: "/home/chef/android-sdk-linux/platform-tools/adb" devices
2015-11-06T09:39:00.391Z - info: [ADB] 1 device(s) connected
2015-11-06T09:39:00.391Z - info: Setting device id to emulator-5554
2015-11-06T09:39:00.391Z - info: [ADB] Waiting for device to be ready and to respond to shell commands (timeout = 5)
2015-11-06T09:39:00.392Z - debug: executing: "/home/chef/android-sdk-linux/platform-tools/adb" -s emulator-5554 wait-for-device
2015-11-06T09:39:00.399Z - debug: executing: "/home/chef/android-sdk-linux/platform-tools/adb" -s emulator-5554 shell "echo 'ready'"
2015-11-06T09:39:00.458Z - info: Starting logcat capture
2015-11-06T09:39:00.542Z - info: Getting device API level
2015-11-06T09:39:00.542Z - debug: executing: "/home/chef/android-sdk-linux/platform-tools/adb" -s emulator-5554 shell "getprop ro.build.version.sdk"
2015-11-06T09:39:00.593Z - info: Device is at API Level 19
2015-11-06T09:39:00.593Z - debug: java -jar "/home/chef/appium/lib/devices/android/helpers/strings_from_apk.jar" "/tmp/tmp9m02A1/myapp.apk" "/tmp/com.sgiggle.production"
2015-11-06T09:39:00.807Z - warn: Error getting strings.xml from apk
2015-11-06T09:39:00.807Z - debug: Exception in thread "main" brut.androlib.AndrolibException: Could not load resources.arsc from file: /tmp/tmp9m02A1/myapp.apk
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:544)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:76)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:68)
	at strings.StringsXML.run(StringsXML.java:84)
	at strings.StringsXML.main(StringsXML.java:151)
Caused by: brut.directory.DirectoryException: java.util.zip.ZipException: error in opening zip file
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:55)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:38)
	at brut.androlib.res.util.ExtFile.getDirectory(ExtFile.java:55)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:540)
	... 4 more
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:132)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:53)
	... 7 more

2015-11-06T09:39:00.807Z - debug: executing: "/home/chef/android-sdk-linux/platform-tools/adb" -s emulator-5554 shell "echo '{}' > /data/local/tmp/strings.json"
2015-11-06T09:39:00.855Z - info: Checking whether aapt is present
2015-11-06T09:39:00.856Z - info: [ADB] Using aapt from /home/chef/android-sdk-linux/build-tools/19.0.1/aapt
2015-11-06T09:39:00.856Z - debug: processFromManifest: "/home/chef/android-sdk-linux/build-tools/19.0.1/aapt" dump xmltree "/tmp/tmp9m02A1/myapp.apk" AndroidManifest.xml
2015-11-06T09:39:00.864Z - warn: ERROR: dump failed because resource AndroidManifest.xml found

2015-11-06T09:39:00.864Z - debug: Set app process to: ggle.production
2015-11-06T09:39:00.864Z - debug: Not uninstalling app since server not started with --full-reset
2015-11-06T09:39:00.865Z - debug: Checking app cert for /tmp/tmp9m02A1/myapp.apk: java -jar "/home/chef/appium/lib/devices/android/helpers/verify.jar" "/tmp/tmp9m02A1/myapp.apk"
2015-11-06T09:39:00.996Z - debug: App not signed with debug cert.
2015-11-06T09:39:00.997Z - debug: Resigning apk with: java -jar "/home/chef/appium/lib/devices/android/helpers/sign.jar" "/tmp/tmp9m02A1/myapp.apk" --override
2015-11-06T09:39:01.169Z - info: Stopping logcat capture
2015-11-06T09:39:01.171Z - debug: Logcat terminated with code null, signal SIGTERM
2015-11-06T09:39:01.172Z - info: Sent shutdown command, waiting for UiAutomator to stop...
2015-11-06T09:39:08.176Z - warn: UiAutomator did not shut down fast enough, calling it gone
2015-11-06T09:39:08.176Z - info: Cleaning up android objects
2015-11-06T09:39:08.176Z - info: Cleaning up appium session
2015-11-06T09:39:08.176Z - error: Failed to start an Appium session, err was: Error: Command failed: /bin/sh -c java -jar "/home/chef/appium/lib/devices/android/helpers/sign.jar" "/tmp/tmp9m02A1/myapp.apk" --override
java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:132)
	at java.util.jar.JarFile.<init>(JarFile.java:153)
	at java.util.jar.JarFile.<init>(JarFile.java:132)
	at s.Sign.sign(Sign.java:441)
	at s.Sign.main(Sign.java:532)

2015-11-06T09:39:08.179Z - info: Error: Command failed: /bin/sh -c java -jar "/home/chef/appium/lib/devices/android/helpers/sign.jar" "/tmp/tmp9m02A1/myapp.apk" --override
java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:132)
	at java.util.jar.JarFile.<init>(JarFile.java:153)
	at java.util.jar.JarFile.<init>(JarFile.java:132)
	at s.Sign.sign(Sign.java:441)
	at s.Sign.main(Sign.java:532)

    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
2015-11-06T09:39:08.179Z - info: Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Command failed: /bin/sh -c java -jar \"/home/chef/appium/lib/devices/android/helpers/sign.jar\" \"/tmp/tmp9m02A1/myapp.apk\" --override\njava.util.zip.ZipException: error in opening zip file\n\tat java.util.zip.ZipFile.open(Native Method)\n\tat java.util.zip.ZipFile.<init>(ZipFile.java:132)\n\tat java.util.jar.JarFile.<init>(JarFile.java:153)\n\tat java.util.jar.JarFile.<init>(JarFile.java:132)\n\tat s.Sign.sign(Sign.java:441)\n\tat s.Sign.main(Sign.java:532)\n)","killed":false,"code":1,"signal":null,"cmd":"/bin/sh -c java -jar \"/home/chef/appium/lib/devices/android/helpers/sign.jar\" \"/tmp/tmp9m02A1/myapp.apk\" --override","origValue":"Command failed: /bin/sh -c java -jar \"/home/chef/appium/lib/devices/android/helpers/sign.jar\" \"/tmp/tmp9m02A1/myapp.apk\" --override\njava.util.zip.ZipException: error in opening zip file\n\tat java.util.zip.ZipFile.open(Native Method)\n\tat java.util.zip.ZipFile.<init>(ZipFile.java:132)\n\tat java.util.jar.JarFile.<init>(JarFile.java:153)\n\tat java.util.jar.JarFile.<init>(JarFile.java:132)\n\tat s.Sign.sign(Sign.java:441)\n\tat s.Sign.main(Sign.java:532)\n"},"sessionId":null}
POST /wd/hub/session 500 7825ms - 1.24kb

**Comment by scottdixon** [comment]
Closing old issue. Please try a more modern version of Appium. Reopen if the issue persists.
