### ISSUE TITLE
Instruments crashed on start up for appium  v1.4.13

### ISSUE THREAD

**Issue by niranjala** [appium/appium#5872]
I have seen this issue open for lower appium versions. But I am seeing this for appium 1.4.13. My configurations are
osx 10.10.4
xcode 7
ios 8.1 ipad mini

 I am not able to run any test with the above config.  But when I try with ios 8.4 the error occures randomly.
Any help on this issue will be much appreciated

Here is the stack trace

org.openqa.selenium.WebDriverException: Instruments died while responding to command, please check appium logs (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 726 milliseconds
Build info: version: '2.47.1', revision: 'unknown', time: '2015-07-30 11:02:44'
System info: host: 'N/A', ip: 'N/A', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.4', java.version: '1.7.0_79'
*** Element info: {Using=-ios uiautomation, value=UIATarget.localTarget().frontMostApp().mainWindow().tableViews().firstWithPredicate("ANY cells.name == 'Sign In to ESPN Account'").cells()["Sign In to ESPN Account"]}
Session ID: eeff622b-6406-4d2e-a904-0a876d920a89
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{waitForAppScript=$.delay(1000); true;, platform=MAC, app=com.espn.enterprise.sportscenterqa, javascriptEnabled=true, screenshotWaitTimeout=5, browserName=iOS, networkConnectionEnabled=false, desired={waitForAppScript=$.delay(1000); true;, newCommandTimeout=30, autoAcceptAlerts=false, platform=MAC, app=com.espn.enterprise.sportscenterqa, screenshotWaitTimeout=5, deviceName=, platformName=iOS, browserName=iOS, takesScreenshot=true, version=Tablet}, locationContextEnabled=false, version=Tablet, newCommandTimeout=30, autoAcceptAlerts=false, databaseEnabled=false, deviceName=, platformName=iOS, webStorageEnabled=false, warnings={}, takesScreenshot=true}]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:595)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:348)
	at io.appium.java_client.ios.IOSDriver.findElementByIosUIAutomation(IOSDriver.java:148)
	at io.appium.java_client.MobileBy$ByIosUIAutomation.findElement(MobileBy.java:73)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:340)
	at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:52)
	at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.findElement(IOSDriver.java:1)
	at com.espn.test.sportscenter.common.util.Interact$1.apply(Interact.java:237)
	at com.espn.test.sportscenter.common.util.Interact$1.apply(Interact.java:1)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:209)
	at com.espn.test.sportscenter.common.util.Interact.waitForPresent(Interact.java:234)
	at com.espn.test.sportscenter.uitests.actionchains.LoginChain.splashNotPresent(LoginChain.java:110)
	at com.espn.test.sportscenter.uitests.actionchains.RegisterChain.registerNewUser(RegisterChain.java:37)
	at com.espn.test.sportscenter.uitests.tests.AlertsTests.settingGameAlertsiOS(AlertsTests.java:135)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)

Here is the appium console for the portion when the error occurs

info: [debug] Sending command to instruments: au.getElementByUIAutomation('UIATarget.localTarget().frontMostApp().mainWindow().tableViews().firstWithPredicate("some selector")

info: [debug] [INST] Instruments Trace Complete (Duration : 51.949177s; Output : /tmp/appium-instruments/instrumentscli0.trace)

info: [debug] [INSTSERVER] Instruments exited with code 0

info: [debug] Cleaning up after instruments exit
info: [debug] Instruments exited unexpectedly
info: [debug] Shutting down command proxy and ignoring any errors
info: [debug] Closing socket server.
info: [debug] Instruments socket server was closed
info: [debug] Stopping iOS log capture
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killing any other simulator daemons
info: [debug] Killall iOS Simulator
info: [debug] On a real device; cannot clean device state
info: [debug] We were in the middle of processing a command when instruments died; responding with a generic error
info: [debug] Cleaning up appium session
info: [debug] Condition unmet after 720ms. Timing out.
info: [debug] Responding to client with error: {"status":13,"value":{"message":"Instruments died while responding to command, please check appium logs","name":"UnknownError","origValue":"Instruments died while responding to command, please check appium logs"},"sessionId":null}
info: <-- POST /wd/hub/session/eeff622b-6406-4d2e-a904-0a876d920a89/element 500 721.171 ms - 230 
info: --> GET /wd/hub/session/eeff622b-6406-4d2e-a904-0a876d920a89/screenshot {}
info: <-- GET /wd/hub/session/eeff622b-6406-4d2e-a904-0a876d920a89/screenshot 404 0.884 ms - 40 
info: --> DELETE /wd/hub/session/eeff622b-6406-4d2e-a904-0a876d920a89 {}
info: <-- DELETE /wd/hub/session/eeff622b-6406-4d2e-a904-0a876d920a89 404 0.712 ms - 40

**Comment by SrinivasanTarget** [comment]
Please try a latest version of appium and raise a new issue along with logs incase if you hit the same.

**Comment by SrinivasanTarget** [comment]
@triager please close
