### ISSUE TITLE
[Android] cannot automate actions on home screen

### ISSUE THREAD

**Issue by nabeel-ibrahim** [appium/appium#5877]
I am trying to automate adding a widget on the home screen, but I am unable to do so. I tried setting the autoLaunch cap to false but any command I run such as driver.findElement() I get the following exception:
```error: Unhandled error: TypeError: Cannot read property 'sendAction' of null
    at [object Object].<anonymous> (/Users/nibrahim/node_modules/appium/lib/devices/android/android.js:504:23)
    at Immediate.q.process [as _onImmediate] (/Users/nibrahim/node_modules/appium/node_modules/async/lib/async.js:806:21)```

**Comment by scottdixon** [comment]
Please try Appium 1.5. Post a new issue with the entire logs as a gist if you have a problem.
