### ISSUE TITLE
Crash when calling pushFile after closeApp

### ISSUE THREAD

**Issue by al007** [appium/appium#5878]
Appium will rise a TypeError exception if one call pushFile(...) method after calling closeApp()

```
driver.closeApp();
driver.pushFile("/sdcard/servers.txt", "string".getBytes());
```

```
> TypeError: Cannot call method 'push' of null
>     at [object Object].async.series.cb.status (C:\Program Files\Appium\node_modules\appium\lib\devices\android\android-controller.js:508:16)
>     at C:\Program Files\Appium\node_modules\appium\node_modules\async\lib\async.js:607:21
>     at C:\Program Files\Appium\node_modules\appium\node_modules\async\lib\async.js:246:17
>     at iterate (C:\Program Files\Appium\node_modules\appium\node_modules\async\lib\async.js:146:13)
>     at async.eachSeries (C:\Program Files\Appium\node_modules\appium\node_modules\async\lib\async.js:162:9)
>     at _asyncMap (C:\Program Files\Appium\node_modules\appium\node_modules\async\lib\async.js:245:13)
>     at Object.mapSeries (C:\Program Files\Appium\node_modules\appium\node_modules\async\lib\async.js:228:23)
>     at Object.async.series (C:\Program Files\Appium\node_modules\appium\node_modules\async\lib\async.js:605:19)
>     at [object Object].androidController.pushFile (C:\Program Files\Appium\node_modules\appium\lib\devices\android\android-controller.js:500:9)
>     at exports.pushFile (C:\Program Files\Appium\node_modules\appium\lib\server\controller.js:1143:16)
>     at Layer.handle [as handle_request] (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\layer.js:82:5)
>     at next (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\route.js:110:13)
>     at Route.dispatch (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\route.js:91:3)
>     at Layer.handle [as handle_request] (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\layer.js:82:5)
>     at C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\index.js:267:22
>     at param (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\index.js:340:14)
>     at param (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\index.js:356:14)
>     at Function.proto.process_params (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\index.js:400:3)
>     at next (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\index.js:261:10)
>     at next (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\route.js:100:14)
>     at next (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
>     at next (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
>     at next (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
>     at next (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
>     at next (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
>     at next (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
>     at next (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
>     at next (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
>     at next (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
>     at next (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
>     at next (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
>     at next (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
>     at next (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
>     at next (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
>     at next (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
>     at next (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
>     at next (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
>     at next (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
>     at next (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
>     at next (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
>     at next (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
>     at next (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
>     at next (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
>     at next (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
>     at exports.sessionBeforeFilter (C:\Program Files\Appium\node_modules\appium\lib\server\controller.js:56:5)
>     at Layer.handle [as handle_request] (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\layer.js:82:5)
>     at next (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\route.js:110:13)
>     at next (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
>     at Route.dispatch (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\route.js:91:3)
>     at Layer.handle [as handle_request] (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\layer.js:82:5)
>     at C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\index.js:267:22
>     at Function.proto.process_params (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\index.js:321:12)
```

**Comment by scottdixon** [comment]
If you're still experiencing a problem, please try with 1.5. Post server logs if you get stuck. Thanks
