### ISSUE TITLE
 Error. For whatever reason, could not click the 'launch safari' button of SafariLauncher

### ISSUE THREAD

**Issue by kolobok01** [appium/appium#5891]
Hello Team 

ENV:
OSX: 10.10.5 
Xcode: Version 7.0
iPad (4th generation Model A1458) -> IOS: 9.1
iPhone: s4 -> IOS: 7.1 

Just trying to get safari test out on real device. Below are my configs.

pulled Appium v1.4.16 (REV ae6877eff263066b26328d457bd285c0cc62430d)

```
$ ./reset.sh --ios --real-safari --verbose (Success)

$ node lib/server/main.js --command-timeout "7200" --debug-log-spacing --robot-address "192.168.43.215" --robot-port "4723" --platform-version "9.0" --platform-name "iOS"  --udid "2078038503984503824509832408" --show-ios-log --device-name "My IPAD" --launch-timeout "90000" --safari
```

Everything is tip top up SafariLauncher is getting deployed and launched.

Simple client:

``` java
@Test
    public void googleTest() throws IOException, InterruptedException {
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("platformName", "iOS");
        capabilities.setCapability("deviceName", "My IPAD");
        capabilities.setCapability(MobileCapabilityType.SUPPORTS_JAVASCRIPT, "true");
        capabilities.setCapability(MobileCapabilityType.SUPPORTS_NETWORK_CONNECTION, "true");
        capabilities.setCapability("newCommandTimeout", 60);
        capabilities.setCapability("udid", "2078038503984503824509832408");
        final AppiumDriver driver = new IOSDriver<WebElement>(new URL("http://192.168.43.215:4723/wd/hub"),
                capabilities);
        Path path = FileSystems.getDefault().getPath("error");
        FileUtils.writeStringToFile(new File(path.toFile(), "ios.html"), driver.getPageSource());
        driver.manage().timeouts().implicitlyWait(45, TimeUnit.SECONDS);
        synchronized (driver) {
            try {
                driver.get("https://www.google.com");
                driver.wait(15000);
            }catch (Exception e){
                e.printStackTrace();
            } finally {
                driver.quit();
            }
            }
    }
```

   Just wanted to get some insight of what direction should i look at. It looks like apium/lib/devices/ios/safari.js: throws but why ? Is there a error in my client code request ?

``` javascript
info: [debug] [INST] 2015-12-01 23:29:24 +0000 Debug: evaluation finished
info: [debug] [INST] 2015-12-01 23:29:24 +0000 Debug: responding with:bled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0","x":0,"y":-0.5,"width":768,"height":1024},">":[{"UIAStaticText":{"@":{"name":"Safari Launcher","label":"Safari Launcher","value":"Safari Launcher","dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/0","x":192,"y":9.5,"width":768,"height":50},">":[]}},{"UIAButton":{"@":{"name":"launch safari","label":"launch safari","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/1","x":284,"y":481.5,"width":200,"height":60},">":[]}},{"UIAStaticText":{"@":{"name":"   url: http://www.apple.com","label":"   url: http://www.apple.com","value":"   url: http://www.apple.com","dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/2","x":0,"y":973.5,"width":768,"height":50},">":[]}}]}},{"UIAWindow":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/1","x":0,"y":-0.5,"width":768,"height":1024},">":[{"UIAStatusBar":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/1/0","x":0,"y":-0.5,"width":768,"height":20},">":[{"UIAElement":{"@":{"name":"iPad","label":"iPad","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":"Swipe down with three fingers to reveal the notification center., Swipe up with three fingers to reveal the control center, Double-tap to scroll to top","path":"/0/1/0/0","x":6,"y":-0.5,"width":25,"height":20},">":[]}},{"UIAElement":{"@":{"name":"3 of 3 Wi-Fi bars","label":"3 of 3 Wi-Fi bars","value":"SSID","dom":null,"enabled":true,"valid":true,"visible":true,"hint":"Swipe down with three fingers to reveal the notification center., Swipe up with three fingers to reveal the control center, Double-tap to scroll to top","path":"/0/1/0/1","x":36,"y":-0.5,"width":13,"height":20},">":[]}},{"UIAElement":{"@":{"name":"6:29 PM","label":"6:29 PM","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":"Swipe down with three fingers to reveal the notification center., Swipe up with three fingers to reveal the control center, Double-tap to scroll to top","path":"/0/1/0/2","x":361,"y":-0.5,"width":50,"height":20},">":[]}},{"UIAElement":{"@":{"name":"100% battery power, On AC Power","label":"100% battery power, On AC Power","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":"Swipe down with three fingers to reveal the notification center., Swipe up with three fingers to reveal the control center, Double-tap to scroll to top","path":"/0/1/0/3","x":696,"y":-0.5,"width":67,"height":20},">":[]}}]}}]}}]}}}
info: [debug] Socket data received (2978 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":{"UIAApplication":{"@":{"name":"SafariLauncher","label":"SafariLauncher","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0","x":0,"y":0,"width":768,"height":1024},">":[{"UIAWindow":{"@":{"name":null,"label":null,"value":null,"dom":null,"ena
info: [debug] On Safari Launcher. Tapping button to launch Safari
info: [debug] Waiting up to 0ms for condition
info: [debug] Pushing command to appium work queue: "au.getElementByAccessibilityId('launch safari')"
info: [debug] Sending command to instruments: au.getElementByAccessibilityId('launch safari')
info: [debug] [INST] 2015-12-01 23:29:24 +0000 Debug: Running system command #2: /Applications/Appium.app/Contents/Resources/node/bin/node /Users/admin/repos/appium/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":{"UIAApplication":{"@":{"name":"SafariLauncher","label":"SafariLauncher","value":null,"dom":null,"enabled":tru...
info: [debug] [INST] 2015-12-01 23:29:25 +0000 Debug: Got new command 2 from instruments: au.getElementByAccessibilityId('launch safari')
info: [debug] [INST] 2015-12-01 23:29:25 +0000 Debug: evaluating au.getElementByAccessibilityId('launch safari')
info: [debug] [INST] 2015-12-01 23:29:25 +0000 Debug: evaluation finished
info: [debug] [INST] 2015-12-01 23:29:25 +0000 Debug: Lookup returned [object UIAButton] with the name "launch safari" (id: 0).
info: [debug] [INST] 2015-12-01 23:29:25 +0000 Debug: responding with:
info: [debug] [INST] 2015-12-01 23:29:25 +0000 Debug: Running system command #3: /Applications/Appium.app/Contents/Resources/node/bin/node /Users/admin/repos/appium/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":{"ELEMENT":"0"}}...
info: [debug] Socket data received (38 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":{"ELEMENT":"0"}}
info: [debug] Pushing command to appium work queue: "au.getElement('0').rect()"
info: [debug] Sending command to instruments: au.getElement('0').rect()
info: [debug] [INST] 2015-12-01 23:29:26 +0000 Debug: Got new command 3 from instruments: au.getElement('0').rect()
info: [debug] [INST] 2015-12-01 23:29:26 +0000 Debug: evaluating au.getElement('0').rect()
info: [debug] [INST] 2015-12-01 23:29:26 +0000 Debug: evaluation finished
info: [debug] [INST] 2015-12-01 23:29:26 +0000 Debug: responding with:
info: [debug] [INST] 2015-12-01 23:29:26 +0000 Debug: Running system command #4: /Applications/Appium.app/Contents/Resources/node/bin/node /Users/admin/repos/appium/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":{"origin":{"x":284,"y":481.5},"size":{"width":200,"height":60}}}...
info: [debug] Socket data received (86 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":{"origin":{"x":284,"y":481.5},"size":{"width":200,"height":60}}}
info: <-- POST /tap 500 10.523 ms - 66 
error: Error. For whatever reason, could not click the 'launch safari' button of SafariLauncher
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: Error. For whatever reason, could not click the 'launch safari' button of SafariLauncher
info: [debug] Error: Error. For whatever reason, could not click the 'launch safari' button of SafariLauncher
    at [object Object].<anonymous> (/Users/admin/repos/appium/appium/lib/devices/ios/safari.js:80:19)
    at Request.self.callback (/Users/admin/repos/appium/appium/node_modules/request/request.js:344:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/Users/admin/repos/appium/appium/node_modules/request/request.js:1239:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/Users/admin/repos/appium/appium/node_modules/request/request.js:1187:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickDomainCallback (node.js:381:11)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Error. For whatever reason, could not click the 'launch safari' button of SafariLauncher)","origValue":"Error. For whatever reason, could not click the 'launch safari' button of SafariLauncher"},"sessionId":null}
info: <-- POST /wd/hub/session 500 17252.302 ms - 298 
Error: invalid json
    at parse (/Users/admin/repos/appium/appium/node_modules/body-parser/lib/types/json.js:79:15)
    at /Users/admin/repos/appium/appium/node_modules/body-parser/lib/read.js:102:18
    at done (/Users/admin/repos/appium/appium/node_modules/body-parser/node_modules/raw-body/index.js:248:14)
    at IncomingMessage.onEnd (/Users/admin/repos/appium/appium/node_modules/body-parser/node_modules/raw-body/index.js:294:7)
    at IncomingMessage.g (events.js:199:16)
    at IncomingMessage.emit (events.js:104:17)
    at _stream_readable.js:908:16
    at process._tickDomainCallback (node.js:381:11
```

Now the same test case works with simulator.
I have tested against 2 different real 

Note: It enters click method: 
https://github.com/appium/appium/blob/88e67ce987d78ce44de252219e07dc176a3511c2/lib/devices/ios/safari.js#L75 

is the any settings that would effect click ? 
maybe tap action will work ?

**Comment by kolobok01** [comment]
Tested out with 8.4 as well as 9.2 same repeatable behavior.
Tried with different versions of xcode 6.1, 6.4, 7.0, 7.1.1, 7.2

**Comment by kolobok01** [comment]
no responce ?

**Comment by scottdixon** [comment]
@kolobok01 Please try with Appium 1.5

**Comment by rkavalap** [comment]
Closing due to inactivity
