### ISSUE TITLE
Apparantly Have Issues Working with Nexus 5 with Android Marshmallow 6.0

### ISSUE THREAD

**Issue by mabdurrahman** [appium/appium#5894]
Actually I've been using Appium against my LG Nexus 5 device for a long time, and It were working very fine, But now, I really face a weird problem, and I don't remember any major changes on my device except upgrading to Marshmallow and working with Caffeine app to keep the device awake while debugging through USB... the problem happens nearly 90% of the times Appium tries to deploy/start the testing application on the device... sometimes it works fine without any problems...

I already start Appium from command line before starting my test suite, and also I can see the problem while starting Appium from Inspector with "Prelaunch Application" option activated without actually starting a testing suite...

It basically stuck after printing those logs: 

```
info: [debug] Waking up device if it's not alive
info: [debug] Pushing command to appium work queue: ["wake",{}]
```

After waiting for a minute or so, it prints this:

```
info: [debug] [BOOTSTRAP] [debug] Emitting system alert message
info: [debug] Emitting alert message...
```

If it's working fine I should expected those instead:

```
info: [debug] [BOOTSTRAP] [debug] Client connected
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"wake","params":{}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: wake
```

If I started Appium from the Inspector, It then throws this exception and closes the session:

```
error: uncaughtException: Cannot read property 'sockets' of null date=Tue Dec 01 2015 19:36:45 GMT+0200 (EET), pid=30951, uid=501, gid=20, cwd=/Applications/Appium.app/Contents/Resources/node_modules/appium, execPath=/Applications/Appium.app/Contents/Resources/node/bin/node, version=v0.12.7, argv=[/Applications/Appium.app/Contents/Resources/node/bin/node, /Applications/Appium.app/Contents/Resources/node_modules/appium/lib/server/main.js, --command-timeout, 7200, --pre-launch, --debug-log-spacing, --automation-name, Appium, --platform-name, Android, --platform-version, 4.4, --app, /Users/mabdurrahman/TestHybridApp.apk, --device-name, 069a15a70b301e8a], rss=135897088, heapTotal=112283136, heapUsed=82491120, loadavg=[1.5185546875, 1.51611328125, 1.57373046875], uptime=864558, trace=[column=25, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/android/uiautomator.js, function=, line=195, method=null, native=false, column=9, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/underscore/underscore.js, function=Function._.each._.forEach, line=153, method=_.each._.forEach, native=false, column=5, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/android/uiautomator.js, function=[object Object].UiAutomator.handleBootstrapOutput, line=185, method=UiAutomator.handleBootstrapOutput, native=false, column=8, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/android/uiautomator.js, function=[object Object].UiAutomator.outputStreamHandler, line=174, method=UiAutomator.outputStreamHandler, native=false, column=17, file=events.js, function=Socket.emit, line=107, method=emit, native=false, column=16, file=_stream_readable.js, function=readableAddChunk, line=163, method=null, native=false, column=10, file=_stream_readable.js, function=Socket.Readable.push, line=126, method=Readable.push, native=false, column=20, file=net.js, function=Pipe.onread, line=538, method=onread, native=false], stack=[TypeError: Cannot read property 'sockets' of null,     at [object Object].<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/android/uiautomator.js:195:25),     at Function._.each._.forEach (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/underscore/underscore.js:153:9),     at [object Object].UiAutomator.handleBootstrapOutput (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/android/uiautomator.js:185:5),     at [object Object].UiAutomator.outputStreamHandler (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/android/uiautomator.js:174:8),     at Socket.emit (events.js:107:17),     at readableAddChunk (_stream_readable.js:163:16),     at Socket.Readable.push (_stream_readable.js:126:10),     at Pipe.onread (net.js:538:20)]
```

Here's the complete Log captured from Inspector:

```
Launching Appium with command: '/Applications/Appium.app/Contents/Resources/node/bin/node' lib/server/main.js --command-timeout "7200" --pre-launch --debug-log-spacing --automation-name "Appium" --platform-name "Android" --platform-version "4.4" --app "/Users/mabdurrahman/TestHybridApp.apk" --device-name "069a15a70b301e8a"

info: [debug] Starting Appium in pre-launch mode

info: Pre-launching app
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: [debug] No appActivity desired capability or server param. Parsing from apk.
info: [debug] No appPackage desired capability or server param. Parsing from apk.
info: [debug] Using local app from command line: /Users/mabdurrahman/TestHybridApp.apk

info: [debug] Creating new appium session 4f0e89ea-f1c0-4efc-8919-ce1f43d69fa2
info: Starting android appium
info: [debug] Getting Java version

info: Java version is: 1.7.0_71

info: [debug] Checking whether adb is present

info: [debug] Using adb from /Users/mabdurrahman/Sources/Developing/Android/SDK/android-sdk-macosx/platform-tools/adb
info: [debug] Parsing package and activity from app manifest
info: [debug] Checking whether aapt is present
info: [debug] Using aapt from /Users/mabdurrahman/Sources/Developing/Android/SDK/android-sdk-macosx/build-tools/23.0.1/aapt
info: [debug] Extracting package and launch activity from manifest.
info: [debug] executing cmd: /Users/mabdurrahman/Sources/Developing/Android/SDK/android-sdk-macosx/build-tools/23.0.1/aapt dump badging /Users/mabdurrahman/TestHybridApp.apk

info: [debug] badging package: com.test.app

info: [debug] badging act: com.test.app.MainActivity
info: [debug] Parsed package and activity are: com.test.app/com.test.app.MainActivity
info: [debug] Using fast reset? true
info: [debug] Preparing device for session
info: [debug] Checking whether app is actually present

info: Retrieving device
info: [debug] Trying to find a connected android device
info: [debug] Getting connected devices...
info: [debug] executing cmd: /Users/mabdurrahman/Sources/Developing/Android/SDK/android-sdk-macosx/platform-tools/adb devices

info: [debug] 1 device(s) connected

info: Found device 069a15a70b301e8a
info: [debug] Setting device id to 069a15a70b301e8a
info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)

info: [debug] executing cmd: /Users/mabdurrahman/Sources/Developing/Android/SDK/android-sdk-macosx/platform-tools/adb -s 069a15a70b301e8a wait-for-device

info: [debug] executing cmd: /Users/mabdurrahman/Sources/Developing/Android/SDK/android-sdk-macosx/platform-tools/adb -s 069a15a70b301e8a shell "echo 'ready'"

info: [debug] Starting logcat capture

info: [debug] Getting device API level

info: [debug] executing cmd: /Users/mabdurrahman/Sources/Developing/Android/SDK/android-sdk-macosx/platform-tools/adb -s 069a15a70b301e8a shell "getprop ro.build.version.sdk"

info: [debug] Device is at API Level 23

info: Device API level is: 23
info: [debug] Extracting strings for language: default

info: [debug] executing cmd: /Users/mabdurrahman/Sources/Developing/Android/SDK/android-sdk-macosx/platform-tools/adb -s 069a15a70b301e8a shell "getprop persist.sys.language"

info: [debug] Current device persist.sys.language: 

info: [debug] java -jar "/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-adb/jars/appium_apk_tools.jar" "stringsFromApk" "/Users/mabdurrahman/TestHybridApp.apk" "/tmp/com.test.app" 

info: [debug] Reading strings from converted strings.json

info: [debug] Setting language to default
info: [debug] executing cmd: /Users/mabdurrahman/Sources/Developing/Android/SDK/android-sdk-macosx/platform-tools/adb -s 069a15a70b301e8a push "/tmp/com.test.app/strings.json" /data/local/tmp

info: [debug] Checking whether aapt is present

info: [debug] Using aapt from /Users/mabdurrahman/Sources/Developing/Android/SDK/android-sdk-macosx/build-tools/23.0.1/aapt
info: [debug] Retrieving process from manifest.

info: [debug] executing cmd: /Users/mabdurrahman/Sources/Developing/Android/SDK/android-sdk-macosx/build-tools/23.0.1/aapt dump xmltree /Users/mabdurrahman/TestHybridApp.apk AndroidManifest.xml
info: [debug] Set app process to: com.test.app
info: [debug] Not uninstalling app since server not started with --full-reset
info: [debug] Checking app cert for /Users/mabdurrahman/TestHybridApp.apk.
info: [debug] executing cmd: java -jar /Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-adb/jars/verify.jar /Users/mabdurrahman/TestHybridApp.apk

info: [debug] App already signed.

info: [debug] Zip-aligning /Users/mabdurrahman/TestHybridApp.apk
info: [debug] Checking whether zipalign is present

info: [debug] Using zipalign from /Users/mabdurrahman/Sources/Developing/Android/SDK/android-sdk-macosx/build-tools/23.0.1/zipalign

info: [debug] Zip-aligning apk.
info: [debug] executing cmd: /Users/mabdurrahman/Sources/Developing/Android/SDK/android-sdk-macosx/build-tools/23.0.1/zipalign -f 4 /Users/mabdurrahman/TestHybridApp.apk /var/folders/34/vv824_550h76c_bypk9wvf3c0000gn/T/115111-30951-1es6i0y/appium.tmp

info: [debug] MD5 for app is 30f5b45e1006c3791ce6a9207c86c2b6

info: [debug] executing cmd: /Users/mabdurrahman/Sources/Developing/Android/SDK/android-sdk-macosx/platform-tools/adb -s 069a15a70b301e8a shell "ls /data/local/tmp/30f5b45e1006c3791ce6a9207c86c2b6.apk"

info: [debug] Getting install status for com.test.app

info: [debug] Getting device API level
info: [debug] executing cmd: /Users/mabdurrahman/Sources/Developing/Android/SDK/android-sdk-macosx/platform-tools/adb -s 069a15a70b301e8a shell "getprop ro.build.version.sdk"

info: [debug] Device is at API Level 23

info: [debug] executing cmd: /Users/mabdurrahman/Sources/Developing/Android/SDK/android-sdk-macosx/platform-tools/adb -s 069a15a70b301e8a shell "pm list packages -3 com.test.app"

info: [debug] App is installed

info: App is already installed, resetting app
info: [debug] Running fast reset (stop and clear)
info: [debug] executing cmd: /Users/mabdurrahman/Sources/Developing/Android/SDK/android-sdk-macosx/platform-tools/adb -s 069a15a70b301e8a shell "am force-stop com.test.app"

info: [debug] executing cmd: /Users/mabdurrahman/Sources/Developing/Android/SDK/android-sdk-macosx/platform-tools/adb -s 069a15a70b301e8a shell "pm clear com.test.app"

info: [debug] Forwarding system:4724 to device:4724

info: [debug] executing cmd: /Users/mabdurrahman/Sources/Developing/Android/SDK/android-sdk-macosx/platform-tools/adb -s 069a15a70b301e8a forward tcp:4724 tcp:4724

info: [debug] Pushing appium bootstrap to device...

info: [debug] executing cmd: /Users/mabdurrahman/Sources/Developing/Android/SDK/android-sdk-macosx/platform-tools/adb -s 069a15a70b301e8a push "/Applications/Appium.app/Contents/Resources/node_modules/appium/build/android_bootstrap/AppiumBootstrap.jar" /data/local/tmp/

info: [debug] Pushing settings apk to device...

info: [debug] executing cmd: /Users/mabdurrahman/Sources/Developing/Android/SDK/android-sdk-macosx/platform-tools/adb -s 069a15a70b301e8a install "/Applications/Appium.app/Contents/Resources/node_modules/appium/build/settings_apk/settings_apk-debug.apk"

info: [debug] Pushing unlock helper app to device...

info: [debug] executing cmd: /Users/mabdurrahman/Sources/Developing/Android/SDK/android-sdk-macosx/platform-tools/adb -s 069a15a70b301e8a install "/Applications/Appium.app/Contents/Resources/node_modules/appium/build/unlock_apk/unlock_apk-debug.apk"

info: Starting App

info: [debug] Attempting to kill all 'uiautomator' processes
info: [debug] Getting all processes with 'uiautomator'
info: [debug] executing cmd: /Users/mabdurrahman/Sources/Developing/Android/SDK/android-sdk-macosx/platform-tools/adb -s 069a15a70b301e8a shell "ps 'uiautomator'"

info: [debug] Attempting to kill process 19394

info: [debug] executing cmd: /Users/mabdurrahman/Sources/Developing/Android/SDK/android-sdk-macosx/platform-tools/adb -s 069a15a70b301e8a shell "kill 19394"

info: [debug] Running bootstrap

info: [debug] spawning: /Users/mabdurrahman/Sources/Developing/Android/SDK/android-sdk-macosx/platform-tools/adb -s 069a15a70b301e8a shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.Bootstrap -e pkg com.test.app -e disableAndroidWatchers false

info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1

info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
info: [debug] [UIAUTOMATOR STDOUT] io.appium.android.bootstrap.Bootstrap:
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap

info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 1

info: [debug] [BOOTSTRAP] [debug] Socket opened on port 4724
info: [debug] [BOOTSTRAP] [debug] Appium Socket Server Ready

info: [debug] [BOOTSTRAP] [debug] Loading json...
info: [debug] [BOOTSTRAP] [debug] json loading complete.
info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.

info: [debug] Waking up device if it's not alive

info: [debug] Pushing command to appium work queue: ["wake",{}]

info: [debug] [BOOTSTRAP] [debug] Emitting system alert message

info: [debug] Emitting alert message...

error: uncaughtException: Cannot read property 'sockets' of null date=Tue Dec 01 2015 19:36:45 GMT+0200 (EET), pid=30951, uid=501, gid=20, cwd=/Applications/Appium.app/Contents/Resources/node_modules/appium, execPath=/Applications/Appium.app/Contents/Resources/node/bin/node, version=v0.12.7, argv=[/Applications/Appium.app/Contents/Resources/node/bin/node, /Applications/Appium.app/Contents/Resources/node_modules/appium/lib/server/main.js, --command-timeout, 7200, --pre-launch, --debug-log-spacing, --automation-name, Appium, --platform-name, Android, --platform-version, 4.4, --app, /Users/mabdurrahman/TestHybridApp.apk, --device-name, 069a15a70b301e8a], rss=135897088, heapTotal=112283136, heapUsed=82491120, loadavg=[1.5185546875, 1.51611328125, 1.57373046875], uptime=864558, trace=[column=25, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/android/uiautomator.js, function=, line=195, method=null, native=false, column=9, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/underscore/underscore.js, function=Function._.each._.forEach, line=153, method=_.each._.forEach, native=false, column=5, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/android/uiautomator.js, function=[object Object].UiAutomator.handleBootstrapOutput, line=185, method=UiAutomator.handleBootstrapOutput, native=false, column=8, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/android/uiautomator.js, function=[object Object].UiAutomator.outputStreamHandler, line=174, method=UiAutomator.outputStreamHandler, native=false, column=17, file=events.js, function=Socket.emit, line=107, method=emit, native=false, column=16, file=_stream_readable.js, function=readableAddChunk, line=163, method=null, native=false, column=10, file=_stream_readable.js, function=Socket.Readable.push, line=126, method=Readable.push, native=false, column=20, file=net.js, function=Pipe.onread, line=538, method=onread, native=false], stack=[TypeError: Cannot read property 'sockets' of null,     at [object Object].<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/android/uiautomator.js:195:25),     at Function._.each._.forEach (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/underscore/underscore.js:153:9),     at [object Object].UiAutomator.handleBootstrapOutput (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/android/uiautomator.js:185:5),     at [object Object].UiAutomator.outputStreamHandler (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/android/uiautomator.js:174:8),     at Socket.emit (events.js:107:17),     at readableAddChunk (_stream_readable.js:163:16),     at Socket.Readable.push (_stream_readable.js:126:10),     at Pipe.onread (net.js:538:20)]
```

I'm currently using Appium 1.4.13, but I can reproduce the issue using older versions as well (1.4.8 and 1.3.7)

Can anyone help me getting this issue resolved?

**Comment by krunkmetalist** [comment]
@mabdurrahman I was also seeing this just yesterday on marshmallow(6.0.0),  appium version 1.4.13, & el capitan(osx). I updated to 6.0.1 this morning and made sure to change the usb connection type, in the notification shade, to "file transfers (MTP)" & now it's working. Hope that helps.
