### ISSUE TITLE
Failed to start an Appium session, err was: TypeError: Cannot read property 'stop' of null

### ISSUE THREAD

**Issue by nadiagarcia** [appium/appium#5938]
Hi all,

I am trying to tun my test in and Android device.
I have downloaded the SDK and set the ANDROID_HOME variable, I was able to successfully run the ```reset.sh --android --verbose command``` :

```
.
.
.
Running "setConfigVer:android" (setConfigVer) task
Config file exists, updating it
{"git-sha":"cdadd16d216abbe9838ed48a37af7d0aaed67150","ios":{"version":"1.4.16"},"built":"2015-12-14T20:38:22.894Z","android":{"version":"1.4.16"}}
Done, without errors.
CLEANING UP
* Cleaning any temp files
* Setting build time and SHA info
Running "setBuildTime" task
Config file exists, updating it
{"git-sha":"cdadd16d216abbe9838ed48a37af7d0aaed67150","ios":{"version":"1.4.16"},"built":"2015-12-18T17:57:12.695Z","android":{"version":"1.4.16"}}
Done, without errors.
---- reset.sh completed successfully ----
```

But when trying to run my test, Appium is logging this error:
```
info: Chromedriver: Changed state to 'starting'
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: TypeError: Cannot read property 'stop' of null
info: [debug] TypeError: Cannot read property 'stop' of null
    at Chromedriver.start$ (lib/chromedriver.js:96:24)
    at tryCatch (/Users/ngarcia/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/ngarcia/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/regenerator/runtime.js:294:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/ngarcia/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/ngarcia/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at bound (domain.js:281:14)
    at GeneratorFunctionPrototype.runBound (domain.js:294:12)
    at run (/Users/ngarcia/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:89:39)
    at /Users/ngarcia/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:100:28
    at nextTickCallbackWith0Args (node.js:433:9)
    at process._tickDomainCallback (node.js:403:13)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Cannot read property 'stop' of null)","origValue":"Cannot read property 'stop' of null"},"sessionId":null}
info: <-- POST /wd/hub/session 500 29709.779 ms - 192 
```

If I run the appium doctor, I get:
```
Running iOS Checks
✔ Xcode is installed at /Applications/Xcode.app/Contents/Developer/
✔ Xcode Command Line Tools are installed.
✔ DevToolsSecurity is enabled.
✔ The Authorization DB is set up properly.
✔ Node binary found at /usr/local/bin/node
✔ iOS Checks were successful.

Running Android Checks
✔ ANDROID_HOME is set to "/Users/ngarcia/Library/Android/sdk"
✔ JAVA_HOME is set to "/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home."
✔ ADB exists at /Users/ngarcia/Library/Android/sdk/platform-tools/adb
✔ Android exists at /Users/ngarcia/Library/Android/sdk/tools/android
✔ Emulator exists at /Users/ngarcia/Library/Android/sdk/tools/emulator
✔ Android Checks were successful.

✔ All Checks were successful
```
I have been googling the problem for a while, but I have not been able to find something useful. Any ideas?

**Comment by nadiagarcia** [comment]
I must add that I am running the chrome driver in a different terminal:
```
$ chromedriver 
Starting ChromeDriver 2.15.322455 (ae8db840dac8d0c453355d3d922c91adfb61df8f) on port 9515
Only local connections are allowed.
```

**Comment by nadiagarcia** [comment]
I was able to work around this by including the path to the chrome driver when launching appium:

```
$ ./bin/appium.js --chromedriver-executable ~/Downloads/chromedriver
```
