### ISSUE TITLE
Session [null] not available and is not among the last 1000 terminated sessions.

### ISSUE THREAD

**Issue by shaikatz** [appium/appium#5942]
Hi,

Environment:
Using appium 1.4 with android Lolipop Genymotion devices 
selenium grid version 2.48.2 (happend on 2.46.0 as well)
javaclient both 3.0 and 3.3 was tried

 after some test runs on the same node I'm getting this exception from the webdriver.
```
Caused by: org.openqa.selenium.WebDriverException: Session [null] not available and is not among the last 1000 terminated sessions.
Active sessions are[ext. key 09d59f24-dcc1-4277-b795-95dc8f69a394, ext. key 74404a11-04c0-42d2-b152-151a1e3af41e, ext. key da9d3902-8004-4ef6-9d60-709388d53657, ext. key 663dec99-a8fd-4bd8-aacb-679606f0c8dd]
Build info: version: '2.48.2', revision: '41bccdd10cf2c0560f637404c2d96164b67d9d67', time: '2015-10-09 13:08:06'
System info: host: 'TCA_7', ip: '10.102.43.116', os.name: 'Windows Server 2008 R2', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_66'
Driver info: driver.version: unknown
    at org.openqa.grid.internal.ActiveTestSessions.getExistingSession(ActiveTestSessions.java:110)
    at org.openqa.grid.internal.Registry.getExistingSession(Registry.java:425)
    at org.openqa.grid.web.servlet.handler.RequestHandler.getSession(RequestHandler.java:240)
    at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:120)
    at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:83)
    at org.openqa.grid.web.servlet.DriverServlet.doGet(DriverServlet.java:61)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
    at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:808)
    at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:587)
    at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:221)
    at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
    at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:515)
    at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:185)
    at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
    at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
    at org.seleniumhq.jetty9.server.Server.handle(Server.java:499)
    at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:310)
    at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:257)
    at org.seleniumhq.jetty9.io.AbstractConnection$2.run(AbstractConnection.java:540)
    at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
    at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
    at java.lang.Thread.run(Unknown Source)
```

The next sessions will get this exception until node restart:
```
Caused by: org.openqa.selenium.remote.SessionNotFoundException: 
Command duration or timeout: 4.50 seconds
Build info: version: '2.48.2', revision: '41bccdd10cf2c0560f637404c2d96164b67d9d67', time: '2015-10-09 13:08:06'
System info: host: 'TCA_7', ip: '10.102.43.116', os.name: 'Windows Server 2008 R2', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_66'
Driver info: io.appium.java_client.android.AndroidDriver
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:164)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:647)
    at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
    at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
    at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
    at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:247)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:129)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:142)
    at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:37)
    at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:161)
    at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:170)
    at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:82)
    at Tests.DriverManagement.MobileDriverFactory.create(MobileDriverFactory.java:37)
```

I'll appreciate your help, thanks.

**Comment by scottdixon** [comment]
Please try with Appium 1.5. If you hit an issue please post a link to your Appium server logs as a gist.

**Comment by SrinivasanTarget** [comment]
@shaikatz Session handling's are improved alot in current architecture.Please give a shot in Appium 1.5.1.Incase if you still face any issues, reopen this with logs inform of gist.Closing this.

**Comment by SrinivasanTarget** [comment]
@triager please close

**Comment by ds3p2** [comment]
Hi, 
I am facing the same problem in Appium 1.5.2.
Environment: Safari on iPad Pro with IOS 9.1, Selenium grid 2.53
Appium is able to launch the SafariLauncher and open the default page in Safari.
But any further operation on the driver will get the same error:
I get the following trace on java side:
```
Caused by: org.openqa.selenium.WebDriverException: Session [c40f4e09-7da9-46a8-af73-9fafa2bb6be8] not available and is not among the last 1000 terminated sessions.
Active sessions are[]
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'XXX', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-327.10.1.el7.x86_64', java.version: '1.8.0_77'
Driver info: driver.version: unknown
	at org.openqa.grid.internal.ActiveTestSessions.getExistingSession(ActiveTestSessions.java:110)
	at org.openqa.grid.internal.Registry.getExistingSession(Registry.java:425)
	at org.openqa.grid.web.servlet.handler.RequestHandler.getSession(RequestHandler.java:240)
	at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:120)
	at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:83)
	at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:67)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.seleniumhq.jetty9.server.Server.handle(Server.java:499)
	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:310)
	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.seleniumhq.jetty9.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:812)
```

But I get no error log on Appium Side:
```
2016-05-05 19:32:43:813 - [MJSONWP] Calling AppiumDriver.createSession() with args: [{"browserName":"safari","version":"","platform":"MAC"},null,null,null,null,null,null,null,null,null]
2016-05-05 19:32:43:814 - [Appium] Creating new IosDriver session
2016-05-05 19:32:43:815 - [Appium] Capabilities:
2016-05-05 19:32:43:815 - [Appium]   browserName: 'safari'
2016-05-05 19:32:43:816 - [Appium]   version: ''
2016-05-05 19:32:43:816 - [Appium]   platform: 'MAC'
2016-05-05 19:32:43:816 - [Appium]   platformName: 'iOS'
2016-05-05 19:32:43:816 - [Appium]   platformVersion: '9.2'
2016-05-05 19:32:43:817 - [Appium]   deviceName: 'iPad Pro'
2016-05-05 19:32:43:817 - [Appium]   udid: 'a9b1dd1a7a081ec5ef00aae7337eba53a5ad7037'
2016-05-05 19:32:43:817 - [Appium]   fullReset: true
2016-05-05 19:32:43:826 - [BaseDriver] The following capabilities were provided, but are not recognized by appium: version, platform.
2016-05-05 19:32:43:826 - [BaseDriver] Session created with session id: c40f4e09-7da9-46a8-af73-9fafa2bb6be8
2016-05-05 19:32:43:827 - [debug] [iOS] Not auto-detecting udid.
2016-05-05 19:32:43:828 - [debug] [iOS] Creating iDevice object with udid a9b1dd1a7a081ec5ef00aae7337eba53a5ad7037
2016-05-05 19:32:45:834 - [debug] [iOS] Checking for presence of SafariLauncher at '/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/build/SafariLauncher/SafariLauncher.app'
2016-05-05 19:32:45:834 - [debug] [iOS] SafariLauncher exists
2016-05-05 19:32:45:835 - [debug] [iOS] Removing any remaining instruments sockets
2016-05-05 19:32:45:836 - [debug] [iOS] Cleaned up instruments socket /var/folders/j5/lkctjtv925sgp66sps01yv5c0000gt/T/instruments_sock
2016-05-05 19:32:45:836 - [debug] [iOS] No language specified. Using default strings
2016-05-05 19:32:45:837 - [debug] [iOS] Strings file not found. Looking in 'en.lproj' directory
2016-05-05 19:32:45:838 - [iOS] Could not file localizable strings file 'Localizable.strings'!
2016-05-05 19:32:45:838 - [debug] [iOS] Creating instruments
2016-05-05 19:32:45:839 - [debug] [UIAuto] Preparing bootstrap code
2016-05-05 19:32:45:839 - [debug] [UIAuto] Dynamic bootstrap dir: /Users/administrator/Library/Application Support/appium/bootstrap
2016-05-05 19:32:45:839 - [debug] [UIAuto] Dynamic env: {"nodePath":"/usr/local/bin/node","commandProxyClientPath":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js","instrumentsSock":"/var/folders/j5/lkctjtv925sgp66sps01yv5c0000gt/T/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"grouped"}
...6-05-05 19:32:45:921 - [debug] [UIAuto] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
2016-05-05 19:32:45:921 - [debug] [UIAuto] Dynamic bootstrap path: /Users/administrator/Library/Application Support/appium/bootstrap/bootstrap-aefcfa7e8ad78c12.js
2016-05-05 19:32:45:947 - [debug] [UIAuto] Reusing dynamic bootstrap: /Users/administrator/Library/Application Support/appium/bootstrap/bootstrap-aefcfa7e8ad78c12.js
2016-05-05 19:32:45:949 - [debug] [iOS] Running ios real device reset flow
2016-05-05 19:32:45:949 - [debug] [iOS] Full reset requested. Will try to uninstall the app 'com.bytearc.SafariLauncher'.
2016-05-05 19:32:46:106 - [debug] [Appium] Appium successfully registered with the grid on XXXX:4444
2016-05-05 19:32:47:573 - [debug] [iOS] Removed com.bytearc.SafariLauncher
2016-05-05 19:32:47:574 - [debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
2016-05-05 19:32:47:575 - [debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
2016-05-05 19:32:49:264 - [debug] [iOS] App is not installed. Will try to install the app.
2016-05-05 19:32:51:110 - [HTTP] --> GET /wd/hub/status {}
2016-05-05 19:32:51:111 - [MJSONWP] Calling AppiumDriver.getStatus() with args: []
2016-05-05 19:32:51:118 - [debug] [Appium] Appium successfully registered with the grid on XXXX:4444
2016-05-05 19:32:51:893 - [debug] [iOS] Starting UIAutoClient, and launching Instruments.
2016-05-05 19:32:51:943 - [debug] [UIAuto] Instruments socket server started at /var/folders/j5/lkctjtv925sgp66sps01yv5c0000gt/T/instruments_sock
2016-05-05 19:32:51:977 - [debug] [Instruments] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
2016-05-05 19:32:51:977 - [debug] [Instruments] Attempting to launch instruments, this is try #1
2016-05-05 19:32:51:978 - [Instruments] Launching instruments
2016-05-05 19:32:52:000 - [debug] [Instruments] Attempting to run app on real device with UDID 'a9b1dd1a7a081ec5ef00aae7337eba53a5ad7037'
2016-05-05 19:32:52:001 - [debug] [Instruments] Found Insruments-Without-Delay: /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-instruments/thirdparty/iwd7
2016-05-05 19:32:52:001 - [debug] [Instruments] Spawning instruments with command: '/Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /var/folders/j5/lkctjtv925sgp66sps01yv5c0000gt/T/appium-instruments/instrumentscli0.trace -w a9b1dd1a7a081ec5ef00aae7337eba53a5ad7037 com.bytearc.SafariLauncher -e UIASCRIPT "/Users/administrator/Library/Application Support/appium/bootstrap/bootstrap-aefcfa7e8ad78c12.js" -e UIARESULTSPATH /var/folders/j5/lkctjtv925sgp66sps01yv5c0000gt/T/appium-instruments'
2016-05-05 19:32:52:002 - [debug] [Instruments] And extra without-delay env: {}
2016-05-05 19:32:52:002 - [debug] [Instruments] And launch timeouts (in ms): {"global":90000}
2016-05-05 19:32:56:118 - [debug] [Appium] Appium successfully registered with the grid on XXXX:4444
2016-05-05 19:32:59:324 - [debug] [Instruments] [INST STDERR] 2016-05-05 19:32:59.323 instruments[81302:5657315] WebKit Threading Violation - initial use of WebKit from a secondary thread.
2016-05-05 19:33:01:121 - [HTTP] --> GET /wd/hub/status {}
2016-05-05 19:33:01:122 - [MJSONWP] Calling AppiumDriver.getStatus() with args: []
2016-05-05 19:33:01:123 - [debug] [Appium] Appium successfully registered with the grid on XXXX:4444
2016-05-05 19:33:03:770 - [UIAuto] Instruments is ready to receive commands
2016-05-05 19:33:03:771 - [debug] [iOS] Instruments launched. Starting poll loop for new commands.
2016-05-05 19:33:03:771 - [debug] [iOS] Setting bootstrap config keys/values
2016-05-05 19:33:03:774 - [debug] [UIAuto] Socket data received (2 bytes)
2016-05-05 19:33:03:774 - [debug] [UIAuto] Got a result when we were not expecting one! Ignoring it
2016-05-05 19:33:03:774 - [debug] [UIAuto] Sending command to instruments: target = $.target();
au = $;
$.isVerbose = true;

2016-05-05 19:33:04:769 - [debug] [UIAuto] Socket data received (27 bytes)
2016-05-05 19:33:04:770 - [debug] [UIAuto] Got result from instruments: {"status":0,"value":true}
2016-05-05 19:33:04:771 - [debug] [iOS] Setting initial orientation to PORTRAIT
2016-05-05 19:33:04:771 - [debug] [UIAuto] Sending command to instruments: au.setScreenOrientation('PORTRAIT')
2016-05-05 19:33:04:959 - [debug] [Instruments] [INST] 2016-05-05 11:33:17 +0000 Debug: evaluation finished
2016-05-05 19:33:05:115 - [debug] [Instruments] [INST] 2016-05-05 11:33:17 +0000 Debug: responding with:
2016-05-05 19:33:05:120 - [debug] [Instruments] [INST] 2016-05-05 11:33:17 +0000 Debug: Running system command #1: /usr/local/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /var/folders/j5/lkctjtv925sgp66sps01yv5c0000gt/T/instruments_sock 2,{"status":0,"value":true}...
2016-05-05 19:33:05:732 - [debug] [Instruments] [INST] 2016-05-05 11:33:18 +0000 Debug: Got new command 1 from instruments: au.setScreenOrientation('PORTRAIT')
2016-05-05 19:33:05:764 - [debug] [Instruments] [INST] 2016-05-05 11:33:18 +0000 Debug: evaluating au.setScreenOrientation('PORTRAIT')
2016-05-05 19:33:05:769 - [debug] [Instruments] [INST] 2016-05-05 11:33:18 +0000 Debug: target.setDeviceOrientation("1")
2016-05-05 19:33:06:122 - [debug] [Appium] Appium successfully registered with the grid on XXXX:4444
2016-05-05 19:33:06:658 - [debug] [Instruments] [INST] 2016-05-05 11:33:19 +0000 Debug: evaluation finished
2016-05-05 19:33:06:663 - [debug] [Instruments] [INST] 2016-05-05 11:33:19 +0000 Debug: responding with:
2016-05-05 19:33:06:690 - [debug] [UIAuto] Socket data received (33 bytes)
2016-05-05 19:33:06:691 - [debug] [UIAuto] Got result from instruments: {"status":0,"value":"PORTRAIT"}
2016-05-05 19:33:06:691 - [debug] [iOS] Attempting to launch Safari from Safari Launcher
2016-05-05 19:33:06:692 - [debug] [BaseDriver] Waiting up to 0 ms for condition
2016-05-05 19:33:06:694 - [debug] [UIAuto] Sending command to instruments: au.getElementByAccessibilityId('launch safari')
2016-05-05 19:33:06:706 - [debug] [Instruments] [INST] 2016-05-05 11:33:19 +0000 Debug: Running system command #2: /usr/local/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /var/folders/j5/lkctjtv925sgp66sps01yv5c0000gt/T/instruments_sock 2,{"status":0,"value":"PORTRAIT"}...
2016-05-05 19:33:07:753 - [debug] [Instruments] [INST] 2016-05-05 11:33:20 +0000 Debug: Got new command 2 from instruments: au.getElementByAccessibilityId('launch safari')
2016-05-05 19:33:07:835 - [debug] [UIAuto] Socket data received (38 bytes)
2016-05-05 19:33:07:835 - [debug] [UIAuto] Got result from instruments: {"status":0,"value":{"ELEMENT":"0"}}
2016-05-05 19:33:07:836 - [debug] [UIAuto] Sending command to instruments: au.tapById('0')
2016-05-05 19:33:07:857 - [debug] [Instruments] [INST] 2016-05-05 11:33:20 +0000 Debug: evaluating au.getElementByAccessibilityId('launch safari')
2016-05-05 19:33:07:863 - [debug] [Instruments] [INST] 2016-05-05 11:33:21 +0000 Debug: evaluation finished
2016-05-05 19:33:07:868 - [debug] [Instruments] [INST] 2016-05-05 11:33:21 +0000 Debug: Lookup returned [object UIAButton] with the name "launch safari" (id: 0).
2016-05-05 19:33:07:874 - [debug] [Instruments] [INST] 2016-05-05 11:33:21 +0000 Debug: responding with:
2016-05-05 19:33:07:911 - [debug] [Instruments] [INST] 2016-05-05 11:33:21 +0000 Debug: Running system command #3: /usr/local/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /var/folders/j5/lkctjtv925sgp66sps01yv5c0000gt/T/instruments_sock 2,{"status":0,"value":{"ELEMENT":"0"}}...
2016-05-05 19:33:08:823 - [debug] [Instruments] [INST] 2016-05-05 11:33:22 +0000 Debug: Got new command 3 from instruments: au.tapById('0')
2016-05-05 19:33:08:829 - [debug] [Instruments] [INST] 2016-05-05 11:33:22 +0000 Debug: evaluating au.tapById('0')
2016-05-05 19:33:08:835 - [debug] [Instruments] [INST] 2016-05-05 11:33:22 +0000 Debug: UIAButton.tap()
2016-05-05 19:33:08:969 - [debug] [Instruments] [INST] 2016-05-05 11:33:22 +0000 Debug: evaluation finished
2016-05-05 19:33:09:005 - [debug] [Instruments] [INST] 2016-05-05 11:33:22 +0000 Debug: responding with:
2016-05-05 19:33:09:036 - [debug] [Instruments] [INST] 2016-05-05 11:33:22 +0000 Debug: Running system command #4: /usr/local/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /var/folders/j5/lkctjtv925sgp66sps01yv5c0000gt/T/instruments_sock 2,{"status":0,"value":""}...
2016-05-05 19:33:09:039 - [debug] [UIAuto] Socket data received (25 bytes)
2016-05-05 19:33:09:039 - [debug] [UIAuto] Got result from instruments: {"status":0,"value":""}
2016-05-05 19:33:09:039 - [debug] [iOS] Clicked button, safari should be launching.
2016-05-05 19:33:09:040 - [debug] [iOS] Waiting for initial webview
2016-05-05 19:33:09:040 - [debug] [iOS] Waiting for 3000 ms before navigating to view.
2016-05-05 19:33:11:125 - [HTTP] --> GET /wd/hub/status {}
2016-05-05 19:33:11:125 - [MJSONWP] Calling AppiumDriver.getStatus() with args: []
2016-05-05 19:33:11:126 - [debug] [Appium] Appium successfully registered with the grid on XXXX:4444
2016-05-05 19:33:12:046 - [debug] [iOS] Navigating to most recently opened webview
2016-05-05 19:33:12:046 - [debug] [iOS] Retrieving contexts and views
2016-05-05 19:33:12:046 - [debug] [iOS] Selecting by url: true (expected url: 'undefined')
2016-05-05 19:33:12:047 - [debug] [RemoteDebugger] Getting WebKitRemoteDebugger pageArray: localhost, 27753
2016-05-05 19:33:12:047 - [debug] [RemoteDebugger] Sending request to: http://localhost:27753/json
2016-05-05 19:33:12:051 - [debug] [RemoteDebugger] Page element JSON: [{"devtoolsFrontendUrl":"/devtools/devtools.html?ws=localhost:27753/devtools/page/7","faviconUrl":"","thumbnailUrl":"/thumb/http://www.apple.com/","title":"Apple","url":"http://www.apple.com/","webSocketDebuggerUrl":"ws://localhost:27753/devtools/page/7","appId":"PID:1629"}]
2016-05-05 19:33:12:052 - [debug] [iOS] Picking webview 'WEBVIEW_7'
2016-05-05 19:33:12:052 - [debug] [iOS] Attempting to set context to 'WEBVIEW_7'
2016-05-05 19:33:12:056 - [debug] [RemoteDebugger] WebKit debugger web socket connected to url: ws://localhost:27753/devtools/page/7
2016-05-05 19:33:12:056 - [debug] [RemoteDebugger] Unregistering from page readiness notifications
2016-05-05 19:33:12:058 - [Appium] New IosDriver session created successfully, session c40f4e09-7da9-46a8-af73-9fafa2bb6be8 added to master session list
2016-05-05 19:33:12:060 - [MJSONWP] Responding to client with driver.createSession() result: {"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"safari","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,...
```

**Comment by ericomurtez** [comment]
@ds3p2 Did you ever solve this? Seeing same, but what is unusual I am only seeing it one of my environments so it is definitely something I have done but I cant figure out the discrepancy?
