### ISSUE TITLE
iOS native app: long press Touch Action does not work with appium java client 3.1.0

### ISSUE THREAD

**Issue by utkarsha1** [appium/appium#5943]
I am trying to automate long press touch action in a native iOS app to simulate long press in top left corner which did not work.

Approach1: 
```
new TouchAction(driver).longPress(0,0).perform() ;
```
Appium logs show no error:
```
info: [debug] [INST] 2015-12-21 17:41:19 +0000 Debug: Got new command 5 from instruments: target.touch([{"touch":[{"x":0,"y":0}],"time":0.2}])
info: [debug] [INST] 2015-12-21 17:41:19 +0000 Debug: evaluating target.touch([{"touch":[{"x":0,"y":0}],"time":0.2}])
info: [debug] [INST] 2015-12-21 17:41:19 +0000 Debug: target.touch(__NSCFArray)
info: [debug] [INST] 2015-12-21 17:41:20 +0000 Debug: evaluation finished
info: [debug] [INST] 2015-12-21 17:41:20 +0000 Debug: responding with:
info: [debug] [INST] 2015-12-21 17:41:20 +0000 Debug: Running system command #6: /usr/local/Cellar/node/4.1.1/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":""}...
info: [debug] Socket data received (25 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":""}
info: [debug] Responding to client with success: {"status":0,"value":"","sessionId":"332523ee-5a1b-427a-8beb-3c150587d08b"}
```
Approach 2: Execute javascript to simulate long press
```
((IOSDriver)driver).executeScript("mobile: longClick", ImmutableMap.of("x", 5, "y", 5));
```
Appium log exception as follows:
```
TypeError: cb is not a function
    at [object Object].iOSController.touchLongClick (/usr/local/lib/node_modules/appium/lib/devices/ios/ios-controller.js:614:3)
    at Object.exports.touchLongClick [as longClick] (/usr/local/lib/node_modules/appium/lib/server/controller.js:371:16)
    at Object.exports.executeMobileMethod (/usr/local/lib/node_modules/appium/lib/server/controller.js:984:22)
    at exports.execute (/usr/local/lib/node_modules/appium/lib/server/controller.js:940:15)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:82:5)
```
Appium server version is 1.4.16.

**Comment by priyankshah217** [comment]
I m using 1.4.16 and Java client 3.3.0 and work perfectly. 
Suggestion: Do not hard code coordinates, Always provide coordinates based on elements.

**Comment by utkarsha1** [comment]
I am trying to long press a 'secret' area of the screen to invoke special behaviour for testing. For that reason we cannot use accessibility so that people to activate accessibility do not see this secret element. Is there a way to uniquely identify such an element without specifying an identifier?

My co-ordinates may be the issue I will continue the trial and error, thanks!
