### ISSUE TITLE
[1.5] Appium doesn't proxy all capabilities from Chromedriver

### ISSUE THREAD

**Issue by bayandin** [appium/appium#5946]
I can't execute javascript code in mobile Chrome because Appium (1.5.0-beta9) doesn't proxy all capabilities from chromedriver (because ruby Selenium lib checks that client — chrome in my case — has {"javascriptEnabled": true} capability and can execute javascript).

Example:

```ruby
#!/usr/bin/env ruby

require 'appium_lib'

android_opts = {
  caps: {
    platformName: 'Android',
    deviceName: '064228da2526d5b1',
    platformVersion: '6.0.1',
    browserName: 'Chrome'
  },
  appium_lib: {
    port: 4723,
  }
}

appium = Appium::Driver.new(android_opts)
driver = appium.start_driver

driver.get 'https://github.com/appium/appium'

begin
  driver.execute_script '1+1'
rescue Selenium::WebDriver::Error::UnsupportedOperationError => e
  puts e
  puts e.backtrace
ensure
  appium.driver_quit
end
```
```
underlying webdriver instance does not support javascript
/Users/bayandin/.rvm/gems/ruby-2.1.5/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/bridge.rb:631:in `assert_javascript_enabled'
/Users/bayandin/.rvm/gems/ruby-2.1.5/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/bridge.rb:366:in `executeScript'
/Users/bayandin/.rvm/gems/ruby-2.1.5/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/common/driver.rb:216:in `execute_script'
bug.rb:23:in `<main>'
```

I've saved all logs (from appium, http log from appium and http log from chromedriver): https://gist.github.com/bayandin/db6d05ffc88f1893d2b6

When chromedriver returns:
```
  HTTP/1.1 200 OK..Content-Length:528..Content-Type:application/json; charset=utf-8..Connection:close....{"sessionId":"e87ea6e6b8d09b1d5dbe9ec2561929e4","status":0,"value":{"acce
  ptSslCerts":true,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"browserName":"chrome","chrome":{},"cssSelectorsEnabled":true,"databaseEnabled":false,"handles
  Alerts":true,"hasTouchScreen":true,"javascriptEnabled":true,"locationContextEnabled":true,"mobileEmulationEnabled":false,"nativeEvents":true,"platform":"ANDROID","rotatable":fa
  lse,"takesHeapSnapshot":true,"takesScreenshot":true,"version":"47.0.2526.83","webStorageEnabled":true}}
```

Appium gets it and returns to the client library only this:
```
  HTTP/1.1 200 OK..X-Powered-By: Express..Access-Control-Allow-Origin: *..Access-Control-Allow-Methods: GET,POST,PUT,OPTIONS,DELETE..Access-Control-Allow-Headers: origin, content
  -type, accept..Vary: X-HTTP-Method-Override..Content-Type: application/json; charset=utf-8..Content-Length: 179..ETag: W/"b3-kHJw9MLOR5dUiuU7gN2h4Q"..Date: Tue, 22 Dec 2015 16:
  36:07 GMT..Connection: close....{"status":0,"value":{"platformName":"Android","deviceName":"064228da2526d5b1","platformVersion":"6.0.1","browserName":"Chrome"},"sessionId":"10c
  dadf1-890b-4e95-af9f-df7756539f72"}
```

**Comment by scottdixon** [comment]
Thanks for the detailed report!

Looks like createSession is only returning the desired caps instead of the merged server + desired caps. Submitting a fix now.

**Comment by scottdixon** [comment]
I've published the android-driver fix. If you do a fresh Appium install you should be in business! Reopen if any issues.

**Comment by bayandin** [comment]
Thanks @scottdixon seems it works fine :)
