### ISSUE TITLE
Remote server getLocation problem

### ISSUE THREAD

**Issue by kasirga32** [appium/appium#5960]
I'm testing a code snippet which runs perfect on local server. When I try same code in remote mac server, Appium throws exception. Code is simple:

```List<WebElement> clickableElements = driver.findElementsByAndroidUIAutomator("new UiSelector()");
      for (WebElement clickableElement : clickableElements) {
         System.out.println(clickableElement.getLocation());
      }```
I tried with several attributes like getTagName, getSize etc. and doesnt give any error but in getLocation method throws exception. Crash log:

```Exception in thread "main" org.openqa.selenium.WebDriverException: Method has not yet been implemented (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 19 milliseconds
Build info: version: '2.46.0', revision: '61506a4624b13675f24581e453592342b7485d71', time: '2015-06-04 10:22:50'
System info: host: 'YUNUS-METE', ip: '217.78.106.33', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_79'
Session ID: 12410ba5-ac8a-4e45-9c5a-91c51065e6f7
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{automationName=Appium, platform=LINUX, app=/Users/netas/Downloads/gov.whitehouse.apk, javascriptEnabled=true, networkConnectionEnabled=true, desired={automationName=Appium, app=/Users/netas/Downloads/gov.whitehouse.apk, platformVersion=4.4.4, disableAndroidWatchers=true, deviceName=CB511WVPVS, platformName=Android, unicodeKeyboard=true, enablePerformanceLogging=true, appPackage=gov.whitehouse}, locationContextEnabled=false, appPackage=gov.whitehouse, platformVersion=4.3, databaseEnabled=false, disableAndroidWatchers=true, platformName=Android, deviceName=192.168.56.101:5555, webStorageEnabled=false, unicodeKeyboard=true, enablePerformanceLogging=true, warnings={}, takesScreenshot=true}]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:605)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:27)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:269)
	at io.appium.java_client.DefaultGenericMobileElement.execute(DefaultGenericMobileElement.java:27)
	at io.appium.java_client.MobileElement.execute(MobileElement.java:1)
	at io.appium.java_client.android.AndroidElement.execute(AndroidElement.java:1)
	at org.openqa.selenium.remote.RemoteWebElement.getLocation(RemoteWebElement.java:321)
	at tr.com.netas.mtos.mtos_android.Main.main(Main.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Picked up JAVA_TOOL_OPTIONS: -Djava.vendor="Sun Microsystems Inc."```
Any ideas?

**Comment by scottdixon** [comment]
Which version of Appium is the server running? You might need to use `getLocationInView`

**Comment by kasirga32** [comment]
Appium build version is 2.46.0 Also I tried to work on Android not iOS.

**Comment by scottdixon** [comment]
@kasirga32 the issue should be resolved, grab a fresh copy of Appium. Please reopen if any issues.

**Comment by kasirga32** [comment]
thanks
