### ISSUE TITLE
Cannot read property 'isAirplaneModeOn' of null

### ISSUE THREAD

**Issue by SwamiShekhar** [appium/appium#5968]
When i am calling method -
		```NetworkConnectionSetting networkConnection = ((AndroidDriver<?>)driver).getNetworkConnection();
		Boolean status = networkConnection.wifiEnabled();```

Getting below expection 
```TypeError: Cannot read property 'isAirplaneModeOn' of null
    at [object Object].androidCommon.getNetworkConnection (D:\Appium\node_modules\appium\lib\devices\android\android-common.js:884:11)
    at exports.getNetworkConnection (D:\Appium\node_modules\appium\lib\server\controller.js:1271:14)
    at Layer.handle [as handle_request] (D:\Appium\node_modules\appium\node_modules\express\lib\router\layer.js:82:5)
    at next (D:\Appium\node_modules\appium\node_modules\express\lib\router\route.js:110:13)
    at Route.dispatch (D:\Appium\node_modules\appium\node_modules\express\lib\router\route.js:91:3)
    at Layer.handle [as handle_request] (D:\Appium\node_modules\appium\node_modules\express\lib\router\layer.js:82:5)
    at D:\Appium\node_modules\appium\node_modules\express\lib\router\index.js:267:22
    at param (D:\Appium\node_modules\appium\node_modules\express\lib\router\index.js:340:14)
    at param (D:\Appium\node_modules\appium\node_modules\express\lib\router\index.js:356:14)
    at Function.proto.process_params (D:\Appium\node_modules\appium\node_modules\express\lib\router\index.js:400:3)
    at next (D:\Appium\node_modules\appium\node_modules\express\lib\router\index.js:261:10)```

**Comment by savishy** [comment]
Some immediate thoughts:

* is your `driver` object initialized?
* Can you clarify why you need to cast to `(AndroidDriver<?>`?

**Comment by SwamiShekhar** [comment]
@savishy  Yeah ! driver object is initialized properly so i am able to run automated scenarios.

AndroidDriver is a raw type in latest java-client-3.3.0 . References to generic type AndroidDriver<RequiredElementType> should be parameterized . If i don't parameterize it , i am getting waring msg. Even if i dont cast it, it works !

**Comment by savishy** [comment]
Okay. I am using java-client 3.2.0. AndroidDriver<AndroidElement> is what I use.

Do you have a small bit of self contained code I can run?

**Comment by SwamiShekhar** [comment]
Somehow driver object was null..solved :)
