### ISSUE TITLE
Can not assign autoWebview to appium driver.

### ISSUE THREAD

**Issue by mi2pankaj** [appium/appium#5973]
Whenever I am assigning autoWebview capability, I get error org.openqa.selenium.SessionNotCreatedException: A new session could not be created. (Original error: An unknown server-side error occurred while processing the command. (Original error: unknown error: Device 4d0025b440ca90d5 is not online. If I don't use this capability the everything is fine.
Appium Server Version: 1.4.16
Appium Client Driver: java-client-3.3.0.jar
With Java.

DesiredCapabilities capabilities = new DesiredCapabilities();

```
        capabilities.setCapability("deviceName", "Android");
        logger.info("Added capability: deviceName = Android");

        capabilities.setCapability("platformName", "Android");
        logger.info("Added capability: platformName = Android");

        capabilities.setCapability("app", appFile.getAbsolutePath());
        logger.info("Added capability: app = "+appFile.getAbsolutePath());

        capabilities.setCapability("serial", deviceID);
        logger.info("Added capability: serial = "+deviceID);

        capabilities.setCapability("newCommandTimeout", "60");
        logger.info("Added capability: newCommandTimeout = 60");

                   capabilities.setCapability("autoWebview", true);
           logger.info("Added capability: autoWebview = "+true);

                 driver = new AndroidDriver<AndroidElement>(new URL("http://localhost:4723/wd/hub"), capabilities);

        driver.manage().timeouts().implicitlyWait(timeout, TimeUnit.SECONDS);
        logger.info("Added Driver Timeout = "+timeout +" Sec. ");
```

Error stack trace:
org.openqa.selenium.SessionNotCreatedException: A new session could not be created. (Original error: An unknown server-side error occurred while processing the command. (Original error: unknown error: Device 4d0025b440ca90d5 is not online
  (Driver info: chromedriver=2.18.343837 (52eb4041461e46a6b73308ebb19e85787ced4281),platform=Mac OS X 10.11.2 x86_64))) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 19.13 seconds
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'VDO109.local', ip: '172.16.0.98', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.2', java.version: '1.8.0_65'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:647)
    at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:247)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:129)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:156)
    at projects.sdk.lib.GetDeviceDriver.setupAndroidDriver(GetDeviceDriver.java:62)
    at projects.sdk.lib.GetDeviceDriver.getDriver(GetDeviceDriver.java:244)
    at projects.sdk.lib.GetResults.getResults(GetResults.java:69)
    at projects.sdk.SDKAdServingTest.sdkTest(SDKAdServingTest.java:243)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
    at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
    at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
    at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
    at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
    at org.testng.TestRunner.privateRun(TestRunner.java:767)
    at org.testng.TestRunner.run(TestRunner.java:617)
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
    at org.testng.SuiteRunner.run(SuiteRunner.java:240)
    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
    at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
    at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
    at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
    at org.testng.TestNG.run(TestNG.java:1057)
    at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
    at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
    at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)

**Comment by scottdixon** [comment]
Can you please provide the Appium server log as a [gist](gist.github.com).

Also, git it a shot with the new Appium 1.5 beta `npm install -g appium@beta`

**Comment by mi2pankaj** [comment]
@scottdixon : I am not able to access gist - getting 404, I am pasting log here, I couldn't try with 1.5 beat version.

2016-01-13 11:42:25:967 - info: Chromedriver: Set chromedriver binary as: /Users/Pankaj/Desktop/QA_Automation/qascripting/Vdopia_Automation/tpt/chromedriver
2016-01-13 11:42:25:968 - info: Chromedriver: Killing any old chromedrivers, running: ps -ef | grep /Users/Pankaj/Desktop/QA_Automation/qascripting/Vdopia_Automation/tpt/chromedriver | grep -v grep |grep -e '--port=9515\(\s.*\)\?$' | awk '{ print $2 }' | xargs kill -15
2016-01-13 11:42:26:067 - info: Chromedriver: Successfully cleaned up old chromedrivers
2016-01-13 11:42:26:068 - info: Chromedriver: Spawning chromedriver with: /Users/Pankaj/Desktop/QA_Automation/qascripting/Vdopia_Automation/tpt/chromedriver --url-base=wd/hub --port=9515
2016-01-13 11:42:26:152 - info: Chromedriver: [STDOUT] Starting ChromeDriver 2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b) on port 9515
Only local connections are allowed.
2016-01-13 11:42:26:158 - info: JSONWP Proxy: Proxying [GET /status] to [GET http://127.0.0.1:9515/wd/hub/status] with no body
2016-01-13 11:42:26:388 - info: JSONWP Proxy: Proxying [GET /status] to [GET http://127.0.0.1:9515/wd/hub/status] with no body
2016-01-13 11:42:26:489 - info: JSONWP Proxy: Got response with status 200: "{\"sessionId\":\"\",\"status\":0,\"value\":{\"build\":{\"version\":\"alpha\"},\"os\":{\"arch\":\"x86_64\",\"name\":\"Mac OS X\",\"version\":\"10.11.2\"}}}"
2016-01-13 11:42:26:491 - info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.vdopia.sample","androidUseRunningApp":true,"androidDeviceSerial":"emulator-5554"}}}
2016-01-13 11:42:38:871 - error: Chromedriver: Chromedriver exited unexpectedly with code null, signal SIGTERM
2016-01-13 11:42:38:871 - info: Chromedriver: Changed state to 'stopped'
2016-01-13 11:42:38:872 - warn: Chromedriver for context WEBVIEW_com.vdopia.sample stopped unexpectedly
2016-01-13 11:42:38:872 - warn: Chromedriver quit unexpectedly, but it wasn't the active context, ignoring
2016-01-13 11:42:39:070 - info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.vdopia.sample","androidUseRunningApp":true,"androidDeviceSerial":"emulator-5554"}}}
2016-01-13 11:42:39:278 - info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.vdopia.sample","androidUseRunningApp":true,"androidDeviceSerial":"emulator-5554"}}}
2016-01-13 11:42:39:484 - info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.vdopia.sample","androidUseRunningApp":true,"androidDeviceSerial":"emulator-5554"}}}
2016-01-13 11:42:39:786 - error: Chromedriver: Error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:9515
    at JWProxy.proxy$ (lib/proxy.js:109:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/node_modules/appium-jsonwp-proxy/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/node_modules/appium-jsonwp-proxy/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/node_modules/appium-jsonwp-proxy/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/node_modules/appium-jsonwp-proxy/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at bound (domain.js:287:14)
    at GeneratorFunctionPrototype.runBound (domain.js:300:12)
    at run (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/node_modules/appium-jsonwp-proxy/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:89:39)
    at /usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/node_modules/appium-jsonwp-proxy/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:100:28
    at flush (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/node_modules/appium-jsonwp-proxy/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:17:13)
    at nextTickCallbackWith0Args (node.js:433:9)
    at process._tickDomainCallback (node.js:403:13)
 [Error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:9515]

**Comment by rkavalap** [comment]
Closing due to inactivity
