### ISSUE TITLE
[Android]Test fails when multiple device connected, Parallel execution affected

### ISSUE THREAD

**Issue by pr4bh4sh** [appium/appium#5982]
Server is not using the udid provided in desire caps as well as with server args on version 1.5(tested with 1.5.0-beta8 and beta9). 
It works with 1.4.16

Sever log:-
prabhashs$ appium --session-override -p 62551 -U emulator-5556 -bp 55518
[Appium] Welcome to Appium v1.5.0-beta8
[Appium] Appium REST http interface listener started on 0.0.0.0:62551
[Appium] Non-default server args:
[Appium]     port: 62551
[Appium]     bootstrapPort: 55518
[Appium]     sessionOverride: true
[Appium]     udid: emulator-5556
[Appium] Deprecated server args:
[Appium]     -U,--udid => --default-capabilities '{"udid":"emulator-5556"}'
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities: {"udid":"emulator-5556"}
^C
sagars-mac-mini:~ prabhashs$ appium
[Appium] Welcome to Appium v1.5.0-beta8
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session 
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"appPackage":"com.android.calculator2","appActivity":"com.android.calculator2.Calculator","platformName":"Android","udid":"emulator-5556","device...
[Appium] Creating new AndroidDriver session
[BaseDriver] Session created with session id: c55309cb-0105-4fce-ae3a-9f118f25ab06
[debug] [AndroidDriver] Getting Java version
[AndroidDriver] Java version is: 1.8.0_51
[ADB] Checking whether adb is present
[ADB] Using adb from /usr/local/opt/android-sdk/platform-tools/adb
[AndroidDriver] App file was not listed, instead we're going to run com.android.calculator2 directly on the device
[debug] [AndroidDriver] Checking whether package is present on the device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 2 device(s) connected
[debug] [ADB] Running /usr/local/opt/android-sdk/platform-tools/adb with args: ["shell","pm","list","packages","com.android.calculator2"]
[ADB] Error: Error executing adbExec. Original error: Command '/usr/local/opt/android-sdk/platform-tools/adb shell pm list packages com.android.calculator2' exited with code 255{"stdout":"","stderr":"error: more than one device/emulator\n","code":255}
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at ADB.execFunc$ (lib/tools/system-calls.js:188:11)
    at tryCatch (/Users/prabhashs/.nvm/versions/node/v0.12.8/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/prabhashs/.nvm/versions/node/v0.12.8/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/prabhashs/.nvm/versions/node/v0.12.8/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/prabhashs/.nvm/versions/node/v0.12.8/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Users/prabhashs/.nvm/versions/node/v0.12.8/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /Users/prabhashs/.nvm/versions/node/v0.12.8/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/Users/prabhashs/.nvm/versions/node/v0.12.8/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at process._tickCallback (node.js:355:11)
 [Error: Error executing adbExec. Original error: Command '/usr/local/opt/android-sdk/platform-tools/adb shell pm list packages com.android.calculator2' exited with code 255{"stdout":"","stderr":"error: more than one device/emulator\n","code":255}]
[debug] [ADB] Running /usr/local/opt/android-sdk/platform-tools/adb with args: ["shell","pm","list","packages","com.android.calculator2"]
[ADB] Error: Error executing adbExec. Original error: Command '/usr/local/opt/android-sdk/platform-tools/adb shell pm list packages com.android.calculator2' exited with code 255{"stdout":"","stderr":"error: more than one device/emulator\n","code":255}
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at ADB.execFunc$ (lib/tools/system-calls.js:188:11)
    at tryCatch (/Users/prabhashs/.nvm/versions/node/v0.12.8/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/prabhashs/.nvm/versions/node/v0.12.8/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/prabhashs/.nvm/versions/node/v0.12.8/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/prabhashs/.nvm/versions/node/v0.12.8/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Users/prabhashs/.nvm/versions/node/v0.12.8/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /Users/prabhashs/.nvm/versions/node/v0.12.8/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/Users/prabhashs/.nvm/versions/node/v0.12.8/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at process._tickCallback (node.js:355:11)
 [Error: Error executing adbExec. Original error: Command '/usr/local/opt/android-sdk/platform-tools/adb shell pm list packages com.android.calculator2' exited with code 255{"stdout":"","stderr":"error: more than one device/emulator\n","code":255}]
[debug] [AndroidDriver] Shutting down Android driver
[AndroidDriver] Cannot shut down Android driver; it has already shut down
[MJSONWP] Encountered internal error running command: Error: Error executing adbExec. Original error: Command '/usr/local/opt/android-sdk/platform-tools/adb shell pm list packages com.android.calculator2' exited with code 255{"stdout":"","stderr":"error: more than one device/emulator\n","code":255}
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at ADB.execFunc$ (lib/tools/system-calls.js:188:11)
    at tryCatch (/Users/prabhashs/.nvm/versions/node/v0.12.8/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/prabhashs/.nvm/versions/node/v0.12.8/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/prabhashs/.nvm/versions/node/v0.12.8/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/prabhashs/.nvm/versions/node/v0.12.8/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Users/prabhashs/.nvm/versions/node/v0.12.8/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /Users/prabhashs/.nvm/versions/node/v0.12.8/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/Users/prabhashs/.nvm/versions/node/v0.12.8/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at process._tickCallback (node.js:355:11)
[HTTP] <-- POST /wd/hub/session 500 595.789 ms - 386

**Comment by pr4bh4sh** [comment]
https://github.com/appium/appium/issues/5949
