### ISSUE TITLE
Reboot scenario fails due to appium server port getting changed at run time

### ISSUE THREAD

**Issue by email2vimalraj** [appium/appium#5992]
**Appium server**: 1.4.13, **java-client**: 3.3.0, **OS**: Mac 10.10.5 

This is my capability for the real android device:

    platformName: Android
    deviceName:   Android
    app:          debug-app.apk
    newCommandTimeout: 120
    noReset: true

I'm using java-client library and the code you can check here: https://gist.github.com/email2vimalraj/518ec9e1e998f838923a

When the test starts, it runs fine on 4723 port, after the reboot the appium server suddenly switches to 4724 port. Due to this the script waits forever. The partial appium log after reboot successfully executed:

```
info: Starting App
info: [debug] Attempting to kill all 'uiautomator' processes
info: [debug] Getting all processes with 'uiautomator'
info: [debug] executing cmd: /Users/vselvam/Tools/android-sdk-macosx/platform-tools/adb -s 4d00a16bd4e8a1ad shell "ps 'uiautomator'"
info: [debug] No matching processes found
info: [debug] Running bootstrap
info: [debug] spawning: /Users/vselvam/Tools/android-sdk-macosx/platform-tools/adb -s 4d00a16bd4e8a1ad shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.Bootstrap -e pkg com.visa.demos.walletapp -e disableAndroidWatchers false
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
info: [debug] [UIAUTOMATOR STDOUT] io.appium.android.bootstrap.Bootstrap:
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 1
info: [debug] [BOOTSTRAP] [debug] Socket opened on port 4724
info: [debug] [BOOTSTRAP] [debug] Appium Socket Server Ready
info: [debug] [BOOTSTRAP] [debug] Loading json...
error: Unhandled error: Error: connect ECONNREFUSED 127.0.0.1:4724
    at Object.exports._errnoException (util.js:860:11)
    at exports._exceptionWithHostPort (util.js:883:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14) context: [POST /wd/hub/session/56bfb9a8-ba6f-48d8-889f-f3c761bb54a3/appium/app/launch {}]
info: [debug] [BOOTSTRAP] [debug] json loading complete.
info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.
info: <-- POST /wd/hub/session/56bfb9a8-ba6f-48d8-889f-f3c761bb54a3/appium/app/launch - - ms - - 
```

**Comment by scottdixon** [comment]
4724 is Bootstrap, which is expected - Appium isn't switching ports. Interesting that it can't connect. Can you try with the the latest appium beta? `npm install -g appium@beta`

**Comment by email2vimalraj** [comment]
I'll give a try and update here as soon as possible.

**Comment by email2vimalraj** [comment]
I updated to beta and get the following error while and after reboot:

```
[Logcat] Logcat terminated with code 0, signal null
[UiAutomator] UiAutomator exited unexpectedly with code 0, signal null
[debug] [UiAutomator] Moving to state 'stopped'
[debug] [AndroidDriver] Shutting down Android driver
[Appium] Closing session, cause was 'UiAUtomator shut down unexpectedly'
[debug] [ADB] Getting connected devices...
[debug] [ADB] 0 device(s) connected
Unhandled rejection Error: No device connected, cannot run adb shell command "am force-stop com.visa.demos.walletapp"
    at ADB.callee$0$0$ (lib/tools/system-calls.js:197:11)
    at tryCatch (/Users/vselvam/.node/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/vselvam/.node/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/vselvam/.node/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/vselvam/.node/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Users/vselvam/.node/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /Users/vselvam/.node/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/Users/vselvam/.node/lib/node_modules/appium/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at doNTCallback0 (node.js:428:9)
    at process._tickCallback (node.js:357:13)
[HTTP] --> DELETE /wd/hub/session/1b013a09-1486-47d0-928f-7755d30ba1ed 
[HTTP] <-- DELETE /wd/hub/session/1b013a09-1486-47d0-928f-7755d30ba1ed 404 1.165 ms - 131 
```
The session seems to become invalid and couldn't launch app after I reboot the device.

**Comment by email2vimalraj** [comment]
Also when I close the app using `driver.closeApp()`, I get this error:

```
[MJSONWP] Calling AppiumDriver.closeApp() with args: ["997b7b51-b5ae-4cef-944b-7c8c940ccd4c"]
[HTTP] <-- POST /wd/hub/session/997b7b51-b5ae-4cef-944b-7c8c940ccd4c/appium/app/close 501 3.741 ms - 122 
```

**Comment by email2vimalraj** [comment]
Is there any other way of simulating the reboot case using appium?

**Comment by scottdixon** [comment]
What's the output of `adb devices`?

Also can you please provide an entire log as a [gist](http://gist.github.com)

**Comment by email2vimalraj** [comment]
O/P of adb devices:

```
List of devices attached
2035518e	device
```

Entire log gist: https://gist.github.com/email2vimalraj/a4cd1613adb8226198b5.
If you see the log, it clears the appium session after cleaning the android objects.

**Comment by email2vimalraj** [comment]
Finally found the issue. Steps to reproduce the issue:

1. Create the capabilities
2. Create android driver object with the capabilities
3. Trigger reboot
4. Watch `appium session cleans up`.

Example (watch line # 36 and 37 are commented out) : https://gist.github.com/email2vimalraj/9ac0df30fb89d7f924be

The following steps are working fine:

1. Create the capabilities
2. Create android driver object with the capabilities
3. Close the app and launch the app again
4. Trigger reboot
5. Now everything will go smooth

Example (watch line # 36 and 37 are un-commented) : https://gist.github.com/email2vimalraj/518ec9e1e998f838923a

**Comment by email2vimalraj** [comment]
Any help?

**Comment by email2vimalraj** [comment]
Opened the new one since this issue is not being answered for many days.
