### ISSUE TITLE
Call to '/click' throwing Invalid JSON error (Ruby Client + OSX Yosemite + Appium 1.4.16 + iPhone 6)

### ISSUE THREAD

**Issue by tsieprawskipega** [appium/appium#6009]
I am developing rspec tests in ruby using appium framework, and I've found an issue with clicking on items.

Short:

0) Have an application with a button, know its name/xpath/whateva (as seen by appium)
1) `Appium::Driver` and `.start_driver`
2) `driver.find_element` to the button
3) `element.click` - this raises.

In appium stdout/err you can see, this looks like issue with appium server:

```
[36minfo[39m: [37m<-- POST /wd/hub/session/2cc1ec8c-18a5-4c13-b335-5fe99169a1ae/element/0/click [39m[31m500[39m[90m 1033.979 ms - 109[39m [90m[39m
Error: invalid json
    at parse (/usr/local/lib/node_modules/appium/node_modules/body-parser/lib/types/json.js:79:15)
    at /usr/local/lib/node_modules/appium/node_modules/body-parser/lib/read.js:102:18
    at done (/usr/local/lib/node_modules/appium/node_modules/body-parser/node_modules/raw-body/index.js:248:14)
    at IncomingMessage.onEnd (/usr/local/lib/node_modules/appium/node_modules/body-parser/node_modules/raw-body/index.js:294:7)
    at IncomingMessage.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:441:9)
    at process._tickDomainCallback (node.js:396:17)
```

The very same scenario with similar application for Android (activity with a button) works.

I cannot post here my iOS application. If you need it I can post a freshly created one in xcode (with one button), but this is simple you should be able to do it quickly.

See logs here: https://gist.github.com/tsieprawskipega/73aa3284ac692d5e9170
- `repro.sh` is master script that runs everything and produces logs,
- `repro.rb` is example script that reproduces the issue,
- `repro.log` is result of `repro.sh`,
- `appium.log` is result of appium.

**Comment by SrinivasanTarget** [comment]
@KazuCocoa ping

**Comment by dpgraham** [comment]
Looks like a client issue.

**Comment by KazuCocoa** [comment]
Current `rury_lib` uses `selenium-webdriver-3.x`, and the error looks parsing JSON error by `selenium-webdriver-2.48.1`.

```
[36minfo[39m: [37m-->[39m [37mPOST[39m [37m/wd/hub/session/2cc1ec8c-18a5-4c13-b335-5fe99169a1ae/element/0/click[39m [90m{}[39m
[36minfo[39m: [debug] Pushing command to appium work queue: "au.getElement('0').rect()"
[36minfo[39m: [debug] Sending command to instruments: au.getElement('0').rect()
[36minfo[39m: [debug] [32m[INST] 2016-01-12 10:24:11 +0000 Debug: Got new command 5 from instruments: au.getElement('0').rect()[39m
[36minfo[39m: [debug] [32m[INST] 2016-01-12 10:24:11 +0000 Debug: evaluating au.getElement('0').rect()
       2016-01-12 10:24:11 +0000 Debug: evaluation finished[39m
[36minfo[39m: [debug] [32m[INST] 2016-01-12 10:24:11 +0000 Debug: responding with:[39m
[36minfo[39m: [debug] Socket data received (83 bytes)
[36minfo[39m: [debug] Socket data being routed.
[36minfo[39m: [debug] Got result from instruments: {"status":0,"value":{"origin":{"x":38,"y":528},"size":{"width":244,"height":34}}}
[36minfo[39m: [37m<-- POST /tap [39m[31m500[39m[90m 3.861 ms - 66[39m [90m[39m
[36minfo[39m: [debug] Responding to client with error: {"status":1,"value":{"message":"undefined status object"},"sessionId":"2cc1ec8c-18a5-4c13-b335-5fe99169a1ae"}
[36minfo[39m: [37m<-- POST /wd/hub/session/2cc1ec8c-18a5-4c13-b335-5fe99169a1ae/element/0/click [39m[31m500[39m[90m 1033.979 ms - 109[39m [90m[39m
Error: invalid json
    at parse (/usr/local/lib/node_modules/appium/node_modules/body-parser/lib/types/json.js:79:15)
    at /usr/local/lib/node_modules/appium/node_modules/body-parser/lib/read.js:102:18
    at done (/usr/local/lib/node_modules/appium/node_modules/body-parser/node_modules/raw-body/index.js:248:14)
    at IncomingMessage.onEnd (/usr/local/lib/node_modules/appium/node_modules/body-parser/node_modules/raw-body/index.js:294:7)
    at IncomingMessage.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:441:9)
    at process._tickDomainCallback (node.js:396:17)
```

---

```
/Library/Ruby/Gems/2.0.0/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/response.rb:70:in `assert_ok': undefined status object (Selenium::WebDriver::Error::IndexOutOfBoundsError)
	from /Library/Ruby/Gems/2.0.0/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/http/common.rb:78:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/http/common.rb:78:in `create_response'
	from /Library/Ruby/Gems/2.0.0/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/http/default.rb:90:in `request'
	from /Library/Ruby/Gems/2.0.0/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/bridge.rb:664:in `raw_execute'
	from /Library/Ruby/Gems/2.0.0/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/bridge.rb:642:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/bridge.rb:404:in `clickElement'
	from /Library/Ruby/Gems/2.0.0/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/common/element.rb:73:in `click'
	from repro.rb:23:in `<main>'
```

**Comment by KazuCocoa** [comment]
We can close this if server side works fine because of ^.
@SrinivasanTarget @dpgraham Could you close this? I have no permission to close this repository's issues.
