### ISSUE TITLE
Beta1.5@11 MainActivity fails to be detected on Android. Tests fail to start.

### ISSUE THREAD

**Issue by apallin** [appium/appium#6020]
On version Beta1.5@11, Appium is failing to detect the launched application even though it does come up on the device.  This is not repeatable on 1.4.16 with the same App.

There is a similar issue open here:https://github.com/appium/appium/issues/5936

Reproduction:
1. Launch v1.5-beta11 appium.
2. Start test session.
3. Observer failure and MainActivity never detected even though App launches successfully.

We are failing with this stack trace, link to full gist here https://gist.github.com/apallin/3cf99dbe8bad93a161c3
```
[ADB] Error: me.APPNAME.android.dev/.me.APPNAME.android.ui.MainActivity never started
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at ADB.callee$0$0$ (lib/tools/apk-utils.js:130:7)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /usr/local/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at process._tickCallback (node.js:355:11)
 [Error: me.APPNAME.android.dev/.me.APPNAME.android.ui.MainActivity never started]
[ADB] Error: Error occured while starting App. Original error: me.APPNAME.android.dev/.me.APPNAME.android.ui.MainActivity never started
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at ADB.callee$0$0$ (lib/tools/apk-utils.js:80:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /usr/local/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at process._tickCallback (node.js:355:11)
 [Error: Error occured while starting App. Original error: me.APPNAME.android.dev/.me.APPNAME.android.ui.MainActivity never started]
```

**Comment by moizjv** [comment]
closing as duplicate
