### ISSUE TITLE
Appium 1.4.16 Failed to start an Appium session, err was: Error: Requested a new session but one was in progress

### ISSUE THREAD

**Issue by SashaWein** [appium/appium#6047]
Hello, 
I am running tests on android device with selenium grid (from remote host).
Chromedriver 2.20, android 4.4, selenium driver 2.48, latest adb.
After running one test appium fails to create another session with the mentioned error.
"Failed to start an Appium session, err was: Error: Requested a new session but one was in progress"
There are several adb.exe processes that are not killed after each test execution so I tried to kill them explicitly after calling driver.quit().This seems to solve the problem but not 100%. In some cases it still fails with the same error.
I tried to set the --session-override flag on the server, but it still fails just with different error
"Failed to start an Appium session, err was: TypeError: Cannot read property 'done' of undefined"
It would be great if someone can help me with this.
Thank in advance!
Here are some relevant logs
2016-01-20 08:47:08:039 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}}}
2016-01-20 08:47:08:039 - info: <-- GET /wd/hub/status 200 2.080 ms - 105 {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}}}
2016-01-20 08:47:12:425 - info: --> POST /wd/hub/session {"desiredCapabilities":{"newCommandTimeout":150,"platform":"ANDROID","app":"chrome","platformVersion":"4.2.2","platformName":"Android","deviceName":"Dan","browserName":"chrome","version":"4.2.2"}}
2016-01-20 08:47:12:425 - info: Client User-Agent string: Apache-HttpClient/4.5.1 (Java/1.7.0_71)
2016-01-20 08:47:12:425 - info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : platform, version
2016-01-20 08:47:12:425 - info: Set mode: Proxying straight through to Chromedriver
2016-01-20 08:47:12:425 - info: [debug] Looks like we want chrome on android
2016-01-20 08:47:12:440 - info: [debug] Creating new appium session 754247a7-fa53-4ff2-bb68-3c5aa6db508b
2016-01-20 08:47:12:440 - info: [debug] Checking whether adb is present
2016-01-20 08:47:12:440 - info: [debug] Using adb from C:\appiumTryout\sdk\platform-tools\adb.exe
2016-01-20 08:47:12:440 - info: [debug] Using fast reset? true
2016-01-20 08:47:12:456 - info: [debug] Preparing device for session
2016-01-20 08:47:12:456 - info: [debug] Not checking whether app is present since we are assuming it's already on the device
2016-01-20 08:47:12:456 - info: Retrieving device
2016-01-20 08:47:12:456 - info: [debug] Trying to find a connected android device
2016-01-20 08:47:12:456 - info: [debug] Getting connected devices...
2016-01-20 08:47:12:472 - info: [debug] executing cmd: C:\appiumTryout\sdk\platform-tools\adb.exe devices
2016-01-20 08:47:13:049 - info: --> GET /wd/hub/status {}
2016-01-20 08:47:13:049 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}},"sessionId":"754247a7-fa53-4ff2-bb68-3c5aa6db508b"}
2016-01-20 08:47:13:049 - info: <-- GET /wd/hub/status 200 2.044 ms - 156 {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}},"sessionId":"754247a7-fa53-4ff2-bb68-3c5aa6db508b"}
2016-01-20 08:47:16:621 - info: [debug] 1 device(s) connected
2016-01-20 08:47:16:621 - info: Found device 32001955094f8000
2016-01-20 08:47:16:621 - info: [debug] Setting device id to 32001955094f8000
2016-01-20 08:47:16:621 - info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
2016-01-20 08:47:16:621 - info: [debug] executing cmd: C:\appiumTryout\sdk\platform-tools\adb.exe -s 32001955094f8000 wait-for-device
2016-01-20 08:47:16:684 - info: [debug] executing cmd: C:\appiumTryout\sdk\platform-tools\adb.exe -s 32001955094f8000 shell "echo 'ready'"
2016-01-20 08:47:16:746 - info: [debug] Starting logcat capture
2016-01-20 08:47:16:777 - info: [debug] Pushing unlock helper app to device...
2016-01-20 08:47:16:777 - info: [debug] executing cmd: C:\appiumTryout\sdk\platform-tools\adb.exe -s 32001955094f8000 install "C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\build\unlock_apk\unlock_apk-debug.apk"
2016-01-20 08:47:17:822 - info: [debug] executing cmd: C:\appiumTryout\sdk\platform-tools\adb.exe -s 32001955094f8000 shell "dumpsys window"
2016-01-20 08:47:17:947 - info: [debug] Screen already unlocked, continuing.
2016-01-20 08:47:17:947 - info: [debug] Forwarding system:4724 to device:4724
2016-01-20 08:47:17:947 - info: [debug] executing cmd: C:\appiumTryout\sdk\platform-tools\adb.exe -s 32001955094f8000 forward tcp:4724 tcp:4724
2016-01-20 08:47:18:010 - info: [debug] Pushing appium bootstrap to device...
2016-01-20 08:47:18:010 - info: [debug] executing cmd: C:\appiumTryout\sdk\platform-tools\adb.exe -s 32001955094f8000 push "C:\\Users\\adm\\Desktop\\AppiumForWindows\\node_modules\\appium\\build\\android_bootstrap\\AppiumBootstrap.jar" /data/local/tmp/
2016-01-20 08:47:18:056 - info: --> GET /wd/hub/status {}
2016-01-20 08:47:18:056 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}},"sessionId":"754247a7-fa53-4ff2-bb68-3c5aa6db508b"}
2016-01-20 08:47:18:056 - info: <-- GET /wd/hub/status 200 5.324 ms - 156 {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}},"sessionId":"754247a7-fa53-4ff2-bb68-3c5aa6db508b"}
2016-01-20 08:47:18:119 - info: Starting App
2016-01-20 08:47:18:119 - info: [debug] Attempting to kill all 'uiautomator' processes
2016-01-20 08:47:18:119 - info: [debug] Getting all processes with 'uiautomator'
2016-01-20 08:47:18:119 - info: [debug] executing cmd: C:\appiumTryout\sdk\platform-tools\adb.exe -s 32001955094f8000 shell "ps 'uiautomator'"
2016-01-20 08:47:18:212 - info: [debug] No matching processes found
2016-01-20 08:47:18:212 - info: [debug] Running bootstrap
2016-01-20 08:47:18:228 - info: [debug] spawning: C:\appiumTryout\sdk\platform-tools\adb.exe -s 32001955094f8000 shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.Bootstrap -e pkg com.android.chrome -e disableAndroidWatchers false
2016-01-20 08:47:18:868 - info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
2016-01-20 08:47:18:883 - info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
2016-01-20 08:47:18:883 - info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
2016-01-20 08:47:18:883 - info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
2016-01-20 08:47:18:883 - info: [debug] [UIAUTOMATOR STDOUT] io.appium.android.bootstrap.Bootstrap:
2016-01-20 08:47:18:883 - info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
2016-01-20 08:47:18:883 - info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
2016-01-20 08:47:18:899 - info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 1
2016-01-20 08:47:18:914 - info: [debug] [BOOTSTRAP] [debug] Socket opened on port 4724
2016-01-20 08:47:18:914 - info: [debug] [BOOTSTRAP] [debug] Appium Socket Server Ready
2016-01-20 08:47:18:914 - info: [debug] [BOOTSTRAP] [debug] Loading json...
2016-01-20 08:47:18:930 - info: [debug] Pushing command to appium work queue: ["getDataDir",{}]
2016-01-20 08:47:18:930 - info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.
2016-01-20 08:47:18:930 - info: [debug] [BOOTSTRAP] [debug] Client connected
2016-01-20 08:47:18:930 - info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"getDataDir","params":{}}
2016-01-20 08:47:18:946 - info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
2016-01-20 08:47:18:946 - info: [debug] [BOOTSTRAP] [debug] Got command action: getDataDir
2016-01-20 08:47:18:946 - info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"\/data\/local\/tmp","status":0}
2016-01-20 08:47:18:946 - info: [debug] dataDir set to: /data/local/tmp
2016-01-20 08:47:18:961 - info: Chromedriver: Changed state to 'starting'
2016-01-20 08:47:18:961 - info: Chromedriver: Set chromedriver binary as: C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe
2016-01-20 08:47:18:961 - info: Chromedriver: Killing any old chromedrivers, running: FOR /F "usebackq tokens=5" %a in (`netstat -nao ^| findstr /R /C:"9515 "`) do (FOR /F "usebackq" %b in (`TASKLIST /FI "PID eq %a" ^| findstr /I chromedriver.exe`) do (IF NOT %b=="" TASKKILL /F /PID %a))
2016-01-20 08:47:23:064 - info: --> GET /wd/hub/status {}

2016-01-20 08:49:26:272 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}},"sessionId":"754247a7-fa53-4ff2-bb68-3c5aa6db508b"}
2016-01-20 08:49:26:272 - info: <-- GET /wd/hub/status 200 2.131 ms - 156 {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}},"sessionId":"754247a7-fa53-4ff2-bb68-3c5aa6db508b"}
2016-01-20 08:49:26:430 - info: <-- POST /wd/hub/session - - ms - - 
2016-01-20 08:49:26:742 - info: --> POST /wd/hub/session {"desiredCapabilities":{"newCommandTimeout":150,"platform":"ANDROID","app":"chrome","platformVersion":"4.2.2","platformName":"Android","deviceName":"Dan","browserName":"chrome","version":"4.2.2"}}
2016-01-20 08:49:26:742 - info: Client User-Agent string: Apache-HttpClient/4.5.1 (Java/1.7.0_71)
2016-01-20 08:49:26:758 - error: Failed to start an Appium session, err was: Error: Requested a new session but one was in progress
2016-01-20 08:49:26:820 - info: [debug] Error: Requested a new session but one was in progress
    at [object Object].Appium.start (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\lib\appium.js:139:15)
    at exports.createSession (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\lib\server\controller.js:188:16)
    at Layer.handle [as handle_request] (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\layer.js:82:5)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:110:13)
    at Route.dispatch (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:91:3)
    at Layer.handle [as handle_request] (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\layer.js:82:5)
    at C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\index.js:267:22
    at Function.proto.process_params (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\index.js:321:12)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\index.js:261:10)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:100:14)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
    at C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\lib\server\controller.js:39:7
    at Layer.handle [as handle_request] (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\layer.js:82:5)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:110:13)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
    at Route.dispatch (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:91:3)
    at Layer.handle [as handle_request] (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\layer.js:82:5)
    at C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\index.js:267:22
    at Function.proto.process_params (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\index.js:321:12)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\index.js:261:10)
    at methodOverride (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\method-override\index.js:79:5)
    at Layer.handle [as handle_request] (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\layer.js:82:5)
    at trim_prefix (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\index.js:302:13)
    at C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\index.js:270:7
    at Function.proto.process_params (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\index.js:321:12)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\index.js:261:10)
    at logger (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\morgan\index.js:136:5)
    at Layer.handle [as handle_request] (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\layer.js:82:5)
    at trim_prefix (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\index.js:302:13)
    at C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\index.js:270:7
    at Function.proto.process_params (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\index.js:321:12)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\index.js:261:10)
    at C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\body-parser\lib\read.js:111:5
    at done (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\body-parser\node_modules\raw-body\index.js:248:14)
    at IncomingMessage.onEnd (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\body-parser\node_modules\raw-body\index.js:294:7)
    at IncomingMessage.g (events.js:199:16)
    at IncomingMessage.emit (events.js:104:17)
    at _stream_readable.js:908:16
    at process._tickDomainCallback (node.js:381:11)
2016-01-20 08:49:26:820 - info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Requested a new session but one was in progress)","origValue":"Requested a new session but one was in progress"},"sessionId":"754247a7-fa53-4ff2-bb68-3c5aa6db508b"}
2016-01-20 08:49:26:836 - info: <-- POST /wd/hub/session 500 80.705 ms - 250 
2016-01-20 08:49:27:119 - info: --> POST /wd/hub/session {"desiredCapabilities":{"newCommandTimeout":150,"platform":"ANDROID","app":"chrome","platformVersion":"4.2.2","platformName":"Android","deviceName":"Dan","browserName":"chrome","version":"4.2.2"}}
2016-01-20 08:49:27:119 - info: Client User-Agent string: Apache-HttpClient/4.5.1 (Java/1.7.0_71)
2016-01-20 08:49:27:119 - error: Failed to start an Appium session, err was: Error: Requested a new session but one was in progress
2016-01-20 08:49:27:197 - info: [debug] Error: Requested a new session but one was in progress
    at [object Object].Appium.start (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\lib\appium.js:139:15)
    at exports.createSession (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\lib\server\controller.js:188:16)
    at Layer.handle [as handle_request] (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\layer.js:82:5)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:110:13)
    at Route.dispatch (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:91:3)
    at Layer.handle [as handle_request] (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\layer.js:82:5)
    at C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\index.js:267:22
    at Function.proto.process_params (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\index.js:321:12)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\index.js:261:10)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:100:14)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
    at C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\lib\server\controller.js:39:7
    at Layer.handle [as handle_request] (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\layer.js:82:5)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:110:13)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
    at Route.dispatch (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\route.js:91:3)
    at Layer.handle [as handle_request] (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\layer.js:82:5)
    at C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\index.js:267:22
    at Function.proto.process_params (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\index.js:321:12)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\index.js:261:10)
    at methodOverride (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\method-override\index.js:79:5)
    at Layer.handle [as handle_request] (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\layer.js:82:5)
    at trim_prefix (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\index.js:302:13)
    at C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\index.js:270:7
    at Function.proto.process_params (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\index.js:321:12)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\index.js:261:10)
    at logger (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\morgan\index.js:136:5)
    at Layer.handle [as handle_request] (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\layer.js:82:5)
    at trim_prefix (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\index.js:302:13)
    at C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\index.js:270:7
    at Function.proto.process_params (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\index.js:321:12)
    at next (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\express\lib\router\index.js:261:10)
    at C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\body-parser\lib\read.js:111:5
    at done (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\body-parser\node_modules\raw-body\index.js:248:14)
    at IncomingMessage.onEnd (C:\Users\adm\Desktop\AppiumForWindows\node_modules\appium\node_modules\body-parser\node_modules\raw-body\index.js:294:7)
    at IncomingMessage.g (events.js:199:16)
    at IncomingMessage.emit (events.js:104:17)
    at _stream_readable.js:908:16
    at process._tickDomainCallback (node.js:381:11)
2016-01-20 08:49:27:197 - info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Requested a new session but one was in progress)","origValue":"Requested a new session but one was in progress"},"sessionId":"754247a7-fa53-4ff2-bb68-3c5aa6db508b"}

**Comment by mehmetboraezer** [comment]
Please read this issue #5938. Maybe this solution will resolve your problem.
