### ISSUE TITLE
Cannot ommit "app" capability when setting "bundleId" for iOS in 1.5.0-beta11

### ISSUE THREAD

**Issue by cthorell** [appium/appium#6051]
Appium for iOS no longer works when setting only the "bundleId" capability, and always expect to receive an "app" capability. 
This used to work with Apium 1.3.x and 1.4.x, in accordance to http://appium.io/slate/en/master/ "To run a test on a real device using the bundle ID, you may omit the ‘app’ capability, but you must provide ‘udid’."

Capabilities:

{"deviceName":"iPhone",
 "udid": "b3a6c616f49783d9455f0e1fbf124704a7f08482",
 "autoAcceptAlerts":True,
 "bundleId":"com.example.Test",
 "autoLaunch":True,
 "browserName":"",
 "newCommandTimeout":99999,
 "platformName":"iOS",
}

Logs:

$ appium --session-override --no-reset --address 127.0.0.1  --command-timeout 99999
[Appium] Welcome to Appium v1.5.0-beta11 (REV 0ca777677c46bad4429f548706096d859130178f)
[Appium] Non-default server args:
[Appium]   address: '127.0.0.1'
[Appium]   sessionOverride: true
[Appium]   defaultCommandTimeout: 99999
[Appium]   noReset: true
[Appium] Deprecated server args:
[Appium]   --no-reset => --default-capabilities '{"noReset":true}'
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   noReset: true
[Appium] Appium REST http interface listener started on 127.0.0.1:4723
[HTTP] --> POST /wd/hub/session 
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"deviceName":"iPhone","udid":"b3a6c616f49783d9455f0e1fbf124704a7f08482","autoAcceptAlerts":true,"browserName":"","autoLaunch":true,"newCommandTim...
[Appium] Creating new IosDriver session
[Appium] Capabilities:
[Appium]   deviceName: 'iPhone'
[Appium]   udid: 'b3a6c616f49783d9455f0e1fbf124704a7f08482'
[Appium]   autoAcceptAlerts: true
[Appium]   browserName: ''
[Appium]   autoLaunch: true
[Appium]   newCommandTimeout: 99999
[Appium]   platformName: 'iOS'
[Appium]   bundleId: 'com.example.Test'
[Appium]   noReset: true
[BaseDriver] Session created with session id: ce337b2f-cb48-441a-ba1f-ef291b2a7630
[debug] [iOS] Not auto-detecting udid.
[debug] [Support] Attempting to parse plist file '/Applications/Xcode.app/Contents/Info.plist'
[debug] [Support] Parsed plist file as binary
[debug] [iOS] Removing any remaining instruments sockets
[debug] [iOS] Cleaned up instruments socket /var/folders/1y/3ml_tzhd51j5nqkl829w88x80000gn/T/instruments_sock
[debug] [iOS] Localizable.strings is not currently supported when using real devices.
[debug] [ios-app-utils] Getting application name from app
[iOS] Could not set the appName from app 'undefined'
[MJSONWP] Encountered internal error running command: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.posix.resolve (path.js:426:5)
    at extractPlist$ (lib/extract.js:10:24)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at new Promise (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:197:7)
    at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at extractPlist (lib/extract.js:10:16)
    at extractPlistEntry$ (lib/extract.js:20:31)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at new Promise (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:197:7)
    at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at extractPlistEntry (lib/extract.js:18:49)
    at extractAppDisplayName$ (lib/appname.js:7:16)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at new Promise (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:197:7)
    at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
[HTTP] <-- POST /wd/hub/session 500 111.354 ms - 178

**Comment by SrinivasanTarget** [comment]
@imurchie Looks like a valid bug.As per our doc's --app is an optional parameter and in ios-app-utils we are in need of app name - https://github.com/appium/ios-app-utils/blob/master/lib/appname.js.

Looking into this now.

**Comment by SrinivasanTarget** [comment]
@imurchie https://github.com/appium/ios-app-utils/blob/master/lib/extract.js needs appname. I think this could be the issue. Working on the fix now.

**Comment by imurchie** [comment]
We no longer need to get the app name in ios driver. The fix is to remove that call altogether.

**Comment by SrinivasanTarget** [comment]
(y)

**Comment by SrinivasanTarget** [comment]
I believe we can close this issue @moizjv
