### ISSUE TITLE
Killing existing chromedrivers hangs.

### ISSUE THREAD

**Issue by rolandoldengarm** [appium/appium#6053]
While running tests using Protractor + Appium, sometimes Appium gets stuck at killing existing Chromedrivers:

info: Chromedriver: Changed state to 'starting'
info: Chromedriver: Set chromedriver binary as: /chromedriver/chromedriver.exe
info: Chromedriver: Killing any old chromedrivers, running: FOR /F "usebackq tokens=5" %a in (`netstat -nao ^| findstr /R /C:"9515 "`) do (FOR /F "usebackq" %b in (`TASKLIST /FI "PID eq %a" ^| findstr /I chromedriver.exe`) do (IF NOT %b=="" TASKKILL /F /PID %a))

It just hangs. It only helps to restart everything and start again.
I've checked task manager, there is no chromedriver.exe running

Running on Windows 10.

**Comment by moizjv** [comment]
Ca you try using appium 1.5 we have made few changes on how we interact with chrome driver

**Comment by rolandoldengarm** [comment]
Hi @moizjv thank you. Where can I download 1.5? The NPM package is still 1.4.x, and on the downloads section on your site I can only find 1.4.x of the Windows client...
https://bitbucket.org/appium/appium.app/downloads/

**Comment by rolandoldengarm** [comment]
@moizjv I've tried for a while to get 1.5 working on my machine, but it does not work. See related issue: https://github.com/appium/appium/issues/6065

**Comment by rolandoldengarm** [comment]
I have just let it run for a while longer, and it continues (verified in latest 1.4). 

However, it is still weird that it takes such a long time? It takes about 2 minutes, while there are no chromedriver.exe processes.

**Comment by rolandoldengarm** [comment]
Any news on this?

**Comment by prashantshukla-qait** [comment]
Hey @imurchie , I am still seeing this error. Can you please tell me what I can do to fix this.

Please refer to @rolandoldengarm's comment on Feb 1st. That is the exact thing that happens with me.
Thanks

**Comment by imurchie** [comment]
Given that that was well over a year ago, much has changed. Without the Appium server logs (as a link to a [gist](https://gist.github.com)) there is nothing that can be said.

**Comment by PrintKopytko** [comment]
I experienced the same issue on Appium 1.7.1. It occurs only when running Appium on Windows, not on Mac. It happens when I run the same testcase several times. This errors appears during every second execution, 2nd, 4th and so on. 
A part of logs where something goes wrong
`2017-12-07 10:59:26:275 - [debug] [AndroidDriver] A port was not given, using random port: 8000
2017-12-07 10:59:26:275 - [debug] [Chromedriver] Changed state to 'starting'
2017-12-07 10:59:26:276 - [Chromedriver] Set chromedriver binary as: C:\Users\patko\AppData\Roaming\npm\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe
2017-12-07 10:59:26:276 - [debug] [Chromedriver] Killing any old chromedrivers, running: FOR /F "usebackq tokens=5" %a in (`netstat -nao ^| findstr /R /C:"8000 "`) do (FOR /F "usebackq" %b in (`TASKLIST /FI "PID eq %a" ^| findstr /I chromedriver.exe`) do (IF NOT %b=="" TASKKILL /F /PID %a))
2017-12-07 11:01:18:545 - [HTTP] <-- POST /wd/hub/session - - ms - - 
2017-12-07 11:01:54:556 - [Appium] Received SIGINT - shutting down
2017-12-07 11:01:54:562 - [Logcat] Logcat terminated with code 3221225786, signal null
2017-12-07 11:01:54:562 - [UiAutomator] UiAutomator exited unexpectedly with code 3221225786, signal null
2017-12-07 11:01:54:562 - [debug] [UiAutomator] Moving to state 'stopped'
2017-12-07 11:01:54:571 - [debug] [AndroidDriver] Shutting down Android driver
2017-12-07 11:01:54:571 - [debug] [AndroidDriver] Resetting IME to io.appium.android.ime/.UnicodeIME
2017-12-07 11:01:54:571 - [debug] [ADB] Getting connected devices...
2017-12-07 11:01:54:640 - [debug] [ADB] 1 device(s) connected`

then AndroidDriver thrown the following error:
Connection to AppiumServer failed. 
OpenQA.Selenium.WebDriverException: A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL http://localhost:4723/wd/hub/session. The status of the exception was ConnectionClosed, and the message was: The underlying connection was closed: The connection was closed unexpectedly. ---> System.Net.WebException: The underlying connection was closed: The connection was closed unexpectedly.
   at System.Net.HttpWebRequest.GetResponse()
   at OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request)
   --- End of inner exception stack trace ---
   at OpenQA.Selenium.Appium.Service.AppiumCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Appium.AppiumDriver`1.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Appium.Android.AndroidDriver`1..ctor(Uri remoteAddress, DesiredCapabilities desiredCapabilities, TimeSpan commandTimeout)

I ask @imurchie to reopen the ticket. Below you can find a log file containing 2 executions. first one was successful, second not. Please note lines 160 and 10892. There chromedriver actions begin
[log_clean.txt](https://github.com/appium/appium/files/1539275/log_clean.txt)

Enviornment:
Appium 1.7.1
Windows 10
Android 6 real device, Android 7 emulator

**Comment by PrintKopytko** [comment]
I found a solution to my problem. I set TcpTimedWaitDelay in Windows registry editor to 10. The manual how to do it can be found here https://www.ibm.com/support/knowledgecenter/en/SSRTHY_8.5.0/com.ibm.installingirm.doc/rminst0231.htm
