### ISSUE TITLE
1.5.0-beta11 SessionNotCreatedError thrown when platformName capability is defined as 'android' instead of 'Android'

### ISSUE THREAD

**Issue by JaniJegoroff** [appium/appium#6055]
Steps to reproduce:
1. Define `platformName` capability as `android` instead of `Android`
2. Launch Appium server 1.5.0-beta11
3. Launch your Android tests

Appium server 1.4.16 is working fine in above use case.

```
[Appium] Welcome to Appium v1.5.0-beta11 (REV 300441be033c7e47ae26de29137aa985ad7169d4)
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> GET /wd/hub/status
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.0-beta11","revision":"300441be033c7e47ae26de29137aa985ad7169d4"}}
[HTTP] <-- GET /wd/hub/status 200 19.073 ms - 128
[HTTP] --> POST /wd/hub/session
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"android","deviceName":"XXXXX","app":"/Users/janijegoroff/projects/mobile-android-app/bdd/app-local-debug.apk","newCommandTimeout"...
[Appium] Creating new AndroidDriver session
[Appium] Capabilities:
[Appium]   platformName: 'android'
[Appium]   deviceName: 'XXXXX'
[Appium]   app: '/Users/janijegoroff/projects/mobile-android-app/bdd/app-local-debug.apk'
[Appium]   newCommandTimeout: 999999
[BaseDriver] SessionNotCreatedError: A new session could not be created. Details: The desiredCapabilities object was not valid for the following reason(s): platformName android is not included in the list.
    at AndroidDriver.validateDesiredCaps (lib/driver.js:120:25)
    at AndroidDriver.validateDesiredCaps (lib/driver.js:28:20)
    at AndroidDriver.callee$0$0$ (lib/commands/session.js:13:8)
```

**Comment by JaniJegoroff** [comment]
Same applies to `ios` versus `iOS`

```
Appium] Welcome to Appium v1.5.0-beta11 (REV d19c85fa5aa8359ea81f5fbe8c3fe977b45ea526)
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"ios","platformVersion":"9.2","deviceName":"iPhone Simulator","app":"/Users/janijegoroff/projects/ruby_lib/ios_tests/UICatalog.app...
[Appium] Creating new IosDriver session
[Appium] Capabilities:
[Appium]   platformName: 'ios'
[Appium]   platformVersion: '9.2'
[Appium]   deviceName: 'iPhone Simulator'
[Appium]   app: '/Users/janijegoroff/projects/ruby_lib/ios_tests/UICatalog.app'
[BaseDriver] SessionNotCreatedError: A new session could not be created. Details: The desiredCapabilities object was not valid for the following reason(s): platformName ios is not included in the list.
    at IosDriver.validateDesiredCaps (lib/driver.js:120:25)
    at IosDriver.validateDesiredCaps (lib/driver.js:41:16)
    at IosDriver.callee$0$0$ (lib/commands/session.js:13:8)
```

**Comment by moizjv** [comment]
looks like an issue; let me confirm this

**Comment by SrinivasanTarget** [comment]
@moizjv @imurchie Error occurs while validating the "platformname" with "desiredCapabilityConstraints" in https://github.com/appium/appium-base-driver/blob/master/lib/driver.js#L107. I believe this issue will occur for automationName and orientation because of case sensitivity.

I think we need to include matches function (validator.validators.matches) in https://github.com/appium/appium-base-driver/blob/master/lib/desired-caps.js#L96 
correct me if i'm wrong.

If right, let me know how to include case sensitivity check here.

**Comment by moizjv** [comment]
@SrinivasanTarget https://github.com/appium/appium-base-driver/pull/43
