### ISSUE TITLE
1.5.0-beta11. Android: Not every UIAutomator selector works.

### ISSUE THREAD

**Issue by TikhomirovSergey** [appium/appium#6087]
Client code sample:

```java
     AppiumDriverLocalService service = AppiumDriverLocalService.buildDefaultService();
     service.start();

    File appDir = new File("src/test/java/io/appium/java_client");
    File app = new File(appDir, "ApiDemos-debug.apk");
    DesiredCapabilities capabilities = new DesiredCapabilities();
    capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "");
    capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "Android Emulator");
    capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, MobilePlatform.ANDROID);
    capabilities.setCapability(MobileCapabilityType.APP, app.getAbsolutePath());
    driver = new AndroidDriver<AndroidElement>(service.getUrl(), capabilities);

...

  @Test
  public void tezt() {
    driver.findElementByAndroidUIAutomator("" +
            "new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().description(\"Views\").instance(0))" /*+
            "new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().text(\"Views\").instance(0));"*/);
  }
```
Error stacktrace:

```
org.openqa.selenium.UnsupportedCommandException: The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 621 milliseconds
Build info: version: '2.50.0', revision: '1070ace4650453d518aeb03e7a9a36c9d264a8e7', time: '2016-01-27 10:46:18'
System info: host: 'spb-STikhomirov', ip: '172.31.16.7', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_71'
*** Element info: {Using=-android uiautomator, value=new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().description("Views").instance(0))}
Session ID: 6baa1f1a-f200-4199-9e9a-55714e0b07a2
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{platformVersion=4.4.4, app=C:\appium\java-client\src\test\java\io\appium\java_client\ApiDemos-debug.apk, platform=LINUX, databaseEnabled=false, javascriptEnabled=true, platformName=Android, deviceName=emulator-5554, browserName=, webStorageEnabled=false, networkConnectionEnabled=true, desired={app=C:\..\java_client\ApiDemos-debug.apk, platformName=Android, deviceName=Android Emulator, browserName=}, locationContextEnabled=false, warnings={}, takesScreenshot=true}]

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
...
```

Server output:
https://gist.github.com/TikhomirovSergey/8ae0d8a514c99bee3c29

Please pay attention: https://gist.github.com/TikhomirovSergey/8ae0d8a514c99bee3c29#file-server-output-L156

This code worked fine with server v<=1.4.16

**Comment by TikhomirovSergey** [comment]
https://github.com/appium/java-client/issues/302

**Comment by imurchie** [comment]
Thanks! Looking into this.

**Comment by imurchie** [comment]
Fixed this in the bootstrap code. I will closet his once it is in and published.

https://github.com/appium/appium-android-bootstrap/pull/14

**Comment by imurchie** [comment]
The fix is now in `appium-android-driver`, and will be soon in Appium 1.5 branch.
