### ISSUE TITLE
1.5.0-beta11. Android: Is pressKeyCode broken or deprecated?

### ISSUE THREAD

**Issue by TikhomirovSergey** [appium/appium#6088]
Client code sample:

```java
     service = AppiumDriverLocalService.buildDefaultService();
     service.start();

    File appDir = new File("src/test/java/io/appium/java_client");
    File app = new File(appDir, "ApiDemos-debug.apk");
    DesiredCapabilities capabilities = new DesiredCapabilities();
    capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "");
    capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "Android Emulator");
    capabilities.setCapability(MobileCapabilityType.APP, app.getAbsolutePath());
    driver = new AndroidDriver<>(service.getUrl(), capabilities);

   ...
    driver.pressKeyCode(AndroidKeyCode.BACK);   
```

Stacktrace:
```
org.openqa.selenium.UnsupportedCommandException: Parameters were incorrect. We wanted {"required":["keycode","metastate"]} and you sent ["keycode"]
Command duration or timeout: 7 milliseconds
Build info: version: '2.50.0', revision: '1070ace4650453d518aeb03e7a9a36c9d264a8e7', time: '2016-01-27 10:46:18'
System info: host: 'spb-STikhomirov', ip: '172.31.16.7', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_71'
Session ID: 86c50457-f3b1-4412-9166-2fca328a4f43
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{platformVersion=4.4.4, app=C:\appium\java-client\src\test\java\io\appium\java_client\ApiDemos-debug.apk, platform=LINUX, databaseEnabled=false, javascriptEnabled=true, deviceName=emulator-5554, platformName=Android, browserName=, webStorageEnabled=false, networkConnectionEnabled=true, desired={app=C:\appium\java-client\src\test\java\io\appium\java_client\ApiDemos-debug.apk, deviceName=Android Emulator, platformName=Android, browserName=}, locationContextEnabled=false, warnings={}, takesScreenshot=true}]

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
```

Server output
https://gist.github.com/TikhomirovSergey/fa5304adc78079e3be99

Pay attention:
https://gist.github.com/TikhomirovSergey/fa5304adc78079e3be99#file-gistfile1-txt-L512

**Comment by TikhomirovSergey** [comment]
https://github.com/appium/java-client/issues/302
https://github.com/appium/appium-dotnet-driver/issues/136

**Comment by TikhomirovSergey** [comment]
is the duplicate
