### ISSUE TITLE
Server crashes after openNotifications function

### ISSUE THREAD

**Issue by S4KH** [appium/appium#6093]
**Environment:**
OS: MAC
Appium version 1.4.16. 
TestNG(6.8.8) for writing tests. 
Appium java-client version 3.3.0

**Test scenario**
From homepage test will first push one notification. After 3 seconds it sends app to the background and opens notification shade and checks/searches the notification.

**Test code** 
`//Driver`
`public static AndroidDriver<WebElement> driver;`

`// Push notifications`
`homePage.pushNotification("test1", "test2");`
`Thread.sleep(3000);`

`driver.pressKeyCode(AndroidKeyCode.HOME);`
`Thread.sleep(3000);`

`// Open notification shade`
`driver.openNotifications();`
`Thread.sleep(1000);`

`// Initialize notification page`
`notifPage = new NativeNotificationPage(driver);`
`Thread.sleep(1500);`
`searchNotification("test4");`

Note: Also tried without pressing home button. i.e. when app is in foreground.

Server just crashes after openNotifications function.

**Test log**

> org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
> Build info: version: '2.47.1', revision: 'unknown', time: '2015-07-30 11:02:44'
> System info: host: 'dannys-Mac-mini.local', ip: '192.168.1.125', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.8.0_05'
> Driver info: driver.version: AndroidDriver
>     at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:589)
>     at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
>     at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
>     at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)

**Appium server log**

> info: [debug] Pushing command to appium work queue: ["pressKeyCode",{"keycode":3,"metastate":null}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"pressKeyCode","params":{"keycode":3,"metastate":null}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: pressKeyCode
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":true}
> info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"3f4ba3b8-d750-475c-b394-42cc506e94fe"}
> info: <-- POST /wd/hub/session/3f4ba3b8-d750-475c-b394-42cc506e94fe/appium/device/press_keycode 200 70.607 ms - 76 {"status":0,"value":true,"sessionId":"3f4ba3b8-d750-475c-b394-42cc506e94fe"}
> info: --> POST /wd/hub/session/3f4ba3b8-d750-475c-b394-42cc506e94fe/appium/device/open_notifications {}
> info: [debug] Pushing command to appium work queue: ["openNotification"]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"openNotification","params":{}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: openNotification
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":true}
> info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"3f4ba3b8-d750-475c-b394-42cc506e94fe"}
> info: <-- POST /wd/hub/session/3f4ba3b8-d750-475c-b394-42cc506e94fe/appium/device/open_notifications 200 9.581 ms - 76 {"status":0,"value":true,"sessionId":"3f4ba3b8-d750-475c-b394-42cc506e94fe"}
> info: [debug] [BOOTSTRAP] [debug] Emitting system alert message
> info: [debug] Emitting alert message...
> error: uncaughtException: Cannot read property 'sockets' of null date=Tue Feb 02 2016 16:38:40 GMT+1100 (AEDT), pid=4082, uid=501, gid=20, cwd=/usr/local/lib/node_modules/appium, execPath=/usr/local/Cellar/node/5.3.0/bin/node, version=v5.3.0, argv=[/usr/local/Cellar/node/5.3.0/bin/node, /usr/local/bin/appium, --pre-launch, --app-pkg, com.tute.simpletestapp, --app-activity, .activities.MainActivity, --platform-name, Android, --app, /Users/dannyshen/Documents/AndroidProjects/SimpleApp/bin/SimpleTestApp.apk], rss=115363840, heapTotal=100289568, heapUsed=75011272, loadavg=[2.3193359375, 1.89794921875, 1.7861328125], uptime=112922, trace=[column=25, file=/usr/local/lib/node_modules/appium/lib/devices/android/uiautomator.js, function=, line=195, method=null, native=false, column=9, file=/usr/local/lib/node_modules/appium/node_modules/underscore/underscore.js, function=Function._.each._.forEach, line=153, method=_.each._.forEach, native=false, column=5, file=/usr/local/lib/node_modules/appium/lib/devices/android/uiautomator.js, function=[object Object].UiAutomator.handleBootstrapOutput, line=185, method=UiAutomator.handleBootstrapOutput, native=false, column=8, file=/usr/local/lib/node_modules/appium/lib/devices/android/uiautomator.js, function=[object Object].UiAutomator.outputStreamHandler, line=174, method=UiAutomator.outputStreamHandler, native=false, column=13, file=events.js, function=emitOne, line=77, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=169, method=emit, native=false, column=16, file=_stream_readable.js, function=readableAddChunk, line=146, method=null, native=false, column=10, file=_stream_readable.js, function=Socket.Readable.push, line=110, method=Readable.push, native=false, column=20, file=net.js, function=Pipe.onread, line=523, method=onread, native=false], stack=[TypeError: Cannot read property 'sockets' of null,     at [object Object].<anonymous> (/usr/local/lib/node_modules/appium/lib/devices/android/uiautomator.js:195:25),     at Function._.each._.forEach (/usr/local/lib/node_modules/appium/node_modules/underscore/underscore.js:153:9),     at [object Object].UiAutomator.handleBootstrapOutput (/usr/local/lib/node_modules/appium/lib/devices/android/uiautomator.js:185:5),     at [object Object].UiAutomator.outputStreamHandler (/usr/local/lib/node_modules/appium/lib/devices/android/uiautomator.js:174:8),     at emitOne (events.js:77:13),     at Socket.emit (events.js:169:7),     at readableAddChunk (_stream_readable.js:146:16),     at Socket.Readable.push (_stream_readable.js:110:10),     at Pipe.onread (net.js:523:20)]

**Comment by scottdixon** [comment]
Can you please try with 1.5?

If no luck, please provide entire Appium server logs.

**Comment by laxmikantm** [comment]
Hi,
We are unable to download Appium 1.5 on MacBook 10.11.1

On currently installed Appium IDE for Mac version : 
Version 1.4.13 (Draco)

Kindly suggest how to validate Push notification in this case?
Once it resume working I was planning to read Notifications as List<MobileElement> 
And then iterate through them, looking out for intended Notification.

Many thanks.

**Error log**:

```
info: [debug] [BOOTSTRAP] [debug] Emitting system alert message

error: uncaughtException: Cannot read property 'sockets' of null date=Tue Apr 05 2016 16:54:50 GMT+0100 (BST), pid=7336, uid=1991679138, gid=1003469773, cwd=/Applications/Appium.app/Contents/Resources/node_modules/appium, execPath=/usr/local/bin/node, version=v4.2.1, argv=[/usr/local/bin/node, /Applications/Appium.app/Contents/Resources/node_modules/appium/lib/server/main.js, --address, 10.19.0.197, --command-timeout, 7200, --pre-launch, --debug-log-spacing, --robot-address, 10.19.0.197, --robot-port, 4723, --automation-name, Appium, --platform-name, Android, --platform-version, 4.3, --app, /Users/laxmi.somni/Desktop/Hive_App/Hive-productV6InternalprodMultiProduct-release-1.2.1.00.apk, --app-pkg, uk.co.centrica.hive.v6.internalprod.multiproduct, --app-activity, uk.co.centrica.hive.ui.base.HiveBottomDrawerActivity, --native-instruments-lib], rss=133758976, heapTotal=84602880, heapUsed=78252240, loadavg=[2.51904296875, 2.4482421875, 2.77197265625], uptime=13578, trace=[column=25, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/android/uiautomator.js, function=, line=195, method=null, native=false, column=9, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/underscore/underscore.js, function=Function._.each._.forEach, line=153, method=_.each._.forEach, native=false, column=5, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/android/uiautomator.js, function=[object Object].UiAutomator.handleBootstrapOutput, line=185, method=UiAutomator.handleBootstrapOutput, native=false, column=8, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/android/uiautomator.js, function=[object Object].UiAutomator.outputStreamHandler, line=174, method=UiAutomator.outputStreamHandler, native=false, column=13, file=events.js, function=emitOne, line=77, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=169, method=emit, native=false, column=16, file=_stream_readable.js, function=readableAddChunk, line=146, method=null, native=false, column=10, file=_stream_readable.js, function=Socket.Readable.push, line=110, method=Readable.push, native=false, column=20, file=net.js, function=Pipe.onread, line=523, method=onread, native=false], stack=[TypeError: Cannot read property 'sockets' of null,     at [object Object].<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/android/uiautomator.js:195:25),     at Function._.each._.forEach (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/underscore/underscore.js:153:9),     at [object Object].UiAutomator.handleBootstrapOutput (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/android/uiautomator.js:185:5),     at [object Object].UiAutomator.outputStreamHandler (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/android/uiautomator.js:174:8),     at emitOne (events.js:77:13),     at Socket.emit (events.js:169:7),     at readableAddChunk (_stream_readable.js:146:16),     at Socket.Readable.push (_stream_readable.js:110:10),     at Pipe.onread (net.js:523:20)]
```

**Comment by dpgraham** [comment]
Closing due to inactivity. If this is still an issue on Appium 1.6 please let me know and I'll re-open.
