### ISSUE TITLE
1.5.0-beta12. Android: Can't launch AndroidDriver (Selendroid mode) 

### ISSUE THREAD

**Issue by TikhomirovSergey** [appium/appium#6102]
Server: 1.5.0-beta12
OS: Windows 7/8/10(?)

Client code sample:
```java
        AppiumServiceBuilder builder = new AppiumServiceBuilder()/*.withArgument(GeneralServerFlag.AUTOMATION_NAME, AutomationName.SELENDROID)*/;
        service = builder.build();
        service.start();

        File appDir = new File("src/test/java/io/appium/java_client");
        File app = new File(appDir, "ApiDemos-debug.apk");
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "Android Emulator");
        capabilities.setCapability(MobileCapabilityType.APP, app.getAbsolutePath());
        capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.SELENDROID);
        //capabilities.setCapability(MobileCapabilityType.SELENDROID_PORT, SELENDROID_PORT);
        driver = new AndroidDriver<WebElement>(service.getUrl(), capabilities);
```

Error which is thrown on the client side:
```
 (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 14.02 seconds
Build info: version: '2.50.0', revision: '1070ace4650453d518aeb03e7a9a36c9d264a8e7', time: '2016-01-27 10:46:18'
System info: host: '', ip: '', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_71'
Driver info: io.appium.java_client.android.AndroidDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)

```

Server ourput: 
https://gist.github.com/TikhomirovSergey/ebede547edff223698dd

Attention please: 
https://gist.github.com/TikhomirovSergey/ebede547edff223698dd#file-gistfile1-txt-L120
https://gist.github.com/TikhomirovSergey/ebede547edff223698dd#file-gistfile1-txt-L132
https://gist.github.com/TikhomirovSergey/ebede547edff223698dd#file-gistfile1-txt-L138

**Comment by TikhomirovSergey** [comment]
appium/java-client#302
appium/appium-dotnet-driver#136

**Comment by scottdixon** [comment]
@TikhomirovSergey - had this worked your Windows machine with Appium 1.4 previously?

**Comment by TikhomirovSergey** [comment]
@scottdixon Yep. It was working fine. I've used this mode in java client/c# client tests.

**Comment by scottdixon** [comment]
Can you please provide server logs from 1.4?

**Comment by TikhomirovSergey** [comment]
@scottdixon 
https://gist.github.com/TikhomirovSergey/217c4dc73118fbb68065

**Comment by scottdixon** [comment]
Strange I get the error on 1.5 and 1.4.

With your emulator running, can you please provide the output of `adb shell pm list packages -f`

**Comment by TikhomirovSergey** [comment]
Here is [adb shell pm list packages -f output](https://gist.github.com/TikhomirovSergey/5ccb150769bbcf44381b)
