### ISSUE TITLE
Error while running appium test case to launch an application

### ISSUE THREAD

**Issue by Gurupreeth** [appium/appium#6152]
I am new to Appium, I have setup everything, but it is giving me the following error.

info: Client User-Agent string: Apache-HttpClient/4.3.3 (java 1.5)
info: [debug] No appActivity desired capability or server param. Parsing from apk.
info: [debug] Using local app from desired caps: /home/dell/workspace/Theatro/apk/com.whatsapp_v2.12.438-450897_Android-2.1.apk
info: [debug] Creating new appium session 8e4c1c9c-ecd4-4e23-89ba-298c1127dfd9
info: Starting android appium
info: [debug] Getting Java version
info: Java version is: 1.8.0_66
info: [debug] Checking whether adb is present
error: Unhandled error: Error: ENOENT: no such file or directory, scandir '/home/dell/.linuxbrew/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/dell/Downloads/node-v5.5.0-linux-x64/bin:/home/dell/.linuxbrew/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/dell/Downloads/node-v5.5.0-linux-x64/bin:/home/dell/workspace/Android/android-sdk-linux/tools:/home/dell/.linuxbrew/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/dell/Downloads/node-v5.5.0-linux-x64/bin:/home/dell/workspace/Android/android-sdk-linux/platform-tools:/home/dell/.linuxbrew/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/dell/Downloads/node-v5.5.0-linux-x64/bin:/home/dell/workspace/Android/android-sdk-linux/build-tools/23.0.2:/home/dell/.linuxbrew/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/dell/Downloads/node-v5.5.0-linux-x64/bin:/home/dell/.linuxbrew/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/dell/Downloads/node-v5.5.0-linux-x64/bin:/home/dell/workspace/Android/android-sdk-linux/tools:/home/dell/.linuxbrew/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/dell/Downloads/node-v5.5.0-linux-x64/bin:/home/dell/workspace/Android/android-sdk-linux/platform-tools:/home/dell/.linuxbrew/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/dell/Downloads/node-v5.5.0-linux-x64/bin:/home/dell/workspace/Android/android-sdk-linux/build-tools/23.0.2:/usr/lib/jvm/java-8-oracle/jre/bin:home/dell/.linuxbrew/bin:/home/dell/Downloads/node-v5.5.0-linux-x64/bin:/home/dell/workspace/Android/android-sdk-linux/build-tools'
at Error (native)
at Object.fs.readdirSync (fs.js:856:18)
at exports.getDirectories (/home/dell/.linuxbrew/lib/node_modules/appium/node_modules/appium-adb/lib/helpers.js:100:18)
at [object Object].ADB.checkSdkBinaryPresent (/home/dell/.linuxbrew/lib/node_modules/appium/node_modules/appium-adb/lib/adb.js:97:25)
at [object Object].ADB.checkAdbPresent (/home/dell/.linuxbrew/lib/node_modules/appium/node_modules/appium-adb/lib/adb.js:134:8)
at Function.ADB.createADB (/home/dell/.linuxbrew/lib/node_modules/appium/node_modules/appium-adb/lib/adb.js:73:7)

I m struggling with this issue for the past few days, didn't get any solution till now. Please help. Thanks in advance

**Comment by imurchie** [comment]
The system cannot find `adb`, which it uses to talk with the Android device.

What is the value of your environment variable `ANDROID_HOME`?

**Comment by Gurupreeth** [comment]
@imurchie thanks for the reply. following is the path set in .bashrc

export PATH=${PATH}:home/dell/.linuxbrew/bin
export MANPATH=home/dell/.linuxbrew/share/man:$MANPATH
export INFOPATH=home/dell/.linuxbrew/share/info:$INFOPATH
export PATH=${PATH}:/home/dell/Downloads/node-v5.5.0-linux-x64/bin
export ANDROID_HOME=${PATH}:/home/dell/workspace/Android/android-sdk-linux
export PATH=${PATH}:$ANDROID_HOME/tools
export PATH=${PATH}:$ANDROID_HOME/platform-tools
export PATH=${PATH}:$ANDROID_HOME/build-tools/23.0.2
export JAVA_HOME=${PATH}:/usr/lib/jvm/java-8-oracle/jre
export PATH=${PATH}:$JAVA_HOME/bin

**Comment by nuggit32** [comment]
Are you running from an IDE or command line?  I know in Eclipse the IDE does not pick up the .bashrc paths.  You have to set ANDROID_HOME in the tool environment.

**Comment by imurchie** [comment]
This line is wrong:

```shell
export ANDROID_HOME=${PATH}:/home/dell/workspace/Android/android-sdk-linux
```

This sets the `ANDROID_HOME` as your `PATH` and where the actual android home is. Change it to 

```shell
export ANDROID_HOME=/home/dell/workspace/Android/android-sdk-linux
```

and try again.

**Comment by SrinivasanTarget** [comment]
@Gurupreeth Have you tried this?

**Comment by SrinivasanTarget** [comment]
@triager please close. Closing this because of inactivity.
