### ISSUE TITLE
Unable to run Appium 1.5 using AppiumDriverLocalService

### ISSUE THREAD

**Issue by mayureshshirodkar** [appium/appium#6197]
## The problem

Installed Appium 1.5 using NPM and tried running it with AppiumDriverLocalService. 
I wasn't able to run Appium server. 
Though same worked fine with Appium version 1.4.16.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.0 
* Last Appium version that did not exhibit the issue (if applicable): 1.4.16
* Desktop OS/version used to run Appium: Mac OS X El Capitan
* Node.js version (unless using Appium.app|exe): v5.5
* Mobile platform: Android/iOS
* Real Device

## Details

**Code Used**:
AppiumDriverLocalService service = AppiumDriverLocalService.buildService(new AppiumServiceBuilder().withStartUpTimeOut(5, TimeUnit.SECONDS));
service.start();
driver=new AndroidDriver(capabilities);

Appium Path:/usr/local/lib/node_modules/appium

## Link to Appium logs
**Error on Eclipse:**
**io.appium.java_client.service.local.InvalidServerInstanceException: Invalid server instance exception has occured: There is no installed nodes! Please install  node via NPM (https://www.npmjs.com/package/appium#using-node-js) or download and install Appium app (http://appium.io/downloads.html)**
	at io.appium.java_client.service.local.AppiumServiceBuilder.findNodeInCurrentFileSystem(AppiumServiceBuilder.java:107)
	at io.appium.java_client.service.local.AppiumServiceBuilder.checkAppiumJS(AppiumServiceBuilder.java:242)
	at io.appium.java_client.service.local.AppiumServiceBuilder.createArgs(AppiumServiceBuilder.java:248)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:299)
	at io.appium.java_client.service.local.AppiumDriverLocalService.buildService(AppiumDriverLocalService.java:194)
	at guide_config.Setup.setupAppium(Setup.java:53)
	at guide_testcases.E2E_Tests.beforeTest(E2E_Tests.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.io.IOException: /usr/local/lib/node_modules

	at io.appium.java_client.service.local.AppiumServiceBuilder.findNodeInCurrentFileSystem(AppiumServiceBuilder.java:110)
	... 30 more

**Comment by SrinivasanTarget** [comment]
@mayureshshirodkar AppiumLocalService works fine with node version till 5.7.0 and Appium server version 1.5. But your error log says node is not installed. Please try to run your script from cmd and confirm us.Going forward please raise these issues in java_client repo.

**Comment by mayureshshirodkar** [comment]
@SrinivasanTarget  Looks like AppiumLocalService din't pick up the default path to the main.js.
It still pointed to appium.js whereas for Appium 1.5, it should have picked up main.js.

I set a environmental variable APPIUM_BINARY_PATH to '/usr/local/lib/node_modules/appium/build/lib/main.js' and this worked for me.

**Comment by saikrishna321** [comment]
@mayureshshirodkar 

```
AppiumServiceBuilder builder = new AppiumServiceBuilder()
				.withAppiumJS(new File("/usr/local/lib/node_modules/appium/build/lib/main.js"))
				.withArgument(GeneralServerFlag.APP, System.getProperty("user.dir") + "/build/wordpress.apk")
				.withArgument(GeneralServerFlag.LOG_LEVEL, "info")
				.withLogFile(new File(System.getProperty("user.dir") + "/target/logs/sample.txt"))
				.usingAnyFreePort()
		/* and so on */;
		appiumDriverLocalService = builder.build();
		appiumDriverLocalService.start();

```

You can also set appium server path when your starting the server, you don't need to set in ENV variables

**Comment by scottdixon** [comment]
Looks like this is resolved. @mayureshshirodkar please reopen if any issues.

**Comment by shynkevich-alex** [comment]
I have the same problem.
Node version 7.0.0
Appium version 1.6.0

But it happens on one machine another works well.

I checked path of node.js and it is the same on both PCs.

> io.appium.java_client.service.local.InvalidServerInstanceException: Invalid server instance exception has occured: There is no installed nodes! Please install node via NPM (https://www.npmjs.com/package/appium#using-node-js) or download and install Appium app (http://appium.io/downloads.html)
    	at io.appium.java_client.service.local.AppiumServiceBuilder.findNodeInCurrentFileSystem(AppiumServiceBuilder.java:160)
    	at io.appium.java_client.service.local.AppiumServiceBuilder.checkAppiumJS(AppiumServiceBuilder.java:305)
    	at io.appium.java_client.service.local.AppiumServiceBuilder.createArgs(AppiumServiceBuilder.java:386)
    	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:299)
    	at com.*****.appium.helper.DriverManager.createAppiumDriver(DriverManager.java:49)
    	at com.autotest.runners.BaseRunner.setUp(BaseRunner.java:77)
    	at com.autotest.runners.advert.AdvertRunner.setUp(AdvertRunner.java:22)
    	at com.autotest.runners.advert.NativeRunner.setUp(NativeRunner.java:23)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
    	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
    	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:216)
    	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:143)
    	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:169)
    	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
    	at org.testng.TestRunner.privateRun(TestRunner.java:753)
    	at org.testng.TestRunner.run(TestRunner.java:607)
    	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
    	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
    	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
    	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
    	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
    	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
    	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
    	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
    	at org.testng.TestNG.runSuites(TestNG.java:1124)
    	at org.testng.TestNG.run(TestNG.java:1096)
    	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.runTests(TestNGTestClassProcessor.java:133)
    	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.stop(TestNGTestClassProcessor.java:83)
    	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
    	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
    	at com.sun.proxy.$Proxy2.stop(Unknown Source)
    	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:120)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:364)
    	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
    	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	at java.lang.Thread.run(Thread.java:745)
    Caused by: java.io.IOException: /usr/local/lib/node_modules

    /var/folders/wk/w9dbkg0x7gbdbcmr2c9pfwnw0000gn/T/get_path_to_default_node5706633666934429851.sh: line 4: shell_session_update: command not found

    	at io.appium.java_client.service.local.AppiumServiceBuilder.findNodeInCurrentFileSystem(AppiumServiceBuilder.java:161)
    	... 54 more

**Comment by jlipps** [comment]
This is an issue that should be handled at the Appium java client repo, not the main repo here

**Comment by shynkevich-alex** [comment]
@jlipps  should I create issue in appium java client or we can move it by some way?

**Comment by imurchie** [comment]
You'll have to create a new issue there.

**Comment by shynkevich-alex** [comment]
@imurchie  @jlipps  So I've created issue #7123

**Comment by imurchie** [comment]
This should be created on https://github.com/appium/java-client

**Comment by avadh93** [comment]
I got the same exact problem as above: I manually set the appium.js and node.exe path in the program but now new error is coming stating: java.lang.NoClassDefFoundError: org/apache/commons/validator/routines/InetAddressValidator


"Code used is as below::" Kindly suggest the walkaround.

public class StartandStopAppiumServerProgrammatically {
	WebDriver driver;
	AppiumDriverLocalService appiumService;
	String appiumServiceUrl;

	@BeforeTest
	public void setUp() throws MalformedURLException {
		// Start Appium Service
		appiumService = AppiumDriverLocalService
				.buildService(new AppiumServiceBuilder().usingAnyFreePort()
						.usingDriverExecutable(new File("C:/Program Files (x86)/Appium/node.exe"))
						.withAppiumJS(new File("C:/Program Files (x86)/Appium/node_modules/appium/bin/appium.js")));
		appiumService.start();
		appiumServiceUrl = appiumService.getUrl().toString();
		System.out.println("Appium Service Address : - " + appiumServiceUrl);

		// Created object of DesiredCapabilities class.
		DesiredCapabilities capabilities = new DesiredCapabilities();

		// Set android deviceName desired capabilitcy. Set your device name.
		capabilities.setCapability("deviceName", "c8c5d8f6");

		// Set BROWSER_NAME desired capability. It's Android in our case here.
		capabilities.setCapability(CapabilityType.BROWSER_NAME, "Android");

		// Set android VERSION desired capability. Set your mobile device's OS
		// version.
		capabilities.setCapability("platformVersion", "5.1.1");

		// Set android platformName desired capability. It's Android in our case
		// here.
		capabilities.setCapability("platformName", "Android");

		// Set android appPackage desired capability. It is
		// com.android.calculator2 for calculator application.
		// Set your application's appPackage if you are using any other app.
		capabilities.setCapability("appPackage", "com.android.calculator2");

		// Set android appActivity desired capability. It is
		// com.android.calculator2.Calculator for calculator application.
		// Set your application's appPackage if you are using any other app.
		capabilities.setCapability("appActivity",
				"com.android.calculator2.Calculator");

		// Created object of RemoteWebDriver will all set capabilities.
		// Set appium server address and port number in URL string.
		// It will launch calculator app in android device.
		driver = new RemoteWebDriver(new URL("http://127.0.0.1:4723/wd/hub"),
				capabilities);
		driver.manage().timeouts().implicitlyWait(15, TimeUnit.SECONDS);
	}

	@Test
	public void Sum() {
		// Click on DELETE/CLR button to clear result text box before running
		// test.
		driver.findElements(
				By.xpath("//android.widget.ImageButton[contains(@resource-id,'clear')]"))
				.get(0).click();

		// Click on number 2 button.
		driver.findElement(By.id("com.android.calculator2:id/digit2")).click();

		// Click on + button.
		driver.findElement(By.id("com.android.calculator2:id/plus")).click();

		// Click on number 5 button.
		driver.findElement(By.id("com.android.calculator2:id/digit5")).click();

		// Click on = button.
		driver.findElement(By.id("com.android.calculator2:id/equal")).click();

		// Get result from result text box.
		String result = driver.findElement(
				By.className("android.widget.EditText")).getText();
		System.out.println("Number sum result is : " + result);

	}

	@AfterTest
	public void End() {

		System.out.println("Stop driver");
		driver.quit();
		System.out.println("Stop appium service");
		appiumService.stop();
	}

}

**Comment by avadh93** [comment]
I got the solution::


To start the server programmatically you have to remove this line in your previous program
driver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"), cap);
and replace with
driver = new AndroidDriver(new URL(service_url),cap);
Where service_url =service.getUrl().toString();

**Comment by JPRuban** [comment]
@saikrishna321 : Your solution worked for me. Thank you very much
 AppiumServiceBuilder builder = new AppiumServiceBuilder()
                .withAppiumJS(new File("/usr/local/lib/node_modules/appium/build/lib/main.js"))
                .withArgument(GeneralServerFlag.LOG_LEVEL, "info")
                .usingAnyFreePort()

        appiumService = builder.build();
        appiumService.start();
        appiumServiceUrl = appiumService.getUrl().toString();
        System.out.println("Appium Service Address : - "+ appiumServiceUrl);

        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("appium-version", "1.3.2");
        capabilities.setCapability("platformName", "android");
        capabilities.setCapability("deviceName", "Pixel_4548");
        capabilities.setCapability(CapabilityType.VERSION, "8.1.0");
        capabilities.setCapability("appPackage", "com.ebay.mobile");
        capabilities.setCapability("appActivity", "com.ebay.mobile.activities.MainActivity");

        // Set job name
        //capabilities.setCapability("name", "Appium Sample" + date);
        //String appPath = System.getenv("android_app_path");
        //assert appPath != null: "Path to Android app is not set";
        //System.out.println("Android App path: "+ appPath);
        //capabilities.setCapability("app", appPath);
        driver = new AndroidDriver(new URL(appiumServiceUrl), capabilities);

        driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);

**Comment by avadh93** [comment]
My pleasure :)

Regards,
Avadh Goyal

+91-9654146260
