### ISSUE TITLE
On windows environment run appium failed

### ISSUE THREAD

**Issue by kaku21** [appium/appium#6205]
## The problem

I use cmd command install appium : npm install -g appium
and setting environment : path = C:\Users\user\AppData\Roaming\npm
when i run the samplecode AndroidContactsTest.java junit failed,the message below:

org.openqa.selenium.InvalidSelectorException: Locator Strategy 'name' is not supported for this session (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 53 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/invalid_selector_exception.html
Build info: version: '2.52.0', revision: '4c2593cfc3689a7fcd7be52549167e5ccc93ad28', time: '2016-02-11 11:22:43'
System info: host: 'zhangziteng', ip: '192.168.34.10', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_51'
*** Element info: {Using=name, value=Add Contact}
Session ID: 8e10e4fb-884d-4c62-834d-e7ef89088a62
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{platform=LINUX, app=E:\2015EclipseWS\anos\apps_android\ContactManager.apk, javascriptEnabled=true, appActivity=.ContactManager, networkConnectionEnabled=true, desired={app=E:\2015EclipseWS\anos\apps_android\ContactManager.apk, platformVersion=4.4, deviceName=Android Emulator, platformName=Android, appActivity=.ContactManager, appPackage=com.example.android.contactmanager}, locationContextEnabled=false, appPackage=com.example.android.contactmanager, platformVersion=4.4.4, databaseEnabled=false, deviceName=192.168.182.101:5555, platformName=Android, webStorageEnabled=false, warnings={}, takesScreenshot=true}]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:363)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByName(RemoteWebDriver.java:461)
	at io.appium.java_client.DefaultGenericMobileDriver.findElementByName(DefaultGenericMobileDriver.java:102)
	at io.appium.java_client.AppiumDriver.findElementByName(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.findElementByName(AndroidDriver.java:1)
	at org.openqa.selenium.By$ByName.findElement(By.java:303)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:355)
	at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:52)
	at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.findElement(AndroidDriver.java:1)
	at jobs.anos.AndroidContactsTest.addContact(AndroidContactsTest.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

then i try the Appium.msi to setup appium.exe and run it,i run the test again and it worked. I don't understand the different between cmd commant run appium and the appium.exe,why I use cmd startup the appium that it cannot run successfully??

## Environment

* Appium version (or git revision) that exhibits the issue:    1.5.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: windows 7 64bit
* Node.js version (unless using Appium.app|exe):v5.0.7
* Mobile platform/version under test: android 4.4.4 - API 19 
* Real device or emulator/simulator:  use genemotion simulator
* Appium CLI or Appium.app|exe: cmd startup appium  ( c:\Users\user\>appium )
  [Appium] Welcome to Appium v1.5.0
  [Appium] Appium REST http interface listener started on 0.0.0.0:4723

## Details

error message on appium console below:

[debug] [ADB] Pressing the HOME button
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running D:\Android\sdk\platform-tools\adb.exe with args: ["-P",503
7,"-s","192.168.182.101:5555","shell","input","keyevent",3]
[debug] [Logcat] Stopping logcat capture
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"shutdown"}
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [UiAutomator] Shutting down UiAutomator
[debug] [UiAutomator] Moving to state 'stopping'
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"shutdow
n"}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type SHUTDOWN
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"value":"OK, shutt
ing down","status":0}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Closed client connection
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: numtests=1
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: stream=.
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: id=UiAutomato
rTestRunner
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: test=testRunS
erver
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: class=io.appi
um.android.bootstrap.Bootstrap
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: current=1
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS_CODE: 0
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: stream=
[debug] [AndroidBootstrap] [UIAUTO STDOUT] Test results for WatcherResultPrinter
=.
[debug] [AndroidBootstrap] [UIAUTO STDOUT] Time: 9.489
[debug] [AndroidBootstrap] [UIAUTO STDOUT] OK (1 test)
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS_CODE: -1
[debug] [UiAutomator] UiAutomator shut down normally
[debug] [UiAutomator] Moving to state 'stopped'
[debug] [ADB] Attempting to kill all uiautomator processes
[debug] [ADB] Getting all processes with uiautomator
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running D:\Android\sdk\platform-tools\adb.exe with args: ["-P",503
7,"-s","192.168.182.101:5555","shell","ps","uiautomator"]
[ADB] No uiautomator process found to kill, continuing...
[debug] [UiAutomator] Moving to state 'stopped'
[Appium] Removing session 8e10e4fb-884d-4c62-834d-e7ef89088a62 from our master s
ession list
[debug] [MJSONWP] Received response: null
[debug] [MJSONWP] But deleting session, so not returning
[MJSONWP] Responding to client with driver.deleteSession() result: null
[HTTP] <-- DELETE /wd/hub/session/8e10e4fb-884d-4c62-834d-e7ef89088a62 200 6797
ms - 76

## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!

**Comment by SrinivasanTarget** [comment]
"Name" locator startegy is officially deprecated still you can it along
with xpath as //*[name="....

**Comment by kaku21** [comment]
@Test
    public void addContact(){
    	WebElement el = driver.findElement(By.name("Add Contact"));
        //System.out.println("8888888");
        el.click();
        List<AndroidElement> textFieldsList = driver.findElementsByClassName("android.widget.EditText");
        textFieldsList.get(0).sendKeys("Some Name");
        textFieldsList.get(2).sendKeys("Some@example.com");
        //driver.swipe(100, 500, 100, 100, 2);
        driver.findElementByName("Save").click();
    }
this is the sample code content,you mean that I should modify [ el = driver.findElement(By.name("Add Contact"));] to xpath  driver.findElement(By.xpath([name="Add Contact")) ,is that so??

**Comment by SrinivasanTarget** [comment]
@kaku21  Yes the same way but your xpath is wrong.It should be //*[@name='Add Contact']

**Comment by kaku21** [comment]
ok , I know it now. I try it with driver.findElementbyid and it worked.but I still not understand the question is
the same code  driver.findElement(By.name("Add Contact")); can run on the Appium.exe which setup through AppiumForWindows_1_4_13_1 include appium-installer.exe and update.bat,
but can not run with the appium setup through  npm install -g appium 
is there some different on version or there are some wrong with my config?? I confuse with it

**Comment by scottdixon** [comment]
ByName has been removed in 1.5. More info: #6192

Reopen in you have any further queries.
