### ISSUE TITLE
Unable to verify the first certificate while downloading app from https

### ISSUE THREAD

**Issue by email2vimalraj** [appium/appium#6218]
## The problem

When app is hosted in *https* and server in *http*, appium fails to download the app.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.0
* Last Appium version that did not exhibit the issue (if applicable): Didn't try
* Desktop OS/version used to run Appium: MAC OSx Yosemite
* Node.js version (unless using Appium.app|exe): v5.0.0
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

## Details

My app is hosted in the server which is accessible only through *https* protocol, whereas I run appium in my local mac machine which is using *http://127.0.0.1:4723/wd/hub". The `app` capability is `https://myhost/myapp.apk`. When I run, the appium server throws an error.

## Appium logs

```
[MJSONWP] Encountered internal error running command: Error: Problem downloading app from url https://myhost//myapp.apk: Error: unable to verify the first certificate
    at downloadApp$ (lib/helpers.js:59:11)
    at tryCatch (/Users/vselvam/.node/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/vselvam/.node/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/vselvam/.node/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/vselvam/.node/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Users/vselvam/.node/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /Users/vselvam/.node/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/Users/vselvam/.node/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at doNTCallback0 (node.js:428:9)
    at process._tickCallback (node.js:357:13)
[HTTP] <-- POST /wd/hub/session 500 802.307 ms - 337 
```

**Comment by scottdixon** [comment]
Do you have a certificate / are you able to access your https host through your browser without any warnings?

**Comment by email2vimalraj** [comment]
Yes I'm able to download the app apk file from the browser without warnings.

**Comment by email2vimalraj** [comment]
I believe it must be something to do with Cross origin setting in our node configs.

**Comment by scottdixon** [comment]
Hmm. Let's narrow it down. 

What happens if you try:
**https** on another host, for example: `https://appium.s3.amazonaws.com/TestApp7.1.app.zip`
**http** on your host, for example: `http://myhost//myapp.apk`

**Comment by email2vimalraj** [comment]
I'll try and let you know. I'm not currently using machine.

**Comment by email2vimalraj** [comment]
Do you have the android app hosted in aws?

**Comment by scottdixon** [comment]
It should be enough to get you past the app download logic. If not, try this one: http://appium.s3.amazonaws.com/ApiDemos-debug-2015-03-19.apk

**Comment by scottdixon** [comment]
How'd you go @email2vimalraj ?

**Comment by email2vimalraj** [comment]
Hi,

Just verified and confirm that it is working fine. The apk gets downloaded with both http and https with no hassle.

So I assume the server where our apk hosted May issue the certificate for the client to trust. I'll follow up with my infrastructure team.

This can be closed.

Thanks
Vimal

**Comment by scottdixon** [comment]
Good news. Thanks for the update!
