### ISSUE TITLE
[v1.5][IOS-Sim]- Not able to launch simulator created with simctl

### ISSUE THREAD

**Issue by saikrishna321** [appium/appium#6228]
## The problem

Created a simulator using simctl and when i try to launch the created simulator appium fails to find the created sim 

## Environment

* Appium version (or git revision) that exhibits the issue:1.5
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:Mac OSX
* Node.js version (unless using Appium.app|exe):5.6.0
* Mobile platform/version under test:iOS
* Real device or emulator/simulator:Simulator
* Appium CLI or Appium.app|exe:CLI

## Details

I created a new simulator with the command 

```
xcrun simctl create AppiumParallel1 com.apple.CoreSimulator.SimDeviceType.iPhone-5 com.apple.CoreSimulator.SimRuntime.iOS-9-2
```

i could find this device under device list instruments -s device 

```
Known Devices:
INsaikrisv [C8476FF9-9BC4-5E52-AE3D-536A2E85D43B]
AppiumParallel1 (9.2) [0120C306-95C1-4196-BC13-4196105EBEF9]
Apple TV 1080p (9.1) [C5957108-6BA4-4A98-9A83-4BED47EFF1BC]
iPad 2 (8.4) [B45264A0-551C-41A5-A636-8211C05D8003]
iPad 2 (9.2) [4444EB1E-BA48-4DFA-B16C-777171FCF3BC]
iPad Air (8.4) [F26279E7-8BAF-4D7B-ABFE-08D1AC364DCF]
```

DesiredCaps:

```
DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setCapability("platformVersion","9.2");
		capabilities.setCapability("deviceName","AppiumParallel1");
		capabilities.setCapability("browserName","");
		capabilities.setCapability("app", "/Users/saikrisv/Downloads/WordPressLatest.app");
		capabilities.setCapability("noReset", true);
		driver = new IOSDriver<MobileElement>(service.getUrl(),capabilities);
```

Error Stack 

```

[iOSSim] Retrieving device name string for Xcode version 7.2.1
[iOS] Error: Could not find a device to launch. You requested 'AppiumParallel1 (9.2)', but the available devices were: ["iPad 2 (8.4) [B45264A0-551C-41A5-A636-8211C05D8003]","iPad 2 (9.2) [4444EB1E-BA48-4DFA-B16C-777171FCF3BC]","iPad Air (8.4) [F26279E7-8BAF-4D7B-ABFE-08D1AC364DCF]","iPad Air (9.2) [0CEA45C5-CF8C-4C9F-BE8E-55A96C2E8933]","iPad Air 2 (9.2) [05A04FC2-5D76-415C-9C00-885D3CBCD219]","iPad Pro (9.2) [2225322D-2149-4C67-BA6A-6A144F656568]","iPad Retina (8.4) [A61166B5-0938-4CB6-933E-8883796C4FA1]","iPad Retina (9.2) [9CEB6501-EF1C-4744-9A4F-2732899B238F]","iPhone 4s (8.4) [F0F5A1D3-8701-4CBB-A87D-94D36A21E3A9]","iPhone 4s (9.2) [27E3B429-1B56-4039-9522-214F96524F88]","iPhone 5 (8.4) [B4436B6B-512A-4258-8E2D-53D30230CBF7]","iPhone 5 (9.2) [A63CE714-A4A7-4542-AE1E-027A81B5E7A6]","iPhone 5s (8.4) [6C93FEC4-61EA-4286-9BA7-84D25B4EC995]","iPhone 5s (9.2) [3A34CD7F-1150-480D-B8D8-3C5909AD5487]","iPhone 6 (8.4) [93231996-F5DC-4730-88F0-396F87D40717]","iPhone 6 (9.2) [F4A4A877-D1F5-4ED3-B8BB-EE6DDA657379]","iPhone 6 Plus (8.4) [2E9633A9-26D4-4C68-8E5F-ABB6D40A0117]","iPhone 6 Plus (9.2) [75B35201-5415-43C3-97F2-C69A62C02897]","iPhone 6s (9.2) [F9D02DC0-5B8D-4843-8DF4-B13EF65FF495]","iPhone 6s (9.2) + Apple Watch - 38mm (2.1) [54E7747B-1D5E-471F-8ECD-24147E48A56C]","iPhone 6s Plus (9.2) [69061194-ABAE-4E6C-9042-148470466E1E]","iPhone 6s Plus (9.2) + Apple Watch - 42mm (2.1) [39565723-ED4A-44FB-B247-1FFE45D811C4]"]
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at noDevicesError (lib/driver.js:869:14)
    at IosDriver.checkSimAvailable$ (lib/driver.js:874:9)
    at tryCatch (/Users/saikrisv/git/appium_master/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/saikrisv/git/appium_master/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/saikrisv/git/appium_master/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/saikrisv/git/appium_master/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Users/saikrisv/git/appium_master/appium/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /Users/saikrisv/git/appium_master/appium/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/Users/saikrisv/git/appium_master/appium/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at nextTickCallbackWith0Args (node.js:453:9)
    at process._tickCallback (node.js:382:13)
```

**Comment by SrinivasanTarget** [comment]
@saikrishna321 I think its been filtered wrongly here, 
https://github.com/appium/appium-instruments/blob/master/lib/utils.js#L29
Checking now.
