### ISSUE TITLE
[Appium 1.5] The reset command uninstalls app instead clear data on Android

### ISSUE THREAD

**Issue by JadeDu** [appium/appium#6260]
## The problem

Steps to reproduce:

1. Start appium server (1.5) on with the command "appium", no arguments.
2. Using Appium Python Client to execute "driver.reset()"
3. Expect application data is cleared (fast reset), but get application uninstalled (running old fashion reset).

Server log:

[HTTP] --> POST /wd/hub/session/562d0f6f-7672-428b-8005-74a27af19f6b/appium/app/reset 
[MJSONWP] Calling AppiumDriver.reset() with args: ["562d0f6f-7672-428b-8005-74a27af19f6b"]
[AndroidDriver] Running old fashion reset (reinstall)

## Environment

* Appium version (or git revision): 1.5
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS 10.10.5
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI

**Comment by JadeDu** [comment]
This seems to be the problem:
https://github.com/appium/appium-android-driver/blob/master/lib/commands/general.js -> commands.reset: the if check need to use this.opts.fullReset as fastReset is not available.

commands.reset = async function () {
  if (this.opts.fastReset) {
    log.info("Running fast reset (stop and clear)");
    await this.adb.stopAndClear(this.opts.appPackage);
  } else {
    log.info("Running old fashion reset (reinstall)");
    await this.adb.stopAndClear(this.opts.appPackage);
    await this.adb.uninstallApk(this.opts.appPackage);
    await androidHelpers.installApkRemotely(this.adb, this.opts.app, this.opts.appPackage, this.opts.fastReset);
  }

  return await this.startAUT();
};

**Comment by JadeDu** [comment]
Created the pull request https://github.com/appium/appium-android-driver/pull/121

**Comment by mittt** [comment]
I use an app that's already installed - capabilities.SetCapability("appPackage", package); 
This result in an error:


[MJSONWP] Encountered internal error running command: TypeError: path must be a string
    at TypeError (native)
    at Object.fs.readFile (fs.js:250:11)
    at Object.tryCatcher (C:\Users\dstefanov\AppData\Roaming\npm\node_modules\appium\node_modules\bluebird\js\main\util.js:26:23)
    at Object.ret [as readFile] (eval at <anonymous> (C:\Users\dstefanov\AppData\Roaming\npm\node_modules\appium\node_modules\bluebird\js\main\promisify.js:163:12), <anonymous>:14:23)
    at Object.md5$ (lib/fs.js:34:25)
    at tryCatch (C:\Users\dstefanov\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\dstefanov\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\dstefanov\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at invoke (C:\Users\dstefanov\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at enqueueResult (C:\Users\dstefanov\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:185:17)
    at new Promise (C:\Users\dstefanov\AppData\Roaming\npm\node_modules\appium\node_modules\core-js\library\modules\es6.promise.js:197:7)
    at AsyncIterator.enqueue (C:\Users\dstefanov\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (C:\Users\dstefanov\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at Object.runtime.async (C:\Users\dstefanov\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:209:12)
    at Object.md5 (lib/fs.js:33:32)
    at Object.callee$0$0$ (lib/android-helpers.js:196:25)
    at tryCatch (C:\Users\dstefanov\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\dstefanov\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\dstefanov\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at invoke (C:\Users\dstefanov\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at enqueueResult (C:\Users\dstefanov\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:185:17)
    at new Promise (C:\Users\dstefanov\AppData\Roaming\npm\node_modules\appium\node_modules\core-js\library\modules\es6.promise.js:197:7)
    at AsyncIterator.enqueue (C:\Users\dstefanov\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (C:\Users\dstefanov\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at Object.runtime.async (C:\Users\dstefanov\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:209:12)
    at Object.callee$0$0 [as installApkRemotely] (lib/android-helpers.js:200:16)
    at AndroidDriver.callee$0$0$ (lib/commands/general.js:172:26)
    at tryCatch (C:\Users\dstefanov\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\dstefanov\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\dstefanov\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\dstefanov\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at run (C:\Users\dstefanov\AppData\Roaming\npm\node_modules\appium\node_modules\core-js\library\modules\es6.promise.js:104:47)
    at C:\Users\dstefanov\AppData\Roaming\npm\node_modules\appium\node_modules\core-js\library\modules\es6.promise.js:115:28
    at flush (C:\Users\dstefanov\AppData\Roaming\npm\node_modules\appium\node_modules\core-js\library\modules\$.microtask.js:19:5)

**Comment by SrinivasanTarget** [comment]
@triager please close
