### ISSUE TITLE
Local installation problem

### ISSUE THREAD

**Issue by shadeimi** [appium/appium#6268]
```
✔ ~/git/appium_v1.5 [v1.5.0 L|✔] 
11:54 $ ls
AUTHORS  bin  CHANGELOG.md  CONDUCT.md  CONTRIBUTING.md  docs  GOVERNANCE.md  gulpfile.js  lib  LICENSE  node_modules  npm-debug.log  npm-shrinkwrap.json  package.json  packweb.json  README.md  RELEASE.pdf  ROADMAP.md  test
✔ ~/git/appium_v1.5 [v1.5.0 L|✔] 
11:54 $ ls
AUTHORS  bin  CHANGELOG.md  CONDUCT.md  CONTRIBUTING.md  docs  GOVERNANCE.md  gulpfile.js  lib  LICENSE  node_modules  npm-debug.log  npm-shrinkwrap.json  package.json  packweb.json  README.md  RELEASE.pdf  ROADMAP.md  test
✔ ~/git/appium_v1.5 [v1.5.0 L|✔] 
11:54 $ npm install .
npm WARN deprecated lodash.padright@3.1.1: This package has been discontinued in favor of lodash.padend@^4.0.0.
npm WARN deprecated lodash.padleft@3.1.1: This package has been discontinued in favor of lodash.padstart@^4.0.0.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN prefer global marked@0.3.5 should be installed with -g
npm WARN prefer global jsonlint@1.6.2 should be installed with -g
npm WARN prefer global babel@5.8.35 should be installed with -g
npm WARN prefer global jshint@2.5.10 should be installed with -g

> appium@1.5.0 prepublish /home/shadeimi/git/appium_v1.5
> gulp prepublish

[11:56:03] Using gulpfile ~/git/appium_v1.5/gulpfile.js
[11:56:03] Starting 'prepublish'...
[11:56:03] Starting 'clean'...
[11:56:03] Finished 'clean' after 18 ms
[11:56:03] Starting 'transpile'...

/home/shadeimi/git/appium_v1.5/node_modules/babel-core/lib/transformation/file/options/option-manager.js:100
      opts = jsonCache[content] = jsonCache[content] || json.parse(content);
                                                             ^
SyntaxError: /home/shadeimi/package.json: Error while parsing JSON - Unexpected end of input
    at Object.parse (native)
    at OptionManager.addConfig (/home/shadeimi/git/appium_v1.5/node_modules/babel-core/lib/transformation/file/options/option-manager.js:100:62)
    at OptionManager.findConfigs (/home/shadeimi/git/appium_v1.5/node_modules/babel-core/lib/transformation/file/options/option-manager.js:171:32)
    at OptionManager.init (/home/shadeimi/git/appium_v1.5/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at File.initOptions (/home/shadeimi/git/appium_v1.5/node_modules/babel-core/lib/transformation/file/index.js:147:75)
    at new File (/home/shadeimi/git/appium_v1.5/node_modules/babel-core/lib/transformation/file/index.js:137:22)
    at Pipeline.transform (/home/shadeimi/git/appium_v1.5/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at DestroyableTransform._transform (/home/shadeimi/git/appium_v1.5/node_modules/gulp-babel/index.js:30:20)
    at DestroyableTransform.Transform._read (/home/shadeimi/git/appium_v1.5/node_modules/readable-stream/lib/_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (/home/shadeimi/git/appium_v1.5/node_modules/readable-stream/lib/_stream_transform.js:160:12)
    at doWrite (/home/shadeimi/git/appium_v1.5/node_modules/readable-stream/lib/_stream_writable.js:335:12)
    at writeOrBuffer (/home/shadeimi/git/appium_v1.5/node_modules/readable-stream/lib/_stream_writable.js:321:5)
    at DestroyableTransform.Writable.write (/home/shadeimi/git/appium_v1.5/node_modules/readable-stream/lib/_stream_writable.js:248:11)
    at DestroyableTransform.ondata (/home/shadeimi/git/appium_v1.5/node_modules/readable-stream/lib/_stream_readable.js:583:20)
    at emitOne (events.js:90:13)
    at DestroyableTransform.emit (events.js:182:7)

npm WARN optional Skipping failed optional dependency //fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.8
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.8
npm ERR! Linux 4.4.3-300.fc23.x86_64
npm ERR! argv "/home/shadeimi/Software/node-v5.8.0-linux-x64/bin/node" "/home/shadeimi/Software/node-v5.8.0-linux-x64/bin/npm" "install" "."
npm ERR! node v5.8.0
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE
npm ERR! appium@1.5.0 prepublish: `gulp prepublish`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appium@1.5.0 prepublish script 'gulp prepublish'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the appium package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp prepublish
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs appium
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls appium
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/shadeimi/git/appium_v1.5/npm-debug.log
✘-1 ~/git/appium_v1.5 [v1.5.0 L|✔] 
11:56 $ 
```

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by imurchie** [comment]
Can you post, in a [gist](https://gist.github.com/), `/home/shadeimi/git/appium_v1.5/npm-debug.log`?

**Comment by SrinivasanTarget** [comment]
@triager please close
