### ISSUE TITLE
Unable to install appium via npm  (issue with appium-selendroid-driver)

### ISSUE THREAD

**Issue by SGDSmith** [appium/appium#6276]
I am having troubles installing appium via npm, it seems to throw a few errors for appium-chromedriver and appium-selendroid-driver before exiting.

I run the following command:
npm install -g appium

And this results in the following error:
Tried too many times to install selendroid, failing

/usr/local/lib/node_modules/appium/node_modules/appium-selendroid-driver/bin/install.js:18
      throw err;
            ^
TypeError: fn must be a function

    See http://goo.gl/916lJJ

    at Function.Promise.promisify (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/promisify.js:268:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/appium/node_modules/appium-support/build/lib/fs.js:141:35)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/appium/node_modules/appium-support/build/lib/tempdir.js:12:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/appium/node_modules/appium-support/build/index.js:11:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/appium/node_modules/appium-selendroid-installer/build/lib/setup.js:21:22)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
npm ERR! appium-selendroid-driver@1.2.2 install: `node ./bin/install.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the appium-selendroid-driver@1.2.2 install script.
npm ERR! This is most likely a problem with the appium-selendroid-driver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls appium-selendroid-driver
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 15.3.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "appium"
npm ERR! cwd /Users/stevensmith
npm ERR! node -v v0.10.30
npm ERR! npm -v 2.0.0-alpha-5
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/stevensmith/npm-debug.log
npm ERR! not ok code 0

I have a JDK installed and the relevant JAVA_HOME paths set but this does not seem to fix the issue. 
Running on Mac OSX 10.11.3

The npm-debug.log file contents can be found here: https://gist.github.com/SGDSmith/4e25f8f383f1feeecad4

**Comment by scottdixon** [comment]
Are you able to run `jar` from the command line?

**Comment by SGDSmith** [comment]
Managed to get it working, seems it was a problem using an out of date version of node.

Installed the latest stable version (5.8.0) and appium appeared to install correctly and I can start appium by typing appium into the terminal.

**Comment by scottdixon** [comment]
Thanks for the update.

**Comment by rajabhaskar** [comment]
I am getting below issue while installing appium. I have installed latest version of nodejs i.e. 6.2.1 and tried to type "npm install -g appium". Installation successfully done till selendroid installer and at Selendroid installer I have got below error which aborted setup ... please help me

C:\Users\msi1370\AppData\Roaming\npm
`-- (empty)

npm WARN optional Skipping failed optional dependency /appium/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fseve
nts@1.0.12
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "appium"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE

npm ERR! appium-selendroid-driver@1.3.3 install: `node ./bin/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the appium-selendroid-driver@1.3.3 install script 'node ./bin
/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the appium-selendroid-dri
ver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs appium-selendroid-driver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls appium-selendroid-driver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\msi1370\npm-debug.log

**Comment by getyourbots** [comment]
@rajabhaskar same thing here

**Comment by chiragintersoft** [comment]
### npm install -g appium
**Getting this error while Installing appium with command npm install -g appium**


![appuim](https://user-images.githubusercontent.com/24715012/56557988-c67e5000-65ba-11e9-88d6-f18db77073d9.PNG)

**Comment by imurchie** [comment]
@chiragintersoft Please post the _full_ logs, as a link to a [gist](https://gist.github.com). A screenshot of a tiny portion is not enough to diagnose anything.
