### ISSUE TITLE
[Appium 1.5][SelendroidDriver] Reset not working

### ISSUE THREAD

**Issue by sahilsingla90** [appium/appium#6297]
## The problem

I am running the server

```
./node_modules/appium/build/lib/main.js --port 4491 --log /path/to/logs/4491-20160315190629.log --session-override --log-timestamp --address 127.0.0.1 --port 4491  --selendroid-port 8081 --default-capabilities "{\"automationName\":\"Selendroid\",\"platformName\":\"Android\",\"udid\":\"XXXXXX\",\"orientation\":\"LANDSCAPE\",\"appPackage\":\"com.xxxx.xxx.xxxx.xxx.xxx\",\"fullReset\":true}"
```

I have my SelendroidDriver setup and it works but when I try to reset the app using
https://github.com/appium/node-mobile-json-wire-protocol/blob/master/lib/routes.js#L375-L376
I get the error in https://gist.github.com/sahilsingla90/9cc81e23dd94e68ad1df
## Environment

Mac OS X El Capitan
ChromeDriver: 2.16
Device: Real Android 4.4.2 (Samsung Galaxy S4)
Node: 0.12.4
## Trial

I also tried using https://github.com/appium/node-mobile-json-wire-protocol/blob/master/lib/routes.js#L326-L328 followed by https://github.com/appium/node-mobile-json-wire-protocol/blob/master/lib/routes.js#L323-L325
but

```
  '/wd/hub/session/:sessionId/appium/device/remove_app': {
    POST: {command: 'removeApp', payloadParams: {required: [['appId'], ['bundleId']]}}
  },
```

seems to be buggy too as it gives the error:

```
Selenium::WebDriver::Error::WebDriverError: unexpected response, code=400, content-type="text/html"
Parameters were incorrect. We wanted {"required":[["appId"],["bundleId"]]} and you sent ["appId","bundleId"]
from /path/to/vendor/bundle/ruby/2.1.0/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/http/common.rb:85:in `create_response'
```

**Comment by imurchie** [comment]
The second method (`remove_app`) takes _either_ `appId` or `bundleId`. It looks like you're sending both?

For the first, can you send the full log? Or at least the information about the build (the first line of the log) so I can make sense of the line numbers in your stack trace.

Thanks!

**Comment by sahilsingla90** [comment]
> The second method (remove_app) takes either appId or bundleId. It looks like you're sending both?

Thanks for pointing out my mistake.

```
2016-03-18 11:09:52:599 - [Appium] Welcome to Appium v1.5.0 (REV 57bf2515bdb38ed063ffd9b437e0b2f608ab3252)
2016-03-18 11:09:52:602 - [Appium] Non-default server args:
2016-03-18 11:09:52:604 - [Appium]   address: '127.0.0.1'
2016-03-18 11:09:52:605 - [Appium]   port: 4491
2016-03-18 11:09:52:605 - [Appium]   sessionOverride: true
2016-03-18 11:09:52:605 - [Appium]   log: '/path/to/logs/4491-20160318200759.log'
2016-03-18 11:09:52:606 - [Appium]   logTimestamp: true
2016-03-18 11:09:52:606 - [Appium]   selendroidPort: 8081
2016-03-18 11:09:52:607 - [Appium]   defaultCapabilities: { automationName: 'Selendroid',
  platformName: 'Android',
  udid: '56de4bf5',
  fullReset: true,
  orientation: 'LANDSCAPE',
  appPackage: 'xxxx.xxx.xxxx.xxx.xxx' }
2016-03-18 11:09:52:608 - [Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
2016-03-18 11:09:52:619 - [Appium]   automationName: 'Selendroid'
2016-03-18 11:09:52:619 - [Appium]   platformName: 'Android'
2016-03-18 11:09:52:620 - [Appium]   udid: '56de4bf5'
2016-03-18 11:09:52:620 - [Appium]   fullReset: true
2016-03-18 11:09:52:620 - [Appium]   orientation: 'LANDSCAPE'
2016-03-18 11:09:52:621 - [Appium]   appPackage: 'xxxx.xxx.xxxx.xxx.xxx'
2016-03-18 11:09:52:686 - [Appium] Appium REST http interface listener started on 127.0.0.1:4491
2016-03-18 11:10:46:703 - [HTTP] --> POST /wd/hub/session
2016-03-18 11:10:46:728 - [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/path/to/app.apk
2016-03-18 11:10:46:732 - [Appium] Creating new SelendroidDriver session
2016-03-18 11:10:46:732 - [Appium] Capabilities:
2016-03-18 11:10:46:733 - [Appium]   app: '/path/to/app.apk'
2016-03-18 11:10:46:733 - [Appium]   deviceName: 'SC-04E'
2016-03-18 11:10:46:734 - [Appium]   newCommandTimeout: 9999
2016-03-18 11:10:46:734 - [Appium]   udid: '56de4bf5'
2016-03-18 11:10:46:734 - [Appium]   platformName: 'Android'
2016-03-18 11:10:46:735 - [Appium]   automationName: 'Selendroid'
2016-03-18 11:10:46:735 - [Appium]   fullReset: true
2016-03-18 11:10:46:735 - [Appium]   orientation: 'LANDSCAPE'
2016-03-18 11:10:46:736 - [Appium]   appPackage: 'xxx.xxx.xx.x.x.x'
2016-03-18 11:10:46:748 - [BaseDriver] Session created with session id: 2ecc3ba4-93a4-47a3-b1df-a6ea2cd45a19
2016-03-18 11:10:46:749 - [BaseDriver] Using local app '/path/to/app.apk'
2016-03-18 11:10:46:750 - [debug] [Selendroid] Checking whether app is actually present
2016-03-18 11:10:46:752 - [debug] [AndroidDriver] Getting Java version
2016-03-18 11:10:47:052 - [AndroidDriver] Java version is: 1.8.0_71
```

```
2016-03-18 11:12:03:660 - [HTTP] --> POST /wd/hub/session/2ecc3ba4-93a4-47a3-b1df-a6ea2cd45a19/appium/app/reset
2016-03-18 11:12:03:663 - [MJSONWP] Calling AppiumDriver.reset() with args: ["2ecc3ba4-93a4-47a3-b1df-a6ea2cd45a19"]
2016-03-18 11:12:03:664 - [AndroidDriver] Running old fashion reset (reinstall)
2016-03-18 11:12:03:665 - [debug] [ADB] Getting connected devices...
2016-03-18 11:12:03:678 - [debug] [ADB] 1 device(s) connected
2016-03-18 11:12:03:679 - [debug] [ADB] Running /path/to/adb with args: ["-P",5037,"-s","56de4bf5","shell","am","force-stop","xxx.xxx.xx.xxx"]
2016-03-18 11:12:04:582 - [debug] [ADB] Getting connected devices...
2016-03-18 11:12:04:595 - [debug] [ADB] 1 device(s) connected
2016-03-18 11:12:04:596 - [debug] [ADB] Running /path/to/adb with args: ["-P",5037,"-s","56de4bf5","shell","pm","clear","xxx.xxx.xxx.xxx"]
2016-03-18 11:12:05:612 - [debug] [ADB] Uninstalling xxxx.x.xxx.xxx.xxx
2016-03-18 11:12:05:613 - [debug] [ADB] Getting connected devices...
2016-03-18 11:12:05:628 - [debug] [ADB] 1 device(s) connected
2016-03-18 11:12:05:628 - [debug] [ADB] Running /path/to/adb with args: ["-P",5037,"-s","56de4bf5","shell","am","force-stop","xxx.xxx.xxx.xxx"]
2016-03-18 11:12:06:494 - [debug] [ADB] Running /path/to/adb with args: ["-P",5037,"-s","56de4bf5","uninstall","xxxx.xxx.xxx.xxx"]
2016-03-18 11:12:08:527 - [ADB] App was uninstalled
2016-03-18 11:12:08:827 - [AndroidDriver] Remote apk path is /data/local/tmp/64c479facc3c1a343789453f0cec3fbc.apk
2016-03-18 11:12:08:828 - [debug] [ADB] Getting connected devices...
2016-03-18 11:12:08:840 - [debug] [ADB] 1 device(s) connected
2016-03-18 11:12:08:841 - [debug] [ADB] Running /path/to/adb with args: ["-P",5037,"-s","56de4bf5","shell","ls","/data/local/tmp/64c479facc3c1a343789453f0cec3fbc.apk"]
2016-03-18 11:12:08:869 - [debug] [AndroidDriver] Checking if app is installed
2016-03-18 11:12:08:869 - [debug] [ADB] Getting install status for xxx.xxx.xxx.xxx
2016-03-18 11:12:08:870 - [debug] [ADB] Device API level: 19
2016-03-18 11:12:08:870 - [debug] [ADB] Getting connected devices...
2016-03-18 11:12:08:883 - [debug] [ADB] 1 device(s) connected
2016-03-18 11:12:08:884 - [debug] [ADB] Running /path/to/adb with args: ["-P",5037,"-s","56de4bf5","shell","pm","list","packages","-3","xxx.xxx.xx.xxx"]
2016-03-18 11:12:09:878 - [debug] [ADB] App is  not installed
2016-03-18 11:12:09:879 - [AndroidDriver] Apk is not yet installed
2016-03-18 11:12:09:879 - [AndroidDriver] installing apk from remote
2016-03-18 11:12:09:881 - [debug] [ADB] Getting connected devices...
2016-03-18 11:12:09:896 - [debug] [ADB] 1 device(s) connected
2016-03-18 11:12:09:897 - [debug] [ADB] Running /path/to/adb with args: ["-P",5037,"-s","56de4bf5","shell","mkdir","-p","/data/local/tmp"]
2016-03-18 11:12:09:924 - [AndroidDriver] Clearing out any existing remote apks with the same hash
2016-03-18 11:12:09:925 - [debug] [AndroidDriver] Removing any old apks
2016-03-18 11:12:09:925 - [debug] [AndroidDriver] Except ["64c479facc3c1a343789453f0cec3fbc"]
2016-03-18 11:12:09:925 - [debug] [ADB] Getting connected devices...
2016-03-18 11:12:09:938 - [debug] [ADB] 1 device(s) connected
2016-03-18 11:12:09:939 - [debug] [ADB] Running /path/to/adb with args: ["-P",5037,"-s","56de4bf5","shell","ls","/data/local/tmp/*.apk"]
2016-03-18 11:12:09:968 - [debug] [ADB] Uninstalling xxx.xxx.xxx.xxx
2016-03-18 11:12:09:969 - [debug] [ADB] Getting connected devices...
2016-03-18 11:12:09:982 - [debug] [ADB] 1 device(s) connected
2016-03-18 11:12:09:982 - [debug] [ADB] Running /path/to/adb with args: ["-P",5037,"-s","56de4bf5","shell","am","force-stop","xxx.xxx.xxx.xxx"]
2016-03-18 11:12:10:886 - [debug] [ADB] Running /path/to/adb with args: ["-P",5037,"-s","56de4bf5","uninstall","xxx.xxx.xxx.xxx"]
2016-03-18 11:12:12:037 - [ADB] App was not uninstalled, maybe it wasn't on device?
2016-03-18 11:12:12:038 - [debug] [ADB] Getting connected devices...
2016-03-18 11:12:12:050 - [debug] [ADB] 1 device(s) connected
2016-03-18 11:12:12:051 - [debug] [ADB] Running /path/to/adb with args: ["-P",5037,"-s","56de4bf5","shell","pm","install","-r","/data/local/tmp/64c479facc3c1a343789453f0cec3fbc.apk"]
2016-03-18 11:12:17:599 - [MJSONWP] Encountered internal error running command: TypeError: undefined is not a function
    at SelendroidDriver.callee$0$0$ (lib/commands/general.js:175:21)
    at tryCatch (/path/to/node_modules/appium/node_modules/appium-android-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/path/to/node_modules/appium/node_modules/appium-android-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/path/to/node_modules/appium/node_modules/appium-android-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/path/to/node_modules/appium/node_modules/appium-android-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/path/to/node_modules/appium/node_modules/appium-android-driver/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /path/to/node_modules/appium/node_modules/appium-android-driver/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/path/to/node_modules/appium/node_modules/appium-android-driver/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at process._tickCallback (node.js:355:11)
2016-03-18 11:12:17:602 - [HTTP] <-- POST /wd/hub/session/2ecc3ba4-93a4-47a3-b1df-a6ea2cd45a19/appium/app/reset 500 13939 ms - 198
```

**Comment by sahilsingla90** [comment]
@imurchie : I just re-installed the application, and on trying to launch it a similar error as above comes up, thus it must be this part which has a problem
```
[1] pry(#<RSpec::ExampleGroups::ShellappSdk::MobageApi>)> drivers.fetch(:test_app).launch
2016-03-18 11:31:04:552 - [MJSONWP] Encountered internal error running command: TypeError: undefined is not a function
    at SelendroidDriver.callee$0$0$ (lib/commands/general.js:142:14)
    at tryCatch (/path/to/node_modules/appium/node_modules/appium-android-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/path/to/node_modules/appium/node_modules/appium-android-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/path/to/node_modules/appium/node_modules/appium-android-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/path/to/node_modules/appium/node_modules/appium-android-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/path/to/node_modules/appium/node_modules/appium-android-driver/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /path/to/node_modules/appium/node_modules/appium-android-driver/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/path/to/node_modules/appium/node_modules/appium-android-driver/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at process._tickCallback (node.js:355:11)
Selenium::WebDriver::Error::UnknownError: An unknown server-side error occurred while processing the command. Original error: undefined is not a function
from /path/to/vendor/bundle/ruby/2.1.0/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/response.rb:70:in `assert_ok'
```

**Comment by jlipps** [comment]
@sahilsingla90 does this reproduce on latest Appium (1.6.3)?
