### ISSUE TITLE
Appium closes connection while waiting for screenshot

### ISSUE THREAD

**Issue by npgarcia** [appium/appium#6305]
## The problem

Time to time I see that when trying to take a screenshot, I get this error:
`java.lang.RuntimeException: Unexpected result for screenshot command: null
    at org.openqa.selenium.remote.RemoteWebDriver.getScreenshotAs(RemoteWebDriver.java:334) ~[selenium-remote-driver-2.48.2.jar:na]
    at com.jcrew.steps.StartingSteps.quitDriver(StartingSteps.java:109) ~[classes/:na]
    at sun.reflect.GeneratedMethodAccessor28.invoke(Unknown Source) ~[na:na]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_11]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_11]
    at cucumber.runtime.Utils$1.call(Utils.java:37) [cucumber-core-1.2.3.jar:na]
    at cucumber.runtime.Timeout.timeout(Timeout.java:13) [cucumber-core-1.2.3.jar:na]
    at cucumber.runtime.Utils.invoke(Utils.java:31) [cucumber-core-1.2.3.jar:na]
    at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60) [cucumber-java-1.2.3.jar:na]
    at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:231) [classes/:na]
    at cucumber.runtime.Runtime.runHooks(Runtime.java:207) [classes/:na]
    at cucumber.runtime.Runtime.runAfterHooks(Runtime.java:201) [classes/:na]
    at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:46) [cucumber-core-1.2.3.jar:na]
    at cucumber.runtime.junit.ExecutionUnitRunner.run(ExecutionUnitRunner.java:91) [cucumber-junit-1.2.3.jar:na]
    at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:63) [cucumber-junit-1.2.3.jar:na]
    at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:18) [cucumber-junit-1.2.3.jar:na]
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit-4.12.jar:4.12]
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
    at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:70) [cucumber-junit-1.2.3.jar:na]
    at cucumber.api.junit.Cucumber.runChild(Cucumber.java:93) [cucumber-junit-1.2.3.jar:na]
    at cucumber.api.junit.Cucumber.runChild(Cucumber.java:37) [cucumber-junit-1.2.3.jar:na]
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit-4.12.jar:4.12]
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
    at cucumber.api.junit.Cucumber.run(Cucumber.java:98) [cucumber-junit-1.2.3.jar:na]
    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283) [surefire-junit4-2.18.jar:2.18]
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173) [surefire-junit4-2.18.jar:2.18]
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153) [surefire-junit4-2.18.jar:2.18]
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128) [surefire-junit4-2.18.jar:2.18]
    at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203) [surefire-booter-2.18.jar:2.18]
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155) [surefire-booter-2.18.jar:2.18]
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103) [surefire-booter-2.18.jar:2.18]`
## Environment
- Appium version: 1.4.13
- Last Appium version that did not exhibit the issue (if applicable): Not Applicable
- Desktop OS/version used to run Appium: Yosemite 10.10.5
- Node.js version (unless using Appium.app|exe): 5.3
- Mobile platform/version under test: iPhone 6 9.2 and 9.1
- Real device or emulator/simulator: Real device and Simulator
- Appium CLI or Appium.app|exe: Appium CLI
## Details

I am getting a screenshot time to time when my test is failing. I see Appium returns an exception. Looking into Appium Logs, I am able to identify when is requesting the screenshot to instruments, but is not receiving any answer. Eventually Appium closes the session because is not receiving any command, making my screenshot unsuccessful. This will make the resto of my tests fails because the session does not exist anymore.
## Link to Appium logs

I can't put all the log because is really big, and is in a machine that is continuously running tests. But here is some lines before and after the error:
### Before Error

`info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"},"isShuttingDown":false},"sessionId":"71ca4ab6-59c6-4d66-80c3-7f2a2ed5ce6e"}
info: <-- GET /wd/hub/status 200 1.203 ms - 179 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"},"isShuttingDown":false},"sessionId":"71ca4ab6-59c6-4d66-80c3-7f2a2ed5ce6e"}
info: [debug] [REMOTE] Debugger web socket received data: {"result":{"result":{"type":"string","value":"{\"status\":0,\"value\":\"(1)\"}"},"wasThrown":false},"id":10912}
info: [debug] Responding to client with success: {"status":0,"value":"(1)","sessionId":"71ca4ab6-59c6-4d66-80c3-7f2a2ed5ce6e"}
info: <-- GET /wd/hub/session/71ca4ab6-59c6-4d66-80c3-7f2a2ed5ce6e/element/8969/text 200 61.639 ms - 77 {"status":0,"value":"(1)","sessionId":"71ca4ab6-59c6-4d66-80c3-7f2a2ed5ce6e"}
info: --> GET /wd/hub/session/71ca4ab6-59c6-4d66-80c3-7f2a2ed5ce6e/screenshot {}
info: [debug] Pushing command to appium work queue: "au.getScreenOrientation()"
info: [debug] Sending command to instruments: au.getScreenOrientation()
info: --> GET /wd/hub/status {}
info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"},"isShuttingDown":false},"sessionId":"71ca4ab6-59c6-4d66-80c3-7f2a2ed5ce6e"}
info: <-- GET /wd/hub/status 200 0.943 ms - 179 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"},"isShuttingDown":false},"sessionId":"71ca4ab6-59c6-4d66-80c3-7f2a2ed5ce6e"}`
### After Error

`info: [debug] Didn't get a new command in 240 secs, shutting down...
info: Shutting down appium session
info: [debug] Stopping safariLauncher
info: [debug] Stopping iOS log capture
info: [debug] [REMOTE] Executing 'execute_script' atom in default context
info: [debug] [REMOTE] Sending javascript command
info: [debug] [REMOTE] Remote debugger data sent [{"method":"Runtime.evaluate","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true,"expression":"(function(){return function(){var g=this;\nfunctio...]
info: [debug] Reset not set, not ending sim or cleaning up app state
info: [debug] Cleaning up appium session
info: [debug] We shut down because no new commands came in
info: [debug] [REMOTE] Debugger web socket received data: {"result":{"result":{"type":"object","value":{"status":0,"value":null}},"wasThrown":false},"id":10913}
info: --> GET /wd/hub/status {}
info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
info: <-- GET /wd/hub/status 200 0.895 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
info: [debug] [REMOTE] Disconnecting from remote debugger`
## Code To Reproduce Issue [ Good To Have ]

This is the code used to take a screenshot:
`if (driver != null && (scenario.isFailed() || scenario.getName().contains(TAKE_SCREENSHOT))) {
            logger.debug("Taking screenshot of scenario {}", scenario.getName());
            try {
                final byte[] screenshot = ((TakesScreenshot) driver).getScreenshotAs(OutputType.BYTES);
                scenario.embed(screenshot, "image/png");
            } catch (Exception e){
                logger.error("An exception happened when taking step screenshot after scenario", e);
            }
}`

**Comment by SrinivasanTarget** [comment]
@npgarcia Please try a latest version of appium 1.5 and java-client 3.4.0, update us if you still face any issues with logs in form of gist

**Comment by npgarcia** [comment]
@SrinivasanTarget unfortunately I can't just go and update Appium in our nodes, since I do not know if everything will start to fail, and is a risk I cannot mitigate right now. But I did got the logs for version 1.4.13 [here](https://gist.github.com/anonymous/95814666a2cbc4981b93)

I will eventually update the nodes, but it will be very helpful if someone can take a look.

**Comment by SrinivasanTarget** [comment]
@npgarcia Appium 1.5 is a complete re-arch, would be great if you give a try on Appium 1.5 and update us with the logs incase of any issues. I didn't see any issues related to this with 1.5.

**Comment by SrinivasanTarget** [comment]
Just to group this #4805

**Comment by npgarcia** [comment]
@SrinivasanTarget I am not able to install version 1.5 in my nodes since it is blocking npm (corporate rules that I can't fight now). I don't see bin/appium file in the repo. How can I run Appium from source?

**Comment by npgarcia** [comment]
Someone in the forum told me how to run from source [here](https://discuss.appium.io/t/run-appium-1-5-from-source/9242).
So I will work in seeing if I am able to reproduce the problem in version 1.5 in one node.

**Comment by SrinivasanTarget** [comment]
Ok @npgarcia
