### ISSUE TITLE
unable to start appium session due to following error in appium 

### ISSUE THREAD

**Issue by krishachetan89** [appium/appium#6337]
## The problem

Not able to start automation due to this error while running the code
## Environment

appium version 1.0.5
android version 6.0.2 
ubuntu 15.10
language - python 
- Appium CLI or Appium.app|exe:
## Details

i tried aapt dump badging from terminal , works fine only with appium its causing problems

Describe in more detail the problem you have been experiencing, if necessary.
## Link to Appium logs

```
[Appium] Welcome to Appium v1.5.0
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session 
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformVersion":"6.0.2","deviceName":"ZH8001J6DW","app":"/home/sowmya/PycharmProjects/sowmyatest/com.flipkart.android-4.4.2-APK4Fun.com.apk","p...
[Appium] Creating new AndroidDriver session
[Appium] Capabilities:
[Appium]   platformVersion: '6.0.2'
[Appium]   deviceName: 'ZH8001J6DW'
[Appium]   app: '/home/sowmya/PycharmProjects/sowmyatest/com.flipkart.android-4.4.2-APK4Fun.com.apk'
[Appium]   platformName: 'Android'
[BaseDriver] Session created with session id: 723bbb09-727f-40bf-8065-a369380a541d
[debug] [AndroidDriver] Getting Java version
[AndroidDriver] Java version is: 1.7.0_95
[ADB] Checking whether adb is present
[ADB] Using adb from /home/sowmya/android-sdk-linux/platform-tools/adb
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[AndroidDriver] Using device: ZH8001J6DW
[ADB] Checking whether adb is present
[ADB] Using adb from /home/sowmya/android-sdk-linux/platform-tools/adb
[debug] [ADB] Setting device id to ZH8001J6DW
[BaseDriver] Using local app '/home/sowmya/PycharmProjects/sowmyatest/com.flipkart.android-4.4.2-APK4Fun.com.apk'
[debug] [AndroidDriver] Checking whether app is actually present
[AndroidDriver] Starting Android session
[debug] [ADB] Running /home/sowmya/android-sdk-linux/platform-tools/adb with args: ["-P",5037,"-s","ZH8001J6DW","wait-for-device"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /home/sowmya/android-sdk-linux/platform-tools/adb with args: ["-P",5037,"-s","ZH8001J6DW","shell","echo","ping"]
[debug] [Logcat] Starting logcat capture
[debug] [AndroidDriver] Pushing settings apk to device...
[debug] [ADB] Running /home/sowmya/android-sdk-linux/platform-tools/adb with args: ["-P",5037,"-s","ZH8001J6DW","install","/home/sowmya/.linuxbrew/lib/node_modules/appium/node_modules/io.appium.settings/bin/settings_apk-debug.apk"]
[debug] [AndroidDriver] Pushing unlock helper app to device...
[debug] [ADB] Running /home/sowmya/android-sdk-linux/platform-tools/adb with args: ["-P",5037,"-s","ZH8001J6DW","install","/home/sowmya/.linuxbrew/lib/node_modules/appium/node_modules/appium-unlock/bin/unlock_apk-debug.apk"]
[ADB] Getting device platform version
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /home/sowmya/android-sdk-linux/platform-tools/adb with args: ["-P",5037,"-s","ZH8001J6DW","shell","getprop","ro.build.version.release"]
[debug] [AndroidDriver] Parsing package and activity from app manifest
[ADB] Checking whether aapt is present
[ADB] Using aapt from /home/sowmya/android-sdk-linux/build-tools/23.0.3/aapt
[ADB] Extracting package and launch activity from manifest
[ADB] Error: packageAndLaunchActivityFromManifest failed. Original error: Command '/home/sowmya/android-sdk-linux/build-tools/23.0.3/aapt dump badging /home/sowmya/PycharmProjects/sowmyatest/com.flipkart.android-4.4.2-APK4Fun.com.apk' errored out: Error: spawn /home/sowmya/android-sdk-linux/build-tools/23.0.3/aapt ENOENT
    at exports._errnoException (util.js:890:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (node.js:383:13)
    at process._tickCallback (node.js:407:11)
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at ADB.callee$0$0$ (lib/tools/android-manifest.js:88:9)
    at tryCatch (/home/sowmya/.linuxbrew/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/home/sowmya/.linuxbrew/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/home/sowmya/.linuxbrew/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/home/sowmya/.linuxbrew/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/home/sowmya/.linuxbrew/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /home/sowmya/.linuxbrew/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/home/sowmya/.linuxbrew/lib/node_modules/appium/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at _combinedTickCallback (node.js:376:9)
    at process._tickCallback (node.js:407:11)
 [Error: packageAndLaunchActivityFromManifest failed. Original error: Command '/home/sowmya/android-sdk-linux/build-tools/23.0.3/aapt dump badging /home/sowmya/PycharmProjects/sowmyatest/com.flipkart.android-4.4.2-APK4Fun.com.apk' errored out: Error: spawn /home/sowmya/android-sdk-linux/build-tools/23.0.3/aapt ENOENT
    at exports._errnoException (util.js:890:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (node.js:383:13)
    at process._tickCallback (node.js:407:11)]
[debug] [AndroidDriver] Shutting down Android driver
[AndroidDriver] Cannot shut down Android driver; it has already shut down
[MJSONWP] Encountered internal error running command: Error: packageAndLaunchActivityFromManifest failed. Original error: Command '/home/sowmya/android-sdk-linux/build-tools/23.0.3/aapt dump badging /home/sowmya/PycharmProjects/sowmyatest/com.flipkart.android-4.4.2-APK4Fun.com.apk' errored out: Error: spawn /home/sowmya/android-sdk-linux/build-tools/23.0.3/aapt ENOENT
    at exports._errnoException (util.js:890:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (node.js:383:13)
    at process._tickCallback (node.js:407:11)
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at ADB.callee$0$0$ (lib/tools/android-manifest.js:88:9)
    at tryCatch (/home/sowmya/.linuxbrew/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/home/sowmya/.linuxbrew/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/home/sowmya/.linuxbrew/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/home/sowmya/.linuxbrew/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/home/sowmya/.linuxbrew/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /home/sowmya/.linuxbrew/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/home/sowmya/.linuxbrew/lib/node_modules/appium/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at _combinedTickCallback (node.js:376:9)
    at process._tickCallback (node.js:407:11)
[HTTP] <-- POST /wd/hub/session 500 7354 ms - 721 
```

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!
## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

``` python
#-*- coding: utf-8 -*-
__author__ = 'chetan.krishna'
import os
import time
import unittest
from time import sleep
from appium import webdriver


# Returns absolute path relative to this file
PATH = lambda p: os.path.abspath(
    os.path.join(os.path.dirname(__file__), p)
)


class AndroidTests(unittest.TestCase):
    def setUp(self):
        desired_caps = {}
# Specify platform below(Android, iOS)
        desired_caps['platformName'] = 'Android'
# Specify OS version(Settings->About phone -> android version)
        desired_caps['platformVersion'] = '6.0.2'
# Obtain the Device name from Adb[For Android](Terminal Command: "adb devices")
        desired_caps['deviceName'] = 'ZH8001J6DW'
        #desired_caps['noReset'] = False
# Specify the path to Application
        desired_caps['app'] = PATH('com.flipkart.android-4.4.2-APK4Fun.com.apk')
# Wait for email login activity to appear
        #desired_caps["appWaitActivity"]= ('')
        self.driver = webdriver.Remote('http://0.0.0.0:4723/wd/hub', desired_caps)

    #def tearDown(self):
# end the session
        #self.driver.quit()


    def test_one(self):
        time.sleep(10)
        try:
            print("TESTING WHETHER USER CAN ACCESS THE APP")
            self.driver.find_element_by_name("Allow").click()
            self.driver.implicitly_wait(30)
        except:
            print("test failed")
        finally:
            self.driver.find_element_by_id("com.flipkart.android:id/btn_mlogin").click()
            self.driver.implicitly_wait(30)
        try:
            self.driver.find_element_by_id("com.flipkart.android:id/mobile_login_signup_edit_text").clear()
            self.driver.implicitly_wait(30)
            self.driver.find_element_by_id("com.flipkart.android:id/mobile_login_signup_edit_text").send_keys("sowmya.ec45@gmail.com")
            self.driver.implicitly_wait(30)
            self.driver.find_element_by_id('com.flipkart.android:id/etPass').click()
            print("accepted given password")
            self.driver.find_element_by_id('com.flipkart.android:id/etPass').send_keys("golden@89")
            self.driver.implicitly_wait(30)
        except:
            print("not accepted the password")

        finally:
            #self.driver.hide_keyboard()
            self.driver.back()
            self.driver.implicitly_wait(30)
        self.driver.find_element_by_id("com.flipkart.android:id/btn_mlogin").click()
        self.driver.implicitly_wait(30)
        time.sleep(6)
        self.driver.find_element_by_id("com.flipkart.android:id/overflowIcon").click()
        self.driver.implicitly_wait(30)
        self.driver.find_element_by_id("com.flipkart.android:id/search_widget_textbox").click()
        self.driver.implicitly_wait(30)
        self.driver.find_element_by_id("com.flipkart.android:id/search_autoCompleteTextView").send_keys("shoes")
        self.driver.implicitly_wait(30)
        self.driver.find_element_by_name("shoes").click()
        self.driver.implicitly_wait(30)
        self.driver.find_element_by_name("Allow").click()
        self.driver.implicitly_wait(30)
        time.sleep(5)
        try:
            for x in range(0, 3):
                self.driver.implicitly_wait(6)
                self.driver.swipe(start_x=69,start_y=205,end_x=407,end_y=205)
                self.driver.implicitly_wait(10)
                self.driver.swipe(start_x=407,start_y=205,end_x=69,end_y=205)
                self.driver.implicitly_wait(10)
                #self.driver.swipe(start_x=259,start_y=670,end_x=259,end_y=343)
                self.driver.implicitly_wait(10)
            for x in range(0, 3):
                self.driver.implicitly_wait(10)
                self.driver.swipe(start_x=259,start_y=670,end_x=259,end_y=343)
                self.driver.implicitly_wait(10)
        except:
            print ("swipe failed")
        self.driver.find_element_by_id("com.flipkart.android:id/product_list_product_item_image").click()
        self.driver.implicitly_wait(30)
        self.driver.find_element_by_id("com.flipkart.android:id/product_page_buy_button").click()
        self.driver.implicitly_wait(30)
        self.driver.find_element_by_id("com.flipkart.android:id/product_page_swatch_item_text").click()
        self.driver.implicitly_wait(30)
        self.driver.find_element_by_id("com.flipkart.android:id/product_page_buy_button").click()
        self.driver.implicitly_wait(30)

if __name__ == '__main__':
    suite = unittest.TestLoader().loadTestsFromTestCase(AndroidTests)
    unittest.TextTestRunner(verbosity=0).run(suite)
```

**Comment by imurchie** [comment]
Does `/home/sowmya/android-sdk-linux/build-tools/23.0.3/aapt` exist?
