### ISSUE TITLE
Error when clicking on button in WebView context on IOS: Error received while executing atom: Cannot read property 'connected' of null

### ISSUE THREAD

**Issue by michalakm** [appium/appium#6367]
## The problem

I test hybrid app. When I switch to webview context (there are 2 webview contexts present) and I try to click on button in the context I get error "Error received while executing atom: Cannot read property 'connected' of null"

2016-04-04 10:12:48:042 - [HTTP] <-- GET /wd/hub/session/985901bb-81e1-4c7b-ab44-d0b0ca14443d/contexts 200 5 ms - 110 
2016-04-04 10:12:48:055 - [HTTP] --> POST /wd/hub/session/985901bb-81e1-4c7b-ab44-d0b0ca14443d/element {"using":"css selector","value":".green.ui-link.ui-btn.ui-shadow.ui-corner-all"}
2016-04-04 10:12:48:056 - [MJSONWP] Calling AppiumDriver.findElement() with args: ["css selector",".green.ui-link.ui-btn.ui-shadow.ui-corner-all","985901bb-81e1-4c7b-ab44-d0b0ca14443d"]
2016-04-04 10:12:48:056 - [debug] [iOS] Executing iOS command 'findElement'
2016-04-04 10:12:48:057 - [debug] [BaseDriver] Waiting up to 0 ms for condition
2016-04-04 10:12:48:058 - [debug] [iOS] Error received while executing atom: Cannot read property 'connected' of null
2016-04-04 10:12:48:593 - [MJSONWP] Encountered internal error running command: TypeError: Cannot read property 'connected' of null
    at WebKitRemoteDebugger.executeAtom$ (lib/remote-debugger.js:255:24)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at new Promise (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:197:7)
    at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:16)
    at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at WebKitRemoteDebugger.executeAtom (lib/remote-debugger.js:259:14)
    at IosDriver.callee$0$0$ (lib/commands/web.js:306:29)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at new Promise (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:197:7)
    at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:16)
    at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at IosDriver.callee$0$0 [as executeAtom] (lib/commands/web.js:306:14)
    at IosDriver.doFind$ (lib/commands/web.js:178:26)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at new Promise (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:197:7)
    at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:16)
    at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at doFind (lib/commands/web.js:177:13)
    at IosDriver.callee$1$0$ (lib/commands/timeout.js:56:24)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at new Promise (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:197:7)
2016-04-04 10:12:48:596 - [HTTP] <-- POST /wd/hub/session/985901bb-81e1-4c7b-ab44-d0b0ca14443d/element 500 540 ms - 211

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.1 (installed by npm install -g appium@1.5)
* Last Appium version that did not exhibit the issue (if applicable): 1.4.13
* Desktop OS/version used to run Appium: OS X Yosemite 10.10.5
* Node.js version: v0.12.0
* Mobile platform/version under test: iOS 9.1.2
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: appium client

## Link to Appium logs

[full log](https://gist.github.com/michalakm/fce38b9357cfaf619896161139a96866)

**Comment by imurchie** [comment]
Interesting. This seems to happen after getting the contexts multiple times. Investigating.

**Comment by imurchie** [comment]
I have fixed this in `appium-ios-driver`. The fix is published in `appium-ios-driver@1.11.0`. If you are running from source you ought to be able update it there. If you are running from npm, you can re-install, adding the `--no-shrinkwrap` flag to get the latest.

**Comment by michalakm** [comment]
I installed the newest version with appium-ios-driver@1.11.1 and verified - issue is fixed.
Thanks for quick reaction and fix.
