### ISSUE TITLE
Can't launch my own app with Appium

### ISSUE THREAD

**Issue by shawninder** [appium/appium#6377]
## The problem

I have just started experimenting with Appium by launching the example apps included in the [sample-code repository](https://github.com/appium/sample-code) locally, which works just fine.

But when I change [this line](https://github.com/appium/sample-code/blob/master/sample-code/examples/node/ios-webview.js#L21) to point to my own app (another webview), then it doesn't launch. It installs correctly on the simulator but refuses to launch (I see the home page zooming in as if it was going to launch, but it never launches, and instead just retries a couple of times and then closes the simulator). I made a gist of the [full appium output](https://gist.github.com/shawninder/f91702cf0f36b4b7e2078cc5c8082118), but here are the parts I think are unexpected:

```
[debug] [Instruments] [INST STDERR] 2016-04-07 09:48:57.658 instruments[94345:267296] Attempting to change event horizon while disengage
[debug] [Instruments] [INST STDERR] Instruments Trace Error : Target failed to run: The operation couldn’t be completed. (FBSOpenApplicationErrorDomain error 1.) : Failed to launch process with bundle identifier 'io.vigour.tester'
2016-04-07 09:48:57.659 instruments[94345:268545] Attempting to change event horizon while disengage
[debug] [Instruments] Instruments exited with code 253
[Instruments] Error launching instruments: Instruments crashed on startup
[debug] [iOSSim] Killing all iOS Simulators
[debug] [Instruments] Attempting to launch instruments, this is try #2
```

I get the above 5 times, and then:

```
[Instruments] Error: We exceeded the number of retries allowed for instruments to successfully start; failing launch
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at Instruments.launch$ (lib/instruments.js:216:15)
    at tryCatch (/Users/shawn/.nvm/versions/node/v4.2.2/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/shawn/.nvm/versions/node/v4.2.2/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/shawn/.nvm/versions/node/v4.2.2/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/shawn/.nvm/versions/node/v4.2.2/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Users/shawn/.nvm/versions/node/v4.2.2/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /Users/shawn/.nvm/versions/node/v4.2.2/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/Users/shawn/.nvm/versions/node/v4.2.2/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
 [Error: We exceeded the number of retries allowed for instruments to successfully start; failing launch]
[MJSONWP] Encountered internal error running command: Error: We exceeded the number of retries allowed for instruments to successfully start; failing launch
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at Instruments.launch$ (lib/instruments.js:216:15)
    at tryCatch (/Users/shawn/.nvm/versions/node/v4.2.2/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/shawn/.nvm/versions/node/v4.2.2/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/shawn/.nvm/versions/node/v4.2.2/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/shawn/.nvm/versions/node/v4.2.2/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Users/shawn/.nvm/versions/node/v4.2.2/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /Users/shawn/.nvm/versions/node/v4.2.2/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/Users/shawn/.nvm/versions/node/v4.2.2/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
[HTTP] <-- POST /wd/hub/session 500 149700 ms - 232
[HTTP] --> DELETE /wd/hub/session {}
[debug] [HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- DELETE /wd/hub/session 404 4 ms - 57
```

## Environment

Trying to run my app on an iPhone 5 Simulator:

```
exports.ios91 = {
  browserName: '',
  'appium-version': '1.3',
  platformName: 'iOS',
  platformVersion: '9.1',
  deviceName: 'iPhone 5',
  app: undefined // will be set later
};
```

```
$ appium --version
1.5.1
$ node -v
v4.2.2
```

OSX Yosemite version 10.10.5 (14F1605)

I tried with the command line `appium` and also with the GUI, but they both seem to produce the same result. I go the logs from the command line though, because with the GUI I can't copy the whole output (the top is cut off)...

## Details

I just clone the sample code repo and modified `sample-code/examples/node/helpers/caps` to use iOS 9.1 instead of 8.1 which I don't have on my machine. I also changed `sample-code/examples/node/ios-webview.js` to use this new config and to point to my app instead of the default webview app. I'm pretty sure all of this is correct but that my app needs to be built differently. Unfortunately I've already tried everything I can think of (Using a development certificate, exporting for a specific simulator instead of for all compatible devices, setting the archive scheme to debug). I've just run out of things to try...

## Link to Appium logs

[full appium output](https://gist.github.com/shawninder/f91702cf0f36b4b7e2078cc5c8082118)

## Code To Reproduce Issue [ Good To Have ]

The only other thing I could add here is the app I'm trying to run. If this can be helpful, just tell me and I will upload it somewhere....

**Comment by shawninder** [comment]
I got the problem resolved thanks to help from RatkoD, blueice349, Rohithnm and priyankshah217 in the gitter chat (many thanks).

My problem was that I was producing the `.app` file in the wrong way. I was archiving and exporting my app to a `.ipa` file and renaming that file to `.zip` and unzipping it and getting from its contents the `.app` file. The correct way was to simply `Project -> Build`, then find the `.app` file somewhere in the `Derived Data` directory (which I found in `Xcode -> Preferences -> Locations`, this is NOT in my project's directory). Pointing to that `.app` file works and appium launches the app successfully.

So my conclusion here is that this is not an issue with Appium itself, rather an issue with the xcode documentation.
