### ISSUE TITLE
[Appium 1.5.1] Instruments Trace Error : *** -[NSFileManager subpathsOfDirectoryAtPath:error:]: path is nil

### ISSUE THREAD

**Issue by wkoszek** [appium/appium#6394]
## The problem

I've run `npm install -g appium --no-shrinkwrap` because I wanted to get https://github.com/appium/appium/issues/6373 fixed. But I've hit the problem:

`[Appium 1.5.1] Instruments Trace Error : *** -[NSFileManager subpathsOfDirectoryAtPath:error:]: path is nil`
## Environment
- Appium version (or git revision) that exhibits the issue: `Welcome to Appium v1.5.1 (REV d5085edce0b5482771c66cfe3e2c013ee3ca90f6)`
- OSX 10.11.4 El Captain
- Node v5.9.1
- iPhone 6 Simulator
## Details

We run the suite of tests. Unfortunately it belongs to the company, so can't really post more stuff. However the output I'm getting is this:

```
getting driver took 46.5338988304
installing package: None
ERROR

======================================================================
ERROR: test_accelerate_accOff (__main__.AccelerateTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/wkoszek/r/autotest/AccelerateTests.py", line 49, in setUp
    testutils.setupTest(self, libcb)
  File "/Users/wkoszek/r/autotest/testutils.py", line 148, in setupTest
    adb.launch_activity(app.mainactivity())
  File "/Users/wkoszek/r/autotest/kitchen/kitchen.py", line 56, in launch_activity
    self.d.launch_app()
  File "/usr/local/lib/python2.7/site-packages/appium/webdriver/webdriver.py", line 529, in launch_app
    self.execute(Command.LAUNCH_APP)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 233, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/site-packages/appium/webdriver/errorhandler.py", line 29, in check_response
    raise wde
WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Abnormal Instruments termination!
```

On the Appium side I get:

```
[debug] [Instruments] [INST STDERR] Instruments Trace Error : *** -[NSFileManager subpathsOfDirectoryAtPath:error:]: path is nil 
```
## Link to Appium logs

https://gist.github.com/wkoszek/410807e3907a01a4a2df3de0c2077e02

**Comment by scottdixon** [comment]
@wkoszek - looks like the app is crashing ` The target application appears to have died`

Are you able to successfully launch the app in simulator / via instruments (without Appium)?

**Comment by wkoszek** [comment]
@scottdixon The failure in the script happens on the 2nd run (2nd unit test we have). The 1st one executed fine. In the previous runs I was able to execute many more test cases, but finally it ended up hitting the issue I'm reporting here.

To conclude: I can't find easy pattern to make it reproduce reliably.

**Comment by VenkateshPS** [comment]
I also got this error. while I tried running parallel tests on two devices. I had started two Appium sessions on 4723 and 4725.

Setup Details

Appium 1.5.3
iphone 5c 9.3.5 [real device]
iphone 5s 9.3.4[real device]
Xcode 7.3.1
EL captain

**Comment by SrinivasanTarget** [comment]
Closing this due to inactivity
