### ISSUE TITLE
Appium unable to detect static textfield through xpath

### ISSUE THREAD

**Issue by karthikthinkclear** [appium/appium#6402]
I'm running into an issue when running my test on simulator iOs (8.1) ,device (iphone 5) against appium server (1.4.16)

**Details**:
Following are the attributes for the specific element
name: 
type: UIATextField
value: First Name
label: 
enabled: true
visible: false
valid: true
location: {54, 136}
size: {91, 50}
xpath: //UIAApplication[1]/UIAWindow[1]/UIATableView[2]/UIATableCell[1]/UIATextField[1]/UIATextField[1]

**Questions**:
Could not enter text in the textfield.Tried by giving relative path as xpath.

@iOSFindBy(xpath= "//UIAApplication[1]/UIAWindow[1]/UIATableView[2]/UIATableCell[1]/UIATextField[1]/UIATextField[1]")

**Appium server log**:
org.openqa.selenium.NoSuchElementException: Cann't locate an element by this strategy: By.xpath: //UIAApplication[1]/UIAWindow[1]/UIATableView[2]/UIATableCell[1]/UIATextField[1]/UIATextField[1]
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.43.1', revision: '5163bceef1bc36d43f3dc0b83c88998168a363a0', time: '2014-09-10 09:43:55'
System info: host: 'Adityas-Mac-mini.local', ip: '192.168.0.2', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.3', java.version: '1.7.0_79'
Driver info: driver.version: unknown
    at io.appium.java_client.pagefactory.AppiumElementLocator.findElement(AppiumElementLocator.java:132)
    at io.appium.java_client.pagefactory.ElementInterceptor.intercept(ElementInterceptor.java:26)
    at io.appium.java_client.MobileElement$$EnhancerByCGLIB$$6abeadfd.getAttribute(<generated>)
    at com.appium.screens.settings.FriendsAndFamily.addFriendAndFamily(FriendsAndFamily.java:44)
    at com.appium.settingstestcases.FriendsAndFamilyTest.AddFriendsFamily(FriendsAndFamilyTest.java:39)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
    at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
    at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
    at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
    at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
    at org.testng.TestRunner.privateRun(TestRunner.java:768)
    at org.testng.TestRunner.run(TestRunner.java:617)
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
    at org.testng.SuiteRunner.run(SuiteRunner.java:240)
    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
    at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
    at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
    at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
    at org.testng.TestNG.run(TestNG.java:1025)
    at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
    at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
    at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)

**Comment by imurchie** [comment]
Are you sure this is the right XPath? The element is not being found.

**Comment by karthikthinkclear** [comment]
That is the xpath i got from appium inspector

**Comment by jlipps** [comment]
The most common instance of this problem is a race condition. Just because you get an XPath from the inspector does not mean you can find the element using that XPath. It must be present at the time you are trying to find it. To debug, print out the XML source immediately before the find attempt, and manually verify that the XPath query matches the element you care about.
