### ISSUE TITLE
Cannot resetApp() Real Devices or Simulators with 1.5.1 and Xcode 7.2 | 7.3

### ISSUE THREAD

**Issue by williamrussell-grindr** [appium/appium#6426]
**## The problem**
I've been bashing my head against this all day. 
I cannot for the life of me get Appium to reset iOS simulator or real devices in between test cases.

**Environment**
Mac OSX 10.10.5
Xcode 7.3 & 7.2
iOS Simulator 9.3 & 8.1
iPhone 6 iOS 9.1
Node.js version 12
Appium 1.5.1 (source code & npm install -g appium with the shrinkwrap fix)
Here is how I obtain the driver, and it is reset between test methods "@AfterMethod"

**## Code To Reproduce Issue [ Good To Have ]**

```
public class MobileTestScopeTemplate {

  public static AppiumDriver<MobileElement> driver;

  @BeforeSuite
  public void startDriver() {
      driver = (AppiumDriver<MobileElement>) DriverFactoryThread.getWebDriver();
  }


  @AfterMethod
  public void resetApp(){
      if(null != driver){
          driver.resetApp();
      }
  }

  @AfterSuite
  public void quitDriver() {
      driver.quit();
  }

  public AppiumDriver<MobileElement> getDriver(){
      return driver;
  }
}
A simple test case

@Test
public void test1() throws Exception {
    new LoginPage(driver).login("somegmail@gmail.com", "12345", "78", "0");
    assertTrue(new CascadePage(driver).isCascadePageLoaded());    
}

@Test
public void test2() throws Exception {
    new LoginPage(driver).login("somegmail@gmail.com", "12345", "78", "0");
    assertTrue(new CascadePage(driver).isCascadePageLoaded());
}
```

The second test case fails, since it is still logged into the application.

SERVER LOGS: 
[debug] [iOSSim] Simulator files not fully created. Waiting a bit
[iOS] Error: Simulator files not fully created. Waiting a bit
at SimulatorXcode73.callee$2$0$ (lib/simulator-xcode-6.js:316:15)
at tryCatch (/Users/williamrussell/projects/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
at GeneratorFunctionPrototype.invoke as _invoke
at GeneratorFunctionPrototype.prototype.(anonymous function) as next
at GeneratorFunctionPrototype.invoke (/Users/williamrussell/projects/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
at run (/Users/williamrussell/projects/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
at /Users/williamrussell/projects/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
at flush (/Users/williamrussell/projects/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
at process._tickCallback (node.js:355:11)
[Error: Simulator files not fully created. Waiting a bit]

[iOS] Could not reset simulator. Leaving as is.

The logs for the device: 
[Real Device Logs](https://gist.github.com/williamrussell-grindr/410ffa6c22bfaa24fd9910afff4daf1d)
## Reason:

We need this to work in DeviceFarm. DeviceFarm does not allow for "fullRest".

I have looked at tickets:
[This](https://github.com/appium/appium/issues/6272)
[This](https://github.com/appium/appium-ios-driver/issues/111)
and 
[This](https://github.com/appium/appium/issues/6241)

Device Farm won't allow for a fullReset. 

Does anyone know the differences between Appium 1.4 and 1.5/1.51 ? 

Any advice?

**Comment by jlipps** [comment]
We shouldn't allow access to `resetApp`, really. It's better to just use the reset capabilities and trust things will work in between sessions. Do you know why DeviceFarm does not allow for a fullReset? Also, may want to upgrade to latest Appium as the rest logic has probably changed.

**Comment by vikramvi** [comment]
related issue https://github.com/appium/appium/issues/6472

**Comment by danggrianto** [comment]
any update about this issue?

**Comment by mykola-mokhnach** [comment]
reset should work properly with Appium 1.6.4 and iOS 10.3

**Comment by danggrianto** [comment]
Is this exclusive to 10.3? I am currently on 1.6.4 beta and iOS 10.2.1.
And when I put full reset = `true` when i still logged in as a user from previous test.

**Comment by mykola-mokhnach** [comment]
Please create a separate issue report then and attach the log.

**Comment by dpgraham** [comment]
Closing due to inactivity. If this problem is still persisting, please ask me to re-open.
