### ISSUE TITLE
Appium Fails on iOS browser automation

### ISSUE THREAD

**Issue by AmeerTabony** [appium/appium#6453]
## The problem

Trying to run simple Appium automation script on iOS browser! 
It passed the first time, but then fails with the following error from the log:

2016-04-27 09:27:24:647 - debug: Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}}}
2016-04-27 09:27:24:653 - info: <-- GET /wd/hub/status 200 11.137 ms - 105 {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}}}
2016-04-27 09:27:24:680 - info: --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"IOS","browserName":"Safari","userName":"user1@default.com","password":"*******","udid":"4de71371cc06368d8353deb0460666d3f72a91ef","deviceName":"4de71371cc06368d8353deb0460666d3f72a91ef","noReset":"true","autoLaunch":"false","newCommandTimeout":300}}
2016-04-27 09:27:24:681 - info: Client User-Agent string: Apache-HttpClient/4.3.6 (java 1.5)
2016-04-27 09:27:24:682 - warn: Converting cap noReset from string to boolean. This might cause unexpected behavior.
2016-04-27 09:27:24:682 - warn: Converting cap autoLaunch from string to boolean. This might cause unexpected behavior.
2016-04-27 09:27:24:683 - debug: The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : userName, password
2016-04-27 09:27:24:684 - debug: Configuring Safari session
2016-04-27 09:27:24:685 - debug: Creating new appium session f3c85a8b-b1e3-4c49-83c3-f08bc290cb2f
2016-04-27 09:27:24:685 - debug: Setting up IOS for 'autoLaunch: false'
2016-04-27 09:27:24:687 - debug: Instruments socket server started at 28303
2016-04-27 09:27:24:687 - info: in navToInitialWebview
2016-04-27 09:27:24:688 - debug: Navigating to most recently opened webview
2016-04-27 09:27:24:689 - debug: [REMOTE] Getting WebKitRemoteDebugger pageArray
2016-04-27 09:27:24:758 - info: Instruments is ready to receive commands
2016-04-27 09:27:24:759 - debug: Socket data received (6 bytes)
2016-04-27 09:27:24:760 - debug: Socket data being routed.
2016-04-27 09:27:24:760 - debug: Got a result when we weren't expecting one! Ignoring it
2016-04-27 09:27:24:913 - warn: Could not find any webviews yet, refreshing/retrying
2016-04-27 09:27:25:413 - debug: [REMOTE] Getting WebKitRemoteDebugger pageArray
2016-04-27 09:27:25:420 - warn: Could not find any webviews yet, refreshing/retrying
2016-04-27 09:27:25:921 - debug: [REMOTE] Getting WebKitRemoteDebugger pageArray
2016-04-27 09:27:25:924 - warn: Could not find any webviews yet, refreshing/retrying
2016-04-27 09:27:26:425 - debug: [REMOTE] Getting WebKitRemoteDebugger pageArray
2016-04-27 09:27:26:430 - warn: Could not find any webviews yet, refreshing/retrying
2016-04-27 09:27:26:931 - debug: [REMOTE] Getting WebKitRemoteDebugger pageArray
2016-04-27 09:27:26:934 - warn: Could not find any webviews yet, refreshing/retrying
2016-04-27 09:27:27:434 - debug: [REMOTE] Getting WebKitRemoteDebugger pageArray
2016-04-27 09:27:27:438 - warn: Could not find any webviews yet, refreshing/retrying
2016-04-27 09:27:27:937 - debug: [REMOTE] Getting WebKitRemoteDebugger pageArray
2016-04-27 09:27:28:946 - error: [REMOTE] Could not connect to WebKitRemoteDebugger server
2016-04-27 09:27:28:947 - error: Failed to start an Appium session, err was: Error: Could not navigate to webview! Err: Error: connect ECONNREFUSED 127.0.0.1:28229
2016-04-27 09:27:28:954 - debug: Error: Could not navigate to webview! Err: Error: connect ECONNREFUSED 127.0.0.1:28229
    at [object Object].<anonymous> (C:\appium\lib\devices\ios\ios.js:1696:12)
    at [object Object].<anonymous> (C:\appium\lib\devices\ios\ios.js:1585:21)
    at [object Object].<anonymous> (C:\appium\lib\devices\ios\ios.js:1572:21)
    at [object Object].<anonymous> (C:\appium\lib\devices\ios\ios-hybrid.js:70:21)
    at [object Object].<anonymous> (C:\appium\lib\devices\ios\webkit-remote-debugger.js:77:14)
    at ClientRequest.<anonymous> (C:\appium\node_modules\underscore\underscore.js:890:21)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:258:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1256:8)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickDomainCallback (node.js:396:17)

## Environment

* 1.4
* Windows 7 - 64 bit
* iOS 8
* Real device

**Comment by scottdixon** [comment]
Can you please try with Appium 1.5? If the issue persists, please provide the entire Appium log as a [gist](gist.github.com).

**Comment by SrinivasanTarget** [comment]
Closing this because of inactivity.

**Comment by SrinivasanTarget** [comment]
@triager please close
