### ISSUE TITLE
Getting Error:Device emulator-5554 was not in the list of connected devices on Fire TV

### ISSUE THREAD

**Issue by Jitu1888** [appium/appium#6467]
## The problem

I am trying to automate Fire Tv , but getting an error Device emulator-5554 was not in the list of connected devices.

## Environment

* Appium version :1.4.16
* Desktop win 7 used to run Appium:
* Mobile platform: Fire OS 5.0.5.1
* Real device 
* Appium CLI or Appium.app|exe:

## Link to Appium logs
```
erver. : version, platform, androidPackage, webviewSupport, device
> info: [debug] Using local app from desired caps: C:\Users\jitu.patel\Desktop\Phone_DishAnywhere_4.7.24_signed.apk
> info: [debug] Creating new appium session 27740b6e-32df-42a7-988c-cd4d37ca34b7
> info: Starting android appium
> info: [debug] Getting Java version
> info: Java version is: 1.8.0_77
> info: [debug] Checking whether adb is present
> info: [debug] Using adb from D:\Automation\sdk\platform-tools\adb.exe
> info: [debug] Using fast reset? true
> info: [debug] Preparing device for session
> info: [debug] Checking whether app is actually present
> info: Retrieving device
> info: [debug] Trying to find a connected android device
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: D:\Automation\sdk\platform-tools\adb.exe devices
> info: [debug] 1 device(s) connected
> info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
> warn: UiAutomator did not shut down fast enough, calling it gone
> info: [debug] Cleaning up android objects
> info: [debug] Cleaning up appium session
> error: Failed to start an Appium session, err was: Error: Device emulator-5554 was not in the list of connected devices
> info: [debug] Error: Device emulator-5554 was not in the list of connected devices
>     at [object Object].<anonymous> (C:\Program Files (x86)\Appium\node_modules\appium\lib\devices\android\android-common.js:405:19)
>     at [object Object].<anonymous> (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\lib\adb.js:621:9)
>     at [object Object].<anonymous> (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\lib\adb.js:853:7)
>     at [object Object].<anonymous> (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\lib\adb.js:180:9)
>     at ChildProcess.exithandler (child_process.js:742:7)
>     at ChildProcess.emit (events.js:110:17)
```

**Comment by Jitu1888** [comment]
Please need a help urgently........................

**Comment by imurchie** [comment]
We have not ever tried to automate a kindle fire tv, so you are mostly on your own here.

Can you provide the full server logs? If it is a real device it should not be trying to find an emulator.

Also can you provide the output from the command `D:\Automation\sdk\platform-tools\adb.exe devices`?

**Comment by Jitu1888** [comment]
Sorry sir, now i am able to launch the application using appium but i am not getting the view hierarchy from UIAUTOMATOR which is present inside the tool floder. for that reason i am not able to read the elements present on the screen of FIre TV .

**Comment by imurchie** [comment]
Uh oh. If the UiAutomarViewer doesn't work, UiAutomator (and therefore Appium) probably won't automate it. :(

**Comment by Jitu1888** [comment]
If I get the ids from the page source then I can automate it right....
