### ISSUE TITLE
Android: Unable to start app: badging act: null Cannot parse launchActivity from manifest.null

### ISSUE THREAD

**Issue by gitserious** [appium/appium#6481]
## The problem

I have an app which I can side load onto an Android device with adb and run fine.
When I try to run the app via the Appium application or programmically via java. The app won't install and run. 
## Environment

I'm running on OSX Appium v1.4.16
I have already tried 1.5 both npm and the actual app.  With 1.5 I can't get anything to run.
I'm loading device into a Genymotion sim.
## Details

The key things i see is the badging act is null
 badging act: null
and 
Cannot parse launchActivity from manifest.null

The manifest these so I don't know why it isn't working.
## Link to Appium logs

```
info: [debug] badging act: null
info: --> GET /wd/hub/status {}
info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}},"sessionId":"d91cff79-1b03-44da-8ace-ed29dc3f2337"}
info: <-- GET /wd/hub/status 200 1.514 ms - 156 {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}},"sessionId":"d91cff79-1b03-44da-8ace-ed29dc3f2337"}
warn: May 06, 2016 11:24:57 AM brut.androlib.res.decoder.AXmlResourceParser getAttributeValue
WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=autoVerify, value=0xffffffff
brut.androlib.err.UndefinedResObject: resource spec: 0x010104ee
    at brut.androlib.res.data.ResPackage.getResSpec(ResPackage.java:59)
    at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:58)
    at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:54)
    at brut.androlib.res.decoder.ResAttrDecoder.decode(ResAttrDecoder.java:36)
    at brut.androlib.res.decoder.AXmlResourceParser.getAttributeValue(AXmlResourceParser.java:369)
    at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeValue(XmlPullParserDelegate.java:69)
    at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:267)
    at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)
    at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:83)
    at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:141)
    at brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPullStreamDecoder.java:153)
    at brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecoder.java:131)
    at brut.androlib.res.AndrolibResources.decodeManifest(AndrolibResources.java:164)
    at io.appium.apktools.AndroidManifestActivityHelper.decodeManifestXML(AndroidManifestActivityHelper.java:27)
    at io.appium.apktools.Main.main(Main.java:33)

info: [debug] Cleaning up android objects
info: [debug] Cleaning up appium session
info: [debug] Error: Cannot parse launchActivity from manifest.null
    at [object Object].<anonymous> (/usr/local/lib/node_modules/appium/lib/devices/android/android-common.js:693:21)
    at ChildProcess.exithandler (child_process.js:742:7)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Cannot parse launchActivity from manifest.null)","origValue":"Cannot parse launchActivity from manifest.null"},"sessionId":null}
```

**Comment by scottdixon** [comment]
Regarding `manifest.null`, please take a look at this ticket: https://github.com/appium/appium/issues/5049

`"With 1.5 I can't get anything to run."` - can you please post your 1.5 logs as a [gist](https://gist.github.com)?

**Comment by gitserious** [comment]
I already looked at the ticket, it looks like there was never a solution.

**Comment by gitserious** [comment]
I added a log to gist, i get the same results with both android and ios

**Comment by scottdixon** [comment]
From #5049 - are you using the appPackage capability?

Please provide the link to the gist.

**Comment by gitserious** [comment]
Sorry about that Scott! Here you go
https://gist.github.com/gitserious/9e9f4d1622027f146384cd351c1eab00

**Comment by gitserious** [comment]
From #5049 - are you using the appPackage capability?

Yes I already tried sending that capability, as well the wait for Activity.

Still same results. =/

**Comment by scottdixon** [comment]
`I get the same results with both android and ios` - iOS shouldn't be complaining about manifest.xml. Do you get a different error on iOS?

Thanks for the logs - they only show Appium server starting, did you mean to link to another log?

**Comment by gitserious** [comment]
I get the same results with both android and ios - I was talking about when I try to use Appium 1.5.2 
On Android and iOS i dont get any error, the appium server just starts but doesn't install or launch my application.

**Comment by gitserious** [comment]
For Android 1.4.13 I figured it out. I have explicitiy send the app package + launch activity

**Comment by scottdixon** [comment]
`On Android and iOS i dont get any error, the appium server just starts but doesn't install or launch my application.` - You'll need to create a session. Which language are you familiar with? I can provide some sample code.

**Comment by gitserious** [comment]
I'm using java.
For 1.5.2 with the Appium App. I used to checking prelaunch and then clicking launch.
In 1.4.13 of the Appium App. The app installs my app and launches it in my emulator. Is this not how it works any more in 1.5.2? How do I prelaunch the app in 1.5.2?

**Comment by gitserious** [comment]
BTW thank you so much for taking the time to help me out. I really appreciate it.

**Comment by scottdixon** [comment]
I think you're referring to the GUIs: https://github.com/appium/appium-dot-app or https://github.com/appium/appium-dot-exe

These haven't been updated to support Appium 1.5. To use 1.5 you'll need to start the server (which you've done successfully) and then send requests to the server to launch the app.

Here's some sample code (including java examples): https://github.com/appium/sample-code/tree/master/sample-code/examples

For further general assistance please post in the forums here: https://discuss.appium.io/. If you believe you find a bug, open an issue here.

**Comment by gitserious** [comment]
ok got it thanks for the help

**Comment by rompic** [comment]
a new version of the appium dot app has been released today see https://github.com/appium/appium-dot-app/issues/532#issuecomment-217668088

**Comment by sofaking** [comment]
Same issue here. 
Setting appPackage and appActivity helps.
I guess that happened after we've increased targetSdk to 24, but not for sure. Also we've tried to rebuild appium_apk_tools.jar with 1.5.4 and 2.1.1 apktools, but failed. Same issue with 1.5.4, while it seems in 2.1.1 API has been dramatically changed and it's impossible to even build with it.

```
2016-07-20 16:07:55:515 - [ADB] Extracting package and launch activity from manifest
2016-07-20 16:07:55:695 - [ADB] Error: packageAndLaunchActivityFromManifest failed. Original error: Path must be a string. Received null
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at ADB.callee$0$0$ (lib/tools/android-manifest.js:88:9)
    at tryCatch (/Users/aup/Documents/appium_1.5/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/aup/Documents/appium_1.5/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/aup/Documents/appium_1.5/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/aup/Documents/appium_1.5/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Users/aup/Documents/appium_1.5/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /Users/aup/Documents/appium_1.5/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/Users/aup/Documents/appium_1.5/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at _combinedTickCallback (node.js:370:9)
    at process._tickCallback (node.js:401:11)
 [Error: packageAndLaunchActivityFromManifest failed. Original error: Path must be a string. Received null]
2016-07-20 16:07:55:698 - [debug] [AndroidDriver] Shutting down Android driver
2016-07-20 16:07:55:699 - [AndroidDriver] Cannot shut down Android driver; it has already shut down
2016-07-20 16:07:55:700 - [MJSONWP] Encountered internal error running command: Error: packageAndLaunchActivityFromManifest failed. Original error: Path must be a string. Received null
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at ADB.callee$0$0$ (lib/tools/android-manifest.js:88:9)
    at tryCatch (/Users/aup/Documents/appium_1.5/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/aup/Documents/appium_1.5/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/aup/Documents/appium_1.5/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/aup/Documents/appium_1.5/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Users/aup/Documents/appium_1.5/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /Users/aup/Documents/appium_1.5/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/Users/aup/Documents/appium_1.5/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at _combinedTickCallback (node.js:370:9)
    at process._tickCallback (node.js:401:11)
```

**Comment by dpgraham** [comment]
If this is still an issue for anyone, let me know and I'll re-open.

**Comment by saravana2906** [comment]
I am facing same error, 
link for error [logs ](https://gist.github.com/saravana2906/af6eb512c4d6bb9d0139c8fc36455099)
Is this error due to aapt.exe? , I tried but couldn't find the latest version of it

**Comment by dpgraham** [comment]
@saravana2906 Have you tried on a recent version of Appium (the current version is 1.7.1)

**Comment by saravana2906** [comment]
@dpgraham  I am using the Appium desktop app in windows, I didn't see any update for it. here is the [link](http://appium.io/slate/en/master/?ruby#a-windows-gui-for-appium) where I downloaded Appium

**Comment by dpgraham** [comment]
@saravana2906 That GUI is no longer supported. https://github.com/appium/appium-desktop/releases is our new, up-to-date UI that has 1.7.1
