### ISSUE TITLE
1.5.2 - Android fails with [Error: packageAndLaunchActivityFromManifest failed. Original error: Path must be a string. Received null]

### ISSUE THREAD

**Issue by GreenJeans** [appium/appium#6499]
Android automation that continues to run as expected using the Appium 1.4.13 GUI fails using the 1.5.2 GUI with:

```
[ADB] Checking whether aapt is present 

[ADB] Error: packageAndLaunchActivityFromManifest failed. Original error: Path must be a string. Received null
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at ADB.callee$0$0$ (lib/tools/android-manifest.js:88:9)
    at tryCatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
 [Error: packageAndLaunchActivityFromManifest failed. Original error: Path must be a string. Received null]
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.2
* Last Appium version that did not exhibit the issue (if applicable): 1.4.13
* Desktop OS/version used to run Appium: OSX 10.11.4
* Node.js version (unless using Appium.app|exe): Appium.app
* Mobile platform/version under test: Android 5.1
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: .app

**Comment by KateOgar** [comment]
any update on this issue?

**Comment by GreenJeans** [comment]
More (complete) logs: https://gist.github.com/GreenJeans/3efaff3e8588b6cd0649d6ba600fa756

**Comment by stba42** [comment]
Hi, I just got the same error. 
I forgot to set ANDROID_HOME! As soon as I did, the problem was solved.
The error message is very confusing, however - it took me a while to figure it out.

**Comment by GreenJeans** [comment]
Specifying my app's package and Launch Activity explicitly in the Appium GUI has caused this automation to work under Appium 1.5.3

**Comment by rajanbharti** [comment]
Any updates on this issue. I am using appium 1.6.4  . ANDROID_HOME is already set, as specified by @stba42 . I am getting this error for some apps. not every app

**Comment by DonnaZh** [comment]
@rajanbharti 
I am using same appium version 1.6.4. ANDROID_HOME set. Get this error for one app, but works fine for the other app. Do you have any solution? Thank you!

**Comment by DonnaZh** [comment]
**update ....**
it works by setting right AppActivity capability.

**To find AppPackageName and AppActivity ...**
C:\Users\myName\AppData\Local\Android\sdk\build-tools\25.0.2>aapt list -a "C:\myProject\bin\Debug\Apps\myApp.apk" > "C:\output.txt"

**in output.txt file**
1. search for [Android manifest] 
==> find [A: package="yourAppPackageName:]

2. search for [E: activity] 
==> find a list of activity names, try them one by one, most likely it would be the first one.
