### ISSUE TITLE
Appium: Error "System.OutOfMemoryException" Appium 1.4.16.1

### ISSUE THREAD

**Issue by feralexandru** [appium/appium#6509]
## Appium suddently stop
Hello guys, unfortunately I have an error on Windows machine on windows 10 64 bit. The log of the Windows error is: 

Application: Appium.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.OutOfMemoryException
   at System.String.Concat(System.String, System.String)
   at Appium.ViewModels.MainWindowVM._OutputDataReceived(System.String)
   at Appium.Engine.AppiumEngine._FireOutputData(System.String)
   at Appium.Engine.AppiumEngine._Process_OutputDataReceived(System.Object, System.Diagnostics.DataReceivedEventArgs)
   at System.Diagnostics.Process.OutputReadNotifyUser(System.String)
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue()
   at System.Diagnostics.AsyncStreamReader.GetLinesFromStringBuilder()
   at System.Diagnostics.AsyncStreamReader.ReadBuffer(System.IAsyncResult)
   at System.IO.Stream+ReadWriteTask.InvokeAsyncCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.IO.Stream+ReadWriteTask.System.Threading.Tasks.ITaskCompletionAction.Invoke(System.Threading.Tasks.Task)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task.FinishStageTwo()
   at System.Threading.Tasks.Task.Finish(Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

## Details
The performance of the PC is not the problem. I have an laptop of i3 core on 2.4Gz, with 12GB or RAM, ready for all the devices that i want to create. For my test i use only version 6.0 Android, and is ruining in loops the test for 50 times. 

## Error that I get, 

The error that I get is when the pc is working. The pc is put on lock screen, the power saving is off, it is turn into high performance. Moreover he never enter in the sleep mode, display off or other sorts. The test is made for approximately 10 min each, and for that reason for the night i need to put in like for 6-7h or working. But suddenly at the test 30 the Appium stop with the messenger that is just in the fist part. Unfortunately, I can not obtain Appium logs, at all .

**Comment by imurchie** [comment]
Without the Appium logs I have no way of moving forward. You might want to open the issue with the `Appium.exe` (https://github.com/appium/appium-dot-exe).

**Comment by SrinivasanTarget** [comment]
@triager please close
