### ISSUE TITLE
[Appium] Android - Cannot Switch to WebView Context with "Method Threw 'org.openqa.selenium.WebDriverException' Exception"

### ISSUE THREAD

**Issue by GilShdemati** [appium/appium#6510]
## The Problem

Android Application (Hybrid) - Cannot Switch from NATIVE Context to WEBVIEW Context
When Executing SetContext()
Method Threw 'org.openqa.selenium.WebDriverException' Exception
Encountered Internal Error Running Command: TypeError: Cannot Read Property 'stop' of NULL
## Environment
- Appium Version: 1.5.1
- Desktop OS: OS X El-Capitan Version 10.11.4
- Node.js Version: v4.1.1
- Mobile Platform: Android 4.4.2
- Real Device
- Appium CLI: Version 1.5.2 (Ara)
## Details

The Issue Doesn't Reproduce When Executing The Same Steps on iOS
## Link to Appium logs

[MJSONWP] Calling AppiumDriver.setContext() with args: ["WEBVIEW_packageName","1ba0d05f-df95-4d79-9784-4df53ed72177"]
[debug] [AndroidDriver] Getting a list of available webviews
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /android-sdk-macosx/platform-tools/adb with args: ["-P",5037,"-s","099a9cd11cee0c54","shell","cat","/proc/net/unix"]
[debug] [AndroidDriver] WEBVIEW_9431 mapped to pid 9431
[debug] [AndroidDriver] Getting process name for webview
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /android-sdk-macosx/platform-tools/adb with args: ["-P",5037,"-s","099a9cd11cee0c54","shell","ps"]
[debug] [AndroidDriver] Parsed pid: 9431 pkg: packageName!
[debug] [AndroidDriver] from: u0_a458,9431,292,872480,197340,ffffffff,00000000,S,packageName
[debug] [AndroidDriver] returning process name: packageName
[debug] [AndroidDriver] Found webviews: ["WEBVIEW_packageName"]
[debug] [AndroidDriver] Available contexts: ["NATIVE_APP","WEBVIEW_packageName"]
[debug] [AndroidDriver] Connecting to chrome-backed webview context 'WEBVIEW_packageName'
[debug] [Chromedriver] Changed state to 'starting'
[MJSONWP] Encountered internal error running command: TypeError: Cannot read property 'stop' of null
    at Chromedriver.start$ (lib/chromedriver.js:104:24)
    at tryCatch (/Users/gilshdemati/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke](/Users/gilshdemati/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw](/Users/gilshdemati/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/gilshdemati/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Users/gilshdemati/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /Users/gilshdemati/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/Users/gilshdemati/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)
[HTTP] <-- POST /wd/hub/session/1ba0d05f-df95-4d79-9784-4df53ed72177/context 500 172 ms - 206
## Code To Reproduce Issue
1. myAndroidDriver.getContextHandles()
   Result = {LinkedHashSet@3539}  size = 2
   0 = "NATIVE_APP"
   1 = "WEBVIEW_packageName"
2. myAndroidDriver.context(myAndroidDriver.getContextHandles().toArray()[1].toString())
   Result = Method Threw 'org.openqa.selenium.WebDriverException' Exception

**Comment by imurchie** [comment]
This is indeed a bug. Waiting for my fix to go through. Thanks!

**Comment by GilShdemati** [comment]
Any estimation time for the Fix?

**Comment by SrinivasanTarget** [comment]
@imurchie I hope
