### ISSUE TITLE
chromedriver error when swithing to webview context

### ISSUE THREAD

**Issue by fdx321** [appium/appium#6525]
## The problem

When switching to Webview context, sometimes the chromedriver quit unexpectedly.
## Environment
- chromedriver version:  2.10.267517
- Appium version (or git revision) that exhibits the issue:1.4.13
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium: OSX 10.11.5
- Node.js version (unless using Appium.app|exe):
- Mobile platform/version under test: android 5.1
- Real device or emulator/simulator: real device
- Appium CLI or Appium.app|exe: appium.app 
## Link to Appium logs

error: Chromedriver: Chromedriver exited unexpectedly with code null, signal SIGTERM

info: Chromedriver: Changed state to 'stopped'

error: Chromedriver: Error: An unknown server-side error occurred while processing the command. (Original error: unknown error: Device 860BCML226BU is not online
  (Driver info: chromedriver=2.10.267517,platform=Mac OS X 10.11.5 x86_64))
    at JWProxy.command$ (lib/proxy.js:149:15)
    at tryCatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke](/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/regenerator/runtime.js:294:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next](/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at bound (domain.js:254:14)
    at GeneratorFunctionPrototype.runBound (domain.js:267:12)
    at run (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:89:39)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:100:28
    at process._tickDomainCallback (node.js:381:11)
 { [Error: An unknown server-side error occurred while processing the command. (Original error: unknown error: Device 860BCML226BU is not online
  (Driver info: chromedriver=2.10.267517,platform=Mac OS X 10.11.5 x86_64))]
  status: 13,
  value: { message: 'unknown error: Device 860BCML226BU is not online\n  (Driver info: chromedriver=2.10.267517,platform=Mac OS X 10.11.5 x86_64)' },
  httpCode: 200 }

warn: Chromedriver for context WEBVIEW_com.xxxx.android stopped unexpectedly
warn: Chromedriver quit unexpectedly, but it wasn't the active context, ignoring
## Code To Reproduce Issue [ Good To Have ]

driver.context("WEBVIEW_com.xxxx.android");

**Comment by fdx321** [comment]
I see there are many issues about my problem, but they all not work.

**Comment by SrinivasanTarget** [comment]
Please try a latest version of appium and revert us back with logs in form of gist incase of issues
