### ISSUE TITLE
Unhandled error: TypeError: Cannot read property 'path' of undefined when run appium by script

### ISSUE THREAD

**Issue by nirajsingh1486** [appium/appium#6541]
error: Unhandled error: TypeError: Cannot read property 'path' of undefined

**This issue get resolved when i delete by code and checkout again from svn.
This issue is very specific to iOS.
Here to start appium i am using AppiumDriverLocalService**
Here i am setting path by HashMap env = new HashMap(); env.put("ANDROID_HOME", Constants.ANDROID_HOME); /** This to give the ANDROID_HOME path to AppiumDriverLocalService */ env.put("PATH", "/usr/local/bin:" + System.getenv("PATH")); /** This to give the PATH to AppiumDriverLocalService for iOS testing */
After that service = AppiumDriverLocalService.buildService(new AppiumServiceBuilder() .usingDriverExecutable(new File("/Applications/Appium.app/Contents/Resources/node/bin/node")) .withAppiumJS(new File("/Applications/Appium.app/Contents/Resources/node_modules/appium/bin/appium.js")) .withIPAddress(Constants.APPIUM_SERVER_HOST) .usingAnyFreePort() .withStartUpTimeOut(60, TimeUnit.SECONDS) .withEnvironment(env) .withLogFile(new File(Constants.basePath + "/Logs/Appium.log")))
LOGS

2016-05-20 07:46:16:493 - info: Welcome to Appium v1.4.13 (REV c75d8adcb66a75818a542fe1891a34260c21f76a) 2016-05-20 07:46:16:497 - info: Appium REST http interface listener started on 127.0.0.1:31932 2016-05-20 07:46:16:500 - info: [debug] Non-default server args: {"address":"127.0.0.1","port":31932,"log":"/Users/nirajkumar/Documents/workspace/ABC.UI_PHASE_2/Logs/Appium.log"} 2016-05-20 07:46:16:501 - info: Console LogLevel: debug 2016-05-20 07:46:16:501 - info: File LogLevel: debug 2016-05-20 07:46:16:555 - info: --> GET /wd/hub/status {} 2016-05-20 07:46:16:557 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}} 2016-05-20 07:46:16:572 - info: <-- GET /wd/hub/status 200 17.400 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}} 2016-05-20 07:46:16:594 - info: --> GET /wd/hub/status {} 2016-05-20 07:46:16:595 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}} 2016-05-20 07:46:16:598 - info: <-- GET /wd/hub/status 200 3.724 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}} 2016-05-20 07:46:17:537 - info: --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/nirajkumar/Documents/workspace/ABC.UI_PHASE_2/apps/UAPP_D.ipa","platformVersion":"9.3.1","udid":"c8d3d65b8fcfc83d82099f26cffdfdghh4f","platformName":"iOS","deviceName":"iPhone 6","autoAcceptAlerts":"true"}} 2016-05-20 07:46:17:538 - info: Client User-Agent string: Apache-HttpClient/4.3.6 (java 1.5) 2016-05-20 07:46:17:539 - warn: Converting cap autoAcceptAlerts from string to boolean. This might cause unexpected behavior. 2016-05-20 07:46:17:542 - info: [debug] Using local .ipa from desired caps: /Users/nirajkumar/Documents/workspace/KMA.UI_PHASE_2/apps/UAPP_D.ipa 2016-05-20 07:46:17:543 - info: [debug] Copying local zip to tmp dir 2016-05-20 07:46:17:551 - error: Unhandled error: TypeError: Cannot read property 'path' of undefined at /Applications/Appium.app/Contents/Resources/node_modules/appium/lib/helpers.js:44:46 at tryCatcher (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-support/node_modules/bluebird/js/main/util.js:26:23) at Promise.errorAdapter (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-support/node_modules/bluebird/js/main/nodeify.js:36:34) at bound (domain.js:254:14) at Promise.runBound (domain.js:267:12) at Promise._settlePromiseAt (/Applications/Aappium.app/Contents/Resources/node_modules/appium/node_modules/appium-support/node_modules/bluebird/js/main/promise.js:575:21) at Promise._settlePromiseAtPostResolution (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-support/node_modules/bluebird/js/main/promise.js:244:10) at Async._drainQueue (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-support/node_modules/bluebird/js/main/async.js:128:12) at Async._drainQueues (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-support/node_modules/bluebird/js/main/async.js:133:10) at Immediate.Async.drainQueues [as _onImmediate] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-support/node_modules/bluebird/js/main/async.js:15:14) at processImmediate [as _immediateCallback] (timers.js:367:17) context: [POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/nirajkumar/Documents/workspace/KMA.UI_PHASE_2/apps/UAPP_D.ipa","platformVersion":"9.3.1","udid":"c8d3d65b8fcfc83d82099f26cffdfdghh4f","platformName":"iOS","d]

This issue get resolved when i delete by code and checkout again from svn.

**Comment by mykola-mokhnach** [comment]
@nirajsingh1486 
Have you tried to update Appium to latest version?
```bash
brew install node      # get node.js
npm install -g appium  # get appium
npm install wd         # get appium client
appium &               # start appium
```

**Comment by nirajsingh1486** [comment]
@mykola-mokhnach  

currently i am using dmg appium version 1.4.13.

1.5.2 has its own problem, so i reverted back from latest one(1.5.2) to 1.4.13

**Comment by nirajsingh1486** [comment]
https://gist.github.com/nirajsingh1486/1f58c2af5cc5966500823e9eecce0069

**Comment by mykola-mokhnach** [comment]
@nirajsingh1486 Ok, I've just check the corresponding code and it seems that Appium just cannot create a temporary file in system temp folder. It might be, that since you provide you own environment,  then it cannot properly guess the path to system temp folder and return undefined as a result.
You can add before line 44 of this file
/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/helpers.js
and repeat your test to know more about the root issue of the problem
```javascript
      var infile = fs.createReadStream(localZipPath);

      logger.debug( Error is: ' + err);

      var outfile = fs.createWriteStream(info.path);
```

**Comment by nirajsingh1486** [comment]
After applying logger in helper.js

It shows
[36minfo[39m: [debug] Error is: Error: ENOENT, no such file or directory '/var/folders/q_/0682gr8x3wd1l7ljsnnxf0j80000gn/T/11651-660-mmx5vq'
[31merror[39m: Unhandled error: TypeError: Cannot read property 'path' of undefined
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/lib/helpers.js:45:46

I am deleting all temp file before starting appium.

Gist location is: https://gist.github.com/nirajsingh1486/87f5a4b6312615e4359bf4293a41e35b

**Comment by mykola-mokhnach** [comment]
Probably, you shouldn't delete these temp files?
Is this folder really present on your file system? If it is there then check whether it has all the necessary permissions.

**Comment by nirajsingh1486** [comment]
Commenting temp deletion code resolved my problem.But i was deleting temp folder first, after that i start appium services. 
any suggestion to handle temp deletion?

**Comment by mykola-mokhnach** [comment]
Is it some particular reason to delete temp files? If you really keen to do so then try not to delete folders there, but rather just files.
