### ISSUE TITLE
org.openqa.selenium.InvalidSelectorException: Locator Strategy 'name' is not supported for this session (WARNING: The server did not provide any stacktrace information)

### ISSUE THREAD

**Issue by xiaominghou** [appium/appium#6546]
## The problem
io.appium.java_client.pagefactory.AndroidFindBy or IOSFindBy  doesn't work . error: rg.openqa.selenium.InvalidSelectorException: Locator Strategy 'name' is not supported for this session 

I know the "name" has been removed after appium 1.5.x,  In my script I used the others, "id" ,"xpath","accessibility" . But  it still cause the same error : name is not supported   

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.1 
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:Mac OS X  10.11.4
* Node.js version (unless using Appium.app|exe):v5.7.1
* Mobile platform/version under test: iphone 5s
* Real device or emulator/simulator: real
* Appium CLI or Appium.app|exe:CLI

## Details
	@AndroidFindBy(id = "view_navbottom_home_iv")
	@iOSFindBy(accessibility ="my")
	public WebElement myTab;

        myTab.click();

org.openqa.selenium.InvalidSelectorException: Locator Strategy 'name' is not supported for this session (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 8 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/invalid_selector_exception.html
Build info: version: '2.47.1', revision: 'unknown', time: '2015-07-30 11:02:44'
System info: host: 'N/A', ip: 'N/A', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.4', java.version: '1.7.0_79'
*** Element info: {Using=name, value=myTab}
Session ID: 13034d14-2ef4-4ea1-b46a-635f9832047b
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{platform=MAC, app=/Users/xiaoming/aaa.ipa, javascriptEnabled=true, browserName=, networkConnectionEnabled=false, desired={app=/Users/hichao/test/mxyc_auto_test/apps/mxyc.ipa, platformVersion=8.3, deviceName=xiaoming, platformName=iOS, appiumVersion=1.0, unicodeKeyboard=true, resetKeyboard=true, udid=ac76963a56e13d8afeae83d3bb33a7f2c826b48a}, udid=ac76963a56e13d8afeae83d3bb33a7f2c826b48a, locationContextEnabled=false, platformVersion=8.3, databaseEnabled=false, platformName=iOS, deviceName=xiaoming, appiumVersion=1.0, webStorageEnabled=false, unicodeKeyboard=true, resetKeyboard=true, takesScreenshot=true}]
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:595)
at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:348)
at org.openqa.selenium.remote.RemoteWebDriver.findElementByName(RemoteWebDriver.java:421)
at io.appium.java_client.DefaultGenericMobileDriver.findElementByName(DefaultGenericMobileDriver.java:102)
at io.appium.java_client.AppiumDriver.findElementByName(AppiumDriver.java:1)
at io.appium.java_client.ios.IOSDriver.findElementByName(IOSDriver.java:1)
at org.openqa.selenium.By$ByName.findElement(By.java:300)
at org.openqa.selenium.support.ByIdOrName.findElement(ByIdOrName.java:50)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:340)
at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:52)
at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
at io.appium.java_client.ios.IOSDriver.findElement(IOSDriver.java:1)
at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:69)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
at com.sun.proxy.$Proxy12.click(Unknown Source)
at com.mxyc.test.common.operateFactory.CommonMethod.click(CommonMethod.java:98)
at com.mxyc.test.testcase.AndroidAppTest.TC1_signIn(AndroidAppTest.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
at org.testng.TestRunner.privateRun(TestRunner.java:782)
at org.testng.TestRunner.run(TestRunner.java:632)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
at org.testng.SuiteRunner.run(SuiteRunner.java:268)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.run(TestNG.java:1064)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Check this issue:
https://github.com/appium/java-client/issues/184

In general, the annotation @iOSFindBy(accessibility ="my") sequentially called these methods on the lower level:
```javascript
au.getElementsById('trackerButton')
au.getElementsByName('trackerButton')
au.getElementsByAccessibilityId('trackerButton')
```
which is why you get the mentioned exception. 

The solution there was
> Disregard my comments, I was an idiot and was passing the driver directly into PageFactory.initElements() rather than a new AppiumFieldDecorator.

**Comment by SrinivasanTarget** [comment]
@triager please close
