### ISSUE TITLE
'Cannot read property 'send' of null' getting thrown when trying to find element on iPhone

### ISSUE THREAD

**Issue by AppiumUserForMobile** [appium/appium#6565]
I am seeing below error when trying to find element on iPhone 9.3.1
 
iPhone 9.3.1

* Appium version (or git revision) that exhibits the issue: 1.5.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS X 10.11.5
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iPhone 9.3
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

I am opening my application pages on iPhone , clicked a link, waited for some time on the page , went back in the browser , made sure I am on the page and then click a different button on the page. At this point appium is throwing this error when calling findElement method.

## Link to Appium logs
[MJSONWP] Calling AppiumDriver.getUrl() with args: ["6abaec6d-1404-4cf4-bed2-8d5324662b46"]
[debug] [iOS] Executing iOS command 'getUrl'
[debug] [RemoteDebugger] Sending javascript command window.location.href
[MJSONWP] Encountered internal error running command: TypeError: Cannot read property 'send' of null
    at WebKitRemoteDebugger.execute$ (lib/remote-debugger.js:424:35)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at new Promise (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:197:7)
    at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:16)
    at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at WebKitRemoteDebugger.execute (lib/remote-debugger.js:424:12)
    at IosDriver.callee$0$0$ (lib/commands/web.js:80:31)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at new Promise (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:197:7)
    at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:16)
    at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at IosDriver.callee$0$0 [as getUrl] (lib/commands/web.js:80:10)
    at lib/driver.js:163:24
    at tryCatcher (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromiseAtPostResolution (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/promise.js:245:10)
    at Async._drainQueue (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)

This is blocking us and Appreciate your help in getting us unblocked!

**Comment by mykola-mokhnach** [comment]
This sounds like a bug, but let's try to dirty workaround first. Find and backup this lib/remote-debugger.js file first. Then insert the following code before the line # 424:
```javascript
if (!this.isConnected()) {
    await this.connect();
}
```
Then save the changed file and restart appium.
I'm not sure if this works , but that's the first idea, that comes into my mind :-)

**Comment by imurchie** [comment]
I would upgrade to 1.5.3 (or at least 1.5.2). This issue has been resolved.

**Comment by SrinivasanTarget** [comment]
@triager please close

**Comment by SrinivasanTarget** [comment]
@AppiumUserForMobile Please reopen with latest logs if you hit the same on latest version
