### ISSUE TITLE
reset.sh file is not present

### ISSUE THREAD

**Issue by CapDam** [appium/appium#6581]
## The problem

reset.sh file is not present, I do not know how to generate SafariLauncher.app (SafariLauncher is present on my actual device).How do without reset.sh?
## Environment
- $ npm -v appium
  3.9.3
- device: Iphone 6S Plus

Thank you

**Comment by imurchie** [comment]
What version of Appium are you using?Appium 1.5.x no longer has `reset.sh`. If you need SafariLauncher it will be built automatically.

**Comment by CapDam** [comment]
I Appium 1.5.3 .
Safari launcher is built automatically? Where is he? and how?

**Comment by amake** [comment]
Look [here](https://github.com/appium/appium/blob/master/docs/en/contributing-to-appium/appium-from-source.md) for instructions on running from source.

**Comment by CapDam** [comment]
I try, thank you

**Comment by CapDam** [comment]
Thank you very much for your help, I followed the tutorial but I do have a problem trying to run a test:

`[iOS] Error: Command 'xcodebuild -sdk iphoneos9.3 -xcconfig /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/safari-launcher/build.xcconfig' exited with code 65
    at ChildProcess.<anonymous> (lib/teen_process.js:65:19)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:475:12)
 { [Error: Command 'xcodebuild -sdk iphoneos9.3 -xcconfig /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/safari-launcher/build.xcconfig' exited with code 65]
  stdout: 'Build settings from command line:\n    SDKROOT = iphoneos9.3\n\nBuild settings from configuration file \'/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/safari-launcher/build.xcconfig\':\n    BUNDLE_ID = com.bytearc.SafariLauncher\n    IDENTITY_CODE = \n    IDENTITY_NAME = iPhone Developer\n\n=== BUILD TARGET SafariLauncher OF PROJECT SafariLauncher WITH THE DEFAULT CONFIGURATION (Release) ===\n\nCheck dependencies\nCode Sign error: No matching provisioning profiles found: No provisioning profiles with a valid signing identity (i.e. certificate and private key pair) matching the bundle identifier “com.bytearc.SafariLauncher” were found.\n\n',
  stderr: '** BUILD FAILED **\n\n\nThe following build commands failed:\n\tCheck dependencies\n(1 failure)\n',
  code: 65 }
[iOS] Error: Command 'xcodebuild -sdk iphoneos9.3 -xcconfig /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/safari-launcher/build.xcconfig' exited with code 65
    at ChildProcess.<anonymous> (lib/teen_process.js:65:19)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:475:12)
 { [Error: Command 'xcodebuild -sdk iphoneos9.3 -xcconfig /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/safari-launcher/build.xcconfig' exited with code 65]
  stdout: 'Build settings from command line:\n    SDKROOT = iphoneos9.3\n\nBuild settings from configuration file \'/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/safari-launcher/build.xcconfig\':\n    BUNDLE_ID = com.bytearc.SafariLauncher\n    IDENTITY_CODE = \n    IDENTITY_NAME = iPhone Developer\n\n=== BUILD TARGET SafariLauncher OF PROJECT SafariLauncher WITH THE DEFAULT CONFIGURATION (Release) ===\n\nCheck dependencies\nCode Sign error: No matching provisioning profiles found: No provisioning profiles with a valid signing identity (i.e. certificate and private key pair) matching the bundle identifier “com.bytearc.SafariLauncher” were found.\n\n',
  stderr: '** BUILD FAILED **\n\n\nThe following build commands failed:\n\tCheck dependencies\n(1 failure)\n',
  code: 65 }
[iOS] Bad app: '/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/build/SafariLauncher/SafariLauncher.app'. App paths need to be absolute, or relative to the appium server install dir, or a URL to compressed file, or a special app name.
[MJSONWP] Encountered internal error running command: Error: Bad app: /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/build/SafariLauncher/SafariLauncher.app. App paths need to be absolute, or relative to the appium server install dir, or a URL to compressed file, or a special app name.
    at IosDriver.configureApp$ (lib/driver.js:247:13)
    at tryCatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
`

**Comment by CapDam** [comment]
Thank you very much for your help, but after following the tutorial, it still does not work:
`[debug] [iOS] Not auto-detecting udid.
[debug] [iOS] Creating iDevice object with udid b08d743e4c8acc04d2ba4adf16b460916d54ae0e
[debug] [iOS] Checking for presence of SafariLauncher at '/Users/Damien/appium/node_modules/appium-ios-driver/build/SafariLauncher/SafariLauncher.app'
[debug] [iOS] SafariLauncher does not exist
[debug] [iOS] SafariLauncher not found, building...
[iOS] Cleaning SafariLauncher
[debug] [iOS] Cleaning SafariLauncher for iphoneos9.3
[iOS] Error: Command 'xcodebuild -sdk iphoneos9.3 clean' errored out: Error: spawn xcodebuild ENOENT
    at exports._errnoException (util.js:1007:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at ChildProcess.<anonymous> (lib/teen_process.js:31:14)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:202:12)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
 Error: Command 'xcodebuild -sdk iphoneos9.3 clean' errored out: Error: spawn xcodebuild ENOENT
    at exports._errnoException (util.js:1007:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at ChildProcess.<anonymous> (lib/teen_process.js:31:14)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:202:12)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[iOS] Error: Command 'xcodebuild -sdk iphoneos9.3 clean' errored out: Error: spawn xcodebuild ENOENT
    at exports._errnoException (util.js:1007:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at ChildProcess.<anonymous> (lib/teen_process.js:31:14)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:202:12)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
 Error: Command 'xcodebuild -sdk iphoneos9.3 clean' errored out: Error: spawn xcodebuild ENOENT
    at exports._errnoException (util.js:1007:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at ChildProcess.<anonymous> (lib/teen_process.js:31:14)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:202:12)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[iOS] Bad app: '/Users/Damien/appium/node_modules/appium-ios-driver/build/SafariLauncher/SafariLauncher.app'. App paths need to be absolute, or relative to the appium server install dir, or a URL to compressed file, or a special app name.
[MJSONWP] Encountered internal error running command: Error: Bad app: /Users/Damien/appium/node_modules/appium-ios-driver/build/SafariLauncher/SafariLauncher.app. App paths need to be absolute, or relative to the appium server install dir, or a URL to compressed file, or a special app name.
    at IosDriver.configureApp$ (lib/driver.js:247:13)
    at tryCatch (/Users/Damien/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/Damien/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/Damien/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/Damien/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
`

**Comment by CapDam** [comment]
Hi, 
I changed my order to launch appium and I have a different error message:

> node . --default-capabilities '{"platformName":"IOS"}' --default-capabilities '{"platformVersion":"9.3.2"}' --default-capabilities '{"browserName":"Safari"}' --default-capabilities '{"launchTimeout":20000}' --default-capabilities '{"udid":"b08d743e4c8acc04d2ba4adf16b460916d54ae0e"}' --default-capabilities '{"noReset":true}' --default-capabilities '{"nativeInstrumentsLib":true}'
[Appium] Welcome to Appium v1.5.3 (REV 1b86d0cba9b645d4a2fb1e9c083d492388d4f147)
[Appium] Non-default server args:
[Appium]   defaultCapabilities: { nativeInstrumentsLib: true }
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   nativeInstrumentsLib: true
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"platformVersion":"9.3","deviceName":"b08d743e4c8acc04d2ba4adf16b460916d54ae0e","browserName":"Safari","platformName":"IOS"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformVersion":"9.3","...
[Appium] Creating new IosDriver session
[Appium] Capabilities:
[Appium]   platformVersion: '9.3'
[Appium]   deviceName: 'b08d743e4c8acc04d2ba4adf16b460916d54ae0e'
[Appium]   browserName: 'Safari'
[Appium]   platformName: 'IOS'
[Appium]   nativeInstrumentsLib: true
[BaseDriver] Session created with session id: f00e6e65-0a6b-4149-9ed1-8caf478101f9
[debug] [iOS] Not auto-detecting udid.
[debug] [iOS] We are on iOS8+ so not copying Safari app
[debug] [iOS] Removing any remaining instruments sockets
[debug] [iOS] Cleaned up instruments socket /var/folders/dr/547_pknn7wg422cb7yzt7k740000gn/T/instruments_sock
[debug] [iOS] Setting Xcode version
[debug] [iOS] Xcode version set to 7.3.1
[debug] [iOS] Setting iOS SDK Version
[debug] [iOS] iOS SDK Version set to 9.3
[debug] [iOS] Checking whether instruments supports our device string
[debug] [Instruments] Getting list of devices instruments supports
[debug] [Instruments] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
[debug] [Instruments] Available devices: Apple TV 1080p (9.2) [A4560DCA-9F32-4ED7-9BF1-A24EE277B66B] (Simulator),iPad 2 (9.3) [68D54A28-AE03-46A9-88DA-08C42ED3FD80] (Simulator),iPad Air (9.3) [53AABC5F-316C-40AC-B7D4-EEC3B17692C4] (Simulator),iPad Air 2 (9.3) [43D3C265-E5FF-4DCA-930E-38D3343A13FD] (Simulator),iPad Pro (9.3) [980C59B7-DE39-4AA8-8005-85F79D781417] (Simulator),iPad Retina (9.3) [709A8FE8-7741-4D7B-B10C-8CE34545E1E4] (Simulator),iPhone 4s (9.3) [318F5CB8-C11A-4637-9005-C137DCA8FDE0] (Simulator),iPhone 5 (9.3) [7AC2457B-4716-4642-94D6-09694C45CFAE] (Simulator),iPhone 5s (9.3) [00272D14-1A38-4482-ABEF-FA7E241EB4F8] (Simulator),iPhone 6 (9.3) [43F0C14F-AB7C-428B-839D-5AE7C181758E] (Simulator),iPhone 6 Plus (9.3) [F0C394DF-C50F-4C1F-9ED5-92BE69933BE7] (Simulator),iPhone 6s (9.3) [01FEB9F3-F870-470E-B9FE-EA3D577A0A4E] (Simulator),iPhone 6s (9.3) + Apple Watch - 38mm (2.2) [AF9FCBF1-8B19-41F0-88B4-78AE330B3B17] (Simulator),iPhone 6s Plus (9.3) [D72CC7E6-F0E7-4875-B884-6D1B3D65094B] (Simulator),iPhone 6s Plus (9.3) + Apple Watch - 42mm (2.2) [BA7ECE98-06AE-41CC-91E5-E75CAF73160A] (Simulator)
[iOSSim] Retrieving device name string for Xcode version 7.3.1
[debug] [iOSSim] Getting device string from options: {"deviceName":"b08d743e4c8acc04d2ba4adf16b460916d54ae0e","platformVersion":"9.3","forceIphone":false,"forceIpad":false}
[debug] [iOSSim] Final device string is 'b08d743e4c8acc04d2ba4adf16b460916d54ae0e (9.3)'
[iOS] Error: Could not find a device to launch. You requested 'b08d743e4c8acc04d2ba4adf16b460916d54ae0e (9.3)', but the available devices were: ["Apple TV 1080p (9.2) [A4560DCA-9F32-4ED7-9BF1-A24EE277B66B] (Simulator)","iPad 2 (9.3) [68D54A28-AE03-46A9-88DA-08C42ED3FD80] (Simulator)","iPad Air (9.3) [53AABC5F-316C-40AC-B7D4-EEC3B17692C4] (Simulator)","iPad Air 2 (9.3) [43D3C265-E5FF-4DCA-930E-38D3343A13FD] (Simulator)","iPad Pro (9.3) [980C59B7-DE39-4AA8-8005-85F79D781417] (Simulator)","iPad Retina (9.3) [709A8FE8-7741-4D7B-B10C-8CE34545E1E4] (Simulator)","iPhone 4s (9.3) [318F5CB8-C11A-4637-9005-C137DCA8FDE0] (Simulator)","iPhone 5 (9.3) [7AC2457B-4716-4642-94D6-09694C45CFAE] (Simulator)","iPhone 5s (9.3) [00272D14-1A38-4482-ABEF-FA7E241EB4F8] (Simulator)","iPhone 6 (9.3) [43F0C14F-AB7C-428B-839D-5AE7C181758E] (Simulator)","iPhone 6 Plus (9.3) [F0C394DF-C50F-4C1F-9ED5-92BE69933BE7] (Simulator)","iPhone 6s (9.3) [01FEB9F3-F870-470E-B9FE-EA3D577A0A4E] (Simulator)","iPhone 6s (9.3) + Apple Watch - 38mm (2.2) [AF9FCBF1-8B19-41F0-88B4-78AE330B3B17] (Simulator)","iPhone 6s Plus (9.3) [D72CC7E6-F0E7-4875-B884-6D1B3D65094B] (Simulator)","iPhone 6s Plus (9.3) + Apple Watch - 42mm (2.2) [BA7ECE98-06AE-41CC-91E5-E75CAF73160A] (Simulator)"]
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at noDevicesError (lib/driver.js:912:14)
    at IosDriver.checkSimAvailable$ (lib/driver.js:917:9)
    at tryCatch (/Users/Damien/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/Damien/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/Damien/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/Damien/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: Could not find a device to launch. You requested 'b08d743e4c8acc04d2ba4adf16b460916d54ae0e (9.3)', but the available devices were: ["Apple TV 1080p (9.2) [A4560DCA-9F32-4ED7-9BF1-A24EE277B66B] (Simulator)","iPad 2 (9.3) [68D54A28-AE03-46A9-88DA-08C42ED3FD80] (Simulator)","iPad Air (9.3) [53AABC5F-316C-40AC-B7D4-EEC3B17692C4] (Simulator)","iPad Air 2 (9.3) [43D3C265-E5FF-4DCA-930E-38D3343A13FD] (Simulator)","iPad Pro (9.3) [980C59B7-DE39-4AA8-8005-85F79D781417] (Simulator)","iPad Retina (9.3) [709A8FE8-7741-4D7B-B10C-8CE34545E1E4] (Simulator)","iPhone 4s (9.3) [318F5CB8-C11A-4637-9005-C137DCA8FDE0] (Simulator)","iPhone 5 (9.3) [7AC2457B-4716-4642-94D6-09694C45CFAE] (Simulator)","iPhone 5s (9.3) [00272D14-1A38-4482-ABEF-FA7E241EB4F8] (Simulator)","iPhone 6 (9.3) [43F0C14F-AB7C-428B-839D-5AE7C181758E] (Simulator)","iPhone 6 Plus (9.3) [F0C394DF-C50F-4C1F-9ED5-92BE69933BE7] (Simulator)","iPhone 6s (9.3) [01FEB9F3-F870-470E-B9FE-EA3D577A0A4E] (Simulator)","iPhone 6s (9.3) + Apple Watch - 38mm (2.2) [AF9FCBF1-8B19-41F0-88B4-78AE330B3B17] (Simulator)","iPhone 6s Plus (9.3) [D72CC7E6-F0E7-4875-B884-6D1B3D65094B] (Simulator)","iPhone 6s Plus (9.3) + Apple Watch - 42mm (2.2) [BA7ECE98-06AE-41CC-91E5-E75CAF73160A] (Simulator)"]
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at noDevicesError (lib/driver.js:912:14)
    at IosDriver.checkSimAvailable$ (lib/driver.js:917:9)
    at tryCatch (/Users/Damien/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/Damien/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/Damien/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/Damien/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[MJSONWP] Encountered internal error running command: Error: Could not find a device to launch. You requested 'b08d743e4c8acc04d2ba4adf16b460916d54ae0e (9.3)', but the available devices were: ["Apple TV 1080p (9.2) [A4560DCA-9F32-4ED7-9BF1-A24EE277B66B] (Simulator)","iPad 2 (9.3) [68D54A28-AE03-46A9-88DA-08C42ED3FD80] (Simulator)","iPad Air (9.3) [53AABC5F-316C-40AC-B7D4-EEC3B17692C4] (Simulator)","iPad Air 2 (9.3) [43D3C265-E5FF-4DCA-930E-38D3343A13FD] (Simulator)","iPad Pro (9.3) [980C59B7-DE39-4AA8-8005-85F79D781417] (Simulator)","iPad Retina (9.3) [709A8FE8-7741-4D7B-B10C-8CE34545E1E4] (Simulator)","iPhone 4s (9.3) [318F5CB8-C11A-4637-9005-C137DCA8FDE0] (Simulator)","iPhone 5 (9.3) [7AC2457B-4716-4642-94D6-09694C45CFAE] (Simulator)","iPhone 5s (9.3) [00272D14-1A38-4482-ABEF-FA7E241EB4F8] (Simulator)","iPhone 6 (9.3) [43F0C14F-AB7C-428B-839D-5AE7C181758E] (Simulator)","iPhone 6 Plus (9.3) [F0C394DF-C50F-4C1F-9ED5-92BE69933BE7] (Simulator)","iPhone 6s (9.3) [01FEB9F3-F870-470E-B9FE-EA3D577A0A4E] (Simulator)","iPhone 6s (9.3) + Apple Watch - 38mm (2.2) [AF9FCBF1-8B19-41F0-88B4-78AE330B3B17] (Simulator)","iPhone 6s Plus (9.3) [D72CC7E6-F0E7-4875-B884-6D1B3D65094B] (Simulator)","iPhone 6s Plus (9.3) + Apple Watch - 42mm (2.2) [BA7ECE98-06AE-41CC-91E5-E75CAF73160A] (Simulator)"]
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at noDevicesError (lib/driver.js:912:14)
    at IosDriver.checkSimAvailable$ (lib/driver.js:917:9)
    at tryCatch (/Users/Damien/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/Damien/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/Damien/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/Damien/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 1646 ms - 1403 

But when I do "instruments -s devices", I get:

> Last login: Tue Jun 14 12:33:17 on console
MacBook-Pro-de-Damien:~ Damien$ ls
AECF			Library			SafariLauncher-master
Applications		Movies			appium
Desktop			Music			cmdAppium.txt
Documents		Pictures		pip.ini
Downloads		Public
MacBook-Pro-de-Damien:~ Damien$ instruments -s devices
Known Devices:
2016-06-14 12:33:42.823 instruments[420:4340] WebKit Threading Violation - initial use of WebKit from a secondary thread.
MacBook Pro de Damien [8B3FCF1E-A5DA-5AB0-8782-3A0FA7C8EC3E]
iPhone de AECF (9.3.2) [b08d743e4c8acc04d2ba4adf16b460916d54ae0e]
Apple TV 1080p (9.2) [A4560DCA-9F32-4ED7-9BF1-A24EE277B66B] (Simulator)
iPad 2 (9.3) [68D54A28-AE03-46A9-88DA-08C42ED3FD80] (Simulator)
iPad Air (9.3) [53AABC5F-316C-40AC-B7D4-EEC3B17692C4] (Simulator)
iPad Air 2 (9.3) [43D3C265-E5FF-4DCA-930E-38D3343A13FD] (Simulator)
iPad Pro (9.3) [980C59B7-DE39-4AA8-8005-85F79D781417] (Simulator)
iPad Retina (9.3) [709A8FE8-7741-4D7B-B10C-8CE34545E1E4] (Simulator)
iPhone 4s (9.3) [318F5CB8-C11A-4637-9005-C137DCA8FDE0] (Simulator)
iPhone 5 (9.3) [7AC2457B-4716-4642-94D6-09694C45CFAE] (Simulator)
iPhone 5s (9.3) [00272D14-1A38-4482-ABEF-FA7E241EB4F8] (Simulator)
iPhone 6 (9.3) [43F0C14F-AB7C-428B-839D-5AE7C181758E] (Simulator)
iPhone 6 Plus (9.3) [F0C394DF-C50F-4C1F-9ED5-92BE69933BE7] (Simulator)
iPhone 6s (9.3) [01FEB9F3-F870-470E-B9FE-EA3D577A0A4E] (Simulator)
iPhone 6s (9.3) + Apple Watch - 38mm (2.2) [AF9FCBF1-8B19-41F0-88B4-78AE330B3B17] (Simulator)
iPhone 6s Plus (9.3) [D72CC7E6-F0E7-4875-B884-6D1B3D65094B] (Simulator)
iPhone 6s Plus (9.3) + Apple Watch - 42mm (2.2) [BA7ECE98-06AE-41CC-91E5-E75CAF73160A] (Simulator)

**Comment by CapDam** [comment]
Hi, 
After much research I get this:
> 
> Launching Appium with command: '/Applications/Appium.app/Contents/Resources/node/bin/node' appium/build/lib/main.js --address "127.0.0.1" --debug-log-spacing --platform-version "9.3" --platform-name "iOS" --udid "b08d743e4c8acc04d2ba4adf16b460916d54ae0e" --no-reset --device-name "iPhone 6" --launch-timeout "20000" --native-instruments-lib
> 
> [Appium] Welcome to Appium v1.5.3
> 
> [Appium] Non-default server args:
> 
> [Appium]   address: '127.0.0.1'
> [Appium]   debugLogSpacing: true
> [Appium]   platformName: 'iOS'
> [Appium]   platformVersion: '9.3'
> [Appium]   deviceName: 'iPhone 6'
> [Appium]   launchTimeout: 20000
> [Appium]   udid: 'b08d743e4c8acc04d2ba4adf16b460916d54ae0e'
> [Appium]   noReset: true
> [Appium]   nativeInstrumentsLib: true
> [Appium] Deprecated server args:
> [Appium]   --platform-name => --default-capabilities '{"platformName":"iOS"}'
> [Appium]   --platform-version => --default-capabilities '{"platformVersion":"9.3"}'
> [Appium]   --device-name => --default-capabilities '{"deviceName":"iPhone 6"}'
> [Appium]   -lt,--launch-timeout => --default-capabilities '{"launchTimeout":20000}'
> [Appium]   -U,--udid => --default-capabilities '{"udid":"b08d743e4c8acc04d2ba4adf16b460916d54ae0e"}'
> [Appium]   --no-reset => --default-capabilities '{"noReset":true}'
> [Appium]   --native-instruments-lib => --default-capabilities '{"nativeInstrumentsLib":true}'
> [Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
> [Appium]   platformName: 'iOS'
> [Appium]   platformVersion: '9.3'
> [Appium]   deviceName: 'iPhone 6'
> [Appium]   launchTimeout: 20000
> [Appium]   udid: 'b08d743e4c8acc04d2ba4adf16b460916d54ae0e'
> [Appium]   noReset: true
> [Appium]   nativeInstrumentsLib: true
> 
> [Appium] Appium REST http interface listener started on 127.0.0.1:4723
> 
> [HTTP] --> GET /wd/hub/status {}
> 
> [MJSONWP] Calling AppiumDriver.getStatus() with args: []
> 
> [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
> [HTTP] <-- GET /wd/hub/status 200 13 ms - 83 
> 
> [HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"platformVersion":"9.3","deviceName":"iPhone de AECF","browserName":"Safari","platformName":"IOS"}}
> 
> [MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformVersion":"9.3","...
> 
> [Appium] Creating new IosDriver session
> [Appium] Capabilities:
> [Appium]   platformVersion: '9.3'
> [Appium]   deviceName: 'iPhone TEST'
> [Appium]   browserName: 'Safari'
> [Appium]   platformName: 'IOS'
> [Appium]   launchTimeout: 20000
> [Appium]   udid: 'b08d743e4c8acc04d2ba4adf16b460916d54ae0e'
> [Appium]   noReset: true
> [Appium]   nativeInstrumentsLib: true
> [BaseDriver] Session created with session id: 585e7f8e-b063-4f4d-ae89-1f5972501d83
> [debug] [iOS] Not auto-detecting did.
> [debug] [iOS] Creating iDevice object with did b08d743e4c8acc04d2ba4adf16b460916d54ae0e

Maybe the problem is that he seeks "BUNDLE_ID com.bytearc.SafariLauncher =" whereas me he did not call him that that I installed on the iPhone with Xcode, but how well the set?

**Comment by imurchie** [comment]
If you build SafariLauncher from Xcode and install it on the device, that should suffice. 

Appium will try to build it with the default identity and code. It is up to you to make sure you have a proper provisioning profile.

Please see https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/mobile-web.md#setup

**Comment by CapDam** [comment]
Safari Launcher has been installed on the iPhone, I have the provisioning profile. But it does not work.
With Xcode, I installed SafariLancher with the bundle "com.SafariLaunch" yet appium displays "" BUNDLE_ID = com.bytearc.SafariLauncher "

**Comment by imurchie** [comment]
The bundle id for the SafariLauncher is `com.bytearc.SafariLauncher`.

**Comment by CapDam** [comment]
Yes but to install Safari on iOS Launcher I had to change the bundle if it did not work. So the bundle is "com.SafariLaunch". How should I do it?

**Comment by imurchie** [comment]
I don't understand the problem. The SafariLauncher code (https://github.com/snevesbarros/SafariLauncher) doesn't work? What did you change and why?

**Comment by CapDam** [comment]
To create a new App ID and select the WildCard App ID must pay $ 99? Because I myself now between a bundle in xcode and I click on "Fix issue" but if I enter "com.bytearc.SafariLauncher" it does not work.

**Comment by CapDam** [comment]
I'm really starting to despair ... someone an idea?

**Comment by affinage** [comment]
Have the same issue as @CapDam 
I'm unable to build using bundle_id `com.bytearc.SafariLauncher` with the same error: `An App ID with Identifier 'com.bytearc.SafariLauncher' is not available. Please enter a different string.`

So is it possible to build using 'free' developer account or at least change somewhere locally bundle id that appium is trying to launch?

**Comment by aluzardo** [comment]
I have the same problem @CapDam 

Did you fix it?

**Comment by SrinivasanTarget** [comment]
Closing this because of inactivity. @triager please close

**Comment by zcmgyu** [comment]
Same issue

**Comment by imurchie** [comment]
The reset.sh file has not existed for over two years. Whatever issue you are having is almost certainly not this one, at least not it its particulars. Please create a new issue.
