### ISSUE TITLE
Problem with ideviceinstaller command while running Appium Inspector 

### ISSUE THREAD

**Issue by geek154** [appium/appium#6596]
## The problem
Hi there.

I am trying to automate test cases on my app on iPad Mini 3. Able launch the server but couldn't able to start inspector or simulator, getting error right after that
![screen shot 2016-06-16 at 3 31 26 pm](https://cloud.githubusercontent.com/assets/19987996/16141291/b210de48-3477-11e6-943a-566284eabde7.png)

Settings screenshots
![screen shot 2016-06-17 at 10 33 35 am](https://cloud.githubusercontent.com/assets/19987996/16141298/bac83acc-3477-11e6-9fc9-e327e372d911.png)

![screen shot 2016-06-17 at 10 33 14 am](https://cloud.githubusercontent.com/assets/19987996/16141246/293226a4-3477-11e6-9003-e0d0f6ebda09.png)

## Environment

* Appium version 1.5.3 Ara
* Mac OS X EI Caption 10.11.4
* iPad Mini3 real device

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Appium logs

Launching Appium with command: '/Applications/Appium.app/Contents/Resources/node/bin/node' appium/build/lib/main.js --address "127.0.0.1" --pre-launch --debug-log-spacing --platform-version "9.3" --platform-name "iOS" --app "/Users/ramanathp/Desktop/UICatalog.app" --udid "cbd2c9c3f550567c91c6c4214b6e78b2991bd" --show-ios-log --device-name "iPad Pro" --native-instruments-lib

[Appium] Welcome to Appium v1.5.3

[Appium] Non-default server args:

[Appium]   address: '127.0.0.1'

[Appium]   launch: true

[Appium]   debugLogSpacing: true
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '9.3'
[Appium]   deviceName: 'iPad Pro'
[Appium]   app: '/Users/ramanathp/Desktop/UICatalog.app'

[Appium]   udid: 'cbd2c9c3f550567c91c6c4214b6e78b2991bd'
[Appium]   nativeInstrumentsLib: true
[Appium]   showIOSLog: true
[Appium] Deprecated server args:
[Appium]   --platform-name => --default-capabilities '{"platformName":"iOS"}'
[Appium]   --platform-version => --default-capabilities '{"platformVersion":"9.3"}'
[Appium]   --device-name => --default-capabilities '{"deviceName":"iPad Pro"}'
[Appium]   --app => --default-capabilities '{"app":"/Users/ramanathp/Desktop/UICatalog.app"}'
[Appium]   -U,--udid => --default-capabilities '{"udid":"cbd2c9c3f550567c91c6c4214b6e78b2991bd"}'
[Appium]   --native-instruments-lib => --default-capabilities '{"nativeInstrumentsLib":true}'
[Appium]   --show-ios-log => --default-capabilities '{"showIOSLog":true}'
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:

[Appium]   platformName: 'iOS'

[Appium]   platformVersion: '9.3'
[Appium]   deviceName: 'iPad Pro'
[Appium]   app: '/Users/ramanathp/Desktop/UICatalog.app'
[Appium]   udid: 'cbd2c9c3f550567c91c6c4214b6e78b2991bd'
[Appium]   nativeInstrumentsLib: true
[Appium]   showIOSLog: true

[Appium] Appium REST http interface listener started on 127.0.0.1:4723

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[HTTP] <-- GET /wd/hub/status 200 72 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[HTTP] <-- GET /wd/hub/status 200 15 ms - 83 
[HTTP] --> GET /wd/hub/sessions {}
[MJSONWP] Calling AppiumDriver.getSessions() with args: []
[MJSONWP] Responding to client with driver.getSessions() result: []

[HTTP] <-- GET /wd/hub/sessions 200 5 ms - 40 

[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"iOS","newCommandTimeout":"7200","app":"/Users/ramanathp/Desktop/UICatalog.app","platformVersion":"9.3","udid":"cbd2c9c3f550567c91c6c4214b6e78b2991bd","deviceName":"iPad Pro","automationName":"Appium"}}

[MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"iOS","new...
[Appium] Creating new IosDriver session
[Appium] Capabilities:
[Appium]   platformName: 'iOS'
[Appium]   newCommandTimeout: '7200'
[Appium]   app: '/Users/ramanathp/Desktop/UICatalog.app'
[Appium]   platformVersion: '9.3'
[Appium]   udid: 'cbd2c9c3f550567c91c6c4214b6e78b2991bd'
[Appium]   deviceName: 'iPad Pro'
[Appium]   automationName: 'Appium'
[Appium]   nativeInstrumentsLib: true
[Appium]   showIOSLog: true

[BaseDriver] Capability 'newCommandTimeout' changed from string ('7200') to integer (7200). This may cause unexpected behavior
[BaseDriver] Session created with session id: 90071079-fbb7-45a4-b46a-e27125da706b
[debug] [iOS] Not auto-detecting udid.

[BaseDriver] Using local app '/Users/ramanathp/Desktop/UICatalog.app'
[debug] [iOS] Removing any remaining instruments sockets
[debug] [iOS] Cleaned up instruments socket /var/folders/mk/mhdm2tm96h9dktfx618h71jc0000gn/T/instruments_sock
[debug] [iOS] No language specified. Using default strings

[debug] [iOS] Strings file not found. Looking in 'en.lproj' directory

[debug] [iOS] Parsed app 'Localizable.strings'

[debug] [ios-app-utils] Getting bundle ID from app

[iOS] Extracted bundleID: com.example.apple-samplecode.UICatalog from app: /Users/ramanathp/Desktop/UICatalog.app

[debug] [iOS] Creating instruments

[debug] [UIAuto] Preparing bootstrap code
[debug] [UIAuto] Dynamic bootstrap dir: /Users/ramanathp/Library/Application Support/appium/bootstrap
[debug] [UIAuto] Dynamic env: {"nodePath":"/Applications/Appium.app/Contents/Resources/node/bin/node","commandProxyClientPath":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js","instrumentsSock":"/var/folders/mk/mhdm2tm96h9dktfx618h71jc0000gn/T/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"grouped"}

[debug] [UIAuto] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...

[debug] [UIAuto] Dynamic bootstrap path: /Users/ramanathp/Library/Application Support/appium/bootstrap/bootstrap-19e27d27dcf9254c.js

[debug] [UIAuto] Reusing dynamic bootstrap: /Users/ramanathp/Library/Application Support/appium/bootstrap/bootstrap-19e27d27dcf9254c.js
[debug] [iOS] Running ios real device reset flow

[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog

[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'

[debug] [iOS] Creating iDevice object with udid cbd2c9c3f550567c91c6c4214b6e78b2991bd

[MJSONWP] Encountered internal error running command: Error: Command failed: ideviceinstaller -u cbd2c9c3f550567c91c6c4214b6e78b2991bd -l 

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)

[HTTP] <-- POST /wd/hub/session 500 636 ms - 216 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 12 ms - 83

**Comment by mykola-mokhnach** [comment]
Which output do you get if this command is executed manually? Does your device have developer mode enabled and UI Automation switcher selected?

**Comment by geek154** [comment]
Thank you for response. I've enabled UI Automation under Developer Settings. When I copy that command and paste it in terminal, it is saying Invalid UDID specified. Even though it is the correct one. Another thing to note is I used iPad Pro in Force device section as I couldn't find iPad Mini 3.

**Comment by mykola-mokhnach** [comment]
I think you can omit device name if UDID is provided

**Comment by geek154** [comment]
Tried that. Could't launch inspector and in the logs got below error:
[BaseDriver] SessionNotCreatedError: A new session could not be created. Details: The desiredCapabilities object was not valid for the following reason(s): deviceName can't be blank.

**Comment by mykola-mokhnach** [comment]
Try to just specify iPad as device name

**Comment by mykola-mokhnach** [comment]
Also the application under test itself should be built in debug mode and be signed with valid developer signature (not enterprise)

**Comment by geek154** [comment]
Yeah tried that too. Specifying name as iPad gives me same error again
[MJSONWP] Encountered internal error running command: Error: Command failed: ideviceinstaller -u cbd2c9c3f550567c91c6c4214b6e78b2991 -l

**Comment by mykola-mokhnach** [comment]
what is the output of this command if executed directly from Terminal?

**Comment by geek154** [comment]
As previously mentioned, it is 
ERROR: Invalid UDID specified

**Comment by mykola-mokhnach** [comment]
try to install ideviceinstaller manually using brew
```bash
brew install ideviceinstaller
```

**Comment by SrinivasanTarget** [comment]
Closing this because of inactivity.I dont see any issues here.Please reopen if you hit the same.

**Comment by SrinivasanTarget** [comment]
@triager please close

**Comment by huig1149** [comment]
@geek154 
I solve the similar problew by reinstalling ideviceinstaller and libimobiledevice. You need the latest libimobiledevice, in the Appium 1.5.3 version.
Open the Terminal, type the commands below:

1. brew uninstall ideviceinstaller 
2. brew uninstall libimobiledevice 
3. brew install --HEAD libimobiledevice 
4. brew link --overwrite libimobiledevice 
5. brew install ideviceinstaller 
6. brew link --overwrite ideviceinstaller

It may work for you.
