### ISSUE TITLE
Install fail

### ISSUE THREAD

**Issue by huzhenjie** [appium/appium#6624]
```
$ npm install -g appium 
/usr/local/bin/appium -> /usr/local/lib/node_modules/appium/build/lib/main.js
/usr/local/bin/authorize-ios -> /usr/local/lib/node_modules/appium/node_modules/.bin/authorize-ios

> fsevents@1.0.12 install /usr/local/lib/node_modules/appium/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
  COPY /usr/local/lib/node_modules/appium/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node
  TOUCH Release/obj.target/action_after_build.stamp

> appium-chromedriver@2.9.2 install /usr/local/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-chromedriver
> node install-npm.js

info Chromedriver Install Installing Chromedriver version '2.21' for platform 'mac' and architecture '32'
info Chromedriver Install Opening temp file to write chromedriver_mac32 to...
info Chromedriver Install Downloading http://chromedriver.storage.googleapis.com/2.21/chromedriver_mac32.zip...
info Chromedriver Install Writing binary content to /var/folders/mk/9b595sc93dg080fps5_cxfvm0000gn/T/2016528-8639-1l6t62x.vht0il766r/chromedriver_mac32.zip...
info Chromedriver Install Extracting /var/folders/mk/9b595sc93dg080fps5_cxfvm0000gn/T/2016528-8639-1l6t62x.vht0il766r/chromedriver_mac32.zip to /var/folders/mk/9b595sc93dg080fps5_cxfvm0000gn/T/2016528-8639-1l6t62x.vht0il766r/chromedriver_mac32
info Chromedriver Install Creating /usr/local/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-chromedriver/chromedriver/mac...
info Chromedriver Install Copying unzipped binary, reading from /var/folders/mk/9b595sc93dg080fps5_cxfvm0000gn/T/2016528-8639-1l6t62x.vht0il766r/chromedriver_mac32/chromedriver...
info Chromedriver Install Writing to /usr/local/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver...
info Chromedriver Install /usr/local/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver successfully put in place

> appium-selendroid-driver@1.3.4 install /usr/local/lib/node_modules/appium/node_modules/appium-selendroid-driver
> node ./bin/install.js

dbug AndroidDriver Getting Java version
info SelendroidInstaller Ensuring /usr/local/lib/node_modules/appium/node_modules/appium-selendroid-driver/node_modules/appium-selendroid-installer/selendroid/download exists
info AndroidDriver Java version is: 1.8.0_20
info SelendroidInstaller Downloading Selendroid standalone server version 0.17.0 from https://github.com/selendroid/selendroid/releases/download/0.17.0/selendroid-standalone-0.17.0-with-dependencies.jar --> /usr/local/lib/node_modules/appium/node_modules/appium-selendroid-driver/node_modules/appium-selendroid-installer/selendroid/download/selendroid-server.jar

/usr/local/lib/node_modules/appium/node_modules/appium-selendroid-driver/node_modules/appium-selendroid-installer/node_modules/request-promise/lib/errors.js:11
        Error.captureStackTrace(this);
              ^
RequestError: Error: read ECONNRESET
    at new RequestError (/usr/local/lib/node_modules/appium/node_modules/appium-selendroid-driver/node_modules/appium-selendroid-installer/node_modules/request-promise/lib/errors.js:11:15)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/appium/node_modules/appium-selendroid-driver/node_modules/appium-selendroid-installer/node_modules/request-promise/lib/rp.js:56:32)
    at self.callback (/usr/local/lib/node_modules/appium/node_modules/appium-selendroid-driver/node_modules/appium-selendroid-installer/node_modules/request-promise/node_modules/request/request.js:200:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/usr/local/lib/node_modules/appium/node_modules/a/usr/local/lib
└── (empty)

npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "appium"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE

npm ERR! appium-selendroid-driver@1.3.4 install: `node ./bin/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appium-selendroid-driver@1.3.4 install script 'node ./bin/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the appium-selendroid-driver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs appium-selendroid-driver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls appium-selendroid-driver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/yixuanxuan/tmp/npm-debug.log
npm ERR! code 1
```

**Comment by mykola-mokhnach** [comment]
Are you able to download this jar file manually using curl?
```bash
curl -L https://github.com/selendroid/selendroid/releases/download/0.17.0/selendroid-standalone-0.17.0-with-dependencies.jar > selendroid-server.jar
```

Maybe your connection quality is not very good. Then try to play with npm's _retries_, _factor_, _minTimeout_ and _maxTimeout_ options (actually, you need to increase their default values).

**Comment by huzhenjie** [comment]
Thx!

when I change my connection, it works

```
$ npm install -g appium 
/usr/local/bin/appium -> /usr/local/lib/node_modules/appium/build/lib/main.js
/usr/local/bin/authorize-ios -> /usr/local/lib/node_modules/appium/node_modules/.bin/authorize-ios
/usr/local/lib
└── appium@1.5.3 
```

Evil GFW

**Comment by laiyuncong8404** [comment]
I have enable proxy in npm config，but still suffering this。
How did you fix it? @huzhenjie

**Comment by huzhenjie** [comment]
I use vpn and try to install again, it works

Maybe I can share the vpn account to you for one day. (I also have a vps)

You can send your application by mail.

My E-mail: `huzhenjie.dev@gmail.com`

**Comment by laiyuncong8404** [comment]
I had used vpn also, it’s Shadowsocks and enable system proxy,
My npm‘s setting profile is likely below:
```
fetch-retries=5
fetch-retry-factor=20
fetch-retry-mintimeout = 60000
fetch-retry-maxtimeout = 600000
registry=http://registry.npmjs.com
proxy=http://localhost:1080
```
I can download the `selendroid-standalone-0.17.0-with-dependencies.jar` manually.

**Comment by akiwarheit** [comment]
Same issue with @laiyuncong8404 I have proxy, can download the jar manually, but I'm getting the socket timeout error. I'll let you know if I can successfully download this. Looks like a proxy issue.
