### ISSUE TITLE
driver.install_app giving "Method has not yet been implemented" error

### ISSUE THREAD

**Issue by juhlila** [appium/appium#6659]
## The problem

I cannot use the method install_app (and some of other methods listed [here](https://github.com/appium/appium/blob/51285550eadb907e5cf90931a0c72ec7bc4a004d/docs/en/writing-running-appium/appium-bindings.md)). It says method is not yet implemented
## Environment
- Appium version (or git revision) that exhibits the issue: 1.5.3
- Last Appium version that did not exhibit the issue (if applicable): i was running 1.5.2 but never tried install_app on that version
- Desktop OS/version used to run Appium: mac el capitan
- Node.js version (unless using Appium.app|exe): 3.10.3
- Mobile platform/version under test: ios version 8.\* and 9.*
- Real device or emulator/simulator:  real devices
- Appium CLI or Appium.app|exe: cli
## Details

When I try to use install_app method inside a context, i see that error. Some o appium bindings works, some dont. 

if i use driver.install (as sugested), i get this message:
`NoMethodError:
       undefined method`install' for #<Selenium::WebDriver::Driver:0x7e0b57a05ecf54ce browser=:"">
       Did you mean?  install_app
`

Im using rspec scenarios. 
capabilities:

`capabilities = {
    platformName: 'iOS',
    versionNumber: '9.3',
    deviceName: get_device_name,
    app: app_path,
    backendRetries: 1,
    launchTimeout: 1000000,
    autoAcceptAlerts: true,
    newCommandTimeout: 12000,
    udid: get_udid
}` 

$appium = Appium::Driver.new(caps: capabilities)
$browser = $appium.start_driver
Appium.promote_appium_methods self.class
Appium.promote_appium_methods Object
Appium.promote_appium_methods Selenium::WebDriver #i added this later to try to solve the problem
Appium.promote_appium_methods RSpec::Core::ExampleGroup #i added this later to try to solve the problem
## Link to Appium logs

https://gist.github.com/juhlila/707a4fd6bfc996a9086d4c1a24018e80

about the log, i tried with fullReset false and it didnt work
## Code To Reproduce Issue [ Good To Have ]

```
describe 'Gameplay' do
    dir = File.dirname(File.expand_path( __FILE__))
    oi =  dir + '/IPAs/cheats4.ipa'
  before :all do
    driver.install_app oi
  end
it 'should work here too'
    driver.install_app oi
end 
```

**Comment by juhlila** [comment]
and if its a appium method, why i get a selenium error?

**Comment by imurchie** [comment]
Does this error still persist in more recent versions?

**Comment by DavidEpsh** [comment]
I still get this error on appium 1.6.3

**Comment by imurchie** [comment]
@DavidEpsh Can you provide logs so we can do something about this? Absent them, there is nothing to go on.

**Comment by DavidEpsh** [comment]
This is the log, happens when trying to install an app on IOS simulator:

org.openqa.selenium.WebDriverException: Method has not yet been implemented (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 5 milliseconds
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'Davids-MacBook-Pro-3.local', ip: '10.0.1.33', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.3', java.version: '1.8.0_92'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{app=/Users/David/IdeaProjects/myautoproj/src/main/java/apps/myapp.app, networkConnectionEnabled=false, noReset=true, databaseEnabled=false, deviceName=iPhone 6, launchTimeout=99999, fullReset=false, platform=MAC, desired={app=/Users/David/IdeaProjects/myautoproj/src/main/java/apps/myapp.app, noReset=true, sendKeyStrategy=oneByOne, newCommandTimeout=99999, platformVersion=9.3, platformName=iOS, deviceName=iPhone 6, launchTimeout=99999, fullReset=false}, sendKeyStrategy=oneByOne, newCommandTimeout=99999, platformVersion=9.3, webStorageEnabled=false, locationContextEnabled=false, browserName=, takesScreenshot=true, javascriptEnabled=true, platformName=iOS}]
Session ID: d5537244-192c-4668-8c94-c03eb9a11f43

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:40)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at io.appium.java_client.AppiumDriver.installApp(AppiumDriver.java:262)
	at scenarios.TestSetup.resetAppDataUsingAppium(TestSetup.java:101)
	at scenarios.SignInTest.signInAfterReset(SignInTest.java:82)
	at scenarios.SignInTest.signInOrSkip(SignInTest.java:141)
	at scenarios.TestSetup.signInOrSkipBeforeClass(TestSetup.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:178)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

**Comment by imurchie** [comment]
We need the Appium server logs, not the client logs. Please attach as a link to a [gist](https://gist.github.com).

**Comment by DavidEpsh** [comment]
So I found the problem-
1. First attempt: I call driver.RemoveApp() while app is running -> i get black screen on the simulator -> then `driver.installApp()` just hangs and throws the `Method has not yet been implemented ` exception. This black screen happens only when uninstalling the application while its running, also if i execute uninstall manually from command line, after that i always need to press on the home button twice to be able to exit the black screen.
2. then i tried to call closeApp() before calling removeApp() and installApp() after the method . This throws `Driver is not ready, cannot execute removeApp` - this happens because on IOS `driver.closeApp()` kills the instruments client socket. 

Solution for anyone interested:
1. calling the function: driver.closeApp()
2. calling Runtime.getRuntime().exec("xcrun simctl uninstall booted <bundleID>");

**Comment by juhlila** [comment]
Unfortunatelly I am not working with appium in ruby anymore, I couldnt manage to make install_app work. If you came here from a google search, heres how i did to install the app:

```
def install(app)
   app_ipa = project_home + '/ipa/' + app
   driver_quit

   puts "Installing #{app}"
   install_and_run = Thread.new {
   Thread.abort_on_exception = true
      system "ideviceinstaller -u #{get_udid} -g #{app_ipa}"
   }
   puts ''
   print '.' until install_and_run.join(1)
   puts "\n Starting appium driver"
   startdriver = Thread.new {
      Thread.abort_on_exception = true
      start_appium_driver(app: app)
   }
   puts ''
   print '.' until startdriver.join(1); puts ''
end
```
