### ISSUE TITLE
'waitForElementByName''s selector is invalid because of Locator strategy 'name' error

### ISSUE THREAD

**Issue by firekyrin** [appium/appium#6687]
## The problem

i got anothor fail like this:

```
1) ios webview should get the url:
     [waitForElementByName("q",5000)] [elements("name","q")] Error response status: 32, , InvalidSelector - Argument was an invalid selector (e.g. XPath/CSS). Selenium error: Locator Strategy 'name' is not supported for this session
  Error: [elements("name","q")] Error response status: 32, , InvalidSelector - Argument was an invalid selector (e.g. XPath/CSS). Selenium error: Locator Strategy 'name' is not supported for this session
      at exports.newError (node_modules/wd/lib/utils.js:139:13)
      at node_modules/wd/lib/callbacks.js:75:19
      at node_modules/wd/lib/webdriver.js:174:5
      at Request._callback (node_modules/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:926:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)
```

it is because of that i fixed code in ios-webview.js:
```
it("should get the url", function () {
    return driver
      .elementByXPath('//UIATextField[@value=\'Enter URL\']')
        .sendKeys('www.google.com')
    //   .elementByName('Go').click()
      .elementByXPath('//UIAButton').click()
      .elementByClassName('UIAWebView').click() // dismissing keyboard
    //   .context('WEBVIEW')
      .sleep(1000)
      .waitForElementByName('q', 5000)
        .sendKeys('sauce labs')
        .sendKeys(wd.SPECIAL_KEYS.Return)
      .sleep(1000)
      .title().should.eventually.include('sauce labs');
  });
```
and i run cmd line in exmaple code:
```
$ npm run ios-webview
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Darwin kaideMacBook-Pro.local 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64

* Node.js version (unless using Appium.app|exe): v6.2.0
* Mobile platform/version under test: iPhone 6
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe:  Appium.app

**Comment by mykola-mokhnach** [comment]
ByName strategy has been changed to AccessibilityId since Appium release 1.5. Check https://github.com/appium/appium/blob/master/CHANGELOG.md for more details.

**Comment by SrinivasanTarget** [comment]
@triager please close
