### ISSUE TITLE
Simulator stopped responding during CI runs.

### ISSUE THREAD

**Issue by harisudhag** [appium/appium#6696]
## The problem

During the CI run, the simulator stops responding for a while before resuming the automation and I see the following error in the console,

[Instruments] Error: Failed getting devices, err: Error: Command '/Applications/Xcode.app/Contents/Developer/usr/bin/instruments -s devices' timed out after 90000ms.
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at getAvailableDevices$ (lib/utils.js:38:9)
    at tryCatch (/Users/builder/.nvm/versions/node/v6.2.2/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke](/Users/builder/.nvm/versions/node/v6.2.2/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw](/Users/builder/.nvm/versions/node/v6.2.2/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/builder/.nvm/versions/node/v6.2.2/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: Failed getting devices, err: Error: Command '/Applications/Xcode.app/Contents/Developer/usr/bin/instruments -s devices' timed out after 90000ms.
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at getAvailableDevices$ (lib/utils.js:38:9)
    at tryCatch (/Users/builder/.nvm/versions/node/v6.2.2/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke](/Users/builder/.nvm/versions/node/v6.2.2/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw](/Users/builder/.nvm/versions/node/v6.2.2/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/builder/.nvm/versions/node/v6.2.2/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
## Environment
- Appium version (or git revision) that exhibits the issue: 1.5.3
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium: OS X 10.11.6
- Node.js version (unless using Appium.app|exe): 6.2.2
- Mobile platform/version under test: iPad Air iOS 9.3 and iPad Air 2 iOS 9.3
- Real device or emulator/simulator: simulator
- Appium CLI or Appium.app|exe: Appium cli
## Details

The test automation suite runs in gitlab CI, which uses vmware -> OSX images to run the tests. During the automation run, the simulator stops responding for 90000ms and then resumes the execution. These errors happens for 4 or 5 times for executing 50 tests, which increases the execution time for test suite.
## Link to Appium logs

[appium.log.txt](https://github.com/appium/appium/files/382892/appium.log.txt)

**Comment by mykola-mokhnach** [comment]
We also have the same random problem. It looks more like Apple instruments issue to me. Anyway, we've created a workaround for it - the driver has overridden _execute_ method, which runs every appium command as separate Future instance and then raises TimeoutException if this command takes more than X seconds for execution.
