### ISSUE TITLE
Facing problem with remote appium call

### ISSUE THREAD

**Issue by tadesushilgithub** [appium/appium#6708]
## The problem

I am running appium 1st instance on 192.168.10.1 with port 5555 and 2nd instance on 192.168.10.1 with port 4444, 2 devices are connected to my system where I am expecting to run my script parallel. I have build definition created on TFS and scripts handle creating web-driver dynamically. But execution happening only on single device for 2nd device i.e second instance I am getting below error

info: [debug] [BOOTSTRAP] [debug] Socket opened on port 4724
info: [debug] [BOOTSTRAP] [debug] Appium Socket Server Ready
info: [debug] Waking up device if it's not alive
info: [debug] Pushing command to appium work queue: ["wake",{}]
info: [debug] [BOOTSTRAP] [debug] Loading json...
error: Unhandled error: Error: read ECONNRESET
    at errnoException (net.js:905:11)
    at TCP.onread (net.js:559:19) context: [POST /wd/hub/session {"desiredCapabi
lities":{"automationName":"Appium","deviceName":"Android","platformName":"Androi
d","platformVersion":"5.0","platform":"Windows","autoWebView":true,"app":null,"a
ppPackage":"com.something.c]
info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.

## Environment

* Appium 1.3.4
* Desktop OS/version used to run Appium: Mac and windows 
* Node.js version (unless using Appium.app|exe): v 0.10.35
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real android devices

**Comment by tadesushilgithub** [comment]
After struggling for long day I got the solution. I was creating multiple instances of appium in wrong way. I have created the service which creates instances of appium on server and my parallel test were not running properly. So I went through appium parallel guide and this fixed :). While creating appium I need to pass address,port, bootstrap port and udid with it to work smoothly.
