### ISSUE TITLE
Getting error as "org.openqa.selenium.WebDriverException: unknown error: bad inspector message....."

### ISSUE THREAD

**Issue by GudiaRani** [appium/appium#6709]
I am getting below error while executing scripts using Selenium and APPIUM only on Chrome browser.
Below issue is occurring when clicking a tab.Same code is working on Firefox not on Chrome...
Versions - Chrome 52.0.2743.82 and chromedriver version - 2.22.397933. APPIUM version 1.4.13 and 1.4.16....Can someone please help me to resolve this issue...
**Error**
```
[186.662][SEVERE]: Bad inspector message: {"method":"Console.messageAdded","params":{"message":{"source":"console-api","level":"log","text":"[object Object]","type":"log",
"url":"https://Application URL/scripts/scripts.eb4172d5.js","line":58,"column":23261,"parameters":[{"type":"object","className":"Object",
"description":"Object","objectId":"{\"injectedScriptId\":1,\"id\":9}","preview":{"type":"object","description":"Object","overflow":false,
"properties":[{"name":"Key","type":"string","value":"BusinessGroup"},{"name":"Value","type":"string","value":"\u3782\u20D2\u0A60\u9E20\u5C20\u2102\uB819\uC096\u03B0\u8A50\u7101\u380F\u6480\u0E20\u0342j\u0218\u0364\u8470\u0DAAF\uAA6D\u9E46\u9024\u8013\u3821\u7003\u100F\u2144\u3E08\u00CC\u23E7\uCF40\u32B1\u7C01\u8C20\u0614\u2029\uBC29\u33E6\u2956\uB340\u116C\uEBF1\uA120\u05CD\u210C\uC203\uF21B\u90A9\u2026\uDB20\u1B6C\u2D8E\u8BB7\u12D8\u5FDB\uC204\uEF79\uB65D\u770E\uD31F\uE19D\u4CAC\u06D2\u34D6\u0016\u910A\u3B9F\u73A8\uEDFA\uBD67\u7AD5\uDF80\u3F7C\u3681\uC8D2~\uEB5F\u518D\uB3A9\u6300\u0BA9\u4050\u37F4\u92D0\u1843\u4E1A\u048B\uF037\uF3A0\u8410\u8249\u5208\u5715\u40B6\u400D\u6402\u8420\u0000"},
{"name":"s_key","type":"string","value":"master_lookupdata/BusinessGroup"}]}}],"stack":{"callFrames":[{"functionName":"","scriptId":"49",
"url":"https://Application URL/scripts.eb4172d5.js","lineNumber":58,"columnNumber":23261},{"functionName":"","scriptId":"49",
"url":"https://Application URL/scripts/scripts.eb4172d5.js","lineNumber":53,"columnNumber":26469},
{"functionName":"","scriptId":"49","url":"https://Application URL/scripts/scripts.eb4172d5.js","lineNumber":54,"columnNumber":20714}]},
"timestamp":1470145104.94625,"executionContextId":1}}}
FAILED: onlineMode
org.openqa.selenium.WebDriverException: unknown error: bad inspector message: {"method":"Console.messageAdded","params":{"message":{"source":"console-api",
"level":"log","text":"[object Object]","type":"log","url":"https://Application URL/scripts/scripts.eb4172d5.js","line":58,"column":23261,
"parameters":[{"type":"object","className":"Object","description":"Object","objectId":"{\"injectedScriptId\":1,\"id\":9}",
"preview":{"type":"object","description":"Object","overflow":false,"properties":[{"name":"Key","type":"string","value":"BusinessGroup"},
{"name":"Value","type":"string","value":"\u3782\u20D2\u0A60\u9E20\u5C20\u2102\uB819\uC096\u03B0\u8A50\u7101\u380F\u6480\u0E20\u0342j\u0218\u0364\u8470\u0DAAF\uAA6D\u9E46\u9024\u8013\u3821\u7003\u100F\u2144\u3E08\u00CC\u23E7\uCF40\u32B1\u7C01\u8C20\u0614\u2029\uBC29\u33E6\u2956\uB340\u116C\uEBF1\uA120\u05CD\u210C\uC203\uF21B\u90A9\u2026\uDB20\u1B6C\u2D8E\u8BB7\u12D8\u5FDB\uC204\uEF79\uB65D\u770E\uD31F\uE19D\u4CAC\u06D2\u34D6\u0016\u910A\u3B9F\u73A8\uEDFA\uBD67\u7AD5\uDF80\u3F7C\u3681\uC8D2~\uEB5F\u518D\uB3A9\u6300\u0BA9\u4050\u37F4\u92D0\u1843\u4E1A\u048B\uF037\uF3A0\u8410\u8249\u5208\u5715\u40B6\u400D\u6402\u8420\u0000"},
{"name":"s_key","type":"string","value":"master_lookupdata/BusinessGroup"}]}}],"stack":{"callFrames":[
{"functionName":"","scriptId":"49","url":"https://Application URL/scripts/scripts.eb4172d5.js","lineNumber":58,"columnNumber":23261},
{"functionName":"","scriptId":"49","url":"https://Application URL/scripts/scripts.eb4172d5.js",
"lineNumber":53,"columnNumber":26469},{"functionName":"","scriptId":"49","url":"https://Application URL/scripts/scripts.eb4172d5.js",
"lineNumber":54,"columnNumber":20714}]},"timestamp":1470145104.94625,"executionContextId":1}}}
  (Session info: chrome=52.0.2743.82)
  (Driver info: chromedriver=2.22.397933 (1cab651507b88dec79b2b2a22d1943c01833cc1b),platform=Windows NT 6.1.7601 SP1 x86_64) 
(WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 9 milliseconds
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 16:57:40'
System info: host: 'Cd390-B21RVS1', ip: '10.10.53.102', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_51'
**\* Element info: {Using=xpath, value=//_[@id='menu_list']/li[2]/a}
Session ID: 8f4446bd7f9b1937154b62b30486e221
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{platform=XP, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=C:\Users\XXX\AppData\Local\Temp\scoped_dir5184_20574, chromedriverVersion=2.22.397933 (1cab651507b88dec79b2b2a22d1943c01833cc1b)}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=52.0.2743.82, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, hasTouchScreen=false, applicationCacheEnabled=false, takesScreenshot=true}]
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:363)
at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:500)
at org.openqa.selenium.By$ByXPath.findElement(By.java:361)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:355)
at TestReports.iWGO1.caseCompletion(iWGO1.java:585)
at TestReports.iWGO_FODesktop.onlineMode(iWGO_FODesktop.java:109)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:617)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
at org.testng.SuiteRunner.run(SuiteRunner.java:240)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
at org.testng.TestNG.run(TestNG.java:1057)
at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
org.openqa.selenium.WebDriverException: unknown error: bad inspector message: {"method":"Console.messageAdded","params":{"message":{"source":"console-api",
"level":"log","text":"[object Object]","type":"log","url":"https://Application URL/scripts/scripts.eb4172d5.js",
"line":58,"column":23261,"parameters":[{"type":"object","className":"Object","description":"Object","objectId":"{\"injectedScriptId\":1,\"id\":9}","preview":{"type":"object","description":"Object","overflow":false,"properties":[{"name":"Key","type":"string","value":"BusinessGroup"},{"name":"Value","type":"string","value":"\u3782\u20D2\u0A60\u9E20\u5C20\u2102\uB819\uC096\u03B0\u8A50\u7101\u380F\u6480\u0E20\u0342j\u0218\u0364\u8470\u0DAAF\uAA6D\u9E46\u9024\u8013\u3821\u7003\u100F\u2144\u3E08\u00CC\u23E7\uCF40\u32B1\u7C01\u8C20\u0614\u2029\uBC29\u33E6\u2956\uB340\u116C\uEBF1\uA120\u05CD\u210C\uC203\uF21B\u90A9\u2026\uDB20\u1B6C\u2D8E\u8BB7\u12D8\u5FDB\uC204\uEF79\uB65D\u770E\uD31F\uE19D\u4CAC\u06D2\u34D6\u0016\u910A\u3B9F\u73A8\uEDFA\uBD67\u7AD5\uDF80\u3F7C\u3681\uC8D2~\uEB5F\u518D\uB3A9\u6300\u0BA9\u4050\u37F4\u92D0\u1843\u4E1A\u048B\uF037\uF3A0\u8410\u8249\u5208\u5715\u40B6\u400D\u6402\u8420\u0000"},{"name":"s_key","type":"string","value":"master_lookupdata/BusinessGroup"}]}}],"stack":{"callFrames":[{"functionName":"","scriptId":"49","url":"https://Application URL/scripts/scripts.eb4172d5.js","lineNumber":58,"columnNumber":23261},
{"functionName":"","scriptId":"49","url":"https://iApplication URL/scripts/scripts.eb4172d5.js",
"lineNumber":53,"columnNumber":26469},{"functionName":"","scriptId":"49","url":"https://Application URL/scripts/scripts.eb4172d5.js",
"lineNumber":54,"columnNumber":20714}]},"timestamp":1470145104.94625,"executionContextId":1}}}
  (Session info: chrome=52.0.2743.82)
  (Driver info: chromedriver=2.22.397933 (1cab651507b88dec79b2b2a22d1943c01833cc1b),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 9 milliseconds
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 16:57:40'
System info: host: 'Cd390-B21RVS1', ip: '10.10.53.102', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_51'
*_\* Element info: {Using=xpath, value=//*[@id='menu_list']/li[2]/a}
Session ID: 8f4446bd7f9b1937154b62b30486e221
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{platform=XP, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=C:\Users\XXX\AppData\Local\Temp\scoped_dir5184_20574, chromedriverVersion=2.22.397933 (1cab651507b88dec79b2b2a22d1943c01833cc1b)}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=52.0.2743.82, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, hasTouchScreen=false, applicationCacheEnabled=false, takesScreenshot=true}]
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:363)
at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:500)
at org.openqa.selenium.By$ByXPath.findElement(By.java:361)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:355)
at TestReports.iWGO1.caseCompletion(iWGO1.java:585)
at TestReports.iWGO_FODesktop.onlineMode(iWGO_FODesktop.java:109)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:617)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
at org.testng.SuiteRunner.run(SuiteRunner.java:240)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
at org.testng.TestNG.run(TestNG.java:1057)
at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
# 
```

```
Default test
Tests run: 1, Failures: 1, Skips: 0
```
# 
# 

Default suite
# Total tests run: 1, Failures: 1, Skips: 0

[TestNG] Time taken by org.testng.reporters.JUnitReportReporter@5aa86d82: 30 ms
[TestNG] Time taken by org.testng.reporters.jq.Main@97919f6: 111 ms
[TestNG] Time taken by org.testng.reporters.XMLReporter@65e8f789: 13 ms
[TestNG] Time taken by org.testng.reporters.EmailableReporter2@55cdaad2: 79 ms
[TestNG] Time taken by [FailedReporter passed=0 failed=0 skipped=0]: 32 ms
[TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@15714c8d: 212 ms

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!
## Environment
- Appium version (or git revision) that exhibits the issue:
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium:
- Node.js version (unless using Appium.app|exe):
- Mobile platform/version under test:
- Real device or emulator/simulator:
- Appium CLI or Appium.app|exe:
## Details

Describe in more detail the problem you have been experiencing, if necessary.
## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!
## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
This looks more like internal chromedriver issue, which has nothing to do with Appium. I'd advice to forward it to Chromedriver bug tracker. Also, I suppose, they will need more detailed environment description to be able to help (OS type, window manager, etc.)
