### ISSUE TITLE
Unable to run test on Android Emulator.

### ISSUE THREAD

**Issue by macroking** [appium/appium#6731]
## The problem

Getting 'Unable to start a WebDriver session' error when running my protractor test in Android Emulator.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:Windows
* Node.js version (unless using Appium.app|exe):4.2.4
* Mobile platform/version under test:Android6.0
* Real device or emulator/simulator:Emulator
* Appium CLI or Appium.app|exe:Appium CLI

## Details

Test launches the default browser in the emulator and crashes.

## Link to Appium logs

https://gist.github.com/macroking/687e8741f55ebf6553d3cb8d176c9aec

## Code To Reproduce Issue [ Good To Have ]
Protractor.conf.js
`    exports.config = {
        seleniumAddress: 'http://localhost:4723/wd/hub',
        specs: ['qa/ui/specs/google-Spec.js'],
        capabilities: {
           'platformName': 'Android',
           'platformVersion': '6.0',
           'deviceName': 'device_name',
           'autoWebView': true,
           'appium-version': '1.5.3',
           'browserName': 'Browser'
       },

    baseUrl: 'http://localhost:8100',

    onPrepare: function () {
        var wd = require('wd'),
            protractor = require('protractor'),
            wdBridge = require('wd-bridge')(protractor, wd);
        wdBridge.initFromProtractor(exports.config);
    }
};`

**Comment by imurchie** [comment]
There is nothing in the logs that indicate any sort of error. A session is created, the async script timeout is set, and then the session is deleted.

**Comment by macroking** [comment]
This is what I see in the terminal after executing the command "protractor protractor.conf.js"

> [10:18:53] I/hosted - Using the selenium server at http://localhost:4723/wd/hub
[10:18:53] I/launcher - Running 1 instances of WebDriver
[10:18:56] E/runner - Unable to start a WebDriver session.
[10:19:02] E/launcher - Error: WebDriverError: Method has not yet been implemented
    at WebDriverError (C:\Users\user_name\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:27:10)
    at Object.checkLegacyResponse (C:\Users\user_name\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:639:15)
    at parseHttpResponse (C:\Users\user_name\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\http\index.js:538:13)
    at C:\Users\user_name\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\http\index.js:472:11
    at ManagedPromise.invokeCallback_ (C:\Users\user_name\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1379:14)
    at TaskQueue.execute_ (C:\Users\user_name\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2913:14)
    at TaskQueue.executeNext_ (C:\Users\user_name\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2896:21)
    at C:\Users\user_name\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2820:25
    at C:\Users\user_name\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:639:7
    at process._tickCallback (node.js:368:9)
From: Task: WebDriver.manage().timeouts().setScriptTimeout(11000)
    at WebDriver.schedule (C:\Users\user_name\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:377:17)
    at Timeouts.setScriptTimeout (C:\Users\user_name\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:1303:25)
    at Runner.createBrowser (C:\Users\user_name\AppData\Roaming\npm\node_modules\protractor\built\runner.js:206:40)
    at C:\Users\user_name\AppData\Roaming\npm\node_modules\protractor\built\runner.js:261:30
    at _fulfilled (C:\Users\user_name\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\user_name\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\user_name\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:796:13)
    at C:\Users\user_name\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:556:49
    at runSingle (C:\Users\user_name\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:137:13)
    at flush (C:\Users\user_name\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:125:13)
[10:19:02] E/launcher - Process exited with error code 100

**Comment by imurchie** [comment]
And that is corresponding to the server log from above? The Appium server is not responding with that error.

What is the command that is causing this?

**Comment by mykola-mokhnach** [comment]
@macroking It looks like _setScriptTimeout_ method call is not implemented there. What if you just comment out this call?

**Comment by macroking** [comment]
After spending too much time in debugging the issue, finally found that one of the windows registry keys had an invalid value. After I clear that up, the script started running fine in the android emulator.

This is the KEY - HKCU\Software\Microsoft\Command Processor\AutoRun
                 Value - (if %ANSICON_VER%==^%ANSICON_VER^% "C:\tools\ansi160\x64\ansicon" -p)

As @imurchie pointed out, appium logs doesn't provide any information about the error, when  I run appium from CLI.

However running the standalone Appium produced the following error message. Even though the error message doesn't clearly specify the error, I checked all my WINDOWS system environment variables and corrected the PATH "STILL DIDN'T GET MY CODE WORK".

Info: [debug] Error: Command failed: C:\windows\system32\cmd.exe /s /c "C:\Users\user_name\AppData\Local\Android\sdk1\platform-tools\adb.exe shell "getprop persist.sys.language""
> The system cannot find the path specified.
> 
>     at ChildProcess.exithandler (child_process.js:751:12)
>     at ChildProcess.emit (events.js:110:17)
>     at maybeClose (child_process.js:1016:16)
>     at Process.ChildProcess._handle.onexit (child_process.js:1088:5)
> info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Command failed: C:\\windows\\system32\\cmd.exe /s /c \"C:\\Users\\user_name\\AppData\\Local\\Android\\sdk1\\platform-tools\\adb.exe shell \"getprop persist.sys.language\"\"\nThe system cannot find the path specified.\r\n)","killed":false,"code":1,"signal":null,"cmd":"C:\\windows\\system32\\cmd.exe /s /c \"C:\\Users\\user_name\\AppData\\Local\\Android\\sdk1\\platform-tools\\adb.exe shell \"getprop persist.sys.language\"\"","origValue":"Command failed: C:\\windows\\system32\\cmd.exe /s /c \"C:\\Users\\user_name\\AppData\\Local\\Android\\sdk1\\platform-tools\\adb.exe shell \"getprop persist.sys.language\"\"\nThe system cannot find the path specified.\r\n"},"sessionId":null}
> info: <-- POST /wd/hub/session 500 203.327 ms - 762 


Finally, removed the value from  "HKCU\Software\Microsoft\Command Processor\AutoRun" registry key helped.
