### ISSUE TITLE
could not determine ios sdk version

### ISSUE THREAD

**Issue by imobarak** [appium/appium#6743]
## The problem

error: Could not determine iOS SDK version

info: [debug] Error: Command failed: /bin/sh -c xcrun --sdk iphonesimulator --show-sdk-version

```
at ChildProcess.exithandler (child_process.js:744:12)
at ChildProcess.emit (events.js:110:17)
at maybeClose (child_process.js:1008:16)
at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
```

info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Command failed: /bin/sh -c xcrun --sdk iphonesimulator --show-sdk-version\n)","cause":{"killed":true,"code":null,"signal":"SIGTERM","cmd":"/bin/sh -c xcrun --sdk iphonesimulator --show-sdk-version"},"isOperational":true,"killed":true,"code":null,"signal":"SIGTERM","cmd":"/bin/sh -c xcrun --sdk iphonesimulator --show-sdk-version","origValue":"Command failed: /bin/sh -c xcrun --sdk iphonesimulator --show-sdk-version\n"},"sessionId":null}
info: <-- POST /wd/hub/session 500 10039.177 ms - 525 

error: Failed to start an Appium session, err was: Error: Command failed: /bin/sh -c xcrun --sdk iphonesimulator --show-sdk-version
## Environment
- Appium version with issue: 1.4.13 and i updated to 1.5.3 to check if it is solved 
- Last Appium version that did not exhibit the issue (if applicable): NA
- Desktop OS/version used to run Appium: OS X el Capitan 10.11.5
- Node.js version (unless using Appium.app|exe): v0.12.0
- Mobile platform/version under test: ios 9.3
- Real device or emulator/simulator: simulator iphone5 9.3
- Appium CLI or Appium.app|exe:
## Details

I am trying to run my maven tests on a simulator and at times it wouldn't launch and give me this error i tried different solutions provided in previous answers like checking "use native instruments libarary" in the advanced ios tab, or check "use external nodejs binary" in developer settings, or resetting the simulator or restarting my machine and at times it works but this time i did all these and it still gives the same error
Can you please explain to me what is the reason for this error and what is the correct way to solve it?

**Comment by imurchie** [comment]
In a terminal window what happens when you run `xcrun --sdk iphonesimulator --show-sdk-version`?

**Comment by imobarak** [comment]
i get: 9.3

**Comment by joshrlesch** [comment]
Im getting this error quite a bit. For me, if I run that command in a terminal, it takes awhile to return the version but eventually does. If I run it a second time, it returns right away.

Is there a capability that we can pass to up that 3 sec timeout?

**Comment by imurchie** [comment]
There is not currently any way, no. I could bump it up a bit, and then put it on the roadmap to add a way to configure it, the implementation of which would take more time.

**Comment by imurchie** [comment]
I've started the process of making this configurable. See https://github.com/appium/appium/issues/6743

In the interim, this also extends the timeout to 15s, which hopefully alleviates some of the problem.

**Comment by joshrlesch** [comment]
Im not sure if there might be another issue here though, in the appium logs it doesn't look like its even trying to wait the full 3000ms, and it should retry 2 times correct? https://github.com/appium/appium-xcode/blob/288dca56b096817b8a176d70f8325b2fb868851b/lib/xcode.js#L13

```
2016-08-23 21:22:02:511 - [HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"http://tc-mac-03:5000/Hudl.app.zip","orientation":"PORTRAIT","newCommandTimeout":60,"platformVersion":"9.2","termTimeout":30000,"platformName":"iOS","fullReset":true,"launchTimeout":180000,"version":"9.2","deviceName":"iPhone 6","applicationName":"iPhone 6"}}
2016-08-23 21:22:02:511 - [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"http://tc-mac-03:5...
2016-08-23 21:22:02:513 - [Appium] Creating new IosDriver session
2016-08-23 21:22:02:513 - [Appium] Capabilities:
2016-08-23 21:22:02:516 - [Appium]   app: 'http://tc-mac-03:5000/Hudl.app.zip'
2016-08-23 21:22:02:516 - [Appium]   orientation: 'PORTRAIT'
2016-08-23 21:22:02:516 - [Appium]   newCommandTimeout: 60
2016-08-23 21:22:02:517 - [Appium]   platformVersion: '9.2'
2016-08-23 21:22:02:517 - [Appium]   termTimeout: 30000
2016-08-23 21:22:02:517 - [Appium]   platformName: 'iOS'
2016-08-23 21:22:02:518 - [Appium]   fullReset: true
2016-08-23 21:22:02:518 - [Appium]   launchTimeout: 180000
2016-08-23 21:22:02:518 - [Appium]   version: '9.2'
2016-08-23 21:22:02:519 - [Appium]   deviceName: 'iPhone 6'
2016-08-23 21:22:02:519 - [Appium]   applicationName: 'iPhone 6'
2016-08-23 21:22:02:522 - [BaseDriver] The following capabilities were provided, but are not recognized by appium: termTimeout, version, applicationName.
2016-08-23 21:22:02:523 - [BaseDriver] Session created with session id: a8aa9d79-066f-44c1-a26b-b93d33a666f6
2016-08-23 21:22:02:523 - [debug] [iOS] Not auto-detecting udid.
2016-08-23 21:22:02:524 - [BaseDriver] Using downloadable app 'http://tc-mac-03:5000/Hudl.app.zip'
2016-08-23 21:22:03:422 - [debug] [BaseDriver] http://tc-mac-03:5000/Hudl.app.zip downloaded to /var/folders/9_/d8gxsj9d54703r4_x5d0mqbc0000gn/T/2016723-22685-z92k0m/appium-app.zip
2016-08-23 21:22:03:423 - [BaseDriver] Downloaded app to '/var/folders/9_/d8gxsj9d54703r4_x5d0mqbc0000gn/T/2016723-22685-z92k0m/appium-app.zip'
2016-08-23 21:22:03:429 - [debug] [BaseDriver] Unzipping /var/folders/9_/d8gxsj9d54703r4_x5d0mqbc0000gn/T/2016723-22685-z92k0m/appium-app.zip
2016-08-23 21:22:03:429 - [debug] [BaseDriver] Testing zip archive: /var/folders/9_/d8gxsj9d54703r4_x5d0mqbc0000gn/T/2016723-22685-z92k0m/appium-app.zip
2016-08-23 21:22:05:250 - [HTTP] --> GET /wd/hub/status {}
2016-08-23 21:22:05:250 - [MJSONWP] Calling AppiumDriver.getStatus() with args: []
2016-08-23 21:22:05:847 - [BaseDriver] Unzipped local app to '/var/folders/9_/d8gxsj9d54703r4_x5d0mqbc0000gn/T/2016723-22685-z92k0m/Hudl.app'
2016-08-23 21:22:05:848 - [debug] [iOS] Removing any remaining instruments sockets
2016-08-23 21:22:05:849 - [debug] [iOS] Cleaned up instruments socket /var/folders/9_/d8gxsj9d54703r4_x5d0mqbc0000gn/T/instruments_sock
2016-08-23 21:22:05:850 - [debug] [iOS] Setting Xcode version
2016-08-23 21:22:05:851 - [debug] [iOS] Xcode version set to 7.3.1
2016-08-23 21:22:05:851 - [debug] [iOS] Setting iOS SDK Version
2016-08-23 21:22:05:852 - [iOS] Could not determine iOS SDK version
2016-08-23 21:22:05:853 - [MJSONWP] Encountered internal error running command: Error: Command 'xcrun --sdk iphonesimulator --show-sdk-version' timed out after 3000ms
    at Timeout._onTimeout (lib/teen_process.js:78:19)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```

**Comment by imurchie** [comment]
I don't think the number of retries would come out in the logs. Only the final failure will cause an error to be thrown.

**Comment by praveen-4705** [comment]
Got temporary solution - Updated Setting > Advanced > BackEnd Retries to 5 than its starts working

**Comment by keshavwy** [comment]
@imurchie I am facing this issue. Please find out the appium logs mentioned here:

[Appium] Welcome to Appium v1.7.1
[Appium] Non-default server args:
[Appium]   address: 127.0.0.1
[Appium]   noReset: true
[Appium] Deprecated server args:
[Appium]   --no-reset => --default-capabilities '{"noReset":true}'
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   noReset: true
[Appium] Appium REST http interface listener started on 127.0.0.1:4723
AppiumServer Started
log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/webyog/Documents/workspace/NewtonApp/src/test/resources/app/Newton.app","platformVersion":"10.3","appiumVersion":"1.6","automationName":"XCUITest","bundleId":"com.cloudmagic.mail","platformName":"iOS","udid":"f253d52aba24834b9c2795ea0a7e95476d521042","deviceName":"iPhone"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/webyog/Documents/workspace/NewtonApp/src/test/resources/app/Newton.app","platformVersion":"10.3","appiumVersion":"1.6","automationName":"XCUITest","bundleId":"com.cloudmagic.mail","platformName":"iOS","udid":"f253d52aba24834b9c2795ea0a7e95476d521042","deviceName":"iPhone"},null,null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1507904567032 (19:52:47 GMT+0530 (IST))
[Appium] Creating new XCUITestDriver (v2.51.1) session
[Appium] Capabilities:
[Appium]   app: '/Users/webyog/Documents/workspace/NewtonApp/src/test/resources/app/Newton.app'
[Appium]   platformVersion: '10.3'
[Appium]   appiumVersion: '1.6'
[Appium]   automationName: 'XCUITest'
[Appium]   bundleId: 'com.cloudmagic.mail'
[Appium]   platformName: 'iOS'
[Appium]   udid: 'f253d52aba24834b9c2795ea0a7e95476d521042'
[Appium]   deviceName: 'iPhone'
[Appium]   noReset: true
[BaseDriver] The following capabilities were provided, but are not recognized by appium: appiumVersion.
[BaseDriver] Session created with session id: 208739e8-626b-4930-a99d-d7743c7e0263
[Xcode] Finding XcodePath by symlink because Error: Command 'xcode-select' not found. Is it installed?
[debug] [XCUITest] Xcode version set to '9.0' 
[XCUITest] Error: Could not determine iOS SDK version: Command 'xcrun' not found. Is it installed?
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at getAndCheckIosSdkVersion$ (../../lib/utils.js:74:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: Could not determine iOS SDK version: Command 'xcrun' not found. Is it installed?
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at getAndCheckIosSdkVersion$ (../../lib/utils.js:74:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[XCUITest] Error: Could not determine iOS SDK version: Command 'xcrun' not found. Is it installed?
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at getAndCheckIosSdkVersion$ (../../lib/utils.js:74:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: Could not determine iOS SDK version: Command 'xcrun' not found. Is it installed?
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at getAndCheckIosSdkVersion$ (../../lib/utils.js:74:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[MJSONWP] Encountered internal error running command: Error: Could not determine iOS SDK version: Command 'xcrun' not found. Is it installed?
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at getAndCheckIosSdkVersion$ (../../lib/utils.js:74:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)

It works fine if I run the code separately. I am facing this issue if I runu it through testng.xml file.

**Comment by imurchie** [comment]
Do you have `xcrun` on your machine? Can you run `xcrun` on the command line?

**Comment by keshavwy** [comment]
Yes. See the logs below:

which xcrun
/usr/bin/xcrun
webyogs-MacBook-Pro-2:~ webyog$ xcrun
Usage: xcrun [options] <tool name> ... arguments ...

Find and execute the named command line tool from the active developer
directory.

The active developer directory can be set using `xcode-select`, or via the
DEVELOPER_DIR environment variable. See the xcrun and xcode-select manual
pages for more information.

Options:
  -h, --help                  show this help message and exit
  --version                   show the xcrun version
  -v, --verbose               show verbose logging output
  --sdk <sdk name>            find the tool for the given SDK name
  --toolchain <name>          find the tool for the given toolchain
  -l, --log                   show commands to be executed (with --run)
  -f, --find                  only find and print the tool path
  -r, --run                   find and execute the tool (the default behavior)
  -n, --no-cache              do not use the lookup cache
  -k, --kill-cache            invalidate all existing cache entries
  --show-sdk-path             show selected SDK install path
  --show-sdk-version          show selected SDK version
  --show-sdk-build-version    show selected SDK build version
  --show-sdk-platform-path    show selected SDK platform path
  --show-sdk-platform-version show selected SDK platform version

**Comment by imurchie** [comment]
Is the PATH available to whatever is running the server?

**Comment by keshavwy** [comment]
Sorry, I am not sure about the PATH. What exactly I need to do it here?

**Comment by imurchie** [comment]
Are you running in Eclipse or something?

**Comment by keshavwy** [comment]
Yes. I am running in eclipse only

**Comment by keshavwy** [comment]
Can you tell me for what I need to set a Path in eclipse?

**Comment by imurchie** [comment]
There may be other ways, but I found this: https://stackoverflow.com/questions/7048216/environment-variables-in-eclipse

I would ask on https://discuss.appium.io/, where you might find people who use Eclipse.

**Comment by keshavwy** [comment]
I know how to set up environment variables in eclipse, but I am not sure which one I need to add it as an environment variable in my case.

**Comment by imurchie** [comment]
The server is expecting to be able to run `xcrun`, and it does so by accessing it on the `PATH` environment variable. So I guess you need to put that in. I find it surprising that it doesn't do that automatically, but then I know nothing of Eclipse.

**Comment by keshavwy** [comment]
If possible can you ask someone? I am stuck on this issue for a long time. It will be helpful.

**Comment by imurchie** [comment]
As I suggested, try https://discuss.appium.io/. Alternatively, create an issue on the https://github.com/appium/java-client where they might have suggestions.

**Comment by samsonbarukula** [comment]
[XCUITest] Error: Could not determine iOS SDK version: Command 'xcrun --sdk iphonesimulator --show-sdk-version' timed out after 15000ms any help pls

**Comment by Kedar-27** [comment]
Try installing command line tools from https://developer.apple.com/download/more/ 
This solved my error

**Comment by reply2sagar** [comment]
Execute 2 commands 
sudo /usr/bin/xcode-select -switch /Applications/Xcode.app/Contents/Developer
xcrun --sdk iphonesimulator --show-sdk-version 

Second command should retun the version of SDK. Then restart appium. This solved my problem

**Comment by bokiperic** [comment]
I got this error while installing the iOS app on AWS Device Farm. Did anyone have the same issue there, or on some other device farm, and maybe know how to fix it?

**Comment by BoazWarshawsky** [comment]
@mykola-mokhnach I am getting this problem when running it in the elements inspector, what shall I do? I cannot run it with `appium --backend-retries 5`

**Comment by BoazWarshawsky** [comment]
The problem solved for me by doing these 2 commands:

`sudo /usr/bin/xcode-select -switch /Applications/Xcode.app/Contents/Developer`
`xcrun --sdk iphonesimulator --show-sdk-version`

Like mentioned above.
