### ISSUE TITLE
iOS 10 Beta not supported

### ISSUE THREAD

**Issue by JasonLunn** [appium/appium#6752]
## The problem

We're attempting to validate our project works on the iOS 10 Beta, but tests fail with a (malformed) error message that it is not supported yet. So, this issue is one part feature request - iOS 10 Beta support, and one part bug report - the error message:

```
Encountered internal error running command: Error: Xcode version [object Object] is not yet supported
```

looks like it was intended to give diagnostic feedback to the user about the specific version that is unsupported but it does not format the message properly, instead injecting the default String serialization of a JavaScript object.

## Environment

* OS X El Capitan 10.11.6
* npm 3.7.5
* appium 1.5.3

## Details

Stack trace:

```
[MJSONWP] Encountered internal error running command: Error: Xcode version [object Object] is not yet supported
[14:16:15]    at handleUnsupportedXcode (lib/simulator.js:15:11)
[14:16:15]    at getDeviceString$ (lib/simulator.js:44:3)
[14:16:15]    at tryCatch (/Users/teamcity/Applications/buildAgent/work/a7e03acd253501fe/iOS-Framework/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[14:16:15]    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/teamcity/Applications/buildAgent/work/a7e03acd253501fe/iOS-Framework/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[14:16:15]    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/teamcity/Applications/buildAgent/work/a7e03acd253501fe/iOS-Framework/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[14:16:15]    at GeneratorFunctionPrototype.invoke (/Users/teamcity/Applications/buildAgent/work/a7e03acd253501fe/iOS-Framework/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[14:16:15]    at process._tickCallback (internal/process/next_tick.js:103:7)
```

## Link to Appium logs

https://gist.github.com/JasonLunn/34be44b9789aa6e07f77aae129209fdb

## Code To Reproduce Issue [ Good To Have ]

I believe that this can be reproduced on any environment that has the Xcode 8 beta installed and configuring the test to use iOS 10

**Comment by imurchie** [comment]
The logging issue has been resolved.

As for iOS 10, Apple removed the automation Instrument from Xcode 8, so how Appium had been automating iOS no longer works. We are working on integrating XCUITest, which is Apple's replacement.

Yesterday the first beta was released (Appium 1.6.0-beta1) which has support for most of the functionality. We are still working on the rest, so not everything will work.

You can install it with `npm install -g appium@beta`, and get the new system by setting the `automationName` desired capability to `XCUITest`.

**Comment by imurchie** [comment]
The logging issue has been resolved.

As for iOS 10, Apple removed the automation Instrument from Xcode 8, so how Appium had been automating iOS no longer works. We are working on integrating XCUITest, which is Apple's replacement.

Yesterday the first beta was released (Appium 1.6.0-beta1) which has support for most of the functionality. We are still working on the rest, so not everything will work.

You can install it with `npm install -g appium@beta`, and get the new system by setting the `automationName` desired capability to `XCUITest`.

**Comment by JasonLunn** [comment]
Installed the beta, and updated my capabilities to specify the `automationName` value as described above. Error message has now changed:
```
[XCUITest] Error: Simulator files not fully created. Waiting a bit
[13:46:49]    at SimulatorXcode8.callee$2$0$ (lib/simulator-xcode-6.js:323:15)
[13:46:49]    at tryCatch (/Users/teamcity/Applications/buildAgent/work/iOS-Framework/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[13:46:49]    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/teamcity/Applications/buildAgent/work/iOS-Framework/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[13:46:49]    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/teamcity/Applications/buildAgent/work/iOS-Framework/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[13:46:49]    at GeneratorFunctionPrototype.invoke (/Users/teamcity/Applications/buildAgent/work/iOS-Framework/node_modules/babel-runtime/regenerator/runtime.js:136:37)
```

**Comment by imurchie** [comment]
I've updated the tool used to query the simulator. It should be better now.

**Comment by JasonLunn** [comment]
What do I need to update to get your improvement?

**Comment by imurchie** [comment]
Depends on how you are running Appium. From npm, you need to reinstall. From source, delete the `node_modules` directory and then run `npm install`.

**Comment by JasonLunn** [comment]
Could you link the commit in question? I don't see anything pushed to master for 6 days, and I experienced this issue 2 days ago.

**Comment by imurchie** [comment]
https://github.com/appium/appium-ios-simulator/commit/cdf9e953a42440372fb1eba0b59e2c5922520b7f

**Comment by JasonLunn** [comment]
Reinstalled, reran. Encountered a different failure mode:
```
2016-08-24 16:49:19:192 - error: [iOSSim] Error: Command 'osascript -e 'quit app "Simulator"'' exited with code 1
    at ChildProcess.<anonymous> (lib/teen_process.js:66:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
 { Error: Command 'osascript -e 'quit app "Simulator"'' exited with code 1
    at ChildProcess.<anonymous> (lib/teen_process.js:66:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
  stdout: '',
  stderr: '0:20: execution error: Simulator got an error: AppleEvent timed out. (-1712)\n',
  code: 1 }
```
See this [gist](https://gist.github.com/JasonLunn/3872e38473cadbb8a58b22566b7fbd0f) for the entire selenium log.

**Comment by imurchie** [comment]
Yes, the iOs 10 simulator freezes sometimes and can't be closed without a force stop. I have no solution to that.

**Comment by JasonLunn** [comment]
I would think that if the polite way via osascript times out, `kill -9 processid` would do the trick.

Leaving that aside for the moment, I reran my test after manually starting and stopping the simulator and managed passed that point and onto yet another failure mode:

```
2016-08-24 19:51:42:743 - error: [XCUITest] Error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1
    at ChildProcess.<anonymous> (lib/teen_process.js:66:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
 { Error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1
    at ChildProcess.<anonymous> (lib/teen_process.js:66:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
  stdout: '\u001b[1mFetching dependencies\nPlease make sure that you have Carthage installed (https://github.com/Carthage/Carthage)\nNote: We are expecting that carthage installed in /usr/local/bin/\n',
  stderr: '',
  code: 1 }
```

I don't have Carthage, and wasn't expecting to need it. Is this a new external dependency, or have I just been lucky enough never to step on this rake before?

**Comment by imurchie** [comment]
https://github.com/appium/appium/blob/master/docs/en/appium-setup/running-on-osx.md#testing-using-xcode-8-including-ios-10-with-xcuitest

**Comment by JasonLunn** [comment]
Thanks

**Comment by JasonLunn** [comment]
The app launched! Screenshots work!

When `textfield_exact` is called on the appium driver (appium_lib 8.0.0) inside a block passed to `wait`, I see:
```
Selenium::WebDriver::Error::TimeOutError: timed out after 10 seconds (underlying webdriver instance does not support javascript)
```

Is there something I have to do to request JavaScript in the capabilities? The [documentation](http://appium.io/slate/en/master/?ruby#appium-server-capabilities) doesn't hint that this is a supported configuration element.

**Comment by imurchie** [comment]
This is some weirdness the ruby client does.

Waiting on this: https://github.com/appium/appium-xcuitest-driver/pull/105

**Comment by JasonLunn** [comment]
Reran this morning after updating appium to get the latest merges to appium-xcuitest-driver. New failure mode:
```
2016-08-26 14:39:07:163 - info: [HTTP] <-- POST /wd/hub/session/500702a9-fcbd-459c-bc35-8f1328509214/element/3B797DB2-9A93-4A45-9B73-76EAEB08BA6E/click 200 800 ms - 118 
2016-08-26 14:39:07:174 - info: [HTTP] --> POST /wd/hub/session/500702a9-fcbd-459c-bc35-8f1328509214/execute {"script":"        (function() {\n        var opts = {\"typeArray\":[\"UIATextField\",\"UIASecureTextField\"],\"onlyVisible\":true,\"name\":{\"target\":\"Distributor ID\",\"substring\":false,\"insensitive\":false},\"label\":{\"target\":\"Distributor ID\",\"substring\":false,\"insensitive\":false},\"value\":{\"target\":\"Distributor ID\",\"substring\":false,\"insensitive\":false},\"onlyFirst\":true};\n        var result = false;\n\n        try {\n          result = $._elementOrElementsByType($.mainWindow(), opts);\n        } catch (e) {\n        }\n\n        return result;\n        })();\n","args":[]}
2016-08-26 14:39:07:174 - info: [MJSONWP] Calling AppiumDriver.execute() with args: ["        (function() {\n  ...
2016-08-26 14:39:07:175 - info: [debug] [XCUITest] Executing command 'execute'
2016-08-26 14:39:07:199 - error: [MJSONWP] Encountered internal error running command: TypeError: Cannot read property 'sendCommand' of undefined
    at XCUITestDriver.callee$0$0$ (lib/commands/execute.js:19:37)
    at tryCatch (/Users/teamcity/Applications/buildAgent/work/9fb8a55cab466928/iOS-Framework/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/teamcity/Applications/buildAgent/work/9fb8a55cab466928/iOS-Framework/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/teamcity/Applications/buildAgent/work/9fb8a55cab466928/iOS-Framework/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/Users/teamcity/Applications/buildAgent/work/9fb8a55cab466928/iOS-Framework/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/Users/teamcity/Applications/buildAgent/work/9fb8a55cab466928/iOS-Framework/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at Promise.exports.(anonymous function).target.(anonymous function).function.target.(anonymous function).F (/Users/teamcity/Applications/buildAgent/work/9fb8a55cab466928/iOS-Framework/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/Users/teamcity/Applications/buildAgent/work/9fb8a55cab466928/iOS-Framework/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/Users/teamcity/Applications/buildAgent/work/9fb8a55cab466928/iOS-Framework/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/Users/teamcity/Applications/buildAgent/work/9fb8a55cab466928/iOS-Framework/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at XCUITestDriver.callee$0$0 [as execute] (lib/commands/execute.js:10:48)
    at lib/basedriver/driver.js:174:24
    at tryCatcher (/Users/teamcity/Applications/buildAgent/work/9fb8a55cab466928/iOS-Framework/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/teamcity/Applications/buildAgent/work/9fb8a55cab466928/iOS-Framework/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Users/teamcity/Applications/buildAgent/work/9fb8a55cab466928/iOS-Framework/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromiseAtPostResolution (/Users/teamcity/Applications/buildAgent/work/9fb8a55cab466928/iOS-Framework/node_modules/bluebird/js/main/promise.js:245:10)
    at Async._drainQueue (/Users/teamcity/Applications/buildAgent/work/9fb8a55cab466928/iOS-Framework/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/Users/teamcity/Applications/buildAgent/work/9fb8a55cab466928/iOS-Framework/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/teamcity/Applications/buildAgent/work/9fb8a55cab466928/iOS-Framework/node_modules/bluebird/js/main/async.js:15:14)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
```

**Comment by imurchie** [comment]
Thanks. I'll fix this. But it still will not work, since there is no UI Automation context in which to run the JS you are sending in. All you will get is a NotImplementedError.

**Comment by JasonLunn** [comment]
We're not invoking any JavaScript explicitly - rather, we're invoking `textfield_exact` (from `appium_lib/ios/element/textfield.rb`). Is there an beta version of the `appium_lib` that we should be using instead?
