### ISSUE TITLE
TypeError: _loggerJs2.default.errorAndthrow is not a function

### ISSUE THREAD

**Issue by ghazel** [appium/appium#6773]
```
$ which appium
/home/ghazel/node-v6.4.0-linux-x86/bin/appium
$ appium --version
1.5.3

... while running tests ...

[MJSONWP] Encountered internal error running command: TypeError: _loggerJs2.default.errorAndthrow is not a function
    at ADB.callee$1$0$ (lib/tools/system-calls.js:434:11)
    at tryCatch (/home/ghazel/node-v6.4.0-linux-x86/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/home/ghazel/node-v6.4.0-linux-x86/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/home/ghazel/node-v6.4.0-linux-x86/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/home/ghazel/node-v6.4.0-linux-x86/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by imurchie** [comment]
Wow! A typo that [lasted a year and a half](https://github.com/appium/appium-adb/commit/85491ce24299b933f86908f588f9183743f2399c#diff-f49fd1c5ec5a147b7500fd6bf3ea46c7R389)!
