### ISSUE TITLE
Error: New app path Browser did not have extension .apk

### ISSUE THREAD

**Issue by jayantsarda** [appium/appium#6790]
## The problem
My tests were working perfectly fine on grid/device/emulator till 1.4.13. trying to upgrade Appium but no matter what browserName i pass I always get below error. 

Trying to run test on Android Browser with android version as 4.4.2 
Appium java-client version: 4.1.2
Appium app version: 1.5.3
using Android Emulator
OS: OSX 10.9.5

`DesiredCapabilities caps = DesiredCapabilities.android();
		    caps.setCapability("appiumVersion", "1.5.3");
		    caps.setCapability("deviceName","emulator-5554");
		    caps.setCapability("browserName", "");
		    caps.setCapability("platformVersion","4.4.2");
		    caps.setCapability("platformName","Android");
		    WebDriver driver = null;
		    driver = new RemoteWebDriver(new URL("http://localhost:4723/wd/hub"), caps);
		    driver.get("https://www.google.com/");`

Server Log:
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"Browser","appiumVersion":"1.5.3","platformVersion":"4.4.2","browserName":"","platformName":"Android","version":"","deviceName":"emulator-5554","platform":"ANDROID"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"Browser","appiumVe...
[Appium] Creating new SelendroidDriver session
[Appium] Capabilities:
[Appium]   app: 'Browser'
[Appium]   appiumVersion: '1.5.3'
[Appium]   platformVersion: '4.4.2'
[Appium]   browserName: ''
[Appium]   platformName: 'Android'
[Appium]   version: ''
[Appium]   deviceName: 'emulator-5554'
[Appium]   platform: 'ANDROID'
[Appium]   automationName: 'Selendroid'
[Appium]   noReset: true
[Appium]   dontStopAppOnReset: true
[BaseDriver] The following capabilities were provided, but are not recognized by appium: appiumVersion, version, platform.
[BaseDriver] Session created with session id: 093020f6-1b1b-40a2-991c-77444c4b4e4f
[BaseDriver] Using local app 'Browser'
[debug] [Selendroid] Deleting Selendroid session
[MJSONWP] Encountered internal error running command: Error: New app path Browser did not have extension .apk
    at Object.configureApp$ (lib/basedriver/helpers.js:41:11)
    at tryCatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at new Promise (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:197:7)
    at AsyncIterator.enqueue (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at Object.configureApp (lib/basedriver/helpers.js:22:21)
    at SelendroidDriver.createSession$ (lib/driver.js:85:42)
    at tryCatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[HTTP] <-- POST /wd/hub/session 500 62 ms - 185

**Comment by mykola-mokhnach** [comment]
Have you tried to set _browserName_ capability to _Browser_ or _Chrome_ like it is described here?
http://appium.io/slate/en/master/?java#python-example

**Comment by srigney** [comment]
I believe you need to add the 'app' capability and set the value to the path of your .apk file on your local system.

Excerpt from the appium md...
**app**	The absolute local path or remote http URL to an .ipa or .apk file, or a .zip containing one of these. Appium will attempt to install this app binary on the appropriate device first. Note that this capability is not required for Android if you specify appPackage and appActivity capabilities (see below). Incompatible with browserName.	/abs/path/to/my.apk or http://myapp.com/app.ipa

**Comment by jayantsarda** [comment]
@mykola-mokhnach Yes , I have tried browserName as 'Browser' still the same issue. I did not try chrome as i wish to run test on Android stock Browser
@srigney I am trying to run test on default browser, does it still need a apk to be specified, if yes then what should be the value for same on an android Emulator?

Thanks in advance for your inputs...

**Comment by mykola-mokhnach** [comment]
Probably this happens because you try to use Selendroid as main driver instead of the default one.
Anyway, try to set _app_ property to **null** explicitly and keep the _browserName_ set to **Browser**

**Comment by jayantsarda** [comment]
@mykola-mokhnach Thanks !!.. that worked ... it seems like we need to use default Automation type instead of selendroid.  Could be a bug with selendroid automation type ...
