### ISSUE TITLE
Instruments exited with code 253 with iOS 9.3.5

### ISSUE THREAD

**Issue by 03623170** [appium/appium#6791]
## The problem

After upgrading our iPhone 6s Plus to iOS 9.3.5, we cannot startup the device through appium v.1.5.3 anymore. It all works before with iOS 9.3.4
--> Instruments exited with code 253

## Link to Appium logs

[Instruments] Error launching instruments: Instruments crashed on startup

[iOSLog] [IOS_SYSLOG_ROW] Aug 31 10:39:36 iPhone notification_proxy[192] <Error>: 0x16e247000 -[MNPLockdownConnection receiveMessage]: lockdown_receive_message error!

[Instruments] Error: We exceeded the number of retries allowed for instruments to successfully start; failing launch
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at Instruments.launch$ (lib/instruments.js:220:15)
    at tryCatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
 [Error: We exceeded the number of retries allowed for instruments to successfully start; failing launch]
[MJSONWP] Encountered internal error running command: Error: We exceeded the number of retries allowed for instruments to successfully start; failing launch
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at Instruments.launch$ (lib/instruments.js:220:15)
    at tryCatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

[iOSLog] [IOS_SYSLOG_ROW] Aug 31 10:39:36 iPhone gputoolsd[222] <Notice>: schedule invalidation <DYTransport 0x12f50f5b0, error: lost transport connection (31)>
[iOSLog] [IOS_SYSLOG_ROW] Aug 31 10:39:36 iPhone DTServiceHub[200] <Warning>: Could not create service named com.apple.instruments.server.services.processcontrol.posixspawn
[HTTP] <-- POST /wd/hub/session 500 39894 ms - 232 
[iOSLog] [IOS_SYSLOG_ROW] Aug 31 10:39:36 iPhone gputoolsd[222] <Notice>: terminating daemon 0x12f50f290
[iOSLog] [IOS_SYSLOG_ROW] Aug 31 10:39:36 iPhone notification_proxy[192] <Error>: 0x16e087000 -[MNPLockdownConnection receiveMessage]: lockdown_receive_message error!

**Comment by mykola-mokhnach** [comment]
Might be similar to https://github.com/appium/appium/issues/6730

**Comment by skumar1122** [comment]
I have upgraded my iPhone 5s to 9.3.5 and it works fine now.
with appium 1.5.3v

**Comment by 03623170** [comment]
it is working for us now again. I killed all the instruments, reboot our system and iOS device and than it works. For my case we  can close this issue
