### ISSUE TITLE
Signing the WebDriver Agent

### ISSUE THREAD

**Issue by pavanbachu0604** [appium/appium#6846]
I am working on iOS 10 device, I have updated the Xcode version to XCode 8 and I have updated t0 appium v1.6 beta 1 and also the latest version appium-xcuittest-driver. When I am running the test case on real device I am getting this issue.

https://gist.github.com/pavanbachu0604/6eddaf82771794f0087e7dcf04a15d46

**Environment**
- Appium version : Appium 1.6 Beta 1
- Desktop OS/version used to run Appium: Mac 10.11.16
- Mobile platform/version under test: iOS 10 
- Real device or emulator/simulator: Real device
- Appium CLI or Appium.app|exe: CLI

**Capabilities that are set into code:** 
capabilities.setCapability("platformVersion", "10.0");
capabilities.setCapability("udid", "_UDID of device_");
capabilities.setCapability("deviceName", "iPad");
capabilities.setCapability("platform", "iOS");
capabilities.setCapability("automationName", "XCUITest");
 capabilities.setCapability("app", "_App path from local_");
driver.set(new IOSDriver(new URL("http://localhost:4723/wd/hub"),capabilities));

**Comment by skumar1122** [comment]
did you tried this - appium/appium-xcuitest-driver#106 ?

**Comment by 03623170** [comment]
I have the same problem:
`[XCUITest]      Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the project editor.
        Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.0'
** TEST FAILED **


The following build commands failed:
        Check dependencies
(1 failure)

[XCUITest] xcodebuild exited with code '65' and signal 'null'
[XCUITest] Error: xcodebuild failed with code 65
    at SubProcess.<anonymous> (lib/webdriveragent.js:236:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
 Error: xcodebuild failed with code 65
    at SubProcess.<anonymous> (lib/webdriveragent.js:236:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[XCUITest] Shutting down WebDriverAgent
[XCUITest] System log exited with code '0'
[debug] [XCUITest] Resetting simulator
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: xcodebuild failed with code 65
    at SubProcess.<anonymous> (lib/webdriveragent.js:236:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
`
I also did sign the WebDriverAgent.xcodeproj

**Comment by pavanbachu0604** [comment]
@skumar1122 : Well I have added the provisioning profile for the app file before execution.

**Comment by shay777** [comment]
any progress with this?
I have the exact same issue

**Comment by 03623170** [comment]
@shay777 nothing yet I guess

**Comment by pavanbachu0604** [comment]
@skumar1122  : After following the steps mentioned by you , 
I am getting the following errors : "_An unknown server-side error occurred while processing the command. Original error: Unable to find real device logging program 'deviceconsole'"_

I have tried clearing the deviceconsole logs from the Xcode still it did not work

**Comment by imurchie** [comment]
Since the normal `idevicesyslog` does not work for iOS 10 at the moment, you need to either have `deviceconsole` in your PATH, or specify its location using the `realDeviceLogger` capability.

See https://github.com/appium/appium-xcuitest-driver#usage

**Comment by pavanbachu0604** [comment]
@imurchie what do you mean by specifying the location ? What should I point to ?

**Comment by imurchie** [comment]
Wherever you have `deviceconsole` installed.

**Comment by pavanbachu0604** [comment]
@imurchie I have cloned the device console from the https://github.com/rpetrich/deviceconsole , Do i need to make any changes in Xcode proj of deviceconsole ?

**Comment by imurchie** [comment]
I have no idea. @yaphatak worked on this part of the system.

**Comment by pavanbachu0604** [comment]
@imurchie : I am getting this error when after the setting the path to realdevicelogger 

_"An unknown server-side error occurred while processing the command. Original error: xcodebuild failed with code 65"_

**Comment by yaphatak** [comment]
@pavanbachu0604 You can get it compiled via npm https://www.npmjs.com/package/deviceconsole

**Comment by dnphung** [comment]
@imurchie @yaphatak same as @pavanbachu0604 I received `[MJSONWP] Encountered internal error running command: Error: xcodebuild failed with code 65
    at SubProcess.<anonymous> (lib/webdriveragent.js:236:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
`

**Comment by imurchie** [comment]
I've just released `appium-xcuitest-driver@2.0.15` which includes the new desired capability `showXcodeLog` which will print out the xcode log within the appium server logs. This will print _a lot_, but might help point to where these errors are coming from.

https://github.com/appium/appium-xcuitest-driver#usage

**Comment by pavanbachu0604** [comment]
@imurchie @yaphatak  Do i need to install the Xcuit test after I clone the workspace ?! I have added the provisioning profile to web driver Xcode project .

Here is the appium https://gist.github.com/pavanbachu0604/5130386b056c865c567a7eb5618394fd

**Comment by yaphatak** [comment]
![screen shot 2016-09-20 at 12 28 20 pm](https://cloud.githubusercontent.com/assets/12143988/18685622/bf73cb26-7f2d-11e6-8760-f6b30d26e970.png)

You need to do that for these 2 targets

**Comment by pavanbachu0604** [comment]
I am just observing this in my Xcode project
[cid:7E1CDE2B-2103-4736-AA1E-4DBFDDDE6280]

**Comment by acdurai** [comment]
@imurchie 
I done the code signing ,it Installed the **Webdriver Agent Runner** successfully in device. But when I run the test It launching the WDA in device after that it launching the app.

**Comment by mallikarjunm034** [comment]
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:374:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:374:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.

**Comment by mallikarjunm034** [comment]
unable to run on iPhone 6s (version:10.3.1) Xcode 8.2.1 and IOS:10.11.6
getting below error . Please help me
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:374:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:374:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.

**Comment by jjacquet** [comment]
If its any consolation I was able to make some progress by signing `com.facebook.WebDriverAgentLib` with my development team, installed `mobiledevice` and executed `mobiledevice tunnel 8100 8100`. Then I ran the script from terminal `xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'platform=iOS,name=Automation' test` and it installed and almost ran. It made it to the phone but closed with this error 
```Testing failed:
	Test target WebDriverAgentRunner encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)
```

Its some progress...
