### ISSUE TITLE
 Could not initialize ios-deploy make sure it is installed and works on your system

### ISSUE THREAD

**Issue by Hellengo** [appium/appium#6880]
$sudo npm install --global --unsafe-perm ios-deploy
...
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil /Users/Hellengo/.npm-packages/lib/node_modules/.staging/ios-deploy-419d7fc2/build/Release/ios-deploy -o /Users/Hellengo/.npm-packages/lib/node_modules/.staging/ios-deploy-419d7fc2/build/Release/ios-deploy.dSYM

** BUILD SUCCEEDED **

/Users/Hellengo/.npm-packages/bin/ios-deploy -> /Users/Hellengo/.npm-packages/lib/node_modules/ios-deploy/build/Release/ios-deploy
/Users/Hellengo/.npm-packages/lib
└── ios-deploy@1.9.0

error log:
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not initialize ios-deploy make sure it is installed and works on your system
Log:
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"deviceName":"iPhone 6","...
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium] deviceName: 'iPhone 6'
[Appium] udid: '11ebe7ca5241c034fbe1845982da4fc79c68eb71'
[Appium] autoAcceptAlerts: true
[Appium] app: '/Users/Hellengo/Desktop/Test/vodka.ipa'
[Appium] platformVersion: '9.3'
[Appium] platformName: 'iOS'
[Appium] automationName: 'XCUITest'
[BaseDriver] Session created with session id: 341bc5e6-ac96-41de-98b4-7bf140991cd4
[debug] [XCUITest] Xcode version set to '8.0'
[debug] [XCUITest] iOS SDK Version set to '10.0'
[debug] [XCUITest] Available devices: 80d160000eeeb4b4f1d6523a4d4ab762ae3197e6, 11ebe7ca5241c034fbe1845982da4fc79c68eb71
[debug] [XCUITest] Creating iDevice object with udid 11ebe7ca5241c034fbe1845982da4fc79c68eb71
[XCUITest] Could not initialize ios-deploy make sure it is installed and works on your system
[XCUITest] Error: Could not initialize ios-deploy make sure it is installed and works on your system
at XCUITestDriver.getIDeviceObj$ (lib/driver.js:618:13)
at tryCatch (/Users/Hellengo/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
at GeneratorFunctionPrototype.invoke as _invoke
at GeneratorFunctionPrototype.prototype.(anonymous function) as throw
at GeneratorFunctionPrototype.invoke (/Users/Hellengo/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
Error: Could not initialize ios-deploy make sure it is installed and works on your system
at XCUITestDriver.getIDeviceObj$ (lib/driver.js:618:13)
at tryCatch (/Users/Hellengo/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
at GeneratorFunctionPrototype.invoke as _invoke
at GeneratorFunctionPrototype.prototype.(anonymous function) as throw
at GeneratorFunctionPrototype.invoke (/Users/Hellengo/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[MJSONWP] Encountered internal error running command: Error: Could not initialize ios-deploy make sure it is installed and works on your system
at XCUITestDriver.getIDeviceObj$ (lib/driver.js:618:13)
at tryCatch (/Users/Hellengo/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
at GeneratorFunctionPrototype.invoke as _invoke
at GeneratorFunctionPrototype.prototype.(anonymous function) as throw
at GeneratorFunctionPrototype.invoke (/Users/Hellengo/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)

**Comment by mykola-mokhnach** [comment]
Make sure that _ios-deploy_ command is available from the command line and also that it is accessible to the Appium service. This is the output on my local system:

```
$: which ios-deploy
/usr/local/bin/ios-deploy
```

**Comment by Hellengo** [comment]
ok, thanks
ln -fs /Users/Hellengo/.npm-packages/lib/node_modules/ios-deploy/build/Release/ios-deploy /usr/local/bin/ios-deploy

**Comment by vikramvi** [comment]
http://brewformulas.org/iosdeploy for mac
