### ISSUE TITLE
XCUITest:Cannot read property 'sessionId' of undefined using Appium 1.6.0-beta1

### ISSUE THREAD

**Issue by mayureshshirodkar** [appium/appium#6893]
## The problem
I have been experiencing this issue for Appium 1.6 beta where the App launches fine on the real iOS device,WebdriverAgent installs fine but once app gets interactable the sessionID undefined error is thrown.

## Environment
* Appium version:appium@1.6.0-beta1
* Last Appium version that did not exhibit the issue (if applicable):Appium 1.5.3
* Desktop OS/version used to run Appium: Mac OS X El Capitan 10.11.6
* Node.js version (unless using Appium.app|exe): v5.5.0
* Mobile platform/version under test: iPhone 5S 0S-9.3.5
* Real device or emulator/simulator:Real Device
* Java client: v4.1.2

## Details

```
[XCUITest] ProxyRequestError: Could not proxy command to remote server. Original error: Cannot read property 'sessionId' of undefined
    at JWProxy.proxy$ (lib/jsonwp-proxy/proxy.js:117:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:108:47)
    at /usr/local/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:119:28
    at flush (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickCallback (node.js:381:13)
 **{ [ProxyRequestError: Could not proxy command to remote server. Original error: Cannot read property 'sessionId' of undefined] jsonwp: undefined }**
[XCUITest] Shutting down WebDriverAgent
[XCUITest] System log exited with code 'null'
[XCUITest] xcodebuild exited with code 'null' and signal 'SIGTERM'
[debug] [XCUITest] Resetting simulator
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: Cannot read property 'sessionId' of undefined
    at JWProxy.proxy$ (lib/jsonwp-proxy/proxy.js:117:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:108:47)
    at /usr/local/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:119:28
    at flush (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickCallback (node.js:381:13)
[HTTP] <-- POST /wd/hub/session 500 79499 ms - 240 
```

## Link to Appium logs
Full log: 
[ErrorLog.txt](https://github.com/appium/appium/files/491759/ErrorLog.txt)

## Code To Reproduce Issue 

Fails at:
```java
Appium driver = new IOSDriver(new URL(Base.readInternalHash("url_ios")), iosNative());

Capabilities:
		iOSCapabilities.setCapability("deviceName","iPhone" );
		iOSCapabilities.setCapability("platformVersion","9.3.5" );
		iOSCapabilities.setCapability("automationName", "XCUITest");
		iOSCapabilities.setCapability("realDeviceLogger", "/usr/local/lib/node_modules/deviceconsole/deviceconsole");
		iOSCapabilities.setCapability("app", System.getProperty("user.dir") + Base.readInternalHash("ios_app"));
		iOSCapabilities.setCapability("bundleID", Base.readInternalHash("bundle_id"));
		iOSCapabilities.setCapability("newCommandTimeout", 500);
		iOSCapabilities.setCapability("autoWebview", true);
		//iOSCapabilities.setCapability("fullReset", true);
		iOSCapabilities.setCapability("autoAcceptAlerts", true);
		iOSCapabilities.setCapability("udid", <udid>);
```

**Comment by imurchie** [comment]
WDA is sending back an empty response, for some reason. I will try to reproduce and see if I can figure something out.

Thanks for posting this.

**Comment by mayureshshirodkar** [comment]
@imurchie I installed Appium 1.6.0 beta2 and it worked for me , for the same configuration. But there seems to be some issue on beta2 as it is very flaky.

**Comment by jkiyomu** [comment]
I am having the same issue but using the python client. Are we suppose to import something else or would something like:
`
from appium import webdriver
self.driver = webdriver.Remote('http://127.0.0.1:4723/wd/hub', desired_caps)`
Work from the python client?

**Comment by aaronflud** [comment]
I am having a similar issue with the java client using Appium 1.6.0 beta 2.  I had everything working and  but now anytime the WebDriverAgent launches I get the following error and then the simulator closes instantly: 

```
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bu...
[XCUITest] SyntaxError: Unexpected token < in JSON at position 0
at Object.parse (native)
at new ProxyRequestError (lib/mjsonwp/errors.js:322:26)
at JWProxy.proxy$ (lib/jsonwp-proxy/proxy.js:117:13)
at tryCatch (/Users/User/Desktop/appiumdev2/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
at GeneratorFunctionPrototype.invoke as _invoke
at GeneratorFunctionPrototype.prototype.(anonymous function) as throw
at GeneratorFunctionPrototype.invoke (/Users/User/Desktop/appiumdev2/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
SyntaxError: Unexpected token < in JSON at position 0
at Object.parse (native)
at new ProxyRequestError (lib/mjsonwp/errors.js:322:26)
at JWProxy.proxy$ (lib/jsonwp-proxy/proxy.js:117:13)
at tryCatch (/Users/User/Desktop/appiumdev2/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
at GeneratorFunctionPrototype.invoke as _invoke
at GeneratorFunctionPrototype.prototype.(anonymous function) as throw
at GeneratorFunctionPrototype.invoke (/Users/User/Desktop/appiumdev2/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[XCUITest] Shutting down WebDriverAgent
[XCUITest] Simulator log exited with code 'null'
[XCUITest] xcodebuild exited with code 'null' and signal 'SIGTERM'
```

If this should be a new issue let me know.

**Comment by imurchie** [comment]
I ran into this problem and I _think_ I fixed it. Re-install the beta and try it out. XCUITestDriver should be version 2.0.21.

**Comment by jkiyomu** [comment]
That worked perfectly. Now I have to figure out how to get the elements to test. Is there any docs for getting the xpaths for ios 10 devices?

**Comment by imurchie** [comment]
Not as of yet. You get the source for the view and see what the elements are now called. :(
