### ISSUE TITLE
Having issue to run the SafariLancher in my real device

### ISSUE THREAD

**Issue by mashek347** [appium/appium#6915]
```
Last login: Thu Sep 29 15:34:47 on ttys000
GNWRICA2080432:~ 502000533$ cd /usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/build/SafariLauncher/
GNWRICA2080432:SafariLauncher 502000533$ appium &
[1] 2791
GNWRICA2080432:SafariLauncher 502000533$ [Appium] Welcome to Appium v1.5.0-beta16 (REV 9378e46ffc2c17df4efc535744279ebfa28bcf30)
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session 
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"io.appium.SafariLauncher","safariIgnoreFraudWarning":true,"platformVersion":"9.3","safariAllowPopups":false,"automationName":"Appium","pla...
[Appium] Creating new IosDriver session
[Appium] Capabilities:
[Appium]   app: 'io.appium.SafariLauncher'
[Appium]   safariIgnoreFraudWarning: true
[Appium]   platformVersion: '9.3'
[Appium]   safariAllowPopups: false
[Appium]   automationName: 'Appium'
[Appium]   platformName: 'iOS'
[Appium]   udid: 'a132919a4b4c2c393ea15f7860fe8ae1e3d6f1e9'
[Appium]   deviceName: 'iPhone 6'
[BaseDriver] Session created with session id: 3a933bef-7e97-4bef-bb41-af9c1f4911a3
[debug] [iOS] Not auto-detecting udid.
[debug] [iOS] App is an iOS bundle, will attempt to run as pre-existing
[debug] [iOS] Removing any remaining instruments sockets
[debug] [iOS] Cleaned up instruments socket /var/folders/z3/tkbh3cns4fd4fyd6xsdgk1bh68_4ff/T/instruments_sock
[debug] [iOS] No language specified. Using default strings
/usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/build/SafariLauncher/io.appium.SafariLauncher/Localizable.strings
[debug] [iOS] Strings file not found. Looking in 'en.lproj' directory
[iOS] Could not file localizable strings file 'Localizable.strings'!
[debug] [iOS] Creating instruments
[debug] [UIAuto] Preparing bootstrap code
[debug] [UIAuto] Dynamic bootstrap dir: /Users/502000533/Library/Application Support/appium/bootstrap
[debug] [UIAuto] Dynamic env: {"nodePath":"/usr/local/bin/node","commandProxyClientPath":"/usr/local/lib/node_modules/appium/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js","instrumentsSock":"/var/folders/z3/tkbh3cns4fd4fyd6xsdgk1bh68_4ff/T/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"grouped"}
[debug] [UIAuto] Dynamic bootstrap code: // This file is automatically generated...o not manually modify!
[debug] [UIAuto] Dynamic bootstrap path: /Users/502000533/Library/Application Support/appium/bootstrap/bootstrap-1301822d1a41d8e9.js
[debug] [UIAuto] Reusing dynamic bootstrap: /Users/502000533/Library/Application Support/appium/bootstrap/bootstrap-1301822d1a41d8e9.js
[debug] [iOS] Running ios real device reset flow
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[debug] [iOS] Creating iDevice object with udid a132919a4b4c2c393ea15f7860fe8ae1e3d6f1e9
[debug] [iOS] App is not installed. Will try to install the app.
[MJSONWP] Encountered internal error running command: Error: Installing io.appium.SafariLauncher failed
    at /usr/local/lib/node_modules/appium/node_modules/node-idevice/main.js:159:6
    at ChildProcess.exithandler (child_process.js:204:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
[HTTP] <-- POST /wd/hub/session 500 3543 ms - 179 
[HTTP] --> POST /wd/hub/session 
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"io.appium.SafariLauncher","safariIgnoreFraudWarning":true,"platformVersion":"9.3","safariAllowPopups":false,"automationName":"Appium","pla...
[Appium] Creating new IosDriver session
[Appium] Capabilities:
[Appium]   app: 'io.appium.SafariLauncher'
[Appium]   safariIgnoreFraudWarning: true
[Appium]   platformVersion: '9.3'
[Appium]   safariAllowPopups: false
[Appium]   automationName: 'Appium'
[Appium]   platformName: 'iOS'
[Appium]   udid: 'a132919a4b4c2c393ea15f7860fe8ae1e3d6f1e9'
[Appium]   deviceName: 'iPhone 6'
[BaseDriver] Session created with session id: 3f75cb90-7296-451e-8137-05913aa23ba6
[debug] [iOS] Not auto-detecting udid.
[debug] [iOS] App is an iOS bundle, will attempt to run as pre-existing
[debug] [iOS] Removing any remaining instruments sockets
[debug] [iOS] Cleaned up instruments socket /var/folders/z3/tkbh3cns4fd4fyd6xsdgk1bh68_4ff/T/instruments_sock
[debug] [iOS] No language specified. Using default strings
/usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/build/SafariLauncher/io.appium.SafariLauncher/Localizable.strings
[debug] [iOS] Strings file not found. Looking in 'en.lproj' directory
[iOS] Could not file localizable strings file 'Localizable.strings'!
[debug] [iOS] Creating instruments
[debug] [UIAuto] Preparing bootstrap code
[debug] [UIAuto] Dynamic bootstrap dir: /Users/502000533/Library/Application Support/appium/bootstrap
[debug] [UIAuto] Dynamic env: {"nodePath":"/usr/local/bin/node","commandProxyClientPath":"/usr/local/lib/node_modules/appium/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js","instrumentsSock":"/var/folders/z3/tkbh3cns4fd4fyd6xsdgk1bh68_4ff/T/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"grouped"}
[debug] [UIAuto] Dynamic bootstrap code: // This file is automatically generated...o not manually modify!
[debug] [UIAuto] Dynamic bootstrap path: /Users/502000533/Library/Application Support/appium/bootstrap/bootstrap-1301822d1a41d8e9.js
[debug] [UIAuto] Reusing dynamic bootstrap: /Users/502000533/Library/Application Support/appium/bootstrap/bootstrap-1301822d1a41d8e9.js
[debug] [iOS] Running ios real device reset flow
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[debug] [iOS] Creating iDevice object with udid a132919a4b4c2c393ea15f7860fe8ae1e3d6f1e9
[debug] [iOS] App is not installed. Will try to install the app.
[MJSONWP] Encountered internal error running command: Error: Installing io.appium.SafariLauncher failed
    at /usr/local/lib/node_modules/appium/node_modules/node-idevice/main.js:159:6
    at ChildProcess.exithandler (child_process.js:204:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:477:12)
[HTTP] <-- POST /wd/hub/session 500 3439 ms - 179 
[HTTP] --> POST /wd/hub/session 
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"io.appium.SafariLauncher","safariIgnoreFraudWarning":true,"platformVersion":"9.3","safariAllowPopups":false,"automationName":"Appium","pla...
[Appium] Creating new IosDriver session
[Appium] Capabilities:
[Appium]   app: 'io.appium.SafariLauncher'
[Appium]   safariIgnoreFraudWarning: true
[Appium]   platformVersion: '9.3'
[Appium]   safariAllowPopups: false
[Appium]   automationName: 'Appium'
[Appium]   platformName: 'iOS'
[Appium]   udid: 'a132919a4b4c2c393ea15f7860fe8ae1e3d6f1e9'
[Appium]   deviceName: 'iPhone 6'
[BaseDriver] Session created with session id: 4ad4da4f-20a0-4d95-bb21-409cdd30bddb
[debug] [iOS] Not auto-detecting udid.
[debug] [iOS] App is an iOS bundle, will attempt to run as pre-existing
[debug] [iOS] Removing any remaining instruments sockets
[debug] [iOS] Cleaned up instruments socket /var/folders/z3/tkbh3cns4fd4fyd6xsdgk1bh68_4ff/T/instruments_sock
[debug] [iOS] No language specified. Using default strings
/usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/build/SafariLauncher/io.appium.SafariLauncher/Localizable.strings
[debug] [iOS] Strings file not found. Looking in 'en.lproj' directory
[iOS] Could not file localizable strings file 'Localizable.strings'!
[debug] [iOS] Creating instruments
[debug] [UIAuto] Preparing bootstrap code
[debug] [UIAuto] Dynamic bootstrap dir: /Users/502000533/Library/Application Support/appium/bootstrap
[debug] [UIAuto] Dynamic env: {"nodePath":"/usr/local/bin/node","commandProxyClientPath":"/usr/local/lib/node_modules/appium/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js","instrumentsSock":"/var/folders/z3/tkbh3cns4fd4fyd6xsdgk1bh68_4ff/T/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"grouped"}
[debug] [UIAuto] Dynamic bootstrap code: // This file is automatically generated...o not manually modify!
[debug] [UIAuto] Dynamic bootstrap path: /Users/502000533/Library/Application Support/appium/bootstrap/bootstrap-1301822d1a41d8e9.js
[debug] [UIAuto] Reusing dynamic bootstrap: /Users/502000533/Library/Application Support/appium/bootstrap/bootstrap-1301822d1a41d8e9.js
[debug] [iOS] Running ios real device reset flow
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[debug] [iOS] Creating iDevice object with udid a132919a4b4c2c393ea15f7860fe8ae1e3d6f1e9
[debug] [iOS] App is not installed. Will try to install the app.
[MJSONWP] Encountered internal error running command: Error: Installing io.appium.SafariLauncher failed
    at /usr/local/lib/node_modules/appium/node_modules/node-idevice/main.js:159:6
    at ChildProcess.exithandler (child_process.js:204:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:477:12)
[HTTP] <-- POST /wd/hub/session 500 3396 ms - 179 
[HTTP] --> POST /wd/hub/session 
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"io.appium.SafariLauncher","safariIgnoreFraudWarning":true,"platformVersion":"9.3","safariAllowPopups":false,"automationName":"Appium","pla...
[Appium] Creating new IosDriver session
[Appium] Capabilities:
[Appium]   app: 'io.appium.SafariLauncher'
[Appium]   safariIgnoreFraudWarning: true
[Appium]   platformVersion: '9.3'
[Appium]   safariAllowPopups: false
[Appium]   automationName: 'Appium'
[Appium]   platformName: 'iOS'
[Appium]   udid: 'a132919a4b4c2c393ea15f7860fe8ae1e3d6f1e9'
[Appium]   deviceName: 'iPhone 6'
[BaseDriver] Session created with session id: 8b275f19-8688-424b-8f0c-65713b6fccde
[debug] [iOS] Not auto-detecting udid.
[debug] [iOS] App is an iOS bundle, will attempt to run as pre-existing
[debug] [iOS] Removing any remaining instruments sockets
[debug] [iOS] Cleaned up instruments socket /var/folders/z3/tkbh3cns4fd4fyd6xsdgk1bh68_4ff/T/instruments_sock
[debug] [iOS] No language specified. Using default strings
/usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/build/SafariLauncher/io.appium.SafariLauncher/Localizable.strings
[debug] [iOS] Strings file not found. Looking in 'en.lproj' directory
[iOS] Could not file localizable strings file 'Localizable.strings'!
[debug] [iOS] Creating instruments
[debug] [UIAuto] Preparing bootstrap code
[debug] [UIAuto] Dynamic bootstrap dir: /Users/502000533/Library/Application Support/appium/bootstrap
[debug] [UIAuto] Dynamic env: {"nodePath":"/usr/local/bin/node","commandProxyClientPath":"/usr/local/lib/node_modules/appium/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js","instrumentsSock":"/var/folders/z3/tkbh3cns4fd4fyd6xsdgk1bh68_4ff/T/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"grouped"}
[debug] [UIAuto] Dynamic bootstrap code: // This file is automatically generated...o not manually modify!
[debug] [UIAuto] Dynamic bootstrap path: /Users/502000533/Library/Application Support/appium/bootstrap/bootstrap-1301822d1a41d8e9.js
[debug] [UIAuto] Reusing dynamic bootstrap: /Users/502000533/Library/Application Support/appium/bootstrap/bootstrap-1301822d1a41d8e9.js
[debug] [iOS] Running ios real device reset flow
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[debug] [iOS] Creating iDevice object with udid a132919a4b4c2c393ea15f7860fe8ae1e3d6f1e9
[debug] [iOS] App is not installed. Will try to install the app.
[MJSONWP] Encountered internal error running command: Error: Installing io.appium.SafariLauncher failed
    at /usr/local/lib/node_modules/appium/node_modules/node-idevice/main.js:159:6
    at ChildProcess.exithandler (child_process.js:204:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:477:12)
[HTTP] <-- POST /wd/hub/session 500 3372 ms - 179 
```

some can help me up for Safari launcher in appium?

**Comment by imurchie** [comment]
First, can you update Appium? You are running an _old_ beta version. 

Then you should search through the issues. This has been discussed.
