### ISSUE TITLE
[iOS] Could not initialize ideviceinstaller; make sure it is installed and works on your system

### ISSUE THREAD

**Issue by albka1986** [appium/appium#6924]
MY ENVIRONMENT:
- OS X EL CAPITAN
- XCODE (Version 8.0)
- SIMULATOR (iPhone 5, iOS 9.3)
- APPIUM version 1.5.3 (Ara)

I can't run ipa file. Appium threw the error. Please help me.

```
[iOS] Could not initialize ideviceinstaller; make sure it is installed and works on your system

[MJSONWP] Encountered internal error running command: Error: Could not initialize ideviceinstaller; make sure it is installed and works on your system
    at IosDriver.getIDeviceObj (lib/driver.js:380:15)
    at IosDriver.get (lib/driver.js:950:49)
    at IosDriver.installToRealDevice$ (lib/driver.js:335:21)
    at tryCatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at new Promise (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:197:7)
    at AsyncIterator.enqueue (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at IosDriver.installToRealDevice (lib/driver.js:351:16)
    at IosDriver.startRealDevice$ (lib/driver.js:309:16)
    at tryCatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```

**Comment by mykola-mokhnach** [comment]
Try to upgrade idevicelibrary to the most recent version;
```
brew uninstall libimobiledevice && brew install --HEAD libimobiledevice
```

Build it from source if this does not help. See the thread https://github.com/libimobiledevice/libimobiledevice/issues/346#issuecomment-246592802 for more details

**Comment by albka1986** [comment]
@mykola-mokhnach 
how to check version of libimobiledevice?

**Comment by mykola-mokhnach** [comment]
```
brew info libimobiledevice
```

**Comment by albka1986** [comment]
@mykola-mokhnach 
unfortunately it doesn't help me

**Comment by mykola-mokhnach** [comment]
@albka1986 Xcode8+ is not supported by Appium older than 1.6. You need to upgrade your automation framework to use Appium 1.6 beta if you want it to work as expected.

**Comment by albka1986** [comment]
@mykola-mokhnach  Do you have any instruction to install Appium 1.6 beta version? I could not find it in the internet (
I have downloaded "appium-1.6.0-beta1", but I don't know how to install it.

**Comment by mykola-mokhnach** [comment]
@albka1986 check the thread https://github.com/appium/appium/issues/6597. There's a comment from **briananderson1222**, which describes all the things needed to be done.

**Comment by albka1986** [comment]
@mykola-mokhnach 

I've have a new mistake:

```
[debug] [iOS] Creating iDevice object with udid 0dbccb9b899550db539a6be4533955a29880133d

[debug] [iOS] App is not installed. Will try to install.

[MJSONWP] Encountered internal error running command: Error: Installing /var/folders/n2/hkgn0n19359fqhtjd0xmpl540000gp/T/201694-3273-1s170mp/Payload/GlobBar.app failed
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/node-idevice/main.js:159:6
    at ChildProcess.exithandler (child_process.js:193:7)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:475:12)

[HTTP] <-- POST /wd/hub/session 500 1977 ms - 243  
```
Do you know what is wrong?

**Comment by mykola-mokhnach** [comment]
Try to install your app manually using ideviceinstaller or ios-deploy tool (depending on what is set in capabilities), enable debug output there and check the result.

**Comment by narendra-chandratre** [comment]
@mykola-mokhnach Yes, Its working well after installing ideviceinstaller and ios-deploy. Thanks
