### ISSUE TITLE
iOS 10 XCUITest - WebDriverAgent Server URL Null

### ISSUE THREAD

**Issue by codywsears** [appium/appium#6930]
When trying to run tests with the appium-xcuitest-driver in appium 1.6.0-beta2 the WebDriverAgent is trying to run its server with a null URL. Can anyone help? @imurchie

See below logs: 

[XCUITest] Detected that WebDriverAgent is running at url 'http://(null):8100'
[XCUITest] Error: Unable to detect url from WebDriverAgent: http://(null):8100. Is the device on the same network as the server?
    at startDetector (lib/webdriveragent.js:323:31)
    at handleOutput (lib/teen_process.js:143:32)
    at Stream.<anonymous> (lib/teen_process.js:179:9)
    at Stream.stream.write (/usr/local/lib/node_modules/appium/node_modules/through/index.js:26:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)
 Error: Unable to detect url from WebDriverAgent: http://(null):8100. Is the device on the same network as the server?
    at startDetector (lib/webdriveragent.js:323:31)
    at handleOutput (lib/teen_process.js:143:32)
    at Stream.<anonymous> (lib/teen_process.js:179:9)
    at Stream.stream.write (/usr/local/lib/node_modules/appium/node_modules/through/index.js:26:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)
[XCUITest] Unable to start WebDriverAgent: Error: Unable to detect url from WebDriverAgent: http://(null):8100. Is the device on the same network as the server?
[XCUITest] Unable to start WebDriverAgent: Error: Unable to detect url from WebDriverAgent: http://(null):8100. Is the device on the same network as the server?
[XCUITest] Shutting down WebDriverAgent
[XCUITest] System log exited with code '0'
[XCUITest] xcodebuild exited with code 'null' and signal 'SIGTERM'
[debug] [XCUITest] Resetting simulator
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: undefined

It seems to be a problem with WebDriverAgent, but does anyone have a solution?

**Comment by imurchie** [comment]
Is the device on the same network as the server?

**Comment by codywsears** [comment]
@imurchie that worked thanks
