### ISSUE TITLE
appium 1.6-beta2 /java client  4.1.2/ iOS 10 emulator     driver.launchApp()  / driver.closeApp()  issues

### ISSUE THREAD

**Issue by bearxc** [appium/appium#6936]
In our test execution , we close app at the end of each test  and then launch app again at the beginning  of  new test , make sure app in a clean state , it works fine on 1.5.3   while  closeApp()    and   launchApp()  seems broken on  appium1.6-beta2 .

1)  closeApp()

It does not close app  and just shut down WDA , if not set noReset to true , simulator would be closed also .

[debug] [XCUITest] Executing command 'closeApp'
[XCUITest] Shutting down WebDriverAgent
[XCUITest] Simulator log exited with code 'null'
[XCUITest] xcodebuild exited with code 'null' and signal 'SIGTERM'
[debug] [iOSLog] Stopping iOS log capture
[iOS] Successfully closed the [undefined] app.
[MJSONWP] Responding to client with driver.closeApp() result: null

2. launchApp() 
 
after closeApp() with noReset to true,  and try to launch again , there is exception

[debug] [XCUITest] Executing command 'launchApp'
[debug] [XCUITest] Xcode version set to '8.0'
[debug] [XCUITest] iOS SDK Version set to '10.0'
[XCUITest] Simluator udid not provided, using desired caps to create a new simulator
[XCUITest] No platformVersion specified. Using latest version '10.0'
[iOSSim] Constructing iOS simulator for Xcode version 8.0 with udid 'B94851FF-6798-47A6-BDC5-E31E970D5D84'
[XCUITest] Created simulator with udid 'B94851FF-6798-47A6-BDC5-E31E970D5D84'.
[XCUITest] Determining device to run tests on: udid: 'B94851FF-6798-47A6-BDC5-E31E970D5D84', real device: false
[debug] [ios-app-utils] Getting bundle ID from app
[iOS] Something went wrong while launching the [undefined] app.
[MJSONWP] Encountered internal error running command: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.posix.resolve (path.js:426:5)
    at extractPlist$ (lib/extract.js:10:24)
    at tryCatch (/Users/jenkins/appium_master/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/jenkins/appium_master/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/jenkins/appium_master/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/Users/jenkins/appium_master/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/Users/jenkins/appium_master/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at new Promise (/Users/jenkins/appium_master/appium/node_modules/core-js/library/modules/es6.promise.js:201:7)
    at AsyncIterator.enqueue (/Users/jenkins/appium_master/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/Users/jenkins/appium_master/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/Users/jenkins/appium_master/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at extractPlist (lib/extract.js:10:16)
    at extractPlistEntry$ (lib/extract.js:20:31)
    at tryCatch (/Users/jenkins/appium_master/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/jenkins/appium_master/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/jenkins/appium_master/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/Users/jenkins/appium_master/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/Users/jenkins/appium_master/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at new Promise (/Users/jenkins/appium_master/appium/node_modules/core-js/library/modules/es6.promise.js:201:7)

**Comment by imurchie** [comment]
Can you try the latest code? It appears to be working for my test cases.

**Comment by bearxc** [comment]
yea, it works fine on latest code 1.6-beta3
