### ISSUE TITLE
[v1.6.0-beta3] 'Could not proxy command to remote server' after restarting driver in iOS

### ISSUE THREAD

**Issue by JaniJegoroff** [appium/appium#6937]
## The problem

I have scenarios where I need to reset app state and restart driver. This has been working perfectly so far with `1.4.16`, `1.6.0-beta1`, `1.6.0-beta2` but since `1.6.0-beta3` I see errors:

`An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8100 (Selenium::WebDriver::Error::UnknownError)`

## Environment

* Appium version (or git revision) that exhibits the issue: v1.6.0-beta3
* Last Appium version that did not exhibit the issue (if applicable): v1.6.0-beta2
* Desktop OS/version used to run Appium: Mac OS Sierra
* Node.js version (unless using Appium.app|exe): v5.1.1
* Mobile platform/version under test: iPhone 7 / iOS 10.0
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: CLI

## Details

```
Scenario: no transactions                  # features/my_app.feature:15
  An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8100 (Selenium::WebDriver::Error::UnknownError)
  ./features/support/utils/environment_utils.rb:45:in `reset_app'
  ./features/support/hooks.rb:14:in `Before'
    Given server returns no transactions     # features/step_definitions/my_app_steps.rb:5
    And I am on my nectar screen             # features/step_definitions/common_steps.rb:1
    Then I should see I have no transactions # features/step_definitions/my_app_steps.rb:57
      A session is either terminated or not started (Selenium::WebDriver::Error::NoSuchDriverError)
      ./features/support/utils/screenshot_utils.rb:16:in `capture'
      ./features/support/hooks.rb:19:in `After'
```

## Link to Appium logs

https://gist.github.com/JaniJegoroff/f24181be33f2439762b853dcbe05bc3e

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by JaniJegoroff** [comment]
@imurchie Not able to reproduce anymore after latest fixes for iOS.
