### ISSUE TITLE
Possible solution for error 65 (missing signature) for XCUITest @ real device

### ISSUE THREAD

**Issue by mykola-mokhnach** [appium/appium#6955]
Currently many people complain they cannot automate tests for real iOS devices using XCUITest driver because of this annoying error 65. The error means, that driver source cannot be signed properly and thus cannot be installed on real device even if the same action works as expected from Xcode on the same machine.
I spent some time investigating the problem and it looks like the main source of it is Accessibility restrictions in Mac OS, because I see "No user interaction is allowed" error in Xcode logs. This happens because the private key, which the tool tries to use, is stored in the system keychain and the parent process has no access to it.  
And here is possible solution:

For now all that Appium does is just execution of _xcodebuild_ with necessary arguments using Subprocess helper class. My proposal is to change it the way that if we run not on a Simulator then a shell script will be executed instead of xcodebuild, which includes the following commands:

```bash
KEYCHAIN_PATH=<path_to_custom_keychain>
KEYCHAIN_PASSWORD=<keychain_access_password>
security -v list-keychains -s "$KEYCHAIN_PATH"
security -v unlock-keychain -p $KEYCHAIN_PASSWORD "$KEYCHAIN_PATH"
security set-keychain-settings -t 3600 -l "$KEYCHAIN_PATH"
xcodebuild <build_args>
``` 

The custom keychain should be prepared manually using the following commands:
```bash
security create-keychain -p [keychain_password] MyKeychain.keychain
security import MyPrivateKey.p12 -t agg -k MyKeychain.keychain -P [p12_Password] -A
```

_MyPrivateKey.p12_ is my private development key exported from the system keychain.

I have tested it via SSH console (because it's not reproducible if one just executes xcodebuild via local Terminal) and it worked. Please think about including that into the next Appium build.

Information source: http://stackoverflow.com/questions/16550594/jenkins-xcode-build-works-codesign-fails

@imurchie FYI

**Comment by imurchie** [comment]
Interesting. Thanks for this! I will look into it.

**Comment by imurchie** [comment]
I'm having a bear of a time getting the `xcodebuild` process to run the `test` action through a shell script.

**Comment by imurchie** [comment]
First pass at this: https://github.com/appium/appium-xcuitest-driver/pull/217

**Comment by chanugithub** [comment]
@mykola-mokhnach @imurchie i am using XCUITest] I am trying to pass these capabilities (key chain path and keychainpassword) but got this error, any idea?    

[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: "Command 'security -v unlock-keychain -p v /Users/Chanakya/Desktop/Certificates.p12' exited with code 49". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
    at XCUITestDriver.quitAndUninstall$ (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:395:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 Error: Unable to launch WebDriverAgent because of xcodebuild failure: "Command 'security -v unlock-keychain -p v /Users/Chanakya/Desktop/Certificates.p12' exited with code 49". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
    at XCUITestDriver.quitAndUninstall$ (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:395:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[debug] [XCUITest] 'pgrep -nif xcodebuild.*18e20052fc6d9a7676a519e63cbbcb62fe818fb8' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] Cannot find xcodebuild's process id, so unable to retrieve DerivedData folder path
[XCUITest] No WebDriverAgent derived data available, so unable to clear system files
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: "Command 'security -v unlock-keychain -p v /Users/Chanakya/Desktop/Certificates.p12' exited with code 49". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
    at XCUITestDriver.quitAndUninstall$ (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:395:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[HTTP] <-- POST /wd/hub/session 500 17848 ms - 543

**Comment by imurchie** [comment]
What happens if you manually run the command `security -v unlock-keychain -p v /Users/Chanakya/Desktop/Certificates.p12`?

**Comment by chanugithub** [comment]
I got the below error

unlock-keychain "-p" "v" "/Users/Chanakya/Desktop/Certificates.p12"
security: SecKeychainUnlock /Users/Chanakya/Desktop/Certificates.p12: The specified keychain is not a valid keychain file.

**Comment by chanugithub** [comment]
@imurchie @mykola-mokhnach Finally i was able to find the solution, it was actually Apple certificates in 'key chain access' which now i set to 'system default' and previously it was in 'Always trust' mode, If anyone had valid code sign dev ids but get messed up with keychains then this is the core solution

**Comment by SoundaryaBhavanam** [comment]
@mykola-mokhnach I tried this configuration, but still facing same code sign issue. Before i was able to proceed at-least on devices.
https://github.com/appium/appium/issues/12137

**Comment by SoundaryaBhavanam** [comment]
when i do test though terminal  with the below command everything is going though 
xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=UDID' test 

but still though jenkins not able to run more than 2 devices

**Comment by pacchan** [comment]
@mykola-mokhnach 
When I run the command it returns:
security: Error reading infile MyPrivateKey.p12: No such file or directory

Can you pls advise
