### ISSUE TITLE
Ran tests on a real device and got [XCUITest] Error checking install status: spawn EACCES

### ISSUE THREAD

**Issue by xshuRoadie** [appium/appium#6968]
iOS 10.0.2 (real device) / XCode 8

When running Appium 1.6 beta 3 I got the following error trace. Anyone has a clue? Thanks!
```

[XCUITest] Setting up real device
[debug] [XCUITest] Error checking install status: spawn EACCES
[debug] [XCUITest] App is not installed. Will try to install.
[debug] [XCUITest] Error : spawn EACCES
[XCUITest] Error: could not install app spawn EACCES
    at IOSDeploy.install$ (lib/ios-deploy.js:37:13)
    at tryCatch (/Users/someone/someone/src/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/someone/someone/src/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/someone/someone/src/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/someone/someone/src/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: could not install app spawn EACCES
    at IOSDeploy.install$ (lib/ios-deploy.js:37:13)
    at tryCatch (/Users/someone/someone/src/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/someone/someone/src/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/someone/someone/src/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/someone/someone/src/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[debug] [XCUITest] Running ios real device reset flow
[debug] [XCUITest] Resetting simulator
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: could not install app spawn EACCES
    at IOSDeploy.install$ (lib/ios-deploy.js:37:13)
    at tryCatch (/Users/someone/someone/src/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/someone/someone/src/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/someone/someone/src/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/someone/someone/src/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 1501 ms - 171 


```

**Comment by imurchie** [comment]
10.2 (which is beta) has not been tested. So it could be anything.

**Comment by mykola-mokhnach** [comment]
@xshuRoadie You can try to investigate the problem yourself. Just install you app to the real device manually using the following command line:

```bash
ios-deploy --verbose --id <your_device_uuid>  --uninstall --bundle <path_to_your_app>
```

and check possible errors in the output.

**Comment by dumplincat** [comment]
@imurchie Can we use appium1.6.0 to test on iOS 9.0/iOS9.3 with xcode 7.3.1?

**Comment by imurchie** [comment]
@dumplincat That depends. Appium's XCUITest support only works for iOS 9.3 and above, so if you are using that you can test iOS 9.3 with Xcode 7.3.1. You can test both iOS 9.0 and 9.3, using Xcode 7.3.1, if you use the old ios-driver (by specifying `platformName = 'ios'` and no `automationName`). This behaviour will be the same as in previous versions of Appium.

**Comment by xshuRoadie** [comment]
I tried different things. Also made sure that the latest appium code was pulled. Now the error in the appium log is slightly different. In the meantime on the device I saw the empty WebDriver icon .... It launched once with a black screen and then crashed. 

[XCUITest] Unable to start WebDriverAgent: Error: spawn EACCES
[XCUITest] Unable to start WebDriverAgent: Error: spawn EACCES
[debug] [XCUITest] Running ios real device reset flow
[debug] [XCUITest] Resetting simulator
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: undefined
[HTTP] <-- POST /wd/hub/session 500 584 ms - 188 

Attached are the screenshot for the empty WebDriver icon, the full appium log as well as the full xcodebuild log: 
[appium_log.pdf](https://github.com/appium/appium/files/527547/appium_log.pdf)
[xcodebuild_log.pdf](https://github.com/appium/appium/files/527560/xcodebuild_log.pdf)
![empty_webdriver_icon](https://cloud.githubusercontent.com/assets/9876675/19355881/eb6fd026-9139-11e6-83b7-c3303bf9b404.jpg)

I also tried ios-deploy which pushed the same ipa to the device successfully. 

Any idea to help me move forward would be great!

**Comment by imurchie** [comment]
@xshuRoadie Are you using the `realDeviceLogger` capability? What is the path sent in?

**Comment by xshuRoadie** [comment]
@imurchie Yes. I am using that capability. Below are the settings for the test device:

IPHONE_6Plus_iOS10={
        'deviceName': 'QA 6-Plus',
        'platformName': 'iOS',
        'platformVersion': '10.0.2',
        'udid': '{xxxx}', 
        'autoAcceptAlerts': 'true',
        'newCommandTimeout': 240,
        'automationName': 'XCUITest',
        'realDeviceLogger':'/Users/someone/.node/lib/node_modules/deviceconsole',
        'xcodeConfigFile': '/Users/someone/someone/src/myconfig.xcconfig'
    }

**Comment by imurchie** [comment]
Change 

```
'realDeviceLogger':'/Users/someone/.node/lib/node_modules/deviceconsole',
```

to

```
'realDeviceLogger':'/Users/someone/.node/lib/node_modules/deviceconsole/deviceconsole',
```

**Comment by xshuRoadie** [comment]
@imurchie That did get rid of "Error: spawn EACCES". Now a different error appears: Timeout exception when "[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading..."

[appium_log.pdf](https://github.com/appium/appium/files/527748/appium_log.pdf)
[xcodebuild_log.pdf](https://github.com/appium/appium/files/527747/xcodebuild_log.pdf)

**Comment by imurchie** [comment]
Can you post the logs as [gists](https://gist.github.com)?

**Comment by xshuRoadie** [comment]
Sure. https://gist.github.com/xshuRoadie/b591b2407e5af035d983d88ace4e3bd5   Thank you.

**Comment by imurchie** [comment]
I don't see any error there. The test runs. The element you are looking for is not found.

**Comment by xshuRoadie** [comment]
@imurchie Is it possible to share with you a quicktime video to show what happened? The reason why the elements are not found is because WebDriverAgent is not installing the app. At least that is what I am seeing on the device . An empty WebDriverAgent icon (same as that in the screenshot I posted earlier) showed up first, launched once and then crashed.

**Comment by imurchie** [comment]
It should launch and go into the background, then launch the app under test.

Can you move your app from `bundleId` to `app` in your desired capabilities?

**Comment by xshuRoadie** [comment]
That worked like a magic! Thanks a lot @imurchie !

**Comment by imurchie** [comment]
Yay! Glad it worked out.
