### ISSUE TITLE
[Appium 1.6.0-beta3] Original error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1 

### ISSUE THREAD

**Issue by tobecrazy** [appium/appium#6980]
## The problem

Get an error when try to execute test case for iOS
An unknown server-side error occurred while processing the command. Original error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1 (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 60.36 seconds
## Environment
- Appium version (or git revision) that exhibits the issue:1.6.0-beta3/java-client 4.12
- Last Appium version that did not exhibit the issue (if applicable):1.5.3
- Desktop OS/version used to run Appium:MAC OS
- Node.js version (unless using Appium.app|exe): 6.2.0
- Mobile platform/version under test:iOS 10.0
- Real device or emulator/simulator:emulator
- Appium CLI or Appium.app|exe:1.5.3
## Details

Describe in more detail the problem you have been experiencing, if necessary.
## Link to Appium logs

An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=163):
[Uploading log.txt…]()

see log.txt
## Code To Reproduce Issue [ Good To Have ]

```
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "XCUITest");
        capabilities.setCapability("platformName", "iOS");
        capabilities.setCapability("platformVersion", "10.0");
        capabilities.setCapability("deviceName", "iPhone 5s");
        // if no need install don't add this
        if (isInstall) {
            File classpathRoot = new File(System.getProperty("user.dir"));
            File appDir = new File(classpathRoot, "apps");
            File app = new File(appDir, "TestApp.ipa");
            System.out.println("---->" + app.getAbsolutePath());
            capabilities.setCapability("app", app.getAbsolutePath());
        }

        // support Chinese
        capabilities.setCapability("unicodeKeyboard", "True");
        capabilities.setCapability("resetKeyboard", "True");

        driver = new IOSDriver(new URL(URL), capabilities);
```

**Comment by tobecrazy** [comment]
[Appium] Welcome to Appium v1.6.0-beta3 (REV 12aad5c65fee39c5f044e39ca1efcbed58aebd39)
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Volumes/Transcend/Document/workspace/appiumDemo/apps/TestApp.ipa","platformVersion":"10.0","automationName":"XCUITest","unicodeKeyboard":"True","platformName":"iOS","deviceName":"iPhone 5s","resetKeyboard":"True"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Volumes/Transcend...
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   app: '/Volumes/Transcend/Document/workspace/appiumDemo/apps/TestApp.ipa'
[Appium]   platformVersion: '10.0'
[Appium]   automationName: 'XCUITest'
[Appium]   unicodeKeyboard: 'True'
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'iPhone 5s'
[Appium]   resetKeyboard: 'True'
[debug] [XCUITest] XCUITestDriver version: 2.0.25
[BaseDriver] The following capabilities were provided, but are not recognized by appium: unicodeKeyboard, resetKeyboard.
[BaseDriver] Session created with session id: 5a835154-ef4b-448d-820e-7dd05ee2d960
[debug] [XCUITest] Xcode version set to '8.0'
[debug] [XCUITest] iOS SDK Version set to '10.0'
[iOSSim] Constructing iOS simulator for Xcode version 8.0 with udid '1AA9F15F-3BBF-4D42-9FF9-F4678406418A'
[XCUITest] Determining device to run tests on: udid: '1AA9F15F-3BBF-4D42-9FF9-F4678406418A', real device: false
[BaseDriver] Using local app '/Volumes/Transcend/Document/workspace/appiumDemo/apps/TestApp.ipa'
[debug] [BaseDriver] Copying local zip to tmp dir
[debug] [BaseDriver] Unzipping /tmp/2016910-4141-gai0mp.fzo4o8yqfr/appium-app.zip
[debug] [BaseDriver] Testing zip archive: /tmp/2016910-4141-gai0mp.fzo4o8yqfr/appium-app.zip
[debug] [BaseDriver] Got a relaxed match for app in zip, be careful for app match errors
[BaseDriver] Unzipped local app to '/tmp/2016910-4141-gai0mp.fzo4o8yqfr/Payload/TestApp.app'
[debug] [XCUITest] Checking whether app is actually present
[debug] [ios-app-utils] Getting bundle ID from app
[debug] [iOSLog] Starting iOS 10.0 simulator log capture
[debug] [iOSLog] System log path: /Users/young/Library/Logs/CoreSimulator/1AA9F15F-3BBF-4D42-9FF9-F4678406418A/system.log
[XCUITest] Setting up simulator
[debug] [iOS] No reason to set locale
[debug] [iOS] No iOS / app preferences to set
[XCUITest] Simulator with udid '1AA9F15F-3BBF-4D42-9FF9-F4678406418A' not booted. Booting up now
[debug] [iOSSim] Killing all iOS Simulators
[iOSSim] Starting simulator with command: open /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID 1AA9F15F-3BBF-4D42-9FF9-F4678406418A
[iOSSim] Tailing simulator logs until we encounter the string "SMS Plugin initialized"
[iOSSim] We will time out after 60000ms
[debug] [iOSSim] Simulator startup timed out. Continuing anyway.
[debug] [iOSSim] Waiting an extra 10000ms for the simulator to really finish booting
[debug] [iOSSim] Done waiting extra time for simulator
[iOSSim] Simulator booted in 70279ms
[debug] [XCUITest] Installing app '/tmp/2016910-4141-gai0mp.fzo4o8yqfr/Payload/TestApp.app' on device
[simctl] Error: simctl error running 'install': An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=163):
Invalid device state
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at simCommand$ (lib/simctl.js:22:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: simctl error running 'install': An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=163):
Invalid device state
    a[debug] [XCUITest] Running iOS simulator reset flow
[debug] [XCUITest] Shutting down simulator
[debug] [iOSSim] Killing all iOS Simulators
t Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at simCommand$ (lib/simctl.js:22:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[XCUITest] Error: simctl error running 'install': An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=163):
Invalid device state
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at simCommand$ (lib/simctl.js:22:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: simctl error running 'install': An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=163):
Invalid device state
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at simCommand$ (lib/simctl.js:22:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[debug] [XCUITest] Cleaning simulator state.
[debug] [iOSSim] Cleaning app data files for 'TestApp.app', 'io.appium.TestApp'
[iOSSim] Attempted to get an app path from a fresh simulator quickly launching the sim to populate its directories
[debug] [iOSSim] Attempting to launch and quit the simulator, to create directory structure
[debug] [iOSSim] Will launch with Safari? false
[iOSSim] Starting simulator with command: open /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID 1AA9F15F-3BBF-4D42-9FF9-F4678406418A
[iOSSim] Tailing simulator logs until we encounter the string "SMS Plugin initialized"
[iOSSim] We will time out after 60000ms
[debug] [iOSSim] Simulator startup timed out. Continuing anyway.
[debug] [iOSSim] Waiting an extra 10000ms for the simulator to really finish booting
[debug] [iOSSim] Done waiting extra time for simulator
[iOSSim] Simulator booted in 70191ms
[debug] [iOSSim] Simulator files not fully created. Waiting a bit
[debug] [iOSSim] Simulator files not fully created. Waiting a bit
[debug] [iOSSim] Simulator files not fully created. Waiting a bit
[debug] [iOSSim] Simulator files not fully created. Waiting a bit
[debug] [iOSSim] Simulator files not fully created. Waiting a bit
[debug] [iOSSim] Simulator files not fully created. Waiting a bit
[debug] [iOSSim] Simulator files not fully created. Waiting a bit
[debug] [iOSSim] Simulator files not fully created. Waiting a bit
[debug] [iOSSim] Simulator files not fully created. Waiting a bit
[debug] [iOSSim] Simulator files not fully created. Waiting a bit
[debug] [iOSSim] Simulator files not fully created. Waiting a bit
[debug] [iOSSim] Simulator files not fully created. Waiting a bit
[debug] [iOSSim] Simulator files not fully created. Waiting a bit
[debug] [iOSSim] Simulator files not fully created. Waiting a bit
[debug] [iOSSim] Simulator files not fully created. Waiting a bit
[debug] [iOSSim] Simulator files not fully created. Waiting a bit
[debug] [iOSSim] Simulator files not fully created. Waiting a bit
[debug] [iOSSim] Simulator files not fully created. Waiting a bit
[debug] [iOSSim] Simulator files not fully created. Waiting a bit
[debug] [iOSSim] Simulator files not fully created. Waiting a bit
[XCUITest] Error: Simulator files not fully created. Waiting a bit
    at SimulatorXcode8.callee$2$0$ (lib/simulator-xcode-6.js:326:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: Simulator files not fully created. Waiting a bit
    at SimulatorXcode8.callee$2$0$ (lib/simulator-xcode-6.js:326:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[XCUITest] Could not reset simulator. Leaving as is.
[debug] [XCUITest] Resetting simulator
[debug] [XCUITest] Shutting down simulator
[debug] [iOSSim] Killing all iOS Simulators
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: simctl error running 'install': An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=163):
Invalid device state
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at simCommand$ (lib/simctl.js:22:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 150076 ms - 291

**Comment by imurchie** [comment]
These logs don't seem to correspond with the original problem.

Can you try running `open /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID 1AA9F15F-3BBF-4D42-9FF9-F4678406418A`? The simulator does not seem to be starting up for some reason.

**Comment by mykola-mokhnach** [comment]
@tobecrazy What output do you get in Terminal if you start iOS Simulator and invoke the following command?

```bash
xcrun simctl install booted <path_to_your_app>
```

**Comment by tobecrazy** [comment]
@mykola-mokhnach 
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.

**Comment by tobecrazy** [comment]
Hi @imurchie ,
I think you mean: 
open Simulator.app --args -CurrentDeviceUDID 1AA9F15F-3BBF-4D42-9FF9-F4678406418A
the Simulator is good.

**Comment by mykola-mokhnach** [comment]
@tobecrazy I see there is "Invalid device state" error in logs (btw, simctl does not support installing packages in .ipa format, only unpacked .app is supported, but this does not really matter now). Try to delete and recreate your Simulator device for "iPhone 5s" from Xcode (Window->Devices->Simulators). This might help to resolve the issue.

**Comment by imurchie** [comment]
@tobecrazy What about the command that I posted. That is what Appium is running to start the simulator, not `Simulator.app` without the full path.

**Comment by vighneshpai-yml** [comment]
I'm facing this issue.

**Comment by ManojKarthick1992** [comment]
Even I was facing this issue ,unable to install the app through appium or install command.but I was able to install the app by drag and drop it in simulator.

@tobecrazy,@vighneshpai-yml,whether the issue resolved for you guys. Need help in advance.

**Comment by imurchie** [comment]
This issue is over a year old. There is little that is going on here that still goes on in Appium. Please start a new issue with all the details that are asked for on the template, so that someone can try to help.
