### ISSUE TITLE
Appium Error Help, ioi

### ISSUE THREAD

**Issue by SubinLee** [appium/appium#6990]
Good morning.
Appium a novice user.
Error You Nago. Help .
Sorry awkward English. Which it is being created as translator.
Please help the following Error. Please.

Xcode 8 
iPhone 5 / iOS 9.1
Mac OS Sierra 10.12 
real device

# LOG

```
Launching Appium with command: '/Applications/Appium.app/Contents/Resources/node/bin/node' appium/build/lib/main.js --address "127.0.0.1" --debug-log-spacing --platform-version "9.1" --platform-name "iOS" --app "/Users/dev/Desktop/Qpost 2016-10-12 09-58-30/Qpost.ipa" --udid "73e931ec4a6c380dedadee6cc67af590ee93adc8" --full-reset --show-ios-log --device-name "iPhone 5"

[Appium] Welcome to Appium v1.5.3

[Appium] Non-default server args:

[Appium]   address: '127.0.0.1'

[Appium]   debugLogSpacing: true
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '9.1'

[Appium]   deviceName: 'iPhone 5'
[Appium]   app: '/Users/dev/Desktop/Qpost 2016-10-12 09-58-30/Qpost.ipa'
[Appium]   udid: '73e931ec4a6c380dedadee6cc67af590ee93adc8'
[Appium]   fullReset: true
[Appium]   showIOSLog: true
[Appium] Deprecated server args:
[Appium]   --platform-name => --default-capabilities '{"platformName":"iOS"}'

[Appium]   --platform-version => --default-capabilities '{"platformVersion":"9.1"}'
[Appium]   --device-name => --default-capabilities '{"deviceName":"iPhone 5"}'
[Appium]   --app => --default-capabilities '{"app":"/Users/dev/Desktop/Qpost 2016-10-12 09-58-30/Qpost.ipa"}'
[Appium]   -U,--udid => --default-capabilities '{"udid":"73e931ec4a6c380dedadee6cc67af590ee93adc8"}'
[Appium]   --full-reset => --default-capabilities '{"fullReset":true}'
[Appium]   --show-ios-log => --default-capabilities '{"showIOSLog":true}'

[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '9.1'

[Appium]   deviceName: 'iPhone 5'
[Appium]   app: '/Users/dev/Desktop/Qpost 2016-10-12 09-58-30/Qpost.ipa'
[Appium]   udid: '73e931ec4a6c380dedadee6cc67af590ee93adc8'
[Appium]   fullReset: true
[Appium]   showIOSLog: true

[Appium] Appium REST http interface listener started on 127.0.0.1:4723

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[HTTP] <-- GET /wd/hub/status 200 25 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[HTTP] <-- GET /wd/hub/status 200 13 ms - 83 

[HTTP] --> GET /wd/hub/sessions {}
[MJSONWP] Calling AppiumDriver.getSessions() with args: []
[MJSONWP] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 3 ms - 40 

[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"iOS","newCommandTimeout":"7200","app":"/Users/dev/Desktop/Qpost 2016-10-12 09-58-30/Qpost.ipa","platformVersion":"9.1","udid":"73e931ec4a6c380dedadee6cc67af590ee93adc8","deviceName":"iPhone 5","automationName":"Appium"}}

[MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"iOS","new...

[Appium] Creating new IosDriver session

[Appium] Capabilities:

[Appium]   platformName: 'iOS'

[Appium]   newCommandTimeout: '7200'
[Appium]   app: '/Users/dev/Desktop/Qpost 2016-10-12 09-58-30/Qpost.ipa'
[Appium]   platformVersion: '9.1'

[Appium]   udid: '73e931ec4a6c380dedadee6cc67af590ee93adc8'
[Appium]   deviceName: 'iPhone 5'
[Appium]   automationName: 'Appium'
[Appium]   fullReset: true

[Appium]   showIOSLog: true

[BaseDriver] Capability 'newCommandTimeout' changed from string ('7200') to integer (7200). This may cause unexpected behavior

[BaseDriver] Session created with session id: c8a2d148-a7a9-477d-a235-3748a6621a82
[debug] [iOS] Not auto-detecting udid.
[BaseDriver] Using local app '/Users/dev/Desktop/Qpost 2016-10-12 09-58-30/Qpost.ipa'
[debug] [BaseDriver] Copying local zip to tmp dir

[debug] [BaseDriver] Unzipping /var/folders/bm/mn11kb9j3y16yq7g39hgy89r0000gn/T/2016912-34759-1720wja/appium-app.zip

[debug] [BaseDriver] Testing zip archive: /var/folders/bm/mn11kb9j3y16yq7g39hgy89r0000gn/T/2016912-34759-1720wja/appium-app.zip

[BaseDriver] Unzipped local app to '/var/folders/bm/mn11kb9j3y16yq7g39hgy89r0000gn/T/2016912-34759-1720wja/Payload/Qpost.app'

[debug] [iOS] Removing any remaining instruments sockets

[debug] [iOS] Cleaned up instruments socket /var/folders/bm/mn11kb9j3y16yq7g39hgy89r0000gn/T/instruments_sock
[debug] [iOS] No language specified. Using default strings
[debug] [iOS] Strings file not found. Looking in 'en.lproj' directory

[debug] [iOS] Parsed app 'Localizable.strings'

[debug] [ios-app-utils] Getting bundle ID from app

[iOS] Extracted bundleID: sg.com.gmarket.qpost from app: /var/folders/bm/mn11kb9j3y16yq7g39hgy89r0000gn/T/2016912-34759-1720wja/Payload/Qpost.app

[debug] [iOS] Creating instruments
[debug] [UIAuto] Preparing bootstrap code
[debug] [UIAuto] Dynamic bootstrap dir: /Users/dev/Library/Application Support/appium/bootstrap
[debug] [UIAuto] Dynamic env: {"nodePath":"/Applications/Appium.app/Contents/Resources/node/bin/node","commandProxyClientPath":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js","instrumentsSock":"/var/folders/bm/mn11kb9j3y16yq7g39hgy89r0000gn/T/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"grouped"}

[debug] [UIAuto] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...

[debug] [UIAuto] Dynamic bootstrap path: /Users/dev/Library/Application Support/appium/bootstrap/bootstrap-daa8e92d421e9d53.js

[debug] [UIAuto] Reusing dynamic bootstrap: /Users/dev/Library/Application Support/appium/bootstrap/bootstrap-daa8e92d421e9d53.js

[debug] [iOS] Running ios real device reset flow

[debug] [iOS] Full reset requested. Will try to uninstall the app 'sg.com.gmarket.qpost'.
[debug] [iOS] Creating iDevice object with udid 73e931ec4a6c380dedadee6cc67af590ee93adc8

[iOS] Could not remove 'sg.com.gmarket.qpost' from device

[MJSONWP] Encountered internal error running command: Error: Removing sg.com.gmarket.qpost failed
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/node-idevice/main.js:145:6
    at ChildProcess.exithandler (child_process.js:193:7)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:475:12)

[HTTP] <-- POST /wd/hub/session 500 4400 ms - 173 
```

**Comment by jlipps** [comment]
try removing `--full-reset` from the appium invocation

**Comment by imurchie** [comment]
Appium 1.5.3 will not be able to automate this anyway, with Xcode 8, as the means of automation has changed. You will need to use Xcode 7.3.

**Comment by SubinLee** [comment]
@imurchie Thank you.
Are you only capable of running in Xcode 8 ver "Appium" 1.6.0 ver?

**Comment by SubinLee** [comment]
@jlipps  Thank you. Have a good day!

**Comment by imurchie** [comment]
@SubinLee Yes. Xcode 8 will only work with 1.6.0 and the `automationName` `XCUITest`.
