### ISSUE TITLE
XCUITest iproxy exited with code 208

### ISSUE THREAD

**Issue by saikrishna321** [appium/appium#6996]
@imurchie i was able run the tests on real device iOS 10.0, after a couple of run's i get the below error 

```
[debug] [WebDriverAgent] Device: Oct 12 19:23:29 HARIHARANs-iPhone XCTRunner[5337] <Notice>: Continuing to run tests in the background with task ID 1
[XCUITest] Detected that WebDriverAgent is running at url 'http://10.234.1.229:8100'
[XCUITest] WebDriverAgent started at url 'http://10.234.1.229:8100'
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[debug] [iProxy] bind(): Address already in use
[debug] [iProxy] Error creating socket: Address already in use
[XCUITest] Error: iproxy exited with code '208'
   at SubProcess.<anonymous> (lib/webdriveragent.js:378:25)
   at emitTwo (events.js:106:13)
   at SubProcess.emit (events.js:191:7)
   at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
   at emitTwo (events.js:106:13)
   at ChildProcess.emit (events.js:191:7)
   at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
Error: iproxy exited with code '208'
   at SubProcess.<anonymous> (lib/webdriveragent.js:378:25)
   at emitTwo (events.js:106:13)
   at SubProcess.emit (events.js:191:7)
   at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
   at emitTwo (events.js:106:13)
   at Ch[debug] [XCUITest] Running ios real device reset flow
ildProcess.emit (events.js:191:7)
   at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[debug] [XCUITest] Resetting simulator
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: iproxy exited with code '208'
   at SubProcess.<anonymous> (lib/webdriveragent.js:378:25)
   at emitTwo (events.js:106:13)
   at SubProcess.emit (events.js:191:7)
   at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
   at emitTwo (events.js:106:13)
   at ChildProcess.emit (events.js:191:7)
   at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[HTTP] <-- POST /wd/hub/session 500 12603 ms - 166
```

**Comment by imurchie** [comment]
Can you provide the logs from the beginning of the DELETE command from the previous session? Something is happening that the proxy server is still running.

**Comment by saikrishna321** [comment]
yah, there was a session of iproxy running. killing and running the tests again worked.. closing for now ...

**Comment by n-jooy** [comment]
How did you close the running iproxy session and where can I find it?

**Comment by imurchie** [comment]
You can run `ps -ax|grep -i "iproxy"|grep -v grep|awk '{print "kill -9 " $1}'|sh` on the command line.

**Comment by RatkoD** [comment]
This still needs some work, I need to execute @imurchie command almost every time I run a test.

**Comment by imurchie** [comment]
@RatkoD Can you provide the logs from a session? We have measures in place to kill the process, and something seems to be going wrong.

**Comment by RatkoD** [comment]
I started the test suite and now I'm stuck on this:

> [HTTP] --> GET /wd/hub/session/d0a39824-7398-48c4-a033-d22dab224703/context {}
> [MJSONWP] Calling AppiumDriver.getCurrentContext() with args: ["d0a39824-7398-48c4-a033-d...
> [debug] [XCUITest] Executing command 'getCurrentContext'
> [MJSONWP] Responding to client with driver.getCurrentContext() result: "NATIVE_APP"
> [HTTP] <-- GET /wd/hub/session/d0a39824-7398-48c4-a033-d22dab224703/context 200 2 ms - 84 
> [HTTP] --> GET /wd/hub/session/d0a39824-7398-48c4-a033-d22dab224703/screenshot {}
> [MJSONWP] Driver proxy active, passing request on via HTTP proxy
> [debug] [XCUITest] Executing command 'proxyReqRes'
> [JSONWP Proxy] Proxying [GET /wd/hub/session/d0a39824-7398-48c4-a033-d22dab224703/screenshot] to [GET http://localhost:8100/session/4F97E338-DC1E-462C-9EF9-AB2D8AB2E92C/screenshot] with body: {}
> [debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...

**Comment by imurchie** [comment]
Can you provide the _full_ logs as a [gist](https://gist.github.com)?

**Comment by RatkoD** [comment]
[debug] [WebDriverAgent] Device: Jan  5 20:33:18 RGs-iPhone-6 XCTRunner[1562] <Notice>: background task expired!!!
[debug] [iProxy] recv failed: Resource temporarily unavailable
[MJSONWP] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: Error: ETIMEDOUT
    at JWProxy.proxy$ (lib/jsonwp-proxy/proxy.js:122:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke 

> (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)[HTTP] <-- PO
> ST /wd/hub/session/2c42c3fb-ae80-4441-a562-982af3308b7f/element/085E5E05-8380-4F01-BB65-02BB711BB80C/value 500 240020 ms - 245 
> Test Failed
> Log report
> ProductType: iPhone7,2
> 
> [HTTP] --> GET /wd/hub/session/2c42c3fb-ae80-4441-a562-982af3308b7f/context {}
> [MJSONWP] Calling AppiumDriver.getCurrentContext() with args: ["2c42c3fb-ae80-4441-a562-9...
> [debug] [XCUITest] Executing command 'getCurrentContext'
> [MJSONWP] Responding to client with driver.getCurrentContext() result: "NATIVE_APP"
> [HTTP] <-- GET /wd/hub/session/2c42c3fb-ae80-4441-a562-982af3308b7f/context 200 2 ms - 84 
> [HTTP] --> GET /wd/hub/session/2c42c3fb-ae80-4441-a562-982af3308b7f/screenshot {}
> [MJSONWP] Driver proxy active, passing request on via HTTP proxy
> [debug] [XCUITest] Executing command 'proxyReqRes'
> [JSONWP Proxy] Proxying [GET /wd/hub/session/2c42c3fb-ae80-4441-a562-982af3308b7f/screenshot] to [GET http://localhost:8100/session/FB9A610F-30A8-4184-8F6A-695AB8752C68/screenshot] with body: {}
> [debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...

**Comment by RatkoD** [comment]
https://gist.github.com/RatkoD/c605a975e5282c8d548bc763632e8d70

**Comment by saikrishna321** [comment]
@RatkoD can you try upgrading to 1.6.3 and give it a try and also make sure you send a different wda port from your caps. 

I also see somehow your tests are picking selendroid as AutomatioName on your second run 

https://gist.github.com/RatkoD/c605a975e5282c8d548bc763632e8d70#file-gistfile1-txt-L2718

**Comment by saikrishna321** [comment]
@imurchie should i reopen this issue ?

**Comment by imurchie** [comment]
@saikrishna321 I don't think so. The latest version of Appium better handles killing the processes. 

@RatkoD Can you upgrade to 1.6.3?

**Comment by RatkoD** [comment]
I've upgraded to 1.6.3, let me do a few more test runs to see if it happens and how often. Thanks!

**Comment by vkvikaskmr** [comment]
Its happening with 1.6.3 in cases where the earlier test failed and the cleanup was not done properly. So appium server could not be stopped(as part of cleanup) and the next time when I started the test I landed up with this error. Here are the associated logs : 

[XCUITest] Detected that WebDriverAgent is running at url 'http://10.252.240.98:8100'
[debug] [WebDriverAgent] Device: Jan 30 14:24:39 iPad XCTRunner[871] <Warning>: ServerURLHere->http://10.252.240.98:8100<-ServerURLHere
[XCUITest] WebDriverAgent started at url 'http://10.252.240.98:8100'
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[debug] [WebDriverAgent] Device: Jan 30 14:24:39 iPad XCTRunner[871] <Warning>: Listening on USB
[debug] [WebDriverAgent] Device: Jan 30 14:24:39 iPad SpringBoard[54] <Warning>: HW kbd: Failed to set (null) as keyboard focus
[debug] [iProxy] bind(): Address already in use
[debug] [iProxy] Error creating socket: Address already in use
[XCUITest] iproxy exited with code '208'
[XCUITest] Error: iproxy exited with code '208'
    at SubProcess.<anonymous> (../../lib/webdriveragent.js:438:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (../../lib/teen_process.js:197:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
 Error: iproxy exited with code '208'
    at SubProcess.<anonymous> (../../lib/webdriveragent.js:438:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (../../lib/teen_process.js:197:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down xcodebuild process (pid 61556)
[XCUITest] xcodebuild exited with code 'null' and signal 'SIGTERM'
[XCUITest] Shutting down Logger process (pid 61562)
[XCUITest] System log exited with code '0'

**Comment by imurchie** [comment]
This ought to be fixed in the next release.

**Comment by ohadschn** [comment]
Rather than categorically kill all iproxy instances (let alone with -9!), it is wiser to simply kills the process that takes up the port. Here's my bash function for doing it:

```bash
kill_process_bound_to_port () { 

    port="$1"
    waitAttempts="${2:-30}" #http://www.tldp.org/LDP/abs/html/parameter-substitution.html

    pid=$(lsof -i:$port -t)
    lsofExitCode=$?

    if (( lsofExitCode != 0 )); then
        echo "No processes listening on port $port"
        return
    fi
    
    echo "Detected process listening on port $port: $pid"
    echo "Killing the process to free up the port..."
    kill $pid
  
    for i in $(seq 1 $waitAttempts)
    do      
        echo "Checking if process $pid is alive... (attempt #$i / $waitAttempts)"
        sleep 1

        ps -p $pid > /dev/null
        psExitCode=$?

        if (( psExitCode == 0 )); then
             echo "Process $pid is still running"
        else
            echo "Process $pid has shut down successfully"
            break
        fi
    done

    if (( psExitCode == 0 )); then
        echo "Could not shut down process $pid gracefully - killing it forcibly..."
        kill -SIGKILL $pid
    fi
}
```

**Comment by mykola-mokhnach** [comment]
@ohadschn We'd be happy to review a pull request from you. This is the project URL on github https://github.com/appium/appium-xcuitest-driver

**Comment by ohadschn** [comment]
@mykola-mokhnach thank you for implying my code is worthy of being part of the driver :) However I think that's more of a script for guys to put in their CI systems, as it would probably unwise for appium to go off killing whatever process happens to be taking the port...

**Comment by VenkateshPS** [comment]
I get this error when Try creating two Appium drivers on two different ports using Appium 1.6.5 beta.
Xcode 8.3.2 

device1 iOS 10.2
device 2 iOS 10.3.2
 

Session one  is created and then error is thrown while creating second session. Below is the Appium console  log

**XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: iproxy exited with code '208'**
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:390:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: Unable to launch WebDriverAgent because of xcodebuild failure: iproxy exited with code '208'
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:390:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: iproxy exited with code '208'
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:390:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 35721 ms - 229 
[HTTP] --> POST /wd/hub/session {"capabilities":[{

**Comment by imurchie** [comment]
There is currently no provision for testing on two iOS devices at the same time.

**Comment by VenkateshPS** [comment]
My bad this was error on my setup, it worked when I used to different wda ports.

**Comment by VenkateshPS** [comment]
@imurchie , I was able to launch and login in two different devices (App). I will let you know if i face any issue.

I am using below commands two launch two different sessions on same machine.

appium --address 127.0.0.1  --port 4723 --show-ios-log --tmp /tmp/ios/ --command-timeout 30000

appium --address 127.0.0.1  --port 4725 --show-ios-log --tmp /tmp/ios6/ --command-timeout 30000

**Comment by saikrishna321** [comment]
@imurchie  

>  There is currently no provision for testing on two iOS devices at the same time.

I have been running on 4 devices in parallel and it works fine. Appium does help on this

**Comment by EitanBe** [comment]
@saikrishna321
Hi,
I connect 3 real IOS 10 devices to Appium 1.6.5.
I am using Java client 5 BETA8.
Sometimes, not consistently, i cannot create new IOSDriver. Do you also experience with the same issue?
If yes do you have a workaround you can share with me? 
Thanks,
Eitan.

**Comment by araveeti** [comment]
I get the same Error when I try to execute on two iOS devices(iPad Mini and ipad Pro) on Safari browser (Not app)

is it because of setting up the webkit debug proxy to 27753 (Default).

can some one please help.

Note: If I try to execute on one device its working fine.

Error:
[debug] [WebDriverAgent] Device: Oct 12 19:23:29 HARIHARANs-iPhone XCTRunner[5337] <Notice>: Continuing to run tests in the background with task ID 1
[XCUITest] Detected that WebDriverAgent is running at url 'http://10.234.1.229:8100'
[XCUITest] WebDriverAgent started at url 'http://10.234.1.229:8100'
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[debug] [iProxy] bind(): Address already in use
[debug] [iProxy] Error creating socket: Address already in use
[XCUITest] Error: iproxy exited with code '208'
   at SubProcess.<anonymous> (lib/webdriveragent.js:378:25)
   at emitTwo (events.js:106:13)
   at SubProcess.emit (event

**Comment by araveeti** [comment]
Here is the complete Error Message 

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: iproxy exited with code '208'

**Comment by VenkateshPS** [comment]
@araveeti launch web driver agents on two different ports if you want to run for two devices. you can assign wdaLocalPort as part of capability.

**Comment by wuhengzhi** [comment]
@VenkateshPS You are right, thank you.
Device 1:
capabilities1.setCapability("wdaLocalPort", "8001");
capabilities1.setCapability("udid", your_uuid);

Device 2:
capabilities2.setCapability("wdaLocalPort", "8002");
capabilities2.setCapability("udid", your_uuid);

**Comment by wuhengzhi** [comment]
@saikrishna321
@VenkateshPS
Did you run the devices in parallel with usb?
Is there any possible to drive devices in parallel with wifi?
Thanks.

**Comment by saikrishna321** [comment]
@wuhengzhi over USB

**Comment by Jitu1888** [comment]
Can you run Appium and iOS over wi -fi@saikrishan

**Comment by Jitu1888** [comment]
using Xcode 9 and iOS 11 we are able to automate over wifi

**Comment by mobigaurav** [comment]
Using Xcode 9 and iOS 11 i keep getting following error>

[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: "iproxy exited with code '208'". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.

I read the documentation and created a sample xcconfig file and put required entry in that but still it throws error on every start. I am trying to automate an ionic application , following is my javascript code to initiate appium.

const wdio = require('webdriverio');
// javascript
const opts = {
    port: 4723,
    desiredCapabilities: {
      platformName: "iOS",
      udid:'XXXXXXXXXXXXXXXX',
      platformVersion: "11.0",
      deviceName: "iPhone 7",
      app: "/Users/gauravku/Desktop/Payload.ipa",
      automationName: "XCUITest"
    }
  };
  const client = wdio.remote(opts);  
  client
  .init()

**Comment by Rajatgpta0208** [comment]
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: "iproxy exited with code '208'". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'B0204289s-MacBook-Pro.local', ip: 'fe80:0:0:0:443:7f8e:6ecf:f707%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.4', java.version: '1.8.0_161'
Driver info: driver.version: IOSDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: "iproxy exited with code '208'". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
    at getResponseForW3CError (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/lib/protocol/errors.js:800:13)
    at asyncHandler$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/lib/protocol/protocol.js:352:37)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
