### ISSUE TITLE
XCUITest [iProxy] recv failed: Operation not permitted

### ISSUE THREAD

**Issue by wjl025** [appium/appium#7007]
## The problem

Operation not permitted
## Environment
- Appium version (or git revision) that exhibits the issue:1.6.0
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium:10.11.6
- Node.js version (unless using Appium.app|exe):6.6.0
- Mobile platform/version under test:ios 9.3.5
- Real device or emulator/simulator:real device
- Appium CLI or Appium.app|exe:CLI
## Details

Describe in more detail the problem you have been experiencing, if necessary.
## Link to Appium logs

https://gist.github.com/wjl025/60d3893bd04aefac2abe8fa43a6c997f
## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by wjl025** [comment]
if not find element,appium.log print 
[debug] [XCUITest] Executing command 'implicitWait'
[debug] [BaseDriver] Set implicit wait to 10000ms
[MJSONWP] Responding to client with driver.implicitWait() result: null
[HTTP] <-- POST /wd/hub/session/c6382495-eca4-4b9a-9e98-68923c828389/timeouts/implicit_wait 200 2 ms - 76 
[HTTP] --> POST /wd/hub/session/c6382495-eca4-4b9a-9e98-68923c828389/execute {"script":"        (function() {\n        var opts = {\"typeArray\":[\"UIATextField\",\"UIASecureTextField\"],\"onlyVisible\":true,\"onlyFirst\":false};\n        var result = false;\n\n        try {\n          result = $._elementOrElementsByType($.mainWindow(), opts);\n        } catch (e) {\n        }\n\n        return result;\n        })();\n","args":[]}
[MJSONWP] Calling AppiumDriver.execute() with args: ["        (function() {\n  ...
[debug] [XCUITest] Executing command 'execute'
[HTTP] <-- POST /wd/hub/session/c6382495-eca4-4b9a-9e98-68923c828389/execute 501 2 ms - 112 
[debug] [iProxy] recv failed: Resource temporarily unavailable
[debug] [iProxy] recv failed: Operation not permitted

again execute script,then Operation not permitted error

**Comment by wjl025** [comment]
solve issue:
ps aux|grep udid|grep -v grep|awk '{print $2}'|xargs kill -9
udid is device

**Comment by imurchie** [comment]
One problem I see here is that the XCUITest driver will _not_ be able to execute that script. It is using UI Automation scripting language which no longer exists. We are looking into how to handle a replacement, but nothing is settled yet.

**Comment by WaFeIS7** [comment]
@imurchie  
Hello. Can you help me ?
I have the same issue with - "Operation not permitted" , when I call the method - IosDriver.navigate.back
Environment: 
Appium 1.6.0
Xcode 8
IPhone 6s Plus  10.0.2
Appium java client 4.1.1

In appium server in logs i have - 
"[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[JSONWP Proxy] Proxying [POST /wd/hub/session/585843eb-543f-4a50-81be-e213914ea639/back] to [POST http://localhost:8100/session/B37D5B39-972E-4723-B486-C2C11DE2F07B/back] with body: {}
[JSONWP Proxy] Got response with status 200: {"value":"Unhandled endpoin...
[JSONWP Proxy] Replacing sessionId B37D5B39-972E-4723-B486-C2C11DE2F07B with 585843eb-543f-4a50-81be-e213914ea639
[HTTP] <-- POST /wd/hub/session/585843eb-543f-4a50-81be-e213914ea639/back 200 11 ms - 285 
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [iProxy] recv failed: Resource temporarily unavailable
[debug] [iProxy] recv failed: Operation not permitted " 

In Idea console - 
"org.openqa.selenium.WebDriverException: Unhandled endpoint: /session/B37D5B39-972E-4723-B486-C2C11DE2F07B/back -- http://localhost:8100/ with parameters {
    wildcards =     (
        "session/B37D5B39-972E-4723-B486-C2C11DE2F07B/back"
    );
}
Command duration or timeout: 16 milliseconds
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'Mykolas-MacBook-Air.local', ip: '10.100.128.18', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12', java.version: '1.8.0_60'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{app=/Users/vadimzdanovich/Downloads/filmon-ios.ipa, networkConnectionEnabled=false, appiumVersion=1.6, xcodeConfigFile=/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Config.xcconfig, databaseEnabled=false, iosInstallPause=8000, deviceName=IPhone 6s Plus, fullReset=true, platform=MAC, newCommandTimeout=9000, platformVersion=10, webStorageEnabled=false, locationContextEnabled=false, automationName=XCUITest, browserName=, takesScreenshot=true, waitForAppScript=$.delay(1000); $.acceptAlert();, javascriptEnabled=true, platformName=iOS, udid=9d1201e667ef158492298d50cbb17248bd5002ce}]
Session ID: 585843eb-543f-4a50-81be-e213914ea639

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:40)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:235)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteNavigation.back(RemoteWebDriver.java:961)
	at com.filmon.mobile.ios.tests.ProfileTest.Test_003_goToRecordings(ProfileTest.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:124)" 

Full Appium logs -- https://gist.github.com/WaFeIS7/b0cb464bb65959aec89ba7e8788fbec9

**Comment by ssynix** [comment]
@WaFeIS7 if you're using a real device, could you also attach what you're seeing in `ios-webkit-debug-proxy` logs?

**Comment by WaFeIS7** [comment]
@ssynix Hello. 
Yes, I use real device to run app without browser.
`ios-webkit-debug-proxy`  to inspect elements on MobileSafari and UIWebViews. 
I did that  `ios_webkit_debug_proxy -c 9d1201e667ef158492298d50cbb17248bd5002ce:9227 -d` 
Here logs -- https://gist.github.com/WaFeIS7/2bafdad01a68044c4e1d6032943590c7 
But I don`t really understand how this logs will help? 
Can you explain me? 
Thanks
Best regards.

**Comment by imurchie** [comment]
@WaFeIS7 This is _not_ the same issue.

The issue you are facing is that there is currently no implementation of `back` for native contexts. You will need to do whatever will send you back in your particular app (e.g., if there is a button to return to the previous screen, click it).

We are working on finding a stable way to implement `back`, but haven't come across one yet.

**Comment by WaFeIS7** [comment]
@imurchie 
Thanks for answer.
Good luck to find solution.
Can i create this issue? or it is not necessary.

**Comment by imurchie** [comment]
@WaFeIS7 https://github.com/appium/appium/issues/7118

**Comment by WaFeIS7** [comment]
@imurchie Thanks

**Comment by ssynix** [comment]
@WaFeIS7 I had this issue where the iOS 10 phone would get disconnected from ios-webkit-debug-proxy, and for me it was fixed by building the proxy from source. I wanted to see if the same pattern happens in your logs before making you build it from source, but at least here that's not the case.

**Comment by Hiran47** [comment]
@imurchie: Any update on the original issue here? I'm facing the same with Appium 1.6.2 on iOS 10.1.1 (real device). Any help would be really appreciated.

Thanks.

**Comment by jlipps** [comment]
There's still conceptually no way to execute 'native' code in an xcuitest session.
