### ISSUE TITLE
How can i install ipa on real device having iOS version 10?

### ISSUE THREAD

**Issue by erhitesh** [appium/appium#7018]
## Problem

When i install ipa using appium on iPhone device having version 10 then it gives me error.
## My DesiredCapability

*DeviceRelatedInformation d = new DeviceRelatedInformation()
*DesiredCapabilities cap  = new DesiredCapabilities()
*cap.setCapability(MobileCapabilityType.AUTOMATION_NAME, "Appium")
*cap.setCapability(MobileCapabilityType.PLATFORM_NAME, "IOS")
*cap.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone 5s")
*cap.setCapability(MobileCapabilityType.APPIUM_VERSION, "1.4.13")
*cap.setCapability(MobileCapabilityType.UDID, "did")
*cap.setCapability(MobileCapabilityType.APP,"app location")
## Environment
- Appium version : 1.4.13
- Desktop OS/version used to run Appium: mac OS X 10.11.6
- Real device: Real device (version 10.0.2)
## Details

when i install ipa using appium on iOS device having version 10 or higher.
Gives the error which is in below appium log.
## Appium Log

2016-10-14 11:19:46:138 - info: Welcome to Appium v1.4.13 (REV c75d8adcb66a75818a542fe1891a34260c21f76a)
2016-10-14 11:19:46:142 - info: Appium REST http interface listener started on 127.0.0.1:4723
2016-10-14 11:19:46:146 - info: [debug] Non-default server args: {"app":"/Users/hiteshbhardwaj/Desktop/Automation/app/LanguagesForIOS/Albanian/albanian.ipa","udid":"84974ee52e47314f4e50b296df4610e953edc63f","address":"127.0.0.1","sessionOverride":true,"noReset":true,"launchTimeout":"90000","log":"/Users/hiteshbhardwaj/Desktop/Automation/workspace/logs/appium2.log","nativeInstrumentsLib":true,"deviceName":"iPhone 5","platformName":"iOS","platformVersion":"10.0.2","showIOSLog":true,"defaultCommandTimeout":7200,"isolateSimDevice":true,"debugLogSpacing":true}
2016-10-14 11:19:46:147 - info: Console LogLevel: debug
2016-10-14 11:19:46:147 - info: File LogLevel: debug
2016-10-14 11:19:46:273 - info: --> GET /wd/hub/status {}
2016-10-14 11:19:46:276 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
2016-10-14 11:19:46:284 - info: <-- GET /wd/hub/status 200 10.505 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
2016-10-14 11:19:57:434 - info: --> GET /wd/hub/status {}
2016-10-14 11:19:57:435 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
2016-10-14 11:19:57:438 - info: <-- GET /wd/hub/status 200 4.209 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
2016-10-14 11:20:14:209 - info: --> GET /wd/hub/status {}
2016-10-14 11:20:14:209 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
2016-10-14 11:20:14:211 - info: <-- GET /wd/hub/status 200 2.073 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
2016-10-14 11:20:58:582 - info: --> GET /wd/hub/status {}
2016-10-14 11:20:58:583 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
2016-10-14 11:20:58:584 - info: <-- GET /wd/hub/status 200 2.574 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
2016-10-14 11:21:15:353 - info: --> GET /wd/hub/status {}
2016-10-14 11:21:15:353 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
2016-10-14 11:21:15:355 - info: <-- GET /wd/hub/status 200 2.136 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
2016-10-14 11:21:59:588 - info: --> GET /wd/hub/status {}
2016-10-14 11:21:59:588 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
2016-10-14 11:21:59:590 - info: <-- GET /wd/hub/status 200 2.194 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
2016-10-14 11:22:16:424 - info: --> GET /wd/hub/status {}
2016-10-14 11:22:16:424 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
2016-10-14 11:22:16:425 - info: <-- GET /wd/hub/status 200 1.625 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
2016-10-14 11:22:38:581 - info: --> GET /wd/hub/status {}
2016-10-14 11:22:38:583 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
2016-10-14 11:22:38:584 - info: <-- GET /wd/hub/status 200 2.247 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
2016-10-14 11:22:38:586 - info: --> GET /wd/hub/sessions {}
2016-10-14 11:22:38:587 - info: [debug] Responding to client with success: {"status":0,"value":[]}
2016-10-14 11:22:38:588 - info: <-- GET /wd/hub/sessions 200 1.411 ms - 23 {"status":0,"value":[]}
2016-10-14 11:22:38:605 - info: --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"iOS","platformVersion":"10.0.2","newCommandTimeout":"999999","automationName":"Appium","deviceName":"iPhone 5"}}
2016-10-14 11:22:38:607 - info: Client User-Agent string: Appium (unknown version) CFNetwork/760.6.3 Darwin/15.6.0 (x86_64)
2016-10-14 11:22:38:608 - info: *************************************
2016-10-14 11:22:38:608 - info: *************************************
2016-10-14 11:22:38:608 - info: *************************************
2016-10-14 11:22:38:609 - info: *************************************
2016-10-14 11:22:38:609 - info: *************************************
2016-10-14 11:22:38:609 - info: *************************************
2016-10-14 11:22:38:610 - info: *************************************
2016-10-14 11:22:38:610 - info: *************************************
2016-10-14 11:22:38:610 - info: ***\*        NEW SESSION           ***
2016-10-14 11:22:38:611 - info: ***\*        NEW SESSION           ***
2016-10-14 11:22:38:611 - info: ***\*        NEW SESSION           ***
2016-10-14 11:22:38:611 - info: ***\*        NEW SESSION           ***
2016-10-14 11:22:38:611 - info: ***\*        NEW SESSION           ***
2016-10-14 11:22:38:611 - info: ***\*        NEW SESSION           ***
2016-10-14 11:22:38:611 - info: ***\*        NEW SESSION           ***
2016-10-14 11:22:38:611 - info: ***\*        NEW SESSION           ***
2016-10-14 11:22:38:611 - info: *************************************
2016-10-14 11:22:38:612 - info: *************************************
2016-10-14 11:22:38:612 - info: *************************************
2016-10-14 11:22:38:612 - info: *************************************
2016-10-14 11:22:38:612 - info: *************************************
2016-10-14 11:22:38:612 - info: *************************************
2016-10-14 11:22:38:612 - info: *************************************
2016-10-14 11:22:38:614 - info: *************************************
2016-10-14 11:22:38:618 - info: [debug] Using local .ipa from command line: /Users/hiteshbhardwaj/Desktop/Automation/app/LanguagesForIOS/Albanian/albanian.ipa
2016-10-14 11:22:38:619 - info: [debug] Copying local zip to tmp dir
2016-10-14 11:22:39:308 - info: [debug] /Users/hiteshbhardwaj/Desktop/Automation/app/LanguagesForIOS/Albanian/albanian.ipa copied to /var/folders/v2/s_nhjz013yvdf6djb20d1f640000gp/T/116914-5902-qishje/appium-app.zip
2016-10-14 11:22:39:326 - info: [debug] Unzipping /var/folders/v2/s_nhjz013yvdf6djb20d1f640000gp/T/116914-5902-qishje/appium-app.zip
2016-10-14 11:22:39:326 - info: [debug] Testing zip archive: /var/folders/v2/s_nhjz013yvdf6djb20d1f640000gp/T/116914-5902-qishje/appium-app.zip
2016-10-14 11:22:40:127 - info: [debug] Zip archive tested clean
2016-10-14 11:22:41:330 - info: [debug] Unzip successful
2016-10-14 11:22:41:334 - info: [debug] Using locally extracted app: /var/folders/v2/s_nhjz013yvdf6djb20d1f640000gp/T/116914-5902-qishje/Payload/LD_AsiaTopVol1Pro.app
2016-10-14 11:22:41:335 - info: [debug] Creating new appium session 025710e2-1e9e-46c8-82e3-ff1ed00d1d6c
2016-10-14 11:22:41:338 - info: [debug] Removing any remaining instruments sockets
2016-10-14 11:22:41:340 - info: [debug] Cleaned up instruments socket /tmp/instruments_sock
2016-10-14 11:22:41:340 - info: [debug] Auto-detecting iOS udid...
2016-10-14 11:22:41:340 - info: [debug] Not auto-detecting udid, running on sim
2016-10-14 11:22:41:343 - info: [debug] Could not parse plist file (as binary) at /var/folders/v2/s_nhjz013yvdf6djb20d1f640000gp/T/116914-5902-qishje/Payload/LD_AsiaTopVol1Pro.app/en.lproj/Localizable.strings
2016-10-14 11:22:41:343 - info: Will try to parse the plist file as XML
2016-10-14 11:22:41:346 - info: [debug] Could not parse plist file (as XML) at /var/folders/v2/s_nhjz013yvdf6djb20d1f640000gp/T/116914-5902-qishje/Payload/LD_AsiaTopVol1Pro.app/en.lproj/Localizable.strings
2016-10-14 11:22:41:346 - warn: Could not parse app Localizable.strings assuming it doesn't exist
2016-10-14 11:22:41:346 - info: [debug] Getting bundle ID from app
2016-10-14 11:22:41:356 - info: [debug] Parsed app Info.plist (as binary)
2016-10-14 11:22:41:358 - info: [debug] Creating instruments
2016-10-14 11:22:41:360 - info: [debug] Preparing uiauto bootstrap
2016-10-14 11:22:41:360 - info: [debug] Dynamic bootstrap dir: /Users/hiteshbhardwaj/Library/Application Support/appium/bootstrap
2016-10-14 11:22:41:362 - info: [debug] Dynamic env: {"nodePath":"/Applications/Appium.app/Contents/Resources/node/bin/node","commandProxyClientPath":"/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"grouped"}
2016-10-14 11:22:41:392 - info: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...
2016-10-14 11:22:41:392 - info: [debug] Dynamic bootstrap path: /Users/hiteshbhardwaj/Library/Application Support/appium/bootstrap/bootstrap-5923cadea0343e3f.js
2016-10-14 11:22:41:397 - info: [debug] Reusing dynamic bootstrap: /Users/hiteshbhardwaj/Library/Application Support/appium/bootstrap/bootstrap-5923cadea0343e3f.js
2016-10-14 11:22:41:402 - info: [debug] Attempting iOS device log capture via libimobiledevice idevicesyslog
2016-10-14 11:22:42:043 - info: [debug] Creating iDevice object with udid 84974ee52e47314f4e50b296df4610e953edc63f
2016-10-14 11:22:42:669 - info: [debug] App is not installed. Will try to install the app.
2016-10-14 11:22:42:670 - info: [debug] Installing ipa found at /Users/hiteshbhardwaj/Desktop/Automation/app/LanguagesForIOS/Albanian/albanian.ipa
2016-10-14 11:22:43:136 - info: [debug] Nothing found on device, going ahead and installing.
2016-10-14 11:22:43:704 - info: [debug] Starting command proxy.
2016-10-14 11:22:43:707 - info: [debug] Instruments socket server started at /tmp/instruments_sock
2016-10-14 11:22:43:708 - info: [debug] Starting instruments
2016-10-14 11:22:43:792 - info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
2016-10-14 11:22:43:793 - info: Launching instruments
2016-10-14 11:22:43:795 - info: [debug] Attempting to run app on real device with UDID 84974ee52e47314f4e50b296df4610e953edc63f
2016-10-14 11:22:43:796 - info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w 84974ee52e47314f4e50b296df4610e953edc63f com.eduVenture.LdAlbanian -e UIASCRIPT "/Users/hiteshbhardwaj/Library/Application Support/appium/bootstrap/bootstrap-5923cadea0343e3f.js" -e UIARESULTSPATH /tmp/appium-instruments
2016-10-14 11:22:43:796 - info: [debug] And extra without-delay env: {}
2016-10-14 11:22:43:797 - info: [debug] And launch timeouts (in ms): {"global":90000}
2016-10-14 11:22:45:815 - info: [debug] [INST STDERR] 2016-10-14 16:52:45.814 instruments[5930:97289] WebKit Threading Violation - initial use of WebKit from a secondary thread.
2016-10-14 11:22:46:305 - info: [debug] [INST STDERR] Instruments Usage Error: Specified target process is invalid: com.eduVenture.LdAlbanian
2016-10-14 11:22:46:306 - info: [debug] [INST STDERR] instruments, version 7.3 (60133)
usage: instruments [-t template] [-D document] [-l timeLimit] [-i #] [-w device] [[-p pid] | [application [-e variable value] [argument ...]]]
2016-10-14 11:22:46:317 - info: [debug] [INSTSERVER] Instruments exited with code 255
2016-10-14 11:22:46:318 - info: [debug] Killall instruments
2016-10-14 11:22:46:321 - info: [debug] Instruments crashed on startup
2016-10-14 11:22:46:322 - info: [debug] Attempting to retry launching instruments, this is retry #1
2016-10-14 11:22:46:323 - info: [debug] Killall iOS Simulator
2016-10-14 11:22:51:326 - info: Launching instruments
2016-10-14 11:22:51:329 - info: [debug] Attempting to run app on real device with UDID 84974ee52e47314f4e50b296df4610e953edc63f
2016-10-14 11:22:51:330 - info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w 84974ee52e47314f4e50b296df4610e953edc63f com.eduVenture.LdAlbanian -e UIASCRIPT "/Users/hiteshbhardwaj/Library/Application Support/appium/bootstrap/bootstrap-5923cadea0343e3f.js" -e UIARESULTSPATH /tmp/appium-instruments
2016-10-14 11:22:51:331 - info: [debug] And extra without-delay env: {}
2016-10-14 11:22:51:331 - info: [debug] And launch timeouts (in ms): {"global":90000}
2016-10-14 11:22:53:453 - info: [debug] [INST STDERR] 2016-10-14 16:52:53.452 instruments[5936:97433] WebKit Threading Violation - initial use of WebKit from a secondary thread.
2016-10-14 11:22:53:749 - info: [debug] [INST STDERR] Instruments Usage Error: Specified target process is invalid: com.eduVenture.LdAlbanian
instruments, version 7.3 (60133)
usage: instruments [-t template] [-D document] [-l timeLimit] [-i #] [-w device] [[-p pid] | [application [-e variable value] [argument ...]]]
2016-10-14 11:22:53:760 - info: [debug] [INSTSERVER] Instruments exited with code 255
2016-10-14 11:22:53:761 - info: [debug] Killall instruments
2016-10-14 11:22:53:766 - info: [debug] Instruments crashed on startup
2016-10-14 11:22:53:766 - info: [debug] Attempting to retry launching instruments, this is retry #2
2016-10-14 11:22:53:767 - info: [debug] Killall iOS Simulator
2016-10-14 11:22:58:773 - info: Launching instruments
2016-10-14 11:22:58:774 - info: [debug] Attempting to run app on real device with UDID 84974ee52e47314f4e50b296df4610e953edc63f
2016-10-14 11:22:58:776 - info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w 84974ee52e47314f4e50b296df4610e953edc63f com.eduVenture.LdAlbanian -e UIASCRIPT "/Users/hiteshbhardwaj/Library/Application Support/appium/bootstrap/bootstrap-5923cadea0343e3f.js" -e UIARESULTSPATH /tmp/appium-instruments
2016-10-14 11:22:58:776 - info: [debug] And extra without-delay env: {}
2016-10-14 11:22:58:776 - info: [debug] And launch timeouts (in ms): {"global":90000}
2016-10-14 11:23:00:597 - info: --> GET /wd/hub/status {}
2016-10-14 11:23:00:598 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"},"isShuttingDown":false},"sessionId":"025710e2-1e9e-46c8-82e3-ff1ed00d1d6c"}
2016-10-14 11:23:00:600 - info: <-- GET /wd/hub/status 200 3.839 ms - 179 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"},"isShuttingDown":false},"sessionId":"025710e2-1e9e-46c8-82e3-ff1ed00d1d6c"}
2016-10-14 11:23:00:802 - info: [debug] [INST STDERR] 2016-10-14 16:53:00.802 instruments[5943:97505] WebKit Threading Violation - initial use of WebKit from a secondary thread.
2016-10-14 11:23:01:108 - info: [debug] [INST STDERR] Instruments Usage Error: Specified target process is invalid: com.eduVenture.LdAlbanian
instruments, version 7.3 (60133)
usage: instruments [-t template] [-D document] [-l timeLimit] [-i #] [-w device] [[-p pid] | [application [-e variable value] [argument ...]]]
2016-10-14 11:23:01:120 - info: [debug] [INSTSERVER] Instruments exited with code 255
2016-10-14 11:23:01:121 - info: [debug] Killall instruments
2016-10-14 11:23:01:124 - info: [debug] Instruments crashed on startup
2016-10-14 11:23:01:126 - info: [debug] Attempting to retry launching instruments, this is retry #3
2016-10-14 11:23:01:127 - info: [debug] Killall iOS Simulator
2016-10-14 11:23:06:127 - info: Launching instruments
2016-10-14 11:23:06:128 - info: [debug] Attempting to run app on real device with UDID 84974ee52e47314f4e50b296df4610e953edc63f
2016-10-14 11:23:06:129 - info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w 84974ee52e47314f4e50b296df4610e953edc63f com.eduVenture.LdAlbanian -e UIASCRIPT "/Users/hiteshbhardwaj/Library/Application Support/appium/bootstrap/bootstrap-5923cadea0343e3f.js" -e UIARESULTSPATH /tmp/appium-instruments
2016-10-14 11:23:06:129 - info: [debug] And extra without-delay env: {}
2016-10-14 11:23:06:129 - info: [debug] And launch timeouts (in ms): {"global":90000}
2016-10-14 11:23:08:248 - info: [debug] [INST STDERR] 2016-10-14 16:53:08.247 instruments[5949:97581] WebKit Threading Violation - initial use of WebKit from a secondary thread.
2016-10-14 11:23:08:714 - info: [debug] [INST STDERR] Instruments Usage Error: Specified target process is invalid: com.eduVenture.LdAlbanian
instruments, version 7.3 (60133)
**usage: instruments [-t template] [-D document] [-l timeLimit] [-i #] [-w device] [[-p pid] | [application [-e variable value] [argument ...]]]**
2016-10-14 11:23:08:726 - info: [debug] [INSTSERVER] Instruments exited with code 255
2016-10-14 11:23:08:727 - info: [debug] Killall instruments
2016-10-14 11:23:08:731 - info: [debug] Instruments crashed on startup
2016-10-14 11:23:08:731 - info: [debug] We exceeded the number of retries allowed for instruments to successfully start; failing launch
2016-10-14 11:23:08:732 - info: [debug] Stopping iOS log capture
2016-10-14 11:23:08:734 - info: [debug] Reset not set, not ending sim or cleaning up app state
2016-10-14 11:23:08:734 - info: [debug] Cleaning up appium session
2016-10-14 11:23:08:736 - error: Failed to start an Appium session, err was: Error: Instruments crashed on startup
2016-10-14 11:23:08:739 - info: [debug] Error: Instruments crashed on startup
    at [object Object].Instruments.onInstrumentsExit (/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-instruments/lib/instruments.js:440:31)
    at [object Object].<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-instruments/lib/instruments.js:353:12)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
2016-10-14 11:23:08:740 - info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Instruments crashed on startup)","origValue":"Instruments crashed on startup"},"sessionId":null}
2016-10-14 11:23:08:745 - info: <-- POST /wd/hub/session 500 30139.632 ms - 182 
2016-10-14 11:23:17:426 - info: --> GET /wd/hub/status {}
2016-10-14 11:23:17:427 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
2016-10-14 11:23:17:429 - info: <-- GET /wd/hub/status 200 2.901 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
2016-10-14 11:24:01:663 - info: --> GET /wd/hub/status {}
2016-10-14 11:24:01:663 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
2016-10-14 11:24:01:664 - info: <-- GET /wd/hub/status 200 1.634 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
2016-10-14 11:24:18:597 - info: --> GET /wd/hub/status {}
2016-10-14 11:24:18:597 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
2016-10-14 11:24:18:598 - info: <-- GET /wd/hub/status 200 1.174 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
2016-10-14 11:25:02:836 - info: --> GET /wd/hub/status {}
2016-10-14 11:25:02:836 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
2016-10-14 11:25:02:837 - info: <-- GET /wd/hub/status 200 1.098 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
2016-10-14 11:25:19:748 - info: --> GET /wd/hub/status {}
2016-10-14 11:25:19:749 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
2016-10-14 11:25:19:750 - info: <-- GET /wd/hub/status 200 1.647 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
2016-10-14 11:26:03:913 - info: --> GET /wd/hub/status {}
2016-10-14 11:26:03:914 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
2016-10-14 11:26:03:915 - info: <-- GET /wd/hub/status 200 1.477 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
2016-10-14 11:26:20:914 - info: --> GET /wd/hub/status {}
2016-10-14 11:26:20:915 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
2016-10-14 11:26:20:916 - info: <-- GET /wd/hub/status 200 1.157 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
2016-10-14 11:27:04:991 - info: --> GET /wd/hub/status {}
2016-10-14 11:27:04:991 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
2016-10-14 11:27:04:992 - info: <-- GET /wd/hub/status 200 1.719 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
2016-10-14 11:27:22:017 - info: --> GET /wd/hub/status {}
2016-10-14 11:27:22:018 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
2016-10-14 11:27:22:019 - info: <-- GET /wd/hub/status 200 2.122 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
2016-10-14 11:28:06:017 - info: --> GET /wd/hub/status {}
2016-10-14 11:28:06:017 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
2016-10-14 11:28:06:019 - info: <-- GET /wd/hub/status 200 1.846 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
2016-10-14 11:28:27:260 - info: --> GET /wd/hub/status {}
2016-10-14 11:28:27:260 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
2016-10-14 11:28:27:262 - info: <-- GET /wd/hub/status 200 2.585 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
2016-10-14 11:29:07:045 - info: --> GET /wd/hub/status {}
2016-10-14 11:29:07:046 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
2016-10-14 11:29:07:046 - info: <-- GET /wd/hub/status 200 1.189 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}

**Comment by erhitesh** [comment]
i

**Comment by erhitesh** [comment]
If anyone facing the same issue and find solution please update me.

**Comment by saikrishna321** [comment]
@erhitesh pls upgrade your appium version to 1.6.0

**Comment by imurchie** [comment]
As @saikrishna321 said, Appium's support for iOS 10 begins at version 1.6.0. Previous versions will not be able to do anything with it.

**Comment by erhitesh** [comment]
Thanks Sai Krishna and Issac A.Murchie.
If I upgrade my appium version to 1.6.0 can handle the issue.

**Comment by SrinivasanTarget** [comment]
Yes @erhitesh

**Comment by SrinivasanTarget** [comment]
@triager please close
