### ISSUE TITLE
Appium 1.6.0 - driver.resetApp fails

### ISSUE THREAD

**Issue by muratme** [appium/appium#7019]
## The problem

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up (WARNING: The server did not provide any stacktrace information)
## Environment
- Appium version (or git revision) that exhibits the issue: Appium 1.6.0
- Desktop OS/version used to run Appium: MACOS 10.11.6 El Capitan 
- Node version (unless using Appium.app|exe): v6.8.0
- Npm Version : 3.10.8
- Mobile platform/version under test: IOS 10.0
- Real device or emulator/simulator: Iphone5
- java version "1.8.0_40"
## Details

The resetApp command fails on test execution.
## Link to Appium logs

https://gist.github.com/muratme/1b7cd3ae067cac71bb526d528a47b85d
## Code To Reproduce Issue [ Good To Have ]

```
@Before
public void setUp() throws Exception
{
    driver.resetApp();
    .
    .
    .
}
```

**Comment by mayureshshirodkar** [comment]
@imurchie 
Even i am facing the same issue.
Appium version (or git revision) that exhibits the issue: Appium 1.6.0
Desktop OS/version used to run Appium: MACOS 10.11.6 El Capitan
Mobile platform/version under test: IOS 9.3.5
Real device or emulator/simulator: Iphone5s

**Comment by rkavalap** [comment]
@muratme  I see error connecting to device from the gist log.  Can this be addressed first. 
[XCUITest] WebDriverAgent started at url 'http://192.168.61.14:8100'
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bu...
[debug] [iProxy] Error connecting to device!
[XCUITest] ProxyRequestError: Could not proxy command to remote server. Original error: Error: socket hang up
    at JWProxy.proxy$ (lib/jsonwp-proxy/proxy.js:122:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 { ProxyRequestError: Could not proxy command to remote server. Original error: Error: socket hang up
    at JWProxy.proxy$ (lib/jsonwp-proxy/proxy.js:122:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
  jsonwp:
   { Error: socket hang up
       at createHangUpError (_http_client.js:254:15)
       at Socket.socketOnEnd (_http_client.js:346:23)
       at emitNone (events.js:91:20)
       at Socket.emit (events.js:185:7)
       at endReadableNT (_stream_readable.js:974:12)
       at _combinedTickCallback (internal/process/next_tick.js:74:11)
       at process._tickCallback (internal/process/next_tick.js:98:9) code: 'ECONNRESET' } }
[JSONWP Proxy] Proxying [DELETE /session/aa7d68e1-2f16-45f9-9ea9-17bbd6f040f8] to [DELETE http://localhost:8100/session/aa7d68e1-2f16-45f9-9ea9-17bbd6f040f8] with no body
[debug] [iProxy] Error connecting to device!

**Comment by mayureshshirodkar** [comment]
@rkavalap There is a defect for the socket hangup here:
https://github.com/appium/appium/issues/7063

**Comment by rkavalap** [comment]
Closing this as dup for #7063
