### ISSUE TITLE
[Error: Could not detect Mac OS X Version from sw_vers output: '10.12 ']

### ISSUE THREAD

**Issue by Tanmoyray** [appium/appium#7031]
## The problem

I am not able run appium. Please help, How to fixed this issue?

appium doctor has not worked. 
Error :
info AppiumDoctor ### Diagnostic starting ###
info AppiumDoctor  ✔ Xcode is installed at: /Applications/Xcode.app/Contents/Developer
[Error: Could not detect Mac OS X Version from sw_vers output: '10.12
## Environment

 macOX siri 
appium: 1.5.3

## Link to Appium logs
```
Launching Appium with command: /Applications/Appium.app/Contents/Resources/node/bin/node' appium/build/lib/main.js --debug-log-spacing --automation-name "Appium" --platform-name "Android" --platform-version "7.0" --app "/Users/tanmoyray/Desktop/veiculu.apk" --avd "test_7.0" --app-pkg "com.senrysa.parkingplace" --app-activity "com.facebook.LoginActivity" --device-name "Moto"
[Appium] Welcome to Appium v1.5.3

[Appium] Non-default server args:
[Appium]   debugLogSpacing: true
[Appium]   platformName: 'Android'
[Appium]   platformVersion: '7.0'
[Appium]   automationName: 'Appium'
[Appium]   deviceName: 'Moto'
[Appium]   app: '/Users/tanmoyray/Desktop/veiculu.apk'
[Appium]   appPackage: 'com.senrysa.parkingplace'
[Appium]   appActivity: 'com.facebook.LoginActivity'
[Appium]   avd: 'test_7.0'
[Appium] Deprecated server args:
[Appium]   --platform-name => --default-capabilities '{"platformName":"Android"}'
[Appium]   --platform-version => --default-capabilities '{"platformVersion":"7.0"}'
[Appium]   --automation-name => --default-capabilities '{"automationName":"Appium"}'
[Appium]   --device-name => --default-capabilities '{"deviceName":"Moto"}'
[Appium]   --app => --default-capabilities '{"app":"/Users/tanmoyray/Desktop/veiculu.apk"}'
[Appium]   --app-pkg => --default-capabilities '{"appPackage":"com.senrysa.parkingplace"}'
[Appium]   --app-activity => --default-capabilities '{"appActivity":"com.facebook.LoginActivity"}'
[Appium]   --avd => --default-capabilities '{"avd":"test_7.0"}'
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   platformName: 'Android'
[Appium]   platformVersion: '7.0'
[Appium]   automationName: 'Appium'
[Appium]   deviceName: 'Moto'
[Appium]   app: '/Users/tanmoyray/Desktop/veiculu.apk'
[Appium]   appPackage: 'com.senrysa.parkingplace'
[Appium]   appActivity: 'com.facebook.LoginActivity'
[Appium]   avd: 'test_7.0'

[Appium] Appium REST http interface listener started on 0.0.0.0:4723

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[HTTP] <-- GET /wd/hub/status 200 41 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[HTTP] <-- GET /wd/hub/status 200 25 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 22 ms - 83 

[HTTP] --> GET /wd/hub/sessions {}

[MJSONWP] Calling AppiumDriver.getSessions() with args: []

[MJSONWP] Responding to client with driver.getSessions() result: []

[HTTP] <-- GET /wd/hub/sessions 200 4 ms - 40 

[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"Android","appPackage":"com.senrysa.parkingplace","newCommandTimeout":"7200","app":"/Users/tanmoyray/Desktop/veiculu.apk","platformVersion":"7.0","deviceName":"Moto","automationName":"Appium"}}

[MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"Android",...

[Appium] Creating new AndroidDriver session
[Appium] Capabilities:
[Appium]   platformName: 'Android'
[Appium]   appPackage: 'com.senrysa.parkingplace'
[Appium]   newCommandTimeout: '7200'
[Appium]   app: '/Users/tanmoyray/Desktop/veiculu.apk'
[Appium]   platformVersion: '7.0'
[Appium]   deviceName: 'Moto'
[Appium]   automationName: 'Appium'
[Appium]   appActivity: 'com.facebook.LoginActivity'
[Appium]   avd: 'test_7.0'

[BaseDriver] Capability 'newCommandTimeout' changed from string ('7200') to integer (7200). This may cause unexpected behavior

[BaseDriver] Session created with session id: 135df2ce-cc52-43c8-95aa-9a1a35d6fb19
[debug] [AndroidDriver] Getting Java version

[AndroidDriver] Java version is: 1.8.0_91

[ADB] Checking whether adb is present

[ADB] Using adb from /Users/tanmoyray/library/android/sdk/platform-tools/adb

[debug] [ADB] Trying to find test_7.0 emulator

[debug] [ADB] Getting connected emulators

[debug] [ADB] Getting connected devices...

[debug] [ADB] 1 device(s) connected

[debug] [ADB] 1 emulator(s) connected

[debug] [ADB] Sending telnet command to device: avd name
[debug] [ADB] Getting running emulator port

[debug] [ADB] Socket connection to device created

[debug] [ADB] Socket connection to device ready

[debug] [ADB] Telnet command got response: Nexus_S_API_24

[debug] [ADB] Emulator test_7.0 not running
[debug] [ADB] Launching Emulator with AVD test_7.0, launchTimeout60000 ms and readyTimeout 60000 ms
[ADB] Checking whether emulator is present

.
.
.

[debug] [ADB] Trying to find test_7.0 emulator

[debug] [ADB] Getting connected emulators
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] 1 emulator(s) connected
[debug] [ADB] Sending telnet command to device: avd name
[debug] [ADB] Getting running emulator port
[debug] [ADB] Socket connection to device created
[debug] [ADB] Socket connection to device ready
[debug] [ADB] Telnet command got response: Nexus_S_API_24
[debug] [ADB] Emulator test_7.0 not running

[debug] [ADB] Trying to find test_7.0 emulator

[debug] [ADB] Getting connected emulators
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] 1 emulator(s) connected
[debug] [ADB] Sending telnet command to device: avd name
[debug] [ADB] Getting running emulator port
[debug] [ADB] Socket connection to device created
[debug] [ADB] Socket connection to device ready
[debug] [ADB] Telnet command got response: Nexus_S_API_24
[debug] [ADB] Emulator test_7.0 not running

[debug] [ADB] Trying to find test_7.0 emulator

[debug] [ADB] Getting connected emulators
[debug] [ADB] Getting connected devices...

[debug] [ADB] 1 device(s) connected

[ADB] Error: Could not find test_7.0 emulator.
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at ADB.callee$0$0$ (lib/tools/system-calls.js:325:9)
    at tryCatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
 [Error: Could not find test_7.0 emulator.]

[debug] [ADB] 1 emulator(s) connected
[debug] [ADB] Sending telnet command to device: avd name
[debug] [ADB] Getting running emulator port
[debug] [ADB] Socket connection to device created
[debug] [ADB] Socket connection to device ready
[debug] [ADB] Telnet command got response: Nexus_S_API_24
[debug] [ADB] Emulator test_7.0 not running
[debug] [AndroidDriver] Shutting down Android driver
[AndroidDriver] Cannot shut down Android driver; it has already shut down
[HTTP] <-- POST /wd/hub/session 500 64352 ms - 216 

[ADB] Error: Error getting AVD with retry. Original error: Could not find test_7.0 emulator.
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at ADB.callee$0$0$ (lib/tools/system-calls.js:327:9)
    at tryCatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
 [Error: Error getting AVD with retry. Original error: Could not find test_7.0 emulator.]
[MJSONWP] Encountered internal error running command: Error: Error getting AVD with retry. Original error: Could not find test_7.0 emulator.
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at ADB.callee$0$0$ (lib/tools/system-calls.js:327:9)
    at tryCatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

[HTTP] --> GET /wd/hub/status {}
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 95 ms - 83 
```

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by imurchie** [comment]
The `appium-doctor` issue has been fixed in a recent version.

Android N support is not available in Appium 1.5.3. You will need to upgrade in order to use it.

**Comment by Tanmoyray** [comment]
How to upgrade appium UI mode ?

**Comment by imurchie** [comment]
I don't know what that means.

**Comment by Tanmoyray** [comment]
I am really sorry for that. Please let me know, how to upgrade appium-1.5.3.dmg file ?

**Comment by imurchie** [comment]
As of yet there is not one, unfortunately. The person who works on it will be making it early this week.

**Comment by Tanmoyray** [comment]
Thank you @imurchie . I am waiting for it.

**Comment by AdamLaiiiii** [comment]
I'm waiting for it too .

**Comment by chattip-playbasis** [comment]
It' worked for me.

Answer for resolve this problem.

http://stackoverflow.com/questions/40129794/how-to-fix-error-could-not-detect-mac-os-x-version-from-sw-vers-output-10-12/40168992#40168992

**Comment by AdamLaiiiii** [comment]
@chattip-playbasis ahhahah~ it works .  thk u.
