### ISSUE TITLE
appium can't run on real-device

### ISSUE THREAD

**Issue by bily621** [appium/appium#7035]
## The problem

I build the app by xcode,and install on my real device,i can use instruments to test my app,but i can not  test cases using appium

## Environment

1、 Appium version :1.5.3
2、OS X: 10.11.6
3、Node.js version :v4.4.3
4、ios :9.2.1
5、xcode verson:8.0

## Link to Appium logs

[debug] [iOS] Creating iDevice object with udid b665282d15e28693a72929c08916d29d451cf81f
[debug] [iOS] App is not installed. Will try to install the app.
[MJSONWP] Encountered internal error running command: Error: Installing com.juangua.mogujiedev.guyan failed
    at /Users/gy/WorkSpaces/nvm/versions/node/v4.4.3/lib/node_modules/appium/node_modules/appium-ios-driver/node_modules/node-idevice/main.js:159:6
    at ChildProcess.exithandler (child_process.js:204:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
[HTTP] <-- POST /wd/hub/session 500 1197 ms - 183

## Code To Reproduce Issue [ Good To Have ]
        capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "9.2.1");
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone");
        capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME,"iOS");
        capabilities.setCapability(MobileCapabilityType.APP,"com.xxx.xxx.xxx");
        capabilities.setCapability(MobileCapabilityType.UDID,"xxxxx");

**Comment by imurchie** [comment]
Appium 1.5.3 _will not_ work with Xcode 8. Xcode 8 will also not be able to automate iOS 9.2. If you want to do so you will need to get Xcode 7.3 and use that.

For installing, there is an issue with `ideviceinstaller`. To fix, re-install `libimobiledevice` with the latest (`brew upgrade libimobiledevice --HEAD`).

**Comment by pengboZheng** [comment]
@imurchie Thanks man!

**Comment by bily621** [comment]
@imurchie tks,but i have another question

when I run a case, the server throw an error ("Could not find app at com.jg.mgjdev")
Detail:
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"com.jg.mgj...
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   app: 'com.jg.mgjdev'
[Appium]   platformVersion: '9.3.4'
[Appium]   automationName: 'XCUITest'
[Appium]   browserName: ''
[Appium]   xcodeConfigFile: '/Users/gy/WorkSpaces/UITestDemo/myconfig.xcconfig'
[Appium]   platformName: 'iOS'
[Appium]   udid: 'ea3f18d9e5b2a94be76a99890349e14500a15b7a'
[Appium]   deviceName: '“guafei”的 iPhone'
[Appium]   launchTimeout: 500000
[Appium]   noReset: true
[debug] [XCUITest] XCUITestDriver version: 2.0.26
[BaseDriver] Session created with session id: 600047f4-58ed-41e3-9487-1535d343848b
[debug] [XCUITest] Xcode version set to '8.0'
[debug] [XCUITest] iOS SDK Version set to '10.0'
[debug] [XCUITest] Available devices: ea3f18d9e5b2a94be76a99890349e14500a15b7a
[debug] [XCUITest] Creating iDevice object with udid ea3f18d9e5b2a94be76a99890349e14500a15b7a
[XCUITest] Determining device to run tests on: udid: 'ea3f18d9e5b2a94be76a99890349e14500a15b7a', real device: true
[debug] [XCUITest] Checking whether app is actually present
[XCUITest] Error: Could not find app at com.jg.mgjdev
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at XCUITestDriver.checkAppPresent$ (lib/driver.js:314:11)
    at tryCatch (/Users/gy/WorkSpaces/nvm/versions/node/v4.4.3/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/gy/WorkSpaces/nvm/versions/node/v4.4.3/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/gy/WorkSpaces/nvm/versions/node/v4.4.3/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/gy/WorkSpaces/nvm/versions/node/v4.4.3/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Users/gy/WorkSpaces/nvm/versions/node/v4.4.3/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:108:47)
    at /Users/gy/WorkSpaces/nvm/versions/node/v4.4.3/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:119:28
    at flush (/Users/gy/WorkSpaces/nvm/versions/node/v4.4.3/lib/node_modules/appium/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
 [Error: Could not find app at com.jg.mgjdev]

my env:
(1) xcode 8
(2) ios version: 9.3.4
(3) appium 1.6

please help me ，this problem is bothering me!

**Comment by imurchie** [comment]
Yes. This is a known issue that was fixed. It will be in the next release. You can get it now by re-installing appium with

```
npm uninstall -g appium && npm install -g appium --no-shrinkwrap
```

**Comment by SrinivasanTarget** [comment]
@triager please close
