### ISSUE TITLE
Running Tests on IOS 9 Devices with XCUITest

### ISSUE THREAD

**Issue by tolgatanriverdi** [appium/appium#7049]
Hi I would like to run Tests on IOS 9 devices with using xcuitest(want to use same software to test both ios 10 and ios 9)
It works on IOS10 but when I try to run with IOS9 I get following error:
Does anyone know the reason?

```
[debug] [XCUITest] App is installed.
[debug] [XCUITest] Full reset not requested. No need to install.
[XCUITest] Using default agent: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj
[XCUITest] Using default bootstrap: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Beginning test with command '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/bin/run-xcodebuild.sh --project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj --scheme WebDriverAgentRunner --destination id=a2129c56bd98f89dc1cec9378fb2aef4d8ca462c' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Waiting for WebDriverAgent to start on device
[XCUITest] xcodebuild exited with code '70' and signal 'null'
[XCUITest] Error: xcodebuild failed with code 70
    at SubProcess.<anonymous> (lib/webdriveragent.js:294:25)
    at emitTwo (events.js:87:13)
    at SubProcess.emit (events.js:172:7)
    at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
 [Error: xcodebuild failed with code 70]
[debug] [XCUITest] Running ios real device reset flow
[debug] [XCUITest] Resetting simulator
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: xcodebuild failed with code 70
    at SubProcess.<anonymous> (lib/webdriveragent.js:294:25)
    at emitTwo (events.js:87:13)
    at SubProcess.emit (events.js:172:7)
    at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
[HTTP] <-- POST /wd/hub/session 500 1130 ms - 167 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"automationName":"XCUITest","platformVersion":"10.0","app":"/Users/nts/Desktop/NETAS/Setups/ipas/MTOSApp.ipa","autoAcceptAlerts":true,"showIOSLog":false,"platformName":"iOS","deviceName":"Tolga's iPad","fullReset":false,"browserName":"","realDeviceLogger":"/usr/local/lib/node_modules/deviceconsole/deviceconsole","udid":"a2129c56bd98f89dc1cec9378fb2aef4d8ca462c"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"automationName":"XCUITes...
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   automationName: 'XCUITest'
[Appium]   platformVersion: '10.0'
[Appium]   app: '/Users/nts/Desktop/NETAS/Setups/ipas/MTOSApp.ipa'
[Appium]   autoAcceptAlerts: true
[Appium]   showIOSLog: false
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'Tolga\'s iPad'
[Appium]   fullReset: false
[Appium]   browserName: ''
[Appium]   realDeviceLogger: '/usr/local/lib/node_modules/deviceconsole/deviceconsole'
[Appium]   udid: 'a2129c56bd98f89dc1cec9378fb2aef4d8ca462c'
[debug] [XCUITest] XCUITestDriver version: 2.0.26
[BaseDriver] Session created with session id: ccb6373b-d8a2-499e-8b0a-c9af97ce84bb
[debug] [XCUITest] Xcode version set to '8.0'
[debug] [XCUITest] iOS SDK Version set to '10.0'
[debug] [XCUITest] Available devices: a2129c56bd98f89dc1cec9378fb2aef4d8ca462c, d01c71e5bff18e022248d8e5e218c6bc0bbbfbba
[debug] [XCUITest] Creating iDevice object with udid a2129c56bd98f89dc1cec9378fb2aef4d8ca462c
[XCUITest] Determining device to run tests on: udid: 'a2129c56bd98f89dc1cec9378fb2aef4d8ca462c', real device: true
[BaseDriver] Using local app '/Users/nts/Desktop/NETAS/Setups/ipas/MTOSApp.ipa'
[debug] [BaseDriver] Copying local zip to tmp dir
[debug] [BaseDriver] Unzipping /var/folders/kl/zfs4qq_d119cvqq26x9rt3zc0000gp/T/2016918-9121-17o61yc/appium-app.zip
[debug] [BaseDriver] Testing zip archive: /var/folders/kl/zfs4qq_d119cvqq26x9rt3zc0000gp/T/2016918-9121-17o61yc/appium-app.zip
[BaseDriver] Unzipped local app to '/var/folders/kl/zfs4qq_d119cvqq26x9rt3zc0000gp/T/2016918-9121-17o61yc/Payload/MTOSApp.app'
[debug] [XCUITest] Checking whether app is actually present
[debug] [ios-app-utils] Getting bundle ID from app
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[XCUITest] Setting up real device
[debug] [XCUITest] Stdout from app isInstalled check: [....] Waiting for iOS device to be connected
[....] Using iPad 4 (CDMA) 'Tolga's iPad' (a2129c56bd98f89dc1cec9378fb2aef4d8ca462c).
true

[debug] [XCUITest] App is installed.
[debug] [XCUITest] Full reset not requested. No need to install.
[XCUITest] Using default agent: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj
[XCUITest] Using default bootstrap: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Beginning test with command '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/bin/run-xcodebuild.sh --project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj --scheme WebDriverAgentRunner --destination id=a2129c56bd98f89dc1cec9378fb2aef4d8ca462c' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Waiting for WebDriverAgent to start on device
[XCUITest] xcodebuild exited with code '70' and signal 'null'
[XCUITest] Error: xcodebuild failed with code 70
    at SubProcess.<anonymous> (lib/webdriveragent.js:294:25)
    at emitTwo (events.js:87:13)
    at SubProcess.emit (events.js:172:7)
    at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
 [Error: xcodebuild failed with code 70]
[debug] [XCUITest] Running ios real device reset flow
[debug] [XCUITest] Resetting simulator
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: xcodebuild failed with code 70
    at SubProcess.<anonymous> (lib/webdriveragent.js:294:25)
    at emitTwo (events.js:87:13)
    at SubProcess.emit (events.js:172:7)
    at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
[HTTP] <-- POST /wd/hub/session 500 1077 ms - 167 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"automationName":"XCUITest","platformVersion":"10.0","app":"/Users/nts/Desktop/NETAS/Setups/ipas/MTOSApp.ipa","autoAcceptAlerts":true,"showIOSLog":false,"platformName":"iOS","deviceName":"Tolga's iPad","fullReset":false,"browserName":"","realDeviceLogger":"/usr/local/lib/node_modules/deviceconsole/deviceconsole","udid":"a2129c56bd98f89dc1cec9378fb2aef4d8ca462c"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"automationName":"XCUITes...
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   automationName: 'XCUITest'
[Appium]   platformVersion: '10.0'
[Appium]   app: '/Users/nts/Desktop/NETAS/Setups/ipas/MTOSApp.ipa'
[Appium]   autoAcceptAlerts: true
[Appium]   showIOSLog: false
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'Tolga\'s iPad'
[Appium]   fullReset: false
[Appium]   browserName: ''
[Appium]   realDeviceLogger: '/usr/local/lib/node_modules/deviceconsole/deviceconsole'
[Appium]   udid: 'a2129c56bd98f89dc1cec9378fb2aef4d8ca462c'
[debug] [XCUITest] XCUITestDriver version: 2.0.26
[BaseDriver] Session created with session id: 3074d2bb-b525-4013-a5f7-aad510da1ac1
[debug] [XCUITest] Xcode version set to '8.0'
[debug] [XCUITest] iOS SDK Version set to '10.0'
[debug] [XCUITest] Available devices: a2129c56bd98f89dc1cec9378fb2aef4d8ca462c, d01c71e5bff18e022248d8e5e218c6bc0bbbfbba
[debug] [XCUITest] Creating iDevice object with udid a2129c56bd98f89dc1cec9378fb2aef4d8ca462c
[XCUITest] Determining device to run tests on: udid: 'a2129c56bd98f89dc1cec9378fb2aef4d8ca462c', real device: true
[BaseDriver] Using local app '/Users/nts/Desktop/NETAS/Setups/ipas/MTOSApp.ipa'
[debug] [BaseDriver] Copying local zip to tmp dir
[debug] [BaseDriver] Unzipping /var/folders/kl/zfs4qq_d119cvqq26x9rt3zc0000gp/T/2016918-9121-1f2lbae/appium-app.zip
[debug] [BaseDriver] Testing zip archive: /var/folders/kl/zfs4qq_d119cvqq26x9rt3zc0000gp/T/2016918-9121-1f2lbae/appium-app.zip
[BaseDriver] Unzipped local app to '/var/folders/kl/zfs4qq_d119cvqq26x9rt3zc0000gp/T/2016918-9121-1f2lbae/Payload/MTOSApp.app'
[debug] [XCUITest] Checking whether app is actually present
[debug] [ios-app-utils] Getting bundle ID from app
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[XCUITest] Setting up real device
[debug] [XCUITest] Stdout from app isInstalled check: [....] Waiting for iOS device to be connected
[....] Using iPad 4 (CDMA) 'Tolga's iPad' (a2129c56bd98f89dc1cec9378fb2aef4d8ca462c).
true

[debug] [XCUITest] App is installed.
[debug] [XCUITest] Full reset not requested. No need to install.
[XCUITest] Using default agent: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj
[XCUITest] Using default bootstrap: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Beginning test with command '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/bin/run-xcodebuild.sh --project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj --scheme WebDriverAgentRunner --destination id=a2129c56bd98f89dc1cec9378fb2aef4d8ca462c' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Waiting for WebDriverAgent to start on device
[XCUITest] xcodebuild exited with code '70' and signal 'null'
[XCUITest] Error: xcodebuild failed with code 70
    at SubProcess.<anonymous> (lib/webdriveragent.js:294:25)
    at emitTwo (events.js:87:13)
    at SubProcess.emit (events.js:172:7)
    at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
 [Error: xcodebuild failed with code 70]
[debug] [XCUITest] Running ios real device reset flow
[debug] [XCUITest] Resetting simulator
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: xcodebuild failed with code 70
    at SubProcess.<anonymous> (lib/webdriveragent.js:294:25)
    at emitTwo (events.js:87:13)
    at SubProcess.emit (events.js:172:7)
    at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
[HTTP] <-- POST /wd/hub/session 500 1087 ms - 167 


```

**Comment by mykola-mokhnach** [comment]
In general XCTest works only on iOS 9.3+
Regrading the issue: please set the  **showXcodeLog** capability to true and add the log from there as a gist.

**Comment by imurchie** [comment]
This all looks like iOS 10, too. Unless the device is 9.x

**Comment by asnaith** [comment]
Your desired capability 'platformVersion' is set to 10.0. Maybe try changing this to 9.3 and re-run the test?
