### ISSUE TITLE
Failed to write to /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/iOS: Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “iOS” in the folder “Build”.

### ISSUE THREAD

**Issue by jwingo1015** [appium/appium#7057]
Im trying to run an automation script that was previously running on xcode 7.3 and appium1.5 yet after upgrading to xcode8 and to appium1.6beta i try to kick off the script using a maven command and i receive the following error messages(I am running this on a Mac which is using Sierra):

```
[debug] [XCUITest] Installing app '/Users/***/Library/Developer/Xcode/DerivedData/HomeApp-cuhesnjoubqeomcapzodwhvawgsy/Build/Products/ReleaseSBD_Ref-iphonesimulator/HomeApp.app' on device
[XCUITest] Using default agent: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj
[XCUITest] Using default bootstrap: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Running WebDriverAgent bootstrap script to install dependencies
[XCUITest] Error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1
    at ChildProcess.<anonymous> (lib/teen_process.js:66:19)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:821:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
 { [Error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1]
  stdout: '\u001b[1mFetching dependencies\n*** Downloading KissXML.framework binary at "5.0.5"\n',
  stderr: 'Failed to write to /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/iOS: Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “iOS” in the folder “Build”." UserInfo={NSFilePath=/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/iOS, NSUnderlyingError=0x7fdd484651d0 {Error Domain=NSPOSIXEr[debug] [XCUITest] Running iOS simulator reset flow
[debug] [XCUITest] Shutting down simulator
ro[debug] [iOrDomain Code=1SSim]3 "Pe Killing all iOS Simulatorrmiss
sion denied"}}\n',
  code: 1 }
[debug] [XCUITest] Cleaning simulator state.
[debug] [iOSSim] Cleaning app data files for 'HomeApp.app', 'com.diyzllc.diyz-stage'
[debug] [iOSSim] Building bundle path map
[debug] [iOSSim] Building bundle path map
[debug] [iOSSim] Deleting directory: '/Users/***/Library/Developer/CoreSimulator/Devices/458B5394-2ED0-4864-960D-9D95BDE5DDF1/data/Containers/Data/Application/0C7DFF8D-283D-411D-B32F-1F788B9AD1B6'
[debug] [iOSSim] Deleting directory: '/Users/***/Library/Developer/CoreSimulator/Devices/458B5394-2ED0-4864-960D-9D95BDE5DDF1/data/Containers/Bundle/Application/B60D4C94-DD07-4255-AA5A-A2AA621119FC'
[debug] [iOSSim] Deleting file: '/Users/***/Library/Developer/CoreSimulator/Devices/Library/Preferences/com.diyzllc.diyz-stage.plist'
[debug] [iOSSim] Killing any simulator daemons for 458B5394-2ED0-4864-960D-9D95BDE5DDF1
[iOSSim] Cleaning simulator 458B5394-2ED0-4864-960D-9D95BDE5DDF1
[debug] [XCUITest] Resetting simulator
[debug] [XCUITest] Shutting down simulator
[debug] [iOSSim] Killing all iOS Simulators
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1
    at ChildProcess.<anonymous> (lib/teen_process.js:66:19)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:821:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
[HTTP] <-- POST /wd/hub/session 500 53382 ms - 199 
Tests run: 7, Failures: 1, Errors: 0, Skipped: 6, Time elapsed: 57.681 sec <<< FAILURE! - in TestSuite
setUp(com.mobile.automation.smokeTest.simulator_test.ios_test.Simulator_IosTest)  Time elapsed: 57.53 sec  <<< FAILURE!
org.openqa.selenium.WebDriverException: 
An unknown server-side error occurred while processing the command. Original error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1 (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 53.55 seconds
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'justins-mbp.americas.swk.pri', ip: '10.142.249.201', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12', java.version: '1.8.0_92'
Driver info: io.appium.java_client.ios.IOSDriver
```

**Comment by imurchie** [comment]
You need to have write access to `/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/iOS`. Did you install appium with `sudo`? 

I would change the permissions on the entire `/usr/local/lib/node_modules` or you will have problems with node/npm in general.

**Comment by jwingo1015** [comment]
How would I change the permissions for the entire /usr/local/lib/node_modules?

From: "Isaac A. Murchie"
Reply-To: appium/appium
Date: Wednesday, October 19, 2016 at 2:02 PM
To: appium/appium
Cc: Justin Wingo, Author
Subject: Re: [appium/appium] Failed to write to /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/iOS: Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “iOS” in the folder “B...


You need to have write access to /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/iOS. Did you install appium with sudo?

I would change the permissions on the entire /usr/local/lib/node_modules or you will have problems with node/npm in general.

**Comment by imurchie** [comment]
http://superuser.com/a/260939

**Comment by jwingo1015** [comment]
It worked thanks @imurchie

**Comment by vijayAlapati** [comment]
thanks @imurchie Worked like charm 👍 , now got an other error 😢 need to hunt again 😎

**Comment by chanisasuw** [comment]
It's work for me.

Thank you.

Just compile this command:

> sudo chmod -R 777 /usr/local/lib/node_modules

**Comment by tsalluri** [comment]
I got the same issue and provided permissions but getting another error, could you please analyze what could be it is.

Issue:

[XCUITest] WebDriverAgent started at url 'http://10.68.226.97:8100'
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.apple.mobilesafari","arguments":["-u","http://0.0.0.0:4723/welcome"],"shouldWaitForQuiescence":true}}
[debug] [XCUITest] Unable to start WebDriverAgent session: Unexpected token < in JSON at position 0
[XCUITest] SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at new ProxyRequestError (../../../lib/mjsonwp/errors.js:322:26)
    at JWProxy.proxy$ (../../../lib/jsonwp-proxy/proxy.js:126:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at new ProxyRequestError (../../../lib/mjsonwp/errors.js:322:26)
    at JWProxy.proxy$ (../../../lib/jsonwp-proxy/proxy.js:126:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[debug] [JSONWP Proxy] Proxying [DELETE /session/fced6589-0885-4279-9891-692ebcfb5de6] to [DELETE http://localhost:8100/session/fced6589-0885-4279-9891-692ebcfb5de6] with no body
[MJSONWP] Encountered internal error running command: SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at new ProxyRequestError (../../../lib/mjsonwp/errors.js:322:26)
    at JWProxy.proxy$ (../../../lib/jsonwp-proxy/proxy.js:126:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 69401 ms - 177

**Comment by imurchie** [comment]
@tsalluri That is a proxy issue. You need to make sure you don't need to go through your proxy in order to hit localhost.

**Comment by tsalluri** [comment]
Thank you, I skipped the Proxy. Now it is working fine.

**Comment by malli02422** [comment]
How to Skip the proxy
