### ISSUE TITLE
Could not find app

### ISSUE THREAD

**Issue by bily621** [appium/appium#7071]
## The problem

My steps：
  (1)  npm install -g appium
  (2)  brew install ideviceinstaller
  (3)  brew install carthage
  (4)  npm install -g ios-deploy
  (5)  gem install xcpretty   ---install fail,ignore

then:
  (1) start server -->appium --no-reset
 (2) run the case

result:
  ERROR:org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not find app at com.jg.mgjdev (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 576 milliseconds
## Environment
- Appium version : 1.6
- MAC OS: 10.11.6
- Node.js version :v4.4.3
- IOS version: 9.3.4
- xcode version: 8.0
## Link to Appium logs

```
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"com.jg.mgj...
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   app: 'com.jg.mgjdev'
[Appium]   platformVersion: '9.3.4'
[Appium]   automationName: 'XCUITest'
[Appium]   browserName: ''
[Appium]   xcodeConfigFile: '/Users/gy/WorkSpaces/UITestDemo/myconfig.xcconfig'
[Appium]   platformName: 'iOS'
[Appium]   udid: 'ea3f18d9e5b2a94be76a99890349e14500a15b7a'
[Appium]   deviceName: '“guafei”的 iPhone'
[Appium]   launchTimeout: 500000
[Appium]   noReset: true
[debug] [XCUITest] XCUITestDriver version: 2.0.26
[BaseDriver] Session created with session id: 600047f4-58ed-41e3-9487-1535d343848b
[debug] [XCUITest] Xcode version set to '8.0'
[debug] [XCUITest] iOS SDK Version set to '10.0'
[debug] [XCUITest] Available devices: ea3f18d9e5b2a94be76a99890349e14500a15b7a
[debug] [XCUITest] Creating iDevice object with udid ea3f18d9e5b2a94be76a99890349e14500a15b7a
[XCUITest] Determining device to run tests on: udid: 'ea3f18d9e5b2a94be76a99890349e14500a15b7a', real device: true
[debug] [XCUITest] Checking whether app is actually present
[XCUITest] Error: Could not find app at com.jg.mgjdev
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at XCUITestDriver.checkAppPresent$ (lib/driver.js:314:11)
    at tryCatch (/Users/gy/WorkSpaces/nvm/versions/node/v4.4.3/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/gy/WorkSpaces/nvm/versions/node/v4.4.3/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/gy/WorkSpaces/nvm/versions/node/v4.4.3/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/gy/WorkSpaces/nvm/versions/node/v4.4.3/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Users/gy/WorkSpaces/nvm/versions/node/v4.4.3/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:108:47)
    at /Users/gy/WorkSpaces/nvm/versions/node/v4.4.3/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:119:28
    at flush (/Users/gy/WorkSpaces/nvm/versions/node/v4.4.3/lib/node_modules/appium/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
 [Error: Could not find app at com.jg.mgjdev]
```
## Code To Reproduce Issue [ Good To Have ]

```
DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "");
        capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "9.3.4");
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "“guafei”的 iPhone");
        capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME,"iOS");
        capabilities.setCapability(MobileCapabilityType.APP,"com.jg.mgjdev");
        capabilities.setCapability(MobileCapabilityType.UDID,"ea3f18d9e5b2a94be76a99890349e14500a15b7a");
        capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME,"XCUITest");      capabilities.setCapability("xcodeConfigFile","/Users/gy/WorkSpaces/UITestDemo/myconfig.xcconfig");
        driver = new IOSDriver<>(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
```

myconfig.xcconfig pattern:

```
DEVELOPMENT_TEAM = MEXXXXXGC2
CODE_SIGN_IDENTITY = iPhone Developer: XXX XXX (3XXXX6X6QD)
`
```

**Comment by imurchie** [comment]
This was an issue. It has been [solved](https://github.com/appium/appium-xcuitest-driver/commit/3491fe33a7cffb378c0cf263419d23e40d8dcaf6) and will be in the next release.

To get it now, you can reinstall appium using `npm uninstall -g appium && npm install -g appium --no-shrinkwrap`). When running, you should see a line `[debug] [XCUITest] XCUITestDriver version: 2.0.29` (2.0.29 is the minimum, it could be higher).

**Comment by bily621** [comment]
@imurchie  thank you very much！
The problem has been bothering me for a few days.

**Comment by SrinivasanTarget** [comment]
@triager please close

**Comment by SteveKangQli** [comment]
Updatd the XCUITestDriver to 2.0.37. Still getting unable to find app using BundleID on an IPhone 6Plus running IOS 10.1. Using Appium 1.6 build. If I use ideviceinstaller -l to probe the device for apps, it does report seeing the app that I'm looking for.

**Comment by SteveKSB** [comment]
Updatd the XCUITestDriver to 2.0.37. Still getting unable to find app using BundleID on an IPhone 6Plus running IOS 10.1. Using Appium 1.6 build. If I use ideviceinstaller -l to probe the device for apps, it does report seeing the app that I'm looking for.

**Comment by SteveKSB** [comment]
Updated the XCUITest on Mac OS X/Appium 1.6 to 2.0.37 but still seeing issues with Appium not being to find the BundleID identified app on an IOS 10.1 device. If I run ideviceinstaller -l, I can see the BundleID that's loaded on the same phone.  If I try the same test on an IOS 9.3 device using Appium 1.5.3, it finds the app. Here's the log with the names scrubbed.

[debug] [XCUITest] App is an iOS bundle, will attempt to run as pre-existing
[debug] [XCUITest] Checking whether app 'com.a.a.vplayer' is actually present
[debug] [XCUITest] Reset not set, not ending sim
[HTTP] <-- POST /wd/hub/session 500 468 ms - 189 

[XCUITest] Error: Could not find app at com.a.a.vplayer
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at XCUITestDriver.checkAppPresent$ (../../lib/driver.js:342:11)
    at tryCatch (/usr/local/Cellar/node/7.1.0/libexec/npm/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/Cellar/node/7.1.0/libexec/npm/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/Cellar/node/7.1.0/libexec/npm/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/Cellar/node/7.1.0/libexec/npm/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: Could not find app at com.a.a.vplayer
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at XCUITestDriver.checkAppPresent$ (../../lib/driver.js:342:11)
    at tryCatch (/usr/local/Cellar/node/7.1.0/libexec/npm/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/Cellar/node/7.1.0/libexec/npm/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/Cellar/node/7.1.0/libexec/npm/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/Cellar/node/7.1.0/libexec/npm/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[MJSONWP] Encountered internal error running command: Error: Could not find app at com.a.a.vplayer
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at XCUITestDriver.checkAppPresent$ (../../lib/driver.js:342:11)
    at tryCatch (/usr/local/Cellar/node/7.1.0/libexec/npm/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/Cellar/node/7.1.0/libexec/npm/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/Cellar/node/7.1.0/libexec/npm/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/Cellar/node/7.1.0/libexec/npm/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
