### ISSUE TITLE
urllib2.URLError: <urlopen error [Errno 61] Connection refused>

### ISSUE THREAD

**Issue by awonda** [appium/appium#7079]
my Email: 824265920@qq.com
## The problem

{'deviceName': '192.168.56.101:5555', 'port': '4723',  'platformVersion': '4.4.4\r\n', 'appPackage': 'com.yodao.ee', 'platformName': 'Android', 'appActivity': '.ui.SplashActivity'}

http://localhost:4723/wd/hub

Traceback (most recent call last):
  File "/Users/yuki/Desktop/Autotesting/BuildPackage/android/libs/driver.py", line 75, in <module>

```
#When i try to get webdriver the issue occur......
  The appium server can be started and APP can be installed to mobile, however the error occur, process is finished...
```

```
    myDriver.driver = webdriver.Remote(myDriver.baseUrl, myDriver.desired_caps_B)
  File "build/bdist.macosx-10.11-intel/egg/appium/webdriver/webdriver.py", line 36, in __init__
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 90, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 177, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 234, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 401, in execute
    return self._request(command_info[0], url, body=data)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 471, in _request
    resp = opener.open(request, timeout=self._timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 61] Connection refused>
```

Process finished with exit code 1
## Environment
- Appium version (or git revision) that exhibits the issue:   v1.4.13
- Last Appium version that did not exhibit the issue (if applicable):  
- Desktop OS/version used to run Appium:  10.11.6 macbook pro
- Node.js version (unless using Appium.app|exe):  v0.12.2
- Mobile platform/version under test:   Android 4.4.4
- Real device or emulator/simulator:  both
- Appium CLI or Appium.app|exe:  Appium.app
## Details

Describe in more detail the problem you have been experiencing, if necessary.
## Link to Appium logs

44467 KB/s (10218614 bytes in 0.224s)
info: Welcome to Appium v1.4.13 (REV c75d8adcb66a75818a542fe1891a34260c21f76a)
info: Appium REST http interface listener started on 0.0.0.0:4723
info: [debug] Non-default server args: {"log":"/Users/yuki/Desktop/Autotesting/BuildPackage/android/result/20161023213511/appium.log"}
info: Console LogLevel: debug
info: File LogLevel: debug
sh: line 1:  1569 Terminated: 15          appium.js --log /Users/yuki/Desktop/Autotesting/BuildPackage/android/result/20161023213511/appium.log

Process finished with exit code 0
## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by imurchie** [comment]
The server is crashing, so your test cannot connect.

What command are you running to launch the server?

**Comment by Abundnce10** [comment]
@awonda Did you ever resolve this issue?

I'm getting the same error on my local machine running my Python (2.7) script within a virtualenv (see traceback below).  However, the same script is working within that same virtualenv on my production box.  Can't really figure out why it's not working on my machine.

```python
Traceback (most recent call last):
  File "daily_amazon_metrics.py", line 34, in <module>
    driver = webdriver.Chrome('/usr/local/Cellar/chromedriver/2.19/bin/chromedriver')
  File "/Users/me/Documents/test/Python_Tasks/env/lib/python2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 67, in __init__
    self.quit()
  File "/Users/me/Documents/test/Python_Tasks/env/lib/python2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 82, in quit
    self.service.stop()
  File "/Users/me/Documents/test/Python_Tasks/env/lib/python2.7/site-packages/selenium/webdriver/chrome/service.py", line 100, in stop
    url_request.urlopen("http://127.0.0.1:%d/shutdown" % self.port)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 61] Connection refused>
```

**Comment by imurchie** [comment]
@Abundnce10 Can you provide the server logs (as a [gist](https://gist.github.com)) so we can try to diagnose the problem?

**Comment by Abundnce10** [comment]
Hi @imurchie,

I actually solved the problem.  It looked like my chromedriver was out of date.  I updated it and I no longer received that error.

Thanks!

**Comment by imurchie** [comment]
Excellent!
