### ISSUE TITLE
crash in WebDriverAgent Scripts/bootstrap.sh using webpack

### ISSUE THREAD

**Issue by aheirich** [appium/appium#7089]
## The problem

I have installed appium-xcuitest-driver using npm as well as other packages: webpack, node, Carthage, deviceconsole, ios-deploy.  I am trying to use Appium 1.6.0 to run an IPA built with XCode 8 to run on an iOS 10 device.

When I try to start the Appium Server it hangs forever.  Debugging show the problem comes in try to build the WebDriverAgent using webpack.  From directory /usr/local/lib/node_modules/appium-xcuitest-driver/WebDriverAgent issue the command "/bin/bash Scripts/bootstrap.sh".  This will invoke webpack like so:
$ webpack --progress --colors

and webpack will crash with this

AlansFyusionMBP:Inspector alanheirich$ webpack --progress --colors
Hash: 9ed7d0b85cc08341fd0f  
Version: webpack 1.13.2
Time: 68ms
   [0] multi main 28 bytes {0} [built] [1 error]
    + 1 hidden modules

ERROR in ./js/app.js
Module parse failed: /usr/local/lib/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/js/app.js Unexpected token (59:4)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (59:4)
    at Parser.pp$4.raise (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseParenAndDistinguishExpression (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:1861:32)
    at Parser.pp$3.parseExprAtom (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:1796:19)
    at Parser.pp$3.parseExprSubscripts (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseExpression (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:1573:21)
    at Parser.pp$1.parseReturnStatement (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:839:33)
    at Parser.pp$1.parseStatement (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:699:34)
    at Parser.pp$1.parseBlock (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:981:25)
    at Parser.pp$3.parseFunctionBody (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:2105:24)
    at Parser.pp$3.parseMethod (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:2075:10)
    at Parser.pp$1.parseClassMethod (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:1137:25)
    at Parser.pp$1.parseClass (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:1118:14)
    at Parser.pp$1.parseStatement (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:697:19)
    at Parser.pp$1.parseTopLevel (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/usr/local/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/usr/local/lib/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/usr/local/lib/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/usr/local/lib/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
 @ multi main

## Environment

* Appium 1.6.0
* OS/X El Capitan 10.11.6
* Node.js version (unless using Appium.app|exe): 6.0.0
* Mobile platform/version under test: iOS 10.0.2
* Real device or emulator/simulator: real device

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by aheirich** [comment]
[package.json.txt](https://github.com/appium/appium/files/548824/package.json.txt)
[webpack.config.js.txt](https://github.com/appium/appium/files/548825/webpack.config.js.txt)

Here are two files that control the webpack process

[app.js.txt](https://github.com/appium/appium/files/548827/app.js.txt)

Here is the file that is complained about in the error at line 59.  It contains an HTML construct <div> inside a Javascript file.  This seems to be the root of the problem, webpack claims we need a different loader to handle this file.  I don't know what to use, I have tried html-loader without success.  By default this uses babel-loader.

**Comment by imurchie** [comment]
Appium uses the `-d` flag, so webpack is not an issue.

Can you provide the Appium server logs? Otherwise there is nothing I can do.

**Comment by aheirich** [comment]
Isaac, I need some advice for how to capture this, could be correspond directly? aheirich@fyusion.com

**Comment by imurchie** [comment]
When you run the appium command, it will produce output. This is what I need to look at.

**Comment by aheirich** [comment]
I do not run the Appium command directly, it is run by a test infrastructure.
Here is the console output, done know whether this will help
[appium_console.txt](https://github.com/appium/appium/files/548940/appium_console.txt)

**Comment by imurchie** [comment]
No, that is not enough. The logs should start with something like

```
[Appium] Welcome to Appium v1.6.0 (REV 2176894a5be5da17a362bf3f20678641a78f4b69)
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
```

And continue with session creation once the command comes in (triggered by the `new IOSDriver()`). I don't know where they would be in your test runner.

**Comment by aheirich** [comment]
[appium.log.txt](https://github.com/appium/appium/files/548979/appium.log.txt)

found it

**Comment by imurchie** [comment]
This is the important line:

```
2016-10-24 20:44:10:987 - error: [XCUITest] The real device logger 'idevicesyslog' was unable to start log capture. Please try installing 'deviceconsole' ('npm install -g deviceconsole') and specify the path to it using the 'realDeviceLogger' capability.
```

Follow the instructions about `deviceconsole` here: https://github.com/appium/appium-xcuitest-driver/#external-dependencies

**Comment by aheirich** [comment]
yep
actually i had installed it but had not set the capability to point to it
that was the issue
thank you

**Comment by omkara120120** [comment]
Hello,

@imurchie  @aheirich 
How did u fixed the following issue  ?

- ERROR in ./js/app.js
Module parse failed: /usr/local/lib/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/js/app.js Unexpected token (59:4)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (59:4) ?

"error: [XCUITest] The real device logger 'idevicesyslog' was unable to start log capture. Please try installing 'deviceconsole' ('npm install -g deviceconsole') and specify the path to it using the 'realDeviceLogger' capability."  - this error is not there in my log

**Comment by imurchie** [comment]
@omkara120120 Where is the error coming up?

**Comment by omkara120120** [comment]
Steps I did:
1. opened terminal 
2. cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/
3. ./Scripts/bootstrap.sh

then error is coming up

if I run $ ./Scripts/bootstrap.sh **- d** , then output is only

-e Fetching dependencies

and then it returns to $ prompt

**Comment by imurchie** [comment]
That is the expected output of running `./Scripts/bootstrap.sh - d` a second time. If you want it to do something, you can run `rm -rf Carthage && ./Scripts/bootstrap.sh - d`.

Appium does not use the Inspector. Running that script without `-d` is unsupported by us.

**Comment by omkara120120** [comment]
Now the steps I am doing - 
1. opened terminal
2. cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/
3. ./Scripts/bootstrap.sh -d
    Output : -e Fetching dependencies
4. Started appium using - appium command 
5. run the code in eclipse 
6. waited for application to get launch and then opened - http://localhost:8100/inspector this link in browser 

Issue - 
Complete blank webpage - neither inspector screen was displayed nor any error message

**Comment by imurchie** [comment]
Please open a new issue with the logs and all information the issue template asks for. This is not related to the issue at hand.

**Comment by omkara120120** [comment]
Ok Thanks

**Comment by pavanbachu0604** [comment]
Try installing web pack , npm install -g webpack

**Comment by Trisha1212** [comment]
I faced same issues. I re-run below command and it resolved 
brew install libimobiledevice --HEAD  # install from HEAD to get important updates
brew install ideviceinstaller         # only works for ios 9. for ios 10, see below
brew install carthage
npm install -g ios-deploy
gem install xcpretty

**Comment by antovrv** [comment]
I too faced the same issue. If it's not working even after the installation of the above packages mentioned by @Trisha1212, Just do restart the machine once. It solved the problem for me.

**Comment by sharathkonda** [comment]
> That is the expected output of running `./Scripts/bootstrap.sh - d` a second time. If you want it to do something, you can run `rm -rf Carthage && ./Scripts/bootstrap.sh - d`.
> 
> Appium does not use the Inspector. Running that script without `-d` is unsupported by us.

Thanks, issue fixed by this step.
