### ISSUE TITLE
Command 'idevice_id -l' errored out: Error: spawn idevice_id ENOENT

### ISSUE THREAD

**Issue by srkannan** [appium/appium#7096]
## The problem

[XCUITest] Error: Command 'idevice_id -l' errored out: Error: spawn idevice_id ENOENT
    at exports._errnoException (util.js:1036:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at ChildProcess.<anonymous> (lib/teen_process.js:32:14)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
## Environment
- Appium version (or git revision) that exhibits the issue:1.6.0-beta3
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium: OS X El Capitan 10.11.6
- Node.js version (unless using Appium.app|exe):v6.7.0
- Mobile platform/version under test:iOS 10.1
- Real device or emulator/simulator:Real device
- Appium CLI or Appium.app|exe:

**Comment by crujzo** [comment]
Which Xcode version r u using?

**Comment by imurchie** [comment]
Do you have `libimobiledevice` installed? Please install it using `brew install libimobiledevice --HEAD`. This will install `idevice_id`.

**Comment by crujzo** [comment]
Hi Imurchie,
i have libimobiledevice installed 
drwxr-xr-x  3   admin   102B Oct 27 11:56 ios-webkit-debug-proxy
drwxr-xr-x  3   admin   102B Oct 27 15:47 libimobiledevice

using Xcode 8, iphone version 10.0, appium 1.6.0 installed via npm

but still i am getting :
[XCUITest] Error: Command 'idevice_id -l' errored out: Error: spawn idevice_id ENOENT
at exports._errnoException (util.js:1026:11).....
Tried to uninstall and reinstall libimobiledevice and reverting back to Xcode 7.3 as suggested in may support posts online but all gone in vain.

Please help.

**Comment by imurchie** [comment]
Is it available on your path? What happens if you run `idevice_id -l`?

**Comment by crujzo** [comment]
Thanks for the reply Imurchie.

**Yes it is available and when i run 'idevice_id -l' i get the device's 40 digit UDID but still same error while instantiating my iOS driver from Eclipse using java  :** 

node version 6.8.1 

[Appium] Capabilities:
[Appium]   app: '/Volumes/Automation/XXXX.ipa'
[Appium]   noReset: true
[Appium]   newCommandTimeout: 900
[Appium]   platformVersion: '10.0'
[Appium]   bundleId: 'com.appster.XXXX'
[Appium]   platformName: 'iOS'
[Appium]   udid: '6aaf5b44904XXXX505b54XX5c09XXXX1208eed7d'
[Appium]   deviceName: 'iPhone 6'
[Appium]   autoAcceptAlerts: true
[debug] [XCUITest] XCUITestDriver version: 2.0.26
[BaseDriver] Session created with session id: 5435bee9-7d0b-4cff-b25b-c4b26a5d9310
[debug] [XCUITest] Xcode version set to '8.0'
[debug] [XCUITest] iOS SDK Version set to '10.0'


**Also i am getting this issue regarding Desired Capabilities:**
 [HTTP] --> POST /wd/hub/session {"capabilities":{"desiredCapabilities":{"app":"/Volumes/Automation/XXXX.ipa","noReset":true,"newCommandTimeout":900,"platformVersion":"10.0","bundleId":"com.YYYY.XXXX","platformName":"iOS","udid":"6aaf5b4490XXXXX505b54025XXX5786120XXXX7d","deviceName":"iPhone 6","autoAcceptAlerts":true},"requiredCapabilities":null},"desiredCapabilities":{"app":"/Volumes/Automation/HomeHero.ipa","noReset":true,"newCommandTimeout":900,"platformVersion":"10.0","bundleId":"com.appster.HomeHero","platformName":"iOS","udid":"6aaf5b44904835f505b54025c0957861208eed7d","deviceName":"iPhone 6","autoAcceptAlerts":true},"requiredCapabilities":null}
**[debug] [MJSONWP] Bad parameters: BadParametersError: Parameters were incorrect. We wanted {"required":["desiredCapabilities"],"optional":["requiredCapabilities","sessionId","id"]} and you sent ["capabilities","desiredCapabilities","requiredCapabilities"]
[HTTP] <-- POST /wd/hub/session 400 4 ms - 201** 

I am not able to understand why i am getting BadParametersError although in my knowledge i am using all the correct values and i am not able to launch appium inspector also it says "**not able to create a new session**"

Your help would be highly appreciated.

**Comment by mykola-mokhnach** [comment]
@crujzo Could you please try stable Appium version instead of beta. It would be also useful to see how capabilities are set in the code.

**Comment by imurchie** [comment]
Ah. If you are running from within Eclipse then the problem is probably the PATH within the IDE. Make sure that the `idevice_id` program is available there.

**Comment by imurchie** [comment]
Your client is sending a `"capabilities"` entry in the create session command. The server does not recognize this. What is your client library?

**Comment by crujzo** [comment]
@imurchie 
i am using <dependency>
    	<groupId>io.appium</groupId>
    	<artifactId>java-client</artifactId>
    	<version>4.1.2</version>
    </dependency>
also i have added : PATH = /usr/local/bin:/bin:/usr/local/Cellar:/usr/local/Cellar/libimobiledevice/HEAD-2c16751/bin in Eclipse Evn variable.

**Comment by crujzo** [comment]
@mykola-mokhnach 
i have installed appium  via npm, does that not download latest version by default?
coz the version i am getting is 1.6.0

**Comment by mykola-mokhnach** [comment]
@crujzo for now it is, but you've stated beta3 in the issue details.

So, how about the code where capabilities are set?

**Comment by crujzo** [comment]
@mykola-mokhnach 
actually it was the question from @srkannan probably he was using bets 3 version
the code for setting capabilities : 

if(platformInfoObject.PlatformName.equalsIgnoreCase("iOS")){
					
						AppiumDriver<WebElement> driver = null;
						DesiredCapabilities capabilities = new DesiredCapabilities();
						capabilities.setCapability("platformName", platformInfoObject.PlatformName);
						capabilities.setCapability("platformVersion", "9.3.5");
						capabilities.setCapability("deviceName", "OIT-MIO00040");
						capabilities.setCapability("udid", platformInfoObject.PlatformID);
						capabilities.setCapability("newCommandTimeout", 900);
						capabilities.setCapability("bundleId", "com.YYYYY.XXXXXXXX");
						capabilities.setCapability("autoAcceptAlerts", true);
						capabilities.setCapability("noReset", true);
						capabilities.setCapability("app", platformInfoObject.AppPath);
						driver = new IOSDriver<WebElement>(new URL("http://"+platformInfoObject.ServerURL+":"+platformInfoObject.ServerPortNumber+"/wd/hub"), capabilities);
						driver.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS);
						return driver;
					}

**Comment by mykola-mokhnach** [comment]
@crujzo setup looks good. Try to update _java-client_ version. I suppose the problem might be there.

**Comment by srkannan** [comment]
I'm using XCOde Version 8.1 (8T61a).
I'm not getting this error any more. I will open a new issue for the different error.

**Comment by crujzo** [comment]
Hi Guys, Please help.
I am getting this error:
Finding XcodePath by symlink because Error: Command 'xcode-select --print-path' errored out: Error: spawn xcode-select ENOENT

Any idea Why this error is coming..

**Comment by imurchie** [comment]
Please start a new issue. This is not the same problem, so it makes using the issues difficult if things are mixed up. Thanks!

**Comment by rkn411** [comment]
@imurchie @jlipps debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1496138807568 (15:36:47 GMT+0530 (IST))
[XCUITest] The 'idevice_id' program is not installed. If you are running a real device test it is necessary. Install with 'brew install libimobiledevice --HEAD'
[debug] [XCUITest] Available devices: 
[XCUITest] Error: Unknown device or simulator UDID: 'fc96ef28f6d5956071cda176c7f5a843a05e183a'
    at XCUITestDriver.determineDevice$ (../../lib/driver.js:604:17)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: Unknown device or simulator UDID: 'fc96ef28f6d5956071cda176c7f5a843a05e183a'
    at XCUITestDriver.determineDevice$ (../../lib/driver.js:604:17)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[MJSONWP] Encountered internal error running command: Error: Unknown device or simulator UDID: 'fc96ef28f6d5956071cda176c7f5a843a05e183a'
    at XCUITestDriver.determineDevice$ (../../lib/driver.js:604:17)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[HTTP] <-- POST /wd/hub/session 500 5139 ms - 213

**Comment by rkn411** [comment]
/usr/local/Cellar/libimobiledevice/HEAD-9df4e69
i had my advice_is in the mentioned path installed through  'brew install libimobiledevice --HEAD'
but i m facing same issue to launch and install app in real device through programmatically


[debug] [XCUITest] Available devices: @imurchie @jlipps 
** @[XCUITest] Error: Unknown device or simulator UDID:** 'fc96ef28f6d5956071cda176c7f5a843a05e183a'
    at XCUITestDriver.determineDevice$ (../../lib/driver.js:604:17)

**Comment by imurchie** [comment]
@rkn411 This does not look like the same issue. Please open a new issue and provide the information asked for.
