### ISSUE TITLE
1.6.0: Could not determine Xcode version.

### ISSUE THREAD

**Issue by mashek347** [appium/appium#7134]
Eclips error:

```
[TestNG] Running:
  /private/var/folders/z3/tkbh3cns4fd4fyd6xsdgk1bh68_4ff/T/testng-eclipse-1803168927/testng-customsuite.xml

Output Excel File Path - /Users/502000533/Documents/Automation/workspace/genworth.apacherule/FinalOutPut/OutPutFile_10312016_114151.xls
log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
log4j:WARN Please initialize the log4j system properly.
FAILED CONFIGURATION: @BeforeMethod setUp
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not determine Xcode version. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 228 milliseconds
Build info: version: '2.47.0', revision: '0e4837e94b1fad0db93e88cd972ed3e235a22892', time: '2015-07-29 15:58:41'
System info: host: 'GNWRICA2080432', ip: '10.22.206.51', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12', java.version: '1.8.0_91'
Driver info: io.appium.java_client.ios.IOSDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:595)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:43)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:242)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:128)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:141)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:39)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:69)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:78)
	at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:55)
	at com.genworth.apacherule.CompareURLTestCaseRealDevice.setUp(CompareURLTestCaseRealDevice.java:179)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:585)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)

SKIPPED CONFIGURATION: @AfterMethod afterMethod
SKIPPED CONFIGURATION: @BeforeMethod setUp
SKIPPED CONFIGURATION: @AfterMethod afterMethod
SKIPPED CONFIGURATION: @BeforeMethod setUp
SKIPPED CONFIGURATION: @AfterMethod afterMethod
SKIPPED CONFIGURATION: @BeforeMethod setUp
SKIPPED CONFIGURATION: @AfterMethod afterMethod
SKIPPED CONFIGURATION: @BeforeMethod setUp
SKIPPED CONFIGURATION: @AfterMethod afterMethod
SKIPPED CONFIGURATION: @BeforeMethod setUp
SKIPPED CONFIGURATION: @AfterMethod afterMethod
SKIPPED CONFIGURATION: @BeforeMethod setUp
SKIPPED CONFIGURATION: @AfterMethod afterMethod
SKIPPED CONFIGURATION: @BeforeMethod setUp
SKIPPED CONFIGURATION: @AfterMethod afterMethod
SKIPPED CONFIGURATION: @BeforeMethod setUp
SKIPPED CONFIGURATION: @AfterMethod afterMethod
SKIPPED CONFIGURATION: @BeforeMethod setUp
SKIPPED CONFIGURATION: @AfterMethod afterMethod
SKIPPED CONFIGURATION: @BeforeMethod setUp
SKIPPED CONFIGURATION: @AfterMethod afterMethod
SKIPPED CONFIGURATION: @BeforeMethod setUp
SKIPPED CONFIGURATION: @AfterMethod afterMethod
SKIPPED CONFIGURATION: @BeforeMethod setUp
SKIPPED CONFIGURATION: @AfterMethod afterMethod
SKIPPED CONFIGURATION: @BeforeMethod setUp
SKIPPED CONFIGURATION: @AfterMethod afterMethod
SKIPPED CONFIGURATION: @AfterClass tearDown
SKIPPED: urlvalidator("1", "https://www.genworth.com/claims//tools-and-forms/claims/annuity-claims/variable-annuity-legal-entity-selector.html --- URL is not working", org.testng.TestRunner@5e2c3d18)
SKIPPED: urlvalidator("2", "https://www.genworth.com/claims//tools-and-forms/claims/life-insurance-claims/life-insurance-claims0-postableForm.html __ Is not working", org.testng.TestRunner@5e2c3d18)
SKIPPED: urlvalidator("3", "https://www.genworth.com/products/immediate-need-annuity/paying-for-care-consultation.html --- Is not working", org.testng.TestRunner@5e2c3d18)
SKIPPED: urlvalidator("4", "https://www.genworth.com/lets-talk/ltc/talking-to-loved-ones/tips-and-insights.html --- Image is missing", org.testng.TestRunner@5e2c3d18)
SKIPPED: urlvalidator("5", "https://www.genworth.com/corporate/newsroom.html", org.testng.TestRunner@5e2c3d18)
SKIPPED: urlvalidator("6", "https://www.genworth.com/long-term-care-insurance/il/make-a-plan/ltc-insurance-calculator.html", org.testng.TestRunner@5e2c3d18)
SKIPPED: urlvalidator("7", "http://genworth.com/login.html", org.testng.TestRunner@5e2c3d18)
SKIPPED: urlvalidator("8", "https://www.genworth.com/claims//tools-and-forms/claims/annuity-claims.html", org.testng.TestRunner@5e2c3d18)
SKIPPED: urlvalidator("9", " https://www.genworth.com/claims//tools-and-forms/claims/annuity-claims/annuity-claims-faq.html", org.testng.TestRunner@5e2c3d18)
SKIPPED: urlvalidator("10", "https://www.genworth.com/claims//tools-and-forms/claims/life-insurance-claims.html", org.testng.TestRunner@5e2c3d18)
SKIPPED: urlvalidator("11", "https://www.genworth.com/claims//tools-and-forms/claims/life-insurance-claims/life-insurance-claims.html", org.testng.TestRunner@5e2c3d18)
SKIPPED: urlvalidator("12", "https://www.genworth.com/claims//tools-and-forms/claims/long-term-care-insurance/long-term-care-history.html", org.testng.TestRunner@5e2c3d18)
SKIPPED: urlvalidator("13", "https://www.genworth.com/content/pro/us/en/home.html", org.testng.TestRunner@5e2c3d18)
SKIPPED: urlvalidator("14", "https://www.genworth.com/long-term-care-insurance/al.html#tab2-tab", org.testng.TestRunner@5e2c3d18)

===============================================
    Default test
    Tests run: 14, Failures: 0, Skips: 14
    Configuration Failures: 1, Skips: 28
===============================================


===============================================
Default suite
Total tests run: 14, Failures: 0, Skips: 14
Configuration Failures: 1, Skips: 28
===============================================

[TestNG] Time taken by org.testng.reporters.EmailableReporter2@2d554825: 9 ms
[TestNG] Time taken by org.testng.reporters.JUnitReportReporter@327471b5: 44 ms
[TestNG] Time taken by org.testng.reporters.jq.Main@64616ca2: 56 ms
[TestNG] Time taken by org.testng.reporters.XMLReporter@1e67b872: 45 ms
[TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@42d3bd8b: 36 ms
[TestNG] Time taken by [FailedReporter passed=0 failed=0 skipped=0]: 10 ms
```

Appium error:
```
Last login: Mon Oct 31 12:53:05 on ttys001
GNWRICA2080432:~ 502000533$ appium &
[1] 32039
GNWRICA2080432:~ 502000533$ [Appium] Welcome to Appium v1.6.0
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"io.appium.SafariLauncher","safariIgnoreFraudWarning":true,"platformVersion":"10.1","safariAllowPopups":false,"automationName":"XCUITest","browserName":"safari","platformName":"iOS","udid":"a132919a4b4c2c393ea15f7860fe8ae1e3d6f1e9","deviceName":"iPhone 6"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"io.appium.SafariLa...
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   app: 'io.appium.SafariLauncher'
[Appium]   safariIgnoreFraudWarning: true
[Appium]   platformVersion: '10.1'
[Appium]   safariAllowPopups: false
[Appium]   automationName: 'XCUITest'
[Appium]   browserName: 'safari'
[Appium]   platformName: 'iOS'
[Appium]   udid: 'a132919a4b4c2c393ea15f7860fe8ae1e3d6f1e9'
[Appium]   deviceName: 'iPhone 6'
[debug] [XCUITest] XCUITestDriver version: 2.0.26
[BaseDriver] Session created with session id: c73916f1-652a-42ad-990e-da3c0f782a8e
[XCUITest] Error: Could not determine Xcode version.
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at getAndCheckXcodeVersion$ (lib/utils.js:37:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:108:47)
    at /usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:119:28
    at flush (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
 [Error: Could not determine Xcode version.]
[XCUITest] Error: Could not determine Xcode version.
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at getAndCheckXcodeVersion$ (lib/utils.js:37:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:108:47)
    at /usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:119:28
    at flush (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
 [Error: Could not determine Xcode version.]
[debug] [XCUITest] Running iOS simulator reset flow
[MJSONWP] Encountered internal error running command: Error: Could not determine Xcode version.
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at getAndCheckXcodeVersion$ (lib/utils.js:37:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:108:47)
    at /usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:119:28
    at flush (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
[HTTP] <-- POST /wd/hub/session 500 118 ms - 171 
```

Please help to fix the issue

**Comment by mykola-mokhnach** [comment]
@mashek347 Please describe the problem properly like the issue template requires it. The current description is unclear.

**Comment by sankritraj** [comment]
i am facing same issue

[MJSONWP] Calling AppiumDriver.createSession() with args: [{"newCommandTimeout":1200,...
[Appium] Creating new IosDriver session
[Appium] Capabilities:
[Appium]   newCommandTimeout: 1200
[Appium]   platformVersion: '9.3.1'
[Appium]   bundleId: 'com.myuvo.k900'
[Appium]   udid: 'cf8836697b4b1acc25186e4ca8cfc80fe9e74206'
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'iPhone 5S'
[Appium]   autoAcceptAlerts: 'true'
[BaseDriver] Capability 'autoAcceptAlerts' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] Session created with session id: 3fb869a2-f5f1-4d9a-81af-ec292d35e0ae
[iOS] Could not determine Xcode version.
[MJSONWP] Encountered internal error running command: Error: Could not find path to Xcode by symlinks located in /var/db/xcode_select_link, or /usr/share/xcode-select/xcode_dir_link
    at getPathFromSymlink$ (lib/xcode.js:66:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 20 ms - 257 
cc



Here started appium and trying to run script

**Comment by imurchie** [comment]
@mashek347 Can you update Appium? The error messaging around this has been fixed to give more information.

```
npm uninstall -g appium
npm install -g appium@beta
```

@sankritraj If you are using Xcode 8+ you will need to specify `automationName` of `XCUITest`.

**Comment by SrinivasanTarget** [comment]
Closing this because of inactivity. Please check from terminal `xcodebuild -version` and it detects proper version or not.
