### ISSUE TITLE
Appium 1.6 beta commands not working from Remote Windows PC

### ISSUE THREAD

**Issue by Nesaganesh** [appium/appium#7152]
I need to run the below command from remote windows 10 PC, I have used putty.exe and logged in as a Macmini user who has the admin rights. When I run the below command its not working throwing me a Code singning issues, can someone please have a look and let me know some solutions.

**Commands**
node appium -a 192.168.59.124 -p 4463 --bootstrap-port 4463 --nodeconfig /Users/matthewdavid/Documents/Nodes/IOS10Safari.json -U 4625d558cb0644ea3447352bdfd3d0db2451167c --native-instruments-lib --no-reset --app /Applications/Appium.app/Contents/Resources/node_modules/appium/Betway.ipa --show-ios-log --tmp /tmp/ios/ --keystore-path  /Users/admin/Library/Keychains/login.keychain --keystore-password C0d3Ninja ;/bin/bash

**Logs**
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   buldleId: 'none'
[Appium]   realDeviceLogger: '/usr/local/lib/node_modules/deviceconsole/deviceconsole'
[Appium]   platformVersion: '10.1'
[Appium]   automationName: 'XCUITest'
[Appium]   browserName: 'Safari'
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'Matthew\'s iPhone'
[Appium]   wdaLocalPort: '8200'
[Appium]   app: '/Applications/Appium.app/Contents/Resources/node_modules/appium/Betway.ipa'
[Appium]   udid: '4625d558cb0644ea3447352bdfd3d0db2451167c'
[Appium]   noReset: true
[Appium]   nativeInstrumentsLib: true
[Appium]   showIOSLog: true
[debug] [XCUITest] XCUITestDriver version: 2.0.34
[BaseDriver] Capability 'wdaLocalPort' changed from string ('8200') to integer (8200). This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by appium: buldleId.
[BaseDriver] Session created with session id: 6b334eee-8651-4eb2-a9e7-d44dcd1f24f6
[debug] [XCUITest] Xcode version set to '8.1'
[debug] [XCUITest] iOS SDK Version set to '10.1'
[debug] [XCUITest] Available devices: 4625d558cb0644ea3447352bdfd3d0db2451167c
[debug] [XCUITest] Creating iDevice object with udid 4625d558cb0644ea3447352bdfd3d0db2451167c
[XCUITest] Determining device to run tests on: udid: '4625d558cb0644ea3447352bdfd3d0db2451167c', real device: true
[XCUITest] Safari test requested
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[XCUITest] Setting up real device
[XCUITest] Using default agent: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj
[XCUITest] Using default bootstrap: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Using real device logger '/usr/local/lib/node_modules/deviceconsole/deviceconsole'
[debug] [XCUITest] Beginning test with command '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/bin/run-xcodebuild.sh --project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj --scheme WebDriverAgentRunner --destination id=4625d558cb0644ea3447352bdfd3d0db2451167c' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Waiting for WebDriverAgent to start on device
[HTTP] --> GET /wd/hub/status {}
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [XCUITest] Log file for xcodebuild test: /Users/matthewdavid/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/41657025-57A3-4577-8B30-F384E1EEA0EF/Session-WebDriverAgentRunner-2016-11-02_143321-PUdEvS.log
[Xcode] 2016-11-02 14:33:27.967 xcodebuild[82560:459467] Error Domain=IDETestOperationsObserverErrorDomain Code=3 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/matthewdavid/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/41657025-57A3-4577-8B30-F384E1EEA0EF/Session-WebDriverAgentRunner-2016-11-02_143321-PUdEvS.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/matthewdavid/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/41657025-57A3-4577-8B30-F384E1EEA0EF/Session-WebDriverAgentRunner-2016-11-02_143321-PUdEvS.log}

[Xcode]
Testing failed:

[Xcode]         No signing certificate "iOS Development" found:  No "iOS Development" signing certificate matching team ID "MYZ7FZLZHN" with a private key was found.
** TEST FAILED **

The following build commands failed:
        Check dependencies
(1 failure)

[XCUITest] xcodebuild exited with code '1' and signal 'null'
[XCUITest] Error: xcodebuild failed with code 1
    at SubProcess.<anonymous> (../../lib/webdriveragent.js:294:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
 Error: xcodebuild failed with code 1
    at SubProcess.<anonymous> (../../lib/webdriveragent.js:294:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[XCUITest] Shutting down WebDriverAgent

**Comment by mykola-mokhnach** [comment]
Use driver capabilities _keychainPath_ and _keychainPassword_ to properly set signing options.. See https://github.com/appium/appium-xcuitest-driver#usage for more details.

**Comment by Nesaganesh** [comment]
I just tried this but it doesnt seems to be working, is the 


bash-3.2$ export PATH=${PATH}:/usr/local/bin; cd /usr/local/lib/node_modules && node appium --safari -a 192.168.59.124 -p 4463 --bootstrap-port 4463 --nodeconfig /Users/matthewdavid/Documents/Nodes/IOS10Safari.json --webkit-debug-proxy-port 27753 -U 4625d558cb0644ea3447352bdfd3d0db2451167c --tmp /tmp/ios/
[Appium] Welcome to Appium v1.6.0-beta3
[Appium] Non-default server args:
[Appium]   address: '192.168.59.124'
[Appium]   port: 4463
[Appium]   bootstrapPort: 4463
[Appium]   safari: true
[Appium]   nodeconfig: '/Users/matthewdavid/Documents/Nodes/IOS10Safari.json'
[Appium]   tmpDir: '/tmp/ios/'
[Appium]   udid: '4625d558cb0644ea3447352bdfd3d0db2451167c'
[Appium] Deprecated server args:
[Appium]   -U,--udid => --default-capabilities '{"udid":"4625d558cb0644ea3447352bdfd3d0db2451167c"}'
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   udid: '4625d558cb0644ea3447352bdfd3d0db2451167c'
[debug] [Appium] Starting auto register thread for grid. Will try to register every 5000 ms.
[Appium] Appium REST http interface listener started on 192.168.59.124:4463
[debug] [Appium] Appium successfully registered with the grid on 192.168.59.124:4444
[HTTP] --> GET /wd/hub/status {}
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.0-beta3","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 21 ms - 89
[HTTP] --> GET /wd/hub/status {}
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.0-beta3","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 12 ms - 89
[HTTP] --> GET /wd/hub/status {}
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.0-beta3","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 13 ms - 89
[HTTP] --> GET /wd/hub/status {}
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.0-beta3","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 13 ms - 89
[HTTP] --> GET /wd/hub/status {}
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.0-beta3","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 11 ms - 89
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"buldleId":"none","realDeviceLogger":"/usr/local/lib/node_modules/deviceconsole/deviceconsole","platformVersion":"10.1","automationName":"XCUITest","keychainPath":"/Users/matthewdavid/Library/Keychains/login.keychain","browserName":"Safari","keychainPassword":"C0d3Ninja","platformName":"iOS","deviceName":"Matthew's iPhone","wdaLocalPort":"8200"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"buldleId":"none","realDeviceLogger":"/usr/local/lib/node_modules/deviceconsole/deviceconsole","platformVersion":"10.1","automationName":"XCUITest","keychainPath":"/Users/matthewdavid/Library/Keychains/login.keychain","browserName":"Safari","key...
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   buldleId: 'none'
[Appium]   realDeviceLogger: '/usr/local/lib/node_modules/deviceconsole/deviceconsole'
[Appium]   platformVersion: '10.1'
[Appium]   automationName: 'XCUITest'
[Appium]   keychainPath: '/Users/matthewdavid/Library/Keychains/login.keychain'
[Appium]   browserName: 'Safari'
[Appium]   keychainPassword: 'PASSWORDDELETED'
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'Matthew\'s iPhone'
[Appium]   wdaLocalPort: '8200'
[Appium]   udid: '4625d558cb0644ea3447352bdfd3d0db2451167c'
[debug] [XCUITest] XCUITestDriver version: 2.0.34
[BaseDriver] Capability 'wdaLocalPort' changed from string ('8200') to integer (8200). This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by appium: buldleId.
[BaseDriver] Session created with session id: 04878440-1c9e-4f88-a307-5a8a6e237deb
[debug] [XCUITest] Xcode version set to '8.1'
[debug] [XCUITest] iOS SDK Version set to '10.1'
[debug] [XCUITest] Available devices: 4625d558cb0644ea3447352bdfd3d0db2451167c
[debug] [XCUITest] Creating iDevice object with udid 4625d558cb0644ea3447352bdfd3d0db2451167c
[XCUITest] Determining device to run tests on: udid: '4625d558cb0644ea3447352bdfd3d0db2451167c', real device: true
[XCUITest] Safari test requested
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[XCUITest] Setting up real device
[XCUITest] Using default agent: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj
[XCUITest] Using default bootstrap: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Using real device logger '/usr/local/lib/node_modules/deviceconsole/deviceconsole'
[debug] [XCUITest] Beginning test with command '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/bin/run-xcodebuild.sh --project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj --scheme WebDriverAgentRunner --destination id=4625d558cb0644ea3447352bdfd3d0db2451167c --keychain-path /Users/matthewdavid/Library/Keychains/login.keychain --keychain-password C0d3Ninja' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Waiting for WebDriverAgent to start on device
[HTTP] --> GET /wd/hub/status {}
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [XCUITest] Log file for xcodebuild test: /Users/matthewdavid/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/DDFE63F0-05A4-4BD0-967D-13DE9DC84C22/Session-WebDriverAgentRunner-2016-11-02_162942-WM16LD.log
[Xcode] 2016-11-02 16:29:50.580 xcodebuild[84802:500289] Error Domain=IDETestOperationsObserverErrorDomain Code=3 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/matthewdavid/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/DDFE63F0-05A4-4BD0-967D-13DE9DC84C22/Session-WebDriverAgentRunner-2016-11-02_162942-WM16LD.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/matthewdavid/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/DDFE63F0-05A4-4BD0-967D-13DE9DC84C22/Session-WebDriverAgentRunner-2016-11-02_162942-WM16LD.log}

[Xcode]
Testing failed:
        No signing certificate "iOS Development" found:  No "iOS Development" signing certificate matching team ID "MYZ7FZLZHN" with a private key was found.

[Xcode] ** TEST FAILED **


The following build commands failed:
        Check dependencies
(1 failure)

[XCUITest] xcodebuild exited with code '1' and signal 'null'
[XCUITest] Error: xcodebuild failed with code 1
    at SubProcess.<anonymous> (../../lib/webdriveragent.js:294:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
 Error: xcodebuild failed with code 1

**Comment by mykola-mokhnach** [comment]
Provide _xcodeConfigFile_ capability as well

**Comment by Nesaganesh** [comment]
I did that as well, still I am not able to get through, please help

**Capabilites**
var capabilities = new DesiredCapabilities();
            capabilities.SetCapability(CapabilityType.BrowserName, "Safari");
            capabilities.SetCapability("automationName", "XCUITest");
            capabilities.SetCapability(MobileCapabilityType.DeviceName, "Matthew's iPhone");
            capabilities.SetCapability(MobileCapabilityType.PlatformName, "ios");
            capabilities.SetCapability("buldleId", "none");
            capabilities.SetCapability(MobileCapabilityType.PlatformVersion, "10.1");
            capabilities.SetCapability("realDeviceLogger", "/usr/local/lib/node_modules/deviceconsole/deviceconsole");
            capabilities.SetCapability("wdaLocalPort", "8200");

            capabilities.SetCapability("xcodeConfigFile", "/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Configurations/ProjectSettings.xcconfig");
            capabilities.SetCapability("keychainPath", "/Users/matthewdavid/Library/Keychains/login.keychain");
            capabilities.SetCapability("keychainPassword", "C0d3Ninja");


**Logs**
Matthews-Mac-mini:node_modules matthewdavid$ export PATH=${PATH}:/usr/local/bin; cd /usr/local/lib/node_modules && node appium --safari -a 192.168.59.124 -p 4463 --bootstrap-port 4463 --nodeconfig /Users/matthewdavid/Documents/Nodes/IOS10Safari.json --webkit-debug-proxy-port 27753 -U 4625d558cb0644ea3447352bdfd3d0db2451167c --tmp /tmp/ios/
[Appium] Welcome to Appium v1.6.0-beta3
[Appium] Non-default server args:
[Appium]   address: '192.168.59.124'
[Appium]   port: 4463
[Appium]   bootstrapPort: 4463
[Appium]   safari: true
[Appium]   nodeconfig: '/Users/matthewdavid/Documents/Nodes/IOS10Safari.json'
[Appium]   tmpDir: '/tmp/ios/'
[Appium]   udid: '4625d558cb0644ea3447352bdfd3d0db2451167c'
[Appium] Deprecated server args:
[Appium]   -U,--udid => --default-capabilities '{"udid":"4625d558cb0644ea3447352bdfd3d0db2451167c"}'
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   udid: '4625d558cb0644ea3447352bdfd3d0db2451167c'
[debug] [Appium] Starting auto register thread for grid. Will try to register every 5000 ms.
[Appium] Appium REST http interface listener started on 192.168.59.124:4463
[HTTP] --> GET /wd/hub/status {}
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.0-beta3","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 21 ms - 89
[debug] [Appium] Appium successfully registered with the grid on 192.168.59.124:4444
[HTTP] --> GET /wd/hub/status {}
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.0-beta3","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 14 ms - 89
[HTTP] --> GET /wd/hub/status {}
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.0-beta3","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 13 ms - 89
[HTTP] --> GET /wd/hub/status {}
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.0-beta3","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 12 ms - 89
[HTTP] --> GET /wd/hub/status {}
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.0-beta3","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 12 ms - 89
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"buldleId":"none","realDeviceLogger":"/usr/local/lib/node_modules/deviceconsole/deviceconsole","platformVersion":"10.1","automationName":"XCUITest","keychainPath":"/Users/matthewdavid/Library/Keychains/login.keychain","browserName":"Safari","xcodeConfigFile":"/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Configurations/ProjectSettings.xcconfig","keychainPassword":"C0d3Ninja","platformName":"iOS","deviceName":"Matthew's iPhone","wdaLocalPort":"8200"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"buldleId":"none","realDeviceLogger":"/usr/local/lib/node_modules/deviceconsole/deviceconsole","platformVersion":"10.1","automationName":"XCUITest","keychainPath":"/Users/matthewdavid/Library/Keychains/login.keychain","browserName":"Safari","xco...
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   buldleId: 'none'
[Appium]   realDeviceLogger: '/usr/local/lib/node_modules/deviceconsole/deviceconsole'
[Appium]   platformVersion: '10.1'
[Appium]   automationName: 'XCUITest'
[Appium]   keychainPath: '/Users/matthewdavid/Library/Keychains/login.keychain'
[Appium]   browserName: 'Safari'
[Appium]   xcodeConfigFile: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Configurations/ProjectSettings.xcconfig'
[Appium]   keychainPassword: 'C0d3Ninja'
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'Matthew\'s iPhone'
[Appium]   wdaLocalPort: '8200'
[Appium]   udid: '4625d558cb0644ea3447352bdfd3d0db2451167c'
[debug] [XCUITest] XCUITestDriver version: 2.0.34
[BaseDriver] Capability 'wdaLocalPort' changed from string ('8200') to integer (8200). This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by appium: buldleId.
[BaseDriver] Session created with session id: 511a6d59-a220-4138-9828-f284b4929993
[debug] [XCUITest] Xcode version set to '8.1'
[debug] [XCUITest] iOS SDK Version set to '10.1'
[debug] [XCUITest] Available devices: 4625d558cb0644ea3447352bdfd3d0db2451167c
[debug] [XCUITest] Creating iDevice object with udid 4625d558cb0644ea3447352bdfd3d0db2451167c
[XCUITest] Determining device to run tests on: udid: '4625d558cb0644ea3447352bdfd3d0db2451167c', real device: true
[XCUITest] Safari test requested
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[XCUITest] Setting up real device
[XCUITest] Using default agent: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj
[XCUITest] Using default bootstrap: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Using real device logger '/usr/local/lib/node_modules/deviceconsole/deviceconsole'
[debug] [XCUITest] Using Xcode configuration file: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Configurations/ProjectSettings.xcconfig'
[debug] [XCUITest] Beginning test with command '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/bin/run-xcodebuild.sh --project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj --scheme WebDriverAgentRunner --destination id=4625d558cb0644ea3447352bdfd3d0db2451167c --xcode-config-file "/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Configurations/ProjectSettings.xcconfig" --keychain-path /Users/matthewdavid/Library/Keychains/login.keychain --keychain-password C0d3Ninja' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Waiting for WebDriverAgent to start on device
[HTTP] --> GET /wd/hub/status {}
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [XCUITest] Log file for xcodebuild test: /Users/matthewdavid/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/821D94F4-4D1D-4B6B-9E50-4345566661F8/Session-WebDriverAgentRunner-2016-11-02_171314-47dAsz.log
[Xcode] 2016-11-02 17:13:31.183 xcodebuild[86987:520997] Error Domain=IDETestOperationsObserverErrorDomain Code=3 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/matthewdavid/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/821D94F4-4D1D-4B6B-9E50-4345566661F8/Session-WebDriverAgentRunner-2016-11-02_171314-47dAsz.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/matthewdavid/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/821D94F4-4D1D-4B6B-9E50-4345566661F8/Session-WebDriverAgentRunner-2016-11-02_171314-47dAsz.log}

[Xcode]
Testing failed:
        No signing certificate "iOS Development" found:  No "iOS Development" signing certificate matching team ID "MYZ7FZLZHN" with a private key was found.
** TEST FAILED **


The following build commands failed:
        Check dependencies
(1 failure)

[XCUITest] xcodebuild exited with code '0' and signal 'null'

**Comment by mykola-mokhnach** [comment]
Try to build and deploy WDA on the target machine manually using Xcode and check the output. Probably, something is wrong with your certificate settings.

**Comment by Nesaganesh** [comment]
I have tried most of the options but no luck now its throwing me different error 

 /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/bin/run-xcodebuild.sh --project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj --scheme WebDriverAgentRunner --destination id=4625d558cb0644ea3447352bdfd3d0db2451167c --xcode-config-file "/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Configurations/ProjectSettings.xcconfig" --keychain-path /Users/matthewdavid/Documents/WebdriverAgent.p12 --keychain-password derivco
Setting security for iOS device
list-keychains "-s" "/Users/matthewdavid/Documents/WebdriverAgent.p12"
unlock-keychain "-p" "derivco" "/Users/matthewdavid/Documents/WebdriverAgent.p12"
security: SecKeychainUnlock /Users/matthewdavid/Documents/WebdriverAgent.p12: The specified keychain is not a valid keychain file.
security: SecKeychainSetSettings /Users/matthewdavid/Documents/WebdriverAgent.p12: The specified keychain is not a valid keychain file.
Running command 'xcodebuild build test -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=4625d558cb0644ea3447352bdfd3d0db2451167c -configuration Debug -xcconfig /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Configurations/ProjectSettings.xcconfig | xcpretty'
--- xcodebuild: WARNING: Using ACTION='build' to override build actions is deprecated, explicitly pass the actions to perform.

> Building WebDriverAgent/WebDriverAgentLib [Debug]
> Check Dependencies

[x] Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.1'



[x] Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.1'



[x] Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.1'



[x] Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.1'



[x] Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.1'



[x] Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.1'


** BUILD FAILED **


The following build commands failed:
        Check dependencies
(1 failure)
Matthews-Mac-mini:node_modules matthewdavid$

**Comment by dpgraham** [comment]
@Nesaganesh Are you able to successfully sign and run /Applications/Appium.app/Contents/Resources/node_modules/appium/Betway.ipa without using Appium? It sounds like the .ipa file you're using isn't provisioned to be used on your machine.

**Comment by ChiWhiteSox56** [comment]
@Nesaganesh - Have you found a solution to the problem that you reported? I'm having a similar issue where I'm also receiving the following error: 

```
No signing certificate "iOS Development" found: No "iOS Development" signing certificate matching team ID "XXXXXXXXXX" with a private key was found.
** TEST FAILED **
```

I really don't know what else to try, and my work is critically blocked because I can't run tests on real iOS devices. Everything was working fine until I had to accommodate the XCUITest framework. 

I submitted the following question to Appium Discuss. It lists everything I've tried in order to fix this problem: https://discuss.appium.io/t/xcodebuild-exited-with-code-65-no-signing-certificate-ios-development-found/14095

**Comment by ohadschn** [comment]
@ChiWhiteSox56 I got this error when I didn't have the signing certificate installed correctly. If you open Keychain and look at your certificates, do you see a valid (non-expired) one that says `iPhone Developer: YourName (XXXXXXXX)`? If not, that is your problem and you can fix it as followd:

1. Delete all existing non-valid/expired iPhone Developer certs (from both System and Login keychains if present).
2. Open some xcode project that requires signing, and in the target configuration, *General* tab, tick *automatically manage signing* and select your team.
3. If you don't have xcode project handy you can copy the WDA one (if installed globally then */usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj*). But copy it somewhere before and work on the copy because you don't want to change it.

XCode should now fix the signing identity for you and you should have the cert in your keychain.

**Comment by jlipps** [comment]
Thanks for the ideas @ohadschn, please give us an update when you've had a chance to try things out @ChiWhiteSox56!

**Comment by rkn411** [comment]
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[XCUITest] Setting up real device
[debug] [XCUITest] App is already installed.
[debug] [XCUITest] Full reset not requested. No need to install.
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Running WebDriverAgent bootstrap script to install dependencies
[XCUITest] Error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1
    at ChildProcess.<anonymous> (../../lib/teen_process.js:66:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
 { Error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1
    at ChildProcess.<anonymous> (../../lib/teen_process.js:66:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
  stdout: '\u001b[1mFetching dependencies\n*** Cloning RoutingHTTPServer\n*** Cloning peertalk\n*** Downloading peertalk.framework binary at "v1.0"\n',
  stderr: 'Failed to write to /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/iOS: Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “iOS” in the folder “Build”." UserInfo={NSFilePath=/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/iOS, NSUnderlyingError=0x7f9d77c3ee10 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}}\n',
  code: 1 }
[XCUITest] Shutting down sub-processes
[debug] [XCUITest] Running ios real device reset flow
[debug] [XCUITest] Resetting simulator
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1
    at ChildProcess.<anonymous> (../../lib/teen_process.js:66:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
[HTTP] <-- POST /wd/hub/session 500 49320 ms - 199 
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.2","revision":null}}

**Comment by rkn411** [comment]
@jlipps help me on this running appium 1.6 Xcode 8.3,ios-10.2 i m unable to figure what exact issue on this i m using 1.4.13 appium gui

**Comment by imurchie** [comment]
This is a permissions issue now: `Failed to write to /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/iOS: Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “iOS” in the folder “Build”`.
