### ISSUE TITLE
UIAutomator shutdown unexpectedly

### ISSUE THREAD

**Issue by SmileZq** [appium/appium#7217]
## The problem

Hi, I am using Appium java client to build an automated testing system. Sometimes, the testing failed unexpectedly. . The server log is as follows:
[debug] [AndroidBootstrap] Received command result from bootstrap
[MJSONWP] Responding to client with driver.click() result: true

[HTTP] <-- POST /wd/hub/session/3fcf68c7-3638-4ad9-b764-33842f5069fc/element/10/click 200 311 ms - 76 
[HTTP] --> POST /wd/hub/session/3fcf68c7-3638-4ad9-b764-33842f5069fc/element {"using":"xpath","value":".//*[@text='组织切换']"}
[MJSONWP] Calling AppiumDriver.findElement() with args: ["xpath",".//*[@text='组织切换'...
[debug] [BaseDriver] Waiting up to 2000 ms for condition
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":".//*[@text='组织切换']","context":"","multiple":false}}

[Logcat] Logcat terminated with code 0, signal null

[debug] [UiAutomator] Moving to state 'stopped'

[UiAutomator] UiAutomator exited unexpectedly with code 0, signal null

[debug] [AndroidDriver] Shutting down Android driver
[Appium] Closing session, cause was 'UiAUtomator shut down unexpectedly'
[Appium] Removing session 3fcf68c7-3638-4ad9-b764-33842f5069fc from our master session list
[debug] [AndroidDriver] Resetting IME to com.google.android.inputmethod.latin/com.android.inputmethod.latin.LatinIME
[debug] [ADB] Getting connected devices...

[MJSONWP] Encountered internal error running command: Error: UiAUtomator shut down unexpectedly
    at AndroidBootstrap.callee$2$0$ (lib/bootstrap.js:76:44)
    at tryCatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at new Promise (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:197:7)
    at AsyncIterator.enqueue (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at UiAutomator.callee$2$0 (lib/bootstrap.js:73:64)
    at emitOne (events.js:90:13)
    at UiAutomator.emit (events.js:182:7)
    at UiAutomator.changeState (lib/uiautomator.js:85:10)
    at SubProcess.<anonymous> (lib/uiautomator.js:47:14)
    at emitTwo (events.js:100:13)
    at SubProcess.emit (events.js:185:7)
    at ChildProcess.<anonymous> (lib/teen_process.js:186:14)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)

[HTTP] <-- POST /wd/hub/session/3fcf68c7-3638-4ad9-b764-33842f5069fc/element 500 330 ms - 205 
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/gzb/program/android-sdk-macosx/platform-tools/adb with args: ["-P",5037,"-s","0491246b094dba76","shell","ime","set","com.google.android.inputmethod.latin/com.android.inputmethod.latin.LatinIME"]

[HTTP] --> GET /wd/hub/session/3fcf68c7-3638-4ad9-b764-33842f5069fc/screenshot {}

[HTTP] <-- GET /wd/hub/session/3fcf68c7-3638-4ad9-b764-33842f5069fc/screenshot 404 1 ms - 131 
## Environment

* Appium version : appium.app 1.5.3
* Desktop OS/version used to run Appium: mac osx
* Node.js version (unless using Appium.app|exe): 6.2.1
* Mobile platform/version under test:4.4.2
* Real device or emulator/simulator:nexus 5

## Details

I serch the promble in Internet, someone maybe have the same problem, but I don't understand how to do in mac with appium.app.
Here is the url：
https://discuss.appium.io/t/android-uiautomator-shutdown-unexpectedly/11452

My English is poor，if anything is misunderstanding，please reply to me。I want to know how to deal with the problem in detail with appium.app in mac。

**Comment by mykola-mokhnach** [comment]
Think about switching to UIAutomator2, which is available since Appium 1.6.0

**Comment by ljpwuguo** [comment]
MayBe the process uiautomator has be killed, we should restart the uiautomator in this scene.

**Comment by SmileZq** [comment]
@ljpwuguo while running test cases, I don't think uiautomator should be killed automatically.

**Comment by rajguptaolx** [comment]
@jlipps I faced the similar problem, do you have the solution?
@mykola-mokhnach I am already running my testcases on Appium version 1.6.0, but there also I am facing this issue.

**Comment by aquintiliano** [comment]
how do I switch to UIAutomator2?

**Comment by jlipps** [comment]
Set the `automationName` capability to `UiAutomator2`

**Comment by Ucoon** [comment]
what defference between uiautomator1 and uiautomator2? I  run well my tests on my computer(127.0.0.1), but once I changed IP,  it occured  sometimes UiAUtomator shut down unexpectedly.

**Comment by samuraii** [comment]
Setting "UiAutomator2" - leads to endless crashes without any answer from developers about the reason.

**Comment by konflic** [comment]
The last answer is true, under UiAutomator2 everything starts crashing.
