### ISSUE TITLE
npm install appium tries to install older version of chromedriver and failing

### ISSUE THREAD

**Issue by vikramvi** [appium/appium#7222]
## The problem

npm install appium try this command on latest Mac OS 10.11.6 ( Mac Pro mid 2015 )

This tries to install /2.21/chromedriver_mac32.zip and fails 

## Environment

* Desktop OS/version used to run Appium:  MAC OS 10.11.6
* Node.js version (unless using Appium.app|exe):  v7.1.0

## Details

(node:11126) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
info Chromedriver Install Installing Chromedriver version '2.21' for platform 'mac' and architecture '32'
info Chromedriver Install Opening temp file to write chromedriver_mac32 to...
info Chromedriver Install Downloading http://chromedriver.storage.googleapis.com/2.21/chromedriver_mac32.zip...
RequestError: Error: read ECONNRESET
    at new RequestError (/Users/vikram-anna/node_modules/appium/node_modules/request-promise/lib/errors.js:11:15)
    at Request.RP$callback [as _callback] (/Users/vikram-anna/node_modules/appium/node_modules/request-promise/lib/rp.js:60:32)
    at self.callback (/Users/vikram-anna/node_modules/appium/node_modules/request/request.js:187:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/Users/vikram-anna/node_modules/appium/node_modules/request/request.js:813:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1281:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Shouldn't it be installing latest 64 bit version for mac https://chromedriver.storage.googleapis.com/index.html?path=2.25/

## Link to Appium logs

NA

## Code To Reproduce Issue [ Good To Have ]

NA

**Comment by imurchie** [comment]
What command are you running?

**Comment by vikramvi** [comment]
@imurchie  npm install -g appium

note:
npm install appium-chromedriver passed though

**Comment by imurchie** [comment]
Yes. The upgrade of ChromeDriver to 2.25 happened _after_ the release of 1.6.0. Your best bet is to get the beta of 1.6.1, which can be retrieved with `npm install -g appium@beta`.

**Comment by vikramvi** [comment]
Thanks for quick help it worked without any problems.

**Comment by tnbsoftlab24** [comment]
This command fix the issue. It works for me:
sudo npm install -g appium --unsafe-perm=true --allow-root

**Comment by nahoang** [comment]
@tnbsoftlab24 thanks a lot
