### ISSUE TITLE
Failed to start an Appium session, err was: Error: stdout maxBuffer exceeded on appium1.4.16

### ISSUE THREAD

**Issue by ljpwuguo** [appium/appium#7227]
## The problem
2016-11-11 12:05:43.059 [Thread-43] DEBUG com.alipay.auto.libs.AppiumManager - line : [36minfo[39m: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":true}
2016-11-11 12:05:43.578 [Thread-43] DEBUG com.alipay.auto.libs.AppiumManager - line : [36minfo[39m: [debug] Resetting IME to 'com.samsung.inputmethod/.SamsungIME'
2016-11-11 12:05:43.578 [Thread-43] DEBUG com.alipay.auto.libs.AppiumManager - line : [36minfo[39m: [debug] executing cmd: /home/ubuntu/android-sdk-linux/platform-tools/adb -s 877e6a36 shell "ime set com.samsung.inputmethod/.SamsungIME"
2016-11-11 12:05:44.221 [Thread-43] DEBUG com.alipay.auto.libs.AppiumManager - line : [36minfo[39m: [debug] Stopping logcat capture
2016-11-11 12:05:44.222 [Thread-43] DEBUG com.alipay.auto.libs.AppiumManager - line : [36minfo[39m: [debug] Logcat terminated with code null, signal SIGTERM
2016-11-11 12:05:44.227 [Thread-43] DEBUG com.alipay.auto.libs.AppiumManager - line : [36minfo[39m: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"shutdown"}
2016-11-11 12:05:44.228 [Thread-43] DEBUG com.alipay.auto.libs.AppiumManager - line : [36minfo[39m: [debug] [BOOTSTRAP] [debug] Got command of type SHUTDOWN
2016-11-11 12:05:44.228 [Thread-43] DEBUG com.alipay.auto.libs.AppiumManager - line : [36minfo[39m: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":"OK, shutting down"}
2016-11-11 12:05:44.231 [Thread-43] DEBUG com.alipay.auto.libs.AppiumManager - line : [36minfo[39m: [debug] [BOOTSTRAP] [debug] Closed client connection
2016-11-11 12:05:44.231 [Thread-43] DEBUG com.alipay.auto.libs.AppiumManager - line : [36minfo[39m: [debug] [90m[UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1[39m
2016-11-11 12:05:44.231 [Thread-43] DEBUG com.alipay.auto.libs.AppiumManager - line : [36minfo[39m: [debug] [90m[UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=.[39m
2016-11-11 12:05:44.231 [Thread-43] DEBUG com.alipay.auto.libs.AppiumManager - line : [36minfo[39m: [debug] [90m[UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner[39m
2016-11-11 12:05:44.231 [Thread-43] DEBUG com.alipay.auto.libs.AppiumManager - line : [36minfo[39m: [debug] [90m[UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer[39m
2016-11-11 12:05:44.231 [Thread-43] DEBUG com.alipay.auto.libs.AppiumManager - line : [36minfo[39m: [debug] [90m[UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap[39m
2016-11-11 12:05:44.231 [Thread-43] DEBUG com.alipay.auto.libs.AppiumManager - line : [36minfo[39m: [debug] [90m[UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1[39m
2016-11-11 12:05:44.231 [Thread-43] DEBUG com.alipay.auto.libs.AppiumManager - line : [36minfo[39m: [debug] [90m[UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 0[39m
2016-11-11 12:05:44.231 [Thread-43] DEBUG com.alipay.auto.libs.AppiumManager - line : [36minfo[39m: [debug] Sent shutdown command, waiting for UiAutomator to stop...
2016-11-11 12:05:44.232 [Thread-43] DEBUG com.alipay.auto.libs.AppiumManager - line : [36minfo[39m: [debug] [90m[UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=[39m
2016-11-11 12:05:44.232 [Thread-43] DEBUG com.alipay.auto.libs.AppiumManager - line : [36minfo[39m: [debug] [90m[UIAUTOMATOR STDOUT] Test results for WatcherResultPrinter=.[39m
2016-11-11 12:05:44.232 [Thread-43] DEBUG com.alipay.auto.libs.AppiumManager - line : [36minfo[39m: [debug] [90m[UIAUTOMATOR STDOUT] Time: 1.385[39m
2016-11-11 12:05:44.232 [Thread-43] DEBUG com.alipay.auto.libs.AppiumManager - line : [36minfo[39m: [debug] [90m[UIAUTOMATOR STDOUT] OK (1 test)[39m
2016-11-11 12:05:44.233 [Thread-43] DEBUG com.alipay.auto.libs.AppiumManager - line : [36minfo[39m: [debug] [90m[UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: -1[39m
2016-11-11 12:05:44.265 [Thread-43] DEBUG com.alipay.auto.libs.AppiumManager - line : [36minfo[39m: [debug] UiAutomator shut down normally
2016-11-11 12:05:44.265 [Thread-43] DEBUG com.alipay.auto.libs.AppiumManager - line : [36minfo[39m: [debug] Cleaning up android objects
2016-11-11 12:05:44.265 [Thread-43] DEBUG com.alipay.auto.libs.AppiumManager - line : [36minfo[39m: [debug] Cleaning up appium session
2016-11-11 12:05:44.265 [Thread-44] ERROR com.alipay.auto.libs.AppiumManager - error line : [31merror[39m: Failed to start an Appium session, err was: Error: stdout maxBuffer exceeded
2016-11-11 12:05:44.266 [Thread-43] DEBUG com.alipay.auto.libs.AppiumManager - line : [36minfo[39m: [debug] Error: stdout maxBuffer exceeded
2016-11-11 12:05:44.266 [Thread-43] DEBUG com.alipay.auto.libs.AppiumManager - line :     at Socket.<anonymous> (child_process.js:266:14)
2016-11-11 12:05:44.266 [Thread-43] DEBUG com.alipay.auto.libs.AppiumManager - line :     at emitOne (events.js:77:13)
2016-11-11 12:05:44.266 [Thread-43] DEBUG com.alipay.auto.libs.AppiumManager - line :     at Socket.emit (events.js:169:7)
2016-11-11 12:05:44.266 [Thread-43] DEBUG com.alipay.auto.libs.AppiumManager - line :     at readableAddChunk (_stream_readable.js:153:18)
2016-11-11 12:05:44.266 [Thread-43] DEBUG com.alipay.auto.libs.AppiumManager - line :     at Socket.Readable.push (_stream_readable.js:111:10)
2016-11-11 12:05:44.266 [Thread-43] DEBUG com.alipay.auto.libs.AppiumManager - line :     at Pipe.onread (net.js:536:20)
2016-11-11 12:05:44.267 [Thread-43] DEBUG com.alipay.auto.libs.AppiumManager - line : [36minfo[39m: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: stdout maxBuffer exceeded)","cmd":"/bin/sh -c /home/ubuntu/android-sdk-linux/platform-tools/adb -s 877e6a36 shell \"dumpsys window\"","origValue":"stdout maxBuffer exceeded"},"sessionId":null}
2016-11-11 12:05:44.271 [Thread-43] DEBUG com.alipay.auto.libs.AppiumManager - line : [36minfo[39m: [37m<-- POST /wd/hub/session [39m[31m500[39m[90m 12537.437 ms - 278[39m [90m[39m

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue:
  1.4.16
* Last Appium version that did not exhibit the issue (if applicable):
  donot sure,  will try on latest appium version
* Desktop OS/version used to run Appium:
  ubuntu 14.04
* Node.js version (unless using Appium.app|exe):
   node version : v4.5.0
* Mobile platform/version under test:
   android / 5.0.2
* Real device or emulator/simulator:
  Real device,SM-A5000
* Appium CLI or Appium.app|exe:
  appium version : 1.4.16
## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Is it still reproducible with Appium 1.6.0?

**Comment by ljpwuguo** [comment]
it is reproducible with 1.5.3 too, i will try on 1.6.0，

**Comment by ljpwuguo** [comment]
it is reproducible with 1.5.3 too, i will try on 1.6.0，
