### ISSUE TITLE
appium 1.6.1 beta with ios 8.1 and xcode 7.3.1 not working

### ISSUE THREAD

**Issue by kineret321** [appium/appium#7246]
So i finally succeed working with appium 1.6.1 beta ios 10 and xcode 8.1.
But now i have problem working on the same machine with ios older versions.
I installed xcode 7.3.1 (now i have both xcode version 7.3.1 and 8.1),
and when i want to use older ios versions I use xcode 7.3.1 as my default xcode version, 
so this is not the problem.
when im trying to use appium UI or from my script with the below desired caps:
desired_caps = {}
desired_caps['appium-version'] = '1.6'
desired_caps['platformName'] = 'ios'
desired_caps['platformVersion'] = '8.1'
desired_caps['deviceName'] = '5s'
desired_caps['app'] = os.path.abspath(desktop+"/Files/ios_1.7.2_TE3487.ipa")
desired_caps['newCommandTimeout']= 0
desired_caps['udid']= '13eeac71220d7ef92316ab3deaf0d2de22d2f263'#'4ba95a2da3af6869344047620c1755dd23cdbc57

it returns error:
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Installing /var/folders/x7/g459t3xs3nz99lmm86jwvx140000gp/T/20161017-9857-6fngl3.xmb0c6jemi/Payload/PingID-Test.app failed

appium log:

2016-11-17 16:33:54:904 - info: [Appium] Welcome to Appium v1.6.1-beta
2016-11-17 16:33:54:906 - info: [Appium] Non-default server args:
2016-11-17 16:33:54:907 - info: [Appium]   log: '/Users/aalocal/Desktop/appium_logs.txt'
2016-11-17 16:33:54:908 - info: [Appium]   fullReset: true
2016-11-17 16:33:54:908 - info: [Appium]   showIOSLog: true
2016-11-17 16:33:54:909 - warn: [Appium] Deprecated server args:
2016-11-17 16:33:54:909 - warn: [Appium]   --full-reset => --default-capabilities '{"fullReset":true}'
2016-11-17 16:33:54:909 - warn: [Appium]   --show-ios-log => --default-capabilities '{"showIOSLog":true}'
2016-11-17 16:33:54:909 - info: [Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
2016-11-17 16:33:54:910 - info: [Appium]   fullReset: true
2016-11-17 16:33:54:911 - info: [Appium]   showIOSLog: true
2016-11-17 16:33:54:954 - info: [Appium] Appium REST http interface listener started on 0.0.0.0:4723
2016-11-17 16:33:55:766 - info: [HTTP] --> GET /wd/hub/status {}
2016-11-17 16:33:55:768 - info: [debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
2016-11-17 16:33:55:770 - info: [HTTP] --> GET /wd/hub/status {}
2016-11-17 16:33:55:770 - info: [debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
2016-11-17 16:33:55:783 - info: [debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.1-beta","revision":null}}
2016-11-17 16:33:55:789 - info: [HTTP] <-- GET /wd/hub/status 200 20 ms - 88 
2016-11-17 16:33:55:801 - info: [debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.1-beta","revision":null}}
2016-11-17 16:33:55:803 - info: [HTTP] <-- GET /wd/hub/status 200 32 ms - 88 
2016-11-17 16:33:56:467 - info: [HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"deviceName":"5s","udid":"13eeac71220d7ef92316ab3deaf0d2de22d2f263","app":"/Users/aalocal/Downloads/pingid.ipa","appium-version":"1.6","newCommandTimeout":0,"platformVersion":"8.1","platformName":"ios"}}
2016-11-17 16:33:56:468 - info: [debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"deviceName":"5s","udid":"13eeac71220d7ef92316ab3deaf0d2de22d2f263","app":"/Users/aalocal/Downloads/pingid.ipa","appium-version":"1.6","newCommandTimeout":0,"platformVersion":"8.1","platformName":"ios"},null,null,null,null]
2016-11-17 16:33:56:470 - info: [Appium] Creating new IosDriver session
2016-11-17 16:33:56:470 - info: [Appium] Capabilities:
2016-11-17 16:33:56:471 - info: [Appium]   deviceName: '5s'
2016-11-17 16:33:56:472 - info: [Appium]   udid: '13eeac71220d7ef92316ab3deaf0d2de22d2f263'
2016-11-17 16:33:56:472 - info: [Appium]   app: '/Users/israellocal/Downloads/pingid.ipa'
2016-11-17 16:33:56:472 - info: [Appium]   appium-version: '1.6'
2016-11-17 16:33:56:472 - info: [Appium]   newCommandTimeout: 0
2016-11-17 16:33:56:473 - info: [Appium]   platformVersion: '8.1'
2016-11-17 16:33:56:473 - info: [Appium]   platformName: 'ios'
2016-11-17 16:33:56:473 - info: [Appium]   fullReset: true
2016-11-17 16:33:56:488 - info: [Appium]   showIOSLog: true
2016-11-17 16:33:56:490 - info: [debug] [iOS] IosDriver version: 1.12.32
2016-11-17 16:33:56:495 - warn: [BaseDriver] The following capabilities were provided, but are not recognized by appium: appium-version.
2016-11-17 16:33:56:517 - info: [BaseDriver] Session created with session id: efc421c6-d2a1-46ba-9e05-4e6e8f2fbeab
2016-11-17 16:33:56:560 - info: [debug] [iOS] Xcode version set to 7.3.1
2016-11-17 16:33:56:560 - info: [debug] [iOS] Not auto-detecting udid.
2016-11-17 16:33:56:563 - info: [BaseDriver] Using local app '/Users/israellocal/Downloads/pingid.ipa'
2016-11-17 16:33:56:563 - info: [debug] [BaseDriver] Copying local zip to tmp dir
2016-11-17 16:33:56:631 - info: [debug] [BaseDriver] Unzipping /var/folders/x7/g459t3xs3nz99lmm86jwvx140000gp/T/20161017-10296-16s1xqz.5awq99hpvi/appium-app.zip
2016-11-17 16:33:56:632 - info: [debug] [BaseDriver] Testing zip archive: /var/folders/x7/g459t3xs3nz99lmm86jwvx140000gp/T/20161017-10296-16s1xqz.5awq99hpvi/appium-app.zip
2016-11-17 16:33:57:316 - info: [BaseDriver] Unzipped local app to '/var/folders/x7/g459t3xs3nz99lmm86jwvx140000gp/T/20161017-10296-16s1xqz.5awq99hpvi/Payload/PingID-Test.app'
2016-11-17 16:33:57:317 - info: [debug] [iOS] Removing any remaining instruments sockets
2016-11-17 16:33:57:319 - info: [debug] [iOS] Cleaned up instruments socket /var/folders/x7/g459t3xs3nz99lmm86jwvx140000gp/T/instruments_sock
2016-11-17 16:33:57:320 - info: [debug] [iOS] No language specified. Using default strings
2016-11-17 16:33:57:320 - info: [debug] [iOS] Strings file not found. Looking in 'en.lproj' directory
2016-11-17 16:33:57:323 - info: [debug] [iOS] Parsed app 'Localizable.strings'
2016-11-17 16:33:57:326 - info: [debug] [ios-app-utils] Getting bundle ID from app '/var/folders/x7/g459t3xs3nz99lmm86jwvx140000gp/T/20161017-10296-16s1xqz.5awq99hpvi/Payload/PingID-Test.app': 'com.pingidentity.pingid.testEnterprise'
2016-11-17 16:33:57:326 - info: [iOS] Extracted bundleID: com.pingidentity.pingid.testEnterprise from app: /var/folders/x7/g459t3xs3nz99lmm86jwvx140000gp/T/20161017-10296-16s1xqz.5awq99hpvi/Payload/PingID-Test.app
2016-11-17 16:33:57:327 - info: [debug] [iOS] Creating instruments
2016-11-17 16:33:57:328 - info: [debug] [UIAuto] Preparing bootstrap code
2016-11-17 16:33:57:328 - info: [debug] [UIAuto] Dynamic bootstrap dir: /Users/israellocal/Library/Application Support/appium/bootstrap
2016-11-17 16:33:57:329 - info: [debug] [UIAuto] Dynamic env: {"nodePath":"/usr/local/Cellar/node/7.0.0/bin/node","commandProxyClientPath":"/usr/local/lib/node_modules/appium/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js","instrumentsSock":"/var/folders/x7/g459t3xs3nz99lmm86jwvx140000gp/T/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"grouped"}
2016-11-17 16:33:57:356 - info: [debug] [UIAuto] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...
2016-11-17 16:33:57:356 - info: [debug] [UIAuto] Dynamic bootstrap path: /Users/israellocal/Library/Application Support/appium/bootstrap/bootstrap-60b46022c755c8c8.js
2016-11-17 16:33:57:359 - info: [debug] [UIAuto] Reusing dynamic bootstrap: /Users/israellocal/Library/Application Support/appium/bootstrap/bootstrap-60b46022c755c8c8.js
2016-11-17 16:33:57:361 - info: [debug] [iOS] Creating iDevice object with udid 13eeac71220d7ef92316ab3deaf0d2de22d2f263
2016-11-17 16:33:57:365 - info: [debug] [iOS] Running ios real device reset flow
2016-11-17 16:33:57:366 - info: [debug] [iOS] Full reset requested. Will try to uninstall the app 'com.pingidentity.pingid.testEnterprise'.
2016-11-17 16:33:57:744 - info: [debug] [iOS] App not installed. No need to uninstall
2016-11-17 16:33:58:118 - error: [iOS] Could not remove 'com.pingidentity.pingid.testEnterprise' from device
2016-11-17 16:33:58:119 - error: [MJSONWP] Encountered internal error running command: Error: Removing com.pingidentity.pingid.testEnterprise failed
    at /usr/local/lib/node_modules/appium/node_modules/node-idevice/main.js:145:6
    at ChildProcess.exithandler (child_process.js:202:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
2016-11-17 16:33:58:127 - info: [HTTP] <-- POST /wd/hub/session 500 1659 ms - 191 
2016-11-17 16:34:06:940 - info: [HTTP] --> GET /wd/hub/status {}
2016-11-17 16:34:06:941 - info: [debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
2016-11-17 16:34:06:952 - info: [debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.1-beta","revision":null}}
2016-11-17 16:34:06:955 - info: [HTTP] <-- GET /wd/hub/status 200 13 ms - 88 
2016-11-17 16:34:06:956 - info: [HTTP] --> GET /wd/hub/status {}
2016-11-17 16:34:06:956 - info: [debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
2016-11-17 16:34:06:966 - info: [debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.1-beta","revision":null}}
2016-11-17 16:34:06:967 - info: [HTTP] <-- GET /wd/hub/status 200 11 ms - 88

**Comment by imurchie** [comment]
You'll need to update to get at least the ios driver version `1.12.33`, unfortunately. Or turn off `fullReset`

To update, you can update Appium altogether:

```
npm uninstall -g appium
npm install -g appium@beta
```

Or find here Appium is installed

```
cd <wherever appium is installed>
npm install appium-ios-driver
```

When you run Appium subsequently you should see the log line (when the session is starting)

```
2016-11-17 16:33:56:490 - info: [debug] [iOS] IosDriver version: 1.12.33
```

**Comment by HlebHalkouski** [comment]
You need to update the permissions for `ideviceinstaller `.
`sudo chmod -R 777 /var/db/lockdown`

@kineret321 @imurchie 
https://github.com/appium/appium/issues/7017

**Comment by imurchie** [comment]
That's not the problem here. This particular version of the driver tries to uninstall an app even if it is not installed, and that fails.

**Comment by kineret321** [comment]
Solved by "npm install appium-ios-driver"

Thank you @imurchie
