### ISSUE TITLE
Suppressed: java.io.FileNotFoundException: https://team-appium.ci.cloudbees.com/cli/

### ISSUE THREAD

**Issue by huming** [appium/appium#7249]
I got the issue at install jenkins. Anybody knows how to resolve this issue? Thanks for whatever help.

## The problem

java -jar jenkins-cli.jar  -s https://team-appium.ci.cloudbees.com -i ~/.ssh/id_rsa on-premise-executor -fsroot ~/jenkins -labels osx -name mac_appiumls
java.io.EOFException
	at java.io.DataInputStream.readFully(DataInputStream.java:197)
	at java.io.DataInputStream.readUTF(DataInputStream.java:609)
	at java.io.DataInputStream.readUTF(DataInputStream.java:564)
	at hudson.cli.CLI.connectViaCliPort(CLI.java:226)
	at hudson.cli.CLI.<init>(CLI.java:128)
	at hudson.cli.CLIConnectionFactory.connect(CLIConnectionFactory.java:72)
	at hudson.cli.CLI._main(CLI.java:473)
	at hudson.cli.CLI.main(CLI.java:384)
	**Suppressed: java.io.FileNotFoundException: https://team-appium.ci.cloudbees.com/cli/**
		at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1836)
		at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
		at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
		at hudson.cli.FullDuplexHttpStream.<init>(FullDuplexHttpStream.java:78)
		at hudson.cli.CLI.connectViaHttp(CLI.java:152)
		at hudson.cli.CLI.<init>(CLI.java:132)
		... 3 more

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS X
* Node.js version (unless using Appium.app|exe): 6.9.1
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

**Comment by parkan** [comment]
How did you resolve this? Seeing it as well
