### ISSUE TITLE
[iProxy] recv failed: Resource temporarily unavailable while app installation is in progress and error out with exception shown in logs..

### ISSUE THREAD

**Issue by SatishKumarKV** [appium/appium#7263]
## The problem

[iProxy] recv failed: Resource temporarily unavailable while app installation is in progress and error out with exception shown in logs..

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Appium logs
```
[ 60%] InspectingPackage
[ 60%] TakingInstallLock
[ 65%] PreflightingApplication
[ 65%] InstallingEmbeddedProfile
[ 65%] InstallingEmbeddedProfile
[ 70%] VerifyingApplication
[ 75%] CreatingContainer
[ 80%] InstallingApplication
[ 85%] PostflightingApplication
[ 90%] SandboxingApplication
[ 95%] GeneratingApplicationMap
[debug] [iProxy] recv failed: Resource temporarily unavailable
[debug] [iProxy] recv failed: Operation not permitted
[100%] Installed package /Users/Automation/iOSAgent/ios/Builds/ResignedBuilds/MaaS360_3.01.ipa
Waiting for process termination
Process terminated
Entered After Invocation of installApplication7
[HTTP] --> GET /wd/hub/session/4714ca8b-4a6e-43da-8268-3bbcd46b6b47/screenshot {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[JSONWP Proxy] Proxying [GET /wd/hub/session/4714ca8b-4a6e-43da-8268-3bbcd46b6b47/screenshot] to [GET http://localhost:8100/session/B08C7573-24D7-4CD3-81AC-E7BE0E2973DA/screenshot] with body: {}
[JSONWP Proxy] Got response with status 200: "{\n \"value\" : \"iVBORw0...
[JSONWP Proxy] Replacing sessionId B08C7573-24D7-4CD3-81AC-E7BE0E2973DA with 4714ca8b-4a6e-43da-8268-3bbcd46b6b47
[HTTP] Entered Test Success of method name installApplication7
Test case execution SUCCESS on 2016/11/22 13:12:53
logMessage9 Started
Entered Before Invocation of logMessage9
[Invoker 1259652483] Invoking com.ios.AppiumScripts.PreInstallConfigure3_01MaaSApp.logMessage9
Error in taking screenshot: null
Entered After Invocation of logMessage9
[HTTP] --> GET /wd/hub/session/4714ca8b-4a6e-43da-8268-3bbcd46b6b47/screenshot {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[JSONWP Proxy] Proxying [GET /wd/hub/session/4714ca8b-4a6e-43da-8268-3bbcd46b6b47/screenshot] to [GET http://localhost:8100/session/B08C7573-24D7-4CD3-81AC-E7BE0E2973DA/screenshot] with body: {}
[JSONWP Proxy] Got response with status 200: "{\n \"value\" : \"iVBORw0...
[JSONWP Proxy] Replacing sessionId B08C7573-24D7-4CD3-81AC-E7BE0E2973DA with 4714ca8b-4a6e-43da-8268-3bbcd46b6b47
[HTTP] Entered Test Success of method name logMessage9
Test case execution SUCCESS on 2016/11/22 13:12:53
launchiOSApp11 Started
Entered Before Invocation of launchiOSApp11
[Invoker 1259652483] Invoking com.ios.AppiumScripts.PreInstallConfigure3_01MaaSApp.launchiOSApp11
[HTTP] --> DELETE /wd/hub/session/4714ca8b-4a6e-43da-8268-3bbcd46b6b47 {}
[MJSONWP] Calling AppiumDriver.deleteSession() with args: ["4714ca8b-4a6e-43da-8268-3...
[JSONWP Proxy] Proxying [DELETE /session/4714ca8b-4a6e-43da-8268-3bbcd46b6b47] to [DELETE http://localhost:8100/session/B08C7573-24D7-4CD3-81AC-E7BE0E2973DA] with no body
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[JSONWP Proxy] Got response with status 200: "{\n \"value\" : {\n\n },...
[XCUITest] Shutting down WebDriverAgent
[XCUITest] xcodebuild exited with code 'null' and signal 'SIGTERM'
[XCUITest] System log exited with code 'null'
[debug] [XCUITest] WebDriverAgent process did not end in a timely fashion. Sending SIGHUP signal...
[debug] [XCUITest] Running ios real device reset flow
[debug] [XCUITest] Resetting simulator
[debug] [iOSLog] Stopping iOS log capture
[Appium] Removing session 4714ca8b-4a6e-43da-8268-3bbcd46b6b47 from our master session list
[debug] [MJSONWP] Received response: null
[debug] [MJSONWP] But deleting session, so not returning
[MJSONWP] Responding to client with driver.deleteSession() result: null
[HTTP] Appium context set to application :MaaS360
[Appium] Welcome to Appium v1.6.0 (REV 5f4111d24a7ced6220ffa92d088559a86bc1c335)
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> GET /wd/hub/status {}
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.0"...
[HTTP] [HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"com.fiberlink.maas360.enterpriseappstore","realDeviceLogger":"/usr/local/lib/node_modules/deviceconsole/deviceconsole","platformVersion":"10.0","automationName":"XCUITest","udid":"d8814950652da486ef218e96adcf098b881e0be6","platformName":"iOS","deviceName":"iPhone 6","autoAcceptAlerts":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"com.fiberlink.maas...
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium] app: 'com.fiberlink.maas360.enterpriseappstore'
[Appium] realDeviceLogger: '/usr/local/lib/node_modules/deviceconsole/deviceconsole'
[Appium] platformVersion: '10.0'
[Appium] automationName: 'XCUITest'
[Appium] udid: 'd8814950652da486ef218e96adcf098b881e0be6'
[Appium] platformName: 'iOS'
[Appium] deviceName: 'iPhone 6'
[Appium] autoAcceptAlerts: true
[debug] [XCUITest] XCUITestDriver version: 2.0.26
[BaseDriver] Session created with session id: 2f3124b9-37e5-425e-8288-8000a09e09a1
[debug] [XCUITest] Xcode version set to '8.1'
[debug] [XCUITest] iOS SDK Version set to '10.1'
[debug] [XCUITest] Available devices: d8814950652da486ef218e96adcf098b881e0be6
[debug] [XCUITest] Creating iDevice object with udid d8814950652da486ef218e96adcf098b881e0be6
[XCUITest] Determining device to run tests on: udid: 'd8814950652da486ef218e96adcf098b881e0be6', real device: true
[debug] [XCUITest] Checking whether app is actually present
[XCUITest] Error: Could not find app at com.fiberlink.maas360.enterpriseappstore
at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
at XCUITestDriver.checkAppPresent$ (lib/driver.js:314:11)
at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
Error: Could not find app at com.fiberlink.maas360.enterpriseappstore
at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
at XCUITestDriver.checkAppPresent$ (lib/driver.js:314:11)
at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[XCUITest] Error: Could not find app at com.fiberlink.maas360.enterpriseappstore
at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
at XCUITestDriver.checkAppPresent$ (lib/driver.js:314:11)
at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
Error: Could not find app at com.fiberlink.maas360.enterpriseappstore
at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
at XCUITestDriver.checkAppPresent$ (lib/driver.js:314:11)
at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[debug] [XCUITest] Running ios real device reset flow
[debug] [XCUITest] Resetting simulator
[MJSONWP] Encountered internal error running command: Error: Could not find app at com.fiberlink.maas360.enterpriseappstore
at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
at XCUITestDriver.checkAppPresent$ (lib/driver.js:314:11)
at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] Failed to launch app:org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not find app at com.fiberlink.maas360.enterpriseappstore (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 3.32 seconds
Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:59:12'
System info: host: 'Automations-Mac-mini.local', ip: '10.104.148.50', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_102'
Driver info: io.appium.java_client.ios.IOSDriver
LogWarning:Retry for the first time after failure and the method name is launchiOSApp11
```

**Comment by imurchie** [comment]
What are the original desired capabilities. I see in the middle another Appium instance starting up and a set of capabilities that seems different from the previous ones (at least in behavior; it's hard to tell from the snippet what was happening before the first iproxy error).

**Comment by SharadRao23** [comment]
I am also getting the same error : [debug] [iProxy] recv failed: Resource temporarily unavailable while trying to get device logs using "showIOSLog" capability for appium1.6.1-beta.

Unable to get devices logs which was working fine with older versions of appium.

**Comment by SatishKumarKV** [comment]
Got this issue fixed.. I was trying to launch an application using Bundle ID which seems to be not working anymore with new build.. Replaced bundle ID with apps location and it started working..

@imurchie 
Why are we not able to initialize Appium driver by passing BUNDLE ID to APP capability.. ?

Logs:
[MJSONWP] Encountered internal error running command: Error: **Could not find app at** com.facebook.test.enterpriseappstore

**Comment by imurchie** [comment]
This has been fixed under another issue.
