### ISSUE TITLE
Socket hang up when running tests on two phones connected to one computer

### ISSUE THREAD

**Issue by sravanmedarapu** [appium/appium#7270]
@marwissqr commented on [Mon Nov 21 2016](https://github.com/appium/appium-uiautomator2-driver/issues/47)

Below error is happening when tests are run simultaneously on two phones connected to one computer.
```
[MJSONWP] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: Error: socket han
g up
    at JWProxy.proxy$ (lib/jsonwp-proxy/proxy.js:122:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
```

Problem probably lies here:
`node_modules/appium-uiautomator2-driver/lib/driver.js:      this.opts.systemPort = this.opts.systemPort || SYSTEM_PORT_RANGE[0];`

Instead of using port range it always selects the same 8200 port:
`info: [debug] [ADB] Forwarding system: 8200 to device: 6790`

Appium version 1.6.0

---

@wojciwojci commented on [Mon Nov 21 2016](https://github.com/appium/appium-uiautomator2-driver/issues/47#issuecomment-261928508)

Hi, i am facing exactly the same problem, looking forward for some solution!

---

@sravanmedarapu commented on [Mon Nov 21 2016](https://github.com/appium/appium-uiautomator2-driver/issues/47#issuecomment-261935680)

Till this fixed. As a workaround, you can use set capability `systemPort` to `available PORT_NUMBER`. 

EX:
`capabilities.setCapability("systemPort", "8181")`

---

@marwissqr commented on [Tue Nov 22 2016](https://github.com/appium/appium-uiautomator2-driver/issues/47#issuecomment-262173262)

Great, thanks!

**Comment by sravanmedarapu** [comment]
Using appium-uiautomator2-driver@0.2.0 should fix the issue.
