### ISSUE TITLE
Unable to launch app with unlocked display (Fingerprint recognition enabled) in Coolpad Note 3 

### ISSUE THREAD

**Issue by sudeepsenmindfire** [appium/appium#7294]
## The problem

I am trying to run a simple script in Java Project to launch the Flipkart application in a real device and navigate to few category of items available. The device is kept in unlocked state and the display is active. The Fingerprint recognition is enabled. I am running the script using Eclipse IDE.
But the script fails to open the app, and at the end I am getting this issues:

 info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: com.flipkart.android/.SplashActivity never started. Current: com.yulong.android.launcher3/.Launcher)","origValue":"com.flipkart.android/.SplashActivity never started. Current: com.yulong.android.launcher3/.Launcher"},"sessionId":null}
> info: <-- POST /wd/hub/session 500 25490.826 ms - 320 

Device under test: **Coolpad Note 3**
http://gadgets.ndtv.com/coolpad-note-3-3023

However I tried the same scenario in Moto Z Play with Fingerprint recognition enabled, and the script worked fine with no issues.

If anyone has any solution to issue, please suggest.

## Environment

* Appium version: 1.4.16.1
* Desktop OS/version used to run Appium: Windows 8.1
* Mobile platform/version under test: Android 5.1.1
* Real device or emulator/simulator: Real Device 
* Device Name: Coolpad Note 3

## Link to Appium logs

info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: com.flipkart.android/.SplashActivity never started. Current: com.yulong.android.launcher3/.Launcher)","origValue":"com.flipkart.android/.SplashActivity never started. Current: com.yulong.android.launcher3/.Launcher"},"sessionId":null}
> info: <-- POST /wd/hub/session 500 25490.826 ms - 320 

## Code To Reproduce Issue [ Good To Have ]

package amazon;

import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.android.AndroidElement;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.CapabilityType;
import org.openqa.selenium.remote.DesiredCapabilities;
 
public class StartApplication {
 
		private static AndroidDriver driver;
		public static void main(String[] args) throws MalformedURLException,              InterruptedException {

                       DesiredCapabilities capabilities = new DesiredCapabilities();
			capabilities.setCapability(CapabilityType.BROWSER_NAME, "");
			capabilities.setCapability(CapabilityType.VERSION, "4.4.2");
			capabilities.setCapability("deviceName", "VSKFI7DULZJ7FYLR");
			capabilities.setCapability("platformVersion", "5.1.1");
			capabilities.setCapability("platformName", "Android");
                       capabilities.setCapability("appPackage", "com.flipkart.android");
			capabilities.setCapability("appActivity", "com.flipkart.android.SplashActivity");

                       driver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
			driver.manage().timeouts().implicitlyWait(80, TimeUnit.SECONDS);
			Thread.sleep(5000)

                        driver.findElement(By.name("Lifestyle")).click();
			Thread.sleep(2000);
			driver.findElement(By.name("Men")).click();
			Thread.sleep(3000);

                       driver.quit();
 
	}
 
}

**Comment by dpgraham** [comment]
Could you provide a gist of the full logs? It would be helpful to see what happened prior to the call to ```wd/hub/session```

**Comment by sudeepsenmindfire** [comment]
This is complete log in Appium window:
===================================
> Checking if an update is available
> Update not available
> Launching Appium server with command: C:\Program Files (x86)\Appium\node.exe lib\server\main.js --address 127.0.0.1 --port 4723 --platform-name Android --platform-version 22 --automation-name Appium --log-no-color
> Killed Node Server.
> Appium server process ended
> Launching Appium server with command: C:\Program Files (x86)\Appium\node.exe lib\server\main.js --address 127.0.0.1 --port 4723 --platform-name Android --platform-version 22 --automation-name Appium --log-no-color
> Killed Node Server.
> Appium server process ended
> Launching Appium server with command: C:\Program Files (x86)\Appium\node.exe lib\server\main.js --address 127.0.0.1 --port 4723 --platform-name Android --platform-version 22 --automation-name Appium --log-no-color
> info: Welcome to Appium v1.4.16 (REV ae6877eff263066b26328d457bd285c0cc62430d)
> info: Appium REST http interface listener started on 127.0.0.1:4723
> info: [debug] Non-default server args: {"address":"127.0.0.1","logNoColors":true,"platformName":"Android","platformVersion":"22","automationName":"Appium"}
> info: Console LogLevel: debug
> info: --> POST /wd/hub/session {"desiredCapabilities":{"appPackage":"com.flipkart.android","appActivity":"com.flipkart.android.SplashActivity","platformVersion":"5.1.1","browserName":"","platformName":"Android","version":"4.4.2","deviceName":"VSKFI7DULZJ7FYLR"}}
> info: Client User-Agent string: Apache-HttpClient/4.3.6 (java 1.5)
> info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : version
> info: [debug] Didn't get app but did get Android package, will attempt to launch it on the device
> info: [debug] Creating new appium session e49a3bd8-827f-4ead-8940-28ba93b012c9
> info: Starting android appium
> info: [debug] Getting Java version
> info: Java version is: 1.8.0_102
> info: [debug] Checking whether adb is present
> info: [debug] Using adb from C:\Users\sudeep.sen\AppData\Local\Android\android-sdk\platform-tools\adb.exe
> warn: No app capability, can't parse package/activity
> info: [debug] Using fast reset? true
> info: [debug] Preparing device for session
> info: [debug] Not checking whether app is present since we are assuming it's already on the device
> info: Retrieving device
> info: [debug] Trying to find a connected android device
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: C:\Users\sudeep.sen\AppData\Local\Android\android-sdk\platform-tools\adb.exe devices
> info: [debug] 1 device(s) connected
> info: Found device VSKFI7DULZJ7FYLR
> info: [debug] Setting device id to VSKFI7DULZJ7FYLR
> info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
> info: [debug] executing cmd: C:\Users\sudeep.sen\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s VSKFI7DULZJ7FYLR wait-for-device
> info: [debug] executing cmd: C:\Users\sudeep.sen\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s VSKFI7DULZJ7FYLR shell "echo 'ready'"
> info: [debug] Starting logcat capture
> info: [debug] Getting device API level
> info: [debug] executing cmd: C:\Users\sudeep.sen\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s VSKFI7DULZJ7FYLR shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 22
> info: Device API level is: 22
> info: [debug] Extracting strings for language: default
> info: [debug] Apk doesn't exist locally
> info: [debug] Could not get strings, but it looks like we had an old strings file anyway, so ignoring
> info: [debug] executing cmd: C:\Users\sudeep.sen\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s VSKFI7DULZJ7FYLR shell "rm -rf /data/local/tmp/strings.json"
> info: [debug] Not uninstalling app since server not started with --full-reset
> info: [debug] Skipping install since we launched with a package instead of an app path
> info: [debug] Forwarding system:4724 to device:4724
> info: [debug] executing cmd: C:\Users\sudeep.sen\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s VSKFI7DULZJ7FYLR forward tcp:4724 tcp:4724
> info: [debug] Pushing appium bootstrap to device...
> info: [debug] executing cmd: C:\Users\sudeep.sen\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s VSKFI7DULZJ7FYLR push "C:\\Program Files (x86)\\Appium\\node_modules\\appium\\build\\android_bootstrap\\AppiumBootstrap.jar" /data/local/tmp/
> info: [debug] Pushing settings apk to device...
> info: [debug] executing cmd: C:\Users\sudeep.sen\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s VSKFI7DULZJ7FYLR install "C:\Program Files (x86)\Appium\node_modules\appium\build\settings_apk\settings_apk-debug.apk"
> info: [debug] Pushing unlock helper app to device...
> info: [debug] executing cmd: C:\Users\sudeep.sen\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s VSKFI7DULZJ7FYLR install "C:\Program Files (x86)\Appium\node_modules\appium\build\unlock_apk\unlock_apk-debug.apk"
> info: Starting App
> info: [debug] Attempting to kill all 'uiautomator' processes
> info: [debug] Getting all processes with 'uiautomator'
> info: [debug] executing cmd: C:\Users\sudeep.sen\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s VSKFI7DULZJ7FYLR shell "ps 'uiautomator'"
> info: [debug] No matching processes found
> info: [debug] Running bootstrap
> info: [debug] spawning: C:\Users\sudeep.sen\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s VSKFI7DULZJ7FYLR shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.Bootstrap -e pkg com.flipkart.android -e disableAndroidWatchers false
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
> info: [debug] [UIAUTOMATOR STDOUT] io.appium.android.bootstrap.Bootstrap:
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 1
> info: [debug] [BOOTSTRAP] [debug] Socket opened on port 4724
> info: [debug] [BOOTSTRAP] [debug] Appium Socket Server Ready
> info: [debug] [BOOTSTRAP] [debug] Loading json...
> info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.
> info: [debug] Waking up device if it's not alive
> info: [debug] Pushing command to appium work queue: ["wake",{}]
> info: [debug] [BOOTSTRAP] [debug] Client connected
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"wake","params":{}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: wake
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":true}
> info: [debug] executing cmd: C:\Users\sudeep.sen\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s VSKFI7DULZJ7FYLR shell "dumpsys window"
> info: [debug] Screen already unlocked, continuing.
> info: [debug] Pushing command to appium work queue: ["getDataDir",{}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"getDataDir","params":{}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: getDataDir
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":"\/data\/local\/tmp"}
> info: [debug] dataDir set to: /data/local/tmp
> info: [debug] Pushing command to appium work queue: ["compressedLayoutHierarchy",{"compressLayout":false}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"compressedLayoutHierarchy","params":{"compressLayout":false}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: compressedLayoutHierarchy
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":false}
> info: [debug] Getting device API level
> info: [debug] executing cmd: C:\Users\sudeep.sen\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s VSKFI7DULZJ7FYLR shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 22
> info: [debug] executing cmd: C:\Users\sudeep.sen\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s VSKFI7DULZJ7FYLR shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n com.flipkart.android/com.flipkart.android.SplashActivity"
> info: [debug] Waiting for pkg "com.flipkart.android" and activity "com.flipkart.android.SplashActivity" to be focused
> info: [debug] Getting focused package and activity
> info: [debug] executing cmd: C:\Users\sudeep.sen\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s VSKFI7DULZJ7FYLR shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing cmd: C:\Users\sudeep.sen\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s VSKFI7DULZJ7FYLR shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing cmd: C:\Users\sudeep.sen\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s VSKFI7DULZJ7FYLR shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing cmd: C:\Users\sudeep.sen\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s VSKFI7DULZJ7FYLR shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing cmd: C:\Users\sudeep.sen\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s VSKFI7DULZJ7FYLR shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing cmd: C:\Users\sudeep.sen\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s VSKFI7DULZJ7FYLR shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing cmd: C:\Users\sudeep.sen\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s VSKFI7DULZJ7FYLR shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing cmd: C:\Users\sudeep.sen\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s VSKFI7DULZJ7FYLR shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing cmd: C:\Users\sudeep.sen\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s VSKFI7DULZJ7FYLR shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing cmd: C:\Users\sudeep.sen\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s VSKFI7DULZJ7FYLR shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing cmd: C:\Users\sudeep.sen\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s VSKFI7DULZJ7FYLR shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing cmd: C:\Users\sudeep.sen\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s VSKFI7DULZJ7FYLR shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing cmd: C:\Users\sudeep.sen\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s VSKFI7DULZJ7FYLR shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing cmd: C:\Users\sudeep.sen\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s VSKFI7DULZJ7FYLR shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing cmd: C:\Users\sudeep.sen\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s VSKFI7DULZJ7FYLR shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing cmd: C:\Users\sudeep.sen\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s VSKFI7DULZJ7FYLR shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing cmd: C:\Users\sudeep.sen\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s VSKFI7DULZJ7FYLR shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing cmd: C:\Users\sudeep.sen\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s VSKFI7DULZJ7FYLR shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing cmd: C:\Users\sudeep.sen\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s VSKFI7DULZJ7FYLR shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing cmd: C:\Users\sudeep.sen\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s VSKFI7DULZJ7FYLR shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing cmd: C:\Users\sudeep.sen\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s VSKFI7DULZJ7FYLR shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing cmd: C:\Users\sudeep.sen\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s VSKFI7DULZJ7FYLR shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing cmd: C:\Users\sudeep.sen\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s VSKFI7DULZJ7FYLR shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing cmd: C:\Users\sudeep.sen\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s VSKFI7DULZJ7FYLR shell "dumpsys window windows"
> error: com.flipkart.android/.SplashActivity never started. Current: com.yulong.android.launcher3/.Launcher
> info: [debug] Stopping logcat capture
> info: [debug] Logcat terminated with code null, signal SIGTERM
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"shutdown"}
> info: [debug] [BOOTSTRAP] [debug] Got command of type SHUTDOWN
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":"OK, shutting down"}
> info: [debug] [UIAUTOMATOR STDOUT] [CDS]close[4724]
> info: [debug] [BOOTSTRAP] [debug] Closed client connection
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=.
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 0
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
> info: [debug] [UIAUTOMATOR STDOUT] Test results for WatcherResultPrinter=.
> info: [debug] [UIAUTOMATOR STDOUT] Time: 22.061
> info: [debug] [UIAUTOMATOR STDOUT] OK (1 test)
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: -1
> info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
> info: [debug] UiAutomator shut down normally
> info: [debug] Cleaning up android objects
> info: [debug] Cleaning up appium session
> error: Failed to start an Appium session, err was: Error: com.flipkart.android/.SplashActivity never started. Current: com.yulong.android.launcher3/.Launcher
> info: [debug] Error: com.flipkart.android/.SplashActivity never started. Current: com.yulong.android.launcher3/.Launcher
>     at [object Object].<anonymous> (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\lib\adb.js:1314:12)
>     at [object Object].<anonymous> (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\lib\adb.js:1258:7)
>     at [object Object].<anonymous> (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\lib\adb.js:180:9)
>     at ChildProcess.exithandler (child_process.js:742:7)
>     at ChildProcess.emit (events.js:110:17)
>     at maybeClose (child_process.js:1016:16)
>     at Process.ChildProcess._handle.onexit (child_process.js:1088:5)
> info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: com.flipkart.android/.SplashActivity never started. Current: com.yulong.android.launcher3/.Launcher)","origValue":"com.flipkart.android/.SplashActivity never started. Current: com.yulong.android.launcher3/.Launcher"},"sessionId":null}
> info: <-- POST /wd/hub/session 500 27060.605 ms - 320

**Comment by jlipps** [comment]
@sudeepsenmindfire we stopped supporting appium 1.4.16 a long time ago; can you see if this reproduces on the most recent appium version?

**Comment by sudeepsenmindfire** [comment]
@jlipps while starting the Appium server it shows no update available.
Can you please mention the exact Appium version with which you want me to retest?

**Comment by vikramvi** [comment]
@sudeepsenmindfire with 1.6.2 https://github.com/appium/appium/releases

**Comment by dpgraham** [comment]
Closing due to inactivity.
