### ISSUE TITLE
Chromedriver Install issues: migration from appium-chromedriver repo

### ISSUE THREAD

**Issue by rkavalap** [appium/appium#7296]
Tracking bug for all chromedriver install issues. 
Including installation behind proxy etc.

**Comment by WitoldGit** [comment]
I have a problem installing the appium behind the proxy. This is due to the installation of the appium-chromedriver. See the stack trace:
`info Chromedriver Install Downloading http://npm.taobao.org/mirrors/chromedriver/2.28/chromedriver_win32.zip...
RequestError: Error: connect EACCES 114.55.80.225:80
    at new RequestError (C:\Users\aaaaaaaaaaaa\AppData\Roaming\npm\node_modules\appium-chromedriver\node_modules\request-promise\lib\errors.js:11:15)
    at Request.RP$callback [as _callback] (C:\Users\aaaaaaaaaaaa\AppData\Roaming\npm\node_modules\appium-chromedriver\node_modules\request-promise\lib\rp.js:60:32)
    at self.callback (C:\Users\aaaaaaaaaaaa\AppData\Roaming\npm\node_modules\appium-chromedriver\node_modules\request\request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (C:\Users\aaaaaaaaaaaa\AppData\Roaming\npm\node_modules\appium-chromedriver\node_modules\request\request.js:884:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1281:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`

I modified locally the appium-chromedriver-2.11.0\lib\install.js to use a proxy like in the post 
https://github.com/request/request-promise/issues/130#issuecomment-267528293. This works!

The appium-chromediver is just a part of the appium installation. When I install the appium-chromedriver separately as above, the appium installation executes nevertheless its own appiumchromedriver installation step which fails.

**Could you please enhance the installation of the appium-chromedriver so that an npm configured proxy or a proxy configured through environment variable is used?**
