### ISSUE TITLE
"WebDriverAgentRunner May Slow Down Your iPhone" system popup

### ISSUE THREAD

**Issue by JaniJegoroff** [appium/appium#7303]
## The problem

I need to reset simulator data before running certain scenarios. Since `reset` feature has been broken for a long time (see https://github.com/appium/appium/issues/4955 and https://github.com/appium/appium/issues/4956) I have been using workaround which have been working very well until `Appium 1.6.1` release:
```
def reset_app
  # TODO
  # https://github.com/appium/appium/issues/4956
  # https://github.com/appium/appium/issues/4955
  # reset

  `osascript -e 'tell application "Simulator" to quit'`
  `xcrun simctl erase all`

  restart
end
```

While restarting simulator Appium 1.6.1 throws an error and system popup dialog is shown saying `WebDriverAgentRunner May Slow Down Your iPhone` making Appium tests pretty much unusable.
```
[Appium] Had trouble ending session aacb0420-1aba-486e-adee-6e064390a290: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8100
[MJSONWP] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8100
    at JWProxy.proxy$ (../../../lib/jsonwp-proxy/proxy.js:126:13)
    at tryCatch (/Users/janijegoroff/projects/mobile-ios-app/mobile-common/bdd/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/janijegoroff/projects/mobile-ios-app/mobile-common/bdd/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/janijegoroff/projects/mobile-ios-app/mobile-common/bdd/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/janijegoroff/projects/mobile-ios-app/mobile-common/bdd/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Users/janijegoroff/projects/mobile-ios-app/mobile-common/bdd/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:108:47)
    at /Users/janijegoroff/projects/mobile-ios-app/mobile-common/bdd/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:119:28
    at flush (/Users/janijegoroff/projects/mobile-ios-app/mobile-common/bdd/node_modules/appium/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at doNTCallback0 (node.js:430:9)
    at process._tickCallback (node.js:359:13)
```

<img width="379" alt="screenshot" src="https://cloud.githubusercontent.com/assets/2363231/20667663/4c71a722-b562-11e6-9180-6a0efbf1e92e.png">

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.1
* Last Appium version that did not exhibit the issue (if applicable): 1.6.0-beta
* Desktop OS/version used to run Appium: Mac OS X Sierra 10.12.1
* Node.js version (unless using Appium.app|exe): v.5.1.1
* Mobile platform/version under test: iOS 10.1 iPhone 7
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: CLI

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Appium logs

https://gist.github.com/JaniJegoroff/51b84fb7a26136ad8e778e4abfab52c8

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Download the newest version of WDA from https://github.com/facebook/WebDriverAgent and replace your local Appium source with it: 

```
/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
```

Looks like Appium devs just forgot to update WDA in the recent Appium release :(

**Comment by JaniJegoroff** [comment]
Awesome, thanks for the workaround. Looks so much better now. 👍

**Comment by mykola-mokhnach** [comment]
The newest WDA source has xpath search patch included as well, which makes xpath searches way faster than before

**Comment by JaniJegoroff** [comment]
Tests are running better now. However, I still see this error quite often:

```
[Appium] Had trouble ending session 57dab009-6ecb-4356-ab4b-1da8518e9a33: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8100
[MJSONWP] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8100
    at JWProxy.proxy$ (../../../lib/jsonwp-proxy/proxy.js:126:13)
    at tryCatch (/Users/janijegoroff/projects/mobile-ios-app/mobile-common/bdd/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/janijegoroff/projects/mobile-ios-app/mobile-common/bdd/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/janijegoroff/projects/mobile-ios-app/mobile-common/bdd/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/janijegoroff/projects/mobile-ios-app/mobile-common/bdd/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Users/janijegoroff/projects/mobile-ios-app/mobile-common/bdd/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:108:47)
    at /Users/janijegoroff/projects/mobile-ios-app/mobile-common/bdd/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:119:28
    at flush (/Users/janijegoroff/projects/mobile-ios-app/mobile-common/bdd/node_modules/appium/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at doNTCallback0 (node.js:430:9)
    at process._tickCallback (node.js:359:13)
```

Looks like it is related to the use case when I need to reset data before running scenarios.

**Comment by JaniJegoroff** [comment]
I had a closer look to this issue and it is related to a case when I need to reset simulator data. Issue description updated.

**Comment by JaniJegoroff** [comment]
I managed to workaround `reset` feature and all tests running stable now. Closing this issue since we have dedicated tickets open for reset issues.
