### ISSUE TITLE
Appium 1.6.1: Set the cap 'realDeviceLogger' could not start a new session.

### ISSUE THREAD

**Issue by CrossShuo** [appium/appium#7319]
## The problem

When i set the cap 'realDeviceLogger', then i get 'Exception in thread "main" org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session.'

## Environment

* Appium version 1.6.1
* MacOS 10.11.5
* Xcode 8.1 
* node 7.2.0
* iOS 10.1.1
* iPhone 6

## Details
`  capabilities = new DesiredCapabilities();
        capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "XCUITest");
        capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
        capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "10.1.1");
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "CROSS");
        capabilities.setCapability(MobileCapabilityType.UDID,"a5dad71a3b343d8566732eud07e6120dabd6da");
        capabilities.setCapability(IOSMobileCapabilityType.BUNDLE_ID, "com.taosustdio.uitestapp");
        capabilities.setCapability("realDeviceLogger", "/Users/tete/.nvm/versions/node/v7.2.0/lib/node_modules/deviceconsole/deviceconsole");
        capabilities.setCapability(IOSMobileCapabilityType.SHOW_IOS_LOG, true);
        capabilities.setCapability("showXcodeLog", true);`
      
## Appium logs

Appium] Welcome to Appium v1.6.1
[Appium] Non-default server args:
[Appium]   sessionOverride: true
[Appium]   loglevel: 'info'
[Appium]   defaultCapabilities: { showIOSLog: true,
  showXcodeLog: true,
  realDeviceLogger: '/Users/tete/Desktop/test/deviceConsole/deviceconsole/deviceconsole',
  platformVersion: '10.1.1',
  automationName: 'XCUITest',
  bundleId: 'com.taosustdio.uitestapp',
  platformName: 'iOS',
  udid: 'a5dad71a3b343d8566732eud07e6120dabd6da',
  deviceName: 'CROSS' }
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   showIOSLog: true
[Appium]   showXcodeLog: true
[Appium]   realDeviceLogger: '/Users/tete/Desktop/test/deviceConsole/deviceconsole/deviceconsole'
[Appium]   platformVersion: '10.1.1'
[Appium]   automationName: 'XCUITest'
[Appium]   bundleId: 'com.taosustdio.uitestapp'
[Appium]   platformName: 'iOS'
[Appium]   udid: 'a5dad71a3b343d8566732eud07e6120dabd6da'
[Appium]   deviceName: 'CROSS'
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> GET /wd/hub/status {}
[HTTP] <-- GET /wd/hub/status 200 12 ms - 83 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"showIOSLog":true,"showXcodeLog":true,"realDeviceLogger":"/Users/tete/Desktop/test/deviceConsole/deviceconsole/deviceconsole","platformVersion":"10.1.1","automationName":"XCUITest","bundleId":"com.taosustdio.uitestapp","platformName":"iOS","udid":"a5dad71a3b343d8566732eud07e6120dabd6da","deviceName":"CROSS"}}
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   showIOSLog: true
[Appium]   showXcodeLog: true
[Appium]   realDeviceLogger: '/Users/tete/Desktop/test/deviceConsole/deviceconsole/deviceconsole'
[Appium]   platformVersion: '10.1.1'
[Appium]   automationName: 'XCUITest'
[Appium]   bundleId: 'com.taosustdio.uitestapp'
[Appium]   platformName: 'iOS'
[Appium]   udid: 'a5dad71a3b343d8566732eud07e6120dabd6da'
[Appium]   deviceName: 'CROSS'
[BaseDriver] Session created with session id: 1e99781c-59b8-4b8b-9a64-740fd72175b0
[XCUITest] Determining device to run tests on: udid: 'a5dad71a3b343d8566732eud07e6120dabd6da', real device: true
[XCUITest] Setting up real device
[XCUITest] Using WDA path: '/Users/tete/.nvm/versions/node/v7.2.0/lib/node_modules/appium/node_modules/.2.2.0@appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Users/tete/.nvm/versions/node/v7.2.0/lib/node_modules/appium/node_modules/.2.2.0@appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
Exception in thread "main" org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'tetedeiMac.local', ip: '192.168.1.104', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.5', java.version: '1.8.0_91'
Driver info: driver.version: IOSDriver
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:665)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:40)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:249)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:36)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:114)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:132)
	at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:82)
	at SmokeTest.main(SmokeTest.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: org.openqa.selenium.WebDriverException: org.apache.http.conn.HttpHostConnectException: Connect to 0.0.0.0:4723 [/0.0.0.0] failed: Connection refused
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'tetedeiMac.local', ip: '192.168.1.104', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.5', java.version: '1.8.0_91'
Driver info: driver.version: IOSDriver
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:84)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:644)
	... 16 more
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 0.0.0.0:4723 [/0.0.0.0] failed: Connection refused
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:162)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:90)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:69)
	... 17 more
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:204)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	... 30 more

But when i cancel the cap 'realDeviceLogger', i get the following logs:
[https://gist.github.com/CrossShuo/b851e92769dd5ffd7fbe0c276fdd0e30](url)

**Comment by jlipps** [comment]
What happens if you run deviceconsole on its own?

**Comment by CrossShuo** [comment]
@jlipps run deviceconsole in the terminal, get the following:
~/.nvm/versions/node/v7.2.0/lib/node_modules/deviceconsole ./deviceconsole
Nov 30 10:26:28 CROSS securityd[105] <Notice>: cert[0]: NonEmptySubject =(leaf)[]> 0
Nov 30 10:26:28 CROSS securityd[105] <Notice>: cert[0]: AnchorTrusted =(leaf)[force]> 0
Nov 30 10:26:29 CROSS securityd[105] <Notice>: cert[0]: NonEmptySubject =(leaf)[]> 0
Nov 30 10:26:29 CROSS securityd[105] <Notice>: cert[0]: AnchorTrusted =(leaf)[force]> 0
Nov 30 10:26:29 CROSS securityd[105] <Notice>: cert[0]: NonEmptySubject =(leaf)[]> 0
Nov 30 10:26:29 CROSS securityd[105] <Notice>: cert[0]: AnchorTrusted =(leaf)[force]> 0
Nov 30 10:26:29 CROSS kernel(AppleBiometricSensor)[0] <Debug>: entry
Nov 30 10:26:29 CROSS kernel(AppleBiometricSensor)[0] <Debug>: entry
Nov 30 10:26:29 CROSS kernel(AppleBiometricSensor)[0] <Debug>: txBufferLength=7 rxBufferLength=23
Nov 30 10:26:29 CROSS kernel(AppleBiometricSensor)[0] <Debug>: Wrote:     7B | 0x80 0x10 0x00 0x07 0x00 0x00 0x00
Nov 30 10:26:29 CROSS kernel(AppleBiometricSensor)[0] <Debug>:  Read:    23B | 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x80 0x20 0x00 0x10 0x00 0x00 0x00 0x11 0x01 0x01 0x00 0x04 0xb1 0x02 0x0c 0x00
Nov 30 10:26:29 CROSS kernel(AppleBiometricSensor)[0] <Debug>: Status={0x80, 0x20, 00, 0x10, 00, 00, 00, 0x11, 0x1, 0x1, 00, 0x4, 0xb1, 0x2, 0xc, 00}
Nov 30 10:26:29 CROSS kernel(AppleBiometricSensor)[0] <Debug>: exit, err=0x0
Nov 30 10:26:29 CROSS kernel(AppleBiometricSensor)[0] <Debug>: mask=0xFF, bad=false
Nov 30 10:26:29 CROSS kernel(AppleBiometricSensor)[0] <Debug>: exit
Nov 30 10:26:29 CROSS kernel(AppleBiometricSensor)[0] <Debug>: entry
Nov 30 10:26:29 CROSS kernel(AppleBiometricSensor)[0] <Debug>: exit
Nov 30 10:26:29 CROSS securityd[105] <Notice>: cert[0]: NonEmptySubject =(leaf)[]> 0
Nov 30 10:26:29 CROSS securityd[105] <Notice>: cert[0]: AnchorTrusted =(leaf)[force]> 0
......

**Comment by jlipps** [comment]
Are you sure you've pasted the full Appium log? It ends with `[XCUITest] Launching WebDriverAgent on the device`? I would not expect the server to print that and stop. Are you running Appium from within Java or something? What happens if you run Appium on its own and not as a Java service?

**Comment by CrossShuo** [comment]
@jlipps  i use `AppiumDriverLocalService` (set Capabilities and GeneralServerFlag) and start Appium service.
run appium in terminal, seems ok.
~appium &
[1] 23425
~ [Appium] Welcome to Appium v1.6.1
[Appium] Appium REST http interface listener started on 0.0.0.0:4723

**Comment by CrossShuo** [comment]
@jlipps And i run the test on Simulator is OK.

**Comment by jlipps** [comment]
@CrossShuo I mean to run Appium on its own and then actually run a test against it.

**Comment by CrossShuo** [comment]
@jlipps run Appium on its own and begin the test is OK. Something wrong with my code?
 ` ServiceStart sS = new ServiceStart();
     if(sS.localService == null || !sS.localService.isRunning()) {
            throw new RuntimeException("Appium server is not started!");}
      IOSDriver<MobileElement> iDriver = new IOSDriver<MobileElement>(sS.localService, sS.capabilities);`

**Comment by jlipps** [comment]
I'm not sure, @CrossShuo but we don't support the appium service starter. For that, please link this issue at the java client repo (I think that's where the service starter is?). Thanks.

**Comment by CrossShuo** [comment]
@jlipps ok,thx jlipps.
