### ISSUE TITLE
touchMultiPerform fails with error Cannot read property 'action' of undefined

### ISSUE THREAD

**Issue by jlipps** [appium/appium#7345]
@APshenkin commented on [Thu Dec 01 2016](https://github.com/appium/appium-android-driver/issues/195)

```
[debug] [MJSONWP] Calling AppiumDriver.performMultiAction() with args: [[{"action":"press","options":{"x":100,"y":250}},{"action":"moveTo","options":{"x":300,"y":100}},{"action":"release"}],null,null,null,null,null,"cdb0e76b-e809-4ce5-a52e-1a83766464e0"]
[MJSONWP] Encountered internal error running command: TypeError: Cannot read property 'action' of undefined
    at AndroidDriver.callee$0$0$ (../../../lib/commands/touch.js:198:32)
    at tryCatch (C:\Users\andrey.pshenkin\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\andrey.pshenkin\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\andrey.pshenkin\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at invoke (C:\Users\andrey.pshenkin\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at enqueueResult (C:\Users\andrey.pshenkin\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:185:17)
    at Promise.F (C:\Users\andrey.pshenkin\AppData\Roaming\npm\node_modules\appium\node_modules\core-js\library\modules\$.export.js:30:36)
    at AsyncIterator.enqueue (C:\Users\andrey.pshenkin\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (C:\Users\andrey.pshenkin\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at Object.runtime.async (C:\Users\andrey.pshenkin\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:209:12)
    at AndroidDriver.callee$0$0 (../../../lib/commands/touch.js:271:21)
    at AndroidDriver.callee$1$0$ (../../../lib/commands/touch.js:301:23)
    at tryCatch (C:\Users\andrey.pshenkin\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\andrey.pshenkin\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\andrey.pshenkin\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at invoke (C:\Users\andrey.pshenkin\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at enqueueResult (C:\Users\andrey.pshenkin\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:185:17)
    at Promise.F (C:\Users\andrey.pshenkin\AppData\Roaming\npm\node_modules\appium\node_modules\core-js\library\modules\$.export.js:30:36)
    at AsyncIterator.enqueue (C:\Users\andrey.pshenkin\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (C:\Users\andrey.pshenkin\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at Object.runtime.async (C:\Users\andrey.pshenkin\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:209:12)
    at callee$1$0 (../../../lib/commands/touch.js:300:53)
    at asyncmap$ (lib/asyncbox.js:75:24)
    at tryCatch (C:\Users\andrey.pshenkin\AppData\Roaming\npm\node_modules\appium\node_modules\asyncbox\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\andrey.pshenkin\AppData\Roaming\npm\node_modules\appium\node_modules\asyncbox\node_modules\babel-runtime\regenerator\runtime.js:294:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\andrey.pshenkin\AppData\Roaming\npm\node_modules\appium\node_modules\asyncbox\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at invoke (C:\Users\andrey.pshenkin\AppData\Roaming\npm\node_modules\appium\node_modules\asyncbox\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at enqueueResult (C:\Users\andrey.pshenkin\AppData\Roaming\npm\node_modules\appium\node_modules\asyncbox\node_modules\babel-runtime\regenerator\runtime.js:167:17)
    at Promise.exp (C:\Users\andrey.pshenkin\AppData\Roaming\npm\node_modules\appium\node_modules\asyncbox\node_modules\core-js\library\modules\$.def.js:38:36)
    at AsyncIterator.enqueue (C:\Users\andrey.pshenkin\AppData\Roaming\npm\node_modules\appium\node_modules\asyncbox\node_modules\babel-runtime\regenerator\runtime.js:166:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (C:\Users\andrey.pshenkin\AppData\Roaming\npm\node_modules\appium\node_modules\asyncbox\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at Object.runtime.async (C:\Users\andrey.pshenkin\AppData\Roaming\npm\node_modules\appium\node_modules\asyncbox\node_modules\babel-runtime\regenerator\runtime.js:192:12)
    at asyncmap (lib/asyncbox.js:74:16)
    at AndroidDriver.callee$0$0$ (../../../lib/commands/touch.js:300:22)
    at tryCatch (C:\Users\andrey.pshenkin\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\andrey.pshenkin\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\andrey.pshenkin\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at invoke (C:\Users\andrey.pshenkin\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at enqueueResult (C:\Users\andrey.pshenkin\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:185:17)
    at Promise.F (C:\Users\andrey.pshenkin\AppData\Roaming\npm\node_modules\appium\node_modules\core-js\library\modules\$.export.js:30:36)
    at AsyncIterator.enqueue (C:\Users\andrey.pshenkin\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (C:\Users\andrey.pshenkin\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at Object.runtime.async (C:\Users\andrey.pshenkin\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:209:12)
    at AndroidDriver.callee$0$0 [as performMultiAction] (../../../lib/commands/touch.js:300:13)
    at ../../../lib/basedriver/driver.js:173:24
    at tryCatcher (C:\Users\andrey.pshenkin\AppData\Roaming\npm\node_modules\appium\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\Users\andrey.pshenkin\AppData\Roaming\npm\node_modules\appium\node_modules\bluebird\js\main\promise.js:510:31)
    at Promise._settlePromiseAt (C:\Users\andrey.pshenkin\AppData\Roaming\npm\node_modules\appium\node_modules\bluebird\js\main\promise.js:584:18)
    at Promise._settlePromiseAtPostResolution (C:\Users\andrey.pshenkin\AppData\Roaming\npm\node_modules\appium\node_modules\bluebird\js\main\promise.js:248:10)
    at Async._drainQueue (C:\Users\andrey.pshenkin\AppData\Roaming\npm\node_modules\appium\node_modules\bluebird\js\main\async.js:128:12)
    at Async._drainQueues (C:\Users\andrey.pshenkin\AppData\Roaming\npm\node_modules\appium\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues (C:\Users\andrey.pshenkin\AppData\Roaming\npm\node_modules\appium\node_modules\bluebird\js\main\async.js:15:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
[HTTP] <-- POST /wd/hub/session/cdb0e76b-e809-4ce5-a52e-1a83766464e0/touch/multi/perform 500 26 ms - 213

```

appium version: 1.6.1
Node version 6.9.1

**Comment by jlipps** [comment]
moved this to appium/appium

**Comment by jlipps** [comment]
What does your client code look like? It seems like it's not sending the right data. That is the main problem. But there is also an Appium bug here (we should have a better error message and error handling).

**Comment by imurchie** [comment]
Closing due to inactivity.
