### ISSUE TITLE
Unable to install "WebDriverAgentRunner-Runner" through Xcode after upgrade appium 1.6.2

### ISSUE THREAD

**Issue by Siddh010** [appium/appium#7356]
Unable to install "WebDriverAgentRunner-Runner" through Xcode after upgrade Appium 1.6.2 

## Environment

* Appium version :- 1.6.2
* Last Appium version that did not exhibit the issue (if applicable):   1.6.1
* Mobile platform/version under test:10.0.1
* Real device or emulator/simulator:Real Device
Xcode  :  8

## Details

Not able to install WebDriver Agent Runner  through Xcode in Device.
 Build  "WebDriver Agent Runner project in Xcode  successful but fail to install in device through xcode also.

 I have follow below step :- 
Open WebDriverAgent.xcodeproj in Xcode. Select your development team for both the WebDriverAgentLib and WebDriverAgentRunner targets. This should also auto select Signing Ceritificate.

https://github.com/appium/appium-xcuitest-driver

## Link to Appium logs

debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Using real device logger 'idevicesyslog'
[debug] [XCUITest] Beginning test with command 'xcodebuild build test -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=bd4f254c81b0ca007f813a4a59f5433dce8a9446 -configuration Debug' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Waiting for WebDriverAgent to start on device
[debug] [XCUITest] Log file for xcodebuild test: /Users/gwgmobilelab/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/DA37196F-6269-456A-AEAE-BB6C38EA19E9/Session-WebDriverAgentRunner-2016-12-05_120020-lxgrhy.log
[Xcode] 2016-12-05 12:00:21.338 xcodebuild[7379:39121] Error Domain=com.apple.dtdevicekit Code=-402620392 "Unable to install "WebDriverAgentRunner-Runner"" UserInfo={NSLocalizedDescription=Unable to install "WebDriverAgentRunner-Runner", NSLocalizedRecoverySuggestion=The certificate used to sign "WebDriverAgentRunner-Runner" has either expired or has been revoked. An updated certificate is required to sign and install the application.}

[Xcode] 2016-12-05 12:00:21.338 xcodebuild[7379:39121] Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}

[Xcode] 2016-12-05 12:00:21.351 xcodebuild[7379:39213] Connection peer refused channel request for "dtxproxy:XCTestManager_IDEInterface:XCTestManager_DaemonConnectionInterface"; channel canceled <DTXChannel: 0x7fcfa4dd35d0>

[Xcode] 
Testing failed:

[Xcode] 	Test target WebDriverAgentRunner encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)
** TEST FAILED **

[XCUITest] xcodebuild exited with code '65' and signal 'null'
[XCUITest] Error: xcodebuild failed with code 65
    at SubProcess.<anonymous> (../../lib/webdriveragent.js:332:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)

**Comment by Siddh010** [comment]
Was issue with my developer Certificate ..  hence closing now.
