### ISSUE TITLE
Unable to start XCUITest "Error: Command 'idevice_id -l' errored out: Error: spawn idevice_id ENOENT"

### ISSUE THREAD

**Issue by Kirubaharan235** [appium/appium#7358]
## The problem

I am trying to set and run appium automation our iOS app . Its throwing the below error on XCUITest when I tried to run the code
Error: Command 'idevice_id -l' errored out: Error: spawn idevice_id ENOENT
at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at ChildProcess.<anonymous> (lib/teen_process.js:32:14)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Please help me get it fixed.

## Environment

Appium v1.6.0
iOS 9.3

## Code To Reproduce Issue [ Good To Have ]

service = AppiumDriverLocalService.buildService(new AppiumServiceBuilder().usingAnyFreePort());
	service.start();
	DesiredCapabilities capabilities=DesiredCapabilities.ipad();

	capabilities.setCapability(MobileCapabilityType.PLATFORM, "iOS");

	capabilities.setCapability(MobileCapabilityType.VERSION, "9.3");

	capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "Rafi's iPad");
	capabilities.setCapability(MobileCapabilityType.APP, "/Users/kiruba-xxxx/Library/Developer/Xcode/DerivedData/zohoform-apfvajhhubdtpddzzgymxvssgkev/Build/Products/Release-iphoneos/Zoho Forms.app");
	capabilities.setCapability(MobileCapabilityType.UDID, "5a2f5b798b6f9c60278368ef8a60bb8ca937ae46");//black iPad
	capabilities.setCapability("bundleId", "com.zoho.xxxxx");
	capabilities.setCapability("automationName", "XCUITest");

**Comment by pavanbachu0604** [comment]
Can you please share the logs ?

**Comment by Kirubaharan235** [comment]
Got the solution from appium discuss. Below is the link.

https://discuss.appium.io/t/eclipse-java-unable-to-start-xcuitest-error-command-idevice-id-l-errored-out-error-spawn-idevice-id-enoent-please-help/13622/20
