### ISSUE TITLE
WebDriverAgent process did not end in a timely fashion. Sending SIGHUP signal

### ISSUE THREAD

**Issue by rkavalap** [appium/appium#7423]
@caizhenxing commented on [Wed Aug 31 2016](https://github.com/appium/appium-xcuitest-driver/issues/116)

```
info XCUITest Waiting for WebDriverAgent to start on device
dbug XCUITest Log file for xcodebuild test: /Users/ucar/Library/Developer/Xcode/DerivedData/WebDriverAgent-gpotvrjsfahdcifdswagnrceyloh/Logs/Test/F0162D0B-881B-45C8-92DA-5ED9BC2D034A/Session-2016-09-01_12:38:16-Avdsuc.log
info XCUITest xcodebuild exited with code '65' and signal 'null'
dbug XCUITest xcodebuild failure warrants retry. Retrying...
info XCUITest Shutting down WebDriverAgent
dbug XCUITest WebDriverAgent process did not end in a timely fashion. Sending SIGHUP signal...
ERR! XCUITest Error: Process didn't end after 10000ms
ERR! XCUITest     at Timeout._onTimeout (lib/teen_process.js:234:16)
ERR! XCUITest     at tryOnTimeout (timers.js:228:11)
ERR! XCUITest     at Timer.listOnTimeout (timers.js:202:5)
ERR! XCUITest  Error: Process didn't end after 10000ms
ERR! XCUITest     at Timeout._onTimeout (lib/teen_process.js:234:16)
ERR! XCUITest     at tryOnTimeout (timers.js:228:11)
ERR! XCUITest     at Timer.listOnTimeout (timers.js:202:5)
info XCUITest Shutting down WebDriverAgent
dbug XCUITest WebDriverAgent process did not end in a timely fashion. Sending SIGHUP signal...
ERR! MJSONWP Encountered internal error running command: Error: Process didn't end after 10000ms
ERR! MJSONWP     at Timeout._onTimeout (lib/teen_process.js:234:16)
ERR! MJSONWP     at tryOnTimeout (timers.js:228:11)
ERR! MJSONWP     at Timer.listOnTimeout (timers.js:202:5)
info HTTP <-- POST /wd/hub/session 500 47651 ms - 169
```

what's the reason? pls help me....

---

@imurchie commented on [Tue Sep 06 2016](https://github.com/appium/appium-xcuitest-driver/issues/116#issuecomment-245044383)

The central problem is that xcodebuild is not able to run. There ought to be a newer version of the driver which gives better logging from xcode as to why it failed.

If you post the entire log it might be easier to give some sort of opinion.

---

@punitbisht commented on [Mon Nov 14 2016](https://github.com/appium/appium-xcuitest-driver/issues/116#issuecomment-260426729)

@imurchie Hi, I am also facing same issue. Hence Attaching logs here . what I can understand with client and server logs is that I am able to find the element can not click it.
[log.txt](https://github.com/appium/appium-xcuitest-driver/files/590211/log.txt)

---

@imurchie commented on [Mon Nov 14 2016](https://github.com/appium/appium-xcuitest-driver/issues/116#issuecomment-260434540)

@punitbisht The logs you have posted have no indication that any click is attempted. You successfully find elements and then close the session.

---

@punitbisht commented on [Mon Nov 14 2016](https://github.com/appium/appium-xcuitest-driver/issues/116#issuecomment-260447806)

@imurchie Thanks for replying. My bad for not attaching code snippet. To make the issue more clear I am attaching the code snippet from spec and page files and a new log file. Previous log file was generated  when line # 30 <Appium::TouchAction.new.tap( x: 42, y:200, count: 3).release> was uncommented and #29 was commented in the snippet.
 This recent log file "log_click.txt" is if you execute the attached snippet as it is .

Note : 
Log_tap.txt is the old log file with touch event 
Log_click.txt is the new log file

[log_click.txt](https://github.com/appium/appium-xcuitest-driver/files/590362/log_click.txt)
[log_tap.txt](https://github.com/appium/appium-xcuitest-driver/files/590364/log_tap.txt)
[Snippet.txt](https://github.com/appium/appium-xcuitest-driver/files/590366/Snippet.txt)

---

@imurchie commented on [Mon Nov 14 2016](https://github.com/appium/appium-xcuitest-driver/issues/116#issuecomment-260450371)

Can you post them as gists? I have no interest in downloading text files.

---

@punitbisht commented on [Mon Nov 14 2016](https://github.com/appium/appium-xcuitest-driver/issues/116#issuecomment-260453736)

 Log_tap - https://gist.github.com/punitbisht/9b40af6593dbe04f07bf013266e4acb9
Log_click - https://gist.github.com/punitbisht/7257fdf39c31bbb28c678784c3562a70
Snippet - https://gist.github.com/punitbisht/412e49c3c8d197e37bdf1ec16a7574ca

---

@imurchie commented on [Tue Nov 15 2016](https://github.com/appium/appium-xcuitest-driver/issues/116#issuecomment-260627011)

The click seems to work. The tap logs have no indication that any tap was even tried. 

I guess I'm not sure what the problem is, what I'm supposed to be looking at.

---

@punitbisht commented on [Tue Nov 15 2016](https://github.com/appium/appium-xcuitest-driver/issues/116#issuecomment-260634459)

Thanks, lemme share other app details(may be useful )
1. This is a hybrid app.
2. Available_context returns only native_app
3. Enable UI automation setting is on.
4. I tried with autowebview='true' capability also .

---

@imurchie commented on [Tue Nov 15 2016](https://github.com/appium/appium-xcuitest-driver/issues/116#issuecomment-260639831)

What is the problem? Is it that there ought to be a webview context? The logs you've provided don't indicate any attempt to find contexts or anything like that.

---

@punitbisht commented on [Tue Nov 15 2016](https://github.com/appium/appium-xcuitest-driver/issues/116#issuecomment-260646931)

@imurchie  Problem here is, may be logs are showing that click is working fine but nothing is happening in my app. code just install the app - start the webdriver agent - launch the login screen and then closes the app .

Regarding attempt to find the context - I was interrogating app in arc "appium ruby console" , it is not part of the code .

---

@punitbisht commented on [Tue Nov 15 2016](https://github.com/appium/appium-xcuitest-driver/issues/116#issuecomment-260662136)

@imurchie : I changed the scenario by finding a text edit and sending text to it instead of a button click. 
I am using <
      def emailField
         @found_emailTextField = wait{xpath('//XCUIElementTypeTextField[@name="Username"]')}
         self
      end

```
  def enterEmail(email)
    @found_emailTextField.send_keys email
    #hide_keyboard
  end> 
```

Now sharing the logs of server : https://gist.github.com/punitbisht/98445191afa1f947774804c3d0692568
and client : https://gist.github.com/punitbisht/1276afc9e1b35b6f7b17ea60f147a691

**Comment by rkavalap** [comment]
Closing as dup https://github.com/appium/appium/issues/6970
