### ISSUE TITLE
timeout waiting for simulator

### ISSUE THREAD

**Issue by rkavalap** [appium/appium#7427]
@joshrlesch commented on [Tue Sep 27 2016](https://github.com/appium/appium-xcuitest-driver/issues/190)

We are getting a timeout waiting for the simulator to launch on some lower performance macs. Is there a way to make that timeout a capability. I think it is hardcoded here https://github.com/appium/appium-ios-simulator/blob/a79dbdaeb21bb781a23c16279d1942aa1b84e605/lib/simulator-xcode-6.js#L17

Error from python client

```
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Condition unmet after 60206 ms. Timing out.
```

Error in appium logs

```
2016-09-27 13:53:45:507 - [iOSSim] Tailing simulator logs until we encounter the string "SMS Plugin initialized"
2016-09-27 13:53:45:507 - [iOSSim] We will time out after 60000ms
2016-09-27 13:54:21:526 - [debug] [iOSSim] Waiting an extra 10000ms for the simulator to really finish booting
2016-09-27 13:54:31:527 - [debug] [iOSSim] Done waiting extra time for simulator
2016-09-27 13:54:31:527 - [iOSSim] Simulator booted in 46214ms
```

---

@imurchie commented on [Tue Sep 27 2016](https://github.com/appium/appium-xcuitest-driver/issues/190#issuecomment-249978454)

Can you post the entire logs? That timeout does not throw an error, it just assumes something happened and it missed the boot, and goes on. That timeout is not being triggered here as the sim booted in 36 seconds.

---

@joshrlesch commented on [Tue Sep 27 2016](https://github.com/appium/appium-xcuitest-driver/issues/190#issuecomment-249979404)

shoot, I pasted the wrong output my bad. I will go fishing for the correct logs my bad.

---

@joshrlesch commented on [Tue Sep 27 2016](https://github.com/appium/appium-xcuitest-driver/issues/190#issuecomment-249989766)

@imurchie ah ok so it wasn't a timeout issue. The sim failed to shutdown correctly from a previous test Im guessing. Is there a force kill that needs to happen if the sim gets in a bad state?

```
 12:34:47:722 - [BaseDriver] Session created with session id: 45bcb056-7c32-404c-b159-0a928dc6025e
2016-09-27 12:34:47:763 - [debug] [XCUITest] Xcode version set to '8.0'
2016-09-27 12:34:47:772 - [debug] [XCUITest] iOS SDK Version set to '10.0'
2016-09-27 12:34:48:046 - [iOSSim] Constructing iOS simulator for Xcode version 8.0 with udid 'D05E374A-FEDA-420A-ADEB-403E06EABE53'
2016-09-27 12:34:48:048 - [debug] [iOSSim] Killing any simulator daemons for D05E374A-FEDA-420A-ADEB-403E06EABE53
2016-09-27 12:34:48:101 - [iOSSim] Cleaning simulator D05E374A-FEDA-420A-ADEB-403E06EABE53
2016-09-27 12:34:49:314 - [HTTP] --> GET /wd/hub/status {}
2016-09-27 12:34:49:316 - [MJSONWP] Calling AppiumDriver.getStatus() with args: []
2016-09-27 12:34:50:362 - [debug] [iOSSim] Killing all iOS Simulators
2016-09-27 12:35:50:840 - [iOSSim] The following devices are not in the correct state:
2016-09-27 12:35:50:841 - [iOSSim]     Simulator not shut down: iPhone 6 (undefined, udid: AAD63143-6AE3-4391-B448-13F142F0AD7F) is still in state 'booted'
2016-09-27 12:35:50:854 - [XCUITest] Error: Condition unmet after 60252 ms. Timing out.
    at spin$ (lib/asyncbox.js:118:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/asyncbox/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/asyncbox/node_modules/babel-runtime/regenerator/runtime.js:294:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/asyncbox/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/asyncbox/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: Condition unmet after 60252 ms. Timing out.
    at spin$ (lib/asyncbox.js:118:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/asyncbox/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/asyncbox/node_modules/babel-runtime/regenerator/runtime.js:294:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/asyncbox/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/asyncbox/node_modules/babel-runtime/regenerator/runtime.js:136:37)
2016-09-27 12:35:50:856 - [MJSONWP] Encountered internal error running command: Error: Condition unmet after 60252 ms. Timing out.
    at spin$ (lib/asyncbox.js:118:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/asyncbox/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/asyncbox/node_modules/babel-runtime/regenerator/runtime.js:294:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/asyncbox/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/asyncbox/node_modules/babel-runtime/regenerator/runtime.js:136:37)
2016-09-27 12:35:50:859 - [HTTP] <-- POST /wd/hub/session 500 63177 ms - 180
```

---

@imurchie commented on [Wed Sep 28 2016](https://github.com/appium/appium-xcuitest-driver/issues/190#issuecomment-250173040)

Ok. For some reason the sim isn't being killed. What is the output of `xcrun simctl list`?

---

@joshrlesch commented on [Wed Sep 28 2016](https://github.com/appium/appium-xcuitest-driver/issues/190#issuecomment-250174945)

```
node-mac-12:~ hudl$ xcrun simctl list
== Device Types ==
iPhone 4s (com.apple.CoreSimulator.SimDeviceType.iPhone-4s)
iPhone 5 (com.apple.CoreSimulator.SimDeviceType.iPhone-5)
iPhone 5s (com.apple.CoreSimulator.SimDeviceType.iPhone-5s)
iPhone 6 (com.apple.CoreSimulator.SimDeviceType.iPhone-6)
iPhone 6 Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-6-Plus)
iPhone 6s (com.apple.CoreSimulator.SimDeviceType.iPhone-6s)
iPhone 6s Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-6s-Plus)
iPhone 7 (com.apple.CoreSimulator.SimDeviceType.iPhone-7)
iPhone 7 Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-7-Plus)
iPhone SE (com.apple.CoreSimulator.SimDeviceType.iPhone-SE)
iPad 2 (com.apple.CoreSimulator.SimDeviceType.iPad-2)
iPad Retina (com.apple.CoreSimulator.SimDeviceType.iPad-Retina)
iPad Air (com.apple.CoreSimulator.SimDeviceType.iPad-Air)
iPad Air 2 (com.apple.CoreSimulator.SimDeviceType.iPad-Air-2)
iPad Pro (9.7-inch) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro--9-7-inch-)
iPad Pro (12.9-inch) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro)
Apple TV 1080p (com.apple.CoreSimulator.SimDeviceType.Apple-TV-1080p)
Apple Watch - 38mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-38mm)
Apple Watch - 42mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-42mm)
Apple Watch Series 2 - 38mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-2-38mm)
Apple Watch Series 2 - 42mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-2-42mm)
== Runtimes ==
iOS 9.2 (9.2 - 13C75) (com.apple.CoreSimulator.SimRuntime.iOS-9-2)
iOS 10.0 (10.0 - 14A345) (com.apple.CoreSimulator.SimRuntime.iOS-10-0)
tvOS 10.0 (10.0 - 14T328) (com.apple.CoreSimulator.SimRuntime.tvOS-10-0)
watchOS 3.0 (3.0 - 14S326) (com.apple.CoreSimulator.SimRuntime.watchOS-3-0)
== Devices ==
-- iOS 9.2 --
    iPhone 4s (30C15505-F25E-43DD-8EF3-3AF4D54DD5F3) (Shutdown)
    iPhone 5 (383ECDFA-932C-4F07-8185-90BC349F3380) (Shutdown)
    iPhone 5s (876F51B5-CCAB-48D5-B802-E3D6443BB213) (Shutdown)
    iPhone 6 (5617646F-896A-4A20-82EC-09CAD45BA369) (Shutdown)
    iPhone 6 Plus (137B3190-48A1-4D63-A35F-3AB9647E1273) (Shutdown)
    iPhone 6s (401DA1EF-1D75-4BA0-9BE0-5E56107881ED) (Shutdown)
    iPhone 6s Plus (F62637F3-7C4A-46DA-8CA1-3B1BB35F1094) (Shutdown)
    iPad 2 (26B5F992-D00A-449F-8353-BC72D30F6A1D) (Shutdown)
    iPad Retina (B27EA9C9-25EF-4B33-A900-D3BA8013BB4C) (Shutdown)
    iPad Air (E53EF0B7-5224-4BF4-8E32-1CFAD315F260) (Shutdown)
    iPad Air 2 (D8FDC4A2-5F2B-4983-B944-1A5C86D62B82) (Shutdown)
    iPad Pro (032145B6-B058-4BB2-BCFC-7A59FF274899) (Shutdown)
-- iOS 10.0 --
    iPhone 5 (7D762D4E-CBCC-4883-A7CF-838AC0E6B2E5) (Shutdown)
    iPhone 5s (89B80912-E003-4284-96D5-DB1D0C641C89) (Shutdown)
    iPhone 6 (AAD63143-6AE3-4391-B448-13F142F0AD7F) (Shutdown)
    iPhone 6 Plus (82A5EE5B-EFAB-4097-A303-009FB7D1CDA3) (Shutdown)
    iPhone 6s (1AD2789D-CAA1-4596-9A2A-E1B6699140FD) (Shutdown)
    iPhone 6s Plus (EBB226B1-5EFC-430F-96EC-05084BB63017) (Shutdown)
    iPhone 7 (88C29CD8-DCC8-4B46-A68F-3D7C37227C10) (Shutdown)
    iPhone 7 Plus (FFDDE7FC-1B87-4A5B-8E31-05A8C2268788) (Shutdown)
    iPhone SE (431ECEC1-0362-4798-8140-C1A65972FAC6) (Shutdown)
    iPad Retina (4BC7E23D-6A17-4CFF-9E7F-3E1BFFDB3716) (Shutdown)
    iPad Air (D05E374A-FEDA-420A-ADEB-403E06EABE53) (Shutdown)
    iPad Air 2 (3091881A-EAF6-4794-92FA-A8A22F559D47) (Shutdown)
    iPad Pro (9.7 inch) (C36D95FE-2CE9-46CD-8386-D8C9C73FEB32) (Shutdown)
    iPad Pro (12.9 inch) (A7957CA7-D3B8-4BE3-962E-EF2891227C9A) (Shutdown)
-- tvOS 10.0 --
    Apple TV 1080p (5E89700B-8AE0-4440-A959-FD58A97BEAED) (Shutdown)
-- watchOS 3.0 --
    Apple Watch - 38mm (D8716FA6-6DCE-49DC-B056-0FB5855FE059) (Shutdown)
    Apple Watch - 42mm (0F4E597B-0D3A-48D3-BFE0-7E4009006A50) (Shutdown)
    Apple Watch Series 2 - 38mm (9B87C401-B4F6-444D-8531-A4E12DB302E0) (Shutdown)
    Apple Watch Series 2 - 42mm (2D3463A3-BB87-48F4-8DD9-83C51EE20713) (Shutdown)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.iOS-9-3 --
    iPhone 4s (2A62305F-CAC6-4693-A404-A9342F302D58) (Shutdown) (unavailable, runtime profile not found)
    iPhone 4s (95A9656D-3279-424C-9675-CADF1EFC258C) (Shutdown) (unavailable, runtime profile not found)
    iPhone 5 (A3418770-743F-4053-9FA2-BCBF7743176B) (Shutdown) (unavailable, runtime profile not found)
    iPhone 5s (BA270F0C-8536-4678-8CDC-F9FCC8365914) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6 (77F30E3C-3407-4C5B-BED6-5D107A19866B) (Shutdown) (unavailable, runtime profile not found)
    iPhone_6_01 (8785AC76-0F2F-49B5-AA82-B4A0271820C9) (Shutdown) (unavailable, runtime profile not found)
    iPhone_6_02 (308B34D5-DBA5-43D2-880A-6AB0780E0242) (Shutdown) (unavailable, runtime profile not found)
    iPhone_6_03 (29902321-D1E2-4221-B4D9-9E74B0EF3F44) (Shutdown) (unavailable, runtime profile not found)
    iPhone_6_04 (43B60588-8877-45ED-B7DD-AB110AD6CFEA) (Shutdown) (unavailable, runtime profile not found)
    iPhone_6_05 (DBFB0A6E-9744-409D-B220-1B8A967CCCA3) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6 Plus (E4A7AEED-80EE-41A4-BE43-B15DD045880A) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6s (C956CEB0-572F-40D9-A329-7DF8E2365670) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6s Plus (00B00BC0-5AC8-4F21-99E3-56E02632E92A) (Shutdown) (unavailable, runtime profile not found)
    iPad 2 (089D892D-F176-4B1E-915B-C41E5ACC7408) (Shutdown) (unavailable, runtime profile not found)
    iPad_2_01 (3C502A92-7777-4817-BC4D-5C866DD273D0) (Shutdown) (unavailable, runtime profile not found)
    iPad_2_02 (93158B33-5AA3-468D-BD67-517463899C59) (Shutdown) (unavailable, runtime profile not found)
    iPad_2_03 (BEE8B592-AC55-40E1-87BA-077EB11904BD) (Shutdown) (unavailable, runtime profile not found)
    iPad_2_04 (A19C75DF-FDFB-48A1-90D2-CFDE132E4D29) (Shutdown) (unavailable, runtime profile not found)
    iPad_2_05 (0CAFB1CD-3878-410F-A528-40D59D5FBF1B) (Shutdown) (unavailable, runtime profile not found)
    iPad Retina (E6E6C735-5158-4FA9-9201-4664EB6177AF) (Shutdown) (unavailable, runtime profile not found)
    iPad Air (380CDF28-C519-4FBB-AC13-247B85BE6B4C) (Shutdown) (unavailable, runtime profile not found)
    iPad Air 2 (4758C2EB-BC04-41F5-B7FA-69FB964B8C5E) (Shutdown) (unavailable, runtime profile not found)
    iPad Pro (664E9BFC-2056-4659-AEC5-E37FC030FFFD) (Shutdown) (unavailable, runtime profile not found)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.tvOS-9-2 --
    Apple TV 1080p (1AC39696-DAAF-498E-B0AC-646E3F5647BD) (Shutdown) (unavailable, runtime profile not found)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.watchOS-2-2 --
    Apple Watch - 38mm (6930530F-BD3E-4533-9B9E-172BE18EF4F5) (Shutdown) (unavailable, runtime profile not found)
    Apple Watch - 42mm (6C2F163E-5F0C-4BBB-9A0F-BB59F9C4647B) (Shutdown) (unavailable, runtime profile not found)
== Device Pairs ==
6BEC7849-B6DD-44F1-8C1E-D76A1417E806 (active, disconnected)
    Watch: Apple Watch Series 2 - 38mm (9B87C401-B4F6-444D-8531-A4E12DB302E0) (Shutdown)
    Phone: iPhone 7 (88C29CD8-DCC8-4B46-A68F-3D7C37227C10) (Shutdown)
DDD754F6-A4D9-47ED-8EB1-3901DBF1A199 (active, disconnected)
    Watch: Apple Watch Series 2 - 42mm (2D3463A3-BB87-48F4-8DD9-83C51EE20713) (Shutdown)
    Phone: iPhone 7 Plus (FFDDE7FC-1B87-4A5B-8E31-05A8C2268788) (Shutdown)
5C30181A-DCB2-4AF8-A4B4-7ACEA69FDF1F (unavailable)
    Watch: Apple Watch - 38mm (6930530F-BD3E-4533-9B9E-172BE18EF4F5) (Shutdown)
    Phone: iPhone 6s (C956CEB0-572F-40D9-A329-7DF8E2365670) (Shutdown)
C6A36D35-89B5-43DC-9B1B-B1FBE10299D6 (unavailable)
    Watch: Apple Watch - 42mm (6C2F163E-5F0C-4BBB-9A0F-BB59F9C4647B) (Shutdown)
    Phone: iPhone 6s Plus (00B00BC0-5AC8-4F21-99E3-56E02632E92A) (Shutdown)
```

---

@imurchie commented on [Wed Sep 28 2016](https://github.com/appium/appium-xcuitest-driver/issues/190#issuecomment-250181013)

I presume the problem doesn't happen at this moment, as there are no booted sims?

---

@joshrlesch commented on [Wed Sep 28 2016](https://github.com/appium/appium-xcuitest-driver/issues/190#issuecomment-250184546)

no I manually killed that sim after it happened :/ We can hold off on this issue for now. If it happens again I will get more info on it at the time it happened. Thanks for the help.

---

@imurchie commented on [Wed Sep 28 2016](https://github.com/appium/appium-xcuitest-driver/issues/190#issuecomment-250185114)

Ok. Just post here with as much info as possible if/when it happens again.

Sometimes, though, things just get stuck for no discernible reason. :(

**Comment by dpgraham** [comment]
Closing unless problem happens further
