### ISSUE TITLE
[enhancement] longpress method not inplemented

### ISSUE THREAD

**Issue by rkavalap** [appium/appium#7434]
@dengwei729 commented on [Wed Oct 26 2016](https://github.com/appium/appium-xcuitest-driver/issues/256)

try to longpress on a special point:
code:
`driver.tap([(200, 300)], 200)`

message:

```
Traceback (most recent call last):
  File "/Users/dengwei/Documents/django_test/mysite/test/test_appium.py", line 18, in <module>
    driver.tap([(200, 300)], 200)
  File "/Library/Python/2.7/site-packages/appium/webdriver/webdriver.py", line 203, in tap
    action.perform()
  File "/Library/Python/2.7/site-packages/appium/webdriver/common/touch_action.py", line 94, in perform
    self._driver.execute(Command.TOUCH_ACTION, params)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/appium/webdriver/errorhandler.py", line 29, in check_response
    raise wde
selenium.common.exceptions.WebDriverException: Message: Support for gestures other than Tap is not yet implemented. Please contact an Appium dev
```

**selenium.common.exceptions.WebDriverException: Message: Support for gestures other than Tap is not yet implemented. Please contact an Appium dev**

---

@imurchie commented on [Wed Oct 26 2016](https://github.com/appium/appium-xcuitest-driver/issues/256#issuecomment-256329109)

Can you provide the server logs for the command (the full logs, if possible. Otherwise at least from the HTTP request for this command to the HTTP response). Long press is implemented, but this command might be triggering something else.

**Comment by dpgraham** [comment]
This is using a dated version of XCUITest. 'longPress' wasn't available at the time but should be there now. (https://github.com/appium/appium-xcuitest-driver/commit/372d5bc14cd2c3123156d03ea8c7b842224597d6)
