### ISSUE TITLE
Xcode8.1 version is not yet supported

### ISSUE THREAD

**Issue by FarAwaytarget** [appium/appium#7448]
## The problem

[MJSONWP] Encountered internal error running command: Error: Xcode version [object Object] is not yet supported
 at handleUnsupportedXcode (lib/simulator.js:15:11)
    at getDeviceString$ (lib/simulator.js:44:3)
    at tryCatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
## Environment

* Appium version (or git revision) that exhibits the issue:  1.5.3
* Last Appium version that did not exhibit the issue (if applicable):no
* Desktop OS/version used to run Appium:10.11.5
* Node.js version (unless using Appium.app|exe):6.2.2
* Mobile platform/version under test:10.0.1
* Real device or emulator/simulator: iphone6
* Appium CLI or Appium.app|exe: Appium.app

## Details

Describe in more detail the problem you have been experiencing, if necessary.
hello ,I settings right,but can't running in the devices
## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by JaniJegoroff** [comment]
Since Apple removed UIAutomation support from Xcode8 it will not work with Appium 1.5.3.

**Comment by mykola-mokhnach** [comment]
Switch to Appium 1.6+
1.5.3 will never support Xcode 8+

@triager please close
