### ISSUE TITLE
Unit tests fail on appium-xcuitest-driver

### ISSUE THREAD

**Issue by crummy** [appium/appium#7464]
## The problem

I made a pull request against appium-xcuitest-driver and ran into some issues running unit tests. I removed my changes and the failures still occurred.

## Environment

* Appium version (or git revision) that exhibits the issue: appium-xcuitest-driver 2.4.0
* Desktop OS/version used to run Appium: macOS 10.12.1 (16B2555)
* Node.js version (unless using Appium.app|exe): v7.2.0

## Details

Here's the exception that appears when I run `gulp unit-test`:

```
1) Constructor should have a binary for the webdriver agent:
     AssertionError: expected false to be true
      at doAsserterAsyncAndAddThen (node_modules/chai-as-promised/lib/chai-as-promised.js:296:33)
      at Assertion.<anonymous> (node_modules/chai-as-promised/lib/chai-as-promised.js:286:25)
      at Assertion.get (node_modules/chai/lib/chai/utils/overwriteProperty.js:50:37)
      at Object.callee$1$0$ (../../../test/unit/webdriveragent-specs.js:20:49)
      at tryCatch (node_modules/babel-runtime/regenerator/runtime.js:67:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (node_modules/babel-runtime/regenerator/runtime.js:315:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (node_modules/babel-runtime/regenerator/runtime.js:100:21)
      at GeneratorFunctionPrototype.invoke (node_modules/babel-runtime/regenerator/runtime.js:136:37)
```

## Code To Reproduce Issue [ Good To Have ]

```
git clone git@github.com:appium/appium-xcuitest-driver.git
cd appium-xcuitest-driver
npm install
gulp unit-test
```

**Comment by imurchie** [comment]
I'm not able to reproduce this. Can you rerun with logging on and see what the output is?

```
_FORCE_LOGS=1 gulp unit-test
```

or, to just run the one test,

```
mocha -R spec build/test/unit/webdriveragent-specs.js
```

**Comment by crummy** [comment]
Yes, here's my output: https://gist.github.com/crummy/ab179e7b3a2b708a77e025dc8e102190

**Comment by imurchie** [comment]
Weird, the output (https://gist.github.com/crummy/ab179e7b3a2b708a77e025dc8e102190#file-gistfile1-txt-L38-L39) is exactly as would be expected. 

Are you not installing the WDA in the normal place? I know you've been working on allowing an external WDA, etc.

These tests need a little revamping anyway. I will do that, to account for some capabilities.

**Comment by crummy** [comment]
😳 I forgot to `git submodule update` and was missing the WDA submodule. All tests pass now. Sorry to bother you!

**Comment by imurchie** [comment]
No problem! I'm glad it worked out!
