### ISSUE TITLE
how to to overcome this 

### ISSUE THREAD

**Issue by rkn411** [appium/appium#7485]
#debug] [iOS] IosDriver version: 1.13.0
[BaseDriver] Session created with session id: ec5bf5e3-9f9a-47cc-ae29-0f22ce5f3aa4
[debug] [iOS] Xcode version set to 8.1
[iOS] SessionNotCreatedError: A new session could not be created. Details: Appium's IosDriver does not support xcode version 8.1. Apple has deprecated UIAutomation. Use the "XCUITest" automationName capability instead.
    at IosDriver.createSession$ (../../lib/driver.js:130:28)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 { SessionNotCreatedError: A new session could not be created. Details: Appium's IosDriver does not support xcode version 8.1. Apple has deprecated UIAutomation. Use the "XCUITest" automationName capability instead.
    at IosDriver.createSession$ (../../lib/driver.js:130:28)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37) jsonwpCode: 33 }
[HTTP] <-- POST /wd/hub/session 500 366 ms - 243

**Comment by rkn411** [comment]
what i need to modify i was confused with latest versions updates help me to figure out why the exact issue was

**Comment by dilsreccse** [comment]
@rkn411 https://discuss.appium.io/t/appium-1-6-0-released/12661

**Comment by rkn411** [comment]
i m unable to c it in https://bitbucket.org/appium/appium.app/downloads/

**Comment by vikramvi** [comment]
@triager please close as this is not an issue but generic query which needs to be asked in discuss.appium.io

**Comment by jlipps** [comment]
@vikramvi thanks for wanting to help us triage! i've added you to the triagers list so your comments will now actually take effect :-)
