### ISSUE TITLE
can't run android test with real device in appium 1.6.2,success in 1.6.1

### ISSUE THREAD

**Issue by wenshi11019** [appium/appium#7506]
## The problem

run android test in appium, but start the server fail and throw a webdriverException. It seems that ‘tcp’ throw a error code.

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.2
* Last Appium version that did not exhibit the issue (if applicable):1.6.1
* Desktop OS/version used to run Appium:Mac os X 10.12.1
* Node.js version (unless using Appium.app|exe):4.7.0
* Mobile platform/version under test: Android 5.1.1
* Real device or emulator/simulator:real device
* Appium CLI or Appium.app|exe: cli

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Appium logs

https://gist.github.com/wenshi11019/104f836bbe662ac91d517d63578c770a

## Code To Reproduce Issue [ Good To Have ]
```
 org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/Users/gaojiewen/android-sdk/platform-tools/adb -P 5037 -s 69e2b803 forward --remove tcp\:8200' exited with code 1'; Stderr: 'error: listener 'tcp:8200' not found'; Code: '1' (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 12.77 seconds
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'MBP.local', ip: '192.168.88.10', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.1', java.version: '1.8.0_112'
Driver info: io.appium.java_client.android.AndroidDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_112]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_112]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_112]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_112]
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206) ~[selenium-remote-driver-2.53.1.jar:?]
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158) ~[selenium-remote-driver-2.53.1.jar:?]
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678) ~[selenium-remote-driver-2.53.1.jar:?]
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:40) ~[java-client-4.1.2.jar:?]
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1) ~[java-client-4.1.2.jar:?]
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1) ~[java-client-4.1.2.jar:?]
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:249) ~[selenium-remote-driver-2.53.1.jar:?]
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131) ~[selenium-remote-driver-2.53.1.jar:?]
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144) ~[selenium-remote-driver-2.53.1.jar:?]
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:36) ~[java-client-4.1.2.jar:?]
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:114) ~[java-client-4.1.2.jar:?]
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:132) ~[java-client-4.1.2.jar:?]
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:92) ~[java-client-4.1.2.jar:?]
	at com.framework.example.AndroidUiAutomatorviewer2Test.beforeClass(AndroidUiAutomatorviewer2Test.java:97) [test-classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144) [testng-6.10.jar:?]
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:169) [testng-6.10.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108) [testng-6.10.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:756) [testng-6.10.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:610) [testng-6.10.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387) [testng-6.10.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382) [testng-6.10.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340) [testng-6.10.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:289) [testng-6.10.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) [testng-6.10.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86) [testng-6.10.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293) [testng-6.10.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218) [testng-6.10.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:1133) [testng-6.10.jar:?]
	at org.testng.TestNG.run(TestNG.java:1104) [testng-6.10.jar:?]
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132) [testng-remote.jar:?]
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236) [testng-remote.jar:?]
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81) [testng-remote.jar:?]
```

**Comment by jlipps** [comment]
This should be fixed in 1.6.3.
