### ISSUE TITLE
babel transform error when trying to transpile appium

### ISSUE THREAD

**Issue by mollywhitnack** [appium/appium#7514]
## Failing to set up appium from source

Failing to set up appium from source, using steps:

```
git clone https://github.com/appium/appium.git
cd appium
npm install
gulp transpile # requires gulp, see below
npm install -g authorize-ios # for ios only
authorize-ios                # for ios only
node .
```

After npm install and gulp transpile appium is still missing many dependencies (appium-gulp-plugins,appium-ci, promisepipe, rimraf, pify,... etc)

I manually installed the dependencies and ran gulp transpile,

This is the error I got:

```
[12:21:16] Using gulpfile ~/oldappium/gulpfile.js
[12:21:16] Starting 'transpile'...

/Users//oldappium/node_modules/gulp-babel/node_modules/babel-core/lib/transformation/file/logger.js:41
    throw new Constructor(this._buildMessage(msg));
          ^
ReferenceError: [BABEL] /Users//oldappium/lib/appium.js: Using removed Babel 5 option: base.blacklist - Put the specific transforms you want in the `plugins` option
    at Logger.error (/Users//oldappium/node_modules/gulp-babel/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at OptionManager.mergeOptions (/Users//oldappium/node_modules/gulp-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:216:20)
    at OptionManager.init (/Users//oldappium/node_modules/gulp-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at File.initOptions (/Users//oldappium/node_modules/gulp-babel/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/Users//oldappium/node_modules/gulp-babel/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/Users//oldappium/node_modules/gulp-babel/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at DestroyableTransform._transform (/Users//oldappium/node_modules/gulp-babel/index.js:37:20)
    at DestroyableTransform.Transform._read (/Users//oldappium/node_modules/gulp-babel/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/Users//oldappium/node_modules/gulp-babel/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/Users//oldappium/node_modules/gulp-babel/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:347:64)
    at writeOrBuffer (/Users//oldappium/node_modules/gulp-babel/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:336:5)
    at DestroyableTransform.Writable.write (/Users//oldappium/node_modules/gulp-babel/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:274:11)
    at DestroyableTransform.ondata (/Users//oldappium/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:546:20)
    at emitOne (events.js:77:13)
    at DestroyableTransform.emit (events.js:169:7)
    at readableAddChunk (/Users//oldappium/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:217:18)
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.2
* Desktop OS/version used to run Appium: OSX 10.11.6
* Node.js version (unless using Appium.app|exe): v7.2.1
* Mobile platform/version under test: IOS 10.1.1

**Comment by jlipps** [comment]
@mollywhitnack what happens if you run `npm ls babel` in that appium directory?

**Comment by mollywhitnack** [comment]
Thank you! 

I did need to install babel but am now facing a different issue.
 
`gulp transpile ` completes but when I run `node . ` I get this error:

```
Error: Cannot find module '/Users/u522210/oldappium/node_modules/appium-xcuitest-driver/node_modules/appium-ios-simulator/node_modules/sqlite3/lib/binding/node-v51-darwin-x64/node_sqlite3.node'
```

I also got this error when trying to install appium through npm and run `appium`

When i navigate to the node-v51-darwin-x64 directory it is empty.

**Comment by jlipps** [comment]
I'm unable to repro this. I'm going to go out on a limb and say the cause was related perhaps to the other issue you were experiencing, which I believe may have been due to a corporate proxy messing with package installers. At least, we can't reproduce this on our side.
