### ISSUE TITLE
uiautomator2 - stopping and starting the script with out ending the session causes issue

### ISSUE THREAD

**Issue by srkannan** [appium/appium#7527]
## The problem

[MJSONWP] Encountered internal error running command:  {"jsonwp":{"status":13,"value":"java.lang.IllegalThreadStateException: Thread already started\n\tat java.lang.Thread.checkNotStarted(Thread.java:849)\n\tat java.lang.Thread.start(Thread.java:1059)\n\tat io.appium.uiautomator2.model.NotificationListener.start(NotificationListener.java:32)\n\tat io.appium.uiautomator2.model.Session.<init>(Session.java:23)\n\tat io.appium.uiautomator2.model.AppiumUiAutomatorDriver.initializeSession(AppiumUiAutomatorDriver.java:19)\n\tat io.appium.uiautomator2.handler.NewSession.safeHandle(NewSession.java:31)\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:54)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:201)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:192)\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:44)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\n\tat io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\n\tat io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)\n\tat io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)\n\tat io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)\n\tat io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\n\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)\n\tat io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:514)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:468)\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)\n\tat io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)\n\tat java.lang.Thread.run(Thread.java:818)\n"}} ProxyRequestError: Could not proxy command to remote server. Original error: 500 - {"status":13,"value":"java.lang.IllegalThreadStateException: Thread already started\n\tat java.lang.Thread.checkNotStarted(Thread.java:849)\n\tat java.lang.Thread.start(Thread.java:1059)\n\tat io.appium.uiautomator2.model.NotificationListener.start(NotificationListener.java:32)\n\tat io.appium.uiautomator2.model.Session.<init>(Session.java:23)\n\tat io.appium.uiautomator2.model.AppiumUiAutomatorDriver.initializeSession(AppiumUiAutomatorDriver.java:19)\n\tat io.appium.uiautomator2.handler.NewSession.safeHandle(NewSession.java:31)\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:54)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:201)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:192)\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:44)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\n\tat io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\n\tat io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)\n\tat io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)\n\tat io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)\n\tat io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\n\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)\n\tat io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:514)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:468)\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)\n\tat io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)\n\tat java.lang.Thread.run(Thread.java:818)\n"}
    at JWProxy.proxy$ (../../../lib/jsonwp-proxy/proxy.js:126:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.3
* Desktop OS/version used to run Appium:10.11.6
* Node.js version (unless using Appium.app|exe):v7.2.1
* Mobile platform/version under test:Android
* Real device or emulator/simulator:Real device

## Details

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: java.lang.IllegalThreadStateException: Thread already started
	at java.lang.Thread.checkNotStarted(Thread.java:849)
	at java.lang.Thread.start(Thread.java:1059)
	at io.appium.uiautomator2.model.NotificationListener.start(NotificationListener.java:32)
	at io.appium.uiautomator2.model.Session.<init>(Session.java:23)
	at io.appium.uiautomator2.model.AppiumUiAutomatorDriver.initializeSession(AppiumUiAutomatorDriver.java:19)
	at io.appium.uiautomator2.handler.NewSession.safeHandle(NewSession.java:31)
	at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:54)
	at io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:201)
	at io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:192)
	at io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:44)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:514)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:818)

**Comment by sravanmedarapu** [comment]
@srkannan Can you please share appium server logs in a separate [gist](https://gist.github.com/).

**Comment by sravanmedarapu** [comment]
Quick investigation:

Typically uiautomator2-driver tries to [`kill` ](https://github.com/appium/appium-uiautomator2-driver/blob/e2d6d7d9a923548136139574f1c89e3a55e80f7e/lib/uiautomator2.js#L167) the existing io.appium.uiautomator2.server process if any. 

`killProcessesByName` relaying on [PID](https://github.com/appium/appium-adb/blob/03ef3a12ee15bfa96d58bbbdd899c40efa2f56c7/lib/tools/adb-commands.js#L537) to kill based on PID(adb shell kill PID) is not reliable always. will return `/system/bin/sh: kill: 29333: Operation not permitted`.

As an alternative, should try to kill process with process name it self `adb shell am force-stop io.appium.uiautomator2.server`

**Comment by sravanmedarapu** [comment]
Should work with appium-uiautomator2-driver v0.2.6

**Comment by anandbagmar** [comment]
I am getting the same problem. I am on Appium 1.6.3 and have installed it using the command
```
npm install -g appium@1.6.3
```
As a result, I am using appium-uiautomator2-driver@0.2.3
```
$ npm -g list | grep uiautomator
│ │ │ ├─┬ appium-uiautomator@1.1.0
│ ├─┬ appium-uiautomator2-driver@0.2.3
│ │ ├── appium-uiautomator2-server@0.0.8

```

How can I upgrade the driver to the latest appium-uiautomator2-driver? Can you please help?

**Comment by priyankshah217** [comment]
@sravanmedarapu , this issue is still alive. We tried with appium-1.6.4 Beta.Below are appium dependencies which appium-1.6.4 is using in my device
npm list -g | grep appium
├─┬ appium@1.6.4-beta
│ ├─┬ appium-android-driver@1.11.3
│ │ ├─┬ appium-adb@2.11.1
│ │ ├─┬ appium-android-bootstrap@2.7.9
│ │ │ ├─┬ appium-uiautomator@1.1.0
│ │ ├── appium-android-ime@2.0.0
│ │ ├─┬ appium-chromedriver@2.10.0
│ │ ├── appium-unlock@0.1.1
│ │ ├── io.appium.settings@2.1.0
│ ├─┬ appium-base-driver@2.2.0
│ ├─┬ appium-fake-driver@0.1.10
│ ├─┬ appium-ios-driver@1.16.0
│ │ ├─┬ appium-instruments@3.9.1
│ │ ├─┬ appium-ios-simulator@1.17.1
│ │ ├─┬ appium-remote-debugger@3.2.3
│ │ ├─┬ appium-uiauto@2.3.3
│ │ ├─┬ appium-xcode@3.1.2
│ ├─┬ appium-logger@2.1.0
│ ├─┬ appium-selendroid-driver@1.5.1
│ ├─┬ appium-support@2.4.0
│ ├─┬ appium-uiautomator2-driver@0.2.9
│ │ ├── appium-uiautomator2-server@0.1.0
│ ├─┬ appium-windows-driver@0.4.0
│ ├─┬ appium-xcuitest-driver@2.8.0
│ ├─┬ appium-youiengine-driver@1.0.7
│ │ └─┬ appium-android-driver@1.10.31
├─┬ appium-doctor@1.4.1
│ ├─┬ appium-logger@2.1.0
│ ├─┬ appium-support@2.4.0
│ │ ├─┬ appium-xcode@3.1.2

Below is my appium log file.
https://gist.github.com/priyankshah217/598bd4fc0d6c61bc2122608cc54f24bf

The workaround which i was doing is uninstalling 
io.appium.uiautomator2.server, io.appium.uiautomator2.server.test before starting appium server.

**Comment by aaronmagi** [comment]
We are also seeing this on appium 1.6.5
