### ISSUE TITLE
Xcode version [object Object] is not yet supported

### ISSUE THREAD

**Issue by myth0506** [appium/appium#7565]
## The problem
appium inspector error log:
[MJSONWP] Encountered internal error running command: Error: Xcode version [object Object] is not yet supported
    at handleUnsupportedXcode (lib/simulator.js:15:11)
    at getDeviceString$ (lib/simulator.js:44:3)
    at tryCatch (/Applications/Appium-1.5.3.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium-1.5.3.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium-1.5.3.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium-1.5.3.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Applications/Appium-1.5.3.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /Applications/Appium-1.5.3.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/Applications/Appium-1.5.3.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

## Environment

* Appium version :1.5.3
* Xcode version:8.2
* emulator/simulator:iPhone 6 (iOS 9.3)

## Details

Describe in more detail the problem you have been experiencing, if necessary.
[appium.error.appiumconfig.zip](https://github.com/appium/appium/files/659302/appium.error.appiumconfig.zip)

[appium.error.appiumconfig.zip](https://github.com/appium/appium/files/659303/appium.error.appiumconfig.zip)

**Comment by mykola-mokhnach** [comment]
Xcode 8+ will never by supported by Appium 1.5. You must use 1.6+

**Comment by myth0506** [comment]
I could not find the version 1.6+;where can I find it?

**Comment by mykola-mokhnach** [comment]
Appium is available in npm repository. Read  https://github.com/appium/appium, Quick Start paragraph.
