### ISSUE TITLE
Session * was terminated due to BROWSER_TIMEOUT

### ISSUE THREAD

**Issue by vishwathma** [appium/appium#7567]
## The problem
Running test suite on various IPHONE simulators using Grid is throwing BROWSER_TIMEOUT error. We are seeing this issue from the last 3 or 4 weeks.

## Environment
* Appium version (or git revision) that exhibits the issue: 1.5.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: IOS
* Node.js version (unless using Appium.app|exe): v4.0.0
* Mobile platform/version under test:  os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_91'
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI

## Details
Running test suite on various IPHONE simulators using Grid is throwing BROWSER_TIMEOUT error. We are seeing this issue from the last 3 or 4 weeks.

## Link to Appium logs
I cannot access https://gist.github.com. So, I am pasting logs here itself.
```
org.openqa.selenium.WebDriverException: Session [3efc32dc-18ea-4c1e-a562-71c8023872de] was terminated due to BROWSER_TIMEOUT
Command duration or timeout: 31 milliseconds
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'macdb021227.fmr.com', ip: '10.33.59.243', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_91'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{app=../grid/app-bin/Debug-3.2-119.app.zip, networkConnectionEnabled=false, databaseEnabled=false, deviceName=iPhone 6s Plus, platform=MAC, desired={app=../grid/app-bin/Debug-3.2-119.app.zip, newCommandTimeout=360000, platformVersion=9.2, platformName=iOS, deviceName=iPhone 6s Plus, platform=MAC}, newCommandTimeout=360000, platformVersion=9.2, webStorageEnabled=false, locationContextEnabled=false, browserName=, takesScreenshot=true, javascriptEnabled=true, platformName=iOS}]
Session ID: 3efc32dc-18ea-4c1e-a562-71c8023872de
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:40)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:235)
	at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:526)
	at com.fmr.pimobile.automation.driver.appium.AppiumBaseDriver.quitDriver(AppiumBaseDriver.java:81)
	at com.fmr.pimobile.automation.test.feature.AppHooks.tearDown(AppHooks.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cucumber.runtime.Utils$1.call(Utils.java:37)
	at cucumber.runtime.Timeout.timeout(Timeout.java:13)
	at cucumber.runtime.Utils.invoke(Utils.java:31)
	at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)
	at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:223)
	at cucumber.runtime.Runtime.runHooks(Runtime.java:211)
	at cucumber.runtime.Runtime.runAfterHooks(Runtime.java:205)
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:46)
	at cucumber.runtime.junit.ExecutionUnitRunner.run(ExecutionUnitRunner.java:91)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:63)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:18)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:70)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:93)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:37)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at cucumber.api.junit.Cucumber.run(Cucumber.java:98)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:117)
	at org.junit.runner.JUnitCore.runMain(JUnitCore.java:96)
	at org.junit.runner.JUnitCore.runMainAndExit(JUnitCore.java:47)
	at org.junit.runner.JUnitCore.main(JUnitCore.java:40)
Caused by: org.openqa.selenium.WebDriverException: Session [3efc32dc-18ea-4c1e-a562-71c8023872de] was terminated due to BROWSER_TIMEOUT
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'macdb021227.fmr.com', ip: '10.33.59.243', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_91'
Driver info: driver.version: unknown
	at org.openqa.grid.internal.ActiveTestSessions.getExistingSession(ActiveTestSessions.java:105)
	at org.openqa.grid.internal.Registry.getExistingSession(Registry.java:425)
	at org.openqa.grid.web.servlet.handler.RequestHandler.getSession(RequestHandler.java:240)
	at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:120)
	at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:83)
	at org.openqa.grid.web.servlet.DriverServlet.doDelete(DriverServlet.java:73)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:713)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.seleniumhq.jetty9.server.Server.handle(Server.java:499)
	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:310)
	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.seleniumhq.jetty9.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jlipps** [comment]
These are your client logs. We need the appium server logs.

**Comment by vishwathma** [comment]
[Server Logs.zip](https://github.com/appium/appium/files/667988/Server.Logs.zip)

**Comment by vishwathma** [comment]
Server logs attached. Thanks!

**Comment by jawlitkp** [comment]
same issue using Android devices running parallel on Grid. seem look like Grid displays node is ready for next testcase and receives request to create new driver but on Appium server side still old session is not cleared

**Comment by vishwathma** [comment]
Can someone help me on this?

**Comment by vishwathma** [comment]
Is this issue been looked into?

**Comment by vishwathma** [comment]
Is this issue been looked into?

**Comment by jlipps** [comment]
That log is not from the latest version of Appium. Please try with Appium 1.6.3 instead.

**Comment by vishwathma** [comment]
@jlipps , yes, we are in the process of upgrading to the new appium version. But is there a solution for the older version(v1.5.3)?

**Comment by MEZISH** [comment]
Just to add -  upgrading to v1.6.3. is not a solution because that version is not working with real iOS devices. Unable to codesign the IntegrationApp.

**Comment by jlipps** [comment]
@MEZISH if you're having problems with real devices, upgrade to 1.6.4 and file your own issue if you're noticing a problem. Closing this for now.
