### ISSUE TITLE
Unable to start WebDriverAgent session: An unknown server-side error occurred while processing the command. Original error: Failed to launch com.apple.mobilesafari application - Appium1.6.3 -iOS 10.1

### ISSUE THREAD

**Issue by mollywhitnack** [appium/appium#7574]
## The problem

I am trying to run a simple test using mobile safari and an ios device. 

This is the test I run (in java):
```
	
        DesiredCapabilities capabilities = new DesiredCapabilities();
	capabilities.setCapability("automationName", "XCUITest");
	capabilities.setCapability("deviceName", "iPhone 7");
	capabilities.setCapability("platformName", "iOS");
	capabilities.setCapability("platformVersion", "10.1");
	capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "Safari");
		
	IOSDriver driver = new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);	
	driver.get("http://www.google.com");

``` 

I have IOS-WEBKIT-DEBUG-PROXY running and my command to run appium is:
```
appium -a 127.0.01 --safari --webkit-debug-proxy-port 27753 --default-capabilities
'{"platformName":"ios", "platformVersion":"10.1.1",
"udid":"f654d84df7011a1897829a2c65c457f7b11413ca"}'
```

Safari Launcher and WebDriver are successfully installed on the phone but it seems to get stuck launching the webdriver agent on the real device.  

Appium logs show it getting stuck here: 
```

[XCUITest] Setting up real device
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Using real device logger 'idevicesyslog'
[debug] [XCUITest] Beginning test with command 'xcodebuild build test -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=f654d84df7011a1897829a2c65c457f7b11413ca -configuration Debug' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Waiting for WebDriverAgent to start on device
[debug] [XCUITest] Log file for xcodebuild test: /Users//Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/8D6E3694-BE45-4159-B9A9-855DABA3CEDC/Session-WebDriverAgentRunner-2016-12-20_101414-1hzSWC.log
[debug] [WebDriverAgent] Device: Dec 20 10:14:16 Barros-Justin-irvins-iPhone XCTRunner[641] <Notice>: Running tests...
[debug] [WebDriverAgent] Device: Dec 20 10:14:17 Barros-Justin-irvins-iPhone XCTRunner[641] <Notice>: Continuing to run tests in the background with task ID 1
[XCUITest] Detected that WebDriverAgent is running at url 'http://11.255.187.116:8100'
[XCUITest] WebDriverAgent started at url 'http://11.255.187.116:8100'
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.apple.mobilesafari","arguments":["-u","http://appium.io"],"shouldWaitForQuiescence":true}}

```
Then Appium gets the "Failed to launch com.apple.mobilesafari " error:
```

[debug] [JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.apple.mobilesafari application","sessionId":"4DDD110F-32EC-43CD-8EF8-0EFDAA990397","status":13}
[debug] [XCUITest] Unable to start WebDriverAgent session: An unknown server-side error occurred while processing the command. Original error: Failed to launch com.apple.mobilesafari application
[debug] [XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down xcodebuild process (pid 61563)
[XCUITest] xcodebuild exited with code 'null' and signal 'SIGTERM'
[XCUITest] Shutting down Logger process (pid 61568)
[XCUITest] System log exited with code '0'
[XCUITest] Shutting down iproxy process (pid 61594)
[XCUITest] iproxy exited with code 'null'
[debug] [XCUITest] Removing WDA application from device

```
Appium cycles through attempting to launch webdriver on the device and getting this error.

Then it finally times out and gives this error in appium Logs:
```

[XCUITest] UnknownError: An unknown server-side error occurred while processing the command. Original error: Failed to launch com.apple.mobilesafari application
    at errorFromCode (../../../lib/mjsonwp/errors.js:398:10)
    at XCUITestDriver.callee$0$0$ (../../../lib/commands/proxy-helper.js:22:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:108:47)
    at /usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:119:28
    at flush (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at nextTickCallbackWith0Args (node.js:436:9)
    at process._tickCallback (node.js:365:13)
 { [UnknownError: An unknown server-side error occurred while processing the command. Original error: Failed to launch com.apple.mobilesafari application] jsonwpCode: 13 }
[debug] [JSONWP Proxy] Proxying [DELETE /session/2c2a3979-8ae5-4588-9e60-00aa0d0a9513] to [DELETE http://localhost:8100/session/E8040613-93AC-49DD-ABA2-F1103796A83A] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n\n  },\n  \"sessionId\" : \"EC3C8FAE-6139-46F4-8085-A6F8776D4758\",\n  \"status\" : 0\n}"
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down xcodebuild process (pid 62918)
[XCUITest] xcodebuild exited with code 'null' and signal 'SIGTERM'
[XCUITest] Shutting down Logger process (pid 62923)
[XCUITest] System log exited with code '0'
[XCUITest] Shutting down iproxy process (pid 62938)
[XCUITest] iproxy exited with code 'null'
[debug] [XCUITest] Running ios real device reset flow
[debug] [XCUITest] Resetting simulator
[debug] [iOSLog] Stopping iOS log capture
[HTTP] <-- POST /wd/hub/session 500 405712 ms - 188
[HTTP] --> POST /wd/hub/session {"capabilities":{"desiredCapabilities":{"automationName":"XCUITest","browserName":"Safari","platformName":"iOS","deviceName":"iPhone 7","platformVersion":"10.1"},"requiredCapabilities":{}}}
[debug] [MJSONWP] Bad parameters: BadParametersError: Parameters were incorrect. We wanted {"required":["desiredCapabilities"],"optional":["requiredCapabilities","capabilities","sessionId","id","sessionId","id","sessionId","id"]} and you sent ["capabilities"]
[HTTP] <-- POST /wd/hub/session 400 3 ms - 205

```

And I get this error from eclipse 
```

FAILED: startBrowser
org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{platformVersion=10.1, automationName=XCUITest, browserName=Safari, platformName=iOS, deviceName=iPhone 7}], required capabilities = Capabilities [{}]
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'DTCAC87A3214356', ip: '10.46.82.233', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_101'
Driver info: driver.version: IOSDriver

```

## Environment

* Appium version: 1.6.3
* Desktop OS/version used to run Appium: OSX 10.11.6
* Node.js version (unless using Appium.app|exe): 4.7.0
* Mobile platform/version under test: ios 10.1, iphone 7

## Link to Appium logs
[Appium Logs](https://gist.github.com/mollywhitnack/f04c5c237808312ac94f8954e9b87095)

**Comment by mollywhitnack** [comment]
I restarted the phone and seems to have fixed the issue

**Comment by jlipps** [comment]
Thanks. Yes I just ran a mobile safari test successfully on my phone so nothing too major is broken.
