### ISSUE TITLE
Error: Command 'idevice_id -l' errored out: Error: spawn idevice_id ENOENT

### ISSUE THREAD

**Issue by Rdexmah** [appium/appium#7576]
I am not able to run mu appium scripts on my IOS device. It gives me below error:

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6 .0 beta2
* Last Appium version that did not exhibit the issue (if applicable):nonw
* Desktop OS/version used to run Appium: Mac OS 10.11.6
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: IOS 
* Real device or emulator/simulator: Ipod Touch
* Appium CLI or Appium.app|exe:

## Details

I am constantly facing this issue ,getting below error.
I have done all troubleshots updating lib mibile libs etc etc...... Dont know how it will resolve
## Link to Appium logs

[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   app: '/Repos/iOS Build for Appium/XXXX.app'
[Appium]   showIOSLog: false
[Appium]   noReset: true
[Appium]   showXcodeLog: false
[Appium]   newCommandTimeout: 1800
[Appium]   realDeviceLogger: '/usr/local/lib/node_modules/deviceconsole/deviceconsole/'
[Appium]   platformVersion: '10.0.1'
[Appium]   automationName: 'XCUITest'
[Appium]   udid: 'baa51e99d3665xxxxxxxxxxxxxx3e95d651960d371d6b'
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'ipod6'
[Appium]   fullReset: false
[debug] [XCUITest] XCUITestDriver version: 2.4.3
[BaseDriver] Session created with session id: caf402b5-b7a8-4197-b5f8-6d85b3ce5217
[debug] [XCUITest] Xcode version set to '8.1'
[debug] [XCUITest] iOS SDK Version set to '10.1'
[XCUITest] Error: Command 'idevice_id -l' errored out: Error: spawn idevice_id ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at ChildProcess.<anonymous> (../../lib/teen_process.js:32:14)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
 Error: Command 'idevice_id -l' errored out: Error: spawn idevice_id ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at ChildProcess.<anonymous> (../../lib/teen_process.js:32:14)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[debug] [XCUITest] Reset not set, not ending sim
[MJSONWP] Encountered internal error running command: Error: Command 'idevice_id -l' errored out: Error: spawn idevice_id ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at ChildProcess.<anonymous> (../../lib/teen_process.js:32:14)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[HTTP] <-- POST /wd/hub/session 500 535 ms - 521

**Comment by jlipps** [comment]
You're missing the `idevice_id` binary, which is part of libimobiledevice. So that is not installed correctly on your system. Please reference the [XCUITest README](https://github.com/appium/appium-xcuitest-driver/blob/master/README.md) for more information.
