### ISSUE TITLE
[XCUITest]Appium 1.6.3  How to unlock app by gesture

### ISSUE THREAD

**Issue by IceEnd** [appium/appium#7589]
## The problem
I have some questions about how to unlock app by gesture, for example：<br/>
```press-wait-moveTo-wait-moveTo-release```<br/>
![ gestures to unlock](https://testerhome.com/photo/2016/9fa6ecf574e4e34294c9e545ade3c13b.png)
 But Appium only supports several simple gestures:```press-wait-moveTo-release```<br/>
https://github.com/appium/appium-xcuitest-driver/blob/master/lib/commands/gesture.js#L26
## Environment
* Appium version : 1.6.3
* Node.js version : 6.9.1
* macOS Sierra: 10.12.2
* iOS simulator: 9.3

## Appium logs

```
[HTTP] <-- POST /wd/hub/session/aea29ecd-1895-4f25-8b50-a8bb5c40b8a8/context 200 4 ms - 76 
[HTTP] --> POST /wd/hub/session/aea29ecd-1895-4f25-8b50-a8bb5c40b8a8/touch/perform [{"action":"press","options":{"x":100,"y":400}},{"action":"wait","options":{"ms":500}},{"action":"moveTo","options":{"x":0,"y":-100}},{"action":"wait","options":{"ms":500}},{"action":"moveTo","options":{"x":100,"y":200}},{"action":"release","options":{}}]
[debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":100,"y":400}},{"action":"wait","options":{"ms":500}},{"action":"moveTo","options":{"x":0,"y":-100}},{"action":"wait","options":{"ms":500}},{"action":"moveTo","options":{"x":100,"y":200}},{"action":"release","options":{}}],"aea29ecd-1895-4f25-8b50-a8bb5c40b8a8"]
[debug] [XCUITest] Executing command 'performTouch'
[debug] [XCUITest] Received the following touch action: press-wait-moveTo-wait-moveTo-release
[HTTP] <-- POST /wd/hub/session/aea29ecd-1895-4f25-8b50-a8bb5c40b8a8/touch/perform 501 2 ms - 164 
[HTTP] --> DELETE /wd/hub/session/aea29ecd-1895-4f25-8b50-a8bb5c40b8a8 {}
[debug] [MJSONWP] Calling AppiumDriver.deleteSession() with args: ["aea29ecd-1895-4f25-8b50-a8bb5c40b8a8"]
[debug] [JSONWP Proxy] Proxying [DELETE /session/aea29ecd-1895-4f25-8b50-a8bb5c40b8a8] to [DELETE http://localhost:8100/session/E1E67E8E-A05D-4F86-90AC-64634EE012EB] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n\n  },\n  \"sessionId\" : \"19BBF743-C705-426F-AF9F-1978DC6D01B5\",\n  \"status\" : 0\n}"
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down xcodebuild process (pid 33974)
[XCUITest] xcodebuild exited with code 'null' and signal 'SIGTERM'
[XCUITest] Shutting down Logger process (pid 33979)
[XCUITest] Simulator log exited with code 'null'
[debug] [XCUITest] Reset not set, not ending sim
[debug] [iOSLog] Stopping iOS log capture
[Appium] Removing session aea29ecd-1895-4f25-8b50-a8bb5c40b8a8 from our master session list
[debug] [MJSONWP] Received response: null
[debug] [MJSONWP] But deleting session, so not returning
[debug] [MJSONWP] Responding to client with driver.deleteSession() result: null
[HTTP] <-- DELETE /wd/hub/session/aea29ecd-1895-4f25-8b50-a8bb5c40b8a8 200 253 ms - 76 
```

## Code
```javascript
var action = new wd.TouchAction(driver);
return action
    .press({x:100,y:400})
    .wait(500)
    .moveTo({x:0,y:-100})
    .wait(500)
    .moveTo({x:100,y:0})
    .release()
    .perform();
```

**Comment by dpgraham** [comment]
Is the code you're running not working correctly?

**Comment by IceEnd** [comment]
Use XCUITest,on iOS 9.3.Throws an exception：
```
1) ios simple #1 :
     Error: [performTouchAction([{"action":"press","options":{"x":100,"y":400}},{"action":"wait","options":{"ms":500}},{"action":"moveTo","options":{"x":0,"y":-100}},{"action":"wait","options":{"ms":500}},{"action":"moveTo","options":{"x":100,"y":200}},{"action":"release","options":{}}])] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: Support for this gesture is not yet implemented. Please contact an Appium dev
      at exports.newError (node_modules/wd/lib/utils.js:145:13)
      at node_modules/wd/lib/callbacks.js:75:19
      at node_modules/wd/lib/webdriver.js:179:5
      at Request._callback (node_modules/wd/lib/http-utils.js:88:7)
      at Request.self.callback (node_modules/request/request.js:187:22)
      at Request.<anonymous> (node_modules/request/request.js:1048:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:969:12)
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)
```

Appium logs:
```
[debug] [MJSONWP] Calling AppiumDriver.getCurrentContext() with args: ["4853e347-47a4-4feb-a8e9-32a8142fd482"]
[debug] [XCUITest] Executing command 'getCurrentContext'
[debug] [MJSONWP] Responding to client with driver.getCurrentContext() result: "NATIVE_APP"
[HTTP] <-- GET /wd/hub/session/4853e347-47a4-4feb-a8e9-32a8142fd482/context 200 2 ms - 84 
[HTTP] --> POST /wd/hub/session/4853e347-47a4-4feb-a8e9-32a8142fd482/touch/perform {"actions":[{"action":"press","options":{"x":100,"y":400}},{"action":"wait","options":{"ms":500}},{"action":"moveTo","options":{"x":0,"y":-100}},{"action":"wait","options":{"ms":500}},{"action":"moveTo","options":{"x":100,"y":200}},{"action":"release","options":{}}]}
[debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":100,"y":400}},{"action":"wait","options":{"ms":500}},{"action":"moveTo","options":{"x":0,"y":-100}},{"action":"wait","options":{"ms":500}},{"action":"moveTo","options":{"x":100,"y":200}},{"action":"release","options":{}}],"4853e347-47a4-4feb-a8e9-32a8142fd482"]
[debug] [XCUITest] Executing command 'performTouch'
[debug] [XCUITest] Received the following touch action: press-wait-moveTo-wait-moveTo-release
[HTTP] <-- POST /wd/hub/session/4853e347-47a4-4feb-a8e9-32a8142fd482/touch/perform 501 11 ms - 164 
[HTTP] --> DELETE /wd/hub/session/4853e347-47a4-4feb-a8e9-32a8142fd482 {}
[debug] [MJSONWP] Calling AppiumDriver.deleteSession() with args: ["4853e347-47a4-4feb-a8e9-32a8142fd482"]
[debug] [JSONWP Proxy] Proxying [DELETE /session/4853e347-47a4-4feb-a8e9-32a8142fd482] to [DELETE http://localhost:8100/session/F45E4F94-2007-41A0-8E42-DBE45D5432C5] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n\n  },\n  \"sessionId\" : \"1322E9D3-9A97-4942-AB9E-C05F982C304E\",\n  \"status\" : 0\n}"
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down xcodebuild process (pid 59176)
[XCUITest] xcodebuild exited with code 'null' and signal 'SIGTERM'
[XCUITest] Shutting down Logger process (pid 59181)
[XCUITest] Simulator log exited with code 'null'
```

**Comment by jlipps** [comment]
There is now a whole set of unlocking features in Appium! https://github.com/appium/appium-android-driver/blob/master/docs/UNLOCK.md
