### ISSUE TITLE
WDA  ./Scripts/bootstrap.sh error happened

### ISSUE THREAD

**Issue by huanglik** [appium/appium#7608]
**when my  pwd is**
/Users/likunhuang/Downloads/appium-1.6.3/node_modules/appium-xcuitest-driver/WebDriverAgent/

**and run  with     ./Scripts/bootstrap.sh   it happens error belows:**

> web-driver-inspector@1.0.0 build /Users/likunhuang/Downloads/appium-1.6.3/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector
> webpack --progress --colors

Hash: 9ed7d0b85cc08341fd0f  
Version: webpack 1.14.0
Time: 48ms
   [0] multi main 28 bytes {0} [built] [1 error]
    + 1 hidden modules

ERROR in ./js/app.js
Module parse failed: /Users/likunhuang/Downloads/appium-1.6.3/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/js/app.js Unexpected token (59:4)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (59:4)
    at Parser.pp$4.raise (/Users/likunhuang/Downloads/appium-1.6.3/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/likunhuang/Downloads/appium-1.6.3/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (/Users/likunhuang/Downloads/appium-1.6.3/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/node........

**but when I checkout WDA separately from github without appium  and check it is okay**

$ ./Scripts/bootstrap.sh

> web-driver-inspector@1.0.0 build /Users/likunhuang/Desktop/Inspector
> webpack --progress --colors

Hash: 464241247f16d853b410  
Version: webpack 1.14.0
Time: 1261ms
       Asset    Size  Chunks             Chunk Names
inspector.js  712 kB       0  [emitted]  main
   [0] multi main 28 bytes {0} [built]
    + 182 hidden modules

i think this is issue of appium ... please help me......

**Comment by imurchie** [comment]
There is no reason to run the webpack initialization code for Appium, and we make no guarantees about its working. If you really really want to run the bootstrap script manually, use the `-d` flag.

```
./Scripts/bootstrap.sh -d
```
