### ISSUE TITLE
python ios_simple.py failed

### ISSUE THREAD

**Issue by erduoniba** [appium/appium#7618]
## The problem

Appium server and clinet is Ok now. when i execute 
`python ios_simple.py` 
always failed

## Environment

* Appium version is 1.7.3
* Node.js version is 3.10.9
* Xcode version is 8.1, iPhone iphonesimulator version is 10.1

## Link to Appium logs

======================================================================
ERROR: test_scroll (__main__.SimpleIOSTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "ios_simple.py", line 21, in setUp
    'deviceName': 'iPhone 7'
  File "build/bdist.macosx-10.12-intel/egg/appium/webdriver/webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "/Library/Python/2.7/site-packages/selenium-3.0.2-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 92, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/Library/Python/2.7/site-packages/selenium-3.0.2-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 179, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/Library/Python/2.7/site-packages/selenium-3.0.2-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/selenium-3.0.2-py2.7.egg/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1

======================================================================
ERROR: test_ui_computation (__main__.SimpleIOSTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "ios_simple.py", line 21, in setUp
    'deviceName': 'iPhone 7'
  File "build/bdist.macosx-10.12-intel/egg/appium/webdriver/webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "/Library/Python/2.7/site-packages/selenium-3.0.2-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 92, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/Library/Python/2.7/site-packages/selenium-3.0.2-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 179, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/Library/Python/2.7/site-packages/selenium-3.0.2-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/selenium-3.0.2-py2.7.egg/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1

----------------------------------------------------------------------
Ran 2 tests in 377.600s

FAILED (errors=2)

**Comment by mykola-mokhnach** [comment]
>  Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1

Make sure you have Carthage installed and working

**Comment by erduoniba** [comment]
@mykola-mokhnach thanks, i installed carthage fix 
` Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1`

But I‘m sorry have another question:


➜  python python ios_simple.py
test_scroll (__main__.SimpleIOSTests) ... ok
test_ui_computation (__main__.SimpleIOSTests) ... ERROR

======================================================================
ERROR: test_ui_computation (__main__.SimpleIOSTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "ios_simple.py", line 41, in test_ui_computation
    self._populate()
  File "ios_simple.py", line 30, in _populate
    els = [self.driver.find_element_by_accessibility_id('TextField1'),
  File "build/bdist.macosx-10.12-intel/egg/appium/webdriver/webdriver.py", line 156, in find_element_by_accessibility_id
    return self.find_element(by=By.ACCESSIBILITY_ID, value=id)
  File "/Library/Python/2.7/site-packages/selenium-3.0.2-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 752, in find_element
    'value': value})['value']
  File "/Library/Python/2.7/site-packages/selenium-3.0.2-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "build/bdist.macosx-10.12-intel/egg/appium/webdriver/errorhandler.py", line 29, in check_response
    raise wde
NoSuchElementException: Message: An element could not be located on the page using the given search parameters.


----------------------------------------------------------------------
Ran 2 tests in 444.044s

FAILED (errors=1)

**Comment by erduoniba** [comment]
@mykola-mokhnach thanks!
