### ISSUE TITLE
Unable to run Appium 1.6.3 on Sierra MACOS

### ISSUE THREAD

**Issue by tzedar** [appium/appium#7624]
## The problem

I upgraded my MAC OS to Sierra and then upgraded Appium from 1.6.0 to 1.6.3. I now get an errro with SQLite3. It is looking for version47 but it is installing version 48.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): 1.6.0
* Desktop OS/version used to run Appium: Sierra

## Code To Reproduce Issue [ Good To Have ]

/Applications/Appium.app/Contents/Resources/node/bin/node /usr/local/bin/appium --address 127.0.0.1 --port 4723 --log /tmp/ios_appium.log --log-timestamp --local-timezone --webkit-debug-proxy-port 27754 -dc '{"showIOSLog": true, "nativeInstrumentsLib": true}'

**Comment by dpgraham** [comment]
-Have you tried doing a full uninstall?

```
npm uninstall -g appium
npm install -g appium
```

-Is the terminal logging anything when you try running the above command?

**Comment by tzedar** [comment]
The installation process works just fine. There error comes when I am running the script.

Error: Cannot find module '/usr/local/lib/node_modules/appium/node_modules/sqlite3/lib/binding/node-v47-darwin-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/appium/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (../../lib/certificate.js:5:32)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (../../lib/utils.js:7:36)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (../../lib/simulator-xcode-6.js:7:23)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/appium/node_modules/appium-ios-simulator/build/lib/simulator.js:11:24)
    at Module._compile (module.js:413:34)
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...6 completed.

[Process completed]

The error references V47 and on my machine I have V48. I cannot figure out how to get V47 of SQLite3 on my machine.

**Comment by imurchie** [comment]
Have you changed Node versions at all? I have seen this happen when I install with one version and switch to another.

**Comment by tzedar** [comment]
The only thing I upgraded was XCode and MAC OS and then I upgraded Appium from 1.6.0 to 1.6.3 and tried to run the script and ran into the above error.

**Comment by imurchie** [comment]
And it continues even after, as @dpgraham suggested, you uninstall and re-install?

**Comment by tzedar** [comment]
Yep. I did that previously on my own also and then once he suggested it I did it again. I have tried:

npm uninstall -g appium
npm install -g appium

and

npm uninstall appium
npm install appium

I moved the location in my script to follow the new path with each installation and both installations give me the same error.

**Comment by imurchie** [comment]
Strange. I get version 47 if I install with Node 5.8. And 48 with Node 6. I'm not sure what to make of all that.

**Comment by tzedar** [comment]
I just checked my node version and it came back with 5.10.1

**Comment by dpgraham** [comment]
By coincidence I just got the exact same error. I'm going to work through this right now and keep you all posted on my status.

**Comment by imurchie** [comment]
One way to "fix" it is to wrap the `require` statement in a `try`/`catch`

```js
let sqlite3;
let openssl;
try {
  sqlite3 = B.promisifyAll(require('sqlite3'));
  openssl = B.promisify(require('openssl-wrapper').exec);
} catch (err) {
  // log some stuff
}
```

And then check if `sqlite3` is undefined before using it, and log appropriately.

That way it only affects the people who actually want to use the feature, not everyone who tries to start Appium.

**Comment by dpgraham** [comment]
I just had this same problem but with electron and not appium (https://discuss.atom.io/t/sqlite3-cannot-find-node-sqlite3-node-question/16530/6) so it is a somewhat common issue.

I think we need to:
* [ ] Find a workaround for this that fixes the problem
* [ ] Implement the fix @imurchie suggested above
* [ ] Document this issue

**Comment by imurchie** [comment]
Does manually installing `sqlite3` fix the problem? Like, going into your Appium installation and running `npm install sqlite3`?

**Comment by tzedar** [comment]
I tried this and still had the same problem. I thought I would try to install an older version of sqlite3 and did not have much luck with this.

**Comment by dpgraham** [comment]
@tzedar When you navigate to /usr/local/lib/node_modules/appium/node_modules/sqlite3/lib/binding/ what do you see?

**Comment by mykola-mokhnach** [comment]
How about this?
http://stackoverflow.com/questions/20221825/node-js-says-it-cant-load-sqlite3-module-but-does-anyway

**Comment by tzedar** [comment]
node-v48-darwin-x64

The script is looking for a folder node-v47-darwin-x64. I thought I would be slick and change the folder name to v47 but then my script said it was looking for V47 and got V48.

**Comment by dpgraham** [comment]
Can you try going into your Appium installation directory and running npm install sqlite3 --build-from-source

**Comment by dpgraham** [comment]
I've done more research on this,

I was able to fix my problem using a component called ```electron-rebuild``` which rebuilds native node modules to match the version of Node that electron is using instead of the system version of Node.

This obviously doesn't help @tzedar but I think it's a related type of problem (incompatible native SQLite3 node module).

We need to figure out how to resolve this problem and then document how users can resolve this problem if they run into it but we also need to do what @imurchie suggested and not make unavailable node_sqlite3 module break the whole driver.

**Comment by imurchie** [comment]
@tzedar Can you try re-installing the latest? I have implemented something that ought to fix this issue.

```
npm uninstall -g appium
npm install -g appium --no-shrinkwrap
```

**Comment by tzedar** [comment]
I have installed with your instructions and my script did load successfully. I have not really run any tests yet but they should be fine since my startup script runs.

**Comment by imurchie** [comment]
Excellent! Glad to hear it.

**Comment by sjenasears** [comment]
Any solution for this. I am facing the same issue.

**Comment by imurchie** [comment]
The latest Appium does not use SQLite3 at all. Try `npm uninstall -g appium && npm install -g appium@beta`.

**Comment by sjenasears** [comment]
i did as u told. Still that issue persists.

**Comment by mykola-mokhnach** [comment]
@sjenasears you are executing wrong Appium executable. npm creates appium alias in _/usr/local/bin/appium_ by default in case of global setup.

**Comment by sjenasears** [comment]
i i am trying to launch through Appium UI

**Comment by mykola-mokhnach** [comment]
That's not gonna happen. The old Appium desktop client is not supported anymore.

Although you can try the [new beta](https://github.com/appium/appium-desktop/releases) if you still need it.

**Comment by sjenasears** [comment]
Thanks.
I have downloaded new beta ui. 
but server is not getting started. Getting following error.
Error starting Appium server: listen EADDRINUSE 0.0.0.0:4723

**Comment by mykola-mokhnach** [comment]
@sjenasears Please use Appium forum for howto questions

**Comment by xiaoyanhln** [comment]
Any solution on this, encounter same problem.

**Comment by imurchie** [comment]
You need to figure out what else is running on port 4723, or start Appium with a different port (using the `--port` server flag).

**Comment by xiaoyanhln** [comment]
Thank you, @imurchie

**Comment by shabana-parveen** [comment]
@imurchie , I am getting below error. 

TypeError: _lodash2.default.toPairs is not a function
at Object. (../../lib/adb.js:74:28)
at Module._compile (module.js:624:30)
at Object.Module._extensions..js (module.js:635:10)
at Module.load (module.js:545:32)
at tryModuleLoad (module.js:508:12)
at Function.Module._load (module.js:500:3)
at Module.require (module.js:568:17)
at require (internal/module.js:11:18)
at Object. (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-adb/build/index.js:11:15)
at Module._compile (module.js:624:30)
at Object.Module._extensions..js (module.js:635:10)
at Module.load (module.js:545:32)
at tryModuleLoad (module.js:508:12)
at Function.Module._load (module.js:500:3)
at Module.require (module.js:568:17)
at require (internal/module.js:11:18)
at Object. (../../lib/android-helpers.js:10:49)
at Module._compile (module.js:624:30)
at Object.Module._extensions..js (module.js:635:10)
at Module.load (module.js:545:32)
at tryModuleLoad (module.js:508:12)
at Function.Module._load (module.js:500:3)
at Module.require (module.js:568:17)
at require (internal/module.js:11:18)
at Object. (../../../lib/commands/general.js:1:23)
at Module._compile (module.js:624:30)
at Object.Module._extensions..js (module.js:635:10)
at Module.load (module.js:545:32)
at tryModuleLoad (module.js:508:12)
at Function.Module._load (module.js:500:3)
at Module.require (module.js:568:17)
at require (internal/module.js:11:18)
at Object. (../../../lib/commands/index.js:1:30)
at Module._compile (module.js:624:30)
at Object.Module._extensions..js (module.js:635:10)
at Module.load (module.js:545:32)
at tryModuleLoad (module.js:508:12)
at Function.Module._load (module.js:500:3)
at Module.require (module.js:568:17)
at require (internal/module.js:11:18)

PS: I was updating appium version with 1.7.0, this version having few issues then I try to install its beta version of 1.7.0. again its showing me few errors. then I downgrade my appium version with 1.6.5. but getting above error

npm version : 5.3.0
node version : v8.6.0

From last 2 days, I was stuck with this issue. I tried all npm uninstallation/ updation, appium downgrade/ update. Please check and provide me a solution.

I tried all solutions listed https://github.com/appium/appium/issues/9072#issuecomment-333161068

**Comment by imurchie** [comment]
This is the wrong version of lodash being loaded. Can you run `npm ls lodash` and post the result?

**Comment by shabana-parveen** [comment]
Its Shabana:~ f2849$ npm ls lodash
bin@1.0.0 /Users/f2849
└── lodash@4.17.4

**Comment by shabana-parveen** [comment]
@imurchie , I can successfully run appium desktop app with 1.7.0 beta version but through command line still facing same issue.

Please help me for same.

**Comment by imurchie** [comment]
Something is wrong with the install, perhaps with things left over in your install directory. I would look to see what sorts of things are in the place where appium is installed.

**Comment by shabana-parveen** [comment]
@imurchie , Please check below appium paths, Also, please guide me how can I help you more to resolve my issue., also when I run **appium-doctor --android** then getting same above error.

Shabana:~ f2849$ which appium
/usr/local/bin/appium

Shabana:~ f2849$ ls -l /usr/local/bin/appium
lrwxr-xr-x  1 f2849  admin  44 Apr 15  2016 /usr/local/bin/appium -> ../lib/node_modules/appium/build/lib/main.js
