### ISSUE TITLE
See whether Appium can set itself as the mock location app automatically

### ISSUE THREAD

**Issue by luisromanwp** [appium/appium#7647]
Hi all!
The Appium settings is crashing every time I use a script that use the setLocation to set the GPS Position when I use a Android 7 N Device or Emulator.

Environment
* Appium 1.5.3 GUI with Appium 1.6.3
* MacOS Sierra
* Node.js v7.2.1
* Tested in Nexus 5 API 25 and Nexus 6 API 24
* Emulator and Real Device

**Comment by imurchie** [comment]
Can you provide the Appium server logs, as a [gist](https://gist.github.com)?

**Comment by imurchie** [comment]
Logcat logs for a run:

```
01-05 08:37:10.192  1482  1872 I ActivityManager: Start proc 2799:io.appium.settings/u0a61 for service io.appium.settings/.LocationService
01-05 08:37:10.194  2799  2799 I art     : Not late-enabling -Xcheck:jni (already on)
01-05 08:37:10.197  2799  2799 W art     : Unexpected CPU variant for X86 using defaults: x86_64
01-05 08:37:10.209  2790  2790 D AndroidRuntime: Shutting down VM
01-05 08:37:10.239  2799  2799 W System  : ClassLoader referenced unknown path: /data/app/io.appium.settings-1/lib/x86_64
01-05 08:37:10.246  2799  2799 I LocationService: setting the location from service with longitude: 78.04 latitude: 27.17
01-05 08:37:10.277  2799  2799 D AndroidRuntime: Shutting down VM
01-05 08:37:10.278  2799  2799 E AndroidRuntime: FATAL EXCEPTION: main
01-05 08:37:10.278  2799  2799 E AndroidRuntime: Process: io.appium.settings, PID: 2799
01-05 08:37:10.278  2799  2799 E AndroidRuntime: java.lang.RuntimeException: Unable to start service io.appium.settings.LocationService@a43dc22 with Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=io.appium.settings/.LocationService (has extras) }: java.lang.SecurityException: io.appium.settings from uid 10061 not allowed to perform MOCK_LOCATION
01-05 08:37:10.278  2799  2799 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3314)
01-05 08:37:10.278  2799  2799 E AndroidRuntime: 	at android.app.ActivityThread.-wrap21(ActivityThread.java)
01-05 08:37:10.278  2799  2799 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1565)
01-05 08:37:10.278  2799  2799 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-05 08:37:10.278  2799  2799 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
01-05 08:37:10.278  2799  2799 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6077)
01-05 08:37:10.278  2799  2799 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-05 08:37:10.278  2799  2799 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
01-05 08:37:10.278  2799  2799 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
01-05 08:37:10.278  2799  2799 E AndroidRuntime: Caused by: java.lang.SecurityException: io.appium.settings from uid 10061 not allowed to perform MOCK_LOCATION
01-05 08:37:10.278  2799  2799 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1683)
01-05 08:37:10.278  2799  2799 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1636)
01-05 08:37:10.278  2799  2799 E AndroidRuntime: 	at android.location.ILocationManager$Stub$Proxy.addTestProvider(ILocationManager.java:1121)
01-05 08:37:10.278  2799  2799 E AndroidRuntime: 	at android.location.LocationManager.addTestProvider(LocationManager.java:1236)
01-05 08:37:10.278  2799  2799 E AndroidRuntime: 	at io.appium.settings.MockLocationProvider.pushLocation(MockLocationProvider.java:20)
01-05 08:37:10.278  2799  2799 E AndroidRuntime: 	at io.appium.settings.LocationService.onStartCommand(LocationService.java:25)
01-05 08:37:10.278  2799  2799 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3297)
01-05 08:37:10.278  2799  2799 E AndroidRuntime: 	... 8 more
```

**Comment by imurchie** [comment]
Adding to our work queue.

**Comment by luisromanwp** [comment]
@imurchie 
Here you have: https://gist.github.com/luisromanwp/d3fe2246f97aa0a213e0ee5d3ee3fa65

**Comment by jlipps** [comment]
do we not have the MOCK_LOCATION permission allowed? or maybe users need to allow mock locations in an emulator setting?

**Comment by Helias-Criouet** [comment]
Adding AppiumSettings as the mock location app in the Developer Settings fixes the issue. Is there any way for Appium to configure that by itself @jlipps ?

**Comment by jlipps** [comment]
That's a good question @Helias-Criouet. Can you describe the steps you went through to do this using the UI exactly?

**Comment by Helias-Criouet** [comment]
@jlipss Since Android 6.0, the option to enable/disable mock location in the "Dev Settings" has disappeared in favor of an option to choose a mock location application.
I just tapped on this option: this made a modal appear, and it suggested me to choose "Appium Settings", which I did.

**Comment by jlipps** [comment]
Thank you. Adjusting the title of this issue to reflect the necessary investigation.
