### ISSUE TITLE
Appium occasionally fails to launch application

### ISSUE THREAD

**Issue by codiophile** [appium/appium#7650]
## The problem

Application occasionally fails to launch with following error:

```
[XCUITest] UnknownError: An unknown server-side error occurred while processing the command. Original error: Failed to launch com.app.identifier application
    at errorFromCode (../../../lib/mjsonwp/errors.js:398:10)
    at XCUITestDriver.callee$0$0$ (../../../lib/commands/proxy-helper.js:22:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 { UnknownError: An unknown server-side error occurred while processing the command. Original error: Failed to launch com.app.identifier application
    at errorFromCode (../../../lib/mjsonwp/errors.js:398:10)
    at XCUITestDriver.callee$0$0$ (../../../lib/commands/proxy-helper.js:22:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37) jsonwpCode: 13 }
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): 1.5.3
* Desktop OS/version used to run Appium: mac 10.12
* Node.js version (unless using Appium.app|exe): v7.0.0
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: Appium CLI

## Details

This only happens occasionally and it started happening after migrating to iOS 10 and XCUITest. 

## Link to Appium logs

https://gist.github.com/codiophile/1d6597fbde12122e91bf1d5b170db69c

**Comment by imurchie** [comment]
Can you update the next time it happens? There is little that can be done from the logs provided.

**Comment by codiophile** [comment]
It happened again on the last run. I am examining the logs at the moment, trying to find the relevant part. Out of 61 scenarios, 3 failed for this reason.

**Comment by codiophile** [comment]
Logs are coming. They are massive, so we need to extract just the relevant parts. Unfortunately that might have to wait as we are working on a release with a tight deadline and I don't have a lot of time to spare for this. 

We are currently working around this problem by catching the exception and trying again, which so far has been working fine for us, but ultimately it would be nice if we didn't have to do that.

**Comment by jlipps** [comment]
@codiophile have you also verified that simply launching your app on the simulator 100 times doesn't have the same failure rate? Or tailed the sim logs to ensure there's not a non-deterministic crash on the app side?

**Comment by codiophile** [comment]
Finally found the time to retrieve the logs:

https://gist.github.com/codiophile/1d6597fbde12122e91bf1d5b170db69c

**Comment by jlipps** [comment]
@codiophile unfortunately that error is coming from WDA. The only thing I can recommend is to try the latest version of Appium which has some WDA updates that might have addressed the cause somehow.
