### ISSUE TITLE
Appium not working with XCode 8.

### ISSUE THREAD

**Issue by ankitthakur** [appium/appium#7685]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

```
[TestNG] Running:
  /private/var/folders/p_/ky29dtlj4g7_9l1jm_q8gh2rs_br95/T/testng-eclipse--1466292208/testng-customsuite.xml

FAILED CONFIGURATION: @BeforeTest setUp
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: xcodebuild failed with code 65 (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 22.31 seconds
Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:55:52'
System info: host: 'N/A', ip: 'N/A', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.7.0_79'
Driver info: io.appium.java_client.ios.IOSDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:647)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:180)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:247)
```
## Appium Console Logs in Derived Data

```
15:28:57.275 xcodebuild[4319:38743] Beginning test session WebDriverAgentRunner-D6AE43D4-6599-4C03-A34F-0B90FBC21B86 at 2017-01-12 15:28:57.274 with Xcode 8C1002 on target <DVTiOSDevice: 0x7f921d265930> {
		deviceSerialNumber:         C31JT74BDTWF
		identifier:                 e8df35db8d93294fd568816a7c35c234389fd57b
		deviceClass:                iPhone
		deviceName:                 iPhone
		deviceIdentifier:           e8df35db8d93294fd568816a7c35c234389fd57b
		productVersion:             10.2
		buildVersion:               14C92
		deviceSoftwareVersion:      10.2 (14C92)
		deviceArchitecture:         armv7s
		deviceTotalCapacity:        13123432448
		deviceAvailableCapacity:    11550240768
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		deviceType:                 <DVTDeviceType:0x7f921ce1ce20 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		activityProgress:          -2
		activityTitle:             
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	} (10.2 (14C92))
15:28:57.275 xcodebuild[4319:38743] 	/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild
build
test
-project
/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj
-scheme
WebDriverAgentRunner
-destination
id=e8df35db8d93294fd568816a7c35c234389fd57b
-configuration
Debug
15:28:57.275 xcodebuild[4319:38743] Launching with Xcode.IDEFoundation.Launcher.PosixSpawn
15:28:57.277 xcodebuild[4319:38743] Initializing test infrastructure.
15:28:57.558 xcodebuild[4319:38743] Launch session started, setting a disallow-finish-token on the run operation.
15:28:57.814 xcodebuild[4319:38771] Creating the test bundle connection.
15:28:57.815 xcodebuild[4319:38771] Listening for proxy connection request from the test bundle (all platforms)
15:28:57.815 xcodebuild[4319:38771] Resuming the connection.
15:28:57.816 xcodebuild[4319:38771] Test connection requires daemon assistance.
15:28:57.817 xcodebuild[4319:38743] Starting test session with ID <__NSConcreteUUID 0x7f921d85b8b0> D6AE43D4-6599-4C03-A34F-0B90FBC21B86
15:28:57.817 xcodebuild[4319:38743] Checking test manager availability..., will wait up to 120s
15:28:57.932 xcodebuild[4319:38746] testmanagerd handled session request.
15:28:57.932 xcodebuild[4319:38743] Waiting for test process to launch.
15:28:58.287 xcodebuild[4319:38746] app uninstall set - {(
)}
15:28:58.287 xcodebuild[4319:38746] app install set - {(
    <DVTFilePath:0x7f921d390bf0:'/Users/${user}/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app'>
)}
15:29:01.456 xcodebuild[4319:38815] remoteExecutable setInstalledPath:/private/var/containers/Bundle/Application/56C44038-FEA6-4B03-BC36-865E4D7FEC6F/WebDriverAgentRunner-Runner.app

15:29:01.459 xcodebuild[4319:38815] Updated test configuration at /var/folders/p_/ky29dtlj4g7_9l1jm_q8gh2rs_br95/T/com.apple.dt.XCTest/D6AE43D4-6599-4C03-A34F-0B90FBC21B86/remote-container/tmp/WebDriverAgentRunner-D6AE43D4-6599-4C03-A34F-0B90FBC21B86.xctestconfiguration with device paths: <XCTestConfiguration: 0x7f921d853750>
	                  testBundleURL:file:///private/var/containers/Bundle/Application/56C44038-FEA6-4B03-BC36-865E4D7FEC6F/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest
	         testBundleRelativePath:(null)
	              productModuleName:WebDriverAgentRunner
	                    testsToSkip:(null)
	                     testsToRun:(null)
	             reportResultsToIDE:YES
	              sessionIdentifier:<__NSConcreteUUID 0x7f921d85b8b0> D6AE43D4-6599-4C03-A34F-0B90FBC21B86
	     pathToXcodeReportingSocket:(null)
	      disablePerformanceMetrics:no
	treatMissingBaselinesAsFailures:no
	                baselineFileURL:(null)
	       baselineFileRelativePath:(null)
	          targetApplicationPath:(null)
	      targetApplicationBundleID:(null)
	               reportActivities:YES
	       testsMustRunOnMainThread:YES
	         initializeForUITesting:YES
	 aggregateStatisticsBeforeCrash:{
    XCSuiteRecordsKey =     {
    };
}

15:29:02.082 xcodebuild[4319:38743] Adding console adaptor <IDEConsoleAdaptor: 0x7f921d55ee40 'target'> for test session D6AE43D4-6599-4C03-A34F-0B90FBC21B86.
15:29:02.352 xcodebuild[4319:38743] Test process runnable PID is 849.
15:29:02.903 xcodebuild[4319:38743] ############## DID EXECUTE #################
15:29:02.903 xcodebuild[4319:38743] Launch session expired.
15:29:02.904 xcodebuild[4319:38743] Test operation failure: Launch session expired before checking in.
15:29:02.904 xcodebuild[4319:38743] _finishWithError:Error Domain=IDETestOperationsObserverErrorDomain Code=4 "Launch session expired before checking in." UserInfo={NSLocalizedDescription=Launch session expired before checking in.} didCancel: 1


```

## Code To Reproduce Issue [ Good To Have ]

```
public AppiumDriver	driver;
	
	@BeforeTest
	public void setUp() throws Exception { 
		
		DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setCapability("platformName", "iOS");
		capabilities.setCapability("browserName", "");
		capabilities.setCapability("automationName", "XCUITest");
		
		capabilities.setCapability("deviceName", "iPhone (10.2) [${device id}]");
		capabilities.setCapability("udid","${udid}");
		capabilities.setCapability("platformVersion", "10.2");
		capabilities.setCapability("app", "/Users/{user}/Desktop/SA/Sample.app");
		
		driver = new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);

	}

	@AfterTest
	public void tearDown() throws Exception {
		driver.quit();
	}
```

## System details:

Xcode 8.2.1
Build version 8C1002

appium --version
1.6.3

Eclipse Java EE IDE for Web Developers.
Version: Mars.2 Release (4.5.2)
Build id: 20160218-0600

MacOS - El Capitan - 10.11.6 (15G1212)

**Comment by mykola-mokhnach** [comment]
This looks like WDA cannot be started on the device. Most likely, this happens because it is signed incorrectly

**Comment by kcinman11358** [comment]
@mykola-mokhnach is correct. this is most likely a signing issue

**Comment by ohadschn** [comment]
I got the "Launch session expired" error when my device ran low on battery and the "low battery" prompt was showing.

**Comment by mishachandan** [comment]
@mykola-mokhnach +1 Signing solved the problem.
