### ISSUE TITLE
browser.get always opens default device browser instead of using app webview

### ISSUE THREAD

**Issue by lordgreg** [appium/appium#7744]
## The problem

I have a hybrid app, meaning cordova app with WebView, where my app runs. In protractor test, I'm calling a simple `browser.get('/#/info/');` which should open an exact url in my webview, not external, android default browser with url.

## Environment

* Appium version (or git revision) that exhibits the issue:
```
▶ appium --version                                                              
1.6.3
```
* -Last Appium version that did not exhibit the issue (if applicable):-
* Desktop OS/version used to run Appium:
macOS Sierra 10.12.2 (16C67) 
* Node.js version (unless using Appium.app|exe):
```
node --version
v6.9.4
```
* Mobile platform/version under test:
Android Device (Galaxy S6 and Genymotion Nexus 5X, Android 6)
iOS simulator (any)
iOS 9.3 iPad Mini 2
iOS 10.2 iPad Air 2
* Real device or emulator/simulator:
Real devices.
* Appium CLI or Appium.app|exe:
CLI

## Details

-

## Link to Appium logs

protractor + appium config (android): http://pastebin.com/yyMGB28a
protractor + appium config (ios): http://pastebin.com/22vuqUww
appium log: http://pastebin.com/PcfwNnub

## Code To Reproduce Issue [ Good To Have ]

1. clone https://github.com/mwaylabs/generator-m-ionic-demo
2. npm i && bower i
3. gulp --cordova 'prepare android'
4. gulp --cordova 'build android'
5. run appium
6. run protractor _CONFIG_ABOVE_

### Protractor test

```
'use strict';

describe('Debug page', function () {

  beforeEach(function () {
    // browser.ignoreSynchronization = true;
    browser.get('/#/side/debug');
    browser.driver.sleep(500);
  });

  it('should grade passwords', function () {

    var passwordInput = element(by.model('ctrl.password.input'));
    var passwordStrength = element(by.binding('ctrl.password.strength'));

    // weak
    passwordInput.sendKeys('my');
    expect(passwordStrength.getInnerHtml()).toEqual('weak');
    expect(passwordStrength.getAttribute('class')).toContain('badge-assertive');

    // medium
    passwordInput.sendKeys('test');
    expect(passwordStrength.getInnerHtml()).toEqual('medium');
    expect(passwordStrength.getAttribute('class')).toContain('badge-energized');

    // strong
    passwordInput.sendKeys('tesyasdft');
    expect(passwordStrength.getInnerHtml()).toEqual('strong');
    expect(passwordStrength.getAttribute('class')).toContain('badge-balanced');

  });
});
```

**Comment by jlipps** [comment]
Have you tried with non-relative urls? Browsers (and webviews) don't understand URLs without a domain, right?

Anyway it looks like your framework is doing something with javascript when you call browser.get. the logs show this:

> "script":"window.name = \"NG_DEFER_BOOTSTRAP!\" + window.name;window.location.replace(\"file:///android_asset/www/index.html/#/side/debug\"

Perhaps this isn't working? What kind of object is `browser` in your code?

**Comment by lordgreg** [comment]
Hi and thank you for your feedback.

My browser object is:
```
ProtractorBrowser {
  controlFlow: [Function],
  schedule: [Function],
  setFileDetector: [Function],
  getExecutor: [Function],
  getSession: [Function],
  getCapabilities: [Function],
  quit: [Function],
  actions: [Function],
  touchActions: [Function],
  executeScript: [Function],
  executeAsyncScript: [Function],
  call: [Function],
  wait: [Function],
  sleep: [Function],
  getWindowHandle: [Function],
  getAllWindowHandles: [Function],
  getPageSource: [Function],
  close: [Function],
  getCurrentUrl: [Function],
  getTitle: [Function],
  findElementInternal_: [Function],
  findElementsInternal_: [Function],
  takeScreenshot: [Function],
  manage: [Function],
  switchTo: [Function],
  driver: 
   WebDriver {
     flow_: 
      ControlFlow {
        propagateUnhandledRejections_: true,
        activeQueue_: [Object],
        taskQueues_: [Object],
        shutdownTask_: null,
        hold_: [Object] },
     session_: 
      ManagedPromise {
        flow_: [Object],
        stack_: null,
        parent_: null,
        callbacks_: null,
        state_: 'fulfilled',
        handled_: true,
        value_: [Object],
        queue_: [Object] },
     executor_: Executor { w3c: false, customCommands_: [Object], log_: [Object] },
     fileDetector_: null,
     onQuit_: undefined,
     getNetworkConnection: [Function],
     setNetworkConnection: [Function] },
  element: { [Function: element] all: [Function] },
  '$': [Function],
  '$$': [Function],
  baseUrl: 'http://localhost:3000',
  rootEl: '',
  internalIgnoreSynchronization: false,
  getPageTimeout: 10000,
  params: {},
  ready: 
   ManagedPromise {
     flow_: 
      ControlFlow {
        propagateUnhandledRejections_: true,
        activeQueue_: [Object],
        taskQueues_: [Object],
        shutdownTask_: null,
        hold_: [Object] },
     stack_: 
      { Task: WebDriver.manage().timeouts().setScriptTimeout(11000)
          at WebDriver.schedule (/Users/aaaaaaaa/Projects/@Test/generator-m-ionic-demo/node_modules/selenium-webdriver/lib/webdriver.js:816:17)
          at Timeouts._scheduleCommand (/Users/aaaaaaaa/Projects/@Test/generator-m-ionic-demo/node_modules/selenium-webdriver/lib/webdriver.js:1500:25)
          at Timeouts.setScriptTimeout (/Users/aaaaaaaa/Projects/@Test/generator-m-ionic-demo/node_modules/selenium-webdriver/lib/webdriver.js:1483:17)
          at Runner.createBrowser (/Users/aaaaaaaa/Projects/@Test/generator-m-ionic-demo/node_modules/protractor/lib/runner.ts:215:49)
          at driverprovider_.setupEnv.then (/Users/aaaaaaaa/Projects/@Test/generator-m-ionic-demo/node_modules/protractor/lib/runner.ts:279:27)
          at _fulfilled (/Users/aaaaaaaa/Projects/@Test/generator-m-ionic-demo/node_modules/protractor/node_modules/q/q.js:834:54)
          at self.promiseDispatch.done (/Users/aaaaaaaa/Projects/@Test/generator-m-ionic-demo/node_modules/protractor/node_modules/q/q.js:863:30)
          at Promise.promise.promiseDispatch (/Users/aaaaaaaa/Projects/@Test/generator-m-ionic-demo/node_modules/protractor/node_modules/q/q.js:796:13)
          at /Users/aaaaaaaa/Projects/@Test/generator-m-ionic-demo/node_modules/protractor/node_modules/q/q.js:556:49
          at runSingle (/Users/aaaaaaaa/Projects/@Test/generator-m-ionic-demo/node_modules/protractor/node_modules/q/q.js:137:13) name: 'Task' },
     parent_: null,
     callbacks_: null,
     state_: 'fulfilled',
     handled_: true,
     value_: null,
     queue_: null },
  plugins_: 
   Plugins {
     setup: [Function],
     onPrepare: [Function],
     teardown: [Function],
     postResults: [Function],
     postTest: [Function],
     onPageLoad: [Function],
     onPageStable: [Function],
     waitForPromise: [Function],
     waitForCondition: [Function],
     pluginObjs: [],
     assertions: {},
     resultsReported: false },
  resetUrl: 'data:text/html,<html></html>',
  debugHelper: DebugHelper { browserUnderDebug_: [Circular] },
  trackOutstandingTimeouts_: true,
  mockModules_: 
   [ { name: 'protractorBaseModule_',
       script: [Function],
       args: [Object] } ],
  ExpectedConditions: ProtractorExpectedConditions { browser: [Circular] },
  allScriptsTimeout: 11000,
  getProcessedConfig: [Function],
  forkNewDriverInstance: [Function],
  restart: [Function] }
```

I've also tried to input the full path, aka. `http://localhost:3000/#/main/debug` for example which didn't made any difference. But, as you said, browser needs full url, that's why didn't the `.get()` function from Protractor work. 

User @sjelin has wrote a perfect response for what the difference is between `.get()` and `.setLocation()`:
> browser.setLocation() uses Angular's $location. browser.driver.get is like typing in a new URL into the search bar. browser.get, which is what most people use, is a wrapped version of browser.driver.get which waits for everything to be synced.

So, these 2 methods worked at the end:
```
browser.getCurrentUrl()
    .then(function (data) {
      // returns file:///var/containers/Bundle/Application/A4B07338-8600-48F0-ADEF-6D0983BD369A/My%20Project.app/www/index.html#/main/list
    });

    // use browser.get(url_above_replace('list', 'debug');
```

or, clearly the winner:
```
browser.setLocation('/main/debug');
```

thank you very much for pointing me into the right direction.


Regards! 👍

**Comment by lordgreg** [comment]
To add something to the comment above..

browser.setLocation() isn't working in browser. So we're back at start.

adding protractor part in confg:
```
  onPrepare: function () {
    var wd = require('wd'),
      protractor = require('protractor'),
      wdBridge = require('wd-bridge')(protractor, wd);
    wdBridge.initFromProtractor(exports.config);

    //To navigate using file:// rather than http://
    var defer = protractor.promise.defer();

    /*globals browser*/
    browser.ignoreSynchronization = true;

    browser.executeScript('return window.location;').then(function (location) {
      browser.resetUrl = 'file://';
      browser.baseUrl = location.origin + location.pathname;
      defer.fulfill();
    });

    return defer.promise;
  }
```

fixes that, so that `browser.get('#/main/debug');` works. The workaround/fix was found on next website: http://flashquartermaster.com/2016/08/02/automated-cross-platform-testing-of-ios-and-android-hybrid-ionic-cordova-angular-apps-using-cucumber-protractor-chai-and-appium/

**Comment by jlipps** [comment]
Thanks for the update @lordgreg and glad we clarified things. IMO protractor does a lot of magic like this that often obscures what's going on.

**Comment by sjelin** [comment]
Protractor does indeed do a lot of magic, and sadly appium support isn't a priority right now 😢
