### ISSUE TITLE
iOS: Simulator: After few tests driver failed to start when we use: fullReset=false + noReset=true

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium#7746]
## The problem

When we execute tests with driver capabilities 'fullReset=false + noReset=true' Appium does not close Simulator. But after 10-15 successful tests driver fails to start.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3 latest
* Desktop OS/version used to run Appium: 10.12.2
* Mobile platform/version under test: MAC
* Real device or emulator/simulator: Simulator 10.0

## Link to Appium logs

Error: simctl error running 'uninstall': An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=163):
Unable to lookup in current state: Shutdown
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at simCommand$ (lib/simctl.js:22:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[MJSONWP] Encountered internal error running command: Error: simctl error running 'uninstall': An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=163):
Unable to lookup in current state: Shutdown
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at simCommand$ (lib/simctl.js:22:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)

**Comment by jlipps** [comment]
Can you send in the full appium logs? Any other idea why the sim would be in a shutdown state? Did it crash on its own maybe?

**Comment by amedvedjev** [comment]
to restart client inside tests i am closing Simulator and do "driver.startApp()". after some tests with such logic it stuck with this error. full logs will try to collect tomorrow.

**Comment by jlipps** [comment]
The preferred way to do this is just to stop and start a session. launchApp is not a good strategy.

**Comment by amedvedjev** [comment]
@jlipps you mean driver.quit() and start again?

**Comment by jlipps** [comment]
Yes, I don't recommend using launchApp, startApp, or stopApp. Just create a new session for each test, and use `noReset` if you want to speed things up.

**Comment by amedvedjev** [comment]
i use no Reset as many as possible. but some test need other state. will try to switch.
