### ISSUE TITLE
[Appium 1.6.3] Unable to run XCUItests : was "Still trying to use UIAutomation"; now "Failing in simulator automation"

### ISSUE THREAD

**Issue by JESii** [appium/appium#7811]
## The problem

I'm trying to run ruby/cucumber tests with Appium, right now for the IphoneSimulator and next for a real iOS device. The command I'm using is:
```
bundle exec cucumber   DEVICE=IphoneSimulator -p mobile_website_default    SITE=MCOM URL=http://<test-url>/  features/website/Selection/MEW/registry/MCOM/registry_navigation.feature:14
```
The command is eventually failing with:
```
A new session could not be created. Details: Appium's IosDriver does not support xcode version 8.2.1. Apple has deprecated UIAutomation. Use the "XCUITest" automationName capability instead
```
I previously had problems with SafariLauncher (issue #7776) on Xcode 7.3.1 so upgraded to Xcode 8.1 hoping the XCUItest setup would solve the problem. No luck so far...

## Environment

* Appium version (or git revision) that exhibits the issue:
1.6.3
* Last Appium version that did not exhibit the issue (if applicable):
N/A
* Desktop OS/version used to run Appium:
OSX ElCap; 10.11.6
* Node.js version (unless using Appium.app|exe):
7.5.0
* Mobile platform/version under test:
iOS 9.3
* Real device or emulator/simulator:
iOS Simulator
* Appium CLI or Appium.app|exe:
Appium CLI

#### What I've installed and configured

Appium.CLI is running with command
`appium -g ~/appium_server.log`
appium-ios-driver -g installed @1.16.0
libimobiledevice installed @1.2.0
ideviceinstaller installed @1.1.0
ios-deploy -g installed  - version 1.9.1
carthage installed; no cartfile; testing web page, not app
.xcconfig defined and contains default settings
```
DEVELOPMENT_TEAM = XXXXXXXXXX
CODE_SIGN_IDENTITY = iPhone Developer
```

## Details

When I run the cucumber command, it is trying to use the old UIAutomation instead of the XCUItest drivers, so I probably have something installed/configured incorrectly.

I just re-installed `npm appium -g` from scratch to remove any old stuff.

## Link to Appium logs

https://gist.github.com/JESii/a93d568c87ac3a646278911c499d48c7

## Code To Reproduce Issue [ Good To Have ]

Not testing an app; testing a web page through ruby/cucumber

**Comment by imurchie** [comment]
Did you try setting the `automationName` to `XCUITest`? 

```
2017-02-06 16:40:29:126 - error: [iOS] SessionNotCreatedError: A new session could not be created. Details: Appium's IosDriver does not support xcode version 8.2.1. Apple has deprecated UIAutomation. Use the "XCUITest" automationName capability instead.
```

**Comment by JESii** [comment]
Didn't know I had to do that; thanks... I'm trying the simulator again.

got this error now:
`An unknown server-side error occurred while processing the command. Original error: xcodebuild failed with code 70 (Selenium::WebDriver::Error::UnknownError)`

**Comment by imurchie** [comment]
Without the full logs I have no idea how to help.

**Comment by JESii** [comment]
Of course; sorry. Here's the latest, with info from the latest run with automationName=XCUItest
https://gist.github.com/JESii/472c82ceffc066a26392de99a9e2e4a8

**Comment by imurchie** [comment]
The next step in debugging is to try the following, and checking the output:

```
cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=7C78C320-2047-4C7E-8A21-4920960416F3 -configuration Debug
```

**Comment by JESii** [comment]
OK; the build succeeded and the simulator started running. Here's the tail end of the output.

```
Signing Identity:     "-"

    /usr/bin/codesign --force --sign - --timestamp=none /Users/yc98js1/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest

** TEST BUILD SUCCEEDED **

2017-02-06 10:11:41.850 xcodebuild[47665:14392170]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/yc98js1/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/606143E3-C6C6-4B6F-8E71-6476351E46BD/Session-WebDriverAgentRunner-2017-02-06_101141-eUg7Yv.log
2017-02-06 10:11:41.851 xcodebuild[47665:14392164] [MT] IDETestOperationsObserverDebug: (78E07CA0-ED91-4744-984B-7204FAA34195) Beginning test session WebDriverAgentRunner-78E07CA0-ED91-4744-984B-7204FAA34195 at 2017-02-06 10:11:41.851 with Xcode 8C1002 on target <DVTiPhoneSimulator: 0x7fda947ef750> {
		SimDevice: SimDevice : iPhone 6 (7C78C320-2047-4C7E-8A21-4920960416F3) : state={ Shutdown } deviceType={ SimDeviceType : com.apple.CoreSimulator.SimDeviceType.iPhone-6 } runtime={ SimRuntime : 9.3 (13E233) - com.apple.CoreSimulator.SimRuntime.iOS-9-3 }
} (9.3 (13E233))

2017-02-06 10:12:27.427 XCTRunner[48186:14394931] Running tests...
2017-02-06 10:12:36.295 XCTRunner[48186:14394931] Continuing to run tests in the background with task ID 1
Test Suite 'All tests' started at 2017-02-06 10:12:36.897
Test Suite 'WebDriverAgentRunner.xctest' started at 2017-02-06 10:12:36.898
Test Suite 'UITestingUITests' started at 2017-02-06 10:12:36.898
Test Case '-[UITestingUITests testRunner]' started.
    t =     0.00s     Start Test at 2017-02-06 10:12:36.899
    t =     0.00s     Set Up
2017-02-06 10:12:36.902 XCTRunner[48186:14394931] Built at Feb  6 2017 09:30:41
2017-02-06 10:12:36.915 XCTRunner[48186:14394931] ServerURLHere->http://11.142.224.1:8100<-ServerURLHere
```

**Comment by JESii** [comment]
But there was this error at the very beginning of the output:
```
xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=7C78C320-2047-4C7E-8A21-4920960416F3 -configuration Debug
=== BUILD TARGET WebDriverAgentLib OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===

Check dependencies
The file “ProjectSettings.xcconfig” couldn’t be opened because there is no such file. (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Configurations/ProjectSettings.xcconfig)

ProcessInfoPlistFile /Users/yc98js1/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/WebDriverAgentLib.framework/Info.plist WebDriverAgentLib/Info.plist
    cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/yc98js1/bin:/Users/yc98js1/.rvm/gems/ruby-2.0.0-p643/bin:/Users/yc98js1/.rvm/gems/ruby-2.0.0-p643@global/bin:/Users/yc98js1/.rvm/rubies/ruby-2.0.0-p643/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Library/Java/JavaVirtualMachines/jdk1.8.0_73.jdk/Contents/Home/bin:/Users/yc98js1/Android/tools:/Users/yc98js1/Android/platform-tools:/Users/yc98js1/.rvm/bin:/usr/local/share/npm/bin:/opt/oracle/instantclient_11_2"
    builtin-infoPlistUtility /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Info.plist -expandbuildsettings -format binary -platform iphonesimulator -o /Users/yc98js1/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/WebDriverAgentLib.framework/Info.plist

Ld /Users/yc98js1/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/WebDriverAgentLib.framework/WebDriverAgentLib normal x86_64
    cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
    export IPHONEOS_DEPLOYMENT_TARGET=9.3
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/
...
```

**Comment by imurchie** [comment]
That error is gone in the latest release.

If the build does not work through Appium when it works manually, can you use the `showXcodeLog` capability (set to `true`). This ought to put the full Xcode logs into the Appium logs, and make more clear what the problem is.

**Comment by JESii** [comment]
OK; I'll get that and get back to you.

Also, I tried re-running the same xcode-build command and this time, I get a simulator timeout error: not sure if that's helpful, but just in case...
```
xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=7C78C320-2047-4C7E-8A21-4920960416F3 -configuration Debug
=== BUILD TARGET WebDriverAgentLib OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===

Check dependencies
The file “ProjectSettings.xcconfig” couldn’t be opened because there is no such file. (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Configurations/ProjectSettings.xcconfig)

=== BUILD TARGET WebDriverAgentRunner OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===

Check dependencies
The file “ProjectSettings.xcconfig” couldn’t be opened because there is no such file. (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Configurations/ProjectSettings.xcconfig)

** TEST BUILD SUCCEEDED **

2017-02-06 10:22:53.173 xcodebuild[54514:14411260]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/yc98js1/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/F591E070-64DC-4D9F-892B-6CBBEA4F6CBE/Session-WebDriverAgentRunner-2017-02-06_102253-CkT8W2.log
2017-02-06 10:22:53.173 xcodebuild[54514:14411252] [MT] IDETestOperationsObserverDebug: (2F0FC206-8EB0-4BD2-B669-B5BD675573D6) Beginning test session WebDriverAgentRunner-2F0FC206-8EB0-4BD2-B669-B5BD675573D6 at 2017-02-06 10:22:53.172 with Xcode 8C1002 on target <DVTiPhoneSimulator: 0x7fb01eac9630> {
                SimDevice: SimDevice : iPhone 6 (7C78C320-2047-4C7E-8A21-4920960416F3) : state={ Shutdown } deviceType={ SimDeviceType : com.apple.CoreSimulator.SimDeviceType.iPhone-6 } runtime={ SimRuntime : 9.3 (13E233) - com.apple.CoreSimulator.SimRuntime.iOS-9-3
}
} (9.3 (13E233))
2017-02-06 10:24:53.180 xcodebuild[54514:14411270]  iOSSimulator: Timed out waiting 120 seconds for simulator to boot, current state is 1.
2017-02-06 10:24:53.185 xcodebuild[54514:14411252] Error Domain=IDETestOperationsObserverErrorDomain Code=3 "Timed out waiting 120 seconds for simulator to boot, current state is 1. If you believe this error represents a bug, please attach the log file at /Users/yc98js1/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/F591E070-64DC-4D9F-892B-6CBBEA4F6CBE/Session-WebDriverAgentRunner-2017-02-06_102253-CkT8W2.log" UserInfo={NSLocalizedDescription=Timed out waiting 120 seconds for simulator
to boot, current state is 1. If you believe this error represents a bug, please attach the log file at /Users/yc98js1/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/F591E070-64DC-4D9F-892B-6CBBEA4F6CBE/Session-WebDriverAgentRunner-2017-02-06_102253-CkT8W2.log}
```

**Comment by JESii** [comment]
OK; here's the log file: https://gist.github.com/JESii/618a5a55b07fb4dd3bb2e6cdb9fc7cfe

#### Actions & Visual results
1) appium server running
    `appium -g ~/appium_server.log --automation-name XCUItest --default-capabilities '{"showXcodeLog": "true"}'`
2) started cucumber: 
    `bundle exec cucumber   DEVICE=IphoneSimulator -p mobile_website_default     SITE=MCOM URL=http://XXX.com/ features/website/Selection/MEW/registry/MCOM/registry_navigation.feature:14`
3) Simulator started
4) Test eventually loaded our home page for testing and threw the following error:
```
And I visit a registry "Home" page via "GNav"                 # features/step_definitions/mobile_website/registry_migration/registry_brand_index_steps.rb:20
      Element {:xpath=>".//body[1]"} does not exist in cache (status: 10) (Selenium::WebDriver::Error::JavascriptError)
```
5) I see the simulator constantly reloading the page
6) And I see the appium server throwing constant error stream as follows:
```
[debug] [iOS] Remote debugger notified us of a new page listing: {"appIdKey":"67242","pageArray":[{"id":1,"title":"Macy's - Shop Fashion Clothing & Accessories - Official Site - Macys.com","url":"http://m.qa19codemacys.fds.com/","isKey":true}]}
[debug] [iOS] Checking if page needs to load
[debug] [iOS] Page load needed. Loading.
[debug] [RemoteDebugger] Page loaded, verifying whether ready
[debug] [RemoteDebugger] Received applicationSentData response
[debug] [RemoteDebugger] Received applicationSentData response
[debug] [RemoteDebugger] Frame navigated, unloading page
(node:65282) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1035): TypeError: this.specialHandlers.Page.frameNavigated is not a function
[debug] [RemoteDebugger] Received applicationSentData response
[debug] [RemoteDebugger] Found data handler for response
[debug] [RemoteDebugger] Received data response from socket send: 'complete'
[debug] [RemoteDebugger] Original command: sendJSCommand
[debug] [RemoteDebugger] readyState was "complete"
[debug] [RemoteDebugger] Page is ready
[debug] [iOS] New page listing is same as old, doing nothing
[debug] [RemoteDebugger] Received applicationSentData response
[debug] [RemoteDebugger] Found data handler for response
[debug] [RemoteDebugger] Received data response from socket send: 'complete'
[debug] [RemoteDebugger] Original command: sendJSCommand
[debug] [RemoteDebugger] readyState was "complete"
[debug] [RemoteDebugger] Page is ready
[debug] [iOS] New page listing is same as old, doing nothing
[debug] [RemoteDebugger] Checking document readyState
[debug] [RemoteDebugger] Sending javascript command (function (){ return document.readyState; })()
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to remote debugger
[debug] [RemoteDebugger] Received applicationSentData response
[debug] [RemoteDebugger] Found data handler for response
[debug] [RemoteDebugger] Received data response from socket send: 'complete'
[debug] [RemoteDebugger] Original command: sendJSCommand
[debug] [RemoteDebugger] readyState was "complete"
[debug] [RemoteDebugger] Page is ready
[debug] [iOS] New page listing is same as old, doing nothing
[debug] [RemoteDebugger] Receiving data from remote debugger: '{"__argument":{"WIRApplicationIdentifierKey":"PID:67242","WIRListingKey":{"1":{"WIRTitleKey":"Macy's - Shop Fashion Clothing & Accessories - Official Site - Macys.com","WIRTypeKey":"WIRTypeWeb","WIRURLKey":"http://m.qa19codemacys.fds.com/","WIRPageIdentifierKey":1,"WIRConnectionIdentifierKey":"446aa350-66a8-4b3c-8ecc-7c9a91b87799"}}},"__selector":"_rpc_applicationSentListing:"}'
[debug] [RemoteDebugger] Page changed: {"1":{"WIRTitleKey":"Macy's - Shop Fashion Clothing & Accessories - Official Site - Macys.com","WIRTypeKey":"WIRTypeWeb","WIRURLKey":"http://m.qa19codemacys.fds.com/","WIRPageIdentifierKey":1,"WIRConnectionIdentifierKey":"446aa350-66a8-4b3c-8ecc-7c9a91b87799"}}
[debug] [iOS] Remote debugger notified us of a new page listing: {"appIdKey":"67242","pageArray":[{"id":1,"title":"Macy's - Shop Fashion Clothing & Accessories - Official Site - Macys.com","url":"http://m.qa19codemacys.fds.com/","isKey":true}]}
[debug] [iOS] Checking if page needs to load
[debug] [iOS] Page load needed. Loading.
[debug] [RemoteDebugger] Page loaded, verifying whether ready
[debug] [RemoteDebugger] Received applicationSentData response
[debug] [RemoteDebugger] Received applicationSentData response
[debug] [RemoteDebugger] Frame navigated, unloading page
(node:65282) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1037): TypeError: this.specialHandlers.Page.frameNavigated is not a function
[debug] [RemoteDebugger] Checking document readyState
[debug] [RemoteDebugger] Sending javascript command (function (){ return document.readyState; })()
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to remote debugger
[debug] [RemoteDebugger] Received applicationSentData response
[debug] [RemoteDebugger] Receiving data from remote debugger: '{"__argument":{"WIRApplicationIdentifierKey":"PID:67242","WIRListingKey":{"1":{"WIRTitleKey":"","WIRTypeKey":"WIRTypeWeb","WIRURLKey":"http://m.qa19codemacys.fds.com/","WIRPageIdentifierKey":1,"WIRConnectionIdentifierKey":"446aa350-66a8-4b3c-8ecc-7c9a91b87799"}}},"__selector":"_rpc_applicationSentListing:"}'
[debug] [RemoteDebugger] Page changed: {"1":{"WIRTitleKey":"","WIRTypeKey":"WIRTypeWeb","WIRURLKey":"http://m.qa19codemacys.fds.com/","WIRPageIdentifierKey":1,"WIRConnectionIdentifierKey":"446aa350-66a8-4b3c-8ecc-7c9a91b87799"}}
[debug] [iOS] Remote debugger notified us of a new page listing: {"appIdKey":"67242","pageArray":[{"id":1,"title":"","url":"http://m.qa19codemacys.fds.com/","isKey":true}]}
[debug] [iOS] Checking if page needs to load
[debug] [iOS] Page load needed. Loading.
[debug] [RemoteDebugger] Page loaded, verifying whether ready
```

**Comment by imurchie** [comment]
Again, getting the latest (`npm uninstall -g appium && npm install -g appium@beta`) will mitigate these errors.

**Comment by JESii** [comment]
OK; tried that and get a similar but slightly different error from cucumber; and here's the log file, still with xcodeShowLog setting: https://gist.github.com/JESii/8884c6ead65f4cc0414751bdef13bbc4
```
   And I visit a registry "Home" page via "GNav"                 # features/step_definitions/mobile_website/registry_migration/registry_brand_index_steps.rb:20
      An unknown server-side error occurred while processing the command. Original error: Error while executing atom: Element {:id=>"mb-j-nav-button"} does not exist in cache (status: 10) (Selenium::WebDriver::Error::UnknownError)
      ./lib/utils/extensions/selenium/remote/bridge.rb:44:in `rescue in execute'
      ./lib/utils/extensions/selenium/remote/bridge.rb:32:in `execute'
      ./lib/utils/extensions/selenium/common/element.rb:24:in `click'
      ./lib/utils/extensions/page-object/elements/element.rb:20:in `click'
      ./lib/utils/extensions/page-object/platforms/selenium_webdriver/surrogate_selenium_element.rb:9:in `method_missing'
      ./lib/utils/extensions/page-object/elements/element.rb:20:in `click'
      ./lib/mobile_website/panels/Header/main_left_nav_panel.rb:103:in `open_global_nav'
      ./features/step_definitions/mobile_website/header_and_footer_panels/global_navigation/global_navigation_action_steps.rb:98:in `/^I navigate to Registry page from global menu$/'
      ./features/step_definitions/mobile_website/registry_migration/registry_brand_index_steps.rb:28:in `/^I visit a registry "(.*?)" page via "(.*?)"$/'
      features/website/Selection/MEW/registry/MCOM/registry_navigation.feature:16:in `And I visit a registry "Home" page via "GNav"'
```

**Comment by JESii** [comment]
Investigating possible error in our test environments; will check back once I've reviewed this.

**Comment by JESii** [comment]
OK; the looping on the home page was a bug in our test environments; I've resolved that and run another test of the IphoneSimulator...

Logs are here: https://gist.github.com/JESii/7e93ffea7bfb1db2465f6013207472ad

Cucumber command:
`bundle exec cucumber   DEVICE=IphoneSimulator -p mobile_website_default     SITE=MCOM URL=http://XXX.com/  features/website/Selection/MEW/registry/MCOM/registry_navigation.feature:14`

appium server command:
`appium -g ~/appium_server.log --default-capabilities '{"showXcodeLog": "true", "automationName": "XCUITest"}'`

Home page loads successfully, but the first real automation step accessing the "Registry Home" page which exercises the functionality fails with:
```
   And I visit a registry "Home" page via "GNav"                 # features/step_definitions/mobile_website/registry_migration/registry_brand_index_steps.rb:20
      Element {:css=>"#m-j-access-reg"} was not present in 20 seconds (Selenium::WebDriver::Error::TimeOutError)
      ./lib/utils/extensions/page-object/platforms/selenium_webdriver/element.rb:11:in `when_present'
      ./lib/utils/extensions/page-object/accessors.rb:39:in `block in expected_element'
      ./lib/mobile_website/pages/registry_home_page.rb:23:in `initialize_page'
      ./lib/utils/extensions/page-object/page_object.rb:47:in `block in initialize'
      ./lib/utils/extensions/page-object/page_object.rb:61:in `call'
      ./lib/utils/extensions/page-object/page_object.rb:61:in `block in perform_benchmark'
      ./lib/utils/extensions/page-object/page_object.rb:61:in `perform_benchmark'
      ./lib/utils/extensions/page-object/page_object.rb:39:in `initialize'
      ./features/step_definitions/mobile_website/registry_migration/registry_brand_index_steps.rb:29:in `/^I visit a registry "(.*?)" page via "(.*?)"$/'
      features/website/Selection/MEW/registry/MCOM/registry_navigation.feature:16:in `And I visit a registry "Home" page via "GNav"'
```

**Comment by JESii** [comment]
OK; Did some more testing. I have a cucumber test that works perfectly when running on Chrome.  However, when running on the Simulator, it fails when attempting to open our global navigation menu and move to another page.

I've gone in while the simulator is running and tested some of the commands we issue to operate our global nav and they do not work at all when in the simulator. For example, our global Nav element is: `global_nav_button`. We are using Selenium. and sometimes the page items are referened with `_element` appended to the name.

In the simulator, the commands:
`@current_page.global_nav_button` returns an empty string, as expected
`@current_page.global_nav_button_element.visible?` returns true, as expected

However, the commands:
`@current_page.global_nav_button_element.click` does not open the global Nav
`@current_page.menu_if_needed` does not open the menu as expected

Is there a capability setting I'm missing?

**Comment by JESii** [comment]
OK; figured it out: I had to set a number of options on the appium command-line, otherwise taps and cssSelectors won't work and tests fail because expected things just don't work. here's the final command line that works for me for iOS Simulator testing:

`appium -g ~/appium_server.log --log-timestamp --local-timezone --debug-log-spacing --tmp ~/tmp --default-capabilities '{"showXcodeLog": "true", "automationName": "XCUITest", "cssSelectorsEnabled": "true”, “nativeEvents”: “true”, “nativeWebTap”: “true”}’`
