### ISSUE TITLE
appium does not return response after switching to webview by executing driver.context()

### ISSUE THREAD

**Issue by zhuchuji** [appium/appium#7816]
## The problem
I use appium for android automation. When I switch to webview, the below error occur:
[Chromedriver] Chromedriver exited unexpectedly with code null, signal SIGTERM
[Chromedriver] Error: Could not proxy command to remote server. Original error: 401 - <HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD>

## Environment
os: mac OS X EI Capitan 10.11.6
appium: 1.5.3
android sdk: 4.4.2
node: v6.8.0
mobile platform: android(emulator)

## Appium logs
```
[Appium] Welcome to Appium v1.5.3
[Appium] Non-default server args:
[Appium]   address: '127.0.0.1'
[Appium]   port: 13284
[Appium]   sessionOverride: true
[Appium]   loglevel: 'info'
[Appium] Appium REST http interface listener started on 127.0.0.1:13284
[HTTP] --> GET /wd/hub/status {}
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 16 ms - 83 
[HTTP] --> GET /wd/hub/status {}
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 10 ms - 83 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"debug.apk","noReset":true,"newCommandTimeout":300,"platformVersion":"4.4.2","platformName":"Android","deviceName":"emulator-5554"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"...
[Appium] Creating new AndroidDriver session
[Appium] Capabilities:
[Appium]   app: 'debug.apk'
[Appium]   noReset: true
[Appium]   newCommandTimeout: 300
[Appium]   platformVersion: '4.4.2'
[Appium]   platformName: 'Android'
[Appium]   deviceName: 'emulator-5554'
[BaseDriver] Session created with session id: 0cd6d5c1-2994-46b5-b905-957c4b46ddfb
[AndroidDriver] Java version is: 1.8.0_91
[ADB] Checking whether adb is present
[ADB] Using adb from /usr/local/Cellar/android-sdk/24.4.1_1/platform-tools/adb
[AndroidDriver] Retrieving device list
[AndroidDriver] Looking for a device with Android 4.4.2
[ADB] Getting device platform version
[AndroidDriver] Using device: emulator-5554
[ADB] Checking whether adb is present
[ADB] Using adb from /usr/local/Cellar/android-sdk/24.4.1_1/platform-tools/adb
[BaseDriver] Using local app 'debug.apk'
[AndroidDriver] Starting Android session
[ADB] Getting device platform version
[AndroidDriver] Screen already unlocked, doing nothing
[ADB] Checking whether aapt is present
[ADB] Using aapt from /usr/local/Cellar/android-sdk/24.4.1_1/build-tools/23.0.2/aapt
[ADB] Extracting package and launch activity from manifest
[AndroidDriver] Remote apk path is /data/local/tmp/8af9260a2c536c75dbe0cc9f72edd6dd.apk
[ADB] No uiautomator process found to kill, continuing...
[AndroidBootstrap] Android bootstrap socket is now connected
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] json loading complete.
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Registered crash watchers.
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Client connected
[Appium] New AndroidDriver session created successfully, session 0cd6d5c1-2994-46b5-b905-957c4b46ddfb added to master session list
[MJSONWP] Responding to client with driver.createSession() result: {"platform":"LINUX","webSto...
[HTTP] <-- POST /wd/hub/session 200 3569 ms - 1016 
[HTTP] --> POST /wd/hub/session/0cd6d5c1-2994-46b5-b905-957c4b46ddfb/element {"using":"xpath","value":"//*[@text='Mobile CI']"}
[MJSONWP] Calling AppiumDriver.findElement() with args: ["xpath","//*[@text='Mobile...
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//*[@text='Mobile CI']","context":"","multiple":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding '//*[@text='Mobile CI']' using 'XPATH' with the contextId: '' multiple: false
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[CLASS=android.widget.TextView, INSTANCE=1]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"value":{"ELEMENT":"1"},"status":0}
[MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"1"}
[HTTP] <-- POST /wd/hub/session/0cd6d5c1-2994-46b5-b905-957c4b46ddfb/element 200 79 ms - 87 
[HTTP] --> POST /wd/hub/session/0cd6d5c1-2994-46b5-b905-957c4b46ddfb/element/1/click {"id":"1"}
[MJSONWP] Calling AppiumDriver.click() with args: ["1","0cd6d5c1-2994-46b5-b9...
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:click","params":{"elementId":"1"}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: click
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"value":true,"status":0}
[MJSONWP] Responding to client with driver.click() result: true
[HTTP] <-- POST /wd/hub/session/0cd6d5c1-2994-46b5-b905-957c4b46ddfb/element/1/click 200 1123 ms - 76 
[HTTP] --> GET /wd/hub/session/0cd6d5c1-2994-46b5-b905-957c4b46ddfb/contexts {}
[MJSONWP] Calling AppiumDriver.getContexts() with args: ["0cd6d5c1-2994-46b5-b905-9...
[MJSONWP] Responding to client with driver.getContexts() result: ["NATIVE_APP","WEBVIEW_hk.c...
[HTTP] <-- GET /wd/hub/session/0cd6d5c1-2994-46b5-b905-957c4b46ddfb/contexts 200 73 ms - 142 
NATIVE_APP
WEBVIEW_hk.com.hsbc.enterprise.hsbcmobilebanking.test
[HTTP] --> POST /wd/hub/session/0cd6d5c1-2994-46b5-b905-957c4b46ddfb/context {"name":"WEBVIEW_hk.com.hsbc.enterprise.hsbcmobilebanking.test"}
[MJSONWP] Calling AppiumDriver.setContext() with args: ["WEBVIEW_hk.com.hsbc.enter...
[Chromedriver] Set chromedriver binary as: /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver
[Chromedriver] Killing any old chromedrivers, running: pkill -15 -f "/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver.*--port=9515"
[Chromedriver] No old chromedrivers seemed to exist
[Chromedriver] Spawning chromedriver with: /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver --url-base=wd/hub --port=9515 --adb-port=5037
[Chromedriver] [STDOUT] Starting ChromeDriver 2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4) on port 9515
Only local connections are allowed.
[JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9515/wd/hub/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9515/wd/hub/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9515/wd/hub/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9515/wd/hub/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9515/wd/hub/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9515/wd/hub/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9515/wd/hub/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9515/wd/hub/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9515/wd/hub/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9515/wd/hub/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9515/wd/hub/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9515/wd/hub/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9515/wd/hub/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9515/wd/hub/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9515/wd/hub/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9515/wd/hub/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9515/wd/hub/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9515/wd/hub/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9515/wd/hub/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9515/wd/hub/status] with no body
[Chromedriver] Chromedriver exited unexpectedly with code null, signal SIGTERM
[Chromedriver] Error: Could not proxy command to remote server. Original error: 401 - <HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD>
<BODY>
<FONT face="Helvetica">
<big><strong></strong></big><BR>
</FONT>
<blockquote>
<TABLE border=0 cellPadding=1 width="80%">
<TR><TD>

</TD></TR>
<TR><TD>
<FONT face="Helvetica">
Your credentials could not be authenticated: "Creden[HTTP] <-- tials arePOST / mwd/huissing.". You will not be pb/session/0cd6d5cermitted acce1-2994-46b5-bss905-957c unt4b46dil your credentialsdfb/context 500 4867 can be verified m.
</FONT>
</Ts - 1302 
D></TR>
<TR><TD>
<FONT face="Helvetica">
This is typically caused by an incorrect username and/or password, but could also be caused by network problems.
</FONT>
</TD></TR>
<TR><TD>

</Table>

<TABLE border=0 cellPadding=1 width="80%">
<TR><TD>
<FONT face="Helvetica" SIZE=2>
<BR>

</FONT>
</TD></TR>
</TABLE>
</blockquote>
</FONT>
</BODY></HTML>

    at JWProxy.proxy$ (lib/jsonwp-proxy/proxy.js:115:13)
    at tryCatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
```

## Code To Reproduce Issue [ Good To Have ]
Aftering debugging, I found the code get stuck in the line this.driver.context(contextName) as below:
```java
        Set<String> contextNames = this.driver.getContextHandles();
        for (String contextName : contextNames) {
            if (contextName.contains("WEBVIEW")) {
                this.driver.context(contextName);
                switchresult = true;
                break;
            }
        }
```

The console shows a request has been sent to appium, but no responses return until timeout. Below is the final output in console, after which there are not any responses from appium.
```
[HTTP] --> GET /wd/hub/session/c59b462d-1c68-40a7-b3a4-a15d3f21740f/contexts {}
[MJSONWP] Calling AppiumDriver.getContexts() with args: ["c59b462d-1c68-40a7-b3a4-a...
[MJSONWP] Responding to client with driver.getContexts() result: ["NATIVE_APP","WEBVIEW_hk.c...
[HTTP] <-- GET /wd/hub/session/c59b462d-1c68-40a7-b3a4-a15d3f21740f/contexts 200 149 ms - 142 
[HTTP] --> POST /wd/hub/session/c59b462d-1c68-40a7-b3a4-a15d3f21740f/context {"name":"WEBVIEW_hk.com.hsbc.enterprise.hsbcmobilebanking.test"}
[MJSONWP] Calling AppiumDriver.setContext() with args: ["WEBVIEW_hk.com.hsbc.enter...
[Chromedriver] Set chromedriver binary as: /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver
[Chromedriver] Killing any old chromedrivers, running: pkill -15 -f "/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver.*--port=9515"
[Chromedriver] Successfully cleaned up old chromedrivers
[Chromedriver] Spawning chromedriver with: /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver --url-base=wd/hub --port=9515 --adb-port=5037
[Chromedriver] [STDOUT] Starting ChromeDriver 2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4) on port 9515
Only local connections are allowed.
[JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9515/wd/hub/status] with no body
[JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"\",\"stat...
[JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"ch...
```

**Comment by mykola-mokhnach** [comment]
Do you get the same result with Appium 1.6.3?

**Comment by zhuchuji** [comment]
@mykola-mokhnach I just tried Appium 1.6.3. It also get stuck in the same line: driver.context().
But this time console log end at chromedriver starting

**Comment by mykola-mokhnach** [comment]
it might be the page is protected with authorisation, so you need to provide your credentials in the URL to log in. Check http://stackoverflow.com/questions/18264601/how-to-send-a-correct-authorization-header-for-basic-authentication/18264755#18264755

**Comment by zhuchuji** [comment]
Yes I am behind a proxy, but why chromedriver use the internet? The log shows that chromedriver starts on 127.0.0.1:9515, but it fails to proxy to the server. Chromedriver get the web resources from my hybrid app(app for test), so it doesn't need to connect to internet(I don't know why chromedriver have to connect to internet and get authenticated, also no idea of why it proxy to which remote server). And you know chromedriver is started and controlled by appium, I could not sent instructions to it except DesiredCapabilities. But I did not find any arguments for chromedriver proxy.

**Comment by mykola-mokhnach** [comment]
http://stackoverflow.com/questions/19225507/how-to-set-proxy-setting-for-chrome-in-selenium-java

Try to use it together with **chromeOptions** capability

**Comment by zhuchuji** [comment]
@mykola-mokhnach I come across the same problem on windows platform. But I solved it by downgrade chromedriver from version 2.21 to 2.14. I will try out the solution if I get the mac machine. But I still do not know why. Thank you for your answers all the same.

**Comment by zhuchuji** [comment]
@mykola-mokhnach I suppose it is because the chromedriver 2.21 doesn't support webview(chrome kernal 30.0.0) in android 4.4.2(api 19). From chromedriver release notes chromedriver 2.21 supports chrome v46-50. But it's wired that chromedriver 2.14 works fine. It supports chrome v39-42, but webview in android 4.4.2 is v30.0.0

**Comment by mykola-mokhnach** [comment]
yup, Google deliberately deprecates support of older browser versions in new chromedriver releases. This is the expected behaviour.

**Comment by zhuchuji** [comment]
Test on mac. Downgrading chromedriver to version 2.14.31 is ok.
