### ISSUE TITLE
iOS: Simulator: fullReset = True: non informative errors while starting driver

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium#7856]
## The problem

with latest appium (--noshrinkwrap) version i see non informative error on driver start. may we remove it?

Feb 13, 2017 3:36:17 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
[simctl] Error: simctl error running 'get_app_container': An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
The operation couldn’t be completed. No such file or directory
No such file or directory
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at simCommand$ (../../lib/simctl.js:26:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: simctl error running 'get_app_container': An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
The operation couldn’t be completed. No such file or directory
No such file or directory
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at simCommand$ (../../lib/simctl.js:26:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
(node:33572) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: simctl error running 'get_app_container': An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
The operation couldn’t be completed. No such file or directory
No such file or directory
(node:33572) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Feb 13, 2017 3:37:00 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS

**Comment by mykola-mokhnach** [comment]
This is known. We need to apply some changes to node-simctl module to avoid printing such confusing errors when they are expected. Right @imurchie

**Comment by imurchie** [comment]
Correct. This should be fixed soon.
