### ISSUE TITLE
findElement using coordinates (Horizontal position) is no longer working in appium 1.6.4

### ISSUE THREAD

**Issue by vjmaiky** [appium/appium#7858]
## The problem

Method to search folders via horizontal position (coordinates) is no longer working

## Environment

* Appium version 1.6.4
* Last Appium version that did not exhibit the issue 1.6.3
* Desktop OS/version used to run Appium: max os X el capitan 10.11.6
* Node.js version v7.4.0
* Mobile platform/version under test: ios10.2.1
* Real device or emulator/simulator: iphone 6+

## Details

I have following method to search a folder inside of my app and to click on it. Application/setup crashes when i execute it. Problem appeared after updating to appium 1.6.4

Crash on console:
2017-02-13 17:13:42 INFO  WebElementHelpers:1556 - Attempt 2 of 10 failed. Unexpected exception.
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Unhandled endpoint: /session/A70D300E-5744-4D76-829F-54C9575D7F15/wda/element/0/dragfromtoforduration -- http://localhost:8100/ with parameters {
    wildcards =     (
        "session/A70D300E-5744-4D76-829F-54C9575D7F15/wda/element/0/dragfromtoforduration"
    );
} (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 18 milliseconds
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'admins-Mac-mini.local', ip: '172.16.101.165', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_91'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{app=/Users/Shared/Appium/TelekomMail-VTU-Universal.ipa, rotatable=true, networkConnectionEnabled=false, databaseEnabled=false, deviceName=iPhone 6 (10.0.2) [90fbc0d9d9e4792dc70b2e40dcdb2afd91655bfd], fullReset=true, platform=MAC, appium-version=1.6.4, newCommandTimeout=600, realDeviceLogger=/usr/local/lib/node_modules/deviceconsole/deviceconsole, platformVersion=10.2.1, webStorageEnabled=false, locationContextEnabled=false, automationName=XCUITest, browserName=, takesScreenshot=true, waitForAppScript=$.delay(1000); $.acceptAlert();, javascriptEnabled=true, platformName=iOS, udid=2ccf30dd21fa31a77967a66580e6c7ee62ecce88}]
Session ID: 85928e55-e246-42b7-a812-082dc24f78cb
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:43)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at io.appium.java_client.AppiumDriver.performTouchAction(AppiumDriver.java:316)
	at io.appium.java_client.TouchAction.perform(TouchAction.java:318)
	at io.appium.java_client.AppiumDriver.swipe(AppiumDriver.java:365)
	at dt.emma.ios.utils.Swipe.swipeInAppiumDriver(Swipe.java:457)
	at dt.emma.ios.utils.Swipe.up(Swipe.java:301)
	at dt.emma.ios.utils.WebElementHelpers.findElement(WebElementHelpers.java:1511)
	at dt.emma.ios.views.FolderView.find_Folder(FolderView.java:184)
	at dt.emma.ios.phone.TestSet_03_EMail_Read.multipleRecipient(TestSet_03_EMail_Read.java:1476)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at dt.emma.ios.utils.IosAutomationTestWatcher.evaluateTest(IosAutomationTestWatcher.java:146)
	at dt.emma.ios.utils.IosAutomationTestWatcher.iosevaluate(IosAutomationTestWatcher.java:83)
	at dt.emma.ios.utils.IosAutomationTestWatcher.access$3(IosAutomationTestWatcher.java:80)
	at dt.emma.ios.utils.IosAutomationTestWatcher$1.evaluate(IosAutomationTestWatcher.java:63)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

## Link to Appium logs
Appium log:
https://gist.github.com/vjmaiky/a68f5f719946e16b13bc333c3e8d8a03

## Code To Reproduce Issue [ Good To Have ]
	public static void find_Folder(String folderName, Direction direction) {
		// waitForFoldersToLoad(60);
		switch (direction) {
		case DOWN:
			WebElementHelpers.findElement(By.id(folderName), direction, folderName, HorizontalPosition.LEFT, 10, 0.5,
					0.0);
			break;
		case UP:
			WebElementHelpers.findElement(By.id(folderName), direction, folderName, HorizontalPosition.LEFT, 10, 0.5,
					1.0);
			break;
		}
	}

public static void click_Folder(String folderName) {
		click(folderName, Attribute.NAME, true, HorizontalPosition.CENTER, VerticalPosition.CENTER, true);
	}

**Comment by mykola-mokhnach** [comment]
Yes, WDA has updated several endpoints and these need to be updated in Appium as well.

**Comment by mykola-mokhnach** [comment]
@imurchie FYI

**Comment by mykola-mokhnach** [comment]
Please install the recent Appium 1.6.4-beta containing appium-xcuitest-driver v. 2.10.0 or higher and try to reproduce the issue

**Comment by vjmaiky** [comment]
@mykola-mokhnach i updated all to latest version and it works. Thank you. Can be closed.
