### ISSUE TITLE
Can't not run the sample code?

### ISSUE THREAD

**Issue by liangjinwen** [appium/appium#7865]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:mac 10.12.1
* Node.js version (unless using Appium.app|exe):v6.9.5
* Mobile platform/version under test:IOS 10.0
* Real device or emulator/simulator:simulator
* Appium CLI or Appium.app|exe:Appium CLI

## Details
I try to connect the real machine is very simulator, run python ios_simple.py, it suggested the following error message, you have encountered? How can I handle it to run, thank you
If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]
log:
python ios_simple.py
test_scroll (__main__.SimpleIOSTests) ... ERROR
test_ui_computation (__main__.SimpleIOSTests) ... ERROR

======================================================================
ERROR: test_scroll (__main__.SimpleIOSTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "ios_simple.py", line 24, in setUp
    'deviceName':'iPhone Simulator'
  File "build/bdist.macosx-10.6-intel/egg/appium/webdriver/webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium-3.0.2-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 92, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium-3.0.2-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 179, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium-3.0.2-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium-3.0.2-py2.7.egg/selenium/webdriver/remote/errorhandler.py", line 163, in check_response
    raise exception_class(value)
WebDriverException: Message: Unhandled endpoint: /wd/hub//session -- http://localhost:8100/ with parameters {
    wildcards =     (
        "wd/hub//session"
    );
}

======================================================================
ERROR: test_ui_computation (__main__.SimpleIOSTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "ios_simple.py", line 24, in setUp
    'deviceName':'iPhone Simulator'
  File "build/bdist.macosx-10.6-intel/egg/appium/webdriver/webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium-3.0.2-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 92, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium-3.0.2-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 179, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium-3.0.2-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium-3.0.2-py2.7.egg/selenium/webdriver/remote/errorhandler.py", line 163, in check_response
    raise exception_class(value)
WebDriverException: Message: Unhandled endpoint: /wd/hub//session -- http://localhost/:8100/ with parameters {
    wildcards =     (
        "wd/hub//session"
    );
}
Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
This information is not enough to help. Please fill out the default issue reporting template and reopen the issue.
