### ISSUE TITLE
[Appium 1.6.4(beta)] : Tap events issue on iOS Real Device testing

### ISSUE THREAD

**Issue by JESii** [appium/appium#7869]
## The problem

I am running ruby/cucumber tests against a mobile web page (not an app). The test hits the device (iPad 9.3.5) and opens the requested home page and opens our Global Navigation menu. 

However, it never proceeds to the requested page from the menu and times out when the requested element on the new page is not found.

The test runs successfully on my local machine as well as on the iOS Simulator.

## Environment

* Appium version (or git revision) that exhibits the issue:
1.6.4(beta)
* Last Appium version that did not exhibit the issue (if applicable):
N/A - Only have iOS simulator running
* Desktop OS/version used to run Appium:
OS X El Cap; 10.11.6
* Node.js version (unless using Appium.app|exe):
7.5.0
* Mobile platform/version under test:
iOS 9.3
* Real device or emulator/simulator:
Real device
* Appium CLI or Appium.app|exe:
appium CLI
* Xcode version:
8.2.1

#### Additional environment details

* appium-ios-driver@1.16.0 (installed with -g option)
* appium-xcuitest-driver@2.7.0 (installed with -g option)
* authorize-ios@1.0.4 (installed with -g option)
* ios-deploy@1.9.1 (installed with -g option)
* ios_webkit_debug_proxy@ 1.7.1, Built with libimobiledevice v1.2.0, libplist v1.12
* libimobiledevice: stable 1.2.0 (bottled), HEAD
* ideviceinstaller: stable 1.1.0 (bottled), HEAD
* .xcconfig created with:
`DEVELOPMENT_TEAM = XXXXXXXXXX`
`CODE_SIGN_IDENTITY = iPhone Developer`
`IOS_INSTALL_PAUSE = 8000`
* iPad Apps installed during the test process
    `WebDriverAgentRunner version 1, com.apple.test.WebDriverAgentRunner-Runner`
    `IntegrationApp version 1, com.facebook.IntegrationApp`

#### Symptoms

1) The test begins running, the WebDriverAgent is built and loaded, and I can see the device / Safari reacting: Starting from Safari, the device slides Safari out of the way, displays a completely black screen, then goes to the home screen, then back to Safari.

2) After a short pause, the device displays http://appium.io page on Safari [Side Note: why is that?]
and the Global Navigation menu opens

3) At this point, the test taps one of the menu items and we should be redirected to the next page

4) However, what happens is that the menu is closed, and the home page just sits there - no transition to the requested page.

5) Cucumber/Selenium emit the following error message:
```
Element {:css=>"#m-j-access-reg"} was not present in 20 seconds (Selenium::WebDriver::Error::TimeOutError)
      ./lib/utils/extensions/page-object/platforms/selenium_webdriver/element.rb:11:in `when_present'
      ./lib/utils/extensions/page-object/accessors.rb:39:in `block in expected_element'
      ./lib/mobile_website/pages/registry_home_page.rb:23:in `initialize_page'
      ./lib/utils/extensions/page-object/page_object.rb:47:in `block in initialize'
      ./lib/utils/extensions/page-object/page_object.rb:61:in `call'
      ./lib/utils/extensions/page-object/page_object.rb:61:in `block in perform_benchmark'
      ./lib/utils/extensions/page-object/page_object.rb:61:in `perform_benchmark'
      ./lib/utils/extensions/page-object/page_object.rb:39:in `initialize'
      ./features/step_definitions/mobile_website/registry_migration/registry_brand_index_steps.rb:29:in `/^I visit a registry "(.*?)" page via "(.*?)"$/'
      features/website/Selection/MEW/registry/MCOM/registry_navigation.feature:16:in `And I visit a registry "Home" page via "GNav"'
```

##### Appium server
`appium -g ~/appium_server.log --log-timestamp --local-timezone --debug-log-spacing --tmp ~/tmp --default-capabilities '{"showXcodeLog": true, "automationName": "XCUITest", "cssSelectorsEnabled": true, "nativeWebTap": true, "nativeEvents": true, "autoWebView": true}'`

##### ios_webkit_debug_proxy
`ios_webkit_debug_proxy -c xxxUDIDxxx:27753 -d running in another terminal window and connected to my device ("JON's iPad")`

##### Cucumber test
`bundle exec cucumber DEVICE=Iphone -p mobile_website_default SITE=MCOM URL=http://m.qa17codemacys.fds.com/ features/website/Selection/MEW/registry/MCOM/registry_navigation.feature:14`

## Link to Appium logs

https://gist.github.com/JESii/1bfdfdea3f5378c7942415075b091813

## Code To Reproduce Issue [ Good To Have ]

Mobile web, not App

**Comment by JESii** [comment]
Hi, there.. any suggestions on this issue?

**Comment by JESii** [comment]
Found/fixed the problem. Part of the framework provides support for  global navigation requests and they handle it like this:
#### HTML
`<li id="NAV-NAME" ...>`
 ` <a href="LINK-URL" ...>LINK-NAME</a>`
`</li>`
#### Navigation Test Code, where `current_nav_elements` are the li elements from above:
`nav_item = current_nav_elements.find { |el| el.text == LINK-NAME }`
`nav_item.click`

To get this to work, I changed `nav_item.click` to `nav_item.link_element.click`

We are currently running:
`selenium-client (1.2.18)`
`selenium-webdriver (2.53.4)`
which I'm guessing is part of the problem; selenium-webdriver is currently at 3.2.0 :=(
