### ISSUE TITLE
  URLError: <urlopen error [Errno 61] Connection refused> 

### ISSUE THREAD

**Issue by AllocAndInit** [appium/appium#7885]
## The problem
test_open (__main__.SimpleIOSTests) ... ERROR

======================================================================
ERROR: test_open (__main__.SimpleIOSTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/h/Desktop/testresult/testscript/script/ios_simple0.py", line 26, in setUp
    'noReset': True
  File "build/bdist.macosx-10.11-intel/egg/appium/webdriver/webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "/Library/Python/2.7/site-packages/selenium-3.0.1-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 92, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/Library/Python/2.7/site-packages/selenium-3.0.1-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 179, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/Library/Python/2.7/site-packages/selenium-3.0.1-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 234, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/Library/Python/2.7/site-packages/selenium-3.0.1-py2.7.egg/selenium/webdriver/remote/remote_connection.py", line 407, in execute
    return self._request(command_info[0], url, body=data)
  File "/Library/Python/2.7/site-packages/selenium-3.0.1-py2.7.egg/selenium/webdriver/remote/remote_connection.py", line 477, in _request
    resp = opener.open(request, timeout=self._timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 61] Connection refused>

----------------------------------------------------------------------

## Environment
appium -v : 1.6.3

node -v : v7.0.0

platform : ios 7 ,ios 8

## Details

when I run test on ios 7 and ios 8 ,  this problem happend ,but not always like this, it happens sometime, who can tell me what's wrong ?

thank you  very much

**Comment by mykola-mokhnach** [comment]
Please attach Appium server log and the part of code where capabilities are set
