### ISSUE TITLE
Not able to install iOS app on real device with Appium 1.6.3

### ISSUE THREAD

**Issue by llfyr** [appium/appium#7898]
Encountered internal error running command: Error: Command 'idevice_id -l' errored out: Error: spawn idevice_id ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at ChildProcess.<anonymous> (../../lib/teen_process.js:32:14)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Appium version: 1.6.3
Mac OS version: 10.12.2
Node.js version: 7.2.1
iOS Device version: 10.0.2
Xcode 8.2.1

I was able to run the same test classes earlier with same Appium version but now im not able to do it. Capabilities etc. are all set. I also updated brew and ideviceinstaller but nothing worked.

thank you in advance

**Comment by mykola-mokhnach** [comment]
Make sure libimidiledevice is installed:

```
brew install libimobiledevice --HEAD
```

nit: [This](https://github.com/appium/appium-xcuitest-driver) tutorial helps to set up real device for Appium properly.

**Comment by llfyr** [comment]
Hi mykola,

when i try to run the script you wrote, i get this error. I couldnt find any related topics about this error.

checking consistency of all components of python development environment... no
configure: error: 
  Could not link test program to Python. Maybe the main Python library has been
  installed in some non-standard library path. If so, pass it to configure,
  via the LDFLAGS environment variable.
  Example: ./configure LDFLAGS="-L/usr/non-standard-path/python/lib"
  ============================================================================
   ERROR!
   You probably have to install the development version of the Python package
   for your distribution.  The exact name of this package varies among them.
  ============================================================================

**Comment by jlipps** [comment]
none of that is relevant to appium. and you can find details on installing packages through homebrew at https://brew.sh
