### ISSUE TITLE
iOS app execution with appium crashes occassional but maximum number of times

### ISSUE THREAD

**Issue by surikiran** [appium/appium#7909]
## The problem
I am trying to execute an iOS app using appium. It gets crashed at a particular instance occasionally but not every time continuously where this happens maximum times only. For every 10 runs it gets crashes 9 times but 1 time no issue 

## Environment
Appium 1.5.3
Max OS X 10.11.6
iphone 5s(8.2) and iPad 6 Plus(8.3)

## Details
I have an iOS app in which after navigating through different screens and navigating back to main screen by pressing a button in one of the module the app gets crashed while navigating to the main screen. This doesn't happen continuously. When I execute for an instance of 10 times. It gets crashed 9 times but for 1 time it doesn't crashes. After going through forums and checking my code I found the NSLog generation of the app is not reason as it has been disabled by my developer. Besides I am using XPath for clicking the button in the module and again click a link the main screen. When I click the same link first time in the main screen there is no crash but when I click the same screen after navigating to a module and then clicking a button for navigating back to main screen this crash generates. When checked the crash log by my developer they say there is no issue in their app besides when done the same activity manually there is no crash. I tried to keep wait,sleep,implicit,explicit waits,etc....but never changed the result. Consistently the app gets crashed with no root cause found till date despite of doing lots and lots of changes. Hence someone please provide a solution as it completely stopped my task 

## Link to Appium logs

[Appium] Closing session, cause was 'An unknown server-side error occurred while processing the command. Original error: Abnormal Instruments termination!'
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Abnormal Instruments termination! (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 2.00 seconds
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:32:46'
System info: host: 'Product-QA-Macmini.local', ip: '172.17.12.180', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_45'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{app=/Users/TAGIT/Documents/TestData/workspace/6.3_Automation_iOS_ParallelExecution/APK/Mobeix6.3.ipa, networkConnectionEnabled=false, bundleid=com.tagitmobile.MobeixSixTwo, databaseEnabled=false, version=, deviceName==iPhone 6 Plus, platform=MAC, desired={app=/Users/TAGIT/Documents/TestData/workspace/6.3_Automation_iOS_ParallelExecution/APK/Mobeix6.3.ipa, platformVersion=8.3, bundleid=com.tagitmobile.MobeixSixTwo, browserName=iPhone, udid=8dbd1440fe66b39b034a891d206ff29f110b12b3, platformName=iOS, version=, deviceName==iPhone 6 Plus, platform=MAC}, platformVersion=8.3, webStorageEnabled=false, locationContextEnabled=false, browserName=iPhone, takesScreenshot=true, javascriptEnabled=true, udid=8dbd1440fe66b39b034a891d206ff29f110b12b3, platformName=iOS}]
Session ID: f838ffcd-3d5b-4836-b7cd-d53da3e49c98
*** Element info: {Using=-ios uiautomation, value=.scrollViews()[0].tableViews()[0].cells()[0].tableViews()[1].cells()[1]}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:40)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:363)
	at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:56)
	at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.findElement(IOSDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.findElementByIosUIAutomation(IOSDriver.java:207)
	at com.mobienxV6_3.automation.utils.WaitScenarios.waitByIOSAutomation(WaitScenarios.java:43)
	at com.mobienxV6_3.automation.usecases.UC6302_Mobile.UC6302ScreensNavigation(UC6302_Mobile.java:458)
	at com.mobienxV6_3.automation.usecases.UC6302_Mobile.UC6302Menu(UC6302_Mobile.java:404)
	at com.mobienxV6_3.automation.execution.iOSDeviceExecution.MainMenu(iOSDeviceExecution.java:199)
	at com.mobienxV6_3.automation.execution.iOSDeviceExecution.ExecutionMode(iOSDeviceExecution.java:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:216)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:143)
	at org.testng.TestRunner.beforeRun(TestRunner.java:631)
	at org.testng.TestRunner.run(TestRunner.java:599)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:402)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by jlipps** [comment]
Please retry using appium 1.6.4 and if the problem persists, link to a gist of your full appium logs.
