### ISSUE TITLE
Bad app: ../grid/app-bin/null. App paths need to be absolute, or relative to the appium server install dir, or a URL to compressed file, or a special app name.

### ISSUE THREAD

**Issue by vishwathma** [appium/appium#7923]
## The problem

com.***.pimobile.automation.driver.appium.ios.IOSAppiumDriver - Error occurred while initializing IOS driver. Error: An unknown server-side error occurred while processing the command. Original error: Bad app: ../grid/app-bin/null. App paths need to be absolute, or relative to the appium server install dir, or a URL to compressed file, or a special app name. (WARNING: The server did not provide any stacktrace information)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): 1.5.3
* Desktop OS/version used to run Appium: MAC EI Capitan
* Node.js version (unless using Appium.app|exe): 6.9.5
* Mobile platform/version under test: IOS
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Appium CLI
* Selenium Grid

## Details

Tests are failing intermittently with the error mentioned above. 
This is happening when we are running tests in parallel using Grid only and not when the tests are run individually. The same tests were running absolutely fine when they were run without using Grid with the new  version.
Fyi, our framework is designed so that the simulators are killed after every test is executed. But what is really happening is during one of the test execution, the simulator is not closing and when the next test gets triggered, the old simulator will still be showing up and then the above error is displayed.

We tried to kill the simulator by adding the below code in the tearDown() but this did not work either.
String kill[] = {"killall","iOS Simulator"};
Runtime.getRuntime().exec(kill);

## Link to Appium logs

[XCUITest] Error: Bad app: ../grid/app-bin/null. App paths need to be absolute, or relative to the appium server install dir, or a URL to compressed file, or a special app name.
    at XCUITestDriver.configureApp$ (../../lib/driver.js:397:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: Bad app: ../grid/app-bin/null. App paths need to be absolute, or relative to the appium server install dir, or a URL to compressed file, or a special app name.
    at XCUITestDriver.configureApp$ (../../lib/driver.js:397:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[debug] [XCUITest] Running iOS simulator reset flow
[debug] [XCUITest] Shutting down simulator
[debug] [iOSSim] Killing all iOS Simulators
[debug] [XCUITest] Full reset is on. Cleaning simulator
[debug] [iOSSim] Killing any simulator daemons for 27B739F4-CB2F-48CF-91D3-2DBBB77299C9
[iOSSim] Cleaning simulator 27B739F4-CB2F-48CF-91D3-2DBBB77299C9
[debug] [XCUITest] Resetting simulator
[MJSONWP] Encountered internal error running command: Error: Bad app: ../grid/app-bin/null. App paths need to be absolute, or relative to the appium server install dir, or a URL to compressed file, or a special app name.
    at XCUITestDriver.configureApp$ (../../lib/driver.js:397:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 1206 ms - 296 
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.3","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 8 ms - 83 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"../grid/app-bin/null","newCommandTimeout":360000,"platformVersion":"9.3","automationName":"XCUITest","platformName":"iOS","deviceName":"iPhone 6s","fullReset":true,"platform":"MAC"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"../grid/app-bin/null","newCommandTimeout":360000,"platformVersion":"9.3","automationName":"XCUITest","platformName":"iOS","deviceName":"iPhone 6s","fullReset":true,"platform":"MAC"},null,null,null,null,null,null]
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   app: '../grid/app-bin/null'
[Appium]   newCommandTimeout: 360000
[Appium]   platformVersion: '9.3'
[Appium]   automationName: 'XCUITest'
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'iPhone 6s'
[Appium]   fullReset: true
[Appium]   platform: 'MAC'
[debug] [XCUITest] XCUITestDriver version: 2.4.2
[BaseDriver] The following capabilities were provided, but are not recognized by appium: platform.
[BaseDriver] Session created with session id: 1b43ac72-037a-4c38-b7bd-d43a9f5bd0ee
[debug] [XCUITest] Xcode version set to '8.2.1'
[debug] [XCUITest] iOS SDK Version set to '10.2'
[iOSSim] Constructing iOS simulator for Xcode version 8.2.1 with udid '27B739F4-CB2F-48CF-91D3-2DBBB77299C9'
[debug] [XCUITest] Full reset requested. Cleaning and stopping simulator
[debug] [iOSSim] Killing any simulator daemons for 27B739F4-CB2F-48CF-91D3-2DBBB77299C9
[iOSSim] Cleaning simulator 27B739F4-CB2F-48CF-91D3-2DBBB77299C9
[debug] [iOSSim] Killing all iOS Simulators
[XCUITest] Determining device to run tests on: udid: '27B739F4-CB2F-48CF-91D3-2DBBB77299C9', real device: false
[BaseDriver] Using local app '../grid/app-bin/null'
[XCUITest] Error: New app path ../grid/app-bin/null did not have extension .app
    at Object.configureApp$ (../../../lib/basedriver/helpers.js:53:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at Promise.F (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at Object.configureApp (../../../lib/basedriver/helpers.js:32:22)
    at XCUITestDriver.configureApp$ (../../lib/driver.js:394:42)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at Promise.F (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at XCUITestDriver.configureApp (../../lib/driver.js:364:34)
    at XCUITestDriver.start$ (../../lib/driver.js:208:18)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: New app path ../grid/app-bin/null did not have extension .app
    at Object.configureApp$ (../../../lib/basedriver/helpers.js:53:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at Promise.F (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at Object.configureApp (../../../lib/basedriver/helpers.js:32:22)
    at XCUITestDriver.configureApp$ (../../lib/driver.js:394:42)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at Promise.F (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at XCUITestDriver.configureApp (../../lib/driver.js:364:34)
    at XCUITestDriver.start$ (../../lib/driver.js:208:18)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[XCUITest] Error: Bad app: ../grid/app-bin/null. App paths need to be absolute, or relative to the appium server install dir, or a URL to compressed file, or a special app name.

[Appium Logs from the nodes](https://drive.google.com/file/d/0B8_69cxt8VqdMWNINHlDVDdTUUU/view?usp=sharing)

**Comment by mykola-mokhnach** [comment]
I think the error text is quite clear here: **app** capability should contain correct path to application package.

**Comment by vishwathma** [comment]
@mykola-mokhnach , Fyi, our framework is designed so that the simulators are killed after every test is executed. But what is really happening is during one of the test execution, the simulator is not closing and when the next test gets triggered, the old simulator will still be showing up and then the above error is displayed.

**Comment by vishwathma** [comment]
Can someone give a clue why it says 'Bad app: ../grid/app-bin/null. ' even though in that directory, the app is copied?

**Comment by vishwathma** [comment]
Even using the absolute App path, this error is thrown.

**Comment by vishwathma** [comment]
Even this piece of code, did not help either. 
String kill[] = {"killall","com.apple.CoreSimulator.CoreSimulatorService"};
I would appreciate if anyone can help me on this. Thanks

**Comment by vishwathma** [comment]
This is not working either: 
if(app.getDriver() != null){
			app.getDriver().quitDriver();
		}
			
		CommandLine command1 = new CommandLine("killall -9 'iOS Simulator'");
		//command1.addArgument("iOS Simulator");
		DefaultExecuteResultHandler resultHandler1 = new DefaultExecuteResultHandler();
		DefaultExecutor executor1 = new DefaultExecutor();
		executor1.setExitValue(1);
		executor1.execute(command1, resultHandler1);

[Appium Logs from the nodes](https://drive.google.com/file/d/0B8_69cxt8VqdMWNINHlDVDdTUUU/view?usp=sharing)

**Comment by jlipps** [comment]
Sorry @vishwathma please link to a gist of the log you want us to look at. And in any case, the `bad app` is a clear error. Something is wrong on your end if the app path isn't being passed in correctly.
