### ISSUE TITLE
Error installing .app file

### ISSUE THREAD

**Issue by kaladine** [appium/appium#7924]
I am setting up a appium server for the first time I have done a npm install of appium and have version 1.63

It is launching an emulator but crashes with the error seen below  Any suggestions would be appriciated

2017-02-23 15:50:07:775 - [Appium] Creating new XCUITestDriver session
2017-02-23 15:50:07:775 - [Appium] Capabilities:
2017-02-23 15:50:07:777 - [Appium]   platformName: 'iOS'
2017-02-23 15:50:07:777 - [Appium]   platformVersion: '10.2'
2017-02-23 15:50:07:778 - [Appium]   platform: 'Mac'
2017-02-23 15:50:07:778 - [Appium]   deviceName: 'iPad Air 2'
2017-02-23 15:50:07:779 - [Appium]   app: '/Users/dfreeman/RubymineProjects/choice360connectregression/features/support/build/IOS_BUILD/Build/Products/Debug-iphonesimulator/Choice360Connect.app'
2017-02-23 15:50:07:779 - [Appium]   automationName: 'xcuitest'
2017-02-23 15:50:07:786 - [BaseDriver] The following capabilities were provided, but are not recognized by appium: platform.
2017-02-23 15:50:07:788 - [BaseDriver] Session created with session id: 4e1b8d7c-2d37-4f97-acf6-516b10203c79
2017-02-23 15:50:07:988 - [iOSSim] Constructing iOS simulator for Xcode version 8.2.1 with udid '639F3560-19DB-405E-9D43-209794DFE3AF'
2017-02-23 15:50:07:989 - [XCUITest] Determining device to run tests on: udid: '639F3560-19DB-405E-9D43-209794DFE3AF', real device: false
2017-02-23 15:50:07:991 - [BaseDriver] Using local app '/Users/dfreeman/RubymineProjects/choice360connectregression/features/support/build/IOS_BUILD/Build/Products/Debug-iphonesimulator/Choice360Connect.app'
2017-02-23 15:50:08:083 - [XCUITest] Setting up simulator
2017-02-23 15:50:08:148 - [XCUITest] Simulator with udid '639F3560-19DB-405E-9D43-209794DFE3AF' not booted. Booting up now
2017-02-23 15:50:08:268 - [iOSSim] Starting simulator with command: open -Fn /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID 639F3560-19DB-405E-9D43-209794DFE3AF
2017-02-23 15:50:08:384 - [iOSSim] Simulator log at '/Users/dfreeman/Library/Logs/CoreSimulator/639F3560-19DB-405E-9D43-209794DFE3AF/system.log'
2017-02-23 15:50:08:385 - [iOSSim] Tailing simulator logs until we encounter the string "com.apple.springboard"
2017-02-23 15:50:08:386 - [iOSSim] We will time out after 60000ms
2017-02-23 15:51:07:745 - [HTTP] <-- POST /wd/hub/session - - ms - - 
2017-02-23 15:51:18:409 - [iOSSim] Simulator booted in 70139ms
2017-02-23 15:51:18:500 - [simctl] Error: simctl error running 'install': An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=163):
Unable to lookup in current state: Shutdown
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at simCommand$ (lib/simctl.js:22:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: simctl error running 'install': An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=163):
Unable to lookup in current state: Shutdown
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at simCommand$ (lib/simctl.js:22:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
2017-02-23 15:51:18:502 - [XCUITest] Error: simctl error running 'install': An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=163):
Unable to lookup in current state: Shutdown
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at simCommand$ (lib/simctl.js:22:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: simctl error running 'install': An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=163):
Unable to lookup in current state: Shutdown
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at simCommand$ (lib/simctl.js:22:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by mykola-mokhnach** [comment]
It looks like something is wrong with your simulator. Have you tried to install the app there manually?

**Comment by kaladine** [comment]
Yes it builds fine using command line xcode build prompts as well as in xcode itself I should mention I'm using xcode version 8.1

**Comment by kaladine** [comment]
I did look at the platform build error that could be causing the issue and got this any advice?

ldu1app3876:appium-xcuitest-driver dfreeman$ Scripts/boostrap.sh -d
-bash: Scripts/boostrap.sh: No such file or directory
ldu1app3876:appium-xcuitest-driver dfreeman$

**Comment by kaladine** [comment]
I found the bootstrap.sh file and was able to run it from the correct location
ldu1app3876:WebDriverAgent dfreeman$ ./Scripts/bootstrap.sh -d
Fetching dependencies
*** Downloading peertalk.framework binary at "v1.0"
*** Downloading RoutingHTTPServer.framework binary at "v1.0.1"
*** xcodebuild output can be found in /var/folders/y8/7y47r2ks1ts4q59cxjt2b6c1s0zrhz/T/carthage-xcodebuild.zr9ptE.log

**Comment by jlipps** [comment]
@kaladine any reason you're passing in a UDID for the simulator? typically that's not a good idea. also it usually helps us to have the _full_ appium logs.

**Comment by kaladine** [comment]
I appreciate the response.. I got things up and running... I've tried many things so don't remember what the actual silver bullet was but all is happy now.
