### ISSUE TITLE
Android bootstrap socket crashed: Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by BernalCarlos** [appium/appium#7930]
## The problem

I have an already working appium tests suite on my MacOS desktop, but when i try to run the same tests on an Ubuntu 16.04 desktop, I get the following error and appium gets closed automatically.

`Android bootstrap socket crashed: Error: connect ECONNREFUSED`

Also, just to be clear, i'm not trying to run simultaneous tests, just a single emulated android device.

## Environment

* Appium version: `1.6.3-Beta`. Also tried with 1.5.3 and got the same error.
* Last Appium version that did not exhibit the issue (if applicable): Not applicable.
* Desktop OS/version used to run Appium: `Ubuntu 16.04`
* Node.js version (unless using Appium.app|exe): `7.6.0`. But got the same error with v6.
* Mobile platform/version under test: `Andorid 6 (Marshmallow)`
* Real device or emulator/simulator: `Simulator`
* Appium CLI or Appium.app|exe: `Appium CLI`

## Details

Been stuck on this for a few days. Saw some question referring to simultaneous tests on the internet, but its not my case. I'm trying to run my tests on a single emulated android device.

Also tried to change the bootstrap port using the `-bp` option, and set the localhost address using `-a 127.0.0.1`, but no success.

## Link to Appium logs

https://gist.github.com/BernalCarlos/752efe621a55a2b2b0d07b966c8b5354

Thank you on advance.

**Comment by mykola-mokhnach** [comment]
> Forwarding system: 4724 to device: 4724

Why 4724 if Appium starts on port 4723 by default?

**Comment by BernalCarlos** [comment]
@mykola-mokhnach What I understand is that 4724 is the default device bootstrap port

**Comment by BernalCarlos** [comment]
Solved the problem by making a fresh install of linux mint 18.1.

Still don't know why this showed up in ubuntu 16.04.

**Comment by vikramvi** [comment]
@triager please close per last comment

**Comment by manishthackray** [comment]
I am facing same issue, using macOS -10.13.6 
Appium v1.8.1

I am trying parallel testing

Unhandled rejection Error: Android bootstrap socket crashed: Error: This socket has been ended by the other party
    at Socket.<anonymous> (/usr/local/lib/node_modules/appium/node_modules/appium-android-bootstrap/lib/bootstrap.js:87:21)
    at Socket.emit (events.js:182:13)
    at Socket.writeAfterFIN [as write] (net.js:404:8)
    at /usr/local/lib/node_modules/appium/node_modules/appium-android-bootstrap/lib/bootstrap.js:112:25
    at tryCatcher (/usr/local/lib/node_modules/appium/node_modules/appium-android-bootstrap/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/usr/local/lib/node_modules/appium/node_modules/appium-android-bootstrap/node_modules/bluebird/js/main/promise.js:483:31)
    at new Promise (/usr/local/lib/node_modules/appium/node_modules/appium-android-bootstrap/node_modules/bluebird/js/main/promise.js:71:37)
    at AndroidBootstrap.sendCommand$ (/usr/local/lib/node_modules/appium/node_modules/appium-android-bootstrap/lib/bootstrap.js:108:18)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at new Promise (<anonymous>)
    at new F (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at AndroidBootstrap.sendCommand (/usr/local/lib/node_modules/appium/node_modules/appium-android-bootstrap/build/lib/bootstrap.js:219:34)
    at AndroidBootstrap.shutdown$ (/usr/local/lib/node_modules/appium/node_modules/appium-android-bootstrap/lib/bootstrap.js:163:18)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at new Promise (<anonymous>)
    at new F (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at AndroidBootstrap.shutdown (/usr/local/lib/node_modules/appium/node_modules/appium-android-bootstrap/build/lib/bootstrap.js:306:34)
    at AndroidDriver.deleteSession$ (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/lib/driver.js:373:28)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
