### ISSUE TITLE
Appium1.6.3 does not find element on Android 7.1.1 device but works fine on 6.0 and lower version

### ISSUE THREAD

**Issue by AmitVerma4HP** [appium/appium#7943]
## The problem

Having issue with findElement via ID or xPath using Appium 1.6.3  and Android 7.1.1 device. 
whereas same appium version can easily find the element on Android 6.0 or lower. 
element details can be seen in below screenshot.
Appium kind of hangs after not finding element. 

![capture](https://cloud.githubusercontent.com/assets/22062978/23386701/e0040470-fd0c-11e6-8f82-5352ce996ec0.PNG)

**Test Code:**
//Click on search in google drive
	  try {
	      	driver.findElement(By.id("com.google.android.apps.docs:id/menu_search")).click();
	         }catch(NoSuchElementException e){
	        	log.info("Element not found via ID so trying with xpath");
	        	try{
	        	driver.findElement(By.xpath("//android.widget.TextView[@content-desc='Search']")).click();
	        	} catch (Exception e1){
		        	log.info("Error Occured while clicking on search icon");
		        	throw new RuntimeException(e1);
	                }
	        }

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details
Test Execution - 
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building MopriaAutoTest 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ MopriaAutoTest ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\github\MopriaAutoTest\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ MopriaAutoTest ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ MopriaAutoTest ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\github\MopriaAutoTest\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ MopriaAutoTest ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ MopriaAutoTest ---
[INFO] Surefire report directory: C:\github\MopriaAutoTest\target\surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running TestSuite
[INFO ] 20170227-164526 [main] getDeviceProp- List values 0=[WED NOV 30 20:07:36 UTC 2016]
[INFO ] 20170227-164526 [main] getDeviceProp- List values 1= [BULLHEAD-USER 7.1.1 N4F26I 3532671 RELEASE-KEYS]
[INFO ] 20170227-164526 [main] getDeviceProp- List values 2= [7.1.1]
[INFO ] 20170227-164526 [main] getDeviceProp- List values 3= [LGE]
[INFO ] 20170227-164526 [main] getDeviceProp- List values 4= [NEXUS 5X]
[INFO ] 20170227-164526 [main] setCapability- Setting Device Capability
[INFO ] 20170227-164526 [main] setCapability- Device Capabilities Are Set Now
[INFO ] 20170227-164533 [main] setup- Ensure device updated with latest APK which needs to be test
[INFO ] 20170227-164535 [main] getInstalledMopriaVersion- *****************************************************************************************
[INFO ] 20170227-164535 [main] getInstalledMopriaVersion- CURRENT MOPRIA VERSION INSTALLED	=2.2.2-BETA2-4-CE73AC2-MASTER
[INFO ] 20170227-164535 [main] printDeviceProp- ******************* Printing Property of Device Under Test ******************************
[INFO ] 20170227-164535 [main] printDeviceProp- DEVICE MANUFACTURER			= [LGE]
[INFO ] 20170227-164535 [main] printDeviceProp- DEVICE MODEL NAME 			= [NEXUS 5X]
[INFO ] 20170227-164535 [main] printDeviceProp- DEVICE ANDROID VERSION		= [7.1.1]
[INFO ] 20170227-164535 [main] printDeviceProp- DEVICE UID					=014b200364f6a4c5
[INFO ] 20170227-164535 [main] printDeviceProp- DEVICE BUILD DATE			=[WED NOV 30 20:07:36 UTC 2016]
[INFO ] 20170227-164535 [main] printDeviceProp- DEVICE BUILD DESCRIPTION	= [BULLHEAD-USER 7.1.1 N4F26I 3532671 RELEASE-KEYS]
[INFO ] 20170227-164535 [main] printDeviceProp- *****************************************************************************************
[INFO ] 20170227-164535 [main] setup- PRINTER UNDER TEST			=HP Officejet Pro 276dw MFP [19D067]
[INFO ] 20170227-164535 [main] setup- *****************************************************************************************
[INFO ] 20170227-164536 [main] StartLogCollection- **Log Capturing STARTED**
[INFO ] 20170227-164536 [main] StartLogCollection- Adb Log Location in Device => //storage//emulated//0//PdfPrintingOptionsAndroidM-27-Feb-2017__04_45_36PM.txt
[INFO ] 20170227-164538 [main] StartLogCollection- ADB process id started for adb logger process => 38792
[INFO ] 20170227-164540 [main] StartScreenRecording- **Video capturing STARTED**
[INFO ] 20170227-164540 [main] StartScreenRecording- Video Location in Device => //storage//emulated//0//PdfPrintingOptionsAndroidM-27-Feb-2017__04_45_38PM.mp4
[INFO ] 20170227-164541 [main] StartScreenRecording- ADB process id started for video recording process => 16516
[INFO ] 20170227-164541 [main] setup- *****************************************************************************************
[INFO ] 20170227-164541 [main] setup- ********************* TEST: START => PDF PRINTING OPTIONS *******************************
[INFO ] 20170227-164541 [main] setup- *****************************************************************************************
[INFO ] 20170227-164541 [main] setup- Opened Google Drive Successfully
[INFO ] 20170227-164545 [main] **OpenPdf- Element not found via ID so trying with xpath**

## Link to Appium logs

2017-02-28 00:45:07:636 - info: [Appium] Welcome to Appium v1.6.3
2017-02-28 00:45:07:636 - info: [Appium] Non-default server args:
2017-02-28 00:45:07:636 - info: [Appium]   address: '127.0.0.1'
2017-02-28 00:45:07:636 - info: [Appium]   sessionOverride: true
2017-02-28 00:45:07:636 - info: [Appium]   log: 'C:/AppiumLogs/appium.log'
2017-02-28 00:45:07:636 - info: [Appium]   logTimestamp: true
2017-02-28 00:45:07:636 - info: [Appium]   noReset: true
2017-02-28 00:45:07:636 - warn: [Appium] Deprecated server args:
2017-02-28 00:45:07:636 - warn: [Appium]   --no-reset => --default-capabilities '{"noReset":true}'
2017-02-28 00:45:07:636 - info: [Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
2017-02-28 00:45:07:651 - info: [Appium]   noReset: true
2017-02-28 00:45:07:698 - info: [Appium] Appium REST http interface listener started on 127.0.0.1:4723
2017-02-28 00:45:26:787 - info: [HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"appPackage":"com.google.android.apps.docs","appActivity":"com.google.android.apps.docs.app.NewMainProxyActivity","browserName":"android","platformName":"Android","udid":"014b200364f6a4c5","version":" 7.1.1","deviceName":" NEXUS 5X","platform":"ANDROID"}}
2017-02-28 00:45:26:787 - info: [debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"appPackage":"com.google.android.apps.docs","appActivity":"com.google.android.apps.docs.app.NewMainProxyActivity","browserName":"android","platformName":"Android","udid":"014b200364f6a4c5","version":" 7.1.1","deviceName":" NEXUS 5X","platform":"ANDROID"},null,null,null,null]
2017-02-28 00:45:26:787 - info: [Appium] Creating new AndroidDriver session
2017-02-28 00:45:26:787 - info: [Appium] Capabilities:
2017-02-28 00:45:26:802 - info: [Appium]   appPackage: 'com.google.android.apps.docs'
2017-02-28 00:45:26:802 - info: [Appium]   appActivity: 'com.google.android.apps.docs.app.NewMainProxyActivity'
2017-02-28 00:45:26:802 - info: [Appium]   browserName: 'android'
2017-02-28 00:45:26:802 - info: [Appium]   platformName: 'Android'
2017-02-28 00:45:26:802 - info: [Appium]   udid: '014b200364f6a4c5'
2017-02-28 00:45:26:802 - info: [Appium]   version: ' 7.1.1'
2017-02-28 00:45:26:802 - info: [Appium]   deviceName: ' NEXUS 5X'
2017-02-28 00:45:26:802 - info: [Appium]   platform: 'ANDROID'
2017-02-28 00:45:26:802 - info: [Appium]   noReset: true
2017-02-28 00:45:26:802 - info: [debug] [AndroidDriver] AndroidDriver version: 1.11.3
2017-02-28 00:45:26:818 - warn: [BaseDriver] The following capabilities were provided, but are not recognized by appium: version, platform.
2017-02-28 00:45:26:834 - info: [BaseDriver] Session created with session id: 44a48049-c0e5-4d4c-b61d-5cac41a8fc21
2017-02-28 00:45:26:834 - info: [debug] [AndroidDriver] Getting Java version
2017-02-28 00:45:27:008 - info: [AndroidDriver] Java version is: 1.8.0_101

2017-02-28 00:45:27:008 - info: [ADB] Checking whether adb is present
2017-02-28 00:45:27:024 - info: [ADB] Using adb.exe from C:\Users\veramit\AppData\Local\Android\sdk\platform-tools\adb.exe
2017-02-28 00:45:27:024 - info: [AndroidDriver] Retrieving device list
2017-02-28 00:45:27:024 - info: [debug] [ADB] Trying to find a connected android device
2017-02-28 00:45:27:024 - info: [debug] [ADB] Getting connected devices...
2017-02-28 00:45:27:039 - info: [debug] [ADB] 2 device(s) connected
2017-02-28 00:45:27:039 - info: [AndroidDriver] Using device: 014b200364f6a4c5
2017-02-28 00:45:27:039 - info: [ADB] Checking whether adb is present
2017-02-28 00:45:27:055 - info: [ADB] Using adb.exe from C:\Users\veramit\AppData\Local\Android\sdk\platform-tools\adb.exe
2017-02-28 00:45:27:055 - info: [debug] [ADB] Setting device id to 014b200364f6a4c5
2017-02-28 00:45:27:055 - info: [AndroidDriver] App file was not listed, instead we're going to run com.google.android.apps.docs directly on the device
2017-02-28 00:45:27:055 - info: [debug] [AndroidDriver] Checking whether package is present on the device
2017-02-28 00:45:27:055 - info: [debug] [ADB] Getting connected devices...
2017-02-28 00:45:27:086 - info: [debug] [ADB] 2 device(s) connected
2017-02-28 00:45:27:086 - info: [debug] [ADB] Running 'C:\Users\veramit\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","014b200364f6a4c5","shell","pm","list","packages","com.google.android.apps.docs"]
2017-02-28 00:45:28:053 - info: [AndroidDriver] Starting Android session
2017-02-28 00:45:28:053 - info: [debug] [ADB] Running 'C:\Users\veramit\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","014b200364f6a4c5","wait-for-device"]
2017-02-28 00:45:28:085 - info: [debug] [ADB] Getting connected devices...
2017-02-28 00:45:28:131 - info: [debug] [ADB] 2 device(s) connected
2017-02-28 00:45:28:131 - info: [debug] [ADB] Running 'C:\Users\veramit\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","014b200364f6a4c5","shell","echo","ping"]
2017-02-28 00:45:28:209 - info: [debug] [Logcat] Starting logcat capture
2017-02-28 00:45:28:287 - info: [debug] [AndroidDriver] Pushing settings apk to device...
2017-02-28 00:45:28:287 - info: [debug] [ADB] Running 'C:\Users\veramit\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","014b200364f6a4c5","install","C:\\Users\\veramit\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\io.appium.settings\\bin\\settings_apk-debug.apk"]
2017-02-28 00:45:28:615 - info: [debug] [ADB] Running 'C:\Users\veramit\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","014b200364f6a4c5","install","C:\\Users\\veramit\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\io.appium.settings\\bin\\settings_apk-debug.apk"]
2017-02-28 00:45:28:960 - info: [debug] [ADB] Application 'C:\Users\veramit\AppData\Roaming\npm\node_modules\appium\node_modules\io.appium.settings\bin\settings_apk-debug.apk' already installed. Continuing.
2017-02-28 00:45:28:960 - info: [debug] [AndroidDriver] Pushing unlock helper app to device...
2017-02-28 00:45:28:976 - info: [debug] [ADB] Running 'C:\Users\veramit\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","014b200364f6a4c5","install","C:\\Users\\veramit\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-unlock\\bin\\unlock_apk-debug.apk"]
2017-02-28 00:45:29:288 - info: [debug] [ADB] Running 'C:\Users\veramit\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","014b200364f6a4c5","install","C:\\Users\\veramit\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-unlock\\bin\\unlock_apk-debug.apk"]
2017-02-28 00:45:29:631 - info: [debug] [ADB] Application 'C:\Users\veramit\AppData\Roaming\npm\node_modules\appium\node_modules\appium-unlock\bin\unlock_apk-debug.apk' already installed. Continuing.
2017-02-28 00:45:29:631 - info: [ADB] Getting device platform version
2017-02-28 00:45:29:631 - info: [debug] [ADB] Getting connected devices...
2017-02-28 00:45:29:662 - info: [debug] [ADB] 2 device(s) connected
2017-02-28 00:45:29:662 - info: [debug] [ADB] Running 'C:\Users\veramit\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","014b200364f6a4c5","shell","getprop","ro.build.version.release"]
2017-02-28 00:45:29:709 - info: [debug] [ADB] Getting connected devices...
2017-02-28 00:45:29:740 - info: [debug] [ADB] 2 device(s) connected
2017-02-28 00:45:29:740 - info: [debug] [ADB] Running 'C:\Users\veramit\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","014b200364f6a4c5","shell","wm","size"]
2017-02-28 00:45:30:458 - info: [debug] [ADB] Getting connected devices...
2017-02-28 00:45:30:489 - info: [debug] [ADB] 2 device(s) connected
2017-02-28 00:45:30:489 - info: [debug] [ADB] Running 'C:\Users\veramit\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","014b200364f6a4c5","shell","getprop","ro.product.model"]
2017-02-28 00:45:30:583 - info: [debug] [ADB] Current device property 'ro.product.model': Nexus 5X
2017-02-28 00:45:30:598 - info: [debug] [ADB] Getting connected devices...
2017-02-28 00:45:30:629 - info: [debug] [ADB] 2 device(s) connected
2017-02-28 00:45:30:629 - info: [debug] [ADB] Running 'C:\Users\veramit\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","014b200364f6a4c5","shell","getprop","ro.product.manufacturer"]
2017-02-28 00:45:30:707 - info: [debug] [ADB] Current device property 'ro.product.manufacturer': LGE
2017-02-28 00:45:30:707 - info: [debug] [ADB] Getting connected devices...
2017-02-28 00:45:30:754 - info: [debug] [ADB] 2 device(s) connected
2017-02-28 00:45:30:754 - info: [debug] [ADB] Running 'C:\Users\veramit\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","014b200364f6a4c5","shell","dumpsys","window"]
2017-02-28 00:45:30:848 - info: [AndroidDriver] Screen already unlocked, doing nothing
2017-02-28 00:45:30:848 - warn: [AndroidDriver] No app sent in, not parsing package/activity
2017-02-28 00:45:30:848 - info: [debug] [AndroidDriver] No app capability. Assuming it is already on the device
2017-02-28 00:45:30:863 - info: [debug] [AndroidBootstrap] Watching for bootstrap disconnect
2017-02-28 00:45:30:863 - info: [debug] [ADB] Forwarding system: 4724 to device: 4724
2017-02-28 00:45:30:863 - info: [debug] [ADB] Running 'C:\Users\veramit\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","014b200364f6a4c5","forward","tcp:4724","tcp:4724"]
2017-02-28 00:45:30:863 - info: [debug] [UiAutomator] Starting UiAutomator
2017-02-28 00:45:30:863 - info: [debug] [UiAutomator] Moving to state 'starting'
2017-02-28 00:45:30:863 - info: [debug] [UiAutomator] Parsing uiautomator jar
2017-02-28 00:45:30:863 - info: [debug] [UiAutomator] Found jar name: 'AppiumBootstrap.jar'
2017-02-28 00:45:30:863 - info: [debug] [ADB] Running 'C:\Users\veramit\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","014b200364f6a4c5","push","C:\\Users\\veramit\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-android-bootstrap\\bootstrap\\bin\\AppiumBootstrap.jar","/data/local/tmp/"]
2017-02-28 00:45:30:926 - info: [debug] [ADB] Attempting to kill all uiautomator processes
2017-02-28 00:45:30:926 - info: [debug] [ADB] Getting all processes with uiautomator
2017-02-28 00:45:30:926 - info: [debug] [ADB] Getting connected devices...
2017-02-28 00:45:30:957 - info: [debug] [ADB] 2 device(s) connected
2017-02-28 00:45:30:957 - info: [debug] [ADB] Running 'C:\Users\veramit\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","014b200364f6a4c5","shell","ps"]
2017-02-28 00:45:31:113 - info: [ADB] No uiautomator process found to kill, continuing...
2017-02-28 00:45:31:113 - info: [debug] [UiAutomator] Starting UIAutomator
2017-02-28 00:45:31:113 - info: [debug] [ADB] Creating ADB subprocess with args: ["-P",5037,"-s","014b200364f6a4c5","shell","uiautomator","runtest","AppiumBootstrap.jar","-c","io.appium.android.bootstrap.Bootstrap","-e","pkg","com.google.android.apps.docs","-e","disableAndroidWatchers",false,"-e","acceptSslCerts",false]
2017-02-28 00:45:31:846 - info: [debug] [UiAutomator] Moving to state 'online'
2017-02-28 00:45:31:846 - info: [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Registered crash watchers.
2017-02-28 00:45:31:862 - info: [AndroidBootstrap] Android bootstrap socket is now connected
2017-02-28 00:45:31:862 - info: [debug] [ADB] Getting connected devices...
2017-02-28 00:45:31:862 - info: [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Client connected
2017-02-28 00:45:31:893 - info: [debug] [ADB] 2 device(s) connected
2017-02-28 00:45:31:909 - info: [debug] [ADB] Running 'C:\Users\veramit\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","014b200364f6a4c5","shell","getprop","ro.build.version.sdk"]
2017-02-28 00:45:31:987 - info: [debug] [ADB] Device API level: 25
2017-02-28 00:45:31:987 - info: [debug] [ADB] Getting connected devices...
2017-02-28 00:45:32:018 - info: [debug] [ADB] 2 device(s) connected
2017-02-28 00:45:32:018 - info: [debug] [ADB] Running 'C:\Users\veramit\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","014b200364f6a4c5","shell","am","start","-W","-n","com.google.android.apps.docs/com.google.android.apps.docs.app.NewMainProxyActivity","-S","-a","android.intent.action.MAIN","-c","android.intent.category.LAUNCHER","-f","0x10200000"]
2017-02-28 00:45:33:703 - info: [Appium] New AndroidDriver session created successfully, session 44a48049-c0e5-4d4c-b61d-5cac41a8fc21 added to master session list
2017-02-28 00:45:33:703 - info: [debug] [MJSONWP] Responding to client with driver.createSession() result: {"platform":"ANDROID","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"appPackage":"com.google.android.apps.docs","appActivity":"com.google.android.apps.docs.app.NewMainProxyActivity","browserName":"android","platformName":"Android","udid":"014b200364f6a4c5","version":" 7.1.1","deviceName":" NEXUS 5X","platform":"ANDROID","noReset":true},"appPackage":"com.google.android.apps.docs","appActivity":"com.google.android.apps.docs.app.NewMainProxyActivity","browserName":"android","platformName":"Android","udid":"014b200364f6a4c5","version":" 7.1.1","deviceName":"014b200364f6a4c5","noReset":true,"deviceUDID":"014b200364f6a4c5","platformVersion":"7.1.1","deviceScreenSize":"1080x1920","deviceModel":"Nexus 5X","deviceManufacturer":"LGE"}
2017-02-28 00:45:33:703 - info: [HTTP] <-- POST /wd/hub/session 200 6919 ms - 946 
2017-02-28 00:45:42:195 - info: [HTTP] --> POST /wd/hub/session/44a48049-c0e5-4d4c-b61d-5cac41a8fc21/element {"using":"id","value":"com.google.android.apps.docs:id/menu_search"}
2017-02-28 00:45:42:195 - info: [debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["id","com.google.android.apps.docs:id/menu_search","44a48049-c0e5-4d4c-b61d-5cac41a8fc21"]
2017-02-28 00:45:42:226 - info: [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
2017-02-28 00:45:42:226 - info: [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
2017-02-28 00:45:42:226 - info: [debug] [BaseDriver] Waiting up to 0 ms for condition
2017-02-28 00:45:42:226 - info: [debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"id","selector":"com.google.android.apps.docs:id/menu_search","context":"","multiple":false}}
2017-02-28 00:45:42:242 - info: [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"id","selector":"com.google.android.apps.docs:id/menu_search","context":"","multiple":false}}
2017-02-28 00:45:42:242 - info: [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
2017-02-28 00:45:42:242 - info: [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
2017-02-28 00:45:42:242 - info: [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding 'com.google.android.apps.docs:id/menu_search' using 'ID' with the contextId: '' multiple: false
2017-02-28 00:45:42:242 - info: [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[INSTANCE=0, RESOURCE_ID=com.google.android.apps.docs:id/menu_search]
2017-02-28 00:45:43:412 - info: [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Failed to locate element. Clearing Accessibility cache and retrying.
2017-02-28 00:45:43:412 - info: [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding 'com.google.android.apps.docs:id/menu_search' using 'ID' with the contextId: '' multiple: false
2017-02-28 00:45:43:427 - info: [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[INSTANCE=0, RESOURCE_ID=com.google.android.apps.docs:id/menu_search]
2017-02-28 00:45:45:705 - info: [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":7,"value":"No element found"}
2017-02-28 00:45:45:705 - info: [debug] [AndroidBootstrap] Received command result from bootstrap
2017-02-28 00:45:45:721 - info: [HTTP] <-- POST /wd/hub/session/44a48049-c0e5-4d4c-b61d-5cac41a8fc21/element 500 3531 ms - 164 
2017-02-28 00:45:45:752 - info: [HTTP] --> POST /wd/hub/session/44a48049-c0e5-4d4c-b61d-5cac41a8fc21/element {"using":"xpath","value":"//android.widget.TextView[@content-desc='Search']"}
2017-02-28 00:45:45:752 - info: [debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["xpath","//android.widget.TextView[@content-desc='Search']","44a48049-c0e5-4d4c-b61d-5cac41a8fc21"]
2017-02-28 00:45:45:752 - info: [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
2017-02-28 00:45:45:752 - info: [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
2017-02-28 00:45:45:752 - info: [debug] [BaseDriver] Waiting up to 0 ms for condition
2017-02-28 00:45:45:752 - info: [debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//android.widget.TextView[@content-desc='Search']","context":"","multiple":false}}
2017-02-28 00:45:45:752 - info: [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//android.widget.TextView[@content-desc='Search']","context":"","multiple":false}}
2017-02-28 00:45:45:767 - info: [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
2017-02-28 00:45:45:768 - info: [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
2017-02-28 00:45:45:768 - info: [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding '//android.widget.TextView[@content-desc='Search']' using 'XPATH' with the contextId: '' multiple: false

**Comment by mykola-mokhnach** [comment]
Probably, it's a good time for switching to UIAutomation2?

**Comment by amedvedjev** [comment]
@mykola-mokhnach good time for switching to UIAutomation2? - really?
tried latest version with:
```
[debug] [ADB] Running '/Users/Aleksei/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","LGH8155e9892e6","forward","--remove","tcp:8200"]
[MJSONWP] Encountered internal error running command: TypeError: Cannot read property 'isScreenLocked' of undefined
    at Object.callee$0$0$ (../../lib/android-helpers.js:419:18)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at F (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at Object.callee$0$0 [as unlock] (../../lib/android-helpers.js:418:59)
    at AndroidUiautomator2Driver.startUiAutomator2Session$ (../../lib/driver.js:242:19)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[HTTP] <-- POST /wd/hub/session 500 7940 ms - 187 
```

**Comment by mykola-mokhnach** [comment]
@amedvedjev Really. Google has dropped support of UIAutomation1 a while ago. It is normal, that a new implementation can have bugs. It requires time for stabilisation and support from community.

**Comment by amedvedjev** [comment]
@mykola-mokhnach agree. but please make it at least start driver pls. i failed to do this with above error.

**Comment by mykola-mokhnach** [comment]
@amedvedjev did you created an issue report for the error already?

**Comment by amedvedjev** [comment]
@mykola-mokhnach just added. will try again when fixed or maybe corrected what i do wrong.

**Comment by AmitVerma4HP** [comment]
How do i use UIAutomator2 for Android automation testing? 
Right now I UIAutomator.exe directly from android SDK so where do i get UIAutomator2.exe to  read device UI XML?

**Comment by priyankshah217** [comment]
Use uiautomator2 as capability while initializing driver. Even I faced issue while using uiautomator1 with Android 7. So this is known issue, it's not from appium side.
Just try with uiautomator2 and close this issue if it does work.
