### ISSUE TITLE
Appium1.6.3 can't install app on real device

### ISSUE THREAD

**Issue by Tracydeng** [appium/appium#7946]
## The problem

 When i use Appium with command 'appium -U identifierxxxxxxx --app com.xxxxx.xxxx'  and run python test case,it throw errors

## Environment

* Appium version (or git revision) that exhibits the issue:v1.6.3
* Desktop OS/version used to run Appium:macOS Sierra
* Node.js version (unless using Appium.app|exe):v6.3.1
* Mobile platform/version under test:iOS 8.4

## Link to Appium logs

```
 ~ appium -U identifierxxxxxxx --app com.xxxxx.xxxx
[Appium] Welcome to Appium v1.6.3
[Appium] Non-default server args:
[Appium]   app: 'com.xxxxx.xxxxx'
[Appium]   udid: 'identifierxxxxxxx'
[Appium] Deprecated server args:
[Appium]   --app => --default-capabilities '{"app":"com.xxxx.xxxx"}'
[Appium]   -U,--udid => --default-capabilities '{"udid":"identifierxxxxxxx"}'
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   app: 'com.xxxx.xxxx'
[Appium]   udid: 'identifierxxxxxxx'
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"requiredCapabilities":{},"desiredCapabilities":{"udid":"identifierxxxxxxx","deviceName":"iPhone 6","app":"com.tzbank.pingAnFF","platformName":"iOS"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"udid":"identifierxxxxxxx","deviceName":"iPhone 6","app":"com.xxxxx.xxxxx","platformName":"iOS"},{},null,null,null]
[Appium] Creating new IosDriver session
[Appium] Capabilities:
[Appium]   udid: 'identifierxxxxxxx'
[Appium]   deviceName: 'iPhone 6'
[Appium]   app: 'com.xxxx.xxxx'
[Appium]   platformName: 'iOS'
[debug] [iOS] IosDriver version: 1.16.0
[BaseDriver] Session created with session id: 242e50e5-d2e4-41e8-b329-86551eaf3cbf
[debug] [iOS] Xcode version set to 7.3.1
[debug] [iOS] Not auto-detecting udid.
[debug] [iOS] App is an iOS bundle, will attempt to run as pre-existing
[debug] [iOS] Removing any remaining instruments sockets
[debug] [iOS] Cleaned up instruments socket /var/folders/rw/y4bk3_s11xn7bgm73wbj0vm80000gn/T/instruments_sock
[debug] [iOS] No language specified. Using default strings
[debug] [iOS] Strings file not found. Looking in 'en.lproj' directory
[iOS] Could not file localizable strings file 'Localizable.strings'!
[debug] [iOS] Creating instruments
[debug] [UIAuto] Preparing bootstrap code
[debug] [UIAuto] Dynamic bootstrap dir: /Users/iSteven/Library/Application Support/appium/bootstrap
[debug] [UIAuto] Dynamic env: {"nodePath":"/Users/iSteven/.nvm/versions/node/v6.3.1/bin/node","commandProxyClientPath":"/Users/iSteven/.nvm/versions/node/v6.3.1/lib/node_modules/appium/node_modules/.2.3.3@appium-uiauto/build/lib/bin/command-proxy-client.js","instrumentsSock":"/var/folders/rw/y4bk3_s11xn7bgm73wbj0vm80000gn/T/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"grouped"}
[debug] [UIAuto] Dynamic bootstrap code: // This file is automatically generated. Do not manually mo...y!
[debug] [UIAuto] Dynamic bootstrap path: /Users/iSteven/Library/Application Support/appium/bootstrap/bootstrap-5cc878eeb6255d81.js
[debug] [UIAuto] Reusing dynamic bootstrap: /Users/iSteven/Library/Application Support/appium/bootstrap/bootstrap-5cc878eeb6255d81.js
[debug] [iOS] Creating iDevice object with udid 26900f10fd440aa0acf68a60d11046fcddfac054
[debug] [iOS] Running ios real device reset flow
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[debug] [iOS] App is not installed. Will try to install.
[MJSONWP] Encountered internal error running command: Error: Installing /Users/iSteven/iSteven/AppiumProject/Xcode8.2.1_iOS10.2/Debug/xxxxx.app failed
    at /Users/iSteven/.nvm/versions/node/v6.3.1/lib/node_modules/appium/node_modules/.0.1.6@node-idevice/main.js:159:6
    at ChildProcess.exithandler (child_process.js:193:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
[HTTP] <-- POST /wd/hub/session 500 1041 ms - 174 
```

## Code To Reproduce Issue [ Good To Have ]

```
app = os.path.abspath('/Users/iSteven/iSteven/AppiumProject/Xcode8.2.1_iOS10.2/Debug/xxx.app')
       self.driver = webdriver.Remote(
                                      command_executor='http://127.0.0.1:4723/wd/hub',
                                      desired_capabilities={
                                      'deviceName': 'iPhone 6',
                                      'app': app,
                                      'platformName': 'iOS',
                                      # 'automationName':"xcuitest",
                                      'udid':'identifierxxxxxxx'
                                      })
```

**Comment by mykola-mokhnach** [comment]
Do you follow the real device configuration [tutorial](https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md)?
Is your app signed with dev signature and built for debug mode?

**Comment by Tracydeng** [comment]
When I run     "xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<udid>' test",
 it  throw Error describle:
2017-02-28 23:20:39.394 xcodebuild[36486:1398919] Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}

It's not certificate trust trouble ,but the app can't lauched, and seems like crash

**Comment by jlipps** [comment]
You need a signed ipa to run on a real device, not a debug version of the app.
