### ISSUE TITLE
ios 10.0 appium 1.6.3 - WebElement Y location is incorrect.

### ISSUE THREAD

**Issue by vsadineni1** [appium/appium#7957]
## The problem
After upgrading to appium 1.6.3, WebElement Y location is coming out to be in-correct. We have to add the height of the address bar to get the correct Y value. Otherwise the element is not getting pressed when we do a TouchAction
This behaviour is not seen in  appium 1.5.4.

## Environment
* Appium version (or git revision) that exhibits the issue:1.6.3
* Last Appium version that did not exhibit the issue (if applicable):1.5.4
* Desktop OS/version used to run Appium: Mac OSX 10.12.2
* Node.js version (unless using Appium.app|exe): v7.6.0
* Mobile platform/version under test: iOS 10.2
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe:

## Details

We are trying to locate a WebElement and call the TouchActions: press -> release -> perform.
But in appium 1.6.3, nothing happens because the element's Y location is not returned correctly. 
To find the correct Y location, we need to add the height of the addressbar in iPhone & iPad.

_Appium] Capabilities:
[Appium]   appiumVersion: '1.6'
[Appium]   version: ''
[Appium]   deviceName: 'iPhone 6'
[Appium]   platform: 'MAC'
[Appium]   tags: [ 'MyMachine.internal.com' ]
[Appium]   build: 'main-local-HEAD'
[Appium]   platformVersion: '10.0'
[Appium]   idleTimeout: 120
[Appium]   name: '[MobileSafari] IOSDriverUtilTest.testTapOnElement'
[Appium]   browserName: 'Safari'
[Appium]   takesScreenshot: true
[Appium]   platformName: 'iOS'
[debug] [XCUITest] XCUITestDriver version: 2.4.2_

## Link to Appium logs

Gist for Log: https://gist.github.com/anonymous/faf7378a4f9fece4b5d157a53338d08e

## Code To Reproduce Issue [ Good To Have ]
Essentially, we find the centre point of element and then do the below TouchActions:
**press -> wait -> release -> perform**  
https://gist.github.com/vsadineni1/6cdc5f886cb1181b8f5db196777df5fa

**Comment by jlipps** [comment]
@vsadineni1 can I ask why you are trying to tap the position of a web element in the native context, rather than simply calling `element.click()` on the web element?

**Comment by jlipps** [comment]
Alternatively, have you tried the `nativeWebTap` capability set to `true`? It attempts to tap natively on web elements without you having to switch contexts.

**Comment by vsadineni1** [comment]
@jlipps 
I tried to call the **click()** method on the WebElement. But I get  the below exception:
Caused by: org.openqa.selenium.WebDriverException: null (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 76 milliseconds
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'localhost', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-110-generic', java.version: '1.8.0_102'
Driver info: test.util.webdriver.SfdcRemoteWebDriver
Capabilities [{networkConnectionEnabled=false, appiumVersion=1.6, databaseEnabled=false, version=, deviceName=iPhone 6, platform=MAC, tags=[venkasadi-wsl.internal.salesforce.com], build=main-local-HEAD, platformVersion=10.0, idleTimeout=120, webStorageEnabled=false, locationContextEnabled=false, name=[MobileSafari] IOSDriverUtilTest.testTapOnElement, browserName=Safari, takesScreenshot=true, javascriptEnabled=true, platformName=iOS}]
Session ID: b050bdc3-11fb-4469-b05c-d8716769a5ff
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
    at test.util.webdriver.SfdcRemoteWebDriver.execute(SfdcRemoteWebDriver.java:177)
    at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:327)
    at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:85)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement$1.invoke(EventFiringWebDriver.java:331)
    at com.sun.proxy.$Proxy382.click(Unknown Source)
    at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement.click(EventFiringWebDriver.java:344)
    at test.util.webdriver.IOSDriverUtil.tap(IOSDriverUtil.java:282)
    at test.frameworktest.uiautomation.infrastructure.IOSDriverUtilTest.testTapOnElement(IOSDriverUtilTest.java:52)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at test.util.SimplerTestCase.runTest(SimplerTestCase.java:292)

I tried to set the capability **nativeWebTap = true** in the capabilities and removed all the context switches. In that case also it failed to find the element. The element's Y co-ordinate is still in-correct.

Gist log: https://gist.github.com/vsadineni1/60b056d940f7de199e5df696c792628d

**Comment by jlipps** [comment]
@vsadineni1 can you share your updated test code? The gist you provided doesn't show any click being attempted by your test script. Rather, the `#touchDiv` element is not being found; that's why your script is stopping. I'm curious why that is.

But it does seem like there is an issue here with element location. We need to do one of two things:

1. fix `nativeWebTap` behavior internally so that it correctly accounts for the presence/absence and height of the nav bar

or

2. fix the element location call so that it returns the correct y value.

I'm not sure which is the correct approach yet since we don't know what exactly is going wrong. But I'll prioritize this investigation.

**Comment by vsadineni1** [comment]
@jlipps click() method is working on the element. Sorry for the confusion. Last time when I tried, I was not in the natie_app context I think.

However, we still need to fix the Y location of the element.

**Comment by imurchie** [comment]
Is this still a problem with the latest version of Appium (1.6.4-beta)? I am trying to reproduce so as to fix it, but I'm able to click on things without any transformation of the Y coordinates.

If it does happen, can you provide a reproducing case?

**Comment by jlipps** [comment]
@vsadineni1 it looks @imurchie was unable to reproduce with the apps we have access to. Any way we can get a repro case from you for the Y location issue?

**Comment by nunessf** [comment]
Was this issue fixed on version 1.6.4 (or any other release), or was it just not reproduceable? I think it may be happening on version 1.6.5
