### ISSUE TITLE
AndroidDriver to get LogType=performance produces exception, works fine with RemoteWebDriver/ChromeDriver

### ISSUE THREAD

**Issue by dgchanchal** [appium/appium#7972]
Using Appium(AndroidDriver) to obtain performance logs from LogType, produces exception.
 If you use a general RemoteWebDriver/ChromeDriver object, the performance logs are getting produced. While Appium also provides "enablePerformanceLogging" flag to capture performance logs for Android webview. But after enabling this flag also, performance logs are not getting captured. 

## Environment
* Appium version (or git revision) that exhibits the issue: 1.5.2
* Desktop OS/version used to run Appium: Mac OS X EI Capitan
* Mobile platform/version under test: Android 4.4
* Real device or emulator/simulator: Lenovo A6000 Real Device
* Appium CLI or Appium.app|exe:Appium.app

## Details
1. Create a driver instance using AndroidDriver:

Produces performance logs without issue:

```
DesiredCapabilities caps = DesiredCapabilities.chrome();
if (null != androidPackage) {
    ChromeOptions chromeOptions = new ChromeOptions();
    chromeOptions.setExperimentalOption("androidPackage", androidPackage);
    caps.setCapability(ChromeOptions.CAPABILITY, chromeOptions);
}
LoggingPreferences logPrefs = new LoggingPreferences();
logPrefs.enable(LogType.BROWSER, Level.ALL);
logPrefs.enable(LogType.PERFORMANCE, Level.INFO);
caps.setCapability(CapabilityType.LOGGING_PREFS, logPrefs);

ChromeDriverService service = new ChromeDriverService.Builder()
        .usingDriverExecutable(new File("/Users/abc/Desktop/driver/chromedriver"))
        .usingAnyFreePort()
        .build();
service.start();
driver = new RemoteWebDriver(service.getUrl(),
        caps);

```
Does NOT produce performance logs:

```
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability("browsername","chrome");
capabilities.setCapability("device","android");
capabilities.setCapability("deviceName","AndroidEmulator");
capabilities.setCapability("platformversion","5.1");
capabilities.setCapability("platformname","Android");
capabilities.setCapability("appPackage","com.android.chrome");
capabilities.setCapability("appActivity","com.google.android.apps.chrome.Main");
// Enabling LoggingPreferences
capabilities.setCapability("enablePerformanceLogging",true);

LoggingPreferences logPrefs = new LoggingPreferences();
logPrefs.enable(LogType.PERFORMANCE, Level.INFO);
capabilities.setCapability(CapabilityType.LOGGING_PREFS, logPrefs);

driver = new AndroidDriver(new URL("http://127.0.0.0:4723/wd/hub"), capabilities);
```
2. Execute `List<LogEntry> entries = driverObj.manage().logs().get(LogType.PERFORMANCE).getAll();`

3. exception thrown:
`org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Unsupported log type performance. Supported types are {"logcat":"Logs for Android applications on real device and emulators via ADB"} (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 65 milliseconds
Build info: version: '2.43.1', revision: '5163bce', time: '2014-09-10 16:27:33'
System info: host: '***', ip: '***', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_121'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{appPackage=com.android.chrome, networkConnectionEnabled=true, noReset=true, warnings={}, loggingPrefs={performance=INFO}, browsername=chrome, databaseEnabled=false, fullReset=false, deviceName=****, platform=LINUX, platformname=Android, appActivity=com.google.android.apps.chrome.Main, desired={appPackage=com.android.chrome, appActivity=com.google.android.apps.chrome.Main, noReset=true, loggingPrefs={performance=INFO}, browsername=chrome, platformversion=5.1, platformName=Android, fullReset=false, device=android, deviceName=AndroidEmulator, enablePerformanceLogging=true, platformname=Android}, platformVersion=5.1.1, webStorageEnabled=false, locationContextEnabled=false, takesScreenshot=true, javascriptEnabled=true, platformversion=5.1, platformName=Android, device=android, enablePerformanceLogging=true}]
Session ID: b893070c-bc90-498a-9d01-70934cbdc34b
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:180)
	at org.openqa.selenium.remote.RemoteExecuteMethod.execute(RemoteExecuteMethod.java:34)
	at org.openqa.selenium.remote.RemoteLogs.getRemoteEntries(RemoteLogs.java:65)
	at org.openqa.selenium.remote.RemoteLogs.get(RemoteLogs.java:61)
	at test.mobile.SDCHTCTest.printLog(SDCHTCTest.java:79)
	at test.mobile.SDCHTCTest.tearDown(SDCHTCTest.java:66)
	at test.mobile.SDCHTCTest.runPerfa(SDCHTCTest.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)`

**Comment by imurchie** [comment]
Thanks for the report. Adding to our backlog.

**Comment by skansar** [comment]
i have similar issue on IOS, for running Mobile Web Tests, Driver successfully created tests with below capabilities

 driver  info: [HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"newCommandTimeout":"1800","automationName":"XCUITest","autoWebview":"true","platformName":"iOS","deviceName":"iPhone 6"}}

but failed with below issue

2017-07-12 22:37:30:325 - info: [HTTP] <-- GET /wd/hub/session/d4018349-9964-47b4-a972-d43490adf380/source 200 26 ms - 16173
2017-07-12 22:37:30:355 - info: [HTTP] --> POST /wd/hub/session/d4018349-9964-47b4-a972-d43490adf380/log {"type":"browser"}
2017-07-12 22:37:30:357 - info: [debug] [MJSONWP] Calling AppiumDriver.getLog() with args: ["browser","d4018349-9964-47b4-a972-d43490adf380"]
2017-07-12 22:37:30:358 - info: [debug] [XCUITest] Executing command 'getLog'
2017-07-12 22:37:30:359 - info: [debug] [iOS] Retrieving 'browser' logs
2017-07-12 22:37:30:452 - error: [MJSONWP] Encountered internal error running command: Error: Unsupported log type 'browser' for this device. Supported types : {"syslog":"System Logs - Device logs for iOS applications on real devices and simulators","crashlog":"Crash Logs - Crash reports for iOS applications on real devices and simulators","performance":"Performance Logs - Debug Timelines on real devices and simulators"}
at XCUITestDriver.callee$0$0$ (../../../lib/commands/logging.js:24:11)

**Comment by imurchie** [comment]
Yes. "browser" is not a supported log type.

**Comment by skansar** [comment]
https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/webdriver.py#1092

you are saying this is not applicable to AppiumDriver

=================
def get_log(self, log_type):
--
  | """
  | Gets the log for a given log type
  |  
  | :Args:
  | - log_type: type of log that which will be returned
  |  
  | :Usage:
  | driver.get_log('browser')
  | driver.get_log('driver')
  | driver.get_log('client')
  | driver.get_log('server')
  | """
  | return self.execute(Command.GET_LOG, {'type': log_type})['value']

**Comment by imurchie** [comment]
Correct. You can see the valid types in the logs you  posted:
```
Supported types : {
  "syslog": "System Logs - Device logs for iOS applications on real devices and simulators",
  "crashlog": "Crash Logs - Crash reports for iOS applications on real devices and simulators",
  "performance": "Performance Logs - Debug Timelines on real devices and simulators"
}
```

**Comment by skansar** [comment]
2017-07-12 22:37:30:325 - info: [HTTP] <-- GET /wd/hub/session/d4018349-9964-47b4-a972-d43490adf380/source 200 26 ms - 16173
2017-07-12 22:37:30:355 - info: [HTTP] --> POST /wd/hub/session/d4018349-9964-47b4-a972-d43490adf380/log {"type":"browser"}

Can you please explain where this POST is getting initiated , its not from my code though? any suggesstions.

**Comment by imurchie** [comment]
I have no idea. Somewhere in your code, even if not some part that you wrote.

**Comment by jlipps** [comment]
@dgchanchal you need to be in a webview context to see performance logs.
