### ISSUE TITLE
Unable to run tests on iOS 10.0.2 using Appium 1.6.3

### ISSUE THREAD

**Issue by abhilashcae** [appium/appium#7975]
## The problem

I'm unable to run tests on iOS 10 device (iPad Pro running on iOS 10.0.2)

## Environment

* Appium version: 1.6.3
* Desktop OS/version used to run Appium: OSX El Capitan 10.11.6
* Node.js version : 6.10.0
* Xcode version: 8.2.1
* Mobile platform/version under test: iOS 10.0.2
* Real device or emulator/simulator: Real Device (iPad Pro)
* Appium CLI

## Details

Below is what I tried:

1. Installed Appium 1.6.3, carthage, ios-deploy, ideviceinstaller, libimobiledevice, ios-webkit-debug-proxy.
2. Added the new capability `automationName` as `XCUITest`.
3. Created a configuration file in added DEVELOPMENT_TEAM and CODE_SIGN_IDENTITY (DEVELOPMENT_TEAM = "10 digit team code provided by Apple", CODE_SIGN_IDENTITY = iPhone Developer).
4. Added the capability `xcodeConfigFile` as `/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Configurations/ProjectSettings.xcconfig` in my test.
5. In WebdriverAgentLib and WebdriverAgentRunner I selected "Automatically merge signing". When this failed to run the tests, I also tried adding the profile manually as well.
6. Added the XCTest.framework dependency to WebdriverAgentLib.
7. Ran `./Scripts/bootstrap.sh - d` but failed (logs attached).
8. Ran `xcodebuild build test -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=<<My_Device_Id>> -configuration Debug` but failed too (logs attached).

Note: Reference ticket: #7022 

[Appium logs.txt](https://github.com/appium/appium/files/818091/Appium.logs.txt)
[Bootstrap shell script logs.txt](https://github.com/appium/appium/files/818090/Bootstrap.shell.script.logs.txt)
[Xcode build command logs.txt](https://github.com/appium/appium/files/818092/Xcode.build.command.logs.txt)

Cc:
@imurchie @jlipps @vjmaiky @andreiaionitoaiesv appreciate your help on this please.

**Comment by mykola-mokhnach** [comment]
Try Appium 1.6.4-beta. I think we've recently pushed a fix for library search while building WDA. So that should be fine now. Right @imurchie ?

**Comment by abhilashcae** [comment]
Thanks, @mykola-mokhnach ! I did update to Appium 1.6.4-beta and ran `./Scripts/bootstrap.sh -d` but it gave me the below error (something different from the one I have attached above).

```Cannot find module 'eslint-config-appium'
Referenced from: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/.eslintrc
Error: Cannot find module 'eslint-config-appium'
Referenced from: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/.eslintrc
    at ModuleResolver.resolve (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/eslint/lib/util/module-resolver.js:74:19)
    at resolve (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/eslint/lib/config/config-file.js:485:25)
    at load (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/eslint/lib/config/config-file.js:502:26)
    at configExtends.reduceRight.e (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/eslint/lib/config/config-file.js:391:36)
    at Array.reduceRight (native)
    at applyExtends (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/eslint/lib/config/config-file.js:362:28)
    at Object.load (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/eslint/lib/config/config-file.js:536:22)
    at loadConfig (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/eslint/lib/config.js:63:33)
    at getLocalConfig (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/eslint/lib/config.js:130:29)
    at Config.getConfig (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/eslint/lib/config.js:260:26)```

Attached are the full logs of `./Scripts/bootstrap.sh -d` 
[Appium1.6.4_bootstraplogs.txt](https://github.com/appium/appium/files/818176/Appium1.6.4_bootstraplogs.txt)

**Comment by mykola-mokhnach** [comment]
what if you just ignore the error (this does not affect any critical components anyway) and continue with testing?
@imurchie why WDA inspector requires appium eslint config module to be installed?

**Comment by imurchie** [comment]
I have no idea. The output does not look like the `-d` flag is actually being used.

**Comment by abhilashcae** [comment]
@mykola-mokhnach - I tried ignoring the error but the tests gave the same error as before (logs attached in the ticket body).

**Comment by imurchie** [comment]
I can reproduce the error but only if the `-d` flag is not used. And within Appium it is _always_ used. So that whole avenue is a red herring. 

Can you post, as a link to a [gist](https://gist.github.com) (_not_ an attached file), the Appium server logs for a test run with Appium 1.6.4-beta? Preferably with `showXcodeLog` capability on.

**Comment by abhilashcae** [comment]
@imurchie - Here you go: https://gist.github.com/abhilashcae/62172ae2f4928669447bad818c0c776d

**Comment by abhilashcae** [comment]
Ok, here's what I did and resolved my issue:
1. Downloaded the latest Apple WWRDC (which I had done previously as well but did not work. Probably because I did not do step #2 mentioned below)
2. Cleared the Xcode DerivedData manually. Thanks to http://stackoverflow.com/questions/32730312/reason-no-suitable-image-found

**Comment by Netardent** [comment]
Dear @abhilashcae @mykola-mokhnach @ imurchie please help me,
I tried to ./Script/bootsrtrap.sh but got same error and after your suggestion @abhilashcae i have the same error which i attached.

Mac Os:Sierra 10.12.4
Xcode: 8.3.2
Appium : 1.6.4
Appium Desktop CLI

Where should i get error log and how can i fix it?

![1](https://cloud.githubusercontent.com/assets/9458718/25515233/6a7f1422-2bf8-11e7-998b-48dd58ebfa56.png)

and the zSusrzSlocalzSlibzSnode_moduleszSappiumzSnode_moduleszSappium-xcuitest-driverzSWebDriverAgentzSInspector.log contain:

[2017-04-28 09:43:29] Initializing Server (This might take some time)
[2017-04-28 09:43:29] executable=/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/flow-bin/flow-osx-v0.38.0/flow
[2017-04-28 09:43:29] version=0.38.0
[2017-04-28 09:43:29] Parsing
[2017-04-28 09:44:31] Building package heap
[2017-04-28 09:44:31] Loading libraries
[2017-04-28 09:44:31] Running local inference
[2017-04-28 09:44:33] Re-resolving directly dependent files
[2017-04-28 09:44:33] Calculating dependencies
[2017-04-28 09:44:33] Merging
[2017-04-28 09:44:33] Done
[2017-04-28 09:44:33] Server is READY
[2017-04-28 09:44:33] Took 64.231523 seconds to initialize.
[2017-04-28 09:44:33] Status: OK

**Comment by imurchie** [comment]
@Netardent There is a flag, `-d`, for the bootstrap script. Use it.
