### ISSUE TITLE
Can't find elements - [MJSONWP] Encountered internal error running command: Error: Error while executing atom: operation timed out

### ISSUE THREAD

**Issue by Icaroto** [appium/appium#7977]
## The problem

I'm not been able to interact with my app (find elements). From the Appium logs I see a the following message:

```
[debug] [RemoteDebugger] Executing 'find_element' atom in default context
[debug] [RemoteDebugger] Sending javascript command (function(){return function(){var aa="function"...
[debug] [RemoteDebugger] Sending WebKit data: {"method":"Runtime.evaluate...
[MJSONWP] Encountered internal error running command: Error: Error while executing atom: operation timed out
    at XCUITestDriver.callee$0$0$ (../../../lib/commands/web.js:75:11)
    at tryCatch (/Users/itorres/.nvm/versions/node/v6.10.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/itorres/.nvm/versions/node/v6.10.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/itorres/.nvm/versions/node/v6.10.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/itorres/.nvm/versions/node/v6.10.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
```

## Environment

* Appium: 1.6.4-beta
* I'm running the tests from a Windows 7 Machine (Visual Studio C#), the machine running the Appium server is a MAC Sierra 10.12.3 with a iPhone 10.0.2 connected.

## Details

To be more specific: My app has 3 pages. On page 1 I set the context to web view and interact with the elements to login, that leads me to page 2 where I set the context to the Native App in order to set some informations and accept an alert. Then, once it loads page 3, I change my context back to webview and use the setWindow to make sure I'm in the correct window. After that, I see the log:

[debug] [MJSONWP] Calling AppiumDriver.setWindow() with args: ["1","63b47f55-b379-4841-9cca-01d873567636"]
[debug] [XCUITest] Executing command 'setWindow'
[debug] [RemoteDebugger] Disconnecting from WebKit remote debugger
[debug] [RemoteDebugger] WebKit remote debugger socket disconnected
[debug] [RemoteDebugger] WebKit debugger web socket connected to url: ws://localhost:27753/devtools/page/1
[debug] [MJSONWP] Responding to client with driver.setWindow() result: null

and can't find any elements on page. If I try to check contexts, it works. But it doesn't find any element on page...
 
In the log below, after the error I tried to see the contexts available (which worked) and then find an element using xpath (which failed)
Appium logs: https://gist.github.com/Icaroto/27a79ed41a15f492cb8fb108017d2b82

Thanks!

**Comment by dpgraham** [comment]
Hey @imurchie, this sounds similar to this ticket https://github.com/appium/appium/issues/6367

@Icaroto is able to interact with webview elements but then after switching context to native and then back to webview finding elements is being timed out.

**Comment by sp5594** [comment]
I have noticed the same issue as well. Please see my attached log..
[log.pdf](https://github.com/appium/appium/files/844728/log.pdf)

**Comment by skumar1122** [comment]
Hey All ,

I am having same issue today with new updates ,
Appium: 1.6.4-beta
Xcode 8.3
iOS - 10.3

> [MJSONWP] Encountered internal error running command: Error: Error while executing atom: Element does not exist in cache (status: 10)
>     at XCUITestDriver.callee$0$0$ (../../../lib/commands/web.js:78:11)
>     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
>     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
>     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
>     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
> Process node with port 59550 PID is: 32023
> Checking status of server: http://10.1.78.52:59550/wd/hub/status/
> Server Running: True
> Server with port: 59416 is not running
> Server with port: 59163 is not running
> Process node with port 59558 PID is: 21471
> Checking status of server: http://10.1.78.52:59558/wd/hub/status/
> Server Running: True
> Server with port: 59005 is not running
> Process node with port 59483 PID is: 20864
> Checking status of server: http://10.1.78.52:59483/wd/hub/status/
> Server Running: True
> [31/Mar/2017 11:19:13] "GET / HTTP/1.1" 200 3770
> [MJSONWP] Encountered internal error running command: Error: Error while executing atom: operation timed out
>     at XCUITestDriver.callee$0$0$ (../../../lib/commands/web.js:78:11)
>     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
>     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
>     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
>     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
> [MJSONWP] Encountered internal error running command: Error: Error while executing atom: Remote debugger is not connected
>     at XCUITestDriver.callee$0$0$ (../../../lib/commands/web.js:78:11)
>     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
>     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
>     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
>     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
>     at runMicrotasksCallback (internal/process/next_tick.js:58:5)
>     at _combinedTickCallback (internal/process/next_tick.js:67:7)
>     at process._tickCallback (internal/process/next_tick.js:98:9)
> [MJSONWP] Encountered internal error running command: Error: Error while executing atom: Remote debugger is not connected
>     at XCUITestDriver.callee$0$0$ (../../../lib/commands/web.js:78:11)
>     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
>     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
>     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
>     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
>     at runMicrotasksCallback (internal/process/next_tick.js:58:5)
>     at _combinedTickCallback (internal/process/next_tick.js:67:7)
>     at process._tickCallback (internal/process/next_tick.js:98:9)
> [MJSONWP] Encountered internal error running command: Error: Error while executing atom: Remote debugger is not connected
>     at XCUITestDriver.callee$0$0$ (../../../lib/commands/web.js:78:11)
>     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
>     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
>     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
>     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
>     at runMicrotasksCallback (internal/process/next_tick.js:58:5)
>     at _combinedTickCallback (internal/process/next_tick.js:67:7)
>     at process._tickCallback (internal/process/next_tick.js:98:9)
> [MJSONWP] Encountered internal error running command: Error: Error while executing atom: Remote debugger is not connected
>     at XCUITestDriver.callee$0$0$ (../../../lib/commands/web.js:78:11)
>     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
>     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
>     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
>     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
>     at runMicrotasksCallback (internal/process/next_tick.js:58:5)
>     at _combinedTickCallback (internal/process/next_tick.js:67:7)
>     at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by Zakyss** [comment]
Hey guys,

Unfortunately I'm facing the same issue. I'm running on a hybrid app where the test automatically switches to WEBVIEW. I'm unable to click or validate that a css element is there. Test was working perfectly before the move to XCUITest

appium 1.6.3
java 1.7
selenium-java-2.48.2 (updating to the latest 3.3.1 didn't fix the issue)
java-client-3.2.0 (updating to 5 beta6 didn't change anything)
running test on iOS iPad 9.3.4 using XCUITest (had no choice but to use XCUITest)
xcode:8.2.1

Log:

[HTTP] --> POST /wd/hub/session/5f74b0ed-5fda-42de-838d-d03bb4532a26/elements {"using":"css selector","value":".payee-list.am-scroller .title"}
[debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["css selector",".payee-list.am-scroller .title","5f74b0ed-5fda-42de-838d-d03bb4532a26"]
[debug] [XCUITest] Executing command 'findElements'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[MJSONWP] Encountered internal error running command: Error: Error while executing atom: Unable to load Atom 'find_elements' from file '/usr/local/lib/node_modules/appium/node_modules/appium-remote-debugger/atoms/find_elements.js'
    at XCUITestDriver.callee$0$0$ (../../../lib/commands/web.js:75:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)

//////////////////////////////////////////

any suggestions ?

**Comment by Icaroto** [comment]
Hi guys, a update from my side. 

Seems the issue I'm having is due the first WebView hanging when I came back from the native app.
So, once I reach the WebView for the second time, I can see (trough Safari develop menu) that there are 2 WebViews available. One is the current page and the other one is the login page hanging. 

Thing is, when I switch back to WebView , Appium is choosing the one that is not supposed to be there anymore (The login WebView ), therefore the driver crashes as it can't interact with anything there.

On Android I was able to workaround that by using the WindowHandles (Find how many windows are open, switch to the latest) but for iOS, even with 2 WebViews, the WindowHandles only sees one.

I think is something similar to: https://github.com/appium/appium/issues/5180

Is there any way to work around that?

Thanks!

**Comment by shaunshaun777** [comment]
same issue, any workaroud?

**Comment by imurchie** [comment]
We have added a capability `webkitResponseTimeout` to configure the length of time that Appium will wait for something to come back with a response. You can get the latest of Appium (`npm uninstall -g appium && npm install -g appium@beta`) to get this, and try making it longer.

**Comment by Icaroto** [comment]
@imurchie  but would that work, even if appium is targeting the "wrong" webview? From what I could see, on Android I can use the "recreateChromeSession" capability, which recreates the driver when I switch the context, not the right way but it is a workaround. Is there anything like that for iOS? Will have a go anyway :)

(my previous assumption was wrong, the switch window didnt work on Android. it was the fact that after coming back from native app, it recreates the driver and it target the correct webview)

Thanks

**Comment by abhilashcae** [comment]
Hi @imurchie  - I'm also facing this issue but on trying to switch to webview for the first time itself. Here are the logs: https://gist.github.com/abhilashcae/bad67be446f467306047ba30edee21ab (the error is almost at the end of the logs).

**Comment by jlipps** [comment]
@Icaroto I hear you saying Appium is picking the "wrong" webview. When you get the list of contexts, do you see the "right" webview there as well? How are you setting the context?

**Comment by Icaroto** [comment]
@jlipps 
So, I set the Webview on the login page by doing:
`driver.Context = "WEBVIEW"`
After login, I switch to NATIVE_APP using the same method and then same method again to return to Webview.

By looking into "chrome://inspect" I can see that I have two "items" inside my Webview:

![image](https://user-images.githubusercontent.com/4673110/28583984-02c9c0e2-7163-11e7-9cae-61943e253559.png)

From the Url of the "untitled" item, I can see it refers to the authentication of the login page.

My "guess" is that Appium tries to send a command to this first item in the list, which is a Webview "hanging" from the login page. Does it make sense?

Then, comes the tricky part:
Android: Sometimes, I can switchWindows to interact with the second item in the list. Some other times, the windows count returns always 1.
iOS: The windows count always returns 1, so I can even try to switch to that second item. 

(Sorry if I cut it out too much from the image, let me know if something is missing)

**Comment by jlipps** [comment]
@Icaroto what do you get when you call the `GET /contexts` command? Not sure what it is in your driver. Maybe driver.Contexts? We need to know what _Appium_ thinks exists, not what the chrome inspector thinks exists.

**Comment by Icaroto** [comment]
@jlipps  Sorry, I should have specified this in the beginning.

Using Driver.Contexts appium returns NATIVE_APP and a single WEBVIEW.

**Comment by jlipps** [comment]
Hmm, I'm not sure if there's anything we can do then... It seems like according to Chromedriver there is only one webview for us to attach to. Next thought: what if you run chromedriver on its own, outside of Appium. Are you able to connect to both views?

**Comment by dpgraham** [comment]
Closing due to inactivity. Let me know if you have an update on this and we can re-open.
