### ISSUE TITLE
uiautomator2: isKeyboardShown not implemented

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium#7984]
## The problem

Appium: 1.6.4-beta
Java-client: 5.0.0-BETA4

```
((AndroidDriver) driver).isKeyboardShown()
->
[HTTP] --> GET /wd/hub/session/7ff36ae8-63a1-4631-b463-a8da84b7383e/appium/device/is_keyboard_shown {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/7ff36ae8-63a1-4631-b463-a8da84b7383e/appium/device/is_keyboard_shown] to [GET http://localhost:8201/wd/hub/session/a9ef25b2-6a35-4874-b05b-fb44fc62a8ee/appium/device/is_keyboard_shown] with body: {}
[MJSONWP] Encountered internal error running command: Error: Could not proxy. Proxy error: Unexpected end of JSON input
    at doJwpProxy$ (../../../lib/mjsonwp/mjsonwp.js:343:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- GET /wd/hub/session/7ff36ae8-63a1-4631-b463-a8da84b7383e/appium/device/is_keyboard_shown 500 40 ms - 229 
```

**Comment by sravanmedarapu** [comment]
@amedvedjev, using appium-uiautomator2-driver v0.3.1 should fix this.
