### ISSUE TITLE
Encountered internal error running command, while clicking an element

### ISSUE THREAD

**Issue by pavanbachu0604** [appium/appium#7992]
Device OS : iOS 10.3 Beta 4
Appium : 1.6.4 Beta

Not able to click a particular element in Hybrid Application on Particular Page

Please find the Gist https://gist.github.com/pavanbachu0604/9ed6205464f4364ac33061c5640e24c6

```
Encountered internal error running command: Error: Error while executing atom: operation timed out
    at XCUITestDriver.callee$0$0$ (../../../lib/commands/web.js:75:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
```

**Comment by dpgraham** [comment]
Can you provide Appium server logs?

**Comment by pavanbachu0604** [comment]
I have updated, please find the gist file

**Comment by dpgraham** [comment]
Before you call findElement, can you try calling `getPageSource()` (if you're using the Java client) and just confirm that `//XCUIElementTypeButton[@name='Skip']` exists in the source

**Comment by pavanbachu0604** [comment]
Why do u want to test //XCUIElementTypeButton[@name='Skip'] ? The issue is with (.//*[@name='transferService'])[2] button right ?

**Comment by dpgraham** [comment]
Yeah, I misread the logs. 

Can you confirm that you have ios_webkit_debug_proxy installed?

https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/ios-webkit-debug-proxy.md

**Comment by pavanbachu0604** [comment]
Yeah, ios-webkit-debug-proxy is installed and version is 1.7.1

**Comment by dpgraham** [comment]
@pavanbachu0604 Can you check your node_modules and let me know which version of `appium-ios-driver` is installed?

@imurchie @jlipps 

https://github.com/appium/appium/issues/7977 is having a similar problem.

This looks similar to https://github.com/appium/appium/issues/6367 (which was submitted last April).

**Comment by jlipps** [comment]
closing, no response
