### ISSUE TITLE
Method has not yet been implemented

### ISSUE THREAD

**Issue by ccangle** [appium/appium#7993]
## The problem

I have used the appium to test chrome browser on android device。

here is the DesiredCapabilities i have set:
    platformName  :Android
    deviceName     :
    udid                  :
    browserName  :Chrome
    appPackage     :com.android.chrome
    appActivity       :com.google.android.apps.chrome.Main
    newCommandTimeout:999999

use the DesiredCappabilities above, when executing the the method "perform" of class "TouchAction" , i always get the the error "Method has not yet been implemented"

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.0
* Last Appium version that did not exhibit the issue (if applicable):not yet
* Desktop OS/version used to run Appium: Win7 64bit
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android:4.4.2
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: Appium CLI 

## Details

when executing the the method "perform" of class "TouchAction" , i always get the the error "Method has not yet been implemented", below is the error detail:

org.openqa.selenium.WebDriverException: Method has not yet been implemented (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 9 milliseconds
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: 'G08XCC02', ip: '10.167.18.162', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_80'
Session ID: 935aec90-9597-4269-9cb8-c8f794a6ffea
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{platform=LINUX, javascriptEnabled=true, appActivity=com.google.android.apps.chrome.Main, browserName=Chrome, deviceModel=HUAWEI C199, networkConnectionEnabled=true, udid=68a0f6ba38cf, desired={newCommandTimeout=999999, deviceName=68a0f6ba38cf, platformName=Android, appActivity=com.google.android.apps.chrome.Main, browserName=Chrome, udid=68a0f6ba38cf, appPackage=com.android.chrome}, locationContextEnabled=false, deviceUDID=68a0f6ba38cf, appPackage=com.android.chrome, newCommandTimeout=999999, platformVersion=4.4.2, databaseEnabled=false, deviceScreenSize=720x1280, platformName=Android, deviceName=68a0f6ba38cf, deviceManufacturer=HUAWEI, webStorageEnabled=false, warnings={}, takesScreenshot=true}]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:40)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at io.appium.java_client.AppiumDriver.performTouchAction(AppiumDriver.java:336)
	at io.appium.java_client.TouchAction.perform(TouchAction.java:323)
	at script.WebScriptAction.doScriptActionWeb(WebScriptAction.java:230)
	at appium.AppiumWeb.message(AppiumWeb.java:107)
	at config.Config.executeWeb(Config.java:126)
	at socket.CreateSocket.CreateSockets(CreateSocket.java:90)
	at Main.main(Main.java:15)

**Comment by vikramvi** [comment]
Issue still exists with latest versions of Java Client and Appium Server

**Comment by vikramvi** [comment]
False alarm from my side, worked after setting context back to native app from chrome browser

@ccangle  please refer to https://discuss.appium.io/t/touchaction-perform-method-has-not-yet-been-implemented/14922/11 and close if it works in your case as well.

**Comment by ccangle** [comment]
@vikramvi 
I have tried what you told me, but there is still problems.
As you have said, on the condition i setting context back to native app from chrome browser, and when the  
"perform" method is executed, then there has the error "can't find the element".(but before the "perform" method executed, "findElement" method has been successfully executed)

**Comment by imurchie** [comment]
Any element you've found in a webview context will _not_ be available in the native context, without re-finding it.

**Comment by imurchie** [comment]
Closing due to inactivity.

**Comment by surajsalunkhe** [comment]
I am also facing the same issue on android device. I used TestNG for execution. At the end of test it is throwing error.
After test execution it is throwing error . 

org.openqa.selenium.NoSuchSessionException: A session is either terminated or not started (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.9.0', revision: '698b3178f0', time: '2018-02-05T14:26:55.441Z'
System info: host: 'surajs-MacBook-Pro.local', ip: 'fe80:0:0:0:1095:4a9a:a69:103f%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_101'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {app: /Users/suraj/repo/ebayAndro..., appActivity: com.ebay.mobile.activities...., appPackage: com.ebay.mobile, appWaitActivity: com.ebay.mobile.activities...., appWaitPackage: com.ebay.mobile, databaseEnabled: false, desired: {app: /Users/suraj/repo/ebayAndro..., appActivity: com.ebay.mobile.activities...., appWaitActivity: com.ebay.mobile.activities...., deviceName: ce071717b4c1de3d04, newCommandTimeout: 10000, package: com.ebay.mobile, platformName: Android}, deviceManufacturer: samsung, deviceModel: SM-G950F, deviceName: ce071717b4c1de3d04, deviceScreenSize: 1440x2960, deviceUDID: ce071717b4c1de3d04, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, newCommandTimeout: 10000, package: com.ebay.mobile, platform: LINUX, platformName: LINUX, platformVersion: 7.0, takesScreenshot: true, warnings: {}, webStorageEnabled: false}
Session ID: a27b9c3f-c260-4585-8a67-c52b3e82d022

**Comment by imurchie** [comment]
@surajsalunkhe If indeed this is the same problem, the information you've provided is not enough to do anything with.

Please attach the _full_ Appium server logs as a link to a [gist](https://gist.github.com) if you want us to be able to do anything.

**Comment by ferreirasouza** [comment]
Try like this...
I'm not sure that will work for you...
 
public boolean tapElement(int x, int y) {
        System.out.println("tapElement is starting");
        System.out.println("Context: " + driver.getContext());
        driver.context("NATIVE_APP");
        System.out.println("Context: " + driver.getContext());
        try {
            new TouchAction((MobileDriver) driver).tap(x, y).perform();
            driver.context("CHROMIUM");
            System.out.println("Context: " + driver.getContext());
            System.out.println("tapElement is finished");
            return true;
        } catch (Exception e) {
            e.printStackTrace();
            driver.context("CHROMIUM");
            System.out.println("Context: " + driver.getContext());
            System.out.println("tapElement is finishing in exception...");
            return false;
        }
    }

**Comment by LyubomirStoimchev** [comment]
Got the same problem while trying to interact with web elements. The way I solve it was to use the capability 'nativeWebTap'.
