### ISSUE TITLE
Unable to launch WebDriverAgent because of xcodebuild failure

### ISSUE THREAD

**Issue by bhamilton80** [appium/appium#8008]
## [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1

Appium inspector won't launch. The following error is displayed in terminal: 
[XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1

## Environment

* Appium version (or git revision) that exhibits the issue: v1.6.4-beta
* Desktop OS/version used to run Appium: Mac OSX
* Mobile platform/version under test: iPhone
* Real device or emulator/simulator: simulator

## Appium logs
````
[Appium] Welcome to Appium v1.6.4-beta
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.4-beta","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 19 ms - 88 
[HTTP] --> GET /wd/hub/sessions {}
[debug] [MJSONWP] Calling AppiumDriver.getSessions() with args: []
[debug] [MJSONWP] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 2 ms - 40 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"iOS","platformVersion":"10.2","newCommandTimeout":"7200","app":"/Users/bhamilton/appium/UICatalog.app.zip","automationName":"Appium","deviceName":"iPhone 7"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"iOS","platformVersion":"10.2","newCommandTimeout":"7200","app":"/Users/bhamilton/appium/UICatalog.app.zip","automationName":"Appium","deviceName":"iPhone 7"},null,null,null,null]
[Appium] Requested iOS support with version >= 10, using XCUITest driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
[Appium] Creating new XCUITestDriver (v2.9.0) session
[Appium] Capabilities:
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '10.2'
[Appium]   newCommandTimeout: '7200'
[Appium]   app: '/Users/bhamilton/appium/UICatalog.app.zip'
[Appium]   automationName: 'Appium'
[Appium]   deviceName: 'iPhone 7'
[debug] [XCUITest] XCUITestDriver version: 2.9.0
[BaseDriver] Capability 'newCommandTimeout' changed from string ('7200') to integer (7200). This may cause unexpected behavior
[BaseDriver] Session created with session id: d3334e50-7322-460a-9d07-296b6bdd6870
[debug] [XCUITest] Xcode version set to '8.2.1'
[debug] [XCUITest] iOS SDK Version set to '10.2'
[iOSSim] Constructing iOS simulator for Xcode version 8.2.1 with udid '39ED8DB4-DEEC-4AD8-969C-C2A158DE73A3'
[XCUITest] Determining device to run tests on: udid: '39ED8DB4-DEEC-4AD8-969C-C2A158DE73A3', real device: false
[BaseDriver] Using local app '/Users/bhamilton/appium/UICatalog.app.zip'
[debug] [BaseDriver] Copying local zip to tmp dir
[debug] [BaseDriver] Unzipping /var/folders/z1/ztzd23ld19jgwcsztw45srpc0000gn/T/201728-60155-t8a74q.lg73545cdi/appium-app.zip
[debug] [BaseDriver] Testing zip archive: /var/folders/z1/ztzd23ld19jgwcsztw45srpc0000gn/T/201728-60155-t8a74q.lg73545cdi/appium-app.zip
[BaseDriver] Unzipped local app to '/var/folders/z1/ztzd23ld19jgwcsztw45srpc0000gn/T/201728-60155-t8a74q.lg73545cdi/UICatalog.app'
[debug] [XCUITest] Checking whether app '/var/folders/z1/ztzd23ld19jgwcsztw45srpc0000gn/T/201728-60155-t8a74q.lg73545cdi/UICatalog.app' is actually present on file system
[debug] [XCUITest] App is present
[debug] [iOS] Getting bundle ID from app '/var/folders/z1/ztzd23ld19jgwcsztw45srpc0000gn/T/201728-60155-t8a74q.lg73545cdi/UICatalog.app': 'com.example.apple-samplecode.UICatalog'
[XCUITest] Not scrubbing third party app in anticipation of uninstall
[debug] [iOSLog] Starting iOS 10.2 simulator log capture
[debug] [iOSLog] System log path: /Users/bhamilton/Library/Logs/CoreSimulator/39ED8DB4-DEEC-4AD8-969C-C2A158DE73A3/system.log
[XCUITest] Setting up simulator
[debug] [iOS] No reason to set locale
[debug] [iOS] No iOS / app preferences to set
[debug] [XCUITest] Reset requested. Removing app with id 'com.example.apple-samplecode.UICatalog' from the device
[XCUITest] Simulator with udid '39ED8DB4-DEEC-4AD8-969C-C2A158DE73A3' already booted
[debug] [XCUITest] Installing /var/folders/z1/ztzd23ld19jgwcsztw45srpc0000gn/T/201728-60155-t8a74q.lg73545cdi/UICatalog.app on Simulator with UUID '39ED8DB4-DEEC-4AD8-969C-C2A158DE73A3'...
[debug] [XCUITest] The app has been installed successfully.
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Running WebDriverAgent bootstrap script to install dependencies
[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1
[debug] [XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[debug] [XCUITest] Removing WDA application from device
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Running WebDriverAgent bootstrap script to install dependencies
[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1
[debug] [XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[debug] [XCUITest] Removing WDA application from device
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:331:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: Unable to launch WebDriverAgent because of xcodebuild failure: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:331:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:331:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)

````

**Comment by mykola-mokhnach** [comment]
Do you have carthage installed and available in PATH?

**Comment by bhamilton80** [comment]
It is installed, but I am not sure if it is available in PATH
[XCUITest] Carthage found: '/usr/local/bin/carthage'

**Comment by imurchie** [comment]
If you update Appium to the latest You should get a more informative error message from this (i.e., https://github.com/appium/appium-xcuitest-driver/commit/4abeb98274bda97d4a90243a4f909aaa70b2ccd3).

**Comment by mykola-mokhnach** [comment]
It might be wrong package with similar name
what is the output of 

```
bash -x Scripts/bootstrap.sh -d
```

the command should be executed from the folder where WDA is located (usually
/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent)

**Comment by bhamilton80** [comment]
Well, this is new:
Brians-MBP:~ bhamilton$ npm update -g appium

> appium@1.6.4-beta prepublish /Users/bhamilton/appium
> gulp prepublish

[14:42:34] Using gulpfile ~/appium/gulpfile.js
[14:42:34] Starting 'prepublish'...
[14:42:34] Starting 'clean'...
[14:42:34] Finished 'clean' after 29 ms
[14:42:34] Starting 'transpile'...
[14:42:36] Finished 'transpile' after 1.82 s
[14:42:36] Starting 'fixShrinkwrap'...
Could not find shrinkwrap; skipping fixing shrinkwrap. (Original error: Cannot find module './npm-shrinkwrap.json')

**Comment by bhamilton80** [comment]
Is this the best way to update appium? 

npm update -g appium

**Comment by imurchie** [comment]
I would do `npm uninstall -g appium && npm install -g appium@beta`

**Comment by bhamilton80** [comment]
Same error after uninstall/reinstall:
Error: Unable to launch WebDriverAgent because of xcodebuild failure: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1

**Comment by imurchie** [comment]
What are the full logs?

**Comment by bhamilton80** [comment]
```
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.4-beta","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 17 ms - 88 
[HTTP] --> GET /wd/hub/sessions {}
[debug] [MJSONWP] Calling AppiumDriver.getSessions() with args: []
[debug] [MJSONWP] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 2 ms - 40 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"iOS","platformVersion":"10.2","newCommandTimeout":"7200","app":"/Users/bhamilton/appium/UICatalog.app.zip","automationName":"Appium","deviceName":"iPhone 7"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"iOS","platformVersion":"10.2","newCommandTimeout":"7200","app":"/Users/bhamilton/appium/UICatalog.app.zip","automationName":"Appium","deviceName":"iPhone 7"},null,null,null,null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1489006677514 (14:57:57 GMT-0600 (CST))
[Appium] Requested iOS support with version >= 10, using XCUITest driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
[Appium] Creating new XCUITestDriver (v2.15.0) session
[Appium] Capabilities:
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '10.2'
[Appium]   newCommandTimeout: '7200'
[Appium]   app: '/Users/bhamilton/appium/UICatalog.app.zip'
[Appium]   automationName: 'Appium'
[Appium]   deviceName: 'iPhone 7'
[debug] [XCUITest] XCUITestDriver version: 2.15.0
[BaseDriver] Capability 'newCommandTimeout' changed from string ('7200') to integer (7200). This may cause unexpected behavior
[BaseDriver] Session created with session id: 6daa9831-3a89-460e-aca8-be007c4c047c
[debug] [XCUITest] Xcode version set to '8.2.1' (tools v8.2.0.0.1.1480973914)
[debug] [XCUITest] iOS SDK Version set to '10.2'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1489006677662 (14:57:57 GMT-0600 (CST))
[iOSSim] Constructing iOS simulator for Xcode version 8.2.1 with udid '39ED8DB4-DEEC-4AD8-969C-C2A158DE73A3'
[XCUITest] Determining device to run tests on: udid: '39ED8DB4-DEEC-4AD8-969C-C2A158DE73A3', real device: false
[BaseDriver] Using local app '/Users/bhamilton/appium/UICatalog.app.zip'
[debug] [BaseDriver] Copying local zip to tmp dir
[debug] [BaseDriver] Unzipping /var/folders/z1/ztzd23ld19jgwcsztw45srpc0000gn/T/201728-60831-1dv0on9.lswrbpgb9/appium-app.zip
[debug] [BaseDriver] Testing zip archive: /var/folders/z1/ztzd23ld19jgwcsztw45srpc0000gn/T/201728-60831-1dv0on9.lswrbpgb9/appium-app.zip
[BaseDriver] Unzipped local app to '/var/folders/z1/ztzd23ld19jgwcsztw45srpc0000gn/T/201728-60831-1dv0on9.lswrbpgb9/UICatalog.app'
[debug] [BaseDriver] Event 'appConfigured' logged at 1489006677885 (14:57:57 GMT-0600 (CST))
[debug] [XCUITest] Checking whether app '/var/folders/z1/ztzd23ld19jgwcsztw45srpc0000gn/T/201728-60831-1dv0on9.lswrbpgb9/UICatalog.app' is actually present on file system
[debug] [XCUITest] App is present
[debug] [iOS] Getting bundle ID from app '/var/folders/z1/ztzd23ld19jgwcsztw45srpc0000gn/T/201728-60831-1dv0on9.lswrbpgb9/UICatalog.app': 'com.example.apple-samplecode.UICatalog'
[debug] [BaseDriver] Event 'resetStarted' logged at 1489006677890 (14:57:57 GMT-0600 (CST))
[XCUITest] Not scrubbing third party app in anticipation of uninstall
[debug] [BaseDriver] Event 'resetComplete' logged at 1489006678045 (14:57:58 GMT-0600 (CST))
[debug] [iOSLog] Starting iOS 10.2 simulator log capture
[debug] [iOSLog] System log path: /Users/bhamilton/Library/Logs/CoreSimulator/39ED8DB4-DEEC-4AD8-969C-C2A158DE73A3/system.log
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1489006678139 (14:57:58 GMT-0600 (CST))
[XCUITest] Setting up simulator
[debug] [iOS] No reason to set locale
[debug] [iOS] No iOS / app preferences to set
[XCUITest] Simulator with udid '39ED8DB4-DEEC-4AD8-969C-C2A158DE73A3' already booted
[debug] [BaseDriver] Event 'simStarted' logged at 1489006678300 (14:57:58 GMT-0600 (CST))
[debug] [XCUITest] Reset requested. Removing app with id 'com.example.apple-samplecode.UICatalog' from the device
[debug] [XCUITest] Installing /var/folders/z1/ztzd23ld19jgwcsztw45srpc0000gn/T/201728-60831-1dv0on9.lswrbpgb9/UICatalog.app on Simulator with UUID '39ED8DB4-DEEC-4AD8-969C-C2A158DE73A3'...
[debug] [XCUITest] The app has been installed successfully.
[debug] [BaseDriver] Event 'appInstalled' logged at 1489006683184 (14:58:03 GMT-0600 (CST))
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1489006683186 (14:58:03 GMT-0600 (CST))
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Running WebDriverAgent bootstrap script to install dependencies
[XCUITest] Fetching dependencies
[XCUITest] *** Downloading peertalk.framework binary at "v1.0"
[XCUITest] *** Skipped installing peertalk.framework binary due to the error:
[XCUITest] 	"Failed to write to /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/iOS: Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “iOS” in the folder “Build”." UserInfo={NSFilePath=/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/iOS, NSUnderlyingError=0x7f8281cb6680 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}}"
[XCUITest] *** Checking out peertalk at "v1.0"
[XCUITest] Failed to check out repository into /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/peertalk: Could not create working directory (Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “peertalk” in the folder “Checkouts”." UserInfo={NSFilePath=/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/peertalk, NSUnderlyingError=0x7f8281c91770 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}})
[debug] [BaseDriver] Event 'wdaStartFailed' logged at 1489006684296 (14:58:04 GMT-0600 (CST))
[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1
[debug] [XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[debug] [XCUITest] Removing WDA application from device
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1489006694440 (14:58:14 GMT-0600 (CST))
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Running WebDriverAgent bootstrap script to install dependencies
[XCUITest] Fetching dependencies
[XCUITest] *** Downloading peertalk.framework binary at "v1.0"
[XCUITest] *** Skipped installing peertalk.framework binary due to the error:
[XCUITest] 	"Failed to write to /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/iOS: Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “iOS” in the folder “Build”." UserInfo={NSFilePath=/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/iOS, NSUnderlyingError=0x7f97d0d8f560 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}}"
[XCUITest] *** Checking out peertalk at "v1.0"
[XCUITest] Failed to check out repository into /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/peertalk: Could not create working directory (Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “peertalk” in the folder “Checkouts”." UserInfo={NSFilePath=/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/peertalk, NSUnderlyingError=0x7f97d0e521b0 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}})
[debug] [BaseDriver] Event 'wdaStartFailed' logged at 1489006695289 (14:58:15 GMT-0600 (CST))
[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1
[debug] [XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[debug] [XCUITest] Removing WDA application from device
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:349:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: Unable to launch WebDriverAgent because of xcodebuild failure: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:349:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:349:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by imurchie** [comment]
"Failed to write to /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/iOS: Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “iOS” in the folder “Build”." UserInfo={NSFilePath=/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/iOS, NSUnderlyingError=0x7f97d0d8f560 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}}"

**Comment by bhamilton80** [comment]
Thank you so much for your help! 
How can I give that permission?

**Comment by imurchie** [comment]
You can use `chown -R <user>:  /usr/local/lib/node_modules`. Might need to use `sudo`.

**Comment by bhamilton80** [comment]
THANK YOU!!! That did it.

**Comment by imurchie** [comment]
Excellent!
