### ISSUE TITLE
android command line tool is no longer available

### ISSUE THREAD

**Issue by chenchaoyi** [appium/appium#8017]
As of Android SDK Tools, Revision 25.3.0, `android` command line tool has been removed, which breaks the current Appium android emulator functionality:

```
[Appium] Welcome to Appium v1.6.3 (REV 685098aca91c599b8f2546857f5da5346f550ca4)
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"appiumVersion":"1.6.3","locale":"en-US","platformName":"Android","platformVersion":"7.1","deviceName":"Android Emulator","avd":"Pixel","sendKeyStrategy":"setValue","app":"./app/debug.apk"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"appiumVersion":"1.6.3","locale":"en-US","platformName":"Android","platformVersion":"7.1","deviceName":"Android Emulator","avd":"Pixel","sendKeyStrategy":"setValue","app":"./app/debug.apk"},null,null,null,null]
[Appium] Creating new AndroidDriver session
[Appium] Capabilities:
[Appium]   appiumVersion: '1.6.3'
[Appium]   locale: 'en-US'
[Appium]   platformName: 'Android'
[Appium]   platformVersion: '7.1'
[Appium]   deviceName: 'Android Emulator'
[Appium]   avd: 'Pixel'
[Appium]   sendKeyStrategy: 'setValue'
[Appium]   app: './app/debug.apk'
[debug] [AndroidDriver] AndroidDriver version: 1.10.38
[BaseDriver] The following capabilities were provided, but are not recognized by appium: appiumVersion, sendKeyStrategy.
[BaseDriver] Session created with session id: edd95154-1095-4e1a-8284-b6bf36ff94d3
[debug] [AndroidDriver] Getting Java version
[AndroidDriver] Java version is: 1.8.0_71
[ADB] Checking whether adb is present
[ADB] Using adb from /Users/test/Library/Android/sdk/platform-tools/adb
[debug] [ADB] Trying to find Pixel emulator
[debug] [ADB] Getting connected emulators
[debug] [ADB] Getting connected devices...
[debug] [ADB] 0 device(s) connected
[debug] [ADB] 0 emulator(s) connected
[debug] [ADB] Emulator Pixel not running
[debug] [ADB] Launching Emulator with AVD Pixel, launchTimeout60000 ms and readyTimeout 60000 ms
[ADB] Checking whether emulator is present
[ADB] Using emulator from /Users/test/Library/Android/sdk/tools/emulator
[ADB] Checking whether android is present
[ADB] Using android from /Users/test/Library/Android/sdk/tools/android
[debug] [AndroidDriver] Shutting down Android driver
[debug] [AndroidDriver] Called deleteSession but bootstrap wasn't active
[MJSONWP] Encountered internal error running command: Error: Command '/Users/test/Library/Android/sdk/tools/android list avd -c' exited with code 1
    at ChildProcess.<anonymous> (../../lib/teen_process.js:66:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
[HTTP] <-- POST /wd/hub/session 500 177 ms - 226
[HTTP] --> DELETE /wd/hub/session/null {}
[HTTP] <-- DELETE /wd/hub/session/null 404 3 ms - 99
```

Any plan to support this breaking change?

**Comment by dpgraham** [comment]
Thanks for notifying us about this breaking change. I imagine this is something that's a pretty high priority fix.

Do you happen to know what they've replaced it with?

**Comment by dpgraham** [comment]
@chenchaoyi Does it happen on v1.6.4-beta?

**Comment by chenchaoyi** [comment]
@dpgraham according to this, it has been replace by sdkmanager and avdmanager:
```
/Users/test/Library/Android/sdk/tools/android --version
The android command is no longer available.
For manual SDK and AVD management, please use Android Studio.
For command-line tools, use tools/bin/sdkmanager and tools/bin/avdmanager
```

**Comment by chenchaoyi** [comment]
Thankfully 1.6.4beta works. Any hold up on making it an official release ? : )

**Comment by dpgraham** [comment]
Great. Glad to hear it works!

No, there's no showstoppers holding up the release. We're working on deploying it right now.

**Comment by claytonneal** [comment]
is that released?

**Comment by a442509097** [comment]
and in android studio doc is always "Fetching Documentation..." , Is it related to this? I find API 25 not offline doc, just API 24 have...

**Comment by Jonothan-Ho** [comment]
How to solve the problem？

**Comment by mrbfrank** [comment]
I hit this issue as well. Fixed by downgrading to older version of android-sdk.. though I had to publish a Homebrew tap to do so. Hope this helps everyone:
https://github.com/mrbfrank/homebrew-android-sdk-24
`https://github.com/mrbfrank/homebrew-android-sdk-24`
