### ISSUE TITLE
[XCUITest] Error: Command 'idevice_id -l' errored out: Error: spawn idevice_id ENOENT

### ISSUE THREAD

**Issue by sglebs** [appium/appium#8031]
## The problem

Exception trying to test IPA on real device (iOS 10.2, iPhone 7)

## Environment

 * Appium.app 1.5.3 but pointing at external Appium, 1.6.3
 * iPhone 7, iOS 10.2
 * Desktop = MacOS

## Details

Exception when trying real device

```
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"automationName":"XCUITest"},{},null,null,null]
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:

[Appium]   automationName: 'XCUITest'
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '10.2'
[Appium]   deviceName: 'iPhone 6'
[Appium]   app: '/Users/mqm/git/nexxera-robot/WithSphinxRst/source/MobileWallet/Wallet-HML-001.ipa'
[Appium]   udid: '4d5c3588977baa98e737778f15f2f97442e12425'
[Appium]   showIOSLog: true
[debug] [XCUITest] XCUITestDriver version: 2.4.2
[BaseDriver] Session created with session id: 95ba08f0-ef39-42be-ab4a-a00a82a85c17

[debug] [XCUITest] Xcode version set to '8.2.1'

[debug] [XCUITest] iOS SDK Version set to '10.2'

[XCUITest] Error: Command 'idevice_id -l' errored out: Error: spawn idevice_id ENOENT
    at exports._errnoException (util.js:1036:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at ChildProcess.<anonymous> (../../lib/teen_process.js:32:14)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
 Error: Command 'idevice_id -l' errored out: Error: spawn idevice_id ENOENT
    at exports._errnoException (util.js:1036:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at ChildProcess.<anonymous> (../../lib/teen_process.js:32:14)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

[debug] [XCUITest] Running iOS simulator reset flow

[MJSONWP] Encountered internal error running command: Error: Command 'idevice_id -l' errored out: Error: spawn idevice_id ENOENT
    at exports._errnoException (util.js:1036:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at ChildProcess.<anonymous> (../../lib/teen_process.js:32:14)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

[HTTP] <-- POST /wd/hub/session 500 273 ms - 521 

```

## Code To Reproduce Issue [ Good To Have ]

```
*** Settings ***
Library     AppiumLibrary
Suite Teardown  Close Application


*** Test Cases ***

Simple Smoke Test
    Open Application   http://localhost:4723/wd/hub    automationName=XCUITest
    Wait Until Page Contains Element    id=com.nexxera.nix:id/btn_register_exist_user   timeout=180
    Tap    id=com.nexxera.nix:id/btn_register_exist_user
    Wait Until Page Contains Element    id=com.nexxera.nix:id/til_cpf   timeout=180
    Capture Page Screenshot
```

**Comment by sglebs** [comment]
For the record, I did set the UDID in the Appium.app UI and enabled the checkbox. I uncheck it if I want to test in the emulator.

**Comment by sglebs** [comment]
advice_id seems to be installed with https://github.com/libimobiledevice/ideviceinstaller from what I Googled. But "brew install" of external Appium did not install this. Maybe this is the root cause?

**Comment by imurchie** [comment]
Not sure what you mena by `But "brew install" of external Appium did not install this`. To get libimobiledevice, install with `brew install libimobiledevice` (it is sometimes necessary to use `brew install libimobiledevice --HEAD` to get the latest).

**Comment by sglebs** [comment]
Right, I had to install it manually. The next drag is the need to install iso-deploy (brew install ios-deploy) manually. But this ticket can be closed then.
