### ISSUE TITLE
Middle of Automation Run : Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSE

### ISSUE THREAD

**Issue by SatishKumarKV** [appium/appium#8036]
## The problem

Middle of Automation Run : Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSE

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe: 1.6.3

## Details

I am running around 200 scripts in a testNG suite. Seeing above error somewhere in between the run and execution is incomplete and rest of all scripts will fail.

## Link to Appium logs

Trying on identifier DocsIBMConnections_MyFolders_Name with value : My Folders
Timeout on element : 1

[HTTP] --> POST /wd/hub/session/6a6eda33-c5e3-4a85-b8cf-2ff96b1bd424/elements {"using":"name","value":"My Folders"}
[debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["name","My Folders","6a6eda33-c5e3-4a85-b8cf-2ff96b1bd424"]
[debug] [XCUITest] Executing command 'findElements'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8418/session/4FC9BA0A-6633-4A35-A6B1-26A41BBD369A/elements] with body: {"using":"name","value":"My Folders"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":[{"ELEMENT":"E329D62C-C698-4916-8AE0-C608578AE5CC","type":"XCUIElementTypeStaticText","label":"My Folders"}],"sessionId":"4FC9BA0A-6633-4A35-A6B1-26A41BBD369A","status":0}
[debug] [MJSONWP] Responding to client with driver.findElements() result: [{"ELEMENT":"E329D62C-C698-4916-8AE0-C608578AE5CC","type":"XCUIElementTypeStaticText","label":"My Folders"}]
[HTTP] <-- POST /wd/hub/session/6a6eda33-c5e3-4a85-b8cf-2ff96b1bd424/elements 200 1212 ms - 180 
Size of found elements 1
[HTTP] --> GET /wd/hub/session/6a6eda33-c5e3-4a85-b8cf-2ff96b1bd424/element/E329D62C-C698-4916-8AE0-C608578AE5CC/displayed {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/6a6eda33-c5e3-4a85-b8cf-2ff96b1bd424/element/E329D62C-C698-4916-8AE0-C608578AE5CC/displayed] to [GET http://localhost:8418/session/4FC9BA0A-6633-4A35-A6B1-26A41BBD369A/element/E329D62C-C698-4916-8AE0-C608578AE5CC/displayed] with body: {}
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : true,\n  \"sessionId\" : \"4FC9BA0A-6633-4A35-A6B1-26A41BBD369A\",\n  \"status\" : 0\n}"
[JSONWP Proxy] Replacing sessionId 4FC9BA0A-6633-4A35-A6B1-26A41BBD369A with 6a6eda33-c5e3-4a85-b8cf-2ff96b1bd424
[HTTP] <-- GET /wd/hub/session/6a6eda33-c5e3-4a85-b8cf-2ff96b1bd424/element/E329D62C-C698-4916-8AE0-C608578AE5CC/displayed 200 570 ms - 76 
Size of found elements true
[HTTP] --> POST /wd/hub/session/6a6eda33-c5e3-4a85-b8cf-2ff96b1bd424/element/E329D62C-C698-4916-8AE0-C608578AE5CC/click {"id":"E329D62C-C698-4916-8AE0-C608578AE5CC"}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/6a6eda33-c5e3-4a85-b8cf-2ff96b1bd424/element/E329D62C-C698-4916-8AE0-C608578AE5CC/click] to [POST http://localhost:8418/session/4FC9BA0A-6633-4A35-A6B1-26A41BBD369A/element/E329D62C-C698-4916-8AE0-C608578AE5CC/click] with body: {"id":"E329D62C-C698-4916-8AE0-C608578AE5CC"}
[debug] [JSONWP Proxy] Got response with status 200: {"status":0,"id":"E329D62C-C698-4916-8AE0-C608578AE5CC","value":"","sessionId":"4FC9BA0A-6633-4A35-A6B1-26A41BBD369A"}
[JSONWP Proxy] Replacing sessionId 4FC9BA0A-6633-4A35-A6B1-26A41BBD369A with 6a6eda33-c5e3-4a85-b8cf-2ff96b1bd424
[HTTP] <-- POST /wd/hub/session/6a6eda33-c5e3-4a85-b8cf-2ff96b1bd424/element/E329D62C-C698-4916-8AE0-C608578AE5CC/click 200 1711 ms - 118 
[XCUITest] xcodebuild exited with code 'null' and signal 'SIGKILL'
[XCUITest] System log exited with code 'null'
[XCUITest] iproxy exited with code 'null'
------Timeout : 1
[HTTP] --> GET /wd/hub/session/6a6eda33-c5e3-4a85-b8cf-2ff96b1bd424/screenshot {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/6a6eda33-c5e3-4a85-b8cf-2ff96b1bd424/screenshot] to [GET http://localhost:8418/session/4FC9BA0A-6633-4A35-A6B1-26A41BBD369A/screenshot] with body: {}
[MJSONWP] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8418
    at doJwpProxy$ (../../../lib/mjsonwp/mjsonwp.js:342:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- GET /wd/hub/session/6a6eda33-c5e3-4a85-b8cf-2ff96b1bd424/screenshot 500 23 ms - 301 
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8418 (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 25 milliseconds
Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:59:12'
System info: host: 'Satishs-MAC.local', ip: '10.104.147.84', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12', java.version: '1.8.0_112'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{app=/Users/Satish/iOS-Agent/ios/Builds/MaaS360_3.18.ipa, networkConnectionEnabled=false, databaseEnabled=false, deviceName=iPhone, platform=MAC, wdaLocalPort=8418, realDeviceLogger=/usr/local/lib/node_modules/deviceconsole/deviceconsole, newCommandTimeout=300, platformVersion=10.0.2, webStorageEnabled=false, locationContextEnabled=false, automationName=XCUITest, browserName=, takesScreenshot=true, javascriptEnabled=true, udid=d8814950652da486ef218e96adcf098b881e0be6, platformName=iOS, autoAcceptAlerts=true}]
Session ID: 6a6eda33-c5e3-4a85-b8cf-2ff96b1bd424
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:647)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:206)
	at org.openqa.selenium.remote.RemoteWebDriver.getScreenshotAs(RemoteWebDriver.java:325)
	at com.commonLibraries.AppiumActions_iOS.captureScreen(AppiumActions_iOS.java:1358)
	at com.commonLibraries.AppiumActions_iOS.click(AppiumActions_iOS.java:80)
	at com.ios.AppiumScripts.STO38473_VerifyMarkingFilesAsFavoriteInIBMConnectionsSource.clickDocsIBMConnections_MyFolders_Name25(STO38473_VerifyMarkingFilesAsFavoriteInIBMConnectionsSource.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.TestNG.privateMain(TestNG.java:1325)
	at org.testng.TestNG.main(TestNG.java:1294)
Entered After Invocation of clickDocsIBMConnections_MyFolders_Name25
Entered Test Success of method name clickDocsIBMConnections_MyFolders_Name25
Test case execution SUCCESS on 2017/03/14 20:13:33
scrollToElementDocsIBMConnections_AutomationFolder_Name27 Started
Entered Before Invocation of scrollToElementDocsIBMConnections_AutomationFolder_Name27
[Invoker 1318180415] Invoking com.ios.AppiumScripts.STO38473_VerifyMarkingFilesAsFavoriteInIBMConnectionsSource.scrollToElementDocsIBMConnections_AutomationFolder_Name27

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Can you also provide Appium log?

**Comment by SatishKumarKV** [comment]
@mykola-mokhnach : These are the console logs produced by Appium.
Trying to figure out if driver.getScreenshotAs method is causing issue here.
Have triggered run again by disabling taking screenshot.

**Comment by SatishKumarKV** [comment]
@mykola-mokhnach : I am not seeing **proxy error could not connect to device** after disabling capturing screenshots during my runs and upgrading to 1.6.4 beta . Will try to optimize screenshot capturing by synchronizing it and see if i can reproduce issue.
