### ISSUE TITLE
Webdriver automatically disconnects

### ISSUE THREAD

**Issue by sp5594** [appium/appium#8038]
## The problem

I have an hybrid app that requires me to sign in using fb. To do so, I switch from webview to native view. It has been working fine until recently I started noticing web driver automatically disconnecting. Anytime FB page loads in the in-app browser, I notice the following in appium logs

## Environment

* Appium version (1.6.3)
* Mac OS
* iPhone 5s iOS 10.2
* Appium CLI

## Link to Appium logs

[https://gist.github.com/sp5594/714c22b0f07fc76260536e324bb6f54e](url)

**Comment by mykola-mokhnach** [comment]
The attached gist is not available. Please attach the correct one.

**Comment by sp5594** [comment]
`+[debug] [BaseDriver] Waiting up to 0 ms for condition
+[debug] [RemoteDebugger] Executing 'find_elements' atom in default context
+[debug] [RemoteDebugger] Sending javascript command (function(){return function(){var l=this;functi...
+[debug] [RemoteDebugger] Sending WebKit data: {"method":"Runtime.evaluate...
+[debug] [RemoteDebugger] WebKit remote debugger socket disconnected
+[debug] [iOS] Error received while executing atom: operation timed out
+[MJSONWP] Encountered internal error running command: TimeoutError: operation timed out
+    at afterTimeout (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/timers.js:16:15)
+    at Timeout.timeoutTimeout [as _onTimeout] (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/timers.js:59:9)
+    at ontimeout (timers.js:365:14)
+    at tryOnTimeout (timers.js:237:5)
+    at Timer.listOnTimeout (timers.js:207:5)` +[debug] [BaseDriver] Waiting up to 0 ms for condition
+[debug] [RemoteDebugger] Executing 'find_elements' atom in default context
+[debug] [RemoteDebugger] Sending javascript command (function(){return function(){var l=this;functi...
+[debug] [RemoteDebugger] Sending WebKit data: {"method":"Runtime.evaluate...
+[debug] [RemoteDebugger] WebKit remote debugger socket disconnected
+[debug] [iOS] Error received while executing atom: operation timed out
+[MJSONWP] Encountered internal error running command: TimeoutError: operation timed out
+    at afterTimeout (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/timers.js:16:15)
+    at Timeout.timeoutTimeout [as _onTimeout] (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/timers.js:59:9)
+    at ontimeout (timers.js:365:14)
+    at tryOnTimeout (timers.js:237:5)
+    at Timer.listOnTimeout (timers.js:207:5)` `

**Comment by mykola-mokhnach** [comment]
Is it possible to get the full log as a text file?

**Comment by sp5594** [comment]
Here you go..

[log.pdf](https://github.com/appium/appium/files/844721/log.pdf)

**Comment by sp5594** [comment]
In the console I`m seeing the following:

Connected :27753 to (UDID)
Page 27753/0 not found
Already sent close_frame

**Comment by sp5594** [comment]
Here`s the console log as well

[consolelog.pdf](https://github.com/appium/appium/files/844778/consolelog.pdf)

**Comment by dpgraham** [comment]
Is this problem still happening for you on the latest Appium?

**Comment by jlipps** [comment]
closing due to inactivity
