### ISSUE TITLE
[MJSONWP] Encountered internal error running command: Error: simctl error running 'install': An error was encountered processing the command (domain=MIInstallerErrorDomain, code=4):

### ISSUE THREAD

**Issue by rogermorgado** [appium/appium#8055]
Hi Guys

I've upgraded to Xcode 8.3 Beta 4 and then realized I couldn't use the old Appium GUI for iOS automation. I've therefore installed the appium desktop 1.0.0 beta 4. When I try to start a new session I get the following error:

[MJSONWP] Encountered internal error running command: Error: simctl error running 'install': An error was encountered processing the command (domain=MIInstallerErrorDomain, code=4):
Failed to chmod /Users/roger/Library/Developer/CoreSimulator/Devices/C4F8A1AF-E878-4F39-8EA6-9EF9EBD80CBC/data/Library/Caches/com.apple.containermanagerd/Bundle/Application/6FE6D4F1-2B79-4614-B87A-F28A34192096/CityPair.app/$(EXECUTABLE_NAME) : No such file or directory

I've restarted the Simulator, reset it, tried different versions but I always get the same error. Any ideas?

Here is the full log:

[Appium] Welcome to Appium v1.6.4-beta
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> DELETE /wd/hub/session {}
[HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- DELETE /wd/hub/session 404 10 ms - 57 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/roger/Downloads/build_2/Release-iphonesimulator/CityPair.app","automationName":"XCUITest","deviceName":"iPhone 7","noReset":true,"platformName":"iOS","platformVersion":"10.3","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/roger/Downloads/build_2/Release-iphonesimulator/CityPair.app","automationName":"XCUITest","deviceName":"iPhone 7","noReset":true,"platformName":"iOS","platformVersion":"10.3","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null,null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1489758520753 (15:48:40 GMT+0200 (SAST))
[Appium] Creating new XCUITestDriver (v2.20.0) session
[Appium] Capabilities:
[Appium]   app: '/Users/roger/Downloads/build_2/Release-iphonesimulator/CityPair.app'
[Appium]   automationName: 'XCUITest'
[Appium]   deviceName: 'iPhone 7'
[Appium]   noReset: true
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '10.3'
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true
[XCUITest] XCUITestDriver version: 2.20.0
[BaseDriver] Session created with session id: c3d66b4a-d5d1-4497-a856-42cf8d7955c0
[XCUITest] Xcode version set to '8.3' (tools v8.2.0.0.1.1480973914)
[XCUITest] iOS SDK Version set to '10.3'
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1489758523294 (15:48:43 GMT+0200 (SAST))
[iOSSim] Constructing iOS simulator for Xcode version 8.3 with udid '4539C402-E620-4A58-B0D0-FEF6D2746DE8'
[XCUITest] Determining device to run tests on: udid: '4539C402-E620-4A58-B0D0-FEF6D2746DE8', real device: false
[BaseDriver] Using local app '/Users/roger/Downloads/build_2/Release-iphonesimulator/CityPair.app'
[BaseDriver] Event 'appConfigured' logged at 1489758523977 (15:48:43 GMT+0200 (SAST))
[XCUITest] Checking whether app '/Users/roger/Downloads/build_2/Release-iphonesimulator/CityPair.app' is actually present on file system
[XCUITest] App is present
[iOS] Getting bundle ID from app '/Users/roger/Downloads/build_2/Release-iphonesimulator/CityPair.app': 'com.LeoNatan.$(PRODUCT_NAME:rfc1034identifier)'
[XCUITest] Setting 'connectHardwareKeyboard' Simulator option to 'on'
[BaseDriver] Event 'resetStarted' logged at 1489758523989 (15:48:43 GMT+0200 (SAST))
[XCUITest] Reset: noReset is on. Leaving simulator as is
[BaseDriver] Event 'resetComplete' logged at 1489758523989 (15:48:43 GMT+0200 (SAST))
[iOSLog] Starting iOS 10.3 simulator log capture
[iOSLog] System log path: /Users/roger/Library/Logs/CoreSimulator/4539C402-E620-4A58-B0D0-FEF6D2746DE8/system.log
[BaseDriver] Event 'logCaptureStarted' logged at 1489758524137 (15:48:44 GMT+0200 (SAST))
[XCUITest] Setting up simulator
[iOS] No reason to set locale
[iOS] No iOS / app preferences to set
[XCUITest] Simulator with udid '4539C402-E620-4A58-B0D0-FEF6D2746DE8' already booted
[BaseDriver] Event 'simStarted' logged at 1489758524371 (15:48:44 GMT+0200 (SAST))
[XCUITest] Installing /Users/roger/Downloads/build_2/Release-iphonesimulator/CityPair.app on Simulator with UUID '4539C402-E620-4A58-B0D0-FEF6D2746DE8'...
[simctl] Error: simctl error running 'install': An error was encountered processing the command (domain=MIInstallerErrorDomain, code=4):
Failed to chmod /Users/roger/Library/Developer/CoreSimulator/Devices/4539C402-E620-4A58-B0D0-FEF6D2746DE8/data/Library/Caches/com.apple.containermanagerd/Bundle/Application/568DF59A-31F0-4179-96B0-621C0A4EA1F4/CityPair.app/$(EXECUTABLE_NAME) : No such file or directory
    at Object.wrappedLogger.errorAndThrow (/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/appium-support/lib/logging.js:60:13)
    at simCommand$ (/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/node-simctl/lib/simctl.js:26:11)
    at tryCatch (/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/node-simctl/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/node-simctl/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/node-simctl/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/node-simctl/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: simctl error running 'install': An error was encountered processing the command (domain=MIInstallerErrorDomain, code=4):
Failed to chmod /Users/roger/Library/Developer/CoreSimulator/Devices/4539C402-E620-4A58-B0D0-FEF6D2746DE8/data/Library/Caches/com.apple.containermanagerd/Bundle/Application/568DF59A-31F0-4179-96B0-621C0A4EA1F4/CityPair.app/$(EXECUTABLE_NAME) : No such file or directory
    at Object.wrappedLogger.errorAndThrow (/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/appium-support/lib/logging.js:60:13)
    at simCommand$ (/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/node-simctl/lib/simctl.js:26:11)
    at tryCatch (/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/node-simctl/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/node-simctl/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/node-simctl/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/node-simctl/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[XCUITest] Error: simctl error running 'install': An error was encountered processing the command (domain=MIInstallerErrorDomain, code=4):
Failed to chmod /Users/roger/Library/Developer/CoreSimulator/Devices/4539C402-E620-4A58-B0D0-FEF6D2746DE8/data/Library/Caches/com.apple.containermanagerd/Bundle/Application/568DF59A-31F0-4179-96B0-621C0A4EA1F4/CityPair.app/$(EXECUTABLE_NAME) : No such file or directory
    at Object.wrappedLogger.errorAndThrow (/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/appium-support/lib/logging.js:60:13)
    at simCommand$ (/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/node-simctl/lib/simctl.js:26:11)
    at tryCatch (/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/node-simctl/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/node-simctl/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/node-simctl/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/node-simctl/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: simctl error running 'install': An error was encountered processing the command (domain=MIInstallerErrorDomain, code=4):
Failed to chmod /Users/roger/Library/Developer/CoreSimulator/Devices/4539C402-E620-4A58-B0D0-FEF6D2746DE8/data/Library/Caches/com.apple.containermanagerd/Bundle/Application/568DF59A-31F0-4179-96B0-621C0A4EA1F4/CityPair.app/$(EXECUTABLE_NAME) : No such file or directory
    at Object.wrappedLogger.errorAndThrow (/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/appium-support/lib/logging.js:60:13)
    at simCommand$ (/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/node-simctl/lib/simctl.js:26:11)
    at tryCatch (/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/node-simctl/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/node-simctl/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/node-simctl/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/node-simctl/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: simctl error running 'install': An error was encountered processing the command (domain=MIInstallerErrorDomain, code=4):
Failed to chmod /Users/roger/Library/Developer/CoreSimulator/Devices/4539C402-E620-4A58-B0D0-FEF6D2746DE8/data/Library/Caches/com.apple.containermanagerd/Bundle/Application/568DF59A-31F0-4179-96B0-621C0A4EA1F4/CityPair.app/$(EXECUTABLE_NAME) : No such file or directory
    at Object.wrappedLogger.errorAndThrow (/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/appium-support/lib/logging.js:60:13)
    at simCommand$ (/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/node-simctl/lib/simctl.js:26:11)
    at tryCatch (/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/node-simctl/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/node-simctl/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/node-simctl/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/node-simctl/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[HTTP] <-- POST /wd/hub/session 500 3883 ms - 528 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/roger/Downloads/build_2/Release-iphonesimulator/CityPair.app","automationName":"XCUITest","deviceName":"iPhone 6","noReset":true,"platformName":"iOS","platformVersion":"10.3","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/roger/Downloads/build_2/Release-iphonesimulator/CityPair.app","automationName":"XCUITest","deviceName":"iPhone 6","noReset":true,"platformName":"iOS","platformVersion":"10.3","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null,null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1489759097115 (15:58:17 GMT+0200 (SAST))

**Comment by mykola-mokhnach** [comment]
Are you sure you application is not damaged? What if you try to install it manually (the target simulator should be already booted)?

```
xcrun simctl install booted app_path
```

**Comment by rogermorgado** [comment]
Same error:

Rogers-MacBook-Pro:~ roger$ xcrun simctl install booted /Users/roger/Downloads/build_2/Release-iphonesimulator/CityPair.app
An error was encountered processing the command (domain=MIInstallerErrorDomain, code=4):
Failed to chmod /Users/roger/Library/Developer/CoreSimulator/Devices/4539C402-E620-4A58-B0D0-FEF6D2746DE8/data/Library/Caches/com.apple.containermanagerd/Bundle/Application/3C2C761E-E3BF-4B64-91B0-49EB7EA0000F/CityPair.app/$(EXECUTABLE_NAME) : No such file or directory

If I run the same command in sudo I get: "No devices are booted." even though the sim is booted and ready.

**Comment by mykola-mokhnach** [comment]
This means you application under test is damaged and cannot be installed on Simulator. Please solve the issue with app developers. 
Closing the issue as not Appium-related.
