### ISSUE TITLE
Issues with UI Automator 2.0 

### ISSUE THREAD

**Issue by HPramesh** [appium/appium#8056]
**ISSUES:**
1. Appium server fails to start new session on rerunning automation with UI Automator 2.0

This issue was observed on 7.1.1 device.
Appium runs fine for the first time but on rerun fails with new session cannot be created error. 
**Workaround,** :  On uninstalling the UI Automator drivers - io.appium.uiautomator2.server and io.appium.uiautomator2.server.test from the device, the appium works fine.

2. Some times automation just stops executing with appium logs showing Proxying... message. This issue is observed on 7.1.1 and 6.0 as well
 
Want to know if this is the issue with the UiAutomator itself or needs any configuration to be set up?

## Environment

Appium version (or git revision) that exhibits the issue:1.6.3
Last Appium version that did not exhibit the issue (if applicable): 4.1.1
Desktop OS/version used to run Appium: windows 7
Node.js version (unless using Appium.app|exe):
Mobile platform/version under test: andrdoid 7.1.1
Real device or emulator/simulator: Real device
Appium CLI or Appium.app|exe:

## Details

**ISSUE 1**
[INFO ] 20170315-220756 [main] getDeviceProp- Got Device Properties
[INFO ] 20170315-220756 [main] setCapability- Setting Device Capability
[INFO ] 20170315-220756 [main] setCapability- Device Capabilities Are Set Now
[INFO ] 20170315-222759 [main] StopScreenRecording- Killing ADB process id for video recording => null
FAILED CONFIGURATION: @BeforeClass setup("0d119a930c59b26c")
org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'AutomationPC', ip: '15.47.191.31', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_111'
Driver info: driver.version: AndroidDriver
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:665)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:40)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:249)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:36)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:114)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:132)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:92)
	at com.hp.mobile.settings.MpsSettingsUiAndroidM.setup(MpsSettingsUiAndroidM.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:169)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: org.openqa.selenium.WebDriverException: org.apache.http.NoHttpResponseException: 127.0.0.1:4723 failed to respond
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'AutomationPC', ip: '15.47.191.31', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_111'
Driver info: driver.version: AndroidDriver
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:84)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:644)
	... 39 more
Caused by: org.apache.http.NoHttpResponseException: 127.0.0.1:4723 failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:162)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:90)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:69)
	... 40 more

**ISSUE2**

2017-03-17 18:56:50:545 - info: [ADB] Checking whether adb is present
2017-03-17 18:56:50:545 - info: [ADB] Using adb.exe from C:\Users\veramit\AppData\Local\Android\sdk\platform-tools\adb.exe
2017-03-17 18:56:50:560 - info: [AndroidDriver] Retrieving device list
2017-03-17 18:56:50:560 - info: [debug] [ADB] Trying to find a connected android device
2017-03-17 18:56:50:560 - info: [debug] [ADB] Getting connected devices...
2017-03-17 18:56:50:576 - info: [debug] [ADB] 2 device(s) connected
2017-03-17 18:56:50:576 - info: [AndroidDriver] Using device: 0b062b370361c37f
2017-03-17 18:56:50:576 - info: [ADB] Checking whether adb is present
2017-03-17 18:56:50:592 - info: [ADB] Using adb.exe from C:\Users\veramit\AppData\Local\Android\sdk\platform-tools\adb.exe
2017-03-17 18:56:50:592 - info: [debug] [ADB] Setting device id to 0b062b370361c37f
2017-03-17 18:56:50:592 - warn: [AndroidDriver] No app sent in, not parsing package/activity
2017-03-17 18:56:50:592 - info: [ADB] Getting device platform version
2017-03-17 18:56:50:592 - info: [debug] [ADB] Getting connected devices...
2017-03-17 18:56:50:607 - info: [debug] [ADB] 2 device(s) connected
2017-03-17 18:56:50:607 - info: [debug] [ADB] Running 'C:\Users\veramit\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","0b062b370361c37f","shell","getprop","ro.build.version.release"]
2017-03-17 18:56:50:716 - info: [debug] [ADB] Getting connected devices...
2017-03-17 18:56:50:732 - info: [debug] [ADB] 2 device(s) connected
2017-03-17 18:56:50:732 - info: [debug] [ADB] Running 'C:\Users\veramit\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","0b062b370361c37f","shell","wm","size"]
2017-03-17 18:56:51:637 - info: [debug] [ADB] Getting connected devices...
2017-03-17 18:56:51:684 - info: [debug] [ADB] 2 device(s) connected
2017-03-17 18:56:51:684 - info: [debug] [ADB] Running 'C:\Users\veramit\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","0b062b370361c37f","shell","getprop","ro.product.model"]
2017-03-17 18:56:51:746 - info: [debug] [ADB] Current device property 'ro.product.model': Nexus 5
2017-03-17 18:56:51:746 - info: [debug] [ADB] Getting connected devices...
2017-03-17 18:56:51:793 - info: [debug] [ADB] 2 device(s) connected
2017-03-17 18:56:51:793 - info: [debug] [ADB] Running 'C:\Users\veramit\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","0b062b370361c37f","shell","getprop","ro.product.manufacturer"]
2017-03-17 18:56:51:840 - info: [debug] [ADB] Current device property 'ro.product.manufacturer': LGE
2017-03-17 18:56:51:840 - info: [debug] [ADB] Getting connected devices...
2017-03-17 18:56:51:871 - info: [debug] [ADB] 2 device(s) connected
2017-03-17 18:56:51:871 - info: [debug] [ADB] Running 'C:\Users\veramit\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","0b062b370361c37f","shell","am","force-stop","io.appium.uiautomator2.server"]
2017-03-17 18:56:52:822 - info: [debug] [ADB] Running 'C:\Users\veramit\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","0b062b370361c37f","wait-for-device"]
2017-03-17 18:56:52:854 - info: [debug] [ADB] Getting connected devices...
2017-03-17 18:56:52:885 - info: [debug] [ADB] 2 device(s) connected
2017-03-17 18:56:52:885 - info: [debug] [ADB] Running 'C:\Users\veramit\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","0b062b370361c37f","shell","echo","ping"]
2017-03-17 18:56:52:932 - info: [debug] [Logcat] Starting logcat capture
2017-03-17 18:56:53:010 - info: [debug] [AndroidDriver] Pushing settings apk to device...
2017-03-17 18:56:53:010 - info: [debug] [ADB] Running 'C:\Users\veramit\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","0b062b370361c37f","install","C:\\Users\\veramit\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\io.appium.settings\\bin\\settings_apk-debug.apk"]
2017-03-17 18:56:54:788 - info: [debug] [AndroidDriver] Pushing unlock helper app to device...
2017-03-17 18:56:54:788 - info: [debug] [ADB] Running 'C:\Users\veramit\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","0b062b370361c37f","install","C:\\Users\\veramit\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-unlock\\bin\\unlock_apk-debug.apk"]
2017-03-17 18:56:59:671 - info: [debug] [UiAutomator2] Forwarding UiAutomator2 Server port 6790 to 8200
2017-03-17 18:56:59:671 - info: [debug] [ADB] Forwarding system: 8200 to device: 6790
2017-03-17 18:56:59:686 - info: [debug] [ADB] Running 'C:\Users\veramit\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","0b062b370361c37f","forward","tcp:8200","tcp:6790"]
2017-03-17 18:56:59:718 - info: [debug] [ADB] Getting connected devices...
2017-03-17 18:56:59:749 - info: [debug] [ADB] 2 device(s) connected
2017-03-17 18:56:59:749 - info: [debug] [ADB] Running 'C:\Users\veramit\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","0b062b370361c37f","shell","dumpsys","window"]
2017-03-17 18:56:59:858 - info: [AndroidDriver] Screen already unlocked, doing nothing
2017-03-17 18:56:59:858 - info: [debug] [AndroidDriver] Extracting strings from apk null null C:\Users\veramit\AppData\Local\Temp\com.android.settings
2017-03-17 18:56:59:874 - info: [debug] [ADB] Extracting strings for language: default
2017-03-17 18:56:59:874 - info: [debug] [ADB] Getting connected devices...
2017-03-17 18:56:59:905 - info: [debug] [ADB] 2 device(s) connected
2017-03-17 18:56:59:905 - info: [debug] [ADB] Running 'C:\Users\veramit\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","0b062b370361c37f","shell","getprop","ro.build.version.sdk"]
2017-03-17 18:57:00:045 - info: [debug] [ADB] Device API level: 23
2017-03-17 18:57:00:045 - info: [debug] [ADB] Getting connected devices...
2017-03-17 18:57:00:076 - info: [debug] [ADB] 2 device(s) connected
2017-03-17 18:57:00:092 - info: [debug] [ADB] Running 'C:\Users\veramit\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","0b062b370361c37f","shell","getprop","persist.sys.locale"]
2017-03-17 18:57:00:154 - info: [debug] [ADB] Current device property 'persist.sys.locale': en-US
2017-03-17 18:57:00:407 - info: [debug] [ADB] No strings.xml for language 'en', getting default strings.xml
2017-03-17 18:57:00:628 - info: [debug] [ADB] Getting connected devices...
2017-03-17 18:57:00:660 - info: [debug] [ADB] 2 device(s) connected
2017-03-17 18:57:00:660 - info: [debug] [ADB] Running 'C:\Users\veramit\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","0b062b370361c37f","shell","rm","-rf","/data/local/tmp/strings.json"]
2017-03-17 18:57:00:738 - info: [debug] [UiAutomator2] No app capability. Assuming it is already on the device
2017-03-17 18:57:00:738 - info: [debug] [ADB] APK doesn't exist. null
2017-03-17 18:57:00:738 - info: [ADB] Checking whether aapt is present
2017-03-17 18:57:00:738 - info: [ADB] Using aapt.exe from C:\Users\veramit\AppData\Local\Android\sdk\build-tools\25.0.1\aapt.exe
2017-03-17 18:57:00:769 - info: [debug] [ADB] Getting install status for io.appium.uiautomator2.server
2017-03-17 18:57:00:769 - info: [debug] [ADB] Getting connected devices...
2017-03-17 18:57:00:816 - info: [debug] [ADB] 2 device(s) connected
2017-03-17 18:57:00:816 - info: [debug] [ADB] Running 'C:\Users\veramit\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","0b062b370361c37f","shell","pm","list","packages","io.appium.uiautomator2.server"]
2017-03-17 18:57:01:564 - info: [debug] [ADB] App is installed
2017-03-17 18:57:01:564 - info: [debug] [ADB] Getting install status for io.appium.uiautomator2.server.test
2017-03-17 18:57:01:564 - info: [debug] [ADB] Getting connected devices...
2017-03-17 18:57:01:596 - info: [debug] [ADB] 2 device(s) connected
2017-03-17 18:57:01:596 - info: [debug] [ADB] Running 'C:\Users\veramit\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","0b062b370361c37f","shell","pm","list","packages","io.appium.uiautomator2.server.test"]
2017-03-17 18:57:02:329 - info: [debug] [ADB] App is installed
2017-03-17 18:57:02:329 - info: [ADB] Checking whether aapt is present
2017-03-17 18:57:02:344 - info: [ADB] Using aapt.exe from C:\Users\veramit\AppData\Local\Android\sdk\build-tools\25.0.1\aapt.exe
2017-03-17 18:57:02:360 - info: [debug] [ADB] Getting connected devices...
2017-03-17 18:57:02:391 - info: [debug] [ADB] 2 device(s) connected
2017-03-17 18:57:02:391 - info: [debug] [ADB] Running 'C:\Users\veramit\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","0b062b370361c37f","shell","dumpsys","package","io.appium.uiautomator2.server"]
2017-03-17 18:57:02:469 - info: [debug] [ADB] Getting connected devices...
2017-03-17 18:57:02:500 - info: [debug] [ADB] 2 device(s) connected
2017-03-17 18:57:02:516 - info: [debug] [ADB] Running 'C:\Users\veramit\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","0b062b370361c37f","shell","am","force-stop","io.appium.uiautomator2.server"]
2017-03-17 18:57:03:514 - info: [UiAutomator2] Starting uiautomator2 server v0.1.1 with cmd: am,instrument,-w,io.appium.uiautomator2.server.test/android.support.test.runner.AndroidJUnitRunner
2017-03-17 18:57:03:514 - info: [UiAutomator2] running command...
adb -s 0b062b370361c37f shell am instrument -w io.appium.uiautomator2.server.test/android.support.test.runner.AndroidJUnitRunner... 
2017-03-17 18:57:03:514 - info: [UiAutomator2] Waiting for UiAutomator2 to be online...
2017-03-17 18:57:03:514 - info: [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
2017-03-17 18:57:04:546 - info: [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
2017-03-17 18:57:05:562 - info: [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
2017-03-17 18:57:06:576 - info: [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
2017-03-17 18:57:07:590 - info: [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
2017-03-17 18:58:11:788 - info: [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
2017-03-17 18:59:15:943 - info: [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
2017-03-17 18:59:23:899 - info: [HTTP] <-- POST /wd/hub/session - - ms - - 
2017-03-17 19:00:20:111 - info: [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
2017-03-17 19:01:24:259 - info: [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
2017-03-17 19:02:28:419 - info: [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
2017-03-17 19:03:32:582 - info: [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
2017-03-17 19:04:36:727 - info: [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
2017-03-17 19:05:40:890 - info: [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
2017-03-17 19:06:45:006 - info: [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
2017-03-17 19:07:49:161 - info: [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
2017-03-17 19:08:53:317 - info: [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
2017-03-17 19:09:57:474 - info: [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
2017-03-17 19:11:01:631 - info: [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
2017-03-17 19:12:05:823 - info: [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
2017-03-17 19:13:09:990 - info: [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
2017-03-17 19:14:14:141 - info: [debug] [UiAutomator2] Deleting UiAutomator2 session
2017-03-17 19:14:14:141 - info: [debug] [UiAutomator2] Deleting UiAutomator2 server session
2017-03-17 19:14:14:141 - warn: [UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: Error: Trying to proxy a session command without session id
2017-03-17 19:14:14:141 - info: [debug] [ADB] Getting connected devices...
2017-03-17 19:14:14:188 - info: [debug] [ADB] 2 device(s) connected
2017-03-17 19:14:14:188 - info: [debug] [ADB] Running 'C:\Users\veramit\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","0b062b370361c37f","shell","am","force-stop","com.android.settings"]
2017-03-17 19:14:15:170 - info: [debug] [Logcat] Stopping logcat capture
2017-03-17 19:14:15:170 - info: [debug] [ADB] Removing forwarded port socket connection: 8200 
2017-03-17 19:14:15:170 - info: [debug] [ADB] Running 'C:\Users\veramit\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","0b062b370361c37f","forward","--remove","tcp:8200"]
2017-03-17 19:14:15:202 - error: [MJSONWP] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: Error: read ECONNRESET
    at JWProxy.proxy$ (../../../lib/jsonwp-proxy/proxy.js:127:13)
    at tryCatch (C:\Users\veramit\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\veramit\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\veramit\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\veramit\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
2017-03-17 21:11:17:707 - info: [Appium] Received SIGINT - shutting down

## Link to Appium logs
 Issue_1 : https://gist.github.com/HPramesh/a4ebfa7b45787b1f818623d6d7ee6272

**Comment by SrinivasanTarget** [comment]
@HPramesh Please use latest version of appium server and java client 5.0 Beta 4.It will be working.

**Comment by HPramesh** [comment]
@SrinivasanTarget  : Thanks for the solution, it worked.

**Comment by mt-nvkhoa** [comment]
Hello,
I'm using appium 1.7.1 and java client 5.0.0-BETA8, but get same issue.
(I'm using android emulator 5.0 for testing)
Could you please give me some hint to solve this issue ? @SrinivasanTarget 

Thanks a lot
