### ISSUE TITLE
Appium 1.5.3: Cannot start Server and launch Inspector

### ISSUE THREAD

**Issue by louis57** [appium/appium#8071]
## The problem

I used Appium 1.4.13 before (for Android), and everything worked fine. After I upgraded Appium to the latest version 1.5.3 (Ara), I can't launch Server and therefore Inspector anymore. Everytime I get a Popup says: "Could not launch Appium Inspector. Could not start a new session., etc."  

When I switch back to Appium 1.4.13, then everything works again. Please, can anyone help me. Thanks

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.3 (Ara)
* Last Appium version that did not exhibit the issue (if applicable): 1.4.13
* Desktop OS/version used to run Appium: Mac OSX El Capitan, Version 10.11.6

## Details

This is logs from server side:
[AndroidDriver] Error: Unable to find an active device or emulator with OS 4.4. The following are available: 06157df683e4993c (6.0.1)
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at Object.callee$0$0$ (lib/android-helpers.js:154:16)
    at tryCatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
 [Error: Unable to find an active device or emulator with OS 4.4. The following are available: 06157df683e4993c (6.0.1)]

[debug] [AndroidDriver] Shutting down Android driver

[MJSONWP] Encountered internal error running command: Error: Unable to find an active device or emulator with OS 4.4. The following are available: 06157df683e4993c (6.0.1)
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at Object.callee$0$0$ (lib/android-helpers.js:154:16)
    at tryCatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

[AndroidDriver] Cannot shut down Android driver; it has already shut down
[HTTP] <-- POST /wd/hub/session 500 347 ms - 247

**Comment by dpgraham** [comment]
Hi @louis57, have you tried v1.6.4beta? That's our latest version.

Also, we have a new cross-platform GUI client (https://github.com/appium/appium-desktop/releases/latest) that is officially supported by the Appium team.

**Comment by bmvbab** [comment]
[Error: Unable to find an active device or emulator with OS 4.4. The following are available: 06157df683e4993c (6.0.1)]

Try fixing the OS version in your capabilities.

**Comment by louis57** [comment]
Hi @dpgraham , could you please tell me where I can get v1.6.4beta as .dmg for OSX? In Download Repository (https://bitbucket.org/appium/appium.app/downloads/) is still v1.5.3 . Thanks a lot

**Comment by louis57** [comment]
@bmvbab Thanks for suggestion. But one silly question: I haven't run the test yet at this point. I just used Appium GUI v1.5.3 to launch the Inspector. And I don't see any OS capabilities as you suggested in Appium GUI. Can you please explain more? Thanks

**Comment by vikramvi** [comment]
@louis57 please refer to comment from **dpgraham** above, you are looking at wrong link.

**Comment by louis57** [comment]
Thanks guys, I use the v1.6.4beta and Inspector works.

**Comment by vikramvi** [comment]
@triager please close per last comment
