### ISSUE TITLE
Unable to find element by Xpath using Xcuitest

### ISSUE THREAD

**Issue by ranjithreddy0005** [appium/appium#8084]
System.out.println(driver.findElements(By.className("XCUIElementTypeWindow")).size());
		System.out.println(driver.findElement(By.className("XCUIElementTypeWindow")).getText());
System.out.println(driver.findElements(By.xpath("//XCUIElementTypeWindow")).size());

Output : 
2
null
0       -----why zero ????

Unable to locate element with XCUITest,please help strucked with almost 3 days.
System.out.println(driver.findElements(By.xpath("//XCUIElementTypeWindow")).size());

**Comment by mykola-mokhnach** [comment]
Please attach full Appium log

**Comment by ranjithreddy0005** [comment]
@mykola-mokhnach  please find the attached log file.
[appium_log.txt](https://github.com/appium/appium/files/864779/appium_log.txt)

@mykola-mokhnach  My class file is 

[code.txt](https://github.com/appium/appium/files/864784/code.txt)

**Comment by mykola-mokhnach** [comment]
Update Appium to 1.6.4-beta:
```
npm remove -g appium
npm install -g appium@1.6.4-beta
```

**Comment by ranjithreddy0005** [comment]
@mykola-mokhnach I have tried 1.6.4-beta ,it did not worked .

So i have reverted back to 1.6.3 again.Please @mykola-mokhnach  hope you could help me on this asap,i already ruined 3 full days working on this and without locating with xpath i cannot continue my tests.

**Comment by mykola-mokhnach** [comment]
Show me the log from 1.6.4-beta.
I see a crash in WDA logs with 1.6.3. This bug might be fixed in the newer version.

**Comment by ranjithreddy0005** [comment]
@mykola-mokhnach  same issue on 1.6.4-beta.

here is the log file
[appium_log_1.6.4-beta.txt](https://github.com/appium/appium/files/864935/appium_log_1.6.4-beta.txt)

**Comment by mykola-mokhnach** [comment]
Are you able to see the output of _driver.getPageSource_? If not, can you send the log as well?

**Comment by ranjithreddy0005** [comment]
@mykola-mokhnach  I dont see output for driver.getPageSource . the below is the code and appium logs.
String html = driver.getPageSource();

System.out.println(html);


Log : 
[Appium_logs_new.txt](https://github.com/appium/appium/files/865045/Appium_logs_new.txt)

**Comment by mykola-mokhnach** [comment]
It looks like you are trying to use old webdriveragent lib with new Appium. It is necessary to make sure the WDA lib is properly replaced after upgrade
Try the solution from https://github.com/appium/appium/issues/8080

**Comment by ranjithreddy0005** [comment]
@mykola-mokhnach  tried above usecase and did not got pagesource the below are the appium logs.
[appium_log_1.txt](https://github.com/appium/appium/files/865257/appium_log_1.txt)


The below is the excpetion got in eclipse console : 

Exception in thread "main" org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Cannot get '(null)' source of the current application (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 106 milliseconds
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'nbmaclap28.local', ip: '192.168.1.2', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.5', java.version: '1.8.0_111'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{app=/Users/ranjith/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/IntegrationApp.app, networkConnectionEnabled=false, appiumVersion=1.6.4-beta, databaseEnabled=false, deviceName=iPhone 6, platform=MAC, platformVersion=10.2, webStorageEnabled=false, locationContextEnabled=false, automationName=XCUITest, browserName=, takesScreenshot=true, javascriptEnabled=true, platformName=iOS, udid=f13ef40626712b5c17aefdccdba596a4529fcf15}]
Session ID: 06370607-1444-4684-a05a-63d53779edfd
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:40)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:235)
	at org.openqa.selenium.remote.RemoteWebDriver.getPageSource(RemoteWebDriver.java:511)
	at spottest.TestNativeAppRealDevice.main(TestNativeAppRealDevice.java:45)

**Comment by mykola-mokhnach** [comment]
Ok, now I see it.
Can you find the full text of the exception stacktrace starting with **objc_exception_thrown** in device log and attach it here?

BTW, you can check whether your app does not have any unsupported characters in string resources (which are not compatible with UTF-8 encoding). I've already seen a report about such strings can break WDA.

**Comment by ranjithreddy0005** [comment]
@mykola-mokhnach  " Can you find the full text of the exception stacktrace starting with objc_exception_thrown in device log and attach it here?"

how to get these logs?


"BTW, you can check whether your app does not have any unsupported characters in string resources "   
and how to check this?

**Comment by ranjithreddy0005** [comment]
@mykola-mokhnach  this one??

[Session-WebDriverAgentRunner-2017-03-23_223830-poRDCI.txt](https://github.com/appium/appium/files/865563/Session-WebDriverAgentRunner-2017-03-23_223830-poRDCI.txt)

**Comment by mykola-mokhnach** [comment]
No, not exactly what I need. The device log can be extracted with [Xcode](https://support.kaspersky.com/12419)

Regarding resources - you need to have access to application sources or discuss this with developers. The problem might be, that WDA expects all application resources to be valid UTF-8-compatible unicode strings. And  it might crash in case you have some random invalid characters there or somewhere in the application code.

**Comment by dpgraham** [comment]
Closing due to inactivity.
