### ISSUE TITLE
Unable to create new remote session. desired capabilities, Not Connected Devices Android to Mac

### ISSUE THREAD

**Issue by efawan** [appium/appium#8086]
## The problem

Hi Appiumers 💃 

I already run my script using appium and windows environment, and its running well. But i try cloning the code and run to mac environtment. But im facing this problem, 

Unable to create new remote session. desired capabilities = Capabilities [{appPackage=org.qluein.android, appActivity=org.qluein.android.ui.activities.SplashAct, platformName=Android, deviceName=d568d8da}], required capabilities = Capabilities [{}]
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'Efawans-MacBook-Pro.local', ip: '192.168.1.104', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.1', java.version: '1.8.0_121'
Driver info: driver.version: SwipeableWebDriver

I try to connected the android device to mac using this tutorial https://developers.google.com/web/tools/chrome-devtools/remote-debugging/

and the result the device already detected. 

I think is somehow its cant connect to appium server, Please help me 

## Environment

* Appium version 1.5.3 Mac Version
* Last Appium version that did not exhibit the issue (if applicable): Appium 1.4.16. 1 Windows Version
* Desktop OS/version used to run Appium: Mac OS Sierra
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android 5.1
* Real device or emulator/simulator: Samsung SM-J500G
* Appium CLI or Appium.app|exe: Appium App

## Details

Unable to create new remote session. desired capabilities = Capabilities [{appPackage=org.qluein.android, appActivity=org.qluein.android.ui.activities.SplashAct, platformName=Android, deviceName=d568d8da}], required capabilities = Capabilities [{}]
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'Efawans-MacBook-Pro.local', ip: '192.168.1.104', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.1', java.version: '1.8.0_121'
Driver info: driver.version: SwipeableWebDriver
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:91)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:141)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:241)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:128)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:155)
	at fullTest.SwipeableWebDriver.<init>(SwipeableWebDriver.java:14)
	at fullTest.mainTest.setUp(mainTest.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43
....

SKIPPED CONFIGURATION: @AfterTest closeApp
SKIPPED: testCase

## Link to Appium logs
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 11 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 11 ms - 83

## Code To Reproduce Issue [ Good To Have ]
public class mainTest{
	WebDriver wd;
	
	@BeforeTest
	public void setUp() throws MalformedURLException
	{
		System.out.println("Setting Koneksi ke Device");
		DesiredCapabilities cap = new DesiredCapabilities();
		//cap.setCapability("deviceName", "FAAZGF00F399");
		cap.setCapability("deviceName", "d568d8da");
		cap.setCapability("platformName", "Android");
		cap.setCapability("appPackage", "org.qluein.android");
		cap.setCapability("appActivity", "org.qluein.android.ui.activities.SplashAct");
		wd = new SwipeableWebDriver(new URL("http://127.0.0.1:4723/wd/hub"), cap);
		wd.manage().timeouts().implicitlyWait(15, TimeUnit.SECONDS);
	}
	
	@Test
	public void testCase(){
		System.out.println("Testing dimulai");
		caseLoginTest();
		caseClickTutorial();

**Comment by dpgraham** [comment]
Have you followed the Appium Android setup guide?

https://github.com/appium/appium/blob/master/docs/en/appium-setup/android-setup.md

**Comment by lohitsb** [comment]
I am facing Same issue for IOS device. Can any one help on the same?




Device identified
Activity and package added
log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
FAILED: test1
org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{platformVersion=10.2.1, bundlid=com.timewarnercable.trialmytwc, udid=3ff68a990cbe3a7b314ae811677a9bcc8df6e25f, platformName=iOS, deviceName=iPad}], required capabilities = Capabilities [{}]
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'Administrator’s-MacBook-Air', ip: '2001:df1:ae00:4610:a875:d6e5:5381:c09f', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.5', java.version: '1.8.0_91'
Driver info: driver.version: IOSDriver
	at io.appium.java_client.remote.AppiumProtocolHandShake.lambda$1(AppiumProtocolHandShake.java:96)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at io.appium.java_client.remote.AppiumProtocolHandShake.createSession(AppiumProtocolHandShake.java:96)
	at io.appium.java_client.remote.AppiumCommandExecutor.doExecute(AppiumCommandExecutor.java:111)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:162)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)

**Comment by imurchie** [comment]
Closing due to inactivity and immediate off-topic-ness.
