### ISSUE TITLE
[Chromedriver] [STDERR] [68.844][SEVERE]: Port leaked: 12208 Error: Can't set headers after they are sent.

### ISSUE THREAD

**Issue by jawlitkp** [appium/appium#8094]
## The problem

After running test for longtime (8-9 hrs) i am seeing this error on one of appium node and it stops execution on that node

## Environment

* 1.6.3
* Android 6.1

## Details

```
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/b8c492e7-fbbf-4a3c-a88a-91ec79552abe/execute] to [POST http://127.0.0.1:9516/wd/hub/session/5e3900f441c7940b6e2bd51ae6e3bc43/execute] with body: {"script":"return document.readyState","args":[]}
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.3","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 10 ms - 83 
[Chromedriver] [STDERR] [68.807][SEVERE]: Unable to receive message from renderer
[Logcat] Logcat terminated with code 0, signal null
[UiAutomator] UiAutomator exited unexpectedly with code 0, signal null
[debug] [UiAutomator] Moving to state 'stopped'
[debug] [AndroidDriver] Shutting down Android driver
[Appium] Closing session, cause was 'UiAUtomator shut down unexpectedly'
[Appium] Removing session b8c492e7-fbbf-4a3c-a88a-91ec79552abe from our master session list
[debug] [AndroidDriver] Stopping chromedriver for context CHROMIUM
[debug] [Chromedriver] Changed state to 'stopping'
[debug] [JSONWP Proxy] Proxying [DELETE /] to [DELETE http://127.0.0.1:9516/wd/hub/session/5e3900f441c7940b6e2bd51ae6e3bc43] with no body
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"5e3900f441c7940b6e2bd51ae6e3bc43","status":0,"value":null}
[JSONWP Proxy] Replacing sessionId 5e3900f441c7940b6e2bd51ae6e3bc43 with b8c492e7-fbbf-4a3c-a88a-91ec79552abe
[HTTP] <-- POST /wd/hub/session/b8c492e7-fbbf-4a3c-a88a-91ec79552abe/execute 200 2173 ms - 76 
[MJSONWP] Encountered internal error running command: Error: Could not proxy. Proxy error: UiAUtomator shut down unexpectedly
    at doJwpProxy$ (../../../lib/mjsonwp/mjsonwp.js:342:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[HTTP] --> POST /wd/hub/session/b8c492e7-fbbf-4a3c-a88a-91ec79552abe/execute {"script":"return document.readyState","args":[]}
[HTTP] <-- POST /wd/hub/session/b8c492e7-fbbf-4a3c-a88a-91ec79552abe/execute 404 1 ms - 131 
[Chromedriver] [STDERR] [68.844][SEVERE]: Port leaked: 12208
Error: Can't set headers after they are sent.
    at ServerResponse.setHeader (_http_outgoing.js:367:11)
    at ServerResponse.header (/usr/local/lib/node_modules/appium/node_modules/express/lib/response.js:719:10)
    at ServerResponse.send (/usr/local/lib/node_modules/appium/node_modules/express/lib/response.js:164:12)
    at ServerResponse.json (/usr/local/lib/node_modules/appium/node_modules/express/lib/response.js:250:15)
    at asyncHandler$ (../../../lib/mjsonwp/mjsonwp.js:285:30)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
logout
```
[Process completed]

**Comment by dpgraham** [comment]
Are you saying that the tests were running successfully and that after 8-9 hours they started failing?

Also, have you tried the latest Appium 1.6.4-beta?

**Comment by jawlitkp** [comment]
Yes this issue is coming when I leave my test running over night. No I haven't tried with 1.6.4 beta yet

**Comment by dpgraham** [comment]
I doubt that it's an Appium problem, but rather a ChromDriver issue

`[Chromedriver] [STDERR] [68.807][SEVERE]: Unable to receive message from renderer`

Does this error happen all the time at the same spot or does the test pass and then randomly fails after a while

**Comment by jawlitkp** [comment]
I am pretty sure it happens after on of test case fails and node goes down so all test cases start failing

**Comment by dpgraham** [comment]
Is this still an issue? If it is, I'll re-open.
