### ISSUE TITLE
Building WebDriverAgent with xcodeOrgId and xcodeSigningId still throws Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file.

### ISSUE THREAD

**Issue by deepaksporty** [appium/appium#8106]
Building WebDriverAgent with xcodeOrgId and xcodeSigningId still throws Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file.

appium 1.6.4-beta
xcode 8.2.1
MacOS Sierra 10.12.3

Logs 👍 
Last login: Mon Mar 27 22:59:16 on ttys000
BLRDTIWA386367:~ dtiwa1$ appium --address 127.0.0.1 --port 4723 --session-override --log-level debug
[Appium] Welcome to Appium v1.6.4-beta
[Appium] Non-default server args:
[Appium]   address: '127.0.0.1'
[Appium]   sessionOverride: true
[Appium] Appium REST http interface listener started on 127.0.0.1:4723
[HTTP] --> POST /wd/hub/session {"capabilities":[{"desiredCapabilities":{"app":"/Users/dtiwa1/git/mSays-AutomationSuiteForAndroid/MSAYS_Automation/src/main/resources/APKs/Tesco_SAYS.ipa","xcodeOrgId":"FEY6Z943BR","bundleId":"com.tesco.scanasyoushop","xcodeConfigFile":"/Users/dtiwa1/git/mSays-AutomationSuiteForAndroid/MSAYS_Automation/src/main/resources/APKsXCodeConfig.xcconfig","fullReset":true,"deviceName":"Tesco's iPhone","xcodeSigningId":"iphone Developer","autoLaunch":true,"platformVersion":"9.3","automationName":"XCUITest","platformName":"iOS","udid":"d7e9ea82703b2905bf0f5a969d925dc8692ef56c"}},{"requiredCapabilities":{}}],"desiredCapabilities":{"app":"/Users/dtiwa1/git/mSays-AutomationSuiteForAndroid/MSAYS_Automation/src/main/resources/APKs/Tesco_SAYS.ipa","xcodeOrgId":"FEY6Z943BR","bundleId":"com.tesco.scanasyoushop","xcodeConfigFile":"/Users/dtiwa1/git/mSays-AutomationSuiteForAndroid/MSAYS_Automation/src/main/resources/APKsXCodeConfig.xcconfig","fullReset":true,"deviceName":"Tesco's iPhone","xcodeSigningId":"
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/dtiwa1/git/mSays-AutomationSuiteForAndroid/MSAYS_Automation/src/main/resources/APKs/Tesco_SAYS.ipa","xcodeOrgId":"FEY6Z943BR","bundleId":"com.tesco.scanasyoushop","xcodeConfigFile":"/Users/dtiwa1/git/mSays-AutomationSuiteForAndroid/MSAYS_Automation/src/main/resources/APKsXCodeConfig.xcconfig","fullReset":true,"deviceName":"Tesco's iPhone","xcodeSigningId":"iphone Developer","autoLaunch":true,"platformVersion":"9.3","automationName":"XCUITest","platformName":"iOS","udid":"d7e9ea82703b2905bf0f5a969d925dc8692ef56c"},{},[{"desiredCapabilities":{"app":"/Users/dtiwa1/git/mSays-AutomationSuiteForAndroid/MSAYS_Automation/src/main/resources/APKs/Tesco_SAYS.ipa","xcodeOrgId":"FEY6Z943BR","bundleId":"com.tesco.scanasyoushop","xcodeConfigFile":"/Users/dtiwa1/git/mSays-AutomationSuiteForAndroid/MSAYS_Automation/src/main/resources/APKsXCodeConfig.xcconfig","fullReset":true,"deviceName":"Tesco's iPhone","xcodeSigningId":"iphone Developer","autoLaunch":true,"platformVersion":"9.3","automationName":"XCUITes...
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1490636273016 (23:07:53 GMT+0530 (IST))
[Appium] Creating new XCUITestDriver (v2.23.1) session
[Appium] Capabilities:
[Appium]   app: '/Users/dtiwa1/git/mSays-AutomationSuiteForAndroid/MSAYS_Automation/src/main/resources/APKs/Tesco_SAYS.ipa'
[Appium]   xcodeOrgId: 'FEY6Z943BR'
[Appium]   bundleId: 'com.tesco.scanasyoushop'
[Appium]   xcodeConfigFile: '/Users/dtiwa1/git/mSays-AutomationSuiteForAndroid/MSAYS_Automation/src/main/resources/APKsXCodeConfig.xcconfig'
[Appium]   fullReset: true
[Appium]   deviceName: 'Tesco\'s iPhone'
[Appium]   xcodeSigningId: 'iphone Developer'
[Appium]   autoLaunch: true
[Appium]   platformVersion: '9.3'
[Appium]   automationName: 'XCUITest'
[Appium]   platformName: 'iOS'
[Appium]   udid: 'd7e9ea82703b2905bf0f5a969d925dc8692ef56c'
[debug] [XCUITest] XCUITestDriver version: 2.23.1
[BaseDriver] Session created with session id: e2124166-1731-4630-ba12-c0a7bdabd067
[debug] [XCUITest] Xcode version set to '8.2.1' (tools v8.2.0.0.1.1480973914)
[debug] [XCUITest] iOS SDK Version set to '10.2'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1490636273207 (23:07:53 GMT+0530 (IST))
[debug] [XCUITest] Available devices: d7e9ea82703b2905bf0f5a969d925dc8692ef56c
[debug] [XCUITest] Creating iDevice object with udid 'd7e9ea82703b2905bf0f5a969d925dc8692ef56c'
[XCUITest] Determining device to run tests on: udid: 'd7e9ea82703b2905bf0f5a969d925dc8692ef56c', real device: true
[BaseDriver] Using local app '/Users/dtiwa1/git/mSays-AutomationSuiteForAndroid/MSAYS_Automation/src/main/resources/APKs/Tesco_SAYS.ipa'
[debug] [BaseDriver] Copying local zip to tmp dir
[debug] [BaseDriver] Unzipping /var/folders/8w/66v1v211569blvqh41krj1vj3hrvc7/T/2017227-48521-mc7ysm.riosx20529/appium-app.zip
[debug] [BaseDriver] Testing zip archive: /var/folders/8w/66v1v211569blvqh41krj1vj3hrvc7/T/2017227-48521-mc7ysm.riosx20529/appium-app.zip
[debug] [BaseDriver] Got a relaxed match for app in zip, be careful for app match errors
[BaseDriver] Unzipped local app to '/var/folders/8w/66v1v211569blvqh41krj1vj3hrvc7/T/2017227-48521-mc7ysm.riosx20529/Payload/Tesco SAYS.app'
[debug] [BaseDriver] Event 'appConfigured' logged at 1490636273890 (23:07:53 GMT+0530 (IST))
[debug] [XCUITest] Checking whether app '/var/folders/8w/66v1v211569blvqh41krj1vj3hrvc7/T/2017227-48521-mc7ysm.riosx20529/Payload/Tesco SAYS.app' is actually present on file system
[debug] [XCUITest] App is present
[debug] [BaseDriver] Event 'resetStarted' logged at 1490636273892 (23:07:53 GMT+0530 (IST))
[debug] [XCUITest] Reset: running ios real device reset flow
[debug] [XCUITest] Reset: fullReset requested. Will try to uninstall the app 'com.tesco.scanasyoushop'.
[debug] [XCUITest] Reset: removed 'com.tesco.scanasyoushop'
[debug] [BaseDriver] Event 'resetComplete' logged at 1490636274246 (23:07:54 GMT+0530 (IST))
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1490636274394 (23:07:54 GMT+0530 (IST))
[XCUITest] Setting up real device
[debug] [XCUITest] Installing '/var/folders/8w/66v1v211569blvqh41krj1vj3hrvc7/T/2017227-48521-mc7ysm.riosx20529/Payload/Tesco SAYS.app' on device with UUID 'd7e9ea82703b2905bf0f5a969d925dc8692ef56c'...
[debug] [XCUITest] The app has been installed successfully.
[debug] [BaseDriver] Event 'appInstalled' logged at 1490636276153 (23:07:56 GMT+0530 (IST))
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1490636276156 (23:07:56 GMT+0530 (IST))
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Using Xcode configuration file: '/Users/dtiwa1/git/mSays-AutomationSuiteForAndroid/MSAYS_Automation/src/main/resources/APKsXCodeConfig.xcconfig'
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=d7e9ea82703b2905bf0f5a969d925dc8692ef56c -configuration Debug -xcconfig /Users/dtiwa1/git/mSays-AutomationSuiteForAndroid/MSAYS_Automation/src/main/resources/APKsXCodeConfig.xcconfig' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will not be logged
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] Log file for xcodebuild test: /Users/dtiwa1/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/2A0158FB-F5CC-41D8-843A-35DB6503EB21/Session-WebDriverAgentRunner-2017-03-27_230803-2kPazl.log
[Xcode] 2017-03-27 23:08:03.019 xcodebuild[48597:844266] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/dtiwa1/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7fd668714180 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[Xcode] 
[Xcode] 2017-03-27 23:08:03.019 xcodebuild[48597:844266] Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[XCUITest] xcodebuild exited with code '65' and signal 'null'
[debug] [BaseDriver] Event 'wdaStartFailed' logged at 1490636283073 (23:08:03 GMT+0530 (IST))
[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
[debug] [XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down iproxy process (pid 48596)
[debug] [XCUITest] iproxy exited with code 'null'
[debug] [XCUITest] Removing WDA application from device
[HTTP] <-- POST /wd/hub/session - - ms - - 
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1490636293242 (23:08:13 GMT+0530 (IST))
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Using Xcode configuration file: '/Users/dtiwa1/git/mSays-AutomationSuiteForAndroid/MSAYS_Automation/src/main/resources/APKsXCodeConfig.xcconfig'
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=d7e9ea82703b2905bf0f5a969d925dc8692ef56c -configuration Debug -xcconfig /Users/dtiwa1/git/mSays-AutomationSuiteForAndroid/MSAYS_Automation/src/main/resources/APKsXCodeConfig.xcconfig' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will not be logged
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] Log file for xcodebuild test: /Users/dtiwa1/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/0A477542-659B-4050-B174-86F5D2C07ADE/Session-WebDriverAgentRunner-2017-03-27_230819-PGpgtS.log
[Xcode] 2017-03-27 23:08:19.384 xcodebuild[48637:844730] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/dtiwa1/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7fe7a257f2e0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[Xcode] 
[Xcode] 2017-03-27 23:08:19.384 xcodebuild[48637:844730] Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[XCUITest] xcodebuild exited with code '65' and signal 'null'
[debug] [BaseDriver] Event 'wdaStartFailed' logged at 1490636299397 (23:08:19 GMT+0530 (IST))
[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
[debug] [XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down iproxy process (pid 48633)
[debug] [XCUITest] iproxy exited with code 'null'
[debug] [XCUITest] Removing WDA application from device
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:369:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:369:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:369:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)

**Comment by mykola-mokhnach** [comment]
Are you able to build WebDriverAgent manually with Xcode?

**Comment by mykola-mokhnach** [comment]
It would be also useful to see xcodebuild log at /Users/dtiwa1/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/0A477542-659B-4050-B174-86F5D2C07ADE/Session-WebDriverAgentRunner-2017-03-27_230819-PGpgtS.log

**Comment by deepaksporty** [comment]
Hi...thanks for the help. I was able to build the WebDriverAgent manually.

Then I also provided the xcodeOrgId and xcodeSigningId. I also added these two values to XCodeConfig.xcconfig file as well.

however it only worked by adding below capabilities:

iOSCapabilities.setCapability("bootstrapPath", "/usr/local/lib/node_modules/appium-xcuitest-driver/WebDriverAgent");
iOSCapabilities.setCapability("agentPath", "/usr/local/lib/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj");

and now I am able to launch the app.

However I somehow feel that Appium is not able to get WebDriverAgent path.

**Comment by deepaksporty** [comment]
sorry I tried finding the log file but it seems it gets deleted.

**Comment by GeeChao** [comment]
@deepaksporty 

Thanks for your help on setting the capabilities for bootstrapPath and agentPath.

Previously it would only work when starting the Appium server via the global installed Appium. 

When using the Appium server started via the local project installed or via the Desktop-inspector, it would throw the errors:
`
[debug] [XCUITest] Log file for xcodebuild test: /Users/machan/Library/Developer/Xcode/DerivedData/WebDriverAgent-axaasxmmqxgctnhafuscommjbvbf/Logs/Test/18E34B2D-766D-4E56-8FA7-7A95B0E9EE9E/Session-WebDriverAgentRunner-2017-06-27_141520-HL3JB0.log
[Xcode] 2017-06-27 14:15:20.126 xcodebuild[33671:1812008] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/machan/Library/Developer/Xcode/DerivedData/WebDriverAgent-axaasxmmqxgctnhafuscommjbvbf/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7fbc295b90e0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[Xcode] 
[Xcode] 2017-06-27 14:15:20.126 xcodebuild[33671:1812008] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[XCUITest] xcodebuild exited with code '65' and signal 'null'
`

**Comment by imurchie** [comment]
The `xcodeOrgId` and `xcodeSigningId` capabilities do nothing is an `xcodeConfigFile` capability is set. 

As for the WDA bootstrap path, that is being set to the bundled WDA:
```
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
```

**Comment by imurchie** [comment]
Closing due to inactivity and duplicate.
