### ISSUE TITLE
iOS Inspector is throwing error for Appium 1.6.4-beta and Xcode 8.

### ISSUE THREAD

**Issue by mmguhe** [appium/appium#8107]
## The problem
I was using Appium 1.4.13 to run my tests. 
Now I am investigating Appium 1.6 and updated my Xcode to 8.2.
iOS version : 9.3.2
iPhone : 6

Step 1 : I want to start Appium inspector to inspect the elementID's.
I started Appium ( 1.6.4-beta) from terminal
Launch the Appium inspector ( 1.5.3) and clicked on the inspector icon.

Error : 

[Appium] Welcome to Appium v1.6.4-beta (REV 6669e91bd8187ae9efbf110e31fc4e4d7b79011f)
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.4-beta","revision":"6669e91bd8187ae9efbf110e31fc4e4d7b79011f"}}
[HTTP] <-- GET /wd/hub/status 200 17 ms - 126 
[HTTP] --> GET /wd/hub/sessions {}
[debug] [MJSONWP] Calling AppiumDriver.getSessions() with args: []
[debug] [MJSONWP] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 2 ms - 40 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"iOS","newCommandTimeout":"7200","app":"/Users/PERSONAL/Documents/repos/ProjectXYZ/dist/ios/ProjectXYZ.ipa","platformVersion":"9.3.2","deviceName":"iPhone 6","bundleId":"","automationName":"Appium","udid":"19d4f9e6e52dc0e42398bf05ebb1ffd6f0520219"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"iOS","newCommandTimeout":"7200","app":"/Users/PERSONAL/Documents/repos/ProjectXYZ/dist/ios/ProjectXYZ.ipa","platformVersion":"9.3.2","deviceName":"iPhone 6","bundleId":"","automationName":"Appium","udid":"19d4f9e6e52dc0e42398bf05ebb1ffd6f0520219"},null,null,null,null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1490637342008 (10:55:42 GMT-0700 (PDT))
[Appium] Creating new IosDriver (v1.18.0) session
[Appium] Capabilities:
[Appium]   platformName: 'iOS'
[Appium]   newCommandTimeout: '7200'
[Appium]   app: '/Users/Personal/Documents/repos/ProjectXYZ/dist/ios/ProjectXYZ.ipa'
[Appium]   platformVersion: '9.3.2'
[Appium]   deviceName: 'iPhone 6'
[Appium]   bundleId: ''
[Appium]   automationName: 'Appium'
[Appium]   udid: '19d4f9e6e52dc0e42398bf05ebb1ffd6f0520219'
[debug] [iOS] IosDriver version: 1.18.0
[BaseDriver] Capability 'newCommandTimeout' changed from string ('7200') to integer (7200). This may cause unexpected behavior
[BaseDriver] Session created with session id: dddbf6c3-bd3f-4006-9bdb-7a1fe2094767
[debug] [iOS] Xcode version set to 8.2.1
[iOS] SessionNotCreatedError: A new session could not be created. Details: Appium's IosDriver does not support xcode version 8.2.1. Apple has deprecated UIAutomation. Use the "XCUITest" automationName capability instead.
    at IosDriver.createSession$ (../../lib/driver.js:131:28)
    at tryCatch (/Users/PERSONAL/.nvm/versions/node/v6.0.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/PERSONAL/.nvm/versions/node/v6.0.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/PERSONAL/.nvm/versions/node/v6.0.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/PERSONAL/.nvm/versions/node/v6.0.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 { SessionNotCreatedError: A new session could not be created. Details: Appium's IosDriver does not support xcode version 8.2.1. Apple has deprecated UIAutomation. Use the "XCUITest" automationName capability instead.
    at IosDriver.createSession$ (../../lib/driver.js:131:28)
    at tryCatch (/Users/PERSONAL/.nvm/versions/node/v6.0.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/PERSONAL/.nvm/versions/node/v6.0.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/PERSONAL/.nvm/versions/node/v6.0.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/PERSONAL/.nvm/versions/node/v6.0.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37) jsonwpCode: 33 }
[HTTP] <-- POST /wd/hub/session 500 91 ms - 245 
<img width="440" alt="appiumerror" src="https://cloud.githubusercontent.com/assets/25352951/24370457/56c6a128-12dc-11e7-963c-e151a54f8b65.png">

**Comment by mykola-mokhnach** [comment]
This Appium inspector is outdated and is not supported anymore. Please use https://github.com/appium/appium-desktop/releases instead
