### ISSUE TITLE
Unable to run iOS tests with locally installed Appium server

### ISSUE THREAD

**Issue by JaniJegoroff** [appium/appium#8115]
## The problem

I'm unable to run iOS tests against `locally` installed Appium server whereas `globally` installed Appium server works fine. Appium server version is the same in both cases and app is prebuild.

`Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65`

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4-beta
* Last Appium version that did not exhibit the issue (if applicable): 1.6.3
* Desktop OS/version used to run Appium: Mac OS 10.12.4
* Node.js version (unless using Appium.app|exe): v7.2.0
* Mobile platform/version under test: iOS 10.3, Xcode 8.3
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI

## Details

Test run against locally installed Appium server fails with an error
```
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:369:15)
    at tryCatch (/Users/janijegoroff/projects/mobile-ios-app/mobile-common/bdd/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/janijegoroff/projects/mobile-ios-app/mobile-common/bdd/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/janijegoroff/projects/mobile-ios-app/mobile-common/bdd/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/janijegoroff/projects/mobile-ios-app/mobile-common/bdd/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:369:15)
    at tryCatch (/Users/janijegoroff/projects/mobile-ios-app/mobile-common/bdd/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/janijegoroff/projects/mobile-ios-app/mobile-common/bdd/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/janijegoroff/projects/mobile-ios-app/mobile-common/bdd/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/janijegoroff/projects/mobile-ios-app/mobile-common/bdd/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:369:15)
    at tryCatch (/Users/janijegoroff/projects/mobile-ios-app/mobile-common/bdd/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/janijegoroff/projects/mobile-ios-app/mobile-common/bdd/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/janijegoroff/projects/mobile-ios-app/mobile-common/bdd/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/janijegoroff/projects/mobile-ios-app/mobile-common/bdd/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

## Link to Appium logs

See logs for both success and failed cases
https://gist.github.com/JaniJegoroff/9bffa4d87fcdb19d1b7ebb1b5acfa8de

## Code To Reproduce Issue [ Good To Have ]

**Common for both global and local test runs**
- App is prebuild
- Appium server version is the same

**Test run against globally installed Appium server**
1. Install Appium server globally: `npm install -g appium@beta`
2. Launch globally installed Appium server: `appium`
3. Launch the tests

Result: test is passed

**Test run against locally installed Appium server**
1. Define `package.json`
```
{
  "name": "xxx-test-runner",
  "version": "1.0.0",
  "private": true,
  "devDependencies": {
    "appium": "1.6.4-beta"
  }
}
```
2. Install Appium server locally: `npm install`
3. Launch test where Appium server is started with command: `node node_modules/appium -a localhost -p 4723 --log-level error`

Result: test fails with an error

**Comment by mykola-mokhnach** [comment]
Can you attach appium and xcodebuild log for the failed case?

**Comment by JaniJegoroff** [comment]
@mykola-mokhnach gist updated with full logs:
https://gist.github.com/JaniJegoroff/9bffa4d87fcdb19d1b7ebb1b5acfa8de#file-xcode-log-and-appium-for-local-test-run

**Comment by mykola-mokhnach** [comment]
It fails because of WDA warning in iOS 8.3. Try to apply [this patch](https://github.com/facebook/WebDriverAgent/pull/525) to local WDA source.

**Comment by JaniJegoroff** [comment]
I can confirm that patch https://github.com/facebook/WebDriverAgent/pull/525 will fix the issue.

**Comment by garkinv** [comment]
But I still facing this problem :( And patch didn't help for me
Please take a look:
https://gist.github.com/garkinv/ccaab276356c9584b1d2ba28c09662f9

**Comment by JaniJegoroff** [comment]
@garkinv How did you apply the patch in your environment?

**Comment by garkinv** [comment]
@JaniJegoroff Yes, I did add changed row to my project and build it in Xcode, should I do anything else?

**Comment by JaniJegoroff** [comment]
Sounds like you didn't apply the patch correctly - there's no need to build anything from Xcode. I modified my local WDA source as follows:
```
Janis-iMac:bdd janijegoroff$ cat node_modules/appium-xcuitest-driver/WebDriverAgent/Configurations/ProjectSettings.xcconfig

<clip>GCC_...</clip>
<clip>GLANG_...</clip>

WARNING_CFLAGS = $(inherited) -Weverything -Wno-objc-missing-property-synthesis -Wno-unused-macros -Wno-disabled-macro-expansion -Wno-gnu-statement-expression -Wno-language-extension-token -Wno-overriding-method-mismatch -Wno-missing-variable-declarations -Rno-module-build -Wno-auto-import -Wno-objc-interface-ivars -Wno-documentation-unknown-command -Wno-reserved-id-macro -Wno-unused-parameter -Wno-gnu-conditional-omitted-operand -Wno-explicit-ownership-type -Wno-date-time -Wno-cast-align -Wno-cstring-format-directive -Wno-double-promotion -Wno-unguarded-availability
```

**Comment by garkinv** [comment]
@JaniJegoroff According to last changes in [#525](https://github.com/facebook/WebDriverAgent/pull/525/files) changes I have added this flag in the end of file:
>  -Wno-partial-availability

**Comment by mykola-mokhnach** [comment]
Closing this as non-Appium issue

**Comment by garkinv** [comment]
@JaniJegoroff Sorry, everything is ok! I just restarted my appium after changes in xcconfig file.
Thanks!
