### ISSUE TITLE
How to ignore the check steps that the package/activity had been launched is correct or not

### ISSUE THREAD

**Issue by tlllly** [appium/appium#8125]
## The problem
How to ingnore the check steps that the package/activity had been launched is correct or not

## Environment

java client build version or git revision if you use some shapshot: jave-client-5.0.0-BETA2
Appium server version or git revision if you use some shapshot: Appium 1.6.3
Desktop OS/version used to run Appium if necessary: Windows 10
Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: v6.9.1
Mobile platform/version under test: Android 6.0 Samsung Galaxy S7 edge
Real device or emulator/simulator: Real device

## Details

I use xxx..MainActivity to launch under test application, it has been launched successfully. After launched the application, there are two scenarios. First, if i have login the application, after launched the application, the activity is xxx.mainActivity， but if i have not login the application, the activity is xxxx.LoginDialogActivity. So the test will be shut down ,because the activity is not correct.
Because the activity is uncertainty, so i can't use "appWaitActivity" capability. I just want to ignore the check steps. 

## Link to Appium logs

**[debug] [ADB] Found package: 'air.tv.douyu.android' and fully qualified activity name : 'tv.douyu.view.activity.LoginDialogActivity'**
**[debug] [ADB] Incorrect package and activity. Retrying.
[ADB] Error: air.tv.douyu.android/tv.douyu.view.activity.MainActivity or air.tv.douyu.android.tv.douyu.view.activity.MainActivity never started**
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at ADB.callee$0$0$ (../../../lib/tools/apk-utils.js:147:7)
    at tryCatch (C:\Users\tangleilei\AppData\Roaming\npm\node_modules\appium\node_modules\.5.8.24@babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\tangleilei\AppData\Roaming\npm\node_modules\appium\node_modules\.5.8.24@babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\tangleilei\AppData\Roaming\npm\node_modules\appium\node_modules\.5.8.24@babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\tangleilei\AppData\Roaming\npm\node_modules\appium\node_modules\.5.8.24@babel-runtime\regenerator\runtime.js:136:37)
 Error: air.tv.douyu.android/tv.douyu.view.activity.MainActivity or air.tv.douyu.android.tv.douyu.view.activity.MainActivity never started
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at ADB.callee$0$0$ (../../../lib/tools/apk-utils.js:147:7)
    at tryCatch (C:\Users\tangleilei\AppData\Roaming\npm\node_modules\appium\node_modules\.5.8.24@babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\tangleilei\AppData\Roaming\npm\node_modules\appium\node_modules\.5.8.24@babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\tangleilei\AppData\Roaming\npm\node_modules\appium\node_modules\.5.8.24@babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\tangleilei\AppData\Roaming\npm\node_modules\appium\node_modules\.5.8.24@babel-runtime\regenerator\runtime.js:136:37)
[ADB] Error: Error occured while starting App. Original error: air.tv.douyu.android/tv.douyu.view.activity.MainActivity or air.tv.douyu.android.tv.douyu.view.activity.MainActivity never started
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at ADB.callee$0$0$ (../../../lib/tools/apk-utils.js:77:9)
    at tryCatch (C:\Users\tangleilei\AppData\Roaming\npm\node_modules\appium\node_modules\.5.8.24@babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\tangleilei\AppData\Roaming\npm\node_modules\appium\node_modules\.5.8.24@babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\tangleilei\AppData\Roaming\npm\node_modules\appium\node_modules\.5.8.24@babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\tangleilei\AppData\Roaming\npm\node_modules\appium\node_modules\.5.8.24@babel-runtime\regenerator\runtime.js:136:37)
 Error: Error occured while starting App. Original error: air.tv.douyu.android/tv.douyu.view.activity.MainActivity or air.tv.douyu.android.tv.douyu.view.activity.MainActivity never started
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at ADB.callee$0$0$ (../../../lib/tools/apk-utils.js:77:9)
    at tryCatch (C:\Users\tangleilei\AppData\Roaming\npm\node_modules\appium\node_modules\.5.8.24@babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\tangleilei\AppData\Roaming\npm\node_modules\appium\node_modules\.5.8.24@babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\tangleilei\AppData\Roaming\npm\node_modules\appium\node_modules\.5.8.24@babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\tangleilei\AppData\Roaming\npm\node_modules\appium\node_modules\.5.8.24@babel-runtime\regenerator\runtime.js:136:37)
[MJSONWP] Encountered internal error running command: Error: Error occured while starting App. Original error: air.tv.douyu.android/tv.douyu.view.activity.MainActivity or air.tv.douyu.android.tv.douyu.view.activity.MainActivity never started
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at ADB.callee$0$0$ (../../../lib/tools/apk-utils.js:77:9)
    at tryCatch (C:\Users\tangleilei\AppData\Roaming\npm\node_modules\appium\node_modules\.5.8.24@babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\tangleilei\AppData\Roaming\npm\node_modules\appium\node_modules\.5.8.24@babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\tangleilei\AppData\Roaming\npm\node_modules\appium\node_modules\.5.8.24@babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\tangleilei\AppData\Roaming\npm\node_modules\appium\node_modules\.5.8.24@babel-runtime\regenerator\runtime.js:136:37)

**Comment by amedvedjev** [comment]
had same issue. with Appium 1.5.3 it was nice feature to skip:
```
capabilities.setCapability("waitForAppScript","$.delay(100); true;");
```

now i just added workaround by adding all possible activities client can start from:
```
capabilities.setCapability("appWaitActivity",
                            "xx.xxxx.activity.LandingPageActivity, " +
                                    "xx.xxxx.activity.SplashScreenActivity, " +
                                    "xx.xxxx.registration.xxxxx.xxxxxxxx");
```

**Comment by mykola-mokhnach** [comment]
Guys, check this [PR](https://github.com/appium/appium-adb/pull/196)
The feature might be useful for you both (note, that it requires Appium 1.6.4-beta to be installed)

**Comment by amedvedjev** [comment]
@mykola-mokhnach works! thanks.

**Comment by mykola-mokhnach** [comment]
@tlllly does it work for you? Can the issue be closed?
