### ISSUE TITLE
Can't install APK into AVD created in Android Studio

### ISSUE THREAD

**Issue by VivaLosDoyers** [appium/appium#8140]
With the recent changes to the Android SDK, on this new workstation setup, I'm installing only Android Studio, and using its build-in SDK and AVD manager to get everything installed.

Unfortunately, when I try to run a test with Appium, it fails when trying to install the specified APK:

```
[debug] [AndroidDriver] App was not copied, so not deleting
[MJSONWP] Encountered internal error running command: Error: packageAndLaunchActivityFromManifest failed. Original error: Command '/Users/mmiller/Library/Android/sdk/build-tools/25.0.2/aapt dump badging /Users/mmiller/appium/Mezzanine.apk' exited with code 1
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at ADB.callee$0$0$ (../../../lib/tools/android-manifest.js:88:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 1217 ms - 334 
```

Full Appium log available here: https://gist.github.com/VivaLosDoyers/e00ca8c3486b7d543acdf30a1516030e

I've tried this with both 1.6.3 and 1.6.4@beta.2, but the problem occurs in both.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): ???
* Desktop OS/version used to run Appium: macOS 10.12.4
* Node.js version (unless using Appium.app|exe): 7.7.4
* Mobile platform/version under test: Android 6.0.0
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: CLI

**Comment by mykola-mokhnach** [comment]
What is the output of this command in terminal window?

```
/Users/mmiller/Library/Android/sdk/build-tools/25.0.2/aapt dump badging /Users/mmiller/appium/Mezzanine.apk
```

**Comment by VivaLosDoyers** [comment]
Yeah looks like my APK was corrupted. I'm surprised by that since I've been using that same file on the same disk for ages. Anyway, closing this. Thanks for the help!
