### ISSUE TITLE
Appium install - Windows 8.1

### ISSUE THREAD

**Issue by pure4Sk** [appium/appium#8166]
## The problem
I am trying to isntall appium 

> npm install -g appium

But i am getting error:

```
C:\Project\taf>npm install -g appium
C:\Users\JE11954\AppData\Roaming\npm\appium -> C:\Users\JE11954\AppData\Roaming\
npm\node_modules\appium\build\lib\main.js

> sqlite3@3.1.8 install C:\Users\JE11954\AppData\Roaming\npm\node_modules\appium
\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.am
azonaws.com/sqlite3/v3.1.8/node-v46-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.8 and node@4.6.0
(node-v46 ABI) (falling back to source compile with node-gyp)
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
  unpack_sqlite_dep
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targ
ets(356,5): error MSB6006: "CL.exe" exited with code -1073741515. [C:\Users\JE1
1954\AppData\Roaming\npm\node_modules\appium\node_modules\sqlite3\build\deps\sq
lite3.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\JE11954\AppData\Roaming\npm\
node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\JE11954\\AppD
ata\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback
-to-build" "--module=C:\\Users\\JE11954\\AppData\\Roaming\\npm\\node_modules\\ap
pium\\node_modules\\sqlite3\\lib\\binding\\node-v46-win32-x64\\node_sqlite3.node
" "--module_name=node_sqlite3" "--module_path=C:\\Users\\JE11954\\AppData\\Roami
ng\\npm\\node_modules\\appium\\node_modules\\sqlite3\\lib\\binding\\node-v46-win
32-x64"
gyp ERR! cwd C:\Users\JE11954\AppData\Roaming\npm\node_modules\appium\node_modul
es\sqlite3
gyp ERR! node -v v4.6.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.e
xe C:\Users\JE11954\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js bu
ild --fallback-to-build --module=C:\Users\JE11954\AppData\Roaming\npm\node_modul
es\appium\node_modules\sqlite3\lib\binding\node-v46-win32-x64\node_sqlite3.node
--module_name=node_sqlite3 --module_path=C:\Users\JE11954\AppData\Roaming\npm\no
de_modules\appium\node_modules\sqlite3\lib\binding\node-v46-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\JE11954\AppDat
a\Roaming\npm\node_modules\appium\node_modules\sqlite3\node_modules\node-pre-gyp
\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:829:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/chi
ld_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 6.3.9600
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\JE11
954\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\sqlite3\\node_mo
dules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\JE11954\AppData\Roaming\npm\node_modules\appium\n
ode_modules\sqlite3
node-pre-gyp ERR! node -v v4.6.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.31
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\JE11954\AppData\Roa
ming\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --modul
e=C:\Users\JE11954\AppData\Roaming\npm\node_modules\appium\node_modules\sqlite3\
lib\binding\node-v46-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --mo
dule_path=C:\Users\JE11954\AppData\Roaming\npm\node_modules\appium\node_modules\
sqlite3\lib\binding\node-v46-win32-x64' (1)
npm WARN Error: EPERM: operation not permitted, lstat 'C:\Users\JE11954\AppData\
Roaming\npm\node_modules\appium\node_modules\sqlite3\node_modules\node-pre-gyp\n
ode_modules\npmlog\node_modules\gauge\node_modules\string-width\node_modules\cod
e-point-at\node_modules'
npm WARN     at Error (native)
npm WARN  { [Error: EPERM: operation not permitted, lstat 'C:\Users\JE11954\AppD
ata\Roaming\npm\node_modules\appium\node_modules\sqlite3\node_modules\node-pre-g
yp\node_modules\npmlog\node_modules\gauge\node_modules\string-width\node_modules
\code-point-at\node_modules']
npm WARN   errno: -4048,
npm WARN   code: 'EPERM',
npm WARN   syscall: 'lstat',
npm WARN   path: 'C:\\Users\\JE11954\\AppData\\Roaming\\npm\\node_modules\\appiu
m\\node_modules\\sqlite3\\node_modules\\node-pre-gyp\\node_modules\\npmlog\\node
_modules\\gauge\\node_modules\\string-width\\node_modules\\code-point-at\\node_m
odules' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@3.1.8 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.1.8 install script 'node-pre-gyp install --fall
back-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sqlite3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\JE11954\AppData\Roaming\npm-cache\_logs\2017-04-04T11_48_3
0_632Z-debug.log
```

I tryied **appium-doctor** but for Android is everything ok.

> C:\Project\taf>appium-doctor --android
> info AppiumDoctor Appium Doctor v.1.4.2
> info AppiumDoctor ### Diagnostic starting ###
> info AppiumDoctor  ? The Node.js binary was found at: C:\Program Files\nodejs\no
> de.exe
> info AppiumDoctor  ? Node version is 4.6.0
> info AppiumDoctor  ? ANDROID_HOME is set to: C:\Users\JE11954\AppData\Local\Andr
> oid\sdk
> info AppiumDoctor  ? JAVA_HOME is set to: C:\Program Files\Java\jdk1.8.0_121
> info AppiumDoctor  ? adb exists at: C:\Users\JE11954\AppData\Local\Android\sdk\p
> latform-tools\adb.exe
> info AppiumDoctor  ? android exists at: C:\Users\JE11954\AppData\Local\Android\s
> dk\tools\android.bat
> info AppiumDoctor  ? emulator exists at: C:\Users\JE11954\AppData\Local\Android\
> sdk\tools\emulator.exe
> info AppiumDoctor  ? Bin directory of %JAVA_HOME% is set
> info AppiumDoctor ### Diagnostic completed, no fix needed. ###
> info AppiumDoctor
> info AppiumDoctor Everything looks good, bye!
> info AppiumDoctor

## Environment

Node.js: v4.6.0
node-gyp -v v3.4.0
npm v4.4.4
Windows 8.1

**Comment by mykola-mokhnach** [comment]
is this reproducible with 1.6.4-beta?

**Comment by pure4Sk** [comment]
With 1.6.4-beta there is something new:

```
C:\Project\taf>npm install -g appium@1.6.4-beta
npm WARN deprecated babel-core@5.8.24: Babel 5 is no longer being maintained. Up
grade to Babel 6.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher
 to avoid a RegExp DoS issue
npm WARN deprecated line-numbers@0.2.0: Copy its ~20 LOC directly into your code
 instead.
C:\Users\JE11954\AppData\Roaming\npm\appium -> C:\Users\JE11954\AppData\Roaming\
npm\node_modules\appium\build\lib\main.js

> appium-chromedriver@2.11.0 install C:\Users\JE11954\AppData\Roaming\npm\node_m
odules\appium\node_modules\appium-chromedriver
> node install-npm.js

info Chromedriver Install Installing Chromedriver version '2.28' for platform 'w
in' and architecture '32'
info Chromedriver Install Opening temp file to write chromedriver_win32 to...
info Chromedriver Install Downloading https://chromedriver.storage.googleapis.co
m/2.28/chromedriver_win32.zip...
RequestError: Error: connect ETIMEDOUT 216.58.211.112:443
    at new RequestError (C:\Users\JE11954\AppData\Roaming\npm\node_modules\appiu
m\node_modules\request-promise\lib\errors.js:11:15)
    at Request.RP$callback [as _callback] (C:\Users\JE11954\AppData\Roaming\npm\
node_modules\appium\node_modules\request-promise\lib\rp.js:60:32)
    at self.callback (C:\Users\JE11954\AppData\Roaming\npm\node_modules\appium\n
ode_modules\request\request.js:188:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (C:\Users\JE11954\AppData\Roaming\npm\node_modules
\appium\node_modules\request\request.js:884:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at TLSSocket.socketErrorListener (_http_client.js:269:9)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at emitErrorNT (net.js:1269:8)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
C:\Users\JE11954\AppData\Roaming\npm
`-- (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.x (node_modules\appiu
m\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appium-chromedriver@2.11.0 install: `node install-npm.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the appium-chromedriver@2.11.0 install script 'node install-n
pm.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the appium-chromedriver p
ackage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install-npm.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs appium-chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls appium-chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\JE11954\AppData\Roaming\npm-cache\_logs\2017-04-04T12_22_2
4_048Z-debug.log
```

**Comment by mykola-mokhnach** [comment]
Are you behind corporate proxy? I can ping that IP address

**Comment by pure4Sk** [comment]
Ah..yeah i am. So i tryied this (most of the time it works): 

> npm install -g appium@1.6.4-beta --ignore_ssl --proxy http://10.165.42.170:8080

```
C:\Project\taf>npm install -g appium@1.6.4-beta --ignore_ssl --proxy http://10.1
65.42.170:8080
npm WARN deprecated babel-core@5.8.24: Babel 5 is no longer being maintained. Up
grade to Babel 6.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher
 to avoid a RegExp DoS issue
npm WARN deprecated line-numbers@0.2.0: Copy its ~20 LOC directly into your code
 instead.
C:\Users\JE11954\AppData\Roaming\npm\appium -> C:\Users\JE11954\AppData\Roaming\
npm\node_modules\appium\build\lib\main.js

> appium-chromedriver@2.11.0 install C:\Users\JE11954\AppData\Roaming\npm\node_m
odules\appium\node_modules\appium-chromedriver
> node install-npm.js

info Chromedriver Install Installing Chromedriver version '2.28' for platform 'w
in' and architecture '32'
info Chromedriver Install Opening temp file to write chromedriver_win32 to...
info Chromedriver Install Downloading https://chromedriver.storage.googleapis.co
m/2.28/chromedriver_win32.zip...
RequestError: Error: connect ETIMEDOUT 172.217.23.208:443
    at new RequestError (C:\Users\JE11954\AppData\Roaming\npm\node_modules\appiu
m\node_modules\request-promise\lib\errors.js:11:15)
    at Request.RP$callback [as _callback] (C:\Users\JE11954\AppData\Roaming\npm\
node_modules\appium\node_modules\request-promise\lib\rp.js:60:32)
    at self.callback (C:\Users\JE11954\AppData\Roaming\npm\node_modules\appium\n
ode_modules\request\request.js:188:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (C:\Users\JE11954\AppData\Roaming\npm\node_modules
\appium\node_modules\request\request.js:884:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at TLSSocket.socketErrorListener (_http_client.js:269:9)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at emitErrorNT (net.js:1269:8)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
C:\Users\JE11954\AppData\Roaming\npm
`-- (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.x (node_modules\appiu
m\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appium-chromedriver@2.11.0 install: `node install-npm.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the appium-chromedriver@2.11.0 install script 'node install-n
pm.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the appium-chromedriver p
ackage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install-npm.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs appium-chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls appium-chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\JE11954\AppData\Roaming\npm-cache\_logs\2017-04-04T12_30_0
2_200Z-debug.log

C:\Project\taf>npm install -g appium@1.6.4-beta --ignore_ssl --proxy http://10.1
65.42.170:8080

```

**Comment by mykola-mokhnach** [comment]
Sorry then - this has nothing to do with Appium. You need to check how to properly combine your proxy with npm

**Comment by pure4Sk** [comment]
Ok, thanks..atleast i know where is problem now.
