### ISSUE TITLE
unable to take screen shot.

### ISSUE THREAD

**Issue by VenkateshPS** [appium/appium#8173]
I have added Applitools jar, but fails to take screen shot with below exception

[debug] [MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["5f11c367-4723-481c-893f-0535d6e33420"]
[debug] [XCUITest] Executing command 'getScreenshot'
[simctl] Error: simctl error running 'io': Invalid device: e72a1083c25ebf44c861e994e7b805258cf88344
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:60:13)
    at simCommand$ (../../lib/simctl.js:26:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: simctl error running 'io': Invalid device: e72a1083c25ebf44c861e994e7b805258cf88344
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:60:13)
    at simCommand$ (../../lib/simctl.js:26:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[MJSONWP] Encountered internal error running command: Error: simctl error running 'io': Invalid device: e72a1083c25ebf44c861e994e7b805258cf88344
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:60:13)
    at simCommand$ (../../lib/simctl.js:26:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- GET /wd/hub/session/5f11c367-4723-481c-893f-0535d6e33420/screenshot 500 263 ms - 254 
[HTTP] --> POST /wd/hub/session/5f11c367-4723-481c-893f-0535d6e33420/elements {"using":"id","value":"Cancel"}

**Comment by VenkateshPS** [comment]
using javaclient 5.0.0-BETA4 and appium Appium v1.6.4-beta.2

**Comment by mykola-mokhnach** [comment]
This is known [bug](https://github.com/appium/appium/issues/8146) and it is already fixed. 

```
npm remove -g appium
npm install -g appium@1.6.4-beta
```

will fix the problem

**Comment by VenkateshPS** [comment]
I am using 1.6.4-beta.2, still do I need to uninstall ?

**Comment by mykola-mokhnach** [comment]
yes if you want to have the recent updates

**Comment by VenkateshPS** [comment]
works fine thanks @mykola-mokhnach
