### ISSUE TITLE
[Appium] Error: Syntax error in node configuration file

### ISSUE THREAD

**Issue by taraa62** [appium/appium#8187]
Hello
I have a problem with the connect of appium selenium grid on mac os (10.12.4)

appium -v 1.6.4-beta.2
node -v v6.10.1
selenium grid 2.53(3.3.1)

config file ios_6.json

{ 
  "capabilities":
      [
        {
		"version":"10.1.1",
          "browserName": "iPhone 6s Plus",
          "maxInstances": 1,
          "platform":"MAC",
          "device_type": "tablet",
          "devicePlatform":"MAC",
          "deviceName":"d________245988b768"
          }
      ],
  "configuration":
  {
    "cleanUpCycle":2000,
    "timeout":300000,
    "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
    "url":"http://192.168.31.185:6001/wd/hub",
    "host": "192.168.31.185",
    "port": 6001,
    "maxSession": 1,
    "register": true,
    "registerCycle": 5000,
    "hubPort": 4444,
    "hubHost": "192.168.31.185"
  }
}

Error:

a-prozorya:~ a-prozorya$ appium  --session-override --full-reset --nodeconfig /Users/a-prozorya/Desktop/ios_6.json --port 5001
[Appium] Welcome to Appium v1.6.4-beta.2 (REV 2a6bb5c46fdea0168cc717c16abc877ca48a32e1)
[Appium] Non-default server args:
[Appium]   port: 5001
[Appium]   sessionOverride: true
[Appium]   nodeconfig: /Users/a-prozorya/Desktop/ios_6.json
[Appium]   fullReset: true
[Appium] Deprecated server args:
[Appium]   --full-reset => --default-capabilities '{"fullReset":true}'
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   fullReset: true
[Appium] Error: Syntax error in node configuration file: Unexpected token \ in JSON at position 1
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:60:13)
    at postRequest$ (../../lib/grid-register.js:42:12)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at Promise.F (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at postRequest (../../lib/grid-register.js:94:24)
    at registerNode$ (../../lib/grid-register.js:20:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: Syntax error in node configuration file: Unexpected token \ in JSON at position 1
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:60:13)
    at postRequest$ (../../lib/grid-register.js:42:12)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at Promise.F (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at postRequest (../../lib/grid-register.js:94:24)
    at registerNode$ (../../lib/grid-register.js:20:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)

/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:69
      return { type: "throw", arg: err.data };
                                      ^
TypeError: Cannot read property 'data' of undefined
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:69:39)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at runMicrotasksCallback (internal/process/next_tick.js:64:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

I checked different options and the validity of the file, nothing works.
Changing pors and addresses fails

**Comment by mykola-mokhnach** [comment]
Make sure your configuration file is a valid JSON file. Use, for example, http://jsonlint.com/ to validate it.

**Comment by taraa62** [comment]
This is a copy of the configuration and it is validated, and I held it ten times before writing comment

**Comment by semeenaa** [comment]
Hello,  
I am new to Appium Grid -Node connection . I am facing the similar problem when try to register the node with below configuration. Could you please help me if you were able to solve the above mentioned issue. I validated my Json and is valid.

node: -v v6.10.0
npm : 4.5.0
Appium: 1.6.4
Selinium Grid :3.3.1

error  is - 
C:\Users\srafi>appium -a localhost -p 4740 -bp 4741 --udid 9885e6304b5747564a --
nodeconfig D:\eclipse\QA_Projects\jsonTestDataFile\node_s7.json
[Appium] Welcome to Appium v1.6.4
[Appium] Non-default server args:
[Appium]   address: localhost
[Appium]   port: 4740
[Appium]   bootstrapPort: 4741
[Appium]   nodeconfig: D:\eclipse\QA_Projects\jsonTestDataFile\node_s7.json
[Appium]   udid: 9885e6304b5747564a
[Appium] Deprecated server args:
[Appium]   -U,--udid => --default-capabilities '{"udid":"9885e6304b5747564a"}'
[Appium] Default capabilities, which will be added to each request unless overri
dden by desired capabilities:
[Appium]   udid: '9885e6304b5747564a'
 in JSON at position 487rror in node configuration file: Unexpected token
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at postRequest$ (../../lib/grid-register.js:42:12)
    at tryCatch (C:\Users\srafi\AppData\Roaming\npm\node_modules\appium\node_mod
ules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\srafi\AppData\Ro
aming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:
315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\U
sers\srafi\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\re
generator\runtime.js:100:21)
    at invoke (C:\Users\srafi\AppData\Roaming\npm\node_modules\appium\node_modul
es\babel-runtime\regenerator\runtime.js:136:37)
    at enqueueResult (C:\Users\srafi\AppData\Roaming\npm\node_modules\appium\nod
e_modules\babel-runtime\regenerator\runtime.js:185:17)
    at Promise.F (C:\Users\srafi\AppData\Roaming\npm\node_modules\appium\node_mo
dules\core-js\library\modules\$.export.js:30:36)
    at AsyncIterator.enqueue (C:\Users\srafi\AppData\Roaming\npm\node_modules\ap
pium\node_modules\babel-runtime\regenerator\runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (C:\Users\srafi\Ap
pData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\run
time.js:100:21) ........etc

**Comment by taraa62** [comment]
Check the validity of the file at http://jsonlint.com/
Select a good format for saving (utf-8)
if not help, put your file

**Comment by semeenaa** [comment]
Thanks for the Update. the Json file is valid only. I installed latest version of nodejs with Repare as option and restarted the server.. Now it is working :)
