### ISSUE TITLE
[Appium 1.6.4] New release - Using "driver.runAppInBackground()" Method isn't recognize elements after implement

### ISSUE THREAD

**Issue by eyalabush** [appium/appium#8200]
Intelij - Latest version
Appium - Latest version
Java client: 5.0.0
Selenium - latest version
Windows 10
app = android app

The appium run the driver.runAppInBackground(1): method
and then after the app is back from the background, elements not found exception,
It works in appium 1.6.4-Beta 6

Logs:
[ADB] 1 device(s) connected
[ADB] Running 'C:\SDK\platform-tools\adb.exe' with args: ["-P",5037,"-s","9b2161ea","shell","dumpsys","window","windows"]
[ADB] Found package: 'com.tgs.systems.lmtdeal' and fully qualified activity name : 'com.tgs.systems.ui.activities.LoginActivity'
[ADB] Incorrect package and activity. Retrying.
[ADB] Getting focused package and activity
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\SDK\platform-tools\adb.exe' with args: ["-P",5037,"-s","9b2161ea","shell","dumpsys","window","windows"]
[ADB] Found package: 'com.tgs.systems.lmtdeal' and fully qualified activity name : 'com.tgs.systems.ui.activities.LoginActivity'
[ADB] Incorrect package and activity. Retrying.
[ADB] Error: com.cyanogenmod.trebuchet/com.android.launcher3.Launcher or com.cyanogenmod.trebuchet.com.android.launcher3.Launcher never started
    at Object.wrappedLogger.errorAndThrow (C:\Users\a.a\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:63:13)
    at ADB.callee$0$0$ (C:\Users\a.a\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\apk-utils.js:147:7)
    at tryCatch (C:\Users\a.a\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\a.a\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\a.a\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\a.a\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
 Error: com.cyanogenmod.trebuchet/com.android.launcher3.Launcher or com.cyanogenmod.trebuchet.com.android.launcher3.Launcher never started
    at Object.wrappedLogger.errorAndThrow (C:\Users\a.a\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:63:13)
    at ADB.callee$0$0$ (C:\Users\a.a\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\apk-utils.js:147:7)
    at tryCatch (C:\Users\a.a\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\a.a\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\a.a\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\a.a\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[ADB] Error: Error occured while starting App. Original error: com.cyanogenmod.trebuchet/com.android.launcher3.Launcher or com.cyanogenmod.trebuchet.com.android.launcher3.Launcher never started
    at Object.wrappedLogger.errorAndThrow (C:\Users\a.a\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:63:13)
    at ADB.callee$0$0$ (C:\Users\a.a\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\apk-utils.js:77:9)
    at tryCatch (C:\Users\a.a\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\a.a\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\a.a\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\a.a\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
 Error: Error occured while starting App. Original error: com.cyanogenmod.trebuchet/com.android.launcher3.Launcher or com.cyanogenmod.trebuchet.com.android.launcher3.Launcher never started
    at Object.wrappedLogger.errorAndThrow (C:\Users\a.a\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:63:13)
    at ADB.callee$0$0$ (C:\Users\a.a\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\apk-utils.js:77:9)
    at tryCatch (C:\Users\a.a\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\a.a\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\a.a\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\a.a\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[MJSONWP] Encountered internal error running command: Error: Error occured while starting App. Original error: com.cyanogenmod.trebuchet/com.android.launcher3.Launcher or com.cyanogenmod.trebuchet.com.android.launcher3.Launcher never started
    at Object.wrappedLogger.errorAndThrow (C:\Users\a.a\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:63:13)
    at ADB.callee$0$0$ (C:\Users\a.a\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\apk-utils.js:77:9)
    at tryCatch (C:\Users\a.a\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\a.a\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\a.a\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\a.a\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session/e80db122-619d-4345-be8c-3400f647c9c1/appium/app/background 500 24398 ms - 351

**Comment by mykola-mokhnach** [comment]
Please attach Appium log

**Comment by dpgraham** [comment]
Closing due to inactivity

**Comment by marwanakeel** [comment]
try this 
`
protected void tapAnywhere() {
		sleep(1000);
		TouchAction action = new TouchAction(driver);
		action.tap(10, 10).perform();
	}
`
It worked for me
