### ISSUE TITLE
appium desktop : [MJSONWP] Encountered internal error running command: Error: packageAndLaunchActivityFromManifest failed. Original error: Path must be a string. Received null 

### ISSUE THREAD

**Issue by Shahunks** [appium/appium#8220]
## The problem

after setting the android desired capabilites and starting the  server i get this error on appium desktop 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MACOSX
* Node.js version (unless using Appium.app|exe): 6.10.2
* Mobile platform/version under test:Android 7.1
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## error in desktop

[ADB] The ANDROID_HOME environment variable is not set to the Android SDK root directory path. ANDROID_HOME is required for compatibility with SDK 23+. Checking along PATH for aapt.
[ADB] Using aapt from /usr/local/bin/aapt
[ADB] Extracting package and launch activity from manifest
[ADB] Error: packageAndLaunchActivityFromManifest failed. Original error: Path must be a string. Received null

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Please attach full Appium log.

also it's already clearly visible, that _ANDROID_HOME_ environment variable should be set.

**Comment by Shahunks** [comment]
@mykola-mokhnach path is clearly set please see the screen shots
![screen shot 2017-04-11 at 11 24 22 am](https://cloud.githubusercontent.com/assets/25055088/24900559/e5510bae-1ec1-11e7-9b1e-2cb050a5d0a3.png)
![screen shot 2017-04-11 at 2 18 52 pm](https://cloud.githubusercontent.com/assets/25055088/24900569/ec6d2cf6-1ec1-11e7-8df0-b17996876c38.png)

**Comment by mykola-mokhnach** [comment]
It might be , that appium daemon is executed in custom environment, so it does not see the var. And how about attaching the log?

**Comment by Shahunks** [comment]
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/Sachin/Downloads/zaptyQC-debug-1-760-5523.apk","appActivity":".ApiDemos","appiumVersion":"1.6.4","deviceName":"Andriod Emulator","platformName":"Android","platformVersion":"7.1.1","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/Sachin/Downloads/zaptyQC-debug-1-760-5523.apk","appActivity":".ApiDemos","appiumVersion":"1.6.4","deviceName":"Andriod Emulator","platformName":"Android","platformVersion":"7.1.1","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null,null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1491896042954 (13:04:02 GMT+0530 (IST))
[Appium] Creating new AndroidDriver (v1.15.0) session
[Appium] Capabilities:
[Appium]   app: '/Users/Sachin/Downloads/zaptyQC-debug-1-760-5523.apk'
[Appium]   appActivity: '.ApiDemos'
[Appium]   appiumVersion: '1.6.4'
[Appium]   deviceName: 'Andriod Emulator'
[Appium]   platformName: 'Android'
[Appium]   platformVersion: '7.1.1'
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true
[AndroidDriver] AndroidDriver version: 1.15.0
[BaseDriver] The following capabilities were provided, but are not recognized by appium: appiumVersion, connectHardwareKeyboard.
[BaseDriver] Session created with session id: db6cc15f-199d-45f5-8128-5019ce0a891d
[AndroidDriver] Getting Java version
[AndroidDriver] Java version is: 1.8.0_121
[ADB] Checking whether adb is present
[ADB] The ANDROID_HOME environment variable is not set to the Android SDK root directory path. ANDROID_HOME is required for compatibility with SDK 23+. Checking along PATH for adb.
[ADB] Using adb from /usr/local/bin/adb
[AndroidDriver] Retrieving device list
[ADB] Trying to find a connected android device
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[AndroidDriver] Looking for a device with Android '7.1.1'
[ADB] Setting device id to emulator-5554
[ADB] Getting device platform version
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/usr/local/bin/adb' with args: ["-P",5037,"-s","emulator-5554","shell","getprop","ro.build.version.release"]
[AndroidDriver] Using device: emulator-5554
[ADB] Checking whether adb is present
[ADB] The ANDROID_HOME environment variable is not set to the Android SDK root directory path. ANDROID_HOME is required for compatibility with SDK 23+. Checking along PATH for adb.
[ADB] Using adb from /usr/local/bin/adb
[ADB] Setting device id to emulator-5554
[BaseDriver] Using local app '/Users/Sachin/Downloads/zaptyQC-debug-1-760-5523.apk'
[AndroidDriver] Checking whether app is actually present
[AndroidDriver] Starting Android session
[ADB] Running '/usr/local/bin/adb' with args: ["-P",5037,"-s","emulator-5554","wait-for-device"]
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/usr/local/bin/adb' with args: ["-P",5037,"-s","emulator-5554","shell","echo","ping"]
[Logcat] Starting logcat capture
[AndroidDriver] Pushing settings apk to device...
[ADB] Running '/usr/local/bin/adb' with args: ["-P",5037,"-s","emulator-5554","install","/private/var/folders/5v/lqq__wt1181f97_jshy71yzh0000gp/T/AppTranslocation/BA415A8C-B29F-422D-A5D0-7882FA862156/d/Appium.app/Contents/Resources/app/node_modules/io.appium.settings/bin/settings_apk-debug.apk"]
[AndroidDriver] Pushing unlock helper app to device...
[ADB] Running '/usr/local/bin/adb' with args: ["-P",5037,"-s","emulator-5554","install","/private/var/folders/5v/lqq__wt1181f97_jshy71yzh0000gp/T/AppTranslocation/BA415A8C-B29F-422D-A5D0-7882FA862156/d/Appium.app/Contents/Resources/app/node_modules/appium-unlock/bin/unlock_apk-debug.apk"]
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/usr/local/bin/adb' with args: ["-P",5037,"-s","emulator-5554","shell","getprop","ro.build.version.sdk"]
[ADB] Device API level: 25
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/usr/local/bin/adb' with args: ["-P",5037,"-s","emulator-5554","shell","appops","set","io.appium.settings","android:mock_location","allow"]
[ADB] Getting device platform version
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/usr/local/bin/adb' with args: ["-P",5037,"-s","emulator-5554","shell","getprop","ro.build.version.release"]
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/usr/local/bin/adb' with args: ["-P",5037,"-s","emulator-5554","shell","wm","size"]
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/usr/local/bin/adb' with args: ["-P",5037,"-s","emulator-5554","shell","getprop","ro.product.model"]
[ADB] Current device property 'ro.product.model': Android SDK built for x86
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/usr/local/bin/adb' with args: ["-P",5037,"-s","emulator-5554","shell","getprop","ro.product.manufacturer"]
[ADB] Current device property 'ro.product.manufacturer': unknown
[AndroidDriver] Parsing package and activity from app manifest
[ADB] Checking whether aapt is present
[ADB] The ANDROID_HOME environment variable is not set to the Android SDK root directory path. ANDROID_HOME is required for compatibility with SDK 23+. Checking along PATH for aapt.
[ADB] Using aapt from /usr/local/bin/aapt
[ADB] Extracting package and launch activity from manifest
[ADB] Error: packageAndLaunchActivityFromManifest failed. Original error: Path must be a string. Received null
    at Object.wrappedLogger.errorAndThrow (/private/var/folders/5v/lqq__wt1181f97_jshy71yzh0000gp/T/AppTranslocation/BA415A8C-B29F-422D-A5D0-7882FA862156/d/Appium.app/Contents/Resources/app/node_modules/appium-support/lib/logging.js:60:13)
    at ADB.callee$0$0$ (/private/var/folders/5v/lqq__wt1181f97_jshy71yzh0000gp/T/AppTranslocation/BA415A8C-B29F-422D-A5D0-7882FA862156/d/Appium.app/Contents/Resources/app/node_modules/appium-adb/lib/tools/android-manifest.js:88:9)
    at tryCatch (/private/var/folders/5v/lqq__wt1181f97_jshy71yzh0000gp/T/AppTranslocation/BA415A8C-B29F-422D-A5D0-7882FA862156/d/Appium.app/Contents/Resources/app/node_modules/appium-adb/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/private/var/folders/5v/lqq__wt1181f97_jshy71yzh0000gp/T/AppTranslocation/BA415A8C-B29F-422D-A5D0-7882FA862156/d/Appium.app/Contents/Resources/app/node_modules/appium-adb/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/private/var/folders/5v/lqq__wt1181f97_jshy71yzh0000gp/T/AppTranslocation/BA415A8C-B29F-422D-A5D0-7882FA862156/d/Appium.app/Contents/Resources/app/node_modules/appium-adb/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/private/var/folders/5v/lqq__wt1181f97_jshy71yzh0000gp/T/AppTranslocation/BA415A8C-B29F-422D-A5D0-7882FA862156/d/Appium.app/Contents/Resources/app/node_modules/appium-adb/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: packageAndLaunchActivityFromManifest failed. Original error: Path must be a string. Received null
    at Object.wrappedLogger.errorAndThrow (/private/var/folders/5v/lqq__wt1181f97_jshy71yzh0000gp/T/AppTranslocation/BA415A8C-B29F-422D-A5D0-7882FA862156/d/Appium.app/Contents/Resources/app/node_modules/appium-support/lib/logging.js:60:13)
    at ADB.callee$0$0$ (/private/var/folders/5v/lqq__wt1181f97_jshy71yzh0000gp/T/AppTranslocation/BA415A8C-B29F-422D-A5D0-7882FA862156/d/Appium.app/Contents/Resources/app/node_modules/appium-adb/lib/tools/android-manifest.js:88:9)
    at tryCatch (/private/var/folders/5v/lqq__wt1181f97_jshy71yzh0000gp/T/AppTranslocation/BA415A8C-B29F-422D-A5D0-7882FA862156/d/Appium.app/Contents/Resources/app/node_modules/appium-adb/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/private/var/folders/5v/lqq__wt1181f97_jshy71yzh0000gp/T/AppTranslocation/BA415A8C-B29F-422D-A5D0-7882FA862156/d/Appium.app/Contents/Resources/app/node_modules/appium-adb/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/private/var/folders/5v/lqq__wt1181f97_jshy71yzh0000gp/T/AppTranslocation/BA415A8C-B29F-422D-A5D0-7882FA862156/d/Appium.app/Contents/Resources/app/node_modules/appium-adb/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/private/var/folders/5v/lqq__wt1181f97_jshy71yzh0000gp/T/AppTranslocation/BA415A8C-B29F-422D-A5D0-7882FA862156/d/Appium.app/Contents/Resources/app/node_modules/appium-adb/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[AndroidDriver] Shutting down Android driver
[AndroidDriver] Called deleteSession but bootstrap wasn't active
[Logcat] Stopping logcat capture
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/usr/local/bin/adb' with args: ["-P",5037,"-s","emulator-5554","shell","am","force-stop","io.appium.unlock"]
[AndroidDriver] Not cleaning generated files. Add `clearSystemFiles` capability if wanted.
[MJSONWP] Encountered internal error running command: Error: packageAndLaunchActivityFromManifest failed. Original error: Path must be a string. Received null
    at Object.wrappedLogger.errorAndThrow (/private/var/folders/5v/lqq__wt1181f97_jshy71yzh0000gp/T/AppTranslocation/BA415A8C-B29F-422D-A5D0-7882FA862156/d/Appium.app/Contents/Resources/app/node_modules/appium-support/lib/logging.js:60:13)
    at ADB.callee$0$0$ (/private/var/folders/5v/lqq__wt1181f97_jshy71yzh0000gp/T/AppTranslocation/BA415A8C-B29F-422D-A5D0-7882FA862156/d/Appium.app/Contents/Resources/app/node_modules/appium-adb/lib/tools/android-manifest.js:88:9)
    at tryCatch (/private/var/folders/5v/lqq__wt1181f97_jshy71yzh0000gp/T/AppTranslocation/BA415A8C-B29F-422D-A5D0-7882FA862156/d/Appium.app/Contents/Resources/app/node_modules/appium-adb/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/private/var/folders/5v/lqq__wt1181f97_jshy71yzh0000gp/T/AppTranslocation/BA415A8C-B29F-422D-A5D0-7882FA862156/d/Appium.app/Contents/Resources/app/node_modules/appium-adb/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/private/var/folders/5v/lqq__wt1181f97_jshy71yzh0000gp/T/AppTranslocation/BA415A8C-B29F-422D-A5D0-7882FA862156/d/Appium.app/Contents/Resources/app/node_modules/appium-adb/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/private/var/folders/5v/lqq__wt1181f97_jshy71yzh0000gp/T/AppTranslocation/BA415A8C-B29F-422D-A5D0-7882FA862156/d/Appium.app/Contents/Resources/app/node_modules/appium-adb/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 10489 ms - 234

**Comment by mykola-mokhnach** [comment]
This error happens if we cannot parse package id from apk file.
Try

```
aapt dump badging <apk_path> | grep 'package: name='
```

and see the output

**Comment by Shahunks** [comment]
i got output has - ERROR: dump failed because no AndroidManifest.xml found. 
what does this mean ?

**Comment by Shahunks** [comment]
@mykola-mokhnach how to solve this issue? please help

**Comment by mykola-mokhnach** [comment]
Fix you apk package with developers. Closing the issue as non Appium related.

**Comment by DonnaZh** [comment]
@Shahunks
Is there any progress on this problem? did you get the problem solved?
May I ask how did you apply this command .... aap dump badging <apk_path> | grep ‘package: name='?

I tried this cmd ...  
C:\Users\myName>aapt dump badging "C:\Users\myName\myProject\bin\Debug\Apps\myApp.apk" | grep
'package: name='

it returns ....
'aapt' is not recognized as an internal or external command,
operable program or batch file.

Thanks for your help!

**Comment by DonnaZh** [comment]
update ....
 it works by setting right AppActivity capability.

To find AppPackageName and AppActivity ...
 C:\Users\myName\AppData\Local\Android\sdk\build-tools\25.0.2>aapt list -a "C:\myProject\bin\Debug\Apps\myApp.apk" > "C:\output.txt"

in output.txt file

1.search for [Android manifest]
 ==> find [A: package="yourAppPackageName:]


2.search for [E: activity]
 ==> find a list of activity names, try them one by one, most likely it would be the first one.

**Comment by vikramvi** [comment]
For someone who lands here with same problem

**[ADB] Extracting package and launch activity from manifest
[ADB] Error: packageAndLaunchActivityFromManifest failed.**

First check if you can install apk manually on Android Simulator
https://stackoverflow.com/questions/4512458/how-to-run-apk-file-on-emulator

If this succeeds then only you can run appium script successfully.
