### ISSUE TITLE
Bad Parameters Error using Java-client 5.0.0-BETA6 and Appium 1.6.4 while creating AndroidDriver instance.

### ISSUE THREAD

**Issue by sivasks19** [appium/appium#8227]
## The problem

I am getting the following error when I use the 5.0.0-BETA6 java client while creating AndroidDriver instance.

[HTTP] --> POST /wd/hub/session {"capabilities":[{"desiredCapabilities":{"appPackage":"com.android.chrome","browserName":"Chrome","platformName":"Android","deviceName":"Android Emulator","platformVersion":"7.1.1"}},{"requiredCapabilities":{}}]}                                                                                                     [debug] [MJSONWP] Bad parameters: BadParametersError: Parameters were incorrect. We wanted {"required":["desiredCapabilities"],"optional":["requiredCapabilities","capabilities","sessionId","id"]} and you sent ["capabilities"]

## Environment

Appium version (or git revision) that exhibits the issue: Appium version 1.6.4 and 5.0.0-BETA6 of the Java client
Last Appium version that did not exhibit the issue (if applicable):  N/A
Desktop OS/version used to run Appium:  Windows 10 Pro
Node.js version (unless using Appium.app|exe): Node v6.10.2
Mobile platform/version under test: Android 7.1.1
Real device or emulator/simulator: AndroidEmulator
Appium CLI or Appium.app|exe: appium

## Details

I am getting a BadParametersError when using the 5.0.0-BETA6 version of the Java client  while creating AndroidDriver.

## Link to Appium logs

https://gist.github.com/sivasks19/ee11f3bcdc3d5c6611751f88d982bc48

## Code To Reproduce Issue [ Good To Have ]

I am creating my Android Driver as below.

		DesiredCapabilities androidCapabilities = new DesiredCapabilities();			
		androidCapabilities.setCapability("deviceName","Android Emulator");
		androidCapabilities.setCapability("platformVersion","7.1.1");	
		androidCapabilities.setCapability("platformName","Android");
		androidCapabilities.setCapability("browserName", "Chrome");	
		androidCapabilities.setCapability("appPackage", "com.android.chrome"); 						
			
		AndroidDriver<MobileElement> driver = new AndroidDriver<MobileElement>(new URL("http://127.0.0.1:4723/wd/hub"), androidCapabilities);

**Comment by mykola-mokhnach** [comment]
I'd rather try to fix this problem first:
> Command 'java -version' exited with code 2

**Comment by sivasks19** [comment]
While we would also like to resolve the command error, having reviewed other issues (such as [#8118](https://github.com/appium/appium/issues/8118), [#597](https://github.com/appium/java-client/pull/597)) it seems likely the `BadParametersError` is separate issue, and is the issue at hand right now for us.

**Comment by kiranks4480** [comment]
Logs say same error but it looks like Socket Hang exception comes back with 1.6.4 when using automationname as uiautomator2

logs are as follows
 args: ["-P",5037,"-s","008afc938a5cca74","shell","pm","grant","io.appium.settings","android.permission.WRITE_SETTINGS",";","pm","grant","io.appium.settings","android.permission.ACCESS_MOCK_LOCATION",";"]
2017-04-11 15:56:40:203 - debug: [ADB] Running '/Users/kirankidiyappa/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","008afc938a5cca74","shell","pm","grant","io.appium.settings","android.permission.WRITE_SETTINGS",";","pm","grant","io.appium.settings","android.permission.ACCESS_MOCK_LOCATION",";"]
2017-04-11 15:56:42:176 - debug: [AndroidDriver] Pushing unlock helper app to device...
2017-04-11 15:56:42:177 - debug: [ADB] Running '/Users/kirankidiyappa/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","008afc938a5cca74","install","/usr/local/lib/node_modules/appium/node_modules/appium-unlock/bin/unlock_apk-debug.apk"]
2017-04-11 15:56:43:105 - debug: [ADB] Running '/Users/kirankidiyappa/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","008afc938a5cca74","install","/usr/local/lib/node_modules/appium/node_modules/appium-unlock/bin/unlock_apk-debug.apk"]
2017-04-11 15:56:44:137 - debug: [ADB] Application '/usr/local/lib/node_modules/appium/node_modules/appium-unlock/bin/unlock_apk-debug.apk' already installed. Continuing.
2017-04-11 15:56:44:138 - debug: [ADB] Device API level: 25
2017-04-11 15:56:44:138 - debug: [ADB] Getting connected devices...
2017-04-11 15:56:44:155 - debug: [ADB] 1 device(s) connected
2017-04-11 15:56:44:155 - debug: [ADB] Running '/Users/kirankidiyappa/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","008afc938a5cca74","shell","appops","set","io.appium.settings","android:mock_location","allow"]
2017-04-11 15:56:44:253 - debug: [UiAutomator2] Forwarding UiAutomator2 Server port 6790 to 8200
2017-04-11 15:56:44:253 - debug: [ADB] Forwarding system: 8200 to device: 6790
2017-04-11 15:56:44:254 - debug: [ADB] Running '/Users/kirankidiyappa/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","008afc938a5cca74","forward","tcp:8200","tcp:6790"]
2017-04-11 15:56:44:272 - debug: [ADB] Getting connected devices...
2017-04-11 15:56:44:287 - debug: [ADB] 1 device(s) connected
2017-04-11 15:56:44:288 - debug: [ADB] Running '/Users/kirankidiyappa/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","008afc938a5cca74","shell","dumpsys","window"]
2017-04-11 15:56:44:380 - info: [AndroidDriver] Screen already unlocked, doing nothing
2017-04-11 15:56:44:380 - debug: [ADB] Getting connected devices...
2017-04-11 15:56:44:397 - debug: [ADB] 1 device(s) connected
2017-04-11 15:56:44:398 - debug: [ADB] Running '/Users/kirankidiyappa/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","008afc938a5cca74","shell","am","force-stop","io.appium.uiautomator2.server"]
2017-04-11 15:56:45:422 - info: [UiAutomator2] Starting uiautomator2 server v0.1.4 with cmd: am,instrument,-w,io.appium.uiautomator2.server.test/android.support.test.runner.AndroidJUnitRunner
2017-04-11 15:56:45:423 - info: [UiAutomator2] running command...
 adb -s 008afc938a5cca74 shell am instrument -w io.appium.uiautomator2.server.test/android.support.test.runner.AndroidJUnitRunner... 
2017-04-11 15:56:45:424 - info: [UiAutomator2] Waiting for UiAutomator2 to be online...
2017-04-11 15:56:45:426 - debug: [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
2017-04-11 15:56:45:974 - info: [HTTP] <-- POST /wd/hub/session - - ms - - 
2017-04-11 15:56:46:441 - debug: [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
2017-04-11 15:56:47:449 - debug: [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
2017-04-11 15:56:48:463 - debug: [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
2017-04-11 15:56:49:475 - debug: [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
2017-04-11 15:56:50:224 - error: [Logcat] Logcat terminated with code 0, signal null

Also the console shows following errors

ADB] Cannot read version codes of /usr/local/lib/node_modules/appium/node_modules/io.appium.settings/app/build/outputs/apk/settings_apk-debug.apk and/or io.appium.settings. Assuming correct app version is already installed
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: Error: Trying to proxy a session command without session id
[MJSONWP] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: Error: socket hang up
    at JWProxy.proxy$ (../../../lib/jsonwp-proxy/proxy.js:144:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
Doubtful whether it is an issue with Appium 1.6.4 or Java-Client-5.0.0 -BETA6

**Comment by sravanmedarapu** [comment]
@kiranks4480, Can you please adb logcat for the same (please clear exiting logs by using `adb logcat -c` command before running the scripts) ?

**Comment by AmitVerma4HP** [comment]
I have similar problem while running Appium automation tests on multiple real Android devices. After removing 2 UIautomator2 server apks from device, makes whole thing work so I am using this work around until this issue is resolved in appium.

**Comment by dpgraham** [comment]
A fix was made for this, recently.
