### ISSUE TITLE
Unable to start WebDriverAgent session: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8100

### ISSUE THREAD

**Issue by FelixHerrera** [appium/appium#8240]
## The problem

I am trying to run appium for my iOS 10 app using appium 1.6.4. I have followed the instructions on the appium git and installed all external dependencies. However when I try to run my tests, the WDA session never starts. It doesn't appear to install onto the simulator I have tried running this command (xcodebuild build-for-testing test-without-building -project /Users/z002j6n/Downloads/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=E7AEDC6A-3462-4778-87B5-494ED894ECBF -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.2) and WDA seems to install fine however when Appium runs the same command nothing happens.

## Environment

* Appium version (or git revision) that exhibits the issue: v1.6.4
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS X 10.11.6
* Node.js version (unless using Appium.app|exe): v6.9.3
* Mobile platform/version under test: iOS 10.2
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: Appium Desktop

## Link to Appium logs

https://gist.github.com/FelixHerrera/29b6738953b5f69973ff687bc0a362ca

**Comment by dpgraham** [comment]
The README for https://github.com/appium/appium-xcuitest-driver has instructions on how to setup appium-xcuitest-driver and webdriveragent. Can you try following that and let me know what happens?

**Comment by FelixHerrera** [comment]
I tried following those instructions before I posted and I still get the mentioned error.

**Comment by dpgraham** [comment]
Can you try running it from xcode and then pinging http://localhost:8100/status ?

**Comment by mykola-mokhnach** [comment]
Is there any reason to set **newCommandTimeout** to zero?

**Comment by FelixHerrera** [comment]
@dpgraham it returned this
{
  "sessionId" : "ADA80B6D-ABC6-413B-B1C5-16558F99A8C2",
  "value" : {
    "state" : "success",
    "os" : {
      "name" : "iOS",
      "version" : "10.2"
    },
    "ios" : {
      "ip" : "172.20.10.36",
      "simulatorVersion" : "10.2"
    },
    "build" : {
      "time" : "Apr 12 2017 10:49:05"
    }
  },
  "status" : 0
}

@mykola-mokhnach I didn't set that manually. These are my capabilities
{
  "platformName": "iOS",
  "platformVersion": "10.2",
  "deviceName": "iPad Retina",
  "browserName": "",
  "automationName": "XCUITest",
  "app": "/path/to/WorkOrder.ipa"
}

**Comment by mykola-mokhnach** [comment]
What if you change it to 120 seconds?

**Comment by FelixHerrera** [comment]
No luck, same error.

**Comment by mykola-mokhnach** [comment]
Log please

**Comment by FelixHerrera** [comment]
https://gist.github.com/FelixHerrera/21ce02b937bae727510e0b40bb2a1fd4

**Comment by mykola-mokhnach** [comment]
> [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Users/z002j6n/Downloads/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=E7AEDC6A-3462-4778-87B5-494ED894ECBF -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.2' in directory '/Users/z002j6n/Downloads/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
> [XCUITest] Output from xcodebuild will not be logged
> [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
> [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
> [XCUITest] xcodebuild exited with code 'null' and signal 'SIGABRT'

This should not happen. What if you execute the same xcodebuild command manually or try to build and deploy WDA from Xcode?

**Comment by FelixHerrera** [comment]
If I run the same command manually I get this.
https://gist.github.com/FelixHerrera/e66f7505a2b99c0519fcfac08411ef2f

**Comment by mykola-mokhnach** [comment]
That's weird. Try to set **showXcodeLog** capability to true and attach the log again

**Comment by FelixHerrera** [comment]
Looks like that gave more helpful information 
https://gist.github.com/FelixHerrera/7ec0230d7a999a0d579dae6a06988435

**Comment by mykola-mokhnach** [comment]
This looks more some internal Xcode failure. Try to either update Xcode or try it on some other machine

**Comment by hqfking** [comment]
I am facing the same error. 

Here is the log: 
[startSessionInGUI.pdf](https://github.com/appium/appium/files/970817/startSessionInGUI.pdf)

The weird thing is that it complains that I don't have carthage installed.  But I actually do.

Then it failed when building the WebDriveAgent project.  However, I can run the same command in the terminal which succeeded without any problem.  Here is the log from running it in terminal:
[runWebDriveInTerminal.pdf]
(https://github.com/appium/appium/files/970823/runWebDriveInTerminal.pdf)

Please give some suggestions since I can't do much at this point. 

Thanks.

**Comment by imurchie** [comment]
Closing due to inactivity.

**Comment by SherwoodSu** [comment]
I am getting the same things, cannot open from Appium-desktop, but I was able to run my test codes using appium, any ideas?

**Comment by akashkhandelwal** [comment]
I have same issue as that of @SherwoodSu . Please help
[appium-server-logs.txt](https://github.com/appium/appium/files/1324818/appium-server-logs.txt)

**Comment by vighneshpai-yml** [comment]
@imurchie and @mykola-mokhnach,

I'm also facing the same issue. I'm able to run it from appium tool but not via scripts. I'm clueless.

It says wda session failed to create. Not sure why?!

**Comment by GeeSlimmy** [comment]
I tried this on MacBook Pro iOS 10.13.2 with Xcode Version 9.2 and I get this issue. Here's the strange thing I tried this on my Mac Mini iOS 10.3.1 with Xcode Version 9.1 and I get this issue today but running the same code on the Mac Mini a few days ago was fine.. ? 

[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: Unable to start WebDriverAgent session because of xcodebuild failure: "Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8100".
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:381:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[HTTP] <-- POST /wd/hub/session 500 402711 ms - 312

**Comment by crhoads1024** [comment]
@GeeSlimmy I've got the same config as you do. 
This was running at one point (2 weeks ago maybe) and launching on Simulator and Physical iOS.

Have you found a workaround for this yet? I've set the useNewWDA capability but it didnt help

Machine Config:
Mac Book Pro: OSX 10.3.2
Xcode: 9.2
Appium Server: 1.7.2
iOS Sim: 11.2 
UDID: 5A4A7D7B-0D5B-4CB4-BBD2-5F1E9E87B2DF
iOS Physical Device: iPhone 6s Plus - 11.2

**Comment by GeeSlimmy** [comment]
@crhroads1024 
I winded up doing a fresh install of everything from scratch as I was getting tired of trying to figure it out. I've tested integration app on iOS simulator and Appium 1.2.7 on MacOS High Sierra 10.13.2 and Xcode version 9.2

**Comment by crhoads1024** [comment]
@GeeSlimmy resolved on local, runs fine, now I have the same issue in my first run of my tests in the AWS Device Farm. So here we go again....
