### ISSUE TITLE
Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65

### ISSUE THREAD

**Issue by bhajojo** [appium/appium#8249]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version : 1.6.4
* Last Appium version that did not exhibit the issue (if applicable):NA
* Desktop OS/version used to run Appium: MacOS 10.0.2
* Node.js version (unless using Appium.app|exe):V 7.8.0
* Mobile platform/version under test:ios10.0.2
* Real device or emulator/simulator:Real device 
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium log
```
Last login: Thu Apr 13 15:24:48 on ttys001
Bharats-iMac:~ bharatjoshi$ appium &
[1] 6634
Bharats-iMac:~ bharatjoshi$ [Appium] Welcome to Appium v1.6.4
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"//Users//bharatjoshi//Documents//workspace//PocNativeApp//trunk//ProjectAutomation//ipa//MobileBank-2.0.0-398.ipa","platformVersion":"10.0.2","automationName":"appium","platformName":"iOS","udid":"ae532b52b89deb5c34448310cd92e2d46e53b69f","deviceName":"iPhone6"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"//Users//bharatjoshi//Documents//workspace//PocNativeApp//trunk//ProjectAutomation//ipa//MobileBank-2.0.0-398.ipa","platformVersion":"10.0.2","automationName":"appium","platformName":"iOS","udid":"ae532b52b89deb5c34448310cd92e2d46e53b69f","deviceName":"iPhone6"},null,null,null,null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1492077427286 (15:27:07 GMT+0530 (IST))
[Appium] Requested iOS support with version >= 10, using XCUITest driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
[Appium] Creating new XCUITestDriver (v2.27.2) session
[Appium] Capabilities:
[Appium]   app: '//Users//bharatjoshi//Documents//workspace//PocNativeApp//trunk//ProjectAutomation//ipa//MobileBank-2.0.0-398.ipa'
[Appium]   platformVersion: '10.0.2'
[Appium]   automationName: 'appium'
[Appium]   platformName: 'iOS'
[Appium]   udid: 'ae532b52b89deb5c34448310cd92e2d46e53b69f'
[Appium]   deviceName: 'iPhone6'
[debug] [XCUITest] XCUITestDriver version: 2.27.2
[BaseDriver] Session created with session id: 25a8ec25-d164-45b6-a452-115a4cd13c1a
[debug] [XCUITest] Xcode version set to '8.1' 
[debug] [XCUITest] iOS SDK Version set to '10.1'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1492077427529 (15:27:07 GMT+0530 (IST))
[debug] [XCUITest] Available devices: ae532b52b89deb5c34448310cd92e2d46e53b69f
[debug] [XCUITest] Creating iDevice object with udid 'ae532b52b89deb5c34448310cd92e2d46e53b69f'
[XCUITest] Determining device to run tests on: udid: 'ae532b52b89deb5c34448310cd92e2d46e53b69f', real device: true
[BaseDriver] Using local app '//Users//bharatjoshi//Documents//workspace//PocNativeApp//trunk//ProjectAutomation//ipa//MobileBank-2.0.0-398.ipa'
[debug] [BaseDriver] Copying local zip to tmp dir
[debug] [BaseDriver] Unzipping /var/folders/fm/0tcmhr1n3hz36v_f83pkflx40000gq/T/2017313-6634-1non0g4.a8dpo80k9/appium-app.zip
[debug] [BaseDriver] Testing zip archive: /var/folders/fm/0tcmhr1n3hz36v_f83pkflx40000gq/T/2017313-6634-1non0g4.a8dpo80k9/appium-app.zip
[BaseDriver] Unzipped local app to '/var/folders/fm/0tcmhr1n3hz36v_f83pkflx40000gq/T/2017313-6634-1non0g4.a8dpo80k9/Payload/MobileBankDev.app'
[debug] [BaseDriver] Event 'appConfigured' logged at 1492077429755 (15:27:09 GMT+0530 (IST))
[debug] [XCUITest] Checking whether app '/var/folders/fm/0tcmhr1n3hz36v_f83pkflx40000gq/T/2017313-6634-1non0g4.a8dpo80k9/Payload/MobileBankDev.app' is actually present on file system
[debug] [XCUITest] App is present
[debug] [iOS] Getting bundle ID from app '/var/folders/fm/0tcmhr1n3hz36v_f83pkflx40000gq/T/2017313-6634-1non0g4.a8dpo80k9/Payload/MobileBankDev.app': 'se.forex.mobile'
[debug] [BaseDriver] Event 'resetStarted' logged at 1492077429760 (15:27:09 GMT+0530 (IST))
[debug] [XCUITest] Reset: running ios real device reset flow
[debug] [BaseDriver] Event 'resetComplete' logged at 1492077429761 (15:27:09 GMT+0530 (IST))
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1492077429896 (15:27:09 GMT+0530 (IST))
[XCUITest] Setting up real device
[debug] [XCUITest] Reset requested. Removing app with id 'se.forex.mobile' from the device
[debug] [XCUITest] Installing '/var/folders/fm/0tcmhr1n3hz36v_f83pkflx40000gq/T/2017313-6634-1non0g4.a8dpo80k9/Payload/MobileBankDev.app' on device with UUID 'ae532b52b89deb5c34448310cd92e2d46e53b69f'...
[debug] [XCUITest] The app has been installed successfully.
[debug] [BaseDriver] Event 'appInstalled' logged at 1492077441896 (15:27:21 GMT+0530 (IST))
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1492077441899 (15:27:21 GMT+0530 (IST))
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=ae532b52b89deb5c34448310cd92e2d46e53b69f -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.0' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will not be logged
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] Log file for xcodebuild test: /Users/bharatjoshi/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/60446CE9-29AA-4D4B-82CC-513A159C2448/Session-WebDriverAgentRunner-2017-04-13_152729-gTSSLC.log
[Xcode] 2017-04-13 15:27:29.441 xcodebuild[6671:106300] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/bharatjoshi/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7fc76eeda660 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[Xcode] 
[Xcode] 2017-04-13 15:27:29.441 xcodebuild[6671:106300] Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[XCUITest] xcodebuild exited with code '65' and signal 'null'
[debug] [BaseDriver] Event 'wdaStartFailed' logged at 1492077449492 (15:27:29 GMT+0530 (IST))
[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
[debug] [XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down iproxy process (pid 6669)
[debug] [XCUITest] iproxy exited with code 'null'
[debug] [XCUITest] Removing WDA application from device
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1492077459694 (15:27:39 GMT+0530 (IST))
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=ae532b52b89deb5c34448310cd92e2d46e53b69f -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.0' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will not be logged
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] Log file for xcodebuild test: /Users/bharatjoshi/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/3887C29B-C29D-4947-BFC2-ED739FFCE9FB/Session-WebDriverAgentRunner-2017-04-13_152747-6o74tS.log
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[Xcode] 2017-04-13 15:27:47.113 xcodebuild[6702:106486] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/bharatjoshi/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7f7fd5abc5b0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[Xcode] 2017-04-13 15:27:47.113 xcodebuild[6702:106486] Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[XCUITest] xcodebuild exited with code '65' and signal 'null'
[debug] [BaseDriver] Event 'wdaStartFailed' logged at 1492077467129 (15:27:47 GMT+0530 (IST))
[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
[debug] [XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down iproxy process (pid 6701)
[debug] [XCUITest] iproxy exited with code 'null'
[debug] [XCUITest] Removing WDA application from device
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:374:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:374:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:374:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 50123 ms - 230 
```

**Comment by imurchie** [comment]
This is a code signing issue. Please see https://github.com/appium/appium/blob/master/docs/en/appium-setup/real-devices-ios.md

**Comment by mykola-mokhnach** [comment]
Closing as non Appium-related

**Comment by bhajojo** [comment]
My Observation while finding out solution to this issue 

This issue will not appear with the appium version 1.6.1 , Xcode  version 8.1 and IOS sdk version 9.2 and above 

Can any one please comment on why this issue is specifically there for appium version 1.6.4

**Comment by imurchie** [comment]
There have been many changes between those two versions. That said, it is entirely possible to make it work with the latest version.

If you run with the `showXcodeLog` capability set to `true` the full error ought to be apparent.

**Comment by swachhab** [comment]
This is code signing issue, it happens when setup for appium have some problem in configuring webdriver-agent in appium library, you can even configure webdriver-agent with free apple developer account as well, follow these steps in video: https://www.youtube.com/watch?v=dyijACVRQOc It worked for me, hope it will help everybody here!
