### ISSUE TITLE
Cannot install .ipa in iOS real device with appium

### ISSUE THREAD

**Issue by reach2jeyan** [appium/appium#8251]
Version : 1.5.3
iOS : 9
Xcode: 8 and above

I am currently not able to install the .ipa file with appium.

**I am able to install with ideviceinstaller manually with the command `ideviceinstaller -i abc.ipa` in the terminal**

but in appium, when I run my cucumber tests, I get the following error, when i tries to install,

 ```
Encountered internal error running command: Error: Command failed: 
 ideviceinstaller -u udid -i 
 /var/folders/58/bqk7r15x7hv_l35vll1hg5_w0000gp/T/2017311-19876-
 1upzlv/Payload/abc.app
/bin/sh: -c: line 0: unexpected EOF while looking for matching `''
/bin/sh: -c: line 1: syntax error: unexpected end of file

at ChildProcess.exithandler (child_process.js:202:12)
at emitTwo (events.js:100:13)
at ChildProcess.emit (events.js:185:7)
at maybeClose (internal/child_process.js:850:16)
at Socket.<anonymous> (internal/child_process.js:323:11)
at emitOne (events.js:90:13)
at Socket.emit (events.js:182:7)
at Pipe._onclose (net.js:475:12)
```

My env.rb file is

 ```
require "appium_lib"

 def caps
  {
  caps:{ deviceName: "iPhone",
         platformName: "iOS",
         app: (File.join(File.dirname(__FILE__), "abc.ipa")),
         bundleId: "com.abc.abc",
         newCommandTimeout: "3600",
         appium_lib: { wait: 20,
                       debug: false
            }
       }
   }
  end


 def server_url
  'http://0.0.0.0:4723/wd/hub'
 end

 Appium::Driver.new(caps)   
 Appium.promote_appium_methods Object 
```

**Comment by imurchie** [comment]
Appium 1.5.3 does not understand Xcode 8+. Please upgrade to 1.6.4 and if this problem persists, post a link to a [gist](https://gist.github.com) of the _entire_ Appium server logs so that we can try to help.

**Comment by reach2jeyan** [comment]
@imurchie I am able to perform the testing through appium if my application is already installed

**Comment by imurchie** [comment]
I don't understand your question. And there is little that I can do without the logs.

**Comment by reach2jeyan** [comment]
@imurchie My Appium version is as mentioned above and I am using xcode 7.3 with it, with iOS version 9.3.2. 

I am able to install from the terminal the .ipa application using the `ideviceinstaller` but, the same is not possible with appium. Appium throws me the exception error while install. 

If the application is installed by me manually and then I run my test case, appium finds the app installed and runs the cases perfectly well.

My question here, is, why is that, appium cannot install the .ipa file to my device? considering, I am using the versions that appium can understand.

**Comment by reach2jeyan** [comment]
@imurchie These are the complete logs

```Launching Appium with command: export ANDROID_HOME="/Users/jain/Library/Android/sdk"; '/Applications/Appium.app/Contents/Resources/node/bin/node' appium/build/lib/main.js --pre-launch --debug-log-spacing --platform-version "9.3" --platform-name "iOS" --app "com.ymedialabs.devteam" --udid "e5c439e0d2d2935686f98c25534aa6937f3201bb" --device-name "iPhone 4s" --launch-timeout "100000"

[Appium] Welcome to Appium v1.5.3

[Appium] Non-default server args:

[Appium]   launch: true

[Appium]   debugLogSpacing: true
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '9.3'
[Appium]   deviceName: 'iPhone 4s'
[Appium]   app: 'com.ymedialabs.devteam'
[Appium]   launchTimeout: 100000

[Appium]   udid: 'e5c439e0d2d2935686f98c25534aa6937f3201bb'
[Appium] Deprecated server args:
[Appium]   --platform-name => --default-capabilities '{"platformName":"iOS"}'
[Appium]   --platform-version => --default-capabilities '{"platformVersion":"9.3"}'
[Appium]   --device-name => --default-capabilities '{"deviceName":"iPhone 4s"}'
[Appium]   --app => --default-capabilities '{"app":"com.ymedialabs.devteam"}'
[Appium]   -lt,--launch-timeout => --default-capabilities '{"launchTimeout":100000}'
[Appium]   -U,--udid => --default-capabilities '{"udid":"e5c439e0d2d2935686f98c25534aa6937f3201bb"}'

[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:

[Appium]   platformName: 'iOS'

[Appium]   platformVersion: '9.3'
[Appium]   deviceName: 'iPhone 4s'
[Appium]   app: 'com.ymedialabs.devteam'
[Appium]   launchTimeout: 100000

[Appium]   udid: 'e5c439e0d2d2935686f98c25534aa6937f3201bb'

[Appium] Appium REST http interface listener started on 0.0.0.0:4723

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[HTTP] <-- GET /wd/hub/status 200 26 ms - 83 

[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"browserName":"","version":"","platform":"ANY","javascriptEnabled":true,"cssSelectorsEnabled":true,"takesScreenshot":true,"nativeEvents":false,"rotatable":false,"deviceName":"iPhone","platformName":"iOS","Browser":"Safari","app":"/Users/jain/Documents/Automation/iOS/Sample/Features/Step_definitions/Support/chefd.ipa","bundleId":"com.ymedialabs.devteam","newCommandTimeout":"3600","appiumLib":{"wait":20,"debug":false}}}

[MJSONWP] Calling AppiumDriver.createSession() with args: [{"browserName":"","version...

[Appium] Creating new IosDriver session
[Appium] Capabilities:
[Appium]   browserName: ''
[Appium]   version: ''
[Appium]   platform: 'ANY'
[Appium]   javascriptEnabled: true
[Appium]   cssSelectorsEnabled: true
[Appium]   takesScreenshot: true
[Appium]   nativeEvents: false
[Appium]   rotatable: false
[Appium]   deviceName: 'iPhone'
[Appium]   platformName: 'iOS'
[Appium]   Browser: 'Safari'
[Appium]   app: '/Users/jain/Documents/Automation/iOS/Sample/Features/Step_definitions/Support/chefd.ipa'
[Appium]   bundleId: 'com.ymedialabs.devteam'
[Appium]   newCommandTimeout: '3600'
[Appium]   appiumLib: { wait: 20, debug: false }
[Appium]   platformVersion: '9.3'
[Appium]   launchTimeout: 100000
[Appium]   udid: 'e5c439e0d2d2935686f98c25534aa6937f3201bb'

[BaseDriver] Capability 'newCommandTimeout' changed from string ('3600') to integer (3600). This may cause unexpected behavior

[BaseDriver] The following capabilities were provided, but are not recognized by appium: version, platform, javascriptEnabled, cssSelectorsEnabled, takesScreenshot, nativeEvents, rotatable, Browser, appiumLib.

[BaseDriver] Session created with session id: f0328796-0740-4df9-b493-376bd62cd037

[debug] [iOS] Not auto-detecting udid.
[BaseDriver] Using local app '/Users/jain/Documents/Automation/iOS/Sample/Features/Step_definitions/Support/chefd.ipa'
[debug] [BaseDriver] Copying local zip to tmp dir

[debug] [BaseDriver] Unzipping /var/folders/58/bqk7r15x7hv_l35vll1hg5_w0000gp/T/2017313-27304-brbjw9/appium-app.zip

[debug] [BaseDriver] Testing zip archive: /var/folders/58/bqk7r15x7hv_l35vll1hg5_w0000gp/T/2017313-27304-brbjw9/appium-app.zip

[BaseDriver] Unzipped local app to '/var/folders/58/bqk7r15x7hv_l35vll1hg5_w0000gp/T/2017313-27304-brbjw9/Payload/CHEF'D.app'

[debug] [iOS] Removing any remaining instruments sockets

[debug] [iOS] Cleaned up instruments socket /var/folders/58/bqk7r15x7hv_l35vll1hg5_w0000gp/T/instruments_sock
[debug] [iOS] No language specified. Using default strings

[debug] [iOS] Parsed app 'Localizable.strings'

[debug] [iOS] Creating instruments
[debug] [UIAuto] Preparing bootstrap code
[debug] [UIAuto] Dynamic bootstrap dir: /Users/jain/Library/Application Support/appium/bootstrap
[debug] [UIAuto] Dynamic env: {"nodePath":"/Applications/Appium.app/Contents/Resources/node/bin/node","commandProxyClientPath":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js","instrumentsSock":"/var/folders/58/bqk7r15x7hv_l35vll1hg5_w0000gp/T/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"grouped"}

[debug] [UIAuto] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...

[debug] [UIAuto] Dynamic bootstrap path: /Users/jain/Library/Application Support/appium/bootstrap/bootstrap-e916b1ddbd07df81.js

[debug] [UIAuto] Reusing dynamic bootstrap: /Users/jain/Library/Application Support/appium/bootstrap/bootstrap-e916b1ddbd07df81.js

[debug] [iOS] Running ios real device reset flow

[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'

[debug] [iOS] Creating iDevice object with udid e5c439e0d2d2935686f98c25534aa6937f3201bb

[debug] [iOS] App is not installed. Will try to install.

[MJSONWP] Encountered internal error running command: Error: Command failed: ideviceinstaller -u e5c439e0d2d2935686f98c25534aa6937f3201bb -i /var/folders/58/bqk7r15x7hv_l35vll1hg5_w0000gp/T/2017313-27304-brbjw9/Payload/CHEF'D.app
/bin/sh: -c: line 0: unexpected EOF while looking for matching `''
/bin/sh: -c: line 1: syntax error: unexpected end of file

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:475:12)

[HTTP] <-- POST /wd/hub/session 500 7879 ms - 434 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
```

**Comment by imurchie** [comment]
Seems like Appium cannot handle the `'` in the path to your app.

**Comment by imurchie** [comment]
Appium's workflow is to unzip the `ipa` file:
```
[debug] [BaseDriver] Testing zip archive: /var/folders/58/bqk7r15x7hv_l35vll1hg5_w0000gp/T/2017313-27304-brbjw9/appium-app.zip
[BaseDriver] Unzipped local app to '/var/folders/58/bqk7r15x7hv_l35vll1hg5_w0000gp/T/2017313-27304-brbjw9/Payload/CHEF'D.app'
```
And then when it tries to install that the command fails.

I can fix this, but it will not get into Appium 1.5.3.

**Comment by reach2jeyan** [comment]
@imurchie: Can't you release it on a bug fix update for 1.5.3? 

When is the scheduled release forappium 1.6 version GUI?

**Comment by reach2jeyan** [comment]
@imurchie Or is there a workaround for this? other than manually installing the build?

**Comment by imurchie** [comment]
There is a GUI for 1.6.4: https://github.com/appium/appium-desktop/releases

**Comment by reach2jeyan** [comment]
@imurchie So this one will have the inspector from the command line?

**Comment by imurchie** [comment]
I don't understand what you mean by "have the inspector from the command line".

Yes, the entire GUI was redesigned and rewritten.

**Comment by reach2jeyan** [comment]
i am sorry for the confusion. I use appium inspector to inspect the elements for both android and iOS. I dont find the same in the new version of appium you had released.

**Comment by imurchie** [comment]
That should be possible. Have you read the README? https://github.com/appium/appium-desktop#appium-desktop-

**Comment by reach2jeyan** [comment]
Alright! I ll go through it, thanks for being patient enough providing me the information.
