### ISSUE TITLE
Setup crashes when trying to run tests with UIautomator2

### ISSUE THREAD

**Issue by vjmaiky** [appium/appium#8272]
## The problem
Setup crashes when trying to run tests with UIautomator2
If i remove capability which contains UIautomator2 works perfectly...from stack trace i see that i crashes on reset app.
Maybe i`m missing something..(i`m not sure that i created UIautomator2driver correctly....)

## Environment

java client 5.0.0-BETA6
Appium server version: 1.6.4
Node.js version: 7.5.0
Mobile platform/version under test: Android 7.0
GennyMotion Emulator

## Details
protected AndroidDriverHelper() {

        File appDir = new File("src/test/java");
        File app = new File(appDir, "Today Calendar_com.underwood.calendar_beta.apk");
        capabilities.setCapability("device", "Simulator");
        capabilities.setCapability("deviceName", "Nexus 5");
        capabilities.setCapability("platformName", "Android");
        capabilities.setCapability("automationName", "Appium");
        capabilities.setCapability("platformVersion", "7.0.1");
        capabilities.setCapability("newCommandTimeout", 120);
        capabilities.setCapability("udid", "192.168.92.101:5555");
        capabilities.setCapability("fullReset", true);
        capabilities.setCapability("appActivity", "com.android.calendar.AllInOneActivity");
        capabilities.setCapability("appPackage", "com.underwood.calendar_beta");
        capabilities.setCapability("app", app.getAbsolutePath());
        capabilities.setCapability("automationName", "uiautomator2");

 public static AndroidDriver createNewDriver() {
        if (driver == null) {
            try {
                driver = new AndroidDriver(new URL("http://0.0.0.0:4723/wd/hub"), capabilities);
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
        return driver;
    }

    public void initConnection() {
        driver = createNewDriver();
        driver.resetApp();
    }

## Link to Appium logs

https://gist.github.com/vjmaiky/2d4890a5914a9d18dcbae5e55df6a509

Ide error:

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: this.grantPermissions is not a function (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 7.33 seconds
Build info: version: '3.3.1', revision: '5234b325d5', time: '2017-03-10 09:10:29 +0000'
System info: host: 'EN63587', ip: '192.168.92.2', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_51'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{appActivity=de.telekom.mail.emma.activities.SplashScreenActivity, appPackage=de.telekom.mail, app=D:\Automation\workspace\NewAndroidTest\src\test\java\Emma-prodautomation.apk, newCommandTimeout=120, platformVersion=6.0.1, automationName=uiautomator2, platformName=Android, udid=192.168.92.101:5555, device=Simulator, deviceName=Nexus 5, fullReset=true, platform=ANY}]
Session ID: 8fa187db-3211-499b-8ab7-43de8ee29b51

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:216)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:168)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:638)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:46)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at io.appium.java_client.InteractsWithApps.resetApp(InteractsWithApps.java:64)
	at config.AppiumServerDriver.initConnection(AppiumServerDriver.java:28)
	at tests.BaseTest.setup(BaseTest.java:10)
	at tests.Test002.startServer(Test002.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

**Comment by vjmaiky** [comment]
@sravanmedarapu are you sure that this fix was released? i`m still getting this error

**Comment by dpgraham** [comment]
It's not released. It will be in the next version of Appium

**Comment by VenkateshPS** [comment]
Is this issue resolved? I tried running using uiautomator2 and getting error.

**Comment by ganesh-pprasad** [comment]
Still getting this error. It is caused because of resetApp(). I'm using wd (node) driver.
