### ISSUE TITLE
send_keys will cause java.lang.IndexOutOfBoundsException when EditText have maxLength property defined

### ISSUE THREAD

**Issue by JaniJegoroff** [appium/appium#8279]
## The problem

Given I have `EditText` with `maxLength` property defined (11 characters in this case)
When I use `send_keys` method to enter text to the EditText two times in a row
Then `java.lang.IndexOutOfBoundsException` is raised

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4, 1.6.5-beta
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Mac OS Sierra 10.12.4
* Node.js version (unless using Appium.app|exe): v7.2.0
* Mobile platform/version under test: Android 5.0.2
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI
* Other: Ruby, uiautomator2

## Details

Crash happens only with `uiautomator2`. I can see `send_keys` will clear EditText before entering text but looks like some internal state is not correct when entering text second time to the same EditText.
```
E/AndroidRuntime(29508): FATAL EXCEPTION: main
E/AndroidRuntime(29508): Process: com.ga.xxx.android.xxx.activities.local, PID: 29508
E/AndroidRuntime(29508): java.lang.IndexOutOfBoundsException: setSpan (22 ... 22) ends beyond length 11
E/AndroidRuntime(29508): 	at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1030)
E/AndroidRuntime(29508): 	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:623)
E/AndroidRuntime(29508): 	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:619)
E/AndroidRuntime(29508): 	at android.text.Selection.setSelection(Selection.java:76)
E/AndroidRuntime(29508): 	at android.text.Selection.setSelection(Selection.java:87)
E/AndroidRuntime(29508): 	at android.widget.EditText.setSelection(EditText.java:104)
E/AndroidRuntime(29508): 	at android.widget.EditText.performAccessibilityAction(EditText.java:150)
E/AndroidRuntime(29508): 	at android.view.AccessibilityInteractionController.perfromAccessibilityActionUiThread(AccessibilityInteractionController.java:626)
E/AndroidRuntime(29508): 	at android.view.AccessibilityInteractionController.access$500(AccessibilityInteractionController.java:53)
E/AndroidRuntime(29508): 	at android.view.AccessibilityInteractionController$PrivateHandler.handleMessage(AccessibilityInteractionController.java:1239)
E/AndroidRuntime(29508): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(29508): 	at android.os.Looper.loop(Looper.java:155)
E/AndroidRuntime(29508): 	at android.app.ActivityThread.main(ActivityThread.java:5696)
E/AndroidRuntime(29508): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(29508): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(29508): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
E/AndroidRuntime(29508): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
E/ActivityManager(  708): App crashed! Process: com.ga.xxx.android.xxx.activities.local
```
EditText view
```
<EditText
  android:id="@+id/login_edittext_card_number"
  android:layout_width="wrap_content"
  android:layout_height="wrap_content"
  android:layout_above="@id/login_underlined"
  android:layout_alignLeft="@id/login_underlined"
  android:layout_alignRight="@id/login_underlined"
  android:background="@drawable/editbox_background_normal"
  android:fontFamily="sans-serif-light"
  android:imeOptions="actionNext"
  android:inputType="number"
  android:maxLength="11"
  android:maxLines="1"
  android:textColor="@android:color/white"
  android:textCursorDrawable="@null"
  android:textSize="@dimen/large"
  tools:text="12312312312">

  <requestFocus />
</EditText>
```

## Link to Appium logs

https://gist.github.com/JaniJegoroff/2b569d12dab0fbeb8259fd6ea4d9af8d

## Code To Reproduce Issue [ Good To Have ]

Crash
```
Given(/^I test text input$/) do
  id = 'login_edittext_card_number'

  wait do
    find_element(id: id).send_keys('22222222222')
    find_element(id: id).send_keys('11111111111')
  end
end
```

No crash - entering text shorter than maxLength
```
Given(/^I test text input$/) do
  id = 'login_edittext_card_number'

  wait do
    find_element(id: id).send_keys('222')
    find_element(id: id).send_keys('111')
  end
end
```

No crash - clearing text field manually before entering text second time
```
Given(/^I test text input$/) do
  id = 'login_edittext_card_number'

  wait do
    find_element(id: id).send_keys('22222222222')
    find_element(id: id).clear
    find_element(id: id).send_keys('11111111111')
  end
end
```

**Comment by HPramesh** [comment]
We observed exactly same issue on Android 6.0 but it always works fine on 7.1.1
Pls let me know if you get any work around on this.

**Comment by JaniJegoroff** [comment]
@HPramesh Workaround would be clearing text field explicitly before entering text. See my last code example.

**Comment by imurchie** [comment]
This no longer happens.
