### ISSUE TITLE
i am getting an issue could not launch a appium inspector

### ISSUE THREAD

**Issue by Vamshivarma** [appium/appium#8282]
[debug] [iOS] fullReset not requested. No need to install.
[debug] [iOS] Starting UIAutoClient, and launching Instruments.

[MJSONWP] Encountered internal error running command: Error: Could not find Automation.tracetemplate in any of the followinglocations /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate,/Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.bundle/Contents/Resources/Automation.tracetemplate
    at getAutomationTraceTemplatePathWithoutRetry$ (lib/xcode.js:172:9)
    at tryCatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

[HTTP] <-- POST /wd/hub/session 500 1956 ms - 513 
[debug] [UIAuto] Instruments socket server started at /var/folders/5n/h5shnf8n6fb56nvlwdxfkg2w0000gq/T/instruments_sock

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 13 ms - 83 

![screen shot 2017-04-19 at 3 18 27 pm](https://cloud.githubusercontent.com/assets/27766577/25174069/d8c5928a-2513-11e7-90b9-8e918bda4a2b.png)

Please help me to fix above issue.i am using Appium Version 1.5.3 (Ara) and Xcode Version 8.2.1 (8C1002) and also using small iOS application.and iPad version 9.0

**Comment by mykola-mokhnach** [comment]
This inspector is not supported anymore. Please use https://github.com/appium/appium-desktop/releases
