### ISSUE TITLE
No sim found with udid caef69bfacbf3c342c61621d7b4527eba9671d3e

### ISSUE THREAD

**Issue by githubliuqi** [appium/appium#8302]
Hi,I want to test with iphone ,when I run the python script, it told me that No sim found with udid caef69bfacbf3c342c61621d7b4527eba9671d3e, it menas my phone needs sim,but I think it is not important.
Environment：
appium version :1.5.3

esdev2deMac-mini:~ esdev2$ python /Applications/Appium/workspace/testscript-iOS.py 
Traceback (most recent call last):
  File "/Applications/Appium/workspace/testscript-iOS.py", line 14, in <module>
    driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/appium/webdriver/webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 92, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 179, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: No sim found with udid caef69bfacbf3c342c61621d7b4527eba9671d3e

**Comment by mykola-mokhnach** [comment]
Please ask questions in Appium forum. This is a place for issues.

Appium 1.5.3 is outdated - use 1.6.4 instead.
