### ISSUE TITLE
Same xpath pass on uiautomator1.0 but failed on uiautomator2.0

### ISSUE THREAD

**Issue by Carlgege** [appium/appium#8329]
## The problem

Use the same xpath on different driver uiautomator1.0(AppiumBoostrap.jar) and uiautomator2.0, click the button success on uiautomator1.0 , but failed on uiautomator2.0

xpath::(//*[@text='' and @content-desc='start_pager' and @resource-id='com.suning.snmessenger:id/loading_item_view'])[1]

## Environment

Appium 1.6.3

## Link to Appium logs
`[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["xpath","(//*[@
text='' and @content-desc='start_pager' and @resource-id='com.suning.snmessenger
:id/loading_item_view'])[1]","dde70f6d-ef41-45df-8e35-604d4d1ce322"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class
 name, accessibility id, -android uiautomator
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class
 name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8200/w
d/hub/session/9abc9246-020d-4ae2-a72b-60bb80ecf10c/element] with body: {"strateg
y":"xpath","selector":"(//*[@text='' and @content-desc='start_pager' and @resour
ce-id='com.suning.snmessenger:id/loading_item_view'])[1]","context":"","multiple
":false}`

**Comment by mykola-mokhnach** [comment]
can you attach the output of getPageSource method for both cases?

**Comment by Carlgege** [comment]
UiAutomator1.0
`<?xml version="1.0" encoding="UTF-8"?><hierarchy rotation="0"><android.widget.FrameLayout index="0" text="" class="android.widget.FrameLayout" package="com.suning.snmessenger" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,1920]" resource-id="" instance="0"><android.widget.LinearLayout index="0" text="" class="android.widget.LinearLayout" package="com.suning.snmessenger" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,1920]" resource-id="" instance="0"><android.widget.FrameLayout index="0" text="" class="android.widget.FrameLayout" package="com.suning.snmessenger" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,1920]" resource-id="android:id/content" instance="1"><android.widget.FrameLayout index="0" text="" class="android.widget.FrameLayout" package="com.suning.snmessenger" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,1920]" resource-id="" instance="2"><android.support.v4.view.ViewPager index="0" text="" class="android.support.v4.view.ViewPager" package="com.suning.snmessenger" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="true" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,1920]" resource-id="com.suning.snmessenger:id/viewPager" instance="0"><android.widget.RelativeLayout index="0" text="" class="android.widget.RelativeLayout" package="com.suning.snmessenger" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,1920]" resource-id="" instance="0"><android.widget.ImageView index="0" text="" class="android.widget.ImageView" package="com.suning.snmessenger" content-desc="start_pager" checkable="false" checked="false" clickable="true" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,1920]" resource-id="com.suning.snmessenger:id/loading_item_view" instance="0"/></android.widget.RelativeLayout></android.support.v4.view.ViewPager><android.widget.RelativeLayout index="1" text="" class="android.widget.RelativeLayout" package="com.suning.snmessenger" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,1860]" resource-id="" instance="1"/></android.widget.FrameLayout></android.widget.FrameLayout></android.widget.LinearLayout></android.widget.FrameLayout></hierarchy>`

**Comment by Carlgege** [comment]
UiAutomator2.0
`<?xml version="1.0" encoding="UTF-8"?><hierarchy rotation="0"><android.widget.FrameLayout index="0" text="" class="android.widget.FrameLayout" package="com.suning.snmessenger" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,1920]" resource-id="" instance="0"><android.widget.LinearLayout index="0" text="" class="android.widget.LinearLayout" package="com.suning.snmessenger" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,1920]" resource-id="" instance="0"><android.widget.FrameLayout index="0" text="" class="android.widget.FrameLayout" package="com.suning.snmessenger" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,1920]" resource-id="android:id/content" instance="1"><android.widget.FrameLayout index="0" text="" class="android.widget.FrameLayout" package="com.suning.snmessenger" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,1920]" resource-id="" instance="2"><android.support.v4.view.ViewPager index="0" text="" class="android.support.v4.view.ViewPager" package="com.suning.snmessenger" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="true" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,1920]" resource-id="com.suning.snmessenger:id/viewPager" instance="0"><android.widget.RelativeLayout index="0" text="" class="android.widget.RelativeLayout" package="com.suning.snmessenger" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,1920]" resource-id="" instance="0"><android.widget.ImageView index="0" text="" class="android.widget.ImageView" package="com.suning.snmessenger" content-desc="start_pager" checkable="false" checked="false" clickable="true" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,1920]" resource-id="com.suning.snmessenger:id/loading_item_view" instance="0"/></android.widget.RelativeLayout></android.support.v4.view.ViewPager><android.widget.RelativeLayout index="1" text="" class="android.widget.RelativeLayout" package="com.suning.snmessenger" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,1860]" resource-id="" instance="1"/></android.widget.FrameLayout></android.widget.FrameLayout></android.widget.LinearLayout></android.widget.FrameLayout></hierarchy>`

**Comment by Carlgege** [comment]
@mykola-mokhnach , please help to check it.

**Comment by mykola-mokhnach** [comment]
Check if it is reproducible with Appium 1.6.4
What if you remove the **\@text=''** verification from the xpath?

**Comment by Carlgege** [comment]
@mykola-mokhnach 
You are right, the result is OK after I remove the @text=''.
But i think it is a BUG, could you help to fix it?
I will test this issue on 1.6.4 and comment again.
Thanks

**Comment by mykola-mokhnach** [comment]
the issue is somehow connected to the internal representation of empty fields in the XML
@sravanmedarapu Can you please provide more details on this?

**Comment by Carlgege** [comment]
@mykola-mokhnach @sravanmedarapu 
Could you help to fix this issue, and then we can use the script which designed by uiautomator1.0 on uiautomator2.0.

`05-03 15:25:31.266 26804-23062/io.appium.uiautomator2.server E/appium: Element not found: 
                                                                       io.appium.uiautomator2.common.exceptions.ElementNotFoundException: Could not find an element using supplied strategy. 
                                                                           at io.appium.uiautomator2.handler.FindElement.getXPathUiObject(FindElement.java:79)
                                                                           at io.appium.uiautomator2.handler.FindElement.findElement(FindElement.java:152)
                                                                           at io.appium.uiautomator2.handler.FindElement.safeHandle(FindElement.java:101)
                                                                           at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:54)
                                                                           at io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:204)
                                                                           at io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:195)
                                                                           at io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:44)
                                                                           at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
                                                                           at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
                                                                           at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
                                                                           at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
                                                                           at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
                                                                           at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
                                                                           at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
                                                                           at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
                                                                           at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
                                                                           at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
                                                                           at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
                                                                           at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
                                                                           at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
                                                                           at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
                                                                           at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
                                                                           at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
                                                                           at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
                                                                           at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
                                                                           at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
                                                                           at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)
                                                                           at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:514)
                                                                           at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:468)
                                                                           at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
                                                                           at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
                                                                           at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
                                                                           at java.lang.Thread.run(Thread.java:818)`

**Comment by mykola-mokhnach** [comment]
Does this xpath work better?

```
//*[boolean(string(@text)) and @content-desc='start_pager' and @resource-id='com.suning.snmessenger:id/loading_item_view']
```

**Comment by Carlgege** [comment]
@mykola-mokhnach 
It works OK, but i do not unstand it. Could you tell me the reason?
Thanks a lot!

And i update the source code and compile again, so the scripts designed by uiautomator1.0 can work normally on uiautomator2.0

`public AppiumResponse safeHandle(IHttpRequest request) {
        try {
            Logger.info("Find element command");
            KnownElements ke = new KnownElements();
            final JSONObject payload = getPayload(request);
            final String method = payload.getString("strategy");
            String selector = payload.getString("selector");
//update the xpath, if it contanins @text=''
            if (selector.contains("@text=''")) {
                selector = selector.replace("@text=''", "not(boolean(string(@text)))");
            }
            if (selector.contains("@content-desc=''")) {
                selector = selector.replace("@content-desc=''", "not(boolean(string(@content-desc)))");
            }
            if (selector.contains("@resource-id=''")) {
                selector = selector.replace("@resource-id=''", "not(boolean(string(@resource-id)))");
            }`

**Comment by mykola-mokhnach** [comment]
I cannot say for sure, but it looks like UIA2 does not add an attribute if it contains no value and UIA1 does this in any case, but assigns it to an empty string. I find the UIA2 approach more logical though it is not backward compatible.
