### ISSUE TITLE
Getting Error: Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 1 When I try to launch the app via appium Desktop app

### ISSUE THREAD

**Issue by shivanisrivastava17** [appium/appium#8348]
## The problem

When I try to launch the app on the simulator via the appium desktop app, it keeps giving me the error
'Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 1'

## Environment

* Appium version (or git revision) that exhibits the issue: v1.6.4
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: 10.12.3
* Node.js version (unless using Appium.app|exe): v7.9.0
* Mobile platform/version under test: iOS 10.3
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: appium-desktop app

## Link to Appium logs

```
[HTTP] <-- POST /wd/hub/session 500 42247 ms - 339 
[Appium] Welcome to Appium v1.6.4
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/ssrivastava/Downloads/Ebates.app","automationName":"XCUITest","deviceName":"iPhone Simulator","platformName":"iOS","platformVersion":"10.3","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/ssrivastava/Downloads/Ebates.app","automationName":"XCUITest","deviceName":"iPhone Simulator","platformName":"iOS","platformVersion":"10.3","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null,null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1493418771760 (15:32:51 GMT-0700 (PDT))
[Appium] Creating new XCUITestDriver (v2.27.2) session
[Appium] Capabilities:
[Appium]   app: '/Users/ssrivastava/Downloads/Ebates.app'
[Appium]   automationName: 'XCUITest'
[Appium]   deviceName: 'iPhone Simulator'
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '10.3'
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true
[XCUITest] XCUITestDriver version: 2.27.2
[BaseDriver] Session created with session id: 828dae36-2a0b-4d91-b140-1901a7a29a6d
[XCUITest] Xcode version set to '8.3.1' (tools v8.3.2.0.1.1492020469)
[XCUITest] iOS SDK Version set to '10.3'
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1493418771805 (15:32:51 GMT-0700 (PDT))
[XCUITest] Changing deviceName from 'iPhone Simulator' to 'iPhone 6'
[iOSSim] Constructing iOS simulator for Xcode version 8.3.1 with udid 'FE712DAE-8CF5-4EA4-9B85-79F6936BFFE4'
[XCUITest] Determining device to run tests on: udid: 'FE712DAE-8CF5-4EA4-9B85-79F6936BFFE4', real device: false
[BaseDriver] Using local app '/Users/ssrivastava/Downloads/Ebates.app'
[BaseDriver] Event 'appConfigured' logged at 1493418771958 (15:32:51 GMT-0700 (PDT))
[XCUITest] Checking whether app '/Users/ssrivastava/Downloads/Ebates.app' is actually present on file system
[XCUITest] App is present
[iOS] Getting bundle ID from app '/Users/ssrivastava/Downloads/Ebates.app': 'com.ebates.EbatesMobileDev'
[XCUITest] Setting 'connectHardwareKeyboard' Simulator option to 'on'
[BaseDriver] Event 'resetStarted' logged at 1493418771962 (15:32:51 GMT-0700 (PDT))
[XCUITest] Not scrubbing third party app in anticipation of uninstall
[BaseDriver] Event 'resetComplete' logged at 1493418772036 (15:32:52 GMT-0700 (PDT))
[iOSLog] Starting iOS 10.3 simulator log capture
[iOSLog] System log path: /Users/ssrivastava/Library/Logs/CoreSimulator/FE712DAE-8CF5-4EA4-9B85-79F6936BFFE4/system.log
[BaseDriver] Event 'logCaptureStarted' logged at 1493418772124 (15:32:52 GMT-0700 (PDT))
[XCUITest] Setting up simulator
[iOS] No reason to set locale
[iOS] No iOS / app preferences to set
[XCUITest] Simulator with udid 'FE712DAE-8CF5-4EA4-9B85-79F6936BFFE4' not booted. Booting up now
[iOSSim] Killing all iOS Simulators
[iOSSim] Simulator is not running. Continuing...
[iOSSim] Starting simulator with command: open -Fn /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID FE712DAE-8CF5-4EA4-9B85-79F6936BFFE4
[XCUITest] Reset requested. Removing app with id 'com.ebates.EbatesMobileDev' from the device
[iOSSim] Simulator booted in 13774ms
[BaseDriver] Event 'simStarted' logged at 1493418786058 (15:33:06 GMT-0700 (PDT))
[XCUITest] Installing /Users/ssrivastava/Downloads/Ebates.app on Simulator with UUID 'FE712DAE-8CF5-4EA4-9B85-79F6936BFFE4'...
[XCUITest] The app has been installed successfully.
[BaseDriver] Event 'appInstalled' logged at 1493418792410 (15:33:12 GMT-0700 (PDT))
[BaseDriver] Event 'wdaStartAttempted' logged at 1493418792412 (15:33:12 GMT-0700 (PDT))
[XCUITest] Using WDA path: '/private/var/folders/m5/4qxj3lt51xz2d374qwwgh7l0hmkzp4/T/AppTranslocation/6F31F7B8-6499-4111-8EF4-13AC992C694D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/private/var/folders/m5/4qxj3lt51xz2d374qwwgh7l0hmkzp4/T/AppTranslocation/6F31F7B8-6499-4111-8EF4-13AC992C694D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Running WebDriverAgent bootstrap script to install dependencies
[XCUITest] Fetching dependencies
[XCUITest] *** Downloading RoutingHTTPServer.framework binary at "v1.0.1"
[XCUITest] *** Skipped installing RoutingHTTPServer.framework binary due to the error:
[XCUITest] 	"Failed to write to /private/var/folders/m5/4qxj3lt51xz2d374qwwgh7l0hmkzp4/T/AppTranslocation/6F31F7B8-6499-4111-8EF4-13AC992C694D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/iOS: Error Domain=NSCocoaErrorDomain Code=642 "You can’t save the file “iOS” because the volume is read only." UserInfo={NSFilePath=/private/var/folders/m5/4qxj3lt51xz2d374qwwgh7l0hmkzp4/T/AppTranslocation/6F31F7B8-6499-4111-8EF4-13AC992C694D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/iOS, NSUnderlyingError=0x7fb8fcc6bdc0 {Error Domain=NSPOSIXErrorDomain Code=30 "Read-only file system"}}"
[XCUITest] *** Checking out RoutingHTTPServer at "v1.0.1"
[XCUITest] Failed to check out repository into /private/var/folders/m5/4qxj3lt51xz2d374qwwgh7l0hmkzp4/T/AppTranslocation/6F31F7B8-6499-4111-8EF4-13AC992C694D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/RoutingHTTPServer: Could not create working directory (Error Domain=NSCocoaErrorDomain Code=642 "You can’t save the file “RoutingHTTPServer” because the volume is read only." UserInfo={NSFilePath=/private/var/folders/m5/4qxj3lt51xz2d374qwwgh7l0hmkzp4/T/AppTranslocation/6F31F7B8-6499-4111-8EF4-13AC992C694D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/RoutingHTTPServer, NSUnderlyingError=0x7fb8fe092360 {Error Domain=NSPOSIXErrorDomain Code=30 "Read-only file system"}})
[BaseDriver] Event 'wdaStartFailed' logged at 1493418793261 (15:33:13 GMT-0700 (PDT))
[XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 1
[XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Removing WDA application from device
[BaseDriver] Event 'wdaStartAttempted' logged at 1493418803338 (15:33:23 GMT-0700 (PDT))
[XCUITest] Using WDA path: '/private/var/folders/m5/4qxj3lt51xz2d374qwwgh7l0hmkzp4/T/AppTranslocation/6F31F7B8-6499-4111-8EF4-13AC992C694D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/private/var/folders/m5/4qxj3lt51xz2d374qwwgh7l0hmkzp4/T/AppTranslocation/6F31F7B8-6499-4111-8EF4-13AC992C694D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Running WebDriverAgent bootstrap script to install dependencies
[XCUITest] Fetching dependencies
[XCUITest] *** Downloading RoutingHTTPServer.framework binary at "v1.0.1"
[XCUITest] *** Skipped installing RoutingHTTPServer.framework binary due to the error:
[XCUITest] 	"Failed to write to /private/var/folders/m5/4qxj3lt51xz2d374qwwgh7l0hmkzp4/T/AppTranslocation/6F31F7B8-6499-4111-8EF4-13AC992C694D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/iOS: Error Domain=NSCocoaErrorDomain Code=642 "You can’t save the file “iOS” because the volume is read only." UserInfo={NSFilePath=/private/var/folders/m5/4qxj3lt51xz2d374qwwgh7l0hmkzp4/T/AppTranslocation/6F31F7B8-6499-4111-8EF4-13AC992C694D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/iOS, NSUnderlyingError=0x7fde4fed6430 {Error Domain=NSPOSIXErrorDomain Code=30 "Read-only file system"}}"
[XCUITest] *** Checking out RoutingHTTPServer at "v1.0.1"
[XCUITest] Failed to check out repository into /private/var/folders/m5/4qxj3lt51xz2d374qwwgh7l0hmkzp4/T/AppTranslocation/6F31F7B8-6499-4111-8EF4-13AC992C694D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/RoutingHTTPServer: Could not create working directory (Error Domain=NSCocoaErrorDomain Code=642 "You can’t save the file “RoutingHTTPServer” because the volume is read only." UserInfo={NSFilePath=/private/var/folders/m5/4qxj3lt51xz2d374qwwgh7l0hmkzp4/T/AppTranslocation/6F31F7B8-6499-4111-8EF4-13AC992C694D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/RoutingHTTPServer, NSUnderlyingError=0x7fde4fedd9f0 {Error Domain=NSPOSIXErrorDomain Code=30 "Read-only file system"}})
[BaseDriver] Event 'wdaStartFailed' logged at 1493418804133 (15:33:24 GMT-0700 (PDT))
[XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 1
[XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Removing WDA application from device
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 1
    at XCUITestDriver.quitAndUninstall$ (/private/var/folders/m5/4qxj3lt51xz2d374qwwgh7l0hmkzp4/T/AppTranslocation/6F31F7B8-6499-4111-8EF4-13AC992C694D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:374:15)
    at tryCatch (/private/var/folders/m5/4qxj3lt51xz2d374qwwgh7l0hmkzp4/T/AppTranslocation/6F31F7B8-6499-4111-8EF4-13AC992C694D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/private/var/folders/m5/4qxj3lt51xz2d374qwwgh7l0hmkzp4/T/AppTranslocation/6F31F7B8-6499-4111-8EF4-13AC992C694D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/private/var/folders/m5/4qxj3lt51xz2d374qwwgh7l0hmkzp4/T/AppTranslocation/6F31F7B8-6499-4111-8EF4-13AC992C694D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/private/var/folders/m5/4qxj3lt51xz2d374qwwgh7l0hmkzp4/T/AppTranslocation/6F31F7B8-6499-4111-8EF4-13AC992C694D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 1
    at XCUITestDriver.quitAndUninstall$ (/private/var/folders/m5/4qxj3lt51xz2d374qwwgh7l0hmkzp4/T/AppTranslocation/6F31F7B8-6499-4111-8EF4-13AC992C694D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:374:15)
    at tryCatch (/private/var/folders/m5/4qxj3lt51xz2d374qwwgh7l0hmkzp4/T/AppTranslocation/6F31F7B8-6499-4111-8EF4-13AC992C694D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/private/var/folders/m5/4qxj3lt51xz2d374qwwgh7l0hmkzp4/T/AppTranslocation/6F31F7B8-6499-4111-8EF4-13AC992C694D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/private/var/folders/m5/4qxj3lt51xz2d374qwwgh7l0hmkzp4/T/AppTranslocation/6F31F7B8-6499-4111-8EF4-13AC992C694D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/private/var/folders/m5/4qxj3lt51xz2d374qwwgh7l0hmkzp4/T/AppTranslocation/6F31F7B8-6499-4111-8EF4-13AC992C694D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 1
    at XCUITestDriver.quitAndUninstall$ (/private/var/folders/m5/4qxj3lt51xz2d374qwwgh7l0hmkzp4/T/AppTranslocation/6F31F7B8-6499-4111-8EF4-13AC992C694D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:374:15)
    at tryCatch (/private/var/folders/m5/4qxj3lt51xz2d374qwwgh7l0hmkzp4/T/AppTranslocation/6F31F7B8-6499-4111-8EF4-13AC992C694D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/private/var/folders/m5/4qxj3lt51xz2d374qwwgh7l0hmkzp4/T/AppTranslocation/6F31F7B8-6499-4111-8EF4-13AC992C694D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/private/var/folders/m5/4qxj3lt51xz2d374qwwgh7l0hmkzp4/T/AppTranslocation/6F31F7B8-6499-4111-8EF4-13AC992C694D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/private/var/folders/m5/4qxj3lt51xz2d374qwwgh7l0hmkzp4/T/AppTranslocation/6F31F7B8-6499-4111-8EF4-13AC992C694D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by shivanisrivastava17** [comment]
Was able to figure it out. Permissions issue and wrong folder from where I was launching the desktop app
