### ISSUE TITLE
New window about:blank, appium cannot handle findElement

### ISSUE THREAD

**Issue by jglifonea** [appium/appium#8386]
I'm currently using appium version 1.6.4-beta.2

Scenario : On my android device, script had to click links to verify that the page is not broken and/or contains any element.

Problem : Whenever a page returns a about:blank page (generated in new window), my script focuses on the generated window and verifies if there are atleast 1 or more element present. Since it was just a white-page, it only consists of //html/body and no more. What I did is 

`driver.findElement(By.xpath("//html/body/div"));`
`driver.findElements(By.xpath("//html/body/div"));`

But whenever I use the codes above, it always throw the error below after certain duration(minutes)

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: Error: ESOCKETTIMEDOUT (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 240.10 seconds
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'C02DG08VDC7C', ip: '192.168.242.33', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_111'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{app=, deviceScreenSize=720x1280, networkConnectionEnabled=true, warnings={}, databaseEnabled=false, version=, deviceName=E8AZCY13A543, platform=WINDOWS, deviceUDID=E8AZCY13A543, desired={app=, platformVersion=4.4, browserName=Chrome, platformName=Android, version=, deviceName=Test Device, platform=WINDOWS}, platformVersion=4.4.2, webStorageEnabled=false, locationContextEnabled=false, takesScreenshot=true, browserName=Chrome, javascriptEnabled=true, deviceModel=ASUS_Z002, platformName=Android, deviceManufacturer=asus}]
Session ID: 8a8d0feb-9adf-4800-9ce9-dc0ef7701431
*** Element info: {Using=xpath, value=//html/body/div}

I expect it to throw a boolean (true/false).

**Comment by mykola-mokhnach** [comment]
Please attach full Appium log

ESOCKETTIMEDOUT means that Appium has been disconnected from chromedriver because it has, most likely, died.

**Comment by jglifonea** [comment]
hi @mykola-mokhnach , logs below : 

MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/5aa25ee3-b5af-4b83-8170-393e06c4e43a/element/0.279898883973535-1/click] to [POST http://127.0.0.1:8023/wd/hub/session/151d150972e54e6ea0ed5afc38e5f363/element/0.279898883973535-1/click] with body: {"id":"0.279898883973535-1"}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"151d150972e54e6ea0ed5afc38e5f363","status":0,"value":null}
[JSONWP Proxy] Replacing sessionId 151d150972e54e6ea0ed5afc38e5f363 with 5aa25ee3-b5af-4b83-8170-393e06c4e43a
[HTTP] <-- POST /wd/hub/session/5aa25ee3-b5af-4b83-8170-393e06c4e43a/element/0.279898883973535-1/click 200 877 ms - 76 
[HTTP] --> GET /wd/hub/session/5aa25ee3-b5af-4b83-8170-393e06c4e43a/window_handles {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/5aa25ee3-b5af-4b83-8170-393e06c4e43a/window_handles] to [GET http://127.0.0.1:8023/wd/hub/session/151d150972e54e6ea0ed5afc38e5f363/window_handles] with body: {}
[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"151d150972e54e6ea0ed5afc38e5f363\",\"status\":0,\"value\":[\"CDwindow-0\",\"CDwindow-9\"]}"
[JSONWP Proxy] Replacing sessionId 151d150972e54e6ea0ed5afc38e5f363 with 5aa25ee3-b5af-4b83-8170-393e06c4e43a
[HTTP] <-- GET /wd/hub/session/5aa25ee3-b5af-4b83-8170-393e06c4e43a/window_handles 200 15 ms - 99 
[HTTP] --> GET /wd/hub/session/5aa25ee3-b5af-4b83-8170-393e06c4e43a/window_handles {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/5aa25ee3-b5af-4b83-8170-393e06c4e43a/window_handles] to [GET http://127.0.0.1:8023/wd/hub/session/151d150972e54e6ea0ed5afc38e5f363/window_handles] with body: {}
[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"151d150972e54e6ea0ed5afc38e5f363\",\"status\":0,\"value\":[\"CDwindow-0\",\"CDwindow-9\"]}"
[JSONWP Proxy] Replacing sessionId 151d150972e54e6ea0ed5afc38e5f363 with 5aa25ee3-b5af-4b83-8170-393e06c4e43a
[HTTP] <-- GET /wd/hub/session/5aa25ee3-b5af-4b83-8170-393e06c4e43a/window_handles 200 14 ms - 99 
[HTTP] --> POST /wd/hub/session/5aa25ee3-b5af-4b83-8170-393e06c4e43a/window {"name":"CDwindow-9"}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/5aa25ee3-b5af-4b83-8170-393e06c4e43a/window] to [POST http://127.0.0.1:8023/wd/hub/session/151d150972e54e6ea0ed5afc38e5f363/window] with body: {"name":"CDwindow-9"}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"151d150972e54e6ea0ed5afc38e5f363","status":0,"value":null}
[JSONWP Proxy] Replacing sessionId 151d150972e54e6ea0ed5afc38e5f363 with 5aa25ee3-b5af-4b83-8170-393e06c4e43a
[HTTP] <-- POST /wd/hub/session/5aa25ee3-b5af-4b83-8170-393e06c4e43a/window 200 13 ms - 76 
[HTTP] --> POST /wd/hub/session/5aa25ee3-b5af-4b83-8170-393e06c4e43a/element {"using":"xpath","value":"//html/body"}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/5aa25ee3-b5af-4b83-8170-393e06c4e43a/element] to [POST http://127.0.0.1:8023/wd/hub/session/151d150972e54e6ea0ed5afc38e5f363/element] with body: {"using":"xpath","value":"//html/body"}
[MJSONWP] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: Error: ESOCKETTIMEDOUT
    at doJwpProxy$ (../../../lib/mjsonwp/mjsonwp.js:343:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session/5aa25ee3-b5af-4b83-8170-393e06c4e43a/element 500 240093 ms - 281 
[HTTP] --> DELETE /wd/hub/session/5aa25ee3-b5af-4b83-8170-393e06c4e43a {}
[debug] [MJSONWP] Calling AppiumDriver.deleteSession() with args: ["5aa25ee3-b5af-4b83-8170-393e06c4e43a"]
[debug] [BaseDriver] Event 'quitSessionRequested' logged at 1494204742523 (08:52:22 GMT+0800 (PHT))
[debug] [AndroidDriver] Shutting down Android driver
[debug] [AndroidDriver] Stopping chromedriver for context CHROMIUM
[debug] [Chromedriver] Changed state to 'stopping'
[debug] [JSONWP Proxy] Proxying [DELETE /] to [DELETE http://127.0.0.1:8023/wd/hub/session/151d150972e54e6ea0ed5afc38e5f363] with no body
[Chromedriver] [STDERR] [1815.334][SEVERE]: Timed out receiving message from renderer: 300.000
[Chromedriver] [STDERR] [1815.342][SEVERE]: Timed out receiving message from renderer: -0.009
[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"151d150972e54e6ea0ed5afc38e5f363\",\"status\":0,\"value\":null}"
[debug] [Chromedriver] Changed state to 'stopped'
[debug] [ADB] Pressing the HOME button
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/juliusglifonea/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","E8AZCY13A543","shell","input","keyevent",3]
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"shutdown"}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"shutdown"}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type SHUTDOWN
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"value":"OK, shutting down","status":0}
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [UiAutomator] Shutting down UiAutomator
[debug] [UiAutomator] Moving to state 'stopping'
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Closed client connection
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: numtests=1
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: stream=.
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: current=1
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS_CODE: 0
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: stream=
[debug] [AndroidBootstrap] [UIAUTO STDOUT] Test results for WatcherResultPrinter=.
[debug] [AndroidBootstrap] [UIAUTO STDOUT] Time: 1818.731
[debug] [AndroidBootstrap] [UIAUTO STDOUT] OK (1 test)
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS_CODE: -1
[debug] [UiAutomator] UiAutomator shut down normally
[debug] [UiAutomator] Moving to state 'stopped'
[debug] [ADB] Attempting to kill all uiautomator processes
[debug] [ADB] Getting all processes with uiautomator
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/juliusglifonea/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","E8AZCY13A543","shell","ps"]
[ADB] No uiautomator process found to kill, continuing...

**Comment by dbashford** [comment]
FWIW, latest Chrome, latest webdriver, not using Appium, just using webdriver.io to test hosted site, I see this error when attempting to execute the same selector twice.

So I'll run selector to make sure something is visible. Click a toggle that makes it go away. Then run the same selector to ensure it is gone.

Under that scenario, I get the `ESOCKETTIMEDOUT` and 💥 . This doesn't happen every time, but it does ~50% of the time.

**Comment by dpgraham** [comment]
Closing due to inactivity. If this is still an issue, let me know and I'll re-open.
