### ISSUE TITLE
Safari launcher app opening the default url which is http://www.apple.com but not opening the actual url

### ISSUE THREAD

**Issue by sujan792000** [appium/appium#8389]
## The problem
Appium: 1.5.3
Ios: 9.3.5
phone: iphone 6 plus

logs:
Launching Appium with command: 
```
'/Applications/Appium.app/Contents/Resources/node/bin/node' appium/build/lib/main.js --debug-log-spacing --platform-version "9.3" --platform-name "iOS" --show-ios-log --default-device

[Appium] Welcome to Appium v1.5.3

[Appium] Non-default server args:

[Appium] defaultDevice: true
[Appium] debugLogSpacing: true
[Appium] platformName: 'iOS'
[Appium] platformVersion: '9.3'
[Appium] showIOSLog: true
[Appium] Deprecated server args:
[Appium] --platform-name => --default-capabilities '{"platformName":"iOS"}'
[Appium] --platform-version => --default-capabilities '{"platformVersion":"9.3"}'
[Appium] --show-ios-log => --default-capabilities '{"showIOSLog":true}'

[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:

[Appium] platformName: 'iOS'

[Appium] platformVersion: '9.3'

[Appium] showIOSLog: true

[Appium] Appium REST http interface listener started on 0.0.0.0:4723

[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"platformVersion":"9.3","bundleId":"com.bytearc.SafariLauncher","browserName":"Safari","platformName":"iOS","udid":"8e81cffc33d2efde2ce59bd63604d228205a8bdd","deviceName":"CSD Admin's iphone"}}

[MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformVersion":"9.3","...

[Appium] Creating new IosDriver session

[Appium] Capabilities:
[Appium] platformVersion: '9.3'
[Appium] bundleId: 'com.bytearc.SafariLauncher'
[Appium] browserName: 'Safari'
[Appium] platformName: 'iOS'
[Appium] udid: '8e81cffc33d2efde2ce59bd63604d228205a8bdd'
[Appium] deviceName: 'CSD Admin\'s iphone'
[Appium] showIOSLog: true

[BaseDriver] Session created with session id: a1583cfc-6b74-4103-8e75-e42d8a3c9b00

[debug] [iOS] Not auto-detecting udid.

[debug] [iOS] Creating iDevice object with udid 8e81cffc33d2efde2ce59bd63604d228205a8bdd

[debug] [iOS] Removing any remaining instruments sockets

[debug] [iOS] Cleaned up instruments socket /var/folders/p9/7f04ddv176q3ytrydk21bxwws4xr0j/T/instruments_sock

[debug] [iOS] No language specified. Using default strings

[debug] [iOS] Strings file not found. Looking in 'en.lproj' directory

[iOS] Could not file localizable strings file 'Localizable.strings'!

[debug] [iOS] Creating instruments
[debug] [UIAuto] Preparing bootstrap code
[debug] [UIAuto] Dynamic bootstrap dir: /Users/cmdev/Library/Application Support/appium/bootstrap
[debug] [UIAuto] Dynamic env: {"nodePath":"/Applications/Appium.app/Contents/Resources/node/bin/node","commandProxyClientPath":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js","instrumentsSock":"/var/folders/p9/7f04ddv176q3ytrydk21bxwws4xr0j/T/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"grouped"}

[debug] [UIAuto] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...

[debug] [UIAuto] Dynamic bootstrap path: /Users/cmdev/Library/Application Support/appium/bootstrap/bootstrap-cac2cc6cbdbbc8df.js

[debug] [UIAuto] Reusing dynamic bootstrap: /Users/cmdev/Library/Application Support/appium/bootstrap/bootstrap-cac2cc6cbdbbc8df.js

[debug] [iOS] Running ios real device reset flow
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog

[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'

[debug] [iOS] App is installed.

[debug] [iOS] fullReset not requested. No need to install.

[debug] [iOS] Starting UIAutoClient, and launching Instruments.

[debug] [UIAuto] Instruments socket server started at /var/folders/p9/7f04ddv176q3ytrydk21bxwws4xr0j/T/instruments_sock

[debug] [Instruments] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments

[debug] [Instruments] Attempting to launch instruments, this is try #1

[Instruments] Launching instruments

[debug] [Instruments] Attempting to run app on real device with UDID '8e81cffc33d2efde2ce59bd63604d228205a8bdd'

[debug] [Instruments] Found Insruments-Without-Delay: /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-instruments/thirdparty/iwd7

[debug] [Instruments] Spawning instruments with command: '/Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /var/folders/p9/7f04ddv176q3ytrydk21bxwws4xr0j/T/appium-instruments/instrumentscli0.trace -w 8e81cffc33d2efde2ce59bd63604d228205a8bdd com.bytearc.SafariLauncher -e UIASCRIPT "/Users/cmdev/Library/Application Support/appium/bootstrap/bootstrap-cac2cc6cbdbbc8df.js" -e UIARESULTSPATH /var/folders/p9/7f04ddv176q3ytrydk21bxwws4xr0j/T/appium-instruments'
[debug] [Instruments] And extra without-delay env: {}
[debug] [Instruments] And launch timeouts (in ms): {"global":90000}

[iOSLog] [IOS_SYSLOG_ROW] May 4 09:54:43 CSD-Admins-iPhone com.apple.xpc.launchd[1] : assertion failed: 13G36: launchd + 116796 [9F6284CF-8A17-36CC-9DB5-85D510A21F14]: 0x3

[debug] [Instruments] [INST STDERR] 2017-05-04 09:54:43.202 instruments[74698:29071335] WebKit Threading Violation - initial use of WebKit from a secondary thread.

[iOSLog] [IOS_SYSLOG_ROW] May 4 09:54:45 CSD-Admins-iPhone SpringBoard[58] : SecTrustEvaluate [leaf AnchorSHA1 AnchorTrusted ChainLength IssuerCommonName SubjectCommonName]

[iOSLog] [IOS_SYSLOG_ROW] May 4 09:54:45 CSD-Admins-iPhone SpringBoard[58] : SecTrustEvaluate [leaf AnchorSHA1 AnchorTrusted ChainLength IssuerCommonName SubjectCommonName]

[iOSLog] [IOS_SYSLOG_ROW] May 4 09:54:45 CSD-Admins-iPhone SpringBoard[58] : SecTrustEvaluate [leaf AnchorSHA1 AnchorTrusted ChainLength IssuerCommonName SubjectCommonName]

[iOSLog] [IOS_SYSLOG_ROW] May 4 09:54:45 CSD-Admins-iPhone securityd[97] : secTaskDiagnoseEntitlements MISSING keychain entitlements: no stored taskRef found

[iOSLog] [IOS_SYSLOG_ROW] May 4 09:54:45 CSD-Admins-iPhone amfid[234] : SecTrustEvaluate [leaf AnchorSHA1 AnchorTrusted ChainLength IssuerCommonName SubjectCommonName]

[iOSLog] [IOS_SYSLOG_ROW] May 4 09:54:45 CSD-Admins-iPhone securityd[97] : secTaskDiagnoseEntitlements MISSING keychain entitlements: no stored taskRef found
[iOSLog] [IOS_SYSLOG_ROW] May 4 09:54:45 CSD-Admins-iPhone amfid[234] : SecTrustEvaluate [leaf AnchorSHA1 AnchorTrusted ChainLength IssuerCommonName SubjectCommonName]

[iOSLog] [IOS_SYSLOG_ROW] May 4 09:54:45 CSD-Admins-iPhone kernel[0] : xpcproxy[233] Container: /private/var/mobile/Containers/Data/Application/45780EFA-2475-4479-B3D0-157CB92A5A24 (sandbox)

[iOSLog] [IOS_SYSLOG_ROW] May 4 09:54:45 CSD-Admins-iPhone SpringBoard[58] : LICreateIconForImage passed NULL CGImageRef image

[iOSLog] [IOS_SYSLOG_ROW] May 4 09:54:45 CSD-Admins-iPhone DTServiceHub[232] : kernel symbolicator unable to open /mach.release.t7000

[iOSLog] [IOS_SYSLOG_ROW] May 4 09:54:45 CSD-Admins-iPhone DTServiceHub[232] : Device Info Service was unable to create symbolicator for the kernel

[iOSLog] [IOS_SYSLOG_ROW] May 4 09:54:46 CSD-Admins-iPhone com.apple.xpc.launchd[1] : assertion failed: 13G36: launchd + 116796 [9F6284CF-8A17-36CC-9DB5-85D510A21F14]: 0x3

[iOSLog] [IOS_SYSLOG_ROW] May 4 09:54:46 CSD-Admins-iPhone SafariLauncher[233] : App setting not found. Initializing app settings to default values.

[iOSLog] [IOS_SYSLOG_ROW] May 4 09:54:46 CSD-Admins-iPhone SafariLauncher[233] : height - 568.000000 : width - 320.000000

[iOSLog] [IOS_SYSLOG_ROW] May 4 09:54:46 CSD-Admins-iPhone UserEventAgent[26] : Tracking com.bytearc.SafariLauncher (via activity)

[iOSLog] [IOS_SYSLOG_ROW] May 4 09:54:46 CSD-Admins-iPhone notification_proxy[156] : 0x16e1bb000 -[MNPLockdownConnection receiveMessage]: lockdown_receive_message error!

[UIAuto] Instruments is ready to receive commands

[debug] [iOS] Instruments launched. Starting poll loop for new commands.

[debug] [iOS] Setting bootstrap config keys/values
[debug] [UIAuto] Socket data received (2 bytes)
[debug] [UIAuto] Got a result when we were not expecting one! Ignoring it
[debug] [UIAuto] Sending command to instruments: target = $.target();
au = $;
$.isVerbose = true;

[debug] [Instruments] [INST] 2017-05-04 08:54:48 +0000 Debug: evaluation finished

[debug] [Instruments] [INST] 2017-05-04 08:54:48 +0000 Debug: responding with:

[debug] [Instruments] [INST] 2017-05-04 08:54:48 +0000 Debug: Running system command #1: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /var/folders/p9/7f04ddv176q3ytrydk21bxwws4xr0j/T/instruments_sock 2,{"status":0,"v...

[debug] [UIAuto] Socket data received (27 bytes)

[debug] [UIAuto] Got result from instruments: {"status":0,"value":true}
[debug] [iOS] Setting initial orientation to PORTRAIT
[debug] [UIAuto] Sending command to instruments: au.setScreenOrientation('PORTRAIT')

[debug] [Instruments] [INST] 2017-05-04 08:54:49 +0000 Debug: Got new command 1 from instruments: au.setScreenOrientation('PORTRAIT')

[debug] [Instruments] [INST] 2017-05-04 08:54:49 +0000 Debug: evaluating au.setScreenOrientation('PORTRAIT')

[debug] [Instruments] [INST] 2017-05-04 08:54:49 +0000 Debug: target.setDeviceOrientation("1")

[debug] [UIAuto] Socket data received (33 bytes)

[debug] [UIAuto] Got result from instruments: {"status":0,"value":"PORTRAIT"}

[debug] [iOS] Attempting to launch Safari from Safari Launcher
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [UIAuto] Sending command to instruments: au.getElementByAccessibilityId('launch safari')

[debug] [Instruments] [INST] 2017-05-04 08:54:50 +0000 Debug: evaluation finished
[debug] [Instruments] [INST] 2017-05-04 08:54:50 +0000 Debug: responding with:
[debug] [Instruments] [INST] 2017-05-04 08:54:50 +0000 Debug: Running system command #2: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /var/folders/p9/7f04ddv176q3ytrydk21bxwws4xr0j/T/instruments_sock 2,{"status":0,"v...

[debug] [Instruments] [INST] 2017-05-04 08:54:51 +0000 Debug: Got new command 2 from instruments: au.getElementByAccessibilityId('launch safari')

[debug] [Instruments] [INST] 2017-05-04 08:54:51 +0000 Debug: evaluating au.getElementByAccessibilityId('launch safari')

[debug] [Instruments] [INST] 2017-05-04 08:54:51 +0000 Debug: evaluation finished

[debug] [UIAuto] Socket data received (38 bytes)

[debug] [UIAuto] Got result from instruments: {"status":0,"value":{"ELEMENT":"0"}}
[debug] [UIAuto] Sending command to instruments: au.tapById('0')

[debug] [Instruments] [INST] 2017-05-04 08:54:51 +0000 Debug: Lookup returned [object UIAButton] with the name "launch safari" (id: 0).
[debug] [Instruments] [INST] 2017-05-04 08:54:51 +0000 Debug: responding with:

[debug] [Instruments] [INST] 2017-05-04 08:54:51 +0000 Debug: Running system command #3: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /var/folders/p9/7f04ddv176q3ytrydk21bxwws4xr0j/T/instruments_sock 2,{"status":0,"v...

[iOSLog] [IOS_SYSLOG_ROW] May 4 09:54:52 CSD-Admins-iPhone MobileGestaltHelper[90] : libMobileGestalt MobileGestalt.c:281: server_access_check denied access to question UniqueDeviceID for pid 235

[iOSLog] [IOS_SYSLOG_ROW] May 4 09:54:52 CSD-Admins-iPhone ScriptAgent[235] : libMobileGestalt MobileGestaltSupport.m:151: pid 235 (ScriptAgent) does not have sandbox access for re6Zb+zwFKJNlkQTUeT+/w and IS NOT appropriately entitled

[iOSLog] [IOS_SYSLOG_ROW] May 4 09:54:52 CSD-Admins-iPhone ScriptAgent[235] : libMobileGestalt MobileGestalt.c:542: no access to UniqueDeviceID (see )

[debug] [Instruments] [INST] 2017-05-04 08:54:52 +0000 Debug: Got new command 3 from instruments: au.tapById('0')
[debug] [Instruments] [INST] 2017-05-04 08:54:52 +0000 Debug: evaluating au.tapById('0')
[debug] [Instruments] [INST] 2017-05-04 08:54:52 +0000 Debug: UIAButton.tap()

[iOSLog] [IOS_SYSLOG_ROW] May 4 09:54:52 CSD-Admins-iPhone SafariLauncher[233] : Launching URL - http://www.apple.com

[debug] [Instruments] [INST] 2017-05-04 08:54:52 +0000 Debug: evaluation finished

[debug] [Instruments] [INST] 2017-05-04 08:54:52 +0000 Debug: responding with:

[iOSLog] [IOS_SYSLOG_ROW] May 4 09:54:52 CSD-Admins-iPhone kernel[0] : xpcproxy[236] Container: /private/var/mobile/Containers/Data/Application/43B23427-4AE9-46A1-BF4D-B4F6A18E01EA (sandbox)

[debug] [UIAuto] Socket data received (25 bytes)
[debug] [UIAuto] Got result from instruments: {"status":0,"value":""}
[debug] [iOS] Clicked button, safari should be launching.
[debug] [iOS] Waiting for initial webview
[debug] [iOS] Waiting for 3000 ms before navigating to view.

[iOSLog] [IOS_SYSLOG_ROW] May 4 09:54:52 CSD-Admins-iPhone com.apple.xpc.launchd[1] : assertion failed: 13G36: launchd + 116796 [9F6284CF-8A17-36CC-9DB5-85D510A21F14]: 0x3

[iOSLog] [IOS_SYSLOG_ROW] May 4 09:54:52 CSD-Admins-iPhone gputoolsd[231] : schedule invalidation

[iOSLog] [IOS_SYSLOG_ROW] May 4 09:54:52 CSD-Admins-iPhone gputoolsd[231] : terminating daemon 0x126e0f460

[iOSLog] [IOS_SYSLOG_ROW] May 4 09:54:53 CSD-Admins-iPhone assertiond[67] : assertion failed: 13G36: assertiond + 30600 [0B862A7D-6E8B-3778-AD17-C7694ECD5BCD]: 0x16

[iOSLog] [IOS_SYSLOG_ROW] May 4 09:54:53 CSD-Admins-iPhone Unknown[67] :
[iOSLog] [IOS_SYSLOG_ROW] May 4 09:54:53 CSD-Admins-iPhone UserEventAgent[26] : Tracking com.apple.mobilesafari (via activity)

[iOSLog] [IOS_SYSLOG_ROW] May 4 09:54:53 CSD-Admins-iPhone com.apple.xpc.launchd[1] : assertion failed: 13G36: launchd + 116796 [9F6284CF-8A17-36CC-9DB5-85D510A21F14]: 0x3

[iOSLog] [IOS_SYSLOG_ROW] May 4 09:54:53 CSD-Admins-iPhone com.apple.xpc.launchd[1] : assertion failed: 13G36: launchd + 116796 [9F6284CF-8A17-36CC-9DB5-85D510A21F14]: 0x3

[iOSLog] [IOS_SYSLOG_ROW] May 4 09:54:53 CSD-Admins-iPhone MobileSafari[236] : KeychainGetICDPStatus: keychain: -25300

[iOSLog] [IOS_SYSLOG_ROW] May 4 09:54:53 CSD-Admins-iPhone MobileSafari[236] : KeychainGetICDPStatus: status: off

[iOSLog] [IOS_SYSLOG_ROW] May 4 09:54:53 CSD-Admins-iPhone MobileSafari[236] : KeychainGetICDPStatus: keychain: -25300
[iOSLog] [IOS_SYSLOG_ROW] May 4 09:54:53 CSD-Admins-iPhone MobileSafari[236] : KeychainGetICDPStatus: status: off

[iOSLog] [IOS_SYSLOG_ROW] May 4 09:54:53 CSD-Admins-iPhone com.apple.xpc.launchd[1] : assertion failed: 13G36: launchd + 116796 [9F6284CF-8A17-36CC-9DB5-85D510A21F14]: 0x3

[iOSLog] [IOS_SYSLOG_ROW] May 4 09:54:54 CSD-Admins-iPhone nsurlsessiond[122] : Task 1 for client {contents = "com.apple.mobileassetd"} completed with error - code: -999

[iOSLog] [IOS_SYSLOG_ROW] May 4 09:54:54 CSD-Admins-iPhone com.apple.xpc.launchd1 : Service exited with abnormal code: 1

[iOSLog] [IOS_SYSLOG_ROW] May 4 09:54:54 CSD-Admins-iPhone UserEventAgent[26] : Tracking com.apple.WebKit.Networking (via activity)

[iOSLog] [IOS_SYSLOG_ROW] May 4 09:54:54 CSD-Admins-iPhone UserEventAgent[26] : Tracking com.apple.WebKit.WebContent (via activity)

[iOSLog] [IOS_SYSLOG_ROW] May 4 09:54:54 CSD-Admins-iPhone MobileSafari[236] : Caching encoded userInfo to use until we are marked dirty again (UAUserActivity.m #1567)

[iOSLog] [IOS_SYSLOG_ROW] May 4 09:54:54 CSD-Admins-iPhone MobileSafari[236] : Caching encoded userInfo to use until we are marked dirty again (UAUserActivity.m #1567)

[debug] [iOS] Navigating to most recently opened webview

[debug] [iOS] Retrieving contexts and views

[debug] [iOS] Selecting by url: true (expected url: 'undefined')
[debug] [RemoteDebugger] Getting WebKitRemoteDebugger pageArray: localhost, 27753
[debug] [RemoteDebugger] Sending request to: http://localhost:27753/json

[MJSONWP] Encountered internal error running command: Error: Could not navigate to webview! Err: 503 - 

503 Service Temporarily Unavailable


Service Temporarily Unavailable

The server is temporarily unable to service your
request due to maintenance downtime or capacity
problems. Please try again later.


at IosDriver.spinHandles$ (lib/commands/context.js:463:15)
at tryCatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
at run (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
at flush (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
at _combinedTickCallback (internal/process/next_tick.js:67:7)
at process._tickCallback (internal/process/next_tick.js:98:9)
[HTTP] <-- POST /wd/hub/session 500 24262 ms - 513

[iOSLog] [IOS_SYSLOG_ROW] May 4 09:54:55 CSD-Admins-iPhone SpringBoard[58] : [MPUSystemMediaControls] Updating supported commands for now playing application.
[iOSLog] [IOS_SYSLOG_ROW] May 4 09:54:55 CSD-Admins-iPhone SpringBoard[58] : [MPUSystemMediaControls] Updating supported commands for now playing application.

[iOSLog] [IOS_SYSLOG_ROW] May 4 09:54:56 CSD-Admins-iPhone com.apple.xpc.launchd[1] : assertion failed: 13G36: launchd + 116796 [9F6284CF-8A17-36CC-9DB5-85D510A21F14]: 0x3

[iOSLog] [IOS_SYSLOG_ROW] May 4 09:54:56 CSD-Admins-iPhone com.apple.xpc.launchd[1] : assertion failed: 13G36: launchd + 116796 [9F6284CF-8A17-36CC-9DB5-85D510A21F14]: 0x3

[iOSLog] [IOS_SYSLOG_ROW] May 4 09:56:56 CSD-Admins-iPhone syncdefaultsd[119] : (Note ) marked "com.me.keyvalueservice" topic as "enabled" on

[iOSLog] [IOS_SYSLOG_ROW] May 4 09:57:46 CSD-Admins-iPhone SpringBoard[58] : [MPUSystemMediaControls] Updating supported commands for now playing application.

[iOSLog] [IOS_SYSLOG_ROW] May 4 09:57:46 CSD-Admins-iPhone SpringBoard[58] : [MPUSystemMediaControls] Updating supported commands for now playing application.

[iOSLog] [IOS_SYSLOG_ROW] May 4 09:57:47 CSD-Admins-iPhone SpringBoard[58] : [MPUSystemMediaControls] Updating supported commands for now playing application.

[iOSLog] [IOS_SYSLOG_ROW] May 4 09:57:47 CSD-Admins-iPhone SpringBoard[58] : [MPUSystemMediaControls] Updating supported commands for now playing application.

[iOSLog] [IOS_SYSLOG_ROW] May 4 09:58:14 CSD-Admins-iPhone SpringBoard[58] : [MPUSystemMediaControls] Updating supported commands for now playing application.

[iOSLog] [IOS_SYSLOG_ROW] May 4 09:58:14 CSD-Admins-iPhone SpringBoard[58] : [MPUSystemMediaControls] Updating supported commands for now playing application.
```
please any one help me on this
Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by imurchie** [comment]
Try setting the `safariInitialUrl` capability to your site to go there directly.

**Comment by sujan792000** [comment]
i used  "   desiredCapabilities.setCapability("safariInitialUrl","https:www.playstation.com/");". Still i am getting the same issue.
also I am running the ios_webkit_debug_proxy with 27753 port number

**Comment by imurchie** [comment]
I'm not sure what is going on with this error:
```
[debug] [RemoteDebugger] Sending request to: http://localhost:27753/json

[MJSONWP] Encountered internal error running command: Error: Could not navigate to webview! Err: 503 - 

503 Service Temporarily Unavailable


Service Temporarily Unavailable

The server is temporarily unable to service your
request due to maintenance downtime or capacity
problems. Please try again later.
```

What happens if you got to `http://localhost:27753/json` in your browser while ios-webkit-debug-proxy is running?
