### ISSUE TITLE
Setting network connection error: TypeError: Cannot read property 'on' of null

### ISSUE THREAD

**Issue by cool-firer** [appium/appium#8409]
```
[AndroidDriver] Setting network connection
[debug] [AndroidBootstrap] Ignoring bootstrap disconnect
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'D:\eclipse-java-luna-SR2-win32-x86_64\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","D8YDU16325002121","shell","settings","put","global","airplane_mode_on",0]
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Restarting adb
[debug] [ADB] Running 'D:\eclipse-java-luna-SR2-win32-x86_64\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","D8YDU16325002121","wait-for-device"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'D:\eclipse-java-luna-SR2-win32-x86_64\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","D8YDU16325002121","shell","echo","ping"]
[debug] [Logcat] Starting logcat capture
[debug] [ADB] Forwarding system: 4725 to device: 5724
[debug] [ADB] Running 'D:\eclipse-java-luna-SR2-win32-x86_64\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","D8YDU16325002121","forward","tcp:4725","tcp:5724"]
[debug] [UiAutomator] Starting UiAutomator
[debug] [UiAutomator] Moving to state 'starting'
[debug] [UiAutomator] Parsing uiautomator jar
[debug] [UiAutomator] Found jar name: 'AppiumBootstrap.jar'
[debug] [ADB] Running 'D:\eclipse-java-luna-SR2-win32-x86_64\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","D8YDU16325002121","push","D:\\tools\\appium2\\node_modules\\appium\\node_modules\\appium-android-bootstrap\\bootstrap\\bin\\AppiumBootstrap.jar","/data/local/tmp/"]
[debug] [ADB] Attempting to kill all uiautomator processes
[debug] [ADB] Getting all processes with uiautomator
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'D:\eclipse-java-luna-SR2-win32-x86_64\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","D8YDU16325002121","shell","ps"]
[debug] [ADB] Attempting to kill process 14254
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'D:\eclipse-java-luna-SR2-win32-x86_64\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","D8YDU16325002121","shell","kill",14254]
[UiAutomator] UiAutomator exited unexpectedly with code 0, signal null
[debug] [UiAutomator] Moving to state 'stopped'
[debug] [UiAutomator] Starting UIAutomator
[debug] [ADB] Creating ADB subprocess with args: ["-P",5037,"-s","D8YDU16325002121","shell","uiautomator","runtest","AppiumBootstrap.jar","-c","io.appium.android.bootstrap.Bootstrap","-e","pkg","com.boyaa.enginedlqp.maindevelop","-e","disableAndroidWatchers",false,"-e","acceptSslCerts",false]
[debug] [UiAutomator] Moving to state 'online'
[AndroidBootstrap] Error: Error occured while starting AndroidBootstrap. Original error: TypeError: Cannot read property 'on' of null
    at Object.wrappedLogger.errorAndThrow (..\../lib/logger.js:60:13)
    at AndroidBootstrap.start$ (..\../lib/bootstrap.js:107:11)
    at tryCatch (D:\tools\appium2\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (D:\tools\appium2\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (D:\tools\appium2\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (D:\tools\appium2\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 Error: Error occured while starting AndroidBootstrap. Original error: TypeError: Cannot read property 'on' of null
    at Object.wrappedLogger.errorAndThrow (..\../lib/logger.js:60:13)
    at AndroidBootstrap.start$ (..\../lib/bootstrap.js:107:11)
    at tryCatch (D:\tools\appium2\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (D:\tools\appium2\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (D:\tools\appium2\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (D:\tools\appium2\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:109:7)
[debug] [AndroidBootstrap] Watching for bootstrap disconnect
```

**Comment by cool-firer** [comment]
is it a bug?

**Comment by mykola-mokhnach** [comment]
Please fill out the default issue reporting form and provide the code and **full** Appium log

**Comment by cool-firer** [comment]
[appium_log.txt](https://github.com/appium/appium/files/988617/appium_log.txt)
log attached

**Comment by mykola-mokhnach** [comment]
the attached log is different from what is copypasted before. Please provide the correct one

**Comment by cool-firer** [comment]
@mykola-mokhnach  I tried serveral times, could not produce the error, but the error in log did exists every time I set network!

**Comment by mykola-mokhnach** [comment]
This error most likely means the server has died because of some unknown reason.
It might happen because you didn't set emulator name as **avd** capability, but rather use **deviceName**, which should be used with real devices only.

**Comment by cool-firer** [comment]
you mean the error occurs because I used emulator? but I did use real device run on my phone

**Comment by mykola-mokhnach** [comment]
I just say what I see in the log. The more detailed and accurate information you provide the more possibilities to get a solution you have.

**Comment by cool-firer** [comment]
This is the appium log and I used a real phone device to run.

**Comment by cool-firer** [comment]
This is the appium log, and I used a real android phone device to run, with python client, the error did occur every time I call: `driver.set_network_connection(ConnectionType.WIFI_ONLY)`

**Comment by dpgraham** [comment]
Closing this for now. If you can fill out the issue template and provide the full logs (the logs provided in the .txt are different from what was copied and pasted into the issue) I can re-open this and we can have a look.
