### ISSUE TITLE
Please help - does the Webdriveragent and the ipa need to have the same certificates?

### ISSUE THREAD

**Issue by Bugdestroyer** [appium/appium#8432]
## The problem 

I'm currently signing the webdriveragent with my own personal apple developer account. However, the ipa i'm trying to install / launch on the device is signed with the companies developers account / certificate.

Developers are sceptical that if we sign the webdriveragent with the companies developer account then that could mess up the live production builds, hence why i'm using my own personal developers account to set up webdriveragent.

Do i need to sign the webdriveragent with the same developers account as the ipa?

Currently following these tutorials: https://github.com/appium/appium/blob/master/docs/en/appium-setup/real-devices-ios.md

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

Appium 1.6.4 - device:  iOS 10.3.1 - Xcode: 8.3.2

Node: v4.4.7

Launching appium through the terminal

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

Here's a copy of my error logs:
```
2017-05-11 12:55:08.037 xcodebuild[11123:430878] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted} [Xcode]  [Xcode] ** TEST EXECUTE FAILED ** [Xcode]  [Xcode]  [Xcode] 2017-05-11 12:55:07.938035+0100 XCTRunner[1012:322734] Running tests... [Xcode] 2017-05-11 12:55:08.053274+0100 XCTRunner[1012:322734] The bundle “WebDriverAgentRunner” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle. [Xcode] 2017-05-11 12:55:08.053403+0100 XCTRunner1012:322734: Library not loaded: @rpath/RoutingHTTPServer.framework/RoutingHTTPServer [Xcode] Referenced from: /private/var/containers/Bundle/Application/6F5E3D36-BCF1-448A-BBCD-53B29BEA54F1/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib [Xcode] Reason: no suitable image found. Did find: [Xcode] /private/var/containers/Bundle/Application/6F5E3D36-BCF1-448A-BBCD-53B29BEA54F1/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer: required code signature missing for '/private/var/containers/Bundle/Application/6F5E3D36-BCF1-448A-BBCD-53B29BEA54F1/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer' [Xcode] ) [Xcode]  [XCUITest] xcodebuild exited with code '65' and signal 'null' [debug] [BaseDriver] Event 'wdaStartFailed' logged at 1494503708056 (12:55:08 GMT+0100 (BST)) [debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65 [debug] [XCUITest] Quitting and uninstalling WebDriverAgent, then retrying [XCUITest] Shutting down sub-processes [XCUITest] Shutting down iproxy process (pid 11122) [debug] [XCUITest] iproxy exited with code 'null' [debug] [XCUITest] Removing WDA application from device [XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65 at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:374:15) at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40) at GeneratorFunctionPrototype.invoke as _invoke at GeneratorFunctionPrototype.prototype.(anonymous function) as next at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37) at run (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:108:47) at /usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:119:28 at flush (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.microtask.js:19:5) at nextTickCallbackWith0Args (node.js:420:9) at process._tickCallback (node.js:349:13) [Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65] [debug] [XCUITest] Not clearing log files. Use clearSystemFiles capability to turn on. [debug] [iOSLog] Stopping iOS log capture [MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65 at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:374:15) at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40) at GeneratorFunctionPrototype.invoke as _invoke at GeneratorFunctionPrototype.prototype.(anonymous function) as next at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37) at run (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:108:47) at /usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:119:28 at flush (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.microtask.js:19:5) at nextTickCallbackWith0Args (node.js:420:9) at process._tickCallback (node.js:349:13) [HTTP] <-- POST /wd/hub/session 500 57159 ms - 230
```

**Comment by dpgraham** [comment]
I'm pretty sure they do need to be the same or else WebDriverAgent is unable to open the other app

**Comment by Bugdestroyer** [comment]
Hi dpgraham, 

Actually i did make it work by signing the webdriveragent with my own apple account id which is different to the one used to develop the app.

**Comment by qual** [comment]
I was also curious about the same thing. @imurchie, Could you throw some light on this ?

**Comment by rajfidel** [comment]
We have a similar setup where the ipa we test is built using developer certificates and the Webdriveragent is built using different certificates. They are not required to be same. You can launch apps from Apple (calculator etc.) as well using its bundleID.
