### ISSUE TITLE
Error while executing atom: [object Object]

### ISSUE THREAD

**Issue by shapovalovei** [appium/appium#8463]
## The problem

Sometimes I have error message: "Error while executing atom: [object Object]"

## Environment

* Appium version (or git revision) that exhibits the issue: *1.6.4 (from npm)*
* Last Appium version that did not exhibit the issue (if applicable): *1.6.4*
* Desktop OS/version used to run Appium: Sierra *10.12.4*
* Node.js version (unless using Appium.app|exe): *v7.5.0*
* Mobile platform/version under test: *iOS 10.3.1*
* Real device or emulator/simulator: *Real Device*
* Appium CLI or Appium.app|exe: *CLI*

## Details

```
[HTTP] --> POST /wd/hub/session/901c2751-c3b6-40c8-bf2d-2ac57be8c0e2/elements {"using":"xpath","value":"//div[@class='mw-note-value' and text()='8536675 ']"}
[debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["xpath","//div[@class='mw-note-value' and text()='8536675 ']","901c2751-c3b6-40c8-bf2d-2ac57be8c0e2"]
[debug] [XCUITest] Executing command 'findElements'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 30000 ms for condition
[debug] [RemoteDebugger] Executing 'find_elements' atom in default context
[debug] [RemoteDebugger] Sending javascript command (function(){return function(){var aa="function"...
[debug] [RemoteDebugger] Sending WebKit data: {"method":"Runtime.evaluate...
[debug] [RemoteDebugger] Receiving WebKit data: {"result":{"result":{"type"...
[debug] [RemoteDebugger] Found handler for message '20'
[MJSONWP] Encountered internal error running command: Error: Error while executing atom: [object Object]
    at XCUITestDriver.callee$0$0$ (../../../lib/commands/web.js:78:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session/901c2751-c3b6-40c8-bf2d-2ac57be8c0e2/elements 500 3235 ms - 214 
May 16, 2017 2:46:29 PM org.openqa.selenium.support.ui.ExpectedConditions findElement
WARNING: WebDriverException thrown by findElement(By.xpath: //div[@class='mw-note-value' and text()='8536675 '])
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error while executing atom: [object Object] (WARNING: The server did not provide any stacktrace information)
```
**START APPIUM**
```
 private static void startAppiumService() {
        if (service == null) {

            int appiumPort = Integer.parseInt(Config.APPIUM_PORT);
            int proxyPort = Integer.parseInt(Config.PROXY_PORT);

            if (Config.PLATFORM_NAME.equals("iOS")) {
                iOSProxyRunner(proxyPort);
            }

            killAppiumServer(appiumPort);

            AppiumServiceBuilder serviceBuilder = new AppiumServiceBuilder();
            serviceBuilder.usingPort(appiumPort);

            // serviceBuilder.withArgument(GeneralServerFlag.SESSION_OVERRIDE);

            if (!Boolean.valueOf(System.getProperty("verboseLogging"))) {
                serviceBuilder.withArgument(GeneralServerFlag.LOG_LEVEL, "warn");
            }

            if (Config.PLATFORM_NAME.equals("iOS")) {
                serviceBuilder.withArgument(IOSServerFlag.WEBKIT_DEBUG_PROXY_PORT, String.valueOf(proxyPort));
            }

            if (Config.PLATFORM_NAME.equals(ANDROID)) {
                serviceBuilder.withArgument(AndroidServerFlag.CHROME_DRIVER_PORT, Config.CHROMEDRIVER_PORT);
                serviceBuilder.withArgument(AndroidServerFlag.BOOTSTRAP_PORT_NUMBER, Config.BOOTSTRAP_PORT);
            }

            service = AppiumDriverLocalService.buildService(serviceBuilder);
            service.start();
        }
    }
```

START DRIVER

```
public static WebDriver getDriver() {

        if (!Boolean.valueOf(System.getProperty("use.desktop.browser"))) {
            startAppiumService();
        }

        if (driver == null) {

            String browserName = Config.DEVICE_BROWSER;
            String platformVersion = Config.PLATFORM_VERSION;
            String platformName = Config.PLATFORM_NAME;
            String deviceName = Config.DEVICE_NAME;
            String deviceUdid = Config.DEVICE_UID;
            String iproxyPort = Config.IPROXY_PORT;


            try {
                if (Boolean.valueOf(System.getProperty("use.desktop.browser"))) {
                    initChromeDriver();
                } else {
                    DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
                    desiredCapabilities.setCapability(MobileCapabilityType.BROWSER_NAME, browserName);
                    desiredCapabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, platformVersion);
                    desiredCapabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, platformName);
                    desiredCapabilities.setCapability(MobileCapabilityType.DEVICE_NAME, deviceName);
                    desiredCapabilities.setCapability(MobileCapabilityType.UDID, deviceUdid);

                    if (Config.PLATFORM_NAME.equals(IOS)) {
                        desiredCapabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "XCUITest");
                        desiredCapabilities.setCapability("wdaLocalPort", Integer.parseInt(iproxyPort));
                        desiredCapabilities.setCapability("useNewWDA", true);
                        desiredCapabilities.setCapability(IOSMobileCapabilityType.LAUNCH_TIMEOUT, 500000);

                        desiredCapabilities.setCapability("xcodeOrgId", "XXXXXXXXXX");
                        desiredCapabilities.setCapability("xcodeSigningId", "iPhone Developer");
                        desiredCapabilities.setCapability("updatedWDABundleId", "com.moovweb.WebDriverAgentRunner");

                        if (Boolean.valueOf(System.getProperty("verboseLogging"))) {
                            desiredCapabilities.setCapability("showXcodeLog", true);
                        }

                        //desiredCapabilities.setCapability("startIWDP", true);
                        //desiredCapabilities.setCapability("preventWDAAttachments", true);

                    }


                    eventListener = new MyWebDriverEventListener();

                    driver = new EventFiringWebDriver(new RemoteWebDriver(new URL(String.valueOf(service.getUrl())), desiredCapabilities)).register(eventListener);
                    driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
                    CommonFunctions.startVideoRecording();
                }

            } catch (Exception e) {
                throw new AssertionError("Can't create driver: " + e.getMessage());
            }
        }
        return driver;
    }
```

STARTING DATA
```
15:42:52: All Tests
15:42:53: Look for the launched iOS proxy on port: 27763
15:42:53: Port: 27763 is free
15:42:53: Execute command: [ios_webkit_debug_proxy, -c, f2b87b1ace53f97344a6c46ba67f33c60fb46cd1:27763, -F]
15:42:55: iOS Proxy started.
15:42:55: Look for the launched appium server on port: 4733
15:42:55: Port: 4733 is free
15:42:55: 
15:42:55: *************************** STARTING APPIUM SERVICE *******************************
15:42:55: APPIUM PORT: 4733
15:42:55: IOS WEB PROXY PORT: 27763
15:42:55: VERBOSE LOGGING: 
15:42:55: PROJECT TRACKING: 
15:43:00: APPIUM URL: http://0.0.0.0:4733/wd/hub
15:43:00: ***********************************************************************************
15:43:00: 
15:43:00: 
15:43:00: **************************** CREATING REMOTE WEB DRIVER ***************************
15:43:00: PLATFORM NAME: iOS
15:43:00: PLATFORM VERSION: 10.3.1
15:43:00: DEVICE NAME: iPhone 6
15:43:00: DEVICE BROWSER: Safari
15:43:00: DEVICE UDID: f2b87b1ace53f97344a6c46ba67f33c60fb46cd1
15:43:00: DEVICE USB PORT: 8111
15:43:00: APPIUM URL: http://0.0.0.0:4733/wd/hub
15:43:00: ***********************************************************************************
15:43:00: 
15:43:23: Running: flick video -a start -p ios -u f2b87b1ace53f97344a6c46ba67f33c60fb46cd1 -e true
```

**Comment by shapovalovei** [comment]
hey all, any updates ?

**Comment by imurchie** [comment]
Can you try with the latest version of Appium (`npm uninstall -g appium && npm install -g appium@beta`)? It should, at least, improve logging of the error.

**Comment by shapovalovei** [comment]
@imurchie Thanks
Today I install appium 1.6.5-beta and I doesn't  see another logs. But I investigate this problem

Safari debugger:
![img_0303](https://cloud.githubusercontent.com/assets/8914951/26163149/6afabdfa-3b31-11e7-9f25-c1903b1ad845.JPG)

Ios-WebKit-debug-proxy:
![img_0304](https://cloud.githubusercontent.com/assets/8914951/26163169/8076b1c0-3b31-11e7-8ecc-ed4712097dbc.JPG)

**Comment by imurchie** [comment]
I'm not sure what I'm supposed to be looking at here.

Can you post a link to a [gist](https://gist.github.com) of the Appium server logs so I can see what is happening there? The difference in the logging is small.

**Comment by shapovalovei** [comment]
@imurchie where I can get this logs ? 


For example You about this log ?
```
[debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["xpath","//div[@class='mw-note-value' and text()='8536675 ']","901c2751-c3b6-40c8-bf2d-2ac57be8c0e2"]
[debug] [XCUITest] Executing command 'findElements'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 30000 ms for condition
```

**Comment by imurchie** [comment]
Yes, wherever that snippet came from, that is the server log. In order to get the best idea of what is going on, the _full_ logs are required, since issues are, most often, dependent on configuration.

**Comment by shapovalovei** [comment]
@imurchie Appium Server Logs: https://pastebin.com/mqqU8W22

**Comment by shapovalovei** [comment]
Any updates?

**Comment by imurchie** [comment]
Not really. I don't think the update got into your install. The extra logging is in version 2.29.1 and I see in the logs you have 2.29.0.

**Comment by shapovalovei** [comment]
<img width="569" alt="screen shot 2017-05-18 at 19 24 12" src="https://cloud.githubusercontent.com/assets/8914951/26212847/a459e3cc-3bff-11e7-8d40-41b8d2e8cff5.png">

**Comment by imurchie** [comment]
I guess so. And you could run `npm cache clean` to make sure you get the latest dependencies.

**Comment by shapovalovei** [comment]
@imurchie 
`npm cache clean`
`npm uninstall -g appium`
`npm install -g appium@beta`

After clean cash and reinstall, I can get more logs:
https://gist.github.com/shapovalovei/2175a48a82aa5137281e22fe2e884d3a

**Comment by imurchie** [comment]
Alright. A little more information to go on:
```
{"result":{"result":{"type":"object","objectId":"{\"injectedScriptId\":3,\"id\":1}","subtype":"error","className":"SyntaxError","description":"SyntaxError: Unexpected EOF"},"wasThrown":true},"id":22}
```

**Comment by imurchie** [comment]
What version of the webkit debug proxy are you running? (`ios_webkit_debug_proxy --version`)

**Comment by shapovalovei** [comment]
```
ios_webkit_debug_proxy 1.7.1
Built with libimobiledevice v1.2.0, libplist v1.12
```

**Comment by shapovalovei** [comment]
@imurchie About screenshots and `ios_webkit_debug_proxy`. On this screenshot, I don't see any tags
<img width="1873" alt="screen shot 2017-05-17 at 17 43 50" src="https://cloud.githubusercontent.com/assets/8914951/26220064/d6e332d4-3c19-11e7-9ef5-39b9960b7d58.png">

**Comment by shapovalovei** [comment]
@imurchie About screenshots and `ios_webkit_debug_proxy`.

We can run ios-web manualally with command for exemplel `ios_webkit_debug_proxy -c 4ea8dd11e8c4fbc1a2deadbeefa0fd3bbbb268c7:9227` after that open browser and nivigate to page `localhost:27754`  And I don't see any tags. Please see attached screenhoot 
<img width="1873" alt="screen shot 2017-05-17 at 17 43 50" src="https://cloud.githubusercontent.com/assets/8914951/26220064/d6e332d4-3c19-11e7-9ef5-39b9960b7d58.png">

**Comment by imurchie** [comment]
I tracked it down. You have a strange character after `8536668`, before the closing `'`, in your XPath.

```
(//div[@class='mw-note-value' and text()='8536668 '])[1]
```

**Comment by imurchie** [comment]
I recreated your test and remove that character (which is not visible) and it worked fine.

**Comment by shapovalovei** [comment]
@imurchie 
On Android I don't have this problem. And this `xpath` works. 
I'm sorry for that issues. Many Thanks for help.

**Comment by shapovalovei** [comment]
@imurchie strange, change `xpath` but after several tests I have error again 

```
OST /wd/hub/session/38bd47e4-2e23-4566-a9d9-afb73046803c/execute 200 9 ms - 76 
[INFO]  23:52:13: [WebDriverEvent] Trying to find Element By:  By.xpath: //div[@class='mw-note-value' and text()='8536675 '][1]
[HTTP] --> POST /wd/hub/session/38bd47e4-2e23-4566-a9d9-afb73046803c/elements {"using":"xpath","value":"//div[@class='mw-note-value' and text()='8536675 '][1]"}
[debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["xpath","//div[@class='mw-note-value' and text()='8536675 '][1]","38bd47e4-2e23-4566-a9d9-afb73046803c"]
[debug] [XCUITest] Executing command 'findElements'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 30000 ms for condition
[debug] [RemoteDebugger] Executing 'find_elements' atom in default context
[debug] [RemoteDebugger] Sending javascript command (function(){return function(){var aa="function"...
[debug] [RemoteDebugger] Sending WebKit data: {"method":"Runtime.evaluate","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true,"expression":"(function(){return function(){var aa=\"function...
[debug] [RemoteDebugger] Webkit response timeout: 5000
[debug] [RemoteDebugger] Receiving WebKit data: {"result":{"result":{"type":"object","objectId":"{\"injectedScriptId\":3,\"id\":1}","subtype":"error","className":"SyntaxError","description":"SyntaxError: Unexpected EOF"},"wasThrown":true},"id":60}
[debug] [RemoteDebugger] Found handler for message '60'
[MJSONWP] Encountered internal error running command: Error: Error while executing atom: {"type":"object","objectId":"{\"injectedScriptId\":3,\"id\":1}","subtype":"error","className":"SyntaxError","description":"SyntaxError: [HTTP] <-- POST /wd/hub/session/38bd47e4-2e2Unexpe3-4566-a9d9-afcted EOF"}
    at XCUITestDriver.callee$0$[INFO]  23:52:13: [WebDriverEvent] 

b73046803c/elements 500 26 ms - 379 
0$ (../../../lib/commands/web.js:79:11)
    at tryCatch (/usr/[INFO]  23:52:13: [WebDriverEvent] Exception occurred: 
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error while executing atom: {"type":"object","objectId":"{\"injectedScriptId\":3,\"id\":1}","subtype":"error","className":"SyntaxError","description":"SyntaxError: Unexpected EOF"} (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 30 milliseconds
Build info: version: '3.2.0', revision: '8c03df6b79', time: '2017-02-23 10:51:31 +0000'
System info: host: 'MacBook-Pro-Eugene.local', ip: 'fe80:0:0:0:14a4:17bc:13bf:4442%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.4', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities [{networkConnectionEnabled=false, xcodeOrgId=Y95G5M3Q84, databaseEnabled=false, deviceName=iPhone 6, launchTimeout=500000, updatedWDABundleId=com.moovweb.WebDriverAgentRunner, xcodeSigningId=iPhone Developer, platform=MAC, wdaLocalPort=8111, platformVersion=10.3.1, webStorageEnabled=false, locationContextEnabled=false, automationName=XCUITest, useNewWDA=true, browserName=Safari, takesScreenshot=true, javascriptEnabled=true, platformName=iOS, udid=f2b87b1ace53f97344a6c46ba67f33c60fb46cd1}]
Session ID: 38bd47e4-2e23-4566-a9d9-afb73046803c
*** Element info: {Using=xpath, value=//div[@class='mw-note-value' and text()='8536675 '][1]}
local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototyp[INFO]  23:52:13: [WebDriverEvent] 

e.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] --> GET /wd/hub/session/38bd47e4-2e23-4566-a9d9-afb73046803c/screenshot {}
```

**Comment by shapovalovei** [comment]
@imurchie sometimes I have this problem again 

```
[INFO]  00:13:34: [PepBoysProductPage] Checking if element: 'By.xpath: //div[@class='mw-note-value' and text()='8536668 ']' visible
[INFO]  00:13:34: [WebDriverEvent] Trying to find Element By:  By.xpath: //div[@class='mw-note-value' and text()='8536668 ']
[HTTP] --> POST /wd/hub/session/46012859-5b90-4fdc-a302-af3017127b15/elements {"using":"xpath","value":"//div[@class='mw-note-value' and text()='8536668 ']"}
[debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["xpath","//div[@class='mw-note-value' and text()='8536668 ']","46012859-5b90-4fdc-a302-af3017127b15"]
[debug] [XCUITest] Executing command 'findElements'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 30000 ms for condition
[debug] [RemoteDebugger] Executing 'find_elements' atom in default context
[debug] [RemoteDebugger] Sending javascript command (function(){return function(){var aa="function"...
[debug] [RemoteDebugger] Sending WebKit data: {"method":"Runtime.evaluate","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true,"expression":"(function(){return function(){var aa=\"function...
[debug] [RemoteDebugger] Webkit response timeout: 5000
[debug] [RemoteDebugger] Receiving WebKit data: {"result":{"result":{"type":"object","objectId":"{\"injectedScriptId\":3,\"id\":1}","subtype":"error","className":"SyntaxError","description":"SyntaxError: Unexpected EOF"},"wasThrown":true},"id":50}
[debug] [RemoteDebugger] Found handler for message '50'
[MJSONWP] Encountered internal error running command: Error: Error while executing atom: {"type":"object","objectId":"{\"injectedScriptId\":3,\"id\":1}","subtype":"error","className":"SyntaxError","description":"SyntaxError: Unexpected EOF"}
    at XCUITestDriver.callee$0$0$ (../../../lib/commands/web.js:79:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session/46012859-5b90-4fdc-a302-af3017127b15/elements 500 43 ms - 379 
[INFO]  00:13:34: [WebDriverEvent] 
```

**Comment by imurchie** [comment]
I still see the same extra character there. The character is http://www.charbase.com/2028-unicode-line-separator

If you go to a site like https://www.freeformatter.com/javascript-escape.html and put in `["xpath","//div[@class='mw-note-value' and text()='8536668 ']"`, then click "Escape" you will see it there.

I don't know why it is there. But it is not Appium that is putting it there.

**Comment by shapovalovei** [comment]
Thanks for you helps. I get ID from file. Its problem with file.

**Comment by imurchie** [comment]
I guess you'll need to trim the id from the file, then.
