### ISSUE TITLE
An unknown server-side error

### ISSUE THREAD

**Issue by cyqluowang** [appium/appium#8470]
## The problem

```
20170517 15:42:01  install app
20170517 15:42:01  start install app
20170517 15:42:31  TestGyUid processTimeout

Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pycharm/_jb_unittest_runner.py", line 35, in <module>
    main(argv=args, module=None, testRunner=test_runner)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/main.py", line 95, in __init__
    self.runTests()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/main.py", line 232, in runTests
20170517 15:42:31  An unknown server-side error occurred while processing the command. Original error: ENOENT: no such file or directory, open '/var/folders/y4/q9m86byx1037b00gynkrtt_40000gn/T/appium117417-39135-154bjv3.dn2qmbcsor.tmp'
    self.result = testRunner.run(self.test)

  File "/Applications/PyCharm.app/Contents/helpers/pycharm/teamcity/unittestpy.py", line 231, in run
    return super(TeamcityTestRunner, self).run(test)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/runner.py", line 151, in run
    test(result)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/suite.py", line 108, in run
    test(result)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/suite.py", line 108, in run
    test(result)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 393, in __call__
    return self.run(*args, **kwds)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 370, in run
    result.stopTest(self)

Process finished with exit code 1
```

## Environment

mac 10.12.4
appium 1.6.4

![image](https://cloud.githubusercontent.com/assets/5178594/26143722/ac292a96-3b18-11e7-9d96-76c5d2d5caec.png)

**Comment by mykola-mokhnach** [comment]
Make sure the user, which executed Appium daemon has write access to /var/folders

**Comment by cyqluowang** [comment]
OK  tks, close
