### ISSUE TITLE
Android: Double tap fails due to doubling coordinates

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium#8485]
## The problem

Test code:
```
new TouchAction((MobileDriver) driver).press(x,y).waitAction(Duration.ofMillis(50)).release().perform().press(x,y).waitAction(Duration.ofMillis(50)).release().perform()
```
Double tap itself happens but server gives error.

## Environment

* Appium version (or git revision) that exhibits the issue: v1.6.5-beta, java-client: 5.0.0-BETA8
* Mobile platform/version under test: Android
* Real device or emulator/simulator: real device android 6.0

## Details

Appium logs:
```
   doubleTapElement(): x - 314, y - 1875
2017-05-18 09:21:34:971 - [HTTP] --> POST /wd/hub/session/d1bba020-175d-473f-a6f4-ee5ece6f1371/touch/perform {"actions":[{"action":"press","options":{"x":314,"y":1875}},{"action":"wait","options":{"ms":50}},{"action":"release","options":{}}]}
2017-05-18 09:21:34:971 - [debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":314,"y":1875}},{"action":"wait","options":{"ms":50}},{"action":"release","options":{}}],"d1bba020-175d-473f-a6f4-ee5ece6f1371"]
2017-05-18 09:21:34:977 - [debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:touchDown","params":{"x":314,"y":1875}}
2017-05-18 09:21:34:980 - [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:touchDown","params":{"x":314,"y":1875}}
2017-05-18 09:21:34:981 - [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
2017-05-18 09:21:34:982 - [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: touchDown
2017-05-18 09:21:34:996 - [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Display bounds: [0,0][1440,2392]
2017-05-18 09:21:34:997 - [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Performing TouchDown using element? false x: 314, y: 1875
2017-05-18 09:21:35:025 - [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":true}
2017-05-18 09:21:35:026 - [debug] [AndroidBootstrap] Received command result from bootstrap
2017-05-18 09:21:35:084 - [debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:touchUp","params":{"x":314,"y":1875}}
2017-05-18 09:21:35:089 - [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:touchUp","params":{"x":314,"y":1875}}
2017-05-18 09:21:35:089 - [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
2017-05-18 09:21:35:089 - [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: touchUp
2017-05-18 09:21:35:091 - [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Display bounds: [0,0][1440,2392]
2017-05-18 09:21:35:092 - [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Performing TouchUp using element? false x: 314, y: 1875
2017-05-18 09:21:35:127 - [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":true}
2017-05-18 09:21:35:129 - [debug] [AndroidBootstrap] Received command result from bootstrap
2017-05-18 09:21:35:130 - [debug] [MJSONWP] Responding to client with driver.performTouch() result: null
2017-05-18 09:21:35:130 - [HTTP] <-- POST /wd/hub/session/d1bba020-175d-473f-a6f4-ee5ece6f1371/touch/perform 200 159 ms - 76 
2017-05-18 09:21:35:134 - [HTTP] --> POST /wd/hub/session/d1bba020-175d-473f-a6f4-ee5ece6f1371/touch/perform {"actions":[{"action":"press","options":{"x":314,"y":1875}},{"action":"wait","options":{"ms":50}},{"action":"release","options":{}},{"action":"press","options":{"x":314,"y":1875}},{"action":"wait","options":{"ms":50}},{"action":"release","options":{}}]}
2017-05-18 09:21:35:134 - [debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":314,"y":1875}},{"action":"wait","options":{"ms":50}},{"action":"release","options":{}},{"action":"press","options":{"x":314,"y":1875}},{"action":"wait","options":{"ms":50}},{"action":"release","options":{}}],"d1bba020-175d-473f-a6f4-ee5ece6f1371"]
2017-05-18 09:21:35:136 - [debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:touchDown","params":{"x":314,"y":1875}}
2017-05-18 09:21:35:142 - [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:touchDown","params":{"x":314,"y":1875}}
2017-05-18 09:21:35:142 - [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
2017-05-18 09:21:35:142 - [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: touchDown
2017-05-18 09:21:35:145 - [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Display bounds: [0,0][1440,2392]
2017-05-18 09:21:35:147 - [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Performing TouchDown using element? false x: 314, y: 1875
2017-05-18 09:21:35:160 - [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":true}
2017-05-18 09:21:35:161 - [debug] [AndroidBootstrap] Received command result from bootstrap
2017-05-18 09:21:35:216 - [debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:touchUp","params":{"x":314,"y":1875}}
2017-05-18 09:21:35:220 - [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:touchUp","params":{"x":314,"y":1875}}
2017-05-18 09:21:35:220 - [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
2017-05-18 09:21:35:220 - [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: touchUp
2017-05-18 09:21:35:224 - [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Display bounds: [0,0][1440,2392]
2017-05-18 09:21:35:224 - [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Performing TouchUp using element? false x: 314, y: 1875
2017-05-18 09:21:35:255 - [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":true}
2017-05-18 09:21:35:256 - [debug] [AndroidBootstrap] Received command result from bootstrap
2017-05-18 09:21:35:256 - [debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:touchDown","params":{"x":628,"y":3750}}
2017-05-18 09:21:35:260 - [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:touchDown","params":{"x":628,"y":3750}}
2017-05-18 09:21:35:260 - [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
2017-05-18 09:21:35:261 - [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: touchDown
2017-05-18 09:21:35:264 - [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Display bounds: [0,0][1440,2392]
2017-05-18 09:21:35:264 - [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":29,"value":"Coordinate [x=628.0, y=3750.0] is outside of element rect: [0,0][1440,2392]"}
```

**Comment by mykola-mokhnach** [comment]
I assume perform should be called only once per chain.
One must create two chains to call perform twice

**Comment by amedvedjev** [comment]
@mykola-mokhnach tried with same result:
```
new TouchAction((MobileDriver) driver).press(x,y).waitAction(Duration.ofMillis(50)).release().
                    press(x,y).waitAction(Duration.ofMillis(50)).release().perform();
```

**Comment by amedvedjev** [comment]
original issue happened with old UIAutomator and Android 6.0. Tried with Android 7.0 and ANDROID_UIAUTOMATOR2. 
```
new TouchAction((MobileDriver) driver).press(x,y).waitAction(Duration.ofMillis(50)).release().
                    press(x,y).waitAction(Duration.ofMillis(50)).release().perform();
```

result was second tap did not happen.
```
doubleTapElement(): x - 314, y - 1875
2017-05-18 11:58:20:250 - [HTTP] --> POST /wd/hub/session/c8639f6c-8715-4e8c-90bf-2bb48dc4b2df/touch/perform {"actions":[{"action":"press","options":{"x":314,"y":1875}},{"action":"wait","options":{"ms":50}},{"action":"release","options":{}},{"action":"press","options":{"x":314,"y":1875}},{"action":"wait","options":{"ms":50}},{"action":"release","options":{}}]}
2017-05-18 11:58:20:250 - [debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":314,"y":1875}},{"action":"wait","options":{"ms":50}},{"action":"release","options":{}},{"action":"press","options":{"x":314,"y":1875}},{"action":"wait","options":{"ms":50}},{"action":"release","options":{}}],"c8639f6c-8715-4e8c-90bf-2bb48dc4b2df"]
2017-05-18 11:58:20:256 - [debug] [JSONWP Proxy] Proxying [POST /touch/down] to [POST http://localhost:8200/wd/hub/session/9965e993-0a6a-4e16-b571-e5c8219a5a85/touch/down] with body: {"params":{"x":314,"y":1875}}
2017-05-18 11:58:20:306 - [debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"9965e993-0a6a-4e16-b571-e5c8219a5a85","status":0,"value":true}
2017-05-18 11:58:20:359 - [debug] [JSONWP Proxy] Proxying [POST /touch/up] to [POST http://localhost:8200/wd/hub/session/9965e993-0a6a-4e16-b571-e5c8219a5a85/touch/up] with body: {"params":{"x":314,"y":1875}}
2017-05-18 11:58:20:414 - [debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"9965e993-0a6a-4e16-b571-e5c8219a5a85","status":0,"value":true}
2017-05-18 11:58:20:415 - [debug] [JSONWP Proxy] Proxying [POST /touch/down] to [POST http://localhost:8200/wd/hub/session/9965e993-0a6a-4e16-b571-e5c8219a5a85/touch/down] with body: {"params":{"x":628,"y":3750}}
2017-05-18 11:58:20:436 - [MJSONWP] Encountered internal error running command:  {"jsonwp":{"sessionId":"9965e993-0a6a-4e16-b571-e5c8219a5a85","status":13,"value":false}} ProxyRequestError: Could not proxy command to remote server. Original error: 500 - {"sessionId":"9965e993-0a6a-4e16-b571-e5c8219a5a85","status":13,"value":false}
    at JWProxy.proxy$ (../../../lib/jsonwp-proxy/proxy.js:144:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
```

**Comment by JimRaid** [comment]
As far as I know the second command is relative to the first one. 
But I am not sure. So the second press should happen on (0,0) instead of (x,y)

**Comment by dpgraham** [comment]
Does this issue still persist?

**Comment by jlipps** [comment]
closing due to inactivity
