### ISSUE TITLE
I can´t connect my testCase with IOS

### ISSUE THREAD

**Issue by SergioParissi** [appium/appium#8516]
## The problem

I tried to run my C# unit test in safari, but appium always return me an error, my desiredCapabilities are:

            capability.SetCapability("deviceName", "iPhone 6S");
            capability.SetCapability("platformName", "iOS");
            capability.SetCapability("udid", "2BDF429984C50358010656C0B12D0640C122CC52");
            capability.SetCapability("version", "10.3.1");
            capability.SetCapability("app", "Safari");

And appium response:
```
[iOS] Error: Could not find path to Xcode by symlinks located in /var/db/xcode_select_link, or /usr/share/xcode-select/xcode_dir_link
    at getPathFromSymlink$ (C:\Users\BMXDDT005072\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-xcode\lib\xcode.js:79:9)
    at tryCatch (C:\Users\BMXDDT005072\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\BMXDDT005072\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\BMXDDT005072\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\BMXDDT005072\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
 Error: Could not find path to Xcode by symlinks located in /var/db/xcode_select_link, or /usr/share/xcode-select/xcode_dir_link
    at getPathFromSymlink$ (C:\Users\BMXDDT005072\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-xcode\lib\xcode.js:79:9)
    at tryCatch (C:\Users\BMXDDT005072\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\BMXDDT005072\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\BMXDDT005072\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\BMXDDT005072\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[iOS] Could not determine Xcode version: Could not find path to Xcode by symlinks located in /var/db/xcode_select_link, or /usr/share/xcode-select/xcode_dir_link
[MJSONWP] Encountered internal error running command: Error: Could not find path to Xcode by symlinks located in /var/db/xcode_select_link, or /usr/share/xcode-select/xcode_dir_link
    at getPathFromSymlink$ (C:\Users\BMXDDT005072\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-xcode\lib\xcode.js:79:9)
    at tryCatch (C:\Users\BMXDDT005072\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\BMXDDT005072\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\BMXDDT005072\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\BMXDDT005072\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
```
## Environment

* Appium version: 1.0.2-beta.2
* Desktop OS/version used to run Appium:Windows 10, Visual Studio 2015
* Mobile version: IOS 10.3.1
* Real device

**Comment by imurchie** [comment]
Do you have Xcode installed?

**Comment by SergioParissi** [comment]
No, i tried to make it in Windows 10

**Comment by imurchie** [comment]
That will not work, unfortunately. Currently the only way to run iOS tests is to have the Appium server on Mac machine as it depends on Xcode.
