### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0xb4 in position 193: invalid start byte

### ISSUE THREAD

**Issue by melissalu** [appium/appium#8534]
I try to run android test download from  https://github.com/appium/python-client  ,I got the error below,can not connect to  webdriver

======================================================================
ERROR: test_update_settings (__main__.AppiumTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "appium_tests.py", line 37, in setUp
    self.driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)
  File "build/bdist.macosx-10.12-intel/egg/appium/webdriver/webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 92, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 179, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 234, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 408, in execute
    return self._request(command_info[0], url, body=data)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 490, in _request
    body = data.decode('utf-8').replace('\x00', '').strip()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xb4 in position 193: invalid start byte

----------------------------------------------------------------------

**Comment by mykola-mokhnach** [comment]
It looks like there is some corrupted string in capabilities, that you pass to initialise the driver.

**Comment by melissalu** [comment]
I debug step by step found request url http://localhost:4723/wd/hub  the response is error,if I chage localhost to my  ip http://10.9.240.102: 4723/wd/hub,then this is  no problem,I do not no why

**Comment by doraISzxy** [comment]
I have the exactly same problem.
for i changed my IE internet with local proxy using fiddler, and i didn't open fiddler.
there are 2 ways to fix it:
1. you can change the local area internet back, removing the localhost.
2. just  open the fiddler
