### ISSUE TITLE
Touchaction is not working

### ISSUE THREAD

**Issue by lehungcuong** [appium/appium#8540]
## The problem

When I use **longpress** action in TouchAction.class in second time, this action has been done but after that I got log `[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":7,"value":"TouchEvent element does not exist."}`. I set try catch and pass this case. But
in other case, I use longpress many times in a screen, after that I move to other screen and use longpress in this screen, `org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters.`

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable): 1.5
* Desktop OS/version used to run Appium: 10.12.4
* Node.js version (unless using Appium.app|exe):7.10.0
* Mobile platform/version under test:Android 5.1.1
* Real device or emulator/simulator: Real device (HTC One)
* Appium CLI or Appium.app|exe: Appium CLI

##Appium log
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:getLocation","params":{"elementId":"32"}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: getLocation
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":{"x":815,"y":1614}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:getSize","params":{"elementId":"32"}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: getSize
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":{"width":250,"height":57}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:getLocation","params":{"elementId":"38"}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: getLocation
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":{"x":815,"y":1614}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:getSize","params":{"elementId":"38"}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: getSize
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":{"width":250,"height":57}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:touchDown","params":{"elementId":"32","x":940,"y":1642.5}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: touchDown
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Performing TouchDown using element? true x: 940, y: 1642
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":true}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:touchUp","params":{"x":940,"y":1642.5}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: touchUp
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Display bounds: [0,0][1080,1920]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Performing TouchUp using element? false x: 940, y: 1642
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":true}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:touchLongClick","params":{"elementId":"38","x":940,"y":1642.5,"duration":1000}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: touchLongClick
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":7,"value":"TouchEvent element does not exist."}
org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1.47 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'cuong.local', ip: 'fe80:0:0:0:86c:4d1a:e049:87c9%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.4', java.version: '1.8.0_131'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{appPackage=com.zing.zalo, networkConnectionEnabled=true, noReset=true, warnings={}, databaseEnabled=false, deviceName=MB339W906918, platform=LINUX, appActivity=ui.ZaloLauncherActivity, desired={appPackage=com.zing.zalo, appActivity=ui.ZaloLauncherActivity, noReset=true, platformVersion=4.4, browserName=, unicodeKeyboard=true, platformName=Android, deviceName=Android, resetKeyboard=true}, platformVersion=5.1.1, webStorageEnabled=false, locationContextEnabled=false, takesScreenshot=true, browserName=, javascriptEnabled=true, unicodeKeyboard=true, platformName=Android, resetKeyboard=true}]
Session ID: 16770023-743d-4a66-bd75-270d7a530ad6
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:167)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:671)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at io.appium.java_client.PerformsTouchActions.performTouchAction(PerformsTouchActions.java:39)
	at io.appium.java_client.TouchAction.perform(TouchAction.java:322)
	at zalo.uitest.helper.ZaloAbstractHelper.longPress(ZaloAbstractHelper.java:652)
	at zalo.uitest.screen.ChatScreen.removeAllMemberOfGroup(ChatScreen.java:1074)
	at android.ContactTest.test10_leave_group_by_longPress(ContactTest.java:159)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)

## Code To Reproduce Issue [ Good To Have ]

helper.longPress(screen.contactTabScreen().listGroupChat.get(1));

**Comment by mykola-mokhnach** [comment]
Please attach full Appium log

**Comment by lehungcuong** [comment]
@mykola-mokhnach I've just updated comment

**Comment by mykola-mokhnach** [comment]
what is being done in helper.longPress ?

**Comment by lehungcuong** [comment]
It pop-up options, after that, it show appium log "TouchEvent element does not exist" and call teardown, not run next method

**Comment by mykola-mokhnach** [comment]
can you show the code?
The error says you are trying to do some action on an element, which does not exist on the screen anymore, which is quite possible if the actions chain is incorrect.

**Comment by lehungcuong** [comment]
##longpress
protected io.appium.java_client.TouchAction touchAction;
public void longPress(MobileElement element) {
        touchAction.longPress(element).perform();
    }
## I longPress to show options to delete some element in a list elements
I sure this element is available in this screen. you can try longPress some times in a screen, this issue will reprocedure.

**Comment by mykola-mokhnach** [comment]
what if you pass element locator instead of element instance there and replace

```
touchAction.longPress(element).perform();
```

with 

```
longPress(driver.findElement(locator)).perform();
```

**Comment by amedvedjev** [comment]
i also had some issues with older appium version (1.6.4) but with 1.6.5 - no issue.
@lehungcuong 
you can try also:
```
new TouchAction((MobileDriver) driver).press(el).waitAction(Duration.ofMillis(1000)).release().perform();
```

**Comment by lehungcuong** [comment]
@amedvedjev  thanks a lot. It worked!
