### ISSUE TITLE
 Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: 'java -version' failed. Error: Command failed: C:\\Windows\\system32\\cmd.exe /s /c \"java -version\"\n'java' 锟斤拷锟斤拷锟节诧拷锟斤拷锟解部锟斤拷锟筋，也锟斤拷锟角匡拷锟斤拷锟叫的筹拷锟斤拷\r\n锟斤拷锟斤拷锟斤拷锟斤拷锟侥硷拷锟斤拷\r\n)"

### ISSUE THREAD

**Issue by azurewer** [appium/appium#8562]
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: A new session could not be created. (Original error: 'java -version' failed. Error: Command failed: C:\Windows\system32\cmd.exe /s /c "java -version"
'java' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 246 milliseconds
Build info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:02:37'
System info: host: 'az', ip: '192.168.33.1', os.name: 'Windows 8', os.arch: 'amd64', os.version: '6.2', java.version: '1.7.0_17'
Driver info: io.appium.java_client.android.AndroidDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:27)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:240)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:126)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:153)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:22)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:202)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:50)
	at com.mooctest.Main.initAppiumTest(Main.java:74)
	at com.mooctest.Main.start(Main.java:79)
	at com.mooctest.Main.main(Main.java:85)

Is there are something wrong in my jdk? while i test the cmd command "java -version", which works well! 
this is really trouble me , please help!!

**Comment by mykola-mokhnach** [comment]
Please fill out the issue reporting template. It is important to have the log and environment info

**Comment by dpgraham** [comment]
Closing. Will re-open if issue template filled out.
