### ISSUE TITLE
xcodebuild exited with code '70' and signal 'null'

### ISSUE THREAD

**Issue by Automation-Test** [appium/appium#8572]
## The problem

iOS App installed and getting an error message [XCUITest] xcodebuild exited with code '70' and signal 'null'

## Environment

* Appium version 1.6.5 Beta
* XCODE - 8.3.2
* Mobile platform/version under test: Real Devices 
* Real device : iPhone 6S

## Details

[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Users/QA/.npm-packages/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=81e1a267c01927decdd9faadda9ad51f5375d1f7 -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.3' in directory '/Users/QA/.npm-packages/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will not be logged
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] xcodebuild exited with code '70' and signal 'null'
[debug] [BaseDriver] Event 'wdaStartFailed' logged at 1496174962508 (16:09:22 GMT-0400 (EDT))
[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70
[debug] [XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down iproxy process (pid 24487)
[debug] [XCUITest] iproxy exited with code 'null'
[debug] [XCUITest] Removing WDA application from device
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1496174972714 (16:09:32 GMT-0400 (EDT))
[XCUITest] Using WDA path: '/Users/QA/.npm-packages/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Users/QA/.npm-packages/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Users/QA/.npm-packages/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=81e1a267c01927decdd9faadda9ad51f5375d1f7 -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.3' in directory '/Users/qa/.npm-packages/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will not be logged
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] xcodebuild exited with code '70' and signal 'null'
[debug] [BaseDriver] Event 'wdaStartFailed' logged at 1496174979216 (16:09:39 GMT-0400 (EDT))
[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70
[debug] [XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down iproxy process (pid 24517)
[debug] [XCUITest] iproxy exited with code 'null'
[debug] [XCUITest] Removing WDA application from device
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:386:15)
    at tryCatch (/Users/QA/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/QA/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/QA/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/QA/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:386:15)
    at tryCatch (/Users/QA/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/QA/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/QA/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/QA/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:109:7)
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:386:15)
    at tryCatch (/Users/QA/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/QA/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/QA/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/QA/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:109:7)
[HTTP] <-- POST /wd/hub/session 500 42064 ms - 230 
[HTTP] --> POST /wd/hub/session {"capabilities":[{"desiredCapabilities":{"app":"/Users/QA/Downloads/Spoke.app","xcodeConfigfile":"/Users/QA/WebDriverAgentRunner/WebDriverAgentRunner/Config.xcconfig","appiumVersion":"1.6.5 beta","platformVersion":"10.3.1","automationName":"XCuiTest","bundleId":"com.Spoke.iOS","platformName":"iOS","udid":"81e1a267c01927decdd9faadda9ad51f5375d1f7","deviceName":"iPhone 6s","launchTimeout":8000}},{"requiredCapabilities":{}}]}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [null,null,[{"desiredCapabilities":{"app":"/Users/QA/Downloads/Spoke.app","xcodeConfigfile":"/Users/QA/WebDriverAgentRunner/WebDriverAgentRunner/Config.xcconfig","appiumVersion":"1.6.5 beta","platformVersion":"10.3.1","automationName":"XCuiTest","bundleId":"com.Spoke.iOS","platformName":"iOS","udid":"81e1a267c01927decdd9faadda9ad51f5375d1f7","deviceName":"iPhone 6s","launchTimeout":8000}},{"requiredCapabilities":{}}]]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1496174989452 (16:09:49 GMT-0400 (EDT))
[MJSONWP] Encountered internal error running command: Error: You must include a platformName capability
    at AppiumDriver.getDriverForCaps (../../lib/appium.js:44:13)
    at AppiumDriver.createSession$ (../../lib/appium.js:157:28)
    at tryCatch (/Users/QA/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/QA/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/QA/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/Users/QA/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/Users/QA/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at F (/Users/QA/.npm-packages/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/Users/QA/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/Users/QA/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/Users/QA/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at AppiumDriver.createSession (../../lib/appium.js:183:31)
    at ../../../lib/basedriver/driver.js:207:24
    at tryCatcher (/Users/QA/.npm-packages/lib/node_modules/appium/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/QA/.npm-packages/lib/node_modules/appium/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/Users/QA/.npm-packages/lib/node_modules/appium/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromiseAtPostResolution (/Users/QA/.npm-packages/lib/node_modules/appium/node_modules/bluebird/js/main/promise.js:248:10)
    at Async._drainQueue (/Users/QA/.npm-packages/lib/node_modules/appium/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/Users/QA/.npm-packages/lib/node_modules/appium/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/Users/QA/.npm-packages/lib/node_modules/appium/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
[HTTP] <-- POST /wd/hub/session 500 5 ms - 179

**Comment by imurchie** [comment]
Can you try building using:
```
cd /Users/qa/.npm-packages/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent

xcodebuild build-for-testing test-without-building -project /Users/QA/.npm-packages/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=81e1a267c01927decdd9faadda9ad51f5375d1f7 -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.3
```

**Comment by Automation-Test** [comment]
Thanks for quick responses , I got an error message Signing Identity:     "iPhone Developer: XXXX@XX.com (YHWQ2WWU2D)"



    /usr/bin/codesign --force --sign BD67698BDCD73FA85004DBE1086FE9Ass3021D7 --timestamp=none /Users/QA/.npm-packages/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/DerivedData/WebDriverAgent/Build/Products/Debug-iphoneos/WebDriverAgentLib.framework



=== BUILD TARGET WebDriverAgentRunner OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===



Check dependencies

No profiles for 'io.Appium.WebDriverAgentRunner' were found:  Xcode couldn't find a provisioning profile matching 'io.Appium.WebDriverAgentRunner'.

Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.3'

No profiles for 'io.Appium.WebDriverAgentRunner' were found:  Xcode couldn't find a provisioning profile matching 'io.Appium.WebDriverAgentRunner'.

Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.3'

No profiles for 'io.Appium.WebDriverAgentRunner' were found:  Xcode couldn't find a provisioning profile matching 'io.Appium.WebDriverAgentRunner'.

Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.3'

Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.3'



** TEST BUILD FAILED **





The following build commands failed:

Check dependencies

(1 failure)

xcodebuild: error: Failed to build project WebDriverAgent with scheme WebDriverAgentRunner.

Reason: Validation for test run specification failed: UITargetAppPath should be provided

QA7:WebDriverAgent QA$

**Comment by imurchie** [comment]
So this is a signing issue. You need to set things up so the system knows how to sign the WebDriverAgentRunner application, which is needed to automate your application. 

Please see https://github.com/appium/appium/blob/master/docs/en/appium-setup/real-devices-ios.md

**Comment by Automation-Test** [comment]
I followed the steps : error: could not read data from '/Users/QA/.npm-packages/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/Info.plist': The file “Info.plist” couldn’t be opened because there is no such file.

**Comment by mykola-mokhnach** [comment]
Open the /Users/QA/.npm-packages/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent project in Xcode, clean all caches and try to build and deploy WebDriverAgentRunner from there.

**Comment by Automation-Test** [comment]
/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Routing/FBWebServer.m:16:9: 'FBErrorBuilder.h' file not found

**Comment by Automation-Test** [comment]
/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Routing/FBWebServer.m:12:9: 'RoutingHTTPServer/RoutingConnection.h' file not found

**Comment by Automation-Test** [comment]
2017-05-31 17:19:09.999 xcodebuild[44916:1546779] Error Domain=IDETestOperationsObserverErrorDomain Code=4 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/DerivedData/WebDriverAgent/Logs/Test/789077EA-6C98-4A40-AB0E-5CC3DD334494/Session-WebDriverAgentRunner-2017-05-31_171909-QKaMpe.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/DerivedData/WebDriverAgent/Logs/Test/789077EA-6C98-4A40-AB0E-5CC3DD334494/Session-WebDriverAgentRunner-2017-05-31_171909-QKaMpe.log}

Testing failed:
	'RoutingHTTPServer/RoutingConnection.h' file not found
** TEST FAILED **

**Comment by Automation-Test** [comment]
Beginning test session WebDriverAgentRunner-FF534DA5-1C70-4DB2-8D5B-0A58020B28DB at 2017-05-31 17:19:09.319 with Xcode 8E2002 on target <DVTiOSDevice: 0x7f8e69b07e70> {
                deviceSerialNumber:         C6KRK2RZGRXR
                identifier:                 81e1a267c01927decdd9faadda9ad51f5375d1f7
                deviceClass:                iPhone
                deviceName:                 iPhone 6s
                deviceIdentifier:           81e1a267c01927decdd9faadda9ad51f5375d1f7
                productVersion:             10.3.2
                buildVersion:               14F89
                deviceSoftwareVersion:      10.3.2 (14F89)
                deviceArchitecture:         arm64
                deviceTotalCapacity:        12301361152
                deviceAvailableCapacity:    7212601344
                deviceIsTransient:          NO
                ignored:                    NO
                deviceIsBusy:               NO
                deviceIsActivated:          YES
                deviceActivationState:      Activated
                isPasscodeLocked:           NO
                deviceType:                 <DVTDeviceType:0x7f8e6959e000 Xcode.DeviceType.iPhone>
                supportedDeviceFamilies:    (
    1
)
                applications:              (null)
                provisioningProfiles:      (null)
                activityProgress:          -2
                activityTitle:
                hasInternalSupport:        NO
                isSupportedOS:             YES
                developerDiskMountError:   (null)
(null)
        bootArgs:                  <unavailable>
                } (10.3.2 (14F89))
17:19:09.320 xcodebuild[44916:1546779]  /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild
-project
WebDriverAgent.xcodeproj
-scheme
WebDriverAgentRunner
-destination
id=81e1a267c01927decdd9faadda9ad51f5375d1f7
test
17:19:09.320 xcodebuild[44916:1546779] Launching with Xcode.IDEFoundation.Launcher.PosixSpawn
17:19:09.325 xcodebuild[44916:1546780] Connecting to mobile device: 81e1a267c01927decdd9faadda9ad51f5375d1f7
17:19:09.327 xcodebuild[44916:1546780] Starting session with mobile device
17:19:09.349 xcodebuild[44916:1546780] Starting test manager service on mobile device.
17:19:09.361 xcodebuild[44916:1546832] Received connection for test runner session
17:19:09.361 xcodebuild[44916:1546832] Listening for proxy connection request from the test bundle
17:19:09.362 xcodebuild[44916:1546832] Initiating session with identifier: FF534DA5-1C70-4DB2-8D5B-0A58020B28DB
<pium-xcuitest-driver/WebDriverAgent/DerivedData/WebDriverAgent/Logs/Test/789077EA-6C98-4A40-AB0E-5CC3DD334494/Session-WebDriverAgentRunner-2017-05-31_171909-QKaMpe.log" 52L, 2855C
