### ISSUE TITLE
[XCUITest] Error: Unknown device or simulator UDID: '**************76c7f5a843a05e183a'

### ISSUE THREAD

**Issue by rkn411** [appium/appium#8574]
BaseDriver] Session created with session id: eedc34a4-7131-4102-bb55-3e1415a9d51d
[debug] [XCUITest] Xcode version set to '8.3.2' (tools v8.3.0.0.1.1490382677)
[debug] [XCUITest] iOS SDK Version set to '10.3'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1496138868715 (15:37:48 GMT+0530 (IST))
**[XCUITest] **The 'i**device_id' program is not installed. If you are running a real device test it is necessary. Install with 'brew install libimobiledevice --HEAD'
[debug] [XCUITest] Available devices:** 
[XCUITest] Error: Unknown device or simulator UDID: 'f*************176c7f5a843a05e183a'
    at XCUITestDriver.determineDevice$ (../../lib/driver.js:604:17)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: Unknown device or simulator UDID: 'fc96ef28f6d5956071cda176c7f5a843a05e183a'
    at XCUITestDriver.determineDevice$ (../../lib/driver.js:604:17)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[MJSONWP] Encountered internal error running command: Error: Unknown device or simulator UDID: 'fc96ef28f6d5956071cda176c7f5a843a05e183a'
    at XCUITestDriver.determineDevice$ (../../lib/driver.js:604:17)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[HTTP] <-- POST /wd/hub/session 500 3677 ms - 213 
[Utils] Attempting to create /Users/Logic/Desktop/AppiumiOS10/test-output/Default suite/Default test.xml
[Utils]   Directory /Users/Logic/Desktop/AppiumiOS10/test-output/Default suite exists: true
FAILED: install
## Environment

* Appium version (1.6.5) that exhibits the issue:
*
* Desktop OS/version used to run Appium:10.12.1
* Node.js version (unless using Appium.app|exe):6.2.1
* Mobile platform/version under test:10.3.2
* Real device or emulator/simulator:real device
* Appium CLI or Appium.app|exe:Appium CLI

## Details

when i try to launch or install app by starting server programmatically it throwing error 
XCUITest] The 'idevice_id' program is not installed. If you are running a real device test it is necessary. Install with 'brew install libimobiledevice --HEAD'
[debug] [XCUITest] Available devices: 
[XCUITest] Error: Unknown device or simulator UDID: 'fc96*******************a843a05e183a'

## Link to Appium logs

package com.NativeDemo.com;

import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;

import org.apache.commons.exec.CommandLine;
import org.apache.commons.exec.DefaultExecuteResultHandler;
import org.apache.commons.exec.DefaultExecutor;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.testng.annotations.Test;

import io.appium.java_client.ios.IOSDriver;

public class LaunchApp {
	IOSDriver Driver;
	public static void startServer() {
		 
		CommandLine command = new CommandLine("/usr/local/bin/node");
		command.addArgument("/usr/local/bin/appium",false);
		command.addArgument("--address", false);
		command.addArgument("127.0.0.1");
		command.addArgument("--port", false);
		command.addArgument("4723");
		command.addArgument("--bootstrap-port", false);
		command.addArgument("4724");
		
		DefaultExecuteResultHandler resultHandler = new DefaultExecuteResultHandler();
		DefaultExecutor executor = new DefaultExecutor();
		
		try {
			executor.execute(command, resultHandler);
			Thread.sleep(5000);
			System.out.println("Appium server started.");
		} catch (IOException e) {
			e.printStackTrace();
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		
	}
 
	public static void stopServer() {
		String[] command = {"/usr/bin/killall", "-KILL", "node"};
		try {
			Runtime.getRuntime().exec(command);
			System.out.println("Appium server stopped.");
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
	@Test
	public void install() throws IOException, Exception
	{
		startServer();
		
		Thread.sleep(120000);
		File apkurl=new File("/Users/Logic/Desktop/webdriveragentp12/WebDriverAgentRunner 2017-05-25 16-19-12/WebDriverAgentRunner.ipa");
		//File apkurl=new  @File("/Users/Logic/Downloads/***************.ipa");
	DesiredCapabilities caps = new DesiredCapabilities();
	caps.setCapability("deviceName", "reddi's iPhone");
	//caps.setCapability("deviceName"," iPod");
	caps.setCapability("platformName", "iOS");
	caps.setCapability("automationName", "XCUITest");
	caps.setCapability("platformVersion", "10.3.2");
	//iphone5s
	//caps.setCapability("udid","");
	//my device
	caps.setCapability("udid","0**************************");
	//caps.setCapability("udid","e");
	caps.setCapability("app",apkurl.getAbsolutePath());
	//caps.setCapability("bundleid","com.**********");
	caps.setCapability("bundleid","com.*********");
	Driver = new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"), caps);
	Thread.sleep(12000);
	Driver.closeApp();
	stopServer();
}
}
@jlipps @imurchie

**Comment by rkn411** [comment]
Environment path is set in eclipse
path=/usr/local/Cellar/libimobiledevice/HEAD-9df4e69/bin


done -Install with 'brew install libimobiledevice --HEAD'
no luck

**Comment by mykola-mokhnach** [comment]
The corresponding variable is called **PATH** and not **path**. Also it should not be overridden. One should simple add /usr/local/bin there:
PATH=$PATH:/usr/local/bin

**Comment by rkn411** [comment]
thanks for help issue resolved but again new error
[Xcode] Finding XcodePath by symlink because Error: Command 'xcode-select' not found. Is it installed?
[Xcode] Could not find path to Xcode by symlinks located in /var/db/xcode_select_link, or /usr/share/xcode-select/xcode_dir_link
[debug] [XCUITest] Error: Could not find path to Xcode by symlinks located in /var/db/xcode_select_link, or /usr/share/xcode-select/xcode_dir_link
    at getPathFromSymlink$ (../../lib/xcode.js:79:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: Could not find path to Xcode by symlinks located in /var/db/xcode_select_link, or /usr/share/xcode-select/xcode_dir_link
    at getPathFromSymlink$ (../../lib/xcode.js:79:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[XCUITest] Error: Could not determine Xcode version: Could not find path to Xcode by symlinks located in /var/db/xcode_select_link, or /usr/share/xcode-select/xcode_dir_link
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at getAndCheckXcodeVersion$ (../../lib/utils.js:52:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: Could not determine Xcode version: Could not find path to Xcode by symlinks located in /var/db/xcode_select_link, or /usr/share/xcode-select/xcode_dir_link
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at getAndCheckXcodeVersion$ (../../lib/utils.js:52:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[XCUITest] Error: Could not determine Xcode version: Could not find path to Xcode by symlinks located in /var/db/xcode_select_link, or /usr/share/xcode-select/xcode_dir_link
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at getAndCheckXcodeVersion$ (../../lib/utils.js:52:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: Could not determine Xcode version: Could not find path to Xcode by symlinks located in /var/db/xcode_select_link, or /usr/share/xcode-select/xcode_dir_link
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at getAndCheckXcodeVersion$ (../../lib/utils.js:52:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on. @mykola-mokhnach

**Comment by rkn411** [comment]
issue related to same error 
https://github.com/appium/appium/issues/7134
@jlipps @mykola-mokhnach

**Comment by mykola-mokhnach** [comment]
Please use Appium forum to ask questions. This is the place for issue.

**Comment by rkn411** [comment]
[Xcode] Finding XcodePath by symlink because Error: Command 'xcode-select' not found. Is it installed?
[debug] [XCUITest] Xcode version set to '8.3.2' 
[XCUITest] Error: Could not determine iOS SDK version: Command 'xcrun' not found. Is it installed?


.
it showing Xcode but y i m  getting error

**Comment by imurchie** [comment]
Do you have the command line tools installed?

**Comment by rkn411** [comment]
Last login: Thu Jun  1 09:16:51 on ttys000
DevRabbit-MAC:~ DevRabbit$ which command line tools
/usr/bin/command
DevRabbit-MAC:~ DevRabbit$ 
yes i had it working fine with manually start and stop server i m facing issues while launching through programmatically

**Comment by rkn411** [comment]
Appium server started.
[Utils] Attempting to create /Users/Logic/Desktop/AppiumiOS10/test-output/Default suite/Default test.xml
[Utils]   Directory /Users/Logic/Desktop/AppiumiOS10/test-output/Default suite exists: true
FAILED: install
org.openqa.selenium.WebDriverException: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:4723 [/127.0.0.1] failed: Connection refused
recent issues

**Comment by keshavwy** [comment]
@rkn411 @mykola-mokhnach  I'm still facing this issue: [Xcode] Finding XcodePath by symlink because Error: Command 'xcode-select' not found. Is it installed?  Please help me.

Xcode:8.3.3
Appium version:1.7.0
iOS:10.3.3

**Comment by mykola-mokhnach** [comment]
Make sure both Xcode and developer tools are properly installed on the machine

**Comment by keshavwy** [comment]
I have checked that and I am not seeing any problem in that. What else can I try from my end?
