### ISSUE TITLE
[XCUITest] Error: Could not determine iOS SDK version: Command 'xcrun' not found. Is it installed?

### ISSUE THREAD

**Issue by rkn411** [appium/appium#8577]
@jlipps @mykola-mokhnach @imurchie 
Appium server started.
[Appium] Welcome to Appium v1.6.5
[Appium] Non-default server args:
[Appium]   address: 127.0.0.1
[Appium] Appium REST http interface listener started on 127.0.0.1:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/Logic/Desktop/webdriveragentp12/WebDriverAgentRunner 2017-05-25 16-19-12/WebDriverAgentRunner.ipa","platformVersion":"10.3.2","automationName":"XCUITest","bundleid":"com.DevRabbit.LIC","platformName":"iOS","udid":"8***********d170f4446f7c4159469d","deviceName":"iPhone"},"requiredCapabilities":{},"capabilities":{"desiredCapabilities":{"app":"/Users/Logic/Desktop/webdriveragentp12/WebDriverAgentRunner 2017-05-25 16-19-12/WebDriverAgentRunner.ipa","platformVersion":"10.3.2","automationName":"XCUITest","bundleid":"com.DevRabbit.LIC","platformName":"iOS","udid":"8*************446f7c4159469d","deviceName":"iPhone"},"requiredCapabilities":{},"alwaysMatch":{"platformName":"iOS"},"firstMatch":[]}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/Logic/Desktop/webdriveragentp12/WebDriverAgentRunner 2017-05-25 16-19-12/WebDriverAgentRunner.ipa","platformVersion":"10.3.2","automationName":"XCUITest","bundleid":"com.DevRabbit.LIC","platformName":"iOS","udid":"*************70f4446f7c4159469d","deviceName":"iPhone"},{},{"desiredCapabilities":{"app":"/Users/Logic/Desktop/webdriveragentp12/WebDriverAgentRunner 2017-05-25 16-19-12/WebDriverAgentRunner.ipa","platformVersion":"10.3.2","automationName":"XCUITest","bundleid":"com.DevRabbit.LIC","platformName":"iOS","udid":"8************6f7c4159469d","deviceName":"iPhone"},"requiredCapabilities":{},"alwaysMatch":{"platformName":"iOS"},"firstMatch":[]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1496220858660 (14:24:18 GMT+0530 (IST))
[Appium] Creating new XCUITestDriver (v2.30.0) session
[Appium] Capabilities:
[Appium]   app: '/Users/Logic/Desktop/webdriveragentp12/WebDriverAgentRunner 2017-05-25 16-19-12/WebDriverAgentRunner.ipa'
[Appium]   platformVersion: '10.3.2'
[Appium]   automationName: 'XCUITest'
[Appium]   bundleid: 'co**********LIC'
[Appium]   platformName: 'iOS'
[Appium]   udid: '835*****************46f7c4159469d'
[Appium]   deviceName: 'iPhone'
[debug] [XCUITest] XCUITestDriver version: 2.30.0
[BaseDriver] The following capabilities were provided, but are not recognized by appium: bundleid.
[BaseDriver] Session created with session id: 0fdde53f-e665-4789-8a33-274cee8a537c
[Xcode] Finding XcodePath by symlink because Error: Command 'xcode-select' not found. Is it installed?
[debug] [XCUITest] Xcode version set to '8.3.2' 
[XCUITest] Error: Could not determine iOS SDK version: Command 'xcrun' not found. Is it installed?
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at getAndCheckIosSdkVersion$ (../../lib/utils.js:75:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: Could not determine iOS SDK version: Command 'xcrun' not found. Is it installed?
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at getAndCheckIosSdkVersion$ (../../lib/utils.js:75:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[XCUITest] Error: Could not determine iOS SDK version: Command 'xcrun' not found. Is it installed?
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at getAndCheckIosSdkVersion$ (../../lib/utils.js:75:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: Could not determine iOS SDK version: Command 'xcrun' not found. Is it installed?
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at getAndCheckIosSdkVersion$ (../../lib/utils.js:75:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[MJSONWP] Encountered internal error running command: Error: Could not determine iOS SDK version: Command 'xcrun' not found. Is it installed?
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at getAndCheckIosSdkVersion$ (../../lib/utils.js:75:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[HTTP] <-- POST /wd/hub/session 500 286 ms - 217 
[Utils] Attempting to create /Users/Logic/Desktop/AppiumiOS10/test-output/Default suite/Default test.xml
[Utils]   Directory /Users/Logic/Desktop/AppiumiOS10/test-output/Default suite exists: true

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.5
*Desktop OS/version used to run Appium:10.12.1
*Node.js version (unless using Appium.app|exe):6.2.1
*Mobile platform/version under test:10.3.2
Real device or emulator/simulator:real device
Appium CLI or Appium.app|exe:Appium CLI

## Details

xcode version is set to 8.3.2

## Link to Appium logs

Xcode] Finding XcodePath by symlink because Error: Command 'xcode-select' not found. Is it installed?
[debug] [XCUITest] Xcode version set to '8.3.2' 
[XCUITest] Error: Could not determine iOS SDK version: Command 'xcrun' not found. Is it installed?
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at getAndCheckIosSdkVersion$ (../../lib/utils.js:75:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: Could not determine iOS SDK version: Command 'xcrun' not found. Is it installed?
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at getAndCheckIosSdkVersion$ (../../lib/utils.js:75:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[XCUITest] Error: Could not determine iOS SDK version: Command 'xcrun' not found. Is it installed?
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at getAndCheckIosSdkVersion$ (../../lib/utils.js:75:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: Could not determine iOS SDK version: Command 'xcrun' not found. Is it installed?
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at getAndCheckIosSdkVersion$ (../../lib/utils.js:75:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[MJSONWP] Encountered internal error running command: Error: Could not determine iOS SDK version: Command 'xcrun' not found. Is it installed?
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at getAndCheckIosSdkVersion$ (../../lib/utils.js:75:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[HTTP] <-- POST /wd/hub/session 500 286 ms - 217 
[Utils] Attempting to create /Users/Logic/Desktop/AppiumiOS10/test-output/Default suite/Default test.xml
[Utils]   Directory /Users/Logic/Desktop/AppiumiOS10/test-output/Default suite exists: true
FAILED: install
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not determine iOS SDK version: Command 'xcrun' not found. Is it installed? (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 604 milliseconds
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'DevRabbit-MAC.local', ip: '192.168.1.39', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.1', java.version: '1.8.0_73'
Driver info: driver.version: IOSDriver

## Code To Reproduce Issue [ Good To Have ]

package com.NativeDemo.com;

import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;

import org.apache.commons.exec.CommandLine;
import org.apache.commons.exec.DefaultExecuteResultHandler;
import org.apache.commons.exec.DefaultExecutor;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.testng.annotations.Test;

import io.appium.java_client.ios.IOSDriver;

public class LaunchApp {
IOSDriver Driver;
public static void startServer() {

	CommandLine command = new CommandLine("/usr/local/bin/node");
	command.addArgument("/usr/local/bin/appium",false);
	command.addArgument("--address", false);
	command.addArgument("127.0.0.1");
	command.addArgument("--port", false);
	command.addArgument("4723");
	command.addArgument("--bootstrap-port", false);
	command.addArgument("4724");
	
	DefaultExecuteResultHandler resultHandler = new DefaultExecuteResultHandler();
	DefaultExecutor executor = new DefaultExecutor();
	
	try {
		executor.execute(command, resultHandler);
		Thread.sleep(5000);
		System.out.println("Appium server started.");
	} catch (IOException e) {
		e.printStackTrace();
	} catch (InterruptedException e) {
		e.printStackTrace();
	}
	
}

public static void stopServer() {
	String[] command = {"/usr/bin/killall", "-KILL", "node"};
	try {
		Runtime.getRuntime().exec(command);
		System.out.println("Appium server stopped.");
	} catch (IOException e) {
		e.printStackTrace();
	}
}
@Test
public void install() throws IOException, Exception
{
	startServer();
	
	Thread.sleep(120000);
	File apkurl=new File("/Users/Logic/Desktop/webdriveragentp12/WebDriverAgentRunner 2017-05-25 16-19-12/WebDriverAgentRunner.ipa");
	//File apkurl=new  @File("/Users/Logic/Downloads/***************.ipa");
DesiredCapabilities caps = new DesiredCapabilities();
caps.setCapability("deviceName", "reddi's iPhone");
//caps.setCapability("deviceName"," iPod");
caps.setCapability("platformName", "iOS");
caps.setCapability("automationName", "XCUITest");
caps.setCapability("platformVersion", "10.3.2");
//iphone5s
//caps.setCapability("udid","");
//my device
caps.setCapability("udid","0**************************");
//caps.setCapability("udid","e");
caps.setCapability("app",apkurl.getAbsolutePath());
//caps.setCapability("bundleid","com.**********");
caps.setCapability("bundleid","com.*********");
Driver = new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"), caps);
Thread.sleep(12000);
Driver.closeApp();
stopServer();

**Comment by rkn411** [comment]
sudo /usr/bin/xcode-select -switch /Applications/Xcode.app/Contents/Developer-solved my issue


issue resolved Thanks

**Comment by rkn411** [comment]
getting new error
[TestNG] Running:
  /private/var/folders/lr/l90lmg_x3dzgc0dxlzwv0pyw0000gn/T/testng-eclipse--501268773/testng-customsuite.xml

Appium server started.
[Appium] Welcome to Appium v1.6.5
[Appium] Non-default server args:
[Appium]   address: 127.0.0.1
[Appium] Appium REST http interface listener started on 127.0.0.1:4723
[Utils] Attempting to create /Users/Logic/Desktop/AppiumiOS10/test-output/Default suite/Default test.xml
[Utils]   Directory /Users/Logic/Desktop/AppiumiOS10/test-output/Default suite exists: true
FAILED: install
org.openqa.selenium.WebDriverException: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:4723 [/127.0.0.1] failed: Connection refused
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'

**Comment by dpgraham** [comment]
Closing this for now. If you weren't able to fix it I'll re-open.

**Comment by sirajios** [comment]
Getting new error. 
**I'm using xcode 8.3 with ios 10.3 and appium server v1.6.5.**
Error : An unknown server-side error occurred while processing the command. Original error: Could not determine iOS SDK version: Command 'xcrun --sdk iphonesimulator --show-sdk-version' timed out after 15000ms

**My desired capabilities:** 
{
  "browserName": "Safari",
  "deviceName": "iPhone",
  "platformName": "iOS",
  "udid": "276180a71ec72********************",
  "platformVersion": "10.1.1",
  "app": "/Users/iexm01/Desktop/test.ipa",
  "automationName": "Appium",
  "bundleId": "{bundleId}",
  "noReset": false,
  "fullReset": true
}

When I start the seesion, i get the following error,
**[MJSONWP] Encountered internal error running command: Error: Could not determine iOS SDK version: Command 'xcrun --sdk iphonesimulator --show-sdk-version' timed out after 15000ms.**

Kindly help me get through this.
Thanks in advance.

**Comment by rkn411** [comment]
try this 
sudo /usr/bin/xcode-select -switch /Applications/Xcode.app/Contents/Developer-solved my issue
@sirajios

**Comment by keshavwy** [comment]
@rkn411 @sirajios I am also facing the same issue. I tried the above steps mentioned, but still, it is showing me the same issue. Any help?

**Comment by keshavwy** [comment]
@rkn411 @dpgraham 

Here is the appium logs: [Appium] Welcome to Appium v1.7.1
[Appium] Non-default server args:
[Appium]   address: 127.0.0.1
[Appium]   noReset: true
[Appium] Deprecated server args:
[Appium]   --no-reset => --default-capabilities '{"noReset":true}'
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   noReset: true
[Appium] Appium REST http interface listener started on 127.0.0.1:4723
AppiumServer Started
log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/webyog/Documents/workspace/NewtonApp/src/test/resources/app/Newton.app","platformVersion":"10.3","appiumVersion":"1.6","automationName":"XCUITest","bundleId":"com.cloudmagic.mail","platformName":"iOS","udid":"f253d52aba24834b9c2795ea0a7e95476d521042","deviceName":"iPhone"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/webyog/Documents/workspace/NewtonApp/src/test/resources/app/Newton.app","platformVersion":"10.3","appiumVersion":"1.6","automationName":"XCUITest","bundleId":"com.cloudmagic.mail","platformName":"iOS","udid":"f253d52aba24834b9c2795ea0a7e95476d521042","deviceName":"iPhone"},null,null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1507904567032 (19:52:47 GMT+0530 (IST))
[Appium] Creating new XCUITestDriver (v2.51.1) session
[Appium] Capabilities:
[Appium]   app: '/Users/webyog/Documents/workspace/NewtonApp/src/test/resources/app/Newton.app'
[Appium]   platformVersion: '10.3'
[Appium]   appiumVersion: '1.6'
[Appium]   automationName: 'XCUITest'
[Appium]   bundleId: 'com.cloudmagic.mail'
[Appium]   platformName: 'iOS'
[Appium]   udid: 'f253d52aba24834b9c2795ea0a7e95476d521042'
[Appium]   deviceName: 'iPhone'
[Appium]   noReset: true
[BaseDriver] The following capabilities were provided, but are not recognized by appium: appiumVersion.
[BaseDriver] Session created with session id: 208739e8-626b-4930-a99d-d7743c7e0263
[Xcode] Finding XcodePath by symlink because Error: Command 'xcode-select' not found. Is it installed?
[debug] [XCUITest] Xcode version set to '9.0' 
[XCUITest] Error: Could not determine iOS SDK version: Command 'xcrun' not found. Is it installed?
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at getAndCheckIosSdkVersion$ (../../lib/utils.js:74:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: Could not determine iOS SDK version: Command 'xcrun' not found. Is it installed?
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at getAndCheckIosSdkVersion$ (../../lib/utils.js:74:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[XCUITest] Error: Could not determine iOS SDK version: Command 'xcrun' not found. Is it installed?
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at getAndCheckIosSdkVersion$ (../../lib/utils.js:74:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: Could not determine iOS SDK version: Command 'xcrun' not found. Is it installed?
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at getAndCheckIosSdkVersion$ (../../lib/utils.js:74:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[MJSONWP] Encountered internal error running command: Error: Could not determine iOS SDK version: Command 'xcrun' not found. Is it installed?
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at getAndCheckIosSdkVersion$ (../../lib/utils.js:74:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by Kedar-27** [comment]
Try installing command line tools from https://developer.apple.com/download/more/ 
This solved my error
