### ISSUE TITLE
Appium error: error: Unhandled error: Error: ENOENT, no such file or directory 

### ISSUE THREAD

**Issue by ravaughan** [appium/appium#8588]
## The problem

When I attempt to run an automated android cucumber test using appium on MacOs Sierra I see the following error in appium

error: Unhandled error: Error: ENOENT, no such file or directory '/Applications/Appium.app/Contents/Resources/node_modules/appium/Users/richard.vaughan/Library/Android/sdk/build-tools'
    at Error (native)
    at Object.fs.readdirSync (fs.js:761:18)
    at exports.getDirectories (/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-adb/lib/helpers.js:100:18)
    at [object Object].ADB.checkSdkBinaryPresent (/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-adb/lib/adb.js:97:25)
    at [object Object].ADB.checkAdbPresent (/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-adb/lib/adb.js:134:8)
    at Function.ADB.createADB (/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-adb/lib/adb.js:73:7)
    at [object Object].androidCommon.initAdb (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/android/android-common.js:1083:9)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:607:21
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:246:17
    at iterate (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:146:13)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:157:25
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:248:21
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:612:34
    at [object Object].<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/android/android-common.js:1077:12)
    at [object Object].<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/android/android-common.js:1064:12)
    at ChildProcess.exithandler (child_process.js:742:7)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12) context: [POST /wd/hub/session {"desiredCapabilities":{"browserName":"","version":"","platform":"ANY","javascriptEnabled":true,"cssSelectorsEnabled":true,"takesScreenshot":true,"nativeEvents":false,"rotatable":false,"deviceName":"N]

## Environment

* I am using Appium 1.4.13

My current bash profile

if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

export ANDROID_HOME="Users/richard.vaughan/Library/Android/sdk"  
export PATH="${PATH}:/$ANDROID_HOME/platform-tools:/$ANDROID_HOME/tools:/$ANDROID_HOME/tools/bin"

I have tried adding a line with the build-tools folder but I still encountered the same error.

**Comment by mykola-mokhnach** [comment]
> export ANDROID_HOME="Users/richard.vaughan/Library/Android/sdk"
Leading slash is missing

Closed as non-Appium related

**Comment by ravaughan** [comment]
@mykola-mokhnach I don't understand, where is the slash missing? I'm new to mac this is all working well on my home pc but my new company uses mac

**Comment by ravaughan** [comment]
@mykola-mokhnach nevermind i figured it out.
