### ISSUE TITLE
appium version 1.6.5-Beta running multiple tests one after another 

### ISSUE THREAD

**Issue by skhanam** [appium/appium#8594]
appium version 1.6.5-Beta running multiple tests one after another 
TestNG
Node - v7.9.0
NPM - 4.2.0

I am having 2 tests within a  testsuite i am unable to run the test

 capabilities.setCapability(MobileCapabilityType.DEVICE_NAME,"emulator-5554");
        capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "6.0");
        capabilities.setCapability(MobileCapabilityType.APP,app);
 capabilities.setCapability("newCommandTimeout", 600);
        driver = new AndroidDriver<MobileElement>(new URL(URL_STRING), capabilities);
        driver.manage().timeouts().implicitlyWait(35, TimeUnit.SECONDS);

org.openqa.selenium.SessionNotCreatedException: A new session could not be created. Details: Problem getting session data for driver type AndroidDriver; does it implement 'get driverData'? (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.3.1', revision: '5234b325d5', time: '2017-03-10 09:10:29 +0000'
System info: host: 'localhost', ip: 'fe80:0:0:0:4d0:b07:d8a1:3238%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.5', java.version: '1.8.0_91'
Driver info: driver.version: AndroidDriver

**Comment by mykola-mokhnach** [comment]
Please attach full Appium log

**Comment by skhanam** [comment]
[HTTP] --> POST /wd/hub/session {"capabilities":[{"desiredCapabilities":{"app":"/Users/shabanakhanum/workspacepersonal/AwsAndroid/src/test/apps/app-quidco-sandbox-qa.apk","platformName":"Android","udid":"1215fcd81beb2f04","deviceName":"Samsung S6","platformVersion":"6.0"}},{"requiredCapabilities":{}}]}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [null,null,[{"desiredCapabilities":{"app":"/Users/shabanakhanum/workspacepersonal/AwsAndroid/src/test/apps/app-quidco-sandbox-qa.apk","platformName":"Android","udid":"1215fcd81beb2f04","deviceName":"Samsung S6","platformVersion":"6.0"}},{"requiredCapabilities":{}}]]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1496315294690 (13:08:14 GMT+0200 (CEST))
[MJSONWP] Encountered internal error running command: Error: You must include a platformName capability
    at AppiumDriver.getDriverForCaps (../../lib/appium.js:44:13)
    at AppiumDriver.createSession$ (../../lib/appium.js:157:28)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at F (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at AppiumDriver.createSession (../../lib/appium.js:183:31)
    at ../../../lib/basedriver/driver.js:207:24
    at tryCatcher (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromiseAtPostResolution (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/promise.js:248:10)
    at Async._drainQueue (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
[HTTP] <-- POST /wd/hub/session 500 4 ms - 179

**Comment by skhanam** [comment]
org.openqa.selenium.SessionNotCreatedException: A new session could not be created. Details: Problem getting session data for driver type AndroidDriver; does it implement 'get driverData'? (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.3.1', revision: '5234b325d5', time: '2017-03-10 09:10:29 +0000'
System info: host: 'localhost', ip: 'fe80:0:0:0:4d0:b07:d8a1:3238%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.5', java.version: '1.8.0_91'
Driver info: driver.version: AndroidDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:216)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:168)
	at io.appium.java_client.remote.AppiumProtocolHandShake.createSession(AppiumProtocolHandShake.java:161)
	at io.appium.java_client.remote.AppiumProtocolHandShake.createSession(AppiumProtocolHandShake.java:76)
	at io.appium.java_client.remote.AppiumCommandExecutor.doExecute(AppiumCommandExecutor.java:111)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:162)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:604)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:244)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:88)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:112)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:73)
	at com.msm.android.RegisterNewUserTest.setUpAppium(RegisterNewUserTest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:326)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)


Results :

Failed tests:   setUpAppium(com.msm.android.ExistingUserSignInTest): A new session could not be created. Details: Problem getting session data for driver type AndroidDriver; does it implement 'get driverData'? (WARNING: The server did not provide any stacktrace information)(..)

**Comment by skhanam** [comment]
here it is from appium 

[HTTP] <-- GET /wd/hub/session/d1435074-3b06-4e2a-825f-791cb572e3c0 200 4 ms - 1002 
[HTTP] --> POST /wd/hub/session/d1435074-3b06-4e2a-825f-791cb572e3c0/timeouts {"type":"implicit","ms":35000}
[debug] [MJSONWP] Calling AppiumDriver.timeouts() with args: ["implicit",35000,"d1435074-3b06-4e2a-825f-791cb572e3c0"]
[debug] [BaseDriver] Set implicit wait to 35000ms
[debug] [MJSONWP] Responding to client with driver.timeouts() result: null
[HTTP] <-- POST /wd/hub/session/d1435074-3b06-4e2a-825f-791cb572e3c0/timeouts 200 3 ms - 76 
[HTTP] --> POST /wd/hub/session {"capabilities":[{"desiredCapabilities":{"app":"/Users/shabanakhanum/workspacepersonal/AwsAndroid/src/test/apps/app-quidco-sandbox-qa.apk","platformName":"Android","deviceName":"emulator-5554","platformVersion":"6.0"}},{"requiredCapabilities":{}}],"desiredCapabilities":{"app":"/Users/shabanakhanum/workspacepersonal/AwsAndroid/src/test/apps/app-quidco-sandbox-qa.apk","platformName":"Android","deviceName":"emulator-5554","platformVersion":"6.0"},"requiredCapabilities":{}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/shabanakhanum/workspacepersonal/AwsAndroid/src/test/apps/app-quidco-sandbox-qa.apk","platformName":"Android","deviceName":"emulator-5554","platformVersion":"6.0"},{},[{"desiredCapabilities":{"app":"/Users/shabanakhanum/workspacepersonal/AwsAndroid/src/test/apps/app-quidco-sandbox-qa.apk","platformName":"Android","deviceName":"emulator-5554","platformVersion":"6.0"}},{"requiredCapabilities":{}}]]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1496326031659 (16:07:11 GMT+0200 (CEST))
[Appium] Creating new AndroidDriver (v1.20.0) session
[Appium] Capabilities:
[Appium]   app: '/Users/shabanakhanum/workspacepersonal/AwsAndroid/src/test/apps/app-quidco-sandbox-qa.apk'
[Appium]   platformName: 'Android'
[Appium]   deviceName: 'emulator-5554'
[Appium]   platformVersion: '6.0'
[HTTP] <-- POST /wd/hub/session 500 3 ms - 193 
[HTTP] --> POST /wd/hub/session {"capabilities":[{"desiredCapabilities":{"app":"/Users/shabanakhanum/workspacepersonal/AwsAndroid/src/test/apps/app-quidco-sandbox-qa.apk","platformName":"Android","deviceName":"emulator-5554","newCommandTimeout":600,"platformVersion":"6.0"}},{"requiredCapabilities":{}}],"desiredCapabilities":{"app":"/Users/shabanakhanum/workspacepersonal/AwsAndroid/src/test/apps/app-quidco-sandbox-qa.apk","platformName":"Android","deviceName":"emulator-5554","newCommandTimeout":600,"platformVersion":"6.0"},"requiredCapabilities":{}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/shabanakhanum/workspacepersonal/AwsAndroid/src/test/apps/app-quidco-sandbox-qa.apk","platformName":"Android","deviceName":"emulator-5554","newCommandTimeout":600,"platformVersion":"6.0"},{},[{"desiredCapabilities":{"app":"/Users/shabanakhanum/workspacepersonal/AwsAndroid/src/test/apps/app-quidco-sandbox-qa.apk","platformName":"Android","deviceName":"emulator-5554","newCommandTimeout":600,"platformVersion":"6.0"}},{"requiredCapabilities":{}}]]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1496326181931 (16:09:41 GMT+0200 (CEST))
[Appium] Creating new AndroidDriver (v1.20.0) session
[Appium] Capabilities:
[Appium]   app: '/Users/shabanakhanum/workspacepersonal/AwsAndroid/src/test/apps/app-quidco-sandbox-qa.apk'
[Appium]   platformName: 'Android'
[Appium]   deviceName: 'emulator-5554'
[Appium]   newCommandTimeout: 600
[Appium]   platformVersion: '6.0'
[HTTP] <-- POST /wd/hub/session 500 3 ms - 193

**Comment by SrinivasanTarget** [comment]
which version of java client being used here?

**Comment by jlipps** [comment]
closing due to inactivity
