### ISSUE TITLE
Appium 1.6.5 does not start iOS Simulator automatically

### ISSUE THREAD

**Issue by guilhotarras** [appium/appium#8605]
## The problem

After upgrading to Appium 1.6.5, iOS Simulator does not start automatically when I start my tests on iOS. As a consequence, I'm having this error on Appium logs:

[BaseDriver] Event 'newSessionRequested' logged at 1496668611002 (14:16:51 GMT+0100 (WEST))
[Appium] Creating new XCUITestDriver (v2.30.0) session
[Appium] Capabilities:
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '10.3'
[Appium]   deviceName: 'iPhone SE'
[Appium]   bundleId: 'com.becker.cpa.2017'
[Appium]   autoWebview: true
[Appium]   noReset: true
[Appium]   automationName: 'XCUITest'
[debug] [XCUITest] XCUITestDriver version: 2.30.0
[BaseDriver] Session created with session id: 01f08b5d-9794-4921-a61a-000ac07756bd
[debug] [XCUITest] Xcode version set to '8.3' (tools v8.3.2.0.1.1492020469)
[debug] [XCUITest] iOS SDK Version set to '10.3'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1496668611097 (14:16:51 GMT+0100 (WEST))
[iOSSim] Constructing iOS simulator for Xcode version 8.3 with udid '2ECA606B-F57D-4D18-AD3C-BEDE9261C4B3'
[XCUITest] Determining device to run tests on: udid: '2ECA606B-F57D-4D18-AD3C-BEDE9261C4B3', real device: false
[debug] [BaseDriver] Event 'appConfigured' logged at 1496668611219 (14:16:51 GMT+0100 (WEST))
[XCUITest] Error: App with bundle identifier 'com.becker.cpa.2017' unknown
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at XCUITestDriver.start$ (../../lib/driver.js:279:13)
    at tryCatch (/Users/beckerqa/Documents/CPA2017Mobile/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/beckerqa/Documents/CPA2017Mobile/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/beckerqa/Documents/CPA2017Mobile/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/beckerqa/Documents/CPA2017Mobile/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: App with bundle identifier 'com.becker.cpa.2017' unknown
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at XCUITestDriver.start$ (../../lib/driver.js:279:13)
    at tryCatch (/Users/beckerqa/Documents/CPA2017Mobile/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/beckerqa/Documents/CPA2017Mobile/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/beckerqa/Documents/CPA2017Mobile/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/beckerqa/Documents/CPA2017Mobile/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[XCUITest] Error: App with bundle identifier 'com.becker.cpa.2017' unknown
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at XCUITestDriver.start$ (../../lib/driver.js:279:13)
    at tryCatch (/Users/beckerqa/Documents/CPA2017Mobile/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/beckerqa/Documents/CPA2017Mobile/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/beckerqa/Documents/CPA2017Mobile/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/beckerqa/Documents/CPA2017Mobile/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: App with bundle identifier 'com.becker.cpa.2017' unknown
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at XCUITestDriver.start$ (../../lib/driver.js:279:13)
    at tryCatch (/Users/beckerqa/Documents/CPA2017Mobile/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/beckerqa/Documents/CPA2017Mobile/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/beckerqa/Documents/CPA2017Mobile/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/beckerqa/Documents/CPA2017Mobile/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[MJSONWP] Encountered internal error running command: Error: App with bundle identifier 'com.becker.cpa.2017' unknown
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at XCUITestDriver.start$ (../../lib/driver.js:279:13)
    at tryCatch (/Users/beckerqa/Documents/CPA2017Mobile/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/beckerqa/Documents/CPA2017Mobile/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/beckerqa/Documents/CPA2017Mobile/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/beckerqa/Documents/CPA2017Mobile/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[HTTP] <-- POST /wd/hub/session 500 305 ms - 193 

If I start the simulator manually, everything works.

## Environment

* Appium 1.6.5 (Node client)
* iOS Simulator
* XCode 8.3

**Comment by imurchie** [comment]
Thanks for the report. Yes, this is a bug. Working on it...

**Comment by guilhotarras** [comment]
Thanks ! When can we have the fix, and how can we install it ? 
Do we have to wait for the next appium release ? (1.6.6)

**Comment by imurchie** [comment]
No. Once I have it fixed it will be available in 1.6.6-beta.

**Comment by guilhotarras** [comment]
Great, please ping me when it's fixed. Thanks

**Comment by imurchie** [comment]
A fix is in the works: https://github.com/appium/appium-xcuitest-driver/pull/446

**Comment by imurchie** [comment]
The fix has been published in `appium-xcuitest-driver@2.30.2`. If you install the beta (`npm uninstall -g appium && npm install -g appium@beta`) you should get it.

There will be a log line saying the version of the XCUITest driver, and it needs to be _at least_ 2.30.2.

**Comment by guilhotarras** [comment]
After installing appium:

$npm uninstall appium
$npm install appium@beta

and then, starting the server, I am getting this error:

Guilherme-Saraiva:CPA2017Mobile beckerqa$ node_modules/.bin/appium
Error: Cannot find module 'pem'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/beckerqa/Documents/CPA2017Mobile/node_modules/appium-ios-driver/lib/server.js:9:28)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/beckerqa/Documents/CPA2017Mobile/node_modules/appium-ios-driver/build/index.js:23:18)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/beckerqa/Documents/CPA2017Mobile/node_modules/appium/build/lib/appium.js:39:24)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/beckerqa/Documents/CPA2017Mobile/node_modules/appium/build/lib/main.js:45:15)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3


What could it be ?
