### ISSUE TITLE
Android application installation fails by passing desired capability "automationName" = "uiautomator2"

### ISSUE THREAD

**Issue by benz-philip** [appium/appium#8610]
## The problem

Android application installation fails by setting desired capability "automationName" = "uiautomator2". But the installation happens and tests start executing if it is not set

## Environment

* Appium version (or git revision) that exhibits the issue: Appium v1.6.5
* Desktop OS/version used to run Appium: MAC
* Node.js version (unless using Appium.app|exe): Node v6.9.5
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real

## Details
Driver:
```java
                                 File androidApp = new File(apk_Path);
				d_cap = new DesiredCapabilities();
				d_cap.setCapability("platformName", platform_Name);
				d_cap.setCapability("platformVersion", android_platform_Version);
				d_cap.setCapability("deviceName", android_device_Name);
				d_cap.setCapability("appPackage", android_app_Package);
				d_cap.setCapability("appActivity", android_app_Activity);
				d_cap.setCapability("autoAcceptAlerts", true);
				d_cap.setCapability("autoGrantPermissions", true);
				d_cap.setCapability("app", androidApp.getAbsolutePath());
				d_cap.setCapability("device ID", android_deviceID);
				d_cap.setCapability("autoLaunch", false);
				d_cap.setCapability("clearSystemFiles", true);
					d_cap.setCapability("noReset", "true");
					d_cap.setCapability("fullReset", "false");
					d_cap.setCapability("automationName", "uiautomator2");
	
					driver = new AndroidDriver<MobileElement>(new URL("http://" + hubURL + ":" + hubPort + "/wd/hub"), d_cap);
```

-------------------------------------

Execution fails only when d_cap.setCapability("automationName", "uiautomator2"); is set 
But execution continues if the app is already present in the device.

## Log
```
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8200/wd/hub/session] with body: {"desiredCapabilities":{"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"appPackage":"XXXX","app":"/Users/benz/git/XXXX/./src/test/resources/apk/XXXX.apk","clearSystemFiles":true,"noReset":true,"deviceName":"Vibe_2","fullReset":false,"appActivity":"XXXX.ui.activity.SplashActivity","autoLaunch":false,"platformVersion":"7.","automationName":"uiautomator2","autoGrantPermissions":true,"device ID":"33002ad3cf212337","platformName":"Android","autoAcceptAlerts":true,"udid":"33002ad3cf212337"},"appPackage":"XXXX","app":"/Users/benz/git/XXXX/./src/test/resources/apk/XXXX.apk","clearSystemFiles":true,"noReset":true,"deviceName":"33002ad3cf212337","fullReset":false,"appActivity":"XXXX.ui.ac...
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"86871aa2-bce2-4463-a57b-ba05a044b8d8","status":0,"value":"Created Session"}
[UiAutomator2] UiAutomator2 did not start the activity we were waiting for, 'XXXX/XXXX.ui.activity.SplashActivity'. Starting it ourselves
[debug] [ADB] Device API level: 24
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/admin/Softwares/sdk/platform-tools/adb' with args: ["-P",5037,"-s","33002ad3cf212337","shell","am","start","-W","-n","XXXX/XXXX.ui.activity.SplashActivity","-S","-a","android.intent.action.MAIN","-c","android.intent.category.LAUNCHER","-f","0x10200000"]
[ADB] Error: Activity used to start app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at ADB.callee$0$0$ (../../../lib/tools/apk-utils.js:67:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: Activity used to start app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at ADB.callee$0$0$ (../../../lib/tools/apk-utils.js:67:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[ADB] Error: Error occured while starting App. Original error: Activity used to start app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at ADB.callee$0$0$ (../../../lib/tools/apk-utils.js:79:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: Error occured while starting App. Original error: Activity used to start app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at ADB.callee$0$0$ (../../../lib/tools/apk-utils.js:79:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [UiAutomator2] Deleting UiAutomator2 server session
```

**Comment by mykola-mokhnach** [comment]
The error says activity name you set as **appActivity**  capability value is incorrect. Try to change it and/or to set correct value to **appWaitActivity** capability.

**Comment by benz-philip** [comment]
appActivity value is correct. Application installation happens if i dont set - setCapability("automationName", "uiautomator2");

If i am setting automationName as uiautomator2, The test application installation is not happening
and it is throwing error:

[MJSONWP] Encountered internal error running command: Error: Error occured while starting App. Original error: Activity used to start app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity

even after setting appWaitActivity capability

**Comment by mykola-mokhnach** [comment]
For me ".SplashActivity" does not look like correct name for the main activity, but you must know better.

**Comment by benz-philip** [comment]
yes, it is correct. Let me explain..

The issue is app installation fails for fresh test run.

If I install the app manually and triggers the run without any capability change, the app launches and continue with the test. If the activity name is not correct, in this case also it should throw error, right?

Additional info: If i dont set 'automationName' capability as 'uiautomator2', For fresh trigger, the app installs before starting the test. But I need uiautomator2 support for triggering test in Android 7

Please suggest me what can be done if it is not a appium defect.

Please let me know i you need additional information.

**Comment by DonnaZh** [comment]
@benz-philip any progress on this problem? I have similar problem Appium failed to launch app with appActivity .SplashActivity

**Comment by benz-philip** [comment]
@DonnaZh : The issue is with the installation of application not launching the app. - mentioned in my very recent comment.

Now, i am installing the app using adb command and proceeding with my test.

**Comment by dpgraham** [comment]
@benz-philip What ADB command are you using to install the app?

The adb command Appium uses to install your app is 

```
["-P",5037,"-s","33002ad3cf212337","shell","am","start","-W","-n","XXXX/XXXX.ui.activity.SplashActivity","-S","-a","android.intent.action.MAIN","-c","android.intent.category.LAUNCHER","-f","0x10200000"]
```

**Comment by benz-philip** [comment]
@dpgraham When I run the code without having app installed in the mobile, i get error message which is mentioned in the incident log plus the below error -

[HTTP] <-- POST /wd/hub/session 500 14429 ms - 299 
[HTTP] --> POST /wd/hub/session {"capabilities":[{"desiredCapabilities":{"app":"/Users/benz/git/xxxx/./src/test/resources/apk/xxxx.apk","appPackage":"xxxx.xxxx","clearSystemFiles":true,"noReset":"true","deviceName":"Vibe_2","fullReset":"false","appActivity":"xxxx.xxxx.ui.activity.SplashActivity","autoLaunch":false,"platformVersion":"7.","automationName":"uiautomator2","autoGrantPermissions":true,"device ID":"SKKVGE7SBUY5OR99","platformName":"Android","autoAcceptAlerts":true}},{"requiredCapabilities":{}}]}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [null,null,[{"desiredCapabilities":{"app":"/Users/benz/git/xxxx/./src/test/resources/apk/xxxx.apk","appPackage":"xxxx.xxxx","clearSystemFiles":true,"noReset":"true","deviceName":"Vibe_2","fullReset":"false","appActivity":"xxxx.xxxx.ui.activity.SplashActivity","autoLaunch":false,"platformVersion":"7.","automationName":"uiautomator2","autoGrantPermissions":true,"device ID":"SKKVGE7SBUY5OR99","platformName":"Android","autoAcceptAlerts":true}},{"requiredCapabilities":{}}]]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1500793794658 (11:09:54 GMT+0400 (+04))
[MJSONWP] Encountered internal error running command: Error: You must include a platformName capability


So, what i am doing is, Installing the app before the code is run using the adb command:
adb -s <deviceID> install <appPath>

**Comment by jlipps** [comment]
@benz-philip did you try include a `platformName` capability with the value `Android`? It would be helpful to have a full set of logs

**Comment by jlipps** [comment]
closing due to inactivity

**Comment by Mounikagendev** [comment]
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error occured while starting App. Original error: Activity used to start app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity (WARNING: The server did not provide any stacktrace information)

**Comment by Alwirasheikh** [comment]
I am getting the same issue. 
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error occured while starting App. Original error: Activity used to start app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity (WARNING: The server did not provide any stacktrace information)
