### ISSUE TITLE
release TouchAction is not work on Huawei devices

### ISSUE THREAD

**Issue by lehungcuong** [appium/appium#8611]
## The problem

I hold an element and release it after some seconds. This action is not work on Huawei P8, on others type is work well.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: 10.12.5 (MAC)
* Node.js version (unless using Appium.app|exe): 7.10.0
* Mobile platform/version under test: 5.0.1 android
* Real device or emulator/simulator: Huawei P8
* Appium CLI or Appium.app|exe: CLI

## Details

I hold an element and release it after some seconds. This action is not work on Huawei P8, on others type is work well.

## Link to Appium logs

N/A

## Code To Reproduce Issue [ Good To Have ]
new TouchAction(driver).press(element).waitAction(1000*seconds).release().perform();

**Comment by mykola-mokhnach** [comment]
Does it work with UIAutomation2 backend?
Also, please attach full Appium logs.

**Comment by lehungcuong** [comment]
###
org.openqa.selenium.interactions.InvalidCoordinatesException: The coordinates provided to an interactions operation are invalid. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 6.57 seconds
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'cuong.local', ip: 'fe80:0:0:0:1070:916b:49a4:905c%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.5', java.version: '1.8.0_131'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{appPackage=com.zing.zalo, networkConnectionEnabled=true, noReset=true, warnings={}, databaseEnabled=false, deviceName=W3D7N16119021679, platform=LINUX, deviceUDID=W3D7N16119021679, appActivity=ui.ZaloLauncherActivity, desired={appPackage=com.zing.zalo, appActivity=ui.ZaloLauncherActivity, noReset=true, browserName=, unicodeKeyboard=true, udid=W3D7N16119021679, platformName=Android, deviceName=Android, resetKeyboard=true}, platformVersion=5.0.1, webStorageEnabled=false, locationContextEnabled=false, takesScreenshot=true, browserName=, javascriptEnabled=true, unicodeKeyboard=true, udid=W3D7N16119021679, platformName=Android, resetKeyboard=true}]
Session ID: 13a85c18-73ef-4495-a7ed-c229f2fc6bc0

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:173)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:671)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at io.appium.java_client.PerformsTouchActions.performTouchAction(PerformsTouchActions.java:39)
	at io.appium.java_client.TouchAction.perform(TouchAction.java:322)
	at zalo.uitest.core.helper.ZaloAbstractHelper.pressAndHold(ZaloAbstractHelper.java:209)
	at zalo.uitest.zaloapp.android.ChatTest.test013_send_txt_msg(ChatTest.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)

**Comment by mykola-mokhnach** [comment]
This is java exception stacktrace, which is not the same as Appium log. 
Also, the exception says you provide unacceptable coordinate values.

**Comment by lehungcuong** [comment]
But it worked on other device likes Samsung, Sony etc.

**Comment by dpgraham** [comment]
Closing this issue. If you can provide Appium logs we can re-open and have a look at it.
