### ISSUE TITLE
Swiping and Touch Actions fail for UWP application

### ISSUE THREAD

**Issue by sheldonyon** [appium/appium#8628]
## The problem

Swiping and touch actions not working for UWP application. The Server has an error.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): 6.11.0
* Mobile platform/version under test: Windows 10 UWP application
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium app

## Details

The Appium server crashes when you try and scroll using swipe or touchaction

## Link to Appium logs

[Appium] Welcome to Appium v1.6.4
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"f736c883-f105-4d30-a719-4bf328872f5e_nh7s0b45jarrj!App","deviceName":"WindowsPC","platformName":"Windows"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"f736c883-f105-4d30-a719-4bf328872f5e_nh7s0b45jarrj!App","deviceName":"WindowsPC","platformName":"Windows"},null,null,null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1496860722249 (11:38:42 GMT-0700 (Pacific Daylight Time))
[Appium] Creating new WindowsDriver (v0.4.1) session
[Appium] Capabilities:
[Appium]   app: 'f736c883-f105-4d30-a719-4bf328872f5e_nh7s0b45jarrj!App'
[Appium]   deviceName: 'WindowsPC'
[Appium]   platformName: 'Windows'
[BaseDriver] The following capabilities were provided, but are not recognized by appium: app.
[BaseDriver] Session created with session id: f1fd4ef0-c993-4574-a875-9de574c5f10b
[WinAppDriver] Verifying WinAppDriver is installed with correct checksum
[WinAppDriver] WinAppDriver changed state to 'starting'
[WinAppDriver] Killing any old WinAppDrivers on same port, running: FOR /F "usebackq tokens=5" %a in (`netstat -nao ^| findstr /R /C:"4724 "`) do (FOR /F "usebackq" %b in (`TASKLIST /FI "PID eq %a" ^| findstr /I winappdriver.exe`) do (IF NOT %b=="" TASKKILL /F /PID %a))
[WinAppDriver] No old WinAppDrivers seemed to exist
[WinAppDriver] Spawning winappdriver with: undefined 4724/wd/hub
[WinAppDriver] [STDOUT] Windows Application Driver Beta listening for requests at: http://127.0.0.1:4724/wd/hub
[WinAppDriver] WinAppDriver changed state to 'online'
[JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:4724/wd/hub/session] with body: {"desiredCapabilities":{"app":"f736c883-f105-4d30-a719-4bf328872f5e_nh7s0b45jarrj!App","deviceName":"WindowsPC","platformName":"Windows"}}
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] Address 'http://127.0.0.1:4724/wd/hub' is already in use
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] Press ENTER to exit.
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] ==========================================
[WinAppDriver] [STDOUT] POST /wd/hub/session HTTP/1.1
[WinAppDriver] [STDOUT] Accept: */*
[WinAppDriver] [STDOUT] Connection: keep-alive
[WinAppDriver] [STDOUT] Content-Length: 138
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] Host: 127.0.0.1:4724
[WinAppDriver] [STDOUT] User-Agent: appium
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] {"desiredCapabilities":{"app":"f736c883-f105-4d30-a719-4bf328872f5e_nh7s0b45jarrj!App","deviceName":"WindowsPC","platformName":"Windows"}}
[WinAppDriver] [STDOUT] SessionManager - Creating session
[WinAppDriver] [STDOUT] SessionManager - WinAppDriver succeeded loading MitaBroker
[WinAppDriver] [STDOUT] SessionManager - Application launched
[WinAppDriver] [STDOUT] SessionManager - Session successfully created: 7BCD7304-9E74-410C-97C5-AD480088EFFD
[WinAppDriver] [STDOUT] HTTP/1.1 200 OK
[WinAppDriver] [STDOUT] Content-Length: 161
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] {"sessionId":"7BCD7304-9E74-410C-97C5-AD480088EFFD","status":0,"value":{"app":"f736c883-f105-4d30-a719-4bf328872f5e_nh7s0b45jarrj!App","platformName":"Windows"}}
[JSONWP Proxy] Got response with status 200: {"sessionId":"7BCD7304-9E74-410C-97C5-AD480088EFFD","status":0,"value":{"app":"f736c883-f105-4d30-a719-4bf328872f5e_nh7s0b45jarrj!App","platformName":"Windows"}}
[Appium] New WindowsDriver session created successfully, session f1fd4ef0-c993-4574-a875-9de574c5f10b added to master session list
[BaseDriver] Event 'newSessionStarted' logged at 1496860732558 (11:38:52 GMT-0700 (Pacific Daylight Time))
[MJSONWP] Responding to client with driver.createSession() result: {"app":"f736c883-f105-4d30-a719-4bf328872f5e_nh7s0b45jarrj!App","deviceName":"WindowsPC","platformName":"Windows"}
[HTTP] <-- POST /wd/hub/session 200 10317 ms - 186 
[HTTP] --> POST /wd/hub/session/f1fd4ef0-c993-4574-a875-9de574c5f10b/timeouts {"type":"implicit","ms":8000}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Proxying [POST /wd/hub/session/f1fd4ef0-c993-4574-a875-9de574c5f10b/timeouts] to [POST http://127.0.0.1:4724/wd/hub/session/7BCD7304-9E74-410C-97C5-AD480088EFFD/timeouts] with body: {"type":"implicit","ms":8000}
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] ==========================================
[WinAppDriver] [STDOUT] POST /wd/hub/session/7BCD7304-9E74-410C-97C5-AD480088EFFD/timeouts HTTP/1.1
[WinAppDriver] [STDOUT] Accept: */*
[WinAppDriver] [STDOUT] Connection: keep-alive
[WinAppDriver] [STDOUT] Content-Length: 29
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] Host: 127.0.0.1:4724
[WinAppDriver] [STDOUT] User-Agent: appium
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] {"type":"implicit","ms":8000}
[WinAppDriver] [STDOUT] HTTP/1.1 200 OK
[WinAppDriver] [STDOUT] Content-Length: 63
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] {"sessionId":"7BCD7304-9E74-410C-97C5-AD480088EFFD","status":0}
[JSONWP Proxy] Got response with status 200: {"sessionId":"7BCD7304-9E74-410C-97C5-AD480088EFFD","status":0}
[JSONWP Proxy] Replacing sessionId 7BCD7304-9E74-410C-97C5-AD480088EFFD with f1fd4ef0-c993-4574-a875-9de574c5f10b
[HTTP] <-- POST /wd/hub/session/f1fd4ef0-c993-4574-a875-9de574c5f10b/timeouts 200 6 ms - 63 
[HTTP] --> POST /wd/hub/session/f1fd4ef0-c993-4574-a875-9de574c5f10b/element {"using":"accessibility id","value":"episodesLabelAutomationId"}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Proxying [POST /wd/hub/session/f1fd4ef0-c993-4574-a875-9de574c5f10b/element] to [POST http://127.0.0.1:4724/wd/hub/session/7BCD7304-9E74-410C-97C5-AD480088EFFD/element] with body: {"using":"accessibility id","value":"episodesLabelAutomationId"}
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] ==========================================
[WinAppDriver] [STDOUT] POST /wd/hub/session/7BCD7304-9E74-410C-97C5-AD480088EFFD/element HTTP/1.1
[WinAppDriver] [STDOUT] Accept: */*
[WinAppDriver] [STDOUT] Connection: keep-alive
[WinAppDriver] [STDOUT] Content-Length: 64
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] Host: 127.0.0.1:4724
[WinAppDriver] [STDOUT] User-Agent: appium
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] {"using":"accessibility id","value":"episodesLabelAutomationId"}
[WinAppDriver] [STDOUT] HTTP/1.1 200 OK
[WinAppDriver] [STDOUT] Content-Length: 100
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] {"sessionId":"7BCD7304-9E74-410C-97C5-AD480088EFFD","status":0,"value":{"ELEMENT":"42.462304.2.19"}}
[JSONWP Proxy] Got response with status 200: {"sessionId":"7BCD7304-9E74-410C-97C5-AD480088EFFD","status":0,"value":{"ELEMENT":"42.462304.2.19"}}
[JSONWP Proxy] Replacing sessionId 7BCD7304-9E74-410C-97C5-AD480088EFFD with f1fd4ef0-c993-4574-a875-9de574c5f10b
[HTTP] <-- POST /wd/hub/session/f1fd4ef0-c993-4574-a875-9de574c5f10b/element 200 42 ms - 100 
[HTTP] --> GET /wd/hub/session/f1fd4ef0-c993-4574-a875-9de574c5f10b/element/42.462304.2.19/text {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Proxying [GET /wd/hub/session/f1fd4ef0-c993-4574-a875-9de574c5f10b/element/42.462304.2.19/text] to [GET http://127.0.0.1:4724/wd/hub/session/7BCD7304-9E74-410C-97C5-AD480088EFFD/element/42.462304.2.19/text] with body: {}
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] ==========================================
[WinAppDriver] [STDOUT] GET /wd/hub/session/7BCD7304-9E74-410C-97C5-AD480088EFFD/element/42.462304.2.19/text HTTP/1.1
[WinAppDriver] [STDOUT] Accept: */*
[WinAppDriver] [STDOUT] Connection: keep-alive
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] Host: 127.0.0.1:4724
[WinAppDriver] [STDOUT] User-Agent: appium
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] HTTP/1.1 200 OK
[WinAppDriver] [STDOUT] Content-Length: 82
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] {"sessionId":"7BCD7304-9E74-410C-97C5-AD480088EFFD","status":0,"value":"Episodes"}
[JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"7BCD7304-9E74-410C-97C5-AD480088EFFD\",\"status\":0,\"value\":\"Episodes\"}"
[JSONWP Proxy] Replacing sessionId 7BCD7304-9E74-410C-97C5-AD480088EFFD with f1fd4ef0-c993-4574-a875-9de574c5f10b
[HTTP] <-- GET /wd/hub/session/f1fd4ef0-c993-4574-a875-9de574c5f10b/element/42.462304.2.19/text 200 7 ms - 82 
[HTTP] --> POST /wd/hub/session/f1fd4ef0-c993-4574-a875-9de574c5f10b/element {"using":"accessibility id","value":"emergencyContactsButtonAutomationId"}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Proxying [POST /wd/hub/session/f1fd4ef0-c993-4574-a875-9de574c5f10b/element] to [POST http://127.0.0.1:4724/wd/hub/session/7BCD7304-9E74-410C-97C5-AD480088EFFD/element] with body: {"using":"accessibility id","value":"emergencyContactsButtonAutomationId"}
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] ==========================================
[WinAppDriver] [STDOUT] POST /wd/hub/session/7BCD7304-9E74-410C-97C5-AD480088EFFD/element HTTP/1.1
[WinAppDriver] [STDOUT] Accept: */*
[WinAppDriver] [STDOUT] Connection: keep-alive
[WinAppDriver] [STDOUT] Content-Length: 74
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] Host: 127.0.0.1:4724
[WinAppDriver] [STDOUT] User-Agent: appium
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] {"using":"accessibility id","value":"emergencyContactsButtonAutomationId"}
[WinAppDriver] [STDOUT] HTTP/1.1 200 OK
[WinAppDriver] [STDOUT] Content-Length: 100
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] {"sessionId":"7BCD7304-9E74-410C-97C5-AD480088EFFD","status":0,"value":{"ELEMENT":"42.462304.2.22"}}
[JSONWP Proxy] Got response with status 200: {"sessionId":"7BCD7304-9E74-410C-97C5-AD480088EFFD","status":0,"value":{"ELEMENT":"42.462304.2.22"}}
[JSONWP Proxy] Replacing sessionId 7BCD7304-9E74-410C-97C5-AD480088EFFD with f1fd4ef0-c993-4574-a875-9de574c5f10b
[HTTP] <-- POST /wd/hub/session/f1fd4ef0-c993-4574-a875-9de574c5f10b/element 200 132 ms - 100 
[HTTP] --> POST /wd/hub/session/f1fd4ef0-c993-4574-a875-9de574c5f10b/element/42.462304.2.22/click {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Proxying [POST /wd/hub/session/f1fd4ef0-c993-4574-a875-9de574c5f10b/element/42.462304.2.22/click] to [POST http://127.0.0.1:4724/wd/hub/session/7BCD7304-9E74-410C-97C5-AD480088EFFD/element/42.462304.2.22/click] with body: {}
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] ==========================================
[WinAppDriver] [STDOUT] POST /wd/hub/session/7BCD7304-9E74-410C-97C5-AD480088EFFD/element/42.462304.2.22/click HTTP/1.1
[WinAppDriver] [STDOUT] Accept: */*
[WinAppDriver] [STDOUT] Connection: keep-alive
[WinAppDriver] [STDOUT] Content-Length: 2
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] Host: 127.0.0.1:4724
[WinAppDriver] [STDOUT] User-Agent: appium
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] {}
[WinAppDriver] [STDOUT] HTTP/1.1 200 OK
[WinAppDriver] [STDOUT] Content-Length: 63
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] {"sessionId":"7BCD7304-9E74-410C-97C5-AD480088EFFD","status":0}
[JSONWP Proxy] Got response with status 200: {"sessionId":"7BCD7304-9E74-410C-97C5-AD480088EFFD","status":0}
[JSONWP Proxy] Replacing sessionId 7BCD7304-9E74-410C-97C5-AD480088EFFD with f1fd4ef0-c993-4574-a875-9de574c5f10b
[HTTP] <-- POST /wd/hub/session/f1fd4ef0-c993-4574-a875-9de574c5f10b/element/42.462304.2.22/click 200 115 ms - 63 
[HTTP] --> GET /wd/hub/session/f1fd4ef0-c993-4574-a875-9de574c5f10b/window/current/size {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Proxying [GET /wd/hub/session/f1fd4ef0-c993-4574-a875-9de574c5f10b/window/current/size] to [GET http://127.0.0.1:4724/wd/hub/session/7BCD7304-9E74-410C-97C5-AD480088EFFD/window/current/size] with body: {}
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] ==========================================
[WinAppDriver] [STDOUT] GET /wd/hub/session/7BCD7304-9E74-410C-97C5-AD480088EFFD/window/current/size HTTP/1.1
[WinAppDriver] [STDOUT] Accept: */*
[WinAppDriver] [STDOUT] Connection: keep-alive
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] Host: 127.0.0.1:4724
[WinAppDriver] [STDOUT] User-Agent: appium
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] HTTP/1.1 200 OK
[WinAppDriver] [STDOUT] Content-Length: 99
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] {"sessionId":"7BCD7304-9E74-410C-97C5-AD480088EFFD","status":0,"value":{"height":940,"width":1216}}
[JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"7BCD7304-9E74-410C-97C5-AD480088EFFD\",\"status\":0,\"value\":{\"height\":940,\"width\":1216}}"
[JSONWP Proxy] Replacing sessionId 7BCD7304-9E74-410C-97C5-AD480088EFFD with f1fd4ef0-c993-4574-a875-9de574c5f10b
[HTTP] <-- GET /wd/hub/session/f1fd4ef0-c993-4574-a875-9de574c5f10b/window/current/size 200 5 ms - 99 
[HTTP] --> POST /wd/hub/session/f1fd4ef0-c993-4574-a875-9de574c5f10b/touch/perform {"actions":[{"action":"press","options":{"x":608,"y":752}},{"action":"moveTo","options":{"x":608,"y":188}},{"action":"release"}]}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Proxying [POST /wd/hub/session/f1fd4ef0-c993-4574-a875-9de574c5f10b/touch/perform] to [POST http://127.0.0.1:4724/wd/hub/session/7BCD7304-9E74-410C-97C5-AD480088EFFD/touch/perform] with body: {"actions":[{"action":"press","options":{"x":608,"y":752}},{"action":"moveTo","options":{"x":608,"y":188}},{"action":"release"}]}
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] ==========================================
[WinAppDriver] [STDOUT] POST /wd/hub/session/7BCD7304-9E74-410C-97C5-AD480088EFFD/touch/perform HTTP/1.1
[WinAppDriver] [STDOUT] Accept: */*
[WinAppDriver] [STDOUT] Connection: keep-alive
[WinAppDriver] [STDOUT] Content-Length: 129
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] Host: 127.0.0.1:4724
[WinAppDriver] [STDOUT] User-Agent: appium
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] {"actions":[{"action":"press","options":{"x":608,"y":752}},{"action":"moveTo","options":{"x":608,"y":188}},{"action":"release"}]}
[WinAppDriver] [STDOUT] HTTP/1.1 400 Bad Request
[WinAppDriver] [STDOUT] Content-Length: 98
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] {"status":100,"value":{"error":"invalid argument","message":"Missing Command Parameter: element"}}
[MJSONWP] Encountered internal error running command:  {"jsonwp":{"status":100,"value":{"error":"invalid argument","message":"Missing Command Parameter: element"}}} ProxyRequestError: Could not proxy command to remote server. Original error: 400 - {"status":100,"value":{"error":"invalid argument","message":"Missing Command Parameter: element"}}
    at JWProxy.proxy$ (C:\Users\sheldony\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:144:13)
    at tryCatch (C:\Users\sheldony\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\sheldony\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\sheldony\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\sheldony\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session/f1fd4ef0-c993-4574-a875-9de574c5f10b/touch/perform 500 7 ms - 186 

## Code To Reproduce Issue [ Good To Have ]

m_WindowsDriver.Swipe(startx, starty, startx, endy, 3000);
            TouchAction scrollDown = new TouchAction(m_WindowsDriver);
            scrollDown.Press(startx, starty).MoveTo(startx, endy).Release().Perform();

**Comment by sheldonyon** [comment]
This issue may be fixed by using 0.9beta version of winappdriver can you change the install to use the new version of winappdriver.
