### ISSUE TITLE
Appium is unable to start the Hybrid app after installing the Hybrid app

### ISSUE THREAD

**Issue by NarayanaBojja** [appium/appium#8642]
## The problem

Appium is  installing the Hybrid app. But it is failing to start the app. 

## Environment

* Appium version : 1.6.5
* Mobile platform/version under test: Android 5.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:  Appium.exe 1.6.5

## Details

Appium is  installing the Hybrid app. But it is failing to start the app. It is able to start in some devices. If I start the the app by clicking by my own then session is creating.

## Link to Appium logs

https://gist.github.com/NarayanaBojja/01eec343e7b0c33c81fb31f6fc3372dd

## Code To Reproduce Issue [ Good To Have ]

                       DesiredCapabilities capabilities = new DesiredCapabilities();

			capabilities.setCapability(CapabilityType.BROWSER_NAME, "");
			capabilities.setCapability("newCommandTimeout", 999999);
			capabilities.setCapability("deviceName", "GYHYGIR4QG8LDA7S");
			capabilities.setCapability("platformName", "Android");
			capabilities.setCapability("platformVersion", "5.1");
			capabilities.setCapability("autoWebview", true);
			capabilities.setCapability("app", "***********.apk");
			capabilities.setCapability("appPackage", "**********");
			driver = new AppiumDriver(new URL("http://0.0.0.0:4723/wd/hub"), capabilities);

**Comment by mykola-mokhnach** [comment]
You must set proper value to **appActivity** capability

**Comment by NarayanaBojja** [comment]
Hi,
Thanks for quick reply. I tried by adding appActivity capability.
capabilities.setCapability("appActivity ", "MainActivity");

But I still have same error. nothing is changed. But it is working for Android 5.0 Version. It is not working for Android 5.1 version.

**Comment by mykola-mokhnach** [comment]
If the error is the same then bootstrap most likely still does not like the given activity name. You could also try to omit BROWSER_NAME and appPackage capabilities.

**Comment by NarayanaBojja** [comment]
Nothing is changed . I am getting same error. I am pasting last line here,
[36minfo[39m: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: com.ionicframework.blankapp494544/.MainActivity never started. Current: com.yulong.android.launcher3/.Launcher)","origValue":"com.ionicframework.blankapp494544/.MainActivity never started. Current: com.yulong.android.launcher3/.Launcher"},"sessionId":null}

**Comment by mykola-mokhnach** [comment]
It might be you also have to set correct value to  **appWaitActivity** capability.

**Comment by NarayanaBojja** [comment]
Hi tried with setting appWaitActivity capability as below .
capabilities.setCapability("appWaitActivity  ", ".MainActivity");  
Nothing is changed I am getting same error.

[36minfo[39m: [debug] Waiting for pkg "com.ionicframework.blankapp494544" and activity "com.ionicframework.blankapp494544.MainActivity" to be focused
[36minfo[39m: [debug] Getting focused package and activity
[36minfo[39m: [debug] executing cmd: C:\sdk\platform-tools\adb.exe -s GYHYGIR4QG8LDA7S shell "dumpsys window windows"
[36minfo[39m: [debug] Getting focused package and activity
[36minfo[39m: [debug] executing cmd: C:\sdk\platform-tools\adb.exe -s GYHYGIR4QG8LDA7S shell "dumpsys window windows"
[36minfo[39m: [debug] Getting focused package and activity
[36minfo[39m: [debug] executing cmd: C:\sdk\platform-tools\adb.exe -s GYHYGIR4QG8LDA7S shell "dumpsys window windows"
[36minfo[39m: [debug] Getting focused package and activity
[36minfo[39m: [debug] executing cmd: C:\sdk\platform-tools\adb.exe -s GYHYGIR4QG8LDA7S shell "dumpsys window windows"
[36minfo[39m: [debug] Getting focused package and activity
[36minfo[39m: [debug] executing cmd: C:\sdk\platform-tools\adb.exe -s GYHYGIR4QG8LDA7S shell "dumpsys window windows"
[36minfo[39m: [debug] Getting focused package and activity
[36minfo[39m: [debug] executing cmd: C:\sdk\platform-tools\adb.exe -s GYHYGIR4QG8LDA7S shell "dumpsys window windows"
[36minfo[39m: [debug] Getting focused package and activity
[36minfo[39m: [debug] executing cmd: C:\sdk\platform-tools\adb.exe -s GYHYGIR4QG8LDA7S shell "dumpsys window windows"
[36minfo[39m: [debug] Getting focused package and activity
[36minfo[39m: [debug] executing cmd: C:\sdk\platform-tools\adb.exe -s GYHYGIR4QG8LDA7S shell "dumpsys window windows"
[36minfo[39m: [debug] Getting focused package and activity
[36minfo[39m: [debug] executing cmd: C:\sdk\platform-tools\adb.exe -s GYHYGIR4QG8LDA7S shell "dumpsys window windows"
[36minfo[39m: [debug] Getting focused package and activity
[36minfo[39m: [debug] executing cmd: C:\sdk\platform-tools\adb.exe -s GYHYGIR4QG8LDA7S shell "dumpsys window windows"
[36minfo[39m: [debug] Getting focused package and activity
[36minfo[39m: [debug] executing cmd: C:\sdk\platform-tools\adb.exe -s GYHYGIR4QG8LDA7S shell "dumpsys window windows"
[36minfo[39m: [debug] Getting focused package and activity
[36minfo[39m: [debug] executing cmd: C:\sdk\platform-tools\adb.exe -s GYHYGIR4QG8LDA7S shell "dumpsys window windows"
[36minfo[39m: [debug] Getting focused package and activity
[36minfo[39m: [debug] executing cmd: C:\sdk\platform-tools\adb.exe -s GYHYGIR4QG8LDA7S shell "dumpsys window windows"
[36minfo[39m: [debug] Getting focused package and activity
[36minfo[39m: [debug] executing cmd: C:\sdk\platform-tools\adb.exe -s GYHYGIR4QG8LDA7S shell "dumpsys window windows"
[36minfo[39m: [debug] Getting focused package and activity
[36minfo[39m: [debug] executing cmd: C:\sdk\platform-tools\adb.exe -s GYHYGIR4QG8LDA7S shell "dumpsys window windows"
[36minfo[39m: [debug] Getting focused package and activity
[36minfo[39m: [debug] executing cmd: C:\sdk\platform-tools\adb.exe -s GYHYGIR4QG8LDA7S shell "dumpsys window windows"
[36minfo[39m: [debug] Getting focused package and activity
[36minfo[39m: [debug] executing cmd: C:\sdk\platform-tools\adb.exe -s GYHYGIR4QG8LDA7S shell "dumpsys window windows"
[36minfo[39m: [debug] Getting focused package and activity
[36minfo[39m: [debug] executing cmd: C:\sdk\platform-tools\adb.exe -s GYHYGIR4QG8LDA7S shell "dumpsys window windows"
[36minfo[39m: [debug] Getting focused package and activity
[36minfo[39m: [debug] executing cmd: C:\sdk\platform-tools\adb.exe -s GYHYGIR4QG8LDA7S shell "dumpsys window windows"
[36minfo[39m: [debug] Getting focused package and activity
[36minfo[39m: [debug] executing cmd: C:\sdk\platform-tools\adb.exe -s GYHYGIR4QG8LDA7S shell "dumpsys window windows"
[36minfo[39m: [debug] Getting focused package and activity
[36minfo[39m: [debug] executing cmd: C:\sdk\platform-tools\adb.exe -s GYHYGIR4QG8LDA7S shell "dumpsys window windows"
[36minfo[39m: [debug] Getting focused package and activity
[36minfo[39m: [debug] executing cmd: C:\sdk\platform-tools\adb.exe -s GYHYGIR4QG8LDA7S shell "dumpsys window windows"
[36minfo[39m: [debug] Getting focused package and activity
[36minfo[39m: [debug] executing cmd: C:\sdk\platform-tools\adb.exe -s GYHYGIR4QG8LDA7S shell "dumpsys window windows"
[36minfo[39m: [debug] Getting focused package and activity
[36minfo[39m: [debug] executing cmd: C:\sdk\platform-tools\adb.exe -s GYHYGIR4QG8LDA7S shell "dumpsys window windows"
[36minfo[39m: [debug] Getting focused package and activity
[36minfo[39m: [debug] executing cmd: C:\sdk\platform-tools\adb.exe -s GYHYGIR4QG8LDA7S shell "dumpsys window windows"
[31merror[39m: com.ionicframework.blankapp494544/.MainActivity never started. Current: com.yulong.android.launcher3/.Launcher
[36minfo[39m: [debug] Stopping logcat capture
[36minfo[39m: [debug] Logcat terminated with code null, signal SIGTERM
[36minfo[39m: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"shutdown"}
[36minfo[39m: [debug] [BOOTSTRAP] [debug] Got command of type SHUTDOWN
[36minfo[39m: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":"OK, shutting down"}
[36minfo[39m: [debug] [90m[UIAUTOMATOR STDOUT] [CDS]close[4724][39m
[36minfo[39m: [debug] Sent shutdown command, waiting for UiAutomator to stop...
[36minfo[39m: [debug] [BOOTSTRAP] [debug] Closed client connection
[36minfo[39m: [debug] [90m[UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1[39m
[36minfo[39m: [debug] [90m[UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=.[39m
[36minfo[39m: [debug] [90m[UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner[39m
[36minfo[39m: [debug] [90m[UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer[39m
[36minfo[39m: [debug] [90m[UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap[39m
[36minfo[39m: [debug] [90m[UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1[39m
[36minfo[39m: [debug] [90m[UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 0[39m
[36minfo[39m: [debug] [90m[UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=[39m
[36minfo[39m: [debug] [90m[UIAUTOMATOR STDOUT] Test results for WatcherResultPrinter=.[39m
[36minfo[39m: [debug] [90m[UIAUTOMATOR STDOUT] Time: 21.577[39m
[36minfo[39m: [debug] [90m[UIAUTOMATOR STDOUT] OK (1 test)[39m
[36minfo[39m: [debug] [90m[UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: -1[39m
[36minfo[39m: [debug] UiAutomator shut down normally
[36minfo[39m: [debug] Cleaning up android objects
[36minfo[39m: [debug] Cleaning up appium session
[31merror[39m: Failed to start an Appium session, err was: Error: com.ionicframework.blankapp494544/.MainActivity never started. Current: com.yulong.android.launcher3/.Launcher
[36minfo[39m: [debug] Error: com.ionicframework.blankapp494544/.MainActivity never started. Current: com.yulong.android.launcher3/.Launcher
    at [object Object].<anonymous> (D:\NarayanaB-Mss178\QV2HybrideApp\Eclipse\QV2HybridApp\lib\vendors\appium\node_modules\appium-adb\lib\adb.js:1314:12)
    at [object Object].<anonymous> (D:\NarayanaB-Mss178\QV2HybrideApp\Eclipse\QV2HybridApp\lib\vendors\appium\node_modules\appium-adb\lib\adb.js:1258:7)
    at [object Object].<anonymous> (D:\NarayanaB-Mss178\QV2HybrideApp\Eclipse\QV2HybridApp\lib\vendors\appium\node_modules\appium-adb\lib\adb.js:180:9)
    at ChildProcess.exithandler (child_process.js:742:7)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1016:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1088:5)
[36minfo[39m: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: com.ionicframework.blankapp494544/.MainActivity never started. Current: com.yulong.android.launcher3/.Launcher)","origValue":"com.ionicframework.blankapp494544/.MainActivity never started. Current: com.yulong.android.launcher3/.Launcher"},"sessionId":null}
[36minfo[39m: [37m<-- POST /wd/hub/session [39m[31m500[39m[90m 30434.095 ms - 342[39m [90m[39m

**Comment by NarayanaBojja** [comment]
Hi,
My issue doesn't get resolved. If you have any update, please comment here.

**Comment by zhaojunlin** [comment]
Have you solved the problem?

**Comment by zhaojunlin** [comment]
I have meet the problem, other tell me that the appium will re-sign the app when it installs app. You can try capabilities.setCapability("noSign", "True");

**Comment by saikrishna321** [comment]
you need to set the correct appActivity, Appium is unable to find the one provided by u ....

**Comment by NarayanaBojja** [comment]
@zhaojunlin 
Thanks for your time. I tried with that capability. Nothing is different . I am getting same error logs.
[36minfo[39m: [debug] Device is at API Level 22
[36minfo[39m: [debug] executing cmd: C:\sdk\platform-tools\adb.exe -s GYHYGIR4QG8LDA7S shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n com.ionicframework.blankapp494544/com.ionicframework.blankapp494544.MainActivity"
[36minfo[39m: [debug] Waiting for pkg "com.ionicframework.blankapp494544" and activity "com.ionicframework.blankapp494544.MainActivity" to be focused
[36minfo[39m: [debug] Getting focused package and activity
[36minfo[39m: [debug] executing cmd: C:\sdk\platform-tools\adb.exe -s GYHYGIR4QG8LDA7S shell "dumpsys window windows"
[36minfo[39m: [debug] Getting focused package and activity
[36minfo[39m: [debug] executing cmd: C:\sdk\platform-tools\adb.exe -s GYHYGIR4QG8LDA7S shell "dumpsys window windows"
[36minfo[39m: [debug] Getting focused package and activity
[36minfo[39m: [debug] executing cmd: C:\sdk\platform-tools\adb.exe -s GYHYGIR4QG8LDA7S shell "dumpsys window windows"
[36minfo[39m: [debug] Getting focused package and activity
[36minfo[39m: [debug] executing cmd: C:\sdk\platform-tools\adb.exe -s GYHYGIR4QG8LDA7S shell "dumpsys window windows"
[36minfo[39m: [debug] Getting focused package and activity
It continues for some time and ends up with error message.

**Comment by NarayanaBojja** [comment]
@saikrishna321 
I am providing correct appActivity. It's not working. It is working without appActivity with other mobiles.

**Comment by zhaojunlin** [comment]
You can try another apk?

**Comment by zhaojunlin** [comment]
My p[roblem has solved，the apk has problem, so install the apk not open

**Comment by NarayanaBojja** [comment]
The problem is not with apk . Because it is working fine for other mobiles. I guess the problem is with my mobile . Appium use chrome driver for hybridApps I think so.  Chrome driver and my phone are not compatible to each other . I had same issue when I was testing mobile web application. I tried changing chrome driver versions latest version. But nothing is changed, same error.  If you have any know workable solution , please help me.

**Comment by dpgraham** [comment]
Have you tried omitting appPackage from your desired capabilities?

**Comment by jlipps** [comment]
closing due to inactivity
