### ISSUE TITLE
Appium doesn't support for Firefox in Android

### ISSUE THREAD

**Issue by osandadeshan** [appium/appium#8651]
Problem: I am using appium for mobile automation. But when I change the browser type to firefox on android, it throws the below error.
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: The desired capabilities must include either an app, appPackage or browserName (WARNING: The server did not provide any stacktrace information)

As the capability for firefox I used,
capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "firefox");

## Environment

* Appium version 1.6.4
* Desktop OS/version used to run Appium: Windows 10
* Node.js version: v7.6.0
* Mobile platform/version under test: 5.1.0 (API 22)
* Real device or emulator/simulator: Genymotion Emulator
* Appium CLI or Appium.app|exe: Appium.exe

## Appium logs

[Appium] Welcome to Appium v1.6.4
[Appium] Non-default server args:
[Appium]   address: 127.0.0.1
[Appium] Appium REST http interface listener started on 127.0.0.1:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"browserName":"firefox","platformName":"Android","version":"5.1.0","deviceName":"My phone","platform":"ANDROID"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"browserName":"firefox","platformName":"Android","version":"5.1.0","deviceName":"My phone","platform":"ANDROID"},null,null,null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1497184060796 (17:57:40 GMT+0530 (Sri Lanka Standard Time))
[Appium] Creating new AndroidDriver (v1.17.1) session
[Appium] Capabilities:
[Appium]   browserName: 'firefox'
[Appium]   platformName: 'Android'
[Appium]   version: '5.1.0'
[Appium]   deviceName: 'My phone'
[Appium]   platform: 'ANDROID'
[AndroidDriver] AndroidDriver version: 1.17.1
[BaseDriver] The following capabilities were provided, but are not recognized by appium: version, platform.
[AndroidDriver] Error: The desired capabilities must include either an app, appPackage or browserName
    at Object.wrappedLogger.errorAndThrow (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:63:13)
    at AndroidDriver.validateDesiredCaps (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-android-driver\lib\driver.js:446:11)
    at AndroidDriver.callee$0$0$ (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\commands\session.js:14:8)
    at tryCatch (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at invoke (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at enqueueResult (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:185:17)
    at Promise.F (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\core-js\library\modules\$.export.js:30:36)
    at AsyncIterator.enqueue (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at Object.runtime.async (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:209:12)
    at AndroidDriver.callee$0$0 [as createSession] (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-base-driver\build\lib\basedriver\commands\session.js:32:30)
    at AndroidDriver.createSession$ (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-android-driver\lib\driver.js:32:20)
    at tryCatch (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at invoke (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at enqueueResult (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:185:17)
    at Promise.F (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\core-js\library\modules\$.export.js:30:36)
    at AsyncIterator.enqueue (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at Object.runtime.async (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:209:12)
    at AndroidDriver.createSession (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-android-driver\build\lib\driver.js:133:34)
    at AppiumDriver.createSession$ (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\lib\appium.js:183:43)
    at tryCatch (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at invoke (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at enqueueResult (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:185:17)
    at Promise.F (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\core-js\library\modules\$.export.js:30:36)
    at AsyncIterator.enqueue (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at Object.runtime.async (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:209:12)
    at AppiumDriver.createSession (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\build\lib\appium.js:307:34)
    at C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\driver.js:218:24
    at tryCatcher (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\bluebird\js\main\promise.js:510:31)
    at Promise._settlePromiseAt (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\bluebird\js\main\promise.js:584:18)
    at Promise._settlePromiseAtPostResolution (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\bluebird\js\main\promise.js:248:10)
    at Async._drainQueue (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\bluebird\js\main\async.js:128:12)
    at Async._drainQueues (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\bluebird\js\main\async.js:15:14)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
 Error: The desired capabilities must include either an app, appPackage or browserName
    at Object.wrappedLogger.errorAndThrow (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:63:13)
    at AndroidDriver.validateDesiredCaps (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-android-driver\lib\driver.js:446:11)
    at AndroidDriver.callee$0$0$ (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\commands\session.js:14:8)
    at tryCatch (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at invoke (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at enqueueResult (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:185:17)
    at Promise.F (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\core-js\library\modules\$.export.js:30:36)
    at AsyncIterator.enqueue (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at Object.runtime.async (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:209:12)
    at AndroidDriver.callee$0$0 [as createSession] (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-base-driver\build\lib\basedriver\commands\session.js:32:30)
    at AndroidDriver.createSession$ (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-android-driver\lib\driver.js:32:20)
    at tryCatch (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at invoke (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at enqueueResult (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:185:17)
    at Promise.F (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\core-js\library\modules\$.export.js:30:36)
    at AsyncIterator.enqueue (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at Object.runtime.async (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:209:12)
    at AndroidDriver.createSession (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-android-driver\build\lib\driver.js:133:34)
    at AppiumDriver.createSession$ (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\lib\appium.js:183:43)
    at tryCatch (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at invoke (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at enqueueResult (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:185:17)
    at Promise.F (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\core-js\library\modules\$.export.js:30:36)
    at AsyncIterator.enqueue (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at Object.runtime.async (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:209:12)
    at AppiumDriver.createSession (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\build\lib\appium.js:307:34)
    at C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\driver.js:218:24
    at tryCatcher (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\bluebird\js\main\promise.js:510:31)
    at Promise._settlePromiseAt (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\bluebird\js\main\promise.js:584:18)
    at Promise._settlePromiseAtPostResolution (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\bluebird\js\main\promise.js:248:10)
    at Async._drainQueue (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\bluebird\js\main\async.js:128:12)
    at Async._drainQueues (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\bluebird\js\main\async.js:15:14)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
[AndroidDriver] Shutting down Android driver
[AndroidDriver] Called deleteSession but bootstrap wasn't active
[MJSONWP] Encountered internal error running command: Error: The desired capabilities must include either an app, appPackage or browserName
    at Object.wrappedLogger.errorAndThrow (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:63:13)
    at AndroidDriver.validateDesiredCaps (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-android-driver\lib\driver.js:446:11)
    at AndroidDriver.callee$0$0$ (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\commands\session.js:14:8)
    at tryCatch (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at invoke (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at enqueueResult (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:185:17)
    at Promise.F (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\core-js\library\modules\$.export.js:30:36)
    at AsyncIterator.enqueue (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at Object.runtime.async (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:209:12)
    at AndroidDriver.callee$0$0 [as createSession] (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-base-driver\build\lib\basedriver\commands\session.js:32:30)
    at AndroidDriver.createSession$ (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-android-driver\lib\driver.js:32:20)
    at tryCatch (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at invoke (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at enqueueResult (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:185:17)
    at Promise.F (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\core-js\library\modules\$.export.js:30:36)
    at AsyncIterator.enqueue (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at Object.runtime.async (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:209:12)
    at AndroidDriver.createSession (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-android-driver\build\lib\driver.js:133:34)
    at AppiumDriver.createSession$ (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\lib\appium.js:183:43)
    at tryCatch (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at invoke (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at enqueueResult (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:185:17)
    at Promise.F (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\core-js\library\modules\$.export.js:30:36)
    at AsyncIterator.enqueue (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at Object.runtime.async (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:209:12)
    at AppiumDriver.createSession (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\build\lib\appium.js:307:34)
    at C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\driver.js:218:24
    at tryCatcher (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\bluebird\js\main\promise.js:510:31)
    at Promise._settlePromiseAt (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\bluebird\js\main\promise.js:584:18)
    at Promise._settlePromiseAtPostResolution (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\bluebird\js\main\promise.js:248:10)
    at Async._drainQueue (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\bluebird\js\main\async.js:128:12)
    at Async._drainQueues (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues (C:\Users\Osanda\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\bluebird\js\main\async.js:15:14)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
[HTTP] <-- POST /wd/hub/session 500 36 ms - 215

**Comment by dpgraham** [comment]
Firefox isn't supported by Android Driver. Android Driver only supports Chrome and the native Android browser.

**Comment by Khushboo10** [comment]
Hi Guys, 
Is appium started giving support for firefox and other browsers?

**Comment by ArjitRout** [comment]
@dpgraham Is firefox driver supported for android? How do we declare the capabilities and platform? can you please provide any example if possible? Appium version we are using is 1.9

**Comment by ckzgraphics** [comment]
**Appium does not support Firefox on Android/iOS as of now**. You can review the following documents-
- [http://appium.io/docs/en/writing-running-appium/web/mobile-web/](http://appium.io/docs/en/writing-running-appium/web/mobile-web/)
- [http://appium.io/docs/en/about-appium/platform-support/](http://appium.io/docs/en/about-appium/platform-support/)

**Comment by mykola-mokhnach** [comment]
Geckodriver support has been added to https://github.com/appium/appium-geckodriver, which is going to be available in the upcoming Appium release (1.20)
