### ISSUE TITLE
[XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 1

### ISSUE THREAD

**Issue by Dayanandmdr** [appium/appium#8681]
Hi,
getting error in mac like this
[XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 1

help me regarding this

environment
1.Mac
2.Appium Desktop 1.6.5

**Comment by mykola-mokhnach** [comment]
Please change current folder to the root folder of WebDriverAgent project and execute 

```bash -x Scripts/bootstrap.sh -d```

Then paste the terminal output here.

**Comment by Dayanandmdr** [comment]
ok i will try this out and get back to you

Regards
Dayanand

**Comment by jyotidgs1** [comment]
@Dayanandmdr : I am also facing same issue, Pls let me know if this issue is resolved and how?

**Comment by imurchie** [comment]
@jyotidgs1 Can you try my was suggested above and report the terminal output here?

**Comment by MoonTahoe** [comment]
I'm having the same problem. I gave the command a shot.

First I navigated to the `node_modules/appium-xciutest-driver/WebDriverAgent` and ran `bash -x Scripts/bootstrap.sh -d` from this directory.

Here is the output

```
+ set -e
+ export PATH=/Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/bin:/Users/alexbanks/.nvm/versions/node/v8.1.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/alexbanks/Library/Android/sdk/tools:/Users/alexbanks/Library/Android/sdk/platform-tools:/Users/alexbanks/Library/Android/sdk/tools:/Users/alexbanks/Library/Android/sdk/platform-tools:/Users/alexbanks/Library/Android/sdk/tools:/Users/alexbanks/Library/Android/sdk/platform-tools:/usr/local/bin
+ PATH=/Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/bin:/Users/alexbanks/.nvm/versions/node/v8.1.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/alexbanks/Library/Android/sdk/tools:/Users/alexbanks/Library/Android/sdk/platform-tools:/Users/alexbanks/Library/Android/sdk/tools:/Users/alexbanks/Library/Android/sdk/platform-tools:/Users/alexbanks/Library/Android/sdk/tools:/Users/alexbanks/Library/Android/sdk/platform-tools:/usr/local/bin
+ BOLD='\033[1m'
+ [[ ! -f Scripts/bootstrap.sh ]]
+ getopts ' i d D h ' option
+ case "$option" in
+ FETCH_DEPS=1
+ getopts ' i d D h ' option
+ [[ -n x ]]
+ fetch_and_build_dependencies
+ echo -e '\033[1mFetching dependencies'
Fetching dependencies
+ assert_has_carthage
+ command -v carthage
+ cmp -s Cartfile.resolved Carthage/Cartfile.resolved
+ carthage bootstrap
*** Downloading RoutingHTTPServer.framework binary at "v1.0.1"
*** xcodebuild output can be found in /var/folders/x2/fhg_b7pj0577_tmjwkqm49zm0000gn/T/carthage-xcodebuild.twn9kg.log
+ cp Cartfile.resolved Carthage
+ [[ -n '' ]]
+ [[ -z x ]]
```

**Comment by MoonTahoe** [comment]
I also noticed this error further up in the appium log:

```
[XCUITest] Failed to check out repository into /Users/alexbanks/.config/yarn/global/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/RoutingHTTPServer: Could not create working directory (Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “RoutingHTTPServer” in the folder “Checkouts”." UserInfo={NSFilePath=/Users/alexbanks/.config/yarn/global/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/RoutingHTTPServer, NSUnderlyingError=0x7fbc10185840 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}})
```

```
"You don’t have permission to save the file “RoutingHTTPServer” in the folder “Checkouts”.
```

Could this Permission denied error be the cause? How would I fix this. I executed a `sudo chown` but it didn't seem to work.

**Comment by imurchie** [comment]
What are the permissions on the folders:
- `/Users/alexbanks/.config/yarn/global/node_modules/appium-xcuitest-driver/WebDriverAgent/`
- `/Users/alexbanks/.config/yarn/global/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/`
- `/Users/alexbanks/.config/yarn/global/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/`

**Comment by MoonTahoe** [comment]
The folder, `/Users/alexbanks/.config/yarn/global/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/` is not there.  I added carthage with `brew install carthage`.  I just tried to add it with a `yarn global add carthage`, but I still cannot find it at either of these locations:

* `/Users/alexbanks/.config/yarn/global/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/`
* `/Users/alexbanks/.config/yarn/global/node_modules/appium-xcuitest-driver/Carthage/`

### Permissions for WebDriverAgent folder
The WebDriver Agent folder was there. Here are the permissions.
```
$ ls -l /Users/alexbanks/.config/yarn/global/node_modules/appium-xcuitest-driver/WebDriverAgent/
total 48
-rw-r--r--   1 root  staff  1324 Jun 30 05:44 CONTRIBUTING.md
-rw-r--r--   1 root  staff    63 Jun 30 05:44 Cartfile
-rw-r--r--   1 root  staff    48 Jun 30 05:44 Cartfile.resolved
drwxr-xr-x   3 root  staff   102 Jul 12 20:38 Configurations
drwxr-xr-x  10 root  staff   340 Jul 12 20:38 Inspector
-rw-r--r--   1 root  staff  1535 Jun 30 05:44 LICENSE
-rw-r--r--   1 root  staff  1985 Jun 30 05:44 PATENTS
drwxr-xr-x   3 root  staff   102 Jul 12 20:38 PrivateHeaders
-rw-r--r--   1 root  staff  2647 Jun 30 05:44 README.md
drwxr-xr-x   4 root  staff   136 Jul 12 20:38 Scripts
drwxr-xr-x   5 root  staff   170 Jul 12 20:38 WebDriverAgent.xcodeproj
drwxr-xr-x  16 root  staff   544 Jul 12 20:38 WebDriverAgentLib
drwxr-xr-x   4 root  staff   136 Jul 12 20:38 WebDriverAgentRunner
drwxr-xr-x   5 root  staff   170 Jul 12 20:38 WebDriverAgentTests
```

**Comment by imurchie** [comment]
The `Carthage` directories are created when running the "carthage" program (which the bootstrap script runs). It looks like you don't have write permission in this folder. Also, it is inadvisable to install Appium as root.

**Comment by MoonTahoe** [comment]
Thanks. I added write permissions to that directory and the iOS device opens and my app loads. However, I am on to an entirely different set of issues.

**Comment by jyotidgs1** [comment]
@imurchie 
i had run the command on terminal : 
The output is:
DSK-496:WebDriverAgent gateway$ bash -xScripts/bootstrap.sh -d
bash: -S: invalid option
Usage:	bash [GNU long option] [option] ...
	bash [GNU long option] [option] script-file ...
GNU long options:
	--debug
	--debugger
	--dump-po-strings
	--dump-strings
	--help
	--init-file
	--login
	--noediting
	--noprofile
	--norc
	--posix
	--protected
	--rcfile
	--restricted
	--verbose
	--version
	--wordexp
Shell options:
	-irsD or -c command or -O shopt_option		(invocation only)
	-abefhkmnptuvxBCHP or -o option
DSK-496:WebDriverAgent gateway$ 
DSK-496:WebDriverAgent gateway$

**Comment by jyotidgs1** [comment]
And Appium log is: 
[Appium] Welcome to Appium v1.6.5
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> GET /wd/hub/sessions {}
[MJSONWP] Calling AppiumDriver.getSessions() with args: []
[MJSONWP] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 11 ms - 40 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/gateway/desktop/IntegrationApp.app","automationName":"XCUITest","deviceName":"iphone Simulator","platformName":"ios","platformVersion":"10.3","xcodeOrgId":"GQ2C5GKWJ2","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/gateway/desktop/IntegrationApp.app","automationName":"XCUITest","deviceName":"iphone Simulator","platformName":"ios","platformVersion":"10.3","xcodeOrgId":"GQ2C5GKWJ2","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1499938241650 (15:00:41 GMT+0530 (IST))
[Appium] Creating new XCUITestDriver (v2.30.0) session
[Appium] Capabilities:
[Appium]   app: '/Users/gateway/desktop/IntegrationApp.app'
[Appium]   automationName: 'XCUITest'
[Appium]   deviceName: 'iphone Simulator'
[Appium]   platformName: 'ios'
[Appium]   platformVersion: '10.3'
[Appium]   xcodeOrgId: 'GQ2C5GKWJ2'
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true
[XCUITest] XCUITestDriver version: 2.30.0
[BaseDriver] Session created with session id: 0cf8fed1-18f8-4f7e-a9ff-8113842c4b24
[XCUITest] Xcode version set to '8.3.3' 
[XCUITest] iOS SDK Version set to '10.3'
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1499938245348 (15:00:45 GMT+0530 (IST))
[XCUITest] Changing deviceName from 'iphone Simulator' to 'iPhone 6'
[iOSSim] Constructing iOS simulator for Xcode version 8.3.3 with udid '553BE51E-86C4-4C9C-AAE4-AD3DE2C7C89D'
[XCUITest] Determining device to run tests on: udid: '553BE51E-86C4-4C9C-AAE4-AD3DE2C7C89D', real device: false
[BaseDriver] Using local app '/Users/gateway/desktop/IntegrationApp.app'
[BaseDriver] Event 'appConfigured' logged at 1499938246373 (15:00:46 GMT+0530 (IST))
[XCUITest] Checking whether app '/Users/gateway/desktop/IntegrationApp.app' is actually present on file system
[XCUITest] App is present
[iOS] Getting bundle ID from app '/Users/gateway/desktop/IntegrationApp.app': 'com.facebooks.IntegrationsApps'
[XCUITest] Setting 'connectHardwareKeyboard' Simulator option to 'on'
[BaseDriver] Event 'resetStarted' logged at 1499938246409 (15:00:46 GMT+0530 (IST))
[XCUITest] Not scrubbing third party app in anticipation of uninstall
[BaseDriver] Event 'resetComplete' logged at 1499938246833 (15:00:46 GMT+0530 (IST))
[iOSLog] Starting iOS 10.3 simulator log capture
[iOSLog] System log path: /Users/gateway/Library/Logs/CoreSimulator/553BE51E-86C4-4C9C-AAE4-AD3DE2C7C89D/system.log
[BaseDriver] Event 'logCaptureStarted' logged at 1499938247200 (15:00:47 GMT+0530 (IST))
[XCUITest] Setting up simulator
[iOS] No reason to set locale
[iOS] No iOS / app preferences to set
[XCUITest] Simulator with udid '553BE51E-86C4-4C9C-AAE4-AD3DE2C7C89D' already booted
[BaseDriver] Event 'simStarted' logged at 1499938247737 (15:00:47 GMT+0530 (IST))
[XCUITest] Reset requested. Removing app with id 'com.facebooks.IntegrationsApps' from the device
[XCUITest] Installing /Users/gateway/desktop/IntegrationApp.app on Simulator with UUID '553BE51E-86C4-4C9C-AAE4-AD3DE2C7C89D'...
[XCUITest] The app has been installed successfully.
[BaseDriver] Event 'appInstalled' logged at 1499938253881 (15:00:53 GMT+0530 (IST))
[BaseDriver] Event 'wdaStartAttempted' logged at 1499938253887 (15:00:53 GMT+0530 (IST))
[XCUITest] Using WDA path: '/Volumes/DATA/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Volumes/DATA/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Running WebDriverAgent bootstrap script to install dependencies
[XCUITest] Fetching dependencies
[XCUITest] *** Downloading RoutingHTTPServer.framework binary at "v1.0.1"
[XCUITest] *** Skipped installing RoutingHTTPServer.framework binary due to the error:
[XCUITest] 	"Failed to write to /Volumes/DATA/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/iOS: Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “iOS” in the folder “Build”." UserInfo={NSFilePath=/Volumes/DATA/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/iOS, NSUnderlyingError=0x7ff137dca4b0 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}}"
[XCUITest] *** Checking out RoutingHTTPServer at "v1.0.1"
[XCUITest] Failed to check out repository into /Volumes/DATA/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/RoutingHTTPServer: Could not create working directory (Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “RoutingHTTPServer” in the folder “Checkouts”." UserInfo={NSFilePath=/Volumes/DATA/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/RoutingHTTPServer, NSUnderlyingError=0x7ff137dd7820 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}})
[BaseDriver] Event 'wdaStartFailed' logged at 1499938259737 (15:00:59 GMT+0530 (IST))
[XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 1
[XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Removing WDA application from device
[BaseDriver] Event 'wdaStartAttempted' logged at 1499938270448 (15:01:10 GMT+0530 (IST))
[XCUITest] Using WDA path: '/Volumes/DATA/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Volumes/DATA/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Running WebDriverAgent bootstrap script to install dependencies
[XCUITest] Fetching dependencies
[XCUITest] *** Downloading RoutingHTTPServer.framework binary at "v1.0.1"
[XCUITest] *** Skipped installing RoutingHTTPServer.framework binary due to the error:
[XCUITest] 	"Failed to write to /Volumes/DATA/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/iOS: Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “iOS” in the folder “Build”." UserInfo={NSFilePath=/Volumes/DATA/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/iOS, NSUnderlyingError=0x7fb2cf4d4d40 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}}"
[XCUITest] *** Checking out RoutingHTTPServer at "v1.0.1"
[XCUITest] Failed to check out repository into /Volumes/DATA/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/RoutingHTTPServer: Could not create working directory (Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “RoutingHTTPServer” in the folder “Checkouts”." UserInfo={NSFilePath=/Volumes/DATA/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/RoutingHTTPServer, NSUnderlyingError=0x7fb2cf4f38f0 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}})
[BaseDriver] Event 'wdaStartFailed' logged at 1499938273281 (15:01:13 GMT+0530 (IST))
[XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 1
[XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Removing WDA application from device
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 1
    at XCUITestDriver.quitAndUninstall$ (/Volumes/DATA/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:386:15)
    at tryCatch (/Volumes/DATA/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Volumes/DATA/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Volumes/DATA/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Volumes/DATA/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 1
    at XCUITestDriver.quitAndUninstall$ (/Volumes/DATA/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:386:15)
    at tryCatch (/Volumes/DATA/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Volumes/DATA/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Volumes/DATA/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Volumes/DATA/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 1
    at XCUITestDriver.quitAndUninstall$ (/Volumes/DATA/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:386:15)
    at tryCatch (/Volumes/DATA/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Volumes/DATA/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Volumes/DATA/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Volumes/DATA/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[HTTP] <-- POST /wd/hub/session 500 41985 ms - 252

**Comment by imurchie** [comment]
There is a space between `-x` and `Scripts`. 

The problem you are seeing the Appium logs is a permissions one: `You don’t have permission to save the file “iOS” in the folder “Build”`, etc.. It seems to be trying to write to `/Volumes/DATA/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage`.

**Comment by dpgraham** [comment]
Closing due to inactivity

**Comment by Dayanandmdr** [comment]
@jyotidgs1  i added package activity and unique developer account number which will be their in your developer account id as capability

**Comment by crspybits** [comment]
I am still having this problem Has it been resolved? Thanks.

**Comment by imurchie** [comment]
@crspybits Can you be more specific? What is "this problem" in your case? There are a few things going on in here.

**Comment by crspybits** [comment]
Thanks for your quick response! I was still getting this error `Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 1`. Digging around a little more, https://github.com/appium/appium/issues/8033 proved to have the solution. I was running the Appium app from my Mac OS desktop. I moved it to the /Applications folder and that solved the problem. 

IMO it could be useful for the Appium to check where it's launching from and tell the user bad things may happen if it's not launched from /Applications if it's not currently launching from there.

**Comment by imurchie** [comment]
It's being prioritized. Documentation does not seem to be enough.

https://github.com/appium/appium-desktop/issues/238

**Comment by venkatasar** [comment]
Thanks for your quick response! I was still getting this error Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 1. Digging around a little more, #8033 proved to have the solution. I was running the Appium app from my Mac OS desktop. I moved it to the /Applications folder and that solved the problem.

IMO it could be useful for the Appium to check where it's launching from and tell the user bad things may happen if it's not launched from /Applications if it's not currently launching from there.



This worked for me .. thanks a lot for this comment

**Comment by imurchie** [comment]
The Appium app (not the server) does this check in the most recent version.

**Comment by hemandhran** [comment]
Hi imurchie,

I am also facing the same issue. Please find the output of the command below, can you please help here.

+ set -e
+ export PATH=/Library/Frameworks/Python.framework/Versions/3.7/bin:/Users/devendrankrishnan/Downloads/adt-bundle-mac-x86_64-20140702/sdk/tools:/Users/devendrankrishnan/Downloads/adt-bundle-mac-x86_64-20140702/sdk/platform-tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
+ PATH=/Library/Frameworks/Python.framework/Versions/3.7/bin:/Users/devendrankrishnan/Downloads/adt-bundle-mac-x86_64-20140702/sdk/tools:/Users/devendrankrishnan/Downloads/adt-bundle-mac-x86_64-20140702/sdk/platform-tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
+ BOLD='\033[1m'
+ [[ ! -f Scripts/bootstrap.sh ]]
+ getopts ' i d D h ' option
+ case "$option" in
+ FETCH_DEPS=1
+ getopts ' i d D h ' option
+ [[ -n x ]]
+ fetch_and_build_dependencies
+ echo -e '\033[1mFetching dependencies'
Fetching dependencies
+ assert_has_carthage
+ command -v carthage
+ cmp -s Cartfile.resolved Carthage/Cartfile.resolved
+ [[ -n '' ]]
+ [[ -z x ]]
