### ISSUE TITLE
Appium-xcuitest-driver version 2.33.0 doesn't contain WebDriverAgent folder

### ISSUE THREAD

**Issue by mdolinin** [appium/appium#8683]
## The problem
Appium-xcuitest-driver version 2.33.0 doesn't contain WebDriverAgent folder
## Environment
* Appium version 1.6.5:
* Desktop OS/version used to run Appium: macOS 10.12.6
* Node.js version v7.1.0
* Mobile platform/version under test: iOS 10
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: CLI

## Code To Reproduce Issue [ Good To Have ]
```
npm i appium-xcuitest-driver@1.6.5
```
Check `node_modules/appium-xcuitest-driver/`
There no `WebDriverAgent` folder inside.
For appium-xcuitest-driver version 2.32.0
This issue is not reproduced.

**Comment by mykola-mokhnach** [comment]
@imurchie I was experiencing the same problem today while installing Appium@1.6.6-beta via npm@5.0.3 

Also got the following exception while removing the previous appium version:

```
npm WARN deprecated babel-core@5.8.24: Babel 5 is no longer being maintained. Upgrade to Babel 6.
npm WARN deprecated line-numbers@0.2.0: Copy its ~20 LOC directly into your code instead.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
Unhandled rejection Error: Argument #2: Expected string but got null align-text@^0.1.3 fetched in 50ms
    at addDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:515:3)
    at /usr/local/lib/node_modules/npm/lib/install/deps.js:463:5
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
    at Array.forEach (native)
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
    at loadDeps (/usr/local/lib/node_modules/npm/lib/install/deps.js:455:3)
    at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
    at /usr/local/lib/node_modules/npm/lib/install/and-finish-tracker.js:8:8
    at resolveBranchDeps.then (/usr/local/lib/node_modules/npm/lib/install/deps.js:419:11)
    at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/elf/.npm/_logs/2017-06-16T12_38_09_480Z-debug.log
```

nodejs version: 7.9.0

**Comment by imurchie** [comment]
Interesting. Reproducible.

**Comment by imurchie** [comment]
@mykola-mokhnach Ok. I guess report that to npm?

**Comment by mykola-mokhnach** [comment]
@imurchie might be already reported: https://github.com/npm/npm/issues/16665

**Comment by imurchie** [comment]
Ok. I've published `2.33.1` which fixes the issue.

Not sure why it happened. @dpgraham do you have any ideas?

**Comment by dpgraham** [comment]
I published `appium-xcuitest-driver` yesterday. I didn't make any changes to WebDriverAgent so I don't know what would have caused that.

**Comment by imurchie** [comment]
Very strange. Well, something to look out for.

**Comment by dpgraham** [comment]
And if I'm correct, all you did was republish, right?

**Comment by imurchie** [comment]
Well, to make sure, I did `rm -rf WebDriverAgent && git submodule update --init`. The re-published.
