### ISSUE TITLE
Lost session after wait for a minute

### ISSUE THREAD

**Issue by netd-eric** [appium/appium#8711]
## The problem

I wrote a test that needed to wait 1 minute then do actions on phone but it caused disconnect from the phone.

## Environment

Appium 1.6.5
Macos 10.12.5
* Node.js 7.1.0
* iPhone 6 with iOS 10.2.1
* Real device
* Appium CLI

## Details
After waited for a minute and call an Appium API, it diplayed: 

Traceback (most recent call last):
  File "/Users/eric/netdimensions/talentslate_appiumtests/TalentSlate.AppiumTests/appium_test/platform.py", line 184, in tearDown
    self.driver.quit()
  File "/Users/eric/.virtualenvs/talentslate_appiumtests/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 520, in quit
    self.execute(Command.QUIT)
  File "/Users/eric/.virtualenvs/talentslate_appiumtests/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Users/eric/.virtualenvs/talentslate_appiumtests/lib/python2.7/site-packages/appium/webdriver/errorhandler.py", line 29, in check_response
    raise wde
WebDriverException: Message: A session is either terminated or not started

**Comment by mykola-mokhnach** [comment]
Try to increase the value of **newCommandTimeout** capability. Also, for longer pauses it might be useful to create custom driver "pinger" and simply send any command to the driver every, say, 30 seconds to just keep it alive.

Please use Appium forum to ask questions.
