### ISSUE TITLE
Issue with babel

### ISSUE THREAD

**Issue by amusharraf** [appium/appium#8714]
## The problem

When I try to run appium I see the same error every time,

Error: Cannot find module 'babel-runtime/helpers/sliced-to-array'
at Function.Module._resolveFilename (module.js:339:15)
at Function.Module._load (module.js:290:25)
at Module.require (module.js:367:17)
at require (internal/module.js:16:19)
at Object. (/Applications/Appium.app/Contents/Resources/node_modules/appium/build/lib/main.js:7:22)
at Module._compile (module.js:413:34)
at Object.Module._extensions..js (module.js:422:10)
at Module.load (module.js:357:32)
at Function.Module._load (module.js:314:12)
at Function.Module.runMain (module.js:447:10)

The issue is also faced here: https://github.com/RallyTools/rally-node/issues/29 but there are no comments on that post maybe because where it was posted.

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.6-beta
* Desktop OS/version used to run Appium: Mac OS Sierra
* Node.js version (unless using Appium.app|exe): 6.11
* Mobile platform/version under test: iOS 10.2
* Real device or emulator/simulator: Simulator

**Comment by mykola-mokhnach** [comment]
I don't observe any issues while installing Appium with npm. Try to uninstall and install Appium again.
