### ISSUE TITLE
UI Automator2 Could not sign with default ceritficate

### ISSUE THREAD

**Issue by saikirankv** [appium/appium#8751]
## The problem

I'm running my tests on aws-device farm they are failing with Could not sign with default certificate

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/saikirankv/e6a343d431464502d20df20b936012c4

**Comment by imurchie** [comment]
This seems like a mis-configuration on the part of aws-device farm. Try running `/usr/lib/jvm/java-8-oracle/bin/java -jar /usr/local/avm/versions/1.6.5/node_modules/appium/node_modules/appium-adb/jars/sign.jar /usr/local/avm/versions/1.6.5/node_modules/appium/node_modules/appium-uiautomator2-driver/uiautomator2/appium-uiautomator2-server-v0.1.5.apk --override` to see if there is more information available.

**Comment by saikirankv** [comment]
I cannot run the above command, I can upload the tests and add requirements to it. Is there any other way to debug it.

**Comment by saikirankv** [comment]
they are using java-8

**Comment by jlipps** [comment]
I'm sorry; you'll need to engage their support team to figure out how they handle app signing for their cloud.

**Comment by arjunbm13** [comment]
@idxn how do u run from root/admin privilege in mac? i have already logged in as admin and i see same problem, but as above i am running it locally not on amazon-aws. ANy help will be appreciated. Recently i changed my automationname to uiautomator2 and i ran into this problem.
Here are the logs.
[RemoteTestNG] detected TestNG version 6.10.0
[TestNG] Running:
  /Users/arjun/viocautomation/Mobile/TestNGSuiteFiles/SmokeTest.xml

[51] [17/11/10 21:10:11] INFO BaseStep: ------------------initilizing----------------
[522] [17/11/10 21:10:11] INFO configuration.ConfigurationFactory: Trying to load configuration application.properties
[43] [17/11/10 21:10:11] INFO SmokeTest: Property File Initialized
[70] [17/11/10 21:10:12] INFO SmokeTest: Extended Cucumber Report Setup Done
[26] [17/11/10 21:10:12] INFO AppiumServer: Available Port is : 61931
[39] [17/11/10 21:10:15] INFO AppiumServer: Appium Server is starting.
[Appium] Welcome to Appium v1.7.1 (REV 93051b27d6886dae6df01544c86df579f21f6410)
[Appium] Non-default server args:
[Appium]   address: 127.0.0.1
[Appium]   port: 61931
[Appium]   log: /Users/arjun/viocautomation/Mobile/Logs/log.txt
[Appium] Appium REST http interface listener started on 127.0.0.1:61931
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.7.1","revision":"93051b27d6886dae6df01544c86df579f21f6410"}}
[HTTP] <-- GET /wd/hub/status 200 32 ms - 121 
[41] [17/11/10 21:10:44] INFO AppiumServer: Appium Server Started
[78] [17/11/10 21:10:44] INFO BaseStep: Launching Application
http://127.0.0.1:61931/wd/hub
[115] [17/11/10 21:10:44] INFO BaseStep: APPIUM will start with fullReset Mode
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"appPackage":"com.mobile.vioc.dev","app":"/Users/arjun/viocautomation/Mobile/Apps/Android/Valvoline_Dev_40001.apk","noReset":false,"unlockKey":"1234","deviceName":"BLR_Mob_92","fullReset":true,"appActivity":"com.mobile.vioc.ValvolineSplashScreenActivity","newCommandTimeout":0,"platformVersion":"7.0","automationName":"uiautomator2","unlockType":"pin","autoGrantPermissions":true,"unicodeKeyboard":true,"platformName":"Android","udid":"ce0716070c04943f02","resetKeyboard":true}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"appPackage":"com.mobile.vioc.dev","app":"/Users/arjun/viocautomation/Mobile/Apps/Android/Valvoline_Dev_40001.apk","noReset":false,"unlockKey":"1234","deviceName":"BLR_Mob_92","fullReset":true,"appActivity":"com.mobile.vioc.ValvolineSplashScreenActivity","newCommandTimeout":0,"platformVersion":"7.0","automationName":"uiautomator2","unlockType":"pin","autoGrantPermissions":true,"unicodeKeyboard":true,"platformName":"Android","udid":"ce0716070c04943f02","resetKeyboard":true},null,null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1510328445619 (21:10:45 GMT+0530 (IST))
[Appium] Creating new AndroidUiautomator2Driver (v0.6.5) session
[Appium] Capabilities:
[Appium]   appPackage: 'com.mobile.vioc.dev'
[Appium]   app: '/Users/arjun/viocautomation/Mobile/Apps/Android/Valvoline_Dev_40001.apk'
[Appium]   noReset: false
[Appium]   unlockKey: '1234'
[Appium]   deviceName: 'BLR_Mob_92'
[Appium]   fullReset: true
[Appium]   appActivity: 'com.mobile.vioc.ValvolineSplashScreenActivity'
[Appium]   newCommandTimeout: 0
[Appium]   platformVersion: '7.0'
[Appium]   automationName: 'uiautomator2'
[Appium]   unlockType: 'pin'
[Appium]   autoGrantPermissions: true
[Appium]   unicodeKeyboard: true
[Appium]   platformName: 'Android'
[Appium]   udid: 'ce0716070c04943f02'
[Appium]   resetKeyboard: true
[BaseDriver] The following capabilities were provided, but are not recognized by appium: unlockKey, unlockType.
[BaseDriver] Session created with session id: 87db969e-f4f3-4ece-b8d5-698cf188c8ab
[BaseDriver] Using local app '/Users/arjun/viocautomation/Mobile/Apps/Android/Valvoline_Dev_40001.apk'
[debug] [UiAutomator2] Checking whether app is actually present
[debug] [AndroidDriver] Getting Java version
[AndroidDriver] Java version is: 1.8.0_144
[ADB] Checking whether adb is present
[ADB] Using adb from /Users/arjun/Desktop/Android/android-sdk-macosx/platform-tools/adb
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[AndroidDriver] Using device: ce0716070c04943f02
[ADB] Checking whether adb is present
[ADB] Using adb from /Users/arjun/Desktop/Android/android-sdk-macosx/platform-tools/adb
[debug] [ADB] Setting device id to ce0716070c04943f02
[ADB] Getting device platform version
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/arjun/Desktop/Android/android-sdk-macosx/platform-tools/adb' with args: ["-P",5037,"-s","ce0716070c04943f02","shell","getprop","ro.build.version.release"]
[debug] [ADB] Current device property 'ro.build.version.release': 7.0
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/arjun/Desktop/Android/android-sdk-macosx/platform-tools/adb' with args: ["-P",5037,"-s","ce0716070c04943f02","shell","wm","size"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/arjun/Desktop/Android/android-sdk-macosx/platform-tools/adb' with args: ["-P",5037,"-s","ce0716070c04943f02","shell","getprop","ro.product.model"]
[debug] [ADB] Current device property 'ro.product.model': SM-G930F
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/arjun/Desktop/Android/android-sdk-macosx/platform-tools/adb' with args: ["-P",5037,"-s","ce0716070c04943f02","shell","getprop","ro.product.manufacturer"]
[debug] [ADB] Current device property 'ro.product.manufacturer': samsung
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/arjun/Desktop/Android/android-sdk-macosx/platform-tools/adb' with args: ["-P",5037,"-s","ce0716070c04943f02","shell","am","force-stop","io.appium.uiautomator2.server"]
[ADB] Checking whether aapt is present
[ADB] Using aapt from /Users/arjun/Desktop/Android/android-sdk-macosx/build-tools/19.1.0/aapt
[debug] [ADB] Getting install status for io.appium.uiautomator2.server
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/arjun/Desktop/Android/android-sdk-macosx/platform-tools/adb' with args: ["-P",5037,"-s","ce0716070c04943f02","shell","pm","list","packages","io.appium.uiautomator2.server"]
[debug] [ADB] App is not installed
[debug] [ADB] Getting install status for io.appium.uiautomator2.server.test
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/arjun/Desktop/Android/android-sdk-macosx/platform-tools/adb' with args: ["-P",5037,"-s","ce0716070c04943f02","shell","pm","list","packages","io.appium.uiautomator2.server.test"]
[debug] [ADB] App is not installed
[debug] [ADB] Checking app cert for /usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-driver/uiautomator2/appium-uiautomator2-server-v0.1.8.apk.
[debug] [ADB] App not signed with debug cert.
[debug] [ADB] Resigning apk.
[ADB] Error: Could not sign with default certificate. Original error spawn ENOTDIR
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at ADB.callee$0$0$ (../../../lib/tools/apk-signing.js:25:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
 Error: Could not sign with default certificate. Original error spawn ENOTDIR
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at ADB.callee$0$0$ (../../../lib/tools/apk-signing.js:25:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [UiAutomator2] Deleting UiAutomator2 server session
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: Error: Trying to proxy a session command without session id
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/arjun/Desktop/Android/android-sdk-macosx/platform-tools/adb' with args: ["-P",5037,"-s","ce0716070c04943f02","shell","am","force-stop","com.mobile.vioc.dev"]
[debug] [UiAutomator2] Capability 'fullReset' set to 'true', Uninstalling 'com.mobile.vioc.dev'
[debug] [ADB] Uninstalling com.mobile.vioc.dev
[debug] [ADB] Getting install status for com.mobile.vioc.dev
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/arjun/Desktop/Android/android-sdk-macosx/platform-tools/adb' with args: ["-P",5037,"-s","ce0716070c04943f02","shell","pm","list","packages","com.mobile.vioc.dev"]
[debug] [ADB] App is not installed
[ADB] com.mobile.vioc.dev was not uninstalled, because it was not present on the device
[debug] [ADB] Removing forwarded port socket connection: 8200 
[debug] [ADB] Running '/Users/arjun/Desktop/Android/android-sdk-macosx/platform-tools/adb' with args: ["-P",5037,"-s","ce0716070c04943f02","forward","--remove","tcp:8200"]
[debug] [ADB] Running '/Users/arjun/Desktop/Android/android-sdk-macosx/platform-tools/adb' with args: ["-P",5037,"-s","ce0716070c04943f02","forward","--remove","tcp:8200"]
[UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original error: 'Command '/Users/arjun/Desktop/Android/android-sdk-macosx/platform-tools/adb -P 5037 -s ce0716070c04943f02 forward --remove tcp\:8200' exited with code 1'; Stderr: 'error: listener not found
error: listener not found'; Code: '1''
[MJSONWP] Encountered internal error running command: Error: Could not sign with default certificate. Original error spawn ENOTDIR
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at ADB.callee$0$0$ (../../../lib/tools/apk-signing.js:25:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
[HTTP] <-- POST /wd/hub/session 500 10967 ms - 206 
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not sign with default certificate. Original error spawn ENOTDIR (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 11.46 seconds
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'BGMM104591.local', ip: '172.16.33.3', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_144'
Driver info: io.appium.java_client.android.AndroidDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:40)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:249)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:36)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:114)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:132)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:92)
	at com.photon.Valvoline.Utilities.BaseStep.InitiateApp(BaseStep.java:124)
	at com.photon.Valvoline.Utilities.BaseStep.LaunchApp(BaseStep.java:69)
	at com.photon.Valvoline.Trigger.SmokeTest.setup(SmokeTest.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.TestRunner.beforeRun(TestRunner.java:634)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
#Author : Arjun B M
@HamburgerTest
Feature: Hambuger menu
[25] [17/11/10 21:10:58] INFO LoginTestSteps: Skip Button Clicked
[673] [17/11/10 21:10:58] INFO CommonUtilities: Element is not present : com.mobile.vioc.dev:id/log_in~id
java.lang.NullPointerException
[206] [17/11/10 21:10:58] INFO BaseStep: Screen Shot taken
	at com.photon.Valvoline.Utilities.BaseStep.getScreenShotFile(BaseStep.java:183)
	at com.photon.Valvoline.Utilities.BaseStep.takeScreenShotonFailure(BaseStep.java:200)
	at com.photon.Valvoline.Trigger.SmokeTest.takeScreenShotonFailure(SmokeTest.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cucumber.runtime.Utils$1.call(Utils.java:40)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.Utils.invoke(Utils.java:34)
	at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)
	at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:224)
	at cucumber.runtime.Runtime.runHooks(Runtime.java:212)
	at cucumber.runtime.Runtime.runAfterHooks(Runtime.java:206)
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:46)
	at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:165)
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:63)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

  Scenario: VIOC_8.01_TC01 Verify user able to view the Hamburger menu expanded                                                                                                 # Hamburger.feature:5
    Given Tap on SKIP link on any onboarding screen                                                                                                                             # LoginTestSteps.Tap_on_SKIP_link()
    Then Verify user on Login or SignUp Page                                                                                                                                    # LoginTestSteps.verify_user_on_Login_Page()
      java.lang.AssertionError: expected [true] but found [false]
      	at org.testng.Assert.fail(Assert.java:94)
      	at org.testng.Assert.failNotEquals(Assert.java:513)
      	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
      	at org.testng.Assert.assertEquals(Assert.java:116)
      	at org.testng.Assert.assertEquals(Assert.java:305)
      	at org.testng.Assert.assertEquals(Assert.java:315)
      	at com.photon.Valvoline.Utilities.CommonUtilities.isElementPresentVerification(CommonUtilities.java:674)
      	at com.photon.Valvoline.StepLibrary.LoginTestStepLibrary.validateUserOnLoginPage(LoginTestStepLibrary.java:18)
      	at com.photon.Valvoline.StepDefinition.LoginTestSteps.verify_user_on_Login_Page(LoginTestSteps.java:19)
      	at ✽.Then Verify user on Login or SignUp Page(Hamburger.feature:7)

    Then Tap on Login button                                                                                                                                                    # LoginTestSteps.tap_on_Login_button()
    Then user enter Vioc email id "test@gmail.com"                                                                                                                              # LoginTestSteps.user_enter_sentara_id(String)
    And password "Photon@123$"                                                                                                                                                  # LoginTestSteps.password(String)
    Then click on the sign in button                                                                                                                                            # LoginTestSteps.click_on_the_sign_in_button()
    Then validate user on Dashboard page                                                                                                                                        # LoginTestSteps.validate_user_on_home_page()
    Then Tap on Hamburger menu                                                                                                                                                  # HamburgerMenuTestSteps.tap_on_Hamburger_menu()
    Then Verify all the components of Hamburger menu displayed                                                                                                                  # HamburgerMenuTestSteps.verify_all_the_components_of_Hamburger_menu_displayed_and_close_the_hamburger_menu()
    Then Tap on Settings on Hamburger menu and verify all the components                                                                                                        # HamburgerMenuTestSteps.tap_on_Settings_on_Hamburger_menu_and_verify_all_the_components()
    Then Modify the Settings like enable push notification and press back and observe Settings should be saved automatically when user navigate back and come back to hamburger # HamburgerMenuTestSteps.modify_the_Settings_like_enable_push_notification_and_press_back_and_observe_Settings_should_be_saved_automatically_when_user_navigate_back()
    Then Tap on Hamburger menu                                                                                                                                                  # HamburgerMenuTestSteps.tap_on_Hamburger_menu()
    Then Tap on FAQs link on Hamburger menu and verify User should be able to expand the subcategory items by tapping the chevron and view the content                          # HamburgerMenuTestSteps.tap_on_FAQs_link_on_Hamburger_menu_and_verify_User_should_be_able_to_expand_the_subcategory_items_by_tapping_the_chevron_and_view_the_content()
    Then Tap on Hamburger menu                                                                                                                                                  # HamburgerMenuTestSteps.tap_on_Hamburger_menu()
    Then Tap on My Coupons on hamburger menu and Check the details on My Coupons page and tap on Tap for details CTA                                                            # HamburgerMenuTestSteps.tap_on_My_Coupons_on_hamburger_menu_and_Check_the_details_on_My_Coupons_page_and_tap_on_Tap_for_details_CTA()
    Then Verify the components of coupon data displayed and close the coupon details page                                                                                       # DashboardTestSteps.verifyComponents()
    Then Tap on My coupons page back button                                                                                                                                     # HamburgerMenuTestSteps.tap_on_My_coupons_page_back_button()
    Then Tap on Hamburger menu                                                                                                                                                  # HamburgerMenuTestSteps.tap_on_Hamburger_menu()
    Then Tap on Call Us menu option and accept                                                                                                                                  # HamburgerMenuTestSteps.tap_on_Call_Us_menu_option_and_accept()
    Then Tap on call button and click call                                                                                                                                      # HamburgerMenuTestSteps.tap_on_call_button_and_click_call()

Failed scenarios:
Hamburger.feature:5 # Scenario: VIOC_8.01_TC01 Verify user able to view the Hamburger menu expanded

1 Scenarios (1 failed)
20 Steps (1 failed, 18 skipped, 1 passed)
0m0.302s

java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.photon.Valvoline.Utilities.CommonUtilities.isElementPresentVerification(CommonUtilities.java:674)
	at com.photon.Valvoline.StepLibrary.LoginTestStepLibrary.validateUserOnLoginPage(LoginTestStepLibrary.java:18)
	at com.photon.Valvoline.StepDefinition.LoginTestSteps.verify_user_on_Login_Page(LoginTestSteps.java:19)
	at ✽.Then Verify user on Login or SignUp Page(Hamburger.feature:7)

[85] [17/11/10 21:10:59] INFO SmokeTest: Android is Quit

===============================================
Smoke Test
Total tests run: 1, Failures: 1, Skips: 0
===============================================

**Comment by idxn** [comment]
@arjunbm13 Could you please try executing command with @imurchie stated above and post result here? BTW, next time i think you should post the log to gist instead of directly post to the thread.

**Comment by KrishnaprabhaSNaik** [comment]
Hi All, I am also facing the similar issue. As @imurchie told I ran the below command and the result is this.
command:
`/usr/lib/jvm/java-8-oracle/bin/java -jar /usr/lib/node_modules/appium/node_modules/appium-adb/jars/sign.jar /usr/lib/node_modules/appium/node_modules/appium-uiautomator2-driver/uiautomator2/appium-uiautomator2-server-v0.1.5.apk --override`
result:
`Exception in thread "main" java.lang.RuntimeException: Unable to rename input apk. /usr/lib/node_modules/appium/node_modules/appium-uiautomator2-driver/uiautomator2/appium-uiautomator2-server-v0.1.5.apk`
	at s.Sign.sign(Sign.java:421)
	at s.Sign.main(Sign.java:532)

**Comment by idxn** [comment]
@KrishnaprabhaSNaik Could you please start appium with sudo command and try again?

**Comment by KrishnaprabhaSNaik** [comment]
@idxn I tried also with sudo appium command. But it also end up with the same error. Finally I have figured out the problem. It was because of a bug in the "apk-signing.js" file residing in location "/usr/lib/node_modules/appium/node_modules/appium-adb/build/lib/tools"
Please chk this link for editing the file and for more details.
[https://discuss.appium.io/t/appium-1-7-1-canot-singin-appium-uiautomator2-server-debug-androidtest-apk/19233/4](url)

**Comment by KrishnaprabhaSNaik** [comment]
@arjunbm13 To run as root start the appium with `sudo appium` command.

**Comment by idxn** [comment]
@KrishnaprabhaSNaik thanks for the info :D

**Comment by idxn** [comment]
@hameno which version do you face the issue? do you use the appium desktop?

**Comment by hameno** [comment]
@idxn see #10130

**Comment by sevetseh28** [comment]
@idxn  how do you run the installed Appium Desktop as root on linux?

**Comment by idxn** [comment]
@sevetseh28 I don't use the appium desktop. I use the one from npm. The reason I asked hameno just because it might need  other solution. Anyway, installing it with user priviledge and running it with sudo might solve the issue.

**Comment by jgreen210** [comment]
You shouldn't use sudo to run appium (i.e "run it as root").  That's since it'll likely sprinkle root-owned files all over your home directory, breaking other things (since they won't be able to replace the root-owned files). It's bad from a "security" point of view too.

The proper fix is to copy the file somewhere else, somewhere that you have write access to. Appium should probably do this for us (and I'm sure they'd love to get a PR for this). Otherwise, do it yourself before running appium.

**Comment by jgreen210** [comment]
Where's an appropriate place to the souce code to implement copying the apk? Does appium have a temporary directory that you can configure and that it cleans up?

**Comment by jgreen210** [comment]
This wasn't a problem for appium 1.7.2 - it worked if you gave it a read-only apk. (I've just upgraded from 1.7.2 to 1.8.1, missing out any intermediate releases.) Did 1.7.2 copy the apk? Did it not sign it? Did it fail to sign it, but carry on and work (for me) anyway?

**Comment by jgreen210** [comment]
Better still, appium should sign the apk into a new location in a temporary directory it owns and manages, only doing it if the signed apk is older than the apk appium is given.
