### ISSUE TITLE
Error: Could not determine iOS SDK version:command 'xcrun' not found. Is it installed?

### ISSUE THREAD

**Issue by vatsa88** [appium/appium#8756]
## The problem

I am getting below exception on running the appium for iphone device .

Error: Could not determine iOS SDK version:command 'xcrun' not found. Is it installed?

Additional info from my laptop
i see xcode and xcode-select is installed already. 
1. xcrun -version gives me 
xcrun version 31

2. xcrun  --show -sdk-version
10.12

## Environment
Appium Version -1.1.0 beta 3 (Server 1.6.5 )
mac machine  - OS X El Capitan 10.11
Device - Iphone 7+
ioS version - 10.3 (Real Device)
Xcode version - 8.2.1 (8C1002)

## Appium logs

[Appium] Welcome to Appium v1.6.5

[Appium] Non-default server args:

[Appium]   address: 127.0.0.1

[Appium] Appium REST http interface listener started on 127.0.0.1:4723

[HTTP] --> GET /wd/hub/sessions {}

[MJSONWP] Calling AppiumDriver.getSessions() with args: []

[MJSONWP] Responding to client with driver.getSessions() result: []

[HTTP] <-- GET /wd/hub/sessions 200 11 ms - 40 

[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"automationName":"XCUITest","browserName":"safari","deviceName":"iPhone 7","platformName":"iOS","platformVersion":"10.3","udid":"468cb32c2cc360ce8ce7abc5722de663f8959508","newCommandTimeout":0,"connectHardwareKeyboard":true}}

[MJSONWP] Calling AppiumDriver.createSession() with args: [{"automationName":"XCUITest","browserName":"safari","deviceName":"iPhone 7","platformName":"iOS","platformVersion":"10.3","udid":"468cb32c2cc360ce8ce7abc5722de663f8959508","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]

[BaseDriver] Event 'newSessionRequested' logged at 1498710747291 (10:02:27 GMT+0530 (IST))

[Appium] Creating new XCUITestDriver (v2.30.0) session

[Appium] Capabilities:

[Appium]   automationName: 'XCUITest'

[Appium]   browserName: 'safari'

[Appium]   deviceName: 'iPhone 7'

[Appium]   platformName: 'iOS'

[Appium]   platformVersion: '10.3'

[Appium]   udid: '468cb32c2cc360ce8ce7abc5722de663f8959508'

[Appium]   newCommandTimeout: 0

[Appium]   connectHardwareKeyboard: true

[XCUITest] XCUITestDriver version: 2.30.0

[BaseDriver] Session created with session id: f36e61a9-18f1-4728-9876-5fb0d945e8a9

[XCUITest] Xcode version set to '8.2.1' 

[XCUITest] Error: Could not determine iOS SDK version: Command 'xcrun' not found. Is it installed?

    at Object.wrappedLogger.errorAndThrow (/Applications/Appium 2.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:63:13)

    at getAndCheckIosSdkVersion$ (/Applications/Appium 2.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/utils.js:75:9)

    at tryCatch (/Applications/Appium 2.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)

    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium 2.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)

    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Applications/Appium 2.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)

    at GeneratorFunctionPrototype.invoke (/Applications/Appium 2.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)

    at process._tickCallback (internal/process/next_tick.js:103:7)

 Error: Could not determine iOS SDK version: Command 'xcrun' not found. Is it installed?

    at Object.wrappedLogger.errorAndThrow (/Applications/Appium 2.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:63:13)

    at getAndCheckIosSdkVersion$ (/Applications/Appium 2.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/utils.js:75:9)

    at tryCatch (/Applications/Appium 2.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)

    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium 2.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)

    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Applications/Appium 2.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)

    at GeneratorFunctionPrototype.invoke (/Applications/Appium 2.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)

    at process._tickCallback (internal/process/next_tick.js:103:7)

DesiredCapabilites used :
{
  "udid": "468cb32c2cc360ce8ce7abc5722de663f8959508",
  "platformName": "iOS",
  "platformVersion": "10.3",
  "deviceName": "iPhone 7",
  "browserName": "safari",
  "automationName": "XCUITest"
}

**Comment by mykola-mokhnach** [comment]
1. Remove unnecessary space from appium application name
2. Make sure you have the folder, where xcrun binary is located, in the process PATH. One may use the `ps -wwE -p <PID>` command to see the list of process env variables on Mac OS.

**Comment by mykola-mokhnach** [comment]
Closed since there is no activity

**Comment by keshavwy** [comment]
@mykola-mokhnach I am also facing similar kind of issue. Can you please guide me how to resolve this?

**Comment by Thevakajan** [comment]
![1](https://user-images.githubusercontent.com/43900489/54179525-fd8f1b00-44be-11e9-8c5f-49eef94f3786.png)

**Comment by keshavwy** [comment]
@Thevakajan 

Can you tell me on what scenario you are seeing this error? Are you trying to run any testng.xml file on eclipse?
