### ISSUE TITLE
Connection to WDA timed out

### ISSUE THREAD

**Issue by lohitsb** [appium/appium#8764]
After launching the application, It is not finding the elements and giving an error "Connection to WDA timed out". 

I am using Xcode 8.3.3
iOS Device with 10.3

Attached the code and Logs for the same.

**My Code:**

package test2.test2;

import java.net.MalformedURLException;
import java.net.URL;

import org.openqa.selenium.remote.DesiredCapabilities;
import org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler;
import org.testng.annotations.Test;

import io.appium.java_client.AppiumDriver;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.ios.IOSDriver;

public class Sample {
	
	@Test
	public void test1() throws MalformedURLException, InterruptedException
	{
		DesiredCapabilities capabilities=new DesiredCapabilities();
		capabilities.setCapability("platformName", "iOS");
		capabilities.setCapability("platformVersion", "10.3.1");
        capabilities.setCapability("deviceName", "MyTwc-iPhone 7");
        capabilities.setCapability("udid", "3f1f389017eee1253e907ce51cb4cf76a596115f");
        capabilities.setCapability("bundleId", "com.timewarnercable.mytwc");
      //  capabilities.setCapability("App", "http://bit.ly/2t2O5I9");
        capabilities.setCapability("automationName", "XCUITest");
        //capabilities.setCapability("xcodeOrgId", "RLWCK255Y4");
        capabilities.setCapability("xcodeLog", true);
       // capabilities.setCapability("xcodeSigningId", "Lohitaksh Belaladavar (RLWCK255Y4)");
        //capabilities.setCapability("updatedWDABundleId", "com.broadsoft.appiumtest");
        capabilities.setCapability("xcodeConfigFile","/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Config.xcconfig");
        capabilities.setCapability("wdaConnectionTimeout", 600000);

        System.out.println("Device identified");

      //  capabilities.setCapability("appPackage", "com.mytwc.common.resource");
        //capabilities.setCapability("appActivity", "com.mportal.twcframework.ui.SplashActivity");

        System.out.println("Activity and package added");

         AppiumDriver driver = new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub/"), capabilities);

        System.out.println("Connected to Appium Server");
        
        Thread.sleep(30);
        
        //androidDriver.findElementByAccessibilityId("Allow").click();
        driver.findElementByAccessibilityId("Sign In").click();
        
        
	}

}

**Attached the Appium Logs:**

[wda_time_out.docx](https://github.com/appium/appium/files/1114915/wda_time_out.docx)

**Comment by mykola-mokhnach** [comment]
Please attach the log as a gist or as a text file. docx files are not appreciated.

**Comment by lohitsb** [comment]
Sorry, Now i have attached the logs as .txt
[WDA_TimeOUT.txt](https://github.com/appium/appium/files/1115180/WDA_TimeOUT.txt)

**Comment by mykola-mokhnach** [comment]
Nothing suspicious in the Appium log. Probably, the device log contains more information

**Comment by amias-channer** [comment]
I saw two things of interest in your log: 

1) 
[debug] [iProxy] recv failed: Operation not permitted

Have you got a restrictive firewall running ? When I run Appium on this Mac I get occasional popups asking for network access for ruby (my scripts are in ruby). 

2)
Closing session, cause was 'New Command Timeout of 60 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'

I usually run with newCommandTimeout = 360 in my caps because this can take a while even over localhost, although it looks like it was a permissions thing

**Comment by lohitsb** [comment]
Nope, i never get any firewall restriction pop up.

I have tried "capabilities.setCapability("newCommandTimeout", 380);", but still i am getting same error.


Please let me know do i need to check anything?

**Comment by jlipps** [comment]
@lohitsb can you re-run the appium server with `--log-timestamp` so we can see the flow of time? and make sure you're using the latest appium beta. then show us the logs.

**Comment by jlipps** [comment]
closing due to inactivity

**Comment by deepikashekar37** [comment]
I am also facing same issue.

Environment
Appium - 1.8.1
xcode - 9.4
real iOS device version - 11.4

**Appium logs **

Responding to client with driver.getContexts() result: ["NATIVE_APP","WEBVIEW_1"]
[HTTP] <-- GET /wd/hub/session/eee59416-4df8-4cd9-8986-41571c960409/contexts 200 9 ms - 36
[HTTP]
[HTTP] --> POST /wd/hub/session/eee59416-4df8-4cd9-8986-41571c960409/context
[HTTP] {"name":"WEBVIEW_1"}
[debug] [W3C] Calling AppiumDriver.setContext() with args: ["WEBVIEW_1","eee59416-4df8-4cd9-8986-41571c960409"]
[debug] [XCUITest] Executing command 'setContext'
[debug] [iOS] Attempting to set context to 'WEBVIEW_1'
[debug] [RemoteDebugger] WebKit debugger web socket connected to url: ws://localhost:27753/devtools/page/1
[debug] [RemoteDebugger] Starting to listen for JavaScript console
[debug] [RemoteDebugger] Sending WebKit data: {"method":"Console.enable","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true}}
[debug] [RemoteDebugger] Webkit response timeout: 50000
[debug] [RemoteDebugger] Receiving WebKit data: '{"result":{},"id":1}'
[debug] [RemoteDebugger] Found handler for message '1'
[debug] [RemoteDebugger] WebKit debugger got a message for 'Console.enable' and have no handler, doing nothing.
[debug] [XCUITest] Connection to WDA timed out
[debug] [iProxy] recv failed: Operation not permitted
[W3C] Encountered internal error running command: TimeoutError: operation timed out
[W3C] at afterTimeout (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/release/timers.js:46:19)
[W3C] at Timeout.timeoutTimeout [as _onTimeout] (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/release/timers.js:76:13)
[W3C] at ontimeout (timers.js:466:11)
[W3C] at tryOnTimeout (timers.js:304:5)
[W3C] at Timer.listOnTimeout (timers.js:267:5)

Can anyone please help on this ?

**Comment by ashoksqa** [comment]
Me also facing the same same issue. Any update?

**Comment by vinaybalepur** [comment]
I have updated to the latest version and am still facing this issue. This is a blocker for our automation execution. Any help would be greatly appreciated.

**Comment by deepikashekar37** [comment]
I was facing the same issue but after upgrading appium to 1.8.2-beta issue solved. Also upgrade java client

**Comment by vinaybalepur** [comment]
I upgraded to 1.8.2-beta. I started getting "Unhandled endpoint" from AppiumDriver.getPageSource(). Then downgraded to 1.8.2. Now am not even able to connect to hub. The xcode version is 9.2. The java client is 6.1.0

**Comment by deepikashekar37** [comment]
Can you please send your desired capabilities

**Comment by vinaybalepur** [comment]
Following is the capabilities.
"udid":"device_udid",
"app":"app_path",
"server:CONFIG_UUID":"74248ac2-26a0-4eb9-8f6c-e205e5efb67c", //this is not provided but some how this is picked up and shown in appium logs
"commandTimeouts":35000,
"newCommandTimeout":1000,
"platformVersion":"9.3",
"automationName":"XCUITest",
"platformName":"ios",
"deviceName":"iPhone",
"iosInstallPause":10000,
"usePrebuiltWDA":true,
"device":"iphone",

**Comment by deepikashekar37** [comment]
Try by setting automation name capability

**Comment by deepikashekar37** [comment]
I mean .....automationName as UIAutomator2....

**Comment by vinaybalepur** [comment]
Thanks for the support. How will adding this capability help?

**Comment by SokhomRatanak** [comment]
I am having the same issue.
Appium 1.9.1
iOS 12.0
xCode 10.0 beta 4

**Comment by akhand-pratap2807** [comment]
I am getting same issue with same device configuration

**Comment by arronhai** [comment]
@lohitsb  Excuse me, have you solved this problem? i have the same problem now , i tried a lot of solutions and they didn't work

**Comment by arronhai** [comment]
@lohitsb my brother, i have tried the solution that you told me, actualy ,it doesn't work for my.But when i change the listening port  on my appium ,it work for me ! How amazing!

**Comment by Sabesna** [comment]
@lohitsb I face the same issue with latest Appium. 
I have tried all the suggestions stated above like,

Changing Appium port, Replacing Appium with Beta version of it and even redoing the full set up. I executed a Native application automation a couple of days back on a different iPAD device and did not face any issue. This is new to me. Please suggest me how you solved the issue. 

I apologize for not posting any LOG information, I do not have access to them at this moment. I will update the LOG file ASAP.

Thanks in advance

**Comment by arronhai** [comment]
you need to open the file which name is 'webdriveragent' with xcode , and then click  'test' . finally, open your appium with 8111 port

**Comment by Sabesna** [comment]
> you need to open the file which name is 'webdriveragent' with xcode , and then click 'test' . finally, open your appium with 8111 port

I tried the above mentioned steps and still the issue pertains.

Could anyone please mention the working combination for iOS automation like,

iOS Version: ?
MacOS Version: ?
Appium Version: ?
Xcode Version: ?

Please respond 

Thanks in advance

**Comment by SukumarKumar** [comment]
Hi deepikashekar37 , arronhai and imurchie , I facing the similar issues. Could you please share the working combination for iOS automation. Please do the needful.

**Comment by aureliendelrue** [comment]
Hi ! i have this error too with Appium 1.10.0, Xcode 10.1 and iOS 12.1.X.
Any news ?

**Comment by gurender1983** [comment]
Hi
I have this error too with Appium 1.13.0, Xcode 10.2.1 and iOS 12.1.
Anyone have any solution. Please update...

**Comment by pavelanihimovsky** [comment]
Hi

**Comment by testingxpertshyd** [comment]
Hi @mykola-mokhnach 
I have this error too with Appium 1.13.0, Xcode 10.2.1 and iOS 12.2 on Mac 10.14.4.
Anyone have any solution. Please update...

**Comment by kartikjain12** [comment]
Also facing this Issue in Appium 1.14.

**Comment by swapnilgorey** [comment]
Please try removing the webdriver agent folder from your appium folder and replacing it with this 
https://github.com/facebookarchive/WebDriverAgent.
continue with rest of steps for setting up appium for iOS.
