### ISSUE TITLE
Error when starting Appium server from code

### ISSUE THREAD

**Issue by vjmaiky** [appium/appium#8811]
## The problem
Error when trying to start appium from code

## Environment
Windows 8.1 Enterprise x64

* Appium version (or git revision) that exhibits the issue: 1.6.6-beta.2
* Last Appium version that did not exhibit the issue (if applicable): 1.4.13
* Node.js version (unless using Appium.app|exe): 6.11.0
* Mobile platform/version under test: Android
* Real device or emulator/simulator: GennyMotion Emulator

## Details

Basically i`m trying to revive a Jenkins job which is using an old version of Appium.
In config.jason i updated the paths to the new appium and node js.

{
	"appium_location":"C:/Users/JenKins/AppData/Roaming/npm/node_modules/appium/build/lib/main.js",
	"node_location":"C:/nodejs/node.exe",
	"bootstrap_port":"4765",
	"chrome_driver_port":"9525",
	"platformName":"android",
	"unicodeKeyboard":true,
	"deviceName":"Nexus 7 Geny",
	"deviceType":"Tablet",
	"appLocation":"C:/Appium/apk/apk.apk",
	"deviceUDID":"192.168.177.101:5555",
	"newCommandTimeout":600,
	"deviceOrientation":"PORTRAIT",
	"fullReset":false,
	"noReset":false,
	"automationName":"Appium"
}

Everything works OK until starting the appium server:

2017-07-10 11:12:56 INFO  Hooks:322 - Device found, no need to restart.
2017-07-10 11:12:56 INFO  Hooks:349 - restartAdbIfNeeded END
2017-07-10 11:12:56 INFO  Hooks:108 - Hook1_END
2017-07-10 11:12:56 INFO  Hooks:113 - Hook2_START
2017-07-10 11:12:56 INFO  AndroidDriver_Static:61 - Getting New Appium Session
2017-07-10 11:12:56 INFO  ThreadEmma:11 - Sleeping for milliseconds: 5000
2017-07-10 11:13:01 INFO  AndroidDriver_Static:54 - New Appium service: http://0.0.0.0:24067/wd/hub

C:\Users\JenKins\AppData\Roaming\npm\node_modules\appium\node_modules\appium-support\build\lib\fs.js:155
      throw _iteratorError;
            ^
TypeError: fn must be a function

    See http://goo.gl/916lJJ

    at Function.Promise.promisify (C:\Users\JenKins\AppData\Roaming\npm\node_modules\appium\node_modules\bluebird\js\main\promisify.js:268:15)
    at Object.<anonymous> (C:\Users\JenKins\AppData\Roaming\npm\node_modules\appium\node_modules\appium-support\build\lib\fs.js:143:35)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\JenKins\AppData\Roaming\npm\node_modules\appium\node_modules\appium-support\build\lib\tempdir.js:12:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\JenKins\AppData\Roaming\npm\node_modules\appium\node_modules\appium-support\build\index.js:11:19)
    at Module._compile (module.js:456:26)

ava.lang.InterruptedException
        at java.lang.ProcessImpl.waitFor(ProcessImpl.java:451)
        at hudson.Proc$LocalProc.join(Proc.java:320)
        at hudson.tasks.CommandInterpreter.join(CommandInterpreter.java:154)
        at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:108)
        at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:65)
        at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
        at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBui
ld.java:779)
        at hudson.model.Build$BuildExecution.build(Build.java:205)
        at hudson.model.Build$BuildExecution.doRun(Build.java:162)
        at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.j
ava:534)
        at hudson.model.Run.execute(Run.java:1728)
        at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
        at hudson.model.ResourceController.execute(ResourceController.java:98)
        at hudson.model.Executor.run(Executor.java:404)

ERROR StatusLogger No log4j2 configuration file found. Using default configurati
on: logging only errors to the console.

I read on forums and understood that it is a node problem. Installed the newest version, but the problem persists. What i`m missing here?

**Comment by mykola-mokhnach** [comment]
Make sure nodejs executable, which interpret appium.js main script is correct. Maybe, there are still some leftovers from the older installation on the system.

**Comment by vjmaiky** [comment]
managed to make it start on phone; but on tablet it`s still not working:

2017-07-10 14:23:31 INFO  Hooks:322 - Device found, no need to restart.
2017-07-10 14:23:31 INFO  Hooks:349 - restartAdbIfNeeded END
2017-07-10 14:23:31 INFO  Hooks:108 - Hook1_END
2017-07-10 14:23:31 INFO  Hooks:113 - Hook2_START
2017-07-10 14:23:31 INFO  AndroidDriver_Static:61 - Getting New Appium Session
2017-07-10 14:23:31 INFO  ThreadEmma:11 - Sleeping for milliseconds: 5000
2017-07-10 14:23:36 INFO  AndroidDriver_Static:54 - New Appium service: http://0.0.0.0:16714/wd/hub
[ADB] Error: Remote install failed: pkg: /data/local/tmp/e26aa3702221d4047ba302f433c175eb.apk

Failure [INSTALL_FAILED_DEXOPT]
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at ADB.callee$0$0$ (../../../lib/tools/apk-utils.js:188:9)
    at tryCatch (C:\Users\JenKins\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\JenKins\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\JenKins\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\JenKins\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 Error: Remote install failed: pkg: /data/local/tmp/e26aa3702221d4047ba302f433c175eb.apk

**Comment by imurchie** [comment]
There should be some corresponding error in the device logs. Without them it is not possible to say what went wrong, other than it is something at the Android level.
