### ISSUE TITLE
I get an error: MJSONWP] Encountered internal error running command: Error: Error occured while starting App. Original error: com.disney.wdpro.android.mdx.activities.LoaderActivity or 

### ISSUE THREAD

**Issue by vladbelo** [appium/appium#8826]
## The problem

My app turns on on real device before scrollTo()  commands starts then the app shuts off.  

## Environment

* Appium version 1.6
* Desktop OS/version used to Windows 10 
*Selenium.Java 2.5
* Real device
eclipse
junit
* 

#**# Link to Appium logs**

[UiAutomator] UiAutomator shut down normally
[UiAutomator] Moving to state 'stopped'
[ADB] Attempting to kill all uiautomator processes
[ADB] Getting all processes with uiautomator
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\vovan\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","IRN7HITKLFOFVKK7","shell","ps"]
[ADB] No uiautomator process found to kill, continuing...
[UiAutomator] Moving to state 'stopped'
[Logcat] Stopping logcat capture
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\vovan\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","IRN7HITKLFOFVKK7","shell","am","force-stop","io.appium.unlock"]
[AndroidDriver] Not cleaning generated files. Add `clearSystemFiles` capability if wanted.
[MJSONWP] Encountered internal error running command: Error: Error occured while starting App. Original error: com.disney.wdpro.android.mdx.activities.LoaderActivity or com.disney.mdx.wdw.google.com.disney.wdpro.android.mdx.activities.LoaderActivity never started
    at Object.wrappedLogger.errorAndThrow (C:\Users\vovan\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:63:13)
    at ADB.callee$0$0$ (C:\Users\vovan\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\apk-utils.js:79:9)
    at tryCatch (C:\Users\vovan\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\vovan\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\vovan\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\vovan\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 66367 ms - 339 

## Code To Reproduce Issue [ Good To Have ]

import static org.junit.Assert.*;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;

import org.junit.After;
import org.junit.Test;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.touch.TouchActions;
import org.openqa.selenium.remote.DesiredCapabilities;

import io.appium.java_client.MobileElement;
import io.appium.java_client.SwipeElementDirection;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.remote.MobileCapabilityType;
import io.appium.java_client.remote.MobilePlatform;

public class desiredcap {
	AndroidDriver driver;
	
	
	@Test
public void test() throws MalformedURLException, InterruptedException {
		File appDir = new File("src");
		File app = new File(appDir, "com.disney.mdx.wdw.google.apk");
		
		DesiredCapabilities cap = new DesiredCapabilities();
		cap.setCapability(MobileCapabilityType.PLATFORM_NAME, MobilePlatform.ANDROID);
		cap.setCapability(MobileCapabilityType.DEVICE_NAME, "Android Device");
		cap.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, "50");
		cap.setCapability(MobileCapabilityType.APP, app.getAbsolutePath());
		
		AndroidDriver driver = new AndroidDriver(new URL("http://169.254.159.242:4723/wd/hub"), cap);
		driver.scrollTo("Get Started");
		TouchActions t = new TouchActions(driver);
		WebElement abc = driver.findElementById("com.disney.mdx.wdw.google:id/tutorial_button");
		t.singleTap(abc).perform();
		
		
		
		Thread.sleep(100000);
		driver.quit();

**Comment by mykola-mokhnach** [comment]
You must provide a correct value to **appWaitActivity** capability

**Comment by vladbelo** [comment]
What type of parameters you put in appWaitActivity?

**Comment by vladbelo** [comment]
How do you find appActivityPackage

**Comment by vladbelo** [comment]
Do you know why my app wont run on emulator I installed it on emulator?

Failure [INSTALL_FAILED_OLDER_SDK]
    at Object.wrappedLogger.errorAndThrow (C:\Users\vovan\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:63:13)
    at ADB.callee$0$0$ (C:\Users\vovan\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\apk-utils.js:186:9)
    at tryCatch (C:\Users\vovan\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\vovan\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\vovan\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\vovan\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[HTTP] <-- POST /wd/hub/session 500 23523 ms - 257

**Comment by mykola-mokhnach** [comment]
Sorry, but this is the place where we solve issues. There is [another place](https://discuss.appium.io) for asking questions
