### ISSUE TITLE
ERROR  deviceName can't be blank

### ISSUE THREAD

**Issue by AlexDingSZ** [appium/appium#8829]
## The problem
In order to get Android toast text, I add a line code  before  the lines start android app, 
the line is :
capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.ANDROID_UIAUTOMATOR2);

I run same script on different Win7 OS , One can run successfully,  another run with Error as below:

org.openqa.selenium.SessionNotCreatedException: A new session could not be created. Details: The desiredCapabilities object was not valid for the following reason(s):  deviceName can't be blank, (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.3.0', revision: 'b526bd5b41', time: '2017-03-07 19:26:04 +0000'
System info: host: 'windows7', ip: '192.168.59.1', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_45'
Driver info: driver.version: AndroidDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:216)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:168)
	at io.appium.java_client.remote.AppiumProtocolHandShake.createSession(AppiumProtocolHandShake.java:161)
	at io.appium.java_client.remote.AppiumProtocolHandShake.lambda$2(AppiumProtocolHandShake.java:88)
	at io.appium.java_client.remote.AppiumProtocolHandShake$$Lambda$5/23545302.get(Unknown Source)
	at java.util.Optional.orElseGet(Optional.java:267)
	at io.appium.java_client.remote.AppiumProtocolHandShake.lambda$0(AppiumProtocolHandShake.java:83)
	at io.appium.java_client.remote.AppiumProtocolHandShake$$Lambda$4/10853795.get(Unknown Source)
	at java.util.Optional.orElseGet(Optional.java:267)
	at io.appium.java_client.remote.AppiumProtocolHandShake.createSession(AppiumProtocolHandShake.java:78)
	at io.appium.java_client.remote.AppiumCommandExecutor.doExecute(AppiumCommandExecutor.java:111)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:162)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:604)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:244)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:88)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:112)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:73)

## Environment

Appium: 5.0.0-BETA9    
Appium server: 1.6.5
OS: Windows 7
Selenium: 3.4.0
env : java + maven + testng + appium + selenium 
android api:23

## Details

If I delete the added line , run successfully without any Error.
Search with google, appears not enough infomation

## Link to Appium logs

[debug] [AndroidDriver] AndroidDriver version: 1.20.0
[BaseDriver] SessionNotCreatedError: A new session could not be created. Details
: The desiredCapabilities object was not valid for the following reason(s):  dev
iceName can't be blank,
    at AndroidDriver.validateDesiredCaps (../../../lib/basedriver/driver.js:155:
25)
    at AndroidDriver.validateDesiredCaps (../../lib/driver.js:32:20)
    at AndroidDriver.callee$0$0$ (../../../../lib/basedriver/commands/session.js
:23:8)
    at tryCatch (D:\Users\useraaa\Application Data\npm\node_modules\appium\node_m
odules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (D:\Users\useraaa\Applicati
on Data\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.j
s:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (D:\U
sers\useraaa\Application Data\npm\node_modules\appium\node_modules\babel-runtime\
regenerator\runtime.js:100:21)
    at invoke (D:\Users\useraaa\Application Data\npm\node_modules\appium\node_mod
ules\babel-runtime\regenerator\runtime.js:136:37)
    at enqueueResult (D:\Users\useraaa\Application Data\npm\node_modules\appium\n
ode_modules\babel-runtime\regenerator\runtime.js:185:17)
    at Promise.F (D:\Users\useraaa\Application Data\npm\node_modules\appium\node_
modules\core-js\library\modules\$.export.js:30:36)
    at AsyncIterator.enqueue (D:\Users\useraaa\Application Data\npm\node_modules\
appium\node_modules\babel-runtime\regenerator\runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (D:\Users\useraaa\A
pplication Data\npm\node_modules\appium\node_modules\babel-runtime\regenerator\r
untime.js:100:21)
    at Object.runtime.async (D:\Users\useraaa\Application Data\npm\node_modules\a
ppium\node_modules\babel-runtime\regenerator\runtime.js:209:12)
    at AndroidDriver.callee$0$0 [as createSession] (../../../../lib/basedriver/c
ommands/session.js:15:11)
    at AndroidDriver.createSession$ (../../lib/driver.js:32:20)
    at tryCatch (D:\Users\useraaa\Application Data\npm\node_modules\appium\node_m
odules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (D:\Users\useraaa\Applicati
on Data\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.j
s:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (D:\U
sers\useraaa\Application Data\npm\node_modules\appium\node_modules\babel-runtime\
regenerator\runtime.js:100:21)
    at invoke (D:\Users\useraaa\Application Data\npm\node_modules\appium\node_mod
ules\babel-runtime\regenerator\runtime.js:136:37)
    at enqueueResult (D:\Users\useraaa\Application Data\npm\node_modules\appium\n
ode_modules\babel-runtime\regenerator\runtime.js:185:17)
    at Promise.F (D:\Users\useraaa\Application Data\npm\node_modules\appium\node_
modules\core-js\library\modules\$.export.js:30:36)
    at AsyncIterator.enqueue (D:\Users\useraaa\Application Data\npm\node_modules\
appium\node_modules\babel-runtime\regenerator\runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (D:\Users\useraaa\A
pplication Data\npm\node_modules\appium\node_modules\babel-runtime\regenerator\r
untime.js:100:21)
    at Object.runtime.async (D:\Users\useraaa\Application Data\npm\node_modules\a
ppium\node_modules\babel-runtime\regenerator\runtime.js:209:12)
    at AndroidDriver.createSession (../../lib/driver.js:125:24)
    at AppiumDriver.createSession$ (../../lib/appium.js:183:43)
    at tryCatch (D:\Users\useraaa\Application Data\npm\node_modules\appium\node_m
odules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (D:\Users\useraaa\Applicati
on Data\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.j
s:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (D:\U
sers\useraaa\Application Data\npm\node_modules\appium\node_modules\babel-runtime\
regenerator\runtime.js:100:21)
    at invoke (D:\Users\useraaa\Application Data\npm\node_modules\appium\node_mod
ules\babel-runtime\regenerator\runtime.js:136:37)
    at enqueueResult (D:\Users\useraaa\Application Data\npm\node_modules\appium\n
ode_modules\babel-runtime\regenerator\runtime.js:185:17)
    at Promise.F (D:\Users\useraaa\Application Data\npm\node_modules\appium\node_
modules\core-js\library\modules\$.export.js:30:36)
    at AsyncIterator.enqueue (D:\Users\useraaa\Application Data\npm\node_modules\
appium\node_modules\babel-runtime\regenerator\runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (D:\Users\useraaa\A
pplication Data\npm\node_modules\appium\node_modules\babel-runtime\regenerator\r
untime.js:100:21)
    at Object.runtime.async (D:\Users\useraaa\Application Data\npm\node_modules\a
ppium\node_modules\babel-runtime\regenerator\runtime.js:209:12)
    at AppiumDriver.createSession (../../lib/appium.js:183:31)
    at ../../../lib/basedriver/driver.js:207:24
    at tryCatcher (D:\Users\useraaa\Application Data\npm\node_modules\appium\node
_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (D:\Users\useraaa\Application Data\npm\n
ode_modules\appium\node_modules\bluebird\js\main\promise.js:510:31)
    at Promise._settlePromiseAt (D:\Users\useraaa\Application Data\npm\node_modul
es\appium\node_modules\bluebird\js\main\promise.js:584:18)
    at Promise._settlePromiseAtPostResolution (D:\Users\useraaa\Application Data\
npm\node_modules\appium\node_modules\bluebird\js\main\promise.js:248:10)
    at Async._drainQueue (D:\Users\useraaa\Application Data\npm\node_modules\appi
um\node_modules\bluebird\js\main\async.js:128:12)
    at Async._drainQueues (D:\Users\useraaa\Application Data\npm\node_modules\app
ium\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues (D:\Users\useraaa\Application Data\npm\node_mo
dules\appium\node_modules\bluebird\js\main\async.js:15:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
 { SessionNotCreatedError: A new session could not be created. Details: The desi
redCapabilities object was not valid for the following reason(s):  deviceName ca
n't be blank,
    at AndroidDriver.validateDesiredCaps (../../../lib/basedriver/driver.js:155:
25)
    at AndroidDriver.validateDesiredCaps (../../lib/driver.js:32:20)
    at AndroidDriver.callee$0$0$ (../../../../lib/basedriver/commands/session.js
:23:8)
    at tryCatch (D:\Users\useraaa\Application Data\npm\node_modules\appium\node_m
odules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (D:\Users\useraaa\Applicati
on Data\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.j
s:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (D:\U
sers\useraaa\Application Data\npm\node_modules\appium\node_modules\babel-runtime\
regenerator\runtime.js:100:21)
    at invoke (D:\Users\useraaa\Application Data\npm\node_modules\appium\node_mod
ules\babel-runtime\regenerator\runtime.js:136:37)
    at enqueueResult (D:\Users\useraaa\Application Data\npm\node_modules\appium\n
ode_modules\babel-runtime\regenerator\runtime.js:185:17)
    at Promise.F (D:\Users\useraaa\Application Data\npm\node_modules\appium\node_
modules\core-js\library\modules\$.export.js:30:36)
    at AsyncIterator.enqueue (D:\Users\useraaa\Application Data\npm\node_modules\
appium\node_modules\babel-runtime\regenerator\runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (D:\Users\useraaa\A
pplication Data\npm\node_modules\appium\node_modules\babel-runtime\regenerator\r
untime.js:100:21)
    at Object.runtime.async (D:\Users\useraaa\Application Data\npm\node_modules\a
ppium\node_modules\babel-runtime\regenerator\runtime.js:209:12)
    at AndroidDriver.callee$0$0 [as createSession] (../../../../lib/basedriver/c
ommands/session.js:15:11)
    at AndroidDriver.createSession$ (../../lib/driver.js:32:20)
    at tryCatch (D:\Users\useraaa\Application Data\npm\node_modules\appium\node_m
odules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (D:\Users\useraaa\Applicati
on Data\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.j
s:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (D:\U
sers\useraaa\Application Data\npm\node_modules\appium\node_modules\babel-runtime\
regenerator\runtime.js:100:21)
    at invoke (D:\Users\useraaa\Application Data\npm\node_modules\appium\node_mod
ules\babel-runtime\regenerator\runtime.js:136:37)
    at enqueueResult (D:\Users\useraaa\Application Data\npm\node_modules\appium\n
ode_modules\babel-runtime\regenerator\runtime.js:185:17)
    at Promise.F (D:\Users\useraaa\Application Data\npm\node_modules\appium\node_
modules\core-js\library\modules\$.export.js:30:36)
    at AsyncIterator.enqueue (D:\Users\useraaa\Application Data\npm\node_modules\
appium\node_modules\babel-runtime\regenerator\runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (D:\Users\useraaa\A
pplication Data\npm\node_modules\appium\node_modules\babel-runtime\regenerator\r
untime.js:100:21)
    at Object.runtime.async (D:\Users\useraaa\Application Data\npm\node_modules\a
ppium\node_modules\babel-runtime\regenerator\runtime.js:209:12)
    at AndroidDriver.createSession (../../lib/driver.js:125:24)
    at AppiumDriver.createSession$ (../../lib/appium.js:183:43)
    at tryCatch (D:\Users\useraaa\Application Data\npm\node_modules\appium\node_m
odules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (D:\Users\useraaa\Applicati
on Data\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.j
s:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (D:\U
sers\useraaa\Application Data\npm\node_modules\appium\node_modules\babel-runtime\
regenerator\runtime.js:100:21)
    at invoke (D:\Users\useraaa\Application Data\npm\node_modules\appium\node_mod
ules\babel-runtime\regenerator\runtime.js:136:37)
    at enqueueResult (D:\Users\useraaa\Application Data\npm\node_modules\appium\n
ode_modules\babel-runtime\regenerator\runtime.js:185:17)
    at Promise.F (D:\Users\useraaa\Application Data\npm\node_modules\appium\node_
modules\core-js\library\modules\$.export.js:30:36)
    at AsyncIterator.enqueue (D:\Users\useraaa\Application Data\npm\node_modules\
appium\node_modules\babel-runtime\regenerator\runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (D:\Users\useraaa\A
pplication Data\npm\node_modules\appium\node_modules\babel-runtime\regenerator\r
untime.js:100:21)
    at Object.runtime.async (D:\Users\useraaa\Application Data\npm\node_modules\a
ppium\node_modules\babel-runtime\regenerator\runtime.js:209:12)
    at AppiumDriver.createSession (../../lib/appium.js:183:31)
    at ../../../lib/basedriver/driver.js:207:24
    at tryCatcher (D:\Users\useraaa\Application Data\npm\node_modules\appium\node
_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (D:\Users\useraaa\Application Data\npm\n
ode_modules\appium\node_modules\bluebird\js\main\promise.js:510:31)
    at Promise._settlePromiseAt (D:\Users\useraaa\Application Data\npm\node_modul
es\appium\node_modules\bluebird\js\main\promise.js:584:18)
    at Promise._settlePromiseAtPostResolution (D:\Users\useraaa\Application Data\
npm\node_modules\appium\node_modules\bluebird\js\main\promise.js:248:10)
    at Async._drainQueue (D:\Users\useraaa\Application Data\npm\node_modules\appi
um\node_modules\bluebird\js\main\async.js:128:12)
    at Async._drainQueues (D:\Users\useraaa\Application Data\npm\node_modules\app
ium\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues (D:\Users\useraaa\Application Data\npm\node_mo
dules\appium\node_modules\bluebird\js\main\async.js:15:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5) jsonwpCode: 33
 }
[debug] [AndroidDriver] Shutting down Android driver
[debug] [AndroidDriver] Called deleteSession but bootstrap wasn't active
[HTTP] <-- POST /wd/hub/session 500 17 ms - 199

**Comment by mykola-mokhnach** [comment]
Have you tried to set _deviceName_ capability, like it is mentioned in the error description?

**Comment by AlexDingSZ** [comment]
@mykola-mokhnach  Yes,  set deviceName as : 
capabilities.setCapability("deviceName", udid);

the situation is:
1、With codes
 capabilities.setCapability("deviceName", udid); 
work very well, but can't get the toast text.
2、With codes, 
 capabilities.setCapability("deviceName", udid); 
capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.ANDROID_UIAUTOMATOR2);
 run the script with ERROR.

I don't know what is the decisive factors to run successfully or Error

**Comment by mykola-mokhnach** [comment]
> 1、With codes
> capabilities.setCapability("deviceName", udid);
> work very well, but can't get the toast text.

So what is the reason to mix two absolutely different problems in the single issue? Toast detection is absolutely separate topic, which has nothing to do with device name setting. And it has been already discussed here many times: https://github.com/appium/appium/issues?q=is%3Aissue+toast

**Comment by AlexDingSZ** [comment]
@mykola-mokhnach ,thanks for your tips.  I just get the way to resolve this problem.
the problem is there are no necessary uiautomator2 apk files  after install appium with command npm install -g appium.  so i reinstall  uiautomator2 driver with command, npm install appium-uiautomator2-driver.  hope can help someone.
