### ISSUE TITLE
Can not run on iOS real device

### ISSUE THREAD

**Issue by prudhvialahari** [appium/appium#8832]
## The problem

The Appium throws an error saying 'idevice_id' program is not installed when I try to run on the iOS real device. I have followed the steps from https://appium.readthedocs.io/en/stable/en/appium-setup/real-devices-ios. I have already installed libimobiledevice saying "brew install libimobiledevice --HEAD", even though it throws that error.

## Environment

* Appium version 1.6.5
* Mac OS 10.12
* Node.js version 6.11.1
* Xcode version 8.3.2
* Real device iOS version 10.3

## Link to Appium logs

[INFO][2017-07-12 18:58:41.738]Calling new AppiumDriver for iOS ...
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/test/Desktop/NewRBAuto/RetailBanking.app","noReset":false,"newCommandTimeout":60000,"autoLaunch":true,"platformVersion":"10.3","bundleId":"com.verticalapps.RetailBanking","platformName":"iOS","fullReset":false,"deviceName":"iPhone 6","platform":"MAC","autoAcceptAlerts":false}}
[Appium] Requested iOS support with version >= 10, using XCUITest driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
[Appium] Creating new XCUITestDriver (v2.30.0) session
[Appium] Capabilities:
[Appium]   app: '/Users/test/Desktop/NewRBAuto/RetailBanking.app'
[Appium]   noReset: false
[Appium]   newCommandTimeout: 60000
[Appium]   autoLaunch: true
[Appium]   platformVersion: '10.3'
[Appium]   bundleId: 'com.verticalapps.RetailBanking'
[Appium]   platformName: 'iOS'
[Appium]   fullReset: false
[Appium]   deviceName: 'iPhone 6'
[Appium]   platform: 'MAC'
[Appium]   autoAcceptAlerts: false
[Appium]   xcodeOrgId: 'XYZ'
[Appium]   udid: 'XYZ'
[Appium]   xcodeSigningId: 'iPhone Developer '
[BaseDriver] The following capabilities were provided, but are not recognized by appium: platform.
[BaseDriver] Session created with session id: b1afb25f-15e6-442e-95e6-6c41a0c702a8
[XCUITest] The 'idevice_id' program is not installed. If you are running a real device test it is necessary. Install with 'brew install libimobiledevice --HEAD'
[XCUITest] Error: Unknown device or simulator UDID: 'XYZ'
    at XCUITestDriver.determineDevice$ (../../lib/driver.js:604:17)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 Error: Unknown device or simulator UDID: 'XYZ'
    at XCUITestDriver.determineDevice$ (../../lib/driver.js:604:17)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:109:7)
[MJSONWP] Encountered internal error running command: Error: Unknown device or simulator UDID: '622c7948[HTTP] <-- POST /wd/hub/session 500 33836 ms - 213 
f37a0e0d585e7001b15dd1b66a9bfdff'
    at XCUITestDriver.determineDevice$ (../../lib/driver.js:604:17)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by imurchie** [comment]
Did the install of `libimobiledevice` create all the links? Sometimes it does not. Does `idevice_id -l` work from the command line?

If it does, how are you running Appium? Is the PATH being replicated?

**Comment by prudhvialahari** [comment]
Hi Imurchie,
"brew install libimobiledevice --HEAD" installed without any errors and "idevice_id -l" listed the iOS real device connected. 

I'm starting the Appium programmatically.

**Comment by imurchie** [comment]
And is the PATH being set up correctly when running programmatically? It seems like no, since this program is not on it.

**Comment by prudhvialahari** [comment]
The Appium started successfully and what is the PATHyou were specifying? Is it the Appium URL?

[TestNG] Running:
  /Users/test/Desktop/NewRBAuto/retailbankingapp/NewRetailBankingTestCode/src/MobileP0.xml

[Appium] Welcome to Appium v1.6.5
[Appium] Non-default server args:
[Appium]   port: 40416
[Appium]   log: /Users/test/Desktop/NewRBAuto/retailbankingapp/NewRetailBankingTestCode/appiumLog.txt
[Appium]   loglevel: info
[Appium]   defaultCapabilities: {
[Appium]     xcodeOrgId: xyz
[Appium]     udid: xyz
[Appium]     xcodeSigningId: iPhone Developer 
[Appium]   }
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   xcodeOrgId: 'XYZ'
[Appium]   udid: 'XYZ'
[Appium]   xcodeSigningId: 'iPhone Developer '
[Appium] Appium REST http interface listener started on 0.0.0.0:40416
[HTTP] --> GET /wd/hub/status {}
[HTTP] <-- GET /wd/hub/status 200 55 ms - 83

**Comment by imurchie** [comment]
No, the environment variable that tells the system where to find executable programs.

**Comment by prudhvialahari** [comment]
I did not set any PATH for Appium (installed it globally) or libimobiledevice. Do we need to set one?

**Comment by imurchie** [comment]
Those are both set automatically when installed.

But since you are starting Appium programmatically, whatever is starting it needs to include the PATH in its executing environment. I have no idea how to do that, since I have no idea how you are executing Appium.

**Comment by prudhvialahari** [comment]
I'm using this piece of code to start Appium. Do you suggest to start Appium manually?
           		
            		appiumService = AppiumDriverLocalService.buildService(new AppiumServiceBuilder()
            				.usingAnyFreePort()
            				.withLogFile(new File("appiumLog.txt"))
            				.withArgument(GeneralServerFlag.LOG_LEVEL,"info")
            				.withCapabilities(cap));

**Comment by imurchie** [comment]
I would query the Java client (https://github.com/appium/java-client)

**Comment by prudhvialahari** [comment]
Any update on this Imurchie?
