### ISSUE TITLE
Failed to launch webdriver agent for after every alternate builds

### ISSUE THREAD

**Issue by AnuvrathElastica** [appium/appium#8839]
## The problem

I am running iOS XC test on a real device which is connected to MacPro. these builds are triggered Jenkins running on same machine. Issue am seeing the following issue, 

Say build 1 on a iOS device runs smoothly, build 2 of same job/any other job on same iOS device fails with this error.

14:30:18 [XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
14:30:18     at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:422:13)
14:30:18     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
14:30:18     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
14:30:18     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
14:30:18     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
14:30:18  Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
14:30:18     at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:422:13)
14:30:18     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
14:30:18     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
14:30:18     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
14:30:18     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
14:30:18 [MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
14:30:18     at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:422:13)
14:30:18     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
14:30:18     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
14:30:18     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
14:30:18     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
14:30:18 2017-07-12 14:30:18 [ERROR] Failed to start remove web driver for ios!!!... So stopping test execution
14:30:18 org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device. (WARNING: The server did not provide any stacktrace information)
14:30:18 Command duration or timeout: 57.54 seconds
14:30:18 Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.6-beta.2
* Last Appium version that did not exhibit the issue (if applicable): 1.6.4
* Desktop OS/version used to run Appium: MacOSX
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS
* Real device or emulator/simulator:Real Device
* Appium CLI or Appium.app|exe:

Capabilities used are: 
public DesiredCapabilities getIOSCapabilities(SuiteDTO suiteData){
		DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.merge(addDefaultCapabilities(suiteData));
		capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, suiteData.getDeviceName());
		capabilities.setCapability(MobileCapabilityType.UDID, suiteData.getDeviceUDID());
		capabilities.setCapability("locationServicesEnabled", true);
		capabilities.setCapability("locationServicesAuthorized", true);
		capabilities.setCapability("autoWebview",false);
		capabilities.setCapability("noReset", true);
		capabilities.setCapability("wdaLaunchTimeout", 300000);		
		capabilities.setCapability("showXcodeLog", false);
		capabilities.setCapability("clearSystemFiles", true);
		capabilities.setCapability(MobileCapabilityType.APP, suiteData.getApp());		
		capabilities.setCapability("realDeviceLogger", "/usr/local/lib/node_modules/deviceconsole/deviceconsole");		
		capabilities.setCapability("wdaLocalPort", 8100);
		capabilities.setCapability("usePrebuiltWDA", true);
		capabilities.setCapability("startIWDP", true);
		capabilities.setCapability("shouldUseSingletonTestManager", false);

		return capabilities;

**Comment by AnuvrathElastica** [comment]
Surprisingly, when i try to run this command directly in command line don't see any issue..

xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=$1 test

**Comment by mykola-mokhnach** [comment]
Please attach the full log.  It would be good to have xcodebuild log. Just set the _showXcodeLog_ capability to **true**.

**Comment by vikramvi** [comment]
@AnuvrathElastica also try per https://github.com/appium/appium/issues/7828#issuecomment-280463147

**Comment by AnuvrathElastica** [comment]
@vikramvi `wdaStartupRetries` already retries two times. So, am not sure if that helps.  

@mykola-mokhnach i'll attache the complete log in sometime.

**Comment by AnuvrathElastica** [comment]
@mykola-mokhnach Please find the attached log. 

[iOS.txt](https://github.com/appium/appium/files/1146234/iOS.txt)

**Comment by AnuvrathElastica** [comment]
@mykola-mokhnach 

I tried your suggestion manually, and seeing these errors;

**Iproxy error:**
Error connecting to device!
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 61 (serial: 2ebb9996f1b12bb47b7b3c60b893c79b245e970c), port 8100

 **"xcodebuild error"** File attached

**Comment by AnuvrathElastica** [comment]
[log.txt](https://github.com/appium/appium/files/1149928/log.txt)
Forgot to attach in previous message

**Comment by AnuvrathElastica** [comment]
@mykola-mokhnach can you please help me with this issue? Can you also please help me understand why i didn't observe this issue in 1.6.4 but seeing only in this 1.6.6. 

If you think, reverting my appium version back to 1.6.4 helps i can try that too.

**Comment by mykola-mokhnach** [comment]
I have already suggested the possible solutions I know. Or better to say "workarounds", because if the issue happens on XCTest/Apple side then I can hardly do anything to address it.

If you say 1.6.4 works the best for you then just use it.
