### ISSUE TITLE
Error: Unknown device or simulator 

### ISSUE THREAD

**Issue by lareddy** [appium/appium#8850]
## The problem

When I connect my real iOS device and try to use access app, Appium is giving error as Unknown device or simulator

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS Sierra - 10.12.5
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS 10.3
* Real device or emulator/simulator: Real device - iPad Air
* Appium CLI or Appium.app|exe: - Appium exe

## Details
When I connect my real iOS device and try to use access app, Appium is giving error as Unknown device or simulator. But device is connected to Mac. And in error I see "The 'idevice_id' program is not installed. If you are running a real device test it is necessary. Install with 'brew install libimobiledevice --HEAD'". But libimobiledevice is already installed. when I execute brew install libimobiledevice --HEAD'" in command line tool, then getting messages as "libimobiledevice HEAD-0dbe76b_2 is already installed"

I entered  below desired capabilities
{
  "platformName": "iOS",
  "platformVersion": "10.3",
  "deviceName": "iPad Air",
  "noReset": true,
  "udid": "9c390e4b2cb047867fa3b108714fc78fcf248f6a",
  "bundleId": "com.davita.pod",
  "automationName": "XCUITest",
  "xcodeOrgId": "AUP79D422L",
  "xcodeSigningId": "iphone Developer"
}

## Link to Appium logs

[MJSONWP] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 16 ms - 40 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"automationName":"XCUITest","bundleId":"com.davita.pod","deviceName":"iPad Air","noReset":true,"platformName":"iOS","platformVersion":"10.3","udid":"9c390e4b2cb047867fa3b108714fc78fcf248f6a","xcodeOrgId":"AUP79D422L","xcodeSigningId":"iphone Developer","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"automationName":"XCUITest","bundleId":"com.davita.pod","deviceName":"iPad Air","noReset":true,"platformName":"iOS","platformVersion":"10.3","udid":"9c390e4b2cb047867fa3b108714fc78fcf248f6a","xcodeOrgId":"AUP79D422L","xcodeSigningId":"iphone Developer","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1499962037140 (11:07:17 GMT-0500 (CDT))
[Appium] Creating new XCUITestDriver (v2.30.0) session
[Appium] Capabilities:
[Appium]   automationName: 'XCUITest'
[Appium]   bundleId: 'com.davita.pod'
[Appium]   deviceName: 'iPad Air'
[Appium]   noReset: true
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '10.3'
[Appium]   udid: '9c390e4b2cb047867fa3b108714fc78fcf248f6a'
[Appium]   xcodeOrgId: 'AUP79D422L'
[Appium]   xcodeSigningId: 'iphone Developer'
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true
[XCUITest] XCUITestDriver version: 2.30.0
[BaseDriver] Session created with session id: 1725414a-e0b9-4733-acf0-38c88fd38400
[XCUITest] Xcode version set to '8.3.3' (tools v8.3.2.0.1.1492020469)
[XCUITest] iOS SDK Version set to '10.3'
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1499962037422 (11:07:17 GMT-0500 (CDT))
[XCUITest] The 'idevice_id' program is not installed. If you are running a real device test it is necessary. Install with 'brew install libimobiledevice --HEAD'
[XCUITest] Available devices: 
[XCUITest] Error: Unknown device or simulator UDID: '9c390e4b2cb047867fa3b108714fc78fcf248f6a'
    at XCUITestDriver.determineDevice$ (/Applications/PoD Shared Apps/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:604:17)
    at tryCatch (/Applications/PoD Shared Apps/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/PoD Shared Apps/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/PoD Shared Apps/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/PoD Shared Apps/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: Unknown device or simulator UDID: '9c390e4b2cb047867fa3b108714fc78fcf248f6a'
    at XCUITestDriver.determineDevice$ (/Applications/PoD Shared Apps/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:604:17)
    at tryCatch (/Applications/PoD Shared Apps/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/PoD Shared Apps/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/PoD Shared Apps/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/PoD Shared Apps/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[MJSONWP] Encountered internal error running command: Error: Unknown device or simulator UDID: '9c390e4b2cb047867fa3b108714fc78fcf248f6a'
    at XCUITestDriver.determineDevice$ (/Applications/PoD Shared Apps/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:604:17)
    at tryCatch (/Applications/PoD Shared Apps/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/PoD Shared Apps/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/PoD Shared Apps/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/PoD Shared Apps/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[HTTP] <-- POST /wd/hub/session 500 545 ms - 213

**Comment by mykola-mokhnach** [comment]
> [XCUITest] The 'idevice_id' program is not installed. If you are running a real device test it is necessary. Install with 'brew install libimobiledevice --HEAD'

Just follow what the log advices

**Comment by lareddy** [comment]
Both libimobiledebice and ideviceinstaller are already installed on mac. But still getting the error

**Comment by mykola-mokhnach** [comment]
Make sure the HEAD branch of these is installed. Also, paths to their binaries should be present in PATH.

**Comment by lareddy** [comment]
I installed using HEAD.  brew install libimobiledevice --HEAD. And set paths also, but still getting the same error. 'idevice_id' program is not installed. Is there any other changes i need to do?
Are the below desired capabilities good, or anything needs to be changed?
{
"platformName": "iOS",
"platformVersion": "10.3",
"deviceName": "iPad Air",
"noReset": true,
"udid": "9c390e4b2cb047867fa3b108714fc78fcf248f6a",
"bundleId": "com.davita.pod",
"automationName": "XCUITest",
"xcodeOrgId": "AUP79D422L",
"xcodeSigningId": "iphone Developer"
}

**Comment by mykola-mokhnach** [comment]
Check the PATH variable of appium process itself. On Mac OS you can do it with `ps -wwE -p <PID>` command

**Comment by lareddy** [comment]
Seeing new error now, please help:

[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 1
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:386:15)

**Comment by lareddy** [comment]
Mykola, i was able to resolve above error, and now getting error as 

[Xcode] 2017-07-17 16:11:48.577 xcodebuild[63321:848040] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/lareddy/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7f9ee8209a50 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[Xcode] 
[Xcode] 2017-07-17 16:11:48.577 xcodebuild[63321:848040] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 

Can you help me how to resolve this?

**Comment by imurchie** [comment]
@lareddy This is now a code signing issue. Please see https://github.com/appium/appium/blob/master/docs/en/appium-setup/real-devices-ios.md

**Comment by lareddy** [comment]
Thank you imurchie, i am able to proceed further.

**Comment by keshavwy** [comment]
@mykola-mokhnach 
>>Make sure the HEAD branch of these is installed. Also, paths to their binaries should be present in PATH.
I am also facing the similar issue. Can you please help in setting up the path to their binaries? I am new to this
