### ISSUE TITLE
App Source Could not obtain source: [object Object] Android 7.1.1

### ISSUE THREAD

**Issue by terrychen92** [appium/appium#8856]
## The problem
like this
[http://i2.kiimg.com/600804/5ac51b95ec6d2071.png](url)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable):unknown
* Desktop OS/version used to run Appium: Windows 7
* Node.js version (unless using Appium.app|exe):8.1.4
* Mobile platform/version under test:7.1.1
* Real device or emulator/simulator:sorry,it`s security
* Appium CLI or Appium.app|exe:appium-desktop-1.1.0-beta.4

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/terrychen92/408419eef2c15fdfbe31ea81d0093d91

**Comment by mykola-mokhnach** [comment]
This looks like an internal UIAutomation issue. Try UIAutomation2 as the automation backend

**Comment by terrychen92** [comment]
@mykola-mokhnach  if i use UIAutomation2 ,it still no work
and post the error:
An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET
and the log：
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[UiAutomator2] Deleting UiAutomator2 session
[UiAutomator2] Deleting UiAutomator2 server session
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: Error: Trying to proxy a session command without session id
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'F:\adt-bundle-windows-x86_64-20170703\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","327371140278","shell","am","force-stop","com.android.messaging"]
[Logcat] Stopping logcat capture
[ADB] Removing forwarded port socket connection: 8200 
[ADB] Running 'F:\adt-bundle-windows-x86_64-20170703\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","327371140278","forward","--remove","tcp:8200"]
[MJSONWP] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: Error: read ECONNRESET
    at JWProxy.proxy$ (C:\Users\Administrator\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:153:13)
    at tryCatch (C:\Users\Administrator\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\Administrator\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\Administrator\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\Administrator\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 43539 ms - 217

**Comment by imurchie** [comment]
There have been changes to the startup flow with UIAutomator2. Can you upgrade to the latest beta and try again? (`npm uninstall -g appium && npm cache clean && npm install -g appium@beta`)

**Comment by terrychen92** [comment]
@imurchie yes,but i installed appium@1.6.6 beta3 ,there was no appium-uiautomator2-server-v0.1.6.apk and appium-uiautomator2-server-debug-androidTest.apk in the folder

**Comment by terrychen92** [comment]
@finally ifound the apk in here [https://github.com/appium/appium-uiautomator2-server/releases](url),but it still not work.
the error:
WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET
the log:
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/h
ub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/h
ub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/h
ub/status] with no body
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [UiAutomator2] Deleting UiAutomator2 server session
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error
 was: Error: Trying to proxy a session command without session id
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'F:\adt-bundle-windows-x86_64-20170703\sdk\platform-tools\
adb.exe' with args: ["-P",5037,"-s","327371140278","shell","am","force-stop","co
m.android.messaging"]
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Removing forwarded port socket connection: 8200
[debug] [ADB] Running 'F:\adt-bundle-windows-x86_64-20170703\sdk\platform-tools\
adb.exe' with args: ["-P",5037,"-s","327371140278","forward","--remove","tcp:820
0"]
[MJSONWP] Encountered internal error running command: ProxyRequestError: Could n
ot proxy command to remote server. Original error: Error: read ECONNRESET
    at JWProxy.proxy$ (../../../lib/jsonwp-proxy/proxy.js:153:13)
    at tryCatch (C:\Users\Administrator\AppData\Roaming\npm\node_modules\appium\
node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\Administrator\Ap
pData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\run
time.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\
Users\Administrator\AppData\Roaming\npm\node_modules\appium\node_modules\babel-r
untime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\Administrator\AppData\Roaming
\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)

**Comment by jlipps** [comment]
@terrychen92 can you share a link to a gist of the _full_ logs that you have run with the latest beta?

**Comment by ayarema** [comment]
And when I try to refresh after first searching I get appium server logs like this:

```
[MJSONWP] Calling AppiumDriver.getPageSource() with args: ["a82805c7-f4f1-4af9-a2f5-96e677170978"]
[XCUITest] Executing command 'getPageSource'
[JSONWP Proxy] Proxying [GET /source] to [GET http://localhost:8100/session/811EB5F7-939A-4B97-89EB-1E68BA488214/source] with no body
[Xcode] 2017-08-30 17:14:06.140 XCTRunner[932:25611] Running tests...
[Xcode] 2017-08-30 17:14:06.919 XCTRunner[932:25611] Continuing to run tests in the background with task ID 1
[Xcode] Test Suite 'All tests' started at 2017-08-30 17:14:07.055
[Xcode] Test Suite 'WebDriverAgentLib.framework' started at 2017-08-30 17:14:07.056
[Xcode] Test Suite 'WebDriverAgentLib.framework' passed at 2017-08-30 17:14:07.057.
[Xcode] 	 Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.000) seconds
[Xcode] Test Suite 'WebDriverAgentRunner.xctest' started at 2017-08-30 17:14:07.057
[Xcode] Test Suite 'UITestingUITests' started at 2017-08-30 17:14:07.057
[Xcode] Test Case '-[UITestingUITests testRunner]' started.
[Xcode]     t =     0.00s     Start Test at 2017-08-30 17:14:07.058
[Xcode]     t =     0.00s     Set Up
[Xcode] 2017-08-30 17:14:07.062 XCTRunner[932:25611] Built at Aug 28 2017 12:40:30
[Xcode] 2017-08-30 17:14:07.084 XCTRunner[932:25611] ServerURLHere->http://1.1.1.1:8100<-ServerURLHere
[Xcode]     t =     0.22s     Launch com.my.application
[Xcode]     t =     0.63s         Wait for app to idle
[Xcode]     t =     2.20s             Unable to monitor animations
[Xcode]     t =     2.29s             Unable to monitor event loop
[Xcode]     t =     3.43s     Find the Application "com.my.application" 0x6000000ae040
[Xcode]     t =     3.43s         Snapshot accessibility hierarchy for com.my.application
[Xcode]     t =     3.82s     Find the Application "com.my.application" 0x6000000ae040
[Xcode]     t =     3.82s         Use cached accessibility hierarchy for com.my.application
[Xcode]     t =     3.82s     Find the Application "com.my.application" 0x6000000ae040
[Xcode]     t =     3.82s         Use cached accessibility hierarchy for com.my.application
[Xcode]     t =     3.88s     Find the Application "local.pid.621" 0x6080000aa620
[Xcode]     t =     3.88s         Snapshot accessibility hierarchy for local.pid.621
[Xcode]     t =     4.02s     Find the Application "local.pid.621" 0x6080000aa620
[Xcode]     t =     4.02s         Use cached accessibility hierarchy for local.pid.621
[Xcode]     t =     4.04s     Find the Application "local.pid.621" 0x6080000aa620
[Xcode]     t =     4.04s         Snapshot accessibility hierarchy for local.pid.621
[Xcode]     t =     4.14s     Set device orientation to Portrait
[Xcode]     t =     4.99s     Find the Application "local.pid.621" 0x6080000aa620
[Xcode]     t =     4.99s         Snapshot accessibility hierarchy for local.pid.621
[Xcode]     t =     5.06s     Find the Application "local.pid.621" 0x6080000aa620
[Xcode]     t =     5.06s         Use cached accessibility hierarchy for local.pid.621
[Xcode]     t =    42.66s     Find the Application "com.my.application" 0x6000000ae040
[Xcode]     t =    42.66s         Snapshot accessibility hierarchy for com.my.application
[Xcode] 2017-08-30 17:15:04.729 XCTRunner[932:26106] Enqueue Failure: Failure getting snapshot Error Domain=XCTDaemonErrorDomain Code=9 "Error -25204 getting snapshot for element  {pid=937}" UserInfo={NSLocalizedDescription=Error -25204 getting snapshot for element  {pid=937}}  0 1
[Xcode]     t =    58.67s         Find the Application "com.my.application" 0x6000000ae040 (retry 1)
[Xcode]     t =    58.67s             Snapshot accessibility hierarchy for com.my.application
[Xcode] 2017-08-30 17:15:20.739 XCTRunner[932:26107] Enqueue Failure: Failure getting snapshot Error Domain=XCTDaemonErrorDomain Code=9 "Error getting main window -25204" UserInfo={NSLocalizedDescription=Error getting main window -25204}  0 1
[Xcode]     t =    74.68s         Find the Application "com.my.application" 0x6000000ae040 (retry 2)
[Xcode]     t =    74.68s             Snapshot accessibility hierarchy for com.my.application
[Xcode] 2017-08-30 17:15:36.749 XCTRunner[932:26240] Enqueue Failure: Failure getting snapshot Error Domain=XCTDaemonErrorDomain Code=9 "Error getting main window -25204" UserInfo={NSLocalizedDescription=Error getting main window -25204}  0 1
[Xcode] 2017-08-30 17:15:36.824 XCTRunner[932:25611] Enqueue Failure: (null) /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 35 1
[Xcode]     t =    89.77s     Find the Application "com.my.application" 0x6000000ae040
[Xcode]     t =    89.77s         Snapshot accessibility hierarchy for com.my.application
[Xcode] 2017-08-30 17:15:51.861 XCTRunner[932:25611] Enqueue Failure: Failed to get snapshot within 15.0s /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 35 1
[Xcode]     t =   105.81s         Find the Application "com.my.application" 0x6000000ae040 (retry 1)
[Xcode]     t =   105.81s             Snapshot accessibility hierarchy for com.my.application
[Xcode] 2017-08-30 17:15:55.788 XCTRunner[932:26515] Enqueue Failure: Failure getting snapshot Error Domain=XCTDaemonErrorDomain Code=9 "Error -25204 getting snapshot for element  {pid=937}" UserInfo={NSLocalizedDescription=Error -25204 getting snapshot for element  {pid=937}}  0 1
[Xcode]     t =   109.73s         Find the Application "com.my.application" 0x6000000ae040 (retry 2)
[Xcode]     t =   109.73s             Snapshot accessibility hierarchy for com.my.application
[Xcode] 2017-08-30 17:16:10.791 XCTRunner[932:26515] Enqueue Failure: Failure getting snapshot Error Domain=XCTDaemonErrorDomain Code=9 "Error getting main window -25204" UserInfo={NSLocalizedDescription=Error getting main window -25204}  0 1
[Xcode] 2017-08-30 17:16:25.830 XCTRunner[932:25611] Enqueue Failure: (null) /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 35 1
[Xcode] 2017-08-30 17:16:25.831 XCTRunner[932:25611] Failed to invoke libxml2>xmlTextWriterStartElement. Error code: -1
[Xcode] 2017-08-30 17:16:25.831 XCTRunner[932:25611] Failed to generate XML presentation of a screen element
[Xcode] Entity: line 2: parser error : Extra content at the end of the document
[Xcode] 
[Xcode] ^
[Xcode] error : xmlTextWriterWriteDocCallback : XML error 5 !
[Xcode] 2017-08-30 17:16:32.592 XCTRunner[932:26024] Enqueue Failure: Failure getting snapshot Error Domain=XCTDaemonErrorDomain Code=9 "Error -25204 getting snapshot for element  {pid=937}" UserInfo={NSLocalizedDescription=Error -25204 getting snapshot for element  {pid=937}}  0 1
[Xcode]     t =   758.21s     Find the Application "com.my.application" 0x6000000ae040
[Xcode]     t =   758.21s         Snapshot accessibility hierarchy for com.my.application
[Xcode] 2017-08-30 17:27:00.273 XCTRunner[932:25611] Enqueue Failure: Failed to get snapshot within 15.0s /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 35 1
[Xcode] 2017-08-30 17:27:00.276 XCTRunner[932:29718] Enqueue Failure: Failure getting snapshot Error Domain=XCTDaemonErrorDomain Code=9 "Error -25204 getting snapshot for element  {pid=937}" UserInfo={NSLocalizedDescription=Error -25204 getting snapshot for element  {pid=937}}  0 1
[Xcode]     t =   774.22s         Find the Application "com.my.application" 0x6000000ae040 (retry 1)
[Xcode]     t =   774.22s             Snapshot accessibility hierarchy for com.my.application
[Xcode] 2017-08-30 17:27:16.280 XCTRunner[932:29785] Enqueue Failure: Failure getting snapshot Error Domain=XCTDaemonErrorDomain Code=9 "Error getting main window -25204" UserInfo={NSLocalizedDescription=Error getting main window -25204}  0 1
[Xcode]     t =   790.23s         Find the Application "com.my.application" 0x6000000ae040 (retry 2)
[Xcode]     t =   790.23s             Snapshot accessibility hierarchy for com.my.application
[Xcode] 2017-08-30 17:27:32.296 XCTRunner[932:25611] Enqueue Failure: Failed to get snapshot within 15.0s /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 35 1
[Xcode] 2017-08-30 17:27:39.977 XCTRunner[932:29785] Enqueue Failure: Failure getting snapshot Error Domain=XCTDaemonErrorDomain Code=9 "Error -25204 getting snapshot for element  {pid=937}" UserInfo={NSLocalizedDescription=Error -25204 getting snapshot for element  {pid=937}} 
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"Cannot get '(null)' source of the current application\",\n  \"sessionId\" : \"811EB5F7-939A-4B97-89EB-1E68BA488214\",\n  \"status\" : 13\n}"
[HTTP] <-- GET /wd/hub/session/a82805c7-f4f1-4af9-a2f5-96e677170978/source 500 109638 ms - 224 
[HTTP] --> GET /wd/hub/session/a82805c7-f4f1-4af9-a2f5-96e677170978/screenshot {}
[MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["a82805c7-f4f1-4af9-a2f5-96e677170978"]
[XCUITest] Executing command 'getScreenshot'
[JSONWP Proxy] Proxying [GET /screenshot] to [GET http://localhost:8100/session/811EB5F7-939A-4B97-89EB-1E68BA488214/screenshot] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"iVBORw0KGgoAAAANSUhEUgAAAu4AAAU2CAYAAADK1zMGAAAAAXNSR0IArs4c6QAA\\r\\nABxpRE9UAAAAAgAAAAAAAAKbAAAAKAAAApsAAAKbAAeJQvZ5NPYAAEAASURBVHgB\\r\\n7L33nx\\/Hcaevc7YlK5EUFS1RFClGgAARFrvYxSYssMg5BwJYAIsMEIkAcyZl+762\\r\\nfLYv2HfnCz5f8KXX5fMFX87ny76cc\\/RfMN\\/nqZ6az+xiQQGkJIPW\\/FCv7ulQXV3d\\r\\n0\\/3umpqZD\\/zKr\\/xK1VGng24OdHOgmwPdHOjmQDcHujnQzYFuDtzZc+AD3QDd2QPU\\r\\njU83Pt0c6OZANwe6OdDNgW4OdHOgmwPOgQ64d08cuicu3Rzo5kA3B7o50M2Bbg50\\r\\nc6CbA++DOdAB9\\/fBIHWn7O6U3c2Bbg50c6CbA90c6OZANwe6OdAB9w64dyfsbg50\\r\\nc6CbA90c6OZANwe6OdDNgffBHOiA+\\/tgkLoTdnfC7uZANwe6OdDNgW4OdHOgmwPd\\r\\nHOiAewfcuxN2Nwe6OdDNgW4OdHOgmwPdHOjmwPtgDnTA\\/X0wSN0Juzthd3OgmwPd\\r\\nHOjmQDcHujnQzYFuDnTAvQPu3Qm7mwPdHOjmQDcHujnQzYFuDnRz4H0wBzrg\\/j4Y\\r\\npO6E3Z2wuznQzYFuDnRzoJsD3Rzo5kA3Bzrg3gH37oTdzYFuDnRzoJsD3Rzo5kA3\\r\\nB7o58D6YA19X4P7f\\/tt\\/q37hF34h6D\\/8h\\/9wR0+AX\\/7lX64effTRasmSJZVy3+mn\\r\\n2P\\/9v\\/939Yf+0B+qLly4UI2MjFQ\\/8AM\\/UH34wx+uft2v+3URem26+Zaz\\/J3ep06+\\r\\nznLQzYEb58C\\/\\/Jf\\/svrjf\\/yPB7lO3Y6O\\/ut\\/\...
[MJSONWP] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAAAu4AAAU2CAYAAADK1zMGAAAAAXNSR0IArs4c6QAA\r\nABxpRE9UAAAAAgAAAAAAAAKbAAAAKAAAApsAAAKbAAeJQvZ5NPYAAEAASURBVHgB\r\n7L33nx/Hcaevc7YlK5EUFS1RFClGgAARFrvYxSYssMg5BwJYAIsMEIkAcyZl+762\r\nfLYv2HfnCz5f8KXX5fMFX87ny76cc/RfMN/nqZ6az+xiQQGkJIPW/FCv7ulQXV3d\r\n0/3umpqZD/zKr/xK1VGng24OdHOgmwPdHOjmQDcHujnQzYFuDtzZc+AD3QDd2QPU\r\njU83Pt0c6OZANwe6OdDNgW4OdHOgmwPOgQ64d08cuicu3Rzo5kA3B7o50M2Bbg50\r\nc6CbA++DOdAB9/fBIHWn7O6U3c2Bbg50c6CbA90c6OZANwe6OdAB9w64dyfsbg50\r\nc6CbA90c6OZANwe6OdDNgffBHOiA+/tgkLoTdnfC7uZANwe6OdDNgW4OdHOgmwPd\r\nHOiAewfcuxN2Nwe6OdDNgW4OdHOgmwPdHOjmwPtgDnTA/X0wSN0Juzthd3OgmwPd\r\nHOjmQDcHujnQzYFuDnTAvQPu3Qm7mwPdHOjmQDcHujnQzYFuDnRz4H0wBzrg/j4Y\r\npO6E3Z2wuznQzYFuDnRzoJsD3Rzo5kA3Bzrg3gH37oTdzYFuDnRzoJsD3Rzo5kA3\r\nB7o58D6YA19X4P7f/tt/q37hF34h6D/8h/9wR0+AX/7lX64effTRasmSJZVy3+mn\r\n2P/9v/939Yf+0B+qLly4UI2MjFQ/8AM/UH34wx+uft2v+3URem26+Zaz/J3ep06+\r\nznLQzYEb58C//Jf/svrjf/yPB7lO3Y6O/ut//a/VX/trf636fb/v91W/+Iu/WN3p\r\n6/Dt9K0re+Nc6XTS6aSbA2UO/PRP/3S1YMGCwETiojuRlE853+uYfV2A+1tvvVU9\r\n...
[HTTP] <-- GET /wd/hub/session/a82805c7-f4f1-4af9-a2f5-96e677170978/screenshot 200 167 ms - 810086 
```

**Comment by mykola-mokhnach** [comment]
> [Xcode] 2017-08-30 17:16:10.791 XCTRunner[932:26515] Enqueue Failure: Failure getting snapshot Error Domain=XCTDaemonErrorDomain Code=9 "Error getting main window -25204" UserInfo={NSLocalizedDescription=Error getting main window -25204}  0 1

is XCTest issue and we cannot do anything on Appium side to fix it. Please report it to Apple.

**Comment by chennareddy08** [comment]
Appium inspector displaying  AX error for all locators Accessibility Id: AX error -2520

<XCUIElementTypeApplication name="AX error -25205">
<XCUIElementTypeWindow name="AX error -25205">
<XCUIElementTypeOther name="AX error -25205">
<XCUIElementTypeNavigationBar name="Handstand.HSLoginView">
<XCUIElementTypeOther name="AX error -25205">
<XCUIElementTypeOther name="AX error -25205">
<XCUIElementTypeOther name="AX error -25205">
<XCUIElementTypeOther name="AX error -25205">
<XCUIElementTypeScrollView name="AX error -25205">
<XCUIElementTypeStaticText name="AX error -25205">
<XCUIElementTypeOther name="AX error -25205">
<XCUIElementTypeOther name="AX error -25205">
<XCUIElementTypeStaticText name="AX error -25205">
<XCUIElementTypeButton name="AX error -25205">
<XCUIElementTypeButton name="AX error -25205">
<XCUIElementTypeButton name="AX error -25205">
<XCUIElementTypeImage name="AX error -25205">
<XCUIElementTypeImage name="AX error -25205">
<XCUIElementTypeToolbar name="AX error -25205">
<XCUIElementTypeWindow name="AX error -25205">
<XCUIElementTypeWindow name="AX error -25205">
<XCUIElementTypeAny>
