### ISSUE TITLE
Appium Wont take a screenshot.

### ISSUE THREAD

**Issue by vladbelo** [appium/appium#8881]
## The problem

I cant take a screen shot of my android phone.

## Environment

* Appium version1.6
* 
* Desktop OS/version used to run Appium: Windows 10 
* N
* Mobile platform/version under test: Android 
* Real device or emulator/simulator: Real Device
* A
## Details

I can't take a screenshot of the android application.

## Link to Appium logs

```
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\vovan\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","192.168.56.101:5555","shell","/system/bin/rm","/data/local/tmp/screenshot.png;","/system/bin/screencap","-p","/data/local/tmp/screenshot.png"]
[ADB] Running 'C:\Users\vovan\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","192.168.56.101:5555","pull","/data/local/tmp/screenshot.png","C:\\Users\\vovan\\AppData\\Local\\Temp\\appium117619-412-kvoil4.ioblyaxlxr.png"]
[MJSONWP] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAABaAAAAoACAYAAABH9IXPAACAAElEQVR4AezBC5CddWHw4d//fd9z2VyWD6IIm4SViqIc2kphaEJpkaEedoShxVxE0W0TF3XqpRtirbeugUqdsW5iOx1bG+Ox7XTo7IJaW9sQb+NoN9FqsW3OIkOr4knihZTLObCXc3s/UmuLcQMJ7Nnsbn7PE4AUSZIkSZIkSZJmWYQkSZIkSZIkSR0QIUmSJEmSJElSB0RIkiRJkiRJktQBEZIkSZIkSZIkdUCEJEmSJEmSJEkdECFJkiRJkiRJUgdESJIkSZIkSZLUARGSJEmSJEmSJHVAhCRJkiRJkiRJHRAhSZIkSZIkSVIHREiSJEmSJEmS1AERkiRJkiRJkiR1QIQkSZIkSZIkSR0QIUmSJEmSJElSB0RIkiRJkiRJktQBEZIkSZIkSZIkdUCEJEmSJEmSJEkdECFJkiRJkiRJUgckSJIkSZKkBaFQKNDd3c0TVatVyuUy0mKTJAnNZpOF4p3vfCcXX3wxz8QnP/lJ/u7v/o6HH34YabFIkCRJkiRJ81KhUGDjxo2sXbuWQqHAkymXy+zdu5eRkRHK5TL6SatXr2bVqlWsXbuW0047jUKhwBGFQoHu7m6OpVqtUi6XOaJcLvPII4+wd+9eDhw4QKVSQZ1RKBQ4dOgQDz30EAvFxRdfzBVXXMEz8c1vfpPPfOYzSItJgiRJkiRJmlc2bNjAW9/6VlatWsXxKhQKFAoFBgYGOHDgAB/4wAcYHR3lVLV27VrWrl3LZZddRqFQoLu7m6eju7ubtWvXcsTatWt5omq1SrlcZmxsjL1797J37170zBUKBXp6ejh06BCSFr4ESZIkSZI0L1x22WXs2LGDVatW8UysWrWKD37wg7z1rW9ly5YtjI2Nsdh1d3dz9dVX09fXx2WXXUZ3dzed1t3dzdq1a1m7di1HVKtVxsbG2L17N3fddRfVahWdmEKhQE9PD5IWjwRJkiRJknRSdXd3c8stt7Bx...
[HTTP] <-- GET /wd/hub/session/70f30deb-47e5-428f-97e6-f9ee456074c6/screenshot 200 82070 ms - 2238174 
[BaseDriver] Shutting down because we waited 200 seconds for a command
[AndroidDriver] Shutting down Android driver
[Appium] Closing session, cause was 'New Command Timeout of 200 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'
[Appium] Removing session 70f30deb-47e5-428f-97e6-f9ee456074c6 from our master session list
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\vovan\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","192.168.56.101:5555","shell","am","force-stop","com.disney.mdx.wdw.google"]
[ADB] Pressing the HOME button
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\vovan\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","192.168.56.101:5555","shell","input","keyevent",3]
[AndroidBootstrap] Sending command to android: {"cmd":"shutdown"}
[AndroidBootstrap] Received command result from bootstrap
[UiAutomator] Shutting down UiAutomator
[UiAutomator] Moving to state 'stopping'
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"shutdown"}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type SHUTDOWN
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":"OK, shutting down"}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Closed client connection
[AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: numtests=1

[AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: stream=.

[AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner

[AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: test=testRunServer

[AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap

[AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: current=1

[AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS_CODE: 0

[UiAutomator] UiAutomator shut down normally
[UiAutomator] Moving to state 'stopped'
[ADB] Attempting to kill all uiautomator processes
[ADB] Getting all processes with uiautomator
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\vovan\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","192.168.56.101:5555","shell","ps"]
[ADB] No uiautomator process found to kill, continuing...
[UiAutomator] Moving to state 'stopped'
[Logcat] Stopping logcat capture
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\vovan\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","192.168.56.101:5555","shell","am","force-stop","io.appium.unlock"]
[AndroidDriver] Not cleaning generated files. Add `clearSystemFiles` capability if wanted.
```

## Code To Reproduce Issue [ Good To Have ]

```java
import java.awt.Dimension;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;
import java.util.concurrent.TimeUnit;

import org.apache.commons.io.FileUtils;
import org.junit.After;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.ScreenOrientation;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.touch.TouchActions;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.DriverCommand;

import com.google.common.collect.ImmutableMap;

import io.appium.java_client.MobileDriver;
import io.appium.java_client.MobileElement;
import io.appium.java_client.MultiTouchAction;
import io.appium.java_client.SwipeElementDirection;
import io.appium.java_client.TouchAction;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.remote.MobileCapabilityType;
import io.appium.java_client.remote.MobilePlatform;

public class desiredcap {
	AndroidDriver driver;
	
	
	@Test
public void test() throws InterruptedException, IOException {
		File appDir = new File("src");
		File app = new File(appDir, "com.disney.mdx.wdw.google.apk");
		
		DesiredCapabilities cap = new DesiredCapabilities();
		cap.setCapability(MobileCapabilityType.PLATFORM_NAME, MobilePlatform.ANDROID);
		cap.setCapability(MobileCapabilityType.DEVICE_NAME, "Android Device");
		cap.setCapability(MobileCapabilityType.APP_PACKAGE, "com.disney.mdx.wdw.google");
		cap.setCapability(MobileCapabilityType.TAKES_SCREENSHOT, "true");
        cap.setCapability(MobileCapabilityType.APP_ACTIVITY, "com.disney.wdpro.android.mdx.activities.LoaderActivity");
		cap.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, "200");
		cap.setCapability(MobileCapabilityType.APP, app.getAbsolutePath());
		
		AndroidDriver driver = new AndroidDriver(new URL("http://0.0.0.0:4723/wd/hub"), cap);
		driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		driver.findElementById("com.disney.mdx.wdw.google:id/pulldown_image").click();
		
		
		

		//driver.findElementById("com.disney.mdx.wdw.google:id/tutorial_button").click();
		
		
		List<WebElement> abc = driver.findElements(By.className("android.widget.TextView"));
		//abc.get(2);
		TouchAction t = new TouchAction(driver);
		t.tap(abc.get(2)).perform();
		driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		
	
		driver.findElement(By.xpath("//android.widget.TextView[@text='IllumiNations: Reflections of Earth']")).click();
		driver.findElement(By.xpath("//android.widget.TextView[@text='Find on Map']")).click();
		driver.navigate().back();
		driver.navigate().back();
		driver.scrollTo("Portobello Country Italian Trattoria").click();//
		
		File file = null;
		file = driver.getScreenshotAs(OutputType.FILE);
		FileUtils.copyFile(file, new File("C:\\image.png"));
		
		
		
		
		
	
		
		
		}
	
		
}
	```

**Comment by dpgraham** [comment]
Can you try increasing `newCommandTimeout` capability and see if that fixes it.

**Comment by vladbelo** [comment]
java.io.FileNotFoundException: C:\image.png (Access is denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at org.apache.commons.io.FileUtils.doCopyFile(FileUtils.java:1139)
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1091)
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1038)
	at desiredcap.test(desiredcap.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
I get on eclipse failure trace:

**Comment by pavanbachu0604** [comment]
Can you try "screenshotWaitTimeout" as capability

**Comment by mykola-mokhnach** [comment]
Try to get the screenshot as byte stream (OutputType.BYTES) and then store it into a file.

```java
final byte[] image = ((TakesScreenshot) driver).getScreenshotAs(OutputType.BYTES);
try (BufferedOutputStream bos = new BufferedOutputStream(new FileOutputStream(yourFile))) {
  bos.write(image);
  bos.flush();
}
```

**Comment by vladbelo** [comment]
screenshotWaitTimeout does not support Android

**Comment by mykola-mokhnach** [comment]
Also try with Appium 1.6.6-beta - we did some improvements to screenshoting logic there

**Comment by vladbelo** [comment]
final byte[] image = ((TakesScreenshot) driver).getScreenshotAs(OutputType.BYTES);
		try (BufferedOutputStream bos = new BufferedOutputStream(new FileOutputStream("C:\\image.png"))) {
		  bos.write(image);
		  bos.flush();

java.io.FileNotFoundException: C:\image.png (Access is denied) ---- eclipse trace failure.
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at desiredcap.test(desiredcap.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by vladbelo** [comment]
Ok ill try my Appium is 1.6.5

**Comment by vladbelo** [comment]
I downloaded 1.6.6 beta from https://libraries.io/npm/appium. How do you run appium. I don't see appium.exe. file in the folder.

**Comment by dpgraham** [comment]
To run Appium on windows:

* Install NodeJS (https://nodejs.org/en/download/)
* Open cmd and install appium with the command `npm install -g appium`
* Run `appium` from cmd
* This will start the server at port 4723 by default; make sure any other instances of appium are closed

**Comment by mykola-mokhnach** [comment]
> java.io.FileNotFoundException: C:\image.png (Access is denied) ---- eclipse trace failure.

On Windows you cannot create files in the partition's root folder - this is automatically prevented by UAC unless it is disabled or your process is running with admin privileges.

**Comment by dpgraham** [comment]
This looks like it's not an Appium issue but rather a problem with saving to a directory you don't have permissions to save to (as per mykola's comment).

Closing this as a non Appium issue.

**Comment by vladbelo** [comment]
When installing appium from cmd. I get this error.

appium-uiautomator2-driver@0.4.4 install: `gulp prepublish && node ./bin/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the appium-uiautomator2-driver@0.4.4 install script 'gulp prepublish && node ./bin/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the appium-uiautomator2-driver package,
npm ERR! not with npm itself.
