### ISSUE TITLE
WebDriverException: Message: A session is either terminated or not started

### ISSUE THREAD

**Issue by wangtao169447** [appium/appium#8911]
## The problem

i connect with a real android device by wifi mode(adb tcpip 5555, adb connect xxxx), however, sometimes the devices will lost connect with the pc( which run appium script), and then throw WebDriverException: Message: A session is either terminated or not started exception.

despite i can reconnect with the android device , however , appium still does not work.

**Comment by mykola-mokhnach** [comment]
It's hard to say anything without logs and environment information.

**Comment by wangtao169447** [comment]
@mykola-mokhnach 
https://gist.github.com/wangtao169447/678ce781553048980a25c1e21e02a6a4

enviroment:
appium:1.6.5
devices:nexus 5 4.4.4
pc:mac os
communicate with phone type: by wifi mode

thanks

**Comment by mykola-mokhnach** [comment]
> [AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements selector:UiSelector[CLASS=android.widget.Button]
> [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Element[] is null: (0)
> [debug] [UiAutomator] Moving to state 'stopped'
> [debug] [AndroidDriver] Shutting down Android driver
> [Appium] Closing session, cause was 'UiAUtomator shut down unexpectedly'

Here you can see that UIAutomator has been unexpectedly shut down. I don't know hat was the reason  for that though.

**Comment by wangtao169447** [comment]
@mykola-mokhnach what can i do ,to help you find the reason?
i also wander why the uiautomator shut down.

**Comment by mykola-mokhnach** [comment]
There might be multiple reasons. I'd try to change location strategy, check if the stuff works manually (maybe, the app under test behaves not as expected)...

**Comment by wangtao169447** [comment]
i update appium,
and now ,throw this kind of exception:
Error: Android bootstrap socket crashed: Error: read ECONNRESET
    at Socket.<anonymous> (../../lib/bootstrap.js:86:21)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:62:8)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)

**Comment by wangtao169447** [comment]
@mykola-mokhnach 
i just disconnect the connection between android device and appium server, and reconnect.
however , appium server throw this kind of exception:
Error: Android bootstrap socket crashed: Error: read ECONNRESET
at Socket. (../../lib/bootstrap.js:86:21)
at emitOne (events.js:115:13)
at Socket.emit (events.js:210:7)
at emitErrorNT (internal/streams/destroy.js:62:8)
at _combinedTickCallback (internal/process/next_tick.js:102:11)
at process._tickCallback (internal/process/next_tick.js:161:9)

**Comment by jlipps** [comment]
@wangtao169447 you can't disconnect the device during a test. is there something that you're trying to do here?

**Comment by jlipps** [comment]
closing due to inactivity
