### ISSUE TITLE
appium-xcuitest-driver: SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by BalabN** [appium/appium#8920]
## SyntaxError: Unexpected token import

Steps to reproduce:
1. Install latest appium from npm and all dependencies and environment
2. clone https://github.com/appium/appium-xcuitest-driver
3. Setup WDA for real device on just cloned repo
4. replace appium node model with the new cloned one
5. Run appium or just run in terminal "appium -v"

## Environment

* Appium: 1.6.5
* MacOS Sierra 10.12.6
* Node.js: v8.1.4
* npm: 5.0.3
* iOS 9>
* Real device
* Appium java client

## Details

```
/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/index.js:3
import yargs from 'yargs';
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (../../lib/appium.js:10:60)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (../../lib/main.js:13:39)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

## Code To Reproduce Issue [ Good To Have ]

```
AppiumServiceBuilder app =
                new AppiumServiceBuilder()
                        .usingAnyFreePort()
                        .withAppiumJS(new File("/usr/local/lib/node_modules/appium/build/lib/main.js"))
                        .withArgument(() -> "--log-level", log.isDebugEnabled() ? "debug" : "info")
                        .withLogFile(new File(appiumLogPath))
                        .withArgument(() -> "--command-timeout", "180");

        service = AppiumDriverLocalService.buildService(app);
driver = new IOSDriver(service.getUrl(), capabilities);
```

**Comment by imurchie** [comment]
Do _not_ just shove a random version of a package into the structure of Appium. Update the whole thing: `npm uninstall -g appium && npm install -g appium@beta`.

**Comment by BalabN** [comment]
Ok then we found it 😄 I didn't want to use the beta version on our production that is why I wanted to update just the part... I will test and close the linked issue then

**Comment by BalabN** [comment]
Closing as cannot reproduce.
