### ISSUE TITLE
Sdk '10.2' was not in list of simctl sdks ... i am currently having this issue on  the appium desktop version 1.6.5... this desktop version is so confusing..i am not able to run any ios tests :(

### ISSUE THREAD

**Issue by sarozNep** [appium/appium#8931]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by imurchie** [comment]
What version of Xcode do you have? Can you paste the output of running the
command "xcrun simctl list"? And can you provide the Appium server logs (as
a link to a [gist](https://gist.github.com))?

**Comment by sarozNep** [comment]
xcode version = 8.2.1

The appium log is as follows;

[Appium] Welcome to Appium v1.6.5
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> GET /wd/hub/sessions {}
[MJSONWP] Calling AppiumDriver.getSessions() with args: []
[MJSONWP] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 13 ms - 40 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/muzzley/Desktop/ios-uicatalog-master/Build/Products/Debug-iphonesimulator/UICatalog.app","deviceName":"iphone 6s","noReset":true,"platformName":"iOS","platformVersion":"10.2","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/muzzley/Desktop/ios-uicatalog-master/Build/Products/Debug-iphonesimulator/UICatalog.app","deviceName":"iphone 6s","noReset":true,"platformName":"iOS","platformVersion":"10.2","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1501258550233 (17:15:50 GMT+0100 (WEST))
[Appium] Requested iOS support with version >= 10, using XCUITest driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
[Appium] Creating new XCUITestDriver (v2.30.0) session
[Appium] Capabilities:
[Appium]   app: '/Users/muzzley/Desktop/ios-uicatalog-master/Build/Products/Debug-iphonesimulator/UICatalog.app'
[Appium]   deviceName: 'iphone 6s'
[Appium]   noReset: true
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '10.2'
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true
[XCUITest] XCUITestDriver version: 2.30.0
[BaseDriver] Session created with session id: 42ced62a-d315-4ade-9543-8c474b4ca3a0
[XCUITest] Xcode version set to '8.3.2' (tools v8.3.2.0.1.1492020469)
[XCUITest] iOS SDK Version set to '10.3'
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1501258550311 (17:15:50 GMT+0100 (WEST))
[XCUITest] Error: Sdk '10.2' was not in list of simctl sdks
    at getDevices$ (/private/var/folders/gm/49c1hvk93b91915wrh1lr95m0000gp/T/AppTranslocation/E3CEE5CC-E927-4FC2-B0BE-1AC91D59D1D8/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/node-simctl/lib/simctl.js:230:13)
    at tryCatch (/private/var/folders/gm/49c1hvk93b91915wrh1lr95m0000gp/T/AppTranslocation/E3CEE5CC-E927-4FC2-B0BE-1AC91D59D1D8/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/private/var/folders/gm/49c1hvk93b91915wrh1lr95m0000gp/T/AppTranslocation/E3CEE5CC-E927-4FC2-B0BE-1AC91D59D1D8/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/private/var/folders/gm/49c1hvk93b91915wrh1lr95m0000gp/T/AppTranslocation/E3CEE5CC-E927-4FC2-B0BE-1AC91D59D1D8/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/private/var/folders/gm/49c1hvk93b91915wrh1lr95m0000gp/T/AppTranslocation/E3CEE5CC-E927-4FC2-B0BE-1AC91D59D1D8/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: Sdk '10.2' was not in list of simctl sdks
    at getDevices$ (/private/var/folders/gm/49c1hvk93b91915wrh1lr95m0000gp/T/AppTranslocation/E3CEE5CC-E927-4FC2-B0BE-1AC91D59D1D8/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/node-simctl/lib/simctl.js:230:13)
    at tryCatch (/private/var/folders/gm/49c1hvk93b91915wrh1lr95m0000gp/T/AppTranslocation/E3CEE5CC-E927-4FC2-B0BE-1AC91D59D1D8/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/private/var/folders/gm/49c1hvk93b91915wrh1lr95m0000gp/T/AppTranslocation/E3CEE5CC-E927-4FC2-B0BE-1AC91D59D1D8/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/private/var/folders/gm/49c1hvk93b91915wrh1lr95m0000gp/T/AppTranslocation/E3CEE5CC-E927-4FC2-B0BE-1AC91D59D1D8/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/private/var/folders/gm/49c1hvk93b91915wrh1lr95m0000gp/T/AppTranslocation/E3CEE5CC-E927-4FC2-B0BE-1AC91D59D1D8/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[MJSONWP] Encountered internal error running command: Error: Sdk '10.2' was not in list of simctl sdks
    at getDevices$ (/private/var/folders/gm/49c1hvk93b91915wrh1lr95m0000gp/T/AppTranslocation/E3CEE5CC-E927-4FC2-B0BE-1AC91D59D1D8/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/node-simctl/lib/simctl.js:230:13)
    at tryCatch (/private/var/folders/gm/49c1hvk93b91915wrh1lr95m0000gp/T/AppTranslocation/E3CEE5CC-E927-4FC2-B0BE-1AC91D59D1D8/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/private/var/folders/gm/49c1hvk93b91915wrh1lr95m0000gp/T/AppTranslocation/E3CEE5CC-E927-4FC2-B0BE-1AC91D59D1D8/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/private/var/folders/gm/49c1hvk93b91915wrh1lr95m0000gp/T/AppTranslocation/E3CEE5CC-E927-4FC2-B0BE-1AC91D59D1D8/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/private/var/folders/gm/49c1hvk93b91915wrh1lr95m0000gp/T/AppTranslocation/E3CEE5CC-E927-4FC2-B0BE-1AC91D59D1D8/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 258 ms - 178

**Comment by sarozNep** [comment]
output of the command

@imurchie 
Last login: Fri Jul 28 15:38:55 on ttys000
V0od0ochild:~ xx$ xcrun simctl list
== Device Types ==
iPhone 4s (com.apple.CoreSimulator.SimDeviceType.iPhone-4s)
iPhone 5 (com.apple.CoreSimulator.SimDeviceType.iPhone-5)
iPhone 5s (com.apple.CoreSimulator.SimDeviceType.iPhone-5s)
iPhone 6 (com.apple.CoreSimulator.SimDeviceType.iPhone-6)
iPhone 6 Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-6-Plus)
iPhone 6s (com.apple.CoreSimulator.SimDeviceType.iPhone-6s)
iPhone 6s Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-6s-Plus)
iPhone 7 (com.apple.CoreSimulator.SimDeviceType.iPhone-7)
iPhone 7 Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-7-Plus)
iPhone SE (com.apple.CoreSimulator.SimDeviceType.iPhone-SE)
iPad 2 (com.apple.CoreSimulator.SimDeviceType.iPad-2)
iPad Retina (com.apple.CoreSimulator.SimDeviceType.iPad-Retina)
iPad Air (com.apple.CoreSimulator.SimDeviceType.iPad-Air)
iPad Air 2 (com.apple.CoreSimulator.SimDeviceType.iPad-Air-2)
iPad Pro (9.7-inch) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro--9-7-inch-)
iPad Pro (12.9-inch) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro)
Apple TV 1080p (com.apple.CoreSimulator.SimDeviceType.Apple-TV-1080p)
Apple Watch - 38mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-38mm)
Apple Watch - 42mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-42mm)
Apple Watch Series 2 - 38mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-2-38mm)
Apple Watch Series 2 - 42mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-2-42mm)
== Runtimes ==
iOS 10.3 (10.3 - 14E269) (com.apple.CoreSimulator.SimRuntime.iOS-10-3)
tvOS 10.2 (10.2 - 14W260) (com.apple.CoreSimulator.SimRuntime.tvOS-10-2)
watchOS 3.2 (3.2 - 14V243) (com.apple.CoreSimulator.SimRuntime.watchOS-3-2)
== Devices ==
-- iOS 10.3 --
    iPhone 5 (B4ADA368-F654-41D0-9BE3-95485CEE4E46) (Shutdown)
    iPhone 5s (DACDC209-66B6-413E-9D01-70D4DED576F6) (Shutdown)
    iPhone 6 (0E64EACE-6064-4F73-B459-425F3F61962A) (Shutdown)
    iPhone 6 Plus (3298508E-9AD2-46DD-8804-AD8EE91DB0DC) (Shutdown)
    iPhone 6s (0617B6B6-1855-41BE-883F-107590232231) (Shutdown)
    iPhone 6s Plus (519B35B5-206A-43F7-9B98-428EC54CA2C0) (Shutdown)
    iPhone 7 (144E902D-71BD-460B-8FFF-2F9EE826289F) (Shutdown)
    iPhone 7 Plus (62F0F124-2066-49A9-B051-ED0B130EABDC) (Shutdown)
    iPhone SE (BC1FF285-DE6E-4D93-A48B-CD83AFD900AD) (Shutdown)
    iPad Air (FD9FBA01-F235-40E6-BAA8-37F002375C12) (Shutdown)
    iPad Air 2 (EB3C5E88-3E79-47E5-B085-C1E43F3490E5) (Shutdown)
    iPad Pro (9.7 inch) (FB4329E5-6E5C-4BE1-B480-2FFF4911F975) (Shutdown)
    iPad Pro (12.9 inch) (0A4AB87D-D36B-4DF1-B5A2-00682F149F2A) (Shutdown)
-- tvOS 10.2 --
    Apple TV 1080p (39B42410-495C-4CF1-8E42-8216A00B4D1B) (Shutdown)
-- watchOS 3.2 --
    Apple Watch - 38mm (7EEC5A9E-0772-460D-9576-F7E708143E95) (Shutdown)
    Apple Watch - 42mm (18B1318D-A60B-45DB-93E1-058B87283FD3) (Shutdown)
    Apple Watch Series 2 - 38mm (59AF180E-A1D0-4150-9A99-1F2B1AC90FDF) (Shutdown)
    Apple Watch Series 2 - 42mm (F2484CFF-558C-47E8-9FCA-63BC071CC28A) (Shutdown)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.iOS-10-2 --
    iPhone 5 (2B043DDC-D52A-4546-8CD3-B9035EE8731F) (Shutdown) (unavailable, runtime profile not found)
    iPhone 5s (877F2EF8-108E-4EA9-9608-62928003AE10) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6 (049E59C2-9A02-4BAF-A271-9AB8DCFF5A8D) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6 Plus (73AEC99B-9649-49EC-9CE1-7DBE2815B0C4) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6s (FBA5F1DB-19F2-4ED5-AA2F-AD24CFF9B591) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6s Plus (B3F0A7BA-3197-487D-9A92-F835515E6665) (Shutdown) (unavailable, runtime profile not found)
    iPhone 7 (8D1C148A-53B7-4C42-A501-C53260EF2D2C) (Shutdown) (unavailable, runtime profile not found)
    iPhone 7 Plus (E21FF695-10AF-4BF7-AA4E-F00554AE7041) (Shutdown) (unavailable, runtime profile not found)
    iPhone SE (6F36AF9A-3E92-40E1-A47E-2635916CB49A) (Shutdown) (unavailable, runtime profile not found)
    iPad Retina (75B5D2A6-ABBA-411C-A914-3E13C638E22B) (Shutdown) (unavailable, runtime profile not found)
    iPad Air (C23AA53D-B912-4BE5-A62E-F31B00D50261) (Shutdown) (unavailable, runtime profile not found)
    iPad Air 2 (FC406B6F-8283-4BC8-B9D7-3F70D86DCC6D) (Shutdown) (unavailable, runtime profile not found)
    iPad Pro (9.7 inch) (16DE7B8B-FCA1-4CE6-A61C-2683A4559292) (Shutdown) (unavailable, runtime profile not found)
    iPad Pro (12.9 inch) (AB7253AB-19C2-439C-B77C-129011A36E96) (Shutdown) (unavailable, runtime profile not found)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.tvOS-10-1 --
    Apple TV 1080p (077639AB-83EE-43EE-9D1E-8E1FF61941AE) (Shutdown) (unavailable, runtime profile not found)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.watchOS-3-1 --
    Apple Watch - 38mm (D8FB875F-8EEC-407A-B9BA-329C6F63E4BC) (Shutdown) (unavailable, runtime profile not found)
    Apple Watch - 42mm (E21E0524-6F63-47F5-A67D-A7BD123DB665) (Shutdown) (unavailable, runtime profile not found)
    Apple Watch Series 2 - 38mm (A3BFD4E2-AFDC-4262-BEA8-BAF92FF574BE) (Shutdown) (unavailable, runtime profile not found)
    Apple Watch Series 2 - 42mm (9DF950F9-1767-46A9-9FC0-0549184623C4) (Shutdown) (unavailable, runtime profile not found)
== Device Pairs ==
F439A9C3-FE49-496F-80C3-215427EC3BF9 (active, disconnected)
    Watch: Apple Watch - 38mm (7EEC5A9E-0772-460D-9576-F7E708143E95) (Shutdown)
    Phone: iPhone 6s (0617B6B6-1855-41BE-883F-107590232231) (Shutdown)
DA9C0BB7-ED27-420F-883D-4DB61352D213 (active, disconnected)
    Watch: Apple Watch - 42mm (18B1318D-A60B-45DB-93E1-058B87283FD3) (Shutdown)
    Phone: iPhone 6s Plus (519B35B5-206A-43F7-9B98-428EC54CA2C0) (Shutdown)
BBF63E63-4307-4953-B5E0-28084D655BE4 (active, disconnected)
    Watch: Apple Watch Series 2 - 38mm (59AF180E-A1D0-4150-9A99-1F2B1AC90FDF) (Shutdown)
    Phone: iPhone 7 (144E902D-71BD-460B-8FFF-2F9EE826289F) (Shutdown)
BAAEF58C-431A-47C1-B778-322A352F38D8 (active, disconnected)
    Watch: Apple Watch Series 2 - 42mm (F2484CFF-558C-47E8-9FCA-63BC071CC28A) (Shutdown)
    Phone: iPhone 7 Plus (62F0F124-2066-49A9-B051-ED0B130EABDC) (Shutdown)
C6D88D8C-9302-4C1E-B612-0B1F533AEBD4 (unavailable)
    Watch: Apple Watch Series 2 - 38mm (A3BFD4E2-AFDC-4262-BEA8-BAF92FF574BE) (Shutdown)
    Phone: iPhone 7 (8D1C148A-53B7-4C42-A501-C53260EF2D2C) (Shutdown)
5453D2F9-4091-4298-A031-EF39C93A4D02 (unavailable)
    Watch: Apple Watch Series 2 - 42mm (9DF950F9-1767-46A9-9FC0-0549184623C4) (Shutdown)
    Phone: iPhone 7 Plus (E21FF695-10AF-4BF7-AA4E-F00554AE7041) (Shutdown)
@

**Comment by mykola-mokhnach** [comment]
As you can see above there is no available simulators with iOS 10.2. You should either use 10.3 as platformVersion value (and set the device name to **iPhone 6s**) or download and install the matching SDK from Xcode preferences
