### ISSUE TITLE
[debug] [AndroidDriver] Called deleteSession but bootstrap wasn't active [MJSONWP] Encountered internal error running command: Error: Unable to find an active device or emulator with OS 5.1. The following are available: 41003cc7e40b12af (6.0.1)

### ISSUE THREAD

**Issue by weixiangyang** [appium/appium#8938]
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"Android","platformVersion":"5.1","app":"/Users/weixiangyang/Downloads/cnyaomaitongappdaily_v250_f76f69d8-974b-4aed-aaf0-65ec0f535d04.apk","appPackage":"cn.yaomaitong.app.daily","automationName":"Appium","deviceName":"SM-N910K"}}

[MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"Android",...

[Appium] Creating new AndroidDriver session

[Appium] Capabilities:
[Appium] platformName: 'Android'
[Appium] platformVersion: '5.1'
[Appium] app: '/Users/weixiangyang/Downloads/cnyaomaitongappdaily_v250_f76f69d8-974b-4aed-aaf0-65ec0f535d04.apk'
[Appium] appPackage: 'cn.yaomaitong.app.daily'
[Appium] automationName: 'Appium'
[Appium] deviceName: 'SM-N910K'
[Appium] optionalIntentArguments: ''
[Appium] dontStopAppOnReset: true
[BaseDriver] Session created with session id: f42f9cd8-e047-40ba-8752-7ae852ab4bdd

[debug] [AndroidDriver] Getting Java version

[AndroidDriver] Java version is: 1.8.0_131

[ADB] Checking whether adb is present

[ADB] Using adb from /Users/weixiangyang/Library/Android/sdk/platform-tools/adb
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...

[debug] [ADB] 1 device(s) connected

[AndroidDriver] Looking for a device with Android 5.1
[debug] [ADB] Setting device id to 41003cc7e40b12af
[ADB] Getting device platform version
[debug] [ADB] Getting connected devices...

[debug] [ADB] 1 device(s) connected

[debug] [ADB] Running /Users/weixiangyang/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","41003cc7e40b12af","shell","getprop","ro.build.version.release"]

[AndroidDriver] Error: Unable to find an active device or emulator with OS 5.1. The following are available: 41003cc7e40b12af (6.0.1)
at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
at Object.callee$0$0$ (lib/android-helpers.js:154:16)
at tryCatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js💯21)
at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
at run (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
at flush (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
at _combinedTickCallback (internal/process/next_tick.js:67:7)
at process._tickCallback (internal/process/next_tick.js:98:9)
[Error: Unable to find an active device or emulator with OS 5.1. The following are available: 41003cc7e40b12af (6.0.1)]

[debug] [AndroidDriver] Shutting down Android driver

[MJSONWP] Encountered internal error running command: Error: Unable to find an active device or emulator with OS 5.1. The following are available: 41003cc7e40b12af (6.0.1)
at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
at Object.callee$0$0$ (lib/android-helpers.js:154:16)
at tryCatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js💯21)
at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
at run (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
at flush (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
at _combinedTickCallback (internal/process/next_tick.js:67:7)
at process._tickCallback (internal/process/next_tick.js:98:9)

[AndroidDriver] Cannot shut down Android driver; it has already shut down
[HTTP] <-- POST /wd/hub/session 500 275 ms - 247

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 9 ms - 83

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[HTTP] <-- GET /wd/hub/status 200 12 ms - 83
[HTTP] --> GET /wd/hub/sessions {}
[MJSONWP] Calling AppiumDriver.getSessions() with args: []
[MJSONWP] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 2 ms - 40
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"Android","platformVersion":"5.1","app":"/Users/weixiangyang/Downloads/cnyaomaitongappdaily_v250_f76f69d8-974b-4aed-aaf0-65ec0f535d04.apk","appPackage":"cn.yaomaitong.app.daily","automationName":"Appium","deviceName":"SM-N910K"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"Android",...
[Appium] Creating new AndroidDriver session
[Appium] Capabilities:
[Appium] platformName: 'Android'
[Appium] platformVersion: '5.1'
[Appium] app: '/Users/weixiangyang/Downloads/cnyaomaitongappdaily_v250_f76f69d8-974b-4aed-aaf0-65ec0f535d04.apk'
[Appium] appPackage: 'cn.yaomaitong.app.daily'
[Appium] automationName: 'Appium'
[Appium] deviceName: 'SM-N910K'
[Appium] optionalIntentArguments: ''
[Appium] dontStopAppOnReset: true
[BaseDriver] Session created with session id: 543bcf66-752a-4eb3-a0be-f31733be13aa
[debug] [AndroidDriver] Getting Java version

[AndroidDriver] Java version is: 1.8.0_131

[ADB] Checking whether adb is present

[ADB] Using adb from /Users/weixiangyang/Library/Android/sdk/platform-tools/adb
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[AndroidDriver] Looking for a device with Android 5.1
[debug] [ADB] Setting device id to 41003cc7e40b12af
[ADB] Getting device platform version
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/weixiangyang/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","41003cc7e40b12af","shell","getprop","ro.build.version.release"]

[AndroidDriver] Error: Unable to find an active device or emulator with OS 5.1. The following are available: 41003cc7e40b12af (6.0.1)
at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
at Object.callee$0$0$ (lib/android-helpers.js:154:16)
at tryCatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js💯21)
at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
at run (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
at flush (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
at _combinedTickCallback (internal/process/next_tick.js:67:7)
at process._tickCallback (internal/process/next_tick.js:98:9)
[Error: Unable to find an active device or emulator with OS 5.1. The following are available: 41003cc7e40b12af (6.0.1)]

[debug] [AndroidDriver] Shutting down Android driver

[MJSONWP] Encountered internal error running command: Error: Unable to find an active device or emulator with OS 5.1. The following are available: 41003cc7e40b12af (6.0.1)
at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
at Object.callee$0$0$ (lib/android-helpers.js:154:16)
at tryCatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js💯21)
at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
at run (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
at flush (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
at _combinedTickCallback (internal/process/next_tick.js:67:7)
at process._tickCallback (internal/process/next_tick.js:98:9)

[AndroidDriver] Cannot shut down Android driver; it has already shut down
[HTTP] <-- POST /wd/hub/session 500 226 ms - 247

**Comment by weixiangyang** [comment]
help me!

**Comment by SrinivasanTarget** [comment]
Hey @weixiangyang One liner will never give us any information to help. Fill out the form with detailed logs (in form of gist only). Else reach appium discuss forum to get instant help.

**Comment by weixiangyang** [comment]
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"Android","platformVersion":"5.1","app":"/Users/weixiangyang/Downloads/cnyaomaitongappdaily_v250_f76f69d8-974b-4aed-aaf0-65ec0f535d04.apk","appPackage":"cn.yaomaitong.app.daily","automationName":"Appium","deviceName":"SM-N910K"}}

[MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"Android",...

[Appium] Creating new AndroidDriver session

[Appium] Capabilities:
[Appium]   platformName: 'Android'
[Appium]   platformVersion: '5.1'
[Appium]   app: '/Users/weixiangyang/Downloads/cnyaomaitongappdaily_v250_f76f69d8-974b-4aed-aaf0-65ec0f535d04.apk'
[Appium]   appPackage: 'cn.yaomaitong.app.daily'
[Appium]   automationName: 'Appium'
[Appium]   deviceName: 'SM-N910K'
[Appium]   optionalIntentArguments: ''
[Appium]   dontStopAppOnReset: true
[BaseDriver] Session created with session id: f42f9cd8-e047-40ba-8752-7ae852ab4bdd

[debug] [AndroidDriver] Getting Java version

[AndroidDriver] Java version is: 1.8.0_131

[ADB] Checking whether adb is present

[ADB] Using adb from /Users/weixiangyang/Library/Android/sdk/platform-tools/adb
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...

[debug] [ADB] 1 device(s) connected

[AndroidDriver] Looking for a device with Android 5.1
[debug] [ADB] Setting device id to 41003cc7e40b12af
[ADB] Getting device platform version
[debug] [ADB] Getting connected devices...

[debug] [ADB] 1 device(s) connected

[debug] [ADB] Running /Users/weixiangyang/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","41003cc7e40b12af","shell","getprop","ro.build.version.release"]

[AndroidDriver] Error: Unable to find an active device or emulator with OS 5.1. The following are available: 41003cc7e40b12af (6.0.1)
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at Object.callee$0$0$ (lib/android-helpers.js:154:16)
    at tryCatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
 [Error: Unable to find an active device or emulator with OS 5.1. The following are available: 41003cc7e40b12af (6.0.1)]

[debug] [AndroidDriver] Shutting down Android driver

[MJSONWP] Encountered internal error running command: Error: Unable to find an active device or emulator with OS 5.1. The following are available: 41003cc7e40b12af (6.0.1)
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at Object.callee$0$0$ (lib/android-helpers.js:154:16)
    at tryCatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

[AndroidDriver] Cannot shut down Android driver; it has already shut down
[HTTP] <-- POST /wd/hub/session 500 275 ms - 247 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 9 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[HTTP] <-- GET /wd/hub/status 200 12 ms - 83 
[HTTP] --> GET /wd/hub/sessions {}
[MJSONWP] Calling AppiumDriver.getSessions() with args: []
[MJSONWP] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 2 ms - 40 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"Android","platformVersion":"5.1","app":"/Users/weixiangyang/Downloads/cnyaomaitongappdaily_v250_f76f69d8-974b-4aed-aaf0-65ec0f535d04.apk","appPackage":"cn.yaomaitong.app.daily","automationName":"Appium","deviceName":"SM-N910K"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"Android",...
[Appium] Creating new AndroidDriver session
[Appium] Capabilities:
[Appium]   platformName: 'Android'
[Appium]   platformVersion: '5.1'
[Appium]   app: '/Users/weixiangyang/Downloads/cnyaomaitongappdaily_v250_f76f69d8-974b-4aed-aaf0-65ec0f535d04.apk'
[Appium]   appPackage: 'cn.yaomaitong.app.daily'
[Appium]   automationName: 'Appium'
[Appium]   deviceName: 'SM-N910K'
[Appium]   optionalIntentArguments: ''
[Appium]   dontStopAppOnReset: true
[BaseDriver] Session created with session id: 543bcf66-752a-4eb3-a0be-f31733be13aa
[debug] [AndroidDriver] Getting Java version

[AndroidDriver] Java version is: 1.8.0_131

[ADB] Checking whether adb is present

[ADB] Using adb from /Users/weixiangyang/Library/Android/sdk/platform-tools/adb
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[AndroidDriver] Looking for a device with Android 5.1
[debug] [ADB] Setting device id to 41003cc7e40b12af
[ADB] Getting device platform version
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/weixiangyang/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","41003cc7e40b12af","shell","getprop","ro.build.version.release"]

[AndroidDriver] Error: Unable to find an active device or emulator with OS 5.1. The following are available: 41003cc7e40b12af (6.0.1)
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at Object.callee$0$0$ (lib/android-helpers.js:154:16)
    at tryCatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
 [Error: Unable to find an active device or emulator with OS 5.1. The following are available: 41003cc7e40b12af (6.0.1)]

[debug] [AndroidDriver] Shutting down Android driver

[MJSONWP] Encountered internal error running command: Error: Unable to find an active device or emulator with OS 5.1. The following are available: 41003cc7e40b12af (6.0.1)
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at Object.callee$0$0$ (lib/android-helpers.js:154:16)
    at tryCatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

[AndroidDriver] Cannot shut down Android driver; it has already shut down
[HTTP] <-- POST /wd/hub/session 500 226 ms - 247

**Comment by weixiangyang** [comment]
@SrinivasanTarget Hey, I updated my new journal, can you help me? emergency

**Comment by mykola-mokhnach** [comment]
> [Error: Unable to find an active device or emulator with OS 5.1. The following are available: 41003cc7e40b12af (6.0.1)]

I assume the error message is pretty clear there. Set the correct values for deviceName and platformVersion capabilities to find the connected device.

**Comment by weixiangyang** [comment]
@mykola-mokhnach thank you,I like you !

**Comment by zaygeee** [comment]
Hello, I have the same problem as you, how do you solve it? 
 
![image](https://user-images.githubusercontent.com/34417702/35319174-a58d9696-0119-11e8-971a-13cab3257e36.png)

**Comment by weixiangyang** [comment]
@zaygeee My deviceName and platformVersion capabilities were incorrectly filled, so I couldn't find the device.
