### ISSUE TITLE
UIAutomator2 Error: write EPIPE

### ISSUE THREAD

**Issue by wangtao169447** [appium/appium#8941]
## The problem

appium_server log:
Error: write EPIPE
    at exports._errnoException (util.js:1022:11)
    at WriteWrap.afterWrite (net.js:851:14)

python/ appium clinent log:
Traceback (most recent call last):
  File "/Users/june/Documents/demo.py", line 2409, in do_alert_handle
    self.click_specify_button(alert_handle.alert_activity)
  File "/Users/june/Documents/product/xmonkey/shoubai_test/android_uitraversal.py", line 2487, in click_specify_button
    print self.driver.page_source
  File "/Library/Python/2.7/site-packages/selenium-2.52.0-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 464, in page_source
    return self.execute(Command.GET_PAGE_SOURCE)['value']
  File "/Library/Python/2.7/site-packages/selenium-2.52.0-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 199, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/Library/Python/2.7/site-packages/selenium-2.52.0-py2.7.egg/selenium/webdriver/remote/remote_connection.py", line 395, in execute
    return self._request(command_info[0], url, body=data)
  File "/Library/Python/2.7/site-packages/selenium-2.52.0-py2.7.egg/selenium/webdriver/remote/remote_connection.py", line 463, in _request
    resp = opener.open(request, timeout=self._timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1200, in do_open
    r = h.getresponse(buffering=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1132, in getresponse
    response.begin()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 54] Connection reset by peer

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.5, UIAutomator2
* Last Appium version that did not exhibit the issue (if applicable): 1.6.5, UIAutomator
* Desktop OS/version used to run Appium:mac os
* Node.js version (unless using Appium.app|exe):v8.1.3
* Mobile platform/version under test:android 7.0
* Real device or emulator/simulator:real devices
* Appium CLI or Appium.app|exe: cli

**Comment by mykola-mokhnach** [comment]
Please provide full server log

**Comment by wangtao169447** [comment]
@mykola-mokhnach 
https://gist.github.com/wangtao169447/de8e492ff59e6284793876806d7695d9

thanks

**Comment by mykola-mokhnach** [comment]
For me it looks like random network connection issue. Does the problem happen always in the same place?

**Comment by wangtao169447** [comment]
however i do not think so.
because ,it can Stable repetition

**Comment by jlipps** [comment]
@wangtao169447 can you provide a repro case? You say that it can be reproduced reliably. Can you help us to do that? Otherwise I can't see what might be causing this.

**Comment by jlipps** [comment]
closing due to inactivity

**Comment by trix0** [comment]
can We reopen ?
https://gist.github.com/trix0/d2d57c28d0fa33d36f19ab2321d3ae8f

You can see in log a lot of screenshots. I need em to validate state. So basicaly what I do is i request screenshot I validate if its what it supoosed to be. If its not get another screenshot. I have set it up on 60 repeats. It fails around 45-46
