### ISSUE TITLE
Add "skipUnlock" capability to AndroidDriver (already exists in UiAutomator2Driver)

### ISSUE THREAD

**Issue by jgoldring** [appium/appium#8950]
## The problem

The release notes for 1.6.5 listed a feature:

> Add skipUnlock capability to skip the device unlock process.

I can't see anywhere in the documentation or in the code itself that indicates how to set this property. I have several Android 7.1.2 devices that fail to unlock. I see that there is a fix [https://github.com/appium/appium-android-driver/blob/9a9ee19a71ba106d5afdfd3d98731881b7571b44/docs/UNLOCK.md](url) but this entails having security set to pin, password, or pattern. I would rather keep the security to "none" and tell Appium to not try to unlock the device. When passing skipUnlock: true in to appium via the desiredCapabilities, it claims that skipUnlock is not recognized by Appium.

Is there a way to set this property?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Desktop OS/version used to run Appium: macOS Sierra 10.12.6
* Node.js version (unless using Appium.app|exe): 7.8.0
* Mobile platform/version under test: Android 7.1.2
* Real device or emulator/simulator: Real Google Pixel
* Appium CLI or Appium.app|exe: CLI

## Details
[Appium] Creating new AndroidDriver (v1.20.0) session
[Appium] Capabilities:
[Appium]   javascriptEnabled: true
[Appium]   locationContextEnabled: true
[Appium]   handlesAlerts: true
[Appium]   rotatable: true
[Appium]   browserName: 'chrome'
[Appium]   acceptSslCerts: true
[Appium]   chromeOptions: { args: [ '--no-sandbox', '--no-proxy-server' ] }
[Appium]   newCommandTimeout: 180000
[Appium]   platformName: 'ANDROID'
**[Appium]   skipUnlock: true**
[Appium]   udid: '<udid>'
[Appium]   deviceName: '<devicename>'
[Appium]   requestOrigins: { url: 'http://webdriver.io',
  version: '4.6.2',
  name: 'webdriverio' }
[debug] [AndroidDriver] AndroidDriver version: 1.20.0
[BaseDriver] The following capabilities were provided, but are not recognized by appium: javascriptEnabled, locationContextEnabled, handlesAlerts, rotatable, **skipUnlock**, baseUrl, requestOrigins.

**Comment by jlipps** [comment]
@jgoldring probably this capability is only for the UiAutomator2 driver; set the `automationName` capability to `UiAutomator2` (however I notice you're using Chrome, so you may run into https://github.com/appium/appium/issues/8897

**Comment by jlipps** [comment]
confirmed, the capability only exists for the Uiautomator2 driver.

**Comment by jgoldring** [comment]
Wow thanks for the quick update! Setting the automationName flag did the trick, but sadly I am now encountering #8897 as you said. Is there any potential timeframe or workaround for #8897 ?

**Comment by liuxuan30** [comment]
sorry to jump in, but how do I start UiAutomator2? I ran with below errors if specify `UiAutomator2`:
```
[debug] [ADB] Running '/Users/xuanliu/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","32ba64e20104","shell","pm","list","packages","io.appium.uiautomator2.server"]
[debug] [ADB] App is not installed
[debug] [ADB] Getting install status for io.appium.uiautomator2.server.test
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/xuanliu/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","32ba64e20104","shell","pm","list","packages","io.appium.uiautomator2.server.test"]
[debug] [ADB] App is not installed
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [UiAutomator2] Deleting UiAutomator2 server session
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: Error: Trying to proxy a session command without session id
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/xuanliu/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","32ba64e20104","shell","am","force-stop","com.facebook.katana"]
[debug] [ADB] Removing forwarded port socket connection: 8200 
[debug] [ADB] Running '/Users/xuanliu/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","32ba64e20104","forward","--remove","tcp:8200"]
[debug] [ADB] Running '/Users/xuanliu/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","32ba64e20104","forward","--remove","tcp:8200"]
[UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original error: 'Command '/Users/xuanliu/Library/Android/sdk/platform-tools/adb -P 5037 -s 32ba64e20104 forward --remove tcp\:8200' exited with code 1'; Stderr: 'error: listener 'tcp:8200' not found'; Code: '1''
[MJSONWP] Encountered internal error running command: Error: JAVA_HOME is not set currently. Please set JAVA_HOME.
    at getJavaHome (../../lib/helpers.js:110:9)
    at getJavaForOs (../../lib/helpers.js:99:17)
    at ADB.callee$0$0$ (../../../lib/tools/apk-signing.js:75:16)
    at tryCatch (/Users/xuanliu/aa/development/appium/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/xuanliu/aa/development/appium/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/xuanliu/aa/development/appium/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/Users/xuanliu/aa/development/appium/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/Users/xuanliu/aa/development/appium/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at new Promise (<anonymous>)
    at new F (/Users/xuanliu/aa/development/appium/appium/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/Users/xuanliu/aa/development/appium/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/Users/xuanliu/aa/development/appium/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/Users/xuanliu/aa/development/appium/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at ADB.callee$0$0 [as checkApkCert] (../../../lib/tools/apk-signing.js:75:13)
    at UiAutomator2Server.checkAndSignCert$ (../../lib/uiautomator2.js:113:33)
    at tryCatch (/Users/xuanliu/aa/development/appium/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/xuanliu/aa/development/appium/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/xuanliu/aa/development/appium/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/Users/xuanliu/aa/development/appium/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/Users/xuanliu/aa/development/appium/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at new Promise (<anonymous>)
    at new F (/Users/xuanliu/aa/development/appium/appium/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/Users/xuanliu/aa/development/appium/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/Users/xuanliu/aa/development/appium/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/Users/xuanliu/aa/development/appium/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at UiAutomator2Server.checkAndSignCert (../../lib/uiautomator2.js:113:15)
    at UiAutomator2Server.signAndInstall$ (../../lib/uiautomator2.js:107:16)
    at tryCatch (/Users/xuanliu/aa/development/appium/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/xuanliu/aa/development/appium/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/xuanliu/aa/development/appium/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/Users/xuanliu/aa/development/appium/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/Users/xuanliu/aa/development/appium/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at new Promise (<anonymous>)
    at new F (/Users/xuanliu/aa/development/appium/appium/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/Users/xuanliu/aa/development/appium/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/Users/xuanliu/aa/development/appium/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/Users/xuanliu/aa/development/appium/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at UiAutomator2Server.signAndInstall (../../lib/uiautomator2.js:106:54)
    at UiAutomator2Server.installServerApk$ (../../lib/uiautomator2.js:58:18)
    at tryCatch (/Users/xuanliu/aa/development/appium/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/xuanliu/aa/development/appium/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/xuanliu/aa/development/appium/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/xuanliu/aa/development/appium/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[HTTP] <-- POST /wd/hub/session 500 4894 ms - 190 
```
```

**Comment by kgp700** [comment]
How to set capability "skipUnlock" for appium java?
I tried this code but still do unlock

DesiredCapabilities capabilities = DesiredCapabilities.android();
capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME,"uiautomator2");
capabilities.setCapability("skipUnlock", true);

I think something wrong in my code

**Comment by mykola-mokhnach** [comment]
fixed in beta

**Comment by olyv** [comment]
Hi, `skipUnlock` is a great time-saver. But I couldn't find in the documentation http://appium.io/docs/en/writing-running-appium/caps. How can I explore all available desired capabilities?

**Comment by KazuCocoa** [comment]
The page will be updated in next release.

We're adding capabilities in the list when we found unlisted one. The unlock related capability has been added after `skipDeviceInitialization`.
https://github.com/appium/appium/blob/59a7dbcdbec761c8ac4adb3f09df779fe2db13ae/docs/en/writing-running-appium/caps.md

---

If you can dive into code, you can find `desired-caps.js` in drivers. (e.g. https://github.com/appium/appium-android-driver/blob/master/lib/desired-caps.js )
Not all of them are for drivers, but the file is all of the capabilities.

**Comment by olyv** [comment]
Perfect, thank you for quick response
