### ISSUE TITLE
Error: Unable to kill uiautomator processes. Original error: Unable to get pids for uiautomator.

### ISSUE THREAD

**Issue by 876072362** [appium/appium#8970]
问题描述：appium mac android真机，始终不能启动 apk

code: DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("platformName", "Android");
        capabilities.setCapability("device", "android");
        capabilities.setCapability("deviceName", "GWY0217124005987");
//        capabilities.setCapability("app", "path=/Users/clare/Downloads/wdw.apk");

        //设置安卓系统版本
        capabilities.setCapability("platformVersion", "7.0");

error 描述：[ADB] Error: Unable to kill uiautomator processes. Original error: Unable to get pids for uiautomator. Orginial error: Error executing adbExec. Original error: Command '/Users/clare/Downloads/android-sdk-macosx/platform-tools/adb -P 5037 -s GWY0217124005987 shell ps uiautomator' exited with code 1{"stdout":"bad pid 'uiautomator'\n","stderr":"","code":1}
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at ADB.callee$0$0$ (lib/tools/adb-commands.js:436:9)
    at tryCatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
 [Error: Unable to kill uiautomator processes. Original error: Unable to get pids for uiautomator. Orginial error: Error executing adbExec. Original error: Command '/Users/clare/Downloads/android-sdk-macosx/platform-tools/adb -P 5037 -s GWY0217124005987 shell ps uiautomator' exited with code 1{"stdout":"bad pi
[UiAutomator] Error while killing uiAutomator: Error: Unable to kill uiautomator processes. Original error: Unable to get pids for uiautomator. Orginial error: Error executing adbExec. Original error: Command '/Users/clare/Downloads/android-sdk-macosx/platform-tools/adb -P 5037 -s GWY0217124005987 shell ps uiautomator' exited with code 1{"stdout":"bad pid 'uiautomator'\n","stderr":"","code":1}
[debug] [UiAutomator] Starting UIAutomator
[debug] [ADB] Creating ADB subprocess with args: -P, 5037, -s, GWY0217124005987, shell, uiautomator, runtest, AppiumBootstrap.jar, -c, io.appium.android.bootstrap.Bootstrap, -e, pkg, com.renrun.aphone.app.UAT, -e, disableAndroidWatchers, false, -e, acceptSslCerts, false

d 'uiautomator'\n","stderr":"","code":1}]

[UiAutomator] UiAutomator exited unexpectedly with code 255, signal null

[debug] [UiAutomator] Moving to state 'stopped'

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

**Comment by jlipps** [comment]
please link to a gist of your full appium logs (from when you start the server up to the failure)

**Comment by mykola-mokhnach** [comment]
It looks like you are using an outdated Appium build. Please try version 1.6.5
