### ISSUE TITLE
appium server log is logging wrong time zone's time desiredCapabilities.setCapability("--local-timezone", false); not working

### ISSUE THREAD

**Issue by vikramvi** [appium/appium#9022]
## The problem

- while running tests I've observed that appium server was wrong time in wrong time zone. I'm into CEST time zone but it's logging time from UTC ( current - 2 hrs )
- I added capability desiredCapabilities.setCapability("--local-timezone", false); to explicitly 
 (  Reference: https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md ) 
- but still appium server log is showing time  = current time - 2:00 
- Eclipse console does show correct timestamp
- Tried desiredCapabilities.setCapability("--local-timezone", true) but same result

## Environment

* Appium version (or git revision) that exhibits the issue:  1.6.6-beta.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac 10.12.5
* Node.js version (unless using Appium.app|exe): v7.9.0
* Mobile platform/version under test: 
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: NA

## Details

mentioned in problem statement itself

## Link to Appium logs

[appium log](https://gist.github.com/vikramvi/34019b311857e67092d7b639f8949924) 

[Eclipse console log](https://gist.github.com/vikramvi/c298d512c5798d0ec15c81445b4f07a6)

## Code To Reproduce Issue [ Good To Have ]

NA

**Comment by imurchie** [comment]
`--local-timezone` is a server argument. It is used when invoking the Appium server:
```
appium --local-timezone
```

**Comment by vikramvi** [comment]
@imurchie 

I tried starting appium server as below

```
AppiumDriverLocalService driverLocalService1 = AppiumDriverLocalService
                                         .buildService(new AppiumServiceBuilder()
                                         	.withAppiumJS(new File("/usr/local/lib/node_modules/appium/build/lib/main.js"))
                    				.usingDriverExecutable(new File("/usr/local/bin/node"))
                                                 .usingPort(portNumber)
                                                 .withLogFile(logFile)
                                                 .withArgument(AndroidServerFlag.BOOTSTRAP_PORT_NUMBER, Integer.toString(bootstrapPortNumber) )
                                                 .withArgument(GeneralServerFlag.SESSION_OVERRIDE)
                                                 .withArgument(GeneralServerFlag.LOG_LEVEL, "debug")
                                                 .withArgument(GeneralServerFlag.CONFIGURATION_FILE, nodeConfigFilePath)
                                                 .withArgument(GeneralServerFlag.LOCAL_TIMEZONE, "true")  //THROWING EXCEPTION
                                         .withCapabilities(new DesiredCapabilities(ImmutableMap.of(MobileCapabilityType.UDID, UDID))));
                                 
                    	      driverLocalService1.start();
```

this is throwing exception 

 ```
/usr/local/lib/node_modules/appium/node_modules/argparse/lib/help/formatter.js:380
							          parts.forEach(function (part) {
							                ^
							  TypeError: parts.forEach is not a function
							      at _getLines (/usr/local/lib/node_modules/appium/node_modules/argparse/lib/help/formatter.js:380:15)
							      at HelpFormatter._formatUsage (/usr/local/lib/node_modules/appium/node_modules/argparse/lib/help/formatter.js:418:17)
							      at /usr/local/lib/node_modules/appium/node_modules/argparse/lib/help/formatter.js:67:17
							      at Array.map (native)
							      at Section.formatHelp (/usr/local/lib/node_modules/appium/node_modules/argparse/lib/help/formatter.js:61:26)
							      at HelpFormatter.formatHelp (/usr/local/lib/node_modules/appium/node_modules/argparse/lib/help/formatter.js:300:32)
							      at ArgumentParser.formatUsage (/usr/local/lib/node_modules/appium/node_modules/argparse/lib/argument_parser.js:1026:20)
							      at ArgumentParser.printUsage (/usr/local/lib/node_modules/appium/node_modules/argparse/lib/argument_parser.js:1082:27)
							      at ArgumentParser.error (/usr/local/lib/node_modules/appium/node_modules/argparse/lib/argument_parser.js:1156:8)
							      at ArgumentParser.parseArgs (/usr/local/lib/node_modules/appium/node_modules/argparse/lib/argument_parser.js:239:10)
							      at ArgumentParser.parser.parseArgs (../../lib/parser.js:752:29)
							      at main$ (../../lib/main.js:146:4)
							      at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
							      at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
							      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
							      at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
							      at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
							      at F (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
							      at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
							      at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
							      at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
							      at main (../../lib/main.js:152:13)
							      at asyncify (lib/asyncbox.js:65:15)
							      at Object.<anonymous> (../../lib/main.js:183:2)
							      at Module._compile (module.js:571:32)
							      at Object.Module._extensions..js (module.js:580:10)
							      at Module.load (module.js:488:32)
							      at tryModuleLoad (module.js:447:12)
							      at Function.Module._load (module.js:439:3)
							      at Module.runMain (module.js:605:10)
							      at run (bootstrap_node.js:423:7)
							      at startup (bootstrap_node.js:147:9)
							      at bootstrap_node.js:538:3
```

**Comment by imurchie** [comment]
What is the command that is being generated to invoke Appium?

**Comment by mykola-mokhnach** [comment]
>     .withArgument(GeneralServerFlag.LOCAL_TIMEZONE, "true")  
Probably, it expects boolean _true_ rather than String one

**Comment by vikramvi** [comment]
@mykola-mokhnach @imurchie Please clarify if this appium server side issue or appium java client ?

**Comment by mykola-mokhnach** [comment]
try to skip the second argument at all:  `withArgument(GeneralServerFlag.LOCAL_TIMEZONE)`

**Comment by vikramvi** [comment]
@mykola-mokhnach  your suggestion worked perfectly.

Now the remaining bug is; if someone wants to set explicit value for this argument say **true / false** , how it can be done ?

**Comment by mykola-mokhnach** [comment]
For this particular flag there are two possible states - it either exists or not. So, setting the falue to "false" should just emulate the argument is not present. Anyway, this is an enhancement request to java client itself.

**Comment by vikramvi** [comment]
@mykola-mokhnach I think this is a bug and not an enhancement.

As per https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md, **default value is false** and **user needs to pass true flag for this** 

To get it work for now, I'm just adding the flag and it's taking its value as true by default instead of false as per documentation

**Comment by vikramvi** [comment]
have opened new issue https://github.com/appium/java-client/issues/694
