### ISSUE TITLE
Issue in launching uwa app

### ISSUE THREAD

**Issue by DeepthiBalla** [appium/appium#9027]
## The problem

Original error: Could not verify WinAppDriver install; re-run install

## Environment

* Appium version 1.1.0

## Details
I am new to automating windows app, installed Appium version 1.1.0 
and trying to launch calculator app , but getting error" An unknown server-side error occurred while processing the command. Original error: Could not verify WinAppDriver install; re-run install"

Haven't installed WinApp driver separately as Windows Application Driver is integrated with Appium

## Link to Appium logs

Result StackTrace:	
at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Appium.AppiumDriver`1.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Appium.AppiumDriver`1..ctor(Uri remoteAddress, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Appium.Windows.WindowsDriver`1..ctor(Uri remoteAddress, DesiredCapabilities desiredCapabilities)
   at WindowsAppTestingPractice.WindowsAppTests.testLaunch() in C:\Users\dballa\Documents\Visual Studio 2015\Projects\WindowsAppTestingPratice\WindowsAppTestingPratice\WindowsAppTests.cs:line 25
Result Message:	System.InvalidOperationException : An unknown server-side error occurred while processing the command. Original error: Could not verify WinAppDriver install; re-run install

## Code To Reproduce Issue [ Good To Have ]

using System;
using OpenQA.Selenium.Remote;
using NUnit.Framework;
using OpenQA.Selenium.Appium.Windows;

namespace WindowsAppTestingPractice
{
   
    public class WindowsAppTests
    {
        [Test]
        
        public void testLaunch()
        {
            WindowsDriver<WindowsElement> CalculatorSession;       

            var appCapabilities = new DesiredCapabilities();
            appCapabilities.SetCapability("app","Microsoft.WindowsCalculator_10.1604.21020.0_x64__8wekyb3d8bbwe");
            appCapabilities.SetCapability("platformName", "Windows");
            appCapabilities.SetCapability("deviceName", "WindowsPC");
            CalculatorSession = new WindowsDriver<WindowsElement>(new Uri("http://127.0.0.1:4723/wd/hub"), appCapabilities);
      
        }
    }
}

**Comment by imurchie** [comment]
Can you provide the Appium _server_ logs, as a link to a [gist](https://gist.github.com)? There is nothing that can be determined without them.

**Comment by DeepthiBalla** [comment]
Please find the Appium server logs below

The server is running
Start New SessionStop Server
[Appium] Welcome to Appium v1.6.5
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"Microsoft.WindowsCalculator_10.1604.21020.0_x64__8wekyb3d8bbwe","platformName":"Windows","deviceName":"WindowsPC"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"Microsoft.WindowsCalculator_10.1604.21020.0_x64__8wekyb3d8bbwe","platformName":"Windows","deviceName":"WindowsPC"},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1502841323651 (09:55:23 GMT+1000 (AUS Eastern Standard Time))
[Appium] Creating new WindowsDriver (v0.5.0) session
[Appium] Capabilities:
[Appium]   app: 'Microsoft.WindowsCalculator_10.1604.21020.0_x64__8wekyb3d8bbwe'
[Appium]   platformName: 'Windows'
[Appium]   deviceName: 'WindowsPC'
[BaseDriver] The following capabilities were provided, but are not recognized by appium: app.
[BaseDriver] Session created with session id: b72a19ef-8ce4-4925-bb79-fa4ece925129
[WinAppDriver] Verifying WinAppDriver is installed with correct checksum
[WinAppDriver] Deleting WinAppDriver session
[MJSONWP] Encountered internal error running command: Error: Could not verify WinAppDriver install; re-run install
    at WinAppDriver.start$ (C:\Users\dballa\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-windows-driver\lib\winappdriver.js:35:13)
    at tryCatch (C:\Users\dballa\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\dballa\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\dballa\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\dballa\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 39 ms - 190

**Comment by jlipps** [comment]
@DeepthiBalla 

```
npm uninstall -g appium
npm install -g appium
```

then try again. If it still doesn't work, first uninstall WinAppDriver manually, then follow the above steps.

**Comment by jlipps** [comment]
closing due to inactivity

**Comment by rijinjohn** [comment]
@jlipps 
I am also facing the same issue, tried npm install and uninstall, the problem  still existing

**Comment by pierrebaran** [comment]
@jlipps 
Encountered the same problem as described above, tried the fix but didn't solve anything.
