### ISSUE TITLE
still can not get performance type log when enable enablePerformanceLogging on 1.6.5

### ISSUE THREAD

**Issue by BeggarMainFact** [appium/appium#9050]
## The problem

appium driver enable enablePerformanceLogging capability, when invoke driver.manage().logs().get("performance"), I get error:
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: No logs of type 'performance' found

## Environment

* Appium version:1.6.5
* Desktop OS/version used to run Appium: mac 10.12
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:  iphone7(ios10.3.2)
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: 

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
Capabilities [{app=myapp, networkConnectionEnabled=false, noReset=true, databaseEnabled=false, version=, deviceName=testios1, platform=MAC, showIOSLog=true, newCommandTimeout=1800, platformVersion=10.3.2, webStorageEnabled=false, locationContextEnabled=false, useNewWDA=true, browserName=iOS, takesScreenshot=true, browsertype=iOS, javascriptEnabled=true, udid=49c66fd5932f5ce0d3b1d1afd19ae0ca2cb1d87b, platformName=iOS, enablePerformanceLogging=true, autoAcceptAlerts=true}]
Session ID: fea2e4b2-f7af-48d3-8b34-154872f74a3c
ERROR - CucumberListener           - Failure is: When the basic 'Personal Shopper' video call establish for Personal Shopper between 'mce','robinson'(| mce | ios | robinson | chrome | TestIosRec | Personal Shopper |)
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: No logs of type 'performance' found. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 184 milliseconds
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'bej00akq.cn.oracle.com', ip: '10.182.12.238', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-327.el7.x86_64', java.version: '1.8.0_121'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{app=myapp, networkConnectionEnabled=false, noReset=true, databaseEnabled=false, version=, deviceName=testios1, platform=MAC, showIOSLog=true, newCommandTimeout=1800, platformVersion=10.3.2, webStorageEnabled=false, locationContextEnabled=false, useNewWDA=true, browserName=iOS, takesScreenshot=true, browsertype=iOS, javascriptEnabled=true, udid=49c66fd5932f5ce0d3b1d1afd19ae0ca2cb1aaaaa, platformName=iOS, enablePerformanceLogging=true, autoAcceptAlerts=true}]
Session ID: fea2e4b2-f7af-48d3-8b34-154872f74a3c
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:216)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:168)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:635)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:40)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at org.openqa.selenium.remote.RemoteExecuteMethod.execute(RemoteExecuteMethod.java:35)
	at org.openqa.selenium.remote.RemoteLogs.getRemoteEntries(RemoteLogs.java:81)
	at org.openqa.selenium.remote.RemoteLogs.get(RemoteLogs.java:77)

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by imurchie** [comment]
Can you provide the _full_ Appium Server logs as a link to a [gist](https://gist.github.com)? Otherwise there is nothing that can be said.

**Comment by jlipps** [comment]
closing due to inactivity

**Comment by tfcardoso** [comment]
@imurchie I'm getting the same. Can you check what I'm doing wrong or if its an issue.

Appium: 1.8.0-beta3
Client: 6.0.0-BETA4
iOS11.2.5 - iPhone5S Real Device

Logs: https://gist.github.com/tfcardoso/7054d8abd4626052f0fd4f615f58e7ce

**Comment by imurchie** [comment]
If I remember correctly, performance logs in iOS are only available in a web context.
