### ISSUE TITLE
Appium settings app upgrade crashes 

### ISSUE THREAD

**Issue by JaniJegoroff** [appium/appium#9058]
## The problem

Given I have older Appium settings app installed to the device
When I try to use latest Appium beta server with newer Appium settings app
Then Appium settings app crashes in upgrade phase

## Environment

* Appium version (or git revision) that exhibits the issue: latest beta (v1.6.6-beta.4)
* Last Appium version that did not exhibit the issue (if applicable): v1.6.5
* Desktop OS/version used to run Appium: MacOS Sierra 10.12.6 (16G29)
* Node.js version (unless using Appium.app|exe): v7.2.0
* Mobile platform/version under test: Android 5.0.2
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI

## Details

```
[debug] [ADB] The installed "io.appium.settings" package is older than /usr/local/lib/node_modules/appium/node_modules/io.appium.settings/app/build/outputs/apk/settings_apk-debug.apk (1 < 3). Executing upgrade
```

Logcat
```
D/APPIUM SETTINGS(25261): Entering Appium settings
E/AndroidRuntime(25261): FATAL EXCEPTION: main
E/AndroidRuntime(25261): Process: io.appium.settings, PID: 25261
E/AndroidRuntime(25261): java.lang.RuntimeException: Unable to start activity ComponentInfo{io.appium.settings/io.appium.settings.Settings}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Set android.os.Bundle.keySet()' on a null object reference
E/AndroidRuntime(25261): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2411)
E/AndroidRuntime(25261): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2474)
E/AndroidRuntime(25261): 	at android.app.ActivityThread.access$800(ActivityThread.java:144)
E/AndroidRuntime(25261): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1359)
E/AndroidRuntime(25261): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(25261): 	at android.os.Looper.loop(Looper.java:155)
E/AndroidRuntime(25261): 	at android.app.ActivityThread.main(ActivityThread.java:5696)
E/AndroidRuntime(25261): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(25261): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(25261): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
E/AndroidRuntime(25261): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
E/AndroidRuntime(25261): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Set android.os.Bundle.keySet()' on a null object reference
E/AndroidRuntime(25261): 	at io.appium.settings.Settings.onCreate(Settings.java:42)
E/AndroidRuntime(25261): 	at android.app.Activity.performCreate(Activity.java:5958)
E/AndroidRuntime(25261): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129)
E/AndroidRuntime(25261): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2364)
E/AndroidRuntime(25261): 	... 10 more
E/ActivityManager(  714): App crashed! Process: io.appium.settings
W/ActivityManager(  714):   Force finishing activity io.appium.settings/.Settings
```

## Link to Appium logs

https://gist.github.com/JaniJegoroff/da268453c90f1332baee8d545ae6d623

**Comment by mykola-mokhnach** [comment]
Try to delete Appium Settings app manually and restart the test

**Comment by jlipps** [comment]
closing due to inactivity

**Comment by sarozNep** [comment]
I have the same issue with 1.7.0 . How to delete appium settings app manually ?
