### ISSUE TITLE
Appium 1.6.6-beta.4 throws error as not compatible withXcode  9.0 beta  

### ISSUE THREAD

**Issue by monism** [appium/appium#9072]
I installed appium 1.6.6-beta.4 but and XCode 9 , appium throws error as "[XCUITest] Error: Xcode version 9.0 is not yet supported"

Xcode: 9-beta
Appium: 1.6.6-beta.4

Logs:
------

[Appium]   clearSystemFiles: 'true'
[Appium]   --no-reset: false
[Appium]   platformVersion: '10.0'
[Appium]   automationName: 'XCUITest'
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'iPhone 7'
[debug] [XCUITest] XCUITestDriver version: 2.30.0
[BaseDriver] Capability 'clearSystemFiles' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by appium: --no-reset.
[BaseDriver] Session created with session id: 89f16c26-6fe0-424a-941a-69723a2ce292
[debug] [XCUITest] Xcode version set to '9.0' (tools v8.3.2.0.1.1492020469)
[debug] [XCUITest] iOS SDK Version set to '11.0'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1503479837745 (14:47:17 GMT+0530 (IST))
[XCUITest] Simulator udid not provided, using desired caps to create a new simulator
[XCUITest] Error: Xcode version 9.0 is not yet supported
    at handleUnsupportedXcode (../../lib/simulator.js:16:11)
    at getSimulator$ (../../lib/simulator.js:28:3)
    at tryCatch (/Users/monismajeed/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/monismajeed/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/monismajeed/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/monismajeed/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
 Error: Xcode version 9.0 is not yet supported
    at handleUnsupportedXcode (../../lib/simulator.js:16:11)
    at getSimulator$ (../../lib/simulator.js:28:3)
    at tryCatch (/Users/monismajeed/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/monismajeed/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/monismajeed/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/monismajeed/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
[debug] [XCUITest] No WebDriverAgent derived data available, so unable to clear system files
[MJSONWP] Encountered internal error running command: Error: Xcode version 9.0 is not yet supported
    at handleUnsupportedXcode (../../lib/simulator.js:16:11)
    at getSimulator$ (../../lib/simulator.js:28:3)
    at tryCatch (/Users/monismajeed/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/monismajeed/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/monismajeed/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/monismajeed/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
[HTTP] <-- POST /wd/hub/session 500 616 ms - 175

**Comment by imurchie** [comment]
Yes. You need to update the beta.

**Comment by monism** [comment]
@imurchie what i need to update both Xcode and Appium are beta only

**Comment by imurchie** [comment]
Update Appium. Support for Xcode 9 is ongoing, and was not in place with your version of Appium.
```
npm uninstall -g appium && npm cache clean && npm install -g appium@beta
```

**Comment by monism** [comment]
I ran above command , but still it shows 1.6.6-beta.4 on running appium -v

**Comment by monism** [comment]
if i uninstall "npm unistall -g appium" and then do "appium -v" [it doesn't show anything], then if i install "npm install -g appium@beta" and then checks version it still shows appium@1.6.6-beta.4

**Comment by imurchie** [comment]
And what happens when you run your test?

**Comment by mlehinchenko** [comment]
had the same issue after full uninstall and install everything works. Thanks.

**Comment by monism** [comment]
@imurchie  @mlehinchenko 
Thanks , its working for me , but whatever xpath i was using with Appium@beta none of the xpaths are getting identified now, i am also using Xcuitest = automationame, but still doesn't help

**Comment by monism** [comment]
And if i have two accounts for machine , can i use grid to run them parallel using those accounts of same machine

**Comment by imurchie** [comment]
I've seen this happen too. @mykola-mokhnach any ideas about this wrong targetting when multiple sims are open?

**Comment by mykola-mokhnach** [comment]
probably wda port is not set properly in capabilities for each session

**Comment by monism** [comment]
@imurchie @mykola-mokhnach 
Ya that works thanks , I have small doubt , i amg oing to use grid for running IOS Appium cases , and if i have 2 machines as a node and i have set up two accounts on both machines, can i use as both accounts of both machines as nodes and setup in grid.

**Comment by mykola-mokhnach** [comment]
Please use Appium forum to ask questions.

**Comment by vikramvi** [comment]
@imurchie 

npm cache clean is throwing below error

```
npm cache clean
npm ERR! As of npm@5, the npm cache self-heals from corruption issues and data extracted from the cache is guaranteed to be valid. If you want to make sure everything is consistent, use 'npm cache verify' instead.
npm ERR! 
npm ERR! If you're sure you want to delete the entire cache, rerun this command with --force.
```

do you think  `npm uninstall -g appium && npm install -g appium@beta` is save enough to update to latest version of appium beta ?

**Comment by livastar** [comment]
--webdriveragent-port PORTNUMBER  should work

**Comment by havenqi** [comment]
I'm using latest Appium Desktop 1.2, which is bundled with Appium 1.6.5. Xcode is running at 9.0. I had the same error when launching inspector. What can I do? 
Appium really killed much time in configuration. Although there are many posts answering various questions, many of them were related to old versions. It has no help. Why the whole ecosystem is in such a mess. Appium official site just provides general information.

**Comment by monismajeed** [comment]
@havenqi  If you are facing issue with Appium Desktop , the you can do the below steps.

Copy node_modules  from  /lib/node_modules/appium/node_modules of appium@beta which have been installed via command to Resources/app/node_modules/appium/node_modules of Appium Dashboard

Appium Desktop will work after that

**Comment by havenqi** [comment]
@monismajeed Many thanks! That way worked. I'd have consulted you on the weekend.
Actually the latest Appium Desktop 1.2.1 doesn't provide the installation pack. It's a executable .app. So I opened the content and replaced the node_modules folder with that resides in my .npm-global folder. I installed appium 1.7 with npm already following another post thread. But I just didn't know how to point the GUI to use the latest appium package until seeing your advice.
Attach the screenshots for the others still in trouble,

To fix the incompatibility between Appium Desktop(e.g. 1.2.1 bundled with appium 1.6.5) and Xcode version(e.g. 9.0), try to install the latest version of Appium(beta, or 1.7), then the replace the Desktop node_modules with the newer one so that the Desktop can utilize the latest Appium,

The Appium Desktop 1.2.1 executable has node_modules at,
![image](https://user-images.githubusercontent.com/11476671/30795211-14fb9714-a1ff-11e7-8321-36e3da3fdc47.png)

The **npm install -g appium@1.7** has the same dir at,
`~/.npm-global/lib/node_modules/appium/node_modules`

**Comment by sibasismukherjee** [comment]
I was having the same issue and tried the fix as suggested by @imurchie and @monismajeed .Fixes were applied but the appium desktop stopped working.

Step 1:- Update to appium@beta
Step 2.- cp -r /usr/local/lib/node_modules/appium/node_modules/ /Applications/Appium\ 3.app/Contents/Resources/app/node_modules/appium/node_modules/
Step 3:- Started Appium Desktop app and getting the following error on start:-

/Applications/Appium\ 3.app/Contents/MacOS/Appium
TypeError: _lodash2.default.toPairs is not a function
    at Object.<anonymous> (../../lib/adb.js:74:28)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Applications/Appium 3.app/Contents/Resources/app/node_modules/appium/node_modules/appium-adb/build/index.js:11:15)
    at Module._compile (module.js:556:32)

**Comment by sibasismukherjee** [comment]
Hey Sorry for the trouble I actually fixed it:
If anyone else has this issue,please run the following steps:-

Step 1:- cd /Applications/Appium\ 3.app/Contents/Resources/app/node_modules/appium
Step 2:- npm uninstall lodash
Step 3:- npm install lodash

**Comment by shabana-parveen** [comment]
@sibasismukherjee , I am still getting below error after performing your suggested steps

TypeError: _lodash2.default.toPairs is not a function
    at Object.<anonymous> (../../lib/adb.js:74:28)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-adb/build/index.js:11:15)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (../../lib/android-helpers.js:10:49)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (../../../lib/commands/general.js:1:23)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (../../../lib/commands/index.js:1:30)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)

PS: I was updating appium version with 1.7.0, this version having few issues then I try to install its beta version of 1.7.0. again its showing me few errors. then I downgrade my appium version with 1.6.5. but getting above error 

npm version : 5.3.0
node version : v8.6.0

From last 2 days, I was stuck with this issue. I tried all npm uninstallation/ updation, appium downgrade/ update. Please check and provide me a solution.

**Comment by sibasismukherjee** [comment]
@shabana-parveen It looks like you are working on the appium cli. I had the issue with Appium Desktop..

Can you double check, after performing the steps mentioned by the above guys..

**Comment by shabana-parveen** [comment]
@sibasismukherjee , I run my suite my client only, still I was trying to update appium latest beta version, but couldn't LUCK. 

Just to bring you attention I am not having app folder inside Resources.

**Comment by shabana-parveen** [comment]
via desktop version getting below error:

Launching Appium with command: '/Applications/Appium.app/Contents/Resources/node/bin/node' appium/build/lib/main.js --debug-log-spacing --automation-name "Appium" --platform-name "Android" --platform-version "4.4" --native-instruments-lib

module.js:341
    throw err;
    ^

Error: Cannot find module '/Applications/Appium.app/Contents/Resources/node_modules/appium/build/lib/main.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3

**Comment by shabana-parveen** [comment]
I follow @havenqi footsteps, now I can run my appium desktop application with appium 1.7.0 beta version, but still facing issues with command line.
