### ISSUE TITLE
[Logcat] Logcat terminated with code 0, signal null

### ISSUE THREAD

**Issue by wangtao169447** [appium/appium#9075]
## The problem
when i run a testcase by appium, however PC lost connect with devices, and throw this kind of exception:
`[Logcat] Logcat terminated with code 0, signal null
[ADB] Getting device platform version
[debug] [ADB] Getting connected devices...
[debug] [ADB] 0 device(s) connected
[ADB] Error: Error getting device platform version. Original error: No device connected, cannot run adb shell command 'getprop ro.build.version.release'
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at ADB.callee$0$0$ (../../../lib/tools/adb-commands.js:48:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
 Error: Error getting device platform version. Original error: No device connected, cannot run adb shell command 'getprop ro.build.version.release'
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at ADB.callee$0$0$ (../../../lib/tools/adb-commands.js:48:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>`

i wonder whether appium have someways to control this kind of exception?

thanks

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.5
* Last Appium version that did not exhibit the issue (if applicable):None
* Desktop OS/version used to run Appium:Mac OS
* Node.js version (unless using Appium.app|exe):v8.1.3
* Mobile platform/version under test:android,4.4.4
* Real device or emulator/simulator:real devices
* Appium CLI or Appium.app|exe:CLI

**Comment by mykola-mokhnach** [comment]
This usually a signal that adb lost connection to the device. We cannot do anything about this on Appium side.
