### ISSUE TITLE
org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. 

### ISSUE THREAD

**Issue by cnkr** [appium/appium#9086]
## Don't use simulator !
I am using appium 1.6.5 for IOS. I dont build the code in simulator using xcode.

## Code

    public static void main (String[] args) throws MalformedURLException {

        DesiredCapabilities d = new DesiredCapabilities();
        d.setCapability(MobileCapabilityType.DEVICE_NAME,"iPhone 6");
        d.setCapability(MobileCapabilityType.PLATFORM_NAME,"iOS");
        d.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.IOS_XCUI_TEST);
        d.setCapability(MobileCapabilityType.APP,"//Users//*****//Desktop//UICatalog.app");
        IOSDriver<IOSElement> driver = new IOSDriver<>(new URL("http://127.0.0.1:4723/wd/hub"),d);
        driver.quit();
## Libs
Java-client-5.0.0BETA9
selenium-server-standalone-3.5.2

## IntelliJ Logs

Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{app=//Users//****//Desktop//UICatalog.app, automationName=XCuiTest, platformName=iOS, deviceName=iPhone 6}], required capabilities = Capabilities [{}]
Build info: version: '3.5.2', revision: '10229a9020', time: '2017-08-21T17:54:21.164Z'
System info: host: 'akir.local', ip: 'fe80:0:0:0:4d3:96ff:9c8d:85d0%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_144'
Driver info: driver.version: IOSDriver
	at io.appium.java_client.remote.AppiumProtocolHandShake.lambda$1(AppiumProtocolHandShake.java:96)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at io.appium.java_client.remote.AppiumProtocolHandShake.createSession(AppiumProtocolHandShake.java:96)
	at io.appium.java_client.remote.AppiumCommandExecutor.doExecute(AppiumCommandExecutor.java:111)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:162)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:641)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:254)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:236)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:137)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:88)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:112)
	at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:78)
	at Practise.main(Practise.java:19)
## Appium logs
```
[HTTP] <-- POST /wd/hub/session 500 172 ms - 336 
[HTTP] --> POST /wd/hub/session {"capabilities":[{"desiredCapabilities":{"app":"//Users//******//Desktop//UICatalog.app","automationName":"XCuiTest","platformName":"iOS","deviceName":"iPhone 6"}},{"requiredCapabilities":{}}]}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [null,null,[{"desiredCapabilities":{"app":"//Users//*******//Desktop//UICatalog.app","automationName":"XCuiTest","platformName":"iOS","deviceName":"iPhone 6"}},{"requiredCapabilities":{}}]]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1503661797748 (14:49:57 GMT+0300 (+03))
[MJSONWP] Encountered internal error running command: Error: You must include a platformName capability
    at AppiumDriver.getDriverForCaps (../../lib/appium.js:44:13)
    at AppiumDriver.createSession$ (../../lib/appium.js:157:28)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at Promise (<anonymous>)
    at F (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at AppiumDriver.createSession (../../lib/appium.js:183:31)
    at ../../../lib/basedriver/driver.js:207:24
    at tryCatcher (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromiseAtPostResolution (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/promise.js:248:10)
    at Async._drainQueue (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
[HTTP] <-- POST /wd/hub/session 500 3 ms - 179 
```

**Comment by imurchie** [comment]
Your client setup requires the latest Appium beta.

**Comment by cnkr** [comment]
@imurchie the latest version is not it v1.6.5 ?

**Comment by mykola-mokhnach** [comment]
it's the latest STABLE version. The recent beta is 1.6.6-beta

**Comment by cnkr** [comment]
@mykola-mokhnach I did the update, but the problem was not solved and appium client wrote the following logs.
##logs

[simctl] Error: simctl error running 'create': Invalid runtime: 10.3

[simctl] Error: Could not create simulator with name 'appiumTest-57ef329a-d9e0-4e4b-806f-9e9ac0001fb3', device type id 'iPhone 6' and runtime id '10.3'. Reason: 'simctl error running 'create': Invalid runtime: 10.3'

[XCUITest] Error: Could not create simulator with name 'appiumTest-57ef329a-d9e0-4e4b-806f-9e9ac0001fb3', device type id 'iPhone 6' and runtime id '10.3'. Reason: 'simctl error running 'create': Invalid runtime: 10.3'

**Comment by mykola-mokhnach** [comment]
Please provide full log

**Comment by jlipps** [comment]
@cnkr do you have the 10.3 ios sdk installed?

**Comment by cnkr** [comment]
Yes @jlipps xcode has a ios 10.3 simulator.

**Comment by cnkr** [comment]
After setting the platform version, the problem solved.
