### ISSUE TITLE
I get this error when runninng: java.lang.NullPointerException error. 

### ISSUE THREAD

**Issue by vladbelo** [appium/appium#9131]
## The problem

I'm trying to run appium with eclipse and testng but it just says server is running.
but I get java.lang.NullPointerException error when running. 

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
[Appium] Welcome to Appium v1.6.5
[Appium] Non-default server args:
[Appium]   address: 127.0.0.1
[Appium] Appium REST http interface listener started on 127.0.0.1:4723
-Stops does not go further. 

## Code To Reproduce Issue [ Good To Have ]
public class screen_detects_ extends Base{
	private AppiumDriver driver;
	
	
	    @Test
        public void AP_Renewals() {

            try {
              
 	         Tutorial_iOSPage tutorial = new Tutorial_iOSPage(driver);
 	         tutorial.skipTutorial(driver);
 	           
 	         Dashboard_iOSPage board1 = new Dashboard_iOSPage(driver);
 	       board1.clickOnDashBoardButton(driver);
 	         
	   
 	        board1.tapOnSignInAP("jkjk@gmail.com", "tatata");
 	           
 	       board1.clickOnMyTickets();
 	          
 	           Log.log(driver).info("Step 4 Verify no Renewal triggered messages display");
 	           
 	           vicketsAndasses backbutton = new vicketsAndasses(driver);
 	           backbutton.clickBackButton();
            	         } catch (Exception exp) {
              exp.printStackTrace();
            }

            
        }
       
}
base.java
public class base {
  public static final Logger LOGGER = Log.getDefaultLogger();
  protected AppiumDriver     driver;
  protected String           platform;
  protected String environment;
  protected JSONObject jsonConfig;
  
  
  

 // @BeforeMethod(alwaysRun = true)
 // @Parameters({ "appName", "platform", "platformVersion", "deviceName","seleniumUrl", "environment", "enableEnv", "ticketFutureDate" })
 
  public void setUp(@Optional String appName, @Optional String platform,
      @Optional String platformVersion, @Optional String deviceName,
      @Optional String seleniumUrl, @Optional String environment, @Optional String enableEnv, @Optional String ticketFutureDate, ITestContext ctx, Method method)
      throws Exception {
   
      if( appName == null || appName.isEmpty() ||  environment == null || enableEnv == null )
      {
        JSONObject jsonCapabilities = DataProviderHelper.readCapabilities();
        appName         = jsonCapabilities.getString("appName");
        platform        = jsonCapabilities.getString("platform");
        platformVersion = jsonCapabilities.getString("platformVersion");
        deviceName      = jsonCapabilities.getString("deviceName");
        seleniumUrl     = jsonCapabilities.getString("seleniumUrl");
        environment     = jsonCapabilities.isNull("environment") ? null : jsonCapabilities.getString("environment");
        enableEnv     = jsonCapabilities.getString( "enableEnv" );
        ticketFutureDate = jsonCapabilities.getString( "ticketFutureDate" );
      }
      
      this.platform = platform;
      this.environment = environment;

      System.out.println("********************************************");
      System.out.println("appName= "+appName);
      System.out.println("platform= "+platform);
      System.out.println("platformVersion= "+platformVersion);
      System.out.println("deviceName= "+deviceName);
      System.out.println("seleniumUrl= "+seleniumUrl);
      System.out.println("environment= "+environment);
      System.out.println("enableEnv= "+enableEnv);
      System.out.println("ticketFutureDate= "+ticketFutureDate);
      System.out.println("********************************************");
      
      this.driver = BaseTest.setupDriver(appName, platform, platformVersion, deviceName, seleniumUrl, environment, enableEnv, ticketFutureDate,  ctx, method);

      
      //Parse FP object from json
//      TestDataHelper.loadTestData(TestDataHelper.ANDROID_JSON_FILE);
      
  }
  
 // @AfterMethod(alwaysRun = true)
  public void tearDown() {
    BaseTest.quitDriver(driver);
  }
  

  
  public <T1 extends Object> JSONObject getGeneralJson() throws JSONException{
    String fileName = TestDataHelper.ANDROID_JSON_FILE;
    //fileName = fileName.split("\\.")[fileName.split("\\.").length - 1];
    String jsonpath = TestDataHelper.ANDROID_JSON_FILE_LOCATION;
    jsonpath = System.getProperty("user.dir") + Constants.DIR_SEPARATOR + jsonpath;
    jsonpath = jsonpath + fileName;
    
    String jsonString = null;
    try {
      jsonString = DataProviderHelper.readFileAsString(jsonpath);
    } catch (IOException e) {
      // TODO Auto-generated catch block
      e.printStackTrace();
    }
    return new JSONObject(jsonString);

  }
}
error: 

objc[2545]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/bin/java (0x10865e4c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x1087264e0). One of the two will be used. Which one is undefined.
08-30 15:48:02.385 [com.disney.appium.scripts.iOS.aprenewals.T1632401_Verify_ap_screen_detects_ap_renewal_eligibility AP_Renewals] Skip Tutorial
 ''''''**'java.lang.NullPointerException  ''**'''''
	at io.appium.java_client.pagefactory.AppiumElementLocator.<init>(AppiumElementLocator.java:72)
	at io.appium.java_client.pagefactory.AppiumElementLocatorFactory.createLocator(AppiumElementLocatorFactory.java:26)
	at io.appium.java_client.pagefactory.AppiumFieldDecorator.decorate(AppiumFieldDecorator.java:65)
	at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:115)
	at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:107)
	at com.disney.apps.dlr.pageObjects.iOS.Tutorial.Tutorial_iOSPage.<init>(Tutorial_iOSPage.java:50)
	at com.disney.appium.scripts.iOS.aprenewals.T1632401_Verify_ap_screen_detects_ap_renewal_eligibility.AP_Renewals(T1632401_Verify_ap_screen_detects_ap_renewal_eligibility.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
PASSED: AP_Renewals

===============================================
    Default test
    Tests run: 1, Failures: 0, Skips: 0
===============================================

===============================================
Default suite
Total tests run: 1, Failures: 0, Skips: 0
===============================================

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/appium/java-client/issues
I assume the problem happens because Selenium API is updated and the java client is still at old version.

closed as non server realated
