### ISSUE TITLE
Error: Error while getting connected devices. Original error: Command '/Users/sh-liujinjia/resource/sdk_niu/platform-tools/adb devices' exited with code 1

### ISSUE THREAD

**Issue by TesterlifeRaymond** [appium/appium#9190]
hi bro ,  my cases is all run and report is created, but appium session delete error , i don't used driver.close() and driver.quit()

[HTTP] --> POST /wd/hub/session/884f8433-aa6d-4366-b2de-183495d6efd2/appium/device/app_installed {"sessionId":"884f8433-aa6d-4366-b2de-183495d6efd2","bundleId":"com.snda.wifilocating"}
[debug] [MJSONWP] Calling AppiumDriver.isAppInstalled() with args: ["com.snda.wifilocating","884f8433-aa6d-4366-b2de-183495d6efd2"]
[debug] [ADB] Getting install status for com.snda.wifilocating
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/sh-liujinjia/resource/sdk_niu/platform-tools/adb' with args: ["-P",5037,"-s","T8DDU15B26002810","shell","pm","list","packages","com.snda.wifilocating"]
[debug] [ADB] App is installed
[debug] [MJSONWP] Responding to client with driver.isAppInstalled() result: true
[HTTP] <-- POST /wd/hub/session/884f8433-aa6d-4366-b2de-183495d6efd2/appium/device/app_installed 200 701 ms - 76
[HTTP] --> POST /wd/hub/session/884f8433-aa6d-4366-b2de-183495d6efd2/appium/device/app_installed {"sessionId":"884f8433-aa6d-4366-b2de-183495d6efd2","bundleId":"com.snda.wifilocating"}
[debug] [MJSONWP] Calling AppiumDriver.isAppInstalled() with args: ["com.snda.wifilocating","884f8433-aa6d-4366-b2de-183495d6efd2"]
[debug] [ADB] Getting install status for com.snda.wifilocating
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/sh-liujinjia/resource/sdk_niu/platform-tools/adb' with args: ["-P",5037,"-s","T8DDU15B26002810","shell","pm","list","packages","com.snda.wifilocating"]
[debug] [ADB] App is installed
[debug] [MJSONWP] Responding to client with driver.isAppInstalled() result: true
[HTTP] <-- POST /wd/hub/session/884f8433-aa6d-4366-b2de-183495d6efd2/appium/device/app_installed 200 710 ms - 76
[HTTP] --> POST /wd/hub/session/884f8433-aa6d-4366-b2de-183495d6efd2/appium/app/launch {"sessionId":"884f8433-aa6d-4366-b2de-183495d6efd2"}
[debug] [MJSONWP] Calling AppiumDriver.launchApp() with args: ["884f8433-aa6d-4366-b2de-183495d6efd2"]
[AndroidDriver] Remote apk path is /data/local/tmp/087978c2cee7ce11b2f580bed267c9bd.apk
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/sh-liujinjia/resource/sdk_niu/platform-tools/adb' with args: ["-P",5037,"-s","T8DDU15B26002810","shell","ls","/data/local/tmp/087978c2cee7ce11b2f580bed267c9bd.apk"]
[debug] [AndroidDriver] Checking if app is installed
[debug] [ADB] Getting install status for com.snda.wifilocating
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/sh-liujinjia/resource/sdk_niu/platform-tools/adb' with args: ["-P",5037,"-s","T8DDU15B26002810","shell","pm","list","packages","com.snda.wifilocating"]
[debug] [ADB] App is installed
[AndroidDriver] Apk is already on remote and installed, resetting
[debug] [AndroidDriver] Running fast reset (stop and clear)
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/sh-liujinjia/resource/sdk_niu/platform-tools/adb' with args: ["-P",5037,"-s","T8DDU15B26002810","shell","am","force-stop","com.snda.wifilocating"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/sh-liujinjia/resource/sdk_niu/platform-tools/adb' with args: ["-P",5037,"-s","T8DDU15B26002810","shell","pm","clear","com.snda.wifilocating"]
[debug] [AndroidDriver] Extracting strings from apk /Users/sh-liujinjia/Desktop/AppiumDemo/apk/wifi.apk null /var/folders/kp/lb3xwdq90sd6yfjymq2vh6jm0000gn/T/com.snda.wifilocating
[debug] [ADB] Extracting strings for language: default
[debug] [ADB] Device API level: 19
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/sh-liujinjia/resource/sdk_niu/platform-tools/adb' with args: ["-P",5037,"-s","T8DDU15B26002810","shell","getprop","persist.sys.language"]
[debug] [ADB] Current device property 'persist.sys.language':
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/sh-liujinjia/resource/sdk_niu/platform-tools/adb' with args: ["-P",5037,"-s","T8DDU15B26002810","shell","getprop","ro.product.locale.language"]
[debug] [ADB] Current device property 'ro.product.locale.language': zh
[debug] [ADB] Reading strings from converted strings.json
[debug] [ADB] Running '/Users/sh-liujinjia/resource/sdk_niu/platform-tools/adb' with args: ["-P",5037,"-s","T8DDU15B26002810","push","/var/folders/kp/lb3xwdq90sd6yfjymq2vh6jm0000gn/T/com.snda.wifilocating/strings.json","/data/local/tmp"]
[debug] [ADB] Device API level: 19
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/sh-liujinjia/resource/sdk_niu/platform-tools/adb' with args: ["-P",5037,"-s","T8DDU15B26002810","shell","am","start","-W","-n","com.snda.wifilocating/com.lantern.launcher.ui.MainActivity","-S","-a","android.intent.action.MAIN","-c","android.intent.category.LAUNCHER","-f","0x10200000"]
[debug] [MJSONWP] Responding to client with driver.launchApp() result: null
[HTTP] <-- POST /wd/hub/session/884f8433-aa6d-4366-b2de-183495d6efd2/appium/app/launch 200 5729 ms - 76
[Logcat] Logcat terminated with code 0, signal null
[UiAutomator] UiAutomator exited unexpectedly with code 0, signal null
[debug] [UiAutomator] Moving to state 'stopped'
[debug] [AndroidDriver] Shutting down Android driver
[Appium] Closing session, cause was 'UiAUtomator shut down unexpectedly'
[Appium] Removing session 884f8433-aa6d-4366-b2de-183495d6efd2 from our master session list
[debug] [ADB] Getting connected devices...
[ADB] Error: Error while getting connected devices. Original error: Command '/Users/sh-liujinjia/resource/sdk_niu/platform-tools/adb devices' exited with code 1
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at ADB.callee$0$0$ (../../../lib/tools/system-calls.js:123:9)
    at tryCatch (/Users/sh-liujinjia/.nvm/versions/node/v6.3.1/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/sh-liujinjia/.nvm/versions/node/v6.3.1/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/sh-liujinjia/.nvm/versions/node/v6.3.1/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/sh-liujinjia/.nvm/versions/node/v6.3.1/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: Error while getting connected devices. Original error: Command '/Users/sh-liujinjia/resource/sdk_niu/platform-tools/adb devices' exited with code 1
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at ADB.callee$0$0$ (../../../lib/tools/system-calls.js:123:9)
    at tryCatch (/Users/sh-liujinjia/.nvm/versions/node/v6.3.1/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/sh-liujinjia/.nvm/versions/node/v6.3.1/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/sh-liujinjia/.nvm/versions/node/v6.3.1/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/sh-liujinjia/.nvm/versions/node/v6.3.1/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
Unhandled rejection Error: Error while getting connected devices. Original error: Command '/Users/sh-liujinjia/resource/sdk_niu/platform-tools/adb devices' exited with code 1
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at ADB.callee$0$0$ (../../../lib/tools/system-calls.js:123:9)
    at tryCatch (/Users/sh-liujinjia/.nvm/versions/node/v6.3.1/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/sh-liujinjia/.nvm/versions/node/v6.3.1/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/sh-liujinjia/.nvm/versions/node/v6.3.1/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/sh-liujinjia/.nvm/versions/node/v6.3.1/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by TesterlifeRaymond** [comment]
e..... After restarting Mac, this problem does not appear, thx

**Comment by maliang04** [comment]
I restarted my mac, it still has this error
