### ISSUE TITLE
Failed to create WDA session

### ISSUE THREAD

**Issue by navinjethani** [appium/appium#9202]
Failed to create WDA session

Setup:
appium<--->real IOS device
Command:
```
appium -U <Id> --app com.example.apple-samplecode.UICatalog
```

```java
       DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("deviceName", "iPhone 6");
        capabilities.setCapability("platformName", "iOS");
        capabilities.setCapability("platformVersion", "10.3");
        capabilities.setCapability("browserName", "safari");
        WebDriver driver = new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
```

starting ios_webkit_debug_proxy from another terminal

Start test: mvn test

Any help appreciated, Thx in advance

====================================================
```
06:45:21.030 xcodebuild[66020:605308] Beginning test session WebDriverAgentRunner-26CBE273-2DA8-473C-8A26-521F9CC211F7 at 2017-09-13 06:45:21.030 with Xcode 8E3004b on target <DVTiOSDevice: 0x7feb5e8754f0> {
		deviceSerialNumber:         F17R50EEGRXQ
		identifier:                 2b9bd104bfc3fd5302d2fa38cff2113cc3483dfc
		deviceClass:                iPhone
		deviceName:                 Navin iPhone
		deviceIdentifier:           2b9bd104bfc3fd5302d2fa38cff2113cc3483dfc
		productVersion:             10.3.3
		buildVersion:               14G60
		deviceSoftwareVersion:      10.3.3 (14G60)
		deviceArchitecture:         arm64
		deviceTotalCapacity:        12299034624
		deviceAvailableCapacity:    329383936
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		isPasscodeLocked:           NO
		deviceType:                 <DVTDeviceType:0x7feb5e499670 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		activityProgress:          -2
		activityTitle:             
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	bootArgs:                  <unavailable>
		} (10.3.3 (14G60))
06:45:21.031 xcodebuild[66020:605308] 	/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild
build-for-testing
test-without-building
-project
/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj
-scheme
WebDriverAgentRunner
-destination
id=2b9bd104bfc3fd5302d2fa38cff2113cc3483dfc
-configuration
Debug
IPHONEOS_DEPLOYMENT_TARGET=10.3
06:45:21.031 xcodebuild[66020:605308] Launching with Xcode.IDEFoundation.Launcher.PosixSpawn
06:45:21.038 xcodebuild[66020:605308] Launch session started.
06:45:21.088 xcodebuild[66020:605344] Connecting to mobile device: 2b9bd104bfc3fd5302d2fa38cff2113cc3483dfc
06:45:21.094 xcodebuild[66020:605344] Starting session with mobile device
06:45:21.169 xcodebuild[66020:605344] Starting test manager service on mobile device.
06:45:21.195 xcodebuild[66020:605385] Received connection for test runner session
06:45:21.195 xcodebuild[66020:605385] Listening for proxy connection request from the test bundle
06:45:21.196 xcodebuild[66020:605308] Test runner session acquired connection.
06:45:21.196 xcodebuild[66020:605308] Waiting for test process to launch.
06:45:21.196 xcodebuild[66020:605385] Initiating session with identifier: 26CBE273-2DA8-473C-8A26-521F9CC211F7
06:45:21.203 xcodebuild[66020:605384] Got reply to session initiation request with identifier 26CBE273-2DA8-473C-8A26-521F9CC211F7 (result:error): 22: (null)
06:45:21.406 xcodebuild[66020:605386] Installing com.apple.test.WebDriverAgentRunner-Runner using MobileInstall
06:45:21.520 xcodebuild[66020:605310] app uninstall set - {(
)}
06:45:21.520 xcodebuild[66020:605310] app install set - {(
    <DVTFilePath:0x7feb5e6e9ae0:'/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/DerivedData/WebDriverAgent/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app'>
)}
06:45:22.317 xcodebuild[66020:605386] remoteExecutable setInstalledPath:/private/var/containers/Bundle/Application/17B91315-4A29-40FF-9582-C67D9B1F2F2C/WebDriverAgentRunner-Runner.app

06:45:22.318 xcodebuild[66020:605386] Configuring for testing on device...
06:45:22.318 xcodebuild[66020:605386] Updating test configuration with device paths.
06:45:22.319 xcodebuild[66020:605386] Updated test configuration at /var/folders/3y/9prf9_y94wb6qcnwdmrqkmz8gs6v1s/T/com.apple.dt.XCTest/26CBE273-2DA8-473C-8A26-521F9CC211F7/remote-container/tmp/WebDriverAgentRunner-26CBE273-2DA8-473C-8A26-521F9CC211F7.xctestconfiguration with device paths: <XCTestConfiguration: 0x7feb5e97ab80>
	                  testBundleURL:file:///private/var/containers/Bundle/Application/17B91315-4A29-40FF-9582-C67D9B1F2F2C/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest
	         testBundleRelativePath:(null)
	              productModuleName:WebDriverAgentRunner
	                    testsToSkip:(null)
	                     testsToRun:(null)
	             reportResultsToIDE:YES
	              sessionIdentifier:26CBE273-2DA8-473C-8A26-521F9CC211F7
	     pathToXcodeReportingSocket:(null)
	      disablePerformanceMetrics:no
	treatMissingBaselinesAsFailures:no
	                baselineFileURL:(null)
	       baselineFileRelativePath:(null)
	          targetApplicationPath:(null)
	      targetApplicationBundleID:(null)
	     targetApplicationArguments:(null)
	   targetApplicationEnvironment:
(null)
	               reportActivities:YES
	       testsMustRunOnMainThread:YES
	         initializeForUITesting:YES
	 aggregateStatisticsBeforeCrash:{
    XCSuiteRecordsKey =     {
    };
}
	        automationFrameworkPath:/Developer/Library/PrivateFrameworks/XCTAutomationSupport.framework
	                     emitOSLogs:no

06:45:22.319 xcodebuild[66020:605386] Uploading test configuration to app container.
06:45:24.375 xcodebuild[66020:605386] Updating test process environment variables.
06:45:24.375 xcodebuild[66020:605386] Updated testing environment variables {
    "DYLD_FRAMEWORK_PATH" = "/private/var/containers/Bundle/Application/17B91315-4A29-40FF-9582-C67D9B1F2F2C/WebDriverAgentRunner-Runner.app/Frameworks:/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/DerivedData/WebDriverAgent/Build/Products/Debug-iphoneos:__PLATFORMS__/iPhoneOS.platform/Developer/Library/Frameworks:/Developer/Library/PrivateFrameworks";
    "DYLD_LIBRARY_PATH" = "/private/var/containers/Bundle/Application/17B91315-4A29-40FF-9582-C67D9B1F2F2C/WebDriverAgentRunner-Runner.app/Frameworks:/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/DerivedData/WebDriverAgent/Build/Products/Debug-iphoneos:__PLATFORMS__/iPhoneOS.platform/Developer/Library/Frameworks:/Developer/Library/PrivateFrameworks";
    "XCODE_DBG_XPC_EXCLUSIONS" = "com.apple.dt.xctestSymbolicator";
    XCTestConfigurationFilePath = "/private/var/mobile/Containers/Data/Application/E1013861-12E3-4769-B25D-459B0A19D484/tmp/WebDriverAgentRunner-26CBE273-2DA8-473C-8A26-521F9CC211F7.xctestconfiguration";
}
06:45:25.435 xcodebuild[66020:605308] Adding console adaptor <IDEConsoleAdaptor: 0x7feb5efef610 'target'> for test session 26CBE273-2DA8-473C-8A26-521F9CC211F7.
06:45:25.592 xcodebuild[66020:605308] Test process runnable PID is 2666.
06:45:25.776 xcodebuild[66020:605320] Handling proxy channel request from test runner
06:45:25.777 xcodebuild[66020:605320] Test runner is ready, running protocol 22, requires at least version 8. Control framework is running 22 and requires at least 8
06:45:25.777 xcodebuild[66020:605308] Test runner session successfully initiated.
06:45:25.777 xcodebuild[66020:605308] Creating the daemon control session.
06:45:25.777 xcodebuild[66020:605308] Whitelisting test process ID 2666
06:45:25.777 xcodebuild[66020:605308] Got authorization request for pid 2666
06:45:26.093 xcodebuild[66020:605387] Requesting authorization for pid 2666
06:45:18.196 testmanagerd[2663:757226] Launched testmanagerd from /Developer/usr/libexec/testmanagerd, modified on Friday, February 17, 2017 at 6:37:54 PM Pacific Standard Time
06:45:18.198 testmanagerd[2663:757228] Received new test session connection from process with PID 2656
06:45:18.197 testmanagerd[2663:757226] Setting availability state.
06:45:26.098 xcodebuild[66020:605384] Got reply to authorization request for pid 2666 (result:error): 22: (null)
06:45:26.099 xcodebuild[66020:605308] Got whitelisting response from test daemon. Success: 1
06:45:18.201 testmanagerd[2663:757226] Posting availability to test bundles...
06:45:18.203 testmanagerd[2663:757226] Initial orientation 1
06:45:18.204 testmanagerd[2663:757227] -[XCTDaemon allowUITestControlForPID:] 0 vs 2656
06:45:18.206 testmanagerd[2663:757233] app info {
    BKSApplicationStateAppIsFrontmost = 0;
    BKSApplicationStateExtensionKey = 0;
    SBApplicationStateDisplayIDKey = "com.apple.test.WebDriverAgentRunner-Runner";
    SBApplicationStateKey = 4;
    SBApplicationStateProcessIDKey = 2656;
    SBApplicationStateRunningReasonsKey =     (
                {
            SBApplicationStateRunningReasonAssertionIdentifierKey = "Called by UIKit, from <redacted>";
            SBApplicationStateRunningReasonAssertionReasonKey = 4;
        }
    );
    SBMostElevatedStateForProcessID = 4;
}
06:45:18.206 testmanagerd[2663:757233] Got request for process assertion for pid 2656.
06:45:18.207 testmanagerd[2663:757233] Created process assertion for pid 2656: <BKSProcessAssertion: 0x10041ff10>, waiting for response from assertiond.
06:45:18.207 testmanagerd[2663:757233] Starting to monitor com.apple.test.WebDriverAgentRunner-Runner
06:45:18.209 testmanagerd[2663:757233] Got reply for process assertion request, success: YES
06:45:18.209 testmanagerd[2663:757229] Got application state update: com.apple.test.WebDriverAgentRunner-Runner (2656) -> 4
06:45:19.162 testmanagerd[2663:757229] IDE connected via lockdown over socket 4 (-[XCTestManagerIDEServer listenForControlConnectionsOverLockdown]_block_invoke)
06:45:19.163 testmanagerd[2663:757229] Created session with socket 4
06:45:19.177 testmanagerd[2663:757229] Handled a proxy request from the IDE with session <XCIDESession: 0x100420200> created Wednesday, September 13, 2017 at 6:45:19 AM Pacific Daylight Time proxy <_DTXProxy: 0x100325a10>
06:45:19.178 testmanagerd[2663:757226] -[XCIDESession _IDE_initiateSessionWithIdentifier:forClient:atPath:protocolVersion:]_block_invoke 26CBE273-2DA8-473C-8A26-521F9CC211F7 1 4 from client 3E2013F2-6BCA-4F19-BFAD-4653A5DBD9C9-66020-00002F23547932F8 (/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild)
06:45:19.179 testmanagerd[2663:757233] -[XCTDaemon setIDESession:forIdentifier:]_block_invoke <XCIDESession: 0x100420200> created Wednesday, September 13, 2017 at 6:45:19 AM Pacific Daylight Time for client 3E2013F2-6BCA-4F19-BFAD-4653A5DBD9C9-66020-00002F23547932F8 waiting to pair with test session 26CBE273-2DA8-473C-8A26-521F9CC211F7 -> 26CBE273-2DA8-473C-8A26-521F9CC211F7
06:45:19.180 testmanagerd[2663:757233] -[XCTDaemon _queue_handleRequestForSessionWithIdentifier:]
06:45:19.717 testmanagerd[2663:757229] Test process connection invalidated or interrupted, closing test session <XCTestSession: 0x100418e00>.
06:45:19.718 testmanagerd[2663:757229] Closed <XCTestSession: 0x100418e00>, removing from (
    "<XCTestSession: 0x100418e00>"
)
06:45:19.718 testmanagerd[2663:757229] Tearing down test session <XCTestSession: 0x100418e00>.
06:45:19.719 testmanagerd[2663:757229] Considering exiting:
06:45:19.719 testmanagerd[2663:757229] Session summary: 0 test sessions, 1 sessions with identifiers, 0 unidentified sessions, does not have control session
06:45:19.719 testmanagerd[2663:757229] Unpaired test sessions: {
    "26CBE273-2DA8-473C-8A26-521F9CC211F7" = "<XCIDESession: 0x100420200> created Wednesday, September 13, 2017 at 6:45:19 AM Pacific Daylight Time for client 3E2013F2-6BCA-4F19-BFAD-4653A5DBD9C9-66020-00002F23547932F8 waiting to pair with test session 26CBE273-2DA8-473C-8A26-521F9CC211F7";
}
06:45:23.204 testmanagerd[2663:757233] Considering exiting:
06:45:23.204 testmanagerd[2663:757233] Session summary: 0 test sessions, 1 sessions with identifiers, 0 unidentified sessions, does not have control session
06:45:23.204 testmanagerd[2663:757233] Unpaired test sessions: {
    "26CBE273-2DA8-473C-8A26-521F9CC211F7" = "<XCIDESession: 0x100420200> created Wednesday, September 13, 2017 at 6:45:19 AM Pacific Daylight Time for client 3E2013F2-6BCA-4F19-BFAD-4653A5DBD9C9-66020-00002F23547932F8 waiting to pair with test session 26CBE273-2DA8-473C-8A26-521F9CC211F7";
}
06:45:23.642 testmanagerd[2663:757233] Received new test session connection from process with PID 2666
06:45:23.644 testmanagerd[2663:757226] Initial orientation 1
06:45:23.646 testmanagerd[2663:757233] Test session 26CBE273-2DA8-473C-8A26-521F9CC211F7 requested socket (-[XCTestSession _XCT_requestSocketForSessionIdentifier:reply:])
06:45:23.646 testmanagerd[2663:757229] Test session 26CBE273-2DA8-473C-8A26-521F9CC211F7 requested socket (-[XCTDaemon requestSocketForSessionIdentifier:reply:]_block_invoke)
06:45:23.646 testmanagerd[2663:757229] -[XCTDaemon _queue_handleRequestForSessionWithIdentifier:]
06:45:23.646 testmanagerd[2663:757229] Closing IDE connection before sending socket 5 to test host.
06:45:23.646 testmanagerd[2663:757229] -[XCIDESession closeIDEConnection:] sending barrier
06:45:23.646 testmanagerd[2663:757227] app info {
    BKSApplicationStateAppIsFrontmost = 1;
    BKSApplicationStateExtensionKey = 0;
    SBApplicationStateDisplayIDKey = "com.apple.test.WebDriverAgentRunner-Runner";
    SBApplicationStateKey = 8;
    SBApplicationStateProcessIDKey = 2666;
    SBMostElevatedStateForProcessID = 8;
}
06:45:23.646 testmanagerd[2663:757226] barrier flushed, closing DTXConnection to IDE, socket will not be closed
06:45:23.646 testmanagerd[2663:757227] Got request for process assertion for pid 2666.
06:45:23.647 testmanagerd[2663:757249] DTXSocketTransport disconnected, owner is <XCIDESession: 0x100420200> created Wednesday, September 13, 2017 at 6:45:19 AM Pacific Daylight Time for client 3E2013F2-6BCA-4F19-BFAD-4653A5DBD9C9-66020-00002F23547932F8 waiting to pair with test session 26CBE273-2DA8-473C-8A26-521F9CC211F7
06:45:23.647 testmanagerd[2663:757227] Created process assertion for pid 2666: <BKSProcessAssertion: 0x100423d10>, waiting for response from assertiond.
06:45:23.648 testmanagerd[2663:757228] Got reply for process assertion request, success: YES
06:45:23.648 testmanagerd[2663:757540] -[XCTDaemon closeIDESession:]_block_invoke <XCIDESession: 0x100420200> created Wednesday, September 13, 2017 at 6:45:19 AM Pacific Daylight Time for client 3E2013F2-6BCA-4F19-BFAD-4653A5DBD9C9-66020-00002F23547932F8 waiting to pair with test session 26CBE273-2DA8-473C-8A26-521F9CC211F7
06:45:23.648 testmanagerd[2663:757540] Considering exiting:
06:45:23.648 testmanagerd[2663:757249] Disconnecting lockdown socket
06:45:23.649 testmanagerd[2663:757540] Session summary: 1 test sessions, 0 sessions with identifiers, 0 unidentified sessions, does not have control session
06:45:23.649 testmanagerd[2663:757227] Starting to monitor com.apple.test.WebDriverAgentRunner-Runner
06:45:23.649 testmanagerd[2663:757540] Got application state update: com.apple.test.WebDriverAgentRunner-Runner (2666) -> 8
06:45:23.751 testmanagerd[2663:757226] Sending socket 5 to test host
06:45:23.752 testmanagerd[2663:757228] -[XCTDaemon closeIDESession:]_block_invoke <XCIDESession: 0x100420200> created Wednesday, September 13, 2017 at 6:45:19 AM Pacific Daylight Time for client 3E2013F2-6BCA-4F19-BFAD-4653A5DBD9C9-66020-00002F23547932F8 waiting to pair with test session 26CBE273-2DA8-473C-8A26-521F9CC211F7
06:45:23.752 testmanagerd[2663:757228] Considering exiting:
06:45:23.752 testmanagerd[2663:757228] Session summary: 1 test sessions, 0 sessions with identifiers, 0 unidentified sessions, does not have control session
06:45:24.089 testmanagerd[2663:757226] Received request to collect crash reports in directories '/var/mobile/Library/Logs/CrashReporter/' for processes with names 'XCTRunner', 'WebDriverAgentRunner-Runner', 'xctest'
06:45:24.068 testmanagerd[2663:757249] IDE connected via lockdown over socket 4 (-[XCTestManagerIDEServer listenForControlConnectionsOverLockdown]_block_invoke)
06:45:24.068 testmanagerd[2663:757249] Created session with socket 4
06:45:24.073 testmanagerd[2663:757540] Handled a proxy request from the IDE with session <XCIDESession: 0x100323010> created Wednesday, September 13, 2017 at 6:45:24 AM Pacific Daylight Time proxy <_DTXProxy: 0x100327150>
06:45:24.074 testmanagerd[2663:757540] -[XCIDESession _IDE_initiateControlSessionForTestProcessID:protocolVersion:] 2666 22
06:45:24.074 testmanagerd[2663:757226] Set control session <XCIDESession: 0x100323010> created Wednesday, September 13, 2017 at 6:45:24 AM Pacific Daylight Time with proto 22 and proxy <_DTXProxy: 0x100327150>
06:45:24.091 testmanagerd[2663:757226] Initializing crash report observer for /var/mobile/Library/Logs/CrashReporter/
06:45:24.093 testmanagerd[2663:757226] Getting files in /var/mobile/Library/Logs/CrashReporter/
06:45:24.117 testmanagerd[2663:757226] Found 453 files in /var/mobile/Library/Logs/CrashReporter/
06:45:24.118 testmanagerd[2663:757226] Started monitoring /var/mobile/Library/Logs/CrashReporter/
06:45:23.637 XCTRunner[2666:757505] Linked XCTest.framework from /var/containers/Bundle/Application/17B91315-4A29-40FF-9582-C67D9B1F2F2C/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest, built with Xcode 0833(8E3002), modified on Wednesday, September 13, 2017 at 6:16:02 AM Pacific Daylight Time
06:45:23.637 XCTRunner[2666:757505] XCTest.framework bundle version: 12124
06:45:23.640 XCTRunner[2666:757505] System uptime: 1d 3:50:36
06:45:23.640 XCTRunner[2666:757505] Process arguments: (
    "/var/containers/Bundle/Application/17B91315-4A29-40FF-9582-C67D9B1F2F2C/WebDriverAgentRunner-Runner.app/XCTRunner",
    "-NSTreatUnknownArgumentsAsOpen",
    NO,
    "-ApplePersistenceIgnoreState",
    YES
)
06:45:23.640 XCTRunner[2666:757505] Process environment: {
    "CFFIXED_USER_HOME" = "/private/var/mobile/Containers/Data/Application/E1013861-12E3-4769-B25D-459B0A19D484";
    CLASSIC = 1;
    "DYLD_FRAMEWORK_PATH" = "/private/var/containers/Bundle/Application/17B91315-4A29-40FF-9582-C67D9B1F2F2C/WebDriverAgentRunner-Runner.app/Frameworks:/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/DerivedData/WebDriverAgent/Build/Products/Debug-iphoneos:__PLATFORMS__/iPhoneOS.platform/Developer/Library/Frameworks:/Developer/Library/PrivateFrameworks";
    "DYLD_LIBRARY_PATH" = "/private/var/containers/Bundle/Application/17B91315-4A29-40FF-9582-C67D9B1F2F2C/WebDriverAgentRunner-Runner.app/Frameworks:/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/DerivedData/WebDriverAgent/Build/Products/Debug-iphoneos:__PLATFORMS__/iPhoneOS.platform/Developer/Library/Frameworks:/Developer/Library/PrivateFrameworks";
    HOME = "/private/var/mobile/Containers/Data/Application/E1013861-12E3-4769-B25D-459B0A19D484";
    LOGNAME = mobile;
    NSUnbufferedIO = YES;
    "OS_ACTIVITY_DT_MODE" = YES;
    PATH = "/usr/bin:/bin:/usr/sbin:/sbin";
    SHELL = "/bin/sh";
    TMPDIR = "/private/var/mobile/Containers/Data/Application/E1013861-12E3-4769-B25D-459B0A19D484/tmp/";
    USER = mobile;
    "XCODE_DBG_XPC_EXCLUSIONS" = "com.apple.dt.xctestSymbolicator";
    XCTestConfigurationFilePath = "/private/var/mobile/Containers/Data/Application/E1013861-12E3-4769-B25D-459B0A19D484/tmp/WebDriverAgentRunner-26CBE273-2DA8-473C-8A26-521F9CC211F7.xctestconfiguration";
    "XPC_FLAGS" = 0x0;
    "XPC_SERVICE_NAME" = "UIKitApplication:com.apple.test.WebDriverAgentRunner-Runner[0xe2a5][63]";
    "__CF_USER_TEXT_ENCODING" = "0x1F5:0:0";
}
06:45:23.641 XCTRunner[2666:757505] <XCTWaiter: 0x170017590> entering wait loop for 5.00s
06:45:23.645 XCTRunner[2666:757522] Got daemon protocol version 12
06:45:23.645 XCTRunner[2666:757522] <XCTWaiter: 0x170017590>: cancelWaiting
06:45:23.645 XCTRunner[2666:757505] <XCTWaiter: 0x170017590> done waiting
06:45:23.645 XCTRunner[2666:757505] <XCTWaiter: 0x170017590> cleaning up Exchange protocol versions with daemon
06:45:23.645 XCTRunner[2666:757505] Requesting socket
06:45:23.646 XCTRunner[2666:757505] <XCTWaiter: 0x1740199e0> entering wait loop for 30.00s
06:45:23.752 XCTRunner[2666:757524] <XCTWaiter: 0x1740199e0>: cancelWaiting
06:45:23.752 XCTRunner[2666:757505] <XCTWaiter: 0x1740199e0> done waiting
06:45:23.752 XCTRunner[2666:757505] <XCTWaiter: 0x1740199e0> cleaning up Socket for IDE session acquired
06:45:23.752 XCTRunner[2666:757505] Creating transport with socket 4
06:45:23.752 XCTRunner[2666:757505] Creating connection with transport <DTXSocketTransport: 0x17010f9c0>
06:45:23.753 XCTRunner[2666:757505] Creating the proxy channel with connection <DTXConnection 0x1741e9e00 : x1>
06:45:23.753 XCTRunner[2666:757505] Messaging IDE proxy - _XCT_testBundleReadyWithProtocolVersion:22 minimumVersion:8
06:45:23.753 XCTRunner[2666:757505] <XCTWaiter: 0x1700176f0> entering wait loop for 30.00s
06:45:23.756 XCTRunner[2666:757521] _XCT_testBundleReadyWithProtocolVersion:minimumVersion: reply received
06:45:24.121 XCTRunner[2666:757521] _IDE_startExecutingTestPlanWithProtocolVersion:22
06:45:24.122 XCTRunner[2666:757521] <XCTWaiter: 0x1700176f0>: cancelWaiting
06:45:24.122 XCTRunner[2666:757505] <XCTWaiter: 0x1700176f0> done waiting
06:45:24.122 XCTRunner[2666:757505] <XCTWaiter: 0x1700176f0> cleaning up IDE session ready for test plan
06:45:26.151 xcodebuild[66020:605308] Starting test plan, clearing initialization timeout timer.
06:45:24.125 XCTRunner[2666:757505] Initializing for UI testing.
06:45:24.125 XCTRunner[2666:757505] <XCTWaiter: 0x170017730> entering wait loop for 20.00s
06:45:24.128 testmanagerd[2663:757233] Performing block with diagnostics...
06:45:24.129 testmanagerd[2663:757233] Waiting 15.0s for AX to finish loading...
06:45:24.131 testmanagerd[2663:757233] _AXSApplicationAccessibilityEnabled() returned false
===============================
```

**Comment by imurchie** [comment]
Can you post the Appium server logs as a link to a [gist](https://gist.github.com)?

**Comment by navinjethani** [comment]
https://gist.github.com/navinjethani/8d2f5a319e402487306de143802238a7

**Comment by imurchie** [comment]
This is the xcodebuild log. How is Appium involved here?

I would like to see the attempt to start a session through Appium.

**Comment by navinjethani** [comment]
https://gist.github.com/navinjethani/1efdb26a72bc5fba0b8e2d4a3fbdafd7

**Comment by mykola-mokhnach** [comment]
> 06:45:24.131 testmanagerd[2663:757233] _AXSApplicationAccessibilityEnabled() returned false

Are you sure the accessibility access is enabled on the device?

**Comment by imurchie** [comment]
Are you trying to do a Safari session or a session with `com.example.apple-samplecode.UICatalog`? Try one or the other. It also looks like you are killing the process part way through? https://gist.github.com/navinjethani/1efdb26a72bc5fba0b8e2d4a3fbdafd7#file-appium-console-log-L73

What happens if you just let it go? The log lines "Failed to create WDA session. Retrying..." are normal... it polls until the system is ready to receive requests.

**Comment by navinjethani** [comment]
I want the session with com.example.apple-samplecode.UICatalog

I set the --app com.example.apple-samplecode.UICatalog when I start appium
thru command line

Not sure, why Safari is being opened and going to appium.io.

Here is the Java code for creating Capabilities
=================================
       DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("deviceName", "iPhone 6");
        capabilities.setCapability("platformName", "iOS");
        capabilities.setCapability("platformVersion", "10.3");
        capabilities.setCapability("browserName", "safari");
        WebDriver driver = new IOSDriver(new URL("
http://127.0.0.1:4723/wd/hub"), capabilities);
=========================================

**Comment by imurchie** [comment]
Remove
```java
capabilities.setCapability("browserName", "safari");
```

**Comment by navinjethani** [comment]
making some progress, but still getting this error.
Thx for all your help

=============================
XCUITest] xcodebuild exited with code '65' and signal 'null'
[debug] [BaseDriver] Event 'wdaStartFailed' logged at 1505317275346
(08:41:15 GMT-0700 (PDT))
[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild
failure: xcodebuild failed with code 65
[debug] [XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down iproxy process (pid 69052)
[debug] [XCUITest] iproxy exited with code 'null'
[debug] [XCUITest] Removing WDA application from device
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild
failure: xcodebuild failed with code 65
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:386:15)
    at tryCatch
(/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke]
(/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next]
(/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke
(/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
 Error: Unable to launch WebDriverAgent because of xcodebuild failure:
xcodebuild failed with code 65
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:386:15)
    at tryCatch
(/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke]
(/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next]
(/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke
(/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles`
capability to turn on.
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: Unable to
launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with
code 65
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:386:15)
    at tryCatch
(/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke]
(/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next]
(/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke
(/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
[HTTP] <-- POST /wd/hub/session 500 53328 ms - 230
======================================

**Comment by imurchie** [comment]
This is now a code signing issue. Please see these instructions: https://github.com/appium/appium/blob/master/docs/en/drivers/ios-xcuitest-real-devices.md

**Comment by navinjethani** [comment]
Yes, you were correct.

Now I am able to control my app.


Thx you very much for your help.


Navin
