### ISSUE TITLE
Appium is not selecting checkbox.

### ISSUE THREAD

**Issue by vladbelo** [appium/appium#9212]
## Environment

* Appium version1.6.5

* Desktop OS
* Node.js version Appium.exe
* Mobile Android 6
* Real d emulator/simulator:
* Appium  Appium.app|exe:

## Details

This is my code: 

 public boolean checkBoxSelected() throws InterruptedException {
		
	  boolean vv = false;
	    Log.log( driver ).info("Selecting CheckbBox...");
	    
	    vv = new_checkBox.get(0).isSelected();
	    if(vv == false) {
	    	new_checkBox.get(0).click();
	    Log.log(driver).info( "Selected Checkbox" );
	    } else {
	    	view_changePass.click();
	    	}
		return true;
	    
	}

## Link to Appium logs

checkBoxSelected] Selecting CheckbBox...
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.appium.java_client.pagefactory.ElementListInterceptor.intercept(ElementListInterceptor.java:29)
	at $java.util.ArrayList$$EnhancerByCGLIB$$cf8af99d.get(<generated>)
	at com.disney.appium.pageobjects.Android.TicketsAndPasses.RenewalLanding_Page.checkBoxSelected(RenewalLanding_Page.java:62)
	at com.disney.appium.scripts.Android.TicketsAndPasses.AP_Verify_Guest_isableto_Select_an_eligible_Pass_to_renew.test(AP_Verify_Guest_isableto_Select_an_eligible_Pass_to_renew.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	... 32 more
PASSED: test

**Comment by mykola-mokhnach** [comment]
Please attach full server log

**Comment by vladbelo** [comment]
I was able to fix it. I have a question how do you compare an element with text with another element text if they are the same. So two elements in different web pages but they have the same text on them. How would you compare them if text is equal or not.

**Comment by mykola-mokhnach** [comment]
Please use Appium forum to ask questions.
