### ISSUE TITLE
Install APP on ios device not support app name which include non-ASCII character

### ISSUE THREAD

**Issue by qjdndgtg** [appium/appium#9239]
## The problem

I start appium with an app which include chinese character in app name. But it failed when install app. Could not find app in local device.

## Environment

1.update  appium  to 1.7.0  use npm 
2.Xcode  8.3.3
3.device: IOS 10.3.3,  iphone6

## Details

appium logs:
2017-09-19 03:22:23:097 - info: [Appium] Welcome to Appium v1.7.0
2017-09-19 03:22:23:098 - info: [Appium] Non-default server args:
2017-09-19 03:22:23:099 - info: [Appium]   log: /Users/cheng/Documents/appium.log
2017-09-19 03:22:23:222 - info: [Appium] Appium REST http interface listener started on 0.0.0.0:4723
2017-09-19 03:22:37:705 - info: [HTTP] --> GET /wd/hub/status {}
2017-09-19 03:22:37:707 - info: [debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
2017-09-19 03:22:37:717 - info: [debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.7.0","revision":null}}
2017-09-19 03:22:37:722 - info: [HTTP] <-- GET /wd/hub/status 200 15 ms - 83 
2017-09-19 03:22:37:725 - info: [HTTP] --> GET /wd/hub/sessions {}
2017-09-19 03:22:37:725 - info: [debug] [MJSONWP] Calling AppiumDriver.getSessions() with args: []
2017-09-19 03:22:37:727 - info: [debug] [MJSONWP] Responding to client with driver.getSessions() result: []
2017-09-19 03:22:37:728 - info: [HTTP] <-- GET /wd/hub/sessions 200 2 ms - 40 
2017-09-19 03:22:37:776 - info: [HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"iOS","newCommandTimeout":"7200","app":"/Users/cheng/Documents/SurveillanceSystem.ipa","platformVersion":"10.3","deviceName":"iPhone 6","bundleId":"net.tplink.surveillancesystem","automationName":"Appium"}}
2017-09-19 03:22:37:776 - info: [debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"iOS","newCommandTimeout":"7200","app":"/Users/cheng/Documents/SurveillanceSystem.ipa","platformVersion":"10.3","deviceName":"iPhone 6","bundleId":"net.tplink.surveillancesystem","automationName":"Appium"},null,null]
2017-09-19 03:22:37:776 - info: [debug] [BaseDriver] Event 'newSessionRequested' logged at 1505791357776 (11:22:37 GMT+0800 (CST))
2017-09-19 03:22:37:778 - info: [Appium] Requested iOS support with version >= 10, using XCUITest driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
2017-09-19 03:22:37:778 - info: [Appium] Creating new XCUITestDriver (v2.49.0) session
2017-09-19 03:22:37:778 - info: [Appium] Capabilities:
2017-09-19 03:22:37:780 - info: [Appium]   platformName: 'iOS'
2017-09-19 03:22:37:780 - info: [Appium]   newCommandTimeout: '7200'
2017-09-19 03:22:37:780 - info: [Appium]   app: '/Users/cheng/Documents/SurveillanceSystem.ipa'
2017-09-19 03:22:37:780 - info: [Appium]   platformVersion: '10.3'
2017-09-19 03:22:37:780 - info: [Appium]   deviceName: 'iPhone 6'
2017-09-19 03:22:37:780 - info: [Appium]   bundleId: 'net.tplink.surveillancesystem'
2017-09-19 03:22:37:780 - info: [Appium]   automationName: 'Appium'
2017-09-19 03:22:37:783 - warn: [BaseDriver] Capability 'newCommandTimeout' changed from string ('7200') to integer (7200). This may cause unexpected behavior
2017-09-19 03:22:37:893 - info: [BaseDriver] Session created with session id: 48eedb2f-e355-4a4f-ab59-4242d49a8951
2017-09-19 03:22:38:885 - info: [debug] [XCUITest] Xcode version set to '8.3.3' (tools v8.3.2.0.1.1492020469)
2017-09-19 03:22:38:908 - info: [debug] [XCUITest] iOS SDK Version set to '10.3'
2017-09-19 03:22:38:908 - info: [debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1505791358908 (11:22:38 GMT+0800 (CST))
2017-09-19 03:22:39:215 - info: [iOSSim] Constructing iOS simulator for Xcode version 8.3.3 with udid 'CA5104BA-8240-45E5-AA39-8C76BE71ECB5'
2017-09-19 03:22:39:216 - info: [XCUITest] Determining device to run tests on: udid: 'CA5104BA-8240-45E5-AA39-8C76BE71ECB5', real device: false
2017-09-19 03:22:39:217 - info: [BaseDriver] Using local app '/Users/cheng/Documents/SurveillanceSystem.ipa'
2017-09-19 03:22:39:217 - info: [debug] [BaseDriver] Copying local zip to tmp dir
2017-09-19 03:22:39:881 - info: [debug] [BaseDriver] Unzipping /var/folders/kl/_7mq_jyn7xd0n20_zz56h5600000gn/T/2017819-2103-yf3vu5.3wyu/appium-app.zip
2017-09-19 03:22:39:881 - info: [debug] [BaseDriver] Testing zip archive: /var/folders/kl/_7mq_jyn7xd0n20_zz56h5600000gn/T/2017819-2103-yf3vu5.3wyu/appium-app.zip
2017-09-19 03:22:41:099 - info: [BaseDriver] Unzipped local app to '/var/folders/kl/_7mq_jyn7xd0n20_zz56h5600000gn/T/2017819-2103-yf3vu5.3wyu/Payload/Ch-LINK�?�?�.app'
2017-09-19 03:22:41:100 - info: [debug] [BaseDriver] Event 'appConfigured' logged at 1505791361100 (11:22:41 GMT+0800 (CST))
2017-09-19 03:22:41:100 - info: [debug] [XCUITest] Checking whether app '/var/folders/kl/_7mq_jyn7xd0n20_zz56h5600000gn/T/2017819-2103-yf3vu5.3wyu/Payload/Ch-LINK�?�?�.app' is actually present on file system
2017-09-19 03:22:41:154 - error: [XCUITest] Error: Could not find app at '/var/folders/kl/_7mq_jyn7xd0n20_zz56h5600000gn/T/2017819-2103-yf3vu5.3wyu/Payload/Ch-LINK�?�?�.app'
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at checkAppPresent$ (../../lib/utils.js:200:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/_babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/_babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/_babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/_babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
 Error: Could not find app at '/var/folders/kl/_7mq_jyn7xd0n20_zz56h5600000gn/T/2017819-2103-yf3vu5.3wyu/Payload/TP-LINK�?�?�.app'
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at checkAppPresent$ (../../lib/utils.js:200:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/_babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/_babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/_babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/_babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
2017-09-19 03:22:41:154 - error: [XCUITest] Error: Could not find app at '/var/folders/kl/_7mq_jyn7xd0n20_zz56h5600000gn/T/2017819-2103-yf3vu5.3wyu/Payload/TP-LINK�?�?�.app'
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at checkAppPresent$ (../../lib/utils.js:200:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/_babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/_babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/_babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/_babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
 Error: Could not find app at '/var/folders/kl/_7mq_jyn7xd0n20_zz56h5600000gn/T/2017819-2103-yf3vu5.3wyu/Payload/Ch-LINK�?�?�.app'
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at checkAppPresent$ (../../lib/utils.js:200:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/_babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/_babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/_babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/_babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
2017-09-19 03:22:41:155 - info: [debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
2017-09-19 03:22:41:156 - error: [MJSONWP] Encountered internal error running command: Error: Could not find app at '/var/folders/kl/_7mq_jyn7xd0n20_zz56h5600000gn/T/2017819-2103-yf3vu5.3wyu/Payload/Ch-LINK�?�?�.app'
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at checkAppPresent$ (../../lib/utils.js:200:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/_babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/_babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/_babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/_babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>

**Comment by mykola-mokhnach** [comment]
Make sure the characters are encoded in UTF-8. Also, you can try to extract the .app file from .ipa archive manually and provide the path to it in capabilities

**Comment by qjdndgtg** [comment]
After extract the .app file from .ipa archive manually and rename the non-ASCII characters, Appium has worked. Thanks,it help me a lot .
When I use appium to install app, it unzipped the ipa file directly, so this issue is my app file has non-ASCII characters. Thank you@mykola-mokhnach
