### ISSUE TITLE
[from appium import webdriver]:  from .webdriver import WebDriver as Remote ImportError: No module named webdriver

### ISSUE THREAD

**Issue by helenakeep** [appium/appium#9253]
## The problem
when i run the appium sample-code at github,just run the command: python andriod_simple.py,
it's failed 
## Environment

* Appium version (or git revision):
1.6.5 server and desktop on mac
*Appium Client(git version) :
https://github.com/appium/python-client
* Desktop OS/version used to run Appium:
mac 10.12.1
* Node.js version (unless using Appium.app|exe):
v6.3.1

## Details
Traceback (most recent call last):
  File "android_simple.py", line 6, in <module>
    from appium import webdriver
  File "build/bdist.macosx-10.12-intel/egg/appium/webdriver/__init__.py", line 19, in <module>
  File "build/bdist.macosx-10.12-intel/egg/appium/webdriver/webdriver.py", line 15, in <module>
  File "/Library/Python/2.7/site-packages/selenium-3.0.0.b2-py2.7.egg/selenium/webdriver/__init__.py", line 19, in <module>
    from .webdriver import WebDriver as Remote
ImportError: No module named webdriver

**Comment by helenakeep** [comment]
resolved ,because of python3

**Comment by sundeepdev** [comment]
Hi @helenakeep , Could you tell what was the issue and how did you resolve it? I'm also facing the same issue.
