### ISSUE TITLE
Multiple device support in Appium 1.7.0 with IOS 11

### ISSUE THREAD

**Issue by swachhab** [appium/appium#9256]
## The problem
Unable to perform parallel testing with this new release of Appium ie 1.7.0

## Environment
Appium: 1.7.0
Xcode: 9
IOS 11
Real Devices: Iphone 7 and Ipad Air2
## Details

Today upgraded my system with updated xcode(9) and Appium. Previously with appium version 1.6.5 and Ios 10.3.3 we were able to execute testcases on multiple devices parallel by providing unique wdalocalport for each device and running appium on different ports for each device.
But now after updation We are not able to execute it parallel, even though execution is running on multiple devices but its running in sequentially like it is executing two or three commands on one device and then executes two or three commands in second device.

I have read release notes for latest appium 1.7.0, and its written over there under "IOS" "Multiple device support". Please us know how to resolve this or What I am missing.

**Comment by mykola-mokhnach** [comment]
Now it is not necessary to start multiple server. It's enough to just provide different WDA port number.
You can check https://github.com/saikrishna321/AppiumTestDistribution/blob/master/src/main/java/com/appium/utils/DesiredCapabilityBuilder.java for the reference

**Comment by swachhab** [comment]
@mykola-mokhnach I just tried with same appium server and different WDA ports, even though same appium server working for both devices but its not able to perform parallel testing as before, It is executing test cases sequentially.

**Comment by swachhab** [comment]
Also tried to run multiple devices on same appium port, but after few test cases got some exception in appium logs:

[debug] [BaseDriver] Event 'wdaSessionStarted' logged at 1505953769851 (05:59:29 GMT+0530 (IST))
[debug] [XCUITest] Cannot find a match for DerivedData folder path from lsof. Trying to access logs
[XCUITest] Error: "toString()" failed
    at Buffer.toString (buffer.js:513:11)
    at RegExp.exec (native)
    at XcodeBuild.retrieveDerivedDataPath$ (../../../lib/wda/xcodebuild.js:110:42)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: "toString()" failed
    at Buffer.toString (buffer.js:513:11)
    at RegExp.exec (native)
    at XcodeBuild.retrieveDerivedDataPath$ (../../../lib/wda/xcodebuild.js:110:42)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[debug] [XCUITest] Cannot find a match for DerivedData folder path from lsof. Trying to access logs
[MJSONWP] Encountered internal error running command: Error: "toString()" failed
    at Buffer.toString (buffer.js:513:11)
    at RegExp.exec (native)
    at XcodeBuild.retrieveDerivedDataPath$ (../../../lib/wda/xcodebuild.js:110:42)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)

**Comment by VSsingh** [comment]
Is appium 1.7.0 supports window 7 because i am not able to use latest appium on window 7 apart from appium 1.4.16

**Comment by swachhab** [comment]
Am working on mac Os, not yet tried on windows

**Comment by mykola-mokhnach** [comment]
@swachhab Can you try to update NodeJS to the most recent version?

**Comment by swachhab** [comment]
Updated NodeJS but no luck!

**Comment by mykola-mokhnach** [comment]
Most likely your Xcode log file is too big, so it cannot fit into the memory. Try to clean up Xcode derived data.

**Comment by cosminstirbu** [comment]
@mykola-mokhnach - I've left a comment on https://github.com/appium/appium-xcuitest-driver/pull/530 - can you please advise what would be the best approach to bring this fix into my Appium 1.7.0 installation? Thank you.

**Comment by mykola-mokhnach** [comment]
@cosminstirbu Wait for the next driver version tag and reinstall 1.7.0-beta. The patch will be available there.
