### ISSUE TITLE
Logcat terminated with code 0, signal null

### ISSUE THREAD

**Issue by gundamsing** [appium/appium#9294]
## The problem

Hallo, i'm using intelliJ with appium1.6.5 to run my android testcases, sometime the testcases ends up with this logs below.

[2017-09-25T17:07:44.751+0200] [INFO] com.xxxxx.tools.appium.internal.DeviceRunner - Running test checkAddedBookmarksAfterEntitlementLogoutHtml on device SGP712 {CB5A28GNDH}
[2017-09-25T17:07:44.751+0200] [INFO] com.xxxxx.tools.appium.internal.android.AndroidUtils - Resetting App com.xxxxx.appiumtestapp on AndroidDevice{deviceSerial='CB5A28GNDH', product='SGP712', model='SGP712', device='SGP712'}
[HTTP] Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.
Error: listen EADDRINUSE 0.0.0.0:22844
    at Object.exports._errnoException (util.js:1008:11)
    at exports._exceptionWithHostPort (util.js:1031:20)
    at Server._listen2 (net.js:1253:14)
    at listen (net.js:1289:10)
    at net.js:1399:9
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[ADB] Cannot read version codes of /usr/local/lib/node_modules/appium/node_modules/io.appium.settings/app/build/outputs/apk/settings_apk-debug.apk and/or io.appium.settings. Assuming correct app version is already installed
[AndroidDriver] No app sent in, not parsing package/activity
[2017-09-25T17:08:06.088+0200] [INFO] org.openqa.selenium.remote.ProtocolHandshake - Detected dialect: OSS
[2017-09-25T17:08:06.107+0200] [INFO] com.xxxxx.purple.pages.StartPage - Click OK button on dialog
[2017-09-25T17:08:28.462+0200] [INFO] com.xxxxx.purple.pages.StartPage - External storage not found
[2017-09-25T17:09:10.902+0200] [INFO] com.xxxxx.purple.pages.MenuPage - Click Kiosk entry in menu
[Logcat] Logcat terminated with code 0, signal null
[UiAutomator] UiAutomator exited unexpectedly with code 0, signal null
[Appium] Closing session, cause was 'UiAUtomator shut down unexpectedly'
[MJSONWP] Encountered internal error running command: Error: UiAUtomator shut down unexpectedly
    at AndroidBootstrap.callee$2$0$ (../../lib/bootstrap.js:76:44)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at Promise.exports.(anonymous function).target.(anonymous function).function.target.(anonymous function).F (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at UiAutomator.callee$2$0 (../../lib/bootstrap.js:73:64)
    at emitOne (events.js:96:13)
    at UiAutomator.emit (events.js:188:7)
    at UiAutomator.changeState (../../lib/uiautomator.js:85:10)
    at SubProcess.<anonymous> (../../lib/uiautomator.js:47:14)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (../../lib/teen_process.js:205:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
Unhandled rejection Error: No device connected, cannot run adb shell command 'am force-stop com.xxxxx.appiumtestapp'
    at ADB.callee$0$0$ (../../../lib/tools/system-calls.js:209:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[2017-09-25T17:09:34.965+0200] [WARN] com.xxxxx.tools.appium.internal.DeviceRunner - Could not save screenshot: org.openqa.selenium.NoSuchSessionException: A session is either terminated or not started (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:42:44.417Z'
System info: host: 'MBP.local', ip: '2001:1438:4010:2812:0:0:0:ff50', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_91'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{appPackage=com.XXXXX.appiumtestapp, deviceScreenSize=2560x1600, networkConnectionEnabled=true, noReset=true, warnings={}, databaseEnabled=false, deviceName=CB5A28GNDH, fullReset=false, platform=LINUX, deviceUDID=CB5A28GNDH, appActivity=com.xxxxx.purple.android.app.purple.splash.SplashActivity, desired={appPackage=com.xxxxx.appiumtestapp, appActivity=com.xxxxx.purple.android.app.purple.splash.SplashActivity, noReset=true, newCommandTimeout=300, udid=CB5A28GNDH, platformName=Android, deviceName=SGP712, fullReset=false}, newCommandTimeout=300, platformVersion=6.0.1, webStorageEnabled=false, locationContextEnabled=false, takesScreenshot=true, javascriptEnabled=true, deviceModel=SGP712, udid=CB5A28GNDH, deviceManufacturer=Sony, platformName=LINUX}]
Session ID: 2f48b7d5-bc0e-46fd-8196-d121e7da6fba
org.openqa.selenium.NoSuchSessionException: A session is either terminated or not started (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:42:44.417Z'
System info: host: 'MBP.local', ip: '2001:1438:4010:2812:0:0:0:ff50', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_91'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{appPackage=com.xxxxx.appiumtestapp, deviceScreenSize=2560x1600, networkConnectionEnabled=true, noReset=true, warnings={}, databaseEnabled=false, deviceName=CB5A28GNDH, fullReset=false, platform=LINUX, deviceUDID=CB5A28GNDH, appActivity=com.xxxxx.purple.android.app.purple.splash.SplashActivity, desired={appPackage=com.xxxxx.appiumtestapp, appActivity=com.xxxxx.purple.android.app.purple.splash.SplashActivity, noReset=true, newCommandTimeout=300, udid=CB5A28GNDH, platformName=Android, deviceName=SGP712, fullReset=false}, newCommandTimeout=300, platformVersion=6.0.1, webStorageEnabled=false, locationContextEnabled=false, takesScreenshot=true, javascriptEnabled=true, deviceModel=SGP712, udid=CB5A28GNDH, deviceManufacturer=Sony, platformName=LINUX}]
Session ID: 2f48b7d5-bc0e-46fd-8196-d121e7da6fba
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:167)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:82)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:45)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:89)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:646)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:46)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.getScreenshotAs(RemoteWebDriver.java:388)
	at com.xxxxx.tools.appium.internal.DeviceRunner$AppiumDriverStatement.evaluate(DeviceRunner.java:273)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at com.xxxxx.tools.appium.internal.DeviceRunner$AppUninstallChildrenInvokerStatement.evaluate(DeviceRunner.java:224)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at com.xxxxx.tools.appium.AppiumMultiDeviceTestRunner.runChild(AppiumMultiDeviceTestRunner.java:151)
	at com.xxxxx.tools.appium.AppiumMultiDeviceTestRunner.runChild(AppiumMultiDeviceTestRunner.java:46)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at com.xxxxx.tools.appium.AppiumMultiDeviceTestRunner$1.evaluate(AppiumMultiDeviceTestRunner.java:140)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
[2017-09-25T17:09:34.966+0200] [INFO] com.xxxxx.tools.appium.internal.DeviceRunner - Finished test checkAddedBookmarksAfterEntitlementLogoutHtml on device SGP712 {CB5A28GNDH}

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.0
* Last Appium version that did not exhibit the issue (if applicable): 1.6.4
* Desktop OS/version used to run Appium: macOS Sierra 10.12.6
* Node.js version (unless using Appium.app|exe): v6.3.0
* Mobile platform/version under test: Android 6.0.1, 5.0.2
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

**Comment by SamyQAZ** [comment]
Got the same issue, struggling hard to work on it.
Not sure how to fix.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue. Most likely a race condition on the client side
