### ISSUE TITLE
Appium 1.7.0beta throws No space left on device on iOS Simulator

### ISSUE THREAD

**Issue by cosminstirbu** [appium/appium#9309]
## The problem

We have a large suite of end to end tests (approx. 647) that run sequentially on an iOS simulator - they take around 12 hrs to run.
Recently, after updating to Appium 1.7.0beta and Xcode 9, the tests have been running fine for two nights, but last night after 7 hrs of running we started receiving this error: `No space left on device`

We have 40gb free on our server, so I don't think we have an issue related to that.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.0beta
* Last Appium version that did not exhibit the issue (if applicable): 1.6.4 (maybe even 1.6.5)
* Desktop OS/version used to run Appium: macOS 10.12.6
* Node.js version (unless using Appium.app|exe): 7.0.0
* Mobile platform/version under test: iOS 11.0
* Real device or emulator/simulator: iPhone 5s
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs

```
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: simctl error running 'install': An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=28):
      copyfile of file:///Users/jenkins/.jenkins/jobs/MyApp/jobs/AQA/jobs/iOS/workspace/iOS/build-simulator/MyApp.app/ to file:///Users/jenkins/Library/Developer/CoreSimulator/Devices/936C7D51-F6C3-41D3-B80B-5411C92491DE/data/Containers/Shared/SystemGroup/systemgroup.com.apple.installcoordinationd/Library/InstallCoordination/PromiseStaging/1912C4C2-45E4-4120-8F38-303CC59D66C8/MyApp.app failed: No space left on device
```

**Comment by mykola-mokhnach** [comment]
Try to find out which file/folder on the local FS is taking the space. I'd start with Xcode derived data folder and temporary files.

**Comment by cosminstirbu** [comment]
WebDriverAgent's Derived Data takes 9 gigs. But I'm not sure I understand why is this a problem if there are 40 gigs available on the machine?

I know that in the past there was a problem with WebDriverAgent's Derived Data growing continuously that's why I had a small script that was wiping it out before starting the whole suite of tests. I was under the impression that this was fixed in recent versions of Appium. Should I put that script back in place?

**Comment by cosminstirbu** [comment]
Also, what's interesting is that it caused our Android tests to crash as well. At some point during the night while they were running (iOS and Android run at the same time, on different instances of Appium on the same machine) - we started receiving this error on Android after Appium crashed and we tried to restart it automatically:

```
[MJSONWP] Encountered internal error running command: Error: Error executing adbExec. Original error: 'Command '/Users/jenkins/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop com.mywebgrocer.personalshopper.rd.qa' timed out after 20000ms'; Stderr: ''; Code: 'null'
    at ADB.execFunc$ (../../../lib/tools/system-calls.js:317:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoorg.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/Users/jenkins/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop com.myapplication' timed out after 20000ms'; Stderr: ''; Code: 'null' (WARNING: The server did not provide any stacktrace information)
```

**Comment by mykola-mokhnach** [comment]
Try _clearSystemFiles_ capability. Also it might be a good idea to perform temporary files cleanup from time to time.

**Comment by cosminstirbu** [comment]
I'll try that and get back to you when I have the results. Thank you.

**Comment by cosminstirbu** [comment]
Yes, after running the tests it seems like the problem was fixed. We can close this issue and if I run into this again I'll let you know.

Thank you,
Cosmin

**Comment by cosminstirbu** [comment]
Hi,

After a while this issue started reproducing again.
Although finder indicates that there are 40 gigs free space, we received this error even after upgrading to Appium 1.7.1

What's even interesting is that we received this error on our build server even when we were simply building one of our projects using xcodebuild when it was trying to write to the Derived Data folder, so we weren't running any Appium related applications / tools.

Although if we re-ran the job, it worked just fine, so there's no pattern in actually reproducing this.

I've did a bit of research and I've found that it could also be some sort of permissions issue.

Is Appium maybe setting some sort of permissions on Derived Data that might cause this?

Thank you,
Cosmin

**Comment by mykola-mokhnach** [comment]
Set the _preventWDAAttachments_ capability to _false_ to avoid permissions midifications

**Comment by cosminstirbu** [comment]
We'll try, monitor, and let you know. Thank you!

**Comment by cosminstirbu** [comment]
The issue still reproduces :(.

This is a new stacktrace, it seems that it occurs when trying to install the app on the simulator:

```
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: simctl error running 'install': An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=28):
copyfile of file:///Users/jenkins/.jenkins/jobs/MyApp/jobs/AQA/jobs/iOS_Parallel/workspace/iOS/build-simulator/MyApp.app/ to file:///Users/jenkins/Library/Developer/CoreSimulator/Devices/936C7D51-F6C3-41D3-B80B-5411C92491DE/data/Containers/Shared/SystemGroup/systemgroup.com.apple.installcoordinationd/Library/InstallCoordination/PromiseStaging/B6661EB8-9E24-40D7-8D70-088A7872C5FD/MyApp.app failed: No space left on device
No space left on device (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 5.14 seconds
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T15:28:36.4Z'
System info: host: 'osxbuildserver.internal.mywebgrocer.com', ip: '10.0.40.9', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_91'
Driver info: driver.version: IOSDriver
	at sun.reflect.GeneratedConstructorAccessor100.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$new$0(JsonWireProtocolResponse.java:53)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$getResponseFunction$2(JsonWireProtocolResponse.java:91)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$24(ProtocolHandshake.java:359)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:362)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:136)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:89)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:586)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:217)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:140)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:83)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:93)
	at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:78)
	at utils.TestBase.startDriver(TestBase.java:94)
	at utils.TestBase.launchAppWithCleanData(TestBase.java:50)
	at glue.hooks.Hooks.onScenarioStart(Hooks.java:14)
	at sun.reflect.GeneratedMethodAccessor37.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cucumber.runtime.Utils$1.call(Utils.java:40)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.Utils.invoke(Utils.java:34)
	at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)
	at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:224)
	at cucumber.runtime.Runtime.runHooks(Runtime.java:212)
	at cucumber.runtime.Runtime.runBeforeHooks(Runtime.java:202)
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:40)
	at cucumber.runtime.junit.ExecutionUnitRunner.run(ExecutionUnitRunner.java:102)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:63)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:18)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:70)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:95)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:38)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at cucumber.api.junit.Cucumber.run(Cucumber.java:100)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:369)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:275)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:239)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:160)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
```

**Comment by cosminstirbu** [comment]
And I've also received a similar error, although it doesn't mention the space issue:

`org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: simctl error running 'install': An error was encountered processing the command (domain=MIInstallerErrorDomain, code=5):
Failed to copy /Users/jenkins/.jenkins/jobs/MyApp/jobs/AQA/jobs/iOS_Parallel/workspace/iOS/build-simulator/MyApp.app to file:///Users/jenkins/Library/Developer/CoreSimulator/Devices/A45F5748-180C-4D23-B1DD-A4CEAE08909B/data/Library/Caches/com.apple.mobile.installd.staging/temp.6eybsz/extracted/MyApp.app/ (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 4.42 seconds
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T15:28:36.4Z'
System info: host: 'osxbuildserver.internal.mycompany.com', ip: '10.0.40.9', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_91'
Driver info: driver.version: IOSDriver
	at sun.reflect.GeneratedConstructorAccessor136.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$new$0(JsonWireProtocolResponse.java:53)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$getResponseFunction$2(JsonWireProtocolResponse.java:91)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$24(ProtocolHandshake.java:359)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:362)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:136)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:89)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:586)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:217)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:140)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:83)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:93)
	at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:78)
	at utils.TestBase.startDriver(TestBase.java:94)
	at utils.TestBase.launchAppWithCleanData(TestBase.java:50)
	at glue.hooks.Hooks.onScenarioStart(Hooks.java:14)
	at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cucumber.runtime.Utils$1.call(Utils.java:40)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.Utils.invoke(Utils.java:34)
	at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)
	at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:224)
	at cucumber.runtime.Runtime.runHooks(Runtime.java:212)
	at cucumber.runtime.Runtime.runBeforeHooks(Runtime.java:202)
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:40)
	at cucumber.runtime.junit.ExecutionUnitRunner.run(ExecutionUnitRunner.java:102)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:63)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:18)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:70)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:95)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:38)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at cucumber.api.junit.Cucumber.run(Cucumber.java:100)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:369)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:275)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:239)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:160)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)`

**Comment by cosminstirbu** [comment]
I did some cleanup on our build machine, now we have 130GB free.

I did play around with both clearSystemFiles and preventWDAAttachments, had them both set to true - while monitoring the test execution, I noticed that after 2 hrs of execution we went down to only 120 GB free (while WebDriver derived data size was just 26 mb) - so there definitely is something that takes our space. As the tests kept running, after almost 8hrs our free space was somewhere around 80 GB - so this explains why we were receiving this error when we had "only" 40 GB free space.

However, when the tests finish executing, and we reopen the iOS simulator, all that space is freed up.

Not sure if there might be an issue with xcodebuild itself and Apple tooling, or with Appium tooling.

**Comment by mykola-mokhnach** [comment]
Try to check temporary files. I would start with something like this: `find ${path_to_the_root_folder} -type f -size +10000k -exec ls -lh {} \`

**Comment by cosminstirbu** [comment]
I've ran `find /private/var -type f -size +10000k -exec ls -lh {} \;`

and it looks that there are some large WebDriver related temp folders folders: 

```
-rw-------  1 jenkins  staff   2.4G Oct  9 00:25 /private/var/folders/6v/xlw3p2pn47d2jl_jghf25dn00000gr/T/com.apple.dt.XCTest/IDETestRunSession-09A74A61-57A5-451C-B53F-7D2AF0433F5D/WebDriverAgentRunner-B85A5DD9-016F-4B3C-ABBD-6E8E7FF919E4/Session-WebDriverAgentRunner-2017-10-08_144754-OaDrjW.log
-rw-r--r--  1 jenkins  staff    94M Oct  9 00:26 /private/var/folders/6v/xlw3p2pn47d2jl_jghf25dn00000gr/T/com.apple.dt.XCTest/IDETestRunSession-09A74A61-57A5-451C-B53F-7D2AF0433F5D/WebDriverAgentRunner-B85A5DD9-016F-4B3C-ABBD-6E8E7FF919E4/StandardOutputAndStandardError.txt
-rw-------  1 jenkins  staff   2.7G Oct  9 00:25 /private/var/folders/6v/xlw3p2pn47d2jl_jghf25dn00000gr/T/com.apple.dt.XCTest/IDETestRunSession-79745577-69B0-4182-84FA-72271EACFD4E/WebDriverAgentRunner-0F11439B-00BC-4222-927A-C78CBC7A7CB1/Session-WebDriverAgentRunner-2017-10-08_144808-Vd0QQ8.log
-rw-r--r--  1 jenkins  staff   102M Oct  9 00:26 /private/var/folders/6v/xlw3p2pn47d2jl_jghf25dn00000gr/T/com.apple.dt.XCTest/IDETestRunSession-79745577-69B0-4182-84FA-72271EACFD4E/WebDriverAgentRunner-0F11439B-00BC-4222-927A-C78CBC7A7CB1/StandardOutputAndStandardError.txt
-rw-------  1 jenkins  staff   559M Oct  8 14:37 /private/var/folders/6v/xlw3p2pn47d2jl_jghf25dn00000gr/T/com.apple.dt.XCTest/IDETestRunSession-C7DCA4FB-1E24-435D-BCCC-6C2F767CC7C2/WebDriverAgentRunner-EB98A420-E023-4D96-BCBC-0D51E64D6235/Session-WebDriverAgentRunner-2017-10-08_125539-dpcDbk.log
-rw-r--r--  1 jenkins  staff    21M Oct  8 14:37 /private/var/folders/6v/xlw3p2pn47d2jl_jghf25dn00000gr/T/com.apple.dt.XCTest/IDETestRunSession-C7DCA4FB-1E24-435D-BCCC-6C2F767CC7C2/WebDriverAgentRunner-EB98A420-E023-4D96-BCBC-0D51E64D6235/StandardOutputAndStandardError.txt
-rw-------  1 jenkins  staff   2.3G Oct  8 12:49 /private/var/folders/6v/xlw3p2pn47d2jl_jghf25dn00000gr/T/com.apple.dt.XCTest/IDETestRunSession-DC792018-77D9-4424-A5E2-1977610BC602/WebDriverAgentRunner-7873C835-3B01-4B2B-AA9F-1F14B0B3C270/Session-WebDriverAgentRunner-2017-10-08_051043-xgSYKX.log
-rw-r--r--  1 jenkins  staff    93M Oct  8 12:49 /private/var/folders/6v/xlw3p2pn47d2jl_jghf25dn00000gr/T/com.apple.dt.XCTest/IDETestRunSession-DC792018-77D9-4424-A5E2-1977610BC602/WebDriverAgentRunner-7873C835-3B01-4B2B-AA9F-1F14B0B3C270/StandardOutputAndStandardError.txt
-rw-------  1 jenkins  staff   532M Oct  8 14:37 /private/var/folders/6v/xlw3p2pn47d2jl_jghf25dn00000gr/T/com.apple.dt.XCTest/IDETestRunSession-E6C2833E-FD81-47AD-BBF1-09402AA34E67/WebDriverAgentRunner-0BED6A41-9D85-4808-A30E-CCC38F37FC4B/Session-WebDriverAgentRunner-2017-10-08_125538-xYdeJZ.log
-rw-r--r--  1 jenkins  staff    20M Oct  8 14:35 /private/var/folders/6v/xlw3p2pn47d2jl_jghf25dn00000gr/T/com.apple.dt.XCTest/IDETestRunSession-E6C2833E-FD81-47AD-BBF1-09402AA34E67/WebDriverAgentRunner-0BED6A41-9D85-4808-A30E-CCC38F37FC4B/StandardOutputAndStandardError.txt
-rw-------  1 jenkins  staff   2.6G Oct  8 12:49 /private/var/folders/6v/xlw3p2pn47d2jl_jghf25dn00000gr/T/com.apple.dt.XCTest/IDETestRunSession-F9070B58-CA21-483A-AD13-744C056F7233/WebDriverAgentRunner-E839FD71-4DCB-4BD5-BF9C-837D4E529B49/Session-WebDriverAgentRunner-2017-10-08_051030-2QLB63.log
-rw-r--r--  1 jenkins  staff   100M Oct  8 12:49 /private/var/folders/6v/xlw3p2pn47d2jl_jghf25dn00000gr/T/com.apple.dt.XCTest/IDETestRunSession-F9070B58-CA21-483A-AD13-744C056F7233/WebDriverAgentRunner-E839FD71-4DCB-4BD5-BF9C-837D4E529B49/StandardOutputAndStandardError.txt
```

**Comment by mykola-mokhnach** [comment]
Please create an enhancement request with this output attached and mention about it's reproducible with Xcode9. I'll try to the cleanup of these large logs to clearSystemFiles capability.

Thanks again for helping us to deal with it. It's hardly possible to repro such issues in test env.
