### ISSUE TITLE
AppiumDriver.restApp() does not work on WindowsDriver

### ISSUE THREAD

**Issue by mdmamunkhan** [appium/appium#9327]
I am testing both iOS and Windows App using AppiumDriver, my driver.resetApp() function works for iOSDriver but I does not for WindowdDriver. here is error "UnsupportedCommand java.lang.ClassCastExcep... "

**Comment by mykola-mokhnach** [comment]
Please attach full server log

**Comment by mdmamunkhan** [comment]
[Appium] Welcome to Appium v1.6.5
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"Engage.Windows.Universal_dp70g6tj9gy86!App","platformName":"Windows","deviceName":"WindowsPC"},"requiredCapabilities":{},"capabilities":{"desiredCapabilities":{"app":"Engage.Windows.Universal_dp70g6tj9gy86!App","platformName":"Windows","deviceName":"WindowsPC"},"requiredCapabilities":{},"alwaysMatch":{"platformName":"Windows"},"firstMatch":[]}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"Engage.Windows.Universal_dp70g6tj9gy86!App","platformName":"Windows","deviceName":"WindowsPC"},{},{"desiredCapabilities":{"app":"Engage.Windows.Universal_dp70g6tj9gy86!App","platformName":"Windows","deviceName":"WindowsPC"},"requiredCapabilities":{},"alwaysMatch":{"platformName":"Windows"},"firstMatch":[]}]
[BaseDriver] Event 'newSessionRequested' logged at 1506614288034 (11:58:08 GMT-0400 (Eastern Daylight Time))
[Appium] Creating new WindowsDriver (v0.5.0) session
[Appium] Capabilities:
[Appium]   app: 'Engage.Windows.Universal_dp70g6tj9gy86!App'
[Appium]   platformName: 'Windows'
[Appium]   deviceName: 'WindowsPC'
[BaseDriver] The following capabilities were provided, but are not recognized by appium: app.
[BaseDriver] Session created with session id: 012a3176-b0d6-4b08-9a81-9f7d43453f84
[WinAppDriver] Verifying WinAppDriver is installed with correct checksum
[WinAppDriver] WinAppDriver changed state to 'starting'
[WinAppDriver] Killing any old WinAppDrivers on same port, running: FOR /F "usebackq tokens=5" %a in (`netstat -nao ^| findstr /R /C:"4724 "`) do (FOR /F "usebackq" %b in (`TASKLIST /FI "PID eq %a" ^| findstr /I winappdriver.exe`) do (IF NOT %b=="" TASKKILL /F /PID %a))
[WinAppDriver] No old WinAppDrivers seemed to exist
[WinAppDriver] Spawning winappdriver with: undefined 4724/wd/hub
[WinAppDriver] [STDOUT] Windows Application Driver Beta listening for requests at: http://127.0.0.1:4724/wd/hub
[WinAppDriver] WinAppDriver changed state to 'online'
[JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:4724/wd/hub/session] with body: {"desiredCapabilities":{"app":"Engage.Windows.Universal_dp70g6tj9gy86!App","platformName":"Windows","deviceName":"WindowsPC"}}
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] Address 'http://127.0.0.1:4724/wd/hub' is already in use
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] Failed to initialize: 0x80004005
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] ==========================================
[WinAppDriver] [STDOUT] POST /wd/hub/session HTTP/1.1
[WinAppDriver] [STDOUT] Accept: */*
[WinAppDriver] [STDOUT] Connection: keep-alive
[WinAppDriver] [STDOUT] Content-Length: 126
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] Host: 127.0.0.1:4724
[WinAppDriver] [STDOUT] User-Agent: appium
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] {"desiredCapabilities":{"app":"Engage.Windows.Universal_dp70g6tj9gy86!App","platformName":"Windows","deviceName":"WindowsPC"}}
[WinAppDriver] WinAppDriver exited unexpectedly with code 2147500037, signal null
[WinAppDriver] WinAppDriver changed state to 'stopped'
[WinAppDriver] [STDOUT] SessionManager - Creating session
[WinAppDriver] [STDOUT] SessionManager - WinAppDriver succeeded loading MitaBroker
[WinAppDriver] [STDOUT] HTTP/1.1 500 Internal Error
[WinAppDriver] [STDOUT] Content-Length: 133
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[WinAppDriver] Deleting WinAppDriver session
[MJSONWP] Encountered internal error running command:  {"jsonwp":{"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}} ProxyRequestError: Could not proxy command to remote server. Original error: 500 - {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
    at JWProxy.proxy$ (C:\Users\mkhan2\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:153:13)
    at tryCatch (C:\Users\mkhan2\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\mkhan2\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\mkhan2\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\mkhan2\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 3101 ms - 152

**Comment by nmane047** [comment]
I am encountering the  same issue.

Windows Application driver: 0.5 beta, Appium version:1.6.0

If I upgrade to latest Windows application driver v1.0, the following error is thrown "Error: Could not verify WinAppDriver install; re-run install"

Below are the logs with Windows Application driver: 0.5 beta,

[Appium] Welcome to Appium v1.6.0
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"Windows","deviceName":"This PC","browserName":"","app":"C:/Users/SaNagaraj/Downloads/npp.7.5.1.Installer.EXE","count":1}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"Windows",...
[Appium] Creating new WindowsDriver session
[Appium] Capabilities:
[Appium]   platformName: 'Windows'
[Appium]   deviceName: 'This PC'
[Appium]   browserName: ''
[Appium]   app: 'C:/Users/SaNagaraj/Downloads/npp.7.5.1.Installer.EXE'
[Appium]   count: 1
[BaseDriver] The following capabilities were provided, but are not recognized by appium: browserName, app, count.
[BaseDriver] Session created with session id: b7f42119-f375-4c90-94d2-c3790e6f59a3
[WinAppDriver] Verifying WinAppDriver is installed with correct checksum
[debug] [WinAppDriver] WinAppDriver changed state to 'starting'
[WinAppDriver] Killing any old WinAppDrivers, running: FOR /F "usebackq tokens=5" %a in (`netstat -nao ^| findstr /R /C:"4823 "`) do (FOR /F "usebackq" %b in (`TASKLIST /FI "PID eq %a" ^| findstr /I winappdriver.exe`) do (IF NOT %b=="" TASKKILL /F /PID %a))
[WinAppDriver] No old WinAppDrivers seemed to exist
[WinAppDriver] Spawning winappdriver with: undefined 4823/wd/hub
[WinAppDriver] [STDOUT] Windows Application Driver Beta listening for requests at: http://127.0.0.1:4823/wd/hub
[debug] [WinAppDriver] WinAppDriver changed state to 'online'
[JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:4823/wd/hub/session] with body: {"desiredCapabilities":{"pl...
[WinAppDriver] [STDOUT] Press ENTER to exit.
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT] ==========================================
[WinAppDriver] [STDOUT] POST /wd/hub/session HTTP/1.1
[WinAppDriver] [STDOUT] Accept: */*
[WinAppDriver] [STDOUT] Connection: keep-alive
[WinAppDriver] [STDOUT] Content-Length: 161
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] Host: 127.0.0.1:4823
[WinAppDriver] [STDOUT] User-Agent: appium
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT] {"desiredCapabilities":{"platformName":"Windows","deviceName":"This PC","browserName":"","app":"C:/Users/SaNagaraj/Downloads/npp.7.5.1.Installer.EXE","count":1}}
[WinAppDriver] [STDOUT] SessionManager - Creating session
[WinAppDriver] [STDOUT] SessionManager - WinAppDriver succeeded loading MitaBroker
[WinAppDriver] [STDOUT] HTTP/1.1 500 Internal Error
[WinAppDriver] [STDOUT] Content-Length: 133
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT] {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[debug] [WinAppDriver] Deleting WinAppDriver session
[MJSONWP] Encountered internal error running command:  {"jsonwp":{"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}} ProxyRequestError: Could not proxy command to remote server. Original error: 500 - {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
    at JWProxy.proxy$ (lib/jsonwp-proxy/proxy.js:122:13)
    at tryCatch (C:\Users\SaNagaraj\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\SaNagaraj\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\SaNagaraj\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\SaNagaraj\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 215 ms - 152

**Comment by jsingh-qualitrol** [comment]
@mdmamunkhan : I am also facing same issue.
Did your problem resolved now, if yes. Pls share the work around. 
Thanks in advance....
[WinAppDriver] [STDOUT] SessionManager - WinAppDriver succeeded loading MitaBroker
[WinAppDriver] [STDOUT] HTTP/1.1 500 Internal Error
[WinAppDriver] [STDOUT] Content-Length: 133
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[WinAppDriver] WinAppDriver exited unexpectedly with code 2147500037, signal null
[WinAppDriver] WinAppDriver changed state to 'stopped'
[WinAppDriver] Deleting WinAppDriver session
[MJSONWP] Encountered internal error running command:  {"jsonwp":{"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}} ProxyRequestError: Could not proxy command to remote server. Original error: 500 - {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
    at JWProxy.proxy$ (C:\Users\jsingh\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:152:13)
    at tryCatch (C:\Users\jsingh\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\jsingh\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-

**Comment by yodurr** [comment]
we'll track this request on the WinAppDriver issue board

**Comment by jsingh-qualitrol** [comment]
@yodurr : Pls help on above post

**Comment by 307440453gitgub** [comment]
@yodurr :Is there any new progress? If yes. Pls share the work around.Thanks a lot.

**Comment by yodurr** [comment]
We haven't made progress yet - focus of late was on Pen support.  I added a note to the issue on WinAppDriver that we should investigate for the 1.2 release.  Please join in the conversation on the WinAppDriver board.  Thanks.
