### ISSUE TITLE
ios device automation using appium giving me the error

### ISSUE THREAD

**Issue by garlapati99** [appium/appium#9330]
Hi, here are my capabilities which i set 

caps = new DesiredCapabilities();
			caps.setCapability("deviceName", prop.getProperty("deviceName"));
			caps.setCapability("udid", prop.getProperty("udid"));
			caps.setCapability("platformName", prop.getProperty("platformName"));
			caps.setCapability("noReset", "true");
			File file = new File("/Users/shabeen/Documents/RequiredJars/Test.app");
			System.out.println(file.getAbsolutePath());
			caps.setCapability("automationName", "XCUITest");
			caps.setCapability("app", file.getAbsolutePath());
			caps.setCapability("autoGrantPermissions", "true");
			caps.setCapability("autoLaunch", true);
			//IOSDriver<WebElement> driver2 = new IOSDriver<>(caps);
			driver = new IOSDriver<WebElement>(new URL("http://127.0.0.1:4725/wd/hub"), caps);

When i run this as TestNG run i am getting the below error though the carthage is installed on my mac

[XCUITest] Error: Carthage not found. Install using `brew install carthage`
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at checkForDependencies$ (../../../lib/wda/utils.js:59:9)
    at tryCatch (/Users/shabeen/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/shabeen/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/shabeen/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/shabeen/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
 Error: Carthage not found. Install using `brew install carthage`
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at checkForDependencies$ (../../../lib/wda/utils.js:59:9)
    at tryCatch (/Users/shabeen/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/shabeen/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/shabeen/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/shabeen/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
[XCUITest] Error: Carthage not found. Install using `brew install carthage`
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at checkForDependencies$ (../../../lib/wda/utils.js:59:9)
    at tryCatch (/Users/shabeen/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/shabeen/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/shabeen/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/shabeen/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
 Error: Carthage not found. Install using `brew install carthage`
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at checkForDependencies$ (../../../lib/wda/utils.js:59:9)
    at tryCatch (/Users/shabeen/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/shabeen/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/shabeen/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/shabeen/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: "Carthage not found. Install using `brew install carthage`".
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:381:13)
    at tryCatch (/Users/shabeen/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/shabeen/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/shabeen/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/shabeen/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 Error: Unable to launch WebDriverAgent because of xcodebuild failure: "Carthage not found. Install using `brew install carthage`".
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:381:13)
    at tryCatch (/Users/shabeen/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/shabeen/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/shabeen/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/shabeen/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: "Carthage not found. Install using `brew install carthage`".
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:381:13)
    at tryCatch (/Users/shabeen/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/shabeen/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/shabeen/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/shabeen/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by garlapati99** [comment]
Not able to get the answer from 9265 ticket. Can someone address this here please
