### ISSUE TITLE
Screenshot not working after updating to 1.7.1

### ISSUE THREAD

**Issue by Icaroto** [appium/appium#9369]
Hello,

I've updated my Appium to latest (from 1.6.5 to 1.7.1) and it started to get an error when taking screenshots.

The log:

```
[debug] [MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["de68bf57-ce19-4368-af15-8ad2b2ae063a"]
[debug] [ADB] Device API level: 23
[AndroidDriver] Cannot get screenshot data with 'adb exec-out' because of 'The size of the taken screenshot equals to zero.'. Defaulting to 'adb shell' call
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/itorres/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","0d39350714089afa","shell","/system/bin/rm","/sdcard/screenshots/screenshot.png;","/system/bin/screencap","-p","/sdcard/screenshots/screenshot.png"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/itorres/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","0d39350714089afa","shell","ls","-la","/sdcard/screenshots/screenshot.png"]
[ADB] Error: Unable to get file size for '/sdcard/screenshots/screenshot.png': Remote path is not a file
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at ADB.callee$0$0$ (../../../lib/tools/system-calls.js:872:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 Error: Unable to get file size for '/sdcard/screenshots/screenshot.png': Remote path is not a file
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at ADB.callee$0$0$ (../../../lib/tools/system-calls.js:872:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:109:7)
[AndroidDriver] Error: Cannot get screenshot data because of 'Unable to get file size for '/sdcard/screenshots/screenshot.png': Remote path is not a file'
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at AndroidDriver.callee$0$0$ (../../../lib/commands/actions.js:278:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: Cannot get screenshot data because of 'Unable to get file size for '/sdcard/screenshots/screenshot.png': Remote path is not a file'
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at AndroidDriver.callee$0$0$ (../../../lib/commands/actions.js:278:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[MJSONWP] Encountered internal error running command: Error: Cannot get screenshot data because of 'Unable to get file size for '/sdcard/screenshots/screenshot.png': Remote path is not a file'
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at AndroidDriver.callee$0$0$ (../../../lib/commands/actions.js:278:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
```

I saw in the release notes that some screenshots fixes were made but couldn't find out what exactly. Do I need to update something in my code?

I'm using Appium Driver nuget package on a Visual Studio for Mac

## Code To Reproduce Issue [ Good To Have ]
There are nothing much, essentially I was using the nativeWebScreenshot set to true when opening the app and calling the .getScreenshot() method;

**Comment by mykola-mokhnach** [comment]
1. Make sure you Android SDK and and dev tools are updated to the most recent version.
2. What is the terminal output for the `adb shell ls /sdcard/screenshots/` command?

**Comment by Icaroto** [comment]
Hi @mykola-mokhnach 

1. I've just Android SDK and error continues
2. In one of my many tries, I changed the screenshot path to that sdcard/screenshot which doesn't exist. I tried again with the default values:

```
[debug] [MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["18d36cec-ab4a-4c9d-aca1-8d6500480479"]
[debug] [ADB] Device API level: 23
[AndroidDriver] Cannot get screenshot data with 'adb exec-out' because of 'The size of the taken screenshot equals to zero.'. Defaulting to 'adb shell' call
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/itorres/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","0d39350714089afa","shell","/system/bin/rm","/data/local/tmp/screenshot.png;","/system/bin/screencap","-p","/data/local/tmp/screenshot.png"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/itorres/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","0d39350714089afa","shell","ls","-la","/data/local/tmp/screenshot.png"]
[AndroidDriver] Error: Cannot get screenshot data because of 'The size of the taken screenshot equals to zero.'
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at AndroidDriver.callee$0$0$ (../../../lib/commands/actions.js:278:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: Cannot get screenshot data because of 'The size of the taken screenshot equals to zero.'
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at AndroidDriver.callee$0$0$ (../../../lib/commands/actions.js:278:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[MJSONWP] Encountered internal error running command: Error: Cannot get screenshot data because of 'The size of the taken screenshot equals to zero.'
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at AndroidDriver.callee$0$0$ (../../../lib/commands/actions.js:278:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- GET /wd/hub/session/18d36cec-ab4a-4c9d-aca1-8d6500480479/screenshot 500 481 ms - 259
[HTTP] --> GET /wd/hub/session/18d36cec-ab4a-4c9d-aca1-8d6500480479/screenshot {}
[debug] [MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["18d36cec-ab4a-4c9d-aca1-8d6500480479"]
[debug] [ADB] Device API level: 23
[AndroidDriver] Cannot get screenshot data with 'adb exec-out' because of 'The size of the taken screenshot equals to zero.'. Defaulting to 'adb shell' call
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/itorres/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","0d39350714089afa","shell","/system/bin/rm","/data/local/tmp/screenshot.png;","/system/bin/screencap","-p","/data/local/tmp/screenshot.png"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/itorres/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","0d39350714089afa","shell","ls","-la","/data/local/tmp/screenshot.png"]
[AndroidDriver] Error: Cannot get screenshot data because of 'The size of the taken screenshot equals to zero.'
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at AndroidDriver.callee$0$0$ (../../../lib/commands/actions.js:278:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: Cannot get screenshot data because of 'The size of the taken screenshot equals to zero.'
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at AndroidDriver.callee$0$0$ (../../../lib/commands/actions.js:278:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[MJSONWP] Encountered internal error running command: Error: Cannot get screenshot data because of 'The size of the taken screenshot equals to zero.'
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at AndroidDriver.callee$0$0$ (../../../lib/commands/actions.js:278:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- GET /wd/hub/session/18d36cec-ab4a-4c9d-aca1-8d6500480479/screenshot 500 369 ms - 259
[HTTP] --> DELETE /wd/hub/session/18d36cec-ab4a-4c9d-aca1-8d6500480479 {}
[debug] [MJSONWP] Calling AppiumDriver.deleteSession() with args: ["18d36cec-ab4a-4c9d-aca1-8d6500480479"]
[debug] [BaseDriver] Event 'quitSessionRequested' logged at 1507054273954 (19:11:13 GMT+0100 (BST))
[Appium] Removing session 18d36cec-ab4a-4c9d-aca1-8d6500480479 from our master session list
```

By running adb shell as you requested I get: 
```
-rw-rw-rw- shell    shell    23711132 2017-10-03 14:47 5be5af5b38c2607cfab5f78ffea4c798.apk
-rw-rw-rw- shell    shell       50944 2017-09-13 15:17 AppiumBootstrap.jar
-rw-rw-rw- shell    shell      573209 2017-01-22 10:45 UIAutomator.jar
-rw-rw-rw- shell    shell         145 2017-10-02 16:47 chrome-command-line
drwxrwxrwx shell    shell             2016-07-19 14:39 dalvik-cache
-rw-rw-r-- shell    shell      254652 2017-10-03 16:38 fu.png
drwx------ shell    shell             2016-08-29 14:30 local
drwxrwxrwx shell    shell             2017-01-30 13:26 minicap-devel
-rw-rw-r-- shell    shell           0 2017-10-03 19:11 screenshot.png
-rw-rw-rw- shell    shell        8212 2017-10-03 19:10 strings.json
```

So it seems the screenshot is taken, but it does fail after. Any reasons?

**Comment by imurchie** [comment]
What happens if you run `adb shell /system/bin/rm /data/local/tmp/screenshot.png; /system/bin/screencap -p /data/local/tmp/screenshot.png`

**Comment by Icaroto** [comment]
@imurchie It generates a screenshot with size bigger than 0

```
shell@hammerhead:/ $ /system/bin/rm /data/local/tmp/screenshot.png;
shell@hammerhead:/ $ /system/bin/screencap -p /data/local/tmp/screenshot.png
shell@hammerhead:/ $ ls -la /data/local/tmp/
-rw-rw-rw- shell    shell    23711132 2017-10-03 14:47 5be5af5b38c2607cfab5f78ffea4c798.apk
-rw-rw-rw- shell    shell       50944 2017-09-13 15:17 AppiumBootstrap.jar
-rw-rw-rw- shell    shell      573209 2017-01-22 10:45 UIAutomator.jar
-rw-rw-rw- shell    shell         145 2017-10-02 16:47 chrome-command-line
drwxrwxrwx shell    shell             2016-07-19 14:39 dalvik-cache
-rw-rw-r-- shell    shell      254652 2017-10-03 16:38 fu.png
drwx------ shell    shell             2016-08-29 14:30 local
drwxrwxrwx shell    shell             2017-01-30 13:26 minicap-devel
-rw-rw-r-- shell    shell      297232 2017-10-03 19:29 screenshot.png
-rw-rw-rw- shell    shell        8212 2017-10-03 19:10 strings.json

```

**Comment by imurchie** [comment]
Alright. I'm going to have a little look. Can you post the desired capabilities for your failing test?

**Comment by mykola-mokhnach** [comment]
Are you sure the screenshoting is not disabled in the application under test? Are you able to take a screenshot on the device being on the same view where your automated test fails to take it?

**Comment by Icaroto** [comment]
So, while I was gathering the capabilities, I tried to open my application using the chrome browser (it's a hybrid app) to see if works. Using Chrome, I can take a screenshot and the test doesn't fail/crash! :)

Apart from app, appPackage and appActivity I use the following capabilities:
platformVersio = 6.0.1
deviceName = Nexus 5
recreateChromeDriverSessions = true
nativeWebScreenshot = true

Now, about the app, I do know that it has some "protection"  against screenshot, but only on the login page. When I open the app and manually try to take the screenshot (using the adb commands from the previous comments) I get this:

Login Screen: screenshot with size 0
After Login: screenshot with size larger than 0

So, somehow only when executing with appium (maybe the C# packages has a issue?) the "After Login" screenshot doesn't work.

**Comment by imurchie** [comment]
Thanks for the investigation. I'm adding a little better error handling. Hopefully we can track this down.

**Comment by Icaroto** [comment]
No worries, as I can't provide the app, please let me know if I can help getting more logs or any other tests :)

**Comment by imurchie** [comment]
Can you update Appium to 1.7.2-beta (`npm uninstall -g appium && npm install -g appium@beta`)? And try again. Hopefully we will get more information in the logs.

**Comment by Icaroto** [comment]
Hello @imurchie  thats the appium logs using the 1.7.2:

```
[HTTP] --> GET /wd/hub/session/db33b376-8104-4a0f-a041-6e51c277819c/screenshot {}
[debug] [MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["db33b376-8104-4a0f-a041-6e51c277819c"]
[debug] [ADB] Device API level: 23
[AndroidDriver] Cannot get screenshot data with 'adb exec-out' because of 'Screenshot returned no data'. Defaulting to 'adb shell' call
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/itorres/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","0d39350714089afa","shell","/system/bin/rm","/data/local/tmp/screenshot.png;","/system/bin/screencap","-p","/data/local/tmp/screenshot.png"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/itorres/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","0d39350714089afa","shell","ls","-la","/data/local/tmp/screenshot.png"]
[AndroidDriver] Error: Cannot get screenshot data because of 'The size of the taken screenshot equals to zero.'. Make sure the 'LayoutParams.FLAG_SECURE' is not set for the current view
    at Object.wrappedLogger.errorAndThrow (/usr/local/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:66:13)
    at AndroidDriver.callee$0$0$ (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/lib/commands/actions.js:289:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: Cannot get screenshot data because of 'The size of the taken screenshot equals to zero.'. Make sure the 'LayoutParams.FLAG_SECURE' is not set for the current view
    at Object.wrappedLogger.errorAndThrow (/usr/local/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:66:13)
    at AndroidDriver.callee$0$0$ (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/lib/commands/actions.js:289:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[MJSONWP] Encountered internal error running command: Error: Cannot get screenshot data because of 'The size of the taken screenshot equals to zero.'. Make sure the 'LayoutParams.FLAG_SECURE' is not set for the current view
    at Object.wrappedLogger.errorAndThrow (/usr/local/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:66:13)
    at AndroidDriver.callee$0$0$ (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/lib/commands/actions.js:289:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- GET /wd/hub/session/db33b376-8104-4a0f-a041-6e51c277819c/screenshot 500 546 ms - 333
```

Regarding LayoutParams.FLAG_SECURE, considering that manually using adb I CAN take a proper screenshot, does it still can be the case of this flag be impacting?

**Comment by imurchie** [comment]
Yeah, that message was added to _all_ failures, since it is often the problem. In your case it shouldn't be the problem. But my hopes of `adb` giving some indication of why it is failing are dashed. :(

Back to the drawing board in terms of trying to figure out what the problem might be.

**Comment by xuanzhaopeng** [comment]
Just provide more information in 1.7.1
Original error: Cannot get screenshot data because of 'Error executing adbExec. Original error: 'Command '/root/platform-tools/adb -P 5038 -s 12160c5d01cf1903 pull /data/local/tmp/screenshot.png /tmp/appium117912-70-1h1x9uh.6hsyk3xr.png' timed out after 60000ms'; Stderr: 'adb I 10-12 08:32:10   622   622 adb_trace.cpp:178] Android Debug Bridge version 1.0.39
adb I 10-12 08:32:10   622   622 adb_trace.cpp:178] Revision 3db08f2c6889-android
adb I 10-12 08:32:10   622   622 adb_trace.cpp:178] Installed as /root/platform-tools/adb
adb I 10-12 08:32:10   622   622 adb_trace.cpp:178] 
adb I 10-12 08:32:10   622   622 adb_client.cpp:271] adb_query: host-serial:12160c5d01cf1903:features
adb I 10-12 08:32:10   622   622 adb_client.cpp:124] _adb_connect: host:version
adb I 10-12 08:32:10   622   622 adb_io.cpp:101] writex: fd=3 len=16 30303063686f73743a76657273696f6e 000chost:version
adb I 10-12 08:32:10   622   622 adb_io.cpp:75] readx: fd=3 wanted=4
adb I 10-12 08:32:10   622   622 adb_io.cpp:91] readx: fd=3 wanted=4 got=4 4f4b4159 OKAY
adb I 10-12 08:32:10   622   622 adb_client.cpp:157] _adb_connect: return fd 3
adb I 10-12 08:32:10   622   622 adb_client.cpp:165] adb_connect: service host-serial:12160c5d01cf1903:features
adb I 10-12 08:32:10   622   622 adb_io.cpp:75] readx: fd=3 wanted=4
adb I 10-12 08:32:10   622   622 adb_io.cpp:91] readx: fd=3 wanted=4 got=4 30303034 0004
adb I 10-12 08:32:10   622   622 adb_io.cpp:75] readx: fd=3 wanted=4
adb I 10-12 08:32:10   622   622 adb_io.cpp:91] readx: fd=3 wanted=4 got=4 30303237 0027
adb I 10-12 08:32:10   622   622 adb_client.cpp:124] _adb_connect: host-serial:12160c5d01cf1903:features
adb I 10-12 08:32:10   622   622 adb_io.cpp:101] writex: fd=3 len=41 30303235686f73742d73657269616c3a 0025host-serial:
adb I 10-12 08:32:10   622   622 adb_io.cpp:75] readx: fd=3 wanted=4
adb I 10-12 08:32:10   622   622 adb_io.cpp:91] readx: fd=3 wanted=4 got=4 4f4b4159 OKAY
adb I 10-12 08:32:10   622   622 adb_client.cpp:157] _adb_connect: return fd 3
adb I 10-12 08:32:10   622   622 adb_client.cpp:245] adb_connect: return fd 3
adb I 10-12 08:32:10   622   622 adb_io.cpp:75] readx: fd=3 wanted=4
adb I 10-12 08:32:10   622   622 adb_io.cpp:91] readx: fd=3 wanted=4 got=4 30303030 0000
adb I 10-12 08:32:10   622   622 adb_io.cpp:75] readx: fd=3 wanted=0
adb I 10-12 08:32:10   622   622 adb_io.cpp:91] readx: fd=3 wanted=0 got=0  
adb I 10-12 08:32:10   622   622 adb_client.cpp:124] _adb_connect: host:version
adb I 10-12 08:32:10   622   622 adb_io.cpp:101] writex: fd=3 len=16 30303063686f73743a76657273696f6e 000chost:version
adb I 10-12 08:32:10   622   622 adb_io.cpp:75] readx: fd=3 wanted=4
adb I 10-12 08:32:10   622   622 adb_io.cpp:91] readx: fd=3 wanted=4 got=4 4f4b4159 OKAY
adb I 10-12 08:32:10   622   622 adb_client.cpp:157] _adb_connect: return fd 3
adb I 10-12 08:32:10   622   622 adb_client.cpp:165] adb_connect: service sync:
adb I 10-12 08:32:10   622   622 adb_io.cpp:75] readx: fd=3 wanted=4
adb I 10-12 08:32:10   622   622 adb_io.cpp:91] readx: fd=3 wanted=4 got=4 30303034 0004
adb I 10-12 08:32:10   622   622 adb_io.cpp:75] readx: fd=3 wanted=4
adb I 10-12 08:32:10   622   622 adb_io.cpp:91] readx: fd=3 wanted=4 got=4 30303237 0027
adb I 10-12 08:32:10   622   622 adb_client.cpp:124] _adb_connect: sync:
adb I 10-12 08:32:10   622   622 adb_io.cpp:101] writex: fd=3 len=35 30303166686f73743a7472616e73706f 001fhost:transpo
adb I 10-12 08:32:10   622   622 adb_client.cpp:91] Switch transport in progress
adb I 10-12 08:32:10   622   622 adb_io.cpp:75] readx: fd=3 wanted=4
adb I 10-12 08:32:10   622   622 adb_io.cpp:91] readx: fd=3 wanted=4 got=4 4f4b4159 OKAY
adb I 10-12 08:32:10   622   622 adb_client.cpp:98] Switch transport success
adb I 10-12 08:32:10   622   622 adb_io.cpp:101] writex: fd=3 len=9 3030303573796e633a 0005sync:
adb I 10-12 08:32:10   622   622 adb_io.cpp:75] readx: fd=3 wanted=4'; Code: 'null''. Make sure the 'LayoutParams.FLAG_SECURE' is not set for the current view

**Comment by Icaroto** [comment]
@imurchie  
Is there a chance of the bug being on AppiumDriver C# package? Since I can manually take the screenshot using adb and appium is not providing any helpful error message. 
Maybe the command through the C# package is failing and the package is "clouding" the error? 
(Unless that's not possible :P)

**Comment by mykola-mokhnach** [comment]
I assume we cannot do more on this from Appium side.
