### ISSUE TITLE
"Get Element Rect" is not implemented for android, but docs says it is

### ISSUE THREAD

**Issue by rseek** [appium/appium#9386]
## The problem
I try to use `element.getRect();` java method as described here:
http://appium.readthedocs.io/en/latest/en/commands/element/attributes/rect/
but I get` org.openqa.selenium.WebDriverException: Method has not yet been implemented` Error

## Environment

* Appium version (or git revision) that exhibits the issue:
Appium 1.7.1
Appium-java-client 5.0.4
* Mobile platform/version under test:
Android 6.0
* Real device or emulator/simulator:
emulator

## Appium logs

```
[HTTP] --> GET /wd/hub/session/dd82aa99-d602-48c1-a155-93caee7efd55/element/22/rect {}
[debug] [MJSONWP] Calling AppiumDriver.getElementRect() with args: ["22","dd82aa99-d602-48c1-a155-93caee7efd55"]
[HTTP] <-- GET /wd/hub/session/dd82aa99-d602-48c1-a155-93caee7efd55/element/22/rect 501 6 ms - 122 
```

**Comment by mykola-mokhnach** [comment]
Please attach the full server log

**Comment by vzhura-grids** [comment]
Have same issue.
Server log snippet
```
[HTTP] --> POST /wd/hub/session/906c4b33-995c-44fb-86f6-1e46def0b84b/elements {"using":"-android uiautomator","value":"new UiSelector().resourceId(\"com.slava.buylist:id/ambilwarna_warnaLama\")"}
[debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["-android uiautomator","new UiSelector().resourceId(\”…\”)”,”906c4b33-995c-44fb-86f6-1e46def0b84b"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"-android uiautomator","selector":"new UiSelector().resourceId(\"com.slava.buylist:id/ambilwarna_warnaLama\")","context":"","multiple":true}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"-android uiautomator","selector":"new UiSelector().resourceId(\"com.slava.buylist:id/ambilwarna_warnaLama\")","context":"","multiple":true}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding 'new UiSelector().resourceId("com.slava.buylist:id/ambilwarna_warnaLama")' using 'ANDROID_UIAUTOMATOR' with the contextId: '' multiple: true
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Parsing selector: new UiSelector().resourceId("com.slava.buylist:id/ambilwarna_warnaLama")
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] UiSelector coerce type: class java.lang.String arg: "com.slava.buylist:id/ambilwarna_warnaLama"
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[RESOURCE_ID=com.slava.buylist:id/ambilwarna_warnaLama]
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements selector:UiSelector[RESOURCE_ID=com.slava.buylist:id/ambilwarna_warnaLama]
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Element[] is null: (0)
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements tmp selector:UiSelector[INSTANCE=0, RESOURCE_ID=com.slava.buylist:id/ambilwarna_warnaLama]
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Element[] is null: (1)
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements tmp selector:UiSelector[INSTANCE=1, RESOURCE_ID=com.slava.buylist:id/ambilwarna_warnaLama]
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":[{"ELEMENT":"53"}]}
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [MJSONWP] Responding to client with driver.findElements() result: [{"ELEMENT":"53"}]
[HTTP] <-- POST /wd/hub/session/906c4b33-995c-44fb-86f6-1e46def0b84b/elements 200 18 ms - 90 
[HTTP] --> POST /wd/hub/session/906c4b33-995c-44fb-86f6-1e46def0b84b/timeouts {"type":"implicit","ms":1000}
[debug] [MJSONWP] Calling AppiumDriver.timeouts() with args: ["implicit",1000,"906c4b33-995c-44fb-86f6-1e46def0b84b"]
[debug] [BaseDriver] Set implicit wait to 1000ms
[debug] [MJSONWP] Responding to client with driver.timeouts() result: null
[HTTP] <-- POST /wd/hub/session/906c4b33-995c-44fb-86f6-1e46def0b84b/timeouts 200 1 ms - 76 
[HTTP] --> GET /wd/hub/session/906c4b33-995c-44fb-86f6-1e46def0b84b/element/53/rect {}
[debug] [MJSONWP] Calling AppiumDriver.getElementRect() with args: ["53","906c4b33-995c-44fb-86f6-1e46def0b84b"]
[HTTP] <-- GET /wd/hub/session/906c4b33-995c-44fb-86f6-1e46def0b84b/element/53/rect 501 15 ms - 122 
[HTTP] --> DELETE /wd/hub/session/906c4b33-995c-44fb-86f6-1e46def0b84b {}
```

Java stack trace
```
org.openqa.selenium.WebDriverException: Method has not yet been implemented (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T15:28:36.4Z'
System info: host: '*.local', ip: '*', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_144'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{app=....apk, appPackage=..., deviceScreenSize=1080x1920, networkConnectionEnabled=true, warnings={}, appWaitPackage=..., appWaitActivity=..., databaseEnabled=false, deviceName=emulator-5554, platform=LINUX, deviceUDID=emulator-5554, appActivity=com.slava.buylist.MainActivity, desired={app=..., unicodeKeyboard=true, platformName=Android, deviceName=emulator1}, platformVersion=7.1.1, webStorageEnabled=false, locationContextEnabled=false, takesScreenshot=true, javascriptEnabled=true, deviceModel=Android SDK built for x86, unicodeKeyboard=true, deviceManufacturer=Google, platformName=LINUX}]
Session ID: 324823fe-92dc-4731-afa4-a045b3d50766
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:82)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:45)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:89)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:586)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:279)
	at io.appium.java_client.DefaultGenericMobileElement.execute(DefaultGenericMobileElement.java:45)
	at io.appium.java_client.MobileElement.execute(MobileElement.java:1)
	at io.appium.java_client.android.AndroidElement.execute(AndroidElement.java:1)
	at org.openqa.selenium.remote.RemoteWebElement.getRect(RemoteWebElement.java:348)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.appium.java_client.pagefactory.ElementInterceptor.getObject(ElementInterceptor.java:40)
	at io.appium.java_client.pagefactory.interceptors.InterceptorOfASingleElement.intercept(InterceptorOfASingleElement.java:62)
	at io.appium.java_client.android.AndroidElement$$EnhancerByCGLIB$$b598166c.getRect(<generated>)
	at 
```

**Comment by mykola-mokhnach** [comment]
The fix has been merged to beta
