### ISSUE TITLE
Appium 1.7.1 - iOS: Timed out after waiting 1.0s for KeyEventCompleted after sending event for ...

### ISSUE THREAD

**Issue by cosminstirbu** [appium/appium#9395]
## The problem

We have a large suite of tests that run in parallel over night.
At some point several tests start to fail due to the error below. In the screenshots that we're making when the tests fail we're seeing in the textfield we're typing 'mm' instead so it seems that two 'm' were introduced when the test failed.

We're using connectHardwareKeyboard=false and also I've disabled Screen Saver on our build, since I've read that this might be a cause as well.

We're not sure what is causing this :-?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): :-?
* Desktop OS/version used to run Appium: macOS 10.12.6
* Node.js version (unless using Appium.app|exe): v7.0.0
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: iOS 10 and iOS 11 Simulator
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

```
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error Domain=XCTDaemonErrorDomain Code=14 "Timed out after waiting 1.0s for KeyEventCompleted after sending event for 'm'." UserInfo={NSLocalizedDescription=Timed out after waiting 1.0s for KeyEventCompleted after sending event for 'm'.} (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 3.75 seconds
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'osxbuildserver.internal.mywebgrocer.com', ip: '10.0.40.9', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_91'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{app=/Users/jenkins/.jenkins/jobs/MyApp/jobs/MPS_AQA/jobs/iOS_Parallel/workspace/iOS/build-simulator/MyApp.app, networkConnectionEnabled=false, clearSystemFiles=true, databaseEnabled=false, connectHardwareKeyboard=false, deviceName=iPhone 5s, platform=MAC, wdaLocalPort=6789, newCommandTimeout=300, platformVersion=11.0, webStorageEnabled=false, locationContextEnabled=false, automationName=XCUITest, browserName=, takesScreenshot=true, javascriptEnabled=true, platformName=iOS, udid=936C7D51-F6C3-41D3-B80B-5411C92491DE}]
Session ID: e481bd46-0eb7-4715-acc3-8d8061f3cb4f
	at sun.reflect.GeneratedConstructorAccessor136.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:40)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:327)
	at io.appium.java_client.DefaultGenericMobileElement.execute(DefaultGenericMobileElement.java:33)
	at io.appium.java_client.MobileElement.execute(MobileElement.java:1)
	at io.appium.java_client.ios.IOSElement.execute(IOSElement.java:1)
	at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:122)
	at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.appium.java_client.pagefactory.ElementInterceptor.getObject(ElementInterceptor.java:39)
	at io.appium.java_client.pagefactory.interceptors.InterceptorOfASingleElement.intercept(InterceptorOfASingleElement.java:58)
	at io.appium.java_client.ios.IOSElement$$EnhancerByCGLIB$$184e91dc.sendKeys(<generated>)
	at pages.SignInPage.setUsername(SignInPage.java:44)
	at glue.steps.SignInSteps.I_sign_in(SignInSteps.java:20)
	at ✽.And I sign in(/Users/jenkins/.jenkins/jobs/MyApp/jobs/AQA/jobs/iOS_Parallel/workspace/src/test/resources/features/feature1/SomeFeature.feature:7)
```

**Comment by mykola-mokhnach** [comment]
You can try to play with _maxTypingFrequency_/_nativeTyping_ capabilities, but this all happens on WebDriverAgent side, so we cannot change anything there.

**Comment by cosminstirbu** [comment]
I've set _maxTypingFrequency_ to 30 and it still didn't solve the issue.

I've Googled _nativeTyping_ capability but I couldn't find it anywhere, not sure what this does and where it is documented.

The interesting piece is that this occurs after approx. 4-5 hrs of running. I managed to catch it, I did play with the simulator while the tests were running, tried to toggle different keyboard options, but it still didn't solve the issue.

I've killed the simulators while the tests where running, and my tests reopened the simulators automatically. However this is not an option in the long run, or an option that I can automate, since in my Cucumber hooks I can't catch the exception that the test failed with (this is a Cucumber JVM limitation).

I've changed my signIn method to something like this:

```
    public void signIn(String username, String password) {
        usernameFieldElement.click();
        usernameFieldElement.clear();
        usernameFieldElement.setValue(username);

        passwordFieldElement.click();
        passwordFieldElement.clear();
        passwordFieldElement.setValue(password);

        signInButtonElement.click();
    }
```
Previously I was using `sendKeys()`.

Tonight the tests will re-run and I'll see if it makes any difference.

**Comment by cosminstirbu** [comment]
The issue still reproduces :(.

I'll add a static variable in my tests to monitor the time passed since the tests start, and restart the simulator after approx 3hrs. That should fix the issue according to my comment above where I've manually killed the simulator and the issue didn't reproduce any longer.

**Comment by cosminstirbu** [comment]
Setting `fullReset` for every 2 hrs before starting the next Cucumber scenario solved my keyboard issue.

Still can't tell if it's an Appium relates issue or an Xcode 9.

**Comment by mykola-mokhnach** [comment]
This must be a Simulator issue.

**Comment by alangithubtrader** [comment]
I am experiencing this when i run my overnight regression test on iOS 11 iPhone 6 with Appium 1.7.1 on a device.

**Comment by derunewige** [comment]
I have the same issue on a real device (iPhone 6s) with iOS10 and iOS11.

I try to enter a quite long string and it always just types two letters.  
{"value":["r","v","p","4","q","5","u","e","b","7","s","o","2","q","7","d","k","f","2","h","f","d","7","m","1","i","@","m","a","i","l","i","n","a","t","o","r",".","c","o","m"]}

It occurs after running for about 2-3hours and can only be fixed by restarting the device

**Comment by ajeeshvl** [comment]
Experiencing same issue on iPhone and iPad devices for long run tests.
