### ISSUE TITLE
[AndroidDriver] Not cleaning generated files. Add `clearSystemFiles` capability if wanted. [MJSONWP] Encountered internal error running command: Error: Error occured while starting App. Original error: 'StartScreenActivity' never started

### ISSUE THREAD

**Issue by showtime25st** [appium/appium#9436]
[appium-server-logs.txt](https://github.com/appium/appium/files/1378301/appium-server-logs.txt)
## The problem

trying to start inspector session

## Environment

* Appium version - appium-desktop-Setup-1.2.3.exe
* Desktop OS/version used to run Appium - win 10
* Node.js version - node-v6.11.4-x64
* Mobile platform/version under test - Android 8.0
* Real device or emulator/simulator - emulator Nexus 5X
*  Appium.app|exe

## Details

Once i managed to run inspector session, 

## Link to Appium logs
[AndroidDriver] Not cleaning generated files. Add `clearSystemFiles` capability if wanted.
MJSONWP] Encountered internal error running command: Error: Error occured while starting App. Original error: 'StartScreenActivity' never started
    at Object.wrappedLogger.errorAndThrow (C:\Users\Step\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:63:13)
    at ADB.callee$0$0$ (C:\Users\Step\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\apk-utils.js:101:9)
    at tryCatch (C:\Users\Step\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\Step\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\Step\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\Step\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)

## Code To Reproduce Issue [ Good To Have ]

{
  "platformName": "Android",
  "platformVersion": "8.0",
  "deviceName": "Nexus 5X API 26",
  "app": "D:\\app\\app-8.33-k1.apk",
  "autoGrantPermissions": true,
  "appWaitActivity": "StartScreenActivity"
}

**Comment by saikrishna321** [comment]
Pls provide complete server logs

**Comment by showtime25st** [comment]
saikrishna321, Thank you!

Done)

**Comment by mykola-mokhnach** [comment]
You must provide correct values to appActivity/appWaitActivity capabilities.

**Comment by showtime25st** [comment]
mykola-mokhnach  thank you!
appWaitActivity = "com.app.mobilebanking.android.gui.activity.StartScreenActivity" this helped! It didn't work without package.

**Comment by saikrishna321** [comment]
closing as issue resolved
