### ISSUE TITLE
[XCUITest] *** Checking out RoutingHTTPServer at "v1.0.1"

### ISSUE THREAD

**Issue by sagarsheth27** [appium/appium#9445]
dc.setCapability("automationName", "XCUITest");
        dc.setCapability("reportDirectory", reportDirectory);
        dc.setCapability("reportFormat", reportFormat);
        dc.setCapability("testName", testName);
        //dc.setCapability("appium-version","1.7.1");
        dc.setCapability("deviceName","Qa");
        dc.setCapability("platformName", "ios");
        dc.setCapability("version","9.3.1");
        //9.3.1
        // iPhone 7 = f172ad34e324e431749f19dbcc4fd8e9f9c75b34
        // iPhone 6S  = ae2ebecd7878587c83f7551dbff4acf1a376e660
        // iPhone 5 = a551a5ab21bfdd80b721e72a0ac376ef7c0d67cf
        // iPhone 6+ = 3835b88d9e35a00043f5ea066cb83634d286605c
        // iPhone 6 = c9021b8d2cd9f2e85a99d35195958b5e45727656
        // iPhone SE = c9021b8d2cd9f2e85a99d35195958b5e45727656
        //dc.setCapability("app","/Users/mccuser/Library/Developer/Xcode/DerivedData/xxxxx-bqmwfyhpopbqpvbqxldvaubnwdbj/Build/Products/Debug-iphoneos/xxxxxx.app");
        dc.setCapability(MobileCapabilityType.UDID, "3835b88d9e35a00043f5ea066cb83634d286605c");
        //dc.setCapability(MobileCapabilityType.UDID,  "f172ad34e324e431749f19dbcc4fd8e9f9c75b34");
        dc.setCapability(IOSMobileCapabilityType.BUNDLE_ID, "com.streebo.pscu.mobile");
        driver = new IOSDriver<IOSElement>(new URL("http://127.0.0.1:4040/wd/hub"), dc);
        //driver = new RemoteWebDriver(new URL("http://192.168.4.52:4444/wd/hub"), dc);
        driver.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS);

Server log as below:

[info] [Appium] Welcome to Appium v1.7.1
[info] [Appium] Non-default server args:
[info] [Appium]   address: 127.0.0.1
[info] [Appium]   port: 4040
[info] [Appium] Appium REST http interface listener started on 127.0.0.1:4040[info] [HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"automationName":"XCUITest","bundleId":"xxxxxxxx","reportDirectory":"reports","reportFormat":"xml","platformName":"iOS","udid":"3835b88d9e35a00043f5ea066cb83634d286605c","deviceName":"Qa","version":"9.3.1","testName":"PSCU_Automized_Testing"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"automationName":"XCUITest","bundleId":"xxxxxxxx","reportDirectory":"reports","reportFormat":"xml","platformName":"iOS","udid":"3835b88d9e35a00043f5ea066cb83634d286605c","deviceName":"Qa","version":"9.3.1","testName":"PSCU_Automized_Testing"},null,null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1507812462227 (18:17:42 GMT+0530 (IST))
[info] [Appium] Creating new XCUITestDriver (v2.51.1) session
[info] [Appium] Capabilities:
[info] [Appium]   automationName: 'XCUITest'
[info] [Appium]   bundleId: 'xxxxxxxx'
[info] [Appium]   reportDirectory: 'reports'
[info] [Appium]   reportFormat: 'xml'
[info] [Appium]   platformName: 'iOS'
[info] [Appium]   udid: '3835b88d9e35a00043f5ea066cb83634d286605c'
[info] [Appium]   deviceName: 'Qa'
[info] [Appium]   version: '9.3.1'
[info] [Appium]   testName: 'PSCU_Automized_Testing'
[warn] [BaseDriver] The following capabilities were provided, but are not recognized by appium: reportDirectory, reportFormat, version, testName.
[info] [BaseDriver] Session created with session id: 97f18975-8bd7-407e-a927-253c539425a4
[debug] [XCUITest] Xcode version set to '8.3.3' (tools v8.3.2.0.1.1492020469)
[debug] [XCUITest] iOS SDK Version set to '10.3'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1507812462273 (18:17:42 GMT+0530 (IST))
[debug] [XCUITest] Available devices: 3835b88d9e35a00043f5ea066cb83634d286605c
[debug] [XCUITest] Creating iDevice object with udid '3835b88d9e35a00043f5ea066cb83634d286605c'
[info] [XCUITest] Determining device to run tests on: udid: '3835b88d9e35a00043f5ea066cb83634d286605c', real device: true
[debug] [BaseDriver] Event 'appConfigured' logged at 1507812462380 (18:17:42 GMT+0530 (IST))
[debug] [BaseDriver] Event 'resetStarted' logged at 1507812462380 (18:17:42 GMT+0530 (IST))
[debug] [XCUITest] Reset: running ios real device reset flow
[debug] [BaseDriver] Event 'resetComplete' logged at 1507812462382 (18:17:42 GMT+0530 (IST))
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Starting iOS device log capture with: 'idevicesyslog'[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1507812463014 (18:17:43 GMT+0530 (IST))
[info] [XCUITest] Setting up real device[info] [XCUITest] Using WDA path: '/private/var/folders/2g/_188v_x17s373h59lf73hxl80000gp/T/AppTranslocation/D4A11C80-D987-47AE-8C33-2ADA9C131BE9/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[info] [XCUITest] Using WDA agent: '/private/var/folders/2g/_188v_x17s373h59lf73hxl80000gp/T/AppTranslocation/D4A11C80-D987-47AE-8C33-2ADA9C131BE9/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[debug] [XCUITest] Capability 'useNewWDA' set to false, so trying to reuse currently running WDA instance at 'http://localhost:8100/'
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[warn] [JSONWP Proxy] Got unexpected response: Cannot GET /status

[debug] [XCUITest] WDA is not listening at 'http://localhost:8100/'. Rebuilding...
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1507812463344 (18:17:43 GMT+0530 (IST))
[info] [XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Running WebDriverAgent bootstrap script to install dependencies[error] [XCUITest] [1mFetching dependencies
[error] [XCUITest] *** Downloading RoutingHTTPServer.framework binary at "v1.0.1"
[error] [XCUITest] *** Skipped installing RoutingHTTPServer.framework binary due to the error:
[error] [XCUITest] 	"Failed to write to /private/var/folders/2g/_188v_x17s373h59lf73hxl80000gp/T/AppTranslocation/D4A11C80-D987-47AE-8C33-2ADA9C131BE9/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/iOS: Error Domain=NSCocoaErrorDomain Code=642 "You can’t save the file “iOS” because the volume is read only." UserInfo={NSFilePath=/private/var/folders/2g/_188v_x17s373h59lf73hxl80000gp/T/AppTranslocation/D4A11C80-D987-47AE-8C33-2ADA9C131BE9/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/iOS, NSUnderlyingError=0x7f90c6541ea0 {Error Domain=NSPOSIXErrorDomain Code=30 "Read-only file system"}}"
[error] [XCUITest] *** Checking out RoutingHTTPServer at "v1.0.1"
[error] [XCUITest] Failed to check out repository into /private/var/folders/2g/_188v_x17s373h59lf73hxl80000gp/T/AppTranslocation/D4A11C80-D987-47AE-8C33-2ADA9C131BE9/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/RoutingHTTPServer: Could not create working directory (Error Domain=NSCocoaErrorDomain Code=642 "You can’t save the file “RoutingHTTPServer” because the volume is read only." UserInfo={NSFilePath=/private/var/folders/2g/_188v_x17s373h59lf73hxl80000gp/T/AppTranslocation/D4A11C80-D987-47AE-8C33-2ADA9C131BE9/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/RoutingHTTPServer, NSUnderlyingError=0x7f90c66483b0 {Error Domain=NSPOSIXErrorDomain Code=30 "Read-only file system"}})
[debug] [BaseDriver] Event 'wdaStartFailed' logged at 1507812466022 (18:17:46 GMT+0530 (IST))
[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: "Command 'Scripts/bootstrap.sh -d' exited with code 1". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
[debug] [XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[info] [XCUITest] Shutting down sub-processes
[debug] [XCUITest] Removing WDA application from device[error] [XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: "Command 'Scripts/bootstrap.sh -d' exited with code 1". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
    at XCUITestDriver.quitAndUninstall$ (/private/var/folders/2g/_188v_x17s373h59lf73hxl80000gp/T/AppTranslocation/D4A11C80-D987-47AE-8C33-2ADA9C131BE9/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:381:13)
    at tryCatch (/private/var/folders/2g/_188v_x17s373h59lf73hxl80000gp/T/AppTranslocation/D4A11C80-D987-47AE-8C33-2ADA9C131BE9/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/private/var/folders/2g/_188v_x17s373h59lf73hxl80000gp/T/AppTranslocation/D4A11C80-D987-47AE-8C33-2ADA9C131BE9/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/private/var/folders/2g/_188v_x17s373h59lf73hxl80000gp/T/AppTranslocation/D4A11C80-D987-47AE-8C33-2ADA9C131BE9/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/private/var/folders/2g/_188v_x17s373h59lf73hxl80000gp/T/AppTranslocation/D4A11C80-D987-47AE-8C33-2ADA9C131BE9/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: Unable to launch WebDriverAgent because of xcodebuild failure: "Command 'Scripts/bootstrap.sh -d' exited with code 1". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
    at XCUITestDriver.quitAndUninstall$ (/private/var/folders/2g/_188v_x17s373h59lf73hxl80000gp/T/AppTranslocation/D4A11C80-D987-47AE-8C33-2ADA9C131BE9/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:381:13)
    at tryCatch (/private/var/folders/2g/_188v_x17s373h59lf73hxl80000gp/T/AppTranslocation/D4A11C80-D987-47AE-8C33-2ADA9C131BE9/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/private/var/folders/2g/_188v_x17s373h59lf73hxl80000gp/T/AppTranslocation/D4A11C80-D987-47AE-8C33-2ADA9C131BE9/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/private/var/folders/2g/_188v_x17s373h59lf73hxl80000gp/T/AppTranslocation/D4A11C80-D987-47AE-8C33-2ADA9C131BE9/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/private/var/folders/2g/_188v_x17s373h59lf73hxl80000gp/T/AppTranslocation/D4A11C80-D987-47AE-8C33-2ADA9C131BE9/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [iOSLog] Stopping iOS log capture
[error] [MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: "Command 'Scripts/bootstrap.sh -d' exited with code 1". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
    at XCUITestDriver.quitAndUninstall$ (/private/var/folders/2g/_188v_x17s373h59lf73hxl80000gp/T/AppTranslocation/D4A11C80-D987-47AE-8C33-2ADA9C131BE9/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:381:13)
    at tryCatch (/private/var/folders/2g/_188v_x17s373h59lf73hxl80000gp/T/AppTranslocation/D4A11C80-D987-47AE-8C33-2ADA9C131BE9/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/private/var/folders/2g/_188v_x17s373h59lf73hxl80000gp/T/AppTranslocation/D4A11C80-D987-47AE-8C33-2ADA9C131BE9/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/private/var/folders/2g/_188v_x17s373h59lf73hxl80000gp/T/AppTranslocation/D4A11C80-D987-47AE-8C33-2ADA9C131BE9/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/private/var/folders/2g/_188v_x17s373h59lf73hxl80000gp/T/AppTranslocation/D4A11C80-D987-47AE-8C33-2ADA9C131BE9/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[info] [HTTP] <-- POST /wd/hub/session 500 14144 ms - 492

**Comment by imurchie** [comment]
Are you running Appium.app? Did you install it? That is, did you move the app from the DMG file you mounted to your `Applications` directory? It seems like you did not, so it is on a read-only partition and Appium cannot function.

**Comment by sagarsheth27** [comment]
I already installed it on my phone.(Physical device). I gave app dependency due to error. Otherwise it is not needed. Please give exact solution. What to do?

**Comment by imurchie** [comment]
I am not sure what you mean.

You are running Appium.app, and you have not moved it onto your harddrive. This is the cause of the error here.
