### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: Parameters were incorrect. We wanted {"required":["desiredCapabilities"],"optional":["requiredCapabilities","sessionId","id","sessionId","id"]} and you sent ["capabilities","desiredCapabilities"]

### ISSUE THREAD

**Issue by miaoqinqin** [appium/appium#9468]
/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7 /Applications/PyCharm.app/Contents/helpers/profiler/run_profiler.py 127.0.0.1 56525 /Users/qinqin/PycharmProjects/untitled/login.py
Starting cProfile profiler

Snapshot saved to /Users/qinqin/Library/Caches/PyCharm2017.1/snapshots/untitled.pstat
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/profiler/run_profiler.py", line 164, in <module>
    profiler.run(file)
  File "/Applications/PyCharm.app/Contents/helpers/profiler/run_profiler.py", line 89, in run
    execfile(file, globals, globals)  # execute the script
  File "/Users/qinqin/PycharmProjects/untitled/login.py", line 30, in <module>
    driver = webdriver.Remote('http://127.0.0.1:4723/wd/hub',dic_parament)
  File "/Library/Python/2.7/site-packages/appium/webdriver/webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 151, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 240, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 165, in check_response
    raise exception_class(value)
selenium.common.exceptions.WebDriverException: Message: Parameters were incorrect. We wanted {"required":["desiredCapabilities"],"optional":["requiredCapabilities","sessionId","id","sessionId","id"]} and you sent ["capabilities","desiredCapabilities"]

**Comment by mykola-mokhnach** [comment]
Please provide a proper issue description

**Comment by miaoqinqin** [comment]
Sorry to bother you. Please give me some directions for the question。

**Comment by mykola-mokhnach** [comment]
Appium 1.5.3 is out of date. You must user Appium 1.7+ together with Selenium 3+
