### ISSUE TITLE
Appium stucks when taking sreccenshot for hybrid app

### ISSUE THREAD

**Issue by wei-gu** [appium/appium#9480]
The problem
Appium stucks when taking sreccenshot for hybrid app after switch context to webview

Environment

Appium version (or git revision) that exhibits the issue: 1.7.2-beta
 Desktop OS/version used to run Appium: Windows 2016
 Mobile platform/version under test: Android 8.0

Logs:
2017-10-17 15:49:43:921 - [HTTP] <-- POST /wd/hub/session/d3ca09a0-698b-4aa3-8723-a0356d3d6998/element/0.11478849023740056-1/click 200 434 ms - 76
2017-10-17 15:49:46:924 - [HTTP] --> GET /wd/hub/session/d3ca09a0-698b-4aa3-8723-a0356d3d6998/screenshot {}
2017-10-17 15:49:46:930 - [MJSONWP] Driver proxy active, passing request on via HTTP proxy
2017-10-17 15:49:46:935 - [debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/d3ca09a0-698b-4aa3-8723-a0356d3d6998/screenshot] to [GET http://127.0.0.1:8001/wd/hub/session/c5fd1c99383819438835a00d50ab0554/screenshot] with body: {}
2017-10-17 15:52:46:922 - [HTTP] <-- GET /wd/hub/session/d3ca09a0-698b-4aa3-8723-a0356d3d6998/screenshot - - ms - -
2017-10-17 15:55:19:616 - [MJSONWP] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: Error: ESOCKETTIMEDOUT
    at doJwpProxy$ (D:\src\git\appium\appium\node_modules\appium-base-driver\lib\mjsonwp\mjsonwp.js:384:13)
    at tryCatch (D:\src\git\appium\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (D:\src\git\appium\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (D:\src\git\appium\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (D:\src\git\appium\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)

**Comment by mykola-mokhnach** [comment]
This must be some problem with chromedriver then. It freezes and stops responding due to some unknown issue.
I'd collect logcat output there and create a bug for chromedriver.
You could try to enable the _nativeWebScreenshot_ capability to workaround the problem.
