### ISSUE TITLE
unable to load certificate

### ISSUE THREAD

**Issue by LukasLewandowski** [appium/appium#9492]
## The problem

Starting tests on iOS simulator or real device causes an error: 

"selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: unable to load certificate
2017-10-20 12:04:58,736 - 12693:error:0906D06C:PEM routines:PEM_read_bio:no start line:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-64.50.6/src/crypto/pem/pem_lib.c:648:Expecting: TRUSTED CERTIFICATE"

Appium log throws:

"[debug] [XCUITest] Xcode version set to '9.0.1' (tools v9.0.1.0.1.1506734476)
[debug] [XCUITest] iOS SDK Version set to '11.0'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1508494132316 (12:08:52 GMT+0200 (CEST))
[debug] [XCUITest] Available devices:
[XCUITest] Error: Unknown device or simulator UDID: '4b15c4284897fa6f9b4c5205325a9cece997ad35'
    at XCUITestDriver.determineDevice$ (../../lib/driver.js:623:17)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 Error: Unknown device or simulator UDID: '4b15c4284897fa6f9b4c5205325a9cece997ad35'
    at XCUITestDriver.determineDevice$ (../../lib/driver.js:623:17)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[XCUITest] No WebDriverAgent derived data available, so unable to set permissions on WDA attachments folder
[XCUITest] No WebDriverAgent derived data available, so unable to clear system files
[debug] [iOS] Stopping https server for async responses
[debug] [iOSSim] Could not uninstall SSL certificate. No simulator with udid '4b15c4284897fa6f9b4c5205325a9cece997ad35'
[iOSSim] Error: unable to load certificate
12801:error:0906D06C:PEM routines:PEM_read_bio:no start line:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-64.50.6/src/crypto/pem/pem_lib.c:648:Expecting: TRUSTED CERTIFICATE

    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/appium/node_modules/openssl-wrapper/src/index.js:77:13)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:547:12)
 { Error: unable to load certificate
12801:error:0906D06C:PEM routines:PEM_read_bio:no start line:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-64.50.6/src/crypto/pem/pem_lib.c:648:Expecting: TRUSTED CERTIFICATE

    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/appium/node_modules/openssl-wrapper/src/index.js:77:13)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:547:12)
  cause: { Error: unable to load certificate
12801:error:0906D06C:PEM routines:PEM_read_bio:no start line:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-64.50.6/src/crypto/pem/pem_lib.c:648:Expecting: TRUSTED CERTIFICATE

    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/appium/node_modules/openssl-wrapper/src/index.js:77:13)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:547:12) code: 1 },
  isOperational: true,
  code: 1 }
[MJSONWP] Encountered internal error running command: Error: unable to load certificate
12801:error:0906D06C:PEM routines:PEM_read_bio:no start line:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-64.50.6/src/crypto/pem/pem_lib.c:648:Expecting: TRUSTED CERTIFICATE

    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/appium/node_modules/openssl-wrapper/src/index.js:77:13)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:547:12)
[HTTP] <-- POST /wd/hub/session 500 334 ms - 365"

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1 and 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): 1.6.5
* Desktop OS/version used to run Appium: OSX 10.12.6
* Node.js version (unless using Appium.app|exe): 8.7.0
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: both
* Appium CLI or Appium.app|exe: CLI

**Comment by mykola-mokhnach** [comment]
Make sure you have the HEAD version of libimobiledevice installed

**Comment by LukasLewandowski** [comment]
I did:

- brew install --HEAD libimobiledevice
- brew link --overwrite libimobiledevice
- brew unlink libimobiledevice && brew link libimobiledevice

no change :(

**Comment by mykola-mokhnach** [comment]
What is the output of `xcrun simctl list`? Is the simulator with udid 4b15c4284897fa6f9b4c5205325a9cece997ad35 present there?

**Comment by LukasLewandowski** [comment]
4b15c4284897fa6f9b4c5205325a9cece997ad35 this udid is for real device and simulators are also listed in output of xrun simctl list (I tried couple)

after running:

npm install -g ios-deploy

Appium started working with real devices but for simulators it throws the same error

**Comment by LukasLewandowski** [comment]
ok I found another problem :) in desired capabilities I had wrong platform version set to 10.3.3 and after correcting it to "platformVersion": "10.3" Appium started working :)

Thx for help 👍
