### ISSUE TITLE
[Android 7][Appium 1.6.5]Throw Exception when using driver.pressKeyCode(AndroidKeyCode.BACK)

### ISSUE THREAD

**Issue by cuong6690** [appium/appium#9493]
## The problem
I used pressKeyCode(AndroidKeyCode.BACK) to automated pressing back button on android 5.x and 6.x. It worked well but on android 7.x (Nougat) , it throws an exception: 
Method threw 'org.openqa.selenium.WebDriverException' exception.
An unknown server-side error occurred while processing the command. Original error: Cannot read property 'sendAction' of undefined (WARNING: The server did not provide any stacktrace information)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Desktop OS/version used to run Appium: Windows
* Node.js version (unless using Appium.app|exe): 8.3.0
* Mobile platform/version under test: Android 7 (Nougat)
* Real device or emulator/simulator: Samsung galaxy J7 Prime

##Here is Appium logs:
[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"2822988eeb3818601c930d19ca288458\",\"status\":0,\"value\":false}"
[JSONWP Proxy] Replacing sessionId 2822988eeb3818601c930d19ca288458 with 1aac0846-0389-453c-8542-371c04132d0f
[HTTP] <-- GET /wd/hub/session/1aac0846-0389-453c-8542-371c04132d0f/element/0.08995605669857687-1/enabled 200 98 ms - 77 
[HTTP] --> POST /wd/hub/session/1aac0846-0389-453c-8542-371c04132d0f/appium/device/press_keycode {"keycode":4}
[debug] [MJSONWP] Calling AppiumDriver.pressKeyCode() with args: [4,null,null,null,"1aac0846-0389-453c-8542-371c04132d0f"]
[MJSONWP] Encountered internal error running command: TypeError: Cannot read property 'sendAction' of undefined
    at AndroidUiautomator2Driver.callee$0$0$ (../../../lib/commands/actions.js:24:30)
    at tryCatch (C:\Users\cuongnm15\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\cuongnm15\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\cuongnm15\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at invoke (C:\Users\cuongnm15\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at enqueueResult (C:\Users\cuongnm15\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:185:17)
    at Promise (<anonymous>)
    at F (C:\Users\cuongnm15\AppData\Roaming\npm\node_modules\appium\node_modules\core-js\library\modules\$.export.js:30:36)
    at AsyncIterator.enqueue (C:\Users\cuongnm15\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (C:\Users\cuongnm15\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at Object.runtime.async (C:\Users\cuongnm15\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:209:12)
    at AndroidUiautomator2Driver.callee$0$0 [as pressKeyCode] (../../../lib/commands/actions.js:23:66)
    at ../../../lib/basedriver/driver.js:207:24
    at tryCatcher (C:\Users\cuongnm15\AppData\Roaming\npm\node_modules\appium\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\Users\cuongnm15\AppData\Roaming\npm\node_modules\appium\node_modules\bluebird\js\main\promise.js:510:31)
    at Promise._settlePromiseAt (C:\Users\cuongnm15\AppData\Roaming\npm\node_modules\appium\node_modules\bluebird\js\main\promise.js:584:18)
    at Promise._settlePromiseAtPostResolution (C:\Users\cuongnm15\AppData\Roaming\npm\node_modules\appium\node_modules\bluebird\js\main\promise.js:248:10)
    at Async._drainQueue (C:\Users\cuongnm15\AppData\Roaming\npm\node_modules\appium\node_modules\bluebird\js\main\async.js:128:12)
    at Async._drainQueues (C:\Users\cuongnm15\AppData\Roaming\npm\node_modules\appium\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\cuongnm15\AppData\Roaming\npm\node_modules\appium\node_modules\bluebird\js\main\async.js:15:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
[HTTP] <-- POST /wd/hub/session/1aac0846-0389-453c-8542-371c04132d0f/appium/device/press_keycode 500 13 ms - 217 
[HTTP] --> POST /wd/hub/session/1aac0846-0389-453c-8542-371c04132d0f/context {"name":"NATIVE_APP"}

**Comment by mykola-mokhnach** [comment]
Do you get the same exception after updating to 1.7.1?

**Comment by cuong6690** [comment]
Do you mean I should update the appium to version 1.7.1 ?

**Comment by mykola-mokhnach** [comment]
yes

**Comment by cuong6690** [comment]
ok, I will try it and let you know the result.

**Comment by cuong6690** [comment]
Hi @mykola-mokhnach , I have tried with appium v1.7.1 and it works well
