### ISSUE TITLE
xcode 9 and iOS 11 fails to execute native app

### ISSUE THREAD

**Issue by lahiruw** [appium/appium#9507]
## The problem

Hi Team , i'm trying to Automate a native app with iOS 11 and xcode 9 .but it fails giving below error .same app works fine with iOS 10.3.3 and xcode 9.

Error
---------
Appium has been started
Running test - testASOHNotinProductInformationForMAUser
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:386:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:386:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:386:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
Result: SKIPPED

Appreciate if any one can help to solve issue ....

**Comment by mykola-mokhnach** [comment]
Code 65 usually means there are problem with WDA code signing

**Comment by lahiruw** [comment]
@mykola-mokhnach

Thanks a Lot .Any other answers pls ?

**Comment by sankarimns** [comment]
having the same issue. Answer pls

**Comment by pavanbachu0604** [comment]
Can you mention Appium Version that was being used for iOS 10.3.3 and iOS 11 ?

**Comment by lahiruw** [comment]
@sankarimns @pavanbachu0604 i was able to automate using xcode 9.0.1 beta /appium 1.6.4 or newer /iOS11 . any other help needed ?

**Comment by lahiruw** [comment]
@sankarimns 
1.)unplug all devices attached to main device
2.)clear all files within /var/db/lockdown
3.)set device , settings>Safari>Advanced > web inspector = ON
4.)Run below on terminal
brew update
brew reinstall --HEAD libimobiledevice
brew reinstall -s ios-webkit-debug-proxy
5.)Replug devices one by one 
* you can run 'ios-webkit-debug-proxy -d ' command to verify devices are connected correctly or not .
6.)Execute tests 

Cheers

**Comment by lahiruw** [comment]
@mykola-mokhnach I was able to execute tests . Thanks .
