### ISSUE TITLE
Appium : Permission to start activity denied.

### ISSUE THREAD

**Issue by chandan188** [appium/appium#9510]
## The problem

 An unknown server-side error occurred while processing the command. Original error: Error occured while starting App. Original error: Permission to start activity denied. (WARNING: The server did not provide any stacktrace information)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.2.4
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe):6.11.4
* Mobile platform/version under test: Honor 4x 6.0.1
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:1.7.0

## Link to Appium logs

[info] [Appium] Welcome to Appium v1.7.0
[info] [Appium] Non-default server args:
[info] [Appium]   address: 127.0.0.1
[info] [Appium] Appium REST http interface listener started on 127.0.0.1:4723[info] [HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"appPackage":"com.facebook.katana","appActivity":"com.facebook.katana.dbl.activity.FacebookLoginActivity","platformName":"Android","deviceName":"Android"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"appPackage":"com.facebook.katana","appActivity":"com.facebook.katana.dbl.activity.FacebookLoginActivity","platformName":"Android","deviceName":"Android"},null,null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1508822144950 (10:45:44 GMT+0530 (India Standard Time))
[info] [Appium] Creating new AndroidDriver (v1.26.5) session
[info] [Appium] Capabilities:
[info] [Appium]   appPackage: 'com.facebook.katana'
[info] [Appium]   appActivity: 'com.facebook.katana.dbl.activity.FacebookLoginActivity'
[info] [Appium]   platformName: 'Android'
[info] [Appium]   deviceName: 'Android'
[info] [BaseDriver] Session created with session id: d088daa9-b736-4cf5-b423-c7e810ebba85
[debug] [AndroidDriver] Getting Java version[info] [AndroidDriver] Java version is: 1.8.0_111
[info] [ADB] Checking whether adb is present
[info] [ADB] Using adb.exe from C:\Users\cdas\AppData\Local\Android\sdk\platform-tools\adb.exe
[info] [AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...[debug] [ADB] 1 device(s) connected
[info] [AndroidDriver] Using device: A6TDU15401007022
[info] [ADB] Checking whether adb is present
[info] [ADB] Using adb.exe from C:\Users\cdas\AppData\Local\Android\sdk\platform-tools\adb.exe
[debug] [ADB] Setting device id to A6TDU15401007022
[info] [AndroidDriver] App file was not listed, instead we're going to run com.facebook.katana directly on the device
[debug] [AndroidDriver] Checking whether package is present on the device
[debug] [ADB] Getting connected devices...[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\cdas\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","A6TDU15401007022","shell","pm","list","packages","com.facebook.katana"][info] [AndroidDriver] Starting Android session
[debug] [ADB] Running 'C:\Users\cdas\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","A6TDU15401007022","wait-for-device"][debug] [ADB] Getting connected devices...[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\cdas\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","A6TDU15401007022","shell","echo","ping"][debug] [Logcat] Starting logcat capture[debug] [AndroidDriver] Pushing settings apk to device...
[debug] [ADB] Getting install status for io.appium.settings
[debug] [ADB] Getting connected devices...[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\cdas\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","A6TDU15401007022","shell","pm","list","packages","io.appium.settings"][debug] [ADB] App is installed
[debug] [ADB] Getting package info for io.appium.settings
[debug] [ADB] Getting connected devices...[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\cdas\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","A6TDU15401007022","shell","dumpsys","package","io.appium.settings"][info] [ADB] Checking whether aapt is present
[info] [ADB] Using aapt.exe from C:\Users\cdas\AppData\Local\Android\sdk\build-tools\25.0.3\aapt.exe[debug] [ADB] The installed "io.appium.settings" package does not require upgrade (4 >= 4)
[debug] [ADB] Getting connected devices...[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\cdas\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","A6TDU15401007022","shell","getprop","ro.build.version.sdk"][debug] [ADB] Current device property 'ro.build.version.sdk': 23
[debug] [ADB] Device API level: 23
[debug] [ADB] Getting connected devices...[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\cdas\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","A6TDU15401007022","shell","dumpsys","package","io.appium.settings"][debug] [ADB] Getting connected devices...[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\cdas\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","A6TDU15401007022","shell","pm","dump","io.appium.settings"][debug] [ADB] Got the following command chunks to execute: pm,grant,io.appium.settings,android.permission.CHANGE_NETWORK_STATE,;,pm,grant,io.appium.settings,android.permission.WRITE_SETTINGS,;,pm,grant,io.appium.settings,android.permission.ACCESS_MOCK_LOCATION,;
[debug] [ADB] Getting connected devices...[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\cdas\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","A6TDU15401007022","shell","pm","grant","io.appium.settings","android.permission.CHANGE_NETWORK_STATE",";","pm","grant","io.appium.settings","android.permission.WRITE_SETTINGS",";","pm","grant","io.appium.settings","android.permission.ACCESS_MOCK_LOCATION",";"][debug] [ADB] Getting connected devices...[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\cdas\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","A6TDU15401007022","shell","ps"][debug] [ADB] Device API level: 23
[debug] [ADB] Getting connected devices...[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\cdas\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","A6TDU15401007022","shell","am","start","-W","-n","io.appium.settings/.Settings","-a","android.intent.action.MAIN","-c","android.intent.category.LAUNCHER","-f","0x10200000"][debug] [ADB] Device API level: 23
[debug] [ADB] Getting connected devices...[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\cdas\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","A6TDU15401007022","shell","appops","set","io.appium.settings","android:mock_location","allow"][debug] [AndroidDriver] Pushing unlock helper app to device...
[debug] [ADB] Running 'C:\Users\cdas\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","A6TDU15401007022","install","C:\\Users\\cdas\\AppData\\Local\\Programs\\appium-desktop\\resources\\app\\node_modules\\appium\\node_modules\\appium-unlock\\bin\\unlock_apk-debug.apk"][info] [ADB] Getting device platform version
[debug] [ADB] Getting connected devices...[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\cdas\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","A6TDU15401007022","shell","getprop","ro.build.version.release"][debug] [ADB] Current device property 'ro.build.version.release': 6.0.1
[debug] [ADB] Getting connected devices...[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\cdas\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","A6TDU15401007022","shell","wm","size"][debug] [ADB] Getting connected devices...[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\cdas\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","A6TDU15401007022","shell","getprop","ro.product.model"][debug] [ADB] Current device property 'ro.product.model': Che1-L04
[debug] [ADB] Getting connected devices...[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\cdas\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","A6TDU15401007022","shell","getprop","ro.product.manufacturer"][debug] [ADB] Current device property 'ro.product.manufacturer': HUAWEI
[warn] [AndroidDriver] No app sent in, not parsing package/activity
[debug] [AndroidDriver] No app capability. Assuming it is already on the device
[debug] [AndroidDriver] Running fast reset (stop and clear)
[debug] [ADB] Getting connected devices...[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\cdas\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","A6TDU15401007022","shell","am","force-stop","com.facebook.katana"][debug] [ADB] Getting connected devices...[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\cdas\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","A6TDU15401007022","shell","pm","clear","com.facebook.katana"][debug] [AndroidBootstrap] Watching for bootstrap disconnect
[debug] [ADB] Forwarding system: 4724 to device: 4724
[debug] [ADB] Running 'C:\Users\cdas\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","A6TDU15401007022","forward","tcp:4724","tcp:4724"]
[debug] [UiAutomator] Starting UiAutomator
[debug] [UiAutomator] Moving to state 'starting'
[debug] [UiAutomator] Parsing uiautomator jar
[debug] [UiAutomator] Found jar name: 'AppiumBootstrap.jar'
[debug] [ADB] Running 'C:\Users\cdas\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","A6TDU15401007022","push","C:\\Users\\cdas\\AppData\\Local\\Programs\\appium-desktop\\resources\\app\\node_modules\\appium\\node_modules\\appium-android-bootstrap\\bootstrap\\bin\\AppiumBootstrap.jar","/data/local/tmp/"][debug] [ADB] Attempting to kill all uiautomator processes
[debug] [ADB] Getting all processes with uiautomator
[debug] [ADB] Getting connected devices...[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\cdas\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","A6TDU15401007022","shell","ps"][info] [ADB] No uiautomator process found to kill, continuing...
[debug] [UiAutomator] Starting UIAutomator
[debug] [ADB] Creating ADB subprocess with args: ["-P",5037,"-s","A6TDU15401007022","shell","uiautomator","runtest","AppiumBootstrap.jar","-c","io.appium.android.bootstrap.Bootstrap","-e","pkg","com.facebook.katana","-e","disableAndroidWatchers",false,"-e","acceptSslCerts",false][debug] [UiAutomator] Moving to state 'online'
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Loading json...
[info] [AndroidBootstrap] Android bootstrap socket is now connected
[debug] [ADB] Getting connected devices...
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] json loading complete.
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Registered crash watchers.
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Client connected[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\cdas\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","A6TDU15401007022","shell","dumpsys","window"][info] [AndroidDriver] Screen already unlocked, doing nothing
[debug] [ADB] Device API level: 23
[debug] [ADB] Getting connected devices...[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\cdas\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","A6TDU15401007022","shell","am","start","-W","-n","com.facebook.katana/com.facebook.katana.dbl.activity.FacebookLoginActivity","-S"][error] [ADB] Error: Permission to start activity denied.
    at Object.wrappedLogger.errorAndThrow (C:\Users\cdas\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:63:13)
    at ADB.callee$0$0$ (C:\Users\cdas\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\apk-utils.js:94:11)
    at tryCatch (C:\Users\cdas\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\cdas\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\cdas\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\cdas\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: Permission to start activity denied.
    at Object.wrappedLogger.errorAndThrow (C:\Users\cdas\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:63:13)
    at ADB.callee$0$0$ (C:\Users\cdas\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\apk-utils.js:94:11)
    at tryCatch (C:\Users\cdas\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\cdas\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\cdas\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\cdas\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[error] [ADB] Error: Error occured while starting App. Original error: Permission to start activity denied.
    at Object.wrappedLogger.errorAndThrow (C:\Users\cdas\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:63:13)
    at ADB.callee$0$0$ (C:\Users\cdas\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\apk-utils.js:101:9)
    at tryCatch (C:\Users\cdas\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\cdas\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\cdas\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\cdas\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: Error occured while starting App. Original error: Permission to start activity denied.
    at Object.wrappedLogger.errorAndThrow (C:\Users\cdas\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:63:13)
    at ADB.callee$0$0$ (C:\Users\cdas\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\apk-utils.js:101:9)
    at tryCatch (C:\Users\cdas\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\cdas\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\cdas\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\cdas\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[debug] [AndroidDriver] Shutting down Android driver
[debug] [ADB] Getting connected devices...[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\cdas\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","A6TDU15401007022","shell","am","force-stop","com.facebook.katana"][debug] [ADB] Pressing the HOME button
[debug] [ADB] Getting connected devices...[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\cdas\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","A6TDU15401007022","shell","input","keyevent",3][debug] [AndroidBootstrap] Sending command to android: {"cmd":"shutdown"}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"shutdown"}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type SHUTDOWN
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":"OK, shutting down"}
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [UiAutomator] Shutting down UiAutomator
[debug] [UiAutomator] Moving to state 'stopping'
[debug] [UiAutomator] UiAutomator shut down normally
[debug] [UiAutomator] Moving to state 'stopped'
[debug] [ADB] Attempting to kill all uiautomator processes
[debug] [ADB] Getting all processes with uiautomator
[debug] [ADB] Getting connected devices...[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\cdas\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","A6TDU15401007022","shell","ps"][info] [ADB] No uiautomator process found to kill, continuing...
[debug] [UiAutomator] Moving to state 'stopped'
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Getting connected devices...[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\cdas\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","A6TDU15401007022","shell","am","force-stop","io.appium.unlock"][debug] [AndroidDriver] Not cleaning generated files. Add `clearSystemFiles` capability if wanted.
[error] [MJSONWP] Encountered internal error running command: Error: Error occured while starting App. Original error: Permission to start activity denied.
    at Object.wrappedLogger.errorAndThrow (C:\Users\cdas\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:63:13)
    at ADB.callee$0$0$ (C:\Users\cdas\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\apk-utils.js:101:9)
    at tryCatch (C:\Users\cdas\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\cdas\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\cdas\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\cdas\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[info] [HTTP] <-- POST /wd/hub/session 500 112085 ms - 223 

## Code To Reproduce Issue [ Good To Have ]
Base Class:
--------------
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.remote.DesiredCapabilities;

import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.android.AndroidElement;
import io.appium.java_client.remote.MobileCapabilityType;

public class base {
public static  AndroidDriver<AndroidElement> capabilities() throws MalformedURLException
{
AndroidDriver<AndroidElement>  driver;

// TODO Auto-generated method stub
//File appDir = new File("src");
//     File app = new File(appDir, "apkpure_app_2021.apk");
     DesiredCapabilities capabilities = new DesiredCapabilities();
     
     capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "Android");
     capabilities.setCapability("platformName", "Android");
     //capabilities.setCapability(MobileCapabilityType.APP, app.getAbsolutePath());
     
   //app details
//     String appPath = "/mnt/asec/com.facebook.katana-2/pkg.apk";
//     capabilities.setCapability("app", "appPath");
     capabilities.setCapability("appPackage","com.facebook.katana");
     capabilities.setCapability("appActivity", "com.facebook.katana.dbl.activity.FirstBootActivity");
     capabilities.setCapability("appActivity", "com.facebook.katana.dbl.activity.FacebookLoginActivity");
    driver = new AndroidDriver<>(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
   
   return driver;
}

}

Main Method:
---------------
import java.net.MalformedURLException;
import java.util.concurrent.TimeUnit;

import io.appium.java_client.TouchAction;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.android.AndroidElement;

public class whatsApp extends base{

	public static void main(String[] args) throws MalformedURLException {
		// TODO Auto-generated method stub
		AndroidDriver<AndroidElement> driver=capabilities();
	     driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
	     System.out.println("FB run");
	
	driver.quit();
	}

}

Appium Logs:

Eclipse Message:

Exception in thread "main" org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error occured while starting App. Original error: Permission to start activity denied. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 112.28 seconds
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'A10P-00000-CDAS', ip: '169.254.34.184', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: io.appium.java_client.android.AndroidDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:249)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:87)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:111)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:72)
	at com.appium.testCases.base.capabilities(base.java:33)
	at com.appium.testCases.whatsApp.main(whatsApp.java:14)

**Comment by mykola-mokhnach** [comment]
I assume the error there is pretty clear - you don't have permissions to start the activity. Most likely the activity name you use it wrong and should be corrected. Also you could try to set both appActivity and appWaitActivity capabilities.

**Comment by chandan188** [comment]
@mykola-mokhnach 

How to enable the permission .

**Comment by chandan188** [comment]
Hi 

I have given the permission through capabilities.
capabilities.setCapability("autoGrantPermissions","true");

Able to Launch my Native App

**Comment by leomperes** [comment]
@chandan188 you can skipp/remove `appActivity` capability.

> See more here: <https://stackoverflow.com/a/36396642/2334082>

**Comment by mirao** [comment]
I had similar issue and solved it by setting of the option _appWaitActivity_
I also tried _appActivity_ only, but it didn't help.
