### ISSUE TITLE
`appium --help` throws exception

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#9529]
Running `appium --help` from the CLI gives an error with this stack trace

```
TypeError: parts.forEach is not a function
    at _getLines (/Users/danielgraham/.nvm/versions/node/v7.10.1/lib/node_modules/appium/node_modules/argparse/lib/help/formatter.js:380:15)
    at HelpFormatter._formatUsage (/Users/danielgraham/.nvm/versions/node/v7.10.1/lib/node_modules/appium/node_modules/argparse/lib/help/formatter.js:418:17)
    at /Users/danielgraham/.nvm/versions/node/v7.10.1/lib/node_modules/appium/node_modules/argparse/lib/help/formatter.js:67:17
    at Array.map (native)
    at Section.formatHelp (/Users/danielgraham/.nvm/versions/node/v7.10.1/lib/node_modules/appium/node_modules/argparse/lib/help/formatter.js:61:26)
    at HelpFormatter.formatHelp (/Users/danielgraham/.nvm/versions/node/v7.10.1/lib/node_modules/appium/node_modules/argparse/lib/help/formatter.js:300:32)
    at ArgumentParser.formatUsage (/Users/danielgraham/.nvm/versions/node/v7.10.1/lib/node_modules/appium/node_modules/argparse/lib/argument_parser.js:1026:20)
    at ArgumentParser.printUsage (/Users/danielgraham/.nvm/versions/node/v7.10.1/lib/node_modules/appium/node_modules/argparse/lib/argument_parser.js:1082:27)
    at ArgumentParser.error (/Users/danielgraham/.nvm/versions/node/v7.10.1/lib/node_modules/appium/node_modules/argparse/lib/argument_parser.js:1156:8)
    at ArgumentParser.parseKnownArgs (/Users/danielgraham/.nvm/versions/node/v7.10.1/lib/node_modules/appium/node_modules/argparse/lib/argument_parser.js:297:10)
    at ArgumentParser.parseArgs (/Users/danielgraham/.nvm/versions/node/v7.10.1/lib/node_modules/appium/node_modules/argparse/lib/argument_parser.js:234:21)
    at ArgumentParser.parser.parseArgs (../../lib/parser.js:752:29)
    at main$ (../../lib/main.js:146:4)
    at tryCatch (/Users/danielgraham/.nvm/versions/node/v7.10.1/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/danielgraham/.nvm/versions/node/v7.10.1/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/danielgraham/.nvm/versions/node/v7.10.1/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/Users/danielgraham/.nvm/versions/node/v7.10.1/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/Users/danielgraham/.nvm/versions/node/v7.10.1/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at F (/Users/danielgraham/.nvm/versions/node/v7.10.1/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/Users/danielgraham/.nvm/versions/node/v7.10.1/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/Users/danielgraham/.nvm/versions/node/v7.10.1/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/Users/danielgraham/.nvm/versions/node/v7.10.1/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at main (../../lib/main.js:152:13)
    at asyncify (lib/asyncbox.js:65:15)
    at Object.<anonymous> (../../lib/main.js:183:2)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
```

**Comment by welnanick** [comment]
Doesn't happen for me on 1.7.2@beta on macOS Sierra 10.12.6.

**Comment by mykola-mokhnach** [comment]
I don't have such exception as well. I'd assume it happens inside argparse module if there are [mistakes in arguments list](https://github.com/appium/appium/issues/9022) or some [problems with the script name](https://github.com/nodeca/argparse/issues/86)

Not sure if we should go deeper there. One can either add a PR to the original module or try/catch on our side to print better error message

**Comment by dpgraham** [comment]
I'll try it again tomorrow and try to fix it myself.

**Comment by dpgraham** [comment]
The Appium CLI should never be throwing errors so I'd like to know how I made an error occur.

**Comment by Jasonzming** [comment]
I have the same exception as well

**Comment by munkyjunky** [comment]
Also hitting this issue with Appium 1.7.2 on Mac. Is there any more information I can provide on this that would be helpful for debugging it?

**Comment by dpgraham** [comment]
@munkyjunky We have a fix ready. We're waiting on a pull request for a third party library that we're using (https://github.com/nodeca/argparse/pull/122) and then it will be in the next version of Appium.
