### ISSUE TITLE
TypeError: opts.platformVersion.trim is not a function

### ISSUE THREAD

**Issue by jh11200** [appium/appium#9531]
appium1.7.1  running in centOS
python 3.6.3 

[debug] [ADB] 1 device(s) connected
[debug] [AndroidDriver] Shutting down Android driver
[debug] [AndroidDriver] Called deleteSession but bootstrap wasn't active
[MJSONWP] Encountered internal error running command: TypeError: opts.platformVersion.trim is not a function
    at Object.callee$0$0$ (../../lib/android-helpers.js:159:51)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:109:7)
[HTTP] <-- POST /wd/hub/session 500 3101 ms - 180
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[BaseDriver] Capability 'autoLaunch' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] Capability 'noReset' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] Capability 'fullReset' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] Session created with session id: cae44405-c669-48d7-bf3f-5bbda12a039c
[debug] [AndroidDriver] Getting Java version
[AndroidDriver] Java version is: 1.8.0_144
[ADB] Checking whether adb is present
[ADB] Using adb from /opt/android_sdk_linux/platform-tools/adb

**Comment by mykola-mokhnach** [comment]
Can you attach the full log with capabilities passed to start the session?

**Comment by mykola-mokhnach** [comment]
The fix to ensure the platformVersion is always a string has been published in the recent Appium@beta

**Comment by klaxmi361** [comment]
after changing platformVersion  type to string, worked as expected
Thank you
R
