### ISSUE TITLE
Appium getting stuck on mac os x while finding elements

### ISSUE THREAD

**Issue by visshal** [appium/appium#9580]
## The problem

Appium not able to identify objects on Native Android App. Even if identifies it never returns result back to the Appium Selenium driver. On Appium server log it just gets stuck at finding object.

## Environment

* Appium version (or git revision) that exhibits the issue: v1.7.1 (Installed using npm)
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS Sierra (v10.12.6)
* Node.js version (unless using Appium.app|exe): v8.7.0
* Mobile platform/version under test: (x86 Pixel API 25)
* Real device or emulator/simulator:emulator
* Appium CLI or Appium.app|exe: CLI

## Details

Appium server was started using appium command. I am using Selenium Webdriver. And same thing works fine on windows.

MobileDriver driver;
DesiredCapabilities capabilities = new DesiredCapabilities("", "", Platform.ANDROID);
capabilities.setCapability("deviceName", "Android Emulator");
capabilities.setCapability("platformVersion", "7.1.1");
capabilities.setCapability("platformName", "Android");
capabilities.setCapability("app",".SampleApplication-V117.apk");
capabilities.setCapability("appPackage", "com.customPackage.simplecontainer");
capabilities.setCapability("appActivity",".SelectionActivity");
        try {
            driver = new AndroidDriver(new URL("http://localhost:4723/wd/hub"),capabilities);
            driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
        }
        catch(MalformedURLException e) {
            e.printStackTrace();
        }
       MobileElement ele = (MobileElement) driver.findElement(By.id("com.jackalopelite.simplecontainer:id/lv_features"));

## Link to Appium logs
Full Appium Log -> [GIST](https://gist.github.com/visshal/7c70fc865d88a6af0b8195963f4b93b1)

**Comment by visshal** [comment]
**After some times 10 minutes (which I guess could be default timeout)**

[HTTP] <-- POST /wd/hub/session/f228f1cf-f1fc-4473-8770-94eb1cfe43ed/element - - ms - - 
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":7,"value":"No element found"}

**Client side Logs:**
org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'adortega-mobl1.amr.corp.intel.com', ip: '10.254.184.24', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_144'
Driver info: driver.version: AndroidDriver
Capabilities [{app=/Users/vgmehta/Documents/TrueVR-Documents/SampleApplication-V117.apk, appPackage=com.jackalopelite.simplecontainer, deviceScreenSize=1440x2560, networkConnectionEnabled=true, warnings={}, databaseEnabled=false, version=, deviceName=emulator-5554, platform=ANDROID, deviceUDID=emulator-5554, appActivity=.SelectionActivity, desired={app=/Users/vgmehta/Documents/TrueVR-Documents/SampleApplication-V117.apk, appPackage=com.jackalopelite.simplecontainer, appActivity=.SelectionActivity, platformVersion=7.1.1, browserName=, platformName=Android, version=, deviceName=Android Emulator, platform=ANDROID}, platformVersion=7.1.1, webStorageEnabled=false, locationContextEnabled=false, takesScreenshot=true, browserName=, javascriptEnabled=true, deviceModel=Android SDK built for x86, platformName=Android, deviceManufacturer=unknown}]
Session ID: f228f1cf-f1fc-4473-8770-94eb1cfe43ed
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:665)
        at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:40)
        at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
        at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
        at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:363)
        at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:56)
        at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
        at io.appium.java_client.android.AndroidDriver.findElement(AndroidDriver.java:1)
        at org.openqa.selenium.remote.RemoteWebDriver.findElementById(RemoteWebDriver.java:413)
        at io.appium.java_client.DefaultGenericMobileDriver.findElementById(DefaultGenericMobileDriver.java:64)
        at io.appium.java_client.AppiumDriver.findElementById(AppiumDriver.java:1)
        at io.appium.java_client.android.AndroidDriver.findElementById(AndroidDriver.java:1)
        at org.openqa.selenium.By$ById.findElement(By.java:218)
        at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:355)
        at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:52)
        at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
        at io.appium.java_client.android.AndroidDriver.findElement(AndroidDriver.java:1)
        at com.intel.truevr.appautomation.sdk.SampleFeature.tapVideoTypeButton(SampleFeature.java:42)
        at ✽.When User taps the normal video button(/Users/vgmehta/TrueVR/mobile-automation/src/main/resources/Feature/sdk/sample.feature:5)
Caused by: org.openqa.selenium.WebDriverException: org.apache.http.NoHttpResponseException: localhost:4723 failed to respond
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'adortega-mobl1.amr.corp.intel.com', ip: '10.254.184.24', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_144'
Driver info: driver.version: AndroidDriver
        at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:84)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:644)
        at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:40)
        at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
        at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
        at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:363)
        at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:56)
        at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
        at io.appium.java_client.android.AndroidDriver.findElement(AndroidDriver.java:1)
        at org.openqa.selenium.remote.RemoteWebDriver.findElementById(RemoteWebDriver.java:413)
        at io.appium.java_client.DefaultGenericMobileDriver.findElementById(DefaultGenericMobileDriver.java:64)
        at io.appium.java_client.AppiumDriver.findElementById(AppiumDriver.java:1)
        at io.appium.java_client.android.AndroidDriver.findElementById(AndroidDriver.java:1)
        at org.openqa.selenium.By$ById.findElement(By.java:218)
        at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:355)
        at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:52)
        at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
        at io.appium.java_client.android.AndroidDriver.findElement(AndroidDriver.java:1)
        at com.intel.truevr.appautomation.sdk.SampleFeature.tapVideoTypeButton(SampleFeature.java:42)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at cucumber.runtime.Utils$1.call(Utils.java:44)
        at cucumber.runtime.Timeout.timeout(Timeout.java:12)
        at cucumber.runtime.Utils.invoke(Utils.java:40)
        at cucumber.runtime.java.JavaStepDefinition.execute(JavaStepDefinition.java:35)
        at cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:38)
        at cucumber.runtime.Runtime.runStep(Runtime.java:270)
        at cucumber.runtime.model.StepContainer.runStep(StepContainer.java:49)
        at cucumber.runtime.model.StepContainer.runSteps(StepContainer.java:43)
        at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:36)
        at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:112)
        at cucumber.runtime.Runtime.run(Runtime.java:105)
        at cucumber.runtime.Runtime.run(Runtime.java:93)
        at cucumber.api.cli.Main.run(Main.java:20)
        at cucumber.api.cli.Main.main(Main.java:12)
Caused by: org.apache.http.NoHttpResponseException: localhost:4723 failed to respond
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
        at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:162)
        at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:90)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
        at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:69)
        ... 36 more

**Comment by mykola-mokhnach** [comment]
Try to change automation backend to UIAutomator2

**Comment by visshal** [comment]
Awesome that worked as charm!!
Can you please advise why do I need to use UIAUtomator2? What is the default backend?

THanks,
Vishal.

**Comment by mykola-mokhnach** [comment]
UIAutomator1 is an outdated technology and is not supported by Google anymore. The lack of support is obvious for newer Android releases.
