### ISSUE TITLE
Appium 1.7.1 Can't run a Chrome-based session

### ISSUE THREAD

**Issue by vaznoe** [appium/appium#9598]
## I can't  launch chrome browser,  error is shown 
 [AndroidDriver] Error: Could not find package com.android.chrome on the device

## Environment
* Appium version (or git revision) that exhibits the issue: 1.7.1
* Desktop OS/version used to run Appium: macOS Sierra v.10.12.6
* Node.js version (unless using Appium.app|exe): v8.9.0
* Mobile platform/version under test: Genymotion v.2.11.0
* Real device or emulator/simulator: emulator

## Appium logs
```
[Appium] Welcome to Appium v1.7.1
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"browserName":"Chrome","chromedriverExecutable":"/Users/name/node_modules/appium-chromedriver/chromedriver/mac/chromedriver","deviceName":"Google Nexus 5X","platformName":"Android"},"capabilities":{"desiredCapabilities":{"browserName":"Chrome","chromedriverExecutable":"/Users/name/node_modules/appium-chromedriver/chromedriver/mac/chromedriver","deviceName":"Google Nexus 5X","platformName":"Android"},"firstMatch":[{"browserName":"Chrome","platformName":"android"}]}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"browserName":"Chrome","chromedriverExecutable":"/Users/name/node_modules/appium-chromedriver/chromedriver/mac/chromedriver","deviceName":"Google Nexus 5X","platformName":"Android"},null,{"desiredCapabilities":{"browserName":"Chrome","chromedriverExecutable":"/Users/name/node_modules/appium-chromedriver/chromedriver/mac/chromedriver","deviceName":"Google Nexus 5X","platformName":"Android"},"firstMatch":[{"browserName":"Chrome","platformName":"android"}]}]
[BaseDriver] Event 'newSessionRequested' logged at 1510082258618 (11:17:38 GMT-0800 (PST))
[Appium] Creating new AndroidDriver (v1.28.1) session
[Appium] Capabilities:
[Appium]   browserName: 'Chrome'
[Appium]   chromedriverExecutable: '/Users/name/node_modules/appium-chromedriver/chromedriver/mac/chromedriver'
[Appium]   deviceName: 'Google Nexus 5X'
[Appium]   platformName: 'Android'
[BaseDriver] Session created with session id: 
[AndroidDriver] Getting Java version
[AndroidDriver] Java version is: 1.8.0_151
[AndroidDriver] We're going to run a Chrome-based session
[AndroidDriver] Chrome-type package and activity are com.android.chrome and com.google.android.apps.chrome.Main
[ADB] Checking whether adb is present
[ADB] Using adb from /Users/name/Library/Android/sdk/platform-tools/adb
[AndroidDriver] Retrieving device list
[ADB] Trying to find a connected android device
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[AndroidDriver] Using device: 192.168.56.101:5555
[ADB] Checking whether adb is present
[ADB] Using adb from /Users/name/Library/Android/sdk/platform-tools/adb
[ADB] Setting device id to :5555
[AndroidDriver] App file was not listed, instead we're going to run com.android.chrome directly on the device
[AndroidDriver] Checking whether package is present on the device
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/Users/name/Library/Android/sdk/platform-tools/adb' with args: ["-P",,"-s",":5555","shell","pm","list","packages","com.android.chrome"]
[AndroidDriver] Error: Could not find package com.android.chrome on the device
    at Object.wrappedLogger.errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:63:13)
    at AndroidDriver.checkPackagePresent$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-android-driver/lib/driver.js:392:11)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: Could not find package com.android.chrome on the device
    at Object.wrappedLogger.errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:63:13)
    at AndroidDriver.checkPackagePresent$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-android-driver/lib/driver.js:392:11)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[AndroidDriver] Shutting down Android driver
[AndroidDriver] Called deleteSession but bootstrap wasn't active
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/Users/name/Library/Android/sdk/platform-tools/adb' with args: ["-P",,"-s",":5555","shell","am","force-stop","io.appium.unlock"]
[AndroidDriver] Not cleaning generated files. Add `clearSystemFiles` capability if wanted.
[MJSONWP] Encountered internal error running command: Error: Could not find package com.android.chrome on the device
    at Object.wrappedLogger.errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:63:13)
    at AndroidDriver.checkPackagePresent$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-android-driver/lib/driver.js:392:11)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 621 ms - 192 
```

## Code To Reproduce Issue [ Good To Have ]

```java
 AndroidDriver driver;
//    protected String deviceName = ":5555";
//    protected String deviceName = "emulator-5554";

    @BeforeClass
    public void setUp() throws MalformedURLException {
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, Platform.ANDROID);
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "Google Nexus 5X");
//        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, deviceName);
        capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, MobileBrowserType.CHROME);
        capabilities.setCapability("chromedriverExecutable", "/Users/name/node_modules/appium-chromedriver/chromedriver/mac/chromedriver");
        driver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
        driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
    }

    @Test
    public void test() {
        driver.get("http://..........");
    }
```

**Comment by vaznoe** [comment]
for the android emulator the chrome browser open and close couple times

here is logs: https://gist.github.com/vaznoe/39c6c6f104dfb03d5a6813ac32341c27
<img width="360" alt="screen shot 2017-11-07 at 11 38 42 am" src="https://user-images.githubusercontent.com/17392464/32513864-4388a40a-c3b0-11e7-8dbb-72ee37f66eec.png">

**Comment by imurchie** [comment]
For the emulator issue, the logs are pretty clear: `Chrome version must be >= 60.0.3112.0`. See https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md

For the real device issue, is Chrome installed? What is it's package name?

**Comment by vaznoe** [comment]
this is emulator
yes, I read from here https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md and followed all instructions install appium-chromedriver, but it's still not working

**Comment by imurchie** [comment]
So you installed Appium with Chromedriver 2.22? Can you post the logs from the failing run with Chromedriver 2.22, as a link to a [gist](https://gist.github.com)?

**Comment by vaznoe** [comment]
yes I did install Appium with Chromedriver 2.23

**Comment by imurchie** [comment]
If you look at the table, Chromedriver 2.23 has a minimum Chrome version of 51.0.2704.0 and your emulator has Chrome version 51.0.2704.90. Chromedriver 2.22 is the latest version that can handle that Chrome.

**Comment by vaznoe** [comment]
I reinstalled Chromedriver 2.33 but it still doesn't work the same problem:
Genymotion emulator shown [AndroidDriver] Error: Could not find package com.android.chrome

**Comment by imurchie** [comment]
Is Chrome installed? What is the package?

**Comment by vaznoe** [comment]
the android emulator shown the same problem
I used chromedriver 2.33 but the chrome version shown 51.0.2704.90 it should be a minimum 60.0.3112.0
here is logs https://gist.github.com/vaznoe/5531874628fa4ae4ae2102c4511b28b3

**Comment by imurchie** [comment]
Yes. Changing the Chromedriver does not change the version of Chrome on the device. It just changes what it can automate. You either need to get a version of Chromedriver that can handle your Chrome version (2.22 or lower) or upgrade Chrome on the device.
