### ISSUE TITLE
Appium keeps unlocking device, but it seems it already unlocked

### ISSUE THREAD

**Issue by liuxuan30** [appium/appium#9602]
## The problem
I just installed appium v1.7.2-beta, and get a Red Mi 4X device which is flushed with an original Android 7.1.2 ROM. However after installing the app and turning off the screen, appium tries to unlock the screen, and it seems work, but the server keeps trying unlocking infinitely. However I already turned off screen lock, and when I am watching the device, it seems already unlocked, but appium just keeps trying.

If I manually click some button like "app" button, the server will realize unlocked.

If I manually run 
>adb -P 5037 -s 32ba64e20104 shell am start -W -n io.appium.unlock/.Unlock -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000

It seems hanging.

## Environment

* Appium version (or git revision) that exhibits the issue: v1.7.2-beta
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS 10.13.1
* Node.js version (unless using Appium.app|exe):v8.7.0
* Mobile platform/version under test: Android 7.1.2
* Real device or emulator/simulator: Red Mi 4X device
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.
## Link to Appium logs
```
[debug] [ADB] Running '/Users/xuanliu/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","32ba64e20104","shell","am","force-stop","io.appium.unlock"]
[AndroidBootstrap] Cannot shut down Android bootstrap; it has already shut down
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/xuanliu/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","32ba64e20104","shell","am","force-stop","io.appium.unlock"]
[debug] [ADB] Device API level: 25
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/xuanliu/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","32ba64e20104","shell","am","start","-W","-n","io.appium.unlock/.Unlock","-a","android.intent.action.MAIN","-c","android.intent.category.LAUNCHER","-f","0x10200000"]
[debug] [AndroidDriver] Not cleaning generated files. Add `clearSystemFiles` capability if wanted.
[debug] [ADB] Running '/Users/xuanliu/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","32ba64e20104","shell","am","start","-W","-n","io.appium.unlock/.Unlock","-a","android.intent.action.MAIN","-c","android.intent.category.LAUNCHER","-f","0x10200000"]
[ADB] Error: Error occured while starting App. Original error: Error executing adbExec. Original error: 'Command '/Users/xuanliu/Library/Android/sdk/platform-tools/adb -P 5037 -s 32ba64e20104 shell am start -W -n io.appium.unlock/.Unlock -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' timed out after 20000ms'; Stderr: ''; Code: 'null'
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at ADB.callee$0$0$ (../../../lib/tools/apk-utils.js:101:9)
    at tryCatch (/Users/xuanliu/aa/development/appium/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/xuanliu/aa/development/appium/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/xuanliu/aa/development/appium/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/xuanliu/aa/development/appium/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
 Error: Error occured while starting App. Original error: Error executing adbExec. Original error: 'Command '/Users/xuanliu/Library/Android/sdk/platform-tools/adb -P 5037 -s 32ba64e20104 shell am start -W -n io.appium.unlock/.Unlock -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' timed out after 20000ms'; Stderr: ''; Code: 'null'
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at ADB.callee$0$0$ (../../../lib/tools/apk-utils.js:101:9)
    at tryCatch (/Users/xuanliu/aa/development/appium/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/xuanliu/aa/development/appium/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/xuanliu/aa/development/appium/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/xuanliu/aa/development/appium/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
[debug] [AndroidDriver] Screen is locked, trying to unlock
[AndroidDriver] Using app unlock, this is going to be deprecated!
[AndroidDriver] Unlocking screen
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/xuanliu/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","32ba64e20104","shell","am","force-stop","io.appium.unlock"]
[debug] [ADB] Device API level: 25
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/xuanliu/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","32ba64e20104","shell","am","start","-W","-n","io.appium.unlock/.Unlock","-a","android.intent.action.MAIN","-c","android.intent.category.LAUNCHER","-f","0x10200000"]
[debug] [ADB] Device API level: 25
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/xuanliu/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","32ba64e20104","shell","am","start","-W","-n","io.appium.unlock/.Unlock","-a","android.intent.action.MAIN","-c","android.intent.category.LAUNCHER","-f","0x10200000"]
[debug] [ADB] Running '/Users/xuanliu/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","32ba64e20104","shell","am","start","-W","-n","io.appium.unlock/.Unlock","-a","android.intent.action.MAIN","-c","android.intent.category.LAUNCHER","-f","0x10200000"]
[ADB] Error: Error occured while starting App. Original error: Error executing adbExec. Original error: 'Command '/Users/xuanliu/Library/Android/sdk/platform-tools/adb -P 5037 -s 32ba64e20104 shell am start -W -n io.appium.unlock/.Unlock -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' timed out after 20000ms'; Stderr: ''; Code: 'null'
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at ADB.callee$0$0$ (../../../lib/tools/apk-utils.js:101:9)
    at tryCatch (/Users/xuanliu/aa/development/appium/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/xuanliu/aa/development/appium/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/xuanliu/aa/development/appium/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/xuanliu/aa/development/appium/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
 Error: Error occured while starting App. Original error: Error executing adbExec. Original error: 'Command '/Users/xuanliu/Library/Android/sdk/platform-tools/adb -P 5037 -s 32ba64e20104 shell am start -W -n io.appium.unlock/.Unlock -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' timed out after 20000ms'; Stderr: ''; Code: 'null'
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at ADB.callee$0$0$ (../../../lib/tools/apk-utils.js:101:9)
    at tryCatch (/Users/xuanliu/aa/development/appium/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/xuanliu/aa/development/appium/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/xuanliu/aa/development/appium/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/xuanliu/aa/development/appium/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
[debug] [AndroidDriver] Screen is locked, trying to unlock
[AndroidDriver] Using app unlock, this is going to be deprecated!
[AndroidDriver] Unlocking screen
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/xuanliu/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","32ba64e20104","shell","am","force-stop","io.appium.unlock"]
[debug] [ADB] Device API level: 25
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/xuanliu/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","32ba64e20104","shell","am","start","-W","-n","io.appium.unlock/.Unlock","-a","android.intent.action.MAIN","-c","android.intent.category.LAUNCHER","-f","0x10200000"]
[debug] [ADB] Device API level: 25
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/xuanliu/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","32ba64e20104","shell","am","start","-W","-n","io.appium.unlock/.Unlock","-a","android.intent.action.MAIN","-c","android.intent.category.LAUNCHER","-f","0x10200000"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/xuanliu/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","32ba64e20104","shell","dumpsys","window"]
[debug] [AndroidDriver] Screen unlocked successfully
[debug] [ADB] Device API level: 25
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/xuanliu/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","32ba64e20104","shell","am","start","-W","-n","com.facebook.katana/com.facebook.katana.LoginActivity","-S","-a","android.intent.action.MAIN","-c","android.intent.category.LAUNCHER","-f","0x10200000"]
```

**Comment by mykola-mokhnach** [comment]
Set _skipUnlock_ capability to true. Or you can also push a PR to fix the unlock utility

**Comment by liuxuan30** [comment]
can you point out where is the unlock utility? I can take a look and try

**Comment by mykola-mokhnach** [comment]
Sure, here it is: https://github.com/appium/unlock_apk

**Comment by liuxuan30** [comment]
hi @mykola-mokhnach just a newbie question,
```
[BaseDriver] Capability 'noReset' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by appium: skipUnlock.
[BaseDriver] Session created with session id: 28a4bfba-9c43-4c66-82a9-7ae6a67b827b

```
I saw this log, and my code is 
```python
        desired_caps['noReset'] = 'true'
        desired_caps['skipUnlock'] = 'true'
```
did I miss anything?

**Comment by liuxuan30** [comment]
Just found https://github.com/appium/appium/issues/8950
seems it's not about the unlock app, but android 7.1.2?

**Comment by mykola-mokhnach** [comment]
The skipUnlock capability has been added to just recently. Make sure your beta is up to date.
Regarding unlock and Android versions - it might be, that it's not supported anymore in the never OS versions, which the second argument to update the utility and create a PR for it.

**Comment by liuxuan30** [comment]
Thanks. I have switched to uiautomator2, seems faster and stable :)

**Comment by mykola-mokhnach** [comment]
Good, shall this issue be closed?

**Comment by liuxuan30** [comment]
sure
