### ISSUE TITLE
runAppInBackground(duration) doesn't work on appium 1.7.1 Java Client 5.0.4

### ISSUE THREAD

**Issue by EitanBe** [appium/appium#9623]
## The problem

call to runAppInBackground(duration) throw exception:

org.openqa.selenium.NoSuchSessionException: A session is either terminated or not started (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:42:44.417Z'
System info: host: 'MY MACHINE', ip: 'IP', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_144'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{networkConnectionEnabled=false, xcodeOrgId=BLA BLA, bundleId=XXX.XXX.YYY, databaseEnabled=false, deviceName=iphone 5C, xcodeSigningId=iPhone Developer, platform=MAC, wdaLocalPort=8209, platformVersion=10.3, webStorageEnabled=false, locationContextEnabled=false, automationName=XCuiTest, useNewWDA=true, browserName=, takesScreenshot=true, waitForAppScript=if (target.frontMostApp().alert().name()=='"app" Would Like to Send You Notifications') {$.acceptAlert(); true;}, javascriptEnabled=true, udid=UDID, platformName=MAC, autoAcceptAlerts=true}]
Session ID: e8de91a7-7be5-4798-883a-c185920c1127

    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:167)
    at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
    at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:82)
    at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:45)
    at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
    at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:89)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:646)
    at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
    at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
    at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
    at io.appium.java_client.ios.IOSDriver.runAppInBackground(IOSDriver.java:170)

## Environment

* Appium 1.7.1
* Java-client - 5.0.4
* Mac
* IOS version: 10
* Java - 1.8.0_144

## Details

In my scenario i need to move application to background.
On Android it worked as expected, however in IOS i got the exception

## Link to Appium logs

org.openqa.selenium.NoSuchSessionException: A session is either terminated or not started (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:42:44.417Z'
System info: host: 'MY MACHINE', ip: 'IP', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_144'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{networkConnectionEnabled=false, xcodeOrgId=BLA BLA, bundleId=XXX.XXX.YYY, databaseEnabled=false, deviceName=iphone 5C, xcodeSigningId=iPhone Developer, platform=MAC, wdaLocalPort=8209, platformVersion=10.3, webStorageEnabled=false, locationContextEnabled=false, automationName=XCuiTest, useNewWDA=true, browserName=, takesScreenshot=true, waitForAppScript=if (target.frontMostApp().alert().name()=='"app" Would Like to Send You Notifications') {$.acceptAlert(); true;}, javascriptEnabled=true, udid=UDID, platformName=MAC, autoAcceptAlerts=true}]
Session ID: e8de91a7-7be5-4798-883a-c185920c1127

    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:167)
    at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
    at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:82)
    at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:45)
    at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
    at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:89)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:646)
    at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
    at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
    at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
    at io.appium.java_client.ios.IOSDriver.runAppInBackground(IOSDriver.java:170)

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]
device.getDriver().runAppInBackground(Duration.ofSeconds(durationInScenond));

**Comment by mykola-mokhnach** [comment]
Please attach the server log

**Comment by EitanBe** [comment]
Actually i found that only on specific mac it doesn't work.
close the issue.
Thanks
