### ISSUE TITLE
Unable to get password attribute of an element

### ISSUE THREAD

**Issue by uarlouski** [appium/appium#9637]
## The problem

Unable to get password attribute of an element
element.getAttribute("password"), exception message is strange because element exists and interaction with it continues during the test

## Environment

* Appium versions: 1.6.5/1.7.1
* Desktop OS/version: MacOS Sierra 10.12.6
* Mobile platform/version: Android 5.1
* Device: Nexus 6 API 22 Emulator

## Exception
org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:42:44.417Z'
System info: host: 'EPBYMINW3828', ip: 'fe80:0:0:0:41:b4d:658b:b860%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_131'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{appPackage=*******, deviceName=emulator-5554, platform=ANDROID, deviceUDID=emulator-5554, desired={app=*******, appPackage=*********, screen-resolution=, commandTimeout=180, recordVideo=true, protocolType=OSS, deviceName=Android Emulator, platform=ANDROID, tags=[group=Login, layout=native], appActivity=**********, idleTimeout=360, platformVersion=5.1, name=dummy, browserName=, deviceOrientation=portrait, platformName=Android, recordScreenshots=true, maxDuration=10800}, platformVersion=5.1.1, webStorageEnabled=false, takesScreenshot=true, browserName=, javascriptEnabled=true, recordScreenshots=true, deviceManufacturer=unknown, platformName=ANDROID, app=***********, deviceScreenSize=1440x2560, networkConnectionEnabled=true, screen-resolution=, warnings={}, commandTimeout=180, recordVideo=true, protocolType=OSS, databaseEnabled=false, tags=[group=Login, layout=native], appActivity=************, idleTimeout=360, locationContextEnabled=false, name=dummy, deviceOrientation=portrait, deviceModel=Android SDK built for x86, maxDuration=10800}]
Session ID: 6b43a8b3-bd8c-4e8e-9e21-f58fa8498703
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:167)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:82)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:45)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:89)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:646)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:275)
	at io.appium.java_client.DefaultGenericMobileElement.execute(DefaultGenericMobileElement.java:45)
	at io.appium.java_client.MobileElement.execute(MobileElement.java:1)
	at io.appium.java_client.android.AndroidElement.execute(AndroidElement.java:1)
	at org.openqa.selenium.remote.RemoteWebElement.getAttribute(RemoteWebElement.java:127)

## Element source code
<android.widget.EditText NAF="true" index="0" text="" class="android.widget.EditText" package="******" content-desc="" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="true" scrollable="false" long-clickable="true" password="true" selected="false" bounds="[56,1142][1384,1310]" resource-id="********/registration_password_input" instance="3"/>

## Link to Appium logs
[HTTP] --> GET /wd/hub/session/6b43a8b3-bd8c-4e8e-9e21-f58fa8498703/element/5/attribute/password {}
[debug] [MJSONWP] Calling AppiumDriver.getAttribute() with args: ["password","5","6b43a8b3-bd8c-4e8e-9e21-f58fa8498703"]
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:getAttribute","params":{"attribute":"password","elementId":"5"}}
[debug] [AndroidBootstrap] Received command result from bootstrap
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:getAttribute","params":{"attribute":"password","elementId":"5"}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: getAttribute
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":7,"value":"This element does not have the 'password' attribute"}
[HTTP] <-- GET /wd/hub/session/6b43a8b3-bd8c-4e8e-9e21-f58fa8498703/element/5/attribute/password 500 9 ms - 164

**Comment by mykola-mokhnach** [comment]
> [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":7,"value":"This element does not have the 'password' attribute"}

I assume the text of the error is quite clear

**Comment by uarlouski** [comment]
But as we see in page source there is password attribute
<android.widget.EditText NAF="true" index="0" text="" class="android.widget.EditText" package="" content-desc="" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="true" scrollable="false" long-clickable="true" password="true" selected="false" bounds="[56,1142][1384,1310]" resource-id="**/registration_password_input" instance="3"/>

**Comment by mykola-mokhnach** [comment]
This attribute is only present in the xml source, but is not implemented for getAttribute call

**Comment by mykola-mokhnach** [comment]
The fix has been merged to Appium beta
