### ISSUE TITLE
Android Chrome Buttons Does not Clicks or Taps.

### ISSUE THREAD

**Issue by vladbelo** [appium/appium#9654]
## The problem

I'm trying to click on Button but It does not work I was able to click on links and texts but not BUTTONS.

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable): 1.7.1
* Desktop OS/version used to run Appium: MacOS Sieera
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: 7.0 
* Real device or emulator/simulator:  Real Galaxy s8
* Appium CLI or Appium.app|exe: appium.app

## Link to Appium logs

[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/Users/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","9887fc35525a485333","shell","dumpsys","input_method"]
[AndroidBootstrap] Sending command to android: {"cmd":"action","action":"pressBack","params":{}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"pressBack","params":{}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: pressBack
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":true}
[AndroidBootstrap] Received command result from bootstrap
[MJSONWP] Responding to client with driver.hideKeyboard() result: true
[HTTP] <-- POST /wd/hub/session/10923751-6fb6-48d1-b61d-50be29f84770/appium/device/hide_keyboard 200 598 ms - 76 
[HTTP] --> POST /wd/hub/session/10923751-6fb6-48d1-b61d-50be29f84770/timeouts {"type":"implicit","ms":30000}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Proxying [POST /wd/hub/session/10923751-6fb6-48d1-b61d-50be29f84770/timeouts] to [POST http://127.0.0.1:8000/wd/hub/session/88cd626a21df604a45e20a5c62f061df/timeouts] with body: {"type":"implicit","ms":30000}
[JSONWP Proxy] Got response with status 200: {"sessionId":"88cd626a21df604a45e20a5c62f061df","status":0,"value":null}
[JSONWP Proxy] Replacing sessionId 88cd626a21df604a45e20a5c62f061df with 10923751-6fb6-48d1-b61d-50be29f84770
[HTTP] <-- POST /wd/hub/session/10923751-6fb6-48d1-b61d-50be29f84770/timeouts 200 8 ms - 76 
[HTTP] --> POST /wd/hub/session/10923751-6fb6-48d1-b61d-50be29f84770/element {"using":"xpath","value":"//*[@id='shopTires']"}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Proxying [POST /wd/hub/session/10923751-6fb6-48d1-b61d-50be29f84770/element] to [POST http://127.0.0.1:8000/wd/hub/session/88cd626a21df604a45e20a5c62f061df/element] with body: {"using":"xpath","value":"//*[@id='shopTires']"}
[JSONWP Proxy] Got response with status 200: {"sessionId":"88cd626a21df604a45e20a5c62f061df","status":0,"value":{"ELEMENT":"0.9252347175112223-7"}}
[JSONWP Proxy] Replacing sessionId 88cd626a21df604a45e20a5c62f061df with 10923751-6fb6-48d1-b61d-50be29f84770
[HTTP] <-- POST /wd/hub/session/10923751-6fb6-48d1-b61d-50be29f84770/element 200 103 ms - 106 
[HTTP] --> POST /wd/hub/session/10923751-6fb6-48d1-b61d-50be29f84770/element {"using":"xpath","value":"//*[@id='shopTires']"}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Proxying [POST /wd/hub/session/10923751-6fb6-48d1-b61d-50be29f84770/element] to [POST http://127.0.0.1:8000/wd/hub/session/88cd626a21df604a45e20a5c62f061df/element] with body: {"using":"xpath","value":"//*[@id='shopTires']"}
[JSONWP Proxy] Got response with status 200: {"sessionId":"88cd626a21df604a45e20a5c62f061df","status":0,"value":{"ELEMENT":"0.9252347175112223-7"}}
[JSONWP Proxy] Replacing sessionId 88cd626a21df604a45e20a5c62f061df with 10923751-6fb6-48d1-b61d-50be29f84770
[HTTP] <-- POST /wd/hub/session/10923751-6fb6-48d1-b61d-50be29f84770/element 200 70 ms - 106 
[HTTP] --> POST /wd/hub/session/10923751-6fb6-48d1-b61d-50be29f84770/element/0.9252347175112223-7/click {"id":"0.9252347175112223-7"}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Proxying [POST /wd/hub/session/10923751-6fb6-48d1-b61d-50be29f84770/element/0.9252347175112223-7/click] to [POST http://127.0.0.1:8000/wd/hub/session/88cd626a21df604a45e20a5c62f061df/element/0.9252347175112223-7/click] with body: {"id":"0.9252347175112223-7"}
[JSONWP Proxy] Got response with status 200: {"sessionId":"88cd626a21df604a45e20a5c62f061df","status":13,"value":{"message":"unknown error: Element is not clickable at point (180, 630)\n  (Session info: chrome=62.0.3202.84)\n  (Driver info: chromedriver=2.30.477690 (c53f4ad87510ee97b5c3425a14c0e79780cdf262),platform=Mac OS X 10.12.6 x86_64)"}}
[JSONWP Proxy] Replacing sessionId 88cd626a21df604a45e20a5c62f061df with 10923751-6fb6-48d1-b61d-50be29f84770
[HTTP] <-- POST /wd/hub/session/10923751-6fb6-48d1-b61d-50be29f84770/element/0.9252347175112223-7/click 200 233 ms - 304 

## Code To Reproduce Issue [ Good To Have ]

I tried Different WAYS TO DO IT, Couldnt Figure Out.  Could
public void clickShopTires() {
		System.out.println("Click all Tires");
		//<a id="shopTires" href="javascript:void(0);" class="btn btn-green shopTires at_shop_tires">
        //<span class="text">Shop tires</span>
      //  <i class="fa fa-chevron-right"></i>  </a>
		//driver.findElementByXPath("//span[contains(., \"" + shopTires + "\")]").click();
		WebElement vova = (WebElement) driver.findElementByXPath("//*[@id='shopTires']");
		TouchAction ta = new TouchAction(driver);
		ta.longPress(vova);
		//WebElement vova = (WebElement) driver.findElementByXPath("//*[@id='shopTires']");
		driver.findElement(By.xpath("//*[@id='shopTires']")).click();
		WebElement elementToClick = driver.findElement(By.xpath("//*[@id='shopTires']"));
		Actions actions = new Actions(driver);
		new WebDriverWait(driver, 60).until(ExpectedConditions.visibilityOf(vova));
		actions.moveToElement(elementToClick).click().build().perform();

FAILED: addANumber
org.openqa.selenium.WebDriverException: unknown error: Element is not clickable at point (180, 630)
  (Session info: chrome=62.0.3202.84)
  (Driver info: chromedriver=2.30.477690 (c53f4ad87510ee97b5c3425a14c0e79780cdf262),platform=Mac OS X 10.12.6 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 237 milliseconds
Build info: version: '2.52.0', revision: '4c2593cfc3689a7fcd7be52549167e5ccc93ad28', time: '2016-02-11 11:22:43'
System info: host: 'AMAC02T90QRGTFM', ip: '192.168.14.180', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_144'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{deviceScreenSize=1440x2960, networkConnectionEnabled=true, warnings={}, databaseEnabled=false, deviceName=9887fc35525a485333, platform=LINUX, deviceUDID=9887fc35525a485333, desired={platformVersion=7.0, browserName=Chrome, platformName=Android, deviceName=Vovchik}, platformVersion=7.0, webStorageEnabled=false, locationContextEnabled=false, takesScreenshot=true, browserName=Chrome, javascriptEnabled=true, deviceModel=SM-G950U, platformName=Android, deviceManufacturer=samsung}]
Session ID: 10923751-6fb6-48d1-b61d-50be29f84770
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:327)
	at io.appium.java_client.DefaultGenericMobileElement.execute(DefaultGenericMobileElement.java:44)
	at io.appium.java_client.MobileElement.execute(MobileElement.java:1)
	at io.appium.java_client.android.AndroidElement.execute(AndroidElement.java:1)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:85)
	at com.appium.MobileWeb.Page_Objects.clickShopTires(Page_Objects.java:103)
	at com.appium.MobileWeb.TireBuyer.addANumber(TireBuyer.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

===============================================
    Default test
    Tests run: 1, Failures: 1, Skips: 0
===============================================

===============================================
Default suite
Total tests run: 1, Failures: 1, Skips: 0
===============================================

[TestNG] Time taken by org.testng.reporters.jq.Main@7a5d012c: 26 ms
[TestNG] Time taken by [FailedReporter passed=0 failed=0 skipped=0]: 4 ms
[TestNG] Time taken by org.testng.reporters.XMLReporter@13fee20c: 12 ms
[TestNG] Time taken by org.testng.reporters.JUnitReportReporter@246ae04d: 3 ms
[TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@21bcffb5: 10 ms
[TestNG] Time taken by org.testng.reporters.EmailableReporter@735f7ae5: 4 ms

**Comment by mykola-mokhnach** [comment]
`Element is not clickable at point` this is the error that chromedriver itself generated and I don't thing it has to do anything with Appium. Perhaps, your buttons are covered with some transparent layer, which intercepts clicks.

**Comment by vladbelo** [comment]
Also How do you scroll down to text in Chrome  Android. I tried android.scrollTo(); didn't work.

**Comment by mykola-mokhnach** [comment]
Inside web context you work directly with chromedriver. appium just acts as a proxy there. So all the commands, that chromedriver itself supports, should work there as well
