### ISSUE TITLE
Original error: Error in waiting for device. Original error: 'Error executing adbExec.

### ISSUE THREAD

**Issue by manojmastiff** [appium/appium#9664]
## The problem

I'm trying to execute a simple and basic appium program, but I'm getting the following exception. I have been struggling with the fix since two days. Im getting the following issue:

**Exception in thread "main" org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error in waiting for device. Original error: 'Error executing adbExec. Original error: 'Command 'C\:\\Users\\IT\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 wait-for-device' timed out after 10000ms'; Stderr: ''; Code: 'null''. Retrying by restarting ADB (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 74.46 seconds**

## Environment
Windows 10 Pro 64x
Appium version 1.6.5
Appium java client 5.0.4
Selenium Standalone jar 3.7.1
Java 9.0.1
Android studio 3.0
Virtual Device: 1080 × 1920: 420dpi | 25 | Android 7.1.1 (Google Play) | x86 | 2 GB |
Eclipse: Oxygen

## Details

Eclipse log:
Exception in thread "main" org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error in waiting for device. Original error: 'Error executing adbExec. Original error: 'Command 'C\:\\Users\\IT\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 wait-for-device' timed out after 10000ms'; Stderr: ''; Code: 'null''. Retrying by restarting ADB (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 74.46 seconds
Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:07:36.161Z'
System info: host: 'L-7WK3MJ2', ip: '192.168.43.71', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '9.0.1'
Driver info: driver.version: AndroidDriver
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$new$0(JsonWireProtocolResponse.java:53)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$getResponseFunction$2(JsonWireProtocolResponse.java:91)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)

## Link to Appium logs

C:\Users\IT>appium
[Appium] Welcome to Appium v1.6.5
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"C:\\Users\\IT\\eclipse-workspace\\DemoApp\\src\\ApiDemos-debug.apk","deviceName":"LKAndroidEmulator","platformName":"Android"},"capabilities":{"desiredCapabilities":{"app":"C:\\Users\\IT\\eclipse-workspace\\DemoApp\\src\\ApiDemos-debug.apk","deviceName":"LKAndroidEmulator","platformName":"Android"},"firstMatch":[{"platformName":"android"}]}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"C:\\Users\\IT\\eclipse-workspace\\DemoApp\\src\\ApiDemos-debug.apk","deviceName":"LKAndroidEmulator","platformName":"Android"},null,{"desiredCapabilities":{"app":"C:\\Users\\IT\\eclipse-workspace\\DemoApp\\src\\ApiDemos-debug.apk","deviceName":"LKAndroidEmulator","platformName":"Android"},"firstMatch":[{"platformName":"android"}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1511091618274 (17:10:18 GMT+0530 (India Standard Time))
[Appium] Creating new AndroidDriver (v1.20.0) session
[Appium] Capabilities:
[Appium]   app: 'C:\\Users\\IT\\eclipse-workspace\\DemoApp\\src\\ApiDemos-debug.apk'
[Appium]   deviceName: 'LKAndroidEmulator'
[Appium]   platformName: 'Android'
[debug] [AndroidDriver] AndroidDriver version: 1.20.0
[BaseDriver] Session created with session id: 72ed04d8-e1c4-4b48-84e4-bffc7b09b916
[debug] [AndroidDriver] Getting Java version
[AndroidDriver] Java version is: 9.0.1
[ADB] Checking whether adb is present
[ADB] Using adb.exe from C:\Users\IT\AppData\Local\Android\Sdk\platform-tools\adb.exe
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[AndroidDriver] Using device: emulator-5554
[ADB] Checking whether adb is present
[ADB] Using adb.exe from C:\Users\IT\AppData\Local\Android\Sdk\platform-tools\adb.exe
[debug] [ADB] Setting device id to emulator-5554
[BaseDriver] Using local app 'C:\Users\IT\eclipse-workspace\DemoApp\src\ApiDemos-debug.apk'
[debug] [AndroidDriver] Checking whether app is actually present
[AndroidDriver] Starting Android session
[debug] [ADB] Running 'C:\Users\IT\AppData\Local\Android\Sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","wait-for-device"]
[debug] [ADB] Running 'C:\Users\IT\AppData\Local\Android\Sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","wait-for-device"]
[debug] [ADB] Restarting adb
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[ADB] Error: Error in waiting for device. Original error: 'Error executing adbExec. Original error: 'Command 'C\:\\Users\\IT\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 wait-for-device' timed out after 10000ms'; Stderr: ''; Code: 'null''. Retrying by restarting ADB
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at ADB.callee$1$0$ (../../../lib/tools/system-calls.js:520:11)
    at tryCatch (C:\Users\IT\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\IT\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\IT\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\IT\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 Error: Error in waiting for device. Original error: 'Error executing adbExec. Original error: 'Command 'C\:\\Users\\IT\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 wait-for-device' timed out after 10000ms'; Stderr: ''; Code: 'null''. Retrying by restarting ADB
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at ADB.callee$1$0$ (../../../lib/tools/system-calls.js:520:11)
    at tryCatch (C:\Users\IT\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\IT\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\IT\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\IT\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

## Code To Reproduce Issue [ Good To Have ]

package com.and;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import org.openqa.selenium.remote.DesiredCapabilities;

import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.android.AndroidElement;
import io.appium.java_client.remote.MobileCapabilityType;

public class DesriedCap {
	
	public static void main(String[] args) throws MalformedURLException {
		// TODO Auto-generated method stub
		
		File file = new File("src");
		File fs = new File(file, "ApiDemos-debug.apk");
		
		DesiredCapabilities cap = new DesiredCapabilities();
		//Invoke Emulator
		
		cap.setCapability(MobileCapabilityType.DEVICE_NAME, "LKAndroidEmulator");
		//cap.setCapability(MobileCapabilityType.PLATFORM_VERSION, "7.1.1");
		//cap.setCapability(MobileCapabilityType.PLATFORM_NAME,"ANDROID");
		//Invoke apk
		cap.setCapability(MobileCapabilityType.APP, fs.getAbsolutePath());
		
	AndroidDriver<AndroidElement> driver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"), cap);
	}

}

Please help me fix this issue.

**Comment by mykola-mokhnach** [comment]
Use `avd` capability in order to set emulator name.

**Comment by manojmastiff** [comment]
@mykola-mokhnach I'm new to appium. Please help me how to use "avd capability". It would be great if you help me. I googled "how to..." but didn't find any helpful post. Thanks in advance.

**Comment by manojmastiff** [comment]
Hi @mykola-mokhnach 
I used this line in my code

cap.setCapability("avd","LKAndroidEmulator");
cap.setCapability(MobileCapabilityType.DEVICE_NAME, "LKAndroidEmulator");

still same error. 

Environment variable is also set 
![android home](https://user-images.githubusercontent.com/6522287/32991008-a1fc9dd6-cd59-11e7-8d5e-e13e31bbda21.png)

**Comment by manojmastiff** [comment]
I changed my Emulator and it's working fine now. Thanks @mykola-mokhnach
