### ISSUE TITLE
Appium 1.7.1 - Error: Xcode version 9.1 is not yet supported

### ISSUE THREAD

**Issue by anton6** [appium/appium#9665]
## The problem

After upgrading to **Xcode 9.1** I am getting "Encountered internal error running command: Error: Xcode version 9.1 is not yet supported" when starting appium.

Worked fine with Xcode 8.3.3.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: macOS High Sierra 10.13
* Node.js version (unless using Appium.app|exe): v8.1.2
* Mobile platform/version under test: iPhone 5s, iOS 11.1
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Appium CLI

## Details

The error is clear, but is it legitimate? So Appium 1.7.1 really does not support Xcode 9.1? I couldn't find this info in docs. Is there a workaround for this?

Thanks

**Comment by shynkevich-alex** [comment]
try beta appium

**Comment by anton6** [comment]
I now installed Appium v1.7.2-beta2.

But when trying to run the test I am getting the same error message as before:

`
[XCUITest] Error: Xcode version 9.1 is not yet supported
    at handleUnsupportedXcode (/Users/anton/Development/common/TestSource/node_modules/appium/node_modules/appium-ios-simulator/lib/simulator.js:16:11)
    at getSimulator$ (/Users/anton/Development/common/TestSource/node_modules/appium/node_modules/appium-ios-simulator/lib/simulator.js:28:3)
    at tryCatch (/Users/anton/Development/common/TestSource/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/anton/Development/common/TestSource/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/anton/Development/common/TestSource/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/anton/Development/common/TestSource/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
 Error: Xcode version 9.1 is not yet supported
    at handleUnsupportedXcode (/Users/anton/Development/common/TestSource/node_modules/appium/node_modules/appium-ios-simulator/lib/simulator.js:16:11)
    at getSimulator$ (/Users/anton/Development/common/TestSource/node_modules/appium/node_modules/appium-ios-simulator/lib/simulator.js:28:3)
    at tryCatch (/Users/anton/Development/common/TestSource/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/anton/Development/common/TestSource/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/anton/Development/common/TestSource/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/anton/Development/common/TestSource/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
`
Any idea what is happening? Thanks.

**Comment by HenningThiemann** [comment]
@mykola-mokhnach I think this should be reopened as there is no suitable solution

**Comment by imurchie** [comment]
Everything under Xcode 10 should now be supported (see the check for version here: https://github.com/appium/appium-ios-simulator/blob/master/lib/simulator.js#L16). This has been the case since June.
