### ISSUE TITLE
Failed to dismiss alert message when desired capabilities "autoAcceptAlerts" is set to True

### ISSUE THREAD

**Issue by BoazWarshawsky** [appium/appium#9666]
## The problem
When my application is launching **as expected** I am getting the following alert:
![img_0105](https://user-images.githubusercontent.com/32813176/33008201-d477f9fa-cdda-11e7-8de7-a25864ceb743.PNG)

and my problem it is that its not dismiss when I asked in desired capabilities that "autoAcceptAlerts" will be true.
I must say that at least 1 other message does dismisses successfully.

## Environment

* Appium version 1.7.1
* Last Appium version that did not exhibit the issue: first time I get trying
* Desktop OS/version used to run Appium: Mac Sierra High
* Node.js version (unless using Appium.app|exe): v6.11.4
* Mobile platform/version under test: iOS 11.0
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

**Comment by mykola-mokhnach** [comment]
`autoAcceptAlerts` capability is not supported by xcuitest driver. You must handle all alerts manually.

**Comment by BoazWarshawsky** [comment]
Does the handling is different between Android and iOS?

**Comment by BoazWarshawsky** [comment]
Your advice for dismissing the alerts manually works for me with other alerts, but the alert in the attachment not working:
I am running:
self.driver.switch_to.alert.dismiss()

and getting the following error:
Error
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 322, in run
    self.setUp()
  File "/Users/boazw/workspace/PyCharm/ApplicasterTestsUtils/framework/common/base_test.py", line 30, in setUp
    self.driver.dismiss_all_alerts()
  File "/Users/boazw/workspace/PyCharm/ApplicasterTestsUtils/framework/appium/appium_web_driver.py", line 133, in dismiss_all_alerts
    self.driver.switch_to.alert.dismiss()
  File "/Library/Python/2.7/site-packages/selenium-3.6.0-py2.7.egg/selenium/webdriver/common/alert.py", line 78, in dismiss
    self.driver.execute(Command.DISMISS_ALERT)
  File "/Library/Python/2.7/site-packages/selenium-3.6.0-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "build/bdist.macosx-10.12-intel/egg/appium/webdriver/errorhandler.py", line 29, in check_response
    raise wde
NoAlertPresentException: Message: {}

**Comment by mykola-mokhnach** [comment]
Check the page source if this alert element is there. It might the alert is generated by some third-party service. In such case it will not be visible to your application and this is known XCTest limitation.

**Comment by BoazWarshawsky** [comment]
Yes, it was not there.
and actually this alert keep showing also when I close the application so it seems to be thrid party one.
