### ISSUE TITLE
I am getting this error while launching an application

### ISSUE THREAD

**Issue by sachi041** [appium/appium#9670]
## The problem

Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{app=C:\Users\Sachin\workspace\sachin\src\ApiDemos-debug.apk, platformName=Android, deviceName=sachin}], required capabilities = Capabilities [{}]
Build info: version: 'unknown', revision: '5234b32', time: '2017-03-10 09:00:17 -0800'
System info: host: 'LAPTOP-AHLOQDNJ', ip: '192.168.0.101', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_151'
Driver info: driver.version: AndroidDriver
	at io.appium.java_client.remote.AppiumProtocolHandShake.lambda$1(AppiumProtocolHandShake.java:95)
	at java.util.Optional.orElseThrow(Unknown Source)
	at io.appium.java_client.remote.AppiumProtocolHandShake.createSession(AppiumProtocolHandShake.java:95)
	at io.appium.java_client.remote.AppiumCommandExecutor.doExecute(AppiumCommandExecutor.java:111)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:162)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:604)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:244)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:88)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:112)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:73)
	at `sachin.base.main(base.java:24)`

## Environment

* Appium version (or git revision) that exhibits the issue:  Appium v1.7.1
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium:Windows 10 AMD 
* Node.js version (unless using Appium.app|exe): 8.9.1
* Mobile platform/version under test: 7.0
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: Installed from node.js
*  selenium-java-3.3.1
*  java-client-5.0.0-BETA6.jar

## Details

I am not able to launch the application with the below code. Application is not launching after running the code. 

## Link to Appium logs

https://gist.github.com/fb146bda37fc6f9782ef739e1dc40bb0.git

## Code To Reproduce Issue [ Good To Have ]
package sachin;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import org.openqa.selenium.remote.DesiredCapabilities;

import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.android.AndroidElement;
import io.appium.java_client.remote.MobileCapabilityType;

public class base {

	public static void main(String[] args) throws MalformedURLException {
		// TODO Auto-generated method stub
		
		File f = new File("src");
		File fs= new File(f,"ApiDemos-debug.apk");

 DesiredCapabilities cap = new DesiredCapabilities();
	cap.setCapability(MobileCapabilityType.DEVICE_NAME, "sachin");
	cap.setCapability(MobileCapabilityType.APP, fs.getAbsolutePath());
	AndroidDriver<AndroidElement> driver=new AndroidDriver<>(new URL("http://127.0.0.1:4723/wd/hub"),cap);
	
	}

}

**Comment by mykola-mokhnach** [comment]
Remove Appium Unlock application from the device manually

**Comment by sachi041** [comment]
Hi mykola-mokhnach Thanks for the reply. But still i am getting the same error message which i said in my 1st comment. In my case when i ran the program both unlock and appium settings got installed but app is not launching. I am getting the same session initiation error. Kindly help me to fix this issue.

**Comment by mykola-mokhnach** [comment]
Update java client and selenium lib to the most recent versions
