### ISSUE TITLE
Using jenkins to start appium server remotely and executing iOS automation will crash

### ISSUE THREAD

**Issue by darkmanno6** [appium/appium#9705]
## The problem

Using jenkins to start appium remotely and executing iOS automation will crash

## Environment

* Appium version : v1.7.1
* iwdp version: ios_webkit_debug_proxy 1.8,Built with libimobiledevice v1.2.1, libplist v2.0.0
* Desktop OS/version used to run Appium:Mac 10.12.6
* Node.js version: v6.11.4
* Mobile platform/version under test: iPhone 6sp iOS 11.0.3
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

first I set capabilities `capabilities.setCapability("startIWDP", true);`
then I use jenkins or ssh(by using JSch ) to  start appium server remotely and start executing iOS automation. when the test Started IWDP, the appium server was crashed, you can watch the logs below;
But, when I set capabilities `capabilities.setCapability("startIWDP", false);`
the the appium server won't be crashed.
pls help me out. thx!!!

## Link to Appium logs
```log
2017-11-27 17:41:52:253 - [debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1511775712253 (17:41:52 GMT+0800 (CST))
2017-11-27 17:41:52:254 - [debug] [XCUITest] Sending createSession command to WDA
2017-11-27 17:41:52:256 - [debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.xxx.xxx","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
ldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"should
UseSingletonTestManager":true}}
2017-11-27 17:41:54:781 - [HTTP] --> GET /wd/hub/status {}
2017-11-27 17:41:54:782 - [debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
2017-11-27 17:41:54:795 - [debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.7.1","revision":"0a95e77000515c1156be593642dd4e452f2f098e"}}
2017-11-27 17:41:54:797 - [HTTP] <-- GET /wd/hub/status 200 14 ms - 121
2017-11-27 17:41:58:650 - [debug] [JSONWP Proxy] Got response with status 200: {"value":{"sessionId":"D539F7A4-92E1-4788-AE7C-977E140265BD","capabilities":{"device":"iphone","browserName":"xxx","sdkVersion":"11.0.3","CFBundleIdentifier":"com.xxx.xxx"}},"sessionId":"D539F7A4-92E1-4788-AE7C-977E140265BD","status":0}
2017-11-27 17:41:58:651 - [debug] [BaseDriver] Event 'wdaSessionStarted' logged at 1511775718650 (17:41:58 GMT+0800 (CST))
2017-11-27 17:41:58:651 - [debug] [BaseDriver] Event 'wdaStarted' logged at 1511775718651 (17:41:58 GMT+0800 (CST))
2017-11-27 17:41:58:652 - [debug] [XCUITest] Setting initial orientation to 'PORTRAIT'
2017-11-27 17:41:58:658 - [debug] [JSONWP Proxy] Proxying [POST /orientation] to [POST http://localhost:8100/session/D539F7A4-92E1-4788-AE7C-977E140265BD/orientation] with body: {"orientation":"PORTRAIT"}
2017-11-27 17:41:59:803 - [HTTP] --> GET /wd/hub/status {}
2017-11-27 17:41:59:803 - [debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
2017-11-27 17:41:59:811 - [debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.7.1","revision":"0a95e77000515c1156be593642dd4e452f2f098e"}}
2017-11-27 17:41:59:812 - [HTTP] <-- GET /wd/hub/status 200 9 ms - 121
2017-11-27 17:42:00:064 - [debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"D539F7A4-92E1-4788-AE7C-977E140265BD","status":0}
2017-11-27 17:42:00:064 - [debug] [BaseDriver] Event 'orientationSet' logged at 1511775720064 (17:42:00 GMT+0800 (CST))
2017-11-27 17:42:00:065 - [debug] [BaseDriver] Event 'iwdpStarting' logged at 1511775720065 (17:42:00 GMT+0800 (CST))
2017-11-27 17:42:00:069 - [debug] [iOS] Starting ios_webkit_debug_proxy at port 27753 on device ed1ecf1e2ddd960ec5acac87da88a38b387cca15
Error: write EPIPE
    at exports._errnoException (util.js:1020:11)
    at WriteWrap.afterWrite (net.js:800:14)
```

**Comment by ochubey** [comment]
@darkmanno6 what would happen if you trying to run `ios_webkit_debug_proxy` on the remote server (where the device is connected)?
In case you would face error while running the mentioned command - try reinstalling `ideviceinstaller, libimobiledevice and ios-webkit-debug-proxy` using following a set of commands:
> brew uninstall ideviceinstaller
> brew uninstall libimobiledevice
> brew install --HEAD libimobiledevice
> brew link --overwrite libimobiledevice
> brew unlink libimobiledevice && brew link libimobiledevice
> brew install --HEAD  ideviceinstaller
> brew link --overwrite ideviceinstaller
> brew unlink ideviceinstaller && brew link ideviceinstaller
> brew install ios-webkit-debug-proxy
> brew postinstall ios-webkit-debug-proxy
> sudo chmod -R 777 /var/db/lockdown/

**Comment by darkmanno6** [comment]
@ochubey when I login the remote server directly and  start appium on the server ,then excute the iOS test(the device is connected to this remote server)， it is all ok. So I think the ios_webkit_debug_proxy has no problem. 
could you try the way I decribed in "Details"

**Comment by ochubey** [comment]
@darkmanno6 running Appium server on remote machine doesn't trigger `ios_webkit_debug_proxy` command. It happens when Driver initiates. That is why, in order to understand the reason for the issue, I asked for the output of this command. In addition, Jenkins might have its own environment, so you can have different results when running a server from Jenkins and from the command line as a user.

**Comment by darkmanno6** [comment]
@ochubey 
ok, I give the log when running ios_webkit_debug_proxy, It's all ok:
```log
➜  appiumlog ios_webkit_debug_proxy
Listing devices on :9221
Connected :9223 to test的 iPhone (ed1ecf1e2ddd960ec5acac87da88a38b387cca15)
```
And I know that ios_webkit_debug_proxy won't be triggered by appium server start, But the java_client(5.0.0BETA9) has the capability` capabilities.setCapability("startIWDP", true)` to start the iwdp automated.
If you think that Jenkins might have its own environment, I understand you.
however, when I use JSch or Ganymed SSH-2 by java to ssh the remote server  and start the appium, then I excute  the ios test .(the device is connected to the remote server and the test script is also on the remote server ) It was still crashed.

**Comment by ochubey** [comment]
I'm using an older Java client (4.1.2), but with `"startIWDP", true` and issue not reproducible.
So if Appium executed using `ssh` it works fine?

**Comment by darkmanno6** [comment]
No, if Appium excuted using ssh(jenkins、JSch or Ganymed SSH-2 by) it wiil be crashed while testing, but it works fine if excuted locally .

**Comment by ochubey** [comment]
Could you, please, describe how you run Appium Server?
Is it from Java code or CLI?
What Server and Device capabilities are you using?
Was it working before java_client update?

**Comment by darkmanno6** [comment]
@ochubey 
#### how you run Appium Server? Is it from Java code or CLI?

1.  Firstly ,I  **use java code(Lib :JSch or Ganymed SSH-2 ) to ssh remote server and start the appium server by CLI** :
```bash
(appium --nodeconfig /Users/test-hwb/iOSAutomation/nodeconfig/iOS_${udid}.json --log-timestamp --local-timezone -p ${port} -U ${udid} > /Users/test-hwb/iOSAutomation/appiumlog/appium_${udid}_${timestamp}.log &)
```
2. Then I run the test script on the remote server(**no ssh and excute locally on the remote server**).
3. The appium server was crahsed when the iwdp has started.

#### What Server and Device capabilities are you using?
* there's my capabilities using:
```java
capabilities.setCapability("automationName", IOS_AUTOMATION_NAME);
capabilities.setCapability("platformVersion", IOS_PLATFORM_VER);
capabilities.setCapability("deviceName", IOS_DEVICE_NAME);
capabilities.setCapability("platformName", IOS_PLATFORM);
capabilities.setCapability("udid", UDID);
capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, 300);
capabilities.setCapability("bundleId", IOS_APP_PACKAGE_NAME);
capabilities.setCapability("noReset", true);
capabilities.setCapability("showXcodeLog", false);
capabilities.setCapability("usePrebuiltWDA", true);
capabilities.setCapability("xcodeOrgId", ORGID);
capabilities.setCapability("xcodeSigningId", SIGNID);
capabilities.setCapability("startIWDP", true);
```
#### Was it working before java_client update?
* sorry, I can't update  java_client version currently.
#### If you running single or multiple sessions of the Appium Server from on the same remote machine?
* I run single session of the appium server on the remote server.

**Comment by hzqroll** [comment]
six six six

**Comment by ochubey** [comment]
@darkmanno6 you can try:
1. run following command through ssh right before Appium Server initialization: `lsof -i tcp:27753| grep ios_webki| awk '{print $2}'| xargs kill`;
2. add server capability with different port defined `appium {all other server flags} --webkit-debug-proxy-port 8302`;
3. set `startIWDP` to `false` and run following command through ssh right before Appium Server initialization: `ios_webkit_debug_proxy -u {device_udid}`.

**Comment by darkmanno6** [comment]
@ochubey 
I have tried and it works fine. Thank you very much.
However, why I set startIWDP to true will make appium crash...

**Comment by ochubey** [comment]
@darkmanno6 could you, please share which of the 3 options helped to resolve an issue (just in case if someone else could face similar situation)?
Regarding startIWDP - looks like there is a broken connection happen between your test code and remote server where appium server started (EPIPE error).
In case if issue resolved - please close it :)

**Comment by darkmanno6** [comment]
The third option helped me.
