### ISSUE TITLE
Calling webDriver.Close() for an iOS simulator or real device causes appium to occassionally throw an InvalidOperationException.

### ISSUE THREAD

**Issue by mike-malandra** [appium/appium#9723]
## The problem

Calling webDriver.Close() for an iOS simulator or real device causes appium to occassionally throw an InvalidOperationException.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.0; dotnet
* Desktop OS/version used to run Appium: MacOS/10.0
* Mobile platform/version under test: iOS 
* Real device or emulator/simulator: occurs on both
* Appium.app|exe:

## Details

We want to close tabs in Safari after verifying a link creates a new tab and verifying the contents of the new tab. webDriver.Close() does successfully close the tab, but performing any action afterwards sometimes causes an exception to be thrown.

## Link to Appium logs

Currently running these tests on Browserstack which does not provide access to appium logs.
Here is the callstack for attempting to perform an action with the webDriver after calling Close:

Result StackTrace:	
at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Appium.AppiumDriver`1.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Appium.AppiumDriver`1.OpenQA.Selenium.Appium.Interfaces.IExecuteMethod.Execute(String driverCommand)
   at OpenQA.Selenium.Appium.AppiumDriver`1.get_Context()
   at Bisk.Core.Controllers.Selenium.AppiumDriverController.set_Context(String value)
Result Message:	System.InvalidOperationException : An unknown server-side error occurred while processing the command.

## Code To Reproduce Issue [ Good To Have ]

webDriver.Close();

**Comment by mykola-mokhnach** [comment]
Cannot advice anything without having the server log

**Comment by mike-malandra** [comment]
i'll see if theres a way browserstack can get those logs to us.
