### ISSUE TITLE
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not find package app-debug.apk on the device (WARNING: The server did not provide any stacktrace information)

### ISSUE THREAD

**Issue by iamabhiram** [appium/appium#9746]
## The problem

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not find package app-debug.apk on the device (WARNING: The server did not provide any stacktrace information)

## Environment

* Appium version 1.7.1
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android 5.1
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe:

## Details

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not find package app-debug.apk on the device (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1.26 seconds
Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:07:31.527Z'

## Link to Appium logs

[info] [Appium] Welcome to Appium v1.7.1
[info] [Appium] Non-default server args:
[info] [Appium]   address: 127.0.0.1
[info] [Appium]   port: 4725
[info] [Appium] Appium REST http interface listener started on 127.0.0.1:4725[info] [HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"app-debug.apk","appActivity":"com.xfactory.in.activity.SplashActivity","appPackage":"com.xfactory.in","deviceName":"Android Emulator","platformName":"Android"},"capabilities":{"desiredCapabilities":{"app":"app-debug.apk","appActivity":"com.xfactory.in.activity.SplashActivity","appPackage":"com.xfactory.in","deviceName":"Android Emulator","platformName":"Android"},"firstMatch":[{"platformName":"android"}]}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"app-debug.apk","appActivity":"com.xfactory.in.activity.SplashActivity","appPackage":"com.xfactory.in","deviceName":"Android Emulator","platformName":"Android"},null,{"desiredCapabilities":{"app":"app-debug.apk","appActivity":"com.xfactory.in.activity.SplashActivity","appPackage":"com.xfactory.in","deviceName":"Android Emulator","platformName":"Android"},"firstMatch":[{"platformName":"android"}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1512471463420 (16:27:43 GMT+0530 (India Standard Time))
[info] [Appium] Creating new AndroidDriver (v1.28.1) session
[info] [Appium] Capabilities:
[info] [Appium]   app: 'app-debug.apk'
[info] [Appium]   appActivity: 'com.xfactory.in.activity.SplashActivity'
[info] [Appium]   appPackage: 'com.xfactory.in'
[info] [Appium]   deviceName: 'Android Emulator'
[info] [Appium]   platformName: 'Android'
[info] [BaseDriver] Session created with session id: 82d38339-f68a-4d30-9cc6-2f543e2b70f0
[debug] [AndroidDriver] Getting Java version[info] [AndroidDriver] Java version is: 1.8.0_144
[info] [ADB] Checking whether adb is present[debug] [ADB] 1 device(s) connected
[info] [AndroidDriver] Using device: emulator-5554
[info] [ADB] Checking whether adb is present
[info] [ADB] Using adb.exe from C:\Users\XXXXXX\AppData\Local\Android\sdk\platform-tools\adb.exe
[debug] [ADB] Setting device id to emulator-5554
[info] [AndroidDriver] App file was not listed, instead we're going to run app-debug.apk directly on the device
[debug] [AndroidDriver] Checking whether package is present on the device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\XXXXXX\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","pm","list","packages","app-debug.apk"]
[error] [AndroidDriver] Error: Could not find package app-debug.apk on the device
    at Object.wrappedLogger.errorAndThrow (C:\Users\XXXXXX\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:63:13)
    at AndroidDriver.checkPackagePresent$ (C:\Users\XXXXXX\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-android-driver\lib\driver.js:392:11)
    at tryCatch (C:\Users\XXXXXX\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\XXXXXX\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\XXXXXX\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\XXXXXX\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: Could not find package app-debug.apk on the device
    at Object.wrappedLogger.errorAndThrow (C:\Users\XXXXXX\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:63:13)
    at AndroidDriver.checkPackagePresent$ (C:\Users\XXXXXX\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-android-driver\lib\driver.js:392:11)
    at tryCatch (C:\Users\XXXXXX\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\XXXXXX\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\XXXXXX\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\XXXXXX\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[debug] [AndroidDriver] Shutting down Android driver
[debug] [AndroidDriver] Called deleteSession but bootstrap wasn't active
[debug] [ADB] Getting connected devices...[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\XXXXXX\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","am","force-stop","io.appium.unlock"][debug] [AndroidDriver] Not cleaning generated files. Add `clearSystemFiles` capability if wanted.
[error] [MJSONWP] Encountered internal error running command: Error: Could not find package app-debug.apk on the device
    at Object.wrappedLogger.errorAndThrow (C:\Users\XXXXXX\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:63:13)
    at AndroidDriver.checkPackagePresent$ (C:\Users\XXXXXX\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-android-driver\lib\driver.js:392:11)
    at tryCatch (C:\Users\XXXXXX\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\XXXXXX\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\XXXXXX\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\XXXXXX\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[info] [HTTP] <-- POST /wd/hub/session 500 1203 ms - 187 

## Code To Reproduce Issue [ Good To Have ]

AndroidDriver<WebElement> driver;
	  public String url;//, Node;
	  protected ThreadLocal<RemoteWebDriver> threadDriver = null;
	  DesiredCapabilities cap = new DesiredCapabilities();
	  //@Parameters("browser")
	  @BeforeTest
	  public void launchapp() throws MalformedURLException{
	  String browser="Mobile";
	
	   if (browser.equalsIgnoreCase("Mobile")) 
	   {
		
		   	cap.setCapability("platformName","Android");
			//cap.setCapability("udid","Android Device");//emulator-5554, Android Device, Android Emulator
			cap.setCapability("deviceName","Android Emulator");//3a24da1
			cap.setCapability("app", "app-debug.apk");
			cap.setCapability("appPackage", "com.XXXXX.in");
			cap.setCapability("appActivity", "com.XXXXXX.in.activity.SplashActivity");
			 			
	   } 
	 
	  }
  @Test
  public void ScrollToText() throws InterruptedException, MalformedURLException { 
	  driver=new AndroidDriver<WebElement>(new URL("http://127.0.0.1:4725/wd/hub"), cap);
		driver.manage().timeouts().implicitlyWait(20, TimeUnit.SECONDS);
		//TouchAction act=new TouchAction(driver);
		driver.manage().timeouts().implicitlyWait(15, TimeUnit.SECONDS);

**Comment by mykola-mokhnach** [comment]
Provide full path to the application under test under `app` capability

**Comment by iamabhiram** [comment]
@mykola-mokhnach - First i tried with full path only, still the same problem. Getting following error.

[MJSONWP] Encountered internal error running command: Error: Error occured while starting App. Original error: Activity used to start app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity
    at Object.wrappedLogger.errorAndThrow (C:\Users\XXXXX\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:63:13)

**Comment by mykola-mokhnach** [comment]
This means you should provide correct values to `appActivity` and `appWaitActivity` capabilities. Closed as not an issue

**Comment by iamabhiram** [comment]
@mykola-mokhnach - Done prob solved
