### ISSUE TITLE
 Unknown device or simulator UDID 

### ISSUE THREAD

**Issue by VenkateshPS** [appium/appium#9800]
## The problem

[XCUITest] Error: Unknown device or simulator UDID: 'XXXXXXXXXXXX'
    at XCUITestDriver.determineDevice$ (../../lib/driver.js:605:17)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
## Environment

* Appium version (or git revision) that exhibits the issue:1.6.5 beta 4
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: mac OS Sierra 10.12.6
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator: real device iPhone 6 iOS11.0.3 
* Appium CLI or Appium.app|exe:

## Details

I need to start and stop appium server multiple times to get rid of this issue, noticed only with iPhone Apps.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
The full server log is missing

**Comment by VenkateshPS** [comment]
There is nothing else in the log except this exception, I can add though when i get next time.

**Comment by mykola-mokhnach** [comment]
Full log shows the context, capabilities and the other data, which helps to figure out what the problem might be.

**Comment by VenkateshPS** [comment]
[25acf2d4c5b7345475a8537fd93e0fb9-c56303338ef38281954a723caf3eaa05559c050d.zip](https://github.com/appium/appium/files/1603103/25acf2d4c5b7345475a8537fd93e0fb9-c56303338ef38281954a723caf3eaa05559c050d.zip)
