### ISSUE TITLE
IOSDriver open url error

### ISSUE THREAD

**Issue by zhaoxusun** [appium/appium#9816]
## The problem
I want to go to some page by scheme protocol in native app, so I try to use driver.navigate().to(String url) method ,but failed in real iPhone device, succeed in simulator
How to solve the problem ?

## Environment

* Appium version 1.7.1
* iOS 11
* Real device (test failed) emulator/simulator(test succeed)
capabilities:
* automationName=XCUITest
* recreateChromeDriverSessions=true
* waitForAppScript=true
* platformVersion=11.0
* port=4723
* startIWDP=true
* udid=f35dbf0d0711dbe757b6165ff2b3fd744868d6db
* deviceName=iPhone 7P
* autoAcceptAlerts=true
* appium-version=1.7.1
* platformName=iOS
* noReset=true
* bundleId=com.meituan.imeituan-beta
## Details

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Failed to open imeituan://www.meituan.com/order/list/?to=0 (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T15:28:36.4Z'
System info: host: 'zhaoxudeMacBook-Pro.local', ip: 'fe80:0:0:0:1cb6:2bb2:5db1:a200%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_121'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{networkConnectionEnabled=false, recreateChromeDriverSessions=true, noReset=true, bundleId=com.meituan.imeituan-beta, databaseEnabled=false, deviceName=iPhone 7P, platform=MAC, platformVersion=11.0, webStorageEnabled=false, locationContextEnabled=false, automationName=XCUITest, browserName=, takesScreenshot=true, waitForAppScript=true, javascriptEnabled=true, udid=f35dbf0d0711dbe757b6165ff2b3fd744868d6db, platformName=MAC, autoAcceptAlerts=true}]
Session ID: 8bfb9401-76ce-4eff-a128-01d8b6f2bb9f

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:82)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:45)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:89)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:586)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:310)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteNavigation.to(RemoteWebDriver.java:897)

## Link to Appium logs

[HTTP] <-- GET /wd/hub/session/5e698a98-6dbe-4489-909c-59ee0aeb6f88 200 239 ms - 479 
[HTTP] --> POST /wd/hub/session/5e698a98-6dbe-4489-909c-59ee0aeb6f88/url {"url":"imeituan://www.meituan.com/order/list/?to=0"}
[MJSONWP] Calling AppiumDriver.setUrl() with args: ["imeituan://www.meituan.com/order/list/?to=0","5e698a98-6dbe-4489-909c-59ee0aeb6f88"]
[XCUITest] Executing command 'setUrl'
[JSONWP Proxy] Proxying [POST /url] to [POST http://localhost:8100/session/EB82C225-2CDE-45B8-BB6C-89D3C3EA7C8A/url] with body: {"url":"imeituan://www.meituan.com/order/list/?to=0"}
[JSONWP Proxy] Got response with status 200: {"value":"Failed to open imeituan://www.meituan.com/order/list/?to=0","sessionId":"EB82C225-2CDE-45B8-BB6C-89D3C3EA7C8A","status":13}
[HTTP] <-- POST /wd/hub/session/5e698a98-6dbe-4489-909c-59ee0aeb6f88/url 500 13 ms - 229 

## Code To Reproduce Issue [ Good To Have ]

driver = new IOSDriver(new URL(Capabilities.getUrl()), capabilities);

driver.navigate().to("imeituan://www.meituan.com/order/list/?to=0");

**Comment by mykola-mokhnach** [comment]
Unfortunately it is not possible. This is known XCTest limitation.
