### ISSUE TITLE
don't connect appium server

### ISSUE THREAD

**Issue by chenzheng102** [appium/appium#9844]
1.mac high Sierra  Version 10.13.2
2.appium1.7.1
3.script:python2.7
4.android 6.0

Execution script, appium server connection is not up, appium does not have any log output, throws exception information：
/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7 /Users/Test/Downloads/SDKCompare/SDKinstall.py
Traceback (most recent call last):
  File "/Users/Test/Downloads/SDKCompare/SDKinstall.py", line 12, in <module>
    driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/appium/webdriver/webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 309, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 460, in execute
    return self._request(command_info[0], url, body=data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 522, in _request
    resp = opener.open(request, timeout=self._timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>

Process finished with exit code 1

use script：
import time
from appium import webdriver
desired_caps = {}
desired_caps['platformName'] = 'Android'
# desired_caps['deviceName'] = 'SOEAMJHE99999999'
desired_caps['deviceName'] = 'KZR4WG4P99999999'
desired_caps['platformVersion'] = '5.0.2'
desired_caps['app'] = "/Users/Test/Downloads/SDKCompare/Demo.apk"
desired_caps['appPackage'] = xxxxxxxxxx
desired_caps['appActivity'] = 'xxxxxx
desired_caps['noReset'] = True
driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)
time.sleep(3)

time.sleep(1)
driver.quit()

**Comment by mykola-mokhnach** [comment]
This error means that Appium server is not listening at `localhost:4723`.
Make sure that `localhost` can be resolved and check if Appium service is listening at port 4723 (using `netstat`utility, for example)
