### ISSUE TITLE
Wanna get toast by Uiautomator2,but run fail

### ISSUE THREAD

**Issue by cloudyhuang** [appium/appium#9851]
appium version: 1.6.5
java-client version: 5.0.4
selenium version : 3.4.0

I wanna get toast by Uiautomator2,so I add  `capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.ANDROID_UIAUTOMATOR2);`，and I insatll UIAUTOMATOR2-driver through cd in appium path and `npm install appium-uiautomator2-driver `,but when I run my case ,it got wrong!
Here is log:
[UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original error: 'Command '/Users/master/Library/Android/sdk/platform-tools/adb -P 5037 -s 192.168.56.101\:5555 forward --remove tcp\:8200' exited with code 1'; Stderr: 'error: listener 'tcp:8200' not found'; Code: '1''
[MJSONWP] Encountered internal error running command: TypeError: this.adb.getScreenDensity is not a function
    at AndroidUiautomator2Driver.startUiAutomator2Session$ (../../lib/driver.js:280:52)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

FAILED CONFIGURATION: @BeforeSuite setUp("192.168.56.101:5555", true)
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: this.adb.getScreenDensity is not a function (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 869 milliseconds
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T15:28:36.4Z'
System info: host: 'bogon', ip: 'fe80:0:0:0:18ab:abd8:37d8:148a%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_51'
Driver info: driver.version: AndroidDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:167)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$new$0(JsonWireProtocolResponse.java:53)
	at org.openqa.selenium.remote.JsonWireProtocolResponse$$Lambda$78/981159997.apply(Unknown Source)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$getResponseFunction$2(JsonWireProtocolResponse.java:91)
	at org.openqa.selenium.remote.JsonWireProtocolResponse$$Lambda$80/1657125852.apply(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$22(ProtocolHandshake.java:365)
	at org.openqa.selenium.remote.ProtocolHandshake$$Lambda$87/827579900.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:368)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:159)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:89)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:250)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:236)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:137)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:83)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:93)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:72)
	at com.hjs.config.CommonAppiumTest.setUp(CommonAppiumTest.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)

**Comment by mykola-mokhnach** [comment]
Try Appium 1.7.1 ir 1.7.2@beta

**Comment by ayarema** [comment]
Hi, I'm facing with the same issue.

Appium version 1.7.1
Appium server is launching from java code. Application is builded with debug mode. 

Here is my log:

```
**************************************************************************
Starting Appium Server......
**************************************************************************

[Appium] Welcome to Appium v1.7.1
[Appium] Non-default server args:
[Appium]   address: 127.0.0.1
[Appium]   port: 61784
[Appium]   loglevel: info
[Appium] Appium REST http interface listener started on 127.0.0.1:61784
[HTTP] --> GET /wd/hub/status {}
[HTTP] <-- GET /wd/hub/status 200 14 ms - 83 
**************************************************************************
Appium Server Started at......http://127.0.0.1:61784/wd/hub ......
**************************************************************************

2017-12-26 15:52:07 Log4Test [INFO] [DeviceManager] INFO: "Method closeAllEmulators invoked"
2017-12-26 15:52:07 Log4Test [INFO] [DeviceManager] INFO: "All emulators are stopped."
2017-12-26 15:52:07 Log4Test [INFO] [DeviceManager] INFO: "Method closeAllEmulators has finished"
2017-12-26 15:52:09 Log4Test [INFO] [com.testcompany.steps.ot.OTTestHelper] INFO: "Method create factory by OS invoked"
2017-12-26 15:52:09 Log4Test [INFO] [com.testcompany.core.DriverController] INFO: "Method createDriver has invoked"
2017-12-26 15:52:09 Log4Test [INFO] [com.testcompany.core.DriverController] INFO: "OS type was configured like: android"
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/user/IdeaProjects/Test-Project/applications/application-application-live-debug-2.17.26-181.apk","newCommandTimeout":2000,"automationName":"UiAutomator2","platformName":"Android","deviceName":"Android","avd":"Nexus_6_API_25"},"requiredCapabilities":{},"capabilities":{"desiredCapabilities":{"app":"/Users/user/IdeaProjects/Test-Project/applications/application-application-live-debug-2.17.26-181.apk","newCommandTimeout":2000,"automationName":"UiAutomator2","platformName":"Android","deviceName":"Android","avd":"Nexus_6_API_25"},"requiredCapabilities":{},"alwaysMatch":{"platformName":"Android"},"firstMatch":[]}}
[Appium] Creating new AndroidUiautomator2Driver (v0.6.5) session
[Appium] Capabilities:
[Appium]   app: '/Users/user/IdeaProjects/Test-Project/applications/application-application-live-debug-2.17.26-181.apk'
[Appium]   newCommandTimeout: 2000
[Appium]   automationName: 'UiAutomator2'
[Appium]   platformName: 'Android'
[Appium]   deviceName: 'Android'
[Appium]   avd: 'Nexus_6_API_25'
[BaseDriver] Session created with session id: ca86ae25-6119-48fe-ab8b-12721e05668a
[BaseDriver] Using local app '/Users/user/IdeaProjects/Test-Project/applications/application-application-live-debug-2.17.26-181.apk'
[AndroidDriver] Java version is: 1.8.0_152
[ADB] Checking whether adb is present
[ADB] Using adb from /Users/user/Library/Android/sdk/platform-tools/adb
[ADB] Checking whether emulator is present
[ADB] Using emulator from /Users/user/Library/Android/sdk/emulator/emulator
[ADB] Checking whether emulator is present
[ADB] Using emulator from /Users/user/Library/Android/sdk/emulator/emulator
[ADB] [AVD OUTPUT] path /Users/user/.android/avd/Nexus_6_API_25.avd/system.img.qcow2
[ADB] [AVD OUTPUT] emulator: ### WARNING: /etc/localtime does not point to /usr/share/zoneinfo/, can't determine zoneinfo timezone name
[AndroidDriver] Using device: emulator-5554
[ADB] Checking whether adb is present
[ADB] Using adb from /Users/user/Library/Android/sdk/platform-tools/adb
[ADB] Checking whether aapt is present
[ADB] Using aapt from /Users/user/Library/Android/sdk/build-tools/26.0.0/aapt
[ADB] Extracting package and launch activity from manifest
[ADB] Error: packageAndLaunchActivityFromManifest failed. Original error: Command '/Users/user/Library/Android/sdk/build-tools/26.0.0/aapt dump badging /Users/user/IdeaProjects/Test-Project/applications/application-application-live-debug-2.17.26-181.apk' exited with code 1
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at ADB.callee$0$0$ (../../../lib/tools/android-manifest.js:104:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 Error: packageAndLaunchActivityFromManifest failed. Original error: Command '/Users/user/Library/Android/sdk/build-tools/26.0.0/aapt dump badging /Users/user/IdeaProjects/Test-Project/applications/application-application-live-debug-2.17.26-181.apk' exited with code 1
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at ADB.callee$0$0$ (../../../lib/tools/android-manifest.js:104:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:109:7)
[UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original error: 'Command '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward --remove tcp\:8200' exited with code 1'; Stderr: 'error: listener 'tcp:8200' not found'; Code: '1''
[MJSONWP] Encountered internal error running command: Error: packageAndLaunchActivityFromManifest failed. Original error: Command '/Users/user/Library/Android/sdk/build-tools/26.0.0/aapt dump badging /Users/user/IdeaProjects/Test-Project/applications/application-application-live-debug-2.17.26-181.apk' exited with code 1
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at ADB.callee$0$0$ (../../../lib/tools/android-manifest.js:104:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:109:7)
[HTTP] <-- POST /wd/hub/session 500 15891 ms - 417 
2017-12-26 15:52:26 Log4Test [INFO] [com.testcompany.core.DriverController] INFO: "Method createDriver has finished"

cucumber.runtime.CucumberException: Failed to instantiate class com.testcompany.steps.ot.HomeScreenStepdefs

	at cucumber.runtime.java.DefaultJavaObjectFactory.cacheNewInstance(DefaultJavaObjectFactory.java:47)
	at cucumber.runtime.java.DefaultJavaObjectFactory.getInstance(DefaultJavaObjectFactory.java:33)
	at cucumber.runtime.java.JavaBackend.buildWorld(JavaBackend.java:131)
	at cucumber.runtime.Runtime.buildBackendWorlds(Runtime.java:141)
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:38)
	at cucumber.runtime.model.CucumberScenarioOutline.run(CucumberScenarioOutline.java:46)
	at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:165)
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:63)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at cucumber.runtime.java.DefaultJavaObjectFactory.cacheNewInstance(DefaultJavaObjectFactory.java:41)
	... 32 more
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: packageAndLaunchActivityFromManifest failed. Original error: Command '/Users/user/Library/Android/sdk/build-tools/26.0.0/aapt dump badging /Users/user/IdeaProjects/Test-Project/applications/application-application-live-debug-2.17.26-181.apk' exited with code 1 (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 16.19 seconds
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T15:28:36.4Z'
System info: host: 'Andriis-Mac-mini.local', ip: 'fe80:0:0:0:863:2356:c77b:8151%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.2', java.version: '1.8.0_152'
Driver info: driver.version: AndroidDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$new$0(JsonWireProtocolResponse.java:53)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$getResponseFunction$2(JsonWireProtocolResponse.java:91)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$24(ProtocolHandshake.java:359)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:362)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:136)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:89)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:586)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:217)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:140)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:83)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:93)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:72)
	at com.testcompany.core.AndroidDriverExtended.<init>(AndroidDriverExtended.java:22)
	at com.testcompany.core.DriverController.createDriver(DriverController.java:111)
	at com.testcompany.pageobjects.ot.AndroidOTPageFactory.<init>(AndroidOTPageFactory.java:40)
	at com.testcompany.steps.ot.OTTestHelper.createFactoryByOS(OTTestHelper.java:23)
	at com.testcompany.steps.ot.BaseBackdrop.<init>(BaseBackdrop.java:19)
	at com.testcompany.steps.ot.HomeScreenStepdefs.<init>(HomeScreenStepdefs.java:14)
	... 37 more


0 Scenarios
0 Steps
0m0.000s

2017-12-26 15:52:27 AppiumServerManager [INFO] Appium Server try to stop....
[Appium] Received SIGTERM - shutting down
2017-12-26 15:52:30 AppiumServerManager [INFO] Appium Server was stopped....
2017-12-26 15:52:30 Log4Test [INFO] [com.testcompany.manager.DeviceManager] INFO: "Method closeAllEmulators invoked"
2017-12-26 15:52:30 Log4Test [INFO] [com.testcompany.manager.DeviceManager] INFO: "All emulators are stopped."
2017-12-26 15:52:30 Log4Test [INFO] [com.testcompany.manager.DeviceManager] INFO: "Method closeAllEmulators has finished"

===============================================
Default Suite
Total tests run: 1, Failures: 1, Skips: 0
===============================================


Process finished with exit code 0
```

**Comment by ayarema** [comment]
No issues. Trouble with java versions. I installed Java 9 and now get a error:

```
[ADB] Error: Could not sign with default certificate. Original error Command '/Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Home/bin/java' not found. Is it installed?
```
And I'm trying to fix it...

**Comment by mykola-mokhnach** [comment]
@ayarema Your problem is known. The current Appium signing utility is incompatible to Java9. You could downgrade to Java8 to workaround it.

**Comment by ayarema** [comment]
Yeah, I downgrade to Java8 and all is working. Thanks!

**Comment by cloudyhuang** [comment]
I found that my appium not install completely,I re-install appium 1.6.5,it's did work! It May be when appium install at "info download google chromedriver...." I cancled the install  progress,or my country Internet reject google access,as you kown China can't visit google website.I re-installed it by VPN,thx...
