### ISSUE TITLE
Ability to use multiple apps sessions supported in XCode 9

### ISSUE THREAD

**Issue by risinek** [appium/appium#9883]
## The problem

As the XCode 9 and iOS 11 supports multiple apps test sessions, I'm looking for hints how to modify appium-xcuitest-driver to support this feature.. As a first step I would like to implement Settings control ability, so basically somehow hardcode initialization of Settings so then the test run won't fail, when profile installation prompt will appear during testing own app.
I don't want to have a solution done by you, but I would like to ask you for some hints where to start with this in xcuitest-driver project and what other dependecies will be probably a problem.

**Comment by mykola-mokhnach** [comment]
Check the recent beta release: https://github.com/mykola-mokhnach/appium/blob/cc5dd06829c5972cd7fbd62584c16f77583c7a73/docs/en/writing-running-appium/ios/ios-xctest-mobile-apps-management.md

**Comment by UtsavSaha** [comment]
Hi, i am using the beta version to use the functionality. 

i could find the `'mobile: installApp'` event working which installs another app, but the events 
`mobile: activateApp / mobile: launchApp` is failing with 500 errorcode at server. 
Refer to [logs](https://gist.github.com/UtsavSaha/9ce382d8662dbcde0304038f60db5e81) for server error.

**Comment by mykola-mokhnach** [comment]
make sure that WebDriverAgent binary on the device is up to date

**Comment by vjmaiky** [comment]
with latest resources i can confirm that launch app works as expected

**Comment by UtsavSaha** [comment]
After updating the appium-xcuittest-driver and rebuilding,this events are working.
Moreover, this events are useful if someone wants to test their app being launched by external Url.

**Comment by risinek** [comment]
I just tried to run my old test run which was failing before on installing profile, because it was not possible to switch to Preferences from our app and accept profile installation, but it seems like now it's working on its own without using launchApp command.

I have this set up:
Appium 1.7.1
XCode 9.2
iPhone SE with iOS 11.1 (15B93)
(running appium on Mac)

Not sure, if this is expected, but it's not mentioned in changelog and it's pretty good feature to control preferences and safari alongside with tested app.

**Comment by vjmaiky** [comment]
@mykola-mokhnach i have two behaviours which seems to have some difference that i cannot figure out:

1. if i use it in a junit test with calling create driver method inside of the test works fine:

```
 @Test
    public void testJSMethods() throws Exception {
        DriverManagerIOS.createiOSDriver();
        Helpers.isInstalled("bundle");
        Thread.sleep(1000);
        Helpers.closeApp("bundle");
        Thread.sleep(1000);
        Helpers.launchApp("bundle");
        Thread.sleep(1000);
        Helpers.closeApp("bundle");
    }
```

2. if i use a test manager class which extends a watcher which actually contains also driver creation, and test class extends test manager, it seems that is not working:

[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/56013e84-2eeb-403d-9f78-8f42cee78e5f/element/53A731F6-3ECD-45E9-BA63-5A5F65005283/displayed] to [GET http://localhost:7341/session/7B1F60C1-703F-4F7E-826B-DB1790B8E8BB/element/53A731F6-3ECD-45E9-BA63-5A5F65005283/displayed] with body: {}
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : true,\n  \"sessionId\" : \"7B1F60C1-703F-4F7E-826B-DB1790B8E8BB\",\n  \"status\" : 0\n}"
[JSONWP Proxy] Replacing sessionId 7B1F60C1-703F-4F7E-826B-DB1790B8E8BB with 56013e84-2eeb-403d-9f78-8f42cee78e5f
01-04-2018 10:29:47 - [core.helpers.Helpers / isInstalled][INFO ] - Verify if de.telekom.connectivity.inflight is installed
01-04-2018 10:29:47 - [core.watchers.iOSTestWatcher / failed][INFO ] - Test Failed: tests.TestSet_01_FirstTimeView, ftwNotDisplayedAfterClosingTheApp

Null pointer here:
final boolean isInstalled = (Boolean) js.executeScript("mobile: isAppInstalled", params);


java.lang.NullPointerException
	at core.helpers.Helpers.isInstalled(Helpers.java:111)
	at tests.TestSet_01_FirstTimeView.ftwNotDisplayedAfterClosingTheApp(TestSet_01_FirstTimeView.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at core.watchers.Retry$1.evaluate(Retry.java:28)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

any sugestions?

**Comment by mykola-mokhnach** [comment]
It's an exception in you client code, I have no idea about what is happening there. Can you show me server log where `mobile: isAppInstalled` is called?

**Comment by vjmaiky** [comment]
i enabled .withArgument(Arg.LOG_LEVEL, "debug")); (because i start appium from code); still when i run that command nothing is logged...

**Comment by vjmaiky** [comment]
i figured out what was the problem; it was on my side (i was casting a null driver..); thanks.

**Comment by UtsavSaha** [comment]
@mykola-mokhnach 
Will this work in android as well?

**Comment by mykola-mokhnach** [comment]
No, it won't

**Comment by UtsavSaha** [comment]
Is there any alternate in android for such support ? 
Is there any plan to introduce these events from in Android?

**Comment by mykola-mokhnach** [comment]
You're welcome to create a pull request

**Comment by vjmaiky** [comment]
@mykola-mokhnach did you tried mobile: isAppInstalled and mobile: removeApp ? on isAppInstalled it is always returning false even if app is installed, and on removeApp is executed ok but app is still installed on device..on logs i could not see anything that can say something..

**Comment by vjmaiky** [comment]
rest of commands are working as expected (i have latest resources 1.7.2 appium and latest xcuitest)

**Comment by mykola-mokhnach** [comment]
@vjmaiky Please create a separate bug report for it
