### ISSUE TITLE
python client fails to import webdriver on Linux

### ISSUE THREAD

**Issue by brett-burkhart** [appium/appium#9914]
## The problem

Trying to run a python test, on Linux, using the Appium Python Client libraries, which will communicate with WinAppDriver on a remote Windows 10 PC, but the test fails when it tries to import the webdriver.  I am running a simple test just to verify that I have everything configured correctly.  The test seems to be trying to use Firefox when importing everything, and it fails in get_window_size, but I don't see where get_window_size() is ever called....and I'm not wanting to use Firefox.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Node.js version (unless using Appium.app|exe): 8.9.3
* Mobile platform/version under test:  none
* Real device or emulator/simulator:  none
* Appium Python Client version: 0.25
* Selenium Python Client version: 3.8.0

## Test Result

ERROR PID:22490 TID:140068833117952 01/04 12:47:07.192 pytroller.py 1090 ######### Failed to import test /home/bburkhart/test_ln5_login_window.py
Traceback (most recent call last):
  File "pytroller.py", line 1086, in _getTestCase
    mod = imp.load_module(basename, file, pathname, desc)
  File "/home/bburkhart/test_ln5_login_window.py", line 1, in <module>
    from appium import webdriver
  File "/home/bburkhart/PythonCore/appium/__init__.py", line 19, in <module>
    from .saucetestcase import SauceTestCase
  File "/home/bburkhart/PythonCore/appium/saucetestcase.py", line 18, in <module>
    from appium import webdriver
  File "/home/bburkhart/PythonCore/appium/webdriver/__init__.py", line 19, in <module>
    from .webdriver import WebDriver as Remote
  File "/home/bburkhart/PythonCore/appium/webdriver/webdriver.py", line 15, in <module>
    from selenium import webdriver
  File "/home/bburkhart/PythonCore/selenium/webdriver/__init__.py", line 18, in <module>
    from .firefox.webdriver import WebDriver as Firefox  # noqa
  File "/home/bburkhart/PythonCore/selenium/webdriver/firefox/webdriver.py", line 35, in <module>
    from selenium.webdriver.remote.webdriver import WebDriver as RemoteWebDriver
  File "/home/bburkhart/PythonCore/selenium/webdriver/remote/webdriver.py", line 994
     return {k: size[k] for k in ('width', 'height')}
                          ^
 SyntaxError: invalid syntax
DEBUG PID:22490 TID:140068833117952 01/04 12:47:07.195 pytroller.py 1093  testcase None
DEBUG PID:22490 TID:140068833117952 01/04 12:47:07.195 pytroller.py 1094  test_info <__main__.TestInfo instance at 0x2b4b4d0>
DEBUG PID:22490 TID:140068833117952 01/04 12:47:07.195 pytroller.py 1095  error invalid syntax (webdriver.py, line 994)

## Code To Reproduce Issue [ Good To Have ]

from appium import webdriver

def execute(self):
    #set up appium
    desired_caps = {}
    desired_caps["platformName"] = "Windows"
    desired_caps["deviceName"] = "WindowsPC"

if __name__=='__main__':
    execute()

**Comment by brett-burkhart** [comment]
Moving issue to https://github.com/appium/python-client/issues/197
