### ISSUE TITLE
Getting Could not detect Mac OS X Version from sw_vers output: '10.13.2' error when trying to run appium-doctor

### ISSUE THREAD

**Issue by still-breathing** [appium/appium#9931]
## The problem
After installing appium-desktop-1.2.7-mac from zip file when I ran appium-doctor I got the following error. 

Error log:
```
╰─ appium-doctor
info AppiumDoctor Appium Doctor v.1.4.2
info AppiumDoctor ### Diagnostic starting ###
info AppiumDoctor  ✔ The Node.js binary was found at: /usr/local/bin/node
info AppiumDoctor  ✔ Node version is 8.1.1
info AppiumDoctor  ✔ Xcode is installed at: /Applications/Xcode.app/Contents/Developer
Error: Could not detect Mac OS X Version from sw_vers output: '10.13.2'
    at Object.macOsxVersion$ (/usr/local/lib/node_modules/appium-doctor/node_modules/appium-support/build/lib/system.js:114:15)
    at tryCatch (/usr/local/lib/node_modules/appium-doctor/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium-doctor/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium-doctor/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium-doctor/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
```
I've searched and found https://stackoverflow.com/questions/40129794/how-to-fix-error-could-not-detect-mac-os-x-version-from-sw-vers-output-10-12 (article) but I'm quite noob at this and afraid to change os system js file.

Is there any easy solution for this?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): not sure
* Desktop OS/version used to run Appium: OS X 10.13.2 
* Node.js version (unless using Appium.app|exe):v8.1.1
* Mobile platform/version under test:Android & iOS
* Real device or emulator/simulator: Real Device 
* Appium CLI or Appium.app|exe: Appium CLI (i guess)

Thanks

## Link to Appium logs

https://gist.github.com/still-breathing/7d41831ab6227e99a02e5ed0494f6c20#file-error-osx_10_13_2-txt

## Code To Reproduce Issue [ Good To Have ]
appium-doctor (at terminal)

**Comment by imurchie** [comment]
Can you update `appium-doctor`? There is a more recent version (1.4.3) which works for MacOS 10.13.
