### ISSUE TITLE
driver.getCurrentContext returns null instead of native_app

### ISSUE THREAD

**Issue by levyshachar2** [appium/appium#9933]
## The problem
Hi , since upgrading to latest appium version (1.7.2) I started getting NullPointerException when trying to access WebElement using pagefactory. 

I have two tests that run consecutively , the first one pass and the second one fails.
they both use the same PageFactory. (both of them pass with appium version 1.6.5)

i am trying to clear a text box of real android device , and i get null pointer exception.
from what i saw in the logs, i think there is an issue with driver.getCurrentContext()
as the first test returns "NATIVE_APP" and the second test returns null
see relevant log lines:
08-01-2018;08:32:19.071 [Thread-15] DEBUG media.muvix.framework.AppiumRunnable - appium :[HTTP] --> GET /wd/hub/session/f3aa0d1f-6070-49c6-a980-80d493526347/context {}
08-01-2018;08:32:19.072 [Thread-15] DEBUG media.muvix.framework.AppiumRunnable - appium :[debug] [MJSONWP] Calling AppiumDriver.getCurrentContext() with args: ["f3aa0d1f-6070-49c6-a980-80d493526347"]
08-01-2018;08:32:19.074 [Thread-15] DEBUG media.muvix.framework.AppiumRunnable - appium :[debug] [MJSONWP] Responding to client with driver.getCurrentContext() **result: "NATIVE_APP"**
08-01-2018;08:32:19.076 [Thread-15] DEBUG media.muvix.framework.AppiumRunnable - appium :[HTTP] <-- GET /wd/hub/session/f3aa0d1f-6070-49c6-a980-80d493526347/context 200 4 ms - 84

and the second one that fails:
08-01-2018;08:35:31.539 [Thread-15] DEBUG media.muvix.framework.AppiumRunnable - appium :[HTTP] --> GET /wd/hub/session/f3aa0d1f-6070-49c6-a980-80d493526347/context {}
08-01-2018;08:35:31.539 [Thread-15] DEBUG media.muvix.framework.AppiumRunnable - appium :[debug] [MJSONWP] Calling AppiumDriver.getCurrentContext() with args: ["f3aa0d1f-6070-49c6-a980-80d493526347"]
08-01-2018;08:35:31.543 [Thread-15] DEBUG media.muvix.framework.AppiumRunnable - appium :[debug] [MJSONWP] Responding to client with driver.getCurrentContext() **result: null**

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): 1.6.5
* Desktop OS/version used to run Appium: Mac OS Sierra
* Node.js version (unless using Appium.app|exe): v8.9.4
* Mobile platform/version under test: UIAutomator
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI
* Java Client - version 4.1.2

## Details

The exception:

> Message: java.lang.NullPointerException
	at io.appium.java_client.pagefactory.utils.WebDriverUnpackUtility.getCurrentContentType(WebDriverUnpackUtility.java:155)
	at io.appium.java_client.pagefactory.bys.ContentMappedBy.findElements(ContentMappedBy.java:36)
	at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:351)
	at io.appium.java_client.DefaultGenericMobileDriver.findElements(DefaultGenericMobileDriver.java:44)
	at io.appium.java_client.AppiumDriver.findElements(AppiumDriver.java:191)
	at io.appium.java_client.pagefactory.AppiumElementLocator$WaitingFunction.apply(AppiumElementLocator.java:154)
	at io.appium.java_client.pagefactory.AppiumElementLocator$WaitingFunction.apply(AppiumElementLocator.java:1)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:238)
	at io.appium.java_client.pagefactory.AppiumElementLocator.waitFor(AppiumElementLocator.java:88)
	at io.appium.java_client.pagefactory.AppiumElementLocator.findElement(AppiumElementLocator.java:103)
	at io.appium.java_client.pagefactory.interceptors.InterceptorOfASingleElement.intercept(InterceptorOfASingleElement.java:57)
	at io.appium.java_client.android.AndroidElement$$EnhancerByCGLIB$$c0b591f0.clear(<generated>)
	at media.muvix.framework.audioplayer.androidaudioplayer.AndroidAudioPlayerRegistration.beginPhoneRegistration(AndroidAudioPlayerRegistration.java:51)
	at media.muvix.steps.ui.audioPlayer.RegistrationSteps.enterPhoneNumber(RegistrationSteps.java:47)
	at media.muvix.steps.ui.audioPlayer.RegistrationSteps.beforeRegistration(RegistrationSteps.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cucumber.runtime.Utils$1.call(Utils.java:37)
	at cucumber.runtime.Timeout.timeout(Timeout.java:13)
	at cucumber.runtime.Utils.invoke(Utils.java:31)
	at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)
	at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:223)
	at cucumber.runtime.Runtime.runHooks(Runtime.java:211)
	at cucumber.runtime.Runtime.runBeforeHooks(Runtime.java:201)
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:40)
	at cucumber.runtime.junit.ExecutionUnitRunner.run(ExecutionUnitRunner.java:91)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:63)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:18)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:70)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:93)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:37)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at cucumber.api.junit.Cucumber.run(Cucumber.java:98)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:117)
	at org.junit.runner.JUnitCore.runMain(JUnitCore.java:96)
	at org.junit.runner.JUnitCore.runMainAndExit(JUnitCore.java:47)
	at org.junit.runner.JUnitCore.main(JUnitCore.java:40)

snippet of the code:
`        final RegistrationPageObject registrationPageObject = new RegistrationPageObject(driver);
        registrationPageObject.init();

        registrationPageObject.phoneNumber.clear();`

`public class RegistrationPageObject extends BasePageObject {
    public RegistrationPageObject(AppiumDriver<MobileElement> driver) {
        super(driver);
    }

    @AndroidFindBy(accessibility = "registration_register_button")
    public MobileElement registerButton;

    @AndroidFindBy(accessibility = "registration_phone_number")
    public MobileElement phoneNumber;

    @AndroidFindBy(accessibility = "registration_country_code")
    public MobileElement selectedCountryCode;

    @AndroidFindBy(accessibility = "registration_country_name")
    public MobileElement countryName;

    @AndroidFindBy(accessibility = "confirm_phone_yes_button")
    public MobileElement phoneConfirmYesButton;

    @AndroidFindBy(accessibility = "confirm_phone_no_button")
    public MobileElement phoneConfirmNoButton;
}
`

## Link to Appium logs
https://gist.github.com/levyshachar2/78edbf48183872223fafc2e92c3330e4

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by daisychainsaw00** [comment]
I'm with appium version 1.6.5，after 
driver.closeApp()
driver.launchApp()
it can also reproduce this issue

so, @levyshachar2  did you restart app via appiumdriver after each test?  I think may this is the real prob?

**Comment by imurchie** [comment]
The problem is in some recent changes. A fix will be forthcoming.

**Comment by levyshachar2** [comment]
Hi , sorry to return to this , but I'm still experiencing the same issue as i reported above.
I updated manually to the latest appium-android-driver (also made sure that the changes are in context.js)

23:19:11 15-01-2018;01:19:05.105 [Thread-15] DEBUG media.muvix.framework.AppiumRunnable - appium :[debug] [MJSONWP] Calling AppiumDriver.getCurrentContext() with args: ["04472226-a970-4f17-a982-22e49745e53f"]
23:19:11 15-01-2018;01:19:05.106 [Thread-15] DEBUG media.muvix.framework.AppiumRunnable - appium :[debug] [MJSONWP] Responding to client with driver.getCurrentContext() result: null

thank you

**Comment by levyshachar2** [comment]
@daisychainsaw00 , does the fix working for you?

**Comment by imurchie** [comment]
You would need to update it in the context of the Appium installation.
```
cd /usr/local/lib/appium
npm install appium-android-driver@1.37.3
```

**Comment by venkatraman91g** [comment]
@imurchie even after updating, still driver.setContext("NATIVE_APP") throws 

[MJSONWP] Encountered internal error running command: TypeError: Cannot read property 'indexOf' of null
    at AndroidDriver.helpers.isChromedriverContext (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/lib/commands/context.js:181:18)
    at AndroidDriver.callee$0$0$ (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/lib/commands/context.js:64:19)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at Promise.F (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at AndroidDriver.callee$0$0 [as switchContext] (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/build/lib/commands/context.js:145:30)
    at AndroidDriver.callee$0$0$ (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/lib/commands/context.js:54:14)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)


**Code To Reproduce:**
driver.closeApp();
driver.startActivity("com.app.clientApp", "com.app.clientApp.Activities.HomActivity");
driver.setContext("NATIVE_APP")

**Comment by Valentine11** [comment]
I use wd 1.8.1 and also reproduce this issue.
Could you tell me please in which folder I should install  appium-android-driver@1.37.3 on Windows?
