### ISSUE TITLE
Original error: Failed to set language: and country: in appium 1.7.2

### ISSUE THREAD

**Issue by lamquangthanh** [appium/appium#9944]
How to fix this issues?

Appium 1.7.2 /Android 7.0
Window 10

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Failed to set language: gb and country:  (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 8.50 seconds
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T18:33:54.468Z'
System info: host: 'DESKTOP-KR7TIVP', ip: '10.161.206.82', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: driver.version: MoziumAndroidDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$new$0(JsonWireProtocolResponse.java:53)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$getResponseFunction$2(JsonWireProtocolResponse.java:91)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:89)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at com.mozium.impl.drivers.MoziumAndroidDriver.execute(MoziumAndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:219)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:142)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:83)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:93)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:72)
	at com.mozium.impl.drivers.MoziumAndroidDriver.<init>(MoziumAndroidDriver.java:21)
	at com.mozium.core.driver.MoziumDriverSetup.start(MoziumDriverSetup.java:89)
	at com.mozium.core.session.TestManager.onTestStart(TestManager.java:146)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1904)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1879)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:685)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

**Comment by mykola-mokhnach** [comment]
Please provide the full Appium server log

**Comment by lamquangthanh** [comment]
[UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original error: 'Command 'D\:\\android-sdk_r24.4.1-windows\\android-sdk-windows\\platform-tools\\adb.exe -P 5037 -s 8a514c6d forward --remove tcp\:8200' exited with code 1'; Stderr: 'error: listener 'tcp:8200' not found'; Code: '1''
[MJSONWP] Encountered internal error running command: Error: Failed to set language: gb and country:
    at Object.callee$0$0$ (C:\Users\Ekino\AppData\Roaming\npm\node_modules\appium\node_modules\appium-android-driver\lib\android-helpers.js:101:11)
    at tryCatch (C:\Users\Ekino\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\Ekino\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\Ekino\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\Ekino\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 8396 ms - 177

**Comment by mykola-mokhnach** [comment]
It looks like the country name is empty and it causes the problem

**Comment by lamquangthanh** [comment]
Hello,
This issues just happened in Appium 1.7.2 (not have in 1.7.1).
And the solution is added new capabilities "country"? Is it right?
Thanks,

**Comment by mykola-mokhnach** [comment]
It's quite possible. try it.

**Comment by KazuCocoa** [comment]
Or use `locale`
https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md

**Comment by lamquangthanh** [comment]
Hello,
Also use locale for config but have the same error. This is log for that:
[MJSONWP] Encountered internal error running command: Error: Failed to set langu                               age: fr and country: fr_CA
    at Object.callee$0$0$ (C:\Users\Ekino\AppData\Roaming\npm\node_modules\appiu                               m\node_modules\appium-android-driver\lib\android-helpers.js:101:11)
    at tryCatch (C:\Users\Ekino\AppData\Roaming\npm\node_modules\appium\node_mod                               ules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\Ekino\AppData\Ro                               aming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:                               315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\U                               sers\Ekino\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\re                               generator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\Ekino\AppData\Roaming\npm\nod                               e_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 12089 ms - 182

**Comment by mykola-mokhnach** [comment]
there is no fr_CA country. Either you set the language to 'fr' and the country to 'CA' or the locale to 'fr-CA' .

**Comment by lamquangthanh** [comment]
[MJSONWP] Encountered internal error running command: Error: Failed to set language: fr and country: CA
    at Object.callee$0$0$ (C:\Users\Ekino\AppData\Roaming\npm\node_modules\appium\node_modules\appium-android-driver\lib\android-helpers.js:101:11)

**Comment by lamquangthanh** [comment]
Not have this issues with appium 1.7.1

**Comment by KazuCocoa** [comment]
Quick investigation.

I've fixed to work them Android 7.0+ => `Change locale cause appium to crash in Android N and O #9619` But I found some cases we should implement more...

Currently, if `io.appium.settings`'s process works and set `locale: 'jp', language: 'JA'`, the feature works fine.

I'll take a look.

----

📝 
- Launch `io.appium.settings` before calling broadcast
    - https://github.com/appium/appium-adb/blob/5c35d7ac6c474b9856c41bc0acd895da5b252fea/lib/tools/apk-utils.js#L598
    - https://github.com/appium/appium-android-driver/blob/master/lib/android-helpers.js#L98
- parsing the capability correctly

**Comment by KazuCocoa** [comment]
📝 
I've created a PR which coordinate the time to install and launch the setting app.
The way to pass `locale: 'JP', language: 'ja'` as capability is correct. We should only update the documentation.

**Comment by lamquangthanh** [comment]
Hello, i try your way **locale: 'JP', language: 'ja'** but have same issues. How to update the latest or way to by pass this issues?

**Comment by KazuCocoa** [comment]
It depends on whether the `io.appium.settings` process is running or not and in most case, the process is not working when Appium try to set locale.
In https://github.com/appium/appium-android-driver/pull/304, the process starts before setting the locale, but before appying the change, you need to launch the app by manual.

**Comment by lamquangthanh** [comment]
and now waiting for next release?

**Comment by KazuCocoa** [comment]
`1.37.1` was released. https://github.com/appium/appium-android-driver/commits/master
So,

1. Specify the new version in your `package.json` if you manage your test environment with `package.json`
2. Wait for the new release if you install the appium with `npm install -g appium`
3. Run `adb am start -W -n io.appium.settings/.Settings -S false -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000` and launch the app once before running Appium.(But in this case, we expect the `io.appium.settings` is installed on the test device.)
