### ISSUE TITLE
Unable to run application in appium 1.7.1

### ISSUE THREAD

**Issue by Amittallewar** [appium/appium#9956]
Hey folks,
Below are the capabilities used :
   DesiredCapabilities cap = new DesiredCapabilities();
		   cap.setCapability(MobileCapabilityType.PLATFORM_NAME, "Android");
		   cap.setCapability(MobileCapabilityType.PLATFORM_VERSION, "7.1.1");
		   cap.setCapability(MobileCapabilityType.NO_RESET, "true");
		   cap.setCapability(MobileCapabilityType.DEVICE_NAME, "motorola");
		   cap.setCapability(AndroidMobileCapabilityType.APP_PACKAGE, "");
		   cap.setCapability(AndroidMobileCapabilityType.APP_ACTIVITY, "");
		 
		  driver = new AndroidDriver(new URL("http://0.0.0.0:4723/wd/hub"),cap);
		   WebDriverWait =new WebDriverWait(driver,30);
		   
		   

## Environment

* Appium version :1.7.1
* Desktop OS/version used to run Appium: windows
* Node.js version :8.9
* Mobile platform/version under test: Android (7.1.1)
* Real device or emulator/simulator: Real Device
*

## Link to Appium logs

[debug] [ADB] Running 'E:\Android_Sdk\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","ZH33B2DN54","shell","am","start","-W","-n","JKMAndroidApp.JKMAndroidApp/md52ca45c06954cb97f1e2dec9f77abd07b.ContactusActivity","-S","-a","android.intent.action.MAIN","-c","android.intent.category.LAUNCHER","-f","0x10200000"]
[debug] [ADB] Running 'E:\Android_Sdk\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","ZH33B2DN54","shell","am","start","-W","-n","JKMAndroidApp.JKMAndroidApp/md52ca45c06954cb97f1e2dec9f77abd07b.ContactusActivity","-S","-a","android.intent.action.MAIN","-c","android.intent.category.LAUNCHER","-f","0x10200000"]
[ADB] Error: Error occured while starting App. Original error: Error executing adbExec. Original error: 'Command 'E\:\\Android_Sdk\\android-sdk-windows\\platform-tools\\adb.exe -P 5037 -s ZH33B2DN54 shell am start -W -n JKMAndroidApp.JKMAndroidApp/md52ca45c06954cb97f1e2dec9f77abd07b.ContactusActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' exited with code 1'; Stderr: 'java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=JKMAndroidApp.JKMAndroidApp/md52ca45c06954cb97f1e2dec9f77abd07b.ContactusActivity } from null (pid=22495, uid=2000) not exported from uid 10179
        at android.os.Parcel.readException(Parcel.java:1684)
        at android.os.Parcel.readException(Parcel.java:1637)
        at android.app.ActivityManagerProxy.startActivityAndWait(ActivityManagerNative.java:3361)
        at com.android.commands.am.Am.runStart(Am.java:634)
        at com.android.commands.am.Am.onRun(Am.java:390)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:51)
        at com.android.commands.am.Am.main(Am.java:122)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:294)'; Code: '1'
    at Object.wrappedLogger.errorAndThrow (C:\Users\admin\AppData\Roaming\npm\node_modules\appium\node_modules\appium-support\lib\logging.js:69:13)
    at ADB.callee$0$0$ (C:\Users\admin\AppData\Roaming\npm\node_modules\appium\node_modules\appium-adb\lib\tools\apk-utils.js:101:9)
    at tryCatch (C:\Users\admin\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\admin\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\admin\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\admin\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at <anonymous>
 Error: Error occured while starting App. Original error: Error executing adbExec. Original error: 'Command 'E\:\\Android_Sdk\\android-sdk-windows\\platform-tools\\adb.exe -P 5037 -s ZH33B2DN54 shell am start -W -n JKMAndroidApp.JKMAndroidApp/md52ca45c06954cb97f1e2dec9f77abd07b.ContactusActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' exited with code 1'; Stderr: 'java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=JKMAndroidApp.JKMAndroidApp/md52ca45c06954cb97f1e2dec9f77abd07b.ContactusActivity } from null (pid=22495, uid=2000) not exported from uid 10179
        at android.os.Parcel.readException(Parcel.java:1684)
        at android.os.Parcel.readException(Parcel.java:1637)
        at android.app.ActivityManagerProxy.startActivityAndWait(ActivityManagerNative.java:3361)
        at com.android.commands.am.Am.runStart(Am.java:634)
        at com.android.commands.am.Am.onRun(Am.java:390)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:51)
        at com.android.commands.am.Am.main(Am.java:122)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:294)'; Code: '1'
    at Object.wrappedLogger.errorAndThrow (C:\Users\admin\AppData\Roaming\npm\node_modules\appium\node_modules\appium-support\lib\logging.js:69:13)
    at ADB.callee$0$0$ (C:\Users\admin\AppData\Roaming\npm\node_modules\appium\node_modules\appium-adb\lib\tools\apk-utils.js:101:9)
    at tryCatch (C:\Users\admin\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\admin\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\admin\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\admin\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at <anonymous>
[debug] [AndroidDriver] Shutting down Android driver

please help

**Comment by mykola-mokhnach** [comment]
You must either grant app permissions or/and fix the activity names.

**Comment by Amittallewar** [comment]
sorry !! i don't get you please explain it

**Comment by Amittallewar** [comment]
Application get invoke manually but if we tried to automate it fails

**Comment by mykola-mokhnach** [comment]
> cap.setCapability(AndroidMobileCapabilityType.APP_PACKAGE, "");
> cap.setCapability(AndroidMobileCapabilityType.APP_ACTIVITY, "");

These capabilities should not be empty and must contain correct values instead.

There is `autoGrantPermissions` capability, which automatically grants application permissions as soon as the app is installed.

**Comment by Amittallewar** [comment]
i'm using this package n activity:

cap.setCapability(AndroidMobileCapabilityType.APP_PACKAGE, "JKMAndroidApp.JKMAndroidApp");
		   cap.setCapability(AndroidMobileCapabilityType.APP_ACTIVITY, "md52ca45c06954cb97f1e2dec9f77abd07b.ContactusActivity");

**Comment by Amittallewar** [comment]
Hey,
Getting the same issue after adding the autograndpermission capabilites

**Comment by mykola-mokhnach** [comment]
it might be that the first application activity is not the same as main activity. In such case the `appWaitActivity` capability should be set. Also, one may use an asterisk '*' to match the activity name that has changeable parts

**Comment by Amittallewar** [comment]
No, main activity and activity name is same .

**Comment by Abmetko** [comment]
I had the same trouble:
java.lang.SecurityException: Permission Denial: starting Intent
I installed 1.8.0-beta3, but it still repro for Android 7.0-8.0, but for 6.0 everything is fine.
How can I resolve this issue?

**Comment by mykola-mokhnach** [comment]
@Abmetko Use UIA2 for Android 6+

**Comment by Abmetko** [comment]
capabilities.setCapability("automationName", "UiAutomator2");
I use it, but it doesn't help.

**Comment by vikramvi** [comment]
@Abmetko  open new issue with appium server log
