### ISSUE TITLE
app is launching in ios iphone 7 simulator and then script is failing.

### ISSUE THREAD

**Issue by sjdptn** [appium/appium#9957]
Versions:
Appium server: 1.7.1 
Eclipse: Oxygen for Java EE developers
Xcode: 9.0
ios Simulator: iPhone 7 (11.0)
Selenium java jars version: 3.8.1

I have written below code/script in eclipse:
package appium;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.testng.annotations.Test;

import io.appium.java_client.ios.IOSDriver;

public class NewTest {
	@SuppressWarnings({ "rawtypes" })
	private IOSDriver driver;

  @SuppressWarnings("rawtypes")
@Test
  public void first() throws MalformedURLException, InterruptedException {
	  DesiredCapabilities caps = new DesiredCapabilities();
	  caps.setCapability("platformName", "iOS");
	  caps.setCapability("platformVersion", "11.0"); 
	  caps.setCapability("deviceName", "iPhone 7"); 
	  caps.setCapability("automationName", "XCUITest");
	  caps.setCapability("app", "/Users/preeti/Library/Developer/Xcode/DerivedData/Kiosk-cqqwwmdzdfarneanaqslqyqicatp/Build/Products/Debug-iphonesimulator/Kiosk.app"); 
	  driver = new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"), caps);
	  driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
	  driver.findElement(By.xpath("//XCUIElementTypeButton[@name=\"SKIP\"]")).click();
	  
	 

}
}

I'm getting the following error in eclipse log:

[RemoteTestNG] detected TestNG version 6.13.1
Jan 11, 2018 1:01:52 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
FAILED: first
java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils
	at io.appium.java_client.HasSessionDetails.lambda$0(HasSessionDetails.java:48)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at com.google.common.collect.CollectSpliterators$1.lambda$forEachRemaining$1(CollectSpliterators.java:115)
	at com.google.common.collect.CollectSpliterators$1.lambda$forEachRemaining$1(CollectSpliterators.java:115)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1696)
	at com.google.common.collect.CollectSpliterators$1.forEachRemaining(CollectSpliterators.java:115)
	at com.google.common.collect.CollectSpliterators$1.forEachRemaining(CollectSpliterators.java:115)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.appium.java_client.HasSessionDetails.getSessionDetails(HasSessionDetails.java:51)
	at io.appium.java_client.HasSessionDetails.getSessionDetail(HasSessionDetails.java:55)
	at io.appium.java_client.HasSessionDetails.getPlatformName(HasSessionDetails.java:62)
	at io.appium.java_client.internal.JsonToMobileElementConverter.<init>(JsonToMobileElementConverter.java:52)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:88)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:93)
	at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:78)
	at appium.NewTest.first(NewTest.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.runSuites(TestNG.java:1028)
	at org.testng.TestNG.run(TestNG.java:996)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.StringUtils
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 45 more

===============================================
    Default test
    Tests run: 1, Failures: 1, Skips: 0
===============================================

===============================================
Default suite
Total tests run: 1, Failures: 1, Skips: 0
===============================================

Log in appium server:
[HTTP] --> GET /wd/hub/session/ffd1f2b6-bb86-491f-8bfa-08ca97154238 {}
[MJSONWP] Calling AppiumDriver.getSession() with args: ["ffd1f2b6-bb86-491f-8bfa-08ca97154238"]
[XCUITest] Executing command 'getSession'
[JSONWP Proxy] Proxying [GET /] to [GET http://localhost:8100/session/0035111A-7755-44DB-AAA4-FEFABAD62EBA] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"sessionId\" : \"0035111A-7755-44DB-AAA4-FEFABAD62EBA\",\n    \"capabilities\" : {\n      \"device\" : \"iphone\",\n      \"browserName\" : \"Delivision Mobile\",\n      \"sdkVersion\" : \"11.0.1\",\n      \"CFBundleIdentifier\" : \"com.ibm.mobilefirst.Kiosk\"\n    }\n  },\n  \"sessionId\" : \"0035111A-7755-44DB-AAA4-FEFABAD62EBA\",\n  \"status\" : 0\n}"
[XCUITest] Merging WDA caps over Appium caps for session detail response
[MJSONWP] Responding to client with driver.getSession() result: {"udid":"411AE598-2210-4806-84E5-7D941673A2F0","app":"/Users/preeti/Library/Developer/Xcode/DerivedData/Kiosk-cqqwwmdzdfarneanaqslqyqicatp/Build/Products/Debug-iphonesimulator/Kiosk.app","automationName":"XCUITest","deviceName":"iPhone 7","platformName":"iOS","platformVersion":"11.0","device":"iphone","browserName":"Delivision Mobile","sdkVersion":"11.0.1","CFBundleIdentifier":"com.ibm.mobilefirst.Kiosk"}
[HTTP] <-- GET /wd/hub/session/ffd1f2b6-bb86-491f-8bfa-08ca97154238 200 64 ms - 480 
[BaseDriver] Shutting down because we waited 60 seconds for a command
[Appium] Closing session, cause was 'New Command Timeout of 60 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'
[Appium] Removing session ffd1f2b6-bb86-491f-8bfa-08ca97154238 from our master session list
[XCUITest] Not changing permissions of '/Users/preeti/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/Attachments' to '755', because the other session does not expect them to be changed
[XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[iOSLog] Stopping iOS log capture

**Comment by mykola-mokhnach** [comment]
> java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils

It is a problem with your client code. Closing as non Appium-related.
