### ISSUE TITLE
Error: Unable to launch WebDriverAgent because of xcodebuild failure

### ISSUE THREAD

**Issue by denysvoskovets** [appium/appium#9960]
## The problem

Updated desktop Appium version from 1.7.1 to 1.7.2. It asked to move Appium into Application folder(I moved). After that it doesn't work. I'm receiving this error in logs but i'm not clearly understand how to fix it. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Desktop OS/version used to run Appium: MacOs Sierra 10.12.6
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Simulator iPhone6s 11.2
* Appium CLI or Appium.app|exe:

## Details
Error:
Error: Unable to launch WebDriverAgent because of xcodebuild failure: "ENOENT: no such file or directory, open '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/PrivateHeaders/XCTest/XCUICoordinate.h'".
    at XCUITestDriver.quitAndUninstall$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:375:13)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at 
 Error: Unable to launch WebDriverAgent because of xcodebuild failure: "ENOENT: no such file or directory, open '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/PrivateHeaders/XCTest/XCUICoordinate.h'".
    at XCUITestDriver.quitAndUninstall$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:375:13)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at 

## Link to Appium logs
Logs attached. 

https://gist.github.com/denysvoskovets/739d7cf7b55f0994c76c1b3bfc36fe94

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/appium/appium-desktop/issues

**Comment by dpgraham** [comment]
This is a known issue. https://github.com/appium/appium-desktop/issues/378

**Comment by aravindanath** [comment]
Even I had faced the same issue, got resolved
try this below command:--

cd /Applications/Appium.app/Contents/Resources/app ; npm install

**Comment by ashwinibaisutrave** [comment]
I am facing the same issue with latest 1.3.2 as well used the above workaround and got this error 
<img width="1680" alt="screen shot 2018-02-07 at 11 07 03" src="https://user-images.githubusercontent.com/28534028/35913310-1ec68e22-0bf7-11e8-96c3-a1add476fadf.png">


previous error before work around .
error
[XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: "ENOENT: no such file or directory, open '/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent/PrivateHeaders/XCTest/XCUICoordinate.h'".
    at XCUITestDriver.quitAndUninstall$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/lib/driver.js:387:13)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
