### ISSUE TITLE
Failure to get page_source when moving from hybrid app to safari 

### ISSUE THREAD

**Issue by derek-phillips-hp** [appium/appium#9965]
## The problem

Getting ProxyRequestError: Socket hang up(Xcode 8.3.3) or "Cannot get '(null)' source of the current application"(Xcode 9.2)  when calling for the page_source after moving from the hybrid app to safari on iPhone. 

## Environment

* Appium version: 1.7.1 and 1.7.2
* iOS: 10.2 and 10.3.3
* Node.js version: 9.4.0
* iPhone 7 (10.3.3) and iPhone 6+ (10.2) 
* 1.7.1 from Appium.app, 1.7.2 with npm install
* Python

## Details

In my app, I was trying to verify that a button opened the correct url once it was clicked, but was failing to verify elements on the Safari browser.

With Appium 1.7.1 and Xcode 8.3.3 I would get the Socket hang up error if I called for page_source as soon as the linked was clicked. I would also loop for a new page_source if I got the bad response, but still got the same error response. 
However, if I hard sleep for 20 seconds then called for the page_source I would get it and be able to continue the test. 

With Appium 1.7.2 and Xcode  9.2 I would get the 'null' source issue when calling for page_source right after clicking on the link. I would also get the 'null' source issue when i called for the page_source after sleeping for 20 seconds. 

## Appium logs

```
##Appium 1.7.2 Xcode 9.2
[debug] [MJSONWP] Calling AppiumDriver.getPageSource() with args: ["404b37f5-954d-406c-ab66-a5db9552f391"]
[debug] [XCUITest] Executing command 'getPageSource'
[debug] [JSONWP Proxy] Proxying [GET /source] to [GET http://localhost:8100/session/918E9974-64CD-4A08-B3ED-408DC47CFF1B/source] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"Cannot get '(null)' source of the current application\",\n  \"sessionId\" : \"918E9974-64CD-4A08-B3ED-408DC47CFF1B\",\n  \"status\" : 13\n}"
[MJSONWP] Encountered internal error running command: Error: An unknown server-side error occurred while processing the command.
    at JWProxy.command$ (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:176:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
[HTTP] <-- GET /wd/hub/session/404b37f5-954d-406c-ab66-a5db9552f391/source 500 285 ms - 238 
[HTTP] --> GET /wd/hub/session/404b37f5-954d-406c-ab66-a5db9552f391/source {}

```
```
Appium 1.7.1 Xcode 8.3.3

[debug] [MJSONWP] Calling AppiumDriver.getPageSource() with args: ["cc1f0390-356a-4100-b763-fbb6c896472f"]
[debug] [XCUITest] Executing command 'getPageSource'
[debug] [JSONWP Proxy] Proxying [GET /source] to [GET http://localhost:8100/session/1671EB10-4B82-4668-A27B-5F450442B52E/source] with no body
[error] [MJSONWP] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: Error: socket hang up    
	at JWProxy.proxy$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:152:13)    
	at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)    
	at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)    
	at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
	at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[info] [HTTP] <-- GET /wd/hub/session/cc1f0390-356a-4100-b763-fbb6c896472f/source 500 198 ms - 250 
[info] [HTTP] --> GET /wd/hub/session/cc1f0390-356a-4100-b763-fbb6c896472f/source {}
```

**Comment by mykola-mokhnach** [comment]
You could try to get the [`description` source](https://github.com/mykola-mokhnach/appium/blob/38e2791dae203258dad3f33bc012963ad30ad2d2/docs/en/writing-running-appium/ios/ios-xctest-source.md) as a workaround. The upcoming Appium beta might address such issues.
