### ISSUE TITLE
Encountered internal error running command: InvalidArgumentError: The capabilities argument was not valid for the following reason(s): "capabilities" must be a JSON object

### ISSUE THREAD

**Issue by yefankongge** [appium/appium#9981]
## The problem

The appium version I used before was 1.6.5, run normal.and then upgraded to 1.7.1 and 1.7.2. This problem occurred. Then I downgraded the version to 1.6.5, which still has this problem.
## Environment

* Appium version (or git revision) that exhibits the issue:1.6.5
* Last Appium version that did not exhibit the issue (if applicable):1.6.5
* Desktop OS/version used to run Appium:mac 10.12.6
* Node.js version (unless using Appium.app|exe):7.2.1
* Mobile platform/version under test:Android 5.0.1
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: The capabilities argument was not valid for the following reason(s): "capabilities" must be a JSON object. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 226 milliseconds
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'yefandeMacBook-Pro.local', ip: '172.17.63.37', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_101'
Driver info: io.appium.java_client.android.AndroidDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:40)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:249)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:36)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:114)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:132)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:92)
	at com.mogujie.qa.AppDriver.<init>(AppDriver.java:50)
	at com.mogujie.qa.AppDriver.getInstance(AppDriver.java:90)
	at com.mogujie.qa.testcase.TestBase.beforeSuite(TestBase.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:298)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
java.lang.NullPointerException
	at com.xxx.qa.testcase.TestBase.beforeSuite(TestBase.java:56)
## Link to Appium logs

[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/yefan/Documents/code/test/UIAutomation_Android/src/main/resources/apk/08081043NAMInnerTest-809-release.apk","noReset":true,"autoLaunch":true,"newCommandTimeout":"120","platformVersion":"5.0.2","appWaitPackage":"com.xxx","appWaitActivity":"com.xxx.host.MGIndexAct","unicodeKeyboard":"True","platformName":"Android","deviceName":"e80ad498","resetKeyboard":"True"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/yefan/Documents/code/test/UIAutomation_Android/src/main/resources/apk/08081043NAMInnerTest-809-release.apk","noReset":true,"autoLaunch":true,"newCommandTimeout":"120","platformVersion":"5.0.2","appWaitPackage":"com.xxx","appWaitActivity":"com.xxx.host.MGIndexAct","unicodeKeyboard":"True","platformName":"Android","deviceName":"e80ad498","resetKeyboard":"True"},null,null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1515990440907 (12:27:20 GMT+0800 (CST))
[Appium] Creating new AndroidDriver (v1.37.2) session
[Appium] Capabilities:
[Appium]   app: '/Users/yefan/Documents/code/test/UIAutomation_Android/src/main/resources/apk/08081043NAMInnerTest-809-release.apk'
[Appium]   noReset: true
[Appium]   autoLaunch: true
[Appium]   newCommandTimeout: '120'
[Appium]   platformVersion: '5.0.2'
[Appium]   appWaitPackage: 'com.xxx'
[Appium]   appWaitActivity: 'com.xxx.host.MGIndexAct'
[Appium]   unicodeKeyboard: 'True'
[Appium]   platformName: 'Android'
[Appium]   deviceName: 'e80ad498'
[Appium]   resetKeyboard: 'True'
[debug] [AndroidDriver] Shutting down Android driver
[debug] [AndroidDriver] Called deleteSession but bootstrap wasn't active
[MJSONWP] Encountered internal error running command: InvalidArgumentError: The capabilities argument was not valid for the following reason(s): "capabilities" must be a JSON object.
    at parseCaps (../../../lib/basedriver/capabilities.js:115:11)
    at processCapabilities (../../../lib/basedriver/capabilities.js:185:43)
    at AndroidDriver.callee$0$0$ (../../../../lib/basedriver/commands/session.js:17:5)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:185:17)
    at F (/usr/local/lib/node_modules/appium/node_modules/._core-js@1.2.7@core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:209:12)
    at AndroidDriver.callee$0$0 [as createSession] (../../../../lib/basedriver/commands/session.js:16:11)
    at AndroidDriver.createSession$ (../../lib/driver.js:31:20)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:185:17)
    at F (/usr/local/lib/node_modules/appium/node_modules/._core-js@1.2.7@core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:209:12)
    at AndroidDriver.createSession (../../lib/driver.js:163:27)
    at AppiumDriver.createSession$ (../../lib/appium.js:183:43)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:185:17)
    at F (/usr/local/lib/node_modules/appium/node_modules/._core-js@1.2.7@core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/._babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:209:12)
[HTTP] <-- POST /wd/hub/session 500 48 ms - 245 

## Code To Reproduce Issue [ Good To Have ]

File app = new File(System.getProperty("user.dir") + "/src/main/resources/apk/", ConfigUtils.getString("app"));
            capabilities.setCapability("unicodeKeyboard", ConfigUtils.getString("unicodeKeyboard"));
            capabilities.setCapability("resetKeyboard", ConfigUtils.getString("resetKeyboard"));
            capabilities.setCapability("autoLaunch", ConfigUtils.getBoolean("autoLaunch"));
            capabilities.setCapability("deviceName", AdbUtils.getFirstDevice());
            capabilities.setCapability("platformVersion", AdbUtils.getFirstDeviceVersion());
            capabilities.setCapability("app", app.getAbsolutePath());
            capabilities.setCapability("appWaitPackage", ConfigUtils.getString("appPackage"));
            capabilities.setCapability("appWaitActivity", ConfigUtils.getString("appActivity"));
            capabilities.setCapability("noReset", ConfigUtils.getBoolean("noReset"));
            capabilities.setCapability("newCommandTimeout", ConfigUtils.getString("newCommandTimeout"));
            //capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.ANDROID_UIAUTOMATOR2);
            try {
                driver = new AndroidDriver<>(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
                Thread.sleep(10000);
            } catch (Exception e) {
                e.printStackTrace();
            }

**Comment by mykola-mokhnach** [comment]
Update selenium api/ java client to the most recent version. The one you have (2.53) is not compatible to Appium 1.7

**Comment by yefankongge** [comment]
@mykola-mokhnach I just upgraded 1.7.2, and then uninstalled, reinstall the appium 1.6.5 version

**Comment by levyshachar2** [comment]
@mykola-mokhnach , is java-client 4.1.2  supported with appium 1.7.2?

**Comment by mykola-mokhnach** [comment]
@levyshachar2 If your selenium api lib version for java is lower than 3.7 then the stuff is not going to work properly

**Comment by mykola-mokhnach** [comment]
For the recent Appium beta the api version should be at 3.7+

**Comment by levyshachar2** [comment]
I just updated to latest java-client version , 6.0.0-BETA2 , which according to their website "selenium:selenium-java was updated to 3.8.1"
but i'm still getting issue with "capabilities" must be a JSON object."

**Comment by sytolk** [comment]
The problem is in this commit: https://github.com/appium/appium-base-driver/pull/171

**Comment by sytolk** [comment]
https://github.com/appium/appium/issues/9984#issuecomment-358030369
