### ISSUE TITLE
IOS 11 unable to take Screenshot with Appium 1.7.1

### ISSUE THREAD

**Issue by samnit** [appium/appium#9999]
I am using the below code to take screenshot using appium driver but getting error on IOS 11 although same code is working on IOS 10 Device. Can you please suggest a workaround or resolvance for the same..
```java
private static String takeScreenshot(AppiumDriver driver) throws IOException, HeadlessException, AWTException  { 
		try { 
			File screenshot = ((TakesScreenshot)driver).getScreenshotAs(OutputType.FILE); 
			BufferedImage screenshotBase64=ImageIO.read(screenshot); 
			ByteArrayOutputStream os = new ByteArrayOutputStream(); 
	     ImageIO.write(screenshotBase64, "png", Base64.getEncoder().wrap(os)); 
	     return os.toString(StandardCharsets.ISO_8859_1.name()); 


		} catch (Exception e) { 
			e.printStackTrace();
			return ""; 
		} 

	}
```
And the error I am facing is  : -
```
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Unable to take screenshot. WDA returned '{}' (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 5.96 seconds
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'INNOSZPC01062', ip: '10.13.67.1', os.name: 'Windows 8.1', os.arch: 'x86', os.version: '6.3', java.version: '1.8.0_40'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{BrowserName=, LocationContextEnabled=false, DeviceConnectApiVersion=0.0, DeviceConnectApiKey=57949f28-ada0-4e39-9abc-4b76754bcc1e, DeviceConnectSkipResigning=false, Platform=MAC, DeviceConnectChromeDriverVerbose=false, JavascriptEnabled=true, bundleId=com.att.osd.dev.myAtt, deviceName=deviceConnect’s iPhone, platform=ANY, TakesScreenshot=true, webDriverAgentUrl=http://127.0.0.1:23153/, DeviceConnectIgnoreSession=true, newCommandTimeout=180.0, automationName=XCUITest, javascriptEnabled=true, DatabaseEnabled=false, DeviceConnectSkipInstall=false, WebStorageEnabled=false, platformName=iOS, udid=1063e9f183eb961a68ba3d45afa1d46b52c8ee6f, DeviceConnectUsername=st217s@att.com}]
Session ID: b4d1d8ef-5cb8-4ccd-935d-38f430a00c0e
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:167)
```

**Comment by imurchie** [comment]
Can you provide the Appium server log, as a link to a [gist](https://gist.github.com)?

Upgrading to Appium 1.7.2 might help as well.
